### ISSUE TITLE
Homebrew/core Travis CI fails to test formula.

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/brew#100]
I just found out that the Travis CI job on Homebrew/core didn't do any formula test for each git push. Instead, it only run `brew tests`. As result, none of recent Homebrew/core git push has been double tested by CI bot.

**Comment by mikemcquaid** [comment]
Nice find.

**Comment by xu-cheng** [comment]
So it appears it has stopped to work since the core/formula split.

**Comment by xu-cheng** [comment]
I'm debuging this on my own repo. And I'm pretty sure this tap resolution is not the cause.

**Comment by mikemcquaid** [comment]
Cool thanks @xu-cheng

**Comment by UniqMartin** [comment]
@xu-cheng My feeling after looking at the Travis logs is that there's some issue with copying the `homebrew/core` repository into the right place, because of [this `brew config` output](https://travis-ci.org/Homebrew/homebrew-core/builds/124101284#L122). Have you looked at the `before_install` steps in the `.travis.yml` and checked for issues there?

**Comment by xu-cheng** [comment]
FYI, I have identity at least one bug in `.travis.yml`:  the rsync command fails to set up the proper repo. But only fixing this rsync problem does not fully fix the bug described in the issue. So I'm still investigating.

**Comment by xu-cheng** [comment]
The second problem I found is git reports `fatal: Not a valid object name <start-sha1>`. Seems to be a Travis bug to me, as I don't know how to fix this.

I will push the fix for `rsync` problem first.

**Comment by mikemcquaid** [comment]
It may just be worth removing the `rsync` stuff altogether and doing a full new re-tap/pull for now until you get it working.

**Comment by xu-cheng** [comment]
So it appears that https://github.com/Homebrew/homebrew-core/commit/dbf25c038e3da6e2669831a21f7f64878fab14a9 has fixed this issue. The git problem could be a temporary thing.

**Comment by mikemcquaid** [comment]
👍
