### ISSUE TITLE
Every command results in Error: undefined method `downcase' for #<Pathname:gtk+>

### ISSUE THREAD

**Issue by Moddus** [Homebrew/brew#1000]
Hi,
I've uninstalled gtk+ today and every ```brew <command>``` shows the following message since then. Could someone please help?

```
Error: undefined method `downcase' for #<Pathname:gtk+>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:349:in `core_path'
/usr/local/Library/Homebrew/formulary.rb:301:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:219:in `factory'
/usr/local/Library/Homebrew/utils.rb:637:in `rescue in rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:634:in `rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:631:in `block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:629:in `each'
/usr/local/Library/Homebrew/utils.rb:629:in `migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by causlayer** [comment]
The same problem，open terminal：
Error: undefined method `downcase' for #<Pathname:pyside>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:349:in `core_path'
/usr/local/Library/Homebrew/formulary.rb:301:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:219:in `factory'
/usr/local/Library/Homebrew/utils.rb:637:in `rescue in rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:634:in `rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:631:in `block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:629:in `each'
/usr/local/Library/Homebrew/utils.rb:629:in `migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'

**Comment by zmwangx** [comment]
Thanks for the helpful report, #1003 should fix this.

**Comment by causlayer** [comment]
@zmwangx Thank you,My problem has been solved.

**Comment by zmwangx** [comment]
@causlayer You mean without #1003?

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/pull/1003 has shipped. Please update, and this should be fixed.
