### ISSUE TITLE
`brew cleanup -s` cleans opposite cache on ARM/M1

### ISSUE THREAD

**Issue by johnalanwoods** [Homebrew/brew#10038]
# Bug report

Unusual issue I noticed today...

I have Intel and ARM home-brew install, in usual locations, Intel at `/usr/local/bin` ARM at `/opt/homebrew`.

I was cleaning my caches using `arch -x86_64 /usr/local/bin/brew cleanup -s` and `/opt/homebrew/bin/brew cleanup -s`...

Here's the weirdness:

* running ARM brew cleanup cleans Intel brew formula & cask caches!
* running Intel brew cleanup cleans ARM brew formula & cask caches!

So it's as if, the `cleanup -s` command is pointed at the alternate installs caches.

I have tested multiple times on two machines same results.

so let me illustrate, say I have both ARM and Intel brew installed, but no formulas or casks yet.

Then, say I use Intel brew to install a formula and cask:

`arch -x86_64 /usr/local/bin/brew install exa` <-- exa formula
`arch -x86_64 /usr/local/bin/brew install --cask authy` <-- authy cask

Then, running Intel cleanup `arch -x86_64 /usr/local/bin/brew cleanup -s`, nothing will be cleaned.

As soon as I run `/opt/homebrew/bin/brew cleanup -s` (ARM cleanup), I see brew purge both the exa formula and authy cask.

Vice versa, if I installed both with ARM brew, then running ARM cleanup wouldn't work. I would need to run Intel cleanup to scrub the ARM cache.

I have tested this multiple times, and if I install different formulas and casks with both Intel or ARM brew, then to clean the caches for Intel I need to use ARM brew, and to clean the cache for ARM, I have to use Intel brew.

Very strange indeed if they are using the same cache!

I first noticed when I ran ARM brew cleanup, and I saw it purge ONLY Intel installed stuff, then I began testing to verify this behaviour.

- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Clean caches on multi-brew machine with `brew cleanup -s`

## What happened (include command output)

Intel cache cleaned by ARM command, ARM cache cleaned by Intel command.

## What you expected to happen

Intel cache cleaned by Intel command, ARM cache cleaned by ARM command.

## Step-by-step reproduction instructions (by running `brew` commands)

As above.

## Output of `brew config` and `brew doctor` commands

ARM brew:

```
HOMEBREW_VERSION: 2.6.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1a52862e6d24cd3bf87bec557a8886a1a825ee3c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 63d446907dfc28301542d9f2832b41df737ecefe
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: N/A
Xcode: 12.3
Rosetta 2: false
```

Intel brew:
```
HOMEBREW_VERSION: 2.6.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1a52862e6d24cd3bf87bec557a8886a1a825ee3c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 63d446907dfc28301542d9f2832b41df737ecefe
Core tap last commit: 25 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit westmere
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: N/A
Xcode: 12.3
Rosetta 2: true
```

**Comment by MikeMcQuaid** [comment]
> As soon as I run `/opt/homebrew/bin/brew cleanup -s` (ARM cleanup), I see brew purge both the exa formula and authy cask.

Can we see the actual output of this command? It'd help understand what's going on here. Thanks!

**Comment by johnalanwoods** [comment]
@MikeMcQuaid sure! Happy to help :)

Hope this helps:

```
john@Tempest ~ % arch -x86_64 /usr/local/bin/brew list
john@Tempest ~ % arch -x86_64 /usr/local/bin/brew install exa
==> Downloading https://homebrew.bintray.com/bottles/exa-0.9.0_1.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/3ee8e461f50fa870cd035a44ba9973e26192953e235adef9d2936f2bdab0b1d3?response-content-disposition=attachment%3Bfilename%3D%22exa-0.9.0_1.big_sur.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbn
######################################################################## 100.0%
==> Pouring exa-0.9.0_1.big_sur.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/exa/0.9.0_1: 11 files, 1.4MB
john@Tempest ~ % /opt/homebrew/bin/brew list
libsodium
coconutbattery                                  daisydisk                                       geekbench                                       iterm2                                          rectangle
john@Tempest ~ % arch -x86_64 /usr/local/bin/brew list
exa
john@Tempest ~ % /opt/homebrew/bin/brew cleanup -s
Removing: /Users/john/Library/Caches/Homebrew/exa--0.9.0_1.big_sur.bottle.tar.gz... (658.2KB)
john@Tempest ~ %
```

**Comment by MikeMcQuaid** [comment]
`brew cleanup -s` will always do this because it cannot look at the installed state of both installations because it only "knows" about one. If `brew cleanup` (without `-s`) does the same: we'll consider fixing (and reopening).

**Comment by johnalanwoods** [comment]
@MikeMcQuaid ok, but if it only knows about one, why does Intel clean ARM, and ARM clean Intel?

**Comment by carlocab** [comment]
That's the point:

ARM `brew` knows only about installed ARM kegs, while Intel `brew` knows only about installed Intel kegs. In order for ARM (Intel) `brew` to avoid removing Intel (ARM) tarballs with `brew cleanup -s`, then ARM (Intel) `brew` would need to know about both installations.

**Comment by johnalanwoods** [comment]
@carlocab  - got it thanks!
