### ISSUE TITLE
Error: undefined method sort_by for nil:NilClass when running `brew livecheck`

### ISSUE THREAD

**Issue by johndbritton** [Homebrew/brew#10052]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? (I fixed all but one, don't think it's related and don't want to break pyenv)
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Update an app to the latest version from it's appcast URL.

I tried running `brew livecheck` because it sounded like something that could help.

## What happened (include command output)

I wasn't sure what the command would do, but it produced an error: "Undefined method `sort_by` for nil:NilClass" which I think is unexpected. The error message told me to report the issue.

<details>
  <summary>Command output</summary>
  <pre>
± brew livecheck
Error: undefined method `sort_by' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/livecheck.rb:98:in `livecheck'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
  </pre>
</details>

I then ran `brew help livecheck` to find what arguments were needed. Running `brew livecheck [formula|cask]` works as expected.

## What you expected to happen

A help message, or successful run of the command with some output.

## Step-by-step reproduction instructions (by running `brew` commands)

1. run `brew livecheck` with no arguments
2. experience error

## Output of `brew config` and `brew doctor` commands

<pre>
± brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/john/.pyenv/shims/python3.9-config
  /Users/john/.pyenv/shims/python-config
  /Users/john/.pyenv/shims/python3-config

± brew config
HOMEBREW_VERSION: 2.6.2-91-g9db324a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9db324ab7a28446debcb407859c9ac184594a772
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 702b00164b283971d745def9ae33bdc453e9b2e3
Core tap last commit: 46 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: atom -w
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: N/A
Xcode: 12.3
</pre>

**Comment by samford** [comment]
We fixed this error in #10054 and improved the error message when a watchlist file isn't present.

To explain, `brew livecheck` doesn't update formulae/casks. It's sole purpose is to identify new versions from upstream sources. Livecheck's data is consumed by other tools and the eventual goal is to have tooling to make it easier to bump a version when we detect a new one but `brew livecheck` itself will never do this.

**Comment by johndbritton** [comment]
Yes, this is resolved for me. Thank you.

> Hopefully this does a better job of pointing you in the right direction than our more generic Error: Invalid usage: No formulae or casks to check. error (which you would have normally seen if not for this bug).

This is the key. The error message before was not really helpful for me gaining an understanding of what `livecheck` does. 

>  It's sole purpose is to identify new versions from upstream sources. Livecheck's data is consumed by other tools and the eventual goal is to have tooling to make it easier to bump a version when we detect a new one but brew livecheck itself will never do this.

Ultimately I was using livecheck to bump a formula version and submit a PR to `homebrew-cask`. This is in line with expectations.

> the eventual goal is to have tooling to make it easier to bump a version when we detect a new one

Really looking forward to this.
