### ISSUE TITLE
Request: Update tintin to 2.01.1

### ISSUE THREAD

**Issue by dragonpaw** [Homebrew/brew#1006]
Tintin++ added ssl support in 2.01.1, their final release. It would be nice to update the install to that version.

**Comment by zmwangx** [comment]
> their final release

What, did they say this will be their final release? Or do you mean "their latest release"?

**Comment by dragonpaw** [comment]
Fair point. It's the release from last year which was the only release we've seen from them since 2013. Regardless, getting a version with ssl support into Brew would be nice.

**Comment by zmwangx** [comment]
> Fair point.

I was not making a point, I was asking a question...

If it's the final release, I would seriously consider boneyarding it. Carrying unsupported software isn't nice, and this one is among the "used by almost no one" camp anyway according to our analytics.

If they did not say it's the final release, then sure.

Can you try to open a PR?

**Comment by dragonpaw** [comment]
Sorry but I'm not in a position to do the work myself.

**Comment by zmwangx** [comment]
Is there any difficulty? It should be [pretty easy](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md). Homebrew relies on contributions to thrive; we as a small team can't maintain thousands of packages on our own.

**Comment by zmwangx** [comment]
Closing the issue because we don't keep this sort of requests open. Someone, either you or one of us, should open a PR, and that's the only way forward in Homebrew land.
