### ISSUE TITLE
superenv does not strip -march arguments at configure time.

### ISSUE THREAD

**Issue by ggouaillardet** [Homebrew/brew#10078]
This issue was initially found and discussed at Homebrew/homebrew-core#65296.
It is not related to the build failure of Homebrew/homebrew-core#67221.
FWIW, workaround(s) (only for Open MPI) are being discussed at open-mpi/ompi#8306

In a nutshell, Open MPI tries to compile a file with `AVX512` intrinsics at `configure` time.
It is a success when the `-march=skylake-avx512` option is passed to the `C` compiler.
At `make` time, such a file is compiled with the very same option.
Alas, they are stripped out by `superenv` and replaced with `-march=nehalem`, which prevents the use of `AVX512` intrinsics and cause the build failure.

This would have not happened if `superenv` did also replace `-march=skylake-avx512` with `-march=nehalem` at `configure` time (since Open MPI would have correctly handled that `AVX512` intrinsics cannot be used).

Bottom line, `superenv` has a different behavior at `configure` and `make` time, and this is causing the build failure. At this stage, my conclusion is this is a bug.

In order to avoid being distracted from the issue I am reporting, let me be clear that
 - I am not suggesting by any mean that `superenv` should not use `-march=nehalem` at `make` time (e.g. I fully understand why you chose to build nehalem only binaries so they can run on the most common x86 processors).
 - In the case of Open MPI, a single object file is built with `AVX512` instructions,  we test for `AVX512` support by the CPU at runtime, and `AVX512` code is only invoked if supported. This means that an Open MPI package/bottle built with a `AVX512` capable compiler will run just fine on an "old" and non `AVX512` capable processor (my understanding is that this is fully in line with brew's expectations).

**Comment by ggouaillardet** [comment]
This is an extract from https://github.com/Homebrew/homebrew-core/suites/1695183648/artifacts/31905273 (logs of Homebrew/homebrew-core#67221)

From `01.configure.cc`:
```
clang called with: -o conftest -O3 -DNDEBUG -finline-functions -fno-strict-aliasing -march=skylake-avx512 -I/usr/local/opt/libevent/include -I/usr/local/include -I/usr/local/include -Wl,-flat_namespace -L/usr/local/opt/libevent/lib conftest.c -lz -lhwloc -levent_core -levent_pthreads
superenv added:    -pipe -Os -march=nehalem -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2 -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl@1.1/include -L/usr/local/opt/openssl@1.1/lib -L/usr/local/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=nehalem -o conftest -O3 -DNDEBUG -finline-functions -fno-strict-aliasing -march=skylake-avx512 -I/usr/local/opt/libevent/include -I/usr/local/include -I/usr/local/include -Wl,-flat_namespace -L/usr/local/opt/libevent/lib conftest.c -lz -lhwloc -levent_core -levent_pthreads -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2 -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl@1.1/include -L/usr/local/opt/openssl@1.1/lib -L/usr/local/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
```

`clang` was called with `-march=skylake-avx512`, `superenv` executed `clang -march=skylake-avx512`.


but from `02.make.cc`

```
clang called with: -DHAVE_CONFIG_H -I. -I../../../../opal/include -I../../../../ompi/include -I../../../../oshmem/include -I../../../../opal/mca/hwloc/hwloc201/hwloc/include/private/autogen -I../../../../opal/mca/hwloc/hwloc201/hwloc/include/hwloc/autogen -I../../../../ompi/mpiext/cuda/c -DGENERATE_SSE3_CODE -DGENERATE_SSE41_CODE -DGENERATE_AVX_CODE -DGENERATE_AVX2_CODE -DGENERATE_AVX512_CODE -I../../../.. -I../../../../orte/include -I/usr/local/opt/libevent/include -I/usr/local/include -I/usr/local/include -march=skylake-avx512 -O3 -DNDEBUG -finline-functions -fno-strict-aliasing -c op_avx_functions.c -fno-common -DPIC -o .libs/liblocal_ops_avx512_la-op_avx_functions.o
superenv removed:  -I/usr/local/include -I/usr/local/include -march=skylake-avx512 -O3
superenv added:    -pipe -w -Os -march=nehalem -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2 -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl@1.1/include
superenv executed: clang -pipe -w -Os -march=nehalem -DHAVE_CONFIG_H -I. -I../../../../opal/include -I../../../../ompi/include -I../../../../oshmem/include -I../../../../opal/mca/hwloc/hwloc201/hwloc/include/private/autogen -I../../../../opal/mca/hwloc/hwloc201/hwloc/include/hwloc/autogen -I../../../../ompi/mpiext/cuda/c -DGENERATE_SSE3_CODE -DGENERATE_SSE41_CODE -DGENERATE_AVX_CODE -DGENERATE_AVX2_CODE -DGENERATE_AVX512_CODE -I../../../.. -I../../../../orte/include -I/usr/local/opt/libevent/include -DNDEBUG -finline-functions -fno-strict-aliasing -c op_avx_functions.c -fno-common -DPIC -o .libs/liblocal_ops_avx512_la-op_avx_functions.o -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2 -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl@1.1/include
```

`clang` was also called with `-march=skylake-avx512` but this was removed by `superenv`, and `superenv` finally executed `clang -march=nehalem`

**Comment by ggouaillardet** [comment]
tagging @fxcoudert

**Comment by jonchang** [comment]
We purposely don't do this at configure time by default, but individual formulae can opt into it by calling `ENV.refurbish_args`. See https://web.archive.org/web/20190629052436/https://github.com/Homebrew/homebrew-versions/issues/364 for the reasoning why.

**Comment by ggouaillardet** [comment]
Thanks for the pointer.

I added `ENV.refurbish_args` right after `def install`, but unfortunately, I observe the very same behavior:
 - `-march=skylake-avx512` is passed at `configure` time
 - `-march=skylake-avx512` is replaced with `-march=nehalem` at `make` time.

did I miss something? meanwhile, shall I reopen this issue?

**Comment by jonchang** [comment]
That suggests that the build system is bypassing Homebrew's superenv shims, so that would be the place to look for e.g. absolute paths to clang or make.

**Comment by ggouaillardet** [comment]
`01.configure.cc` and `02.make.cc` make it clear that `superenv` is being used. Unfortunately, it has different behaviors. In both cases, `clang` is being used, no absolute path.
