### ISSUE TITLE
Doctor: false positive for pre-commit-validate-config

### ISSUE THREAD

**Issue by memeplex** [Homebrew/brew#10071]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Some python scientific packages still don't work quite well with current brew python version (3.9), so I also installed 3.8. In order not to interfere with brew installation I created a virtual environment for my stuff, which I want to be active or at least in the PATH during my shell sessions. One dependency I need in the environment is pre-commit, which unfortunately installs a pre-commit-validate-config script that makes `brew doctor` think it's a "config" script.

I know it's just a warning, but if you keep a list of exceptions somewhere then`pre-commit-validate-config` goes there. If not, ignore me.

## What happened (include command output)

<details>
  <summary>Command output</summary>

  The `brew doctor` output pasted below.
</details>

## What you expected to happen

`brew doctor` ends without warnings.

## Step-by-step reproduction instructions (by running `brew` commands)

1. `brew install python@3.8`
2. `brew install python@3.9`
3. `cd /tmp`
3. `/usr/local/Cellar/python@3.8/3.8.6_2/bin/python3 -m venv Test`
4. `source /tmp/Test/bin/activate`
5. `pip install pre-commit`
6. `deactivate`
7.  `export PATH=/tmp/Test/bin:$PATH`
8. `brew doctor`

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.6.2-134-g24046c3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 24046c3182301aeed7d6de7228bc30bfc7d712bd
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 45a2950c6fe2bda18b9e4aa77aa551c2e6775002
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
</pre>

<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/carlos/Base/Venvs/Base/bin/pre-commit-validate-config
</pre>

**Comment by MikeMcQuaid** [comment]
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry or file an issue; just ignore this. Thanks!

**Comment by memeplex** [comment]
Yep, I had read that but I thought improving the FPR could be of some worth to you.

**Comment by carlocab** [comment]
It would be nice to not have it, but I'm not certain it would be a maintainer priority. Perhaps you'd like to open a PR to improve it?

**Comment by MikeMcQuaid** [comment]
> Yep, I had read that

Please next time both read it and do what it says, thanks.

> he FPR could be of some worth to you.

We don't consider this a false-positive.

**Comment by memeplex** [comment]
> It would be nice to not have it, but I'm not certain it would (or should) be a maintainer priority. Perhaps you'd like to open a PR to improve it?

I don't feel inclined to do so after the display of unnecessary harshness. And, in any case, I must conclude that as it is all is for the best in this best of all possible worlds. 

Thank you for your answers, anyway.
