### ISSUE TITLE
Compinit: insecure directories on MacOS catalina

### ISSUE THREAD

**Issue by thesyntaxinator** [Homebrew/brew#10070]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew install any module

## What happened (include command output)

Running brew install requires the current user to have ownership of /usr/local/share/zsh and /usr/local/share/zsh/site-functions.  However this causes a compinit warning re insecure directories when opening a terminal shell (zsh by default) on macOS Catalina. Setting ownership back to root for the above directories removes this warning but causes brew to fail when attempting to install a module.

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

Brew install should just work without causing the compinit warning when opening a terminal window.

## Step-by-step reproduction instructions (by running `brew` commands)

See above

## Output of `brew config` and `brew doctor` commands

<pre>

</pre>

**Comment by thesyntaxinator** [comment]
Workaround: use the below script to execute brew commands. This temporarily changes ownership of the affected directories to allow brew to operate as expected, then changes them back to avoid the zsh compinit warning described above.

```
sudo chown -R $(whoami) /usr/local/share/zsh /usr/local/share/zsh/site-functions
brew "$@"
sudo chown -R root /usr/local/share/zsh /usr/local/share/zsh/site-functions
```

**Comment by gromgit** [comment]
See the last paragraph of https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh, for how your issue can be addressed without resorting to root.

**Comment by thesyntaxinator** [comment]
Got it, thanks. Closing this issue.
