### ISSUE TITLE
Mactracker cask not upgrading automatically

### ISSUE THREAD

**Issue by mariobrostech** [Homebrew/brew#10076]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew config:
```
HOMEBREW_VERSION: 2.6.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1a52862e6d24cd3bf87bec557a8886a1a825ee3c
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 61ea587ca416a5026647c2b956baf261b0ac4bfd
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: N/A
Xcode: 12.3
```

brew doctor:
```
Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

## What you were trying to do (and why)

I was trying to update the Mactracker cask because I saw that Homebrew showed it as an updated cask when running `brew update`. I ran `brew upgrade` in an attempt to upgrade Mactracker, along with any additional packages that were out-of-date.

## What happened (include command output)

Running `brew upgrade` returned a message saying that everything was up-to-date. Running `brew upgrade mactracker` succeeded in upgrading the cask, but this wasn't the case when running the umbrella `brew upgrade` command.

## What you expected to happen

I expected for all of my packages and casks, including Mactracker, to be upgraded after running `brew upgrade`. However, this didn't work until I manually added Mactracker as an additional parameter to the `brew upgrade` command.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. Install an older version of Mactracker. Unfortunately, I tried several times to accomplish this without making my own tap, but I couldn't figure out how to do this. If anyone could point me in the right direction, that would be great! I already had an older version of Mactracker installed via Homebrew, so that was sufficient for my testing.
2. Run `brew update && brew upgrade`, and observe that Mactracker isn't upgraded along with the rest of your packages.

**Comment by mariobrostech** [comment]
Thanks for the clarification and moving the issue to the right spot 🙂

**Comment by Rylan12** [comment]
CC: @Homebrew/cask

If this is not an issue with `upgrade` one of you can transfer the issue to the cask repo (I don't know enough about cask stuff to make the call)

**Comment by vitorgalvao** [comment]
The `mactracker` cask uses `auto_updates true`, so it’s not included in normal `upgrade` output because we can’t really track it’s version, it could update from under your feet. To force it to upgrade with Homebrew, add the `--greedy` flag. This is explained on the `man` page.
