### ISSUE TITLE
Platform detection on M1 arm64 mac is wrong (when ruby is a universal binary)

### ISSUE THREAD

**Issue by wookayin** [Homebrew/brew#10088]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

On my mac, homebrew for arm64 is installed on `/opt/homebrew` and another one for Intel on `/usr/local`.

At some point `brew` stopped working on a M1 mac. `brew install` commands cannot run with the following error:

```
Cannot install in Homebrew on Intel processor in ARM default prefix (/opt/homebrew)!
```

But this machine does **NOT** have an Intel processor! I looked at the source code and found that `Hardware::CPU.intel?` returns True where `Hardware::CPU.arm?` returns False.

## What happened (include command output)

```
$ which brew
/opt/homebrew/bin/brew

$ brew upgrade
Error: Cannot install in Homebrew on Intel processor in ARM default prefix (/opt/homebrew)
```

## What you expected to happen

It should work, installing packages on `/opt/homebrew`.

## Step-by-step reproduction instructions (by running `brew` commands)

See above.

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.7.0-5-g9c1bdfe-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9c1bdfe22906d4022a1a4aefc9365505a907bf7a
Last commit: 78 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ff46a504b15a472061c25de780dad7a6d61f0a6c
Core tap last commit: 29 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim 
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
universal.x86_64-darwin20                    
universal.x86_64-darwin20
CPU: octa-core 64-bit westmere
Clang: 12.0 build 1200                                                            
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git                      
Curl: 7.64.1 => /usr/bin/curl                                                     
macOS: 11.0-x86_64                       
CLT: 12.2.0.0.1.1604076827                   
Xcode: 12.2                              
Rosetta 2: true
</pre>

**Comment by wookayin** [comment]
## Why this is happening?

The ruby binary I am using is a flat universal binary.

```
$ which ruby
/usr/bin/ruby

$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

$ file $(which ruby)
/usr/bin/ruby: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/ruby (for architecture x86_64):        Mach-O 64-bit executable x86_64
/usr/bin/ruby (for architecture arm64e):        Mach-O 64-bit executable arm64e
```

Therefore `RUBY_PLATFORM` tells `universal.x86_64-darwin20`. The hardware detection logics needs to be fixed.

**Comment by carlocab** [comment]
Does `arch -arm64e brew upgrade` work? If it does, it's because you're running your terminal in Rosetta, as shown in `brew config`

    Rosetta 2: true

**Comment by wookayin** [comment]
Thanks for the info. Given your hint I found that the main reason I was running into this is because the shell was running under `tmux` (which was unfortunately a x86_64). Confirmed that ruby returns a correct platform string when running without Rosetta 2, so this is not a bug.

```
> RUBY_PLATFORM
=> "universal.arm64e-darwin20"
```

As a side note, I feel it'd be even better if error messages could be improved to let users to check whether processes were running under Rosetta 2.

**Comment by carlocab** [comment]
I believe `tmux` builds on Apple Silicon now, so you should be able to do `brew install -s tmux`. You may need to `brew install -s` its dependencies first as well.

>I feel it'd be even better if error messages could be improved to let users to check whether processes were running under Rosetta 2

I'm sure a PR that implements this would be appreciated. Perhaps you could open one.

**Comment by wookayin** [comment]
Yes I reinstalled tmux via arm64 brew and now everything works normally. Will be working on improving error messages -- thank you for the help!

**Comment by carlocab** [comment]
Great to hear. Looking forward to your pull request.

**Comment by MikeMcQuaid** [comment]
> Yes I reinstalled tmux via arm64 brew and now everything works normally. Will be working on improving error messages -- thank you for the help!

I wrote the original error so I've opened a PR in https://github.com/Homebrew/brew/pull/10093 for you. Thanks for the bug report!
