### ISSUE TITLE
Flat logo

### ISSUE THREAD

**Issue by bromso** [Homebrew/brew#10096]
I made a flat icon/logo of your current logo. Hope it was ok?

If you want to I can push the .svg version to the repo if you would like?
![homebrew-flat](https://user-images.githubusercontent.com/4441528/102896837-b1cd1c00-446f-11eb-9a24-15454c64dfcb.png)

**Comment by iMichka** [comment]
I think @vitorgalvao was involved in the logo redesign sometime ago and knows best where we could store this version.

**Comment by vitorgalvao** [comment]
> I think @vitorgalvao was involved in the logo redesign sometime ago and knows best where we could store this version.

Thank you for the ping.

> I made a flat icon/logo of your current logo. Hope it was ok?

It is, but I have the originals and can make it monocoloured directly if needed. Your version has an extraneous sharp corner which weirdly was on the previous logo (it was one of the things I wanted to fix).

The question is “why?” We never need HB’s logo in monocolour, as it always shows in digital media—and when it doesn’t it’s in stickers which we’d want to be in colour as well, so I don’t see the need for it.

**Comment by MikeMcQuaid** [comment]
Thanks for the issue but, as @vitorgalvao mentioned, we don't need this anywhere. Cheers!
