### ISSUE TITLE
Seems like too often I am getting "zsh: illegal hardware instruction" from osx 10.15.7

### ISSUE THREAD

**Issue by lewisdonofrio** [Homebrew/brew#10091]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [Yes ] ran `brew update` and can still reproduce the problem?
- [Yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Yes ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

trying to run applications like pianobar and youtube-dl both do the same "zsh: illegal hardware instruction"

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

lewisdonofrio@Lewiss-iMac Videos % youtube-dl C2Ol2OJPZYY
[youtube] C2Ol2OJPZYY: Downloading webpage
zsh: illegal hardware instruction  youtube-dl C2Ol2OJPZYY
lewisdonofrio@Lewiss-iMac Videos % 

lewisdonofrio@Lewiss-iMac Videos % pianobar 
Welcome to pianobar (2020.11.28)! Press ? for a list of commands.
[?] Email: lewis.donofrio@gmail.com
[?] Password: 
(i) Login... Ok.
(i) Get stations... Ok.
	 0) q   38 Special Radio
	 1) q   60s, 70s, and 80s Hits Radio
	 2) q   Abba Radio
	 3)     Al Green Radio
	.
	.
	.
	130) q   Wendy Carlos Radio
	131) q   Yello Radio
	132) q   Yes Radio
	133)     ZAYN Radio
	134) q   ZZ Top Radio
[?] Select station: 2
|>  Station "Abba Radio" (501330805033353714)
(i) Receiving new playlist... Ok.
|>  "S.O.S." by "ABBA" on "Gold - Greatest Hits (Explicit)" <3
zsh: illegal hardware instruction  pianobar
lewisdonofrio@Lewiss-iMac Videos %

  </pre>
</details>

## What you expected to happen

Not to get the message and for youtube-dl to be able to run python and be able to download the video along with pianobar being able to play the music though the soundcard (libav?)

## Step-by-step reproduction instructions (by running `brew` commands)

brew install youtube-dl
brew install pianobar

## Output of `brew config` and `brew doctor` commands

<pre>
lewisdonofrio@Lewiss-iMac Videos % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  libav
lewisdonofrio@Lewiss-iMac Videos % brew config
HOMEBREW_VERSION: 2.7.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 993bf95877143afe1cede022083499e0b4fe336c
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5516a9f3614804b131ee5e10583f41da8a965198
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit penryn
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
lewisdonofrio@Lewiss-iMac Videos % 
</pre>

**Comment by jonchang** [comment]
> CPU: dual-core 64-bit penryn

Mojave and above only support nehalem processors.

**Comment by lewisdonofrio** [comment]
Ok well, I appreciate all your help, that reinstall didn't seem to fix anything, unless I missed a step like an export or something.  I'm wondering why the cold shoulder to these machines, running current software on older hardware, should be welcomed because we are keeping these still running machines out of the landfills and keeping the planet that much healthier.  Please reconsider helping me with this because other applications do work like "mc" and more it's just the other applications that throw this error that I'd like to know how to help out debugging and resolving.  These machines are still good and deserve some love to keep them going without being Apple'esk and thumbing your noses at them (I mean unless I missed some technical reason why you want the people who have perhaps have lost there jobs and are just trying to get by in this day and age to struggle?)

--I'm open to suggestions on what to do next, and I thank you for your time and consideration of this request.

**Comment by jonchang** [comment]
We can do without the commentary, thanks. You'll likely have to reinstall everything from source.
