### ISSUE TITLE
brew audit failing for casks using version.before_comma

### ISSUE THREAD

**Issue by jabenninghoff** [Homebrew/brew#10119]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Running `brew audit` to test a CI/CD failure of a cask version update (https://github.com/Homebrew/homebrew-cask/pull/96743).

## What happened (include command output)

`brew audit` fails for the current backuploupe cask:

<details>
  <summary>Command output</summary>
  <pre>
$ brew audit --cask --appcast --online backuploupe
==> Downloading https://www.soma-zone.com/download/files/BackupLoupe-3.2.3.tar.bz2
Already downloaded: /Users/agamemnon/Library/Caches/Homebrew/downloads/f469f972340fb92ab2e4533ce54bd8c1c109b8c8f2d5fd895fd13820a90f7917--BackupLoupe-3.2.3.tar.bz2
audit for backuploupe: failed
 - exception while auditing backuploupe: no implicit conversion of Hash into String
Error: 1 problem in 1 cask detected
  </pre>
</details>

## What you expected to happen

No errors

## Step-by-step reproduction instructions (by running `brew` commands)

run `brew audit --cask --appcast --online` for any cask containing `version.before_comma`

This seems to be a recent change: `activedock` had a clean audit ~16 hours ago (https://github.com/Homebrew/homebrew-cask/pull/96733), but now fails:

```
$ brew audit --cask --appcast --online activedock
==> Downloading https://macplus-software.com/downloads/ActiveDock.zip
Already downloaded: /Users/agamemnon/Library/Caches/Homebrew/downloads/b23a0c15acd004207d714da75e7a4eac6efc3e0c771d581ad1cb0e4ceda91851--ActiveDock.zip
Warning: No checksum defined for cask 'activedock', skipping verification.
audit for activedock: failed
 - exception while auditing activedock: no implicit conversion of Hash into String
Error: 1 problem in 1 cask detected
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.7.0-44-gcb8e9a6
ORIGIN: https://github.com/Homebrew/brew
HEAD: cb8e9a695fb500e3a1e6e79c370a824c3e7865ea
Last commit: 20 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9b4db65029f60880c8f792fd1b0c80d367700487
Core tap last commit: 36 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 36500
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ZpILXAZo3i/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 11.0 build 1100
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 15
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
</pre>

**Comment by reitermarkus** [comment]
Fixed by https://github.com/Homebrew/brew/pull/10125.
