### ISSUE TITLE
brew list -l produces short output for casks, doesn't print totals as claimed in help

### ISSUE THREAD

**Issue by rptb1** [Homebrew/brew#10116]
# Bug report

NOTE: This is the same issue as #9033.  PR https://github.com/Homebrew/brew/pull/9035 was filed to close that issue, but does not seem to fix the problems I listed.  `git log --grep '#9033'` shows that https://github.com/Homebrew/brew/pull/9035 has made it to my /usr/local but the problems I listed in #9033 are still present.  I'm duplicating the issue here but have checked and updated the details.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Obtaining long form output of all installed packages and casks.

## What happened (include command output)

The long `ls -l` output for formulae was mixed with short `ls` output for casks.

<details>
  <summary>Command output</summary>
  <pre>
rb@Silverbird$ brew list -l
total 0
drwxr-xr-x  3 rb  staff  96 Dec 16 18:16 ansible
drwxr-xr-x  3 rb  staff  96 Nov 27 07:38 aom
drwxr-xr-x  3 rb  staff  96 Dec  4  2018 autoconf
...
drwxr-xr-x  3 rb  staff  96 Dec 22 13:48 zstd
adium                                 font-freefont                         protonvpn
...
font-dejavu-sans-mono-nerd-font       protonmail-bridge
  </pre>
</details>

## What you expected to happen

1. `brew help list` says “If the output is to a terminal, a total sum for all the file sizes is printed before the long listing.” There wasn't one.

2. Formulae and casks listed in the same long format *or* an error if `-l` only works with `--formula`.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew list -l`

## Output of `brew config` and `brew doctor` commands

(Note, brew doctor says there are updated command line tools, even if I update them. Maybe it assumes I'm on latest mac OS?)

<pre>
rb@Silverbird$ brew config
HOMEBREW_VERSION: 2.7.0-39-gd6692d2
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6692d2883a34fdb1e39e0001b3caf7ff681c7a0
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2be111d6b85b6a72565b4883cafb4f171c6e6b8f
Core tap last commit: 5 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: emacsclient --alternate-editor='bbedit -w'
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 11.0 build 1100
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 15
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11
rb@Silverbird$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  s3-backer
  s3fs
</pre>

**Comment by rptb1** [comment]
I've done a bit of digging.  It looks like the original work done to fix this work was later regressed.

If I do `git checkout 5adb76a5babdccd2c4edfb8752ac979ed14716ca list.rb` then I get this:

```
brew list -l
...
Error: Invalid usage: `--l` cannot be passed without `--formula`.
```

This fixes item 2 (mixed output) of my issue.  But item 1 (should print total size) doesn't look like it was ever fixed.

I looked at this because although this issue isn't very important, I was concerned there might be a wider problem with regression.  I can't really tell, since I don't know Homebrew's processes.

**Comment by issyl0** [comment]
> 2. Formulae and casks listed in the same long format or an error if -l only works with --formula.

The `-l` option only works for listing _formulae_ in a long format. From `brew help list`:

```
-l                              List formulae in long format. If the output
                                 is to a terminal, a total sum for all the
                                 file sizes is printed before the long
                                 listing.
```

**Comment by rptb1** [comment]
Good luck with the detective work and Merry Christmas or equivalent!

**Comment by issyl0** [comment]
Thanks, @rptb1, Merry Christmas (or equivalent) to you too! 🎄
