### ISSUE TITLE
Provide completions for Casks in regular commands

### ISSUE THREAD

**Issue by kidonng** [Homebrew/brew#10123]
# Feature suggestion

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# A detailed description of the proposed feature

Provide completions for Casks in regular commands such as `brew install`.

Proposed design:

- `brew install --formula` should only lists available formulae, while `brew install --cask` should only lists available casks.
- `brew install` (without specifying `--formula` or `--cask`) should list all formulae and casks available.

We can provide a new `brew casks` command (like in #8846 which adds a `brew formulae` command) that lists all available casks that can be used for shell completions or other programs (like a fuzzy finder).

# The motivation for the feature

Since [Homebrew 2.6.0](https://brew.sh/2020/12/01/homebrew-2.6.0/) all brew cask commands have been deprecated, but current shell completions only provide completions for formulae, not casks (at least in Fish shell).

A workaround is to use the deprecated `brew cask <command>` to get completions, and replace `cask <command>` with `<command> --cask` later. This is not so obvious for a new Homebrew user and is way too clunky.

# How the feature would be relevant to at least 90% of Homebrew users

Shell completions is essential for most users, as one don't need to remember a long list of full names of casks.

# What alternatives to the feature have been considered

Nope, I think?

**Comment by MikeMcQuaid** [comment]
Seems like a good idea but we'll need help with implementation.

**Comment by kidonng** [comment]
I started doing this when I created this issue, but since I'm only familiar with Fish, it's not an easy task. And I see there are some ongoing efforts (#10200, #10223) so maybe I will try to make simple improvements first.

**Comment by MikeMcQuaid** [comment]
@Rylan12 @jonchang Is this already working? I wasn't sure.

**Comment by Rylan12** [comment]
Partially. All shells are now able to complete both formulae and casks as required. However, the completions aren't intelligent enough to know to not fill formulae when `--cask` is passed and vice-versa. This is on my to-do list but I haven't had a chance to get it working, yet.

Up to you, I'd say, as to whether to keep this open or to close in favor of #10223

**Comment by MikeMcQuaid** [comment]
I'd say it's partially working enough now to close out in favour of https://github.com/Homebrew/brew/issues/10223. Thanks @rylan12 and all!
