### ISSUE TITLE
11.0 and 11.1 pkg-config files should be merged

### ISSUE THREAD

**Issue by Bo98** [Homebrew/brew#10126]
The MacOS version to take pkg-config files from is not determined at runtime - it is baked into the compiled binary and shipped with the bottle. Because we have only one bottle for all of Big Sur, we should not be supplying pkg-config files for minor Big Sur versions.

I recommend merging 11.0 and 11.1. Easiest approach I suggest would be to:

* Delete the 11.0 files and rename the 11.1 files to "11" or similar.
* Modify the SDK in the *.pc files to use unversioned MacOSX.sdk (for now - may be problematic when macOS 12 arrives).
* Update the pkg-config formula in homebrew-core to adjust the path logic for `>= :big_sur` and then revision bump.

---

(I can submit pull requests for this but am unlikely to be able to until at least the weekend.)

**Comment by carlocab** [comment]
It seems that last step may be unnecessary, as on Big Sur:
```
❯ brew ruby -e 'puts MacOS.version'
11
```
while in the `pkg-config` formula, we [have](https://github.com/Homebrew/homebrew-core/blob/132967e66b467615bee227813bd653c9e46e3758/Formula/pkg-config.rb#L38)
```
      pc_path << "#{HOMEBREW_LIBRARY}/Homebrew/os/mac/pkgconfig/#{MacOS.version}"
```

**Comment by carlocab** [comment]
I've opened https://github.com/Homebrew/brew/pull/10129.

**Comment by Bo98** [comment]
Oh I didn't realise the behaviour changed.

The existing Intel bottle is still affected however:

> /usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11.0

So we need to either revision bump or have a 11.0 symlink.

**Comment by carlocab** [comment]
>So we need to either revision bump or have a 11.0 symlink.

I'd like to avoid a revision bump. That leads to a costly CI run which takes quite a while to merge because of spurious failures. Let's do symlinks, unless someone else has a strong opinion about it.
