### ISSUE TITLE
allow using distcc as compiler wrapper for builds

### ISSUE THREAD

**Issue by ejelly** [Homebrew/brew#10120]
# Feature suggestion

# A detailed description of the proposed feature

Being able to tell brew to pass the distcc wrapper down as the compiler for building C/C++ projects instead of the native compiler.

# The motivation for the feature

People may have several Macs, some faster than others, and being able to use compilers remotely could greatly benefit build time. distcc is a tried and tested solution, but I at least found no way to pass it down as the compiler to use.

# How the feature would be relevant to at least 90% of Homebrew users

This is potentially useful to any user with more than one Mac, as they can distribute compiling of especially bigger projects among them.

# What alternatives to the feature have been considered

A very weak alternative is building projects on the faster Macs and then transferring them over. This is very cumbersome, and still lacks the potential of distributing building across _multiple_ Macs.

**Comment by MikeMcQuaid** [comment]
Sorry, we're not interested in this at that time.
