### ISSUE TITLE
Apple Silicon RabbitMQ install error

### ISSUE THREAD

**Issue by Print-beats-Debug** [Homebrew/brew#10158]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Tried to install RabbitMQ using homebrew according to the instructions on the RabbitMQ site.

## What happened (include command output)

Running `brew install rabbitmq` gave the following after the package was downloaded from github

<details>
  <summary>Command output</summary>
  <pre>

  ==> /usr/bin/unzip -qq -j /usr/local/Cellar/rabbitmq/3.8.9_1/plugins/rabbitmq_ma
Error: undefined method `exitstatus' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:585:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:11:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:11:in `rewrite_child_error'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:87:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:404:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:63:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:899:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:453:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:384:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:297:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:295:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:295:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'

  </pre>
</details>

Running `brew config` produces:
<details>
  <summary>Command output</summary>
  <pre>
HOMEBREW_VERSION: 2.7.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 993bf95877143afe1cede022083499e0b4fe336c
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4e33c19dfbdaaa30782c4eac8282443ce883ae4d
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit westmere
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
Rosetta 2: true
  </pre>
</details>

## What you expected to happen

No errors to occur

## Step-by-step reproduction instructions (by running `brew install` commands)

I installed homebrew with a rosetta2 terminal and the command:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
and had no issues.

I then attempted to run `brew install rabbitmq` and produced the previous message.

**Comment by Print-beats-Debug** [comment]
The command `brew install rabbitmq` is now producing a different error message.
I have run `brew update` and am now getting the following output:

<details>
  <summary>Command output</summary>
  <pre>
Error: undefined method `termsig' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:592:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:11:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:11:in `rewrite_child_error'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:87:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:404:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:63:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:902:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:456:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:384:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:297:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:295:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:295:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
  </pre>
</details>

**Comment by ADTRT** [comment]
JQuePi
