### ISSUE TITLE
Add ability for formulae to add custom shell environment initialization

### ISSUE THREAD

**Issue by felipecrs** [Homebrew/brew#10167]
# A detailed description of the proposed feature

Allow formulae to define custom shell environment initialization snippets to be added on `brew shellenv`. 

# The motivation for the feature

This would allow projects which require to change the shell environment initialization to be flawlessly installable with Homebrew. Some examples are:

- `sdkman`:
  ```sh
  export SDKMAN_DIR="$HOME/.sdkman"
  . "$HOME/.sdkman/bin/sdkman-init.sh"
  ```

- `nvm`:
  ```sh
  export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
  if [ -f "$NVM_DIR/nvm.sh" ]; then
    . "$NVM_DIR/nvm.sh"
  else
    unset NVM_DIR
  fi
  ```
- `pyenv`:
  ```sh
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
  ```

Since it's already a requisite of Homebrew to add its snippet to the .bashrc (or whatever), a user would have to do this task only once and then rely on Homebrew for further changes.

Adding this feature to Homebrew would enable:

- The shellenv snippet to be updated automatically if a formulae is also updated
- The shellenv to be automatically removed if the pertinent module is uninstalled (no more leftovers in the .bashrc or whatever)
- Easier installation for this kind of tools

# How the feature would be relevant to at least 90% of Homebrew users

Adding snippets on the shell initialization is not always a straightforward task. There is no pattern in this matter, and a big portion of the newbies do not understand what they are doing when they have to do such a thing.

# What alternatives to the feature have been considered

The best that Homebrew can do for now is to display a message with instructions for the user on how to edit the shell initialization files and what to add.

**Comment by carlocab** [comment]
Thanks for the suggestion.

This seems difficult to implement, as there needs to be a standardised way for `brew shellenv` to get the needed data from a formula or keg. 

The naive way to do it would be to add a method to a formula that does it, but this would almost certainly create a maintenance burden that would be inefficient for homebrew/core maintainers to shoulder.

Another way is for the relevant upstream projects to customise their installers (if they have one) that makes it easy for `brew shellenv` to query the needed data from their kegs. Coordinating this will be difficult, however, and probably unlikely to be worth the effort.

>display a message with instructions

We avoid doing that wherever possible. Instructions should be documented upstream, not by Homebrew. The reason is that instructions can very quickly become wrong or outdated without us knowing about it. Keeping track of special instructions for a large number of formulae just isn't doable for us, unfortunately.

I suspect a better alternative would be to use shell plugins offered by frameworks such as [OhMyZsh](https://ohmyz.sh) or [Prezto](https://github.com/sorin-ionescu/prezto). OhMyZsh already offers [a large number of plugins](https://github.com/ohmyzsh/ohmyzsh#plugins) that simplify the set up of your shell environment. If the plugin you want isn't already available, using a [custom one](https://github.com/ohmyzsh/ohmyzsh#custom-plugins-and-themes) is also rather easy.

**Comment by felipecrs** [comment]
>  Another way is for the relevant upstream projects to customise their installers (if they have one) that makes it easy for brew shellenv to query the needed data from their kegs. Coordinating this will be difficult, however, and probably unlikely to be worth the effort. @carlocab

I was thinking about something very simple:

```ruby
# pyenv
def install
    # [..]

    bash_shellenv.install <<-SHELL
        eval "$(pyenv init -)"
    SHELL
    zsh_shellenv.install <<-SHELL
        eval "$(pyenv init -)"
    SHELL
end
```

```ruby
# sdk
def install
    # [..]

    bash_shellenv.install <<-SHELL
        export SDKMAN_DIR="$HOME/.sdkman"
        . "$HOME/.sdkman/bin/sdkman-init.sh"
    SHELL
    zsh_shellenv.install <<-SHELL
        export SDKMAN_DIR="$HOME/.sdkman"
        . "$HOME/.sdkman/bin/sdkman-init.sh"
    SHELL
end
```

**Comment by carlocab** [comment]
I've addressed what you're describing here:

>The naive way to do it would be to add a method to a formula that does it, but this would almost certainly create a maintenance burden that would be inefficient for homebrew/core maintainers to shoulder.

In case the point I make there is not clear, it's actually related to this:

>The reason is that instructions can very quickly become wrong or outdated without us knowing about it. Keeping track of special instructions for a large number of formulae just isn't doable for us, unfortunately.

Just `s/instructions/shell commands`.

**Comment by felipecrs** [comment]
> The reason is that instructions can very quickly become wrong or outdated without us knowing about it. Keeping track of special instructions for a large number of formulae just isn't doable for us, unfortunately.

These snippets are made not to be changed. The chances are that they probably never changed since the maintainers know that manual intervention would be needed otherwise. So I don't believe it will make that difference in the maintainability.

**Comment by felipecrs** [comment]
> The reason is that instructions can very quickly become wrong or outdated without us knowing about it. Keeping track of special instructions for a large number of formulae just isn't doable for us, unfortunately.

But you are right, they can change without you knowing about it.

> Another way is for the relevant upstream projects to customise their installers (if they have one) that makes it easy for brew shellenv to query the needed data from their kegs. Coordinating this will be difficult, however, and probably unlikely to be worth the effort.

It would also be a good plan. Adding this API would be helpful, and the adoption is the least of our problems once it's possible. It's just a matter of time to ask the maintainers to adopt the new API. [That's one reason why SDKMAN! are against adding them to Homebrew.](https://github.com/sdkman/sdkman-cli/issues/799#issuecomment-695334675)

**Comment by carlocab** [comment]
If these snippets were contained in files that come with the tarball associated with the formula, then maybe what you suggest could work.

However, what about users who just want the minimal set of shell commands necessary to get `brew` working, and don't want all the extra cruft that comes with your proposed `brew shellenv` command? I would personally be wary of putting `eval $(brew shellenv)` in my `zshrc` if I knew that any random formula could be putting god-knows-what into that command.

**Comment by felipecrs** [comment]
> However, what about users who just want the minimal set of shell commands necessary to get brew working, and don't want all the extra cruft that comes with your proposed brew shellenv command? I would personally be wary of putting eval $(brew shellenv) in my zshrc if I knew that any random formula could be putting god-knows-what into that command.

You got a point, that's one reason why to keep this snippet in the formulae, so they're audited by the community. Optionally, one could disable `shellenv.install` with `brew install nvm --no-shellenv`

**Comment by carlocab** [comment]
I'm still sceptical `brew` is the right tool for this, but no longer think that this is a terrible idea. If you want it to happen, you should look into opening the necessary PRs for it. The maintainers who review your PRs may not be as receptive, however.

I'm also still pretty sure the tool you're looking for is this:

>I suspect a better alternative would be to use shell plugins offered by frameworks such as OhMyZsh or Prezto.

Setting up a plugin would take far less work than what's needed to get `brew` to the place you want it to be. Not to mention that these frameworks are already designed to help you set up your shell. As an example, the `z.lua` formula actually ships with a Zsh plugin that does exactly what you are suggesting, and using it with OhMyZsh is trivial.

**Comment by felipecrs** [comment]
> Setting up a plugin would take far less work than what's needed to get brew to the place you want it to be. Not to mention that these frameworks are already designed to help you set up your shell. As an example, the z.lua formula actually ships with a Zsh plugin that does exactly what you are suggesting, and using it with OhMyZsh is trivial.

In the past, I was using a zsh plugin for `nvm` which indeed solved this problem. There aren't zsh plugins for most of the tools that I use, but as you said I could create a plugin by myself for that. There are two major caveats though:

1. This is only valid for ZSH, and more specifically for those who use Oh My ZSH!. How about bash? Fish? That's not so trivial having to create/install plugins for bash (if you use Oh My Bash or Bash-it), or even fish. I personally use both zsh and bash (ZSH for personal usage, while the projects I work are bash scripts so I often switch for testing), and that's why I switched away from the nvm ZSH plugin for this purpose.

2. It's still a secondary post-installation method that no one would know about unless they read a How-To somewhere. That's the issue I'm trying to prevent here. Because if the user was asked to perform a post-installation step, he could manually inject the snippet in his `.bashrc` or `.zshrc` then, the effort difference is minimal.

**Comment by MikeMcQuaid** [comment]
My main issues with this are:

- `brew shellenv` shouldn't be running arbitrary code installed by formulae or upstreams without additional configuration. Something like `brew shellenv rbenv` should be required for security reasons. Once you get to that point, though, I'm not sure how that's better than having `eval "$(rbenv init -)"` added manually to the dotfiles
- this would need a new DSL added to formulae which, as @carlocab mentioned, we'd be responsible for maintaining and I'm not sure that's worth doing at this point
- This:

> It would also be a good plan. Adding this API would be helpful, and the adoption is the least of our problems once it's possible. It's just a matter of time to ask the maintainers to adopt the new API. [That's one reason why SDKMAN! are against adding them to Homebrew.](https://github.com/sdkman/sdkman-cli/issues/799#issuecomment-695334675)

Well, they actually said:

> brew discourages tools that update itself (like SDKMAN! does)

We still discourage this and would need this behaviour patched out.

> brew by design never modifies files outside HOMEBREW_PREFIX, so you would have to manually modify your .bash_profile to source SDKMAN's init script

You'd still need to modify your profile manually to source this as a result.

**Comment by felipecrs** [comment]
The goal is to have simpler installation methods for such kind of tools. Having to modify the `.bash_profile` once is fine, but having to modify on every new install, then I don't think it worth the effort despite there are benefits still:

> Once you get to that point, though, I'm not sure how that's better than having eval "$(rbenv init -)" added manually to the dotfiles

A benefit is that you don't need to know the tool-specific snippet. `brew shellenv rbenv` is a more generic, easier to know, which can be updated by Homebrew if needed. Nonetheless, I'm against this method: I also think it does not worth it because of the first sentence of this comment.

I have another suggestion though, which I believe is better:

1. Introducing `shellenv` files, which are files meant to be `source`d by the shells, they live in `$(brew --prefix)/share/{bash/zsh}/shellenvs/`. E.g.: `/home/linuxbrew/.linuxbrew/share/bash/shellenvs/pyenv.bash`
  
  ```bash
  #!/bin/bash
  
  eval "$(pyenv init -)"
  ```
  
 2. One can opt-in to automatically load those shellenvs, [just like they do with the completions](https://docs.brew.sh/Shell-Completion):
    
   ```bash
    if type brew &>/dev/null; then
        for SHELLENV in "$(brew --prefix)/share/bash/shellenvs/"*.bash; do
          [[ -r "$SHELLENV " ]] && source "$SHELLENV"
        done
        unset SHELLENV
      fi
    fi
   ```
 
3. Tools/packages can provide `shellenv` files the same way they can provide shell completions.

4. As stated earlier, but just to summarize:
    - Now, the user only needs to edit the `.bash_profile` once, the same way they did to opt-in loading the completions.
    - Homebrew can now install and uninstall these completions as needed. The user does not need to manage this on every install/uninstall.

**Comment by MikeMcQuaid** [comment]
> One can opt-in to automatically load those shellenvs, [just like they do with the completions](https://docs.brew.sh/Shell-Completion):

This seems more appropriate. 

My other reservations stand and I'd want to see much more demand for a feature like this than we currently have before we'd consider merging an implementation.

**Comment by felipecrs** [comment]
Another use case:

The Java formula could add automatically add a JAVA_HOME variable to the environment.
