### ISSUE TITLE
`brew deps` returns inconsistent output

### ISSUE THREAD

**Issue by gromgit** [Homebrew/brew#10173]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was digging into https://github.com/Homebrew/homebrew-core/issues/67939, and decided to check dependency info on `atk`. To my surprise, `brew deps atk` and `brew deps --tree atk` output different Python dependencies, which may have some bearing on the abovementioned issue.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ brew deps atk
gdbm
gettext
glib
libffi
openssl@1.1
pcre
python@3.8
readline
sqlite
xz

$ brew deps --tree atk
atk
└── glib
    ├── gettext
    ├── libffi
    ├── pcre
    └── python@3.9
        ├── gdbm
        ├── openssl@1.1
        ├── readline
        ├── sqlite
        │   └── readline
        └── xz
  </pre>
</details>

I then tried `brew uninstall --ignore-dependencies python@3.8`, then ran the two commands again, with exactly the same results. I also get the same results after a successful `brew update`.

## What you expected to happen

I was expecting both `brew deps` commands to list the same set of formulae. Since `glib` has an explicit dependency on `python@3.9`,  I was certainly not expecting `python@3.8` to be reported, though I have both installed on my Mojave box.

## Step-by-step reproduction instructions (by running `brew` commands)

```
brew deps atk
brew deps --tree atk
```

Note: I was unable to replicate this on my other box (Catalina), so it may be a issue of Homebrew installed state. Nevertheless, I wasn't expecting a change in dependency sets when I only changed the output format, so I'd consider this a bug, and I'm suspending further activity on my Mojave box in case anyone needs further debug output.

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.7.1-40-gc54acef
ORIGIN: https://github.com/Homebrew/brew
HEAD: c54acefab31e2e4b03242d8143f90f164e28393c
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 865fd382230a77b16aff5232a63c0b7ff9eb4470
Core tap last commit: 50 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 11.0 build 1100
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  boost-python
  csv-fix
  encfs
  es
  ext2fuse
  hardlink-osx
  json11
  ntfs-3g
  rtv
  sshfs

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libpgtcl.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  parallel
  lua@5.1
  emacs
  gcc@8
  gcc@7
</pre>

**Comment by dawidd6** [comment]
This has been an issue for a long time actually and I remember the difference is caused by the fact that one command takes installed formulae and the other one takes formula files into consideration or something else.
I've always found this behavior confusing, but couldn't make it right tho.

**Comment by carlocab** [comment]
Can't reproduce; on Big Sur though.

Probably related (?): https://github.com/Homebrew/brew/issues/9333

**Comment by gromgit** [comment]
On the assumption that it's `brew linkage`-related, as Mike mentioned in #9333:
```sh
# Ignoring python@3.8, because I'd already uninstalled it
$ brew linkage $(brew deps atk | grep -v python@3.8)
==> Checking gdbm linkage
System libraries:
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /usr/local/Cellar/gdbm/1.18.1_1/lib/libgdbm.6.dylib (gdbm)
==> Checking gettext linkage
System libraries:
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libxml2.2.dylib
Homebrew libraries:
  /usr/local/Cellar/gettext/0.21/lib/libgettextlib-0.21.dylib (gettext)
  /usr/local/Cellar/gettext/0.21/lib/libgettextsrc-0.21.dylib (gettext)
  /usr/local/Cellar/gettext/0.21/lib/libintl.8.dylib (gettext)
  /usr/local/Cellar/gettext/0.21/lib/libtextstyle.0.dylib (gettext)
==> Checking glib linkage
System libraries:
  /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
  /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
  /usr/lib/libSystem.B.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libobjc.A.dylib
  /usr/lib/libresolv.9.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/gettext/lib/libintl.8.dylib (gettext)
  /usr/local/Cellar/glib/2.66.4/lib/libgio-2.0.0.dylib (glib)
  /usr/local/Cellar/glib/2.66.4/lib/libglib-2.0.0.dylib (glib)
  /usr/local/Cellar/glib/2.66.4/lib/libgmodule-2.0.0.dylib (glib)
  /usr/local/Cellar/glib/2.66.4/lib/libgobject-2.0.0.dylib (glib)
  /usr/local/opt/libffi/lib/libffi.7.dylib (libffi)
  /usr/local/opt/pcre/lib/libpcre.1.dylib (pcre)
Dependencies with no linkage:
  python@3.9
==> Checking libffi linkage
System libraries:
  /usr/lib/libSystem.B.dylib
==> Checking openssl@1.1 linkage
System libraries:
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /usr/local/Cellar/openssl@1.1/1.1.1i/lib/libcrypto.1.1.dylib (openssl@1.1)
  /usr/local/Cellar/openssl@1.1/1.1.1i/lib/libssl.1.1.dylib (openssl@1.1)
==> Checking pcre linkage
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/Cellar/pcre/8.44/lib/libpcre.1.dylib (pcre)
  /usr/local/Cellar/pcre/8.44/lib/libpcre16.0.dylib (pcre)
  /usr/local/Cellar/pcre/8.44/lib/libpcre32.0.dylib (pcre)
  /usr/local/Cellar/pcre/8.44/lib/libpcreposix.0.dylib (pcre)
==> Checking readline linkage
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libncurses.5.4.dylib
==> Checking sqlite linkage
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/readline/lib/libreadline.8.dylib (readline)
==> Checking xz linkage
System libraries:
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /usr/local/Cellar/xz/5.2.5/lib/liblzma.5.dylib (xz)
```
No `python@3.8` anywhere.

**Comment by gromgit** [comment]
Not an issue with incorrect aliases or `opt` symlinks either:
```
$ ls -ld $(brew --repo homebrew/core)/Aliases/python* /usr/local/opt/python*
lrwxr-xr-x  1 aho admin  24 Dec 19 18:12  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/python -> '../Formula/python@3.9.rb'
lrwxr-xr-x  1 aho admin  24 Dec 19 18:12  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/python3 -> '../Formula/python@3.9.rb'
lrwxr-xr-x  1 aho admin  24 Dec 19 18:12 '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/python@3' -> '../Formula/python@3.9.rb'
lrwxr-xr-x  1 aho wheel  28 Dec 29 18:16  /usr/local/opt/python -> '../Cellar/python@3.9/3.9.1_3'/
lrwxr-xr-x  1 aho wheel  28 Dec 29 18:16  /usr/local/opt/python3 -> '../Cellar/python@3.9/3.9.1_3'/
lrwxr-xr-x  1 aho wheel  28 Dec 29 18:16 '/usr/local/opt/python@3' -> '../Cellar/python@3.9/3.9.1_3'/
lrwxr-xr-x  1 aho wheel  28 Dec 29 18:16 '/usr/local/opt/python@3.9' -> '../Cellar/python@3.9/3.9.1_3'/
```

**Comment by carlocab** [comment]
What does

    jq '.runtime_dependencies' <$(brew --prefix atk)/INSTALL_RECEIPT.json

say?

**Comment by gromgit** [comment]
Bingo!
```
$ jq '.runtime_dependencies' <$(brew --prefix atk)/INSTALL_RECEIPT.json
[
  {
    "full_name": "gettext",
    "version": "0.20.2"
  },
  {
    "full_name": "libffi",
    "version": "3.3"
  },
  {
    "full_name": "pcre",
    "version": "8.44"
  },
  {
    "full_name": "gdbm",
    "version": "1.18.1"
  },
  {
    "full_name": "openssl@1.1",
    "version": "1.1.1g"
  },
  {
    "full_name": "readline",
    "version": "8.0.4"
  },
  {
    "full_name": "sqlite",
    "version": "3.32.1"
  },
  {
    "full_name": "xz",
    "version": "5.2.5"
  },
  {
    "full_name": "python@3.8",
    "version": "3.8.3"
  },
  {
    "full_name": "glib",
    "version": "2.64.3"
  }
]
```
I'm guessing the `atk` bottle passed the usual testing that happened when `glib`'s own Python dependency was bumped to 3.9, so the bottle was never rebuilt.

**Comment by carlocab** [comment]
>it really shouldn't be used to infer dependencies

Hard to say this for sure, as it seems like the only time it goes awry is when it involves `python@3.x`. Admittedly, that is a pretty big corner case...

**Comment by iMichka** [comment]
> I'm not sure INSTALL_RECEIPT.json's utility extends beyond "this was Homebrew state when the user installed this keg". In particular, it really shouldn't be used to infer dependencies.

It is. Say that you modify a few formulae manually to test something (this happens as a maintainer). Then you stash away your changes: the dependencies list that was used to build your package at time X might differ from the one defined in the formula file at time Y. So this is why `brew deps` sometimes returns something different than what you would think.

**Comment by gromgit** [comment]
I'll grant that this may be useful in developer mode, but in end-user mode, it just confuses folks with false-positives and blocks legal operations on bottled installs. I double-checked this by manually changing `atk`'s JSON to depend on `python@3.9 3.9.1`, and confirmed that a `brew uninstall python@3.8` no longer lists `atk` as one of the "blocking" formulae.

Also, I just realized that the `deps --tree` output in my original post was mangled:
```
atk
└── glib
    ├── gettext
    ├── libffi
    ├── pcre
    └── python@3.9
        ├── gdbm
        ├── openssl@1.1
        ├── readline
        ├── sqlite
        │   └── readline
        └── xz
```
Here, it's clear that Python is only an _indirect_ dependency of `atk`. In fact, _all_ the "blocking" formulae on my box (and I suspect those on the original reporter) indirectly depend on Python via two formulae (`glib` and `gobject-introspection`), both of which were updated to depend on `python@3.9` before the `python@3.8` uninstall was attempted.

Off the top of my head, since indirect dependencies of a formula can be updated without bumping the formula itself, a more correct algorithm is:
```python
# to be applied recursively, of course
if installed keg version matches repo formula:
  use declared dependencies in formula
else:
  use declared dependencies in INSTALL_RECEIPT.json
  [optional] warn user that keg is out-of-date, so dependency info may be incorrect
```

**Comment by MikeMcQuaid** [comment]
> In particular, it really shouldn't be used to infer dependencies.

It should be used to infer dependencies because it's generated from the actual linkage of the bottled binaries which, due to opportunistic linkage, may be different to the declared linkage in the formula.

Before we had/did this: we would tell people that nothing depended on a given formula but uninstalling it then broke things.

We'll consider PRs that make this behaviour but I don't think it's worth having a tracking issue for something that's working as intended currently. Sorry!
