### ISSUE TITLE
ENV.cc and ENV.cxx is not correctly set when depending on gcc formula

### ISSUE THREAD

**Issue by iMichka** [Homebrew/brew#10170]
## What you were trying to do (and why)

Trying to install a meson-based formula (https://github.com/Homebrew/linuxbrew-core/pull/21946) on linux with gcc@7.
The issues is also present on macOS.

## What happened (include command output)

ENV["CC"], ENV["CXX"], ENV.cc, ENV.cxx is incorrectly set in the install and test block.

The wrong compiler is defined.
- On Mac it is always set to clang/clang++, even if I define `depends_on "gcc@x"` in the formula.
- On Linux it is always set to the biggest gcc installed: if gcc@10 is installed on the system, ENV.cc is always gcc-10.

`meson` (but maybe other build tools) will pick up the wrong compiler.
Some tests blocks are run with the wrong compiler too, as we use ENV.cc a lot.

## What you expected to happen

ENV["CC"], ENV["CXX"], ENV.cc, ENV.cxx should point to the gcc formula defined in the formula.

## Note

This issue might not be a bug but a design choice. In that case I would like to change that behaviour.

**Comment by carlocab** [comment]
>On Mac it is always set to clang/clang++, even if I define depends_on "gcc@x" in the formula.

I think this is intentional, as many of the formulae just depend on `gcc` for `gfortran`. If you want it not to use clang on macOS, I think you need `fails_with`.

**Comment by iMichka** [comment]
I see. I can use (on Mac)
```
  fails_with :clang
  depends_on "gcc@9"
```

which gives me ... `gcc-10`, because I have `gcc` installed.

If I want gcc@9, I need to use:
```
  fails_with :clang
  fails_with gcc: "10"
  depends_on "gcc@9"
```

If I want gcc@7, I need to use:
```
  fails_with :clang
  fails_with gcc: "8"
  fails_with gcc: "9"
  fails_with gcc: "10"
  depends_on "gcc@7"
```

It's not the shortest syntax but it works.

**Comment by carlocab** [comment]
Yes. I haven't managed to figure out how to use `fails_with` to get it to use LLVM `clang` instead of Apple `clang`, though. But I didn't try very hard, and that was a while ago.

**Comment by iMichka** [comment]
Ok so I can live with the fails_with syntax for the time being.

I think the biggest issue I have right now is on Linux: ENV.cc and friends will always point to the highest gcc installed.
Historically brewed `gcc` on linux was gcc-5. I am changing it to align it with homebrew-core, so now brew `gcc` becomes gcc-10 (https://github.com/Homebrew/linuxbrew-core/pull/21380).

If I `brew install gcc` on linux, now all the ENV.cc will point to gcc-10, even with a pristine formula that does not defined a specific gcc.

I would expect the following behaviour (on Linux):
ENV.CC points to `/usr/bin/gcc` by default
ENV.CC points to `gcc@5` if `/usr/bin/gcc` != `gcc-5` (this also means that gcc@5 needs to be installed)
ENV.CC points to `gcc@x` if `gcc@x` is defined in the formula

I have no clue how to change that behaviour right now.

**Comment by jonchang** [comment]
The logic is in compilers.rb, but compiler selection is pretty hairy currently and we'd need to think carefully about how to handle this. In particular:

>  ENV.CC points to gcc@5 if /usr/bin/gcc != gcc-5 (this also means that gcc@5 needs to be installed)

Do we want gcc@5 to be used if the system compiler is newer?

**Comment by iMichka** [comment]
> Do we want gcc@5 to be used if the system compiler is newer?

I would like. Almost everything is compiled with gcc5 on linux CI: I would like to use brewed gcc5 as a fallback when no gcc5 is present. This makes sure the builds have more chances to pass if someone builds from source.

**Comment by carlocab** [comment]
One thing I noticed though is that `fails_with gcc "8"` also appears to rule out any newer `gcc`, so it may be sufficient to just do
```
fails_with :clang
fails_with gcc: "8"
depends_on "gcc@7"
```
if you want gcc@7.

**Comment by MikeMcQuaid** [comment]
Yes, `fails_with` is what's required to make this work as expected. We can't really change the behaviour of `depends_on` here without breaking lots of other formulae.



> ENV.CC points to `/usr/bin/gcc` by default
> ENV.CC points to `gcc@5` if `/usr/bin/gcc` != `gcc-5` (this also means that gcc@5 needs to be installed)

Something like this seems reasonable for Linux-only with a concept of preferring a specific compiler version that we use for building bottles.

**Comment by iMichka** [comment]
>> ENV.CC points to /usr/bin/gcc by default
>>ENV.CC points to gcc@5 if /usr/bin/gcc != gcc-5 (this also means that gcc@5 needs to be installed)

>Something like this seems reasonable for Linux-only with a concept of preferring a specific compiler version that we use for building bottles.

This is on the todo list then for the linuxbrew-core migration.
