### ISSUE TITLE
fish completion for `brew search` offers wrong documentation

### ISSUE THREAD

**Issue by kgrossjo** [Homebrew/brew#10179]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
  I fixed all errors, but there are still warnings left.
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to search for packages but did not remember how to use `brew search` and so I used (fish) completion.

## What happened (include command output)

If I type `brew search --` and then hit the tab key, I get a nice list of all possible long options and what they do.  One of them is `--desc` and it says "Search also in descriptions".

But `brew search --help` tells me that `--desc` does something different: "Search for formulae with a description matching text and casks with a name matching text."

I feel that "Search _only_ in descriptions" would be a better approximation of what this does.  A more precise phrase would be "Search in formula descriptions and cask names", but that's maybe too long for completion.

(Actually, an argument could be made that `brew search --desc foo` should search in formula names, formula descriptions, and cask names.  Not searching in formula names doesn't really make sense to me.  But this is about the fish completions, not about the brew behavior...)

(By running `brew search tectonic` (finds tectonic) and `brew search --desc tectonic` (finds nothing) you can easily verify that the "also" part of the completion help is wrong, and the help text is correct.)

<details>
  <summary>Command output</summary>
  <pre>

kgrossjo@marcie ~> brew search --{hit tab here but not return}
--casks  (Display all locally available casks)  --fink      (Search only in this repository)
--debian      (Search only in this repository)  --macports  (Search only in this repository)
--desc           (Search also in descriptions)  --opensuse  (Search only in this repository)
--fedora      (Search only in this repository)  --ubuntu    (Search only in this repository)
kgrossjo@marcie ~> brew search --help
Usage: brew search [options] [text|/text/]

Perform a substring search of cask tokens and formula names for text. If
text is flanked by slashes, it is interpreted as a regular expression. The
search for text is extended online to homebrew/core and homebrew/cask.

If no text is provided, list all locally available formulae (including tapped
ones). No online search is performed.

      --formula, --formulae        Without text, list all locally available
                                   formulae (no online search is performed).
                                   With text, search online and locally for
                                   formulae.
      --cask, --casks              Without text, list all locally available
                                   casks (including tapped ones, no online
                                   search is performed). With text, search
                                   online and locally for casks.
      --desc                       Search for formulae with a description
                                   matching text and casks with a name
                                   matching text.
      --pull-request               Search for GitHub pull requests containing
                                   text.
      --open                       Search for only open GitHub pull requests
      --closed                     Search for only closed GitHub pull requests
      --macports                   Search for text in the given package
                                   manager's list.
      --fink                       Search for text in the given package
                                   manager's list.
      --opensuse                   Search for text in the given package
                                   manager's list.
      --fedora                     Search for text in the given package
                                   manager's list.
      --debian                     Search for text in the given package
                                   manager's list.
      --ubuntu                     Search for text in the given package
                                   manager's list.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.

  </pre>
</details>

## What you expected to happen

I was expecting the completion output after `brew search --` and then hitting tab to accurately reflect what happens.

## Step-by-step reproduction instructions (by running `brew` commands)

I think the above sections were clear enough, but here I want to note that while preparing this report I learned about `brew desc` which gives much nicer output, and its completion is also correct!  `brew desc -s tectonic` finds it and also prints a short blurb.  Very nice.  (But `brew desc` doesn't do casks; sigh.)

Still, it would be nice if the completion for `brew search` was more accurate.

## Output of `brew config` and `brew doctor` commands

<pre>
kgrossjo@marcie ~> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  python@2

Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See:
  https://github.com/Homebrew/brew/issues/5558

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2
  fff
  bash-completion@2

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish

# Note that I've already updated ~/.config/fish/config.fish, but it does not show up yet.

kgrossjo@marcie ~ [1]> brew config
HOMEBREW_VERSION: 2.7.1-54-g8945803
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8945803432764e6941ebbb55485fdf346d640ad0
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e1b43eb23c83ab7e3c4148bc5387b5a0f0bb0c4f
Core tap last commit: 26 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.E83rauddvD/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
</pre>

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request to fix the fish completion (https://github.com/Homebrew/brew/blob/master/completions/fish/brew.fish)? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!
