### ISSUE TITLE
Getting "zsh: command not found: brew" error when installing youtube.dl

### ISSUE THREAD

**Issue by summitisadoofus** [Homebrew/brew#10187]
Im new to macos, so apologies if Im a noob.

I installed Homebrew on M1 mac running Big Sur 11.1, and I installed XCode, but when I try to install youtube-dl I get this error message and I dont know what to do. Seems like my Macbook Pro doesnt see that I have Homebrew installed or something.

Please help me.

**Comment by carlocab** [comment]
Do

    export PATH="/opt/homebrew/bin:$PATH"

then try again. You may wish to add the line above to your `.zshrc`.

Also, please don't ignore the issue template. It's there for a reason.

**Comment by summitisadoofus** [comment]
Im a total noob like I said, I have used macos for a 2 weeks now. I have no idea what that export command means.

**Comment by summitisadoofus** [comment]
Even when I do brew search I get the same error.

**Comment by Rylan12** [comment]
Do you know if you installed Homebrew using Rosetta 2? If so, the correct command might be:

```sh
export PATH="/usr/local/bin:$PATH"
```

For more information on `export` see https://superuser.com/questions/153371/what-does-export-do-in-bash and for more info on what `PATH` is see https://medium.com/@jalendport/what-exactly-is-your-shell-path-2f076f02deb4

Can you verify that `/opt/homebrew/bin/brew` exists and contains a `brew` executable? If not, how about `/usr/local/bin/brew`?

An easy way to check is to run `ls -l /opt/homebrew/bin/brew` and `ls -l /usr/local/bin/brew`. Maybe paste the output if it's unclear to you.

**Comment by summitisadoofus** [comment]
I ran those commands.

<img width="689" alt="Screenshot 2020-12-31 at 7 32 09 PM" src="https://user-images.githubusercontent.com/76802870/103420276-163e5880-4b9f-11eb-9cf1-5e901b5b89ca.png">

**Comment by carlocab** [comment]
When sharing the output of commands, please avoid using screenshots. Instead, copy and paste the command along with its output. Use a [gist](https://gist.github.com) if you have to.

What do these commands return?
```
echo $PATH
which -a brew
export PATH="/opt/homebrew/bin:$PATH"
echo $PATH
which -a brew
```

**Comment by summitisadoofus** [comment]
Last login: Thu Dec 31 19:25:57 on ttys000
tonikumpula@Tonis-MBP ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
tonikumpula@Tonis-MBP ~ % which -a brew
brew not found
tonikumpula@Tonis-MBP ~ % export PATH="/opt/homebrew/bin:$PATH"
tonikumpula@Tonis-MBP ~ % echo $PATH
/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by carlocab** [comment]
You missed one command.

**Comment by summitisadoofus** [comment]
Last login: Thu Dec 31 19:43:32 on ttys000
tonikumpula@Tonis-MBP ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
tonikumpula@Tonis-MBP ~ % which -a brew
brew not found
tonikumpula@Tonis-MBP ~ % export PATH="/opt/homebrew/bin:$PATH"
tonikumpula@Tonis-MBP ~ % echo $PATH
/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
tonikumpula@Tonis-MBP ~ % which -a brew
/opt/homebrew/bin/brew
tonikumpula@Tonis-MBP ~ %

**Comment by carlocab** [comment]
Ok, the output of the last `which -a brew` says that your terminal can find `brew` just fine after you've done the `export PATH`. There's no reason you should be getting a `zsh: command not found: brew` error after the `export` command.

Can you paste the output of
```
export PATH="/opt/homebrew/bin:$PATH"
brew config
brew doctor
```

**Comment by summitisadoofus** [comment]
Last login: Thu Dec 31 20:03:56 on ttys000
tonikumpula@Tonis-MBP ~ % export PATH="/opt/homebrew/bin:$PATH"
tonikumpula@Tonis-MBP ~ % brew config
HOMEBREW_VERSION: 2.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdb71a5cb3029da2ef74d7e09c40575bbfb4ec72
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2c069f82c797ce58d9f8a59f43747b9af9a85724
Core tap last commit: 14 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
Rosetta 2: false
tonikumpula@Tonis-MBP ~ % brew doctor
Your system is ready to brew.
tonikumpula@Tonis-MBP ~ %

**Comment by carlocab** [comment]
So you really shouldn't be getting a `command not found` error, since being able to do `brew config` and `brew doctor` says that `zsh` can find the `brew` command just fine. You were trying to install `youtube-dl`, right?

What does this do:
```
export PATH="/opt/homebrew/bin:$PATH"
brew install youtube-dl
```

**Comment by Rylan12** [comment]
It looks like you just need to add the export line to the bottom of `~/.zshrc`. That will make it so that you won't have to run the command every time you want to use Homebrew.

The easiest way to do this is to run the following command:

```sh
echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc
```

**Comment by summitisadoofus** [comment]
Argh, I cant get this working no matter what I try.

I managed to install youtube-dl but I have to run export command everytime I wanna use homebrew. And when I try to use youtube-dl I get error zsh: no matches found

**Comment by carlocab** [comment]
What do these commands say?
```
cat $HOME/.zshrc
cat $HOME/.zprofile
```

**Comment by summitisadoofus** [comment]
Last login: Fri Jan  1 00:44:11 on ttys000
tonikumpula@Tonis-MBP ~ % cat $HOME/.zshrc
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
tonikumpula@Tonis-MBP ~ % cat $HOME/.zprofile
cat: /Users/tonikumpula/.zprofile: No such file or directory
tonikumpula@Tonis-MBP ~ %

**Comment by Rylan12** [comment]
Can you paste the output of the following commands when run in a new terminal?

```sh
echo $PATH
cat ~/.zshrc
```

**Comment by carlocab** [comment]
You can delete one of those duplicate lines. Add something like

    echo "Hello, world!"

to the start of your `.zshrc` to double-check that it’s being sourced when you start your terminal. Then restart your terminal. (If you’re using Apple Terminal, be sure to quit it completely with Command + Q.) Do you see the “hello, world” message?

**Comment by gromgit** [comment]
Just to be sure, post the output of the following:
```
echo $ZDOTDIR
echo $ZSH_VERSION
echo $BASH_VERSION
echo $tcsh
```

**Comment by summitisadoofus** [comment]
Last login: Fri Jan  1 19:11:28 on ttys000
tonikumpula@Tonis-MBP ~ % echo $ZDOTDIR

tonikumpula@Tonis-MBP ~ % echo $ZSH_VERSION
5.8
tonikumpula@Tonis-MBP ~ % echo $BASH_VERSION

tonikumpula@Tonis-MBP ~ % echo $tcsh

tonikumpula@Tonis-MBP ~ %

**Comment by carlocab** [comment]
@summitisadoofus did you check if your `.zshrc` was being sourced, as I suggested in my previous comment?

**Comment by summitisadoofus** [comment]
I dont know how.

**Comment by carlocab** [comment]
You just need to edit your `.zshrc`. You can do that using TextEdit by doing `open $HOME/.zshrc`. Remove one of the duplicated lines, then put

    echo ".zshrc sourced"

at the start of the file. Save the file, and restart your terminal. See previous comment for instructions. Does `.zshrc sourced` show up?

**Comment by summitisadoofus** [comment]
Yes it does after editing.

**Comment by carlocab** [comment]
Ok. You can remove the `echo` line now, using the same instructions.

`brew` should be in your `PATH`, so there's no explanation for the `command not found` error anymore. Are you sure it's still happening?

**Comment by summitisadoofus** [comment]
I remove the line, but still getting zsh: no matches found error when using youtube-dl in terminal.

I used this command: youtube-dl "youtube link" <- Without quotes

**Comment by summitisadoofus** [comment]
Is there a way to uninstall youtube-dl? I would like to try to reinstall it if it fixes it.

**Comment by carlocab** [comment]
What does `which -a brew` say? You can reinstall youtube-dl using
```
brew uninstall youtube-dl
brew install youtube-dl
```

`brew reinstall` should also work, but the above commands work better for me when I have a broken installation, which might be what you're having trouble with here.

**Comment by summitisadoofus** [comment]
Ok, uninstalling/reinstalling didnt help.

Last login: Fri Jan  1 19:54:50 on ttys000
tonikumpula@Tonis-MBP ~ % which -a brew
/opt/homebrew/bin/brew
tonikumpula@Tonis-MBP ~ %  

I also tried brew reinstall youtube-dl but that didnt help.

**Comment by Rylan12** [comment]
How about the following commands:

```sh
brew info youtube-dl
brew list youtube-dl
ls -l /opt/homebrew/bin/youtube-dl
```

**Comment by carlocab** [comment]
Sorry, can you copy and paste your command line, like you did with `which -a brew` above for the command you ran with `youtube-dl`? Not knowing what exactly you ran and the error message it produced is making diagnosing this problem impossible.

**Comment by summitisadoofus** [comment]
I think I know why I was getting these errors, I was coping the video address from browsers address bar, when I right click the video to copy the url and pasted it in terminal video downloaded successfully.

**Comment by Rylan12** [comment]
Glad you figured it out.

In the future, please please please always paste the _full_ command that you are running. In this case, we thought the issue was in a totally different place. It would have taken quite a long time for us to figure that out without knowing _exactly_ what command you ran.

Things like "it didn't work" or "I tried running it" aren't helpful to us. There's a lot of debugging that we can do based on the specific command that you run and the (seemingly irrelevant) output.

**Comment by carlocab** [comment]
Great, glad that's fixed!

I know learning to use the command line can be overwhelming. Here's an intro that's been recommended to me as useful for beginners: https://swcarpentry.github.io/shell-novice/

You may also wish to read about the `PATH` variable here: https://astrobiomike.github.io/unix/modifying_your_path

If you ever have trouble with something, reading the documentation (e.g. `man brew`) is always a good starting point.
