### ISSUE TITLE
No clear message given when CLT is needed for a bottle

### ISSUE THREAD

**Issue by bavardage** [Homebrew/brew#10180]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ~~ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~~
```% brew gist-logs python
Error: No logs.
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
% brew doctor
Your system is ready to brew.
```

```
% brew config
HOMEBREW_VERSION: 2.7.1-54-g8945803
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8945803432764e6941ebbb55485fdf346d640ad0
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f2cc04c45e0fde4973784f5376e061aa0ccff24a
Core tap last commit: 47 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: N/A
Xcode: 12.3
```

## What you were trying to do (and why)

Install python. The existing python install is the mac built-in one, I think.

## What happened (include command output)

<details>
  <summary>brew install python</summary>
  <pre>
Error: python@3.9: no bottle available!
You can try to install from source with e.g.
  brew install --build-from-source python@3.9
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
  </pre>
</details>

## What you expected to happen

I expect there to be a bottle available to use - at least https://formulae.brew.sh/formula/python@3.9 suggests there's a bottle available for big sur.

## Step-by-step reproduction instructions (by running `brew install` commands)

See above.

**Comment by fxcoudert** [comment]
The `brew` issue, in my opinion, is this: for a user with Xcode installed but not CLT, `brew install python@3.9` will say this:

```
Error: python@3.9: no bottle available!
You can try to install from source with e.g.
  brew install --build-from-source python@3.9
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

and the helpful message contained in the formula itself is not displayed:

```
  pour_bottle? do
    on_macos do
      reason <<~EOS
        The bottle needs the Apple Command Line Tools to be installed.
          You can install them, if desired, with:
            xcode-select --install
      EOS
      satisfy { MacOS::CLT.installed? }
    end
  end
```
