### ISSUE TITLE
Brew stopped working

### ISSUE THREAD

**Issue by jamielsharief** [Homebrew/brew#10185]
I installed imagemagic with brew, it took ages and updated everything, despite just asking to install imagemagic.

All of the sudden i started getting PHP errors, as it updated it to PHP 8. I then uninstalled PHP and tried to reinstall and started to get errors, it told me to run a git command because GIT usage etc (something to do with shallow or shadow copy). I then ran that git command and brew update did not work. I have now uninstalled brew and when i try to reinstall it does not. Same error after running the GIT command.

![image](https://user-images.githubusercontent.com/20553479/103373022-0d348500-4ad4-11eb-8e41-c44155067cf1.png)

**Comment by gromgit** [comment]
Kevin Abel (the maintainer of the `kabel/php-ext` tap) seems to have renamed his primary branch from `master` to `main`. Try the following:
```
brew untap kabel/php-ext
brew tap kabel/php-ext
brew update
```

**Comment by jamielsharief** [comment]
Thank you.
