### ISSUE TITLE
missing backtick on shell completion docs page

### ISSUE THREAD

**Issue by zmoon** [Homebrew/brew#10202]
I noticed closing backtick missing on [this page](https://docs.brew.sh/Shell-Completion) (for `.profile` in the Bash section), currently [here](https://github.com/Homebrew/brew/blame/master/docs/Shell-Completion.md#L11).

**Comment by issyl0** [comment]
It would be great if you could submit a PR for this. GitHub has a web editor perfect for simple text changes like this - click the pencil icon on the page of the file you linked.

**Comment by issyl0** [comment]
Fixed by #10204.
