### ISSUE TITLE
Allow multi-level inheritance in external taps.

### ISSUE THREAD

**Issue by shivammathur** [Homebrew/brew#10209]
## Feature suggestion

This request is to allow multi-level inheritance in external taps.

## A detailed description of the proposed feature

In external taps many formulae may have methods which are common to all formulae in the tap.
So instead of each formula inheriting from `Formula` class, it helps to abstract common methods in a parent class which then is a sub-class of the Formula class.

Checking that parent class is `Formula`  in `ast.rb` prevents this
https://github.com/Homebrew/brew/blob/4a90a5a5d6210b3ab526d68c3c9330c91bc4a55d/Library/Homebrew/utils/ast.rb#L97-L103

This was possible before the above check was added in #10064

## The motivation for the feature

Help maintain the common methods for all formulae in a single class instead of being duplicated in each formula.

## How the feature would be relevant to at least 90% of Homebrew users

It is relevant to people maintaining external taps which have methods common to each formula.

## What alternatives to the feature have been considered

Duplicating same code in each formula.

**Comment by gromgit** [comment]
Not a Ruby guru, but isn't this a use-case for mixins? https://www.sitepoint.com/ruby-mixins-2/

**Comment by shivammathur** [comment]
I guess, will have to refactor.

**Comment by SeekingMeaning** [comment]
Sorry, I missed this—it has been fixed in https://github.com/Homebrew/brew/pull/10277
