### ISSUE TITLE
brew test-bot doesn't allow formulae with patches

### ISSUE THREAD

**Issue by aconchillo** [Homebrew/brew#10216]
# Bug report

## What you were trying to do (and why)

I'm the maintainer of Guile Homebrew Tap, a tap to install Guile dependencies. I was adding a new formula which has an embedded (END) patch.

https://github.com/aconchillo/homebrew-guile

## What happened (include command output)

The github workflows (that comes with `brew tap-new`) complain that a formulae can't contain patches and that they should be submitted upstream. This seems weird as adding patches seems like a common use case, not all patches can be sent upstream as mentioned in homebrew documentation.

Note that this was working a few months ago.

## What you expected to happen

I was hoping for `brew audit` to not complain on patches.

Here's the output of one of the failures: https://github.com/aconchillo/homebrew-guile/runs/1642488881?check_suite_focus=true#step:7:32

Apologies if I should have sent/reported this somewhere else but I didn't really know where.

Thanks in advance.

**Comment by dawidd6** [comment]
Patches cannot be included in new formulae. I think it should be okay if you just ignore it this time.

**Comment by aconchillo** [comment]
Thank you @dawidd6. So, patches are not allowed when it's a new formula in the tap? But they are allowed afterwards? Is that what you meant?

**Comment by jonchang** [comment]
We should probably restrict that audit to core taps.

**Comment by carlocab** [comment]
I've run into this previously too. It'll be a problem whenever a user tries to `extract` a patched formula into their tap, so 

>We should probably restrict that audit to core taps.

this sounds like a good solution.

@aconchillo one workaround for you at the moment is to trick `brew audit` into thinking it's not a new formula, by first manually merging your formula to your master branch. Then, make some modification to it and open a PR for that modification to build a bottle.

**Comment by aconchillo** [comment]
> @aconchillo one workaround for you at the moment is to trick `brew audit` into thinking it's not a new formula, by first manually merging your formula to your master branch. Then, make some modification to it and open a PR for that modification to build a bottle.

Cool, I'll do that. Thanks! I guess you want to leave this open since this seems a real issue?
