### ISSUE TITLE
Git must be installed and in your PATH!

### ISSUE THREAD

**Issue by fbouchon** [Homebrew/brew#10228]
# Feature suggestion

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# A detailed description of the proposed feature

I've been trying to update ruby from 2.0.0 to 2.5.0 so I have to update brew. I tried several methods but none work because it says "git: no bottle available!" and "Git must be installed and in your PATH!", even though i have it installed. When I type "which git" I get /usr/bin/git.

I'm getting the following log with this error.
[2021-01-05 16:13:59] requirements_osx_brew_update_system
requirements_osx_brew_update_system () 
{ 
    if __rvm_version_compare "${_system_version}" -ge 10.7; then
        __rvm_detect_xcode_version_at_least 4.6.2 || __CLT_version_at_least 4.6.0 || { 
            \typeset ret=$?;
            rvm_error "
Xcode version older than 4.6.2 installed, download and install newer version from:

    http://connect.apple.com

After installation open Xcode, go to Downloads and install Command Line Tools.
";
            return $ret
        };
    fi;
    brew update || { 
        \typeset ret=$?;
        rvm_error "Failed to update Homebrew, follow instructions at

    https://docs.brew.sh/Common-Issues

and make sure \`brew update\` works before continuing.";
        return $ret
    }
}
current path: /Users/franciscobouchon
PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/franciscobouchon/.rvm/bin
command(2): requirements_osx_brew_update_system ruby-3.0.0
++ __rvm_version_compare 10.10 -ge 10.7
++ typeset first
+++ command printf %b '10.10\n10.7\n'
+++ printf %b '10.10\n10.7\n'
+++ __rvm_version_sort
+++ command head -n1
+++ head -n1
+++ command awk '-F[.-]' -v OFS=. '{                   # split on "." and "-", merge back with "."
    original=$0                                        # save original to preserve it before the line is changed
    for (n=1; n<10; n++) {                             # iterate through max 9 components of version
      $n=tolower($n)                                   # ignore case for sorting
      if ($n == "")                 $n="0"             # treat non existing parts as 0
      if ($n ~ /^p[0-9]/)           $n=substr($n, 2)   # old ruby -p notation
      if ($n ~ /^[0-9](rc|b)/)      $n=substr($n, 1, 1)". "substr($n, 2)   # old jruby 0RC1 notation
      if (n == 1 && $n ~ /^[0-9]/)  $n="zzz."$n        # first group must be a string
      if (n > 1 && $n ~ /^[a-z]/)   $n=" "$n           # names go before numbers thanks to space
    }
    print $0"\t"original                               # print the transformed version and original separated by \t
                                                       # so we can extract original after sorting
  }'
+++ awk '-F[.-]' -v OFS=. '{                   # split on "." and "-", merge back with "."
    original=$0                                        # save original to preserve it before the line is changed
    for (n=1; n<10; n++) {                             # iterate through max 9 components of version
      $n=tolower($n)                                   # ignore case for sorting
      if ($n == "")                 $n="0"             # treat non existing parts as 0
      if ($n ~ /^p[0-9]/)           $n=substr($n, 2)   # old ruby -p notation
      if ($n ~ /^[0-9](rc|b)/)      $n=substr($n, 1, 1)". "substr($n, 2)   # old jruby 0RC1 notation
      if (n == 1 && $n ~ /^[0-9]/)  $n="zzz."$n        # first group must be a string
      if (n > 1 && $n ~ /^[a-z]/)   $n=" "$n           # names go before numbers thanks to space
    }
    print $0"\t"original                               # print the transformed version and original separated by \t
                                                       # so we can extract original after sorting
  }'
+++ LC_ALL=C
+++ sort -t. -k 1,1d -k 2,2n -k 3,3n -k 4,4n -k 5,5n -k 6,6n -k 7,7n -k 8,8n -k 9,9n
+++ awk '-F\t' '{print $2}'
++ first=10.7
++ case "$2" in
++ [[ 10.7 == \h\e\a\d ]]
++ [[ 10.7 == \1\0\.\7 ]]
++ return 0
++ __rvm_detect_xcode_version_at_least 4.6.2
+++ __rvm_detect_xcode_version
+++ typeset version_file
+++ for version_file in /Applications/Xcode.app/Contents/version.plist /Developer/Applications/Xcode.app/Contents/version.plist
+++ [[ -f /Applications/Xcode.app/Contents/version.plist ]]
+++ [[ -x /usr/libexec/PlistBuddy ]]
+++ /usr/libexec/PlistBuddy -c 'Print CFBundleShortVersionString' /Applications/Xcode.app/Contents/version.plist
+++ return 0
++ typeset __xcode_version=6.3
++ [[ -n 6.3 ]]
++ __rvm_version_compare 6.3 -ge 4.6.2
++ typeset first
+++ command printf %b '6.3\n4.6.2\n'
+++ printf %b '6.3\n4.6.2\n'
+++ __rvm_version_sort
+++ command head -n1
+++ head -n1
+++ command awk '-F[.-]' -v OFS=. '{                   # split on "." and "-", merge back with "."
    original=$0                                        # save original to preserve it before the line is changed
    for (n=1; n<10; n++) {                             # iterate through max 9 components of version
      $n=tolower($n)                                   # ignore case for sorting
      if ($n == "")                 $n="0"             # treat non existing parts as 0
      if ($n ~ /^p[0-9]/)           $n=substr($n, 2)   # old ruby -p notation
      if ($n ~ /^[0-9](rc|b)/)      $n=substr($n, 1, 1)". "substr($n, 2)   # old jruby 0RC1 notation
      if (n == 1 && $n ~ /^[0-9]/)  $n="zzz."$n        # first group must be a string
      if (n > 1 && $n ~ /^[a-z]/)   $n=" "$n           # names go before numbers thanks to space
    }
    print $0"\t"original                               # print the transformed version and original separated by \t
                                                       # so we can extract original after sorting
  }'
+++ awk '-F[.-]' -v OFS=. '{                   # split on "." and "-", merge back with "."
    original=$0                                        # save original to preserve it before the line is changed
    for (n=1; n<10; n++) {                             # iterate through max 9 components of version
      $n=tolower($n)                                   # ignore case for sorting
      if ($n == "")                 $n="0"             # treat non existing parts as 0
      if ($n ~ /^p[0-9]/)           $n=substr($n, 2)   # old ruby -p notation
      if ($n ~ /^[0-9](rc|b)/)      $n=substr($n, 1, 1)". "substr($n, 2)   # old jruby 0RC1 notation
      if (n == 1 && $n ~ /^[0-9]/)  $n="zzz."$n        # first group must be a string
      if (n > 1 && $n ~ /^[a-z]/)   $n=" "$n           # names go before numbers thanks to space
    }
    print $0"\t"original                               # print the transformed version and original separated by \t
                                                       # so we can extract original after sorting
  }'
+++ LC_ALL=C
+++ sort -t. -k 1,1d -k 2,2n -k 3,3n -k 4,4n -k 5,5n -k 6,6n -k 7,7n -k 8,8n -k 9,9n
+++ awk '-F\t' '{print $2}'
++ first=4.6.2
++ case "$2" in
++ [[ 4.6.2 == \h\e\a\d ]]
++ [[ 4.6.2 == \4\.\6\.\2 ]]
++ return 0
++ true
++ brew update
Warning: You are using macOS 10.10.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

Error: git: no bottle available!
You can try to install from source with:
  brew install --build-from-source git
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
Error: Git must be installed and in your PATH!
++ typeset ret=1
++ rvm_error 'Failed to update Homebrew, follow instructions at

    https://docs.brew.sh/Common-Issues

and make sure `brew update` works before continuing.'
++ rvm_pretty_print stderr
++ case "${rvm_pretty_print_flag:=auto}" in
++ case "${TERM:-dumb}" in
++ case "$1" in
++ [[ -t 2 ]]
++ return 1
++ printf %b 'Failed to update Homebrew, follow instructions at

    https://docs.brew.sh/Common-Issues

and make sure `brew update` works before continuing.\n'
++ return 1
 

# The motivation for the feature

All of this is for installing Ruby on Rails. I'm using mac os yosemite, so if anyone had a similar problem I would be so greatful if you could help me.
Thank you so much.

# How the feature would be relevant to at least 90% of Homebrew users

# What alternatives to the feature have been considered

I've tried different types of installation methods, but none of those work.

**Comment by gromgit** [comment]
> Warning: You are using macOS 10.10.

WARNING: You're _way_ outside the Homebrew OS support window, so all installations going forward will be from source (hence the "no bottle available" error), may well fail miserably, and you'll be lucky to get help from anyone at that point.

All that said, what is the output of `brew config` on your system?

**Comment by fbouchon** [comment]
I'm getting this in brew config

HOMEBREW_VERSION: 2.7.1-143-gb678af3-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: b678af3fa33a6faaf8645ca8c1064e58fc2458b5
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eb3250c061f1bb6764be295902541529d8e807df
Core tap last commit: 22 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.8jdBoFypQf/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit penryn
Clang: 6.1 build 602
Git: 2.3.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 1.8.0_202, 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
CLT: 7.2.0.0.1.1447826929
Xcode: 6.3
XQuartz: 2.7.11 => /opt/X11
