### ISSUE TITLE
Update shell completions

### ISSUE THREAD

**Issue by Rylan12** [Homebrew/brew#10223]
# Feature suggestion

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# A detailed description of the proposed feature

Currently, many of our tab completions for commands are outdated. Some will autofill options that are no longer valid, some are missing options, etc.

# The motivation for the feature

We should strive to keep our completions up to date with our commands to give users a flawless completion experience (sounds like a sales pitch 😅)

# How the feature would be relevant to at least 90% of Homebrew users

In its current state, tab completion can't really be trusted. If we offer completions, we should offer _correct_ completions.

# What alternatives to the feature have been considered

The alternatives are to either keep bad completions or remove completions all together. Neither are good options.

---

# My Questions

- Should our completion be aware of _all_ options? If not, what determines which options are available? Follow-up: what about commands like `install` that have lots and lots of options? If this is a hard yes, the rest of the questions don't apply.
  - My view: yes. All options should be tab-completable.

- For commands like `install` that have lots and lots of options, do we still want to include them all? They would be as context-specific as possible (within reason) so, for example, an existing `--formula` option should restrict suggestions to options that are compatible with formulae.
    - My view: no, show all options. As the user completes more of the command the options can narrow.

- Some options have alternate names. For example, `--formula` and `--formulae` are equivalent. Should they both be listed?
  - My view: no need to list both. List the simpler or main name. Listing multiple will add confusion

- Extension of the above: how do we complete options like `--[no-]quarantine`?
  - My view: treat it as two separate options: `--quarantine` and `--no-quarantine`

- Do we always complete global options (`--debug`, `--verbose`, `--help`, `--quiet`)? For certain commands, these global options are pretty much useless. Do we still show them? This would not affect the commands that override global options with other functionality (like `install --debug`).
  - My view: yes, although I'm not set on this one. I think `--help` should always be shown.

- How intelligent should the completions be? Most commands are pretty straight forward in that they have very few option conflicts or requirements. Some, though, are much more complex. Should we strive for simpler completions or more context-accurate completions?
  - My view: we should aim to get completions to be as context-accurate as possible.

- Lastly, how do we avoid completions becoming so out of date in the future? Ideally, `brew man` would update these completions, but given their complexity, I'm not sure that's feasible. What other options are there to keep completions better synced with command options? Maybe we can write a test somehow that detects hitting tab on `brew <command> --` will return a complete list of options? This is less urgent and is something that can be brainstormed more in the future.

_I am volunteering to do the work here. In fact, I've already started some of it locally. It's a rather large undertaking, though, so I wanted to clear a few things up before spending too much time on it to try to avoid wasting work._

**Comment by Rylan12** [comment]
Actually, it may not be as difficult as I thought to automatically generate these completions. I `Homebrew.<command>_args.processed_options` and `.conflicts` can help us parse the options to generate completion code. This is something I'll need to look into a little bit more. If anyone has any ideas or pointers about this, I'd be happy to hear them.

If this is done, I figure it would go into the `brew man` command so that any time a command signature is modified the completions will be modified as well.

**Comment by MikeMcQuaid** [comment]
> In its current state, tab completion can't really be trusted. If we offer completions, we should offer _correct_ completions.
> * Should our completion be aware of _all_ options?
> * For commands like `install` that have lots and lots of options, do we still want to include them all?
> * My view: treat it as two separate options: `--quarantine` and `--no-quarantine`
> * Do we always complete global options (`--debug`, `--verbose`, `--help`, `--quiet`)?

Yes to all the above.

> * Should they both be listed?

No.

> * Should we strive for simpler completions or more context-accurate completions?

Aim for context-accurate, accept simpler as a first step/PR.

> Actually, it may not be as difficult as I thought to automatically generate these completions. I `Homebrew.<command>_args.processed_options` and `.conflicts` can help us parse the options to generate completion code. This is something I'll need to look into a little bit more. If anyone has any ideas or pointers about this, I'd be happy to hear them.
> 
> If this is done, I figure it would go into the `brew man` command so that any time a command signature is modified the completions will be modified as well.

Yes, this seems like the right thing to do here. https://github.com/Homebrew/brew/blob/a805a5ea16e8d8c38369de16dbe35d3d0fe992ab/Library/Homebrew/commands.rb#L193-L199 is also something that may be useful.

I think, as a first pass, just dumping the commands and options while omitting conflicts would be fine.

**Comment by EricFromCanada** [comment]
I added the `brew options --compact --command <cmd>` functionality with the intent that it'd be used for automatic completion generation.

**Comment by Rylan12** [comment]
Thanks, that's very helpful!

I'll start out simple and work up from there. Watch for a PR soon.

_(I changed from `help wanted` to `in progress` as I've started working on this. I don't think we need contributors opening PRs at the moment if `brew man` is going to automatically generate these soon.)_

**Comment by vollkommenheit** [comment]
Apologies for going off on a tangent, but it's related to shell completion: Given Apple is signaling moving away from bash to zsh/dash (per sources such as https://scriptingosx.com/2020/06/about-bash-zsh-sh-and-dash-in-macos-catalina-and-beyond/), any chance /usr/local/etc/bash_completion.d/brew could be made zsh/dash/POSIX-compatible (while keeping it being ... bash_completion), now? 

According to "dash -n", the only bit of bashism in there is all the `COMPREPLY=($(compgen -W "$list" -- "$cur"))`

**Comment by Rylan12** [comment]
@vollkommenheit pardon my unfamiliarity with the details of this. We do have zsh completions available as well. Are those not sufficient?

**Comment by vollkommenheit** [comment]
@Rylan12, ah yes, I wasn't aware of that. That will certainly do. Thanks! I had never heard of dash until reading about it in that https://scriptingosx.com blog post/article; I did use zsh a bit (while wishing for bash) back in the OS X 10.3 days, IIRC. Since dash is "news" to me, I assumed it'd be replacing bash all by itself, while discounting zsh's "comeback". I only realized after making the post above that dash appears to be more barebone/lightweight, and therefore is probably not intended by Apple to be THE interactive shell replacement on macOS going forward--that role would likely go to zsh then. So I'm glad homebrew is already well-positioned for that change.

**Comment by Rylan12** [comment]
I'm glad that will work. Stay tuned for some improvements to the zsh completions coming (hopfully) soon. At the moment they're a tad outdated (hence me opening this issue).

Thanks for sharing the article. It's first time I've heard of `dash` as well. Yeah, I agree, it seems that zsh is doing to be the way to go rather than dash, and dash is really only there for compatibility or the `/bin/sh` functionality. If you're looking for `dash` completions, it seems that you're out of luck given [`dash` doesn't support completions](https://unix.stackexchange.com/questions/158369/add-autocompletion-in-dash).

**Comment by MikeMcQuaid** [comment]
I think this is now done! Nice work @Rylan12. Feel free to reopen if you disagree.
