### ISSUE TITLE
Can't brew update: Error homebrew-cask is a shallow clone

### ISSUE THREAD

**Issue by cruzzer** [Homebrew/brew#10238]
## Description

This appears to be the same issue as seen in this closed [issue](https://github.com/Homebrew/brew/issues/9420). I tried the same commands mentioned there. 

<pre>
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch --unshallow
</pre>

But I've not had success with these commands.

# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

$ brew update

## What happened (include command output)

<pre>
$ brew update

Error:
  homebrew-cask is a shallow clone.
To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!
Minix:Applications cruiser$ git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch --unshallow
fatal: --unshallow on a complete repository does not make sense
</pre>

## What you expected to happen

System should update itself

## Step-by-step reproduction instructions (by running `brew` commands)

$ brew update

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.7.0-39-gd6692d2
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6692d2883a34fdb1e39e0001b3caf7ff681c7a0
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 84c3b459a7cc5e545c4f7a3e9aec427e0f9acf7a
Core tap last commit: 2 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.k4BpTbpumJ/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 6
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 10.0 build 1001
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.2, 11.0.5, 1.8.0_111
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
</pre>

<pre>
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
</pre>

**Comment by MikeMcQuaid** [comment]
This issue is specific to your system. Delete those directories and rerun `brew update` and it should resolve itself.

> * [x]  ran `brew doctor`, fixed all issues and can still reproduce the problem?

You did not so please don't say you did.

**Comment by cruzzer** [comment]
Thank you for your response. Maybe I ran "brew doctor" incorrectly. I attached the output of "brew doctor" at the end of my report and attached it again below here, or should I be running something else?

I would be happy to delete a folder, but which one would that be?

<pre>
host:~ user$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

</pre>

**Comment by MikeMcQuaid** [comment]
> I would be happy to delete a folder, but which one would that be?

`/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core`, `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask`




> On a second note, I've also ran the commands listed in "brew doctor" with reinstalling the xcode tools, but the error remains.



> If that doesn't show you an update run:
>   sudo rm -rf /Library/Developer/CommandLineTools
>   sudo xcode-select --install

Did you run these?

**Comment by cruzzer** [comment]
1. Deleting those folders worked, updating works again. Issue fixed. thank you

2. I did run the "brew doctor" commands, but it still claims that newer tools are available.

<pre>
softwareupdate --all --install --force
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
</pre>

The new xcode appears to be installed, but brew doctor still 

![Screenshot 2021-01-06 at 16 52 03](https://user-images.githubusercontent.com/2527732/103788813-92251e80-503f-11eb-8851-3ed5bf0835a8.png)

Should I just ignore this for now, or make a new issue?

**Comment by carlocab** [comment]
>Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
