### ISSUE TITLE
Fresh brew install returns incorrect value for --prefix openssl

### ISSUE THREAD

**Issue by dcow** [Homebrew/brew#10261]
# Bug report

It seems a fresh installation of `brew` reports a value for `brew --prefix openssl` despite the keg not being installed.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to `cargo install cargo-generate`, which uses `brew` to find the "system" openssl installation. The install failed saying it could not find openssl. 

## What happened (include command output)
I doubled checked and ran:

```
% brew --prefix openssl
/opt/homebrew/Cellar/openssl@1.1/1.1.1i
```

## What you expected to happen

I expected no path to be reported. And when I tried to list the directory it did not exist:
```
% ls -lah $(brew --prefix openssl)
ls: /opt/homebrew/Cellar/openssl@1.1/1.1.1i: No such file or directory
% ls /opt/homebrew/Cellar/openssl@1.1
ls: /opt/homebrew/Cellar/openssl@1.1: No such file or directory
% ls /opt/homebrew/Cellar/
%
```

After installing openssl via `brew install openssl`, a different prefix is reported:
```
brew --prefix openssl
/opt/homebrew/opt/openssl@1.1
```
*note the missing `/1.1.1i` suffix.

Anyway, the installation of `cargo-generate` succeeds after `brew install openssl`. But I suspect there is something up here. Should brew be reporting a prefix for a cask that does not exist on the system? It looks like it does that for other formula that have not been installed when I check just now, so perhaps that is intended behavior. But why would the prefix _change_ once the formula has been installed?

## Step-by-step reproduction instructions (by running `brew` commands)

I believe simply installing homebrew using the install script and then running the command above yields the incorrect path.

## Output of `brew config` and `brew doctor` commands

<pre>
% brew doctor
Your system is ready to brew.
% brew config
HOMEBREW_VERSION: 2.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: dad7dc6a1498b80770d98f2d7cd6fb927c300bbb
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ff9062c21bd1491b03541c62bb04a767f9957de2
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
Rosetta 2: false
</pre>

**Comment by gromgit** [comment]
> I expected no path to be reported.

As the man page states:
>
>   --prefix [formula]
> [...]
>       If formula is provided, display the location in the Cellar where formula is **or would be** installed.

so what you expect would actually be considered a bug in Homebrew, unless the formula doesn't exist:
```sh
$ brew --prefix dummy
Error: No available formula with the name "dummy".
```

> why would the prefix change once the formula has been installed?

A maintainer would have to definitively comment on the _why_, but the versionless `opt` prefix is commonly used for builds both inside and outside Homebrew, to avoid linking against version-locked paths that would instantly break on an upgrade.

**Comment by dcow** [comment]
Hmm okay I will talk to the `openssl-sys` crate maintainers to make sure they understand this behavior and that it is reflected in the documentation if necessary. Alternatively, is there an option available that acts more like `pkg-config` and prints only the prefix of installed brew formula? The crate in question is essentially using `brew --prefix` as a replacement for `pkg-config`...

**Comment by gromgit** [comment]
The simplest solution is to actually check the output of `brew --prefix`, since you'll need it in any case:
* If it contains `/opt/`, the dependent is installed and can be used directly
* If it _doesn't contain `/opt/`, the dependent is missing and needs to be installed
* If it's _empty_ (which should also result in `brew --prefix` returning a non-zero exit status), something's wrong that requires user intervention

**Comment by gromgit** [comment]
Scratch what I wrote previously. A better algorithm makes no assumption about the exact components of `brew --prefix`, and will therefore continue to work no matter how many times the Homebrew team decides to reorganize the directory hierarchy:

* If `brew --prefix` returns an error, something went wrong (duh!)
* If the output of `brew --prefix` doesn't exist, the formula hasn't been installed, and you can automatically install it if you want
* If the output of `brew --prefix` exists, you're good to go.

Note that `brew --prefix` has a distinct advantage over `pkg-config`, despite your preference for the latter. If you get nothing back from `pkg-config`, you can't distinguish between "package not installed" and "package doesn't exist" (i.e. you typed it wrong). With `brew --prefix`, typo'd formula names are instantly revealed.

**Comment by MikeMcQuaid** [comment]
> Alternatively, is there an option available that acts more like `pkg-config` and only prints the prefix of a formula if it is installed?

No option exists but I can see the use-case in adding it. Any suggestions on naming, anyone?

**Comment by gromgit** [comment]
Honestly, `--prefix` is the most logical.

Also, `brew --prefix` output for non-installed formula is IIRC equivalent to the already-deleted `brew diy`. Is there a reason we can't simply make `brew --prefix` return an empty string if the formula isn't installed?

**Comment by MikeMcQuaid** [comment]
Sorry, to clarify, I'm proposing an additional flag to prefix so that `brew --prefix --something` would produce no output and/or a non-zero exit code if it isn't already installed. Maybe `brew --prefix --installed`?

**Comment by gromgit** [comment]
`brew --prefix --installed` is about as good as any, given the logic it's meant to modify (if set, print empty string for uninstalled formulae, instead of formula's Cellar prefix).

I think I've just enough Ruby under the belt to knock out a PR for this.

**Comment by dcow** [comment]
`brew --prefix --pkg-config` although at that point why not just `brew --pkg-config`? Alternatives `brew --prefix --local`, `brew --prefix=include-path`, or `brew --prefix=local`. Of course `brew --prefix --installed` works nicely too. 

Few more ideas: 
```
brew pkg-config include-path
brew pkg-config prefix
brew prefix --installed
brew prefix --local
```
(why is prefix a -- option rather than a sub-command anyway?)

**Comment by dcow** [comment]
Oh, another thought, the list command is already limited to installed packages:
```
brew list --prefix
```

**Comment by gromgit** [comment]
Sorry, accidentally nuked my notifications and missed the latest PR comments. Still in progress...
