### ISSUE TITLE
An error shows when using brew command in M1

### ISSUE THREAD

**Issue by albertsundq** [Homebrew/brew#10271]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

run brew search/doctor/update
## What happened (include command output)

An error is shown in terminal as bellowed

/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory

<details>
  <summary>Command output</summary>
  <pre>

/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory

  </pre>
</details>

## What you expected to happen

No error be output

## Step-by-step reproduction instructions (by running `brew` commands)

run brew command
## Output of `brew config` and `brew doctor` commands

<pre>

sunyuqi@MacBook-Air local % brew config
/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory
HOMEBREW_VERSION: 2.7.2
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: dad7dc6a1498b80770d98f2d7cd6fb927c300bbb
Last commit: 3 days ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: 70ef7a2f9ff35b3a3e6197f519f4666d4c968a22
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.9.1
macOS: 11.0.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
Rosetta 2: false
sunyuqi@MacBook-Air local % brew doctor
/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.ustc.edu.cn/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/opt/homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.ustc.edu.cn/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/opt/homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/python3-config
  /usr/local/bin/pcre2-config
  /usr/local/bin/python3.8-config
</pre>

**Comment by gromgit** [comment]
> ```
> Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
> The current git origin is:
>   https://mirrors.ustc.edu.cn/brew.git
> ```

I know the Homebrew core tap repo is large enough to cause problems behind the so-called "Great Firewall of China", but is there a reason to use a mirror for the Homebrew _software_? You really want to be as up-to-date as possible for this part of Homebrew.

I strongly suggest doing what `brew doctor` says and reset the software repo upstream:
```
With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/opt/homebrew" remote set-url origin https://github.com/Homebrew/brew
```
then `brew update` and `brew config` again. The `brew update` will likely still show you the same error you've been getting, but `brew config` should complete without error.

**Comment by albertsundq** [comment]
> then `brew update` and `brew config` again. The `brew update` will likely still show you the same error you've been getting, but `brew config` should complete without error.

Still facing issue after the suggested way. Bellowed output be printed.

sunyuqi@MacBook-Air homebrew % brew config
/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory
HOMEBREW_VERSION: 2.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: dad7dc6a1498b80770d98f2d7cd6fb927c300bbb
Last commit: 3 days ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: ebf42bd33d8e9f8ffd86d6015b69defe30aba700
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.9.1
macOS: 11.0.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
Rosetta 2: false

**Comment by gromgit** [comment]
That's weird. Try `bash -x /opt/homebrew/bin/brew config 2>/tmp/brew.dbg`, then post the contents of `/tmp/brew.dbg`.

**Comment by albertsundq** [comment]
Issue has been identified.
RCA as bellowed.

**Background**
Before, I have a Intel MacBook, I installed brew in it.
When new M1 MacBook coming, I used apple's data transfer to make M1 MacBook same as old one, so brew be transferred, too.

**Issue Root Cause**
There's a symlink for /usr/local/bin/brew which link to /usr/local/Homebrew/bin/brew.
I had removed Intel homebrew before, so the link be die.
In opt/homebrew/bin/brew, There's a condition as bellowed

`# Try to find a /usr/local HOMEBREW_PREFIX where possible (for bottles)
if [[ -L "/usr/local/bin/brew" && ! -L "$HOMEBREW_PREFIX/Cellar" ]]
then
  USR_LOCAL_BREW_FILE_DIRECTORY="$(symlink_target_directory "/usr/local/bin/brew" "/usr/local/bin")"
  USR_LOCAL_HOMEBREW_REPOSITORY="${USR_LOCAL_BREW_FILE_DIRECTORY%/*}"
  if [[ "$HOMEBREW_REPOSITORY" = "$USR_LOCAL_HOMEBREW_REPOSITORY" ]]
  then
    HOMEBREW_PREFIX="/usr/local"
  fi
fi`

So the condition is true, then error be printed in terminal.

**Solution**
Remove /usr/local/bin/brew as bellowed command in terminal, issue be resolved.
`rm -rf /usr/local/binbrew`
