### ISSUE TITLE
Better documentation for the shallow clone suggestion

### ISSUE THREAD

**Issue by jcpayne** [Homebrew/brew#10274]
The current instruction:
> To `brew update`, first run:
>   git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
>   git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow

is discussed in [Issue 9430](https://github.com/Homebrew/brew/issues/9430), which was just closed.  @vitorgalvao wrote "If a user understands enough of the command-line to use Homebrew; they’re likely capable of understanding that line and running that command."  Yes sure, kind of, maybe, not really.

I use the command line and git every day, but I was confused at first:
1. I didn't realize (or remember) that my original installation of Homebrew was a git clone (or was it?);
2. I had no idea where the Homebrew git repo is on my machine--looks like maybe it's in `/usr/local/`? 
3. It's an unusual git command.  `git -C` runs git "_as if git was started in <path> instead of the current working directory._"  Um, okay, so this is a `git fetch` operation.  But I ran it from my home directory without thinking, and then wondered "Does git know where to find the homebrew repo?"  And then I wondered "What happens to the ~500 Mb of files that it just downloaded?  Are they needed for next time; i.e., is my Homebrew installation _always_ going to run from that repo in the future?"  (I assume yes, but that's not explained -- the alternative, which some users will worry about, is that you've just created a duplicate installation which is wasting space, or downloaded a pile of temporary files to some hidden location.)  

My suggestion:
1. Clarify that homebrew is (usually? always?) installed in a git repo and that the `git -C fetch` command will know how to find and update it.
2. The message should specify more clearly that **three steps are required**:
    1. run the `homebrew-core fetch` command
    2. run the `homebrew-cask fetch` command
    3. run `brew update`

I expect that you will have a lot of confused and unhappy users until you improve the message.

**Comment by vitorgalvao** [comment]
> in [Issue 9430](https://github.com/Homebrew/brew/issues/9430), which was just closed.

No, it wasn’t “just closed”. It has multiple replies, including from two maintainers; the conversation continued even after it was closed; and it [ended with a third maintainer](https://github.com/Homebrew/brew/issues/9430#issuecomment-739978433) making a PR to improve the messaging.

You’re free [to follow that example](https://github.com/Homebrew/brew/pull/9447) and submit a new PR for discussion.

**Comment by jcpayne** [comment]
Perhaps you misunderstood me -- by "just closed"' I meant "recently closed" (3 days ago).  I am trying to be constructive, hence the suggestions I made.   You suggest that I submit "a new PR for discussion."  But I do not really have the time to dig into the source code for Homebrew.  Should I move this somewhere else?

**Comment by Rylan12** [comment]
@jcpayne thanks for the feedback. You're right, we have received several issues from people who are confused by this. However, most of the time, the issues are simply that the user doesn't want to read the instructions we've provided or run the command.

That being said, if you think the current wording can be improved to increase clarity, please do open a PR. As maintainers, we are super well-versed in the inner workings of Homebrew so we don't always explain things in a way that makes sense to all users who may be less knowledgeable about what's going on. Plus, the maintainers have already modified the message several times, so I think the best way we can improve it is with a suggestion from a non-maintainer.

The message comes from [`Library/Homebrew/cmd/update.sh`](https://github.com/Homebrew/brew/blob/d75e9c99b34bc55e89a6ea0d3520273451e06131/Library/Homebrew/cmd/update.sh#L407-L419):

https://github.com/Homebrew/brew/blob/d75e9c99b34bc55e89a6ea0d3520273451e06131/Library/Homebrew/cmd/update.sh#L407-L419

It's mostly just text, so it should be relatively simple to modify even if you're not fluent in bash.

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template. This should be opened in Homebrew/discussions rather than Homebrew/brew.

We literally tell you what commands to run. You don't need to know that Homebrew uses Git in order to do that and most people do not have a problem here.
