### ISSUE TITLE
ZeroMQ can be found but not installed. Similar matching not working?

### ISSUE THREAD

**Issue by richardwei6** [Homebrew/brew#10286]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install ZeroMQ

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  Last login: Sun Jan 10 20:29:57 on console
richyvm@Richards-Mac ~ % brew install zeromq
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 1 formula.
==> Updated Casks
Updated 3 casks.

==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install zeromq@4.3
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "zeromq@4.3".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install pkg-config
Warning: pkg-config 0.29.2_3 is already installed and up-to-date
To reinstall 0.29.2_3, run `brew reinstall pkg-config`
richyvm@Richards-Mac ~ % brew install zeromq
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install libzmq
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "libzmq".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew update
Already up-to-date.
richyvm@Richards-Mac ~ % ^[[200~git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core.git~
zsh: bad pattern: ^[[200~git
richyvm@Richards-Mac ~ % git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core.git
richyvm@Richards-Mac ~ % brew install zeromq
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install zeromq --HEAD
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install zeromq.rb    
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "zeromq.rb".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install 0zmq     
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "0zmq".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install zmq 
==> Searching for similarly named formulae...
These similarly named formulae were found:
czmq                                     zmqpp
To install one of them, run (for example):
  brew install czmq
Error: No available formula or cask with the name "zmq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install 0mq
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "0mq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew search zeromq
==> Formulae
zeromq
richyvm@Richards-Mac ~ % brew install zeromq
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install zeromq
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install zeromq
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install zeromq 
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install  zeromq 
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % brew install zeromq  
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac ~ % clear

richyvm@Richards-Mac ~ % brew update
Already up-to-date.
richyvm@Richards-Mac ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3-config

Warning: Some installed formulae are not readable:
  zeromq: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zeromq.rb:49: syntax error, unexpected <<, expecting end
<<<<<<< Updated upstream
^~
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zeromq.rb:51: syntax error, unexpected ===, expecting end
=======
^~~
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zeromq.rb:53: syntax error, unexpected >>, expecting end
>>>>>>> Stashed changes
^~

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
[Include like 1000s of lines of files]
richyvm@Richards-Mac local % brew update
Already up-to-date.
richyvm@Richards-Mac local % brew install zeromq
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
bError: No formulae found in taps.
richyvm@Richards-Mac local % brew reinstall zeromq
Error: No available formula or cask with the name "zeromq".
richyvm@Richards-Mac local % brew config
HOMEBREW_VERSION: 2.7.2-80-g6968c19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6968c199e862299ab45e7a8bdc0362235d6484b1
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: feae7f8daea40cefbf38622753abdc5a918bfaa7
Core tap last commit: 19 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.32.2
Xcode: 12.3
richyvm@Richards-Mac local % brew install zeromq
==> Searching for similarly named formulae...
This similarly named formula was found:
zeromq
To install it, run:
  brew install zeromq
Error: No available formula or cask with the name "zeromq".
==> Searching taps on GitHub...
Error: No formulae found in taps.
richyvm@Richards-Mac local % 

  </pre>
</details>

## What you expected to happen

ZeroMQ to successfully install

## Step-by-step reproduction instructions (by running `brew` commands)

`brew install zeromq`

## Output of `brew config` and `brew doctor` commands

<pre>

HOMEBREW_VERSION: 2.7.2-80-g6968c19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6968c199e862299ab45e7a8bdc0362235d6484b1
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: feae7f8daea40cefbf38622753abdc5a918bfaa7
Core tap last commit: 29 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.32.2
Xcode: 12.3

[You can find doctor command output above in console output]
</pre>

**Comment by gromgit** [comment]
```
Warning: Some installed formulae are not readable:

zeromq: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zeromq.rb:49: syntax error, unexpected <<, expecting end

<<<<<<< Updated upstream

^~

/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zeromq.rb:51: syntax error, unexpected ===, expecting end

^~~

/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zeromq.rb:53: syntax error, unexpected >>, expecting end









Stashed changes

^~
```
Looks like you tried to `git stash pop` a set of changes that conflicts with the current version of the formula. IIRC, the original stash should still be in the stack (since the stash merge failed), so:
```
git -C $(brew --repo homebrew/core) checkout -- Formula/zeromq.rb
```
should reset the formula to Homebrew-current.

**Comment by richardwei6** [comment]
> ```
> Warning: Some installed formulae are not readable:
> 
> zeromq: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zeromq.rb:49: syntax error, unexpected <<, expecting end
> 
> <<<<<<< Updated upstream
> 
> ^~
> 
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zeromq.rb:51: syntax error, unexpected ===, expecting end
> 
> ^~~
> 
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zeromq.rb:53: syntax error, unexpected >>, expecting end
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Stashed changes
> 
> ^~
> ```
> 
> Looks like you tried to `git stash pop` a set of changes that conflicts with the current version of the formula. IIRC, the original stash should still be in the stack (since the stash merge failed), so:
> 
> ```
> git -C $(brew --repo homebrew/core) checkout -- Formula/zeromq.rb
> ```
> 
> should reset the formula to Homebrew-current, then you can figure out how to resolve the conflict with your stashed changes.

I got this error: `error: pathspec 'Formula/zeromq.rb' did not match any file(s) known to git`.

**Comment by gromgit** [comment]
Did you `git rm Formula/zeromq.rb` at some point?

It seems like you've somewhat mangled your `homebrew/core` tap, so a `brew update-reset $(brew --repo homebrew/core)` would be advisable at this point.

**Comment by richardwei6** [comment]
> brew update-reset $(brew --repo homebrew/core)

Perfect, that worked. Thanks. It seemed that it was something on my side then.
