### ISSUE TITLE
Making `install.sh` compatible with brewdo

### ISSUE THREAD

**Issue by alexreg** [Homebrew/brew#10281]
Would it be alright if I submitted a PR that slightly modified [`install.sh`](https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh) so that an environment variable can be used to turn off the chown-ing & chmod-ing, for the purpose of [brewdo](https://github.com/brewdo/brewdo) using this script for installation but handling ownership and permissions within `/usr/local` itself? The diff would probably just be a few lines of if-statement. It wouldn't be ideal to maintain a fork of this install script, so anything in this respect would be appreciated.

**Comment by MikeMcQuaid** [comment]
No, sorry. There's PRs ongoing working on multiuser support which may be what you're interested in.

Please always fill out the issue template and ask questions like this in Homebrew/discussions.
