### ISSUE TITLE
Homebrew takes too long to install

### ISSUE THREAD

**Issue by paulmillr** [Homebrew/brew#10293]
I think you should create a clean git repo. Waiting 30 minutes on perfect connection >=100mbps is unacceptable.

What about folks with 0.5mbps connection?

Is there any plan to increase the speed?

**Comment by carlocab** [comment]
>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

You may wish to consider posting this at https://github.com/Homebrew/discussions instead.

**Comment by paulmillr** [comment]
Why are you making this more bureaucratic than required?

This is clearly a bug. It happens at all new installs. It does not have an "expected" or "actual" parts. It's just slow. The reason is: huge git repo.

Git repo needs to be shrunk down. 

This is not a "discussion", this is a bug.

**Comment by MikeMcQuaid** [comment]
> Why are you making this more bureaucratic than required?

Why are you not reading or following the instructions the issue template asks you to?

> Git repo needs to be shrunk down.

This cannot be done without rewriting history. Rewriting history will break all existing checkouts.

If it were as simple as you make it out to be: we'd have done it already.

Please adjust your tone and read the issue template for future issues.
