### ISSUE TITLE
brew upgrade: show formula caveats after casks have been upgraded

### ISSUE THREAD

**Issue by max-ae** [Homebrew/brew#10290]
# Feature suggestion

# A detailed description of the proposed feature
Currently, `brew upgrade` upgrades formulae, shows a summary of caveats, and then proceeds to upgrade casks.
The caveats therefore get 'lost' in the middle of the shell output if the output of the cask upgrade process is lengthy. This is not ideal.

# The motivation for the feature
Overlooking caveats for formula or having to search for them in lengthy shell output is not ideal behaviour.
This issue only occurs since the `brew cask upgrade` command has been incorporated into `brew upgrade` and I think what I described, having a summary of caveats at the end of the upgrade process is the actual desired behaviour. 

# How the feature would be relevant to at least 90% of Homebrew users
Homebrew users would not have to check the complete upgrade log for formula caveats. 

# What alternatives to the feature have been considered
Only use `brew upgrade --formula` and `brew upgrade --cask` instead of the combined `brew upgrade` command.

**Comment by SeekingMeaning** [comment]
This should be fixed in master (and the next brew release); thank you for opening an issue, @max-ae!

**Comment by max-ae** [comment]
Awesome to see this resolved this quickly! @SeekingMeaning
