### ISSUE TITLE
brew list | grep xyz has been disabled why?

### ISSUE THREAD

**Issue by davidbdeath** [Homebrew/brew#10291]
brew list | grep xyz has been disabled why?

**Comment by carlocab** [comment]
>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by tlk** [comment]
Related: https://github.com/Homebrew/discussions/discussions/519
