### ISSUE TITLE
Homebrew takes too long to install

### ISSUE THREAD

**Issue by paulmillr** [Homebrew/brew#10294]
# Bug report

I think you should create a clean git repo. Waiting 30 minutes on perfect connection >=100mbps is unacceptable.

What about folks with 0.5mbps connection?

Is there any plan to increase the speed? E.g. resetting the repo every year and having a script that migrates from formulas-2020 to formulas-2021

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install homebrew

## What happened (include command output)

Takes 30 minutes

<details>
  <summary>Command output</summary>
  <pre>

  git clone output that takes 30 mins

  </pre>
</details>

## What you expected to happen

Install in 1 minute

## Step-by-step reproduction instructions (by running `brew` commands)

Install homebrew with command on its site

## Output of `brew config` and `brew doctor` commands

<pre>
Not applicable
</pre>

**Comment by paulmillr** [comment]
x-post after you've closed #10293

**Comment by carlocab** [comment]
You seem to be the only one complaining about half an hour install times, so it seems unlikely that this is a bug in Homebrew's installer rather than a problem on your end.

Just to check, I timed how long it takes to clone the homebrew/core repo from scratch:
```
❯ time git clone https://github.com/Homebrew/homebrew-core.git
Cloning into 'homebrew-core'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 886330 (delta 30), reused 25 (delta 14), pack-reused 886278
Receiving objects: 100% (886330/886330), 357.95 MiB | 27.55 MiB/s, done.
Resolving deltas: 100% (600649/600649), done.
Updating files: 100% (5727/5727), done.
git clone https://github.com/Homebrew/homebrew-core.git  169.62s user 19.53s system 154% cpu 2:02.18 total
```
This step is the major bottleneck of the install script, so it shouldn't take much longer than this.

I also timed the install script:
```
./install.sh  208.76s user 21.67s system 119% cpu 3:13.56 total
```
and, indeed, it only takes a little bit longer than cloning homebrew/core on its own.

I also want to note that you've done none of these:
>- [ ] ran `brew update` and can still reproduce the problem?
>- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
>- [ ] ran `brew config` and `brew doctor` and included their output with your issue?
despite claiming you have.

This is not a bug and a problem with your personal setup. You might be able to get help for this at https://github.com/Homebrew/discussions.

**Comment by paulmillr** [comment]
I did not include config and doctor because they are irrelevant. I have tried this on several different systems -- from scratch -- and every time it took 30 mins. Maybe you don't have this issue in London, but there are lots of other countries which have 250kbps peering to GitHub. This is THE issue. It's not "clt" version. If GH cloning takes 250kbps, using any big 

Again, pointing me to discussions is irrelevant. There are other developers in other countries who are using brew.

**Comment by carlocab** [comment]
You might not like the "bureaucratic shit", but it's part of what helps keep Homebrew running efficiently for 99% of our users. It may very well be a pointless (but small) waste of time on your end, but it's a huge time saver on ours. If you want us to value your time, then you should value ours too and respect the issue template.

The issue you are posting about, in its current form, is almost entirely non-actionable for Homebrew. This makes it a poor fit for our issue tracker but a good fit for the discussions page. Indeed, there are already posts there discussing similar issues. This is why I have pointed you twice (and now, including this post, thrice) to the discussions page.
