### ISSUE TITLE
Error: Cannot install in Homebrew under Rosetta 2 in ARM default prefix (/opt/homebrew)!

### ISSUE THREAD

**Issue by dcow** [Homebrew/brew#10313]
# Bug report

Opening a [new bug](https://github.com/Homebrew/discussions/discussions/412#discussioncomment-277855) as [suggested over in discussions](https://github.com/Homebrew/discussions/discussions/412#discussioncomment-278486). When running brew from a translated process such as the `kitty` terminal emulator (which does not support M1 yet), brew raises an error indicating it can't be installed in the arm default prefix. However, `kitty` can execute `arm64` programs naturally. It's not a requirement that a rosetta process only launch other rosetta processes. More commentary below.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?

    Brew doctor output:
    ```
    Warning: Your Homebrew's prefix is not /usr/local.
    Some of Homebrew's bottles (binary packages) can only be used with the default
    prefix (/usr/local).
    You will encounter build failures with some formulae.
    Please create pull requests instead of asking for help on Homebrew's GitHub,
    Twitter or any other official channels. You are responsible for resolving
    any issues you experience while you are running this
    unsupported configuration.
    ```

- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install `tree` via
```
% brew install tree
```

## What happened (include command output)

brew raised an error:
```
Error: Cannot install in Homebrew under Rosetta 2 in ARM default prefix (/opt/homebrew)!
```

## What you expected to happen

brew installs `arm64` version of tree.

## Step-by-step reproduction instructions (by running `brew` commands)

```
% brew install kitty
% kitty
% brew install tree
```

## Commentary

When brew is run in a translated environment it tries to determine whether it is running on intel or arm64 and then enforce its prefix. This restriction is overbearing considering that an e.g. x86 terminal emulator, and the resulting invoked ruby, may, despite being translated, also coexist with arm64 on the same system. For example,
```
% arch -arm64 brew install tree #(or simply brew install from a native terminal emulator)
% tree
  ... (success)
% file tree
/opt/homebrew/bin/tree: Mach-O 64-bit executable arm64
% arch
i386
```
works just fine. After a little experimenting, it seems rosetta2 will prefer to match architecture but, if it can't, simply pick another viable architecture. Considering all this together, it feels like a bug that brew won't install packages compiled for the native host architecture when invoked from a process that is being translated by rosetta2.

I obviously don't have all the history. But want to open this for discussion because the issue presents in a moderately confusing way and seems like a bug since rosetta2 makes running Applications for either architecture side-by-side so seamless. I didn't realize what was happening (I didn't even know kitty was running via rosetta2 since I installed it via brew "normally" using an arm64 terminal emulator) until doing some digging on the issue tracker. So, if nothing else, a slightly more informative error message might be in order. Something along the lines of:
```
if i386 and rosetta2:
  raise Err: "homebrew is being translated via rosetta2 but installed in the native arm64 location. This likely means your terminal emulator is being translated. Using brew in this fashion is not supported. Please use `arch -amd64 brew install ..." to run `brew` natively.
```

## Output of `brew config` and `brew doctor` commands

<pre>
% brew config
HOMEBREW_VERSION: 2.7.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7d7b703696d6d01eda4d4716257ccb0dbe3ab5a
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9d3f868b1623e1afa10409daddc20dce9ad6a81e
Core tap last commit: 9 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit westmere
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
Rosetta 2: true
</pre>

**Comment by MikeMcQuaid** [comment]
> ```
> if i386 and rosetta2:
>   raise Err: "homebrew is being translated via rosetta2 but installed in the native arm64 location. This likely means your terminal emulator is being translated. Using brew in this fashion is not supported. Please use `arch -amd64 brew install ..." to run `brew` natively.
> ```

We'd review a PR to improve the messaging in https://github.com/Homebrew/brew/blob/028e733e79c37724bc2d36238fd18e3763ccef9d/Library/Homebrew/install.rb#L32-L51

Maintainers are unlikely to work on this given there's a workaround.
