### ISSUE TITLE
"bash: brew: command not found" can't use brew

### ISSUE THREAD

**Issue by NotCarti** [Homebrew/brew#10314]
# Bug report

- [ ] ran `brew update` and can still reproduce the problem? I can't run it.
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? I can't run it.
- [ ] ran `brew config` and `brew doctor` and included their output with your issue? I can't run it

## What you were trying to do (and why)

I've installed brew following this: https://docs.brew.sh/Homebrew-on-Linux#alternative-installation and after that I've done this https://docs.brew.sh/Homebrew-on-Linux#install (I'm on void linux so I've to do ~/.bash_profile). 

## What happened (include command output)

tommaso@aspire-one $ brew install hyper
bash: brew: command not found

## What you expected to happen

Starting installing hyper terminal emulator.

## Step-by-step reproduction instructions (by running `brew` commands)

brew install hyper

## Output of `brew config` and `brew doctor` commands

bash: brew: command not found
bash: brew: command not found

**Comment by MikeMcQuaid** [comment]
`eval $(~/.linuxbrew/bin/brew shellenv)` is not being/has not been run in your shell configuration.

**Comment by NotCarti** [comment]
But when I reboot it doesn't work again and I need to write again this command, there's a way to automate it?

**Comment by NotCarti** [comment]
> `eval $(~/.linuxbrew/bin/brew shellenv)` is not being/has not been run in your shell configuration.

But when I reboot it doesn't work again and I need to write again this command, there's a way to automate it?
