### ISSUE TITLE
suggestion: brew --cache --HEAD 

### ISSUE THREAD

**Issue by real-or-random** [Homebrew/brew#10326]
# Feature suggestion

# A detailed description of the proposed feature

If I'm not mistaken, there's no way to query brew for CVS directories for --HEAD builds.

I can currently use `$(brew --cache)/valgrind--git` but there's no `brew --cache --HEAD` (or should it be called `brew --cache -s --HEAD`?) to obtain the path.

(If I am mistaken and there is a way to do this, I'm really sorry for posting this here, and please close this.)

# The motivation for the feature
This is helpful in scripts and to maintain forward-compatibility, e.g., when the path is changed in future brew versions.

# How the feature would be relevant to at least 90% of Homebrew users
To be honest, I don't think it is. But I believe `brew --cache` itself is not relevant to 90% of users. I think the path to the directory  should be obtainable via a command even though most user won't need it. It's simply inconsistent that paths to tarballs are obtainable but --HEAD paths are not.     

# What alternatives to the feature have been considered
 * Document the naming scheme such that things like `$(brew --cache)/valgrind--git` will be stable. But that doesn't sound clever to me.

**Comment by MikeMcQuaid** [comment]
> This is helpful in scripts and to maintain forward-compatibility, e.g., when the path is changed in future brew versions.

Can you explain what exactly you're wanting to do in scripts?

**Comment by real-or-random** [comment]
In my specific case, I'd use this to obtain the exact git commit ID that has been fetched by brew. (I don't think there is a more direct way of doing this?) This helps me decide in CI whether results of brew can be cached or not: https://github.com/bitcoin-core/secp256k1/blob/ac702dabe0cd111ff2a669b30a30b09ad0ec174f/.cirrus.yml#L164

If you now say that's obscure, I cannot argue against this but I'm sure other people may have other use cases.

**Comment by carlocab** [comment]
I think you can parse this from `INSTALL_RECEIPT.json`. For example:

    jq '.HEAD' <$(brew --prefix neovim)/INSTALL_RECEIPT.json

**Comment by real-or-random** [comment]
> ```
> jq '.HEAD' <$(brew --prefix neovim)/INSTALL_RECEIPT.json
> ```

Thanks! I guess the jury is still out on whether this is more direct or not. ;)

**Comment by carlocab** [comment]
I think it's as direct as it gets -- my guess is a `brew --cache --HEAD` command is going to end up parsing `INSTALL_RECEIPT.json` anyway, at the added cost of spinning up a ruby VM

**Comment by real-or-random** [comment]
> I think it's as direct as it gets -- my guess is a `brew --cache --HEAD` command is going to end up parsing `INSTALL_RECEIPT.json` anyway, at the added cost of spinning up a ruby VM

Ok I see. I just noticed that this (I assume) won't work after only `brew fetch --HEAD`, so it does not fit my needs. (Just saying... I can still use `$(brew --cache)/...`)

**Comment by MikeMcQuaid** [comment]
> In my specific case, I'd use this to obtain the exact git commit ID that has been fetched by brew. (I don't think there is a more direct way of doing this?) This helps me decide in CI whether results of brew can be cached or not: https://github.com/bitcoin-core/secp256k1/blob/ac702dabe0cd111ff2a669b30a30b09ad0ec174f/.cirrus.yml#L164

Can you explain why you're doing this? What are you hoping to e.g. cache?

**Comment by real-or-random** [comment]
This caches the contents of  `/usr/local/Cellar/valgrind` to avoid rebuilding them every time, which wastes time. I want to flush the cache if the HEAD revision has changed. 

I admit that the cleanest way to do this would be to build my own bottles but that seems overly complex for this use case. Since there's no way to make `brew install` use local bottle file, I necessarily will need to setup bintray or similar and fetch the bottles over network (or have a local webserver), etc. Open to other suggestions of course.

**Comment by carlocab** [comment]
So I'm still not really sure what you're trying to do exactly, but `brew outdated --fetch-HEAD $formula` will tell you whenever `$formula` installed using `brew install --HEAD $formula` is outdated. For example:
```
if brew --fetch-HEAD $formula > /dev/null; then
  echo "$formula is up to date."
else
  echo "$formula can be rebuilt with `brew reinstall $formula`"
fi
```

**Comment by MikeMcQuaid** [comment]
> Since there's no way to make `brew install` use local bottle file

Yeh, there is. `brew install ./file.bottle.tar.gz` works like how you'd expect.

**Comment by MikeMcQuaid** [comment]
> This caches the contents of `/usr/local/Cellar/valgrind` to avoid rebuilding them every time, which wastes time. I want to flush the cache if the HEAD revision has changed.

For this directly though: I think just relying on the existing naming format is fine for now. We'll reconsider this request in future if we see more people requesting this. Feel free to keep chatting in this issue, though!

**Comment by real-or-random** [comment]
Thanks for all the hints!

> > Since there's no way to make `brew install` use local bottle file
> 
> Yeh, there is. `brew install ./file.bottle.tar.gz` works like how you'd expect.

Ah thanks! I really missed this in the man page...

> > This caches the contents of `/usr/local/Cellar/valgrind` to avoid rebuilding them every time, which wastes time. I want to flush the cache if the HEAD revision has changed.
> 
> For this directly though: I think just relying on the existing naming format is fine for now. We'll reconsider this request in future if we see more people requesting this. Feel free to keep chatting in this issue, though!

Fair enough, thanks for all the responses.
