### ISSUE TITLE
feature brew cask list -m

### ISSUE THREAD

**Issue by guycalledseven** [Homebrew/brew#1033]
In recent brew folder location changes, I've learned to like list -m option because it produces ready to use output for eg. backup/restore:
```
brew list -m
c-ares, cmake, d-bus, dbus, docker, docker-compose, docker-machine, docker-machine-parallels...
```

However the same does not work for **cask**:
```
brew cask list -m
Error: No available Cask for -m
Error: nothing to list
```
BTW I really couldn't find any reference to -m for brew list in the docs, I accidentally stumbled upon it.
edit: typos

**Comment by zmwangx** [comment]
Although quite obscure, it is in the docs:

```
$ brew list -h
brew list, ls [--full-name]:
    List all installed formulae. If --full-name is passed, print formulae
    with fully-qualified names. If --full-name is not passed, any other
    options (e.g. -t) are passed to ls which produces the actual output.

brew list, ls --unbrewed:
    List all files in the Homebrew prefix not installed by Homebrew.

brew list, ls [--versions [--multiple]] [--pinned] [formulae]:
    List the installed files for formulae. Combined with --verbose, recursively
    list the contents of all subdirectories in each formula's keg.

    If --versions is passed, show the version number for installed formulae,
    or only the specified formulae if formulae are given. With --multiple,
    only show formulae with multiple versions installed.

    If --pinned is passed, show the versions of pinned formulae, or only the
    specified (pinned) formulae if formulae are given.
    See also pin, unpin.
```

Note *any other options (e.g. `-t`) are passed to `ls` which produces the actual output.* `-m` is just an `ls` option.

I'm not familiar with cask code but I guess they do not support `ls` options.

By the way, I've lost track since cask's import to core, but IMO cask-specific feature requests should still go to https://github.com/caskroom/homebrew-cask/issues :)

**Comment by reitermarkus** [comment]
Cask doesn't have a `-m` option, but it also has a `-1` option like `brew`, which outputs one cask per line, which should work for backup/restore.

**Comment by MikeMcQuaid** [comment]
It's definitely worth using `brew bundle` for backup/restore and not `brew list`.

**Comment by guycalledseven** [comment]
tnx @reitermarkus  did not know about -1 
although preferably I would like  -m output. :)
