### ISSUE TITLE
Linuxbrew bottles should exclude pre-Core 2 x86_64 machines, e.g. AMD K10

### ISSUE THREAD

**Issue by Artoria2e5** [Homebrew/brew#10347]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Get `wcalc` to run.

## What happened (include command output)

Ilegal instruction with the wcalc invocation ```wcalc <<< 1+1```

```
artoria@HASEE-FJ0VL6L:~$ qemu-x86_64 -cpu phenom ~/.linuxbrew/bin/wcalc <<< 1+1
warning: TCG doesn't support requested feature: CPUID.80000001H:EDX.fxsr-opt [bit 25]
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Illegal instruction (core dumped)
```

## What you expected to happen

It should tell me it is two.

## Why this happened

This issue is caused by brew downloading a bottled version of GCC. The bottles require core 2, which [despite what you mac people think](https://github.com/Homebrew/linuxbrew-core/issues/16215), is not the most ancient of x86-64 CPUs. Ever heard about the SSSE3 vs SSE4a split? That was still a thing when core 2 came out.

You guys need to :
* rephrase the system requirements to say 64-bit x86_64 CPU **with SSSE3** (and maybe SSE4.1)
* add a hardware check for bottle installation. I am sorry, but you should've known that this relying on system version for CPU check thing ain't gonna last.

### Run brew in an emulated CPU
We need QEMU to emulate an old system, K10 (phenom) in our case. In this case, /bin/bash happens to be a x86_64 system's /bin/bash.

1. Run `qemu-x86_64 -cpu phenom /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`.
2. Very patiently wait for the full 350M clone to complete "resolving delta". Seriously, people, if you want to go unshallow you should at least compact the history once per year or something to restrict stuff to a single branch.

If you are not using Linux, you might need to do a system emulation. Remember, get an OS with Ruby 2.6 and glibc, since that's what the vendor script asks for. I went for a system emulation first try on Alpine, and that sucked. Anyways:
* Musl *should* work, but your vendor script blocks it.
* Ruby 2.7 *might* work, but rocket surgery ends at `cannot load such file -- active_support/core_ext/object/blank (LoadError)`. 

### Trigger the bug
1. `export PATH=$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH`
2. `qemu-x86_64 -cpu phenom /usr/bin/env brew install w-calc` (Yes, this is how we invoke `brew` now)
    * For some reason this seems to escape the emulation, handing off to the host to do the actual running, making this no different from "brew". Must be because the `exec` syscall [being handled as a pass-thru](https://bugs.launchpad.net/qemu/+bug/1912107).
3. `qemu-x86_64 -cpu phenom ~/.linuxbrew/bin/wcalc <<< 1+1`
    * Because of the issue with `env` above, just calling through `env` would make it fall to the non-antique host CPU. A direct path is required.

(The original version of the bug triggers when `gcc` sees a floating-point number in the source code and feeds it to GMP. However, it actually happens in one of gcc's child processess, so it escapes QEMU's emulation by exec.)

## Output of `brew config` and `brew doctor` commands

(Yes, it says skylake because `env` spawn escapes `qemu`. I can maybe waste some time adding shell script wrappers for Ruby to put it under qemu, but we all know there's no check except here.)
```
artoria@HASEE-FJ0VL6L:~$ qemu-x86_64 -cpu phenom /usr/bin/env brew config
warning: TCG doesn't support requested feature: CPUID.80000001H:EDX.fxsr-opt [bit 25]
HOMEBREW_VERSION: 2.7.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: bca4804a9e48de5319383d3eddadaa7f054c77da
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 6bdf0daedf7537d696cb3e59bb67af2bd3168a01
Core tap last commit: 20 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/artoria/.linuxbrew
HOMEBREW_REPOSITORY: /home/artoria/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/artoria/.linuxbrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
all_proxy: http://127.0.0.1:7890
Homebrew Ruby: 2.6.3 => /home/artoria/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit skylake
Clang: 7.0 build 701
Git: 2.20.1 => /usr/bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 4.4.0-19041-Microsoft x86_64 GNU/Linux
OS: Debian GNU/Linux 10 (buster) (buster)
Host glibc: 2.28
/usr/bin/gcc: 8.3.0
/usr/bin/ruby: 2.5.5
glibc: N/A
gcc: 5.5.0_7
xorg: N/A
```

```
artoria@HASEE-FJ0VL6L:~$ qemu-x86_64 -cpu phenom /usr/bin/env brew doctor
warning: TCG doesn't support requested feature: CPUID.80000001H:EDX.fxsr-opt [bit 25]
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gcc@5

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

**Comment by Artoria2e5** [comment]
Anyways, @cuihaoleo encountered this issue on a real K10 machine when running GCC. Hand any questions to him, although I will help when I can repro it using a shallow qemu user emulation.

Just don't ask me to do system emulation.

**Comment by iMichka** [comment]
1) I really do not like the tone used in this bug report, sorry. And the first thing which comes to  my mind when reading your issue is to ask you to follow our code of conduct: https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md#code-of-conduct.
Please be a little bit nicer, especially when asking for help.

2) The last warning you have in the issue report tells you exactly what to expect:
```
Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

**Comment by Artoria2e5** [comment]
@iMichka The warning has nothing to do with the reproducibility of the bug. I skipped creating the user because it only complicate accessing it from a non-priv account.

And yes I will PR this.

**Comment by MikeMcQuaid** [comment]
> 1. I really do not like the tone used in this bug report, sorry
 
@iMichka I strongly agree.

> The warning has nothing to do with the reproducibility of the bug.

@Artoria2e5 It does tell you not to report it, though, which you ignored and then proceed to write a rude and patronising bug report. 

Adjust your tone in future or you will be blocked.

**Comment by Artoria2e5** [comment]
Look, I told you people how, why, and provided a solution. If you want to keep confusing users over the tone of a bug report, it's your choice.

You people have received numerous bug reports of the same issue over the years, and have never update the documentation once. Don't believe it? Go to the linuxbrew-core repo and search for illegal instruction. Maybe go to the legacy linuxbrew repo too.

And why didn't you change that? Maybe it's because you are spending too much time on clearly irrelevant things like where the homebrew directory is. How does that change the bottle being downloaded? This is programming, not alchemy.

The only patronizing part of my report was when I called you Mac people and did an "ever hear about". If that offends you people, let me remind you that you have been treating every user as lesser beings by giving them vague explanations that are unhelpfdamn becausand never even mind the nanny checks that cannot be skipped. It's not my machine's problem to start with, and honestly I don't give a damn because I don't use computer lab hardware where I don't have root access.

PS: @jonchang good job on some of the issue replies. just one nitpick -- core2 in clang is ssse3, not sse4.1.
