### ISSUE TITLE
invalid option: --with-webp

### ISSUE THREAD

**Issue by 2012shenghua** [Homebrew/brew#10371]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [✔️ ] ran `brew update` and can still reproduce the problem?
- [✔️ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [✔️ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Output of `brew config` and `brew doctor` commands

<pre>

</pre>

**Comment by 2012shenghua** [comment]
i need run command: `brew install vips --with-webp --with-graphicsmagick.`
after,  I meet the problem.
![image](https://user-images.githubusercontent.com/15325522/105140384-928ae280-5b32-11eb-87fe-3725bfe3102e.png)

**Comment by 2012shenghua** [comment]
![image](https://user-images.githubusercontent.com/15325522/105140416-a20a2b80-5b32-11eb-8cff-a9983cc58877.png)

**Comment by gromgit** [comment]
You have two problems:
1. The `homebrew/science` tap no longer exists.
2. The `vips` formula seems to have been moved to the core tap, which doesn't allow `--with` options.

If you need such options, you'll have to `brew extract` the appropriate version of the formula to your own tap, then modify it from there.

**Comment by 2012shenghua** [comment]
thanks! so should i change my command `brew i vips` to solve my problem?

**Comment by gromgit** [comment]
`brew info vips` indicates that `webp` and `imagemagick` are already dependencies, so presumably they were enabled by default when they were migrated from `homebrew/science`.

So yeah, `brew install vips` and see if it works for you. If it doesn't, you'll have to `brew extract` the formula into your own tap and modify it yourself.
