### ISSUE TITLE
"brew doctor" advice to upgrade Command Line Tools fails

### ISSUE THREAD

**Issue by reidpr** [Homebrew/brew#10399]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade the Command Line Tools, because `brew doctor` has been pestering me to.

## What happened (include command output)

The instructions given failed and now I have no Command Line Tools.

<details>
  <summary>Command output</summary>
  <pre>
$ softwareupdate --all --install --force
Software Update Tool

Finding available software
No updates are available.
$ sudo xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
$ sudo rm -rf /Library/Developer/CommandLineTools
$ sudo xcode-select --install
xcode-select: error: no developer tools were found, and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
</pre>
</details>

## What you expected to happen

Command Line Tools would be upgraded, or if something went wrong, left in the same state they were. Or, additional commands in the instructions to make sure `xcode-select` would work after I deleted `/Library/Developer/CommandLineTools`.

## Step-by-step reproduction instructions (by running `brew` commands)

See above under "What happened".

## Output of `brew config` and `brew doctor` commands

Prior to above:

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  sshfs
</pre>

After above:

<pre>
$ brew uninstall sshfs
Uninstalling /usr/local/Cellar/sshfs/2.10_2... (6 files, 101.8KB)
$ brew update
Already up-to-date.
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unknown support status

Warning: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install

Warning: Your Xcode does not support macOS 10.15.
It is either outdated or was modified.
Please update your Xcode or delete it if no updates are available.
Xcode can be updated from the App Store.

Warning: Xcode alone is not sufficient on Catalina.
Install the Command Line Tools:
  xcode-select --install

$ brew config
HOMEBREW_VERSION: 2.7.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: bca4804a9e48de5319383d3eddadaa7f054c77da
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 37a8583a7fafede53c280b65878ee8ed9af6b60f
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--fontdir=/Library/Fonts"]
HOMEBREW_EDITOR: emacs -nw
HOMEBREW_MAKE_JOBS: 8
all_proxy: http://[redacted]
http_proxy: http://[redacted]
https_proxy: http://[redacted]
no_proxy: localhost,127.0.0.1,[redacted]
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: N/A
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_271, 1.8.0_261
macOS: 10.15.7-x86_64
CLT: N/A
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
</pre>

**Comment by jonchang** [comment]
> xcode-select: error: no developer tools were found, and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.

To install the Command Line Tools, you need either a console login with the GUI, or the .pkg already downloaded from the Apple developer website.

**Comment by reidpr** [comment]
> a console login with the GUI

I *was* logged in on the GUI. It was an iTerm2 window. I don't know what a "console login" is or if that's different somehow.

The bug is, please do not give people instructions that will break their install. I'm guessing that whatever a "console login on the GUI" is, it's not to hard to detect that situation, and in that case you could print a warning. Even if logged in over SSH (as you apparently and incorrectly assume), `xcode-select` is an obscure command, and few folks will know it requires the GUI. By following your instructions, even if you can make sense of the error (SSH *is* a UI), you've already trashed your Command Line Tools by the time you get the error.

I went to the trouble of writing a high quality, clear bug report for you. This is a real UX bug. You could give folks the courtesy of assuming good faith and intelligence, rather than closing their bug reports with one condescending sentence based on false assumptions.

For anyone else in this situation, I was able to work around it by installing the `.pkg` manually from the URL given. This does require an Apple login. `xcode-select` was completely hosed until I did this, even after installing Xcode.

**Comment by carlocab** [comment]
>This is a real UX bug

This may well be the case, but there's nothing actionable for Homebrew here. If the first two methods using `softwareupdate` or `xcode-select` don't work, then you really have to go to https://developer.apple.com/download/more/ to download the Command Line Tools. This is already suggested by `brew doctor`, and by `xcode-select` when it fails.

Note that `sudo rm -rf /Library/Developer/CommandLineTools` is also the uninstall process [documented by Apple](https://developer.apple.com/library/archive/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-HOW_CAN_I_UNINSTALL_THE_COMMAND_LINE_TOOLS_).

If you're unhappy about this state of affairs, then you need to report this to Apple. Homebrew can't do anything about how `xcode-select` functions, as this is Apple-provided software.

**Comment by laggardkernel** [comment]
I can't install the newest, 12.3, command line tool since I'm still on 10.14. Seems the advice to upgrade command line tool doesn't take the compatibility into consideration.

**Comment by carlocab** [comment]
It does. It won't show you the message if you have the latest compatible Command Line Tools installed. Admittedly, it should probably tell you which version that is.

If you're on the latest minor version of Mojave, then you should be able to install the Command Line Tools for Xcode 11.3.1.

**Comment by laggardkernel** [comment]
Thanks. Installing  Xcode command line tool 11.3.1 resolves the warning. @carlocab 

```
❯ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep version
version: 11.3.1.0.1.1576735732

```

**Comment by MikeMcQuaid** [comment]
> I went to the trouble of writing a high quality, clear bug report for you. This is a real UX bug. You could give folks the courtesy of assuming good faith and intelligence, rather than closing their bug reports with one condescending sentence based on false assumptions.

@reidpr Please read our [Code of Conduct](https://github.com/Homebrew/.github/blob/master/CODE_OF_CONDUCT.md) and adjust your future tone accordingly. 

> If you're unhappy about this state of affairs, then you need to report this to Apple. Homebrew can't do anything about how `xcode-select` functions or how to manage CLT installations, as this is Apple-provided software.

This.
