### ISSUE TITLE
Cannot install the formula in local tap

### ISSUE THREAD

**Issue by athenason** [Homebrew/brew#10392]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I want install an old version of bazel, and I create a local repo with the following command

`1. create a new tap`
`brew tap-new $USER/local-<packageName>`
`2. extract into local tap`
`brew extract --version=1.2.3 <packageName> $USER/local-<packageName>`
`3. run brew install@version as usual`
`brew install <packageName>@1.2.3`

## What happened (include command output)

Then when I install it, homebrew cannot found it. 
But in previous step, homebrew found the formula, I am confused.

<details>
  <summary>Command output</summary>
  <pre>

 brew install bazel@1.2.1 
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 11 formulae.
==> Updated Casks
Updated 1 cask.

==> Searching for similarly named formulae...
This similarly named formula was found:
athenason/repo/bazel@1.2.1
To install it, run:
  brew install athenason/repo/bazel@1.2.1
Error: No available formula or cask with the name "bazel@1.2.1".
==> Searching taps on GitHub...
Error: No formulae found in taps.
frostzhang@MacBook-Pro-4 ~ % brew install athenason/repo/bazel@1.2.1
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "athenason/repo/bazel@1.2.1".

  </pre>
</details>

## What you expected to happen
make the following working
brew install bazel@1.2.1  or
brew install athenason/repo/bazel@1.2.1

## Step-by-step reproduction instructions (by running `brew` commands)

1 brew tap-new athenason/homebrew-repo
2 brew extract --version 1.2.1 bazel athenason/homebrew-repo
3 brew install bazel@1.2.1 or brew install athenason/repo/bazel@1.2.1

## Output of `brew config` and `brew doctor` commands

<pre>
brew config
HOMEBREW_VERSION: 2.7.5-116-gacede73
ORIGIN: https://github.com/Homebrew/brew
HEAD: acede7315ab0f5f7b2fd9d8d6bfedd85f6ad2342
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab61019e86e72aced43da0e56da457099e580992
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.aRitvQFqwI/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.251.08, 1.8.0_121
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/local/bin/pkg-config
  /opt/local/bin/krb5-config
  /opt/local/bin/freetype-config
  /opt/local/bin/libpng16-config
  /opt/local/bin/python2.7-config
  /opt/local/bin/libpng-config
  /opt/local/bin/xml2-config
  /opt/local/bin/curl-config
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/apr-1-config
  /opt/local/bin/pcre2-config
  /opt/local/bin/uuid-config
  /opt/local/bin/apu-1-config
  /opt/local/bin/pcre-config
  /opt/local/bin/ncurses6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libGIF.dylib
  /usr/local/lib/libJPEG.dylib
  /usr/local/lib/libPng.dylib
  /usr/local/lib/libTIFF.dylib
  /usr/local/lib/libcairo.2.dylib
  /usr/local/lib/libgeos-3.3.3.dylib
  /usr/local/lib/libgeos_c.1.dylib
  /usr/local/lib/libpng16.16..dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/geos.h
  /usr/local/include/geos_c.h
  /usr/local/include/groupsock/NetCommon.h
  /usr/local/include/libavcodec/ac3_parser.h
  /usr/local/include/libavcodec/adts_parser.h
  /usr/local/include/libavcodec/avcodec.h
  /usr/local/include/libavcodec/avdct.h
  /usr/local/include/libavcodec/avfft.h
  /usr/local/include/libavcodec/bsf.h
  /usr/local/include/libavcodec/codec.h
  /usr/local/include/libavcodec/codec_desc.h
  /usr/local/include/libavcodec/codec_id.h
  /usr/local/include/libavcodec/codec_par.h
  /usr/local/include/libavcodec/d3d11va.h
  /usr/local/include/libavcodec/dirac.h
  /usr/local/include/libavcodec/dv_profile.h
  /usr/local/include/libavcodec/dxva2.h
  /usr/local/include/libavcodec/jni.h
  /usr/local/include/libavcodec/mediacodec.h
  /usr/local/include/libavcodec/packet.h
  /usr/local/include/libavcodec/qsv.h
  /usr/local/include/libavcodec/vaapi.h
  /usr/local/include/libavcodec/vdpau.h
  /usr/local/include/libavcodec/version.h
  /usr/local/include/libavcodec/videotoolbox.h
  /usr/local/include/libavcodec/vorbis_parser.h
  /usr/local/include/libavcodec/xvmc.h
  /usr/local/include/libavdevice/avdevice.h
  /usr/local/include/libavdevice/version.h
  /usr/local/include/libavfilter/avfilter.h
  /usr/local/include/libavfilter/buffersink.h
  /usr/local/include/libavfilter/buffersrc.h
  /usr/local/include/libavfilter/version.h
  /usr/local/include/libavformat/avformat.h
  /usr/local/include/libavformat/avio.h
  /usr/local/include/libavformat/version.h
  /usr/local/include/libavutil/adler32.h
  /usr/local/include/libavutil/aes.h
  /usr/local/include/libavutil/aes_ctr.h
  /usr/local/include/libavutil/attributes.h
  /usr/local/include/libavutil/audio_fifo.h
  /usr/local/include/libavutil/avassert.h
  /usr/local/include/libavutil/avconfig.h
  /usr/local/include/libavutil/avstring.h
  /usr/local/include/libavutil/avutil.h
  /usr/local/include/libavutil/base64.h
  /usr/local/include/libavutil/blowfish.h
  /usr/local/include/libavutil/bprint.h
  /usr/local/include/libavutil/bswap.h
  /usr/local/include/libavutil/buffer.h
  /usr/local/include/libavutil/camellia.h
  /usr/local/include/libavutil/cast5.h
  /usr/local/include/libavutil/channel_layout.h
  /usr/local/include/libavutil/common.h
  /usr/local/include/libavutil/cpu.h
  /usr/local/include/libavutil/crc.h
  /usr/local/include/libavutil/des.h
  /usr/local/include/libavutil/dict.h
  /usr/local/include/libavutil/display.h
  /usr/local/include/libavutil/dovi_meta.h
  /usr/local/include/libavutil/downmix_info.h
  /usr/local/include/libavutil/encryption_info.h
  /usr/local/include/libavutil/error.h
  /usr/local/include/libavutil/eval.h
  /usr/local/include/libavutil/ffversion.h
  /usr/local/include/libavutil/fifo.h
  /usr/local/include/libavutil/file.h
  /usr/local/include/libavutil/frame.h
  /usr/local/include/libavutil/hash.h
  /usr/local/include/libavutil/hdr_dynamic_metadata.h
  /usr/local/include/libavutil/hmac.h
  /usr/local/include/libavutil/hwcontext.h
  /usr/local/include/libavutil/hwcontext_cuda.h
  /usr/local/include/libavutil/hwcontext_d3d11va.h
  /usr/local/include/libavutil/hwcontext_drm.h
  /usr/local/include/libavutil/hwcontext_dxva2.h
  /usr/local/include/libavutil/hwcontext_mediacodec.h
  /usr/local/include/libavutil/hwcontext_opencl.h
  /usr/local/include/libavutil/hwcontext_qsv.h
  /usr/local/include/libavutil/hwcontext_vaapi.h
  /usr/local/include/libavutil/hwcontext_vdpau.h
  /usr/local/include/libavutil/hwcontext_videotoolbox.h
  /usr/local/include/libavutil/hwcontext_vulkan.h
  /usr/local/include/libavutil/imgutils.h
  /usr/local/include/libavutil/intfloat.h
  /usr/local/include/libavutil/intreadwrite.h
  /usr/local/include/libavutil/lfg.h
  /usr/local/include/libavutil/log.h
  /usr/local/include/libavutil/lzo.h
  /usr/local/include/libavutil/macros.h
  /usr/local/include/libavutil/mastering_display_metadata.h
  /usr/local/include/libavutil/mathematics.h
  /usr/local/include/libavutil/md5.h
  /usr/local/include/libavutil/mem.h
  /usr/local/include/libavutil/motion_vector.h
  /usr/local/include/libavutil/murmur3.h
  /usr/local/include/libavutil/opt.h
  /usr/local/include/libavutil/parseutils.h
  /usr/local/include/libavutil/pixdesc.h
  /usr/local/include/libavutil/pixelutils.h
  /usr/local/include/libavutil/pixfmt.h
  /usr/local/include/libavutil/random_seed.h
  /usr/local/include/libavutil/rational.h
  /usr/local/include/libavutil/rc4.h
  /usr/local/include/libavutil/replaygain.h
  /usr/local/include/libavutil/ripemd.h
  /usr/local/include/libavutil/samplefmt.h
  /usr/local/include/libavutil/sha.h
  /usr/local/include/libavutil/sha512.h
  /usr/local/include/libavutil/spherical.h
  /usr/local/include/libavutil/stereo3d.h
  /usr/local/include/libavutil/tea.h
  /usr/local/include/libavutil/threadmessage.h
  /usr/local/include/libavutil/time.h
  /usr/local/include/libavutil/timecode.h
  /usr/local/include/libavutil/timestamp.h
  /usr/local/include/libavutil/tree.h
  /usr/local/include/libavutil/twofish.h
  /usr/local/include/libavutil/tx.h
  /usr/local/include/libavutil/version.h
  /usr/local/include/libavutil/video_enc_params.h
  /usr/local/include/libavutil/xtea.h
  /usr/local/include/libpostproc/postprocess.h
  /usr/local/include/libpostproc/version.h
  /usr/local/include/libswresample/swresample.h
  /usr/local/include/libswresample/version.h
  /usr/local/include/libswscale/swscale.h
  /usr/local/include/libswscale/version.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libgeos.la
  /usr/local/lib/libgeos_c.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/libavcodec.pc
  /usr/local/lib/pkgconfig/libavdevice.pc
  /usr/local/lib/pkgconfig/libavfilter.pc
  /usr/local/lib/pkgconfig/libavformat.pc
  /usr/local/lib/pkgconfig/libavutil.pc
  /usr/local/lib/pkgconfig/libpostproc.pc
  /usr/local/lib/pkgconfig/libswresample.pc
  /usr/local/lib/pkgconfig/libswscale.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libBasicUsageEnvironment.a
  /usr/local/lib/libUsageEnvironment.a
  /usr/local/lib/libavcodec.a
  /usr/local/lib/libavdevice.a
  /usr/local/lib/libavfilter.a
  /usr/local/lib/libavformat.a
  /usr/local/lib/libavutil.a
  /usr/local/lib/libcairo.a
  /usr/local/lib/libgeos.a
  /usr/local/lib/libgeos_c.a
  /usr/local/lib/libgroupsock.a
  /usr/local/lib/libliveMedia.a
  /usr/local/lib/libpostproc.a
  /usr/local/lib/libswresample.a
  /usr/local/lib/libswscale.a
</pre>

**Comment by gromgit** [comment]
What does `brew readall` output?

**Comment by SeekingMeaning** [comment]
`bazel@1.2.1.rb` contains `depends_on :java`, which was deprecated in 2.7.0—this is causing the formula not to load

**Comment by athenason** [comment]
> What does `brew readall` output?

brew readall                           
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/athenason/homebrew-repo/Formula/bazel@1.2.1.rb
bazel@1.2.1: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the athenason/repo tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/athenason/homebrew-repo/Formula/bazel@1.2.1.rb:9

**Comment by athenason** [comment]
@SeekingMeaning after change depends to "openjdk@8", it works. thanks
