### ISSUE TITLE
linker error while compiling gmp program

### ISSUE THREAD

**Issue by taqiali110** [Homebrew/brew#10396]
[#]([url](url)) Please fill out one of the templates on: https://github.com/Homebrew/brew/issues/new/choose or we will close it without comment.

I installed gmp library through "brew install gmp". But not able to execute any program.

<img width="573" alt="Screenshot 2021-01-22 at 4 57 42 PM" src="https://user-images.githubusercontent.com/46449947/105485938-aa4d9c80-5cd3-11eb-8ddc-cc2fec466b20.png">

**Comment by taqiali110** [comment]
And also the /usr/local/lib is not a directory, but a file with extended attribute
as visible in above image

**Comment by jonchang** [comment]
> Please fill out one of the templates on: https://github.com/Homebrew/brew/issues/new/choose or we will close it without comment.
