### ISSUE TITLE
Cannot install on fresh MacOS 11.1

### ISSUE THREAD

**Issue by mt-inside** [Homebrew/brew#10418]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] ran `brew update` and can still reproduce the problem? - N/A
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem? - N/A
- [ x ] ran `brew config` and `brew doctor` and included their output with your issue? - N/A

## What happened (include command output)

Tried to install onto a fresh 11.1 Intel

```
matt@matts-MBP Homebrew % uname -a
Darwin matts-MBP.inside 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

Process fails part way through.
It can't run brew to continue.
`/usr/local/bin/brew` symlink is present, but it's broken; pointing to a non-existant bin directory in `/usr/local/Homebrew`
It's like the git checkout wasn't complete?
Git checkout looks correctly setup?

<details>
  <summary>Command output</summary>
  <pre>

  matt@matts-MBP ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /usr/sbin/chown matt:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at 95c6e92d9b4 Merge pull request #10278 from zkokaja/add-cask-json-values
/bin/bash: line 138: /usr/local/bin/brew: No such file or directory
Failed during: /usr/local/bin/brew update --force --quiet

matt@matts-MBP ~ % ls -l /usr/local/bin/brew
lrwxr-xr-x  1 matt  admin  28 25 Jan 12:18 /usr/local/bin/brew -> /usr/local/Homebrew/bin/brew
matt@matts-MBP ~ % ls -l /usr/local/Homebrew 
total 0
drwxr-xr-x  3 matt  admin  96 25 Jan 11:54 Library

matt@matts-MBP Homebrew % git remote -v
origin	https://github.com/Homebrew/brew (fetch)
origin	https://github.com/Homebrew/brew (push)
matt@matts-MBP Homebrew % git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

  </pre>
</details>

## What you expected to happen

Installation should work

## Step-by-step reproduction instructions (by running `brew` commands)

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

## Output of `brew config` and `brew doctor` commands

N/A

**Comment by carlocab** [comment]
This doesn't look like a bug with `brew`. There are many related discussions on [Homebrew's discussions page](https://github.com/Homebrew/discussions/discussions). 

For example:
https://github.com/Homebrew/discussions/discussions/590
https://github.com/Homebrew/discussions/discussions/140
https://github.com/Homebrew/discussions/discussions/600
https://github.com/Homebrew/discussions/discussions/595

Please check there first, and see if any of those discussions will help you. If they do not, perhaps you can post in one of them for help.

**Comment by mt-inside** [comment]
Ok good to know; I don't what GitHub's SEO game is but google didn't find any of those.

None of them is my problem, but I'll post there.
