### ISSUE TITLE
does anybody installed pyqt in mac m1

### ISSUE THREAD

**Issue by tomuGo** [Homebrew/brew#10419]
does anybody installed pyqt in mac m1?

**Comment by carlocab** [comment]
The issue tracker is for bug reports, not questions. Questions are best asked at [Homebrew's discussion page](https://github.com/Homebrew/discussions/discussions).

>does anybody installed pyqt in mac m1?

I suggest you try `brew install pyqt`.

**Comment by yamiyukiharu** [comment]
I have successfully ran PySide2 on M1 Mac, i believe it should work for pyqt as well. You need to apply the fix described here:
https://forums.macrumors.com/threads/pyqt5-and-big-sur.2260773/
