### ISSUE TITLE
Repo rearrangement didn't fix my manpage links

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#1045]
The new repo rearrangement did not replace my manpage link (which used to point at `HOMEBREW_REPOSITORY/share/man/man1/brew.1`) with one pointing at the manpage's new location.  It left the old, now broken, symlink in place.

I expected that perhaps a subsequent `brew update` would auto-migrate, but that didn't happen either.

It was an easy manual fix, but since my REPOSITORY/PREFIX separation has become the default I was suprised that a manual fix was necessary.

**Comment by chdiza** [comment]
Same is true of my "doc" symlink, which originally pointed at `HOMEBREW_REPOSITORY/share/doc/homebrew`.

**Comment by chdiza** [comment]
Sorry, forgot to mention that my HB REPO was in `/usr/local/hb`...but still, there shouldn't have been that problem.

**Comment by zmwangx** [comment]
This can be confirmed on a standard install, will issue a fix soonish.

**Comment by MikeMcQuaid** [comment]
Thanks @zmwangx, @chdiza.

**Comment by chdiza** [comment]
FYI the same goes for shell completions.  (I don't use them, so I didn't notice at first.)

**Comment by zmwangx** [comment]
Just to make it clear, I won't have time to work on this until a few hours later, so feel free.

**Comment by MikeMcQuaid** [comment]
> This can be confirmed on a standard install, will issue a fix soonish.

This should be fixed by https://github.com/Homebrew/install/pull/64.

**Comment by MikeMcQuaid** [comment]
@chdiza does `brew update --force` fix it or print any weird messages?

**Comment by zmwangx** [comment]
> This should be fixed by Homebrew/install#64.

By "a standard install" I meant an install with standard paths (I haven't found out about the fresh install problem at the time of that comment), but 👍  on the `install` change.

> does brew update --force fix it or print any weird messages?

At least it fixed it for me. I think you'll be fine as soon as you hit `update-report`.

**Comment by chdiza** [comment]
> does brew update --force fix it or print any weird messages?

I don't know; I already fixed it manually.

**Comment by zmwangx** [comment]
@chdiza You can change them back to broken links and run `brew update --force` again to see if they'll be fixed, if you're okay with the trouble.

**Comment by chdiza** [comment]
OK, yeah, `brew update --force` fixed it.  Thanks.

**Comment by MikeMcQuaid** [comment]
🆒.
