### ISSUE TITLE
Homebrew installation failed because a remote server "hangs up" a SSL Connection over and over again.

### ISSUE THREAD

**Issue by sadeqush** [Homebrew/brew#10464]
[``]([url](url
<img width="682" alt="Screen Shot 2021-01-31 at 2 31 15 PM" src="https://user-images.githubusercontent.com/32276793/106378744-4876ec00-63d1-11eb-9b34-8cb59e29a1fb.png">
))

**Comment by carlocab** [comment]
>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
