### ISSUE TITLE
Docs link on brew.sh homepage is broken

### ISSUE THREAD

**Issue by brion** [Homebrew/brew#1047]
https://git.io/brew-docs Is linked at the bottom of http://brew.sh however this expands to a 404 page: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/README.md#readme

**Comment by zmwangx** [comment]
We'll fix this, thanks for the report. 👍

**Comment by MikeMcQuaid** [comment]
Fixed, thanks again!
