### ISSUE TITLE
Broken links on homepage and in installation output

### ISSUE THREAD

**Issue by saberworks** [Homebrew/brew#1048]
The home page has a link to "alternate installation" methods, but the link is broken:

https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Installation.md#installation which is a 404.

The output of the installation says it will provide more information on spyware/google analytics (including opt-out) but the link is broken:

https://git.io/brew-analytics redirects to https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Analytics.md which is a 404.

**Comment by zmwangx** [comment]
Thanks for the report.

The broken installation instructions link will be fixed by Homebrew/homebrew.github.io#125.

The broken analytics doc link will be fixed too.
