### ISSUE TITLE
Formula isn't changing versions but homebrew tries to upgrade it

### ISSUE THREAD

**Issue by afnanenayet** [Homebrew/brew#10483]
**Contributor Checklist**

- [X] I ran `brew update` and can still reproduce the problem?
- [X] I ran `brew doctor`, fixed all issues and can still reproduce the problem?

**`brew config` output**

HOMEBREW_VERSION: 2.7.7-98-ga31d0f8
ORIGIN: https://github.com/Homebrew/brew
HEAD: a31d0f85d2c6dce8daefde1e1d8f7ef059a1b833
Last commit: 13 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7e883871ef5ce46795d9b7af5b3bd30bab0c5536
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2-x86_64
CLT: N/A
Xcode: 12.4

**`brew doctor` output**

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/afnanenayet/.cargo/bin/cargo-install-update-config

**What were you trying to do (and why)?**

I ran `brew upgrade` (just a routine update), and one of my custom packages, whose version isn't changing, will attempt to update again. It should've update since the package hasn't changed (I believe), and homebrew isn't using a new archive or anything, it's using the exact same cached archive. It also returns an error about an existing `.brew` file in `/usr/local/opt/{package}`.

**What happened (include all command output)?**

```
❯ brew upgrade
==> Upgrading 1 outdated package:
afnanenayet/tap/diffsitter 0.5.0_1 -> 0.5.0_1
==> Upgrading afnanenayet/tap/diffsitter 0.5.0_1 -> 0.5.0_1
==> Downloading https://github.com/afnanenayet/diffsitter/releases/download/v0.5.0_1/diffsitter-darwin-amd64.tar.gz
Already downloaded: /Users/afnanenayet/Library/Caches/Homebrew/downloads/6ee19af6b3246e072685335435a4819a32e0a0abb9cadd5c24b4fad9acb08838--diffsitter-darwin-amd64.tar.gz
Error: File exists @ dir_s_mkdir - /usr/local/opt/diffsitter/.brew
```

You can find the formula here: https://github.com/afnanenayet/homebrew-tap/blob/master/diffsitter.rb

I'm unclear as to whether my formula is the issue, I don't *think* it is since it's simple, just installs a binary from the archive and has no dependencies. I did read that sometimes this issue pops up because of circular dependencies, but that doesn't apply here and I wasn't able to find much relevant information about this error.

**What did you expect to happen?**

I would expect that my package only upgrade via if the version/formula got updated.

**Step-by-step reproduction instructions (by running `brew` commands)**

```sh
brew install afnanenayet/tap/diffsitter
brew upgrade
```

**Comment by MikeMcQuaid** [comment]
````
mikebook # brew audit diffsitter                                              (master) [~/OSS/Homebrew]
afnanenayet/tap/diffsitter:
  * 2: col 9: Description shouldn't start with an article.
  * 3: col 12: Formula should have a homepage.
  * 4: col 3: version 0.5.0_1 should not end with an underline and a number
  * 5: col 3: `url` (line 5) should be put before `version` (line 4)
Error: 4 problems in 1 formula detected
```

Specifically: `version 0.5.0_1 should not end with an underline and a number` is what is breaking here.

**Comment by afnanenayet** [comment]
Aw man sorry about that, I had a feeling it would be a dumb mistake on my end. Thanks for the response!

**Comment by MikeMcQuaid** [comment]
No worries, thanks for the apology! ❤️
