### ISSUE TITLE
upgrade macos sierra but error

### ISSUE THREAD

**Issue by CoderBOBO** [Homebrew/brew#1049]
You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
How to solve this problem？？？？？？？？？？？

**Comment by zmwangx** [comment]
`brew update`. You shouldn't be seeing this warning anymore.

**Comment by zmwangx** [comment]
Also, please follow our [troubleshooting checklist](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting). This issue is not at all actionable because we currently know nothing about what you were trying to do and what error you encountered.
