### ISSUE TITLE
macOS Java JDK pop up appears on executing brew doctor and brew config

### ISSUE THREAD

**Issue by dkav** [Homebrew/brew#10491]
**`brew config` output**

HOMEBREW_VERSION: 2.7.7-120-gd2430bc
ORIGIN: https://github.com/Homebrew/brew
HEAD: d2430bcf50d513807ab62320ff966d569afc40dc
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9700fddec6199c8cd3bb98429ea2a00224b3decf
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 14
HOMEBREW_EDITOR: /usr/local/bin/mvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.32.28
Xcode: N/A

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Run brew doctor.

**What happened (include all command output)?**

A pop up window that says __"To use the "java" command-line tool you need to install a JDK. Click "More-info..." to visit the Java Developer Kit download website."__ 

It appears to me that the following check is the source of the issue:
```
Checking check_cask_software_versions
java -version
```

I do not have Java installed.

**What did you expect to happen?**

No Java JDK pop up.

**Step-by-step reproduction instructions (by running `brew` commands)**

brew doctor

**Comment by jaqque** [comment]
git blame points to https://github.com/Homebrew/brew/commit/447ea12d386832672c165d0fa29400bfcbb6efa8 but I didn't see the issue until a few days ago.

**Comment by dkav** [comment]
Still occurring in the new release (version 3).

**Comment by JBallin** [comment]
Still seeing this on latest when running `brew doctor`. 

Thanks brew! ❤️

**Comment by carlocab** [comment]
@JBallin what does `brew --version` say for you?

**Comment by JBallin** [comment]
@carlocab I'm actually only seeing it on my Mac running Catalina, which shows `Homebrew 3.0.0`.
My other Mac, running Big Sur, does not have the issue and shows `Homebrew 3.0.0-69-g3bcd919`.

Curious why they show different versions?

**Comment by carlocab** [comment]
Your Big Sur machine is running a dev version of `brew`, where this has already been fixed. Presumably you've run a dev command there, and that's why that's the version you're getting.

Your Catalina Mac will be fixed in 3.0.1.
