### ISSUE TITLE
Hide Rubocop parser warnings with warning gem

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#10505]
**Provide a detailed description of the proposed feature**

Use https://github.com/jeremyevans/ruby-warning to hide these warnings from `rubocop` (and whenever we use `parser`):
```
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.6-compliant syntax, but you are running 2.6.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

**What is the motivation for the feature?**

These warnings are annoying and we pin specific Ruby versions for a reason.

**How will the feature be relevant to at least 90% of Homebrew users?**

It will not be.

**What alternatives to the feature have been considered?**

Putting up with them.

**Comment by hyuraku** [comment]
I will open PR to solve this issue this week !!

**Comment by hyuraku** [comment]
@MikeMcQuaid 
it is difficult to hide warnings with additional configuration because these warnings are generated when  `require 'rubocop'` was executed".

**Comment by Rylan12** [comment]
I'm totaling wading into waters I'm not familiar with here so I may be totally off base.

It looks to me like the warnings are triggered (at least for `brew style`) when using a `system` call. So if my understanding is correct, we can't actually ignore those warning within the brew code. We could pass `-W0` to the call, though. Maybe something like this in [`style.rb`](https://github.com/Homebrew/brew/blob/0d1aa33f81b7a5274cb33326cbd8c0bc78cd7623/Library/Homebrew/style.rb#L137-L140) (the difference is adding the `verbose ? nil : "-W0"` line):

```ruby
      ruby_args = [
        verbose ? nil : "-W0",
        "-S",
        "rubocop",
      ].compact.freeze
```

Of course, this ignored all warnings so it's not ideal. I don't know of a way to disable a specific warning although it's totally possible that there is a way.

**Comment by dtrodrigues** [comment]
Some other discussion here - https://github.com/rubocop-hq/rubocop/issues/1819

**Comment by Rylan12** [comment]
It looks like this is the same with `brew tests`.

https://github.com/Homebrew/brew/blob/0d1aa33f81b7a5274cb33326cbd8c0bc78cd7623/Library/Homebrew/dev-cmd/tests.rb#L146-L150

The following looks like it will work:

```ruby
      verbosity = args.verbose? ? {} : { "RUBYOPT" => "-W0" }

      if parallel
        system verbosity, "bundle", "exec", "parallel_rspec", *parallel_args, "--", *bundle_args, "--", *files
      else
        system verbosity, "bundle", "exec", "rspec", *bundle_args, "--", *files
      end
```

**Comment by Rylan12** [comment]
> Some other discussion here - [rubocop-hq/rubocop#1819](https://github.com/rubocop-hq/rubocop/issues/1819)

Thanks, didn't see that.

Two things to note, I think:

https://github.com/rubocop-hq/rubocop/issues/1819#issuecomment-95377009:

> Run Rubocop as, for example, `ruby -W0 -S rubocop args...`.

https://github.com/rubocop-hq/rubocop/issues/1819#issuecomment-769278581

> For anyone else coming here looking for an easy solution without updating their Ruby version. Just use the warning gem to suppress the output.
> ```ruby
> # config/initializers/warning_ignores.rb
> 
> ### https://github.com/jeremyevans/ruby-warning
> 
> Warning.ignore(/warning: parser/)
> ```

I'd certainly prefer the second one but I don't think it has any effect because we are shelling-out to `ruby -S rubocop` or `bundle exec rspec` anyway. The warning ignores we use won't apply there.

**Comment by MikeMcQuaid** [comment]
> It looks to me like the warnings are triggered (at least for `brew style`) when using a `system` call. So if my understanding is correct, we can't actually ignore those warning within the brew code. We could pass `-W0` to the call, though.

We just removed this because it will hide actual failures causing it to look like RuboCop is successful when it's actually failed.



> I don't know of a way to disable a specific warning although it's totally possible that there is a way.

This gem, pretty much.



> It looks to me like the warnings are triggered (at least for `brew style`) when using a `system` call. So if my understanding is correct, we can't actually ignore those warning within the brew code.

It should be possible if we can either inject code into the RuboCop process somehow or write our own wrapper and call RuboCop from Ruby (still in a new process) after we've run the code we want.

**Comment by Rylan12** [comment]
Done in #10598
