### ISSUE TITLE
Use CodeCov GitHub Action

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#10506]
**Provide a detailed description of the proposed feature**

Use https://github.com/codecov/codecov-action instead of the CodeCov Ruby gem to report our test results.

**What is the motivation for the feature?**

- we use one fewer gem
- we won't need to hardcode our CodeCov token in the repository (because this works on public repos without tokens)
- the CodeCov upload being a separate step makes the `brew tests` output more readable because it's very noisy as-is with CodeCov upload information

**How will the feature be relevant to at least 90% of Homebrew users?**

It will not be.

**What alternatives to the feature have been considered?**

The status quo.

**Comment by thomasrockhu** [comment]
Tom from Codecov here, I'll take a look this week!
