### ISSUE TITLE
Allow formulae to allow overridable JAVA_HOME but verify the override matches a version or version range

### ISSUE THREAD

**Issue by srudolph-credera** [Homebrew/brew#10503]
**Provide a detailed description of the proposed feature**

Add a new method in Library/Homebrew/language/java.rb alongside the existing `java_home_env` and a `overridable_java_home_env` methods that would use an overridden JAVA_HOME if and only if the Java installation found there matched a range of versions passed into he method call.

**What is the motivation for the feature?**

Library/Homebrew/language/java.rb currently provides both a `java_home_env` and a `overridable_java_home_env` method that either allow the formula author to force a particular Java version or allow the end user to pick a different Java installation by setting their JAVA_HOME. This latter option provides the user with choice, but when the formula requires a particular Java version (or range of versions) to run, it comes at the cost of usability for users with a JAVA_HOME set to an incompatible installation - they're left debugging a problem.

For example, SonarQube officially requires Java 11 (but works with versions 11-14). A user working with either Java 8 (still common) or Java 15 (to work with the very latest non-LTS release) for development might wish to analyze their project and install the sonarqube or sonarqube-lts formula to do so. These formulae depend on OpenJDK 11 but use the `overridable_java_home_env` method, so when the user starts SonarQube, it will fail.

This new method would provide a "best of both worlds" option that allowed user choice without damaging the user experience.

**How will the feature be relevant to at least 90% of Homebrew users?**

This would allow formula authors to improve user experience for users of the 84 formulae that use java_home_env or overridable_java_home_env.

**What alternatives to the feature have been considered?**

An alternative to a new method in Library/Homebrew/language/java.rb is showing a message to the user in the console that indicates which JAVA_HOME is being used to launch the tool, whether that setting is overridable, and if so, instructions for using an override.

**Comment by carlocab** [comment]
>showing a message to the user in the console that indicates which JAVA_HOME is being used to launch the tool, whether that setting is overridable, and if so, instructions for using an override

Something like this might be feasible. The original suggestion would be rather complicated to implement.

The way `overridable_java_home_env` works is that `brew` creates a wrapper script that sets the appropriate environment variables before calling the relevant executable.

I suppose it _may_ be possible to build a version check into that wrapper script. However, unless different JDKs feature a common API for version verification, this would not be straightforward to implement. (Doing version checks in a shell script isn't fun either.) A version check may also slow down calls to your application, and you might not want that.

**Comment by srudolph-credera** [comment]
All of my Java folders have a `release` text file with the version line (e.g. `JAVA_VERSION="1.8.0_241"` or `JAVA_VERSION="11.0.10"`), I'm not sure whether that's a standard though and there would have to be some version parsing.

However, if invoking Java isn't out of the question, this should allow us to get the major (specification) version cleanly:  `$JAVA_HOME/bin/java -XshowSettings:properties -version 2>&1 | grep java.vm.specification.version | awk -F\ =\  '{ print $2 }'`.

For the console message approach - would that potentially cause issues with users invoking the formulae as part of a script and not expecting the additional output? There may be a workaround for that though.

**Comment by srudolph-credera** [comment]
After my previous post, I did some digging and found that the Apache commons project uses the java.vm.specification.version property to determine Java version, although interestingly they choose to do a prefix match instead of an exact match: https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/SystemUtils.java. 

Possible (prefix) values they look for are currently: `1.1`, `1.2`, `1.3`, `1.4`, `1.5`, `1.6`, `1.7`, `1.8`, `9`, `10`, `11`, `12`, `13`, `14`, & `15`.

**Comment by MikeMcQuaid** [comment]
I'd want to see this be applicable to at least 5+ formulae before we add a new DSL for it.

**Comment by srudolph-credera** [comment]
I started looking through all of the packages with Java dependencies and finished reviewing all that use the `overridable_java_home_env` method (I count 120 more that I haven't reviewed). For the purposes of this survey, I did not consider compatibility below Java 8.

Here are the formula that would benefit from the proposed method (or at least benefit from using the non-overridable `java_home_env` method, with the drawback of limiting user choice):

- There are a few that strictly require Java 8: cassandra (and cassandra@2.2), sbt@0.13, and voldemort (plus druid if you count that they explicitly state higher than v8 is strictly experimental)
- There are a few that need at least Java 11 (higher versions for some): gradle-profiler (for JFR feature), questdb, prestosql
- There are a few that are compatible with Java 11, but not Java 15: sonarqube and sonartqube-lts of course (also incompatible with v8), languagetool (v15 support [merged](https://github.com/languagetool-org/languagetool/issues/4061), but unreleased),

**Comment by srudolph-credera** [comment]
I'm interested in attempting a fix here, but was delayed due to the extreme winter weather Texas
