### ISSUE TITLE
Cache parallel_runtime_rspec.log

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#10507]
**Provide a detailed description of the proposed feature**

The parallel tests gem we're using groups tests better based on test runtime. If this file is cached between runs and jobs then our parellisation should be more efficient.

**What is the motivation for the feature?**

Speeding up test runtime using documented behaviour.

**How will the feature be relevant to at least 90% of Homebrew users?**

It will not be.

**What alternatives to the feature have been considered?**

The status quo.

**Comment by Manav-Kumar** [comment]
Hi, I'm new to HomeBrew open source and wishes to contribute in it by working on this issue. Can someone give me a heads up upon this.

**Comment by carlocab** [comment]
Please go ahead and work on it, @Manav-Kumar. You may find this guide helpful: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

Thanks!

**Comment by hyuraku** [comment]
@MikeMcQuaid 
Can we solve this issue by adding the two below?
1 `--runtime-log` option to [parallel_args](https://github.com/Homebrew/brew/blob/6d883d1808e5f506f1294ec84c5e6f9813f3efe6/Library/Homebrew/dev-cmd/tests.rb#L101)  in `dev-cmd/tests.rb` 
2. `parallel tests log path for cache` to `.github/tests.yml`

**Comment by MikeMcQuaid** [comment]
@hyuraku Yes, that sounds right!
