### ISSUE TITLE
Error trying to upgrade some packages after brew upgraded

### ISSUE THREAD

**Issue by IAMdanloaiza** [Homebrew/brew#10519]
I am running Mac sierra with latest brew version.

**`brew config` output**

--
will provide it later

**`brew doctor` output**

--
will provide it later

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

I am trying to install any upgrade with my brew and it just failed with 

```
tar xof /path/brew/downloads/xxxxx.xz -C /private/temp/directory-output/
```

**What happened (include all command output)?**

Error with tar xof path -C output dir

**What did you expect to happen?**

I just expect brew  to upgrade my obsolete packages

**Step-by-step reproduction instructions (by running `brew` commands)**

For example:
brew upgrade gnutls

Or 

brew upgrade tcl-tk

**Comment by carlocab** [comment]
We can reopen this later when you've provided the necessary information. Thanks!

**Comment by iMichka** [comment]
Also (from your logs):
```
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
```

**Comment by IAMdanloaiza** [comment]
Yeah i know about my outdated mac version. But it fail over a tar decompress action. I think i can find a way to install or link to a expected tar version.

**Comment by gromgit** [comment]
> ```
> tar (child): xz: Cannot exec: No such file or directory
> ```

This says `tar` couldn't find the `xz` program to do the decompression. Suggest you `brew install xz`, then try again.

**Comment by IAMdanloaiza** [comment]
Yeah i installed xz before creating this issue.

```
/usr/local/Cellar/xz/5.2.5
```

**Comment by gromgit** [comment]
What's the output of `type -p xz tar`?

**Comment by IAMdanloaiza** [comment]
```
% type -p xz tar
xz is /usr/local/bin/xz
tar is /usr/local/bin/tar
```

**Comment by gromgit** [comment]
What's the output of `file /usr/local/bin/xz`?

**Comment by IAMdanloaiza** [comment]
this:

```
% file /usr/local/bin/xz
/usr/local/bin/xz: Mach-O 64-bit executable x86_64
```

**Comment by gromgit** [comment]
What's the output of `tar tof /Users/papachan/Library/Caches/Homebrew/downloads/a7cfa9aec46b39827e31cf24566ee2f2f6fba451f76efe179441ddbc0e51b90e--tcllib-1.20.tar.xz | head -n 10`?

**Comment by IAMdanloaiza** [comment]
```
% tar tof /Users/papachan/Library/Caches/Homebrew/downloads/a7cfa9aec46b39827e31cf24566ee2f2f6fba451f76efe179441ddbc0e51b90e--tcllib-1.20.tar.xz | head -n 10

tcllib-1.20/
tcllib-1.20/sak.tcl
tcllib-1.20/idoc/
tcllib-1.20/idoc/man/
tcllib-1.20/idoc/man/toc.n
tcllib-1.20/idoc/man/files/
tcllib-1.20/idoc/man/files/modules/
tcllib-1.20/idoc/man/files/modules/tool/
tcllib-1.20/idoc/man/files/modules/tool/tool.n
tcllib-1.20/idoc/man/files/modules/tool/meta.n
```

**Comment by MikeMcQuaid** [comment]
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Twitter or any other official channels. You are responsible for resolving
> any issues you experience while you are running this
> old version.

Also, if you do the whole "I'm not filling in the template" dance again: you will be blocked.
