### ISSUE TITLE
When brew is used, an error is reported：'/usr/local/opt/libyaml/lib/libyaml-0.2.dylib' not found

### ISSUE THREAD

**Issue by aboutmydreams** [Homebrew/brew#10520]
**`brew config` output**

brew
Traceback (most recent call last):
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	17: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	16: from /usr/local/Homebrew/Library/Homebrew/global.rb:34:in `<top (required)>'
	15: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n.rb:55:in `backend'
	14: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/config.rb:21:in `backend'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/backend/simple.rb:3:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/backend/base.rb:3:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.rb:13:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle, 0x0009): dependent dylib '/usr/local/opt/libyaml/lib/libyaml-0.2.dylib' not found for '/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle' - /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle (LoadError)

**`brew doctor` output**

brew
Traceback (most recent call last):
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	17: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	16: from /usr/local/Homebrew/Library/Homebrew/global.rb:34:in `<top (required)>'
	15: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n.rb:55:in `backend'
	14: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/config.rb:21:in `backend'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/backend/simple.rb:3:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/backend/base.rb:3:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.rb:13:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle, 0x0009): dependent dylib '/usr/local/opt/libyaml/lib/libyaml-0.2.dylib' not found for '/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle' - /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle (LoadError)

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

I want to use brew install some libs, and I run the `brew update-reset`

**What happened (include all command output)?**

brew update-reset
==> Fetching /usr/local/Homebrew...
remote: Enumerating objects: 841, done.
remote: Counting objects: 100% (841/841), done.
remote: Compressing objects: 100% (281/281), done.
remote: Total 841 (delta 535), reused 841 (delta 535)
Receiving objects: 100% (841/841), 398.25 KiB | 2.95 MiB/s, done.
Resolving deltas: 100% (535/535), completed with 175 local objects.
From https://mirrors.ustc.edu.cn/brew
   bca8f6aa1..92caaf8c3  master     -> origin/master

==> Resetting /usr/local/Homebrew...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
remote: Enumerating objects: 467, done.
remote: Counting objects: 100% (467/467), done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 467 (delta 284), reused 467 (delta 284)
Receiving objects: 100% (467/467), 326.78 KiB | 3.05 MiB/s, done.
Resolving deltas: 100% (284/284), completed with 44 local objects.
From https://mirrors.ustc.edu.cn/homebrew-cask
   ef7dea366b..3c73a0b893  master     -> origin/master

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
remote: Enumerating objects: 6735, done.
remote: Counting objects: 100% (6735/6735), done.
remote: Compressing objects: 100% (647/647), done.
remote: Total 6735 (delta 6088), reused 6735 (delta 6088)
Receiving objects: 100% (6735/6735), 1.87 MiB | 8.00 MiB/s, done.
Resolving deltas: 100% (6088/6088), completed with 4784 local objects.
From https://mirrors.ustc.edu.cn/homebrew-core
   8253d9f5e8..0ae3a2e522  master     -> origin/master

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Updating files: 100% (4920/4920), done.
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.
---
brew
brew
Traceback (most recent call last):
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	17: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	16: from /usr/local/Homebrew/Library/Homebrew/global.rb:34:in `<top (required)>'
	15: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n.rb:55:in `backend'
	14: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/config.rb:21:in `backend'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/backend/simple.rb:3:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/backend/base.rb:3:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.rb:13:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle, 0x0009): dependent dylib '/usr/local/opt/libyaml/lib/libyaml-0.2.dylib' not found for '/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle' - /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle (LoadError)

**What did you expect to happen?**

have no LoadError

**Step-by-step reproduction instructions (by running `brew` commands)**

brew
Traceback (most recent call last):
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	17: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	16: from /usr/local/Homebrew/Library/Homebrew/global.rb:34:in `<top (required)>'
	15: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n.rb:55:in `backend'
	14: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/config.rb:21:in `backend'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/backend/simple.rb:3:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/backend/base.rb:3:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.rb:13:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle, 0x0009): dependent dylib '/usr/local/opt/libyaml/lib/libyaml-0.2.dylib' not found for '/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle' - /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle (LoadError)

**Comment by carlocab** [comment]
Do you still get these errors after doing `brew update-reset`? What is the output of `git -C $(brew --repo) describe`?

**Comment by Bo98** [comment]
Running `gem uninstall psych` will probably fix this. You can reinstall it later if you have a Ruby project that really needs it.

(Not sure if there's a nice way we can make `brew` ignore system-installed gems.)

**Comment by MikeMcQuaid** [comment]
This is specific to your machine.

**Comment by aboutmydreams** [comment]
> git -C $(brew --repo) describe

git -C $(brew --repo) describe
2.7.4-463-g92caaf8c3

And I still get these errors after doing brew update-reset?

**Comment by aboutmydreams** [comment]
> This is specific to your machine.

I used rvm install my ruby when I develop, and now I update brew and find it error, and I cant use rvm reinstall the ruby...

**Comment by aboutmydreams** [comment]
> Running `gem uninstall psych` will probably fix this. You can reinstall it later with a working libyaml if you have a Ruby project that really needs it.
> 
> (Not sure if there's a nice way we can make `brew` ignore user-installed gems.)

Thank, but it don't work
hope brew ignore user-installed gems oneday

**Comment by Bo98** [comment]
There’s a small error in my suggestion: I should have said to use /usr/bin/gem rather than just `gem`

**Comment by aboutmydreams** [comment]
> There’s a small error in my suggestion: I should have said to use /usr/bin/gem rather than just `gem`
> […](#)
> On 6 Feb 2021, at 14:50, aboutmydreams ***@***.***> wrote: ﻿ Running gem uninstall psych will probably fix this. You can reinstall it later with a working libyaml if you have a Ruby project that really needs it. (Not sure if there's a nice way we can make brew ignore user-installed gems.) Thank, but it don't work hope brew ignore user-installed gems oneday — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

thx, its not work
my machine’s problem.
