### ISSUE TITLE
File is downloaded twice if remote server does not support ranges

### ISSUE THREAD

**Issue by stek29** [Homebrew/brew#10528]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force` – not applicable
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

curl based fetcher seems to work in two stages: first by requesting file with range 0-1, and later by downloading the file with some info being discovered on first curl invocation.
however, if remote server does not support ranged downloads, file is downloaded twice, being completely discarded on first try.

It's easier to notice when server is also painfully slow (like portswigger's burp suite)

#### Output of command with `--verbose --debug`

```
❯ brew install --cask --verbose --debug burp-suite
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.7-154-g6c1bd25\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://portswigger.net/burp/releases/download\?product=community\&version=2020.12.1\&type=MacOsx
==> Downloading https://portswigger.net/burp/releases/download?product=community&version=2020.12.1&type=MacOsx
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.7-154-g6c1bd25\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://portswigger.net/burp/releases/download\?product=community\&version=2020.12.1\&type=MacOsx
```

it gets stuck on this stage. running that curl command in terminal shows that range header was ignored by remote server and curl is trying to download whole file.

**Comment by jonchang** [comment]
To fix this issue we could probably avoid sending the initial 0-1 range request to /dev/null and instead save it to a temporary file. Then we can examine the content-length from the headers and compare it to the final file to determine if we need to do a full download.

**Comment by wilkmaciej** [comment]
Total newbie here but wouldn't adding "--head"argument just solve the problem? 
I tested it with a few casks that i use and seems to work fine.
I read that some servers may block HEAD request but don't know of any.
