### ISSUE TITLE
GCC Installation failure in Ubuntu Linux

### ISSUE THREAD

**Issue by sivaswami** [Homebrew/brew#10529]
**`brew config` output**

I created a symbolic link in home for linuxbrew

• • • brew config
HOMEBREW_VERSION: 2.7.7-162-g42b755e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 42b755e13f36c34e6a751182f1ec8d7170351549
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c41576ea2f345c26de7cf65c4851d25f38cbd891
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/sivaswami/WORK/STOP/SOFT/BREW
HOMEBREW_REPOSITORY: /home/sivaswami/WORK/STOP/SOFT/BREW
HOMEBREW_CELLAR: /home/sivaswami/WORK/STOP/SOFT/BREW/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/sivaswami/WORK/STOP/SOFT/BREW/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 11.0 build (parse error)
Git: 2.30.0 => /home/sivaswami/WORK/STOP/SOFT/BREW/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.8.0-41-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: 5.5.0_7
xorg: N/A

**`brew doctor` output**

• • • brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  libva-internal

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/libpng16-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/icu-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/python3.6m-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/krb5-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/curl-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/xslt-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/python3.6-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/python3-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/pcre-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/libpng-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/xml2-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/freetype-config
  /home/sivaswami/WORK/STOP/SOFT/ANACONDA3/bin/ncursesw6-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gcc@6

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /home/sivaswami/WORK/STOP/SOFT/BREW/lib/python3.9/ensurepip/_bundled/pip-20.2.3-py2.py3-none-any.whl
  /home/sivaswami/WORK/STOP/SOFT/BREW/lib/python3.9/ensurepip/_bundled/setuptools-49.2.1-py3-none-any.whl
  /home/sivaswami/WORK/STOP/SOFT/BREW/share/man/man5/package-locks.5
  /home/sivaswami/WORK/STOP/SOFT/BREW/share/man/man5/shrinkwrap-json.5
Warning: Use wayland instead of deprecated linuxbrew/xorg/wayland
Warning: Use libvdpau instead of deprecated linuxbrew/xorg/libvdpau
Warning: Use wayland-protocols instead of deprecated linuxbrew/xorg/wayland-protocols
Warning: Use wayland instead of deprecated linuxbrew/xorg/wayland
Warning: Use libvdpau instead of deprecated linuxbrew/xorg/libvdpau
Warning: Use wayland-protocols instead of deprecated linuxbrew/xorg/wayland-protocols
Warning: Use wayland instead of deprecated linuxbrew/xorg/wayland
Warning: Use libvdpau instead of deprecated linuxbrew/xorg/libvdpau
Warning: Use wayland-protocols instead of deprecated linuxbrew/xorg/wayland-protocols
Warning: Use libvdpau instead of deprecated linuxbrew/xorg/libvdpau
Warning: Use wayland-protocols instead of deprecated linuxbrew/xorg/wayland-protocols

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

brew upgrade

**What happened (include all command output)?**

==> Upgrading gcc@6 -> 6.5.0_6 
Warning: Building gcc@6 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/sivaswami/WORK/STOP/SOFT/BREW/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/sivaswami/WORK/STOP/SOFT/BREW)
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-6.5.0/gcc-6.5.0.tar.xz
Already downloaded: /home/sivaswami/.cache/Homebrew/downloads/0a7c1b4768113746153c6e06f4ea6b2abf2d8ba48a68bf28f7c686b70117540e--gcc-6.5.0.tar.xz
==> ../configure --prefix=/home/sivaswami/WORK/STOP/SOFT/BREW/Cellar/gcc@6/6.5.0
==> make bootstrap
Last 15 lines from /home/sivaswami/.cache/Homebrew/Logs/gcc@6/02.make:
mv -f .deps/futex.Tpo .deps/futex.Plo
mv -f .deps/method-gl.Tpo .deps/method-gl.Plo
mv -f .deps/method-ml.Tpo .deps/method-ml.Plo
/bin/bash ./libtool --tag=CC   --mode=link /tmp/gcc-6-20210204-13003-bsdx97/gcc-6.5.0/build/./gcc/xgcc -B/tmp/gcc-6-20210204-13003-bsdx97/gcc-6.5.0/build/./gcc/ -B/home/sivaswami/WORK/STOP/SOFT/BREW/Cellar/gcc@6/6.5.0_6/x86_64-pc-linux-gnu/bin/ -B/home/sivaswami/WORK/STOP/SOFT/BREW/Cellar/gcc@6/6.5.0_6/x86_64-pc-linux-gnu/lib/ -isystem /home/sivaswami/WORK/STOP/SOFT/BREW/Cellar/gcc@6/6.5.0_6/x86_64-pc-linux-gnu/include -isystem /home/sivaswami/WORK/STOP/SOFT/BREW/Cellar/gcc@6/6.5.0_6/x86_64-pc-linux-gnu/sys-include    -mrtm -Wall -Werror  -Wc,-pthread -g -O2   -Wl,-O1    -o libitm.la -version-info 1:0:0 -Wl,--version-script,../../../libitm/libitm.map -rpath /home/sivaswami/WORK/STOP/SOFT/BREW/Cellar/gcc@6/6.5.0_6/lib/gcc/6 aatree.lo alloc.lo alloc_c.lo alloc_cpp.lo barrier.lo beginend.lo clone.lo eh_cpp.lo local.lo query.lo retry.lo rwlock.lo useraction.lo util.lo sjlj.lo tls.lo method-serial.lo method-gl.lo method-ml.lo  x86_sse.lo x86_avx.lo futex.lo  
libtool: link: /tmp/gcc-6-20210204-13003-bsdx97/gcc-6.5.0/build/./gcc/xgcc -B/tmp/gcc-6-20210204-13003-bsdx97/gcc-6.5.0/build/./gcc/ -B/home/sivaswami/WORK/STOP/SOFT/BREW/Cellar/gcc@6/6.5.0_6/x86_64-pc-linux-gnu/bin/ -B/home/sivaswami/WORK/STOP/SOFT/BREW/Cellar/gcc@6/6.5.0_6/x86_64-pc-linux-gnu/lib/ -isystem /home/sivaswami/WORK/STOP/SOFT/BREW/Cellar/gcc@6/6.5.0_6/x86_64-pc-linux-gnu/include -isystem /home/sivaswami/WORK/STOP/SOFT/BREW/Cellar/gcc@6/6.5.0_6/x86_64-pc-linux-gnu/sys-include    -shared  -fPIC -DPIC  .libs/aatree.o .libs/alloc.o .libs/alloc_c.o .libs/alloc_cpp.o .libs/barrier.o .libs/beginend.o .libs/clone.o .libs/eh_cpp.o .libs/local.o .libs/query.o .libs/retry.o .libs/rwlock.o .libs/useraction.o .libs/util.o .libs/sjlj.o .libs/tls.o .libs/method-serial.o .libs/method-gl.o .libs/method-ml.o .libs/x86_sse.o .libs/x86_avx.o .libs/futex.o    -mrtm -pthread -Wl,-O1 -Wl,--version-script -Wl,../../../libitm/libitm.map   -Wl,-soname -Wl,libitm.so.1 -o .libs/libitm.so.1.0.0
libtool: link: (cd ".libs" && rm -f "libitm.so.1" && ln -s "libitm.so.1.0.0" "libitm.so.1")
libtool: link: (cd ".libs" && rm -f "libitm.so" && ln -s "libitm.so.1.0.0" "libitm.so")
libtool: link: ar rc .libs/libitm.a  aatree.o alloc.o alloc_c.o alloc_cpp.o barrier.o beginend.o clone.o eh_cpp.o local.o query.o retry.o rwlock.o useraction.o util.o sjlj.o tls.o method-serial.o method-gl.o method-ml.o x86_sse.o x86_avx.o futex.o
libtool: link: ranlib .libs/libitm.a
libtool: link: ( cd ".libs" && rm -f "libitm.la" && ln -s "../libitm.la" "libitm.la" )
make[4]: Leaving directory '/tmp/gcc-6-20210204-13003-bsdx97/gcc-6.5.0/build/x86_64-pc-linux-gnu/libitm'
make[3]: Leaving directory '/tmp/gcc-6-20210204-13003-bsdx97/gcc-6.5.0/build/x86_64-pc-linux-gnu/libitm'
make[2]: Leaving directory '/tmp/gcc-6-20210204-13003-bsdx97/gcc-6.5.0/build/x86_64-pc-linux-gnu/libitm'
make[1]: Leaving directory '/tmp/gcc-6-20210204-13003-bsdx97/gcc-6.5.0/build'
make: *** [Makefile:22634: bootstrap] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
gcc: align with upstream https://github.com/Homebrew/linuxbrew-core/pull/21380
gcc@10: rebuild for isl version bump https://github.com/Homebrew/linuxbrew-core/pull/22135
gcc@10 install broken on CentOS 7 https://github.com/Homebrew/linuxbrew-core/issues/22128

**What did you expect to happen?**

Upgrade gcc

**Step-by-step reproduction instructions (by running `brew` commands)**

export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
export HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar
brew update
brew upgrade
brew doctor
brew link
brew upgrade
-- still fails.

**Comment by jonchang** [comment]
> Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
> Some of Homebrew's bottles (binary packages) can only be used with the default
> prefix (/home/linuxbrew/.linuxbrew).
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Twitter or any other official channels. You are responsible for resolving
> any issues you experience while you are running this
> unsupported configuration.

**Comment by danielnachun** [comment]
You actually don't need to build gcc from source - just use `brew uninstall --ignore-dependencies gcc@6` and then `brew install --force-bottle gcc@6`.  I am working on a fix for `gcc` so that `--force-bottle` is no longer needed, but for now this workaround will get you by.
