### ISSUE TITLE
ohai_stdout_or_stderr - wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by fjarlq** [Homebrew/brew#10542]
**`brew config` output**

HOMEBREW_VERSION: 3.0.0-13-g15ae53c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 15ae53c049c498d9f07ddc9e208c1d7dd56857fd
Last commit: 82 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 149d62524beea0231087f189a242fddc325adb3b
Core tap last commit: 47 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.2vFtLpH6iS/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit penryn
Clang: 10.0 build 1001
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.7.0_80
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

`brew upgrade`

**What happened (include all command output)?**

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 6df0a49fb to 15ae53c04.
Updated 4 taps (homebrew/core, homebrew/cask, homebrew/bundle and homebrew/cask-fonts).
==> New Formulae
coin3d                                      dasel                                       libprelude
Error: wrong number of arguments (given 2, expected 1)
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:114:in `ohai_stdout_or_stderr'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:489:in `dump'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:132:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
==> Upgrading 2 outdated packages:
glib 2.66.5 -> 2.66.6
awscli 2.1.23 -> 2.1.24
==> Upgrading glib 2.66.5 -> 2.66.6
==> Downloading https://homebrew.bintray.com/bottles/glib-2.66.6.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/af5ee309e12bba797dbf59bb5553591fa901eb8314f290aa2f30a50c286922c4?response
######################################################################## 100.0%
==> Pouring glib-2.66.6.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.66.6: 441 files, 20.4MB
Removing: /usr/local/Cellar/glib/2.66.5... (441 files, 20.4MB)
Removing: /Users/mday/Library/Caches/Homebrew/glib--2.66.5.mojave.bottle.tar.gz... (6.2MB)
==> Upgrading awscli 2.1.23 -> 2.1.24
==> Downloading https://homebrew.bintray.com/bottles/awscli-2.1.24.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/83370f45160b45dcf8010880cb7622807dbc9d1d7785c6273bc040335e4ae277?response
######################################################################## 100.0%
==> Pouring awscli-2.1.24.mojave.bottle.tar.gz
==> Caveats
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/awscli/2.1.24: 11,995 files, 93MB
Removing: /usr/local/Cellar/awscli/2.1.23... (12,618 files, 97.8MB)
Removing: /Users/mday/Library/Caches/Homebrew/awscli--2.1.23.mojave.bottle.tar.gz... (22.6MB)
==> Caveats
==> awscli
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
```

**What did you expect to happen?**

`brew upgrade` should complete without errors

**Step-by-step reproduction instructions (by running `brew` commands)**

Running `brew upgrade` again doesn't seem to reproduce the problem, probably because there are no packages to update right now?

But it looks to me like the syntax error still exists at https://github.com/Homebrew/brew/blob/15ae53c049c498d9f07ddc9e208c1d7dd56857fd/Library/Homebrew/cmd/update-report.rb#L489

also on lines 360, 401, and 501?

https://github.com/Homebrew/brew/blob/15ae53c049c498d9f07ddc9e208c1d7dd56857fd/Library/Homebrew/cmd/update-report.rb#L360

https://github.com/Homebrew/brew/blob/15ae53c049c498d9f07ddc9e208c1d7dd56857fd/Library/Homebrew/cmd/update-report.rb#L401

https://github.com/Homebrew/brew/blob/15ae53c049c498d9f07ddc9e208c1d7dd56857fd/Library/Homebrew/cmd/update-report.rb#L501

**Comment by carlocab** [comment]
Should've been fixed in https://github.com/Homebrew/brew/pull/10541. Try `brew update` and see if that fixes the problem.

**Comment by fjarlq** [comment]
Sure enough. Sorry for failing to find the earlier bug report.
