### ISSUE TITLE
Permission issues with multi-user system

### ISSUE THREAD

**Issue by diogoeichert** [Homebrew/brew#10546]
**`brew config` output**

HOMEBREW_VERSION: 2.7.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: cd191a7f6c4c8e053336d0ea34a9886b12d06470
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9385ea155478cf4a05c0f0ca73cab79b16fa44d8
Core tap last commit: 5 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Trying to install packages with an admin account which was not the account that installed Homebrew. Because this is a multi-user system and has more than one administrator account.

**What happened (include all command output)?**

Error: /usr/local/Homebrew is not writable. You should change the
ownership and permissions of /usr/local/Homebrew back to your
user account:
  sudo chown -R $(whoami) /usr/local/Homebrew
==> Caveats
zdoom has been officially discontinued upstream.
It may stop working correctly (or at all) in recent versions of macOS.

Error: Download failed on Cask 'zdoom' with message: No such file or directory @ dir_s_rmdir - /usr/local/var/homebrew/locks/da6ce441f43834b3c58f1d45b8c6e0a451e1c7884b0ba72ceb249121b3e07f71--zdoom-2.8.1.dmg.incomplete.lock

**What did you expect to happen?**

- Expected Homebrew to handle multi-user systems gracefully, allowing different administrator accounts to manage the installed packages;
- Also expected Homebrew to **not** recommend changing the ownership of `/usr/local/Homebrew` directory, because that would then cause problems to the other administrator account, it should instead suggest setting group write permissions, since the directory belongs to the `admin` group already.

**Step-by-step reproduction instructions (by running `brew` commands)**

In the above case, `brew install zdoom` was issued by the second administrator account. The `zdoom` package was used just for the purpose of providing detailed information in this issue report, but the same behavior happens with any package, cask or not.

**Comment by gromgit** [comment]
It's already a work in progress: https://github.com/Homebrew/install/pull/328

**Comment by MikeMcQuaid** [comment]
This is current unsupported as-is. We'll accept pull requests to improve behaviour.
