### ISSUE TITLE
`check_xcode_select_path` doctor diagnostic gives wrong text if Xcode is not installed

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/brew#1055]
If Xcode is not installed, the `check_xcode_select_path` diagnostic prints the following:

```
Warning: Your Xcode is configured with an invalid path.
You should change it to the correct path:
  sudo xcode-select -switch /Developer
```

`/Developer` should never be the right path on 10.12, and suggesting `-switch` is misleading if the user doesn't have Xcode at all. `check_for_installed_developer_tools` properly identified that no developer tools were installed, so I imagine the check should be skippable.

**Comment by zmwangx** [comment]
What about

```
sudo xcode-select --reset
```

**Comment by everedifice** [comment]
It seems to be can't find Xcode library on 10.12 version (Sierra)

my new MacBook has same symptom.

**Comment by DomT4** [comment]
@everedifice What's your `brew config`?

`softwareupdate --list` may be useful as well.

**Comment by everedifice** [comment]
@DomT4 Problem solved. `softwareupdate --list` notify me that need Command Line Tool update.

So I update that with `softwareupdate -ira`. after that, it works!

**Comment by mistydemeo** [comment]
@zmwangx I think that's useful if the CLT's installed, but we should probably skip the test entirely if neither is present.
