### ISSUE TITLE
Replacing current python version, while other modules upgrade

### ISSUE THREAD

**Issue by attashe** [Homebrew/brew#10556]
**Provide a detailed description of the proposed feature**

Brew replaces python version while upgrades other modules

**What is the motivation for the feature?**

I'm furious, when updating something like Node.js, brew decides to update the python version without asking for any permissions, unlike other packages, updating python entails having to install dozens of packages. 

With new version of python I get new errors
```
Traceback (most recent call last):
  File "/usr/local/opt/python/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```

**How will the feature be relevant to at least 90% of Homebrew users?**

This will eliminate the situation where users have to kill an hour to install the necessary python packages. And also after reinstalling python, homebrew leaves site-packages of the old version, which clog up the hard disk and can weigh several gigabytes. 

**What alternatives to the feature have been considered?**

I know about disabling authomatic updates for dependency packages. But some packages have dozens dependencies and it make worse my work with homebrew every time  when it breaks my workspace.

**Comment by SinisterStairs** [comment]
Have you tried pinning Python to the current version?  That way you could still upgrade all your other packages except Python.  `brew help pin`

**Comment by Rylan12** [comment]
You can read more in our FAQ about [pinning versions](https://docs.brew.sh/FAQ#how-do-i-stop-certain-formulae-from-being-updated), [keeping old versions](https://docs.brew.sh/FAQ#how-can-i-keep-old-versions-of-a-formula-when-upgrading), and [why things are upgraded automatically](https://docs.brew.sh/FAQ#why-does-brew-upgrade-formula-also-upgrade-a-bunch-of-other-stuff).

If you rely on python for virtual environments or require a stable version for whatever reason, Homebrew's Python is not right for your use case. You should be using something like `pyenv` instead (which you can install with Homebrew) to manage your python installations. This will not break when Homebrew upgrades our Python formula. Homebrew's Python is really just there for occasional Python invocations and for use by other Homebrew formulae.

See [this article](https://justinmayer.com/posts/homebrew-python-is-not-for-you/) for a good explanation.

**Comment by attashe** [comment]
> Have you tried pinning Python to the current version? That way you could still upgrade all your other packages except Python. `brew help pin`

I had pinned python version. It worked for a long time but stopped.
