### ISSUE TITLE
Suggestion: Add notes and/or tags to formulae/casks

### ISSUE THREAD

**Issue by SinisterStairs** [Homebrew/brew#10555]
**Provide a detailed description of the proposed feature**

It would be nice if an optional `--note` and/or multiple `--tag` could specified when `install`-ling packages.

My use cases are primarily for correlating Homebrew packages with software not managed by Homebrew.  For examples, noting why particular packages were installed:
- `--note "This library was installed because 3rd party software X [not in Homebrew] requires it"`
- `--note "This older version of Java 6 is required to run an applicant's JAR file"`
and/or, more sophisticated tagging could be implemented:
- Remind myself to delete packages that are only needed temporarily:  `--tag delete`
- Categorize packages that will attempt to run as `root`:  `--tag sudo`
- Categorize packages that are games:  `--tag game`
If both notes and tags were implemented, using the examples above, a use case could be:
- `--note "This version of Java 6 is required to run an applicant's JAR file" --tag delete` to note why I installed Java 6, and a tag to remind myself to delete it later

If either `--note` or `--tag` were implemented, it'd be natural for them to be usable with other commands:
- `brew pin --note "Software Z does not support newer versions"`
- `brew list --installed --tag delete` to show all installed packages that are tagged for deletion
- `brew note` to add/clear notes to a package (that may or may not be installed)
- `brew tag` to add/remove/clear tags to a package (that may or may not be installed)
- `brew bundle dump` could include notes/tags to be applied, or simply add them as #comments for reference

My apologies in advance if this has been proposed in the past.

**What is the motivation for the feature?**

Primarily for correlating Homebrew formulae/casks with software, libraries, scripts, etc. that are not managed by Homebrew.  Also a way to organize packages, or remind the user about the need for particular packages.

**How will the feature be relevant to at least 90% of Homebrew users?**

It would help users remember why they installed a package, or to help categorize packages.

For examples:
- `brew list --installed --tag gfx` to show all the packages I installed that are used for graphics
- `brew list --tag games` to show all packages that have been tagged as games
- `brew list --installed --tag delete` to list all the packages I've tagged to be deleted

**What alternatives to the feature have been considered?**

Excel/Sheets, text file, pen & paper, human memory

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this. A `Brewfile` with comments is likely the best current workaround.
