### ISSUE TITLE
Unable to install brew. 

### ISSUE THREAD

**Issue by jmaleonard** [Homebrew/brew#10564]
**`brew config` output**

No brew on my machine

**`brew doctor` output**

No brew on my machine

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Install brew on my new machine

**What happened (include all command output)?**

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

returned 

```
==> Downloading and installing Homebrew...
Checking out files: 100% (2523/2523), done.
HEAD is now at f416f8b54 Merge pull request #10534 from Bo98/doctor-ci
Error: 
  homebrew-core is a shallow clone.
  homebrew-cask is a shallow clone.
To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
These commands may take a few minutes to run due to the large size of the repositories.
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!

```

**What did you expect to happen?**

Have brew installed. 

**Step-by-step reproduction instructions (by running `brew` commands)**

Open any terminal. 

Run - `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

Then I get the above error.

**Comment by MikeMcQuaid** [comment]
> To `brew update`, first run:
>   git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
>   git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow

Do this.

**Comment by jmaleonard** [comment]
Thanks!
