### ISSUE TITLE
`brew info` doesn't re-read available formulae after auto-tap

### ISSUE THREAD

**Issue by gromgit** [Homebrew/brew#10584]
**`brew config` output**

HOMEBREW_VERSION: 3.0.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ebc7cc36a0e029d58fac8cebd1b5ff583b3fd95b
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 627a335d2d645ff7166b2f53f98705d4ecf24134
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: hexa-core 64-bit skylake
Clang: N/A
Git: 2.29.0 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 5.4.0-65-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.7 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: N/A
xorg: N/A

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

I was trying to figure out where formula install-time options were saved, to expand on my reply to https://github.com/Homebrew/discussions/discussions/748#discussioncomment-353804 , so I chose the third-party `mongodb-community` formula to experiment on. To verify that it had options, I ran `brew info` on it.

**What happened (include all command output)?**

`mongodb/brew` was auto-tapped, but `brew info` still failed to find the formula:
```
$ brew info mongodb/brew/mongodb-community
==> Tapping mongodb/brew
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/mongodb/homebrew-brew'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 533 (delta 9), reused 6 (delta 1), pack-reused 503
Receiving objects: 100% (533/533), 114.71 KiB | 255.00 KiB/s, done.
Resolving deltas: 100% (247/247), done.
Tapped 11 formulae (39 files, 265.3KB).
Error: No available formula or cask with the name "mongodb/brew/mongodb-community".
```
But the formula clearly exists:
```
$ brew search mongodb
==> Formulae
mongodb/brew/libmongocrypt                    mongodb/brew/mongodb-community                mongodb/brew/mongodb-community@3.2            mongodb/brew/mongodb-community@3.6            mongodb/brew/mongodb-community@4.2            mongodb/brew/mongosh
mongodb/brew/mongocli                         mongodb/brew/mongodb-community-shell          mongodb/brew/mongodb-community@3.4            mongodb/brew/mongodb-community@4.0            mongodb/brew/mongodb-database-tools
==> Casks
homebrew/cask-versions/mongodb-compass-beta                          homebrew/cask/mongodb-compass                                        homebrew/cask/mongodb-compass-readonly                               homebrew/cask/nosqlbooster-for-mongodb
homebrew/cask/gcollazo-mongodb                                       homebrew/cask/mongodb-compass-isolated-edition                       homebrew/cask/mongodb-realm-studio
```
And a second `brew info` does find it:
```
$ mongodb/brew/mongodb-community: stable 4.4.3
High-performance, schema-free, document-oriented database
https://www.mongodb.com/
Not installed
From: https://github.com/mongodb/homebrew-brew/blob/HEAD/Formula/mongodb-community.rb
==> Dependencies
Recommended: mongodb-database-tools ✘
==> Options
--without-mongodb-database-tools
	Build without mongodb-database-tools support
==> Caveats
Warning: mongodb-community provides a launchd plist which can only be used on macOS!
You can manually execute the service instead with:
  mongod --config /home/linuxbrew/.linuxbrew/etc/mongod.conf
```

**What did you expect to happen?**

Auto-tapping on any operation should trigger a load of the newly-available formulae before resuming that operation, so `brew info` should have worked the first time.

**Step-by-step reproduction instructions (by running `brew` commands)**

```bash
$ brew untap mongodb/brew
$ brew info mongodb/brew/mongodb-community   # first run fails
$ brew info mongodb/brew/mongodb-community   # second run succeeds
```

**Comment by Bo98** [comment]
I'm not sure if it's meant to auto-tap. The thing doing the auto-tapping is actually the Cask loader.

**Comment by hyuraku** [comment]
>  The thing doing the auto-tapping is actually the cask loader.

I agree that. 
In `NamedArgs#load_formula_or_cask`,  `if only != :formula`  function two things these returning Cask info and auto-tapping. 
It Should be separated `return Cask` and `auto-tapping`
