### ISSUE TITLE
CONTRIBUTING.md should be improved to direct users to the repo for the vast majority of formula-related issues they'd be filing

### ISSUE THREAD

**Issue by beej** [Homebrew/brew#10580]
**Provide a detailed description of the proposed feature**

CONTRIBUTING.md currently has:
`Open an issue on the formula's repository or on Homebrew/brew if it's not a formula-specific issue.`

It should be more helpful in directing users to https://github.com/Homebrew/homebrew-core/issues for the case of formula-specific issues related to the homebrew/core tap, which I'd venture to say would cover the vast majority of issues in that case.

**What is the motivation for the feature?**

Saving users the trouble in trying to figure out where to report relevant issues.

**How will the feature be relevant to at least 90% of Homebrew users?**

I'd venture that 90% of Homebrew users who come up against issues don't even consider reporting them, but for those that do, this would be relevant.

See, eg, https://github.com/Homebrew/discussions/discussions/757

**What alternatives to the feature have been considered?**

This isn't really a feature so much as an improvement.  The alternative is to not improve the document.  That seems clearly less desirable to me, but perhaps I'm missing something.

**Comment by Rylan12** [comment]
Can you open a PR with the changes you'd like to see?
