### ISSUE TITLE
build with debug symbols

### ISSUE THREAD

**Issue by alex-tee** [Homebrew/brew#10591]
**Provide a detailed description of the proposed feature**

add an option to keep debug symbols: https://github.com/Homebrew/legacy-homebrew/issues/29030

**What is the motivation for the feature?**

I want to build my formula without stripping symbols (-g)

**How will the feature be relevant to at least 90% of Homebrew users?**

idk

**What alternatives to the feature have been considered?**

none

**Comment by jonchang** [comment]
See https://docs.brew.sh/FAQ#how-can-i-specify-different-configure-arguments-for-a-formula and/or https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap. Please always fill out the pull request template.

**Comment by alex-tee** [comment]
it looks like homebrew strips symbols away anyway, regardless of if you build a formula with debug symbols (`-g`). is there a way to make homebrew not strip symbols from binaries?
