### ISSUE TITLE
ansible 2.10.7 incorrect build?

### ISSUE THREAD

**Issue by sfuerte** [Homebrew/brew#10596]
**`brew config` output**

HOMEBREW_VERSION: 3.0.1-10-g0d36d54
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0d36d54ede5b95730b9474b6a448866997bbce4f
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: af80e75a862c809f0f7197d4fffdb9d64d633c69
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A

**`brew doctor` output**

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See:
  https://github.com/Homebrew/brew/issues/5558

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install python@3.8

Run `brew missing` for more details.

> brew missing
azure-cli: python@3.8

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Have Ansible installed via Homebrew for a while. Just caught my eye today that the actual version doesn't match the Cellar's one. See below.

PS: nevermind warnings above, Bitdefender is a corporate policy and python@3.8 is related to another package.

**What happened (include all command output)?**

> which ansible
/usr/local/bin/ansible

> ls -l /usr/local/bin/ansible
lrwxr-xr-x  1 <USER>  admin  36 Feb 10 10:48 /usr/local/bin/ansible -> ../Cellar/ansible/2.10.7/bin/ansible

> ansible --version
ansible 2.10.5
  config file = .../ansible.cfg
  configured module search path = ['/Users/<USER>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.7/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Feb  3 2021, 07:38:02) [Clang 12.0.0 (clang-1200.0.32.29)]

> brew info ansible
ansible: stable 2.10.7 (bottled), HEAD
Automate deployment, configuration, and upgrading
https://www.ansible.com/
/usr/local/Cellar/ansible/2.10.7 (37,810 files, 359.3MB) *
  Poured from bottle on 2021-02-10 at 10:48:56
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ansible.rb
License: GPL-3.0-or-later
==> Dependencies
Build: pkg-config ✔, rust ✘
Required: libyaml ✔, openssl@1.1 ✔, python@3.9 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 46,771 (30 days), 133,800 (90 days), 449,971 (365 days)
install-on-request: 46,450 (30 days), 132,252 (90 days), 437,882 (365 days)
build-error: 0 (30 days)

**What did you expect to happen?**

> ansible --version
ansible 2.10.7
...

**Step-by-step reproduction instructions (by running `brew` commands)**

```
brew install ansible
```

**Comment by sfuerte** [comment]
Actually, found the problem. Can be closed.

**Comment by unikitty37** [comment]
@sfuerte Could you elaborate on your fix, please?

I've just run `brew upgrade ansible` which has linked /usr/local/bin/ansible to ../Cellar/ansible/3.0.0/bin/ansible, yet `ansible --version` still shows ansible 2.10.6 rather than the expected 3.0.0…

**Comment by sfuerte** [comment]
@unikitty37, there is no fix. It's just maintainers of the Brew package are jumping the gun. Somehow it was released in Homebrew under 3.0.0 but the official Ansible release is still 2.10.6 ! Hence the confusion.
Verify here - https://github.com/ansible/ansible/releases

**Comment by carlocab** [comment]
We follow the version on PyPI, which is 3.0.0: https://pypi.org/project/ansible/

**Comment by sfuerte** [comment]
@carlocab, it is indeed 3.0.0 on PyPI. But then something wrong with the package? 
Because the installed version equals one on the Github.

```
> ansible --version
ansible 2.10.6
  config file = None
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/3.0.0/libexec/lib/python3.9/site-packages/ansible
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.2 (default, Feb 24 2021, 05:06:40) [Clang 12.0.0 (clang-1200.0.32.29)]

> brew info ansible
ansible: stable 3.0.0 (bottled), HEAD
Automate deployment, configuration, and upgrading
https://www.ansible.com/
/opt/homebrew/Cellar/ansible/3.0.0 (39,605 files, 370.6MB) *
  Poured from bottle on 2021-02-23 at 16:19:47
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ansible.rb
License: GPL-3.0-or-later
==> Dependencies
Build: pkg-config ✔, rust ✘
Required: libyaml ✔, openssl@1.1 ✔, python@3.9 ✔
==> Options
--HEAD
	Install HEAD version

> which ansible
/opt/homebrew/bin/ansible

> ls -l /opt/homebrew/bin/ansible
lrwxr-xr-x  1 user  staff  35 23 Feb 16:19 /opt/homebrew/bin/ansible -> ../Cellar/ansible/3.0.0/bin/ansible
```

**Comment by carlocab** [comment]
There may be, but it's not a bug in the formula. I installed `ansible` into a throwaway virtual env:
```
❯ cd $(mktemp -d)
❯ source venv/bin/activate
❯ pip install ansible
[snip]
❯ which -a ansible
/private/var/folders/kb/pf4wbfc512z47l56g5072l900000gn/T/tmp.hxzFLjC1Ni/venv/bin/ansible
❯ ansible --version
ansible 2.10.6
  config file = None
  configured module search path = ['/Users/carlocab/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /private/var/folders/kb/pf4wbfc512z47l56g5072l900000gn/T/tmp.hxzFLjC1Ni/venv/lib/python3.9/site-packages/ansible
  executable location = /private/var/folders/kb/pf4wbfc512z47l56g5072l900000gn/T/tmp.hxzFLjC1Ni/venv/bin/ansible
  python version = 3.9.2 (default, Feb 24 2021, 13:26:09) [Clang 12.0.0 (clang-1200.0.32.29)]
```
If it bothers you that much, you should report it to the ansible developers.

**Comment by sfuerte** [comment]
Neh, it doesn't bother me now when I know. Just found it confusing :D

**Comment by Bo98** [comment]
It is showing the version number of `ansible-base` rather than the CLI `ansible` frontend. Future versions of `ansible` will tweak the output of `--version` to make this clearer: https://github.com/ansible/ansible/pull/72287
