### ISSUE TITLE
Don't run Ruby with -W0

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#10593]
**Provide a detailed description of the proposed feature**

We should avoid running `ruby -W0` because it hides legitimate code style issues (as well as annoying messages).

This could be a multistep process:
- use the `warning` gem added in https://github.com/Homebrew/brew/pull/10583 to selectively hide the various warning messages
- remove the use of `-W0`
- one-by-one remove each of the warnings and the causes of those warnings

**What is the motivation for the feature?**

https://github.com/Homebrew/brew/pull/10583 indicated the confusion that results from us setting this.

**How will the feature be relevant to at least 90% of Homebrew users?**

A more reliable Homebrew that doesn't ignore warnings. A more idiomatic Ruby codebase.

**What alternatives to the feature have been considered?**

The status quo.

**Comment by Rylan12** [comment]
I'm a little confused with what the default is/should be here.

For testing, I removed [these lines] from [`brew.sh`](https://github.com/Homebrew/brew/blob/0d36d54ede5b95730b9474b6a448866997bbce4f/Library/Homebrew/brew.sh#L577-L580) and ran a few `brew` commands.

So far, I've had no warnings pop up. If I add `HOMEBREW_RUBY_WARNINGS="-W2"` to my environment (and re-add the lines above), I _do_ see lots of messages. If I stick with `-W1` or totally unset `HOMEBREW_RUBY_WARNINGS`, I don't seem to have any warnings.

So, is the goal to always run with `-W2` and have no warnings?

**Comment by MikeMcQuaid** [comment]
> I'm a little confused with what the default is/should be here.

I would say just the Ruby default (`-W1`?).

> So far, I've had no warnings pop up.

Neat. It could be some/all of these have been fixed (as `rubocop` will flag and fix some of them).

**Comment by Rylan12** [comment]
Is this a fair summary of the warning levels?

- `-W0`: show no warnings
- `-W1`: only show "custom warnings" thrown using `#warn`
- `-W2`: show internal ruby warnings as well (e.g. `warning: instance variable @foo not initialized`)

Assuming that's correct, I think we should definitely switch to `-W1`. We don't use the `warn` method anywhere, the only newly-ignored instances would be when another gem does so. I'll open a PR to make this change later.

Setting `-W2` _does_ raise warnings. Is removing these warnings and running with `-W2` a goal of ours? Some of the warnings are probably fixable, and we manually ignore others as needed.

For ignoring, having something like this would probably be good.

```ruby
ignore_warnings :method_redefined, /custom warning/ do
  code_with_warnings
end
```

**Comment by Bo98** [comment]
> Is removing these warnings and running with `-W2` a goal of ours?

I think it's reasonable to fix any warnings worth fixing. I don't think we'd run `-W2` by default - maybe by default under `HOMEBREW_DEVELOPER` if the number of warnings gets down to zero but I suspect there may be some third-party warnings that aren't our responsibility.

**Comment by MikeMcQuaid** [comment]
> Assuming that's correct, I think we should definitely switch to `-W1`. We don't use the `warn` method anywhere, the only newly-ignored instances would be when another gem does so. I'll open a PR to make this change later.

Yup, perfect 👍🏻 

> I think it's reasonable to fix any warnings worth fixing. I don't think we'd run `-W2` by default - maybe by default under `HOMEBREW_DEVELOPER` if the number of warnings gets down to zero but I suspect there may be some third-party warnings that aren't our responsibility.

Agreed! It's almost certain some gems we use will have some warnings.

**Comment by Rylan12** [comment]
Makes sense, thank you both for your input.

Hearing this, I think I may try keeping `-W2` around for a little and see if I can cleanup some warnings. That will be the best way to judge whether or not getting down to (nearly) 0 warnings is possible. If it gets pretty close and there are just some gem warnings, I may open a PR to selectively ignore those. But that will probably be far in the future, this seems like a more longterm project.

**Comment by MikeMcQuaid** [comment]
> Hearing this, I think I may try keeping `-W2` around for a little and see if I can cleanup some warnings.

That'd be nice!


---

Considering the original intent of this fixed by https://github.com/Homebrew/brew/pull/10598. Thanks @Rylan12!

**Comment by Rylan12** [comment]
Yeah, given that switching to `-W2` is not really a priority and we're now running with `-W1`, I'm going to close this. Any changes to solve `-W2` errors are just "extra fixes" at this point.

**Comment by Rylan12** [comment]
You know, I'm not sure how much progress will be made here. The number of warnings with `-W2` is pretty overwhelming. I see a ton of method redefined warnings that I doubt we're going to remove. I guess we could globally ignore this warning if desired because we're certainly not going to manually ignore the warning every time we define a method.

And lots of these methods are intentional redefinitions in e.g. `extend/os`.

**Comment by Bo98** [comment]
> method redefined warnings

Is it wanting an `undef` beforehand? We do that in a few places.
