### ISSUE TITLE
brew update prints to stdout

### ISSUE THREAD

**Issue by kbadk** [Homebrew/brew#10609]
**`brew config` output**

	  HOMEBREW_VERSION: 3.0.1-36-ge2cbc91-dirty <-- Due to diagnostic `puts` and `set -x` lines.
	  ORIGIN: https://github.com/Homebrew/brew
	  HEAD: e2cbc916891861a461a4fcc81303a04118bb79ca
	  Last commit: 54 minutes ago
	  Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
	  Core tap HEAD: 0a7da28732c97d99858f28671c014ef17d55b066
	  Core tap last commit: 4 minutes ago
	  Core tap branch: master
	  HOMEBREW_PREFIX: /usr/local
	  HOMEBREW_CASK_OPTS: []
	  HOMEBREW_EDITOR: cw
	  HOMEBREW_MAKE_JOBS: 12
	  HOMEBREW_NO_AUTO_UPDATE: set
	  Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
	  CPU: dodeca-core 64-bit kabylake
	  Clang: 12.0 build 1200
	  Git: 2.30.0 => /usr/local/bin/git
	  Curl: 7.64.1 => /usr/bin/curl
	  macOS: 10.15.7-x86_64
	  CLT: 11.0.33.17
	  Xcode: 12.3

**`brew doctor` output**

	Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Run `brew update` in a cronjob (no tty).

**What happened (include all command output)?**

The following line

    Updated 3 taps (homebrew/core, homebrew/cask and homebrew/services).

was sent to stderr (might be related to https://github.com/Homebrew/brew/pull/10537/files) instead of stdout, although it is clearly not an error.

**What did you expect to happen?**

The same as what happened until a few days ago: Regular non-error output is sent to stdout, so cron doesn't send me mails.

**Step-by-step reproduction instructions (by running `brew` commands)**

1. Put `/usr/local/bin/brew update >> /some/path/brew-log` in a cronjob.
2. Wait for the cronjob to run and update packages.
3. Open a new terminal and notice that you've received mail from cron ("You have mail").

**Comment by MikeMcQuaid** [comment]
This is intentional behaviour for non-TTYs so that e.g. `$(brew bundle list)` won't output invalid output when it auto-updates.

**Comment by kbadk** [comment]
I don't see how it's intentional that non-errors are sent to standard error.

If this is intentional, was the previous behavior – the behavior that has existed for years where regular output was sent to stdout – "unintentional"? Just trying to figure out how this sudden regression can be considered intentional.

**Comment by MikeMcQuaid** [comment]
> I don't see how it's intentional that non-errors are sent to standard error.

It was an intentional change because we made a pull request to change this behaviour. 

> If this is intentional, was the previous behavior – the behavior that has existed for years where regular output was sent to stdout – "unintentional"?

Yes: the side-effect of having these messages output to a TTY was a shortcoming given our typical `brew update` workflow is through autoupdate.

**Comment by brorbw** [comment]
This seems like a misuse of stderr. I get why some might consider it easier to send to stderr but its clearly not the right place to send the message.

**Comment by MikeMcQuaid** [comment]
We do this already in several places e.g. printing the tapping output.

**Comment by dkav** [comment]
@MikeMcQuaid what is your recommendation for dealing with the issue @kbadk reported? Redirect all output and ignore errors? The [new addition](https://github.com/Homebrew/brew/pull/10581) to the update-report is also being added to stderr.

**Comment by MikeMcQuaid** [comment]
@dkav We do not consider it an issue. My recommendation is not not to do anything.
