### ISSUE TITLE
`bump-formula-pr` should allow multiple `--mirror` options

### ISSUE THREAD

**Issue by Moisan** [Homebrew/brew#10600]
**Provide a detailed description of the proposed feature**

Currently, when using the `brew bump-formula-pr` command, if multiple `--mirror` options are given, only the last one is used. This feature would use all the `--mirror` options.

**What is the motivation for the feature?**

Handling multiple `--mirror` options would allow to update directly formulae with multiple `mirror` URLs.

**How will the feature be relevant to at least 90% of Homebrew users?**

My understanding is that `bump-formula-pr` exists to ease the creation of PR to bump formulae version. This would help at least 90% by easing further the creation of the PRs for the formulae having multiple mirrors. Multiple mirrors also help to make sure the source code is always available to users.

**What alternatives to the feature have been considered?**

The current alternative is to manually fix the missing mirror URLs.

**Comment by carlocab** [comment]
Doesn't `--mirror` work if it's followed by a comma-separated list? e.g.,
```
brew bump-formula-pr --mirror=https://www.one.com/hello.tar.gz,https://www.two.com/hello.tar.gz hello
```
The help says it does:
```
      --mirror                     Use the specified URL as a mirror URL. If
                                   URL is a comma-separated list of URLs,
                                   multiple mirrors will be added.

```

**Comment by gromgit** [comment]
On a side note, is there a reason `#{version}` and other expansions aren't used in `mirror` URLs? I just did a test to confirm that they expand correctly, and I can't think of a case where the mirror URL differs so greatly from the original as to make such expansions pointless.
```bash
$ grep 127.0.0.1 /etc/hosts
127.0.0.1	localhost www.gnupg.org
$ grep -h mirror $(brew --repo homebrew/core)/Formula/gnutls.rb
mirror "https://www.mirrorservice.org/sites/ftp.gnupg.org/gcrypt/gnutls/v3.6/gnutls-#{version}.tar.xz"
$ brew install -s gnutls
...
==> Downloading https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.15.tar.xz

curl: (7) Failed to connect to www.gnupg.org port 443: Connection refused
Trying a mirror...
==> Downloading https://www.mirrorservice.org/sites/ftp.gnupg.org/gcrypt/gnutls/v3.6/gnutls-3.6.15.tar.xz
######################################################################## 100.0%
```

**Comment by Bo98** [comment]
It wouldn't work for formulae with custom versions, since currently the component order is `mirror` comes before `version`.

**Comment by Moisan** [comment]
@carlocab : I must confess that I didn't check the help of the command before opening the issue. I would will close this issue for now since it's less a pressing concern than I first thought.

The mirror version question seems like a different issue. Feel free to reopen if you disagree.
