### ISSUE TITLE
homebrew: packages: ansible: missed ovirt-engine-sdk-python lib

### ISSUE THREAD

**Issue by k0ste** [Homebrew/brew#10618]
[ovirt-engine-sdk-python](https://pypi.org/project/ovirt-engine-sdk-python/) is required for [Ansible oVirt collections](https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/).

**Comment by carlocab** [comment]
Please don't ignore the issue template. If it doesn't seem applicable, that's a big indicator that you're in the wrong place.
