### ISSUE TITLE
problem installing php56-sphinx

### ISSUE THREAD

**Issue by wanglilong2013** [Homebrew/brew#1061]
brew reinstall homebrew/php/php56-sphinx
==> Reinstalling homebrew/php/php56-sphinx
==> Downloading https://pecl.php.net/get/sphinx-1.3.2.tgz
Already downloaded: /Users/wanglilong/Library/Caches/Homebrew/php56-sphinx-1.3.2.tgz
==> /usr/local/opt/php56/bin/phpize
Last 15 lines from /Users/wanglilong/Library/Logs/Homebrew/php56-sphinx/01.phpize:
2016-09-21 21:42:13 +0800

/usr/local/opt/php56/bin/phpize

/usr/local/opt/php56/bin/phpize: line 61: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php56/bin/phpize: line 62: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php56/bin/phpize: line 63: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
Configuring for:
PHP Api Version:        
Zend Module Api No:     
Zend Extension Api No:  
/usr/local/opt/php56/bin/phpize: line 155: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
autoheader: error: AC_CONFIG_HEADERS not found in configure.in

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

**Comment by MikeMcQuaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting
> If reporting this issue please do so at (not Homebrew/brew):
> https://github.com/Homebrew/homebrew-php/issues

Please do so.
