### ISSUE TITLE
old brew doesn't run on Big Sur

### ISSUE THREAD

**Issue by JonathanGoodman** [Homebrew/brew#10627]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

[JonathansMBP20:~] jg% brew doctor
Traceback (most recent call last):
	11: from /usr/local/Library/brew.rb:6:in `<main>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Library/Homebrew/global.rb:7:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Library/Homebrew/os.rb:1:in `<top (required)>'
	 4: from /usr/local/Library/Homebrew/os.rb:16:in `<module:OS>'
	 3: from /usr/local/Library/Homebrew/os/mac.rb:18:in `version'
	 2: from /usr/local/Library/Homebrew/os/mac.rb:18:in `new'
	 1: from /usr/local/Library/Homebrew/os/mac/version.rb:25:in `initialize'
/usr/local/Library/Homebrew/version.rb:186:in `initialize': Version value must be a string (TypeError)
[JonathansMBP20:~] jg% brew config
Traceback (most recent call last):
	11: from /usr/local/Library/brew.rb:6:in `<main>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Library/Homebrew/global.rb:7:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Library/Homebrew/os.rb:1:in `<top (required)>'
	 4: from /usr/local/Library/Homebrew/os.rb:16:in `<module:OS>'
	 3: from /usr/local/Library/Homebrew/os/mac.rb:18:in `version'
	 2: from /usr/local/Library/Homebrew/os/mac.rb:18:in `new'
	 1: from /usr/local/Library/Homebrew/os/mac/version.rb:25:in `initialize'

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

bring my cmake up to date

**What happened (include all command output)?**

Every command gives the same output.  For example
 brew --version
Traceback (most recent call last):
	11: from /usr/local/Library/brew.rb:6:in `<main>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Library/Homebrew/global.rb:7:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Library/Homebrew/os.rb:1:in `<top (required)>'
	 4: from /usr/local/Library/Homebrew/os.rb:16:in `<module:OS>'
	 3: from /usr/local/Library/Homebrew/os/mac.rb:18:in `version'
	 2: from /usr/local/Library/Homebrew/os/mac.rb:18:in `new'
	 1: from /usr/local/Library/Homebrew/os/mac/version.rb:25:in `initialize'
/usr/local/Library/Homebrew/version.rb:186:in `initialize': Version value must be a string (TypeError)

I don't know if this helps, but the version.rb file in /usr/local/Library/Homebrew/os/mac starts with a list of mac operating systems that doesn't include Big Sur.  Here's the beginning of that file.

require "version"

module OS
  module Mac
    class Version < ::Version
      SYMBOLS = {
        :el_capitan    => "10.11",
        :yosemite      => "10.10",
        :mavericks     => "10.9",
        :mountain_lion => "10.8",
        :lion          => "10.7",
        :snow_leopard  => "10.6",
        :leopard       => "10.5",
        :tiger         => "10.4"
      }

**What did you expect to happen?**

I would be glad to delete my old brew and install the most recent one, but my old brew won't do that.

**Step-by-step reproduction instructions (by running `brew` commands)**

I hope this is clear from above

**Comment by JonathanGoodman** [comment]
Thanks.  Unfortunately the same thing happened.  I think I need to manually delete my brew and install a fresh brew:
 jg% brew update-reset
Traceback (most recent call last):
	11: from /usr/local/Library/brew.rb:6:in `<main>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Library/Homebrew/global.rb:7:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Library/Homebrew/os.rb:1:in `<top (required)>'
	 4: from /usr/local/Library/Homebrew/os.rb:16:in `<module:OS>'
	 3: from /usr/local/Library/Homebrew/os/mac.rb:18:in `version'
	 2: from /usr/local/Library/Homebrew/os/mac.rb:18:in `new'
	 1: from /usr/local/Library/Homebrew/os/mac/version.rb:25:in `initialize'
/usr/local/Library/Homebrew/version.rb:186:in `initialize': Version value must be a string (TypeError)

**Comment by carlocab** [comment]
Possibly. What version of ruby are you running? i.e. what is the output of
```
which -a ruby
ruby --version
```
?

If `brew --repo` works, you can also try
```
git -C $(brew --repo) clean -xdf
git -C $(brew --repo) pull --ff-only
brew update
```

If `brew --repo` doesn't work, you need to replace `$(brew --repo)` with the location of `HOMEBREW_REPOSITORY`. In a default installation that's `/usr/local/Homebrew` (on ARM, I think it should just be `/opt/homebrew`).

**Comment by MikeMcQuaid** [comment]
> I think I need to manually delete my brew and install a fresh brew:

Yes, do this.

**Comment by JonathanGoodman** [comment]
Thanks, I’ll try to do this. 

     — Jonathan
