### ISSUE TITLE
No brew issue template?

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#10622]
When I try to open a new `brew` issue, the templates offered do not actually include any option to open a `brew` issue:

<img width="1448" alt="Capture d’écran 2021-02-15 à 16 42 14" src="https://user-images.githubusercontent.com/1980544/107966908-c54abe00-6fac-11eb-9104-ace6b0db6b6a.png">

How are users or maintainers supposed to open a `brew` issue? I managed to do so because I modified the github URL, but otherwise I don't know how it's supposed to happen.

**Comment by Rylan12** [comment]
Looks like #10607 broke the issue templates. I'm seeing the following warning on the [`bug.yml`](https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE/bug.yml) [`feature.yml`](https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE/feature.yml) files.

CC @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
This needed to be merged next Friday, not last Friday 🤦🏻.
