### ISSUE TITLE
brew should error out when CLT is not there

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#10623]
macOS minor updates are systematically wiping out CLT installs since macOS 11. `brew doctor` will warn about it, but running other operations in `brew` will not, and will lead to weird results that are totally not user-friendly.

One example, running a simple `brew upgrade` will build GCC from source instead of just telling me “no“:

```
==> Upgrading 1 outdated package:
gcc 10.2.0_3 -> 10.2.0_4
==> Upgrading gcc 10.2.0_3 -> 10.2.0_4 
Warning: Building gcc from source:
  The bottle needs the Xcode CLT to be installed.
```

I don't think that behaviour is “doing what's right for users”. I would suggest that we simply require CLT to be installed on macOS >= 11, and bail out when we find it is not.

**Comment by fxcoudert** [comment]
I would add that this is causing endless trouble and confusion to users, as noted in discussions, on twitter, and here: https://github.com/Homebrew/brew/issues/10275#issuecomment-777716550

**Comment by Bo98** [comment]
We do now require this on Apple Silicon, as of Homebrew 3.0.1 (https://github.com/Homebrew/brew/pull/10533), which should effectively fix #10275 (will have to wait for the next macOS update to see the benefits though).

I do see the annoyance of `brew upgrade gcc` on Intel though.

**Comment by MikeMcQuaid** [comment]
We have some people who want to just use the CLT as part of Xcode. Given the size of the install, though, I can see an argument for just enforcing this globally.

We could also consider tracking if we've _ever_ seen the CLT installed and, if so, error out hard if you try to do anything and it's not there.

**Comment by Bo98** [comment]
There's also the case that we do support (on Intel only) having _no_ dev tools installed if only consuming bottles.

**Comment by MikeMcQuaid** [comment]
> There's also the case that we do support (on Intel only now) having _no_ dev tools installed if only consuming bottles.

Good point.

> `gcc` is a bit of an exception that it mandates CLT. We could perhaps have a system to make such enforcements stronger rather than a "build from source" fallback.

Agreed. That's what I thought here: maybe this should just refuse to install rather than building from source? Same deal for all our other bottle requirements like this.

**Comment by MikeMcQuaid** [comment]
@Bo98 I think what we're both zeroing in on is essentially making `HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK` the default.

**Comment by Bo98** [comment]
`HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK` does not cover this scenario, but yes that general idea is what I think we're looking at.

**Comment by MikeMcQuaid** [comment]
Opened a PR to tackle all this in https://github.com/Homebrew/brew/pull/10640
