### ISSUE TITLE
Unable to use any brew commands

### ISSUE THREAD

**Issue by iliyaST** [Homebrew/brew#10621]
**`brew config` output**

zsh: command not found: brew

**`brew doctor` output**

zsh: command not found: brew

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

zsh: command not found: brew

**What happened (include all command output)?**

istalled on mac using this command:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
then i could not use it

**What did you expect to happen?**

I was expecting to be able to run brew commands

**Step-by-step reproduction instructions (by running `brew` commands)**

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" run in the zsh
brew install
zsh: command not found: brew

**Comment by carlocab** [comment]
Did you follow the instructions that the installer showed you about adding `brew` to your `PATH`?

**Comment by iliyaST** [comment]
What do you mean instructions ? 
I tried running this 
echo $PATH
which -a brew
export PATH="/opt/homebrew/bin:$PATH"
echo $PATH
which -a brew 
But still getting zsh: command not found: witch

**Comment by carlocab** [comment]
When the installer finishes, it shows you something like
```
==> Next steps:
- Add Homebrew to your PATH in /Users/homefolder/.zprofile:
    echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> /Users/homefolder/.zprofile
    eval $(/opt/homebrew/bin/brew shellenv)
- Run `brew help` to get started
```
The exact message will depend on which shell you're running, and the path to your `HOME` directory. You may need to restart your terminal for this to work.
