### ISSUE TITLE
Environment variable to whitelist packages to prevent brew cleanup?

### ISSUE THREAD

**Issue by AlJohri** [Homebrew/brew#10633]
**Provide a detailed description of the proposed feature**

Create an environment variable that whitelists packages from homebrew cleanup, even when manually running `brew cleanup` unless it is passed `--force`. Ideally add python to this whitelist by default.

**What is the motivation for the feature?**

This recent blogpost describes a problem I've been experiencing with homebrew+python for quite sometime: https://justinmayer.com/posts/homebrew-python-is-not-for-you/

I don't know if the feature request posed is the _best_ solution but homebrew is definitely getting harder to use for python.

Homebrew's automatic upgrade+cleanup of minor and patch versions of python break all existing virtual environments. This poses problems for any venv created for development purposes or tool-specific venvs created by pipx.

**How will the feature be relevant to at least 90% of Homebrew users?**

There are hundreds of bug reports all over the place that look like:

```
dyld: Library not loaded: @executable_path/../.Python
Referenced from: /your/home/.virtualenvs/your-env-name/bin/python
Reason: image not found
```

which all stem from the underlying python being upgraded/deleted/moved etc.

**What alternatives to the feature have been considered?**

Alternatives include using something like pyenv or asdf for python development, however this requres using shim-based tools which can at time be unideal.

And tools like `pipx` which create venvs can be installed outside of homebrew and depend on a pyenv or asdf based-python which will not be automatically upgraded/deleted.

To illustrate how pernicious this issue can be, pipx has created an entire command, `pipx reinstall-all`, almost exclusively because of this problem with homebrew.

**Comment by carlocab** [comment]
What is the issue with using shims?

Homebrew's default configuration isn't designed for you to be able to carefully manage the versions of software you have installed. I'm concerned that making it easier to use Homebrew for something it isn't meant for is just liable to encourage people to cultivate bad habits. (They're doing that already, but no need to make it worse.)

If you need to pin the versions of software you've installed using `brew` (and if you really must use `brew`, rather than another tool actually designed for that purpose), then the correct solution is to `brew extract` the formula you need to your own tap and use that.

**Comment by AlJohri** [comment]
>What is the issue with using shims?

@carlocab here's one example of shims failing: https://github.com/jezdez/envdir/issues/62. the TL;DR is when using a globally installed tool installed via pyenv, the pyenv shim adds the global python to the beginning of the PATH. if the the tool were installed using homebrew python OR within the virtualenv itself, this problem wouldn't occur

> Homebrew's default configuration isn't designed for you to be able to carefully manage the versions of software you have installed.

My argument here is that I don't care what version of python I'm using as long as its the latest (or close to it). This seems exactly what homebrew is designed for.

> I'm concerned that making it easier to use Homebrew for something it isn't meant for is just liable to encourage people to cultivate bad habits.

My recommendation in the past used to be "just use homebrew python" for beginner python developers who don't need to write code specific to any python version. But I'm afraid a tool like `pyenv` or `asdf` is now necessary to use as virtualenvs break automatically otherwise.

> If you need to pin the versions of software you've installed using brew (and if you really must use brew, rather than another tool actually designed for that purpose), then the correct solution is to brew extract the formula you need to your own tap and use that.

I've used `brew pin python` in the past but that has been unideal given how many tools depend on python. I could try the `brew extract` route but I don't really want to pin to a specific version. I just want old virtual envs to not break- new ones can use the latest python version as homebrew auto-upgrades.

**Comment by MikeMcQuaid** [comment]
> This recent blogpost describes a problem I've been experiencing with homebrew+python for quite sometime: https://justinmayer.com/posts/homebrew-python-is-not-for-you/

I read this post and wanted to get annoyed at it based on the title but ended up totally agreeing. Our Python is primarily designed as a dependency for other packages. If that breaks its use as a `virtualenv` for you: use one of the other tools better suited for it. I'm primarily a Ruby developer; I use both Homebrew's Ruby and `rbenv` for different things at different times based on which each is better for.

---

I'm a hard 👎🏻 on this feature as proposed. Given how Python virtualenv centric this is it feels like the obvious and best (although likely not easiest, I'll admit) solution is to fix `virtualenv` and/or the way we install `virtualenv` so it doesn't break like this. 

We already provide a way to prevent upgrade of packages (`brew pin`) and cleanup of packages (`HOMEBREW_NO_INSTALL_CLEANUP`).

There's also the fact that: simply not upgrading Python versions means you don't get bug or security fixes. This is one of the reasons we don't make it easy for you to simply sit on outdated versions forever.

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/pull/73201 was just merged. This might resolve some of the issues you've been having.
