### ISSUE TITLE
Can you update openssl to openssl 1.0.2_stable?

### ISSUE THREAD

**Issue by mikelupo** [Homebrew/brew#1063]
Hi.
It appears that the openssl that is compiled with 'brew install openssl' installs 1.0.2_h. This causes "Trust this computer" to appear incessantly with libimobiledevice. 
Can you please update openssl to build the openssl 1.0.2_stable (openssl 1.1.0 has a bug with what looks like an attempt to call free on an already free'd object)

We are on the latest brew.
brew --version
Homebrew 1.0.0 (git revision a381b; last commit 2016-09-21)
Homebrew/homebrew-core (git revision 1938; last commit 2016-09-21)

**Comment by MikeMcQuaid** [comment]
> 1.0.2_h

This is the latest stable release of OpenSSL: https://www.openssl.org/source/. When they release a newer version we'll install that. Thanks!

**Comment by mikelupo** [comment]
Hi Mike. 
Thanks for the quick response. And for Brew. Love the tool.

I suppose it would be a feature request to allow the forced usage of a specific version of a library? It would certainly be particularly useful.

Thanks again.

**Comment by MikeMcQuaid** [comment]
@mikelupo We may allow you to force major/minor versions in future. We'll never allow forcing patch versions for security reasons.
