### ISSUE TITLE
Add more scheduled job automation

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#10644]
**Provide a detailed description of the proposed feature**

It would be cool to have scheduled jobs run some existing commands we already have

- [x] `brew man` (could allow us to drop the `brew man` CI checks in favour of this job)
- [x] `brew update-maintainers` ~and `brew sponsors`~ (instead of maintainers remembering to run and commit them)
- ~~`brew style --fix` (when doing `vendor-gems` for `rubocop*` gem updates) and perhaps even `brew style --fix` on all relevant dependent repositories that block `rubocop` PRs (homebrew/core, homebrew/bundle, homebrew-test-bot, homebrew/cask) or even all the `homebrew-*` repositories in the organisation~~

**What is the motivation for the feature?**

Have robots do more things instead of humans

**How will the feature be relevant to at least 90% of Homebrew users?**

Maintainers spend less time on automatable tasks

**What alternatives to the feature have been considered?**

Continue to run these commands manually

**Comment by nandahkrishna** [comment]
As @Bo98 suggested over in Slack, would @Homebrew/maintainers be okay with creating a new `Homebrew/admin-workflows` repository (with write access for organisation owners/admins only) for the workflow to update maintainers and sponsors?

These developer commands require tokens with the `read:org` and `admin:org` scopes, thus ruling out a workflow in `Homebrew/brew`, but the automation is desirable.

**Comment by MikeMcQuaid** [comment]
> These developer commands require tokens with the `read:org` and `admin:org` scopes, thus ruling out a workflow in `Homebrew/brew`, but the automation is desirable.

I think `read:org` would be OK but `admin:org` would be a hard pass. Anything this rules out: let's not worry about it I guess (and let me know and I'll score them out).

**Comment by nandahkrishna** [comment]
We'd have to rule out `brew sponsors`, but `brew update-maintainers` would be possible with `read:org`. Do we still want a separate restricted repository for the workflow?

**Comment by Bo98** [comment]
There's no danger of `read:org`. Every member should have it.

**Comment by nandahkrishna** [comment]
Just a status update (and linking relevant PRs):
* `brew man` automation was added in #10650 and the CI check was removed in #10667.
* `brew update-maintainers` will be automated once #10673 is merged.

**Comment by MikeMcQuaid** [comment]
Passing on `brew style --fix` here. Thanks for the work @nandahkrishna!

**Comment by MikeMcQuaid** [comment]
Passing on `brew style --fix` here. Thanks for the work @nandahkrishna!
