### ISSUE TITLE
always error output: Ignoring redcarpet-3.5.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.5.0

### ISSUE THREAD

**Issue by tkosaka1976** [Homebrew/brew#10649]
**`brew config` output**

Ignoring redcarpet-3.5.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.5.0
HOMEBREW_VERSION: 3.0.1-93-g53d840c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 53d840c969fbe7f7cc736f604a486753314aa218
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 703451fe242d959d029d867909ffd92f0d522ffd
Core tap last commit: 8 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.1s9VryR1ZM/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/mate -w
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

**`brew doctor` output**

Ignoring redcarpet-3.5.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.5.0
Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

update or upgrade

**What happened (include all command output)?**

usually showing
: Ignoring redcarpet-3.5.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.5.0

**What did you expect to happen?**

no output

**Step-by-step reproduction instructions (by running `brew` commands)**

brew doctor, brew update, brew upgrade...

**Comment by Bo98** [comment]
You probably have something broken in ~/.gem/ruby/2.6.0. If you have ruby@2.6 installed then you can try uninstall that gem.

**Comment by Bo98** [comment]
For further help, you can ask here: https://github.com/Homebrew/discussions/discussions

**Comment by tkosaka1976** [comment]
Thank you. That was solved.
