### ISSUE TITLE
Congrats on v1.0

### ISSUE THREAD

**Issue by ronaldpetty** [Homebrew/brew#1065]
I appreciate the hard work that goes into something like this.  Aside cash/code, not sure how else to show support (GH star?) except file an issue where no work is required!

Well done.

Ron

**Comment by MikeMcQuaid** [comment]
Thanks @ronaldpetty! GitHub stars, one-off and recurring tax-deductible donations (even if very small) are all appreciated but your kind words are most important ❤️

**Comment by MikeMcQuaid** [comment]
And I forgot the donations link for anyone else who stumbles across this: https://github.com/Homebrew/brew#donations

**Comment by zyradyl** [comment]
@MikeMcQuaid Just wanted to throw in here without opening another issue. I can't tell you how much I appreciate this project, the workflow improvements alone, plus how hackable it is. You guys have done great with it.

Look forward to seeing more from you guys <3

Also hoping to donate here soon :P
