### ISSUE TITLE
brew upgrade command shows 'Warning' when installed is up-to-date, even with --quiet

### ISSUE THREAD

**Issue by timecode** [Homebrew/brew#10666]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

HOMEBREW_VERSION: 3.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: c951be8d3c7b339c7e759b7c40aec859e09a70a5
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 647e215ff8f6d2ecd096f8436fde6fe74f59f56c
Core tap last commit: 31 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit westmere
Clang: 10.0 build 1000
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Upgrade a package (any package, the package is not important)
I am using 'go' purely as an example, below...

**What happened (include all command output)?**

```
brew upgrade --quiet go
Warning: go 1.15.8 already installed
```

**What did you expect to happen?**

I know that the package is already installed - I'm trying to upgrade it...

Without the `--quiet` switch, it's acceptable to provide some feedback, although I would expect something like:
```
Warning/Info: go 1.15.8 already up-to-date
```

However, with the `--quiet` switch, I would not expect a warning when everything is up-to-date?

**Step-by-step reproduction instructions (by running `brew` commands)**

```
# again, any package, the package is not important
# just ensure that the package is already installed
# e.g. brew install go

brew upgrade --quiet go
```

**Comment by fxcoudert** [comment]
```
  -q, --quiet                      Make some output more quiet.
```

It doesn't say “suppress all output”. I think it's fair that a warning is emitted: you're asking explicitly, by name, to upgrade a formula that will not be upgraded. A warning seems in order, in all cases.

**Comment by timecode** [comment]
Almost, hence the suggestion of "already up-to-date" rather than the same message that's given when trying to actually install something that's "already installed". Without the `--quiet` I'd certainly expect to see something like that as there is helpful information there. However, it's not really adding anything, by informing me know that nothing's going to change, when I've specifically requested some 'quietness' :-)

**Comment by timecode** [comment]
I didn't suggest that it should “suppress all output”. I agree with you that this would be the outcome (in this instance), but I'm not saying that should always be the case (other warnings for example, where they provide useful information, may be helpful). It's just that in this case, it doesn't add anything helpful. If an update were available, we would see the update occur (regardless of the `--quiet` switch). I wasn't expecting the `--quiet` switch to **mute** everything (as you've highlighted, it's merely there to "Make **some** output more quiet", which is what I had expected - that 'some' being the warning which I don't care about... hence, wanting to quiet down the resulting output)

**Comment by MikeMcQuaid** [comment]
Passing on this for now given the documentation, sorry.
