### ISSUE TITLE
Error: Status neither has `exitstatus` nor `termsig`.

### ISSUE THREAD

**Issue by defp** [Homebrew/brew#10661]
**`brew config` output**

HOMEBREW_VERSION: 3.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: c951be8d3c7b339c7e759b7c40aec859e09a70a5
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f39001507019da7747deba1099576bb1dbcabdad
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
all_proxy: socks5://127.0.0.1:1235
http_proxy: http://127.0.0.1:1234
https_proxy: http://127.0.0.1:1234
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false

**`brew doctor` output**

❯ brew doctor
Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

brew upgrade

**What happened (include all command output)?**

==> Upgrading rabbitmq 3.8.11 -> 3.8.12
==> Downloading https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.12/rabbitmq-server-generic-unix-3.8.12.tar.xz
Already downloaded: /Users/lidashuang/Library/Caches/Homebrew/downloads/04d6b767c386e6df0fd6e2308cddd690b997e283ebf39808f5ca7d42c6cf967b--rabbitmq-server-generic-unix-3.8.12.tar.xz
==> /usr/bin/unzip -qq -j /opt/homebrew/Cellar/rabbitmq/3.8.12/plugins/rabbitmq_management-3.8.12.ez rabbitmq_management-3.8.12/priv/www/cli/rabbitmqadmin
Error: Status neither has `exitstatus` nor `termsig`.
/opt/homebrew/Library/Homebrew/exceptions.rb:596:in `initialize'
/opt/homebrew/Library/Homebrew/utils/fork.rb:11:in `new'
/opt/homebrew/Library/Homebrew/utils/fork.rb:11:in `rewrite_child_error'
/opt/homebrew/Library/Homebrew/utils/fork.rb:90:in `block (3 levels) in safe_fork'
/opt/homebrew/Library/Homebrew/utils.rb:423:in `ignore_interrupts'
/opt/homebrew/Library/Homebrew/utils/fork.rb:66:in `block (2 levels) in safe_fork'
/opt/homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
/opt/homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/opt/homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
/opt/homebrew/Library/Homebrew/formula_installer.rb:913:in `build'
/opt/homebrew/Library/Homebrew/formula_installer.rb:466:in `install'
/opt/homebrew/Library/Homebrew/upgrade.rb:102:in `upgrade_formula'
/opt/homebrew/Library/Homebrew/upgrade.rb:36:in `block in upgrade_formulae'
/opt/homebrew/Library/Homebrew/upgrade.rb:33:in `each'
/opt/homebrew/Library/Homebrew/upgrade.rb:33:in `upgrade_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:175:in `upgrade_outdated_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:122:in `<main>'

**What did you expect to happen?**

==> Upgrading rabbitmq 3.8.11 -> 3.8.12

**Step-by-step reproduction instructions (by running `brew` commands)**

❯ brew upgrade

**Comment by Bo98** [comment]
There's something wrong with your `/usr/bin/unzip` that's causing it to crash.

There is a `brew` bug here in the way it is reporting the error (we should be marshalling the entire `Process::Status` object in `safe_fork` - not just getting `exitstatus`).

**Comment by defp** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/rabbitmq.rb#L53

**Comment by defp** [comment]
![image](https://user-images.githubusercontent.com/612381/108615652-396be280-7441-11eb-8d44-1de2bd53469c.png)

**Comment by giacomoalonzi** [comment]
Installing heroku cli, getting this error "Status neither has `exitstatus` nor `termsig`"

**Comment by Bo98** [comment]
I'm getting the error fixed - but there is still a genuine error behind it. It should be reading something like:

```
ErrorDuringExecution (Failure while executing; [something] was terminated by uncaught signal [something].)
```

You can maybe look into what was the last thing it did before throwing the error - it's likely that binary/whatever is broken and crashing.
