### ISSUE TITLE
should 'brew edit <name>' ignore existing directories on the filesystem?

### ISSUE THREAD

**Issue by kevinushey** [Homebrew/brew#10674]
**Provide a detailed description of the proposed feature**

`brew edit <name>` should open the formula called `<name>` for editing, even if a directory called `<name>` happens to exist in the current working directory. To illustrate the current behavior:

```
cd /tmp
mkdir r
brew edit r
```

In this case, the directory called `r` is opened for editing, rather than the Homebrew formula for R.

This example is somewhat contrived, but in reality I have a folder called `r` in my home directory and calling `brew edit r` from that directory bumps me into this issue.

**What is the motivation for the feature?**

Removing a small piece of confusion from the `brew edit` interface.

**How will the feature be relevant to at least 90% of Homebrew users?**

My guess is the majority of users would prefer the proposed behavior over the current default behavior.

**What alternatives to the feature have been considered?**

I guess the alternatives are:

1. Do nothing and preserve the status quo;
2. Let users work around this by explicitly managing the working directory before invoking `brew`

**Comment by MikeMcQuaid** [comment]
This is intentional behaviour because we want to have `brew edit` edit a named file in the current working directory if it's present. We have users that rely on this workflow. Sorry!

**Comment by kevinushey** [comment]
No worries; I appreciate your taking the time to consider my request.
