### ISSUE TITLE
Brew is 'Ignoring ffi-1.13.1 because its extensions are not built.'

### ISSUE THREAD

**Issue by gpkirk** [Homebrew/brew#10675]
**`brew config` output**

brew config
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
/Library/Ruby/Gems/2.6.0/gems/forwardable-1.3.1/lib/forwardable/version.rb:3: warning: already initialized constant Forwardable::VERSION
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:116: warning: previous definition of VERSION was here
/Library/Ruby/Gems/2.6.0/gems/forwardable-1.3.1/lib/forwardable/version.rb:4: warning: already initialized constant Forwardable::FORWARDABLE_VERSION
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:117: warning: previous definition of FORWARDABLE_VERSION was here
HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c32b1b6839bb623442dfd5f901b84c421753317f
Core tap last commit: 37 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.zjTBMiJzP2/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

**`brew doctor` output**

brew doctor
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
/Library/Ruby/Gems/2.6.0/gems/forwardable-1.3.1/lib/forwardable/version.rb:3: warning: already initialized constant Forwardable::VERSION
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:116: warning: previous definition of VERSION was here
/Library/Ruby/Gems/2.6.0/gems/forwardable-1.3.1/lib/forwardable/version.rb:4: warning: already initialized constant Forwardable::FORWARDABLE_VERSION
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:117: warning: previous definition of FORWARDABLE_VERSION was here
Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

run 'brew upgrade'

**What happened (include all command output)?**

I am getting these new errors pertaining to 'ffi' package and I am not sure what caused it. 

**What did you expect to happen?**

I expect that it would not have these warnings.  I tried to run 'gem pristine ffi --version 1.13.1' but it did not help.  I do see that my system version of ruby (2.6) is older than the ruby I installed using brew (see below).

ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**Step-by-step reproduction instructions (by running `brew` commands)**

see gist.

**Comment by gpkirk** [comment]
Gist: https://gist.github.com/gpkirk/3f68dc8540e325f0f4e12fec86313a8b

**Comment by dixius99** [comment]
Started getting the same today, but for msgpack.

```
Ignoring msgpack-1.3.1 because its extensions are not built. Try: gem pristine msgpack --version 1.3.1
```

**Comment by Bo98** [comment]
This can be fixed by uninstalling those gems from your system. I'm looking into the feasibility of `brew` ignoring those gems however, since it's not the first time user-installed gems has caused problems.

To be clear: they are warnings, not errors, but I can see that they are indeed annoying.

**Comment by MikeMcQuaid** [comment]
> To be clear: they are warnings, not errors, but I can see that they are indeed annoying.

Closing given this.

**Comment by gpkirk** [comment]
That worked great!  Thanks!

Sincerely,

Geoff Kirk
geoffkirk@gmail.com
1244 Williston Drive
Lawrenceville, GA  30044
mobile ~ 678-772-5658
