### ISSUE TITLE
BrewTestBot GPG signing

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#10672]
**Provide a detailed description of the proposed feature**

We should have @BrewTestBot (i.e. anywhere we author commits as @BrewTestBot) sign their commits using the same GPG key (which we can keep in 1Password and use as a GitHub Actions secret).

We should not expose these secrets in any PRs running on a fork (but none of these can autocommit anyway).

**What is the motivation for the feature?**

Be able to turn on "require signed commits" for pushing to Homebrew/brew and Homebrew/homebrew-core.

**How will the feature be relevant to at least 90% of Homebrew users?**

Increase the security of Homebrew.

**What alternatives to the feature have been considered?**

Not doing this.

**Comment by Bo98** [comment]
Sounds like this might also affect `brew pr-publish` and `brew dispatch-build-bottle` since they perform commits within GitHub Actions on behalf of the user, rather than the bot.

**Comment by MikeMcQuaid** [comment]
Yup, in those cases we should be changing them to be signed as the bot (and co-authored by the relevant user for the UI flair).

**Comment by Bo98** [comment]
Yeah "author" and "committer" are distinct so we can make use of that.

**Comment by nandahkrishna** [comment]
I have a setup that seems to work (nandahkrishna/homebrew-testing#1) in personal testing tap, loosely based on [this post](https://joemiller.me/2019/07/signing-releases-with-a-gpg-project-key/). I managed to upload a signed commit to a PR as BrewTestBot – it shows up as unverified because I haven't actually uploaded the key to BrewTestBot's account.

**Comment by MikeMcQuaid** [comment]
Great work @nandahkrishna! Let's talk on Slack about you getting the access you need to finish this off.

**Comment by MikeMcQuaid** [comment]
🚢d! Great work @nandahkrishna 🎉 

> for pushing to Homebrew/brew

This wasn't possible to enable but we don't allow pushing to `master` there so it's an acceptable trade-off.
