### ISSUE TITLE
Cannot brew update anymore

### ISSUE THREAD

**Issue by LogicalKnight** [Homebrew/brew#1067]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Seeing the following error when trying to update brew:

```
Checking out v1.0.0 in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
To checkout master in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git checkout master
fatal: Cannot update paths and switch to branch 'v1.0.0' at the same time.
Did you intend to checkout 'refs/tags/1.0.0' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.0.0
```
Failing since there is no v1.0.0 in homebrew-core (actually, no tags at all!). I updated brew yesterday successfully (including migration to the Homebrew subdirectory).

Shouldn't the Taps be tracking master at all times anyway? brew itself is at v1.0.0.

**Comment by LogicalKnight** [comment]
Ack! Nevermind. I just saw v1.0.1 come down that fixes this. Sorry for the noise.

**Comment by zmwangx** [comment]
Sorry for the trouble.

**Comment by LogicalKnight** [comment]
No problem. But, should this be reopened? I had to manually update to 1.0.1 as brew would not go from 1.0.0 to 1.0.1 automatically.

**Comment by zmwangx** [comment]
I haven't been following this round of issues closely due to work at hand but I think the discussions are mainly happening in the PR that introduced updating to tags: #998.

**Comment by LogicalKnight** [comment]
That's it. Thanks!
