### ISSUE TITLE
'brew update' checking ~/.config/git/attributes when there's no such directory under .config

### ISSUE THREAD

**Issue by shikibu-z** [Homebrew/brew#10687]
**`brew config` output**

```
HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 43bda13a836a3695263d1945e3a1a4906e8f9431
Core tap last commit: 64 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.FrYIqeURXD/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

**`brew doctor` output**
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
```

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Updating Homebrew regularly using 'brew update'.

**What happened (include all command output)?**

I got a .config in my home dir with root ownership for other clt softwares (htop) and these lines pop up when doing 'brew update' 
```
~ ❯ brew update
warning: unable to access '/Users/feketerigo/.config/git/attributes': Permission denied
warning: unable to access '/Users/feketerigo/.config/git/attributes': Permission denied
warning: unable to access '/Users/feketerigo/.config/git/attributes': Permission denied
Already up-to-date.
```
I checked that there's even no such git directory under .config when I did the update.

**What did you expect to happen?**

Brew updated normally without any warnings.

**Step-by-step reproduction instructions (by running `brew` commands)**

1. Put .config under root ownership.
2. Run 'brew update'.

**Comment by Bo98** [comment]
Regular git operation will make this warning - so this isn't a `brew` bug. Having stuff in a user-specific home directory not actually be owned by the user is not really expected behaviour.
