### ISSUE TITLE
brew update, really really slow

### ISSUE THREAD

**Issue by hitzhangjie** [Homebrew/brew#10692]
**`brew config` output**

HOMEBREW_VERSION: 2.5.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: af4143150da32097f751b1538a5b6f6958bb2175
Last commit: 3 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 48f331373d09b153b31ec0d4a815b68d2b36cbbd
Core tap last commit: 3 months ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
http_proxy: http://127.0.0.1:49960
https_proxy: http://127.0.0.1:49960
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1, 1.7.0_80
macOS: 10.15.7-x86_64
CLT: 1103.0.32.59
Xcode: 12.4

**`brew doctor` output**

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Run `brew missing` for more details.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

brew update

**What happened (include all command output)?**

really really really slow, I even cann't judge when it'll start and finish

**What did you expect to happen?**

run faster

**Step-by-step reproduction instructions (by running `brew` commands)**

brew update

**Comment by gromgit** [comment]
> ```
> http_proxy: http://127.0.0.1:49960
> https_proxy: http://127.0.0.1:49960
> ```

What happens if you unset the above environment variables?

**Comment by dawidd6** [comment]
> Core tap last commit: **3 months ago**

No wonder it's slow. We get many commits daily into core tap, so I think it's ought to be slow to pull all those after a few months.

**Comment by XuehaiPan** [comment]
Change the git repo remote to a mirror in China ([TUNA](https://mirrors.tuna.tsinghua.edu.cn/), [USTC](http://mirrors.ustc.edu.cn/), [Aliyun](https://developer.aliyun.com/mirror/), etc.).
For example, run the following command in terminal:
```bash
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
echo 'export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"' >> ~/.zshrc
git -C "$(brew --repo)" remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
git -C "$(brew --repo homebrew/core)" remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
brew update-reset && brew update
```

**Comment by MikeMcQuaid** [comment]
@XuehaiPan Use `HOMEBREW_CORE_GIT_REMOTE` and `HOMEBREW_BREW_GIT_REMOTE` instead.

**Comment by hitzhangjie** [comment]
git -C "$(brew repo)" remote set-url https://mirrors.tencent.com/homebrew/brew.git

Now it finishes faster.

Thank you all.
