### ISSUE TITLE
Unable to use brew

### ISSUE THREAD

**Issue by eMdOS** [Homebrew/brew#1070]
If I run:

`brew update`

I'm getting:

`-bash: brew: command not found`

Then, if I run:

`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

I'm getting:

```
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
The current contents of /usr/local are bin Cellar etc Frameworks Homebrew include lib opt sbin share var
```

So, then, if I try to uninstall brew in order to reinstall it:

`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"`

I'm getting:

`Failed to locate Homebrew!`

So... what I supposed to do?

**Comment by alswl** [comment]
It was in `vv0.60.0` version, git hash `f2c2f85`, there is no `bin`, and was modified in 10 month ago.

**Comment by alswl** [comment]
Fix with `cd /usr/local/Homebrew; git checkout master`,

DO NOT `brew update` now!

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by eMdOS** [comment]
I did it, but nothing there solved my problem.

**Comment by MikeMcQuaid** [comment]
@eMdOS Yes but we need the information it instructs you to provide to help you. I'll reopen this when you read it and provide it.

**Comment by miomao656** [comment]
i have the same issue, running 10.11.6 osx, i cant do the troubleshooting because `-bash: brew: command not found`

**Comment by alswl** [comment]
Now `brew udpate` works well, the git hash is `817bc2746e594761911edd78f743a640f089494f`

**Comment by MikeMcQuaid** [comment]
@miomao656 https://github.com/homebrew/install#uninstall-homebrew

**Comment by miomao656** [comment]
i get this message when trying to uninstall `Failed to locate Homebrew!`

**Comment by MikeMcQuaid** [comment]
@miomao656 You'll need to delete your files manually or run `ln -sf /usr/local/Homebrew/bin/brew /usr/local/bin/brew` which may fix your installation.

**Comment by miomao656** [comment]
tnx this command line worked :)

**Comment by dionellcardona** [comment]
I have this issue, how to fix it? please help me out, Thanks! 

dyld: lazy symbol binding failed: Symbol not found: ___strlcpy_chk
 Referenced from: /usr/local/bin/git
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___strlcpy_chk
  Referenced from: /usr/local/bin/git
  Expected in: /usr/lib/libSystem.B.dylib
