### ISSUE TITLE
Unable to install packages with brew

### ISSUE THREAD

**Issue by rudranshj** [Homebrew/brew#10709]
**`brew config` output**

HOMEBREW_VERSION: 3.0.2-56-g485f73a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 485f73a32eab3e95986bb5f10786645ef071b161
Last commit: 34 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/brew
Core tap HEAD: 485f73a32eab3e95986bb5f10786645ef071b161
Core tap last commit: 34 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4

**`brew doctor` output**

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://github.com/Homebrew/brew

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/rudransh/anaconda3/bin/icu-config
  /Users/rudransh/anaconda3/bin/krb5-config
  /Users/rudransh/anaconda3/bin/freetype-config
  /Users/rudransh/anaconda3/bin/xslt-config
  /Users/rudransh/anaconda3/bin/libpng16-config
  /Users/rudransh/anaconda3/bin/python3.7-config
  /Users/rudransh/anaconda3/bin/libpng-config
  /Users/rudransh/anaconda3/bin/xml2-config
  /Users/rudransh/anaconda3/bin/python3.7m-config
  /Users/rudransh/anaconda3/bin/python3-config
  /Users/rudransh/anaconda3/bin/curl-config
  /Users/rudransh/anaconda3/bin/ncursesw6-config
  /Users/rudransh/anaconda3/bin/pcre-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8-config

****

- [ ] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

I want to install gcc. I tried:
brew install gcc

**What happened (include all command output)?**

Updating Homebrew...
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "gcc".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**What did you expect to happen?**

gcc getting installed!
I have tried so many things looking up at internet, but nothing worked! 

**Step-by-step reproduction instructions (by running `brew` commands)**

brew install gcc

**Comment by nandahkrishna** [comment]
> You can solve this by setting the origin remote:
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

Please do this.

**Comment by rudranshj** [comment]
I have done this:
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
It ran without any error

Now on running:
brew install gcc
I get this:
zsh: command not found: brew

Should I run it in some specific directory?

**Comment by gromgit** [comment]
> zsh: command not found: brew

What's the output of the following:
```
type -p brew
echo $PATH
```

Once you resolve the "command not found" issue, you'll also have to `brew update-reset /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` before trying to install GCC again.

**Comment by rudranshj** [comment]
These are the outputs:
type -p brew
brew not found

echo $PATH
/Users/rudransh/anaconda3/bin:/Users/rudransh/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

**Comment by gromgit** [comment]
So how exactly did you manage to run `brew config` in your original message?

**Comment by gromgit** [comment]
Just in case, what's the output of `git -C /usr/local/Homebrew remote -v`?

**Comment by rudranshj** [comment]
I was able to run `brew config` before running `git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core`

`git -C /usr/local/Homebrew remote -v` gives this:
origin	https://github.com/Homebrew/homebrew-core (fetch)
origin	https://github.com/Homebrew/homebrew-core (push)

**Comment by gromgit** [comment]
That's the wrong remote. Your original setup already had the correct remote set up, and `brew doctor` did not ask you to change it.

Now you'll have to:
```
git -C /usr/local/Homebrew remote set-url origin https://github.com/Homebrew/brew
```
Then `brew update-reset` to pull the correct contents, and you should be ready to brew.

**Comment by gromgit** [comment]
Actually, before you do that, what's the output of `cat /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/config`?

**Comment by rudranshj** [comment]
after `git -C /usr/local/Homebrew remote set-url origin https://github.com/Homebrew/brew`
`brew install gcc` still gives:
command not found: brew

and `cat /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/config` shows:
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
	autocrlf = false
[remote "origin"]
	url = https://github.com/Homebrew/homebrew-core
	fetch = +refs/heads/*:refs/remotes/origin/*

**Comment by gromgit** [comment]
> after `git -C /usr/local/Homebrew remote set-url origin https://github.com/Homebrew/brew` ,
> `brew install gcc` still gives:
> command not found: brew

You missed the second part:

> Then `brew update-reset` to pull the correct contents, and you should be ready to brew.

**Comment by rudranshj** [comment]
Yeah I'm sorry I actually ran this : `brew update-reset` and got this:
zsh: command not found: brew

**Comment by Bo98** [comment]
`git -C /usr/local/Homebrew reset --hard origin/master` might work.

**Comment by gromgit** [comment]
Yeah, slipped my mind that there would be a chicken-n-egg problem here, in that `brew` itself can't be relied on when `/usr/local/Homebrew` is b0rked. I blame my dinner :beer: . :grinning: 

@rudranshj , looks like you'll have to do what @Bo98 indicated, as follows:
```
git -C /usr/local/Homebrew fetch --force --tags origin
git -C /usr/local/Homebrew reset --hard origin/master
brew config
brew doctor
```
If `brew doctor` doesn't throw any warnings, _then_ do a `brew update-reset` just to be sure the core repos are correctly replicated, then try `brew install gcc` again.

**Comment by rudranshj** [comment]
I did the steps above, however brew doctor threw few warnings 
Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://github.com/Homebrew/brew

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/rudransh/anaconda3/bin/icu-config
  /Users/rudransh/anaconda3/bin/krb5-config
  /Users/rudransh/anaconda3/bin/freetype-config
  /Users/rudransh/anaconda3/bin/xslt-config
  /Users/rudransh/anaconda3/bin/libpng16-config
  /Users/rudransh/anaconda3/bin/python3.7-config
  /Users/rudransh/anaconda3/bin/libpng-config
  /Users/rudransh/anaconda3/bin/xml2-config
  /Users/rudransh/anaconda3/bin/python3.7m-config
  /Users/rudransh/anaconda3/bin/python3-config
  /Users/rudransh/anaconda3/bin/curl-config
  /Users/rudransh/anaconda3/bin/ncursesw6-config
  /Users/rudransh/anaconda3/bin/pcre-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8-config

**Comment by Bo98** [comment]
I think this might work for you:

```
rm -rf /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
brew tap homebrew/core
```

If you don't mind: it would be useful if, before you do the above, you archived your currently broken `/usr/local/Homebrew` and send me a copy (email is on my profile, if you prefer that). You're not the first person I've seen with the issue and it will be beneficial if we can find a way to detect the problem and give a better `brew doctor` message on how to fix it.

**Comment by rudranshj** [comment]
Thanks a lot. Finally it worked!
I'm sorry I couldn't archive `/usr/local/Homebrew`

**Comment by Bo98** [comment]
That's fine. Glad you got it working!
