### ISSUE TITLE
Doesn't work with Xcode tools

### ISSUE THREAD

**Issue by FraserEmbrey** [Homebrew/brew#10714]
**`brew config` output**

HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 01949e88a82778628802068eb2e0377d47ca9afe
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--appdir=/Users/frsr/Applications/", "--fontdir=/Library/Fonts/"]
HOMEBREW_EDITOR: /usr/local/bin/vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

I wanted to use Xcode command line tools since these contain more tools than the ones installed with `xcode-select --install`.

**What happened (include all command output)?**

With the right path set and the tools working generally, brew still complains about needing to install with `xcode-select --install`.

Type `brew upgrade`:

```
==> Upgrading 1 outdated package:
python@3.9 3.9.2 -> 3.9.2_1
==> Upgrading python@3.9 3.9.2 -> 3.9.2_1
Error: python@3.9: the bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install

You can try to install from source with:
  brew install --build-from-source python@3.9
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

**What did you expect to happen?**

Upgrade to just work.

**Step-by-step reproduction instructions (by running `brew` commands)**

brew update
brew upgrade

**Comment by Bo98** [comment]
> I wanted to use Xcode command line tools since these contain more tools than the ones installed with `xcode-select --install`.

The reason we need the Command Line Tools rather than just Xcode.app is for a few reasons:

* The CLT contains more SDKs than Xcode - Xcode may contain SDKs newer than your OS while the CLT always has a compatible SDK. Having a matching SDK is very important for some formulae.
* The CLT is in a fixed location `/Library/Developer/CommandLineTools` while Xcode is not. This matters as some formulae (including Python) bake in paths into files at compile-time - if they pointed to Xcode then it will only work for people who have Xcode installed in the same place.
