### ISSUE TITLE
Apple Silicon M1 Big Sur zprofile Repeated eval Entry

### ISSUE THREAD

**Issue by daBee** [Homebrew/brew#10716]
**`brew config` output**

HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a2a59b2ee70045121e141efad2c7520230aabcc3
Core tap last commit: 15 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: bbedit
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Living my life

**What happened (include all command output)?**

I found multiple eval entries in my ~/.zprofile:

eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)

I'm not sure when they are duplicated/individually inserted.  Maybe upon reboot.  I haven't tested.  

**What did you expect to happen?**

Single entry was inserted upon `rbenv` install.  Also not expected to find many.  

**Step-by-step reproduction instructions (by running `brew` commands)**

n/a

**Comment by carlocab** [comment]
Just delete all the extra ones. If more keep showing up, then something in your setup is putting them there, and it isn't (or, at least, shouldn't be) `brew`.

**Comment by gromgit** [comment]
Sounds like you may have done the same thing as https://github.com/Homebrew/discussions/discussions/951#discussioncomment-411446. See that discussion for the solution.

**Comment by daBee** [comment]
@gromgit Thanks for that.  Turns out it's coming from the login script.

**Comment by daBee** [comment]
Turns out it was in `.zprofile` itself.
