### ISSUE TITLE
sshfs.c:15:10: fatal error: 'fuse_lowlevel.h' file not found

### ISSUE THREAD

**Issue by wangliguang517** [Homebrew/brew#10721]
**`brew config` output**

when brew install datawire/blackbird/telepresence

sshfs.c:15:10: fatal error: 'fuse_lowlevel.h' file not found
#include <fuse_lowlevel.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [sshfs-sshfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

**`brew doctor` output**

sshfs.c:15:10: fatal error: 'fuse_lowlevel.h' file not found
#include <fuse_lowlevel.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [sshfs-sshfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

sshfs.c:15:10: fatal error: 'fuse_lowlevel.h' file not found
#include <fuse_lowlevel.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [sshfs-sshfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

**What happened (include all command output)?**

sshfs.c:15:10: fatal error: 'fuse_lowlevel.h' file not found
#include <fuse_lowlevel.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [sshfs-sshfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

**What did you expect to happen?**

sshfs.c:15:10: fatal error: 'fuse_lowlevel.h' file not found
#include <fuse_lowlevel.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [sshfs-sshfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

**Step-by-step reproduction instructions (by running `brew` commands)**

sshfs.c:15:10: fatal error: 'fuse_lowlevel.h' file not found
#include <fuse_lowlevel.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [sshfs-sshfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

**Comment by jonchang** [comment]
> Do not report this issue to Homebrew/brew or Homebrew/core!

Please report this to whomever runs datawire/blackbird.
