### ISSUE TITLE
brew install falls back to source build for unbottled dependents

### ISSUE THREAD

**Issue by dtrodrigues** [Homebrew/brew#10729]
**`brew config` output**

$ brew config
HOMEBREW_VERSION: 3.0.2-104-g4d88d10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d88d100499d5ccf389e9725ef7f20de410e8b02
Last commit: 87 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 466697a76b4dfddf9314b2ca791a5c733c797087
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false

**`brew doctor` output**

$ brew doctor
Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Install kubectx on Apple Silicon

**What happened (include all command output)?**

$ HOMEBREW_DEVELOPER= brew install kubectx
==> Cloning https://github.com/kubernetes/kubernetes.git
Updating /Users/dustin/Library/Caches/Homebrew/kubernetes-cli--git
==> Checking out tag v1.20.4
HEAD is now at e87da0bd Release commit for Kubernetes v1.20.4
HEAD is now at e87da0bd Release commit for Kubernetes v1.20.4
==> Downloading https://github.com/ahmetb/kubectx/archive/v0.9.3.tar.gz
==> Downloading from https://codeload.github.com/ahmetb/kubectx/tar.gz/v0.9.3
######################################################################## 100.0%
==> Installing dependencies for kubectx: kubernetes-cli
==> Installing kubectx dependency: kubernetes-cli
==> make WHAT=cmd/kubectl

$ HOMEBREW_DEVELOPER= brew install kubernetes-cli
Error: kubernetes-cli: no bottle available!
You can try to install from source with:
  brew install --build-from-source kubernetes-cli
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

**What did you expect to happen?**

I expected `brew install kubectx` to fail to install because it had an unbottled dependency of `kubernetes-cli` instead of trying to build the dependency from source. When directly trying to install `kuberntes-cli`, it refuses to install or build from source as expected.

**Step-by-step reproduction instructions (by running `brew` commands)**

`brew install kubectx`. Should be able to reproduce on Intel by removing the appropriate bottle line from `kubernetes-cli`.

**Comment by MikeMcQuaid** [comment]
@dtrodrigues Good catch. Marking this "help wanted".

**Comment by MikeMcQuaid** [comment]
@dtrodrigues I can't see how this is failing based on https://github.com/Homebrew/brew/blob/61427d6682c0079ca3ab093adec32432fa8692e2/Library/Homebrew/formula_installer.rb#L230-L253. Can you try to add some debugging there to figure out what's not working as expected?

**Comment by Bo98** [comment]
> `elsif !installed_as_dependency?`

> ```
> # don't want to complain about no bottle available if doing an 
> # upgrade/reinstall/dependency install
> ```

**Comment by MikeMcQuaid** [comment]
Thanks @Bo98. In my head this was a `pour_bottle_check_unsatisfied_reason` case but it's not. Opened https://github.com/Homebrew/brew/pull/10788 to address this.
