### ISSUE TITLE
"Error: This formula is not in a tap!" when running brew bump-formula-pr on a formula that is in a tap

### ISSUE THREAD

**Issue by micahellison** [Homebrew/brew#10733]
**`brew config` output**

HOMEBREW_VERSION: 2.7.6-11-g5b2f8a5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5b2f8a5a7307b58843eedfb2886a80964b937b30
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1fe981399a12641c22ac4860928e762c1d61236c
Core tap last commit: 4 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 11.0 build 1103
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 1103.0.32.62
Xcode: 12.4

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

We run `brew bump-formula-pr` in our CI. Without any changes to our brew process, it started failing on [Feb 20](https://github.com/jrnl-org/jrnl/runs/1943191432?check_suite_focus=true) (the last working run was [Jan 23](https://github.com/jrnl-org/jrnl/runs/1755410996?check_suite_focus=true)) with the error message "Error: This formula is not a tap!"

**What happened (include all command output)?**

```
Error: This formula is not in a tap!
Warning: Attempt 1 failed. Reason: Child_process exited with error code 1
git config --replace-all homebrew.devcmdrun true
Error: This formula is not in a tap!
Warning: Attempt 2 failed. Reason: Child_process exited with error code 1
git config --replace-all homebrew.devcmdrun true
Error: This formula is not in a tap!
Warning: Attempt 3 failed. Reason: Child_process exited with error code 1
git config --replace-all homebrew.devcmdrun true
Error: This formula is not in a tap!
Warning: Attempt 4 failed. Reason: Child_process exited with error code 1
git config --replace-all homebrew.devcmdrun true
Error: This formula is not in a tap!
Warning: Attempt 5 failed. Reason: Child_process exited with error code 1
git config --replace-all homebrew.devcmdrun true
Error: This formula is not in a tap!
```

**What did you expect to happen?**

I expect to be able to run `brew bump-formula-pr` on a local repo to update the formula file for processing (opening a PR or making a commit).

**Step-by-step reproduction instructions (by running `brew` commands)**

```
brew bump-formula-pr "Formula/${FORMULA_NAME}.rb" --url (pypi url here) --sha256 (sha goes here) --version=$PYPI_VERSION --no-audit --write --commit --force --verbose
```
We've gotten the same result in our CI ([output](https://github.com/jrnl-org/jrnl/runs/1943191432?check_suite_focus=true)) and on a local machine.

**Comment by Rylan12** [comment]
When you run the `actions/checkout@v2` action, you're just checking out the repo to the current working directory, right? This doesn't really "tap" the repository. Even though the formula file exists in a tap, it's not one that's actually tapped by the repo.

There are a few ways you can fix this. The best is to actually tap the repo by running `brew tap jrnl-org/prerelease` if necessary (`homebrew/core` should already be tapped if Homebrew is installed). Another option would be to checkout the repo to `/usr/local/Homebrew/Library/Taps/jrnl-org/homebrew-prerelease` instead of the working directory (again, `homebrew/core` should already be in the right location). Lastly, if needed, you could write a custom script to do the updates for you that doesn't require having a formula in a tap.

To be honest, the `bump-formula-pr` command could probably run in instances like this (i.e. not truly in a "tapped-tap" but in a tap repository elsewhere in the system). I wouldn't be opposed to this (without looking at the code to make sure there's nothing that would be broken). Not sure if other maintainers would agree or not.

**Comment by MikeMcQuaid** [comment]
> To be honest, the `bump-formula-pr` command could probably run in instances like this (i.e. not truly in a "tapped-tap" but in a tap repository elsewhere in the system). I wouldn't be opposed to this (without looking at the code to make sure there's nothing that would be broken). Not sure if other maintainers would agree or not.

I think it's worth symlinking to the correct location in this case. Our `brew tap-new` will do that for you.

**Comment by micahellison** [comment]
Thanks for looking into this and explaining the alternatives.

> To be honest, the `bump-formula-pr` command could probably run in instances like this (i.e. not truly in a "tapped-tap" but in a tap repository elsewhere in the system). I wouldn't be opposed to this (without looking at the code to make sure there's nothing that would be broken). Not sure if other maintainers would agree or not.

This is actually how it worked until around a month ago. We were putting out successful releases using this method. Is this a bug, or was it never supposed to work?

**Comment by Rylan12** [comment]
Yeah, there was a change made in https://github.com/Homebrew/brew/pull/10251 to require this. The use case you're talking about was never really "officially" supported, I think, so while not really a "bug" it wasn't what `bump-formula-pr` was designed for.

> I think it's worth symlinking to the correct location in this case. Our `brew tap-new` will do that for you.

@MikeMcQuaid does `brew tap-new` do that? I can't figure out how.

You could definitely symlink. Without testing them, here's what I think you'd need to do to modify your workflow to work.

Modify the [`Determine type of release`](https://github.com/jrnl-org/jrnl/blob/5a44385a542075269daf8a8bcdf06043bb992b63/.github/workflows/release.yaml#L131-L154) item to set the `REPO_OWNER` variable as well.

Put this after the [`Checkout homebrew repo` item](https://github.com/jrnl-org/jrnl/blob/5a44385a542075269daf8a8bcdf06043bb992b63/.github/workflows/release.yaml#L156-L160):

```yml
- name: Symlink repo into Homebrew's tap directory
  run: |
    mkdir -p "$(brew --repository)/Library/Taps/${REPO_NAME}"
    ln -s "$(pwd)" "$(brew --repository)/Library/Taps/${FORMULA_REPO}"
```

And then replace the start of the actual [`bump-formula-pr` command](https://github.com/jrnl-org/jrnl/blob/5a44385a542075269daf8a8bcdf06043bb992b63/.github/workflows/release.yaml#L205) with:

```yml
brew bump-formula-pr "${FORMULA_REPO}/${FORMULA_NAME}"
```

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid does `brew tap-new` do that? I can't figure out how.

I more mean the actions that `brew tap-new` will generate for you will do all this. https://github.com/Homebrew/actions/tree/master/setup-homebrew is what I'd recommend using specifically instead of actions/checkout.
