### ISSUE TITLE
Can't install hadolint

### ISSUE THREAD

**Issue by pzelnip** [Homebrew/brew#10744]
**`brew config` output**

HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3327087e98798eb70b4d3e590628f12d04870f89
Core tap last commit: 79 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Install Hadolint.

**What happened (include all command output)?**

 λ brew install hadolint
Error: hadolint: no bottle available!
You can try to install from source with:
  brew install --build-from-source hadolint
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

**What did you expect to happen?**

It to install Hadolint

**Step-by-step reproduction instructions (by running `brew` commands)**

`brew install hadolint`

**Comment by pzelnip** [comment]
Hadolint is a listed formula on the brew website: https://formulae.brew.sh/formula/hadolint and I have installed it successfully on other machines in the past via brew.

**Comment by carlocab** [comment]
`hadolint` needs `ghc` to build, but `ghc` is not yet compatible with ARM. (And it may be a while before they support ARM.)

If you need `hadolint`, you'll need to install it using a Rosetta installation of `brew`.

**Comment by pzelnip** [comment]
Gotcha, thanks.
