### ISSUE TITLE
unknown command switch

### ISSUE THREAD

**Issue by Bluelich** [Homebrew/brew#10748]
**`brew config` output**

HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 81c64f29d6371340885e5f0d0c39cd307f97e568
Core tap last commit: 73 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2-x86_64
CLT: 11.0.33.8
Xcode: 12.4

**`brew doctor` output**

Your system is ready to brew.

****

- [x] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

brew switch cocapods 1.9.3

**What happened (include all command output)?**

unknown command switch

**What did you expect to happen?**

"switch"  command works fine.

**Step-by-step reproduction instructions (by running `brew` commands)**

brew switch cocapods 1.9.3.

**Comment by jonchang** [comment]
This was deprecated 3 months ago. Use `brew extract` in your own tap instead. https://brew.sh/2020/12/01/homebrew-2.6.0/
