### ISSUE TITLE
Consider creating a homebrew/xcode tap

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#1075]
Just as we've done for `X11` and `TeX`, it may make sense to put formulae that have a hard `Xcode.app` dependency in their own tap.

Of the 3,604 formulae in core, there are 49 with a `depends_on xcode`:

- aescrypt-packetizer
- appledoc
- blueutil
- carthage
- choose-gui
- chrome-cli
- chuck
- contacts
- corelocationcli
- dark-mode
- dshb
- duck
- fmdiff
- graphviz
- imagesnap
- ios-class-guard
- ios-deploy
- irrlicht
- launch
- libmxml
- macosvpn
- macvim
- mas
- mit-scheme
- mogenerator
- mplayershell
- natalie
- objc-codegenutils
- pcap_dnsproxy
- phantomjs
- pinentry-mac
- planck
- platypus
- qt5
- rem
- rswift
- sourcekitten
- swift
- swiftgen
- swiftlint
- switchaudio-osx
- taylor
- terminal-notifier
- unar
- watch-sim
- webarchiver
- wry
- xcproj
- xctool

All of the above call `xcodebuild` except these 20

- aescrypt-packetizer
- carthage
- chuck
- contacts
- dshb
- duck
- libmxml
- macvim
- mit-scheme
- natalie
- phantomjs
- pinentry-mac
- planck
- qt5
- sourcekitten
- swift
- swiftgen
- swiftlint
- taylor
- watch-sim

which may in particular be candidates for being tweaked to no longer need Xcode.

Some of the formulae that do call `xcodebuild` may to a lesser extent also be candidates for such tweaking.

**Comment by ilovezfs** [comment]
Reverse dependencies that would be affected, assuming that the Xcode requirement cannot be eliminated for their dependency, are

graphvis:
- bokken
- eralchemy
- fobis
- ford
- gammaray
- gprof2dot
- json-fortran
- makefile2graph
- plantuml
- simgrid
- xdot

phantomjs:
- asciinema2gif
- casperjs

unar:
- ievms

qt5:
- codequery
- dspdfviewer
- gammaray
- opencsg
- pushpin
- pyqt5
- qbs
- qcachegrind
- qjackctl
- qscintilla2
- sqliteman
- zurl

plus any qt reverse dependencies as they are transitioned to qt5:
- automoc4
- binwalk
- bzr-explorer
- coin
- cuty_capt
- djview4
- ezlupdate
- frescobaldi
- git-cola
- gnuradio
- gpsbabel
- libechonest
- liblastfm
- libqglviewer
- puddletag
- pyqt
- pyside-tools
- pyside
- qbzr
- qca
- qjson
- quazip
- qwt
- qwtpolar
- qxmpp
- rcssserver
- shiboken
- sqliteman
- treeline
- valkyrie
- weboob

**Comment by MikeMcQuaid** [comment]
Another thing that may help some of these: depending on our `swift` formula rather than Xcode for some swift stuff.

**Comment by ilovezfs** [comment]
Would a `:swift` requirement make sense, able to be satisfied by `Xcode.app` or our `swift` formula?

**Comment by MikeMcQuaid** [comment]
@ilovezfs Yep 👍

**Comment by MikeMcQuaid** [comment]
Although, I'm an idiot because actually Swift is provided by the CLT...

**Comment by ilovezfs** [comment]
>I'm an idiot

Well, now we know that's not true.

>because actually Swift is provided by the CLT...

maybe it wasn't originally? somehow that memory got there! hehe

**Comment by DomT4** [comment]
Gotta be honest, I'm pretty 😢 about the prospect of moving anything more to a tap that isn't the boneyard. At this point I'm prepared to call the vast majority of Homebrew organisation non-core taps a failed project, especially around getting communities interested in maintaining them & keeping them up-to-date that way.

Taps are vastly unloved & I think we're genuinely better boneyarding things we no longer want to maintain than chucking them in a tap with a vague promise that maybe it won't be more-or-less abandoned fairly imminently.

**Comment by chdiza** [comment]
> it may make sense to put formulae that have a hard Xcode.app dependency in their own tap.

I'm curious as to what would be gained by doing this.

As to what would be lost by doing this, I can think of at least two things:  the more times the user has to tap something, the more annoying it is for the user.  And the more times the user has to type "sometapname/someformulaname" rather than "someformulaname", the more annoying it is for the user.  There should be some kind of significant gain to offset this.

(This wouldn't affect me personally, since everything on that list that I use I've either already made my own custom local formula for, or don't use HB to manage.)

**Comment by ilovezfs** [comment]
Yup, the CLT alone is insufficient to prop up what rightfully belongs in core.

**Comment by MikeMcQuaid** [comment]
> Gotta be honest, I'm pretty 😢 about the prospect of moving anything more to a tap that isn't the boneyard. At this point I'm prepared to call the vast majority of Homebrew organisation non-core taps a failed project, especially around getting communities interested in maintaining them & keeping them up-to-date that way.
> 
> Taps are vastly unloved & I think we're genuinely better boneyarding things we no longer want to maintain than chucking them in a tap with a vague promise that maybe it won't be more-or-less abandoned fairly imminently.

That's pretty fair. Unless it's a single maintainers pet project (e.g. @dunn and homebrew/emacs) or an existing community tap we've brought in (e.g. homebrew/php, homebrew/science) the taps that are basically "not good enough for core but we feel bad saying no" are fairly dismal and we should consider shutting them down and moving stuff into core or the boneyard.
