### ISSUE TITLE
Follow manually installed packages and automatically installed dependencies separately

### ISSUE THREAD

**Issue by tonimelisma** [Homebrew/brew#10754]
### Provide a detailed description of the proposed feature

Have a command similar to `brew leaves` which shows all the packages manually installed by the user themselves, without various automatically installed dependencies. `brew leaves` shows only packages which aren't dependencies of anything, even if the user installed them manually (e.g. if Python 3.9 is installed manually by the user, it's often also a dependency and doesn't show up there).

### What is the motivation for the feature?

Standard functionality in other package managers (e.g. apt has `apt-mark showmanual`, `apt-mark markauto`)

### How will the feature be relevant to at least 90% of Homebrew users?

They can easily differentiate between the 80% of installed packages which are automatic dependencies and packages they installed themselves and want to keep

### What alternatives to the feature have been considered?

Manually keeping a text file of what packages I've installed

**Comment by carlocab** [comment]
`brew bundle dump` will generate a `Brewfile` listing all the formulae (and casks) you've installed on request.

**Comment by tonimelisma** [comment]
That's good, but not quite a fit. To be specific about the feature request, three commands would be required:
- `brew showmanual` - shows all currently installed packages which have been set to manually installed
- `brew markmanual` - marks an automatically installed dependency as manually installed
- `brew markauto` - marks a manually installed packages as an automatically installed dependency, and uninstalls if no other package depends on it

**Comment by carlocab** [comment]
>shows all currently installed packages which have been set to manually installed

`brew bundle dump`

>marks an automatically installed dependency as manually installed

Add it to your `Brewfile`

>marks a manually installed packages as an automatically installed dependency, and uninstalls if no other package depends on it

make sure your `Brewfile` is correctly specified, then run `brew bundle cleanup --force`

**Comment by tonimelisma** [comment]
Yeah, I'm sure you understand that's not quite proper ergonomics for the use case

**Comment by MikeMcQuaid** [comment]
> * `brew markmanual` - marks an automatically installed dependency as manually installed

`brew install` already does this if the package is already installed.

> * `brew markauto` - marks a manually installed packages as an automatically installed dependency, and uninstalls if no other package depends on it

This requires manually editing the `INSTALL_RECEIPT.json`. I'm not sure I've seen enough demand to warrant adding a new command for it (but an external command [https://docs.brew.sh/External-Commands] could be added for this).

**Comment by MikeMcQuaid** [comment]
> * `brew showmanual` - shows all currently installed packages which have been set to manually installed

`brew leaves --installed-on-request` and `brew leaves --not-installed-as-dependency` could be added as flags which use these entries for identification. Marking this as the "help wanted" here.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Similar funcctionality [was suggested](https://github.com/Homebrew/brew/pull/1881#issuecomment-274260312) as complementary to #1881's '`brew orphaned`' at the time.  (That command never got implemented even though '`brew autoremove` did.  Some of the code used to implement the latter should help.)

**Comment by tonimelisma** [comment]
Wow! This is fantastic! You actually implemented my feature request! I do hope you guys understand that Homebrew is probably the most valuable open source tool I use on my macOS and the work you guys do is awesome. I put in a little monetary sponsorship via Github. Thank you so much for Homebrew, you guys rock!! ❤️ 

@MikeMcQuaid @RandomDSdevel @Rylan12 @cnnrmnn

**Comment by MikeMcQuaid** [comment]
Better still @tonimelisma: a community member (@cnnrmnn) implemented it rather than one of the maintainers. He rocks, you rock, everyone rocks! 🎉 🎸 👨🏻‍🎤 👩🏻‍🎤
