### ISSUE TITLE
pr-pull broken on taps: Error: No matching workflow run found for these criteria!

### ISSUE THREAD

**Issue by aconchillo** [Homebrew/brew#10755]
### `brew config` output

N/A

### `brew doctor` output

N/A

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

This is an issue with a tap homebrew-guile (https://github.com/aconchillo/homebrew-guile). When setting tha label as `pr-pull` I would expect the built bottles to be uploaded and the PR to be merged as before.

### What happened (include all command output)?

https://github.com/aconchillo/homebrew-guile/pull/22/checks?check_run_id=2006876069

I'm getting this error (see link above):

```
Error: No matching workflow run found for these criteria!
==> Downloading bottles for workflow: tests.yml
  Commit SHA:   c875bc79dc9ddceb0362d0d916a1fadcf7d9b6ab
  Branch ref:   guile-redis_2.1.0
  Pull request: 22
  Workflow:     tests.yml
```

### What did you expect to happen?

I would expect the bottles to be uploaded and the PR to be merged as before.

### Step-by-step reproduction instructions (by running `brew` commands)

I don't know how to reproduce this issue locally.

**Comment by carlocab** [comment]
This is a problem with the Actions API:

>We are having problems searching workflow runs. The results may not be complete.

See, for example, https://github.com/aconchillo/homebrew-guile/actions?query=is%3Afailure.

I've reported this to GitHub as ticket 1041548.

**Comment by carlocab** [comment]
GitHub Support response:

>Thanks for confirming, this would then be related to the status incident from earlier today -- the Actions folks are reindexing runs now and that should complete later today.

**Comment by aconchillo** [comment]
Thank you @carlocab .
