### ISSUE TITLE
brew audit should complain about installation of (some) empty files

### ISSUE THREAD

**Issue by mitchblank** [Homebrew/brew#10768]
### Provide a detailed description of the proposed feature

Ideally it should be uncommon for empty files to be installed, but it seems to happen.  There are some common exceptions (`__init__.py`) but in many other places it may be an indication that a formula did not build as successfully as thought.

Just banning them outright might be hard.  I ran:
```
$ find $(brew --prefix) -type f -size 0 | grep -v __init__
```
...and had more than 1000 hits.

Obviously many of these must be fine, but also many are probably actually mistakes.  Maybe we could start by flagging empty files in `bin`/`libexec`/`man`/`share/doc` and/or files with certain extensions that aren't likely to make sense if they're zero length (`.html`?)

### What is the motivation for the feature?

Recently https://github.com/Homebrew/homebrew-core/issues/72328 got filed where an empty man page was installed by the `cloc` formula in homebrew-core.  The underlying bug was straightforward but maybe `brew audit` could have caught it earlier.

Some zero-length examples on my machine that look obviously wrong:
```
/usr/local/Cellar/neomutt/20210205/share/doc/neomutt/manual.txt
/usr/local/Cellar/mutt/2.0.5/share/doc/mutt/manual.txt
/usr/local/Cellar/sysbench/1.0.20/share/doc/sysbench/manual.html
```
It seems particularly common for `ChangeLog`/`AUTHORS`/etc files that get installed.  I haven't checked how many are empty in the source package or whether they are being installed in some incorrect way:
```
$ find $(brew --prefix) -type f -size 0 \( -name ChangeLog -o -name NEWS -o -name AUTHORS -o -name NOTES \) -ls | wc -l
      34
```

### How will the feature be relevant to at least 90% of Homebrew users?

More formula bugs caught before bottling

### What alternatives to the feature have been considered?

It's just an idea for discussion.

**Comment by MikeMcQuaid** [comment]
Good catch. I think there's an argument for finding file with certain names or extensions that are empty e.g. `ChangeLog`, `AUTHORS`, `*.txt`, etc. We could/should either audit for them and/or ensure they are automatically cleaned up after installation.

**Comment by kthchew** [comment]
I think I can try my hand at this issue. 

I looked through some of the existing code for audits. Would I be correct to put a check of this type in [`formula_cellar_checks.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_cellar_checks.rb)?

**Comment by MikeMcQuaid** [comment]
Passing on this as we had to revert https://github.com/Homebrew/brew/pull/10851. It's at least improved as we're no longer installing empty metafiles.
