### ISSUE TITLE
brew link openjdk: Warning: Refusing to link macOS provided/shadowed software: openjdk

### ISSUE THREAD

**Issue by milosivanovic** [Homebrew/brew#10785]
### `brew config` output

HOMEBREW_VERSION: 3.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee52b19179d056f3dd2fdf9c52214d3d51dbb9d9
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a4cb2a1d655db92899bf4ceee5800e41c36fed4c
Core tap last commit: 46 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.JPvznkhiMg/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
Rosetta 2: false

### `brew doctor` output

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

### 

- [] The `brew doctor` above contains no "Warning" lines.
- (There are warning lines, but they shouldn't matter here.)

### What were you trying to do (and why)?

I have openjdk@15 and openjdk@11 installed. It seems I already had openjdk@15 linked because when I ran `java -version` it told me it was 15. When I needed to switch to openjdk@11, I ran `brew link openjdk@11` and it said it created a bunch of symlinks. I would have thought it would tell me that I need to overwrite links, but it never asked me that, it just went and created the openjdk@11 links. I ran `hash -r` to reload the bash cache paths to make openjdk@11 work otherwise despite the new links it still pointed to openjdk@15. With that out of the way, I wasn't able to ever re-link openjdk@15 when I was done with openjdk@11.

### What happened (include all command output)?

```
milos@air:~$ brew link openjdk@15
Warning: Refusing to link macOS provided/shadowed software: openjdk

milos@air:~$ brew link openjdk
Warning: Refusing to link macOS provided/shadowed software: openjdk
```

### What did you expect to happen?

Overwrite the openjdk@11 symlinks and java `java -version` should match expectations from openjdk@15.

### Step-by-step reproduction instructions (by running `brew` commands)

```
milos@air:~$ brew install openjdk
==> Downloading https://homebrew.bintray.com/bottles/openjdk-15.0.2.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/063189cdbad2c9ef5ab5e7dc34cea1d2fe68a5405b3728eb87765d6c1b9a3a64?response-content-disposition=attachment%3Bfilename%3D%22openjdk-15.0.2.arm64_big_sur.bottle.tar.gz%22&Policy=eyJTd
######################################################################## 100.0%
==> Pouring openjdk-15.0.2.arm64_big_sur.bottle.tar.gz
==> Caveats
For the system Java wrappers to find this JDK, symlink it with
  sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
This is a beta version of openjdk for Apple Silicon
(openjdk 16 preview).

openjdk is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides similar software and installing this software in
parallel can cause all kinds of trouble.

If you need to have openjdk first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"' >> /Users/milos/.bash_profile

For compilers to find openjdk you may need to set:
  export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

==> Summary
🍺  /opt/homebrew/Cellar/openjdk/15.0.2: 613 files, 305.5MB
Removing: /Users/milos/Library/Caches/Homebrew/openjdk--15.0.1.arm64_big_sur.bottle.1.tar.gz... (184.1MB)

milos@air:~$ java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)

milos@air:~$ hash -r

milos@air:~$ java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)

milos@air:~$ which java
/opt/homebrew/opt/openjdk/bin/java

milos@air:~$ brew install openjdk@11
==> Downloading https://homebrew.bintray.com/bottles/openjdk%4011-11.0.9.arm64_big_sur.bottle.tar.gz
Already downloaded: /Users/milos/Library/Caches/Homebrew/downloads/b56e93e39e3ce73734c239e8402097d7e6a785de61ea1d5a4c9894d8199812d4--openjdk@11-11.0.9.arm64_big_sur.bottle.tar.gz
==> Pouring openjdk@11-11.0.9.arm64_big_sur.bottle.tar.gz
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/openjdk@11/11.0.9/libexec/openjdk.jdk/Contents/MacOS/libjli.dylib:
/opt/homebrew/Cellar/openjdk@11/11.0.9/libexec/openjdk.jdk/Contents/MacOS/libjli.dylib: replacing existing signature
/opt/homebrew/Cellar/openjdk@11/11.0.9/libexec/openjdk.jdk/Contents/MacOS/libjli.dylib: resource fork, Finder information, or similar detritus not allowed

==> Caveats
For the system Java wrappers to find this JDK, symlink it with
  sudo ln -sfn /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk

openjdk@11 is keg-only, which means it was not symlinked into /opt/homebrew,
because this is an alternate version of another formula.

If you need to have openjdk@11 first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"' >> /Users/milos/.bash_profile

For compilers to find openjdk@11 you may need to set:
  export CPPFLAGS="-I/opt/homebrew/opt/openjdk@11/include"

==> Summary
🍺  /opt/homebrew/Cellar/openjdk@11/11.0.9: 643 files, 272.4MB

milos@air:~$ java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)

milos@air:~$ hash -r

milos@air:~$ java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)

milos@air:~$ brew link openjdk@11
Linking /opt/homebrew/Cellar/openjdk@11/11.0.9... 40 symlinks created.

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"' >> /Users/milos/.bash_profile

milos@air:~$ java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)

milos@air:~$ hash -r

milos@air:~$ java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11)
OpenJDK 64-Bit Server VM (build 11.0.9+11, mixed mode)

milos@air:~$ brew link openjdk
Warning: Refusing to link macOS provided/shadowed software: openjdk
If you need to have openjdk first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"' >> /Users/milos/.bash_profile

For compilers to find openjdk you may need to set:
  export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
```

**Comment by Bo98** [comment]
> It seems I already had openjdk@15 linked because when I ran `java -version`

No it was never linked. It looks like you just had `/opt/homebrew/opt/openjdk/bin` in your PATH.

`brew unlink openjdk@11` will unlink OpenJDK 11.

I do understand the confusion from the difference of behaviour of blocking `brew link` though.

**Comment by milosivanovic** [comment]
I'm confused, is this not a bug then, given it was closed? With Python I can do `brew link --overwrite python@3.8` to make it my default and then `brew link --overwrite python` to go back to the latest. Why would I not be able to do this with openjdk?

Also a separate question, every time a newer version of Python is updated (e.g. 3.9) it re-links against that version so I have to overwrite again. Is there any better concept of "default" that doesn't constantly get reset with each upgrade of a newer version of that package?
