### ISSUE TITLE
Support PyPI Cacheing Proxy

### ISSUE THREAD

**Issue by adam-moss** [Homebrew/brew#10782]
### Provide a detailed description of the proposed feature

This request removes environment filtering for

* PIP_CERT
* PIP_INDEX_URL

so that python based formula, such as `awscli` can be installed when the end-user device is behind a cacheing proxy.

Some discussion of this particular issue was undertaken in https://github.com/Homebrew/discussions/discussions/863.

### What is the motivation for the feature?

The environment in which I'm using `brew` insists on having TLS-inspection in place at this time.  As Homebrew filters out  the majority of environment variables and ignores the users `pip.conf` settings it results in errors.

### How will the feature be relevant to at least 90% of Homebrew users?

In real terms it probably isn't unless PyPi considers implementing rate-limiting in the same way hub.docker.com recently did.

### What alternatives to the feature have been considered?

I have submitted https://github.com/Homebrew/brew/pull/10781 as a starter for 10 on this feature request.  In this change I have made the simplest and smallest edit to achieve the desired outcome. Another alternative I considered was including an option along a similar line to the unsupported `HOMEBREW_NO_ENV_FILTERING`, e.g. `HOMEBREW_USE_PIP_CONFIG` to make this an opt-in feature, and I'd be happy to implement that if that is a preferred approach.

**Comment by MikeMcQuaid** [comment]
Let's discuss in the PR instead.
