### ISSUE TITLE
`brew --prefix` searches casks for matches

### ISSUE THREAD

**Issue by gromgit** [Homebrew/brew#10799]
### `brew config` output

HOMEBREW_VERSION: 3.0.4-50-ga930e2b
ORIGIN: https://github.com/Homebrew/brew
HEAD: a930e2b36235d3c0b15f655752c76fadc35dc3fb
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fa4991b9612780d13c31897df939d4c397519dc1
Core tap last commit: 16 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dual-core 64-bit penryn
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

### `brew doctor` output

Your system is ready to brew.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I was trying out some combinations of `brew --prefix` invocations in support of #10797. Contrary to the man page, it seems that `brew --prefix` _does_ search available casks when deriving its output.

### What happened (include all command output)?

```bash
$ brew --prefix dummy
Error: No available formula with the name "dummy".
# OK...

$ brew --prefix google-chrome
/usr/local/opt/google-chrome
# Wait, what?

$ brew search google-chrome
==> Casks
google-chrome                                                        homebrew/cask-versions/google-chrome-beta                            homebrew/cask-versions/google-chrome-canary                          homebrew/cask-versions/google-chrome-dev
```

### What did you expect to happen?

```bash
$ brew --prefix google-chrome
Error: No available formula with the name "google-chrome".
```

### Step-by-step reproduction instructions (by running `brew` commands)

```bash
brew --prefix google-chrome
```

**Comment by VonUniGE** [comment]
This problem is in brew/Library/Homebrew/prefix.sh:
```local formula_path
  if [ -f "$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-core/${formula}.rb" ]; then
    formula_path="$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-core/${formula}.rb"
  else
    formula_path="$(find "$HOMEBREW_REPOSITORY/Library/Taps" -name "${formula}.rb" -print -quit)"
  fi
  [ -z "$formula_path" ] && return 1

  echo "$HOMEBREW_PREFIX/opt/$formula"```

To check if a formula exists:
```
find "$HOMEBREW_REPOSITORY/Library/Taps" -name "${formula}.rb" 
```
is used.

Running `brew --prefix virtualbox` will thenfind the cask even if there is no formula named virtualbox.

**Comment by VonUniGE** [comment]
There is another problem on line 21. It should be:
```
   formula_path="$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-core/Formula/${formula}.rb" 
```

**Comment by carlocab** [comment]
I guess you could change Line 23 to
```bash
formula_path="$(find "$HOMEBREW_REPOSITORY/Library/Taps" -name "Formula/${formula}.rb" -print -quit)" 
```
This will work for taps that keep their formula files in a directory called `Formula`, but it'll break it for all taps that don't. Otherwise, I suppose we could exclude searching subdirectories called `Casks`.
