### ISSUE TITLE
Stuck at login to Ubuntu 20.10

### ISSUE THREAD

**Issue by aiurovet** [Homebrew/brew#10793]
### `brew config` output

HOMEBREW_VERSION: 3.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee52b19179d056f3dd2fdf9c52214d3d51dbb9d9
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c1b4369de9da439ae45f67941582556370a489ad
Core tap last commit: 2 days ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0.0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.27.0 => /usr/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.8.0-44-generic x86_64 GNU/Linux
OS: Ubuntu 20.10 (groovy)
Host glibc: 2.32
/usr/bin/gcc: 10.2.0
/usr/bin/ruby: 2.7.1
glibc: N/A
gcc@5: N/A
xorg: N/A

### `brew doctor` output

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

The following tools exist at both paths:
  dart2native
  dart

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Just logging into Ubuntu MATE 20.10 (a day before, I successfully installed brew, and eventually shut down the desktop PC).

### What happened (include all command output)?

Firstly, I had an infinite login loop after I enter the password. Later on, was just stuck at the black screen with the small green rectangle at the top left corner of the screen without any further action.

### What did you expect to happen?

Just to login to Ubuntu.

### Step-by-step reproduction instructions (by running `brew` commands)

I googled 'infinite loop Ubuntu login' and found a bit of a good advice to press Ctrl+Alt+F3, then to login to terminal and have a look at ~/.xsession-errors

It showed me an issue, which is obviously related to PATH: mktemp was not found as well as cat, truncate and something else, which I don't remember.

The two of my files (~/.bash_aliases and ~/.bash_profile) have a common line: source /etc/environment (I did that myself to control extra environment variables in a single place).

During Homebrew installation, I added a few lines to that file (/etc/environment):

export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}";

There was one more for PATH, which essentially, was a culprit. Firstly, I thought it could happen because your folders were put in front of the rest PATH, so I converted that to:

export PATH="${PATH}:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin";

That didn't help. Then I removed 'export', but got the same result. The only thing, which worked for me, was appending the list of actual Homebrew directories to the explicit definition of PATH above (yes, it is defined in that file too).

I left the rest of Homebrew environment as is, as that did not impact anything. And obviously, the 'brew' command is found and works as expected.

**Comment by aiurovet** [comment]
Additionally, I wanted to mention, that as far as I understood, I had to remove warning lines from 'brew doctor' and tick the box. In case I misunderstood and had to leave those and not to tick the box, here is the full output of 'brew doctor':

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: /usr/bin occurs before /home/linuxbrew/.linuxbrew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/home/linuxbrew/.linuxbrew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >> /home/ra/.bash_profile

The following tools exist at both paths:
  dart2native
  dart

**Comment by aiurovet** [comment]
I've just realised that you require to put your directories in front of the rest of PATH, so I did that too. All works fine, I'm able to login, and the full output of 'brew doctor' is as follows:

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

**Comment by gromgit** [comment]
> It showed me an issue, which is obviously related to PATH: mktemp was not found as well as cat, truncate and something else, which I don't remember.

It sounds like you made a mistake when changing your `PATH` that effectively broke it. It was to avoid issues like this that `brew shellenv` was introduced, and why the Homebrew installer tells you the following at the end:
```
- Add Homebrew to your PATH in ~/.bash_profile:
    echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> ~/.bash_profile
    eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
```

**Comment by aiurovet** [comment]
Interesting, it helped, although the output of `/home/linuxbrew/.linuxbrew/bin/brew shellenv` is effectively the same as what I've put into the file originally. By the way, getting rid of warnings did not have any impact, as I was able to reproduce the issue after fixing them. Using the command you've suggested, fixed the issue though.

**Comment by gromgit** [comment]
> the output of /home/linuxbrew/.linuxbrew/bin/brew shellenv is effectively the same as what I've put into the file originally

Pretty much, but with two major differences:
1. No typo-related errors. 
2. It gets updated as Homebrew evolves over times, so it'll always be right. :crossed_fingers:
