### ISSUE TITLE
Running brew --prefix <cask_name> return misleading information

### ISSUE THREAD

**Issue by VonUniGE** [Homebrew/brew#10797]
### `brew config` output

HOMEBREW_VERSION: 3.0.4-50-ga930e2b
ORIGIN: https://github.com/Homebrew/brew
HEAD: a930e2b36235d3c0b15f655752c76fadc35dc3fb
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3cc6a063d22d8e3c12ed013b71be394881bb56aa
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.eZzOB2k1e3/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.32.21
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

### `brew doctor` output

Your system is ready to brew.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Finding the files installed by a cask.

### What happened (include all command output)?

```
$  brew --prefix docker
/usr/local/opt/docker
```

But /usr/local/opt/docker is not the install location of docker. Same behavior with other casks.

### What did you expect to happen?

Either show the install location(s) or a message such as : "brew --prefix cannot be used with casks".

### Step-by-step reproduction instructions (by running `brew` commands)

`brew --prefix docker`

**Comment by jonchang** [comment]
`brew --prefix` only works for formulae, not casks, per the documentation: https://docs.brew.sh/Manpage#--prefix---unbrewed---installed-formula-

**Comment by VonUniGE** [comment]
@jonchang Thank you, I've also read the documentation. The issue is about the fact that `brew --prefix` gives bogus information when used with a cask instead of saying that it doesn't work with casks.

**Comment by carlocab** [comment]
You didn't use it on a cask though. When you did `brew --prefix docker`, `brew` assumes you meant the formula (because `--prefix` doesn't apply to casks).

**Comment by VonUniGE** [comment]
@carlocab Yes, you are right. I understand the logic, but this formula/cask dichotomy is sometimes a bit confusing.

**Comment by VonUniGE** [comment]
@carlocab Still something unclear:

```
$ brew --prefix docker
/usr/local/opt/docker

$ brew --prefix dockerx
Error: No available formula with the name "dockerx".
/usr/local/opt/docker
```
If docker is a cask and not a formula why running `brew --prefix docker` doesn't output:
```Error: No available formula with the name "docker".``` ?

**Comment by carlocab** [comment]
This is by design:

```
❯ brew help --prefix
Usage: brew --prefix [--unbrewed] [--installed] [formula ...]

Display Homebrew's install path. Default:

  - macOS Intel: /usr/local
  - macOS ARM: /opt/homebrew
  - Linux: /home/linuxbrew/.linuxbrew

If formula is provided, display the location where formula is or would be
installed.
```

You could probably pass the `--installed` flag to try to emulate some (but perhaps not all) of the functionality you're looking for:
```
      --installed                  Outputs nothing and returns a failing
                                   status code if formula is not installed.
```

**Comment by gromgit** [comment]
> If docker is a cask and not a formula why running `brew --prefix docker` doesn't output:
> `Error: No available formula with the name "docker".` ?

Because it's _both_:
```bash
==> Formulae
docker                           docker-credential-helper-ecr     docker-machine-driver-vmware     docker-squash
docker-clean                     docker-gen                       docker-machine-driver-vultr      docker-swarm
docker-completion                docker-ls                        docker-machine-driver-xhyve      docker2aci
docker-compose                   docker-machine                   docker-machine-nfs               dockerize
docker-compose-completion        docker-machine-completion        docker-machine-parallels         lazydocker
docker-credential-helper         docker-machine-driver-hyperkit   docker-slim
==> Casks
docker                                      docker-toolbox                              homebrew/cask-versions/docker-edge
```
In any case, #10800 fixed the side issue of `brew --prefix` mistakenly finding casks, so now `brew --prefix <cask>` will error out for all casks:
```bash
$ brew --prefix docker
/usr/local/opt/docker
# Correct, because there's a `docker` formula

$ brew --prefix docker-toolbox
Error: No available formula with the name "docker-toolbox".
```
