### ISSUE TITLE
Overly-zealous tap guarding.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#108]
When we shipped https://github.com/Homebrew/brew/commit/fad235d8e82ae57b2004429a0297f313aafa3186 was it intentional to end up blocking remote overrides?

```
~> brew tap homebrew/fuse
Error: Tap homebrew/fuse remote mismatch.
git@github.com:Homebrew/homebrew-fuse.git != https://github.com/Homebrew/homebrew-fuse
```

```
[url "git@github.com:Homebrew/"]
	# Use SSH for Homebrew instead of https://
	insteadOf = https://github.com/Homebrew/
```

It feels a little heavy-handed and unnecessary, given that the URL still matches GitHub + the Homebrew organisation.

**Comment by mikemcquaid** [comment]
> It feels a little heavy-handed and unnecessary, given that the URL still matches GitHub + the Homebrew organisation.

Agreed 👍

**Comment by mikemcquaid** [comment]
CC @ilovezfs for thoughts

**Comment by ilovezfs** [comment]
As documented in the manpage (https://github.com/Homebrew/brew/blob/master/share/man/man1/brew.1#L415), yes it was intentional. This was a change requested by @apjanke

**Comment by mikemcquaid** [comment]
@ilovezfs @apjanke Can you elaborate a bit more or point to context anywhere? I'm not sure what my feelings are yet. If nothing else we should guard this with `HOMEBREW_DEVELOPER` I think so people can still use SSH auth if they want to.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/legacy-homebrew/pull/50639

**Comment by mikemcquaid** [comment]
Cheers!

**Comment by apjanke** [comment]
Yeah, my intention was to make sure that `brew tap foo <some-url>` made sure that tap `foo` was pointing to the right place, so it didn't blindly succeed but leave a tap pointing to some other repo source, preventing stuff like this from succeeding silently.

```
brew tap bob/burgers http://git.bobs-burgers.com/bob/recipes.git
...
brew tap bob/burgers http://mcdonalds.com/git/ronald/recipes.git
```

I didn't know about `git` remote overrides at the time, and the idea wasn't to prevent changing the transport mechanism; just to make sure that the target origin repo was as requested in the most recent command.

Maybe we could munge it to treat `https://github.com/` and `git@github.com:` as equivalent?

**Comment by mikemcquaid** [comment]
> Maybe we could munge it to treat https://github.com/ and git@github.com: as equivalent?

That'd be good. Similarly `git://github.com/`

**Comment by xu-cheng** [comment]
The quickest fix is:
```diff
- raise TapRemoteMismatchError.new(name, @remote, requested_remote) unless remote == requested_remote
  raise TapAlreadyTappedError, name unless full_clone
  raise TapAlreadyUnshallowError, name unless shallow?
+ raise TapRemoteMismatchError.new(name, @remote, requested_remote) unless remote == requested_remote

**Comment by UniqMartin** [comment]
I get why this sequence should produce an error (in an effort not to ignore the second URL):

```
brew tap some/tap <original-url> 
brew tap some/tap <different-rul>
```

But it feels like we've made `brew tap` complain for this case:

```
brew tap some/tap <original-url>
brew tap some/tap
```

In this second case there's no second URL that we might be ignoring, so complaining that the original URL is not the one we believe it should be doesn't seem to make sense (to me). We should be trusting that the URL stored in this tap's Git config is just fine.

I think the URL rewriting happening via `url.*.insteadOf` isn't even relevant to this discussion. I suspect that the tap in question actually has a `git@github.com:Homebrew/homebrew-fuse.git` in its `.git/config`, because we're directly querying the config which doesn't involve applying transformations implied by `url.*.insteadOf`, unless this has changed in a more recent version of Git. Maybe to make things clearer:

```
$ git -C $(brew --repo homebrew/fuse) remote -v
origin https://github.com/Homebrew/homebrew-fuse.git (fetch)
origin https://github.com/Homebrew/homebrew-fuse.git (push)
$ brew tap-info homebrew/fusehomebrew/fuse: unpinned, 27 formulae
/opt/brewery/tests/Library/Taps/homebrew/homebrew-fuse (81 files, 117.5K)
From: github-ro://Homebrew/homebrew-fuse.git
```

(Notice the different URLs being reported, the former output takes into account `url.*.insteadOf`.)

**Comment by DomT4** [comment]
> I suspect that the tap in question actually has a git@github.com:Homebrew/homebrew-fuse.git in its .git/config

It does, yeah 👍. Before I slapped it on globally I overwrote the remotes of various taps to use SSH via the standard `git remote xyz` command, which produced this:
```
[branch "master"]
[remote "origin"]
	url = git@github.com:Homebrew/homebrew-fuse.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[remote "Dom"]
	url = git@github.com:DomT4/homebrew-fuse.git
	fetch = +refs/heads/*:refs/remotes/Dom/*
```

The `tap` command doesn't care about the taps I haven't fiddled the remotes on, even with the global override.

I still consider the change unnecessarily breaking here; as long as the URL equals GitHub + the Homebrew organisation I don't think we should be policing method of transport generally. I don't have strong feelings on how it should be fixed, but treating the various potential URLs as equally valid seems fine to me.

**Comment by DomT4** [comment]
Thanks @xu-cheng!
