### ISSUE TITLE
update os 10.12 and xcode8 don't used brew update and brew doctor

### ISSUE THREAD

**Issue by CoderBOBO** [Homebrew/brew#1080]
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
How to solve it？

**Comment by CoderBOBO** [comment]
don't update homebrew 1.0.0

**Comment by DomT4** [comment]
See https://github.com/Homebrew/homebrew-core/issues/5113#issuecomment-248894481.
