### ISSUE TITLE
`brew reinstall neovim` is broken

### ISSUE THREAD

**Issue by glitchy** [Homebrew/brew#10819]
### `brew config` output

❯ brew config
HOMEBREW_VERSION: 3.0.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8b677c0ddd5f96b5521c1b353a9ca07dfe57b80e
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0d5ae88abf46a18896a1fd0b481a6cfe2e28e0ff
Core tap last commit: 25 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4

### `brew doctor` output

❯ brew doctor
Your system is ready to brew.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I am trying to run `brew reinstall neovim` in order to reinstall neovim to the latest commit on `--HEAD` (my first install was `brew install --HEAD neovim`). I do this every day in order to stay on the latest commit of the neovim nightly version.

### What happened (include all command output)?

The following error is written to stdout:

```
❯ brew reinstall neovim
Error: neovim: no bottle available!
You can try to install from source with:
  brew install --build-from-source neovim
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

I have never seen this before in the year I've been doing this.

### What did you expect to happen?

Because my install was `brew install --HEAD neovim` I expected `brew reinstall neovim` to reinstall neovim to the latest `--HEAD` on the neovim nightly.

### Step-by-step reproduction instructions (by running `brew` commands)
```
❯ brew install --HEAD neovim
❯ brew reinstall neovim
```

**Comment by MikeMcQuaid** [comment]
> Please note building from source is unsupported. You will encounter build
> failures with some formulae. If you experience any issues please create pull
> requests instead of asking for help on Homebrew's GitHub, Twitter or any other
> official channels.

**Comment by rafi** [comment]
@glitchy 
```sh
brew uninstall neovim
brew install --build-from-source --HEAD neovim
```

If you don't uninstall first, you'll get a weird message saying
> Warning: neovim HEAD-c29494b_1 is already installed and up-to-date.
> To reinstall HEAD_1, run:
>  brew reinstall neovim
