### ISSUE TITLE
Node 15.11 being installed during treesitter install fails on M1 Mac

### ISSUE THREAD

**Issue by TC72** [Homebrew/brew#10818]
### `brew config` output

HOMEBREW_VERSION: 3.0.4-74-g8b677c0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8b677c0ddd5f96b5521c1b353a9ca07dfe57b80e
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6d37897a2fae25bf3ce7ca012be597618805f7d6
Core tap last commit: 58 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false

### `brew doctor` output

Your system is ready to brew.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I was trying to install an older version of treesitter.
brew install tree-sitter@0.18.3

### What happened (include all command output)?

It failed, when I checked Console, Crash Reports I could see an issue with node.
During the treesitter install brew installed node-15.11.0.arm64_big_sur.bottle.tar.gz
If I try to run that version of node directly with :
```/opt/homebrew/Cellar/node/15.11.0/bin/node -v```
I get the message
```zsh: killed     /opt/homebrew/Cellar/node/15.11.0/bin/node -v```

### What did you expect to happen?

I expected treesitter to be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

brew uninstall tree-sitter --ignore-dependencies
brew extract --version=0.18.3 tree-sitter homebrew/cask
brew install tree-sitter@0.18.3

**Comment by carlocab** [comment]
Try
```
brew update
brew reinstall icu4c
brew install node
```
then install your version of `tree-sitter`.

**Comment by TC72** [comment]
Thanks, that fixed the node issue. But still no luck with tree-sitter, I'll take the conversation back to the neovim section.

**Comment by carlocab** [comment]
Great. Closing this as resolved.
