### ISSUE TITLE
Expand documentation around --quiet

### ISSUE THREAD

**Issue by blakegearin** [Homebrew/brew#10820]
### Provide a detailed description of the proposed feature

While experimenting with `--quiet` on `install` and `uninstall` commands I noticed including it made little to no difference. I read the documentation which didn't provide much detail "Make some output more quiet." I think it's reasonable to expect what categories of output to expect (e.g. warnings, errors, current action, status, success)

Installs
``` bash
$ brew install --quiet --cask libreoffice
==> Installing Cask libreoffice
==> Moving App 'LibreOffice.app' to '/Applications/LibreOffice.app'
==> Linking Binary 'regmerge' to '/usr/local/bin/regmerge'
==> Linking Binary 'regview' to '/usr/local/bin/regview'
==> Linking Binary 'senddoc' to '/usr/local/bin/senddoc'
==> Linking Binary 'ui-previewer' to '/usr/local/bin/ui-previewer'
==> Linking Binary 'uno' to '/usr/local/bin/uno'
==> Linking Binary 'unopkg' to '/usr/local/bin/unopkg'
==> Linking Binary 'uri-encode' to '/usr/local/bin/uri-encode'
==> Linking Binary 'xpdfimport' to '/usr/local/bin/xpdfimport'
==> Linking Binary 'soffice.wrapper.sh' to '/usr/local/bin/soffice'
==> Linking Binary 'unoinfo' to '/usr/local/bin/unoinfo'
==> Linking Binary 'gengal' to '/usr/local/bin/gengal'
🍺  libreoffice was successfully installed!

$ brew install --cask libreoffice
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 1 cask.

==> Downloading https://download.documentfoundation.org/libreoffice/stable/7.1.1/mac/x86_64/LibreOffice_7.1.1_MacOS_
Already downloaded: /Users/blake/Library/Caches/Homebrew/downloads/9944adfc78471d72cb29f14bad4dc55406670b0afb0ff265be60db157e54ba5b--LibreOffice_7.1.1_MacOS_x86-64.dmg
==> Installing Cask libreoffice
==> Moving App 'LibreOffice.app' to '/Applications/LibreOffice.app'
==> Linking Binary 'regmerge' to '/usr/local/bin/regmerge'
==> Linking Binary 'regview' to '/usr/local/bin/regview'
==> Linking Binary 'senddoc' to '/usr/local/bin/senddoc'
==> Linking Binary 'ui-previewer' to '/usr/local/bin/ui-previewer'
==> Linking Binary 'uno' to '/usr/local/bin/uno'
==> Linking Binary 'unopkg' to '/usr/local/bin/unopkg'
==> Linking Binary 'uri-encode' to '/usr/local/bin/uri-encode'
==> Linking Binary 'xpdfimport' to '/usr/local/bin/xpdfimport'
==> Linking Binary 'soffice.wrapper.sh' to '/usr/local/bin/soffice'
==> Linking Binary 'unoinfo' to '/usr/local/bin/unoinfo'
==> Linking Binary 'gengal' to '/usr/local/bin/gengal'
🍺  libreoffice was successfully installed!
```

Uninstalls
``` sh
$ brew uninstall --cask libreoffice
==> Uninstalling Cask libreoffice
==> Backing App 'LibreOffice.app' up to '/usr/local/Caskroom/libreoffice/7.1.1/LibreOffice.app'
==> Removing App '/Applications/LibreOffice.app'
==> Unlinking Binary '/usr/local/bin/regmerge'
==> Unlinking Binary '/usr/local/bin/regview'
==> Unlinking Binary '/usr/local/bin/senddoc'
==> Unlinking Binary '/usr/local/bin/ui-previewer'
==> Unlinking Binary '/usr/local/bin/uno'
==> Unlinking Binary '/usr/local/bin/unopkg'
==> Unlinking Binary '/usr/local/bin/uri-encode'
==> Unlinking Binary '/usr/local/bin/xpdfimport'
==> Unlinking Binary '/usr/local/bin/soffice'
==> Unlinking Binary '/usr/local/bin/unoinfo'
==> Unlinking Binary '/usr/local/bin/gengal'
==> Purging files for version 7.1.1 of Cask libreoffice

$ brew uninstall --quiet --cask libreoffice
==> Uninstalling Cask libreoffice
==> Backing App 'LibreOffice.app' up to '/usr/local/Caskroom/libreoffice/7.1.1/LibreOffice.app'
==> Removing App '/Applications/LibreOffice.app'
==> Unlinking Binary '/usr/local/bin/regmerge'
==> Unlinking Binary '/usr/local/bin/regview'
==> Unlinking Binary '/usr/local/bin/senddoc'
==> Unlinking Binary '/usr/local/bin/ui-previewer'
==> Unlinking Binary '/usr/local/bin/uno'
==> Unlinking Binary '/usr/local/bin/unopkg'
==> Unlinking Binary '/usr/local/bin/uri-encode'
==> Unlinking Binary '/usr/local/bin/xpdfimport'
==> Unlinking Binary '/usr/local/bin/soffice'
==> Unlinking Binary '/usr/local/bin/unoinfo'
==> Unlinking Binary '/usr/local/bin/gengal'
==> Purging files for version 7.1.1 of Cask libreoffice
```

### What is the motivation for the feature?

To expand awareness of what `--quiet` is and in what situations it provides value

Questions users might have:
- What's the criteria for deciding what gets output when `--quiet` is included?
- Do any other options cancel out or otherwise impact `--quiet`?
- Besides trial and error, how can a user know that including `--quiet` will reduce the amount of output?

### How will the feature be relevant to at least 90% of Homebrew users?

Documentation is essential for users to understand how to use Homebrew appropriately and with confidence

### What alternatives to the feature have been considered?

I personally think it would be beneficial to introduce a quieter option (e.g. `-Q`) which is offered by other programs (e.g. `-qq` in `unzip`) or some call this silent (e.g. `-s` in `curl`). This type of option would output nothing if everything about the command functions normally/as expected

**Comment by MikeMcQuaid** [comment]
> While experimenting with `--quiet` on `install` and `uninstall` commands I noticed including it made little to no difference. I read the documentation which didn't provide much detail "Make some output more quiet." I think it's reasonable to expect what categories of output to expect (e.g. warnings, errors, current action, status, success)

I'm afraid we can't commit to providing a consistent behaviour here in the nearish term. We simply don't have a way with the current messaging infrastructure to restrict this.

**Comment by blakegearin** [comment]
> I'm afraid we can't commit to providing a consistent behaviour here in the nearish term. We simply don't have a way with the current messaging infrastructure to restrict this.

Fair enough, I realized when submitting that this might not be immediately addressable considering the size & scope.

What are your thoughts on a quieter/silent option? Perhaps too niche?

**Comment by MikeMcQuaid** [comment]
> What are your thoughts on a quieter/silent option? Perhaps too niche?

I think `--quiet` or `--verbose` being more consistent would make sense instead. We'd need to come up with a consistent policy for what `--quiet` should do, though, and apply it universally before changing the docs.
