### ISSUE TITLE
Repeated issues due to tools crashing with code signing issues

### ISSUE THREAD

**Issue by TC72** [Homebrew/brew#10823]
### `brew config` output

HOMEBREW_VERSION: 3.0.4-74-g8b677c0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8b677c0ddd5f96b5521c1b353a9ca07dfe57b80e
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5262bcb7c52daf6137d9e94a4f775476af2aa74b
Core tap last commit: 21 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false

### `brew doctor` output

Your system is ready to brew.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I've been trying to reinstall an old version of tree-sitter but keep hitting problems with tools used during the install.
Since updating MacOS to 11.2.2 and homebrew to 3.0.4 I have been having lots of issues which seem to be linked to code signing. I did have to install command line tools again.
I was having issues with node crashing and now it's python. Console Crash Reports keeps mentioning signing.
Node is now fixed after following instructions to `brew reinstall icu4c`
Is there something wrong with my xcode install which is causing the issues?

### What happened (include all command output)?

This is the kind of output I see in Crash Reports:
```
Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000000102afc000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2
```

### What did you expect to happen?

I expect homebrew to be able to use python and node for installations that require them to be used.

### Step-by-step reproduction instructions (by running `brew` commands)

```
brew uninstall tree-sitter --ignore-dependencies
brew extract --version=0.18.3 tree-sitter homebrew/cask
brew install tree-sitter@0.18.3
```

**Comment by MikeMcQuaid** [comment]
> I've been trying to reinstall an old version of tree-sitter but keep hitting problems with tools used during the install.

We don't support this. Can you reproduce this on a current version of a homebrew/core formula?

**Comment by TC72** [comment]
I included tree-sitter in my report as that's what I'm doing but I'm getting failures on so many things all linked to code signing.
I think I have a pretty broken setup and not sure how or what I can do to fix it.

I've just followed another guide to use pyenv to install python on my system. Installed pyenv from homebrew, then asked pyenv to install python3.9.1 fails while building. Crash report shows python.exe and once gain, this is in the crash report:

```
Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x00000001052d4000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2
```

**Comment by carlocab** [comment]
There's nowhere near enough information to tell what's going on in the snippet of the crash report you've shared. You'll need to share the complete crash report (put it in a gist, if it's too long).

The `pyenv` problem also seems to have nothing to do with your issues with `tree-sitter`, as the two formulae do not have intersecting dependency graphs.

Short of a more meaningful crash report, I'd try
```
brew update
brew reinstall $(brew deps pyenv) pyenv
```

**Comment by TC72** [comment]
Thanks, that reinstall command gave me a version of pyenv that was able to install python for me.
Still don't understand what I've done to my system to give me so many issues.

**Comment by carlocab** [comment]
Neither do I, because

>There's nowhere near enough information to tell what's going on in the snippet of the crash report you've shared. You'll need to share the complete crash report

My guess is that you somehow installed some formula without CLT/Xcode installed, which meant these formulae were not signed on installation. CLT/Xcode installs are sometimes (often/always?) removed at version upgrades. (I don't know why Apple is doing that.)

**Comment by TC72** [comment]
Thanks, I think you are 100% right. I upgraded my OS yesterday and shit got messed up after that.
I tried to install some stuff to fix my tree-sitter issues and then had to install the command line tools.
Is there a way for me to ask brew to reinstall everything?

I thought using pyenv was a bright idea but brew doctor doesn't agree.

**Comment by carlocab** [comment]
Can we error out instead of trying to pour bottles on ARM without dev tools? Or is that what we're meant to be doing already?

**Comment by Bo98** [comment]
We error out pre-installation already.

**Comment by Bo98** [comment]
To be clear: `codesign` should apparently work without dev tools now as of Big Sur, but there was a correlation between people without dev tools and people with codesigning failures so it was worth a shot.

**Comment by TC72** [comment]
I've gone back through my history and looks like me upgrading brew without command line tools is what screwed my system. You can see the point where I freaked out because brew doctor told me it didn't have git:
```
brew install -s --HEAD neovim
brew update
brew upgrade
brew doctor
xcode-select --install
which brew
brew doctor
git
git
brew install git
brew reinstall git
```

**Comment by Bo98** [comment]
>  for a short-term improvement, considering making it fatal on not-`openjdk` (with an allowlist we can add to if needed)? Could do that immediately, I think.

Possibly yeah. The code is knee deep in relocation code, so I'm not sure what the best approach is: abort immediately, let relocation continue but fail at the end of it, maybe even somehow try and uninstall the broken formula (useful for `git` breakages)?

**Comment by MikeMcQuaid** [comment]
> Possibly yeah. The code is knee deep in relocation code, so I'm not sure what the best approach is: abort immediately, let relocation continue but fail at the end of it, maybe even somehow try and uninstall the broken formula (useful for `git` breakages)?

@Bo98 I'd say bail out as if the installation failed on a `system` in `def install`. `brew install`, `brew upgrade` and `brew reinstall` should all do The Right Thing in that case.

**Comment by Bo98** [comment]
Ah yes, just realised it's done in `pour` so it should work.
