### ISSUE TITLE
Installed but won't run

### ISSUE THREAD

**Issue by ruppke** [Homebrew/brew#10827]
### `brew config` output

-bash: brew: command not found

### `brew doctor` output

-bash: brew: command not found

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

i was trying to install a package

### What happened (include all command output)?

-bash: brew: command not found

### What did you expect to happen?

...

### Step-by-step reproduction instructions (by running `brew` commands)

docker pull ghcr.io/homebrew/ubuntu18.04:latest
ghcr.io/homebrew/ubuntu18.04:latest

**Comment by gromgit** [comment]
Not a Docker expert, but I've never seen Docker images (what you pulled) used without starting a Docker container.

If you're trying to run a new container to experiment with Homebrew, or to test a formula in isolation: `docker run -it homebrew/ubuntu18.04`

If you actually want to _use_ Homebrew on a daily basis, then as the [homepage](https://brew.sh/) recommends: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
