### ISSUE TITLE
Include dependencies when using install --build-from-source 

### ISSUE THREAD

**Issue by bmaupin** [Homebrew/brew#10832]
### Provide a detailed description of the proposed feature

I'm using macOS 10.11 so I have to build all packages from source. I would expect that `brew install --build-from-source` would include dependencies. But it doesn't.

In the man page I see `Dependencies will still be installed from bottles if they are available.`, so this seems to be intended behaviour and why I created this as a feature request and not a bug.

Expected behaviour:

```
$ brew install --build-from-source ffmpeg
...
# ffmpeg installed
```

Actual behaviour:

```
$ brew install --build-from-source ffmpeg
...
Error: nasm: no bottle available!
You can try to install from source with:
  brew install --build-from-source nasm
...
$ brew install --build-from-source nasm
...
$ brew install --build-from-source ffmpeg
...
Error: pkg-config: no bottle available!
You can try to install from source with:
  brew install --build-from-source pkg-config
...
```

### What is the motivation for the feature?

1. Better user experience when installing packages from source
1. I would also imagine that this would match behaviour when not using `--build-from-source`, which I would expect does not require installation of all dependencies manually

### How will the feature be relevant to at least 90% of Homebrew users?

I don't know anything about the demographic breakdown of Homebrew users, but assuming 90% of Homebrew users are not running an unsupported version of macOS, this feature will likely not be relevant to them.

### What alternatives to the feature have been considered?

Another option might be to have some sort of additional parameter, e.g. `--include-dependencies` or `--build-dependencies-from-source` to allow enabling this behaviour explicitly.

Thanks!

**Comment by carlocab** [comment]
The default behaviour is useful for testing formula changes when you're able to install bottles, but an extra flag that builds dependencies from source might also be useful.

Does
```
brew install --only-dependencies --build-from-source ffmpeg
```
help?

**Comment by bmaupin** [comment]
Unfortunately it doesn't; it exhibits the same behaviour and fails at the first missing dependency.

I tried this:

```
for dependency in $(brew deps ffmpeg); do brew install --build-from-source $dependency; done
```

but it fails because some of the dependencies are missing dependencies 😝

**Comment by bmaupin** [comment]
I think I may have figured out the incantation that works:

```
for dependency in $(brew deps --include-build -n ffmpeg); do brew install --build-from-source $dependency; done
```

`-n` seems to order them properly, but only includes install dependencies so it gives me errors by itself. Adding `--include-build` seems to fix that. No errors so far 🤞

I probably would have saved a bunch of time by just downloading the pre-built binaries from https://evermeet.cx/ffmpeg/ but I'd much prefer to get everything from homebrew if possible.

**Comment by carlocab** [comment]
I guess the simplest fix here would be to just avoid the `no bottle available` error on macOS versions that are no longer supported. I'll work on a PR to do that.

**Comment by carlocab** [comment]
Actually, what about
```
brew install --build-from-source $(brew deps --include-build ffmpeg) ffmpeg
```
?

**Comment by bmaupin** [comment]
Amazing, thank you so much!
