### ISSUE TITLE
Casks installed long ago invalidated by intervened deprecations

### ISSUE THREAD

**Issue by giucal** [Homebrew/brew#10833]
### `brew config` output

```
HOMEBREW_VERSION: 3.0.5-14-g5240afb
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5240afbbb5cd1a9a10cb207c5277f076e8a8f52a
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bc374a6f5cb907b576eb36735b344dde7e8128f4
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

### `brew doctor` output

```
Your system is ready to brew.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Reinstall a cask that `depends_on macos: '>= :mountain_lion'`. Lots of apps self-update, so this may happen once in a while (#5640).

In my case:
```
brew reinstall textmate
```

### What happened (include all command output)?

`depends_on` failed because `:mountain_lion` is not a known version anymore.

```
==> Downloading https://github.com/textmate/textmate/releases/download/v2.0.19/TextMate_2.0.19.tbz
Already downloaded: /Users/giucal/Library/Caches/Homebrew/downloads/1212d0bb473a730006dbee528ce71eb49ca32b967fabc03fa4978dfb68f8783f--TextMate_2.0.19.tbz
Error: Cask 'textmate' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :mountain_lion
```

### What did you expect to happen?

```
% brew reinstall textmate
==> Downloading https://github.com/textmate/textmate/releases/download/v2.0.19/TextM
Already downloaded: /Users/giucal/Library/Caches/Homebrew/downloads/1212d0bb473a730006dbee528ce71eb49ca32b967fabc03fa4978dfb68f8783f--TextMate_2.0.19.tbz
==> Installing Cask textmate
==> Moving App 'TextMate.app' to '/Applications/TextMate.app'
==> Linking Binary 'mate' to '/usr/local/bin/mate'
🍺  textmate was successfully installed!
```

### Step-by-step reproduction instructions (by running `brew` commands)

Pick an installed cask, e.g. `foo`, whose depends-on clause refers to a deprecated OS version.
```
brew reinstall foo
```

**Comment by giucal** [comment]
I know that the tip in Homebrew/homebrew-cask#58046 works, but it's a hack. 

I feel version deprecation need not to be an ontological matter. Older versions were supported at some point: letting brew forget about them inevitably introduces regressions.

Why not nominally reinstating old versions in `Mac::Version`?

That would solve the problem with `dsl/depends_on.rb`. The deprecation status of such versions wouldn't be impacted. Indeed, versions from Yosemite to High Sierra are currently declared in there despite being unsupported, and I think it's fine.

Isn't it sufficient to enforce deprecation elsewhere (e.g. in `audit`)?

**Comment by Bo98** [comment]
Yeah this has been a bug for a while and should be looked into.

> Why not nominally reinstating old versions in `Mac::Version`?

I don't think that's the solution. We're able to deal with this fine for formulae - it's cask specific.

**Comment by MikeMcQuaid** [comment]
The solution here is not using the archived Cask file if it's invalid (for any reason) and instead using the file from homebrew-cask.
