### ISSUE TITLE
where package output two same path.

### ISSUE THREAD

**Issue by wejectchen** [Homebrew/brew#10843]
### `brew config` output

```
➜  /opt brew config      
HOMEBREW_VERSION: 3.0.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8b677c0ddd5f96b5521c1b353a9ca07dfe57b80e
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a567617d9592796a0008f3532f38f94798624dd8
Core tap last commit: 14 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.2 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false
```
### `brew doctor` output
```shell
➜  /opt brew doctor
Your system is ready to brew.
```
### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?
```shell
➜ brew install git
➜ ~ where git  
```
### What happened (include all command output)?
```shell
➜  /opt where git  
/opt/homebrew/bin/git
/opt/homebrew/bin/git
/usr/bin/git
```
### What did you expect to happen?
```shell
➜  /opt where git  
/opt/homebrew/bin/git
/usr/bin/git
```
### Step-by-step reproduction instructions (by running `brew` commands)

any package installed from brew,when run where command,it's also output two same path like `/opt/homebrew/bin/*`
is it normal? or how can solve this problem？

**Comment by gromgit** [comment]
What's the output of `echo $PATH`? I'm also certain you'll see `/opt/homebrew/bin` in it _twice_.

**Comment by wejectchen** [comment]
> What's the output of `echo $PATH`? I'm also certain you'll see `/opt/homebrew/bin` in it _twice_.

it's nice, thx.
`echo $PATH`
```shell
➜  ~ echo $PATH
/opt/homebrew/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
there are really tow same `/opt/homebrew/bin` in $PATH,when i delete one of them ,it's normal.

```shell
➜  ~ where git 
/opt/homebrew/bin/git
/usr/bin/git
```

**Comment by carlocab** [comment]
Looks like this is resolved then. You just need to find out why you're adding `/opt/homebrew/bin` to your `PATH` twice and remove the second one. (or first, if you prefer)
