### ISSUE TITLE
CPATH=/opt/homebrew/include when running tests causes compilation issues

### ISSUE THREAD

**Issue by wrobelda** [Homebrew/brew#10841]
### `brew config` output

```
HOMEBREW_VERSION: 3.0.5-18-g433cd83
ORIGIN: https://github.com/Homebrew/brew
HEAD: 433cd83cbc186afbe970289557ceee3f33c7383a
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 58255170a2445dafa0d5d0acd8aa32b32eadc81f
Core tap last commit: 7 hours ago
Core tap branch: kde-kplotting
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.CJPNli5DdI/org.xquartz:0
HOMEBREW_EDITOR: code
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

No issues

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I am working on some additional KDE formulas and many of the example tests included with them fail to compile successfully. The error messages consistently suggest as if it they are caused by an improper c++ standard choice, yet I could not reproduce them using a local copy of the source code and an identical copy of the Formula's testing CMakeLists.txt. After (painstaking) debugging it turns out this is caused by Brew adding the `/opt/homebrew/include` to `CPATH` environment variable. 

I also noticed that there are many more env variables set (CPPFLAGS, LDFLAGS, etc.) implicitly and I don't think that a clean-room approach to testing Formulas post-installation warrants setting up any additional variables on top of what a regular user sees in their shell of choice. Otherwise such tests prove nothing: they may not be reproducible (outside of brew's own env) and can yield false-positive results. 

### What happened (include all command output)?

```
[ 47%] Building CXX object autotests/CMakeFiles/kplotaxistest.dir/kplotaxistest.cpp.o
In file included from /tmp/kde-kplotting-test-20210312-36018-12axo35/examples/testplot_widget.cpp:10:
In file included from /opt/homebrew/opt/qt@5/lib/QtWidgets.framework/Headers/QComboBox:1:
In file included from /opt/homebrew/opt/qt@5/lib/QtWidgets.framework/Headers/qcombobox.h:43:
In file included from /opt/homebrew/include/QtWidgets/qtwidgetsglobal.h:43:
In file included from /opt/homebrew/include/QtGui/qtguiglobal.h:43:
/opt/homebrew/include/QtCore/qglobal.h:667:26: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?
         typename = std::enable_if_t<std::is_arithmetic_v<T> && std::is_arithmetic_v<U> &&
                    ~~~~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:538:63: note: 'enable_if' declared here
template <bool, class _Tp = void> struct _LIBCPP_TEMPLATE_VIS enable_if {};
                                                              ^
In file included from /tmp/kde-kplotting-test-20210312-36018-12axo35/examples/testplot_widget.cpp:10:
In file included from /opt/homebrew/opt/qt@5/lib/QtWidgets.framework/Headers/QComboBox:1:
In file included from /opt/homebrew/opt/qt@5/lib/QtWidgets.framework/Headers/qcombobox.h:43:
In file included from /opt/homebrew/include/QtWidgets/qtwidgetsglobal.h:43:
In file included from /opt/homebrew/include/QtGui/qtguiglobal.h:43:
/opt/homebrew/include/QtCore/qglobal.h:667:43: error: no template named 'is_arithmetic_v' in namespace 'std'; did you mean 'is_arithmetic'?
         typename = std::enable_if_t<std::is_arithmetic_v<T> && std::is_arithmetic_v<U> &&
                                     ~~~~~^
```

### What did you expect to happen?

Compilation should finish without errors.

### Step-by-step reproduction instructions (by running `brew` commands)

Using https://github.com/Homebrew/homebrew-core/pull/73032:
```
brew install kde-kplotting
brew test kde-kplotting
```

**Comment by Bo98** [comment]
That doesn't really make sense that a `CPATH` would change the C++ version used.

Does `depends_on :xcode => :test` help? That changes the SDK used in `CPATH` and is often needed for Qt dependents.

**Comment by MikeMcQuaid** [comment]
Can you reproduce this with any current Homebrew/homebrew-core formulae? If not, this smells a lot like a formula bug.

**Comment by carlocab** [comment]
We do have 16 formulae that do `ENV.delete "CPATH"` somewhere. Half of them are `qt`-related.

**Comment by Bo98** [comment]
And pretty much all of those Qt ones should have `depends_on :xcode => :test` instead. Qt is known to not work well with the CLT SDK.

**Comment by wrobelda** [comment]
> Can you reproduce this with any current Homebrew/homebrew-core formulae? If not, this smells a lot like a formula bug.

@MikeMcQuaid , as I explained:
> yet I could not reproduce them using a local copy of the source code and an identical copy of the Formula's testing CMakeLists.txt.

I can reproduce it by:
- running `brew test kde-kplotting --debug --keep-tmp`
- copying the contents of the `tmp` folder, removed `CMakeCache.txt` and `CMakeFiles`
- running the same cmake commands brew did in a clean shell session
- having those tests compile fine

So this is not a formula bug, so whether I can reproduce it with another formula is IMHO irrelevant here, but if you insist: https://github.com/Homebrew/homebrew-core/commit/394421c25a9f60fe7502a641ed3bb473d013d499

I'd say that having brew applying any particular, implicit, compiler-affecting variables _for the test section of the formula_ is a bug. Tests should be running in an environment that is identical to what developers actually use post-installation of a brew. Otherwise this whole effort of defining those tests is completely futile and those tests running can yield false-positive. Not to mention how this sets your contributors for failure. I don't understand why this part of my bug report was skipped over and this was closed preemptively without addressing these concerns.

> That doesn't really make sense that a CPATH would change the C++ version used.

@Bo98  I didn't mean it did, just saying it looked like it, which is why it was so particularly misleading and pesky, since I kept assuming this had something to do with my testing CMakeLists missing some instructions. 

> We do have 16 formulae that do ENV.delete "CPATH" somewhere. Half of them are qt-related.

@carlocab indeed, and I should have checked the existing `kde-karchive` in the first place because it does exactly that: https://github.com/Homebrew/homebrew-core/commit/394421c25a9f60fe7502a641ed3bb473d013d499. This was added just days ago as part of "qt to qt@5" change, which is even more confusing. But the whole point of this bug report is that the test section should _not_ be setting any `CPATH` or other compiler variables implicitly. I don't have them in my shell, so why apply those hiddenly? How does this not contradict the whole existence of tests? What do those tests prove, then? I feel like I am repeating myself here.

> And pretty much all of those Qt ones should have depends_on :xcode => :test instead. Qt is known to not work well with the CLT SDK, which is used by default.

@Bo98 `vcpkg` can build whole Qt and all other Qt apps out there [with Xcode CLI only](https://github.com/Microsoft/vcpkg#installing-macos-developer-tools). Just sayin'. And, again, my whole point is those should not be needed to build those tests at all if I did not have to set any additional environment variables in my clean shell session to do that. So why would brew "massage" the reality here? Guess what I am saying here is that, __for the test section__:
- no implicit env variables set, unless __explicitly__ requested by the dev.
- if anything, they should be able to use `:cli_sdk => :test` if needed.

**Comment by wrobelda** [comment]
> Can you reproduce this with any current Homebrew/homebrew-core formulae? If not, this smells a lot like a formula bug.

@MikeMcQuaid , as I explained:
> yet I could not reproduce them using a local copy of the source code and an identical copy of the Formula's testing CMakeLists.txt.

I can reproduce it by:
- running `brew test kde-kplotting --debug --keep-tmp`
- copying the contents of the `tmp` folder, removed `CMakeCache.txt` and `CMakeFiles`
- running the same cmake commands brew did in a clean shell session
- having those tests compile fine

So this is not a formula bug, so whether I can reproduce it with another formula is IMHO irrelevant here, but if you insist: https://github.com/Homebrew/homebrew-core/commit/394421c25a9f60fe7502a641ed3bb473d013d499

I'd say that having brew applying any particular, implicit, compiler-affecting variables _for the test section of the formula_ is a bug. Tests should be running in an environment that is identical to what developers actually use post-installation of a brew. Otherwise this whole effort of defining those tests is completely futile and those tests running can yield false-positive. Not to mention how this sets your contributors for failure. I don't understand why this part of my bug report was skipped over and this was closed preemptively without addressing these concerns.

> That doesn't really make sense that a CPATH would change the C++ version used.

@Bo98  I didn't mean it did, just saying it looked like it, which is why it was so particularly misleading and pesky, since I kept assuming this had something to do with my testing CMakeLists missing some instructions. 

> We do have 16 formulae that do ENV.delete "CPATH" somewhere. Half of them are qt-related.

@carlocab indeed, and I should have checked the existing `kde-karchive` in the first place because it does exactly that: https://github.com/Homebrew/homebrew-core/commit/394421c25a9f60fe7502a641ed3bb473d013d499. This was added just days ago as part of "qt to qt@5" change, which is even more confusing. But the whole point of this bug report is that the test section should _not_ be setting any `CPATH` or other compiler variables implicitly. I don't have them in my shell, so why apply those hiddenly? How does this not contradict the whole existence of tests? What do those tests prove, then? I feel like I am repeating myself here.

> And pretty much all of those Qt ones should have depends_on :xcode => :test instead. Qt is known to not work well with the CLT SDK, which is used by default.

@Bo98 `vcpkg` can build whole Qt and all other Qt apps out there [with Xcode CLI only](https://github.com/Microsoft/vcpkg#installing-macos-developer-tools). Just sayin'. And, again, my whole point is those should not be needed to build those tests at all if I did not have to set any additional environment variables in my clean shell session to do that. So why would brew "massage" the reality here? Guess what I am saying here is that, __for the test section__:
- no implicit env variables set, unless __explicitly__ requested by the dev.
- if anything, they should be able to use `:cli_sdk => :test` if needed.

**Comment by MikeMcQuaid** [comment]
> But the whole point of this bug report is that the test section should _not_ be setting any `CPATH` or other compiler variables implicitly.

The test section does and literally always has set some compiler variables.

> * no implicit env variables set, unless **explicitly** requested by the dev.

This would break many tests.

You've got a workaround here: please apply that, thanks.

**Comment by Bo98** [comment]
> `vcpkg` can build whole Qt and all other Qt libs out there with Xcode CLI only.

Feel free to open a PR with the fixes needed to get Qt to work with the CLT - that would be very appreciated.

But until that happens, Qt's `qmake` modules etc will contain baked in paths to the Xcode SDK (this is Qt's build system which does this) and thus the Xcode SDK must also be used by Qt dependents.
