### ISSUE TITLE
`electron-builder` `livecheck` strategy for casks

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/brew#10866]
### Provide a detailed description of the proposed feature

A bunch of Electron apps use [`electron-builder`](https://www.electron.build) appcasts which can be detected with [`find-appcast`](https://github.com/Homebrew/homebrew-cask/blob/master/developer/bin/find-appcast).

Since those `appcasts` are YAML files with a specific pattern, [detecting versions is simple](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/remnote.rb#L10L15):

```ruby
livecheck do
  url "https://s3.amazonaws.com/download.remnote.io/latest-mac.yml"
  strategy :page_match do |page|
    YAML.safe_load(page)["version"]
  end
end
```

These appcasts are somewhat common, which makes them good candidates for a new strategy.

### What is the motivation for the feature?

Making simpler `livecheck`s, which will result in more casks being up-to-date and less maintenance effort.

### How will the feature be relevant to at least 90% of Homebrew users?

User who *make* casks will have an easier time doing so (in these specific cases). Users who *use* casks will benefit indirectly from casks which are easier to maintain.

### What alternatives to the feature have been considered?

Doing it the long (well, medium) way as in the code block above.

**Comment by samford** [comment]
@vitorgalvao Nanda's `ElectronBuilder` strategy is now merged, so you can update related casks to simply use `strategy :electron_builder` and this will work in the same manner as the existing `strategy` blocks.

If you need to modify the version, you can access the `yaml` hash in the strategy block like so:

```ruby
strategy :electron_builder do |yaml|
  yaml["version"]&.gsub(/\D/, "")
end
```
