### ISSUE TITLE
HackerOne

### ISSUE THREAD

**Issue by SynergyBest** [Homebrew/brew#10874]
### Provide a detailed description of the proposed feature

On the hackerone page for homebrew it says “We pay bounties through BountyGraph (https://bountygraph.com/programs/homebrew).“ but bountygraph shut down a year ago.

### What is the motivation for the feature?

If someone wants an insensitive to report a vulnerability (none that I know of) this will help

### How will the feature be relevant to at least 90% of Homebrew users?

It probably won’t but it’s a very easy issue to solve

### What alternatives to the feature have been considered?

Not sure

**Comment by SynergyBest** [comment]
(I realize this in the wrong section but I don’t see where else to put it)

**Comment by MikeMcQuaid** [comment]
Fixed, thanks for the report @SynergyBest!

**Comment by SynergyBest** [comment]
👍
