### ISSUE TITLE
ARM64 brew install ${formulae}, always show Error: SHA256 mismatch

### ISSUE THREAD

**Issue by Manlinup** [Homebrew/brew#10875]
### `brew config` output

HOMEBREW_VERSION: 3.0.7-11-g53f34af-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 53f34af1c53c5716a77255d3227a5ba2cdc58ea9
Last commit: 20 hours ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: 3ad9891001294e7583e61fa6cfb7db68435abdca
Core tap last commit: 14 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.aliyun.com/homebrew/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false

### `brew doctor` output

Much info but no waning.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

ARM64 brew....
Install some Formulae such as php@7.4, kafka.

### What happened (include all command output)?

Always shows:
brewa install php@7.4
==> Downloading https://mirrors.aliyun.com/homebrew/homebrew-bottles/bottles/apr-1.7.0_2.arm64_big_sur.bottle.tar.gz
Already downloaded: /Users/linyida/Library/Caches/Homebrew/downloads/88d0983312cd82ff8b457d6646677fd9d447b15e235c7941e5d6e321647a000d--apr-1.7.0_2.arm64_big_sur.bottle.tar.gz
==> Downloading https://mirrors.aliyun.com/homebrew/homebrew-bottles/bottles/apr-util-1.6.1_3.arm64_big_sur.bottle.tar.gz
Already downloaded: /Users/linyida/Library/Caches/Homebrew/downloads/1e5f752c21a2e00680ae2875987d66f4b5ebf20921bc08fb0af0d3aabf83f981--apr-util-1.6.1_3.arm64_big_sur.bottle.tar.gz
Error: SHA256 mismatch
Expected: 29ffec15c99813b879d9410e2040044b02ee8e219492d065043b4bb65cf30741
  Actual: 79b9dc1a57ac27e3ba8677023ab5eed214db2c9ae4af72dea2aa4ac91fafabc3
    File: /Users/linyida/Library/Caches/Homebrew/downloads/1e5f752c21a2e00680ae2875987d66f4b5ebf20921bc08fb0af0d3aabf83f981--apr-util-1.6.1_3.arm64_big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.

### What did you expect to happen?

install succeed

### Step-by-step reproduction instructions (by running `brew` commands)

brew cleanup && brew update
brew install php@7.4

**Comment by carlocab** [comment]
One of these two might be causing the problem:
```
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
```
or
```
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.aliyun.com/homebrew/homebrew-bottles
```
Try setting these to the defaults (i.e. unset `HOMEBREW_BOTTLE_DOMAIN` and/or set your core tap origin to https://github.com/Homebrew/homebrew-core.git) and see if that helps.

**Comment by carlocab** [comment]
I think the issue is with your bottle mirror:
```
❯ curl -sSL https://homebrew.bintray.com/bottles/apr-util-1.6.1_3.arm64_big_sur.bottle.tar.gz | sha256sum
29ffec15c99813b879d9410e2040044b02ee8e219492d065043b4bb65cf30741  -
❯ curl -sSL https://mirrors.aliyun.com/homebrew/homebrew-bottles/bottles/apr-util-1.6.1_3.arm64_big_sur.bottle.tar.gz | sha256sum
79b9dc1a57ac27e3ba8677023ab5eed214db2c9ae4af72dea2aa4ac91fafabc3  -
```
The bottles in your mirror appear to be compromised.

**Comment by carlocab** [comment]
If Bintray is too slow, you might want to try https://mirrors.sustech.edu.cn/homebrew-bottles. This seems to work:
```
❯ curl -sSL https://mirrors.sustech.edu.cn/homebrew-bottles/bottles/apr-util-1.6.1_3.arm64_big_sur.bottle.tar.gz | sha256sum
29ffec15c99813b879d9410e2040044b02ee8e219492d065043b4bb65cf30741  -
```
