### ISSUE TITLE
Automatically update homebrew every 24 hours by default

### ISSUE THREAD

**Issue by ndbroadbent** [Homebrew/brew#10876]
### Provide a detailed description of the proposed feature

Homebrew should adopt https://github.com/DomT4/homebrew-autoupdate as the default behavior, instead of making users wait for `brew update` before `brew install` commands.

This behavior can be implemented manually by running the following commands:

```bash
brew tap domt4/autoupdate
brew autoupdate --start
echo 'export HOMEBREW_NO_AUTO_UPDATE="1"' >> ~/.zshrc
# (or ~/.bashrc)
```

Some care should be taken to avoid large spikes in `brew update` requests at exactly the same time (e.g. midnight.) The auto-update time should be randomized so that `brew update` commands are spread out.

Otherwise, it should be straightforward to integrate the code from [DomT4/homebrew-autoupdate](https://github.com/DomT4/homebrew-autoupdate) and run `brew autoupdate --start` during the Homebrew installation.

### What is the motivation for the feature?

`brew update` can be quite slow, and it can be frustrating when homebrew decides to fetch updates before installing a new package. It would be great if the Homebrew formula index could be updated in the background, so the latest formulae are always ready to use whenever we run `brew install ...`. (However, I wouldn't recommend actually upgrading installed formulae in the background.)

### How will the feature be relevant to at least 90% of Homebrew users?

100% of Homebrew users would benefit from this becoming the default behavior.

### What alternatives to the feature have been considered?

It's currently possible to opt-in to automatic updates by using this third-party script: [DomT4/homebrew-autoupdate](https://github.com/DomT4/homebrew-autoupdate)

```bash
brew tap domt4/autoupdate
brew autoupdate --start
echo 'export HOMEBREW_NO_AUTO_UPDATE="1"' >> ~/.zshrc
# (or ~/.bashrc)
```

**Comment by gromgit** [comment]
`cron` does the same job without installing extra stuff, and is cross-platform to boot (I also run Homebrew on my Linux boxes). My crontab contains, among other things:
```
3 0 * * * { /usr/local/bin/brew update ; /usr/local/bin/brew bundle dump --global --force ; } > /tmp/brew_maint.log 2>&1
```
which both updates Homebrew and dumps the current list of installed formulae, every night at 12:03am.

**Comment by MikeMcQuaid** [comment]
We're not going to make this default behaviour but, if @DomT4 was game, we could consider making this an official tap and point the documentation to it.

**Comment by DomT4** [comment]
Me and @MikeMcQuaid held some initial discussions on making my `autoupdate` tap part of the Homebrew organisation last month. That's likely to happen in the near future, and likely would have already if I hadn't been briefly derailed by some very minor surgery & the aftercare around that. Remains very much on my radar and should see a resolution soon 🤞🏻.

**Comment by MikeMcQuaid** [comment]
> if I hadn't been briefly derailed by some very minor surgery & the aftercare around that

Oof, get well soon @DomT4 ❤️
