### ISSUE TITLE
brew leaves does not display explicitly installed packages that are dependencies for other installed packages (Linux)

### ISSUE THREAD

**Issue by nickgerace** [Homebrew/brew#10892]
### `brew config` output

```shell
[nick at pop-os in ~/github.com/nickgerace/dotfiles] (1) (pop)
% brew config
HOMEBREW_VERSION: 3.0.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 59ada80ca740e72d29e625079395ee91cae4b3cf
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 09efd651a7de5a88fac017ff501851d27a97a308
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit icelake
Clang: N/A
Git: 2.27.0 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.8.0-7642-generic x86_64 GNU/Linux
OS: Pop!_OS 20.10 (groovy)
Host glibc: 2.32
/usr/bin/gcc: 10.2.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
[nick at pop-os in ~/github.com/nickgerace/dotfiles] (0) (pop)
% brew doctor
Your system is ready to brew.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I was trying to use `brew leaves` to store my packages, but noticed that `kubernetes-cli` was not being included in the output. I believe the issue is that I explicitly installed `kubectx` and `kubernetes-cli` (order does not matter), and that there is some issue with `brew leaves` including explicitly dependencies for other installed packages in its output. I'm assuming that `brew leaves` does not understand that `kubernetes-cli` may be a dependency for `kubectx`, but I also explicitly installed `kubernetes-cli` as well.

### What happened (include all command output)?

```bash
[nick at pop-os in ~/github.com/nickgerace/dotfiles] (0) (pop)
% brew leaves
doctl
helm
k3d
k9s
kubectx
patchelf
rke
[nick at pop-os in ~/github.com/nickgerace/dotfiles] (0) (pop)
% brew deps --tree --installed
doctl

helm

k3d

k9s

kubectx
└── kubernetes-cli

kubernetes-cli

patchelf

rke

[nick at pop-os in ~/github.com/nickgerace/dotfiles] (0) (pop)
% brew --version
Homebrew 3.0.7
Homebrew/homebrew-core (git revision 09efd651a7d; last commit 2021-03-20)
```

### What did you expect to happen?

I expected both `kubectx` and `kubernetes-cli` to be in the output of `brew leaves`.
The counterargument is that installing `kubectx` will always install `kubernetes-cli`, but I believe that may not always be true.
Dependencies change, so `brew leaves` making that assumption might not be ideal (if this behavior is intentional).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
docker run -it --entrypoint /bin/bash linuxbrew/linuxbrew:latest
# in the container...
brew install kubectx
brew install kubernetes-cli
brew leaves
```

**Comment by carlocab** [comment]
This is by design, so it can't be a bug:
```
❯ brew help leaves
Usage: brew leaves

List installed formulae that are not dependencies of another installed formula.
```
I guess you're looking for formulae that you installed on request. `brew bundle dump` will create a `Brewfile` in your current working directory that does this.

**Comment by nickgerace** [comment]
Thank you for your patience and explanation @carlocab. This was an RTFM issue on my part. For some reason, I believed it behaved different on macOS, so that's what led me to file this, but that was more than likely a mistake. I appreciate it.
