### ISSUE TITLE
non-cask formulas not properly padded with `brew ls`

### ISSUE THREAD

**Issue by jcayzac** [Homebrew/brew#10897]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.0.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 59ada80ca740e72d29e625079395ee91cae4b3cf
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9a7f59dcd615b696b687a349571be2dfdb5f6f28
Core tap last commit: 40 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_BADGE:   🥃  
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 12.0.32.28
Xcode: 12.4
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

`brew ls`

### What happened (include all command output)?

The formulas at the end use `U+0020 SPACE` characters for padding, so they are properly aligned.
The other formulas are padded with `U+0009 TAB` characters, and it's unclear to me what's the assumption regarding the width: I use `tabs -2` but even with `tabs -4` the output is all messed up.

```sh
$ brew ls
act			gettext			lame			lzo			rubberband
allure			gh			leptonica		make			ruby
aom			ghostscript		libass			mas			ruby-build
apktool			giflib			libbluray		microk8s		rush
aria2			git			libcroco		mpdecimal		sdl2
asciinema		git-lfs			libde265		ncurses			sdl2_image
autoconf		glew			libev			netpbm			shared-mime-info
bash			glib			libevent		nettle			shellcheck
bash-completion@2	gmp			libffi			nghttp2			sleepwatcher
bat			gnu-getopt		libheif			oniguruma		snappy
bc			gnu-sed			libidn			openapi-generator	sonar-scanner
bdw-gc			gnu-tar			libidn2			opencore-amr		speex
berkeley-db		gnutls			liblqr			openexr			sqlite
blueutil		go			libogg			openjdk			srt
boost			go-md2man		libomp			openjdk@8		starship
brotli			gobject-introspection	libpng			openjpeg		svg2png
bundletool		gource			libpthread-stubs	openssl@1.1		tcl-tk
c-ares			gradle			librsvg			opus			termtosvg
cairo			graphite2		libsamplerate		p11-kit			tesseract
cf-cli			graphviz		libsndfile		packer			testssl
coreutils		grep			libsodium		pandoc			thefuck
dav1d			gts			libsoxr			pango			theora
deno			guile			libssh2			parallel		tmux
docbook			harfbuzz		libsvg			pcre			unbound
docbook-xsl		highlight		libsvg-cairo		pcre2			utf8proc
docker			httpie			libtasn1		perl			vim
duck			httpx			libtiff			pidcat			watchman
exiftool		hugo			libtool			pigz			webp
ffmpeg			icu4c			libunistring		pipenv			wget
findutils		ilmbase			libvidstab		pixman			x264
fish			imagemagick		libvorbis		pkg-config		x265
flac			inetutils		libvpx			plantuml		xclogparser
fontconfig		jasper			libx11			pngcrush		xmlto
fonttools		jemalloc		libxau			pure-ftpd		xorgproto
fortune			jenv			libxcb			python@3.8		xvid
freetype		jinja2-cli		libxdmcp		python@3.9		xz
frei0r			jpeg			libxext			qpdf			yaml-cpp
fribidi			jq			libxrender		rav1e			yq
gd			jwkgen			libyaml			rbenv			zeromq
gdbm			ktlint			little-cms2		readline		zimg
gdk-pixbuf		kubernetes-cli		lua			rtmpdump
android-studio                      font-meslolg-nerd-font              keybase                             swiftdefaultappsprefpane
apppolice                           google-chrome                       krita                               viber
basictex                            iina                                lastpass                            visual-studio-code
cisco-proximity                     iterm2                              lulu                                zettlr
cyberduck                           java                                microsoft-teams                     zoom
docker                              jdownloader                         ngrok
font-consolas-for-powerline         kap                                 postman
```

### What did you expect to happen?

Consistent use of `U+0020 SPACE` characters for padding.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Assuming Bash,


$ tabs -2
$ brew ls
```

**Comment by carlocab** [comment]
The misalignment is actually useful (and, I'd argue, not messed up):

The first set of items you see (e.g. act, `allure`, `aom`, `gettext`)  are formulae. The second set set of items (e.g. `android-studio`, `appolice`, `font-meslolg-nerd-font`) are casks.

They happen to be aligned differently because the alignment is set differently within each group. Delineating the two sets with a header that says `Formulae:` for the first set and `Casks:` for the second might be useful here.

Not really sure what you mean by a "non-cask formula", though. A formula isn't a cask, so all formulae are non-casks.

**Comment by MikeMcQuaid** [comment]
> The misalignment is actually useful (and, I'd argue, not messed up):

agreed 👍🏻

**Comment by jcayzac** [comment]
@carlocab I understand your argument above and thank you for the PR you submitted, which will indeed make it much less confusing.

As for the `messed up`, I stand by it: try `brew ls` when your terminal uses 2 spaces for tabs (`tabs -2`). Nothing is aligned. Here is a screenshot so that things aren't fixed by GitHub defaulting to 8 spaces per tab:

<img width="1290" alt="Screen Shot 2021-03-24 at 11 12 53" src="https://user-images.githubusercontent.com/106682/112244053-fd22e080-8c91-11eb-915d-ba7bda36008b.png">

Relying on tabs (or unknown width) for padding doesn't work, formulaes should use space characters like casks do. Looking at the code, I realize it's an artifact of delegating to different commands (`ls` vs `find`). Maybe some filtering of the output to replace tabs with 8 spaces would fix it?

**Comment by carlocab** [comment]
What does the output of `ls $(brew --cellar)` look like?

If the output of `ls` is also messed up, then I'm not sure monkey-patching the output of `ls` to get it to come out right in non-standard setups is the correct move for `brew`. This probably needs to be fixed in `ls`, not in `brew`.

If the output isn't, then we can look into why `brew` is breaking `ls`' output.

**Comment by MikeMcQuaid** [comment]
> I stand by it: try `brew ls` when your terminal uses 2 spaces for tabs (`tabs -2`).

Don't do that then. This behaviour has been the case the entire time `brew ls` has existed as a command.

As @carlocab points out: your issue is with `ls` (which we shell out to).

**Comment by jcayzac** [comment]
You're right, I thought maybe brew was not invoking ls properly but when I try the default BSD `ls` in my terminal it's the same misaligned thing 😢  (I've always aliased `ls` to `gls` so it's never been an issue for me).
