### ISSUE TITLE
Homebrew for Windows (Not just like WSL)

### ISSUE THREAD

**Issue by CreativeQuilt** [Homebrew/brew#10902]
### Provide a detailed description of the proposed feature

Homebrew is the "Missing package manger for macOS" but also windows doesn't have a package manger either, sure there is Cygwin, minGW, and Chocolatey but people don't like those. Sure you may say just use WSL but you can't go in to PowerShell and say "Brew install gcc" it won't work at all because you need WSL. 

### What is the motivation for the feature?

I'm a Developer using windows and I like many other windows programmers need a package manger that has good stuff and not some crappy one that only has a few packages which are viruses and trogons imported by the developer. 

### How will the feature be relevant to at least 90% of Homebrew users?

It means if they switch to windows they can still use Homebrew and it's many packages

### What alternatives to the feature have been considered?

Homebrew on Windows Subsystem for Linux

**Comment by carlocab** [comment]
Homebrew on Linux happened when someone forked `brew` and then made it work on Linux. Eventually, that fork was merged with Homebrew (though not fully yet -- linuxbrew-core is still separate from homebrew-core, but hopefully not for long).

The same will probably have to happen for Homebrew on Windows to happen.

**Comment by MikeMcQuaid** [comment]
This won't happen, sorry.

**Comment by CreativeQuilt** [comment]
People are Lazy

**Comment by carlocab** [comment]
Is that why, when you want something built, you go ask other people to do it rather than build it yourself?
