### ISSUE TITLE
`brew upgrade` ignores `--dry-run` option

### ISSUE THREAD

**Issue by kidonng** [Homebrew/brew#10909]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.0.8-12-g28b1765
ORIGIN: https://github.com/Homebrew/brew
HEAD: 28b176567992f8d323d73a0a1367d8239e34e8a4
Last commit: 42 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 76f9b4a0c3d48200edd075343103b24c8bebe53c
Core tap last commit: 19 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3-x86_64
CLT: 12.0.32.29
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Checking outdated formulae and casks by `brew upgrade --greedy --dry-run`.

### What happened (include all command output)?

Homebrew starts to upgrade packages.

### What did you expect to happen?

Homebrew should not do upgrades with `--dry-run`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Have at least one outdated formula
2. Run `brew upgrade --dry-run`
```

---

This is introduced in #10880:

![image](https://user-images.githubusercontent.com/44045911/112071839-988d5600-8bab-11eb-9d38-8934c7d43672.png)

(**EDIT last screenshot is wrong**)

**Comment by carlocab** [comment]
#10907 might help, but I suspect @Bo98 should have a fix for this shortly.
