### ISSUE TITLE
Recent timeout addition set to nil causes many old systems using this to die.

### ISSUE THREAD

**Issue by jayzalowitz** [Homebrew/brew#10913]
### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 3.0.8-26-g2d3aca7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2d3aca706def80d90a271e2eb45a9c4b2f5e9a77
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f9507dc3abef8a7d675fbe700d15e30b63cf2cb7
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

### `brew doctor` output

```shell
Not the problem, verified with a fix internally.

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/jayzalowitz/.pyenv/shims/python3.9-config
  /Users/jayzalowitz/.pyenv/shims/python-config
  /Users/jayzalowitz/.pyenv/shims/python3-config

Warning: Found Ruby file outside xxxxx/tap tap formula directory.
(/usr/local/Homebrew/Library/Taps/xxxxx/homebrew-tap/Formula):
  /usr/local/Homebrew/Library/Taps/xxxxx/homebrew-tap/download_strategy.rb

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  docutils
  awscli
  gnupg

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> /Users/jayzalowitz/.bash_profile

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install postgresql

Run `brew missing` for more details.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

https://github.com/Homebrew/brew/commit/712a95fdd0aabab3b335341ae5efd675d5a0da9c#r48562926 sets timeout default as nil, causing an unkown keyworkd to be passed down in old code, which is a breaking change for a few old systems.
Many systeems use this in their code, ex: https://gist.github.com/minamijoyo/3d8aa79085369efb79964ba45e24bb0e#file-private_strategy-rb-L65
All of these systems are going to need to be updated if it isnt default set

### What happened (include all command output)?

Error: unknown keyword: timeout
Please report this issue:
  https://docs.brew.sh/Troubleshooting
xxxxx/download_strategy.rb:124:in `_fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:390:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:142:in `fetch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1882:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1130:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:401:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:315:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:313:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:313:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

### What did you expect to happen?

Timeout to have been defined and just worked.

Setting as 30 default is probably better

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
its just a brew install that calls something like 

https://gist.github.com/minamijoyo/3d8aa79085369efb79964ba45e24bb0e#file-private_strategy-rb
```

**Comment by Rylan12** [comment]
I think the problem with your specific case is that overriding the `_fetch` method is not part of the public API. Custom download strategies are means to override the `fetch` method, instead. If you override `fetch`, formula installs should still work as expected because formula installs don't specify a timeout for fetching resources.

---

That being said, I think this does break the public API. Since cask downloads can specify a timeout, if the custom download strategy hasn't fixed its `fetch` method, passing a timeout will fail.

We may need to do something like this in [`Cask::Download#fetch`](https://github.com/Homebrew/brew/blob/00d8e1ab3dab7644f93fccdfbabb4e24310d24aa/Library/Homebrew/cask/download.rb#L25):

```ruby
begin
  downloader.fetch(timeout: timeout)
rescue ArgumentError
  odeprecated "`downloader.fetch` without a timeout", "`downloader.fetch` with a timeout"
  downloader.fetch
end
```

This may not be the best way to handle this (and I'm not super pumped with that deprecation warning), but if I don't hear any other maintainer opinions I'll open a PR to make this change.

CC @reitermarkus

**Comment by Rylan12** [comment]
> I think the problem with your specific case is that overriding the `_fetch` method is not part of the public API. Custom download strategies are means to override the `fetch` method, instead. If you override `fetch`, formula installs should still work as expected because formula installs don't specify a timeout for fetching resources.

As another maintainer pointed out to me, this isn't really a fair statement because the public API is about which methods can be called and doesn't really indicate anything about inheritance. So, my statement to use `fetch` instead of `_fetch` may not be totally correct.

I've opened #10919 to add a deprecation message and to help solve this issue.

**Comment by Rylan12** [comment]
@jayzalowitz and @lordjabez I've reverted the problematic PRs. As soon as CI runs on the master branch (~20 minutes) I'll tag version 3.0.9 which will include the fixes.
