### ISSUE TITLE
Brew upgrade relinks unlinked packages

### ISSUE THREAD

**Issue by mcfedr** [Homebrew/brew#10943]
### Provide a detailed description of the proposed feature

Prevent brew from automatically linking packages during upgrade if its been manually unlinked.

### What is the motivation for the feature?

I have some packages installed, but i keep them unlinked, mostly because they conflict or interact with the PATH, or because i have multiple versions of a program installed.

but i want to be able to run upgrade to get the latest version of everything, after this i have to re-unlink/link things.

### How will the feature be relevant to at least 90% of Homebrew users?

i think lots of users use multiple versions, this is were it it most relevent.
e.g.
brew install php php@74

- now you have php 8 installed and default in PATH - and also php 7.4 availble
- a really easy way to change the default version - brew unlink php && brew link php@74
- wait a few weeks and run upgrade
- suddenly you are accidently using the wrong version again, because upgrade php has linked it again.

### What alternatives to the feature have been considered?

right now I do this by hand and its a bit annoying because i forget...

**Comment by MikeMcQuaid** [comment]
> Prevent brew from automatically linking packages during upgrade if its been manually unlinked.

We don't have a way of distinguishing between manually and intentionally unlinked so this isn't possible.



> * a really easy way to change the default version - brew unlink php && brew link php@74

An easier way still: change your `PATH`.
