### ISSUE TITLE
Weird brew is / is NOT installed catch-22 situation

### ISSUE THREAD

**Issue by Sauraus** [Homebrew/brew#1095]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

### Bug reports:

I am stuck in a weird catch-22 situation where brew ends up with a split brain.

```ruby
default-macosx-1011:~ vagrant$ brew
-bash: brew: command not found
default-macosx-1011:~ vagrant$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
The current contents of /usr/local are bin Cellar etc Frameworks Homebrew include lib opt sbin share var
default-macosx-1011:~ vagrant$ 
default-macosx-1011:~ vagrant$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
Failed to locate Homebrew!
```

**Comment by wayne-luminal** [comment]
Came here to report this. I am having the same problem.

**Comment by Sauraus** [comment]
Workaround is to delete `/usr/local/Cellar` & `/usr/local/Homebrew` at least that did the trick for me and I could install brew again.

**Comment by MikeMcQuaid** [comment]
> Workaround is to delete /usr/local/Cellar & /usr/local/Homebrew at least that did the trick for me and I could install brew again.

@Sauraus Glad you have a workaround. I'll try to fix the install/uninstall process to handle this case.

**Comment by zmwangx** [comment]
To anyone who experiences this problem: the output of the following commands could help us diagnose your issue:

```bash
brew --prefix
command -v brew
/bin/ls -ld /usr/local/bin/brew /usr/local/.git
```

**Comment by wayne-luminal** [comment]
@zmwangx 

```
[:~] % brew --prefix
zsh: command not found: brew
[:~] 127 % command -v brew
[:~] 1 % /bin/ls -ld /usr/local/bin/brew /usr/local/.git
ls: /usr/local/.git: No such file or directory
ls: /usr/local/bin/brew: No such file or directory
```

**Comment by zmwangx** [comment]
@wayne-luminal Do you have `/usr/local/Homebrew/.git`?

**Comment by wayne-luminal** [comment]
@zmwangx Yes

```
[:~] % cd /usr/local/Homebrew
[:/usr/local/Homebrew] master ± ls -a
.                .git             .gitignore       .yardopts        CONTRIBUTING.md  Library          bin              docs
..               .github          .travis.yml      CODEOFCONDUCT.md LICENSE.txt      README.md        completions      manpages
[:/usr/local/Homebrew] master ±
```

**Comment by zmwangx** [comment]
@wayne-luminal That's very interesting, no `bin`. You should

```sh
cd /usr/local/Homebrew
git fetch
git reset --hard origin/master
ls -l bin/brew  # you should have it now
bin/brew update --force
```

**Comment by Sauraus** [comment]
I can reproduce this problem consistently with using the Chef Homebrew cookbook (https://github.com/chef-cookbooks/homebrew) when installing brew on a VM running Sierra on VMWare-Fusion 8.5.

**Comment by wayne-luminal** [comment]
@zmwangx Looks like that did the trick to let me use brew again. I ended up on the v1.0.2 release directly so I just manually reset to master and ran a second update. Aside from this and needing to create a symlink myself, these steps worked for me.

```
[:/usr/local/Homebrew] master ± git fetch
remote: Counting objects: 639, done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 639 (delta 510), reused 588 (delta 463), pack-reused 0
Receiving objects: 100% (639/639), 66.48 KiB | 0 bytes/s, done.
Resolving deltas: 100% (510/510), completed with 142 local objects.
From https://github.com/Homebrew/brew
   559cea7..246bb1a  master     -> origin/master
[:/usr/local/Homebrew] master ± git reset --hard origin/master
HEAD is now at 246bb1a Merge pull request #1050 from reitermarkus/rubocop
[:/usr/local/Homebrew] master ± ls -l bin/brew
-rwxr-xr-x  1 user  admin  1363 Sep 22 20:47 bin/brew
[:/usr/local/Homebrew] master ± bin/brew update --force
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
aws-sdk-cpp                      cromwell                         gitlab-ci-multi-runner           kobalt                           mesos                            repo
[:/usr/local/Homebrew] v1.0.2 1 ±
```

**Comment by zmwangx** [comment]
@wayne-luminal 

> I ended up on the v1.0.2 release directly so I just manually reset to master and ran a second update

You ended up on the v1.0.2 release because you should.

**Comment by zmwangx** [comment]
@Sauraus 

> I can reproduce this problem consistently with using the Chef Homebrew cookbook 

Well, if you want to get support for us you should follow *our* instructions, not the Chef Homebrew cookbook (I don't know what that is)...

**Comment by Sauraus** [comment]
@zmwangx I was just trying to provide a test case that causes this split brain brew install in the first place, therefore I am not entirely sure what you mean by 'follow **our** instructions'?

The root cause in my case appears to be a timeout on the git fetch operation during the brew install which results in a half-baked brew installation, necessitating the manual git fetch operation to un-break it.

**Comment by zmwangx** [comment]
> I was just trying to provide a test case that causes this split brain brew install in the first place

Thanks for a "test case" like this: https://github.com/chef-cookbooks/homebrew

**Comment by MikeMcQuaid** [comment]
I think what @zmwangx is trying to say is: if you can produce a reproducible test case with e.g. Homebrew's installer let us know so we can fix it but we cannot be responsible for how e.g. Chef installs Homebrew.

**Comment by Sauraus** [comment]
Someone will have to explain to me how they differ... :)

Official brew page:
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

Chef Homebrew recipe:
```
default['homebrew']['installer']['url'] = 'https://raw.githubusercontent.com/Homebrew/install/master/install'

remote_file homebrew_go do
  source node['homebrew']['installer']['url']
  checksum node['homebrew']['installer']['checksum'] unless node['homebrew']['installer']['checksum'].nil?
  mode 00755
end

execute 'install homebrew' do
  command homebrew_go
  environment lazy { { 'HOME' => ::Dir.home(homebrew_owner), 'USER' => homebrew_owner } }
  user homebrew_owner
  not_if { ::File.exist? '/usr/local/bin/brew' }
end
```

Both methods run exactly the same code. ;)

**Comment by zmwangx** [comment]
> Someone will have to explain to me how they differ... :)

I'm afraid you got it wrong. No one (here) has to explain that to me because how Chef installs Homebrew is none of our business.

I'm also afraid I can't read that DSL, and thus can't tell whether it differs.

Bottom line: If you have problem with `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`, let us know. Otherwise, I'm afraid you'll need to talk to Chef.

**Comment by MikeMcQuaid** [comment]
The install situation should be massively improved by https://github.com/Homebrew/install/pull/69.
