### ISSUE TITLE
Fatal error on outdated xcode

### ISSUE THREAD

**Issue by reaperhulk** [Homebrew/brew#1096]
### Bug reports:

A recent commit (https://github.com/Homebrew/brew/commit/a124680b189f50ebeb550845e3c0efd34db66247) now causes running an outdated Xcode to raise a fatal error. On Travis CI this results in any image other than xcode8 (presumably) failing. Choosing which version of macOS you get on Travis is based on xcode versioning (see: https://blog.travis-ci.com/2016-09-15-new-default-osx-image-coming/) so this change is problematic.

**Comment by DomT4** [comment]
Just great. Great great great. Fantastic.

Give me a short while.

**Comment by reaperhulk** [comment]
FWIW I would be fine with having a flag to bypass the check. This would result in breakage for Travis projects, but they'd be able to add `--no-xcode-check` and proceed, while normal desktop users would continue to receive the fatal error and be asked to upgrade.

Thanks for the quick action @DomT4!

**Comment by DomT4** [comment]
I've just reverted it for now before people start noticing this & I have to deal with 50 unique issues 😕. We'll want to keep the check, but yeah, we'll want to be smarter about it since there's nothing people relying on Travis can do to force Travis to update.

I believe Travis sets `TRAVIS` or something similar in the environment, so maybe I can sniff that out & skip over when it exists.

**Comment by reaperhulk** [comment]
They do (https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables), although I'd personally prefer a flag rather than it trying to sniff the env. I completely understand why you may not want to go that route due to the avalanche of bug reports you'd receive, although maybe that can be mitigated by using the env detection to just print a message suggesting that they add the flag?

Either way, I appreciate the hard work you do here! 👍

**Comment by zmwangx** [comment]
I'd rather people never need to worry about brew (plus people can't read), so I'd vote for env var detection, although that means only the most popular service(s) get special treatment.

**Comment by DomT4** [comment]
I'll probably re-add it with a couching that allows `TRAVIS` and `HOMEBREW_DEVELOPER` to not suffer fatal failures on this. That's maybe not a bad compromise.

Given we soft-fail if you try to force link OpenSSL and almost nobody seems to have noticed or tweaked their Travis builds accordingly I'd take a rough guess that a lot of people aren't regularly reading the logs particularly deeply.

**Comment by zmwangx** [comment]
> Given we soft-fail if you try to force link OpenSSL

That one definitely broke SO though, lol.

**Comment by DomT4** [comment]
https://github.com/Homebrew/brew/pull/1097

**Comment by DanToml** [comment]
@DomT4 Hey, sorry for commenting on a closed issue, but I think this may need a slightly more complex solution. We're having similar problems over at CircleCI, and can't force users to upgrade their formulae or Xcode versions.

A potential solution would be the discussed explicit `--no-xcode-check`, or adding a generic `CI` env var check, but this could break users local workflows (Especially for Swift Formulae that may not work on latest Xcode yet, like [SwiftLint](https://github.com/Homebrew/homebrew-core/blob/303660134f72cffaef94f87abfb6bfeedccc0e1c/Formula/swiftlint.rb)).

I'm more than happy to contribute a PR for this, but I'm not sure which approach the team would rather see.

**Comment by DomT4** [comment]
@DanToml Do you set an env in the same way Travis does by any chance? I might just scope this to 10.12 temporarily until we can iron this out a bit more 😕.

The primary point of the change was to stop 10.12 users running Xcode 7.x, which flat out breaks almost everything on 10.12 in fun and interesting ways, so if we have to tone it down a touch whilst considering how to move forwards I can live with that.

**Comment by DanToml** [comment]
@DomT4 Yeah, we set `CIRCLECI` and `CI` to true on every build.

Yeah I've seen some pretty weird issues from people running 7.x on 10.12 with some of my repos, but also the same types of issue with Xcode 8.0 running on 10.11 for more complex dependencies.

I threw up a branch with a check for our env for a quick test https://github.com/DanToml/brew/tree/dani_circleci_xcode_version, but can PR a toned down check now.

**Comment by jawshooah** [comment]
@DomT4 FYI Travis sets `CI` as well, so you could just use that instead of both `TRAVIS` and CIRCLECI`.

**Comment by DomT4** [comment]
Give me a sec, I'll push something directly to solve the problem. We protect our master branch but I can turn it off temporarily. Otherwise you'll be waiting 40+ minutes for a solution as our CI tests on core code are fairly extensive and our CI resources fairly limited.

**Comment by DomT4** [comment]
Double opt-out in https://github.com/Homebrew/brew/commit/12aad5c65fee39c5f044e39ca1efcbed58aebd39. If you're running `ENV["CI"]` anywhere you won't get nagged at, even if you're running Sierra. If you're running any OS X version prior to Sierra you won't get nagged at. If you're running Sierra and your installed development tools are outdated and you're not a robot, you'll get nagged at 😄.

Hopefully that's a decent short-term compromise until we can iron out the kinks in a way that works for everyone.

**Comment by DanToml** [comment]
@DomT4 💖 thanks for this!

**Comment by Adnn** [comment]
Hi,

@DomT4 Since a recent `brew update`, I am running into the reported error.

> Error: Your Xcode (6.4) is outdated
> Please update to Xcode 8.0.

 My environment is El Capitan (OS X 10.11), I tried updating brew just now, without success. I also reinstalled it (just to make sure).

     ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Without any more success.

From your latest comment:
> If you're running any OS X version prior to Sierra you won't get nagged at. 
I understood that and up-to-date version of brew should not raise this error anymore. Is there something obvious I missed ?

Thank you for reading

**Comment by zmwangx** [comment]
@Adnn 

> It thus seems an up-to-date version of brew on El Capitan should not raise this error anymore. Is there something obvious I missed ?

Only if you're on the master branch. But apparently you're on the 1.0.3 branch, and you should wait for the 1.0.4 release.

In the meantime the workaround is `export TRAVIS=1`, but seriously, Xcode 6.4 on El Capitan? We can't guarantee that won't be blocked again in the near future. No way are we going to support this configuration. Please at least update to Xcode 7.3.

**Comment by Adnn** [comment]
@zmwangx Thank you for the workaround, it works!

Then, Xcode 6.4 ships with llvm 3.6 based compiler. Appart from Boost, not so many projects are C++ enough to go beyond the limit of this compiler ;)

**Comment by zmwangx** [comment]
@Adnn A major Xcode release is much more than better coverage of newer C++ specs (think about Swift for a very basic example). Keep in mind that if you run into problems with Xcode 6.4 we cannot provide support for you, and we may block Xcode 6.4 on El Capitan in the future.

**Comment by DomT4** [comment]
Yeah. I tweaked the change, which will land in the next tag which likely won't be too long, but realistically at some point in the future we will likely be enforcing a minimum supported Xcode version, which for 10.11 is likely to be `7.2.1` or such rather than `8.0`.

This offers people some flexibility but also will quite drastically reduce the level of bugs users see & the level of bugs our reply has to be "Upgrade your Xcode" to. We have diagnostic warnings in place already, but too many people ignore them and it creates unnecessary hassle for them & increases the maintenance burden on us not insignificantly.
