### ISSUE TITLE
Confusion about custom location

### ISSUE THREAD

**Issue by chmaynard** [Homebrew/brew#1098]
A few weeks ago, I installed Homebrew in a custom location: 

    git clone https://github.com/Homebrew/brew /Users/craig/Homebrew

After version 1.0 was released, I deleted this directory and did a clean install:

    git clone https://github.com/Homebrew/brew /Users/craig/brew

When I run ```brew update``` I now see this error message:

    /Users/craig/brew/bin/brew: line 5: cd: /Users/craig/Homebrew/bin: No such file or directory

Apparently, Homebrew still remembers the old location. How can I fix this problem?

**Comment by MikeMcQuaid** [comment]
What does `ls -lha /Users/craig/brew/bin/brew` and `which brew` output?

**Comment by chmaynard** [comment]
```
$ ls -lha /Users/craig/brew/bin/brew
-rwxr-xr-x  1 craig  admin   1.3K Sep 21 15:43 /Users/craig/brew/bin/brew

$ which brew
/Users/craig/brew/bin/brew

```

**Comment by MikeMcQuaid** [comment]
How about `ls -lha /usr/local/bin/brew`?

**Comment by zmwangx** [comment]
Also,

```
/usr/bin/sed -i '' $'1 a\\\nset -x\n' /Users/craig/brew/bin/brew
brew
```

will help us a lot in diagnosing your issue.

**Comment by chmaynard** [comment]
```
$ ls -lha /usr/local/bin/brew
lrwxr-xr-x  1 root  wheel    30B Sep 21 07:49 /usr/local/bin/brew -> /Users/craig/Homebrew/bin/brew
```

Oops. Sorry for the noise.

**Comment by chmaynard** [comment]
@zmwangx I'm not familiar with sed. How do I undo this?

    /usr/bin/sed -i '' $'1 a\\\nset -x\n' /Users/craig/brew/bin/brew

**Comment by zmwangx** [comment]
@chmaynard 

    git -C /Users/craig/brew/bin checkout brew

**Comment by chmaynard** [comment]
🙏

**Comment by MikeMcQuaid** [comment]
@zmwangx That's unnecessary, btw, you can just use `--debug`.

**Comment by zmwangx** [comment]
@MikeMcQuaid `--debug` has no effect on `/bin/brew`.

**Comment by MikeMcQuaid** [comment]
@zmwangx Aye but it'll dump the variables in `brew.sh` such as HOMEBREW_BREW_FILE

**Comment by zmwangx** [comment]
@MikeMcQuaid It you never get to the sourcing `brew.sh` stage then it won't (which is the case here), unfortunately.

**Comment by MikeMcQuaid** [comment]
@zmwangx True. Another option is `bash -x /Users/craig/brew/bin/brew`

**Comment by zmwangx** [comment]
Yeah.
