### ISSUE TITLE
After `brew update` my custom formulas are gone.

### ISSUE THREAD

**Issue by ellio167** [Homebrew/brew#11]
I ran `brew update` and it updated fine, but now the /usr/local git repo has been completely rewritten and all the changes I has stored locally appear to be gone!

I'm surprised by the major migration without any warning...

**Comment by bfontaine** [comment]
> all the changes I has stored locally appear to be gone!

How did you store them? Did you add your formula files directly under `Library/Formula/`?

**Comment by ellio167** [comment]
I did `brew create` and then committed the changes to my /usr/local/ repo.  Luckily, I have pushed these changes to my own remote fork of the repo.  So, I'll be able to recover, but it was surprising that the migration didn't check for any changes.

**Comment by bfontaine** [comment]
It `reset` the git history during the migration. The supported way to have your own formulae is to host them in a tap: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

**Comment by ellio167** [comment]
Ah!  OK, that's a helpful pointer... Thanks!

**Comment by joneskoo** [comment]
Quite scary to lose all local changes without prompt. I was working on a pull request, and did a brew update. Now the change is gone. Would have been a great idea to rename the old directory rather than destroy it without prompt. No luck with Time Machine either. :disappointed:

**Comment by mikemcquaid** [comment]
While this is regrettable: putting untracked, uncommitted, unbackuped files in any Git repository is a disaster waiting to happen.
