### ISSUE TITLE
Simple pre/post brew command hooks. 

### ISSUE THREAD

**Issue by seivan** [Homebrew/brew#11017]
### Provide a detailed description of the proposed feature

I know this has been discussed before and obviously been shut down pretty quick, but since it's been a while I'd thought I try again.

I'm looking for two hooks for *any* brew command, not interested in distinguishing what kind of command. 
This could be from `brew install`, `brew doctor` to `brew search`, doesn't matter. 

As I understand it, some of the hesitation has been for complexity and foot guns. 
To avoid that, pass no arguments, no params or flags or any form of context.
Only that I get to execute some bash/shell script before and after brew has done its part. 

### What is the motivation for the feature?

Brew is running some form of regex on files in `$PATH` that triggers a warning, that as far as I know hasn't causing an issue yet, but always spits out a giant warning which I find bothersome . 

I am saying as far as I know in a sense that I am scared it **might** causes issues down the line. 

The issue I've had in the past is that some brew warnings are actually important and need to be fixed.
However, this basically poisons the well and pollutes the interface for more serious issues.

I rather fix the issue by not having those things in my `$PATH` and b

### How will the feature be relevant to at least 90% of Homebrew users?

On it's own it's most likely not going to be. 
But to change perspective, users might just be living with the issues since they got no choice. 
Either way, the ability to add a feature that helps with getting rid of warnings has value. 

### What alternatives to the feature have been considered?

Right now I'm doing something like `pb; brew <command>; ab` to alter `$PATH` between brew calls. 
Before that, it was aliases and functions but that messes up completions. 
The issue also comes from automation and other scripts that relies on brew directly like `ruby-install`. 
Which means I need to do it before `ruby-install` as well.

**Comment by Rylan12** [comment]
What's the warning that's being shown? Fixing that seems like an easier solution to me (without knowing what it is). I don't think we've received other similar complaints so I'm not sure we'd be willing to add a new layer of complexity just for the one-off case where a warning is shown.

**Comment by Rylan12** [comment]
You could also make a shell function that wraps the `brew` command with something like this:

```bash
brew() {
    pb
    /usr/local/bin/brew $*
    ab
}
```

**Comment by carlocab** [comment]
+1 for wrapping `brew` in a shell function. It's what I do, and it works quite well for me.

**Comment by carlocab** [comment]
You can even do something like
```bash
brew() {
    pb
    command brew $@
    local brew_status=$?
    ab
    return $brew_status
}
```
If you need `brew`'s exit code for some reason.

**Comment by MikeMcQuaid** [comment]
> Brew is running some form of regex on files in `$PATH` that triggers a warning, that as far as I know hasn't causing an issue yet, but always spits out a giant warning which I find bothersome .

Which commands? `brew doctor` or more than this?

> +1 for wrapping `brew` in a shell function. It's what I do, and it works quite well for me.

Agreed. Closing, sorry!

**Comment by seivan** [comment]
@carlocab @Rylan12 Thanks for the help!
