### ISSUE TITLE
Support for cask alternatives in depends_on

### ISSUE THREAD

**Issue by lukasbestle** [Homebrew/brew#11011]
### Provide a detailed description of the proposed feature

It should be possible for formulae to define cask alternatives to dependencies:

```rb
depends_on "gpg", cask_alternative: "gpg-suite"
```

Homebrew will then check if the cask (here `gpg-suite`) is already installed, in which case it will skip installing the dependency (here `gpg`). If the cask is *not* already installed, it will install the dependency as normal.

Of course it should never be possible to define *just* a cask as a formula dependency. This would create a dependency on a non-open-source package (as explained [here](https://github.com/Homebrew/brew/issues/9401#issuecomment-738007106)). If the cask is just the alternative, the current behavior of installing the formula dependency will still work, be tested and will stay the default if the cask alternative is not already present.

### What is the motivation for the feature?

Sometimes a dependency is already provided by a Cask a user has installed. An example is the `gpg` formula, which is also provided by the `gpg-suite` cask. So if the user installs a formula that depends on `gpg`, the `gpg-suite` cask should also be accepted and therefore the installation of the `gpg` formula should be skipped.

A practical use-case for this feature is the `pass` formula, which currently depends on `gpg`.

### How will the feature be relevant to at least 90% of Homebrew users?

It will increase the reliability of Homebrew in scenarios where a tool like GPG is already present on the system. The current behavior leads to a broken system state as GPG is installed twice. This can happen to every user, but should happen to no user. So the feature is relevant for 100 % of Homebrew users.

### What alternatives to the feature have been considered?

The alternative could be to make the casks define which formulae they replace. Homebrew could check all installed casks for this information before installing a new formula.

For example the `gpg-suite` cask could define that it replaces the `gpg` formula. If the user now installs the `pass` formula, Homebrew will know that GPG is already installed and will skip installing `gpg`.

The advantage is that the installation order wouldn't matter (if `gpg` is installed first and then the user installs `gpg-suite`, the `gpg` formula could be automatically uninstalled).

The disadvantage is potentially a lower performance when installing formulae. Also the feature I have proposed above is more explicit and allows each formula to define if it's happy with the cask alternative.

I'm not sure which way is the best overall. The alternative listed here would be cleaner, but potentially more work to implement.

**Comment by carlocab** [comment]
I don't see this happening, unfortunately -- at least not for any formulae in homebrew/core.

It might be something allowed for formulae outside of homebrew/core, but given that it's a feature that won't ever be used in homebrew/core, I suspect that implementing it would have to be done by someone who isn't a Homebrew maintainer.

Not a satisfying answer, I know. However, this is supported by reasoning that I don't quite have time to explain at the moment. You may wish to look into the removal of options and cask dependencies in homebrew/core, as what's discussed there is related to this.

**Comment by MikeMcQuaid** [comment]
> It will increase the reliability of Homebrew in scenarios where a tool like GPG is already present on the system.

We used to do this (`Requirement`s and `default_formula`). It was significantly _less_ reliable. Strong 👎🏻 from me on ever bringing it back.

> The current behavior leads to a broken system state as GPG is installed twice.

Can you elaborate on this? This seems like something that should/could be fixed if one of these installations fails.

**Comment by lukasbestle** [comment]
Thanks for your quick replies!

> @carlocab You may wish to look into the removal of options and cask dependencies in homebrew/core, as what's discussed there is related to this.

Do you have a link for me? I looked through the issues in this repo and couldn't find any discussions on this topic. That's why I opened this issue in the first place. :)

> Can you elaborate on this? This seems like something that should/could be fixed if one of these installations fails.

Installation won't fail, but it will lead to two GPG installations with different versions. This in turn leads to conflicts because of two `gpg-agent`s running side-by-side. There should just never be two separate GPG installations on the same machine.

What about the alternative solution from my first post? If this has been discussed before, a link would be helpful.

**Comment by MikeMcQuaid** [comment]
> Installation won't fail, but it will lead to two GPG installations with different versions.

This doesn't seem to inherently be a problem.

> This in turn leads to conflicts because of two `gpg-agent`s running side-by-side.

This requires you to run both `gpg-agent`s, no?

> There should just never be two separate GPG installations on the same machine.

I strongly disagree.

> What about the alternative solution from my first post?

If the cask and formula are different versions: they are not interchangeable so this alternative doesn't work.

> Do you have a link for me?
> If this has been discussed before, a link would be helpful.

You should have enough here to search through the past issues/PRs on this topic.

**Comment by lukasbestle** [comment]
> I strongly disagree.

How can you say that without explaining your reasoning?

> You should have enough here to search through the past issues/PRs on this topic.

See my comment above: "I looked through the issues in this repo and couldn't find any discussions on this topic. That's why I opened this issue in the first place. :)"

To be honest, I'm pretty astonished that you are closing issues that fast. Is this the culture in which you would want to contribute to open-source projects?

**Comment by carlocab** [comment]
Open issues on our issue tracker represent work to be done. There's no work to be done here at the moment, so we can't afford to keep it open. I'm sorry you find that disappointing, but that's just the way we manage our project.

Regarding `gnupg` and `gpg-suite`: it doesn't look like they are drop-in replacements for each other. `gnupg` links with a number of Homebrew libraries:
```
❯ brew linkage gnupg
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libresolv.9.dylib
  /usr/lib/libsqlite3.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/gettext/lib/libintl.8.dylib (gettext)
  /usr/local/opt/gnutls/lib/libgnutls.30.dylib (gnutls)
  /usr/local/opt/libassuan/lib/libassuan.0.dylib (libassuan)
  /usr/local/opt/libgcrypt/lib/libgcrypt.20.dylib (libgcrypt)
  /usr/local/opt/libgpg-error/lib/libgpg-error.0.dylib (libgpg-error)
  /usr/local/opt/libksba/lib/libksba.8.dylib (libksba)
  /usr/local/opt/libusb/lib/libusb-1.0.0.dylib (libusb)
  /usr/local/opt/npth/lib/libnpth.0.dylib (npth)
  /usr/local/opt/readline/lib/libreadline.8.dylib (readline)
Indirect dependencies with linkage:
  readline
```
so software that depend on `gnupg` could be indirectly referencing those libraries as well. This means that `gpg-suite` is unlikely to be a drop-in replacement for `gnupg`, and one is likely to encounter subtle and difficult-to-diagnose bugs when trying to replace `gnupg` with `gpg-suite`.

A similar problem is likely to be the case with other cask replacements, and we just don't have the testing infrastructure in place to check.

**Comment by MikeMcQuaid** [comment]
> Open issues on our issue tracker represent work to be done.

This is the culture I wish to encourage on this project, yes.

**Comment by lukasbestle** [comment]
@carlocab Thanks for the explanation! I just tried `brew install pass` on a machine that has `gpg-suite` installed and it failed with the following error output:

```
==> Pouring gnupg-2.2.27.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/gpg
Target /usr/local/bin/gpg
already exists. You may want to remove it:
  rm '/usr/local/bin/gpg'

To force the link and overwrite all conflicting files:
  brew link --overwrite gnupg

To list all files that would be deleted:
  brew link --overwrite --dry-run gnupg

Possible conflicting files are:
/usr/local/bin/gpg -> /usr/local/MacGPG2/bin/gpg2
```

If we won't get on with this issue (which is fine, I respect your decision as the maintainers), how can this be solved instead?

@MikeMcQuaid You and I both know that you didn't answer my question. I'll leave it at that.

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid You and I both know that you didn't answer my question. I'll leave it at that.

Ok then:

> > I strongly disagree.
> 
> How can you say that without explaining your reasoning?

I don't think avoiding duplicating of packages is more important than the reliability, robustness and maintaining upstream consistency between versions of packages. This is both a technical principle I hold and also one I've seen play out through maintaining this project for 11+ years and singlehandedly adding binary packages and CI into this project when it lacked either.

> See my comment above: "I looked through the issues in this repo and couldn't find any discussions on this topic. That's why I opened this issue in the first place. :)"

You didn't look hard enough, clearly. It is not the job of Homebrew maintainers to go and find justifications that satisfy you. We've given you more information that may help your search. If that's not enough: sorry but we don't have time to do more.

> To be honest, I'm pretty astonished that you are closing issues that fast.

Read through the issue tracker on this project and on homebrew-core and you will see that it's not uncommon at all. Ironically, many people seem to appreciate that we're responsive.

> Is this the culture in which you would want to contribute to open-source projects?

Yes. Again, I've been maintaining this project for 11+ years. I've been contributing to open source in some form for 15+ years. I consider closing issues quickly to be a good thing rather than a bad one.

Hopefully this answers your question(s).

---

> If we won't get on with this issue (which is fine, I respect your decision as the maintainers), how can this be solved instead?

Formulae could be taught that it's OK to overwrite casks, casks could be taught to not create symlinks that class with formulae, the formula could be made keg-only or the formula could be unlinked by default when the cask in installed.

**Comment by lukasbestle** [comment]
Thanks for your reply.
Again (as I wrote in my first reply), I really appreciate your fast response, I just don't appreciate closing issues quickly without understandable reasoning. Your last reply clears that up for me. Thanks for that!

I will open an issue in `homebrew-core` about the specific `pass` installation issue.
