### ISSUE TITLE
instant configurations

### ISSUE THREAD

**Issue by queilawithaQ** [Homebrew/brew#11019]
### Provide a detailed description of the proposed feature

instantly configurating/linking bundles & casks via simple command in turn helping the terminal stay connected to the correct user admins profile as well as fixing any leaks or broken links within the terminal.

### What is the motivation for the feature?

my terminal's had many issues where im not able to find or access a dir or profile. ..

### How will the feature be relevant to at least 90% of Homebrew users?

will help users stay bug free & effectively use homebrew.

### What alternatives to the feature have been considered?

instead of each person tapping into the same files/folder paths, helping the user configure their existing and homebrew REQUIRED packages.

**Comment by MikeMcQuaid** [comment]
Sorry, I don't understand what you're asking for here.
