### ISSUE TITLE
brew 3.0.10 crashes sometimes during interrupts

### ISSUE THREAD

**Issue by Dentrax** [Homebrew/brew#11020]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0ad2564c5f1ddf6f16f707f2861556b80546713c
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 739e6ffb3cd270ef0d769452ef527380345b06d6
Core tap last commit: 65 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: 12.4
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  go@1.13
  libav

Warning: Found Ruby file outside goodwithtech/r tap formula directory.
(/usr/local/Homebrew/Library/Taps/goodwithtech/homebrew-r/Formula):
  /usr/local/Homebrew/Library/Taps/goodwithtech/homebrew-r/dockle.rb

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  bats
  gnupg@1.4
  kubernetes-cli

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo filippo.io/age) checkout master
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

```bash
$ brew install argocf
^C 
# (SIGINT, instantly)

# `argocf` is a typo of `argocd`

```

### What happened (include all command output)?

brew install argocf
^CTraceback (most recent call last):
	21: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
	20: from <internal:gem_prelude>:2:in `require'
	19: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:1391:in `<top (required)>'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:868:in `load_defaults'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:814:in `each_spec'
	16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:766:in `each_gemspec'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:766:in `each'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:767:in `block in each_gemspec'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:767:in `each'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:768:in `block (2 levels) in each_gemspec'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:815:in `block in each_spec'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1168:in `load'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1168:in `eval'
	 8: from /Library/Ruby/Gems/2.6.0/specifications/default/scanf-1.0.0.gemspec:4:in `load'
	 7: from /Library/Ruby/Gems/2.6.0/specifications/default/scanf-1.0.0.gemspec:4:in `new'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2067:in `initialize'
	 5: from /Library/Ruby/Gems/2.6.0/specifications/default/scanf-1.0.0.gemspec:26:in `block in load'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:548:in `add_development_dependency'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1536:in `add_dependency_with_type'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1536:in `require'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:5:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:5:in `require': Interrupt

### What did you expect to happen?

it should do nothing?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install argocf
```

`macOS 11.0.1`
`zsh 5.8 (x86_64-apple-darwin20.1.0)`
`ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]`

**Comment by MikeMcQuaid** [comment]
This isn't really avoidable. We can't handle every single possible exception in every single case on interrupt.
