### ISSUE TITLE
Finding a new home for Hombrew binaries - Bintray sunsets on May 1st 2021

### ISSUE THREAD

**Issue by harishperfect** [Homebrew/brew#11026]
### Provide a detailed description of the proposed feature

I navigated to bintray.com while on slow internet (I was installing neovim while connected to a train wifi), I found that bintray is being sunset as of May 1st, 2021. I googled to see if there were any alternate plans discussed but could not find any related issues. Please feel free to close if this has been discussed :) 

### What is the motivation for the feature?

Bintray, JCenter, GoCenter, and ChartCenter are being deprecated on May 1st 2021. Blog link https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

### How will the feature be relevant to at least 90% of Homebrew users?

I believe it would affect 100% of homebrew users if there is no alternative already. Seems like we may have a supply chain deprecation issue.

### What alternatives to the feature have been considered?

Maven? Github maybe? I don't have enough information to suggest. Will update the issue as I continue my research for a better and efficient alternative.

**Comment by carlocab** [comment]
This is already being discussed at https://github.com/Homebrew/discussions/discussions/691. Feel free to continue the discussion there.
