### ISSUE TITLE
Homebrew Locks Folder

### ISSUE THREAD

**Issue by kube** [Homebrew/brew#1104]
We use Homebrew at our school, the problem is that we use home sessions over NFS, where `flock` is not permitted.

So when installing a package, Homebrew fails to `flock` in `~/.brew/var/homebrew/locks`.

I created a dirty fix to install Homebrew on our sessions that just makes a symlink on a `/tmp/` folder: https://github.com/kube/42homebrewfix/blob/master/install.sh

But, I was guessing if it would be possible to create a variable `HOMEBREW_LOCKS`, just like `HOMEBREW_CACHE` and `HOMEBREW_TEMP` to prevent the use of symlinks?

**Comment by MikeMcQuaid** [comment]
We'll need more than single user to request this, I'm afraid. A workaround would be to do another mount on top of `var/homebrew/locks` to some other non-NFS path.
