### ISSUE TITLE
Rename "brew update" to "brew self-update" perhaps?

### ISSUE THREAD

**Issue by kevinquillen** [Homebrew/brew#1105]
I may be in a minority here, but is there any possibility of renaming `brew update` to `brew self-update`?

I get it mixed up with `brew upgrade` all the time, and when it comes to a package like Node, can be a pain when working with others where the slightest change in node version can have weird and wild hard to trace effects.

Or alternatively, could `brew upgrade` do nothing without args, and have an `--all` flag to upgrade all pacakges?

**Comment by zmwangx** [comment]
Sorry, `brew update` has been around for years and we surely won't rename it and break everything. Use an alias like `brewu` for `brew update` to prevent mistyping.

> Or alternatively, could brew upgrade do nothing without args, and have an --all flag to upgrade all pacakges?

That one's been tried, people got angry, and the decision was reversed. So no.

**Comment by zmwangx** [comment]
By the way,

> where the slightest change in node version can have weird and wild hard to trace effects.

`brew pin node`, or use something like nvm instead.
