### ISSUE TITLE
Brew doesnt play nicely with virus scanners

### ISSUE THREAD

**Issue by gtmtech** [Homebrew/brew#11085]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.0.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8e11f03fa93b148e26044a331654241a2c307039
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab461737d0420601affad3493035db582ad7a37f
Core tap last commit: 19 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.31.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.


# btw normally I have /usr/bin before /opt/homebrew/bin because ... security reasons ... but it doesnt affect this issue
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I was trying to install ffmpeg because I wanted to use ffmpeg. 

I already diagnosed this issue - so I'll put it here. It seems temporary files are created in `/private/tmp` as part of the installation or download process - and then cleaned up

However it seems the Intego for mac virus scanner with realtime scanning keeps these files from being deleted momentarily resulting in random amount of errors of the form below

```
Error: Directory not empty @ dir_s_rmdir - /private/tmp/d20210408-2683-1k88ehp
```

Personally I think it would be good if brew could detect and/or wait for the virus scan to do its thing rather than just erroring. 

As a workaround disabling active virus scans and switching back on solved the issue - but in an ideal world obviously virus scans should be taking place - so really it should be homebrew to fix this race condition.

### What happened (include all command output)?

```
brew install ffmpeg 

...

==> Summary
🍺  /opt/homebrew/Cellar/m4/1.4.18: 13 files, 658KB
==> Installing ffmpeg dependency: libtool
==> Pouring libtool-2.4.6_3.arm64_big_sur.bottle.tar.gz
Error: Directory not empty @ dir_s_rmdir - /private/tmp/d20210408-2683-1k88ehp
```

### What did you expect to happen?

I expected ffmpeg to be installed without errors

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Install Intego virus scanner for mac
2. Make sure Virus Barrier / Turn Real-time scanning is on. 
3. brew install ffmpeg
```

**Comment by MikeMcQuaid** [comment]
> but in an ideal world obviously virus scans should be taking place

We disagree. Virus scanners are redundant on macOS. This needs to be fixed in the virus scan software and not a volunteer-run open source project.

**Comment by gtmtech** [comment]
@MikeMcQuaid Are you saying "virus scanners are redundant on macOS" because you think you can't get viruses or malware on a mac? I'm interested in why you said it, as it certainly isn't a common view held amongst secops, although obviously there is much less malware and viruses around on mac than windows.

In reality lots of corporate governance require you to run and have turned on virus scanners on corporate machines, whether or not they are macosx, windows or linux desktops. From a corporate perspective, you are not just trying to protect your own staff from having viruses, but you need to protect your staff from inadvertently sending viruses to other people (even if they don't affect you) to stop your liability in case of passing them on to other entities. 

Anyway if someone has the same problem, hopefully they'll find this issue and understand why. The interoperability and quality of homebrew is as you say - a matter for you.
