### ISSUE TITLE
Improve Shellcheck usage

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#11086]
### Provide a detailed description of the proposed feature

We use `shellcheck` as part of `brew style`. It should ideally be improved so that:
- [x] We also check Bash (and perhaps Zsh?) completion files: https://github.com/Homebrew/brew/blob/fa3af8d24d0335641e58a4355fa9de6d42ae4982/Library/Homebrew/style.rb#L179
- [x] We use `--enable=all` to run more checks (and fix them): https://github.com/Homebrew/brew/blob/fa3af8d24d0335641e58a4355fa9de6d42ae4982/Library/Homebrew/style.rb#L188
- [ ] We use `shellcheck --format=json` or `--format=json1` output with `brew style`'s JSON output (https://github.com/Homebrew/brew/blob/fa3af8d24d0335641e58a4355fa9de6d42ae4982/Library/Homebrew/style.rb#L62-L63) to then provide annotations that are displayed inline using GitHub Actions

### What is the motivation for the feature?

We have similar behaviour for Ruby code and find it useful.

### How will the feature be relevant to at least 90% of Homebrew users?

Improved and maintained code quality for our Bash scripts.

### What alternatives to the feature have been considered?

Doing nothing.

**Comment by hyuraku** [comment]
@MikeMcQuaid 
How do we solve the warning ` SC2154:` like below when  ` We use --enable=all to run more checks`
Should we add `export HOMEBREW_LINUX=` or rewrite ` if [[ -n "$HOMEBREW_LINUX:-" ]]` ?

```
In /usr/local/Homebrew/Library/Homebrew/utils/analytics.sh line 61:
  if [[ -n "$HOMEBREW_LINUX" ]]
            ^-------------^ SC2154: HOMEBREW_LINUX is referenced but not assigned.
            ^-------------^ SC2250: Prefer putting braces around variable references even when not strictly required.
```

**Comment by MikeMcQuaid** [comment]
@hyuraku I'd suggest we disable it for specific variables and note specifically what script that are exported from.

**Comment by MikeMcQuaid** [comment]
Nice work on this so far @GauthamGoli and @hyuraku!

**Comment by hyuraku** [comment]
@MikeMcQuaid 
> We use spellcheck --format=json or --format=json1 output with brew style's JSON output (

I guess it's a mistake `shellcheck` for `spellcheck`; how about it?

**Comment by MikeMcQuaid** [comment]
@hyuraku Whoops, updated!

**Comment by XuehaiPan** [comment]
`shellcheck` added a new output format `diff` ([FORMATS](https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md#FORMATS)) in (https://github.com/koalaman/shellcheck/commit/b1aeee564c6852147081dda08b1030e864b1711f) since 0.7.0.

We can add:

```bash
shellcheck -f diff <files> | git apply
```

or

```bash
shellcheck -f diff <files> | patch -p1  # (`-p1` for relative paths and `-d / -p0` for absolute paths)
```

to `brew style --fix` to auto-fix code styles for shell scripts.

Besides, we can use vscode-shellcheck/vscode-shellcheck#278 in our vscode settings to apply auto-fix on save.

**Comment by MikeMcQuaid** [comment]
@XuehaiPan Sounds nice! Does that mean we can avoid using `shfmt`?

**Comment by MikeMcQuaid** [comment]
@XuehaiPan Do we have inline `shellcheck` comments on pull requests through GitHub Actions now? I can't remember :think

**Comment by XuehaiPan** [comment]
> Do we have inline `shellcheck` comments on pull requests through GitHub Actions now?

## Homebrew/brew

We use `.shellcheckrc` in [Homebrew/brew](https://github.com/Homebrew/brew) to disable SC2310-SC2312 in PR #12397. For the other checks (all checks except SC2310-SC2312), we have inline comments `# shellcheck diable=...` with explanations in repo [Homebrew/brew](https://github.com/Homebrew/brew).

We have run `brew style` for Homebrew/brew itself through GitHub Actions (both ruby files and shell scripts):

https://github.com/Homebrew/brew/blob/0730fa74f654845598b8bb48dc5bccb3a07ef2f1/.github/workflows/tests.yml#L42

## Homebrew official taps

We have also run `brew style` on all official taps, but for ruby files only (`shellcheck` will not run):

https://github.com/Homebrew/brew/blob/0730fa74f654845598b8bb48dc5bccb3a07ef2f1/.github/workflows/tests.yml#L129-L147

Usually, the official taps don't contain shell scripts and we don't need to run `shellcheck` on them. The repo [Homebrew/command-not-found](https://github.com/Homebrew/command-not-found) has `.sh` and `.fish` scripts but not in `bash`. There is a bug for shellcheck autofix koalaman/shellcheck#2370 when I run `brew style --fix` in [Homebrew/command-not-found](https://github.com/Homebrew/command-not-found).

## Homebrew/install

We have integrated `brew style` in [Homebrew/install](https://github.com/Homebrew/install)'s GitHub Actions:

https://github.com/Homebrew/install/blob/cc7fe005e7449d29a064d82736ad5419a4f9da23/.github/workflows/tests.yml#L112-L116

The inline comments need to be added in PR Homebrew/install#593 for [Homebrew/install](https://github.com/Homebrew/install).

**Comment by MikeMcQuaid** [comment]
Thanks @XuehaiPan! I think what I'm asking is: if `brew style` fails: do the comments show up in the PR files tab (like they do for `rubocop`)?

**Comment by XuehaiPan** [comment]
> I think what I'm asking is: if `brew style` fails: do the comments show up in the PR files tab (like they do for `rubocop`)?

If `brew style` fails, the message (file name / line number / what) and the check ID (SCxxxx, etc.) will show on the GitHub Action result page.

**Comment by MikeMcQuaid** [comment]
@XuehaiPan Perfect, then this is done. Thanks for all your great work here 🎉 ❤️
