### ISSUE TITLE
rewrite_shebang does not work when there is a flag in the shebang

### ISSUE THREAD

**Issue by iMichka** [Homebrew/brew#11108]
### What were you trying to do (and why)?

I'm trying to use the `rewrite_shebang detected_perl_shebang`the DSL on the `xmltoman` script (from the xmltoman formula).

### What happened (include all command output)?

It does not work because the original shebang has a flag in it (`#!/usr/bin/perl -w`).

### What did you expect to happen?

`#!/usr/bin/perl -w` to be replaced by `#!/usr/bin/env perl` (I don't think it's possible to keep the flag though).

**Comment by Bo98** [comment]
> I don't think it's possible to keep the flag though

We replace with the full opt bin path to the Perl binary rather than use `/usr/bin/env`, so this won't be a problem.
