### ISSUE TITLE
Deduplicate GitHub Actions Usage

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#11101]
### Provide a detailed description of the proposed feature

Homebrew/homebrew-core and Homebrew/linuxbrew-core (and, to a much lesser extent, Homebrew/brew) have a huge amount of duplication and copy-paste between actions that differ in very small ways. These should be deduplicated and move of their logic moved to Homebrew/actions.

Composite actions (https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action) may be a simple way to simplify some of these workflow files and keep them in sync.

### What is the motivation for the feature?

Reducing complexity due to repeated duplication in GitHub Actions workflow files.

### How will the feature be relevant to at least 90% of Homebrew users?

More reliable CI.

### What alternatives to the feature have been considered?

Not doing this.

**Comment by GauthamGoli** [comment]
I've spent some time on this, posting the findings here. 

Composite actions don't support setting conditionals, continue-on-error, timeout-minutes, "uses", and secrets on individual steps within a composite action right now.  (Reference: https://github.com/actions/runner/issues/646) 

The actions which we want to be deduplicated use one of the above unsupported statements/features. We'll have to park this idea until then. 

As of now, we can only use composite actions to replace a bunch of `run` statements, which is a very narrow use case.

**Comment by MikeMcQuaid** [comment]
Thanks @GauthamGoli! Looks like composite actions are a non-starter for now, indeed. Do you have any other ideas on how to deduplicate? Perhaps we could have e.g. a single workflow that takes more inputs?

**Comment by GauthamGoli** [comment]
@MikeMcQuaid yeah, using a single workflow seems promising. I will open a PR if it works!

**Comment by xakep8** [comment]
Can we do something like process scheduling, like in apt?

**Comment by MikeMcQuaid** [comment]
@xakep8 I'm not sure I understand the question, please elaborate!

**Comment by mohzulfikar** [comment]
Hi there, I want to ask about this issue. From what I understand, homebrew has a custom action repository in [here](https://github.com/Homebrew/actions/). So, if I want to create new composite action I should place the composite action in there and then use it on other repository. Is that the correct flow?

**Comment by dawidd6** [comment]
Yes

**Comment by mohzulfikar** [comment]
Thank you

**Comment by MikeMcQuaid** [comment]
I think this is as done as it needs to be.
