### ISSUE TITLE
`cleanup` will uninstall the only installed version of a formula if the formula was installed before #11114 was merged

### ISSUE THREAD

**Issue by wendorf** [Homebrew/brew#11127]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.1-6-gd81a047
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d81a047544c431ab733f21d8ebd028a44341bfa6
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7e1b80e655368fc16c9ade900154b68dff8db352
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I was trying to run `brew cleanup` to cleanup caches, etc.

### What happened (include all command output)?

This is for `brew cleanup --dry-run` since I don't want to be bit by the bug:

```
Would remove: /usr/local/Cellar/openssl@1.1/1.1.1k (8,071 files, 18.5MB)
Would remove (empty directory): /usr/local/lib/ruby/vendor_ruby/3.0.0/x86_64-darwin20
Would remove (empty directory): /usr/local/lib/ruby/site_ruby/3.0.0/x86_64-darwin20
Would remove (empty directory): /usr/local/etc/openssl@1.1/private
Would remove (empty directory): /usr/local/etc/openssl@1.1/certs
==> This operation would free approximately 18.5MB of disk space.
```

### What did you expect to happen?

I expected openssl not to be removed, since I only have one installed openssl keg.

#11114 fixes this for _new_ installs, but for installs from before that PR is merged, the INSTALL_RECEIPT will still include the incorrect version_schema and brew will attempt to uninstall it. A workaround is to `brew reinstall` the affected formula, but a potential fix would be to not return a keg in `eligible_kegs_for_cleanup` if 1) the formula's `version_scheme` is not 0 2) the keg's `version_scheme` is 0 and 3) the keg would not be the only remaining keg if all other kegs eligible for cleanup were removed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
(cd "$(brew --prefix)/Homebrew" && git checkout 627381e949233ec90e4ea4ffc9d0e811f68619b9~)
HOMEBREW_NO_INSTALL_CLEANUP=1 brew install openssl # Note: I'm setting HOMEBREW_NO_INSTALL_CLEANUP=1 just to reproduce the issue. In practice, this was caused by me having an old install of openssl with an old INSTALL_RECEIPT
(cd "$(brew --prefix)/Homebrew" && git checkout master)
brew cleanup
```

**Comment by ElfSundae** [comment]
Same here, OpenSSL was removed in `brew cleanup`, then many `brew` commands will error:

```
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /usr/local/opt/curl/bin/curl
  Reason: image not found
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 295: 87158 Abort trap: 6           "$HOMEBREW_PREFIX/opt/curl/bin/curl" --version > /dev/null
```

I tried to reinstall Homebrew and all formulas but does not work.

Thank you for this issue description, I fixed this issue by using the `master` branch of brew repo then reinstalling openssl@1.1.

**Comment by carlocab** [comment]
#11114 wasn't really designed to prevent the cleanup of formulae with a misconfigured `version_scheme` that have already been installed, unfortunately.

That would require building some rather complicated logic that requires going through the formulae you already have installed, checking that it matches the formulae on the master branch of homebrew/core, and then changing the `version_scheme` in the tab.

**Comment by Bo98** [comment]
> but for installs from before that PR is merged, the INSTALL_RECEIPT will still include the incorrect version_schema and brew will attempt to uninstall it

How old are we talking about? I've recovered my install from March, and it has:

```
"versions":{"stable":"1.1.1k","head":"","version_scheme":1}}
```

The window where `INSTALL_RECEIPT` contained a version_scheme of 0 was:

* 12th April, 09:06 UTC to 12th April, 15:31 UTC for those on the "stable" channel (updates on new tags only)
* 8th April, 10:56 UTC to 12th April, 15:18 UTC for those on the "dev" channel on macOS (updates on every commit)
* 9th April, 09:07 UTC to 12th April, 15:18 UTC for those on the "dev" channel on Linux

**Comment by wendorf** [comment]
@carlocab Makes sense. I'm happy the fix is there, this is just to track the problem for people like me who were bit by the issue :)

@Bo98 The window you've put together matches my experience, since I was bit by this on the 10th or 11th.

**Comment by detunized** [comment]
I had a major problem with this one. I had lots formulae failing to install or requiring reinstall because I ran `brew cleanup`. Basically everything depending on `openssl@1.1` just got broken. It somehow works now, but I have a problem with the paths now. All the following formulae have .reinstall appended to them. I have not found a wait to correct that short of manual renaming.

```
❯ find /usr/local/Cellar -iname *.reinstall
/usr/local/Cellar/midnight-commander/4.8.26.reinstall
/usr/local/Cellar/glib-networking/2.68.0.reinstall
/usr/local/Cellar/wget/1.21.1.reinstall
/usr/local/Cellar/ffmpeg/4.3.2_4.reinstall
/usr/local/Cellar/nghttp2/1.43.0.reinstall
/usr/local/Cellar/mitmproxy/6.0.2_1.reinstall
/usr/local/Cellar/rtmpdump/2.4+20151223_1.reinstall
/usr/local/Cellar/aria2/1.35.0.reinstall
/usr/local/Cellar/rsync/3.2.3.reinstall
/usr/local/Cellar/srt/1.4.2.reinstall
/usr/local/Cellar/duo_unix/1.11.4.reinstall
/usr/local/Cellar/curl/7.76.0.reinstall
/usr/local/Cellar/libssh2/1.9.0_1.reinstall
/usr/local/Cellar/qemu/5.2.0_1.reinstall
/usr/local/Cellar/tcl-tk/8.6.11_1.reinstall
/usr/local/Cellar/watchman/4.9.0_5.reinstall
/usr/local/Cellar/lastpass-cli/1.3.3_1.reinstall
/usr/local/Cellar/libssh/0.9.5_1.reinstall
/usr/local/Cellar/libevent/2.1.12.reinstall
/usr/local/Cellar/megatools/1.10.3.reinstall
/usr/local/Cellar/node/15.14.0.reinstall
/usr/local/Cellar/unbound/1.13.1.reinstall
/usr/local/Cellar/nmap/7.91.reinstall
/usr/local/Cellar/openldap/2.4.58.reinstall
/usr/local/Cellar/python@3.8/3.8.9.reinstall
/usr/local/Cellar/gnupg/2.2.27.reinstall
/usr/local/Cellar/wireshark/3.4.4.reinstall
/usr/local/Cellar/ruby/3.0.1.reinstall
/usr/local/Cellar/python@3.9/3.9.4.reinstall
```

**Comment by MikeMcQuaid** [comment]
@detunized `rm -rf /usr/local/Cellar/*/*.reinstall` and then `brew install $(brew missing)` should sort you out.
