### ISSUE TITLE
Issue installing packages hosted on bintray?

### ISSUE THREAD

**Issue by jrista** [Homebrew/brew#11123]
### `brew config` output

```shell
HOMEBREW_VERSION: 2.2.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 13f508d0dc8ada1726ee09a750285d7447ac3df4
Last commit: 1 year, 4 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f2463cbba086689c872cddd3a8bc242976a603ff
Core tap last commit: 1 year, 3 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AWS_ACCESS_KEY_ID: set
HOMEBREW_AWS_SECRET_ACCESS_KEY: set
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_232
macOS: 10.15.1-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1 => /Applications/Xcode-11.3.1.app/Contents/Developer
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  python@2

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gettext

Warning: Your Xcode (11.3.1) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

We are trying to install the `httpie` command line tool so we can download various files and data during a CI build process. I have fibbed the above "no warnings" check, as I need to get this bug report in, as I dont' think its really a brew issue, but a bintray issue. I have tried to upgrade to xcode 12, which just snowballed into a whole 'nother ordeal I cannot handle right now. 

Suffice it to say, it appears bintray is shutting down next month. A package is now marked 403 Forbidden there, and the fallback that brew tries to look for is 404 Not Found. Someone needs to get this package fixed...hosted somewhere.

### What happened (include all command output)?

brew install httpie
Updating Homebrew...
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:b065e5e3783954f3e65d8d3a6377ca51649bfcfa21b356b0dd70490f74c6bd86
######################################################################## 100.0%
==> Pouring portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> New Formulae
abseil                                   libpciaccess
acl2                                     libpinyin
act                                      libpipeline
aerc                                     libpqxx@6
aida-header                              libprelude
airshare                                 libpthread-stubs
aliddns                                  libraqm
alsa-lib                                 librttopo
amp                                      libseccomp
ansible@2.9                              libslirp
apidoc                                   libsm
apollo-cli                               libtirpc
arb                                      libtorrent-rakshasa
archiver                                 libunwind
argo                                     libva
argocd                                   libvdpau
arrayfire                                libvnc
arturo                                   libx11
as-tree                                  libxau
asimov                                   libxaw
asroute                                  libxaw3d
asuka                                    libxcb
asymptote                                libxcomposite
athenacli                                libxcursor
atkmm@2.28                               libxdamage
attr                                     libxdmcp
austin                                   libxext
autodiff                                 libxfixes
aws-console                              libxfont
aws-rotate-key                           libxft
awscli@1                                 libxi
awsweeper                                libxinerama
azcopy                                   libxkbfile
b3sum                                    libxml++@4
bandit                                   libxml++@5
bas55                                    libxmu
bcoin                                    libxp
beancount                                libxpm
bic                                      libxrandr
biosig                                   libxrender
bit-git                                  libxres
blaze                                    libxscrnsaver
blogc                                    libxshmfence
bnfc                                     libxt
bombadillo                               libxtst
bond                                     libxv
bootloadhid                              libxvmc
borgbackup                               libxxf86dga
box2d                                    libxxf86vm
bpython                                  linux-headers
bpytop                                   linux-pam
brook                                    litecli
buildozer                                literate-git
c7n                                      lizard-analyzer
cacli                                    llvm@9
cadence                                  localstack
cadence-workflow                         logcli
cairomm@1.14                             logswan
cargo-audit                              loki
cargo-edit                               lp_solve
cargo-instruments                        lttng-ust
cargo-watch                              lua@5.3
carton                                   luajit-openresty
cassandra-cpp-driver                     lunchy
cassowary                                lunchy-go
castget                                  luv
cbc                                      macos-trash
cbmc                                     magic_enum
ccheck                                   mandown
cctz                                     mapcidr
cddlib                                   mariadb@10.4
cdk8s                                    markdownlint-cli
cdktf                                    marked
cdo                                      mask
cfn-flip                                 massdns
cfn-format                               matplotplusplus
cgl                                      md4c
chalk-cli                                mermaid-cli
charge                                   mesa-glu
chars                                    mhonarc
chart-testing                            microplane
checkov                                  minipro
cherrytree                               mmctl
chezmoi                                  mockery
choose-rust                              mockolo
chrony                                   moto
clair                                    mpdecimal
clang-format@8                           msc-generator
clash                                    mtoc
claws-mail                               muffet
cli11                                    multitime
clip                                     mx
cloud-nuke                               naabu
cloudflare-wrangler                      name-that-hash
cloudformation-cli                       nanorc
cloudformation-guard                     ncspot
clusterctl                               nef
cmt                                      nest
coconut                                  net-tools
code-server                              networkit
coin3d                                   never
colfer                                   newrelic-cli
commitizen                               nfpm
condure                                  ngs
confd                                    nicotine-plus
container-structure-test                 node@14
copilot                                  notmuch-mutt
coredns                                  nuclei
cortex                                   numactl
counterfeiter                            numcpp
cpio                                     oakc
cpm                                      obfs4proxy
cpplint                                  ocaml-zarith
cppman                                   oci-cli
cpr                                      odin
cqlkit                                   oha
crackpkcs                                oil
crane                                    omake
crcany                                   open-adventure
crispy-doom                              openalpr
croaring                                 openfast
croc                                     openfst
cubejs-cli                               openjdk@8
cucumber-ruby                            openlibm
curlie                                   openmama
cvs-fast-export                          openmodelica
dasel                                    openstackclient
datalad                                  oq
datasette                                or-tools
dbdeployer                               oras
delve                                    orgalorg
detach                                   ormolu
device-mapper                            ory-hydra
dgraph                                   osi
dhall-lsp-server                         osm
dhall-yaml                               osmcoastline
diskonaut                                overdrive
djl-serving                              ox
dmagnetic                                packetbeat
dnsprobe                                 packr
dnsx                                     pandoc-include-code
doctest                                  pandoc-plot
docui                                    pandocomatic
dog                                      parallel-hashmap
dolt                                     parliament
dosbox-staging                           pass-git-helper
dotenv-linter                            pcalc
dotnet                                   pcp
dprint                                   pdftilecut
driftctl                                 pdm
dstask                                   periscope
dua-cli                                  pfetch
duckdb                                   phive
duckscript                               php@7.4
duf                                      phpbrew
duktape                                  pickle
dynet                                    pipgrip
earthly                                  pkger
easy-rsa                                 po4a
efm-langserver                           podman
eksctl                                   polynote
eleventy                                 postgresql@12
emacs-dracula                            projectm
empty                                    prometheus-cpp
enkits                                   promtail
envoy                                    protoc-gen-go-grpc
enzyme                                   protoc-gen-gogo
epr                                      protoc-gen-gogofaster
erlang@22                                protoc-gen-grpc-web
eureka                                   psc-package
eva                                      ptpython
evernote2md                              publish
f3d                                      pueue
faiss                                    pure
fargatecli                               pwncat
fava                                     pyqt-3d
fblog                                    pyqt-builder
fcct                                     pyqt-networkauth
fennel                                   pyside@2
fetch                                    python-tabulate
fizz                                     python-tk@3.9
flamegraph                               python@3.7
flank                                    python@3.9
flarectl                                 qp
flash                                    qrcp
fleet-cli                                qt-libiodbc
flit                                     qt-mariadb
flow-cli                                 qt-mysql
flux                                     qt-percona-server
fnm                                      qt-postgresql
folderify                                qt-unixodbc
font-util                                quill
forcecli                                 rain
foreman                                  raxml-ng
forge                                    rbtools
fpart                                    rcm
fpdns                                    rdkit
fplll                                    redo
functionalplus                           reg
gallery-dl                               regipy
gateway-go                               reorder-python-imports
gau                                      rgf
gcalcli                                  richmd
gcc@9                                    rm-improved
gdbgui                                   rosa-cli
gdu                                      rqlite
geph2                                    rtl_433
geph4                                    rtorrent
gh                                       rttr
ghc@8.8                                  ruby@2.6
ghc@9                                    ruby@2.7
ghz                                      rubyfmt
ghz-web                                  rust-analyzer
git-annex-remote-rclone                  rustscan
git-bug                                  s2n
git-gui                                  saltwater
git-hooks-go                             saml2aws
git-hound                                sdns
git-remote-codecommit                    seal
git-trim                                 semgrep
gitbatch                                 semtag
gitlint                                  server-go
gitql                                    shallow-backup
gitui                                    sheldon
giza                                     showkey
glab                                     shtools
glibc                                    silicon
gluon                                    simdjson
gmailctl                                 skylighting
go-boring                                sleef
go-jsonnet                               smlpkg
go@1.13                                  smu
go@1.14                                  snap
go@1.15                                  snowpack
gobo                                     so
gocloc                                   solidity
gofish                                   sollya
gofumpt                                  sonic
gojq                                     spaceship
golangci-lint                            spack
googletest                               sponge
gopass-jsonapi                           spotify-tui
gopls                                    spotifyd
goredo                                   sqlancer
gosec                                    sqlc
gost                                     sqlite-utils
gostatic                                 standardese
gotop                                    staticcheck
gping                                    strace
gradle-profiler                          structurizr-cli
graphql-cli                              subfinder
gravity                                  swift-format
grex                                     swift-sh
grokj2k                                  systemd
grokmirror                               t-rec
grpcui                                   tanka
gtkmm4                                   taskwarrior-tui
guile@2                                  tctl
gulp-cli                                 tendermint
h2spec                                   tengo
halide                                   termcolor
haruhi-dl                                terracognita
hashlink                                 terraform-ls
haskell-language-server                  terraform-provider-libvirt
hasura-cli                               terraform@0.12
hblock                                   terraform@0.13
hcxtools                                 terrascan
hdf5-mpi                                 tfsec
hdf5@1.10                                tgenv
hdt                                      thanos
heksa                                    thrax
helib                                    threemux
heppdt2                                  timg
hexo                                     tlx
hsd                                      tm
htmltest                                 tomcat@9
httpx                                    toot
hy                                       torchvision
i686-elf-binutils                        trailscraper
i686-elf-gcc                             tre-command
iam-policy-json-to-terraform             trec_eval
iblinter                                 tree-sitter
iconsur                                  trimage
idris2                                   truffle
immudb                                   trunk
indicators                               tty-share
influxdb@1                               tz
infracost                                ugrep
inframap                                 unum
inja                                     uptoc
inko                                     usb.ids
inxi                                     utf8cpp
ioctl                                    util-macros
isl@0.18                                 uutils-coreutils
isort                                    v2ray
jc                                       vapor
jerryscript                              vc
jimtcl                                   vcpkg
jinx                                     vgrep
jobber                                   vint
jolie                                    virtualenv
jpeg-xl                                  vitess
jql                                      vivid
json5                                    vlang
jsonnet-bundler                          vlmcsd
k3sup                                    volk
k9s                                      volta
kamel                                    vpn-slice
katago                                   vroom
kcgi                                     vsearch
kcptun                                   vsh
keptn                                    vtk@8.2
kertish-dfs                              vulture
keydb                                    waffle
khiva                                    wangle
kickstart                                wapm
killswitch                               wasm-pack
klee                                     wasm3
ko                                       wasmer
kona                                     wayland
kondo                                    wayland-protocols
kotlin-language-server                   webify
ksync                                    wgcf
kube-linter                              wllvm
kubecm                                   wolfmqtt
kubergrunt                               wownero
kubevela                                 wren
kubie                                    wren-cli
kumactl                                  x86_64-elf-gdb
lab                                      xbitmaps
ladspa-sdk                               xcb-proto
lanraragi                                xcb-util
latexindent                              xcb-util-cursor
latino                                   xcb-util-image
lc0                                      xcb-util-keysyms
ldpl                                     xcb-util-renderutil
leaf                                     xcb-util-wm
leaf-proxy                               xcbeautify
leakcanary-shark                         xcinfo
libaio                                   xclogparser
libbsd                                   xcprojectlint
libcap                                   xdpyinfo
libcap-ng                                xinput
libcbor                                  xkeyboardconfig
libcouchbase@2                           xorgproto
libcpuid                                 xorgrgb
libdeflate                               xray
libdmx                                   xterm
libdrm                                   xtrans
libfido2                                 xxh
libfontenc                               yh
libfs                                    yj
libfuse                                  ykdl
libgccjit                                youtube-dlc
libgnt                                   youtubedr
libhandy                                 yq@3
libice                                   yubikey-agent
libirecovery                             z.lua
libmd                                    zenith
libmnl                                   zim
libnetfilter-queue                       zlib-ng
libnetworkit                             zoxide
libnfnetlink                             zsh-async
libnsl                                   zsh-vi-mode
libolm                                   zsh-you-should-use
liboqs
==> Updated Formulae
Updated 4758 formulae.
==> Renamed Formulae
elasticsearch@6.8 -> elasticsearch@6
glibmm@2.64 -> glibmm@2.66
gst-validate -> gst-devtools
gtk+4 -> gtk4
ht-rust -> xh
interactive-rebase-tool -> git-interactive-rebase-tool
jfrog-cli-go -> jfrog-cli
kde-extra-cmake-modules -> extra-cmake-modules
kde-karchive -> karchive
kde-kdoctools -> kdoctools
kde-ki18n -> ki18n
kde-threadweaver -> threadweaver
kibana@6.8 -> kibana@6
libsasl2 -> cyrus-sasl
minizip2 -> minizip-ng
mkl-dnn -> onednn
now-cli -> vercel-cli
pangomm@2.42 -> pangomm@2.46
prest -> prestd
pyqt5 -> pyqt@5
qt5 -> qt@5
==> Deleted Formulae
python ✔                   elasticsearch@2.4          openjdk@12
python@2 ✔                 elasticsearch@5.6          ori
apache-zeppelin            fmsx                       pgplot
arx                        fstar                      pijul
atlassian-cli              geant4                     residualvm
avian                      ghc@8.2                    rmtrash
baidupcs-go                gmediaserver               sflowtool
biogeme                    gnome-builder              sshrc
boost@1.55                 gobby                      stlviewer
boost@1.59                 godep                      syncthing-inotify
camlp4                     highlighting-kate          tomee-jax-rs
cargo-completion           i386-elf-grub              unp64
ck                         jpcsp                      unrar
cless                      kibana@5.6                 unravel
compcert                   lastfmfpclient             urbit
confluent-platform         llvm@6                     woboq_codebrowser
crc                        lumo                       wpscan
cryptopp                   marathon-swift             wu
curl-openssl               meson-internal             xspin
deis                       mldonkey                   xu4
deisctl                    mysql-connector-c++@1.1    zpython
djmount                    neal
dtrx                       open-cobol
==> New Casks
7777
8bitdo-ultimate-software
8x8-meet
ableton-live-intro10
ableton-live-lite10
ableton-live-standard10
ableton-live-suite10
abyssoft-teleport
accordance
accurics
affinity-publisher-beta
aio-creator-neo
airbuddy
airtrash
ajour
aldente
aleo-studio
aleph-one
alipay-development-assistant
all-in-one-messenger
alloy
altdeploy
amazon-workdocs-drive
amd-power-gadget
android-studio-preview-beta
android-studio-preview-canary
anka-build-cloud-controller-and-registry
anka-build-cloud-registry
anka-virtualization
anzeigenchef
apparency
arduino-beta
around
arq5
astah-uml
atemosc
atomic-wallet
audacity
audiogridder-plugin
audiogridder-server
audius
aural
auristor-client
avast-secure-browser
avitools
aws-vpn-client
azure-data-studio-insiders
babeledit
badlion-client
balsamiq-wireframes
banksiagui
batteries
battery-buddy
beekeeper-studio
berrycast
betelguese
bigsur-cache-cleaner
binance
bingpaper
blackhole-16ch
blackhole-2ch
blender-lts
bleunlock
bluejeans
bluesnooze
bluetility
bluewallet
blurred
bome-network
boop
boost-note
box-notes
box-tools
breaktimer
brewlet
bricklink-partdesigner
brightness-sync
brooklite
buildsettingextractor
cakebrewjs
calendar-366
calibre4
camera-live
camo-studio
canva
caramba-switcher
cernbox
chatterino
chef-workstation
chirp
cinco
cinderella
circuitjs1
cisco-jabber
clash-for-windows
clashx-pro
classicftp
cleanshot
clicker-for-netflix
clicker-for-youtube
cljstyle
clocker
cloudflare-warp
coconutid
code-composer-studio
codeexpander
codespace
cog
coin-wallet
coinomi-wallet
collabshot
colorchecker-camera-calibration
colorwell
command-pad
conferences
connectmenow
convert3dgui
copytranslator
corona-tracker
corretto11
coscreen
countdown
cryo
curiosity
curseforge
customshortcuts
daedalus-flight
daedalus-mainnet
daedalus-testnet
dangerzone
dash5
datweatherdoe
db-browser-for-sqlite-nightly
ddnet
deadbeef
deadbeef-nightly
deadbolt
decloner
deltachat
deskreen
desktoppr
devbook
deviceinfo
devolo-cockpit
devutils
displays
ditto
dmenu-mac
dnagedcom
dnagedcom-beta
dockmate
dremel-slicer
dropbox-passwords
drovio
dteoh-devdocs
duckstation
duoshao
dyalog
dynobase
eaccess
edenmath
edfbrowser
electerm
electricbinary
electrocrud
electronmail
element
elpki
eme
empoche
energia
epoccam
eset-cyber-security-pro
eudic-es
eul
ev3-classroom
evkey
exifcleaner
f-bar
fabfilter-micro
fabfilter-one
fabfilter-pro-c
fabfilter-pro-ds
fabfilter-pro-g
fabfilter-pro-l
fabfilter-pro-mb
fabfilter-pro-q
fabfilter-pro-r
fabfilter-saturn
fabfilter-simplon
fabfilter-timeless
fabfilter-twin
fabfilter-volcano
fantasy-grounds
fastclicker
fawkes
fellow
figma-beta
filemaker-pro
fing-cli
finisher-fluxx
finisher-micro
finisher-neo
finisher-voodoo
firestormos
fireworks
flrig
flutter
flying-carpet
fm3-edit
fme
foldit
font-smoothing-adjuster
fontgoggles
foobar2000
forticlient-vpn
free42-binary
free42-decimal
freecad-pre
freesurfer
freetube
freeyourmusic
fspy
futubull
fvim
g-desktop-suite
gactions
gather
gdat
gdlauncher
gearboy
gearsystem
geotag-photos-pro
geph
ghdl
giteye
gitfiend
gitpigeon
glance
gluemotion
glyphfinder
goldendict
goldenpassport
google-analytics-opt-out
google-drive
gotomeeting
gplates
grid
grid-clock
guijs
ha-menu
hackintool
hakuneko
hancock
happymac
helo
hermit-crab
hessenbox-da
hey
home-assistant
hookshot
hoststool
hot
ibm-aspera-connect
icestudio
icollections
iconscout
iconset
iina-plus
imarisviewer
imdone
imitone
imobie-m1-app-checker
inav-configurator
infinity
infoflow
intel-psxe-ce-c-plus-plus
intellidock
intellij-idea-ce19
intellij-idea19
internxt-drive
intune-company-portal
ipremoteutility
iriunwebcam
jabt-flow
jamulus
jandi-statusbar
jazzup
jdk-mission-control
jellybeansoup-netflix
jellyfin
jetbrains-space
joshjon-nocturnal
juicebar
julia-lts
katrain
kdiff3
kekaexternalhelper
keysmith
kieler
kiwi-for-gmail
klogg
komet
koodo-reader
kryoflux
ksnip
kui
kyokan-bob
lando-edge
lark
lazy
leela
lens
librepcb
lightform
lightkey
linear-linear
little-navmap
little-snitch4
loaf
local-beta
locationsimulator
locklizard-safeguard-viewer
lofi
logicalshift-zoom
loni-pipeline
lunar-client
lx-music
macdroid
macfuse
machoview
macintoshjs
macjournal
macpass-dev
macx-video
maczip
magicplotpro
magicplotstudent
mailtrackerblocker
marathon-infinity
marathon2
masscode
masterway-note
mater
mathinspector
matterhorn
mcreator
mdimagesizemdimporter
mechvibes
medibangpaintpro
meetingbar
megax
mellow
melonbooksviewer
melonds
memo
memory-clean-3
mendeley
messenger-unofficial
metaimage
mi-beta
mic-drop
micro-sniff
microsoft-auto-update
microsoft-edge
microsoft-outlook
microsoft-remote-desktop
middle
miniforge
miro
mit-app-inventor
mmhmm
mochi
modern-csv
molsoftbrowser
mongodb-realm-studio
mono-mdk-for-visual-studio
moose
morpheus-beta
mouse-fix
mplab-xc16
mplab-xc32
mplab-xc8
mplabx-ide
mqttx
mtgaprotracker
mubu
multi
mumu
munkiadmin
mxsrvs
n1ghtshade
napari
nault
nautilus
naver-whale
neat-reader
netdownloadhelpercoapp
netnewswire-beta
network-radar
nifty
niftyman
nightfall
noisebuddy
nomachine-enterprise-client
noraswitch
nordlocker
nordpass
nordvpn-teams
northernspysoftware-colorpicker
nosql-workbench
nota
noto
nova
now-tv-player
noxappplayer
ntfstool
nuage
nure
objektiv
obs-ndi
obs-virtualcam
obs-websocket
obsidian
offset-explorer
okta-advanced-server-access
old-school-runescape
olympus
omniplan3
omx-ebooks
openaudible
openboard
opencore-configurator
openmtp
openphone
openvpn-connect
openvpn-connect-beta
openzfs-dev
opera-gx
operator
opgg
orca
orka
osculator
osquery
oss-browser
output-factory
packetproxy
padloc
paletro
papers3
parallels14
parallels15
parsify
pathephone
pb
pcoipclient
pdf-over
pdf-reader-pro
perimeter81
phd2
photosrevive
pibar
pictogram
pika
pine
piskel
pitch
pixelorama
plasticscm-cloud-edition
plecs-standalone
pokemon-reborn
pomatez
powershell6
pppc-utility
pragli
prezi-next
prezi-video
privatevpn
privatus
pro-fit
propresenter-beta
propresenter6
prosys-opc-ua-browser
protoio-overflow
prowritingaid
ptpwebcam
publii
purei-play
pushplaylabs-sidekick
pycharm-ce-with-anaconda-plugin
pycharm-with-anaconda-plugin
qgis-ltr
qit
qq-beta
qtum
qtvlm
querypie
quickkeyextension
quickwords
qv2ray
qview
radicle-upstream
raiderio
raspberry-pi-imager
raven-reader
ray
raycast
raze
rcse
realforce
reamp
recaf
redeclipse
redisinsight
redream
refined-github-safari
reflector2
remnote
remote-wake-up
removebg
repoz
residualvm
responsively
retroactive
rhino
ringcentral-classic
ringcentral-phone
ripme
river-sparkle
rolisteam
rotki
runelite
s3stat-setup
scrapp
screen
screenfocus
secretive
sengi
sensei
sentinel
sequel-ace
session
sessionrestore
shearwater-cloud
shutter-encoder
sigdigger
signet
sigviewer
silentknight
silicon
silicon-info
silnite
sim-genie
simplelink-msp432-sdk
simplelink-msp432e4-sdk
simtoolkitpro
sipgate-softphone
sitebulb
sitesucker-pro
sketch-beta
sky-ticket
skychart
slicer-preview
slimhud
slippi-dolphin
smcfancontrol-beta
smultron
snapmotion
snipy
sofa-server
softube-central
solar2d
sonarr-beta
sonobus
sonos-s1-controller
sourcenote
space-saver
spaceman
spark-ar-studio
spectx
spires
spitfire-audio
splayer
spotter
spyder
ssh-config-editor
stack-stack
stageplotpro
starsector
start
stashcat
stats
stems
strange-flesh
strawberry
strawberry-wallpaper
streamlabs-obs
stringz
strongvpn
studiolinkstandalone
subsync
sunloginclient
superslicer
surfshark
swiftbar
swifty
syncalicious
syncroom
syncsettings
syntax-highlight
tandem
tap-forms
tbe
teamviewermeeting
teamwire
techsmith-capture
telavox-flow
tempo
tenable-nessus-agent
tencent-docs
tencent-meeting
tetrio
textbuddy
the-archive
the-unofficial-homestuck-collection
thonny-xxl
thor
thorium
thought-train
tigerjython
timche-gmail-desktop
time-to-leave
timelane
tinkerwell
tip
tmnotifier
toggl-track
toinane-colorpicker
toolreleases
tradingview
transcribe
transnomino
transocks
tribler
trojanx
tunein
twilioquest
twitterrific
twobird
tyme
uberconference
ueli
ultdata
unclack
unclutter
uniflash
unity-appletv-support-for-editor
unity-linux-il2cpp-support-for-editor
unity-macos-il2cpp-support-for-editor
unnaturalscrollwheels
usenapp
utm
utools
utterly
uu-booster
vallum
vb-cable
veepn
via
videofusion
vidl
vidrio
vine-server
vipriser
virtualgl
vmware-fusion-tech-preview
vmware-fusion11
vofa-plus
volanta
voov-meeting
vrew
wannianli
warzone-2100
waterfox-classic
weakauras-companion
webcatalog
webex
webots
webull
winclone
windocd
winx-hd-video-converter
wolfram-engine
wombat
wondershare-uniconverter
workspaces
wormhole
wowup
wxmacmolplt
x-swiftformat
xamarin-workbooks
xattred
xbar
xcodeclangformat
xcodes
xlink-kai
xournal-plus-plus
yesplaymusic
yggdrasil
youtube-downloader
ytmdesktop-youtube-music
yuna
yuque
zappy
zbuc-imgur
zecwallet-lite
zeitgeist
zenbeats
zoom-for-it-admins
zoom-outlook-plugin
zprint
zulu13
zulu15
zulufx
zy-player
==> Updated Casks
Updated 3361 casks.
==> Deleted Casks
0xed                                     lingon-x5
33-rpm                                   lisanet-gimp
ableton-live                             liteswitch-x
ableton-live-standard9                   little-snitch-nightly
adobe-dng-converter                      livechat
alcatraz                                 logoist
alephone                                 loopback1
alice                                    luminetmonitor
aliwangwang                              lunchy
android-studio-preview                   madruby
angular-console                          majestic
anka-flow                                makerbot-print
anvil                                    mammon
anyipsum                                 mamp4
appearin                                 manopen
appshelf                                 manuscripts
argouml                                  master-password
arrayfire                                medleytext
aspera-connect                           mega
autopano-giga                            megahertz-knotes
autopano-pro                             mendeley-desktop
baiduhi                                  microsoft-remote-desktop-beta
balsamiq-mockups                         miro-formerly-realtimeboard
barmaid                                  mist
barxtemp                                 mobile-mouse-server
battery-guardian                         mollyguard
beatport-pro                             mongodb-compass-community
beyond-compare-beta                      mono-mdk516
bforartists                              monogame
bink-player                              moodo
blackhole                                moonitor
blue-jeans                               muzei
blueservice                              muzie
borgbackup                               myworkspace
box-edit                                 near-lock
breeze                                   netbeans-html
brogue                                   netsurf
browser-chooserx                         nimble
callersbane                              noobproof
canary                                   nosql-workbench-for-amazon-dynamodb
canoe                                    noteplan
captur                                   nox-app-player
capture-one                              obinslab-starter
catalina-cache-cleaner                   odio
cathode                                  okapi
cgoban                                   oni
chicken                                  openxcom
chirp-daily                              paste
chitchat                                 pdfinfo
cisdem-pdftoolkit                        peepopen
clementine-latest                        people-plus-content-ip
cloudtv                                  pext-nightly
cocoscreator                             phiewer
colloquy                                 pibakery
colormunki-display                       pins
colorpicker-rcwebcolorpicker             pixi-paint
coronasdk                                podman
coyim                                    powershell60
cracked                                  pphelper
cube                                     privacy-services-manager
cutbox                                   prosys-opc-ua-client
daedalus                                 protonmail-unofficial
daemon-tools                             proxpn
daily-english-listening                  psequel
darwiinremoteosc                         qianqianmusic
dawnlabs-alchemy                         qrfcview
deadbeef-devel                           qtum-qt
delibar                                  qubibox
delta                                    racket-cs
deploystudio                             raptor
desktop-presenter                        raven
diptrace                                 rcdefaultapp
disablemonitor                           readandwrite
disk-sensei                              realm-studio
djay-pro                                 relativewave-form
docear                                   remembear
dofus                                    rhinoceros
dradio                                   ring
dropbox-encore                           ringtones
dropzone                                 riot
eclipse-ptp                              ripit
eclipse-scout                            roblox
eim                                      rocketcake
elektriktrick                            rumpus
enolsoft-chm-view                        safaricookiecutter
eve                                      safarisort
eventstore                               safe-exam-browser
evom                                     scaleft
ezip                                     scope
f-secure-anti-virus                      screentray
facebook-ios-sdk                         semaphor
fastlane                                 sharpshooter
fdr                                      shinhan-ezplus
feeder                                   silverback
feeds                                    simplecap
filemaker-pro-advanced                   simpless
findings                                 sleepyhead
flash-ppapi                              slicer-nightly
font-cica                                softu2f
fractal-bot                              sopcast
futuniuniu                               soundnode
gambit                                   sourcetree-alpha
gfortran                                 spectacularity
ghost                                    spotify-notifications
ghostlab                                 spyder-py2
gifs                                     stamp
gislook                                  station
glip                                     strongvpn-client
glueprint                                subsmarine
gog-downloader                           sugarsync
gom-player                               surge2
google-hangouts                          sus-inspector
google-nik-collection                    tagalicious
google-notifier                          tap
gpsdump                                  teamspeak-client
grip                                     teamsql
hab                                      telegram-alpha
hackety-hack                             texstudio-beta
haskell-for-mac                          textricator
hex-fiend-beta                           tftpserver
hider                                    the-hit-list
hipchat                                  thorn-writing
hockey                                   tiat
hook                                     tinyumbrella
hostbuddy                                toggl
hyperion-download-manager                toggl-beta
ichm                                     toggl-dev
iconping                                 trailrunner
iina-nightly                             twelf
imaging-edge                             ukrainian-typographic-keyboard
imazing-mini                             uniconverter
imgur                                    unity-vuforia-ar-support-for-editor
intelliscape-caffeine                    universalmailer
interface-inspector                      use-engine
invisorql                                validator-sac
iphoney                                  veonim
iringg                                   veraview
irip                                     vmware-remote-console
java                                     watts
java11                                   webex-teams
jedict                                   webponize
jeromelebel-mongohub                     whatsapp-pocket
jing                                     wineskin-winery
jmetrik                                  wko
joshaven-winbox                          wondershare-player
kafka-tool                               workflowy-beta
kekadefaultapp                           x48
kindlegen                                xact
kitabu                                   xmrouter
kiwi-for-g-suite                         yabumi
kode54-cog                               yandexradio
kompozer                                 yourkit-java-profiler
kube-solo                                youview
leanpub                                  yyets
levelator                                zoomus-outlook-plugin
lightpaper

==> Downloading https://homebrew.bintray.com/gdbm-1.19.catalina.bottle.tar.gz
##O#- #                                                                       
curl: (22) The requested URL returned error: 403 Forbidden
Trying a mirror...
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm-1.19.catalina.bottle.tar.g
==> Downloading from https://github.com/-/v2/packages/container/package/homebrew
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "gdbm"
Download failed: https://ghcr.io/v2/homebrew/core/gdbm-1.19.catalina.bottle.tar.gz

Exited with code exit status 1
CircleCI received exit code 1

### What did you expect to happen?

The command to successfully install Httpie. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install httpie
```

**Comment by Bo98** [comment]
> `Last commit: 1 year, 4 months ago`

This is why. Your version of Homebrew is extremely out of date.

**Comment by jrista** [comment]
It starts out that way, yes. However it upgrades itself first when we install, and only after that upgrade has occurred does it run into the error.

**Comment by Bo98** [comment]
I've found one issue relating to auto-updates (`brew update` works fine), which I've opened #11126 for.

Unfortunately, it won't help your case since it's a bug in the update process.

Therefore either Circle CI need to update their very old install, or you need to add an explicit `brew update` step since only the implicit updates experience the described issue.

**Comment by jrista** [comment]
Ok...Thank you for the update. Yeah, we started to think that the automatic update wasn't quite working. We ended up just switching back to `curl` instead of using `httpie` to get around the problem for now.
