### ISSUE TITLE
unclear usage what disabled fuse

### ISSUE THREAD

**Issue by glensc** [Homebrew/brew#11132]
### What were you trying to do (and why)?

`brew install squashfuse`

### What happened (include all command output)?

```
➔ brew install squashfuse
Error: squashfuse has been disabled because it requires FUSE!
```

### What did you expect to happen?

package installed. but what the 'disabled' message means? package as not installed?

### Step-by-step reproduction instructions (by running `brew` commands)

But if I do `brew edit squashfuse` i see there was change:

```diff
  on_macos do
-    deprecate! date: "2020-11-10", because: "requires FUSE"
-    depends_on :osxfuse
+    disable! date: "2021-04-08", because: "requires FUSE"
  end
```

- https://github.com/Homebrew/homebrew-core/commit/3e55d8bc2745bb0dfd5ae1fd80266c67ddc561c0

what I read out that it requires fuse, but fuse is present and installed:

```
$ brew search osxfuse
==> Casks
osxfuse ✔

If you meant "osxfuse" specifically:
It was migrated from homebrew/core to homebrew/cask.
You can access it again by running:
  brew tap homebrew/cask
And then you can install it by running:
  brew install --cask osxfuse
```

why would the formula disabled if it just depends on osxfuse formula/cask?
```

**Comment by MikeMcQuaid** [comment]
> why would the formula disabled if it just depends on osxfuse formula/cask?

We are no longer supporting formulae that depend on this cask because it's not open source software and we won't install it in our CI as a result.

**Comment by glensc** [comment]
Found PR with the reasoning:
- https://github.com/Homebrew/homebrew-core/pull/64491

----

it would help a lot if the brew would print message pointing to the discussion.

because really, users do not know your internals and policies, so this message is not helpful for them:

> Error: squashfuse has been disabled because it requires FUSE!

better would be to:

> Error: squashfuse has been disabled because it requires osxfuse, which is no longer available on homebrew core, see https://github.com/Homebrew/homebrew-core/pull/64491

**Comment by glensc** [comment]
@MikeMcQuaid can taps continue to use cask dependencies? like:

```rb
depends_on :osxfuse
```

**Comment by glensc** [comment]
https://github.com/Homebrew/homebrew-core/pull/64491 indicates to create taps, but how to specify cask dependency?

```
➔ brew install glensc/tap/squashfuse
Error: glensc/tap/squashfuse: Unsupported special dependency :osxfuse
```

**Comment by glensc** [comment]
Tried:

```
depends_on "osxfuse"
```

**FAIL**:
```
$ brew install glensc/tap/squashfuse
==> Installing squashfuse from glensc/tap
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula with the name "osxfuse" (dependency of glensc/tap/squashfuse).
Found a cask named "osxfuse" instead. Try
  brew install --cask osxfuse

$ brew install --cask osxfuse
Warning: Cask 'osxfuse' is already installed.

To re-install osxfuse, run:
  brew reinstall osxfuse
```

**Comment by carlocab** [comment]
You can just remove the `depends_on :osxfuse`. If you want the formula to check for a fuse install, see

https://github.com/Homebrew/brew/issues/9401
https://github.com/borgbackup/homebrew-tap
https://github.com/gromgit/homebrew-fuse

**Comment by gromgit** [comment]
@glensc I'm surprised it works for you. That's only ever been used in _cask_ definitions, and when testing with the following formula:
```
class Afuse2 < Formula
  desc "Automounting file system implemented in userspace with FUSE"
  homepage "https://github.com/pcarrier/afuse/"
  url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/afuse/afuse-0.4.1.tar.gz"
  sha256 "c6e0555a65d42d3782e0734198bbebd22486386e29cb00047bc43c3eb726dca8"
  license "GPL-2.0-only"

  bottle do
    root_url "https://github.com/gromgit/homebrew-fuse/releases/download/afuse-mac-0.4.1"
    sha256 cellar: :any, big_sur:  "d14a7e51b8d3fd8c7b3419ab06011e5e14c89b6d8c8f46dbe66b80ea3c97fa1f"
    sha256 cellar: :any, catalina: "bf5f4add8d2e8a2c9ad50e2508771f3c51fded35c21f7a23cf95b364e98f9c7a"
    sha256 cellar: :any, mojave:   "577023bd06623a90ca245be88fbb49041a71cc1e4852195dc5d9d3b2bbdaf617"
  end

  depends_on "pkg-config" => :build
  depends_on cask: "macfuse"
  depends_on :macos

  def install
    system "./configure", "--disable-dependency-tracking", "--prefix=#{prefix}"
    system "make", "install"
  end

  test do
    assert_match "FUSE library version", pipe_output("#{bin}/afuse --version 2>&1")
  end
end
```
even `brew info afuse2` errors out with:
```
Error: afuse2: Unsupported special dependency :cask
```

**Comment by glensc** [comment]
@gromgit indeed, I found it worked with this cask:
- https://github.com/trinitronx/homebrew-pcloud/blob/f4f2408416e55716833ef2a3dafe528011364981/Casks/pcloud-drive.rb#L59

and I assumed it works the same for Formula. my bad I did not perform actual testing as it might have broken my existing install.
