### ISSUE TITLE
curl: (22) The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by chenpinganguo** [Homebrew/brew#11148]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: bc9b98aa0ba777889218ac51f67ccc76b0be6a28
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 91c19159ac5d492a51b22099b4ba7d6ceaba5dd8
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Your Xcode (12.3) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.
```

### 

I ran `brew update` and am still able to reproduce my issue.
I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to download some packages

### What happened (include all command output)?

input：
brew install php

output：
Updating Homebrew...
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/apr-1.7.0_2.big_sur
==> Downloading from https://homebrew.bintray.com/apr-1.7.0_2.big_sur.bottle.tar
#=#=-#  #
curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://ghcr.io/v2/homebrew/core/apr-1.7.0_2.big_sur.bottle.tar.
==> Downloading from https://github.com/-/v2/packages/container/package/homebrew
#=#=-#  #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "apr"
Download failed: https://ghcr.io/v2/homebrew/core/apr-1.7.0_2.big_sur.bottle.tar.gz

### What did you expect to happen?

I want to download php

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install php
```

**Comment by carlocab** [comment]
Can you `unset HOMEBREW_BOTTLE_DOMAIN` and try again?

**Comment by chenpinganguo** [comment]
> 您可以`unset HOMEBREW_BOTTLE_DOMAIN`再试一次吗？

OK, thank you very much
