### ISSUE TITLE
Add option to bump-formula-pr to specify using an organization fork of homebrew-core

### ISSUE THREAD

**Issue by brendongo** [Homebrew/brew#11143]
### Provide a detailed description of the proposed feature

Adding a flag to `brew bump-formula-pr` to specify which organization to fork homebrew-core in. I propose adding `--organization STRING`. This optional flag will use the specified organization when creating/looking up where to fork homebrew-core and create a PR to homebrew-core as originating from this organization fork instead of a fork in the personal namespace.

### What is the motivation for the feature?

I have an org fork of homebrew-core: https://github.com/returntocorp/homebrew-core but the
bump-formula-pr action defaults to my personal fork: https://github.com/brendongo/homebrew-core it would be easier for collaborators in the org to fix the PR if it came from the organization fork instead of the personal one.

### How will the feature be relevant to at least 90% of Homebrew users?

Not sure will affect most homebrew users but happy to make the PR myself if the maintainers are fine with this functionality.

The Github API used in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github.rb#L122 allows for an optional organization parameter in the request body: https://docs.github.com/en/rest/reference/repos#create-a-fork. 

Modifications would then need to be made to the check_fork_exits function https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github.rb#L125 because it assumes right now that the forked repo is always under the users namespace.

### What alternatives to the feature have been considered?

Manually creating the PR from the organization fork instead of using brew bump-formula-pr

**Comment by MikeMcQuaid** [comment]
Makes sense. We'd review a PR for this.

**Comment by dawidd6** [comment]
Can take it. Should be done tonight.
