### ISSUE TITLE
Don't download the same endpoint multiple times

### ISSUE THREAD

**Issue by alexbowers** [Homebrew/brew#11172]
### Provide a detailed description of the proposed feature

When installing `microsoft-excel` it uses the download link: 

https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4

When installing `microsoft-word` it uses the download link:

https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4

These 2 links are the same, however they download for each of the installs, and the download is _really slow_.

### What is the motivation for the feature?

Reduce bandwidth and improve speed.

### How will the feature be relevant to at least 90% of Homebrew users?

I haven't checked how many different casks have the same endpoint, but at least 2 Microsoft Office ones do, and this would drastically improve performance for these endpoints; and I imagine a lot of people install microsoft office via Homebrew.

### What alternatives to the feature have been considered?

It could either be done via caching; or if the endpoint is the same for multiple, perhaps show a list of available packages from that download to install them at the same time; something like:

```
Select software to install:

[x] Microsoft Office Excel
[  ] Microsoft Office Word
[  ] Microsoft Office X
[  ] Microsoft Office Y
[  ] Microsoft Office Z
```

Where you choose all the ones you want.

The reason for this is that, while you can install `microsoft-office` that installs _all_ of the software, which I do not want.

**Comment by TheThreeBody** [comment]
=====>>>>>>>>>>>>  brew cleanup should be run automatically #4760

how stupid idea can human think out this!

**Comment by alexbowers** [comment]
Not sure what the relevance of that ticket is to this feature request?

**Comment by Rylan12** [comment]
I, personally, am not super familiar with the caching system we have but I do know that the sha256 is part of the cached file's filename, so I don't think it would be overly difficult to do a quick check to see if another file in the cache directory has the same checksum. We already have the checksum stored in the formula so no need to even bother keeping a database of urls and their cached downloads or anything like that.

The part that might be more challenging is handling `brew cleanup` on those shared files. We might want to create a copy of that cached file for each formula that uses it. That way, `brew cleanup` doesn't need to check whether the given file is used by any formulae other than the one specified in the filename. That would mean storing the same file twice (or more) which is still a tad inefficient but it should give at least a speed improvement for downloads which would definitely be nice in those few cases.

**Comment by alexbowers** [comment]
It would be no more inefficient copying that file over than what currently happens by downloading it twice so I’m a fan of that implementation of it means that it is more likely to be stable and reduce potential issues

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Bo98** [comment]
We already have caching but it doesn't apply here as the URLs are _not_ the same.

One is:

https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Excel_16.48.21041102_Installer.pkg

and the other is:

https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Word_16.48.21041102_Installer.pkg

**Comment by nandahkrishna** [comment]
I get why the issue was filed though: when `brew install`ing these Casks, the URLs are truncated (this is intentional behaviour) and so it may seem like they're the same.

**Comment by carlocab** [comment]
Yep. But I think `brew` already does what's requested here. For example:
```
❯ brew fetch -s petsc
==> Downloading https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.15.0.tar.gz
######################################################################## 100.0%
Downloaded to: /Users/carlocab/Library/Caches/Homebrew/downloads/b7f17976cec19c701d600996246954b2b8b53d74873b99b21199d88abbe54abf--petsc-lite-3.15.0.tar.gz
SHA256: ac46db6bfcaaec8cd28335231076815bd5438f401a4a05e33736b4f9ff12e59a
❯ brew fetch -s petsc-complex
==> Downloading https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.15.0.tar.gz
Already downloaded: /Users/carlocab/Library/Caches/Homebrew/downloads/b7f17976cec19c701d600996246954b2b8b53d74873b99b21199d88abbe54abf--petsc-lite-3.15.0.tar.gz
SHA256: ac46db6bfcaaec8cd28335231076815bd5438f401a4a05e33736b4f9ff12e59a
```
