### ISSUE TITLE
Launchpad folders support

### ISSUE THREAD

**Issue by JulyIghor** [Homebrew/brew#11176]
### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to organize my apps in Launchpad folders

### What happened (include all command output)?

App removed from a Launchpad  folder and placed outside of it on every update via brew

### What did you expect to happen?

Expected brew cask apps to stay in a Launchpad folders after updates

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1) Install brew cask app
2) Put cask installed app to a Launchpad folder
3) Install that app update via brew update
4) App being removed from a Launchpad folder and placed outside
```

**Comment by carlocab** [comment]
Sounds like https://github.com/Homebrew/homebrew-cask/issues/102721.

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/issues/102721

Please always fill out the issue template. You didn't here.
