### ISSUE TITLE
More specific feedback when `brew audit` fails for bad URLs

### ISSUE THREAD

**Issue by cdayjr** [Homebrew/brew#11183]
### Provide a detailed description of the proposed feature

When `brew audit` fails due to a specific field, printing out which field would be ideal. It may do this already for certain failures, but in the specific case of pulling a URL it was just telling me the URL returned a 404 and it wasn't clear that the 404 was related to the `homepage` field specifically.

### What is the motivation for the feature?

I was creating a formula with a private GitHub repository as the homepage for a private tap and it was failing pulling a URL and because I was using the repository as the source for the formula it wasn't clear that it had to do with the home page.

```
$ brew audit cdayjr/private/private --new-formula
cdayjr/private/private:
  * The URL https://github.com/cdayjr/private is not reachable (HTTP status code 404)
Error: 1 problem in 1 formula detected
```

I was able to trace this down to the `--online` flag specifically by trying different flags, but it still wasn't totally clear that this had something to do with the `homepage` field.

### How will the feature be relevant to at least 90% of Homebrew users?

It'd save a lot of mostly aimless troubleshooting to get feedback about what field is failing when `brew audit` fails.

### What alternatives to the feature have been considered?

Additional documentation may help, it should be possible to update https://docs.brew.sh/Formula-Cookbook#fill-in-the-homepage to mention that the homepage must be publicly accessible. But ideally the feedback for failure should be in the tool when it fails.

Maybe detecting if it's a private repo before the homepage check would help in my specific use-case, but for other kinds of URLs that could fail I still think the feedback would be more helpful.

**Comment by MikeMcQuaid** [comment]
> I was creating a formula with a private GitHub repository as the homepage for a private tap and it was failing pulling a URL and because I was using the repository as the source for the formula it wasn't clear that it had to do with the home page.

Good idea! We'd accept a PR to improve this messaging.

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/pull/11203
