### ISSUE TITLE
brew update falsely succeeds when homebrew core current branch is not master

### ISSUE THREAD

**Issue by ssbarnea** [Homebrew/brew#11194]
### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 3.1.2-55-gd89eda0
ORIGIN: https://github.com/Homebrew/brew
HEAD: d89eda09abbeae907eb88bd6d01dc9cde7ff0e19
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d48d1c6e558bbf67eb32700e227f6070f05c010a
Core tap last commit: 10 days ago
Core tap branch: fix/mk
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.TLFRo7V1ul/org.xquartz:0
HOMEBREW_EDITOR: edit
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

### `brew doctor` output

```shell
Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I did run `brew update` and assumed it did the right thing but the new formulas were not available.

I then remembered that a couple of weeks ago I proposed a new formula and the process for doing so involved branching the repository and adding the new formular.

Since that moment, I was using that development branch and `brew update` only pulled changes from master, but not affecting current branch.

### What happened (include all command output)?

I am aware that `brew doctor` was able to identify the problem, I want to state that this is a problem that needs to be displayed when brew update or upgrade is running, not only on doctor command.

The main reason for this is due to the fact that the lack of updates is not effectively an error, i would call it more of a "false-positive update".  Command succeeded, without any warning but you still do not have any updates available.

For this reason, I think it would very useful to display the same warning when update runs, so user will know to switch to default branch.

### What did you expect to happen?

I would expect either a failure to update when current branch is not master or at least a warning message explaining that you are using a branch, so update would not make the changes available to you.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
cd $(brew --repo homebrew/core)
git branch -c my-branch
brew update
# wonder why you are not able to upgrade refreshed formulas
git checkout master
# now you can upgrade formulas
```
```

**Comment by carlocab** [comment]
This is by design. It would be pretty bad for you to be working on a development branch only for `brew update` to stomp all over the changes you've made there.

I don't think that `brew update` needs to return a non-zero exit code or display a message when you use it and you don't have the `master` branch checked out either.

**Comment by mislav** [comment]
This behavior bit me in the past as well as I am regularly a `homebrew/core` contributor, but I don't always remember to switch back to the main branch. I would welcome a warning on stderr that `brew update` was prevented to do the desired operation in the repository of the tap. The fact that it continues without error nor diagnostic messages seems like a pitfall that occasionally prevents folks from upgrading.

**Comment by carlocab** [comment]
Being on a different branch shouldn't prevent `brew update` from doing anything -- it's designed to update your local `master` branches (or otherwise default branches for any local taps that don't use `master`).

Maybe an opt-in (or opt-out?) warning when you do `brew update` and you're not actually on a default branch could work here, but I'm not sure that's far enough removed from what `brew doctor` already tells you.

**Comment by ssbarnea** [comment]
@carlocab I do not see any disadvantage about including a warning when you do "update", and current branch is not master. It would save hours for every brew contributor. I bet almost every contributor was fooled by this at some point, it is very easy to forget restoring the branch.

IMHO, if possible, the same code/warning that is used by doctor should be used by update, no need to implement the same check twice.

**Comment by Rylan12** [comment]
To offer another perspective: as a developer, I sometimes like to keep a repo on a separate branch intentionally for a little bit (usually to test some new feature out) and a warning on every `brew update` can be quite annoying. Also, there are plenty of times when I want to run `brew update` to update some taps but am currently doing some work on a separate branch in a different tap. So for me, personally, a warning update would be inconvenient in most cases.

I may not be correctly evaluating your use case, but I think that in many cases with Homebrew contributions, you can use `git stash` and `git cherry-pick` (or other `git` tooling) to easily move changes/commits between branches if you realize that you were working on the wrong branch.

**Comment by carlocab** [comment]
> I do not see any disadvantage about including a warning when you do "update", and current branch is not master.

Oh, but I do. I do `brew update` when one of my Homebrew-related repositories is not on the default branch quite often, and I would find it extremely annoying to see this warning every time.

> It would save hours for every brew contributor.

It shouldn't need to, because `brew` contributors should know to run `brew doctor` if they have problems. That should take minutes, not hours.

**Comment by ssbarnea** [comment]
With all due respect, I think you are missing the point here: if you run update and it passed, you do not know you have a problem. It can take days or weeks until you realise that update did not made anything new available. It is not clear when brew is running from master or not, that is the source of the confusion.

It took me two weeks to discover that, i ended up creating a false bug report on gh tool because their instructions to update gh did not work. 

How about just letting this ticket closed and see if others endup voting for it. If it gets enough votes maybe there is a sign that the decision to not display a warning should be reconsidered?

**Comment by MikeMcQuaid** [comment]
> How about just letting this ticket closed and see if others endup voting for it. If it gets enough votes maybe there is a sign that the decision to not display a warning should be reconsidered?

That's not how we run our issue tracker, sorry.

I would be game to have an (opt-out) message printed by `brew update` if we're staying on a non-`master` branch. I'd review a PR.
