### ISSUE TITLE
Error: zssh: no bottle available!

### ISSUE THREAD

**Issue by li-zeyuan** [Homebrew/brew#11193]
### `brew config` output

```shell
➜  ~ brew config
HOMEBREW_VERSION: 3.1.2-53-g844f15e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 844f15edec8c85b9903678fd07b493c237ce24f7
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8d2b00790da47b29ce83968f7a272797f6e6a22c
Core tap last commit: 16 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.cloud.tencent.com/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false
➜  ~
```

### `brew doctor` output

```shell
➜  ~ brew doctor
Your system is ready to brew.
➜  ~
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to install zssh
芯片：Apple M1
系统版本：macOS 11.2.3 (20D91)
内核版本：Darwin 20.3.0

### What happened (include all command output)?

➜  tool brew install zssh
Error: zssh: no bottle available!
You can try to install from source with:
  brew install --build-from-source zssh
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

### What did you expect to happen?

zssh installation was successful

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
➜  tool brew update
Already up-to-date.
➜  tool brew doctor
Your system is ready to brew.
➜  tool brew install zssh
Error: zssh: no bottle available!
You can try to install from source with:
  brew install --build-from-source zssh
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
➜  tool
```

**Comment by MikeMcQuaid** [comment]
This is not an error.
