### ISSUE TITLE
Private repo GitHub releases for bottles

### ISSUE THREAD

**Issue by cdayjr** [Homebrew/brew#11218]
### Provide a detailed description of the proposed feature

Currently, if you have a bottle saved at a private repo's GitHub release, you'll get something similar to the following:

```
==> Installing boatswain from cdayjr/private
==> Downloading https://github.com/cdayjr/private/releases/download/1.0.0/private-1.0.0.catalina.bottle.tar.gz

curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "private"
Download failed: https://github.com/cdayjr/private/releases/download/1.0.0/private-1.0.0.catalina.bottle.tar.gz
```

404 response is the standard GitHub response of trying to access a private repo's resource.

If possible, it'd be nice if the GitHub API was used to make the download instead, authenticating like brew does for other GitHub URLs like source repository URLs and tap repositories.

### What is the motivation for the feature?

I'd like to use brew for some proprietary software that I don't want to distribute to the public right now.

### How will the feature be relevant to at least 90% of Homebrew users?

Users who wish to use brew to distribute private software would be able to do so. This probably isn't applicable to most people.

### What alternatives to the feature have been considered?

The other features of brew work fine with a private repository, so the formula can be installed via compiling the source code each time. Alternatively, just making the repo public can work around this.

**Comment by carlocab** [comment]
Writing a [custom download strategy](https://docs.brew.sh/Formula-Cookbook#specifying-the-download-strategy-explicitly) for your formula is probably what you need here.

**Comment by cdayjr** [comment]
> Writing a [custom download strategy](https://docs.brew.sh/Formula-Cookbook#specifying-the-download-strategy-explicitly) for your formula is probably what you need here.

Does that work for bottles?

I've used that before for downloading and installing a binary instead of the repo, but I have concerns about doing that when it comes to supporting different systems / architectures. Might not matter though.

**Comment by carlocab** [comment]
Hm, yes, I was thinking it would work for `root_url`, but now that you've made me think twice about it perhaps not.

I imagine it would be reasonable for bottle downloads to support download strategies somehow, though.

**Comment by MikeMcQuaid** [comment]
We'll review pull requests for this. We aren't particularly interested in the non-open-source workflows so it may not be something that we'll include, I can't promise anything here.
