### ISSUE TITLE
Ability to download release artifacts from self hosted github

### ISSUE THREAD

**Issue by kplimack** [Homebrew/brew#11217]
### Provide a detailed description of the proposed feature

The downloading code seems built for cloud-hosted github, not private installs at different URLs (https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github.rb)

Even with a custom strategy like `GitHubPrivateRepositoryReleaseDownloadStrategy`, updating the `download_url` does not seem to be effective.

### What is the motivation for the feature?

private homebrew tap's on private self-hosted github

### How will the feature be relevant to at least 90% of Homebrew users?

It wont.  But there would be more enterprise usage of homebrew if this was supported

### What alternatives to the feature have been considered?

/shrug

**Comment by kplimack** [comment]
I guess its not too bad to monkey patch
```
module GitHub
  API_URL = "https://api.whatever-I-want.com"
end
```

**Comment by carlocab** [comment]
This feature sounds very similar to #11218.

I think the answer here is the same: https://github.com/Homebrew/brew/issues/11218#issuecomment-824759529

**Comment by kplimack** [comment]
Could we add a variable for the api url instead of closing this ?

**Comment by carlocab** [comment]
Sorry, but that's not how we use our issue tracker. As noted in the answer I linked to, we'll review a pull request for this.
