### ISSUE TITLE
Cross-platform `all` bottles: shebangs

### ISSUE THREAD

**Issue by Bo98** [Homebrew/brew#11227]
### Provide a detailed description of the proposed feature

One key difference between macOS and Linux is how we use system Perl (and other scripting languages) on macOS but use brewed Perl on Linux.

This leads to different shebangs in some cases, with macOS pointing to `/usr/bin/perl` and Linux pointing to `HOMEBREW_PREFIX/opt/perl/bin/perl`.

In order to achieve cross-platform bottles, we could use keg-relocation logic to replace the shebangs with `@@HOMEBREW_PERL@@` which can be replaced with the correct shebang at pour time.

### What is the motivation for the feature?

Achieving cross-platform `all` bottles where possible.

### How will the feature be relevant to at least 90% of Homebrew users?

Formulae which have `all` bottles can be installed on any platform without having to build from source - rather than be limited to just what we run CI on.

### What alternatives to the feature have been considered?

An alternative is to stop using system Perl and use brewed Perl universally.

**Comment by iMichka** [comment]
> An alternative is to stop using system Perl and use brewed Perl universally.

If I remember well, Apple plans to drop all scripting languages (like ruby, Python, ...). Don't know what is the fate of system perl. On the other hand they started providing Python 3 through the CLT, so their way of doing things is not super consistent.

**Comment by Bo98** [comment]
Yeah they do plan to do something, albeit not very clearly. They say "future versions of macOS won’t include scripting language runtimes by default, and might require you to install additional packages."

"Additional packages" might refer to the CLT, but this would indeed still be a concern for us since we do support the no-devtools case.

**Comment by MikeMcQuaid** [comment]
> In order to achieve cross-platform bottles, we could use keg-relocation logic to replace the shebangs with `@@HOMEBREW_PERL@@` which can be replaced with the correct shebang at pour time.

👍🏻 

How/why does this happen, is it just `uses_from_macos` related? If so, perhaps something more generic could be done to use these `uses_from_macos` lines to replace system dependencies with Homebrew ones in these cases?

> If I remember well, Apple plans to drop all scripting languages (like ruby, Python, ...).

They've announced it but I wouldn't bet on it happening for a good while. While we still have system libraries/languages: let's use them. That's kinda why Homebrew originally came into creation.

**Comment by Bo98** [comment]
> How/why does this happen, is it just `uses_from_macos` related? If so, perhaps something more generic could be done to use these `uses_from_macos` lines to replace system dependencies with Homebrew ones in these cases?

Pretty much yes.

`ExtUtils::MakeMaker` will detect itself what perl executable is being run, and in other cases `rewrite_shebang` also does something similar to use `/usr/bin/perl` if we have `uses_from_macos` and `HOMEBREW_PREFIX/opt/perl/bin/perl` otherwise.

**Comment by MikeMcQuaid** [comment]
Ah, this is pretty much only a thing because of `rewrite_shebang`, right? I think in that case it'd be reasonable to only handle those cases (or store enough state so that we know we need to fix up those cases when we do rewrite shebangs).

**Comment by Bo98** [comment]
> this is pretty much only a thing because of `rewrite_shebang`, right?

Perl's `ExtUtils::MakeMaker` also does it.

**Comment by Bo98** [comment]
This was addressed in #11286.
