### ISSUE TITLE
Cross-platform `all` bottles: perllocal and packlist

### ISSUE THREAD

**Issue by Bo98** [Homebrew/brew#11228]
### Provide a detailed description of the proposed feature

`ExtUtils::MakeMaker` installs a packlist and a perllocal.pod to a platform-specific directory: `lib/perl5/darwin-thread-multi-2level`.

We should pass `NO_PACKLIST=1` and `NO_PERLLOCAL=1` to `Makefile.PL` to prevent these files from being created. A method could be created (e.g. `std_perl_makemaker_args`) to do this.

However, this requires a newer `ExtUtils::MakeMaker` (6.75_01) than what ships with Mojave (6.66), so we might want some other helper methods to aid with this.

### What is the motivation for the feature?

Achieving cross-platform `all` bottles where possible.

### How will the feature be relevant to at least 90% of Homebrew users?

Formulae which have `all` bottles can be installed on any platform without having to build from source - rather than be limited to just what we run CI on.

### What alternatives to the feature have been considered?

Instead of resourcing an updated `ExtUtils::MakeMaker`, an alternative is to stop using system Perl and use brewed Perl universally, which is bundled with a more recent `ExtUtils::MakeMaker`. This would also address #11227.

In any case, it is still desirable to pass `NO_PACKLIST=1` and `NO_PERLLOCAL=1` as standard.

**Comment by MikeMcQuaid** [comment]
> Instead of resourcing an updated `ExtUtils::MakeMaker`, an alternative is to stop using system Perl and use brewed Perl universally, which is bundled with a more recent `ExtUtils::MakeMaker`. This would also address #11227.
> 
> In any case, it is still desirable to pass `NO_PACKLIST=1` and `NO_PERLLOCAL=1` as standard.

I think we should do this on Mojave and earlier but not on Catalina or newer.
