### ISSUE TITLE
I am trying to install virt-manager but getting errors

### ISSUE THREAD

**Issue by vishalybhatia28** [Homebrew/brew#11226]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: d89eda09abbeae907eb88bd6d01dc9cde7ff0e19
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dae145a633065636eb652767dcb3e3535dff3409
Core tap last commit: 19 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

### `brew doctor` output

```shell
brew doctor output is also weird.

Error: undefined method `name' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:256:in `block in initialize'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:255:in `map'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:255:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:485:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:485:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:374:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:417:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:394:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:739:in `block in check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:738:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:738:in `check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to install virt-manager on my mac. Below are the errors:

brew install virt-manager
Error: undefined method `name' for nil:NilClass
Please report this issue:
https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:256:in `block in initialize'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:255:in `map'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:255:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:485:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:485:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:374:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:638:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:634:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:634:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:303:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:131:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

### What happened (include all command output)?

I am stuck at one place only.

### What did you expect to happen?

I expected to install virt-manager

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
trying to install brew install virt-manager
```

**Comment by gromgit** [comment]
What's the output of `brew readall`?

**Comment by vishalybhatia28** [comment]
out for brew readall is nothing...

**Comment by vishalybhatia28** [comment]
Vishals-MacBook-Pro:~ vishalbhatia$ brew readall
Vishals-MacBook-Pro:~ vishalbhatia$

**Comment by gromgit** [comment]
Assuming you haven't changed any Homebrew formulae locally, run `brew update-reset` then `brew doctor` again.

**Comment by zachauten** [comment]
@vishalybhatia28 That formula doesn't exist in homebrew-core, but maybe you could find a tap for it.

**Comment by vishalybhatia28** [comment]
> Assuming you haven't changed any Homebrew formulae locally, run `brew update-reset` then `brew doctor` again.

here is the result.

Vishals-MacBook-Pro:~ vishalbhatia$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> /Users/vishalbhatia/.bash_profile
Vishals-MacBook-Pro:~ vishalbhatia$

**Comment by vishalybhatia28** [comment]
> @vishalybhatia28 That formula doesn't exist in homebrew-core, but maybe you could find a tap for it.

@ zachauten, thanks, but I am one day old with this brew. How do I find a tap for it?

**Comment by vishalybhatia28** [comment]
Actual issues start from below once I apply command brew install virt-manager

==> /usr/local/Cellar/virt-manager/2.2.1_3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed
Last 15 lines from /Users/vishalbhatia/Library/Logs/Homebrew/virt-manager/02.pip:
  Found link https://files.pythonhosted.org/packages/03/41/6da553f689d530bc2c337d2c496a40dc9c0fdc6481e5df1f3ee3b8574479/pip-20.3.tar.gz#sha256=9ae7ca6656eac22d2a9b49d024fc24e00f68f4c4d4db673d2d9b525c3dea6e0e (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3
  Found link https://files.pythonhosted.org/packages/ab/11/2dc62c5263d9eb322f2f028f7b56cd9d096bb8988fcf82d65fa2e4057afe/pip-20.3.1-py2.py3-none-any.whl#sha256=425e79b20939abbffa7633a91151a882aedc77564d9313e3584eb0416c28c558 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.1
  Found link https://files.pythonhosted.org/packages/cb/5f/ae1eb8bda1cde4952bd12e468ab8a254c345a0189402bf1421457577f4f3/pip-20.3.1.tar.gz#sha256=43f7d3811f05db95809d39515a5111dd05994965d870178a4fe10d5482f9d2e2 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.1
  Skipping link: yanked for reason: <none given>: https://files.pythonhosted.org/packages/3d/0c/01014c0442830eb38d6baef0932fdcb389279ce74295350ecb9fe09e048a/pip-20.3.2-py2.py3-none-any.whl#sha256=8d779b6a85770bc5f624b5c8d4d922ea2e3cd9ce6ee92aa260f12a9f072477bc (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*)
  Skipping link: yanked for reason: <none given>: https://files.pythonhosted.org/packages/51/63/86e147c44335b03055e58a27c791d94fff4baaf08d67852f925ab9b90240/pip-20.3.2.tar.gz#sha256=aa1516c1c8f6f634919cbd8a58fc81432b0fa96f421a97d05a205ee86b07c43d (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*)
  Found link https://files.pythonhosted.org/packages/54/eb/4a3642e971f404d69d4f6fa3885559d67562801b99d7592487f1ecc4e017/pip-20.3.3-py2.py3-none-any.whl#sha256=fab098c8a1758295dd9f57413c199f23571e8fde6cc39c22c78c961b4ac6286d (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.3
  Found link https://files.pythonhosted.org/packages/ca/1e/d91d7aae44d00cd5001957a1473e4e4b7d1d0f072d1af7c34b5899c9ccdf/pip-20.3.3.tar.gz#sha256=79c1ac8a9dccbec8752761cb5a2df833224263ca661477a2a9ed03ddf4e0e3ba (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.3
  Found link https://files.pythonhosted.org/packages/27/79/8a850fe3496446ff0d584327ae44e7500daf6764ca1a382d2d02789accf7/pip-20.3.4-py2.py3-none-any.whl#sha256=217ae5161a0e08c0fb873858806e3478c9775caffce5168b50ec885e358c199d (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.4
  Found link https://files.pythonhosted.org/packages/53/7f/55721ad0501a9076dbc354cc8c63ffc2d6f1ef360f49ad0fbcce19d68538/pip-20.3.4.tar.gz#sha256=6773934e5f5fc3eaa8c5a44949b5b924fc122daa0a8aa9f80c835b4ca2a543fc (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.4
  Found link https://files.pythonhosted.org/packages/de/47/58b9f3e6f611dfd17fb8bd9ed3e6f93b7ee662fb85bdfee3565e8979ddf7/pip-21.0-py3-none-any.whl#sha256=cf2410eedf8735fd842e0fecd4117ca79025d7fe7c161e32f8640ed6ebe5ecb9 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0
  Found link https://files.pythonhosted.org/packages/9e/24/bc928987f35dd0167f21b13a1777c21b9c5917c9894cff93f1c1a6cb8f3b/pip-21.0.tar.gz#sha256=b330cf6467afd5d15f4c1c56f5c95e56a2bfb941c869bed4c1aa517bcb16de25 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0
  Found link https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl#sha256=37fd50e056e2aed635dec96594606f0286640489b0db0ce7607f7e51890372d5 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0.1
  Found link https://files.pythonhosted.org/packages/b7/2d/ad02de84a4c9fd3b1958dc9fb72764de1aa2605a9d7e943837be6ad82337/pip-21.0.1.tar.gz#sha256=99bbde183ec5ec037318e774b0d8ae0a64352fe53b2c7fd630be1d07e94f41e5 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0.1
Given no hashes to check 161 links for project 'pip': discarding no candidates
Removed build tracker: '/private/tmp/pip-req-tracker-djnnjoeg'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
virt-manager: command not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/169
virt-manager broken on Big Sur after minor update https://github.com/jeffreywildman/homebrew-virt-manager/issues/170
bump virt-manager/view-viewer and deps https://github.com/jeffreywildman/homebrew-virt-manager/pull/166
Virt-manager wont build. Update to libvirt-python https://github.com/jeffreywildman/homebrew-virt-manager/pull/171
Error installing virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/145
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62

**Comment by zachauten** [comment]
@vishalybhatia28 Could you open a thread in the [discussions thread](https://github.com/Homebrew/discussions/discussions)? I'd be glad to answer some of your questions but this section is for bugs in the homebrew cli client, and this is not a bug.

It looks like you found a tap at https://github.com/jeffreywildman/homebrew-virt-manager. But as the output you included says, it's a third party tap and not maintained by the Homebrew team, so you'll have to open an issue on that repo if there's a problem with it.
>If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

**Comment by twocountriestrus** [comment]
Gracias 


Enviado desde Yahoo Mail para iPhone


El jueves, abril 22, 2021, 9:20 a. m., Adrian Ho ***@***.***> escribió:




What's the output of brew readall?
