### ISSUE TITLE
Some entries missing from 3.1.3 changelog

### ISSUE THREAD

**Issue by scpeters** [Homebrew/brew#11245]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.3-91-gfb7d19c
ORIGIN: https://github.com/Homebrew/brew
HEAD: fb7d19c6618f90b30c463fa854ae241fb5e0bacc
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 62a49388cde09c034267c7ee07d5f6bbd6b9b36f
Core tap last commit: 7 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 6.0 build 600
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 5.4.0-70-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.5 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 8.4.0
/usr/bin/ruby: 2.5.1
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.0.0/bin/bundle
  /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.0.0/bin/bundler
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was looking at the GitHub release [changelog for 3.1.3](https://github.com/Homebrew/brew/releases/tag/3.1.3) and I noticed some entries are missing. As of this writing, the release notes have the following content:

- [rubocops/patches: GitLab patches should use .diff](https://github.com/Homebrew/brew/pull/10760) (@jonchang)
- [rubocops/patches: remove autocorrection of some `url`s](https://github.com/Homebrew/brew/pull/11170) (@nandahkrishna)
- [build(deps-dev): bump html-proofer from 3.19.0 to 3.19.1 in /docs](https://github.com/Homebrew/brew/pull/11184) (@Homebrew)
- [Update maintainers, manpage and completions.](https://github.com/Homebrew/brew/pull/11188) (@Homebrew)
- [bump-cask-pr: add --fork-org flag](https://github.com/Homebrew/brew/pull/11181) (@Homebrew)
- [Update maintainers, manpage and completions.](https://github.com/Homebrew/brew/pull/11173) (@Homebrew)
- [bump-formula-pr: add --fork-org flag](https://github.com/Homebrew/brew/pull/11158) (@dawidd6)
- [Always take latest item in `Sparkle` strategy.](https://github.com/Homebrew/brew/pull/11171) (@reitermarkus)
- [formula: add `-DBUILD_TESTING=OFF` to `std_cmake_args`](https://github.com/Homebrew/brew/pull/11159) (@Bo98)
- [rubocops/patches: Fix quoting of the patch `url` when autocorrecting](https://github.com/Homebrew/brew/pull/11169) (@issyl0)
- [Revert "dev-cmd/bottle: set uid/gid."](https://github.com/Homebrew/brew/pull/11166) (@Homebrew)
- [dev-cmd/bottle: set uid/gid.](https://github.com/Homebrew/brew/pull/11165) (@MikeMcQuaid)
- [dev-cmd/bottle: revert filename in JSON to use single dash always](https://github.com/Homebrew/brew/pull/11163) (@Bo98)
- [Bottle reproducibility tweaks](https://github.com/Homebrew/brew/pull/11150) (@MikeMcQuaid)
- [brew.sh: add workaround for old auto-updates](https://github.com/Homebrew/brew/pull/11162) (@Bo98)
- [Service: generate systemd unit file](https://github.com/Homebrew/brew/pull/11133) (@SMillerDev)
- [sorbet: Update RBI files.](https://github.com/Homebrew/brew/pull/11161) (@Homebrew)
- [Always take first item in `Sparkle` strategy.](https://github.com/Homebrew/brew/pull/11146) (@reitermarkus)
- [software_spec: fix bottle domain fallback handling](https://github.com/Homebrew/brew/pull/11157) (@Bo98)
- [build: set SOURCE_DATE_EPOCH](https://github.com/Homebrew/brew/pull/11141) (@Bo98)
- [bin/brew: repair style](https://github.com/Homebrew/brew/pull/11152) (@hyuraku)
- [settings: use quieter `system_command!`](https://github.com/Homebrew/brew/pull/11139) (@MikeMcQuaid)
- [dev-cmd/bottle: fix INSTALL_RECEIPT appearing in changed_files](https://github.com/Homebrew/brew/pull/11145) (@Bo98)

### What happened (include all command output)?

I noticed that the 3.1.3 tag points to https://github.com/Homebrew/brew/commit/d89eda09abbeae907eb88bd6d01dc9cde7ff0e19, which is the merge commit for https://github.com/Homebrew/brew/pull/11187, which isn't in the list.

### What did you expect to happen?

I thought it would include that pull request.

I'm guessing the `brew release` command was run to create a draft release before all the pull requests were merged? Perhaps we need to update our release workflow to ensure the changelog is up to date just before publishing the release. It's easy enough to update the release notes after the fact, but I wanted to create this for visibility.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Running `puts ReleaseNotes::generate_release_notes('3.1.2', '3.1.3', markdown: true)` in a `brew irb` session gives the following:

- [formula: add rpath helper method](https://github.com/Homebrew/brew/pull/11187) (@carlocab)
- [search: properly deprecate `brew search --cask`](https://github.com/Homebrew/brew/pull/11182) (@Rylan12)
- [rubocops/patches: GitLab patches should use .diff](https://github.com/Homebrew/brew/pull/10760) (@jonchang)
- [rubocops/patches: remove autocorrection of some `url`s](https://github.com/Homebrew/brew/pull/11170) (@nandahkrishna)
- [build(deps-dev): bump html-proofer from 3.19.0 to 3.19.1 in /docs](https://github.com/Homebrew/brew/pull/11184) (@Homebrew)
- [Update maintainers, manpage and completions.](https://github.com/Homebrew/brew/pull/11188) (@Homebrew)
- [bump-cask-pr: add --fork-org flag](https://github.com/Homebrew/brew/pull/11181) (@Homebrew)
- [Update maintainers, manpage and completions.](https://github.com/Homebrew/brew/pull/11173) (@Homebrew)
- [bump-formula-pr: add --fork-org flag](https://github.com/Homebrew/brew/pull/11158) (@dawidd6)
- [Always take latest item in `Sparkle` strategy.](https://github.com/Homebrew/brew/pull/11171) (@reitermarkus)
- [formula: add `-DBUILD_TESTING=OFF` to `std_cmake_args`](https://github.com/Homebrew/brew/pull/11159) (@Bo98)
- [rubocops/patches: Fix quoting of the patch `url` when autocorrecting](https://github.com/Homebrew/brew/pull/11169) (@issyl0)
- [Revert "dev-cmd/bottle: set uid/gid."](https://github.com/Homebrew/brew/pull/11166) (@Homebrew)
- [dev-cmd/bottle: set uid/gid.](https://github.com/Homebrew/brew/pull/11165) (@MikeMcQuaid)
- [dev-cmd/bottle: revert filename in JSON to use single dash always](https://github.com/Homebrew/brew/pull/11163) (@Bo98)
- [Bottle reproducibility tweaks](https://github.com/Homebrew/brew/pull/11150) (@MikeMcQuaid)
- [brew.sh: add workaround for old auto-updates](https://github.com/Homebrew/brew/pull/11162) (@Bo98)
- [Service: generate systemd unit file](https://github.com/Homebrew/brew/pull/11133) (@SMillerDev)
- [sorbet: Update RBI files.](https://github.com/Homebrew/brew/pull/11161) (@Homebrew)
- [Always take first item in `Sparkle` strategy.](https://github.com/Homebrew/brew/pull/11146) (@reitermarkus)
- [software_spec: fix bottle domain fallback handling](https://github.com/Homebrew/brew/pull/11157) (@Bo98)
- [build: set SOURCE_DATE_EPOCH](https://github.com/Homebrew/brew/pull/11141) (@Bo98)
- [bin/brew: repair style](https://github.com/Homebrew/brew/pull/11152) (@hyuraku)
- [settings: use quieter `system_command!`](https://github.com/Homebrew/brew/pull/11139) (@MikeMcQuaid)
- [dev-cmd/bottle: fix INSTALL_RECEIPT appearing in changed_files](https://github.com/Homebrew/brew/pull/11145) (@Bo98)
```

**Comment by scpeters** [comment]
sorry for all the @-mentions

**Comment by carlocab** [comment]
Huh, I thought that commit wasn't included in the latest release tag, which is why I was sitting on https://github.com/Homebrew/homebrew-core/issues/75458. Guess I can go do that now.

**Comment by Rylan12** [comment]
If you run `brew ruby -rrelease_notes -e 'puts ReleaseNotes.generate_release_notes("3.1.2", "3.1.3", markdown: true)'` you'll get what the release notes algorithm woudl output now between those tags. Here it is:

```console
$ brew ruby -rrelease_notes -e 'puts ReleaseNotes.generate_release_notes("3.1.2", "3.1.3", markdown: true)'
- [formula: add rpath helper method](https://github.com/Homebrew/brew/pull/11187) (@carlocab)
- [search: properly deprecate `brew search --cask`](https://github.com/Homebrew/brew/pull/11182) (@Rylan12)
- [rubocops/patches: GitLab patches should use .diff](https://github.com/Homebrew/brew/pull/10760) (@jonchang)
- [rubocops/patches: remove autocorrection of some `url`s](https://github.com/Homebrew/brew/pull/11170) (@nandahkrishna)
- [build(deps-dev): bump html-proofer from 3.19.0 to 3.19.1 in /docs](https://github.com/Homebrew/brew/pull/11184) (@Homebrew)
- [Update maintainers, manpage and completions.](https://github.com/Homebrew/brew/pull/11188) (@Homebrew)
- [bump-cask-pr: add --fork-org flag](https://github.com/Homebrew/brew/pull/11181) (@Homebrew)
- [Update maintainers, manpage and completions.](https://github.com/Homebrew/brew/pull/11173) (@Homebrew)
- [bump-formula-pr: add --fork-org flag](https://github.com/Homebrew/brew/pull/11158) (@dawidd6)
- [Always take latest item in `Sparkle` strategy.](https://github.com/Homebrew/brew/pull/11171) (@reitermarkus)
- [formula: add `-DBUILD_TESTING=OFF` to `std_cmake_args`](https://github.com/Homebrew/brew/pull/11159) (@Bo98)
- [rubocops/patches: Fix quoting of the patch `url` when autocorrecting](https://github.com/Homebrew/brew/pull/11169) (@issyl0)
- [Revert "dev-cmd/bottle: set uid/gid."](https://github.com/Homebrew/brew/pull/11166) (@Homebrew)
- [dev-cmd/bottle: set uid/gid.](https://github.com/Homebrew/brew/pull/11165) (@MikeMcQuaid)
- [dev-cmd/bottle: revert filename in JSON to use single dash always](https://github.com/Homebrew/brew/pull/11163) (@Bo98)
- [Bottle reproducibility tweaks](https://github.com/Homebrew/brew/pull/11150) (@MikeMcQuaid)
- [brew.sh: add workaround for old auto-updates](https://github.com/Homebrew/brew/pull/11162) (@Bo98)
- [Service: generate systemd unit file](https://github.com/Homebrew/brew/pull/11133) (@SMillerDev)
- [sorbet: Update RBI files.](https://github.com/Homebrew/brew/pull/11161) (@Homebrew)
- [Always take first item in `Sparkle` strategy.](https://github.com/Homebrew/brew/pull/11146) (@reitermarkus)
- [software_spec: fix bottle domain fallback handling](https://github.com/Homebrew/brew/pull/11157) (@Bo98)
- [build: set SOURCE_DATE_EPOCH](https://github.com/Homebrew/brew/pull/11141) (@Bo98)
- [bin/brew: repair style](https://github.com/Homebrew/brew/pull/11152) (@hyuraku)
- [settings: use quieter `system_command!`](https://github.com/Homebrew/brew/pull/11139) (@MikeMcQuaid)
- [dev-cmd/bottle: fix INSTALL_RECEIPT appearing in changed_files](https://github.com/Homebrew/brew/pull/11145) (@Bo98)
```

The two missing entries are both seen in this output which is also what's used to generate the changelog. The `brew release` command, when run, creates a new draft release and automatically fills in the changelog using `ReleaseNotes.generate_release_notes latest_version, "origin/HEAD", markdown: true`. My guess is that what's happened here is that `brew release` was run before those last two PRs were merged so they weren't included in the release notes. By the time the release was published, though, they had been merged (and the changelog had not been updated).

**Comment by MikeMcQuaid** [comment]
> My guess is that what's happened here is that `brew release` was run before those last two PRs were merged so they weren't included in the release notes. By the time the release was published, though, they had been merged (and the changelog had not been updated).

Sounds about right. Closing and will pay closer attention to this in future.
