### ISSUE TITLE
Homebrew Update on MacOS Big Sur 11.3 (Apple Silicon) causes system to Crash and Enter a Boot Loop

### ISSUE THREAD

**Issue by rishitc** [Homebrew/brew#11273]
### `brew config` output

```shell
Not recoverable as the system is stuck in a boot loop.
```

### `brew doctor` output

```shell
Not recoverable as the system is stuck in a boot loop.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to update the packages installed on my system, so I was trying to update the formulae and Homebrew itself. I was following the instructions as per this link [Brew FAQ](https://docs.brew.sh/FAQ)

### What happened (include all command output)?

My system details, are:
1. **System Name:** MacBook Pro 13
2. **Processor:** Apple M1

I had recently updated to macOS Big Sur 11.3 and ran ```brew update```. Here are the series of events that took places after that,
1. The terminal showed that brew was trying to access a few different folders for the different packages I had installed on my system.
    - However, for every folder, it was trying to access, the permission to access that folder was denied automatically each time.
    - The system did not ask me whether I wanted to allow or deny permissions for brew to access those folders.
2. The system froze
3. The system's screen became completely pink for a second or two 
4. The system automatically switched off and is since then stuck in a boot loop.
    - I've tried entering ```Safe Mode``` after switching my system off and on again *(i.e. long pressing the power button)*, but it fails to enter ```Safe Mode```

I think that Big Sur 11.3 has changed a few filesystem access permissions and/or also some system files (configurations) as after the update I had a ```Relocated Items``` folder which had a file called ```group.system_default``` inside ```Configuration/private/etc```.

I want to report this issue here as executing ```brew update``` was the last thing I did on my system before it got stuck in this boot loop and to the best of my knowledge, it was the only task that was not operating as expected (see point **1.**) before the failure of my system occurred.

I hope this issue gets some traction as many people who update to macOS Big Sur 11.3 on their systems and use brew might run into this issue. I hope that my issue was just an exception, but I would request the maintainers to look into this issue; whether it can affect other machines or not.

If you have any other question about the issue that affected my system. Please do reply to this issue and I would be glad to help out to provide more details. I'll keep updating this issue as I try to recover my system.

Thanks,
Rishit.C

P.S. I have filed this GitHub issue on my old Linux System, which is now my daily driver until I can get my MacBook, working again.

**References:**
- [**Relocated Items** folder which had a file called ```group.system_default``` inside Configuration/private/etc](https://apple.stackexchange.com/questions/419519/installing-macos-11-3-creates-a-relocated-items-nosync-with-changes-to-private-e)

### What did you expect to happen?

The system would update the formulae and Homebrew. I was following the instructions as per this link [Brew FAQ](https://docs.brew.sh/FAQ)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Update your Mac to Big Sur 11.3 (preferably try this on a system running the Apple M1)
2. Open the terminal
3. Run brew update
```

**Edit:**
1. Updated the steps in the section: *Step-by-step reproduction instructions (by running `brew` commands)*

**Comment by carlocab** [comment]
I'm sorry to hear about your issue, but I don't think this is a problem caused by `brew`. We updated Homebrew ARM CI to Big Sur 11.3 the other night (along with a manual `brew update` after that), and discovered zero problems while doing so. Our ARM nodes have also been building formulae just fine since then.

**Comment by rishitc** [comment]
Hi,
Which versions of ```brew``` have been tested on the ARM CI? Would it be possible that if I'm running a slightly older version of ```brew```, I could have run into this problem? (I don't recall the exact version of ```brew``` I was using, but looking at the releases, on GitHub, I feel mine was slightly old).

Any information regarding this would be of great help, as it would help me eliminate potential reasons that could have caused this.

Thanks,
Rishit.C

**Comment by carlocab** [comment]
Homebrew CI runs `brew` off the tip of the master branch.

**Comment by rishitc** [comment]
Hi,
Any chances that running an older version of ```brew``` could cause this issue? Because when I ran ```brew update```, the program did try to access different files on my system and it kept showing that the **permission was denied**  (also I was not asked by the system, whether to grant or deny permission). This was quite surprising and not the excepted behaviour, and what leads to believe that a bug in the older version of ```brew``` cause this error. 


I'm trying to understand what happened to my system and the **permission-denied-during-file-access** is something I'm unable to make sense of.


Is there any possibility of a bug in an older version of ```brew``` that could cause this? Any information would be useful.


Thanks,
Rishit.C

**Comment by rishitc** [comment]
@MikeMcQuaid I request you to keep this issue open, as there is no reason established yet as to why the file permissions were being denied each time while ```brew``` tried to access the packages' files on my system while running ```brew update```.

I'm still trying to recover my system, but I have low hopes that I would be able to recover any useful data for the maintainers, as the system may have to recovered using DFU (I lose my personal data on the system as well, but that's not the point of this thread).

@MikeMcQuaid Requesting you to please keep this issue open,

Thanks,
Rishit.C

**Comment by Bo98** [comment]
If `brew update` is having permission problems, it's very likely the case that the permisisons were _already_ broken - perhaps by something else outside `brew` (we regularly see people run tools that "fix" permissions of some directories that end up actually breaks things). To my knowledge, at no point in the `brew update` process is `chmod` invoked, beyond what Git may internally do.

Because `brew` doesn't run under sudo, it can't touch very much on system level either and thus should be impossible to cause a boot loop.

**Comment by MikeMcQuaid** [comment]
@rishitc This is not a Homebrew problem, sorry.
