### ISSUE TITLE
Perl shebangs should be pinned to a specific version on macOS

### ISSUE THREAD

**Issue by Bo98** [Homebrew/brew#11275]
### Provide a detailed description of the proposed feature

macOS 11.3 changed the default Perl from 5.28 to 5.30. This broke a number of formulae that are built against system Perl 5.28.

Since `/usr/bin/perl5.30` exists on all Big Sur versions, I suggest we stop using `/usr/bin/perl` for shebangs and use the versioned Perl binary instead.

This will also fix an issue where Homebrew formulae break when the user changes the default Perl version themselves (macOS has a `defaults` property that can do this). For example, Catalina defaults to 5.18 but does support switching the default to 5.28.

The question mostly is how to handle this. If we want to force doing this, then this means effectively making `rewrite_shebang detected_perl_shebang, file` happen automatically in the `Cleaner` or similar. This would thus mean it is no longer necessary to rewrite shebangs in the formulae themselves. This however comes with the strong assumption that all the files are designed to be run locally and aren't some remote script to run on a server.

This is linked very closely to #11227 so it makes sense to find a solution here (if we can't do general automatic shebang rewrites then we probably can't solve #11227). The only difference being that what we do here needs to apply to all installs (including builds from source) while #11227 only concerns the bottle.

### What is the motivation for the feature?

Doing this means formulae are less prone to break if the default Perl changes, either by Apple or by the user.

### How will the feature be relevant to at least 90% of Homebrew users?

Broken formulae are unusable and useless to users.

### What alternatives to the feature have been considered?

* Using brewed Perl instead.
* Bumping minimum macOS to 11.3 and continue to rely on whatever `/usr/bin/perl` is. Note however that this won't actually fully fix the issue. The user can still change the default Perl themselves (which I suspect some might end up doing in this case).

**Comment by Bo98** [comment]
(I'm happy to do some work on this - mainly opened this for tracking.)

**Comment by MikeMcQuaid** [comment]
> * The user can still change the default Perl themselves (which I suspect some might end up doing in this case).

That we never saw anyone doing this before tends to make me think it won't happen. That said, definitely in favour of the "proper" solution here if possible.

**Comment by rprimus** [comment]
Sun May 23 08:26:10 BST 2021

Hi @Bo98 , @MikeMcQuaid .

I've noticed some strange behaviour on my system after:
```
/usr/local/Cellar/perl/5.34.0 (4,629 files, 96.9MB) *
  Poured from bottle on 2021-05-22 at 05:52:06
```
 and tracked it down to https://github.com/Homebrew/brew/releases/tag/3.1.7 and https://github.com/Homebrew/brew/pull/11286.

All perl 'Apps' - cpan-outdated, cpanm, perlcritic, etc - are no longer using `/usr/local/opt/perl` (or the preferred `/usr/bin/env perl`).  

After a perl upgrade I normally rebuild/reinstall all perl `bundles` in `~/perl5/lib/perl5/darwin-thread-multi-2level/auto/` to match the new version.
This did not work yesterday as cpanm is now using `/usr/bin/perl` (v5.18.4) to rebuild all the bundles, however,  perl is now v5.34.0 - causing a binary mismatch:

Using the example code from `Encode::Byte`:
```perl
           use Encode qw/encode decode/;
           $greek = encode("iso-8859-7", $utf8);  # loads Encode::Byte implicitly
           $utf8  = decode("iso-8859-7", $greek); # ditto
```
```sh
: ; perl /tmp/tt.pl
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_apiversion_bootcheck
  Referenced from: /Users/m/perl5/lib/perl5/darwin-thread-multi-2level/auto/Encode/Encode.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_apiversion_bootcheck
  Referenced from: /Users/m/perl5/lib/perl5/darwin-thread-multi-2level/auto/Encode/Encode.bundle
  Expected in: flat namespace

[1]    47695 abort      perl /tmp/tt.pl
```
```
: ; which perl
/usr/local/bin/perl
➜  Encode
: ; perl -v | head -2

This is perl 5, version 34, subversion 0 (v5.34.0) built for darwin-thread-multi-2level
```
```
: ; strings /Users/m/perl5/lib/perl5/darwin-thread-multi-2level/auto/Encode/Encode.bundle | head -14
CMalformed UTF-8 character
UTF-16 surrogate U+%04lX
Code point 0x%lX is not Unicode, may not be portable
Unicode non-character U+%04lX is not recommended for open interchange
ascii
ascii-ctrl
cp1252
iso-8859-1
null
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
Encode.c
v5.18.0
3.10
Encode::utf8::decode
➜  Encode
: ;
```
Any suggestions on the best way to 'fix' this?

**Comment by rprimus** [comment]
Sun May 23 09:15:44 BST 2021

Additionally, everything in `~/perl5/bin` is being built using `/usr/bin/perl`:
```
: ; pwd
/Users/m/perl5/bin
➜  bin
```
```
: ; ls -lat  | ag -i 'may 2' | ag -v 2017
drwxr-xr-x 105 m staff   3360 May 23 09:04 .
-r-xr-xr-x   1 m staff   7013 May 23 09:04 json_xs
-r-xr-xr-x   1 m staff  41663 May 23 08:54 enc2xs
-r-xr-xr-x   1 m staff   2980 May 23 08:54 encguess
-r-xr-xr-x   1 m staff   8271 May 23 08:54 piconv
-r-xr-xr-x   1 m staff   9892 May 23 08:51 shasum
-r-xr-xr-x   1 m staff   9634 May 23 08:51 sha3sum
-r-xr-xr-x   1 m staff    436 May 23 08:48 moose-outdated
-r-xr-xr-x   1 m staff   9993 May 23 08:46 cpanel_json_xs
-r-xr-xr-x   1 m staff   1416 May 23 08:46 pod_cover
-r-xr-xr-x   1 m staff 302729 May 23 08:45 cpanm
-r-xr-xr-x   1 m staff   9079 May 23 07:41 cpan-outdated
-r-xr-xr-x   1 m staff  41013 May 22 17:59 perlcritic
-r-xr-xr-x   1 m staff   4194 May 22 17:45 instmodsh
-r-xr-xr-x   1 m staff 183880 May 22 17:15 perltidy
-r-xr-xr-x   1 m staff   1333 May 22 17:15 podspell
drwxr-xr-x   9 m staff    288 May 22 17:10 ..
-r-xr-xr-x   1 m staff   7138 May 22 11:37 config_data
-r-xr-xr-x   1 m staff  13649 May 22 11:37 prove
-r-xr-xr-x   1 m staff   4981 May 22 11:36 json_pp
➜  bin
: ;
```
```
: ; ls -lat  | ag -i 'may 2' | ag -v 2017 | awk '{print $NF}' | xargs head -1 {}
head: {}: No such file or directory
==> . <==
head: Error reading .

==> json_xs <==
#!/usr/bin/perl

==> enc2xs <==
#!/usr/bin/perl

==> encguess <==
#!/usr/bin/perl

==> piconv <==
#!/usr/bin/perl

==> shasum <==
#!/usr/bin/perl

==> sha3sum <==
#!/usr/bin/perl

==> moose-outdated <==
#!/usr/bin/perl

==> cpanel_json_xs <==
#!/usr/bin/perl

==> pod_cover <==
#!/usr/bin/perl -w

==> cpanm <==
#!/usr/bin/perl

==> cpan-outdated <==
#!/usr/bin/env perl

==> perlcritic <==
#!/usr/bin/perl

==> instmodsh <==
#!/usr/bin/perl -w

==> perltidy <==
#!/usr/bin/perl

==> podspell <==
#!/usr/bin/perl

==> .. <==
head: Error reading ..

==> config_data <==
#!/usr/bin/perl

==> prove <==
#!/usr/bin/perl -w

==> json_pp <==
#!/usr/bin/perl
➜  bin
: ;
```

**Comment by carlocab** [comment]
Possibly related: https://github.com/Homebrew/homebrew-core/issues/77797

**Comment by Bo98** [comment]
3.1.9 has been released to fix this.
