### ISSUE TITLE
Container registry bottle backend with non-ghcr.io URL

### ISSUE THREAD

**Issue by jkenn99** [Homebrew/brew#11287]
### Provide a detailed description of the proposed feature

Add support for brew to use a custom container registry URL to fetch bottles. Essentially, `HOMEBREW_BOTTLE_DOMAIN` but still using the new github packages-style backend.

### What is the motivation for the feature?

I operate a local mirror for bottles using Artifactory. Now that bottles are being downloaded as container images from Github packages, I've created a new container repo in Artifactory for the bottles. I can fetch bottles using my repo fine using podman (i.e. `podman pull myrepo.example.com/homebrew/brew:latest` works fine) but if I set `export HOMEBREW_BOTTLE_DOMAIN=https://myrepo.example.com/v2/homebrew/core` brew tries to fetch the bintray-style .tar.gz bottles instead (i.e. `https://myrepo.example.com/v2/homebrew/core/somepackage.big_sur.bottle.tar.gz`

### How will the feature be relevant to at least 90% of Homebrew users?

It won't, but it is relevant to 100% of users that use `HOMEBREW_BOTTLE_DOMAIN` with a local mirror.

### What alternatives to the feature have been considered?

Open to ideas.

**Comment by MikeMcQuaid** [comment]
Can you try `HOMEBREW_BOTTLE_DOMAIN=docker://myrepo.example.com/v2/homebrew/core` or similar? That may work as-is just now. If it doesn't: I think that's the best route to go down for a pull request. We can't change the default https behaviour for arbitrary domains without breaking normal HTTPS mirrors.

**Comment by Bo98** [comment]
We possibly need to adjust `GitHubPackages::DOCKER_PREFIX` to not include the `ghcr.io` domain.

**Comment by jkenn99** [comment]
I looked at what it would take to get this working and it is turns out to be more than just updating the url regexp. Brew isn't correctly implementing the v2 registry api when it comes to fetching and providing a bearer token, so that would need to be resolved as well. There is a gem for it which may help though.

**Comment by jkenn99** [comment]
> Out of interest, which Gem are you referring to?

https://rubygems.org/gems/docker_registry2 
I just did a quick read through the code so far but it seems like it could provide what is needed.

**Comment by MikeMcQuaid** [comment]
We won't be interested in using that gem given how much is already supported. We would consider adding code to handle non-public/non-GHCR registries if it's minimal enough.

**Comment by jkenn99** [comment]
I'm willing to take a stab at it. 
Essentially what's missing is the precheck step against the `/v2/` endpoint (https://docs.docker.com/registry/spec/api/#base) and acting on the `WWW-Authenticate` header on 401 responses to that.
I'd appreciate some thoughts on where would be best to fit this in. ([CurlGitHubPackagesDownloadStrategy](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/download_strategy.rb#L561)?)

**Comment by Bo98** [comment]
HTTP level stuff usually lives in download strategies so yes I think that makes sense.

I assume this would essentially be trying the download (I don't think you need to change the URL - you should get the header back in any endpoint) and reacting to `WWW-Authenticate`'s realm attribute which gives the token endpoint, with exception to GHCR since the header returned is bogus and you don't need a proper token anyway.

Ideally this would be cached across requests so we don't keep asking for a new token.

**Comment by MikeMcQuaid** [comment]
> I'd appreciate some thoughts on where would be best to fit this in. ([CurlGitHubPackagesDownloadStrategy](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/download_strategy.rb#L561)?)

I'd say you probably want something like `DockerRegistryDownloadStrategy` which you then make `GitHubPackagesDownloadStrategy` inherit from so it can handle the e.g. fixed bearer token.

**Comment by jkenn99** [comment]
I created PR #11339 to resolve this. Getting some local test failures which seem to more likely be caused by my local machine than by my changes, so if someone could kick off the Github Actions tests I'd appreciate it.

**Comment by Vishesh-Gupta** [comment]
Any updates on this? Trying to set up a custom container registry for bottles on artifactory.

**Comment by MikeMcQuaid** [comment]
@Vishesh-Gupta No. I'd suggest asking Artifactory to spend some of the money you pay them to get one of their engineers to work on an updating version of https://github.com/Homebrew/brew/pull/11339

**Comment by yahavi** [comment]
@jkenn99 @MikeMcQuaid @Bo98 @Vishesh-Gupta @technoweenie 
We created #11766 for the support using Artifactory as a proxying remote registry for Homebrew. 
Basically, we think that populating `HOMEBREW_ARTIFACT_DOMAIN` instead of `HOMEBREW_BOTTLE_DOMAIN` is a better idea for some reasons:
1. With that, you can proxy not only the blobs, but also the manifests.
2. To make it work as before on Bintray. See https://jfrog.com/blog/part-ii-artifactory-as-a-caching-mechanism-for-package-managers.
3. It is easier to configure - you just have to configure a Docker remote repository to https://ghcr.io and set `HOMEBREW_ARTIFACT_DOMAIN` to be `<artifactory-url>/<repo-name>`

We also added to the PR the `HOMEBREW_REGISTRY_ACCESS_TOKEN` environment variable to allow configuring non-interactively Artifactory’s access token.

**Comment by MikeMcQuaid** [comment]
@yahavi Sounds sensible from here. Will review PR now.

**Comment by thomvaill** [comment]
Thank you @yahavi for your PR! It really saved us ;)

However, we found some limitations regarding authentication.
I created an issue about this: https://github.com/Homebrew/brew/issues/12574

I suppose we can close this issue now?

**Comment by Jasonnft** [comment]
> ### Provide a detailed description of the proposed feature
> Add support for brew to use a custom container registry URL to fetch bottles. Essentially, `HOMEBREW_BOTTLE_DOMAIN` but still using the new github packages-style backend.
> 
> ### What is the motivation for the feature?
> I operate a local mirror for bottles using Artifactory. Now that bottles are being downloaded as container images from Github packages, I've created a new container repo in Artifactory for the bottles. I can fetch bottles using my repo fine using podman (i.e. `podman pull myrepo.example.com/homebrew/brew:latest` works fine) but if I set `export HOMEBREW_BOTTLE_DOMAIN=https://myrepo.example.com/v2/homebrew/core` brew tries to fetch the bintray-style .tar.gz bottles instead (i.e. `https://myrepo.example.com/v2/homebrew/core/somepackage.big_sur.bottle.tar.gz`
> 
> ### How will the feature be relevant to at least 90% of Homebrew users?
> It won't, but it is relevant to 100% of users that use `HOMEBREW_BOTTLE_DOMAIN` with a local mirror.
> 
> ### What alternatives to the feature have been considered?
> Open to ideas.

**Comment by Jasonnft** [comment]
heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you heyy btch asshole fuck you

**Comment by MikeMcQuaid** [comment]
I think we're far enough on this to close it out. Thanks all!
