### ISSUE TITLE
Allow formula to specify equivalent dependencies

### ISSUE THREAD

**Issue by kevinhwang** [Homebrew/brew#11312]
### Summary

Modify the [`depends_on`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/depends_on.md) stanza in the formula DSL to accept a set of equivalent dependencies, and update `brew` with new behavior accordingly.

### DSL Changes

Example of new DSL:

```ruby
class MyFormula < Formula
  # ...
  depends_on { "corretto", "openjdk",  "oracle-jdk" }
  depends_on { "boringssl", "libressl", "openssl" }
  # ...
end
```

The above example indicates the formula requires two dependencies:

- One of: `corretto` OR `openjdk` OR `oracle-jdk`
- One of: `boringssl` OR `libressl` OR `openssl`

Another way to conceive of this is that a formula dependency can be a named interface or abstract object (e.g., `java`, indicating that this formula needs a JRE / JDK, but any will do), but multiple concrete implementations may satisfy this requirement. The terminology isn't particularly important, but the concept we all probably get.

### Formula lifecycle changes

This would have implications on `brew install` and `brew upgrade` behavior.

E.g., when installing or upgrading formula, brew would consider the dependency satisfied if one or more of the entries in the set was installed. If not, brew would try to install the first one (as a convention, the first could be the default, or declared order could be order of preference).

### What is the motivation for the feature?

Rationale seems pretty straightforward. Right now there's no concept of equivalent dependencies.

If you want to install [`gradle`](https://github.com/Homebrew/homebrew-core/blob/e4f49a7/Formula/gradle.rb) or [`maven`](https://github.com/Homebrew/homebrew-core/blob/e4f49a7/Formula/maven.rb), it will always install [`openjdk`](https://github.com/Homebrew/homebrew-core/blob/7fd84fc/Formula/openjdk.rb). If you already have [`corretto`](https://github.com/Homebrew/homebrew-cask/blob/86d50e5/Casks/corretto.rb) installed as your preferred JRE / JDK, it will still install OpenJDK.

If you then try to install the formula w/ `--ignore-dependencies` to prevent it from installing OpenJDK, it will work until the next time you do a `brew upgrade`, at which point it will install it once it gets to that formula that has `openjdk` declared as a dependency, which will then break your Maven / Gradle install (b/c it'll munge the targets to which the `java` / `javac` wrappers point and the `JAVA_HOME` env var, which confuses Maven / Gradle).

The specifics of Maven and Gradle and how the `java` and `javac` wrappers work on macOS aside, the thing is, Maven doesn't depend on OpenJDK. OpenJDK is one offering that provides an implementation of Java, and that's what Maven depends on.

The same is true of many common libraries., like OpenSSL and its many (often superior) alternatives.

### How will the feature be relevant to at least 90% of Homebrew users?

90% of formulae have dependencies, and many of those dependencies are hardcoded to specific implementations of more general required software.

This would solve the problem of people not being able to use their preferred JRE / JDK or library within the Homebrew system.

**Comment by carlocab** [comment]
A similar feature has been requested before: #11011 The answer is likely the same.

The biggest impediment to something like this is that we lack a way for alternative dependencies to be tested in CI. Casks also don't quite work as dependencies for formulae in Homebrew/core, so such a feature, if implemented, probably still wouldn't allow replacing `openjdk` with a cask.

>it'll munge the targets to which the `java` / `javac` wrappers point and the `JAVA_HOME` env var, which confuses Maven / Gradle

The wrapper scripts for Maven and Gradle shouldn't override your `JAVA_HOME` environment variable. Is that not working for you?

**Comment by MikeMcQuaid** [comment]
> The specifics of Maven and Gradle and how the `java` and `javac` wrappers work on macOS aside, the thing is, Maven doesn't depend on OpenJDK. OpenJDK is one offering that provides an implementation of Java, and that's what Maven depends on.

Maven installed by Homebrew _does_ depend on OpenJDK because that's the Java implementation we've chosen to use. If you wish to _not_ do this: you need to make your own formula in a tap which depends on whatever you want.

We used to have essentially the system you describe. It sucked because you either multiple the testing time by the number of dependency combinations or just don't test these combinations and ever know if they are broken. We're no longer willing to ship conditional options/dependencies that we don't test in CI because they break and lead to a shitty experience.

Sorry!

**Comment by kevinhwang** [comment]
@carlocab:

> The biggest impediment to something like this is that we lack a way for alternative dependencies to be tested in CI.

Could CI not iterate over ea. dependency and test a clean install of that formula with ea. dependency?

> Casks also don't quite work as dependencies for formulae in Homebrew/core, so such a feature, if implemented, probably still wouldn't allow replacing `openjdk` with a cask.

Makes sense, but if one day they can be treated as just another formula, would that then work? It seems like it's moving in that direction, right?

I.e., lately some things seem to indicate that distinction b/w binary formulae and casks are blurring—e.g., you no longer have to do `brew cask ...` or even `brew --cask`, but can just straight up say `brew install corretto` or `brew install google-chrome`. Isn't the distinction slowly blurring? And the idea of treating the two similarly under a more generic concept of `Formula` or whatever does seem attractive from a design standpoint too.

> The wrapper scripts for Maven and Gradle shouldn't override your JAVA_HOME environment variable. Is that not working for you?

So if you try the following, you'll see what I mean:

```shell script
brew uninstall -f maven openjdk
brew install corretto
brew install --ignore-dependencies maven  # We want use our corretto installation
mvn -v # Maven will work, using our corretto installation of Java 👍
```

Now, wait some time for an update to the `maven` formula, and `brew upgrade`, or just `brew reinstall maven` to see it happen immediately. It will install `openjdk` as a dependency.

On doing so, the maven, which before worked fine using corretto, will be reconfigured to rely on openjdk, so that if you try to `brew uninstall --ignore-dependencies openjdk`, `mvn -v` will break with:

```
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

**Comment by MikeMcQuaid** [comment]
> ```shell
> brew install --ignore-dependencies maven  # We want use our corretto installation
> ```

Don't do this. It's not supported and expected to break.

**Comment by kevinhwang** [comment]
@MikeMcQuaid:

> Maven installed by Homebrew _does_ depend on OpenJDK because that's the Java implementation we've chosen to use. If you wish to _not_ do this: you need to make your own formula in a tap which depends on whatever you want.

I'm a bit confused by what you mean by this. Maven as software doesn't depend on OpenJDK. Yes, the current revision of the `maven` formula has a declared dependency on `openjdk`, but that's just due to how the file was initially authored, not based on any intrinsic requirement of the underlying software.

So it's true that maven as installed by Homebrew depends on openjdk, but isn't that the whole point of this request? That it doesn't need to?

What makes OpenJDK more valid than Corretto, or OpenSSL more valid than BoringSSL, or Docker more valid than Podman, or Google's distribution of Kubernetes than K3s? They're all functionally identical and can be substituted and treated as fungible from the perspective of dependents, and there's good reason sometimes to prefer one to the other.

**Comment by MikeMcQuaid** [comment]
> Maven needs _a_ Java distribution, but isn't picky about which one.

Homebrew is picky about which one due to the reasons above.

> What makes OpenJDK more valid than Corretto, or OpenSSL more valid than BoringSSL, or Docker more valid than Podman, or Google's distribution of Kubernetes than K3s?

Homebrew maintainers decided it is the case. If you'd like to change that: we'll review pull requests (with the relevant reasoning).

> They're all functionally identical and can be substituted

This is not universally true. When it's not true: how does this get verified?

> A Homebrew user might prefer one over the other for any number of reasons, incl. security, support, performance characteristics, etc.

They might. They can also create their own formula/tap which does it however they want.

Fundamentally Homebrew users primarily want things to work. When we start allowing formulae to start switching around dependencies: this will sometimes break in ways that are hard to debug and in a way that we do not have the maintainer or CI resources to test and resolve.

**Comment by carlocab** [comment]
> Could CI not iterate over ea. dependency and test a clean install of that formula with ea. dependency?

That requires someone to write the `test-bot` code and get it through a review. Are you willing to work on that?

> Makes sense, but if one day they can be treated as just another formula, would that then work? It seems like it's moving in that direction, right?

Those changes are designed to make `brew` as simple to use as possible for the most common use cases. I don't think switching dependencies falls in that category.

> So if you try the following, you'll see what I mean:
> 
> ```shell
> brew uninstall -f maven openjdk
> brew install corretto
> brew install --ignore-dependencies maven  # We want use our corretto installation
> mvn -v # Maven will work, using our corretto installation of Java 👍
> ```
> 
> Now, wait some time for an update to the `maven` formula, and `brew upgrade`, or just `brew reinstall maven` to see it happen immediately. It will install `openjdk` as a dependency.

This doesn't answer my question though. Do you set `JAVA_HOME`? If you do, you might be setting it wrong. If you don't, then you should set it and `maven` will ignore your `openjdk` install.

**Comment by MikeMcQuaid** [comment]
> That requires someone to write the `test-bot` code and get it through a review. Are you willing to work on that?

Just to avoid anyone doing the work here and being disappointed: CI resources are sufficiently constrained that we are unlikely to do this even if it was done.
