### ISSUE TITLE
problems with new xcode 8 dependency, and a hackish workaround.

### ISSUE THREAD

**Issue by paultopia** [Homebrew/brew#1131]
This isn't really a bug report or a feature request, but an issue with the latest version and a workaround.  

Issue: on update to Sierra, Homebrew starts throwing an error unless user hasn't upgraded to xcode 8.  

Why is this a problem?: For those of us with problems in the xcode department, including: inadequate hard drive space, slow network connections, or just hating the monstrous bloatware that is xcode and being quite happy only compiling the things that can be compiled with the command line tools, this is a big problem.

For example, I have a kind of weird case.  Twice I've suffered massive SSD crashes after trying to upgrade xcode, in both cases I eventually just had to wipe and reinstall. Even to get it to download,  I've repeatedly watched the app store randomly hang, had to do all kinds of dark voodoo with deleting files found by stackoverflow searches, etc. etc. At this point, I've just given up: I have a non-working 7.2.1. install and I'm happy with that, maybe I'll try again when I buy a new computer.

Suggestion: Could this maybe be a warning, rather than an error? Ideally a warning that describes, even in most general terms, what exactly it is that won't compile without an updated full xcode, so that people can make their own decisions on whether losing some subset of the brew recipes is a tradeoff worth making?

My workaround: I found the place in the brew code where this check is made.  It's /usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb 

So I just modified lines 18 and 19 of that file.

old: 

```
        when "10.11" then "8.0"
        when "10.12" then "8.0"
```

new:

```
        when "10.11" then "7.2.1"
        when "10.12" then "7.2.1"
```

Is this a horrendous hack?  Yes.  But it seemed to work for at least my own short-term need. (I needed to install imagemagick.  It installed fine, and the broken dependency that I needed it for got fixed.)

So, if anyone else is having this issue, that might serve as a temporary fix for you too, at your own risk.

**Comment by chdiza** [comment]
In #1097, I said that HB should at least deliver easy instructions on how to revert to the tag before the Xcode-killing change.

There was an idea on that thread, @paultopia, to make HB simply nag rather than die.

Is the CLT package causing similar problems for you?  The latest CLT package should be sufficient to install `imagemagick`.

**Comment by paultopia** [comment]
The current CLT package, in the absence of Xcode 8, seems to be behaving fine for me...

**Comment by zmwangx** [comment]
If you just want a workaround and don't care about getting proper support, set `CI`.

**Comment by DomT4** [comment]
> Why is this a problem?: For those of us with problems in the xcode department, including: inadequate hard drive space, slow network connections, or just hating the monstrous bloatware that is xcode and being quite happy only compiling the things that can be compiled with the command line tools, this is a big problem.

Remove Xcode if you don't intend to use it. We support CLT-only as best as we can, and almost all `xcode` dependencies are `:build` only. There are some notable exceptions, but we try to support CLT-only as widely as possible.

> Suggestion: Could this maybe be a warning, rather than an error?

No. It was a warning, and to be honest I pretty quickly got sick of the default fix for a 10.12 bug reported to us being _"You need to update Xcode. `brew doctor` has warned you about this"_.

This causes both users and us real, significant problems & takes up time that could and should be used solving problems that aren't entirely user configuration based. Apple themselves say do not use Xcode 7.2.1 on 10.12, it isn't supported, it will break stuff if used. We didn't magic up the requirement.

Note that the only configuration that is flagged as of the last tag being cut is running < Xcode 8 on 10.12. That's all.

**Comment by paultopia** [comment]
@DomT4 : 

> Remove Xcode if you don't intend to use it. We support CLT-only as best as we can, and almost all xcode dependencies are :build only. There are some notable exceptions, but we try to support CLT-only as widely as possible.

Hmm.  This is interesting.  Just to clarify: am I right in reading this to mean that: 

1.  there is some subset of the stuff brew does for which Xcode is a real dependency, but that subset is fairly small, and 

2. as long as one is asking brew to carry out tasks for which Xcode isn't a real dependency, it'll happily carry them out *so long as there is no Xcode at all on one's system*, but will throw a fatal error and refuse to carry them out *if there is the wrong Xcode on one's system*?  

If that's true, then at the very least this really needs to be documented in some readily accessible place. For example, the error that I ran into should actually provide this information, so that there aren't hordes of people polluting their poor machines with Xcode 8 and god only knows what nightmarish installation issues and bugs that creates *just to get package management working again when they don't actually need to.*  

If I understood you right, I'll happy submit the trivial PR myself to change the error message.  (I'll also gleefully get rid of Xcode on my own machine and start popping champagne.)  But first I want to make sure that I'm understanding you right. 

The real problem here isn't brew---it's an amazing tool, supported by a wonderful community. The real problem, frankly, is that Xcode is horrible. But it will seriously hurt the brew community if people think, even inaccurately, that they're forced to get their paws on Xcode 8 in order to use brew at all.

**Comment by MikeMcQuaid** [comment]
> there is some subset of the stuff brew does for which Xcode is a real dependency, but that subset is fairly small

Yes.

> The real problem here isn't brew---it's an amazing tool, supported by a wonderful community. The real problem, frankly, is that Xcode is horrible. But it will seriously hurt the brew community if people think, even inaccurately, that they're forced to get their paws on Xcode 8 in order to use brew at all.

This is the same as pretty much all Homebrew's soft dependencies: we'll allow you to install things if they aren't around and only complain if you actually need them. If you have them installed, though, you need to have them be up-to-date to avoid complaining as otherwise things may break. 

We may consider changing our messaging in future but I'd like to see more widespread evidence of this being an issue first.

Thanks for filing the issue and I hope this has helped.
