### ISSUE TITLE
Keg relocation should also relocate `RPATH`s on macOS

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#11329]
### Provide a detailed description of the proposed feature

On macOS, the relocation of kegs does not touch `LC_RPATH` entries in MachO files. This behaviour differs from that on Linux, where `RPATH`s are relocated, and I believe this partly explains why more formulae are relocatable on Linux than on macOS.

I propose that `brew` also apply the existing relocation logic to `LC_RPATH` entries. That is, it should substitute path prefixes in each `LC_RPATH` entry with the appropriate placeholders (e.g. `@@HOMEBREW_PREFIX@@`, `@@HOMEBREW_CELLAR@@`, etc) upon bottling, and substitute those placeholders with the correct prefixes upon pouring.

This complements #10846. Personally, I think this should be implemented first before we do any binary patching.

There is some existing (but, AFAICT, unused) logic in `brew` that clears MachO files of "unused" `RPATH`s:

https://github.com/Homebrew/brew/blob/42ffee75a1245117d25b9e3bfd6e8e51b0cb0ff4/Library/Homebrew/extend/os/mac/keg_relocate.rb#L57-L65

but my (admittedly limited) testing suggests that the test it uses for deciding whether to clear redundant `RPATH`s is incorrect, and actually breaks formulae.

### What is the motivation for the feature?

More relocatable bottles.

### How will the feature be relevant to at least 90% of Homebrew users?

Probably won't be.

### What alternatives to the feature have been considered?

Doing nothing, or just relying fully on binary patching instead.

**Comment by carlocab** [comment]
To be clear, I am willing to work on this (but not immediately). However, I am opening this issue in case this is actually not a good idea for reasons I haven't considered.

CC @sjackman @danielnachun

**Comment by MikeMcQuaid** [comment]
This seems like a good idea given my limited understanding.

**Comment by Bo98** [comment]
This would help with Swift. The current approach I'm doing is deleting the absolute rpath (becuase in the Swift case, it's actually a duplicate of an already existing relative path and thus pointless).

There's an argument that the absolute rpath should be fixed at source, but this sometimes isn't possible and can require patches.

**Comment by Bo98** [comment]
As for `HOMEBREW_RELOCATE_METAVARS`, I agree that should be deleted. It does look like it would cause problems.

**Comment by sjackman** [comment]
Makes sense to me. Thanks, Carlo!

**Comment by danielnachun** [comment]
>Personally, I think this should be implemented first before we do any binary patching

I completely agree, and I actually proposed https://github.com/Homebrew/brew/issues/10846 under the assumption that we were already doing this.  Since we are not, I fully support getting this working before trying to do binary patching on macOS.  

One question that may warrant some further thought: should we be checking if the user is actually running a non-default cellar before doing this?  If they are not, then we end up replacing the old install prefix in the RPATHs with the same one.  This is harmless but arguably unnecessary.  I'm not actually sure we even check that for patching install_names on macOS or RPATHs on Linux.  

When https://github.com/Homebrew/brew/issues/10846 is implemented, install_name/RPATH patching will be mandatory for bottles built with long prefixes because all users will have a different install prefix than the one used to build the bottle.  However, bottles which don't need binary patching could still be built with the default prefix and would only need install_name/RPATH patching when the user is in a non-default cellar.

**Comment by Bo98** [comment]
>  If they are not, then we end up replacing the old install prefix in the RPATHs with the same one.

The bottles contain `@@HOMEBREW_PREFIX@@` - we don't actually scan for `/usr/local` at pour time. A similar practice would be done here where the RPATHs will be replaced with `@@HOMEBREW_PREFIX@@`.

**Comment by carlocab** [comment]
> This would help with Swift.

I've been contemplating this on and off for a little while now, but your comment about making Swift relocatable did encourage me to open this. And this: #11331

**Comment by carlocab** [comment]
I've merged #11331. `RPATH` relocation is currently gated behind `HOMEBREW_RELOCATE_RPATHS`, which I intend to test more thoroughly at https://github.com/carlocab/homebrew-rpath-test.

**Comment by carlocab** [comment]
Tested about 20 formulae, and this doesn't seem to break anything. A minority of the ones I tested become `cellar: :any` after `RPATH` relocation. CC @Bo98 (since you said you wanted updates)

**Comment by MikeMcQuaid** [comment]
@carlocab I'd be 👍🏻 to set this in the homebrew-core workflow once you're happy.

**Comment by Bo98** [comment]
We cannot publish any bottles with that env set as the end users would then need it set in order to use those bottles.

**Comment by MikeMcQuaid** [comment]
@Bo98 Ah, I see. Can we ship just the "do rpath relocations on pouring if needed" parts before the "do rpath relocations on building bottles" parts? If not: this feels like it's going to be potentially pretty risk to ship to ensure users without an easy way to toggle on/off.

**Comment by Bo98** [comment]
If you feel more comfortable doing that then yeah we could do that. The original thoughts discussed in #11331 were to just ship it all with the Perl changes in the next couple days (particularly since I don't see the RPATH changes as risky at all).

**Comment by MikeMcQuaid** [comment]
> If you feel more comfortable doing that then yeah we could do that. The original thoughts discussed in #11331 were to just ship it all with the Perl changes in the next couple days (particularly since I don't see the RPATH changes as risky at all).

Yeh, I think I'd feel more comfortable having a tag that pours correctly 🔜 and then we can ramp up the bottle creation side and release that in a later tag.

**Comment by Bo98** [comment]
Do you want something similar for Perl? I'll try get that done by the end of today. I would still like to ship Perl bottles this weekend.

**Comment by MikeMcQuaid** [comment]
> Do you want something similar for Perl?

No, I'm fine with Perl given the scope there is a bit lower. RPATH stuff has bitten us in the past so I'm more paranoid.

**Comment by carlocab** [comment]
> Can we ship just the "do rpath relocations on pouring if needed" parts before the "do rpath relocations on building bottles" parts?

One way to do this is to set `HOMEBREW_RELOCATE_RPATHS` in the `install` method of `formula_installer`.

**Comment by MikeMcQuaid** [comment]
@carlocab Seems fine for a temporary workaround until we default it to on 👍🏻

**Comment by Bo98** [comment]
Open a PR for that and we can make sure it's included in the next tag.

**Comment by carlocab** [comment]
#11342

**Comment by carlocab** [comment]
`RPATH` relocation is enabled in Homebrew/core. https://github.com/Homebrew/homebrew-core/pull/76875

Keeping this open for now while we still have the environment variables around.

**Comment by carlocab** [comment]
These environment variables are now gone, and will be removed from Homebrew/core in Homebrew/homebrew-core#93327.
