### ISSUE TITLE
Homebrew on Linux installation fails / not useable on linux aarch64 (raspberry pi 4/400)

### ISSUE THREAD

**Issue by cmosetick** [Homebrew/brew#11320]
### `brew config` output

```shell
eval $(~/.linuxbrew/bin/brew shellenv)

which brew
/home/<user>/.linuxbrew/bin/brew

brew config
Error: No Homebrew ruby 2.6.3_2 available for aarch64 processors!
Error: Failed to install Homebrew Portable Ruby and cannot find another Ruby 2.6.3!
If there's no Homebrew Portable Ruby available for your processor:
- install Ruby 2.6.3 with your system package manager (or rbenv/ruby-build)
- make it first in your PATH
- try again

ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [aarch64-linux-gnu]
```

### `brew doctor` output

```shell
brew doctor
Error: No Homebrew ruby 2.6.3_2 available for aarch64 processors!
Error: Failed to install Homebrew Portable Ruby and cannot find another Ruby 2.6.3!
If there's no Homebrew Portable Ruby available for your processor:
- install Ruby 2.6.3 with your system package manager (or rbenv/ruby-build)
- make it first in your PATH
- try again
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Was trying to install Homebrew on linux aarch64. (Raspeberry Pi 4/400)

```
lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1800.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
```

### What happened (include all command output)?

==> Checking for `sudo` access (which may request your password).
==> Select the Homebrew installation directory
- Enter your password to install to /home/linuxbrew/.linuxbrew (recommended)
- Press Control-D to install to /home/<user-name>/.linuxbrew
- Press Control-C to cancel installation
[sudo] password for user-name: 
Homebrew on Linux is only supported on Intel processors!

### What did you expect to happen?

Expected brew installation to complete, run a brew doctor, brew update, brew install.
There is a ruby installation newer than what homebrew claims to need present on the system.

Additionally the official Homebrew documentation says that homebrew is supported on aarch64 on a "best effort" basis.

**The installer script wording in English regarding Intel processors is not well structured.**

**Note** that the currently published documentation states the following:

> Homebrew can run on 32-bit ARM (Raspberry Pi and others) and 64-bit ARM (AArch64), but no binary packages (bottles) are available. Support for ARM is on a best-effort basis. Pull requests are welcome to improve the experience on ARM platforms.

> You may need to install your own Ruby using your system package manager, a PPA, or rbenv/ruby-build as we no longer distribute a Homebrew Portable Ruby for ARM.

Source:
https://docs.brew.sh/Homebrew-on-Linux

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [aarch64-linux-gnu]

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"


/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

==> Checking for `sudo` access (which may request your password).
==> Select the Homebrew installation directory
- Enter your password to install to /home/linuxbrew/.linuxbrew (recommended)
- Press Control-D to install to /home/<user-name>/.linuxbrew
- Press Control-C to cancel installation
[sudo] password for user-name: 
Homebrew on Linux is only supported on Intel processors!

eval $(~/.linuxbrew/bin/brew shellenv)

brew doctor
Error: No Homebrew ruby 2.6.3_2 available for aarch64 processors!
Error: Failed to install Homebrew Portable Ruby and cannot find another Ruby 2.6.3!
If there's no Homebrew Portable Ruby available for your processor:
- install Ruby 2.6.3 with your system package manager (or rbenv/ruby-build)
- make it first in your PATH
- try again
```

**Comment by Bo98** [comment]
We unfortunately don't have a Portable Ruby build for aarch64. However, installing Ruby 2.6 should work (2.7 will not).

I'm aware that Ubuntu doesn't package Ruby 2.6 though, so you might need to find a PPA for now.

**Comment by cmosetick** [comment]
Hi thanks for the response and help @Bo98.
I have to ask if there was a major feature adjusted or added in ruby 2.7 that breaks homebrew?

![Screenshot from 2021-05-05 03-01-26](https://user-images.githubusercontent.com/4873085/117083832-49ac1200-ad4e-11eb-8ab7-6f1bce684d14.png)

**Comment by Bo98** [comment]
There may be some API differences, but the biggest breakage you'll see is that none of the required dependencies (gems) will load on non-2.6 Ruby: https://github.com/Homebrew/brew/tree/master/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems. They would need to be reinstalled and rebundled for Ruby 2.7.

**Comment by MikeMcQuaid** [comment]
> Support for ARM is on a best-effort basis. Pull requests are welcome to improve the experience on ARM platforms.
> Homebrew on Linux is only supported on Intel processors!

Both of these statements are true. We'll accept suggestions on how to improve the prior given that we don't support it. Closing but happy to continue discussion here.

**Comment by Bo98** [comment]
If you're having issues with this let me know. I discovered one bug which I'm fixing here: https://github.com/Homebrew/brew/pull/11330

**Comment by gromgit** [comment]
@Bo98 Just confirming that #11330 indeed fixes a regression I noticed but never got around to report. I'm using `rbenv`'d Ruby 2.6.3 on RPi Ubuntu 20.10, and `brew XYZ` worked just fine for a month, but suddenly started throwing the same error as @cmosetick a few days ago.
