### ISSUE TITLE
Automatic install of dependencies fail if not found in HOMEBREW_BOTTLE_DOMAIN

### ISSUE THREAD

**Issue by derrick-hardison** [Homebrew/brew#11338]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 227445ece9414a82aa8929b91ca2e0cca28a561b
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 279c9afbfc499c1b6e4f7fea998b3cbdf46b77af
Core tap last commit: 61 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://xxx/homebrew-remote/
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
all_proxy: http://xxx:8080
http_proxy: http://xxx:8080
https_proxy: http://xxx:8080
no_proxy: localhost,127.0.0.1,10.*,192.*,172.*
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-x86_64
CLT: N/A
Xcode: 12.4
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/xxx/.pyenv/shims/python3.9-config
  /Users/xxx/.pyenv/shims/python-config
  /Users/xxx/.pyenv/shims/python3-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libMsgCom.dylib
  /usr/local/lib/libSysCtlCom.dylib
  /usr/local/lib/libwep_airdrop.dylib
  /usr/local/lib/libwep_burn.dylib
  /usr/local/lib/libwep_cbcarbon.dylib
  /usr/local/lib/libwep_cbcocoa.dylib
  /usr/local/lib/libwep_chrome.dylib
  /usr/local/lib/libwep_dutil.dylib
  /usr/local/lib/libwep_ff.dylib
  /usr/local/lib/libwep_icloud.dylib
  /usr/local/lib/libwep_mail.dylib
  /usr/local/lib/libwep_outlook.dylib
  /usr/local/lib/libwep_post.dylib
  /usr/local/lib/libwep_printer.dylib
  /usr/local/lib/libwep_screen.dylib
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install kubectx with HOMEBREW_BOTTLE_DOMAIN set to an internal URL. It appears to do what it should when it doesn't find the bottle in HOMEBREW_BOTTLE_DOMAIN, however, it when it tries to unpack the wrong filename.

e.g.
tar: Error opening archive: Failed to open '/Users/xxx/Library/Caches/Homebrew/downloads/5b492d93e682d2b40706c60c1b6cf7ca844b39495c4987785894daad952a7c41--kubernetes-cli-1.21.0.big_sur.bottle.tar.gz'

❯ ls /Users/xxx/Library/Caches/Homebrew/downloads
3378c82130b8c7fa765e0aa177db9dfb858936143e679eba0b46c817cf15c4ef--kubectx-0.9.3.bottle_manifest.json
3f8ef2378f80f590de2b23fbeabb568d642c05a8bb81ba9069820efb536c1be0--kubernetes-cli--1.21.0.big_sur.bottle.tar.gz
869394ee095ee0fced4d6ed6cf4300669838167b7f657e73b34a8538aeb17ee1--kubectx--0.9.3.all.bottle.tar.gz
d9578ef448c1a3aa8c2d42c666a445d975154191053a34e682f7a45202dfb335--kubernetes-cli-1.21.0.bottle_manifest.json

As you can see, the bottle is there, but it's named different than what the script is expecting.

### What happened (include all command output)?

❯ brew install kubectx
==> Downloading https://xxx/homebrew-remote//kubernetes-cli-1.21.0.big_sur.bottle.tar.gz
##O#- #
curl: (22) The requested URL returned error: 404 Not Found
Warning: Bottle missing, falling back to the default domain...
==> Downloading https://ghcr.io/v2/homebrew/core/kubernetes-cli/manifests/1.21.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:9af94c3f27d4a8d95fa874453c30208f8fff41becb19668260099dcd2708ec61
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:9af94c3f27d4a8d95fa874453c30208f8fff41becb19668260099dcd2708ec61?se=2021-05-06T15%3A15%3A00Z&sig=QMpE0i%2FsQa1SaHVy01Yq
######################################################################## 100.0%
==> Downloading https://xxx/homebrew-remote//kubectx-0.9.3.all.bottle.tar.gz
##O#- #
curl: (22) The requested URL returned error: 404 Not Found
Warning: Bottle missing, falling back to the default domain...
==> Downloading https://ghcr.io/v2/homebrew/core/kubectx/manifests/0.9.3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/kubectx/blobs/sha256:30c0b39d23e542bc936994a8c1a47705f0205e42e59cb043adaed21f3e992efa
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:30c0b39d23e542bc936994a8c1a47705f0205e42e59cb043adaed21f3e992efa?se=2021-05-06T15%3A15%3A00Z&sig=LJLb1C6BpjFj8lXYs4Y2Jn
######################################################################## 100.0%
==> Installing dependencies for kubectx: kubernetes-cli
==> Installing kubectx dependency: kubernetes-cli
==> Pouring kubernetes-cli-1.21.0.big_sur.bottle.tar.gz
tar: Error opening archive: Failed to open '/Users/xxx/Library/Caches/Homebrew/downloads/5b492d93e682d2b40706c60c1b6cf7ca844b39495c4987785894daad952a7c41--kubernetes-cli-1.21.0.big_sur.bottle.tar.gz'
Error: Failure while executing; `tar --extract --no-same-owner --file /Users/xxx/Library/Caches/Homebrew/downloads/5b492d93e682d2b40706c60c1b6cf7ca844b39495c4987785894daad952a7c41--kubernetes-cli-1.21.0.big_sur.bottle.tar.gz --directory /private/tmp/d20210506-91907-11yxqqd` exited with 1. Here's the output:
tar: Error opening archive: Failed to open '/Users/xxx/Library/Caches/Homebrew/downloads/5b492d93e682d2b40706c60c1b6cf7ca844b39495c4987785894daad952a7c41--kubernetes-cli-1.21.0.big_sur.bottle.tar.gz'

❯ ls /Users/xxx/Library/Caches/Homebrew/downloads
3378c82130b8c7fa765e0aa177db9dfb858936143e679eba0b46c817cf15c4ef--kubectx-0.9.3.bottle_manifest.json
3f8ef2378f80f590de2b23fbeabb568d642c05a8bb81ba9069820efb536c1be0--kubernetes-cli--1.21.0.big_sur.bottle.tar.gz
869394ee095ee0fced4d6ed6cf4300669838167b7f657e73b34a8538aeb17ee1--kubectx--0.9.3.all.bottle.tar.gz
d9578ef448c1a3aa8c2d42c666a445d975154191053a34e682f7a45202dfb335--kubernetes-cli-1.21.0.bottle_manifest.json

### What did you expect to happen?

kubectx is installed and any nested dependencies are installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
export HOMEBREW_BOTTLE_DOMAIN=<<URL THAT DOESN'T HAVE THE BOTTLE>>
brew install kubectx
```

**Comment by Bo98** [comment]
This is probably a duplicate of #11209.

**Comment by derrick-hardison** [comment]
Yes, I agree. Didn’t see that one in my search.

Derrick Hardison
TOS - GTS - The Grove
US Bank | Elavon
2 Concourse Parkway | Suite 800 | Atlanta, GA 30328
O: 678.731.5213            M: 404.934.1908

***@***.******@***.***>
--


From: Bo Anderson ***@***.***>
Date: Thursday, May 6, 2021 at 11:23 AM
To: Homebrew/brew ***@***.***>
Cc: Hardison, Derrick ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [Homebrew/brew] Automatic install of dependencies fail if not found in HOMEBREW_BOTTLE_DOMAIN (#11338)
[WARNING] Use caution when opening attachments or links from unknown senders.


This is probably a duplicate of #11209<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Homebrew_brew_issues_11209&d=DwMCaQ&c=1hIq-C3ayh4zm6RZ7m4R2A&r=x0qR5yteuUbrw_F0lvG9_LnmDNoL9FQEOdzqGXurwH4&m=qfECzkx9sEmGyfj0hFOdUfdwpuvdsX0nYOt1hIsARhE&s=KBAbJAMcPVpN7ugDlJg1SXNU2GZeH0F3aMIQ8vJZawk&e=>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Homebrew_brew_issues_11338-23issuecomment-2D833610141&d=DwMCaQ&c=1hIq-C3ayh4zm6RZ7m4R2A&r=x0qR5yteuUbrw_F0lvG9_LnmDNoL9FQEOdzqGXurwH4&m=qfECzkx9sEmGyfj0hFOdUfdwpuvdsX0nYOt1hIsARhE&s=maqZSN2I8fN1y1uoySbh3_blnZ-46nQnZdbuqf-xqNs&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIM3QJBOKTWLX3UWFYEUN73TMKX4FANCNFSM44HIIQ2A&d=DwMCaQ&c=1hIq-C3ayh4zm6RZ7m4R2A&r=x0qR5yteuUbrw_F0lvG9_LnmDNoL9FQEOdzqGXurwH4&m=qfECzkx9sEmGyfj0hFOdUfdwpuvdsX0nYOt1hIsARhE&s=acO4npx3InNXI6YNKYyJRQ3CiQTmJ1pFNB12EJxW5dI&e=>.
The information contained in this e-mail and in any attachments is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. This message has been scanned for known computer viruses.

**Comment by derrick-hardison** [comment]
Agreed, closed.
