### ISSUE TITLE
undefined method `rebuild' for #<BottleSpecification:0x007fda241da208>

### ISSUE THREAD

**Issue by merlinyang521** [Homebrew/brew#1133]
brew install php70
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Installing php70 from homebrew/php
Error: undefined method `rebuild' for #<BottleSpecification:0x007fda241da208>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56.rb:16:in `block in <class:Php56>'
/usr/local/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1726:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56.rb:15:in `<class:Php56>'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56.rb:3:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formula_installer.rb:245:in `block in check_conflicts'
/usr/local/Library/Homebrew/formula_installer.rb:243:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:243:in `check_conflicts'
/usr/local/Library/Homebrew/formula_installer.rb:179:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:214:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `install'
/usr/local/Library/brew.rb:83:in `<main>'

**Comment by MikeMcQuaid** [comment]
You need to run `brew update` (twice).
