### ISSUE TITLE
curl: (22) The requested URL returned error: 416

### ISSUE THREAD

**Issue by erickyim** [Homebrew/brew#11347]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.5-146-g64b6846
ORIGIN: https://github.com/Homebrew/brew
HEAD: 64b6846d6078525b8569834718f7b093a7dd05e1
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1220c789207176204e85bb597fe56530da4f503c
Core tap last commit: 71 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3-x86_64
CLT: 12.5.0.22.9
Xcode: 12.4
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Upgrade a formula

### What happened (include all command output)?

➜  ~ brew upgrade node --verbose           
Updating Homebrew...
==> Upgrading 1 outdated package:
node 16.0.0_1 -> 16.1.0
==> Upgrading node 16.0.0_1 -> 16.1.0 
==> Downloading https://ghcr.io/v2/homebrew/core/node/manifests/16.1.0
Already downloaded: /Users/mac/Library/Caches/Homebrew/downloads/a6c30763ba02dc89f8e17eaf6cebb33db4ae0c5693b9986be57d61be6227e014--node-16.1.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/node/blobs/sha256:94748e79deb9f299fa33d7e0d41764893365742079f46dfa0becd02acdd84fb2
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:94748e79deb9f299fa33d7e0d41764893365742079f46dfa0becd02acdd84fb2?se=2021-05-08T07%3A40%3A00Z&sig=tnlGF1UJ4UCpvq7Oqam%2BZEStRpPaIHsWvh1yPufZH48%3D&sp=r&spr=https&sr=b&sv=2019-12-12
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.5-146-g64b6846\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.3\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --header Authorization:\ Bearer\ QQ== --location --remote-time --continue-at - --output /Users/mac/Library/Caches/Homebrew/downloads/7b51d544f0d5d84faf5e04cf0096b9c064623f09cf31f6f4986aa7d2e85128f1--node--16.1.0.big_sur.bottle.tar.gz.incomplete https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:94748e79deb9f299fa33d7e0d41764893365742079f46dfa0becd02acdd84fb2\?se=2021-05-08T07\%3A40\%3A00Z\&sig=tnlGF1UJ4UCpvq7Oqam\%2BZEStRpPaIHsWvh1yPufZH48\%3D\&sp=r\&spr=https\&sr=b\&sv=2019-12-12
** Resuming transfer from byte position 13758007
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 416
Error: Failed to download resource "node"
Download failed: https://ghcr.io/v2/homebrew/core/node/blobs/sha256:94748e79deb9f299fa33d7e0d41764893365742079f46dfa0becd02acdd84fb2

### What did you expect to happen?

Upgrade the formula successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade node --verbose
```

**Comment by erickyim** [comment]
Then I open the link 'https://ghcr.io/v2/homebrew/core/node/manifests/16.1.0' on browser, it returns `{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}`

**Comment by gromgit** [comment]
```
rm -f /Users/mac/Library/Caches/Homebrew/downloads/7b51d544f0d5d84faf5e04cf0096b9c064623f09cf31f6f4986aa7d2e85128f1--node--16.1.0.big_sur.bottle.tar.gz*
brew upgrade node
```

**Comment by erickyim** [comment]
> rm -f /Users/mac/Library/Caches/Homebrew/downloads/7b51d544f0d5d84faf5e04cf0096b9c064623f09cf31f6f4986aa7d2e85128f1--node--16.1.0.big_sur.bottle.tar.gz*
> brew upgrade node

It works, thx.

**Comment by erickyim** [comment]
> > rm -f /Users/mac/Library/Caches/Homebrew/downloads/7b51d544f0d5d84faf5e04cf0096b9c064623f09cf31f6f4986aa7d2e85128f1--node--16.1.0.big_sur.bottle.tar.gz*
> > brew upgrade node
> 
> It works, thx.

I also have this problem with other formulas. So I removed Homebrew  caches `rm -rf ~/Library/Caches/Homebrew/downloads`, and this problem resolved.

Maybe it's related with a HOMEBREW_BOTTLE_DOMAIN problem. #11209
