### ISSUE TITLE
fatal: unable to access 'https://github.com/Homebrew/brew/': Couldn't connect to server

### ISSUE THREAD

**Issue by aaankur** [Homebrew/brew#1134]
I was trying to install homebrew on a MacBook Pro (Retina, 13-inch, Late 2013) running OS X El Capitan v10.11.5

I am accessing the internet using a cellular hotspot that does not use any proxy server.

I used the following command to install:

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Then this follows:**

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Homebrew
/usr/local/Frameworks
/usr/local/etc
/usr/local/opt

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/etc /usr/local/opt
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/etc /usr/local/opt
==> /usr/bin/sudo /bin/chmod u+rwx share/zsh share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown Ankur /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/etc /usr/local/opt
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/etc /usr/local/opt
==> Downloading and installing Homebrew...

### Bug reports:

At this point it the terminal throws the following errors

fatal: unable to access 'https://github.com/Homebrew/brew/': Couldn't connect to server
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1

Would really appreciate any help on how to solve this issue. Thanks!

**Comment by MikeMcQuaid** [comment]
> fatal: unable to access 'https://github.com/Homebrew/brew/': Couldn't connect to server
> Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1

This means you failed to connect to GitHub to download Homebrew. I'm afraid there's nothing we can do to fix this, sorry.

**Comment by aaankur** [comment]
Any clue of why it might be happening or what I can do to resolve this? My internet connection is properly functioning. I have been trying to figure this out but have not been able to. I understand it is not an issue from your end but this will be a big help for me. Thanks again!

**Comment by MikeMcQuaid** [comment]
@aaankur Try to manually `git clone https://github.com/Homebrew/brew`. If that works: try to rerun the install script. If it does not you're better dealing with GitHub support.

**Comment by aaankur** [comment]
@MikeMcQuaid Thanks a lot! It was a proxy issue, I guess. I had to use the following command `git config --global --unset http.proxy` and then rerun the install script and it worked. Thanks again for your help!

**Comment by MikeMcQuaid** [comment]
@aaankur Glad you got it sorted!
