### ISSUE TITLE
I don't have a descriptions cache, and nothing seems to create one

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#1136]
On ElCap, I am missing the `desc_cache.json` cache file that's supposed to be created and used by `brew desc`.

No such file exists anywhere on the machine, much less in my `HOMEBREW_CACHE`.  (The latter is set in my `~/.profile` to a non-standard location.)

I tried running `brew update` to see if that would create one, but it doesn't.  (Normally I don't call that command; I run `git pull` in the two repos "brew" and "core".)

I have never manually deleted such a file, so I think it's just never being created.

**Comment by zmwangx** [comment]
Try `brew search --desc player`? Pretty sure you'll get one in `HOMEBREW_CACHE`.

I haven't read the code, but I suppose there's no point in writing everything if you just describe a few individual formulae.

**Comment by zmwangx** [comment]
Read code (`descriptions.rb`) and confirmed my assumption: `save_cache` only appears in `generate_cache`, which in turn only appears in `ensure_cache`, which in turn only appears in `search`

**Comment by chdiza** [comment]
Running `brew desc foo` ought to ensure that there's a cache there, right?  Why would the cache only be for `brew search --desc`?

**Comment by zmwangx** [comment]
The cache contains at the very least descriptions of every core formula. Do you want to ask brew to describe `foo` and instead have brew read all formulae under the sun? I don't know about you, but I don't.

**Comment by zmwangx** [comment]
In other words: you only create a cache when it's worthwhile. Describing a single formula isn't an operation that's worth caching.

**Comment by chdiza** [comment]
>  Do you want to ask brew to describe foo and instead have brew read all formulae under the sun?

It wouldn't do this if there were a cache.  It would start reading the cache, not all the formulas, and stop when it found the requested description.

But never mind anyway, because even *that* may well take longer than going straight to a formula if the requested description is for a formula that isn't near the beginning of the cache.

**Comment by zmwangx** [comment]
> It wouldn't do this if there were a cache. It would start reading the cache, not all the formulas, and stop when it found the requested description.

It would need to make sure the cache isn't outdated, and if it is (the consider is `.git/refs/heads/master` in any tap being newer than the cache), update it. Updating the cache means reading all formulae under the sun. Since homebrew-core and friends are supposedly updated all the time, the chance of cache being fresh is very low.

Also, even if the cache is fresh, which do you think is faster, parsing a 2K formula, or reading a 200K+ JSON cache? I'm not entirely sure, but I would put money on the former.

Anyway, if you don't like this behavior, submit a PR.

**Comment by zmwangx** [comment]
Oh I didn't see your second paragraph.
