### ISSUE TITLE
Support to install/update/upgrade apps concurrently

### ISSUE THREAD

**Issue by Loyalsoldier** [Homebrew/brew#11363]
### Provide a detailed description of the proposed feature

It's too slow to install apps that have too many dependencies(eg, ffmpeg) one by one. I think to install them concurrently is a faster solution.

### What is the motivation for the feature?

Time is money.

### How will the feature be relevant to at least 90% of Homebrew users?

People hate waiting.

### What alternatives to the feature have been considered?

No.

**Comment by Bo98** [comment]
Depends really where the slowdown is.

The benefits of concurrent downloads is somewhat limited. You can't exceed the bandwidth your internet provider allows so if that's what you are hitting then splitting it into two won't really make anything much faster.

For installing there's some disk IO. Not entirely sure how much - measurements would be needed here.

For everything in between, efforts are better spent making sure investigating why they might be slow, if they are.

**Comment by Loyalsoldier** [comment]
The reason why it's slow:

1. It first gets the manifest, then the real URL for each dependency one by one;
2. It downloads dependencies one by one;
3. It writes to disk one by one.

The faster way will be to:

1. Get URLs concurrently
2. Download concurrently (or one by one due to bandwidth limitation)
3. Write disk (install the downloaded one) while downloading the other dependencies.

**Comment by MikeMcQuaid** [comment]
I'd need to see evidence this made things faster on average. Parallel IO contention often does the opposite. Closing but will review a PR that provides supporting data.

**Comment by Loyalsoldier** [comment]
Given the fact that hard disk write speed is much faster than network speed in most cases, there is no doubt that it's much faster to download and install apps concurrently.

**Comment by MikeMcQuaid** [comment]
There is doubt. I have doubt. My doubt would be overcome through data.

**Comment by carlocab** [comment]
Even if we assume that you're correct and doing things concurrently would be faster, I also doubt that the speed gains will be enough to be worth the effort of implementing and maintaining them. Concurrency opens the door to non-deterministic bugs.

As with Mike, my doubts can be overcome with data.
