### ISSUE TITLE
Bug in `brew remove`?

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#1138]
This isn't a case of normal usage, but:  `brew remove ""` results in:

```
/usr/local/Cellar/autoconf is not a valid keg
```

There's nothing special about `autoconf`; testing reveals that whatever formula is the alphabetically earliest that's installed will be the one that appears in the message.

This kind of thing is probably supposed to be blocked by line 13 of `uninstall.rb`, but the KegUnspecifiedError isn't getting raised AFAICT.  I suspect that the `named` method insufficiently strict to use as the guard here.

**Comment by zmwangx** [comment]
Yeah I can reproduce, it tries to uninstall whatever keg that comes first alphabetically, and fails.

**Comment by zmwangx** [comment]
Fix in #1139.

**Comment by chdiza** [comment]
Thanks!
