### ISSUE TITLE
Add multithreaded Bullet formula: bullet@mt

### ISSUE THREAD

**Issue by psi29a** [Homebrew/brew#11383]
### Provide a detailed description of the proposed feature

Now that we have both single and double precision bullet and also the latest 3.17 thanks to #77143, can we also have a multi-threaded variant too?

I thought perhaps: bullet@mt

### What is the motivation for the feature?

Add multi-threaded bullet libraries for software that takes advantage of this, such as OpenMW

### How will the feature be relevant to at least 90% of Homebrew users?

As more and software supports multi-threaded bullet, this package will likely become even more popular.

### What alternatives to the feature have been considered?

We can still edit the original formula to turn on multi-threaded that way.

**Comment by MikeMcQuaid** [comment]
Please open a pull request, thanks!
