### ISSUE TITLE
Pre- and Post-Upgrade Hooks

### ISSUE THREAD

**Issue by leemcd56** [Homebrew/brew#11380]
### Provide a detailed description of the proposed feature

Like many, I use Homebrew to install background services I can use for development (such as PHP, Node, Postgres, or Redis). When I run `brew upgrade` and forget to stop external services that rely on some of these, I will get a message like so:

```sh
==> Summary
🍺  /opt/homebrew/Cellar/php/8.0.6_1: 500 files, 78.0MB
Removing: /opt/homebrew/Cellar/php/8.0.6... (500 files, 78.0MB)
Error: Directory not empty @ dir_s_rmdir - /opt/homebrew/Cellar/php/8.0.6
```

A minor grievance, having to manually remove these directories. However, if the external services are stopped ahead of time, this doesn't occur.

When Homebrew runs _upgrade_, it could look for a shell script in `~/.brew` named either `pre-upgrade.sh` or `post-upgrade.sh` to perform certain actions prior or after upgrading packages.

_Alternatively_, a new command (such as `brew configure upgrade`) could safely tuck these away in `/opt/homebrew` to reduce security issues.

### What is the motivation for the feature?

Certain services I use, such as Homebridge or Laravel Valet, rely on other services I have installed through Homebrew. Being able to stop these services prior to upgrade, allowing Homebrew to remove the previous directories without conflict, would be great.

### How will the feature be relevant to at least 90% of Homebrew users?

Any user that utilizes third-party services which may rely on a Homebrew package may want to either stop and start these services during an upgrade or run parallel auditing commands.

### What alternatives to the feature have been considered?

Typically, pre-upgrading packages requires stopping these services manually, and then starting them back up afterwards.

Alternatively, one could simply write a wrapper for `brew upgrade` in their `.bashrc` or `.zshrc` file that performs these actions ahead of time.

**Comment by carlocab** [comment]
See #2202 and #11017.

**Comment by MikeMcQuaid** [comment]
> Alternatively, one could simply write a wrapper for `brew upgrade` in their `.bashrc` or `.zshrc` file that performs these actions ahead of time.

This is what we recommend, sorry.
