### ISSUE TITLE
`brew install` and `brew upgrade` should be idempotent 

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#11393]
### Provide a detailed description of the proposed feature

Repeatedly running `brew install` or `brew upgrade` should produce the same exit code and not output any `Error:`s. 

This could be done initially with an `--idempotent` flag or just made the default (which I think it should be eventually). Potentially a `HOMEBREW_NO_IDEMPOTENT` could be added to allow short-term workarounds but this should not stick around forever.

### What is the motivation for the feature?

People have asked for this for a long time. We've pushed back arguing that the exit code consistency is important but I'm less convinced that's the case (and if it is: we can use our deprecation/disable cycle) 

### How will the feature be relevant to at least 90% of Homebrew users?

Homebrew works more like how people expect.

### What alternatives to the feature have been considered?

- The status quo.
- Telling people to use `brew bundle` for idempotent behaviour.

**Comment by cnnrmnn** [comment]
I assume I'm missing something, but as far as I can tell, repeatedly running `brew install/upgrade <formula>` or produces the same exit code and doesn't output any errors provided that it didn't output errors on the first run (e.g., if the formula didn't exist).

Examples:
```zsh
$ brew install cowsay
(normal installation output)
$ echo $?
0
$ brew install cowsay
Warning: cowsay 3.04_1 is already installed and up-to-date.
To reinstall 3.04_1, run:
  brew reinstall cowsay
$ echo $?
0
```
`brew upgrade` does the same thing.

What scenarios exist at the moment where repeatedly running `brew install` or `brew upgrade` do not conform to the behavior you describe?

**Comment by MikeMcQuaid** [comment]
> I assume I'm missing something, but as far as I can tell, repeatedly running `brew install/upgrade <formula>` produces the same exit code and doesn't output any errors provided that it didn't output errors on the first run (e.g., if the formula didn't exist).
> `brew upgrade` does the same thing.

Thanks for verifying this! I may have misremembered some of this 😅 

> What scenarios exist at the moment where repeatedly running `brew install` or `brew upgrade` do not conform to the behavior you describe?

If I remember correct: if a formula is outdated then `brew install` will return `1`. It's a bit different from the original issue but I've been debating if it should do a `brew upgrade` if a formula is already installed but not up-to-date. Alternatively, `brew upgrade` could install formulae that aren't installed.

There may also be situations where e.g. a formula isn't linked where the exit codes are not consistent/zero.

The main case I'm concerned about is people not needing to do something like `brew install || brew upgrade` if a formula is outdated.

**Comment by cnnrmnn** [comment]
> If I remember correct: if a formula is outdated then brew install will return 1. It's a bit different from the original issue but I've been debating if it should do a brew upgrade if a formula is already installed but not up-to-date.

You're correct here.

>The main case I'm concerned about is people not needing to do something like brew install || brew upgrade if a formula is outdated.

I agree, this seems annoying. I'll open a PR that fixes this.

>Alternatively, brew upgrade could install formulae that aren't installed.

I could add this too, but I'm less sure about it. I'll see what other maintainers think in the PR, but if you feel strongly about it, I'm happy to implement it.

**Comment by MikeMcQuaid** [comment]
> I agree, this seems annoying. I'll open a PR that fixes this.

🎉. I'd suggest you also add a `HOMEBREW_NO_INSTALL_UPGRADE` to `EnvConfig` to be able to fall back to the existing functionality.

> I could add this too, but I'm less sure about it. I'll see what other maintainers think in the PR, but if you feel strongly about it, I'm happy to implement it.

Yeh, let's pass on this for now.

**Comment by cnnrmnn** [comment]
What function should I use to run the `brew upgrade` command? Slightly confused by the `system_command`, `system`, `safe_system`, etc. commands.

>🎉. I'd suggest you also add a HOMEBREW_NO_INSTALL_UPGRADE to EnvConfig to be able to fall back to the existing functionality.
Will do!

**Comment by MikeMcQuaid** [comment]
> What function should I use to run the `brew upgrade` command? Slightly confused by the `system_command`, `system`, `safe_system`, etc. commands.

Rather than shelling out it should perform similar behaviour as in `brew upgrade`. I think this is actually just the matter of removing the checks that fail on a `brew install` formula being outdated e.g. https://github.com/Homebrew/brew/blob/bf7f2e9a49ff8edecffe00cc9a6d81f179f741f6/Library/Homebrew/cmd/install.rb#L221-L222 and elsewhere

**Comment by Rylan12** [comment]
Heads up I'm doing a bit of refactoring on the `install` command here https://github.com/Homebrew/brew/pull/11522. Not to stop you from working on this but just keep in mind there might be some conflicts. Really all I'm doing is extracting some of the checks to the `Install` module and out of the `install` command, so shouldn't cause major problems if you've already started working on it.

**Comment by cnnrmnn** [comment]
Thanks for the heads up, @Rylan12! Currently working on this. If there end up being any conflicts, I'm happy to resolve them :)

**Comment by Rylan12** [comment]
(Still open a PR when you're ready because yours might get through first and then I'll fix conflicts in mine)

**Comment by cnnrmnn** [comment]
> Rather than shelling out it should perform similar behaviour as in brew upgrade. I think this is actually just the matter of removing the checks that fail on a brew install formula being outdated e.g.

Gotcha. Thanks for the help. I appreciate your time.
