### ISSUE TITLE
"Error: type mismatch: String given" on brew audit --strict --online

### ISSUE THREAD

**Issue by CarloQ** [Homebrew/brew#1140]
When I run brew audit --strict --online, It said:

```
Error: type mismatch: String given
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `=~'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `block in search_tap'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `search_tap'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:346:in `block (2 levels) in audit_formula_name'
```

Sorry for my bad English !

If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue.

### Propose a feature:

Instead of creating an issue here, please create a pull request with your change proposal in the [Homebrew Evolution](https://github.com/Homebrew/brew-evolution) repository using the [proposal template](https://github.com/Homebrew/brew-evolution/blob/master/proposal_template.md).

**Comment by zmwangx** [comment]
Thanks for the report. This is a known issue and has been fixed in #1135. Please run `brew update`.

**Comment by zmwangx** [comment]
(You may need to run `git -C "$(brew --repo)" checkout master` once to switch to the master branch.)

**Comment by MikeMcQuaid** [comment]
Let's leave this open until it hits a tagged release.

**Comment by MikeMcQuaid** [comment]
Fixed now.
