### ISSUE TITLE
Require signed commits on Homebrew/homebrew-cask*

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#11403]
Follow-up from https://github.com/Homebrew/brew/issues/10672

Homebrew/homebrew-core requires signed commits. Homebrew/homebrew-cask* should do the same. 

@BrewTestBot is already set up for signing (CC @nandahkrishna in case there's any cask-related gotchas you see) so this is mainly blocked on @Homebrew/cask maintainers following https://github.com/Homebrew/ops/blob/master/SigningCommits.md (or raising issues here that we can resolve).

CC @Homebrew/cask. Please check yourself off below when you've done this. I've pre-checked the Homebrew/homebrew-core maintainers I know are already setup for this.

- [x] @claui
- [x] @reitermarkus
- [x] @vitorgalvao
- [x] @alebcay
- [x] @miccal
- [x] @ran-dall
- [x] @cho-m
- [x] @SMillerDev
- [x] @carlocab
- [x] @Rylan12

**Comment by nandahkrishna** [comment]
It seems we only have to add the `setup-commit-signing` action step to the necessary workflow(s) in Homebrew/homebrew-cask* to enable commit signing for BrewTestBot. The third party action used to create pull requests ([example](https://github.com/Homebrew/homebrew-cask/blob/1212ae9879ed484487aeed96cb8d31ef497893ed/.github/workflows/sync-templates-and-ci-config.yml#L41)) does support signed commits.

I'll open PRs in some time to add the commit signing step.

**Comment by MikeMcQuaid** [comment]
> I'll open PRs in some time to add the commit signing step.

Thanks again @nandahkrishna!

**Comment by cho-m** [comment]
Please check me off as I don't have permissions to edit posts in Homebrew/brew.

**Comment by MikeMcQuaid** [comment]
Assuming @reitermarkus is 👍🏻 because I've seen commits from him here. @ran-dall shout if you need a hand getting set up.

Enabled this now @Homebrew/cask! Shout if there's any problems.

**Comment by ran-dall** [comment]
@MikeMcQuaid Thanks for the heads up. I'm all set.
