### ISSUE TITLE
`brew autoremove` cannot recognize dependencies of casks? 

### ISSUE THREAD

**Issue by maxwellzh** [Homebrew/brew#11417]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: e0bfcdaf258dadaaf8c102d4cb51f23b6fdb2c4c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ee8ea106efb5627ffeb216c4625922d176b85b24
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
http_proxy: http://127.0.0.1:1087
https_proxy: http://127.0.0.1:1087
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-x86_64
CLT: 12.5.0.22.9
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

invoke `brew autoremove` to uninstall all unused dependencies as `apt autoremove` in debian system.

### What happened (include all command output)?

brew recognizes `ghostscript` as unneeded formula, but it is needed for cask `mactex-no-gui` and raise an error.
```
$ brew autoremove
==> Uninstalling 1 unneeded formula:
ghostscript
Error: Refusing to uninstall /usr/local/Cellar/ghostscript/9.53.3_1
because it is required by mactex-no-gui, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies
```

### What did you expect to happen?

`brew autoremove` functions as well as `apt autoremove`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Assure `ghostscript` is not installed.
2. Install `mactex-no-gui`: `brew install --cask mactex-no-gui` (this might take a while)
3. Run `brew autoremove`
```

**Comment by MikeMcQuaid** [comment]
Yes, this is expected behaviour (for now). We'd welcome PRs to improve this.
