### ISSUE TITLE
add `Homebrew.install_bundler_gems!` to `brew update`

### ISSUE THREAD

**Issue by hyuraku** [Homebrew/brew#11419]
### Provide a detailed description of the proposed feature

`Homebrew.install_bundler_gems!` works in `brew update`.

### What is the motivation for the feature?

When I executed `brew livecheck elmedia-player` after `brew style`, an error happened `Error: cannot load such file -- nokogiri` like below error log, because `brew update` updated `nokogiri` version in `Library/Homebrew/Gemfile.lock` by https://github.com/Homebrew/brew/pull/11415 not install newer `nokogiri` gem.

- error log
```bash
$ brew livecheck elmedia-player
Error: cannot load such file -- nokogiri
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:60:in `require'
/usr/local/Homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:60:in `item_from_content'
/usr/local/Homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:118:in `find_versions'
/usr/local/Homebrew/Library/Homebrew/livecheck/livecheck.rb:532:in `block in latest_version'
/usr/local/Homebrew/Library/Homebrew/livecheck/livecheck.rb:479:in `each'
/usr/local/Homebrew/Library/Homebrew/livecheck/livecheck.rb:479:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/livecheck/livecheck.rb:479:in `latest_version'
/usr/local/Homebrew/Library/Homebrew/livecheck/livecheck.rb:189:in `block in run_checks'
/usr/local/Homebrew/Library/Homebrew/livecheck/livecheck.rb:142:in `map'
/usr/local/Homebrew/Library/Homebrew/livecheck/livecheck.rb:142:in `with_index'
/usr/local/Homebrew/Library/Homebrew/livecheck/livecheck.rb:142:in `run_checks'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/livecheck.rb:115:in `livecheck'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### How will the feature be relevant to at least 90% of Homebrew users?

avoid the error

### What alternatives to the feature have been considered?

Manually `brew install-bundler-gems` after `brew update`

**Comment by nandahkrishna** [comment]
This is actually an issue with `livecheck` not running `Homebrew.install_bundler_gems!`, which is required only for the `Sparkle` strategy. You might want to take a look at https://github.com/Homebrew/discussions/discussions/1299, there is some useful discussion there, including a point about how this may still be problematic on ARM.
