### ISSUE TITLE
Developer users stuck on old tag... again

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/brew#1141]
1.0.4 is a funny release because it claims to 

- Stop developer users from getting "stuck" on an old tag (#1114)

but then the entry immediately below it

- Always use the stable branch for tagged checkouts (#1121)

seems to have broken that promise again. This is because the mitigation implemented in #1114 became useless after #1121.

Reproducer:

```sh
# start with a clean install, on the stable branch
$ git reset --hard 1.0.3
# on stable branch, HEAD at 1.0.3
$ git config --add homebrew.devcmdrun true
$ brew update
# master branch updated, stable branch untouched
$ git describe --tags
1.0.3
```

CC @MikeMcQuaid.

**Comment by zmwangx** [comment]
One solution might be to keep the `stable` branch updated for developer users.

**Comment by MikeMcQuaid** [comment]
> $ git reset --hard 1.0.3

Does the same reproduce with 1.0.4?

**Comment by zmwangx** [comment]
> Does the same reproduce with 1.0.4?

Good point. Since we don't have 1.0.5 yet you shouldn't see an update to 1.0.4 anyway, but say you `git reset --hard 2f82837` (2f82837 is the merge commit of #1121), you'll see this. The point is the stable isn't touched, only master is.

**Comment by MikeMcQuaid** [comment]
If you're on `stable` and run `brew update` then it'll update `stable` to the latest tag. You can confirm this locally by running `git checkout master; git tag 1.0.5`. That seems to be the desired behaviour so I'm not sure I understand the problem?

**Comment by zmwangx** [comment]
> If you're on stable and run brew update then it'll update stable to the latest tag. 

But it won't if you're a developer user.
