### ISSUE TITLE
brew install graphviz failed

### ISSUE THREAD

**Issue by ssh352** [Homebrew/brew#11418]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: e0bfcdaf258dadaaf8c102d4cb51f23b6fdb2c4c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 07a2cf3127f6a890207b3654018d6fe78f89b14e
Core tap last commit: 7 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.aliyun.com/homebrew/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.t1zjOy8VFA/org.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.24.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 11.3.0.32.59
Xcode: 12.4
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install graphviz

### What happened (include all command output)?

==> Pouring libtiff-4.3.0.catalina.bottle.tar.gz
tar: Error opening archive: Failed to open '/Users/zhang/Library/Caches/Homebrew/downloads/f9004d3169ace5a3e9081f0de7bc6e10496bf373328e56cefebbce5383057776--libtiff-4.3.0.catalina.bottle.tar.gz'
Error: Failure while executing; `tar --extract --no-same-owner --file /Users/zhang/Library/Caches/Homebrew/downloads/f9004d3169ace5a3e9081f0de7bc6e10496bf373328e56cefebbce5383057776--libtiff-4.3.0.catalina.bottle.tar.gz --directory /private/tmp/d20210520-13750-t067hx` exited with 1. Here's the output:
tar: Error opening archive: Failed to open '/Users/zhang/Library/Caches/Homebrew/downloads/f9004d3169ace5a3e9081f0de7bc6e10496bf373328e56cefebbce5383057776--libtiff-4.3.0.catalina.bottle.tar.gz'

### What did you expect to happen?

installation success

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install graphviz
```

**Comment by carlocab** [comment]
Please do
```
unset HOMEBREW_BOTTLE_DOMAIN
````
then try again.

**Comment by ssh352** [comment]
it fixed it, Thanks!
