### ISSUE TITLE
Error while installing Homebrew on Linux

### ISSUE THREAD

**Issue by samuelarogbonlo** [Homebrew/brew#11423]
### `brew config` output

```
shell
HOMEBREW_VERSION: 3.1.8-56-gda2a3aa
ORIGIN: https://github.com/Homebrew/brew
HEAD: da2a3aadcb38b06164a4b59f50a1104a03ced82c
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: HEAD
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.8.0-53-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  mpfr
  zlib
  libmpc
  isl@0.18
  eksctl
  binutils
  gcc
  kubernetes-cli
  aws-iam-authenticator
  hello
  gmp
  patchelf

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to install homebrew so I can install the terraform environment 

### What happened (include all command output)?

I ran this command below install homebrew and then an error popped.

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"```
```
After installing to an extent, this error below popped:
```
==> Downloading and installing Homebrew...
HEAD is now at da2a3aadc Merge pull request #11422 from Homebrew/spdx-update
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
^CFailed during: /home/linuxbrew/.linuxbrew/bin/brew update --force --quiet
```
### What did you expect to happen?

I expected it to install succesfully

### Step-by-step reproduction instructions (by running `brew` commands)
I ran this command below install homebrew and then an error popped.
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"```
```

**Comment by carlocab** [comment]
This is a connection problem, and not a problem with `brew` itself. There's not much we can do to help you with that. Try
```
rm -rf $(brew --repo homebrew/core)
brew tap homebrew/core
```
If that doesn't work, see if you're able to clone https://github.com/Homebrew/linuxbrew-core manually into `$(brew --prefix)/Homebrew/Library/Taps/homebrew`.

Failing that, you can check https://github.com/Homebrew/discussions/discussions/666 and related threads for things other users did to solve similar connection problems.
