### ISSUE TITLE
Multiple formula refuse to install because the command line tools are not installed, even though the full version of Xcode is installed

### ISSUE THREAD

**Issue by Candygoblen123** [Homebrew/brew#11433]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76cfe88b7628a8010bf98115627f6aced4ff8870
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 48d8d66985f59d7fd22c6344d7480d05465963b4
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.uGdrC1V8Xp/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_EMOJI: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-x86_64
CLT: N/A
Xcode: 12.5
XQuartz: 2.7.11 => /opt/X11
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
  rdesktop

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  imath
  openexr
  gnupg

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/opt/python@3

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install python@3.9 #Uninstalled for testing

Run `brew missing` for more details.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install mpv, which has a requirement for python@3.9, and was getting an error that I do not have the command line tools installed.  I do not have the standalone command line tools installed, but I do have the full version of Xcode.app.  After a little bit of testing, I was able to reproduce this error with python and gcc, so it is not an issue with python. 

### What happened (include all command output)?

```
candy@MacBook-Air ~ % brew install mpv
Warning: Treating mpv as a formula. For the cask, use homebrew/cask/mpv
Error: python@3.9: the bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install

You can try to install from source with:
  brew install --build-from-source python@3.9
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
candy@MacBook-Air ~ %
```

### What did you expect to happen?

I expected mpg to install without issue.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1) have Xcode.app installed, but not the Xcode command line tools installed. `xcode-select -p` should return `/Applications/Xcode.app/Contents/Developer`.  
2) try to install either python or gcc. for example `brew install gcc`.
3) wait for the install to error out.
```

**Comment by carlocab** [comment]
The bottles for those formulae work only with the Xcode Command Line Tools. It's not enough to have the full version of Xcode installed. That's why the error message says
```
Error: python@3.9: the bottle needs the Apple Command Line Tools to be installed.
```

You can either build these from source (this is unsupported, but should typically just work), or install the CLT to use the bottles.

**Comment by carlocab** [comment]
Alternatively, you can try
```
brew install --force-bottle python@3.9
```
to force a bottle installation even if you don't have the CLT installed. Note, however, that `brew` checks for a CLT installation for a reason. Please don't file issues if you have a broken `python@3.9` from forcing a bottle install when you don't have the CLT.

**Comment by Candygoblen123** [comment]
Ah, I'll install the CLT then.  You could make the error message a little more clear by adding something that says "The command line tools that are included with the full install of Xcode are not good enough, the standalone Command Line Tools are required."

**Comment by carlocab** [comment]
We'll review a pull request to improve the messaging here.
