### ISSUE TITLE
Formula fails to install and no error message is printed

### ISSUE THREAD

**Issue by aleb** [Homebrew/brew#1144]
Brew does not report the failure when attempting to install this formula:
`brew install https://raw.githubusercontent.com/aleb/homebrew-gui/master/pitivi.rb`

I run it and notice it builds gst-plugins-good because some optional dependencies are required, and that's it. At the end, pitivi is not installed and no error message is printed.

Is it a problem that it prints `==> Installing dependencies for pitivi: gst-plugins-good` twice?

gst-plugins-good seems to be installed fine (at least brew uninstall gst-plugins-good did something) but when running the "brew install pitivi" command again, it rebuilds each time gst-plugins-good even though it should already satisfy the requirements of the formula. Should I file a separate bug?

I tried using `--ignore-dependencies` but in this case `configure` fails fast because the shebang line requires python3 and PATH does not contain /usr/local/bin when using this flag:
`PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/bin:/bin:/usr/sbin:/sbin`
Should I file a separate bug?

**Comment by MikeMcQuaid** [comment]
Please use `brew install homebrew/gui/pitivi` and report it to the homebrew/gui tap's issue tracker if that fails.

**Comment by aleb** [comment]
I run `brew install https://raw.githubusercontent.com/aleb/homebrew-gui/master/pitivi.rb --verbose` and brew does not run the "def install" method! It should print an error or an explanation why it does not do this. I think this is a `brew` problem, not a homebrew-gui problem. Please reopen the issue.

FWIW, the pitivi formula is not yet in homebrew-gui.

**Comment by MikeMcQuaid** [comment]
What does `brew install aleb/gui/pitivi` output?

**Comment by aleb** [comment]
```
➜  ~ brew install aleb/gui/pitivi
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Tapping aleb/gui
Cloning into '/usr/local/Homebrew/Library/Taps/aleb/homebrew-gui'...
remote: Counting objects: 27, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 27 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (27/27), done.
Tapped 23 formulae (74 files, 87.4K)
==> Installing pitivi from aleb/gui
==> Installing dependencies for aleb/gui/pitivi: gst-plugins-good
==> Installing aleb/gui/pitivi dependency: gst-plugins-good
==> Using the sandbox
==> Downloading https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.8.3.tar.xz
Already downloaded: /Users/aleb/Library/Caches/Homebrew/gst-plugins-good-1.8.3.tar.xz
==> Patching
patching file sys/osxvideo/cocoawindow.h
patching file sys/osxvideo/osxvideosink.h
==> ./configure --prefix=/usr/local/Cellar/gst-plugins-good/1.8.3_1 --disable-gtk-doc --disable-goom --with-default-videosin
==> make
==> make install
🍺  /usr/local/Cellar/gst-plugins-good/1.8.3_1: 368 files, 13.6M, built in 3 minutes 25 seconds
==> Installing aleb/gui/pitivi
==> Installing dependencies for aleb/gui/pitivi: gst-plugins-good

```

**Comment by MikeMcQuaid** [comment]
This is likely because `gst-plugins-base` is implied twice because of depending on from both `gst-plugins-good` and your formula. You may be able to get a backtrace by running `brew install --debug`

**Comment by aleb** [comment]
I don't see any backtrace when I use --debug. 

If I remove the gst-plugins-base dependency (from pitivi.rb), it's still the same. A few of the gst-* formulas depend on it.
If I remove the gst-plugins-good dependency, it goes further.

**Comment by MikeMcQuaid** [comment]
I can't reproduce this locally because there's things I can't build in the dependency tree. Can you try to slim this down to a minimal, reproducible test-case?

**Comment by aleb** [comment]
What stops you from building the dependency tree?

**Comment by MikeMcQuaid** [comment]
Can you try to slim this down to a minimal, reproducible test-case?

**Comment by aleb** [comment]
Sorry, we're busy making a release at the moment.

**Comment by MikeMcQuaid** [comment]
Will reopen when there's a minimal, reproducible test-case.

**Comment by aleb** [comment]
Could you please detail, how minimal do you need the "reproducible test-case" to be?
Are there other similar test-cases I could copy/paste from to build my own test case?
Thanks for helping!

**Comment by MikeMcQuaid** [comment]
Basically the simplest thing you can get that reproduces the problem e.g. keep deleting lines from your formula until you can still reproduce it with only those lines. Thanks!

**Comment by aleb** [comment]
Could you please answer whether I should file separate bugs for the other problems I mentioned in the first comment?

**Comment by MikeMcQuaid** [comment]
There's no need, thanks.

**Comment by aleb** [comment]
Ok, I'm trying to minimize the formula to showcase the problem.

**Comment by aleb** [comment]
hm, cannot reproduce anymore

**Comment by MikeMcQuaid** [comment]
Good news.
