### ISSUE TITLE
support brew is available|installed|outdated|keg_only <PKG>

### ISSUE THREAD

**Issue by leleliu008** [Homebrew/brew#11448]
### Provide a detailed description of the proposed feature

```
brew is available|installed|outdated|keg_only <PKG>
```

### What is the motivation for the feature?

to write  shell script.

### How will the feature be relevant to at least 90% of Homebrew users?

as the default package manager used by GitHub Actions Virtual Env.

### What alternatives to the feature have been considered?

No.

**Comment by Bo98** [comment]
Does `brew info --json=v2 <pkg>` work for you?

**Comment by leleliu008** [comment]
Thank you for your reply. `brew info --json=v2 <pkg>` works for me.
