### ISSUE TITLE
Integration with version management tools like nvm, pyenv and rbenv to fulfill dependencies

### ISSUE THREAD

**Issue by egonbraun** [Homebrew/brew#11452]
### Provide a detailed description of the proposed feature

Some packages, e.g. `asciinema` have dependencies on interpreters like, in this case, Python.

Users of such languages already manage their versions using tools like `pyenv`, `nvm`, `rbenv`, etc.

It would be nice if Homebrew would integrate with such tools to fulfill the dependency on a specific language so we do not need to have multiple interpreters (sometimes even on the same version) being installed in the system.

So, if this feature existed when I run `brew info asciinema` I would be informed that Python is a dependency but its installation is not necessary since I already have it through `pyenv`. Example:

```
$ brew info asciinema                                                                                                                                                                                        template-golang-project/git/main
asciinema: stable 2.0.2 (bottled), HEAD
Record and share terminal sessions
https://asciinema.org
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/asciinema.rb
License: GPL-3.0
==> Dependencies
Required: python@3.9 ✔ (pyenv)
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 1,404 (30 days), 4,571 (90 days), 27,588 (365 days)
install-on-request: 1,400 (30 days), 4,569 (90 days), 27,358 (365 days)
build-error: 0 (30 days)
```

### What is the motivation for the feature?

Today I was trying to install `asciinema` and, as I usually do, I first check the dependencies of a package before I decide to install it in my system. In this specific case, `python@3.9` was missing.

I manage my Python versions using `pyenv` and I don't like having installations outside `pyenv` realm as it can lead to confusion and unforeseen behavior. **But that's a personal opinion**.

### How will the feature be relevant to at least 90% of Homebrew users?

I am not sure whether it will be relevant to 90% of the users, only for a part of the users that program in Python or other interpreted languages like Ruby and NodeJS.

What we can do is check how many packages depend on those languages. This could give us an idea of the impact.

I also believe that this could bring a marginal benefit when it comes to downloading bandwidth since it will be one less thing to pull from the internet. But probably this would be an irrelevant gain, I don't have data to support this.

### What alternatives to the feature have been considered?

I know that I could probably get by by using `--ignore-dependencies` but the documentation for that flag is basically saying to never use it unless you are a homebrew dev, which is definitely not my case.

**Comment by carlocab** [comment]
Similar requests have been made several times before (see, for example, #11312). This leads to configurations that would never be tested in CI, which we can't support.

Sorry!
