### ISSUE TITLE
Linuxbrew ffi not picked up by other tooling (RVM)

### ISSUE THREAD

**Issue by Lewiscowles1986** [Homebrew/brew#11458]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76cfe88b7628a8010bf98115627f6aced4ff8870
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 14ef6696fac5bc1788ec916aad6960c0a9efcafc
Core tap last commit: 15 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 40
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 40-core 64-bit ivybridge
Clang: N/A
Git: 2.31.1 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 5.4.0-73-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.5 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.5.0
/usr/bin/ruby: 2.5.1
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was just trying to use Jekyll with RVM.

brew installed `libffi` for me, but did not make it available on the system, even when using `brew link libffi`

I Got the rather opaque message that libffi.so.7 was not found. Using ldd, I was able to see a shared-object from ruby ffi library could not find the system dependency needed.

### What happened (include all command output)?

```
	 2: from /home/lewis/.rvm/gems/ruby-2.7.2/gems/ffi-1.15.1/lib/ffi.rb:2:in `<top (required)>'
	 1: from /home/lewis/.rvm/gems/ruby-2.7.2/gems/ffi-1.15.1/lib/ffi.rb:5:in `rescue in <top (required)>'
/home/lewis/.rvm/gems/ruby-2.7.2/gems/ffi-1.15.1/lib/ffi.rb:5:in `require': libffi.so.7: cannot open shared object file: No such file or directory - /home/lewis/.rvm/gems/ruby-2.7.2/gems/ffi-1.15.1/lib/ffi_c.so (LoadError)

```

### What did you expect to happen?

jekyll to install and run

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
This involves brew interaction outside of it's system, with other dependencies.


brew install libffi
brew install ruby
<- install rvm using commands pasted from their homepage
rvm install 2.7
rvm use 2.7
gem install bundler jekyll
jekyll new somefolder
jekyll serve .
```
```

**Comment by danielnachun** [comment]
This doesn't look like a Homebrew bug.  The problem is likely because `rvm` is not adding `$HOMEBREW_PREFIX/lib` to the LDFLAGS and RPATHs of the binaries it is building.  I think something like `gem install --with-ldflags="-L$HOMEBREW_PREFIX/lib -Wl,-rpath,$HOMEBREW_PREFIX/lib jekyll" will get those flags passed into there.  Please feel free to make a post in https://github.com/Homebrew/discussions/discussions under the Linux section, as that is a better place to discuss this.

**Comment by Lewiscowles1986** [comment]
This is happening at runtime, not compile time. Are you sure your response took that into account, because the ffi gem built successfully, but just didn't run, and wasn't able to pick-up it's dependencies after compilation...

**Comment by carlocab** [comment]
>This is happening at runtime, not compile time.

This makes it sound even less likely to be a Homebrew bug, as this gem shouldn't have compiled if it needed Homebrew `libffi` but couldn't find it. If it did need Homebrew `libffi` and found it at compile time but can't find it at runtime, then this is a problem with the gem, not with Homebrew.

If you'd like to continue this discussion, please take it to https://github.com/Homebrew/discussions/discussions as suggested.
