### ISSUE TITLE
"brew audit --fix --cask" - doesn't check sha256

### ISSUE THREAD

**Issue by vraravam** [Homebrew/brew#11461]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.9-68-g990d5f0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 990d5f048fa429b15b2babe7c639104ce11da152
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 16c46fe92664bcd3484e4b26381dd3b4b5212a2d
Core tap last commit: 46 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 3
HOMEBREW_EDITOR: code --goto
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED: set
HOMEBREW_VERBOSE_USING_DOTS: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-x86_64
CLT: 12.5.0.0.1.1617976050
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to create a new PR for an existing cask: https://github.com/Homebrew/homebrew-cask-versions/pull/11092

### What happened (include all command output)?

`brew audit --fix --cask` did not report that I had an incorrect `sha256`. I used to run the cask with an empty string - and the old behavior used to warn about a missing sha, but would continue and then report the expected value. This was a shortcut to copy-paste into the cask file before committing and raising the PR. Now, it didn't download the asset and so didn't complain at all for a random string (only complained about missing/empty, and the length of the random string).

### What did you expect to happen?

I expected that the sha would actually be checked after downloading the asset.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Edit a pre-existing cask file (say `Casks/ferdi-beta.rb` in the `homebrew-cask-versions` repo
2. Replace the `sha256` string with another random string of the same length, but not the same as the downloaded file.
3. See the absence of any error.
```

**Comment by Rylan12** [comment]
Try adding `--online` to `brew audit`

**Comment by vraravam** [comment]
Thanks @Rylan12 : that works! Maybe I missed the documentation, could that be verified please? Closing the ticket for now.

**Comment by Rylan12** [comment]
From `brew help audit`:

```
      --online                     Run additional, slower style checks that
                                   require a network connection.
```

To check the `sha256` requires downloading the file and, thus, a network connection. This command (well really it's `brew audit --appcast --online` I believe) is what's run by our CI.

**Comment by vraravam** [comment]
So, the github issue template (while submitting the PR) doesn't mention `--online`, nor the `--appcast`

**Comment by Rylan12** [comment]
You could open a PR if you think it should be added. I don't know if there's a reason as to why it isn't already there.
