### ISSUE TITLE
Issue with `brew bump-cask-pr` 

### ISSUE THREAD

**Issue by ondrejfuhrer** [Homebrew/brew#11485]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

When trying to update `figma` cask to its latest version I noticed an issue with the bump command. The issue seems to be that it tries to download an arm version (that is probably not yet available), but I have intel chip computer.

So the check that is inside the cask
```ruby
if Hardware::CPU.intel?
```
doesn't seem to work properly.

If I run `brew reinstall figma` then it downloads it from the correct source 🤔  So my guess is that the `bump-cask-pr` is doing something "special" here?

### Command that failed

brew bump-cask-pr figma --version 98.13.0

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

git config --get homebrew.devcmdrun
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
/usr/local/opt/curl/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.9-110-g273b06c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.4\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=figma\+repo\%3AHomebrew\%2Fhomebrew-cask\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --dump-header /private/tmp/github_api_headers20210603-10286-dfdtyj
==> Downloading https://desktop.figma.com/mac/Figma-98.13.0.zip
/usr/local/opt/curl/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.9-110-g273b06c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.4\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://desktop.figma.com/mac/Figma-98.13.0.zip
Already downloaded: /Users/ondrej.fuehrer/Library/Caches/Homebrew/downloads/0e12250ebf7ced5ef4e861367ec6dbd41742b0db2785f12fa88ebced54f3a752--Figma-98.13.0.zip
==> Verifying checksum for '0e12250ebf7ced5ef4e861367ec6dbd41742b0db2785f12fa88ebced54f3a752--Figma-98.13.0.zip'
Warning: Cannot verify integrity of '0e12250ebf7ced5ef4e861367ec6dbd41742b0db2785f12fa88ebced54f3a752--Figma-98.13.0.zip'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "213753d01235bc39925553bb78d8d079553885516cadf2e18702ccc6da46a8a8"
/usr/local/opt/curl/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.9-110-g273b06c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.4\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://desktop.figma.com/mac-arm/Figma-98.13.0.zip
==> Downloading https://desktop.figma.com/mac-arm/Figma-98.13.0.zip
/usr/local/opt/curl/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.9-110-g273b06c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.4\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --head https://desktop.figma.com/mac-arm/Figma-98.13.0.zip
/usr/local/opt/curl/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.9-110-g273b06c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.4\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/user/Library/Caches/Homebrew/downloads/2922699d15fae55a28ced0546fd7a99aebf3e91b8928cd6cb4fe7df0345f5226--Figma-98.13.0.zip.incomplete https://desktop.figma.com/mac-arm/Figma-98.13.0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
Error: Failed to download resource "figma"
Download failed: https://desktop.figma.com/mac-arm/Figma-98.13.0.zip
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:407:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:404:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:142:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:193:in `fetch_resource'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:203:in `fetch_cask'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:140:in `bump_cask_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

REPLACE THIS TEXT WITH THE OUTPUT

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

alexanderwillner/tap
buo/cask-upgrade
clementtsang/bottom
codacy/tap
getsentry/tools
golangci/tap
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
nrlquaker/createzap
romkatv/powerlevel10k
vitorgalvao/tiny-scripts

</code></pre></details>

**Comment by SMillerDev** [comment]
Transfering since this is an issue with a `brew` command, not a cask

**Comment by ondrejfuhrer** [comment]
Ah, sorry, I thought I created it in `brew` repo 🤦‍♂️  sorry, my bad.

**Comment by carlocab** [comment]
I think this is on purpose so that `bump-cask-pr` is able to update both the Intel branch and the ARM branch of a cask at the same time.

**Comment by ondrejfuhrer** [comment]
So the fix for the particular cask is to add the version inside the `if..else` so that there are different version for different platforms? Since apparently the desired version doesn't exist when trying to download it.

Then I wonder if there should be a different `livecheck` 🤔

**Comment by cho-m** [comment]
@ondrejfuhrer Yes, if the release versions deviate, then you can track separate version numbers and livechecks.
Usually the version numbers will converge in a future release, as long as both are still supported by the developer.

```console
❯ curl https://desktop.figma.com/mac/RELEASE.json
{ "url": "https://desktop.figma.com/mac/Figma-98.13.0.zip", "version": "98.13.0", "stage": 100 }

❯ curl https://desktop.figma.com/mac-arm/RELEASE.json
{ "url": "https://desktop.figma.com/mac-arm/Figma-98.11.0.zip", "version": "98.11.0", "stage": 100 }
```

**Comment by ondrejfuhrer** [comment]
@cho-m so I assume something like that. https://github.com/Homebrew/homebrew-cask/pull/106770 

The only thing is that now livecheck only reports non-arm version 🤔  but I guess it is better than before?

**Comment by cho-m** [comment]
The livecheck will show versions based on the hardware you are running on.

For Intel Macs, this will only show the Intel release
For M1 Macs, this will show the ARM release when run natively and the Intel release when run via Rosetta.

`brew bump-cask-pr` should (hopefully) deal with both.

**Comment by ondrejfuhrer** [comment]
@cho-m I just wonder, since `bump-cask-pr` only accepts single version as an argument, to which version that will be applied 🤔  I guess the one the command is running on?

**Comment by cho-m** [comment]
Closing this as Homebrew/homebrew-cask#106770 has been merged.

Bump behavior works by using `livecheck` output for other branch, e.g.
```console
❯ arch -x86_64 brew livecheck figma
figma : 98.13.0 ==> 98.13.0

❯ arch -x86_64 brew bump-cask-pr --dry-run figma --version 98.13.0
==> Downloading https://desktop.figma.com/mac/Figma-98.13.0.zip
...
==> Downloading https://desktop.figma.com/mac-arm/Figma-98.11.0.zip
...

❯ brew livecheck figma
figma : 98.11.0 ==> 98.11.0

❯ brew bump-cask-pr --dry-run figma --version 98.11.0
==> Downloading https://desktop.figma.com/mac-arm/Figma-98.11.0.zip
...
==> Downloading https://desktop.figma.com/mac/Figma-98.13.0.zip
...
```
