### ISSUE TITLE
Copying terminology in man

### ISSUE THREAD

**Issue by Arthur-Milchior** [Homebrew/brew#11489]
### Provide a detailed description of the proposed feature

On https://docs.brew.sh/Formula-Cookbook there is a terminology list. I suggest copying it on https://docs.brew.sh/Manpage or at least adding a link

### What is the motivation for the feature?

I started by reading man. I could not find anything defining casks in it. I know I can install a formula and don't know what a formula is, what casks is, etc... This make the man page hard to understand and the official answer is not easy to find without opening random page until the right one is found

### How will the feature be relevant to at least 90% of Homebrew users?

I'd be surprise if 90% of users read the man page. So by this account, I guess the man page is not relevant. But for the people who have the habit to still use man, it is relevant in that it make the documentation more self contained. If you are a seasoned user, you can skip it and search for exactly what you want, as you probably already do given the size. And otherwise it allow to avoid moving to browser to understand

### What alternatives to the feature have been considered?

Creating a clearly marked glossary page, so that it gets easier to find this list

**Comment by Rylan12** [comment]
This is good feedback. Would simply putting a link to the Formula Cookbook section be enough?

**Comment by zachauten** [comment]
@Rylan12 I think if we're going to update the man page, it would be better to put the actual info there so you don't have to leave the CLI to read it. But there are several links to other docs in the man page, so maybe a link to the cookbook is warranted if a glossary takes up a lot of room.

**Comment by MikeMcQuaid** [comment]
👍🏻 to having this table (or an equivalent) displayed in the manpage. I think we should define all/only the terms that we use in the manpage in there.

**Comment by ran-dall** [comment]
> I think we should define all/only the terms that we use in the manpage in there.

I strongly agree with this statement; thought I'd make a comment to emphasize. 😁

**Comment by Arthur-Milchior** [comment]
> This is good feedback. Would simply putting a link to the Formula Cookbook section be enough?

As far as I'm concerned, it would have already helped. Because there were little way for me to find the link in the first place.
The main trouble is that the link may not have appeared when i was searching for the term in the man page, and a link to a glossary, unless it is very visible, would still have taken time to be discovered.

Thanks for agreeing on principle with my feedback.

**Comment by Rylan12** [comment]
I opened a PR: #11493
