### ISSUE TITLE
Branch vpr-24686 and bad ruby interpreted

### ISSUE THREAD

**Issue by talyuk** [Homebrew/brew#1148]
After upgrading to macos 10.12, my brew is broken. It always says:

`/usr/local/bin/brew: /usr/local/Homebrew/Library/brew.rb: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: bad interpreter: No such file or directory
/usr/local/bin/brew: line 21: /usr/local/Homebrew/Library/brew.rb: Undefined error: 0`

I checked homebrew branch and it was **vpr-24686**. Ok, checkout to master, pull and my brew works. But after some time brew switches to vpr-24686 branch and again breaks.
Latest commit at this branch was pushed in 2013.
I tried to **branch -D vpr-24686**, but it not works. Merge master to this branch not works too.

**Comment by MikeMcQuaid** [comment]
`git checkout master; git fetch; git reset --hard origin/master; brew update --force` should sort you out.
