### ISSUE TITLE
Error: "pxpx" is not available on PyPI.

### ISSUE THREAD

**Issue by walles** [Homebrew/brew#11494]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.9-121-g654c78c
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 654c78c2d7aec2620f006f9e5bd07ec498c32d5d
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ff25e529a5eaf23b54bf223a55fa1edb624a6695
Core tap last commit: 81 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.SNP0TQWvNT/org.macosforge.xquartz:0
HOMEBREW_EDITOR: code -w
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0.5 build 1205
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am creating a new formula for this Python contraption: <https://github.com/walles/px>

As part of that, [the instructions](https://docs.brew.sh/Python-for-Formula-Authors#installing) say:

> You can use brew update-python-resources to help you write resource stanzas. To use it, simply run `brew update-python-resources <formula>`.

### What happened (include all command output)?

```sh
/u/l/H/L/T/w/homebrew-johan (walles/px|✔) [1] $ brew update-python-resources walles/johan/px
Error: Could not infer PyPI package name from URL:
  https://github.com/walles/px.git
/u/l/H/L/T/w/homebrew-johan (walles/px|✔) [1] $ brew update-python-resources --package-name pxpx walles/johan/px
Error: "pxpx" is not available on PyPI.
/u/l/H/L/T/w/homebrew-johan (walles/px|✔) [1] $
```

### What did you expect to happen?

Since `pxpx` *is* available on PyPI...

<https://pypi.org/project/pxpx/>

... I expected `brew update-python-resources` to do its thing to my formula.

I did *not* expect it to claim that `pxpx` is not available on PyPI, since `pxpx` *is* in fact available on PyPI.

So the error message is wrong.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# This can be reproduced on any package, the error message is the same, I just picked lsof at random:

brew update-python-resources --package-name pxpx lsof

# This prints: Error: "pxpx" is not available on PyPI.
#
# But since "pxpx" *is* available on PyPI, the error message is wrong.
#
# I'd be happy for one of:
# * Fix the error message to say what's *actually* wrong
# * Make brew update-python-resources work when specifying "--package-name pxpx"
```

**Comment by Rylan12** [comment]
The reason you're getting this message is that while a wheel _is_ available from PyPI, there's no _source archive_ that can be downloaded. If you go to https://pypi.org/project/pxpx/#files there's only `pxpx-1.4.0-py2.py3-none-any.whl` while other PyPI packages (e.g. [`youtube-dl`](https://pypi.org/project/youtube_dl/#files)) you'll see the wheel files in addition to a source file that usually ends in `.tar.gz`)

If you can publish a source archive to PyPI as well that should solve this. I don't know anything about PyPI publishing, though, so I can't help you with that.

**Comment by walles** [comment]
I worked around this by adding the required dependencies by hand, so I'm clear.

And I'm also pretty bad at PyPI Python packaging unfortunately 😛.

But just having the error message improved to say that it's the `.tar.gz` that's missing that would have saved me some time!

**Comment by Rylan12** [comment]
Would you be willing to open a PR to improve the message? Here's the line where the message is printed:

https://github.com/Homebrew/brew/blob/654c78c2d7aec2620f006f9e5bd07ec498c32d5d/Library/Homebrew/utils/pypi.rb#L178

**Comment by damonmitchellsr1** [comment]
Fix bug

**Comment by walles** [comment]
I don't think I'll be making a PR, sorry.
