### ISSUE TITLE
brew audit --strict /path/to/myformula.rb wants Ruby 1.9 hash syntax

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#1149]
```
iMac-TMP:~ joe$ brew audit --strict ./purescript.rb 
purescript:
  * C: 28: col 27: Use the new Ruby 1.9 hash syntax.
Error: 1 problem in 1 formula
iMac-TMP:~ joe$ brew audit --strict purescript
iMac-TMP:~ joe$ 
```

**Comment by MikeMcQuaid** [comment]
Thanks for opening an issue. @reitermarkus Any thoughts on a workaround for this?

**Comment by ilovezfs** [comment]
>Thanks for opening an issue

I can pester you about it on Slack, too, if you'd like :)

**Comment by reitermarkus** [comment]
> Any thoughts on a workaround for this?

I don't think there is one. The only **reliable** way for this to work consistently is to use a separate RuboCop config file for formulae which doesn't rely on `Exclude: 'Taps/**/*.rb'`.

**Comment by MikeMcQuaid** [comment]
@reitermarkus What about doing the inverse and having different configuration only for `Library/Homebrew`?

**Comment by MikeMcQuaid** [comment]
Seems to be fixed now.
