### ISSUE TITLE
Travis still suffers from #1100

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#1150]
https://github.com/Homebrew/homebrew-core/blob/master/.travis.yml

It seems that Travis was relying on git cleanup too, and doesn't pass --cleanup to test-bot, so it still suffers from the bug that was addressed in #1100 

https://travis-ci.org/Homebrew/homebrew-core/jobs/162711389

**Comment by MikeMcQuaid** [comment]
This is a different bug actually I think because Travis has stuff pre-installed into a `/usr/local` (not `/usr/local/Homebrew` installation location.

**Comment by MikeMcQuaid** [comment]
`--cleanup` is set automatically for Jenkins but not for Travis because it wasn't needed in the past: 
https://github.com/Homebrew/homebrew-test-bot/blob/05b815025ebaec9e478861796dc3e673b4b53378/cmd/brew-test-bot.rb#L1048

The guard for `JENKINS_HOME` here should be removed.

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/Homebrew/homebrew-test-bot/pull/10
