### ISSUE TITLE
Bottles fail to download/install on MacOS 12 (Monterey)

### ISSUE THREAD

**Issue by shaunsingh** [Homebrew/brew#11523]
Note: I understand homebrew gives a warning to not open issues on prerelease versions 

```zsh
Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
```

However 
1. I already opened a PR to add macOS 12 support, and was told to create this issue. See: https://github.com/Homebrew/brew/pull/11504#issuecomment-857453938
2. This isn't an issue with the formulae themselves, but one with Homebrew 

### `brew config` output

```shell
~
❯ brew config
HOMEBREW_VERSION: 3.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9657303ed2c484a4bd8f7527706940f9e4d43354
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7fcd6cd7965e62d2d112a6f146da38ba5cb6fe56
Core tap last commit: 81 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.76.0 => /usr/bin/curl
macOS: 12.0-arm64
CLT: 13.0.0.0.1.1622682579
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/python3.7-config
  /usr/local/bin/python3.7m-config
  /usr/local/bin/python3.9-config
  /usr/local/bin/python3-config

Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.
```

### 

- [x] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install a formula using homebrew on macOS 12 (e.g. `brew install neofetch). 

### What happened (include all command output)?

~
❯ brew install neofetch
Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Error: neofetch: no bottle available!
You can try to install from source with:
  brew install --build-from-source neofetch
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

### What did you expect to happen?

Neofetch should use the macOS 11 bottle. since all formulas bottled on macOS 11 would work as expected on macOS 12.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install neofetch
```

**Comment by carlocab** [comment]
CC @fxcoudert

**Comment by shaunsingh** [comment]
cc @fxcoudert

**Comment by Bo98** [comment]
> `HEAD: 9657303ed2c484a4bd8f7527706940f9e4d43354`

Monterey support is not present in this version: https://github.com/Homebrew/brew/blob/9657303ed2c484a4bd8f7527706940f9e4d43354/Library/Homebrew/os/mac/version.rb.

It will be a part of 3.1.12.

If you wish to be on the bleeding-edge channel of updates (i.e. latest `master` commit), you can consider opting in by running a [dev-cmd](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/dev-cmd) once.

**Comment by shaunsingh** [comment]
Thanks for that, I didn't realize homebrew versions were seperate from the `master` branch. It works as expected, now, thank you!

**Comment by gperdomor** [comment]
> It will be a part of 3.1.12.

@Bo98 Hi, thanks for the clarification, do you have an ETA for that? :D

**Comment by carlocab** [comment]
We don't have a set release schedule so it's hard to give an ETA. However, I don't recommend using Homebrew's stable tag for use with a beta version of macOS (it'll delay your getting bug fixes for the beta, for example). So if you want to use `brew` on macOS 12, the best thing to do is this:

> If you wish to be on the bleeding-edge channel of updates (i.e. latest `master` commit), you can consider opting in by running a [dev-cmd](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/dev-cmd) once.

Alternatively, you can `export HOMEBREW_DEVELOPER=1`.

**Comment by MikeMcQuaid** [comment]
3.1.12 has been released now.
