### ISSUE TITLE
Can't find or install brew formula: ripgrip

### ISSUE THREAD

**Issue by johnathanz** [Homebrew/brew#11526]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9657303ed2c484a4bd8f7527706940f9e4d43354
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 776fcbf72fd0a20f673351cba5b9b825863fc144
Core tap last commit: 40 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 11.0.0 build 1100
Git: 2.21.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install [ripgrip (formulae.brew.sh link)](https://formulae.brew.sh/formula/ripgrep), but brew can't find it

### What happened (include all command output)?

JZ-MBP:~ johnathan$ brew list ripgrip
Error: No such keg: /usr/local/Cellar/ripgrip
JZ-MBP:~ johnathan$ brew install ripgrip
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "ripgrip".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
JZ-MBP:~ johnathan$ 

### What did you expect to happen?

brew should've found ripgrip when using `brew list`, allowing me to run `brew install` for ripgrip on my Mac

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
JZ-MBP:~ johnathan$ brew doctor
Your system is ready to brew.
JZ-MBP:~ johnathan$ brew list ripgrip
Error: No such keg: /usr/local/Cellar/ripgrip
JZ-MBP:~ johnathan$ brew install ripgrip
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "ripgrip".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
JZ-MBP:~ johnathan$
```

**Comment by gromgit** [comment]
There really isn't any formula or cask called `ripgrip`. You might thinking of `ripgrep` instead.

**Comment by johnathanz** [comment]
omg 🤦‍♀️  🤦‍♀️  🤦‍♀️  🤦‍♀️

Well, that's 1.5 hours well spent 😛 

Thanks a lot @gromgit !
