### ISSUE TITLE
Sierra, Golang, Pouring locked

### ISSUE THREAD

**Issue by yageek** [Homebrew/brew#1157]
After upgrading to sierra, I uninstall all the homebrew elements I had and wanted to install them again.

The first step I did was to install golang.

After triggering `brew install -v golang`, the archive is correctly downloaded. Then homebrew seems to unarchive it but it is locked after:
```
x go/1.7.1/libexec/api/except.txt
x go/1.7.1/libexec/api/go1.1.txt
x go/1.7.1/libexec/api/go1.2.txt
x go/1.7.1/libexec/api/go1.3.txt
x go/1.7.1/libexec/api/go1.4.txt
x go/1.7.1/libexec/api/go1.5.txt
x go/1.7.1/libexec/api/go1.6.txt
x go/1.7.1/libexec/api/go1.7.txt
x go/1.7.1/libexec/api/go1.txt
x go/1.7.1/libexec/api/next.txt
x go/1.7.1/libexec/api/README
x go/1.7.1/bin/go
x go/1.7.1/bin/godoc
x go/1.7.1/bin/gofmt
# Seems to be locked
```

I use the system ruby for now through `rbenv` ( `ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]`)

The homebrew version:
```
Homebrew 1.0.4
Homebrew/homebrew-core (git revision 9c21; last commit 2016-09-26)
```

**Comment by MikeMcQuaid** [comment]
How long did you wait? Also: sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by yageek** [comment]
Seems to be that after updating to sierra, Kaspersky was slowing down everything. 
I removed it and now I have to wait a little but the build finishes after 30 seconds.

Thanks for your help
