### ISSUE TITLE
Error when using "brew extract": "Calling `cellar` in a bottle block is disabled"

### ISSUE THREAD

**Issue by weisserw** [Homebrew/brew#11593]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 3.2.0-45-gff48561
ORIGIN: https://github.com/Homebrew/brew
HEAD: ff48561df1f23101e5f76648be7dafde5a1856f8
Last commit: 77 seconds ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 62c780c8e41726f9034652a79d2ca205386961f7
Core tap last commit: 22 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: N/A

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/will/.pyenv/shims/python3.9-config
  /Users/will/.pyenv/shims/python-config
  /Users/will/.pyenv/shims/python3-config

(note: I cannot remove this warning as I need pyenv installed on this system)
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Use brew extract to extract and install a specific version of a package

### What happened (include all command output)?
```
% brew tap-new tmp/tmp
Initialized empty Git repository in /usr/local/Homebrew/Library/Taps/tmp/homebrew-tmp/.git/
[main (root-commit) 6c4d9e9] Create tmp/tmp tap
 ...
% brew extract --version=14.17.1 node tmp/tmp
==> Searching repository history
Error: node: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb:15
```
### What did you expect to happen?

I expected the formula to be extracted without errors.

### Step-by-step reproduction instructions (by running `brew` commands)

See above. I also tried doing a `brew update-reset` before running the above commands. This error is reproducible for every developer I have talked to who is running a script we use to set up our systems. As of last month or so the script was working fine so my assumption this is something that broke in Homebrew recently.

**Comment by carlocab** [comment]
I don't think the `node` formula ever had a version 14.17.1 since that's the current version of the `node@14` formula. I suppose the error message could be more informative here.

Can you try
```
brew extract --version=14.17.1 node@14 tmp/tmp
```
?

**Comment by weisserw** [comment]
`brew extract --version=14.17.1 node@14 tmp/tmp` works, but I can't use the same command to get an older version from the same formula:

```
brew extract --version=14.14.0 node@14 tmp/tmp
==> Searching repository history
Error: node@14: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb:14
```

**Comment by carlocab** [comment]
That's because the earliest `node@14` version is 14.15.0. See https://github.com/Homebrew/homebrew-core/commit/708834a7c78ca33a3f291c207fc0ffdce4e3e79b.

You should be able to do it with the `node` formula, but it's not working for me either...

**Comment by carlocab** [comment]
Not really sure why
```
brew extract --version=14.14.0 node tmp/tmp
```
isn't working.

However, I imagine `brew extract --version=x.y.z node` should also check the versioned Node formulae when it can't find the requested version in the main one.

CC @alebcay who'd know more about this.

**Comment by gromgit** [comment]
> You should be able to do it with the `node` formula, but it's not working for me either...

Me neither. I'm guessing that the extracted formula has to be loaded in order to change the `Node` class name, and is therefore triggering parse errors due to its old-style `bottle` block syntax.

If that's the case, there's a varying limit on how far back you can extract formulae, based on how up-to-date your Homebrew software is.

**Comment by gromgit** [comment]
@weisserw I've written a simplified version of `brew extract` that does the bare minimum (that I know of), so it should do what you need. You can try it out by tapping my dev repo:
```
brew tap gromgit/dev
brew yank node 14.14.0 tmp/tmp
```
It currently doesn't extract the latest revision of the chosen formula, but that doesn't seem to be an issue in this specific case.

**Comment by LiuShuai26** [comment]
exactly same error shows when i am trying to install older version of boost (boost@1.72). `brew extract` works fine until i upgrade brew. Is there any other way to install older version formula?

**Comment by alebcay** [comment]
Sorry I'm late to this conversation. `brew extract` is supposed to be able to support older versions of formulae that are now invalid due to DSL changes (i.e. ignore what appears to be an invalid formula). [We accomplish that by monkeypatching in deprecated/removed stanzas](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/extract.rb#L10). Not sure if this needs to be adjusted to accommodate the `bottle` block changes.

**Comment by gromgit** [comment]
It probably does, since I wrote `brew yank` a month after the last known commit to `extract.rb`. I would've fixed it at the source, but Ruby gives me a headache for some reason. :grin:

**Comment by alebcay** [comment]
We run `Formulary.from_contents` on the formula contents pulled from a Git revision. This is the actual source of the exception being raised (`FormulaUnreadableError`). It turns out that we can pass `Formulary.from_contents(..., ignore_errors: true)` and the exception (at least in this case) will not be raised.

I'll have a PR for this soon but if someone wants to beat me to it, have at it. This will hopefully be a trivial fix.

**Comment by gromgit** [comment]
Thanks for the pointer, @alebcay ! I might as well take a crack at fixing it then.
