### ISSUE TITLE
Postinstall fails for openssl@1.1 and gnutls formula on Apple Silicon Mac

### ISSUE THREAD

**Issue by brentward** [Homebrew/brew#11595]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.0-43-g47d5150
ORIGIN: https://github.com/Homebrew/brew
HEAD: 47d5150c333784c956db25c3d8ff8ffdd616bb68
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f726665062954d90454a550b7acb808e4cea2184
Core tap last commit: 19 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-arm64
CLT: 12.5.0.22.9
Xcode: 12.5.1
Rosetta 2: false

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
   M Formula/gnutls.rb
   M Formula/openssl@1.1.rb
  ?? Formula/.openssl@1.1.rb.swp

Warning: Homebrew's "bin" was not found in your PATH.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

When I try to install openssl or gnutls I get postinstall errors. I previously opened a ticket on this and it was closed because they could not reproduce it.

However I have now determined what is happening and how to fix it. My path isn't getting passed into the sandbox session so the security cli tool needs the full path specified. I have a pull request to address this forthcoming.

https://github.com/Homebrew/brew/issues/10181

On Apple Silicon Mac when brew installed openssl@1.1 and gnutls as dependencies for pyenv and gpg respectively I got warnings:

==> Installing pyenv dependency: openssl@1.1
==> Pouring openssl@1.1-1.1.1i.arm64_big_sur.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall openssl@1.1`
and

==> Installing gnupg dependency: gnutls
==> Pouring gnutls-3.6.15.arm64_big_sur.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall gnutls`
respectively. So I attempted the postinstall commands as instructed

### What happened (include all command output)?

Command output of: brew postinstall openssl@1.1
```
❯ brew postinstall openssl@1.1 -dv
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
==> Postinstalling openssl@1.1
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201229-26088-ca0bns.sb nice ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/postinstall.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall openssl@1.1`
==> An exception occurred within a child process:
 Errno::ENOENT: No such file or directory - security

/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:124:in ``'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:124:in `macos_post_install'
/opt/homebrew/Library/Homebrew/extend/os/mac/on_os.rb:8:in `on_macos'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:115:in `post_install'
/opt/homebrew/Library/Homebrew/formula.rb:1062:in `block (2 levels) in run_post_install'
/opt/homebrew/Library/Homebrew/formula.rb:904:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1061:in `block in run_post_install'
/opt/homebrew/Library/Homebrew/utils.rb:530:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1050:in `run_post_install'
/opt/homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'

```
 
Command output of: brew postinstall gnutls
```
❯ brew postinstall gnutls -dv     
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb
==> Postinstalling gnutls
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201229-26242-1g3cec.sb nice ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/postinstall.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall gnutls`
==> An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - security

/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:73:in ``'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:73:in `post_install'
/opt/homebrew/Library/Homebrew/formula.rb:1062:in `block (2 levels) in run_post_install'
/opt/homebrew/Library/Homebrew/formula.rb:904:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1061:in `block in run_post_install'
/opt/homebrew/Library/Homebrew/utils.rb:530:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1050:in `run_post_install'
/opt/homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```

### What did you expect to happen?

Postintall scripts should have ran without failing due to an exception. Both of them seem to be failing doing the same thing which is it can't find the security command when run in backticks like this: certs_list = `security find-certificate -a -p #{keychains.join(" ")}` 
here: https://github.com/Homebrew/homebrew-core/blob/239ebee1f006dd5dcd658e5603936decc1aea4dc/Formula/openssl%401.1.rb#L124
and here: https://github.com/Homebrew/homebrew-core/blob/239ebee1f006dd5dcd658e5603936decc1aea4dc/Formula/gnutls.rb#L73

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Reproducable on my machine:
This can be reproduced by executing:

brew install pyenv
brew postinstall openssl@1.1
```
and
```
brew install gpg
brew postinstall gnutls
```
```

**Comment by brentward** [comment]
It is indeed because I had the HOMEBREW_PATH set in my environment. I figured it out while while working through the code and I confirmed it by not setting that variable and post-install succeeded.

**Comment by MikeMcQuaid** [comment]
Solution: don't set `HOMEBREW_PATH`. I don't think it's worth changing code for a single user report here but we'll keep our eyes out and change this if it happens again.

**Comment by carlocab** [comment]
@brentward if you want to use an environment variable for things like `$VAR/sbin` to refer to Homebrew's `sbin`, I suggest using `HOMEBREW_PREFIX`, e.g. `$HOMEBREW_PREFIX/sbin`.

**Comment by brentward** [comment]
@cacology Thanks! That is what I ended up doing. I started using `eval $(/opt/homebrew/bin/brew shellenv)` as suggested above to set the path and env vars and using the `HOMEBREW_PREFIX` in the rest of my config files.
