### ISSUE TITLE
Time out again and again

### ISSUE THREAD

**Issue by liuzexin** [Homebrew/brew#1160]
When I run `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

I get this error 
`fatal: unable to access 'https://github.com/Homebrew/brew/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1`

I have open the vpn,what should I do?

**Comment by MikeMcQuaid** [comment]
@liuzexin Run `git clone https://github.com/Homebrew/brew/` manually and speak to GitHub if it doesn't work as Homebrew cannot fix that.
