### ISSUE TITLE
Why does Homebrew not distribute binaries ?

### ISSUE THREAD

**Issue by freebrowser1** [Homebrew/brew#11607]
### Provide a detailed description of the proposed feature

Unlike Linux package managers like yum, dnf (Centos), apt (Ubuntu / Debian), Homebrew downloads source code for most packages and compiles it locally, which is usually time consuming. Weird, because macOS has far less distributions which is just Intel64 or ARM64 for each macOS version.
Linux had *per version* several distros and then also for both Intel64 and ARM64 and possibly even Intel32 for each version, which is far more complicated. And yet, binaries are distributed.

So why does Homebrew not distribute binaries ? 

### What is the motivation for the feature?

Far less time consuming at installing and updating.

### How will the feature be relevant to at least 90% of Homebrew users?

Very well.

### What alternatives to the feature have been considered?

No idea.

**Comment by gromgit** [comment]
Homebrew absolutely _does_ distribute binaries, and by default: https://docs.brew.sh/Bottles

Please show us the command output that led you to believe otherwise.

**Comment by freebrowser1** [comment]
`brew install mariadb`
`brew install sshfs`

**Comment by carlocab** [comment]
`brew install mariadb` installs a binary for me. Homebrew no longer distributes `sshfs` on macOS because it requires macFUSE, which is no longer open source. You can, however, install `sshfs` using a third-party tap. We still distribute binaries for `sshfs` on Linux.

If these build from source for you, then the likely explanation is that you're not running a supported configuration.

What is the output of `brew config` and `brew doctor`?

**Comment by freebrowser1** [comment]
````% brew config
HOMEBREW_VERSION: 3.2.0-61-gaa14e48
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: aa14e48f4e73d2f4c7d178d7b8a2f528b74995d7
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fdd61f9d93c4b525cd913419a1a83ad1a2ae447f
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /Users/user/homebrew
HOMEBREW_REPOSITORY: /Users/user/homebrew
HOMEBREW_CELLAR: /Users/user/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
XQuartz: 2.7.11 => /opt/X11
userpc:~/scratch % 
````

`brew doctor` dumps lots of warnings, but I cannot judge which are correct.
I have installed it in my home folder but actually it should be installed in /opt/homebrew. Is that really necessary ?

````
userpc:~/scratch % brew doctor            

````
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  python@2
  meson-internal
  pygtk
  pygobject

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  gconf
  ilmbase
  orbit
  py2cairo

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libavcodec.52.100.0.dylib
  /usr/local/lib/libavcore.0.16.0.dylib
  /usr/local/lib/libavdevice.52.2.2.dylib
  /usr/local/lib/libavfilter.1.70.0.dylib
  /usr/local/lib/libavformat.52.88.0.dylib
  /usr/local/lib/libavutil.50.36.0.dylib
  /usr/local/lib/libfdk-aac.2.dylib
  /usr/local/lib/libmp3lame.dylib
  /usr/local/lib/libmysqlclient.20.dylib
  /usr/local/lib/libswscale.0.12.0.dylib
  /usr/local/lib/libusb-1.0.0.dylib
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/big_endian.h
  /usr/local/include/binary_log_types.h
  /usr/local/include/byte_order_generic.h
......... 700 .h files !
  

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libfdk-aac.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/libavcodec.pc
  /usr/local/lib/pkgconfig/libavcore.pc
  /usr/local/lib/pkgconfig/libavdevice.pc
  /usr/local/lib/pkgconfig/libavfilter.pc
  /usr/local/lib/pkgconfig/libavformat.pc
  /usr/local/lib/pkgconfig/libavutil.pc
  /usr/local/lib/pkgconfig/libswscale.pc
  /usr/local/lib/pkgconfig/mysqlclient.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libavcodec.a
  /usr/local/lib/libavcore.a
  /usr/local/lib/libavdevice.a
  /usr/local/lib/libavfilter.a
  /usr/local/lib/libavformat.a
  /usr/local/lib/libavutil.a
  /usr/local/lib/libfdk-aac.a
  /usr/local/lib/libmysqlclient.a
  /usr/local/lib/libmysqld-debug.a
  /usr/local/lib/libmysqld.a
  /usr/local/lib/libmysqlservices.a
  /usr/local/lib/libswscale.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  imath
  openexr
  youtube-dl

Warning: Some installed formulae are not readable:
  gnome-mime-data: Unsupported special dependency :x11

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /Users/user/homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
   M Formula/libfuse.rb
   M Formula/sshfs.rb

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
````

**Comment by MikeMcQuaid** [comment]
> Warning: Your Homebrew's prefix is not /usr/local.
> Some of Homebrew's bottles (binary packages) can only be used with the default
> prefix (/usr/local).
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Twitter or any other official channels. You are responsible for resolving
> any issues you experience while you are running this
> unsupported configuration.

This is why you are not getting binaries. I'm pretty sure it'll literally output a similar message every time you run `brew install`, too.

Install Homebrew into the supported location and you'll get binaries.
