### ISSUE TITLE
brew services commands not working on Big Sur M1

### ISSUE THREAD

**Issue by daBee** [Homebrew/brew#11618]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09f7bc27a99469cf947431df4754737dfbadb31d
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5c3836dd0756581a3ebbe608636fa795b2d0ee1c
Core tap last commit: 42 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: bbedit
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.32.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-arm64
CLT: 12.5.0.22.9
Xcode: 12.5.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew services start nginx ==> should start nginx.  It doesn't.  `brew services` options don't work.  

Using `sudo` works, but that's not recommended.

### What happened (include all command output)?

```
>> 20:52:23 rich@HQ3 ~ ➜ brew services start nginx
==> Successfully started `nginx` (label: homebrew.mxcl.nginx)                 # not started up
>> 20:53:57 rich@HQ3 ~ ➜ ps -ax | grep nginx
61929 ttys004    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox nginx
```

There is no nginx.pid file at this point. 

```
>> 20:55:14 rich@HQ3 ~ ➜ nmap_open_ports localhost
Starting Nmap 7.91 ( https://nmap.org ) at 2021-06-28 20:55 EDT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000055s latency).
Not shown: 995 closed ports
PORT      STATE SERVICE
22/tcp    open  ssh
445/tcp   open  microsoft-ds
3689/tcp  open  rendezvous
5432/tcp  open  postgresql
49154/tcp open  unknown
```

### What did you expect to happen?

nginx to behave according to `brew` instructions.  Nothing is happening.  

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
As above.
```

**Comment by daBee** [comment]
Console reports:

```
$ brew services stop nginx
Stopping `nginx`... (might take a while)
==> Successfully stopped `nginx` (label: homebrew.mxcl.nginx)

**Console**:
error	07:01:41.413849-0400	kernel	Sandbox: ContextStoreAgen(404) deny(1) mach-lookup com.apple.ocspd
error	07:01:43.002834-0400	analyticsd	[Fault] Transform 'MT_com.apple.BSDServices.ScriptingLanguageUse_v2' hit unrecoverable error with reason='<private>' and context='<private>' with event='<private>'

$ brew services start nginx
==> Successfully started `nginx` (label: homebrew.mxcl.nginx)

**Console**:
error	07:01:45.659728-0400	analyticsd	[Fault] Transform 'MT_com.apple.BSDServices.ScriptingLanguageUse_v2' hit unrecoverable error with reason='<private>' and context='<private>' with event='<private>'
error	07:01:52.361865-0400	kernel	Sandbox: com.apple.WebKit(634) deny(1) mach-lookup com.apple.diagnosticd

```

**Comment by MikeMcQuaid** [comment]
Does this only happen with `nginx` or everything? What's the output in the `nginx` error log?

**Comment by daBee** [comment]
There is nothing in the `error.log` at all.  `pgbouncer` works just fine.

**Comment by daBee** [comment]
Any chance the maintainer could let me know what I should be seeing in the Security Control Panel?

**Comment by MikeMcQuaid** [comment]
> Any chance the maintainer could let me know what I should be seeing in the Security Control Panel?

I have no idea what this means.

Can you start `nginx` outside of `brew services`? Does this work after restarting your machine? It sounds a lot like a local machine/configuration issue?

**Comment by daBee** [comment]
Big Sur permissions in the Security & Privacy control panel.  I've seen nginx in there before, but I can't find it now.  

This failed:

```
>> 14:08:34 rich@HQ3 1.21.0 ➜ launchctl load /opt/homebrew/Cellar/nginx/1.21.0/homebrew.mxcl.nginx.plist
Load failed: 5: Input/output error
```
Restarted box, reinstalled nginx twice.  Here is something strange though:

```
>> 14:21:58 rich@HQ3 ~ ➜ nginx
nginx: [alert] could not open error log file: open() "/opt/homebrew/var/log/nginx/error.log" failed (13: Permission denied)
2021/06/29 14:22:02 [emerg] 1841#0: open() "/opt/homebrew/var/log/error.log" failed (13: Permission denied)
```

The error.log is nowhere in my conf files.  I've deleted it before and it's being erased.  I want everything to be in `/opt/homebrew/var/log/*.log`.  

`$ sudo chmod 777 error.log
$ nginx`

OK, **THAT** works.  But the original reason all this started, still persists.  I can't load a properly configured `VHost`.  It redirects to the `default_server`.

**Comment by andreasloe** [comment]
I am having similar problems on a M1 with
`brew install gv`

**Comment by daBee** [comment]
Did you check the console for anything?

**Comment by andreasloe** [comment]
Maybe my error is not connected to the one above. A software I am using requires gv and says that I should install this using brew. I deinstalled Homebrew and reinstalled it (this time in English, not German) and managed this without error messages. But it does not find gv:
`Error: No available formula or cask with the name "gv".`
Either this was not ported to M1 or I am making something completely wrong here.

**Comment by carlocab** [comment]
Homebrew does not ship any software called `gv` via official channels. It's possible that this is provided by an external tap. Please contact whoever provided your software for instructions on how to install `gv`.

**Comment by andreasloe** [comment]
Thx.

**Comment by MikeMcQuaid** [comment]
Sorry, this is not a Homebrew bug but a configuration issue with your local machine @daBee.

**Comment by daBee** [comment]
Any suggestions as to what is wrong?  It was working until it didn't.  Nothing was configured out of the ordinary.  The box is months old.

**Comment by MikeMcQuaid** [comment]
You'll need to figure this out yourself, sorry.

**Comment by daBee** [comment]
Just sat down and tried it and it works this morning.  <sigh>  

Thank you.  Cheers
