### ISSUE TITLE
"Brew install" should be renamed to "Brew me a" 

### ISSUE THREAD

**Issue by pauladam316** [Homebrew/brew#11617]
### Provide a detailed description of the proposed feature

The command for installing a new package should be renamed to "Brew me a"

### What is the motivation for the feature?

It sounds cooler

### How will the feature be relevant to at least 90% of Homebrew users?

The average user will chuckle every time they install something, and I think thats worth making everyone relearn the command

### What alternatives to the feature have been considered?

Probably none? I'm not sure anyone else would waste their time thinking about this

**Comment by carlocab** [comment]
Try
```
brew tap homebrew/aliases
brew alias me=install
brew me hello
```

**Comment by MikeMcQuaid** [comment]
What @carlocab said 😁. I like this idea and your humility here. I'd consider adding this as an official alias if we have a few more people wanting this.
