### ISSUE TITLE
homebrew getting exceptions trying to install tar file from private repo

### ISSUE THREAD

**Issue by aviatam** [Homebrew/brew#11623]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.0-87-g5a5db3a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5a5db3ab968518b82b54c9b043f357ed30d077e0
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9d2063685565b06c5b19a285ffda3b094e222d1f
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.0.22.9
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install a home brew app from github private repo 

### What happened (include all command output)?

trying to install new private repo .tar.gz via brew 
1. brew tap datorama/ferret git@github.com:datorama/homebrew-ferret.git
2. brew install ferret \\ our app 
➜  ~ brew install ferret          
==> Installing ferret from datorama/ferret
==> Downloading https://github.com/datorama/ferret/releases/download/1.0.12/ferret-mac-1.0.12.tar.gz
Error: unknown keyword: timeout
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/datorama/homebrew-ferret/formula/lib/private_strategy.rb:117:in `_fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:405:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:142:in `fetch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1985:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1133:in `fetch'
/usr/local/Homebrew/Library/Homebrew/install.rb:299:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:207:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

### What did you expect to happen?

this used to work until 2 weeks ago 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
trying to install new private repo .tar.gz via brew 
1. brew tap datorama/ferret git@github.com:datorama/homebrew-ferret.git
2. brew install ferret \\ our app 
➜  ~ brew install ferret          
==> Installing ferret from datorama/ferret
==> Downloading https://github.com/datorama/ferret/releases/download/1.0.12/ferret-mac-1.0.12.tar.gz
Error: unknown keyword: timeout
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/datorama/homebrew-ferret/formula/lib/private_strategy.rb:117:in `_fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:405:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:142:in `fetch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1985:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1133:in `fetch'
/usr/local/Homebrew/Library/Homebrew/install.rb:299:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:207:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
You'll need to report this to that repository, the error is in their code.

**Comment by aviatam** [comment]
@MikeMcQuaid no change was done in the code

**Comment by aviatam** [comment]
@MikeMcQuaid are you saying this is a github issue ?

**Comment by MikeMcQuaid** [comment]
@aviatam They need to change their code. They are relying on private APIs which have changed.

**Comment by jef** [comment]
@aviatam, they're probably using some custom GitHub private repo download strategy. They'll need to update their `_fetch` method signature to include `timeout:` to the parameters.
