### ISSUE TITLE
Running on a Issue Trying Install Brew on Big Sur M1

### ISSUE THREAD

**Issue by padagoal** [Homebrew/brew#11627]
### `brew config` output

```shell
--
```

### `brew doctor` output

```shell
--
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Im trying install Brew using the command posted on the official Page:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

### What happened (include all command output)?

This return:

==> Downloading and installing Homebrew...
HEAD is now at 5a5db3ab9 Merge pull request #11239 from MikeMcQuaid/audit_core_bottle_disabled_unneeded
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
^Cfatal: index-pack failed
Failed during: /opt/homebrew/bin/brew update --force --quiet

### What did you expect to happen?

--

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
--
```

**Comment by carlocab** [comment]
This is an issue with your Internet connection. Please see the [discussions](https://github.com/Homebrew/discussions) page for related problems and solutions. [This thread](https://github.com/Homebrew/discussions/discussions/666) may be particularly useful.

**Comment by padagoal** [comment]
Thanks @carlocab ! I will check the information on the thread!
