### ISSUE TITLE
`brew bump-cask-pr` fails on tap

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/brew#11633]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.0-95-g45b2b54
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 45b2b549ff188762a39f3614bcfb9adf95db6ea8
Last commit: 16 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 34284fe7bb4dcafc59d32f659d2ab352753fe40b
Core tap last commit: 13 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
```

### `brew doctor` output

```shell
﻿Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php
  six

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
  ?? Formula/graal.rb
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Update a cask in a personal tap.

### What happened (include all command output)?

Instead I got a weird error that printed part of the cask.
```console
[sean] /u/l/H/L/T/s/homebrew-saltstack (main)> brew bump-cask-pr --version=3003.1  smillerdev/saltstack/saltstack
Error: Cask 'i)
  end

  conflicts_with cask: ["saltstack-3001", "saltstack-3000"]

  pkg "salt-#{version}-py3-x86_64.pkg"

  uninstall pkgutil: "com.saltstack.salt"
end
' is unavailable: No Cask with this name exists.
```

### What did you expect to happen?

Open a PR to update the cask

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap smillerdev/saltstack
brew bump-cask-pr --version=3003.1  smillerdev/saltstack/saltstack
```

**Comment by issyl0** [comment]
My initial thoughts for what this problem was were wrong, given it only appeared on this tap and none of the others I tested afterwards. Now it seems like it's just choking on the comment at the top of the file and thus not replacing anything? If I remove the comment at the top of the `SMillerDev/saltstack/saltstack` file, `brew bump-cask-pr` works fine. 😕

**Comment by issyl0** [comment]
Not sure if this warrants an audit here (I don't really know about Casks), given the `CaskLoader` expects a file to start with `cask "name" do` and not a comment, I fixed up the comments in the tap to be inside the Cask block. Alternative fixes (for if any other user does this in taps we don't know about) is to skip the comment lines or allow them optionally in the regex, but I'm not sure how big a problem this is and whether it warrants that. Although this was a pretty confusing bug to figure out.

**Comment by SMillerDev** [comment]
Great find, I do see this as a bug in brew though. I really don't expect features to crash on code comments.

**Comment by carlocab** [comment]
Improving `utils/ast` would probably help in avoiding having to develop a regex that works for all sorts of corner cases for `bump-{formula,cask}-pr`.

**Comment by SMillerDev** [comment]
Does that mean https://github.com/Homebrew/homebrew-cask/pull/108383/files would also fail on a `bump-cask-pr`?
