### ISSUE TITLE
`brew` dot-files for packages that require ENV setting

### ISSUE THREAD

**Issue by viztor** [Homebrew/brew#11632]
### Provide a detailed description of the proposed feature

have a homebrew-specific shell configuration file somewhere, so the user can just add one liner (in the example of using .zshrc)
`source $HOMEBREW_DOTFILES/.zshrc' to their own ~/.zshrc
while the $HOMEBREW_DOTFILES/.zshrc could be generated or updated by homebrew.
the homebrew can either generate a specific .shellrc or generate all .shellrc, but let the user decide which to choose.

### What is the motivation for the feature?

I ran into a issue today since I only updated the package, and tried uninstall / re-install, though most of the time they should be the same, it is ideal that the user wouldn't have to do those manually with a package manager.

### How will the feature be relevant to at least 90% of Homebrew users?

Although I do not imagine most of the packages would need this, but as most of developers do use package managers and things-alike, it would affect them when setting things up.

### What alternatives to the feature have been considered?

Alternatively, the user can have a section in their dot files flagged out by comment which homebrew can identify and update.

The other alternative is to have a command like `brew dotfile` that print all the required commands to put in shell initialization script for packages installed.

**Comment by MikeMcQuaid** [comment]
This is an interesting idea but I don't think it's something we'd want to enable as running this much code automatically is a security risk. I don't think `brew install foo` should imply that you run code by `foo` automatically next time you open a shell.
