### ISSUE TITLE
Error: No available formula with the name ...

### ISSUE THREAD

**Issue by Arkanine** [Homebrew/brew#1163]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Hi,
Every time I try to install something, I receive:
Error: No available formula with the name "wget" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

Please help me figure out what is the cause of this issue.

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by Arkanine** [comment]
No probs,

176-67-23-67:~ roman$ brew gist-logs wget
Error: No available formula with the name "wget" 

176-67-23-67:~ roman$ brew update
Already up-to-date.

176-67-23-67:~ roman$ brew update
Already up-to-date.

176-67-23-67:~ roman$ brew doctor
Your system is ready to brew.

176-67-23-67:~ roman$ brew gist-logs wget
Error: No available formula with the name "wget" 

OS X El Capitan
Version 10.11.6

**Comment by MikeMcQuaid** [comment]
Can I see your `brew config` output?

**Comment by Arkanine** [comment]
Sure
HOMEBREW_VERSION: 1.0.3-31-gb432f8e
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b432f8e9cb2d03c8f1d7a65b9d6df2e04b3d37a7
Last commit: 33 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/brew.git
Core tap HEAD: b432f8e9cb2d03c8f1d7a65b9d6df2e04b3d37a7
Core tap last commit: 33 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.7.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_91
macOS: 10.11.6-x86_64
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
X11: N/A

**Comment by Arkanine** [comment]
Also I forgot to Check that Command Line Tools for Xcode (CLT) and/or Xcode are up to date:

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by MikeMcQuaid** [comment]
> Core tap ORIGIN: https://github.com/Homebrew/brew.git

This is the issue. Run `rm -rf /usr/local/Library/Homebrew/Taps/homebrew/homebrew-core` and then try to reinstall.

**Comment by Arkanine** [comment]
@MikeMcQuaid thank you! My problem is solved.

**Comment by MikeMcQuaid** [comment]
Glad to hear it!
