### ISSUE TITLE
tput: unknown terminal "tmux-256color-italic"

### ISSUE THREAD

**Issue by vbauerster** [Homebrew/brew#1165]
After upgrading to tmux 2.1, and applying italics font support as described [there] (https://github.com/tmux/tmux/blob/2.1/FAQ#L355-L383)
I've noticed that brew outputs strange messages like
`tput: unknown terminal "tmux-256color-italic"`
instead of icons.

Indeed my $TERM variable says `tmux-256color-italic` while inside tmux.
Is it possible to have brew recognise such term?

**Comment by zmwangx** [comment]
This unfortunately has nothing to do with brew and you should report to tmux.
