### ISSUE TITLE
reinstate brew switch

### ISSUE THREAD

**Issue by pahjbo** [Homebrew/brew#11658]
### Provide a detailed description of the proposed feature

brew switch to work as it did before deprecation.

### What is the motivation for the feature?

In my development environment I sometimes need to pin a formula as newer versions have breaking changes. Occasionally I like to try the latest version to see if the breaking changes have been fixed, and if they have not, then to return to my old installed and pinned formula. Brew switch made this quick and easy (along with HOMEBREW_NO_INSTALL_CLEANUP=1)

### How will the feature be relevant to at least 90% of Homebrew users?

It is not - it is for experts, however it was a small but useful utility - without it brew pin is almost useless.

### What alternatives to the feature have been considered?

brew extract to create an explicitly @ versioned formula in a local tap - however this is a much more long winded  to get the same workflow

**Comment by MikeMcQuaid** [comment]
I'd suggest extracting the previous code from `brew switch` into an external command, sorry.
