### ISSUE TITLE
Automatically add Time Machine exclusions

### ISSUE THREAD

**Issue by dovchinnikov** [Homebrew/brew#11677]
### Provide a detailed description of the proposed feature

Please add an ability exclude downloadable files from Time Machine backups.

### What is the motivation for the feature?

Automatization

### How will the feature be relevant to at least 90% of Homebrew users?

They won't have to exclude the downloadable stuff themselves OR if they don't exclude it themselves, then they will have lighter backups out of the box.

### What alternatives to the feature have been considered?

https://github.com/stevegrunwell/asimov 
I've found it inconvenient and it excludes too much.

**Comment by MikeMcQuaid** [comment]
What specifically are you wanting to exclude from what and why?

**Comment by dovchinnikov** [comment]
I want to exclude huge packages that are not essential and can be re-downloaded later to reduce the size of the backup. 
I have manually excluded `/usr/local/Homebrew`, `/usr/local/Cellar`, and `/urs/local/Caskroom`. It will be inconvenient to restore from such backup. I would be happy to exclude `openjdk` and `go`, but it means I have to do it manually, hence I'm asking for an ability to add TM exclusions by package.

**Comment by MikeMcQuaid** [comment]
Homebrew's cache is already excluded from Time Machine.

> It will be inconvenient to restore from such backup.

I'd recommend using `brew bundle` for this.

For the rest, sorry: passing on this for now (as I've never heard this request before).
