### ISSUE TITLE
issues with the latest XCode

### ISSUE THREAD

**Issue by williamcodes** [Homebrew/brew#1167]
Looks like the latest version of XCode doesn't play nicely with brew. Here's a [github issue](http://stackoverflow.com/questions/33728905/qt-creator-project-error-xcode-not-set-up-properly-you-may-need-to-confirm-t/35098040#35098040) with the question and an answer with 38 upvotes that involves modifying a file inside a brew keg. Given the number of upvotes, it seems like this is a problem for a lot of people and the fix is fairly effective. Can we make the fix directly to the keg so people don't have to fix this bug themselves? Also, is there a better repo to post this issue on?

**Comment by devmage** [comment]
Looks like your ticket here may be related to https://github.com/Homebrew/brew/issues/972

**Comment by MikeMcQuaid** [comment]
This is an issue with Qt itself so should be reported to them. If there's a change we can make in the Qt formula we'll accept a pull request to do so. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!
