### ISSUE TITLE
M1 should install on /usr/local

### ISSUE THREAD

**Issue by aspacca** [Homebrew/brew#11690]
### Provide a detailed description of the proposed feature

Install brew on /usr/local also on M1 platform.
/usr/local/bin is in the default path on Big Sur (minimum OS requirement for M1 devices) and there would be no need to tweak with any shell environments or override $PATH on other tools.

### What is the motivation for the feature?

Having brew installing on /opt/hombrew on M1 is reducing a lot the seamless user experience that brew used to have.
/usr/local/bin is in the default path on Big Sur without needing to tweak any shell environment and will be available to tools that don't use a shell.

Just as an example on JetBrains IDEs in order to access brew installation on build and debug features requires overriding the path in every single IDE.

If I remember well back then homebrew was advertising the fact to install in /usr/local as a better feature over other alternatives.

### How will the feature be relevant to at least 90% of Homebrew users?

This will impact 100% of Hombrew users on M1.

### What alternatives to the feature have been considered?

The alternatives require a lot of custom setup for every different tools (as explained in the JetBrains example).

**Comment by carlocab** [comment]
Sorry, but this isn't going to happen. You could maybe patch `brew` to let you do it, but you'll be on your own with that.

See this issue for a discussion of Homebrew's prefix on ARM: https://github.com/Homebrew/brew/issues/9177

**Comment by claui** [comment]
> Having brew installing on /opt/hombrew on M1 is reducing a lot the seamless user experience that brew used to have.

Sorry but there’s no way around it for the time being.
Intel bottles are pinned to the `/usr/local` prefix. We need to provide both architectures to users, which means ARM Homebrew has to live somewhere else.

> Just as an example on JetBrains IDEs in order to access brew installation on build and debug features requires overriding the path in every single IDE.

I figured it should be possible to set it for all apps.
Have you tried [launchctl setenv](https://stackoverflow.com/a/3756686)?

**Comment by aspacca** [comment]
I read https://github.com/Homebrew/brew/issues/9177
Honestly I wouldn't expect people complaining about stuff in `/usr/local`, for me having the contrary is rather annoying, not only for path but also for pkgconfig etc, as mentioned in the discussion.
Indeed for me this mean there's no more reason to favour Homebrew over other package managers, sadly.

**Comment by carlocab** [comment]
Sorry to hear that! I hope you're able to find a package manager that works for you.

**Comment by aspacca** [comment]
@carlocab thanks

Indeed I see that the main point of the discussion was to provide both platform binaries at the same time, but that should be feasible building universal ones.
I don't see this mentioned in the issue, was it ever considered?

**Comment by claui** [comment]
@aspacca We’ve had long discussions about that internally and in #7857 but ultimately decided against it.

**Comment by carlocab** [comment]
Homebrew tried to support building universal binaries before but they never worked properly and were a nightmare to maintain.

**Comment by MikeMcQuaid** [comment]
> Just as an example on JetBrains IDEs in order to access brew installation on build and debug features requires overriding the path in every single IDE.

I suggest making a feature request to JetBrains.

**Comment by aspacca** [comment]
what would the feature that JetBrains has to implement?

Just anothe example:
`LIBRARY_PATH=/opt/homebrew/lib/ make`

this is now requested for building from sources in a lot of cases

**Comment by MikeMcQuaid** [comment]
> what would the feature that JetBrains has to implement?

I don't use it so I don't really know. Presumably you didn't have to add `/usr/local/bin` to the PATH there so perhaps `/opt/homebrew/bin` should be in the default PATH.

> shoukd I open a feature request to `make` maintainers? ;)

Projects shouldn't assume Homebrew is installed in a certain PATH and, where they have made this assumption, that should be fixed.

**Comment by aspacca** [comment]
@MikeMcQuaid I assume you are familiar with what's stated on own Homebrew's FAQ:
https://docs.brew.sh/FAQ#why-does-homebrew-prefer-i-install-to-usrlocal

This was historically a selling point for Homebrew to push itself over other package managers.

No projects in the examples I've posted have made any assumption about Homebrew, they don't even know about it or care for it (sorry if this could sound unfair).

Having `/opt/homebrew` as Hombrew prefix on M1 is against your own FAQ, it breaks the seamless experience Homebrew user used to have and that the project itself has always pushed for.

**Comment by carlocab** [comment]
@aspacca -- I don't think this is your intention, but you make it sound like the choice to use `/opt/homebrew` instead of `/usr/local` wasn't carefully considered. What is the point of bringing up the FAQ here? What do you hope to achieve?

We're well aware of the benefits of using `/usr/local`, but decided that the benefits of using `/opt/homebrew` outweighed those. That may make using Homebrew inconvenient for you. We find that regrettable, but not regrettable enough to change anything, because using `/opt/homebrew` is still what works best for most of our users -- despite the inconvenience it imposes on some.

**Comment by aspacca** [comment]
@carlocab I just answered to the Homebrew project leader that suggested to ask for a feature request to JetBrains so that they could add `/opt/homebrew/bin` to the default path, while he stated that external tools should not make any assumption on Homebrew installed path.

The issue was already closed, I was not the one to bring it up again ;)

**Comment by carlocab** [comment]
That answer is either totally disingenuous or complete nonsense. In either case, there's no point in continuing this discussion.

**Comment by MikeMcQuaid** [comment]
> No projects in the examples I've posted have made any assumption about Homebrew, they don't even know about it or care for it (sorry if this could sound unfair).

@aspacca macOS developer tools do tend to care about Homebrew because millions of macOS developers use Homebrew.

> Having `/opt/homebrew` as Homebrew prefix on M1 is against your own FAQ, it breaks the seamless experience Homebrew user used to have and that the project itself has always pushed for.

It was not possible to have Rosetta 2 support for M1 (still required for tools as widely used as ElasticSearch) with Intel/Rosetta 2 binary packages and use `/usr/local` for ARM. 

Everything in software is a trade-off. `/usr/local` has some benefits and would have been better in some ways than `/opt/homebrew`, I agree. That doesn't make it the right decision.
