### ISSUE TITLE
Cloning repo with depth 1 on installation

### ISSUE THREAD

**Issue by Quantalabs** [Homebrew/brew#11693]
### Provide a detailed description of the proposed feature

Instead of cloning the homebrew repo as:
```sh
git clone https://github.com/Homebrew/brew
```
or the core repo, cloning with depth 1 will make the installation quicker:
```sh
git clone https://github.com/Homebrew/brew --depth=1
```

### What is the motivation for the feature?

After installing homebrew 2 times, I've been frustrated by the long time it takes to install, the longest of which was the cloning of the `homebrew/core` repo. 

### How will the feature be relevant to at least 90% of Homebrew users?

It will be very relevant as new users will have a quick installation, and updates for existing users will be faster and easier.

### What alternatives to the feature have been considered?

Manually installing, perhaps? However when I tried this homebrew updated, and took forever to update while cloning the `homebrew/core` repo.

**Comment by Rylan12** [comment]
We intentionally [do not support shallow clones](https://github.com/Homebrew/brew/pull/9383) per a request from GitHub. While shallow clones are faster for the initial clone step, each fetch (i.e. `brew update` run) will take much longer and be much more computationally expensive for GitHub's servers.

If you _must_ have a shallow clone, manual installation is the only option (and you'll need to manually clone the `homebrew/core` repo). Also, if you choose to do this, `brew update` will not be able to update Homebrew and its taps; you'll need to manually update them using `git`. Note, though, that we are in the process of removing the need to have the `homebrew/core` (and, eventually, `homebrew/cask`) repo(s) downloaded locally which will speed up the installation process _and_ future `brew update` runs.

See https://github.com/Homebrew/brew/issues/7050 and https://github.com/Homebrew/brew/issues/10557, among others. You may also find these GitHub blog posts to be helpful in understanding why this is the case: [Get up to speed with partial clone and shallow clone ](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) and  [Git clone: a data-driven study on cloning behaviors ](https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/)
