### ISSUE TITLE
`brew unbottled --tag=x86_64_linux` does not check Linux dependencies when run on macOS

### ISSUE THREAD

**Issue by Rylan12** [Homebrew/brew#11694]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.1-70-g5659d74
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5659d74ff59414d22e285d77a7fcfcd3c1bf0614
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 02954afbfbb2c46daf9239b22f1490c4eca8bab7
Core tap last commit: 10 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: vim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GITHUB_PACKAGES_TOKEN: set
HOMEBREW_GITHUB_PACKAGES_USER: Rylan12
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_PRY: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/opt/git/bin/git
Curl: 7.77.0 => /usr/local/opt/curl/bin/curl
macOS: 11.3-x86_64
CLT: 12.5.0.22.9
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Check whether `svgbob` was ready for a Linux bottle

### What happened (include all command output)?

```console
$ brew unbottled --tag=x86_64_linux -v svgbob
==> Populating dependency tree...
==> :x86_64_linux bottle status
svgbob: ready to bottle
```

`svgbob` is _not_ ready to bottled because `libiconv`, a Linux-only dependency (specified using `uses_from_macos`) is not yet bottled.

This is a problem if the unbottled formula is specified using `uses_from_macos` or in an `on_linux` block.

### What did you expect to happen?

`brew unbottled` to show that `svgbob` was not ready for a bottle yet because `libiconv` did not have a bottle

This is the output that I get if I change `libiconv` to a normal `depends_on` rather than a `uses_from_macos`:

```console
$ brew unbottled --tag=x86_64_linux -v svgbob
==> Populating dependency tree...
==> :x86_64_linux bottle status
svgbob: unbottled deps: libiconv
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew unbottled --tag=x86_64_linux -v svgbob
```

**Comment by Rylan12** [comment]
A potential solution for this might be to have a `HOMEBREW_FORCE_LINUX_ON_MACOS` (or similar) that allows `on_macos` and `on_linux` blocks to be executed on the opposite platforms (and likewise for `uses_from_macos`)

**Comment by MikeMcQuaid** [comment]
> A potential solution for this might be to have a `HOMEBREW_FORCE_LINUX_ON_MACOS` (or similar) that allows `on_macos` and `on_linux` blocks to be executed on the opposite platforms (and likewise for `uses_from_macos`)

This would be fine with me. I think in the `brew unbottled` case specifically, though, it'd be good to have this handled internally without needing to set any flags.

**Comment by Rylan12** [comment]
If flags were needed, `brew unbottled` would also make sure they were set. It sounds like this might go together with #11687, too (at least the `brew info`/formulae.brew.sh part).

Either way, I don't think I have the bandwidth to work on this (at least at the moment)
