### ISSUE TITLE
uninstall issue

### ISSUE THREAD

**Issue by Sajaki** [Homebrew/brew#117]
i'm running osx 10.11.4. 

### Bug reports:

I tried updating brew but got this error
```
zeus:~ Nix$ brew update
warning: unable to unlink CONTRIBUTING.md: Permission denied
warning: unable to unlink SUPPORTERS.md: Permission denied
fatal: cannot create directory at '.github': Permission denied
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
```
then i tried uninstalling
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"`
but got 
```
-e:114: undefined method `start_with?' for "/*":String (NoMethodError)
	from -e:114
```
now launching "brew" throws a big error. 

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
```

**Comment by UniqMartin** [comment]
You don't seem to have followed these steps from the issue template, that was there when you first posted but you removed since (you're seeing permission issues, right?):

- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

The error from the uninstall script is somewhat surprising. I don't think it came to the point where it was actually able to remove anything. What is the output of `which ruby` and `ruby --version`?

I think because of the permission errors, you now have a Homebrew installation in a somewhat mixed up state, where some files were updated and some were not. Please try the following:

```
sudo chown -R $(whoami) /usr/local
cd /usr/local && git reset --hard origin/master
brew update
```

Please post the output of those commands, particularly if you're still seeing error messages.

**Comment by UniqMartin** [comment]
Closing for a lack of response/information; happy to reopen once there's some activity here.

**Comment by Sajaki** [comment]
hello, 

Thanks very much for your answer. I followed your instructions and it seems to be ok again. 

`zeus:~ Nix$ brew
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
`

`zeus:~ Nix$ brew doctor
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
`

`zeus:~ Nix$ which ruby
/usr/local/bin/ruby
zeus:~ Nix$ ruby --version
ruby 1.8.4 (2005-12-24) [i686-darwin8.9.1]`

no permission errors seen running this.
`zeus:~ Nix$ sudo chown -R $(whoami) /usr/local
zeus:~ Nix$ `

finally
`eus:~ Nix$ cd /usr/local && git reset --hard origin/master
HEAD is now at 53c5089 CoreTap#install: fix clone target setting
zeus:local Nix$ 
zeus:local Nix$ brew update
warning: no common commits
remote: Counting objects: 469, done.
remote: Compressing objects: 100% (426/426), done.
remote: Total 469 (delta 27), reused 276 (delta 17), pack-reused 0
Receiving objects: 100% (469/469), 766.45 KiB | 381 KiB/s, done.
Resolving deltas: 100% (27/27), done.
From https://github.com/Homebrew/brew
 + 53c5089...12686ad master     -> origin/master  (forced update)
HEAD is now at 12686ad cmd/fetch: fix typo in doco
==> Homebrew has enabled anonymous aggregate user behaviour analytics
Read the analytics documentation (and how to opt-out) here:
  https://git.io/brew-analytics
==> Tapping homebrew/core
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 3696, done.
remote: Compressing objects: 100% (3584/3584), done.
remote: Total 3696 (delta 14), reused 627 (delta 1), pack-reused 0
Receiving objects: 100% (3696/3696), 2.84 MiB | 1.66 MiB/s, done.
Resolving deltas: 100% (14/14), done.
Checking connectivity... done.
Tapped 3572 formulae (3,722 files, 8.8M)
Already up-to-date.
`

now brew doctor works again. 

`zeus:local Nix$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /Applications/MAMP/bin/php/php5.6.10/bin/php-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libbeid.2.7.4.dylib
    /usr/local/lib/libbeidcardlayer.4.0.7.dylib
    /usr/local/lib/libbeidcommon.1.0.0.dylib
    /usr/local/lib/libbeidcommon.4.0.7.dylib
    /usr/local/lib/libbeiddialogsQT.4.0.7.dylib
    /usr/local/lib/libbeidgui.1.5.0.dylib
    /usr/local/lib/libbeidlibjni.2.7.2.dylib
    /usr/local/lib/libbeidlibopensc.2.2.0.dylib
    /usr/local/lib/libbeidlibopenscinternal.2.2.0.dylib
    /usr/local/lib/libbeidpkcs11.4.0.7.dylib
    /usr/local/lib/libbeidpkcs11.4.1.8.dylib
    /usr/local/lib/libbeidpkcs11.4.1.9.dylib
    /usr/local/lib/libicudata.48.1.1.dylib
    /usr/local/lib/libMagick++-6.Q16.3.dylib
    /usr/local/lib/libMagickCore-6.Q16.2.dylib
    /usr/local/lib/libMagickWand-6.Q16.2.dylib
    /usr/local/lib/libqt-mt.3.3.8.dylib
    /usr/local/lib/libxerces-c-3.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/fastcgi.h
    /usr/local/include/fcgi_config.h
    /usr/local/include/fcgi_stdio.h
    /usr/local/include/fcgiapp.h
    /usr/local/include/fcgimisc.h
    /usr/local/include/fcgio.h
    /usr/local/include/fcgios.h
    /usr/local/include/graphviz/arith.h
    /usr/local/include/graphviz/cdt.h
    /usr/local/include/graphviz/cgraph.h
    /usr/local/include/graphviz/color.h
    /usr/local/include/graphviz/geom.h
    /usr/local/include/graphviz/graphviz_version.h
    /usr/local/include/graphviz/gvc.h
    /usr/local/include/graphviz/gvcext.h
    /usr/local/include/graphviz/gvcjob.h
    /usr/local/include/graphviz/gvcommon.h
    /usr/local/include/graphviz/gvconfig.h
    /usr/local/include/graphviz/gvplugin.h
    /usr/local/include/graphviz/gvplugin_device.h
    /usr/local/include/graphviz/gvplugin_layout.h
    /usr/local/include/graphviz/gvplugin_loadimage.h
    /usr/local/include/graphviz/gvplugin_render.h
    /usr/local/include/graphviz/gvplugin_textlayout.h
    /usr/local/include/graphviz/gvpr.h
    /usr/local/include/graphviz/pack.h
    /usr/local/include/graphviz/pathgeom.h
    /usr/local/include/graphviz/pathplan.h
    /usr/local/include/graphviz/textpara.h
    /usr/local/include/graphviz/types.h
    /usr/local/include/graphviz/usershape.h
    /usr/local/include/graphviz/xdot.h
    /usr/local/include/ImageMagick-6/magick/accelerate.h
    /usr/local/include/ImageMagick-6/magick/animate.h
    /usr/local/include/ImageMagick-6/magick/annotate.h
    /usr/local/include/ImageMagick-6/magick/api.h
    /usr/local/include/ImageMagick-6/magick/artifact.h
    /usr/local/include/ImageMagick-6/magick/attribute.h
    /usr/local/include/ImageMagick-6/magick/blob.h
    /usr/local/include/ImageMagick-6/magick/cache-view.h
    /usr/local/include/ImageMagick-6/magick/cache.h
    /usr/local/include/ImageMagick-6/magick/channel.h
    /usr/local/include/ImageMagick-6/magick/cipher.h
    /usr/local/include/ImageMagick-6/magick/client.h
    /usr/local/include/ImageMagick-6/magick/coder.h
    /usr/local/include/ImageMagick-6/magick/color.h
    /usr/local/include/ImageMagick-6/magick/colormap.h
    /usr/local/include/ImageMagick-6/magick/colorspace.h
    /usr/local/include/ImageMagick-6/magick/compare.h
    /usr/local/include/ImageMagick-6/magick/composite.h
    /usr/local/include/ImageMagick-6/magick/compress.h
    /usr/local/include/ImageMagick-6/magick/configure.h
    /usr/local/include/ImageMagick-6/magick/constitute.h
    /usr/local/include/ImageMagick-6/magick/decorate.h
    /usr/local/include/ImageMagick-6/magick/delegate.h
    /usr/local/include/ImageMagick-6/magick/deprecate.h
    /usr/local/include/ImageMagick-6/magick/display.h
    /usr/local/include/ImageMagick-6/magick/distort.h
    /usr/local/include/ImageMagick-6/magick/distribute-cache.h
    /usr/local/include/ImageMagick-6/magick/draw.h
    /usr/local/include/ImageMagick-6/magick/effect.h
    /usr/local/include/ImageMagick-6/magick/enhance.h
    /usr/local/include/ImageMagick-6/magick/exception.h
    /usr/local/include/ImageMagick-6/magick/feature.h
    /usr/local/include/ImageMagick-6/magick/fourier.h
    /usr/local/include/ImageMagick-6/magick/fx.h
    /usr/local/include/ImageMagick-6/magick/gem.h
    /usr/local/include/ImageMagick-6/magick/geometry.h
    /usr/local/include/ImageMagick-6/magick/hashmap.h
    /usr/local/include/ImageMagick-6/magick/histogram.h
    /usr/local/include/ImageMagick-6/magick/identify.h
    /usr/local/include/ImageMagick-6/magick/image-view.h
    /usr/local/include/ImageMagick-6/magick/image.h
    /usr/local/include/ImageMagick-6/magick/ImageMagick.h
    /usr/local/include/ImageMagick-6/magick/layer.h
    /usr/local/include/ImageMagick-6/magick/list.h
    /usr/local/include/ImageMagick-6/magick/locale_.h
    /usr/local/include/ImageMagick-6/magick/log.h
    /usr/local/include/ImageMagick-6/magick/magic.h
    /usr/local/include/ImageMagick-6/magick/magick-baseconfig.h
    /usr/local/include/ImageMagick-6/magick/magick-config.h
    /usr/local/include/ImageMagick-6/magick/magick-type.h
    /usr/local/include/ImageMagick-6/magick/magick.h
    /usr/local/include/ImageMagick-6/magick/MagickCore.h
    /usr/local/include/ImageMagick-6/magick/matrix.h
    /usr/local/include/ImageMagick-6/magick/memory_.h
    /usr/local/include/ImageMagick-6/magick/method-attribute.h
    /usr/local/include/ImageMagick-6/magick/methods.h
    /usr/local/include/ImageMagick-6/magick/mime.h
    /usr/local/include/ImageMagick-6/magick/module.h
    /usr/local/include/ImageMagick-6/magick/monitor.h
    /usr/local/include/ImageMagick-6/magick/montage.h
    /usr/local/include/ImageMagick-6/magick/morphology.h
    /usr/local/include/ImageMagick-6/magick/opencl.h
    /usr/local/include/ImageMagick-6/magick/option.h
    /usr/local/include/ImageMagick-6/magick/paint.h
    /usr/local/include/ImageMagick-6/magick/pixel-accessor.h
    /usr/local/include/ImageMagick-6/magick/pixel.h
    /usr/local/include/ImageMagick-6/magick/policy.h
    /usr/local/include/ImageMagick-6/magick/prepress.h
    /usr/local/include/ImageMagick-6/magick/PreRvIcccm.h
    /usr/local/include/ImageMagick-6/magick/profile.h
    /usr/local/include/ImageMagick-6/magick/property.h
    /usr/local/include/ImageMagick-6/magick/quantize.h
    /usr/local/include/ImageMagick-6/magick/quantum.h
    /usr/local/include/ImageMagick-6/magick/random_.h
    /usr/local/include/ImageMagick-6/magick/registry.h
    /usr/local/include/ImageMagick-6/magick/resample.h
    /usr/local/include/ImageMagick-6/magick/resize.h
    /usr/local/include/ImageMagick-6/magick/resource_.h
    /usr/local/include/ImageMagick-6/magick/segment.h
    /usr/local/include/ImageMagick-6/magick/semaphore.h
    /usr/local/include/ImageMagick-6/magick/shear.h
    /usr/local/include/ImageMagick-6/magick/signature.h
    /usr/local/include/ImageMagick-6/magick/splay-tree.h
    /usr/local/include/ImageMagick-6/magick/statistic.h
    /usr/local/include/ImageMagick-6/magick/stream.h
    /usr/local/include/ImageMagick-6/magick/string_.h
    /usr/local/include/ImageMagick-6/magick/studio.h
    /usr/local/include/ImageMagick-6/magick/threshold.h
    /usr/local/include/ImageMagick-6/magick/timer.h
    /usr/local/include/ImageMagick-6/magick/token.h
    /usr/local/include/ImageMagick-6/magick/transform.h
    /usr/local/include/ImageMagick-6/magick/type.h
    /usr/local/include/ImageMagick-6/magick/utility.h
    /usr/local/include/ImageMagick-6/magick/version.h
    /usr/local/include/ImageMagick-6/magick/widget.h
    /usr/local/include/ImageMagick-6/magick/xml-tree.h
    /usr/local/include/ImageMagick-6/magick/xwindow.h
    /usr/local/include/ImageMagick-6/Magick++/Blob.h
    /usr/local/include/ImageMagick-6/Magick++/CoderInfo.h
    /usr/local/include/ImageMagick-6/Magick++/Color.h
    /usr/local/include/ImageMagick-6/Magick++/Drawable.h
    /usr/local/include/ImageMagick-6/Magick++/Exception.h
    /usr/local/include/ImageMagick-6/Magick++/Geometry.h
    /usr/local/include/ImageMagick-6/Magick++/Image.h
    /usr/local/include/ImageMagick-6/Magick++/Include.h
    /usr/local/include/ImageMagick-6/Magick++/Montage.h
    /usr/local/include/ImageMagick-6/Magick++/Pixels.h
    /usr/local/include/ImageMagick-6/Magick++/STL.h
    /usr/local/include/ImageMagick-6/Magick++/TypeMetric.h
    /usr/local/include/ImageMagick-6/Magick++.h
    /usr/local/include/ImageMagick-6/wand/animate.h
    /usr/local/include/ImageMagick-6/wand/compare.h
    /usr/local/include/ImageMagick-6/wand/composite.h
    /usr/local/include/ImageMagick-6/wand/conjure.h
    /usr/local/include/ImageMagick-6/wand/convert.h
    /usr/local/include/ImageMagick-6/wand/deprecate.h
    /usr/local/include/ImageMagick-6/wand/display.h
    /usr/local/include/ImageMagick-6/wand/drawing-wand.h
    /usr/local/include/ImageMagick-6/wand/identify.h
    /usr/local/include/ImageMagick-6/wand/import.h
    /usr/local/include/ImageMagick-6/wand/magick-image.h
    /usr/local/include/ImageMagick-6/wand/magick-property.h
    /usr/local/include/ImageMagick-6/wand/magick-wand.h
    /usr/local/include/ImageMagick-6/wand/magick_wand.h
    /usr/local/include/ImageMagick-6/wand/MagickWand.h
    /usr/local/include/ImageMagick-6/wand/method-attribute.h
    /usr/local/include/ImageMagick-6/wand/mogrify.h
    /usr/local/include/ImageMagick-6/wand/montage.h
    /usr/local/include/ImageMagick-6/wand/pixel-iterator.h
    /usr/local/include/ImageMagick-6/wand/pixel-wand.h
    /usr/local/include/ImageMagick-6/wand/stream.h
    /usr/local/include/ImageMagick-6/wand/wand-view.h
    /usr/local/include/lauxlib.h
    /usr/local/include/lua.h
    /usr/local/include/luaconf.h
    /usr/local/include/lualib.h
    /usr/local/include/neon/ne_207.h
    /usr/local/include/neon/ne_acl.h
    /usr/local/include/neon/ne_alloc.h
    /usr/local/include/neon/ne_auth.h
    /usr/local/include/neon/ne_basic.h
    /usr/local/include/neon/ne_compress.h
    /usr/local/include/neon/ne_dates.h
    /usr/local/include/neon/ne_defs.h
    /usr/local/include/neon/ne_i18n.h
    /usr/local/include/neon/ne_locks.h
    /usr/local/include/neon/ne_md5.h
    /usr/local/include/neon/ne_props.h
    /usr/local/include/neon/ne_redirect.h
    /usr/local/include/neon/ne_request.h
    /usr/local/include/neon/ne_session.h
    /usr/local/include/neon/ne_socket.h
    /usr/local/include/neon/ne_ssl.h
    /usr/local/include/neon/ne_string.h
    /usr/local/include/neon/ne_uri.h
    /usr/local/include/neon/ne_utils.h
    /usr/local/include/neon/ne_xml.h
    /usr/local/include/neon/ne_xmlreq.h
    /usr/local/include/pcre.h
    /usr/local/include/pcre_scanner.h
    /usr/local/include/pcre_stringpiece.h
    /usr/local/include/pcrecpp.h
    /usr/local/include/pcrecpparg.h
    /usr/local/include/pcreposix.h
    /usr/local/include/readline/chardefs.h
    /usr/local/include/readline/history.h
    /usr/local/include/readline/keymaps.h
    /usr/local/include/readline/readline.h
    /usr/local/include/readline/rlconf.h
    /usr/local/include/readline/rlstdc.h
    /usr/local/include/readline/rltypedefs.h
    /usr/local/include/readline/tilde.h
    /usr/local/include/subversion-1/mod_dav_svn.h
    /usr/local/include/subversion-1/svn_auth.h
    /usr/local/include/subversion-1/svn_base64.h
    /usr/local/include/subversion-1/svn_client.h
    /usr/local/include/subversion-1/svn_cmdline.h
    /usr/local/include/subversion-1/svn_config.h
    /usr/local/include/subversion-1/svn_ctype.h
    /usr/local/include/subversion-1/svn_dav.h
    /usr/local/include/subversion-1/svn_delta.h
    /usr/local/include/subversion-1/svn_diff.h
    /usr/local/include/subversion-1/svn_error.h
    /usr/local/include/subversion-1/svn_error_codes.h
    /usr/local/include/subversion-1/svn_fs.h
    /usr/local/include/subversion-1/svn_hash.h
    /usr/local/include/subversion-1/svn_io.h
    /usr/local/include/subversion-1/svn_md5.h
    /usr/local/include/subversion-1/svn_nls.h
    /usr/local/include/subversion-1/svn_opt.h
    /usr/local/include/subversion-1/svn_path.h
    /usr/local/include/subversion-1/svn_pools.h
    /usr/local/include/subversion-1/svn_props.h
    /usr/local/include/subversion-1/svn_quoprint.h
    /usr/local/include/subversion-1/svn_ra.h
    /usr/local/include/subversion-1/svn_ra_svn.h
    /usr/local/include/subversion-1/svn_repos.h
    /usr/local/include/subversion-1/svn_sorts.h
    /usr/local/include/subversion-1/svn_string.h
    /usr/local/include/subversion-1/svn_subst.h
    /usr/local/include/subversion-1/svn_time.h
    /usr/local/include/subversion-1/svn_types.h
    /usr/local/include/subversion-1/svn_utf.h
    /usr/local/include/subversion-1/svn_version.h
    /usr/local/include/subversion-1/svn_wc.h
    /usr/local/include/subversion-1/svn_xml.h
    /usr/local/include/unicode/appendable.h
    /usr/local/include/unicode/brkiter.h
    /usr/local/include/unicode/bytestream.h
    /usr/local/include/unicode/bytestrie.h
    /usr/local/include/unicode/bytestriebuilder.h
    /usr/local/include/unicode/caniter.h
    /usr/local/include/unicode/chariter.h
    /usr/local/include/unicode/dbbi.h
    /usr/local/include/unicode/docmain.h
    /usr/local/include/unicode/dtintrv.h
    /usr/local/include/unicode/errorcode.h
    /usr/local/include/unicode/icudataver.h
    /usr/local/include/unicode/icuplug.h
    /usr/local/include/unicode/idna.h
    /usr/local/include/unicode/localpointer.h
    /usr/local/include/unicode/locid.h
    /usr/local/include/unicode/messagepattern.h
    /usr/local/include/unicode/normalizer2.h
    /usr/local/include/unicode/normlzr.h
    /usr/local/include/unicode/parseerr.h
    /usr/local/include/unicode/parsepos.h
    /usr/local/include/unicode/platform.h
    /usr/local/include/unicode/ppalmos.h
    /usr/local/include/unicode/ptypes.h
    /usr/local/include/unicode/putil.h
    /usr/local/include/unicode/pwin32.h
    /usr/local/include/unicode/rbbi.h
    /usr/local/include/unicode/rep.h
    /usr/local/include/unicode/resbund.h
    /usr/local/include/unicode/schriter.h
    /usr/local/include/unicode/std_string.h
    /usr/local/include/unicode/strenum.h
    /usr/local/include/unicode/stringpiece.h
    /usr/local/include/unicode/stringtriebuilder.h
    /usr/local/include/unicode/symtable.h
    /usr/local/include/unicode/ubidi.h
    /usr/local/include/unicode/ubrk.h
    /usr/local/include/unicode/ucasemap.h
    /usr/local/include/unicode/ucat.h
    /usr/local/include/unicode/uchar.h
    /usr/local/include/unicode/ucharstrie.h
    /usr/local/include/unicode/ucharstriebuilder.h
    /usr/local/include/unicode/uchriter.h
    /usr/local/include/unicode/uclean.h
    /usr/local/include/unicode/ucnv.h
    /usr/local/include/unicode/ucnv_cb.h
    /usr/local/include/unicode/ucnv_err.h
    /usr/local/include/unicode/ucnvsel.h
    /usr/local/include/unicode/uconfig.h
    /usr/local/include/unicode/udata.h
    /usr/local/include/unicode/udeprctd.h
    /usr/local/include/unicode/udraft.h
    /usr/local/include/unicode/uenum.h
    /usr/local/include/unicode/uidna.h
    /usr/local/include/unicode/uintrnal.h
    /usr/local/include/unicode/uiter.h
    /usr/local/include/unicode/uloc.h
    /usr/local/include/unicode/umachine.h
    /usr/local/include/unicode/umisc.h
    /usr/local/include/unicode/unifilt.h
    /usr/local/include/unicode/unifunct.h
    /usr/local/include/unicode/unimatch.h
    /usr/local/include/unicode/uniset.h
    /usr/local/include/unicode/unistr.h
    /usr/local/include/unicode/unorm.h
    /usr/local/include/unicode/unorm2.h
    /usr/local/include/unicode/uobject.h
    /usr/local/include/unicode/uobslete.h
    /usr/local/include/unicode/urename.h
    /usr/local/include/unicode/urep.h
    /usr/local/include/unicode/ures.h
    /usr/local/include/unicode/uscript.h
    /usr/local/include/unicode/uset.h
    /usr/local/include/unicode/usetiter.h
    /usr/local/include/unicode/ushape.h
    /usr/local/include/unicode/usprep.h
    /usr/local/include/unicode/ustring.h
    /usr/local/include/unicode/ustringtrie.h
    /usr/local/include/unicode/usystem.h
    /usr/local/include/unicode/utext.h
    /usr/local/include/unicode/utf.h
    /usr/local/include/unicode/utf16.h
    /usr/local/include/unicode/utf32.h
    /usr/local/include/unicode/utf8.h
    /usr/local/include/unicode/utf_old.h
    /usr/local/include/unicode/utrace.h
    /usr/local/include/unicode/utypes.h
    /usr/local/include/unicode/uvernum.h
    /usr/local/include/unicode/uversion.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libMagick++-6.Q16.la
    /usr/local/lib/libMagickCore-6.Q16.la
    /usr/local/lib/libMagickWand-6.Q16.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/ImageMagick++-6.Q16.pc
    /usr/local/lib/pkgconfig/ImageMagick++.pc
    /usr/local/lib/pkgconfig/ImageMagick-6.Q16.pc
    /usr/local/lib/pkgconfig/ImageMagick.pc
    /usr/local/lib/pkgconfig/Magick++-6.Q16.pc
    /usr/local/lib/pkgconfig/Magick++.pc
    /usr/local/lib/pkgconfig/MagickCore-6.Q16.pc
    /usr/local/lib/pkgconfig/MagickCore.pc
    /usr/local/lib/pkgconfig/MagickWand-6.Q16.pc
    /usr/local/lib/pkgconfig/MagickWand.pc
    /usr/local/lib/pkgconfig/Wand-6.Q16.pc
    /usr/local/lib/pkgconfig/Wand.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/liblua.a
    /usr/local/lib/libMagick++-6.Q16.a
    /usr/local/lib/libMagickCore-6.Q16.a
    /usr/local/lib/libMagickWand-6.Q16.a

Warning: Your Xcode (7.3) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.

Warning: Broken symlinks were found. Remove them with `brew prune`:
    /usr/local/lib/libbeidapplayer.4.0.dylib
    /usr/local/lib/libbeidapplayer.4.dylib
    /usr/local/lib/libbeidapplayer.dylib
    /usr/local/lib/libbeidlib.4.0.dylib
    /usr/local/lib/libbeidlib.4.dylib
    /usr/local/lib/libbeidlib.dylib
    /usr/local/lib/libbeidlibJava_Wrapper.4.0.dylib
    /usr/local/lib/libbeidlibJava_Wrapper.4.dylib
    /usr/local/lib/libbeidlibJava_Wrapper.dylib`

**Comment by UniqMartin** [comment]
@Sajaki Good to hear back from you and that things worked out. 😺
