### ISSUE TITLE
Audit: Handle homepages with cloudflare and other security related curl errors

### ISSUE THREAD

**Issue by bevanjkay** [Homebrew/brew#11706]
### Provide a detailed description of the proposed feature

Add a flag to `brew audit` to disable the homepage check (would need to be manually verified).
The flag would be able to be applied to cask CI checks with a label.

### What is the motivation for the feature?

There is an increasing amount of casks that are failing CI due to curl being unable to fetch the homepage.
In some cases, this can be mitigated by passing user_agent and other headers to the request, but does not help in others.

The flag would allow other tests to pass CI, and not require using syntax only checks, or overriding failures to merge PRs.

### How will the feature be relevant to at least 90% of Homebrew users?

Would allow more Cask audits to pass without manual overrides.

### What alternatives to the feature have been considered?

Another option could be to allow setting user_agent and other headers on homepage URLs (livecheck URLs as well) however this may not work in all circumstances.

**Comment by bevanjkay** [comment]
I am working on a draft PR that would add a `--[no-]-homepage` flag to the brew audit command.

**Comment by MikeMcQuaid** [comment]
I'd like to see this solved by https://github.com/Homebrew/brew/issues/11705 instead. I don't think we want to make manual verification a part of our workflow.
