### ISSUE TITLE
Use Homebrew `curl` for fetching and audit when specified in the formula

### ISSUE THREAD

**Issue by nandahkrishna** [Homebrew/brew#11705]
### Provide a detailed description of the proposed feature

When explicitly specified in a formula, using `depends_on "curl" => :fetch` or similar, Homebrew `curl` must be used instead of macOS `curl`. This will ensure that Homebrew `curl` is used when the formula's source is fetched and when auditing the formula URLs. This is not done by default to prevent unwanted linkage to Homebrew's `curl`. See https://github.com/Homebrew/brew/pull/11536 for some discussion.

### What is the motivation for the feature?

macOS `curl` does not have TLS v1.3 support, so many servers which support only TLS v1.3 do not work with it. For example, sources for `Xiph.org` formulae are hosted on one such server, and thus fail the audit with `Stable URL is not reachable`. This prevents bottling for a specific OS using `dispatch-build-bottle`. Here is a list of formulae that would benefit from this feature (there may be others as well):

1. cdparanoia
2. ezstream
3. flac
4. icecast
5. libfishsound
6. libshout
7. libvorbis
8. libxspf
9. oggz
10. speex
11. theora
12. vorbis-tools

### How will the feature be relevant to at least 90% of Homebrew users?

It may not be relevant to 90% of Homebrew users since we do not support building from source, but it would definitely help those on older, unsupported OSes which do not have bottles. It is also relevant to Homebrew maintainers and contributors working with affected formulae, and would help bottle them on other/newer OSes.

### What alternatives to the feature have been considered?

Using Homebrew `curl` by default, but this is unnecessary (a very small portion of formulae require this feature so it isn't necessary to make this the default and encounter issues we do not want to, e.g. linkage with Homebrew-provided `libcurl`).

**Comment by iMichka** [comment]
Another strategy would be to move the `brew audit <formula>` and `brew livecheck` steps out of the main test-bot call, and run these in the tap_syntax part of the workflow. (there should be a separate test bot command for that, really). And change from ubuntu 16.04 to 20.04 here https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/tests.yml#L21-L26, so that we use a newer version of curl. I tested the audit call with the curl provided by ubuntu 20.04 and it worked.

I think this is probably easier than having to manually define which curl should be used for specific formulae or to introduce a new DSL.

**Comment by carlocab** [comment]
I think this also requires refactoring our audits so to run the ones that don't need a formula installed can be run separately from the ones that do.

It also doesn't solve the problem of fetching the tarball so we can actually build something, I think.

**Comment by MikeMcQuaid** [comment]
> Another strategy would be to move the `brew audit <formula>` and `brew livecheck` steps out of the main test-bot call, and run these in the tap_syntax part of the workflow. (there should be a separate test bot command for that, really). And change from ubuntu 16.04 to 20.04 here https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/tests.yml#L21-L26, so that we use a newer version of curl. I tested the audit call with the curl provided by ubuntu 20.04 and it worked.

This doesn't solve the problem entirely but I do like the idea of moving some more logic like `brew audit` that's not platform-dependent onto Linux.

**Comment by iMichka** [comment]
Test PR in homebrew-core: https://github.com/Homebrew/homebrew-core/pull/83470

**Comment by iMichka** [comment]
This has been implemented and is now being used. You can add `, using: :homebrew_curl` to the `url` stanza in a formula and it will be used for downloads and audits. Test-bot will install brewed curl for you on CI.
