### ISSUE TITLE
Install brew with Error: no implicit conversion of false to String 

### ISSUE THREAD

**Issue by QinanWu** [Homebrew/brew#11707]
### `brew config` output

```shell
NO
```

### `brew doctor` output

```shell
NO
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

In stall brew by this way:
root~#: /bin/bash -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"

### What happened (include all command output)?

Please report this issue

### What did you expect to happen?

No error, install succed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
/bin/bash -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"
```

**Comment by bayandin** [comment]
You try to install not a Homebrew script (`https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh`), you should report this issue there.

**Comment by QinanWu** [comment]
http://img.swtest888.com/mweb/16261743220619.jpg

**Comment by nandahkrishna** [comment]
As mentioned by @bayandin, the install script you are using is not the official Homebrew install script. We do not support this unofficial method. You should use:
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
Your installation is possibly failing using the unofficial script because homebrew-serviohces doesn't work on Linux yet.

**Comment by QinanWu** [comment]
use the script and got this:
CentOS 7.4 64 
fatal: unable to access ' https ://github.com/Homebrew/brew/' : Encountered end of file 
Failed during: git fetch --force origin

**Comment by gromgit** [comment]
You seem to be having issues reaching GitHub. Since you're in China, you might want to talk to other users around you who're using Homebrew to see what adjustments they made to get through.
