### ISSUE TITLE
Error while importing sqlite: ImportError: No module named _sqlite3

### ISSUE THREAD

**Issue by lipis** [Homebrew/brew#1171]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

I basically tried everything. Whatever I found online regarding this issue and people were mentioning that it worked I did it.. but it doesn't work for me. For example `brew rm python python3 sqlite --force` and other things that I could remove I did it.. but no luck..

I'm recently updated all of my Homebrew stuff when I upgraded to macOS 10.12.. and here is the current situation.. is there anything I can try before throwing away this Macbook Pro outside of my window?

```bash
$ brew install python sqlite
Warning: python-2.7.12 already installed
Warning: sqlite-3.14.2 already installed

#-----------------------------------------------------------------------------

$ which python
/usr/local/bin/python

#-----------------------------------------------------------------------------

$ find /usr/local -name sqlite
/usr/local/Cellar/sqlite
/usr/local/opt/sqlite

#-----------------------------------------------------------------------------

$ python
Python 2.7.12 (default, Sep 27 2016, 20:06:01)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import sqlite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named sqlite

>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
```

**Comment by zmwangx** [comment]
Did you install python from source? Or did you pour our bottle? Please post of the output of the following commands:

```
brew info python
/bin/ls -l /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_sqlite3.so
```

**Comment by lipis** [comment]
Used your bottles. Here is the [gist](https://gist.github.com/lipis/6aba25182ca6545e1b86400f5d568f4f) to avoid crappy comments.

**Comment by lipis** [comment]
@zmwangx I'm guessing it's not what you wanted to see.. :(

**Comment by zmwangx** [comment]
I just came back to my computer.

> Used your bottles.

Info disagrees.

```
/usr/local/Cellar/python/2.7.12 (6,288 files, 85.3M) *
  Built from source on 2016-09-27 at 20:06:59
```

Judging from your desperateness, you should really consider pouring our bottle instead of trying to debug your source build.

But if you really want to debug your source build, show us your

```
brew config
```

and the conversation might be able to continue.

**Comment by lipis** [comment]
I don't care about debugging.. I just want to make it work.. I thought by running `brew install python` would use your bottle :) Am I missing something?! How do I override.. solve my problem?

**Comment by lipis** [comment]
```bash
HOMEBREW_VERSION: 1.0.5-25-g7e93340
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 7e93340073106f9f5a4bef057823210fb432c064
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 81697c641696ca9249ff9c6b1a24095ccb0c04d8
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60
macOS: 10.12-x86_64
Xcode: 8.0
CLT: N/A
X11: 2.7.9 => /opt/X11
```

**Comment by zmwangx** [comment]
That's weird. Could you please try

```
sudo xcode-select --install
```

to install CLT and try again (`brew update --force; brew uninstall --force python; brew install python`)?

If that doesn't work I'll tell you a secret way.

**Comment by lipis** [comment]
The beauty of Python! On it..

**Comment by lipis** [comment]
Magic! I really can't believe that it worked :) Thank you very very nice..! Spent the whole evening on that.. :)

![magic](https://cloud.githubusercontent.com/assets/125676/18891874/83886cfe-8507-11e6-8851-05fc4e8fe259.gif)

**Comment by lipis** [comment]
I still want to know the secret way though.. in case of trouble in the future I can always come back here..

**Comment by zmwangx** [comment]
Glad to hear.

**Comment by zmwangx** [comment]
The secret way is

```sh
# Depending on current version of formula and OS
curl -LO https://homebrew.bintray.com/bottles/python-2.7.12.sierra.bottle.tar.gz
brew install ./python-2.7.12.sierra.bottle.tar.gz
```

But `brew install python` should really pull the bottle. Guess it's because you're missing CLT, but not sure, I'm not familiar with no-CLT configurations.

**Comment by lipis** [comment]
I'm sure I had them installed on that machine.. as I think Homebrew requires that at one point.. but after the Sierra upgrade things went sideways (as always)... thanks again! Cheers.. 🍺 🍻 🍺

**Comment by zmwangx** [comment]
```
$ pkgutil --lsbom com.apple.pkg.DevSDK_OSX1012 | cut -d / -f 2 | uniq
.
System
usr
```

As you can see, CLT package installs its contents into `/System` and `/usr`, both of which are overwritten by a major OS upgrade.

**Comment by lipis** [comment]
<img width="545" alt="screen shot 2016-09-28 at 22 38 27" src="https://cloud.githubusercontent.com/assets/125676/18931432/7297c550-85cc-11e6-90fd-619466833bf9.png">

<img width="645" alt="screen shot 2016-09-28 at 22 38 35" src="https://cloud.githubusercontent.com/assets/125676/18931435/7447cb70-85cc-11e6-9612-7f0977dbf4a3.png">

I might need to throw away this computer (or maybe just have clean install) after all.. :(

Not sure if that's related but it looks like something is wrong again.. that happens every time that I'm trying to [deploy](https://cloud.google.com/sdk/gcloud/reference/app/deploy) the app on App Engine.. In case that matters.. and yes I deleted every single trace of [google-cloud-sdk](https://cloud.google.com/sdk/docs/quickstart-mac-os-x) and installed it again.. no luck :)

Maybe @zmwangx you have some other *black magic* that could help me..?

**Comment by zmwangx** [comment]
Unfortunately no, I'm not running into such issues on Sierra, and I doubt it's our problem (most of my stuff run on Python 3 though, and almost always with a non system wide Python). Maybe you could give pyenv a try?

**Comment by lipis** [comment]
Something is odd with my machine :( thanks man.. I installed `pyenv` used all the versions from `2.7.8 - 2.7.12` and I downgraded the App Engine sdk as well.. no luck.. I'm ready!

![giphy](https://cloud.githubusercontent.com/assets/125676/18933621/f860746c-85d5-11e6-9ff0-4b1b99e1f627.gif)

**Comment by zmwangx** [comment]
Huh sorry to hear that but no idea... I myself did run into "Python quit unexpectedly" issue intermittently since 3.5 I believe (which is roughly the same time as 2.7.11), but it was pretty rare and never reproducible.

**Comment by zmwangx** [comment]
Now you may try a binary installer from python.org directly but I doubt it would help much...

**Comment by zmwangx** [comment]
Or you can try installing just Python in a clean VM.

**Comment by lipis** [comment]
It's just sucks.. but that's life :) When you play dangerous games.. 

Basically at the moment I'm backing up, committing my 3423 projects into GitHub making sure that 652TB of crap in Dropbox are synced and I'll be ready to clean the shit out of it... I wanted to do that for quite some time now.. so it looks like that day/night just arrived :)

**Comment by zmwangx** [comment]
👍 Good luck with your clean install.

**Comment by lipis** [comment]
By the way..! Homebrew is on #43.. http://githubstats.lip.is

**Comment by reitermarkus** [comment]
And [legacy-homebrew](https://github.com/Homebrew/legacy-homebrew) is 28. 😂

**Comment by zmwangx** [comment]
Opened https://github.com/Homebrew/homebrew-core/issues/5347 to see if we can prevent more users from wasting time on Python due to missing CLT.

**Comment by lipis** [comment]
Maybe also change the first CLT to: Command Line Tools (CLT)

@reitermarkus Let's see when the new one will overpass it..

**Comment by lipis** [comment]
@zmwangx and now everything is nice and clean! :) Can I ask your opinion about `brew cask`.. I used to [have it like a million years ago](https://github.com/lipis/dotfiles/blob/master/cask.sh).. is it OK to use it?

**Comment by lipis** [comment]
and I'm also ready to run this beauty: [`brew.sh`](https://github.com/lipis/dotfiles/blob/master/brew.sh) any other magic to add or remove?

(you can also totally ignore my questions..)

**Comment by zmwangx** [comment]
> Can I ask your opinion about brew cask

My **personal** opinion of cask is it's pretty awful for any sort of management, but it's useful for one off installations, and that's what I use it for. Any cask lovers out there: I do not intend to spark an argument.

> brew.sh

It's fine, but 

```
ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum
```

is pointless since the non-prefixed version is already in `gnubin`. Also, you should hard code
`$(brew --prefix coreutils)/libexec/gnubin` (e.g. `/usr/local/opt/coreutils/libexec/gnubin`) to speed up shell init.

**Comment by lipis** [comment]
Awesome man! Much appreciated..

**Comment by lipis** [comment]
So the good news is that my machine is very clean and nice..!!

the bad news is that I still have the error: https://gist.github.com/lipis/946c17457cdd8acf45d6270091ebc63a

```
Segmentation fault: 11
```

If there are any clues above.. fine.. but in the meantime I'll try to work on my older machine.. and maybe downgrade (somehow) to El Capitan :(

(Maybe also posting this somewhere else would make sense.. I can't be the only one..)

![wzbcycv](https://cloud.githubusercontent.com/assets/125676/19017413/d81579ea-8838-11e6-8d61-f47d440d7bea.png)

**Comment by KeynesYouDigIt** [comment]
not sure if this contributes here, but I am having the same issue, except only on the deployed app, not the local python install (which runs perfectly). is App Engine using brew? does knowing this help your issue?

**Comment by zmwangx** [comment]
> is App Engine using brew?

No.

> does knowing this help your issue?

Python compiled without SQLite is common enough. It happens whenever `sqlite.h` is not found in [this short list of paths](https://github.com/python/cpython/blob/59fa72e34da71fb24f52251c1cc88ed3c3b14797/setup.py#L1132-L1138), regardless of `CPATH`, `CFLAGS`, etc. We have this patched in homebrew/core, and knowing another unrelated case of failure doesn't really help us. But thanks anyway.
