### ISSUE TITLE
Print git output for `brew upgrade -v --fetch--HEAD`

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#11723]
### Provide a detailed description of the proposed feature

Now `brew upgrade -v --fetch--HEAD` doesn't print any info for git operations, so it looks like stuck after a lot of lines like:

```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/<formula_name>.rb
```

### What is the motivation for the feature?

Verbose brew output should include git output.

### How will the feature be relevant to at least 90% of Homebrew users?

I think that 90% of those who installed at least one HEAD formula will find this useful.

### What alternatives to the feature have been considered?

Keep it as is.

**Comment by MikeMcQuaid** [comment]
> Now `brew upgrade -v --fetch--HEAD` doesn't print any info for git operations
 
Since when? Can you figure out the commit or Homebrew release when this happens? Does `--debug` include this output?

> ### What alternatives to the feature have been considered?
> N/A

Please fill out this section.

**Comment by yurikoles** [comment]
I had bisected it to 490e503b1b6977cfd9d7580058e12a2d4d3c964a

**Comment by MikeMcQuaid** [comment]
@yurikoles Thanks. What are the specific `git` calls you are expecting to see?

**Comment by yurikoles** [comment]
I'm unsure, previous behavior was fine. If it hard to return, at least some progress indication would be nice, because now the brew looks stuck.

**Comment by yurikoles** [comment]
The most frustrating case is that after `brew cleanup -s` HEAD formulas are being re-cloned, which may take much more time and brew seems like just stuck.

**Comment by MikeMcQuaid** [comment]
@yurikoles I strongly suggest not using `-s`.
