### ISSUE TITLE
Odd return code for `brew list --versions <package>`

### ISSUE THREAD

**Issue by TheKevJames** [Homebrew/brew#1172]
Originally discovered by @jordigg [here](https://github.com/TheKevJames/puppet-homebrew/pull/52#issuecomment-249251113).

## Issue
Running `brew list --versions PACKAGE_NAME` with a package that is not installed returns 0, whereas `brew list PACKAGE_NAME` returns 1.

```
$ brew list git; echo $?
/usr/local/Cellar/git/2.10.0/bin/git
# output snipped
0
$ brew list --versions git; echo $?
git 2.10.0 2.9.3
0
$ brew list gitasdfasdfasdf; echo $?
Error: No such keg: /usr/local/Cellar/gitasdfasdfasdf
1
$ brew list --versions gitasdfasdfasdf; echo $?
0
```

## Suggested Fix
These return values should probably be the same, whether that is 0 or 1. Personally, I think error code 1 is correct and the the return value of `brew list --versions` needs to be changed.

**Comment by vladshablinsky** [comment]
We can change `cmd/list.rb` so `brew list --versions <package1, package2, ..., packageN>` will exit with `1` code if there is no keg for some `<package_i>`, for the others packages it'll print their versions. So, we print everything we can just like before the change and what we change is exit code if there are kegs that could not be found in the Cellar. This is the **first** option:

```diff
diff --git a/Library/Homebrew/cmd/list.rb b/Library/Homebrew/cmd/list.rb
index d2eebb5..43a0382 100644
--- a/Library/Homebrew/cmd/list.rb
+++ b/Library/Homebrew/cmd/list.rb
@@ -106,7 +106,11 @@ module Homebrew
     names = if ARGV.named.empty?
       Formula.racks
     else
-      ARGV.named.map { |n| HOMEBREW_CELLAR+n }.select(&:exist?)
+      racks = ARGV.named.map { |n| HOMEBREW_CELLAR+n }
+      racks.select do |rack|
+        Homebrew.failed = true unless rack.exist?
+        rack.exist?
+      end
     end
     if ARGV.include? "--pinned"
       pinned_versions = {}
```

The **second** option could be raising an error like we do for `list` command without `--versions` flag. E.g.

```bash
➜ vlad:Homebrew$ brew list --verbose installed_package_1 no_such_package installed_package_2
Error: No such keg: /usr/local/Cellar/no_such_package
``` 
or
```bash
➜ vlad:Homebrew$ brew list --verbose installed_package_1 no_such_package installed_package_2
installed_package_1 1.0 1.1 2.0
Error: No such keg: /usr/local/Cellar/no_such_package
```

I like the first option.

**Comment by MikeMcQuaid** [comment]
I'm happy with either @vladshablinsky.
