### ISSUE TITLE
Add static build for jsoncpp

### ISSUE THREAD

**Issue by zcream** [Homebrew/brew#11732]
### Provide a detailed description of the proposed feature

jsoncpp is only installed as a shared dylib. Could a static build be added a well? 

### What is the motivation for the feature?

From https://github.com/Homebrew/homebrew-core/issues/16441 - If someone requests them, or it's trivial to build both, we usually do.

### How will the feature be relevant to at least 90% of Homebrew users?

Most of the brew formula will build static libs. And for such a small library, a shared lib does not make sense.

### What alternatives to the feature have been considered?

brew edit jsoncpp

I added 
```
  def install
  args = std_cmake_args
  args << "-DBUILD_SHARED_LIBS=OFF"
```
Then
`brew reinstall jsoncpp`

But still no static libs were installed.

**Comment by carlocab** [comment]
We'll review a pull request that installs the static libraries in addition to the shared ones.

For future reference, this issue tracker is for issues regarding the `brew` command-line tool. Formula related issues should be addressed at https://github.com/Homebrew/homebrew-core. Note that we don't usually take feature requests there -- those should be made in the form of pull requests. Thanks!
