### ISSUE TITLE
Brew doctor should not nag about missing build-time dependencies

### ISSUE THREAD

**Issue by Rotonen** [Homebrew/brew#1173]
Reproduction steps:

1) install libevent
2) run brew doctor
3) brew doctor returns nonzero

During buildtime libevent requires doxygen, but libevent is shipped as a bottle. This causes doxygen appear in brew missing and brew doctor to return nonzero.

Building libevent would pull in the build-time dependency in any case, so this is a corner case which should not get flagged.

**Comment by zmwangx** [comment]
`doxygen` is a `:recommended` dependency in addition to a `:build` dependency. The former makes it marked as missing, not the latter.

Please shout at me if my diagnostics was not clear or if you find a bare `:build` dependency marked as missing.
