### ISSUE TITLE
perforce binary SHA256 mismatch

### ISSUE THREAD

**Issue by sonicfly** [Homebrew/brew#11738]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d37d09709b6fbd5b89b468eb0b4438ffa0fb81c
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c13db0d1a43e4f105b56e2d174bf58569a07fe34
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install p4

### What happened (include all command output)?

==> Downloading https://cdist2.perforce.com/perforce/r21.1/bin.macosx1015x86_64/p4
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 85c0d2f92b59564ea36a56a8f07b87aecf0b2806637e8b7d69d6edd0d79d6c40
  Actual: 6ce7ba5241a35979a439bf344b46d3f5d5b0ae8d0916c88a4fb4a092be0b4dcb
    File: /Users/chzhou/Library/Caches/Homebrew/downloads/58e4251de3b76e06a4b812828344ae5374219df8b6a5803b054e12338f34f562--bin.macosx1015x86_64
To retry an incomplete download, remove the file above.

### What did you expect to happen?

Expect SHA256 match and install succeeds

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install p4
```

**Comment by carlocab** [comment]
This issue tracker is for the `brew` command line tool. Cask-related issues should be addressed at https://github.com/Homebrew/homebrew-cask.

Please see the documentation on checksum mismatches before opening an issue: https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
