### ISSUE TITLE
Homebrew package non-interractive installation

### ISSUE THREAD

**Issue by sahaqaa** [Homebrew/brew#11757]
### Provide a detailed description of the proposed feature

Hello,
Im trying to install Homebrew via Ansible on remote MacOS machines (10 MacBook's), in non-interractive , i.e. in unattended mode via Ansible.
I tried few different ways, Googled for a few hours, tried to find workaround but failed to do so.

Installation process actually expect user input, and not proceeding to  next stages.

When i install it manually on node, i.e. i connect via SSH and directly running commands in Terminal:

slave-app-mac11:~ jenkins$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password).
==> You are using macOS 10.11.
==> We (and Apple) do not provide support for this old version.
This installation may not succeed.
After installation, you will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew\'s GitHub,
Twitter or IRC. You are responsible for resolving any issues you experience
while you are running this old version.

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following existing directories will be made writable by user only:
/usr/local/share/zsh
/usr/local/share/zsh/site-functions

Press RETURN to continue or any other key to abort

Is there any way how to install Homebrew on remote node (in non-interractive , i.e. in unattended mode)?

### What is the motivation for the feature?

It will help to automate deyployment of Homebrew via automation tools such as Ansible and others

### How will the feature be relevant to at least 90% of Homebrew users?

Dont know about 90% of Homebrew users. But it will be relevant for companies, which trying to automate its processes

### What alternatives to the feature have been considered?

Manual installation, i.e. pain in the butt method on multiple MacOS deployments

**Comment by gromgit** [comment]
Have you looked at Jeff Geerling's work? https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/README.md

**Comment by MikeMcQuaid** [comment]
> Is there any way how to install Homebrew on remote node (in non-interractive , i.e. in unattended mode)?

If you run that script outside of a TTY it'll run in non-interactive mode.
