### ISSUE TITLE
Having version independent bottles

### ISSUE THREAD

**Issue by EdSchouten** [Homebrew/brew#1176]
Hi there,

[CloudABI Ports](https://github.com/NuxiNL/cloudabi-ports) provides a set of packages for software that is cross compiled for [CloudABI](https://nuxi.nl/). Right now we export our packages to formulae and bottles for macOS, so that they can easily be managed using `brew`. In our case, these bottles only need to be built once. As these packages only contain cross compiled software, the bottles would be identical regardless of the version of macOS used. In fact, our build tools don't even require using macOS to build them. We can also use Linux, FreeBSD, etc. to generate these.

One of the issues we're having right now is that Brew requires bottles to contain the name of the macOS codename in their filename. The same holds for the formulae: they also have to list the bottles multiple times. Things would be a lot easier for us if we could do something like this:

```
  bottle do
    ...
    sha256 "ef468b7b91d053870d13183d2743fe0fa96473c76f1cf5857d7b9930578d9ac9" => :noarch
  end
```

This would result in `${root_url}/${name}-${version}.noarch.bottle.tar.gz` being fetched instead. This would allow us to get rid of our explicit list of macOS versions that we use to symlink bottles server-side, while also simplifying our formulae.

**Comment by MikeMcQuaid** [comment]
Do the bottles rely on a particular `Cellar` location?

**Comment by EdSchouten** [comment]
Thanks for the quick response, Mike!

Right now I guess they don't. All formulae are named `${gnu_cross_target}-${name}`, e.g. `aarch64-unknown-cloudabi-boost` for Boost for ARM64. That way you can easily install cross build infrastructure for any architecture of choice. They all install their files under `Cellar/${gnu_cross_target}-${name}/${version}/share/${gnu_cross_target}`, so that they get linked under `/usr/local/share/${gnu_cross_target}`.

**Comment by MikeMcQuaid** [comment]
To be more explicit: does `brew bottle` generate a `cellar :any` bottle? If not, they are bound to a particular path. If it does generate one a better fit may be avoiding bottles altogether and just having a formula that installs your binary.

**Comment by EdSchouten** [comment]
Ah, wait. I understand what you're saying. Yes. The bottles are bound to a particular path right now, as they hardcode paths starting with `/usr/local`. That said, there are changes I can make on my side to prevent this, which at the same time means that I don't need to use bottles, as the formula is directly installable.

Let's close this issue, as there is nothing on Homebrew's side that needs changes.
