### ISSUE TITLE
Error: autoconf: Calling `cellar` in a bottle block is disabled!macOS big Sur 11.5

### ISSUE THREAD

**Issue by hkun0120** [Homebrew/brew#11764]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.3-67-g4cf2820
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 4cf28209435e4f60b2987e11d117ab4fc388ecd6
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 528fae2312cfa8bc55ada124cd51be416edc03a2
Core tap last commit: 2 years, 4 months ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles/bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0.5 build 1205
Git: 2.10.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-x86_64
```

### `brew doctor` output

```shell
Error: git: Calling `sha256 "digest" => :tag` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb:9
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I willing to  install autoconfig ,and compile my openJDK

### What happened (include all command output)?

Error: autoconf: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb:9

### What did you expect to happen?

installed success

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install autoconf
```

**Comment by carlocab** [comment]
This is your problem:
```
Core tap last commit: 2 years, 4 months ago
```
Your core tap has not been updating in over two years.

Please run `brew update`. If that doesn't fix it, do `brew update-reset`, but please note:
```
❯ brew help update-reset
Usage: brew update-reset [repository ...]

Fetch and reset Homebrew and all tap repositories (or any specified
repository) using git(1) to their latest origin/HEAD.

Note: this will destroy all your uncommitted or committed changes.
```

`brew doctor` should also have helpful advice, but it's hard to give recommendations when you've omitted the output of `brew doctor` despite being asked to provide it.

Please be sure to provide all the requested information next time.

**Comment by geniusj204** [comment]
will make adjustment. to eliminate unnecessary background noise the function better serves the project as N/A
