### ISSUE TITLE
Support Steam on a Case-Sensitive File System on MacOS

### ISSUE THREAD

**Issue by davidpgil** [Homebrew/brew#11768]
### Provide a detailed description of the proposed feature

My MasOS system was installed with case-sensitivity turned on. When I install Steam via "brew install Steam" the installation is successful but upon executing the Steam app, I am met with the following warning and the app will not load.

<img width="262" alt="Screen Shot 2021-07-25 at 8 25 45 AM" src="https://user-images.githubusercontent.com/41744832/126898973-325f4a88-95ae-4cde-8ff0-b6858aa32671.png">

### What is the motivation for the feature?

Support Steam on case-sensitive MacOS systems.

### How will the feature be relevant to at least 90% of Homebrew users?

The will be able to use the most prominent gaming platform on a case-sensitive MacOS without needing to reinstall the whole computer.

### What alternatives to the feature have been considered?

None that I am aware of.

**Comment by carlocab** [comment]
We only ship what the Steam developers publish, so you'll need to take this up with them. This isn't a limitation enforced by Homebrew.
