### ISSUE TITLE
Python2 installs without sqlite3

### ISSUE THREAD

**Issue by Rotonen** [Homebrew/brew#1179]
Reproduction steps:
0) MacOS Sierra
1) `brew install python`
2) `python -c 'import sqlite3'`

```
ImportError: No module named _sqlite3
```

The SQLite is listed as a recommended dependency and is installed. There is no `--with-sqlite` and `--without-sqlite` is not used.

Running `brew reinstall python` did not help. Used to work out of the box on El Capitan.

**Comment by zmwangx** [comment]
Please install CLT

```
sudo xcode-select --install
```

and try again.

**Comment by Rotonen** [comment]
Thank you, I did indeed still have the command line tools from El Capitan.

User error.

Should `brew doctor` catch this?

**Comment by zmwangx** [comment]
I think this problem is specific to `python` and a few other formulae (see the `pour_bottle` block in `python.rb`) so IMO it may not be the best idea to warn about this in general.

We will consider how to better deal with this problem. Meanwhile, glad the problem is fixed.

**Comment by zmwangx** [comment]
#5347.
