### ISSUE TITLE
`brew test` CompilerSelectionError when using `fails_with` & build-only compiler dependency

### ISSUE THREAD

**Issue by cho-m** [Homebrew/brew#11795]
### `brew config` output

```shell
==> Running Setup#run!
==> brew install-bundler-gems
==> brew config
HOMEBREW_VERSION: 3.2.5-17-g689c1fd
ORIGIN: https://github.com/Homebrew/brew
HEAD: 689c1fdb6ec2637964a004727a4f407861809bbd
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bdbfc4fcbcdef82b3d06c8ecb85c2464c61512bb
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3650
HOMEBREW_COLOR: set
HOMEBREW_DEVELOPER: set
HOMEBREW_FAIL_LOG_LINES: 150
HOMEBREW_FORCE_HOMEBREW_ON_LINUX: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GIT_EMAIL: 1589480+BrewTestBot@users.noreply.github.com
HOMEBREW_GIT_NAME: BrewTestBot
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: set
HOMEBREW_NO_EMOJI: set
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.32.0 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 5.8.0-1039-azure x86_64 GNU/Linux
OS: Ubuntu 16.04.7 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
==> brew doctor
All steps passed!
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

~~Linux CI run on `envoy` https://github.com/Homebrew/homebrew-core/pull/82077 with diff to disable default GCC for build (`fails_with gcc: "5"`) and only enable working GCC in necessary section, i.e. build (`depends_on "gcc@9" => :build`).~~

**EDIT:** Issue is more for LLVM rather than GCC since GCC-dependency often carries newer runtime library dependency. Specific examples:
- `dotnet` https://github.com/Homebrew/homebrew-core/pull/81945 when trying to only enable `llvm` for build.
- `swift`
- `fibjs`

It would also be more accurate to test without extra brewed `gcc`/`llvm` dependency to make sure it truly isn't used by runtime.

### What happened (include all command output)?

`brew test` fails during set up due to compiler selection error. The error message complains about being unable to "build" the formula, even though it should be testing an already built/installed formula.

See https://github.com/Homebrew/homebrew-core/runs/3190458966
```
==> FAILED
Error: test failed
==> Testing envoy
Error: envoy: failed
An exception occurred within a child process:
  CompilerSelectionError: envoy cannot be built with any available compilers.
Install Clang or run `brew install gcc`.
```

### What did you expect to happen?

`brew test` should not fail on `CompilerSelectionError`. It should run in the test block as is, without requiring extra/unneeded compiler dependencies.

Some clarification/changes to `fails_with` is necessary so that there is a way to just disable GCC-5(Linux) or Apple Clang in build, but allow usage during test.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
https://github.com/Homebrew/homebrew-core/runs/3190458966
```

**Comment by MikeMcQuaid** [comment]
> Both of these don't need the compiler for runtime/test.

They don't need for runtime but they do for testing because that's how Homebrew works. This is something I'd review a PR for but I don't see as being a high priority given the workaround is so trivial on our side.

**Comment by carlocab** [comment]
Related issue, with no workarounds that I know of: https://github.com/Homebrew/homebrew-core/pull/86826#issuecomment-938263905
