### ISSUE TITLE
Unable to install/compile rust on macOS Sierra.

### ISSUE THREAD

**Issue by cooperaj** [Homebrew/brew#1180]
### Bug reports:

I'm currently unable to build rust. I'm on macOS Sierra and XCode8. I am running the latest version of everything having run the steps you mention in the issue template.

![Issue image](https://www.dropbox.com/s/o6eq5e7fe0oc2qo/Screenshot%202016-09-28%2016.08.21.png?dl=1)

The compiler appears to finish building and then runs some sort of rust command which hangs indefinitely. As you can see in the image the rustc process has been running for the last 5 hours.

**Comment by zmwangx** [comment]
Thanks for the report. This is a known issue, see Homebrew/homebrew-core#4841. We don't track issues of individual formula in the Homebrew/brew issue tracker, so I'm closing this.

**Comment by zmwangx** [comment]
By the way, this is really an upstream issue so if you could pressure on upstream it would be nice.

**Comment by DomT4** [comment]
New Rust release is being cut today which should fix Sierra: https://github.com/Homebrew/homebrew-core/pull/4960#issuecomment-250295814
