### ISSUE TITLE
As a user, I want the Dockerfile to run brew as a non-root user

### ISSUE THREAD

**Issue by sudoforge** [Homebrew/brew#11802]
### `brew config` output

```shell
➜ docker run --rm homebrew/brew:3.2.5 brew config
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

### `brew doctor` output

```shell
➜ docker run --rm homebrew/brew:3.2.5 brew doctor
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm currently working to add a new package, and am attempting to run `brew` via Docker to avoid installing it directly on my system -- because I do not install packages via shell scripts (only through my system package manager), and there is not a currently available package for my particular Linux distribution.

### What happened (include all command output)?

Running any command at all results in the following error:

```
➜ docker run --rm homebrew/brew:latest brew help
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

### What did you expect to happen?

I would expect the docker image to invoke the `brew` executable without issue.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ docker pull homebrew/brew:3.2.5
$ docker run --rm homebrew/brew brew <any subcommand>
```

**Note that the `3.2.5` tag is currently mapped to the same digest as `latest`.**

**Comment by sudoforge** [comment]
In working on a fix for this, It's actually apparent that the docker image doesn't even build successfully as-is:

```
Step 8/8 : RUN cd /home/linuxbrew/.linuxbrew   && mkdir -p bin etc include lib opt sbin share var/homebrew/linked Cellar   && ln -s ../Homebrew/bin/brew /home/linuxbrew/.linuxbrew/bin/   && git -C /home/linuxbrew/.linuxbrew/Homebrew remote set-url origin https://github.com/Homebrew/brew   && git -C /home/linuxbrew/.linuxbrew/Homebrew fetch origin   && HOMEBREW_NO_ANALYTICS=1 HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/core   && brew install-bundler-gems   && brew cleanup   && { git -C /home/linuxbrew/.linuxbrew/Homebrew config --unset gc.auto; true; }   && { git -C /home/linuxbrew/.linuxbrew/Homebrew config --unset homebrew.devcmdrun; true; }   && rm -rf ~/.cache   && chown -R linuxbrew: /home/linuxbrew/.linuxbrew   && chmod -R g+w,o-w /home/linuxbrew/.linuxbrew
 ---> Running in b8db808dc99f
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

**Comment by iMichka** [comment]
There is a  non root `linuxbrew` user in the image. Can you try `docker run --user linuxbrew` ?

**Comment by sudoforge** [comment]
That would work, but I'm actually working on a larger refactoring for the image given that it is currently pretty bloated and has various errors. I'm in the middle of my work day, but should have PR up later.

**Comment by iMichka** [comment]
The latest images are stored on `ghcr.io` (built from https://github.com/Homebrew/brew/blob/master/.github/workflows/docker.yml), did you try the `ghcr.io/homebrew/ubuntu16.04`, `ghcr.io/homebrew/ubuntu18.04` or `ghcr.io/homebrew/ubuntu20.04` images?

**Comment by sudoforge** [comment]
They all fail with the same error (unless specifying a non-root user). Requiring users to specify a user to run the command as is extremely inconvenient and given that `brew` requires running as a non-root user, I'd say that doing so is an anti-pattern.

**Comment by MikeMcQuaid** [comment]
Some good feedback here. Closing this in favour of the imminent PR. Thanks!
