### ISSUE TITLE
`brew bundle` not installing software

### ISSUE THREAD

**Issue by alephao** [Homebrew/brew#11817]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 265c8c36a4c0a74f478cba16417940b3b588736c
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f515f90012ad555f285840dab614cf21ad38749e
Core tap last commit: 27 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode-12.5.0.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5 => /Applications/Xcode-12.5.0.app/Contents/Developer
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to install a bunch of software using `brew bundle` using a `Brewfile`

### What happened (include all command output)?

I have a `Brewfile` with the following entry:

```
brew 'mint'
```

When I run `brew bundle` it shows `Installing mint`

After brew is done, the software is not installed. If I run `brew install mint` then it is installed correctly.

Note: It happened with other software as well like `swiftgen`

[![asciicast](https://asciinema.org/a/q5aeQY10P867Wa0SCgaqbHLOV.svg)](https://asciinema.org/a/q5aeQY10P867Wa0SCgaqbHLOV)

### What did you expect to happen?

I expected it to install the software (mint) and link it to PATH.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
echo "brew 'mint'" > Brewfile
brew bundle
mint
```

**Comment by robhanlon22** [comment]
Confirming the same behavior on my machine. My coworker @cyndilopez was also able to repro this.
