### ISSUE TITLE
Brew should give information about installed package architecture

### ISSUE THREAD

**Issue by berkus** [Homebrew/brew#11816]
### Provide a detailed description of the proposed feature

`brew list --arch` should give information about installed architecture(s) of the package/bottle.

### What is the motivation for the feature?

On macOS I could install an x86_64 package and an arm64 package, but brew does not give any information about which architecture is installed.

### How will the feature be relevant to at least 90% of Homebrew users?

They will see if any packages need to be reinstalled in light of added arch support.

### What alternatives to the feature have been considered?

Try to parse `brew list` into list of packages, then parse `brew list <package>` for each package to get list of files, try to run `file` on each found file and grep architecture from the file output. 

`brew list --json` does not give architecture information about installed package either.

**Comment by Rylan12** [comment]
`brew info --json` shows available bottles. Does that give you the information you need?

You can check `brew info --json` for available bottles like this:

```sh
brew info --json FORMULA | jq '.[].bottle.stable.files' | jq -r 'keys[]'
```

You can also use `brew info --json --installed` to list all installed formulae.

**Comment by berkus** [comment]
Nope, i want information about _installed_ bottle, not available ones.

**Comment by carlocab** [comment]
If it's a formula installed from Homebrew/core on macOS, then:

1. If you're using a `/usr/local` installation of Homebrew, then any installed formula is built for x86_64.
2. If you're using any other prefix, then any installed formula is built for arm64.

If there are exceptions to the above for Homebrew/core formula, then I think that's a bug. In light of this, I'm not sure there's a lot of value added from adding an `--arch` flag for `brew list`.

**Comment by MikeMcQuaid** [comment]
> * If you're using a `/usr/local` installation of Homebrew, then any installed formula is built for x86_64.
> * If you're using any other prefix, then any installed formula is built for arm64.

Yup, this.



> If there are exceptions to the above for Homebrew/core formula, then I think that's a bug. In light of this, I'm not sure there's a lot of value added from adding an `--arch` flag for `brew list`.

Agreed, sorry!

**Comment by berkus** [comment]
Ok.
