### ISSUE TITLE
Brew Cask installation default for Apple Silicon (M1) Macs

### ISSUE THREAD

**Issue by D3AS8A** [Homebrew/brew#11829]
### Provide a detailed description of the proposed feature

Somewhat related to the [general issue](https://github.com/Homebrew/brew/issues/10152) about Apple Silicon support, but I'm specifically referring to `cask` installs.

On a new machine, I usually just run install for a few hundred casks. However, I noticed that these seem to default to Intel applications (for example, `brew install --cask firefox` installs 64 bit Intel Firefox, which runs okay, but through Rosetta).

### What is the motivation for the feature?

It would be great if homebrew automatically detected the optimal architecture for casks (and for cask sources to have these available, of course)

### How will the feature be relevant to at least 90% of Homebrew users?

As Apple transitions to Apple Silicon, more users will offboard from Intel machines and onboard to Apple Silicon.

### What alternatives to the feature have been considered?

I used the 64-bit Intel versions of apps, which automatically work through Rosetta emulation. But this is not ideal.

I had to uninstall some casks via homebrew, and re-install them by manually downloading from the software vendors' websites.

Afaik, there is no way to select the architecture for a cask? Searching just shows different packages or casks.
```zsh
~ % brew search firefox
==> Casks
firefox ✔                           firefox-beta                        firefox-developer-edition           firefox-esr                         firefox-nightly                     multifirefox
```

**Comment by EricFromCanada** [comment]
Firefox is distributed as a universal binary, so each build contains binaries for both architectures:
```
% file /Applications/Firefox.app/Contents/MacOS/firefox
/Applications/Firefox.app/Contents/MacOS/firefox: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Applications/Firefox.app/Contents/MacOS/firefox (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Applications/Firefox.app/Contents/MacOS/firefox (for architecture arm64):	Mach-O 64-bit executable arm64
```
Casks that have separate downloads for each architecture should detect and install only the one for the current architecture, as is done for e.g. [`zoom`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/zoom.rb) or [`google-chrome`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/google-chrome.rb). However, it's not possible to determine whether a cask provides an ARM-native binary or not.
