### ISSUE TITLE
Issue while installing brew

### ISSUE THREAD

**Issue by ravindrasinghmutualmobile** [Homebrew/brew#11827]
### `brew config` output

```shell
HEAD is now at 1add49c35 Merge pull request #11823 from Homebrew/dependabot/bundler/Library/Homebrew/tapioca-0.4.24
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### `brew doctor` output

```shell
HEAD is now at 1add49c35 Merge pull request #11823 from Homebrew/dependabot/bundler/Library/Homebrew/tapioca-0.4.24
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install brew. with the command /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

### What happened (include all command output)?

HEAD is now at 1add49c35 Merge pull request #11823 from Homebrew/dependabot/bundler/Library/Homebrew/tapioca-0.4.24
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

### What did you expect to happen?

should install brew with /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
just run the installation command /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by MikeMcQuaid** [comment]
This is an issue with your GitHub connection.

**Comment by gromgit** [comment]
See https://github.com/Homebrew/discussions/discussions/666 for various possibilities, and how to fix them.
