### ISSUE TITLE
Install completions for taps that install commands

### ISSUE THREAD

**Issue by joshka** [Homebrew/brew#1184]
When installing a tap (e.g. Homebrew/homebrew-services), install completions at the same time in the same fashion as formula already does.

**Comment by MikeMcQuaid** [comment]
We don't really do feature requests here but I'm broadly 👍. Either open a https://github.com/homebrew/brew-evolution PR or just implement it here. You'll be able to do this similarly to https://github.com/Homebrew/brew/blob/de5deaea986a82daf5924791cfb9224a6a88b29a/Library/Homebrew/tap.rb#L250-L252

**Comment by apjanke** [comment]
Addressed by #1195.
