### ISSUE TITLE
Formula with single MacOS arm entry makes it unable to install other formulas of same tap

### ISSUE THREAD

**Issue by Junkern** [Homebrew/brew#11856]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 265c8c36a4c0a74f478cba16417940b3b588736c
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 44b35a418dfd78018c6fc841df30e9b295c3e688
Core tap last commit: 26 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.32.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-arm64
CLT: 12.5.0.22.9
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  tfenv
  pre-commit
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

A user was trying to install `awsu` from a maintained tap (https://github.com/kreuzwerker/homebrew-taps)

### What happened (include all command output)?

The user got the following error message 

```
$ brew tap kreuzwerker/taps -v
==> Tapping kreuzwerker/taps
git clone https://github.com/kreuzwerker/homebrew-taps /usr/local/Homebrew/Library/Taps/kreuzwerker/homebrew-taps --origin=origin --template=
Cloning into '/usr/local/Homebrew/Library/Taps/kreuzwerker/homebrew-taps'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 59 (delta 0), reused 0 (delta 0), pack-reused 56
Receiving objects: 100% (59/59), 12.06 KiB | 398.00 KiB/s, done.
Resolving deltas: 100% (24/24), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kreuzwerker/homebrew-taps/m1-terraform-provider-helper.rb
formulae require at least a URL
Error: Cannot tap kreuzwerker/taps: invalid syntax in tap!
```
(Issue: https://github.com/kreuzwerker/homebrew-taps/issues/7)

### What did you expect to happen?

A successful install of `awsu`.

The installation did not work, because the formula for `m1-terraform-provider-helper` did only contain an entry for macos arm. It was fixed by adding an additional entry for macos amd64.

The thing is: The tool  `m1-terraform-provider-helper` is only helpful for Macos M1 chips. So adding a amd64 case is not really needed.
To my understanding the error occurs, because the user is running an Intel Mac, and brew wants to see an url for macos amd64, but cannot find one.

**From my point of view, it should be possible to add a formula containing only a macos arm entry to a tap and users not running on macos arm should still be able to use the tap normally.**

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew tap kreuzwerker/taps`

It is fixed now, so it is not possible to reproduce anymore. Or is there a way to run `brew tap kreuzwerekr/taps` for a specific commit of that tap?
```

**Comment by carlocab** [comment]
Formulae aren't really designed for distributing binary packages this way, so I think the issue you saw with `brew tap kreuzwerker/taps` is expected behaviour. Binaries are supposed to be distributed using `bottle` blocks.

If you want to restrict installing a formula to ARM, use
```ruby
depends_on arch: :arm64
```
instead of building a formula that is conditionally incomplete.
