### ISSUE TITLE
brew shellenv does not return any output

### ISSUE THREAD

**Issue by deweller** [Homebrew/brew#11851]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.6-102-g9fe6427
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9fe642759c9c4772d50cee279665422f7f403530
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 922c1e06b378613fd5ebb980d8ee6bd4d1143574
Core tap last commit: 59 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Users/dweller/bin/sub -w
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.32.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.1-arm64
CLT: 12.5.0.22.9
Xcode: 12.5.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  imath
  openexr

Warning: /usr/bin occurs before /opt/homebrew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/opt/homebrew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

The following tools exist at both paths:
  phpize
  git-receive-pack
  python3
  phar.phar
  pip3
  phar
  rsync
  git-upload-archive
  php
  tidy
  git-shell
  git-upload-pack
  git
  php-config

Warning: Homebrew's "bin" was not found in your PATH.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to configure my shell PATH

### What happened (include all command output)?

`brew shellenv` returns no output

```
~ /opt/homebrew/bin/brew shellenv
~
```

### What did you expect to happen?

export shell environment configurations

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
/opt/homebrew/bin/brew shellenv
```

**Comment by deweller** [comment]
```
~ echo $HOMEBREW_SHELLENV_PREFIX $HOMEBREW_PREFIX

/opt/homebrew /opt/homebrew
```

**Comment by carlocab** [comment]
That's expected. See #11789. Do you need it to return output once it's been set in your environment?

**Comment by deweller** [comment]
You're recommendation was to include:
`eval $(/opt/homebrew/bin/brew shellenv)` in `.zprofile`

(https://github.com/Homebrew/discussions/discussions/938#discussioncomment-407419)

I assumed that brew shellenv used to output something and now it now longer does.

My `$PATH` variable used to be altered.  And now it is no longer being altered to include /opt/homebrew/bin and /opt/homebrew/sbin.

**Comment by deweller** [comment]
```
~ unset HOMEBREW_SHELLENV_PREFIX
/opt/homebrew/bin/brew shellenv

export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export HOMEBREW_SHELLENV_PREFIX="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
```

**Comment by carlocab** [comment]
This is behaving as expected then. `/opt/homebrew/bin/brew shellenv` is only meant to be run once. It should also have run successfully since you have `HOMEBREW_SHELLENV_PREFIX` set in your environment.

I don't know why this is happening:

> My `$PATH` variable used to be altered. And now it is no longer being altered to include /opt/homebrew/bin and /opt/homebrew/sbin.

But it's relatively clear that it's not because of `brew shellenv`. There is something else going on in your config that's causing this.

**Comment by deweller** [comment]
I think the order has changed in when the PATH was being set in my config or else `brew shellenv` used to always output these exports.

I will include `unset HOMEBREW_SHELLENV_PREFIX && opt/homebrew/bin/brew shellenv ` in my config in order to make this work in my setup.

**Comment by deweller** [comment]
Thanks for your help.  I can make it work now.

**Comment by jcchak** [comment]
Had the same issue as @deweller...the change that was done recently to Library/Homebrew/cmd/shellenv.sh doesn't allow me to reload the shell (i.e: with `exec $SHELL`) anymore.

It can be easily fixed adding `unset HOMEBREW_SHELLENV_PREFIX && opt/homebrew/bin/brew shellenv` as Devon mentions in his last comment, but I think it might be a problem that the post-installation instructions don't mention that "fix" for that kind of special cases.

**Comment by carlocab** [comment]
I don't quite follow -- why does `exec $SHELL` retain `HOMEBREW_SHELLENV_PREFIX` but reset your `PATH`?

**Comment by jcchak** [comment]
Ok, I see it's a problem when `PATH` is setup.

One simple `.zshrc` to reproduce the issue:

```
PATH="/usr/bin:/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin"

eval "$(/opt/homebrew/bin/brew shellenv)"
```

So the first load of the shell is ok as `HOMEBREW_SHELLENV_PREFIX` is unset, but followings ones gets only .zshrc PATH as `HOMEBREW_SHELLENV_PREFIX` is set.

Well, I guess if someone is playing with the PATH on their config they will know how to fix the problem (or find this github issue), so please forget my comments about the post-installation instructions :)
