### ISSUE TITLE
Allow pinning for casks

### ISSUE THREAD

**Issue by cglong** [Homebrew/brew#11860]
### Provide a detailed description of the proposed feature

I wish I could use `brew pin` to pin casks to a specific version rather than only formulae.

### What is the motivation for the feature?

I use the `mactex` cask, which is a ~4GB download. The newest version of the cask has a requirement I can't meet (minimum macOS version), but every `brew upgrade` call tries to download the new version anyway. I wish I could pin `mactex` to short-circuit this.

### How will the feature be relevant to at least 90% of Homebrew users?

Casks are commonly used for proprietary applications. Unlike FOSS, proprietary apps can make huge UX changes that the user cannot revert. Allowing everyone to pin casks would help users ensure they don't suffer any regressions in their favorite apps.

### What alternatives to the feature have been considered?

I considered suggesting that cask requirements be evaluated *before* the download, but this would be relevant for a much smaller segment of users.

**Comment by miccal** [comment]
Please see the discussion in https://github.com/Homebrew/homebrew-cask/issues/90242.

I would suggest that you remove `mactex` from your `brew list --casks` by running the command `rm -r /usr/local/Caskroom/mactex`.
