### ISSUE TITLE
brew reinstall fail on cached recipe

### ISSUE THREAD

**Issue by glensc** [Homebrew/brew#11866]
### `brew config` output

```shell
[not relevant, not posting noise]
```

### `brew doctor` output

```shell
[not relevant, not posting noise]
```

### 

- [ ] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Recover broken installation. I wanted to use pip2.

### What happened (include all command output)?

Seems brew is unable to reinstall from internal location, like:
`/usr/local/opt/python@2/.brew/python@2.rb`

as I believe it's deleting (renaming) the dir while building brew is buildng.

i.e a simple test (below) showed that if I made copy of the file, the output was different.

So therefore I believe brew is unable to re-use `.brew/FORMULA.rb` recipes. I've seen the same for other expired formulas like pygobject.rb

```
➔ brew reinstall python@2
==> Downloading 
[...snip..]
==> Reinstalling python@2
Error: An exception occurred within a child process:
  FormulaUnavailableError: No available formula with the name "/usr/local/opt/python@2/.brew/python@2.rb".

➔ l /usr/local/opt/python@2/.brew/python@2.rb
-rw-r--r-- 1 glen staff 13K okt   19  2019 /usr/local/opt/python@2/.brew/python@2.rb

➔ brew reinstall /usr/local/opt/python@2/.brew/python@2.rb
Error: Failed to load cask: /usr/local/opt/python@2/.brew/python@2.rb
Cask 'python@2' is unreadable: wrong constant name #<Class:0x00007fd30f403258>
Warning: Treating /usr/local/opt/python@2/.brew/python@2.rb as a formula.
==> Downloading 

[...snip...]
==> Reinstalling python@2
Error: An exception occurred within a child process:
  FormulaUnavailableError: No available formula with the name "/usr/local/opt/python@2/.brew/python@2.rb".



➔ cp /usr/local/opt/python@2/.brew/python@2.rb ~
➔ brew reinstall ~/python@2.rb
Error: Failed to load cask: /Users/glen/python@2.rb
Cask 'python@2' is unreadable: wrong constant name #<Class:0x00007fd14022adf8>
Warning: Treating /Users/glen/python@2.rb as a formula.
==> Downloading 
[...snip...]
==> Reinstalling python@2
==> ./configure --prefix=/usr/local/Cellar/python@2/2.7.17_1 --enable-ipv6 --datarootdir=/usr/local/Cellar/python@2/2.7
[...snip...]
```

the build failed, but that's not relevant here

### What did you expect to happen?

`brew reinstall` should be able to use `/usr/local/opt/RECIPE/.brew/RECIPE.rb` or at least give a better error than file not found

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew reinstall recipe_thats_expired_from_homebrew_core_but_installed_locally
```
```

**Comment by MikeMcQuaid** [comment]
> ### `brew config` output
> ```shell
> [not relevant, not posting noise]
> ```
> 
> ### `brew doctor` output
> ```shell
> [not relevant, not posting noise]
> ``

We need this information.

**Comment by glensc** [comment]
doctor

```
HOMEBREW_VERSION: 3.2.7-17-g8b69798
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8b69798ba4d351a69a557baae4152e0f8f0040bf
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4f32f0d4746b71392e253914eb2e1f7adf3552a3
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 86400
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.s6rKipQTOL/org.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/nvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.1-x86_64
CLT: 12.5.0.22.11
Xcode: N/A
```

**Comment by glensc** [comment]
`$ brew doctor`

<details>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unknown support status

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  php@7.1-ssh2
  python@2
  php@7.2-solr
  php@7.2-tideways-xhprof
  php@7.2-imagick
  cryptopp
  php72-mongodb
  judy
  php@7.1-imap
  git-mr
  php@7.2-translit
  php@7.2-xhprof
  php@7.2-xdebug
/usr/local/Homebrew/Library/Taps/glensc/homebrew-tap/lib/php_pecl_formula.rb:61: warning: already initialized constant Class::NAME_PATTERN
/usr/local/Homebrew/Library/Taps/kabel/homebrew-pecl/lib/php_pecl_formula.rb:61: warning: previous definition of NAME_PATTERN was here

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  lua@5.1
  node@10
  php@7.2
  py2cairo
  rdesktop
  squashfuse
  sshfs

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-eid
Untap them with `brew untap`.

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php@7.1-ssh2
  python@2
  pipenv
  php@7.2-solr
  php@7.2-tideways-xhprof
  flake8
  imath
  php@7.2-imagick
  lua@5.1
  php@7.1-imap
  php@7.2-translit
  php@7.2-xhprof
  rpm2cpio
  six
  docker-compose
  git-utils
  php@7.2-xdebug
  git-extras

Warning: Some installed formulae are not readable:
  php@7.1-ssh2: cannot load such file -- /usr/local/opt/php@7.1-ssh2/lib/php_pecl_formula

  php@7.2-solr: cannot load such file -- /usr/local/opt/php@7.2-solr/lib/php_pecl_formula

  php@7.2-tideways-xhprof: cannot load such file -- /usr/local/opt/php@7.2-tideways-xhprof/lib/php_pecl_formula

  php@7.2-imagick: cannot load such file -- /usr/local/opt/php@7.2-imagick/lib/php_pecl_formula

  php72-mongodb: cannot load such file -- /usr/local/opt/php72-mongodb/Abstract/abstract-php-extension

  php@7.1-imap: cannot load such file -- /usr/local/opt/php@7.1-imap/lib/php_extension_formula

  php@7.2-translit: cannot load such file -- /usr/local/opt/php@7.2-translit/lib/php_pecl_formula

  php@7.2-xhprof: cannot load such file -- /usr/local/opt/php@7.2-xhprof/lib/php_pecl_formula

  php@7.2-xdebug: cannot load such file -- /usr/local/opt/php@7.2-xdebug/lib/php_pecl_formula

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/bin/pylupdate5
  /usr/local/bin/pylupdate6
  /usr/local/bin/pyrcc5
  /usr/local/bin/pyuic5
  /usr/local/bin/pyuic6
  /usr/local/share/qt/plugins/PyQt6
  /usr/local/share/qt/plugins/designer/libpyqt6.dylib

```
</details>

**Comment by glensc** [comment]
@MikeMcQuaid are you sure? did you even read the issue?

seems deliberately making issue-reporting so annoying, so that people just no longer want to report anything.

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid are you sure?

Yes. I needed:
- the Homebrew version number
- the core tap HEAD

> did you even read the issue?

Yes. You either didn't read or decided you know better than the issue template, though.

> seems deliberately making issue-reporting so annoying

Alternatively: we're asking for easily accessible information we need to make issue reporting quicker for everyone.

I'll reopen but given your tone here: I personally have no interest in helping you any further here.

**Comment by glensc** [comment]
The problem is not related to the tap (recipe is being deleted on the HEAD) or brew version (it's been around for months, maybe even years (haven't kept track of it)).

but as of today, I figured it's very easy to reproduce, to make a bug report of it.

**Comment by MikeMcQuaid** [comment]
> brew version (it's been around for months, maybe even years (haven't kept track of it).

Nothing is unrelated to the Homebrew version. You can't reproduce this on Homebrew 0.1. You can, it seem, reproduce this on 3.2.7. This relates to some code that has changed recently. This information is needed for us to know where best to look and whether this is a regression or something that's never worked.

Many problems are related to taps. This is a formula that used to be in Homebrew/homebrew-core and it could be that it was that you were stuck on an old revision or have a non-`master` revision checked out. This formula used to be in the core tap and was removed. This is also likely to be related to the tap remote and revision.

Sorry, you're not going to convince me that the information I said I needed I actually didn't.

**Comment by carlocab** [comment]
We can't rely on users deciding when the requested information is relevant or not, because the average user is wrong about it more than half the time. That just leads to time wasted for everyone all around. Providing the information is not particularly onerous, so we'd rather avoid the wasted time by requiring it from everybody instead.

It might lead to a few extra steps for issue reports when it's not needed, but that pales in comparison to the time saved when it's actually needed. So, even if you are correct about the information not being relevant, we still have good reasons to require it anyway. You might find this annoying. That's regrettable, but we can't run our issue tracker based on your needs alone.

That said, the output of `brew doctor` is relevant here: there's a reason why it complains about installed kegs that have no formulae. If you really don't want to maintain your own formula (even given all the tooling in `brew` designed to make this easy), you can use this one: https://github.com/lithammer/homebrew-deadsnakes.git

**Comment by glensc** [comment]
@carlocab thanks for the project share, but this issue is not about python@2, it was just used as an example to show the bug.

**Comment by carlocab** [comment]
To be clear: the output of `brew doctor` tells you that this is expected behaviour, so I don't think it's a bug.

**Comment by glensc** [comment]
@carlocab the same code path seems to be used when running `brew upgrade`.

at the end of bottles brew, 
brew attempts to `brew reinstall recipe` that has been removed from tap and has broken dependencies. I used to have `pygobject` haunting me with very similar error. by now I've `brew uninstall pygobject` as I never installed it directly.

**Comment by woshiJason** [comment]
I can access 'raw.githubusercontent.com/Homebrew/install/HEAD/install.sh' through Google browser, but I can't access it through Ping from terminal，who can help me solve this problem? thanks a lot

**Comment by glensc** [comment]
Here's output of the `brew upgrade` I mentioned earlier (it's from my older macOS):

```
...
Error: Could not get runtime dependencies from /usr/local/opt/pygtk/.brew/pygtk.rb!
Error: No available formula with the name "pygobject". Did you mean pygobject3?
```

```
[~] ➔ brew reinstall pygtk
Error: No available formula with the name "pygobject" (dependency of pygtk). Did you mean pygobject3?
```

```
[~] ➔ brew info pygtk
pygtk: stable 2.24.0
GTK+ bindings for Python
http://www.pygtk.org/
/usr/local/Cellar/pygtk/2.24.0_3 (591 files, 15.4MB) *
  Poured from bottle on 2019-06-18 at 13:30:40
From: /usr/local/opt/pygtk/.brew/pygtk.rb
==> Dependencies
Build: pkg-config ✔
Error: No available formula with the name "pygobject". Did you mean pygobject3?
[~] ➔
```

I guess everything looks like expected. So this can be closed
