### ISSUE TITLE
Version parsed from https://.../2.1b.tar.gz should be 2.1b not 2.1

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#1187]
Currently the version parsing results in
```
https://github.com/biocore/sortmerna/archive/2.1b.tar.gz -> version 2.1
https://github.com/biocore/sortmerna/archive/foo-2.1b.tar.gz -> version 2.1b
```
Presumably they should both be parsed as `2.1b`.

**Comment by MikeMcQuaid** [comment]
Unfortunately while they both perhaps _should_ our versions code is such that it's pretty hard to make that change while guaranteeing that we're not going to break another version format 😭

**Comment by ilovezfs** [comment]
This was more of a note to myself to fix this. I'm not expecting you to.

**Comment by MikeMcQuaid** [comment]
Ok, cool. Either way I'd love to see this stuff be more consistent but we'll probably need some sort of automated "test all of homebrew/core and make sure it stays the same" thing 😭
