### ISSUE TITLE
line 11: cd: /usr/local/Homebrew/bin: No such file or directory

### ISSUE THREAD

**Issue by MarcelXia** [Homebrew/brew#11886]
### `brew config` output

```shell
brew config 
/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory
HOMEBREW_VERSION: 3.2.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: f026dd21c195952747395ebdda24327204f012ec
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0f81ec1482f5b620523970582baa5f517a7c4393
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.32.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-arm64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.4 => /Users/marcelloh/Downloads/Xcode.app/Contents/Developer
Rosetta 2: false
```

### `brew doctor` output

```shell
brew doctor                    
/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to use brew on a Mac M1. I think this has a different directory structure or something.

### What happened (include all command output)?

With every command I do it has this message which makes me not trust what brew is doing for me.

### What did you expect to happen?

No error messages, but even the normal brew command has that

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew
/opt/homebrew/bin/brew: line 11: cd: /usr/local/Homebrew/bin: No such file or directory
Example usage:
  brew search TEXT|/REGEX/
  brew info [FORMULA|CASK...]
  brew install FORMULA|CASK...
```

**Comment by Bo98** [comment]
This appears to be caused by a broken (leftover?) `/usr/local/bin/brew` symlink.

Anyhow, I've opened #11887 which will probably fix this.

**Comment by MarcelXia** [comment]
Ah, correct :-) If I remove that broken symlink, it works as expected. I will close this.
