### ISSUE TITLE
`--system-site-packages` should be customizable by `virtualenv_create`

### ISSUE THREAD

**Issue by jiasli** [Homebrew/brew#11885]
### Provide a detailed description of the proposed feature

https://github.com/Homebrew/brew/pull/11611 specifies `--system-site-packages` when creating a virtual environment. This makes Azure CLI installed by Homebrew conflict with [Ansible collection for Azure](https://github.com/ansible-collections/azure) installed to system `site-packages` using `pip`. (https://github.com/Azure/azure-cli/issues/19027, https://github.com/Homebrew/discussions/discussions/2009).

This makes Homebrew less flexible, even though it fixes https://github.com/Homebrew/brew/issues/1790.

### What is the motivation for the feature?

To makes Homebrew more flexible.

### How will the feature be relevant to at least 90% of Homebrew users?

No

### What alternatives to the feature have been considered?

Let the users create virtual env by themselves when installing with `pip`.

**Comment by carlocab** [comment]
I had come to the same conclusion after our discussion at Homebrew/discussions#2009. This would be good to have, and should be straightforward to implement.
