### ISSUE TITLE
Cannot run any brew commands 

### ISSUE THREAD

**Issue by crisciceroe** [Homebrew/brew#11881]
### `brew config` output

```shell
from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `require_relative'
	7: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	6: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	5: from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `<top (required)>'
	4: from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `require_relative'
	3: from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `<top (required)>'
	2: from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `require'
	1: from /usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `require': cannot load such file -- sorbet-runtime-stub (LoadError)
```

### `brew doctor` output

```shell
Same error as above.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

trying to run brew cleanup and update brew. I am on Big Sur. It crashed everything and wiped my entire filesystem had to go through some long steps to get back into the account. 

### What happened (include all command output)?

Crashes and will not allow any brew usage. 
![Uploading Screen Shot 2021-08-18 at 4.36.43 PM.png…]()

### What did you expect to happen?

I expected to run it smoothly. Everything is working fine in Catalina. What I did notice is some strange new path prepended to my actual path.  .cabal, and .ghcup

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew cleanup 
brew doctor. 




error: bad signature 0x00000000
fatal: index file corrupt
Error: Fetching /usr/local/Homebrew failed!
error: bad signature 0x00000000
fatal: index file corrupt
error: bad signature 0x00000000
fatal: index file corrupt
error: bad signature 0x00000000
fatal: index file corrupt
Traceback (most recent call last):
	9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `require_relative'
	7: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	6: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	5: from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `<top (required)>'
	4: from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `require_relative'
	3: from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `<top (required)>'
	2: from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `require'
	1: from /usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `require': cannot load such file -- sorbet-runtime-stub (LoadError)
```

**Comment by alebcay** [comment]
> I expected to run it smoothly. Everything is working fine in Catalina. What I did notice is some strange new path prepended to my actual path. .cabal, and .ghcup

What path are you seeing?

Can you try `brew update-reset` and then try `brew config` again?

**Comment by MikeMcQuaid** [comment]
This is specific to your machine but what @alebcay has said may help.

**Comment by crisciceroe** [comment]
brew update-reset
==> Fetching /usr/local/Homebrew...
error: bad signature 0x00000000
fatal: index file corrupt

==> Resetting /usr/local/Homebrew...
error: bad signature 0x00000000
fatal: index file corrupt


From https://github.com/Homebrew/homebrew-core
 * [new branch]            hard       -> origin/hard
   b651ad4ea1..4795d5b754  master     -> origin/master

brew config
Traceback (most recent call last):
	9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `require_relative'
	7: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	6: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	5: from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `<top (required)>'
	4: from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `require_relative'
	3: from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `<top (required)>'
	2: from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `require'
	1: from /usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `require': cannot load such file -- sorbet-runtime-stub (LoadError)

**Comment by Bo98** [comment]
Run `rm -f /usr/local/Homebrew/.git/index && git -C /usr/local/Homebrew reset`. You may potentially need to do `brew update-reset` again afterwards too.

**Comment by crisciceroe** [comment]
Thanks! Excellent! that actually worked! Now I got a different warning of outdated command line tools. Are there new ones for Big Sur?

**Comment by carlocab** [comment]
Yes. `brew doctor` will show you update instructions if you need it.
