### ISSUE TITLE
brew broken in tmux from shellenv

### ISSUE THREAD

**Issue by rothgar** [Homebrew/brew#11883]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0e63fb8200d54e365cfb20eb8c7a98620b23b42f
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c4568afa9224efb2a343c40f8cd00366c1512227
Core tap last commit: 26 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0.1 build (parse error)
Git: 2.32.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.11.0-27-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: 5.5.0_7
xorg: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  libva-internal

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  //home/ANT.AMAZON.COM/rothgar/.cargo/bin/cargo-install-update-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libvdpau
  six
Warning: Use wayland instead of deprecated linuxbrew/xorg/wayland
Warning: Use libvdpau instead of deprecated linuxbrew/xorg/libvdpau
Warning: Use wayland-protocols instead of deprecated linuxbrew/xorg/wayland-protocols
Warning: Use wayland instead of deprecated linuxbrew/xorg/wayland
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Open a terminal and then start a tmux session.

### What happened (include all command output)?

The initial terminal works but the tmux session does not have brew available or any brew commands in path

It appears to be related to #11789
If I unset `HOMEBREW_SHELLENV_PREFIX` in my zshrc then the shellenv command works and brew is available inside tmux.

![homebrew](https://user-images.githubusercontent.com/371796/129987351-48b59a26-3957-4d46-a7c7-a38ffa930393.gif)

### What did you expect to happen?

Ability to still run brew inside a tmux session.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Please see attached gif.

1. open a terminal
1. open tmux

It works if I
1. open a terminal
1. `unset HOMEBREW_SHELLENV_PREFIX` inside .zshrc
1. open tmux
```

**Comment by rothgar** [comment]
This is also related to #11851 which has the same work around.

One thing to note is not all tmux users will know to unset that variable or know why homebrew is broken only inside tmux.

**Comment by MikeMcQuaid** [comment]
@rothgar You'll need to provide a lot more information here for debugging. How are you calling `brew shellenv`? What's your `PATH` both inside and outside `tmux`?

**Comment by rothgar** [comment]
I'm calling `brew shellenv` via https://gitlab.com/jgarr/dotfiles/-/blob/main/zdotdir/.zshrc#L68
```
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
```
A normal terminal my path is
```
/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/rothgar/bin:/home/rothgar/.local/bin:/home/rothgar/.toolbox/bin:/home/rothgar/go/bin://home/rothgar/.cargo/bin:/home/rothgar/.krew/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/snap/bin:/home/rothgar/.rvm/bin
```
Launching tmux my path is
```
/home/rothgar/bin:/home/rothgar/.local/bin:/home/rothgar/.toolbox/bin:/home/rothgar/go/bin://home/rothgar/.cargo/bin:/home/rothgar/.krew/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/snap/bin:/home/rothgar/.rvm/bin
```

**Comment by carlocab** [comment]
This happens because you reset your `PATH` here:

https://gitlab.com/jgarr/dotfiles/-/blob/main/zdotdir/.zshrc#L56

Resetting your `PATH` requires `unset`ting `HOMEBREW_SHELLENV_PREFIX`.

**Comment by rothgar** [comment]
That is what I found from those issues and my own troubleshooting. Resetting my PATH is preferred for new shells so I always start from a known state.

Is the requirement to unset `HOMEBREW_SHELLENV_PREFIX` documented somewhere? I only found this working backwards from release notes and finding the issues here on GitHub.

**Comment by MikeMcQuaid** [comment]
> Is the requirement to unset `HOMEBREW_SHELLENV_PREFIX` documented somewhere? I only found this working backwards from release notes and finding the issues here on GitHub.

No. It's a performance optimisation around the assumption that people won't do what you've done here 😁
