### ISSUE TITLE
Linux Brew - No such file or directory on install + FIX

### ISSUE THREAD

**Issue by jbremson** [Homebrew/brew#11880]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: f026dd21c195952747395ebdda24327204f012ec
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: e835fc84ca3fc862797a39bd4613582b13862d8f
Core tap last commit: 43 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.11.0-25-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install homebrew on a new Ubuntu 20.04 VM.

### What happened (include all command output)?

Path error from the command line. 

`brew help
/bin/bash: /home/linuxbrew/.linuxbrew/Library/Homebrew/brew.sh: No such file or directory
`

### What did you expect to happen?

The help message.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
As documented above. 

FIX

I was able to get it to work by making a symbolic link from `Library` -> `Homebrew`
in `/home/linuxbrew/.linuxbrew`.
```

**Comment by MikeMcQuaid** [comment]
Sorry, you're going to need to supply more information here on what you tried and what the output was. As-is there's not enough information here to help you.
