### ISSUE TITLE
Support multi-user system

### ISSUE THREAD

**Issue by diogoeichert** [Homebrew/brew#11893]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: f026dd21c195952747395ebdda24327204f012ec
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 00e48ed20f88de830afbf180af46787edc7b5d96
Core tap last commit: 46 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  fakeroot
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install formulas from different `admin` users on the same system.

### What happened (include all command output)?

After installing formulas with one `admin` user, the other `admin` user gets permission errors when trying to install other formulas.

### What did you expect to happen?

I expect all user in the `admin` group to be able to install formulas without issues.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
(log in as user a)
brew install spotify
(log in as user b)
brew install telegram
(permission errors occur)
```

**Comment by ipatch** [comment]
this has been an ongoing topic / discussion for quite some time now. i don't you'll get much traction with this issue TBH, and more than likely it will get closed by one of the maintainers.

there's a pretty decent stackoverflow Q/A about this topic. i'd suggest reading the below link. and my personal experience using brew on a multi user system with github actions if you plan on doing tap maintenance at all, see the answer provided by pokidyshev

https://stackoverflow.com/a/68209534/708807

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Implementing support for multiple-user Homebrew user was being worked on and tracked in Homebrew/install#328 and #9219, last I recall seeing, but there hasn't been any activity in that area recently.

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this given the above, all previous efforts have stalled.
