### ISSUE TITLE
Brew cleanup is leaving installs in the caskroom using up space

### ISSUE THREAD

**Issue by PlanetWilson** [Homebrew/brew#11912]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: f026dd21c195952747395ebdda24327204f012ec
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8535e6dbdcb160455b663f4bff4b7ed010b2094d
Core tap last commit: 4 days ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.33.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-arm64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I did a brew cleanup to clean up cached files etc to free up space on my Macbook Air. I can see using a disk space tool that it has not removed a number of installer pkg files and install .app files too. These are taking up a large amount of space. They are not required as far as I know for running the apps which have been installed to /Applications.

### What happened (include all command output)?

Brew cleanup removed cached files but left the caskroom files in place such as the Microsot Office installer.

➜  ~ brew cleanup
Warning: Skipping terraform: most recent version 1.0.5 not installed
Removing: /Users/mark/Library/Caches/Homebrew/terraform--1.0.4... (17.2MB)
Removing: /Users/mark/Library/Caches/Homebrew/Cask/powershell--7.1.3.pkg... (63.5MB)
Removing: /Users/mark/Library/Caches/Homebrew/Cask/calibre--5.24.0.dmg... (144.5MB)
Removing: /Users/mark/Library/Caches/Homebrew/Cask/onyx--3.9.7.dmg... (5.0MB)
Removing: /Users/mark/Library/Caches/Homebrew/Cask/google-chrome--92.0.4515.131.dmg... (177.7MB)
Removing: /Users/mark/Library/Logs/Homebrew/youtube-dl... (64B)
Removing: /Users/mark/Library/Logs/Homebrew/python@3.9... (2 files, 4.4KB)
➜  ~ brew cleanup -s
Warning: Skipping terraform: most recent version 1.0.5 not installed
Removing: /Users/mark/Library/Caches/Homebrew/Cask/mediainfo--21.03.dmg... (10MB)
Removing: /Users/mark/Library/Caches/Homebrew/Cask/filebot--4.9.4.tar.xz... (40.2MB)
Removing: /Users/mark/Library/Caches/Homebrew/Cask/dotnet-preview--6.0.0-preview.7.21377.19,291e415b-c521-45b9-b817-710c342d2eb8:d05ca09bec35d4fbb31a07d700e9f416.pkg... (26.8MB)

<img width="831" alt="Screenshot 2021-08-24 at 09 37 40" src="https://user-images.githubusercontent.com/283116/130585249-ce97b3f5-8d63-4bb7-8a61-7aec8db03f5c.png">

### What did you expect to happen?

Caskroom installers should be removed to free up space. I only have a 256GB SSD and these take up a substantial amount of space.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew cleanup
```

**Comment by miccal** [comment]
Please see https://github.com/Homebrew/homebrew-cask/issues/74831 and https://github.com/Homebrew/homebrew-cask/issues/66242.

`brew cleanup` cremoves things in `~/Library/Caches/Homebrew/*`, and does not touch things in `*/Caskroom`.
