### ISSUE TITLE
-L#{sysroot}/usr/lib isn't always removed by superenv with Xcode 8

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/brew#1191]
Observations:
- superenv isn't stripping some paths that resolve to -L#{sysroot}/usr/lib: https://github.com/Homebrew/homebrew-core/issues/5347#issuecomment-250629471
- MacOSX10.12.sdk is a symlink to MacOSX.sdk so there exist non-canonical paths for sysroot
- MacOS.sdk_root is non-canonical on Xcode 8: `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk`
- We find sdk paths here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac/sdk.rb#L48-L51 and don't immediately canonicalize them
- We blacklist paths here: https://github.com/Homebrew/brew/blame/master/Library/Homebrew/shims/super/cc#L281 and compare them to canonicalized paths

This seems likely to have been responsible for breaking the python `sqlite3` module on Xcode-only Sierra systems.

Inference:
- we should `realpath` all the things, or else
- anticipate Xcode's symlinking behavior in other ways, and/or
- ?

Is there a correct `realpath` discipline we should use? Point of introduction? Point of use? Everywhere?

**Comment by MikeMcQuaid** [comment]
I guess I'd `realpath` everything and then use both the `real` and non-real version to decide what we should filter.

**Comment by gregory-nisbet** [comment]
Is this issue still open?

I think the blacklist code has drifted since this issue was created. Where does it live now? 

You can compare paths for equivalence using the inode and device number and that can save you the trouble of needing to `realpath` and needing to keep track of whether your path has been canonicalized or not.

silly example that prints `true`.

```
#!/usr/bin/ruby

class Test
    def self.file_sameness(a, b)
        if File.exists?(a) and File.exists?(b)
            st_a = File::Stat.new(a)
            st_b = File::Stat.new(b)
            st_a.ino == st_b.ino and st_a.dev == st_b.dev
        else
            false
        end
    end
end

puts Test.file_sameness("/tmp", "/private/tmp")

```

**Comment by MikeMcQuaid** [comment]
> Is this issue still open?

Yes.

> I think the blacklist code has drifted since this issue was created. Where does it live now?

Here I think but not sure: https://github.com/Homebrew/brew/blame/e77701075606cbcf3075d7fcc123556b63977bcf/Library/Homebrew/shims/super/cc#L227

**Comment by MikeMcQuaid** [comment]
Closing this out just because I'm not convinced it's a problem when building formulae. Sorry!
