### ISSUE TITLE
`brew search --verbose` to show short description

### ISSUE THREAD

**Issue by abitrolly** [Homebrew/brew#11932]
### Provide a detailed description of the proposed feature

Make `brew search -v nvm` return results similar to `brew search --desc nvm` with short description.

Currently `--verbose` does nothing for `brew search`.
```sh
$ brew search nvm --verbose
==> Formulae
convmv      mvnvm       nvm         nvi         nvc         nim         dvm
```

It would be awesome if `--verbose` resulted in the info like this.
```sh
$ brew search --desc nvm   
==> Formulae
tox: Generic Python virtualenv management and test command-line tool
vfuse: Convert bootable DMG images for use in VMware Fusion
```

I thought it could be a trivial printing of additional object field returned from https://github.com/Homebrew/brew/blob/6da8630f4e077b38883f6ea57d96e4002f7b8599/Library/Homebrew/search.rb#L77 but it seems to return names as strings, and I don't know how to lookup package data by its name.

### What is the motivation for the feature?

Understand if found `brew` packages are really what I look for.

### How will the feature be relevant to at least 90% of Homebrew users?

Yep.

### What alternatives to the feature have been considered?

The alternative is to invoke `brew info` for each found package manually.

**Comment by MikeMcQuaid** [comment]
> The alternative is to invoke `brew info` for each found package manually.

Or `brew search --desc`, no?

**Comment by abitrolly** [comment]
@MikeMcQuaid  `brew search --desc` outputs a different set of packages, because it instructs to search in descriptions, and standard `brew search` matches names.

**Comment by EricFromCanada** [comment]
`brew desc --name nvm` shows descriptions of packages with names containing "nvm":
```
convmv: Filename encoding conversion tool
mvnvm: Maven version manager
nvm: Manage multiple Node.js versions
```

**Comment by abitrolly** [comment]
So many commands. I would deprecate `brew desc` if `brew search -v` was working. Although `brew desc` interface looks cleaner, I'd expect it to show output similar to https://formulae.brew.sh/formula/multi-git-status#default (which is shown by `brew info`).

The `--verbose` flag is underused in `brew`. `brew commands -v` doesn't make the output any different too.

**Comment by MikeMcQuaid** [comment]
No. `--verbose` duplicates `--name` here so I'd review a PR to improve the discoverability of `--name`.

**Comment by abitrolly** [comment]
Just to make sure we are on the same wavelength. You mean that `search --verbose` duplicates the `desc --name`, so its not the discoverability of `search --name` that should be addressed, but the discoverability of `desc --name` in `search --help`, right?

**Comment by MikeMcQuaid** [comment]
Yup!
