### ISSUE TITLE
Brew always asks to be updated when trying to install an invalid formula name.

### ISSUE THREAD

**Issue by fseidel** [Homebrew/brew#1194]
When trying to install a formula that does not exist, Homebrew will complain that it hasn't been updated in a while, even if it has just been updated.

Specifically, it gives the "You haven't updated Homebrew in a while" warning.

To reproduce: try to install a nonexistent formula.

**Comment by chdiza** [comment]
I can't reproduce this.

**Comment by tml** [comment]
I just ran into this myself:

```
joey@sys$ brew update
Already up-to-date.
joey@sys$ brew install lyx
Error: No available formula with the name "lyx"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/lyx
To install it, run:
  brew install Caskroom/cask/lyx
==> You haven't updated Homebrew in a while.
A formula for lyx might have been added recently.
Run `brew update` to get the latest Homebrew updates!
```


Following from this issue in legacy-homebrew (first hit in Google) did no good:

```

joey@sys$ cd $(brew --repo); git fetch; git reset --hard origin/master; brew update
HEAD is now at 41b2df8 Merge pull request #1177 from scpeters/man_exit_code
Already up-to-date.
```

I realize that in this instance I will be able to install lyx from the provided cask, but it's a bit disconcerting to get the "==> You haven't updated Homebrew in a while." when I do it almost reflexively every day.

**Comment by MikeMcQuaid** [comment]
Can I see your `brew config` output please?

**Comment by tml** [comment]
HOMEBREW_VERSION: 1.0.5-43-g41b2df8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 41b2df8e338c3fe345afc89b1bb394e824213561
Last commit: 35 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a2941783d3052ebb6e0e8af4f7064da4dc3c7678
Core tap last commit: 19 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 5666
Clang: 8.0 build 800
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/joey/.rvm/rubies/ruby-2.1.2/bin/ruby
Java: 1.8.0_102, 1.8.0_45, 1.7.0_75, 1.7.0_45, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
