### ISSUE TITLE
brew progress bars print on newline on each update

### ISSUE THREAD

**Issue by TallonRain** [Homebrew/brew#11950]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: ab2118a402a44451b1d7559167b6956dc47cc19a
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e829483f9436ca4e9bbf569d40cf7e62a63e04e7
Core tap last commit: 37 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

On any `brew` task which invokes the progress bars, such as new installs or updates, the progress bars will always print on new lines on each new iteration of the progress bar.

### What happened (include all command output)?

λ brew install --cask wireshark
==> Downloading https://2.na.dl.wireshark.org/osx/Wireshark%203.4.8%20Intel%20
                                                                           0.1                                                                           0.8###                                                                        5.0######                                                                     9.3#########                                                                 13.4############                                                              17.6###############                                                           21.8##################                                                        25.7#####################                                                     29.9########################                                                  34.1###########################                                               38.2##############################                                            42.1#################################                                         46.2####################################                                      50.0######################################                                    54.1#########################################                                 58.1############################################                              61.9###############################################                           65.9##################################################                        69.8#####################################################                     74.0#######################################################                   77.7##########################################################                81.8#############################################################             85.8################################################################          89.2###################################################################       93.3######################################################################    97.5######################################################################## 100.0%
==> Installing Cask wireshark
==> Running installer for wireshark; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Password:
installer: Package name is Add Wireshark to the system PATH
installer: Installing at base path /
installer: The install was successful.
==> Running installer for wireshark; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is ChmodBPF
installer: Installing at base path /
installer: The install was successful.
==> Moving App 'Wireshark.app' to '/Applications/Wireshark.app'
==> Backing App 'Wireshark.app' up to '/usr/local/Caskroom/wireshark/3.4.8/Wir
==> Removing App '/Applications/Wireshark.app'
==> Purging files for version 3.4.8 of Cask wireshark
Error: It seems there is already a Binary at '/usr/local/bin/editcap'.

### What did you expect to happen?

Progress bar to not generate a newline and update on a single line.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Single step process. Run any `brew` command to generate progress bars; install any new formula or cask via `brew install` or update any outdated packages via `brew update`

Error is reproducible on any terminal emulator with any width.
```

**Comment by Bo98** [comment]
Sounds like some issue between your terminal and curl. You might find that you have the same issue with `/usr/bin/curl --progress-bar`.

**Comment by carlocab** [comment]
Can't reproduce. Probably an issue with your terminal.
