### ISSUE TITLE
Error: 'curl' must be installed and in your PATH!

### ISSUE THREAD

**Issue by jhnworks** [Homebrew/brew#11960]
### `brew config` output

```shell
[azureusr@SLAZEXVCLDSSO01 .linuxbrew]$ brew config
Error: Please update your system curl.
Minimum required version: 7.41.0
Your curl version: 7.29.0
Your curl executable: /usr/bin/curl
HOMEBREW_VERSION: 3.2.10-40-g7c37a34
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7c37a34ccaeed4f9c9ed94c037c55b8ba93c1309
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: d13f0e53ee1fd0b42431eebcd2844cbc7f7bff48
Core tap last commit: 14 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/azureusr/.linuxbrew
HOMEBREW_REPOSITORY: /home/azureusr/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/azureusr/.linuxbrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/azureusr/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: N/A
Git: 2.30.1 => /bin/git
Curl: 7.29.0 => /usr/bin/curl
Kernel: Linux 3.10.0-1160.36.2.el7.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
[azureusr@SLAZEXVCLDSSO01 .linuxbrew]$ echo $PATH
/home/azureusr/.linuxbrew/bin:/home/azureusr/.linuxbrew/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
[azureusr@SLAZEXVCLDSSO01 .linuxbrew]$ which curl
/usr/local/bin/curl
```

### `brew doctor` output

```shell
[azureusr@SLAZEXVCLDSSO01 .linuxbrew]$ brew doctor
Error: Please update your system curl.
Minimum required version: 7.41.0
Your curl version: 7.29.0
Your curl executable: /usr/bin/curl
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/curl-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/curl/curl.h
  /usr/local/include/curl/curlver.h
  /usr/local/include/curl/easy.h
  /usr/local/include/curl/mprintf.h
  /usr/local/include/curl/multi.h
  /usr/local/include/curl/options.h
  /usr/local/include/curl/stdcheaders.h
  /usr/local/include/curl/system.h
  /usr/local/include/curl/typecheck-gcc.h
  /usr/local/include/curl/urlapi.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libcurl.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/libcurl.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libcurl.a

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install ping-devops
Ref : https://devops.pingidentity.com/get-started/pingDevopsUtil/
brew tap pingidentity/devops
brew install ping-devops

### What happened (include all command output)?

[azureusr@SLAZEXVCLDSSO01 .linuxbrew]$ brew install openssl
Error: Please update your system curl.
Minimum required version: 7.41.0
Your curl version: 7.29.0
Your curl executable: /usr/bin/curl
Warning: Building m4 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
Updating Homebrew...
==> Downloading https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/gmp/manifests/6.2.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/gmp/blobs/sha256:47ec066627ce0564e7c6b5da2a3311cdcbf09762dce6bad
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:47ec066627ce0564e7c6b5da2a331
######################################################################## 100.0%
Warning: isl@0.18 has been deprecated because it is a versioned formula!
==> Downloading https://ghcr.io/v2/linuxbrew/core/isl/0.18/manifests/0.18
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/isl/0.18/blobs/sha256:3ef95686496676a3c73c57db6eee32a9f039e9c2b7
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:3ef95686496676a3c73c57db6eee3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/mpfr/manifests/4.1.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/mpfr/blobs/sha256:5fa04c762dd682c46b3c15d2c28e89a36353717c533e7a
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5fa04c762dd682c46b3c15d2c28e8
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libmpc/manifests/1.2.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libmpc/blobs/sha256:c12f0406fb375c08d4c9f699ec2d28099088bb999fe9
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:c12f0406fb375c08d4c9f699ec2d2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/zlib/manifests/1.2.11
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/zlib/blobs/sha256:6f604280b9e056da163b81cef3076b2e39bbd2b8d3cc8c
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:6f604280b9e056da163b81cef3076
######################################################################## 100.0%
Warning: Building binutils from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://ftp.gnu.org/gnu/binutils/binutils-2.37.tar.xz
######################################################################## 100.0%
Warning: Building gcc@5 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-5.5.0/gcc-5.5.0.tar.xz
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/brotli/manifests/1.0.9
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/brotli/blobs/sha256:079fe73a868cd0c2b8086d902a88d49ab03921a553ae
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:079fe73a868cd0c2b8086d902a88d
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/pkg-config/manifests/0.29.2_4
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/pkg-config/blobs/sha256:bc8ac04f3d8e42a748f40544f8e1b7f2471f3260
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:bc8ac04f3d8e42a748f40544f8e1b
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/gpatch/manifests/2.7.6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/gpatch/blobs/sha256:70df1fb356ca7ccccd277110fcf467ea9fd0dc7337c9
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:70df1fb356ca7ccccd277110fcf46
######################################################################## 100.0%
Warning: Building ncurses from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://ftp.gnu.org/gnu/ncurses/ncurses-6.2.tar.gz
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/readline/manifests/8.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/readline/blobs/sha256:cf7ae93f4dc5560c7c7fac35d3fbb7f528a43f3084
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:cf7ae93f4dc5560c7c7fac35d3fbb
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libxml2/manifests/2.9.12
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libxml2/blobs/sha256:2b4091b5697e5011a8bd1ef89e762e73a8102dfdfd9
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:2b4091b5697e5011a8bd1ef89e762
######################################################################## 100.0%
Warning: Building gettext from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://ftp.gnu.org/gnu/gettext/gettext-0.21.tar.xz
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libunistring/manifests/0.9.10
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libunistring/blobs/sha256:c3abe7fa8b2fb314e2bbbe003e9db550148e95
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:c3abe7fa8b2fb314e2bbbe003e9db
######################################################################## 100.0%
Warning: Building libidn2 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://ftp.gnu.org/gnu/libidn/libidn2-2.3.2.tar.gz
######################################################################## 100.0%
Warning: Building openssl@1.1 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://curl.haxx.se/ca/cacert-2020-01-01.pem
==> Downloading from https://curl.se/ca/cacert-2020-01-01.pem
######################################################################## 100.0%
==> Downloading https://cpan.metacpan.org/authors/id/L/LE/LEONT/Test-Harness-3.42.tar.gz
######################################################################## 100.0%
==> Downloading https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302175.tar.gz
######################################################################## 100.0%
==> Downloading https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.48.tar.gz
######################################################################## 100.0%
==> Downloading https://www.openssl.org/source/openssl-1.1.1l.tar.gz
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libssh2/manifests/1.9.0_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libssh2/blobs/sha256:07fa92938502deb9633103511ef95a7a54a9bd1a429
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:07fa92938502deb9633103511ef95
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/c-ares/manifests/1.17.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/c-ares/blobs/sha256:140ba2dd2dcbb041d411b37bca3c5e9c614fb066fc6a
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:140ba2dd2dcbb041d411b37bca3c5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/jemalloc/manifests/5.2.1_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/jemalloc/blobs/sha256:08def7a0bdddf9311aeca1d40b93f4ac1b8b0c13de
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:08def7a0bdddf9311aeca1d40b93f
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libev/manifests/4.33
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libev/blobs/sha256:0a2e30ca1379034e45954d63729f03aa55ad265f602d7
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:0a2e30ca1379034e45954d63729f0
######################################################################## 100.0%
Warning: Building nghttp2 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://github.com/nghttp2/nghttp2/commit/829258e7038fe7eff849677f1ccaeca3e704eb67.patch?full_inde
######################################################################## 100.0%
==> Downloading https://github.com/nghttp2/nghttp2/releases/download/v1.44.0/nghttp2-1.44.0.tar.xz
==> Downloading from https://github-releases.githubusercontent.com/11452676/ef4a67af-39a9-47f0-9637-fd01bc8e8c0e?X
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libyaml/manifests/0.2.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/libyaml/blobs/sha256:7467d0c0a6a389b6e3b90dee0ea083be1a85be412f8
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:7467d0c0a6a389b6e3b90dee0ea08
######################################################################## 100.0%
Warning: Building ruby@2.7 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://rubygems.org/rubygems/rubygems-3.2.22.tgz
######################################################################## 100.0%
==> Downloading https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.4.tar.xz
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/asciidoctor/manifests/2.0.16
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/asciidoctor/blobs/sha256:8c46e2d5344f1908d4bc0c2597867563b562e10
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:8c46e2d5344f1908d4bc0c2597867
######################################################################## 100.0%
Warning: Building util-linux from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.37/util-linux-2.37.tar.xz
######################################################################## 100.0%
Warning: Building openldap from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-2.5.7.tgz
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/rtmpdump/manifests/2.4.20151223_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/rtmpdump/blobs/sha256:422733ec0ea4c3884b781346333c9292c3042da1a3
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:422733ec0ea4c3884b781346333c9
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/zstd/manifests/1.5.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/zstd/blobs/sha256:35f3d0c3e35229b4b9d32a2315f061651ee1cf88e2d521
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:35f3d0c3e35229b4b9d32a2315f06
######################################################################## 100.0%
Warning: Building bison from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://ftp.gnu.org/gnu/bison/bison-3.7.6.tar.xz
######################################################################## 100.0%
Warning: Building krb5 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://kerberos.org/dist/krb5/1.19/krb5-1.19.2.tar.gz
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/curl/manifests/7.78.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/curl/blobs/sha256:27fad41c2dab52ad840ca7612bb045820456ba75c2d739
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:27fad41c2dab52ad840ca7612bb04
######################################################################## 100.0%
==> Installing dependencies for curl: m4, gmp, isl@0.18, mpfr, libmpc, zlib, binutils, gcc@5, brotli, pkg-config, gpatch, ncurses, readline, libxml2, gettext, libunistring, libidn2, openssl@1.1, libssh2, c-ares, jemalloc, libev, nghttp2, libyaml, ruby@2.7, asciidoctor, util-linux, openldap, rtmpdump, zstd, bison and krb5
==> Installing curl dependency: m4
==> ./configure --prefix=/home/azureusr/.linuxbrew/Cellar/m4/1.4.19
==> make
==> make install
🍺  /home/azureusr/.linuxbrew/Cellar/m4/1.4.19: 39 files, 889.0KB, built in 1 minute 32 seconds
==> Installing curl dependency: gmp
==> Pouring gmp--6.2.1.x86_64_linux.bottle.tar.gz
🍺  /home/azureusr/.linuxbrew/Cellar/gmp/6.2.1: 23 files, 3.9MB
==> Installing curl dependency: isl@0.18
==> Pouring isl@0.18--0.18.x86_64_linux.bottle.tar.gz
🍺  /home/azureusr/.linuxbrew/Cellar/isl@0.18/0.18: 81 files, 6.4MB
==> Installing curl dependency: mpfr
==> Pouring mpfr--4.1.0.x86_64_linux.bottle.tar.gz
🍺  /home/azureusr/.linuxbrew/Cellar/mpfr/4.1.0: 30 files, 7.8MB
==> Installing curl dependency: libmpc
==> Pouring libmpc--1.2.1.x86_64_linux.bottle.tar.gz
🍺  /home/azureusr/.linuxbrew/Cellar/libmpc/1.2.1: 14 files, 526.3KB
==> Installing curl dependency: zlib
==> Pouring zlib--1.2.11.x86_64_linux.bottle.tar.gz
🍺  /home/azureusr/.linuxbrew/Cellar/zlib/1.2.11: 12 files, 392.5KB
==> Installing curl dependency: binutils
==> ./configure --enable-deterministic-archives --prefix=/home/azureusr/.linuxbrew/Cellar/binutils/2.37 --infodir=
==> make
Last 15 lines from /home/azureusr/.cache/Homebrew/Logs/binutils/02.make:
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... (cached) yes
checking for working mmap... config.status: executing default-1 commands
config.status: executing default commands
yes
checking for working strncmp... yes
configure: updating cache ./config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating testsuite/Makefile
config.status: creating config.h
config.status: executing default commands
make[1]: Leaving directory `/tmp/binutils-20210901-9895-1p5b1ms/binutils-2.37'
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

Error: 'curl' must be installed and in your PATH!
Warning: Building openssl@1.1 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://curl.haxx.se/ca/cacert-2020-01-01.pem
Already downloaded: /home/azureusr/.cache/Homebrew/downloads/e2b36a2c425753a7b9d6a8eccb44b33cb7ed93cb91f96dafcf35fa18d8e0513a--cacert-2020-01-01.pem
==> Downloading https://cpan.metacpan.org/authors/id/L/LE/LEONT/Test-Harness-3.42.tar.gz
Already downloaded: /home/azureusr/.cache/Homebrew/downloads/4a5728e2132a470084886ad6e6278c6b23584e314ee60dcd57ea679202d5da4a--Test-Harness-3.42.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302175.tar.gz
Already downloaded: /home/azureusr/.cache/Homebrew/downloads/af880136321fd9982d8eb9dd29977fec40c093fb2fd48d6fff85de8d6bb9a5b5--Test-Simple-1.302175.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.48.tar.gz
Already downloaded: /home/azureusr/.cache/Homebrew/downloads/5c7e196d2435858f251597e37b63b670add424924b9e99d3079665b0628eed04--ExtUtils-MakeMaker-7.48.tar.gz
==> Downloading https://www.openssl.org/source/openssl-1.1.1l.tar.gz
Already downloaded: /home/azureusr/.cache/Homebrew/downloads/b6ccc5a2a602c2af3480bbcf1656bd9844595974ba60501871ac12504508e818--openssl-1.1.1l.tar.gz
==> perl Makefile.PL INSTALL_BASE=/home/azureusr/.linuxbrew/Cellar/openssl@1.1/1.1.1l/libexec
==> make PERL5LIB=/home/azureusr/.linuxbrew/Cellar/openssl@1.1/1.1.1l/libexec/lib/perl5 CC=gcc
==> make install
==> perl Makefile.PL INSTALL_BASE=/home/azureusr/.linuxbrew/Cellar/openssl@1.1/1.1.1l/libexec
==> make PERL5LIB=/home/azureusr/.linuxbrew/Cellar/openssl@1.1/1.1.1l/libexec/lib/perl5 CC=gcc
==> make install
==> perl Makefile.PL INSTALL_BASE=/home/azureusr/.linuxbrew/Cellar/openssl@1.1/1.1.1l/libexec
==> make PERL5LIB=/home/azureusr/.linuxbrew/Cellar/openssl@1.1/1.1.1l/libexec/lib/perl5 CC=gcc
==> make install
==> perl ./Configure --prefix=/home/azureusr/.linuxbrew/Cellar/openssl@1.1/1.1.1l --openssldir=/home/azureusr/.lin
==> make
==> make install MANDIR=/home/azureusr/.linuxbrew/Cellar/openssl@1.1/1.1.1l/share/man MANSUFFIX=ssl
==> make test
==> Downloading https://curl.haxx.se/ca/cacert-2020-01-01.pem
Already downloaded: /home/azureusr/.cache/Homebrew/downloads/e2b36a2c425753a7b9d6a8eccb44b33cb7ed93cb91f96dafcf35fa18d8e0513a--cacert-2020-01-01.pem
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /home/azureusr/.linuxbrew/etc/openssl@1.1/certs

and run
  /home/azureusr/.linuxbrew/opt/openssl@1.1/bin/c_rehash
==> Summary
🍺  /home/azureusr/.linuxbrew/Cellar/openssl@1.1/1.1.1l: 8,408 files, 24.1MB, built in 5 minutes 39 seconds
[azureusr@SLAZEXVCLDSSO01 .linuxbrew]$ which curl
/usr/local/bin/curl
[azureusr@SLAZEXVCLDSSO01 .linuxbrew]$ curl --version
curl 7.78.0 (x86_64-pc-linux-gnu) libcurl/7.78.0 OpenSSL/1.0.2k-fips zlib/1.2.7
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets

### What did you expect to happen?

have base64 installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
[azureusr@SLAZEXVCLDSSO01 .linuxbrew]$ export HOMEBREW_CURL=/usr/local/bin/curl
[azureusr@SLAZEXVCLDSSO01 .linuxbrew]$ brew install base64
Error: Please update your system curl.
Minimum required version: 7.41.0
Your curl version: 7.29.0
Your curl executable: /usr/bin/curl
Updating Homebrew...
Warning: Building binutils from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://ftp.gnu.org/gnu/binutils/binutils-2.37.tar.xz
:
:
:
config.status: creating config.h
config.status: executing default commands
make[1]: Leaving directory `/tmp/binutils-20210901-8857-1pzhb2g/binutils-2.37'
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

Error: 'curl' must be installed and in your PATH!
Warning: Building binutils from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://ftp.gnu.org/gnu/binutils/binutils-2.37.tar.xz
Already downloaded: /home/azureusr/.cache/Homebrew/downloads/ba350afe7ac6628be46366c9f06e233a3731512a08b8f208ee1f2b0197307c5a--binutils-2.37.tar.xz
Warning: Building gcc@5 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/azureusr/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/azureusr/.linuxbrew)
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-5.5.0/gcc-5.5.0.tar.xz
Already downloaded: /home/azureusr/.cache/Homebrew/downloads/62d8cc20018aa926380222fa7098af4384ca68c3ebdabe0806f2cd801ea0d075--gcc-5.5.0.tar.xz
==> Downloading https://ghcr.io/v2/linuxbrew/core/base64/manifests/1.5
Already downloaded: /home/azureusr/.cache/Homebrew/downloads/222214bda65b4ab4dc979e850b4f9636d74ccda59f20df2b85632a1eb7180906--base64-1.5.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/base64/blobs/sha256:9a9ce00338cde1af65b9283cc9893621c645bf32307e
Already downloaded: /home/azureusr/.cache/Homebrew/downloads/ef99a2766527e16338891da2cca200b409977625bb2ca6abbdce4167bf0d3b55--base64--1.5.x86_64_linux.bottle.tar.gz
==> Installing dependencies for base64: binutils and gcc@5
==> Installing base64 dependency: binutils
==> ./configure --enable-deterministic-archives --prefix=/home/azureusr/.linuxbrew/Cellar/binutils/2.37 --infodir=
==> make
Last 15 lines from /home/azureusr/.cache/Homebrew/Logs/binutils/02.make:
checking whether canonicalize_file_name must be declared... no
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... (cached) yes
checking for working mmap... yes
checking for working strncmp... yes
configure: updating cache ./config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating testsuite/Makefile
config.status: creating config.h
config.status: executing default commands
make[1]: Leaving directory `/tmp/binutils-20210901-28715-pwfbip/binutils-2.37'
make: *** [all] Error 2
```

**Comment by jhnworks** [comment]
Sorry, how does one overwrite brew from picking sys curl? User's .bash_profile set the PATH to have /usr/local/bin/curl which is ver 7.7 and have set a var HOMEBREW_CURL with the loc of the latest Curl.

**Comment by Bo98** [comment]
`HOMEBREW_CURL_PATH` is what you want. It however also requires setting `HOMEBREW_DEVELOPER` at the moment.

**Comment by Bo98** [comment]
Yeah, it's a bit experimental and I think it still tries to install Homebrew Curl. You should probably look into why building binutils fails - this requires digging deeper into the logs since there isn't enough information there. That discussion is better suited for https://github.com/Homebrew/discussions/discussions
