### ISSUE TITLE
[suggestion] change default value of $HOMEBREW_BAT_CONFIG_PATH

### ISSUE THREAD

**Issue by Freed-Wu** [Homebrew/brew#11974]
### Provide a detailed description of the proposed feature

```shell
$ bat --config-dir
/home/XXX/.config/bat
```

bat has changed its default config path.

However, according to <https://docs.brew.sh/Manpage#environment>
```
HOMEBREW_BAT_CONFIG_PATH
Use this as the bat configuration file.

Default: $HOME/.bat/config.
```

### What is the motivation for the feature?

/

### How will the feature be relevant to at least 90% of Homebrew users?

/

### What alternatives to the feature have been considered?

/

**Comment by carlocab** [comment]
Thanks for the report.

Homebrew doesn't actually set this default value; it uses `bat`'s default whenever you don't set `HOMEBREW_BAT_CONFIG_PATH`.

The only thing that needs changing is here:

https://github.com/Homebrew/brew/blob/fd46a173fef7a60bd7da5032f2fcde3c0ea0d1c2/Library/Homebrew/env_config.rb#L32-L34

Can you open a pull request for that?
