### ISSUE TITLE
brew extract on non-existent version ends up with error "Error: no implicit conversion of nil into Array"

### ISSUE THREAD

**Issue by freakalot** [Homebrew/brew#11978]
### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 3.2.10-69-gfaa56d2
ORIGIN: https://github.com/Homebrew/brew
HEAD: faa56d2118db315bba8415d1770c51f0c4a69adf
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1bfe8dfd7f728a0b191900721d3759d76ed5326d
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Applications/Xcode_12.4.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4 => /Applications/Xcode_12.4.app/Contents/Developer
```

### `brew doctor` output

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  boost@1.60
  gnu-getopt@1.1.6

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/ansible-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.5.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  telnet
  python@3.9

Warning: Some installed formulae are not readable:
  boost@1.60: undefined method `cxx11?' for #<BuildOptions:0x00007ffe94b93b70>
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I try to extract a previous version of cmake to my local tap. I did not fix all issues brew docotr found as I don't see how this could be related, also some outdated brews I still need for now to build up the tap with the old versions as homebrew doesn't have a better way to install old versions of a formula anymore.

### What happened (include all command output)?

brew extract --version 1.18.4 cmake homebrew/lsyzrh
==> Searching repository history
Error: no implicit conversion of nil into Array
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:226:in `concat'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:226:in `block in needs'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:225:in `each'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:225:in `needs'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2955:in `block in needs'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2955:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2955:in `needs'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb:23:in `<class:Cmake>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb:1:in `block in load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:78:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:78:in `block in load_formula'
/usr/local/Homebrew/Library/Homebrew/ignorable.rb:44:in `hook_raise'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:385:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:180:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:500:in `from_contents'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:229:in `block in formula_at_revision'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:38:in `with_monkey_patch'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:229:in `formula_at_revision'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:158:in `block in extract'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:138:in `loop'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:138:in `extract'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'

### What did you expect to happen?

I expect the version to be extract an being available in my local tap, but it only throws this error above

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap --force-auto-update homebrew/lsyzrh ssh://git@.......
brew extract --version 1.18.4 cmake homebrew/lsyzrh
```

**Comment by carlocab** [comment]
Are you sure you want version 1.18.4? As far as I can tell, the earliest version packaged by Homebrew is 2.6.3. (Trying to `brew extract` that is probably not going to work too well either.)

**Comment by freakalot** [comment]
omg...thx for pointing this out....I guess it was already too late yesterday and I didn't see the obvious problem. I wanted to extract 3.18.4...but the blurry error message didn't gave me the right hint.

**Comment by carlocab** [comment]
Let's see if we can get that error message fixed.
