### ISSUE TITLE
Change mysql db location when installed with homebrew using Big Sur and external hard drive

### ISSUE THREAD

**Issue by jamie-selesti** [Homebrew/brew#11976]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: ab2118a402a44451b1d7559167b6956dc47cc19a
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a9432939d7dc6c8c792dd5360e3e0aa096584a6c
Core tap last commit: 4 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: subl
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
```

### `brew doctor` output

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.2

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Previously I had `/usr/local/var/mysql` symlinked to `/Volumes/External/mysql` meaning all my databases were stored on the external hard drive.

I have had to reformat my machine and upgrade to BigSur. If I try to set up the symlink as before I now get the following when I try to start MySQL

    brew services start mysql
    Bootstrap failed: 5: Input/output error
    Error: Failure while executing; `/bin/launchctl bootstrap gui/502 /Users/jamie/Library/LaunchAgents/homebrew.mxcl.mysql.plist` exited with 5. 

If I try to also change the `-datadir` in 

     /usr/local/Cellar/mysql/8.0.26/homebrew.mxcl.mysql.plist

to be 

    <string>--datadir=/Volumes/External/mysql</string>

I get the same error

    brew services start mysql
    Bootstrap failed: 5: Input/output error
    Error: Failure while executing; `/bin/launchctl bootstrap gui/502 /Users/jamie/Library/LaunchAgents/homebrew.mxcl.mysql.plist` exited with 5.

I have tried 

    launchctl unload /Users/jamie/Library/LaunchAgents/homebrew.mxcl.mysql.plist
    launchctl unload /Users/jamie/Library/LaunchAgents/homebrew.mxcl.mysql.plist

but that didn't work either. It's like it doesn't have the correct permissions.

Looking at the privacy settings you can see httpd which is also installed by brew is allowed to see "Removable volumes".

![Screenshot 2021-09-05 at 10 17 21](https://user-images.githubusercontent.com/1398649/132122104-a4ad366b-0398-4eef-adf5-a9f5e81e4d9e.png)

I can't add MySQL as the + symbol is grey out even though I have unlocked the panel

The external hard drive is located at `/Volumes/External/` and is APFS (Encrypted) volume.

### What happened (include all command output)?

    Bootstrap failed: 5: Input/output error
    Error: Failure while executing; `/bin/launchctl bootstrap gui/502 /Users/jamie/Library/LaunchAgents/homebrew.mxcl.mysql.plist` exited with 5.

### What did you expect to happen?

MySQL to to start

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above
```

**Comment by MikeMcQuaid** [comment]
Sorry, we don't support using Homebrew in this way so it's not a bug. You may have more luck asking for help in our discussions forum.
