### ISSUE TITLE
TTY not properly reset after `brew install` 

### ISSUE THREAD

**Issue by sullivan-sean** [Homebrew/brew#11984]
### `brew config` output

```shell
% brew config
HOMEBREW_VERSION: 3.2.10-78-gf0dbd8d
ORIGIN: https://github.com/Homebrew/brew
HEAD: f0dbd8d9a5e1db3de1fb495039e751a9a816b5ee
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 68e4bdd5e77e898f3884376f09e5a9a8dbc3b20a
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-arm64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
Rosetta 2: false
```

### `brew doctor` output

```shell
% brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install any package (e.g. `brew install tree-sitter`)

### What happened (include all command output)?

TTY flags are modified by `brew install` and not properly reset. In particular note differences in the output of `stty -a` before and after running `brew install` in a fresh terminal:

```
% stty -a
speed 38400 baud; 49 rows; 99 columns;
lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: -istrip icrnl -inlcr -igncr ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
% brew install tree-sitter
==> Downloading https://ghcr.io/v2/homebrew/core/tree-sitter/manifests/0.20.0-1
Already downloaded: /Users/seansullivan/Library/Caches/Homebrew/downloads/caf4df26418c0c4664fed59578fe8257f590731241bbbc342433585a2bab3694--tree-sitter-0.20.0-1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/tree-sitter/blobs/sha256:cbf44029649cea921fe333454
Already downloaded: /Users/seansullivan/Library/Caches/Homebrew/downloads/e30e408fcc1bd5715be4a06aefd102e2e64d2209249d2fec6f41c7d3d115b0c1--tree-sitter--0.20.0.arm64_big_sur.bottle.1.tar.gz
==> Pouring tree-sitter--0.20.0.arm64_big_sur.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/tree-sitter/0.20.0: 18 files, 12.6MB
% stty -a

speed 38400 baud; 49 rows; 99 columns;
lflags: icanon isig iexten echo echoe echok echoke echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: istrip icrnl -inlcr -igncr ixon -ixoff ixany -imaxbel iutf8
	ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

The `echonl` flag is OFF (`-echonl`) in the `stty -a` output before hand and ON afterwards, which has the side effect of an extra newline before the output of each command in the given TTY after running `brew install`. 

It seems like this issue is related to the `io/console` Ruby gem, which was not used by Homebrew until https://github.com/Homebrew/brew/pull/11914 introduced in `3.2.10` -- the behavior above did not occur prior to this update and by adding logging statement in a local clone of the brew repo, it seems like the line that sets the undesired `echonl` property is a call to `$stdin.cooked!` [here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/sandbox.rb#L128).

Further, if I create and run a very simple ruby file:
```ruby
require "io/console"

$stdout.puts `stty -a | grep echonl`
$stdin.raw! if $stdin.tty?
$stdin.cooked! if $stdin.tty?
$stdout.puts `stty -a | grep echonl`
```

I get the same undesired behavior. So while this is not strictly a homebrew issue, I wanted to flag this to the homebrew maintainers as a possible regression in 3.2.10 for some users. Not sure that this is reproducible everywhere: I was able to reproduce this behavior on my Big Sur and Catalina machines and was NOT able to reproduce on linux.

### What did you expect to happen?

The output of `stty -a` should be the same before and after `brew install {package}`. I expect this command to fully restore the state of my terminal, in particular it should not modify the `echonl` or `istrip` flags.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install {package}
```

**Comment by sullivan-sean** [comment]
I was able to fix this issue (see https://github.com/sullivan-sean/brew/commit/c88f4c064556b867ec1a3460ab9f8820453cef18) on my machine by using the `io.raw` method from `io/console` instead of `io.raw!` 

As mentioned in the documentation for [raw!](https://docs.ruby-lang.org/en/2.2.0/IO.html#method-i-raw-21) if the terminal needs to be returned to the original state, `io.raw` should be used. I imagine the current approach might work in some cases but using `io.raw` will properly reset the tty in all cases and is probably preferable. 

Happy to make a PR for this if things make sense and the above diff looks okay.

**Comment by carlocab** [comment]
A PR would be good so your changes could be reviewed more carefully. I think you need to do `brew style --fix` before opening it, though.

**Comment by MikeMcQuaid** [comment]
CC @Bo98 who has been working on this recently.

**Comment by Bo98** [comment]
> [sullivan-sean@c88f4c0](https://github.com/sullivan-sean/brew/commit/c88f4c064556b867ec1a3460ab9f8820453cef18)

Change looks good to me.
