### ISSUE TITLE
Linux on Arm

### ISSUE THREAD

**Issue by mattpackwood** [Homebrew/brew#11995]
### Provide a detailed description of the proposed feature

Any chance of supporting Linux on M1 / ARM?

### What is the motivation for the feature?

Moving from Intel to M1

### How will the feature be relevant to at least 90% of Homebrew users?

As more of us move to M1 those running VMs will need this more and more as part of our keychain.

### What alternatives to the feature have been considered?

None

**Comment by MikeMcQuaid** [comment]
No plans for this, sorry. If/when GitHub Actions supports this: we'll consider it.

**Comment by mattpackwood** [comment]
No worries, I did not think about Actions support...
