### ISSUE TITLE
kdenlive?

### ISSUE THREAD

**Issue by chovyprognos** [Homebrew/brew#12001]
### Provide a detailed description of the proposed feature

Can we get kdenlive added? Apparently it was once availalbe in macports for MacOS

Surprised nobody has added this yet.

### What is the motivation for the feature?

good video edditor

### How will the feature be relevant to at least 90% of Homebrew users?

foss video editor

### What alternatives to the feature have been considered?

shot cup open shot

**Comment by carlocab** [comment]
Please open a pull request at https://github.com/Homebrew/homebrew-core. We're happy to help you finish one off if you get stuck somewhere along the way.

This should help you get started: https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by ran-dall** [comment]
> Can we get kdenlive added? Apparently it was once availalbe in macports for MacOS
>
> Surprised nobody has added this yet.

@chovyprognos FWIW, Kdenlive doesn't have a redistributable binary availbile for macOS, and building from source can be quite challenging. This is one of the main reasons the Macports version somewhat got adandoned.
