### ISSUE TITLE
Brew Install Stuck on HEAD 

### ISSUE THREAD

**Issue by gittyhubber** [Homebrew/brew#12023]
### `brew config` output

```shell
HEAD is now at 1e8e57c19 Merge pull request #12021 from Bo98/triage-concurrency
```

### `brew doctor` output

```shell
HEAD is now at 1e8e57c19 Merge pull request #12021 from Bo98/triage-concurrency
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install brew for mac os x86 operating system

### What happened (include all command output)?

does basic setup with files and permissions then this pull error comes up HEAD is now at 1e8e57c19 Merge pull request #12021 from Bo98/triage-concurrency

### What did you expect to happen?

install homebrew??

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
doesn't work because brew hasn't been successfully installed?
```

**Comment by MikeMcQuaid** [comment]
This is specific to your machine. Please discuss in Homebrew/discussions.
