### ISSUE TITLE
bump-cask-pr to allow 'fake' user agent

### ISSUE THREAD

**Issue by karbassi** [Homebrew/brew#12038]
### Provide a detailed description of the proposed feature

When using `bump-cask-pr` to update a cask, the user agent is hard-coded (see ruby code). It would be nice if the `bump-cask-pr` code used the cask's settings.

For example, when bumping [typinator](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/typinator.rb), the formula file notes a `fake` user agent.

https://github.com/Homebrew/homebrew-cask/blob/2482cb2a58efd514764f2b1f9d760cd1a2ab2038/Casks/typinator.rb#L5-L6

However, when using `bump-cask-pr`, it fails to download since the curl command uses the Homebrew user agent.

```bash
/usr/bin/curl --disable --cookie-jar /dev/null --globoff --show-error --user-agent Homebrew/3.2.11-103-gbf95782\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.5.2\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/REDACTED/Library/Caches/Homebrew/downloads/d7202ddcf6fede6e47099292992ad581da04f00947ce363f627f759ae47210a1--Typinator89-Install.dmg.incomplete https://www.ergonis.com/downloads/products/typinator/Typinator89-Install.dmg
```

```bash
curl: (22) The requested URL returned error: 403 Forbidden
```

### What is the motivation for the feature?

Allowing for cask updates.

### How will the feature be relevant to at least 90% of Homebrew users?

This will help more people who want to help update casks.

### What alternatives to the feature have been considered?

Manually updating the cask and submitting the PR.

**Comment by EricFromCanada** [comment]
This doesn't appear to occur on the latest HEAD of Homebrew:
```
$ brew bump-cask-pr --version=8.9 --dry-run typinator
==> Downloading https://www.ergonis.com/downloads/products/typinator/Typinator89-Install.dmg
######################################################################## 100.0%
==> replace /version\s+["']8\.8["']/m with "version \"8.9\""
==> replace /sha256\s+["']4453cf969679d01dde0e10dff4072bbad576c85cc58b818e0bd0592c5d3f3025["']/m with "sha256 \"7c223e1624ad89a0a203b7750f7276ee1a7c1038ccceafc68ce1dcaaf54518b2\""
==> brew audit --cask typinator.rb
==> brew style --fix typinator.rb
==> try to fork repository with GitHub API
==> git add /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/typinator.rb
==> git checkout --no-track -b bump-typinator-8.9 origin/master
==> git commit --no-edit --verbose --message='Update typinator from 8.8 to 8.9' -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/typinator.rb
==> git push --set-upstream FORK_URL bump-typinator-8.9:bump-typinator-8.9
==> git checkout --quiet -
==> create pull request with GitHub API (base branch: master)
```
