### ISSUE TITLE
depends_on with a dependency that is a cask errors as unsupported special dependency

### ISSUE THREAD

**Issue by leighmcculloch** [Homebrew/brew#12041]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 84f4fbf3cf5e83d33de0b28b2658fcb50aaa761e
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 00889339ce46b6ca17575145a908b0dc2928429a
Core tap last commit: 48 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install a formula that has a `depends_on: :multipass` where multipass is a cask.
```
brew install 4d63/dockerhost/dockerhost
```

The formula is:
```ruby
class Dockerhost < Formula
  desc "Setup a docker host on macOS in a lightweight Ubuntu vm."
  homepage "https://github.com/leighmcculloch/dockerhost"
  bottle :unneeded

  depends_on :multipass
  depends_on "docker"
  depends_on "jq"

  version "1.0.5"
  sha256 "8aad86aa7ca4b4fa599204fe51c7c3be23389c2b36a3d18df28b8377b5234228"

  url "https://raw.githubusercontent.com/leighmcculloch/dockerhost/v#{version}/dockerhost"

  def install
    bin.install "dockerhost"
  end

  test do
    system "#{bin}/dockerhost"
  end
end
```

### What happened (include all command output)?

Brew complains that the `:multipass` is an unsupported special dependency.
```
% brew install 4d63/dockerhost/dockerhost                       
==> Tapping 4d63/dockerhost
Cloning into '/usr/local/Homebrew/Library/Taps/4d63/homebrew-dockerhost'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 46 (delta 18), reused 41 (delta 13), pack-reused 0
Receiving objects: 100% (46/46), 4.86 KiB | 4.86 MiB/s, done.
Resolving deltas: 100% (18/18), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/4d63/homebrew-dockerhost/Formula/dockerhost.rb
dockerhost: Unsupported special dependency :multipass
Error: Cannot tap 4d63/dockerhost: invalid syntax in tap!
```

### What did you expect to happen?

I expected the `multipass` cask to be installed.

According to the Brew Formula Cookbook specifying a symbol (`:multipass`) instead of a string (`"multipass"`) is appropriate if the dependency is a cask.

https://github.com/Homebrew/brew/blob/8db3289f15f08eea5406653141e11a911a2cd24d/docs/Formula-Cookbook.md#L141-L156

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install 4d63/dockerhost/dockerhost
```

**Comment by dawidd6** [comment]
`:multipass` isn't a valid Requirement. A formula cannot simply depend on a cask. Refactor your formula to be a cask and then you can depend on other casks + formulae.

List of available Requirements in code:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/requirements.rb

**Comment by carlocab** [comment]
To elaborate a bit on the above:

`brew` parses `Symbol` arguments to `depends_on` as a `Requirement`, where a `Requirement` specifies that the formula requires "one or more formulae, casks or other system-wide installed software (e.g. Xcode)".

Homebrew has some pre-specified `Requirement`s (see link above), but you can also create your own. In particular, Homebrew does not provide `Requirement`s for arbitrary casks.

**Comment by leighmcculloch** [comment]
Got it, thanks for explaining how it works. Changing my formula to a cask worked. Thank you.

> you simply misunderstood the docs

👍🏻 I think the docs could be improved to clarify that when it says that symbols can be used for casks, it means a limited set of casks and not all or any casks.
