### ISSUE TITLE
brew test-bot error "on_macos cannot include url"

### ISSUE THREAD

**Issue by huahaiy** [Homebrew/brew#12040]
### `brew config` output

```shell
❯ brew config
HOMEBREW_VERSION: 3.2.11-103-gbf95782
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: bf95782ee2c9a4622c1110e8d3adf768fc4fd897
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5ccc7bbbab9409b283c11c48faf5149c52123589
Core tap last commit: 20 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.mYw5XPZqZF/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0.5 build 1205
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.0.0.32.27
Xcode: 12.5.1
XQuartz: 2.7.11 => /opt/X11
```

### `brew doctor` output

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.5.


Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.5.


Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  python@2
  suite-sparse421
  dirmngr
  gmp@4
  gpg-agent
  qt@5.7
  gitzero
  isl@0.12

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  bats
  ilmbase

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your user.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ctags
  python@2
  pyqt@5
  imath
  suite-sparse421
  openexr
  libsigc++@2
  qt@5.7
  unbound
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:274:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:209:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:181:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:181:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:340:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:414:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:480:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:453:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:778:in `block in check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:777:in `check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I have a formula, github test-bot checking its syntax wrongly produces an error, and people in discussions suggest me to file a bug report here. See https://github.com/Homebrew/discussions/discussions/2119#discussioncomment-1309353

### What happened (include all command output)?

brew test-bot --only-tap-syntax
  shell: /usr/bin/bash -e {0}
==> Using Homebrew/homebrew-test-bot 239af84 (Merge pull request #660 from carlocab/git)
==> Using Homebrew/brew 3.2.11-103-gbf95782ee (Merge pull request #12019 from valrus/services-plist-add-process-type)
==> Using Homebrew/linuxbrew-core a55e1a81ac4 (wangle: update 2021.09.06.00 bottle.)
==> Testing huahaiy/homebrew-brew 26a8f99 (update):

==> Running TapSyntax#run!
==> brew readall --aliases huahaiy/brew
==> brew style huahaiy/brew
==> FAILED
Formula/datalevin.rb:10:5: C: on_macos cannot include url. Only depends_on, patch, resource, deprecate!, disable!, conflicts_with, keg_only, and ignore_missing_libraries are allowed.
    url "https://github.com/juji-io/datalevin/releases/download/0.5.8/dtlv-0.5.8-macos-latest-amd64.zip"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Formula/datalevin.rb:11:5: C: on_macos cannot include sha256. Only depends_on, patch, resource, deprecate!, disable!, conflicts_with, keg_only, and ignore_missing_libraries are allowed.
    sha256 "d051099a857083ec7a3fbfa11bf8262c0537d6d96acd12bcdadfecc21ef9b369"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Formula/datalevin.rb:15:5: C: on_linux cannot include url. Only depends_on, patch, resource, deprecate!, disable!, conflicts_with, keg_only, and ignore_missing_libraries are allowed.
    url "https://github.com/juji-io/datalevin/releases/download/0.5.8/dtlv-0.5.8-ubuntu-latest-amd64.zip"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Formula/datalevin.rb:16:5: C: on_linux cannot include sha256. Only depends_on, patch, resource, deprecate!, disable!, conflicts_with, keg_only, and ignore_missing_libraries are allowed.
    sha256 "aa966a9906acdc0e80768b5744f093978f44176fb3c4d55ff9e0b9cea58ef638"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 4 offenses detected
Error: `on_macos` cannot include `url`. Only `depends_on`, `patch`, `resource`, `deprecate!`, `disable!`, `conflicts_with`, `keg_only`, and `ignore_missing_libraries` are allowed.
Error: `on_macos` cannot include `sha256`. Only `depends_on`, `patch`, `resource`, `deprecate!`, `disable!`, `conflicts_with`, `keg_only`, and `ignore_missing_libraries` are allowed.
Error: `on_linux` cannot include `url`. Only `depends_on`, `patch`, `resource`, `deprecate!`, `disable!`, `conflicts_with`, `keg_only`, and `ignore_missing_libraries` are allowed.
Error: `on_linux` cannot include `sha256`. Only `depends_on`, `patch`, `resource`, `deprecate!`, `disable!`, `conflicts_with`, `keg_only`, and `ignore_missing_libraries` are allowed.

==> brew audit --tap=huahaiy/brew --except=version
Error: 1 failed step!
brew style huahaiy/brew
Error: Process completed with exit code 1.

### What did you expect to happen?

No error.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew style huahaiy/brew
Inspecting 1 file
C

Offenses:

/usr/local/Homebrew/Library/Taps/huahaiy/homebrew-brew/Formula/datalevin.rb:10:5: C: on_linux cannot include url. Only depends_on, patch, resource, deprecate!, disable!, conflicts_with, keg_only, and ignore_missing_libraries are allowed.
    url "https://github.com/juji-io/datalevin/releases/download/0.5.8/dtlv-0.5.8-ubuntu-latest-amd64.zip"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/usr/local/Homebrew/Library/Taps/huahaiy/homebrew-brew/Formula/datalevin.rb:11:5: C: on_linux cannot include sha256. Only depends_on, patch, resource, deprecate!, disable!, conflicts_with, keg_only, and ignore_missing_libraries are allowed.
    sha256 "aa966a9906acdc0e80768b5744f093978f44176fb3c4d55ff9e0b9cea58ef638"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected
```

**Comment by Rylan12** [comment]
@huahaiy was this working before about a week ago)?

If so, this looks like a compatibility issue introduced by https://github.com/Homebrew/brew/pull/11955 (CC @MikeMcQuaid and @carlocab)

It's possible, though, that this was always the intended behavior. If so, hopefully, someone else can advise you on the best way to move forward. As far as I know, there's no other way to support separate URLs for formulae (and we don't have any formulae that do this that I know of)

**Comment by huahaiy** [comment]
Yes, It was working util a few days ago. This use is very common for GraalVM compiled native image, see for another example, babashka.

https://github.com/borkdude/homebrew-brew/blob/900874b6f5e3a6439dde91367d59e97fe2b0f9e4/babashka.template#L7

For now, I disabled the syntax check on the automatic build, so the formula is available for people. But it is desirable to fix this, as I am sure that they are other people use it the same way, since I originally copied it from others.
