### ISSUE TITLE
Alias --prune to --purge

### ISSUE THREAD

**Issue by snobu** [Homebrew/brew#12073]
### Provide a detailed description of the proposed feature

May we please have a `--purge` alias for `--prune`? I always and i mean ALWAYS end up typing the former first. Some open source tools use --purge, some --prune, it's never consistent. This would save a few seconds a day times the amount of people who type the wrong word in just like me.

If it's just me, then i'm sure i can live with it. If it's also you out there, comment like and subscribe :)

### What is the motivation for the feature?

I always type the wrong thing in.

### How will the feature be relevant to at least 90% of Homebrew users?

I can only speculate there are more users out there who type the wrong thing on the 1st try.

### What alternatives to the feature have been considered?

Stopped drinking for a while. Still typed the wrong thing in.

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this!
