### ISSUE TITLE
zsh: command not found: brew

### ISSUE THREAD

**Issue by bibhas2** [Homebrew/brew#12091]
### `brew config` output

```shell
None.
```

### `brew doctor` output

```shell
None.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

System: macOS. Bug Sur. 11.5.2. Chip: Apple M1.

Installed homebrew. 

Ran command:

```
brew install gpg
```

### What happened (include all command output)?

Output shows:

```
zsh: command not found: brew
```

### What did you expect to happen?

brew command should run and function.

### Step-by-step reproduction instructions (by running `brew` commands)

Install homebrew using the command provided on web site.

```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

Opened a new Terminal command prompt.

Ran this command.

```
brew install gpg
```

Output shows:

```
zsh: command not found: brew
```

**Comment by carlocab** [comment]
Please follow the instructions about adding `brew` to your `PATH` shown to you by the installer.

If you're still having trouble, you can get help at https://github.com/Homebrew/discussions/discussions.

**Comment by bibhas2** [comment]
This is bad ergonomics. People expect to run a piece of software after installing it. The installer itself puts out thousands of lines of text. You should not expect people to read through this all.

I read the [full installation web page](https://docs.brew.sh/Installation) and saw no mention of adjusting PATH. 

Anyway, my 2c. I am hoping to improve the software.

**Comment by carlocab** [comment]
The instructions are shown to you at the very end. There is no need to read more than ~5 lines of text.

`brew` does tend to produce a lot of output, but it also goes out of its way to make sure you see the most important things at the very end.
