### ISSUE TITLE
Warning after migrating from M1 Mac back to Intel based Mac

### ISSUE THREAD

**Issue by peterrakolcza** [Homebrew/brew#12107]
### `brew config` output

```shell
HOMEBREW_VERSION: >=2.5.0 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: (none)
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: (none)
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: N/A
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 12.5.0.22.11
Xcode: 12.5.1
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Git could not be found in your PATH.
Homebrew uses Git for several internal functions, and some formulae use Git
checkouts instead of stable tarballs. You may want to install Git:
  brew install git

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to use Homebrew as intended.

### What happened (include all command output)?

I have migrated from a M1 MacBook Air back to a MacBook Pro 13

### What did you expect to happen?

I want to use Homebrew as intended.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update:
Error: Cannot install on Intel processor in ARM default prefix (/opt/homebrew)!
Error: 'git' must be installed and in your PATH!
```

**Comment by Bo98** [comment]
Your Homebrew installation, including all formulae installed, will contain arm64 binaries so you can't just copy the installation as nothing will run.

You'll need to reinstall Homebrew and all formulae so it can install x86_64 binaries instead. This lies in a separate prefix `/usr/local` so `/opt/homebrew` will stay as it is until you delete it.

Tools like `brew bundle dump` can help, though you might need to fix your system Git (`/usr/bin/git`) first so that brew can at least be partially usable.
