### ISSUE TITLE
Opening a new Terminal session (Ubuntu) removes Homebrew from PATH

### ISSUE THREAD

**Issue by IceColdTray** [Homebrew/brew#12128]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 109f24fd601177dea4a754b43efe684903db2a83
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 23995b2435bff7afd1c20fdd45d3b564e80af0bc
Core tap last commit: 3 days ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.11.0-36-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.3 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: 5.5.0_7
xorg: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

trying to execute `brew help` in a new terminal session

### What happened (include all command output)?

Command 'brew' not found, did you mean:

  command 'brec' from deb bplay (0.991-10build1)
  command 'qbrew' from deb qbrew (0.4.1-8build1)

Try: apt install <deb name>

### What did you expect to happen?

Brew installing succesfully and commands being functional.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/greeeen/.profile
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
brew (opening a new terminal session)
```

**Comment by IceColdTray** [comment]
`echo $PATH` output before:
`/home/greeeen/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
`echo $PATH` output after:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`

**Comment by MikeMcQuaid** [comment]
This is specific to your machine. Please open a discussion instead.
