### ISSUE TITLE
Suggestion: Flag for getting all source code for all installed formuals in an dedicated dir

### ISSUE THREAD

**Issue by janderssonse** [Homebrew/brew#12163]
### Provide a detailed description of the proposed feature

We are preparing a docker image for distribution containing a Brew tap (to own tap) and installation. To easily keep up with license compliance, we would like to be able to easily distribute the sources of all the forumulas brew installs, by a single commando maybe something like "with-source-code" or something, fetching all the downloaded formulas source code to a special source dir (with patches etc). As I understood, today this is not easily achieved automatically (if i'm wrong here, sorry), although the source code for the formulas might be in the cache dir by default (read that it still does not is 100% regarding patches etc in formulas).

### What is the motivation for the feature?

To be able to distribute a brew installation in a docker container, and at the same time easily fullfil license compliance request regarding source code.

### How will the feature be relevant to at least 90% of Homebrew users?

They will be able to easily full license compliance requests without manual work. They can easily use brew in container images and such, knowing that the layer which installs brew formulas is perfectly fine for license compliance requests.

### What alternatives to the feature have been considered?

Looking around I understand this can partially be achvied by lookin in an eventual cache. and manually, but it would much better if there was an easy way to achive this out of the box.

**Comment by carlocab** [comment]
How does including the source help with license compliance? Most licenses just require a copy of the license to be distributed with the software even when repackaged in binary form. This is something we do already.

See

https://github.com/Homebrew/brew/blob/9b42a104ee51fd2c45f91a72fc18bbad73b1aa5a/Library/Homebrew/build.rb#L175-L177
https://github.com/Homebrew/brew/blob/58e34293554a827e717a7383940c2e57c2d0b360/Library/Homebrew/extend/pathname.rb#L418-L433

**Comment by janderssonse** [comment]
Great, and that should cover most of the licenses except for copyleft styles like GPLx where distribution also means that the distributor also must provide source code on request. In other words. I.e if one distributes a docker image, where source code must be provided upon request. There has be a lot written about this . for example https://www.linuxfoundation.org/wp-content/uploads/Docker-Containers-for-Legal-Professionals-Whitepaper_042420.pdf and some solutions. Regarding solutions Fedora/Red Hat has solved it with serving a source image available to their base images .https://opensource.com/article/20/7/compliance-containers . For Debian and Alpine there is the OASDL image. https://www.osadl.org/OSADL-Docker-Base-Image.osadl-docker-base-image.0.html. Having an option like that would make it far easier for example use brew in an official docker image and be assured that upon compliance requests it would be supereasy to handle those requests.

**Comment by janderssonse** [comment]
I know these things are not that fun, but It is for my orga a real life use-case, and if we have it I guess other have it.

**Comment by carlocab** [comment]
It doesn't do everything that you want, but you can use `brew unpack`:

```
Usage: brew unpack [options] formula [...]

Unpack the source files for formula into subdirectories of the current working
directory.

      --destdir                    Create subdirectories in the directory
                                   named by path instead.
      --patch                      Patches for formula will be applied to
                                   the unpacked source.
  -g, --git                        Initialise a Git repository in the unpacked
                                   source. This is useful for creating patches
                                   for the software.
  -f, --force                      Overwrite the destination directory if it
                                   already exists.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.
```

**Comment by janderssonse** [comment]
That I missed! Should be a good enough, with the --patch option, one then only has to step through the formulas I guess and pick them out.. Will try.  Thanks, I think it is good enough for the use case.
