### ISSUE TITLE
`brew install wget` resulted in updating 8 billion 300 thousand and 35 trillion packages on my system

### ISSUE THREAD

**Issue by josh-m-sharpe** [Homebrew/brew#12169]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e6919b73444e9f9e02ad81d8afc4bbd97533567
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 918badf7f68bbe68f03e2ae1f977aa71f9aeb801
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.0.0 build 1300
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 12.5.0.22.11
Xcode: 13.0
```

### `brew doctor` output

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 13.0.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  imath
  qt
  openexr

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install `wget` ... to download a file?

### What happened (include all command output)?

home-brew updated literally everything.  mysql, ruby, python, sensible, like... everything on my system.  it's still going.

it's installed/updated so much stuff at this point the original list has scrolled off the buffer.

finally it ended - it must've updated everything.  it updated memcache, Postgres, map nginx imagemagick, etc etc etc -- all stuff I've previously installed but by no means wanted or needed updated.

I bet absolutely nothing works now.

### What did you expect to happen?

just install wget and maybe, I dunno, 3 dependencies

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. don't brew install anything for a few months
2. `brew install wget`
```

**Comment by carlocab** [comment]
`brew install foo` will also upgrade everything connected to `foo` via its dependency graph.

`wget` depends on `openssl@1.1`. Lots of packages are connected to `openssl@1.1`, so those are upgraded too.

**Comment by MikeMcQuaid** [comment]
@josh-m-sharpe Please reread our Code of Conduct and adjust your tone accordingly in future issues.
