### ISSUE TITLE
CLT download URL requires update

### ISSUE THREAD

**Issue by eranguy** [Homebrew/brew#12174]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e6919b73444e9f9e02ad81d8afc4bbd97533567
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b3db614229214629fc5bf9554d37a734da8c88a2
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.2RZPyXHmLL/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/gvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 12.0.0.32.28
Xcode: 13.0
XQuartz: 2.7.11 => /opt/X11
```

### `brew doctor` output

```shell
Warning: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 13.0.


Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 13.0.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Execute `brew doctor`.

### What happened (include all command output)?

CLT download URL in output isn't valid - [https://developer.apple.com/download/more](https://developer.apple.com/download/more) was changed/moved to [https://developer.apple.com/download/all](https://developer.apple.com/download/all).

     

- [https://developer.apple.com/download/more](https://developer.apple.com/download/more):

![image](https://user-images.githubusercontent.com/30695162/135863150-22315cd2-5b3e-43b8-86ca-2858e9473ff2.png)

- [https://developer.apple.com/download/all](https://developer.apple.com/download) - showing updated URL:

![image](https://user-images.githubusercontent.com/30695162/135863878-36cc3bab-313a-4a95-ad53-8796de0bdf94.png)

### What did you expect to happen?

Get vaild URL from output.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew doctor
```

**Comment by carlocab** [comment]
Thanks for the report. Should be fixed by #12175.
