### ISSUE TITLE
Error: pkg-config: Invalid preset `pour_bottle?` condition

### ISSUE THREAD

**Issue by mascotli** [Homebrew/brew#12213]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.9
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: 76cfe88b7628a8010bf98115627f6aced4ff8870
Last commit: 5 months ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: e2cb54a23669efc58dacd3728b3b3aaa5a30cc96
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.0.0 build 1300
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.ustc.edu.cn/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.ustc.edu.cn/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

cd "$(brew --repo)"
git remote set-url origin https://github.com/Homebrew/brew.git

### What happened (include all command output)?

==> Upgrading 5 outdated packages:
nghttp2 1.45.1 -> 1.45.1_1
pcre2 10.37_1 -> 10.38
kubernetes-cli 1.22.1 -> 1.22.2
six 1.16.0_1 -> 1.16.0_2
git 2.33.0 -> 2.33.0_1
==> Upgrading nghttp2 1.45.1 -> 1.45.1_1 
Error: pkg-config: Invalid preset `pour_bottle?` condition

### What did you expect to happen?

brew upgrade success

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew update

2. brew upgrade
```

**Comment by MikeMcQuaid** [comment]
> * [x]  I have resolved all warnings from `brew doctor` and that did not fix my problem.



> ```shell
> Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
> The current git origin is:
>   https://mirrors.ustc.edu.cn/brew.git
> 
> With a non-standard origin, Homebrew won't update properly.
> You can solve this by setting the origin remote:
>   git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew
> ```

You did not. Your version of Homebrew/brew is very old.
