### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by filipre** [Homebrew/brew#1223]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
```
→ brew doctor
Error: Operation not permitted - /tmp/doctor20161004-5492-gm9js7
```
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Hi!

Somehow I can't install packages anymore. Every `brew install` fails with `Error: Operation not permitted - /tmp/github_api_headers20161004-5754-me67iw` and I am kinda clueless why this happens:

```
→ brew install wget
==> Installing dependencies for wget: openssl
==> Installing wget dependency: openssl
Error: Operation not permitted - /tmp/github_api_headers20161004-5754-me67iw
```

I guess it has to do with some permission but the `sudo chown ...` command did not help.

Here is my `brew config`:
```
→ brew config
HOMEBREW_VERSION: >1.0.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: cafe1497808ef1ddb002061665ad606aa2340d10
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5f95c08faa990b7634a72689fb0780ae66c5f354
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/rene/.rvm/rubies/ruby-2.0.0-p648/bin/ruby
Java: 1.8.0_66, 1.7.0_79, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A
MacPorts/Fink: /opt/local/bin/port
```

I also tried to uninstall / reinstall brew using [this](http://superuser.com/a/203740) guide but this did not solve my problem as well. The script told me to delete some folders by hand (like `/usr/local`) but those folders contain other programs I need as well.

I found issue #253 which used to be an error I had before. However, those steps did not help me as well. 

Do you have any ideas what I could try next?

Greetings
René

**Comment by filipre** [comment]
Wow. I guess the "System Integrity Protection" caused this, even though brew used to work with this turned on. Anyway, I turned it [off](http://stackoverflow.com/a/32661637) and I can install stuff again. There might be even an issue about this in legacy-homebrew where I did not search for solutions.

**Comment by MikeMcQuaid** [comment]
> I guess the "System Integrity Protection" caused this, even though brew used to work with this turned on.

I really strongly recommend not turning it off. It's a major security feature used by both macOS and Homebrew itself. If you would consider turning it back on and running `brew doctor --debug --verbose` we may be able to help.

**Comment by filipre** [comment]
I see, okay I turned it back on to find the *real* problem. However the problem changed a bit now: It seems like I can install packages again (I installed `awscli`) but `brew doctor` still fails. I also tried to run `sudo chown -R $(whoami) $(brew --prefix)` again but this did not change anything. Is there something wrong with Ruby's permissions?


##### `brew install awscli` (worked)
```
→ brew install awscli
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
nmh
==> Updated Formulae
notmuch

==> Downloading https://homebrew.bintray.com/bottles/awscli-1.11.1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring awscli-1.11.1.el_capitan.bottle.tar.gz
==> Caveats
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

Before using aws-cli, you need to tell it about your AWS credentials.
The quickest way to do this is to run:
  aws configure

More information:
  https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
  https://pypi.python.org/pypi/awscli#getting-started

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/awscli/1.11.1: 3,453 files, 28M
```

##### `brew doctor --debug --verbose` (failed)
```
 → brew doctor --debug --verbose
Checking check_access_cache
Checking check_access_cellar
Checking check_access_homebrew_repository
Checking check_access_logs
Checking check_access_prefix_directories
Checking check_access_site_packages
Checking check_clt_up_to_date
Checking check_dyld_vars
Checking check_filesystem_case_sensitive
Checking check_for_anaconda
Checking check_for_bad_curl
Checking check_for_bad_install_name_tool
Checking check_for_bad_python_symlink
Checking check_for_beta_xquartz
Checking check_for_config_scripts
Checking check_for_enthought_python
Checking check_for_external_cmd_name_conflict
Checking check_for_gettext
Checking check_for_git
Checking check_for_iconv
Checking check_for_installed_developer_tools
Checking check_for_latest_xquartz
Checking check_for_library_python
Checking check_for_multiple_volumes
Error: Operation not permitted - /tmp/doctor20161005-4006-lxgygi
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:85:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:85:in `block in mktmpdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:142:in `create'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:85:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:647:in `check_for_multiple_volumes'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
What's `env | grep -iE 'TE?MP'` and `echo "HOMEBREW_TEMP" | brew irb` output?

**Comment by filipre** [comment]
Thank you for your help btw!

```
# rene at Renes-MacBook-Pro.local in ~ [10:54:03]
→ env | grep -iE 'TE?MP'
TMPDIR=/var/folders/j_/0cgbtlz10q15nk07q5bbk9qw0000gn/T/

# rene at Renes-MacBook-Pro.local in ~ [10:54:04]
→ echo "HOMEBREW_TEMP" | brew irb
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
Switch to inspect mode.
HOMEBREW_TEMP
#<Pathname:/tmp>
```

**Comment by MikeMcQuaid** [comment]
What does `ls -lha /tmp` show?

**Comment by filipre** [comment]
```
→ ls -lha /tmp
lrwxr-xr-x@ 1 root  wheel    11B Sep 17  2015 /tmp -> private/tmp
```

**Comment by MikeMcQuaid** [comment]
Sorry, `ls -lha /tmp/` and also `mount`.

**Comment by filipre** [comment]
Alright:

```
→ ls -lha /tmp/
total 5384
drwxrwxrwt@ 14 root  wheel   476B Oct  5 09:21 .
drwxr-xr-x@  6 root  wheel   204B Oct  3 22:09 ..
-rw-rw-rw-@  1 rene  wheel     0B Oct  4 14:45 .keystone_install_lock
drwxr-xr-x@  6 rene  wheel   204B Oct  4 15:08 Atom Crashes
drwxr-xr-x@  6 rene  wheel   204B Oct  4 14:45 WhatsApp Crashes
drwx------   3 rene  wheel   102B Oct  4 14:44 com.apple.launchd.65KnVCBK85
drwx------   3 rene  wheel   102B Oct  4 14:44 com.apple.launchd.au9aS8gvsF
-rw-r--r--@  1 rene  wheel     0B Oct  4 14:44 ct.shutdown
-rw-r--r--   1 root  wheel   160K Oct  5 07:42 wifi-KRVRJc.log
-rw-r--r--   1 root  wheel   889K Oct  4 18:11 wifi-bilkHJ.log
-rw-r--r--   1 root  wheel   3.1K Oct  4 18:11 wifi-iTtPIA.log
-rw-r--r--   1 root  wheel   1.4M Oct  5 06:13 wifi-mhH0Y6.log
-rw-r--r--   1 root  wheel   4.1K Oct  4 18:11 wifi-oD05lp.log
-rw-r--r--   1 root  wheel   233K Oct  5 07:02 wifi-y0HWMA.log
```

```
→ mount
/dev/disk1 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
/dev/disk0s4 on /Volumes/BOOTCAMP (ntfs, local, read-only, noowners)
```

**Comment by MikeMcQuaid** [comment]
The plot thickens. How about `touch /tmp/test1` and `touch "$TMPDIR"/test2`?

**Comment by filipre** [comment]
Sweet!

```
# rene at Renes-MacBook-Pro.local in ~ [11:21:32]
→ touch /tmp/test1
touch: /tmp/test1: Operation not permitted

# rene at Renes-MacBook-Pro.local in ~ [11:30:20]
→ touch "$TMPDIR"/test2

# rene at Renes-MacBook-Pro.local in ~ [11:30:32]
→ echo $TMPDIR
/var/folders/j_/0cgbtlz10q15nk07q5bbk9qw0000gn/T/

**Comment by MikeMcQuaid** [comment]
Hmm, for some reason your `/tmp` isn't writable. I'll improve the `doctor` check but I'm not sure why this would be the case and it'll likely break some other software too.

**Comment by filipre** [comment]
Thank you for your help again. If you plan to extend the `doctor` check, we can leave the issue open. Otherwise feel free to close it since the error has nothing to do with `brew` itself.

Maybe as a follow up for someone who has similar problems:
I learned that OS X has for [historical reasons](http://apple.stackexchange.com/questions/1043/why-is-tmp-a-symlink-to-private-tmp) a symbolic link from `/tmp` to `/private/tmp`. Now it gets odd: `ls` shows the correct permissions for `/private/tmp` (`1777` or `drwxrwxrwt`).
```
→ ls -ld /private/tmp
drwxrwxrwt@ 14 root  wheel  476 Oct  5 20:33 /private/tmp
```
However, I can't write stuff there and the program `/usr/libexec/repair_packages` (a program to check if permissions are set correctly) tells me, that my folder is still screwed up. Additionally, it can't repair the permissions.
```
# rene at Renes-MacBook-Pro.local in /private/tmp [10:01:00]
→ touch /private/tmp/test
touch: /private/tmp/test: Operation not permitted

# rene at Renes-MacBook-Pro.local in /private/tmp [10:01:25]
→ sudo /usr/libexec/repair_packages --verify --standard-pkgs /private
	Permissions differ on "tmp", should be drwxrwxrwt , they are lrwxr-xr-x .
	Permissions differ on "usr/X11", should be drwxr-xr-x , they are lrwxr-xr-x .

# rene at Renes-MacBook-Pro.local in /private/tmp [10:04:49]
→ sudo /usr/libexec/repair_packages --repair --standard-pkgs /private
	Permissions differ on "tmp", should be drwxrwxrwt , they are lrwxr-xr-x .
	Unable to set owner & group on "tmp". Error 1: Operation not permitted
	Unable to set permissions on "tmp". Error 1: Operation not permitted
	Permissions differ on "usr/X11", should be drwxr-xr-x , they are lrwxr-xr-x .
	Repaired "usr/X11".
```
Although `chmod` runs without errors, writing files is still not possible. 
```
# rene at Renes-MacBook-Pro.local in /private/tmp [10:11:12]
→ sudo chmod 1777 /private/tmp

# rene at Renes-MacBook-Pro.local in /private/tmp [10:11:18]
→ touch /private/tmp/test
touch: /private/tmp/test: Operation not permitted
```

I might miss something there but this is all really confusing to me. Anyway, I will fix this when I have more time.

**Comment by MikeMcQuaid** [comment]
Yeh, sounds like a weird machine-specific thing. I'll make the doctor check handle this a bit better, though.

**Comment by mwerner** [comment]
Just to corroborate the problem; I am experiencing this on my machine as well.

**Comment by rz** [comment]
I'm also experiencing this problem.

**Comment by MikeMcQuaid** [comment]
If anyone can figure out _why_ the problem is happening we might be able to do something. There's not really a workaround for us otherwise so adding that this happens to you too doesn't really help. Regardless, it's not a bug in Homebrew but something else in your macOS installation.

**Comment by filipre** [comment]
Here is my "solution": I upgraded to Sierra. I still don't know what the problem was but I am very sure that this was an OS bug since I couldn't write to `/private/tmp` even though I had the right permissions. 
Notice that the update also removes `/usr/libexec/repair_packages` [[1](https://www.techisky.com/tips/disk-utility-missing-features-macos-sierra.html)].

**Comment by johndpope** [comment]
I installed fresh os - high sierra - successfully installed brew no problem.
After creating  a new admin user / account and logging in, then I try to run this script below to allow multiple users with access for brew.
Why? I don't want to have to install brew and associated packages for each user. or  
is this possible? am I doing this all wrong? anyway - you should be able to reproduce this error following above steps. 



it throws this same error.

sudo chgrp -R admin /usr/local
chgrp: /usr/local: Operation not permitted




#!/bin/sh
# Configure homebrew permissions to allow multiple users on MAC OSX.
# Any user from the admin group will be able to manage the homebrew and cask installation on the machine.

# allow admins to manage homebrew's local install directory
chgrp -R admin /usr/local
chmod -R g+w /usr/local

# allow admins to homebrew's local cache of formulae and source files
chgrp -R admin /Library/Caches/Homebrew
chmod -R g+w /Library/Caches/Homebrew

# if you are using cask then allow admins to manager cask install too
chgrp -R admin /opt/homebrew-cask
chmod -R g+w /opt/homebrew-cask
