### ISSUE TITLE
brew update failed now continually fails with "/usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative': cannot load such file -- /usr/local/Homebrew/Library/Homebrew/load_path (LoadError)"

### ISSUE THREAD

**Issue by ch4unc3y** [Homebrew/brew#12254]
### `brew config` output

```shell
/usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative': cannot load such file -- /usr/local/Homebrew/Library/Homebrew/load_path (LoadError)
	from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
```

### `brew doctor` output

```shell
/usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative': cannot load such file -- /usr/local/Homebrew/Library/Homebrew/load_path (LoadError)
	from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to do a simple brew update. Last night, I issued the "brew update" command at a command prompt and it took quite a while (over half an hour) and it failed, and although I don't remember the exact error, I do remember it failed and it did have some information similar to https://github.com/Homebrew/homebrew-core/issues/2970, particularly the "If no other git process is currently running, this probably means a git process crashed in this repository earlier" message. I have no idea where any of this is logged, otherwise I would give the exact output.

When It tried to do a "brew update" this morning, or at any time now, it fails - I will give that output in the next "What happened" section.

### What happened (include all command output)?

------ I enter the following at a command prompt:
$ brew update
------ output:
Traceback (most recent call last):
	3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	2: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	1: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative': cannot load such file -- /usr/local/Homebrew/Library/Homebrew/load_path (LoadError)
Error: 'git' must be installed and in your PATH!

------ I enter the following at a command prompt:
$ type git
------ output:
git is /usr/bin/git

------- I am on macos Catalina, 10.15.7, latest update for Catalina

### What did you expect to happen?

Normal update.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
------ I enter the following at a command prompt:
$ brew update
------ output:
Traceback (most recent call last):
	3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	2: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	1: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative': cannot load such file -- /usr/local/Homebrew/Library/Homebrew/load_path (LoadError)
Error: 'git' must be installed and in your PATH!

------ I enter the following at a command prompt:
$ type git
------ output:
git is /usr/bin/git

------ I enter the following at a command prompt:
$ brew config
------ output:
Traceback (most recent call last):
	3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	2: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	1: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative': cannot load such file -- /usr/local/Homebrew/Library/Homebrew/load_path (LoadError)

------ I enter the following at a command prompt:
$ brew doctor
------ output:
Traceback (most recent call last):
	3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	2: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	1: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative': cannot load such file -- /usr/local/Homebrew/Library/Homebrew/load_path (LoadError)
```

**Comment by ch4unc3y** [comment]
$ brew update-reset
==> Fetching /usr/local/Homebrew...
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory

==> Resetting /usr/local/Homebrew...
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions...
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions...
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 113: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory

------ brew update/doctor/config still fail same way

**Comment by carlocab** [comment]
Try `brew update-reset` again. If that doesn't work:

What's the output of
```
ls -la /usr/local/Homebrew/Library/Homebrew/shims/shared
ls -la /usr/local/Homebrew/Library/Homebrew/shims/scm
ls -la /usr/local/Homebrew/Library/Homebrew/shims
```
?
