### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by xnathanh** [Homebrew/brew#1226]
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
remote: Counting objects: 85, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 85 (delta 81), reused 76 (delta 72), pack-reused 0
Unpacking objects: 100% (85/85), done.
From https://github.com/Homebrew/brew
 ! [rejected]        master     -> origin/master  (non-fast-forward)
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1

brew --config 
HOMEBREW_VERSION: 1.0.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35ee2831086e923e7fcaf75fb440b01312e3f9c5
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f3a2b0a1e146cbc091e12d474617be57cf9be8be
Core tap last commit: 22 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_72
macOS: 10.12-x86_64
Xcode: 8.0
CLT: 8.0.0.0.1.1472435881
X11: N/A

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/install#70
