### ISSUE TITLE
Github API Error

### ISSUE THREAD

**Issue by ASBaumgarten** [Homebrew/brew#1230]
`Error: GitHub API Error: API rate limit exceeded for 50.251.82.155. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Try again in 15 minutes 49 seconds, or create a personal access token:
  https://github.com/settings/tokens/new?scopes=&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token" `

Why is this coming up as an error and will I have to authenticate every network I use to avoid this?

**Comment by vladshablinsky** [comment]
This means what it says, probably you're trying to access GitHub API too frequently.

[For requests using Basic Authentication or OAuth, you can make up to 5,000 requests per hour. For unauthenticated requests, the rate limit allows you to make up to 60 requests per hour. Unauthenticated requests are associated with your IP address, and not the user making requests. Note that the Search API has custom rate limit rules.](https://developer.github.com/v3/#rate-limiting)

 You can try setting `HOMEBREW_NO_GITHUB_API` environment variable I guess.

**Comment by vladshablinsky** [comment]
Hm, I see the problem. Could you provide the command you ran to get this output?

**Comment by ASBaumgarten** [comment]
I've just been doing regular brew search command

**Comment by MikeMcQuaid** [comment]
As mentioned by the error message, you need to either set an API token or run `brew search` less often.

**Comment by joem** [comment]
> As mentioned by the error message, you need to either set an API token or run brew search less often.

I just did four `brew search` commands and got this rate limit error (this was my first time doing a `brew search` in weeks or months). That doesn't seem right to me.
