### ISSUE TITLE
Apply HOMEBREW_INSTALL_FROM_API env to brew upgrade operations

### ISSUE THREAD

**Issue by fanvinga** [Homebrew/brew#12326]
### Provide a detailed description of the proposed feature

After Homebrew 3.3.0 released, `HOMEBREW_INSTALL_FROM_API` has been added to avoid clone taps and this flag works on `brew install` operations.However `brew outdated/upgrade` would still try to clone the remote `Homebrew/homebrew-core` repo to local.Is this kind of behavior necessary ?

### What is the motivation for the feature?

Improve the `brew outdated/upgrade` experience.

### How will the feature be relevant to at least 90% of Homebrew users?

By improve the `brew outdated/upgrade` experience.

### What alternatives to the feature have been considered?

No

**Comment by fanvinga** [comment]
> Either way, thanks for opening this issue and being so helpful, @fanvinga! It was very helpful for us because we were able to fix some issues, even though you didn't really get the answer you're looking for. I appreciate it!

@Bo98 @Rylan12 Thank you both very much for your efforts in thinking about this and related problems, I tried to uninstall Homebrew completely and reinstall it using the install script, now `brew upgrade/outdated/install` can be done without clone remote repo, I think the root of the problem may be in the previous accumulation of local taps or branches, anyway, thanks again for your efforts!

**Comment by fanvinga** [comment]
@Rylan12 Sorry to interrupt your again, but I seem to have found something related to this issue, when I set `HOMEBREW_INSTALL_FROM_API`, brew upgrade does not get the correct latest version, but following the curl command in the debug message, I found the correct version in the json downloaded from curl.
![image](https://user-images.githubusercontent.com/26292849/139531759-5f7c1d71-89d5-4c8c-b90a-c965a59a2a3a.png)

**Comment by fanvinga** [comment]
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/26292849/139531815-bd2674d4-3035-4edc-bd40-d03b47e76517.png">

**Comment by carlocab** [comment]
Please [don't use screenshots](https://meta.stackoverflow.com/a/285557) when sharing the output of commands in your terminal. They're often difficult to read and impossible to reuse. Instead, copy the text here and wrap them in three back-ticks (```) on the line before and on the line after to format them properly.

**Comment by fanvinga** [comment]
> Please [don't use screenshots](https://meta.stackoverflow.com/a/285557) when sharing the output of commands in your terminal. They're often difficult to read and impossible to reuse (e.g. when looking up error messages). Instead, copy the text here and wrap them in three back-ticks (```) on the line before and on the line after to format them properly.

Sorry, I was just a little worried that placing the output directly here would make the comment too long and unreadable.I won't do it again :-(

**Comment by carlocab** [comment]
Long comments are fine. You can dump them in a text file and attach them to the comment if needed. Or, you can use [collapsible markdown](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab) to hide long text under a fold. (Click on the `Raw` button the top right to see how the linked gist is formatted.)

**Comment by Rylan12** [comment]
This looks like the same (or similar) problem to https://github.com/Homebrew/discussions/discussions/2365#discussioncomment-1560798.

Since this is a different problem, it's probably best to discuss it in a separate issue. I've asked the user who reported it in the discussion I linked to open an issue but feel free to open it first if you'd like.

I'm looking into it

**Comment by fanvinga** [comment]
@Rylan12 After update homebrew to 3.3.2, the issue seems to be solved, there isn't any thing strange during `brew update && brew upgrade`.But I cannot sure it's fixed by 3.3.2 or by reinstalling sublime-text before 3.3.2
BTW, after updating homebrew to 3.3.2, I found a new issue that I have already reported #12356 .

**Comment by Rylan12** [comment]
Glad it's solved. I wonder if the cause was actually just a weird timing bug. When you ran `brew update`, you may have updated the local cask tap to a state that included `sublime-text` 4.121. So, for some reason, that `brew upgrade` invocation upgraded the cask. However, it takes some time (at most 1 hour) for the API to be updated when new versions are released, so when you tried again, it used the latest API version (which is 4.113). I'm not totally sure how that would have happened, but I did notice that the first invocation updated from 4.113 to 4.121 (which was expected), and the second seemed to stay at 4.113 which would have been outdated.

**Comment by fanvinga** [comment]
> Glad it's solved. I wonder if the cause was actually just a weird timing bug. When you ran `brew update`, you may have updated the local cask tap to a state that included `sublime-text` 4.121. So, for some reason, that `brew upgrade` invocation upgraded the cask. However, it takes some time (at most 1 hour) for the API to be updated when new versions are released, so when you tried again, it used the latest API version (which is 4.113). I'm not totally sure how that would have happened, but I did notice that the first invocation updated from 4.113 to 4.121 (which was expected), and the second seemed to stay at 4.113 which would have been outdated.

I have a feeling you are right, but the strange thing is that just like the picture I showed above, I followed the `curl`commands given in the debug and tried to check the version provided by the api and found that it was the latest version, but at this point brew still thinks that the old version is the latest.

Anyway, due to the issue is solved now and the comments are too much here, I think it's time to focus on others issue.Thank you again for explaining and have a great weekend!
