### ISSUE TITLE
`brew rm <URL>` downcases the URL when fetching it

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/brew#1232]
(note: I’m using Linuxbrew here but others have been able to reproduce the issue on macOS)

Steps to reproduce:

```
$ brew rm -v https://raw.githubusercontent.com/teoljungberg/homebrew-core/4f08fc94bd35aecebe16e6c1b59c423a772df4e6/Formula/pick.rb
/usr/bin/curl --fail --remote-time --location --user-agent Linuxbrew/1.0.6-2-gcdb9b18 (Linux; x86_64 Ubuntu 14.04.5 LTS) curl/7.35.0 https://raw.githubusercontent.com/teoljungberg/homebrew-core/4f08fc94bd35aecebe16e6c1b59c423a772df4e6/formula/pick.rb -o /home/baptiste/.cache/Homebrew/Formula/pick.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /usr/bin/curl --fail --remote-time --location --user-agent Linuxbrew/1.0.6-2-gcdb9b18\ (Linux;\ x86_64\ Ubuntu\ 14.04.5\ LTS)\ curl/7.35.0 https://raw.githubusercontent.com/teoljungberg/homebrew-core/4f08fc94bd35aecebe16e6c1b59c423a772df4e6/formula/pick.rb -o /home/baptiste/.cache/Homebrew/Formula/pick.rb
```

It may fail later in the process if you don’t have `pick` installed but it shouldn’t fail when fetching the formula. It’s because it tries to fetch a downcased URL: see the `…/Formula/…` that becomes `…/formula/…` in the `curl` command.

---

`brew rm` calls `ARGV.kegs`, which itself calls `downcased_unique_named` ([see here](https://github.com/Homebrew/brew/blob/7e70ebd4f188e59172decc3a74aa61fbb4b58655/Library/Homebrew/extend/ARGV.rb#L67)). The downcased URL is then passed to `Formulary.to_keg` which passes it to `Formulary.factory` ([here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formulary.rb#L271)), which retrieves the formula using [`FromUrlLoader`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formulary.rb#L139).

The problem is thus that we want to preserve the argument’s casing _when it’s an URL_. I don’t have a fix ready for that; hence an issue instead of a PR.

**Comment by MikeMcQuaid** [comment]
Honestly I'd probably rather we scoped back the places we accept URLs. They don't work well and there's rarely a good argument for one over a tap or `brew pull`.

**Comment by MikeMcQuaid** [comment]
Gonna close this out just because it's not something users are hitting. Will accept a fix, though.
