### ISSUE TITLE
make curl more resilient to failures

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/brew#1234]
_From @rdp on October 5, 2016 23:4_

As a note, I once got this:

```
$brew install rpm
==> Installing dependencies for rpm: berkeley-db, libmagic, popt, libtasn1, ossp-uuid
==> Installing rpm dependency: berkeley-db
==> Downloading https://homebrew.bintray.com/bottles/berkeley-db-6.1.26.el_capitan.bottle.tar.gz

curl: (35) Server aborted the SSL handshake
Error: Failed to download resource "berkeley-db"
Download failed: https://homebrew.bintray.com/bottles/berkeley-db-6.1.26.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading http://download.oracle.com/berkeley-db/db-6.1.26.tar.gz

curl: (52) Empty reply from server
Error: Failed to download resource "berkeley-db"
Download failed: http://download.oracle.com/berkeley-db/db-6.1.26.tar.gz
```

but on retry it worked:

```
$brew install rpm
==> Installing dependencies for rpm: berkeley-db, libmagic, popt, libtasn1, ossp-uuid
==> Installing rpm dependency: berkeley-db
==> Downloading https://homebrew.bintray.com/bottles/berkeley-db-6.1.26.el_capitan.bottle.tar.gz
###############################                                           43.5%
######################################################################## 100.0%
==> Pouring berkeley-db-6.1.26.el_capitan.bottle.tar.gz
```

Suggestion/feature request: make curl more resilient to failures, this may help anyway (sorry for the manual diff, I'd be happy to convert to pull request if it has a chance of being accepted and that would help).
Cheers!

```

diff --git a/Library/Homebrew/utils/curl.rb b/Library/Homebrew/utils/curl.rb
index 00c3a59..2b706ac 100644
--- a/Library/Homebrew/utils/curl.rb
+++ b/Library/Homebrew/utils/curl.rb
@@ -12,6 +12,7 @@ def curl_args(extra_args = [])
   args = [curl.to_s] + flags + extra_args
   args << "--verbose" if ENV["HOMEBREW_CURL_VERBOSE"]
   args << "--silent" if !$stdout.tty? || ENV["TRAVIS"]
+  args << "--retry 5"
   args
 end

```

_Copied from original issue: Homebrew/homebrew-core#5618_

**Comment by bfontaine** [comment]
>  (sorry for the manual diff, I'd be happy to convert to pull request if it has a chance of being accepted and that would help)

Please make pull-requests instead of diffs in issues; it makes them easier to review.

**Comment by MikeMcQuaid** [comment]
`--retry 1` may be a good default. I'd be 🆗 with that as long as respects Ctrl-C interrupts as expected.

**Comment by tyteen4a03** [comment]
+1.

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by rdp** [comment]
Yeah I'll try and do a pull request feel free to close this one.
