### ISSUE TITLE
Error: No Homebrew ruby 2.6.8 available for arm64 processors!

### ISSUE THREAD

**Issue by KyLeggiero** [Homebrew/brew#12351]
### `brew config` output

```shell
Error: No Homebrew ruby 2.6.8 available for arm64 processors!
Error: Failed to upgrade Homebrew Portable Ruby!
```

### `brew doctor` output

```shell
Error: No Homebrew ruby 2.6.8 available for arm64 processors!
Error: Failed to upgrade Homebrew Portable Ruby!
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.

### What were you trying to do (and why)?

Anything at all. Installing a formula, installing a cask, updating homebrew, getting info... anything.

### What happened (include all command output)?

No matter what I do, it outputs:

```
Error: No Homebrew ruby 2.6.8 available for arm64 processors!
Error: Failed to upgrade Homebrew Portable Ruby!
```

### What did you expect to happen?

What was supposed to happen

### Step-by-step reproduction instructions (by running `brew` commands)

1. Open Terminal
2. Type `brew `
3. Type a space and then any homebrew command
4. Press <kbd>return</kbd>

---

**I also tried to re-install homebrew.** That did not change this problem.

**Comment by Bo98** [comment]
Sounds like you are using an x86_64 installation of Homebrew in an arm64 Terminal. Check your `PATH`.

**Comment by KyLeggiero** [comment]
@Bo98 why would it install that? I just ran the standard installation script.

Here's my `$PATH`:

```zsh
% echo $PATH
/usr/local/opt/openjdk/bin:/Users/benleggiero/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/benleggiero/Library/Android/sdk/platform-tools:.:/Users/benleggiero/.rvm/bin:/opt/homebrew
```

**Comment by Archerious** [comment]
Same issue as well. 

```
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Ruby version 2.6.3 is unsupported on macOS 12. Homebrew
is developed and tested on Ruby 2.6.8, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
```

**Comment by SleepyBrett** [comment]
Same thing is happening for me this afternoon.

**Comment by Bo98** [comment]
You don't have arm64 Homebrew in your PATH. Run:

```
echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> /Users/$USER/.zprofile
eval $(/opt/homebrew/bin/brew shellenv)
```

(or whatever is appropriate for the shell you use)

If you don't need x86_64 Homebrew then you can also run:

```
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
```

**Comment by SleepyBrett** [comment]
opt? my homebrew is in /usr/local

**Comment by Bo98** [comment]
`/opt/homebrew` is arm64
`/usr/local` is x86_64

**Comment by SleepyBrett** [comment]
I assume that this is because i did a transfer from a x86 machine. I guess I'll wipe it and start over.

**Comment by MikeMcQuaid** [comment]
> Sounds like you are using an x86_64 installation of Homebrew in an arm64 Terminal. Check your `PATH`.

Leaving this open because we should handle this better.

**Comment by workhardforcoding** [comment]
I met the same issue. And I just re-install the home brew following instructions on official website. Please check here https://brew.sh/

**Comment by GJRobert** [comment]
I have installed arm64 Homebrew with script on https://brew.sh/, but without uninstalling x86_64 Homebrew first. Will there be a problem? How to uninstall my Homebrew in /usr/local if necessary for M1 Silicon systems?

(Also wondering, because my x86_64 Homebrew seems to be installed by macOS Command Line Tools. Is it Apple which should use arm64 Homebrew instead, in the first place?)

**Comment by KyLeggiero** [comment]
> You don't have arm64 Homebrew in your PATH

Isn't that what's at the end? `:/opt/homebrew`?

> Run:
> ```
> echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> /Users/$USER/.zprofile
> eval $(/opt/homebrew/bin/brew shellenv)
> ```

I did and it seems to have fixed it. Perhaps that should be added to some automation in homebrew, or at least noted in the error message

**Comment by MikeMcQuaid** [comment]
> Isn't that what's at the end? `:/opt/homebrew`?

If it's at the end but `/usr/local/bin` is ahead of it: it won't be used.

> Perhaps that should be added to some automation in homebrew, or at least noted in the error message

The installer tells you to do that.

**Comment by KyLeggiero** [comment]
> If it's at the end but /usr/local/bin is ahead of it: it won't be used.

oh good point, @MikeMcQuaid! Thank you. Shell is not my native environment 😅

> The installer tells you to do that.

I don't recall ever seeing that message, but I'll trust you on that. Thank you for letting me know
