### ISSUE TITLE
brew info cannot show information of remote formulae with `HOMEBREW_INSTALL_FROM_API` set

### ISSUE THREAD

**Issue by fanvinga** [Homebrew/brew#12357]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9daf5e2d28396c7a4379605e89e029d9fccb41e6
Last commit: 2 hours ago
Core tap: N/A
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.MstZqkjrdb/org.xquartz:0
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.33.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: N/A
XQuartz: 2.8.1 => /opt/X11
Rosetta 2: false
```

### `brew doctor` output

```shell
Due to #12356, I'll update this output after `brew doctor` works.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to show information of some formulas and casks I haven't installed.But I found that I can only get the information of installed formulas and get errors with others.

### What happened (include all command output)?

For those formulas/casks that were already installed, I can get their information.But for those I haven't installed, I get some errors.

```
╭─ ~/Desktop [ 15:16:21 ] Δ
╰─ brew info fish
Error: No available formula or cask with the name "fish".
╭─ ~/Desktop [ 15:16:28 ] ✗
╰─ brew info --cask telegram
Error: Cask 'telegram' is unavailable: No Cask with this name exists.
╭─ ~/Desktop [ 15:16:35 ] ✗
╰─ brew info go
go: stable 1.17.2 (bottled), HEAD
Open source programming language to build simple/reliable/efficient software
https://golang.org
/opt/homebrew/Cellar/go/1.17.2 (10,814 files, 564.3MB) *
  Poured from bottle on 2021-10-12 at 11:20:18
From: /opt/homebrew/opt/go/.brew/go.rb
License: BSD-3-Clause
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 113,364 (30 days), 331,395 (90 days), 1,326,761 (365 days)
install-on-request: 91,500 (30 days), 267,219 (90 days), 1,079,209 (365 days)
build-error: 0 (30 days)
╭─ ~/Desktop [ 15:16:45 ] Δ
╰─ brew info docker
docker: 4.1.1,69879 (auto_updates)
https://www.docker.com/products/docker-desktop
/opt/homebrew/Caskroom/docker/4.1.1,69879 (120B)
==> Names
Docker Desktop
Docker Community Edition
Docker CE
==> Description
App to build and share containerized applications and microservices
==> Artifacts
Docker.app (App)
/Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion -> /opt/homebrew/etc/bash_completion.d/docker-compose (Binary)
/Applications/Docker.app/Contents/Resources/etc/docker.zsh-completion -> /opt/homebrew/share/zsh/site-functions/_docker (Binary)
/Applications/Docker.app/Contents/Resources/etc/docker.fish-completion -> /opt/homebrew/share/fish/vendor_completions.d/docker.fish (Binary)
/Applications/Docker.app/Contents/Resources/etc/docker-compose.fish-completion -> /opt/homebrew/share/fish/vendor_completions.d/docker-compose.fish (Binary)
/Applications/Docker.app/Contents/Resources/etc/docker-compose.zsh-completion -> /opt/homebrew/share/zsh/site-functions/_docker_compose (Binary)
/Applications/Docker.app/Contents/Resources/etc/docker.bash-completion -> /opt/homebrew/etc/bash_completion.d/docker (Binary)
==> Analytics
install: 19,321 (30 days), 57,042 (90 days), 223,129 (365 days)
```

### What did you expect to happen?

`brew info` returns correct information of formulas/casks.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1.Set `HOMEBREW_INSTALL_FROM_API`
2.brew info FORMULAS_NOT_INSTALLED
```

**Comment by Rylan12** [comment]
Thanks, we are aware that `brew info` hasn't been updated to handle `HOMEBREW_INSTALL_FROM_API`.

If someone would like to take a stab at this, feel free. Essentially, the goal is to modify `brew info` to use the formula API (i.e. `/api/formula/foo.json`) as its source of information instead of the formula file for core formulae when `HOMEBREW_INSTALL_FROM_API` is set and `homebrew/core` isn't installed. However, pending discussion in #12350, we may choose to go about this in a different way.

The turnaround time for this is likely going to be a bit longer as I'm going to focus on fixing the bugs that are appearing (btw thank you for reporting so many of these, it's been very helpful for us) and my time is pretty limited.

**Comment by fanvinga** [comment]
> The turnaround time for this is likely going to be a bit longer as I'm going to focus on fixing the bugs that are appearing (btw thank you for reporting so many of these, it's been very helpful for us) and my time is pretty limited.

I'm just so excited about how much space this feature can save (it can take hours to download hundreds of MB of repositories files from GitHub in my location) that I want to use it as much as possible.Of course everything works thanks to your hard work, have a great weekend!

**Comment by Rylan12** [comment]
Thanks for the kind words, and I'm glad you see the value in the feature! This is exactly what we were hoping for! ❤️

**Comment by kidonng** [comment]
This seems to have been resolved.

```shellsession
$ echo $HOMEBREW_INSTALL_FROM_API 
1

$ brew info go
==> go: stable 1.19.1 (bottled)
Open source programming language to build simple/reliable/efficient software
https://go.dev/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/go.rb
License: BSD-3-Clause
==> Analytics
install: 138,644 (30 days), 441,740 (90 days), 1,574,968 (365 days)
install-on-request: 110,816 (30 days), 351,323 (90 days), 1,257,021 (365 days)
build-error: 483 (30 days)
```
