### ISSUE TITLE
Add an option to install only if not already installed

### ISSUE THREAD

**Issue by andyfleming** [Homebrew/brew#12361]
### Provide a detailed description of the proposed feature

Add an option to install only if not already installed with CLI option `--if-not-installed`.

### What is the motivation for the feature?

When setting up a new computer, I'd like to ignore applications I may have already installed (or that may have been automatically provisioned by other software).

### How will the feature be relevant to at least 90% of Homebrew users?

Anyone using brew cask installations for setup of a new computer could be interested in this feature.

### What alternatives to the feature have been considered?

The old issue (#2491) was closed for this, but 3 years later as a newcomer to this CLI feature, I find it compelling.

The alternative suggested was to use a Brewfile or implement the logic yourself in a script. The reason that it's not sufficient is that writing the logic myself might be complicated. I do want to catch an error if installation actually files, but I don't want my script to exit with an error if it's already installed. In the context of a brew cask installation, I don't consider that a hard error.

**Comment by Rylan12** [comment]
`brew install` on a formula or cask that's already installed still returns a passing exit code, so your script shouldn't exit unless there's an actual installation error:

```console
$ brew list hello
Error: No available formula or cask with the name "hello". Did you mean jello or helm?

$ brew install hello
==> Downloading https://ghcr.io/v2/homebrew/core/hello/manifests/2.10
Already downloaded: /Users/rylanpolster/Library/Caches/Homebrew/downloads/93309a1636f67f0f51e2604bb2ece243b5a9324eda1d49e05192ed285af508cd--hello-2.10.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/hello/blobs/sha256:69489ae397e4645127aa7773211310f81ebb6c99e1f8e3e22c5cdb55333f5408
Already downloaded: /Users/rylanpolster/Library/Caches/Homebrew/downloads/e0395c201b40d07f50d44b84fccab28bb89bb292929894555688f6510f583a4c--hello--2.10.big_sur.bottle.tar.gz
==> Pouring hello--2.10.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/hello/2.10: 11 files, 165.7KB

$ echo $?
0

$ brew install hello
Warning: hello 2.10 is already installed and up-to-date.
To reinstall 2.10, run:
  brew reinstall hello

$ echo $?
0
```

**Comment by andyfleming** [comment]
The exit code is `1` if the application was installed from a different source.

```bash
brew install --cask slack
```

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/cask-fonts).
==> Updated Formulae
Updated 14 formulae.
==> New Casks
inso
==> Updated Casks
Updated 28 casks.
==> Deleted Casks
eudic-es                                                      videobox

==> Downloading https://downloads.slack-edge.com/releases/macos/4.21.1/prod/arm64/Slack-4.21.1-macOS.dmg
######################################################################## 100.0%
==> Installing Cask slack
==> Purging files for version 4.21.1 of Cask slack
Error: It seems there is already an App at '/Applications/Slack.app'.
```

```bash
echo $?
```

```
1
```

**Comment by MikeMcQuaid** [comment]
> The exit code is `1` if the application was installed from a different source.

This is intentional for Cask installed stuff, we have no way of tracking upgrades or verifying that it's the same application otherwise. 

Passing on this, sorry!

**Comment by andyfleming** [comment]
The exit code totally makes sense, but that doesn't really negate the use case.

Alternatively, is there an existing flag to overwrite an existing installation and have homebrew manage the application instead?

**Comment by MikeMcQuaid** [comment]
> Alternatively, is there an existing flag to overwrite an existing installation and have homebrew manage the application instead?

Yeh, `--force` will do this 👍🏻

**Comment by andyfleming** [comment]
While, not preferred, I think this will work cleanly enough for my use case. Thanks! 👍
