### ISSUE TITLE
brew update crashes with 'Error: stack level too deep'

### ISSUE THREAD

**Issue by martinborgman** [Homebrew/brew#12370]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.2-27-gffd3077
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ffd3077bebaf12197df2770bea429a7205f172ec
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 13cb6c4236be8a72e9b6b257ac001f71f62ab887
Core tap last commit: 9 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 24
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: 24-core 64-bit westmere
Clang: 12.0.0 build 1200
Git: 2.33.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  bicep
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the cue-lang/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/cue-lang/homebrew-tap/cue.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the instrumenta/instrumenta tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/instrumenta/homebrew-instrumenta/Formula/conftest.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the wagoodman/dive tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/wagoodman/homebrew-dive/dive.rb:6

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the azure/functions tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/azure/homebrew-functions/Formula/azure-functions-core-tools@3.rb:10

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the derailed/k9s tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/derailed/homebrew-k9s/Formula/k9s.rb:9

Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/pathname.rb:42:in `chop_basename'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/pathname.rb:359:in `plus'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/pathname.rb:351:in `+'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:310:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
.
.
.
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:302:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:547:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:547:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:418:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:484:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:457:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1704:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1703:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1703:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1703:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:700:in `check_deprecated_disabled'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I wanted to update my homebrew system

### What happened (include all command output)?

$ brew update
Updated 1 tap (homebrew/core).
==> New Formulae
twty
==> Updated Formulae
chezmoi                      libstrophe                   mmctl                        newrelic-infra-agent         zoxide
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the cue-lang/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/cue-lang/homebrew-tap/cue.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the instrumenta/instrumenta tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/instrumenta/homebrew-instrumenta/Formula/conftest.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the wagoodman/dive tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/wagoodman/homebrew-dive/dive.rb:6

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the azure/functions tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/azure/homebrew-functions/Formula/azure-functions-core-tools@3.rb:10

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the derailed/k9s tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/derailed/homebrew-k9s/Formula/k9s.rb:9

Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/tap.rb:46:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/tap.rb:46:in `any?'
/usr/local/Homebrew/Library/Homebrew/tap.rb:46:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:308:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
.
.
.
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:328:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:302:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:547:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:547:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:418:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:484:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:457:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1704:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1703:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1703:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1703:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:503:in `migrate_formula_rename'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:189:in `block in update_report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:189:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'

### What did you expect to happen?

I expected a list with outdated formulas

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
```

**Comment by martinborgman** [comment]
brow doctor, brew outdated and brew upgrade also fail

This also happens on a different mac running macOS: 12.1-x86_64.

**Comment by carlocab** [comment]
Is the
```
.
.
.
```
from you truncating the stacktrace? Because the part you cut out is likely pretty important for working out what's going on.

If it's too long, dump it in a text file and attach it to a comment or upload it to a gist.

The error also seems to be related to parsing the taps you have installed. I'd try `untap`ping them to see which one might be causing this.

**Comment by martinborgman** [comment]
Yes
[brew-update-error.txt](https://github.com/Homebrew/brew/files/7463508/brew-update-error.txt)

Added output as attachment.

**Comment by martinborgman** [comment]
brew untap also fails

**Comment by martinborgman** [comment]
brew doctor --debug revealed a missing formula. See output below

==> Checking check_access_directories
==> Checking check_brew_git_origin
/usr/local/Homebrew/Library/Homebrew/shims/shared/git --version
==> Checking check_broken_sdks
==> Checking check_cask_environment_variables
==> Checking check_cask_install_location
==> Checking check_cask_load_path
==> Checking check_cask_quarantine_support
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Checking check_cask_software_versions
==> Checking check_cask_staging_location
==> Checking check_cask_taps
==> Checking check_cask_xattr
/usr/bin/xattr -h
==> Checking check_casktap_integrity
==> Checking check_clt_minimum_version
==> Checking check_clt_up_to_date
==> Checking check_coretap_integrity
==> Checking check_deleted_formula
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  bicep
==> Checking check_deprecated_caskroom_taps
==> Checking check_deprecated_disabled
.
.
.
 but the 'azure/bicep' tap was installed.

So I moved the /usr/local/Homebrew/Library/Tabs/azure directory to my home directory to see if this would fix the issue and it did.

**Comment by martinborgman** [comment]
The azure/bicep tap does not appear to contain a homebrew formula. It appears to contain the contents of the bicep source code. I wil make an issue in the azure bicep github repository.

**Comment by martinborgman** [comment]
Microsoft already fixed the issue.

**Comment by dirien** [comment]
@martinborgman did you just reinstall the azure tap? Runnning in the same error right now :(

**Comment by martinborgman** [comment]
Yes, I first removed the azure/bicep directory and reinstalled the azure bicep tap.
