### ISSUE TITLE
Propose to add VictoriaMetrics into brew packages

### ISSUE THREAD

**Issue by denisgolius** [Homebrew/brew#12383]
### Provide a detailed description of the proposed feature

There is a TSDB named [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics). I can be used as a Prometheus replacement. More over it has many other features that have been improve from developers - see this https://docs.victoriametrics.com/#prominent-features

### What is the motivation for the feature?

VictoriaMetrics as other open source software is free to use and open for feature requests from users. As a community member I see feature requests for adding VictoriaMetrics to brew packages. But I can't find any documentation how to add it so created this feature request.

### How will the feature be relevant to at least 90% of Homebrew users?

For now we have an RPM community repository for redhat linux and redhat forks, docker scenarios and kubernetes helm charts for installation and using it but many users don't want to use docker on MacOS and prefer to use binary files from brew. IMHO: adding VictoriaMetrics to brew packages will increase amount of new users which could bring new contributors.

### What alternatives to the feature have been considered?

Brew already contains loki, grafana, prometheus, influxdb and other software for monitoring different kind of software and devices but I think that the availability of alternatives and competitors always encourages the development and improvement of the quality of the software.

**Comment by carlocab** [comment]
Please open a pull request at https://github.com/Homebrew/homebrew-core. This guide might help: https://docs.brew.sh/Adding-Software-to-Homebrew
