### ISSUE TITLE
`--HEAD` option doesn't work for `brew install`

### ISSUE THREAD

**Issue by lgarron** [Homebrew/brew#12389]
### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I maintain a personal tap: https://github.com/lgarron/homebrew-lgarron
It mostly installs scripts from: https://github.com/lgarron/scripts

In order to avoid having to update both repos every time I change a script, I use `--HEAD` to install. Unfortunately, `brew reinstall --HEAD` always fails.

### What happened (include all command output)?

```shell
Error: invalid option: --HEAD
```

### What did you expect to happen?

`brew reinstall` accepts the `--HEAD` argument like `brew install` does!

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --HEAD lgarron/lgarron/node_crunchule
brew reinstall --HEAD lgarron/lgarron/node_crunchule
```

**Comment by lgarron** [comment]
`brew tests` fails with `rspec ./test/cask/cmd/reinstall_spec.rb:27` locally, but the output is a bit annoying for me to debug. CI for this PR also shows a failure, but I believe it's an unrelated flake.

**Comment by carlocab** [comment]
If you did `brew install --HEAD foo`, then `brew reinstall foo` will reinstall `foo` from the latest commit. There is no need to pass `--HEAD` to `brew reinstall`.

Adding a `--HEAD` flag to `brew reinstall` is also likely to interact poorly with having both the `stable` and `head` installed in parallel -- which you can do.

**Comment by lgarron** [comment]
> If you did `brew install --HEAD foo`, then `brew reinstall foo` will reinstall `foo` from the latest commit. There is no need to pass `--HEAD` to `brew reinstall`.

Ah, nice. I had issues with this in the past, but they may have been unrelated. It seems to work well for me now!
