### ISSUE TITLE
41 core formulas depend on `tap` and can not be run directly

### ISSUE THREAD

**Issue by evanphx** [Homebrew/brew#12410]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.3-11-ge38e25d
ORIGIN: https://github.com/Homebrew/brew
HEAD: e38e25dfd1936af95b1cd4c13abb738ca366d36b
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1a0415ac2ba81b241c37466380e0bbe0813ee78d
Core tap last commit: 2 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  libelf

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gmp
  pinentry
  libksba
  gpgme
  nettle
  libunistring
  libyaml
  bdw-gc
  libassuan
  libgpg-error
  libtasn1
  oniguruma
  unbound
  jq
  libusb
  guile
  gnupg
  p11-kit
  gnutls
  npth

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Attempting to run the homebrew-core formula `llvm` directly, as `brew install ./llvm.rb`.

### What happened (include all command output)?

Trying to run a formula in homebrew-core such as `llvm` from a file such as `brew install ./llvm.rb` errors out because this and 40 other formulas in core depend on the Formula attribute `tap` to calculate things like `tap.user` and `tap.issues_url`.

The code establishes that when a formula is run as a file directly, `tap` will be set to nil, causing the formula to break.

### What did you expect to happen?

The formula does not error out and instead the values for the CoreTap are returned. Or all the core formulas that use `tap` need to be updated to conditionally use it.

I'm happy submit a PR to either work but want some guidance on which.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
git co https://github.com/homebrew/homebrew-core.git
cd homebrew-core/Formula
brew install ./llvm.rb
```
```

**Comment by carlocab** [comment]
The requested information might not seem relevant to you, but that's not the same as being not relevant. We can reopen this when you provide them.

**Comment by evanphx** [comment]
Could you reopen it? I'm happy to add those now.

**Comment by evanphx** [comment]
@carlocab sorry about that, they're added now.

**Comment by gromgit** [comment]
Wasn't `brew install /path/to/formula.rb` disabled quite some time ago?

In any case, for any `f=/path/to/tap/Formula/formula.rb`, a simple `brew install $(basename "$f" .rb)` should Do The Right Thing.

**Comment by evanphx** [comment]
The current code supports the ability to install formulas by path. If the expectation is that is going away, then this can be closed in favor of knowing that there is a number of comments and cleanups that will need to occur (as the code makes reference to the ability to load a formula by path).

In my (albiet extremely niche) case, I need to be able to install the core forumlas by path. I don't expect homebrew to bend to my niche needs, but just want to clarify how these behavior should interact.

**Comment by carlocab** [comment]
Yes, I don't think we support installing formulae by referencing a path to a formula file is supported anymore. We could probably make the error more informative.

Why do you need to install formulae using paths?

**Comment by evanphx** [comment]
Installing by path I'm sure is used by recipe authors as well.

**Comment by evanphx** [comment]
The code probably needs to remove that functional to avoid this strange case.

For me specifically, I'm building a package manager that "chainloads" to homebrew, bypassing the tap system entirely. Again, I don't expect you all to support anything that doesn't make sense for your core usecases.

**Comment by MikeMcQuaid** [comment]
> Yes, I don't think we support installing formulae by referencing a path to a formula file is supported anymore.

Unless it's documented behaviour (in which case the documentation should be updated/removed): this is a Homebrew implementation detail you should not rely on. I don't see evidence that the code needs changed.
