### ISSUE TITLE
Allow pinning casks

### ISSUE THREAD

**Issue by rafalkrupinski** [Homebrew/brew#12425]
### Provide a detailed description of the proposed feature

As a user of package X, I'd like to be able to mark a version Y of that package as blacklisted for example, when it's buggy or incompatible with my environment.
If version Y is currently installed, it should be either updated (if available), downgraded (if available) or perhaps uninstalled as it's unresolvable.

### What is the motivation for the feature?

I use vagrant with virtualbox. The latest release has a bug that makes it not work in headless configuration.
That bug has been fixed in master and will be available in the next release

### How will the feature be relevant to at least 90% of Homebrew users?

Bugs and regressions may happen to any package

### What alternatives to the feature have been considered?

Manual install

**Comment by MikeMcQuaid** [comment]
`brew pin` provides this behaviour for formulae. We do not have something like this for casks. For both formulae or casks your best bet is to extract the formula or cask into your own external tap where it won't be updated without your intervention.

**Comment by rafalkrupinski** [comment]
> `brew pin` provides this behaviour for formulae. We do not have something like this for casks.

I know. Hence the feature request for it.

**Comment by carlocab** [comment]
You might be interested in https://github.com/buo/homebrew-cask-upgrade.

**Comment by MikeMcQuaid** [comment]
Reopening as a cask-specific request.

**Comment by miccal** [comment]
This has been discussed numerous times in the `homebrew-cask` repository, for example see the discussion in https://github.com/Homebrew/homebrew-cask/issues/90242.
