### ISSUE TITLE
Brew command to check architecture support on command line

### ISSUE THREAD

**Issue by samjijina** [Homebrew/brew#12420]
### Provide a detailed description of the proposed feature

A command which tells the user the supported architectures of any package.

Example: 
```
$ brew arch htop
htop        Apple Silicon
htop        x86
```

### What is the motivation for the feature?

With the transition of Apple device to Apple Silicon (ARM), there should be an easy way on the command line for the user to check if a package has native support for Apple Silicon before installing it.
It has been shown extensively that running x86 packages with Rosetta is not as performant as running natively.

For other users, knowing the intended architecture beforehand can also be useful.

### How will the feature be relevant to at least 90% of Homebrew users?

In general, checking architecture before install will be useful to several users as other devices are also moving to AArch64.

### What alternatives to the feature have been considered?

The alternative is to do a manual lookup of the package on the https://formulae.brew.sh/ website to check if it supports a particular architecture.

**Comment by carlocab** [comment]
You can also use `brew unbottled` which tells you if a formula is bottled on a specific OS/Arch pair.

**Comment by MikeMcQuaid** [comment]
> With the transition of Apple device to Apple Silicon (ARM), there should be an easy way on the command line for the user to check if a package has native support for Apple Silicon before installing it.

`brew info` contains `(bottled)` if it's bottled for this platform.
