### ISSUE TITLE
Why is git using macOS provided libcurl?

### ISSUE THREAD

**Issue by jmpolom** [Homebrew/brew#12486]
### Provide a detailed description of the proposed feature

It's pretty well known that Apple ships woefully out-of-date versions of many common open source utilities and system libraries. A manifestation of this is that git, even when installed via homebrew, cannot connect over http to TLS 1.3-only repos because the version of libcurl it's linked against (provided by macOS) uses a very outdated version of libressl lacking TLS 1.3 support.

It really doesn't make sense to me that homebrew's git would link against the macOS provided version of libcurl. All of the dependencies for git are also available via homebrew at versions that are more up-to-date than those provided by Apple. It seems more reasonable that those should be used instead of those provided by Apple especially with how notoriously out-of-date most of them tend to be. Certainly homebrew exists at least in part to deal with the shortcomings of Apple's included set of apps/libraries.

### What is the motivation for the feature?

Improved security and broader adoption of more modern TLS versions.

### How will the feature be relevant to at least 90% of Homebrew users?

TLS 1.3 is going to become more common in the immediate future.

### What alternatives to the feature have been considered?

Wait for Apple to get around to providing a version of openssl/libressl that support TLS 1.3?

**Comment by MikeMcQuaid** [comment]
> All of the dependencies for git are also available via homebrew at versions that are more up-to-date than those provided by Apple. It seems more reasonable that those should be used instead of those provided by Apple especially with how notoriously out-of-date most of them tend to be.

This goes against the original (and somewhat current) ethos of Homebrew where we actively try to use the system dependencies when they aren't irredeemably broken.

**Comment by carlocab** [comment]
You can use `brew extract` to maintain your own version of `git` that uses Homebrew `libcurl`.

**Comment by jmpolom** [comment]
@MikeMcQuaid I would completely disagree that the macOS included libressl/libcurl are not irredeemably broken. It doesn't support TLS 1.3 which has been a published IETF standard since 2018. Supporting the latest cryptographic standards when Apple has failed to do so really should be a priority here.

**Comment by Bo98** [comment]
Do you have an example Git repository that's TLS 1.3 only? I've not yet seen one in any of our homebrew-core formulae. Xiph for one has gone TLS 1.3 only for their website but not their git repos.

**Comment by jmpolom** [comment]
For some context, our organization (in a security conscious industry) was looking to re-deploy our internal gitlab instance as TLS 1.3 only. This is a reasonable choice given the wide support for TLS 1.3 in recent versions of upstream ssl libraries. No issues were encountered on Windows or Linux clients when TLS 1.3 was the only transport allowed. Coinciding with a move to TLS 1.3 was also going to be a sunsetting of ssh access for git on our private gitlab. Again, this is really a very reasonable decision from a security perspective given the excellent support git over https now has.

Issues arose only with macOS clients due to the causes described in this issue. While I appreciate that so far nobody seems to have reported a similar issue, I can assure you this is a real problem that is at present time preventing homebrew provided git from interacting with https endpoints that are leaning hard into newer cryptographic standards. This situation **will not** improve with age.

Based on the responses supplied here from @MikeMcQuaid to “deal with it; I don’t have a problem” and @carlocab to “fix it for yourself, our community can suffer alone all at once” I would agree that:

> Perhaps a different package manager would be a better fit for you.

I think it is time to move on to macports for me.

**Comment by carlocab** [comment]
I was actually quite sympathetic to your request, so it's rather appalling that you decided to misrepresent my suggestion to mean

> fix it for yourself, our community can suffer alone all at once

I was merely suggesting a fix that you can implement for yourself quite easily right away.

> I think it is time to move on to macports for me.

Good. I'd rather not have someone this discourteous and uncharitable using software I work on.

**Comment by jmpolom** [comment]
My apologies for misconstruing your statement. I didn’t really pickup on anything other than “this is how you can fix it yourself.” Coupled with the comments from @MikeMcQuaid, I perceived that it’s highly unlikely any changes to build git with homebrew provided libcurl would ever be incorporated upstream.

I don’t really see any value in solving this issue using `brew extract` only for myself since I could just as easily solve this issue for myself by using macports. I would only consider modifying the upstream package if I could contribute those changes back via a PR.

I did notice that some time ago there were [options](https://github.com/Homebrew/homebrew-core/blob/de207300210813de108f7248490068faf253ca7d/Formula/git.rb) to build git using or not using a variety of macOS provided libraries. Seems like those options were removed at some point between then and now.

**Comment by MikeMcQuaid** [comment]
> Based on the responses supplied here from @MikeMcQuaid to “deal with it; I don’t have a problem”

Alternatively: "I've been maintaining this macOS package manager for over a decade and have seen a lot of problems like this and the problem you are experiencing is a niche enough one that I'd rather not push another dependency on all of our users of one of most popular formulae".

You claimed this package was "irredeemably broken" and I pointed out my use-case which points out that it doesn't seem to be for me (or for most users who aren't complaining about this).
