### ISSUE TITLE
Fully parallel downloads on install

### ISSUE THREAD

**Issue by soshimee** [Homebrew/brew#12489]
### Provide a detailed description of the proposed feature

Fully parallel downloads, which can be limited or disabled using arguments upon package installation.

Now, while installing packages, it downloads dependencies one-by-one then installs. The new method is to download them all at once, or n of them at once.

### What is the motivation for the feature?

Packages with a lot of dependencies take forever to download because of how all the downloads are linear right now.

### How will the feature be relevant to at least 90% of Homebrew users?

When installing a package with a lot of small dependencies, many people often get delayed because of the server's response time. With a reasonable internet connection, parallel downloads are much faster. 

### What alternatives to the feature have been considered?

Less ping to servers, but it isn't viable in many times due to physical locations or server's capacity to handle requests.

**Comment by MikeMcQuaid** [comment]
Sorry, not going to do this. Almost all downloads are from GitHub so it'll add a bunch of complexity on our side and make it much harder on their servers.
