### ISSUE TITLE
Brew audit failing on homebrew/brew:latest 

### ISSUE THREAD

**Issue by dmurray-lacework** [Homebrew/brew#12506]
### `brew config` output

```shell
brew config >
HOMEBREW_VERSION: 3.3.6ORIGIN: https://github.com/Homebrew/brewHEAD: 32a3e1fe28f9372a6c6d5eca52129f92b0f00ba0Last commit: 4 days agoCore tap ORIGIN: https://github.com/Homebrew/homebrew-coreCore tap HEAD: 65fd189d10044bfb5dcfb2f7f4734e5d2b31b36bCore tap last commit: 3 days agoCore tap branch: masterHOMEBREW_PREFIX: /home/linuxbrew/.linuxbrewHOMEBREW_CASK_OPTS: []HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-coreHOMEBREW_MAKE_JOBS: 16Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/rubyCPU: 16-core 64-bit skylakeClang: N/AGit: 2.34.1 => /bin/gitCurl: 7.68.0 => /bin/curlKernel: Linux 5.4.129-63.229.amzn2.x86_64 x86_64 GNU/LinuxOS: Ubuntu 20.04.3 LTS (focal)Host glibc: 2.31/usr/bin/gcc: 9.3.0/usr/bin/ruby: N/Aglibc: N/Agcc@5: N/Axorg: N/A---------------------------
```

### `brew doctor` output

```shell
No output from brew doctor
brew doctor >
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run brew audit in CI pipeline.
Using image homebrew/brew:latest 

`brew audit --formula <formula> --strict`
The audit pipeline is triggered, whenever the formula is updated.

The last passing image is homebrew/brew:3.3.4

### What happened (include all command output)?

The following error output is produced:

```
brew audit --formula <formula> --strict                                                                                                            
==> Installing 'bundler' gem                                                                                                                                     
Fetching bundler-1.17.3.gem                                                                                                                                      
Error: undefined method `path' for nil:NilClass                                                                                                                  
Did you mean?  paths                                                                                                                                             
Please report this issue:                                                                                                                                        
  https://docs.brew.sh/Troubleshooting                                                                                                                           
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_auditor.rb:124:in `audit_synced_versions_formulae'                                                  
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_auditor.rb:823:in `block in audit'                                                                  
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_auditor.rb:818:in `each'                                                                            
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_auditor.rb:818:in `audit'                                                                           
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/audit.rb:185:in `block in audit'                                                                    
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/audit.rb:169:in `map'                                                                               
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/audit.rb:169:in `audit'                                                                             
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>' 
```

### What did you expect to happen?

I expected brew audit command to return no linting issues.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- On homebrew/brew:latest image 
- From the directory containing the brew formula
- Run `brew audit --formula <formula> --strict`
```

**Comment by Bo98** [comment]
I'll get it fixed, but it's worth noting that this only happens if you are auditing a formula which does not live in any tap.

**Comment by carlocab** [comment]
> it's worth noting that this only happens if you are auditing a formula which does not live in any tap.

This is important because formulae are meant to work if they live in a tap. There are many other things that could be broken for formulae that don't.

**Comment by dmurray-lacework** [comment]
Hey @Bo98 here is a link to the tap -> https://github.com/lacework/homebrew-tap if it helps.
You may be right and I'm using the audit command incorrectly, any further information would be appreciated

**Comment by carlocab** [comment]
Do you do `brew audit /path/to/lacework-cli.rb` or `brew audit lacework-cli`? The latter will work, but the former is going to run into some weird edge cases like this one (among others).

**Comment by Bo98** [comment]
I'm not sure your exact CI setup, but it should work if the repo is in the correct place (`$(brew --repo)/Library/Taps`). Just did this and it worked fine:

```sh
brew tap lacework/tap
cd $(brew --repo lacework/tap)
make lint-cli
```

**Comment by dmurray-lacework** [comment]
Hey @carlocab,  the intent is to run the first use case you've specified (Audit the changed formula before pushing changes to main). This was running in CI prior to the [3.3.5](https://github.com/Homebrew/brew/releases/tag/3.3.5) release.

**Comment by carlocab** [comment]
I may have been unclear: the former (using a path to a `.rb` file) is not a supported use case. The fact that it used to work was just a happy coincidence, but please don't take it to mean that it was designed to work the way you were using it.

**Comment by dmurray-lacework** [comment]
👍 @carlocab , Would you mind pointing me in the right direction to any docs or example for my scenario and we can close this ticket.
We want to run linting against the formula, which has been updated via script, before pushing to main. What is the best way to audit this formula?

**Comment by gromgit** [comment]
Create your own tap, put the formula in it, then you can do all the Homebrew-dev stuff on it:
```
brew tap-new --no-git dmurray-lacework/tap
mv my_formula.rb $(brew --repo dmurray-lacework/tap)/Formula
brew audit dmurray-lacework/tap/my_formula
```

**Comment by lbergelson** [comment]
I also ran into this problem and was confused by it.  I (and I suspect many others) have been developing changes to formula for years outside of taps without knowing that could cause issues.  All of the commands accept a direct file path without any indication that that might not be a good idea.  

It might be good to reopen this issue this until a solution (or better error message) is in place since I initially missed it when scanning open issues.

**Comment by Bo98** [comment]
Yes I do plan to fix this to make it still work for non-taps. For those making taps though I still recommend what I said above.

**Comment by lbergelson** [comment]
@Bo98 Thank you.  I don't mind changing my workflow, I just never realized it wasn't the supported path.

**Comment by MikeMcQuaid** [comment]
@Bo98 I'd actually like us to consider going the opposite and deprecating and eventually disabling/removing this behaviour. We don't recommend it, it breaks often and we should instead point people to the right way of doing it instead.

**Comment by Bo98** [comment]
I'm fine with deprecating but that's a long term fix and we will still need to fix this issue for the short term. I'll open a PR with such fix this afternoon.
