### ISSUE TITLE
brew update returning errors on macos 11.6.1 2013 MacPro

### ISSUE THREAD

**Issue by MadBomber** [Homebrew/brew#12503]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.6-31-gbe908f6
ORIGIN: https://github.com/Homebrew/brew
HEAD: be908f679dc18cb45706921cde45bfde9c1514d6
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 947f3a3e4f3c67f0037aacfcbd85873683e1a151
Core tap last commit: 85 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: subl -w
HOMEBREW_MAKE_JOBS: 24
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: 24-core 64-bit ivybridge
Clang: 13.0.0 build 1300
Git: 2.34.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.1-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: 13.1
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
  pdf2htmlex

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew update ... because that's what I do in the middle of the week.

This problem has existed for several weeks.  I can not pinpoint a specific event that might have caused the problem.  I did attempt to do a MacOS update to 12.0.1 which failed because my MacPro (trash can -late 2013) does not have an Apple SSD which is required on this platform by the new OS because of a firmware update.  However, I recall having this brew update problem before my failed MacOS update attempt.

### What happened (include all command output)?

16:34:52 3.0.3p157  s5:~ $ brew update
fatal: bad object refs/remotes/origin/default.profraw
error: https://github.com/Homebrew/homebrew-services did not send all necessary objects

Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services failed!
16:36:20 3.0.3p157  s5:~ $

### What did you expect to happen?

No error messages.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
```

**Comment by Bo98** [comment]
Looks like something on your system has placed a random file in the `homebrew-services` git directory.

I don't know what it is so I suggest `rm $(brew --repo homebrew/services)/.git/refs/remotes/origin/default.profraw`

**Comment by MadBomber** [comment]
Bo, your suggestion cleared up the mess.

16:36:20 3.0.3p157  s5:~ $ rm $(brew --repo
homebrew/services)/.git/refs/remotes/origin/default.profraw
remove
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/.git/refs/remotes/origin/default.profraw?
y
17:05:59 3.0.3p157  s5:~ $ brew update
Updated Homebrew from be908f679 to b0a0a0020.
Updated 1 tap (homebrew/services).
No changes to formulae.
17:06:19 3.0.3p157  s5:~ $


Dewayne
  o-*
