### ISSUE TITLE
Keg.relocate_text_files performance is awful

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/brew#1250]
`Keg.relocate_text_files` reads every single text file and libtool file in a bottle, replaces the cellar, prefix and repository placeholders (if any), and rewrites the files that need modifications. This process is single-handedly inflating bottle pouring time 10–100 times. A few examples I tested:

- `git`: untar ~0.3s, relocate text files ~6s;
- `go`: untar ~1.6s, relocate text files ~70s;
- `mysql`: untar ~2.7s, relocate text files ~170s.

**Comment by MikeMcQuaid** [comment]
@zmwangx Thanks for filing this!

**Comment by jawshooah** [comment]
Looks like we're currently doing [three separate passes](https://github.com/Homebrew/brew/blob/e851c9bf6c3adda268f1a307d6b49acb1ad1852d/Library/Homebrew/keg_relocate.rb#L28-L30) over each file when we could just do one with multiple replacements. Not an asymptotic improvement, but ~3x isn't bad.

**Comment by jawshooah** [comment]
Scratch that; looks like the real bottleneck is in `text_files`, particularly [running `/usr/bin/file` on every file and parsing the output](https://github.com/Homebrew/brew/blob/e851c9bf6c3adda268f1a307d6b49acb1ad1852d/Library/Homebrew/keg_relocate.rb#L78). After some quick googling, I can't find a better way to determine whether a file is text or binary without bringing in external dependencies like [ruby-filemagic](https://rubygems.org/gems/ruby-filemagic/).

**Comment by MikeMcQuaid** [comment]
A few options:
- do that in parallel to try and speed it up
- cache the files we actually rewrite in `bottle.rb` and store them with inside the bottle
