### ISSUE TITLE
compile yaz with GnuTLS support

### ISSUE THREAD

**Issue by adamdickmeiss** [Homebrew/brew#12511]
### Provide a detailed description of the proposed feature

Configure yaz with `--with-gnutls` and depend on gnutls package.

### What is the motivation for the feature?

With GnuTLS support in YAZ, it can work with HTTPS. Without GnuTLS only HTTP is supported.

### How will the feature be relevant to at least 90% of Homebrew users?

Many URLs these days are HTTPS-based, so this will improve the usage of the YAZ library when it much fetch content from those sites.

### What alternatives to the feature have been considered?

None. Only with GnuTLS yaz will be able to work with HTTPs-links.

**Comment by carlocab** [comment]
This issue tracker is for the `brew` CLI tool, and not for formulae hosted at https://github.com/Homebrew/homebrew-core.

If you'd like to see a change to a formula, please open a pull request there.
