### ISSUE TITLE
Shame on you losers

### ISSUE THREAD

**Issue by ghost** [Homebrew/brew#12519]
### Provide a detailed description of the proposed feature

Shame on you for making that dumb second command (after `brew update`) mentioned in this thread #8550. Shame on you @Sulcalibur for stating that disgusting word after `brew` in your garbage thread.
TO HELL WITH THE LOSERS WHO DEVELOP BREW, WHO MADE THAT DUMB COMMAND. You are cheap worthless slaves, who have no ethics and no brain. TO HELL WITH "universities". TO HELL WITH IDIOTS WHO USE DAFT AND ARROGANT "TITLES" WITH NAMES. SHAME ON YOU ALL
Brew is a garbage project made by losers. Hope the people who came up with the command mentioned in #8550 get destroyed.

### What is the motivation for the feature?

Shame on you for making that dumb second command (after `brew update`) mentioned in this thread #8550. Shame on you @Sulcalibur for stating that disgusting word after `brew` in your garbage thread.
TO HELL WITH THE LOSERS WHO DEVELOP BREW, WHO MADE THAT DUMB COMMAND. You are cheap worthless slaves, who have no ethics and no brain. TO HELL WITH "universities". TO HELL WITH IDIOTS WHO USE DAFT AND ARROGANT "TITLES" WITH NAMES. SHAME ON YOU ALL
Brew is a garbage project made by losers. Hope the people who came up with the command mentioned in #8550 get destroyed.

### How will the feature be relevant to at least 90% of Homebrew users?

Shame on you for making that dumb second command (after `brew update`) mentioned in this thread #8550. Shame on you @Sulcalibur for stating that disgusting word after `brew` in your garbage thread.
TO HELL WITH THE LOSERS WHO DEVELOP BREW, WHO MADE THAT DUMB COMMAND. You are cheap worthless slaves, who have no ethics and no brain. TO HELL WITH "universities". TO HELL WITH IDIOTS WHO USE DAFT AND ARROGANT "TITLES" WITH NAMES. SHAME ON YOU ALL
Brew is a garbage project made by losers. Hope the people who came up with the command mentioned in #8550 get destroyed.

### What alternatives to the feature have been considered?

Shame on you for making that dumb second command (after `brew update`) mentioned in this thread #8550. Shame on you @Sulcalibur for stating that disgusting word after `brew` in your garbage thread.
TO HELL WITH THE LOSERS WHO DEVELOP BREW, WHO MADE THAT DUMB COMMAND. You are cheap worthless slaves, who have no ethics and no brain. TO HELL WITH "universities". TO HELL WITH IDIOTS WHO USE DAFT AND ARROGANT "TITLES" WITH NAMES. SHAME ON YOU ALL
Brew is a garbage project made by losers. Hope the people who came up with the command mentioned in #8550 get destroyed.

**Comment by iMichka** [comment]
I’m leaving the original message above so everyone can see with what we have to deal with as maintainers …

**Comment by MikeMcQuaid** [comment]
> Brew is a garbage project made by losers.

Actually, we prefer British English here so it's a rubbish project made by losers.
