### ISSUE TITLE
Error when listing brew services or making brew bundle dump

### ISSUE THREAD

**Issue by avenue9977** [Homebrew/brew#12526]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 32a3e1fe28f9372a6c6d5eca52129f92b0f00ba0
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 14cdf31f7d93847c8e6e5999cc4104f5076c7d5d
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to run `brew bundle dump --force --describe` and also `brew services list`

### What happened (include all command output)?

```
Error: undefined method `timed?' for #<Homebrew::Service:0x0000000126ee4298>
Did you mean?  tainted?
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:42:in `timed?'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:176:in `to_hash'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `map'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `services_list'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:13:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:86:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### What did you expect to happen?

Overwrite my Brewfile or list the brew services

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bundle dump --force --describe

or

brew services list
```

**Comment by MikeMcQuaid** [comment]
CC @SMillerDev for regression

**Comment by MikeMcQuaid** [comment]
@SMillerDev sorry, hadn't seen your open PR yet.

@avenue9977 can you try to `brew update` and see if you can still reproduce?

**Comment by AiAe** [comment]
@MikeMcQuaid having the same issue on that version, tried brew update and upgrade nothing resolved it.

**Comment by ishetnogferre** [comment]
@MikeMcQuaid same here.
If it helps:

**brew doctor** 
`Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.4`


**brew config**
`HOMEBREW_VERSION: 3.3.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: dbec9de77ebc65a4845a5e672950219aa19b35b8
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 370fa976f6966d510bb71c09323199be17163396
Core tap last commit: 27 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: 13.1
Rosetta 2: false`

**Comment by SMillerDev** [comment]
@ishetnogferre can you run `brew services list` again and post the output?

**Comment by avenue9977** [comment]
@SMillerDev 
Restarting the laptop resolved the issue for me also.
