### ISSUE TITLE
`_brew: function definition file not found` by pressing the Tab key

### ISSUE THREAD

**Issue by alphavector** [Homebrew/brew#12525]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 32a3e1fe28f9372a6c6d5eca52129f92b0f00ba0
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 445d34e2c60e29ea9d41ce7ce1c01745fdc0ce69
Core tap last commit: 59 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I press `Tab` after the brew command and get this error. I tried uninstalling and reinstalling brew, but the error won't go away

### What happened (include all command output)?

```
~ > brew                                                               20:05:17
(eval):1: _brew: function definition file not found
(eval):1: _brew: function definition file not found
(eval):1: _brew: function definition file not found
```

### What did you expect to happen?

proposed command selection

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
simply type `brew` and press the Tab key
```

**Comment by alphavector** [comment]
I added the lines below to `~/.zshrc` and everything worked
```
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi
```
It is not clear why brew did not do this itself when installing

**Comment by carlocab** [comment]
> It is not clear why brew did not do this itself when installing

Is the explanation given in [the documentation](https://docs.brew.sh/Shell-Completion) not clear?
