### ISSUE TITLE
Error installing php@7.3

### ISSUE THREAD

**Issue by asentner** [Homebrew/brew#12549]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: dbec9de77ebc65a4845a5e672950219aa19b35b8
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 28c26da4bfa09f96d89794af3d877dff5ea28dd1
Core tap last commit: 35 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.1-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: 13.1
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install -v php@7.3`

### What happened (include all command output)?

Error: php@7.3 has been disabled because it is a versioned formula!

### What did you expect to happen?

The package should have installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install -v php@7.3
```

**Comment by Bo98** [comment]
We should probably improve the error message here. The reason is that PHP 7.3 has now reached end-of-life.
