### ISSUE TITLE
Slim down the brew taps by removing .git folder

### ISSUE THREAD

**Issue by vfilimonov** [Homebrew/brew#12556]
### Provide a detailed description of the proposed feature

At the moment the taps (/usr/local/Homebrew/Library/Taps/homebrew) at my machine are over 1Gb.
In each of the taps the most of space is taken by .git folders
homebrew-cask: 340 Mb of 360 Mb
homebrew-cask-versions: 76Mb of 77 Mb
homebrew-core: 590Mb of 620 Mb

While I understand that git is in the core functionality of the homebrew, removing of .git and keeping only the latest commit would save a lot of space.

### What is the motivation for the feature?

Reducing the space for taps by 95%.

### How will the feature be relevant to at least 90% of Homebrew users?

Reducing the space for taps by 95%.

### What alternatives to the feature have been considered?

Please let me know if there's an alternative or a workaround.

**Comment by gromgit** [comment]
The [`HOMEBREW_INSTALL_FROM_API` environment variable](https://docs.brew.sh/Manpage#environment) was [introduced in v3.3.0](https://brew.sh/2021/10/25/homebrew-3.3.0/) about two months ago.

**Comment by MikeMcQuaid** [comment]
> The [`HOMEBREW_INSTALL_FROM_API` environment variable](https://docs.brew.sh/Manpage#environment) was [introduced in v3.3.0](https://brew.sh/2021/10/25/homebrew-3.3.0/) about two months ago.

Yup, this is the feature that will address this. I recommend testing it out.

**Comment by vfilimonov** [comment]
Thank you @MikeMcQuaid @gromgit 

After setting `HOMEBREW_INSTALL_FROM_API=1` could I simply erase `/usr/local/Homebrew/Library/Taps/` or will it have some unintended consequences?

**Comment by Rylan12** [comment]
You should instead run `brew untap homebrew/core` and `brew untap homebrew/cask`. Those are currently the only two taps that are supported by `HOMEBREW_INSTALL_FROM_API` so you'd lose the ability to use any other taps by removing that directory. However, the good news is that those two are by far the biggest taps so it should still make a difference.

**Comment by vfilimonov** [comment]
Great, thanks a lot for the prompt response @Rylan12 !
