### ISSUE TITLE
Make entire output of "brew outdated" grep-able

### ISSUE THREAD

**Issue by katrinleinweber** [Homebrew/brew#12554]
### Provide a detailed description of the proposed feature

Version numbers are currently not written to stdout or stderr, apparently, but formulae or cask names are:

```
$ brew outdated
gitleaks (8.1.3) < 8.2.0
terraform (1.0.11) < 1.1.0

$ brew outdated | grep git
gitleaks

$ brew outdated | grep '.0'
# nothing
```

This problem is also mentioned in https://stackoverflow.com/questions/58344963/cant-redirect-all-homebrew-cask-outdated-output

Another example:

```
$ brew outdated | cut -d' ' -f1
gitleaks
terraform

$ brew outdated | cut -d' ' -f2-
gitleaks
terraform
```

### What is the motivation for the feature?

I'd like to be able to use custom shell aliases or functions with `grep` to for example highlight some SemVer patterns for special attention. E.g., upgrading anything that matches `\.[1-9]\d*$` first.

### How will the feature be relevant to at least 90% of Homebrew users?

Making `brew` output more consistently usable with other UNIX tools.

### What alternatives to the feature have been considered?

Custom `script`ing like https://stackoverflow.com/a/62682938/4341322

**Comment by MikeMcQuaid** [comment]
> $ brew outdated | grep git
> gitleaks

`brew outdated --verbose` which matches the output of `brew outdated` when not connected to a TTY. Alternatively, use `brew outdated --json` and `jq`. We cannot change the default output to avoid breaking scripts that already rely on that behaviour e.g. `brew info $(brew outdated)`.
