### ISSUE TITLE
Private Registry and Cask issues with Download Strategy

### ISSUE THREAD

**Issue by byjrack** [Homebrew/brew#12568]
### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 3.3.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3f0b412951996a675b8a48037e9a978f0ccd8363
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6ee17887b040b961ba433fb147e22650173320aa
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_ARTIFACT_DOMAIN: <private registry>
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DOCKER_REGISTRY_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

### `brew doctor` output

```shell
brew doctor                 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
  php@7.3
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Using HOMEBREW_ARTIFACT_DOMAIN I want to provide a private homebrew registry for my associates.  Works great for Formulae and Bottles, but Cask resource URLs get munged up by the current download strategy.

### What happened (include all command output)?

The ARTIFACT_DOMAIN seems to be getting prefixed to all URLs and not just GHCR.io.  

```
brew upgrade powershell
Password:
==> Upgrading 1 outdated package:
powershell 7.1.5 -> 7.2.1
==> Upgrading powershell
==> Caveats
To use Homebrew in PowerShell, set:
  Add-Content -Path $PROFILE.CurrentUserAllHosts -Value '$(/usr/local/bin/brew shellenv) | Invoke-Expression'

==> Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/powershell-7.2.1-osx-x64.pkg
==> Downloading from <private registry>/https://github.com/PowerShell/PowerShell/r
#=#=#                                                                         
curl: (22) The requested URL returned error: 400 
==> Purging files for version 7.2.1 of Cask powershell
Error: powershell: Download failed on Cask 'powershell' with message: Download failed: https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/powershell-7.2.1-osx-x64.pkg

brew upgrade pgadmin4
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Upgrading 1 outdated package:
pgadmin4 6.0 -> 6.2
==> Upgrading pgadmin4
==> Downloading https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v6.2/macos/pgadmin4-6.2.dmg
==> Downloading from <private registry>/https://ftp.postgresql.org/pub/pgadmin/pga
#=#=#                                                                         
curl: (22) The requested URL returned error: 400 
==> Purging files for version 6.2 of Cask pgadmin4
Error: pgadmin4: Download failed on Cask 'pgadmin4' with message: Download failed: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v6.2/macos/pgadmin4-6.2.dmg
```

### What did you expect to happen?

The formula would be sourced from the private registry, but the Cask will need to be sourced using whatever protocol and location that was provided in the formula.

So not a ruby developer or familiar with the codebase so the patch may be obvious, but feels like there should be an additional check in https://github.com/Homebrew/brew/blob/371122da557d770aa4555f258a904aa008f9ce8b/Library/Homebrew/download_strategy.rb#L454 to not adjust the URLs for casks.  Now I thought that url.sub wouldn't do anything unless it saw ghcr.io and in the Cask URL that will mostly not be ghcr.io so not sure why the URL is being prefixed.  And also can't find any other uses.

I am unsure if Casks are classed pourable or if in the download context we know who the caller was and could != casks.  I just don't see a scalable model for handling Casks in the private registry without that registry provider being very dynamic and rewriting the formulae dynamically while also fetching the resource from the Cask provider.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just run brew upgrade of any cask w ARTIFACT_DOMAIN configured.
```

**Comment by MikeMcQuaid** [comment]
The behaviour here matches the docs:
```
HOMEBREW_ARTIFACT_DOMAIN
       Prefix all download URLs, including those for bottles, with this value. For
       example, HOMEBREW_ARTIFACT_DOMAIN=http://localhost:8080 will cause a formula
       with the URL https://example.com/foo.tar.gz to instead download from
       http://localhost:8080/example.com/foo.tar.gz.
```
https://docs.brew.sh/Manpage#environment

As a result, this is intentional behaviour so closing.

> The formula would be sourced from the private registry, but the Cask will need to be sourced using whatever protocol and location that was provided in the formula.

This artefact domain is designed to support e.g. transparent/passthrough proxies. I'm not sure I understand why they should work for just GitHub Packages and not other things.

We cannot change this because people rely on the behaviour you do not want.

**Comment by byjrack** [comment]
Got it @MikeMcQuaid that was helpful.  I was using this via Artifactory (I believe this support came from them) which didn't seem to support simple proxying like Squid and was failing.  I read the manpage and agreed sourcing via Formula coords was the goal (I read as unmodified though), but didn't connect the dots that env was designed for using an agnostic HTTP proxy for all things and not an opinionated one like the OCI implementation in Arti which is how we are configured.
