### ISSUE TITLE
`brew tests` is failing with a Bundler checksum error

### ISSUE THREAD

**Issue by alyssais** [Homebrew/brew#1256]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

---

This looks like it's causing all of the CI builds to fail.

<details>
  <summary><kbd>brew tests</kbd></summary>
  <pre>$ brew tests
Fetching gem metadata from https://rubygems.org/.
Retrying fetcher due to error (2/4): Bundler::HTTPError The checksum of /info/rake does not match the checksum provided by the server! Something is wrong (local checksum is "\"c883c268f189125ef7f8bb710c8f6ac4\"", was expecting "W/\"c883c268f189125ef7f8bb710c8f6ac4\"")..
Retrying fetcher due to error (3/4): Bundler::HTTPError The checksum of /info/url does not match the checksum provided by the server! Something is wrong (local checksum is "\"9da72ec7d77924fbe04ef93fdfd39719\"", was expecting "W/\"9da72ec7d77924fbe04ef93fdfd39719\"")..
Retrying fetcher due to error (4/4): Bundler::HTTPError The checksum of /info/codecov does not match the checksum provided by the server! Something is wrong (local checksum is "\"531fe865c145e807fd149e7d1ab66d1e\"", was expecting "W/\"531fe865c145e807fd149e7d1ab66d1e\"")....
Fetching version metadata from https://rubygems.org/..
Retrying fetcher due to error (2/4): Bundler::HTTPError The checksum of /info/RubyInline does not match the checksum provided by the server! Something is wrong (local checksum is "\"b3dacb8250b6b0e27513ba100169ad0e\"", was expecting "W/\"b3dacb8250b6b0e27513ba100169ad0e\"").......
Retrying fetcher due to error (3/4): Bundler::HTTPError The checksum of /info/ZenTest does not match the checksum provided by the server! Something is wrong (local checksum is "\"f58b1bf894ef8305d7dc93b3b39f9ccb\"", was expecting "W/\"f58b1bf894ef8305d7dc93b3b39f9ccb\"")......
Retrying fetcher due to error (4/4): Bundler::HTTPError The checksum of /info/rbnacl does not match the checksum provided by the server! Something is wrong (local checksum is "\"a24fdeb1b792cbd52855baa1ff7123fe\"", was expecting "W/\"a24fdeb1b792cbd52855baa1ff7123fe\"")..The checksum of /info/spruz does not match the checksum provided by the server!
Something is wrong (local checksum is "\"ddabf75dc4e2c5c4433f50fd7c0c9a9e\"",
was expecting "W/\"ddabf75dc4e2c5c4433f50fd7c0c9a9e\"").
bundler: command not found: parallel_test
Install missing gem executables with `bundle install`</pre>
</details>

**Comment by alyssais** [comment]
Looks like a build just passed, so I guess this has gone away now.

**Comment by MikeMcQuaid** [comment]
RubyGems blip, I guess. Thanks for filing anyway!
