### ISSUE TITLE
Add basic auth capability for private Docker registries

### ISSUE THREAD

**Issue by thomvaill** [Homebrew/brew#12574]
### Provide a detailed description of the proposed feature

Today, thanks to https://github.com/Homebrew/brew/pull/11766, only bearer tokens are supported to authenticate against a private Docker registry. Configuration example:

```bash
export HOMEBREW_ARTIFACT_DOMAIN=https://artifactory.your-company.com/artifactory/brew-remote
export HOMEBREW_DOCKER_REGISTRY_TOKEN=<artifactory-access-token>
````

I propose to implement the support of basic authentication. Configuration example of my proposal:

```bash
export HOMEBREW_ARTIFACT_DOMAIN=https://artifactory.your-company.com/artifactory/brew-remote
export HOMEBREW_DOCKER_REGISTRY_BASIC_USER=<username>
export HOMEBREW_DOCKER_REGISTRY_BASIC_PWD=<password>
````

... which would send an `Authorization: Basic ...`  header instead of a Bearer one:
https://github.com/Homebrew/brew/blob/371122da557d770aa4555f258a904aa008f9ce8b/Library/Homebrew/download_strategy.rb#L599

### What is the motivation for the feature?

In our case we use Artifactory as a mirror. It supports both authentication methods:

- [access token](https://www.jfrog.com/confluence/display/JFROG/Access+Tokens) (Bearer)
- [username / API key](https://www.jfrog.com/confluence/display/JFROG/User+Profile#UserProfile-APIKey) (Basic)

However, only super admins can generate access tokens that don't expire.
Regular users can only generate access tokens with a 3600s duration maximum.
On the other hand, regular users can generate a random API key that can be used as a password in a basic auth that doesn't expire.

Also, many other Docker registries only support basic auth.

### How will the feature be relevant to at least 90% of Homebrew users?

The support of this feature will really help using homebrew in large companies where you are behind a proxy and you are forced to use a mirror like Artifactory with restricted permissions.

### What alternatives to the feature have been considered?

Today we developed this wrapper around homebrew that automatically refreshes Artifactory's access token when it's expired.
The dev experience becomes quite decent, but it's still hacky.

Snippet to include in your `~/.zshrc` or equivalent:

```bash
export HOMEBREW_ARTIFACT_DOMAIN=https://artifactory.your-company.com/artifactory/brew-remote

brewtoken() {
  if [[ -f ~/.brewtoken.sh ]]; then
    source ~/.brewtoken.sh
  fi

  if [[ ! -z "${BREWTOKEN_TS:-}" && "${1:-}" != "--force" ]]; then
    if [[ $(( $(date +%s) - $BREWTOKEN_TS )) -le 3300 ]]; then
      # Token not expired > we silently exit
      return
    fi
  fi

  >&2 echo "Requesting access token from Artifactory..."
  local rtRes=$(jfrog rt access-token-create)
  local rtAccessToken=$(echo "${rtRes}" | tr -d ' ' | grep -o '"access_token":"[^"]*"' | tr -d \" | sed 's/^access_token://') # we cannot use jq because we need homebrew to install it :-)
  if [[ -z "${rtAccessToken}" ]]; then
    >&2 echo "Failed to fetch access token:"
    >&2 echo "${rtRes}"
    return 1
  fi

  echo "export BREWTOKEN_TS=$(date +%s)" > ~/.brewtoken.sh
  echo "export HOMEBREW_DOCKER_REGISTRY_TOKEN=\"${rtAccessToken}\"" >> ~/.brewtoken.sh
  source ~/.brewtoken.sh
}

brew() {
  if [[ "${1:-}" =~ 'install|upgrade|reinstall|fetch|formulae|search|update' ]]; then
    brewtoken
  fi
  /usr/local/bin/brew $@
}
```

... and you first have to install the [JFrog CLI](https://jfrog.com/fr/getcli/) and execute `jfrog config add` to set your credentials up
(if you don't want to, you can rewrite the script above with simple curl calls)

**Comment by MikeMcQuaid** [comment]
Will review a pull request for this.

**Comment by thomvaill** [comment]
Unfortunately I don't have any Ruby skills, so if someone's willing to open a PR, go on :)
Otherwise, I can give it a try in my free time later

**Comment by prathamaror** [comment]
> Unfortunately I don't have any Ruby skills, so if someone's willing to open a PR, go on :) Otherwise, I can give it a try in my free time later

I would like to work on this issue
