### ISSUE TITLE
brew tap --full <repo> failing 

### ISSUE THREAD

**Issue by jweyer8** [Homebrew/brew#12581]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3f0b412951996a675b8a48037e9a978f0ccd8363
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2d78cf0cf152ee08c765c3a6c483c6a44a85577e
Core tap last commit: 43 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.1-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

trying to use `brew tap --full` or `brew tap --shallow`. The Chef.io built-in homebrew resources are failing because these options aren't working. 

### What happened (include all command output)?

Calling `brew tap --full` is disabled! There is no replacement.
Calling `brew tap --shallow` is disabled! There is no replacement.

### What did you expect to happen?

The brew man page still indicates support for these options.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
executing `brew tap --full <repo>` will reproduce this error.
```

**Comment by Rylan12** [comment]
> Calling `brew tap --full` is disabled! There is no replacement.
>
> Calling `brew tap --shallow` is disabled! There is no replacement.

As the output that you posted said, these commands are disabled. They're being removed from the help page and documentation in #12583.

**Comment by MikeMcQuaid** [comment]
> trying to use `brew tap --full` or `brew tap --shallow`. The Chef.io built-in homebrew resources are failing because these options aren't working.

Please also note: this `--full` option can be removed because `--full` is now the default behaviour.
