### ISSUE TITLE
bash completion freeze for 'brew info'

### ISSUE THREAD

**Issue by zh-lab** [Homebrew/brew#126]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:
Type 'brew info doc' then press tab to get auto completion, it freeze. After 15s I can get completion suggestion.

**Comment by apjanke** [comment]
Completing `brew info doc` is fast for me: well under 1 second to produce completions in `zsh`, and in `bash` it's an instant no-op.

Getting some more info about your setup would help us diagnose this. Could you post the results of `brew config`, `brew tap`, `brew doctor`, and `which _brew` as [a new gist](https://gist.github.com/)?

What shell are you running?

**Comment by zh-lab** [comment]
@apjanke 
I am running os x default terminal.
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

And here is https://gist.github.com/zh-lab/1b115479ca8a3693e795e2057a7b971c

**Comment by UniqMartin** [comment]
I can confirm that it also works without noticeable delay for me, both using the old system-provided Bash 3.2 as well as Bash 4.3 from Homebrew. Not sure what is going on there.

Does it make a difference if you're in a newly opened Terminal session or if that session is already open for an extended period of time (think several days/weeks)?

**Comment by zh-lab** [comment]
@UniqMartin A newly session also freeze.
@apjanke And I found that bash cpu usage grows over 90% very fast when I press tab to get completions.

**Comment by UniqMartin** [comment]
@zh-lab The formula completions are internally based on `brew search`. Can you check whether this command requires significant amounts of time to complete? Try

```
/usr/bin/time brew search > /dev/null
```

to measure the time and to suppress the normal output of that command. What does this output? Does the “real” time as printed by `time` approximately match the delay you're seeing with the completions?

Have you noticed other parts of the completions being unexpectedly slow? Do certain `brew` commands that you would usually expect to be fast have similarly noticeable delays? Thanks!

**Comment by zh-lab** [comment]
```
/usr/bin/time brew search > /dev/null

real	0m0.210s
user	0m0.169s
sys	0m0.036s
```

Does the “real” time as printed by time approximately match the delay you're seeing with the completions?
`No, not match.`

And `brew install `with completions also slow. It seems never success to get completions when 1st time to press tab. 😭

**Comment by UniqMartin** [comment]
> It seems never success to get completions when 1st time to press tab. 😭

That's expected behavior. It will only complete on first tab if the completion is unique. For example, if I type `brew info az<tab>`, it will almost immediately be completed to `brew info azure-cli` (because there's only one formula name starting with `az`). However, if I type `brew info al<tab>`, nothing will happen as there are multiple possible completions. I have to type `brew info al<tab><tab>` in this case to see a list of possible completions.

Sorry if you knew all that. I just wanted to make sure that this (expected behavior) is not the issue you're experiencing. If that's not the issue, I'm running out of ideas why the tab completion is slow for you.

**Comment by zh-lab** [comment]
@UniqMartin ok, thanks for your explanation about completions mechanism 😄 
But it is still slow when i try to get completions, not only for the 1st tab, but also for the 2nd, 3rd ....
```
3770  bash         99.0 02:22.58 1/1   0    17    9240K  0B     0B     3770 3769 running  *0[1]          0.00000 0.00000    501  28830+   2166    269       125       429175+   358       87128+    0      0
3769  login        0.0  00:00.01 3     1    30    1092K  0B     0B     3769 393  stuck    *0[9]          0.00000 0.00000    0    1359     162     192       68        1604      261       137       0      0
3734  bash         99.0 02:32.98 1/1   0    17    8948K  0B     0B     3734 3733 running  *0[1]          0.00000 0.00000    501  31029+   2378    314       147       466679+   413       97971+    0      0
```
And this bash cpu usage over 90%, is that an expected behavior?

**Comment by zh-lab** [comment]
@UniqMartin Just found that if I turn off the `Set locale environment variables on startup` in `terminal Preferences`, it will make help for the completions speed.

**Comment by UniqMartin** [comment]
> And this bash cpu usage over 90%, is that an expected behavior?

No, this shouldn't be happening. Clearly something is taking `bash` a long time to process, but we have yet to figure out what it is …

> Just found that if I turn off the “Set locale environment variables on startup” in “Terminal Preferences”, it will make help for the completions speed.

That's interesting. Can you please post the output of `env | egrep '^(LC_|LANG)'` both with that setting turned on and off? Thanks!

**Comment by zh-lab** [comment]
@UniqMartin 
> Can you please post the output of env | egrep '^(LC_|LANG)' both with that setting turned on and off?

Turn on
`LC_CTYPE=UTF-8`

Turn off
No response
`$?` return 1

**Comment by apjanke** [comment]
> `LC_CTYPE=UTF-8`

Strictly speaking, that's not a valid `LC_*` value. (It does happen on some systems, but I can't remember if that's a Linux-ism or an OSX-ism. I seem to recall it being a Linux thing.) It should be `en_US.UTF-8` or similar. (That is, `<language>_<region>.<encoding>`, not just `<encoding>`). I wonder if that is causing `bash` to do something pathological where it is repeatedly looking up locale-related stuff.

Could you try starting a session with "Set locale environment variables" enabled and doing an `export LC_CTYPE=en_US.UTF-8` and seeing if that fixes it?

And I wonder how that's getting set in the first place. What language did you set up OS X with on this machine? And what's the output of `locale` for you? E.g. I get this.

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

I tried setting `LC_CTYPE=UTF-8` in `bash` on my own 10.11 machine, and completion was still fast, so I couldn't reproduce this. Could be some interaction with something else, though.

**Comment by UniqMartin** [comment]
I also tried to reproduce the slowness, tested with both Bash 3.2 and 4.3 and various locale settings, but failed to observe the issue. I even tested with a Homebrew installation that has about 6,000 formulae (literally all official taps installed), but in all circumstances the response was fairly quick (< 1s) nonetheless. I'm afraid I'm running out of ideas …

Can you open a new Terminal, check that things are still unacceptably slow, and then enter the following commands individually one after the other?

```shell
cur="az" # The prefix that should be completed.
formulas="$(brew search)"
shortnames="$(echo "$formulas" | grep / | cut -d / -f 3)"
completions=($(compgen -W "$formulas $shortnames" -- "$cur"))
```

This is basically what is going on internally. I would expect that (on your system) one of those lines does take more time to complete than it should. If so, which one is it?

**Comment by apjanke** [comment]
You can also try doing the completion with `set -x` enabled if those steps don't identify anything. That'll show you a trace of its activity, and may be enough to identify where it's getting slow, or if it's doing something weird.

You could also try doing the same completions in `zsh` to see if it's shell specific.

And in either shell with `set -x` tracing enabled, if you set `$PS4` to something like `PS4='+ $(date "+%s.%N")\011 ->'` then you'll get timestamps in the execution trace log. Read it in to Excel as a tab-separated-value file, diff the timestamps in a new column, and you'll have execution times for each step.

**Comment by zh-lab** [comment]
normal one locale:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

slow one:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

And for this piece of script
```
cur="az" # The prefix that should be completed.
formulas="$(brew search)"
shortnames="$(echo "$formulas" | grep / | cut -d / -f 3)"
completions=($(compgen -W "$formulas $shortnames" -- "$cur"))
```
it's run very fast.

But while I do like this:
```
set -x
PS4='+ $(date "+%s.%N")\011 ->'
brew info doc #now press tab to get completions
```
It generates lots of output.
And I save this output to a file, it's about 184MB, is that an expected behavior? 
Sorry for missing this file here, because it's too big...:cry:

@apjanke @UniqMartin

**Comment by zh-lab** [comment]
@apjanke @UniqMartin btw, zsh works well, very fast.
And while doing this in zsh:
```
set -x
PS4='+ $(date "+%s.%N")\011 ->'
brew info doc #now press tab to get completions
```
output are very small, only 72KB.

**Comment by UniqMartin** [comment]
> It generates lots of output.
> And I save this output to a file, it's about 184MB, is that an expected behavior?

No, that's way too much. It means that a lot of stuff is happening (we just haven't found out yet, what it is) and that's why the processing is so slow in Bash.

Can you post the contents of your `.profile`, `.bashrc`, and `.bash_profile` files from your home directory? Some of those files may not exist. These files are used to set up every Bash session you start and maybe there's something in them that slows things down considerably. Before posting the contents, make sure the files don't contain any sensitive data you wouldn't want to share publicly.

> And while doing this in zsh:
> […snip…]
> output are very small, only 72KB.

This sounds about right. That's also approximately the size I get when I do the same in Bash on my system.

**Comment by zh-lab** [comment]
@UniqMartin 
This is my .bash_profile
```
# Go
export GOPATH=/Users/Heng/Workspace/go

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
```

**Comment by zh-lab** [comment]
And for the big output.
```
for file in '${taps}/*/*/*.rb' '${taps}/*/*/Formula/*.rb' '${taps}/*/*/HomebrewFormula/*.rb'
```
bash run this for 3819 times.

Just like this:
```
+ 1462065333.N	 ->for file in '${taps}/*/*/*.rb' '${taps}/*/*/Formula/*.rb' '${taps}/*/*/HomebrewFormula/*.rb'
+ 1462065333.N	 ->'[' -f /usr/local/Library/Taps/homebrew/homebrew-versions/iojs.rb ']'
+ 1462065333.N	 ->file=/usr/local/Library/Taps/homebrew/homebrew-versions/iojs.rb
+ 1462065333.N	 ->file=/usr/local/Library/Taps/homebrew/homebrew-versions/iojs.rb
+ 1462065333.N	 ->file=homebrew/homebrew-versions/iojs.rb
+ 1462065333.N	 ->file=homebrew/homebrew-versions/iojs
+ 1462065333.N	 ->file=homebrew/versions/iojs
+ 1462065333.N	 ->tf=' homebrew/versions/allegro4 homebrew/versions/android-ndk-r10d homebrew/versions/android-ndk-r10e homebrew/versions/ansible14 homebrew/versions/ansible18 homebrew/versions/ansible19 homebrew/versions/antlr2 homebrew/versions/antlr3 homebrew/versions/apache-spark141 homebrew/versions/apache-spark15 homebrew/versions/appledoc20 homebrew/versions/appledoc21 homebrew/versions/appledoc22 homebrew/versions/astyle204 homebrew/versions/autoconf213 homebrew/versions/autoconf264 homebrew/versions/automake112 homebrew/versions/bash-completion2 homebrew/versions/bind99 homebrew/versions/bison27 homebrew/versions/boost-python159 homebrew/versions/boost149 homebrew/versions/boost150 homebrew/versions/boost155 homebrew/versions/boost159 homebrew/versions/camlp5-606 homebrew/versions/cassandra-0.6 homebrew/versions/cassandra10 homebrew/versions/cassandra12 homebrew/versions/cassandra20 homebrew/versions/cassandra21 homebrew/versions/cassandra22 homebrew/versions/clojure14 homebrew/versions/cloog-ppl015 homebrew/versions/cloog018 homebrew/versions/cmake28 homebrew/versions/cmake30 homebrew/versions/cmake31 homebrew/versions/coq83 homebrew/versions/cvsps2 homebrew/versions/docker171 homebrew/versions/doxygen1831 homebrew/versions/drush4 homebrew/versions/drush5 homebrew/versions/duplicity06 homebrew/versions/eigen2 homebrew/versions/elasticsearch17 homebrew/versions/elasticsearch22 homebrew/versions/erlang-r13 homebrew/versions/erlang-r14 homebrew/versions/erlang-r15 homebrew/versions/erlang-r16 homebrew/versions/erlang-r17 homebrew/versions/freetds091 homebrew/versions/gawk3 homebrew/versions/gcc43 homebrew/versions/gcc44 homebrew/versions/gcc45 homebrew/versions/gcc46 homebrew/versions/gcc47 homebrew/versions/gcc48 homebrew/versions/gcc49 homebrew/versions/gcc5 homebrew/versions/gcc6 homebrew/versions/gdal111 homebrew/versions/gecode373 homebrew/versions/gegl02 homebrew/versions/giflib5 homebrew/versions/git-tf-2.0.2 homebrew/versions/glfw2 homebrew/versions/glfw3 homebrew/versions/gmp4 homebrew/versions/gnupg21 homebrew/versions/gnuplot4 homebrew/versions/gnutls34 homebrew/versions/go12 homebrew/versions/go13 homebrew/versions/go14 homebrew/versions/go15 homebrew/versions/gradle110 homebrew/versions/gradle112 homebrew/versions/gradle16 homebrew/versions/gradle18 homebrew/versions/gradle20 homebrew/versions/gradle21 homebrew/versions/gradle221 homebrew/versions/gradle24 homebrew/versions/gradle26 homebrew/versions/gradle27 homebrew/versions/gradle28 homebrew/versions/grails13 homebrew/versions/grails20 homebrew/versions/grails21 homebrew/versions/grails22 homebrew/versions/grails223 homebrew/versions/grails224 homebrew/versions/grails23 homebrew/versions/gsl114 homebrew/versions/gst-ffmpeg010 homebrew/versions/gst-plugins-bad010 homebrew/versions/gst-plugins-base010 homebrew/versions/gst-plugins-good010 homebrew/versions/gst-plugins-ugly010 homebrew/versions/gst-python010 homebrew/versions/gst-rtsp010 homebrew/versions/gstreamer010 homebrew/versions/guile18 homebrew/versions/hadoop0202 homebrew/versions/hadoop121 homebrew/versions/hadoop25 homebrew/versions/hdf4 homebrew/versions/hive010 homebrew/versions/hive011 homebrew/versions/imagemagick-ruby186 homebrew/versions/influxdb08 homebrew/versions/iojs'
```

@UniqMartin

**Comment by UniqMartin** [comment]
@zh-lab Oh, that explains it. For some reason, you still have the old Bash completion in your Homebrew installation. It should have been updated during one of the Homebrew updates, but apparently it wasn't. Can you please execute the following commands and post their outputs here?

```
cd $(brew --prefix)/etc/bash_completion.d
ls -l brew
git status
git checkout HEAD -- brew
```

The last command should reset the completion file for Homebrew to what is currently in the Git repository (that implementation no longer uses the slow `for` loop). Hopefully after you've done this, completion in a newly opened Terminal window or tab will be fast.

**Comment by zh-lab** [comment]
```
$ ls -l brew

-rw-r--r--  1 Heng  admin  13877 Apr 12 15:22 brew
```

```
$ git status

On branch master
nothing to commit, working directory clean
```

```
$ git log brew

commit b50e950f0ea2a5fdfc8d312d1a6eb4f4e6240fa0
Author: Martin Afanasjew <martin@afanasjew.de>
Date:   Tue Dec 8 08:40:44 2015 +0100

    unlinkapps: add --dry-run option
    
    Add `--dry-run` option as is customary for destructive commands. Update
    `bash` completion and man page accordingly. Also correct and update
    documentation for both `brew linkapps` and `brew unlinkapps` in more
    general terms.

commit 3afacc351c44c4cee08c181e7c761f44e8b43722
Author: tim smith <github@tim-smith.us>
Date:   Tue Apr 5 09:48:28 2016 -0700

    Speed up tab completion
    
    Fixes #20. Closes #23.

commit ceed6636d6986bb2b993ba4680ae484deb76ae29
Author: Andrew Janke <andrew@apjanke.net>
Date:   Mon Apr 4 01:43:43 2016 -0400

    test-bot: revise Step output transcoding and XML character filtering
    
    Closes #24.
    
    Signed-off-by: Andrew Janke <andrew@apjanke.net>

```

```
$ git checkout HEAD -- brew

$ echo $?
0
```

I have done this, and still slow..
@UniqMartin

**Comment by zh-lab** [comment]
@UniqMartin 
It's strange that b50e950f0ea2a5fdfc8d312d1a6eb4f4e6240fa0 is not a latest commit, but on the top of the log history.

FYI: https://github.com/Homebrew/brew/commits/master/etc/bash_completion.d/brew

**Comment by UniqMartin** [comment]
> I have done this, and still slow..

Apparently your completion for `brew` is loaded from somewhere else and not from that path. Do you have anything else installed that provides Bash completion for various commands and maybe overrides our official completion file (the one in `etc/bash_completion.d/brew`).

> It's strange that b50e950 is not a latest commit, but on the top of the log history.

That's normal. If you ask `git` for the log of a specific file, it will only show the commits that modified this file and omit all other commits. If you use just `git log`, you'll see the complete history.

**Comment by zh-lab** [comment]
@UniqMartin 
>  Do you have anything else installed that provides Bash completion for various commands and maybe overrides our official completion file (the one in etc/bash_completion.d/brew).

No, I only have official one.

**Comment by apjanke** [comment]
Maybe you're running in to a pathological case related to locales here. Using `"C"` as your locale is probably wrong, especially if you're mixing it with Unicode/UTF-8 and international characters. ("C" is an alias for "POSIX", which mostly treats all characters as single-byte opaque characters, but speaking strictly has undefined behavior for some character values; maybe that's interacting weirdly with the `"UTF-8"` LC_CTYPE.) If you're running with a "C" locale, some things will break. (Even if a forum post or StackOverflow answer told you to do so.) And strictly speaking, `"UTF-8"` is not a valid locale value at all.

Since nothing else panned out, let's address these strange locale settings and see if that fixes things.

As far as I know, OS X and its Terminal.app will not set your locale variables to `"C"`, they'll use region-specific UTF-8 locale settings, like `"en_US.UTF-8"`. So it may be your shell setup that's setting these variables. Check your `~/.bashrc`, `~/.bash_profile`, `~/.bash_login`, and `~/.profile`, and other shell startup files to see if they're setting locale variables. (Just `grep 'LC_\|LANG' ~/.*` and see what pops up. I know you posted `.bashrc` earlier, but maybe there are other shell config files hanging around?)

Between that and loading the old `brew` bash completions, looks like there are some machine configuration issues here.

**Comment by zh-lab** [comment]
@apjanke Here is all my files under home.
```
total 96
drwxr-xr-x+  22 Heng  staff    748 May  1 11:46 .
drwxr-xr-x    6 root  admin    204 Oct  8  2015 ..
-r--------    1 Heng  staff      7 Oct  8  2015 .CFUserTextEncoding
-rw-r--r--@   1 Heng  staff  18436 May  1 09:17 .DS_Store
drwx------    2 Heng  staff     68 May  1 11:44 .Trash
-rw-r--r--    1 Heng  staff   6476 May  1 11:46 .bash_history
-rw-r--r--@   1 Heng  staff    182 May  1 10:53 .bash_profile
drwxr-xr-x  350 Heng  staff  11900 May  1 12:23 .bash_sessions
drwx------    3 Heng  staff    102 Oct  9  2015 .docker
-rw-r--r--    1 Heng  staff     75 Feb 18 17:53 .gitconfig
drwx------    5 Heng  staff    170 Apr 19 16:59 .ssh
-rw-------    1 Heng  staff   6396 May  1 10:53 .viminfo
drwx------    3 Heng  staff    102 Mar 21 11:21 Applications
drwx------+   4 Heng  staff    136 Apr 19 17:42 Desktop
drwx------+   5 Heng  staff    170 May  1 11:43 Documents
drwx------+  12 Heng  staff    408 May  2 01:40 Downloads
drwx------@  56 Heng  staff   1904 Mar 21 11:21 Library
drwx------+   5 Heng  staff    170 Oct  8  2015 Movies
drwx------+   7 Heng  staff    238 Oct  8  2015 Music
drwx------+   8 Heng  staff    272 Dec 17 11:10 Pictures
drwxr-xr-x+   5 Heng  staff    170 Oct  8  2015 Public
drwxr-xr-x    5 Heng  staff    170 May  1 11:44 Workspace

```
I just have a .bash_profile.
and it does not have settings about locale.:cry:

I also try to reinstall bash-completion, it doesn't help.

**Comment by apjanke** [comment]
Well, we can try it the hackish way: force your locale settings back to the typical ones by configuring them in your `~/.bash_profile`. Add these lines to your `~/.bash_profile`:

```
export LANG=en_US.UTF-8
unset LC_ALL LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME
```

Then start a new session, see what `locale` says your locale settings are now (they should all be "en_US.UTF-8"), and see completion is still slow.

**Comment by zh-lab** [comment]
@apjanke Added. And still slow. Maybe I should try to reinstall brew...
And I think the main reason is that 3800+ loops..

**Comment by apjanke** [comment]
Yeah, I'd do that pretty soon myself.

One other quick test to try: create a new user and set their `~/.bash_profile` up to use `brew`. See what their `local` output is, and see if brew completion is slow for them. That will give you some indication as to whether it's a user account configuration or Homebrew installation configuration issue.

If it's still slow for a new user, reinstalling Homebrew is a good next step.

If it's fast for the new user, I'd probably reinstall Homebrew anyway just in case. And then see if you could migrate to a new user account for yourself.

Make sure you have good backups of all your data before messing with switching to a new account or doing low-level fiddling with the OS!

**Comment by zh-lab** [comment]
I just reinstalled OS X. And everything works well now...Thanks for your help!
