### ISSUE TITLE
'brew leaves' should have option to show version numbers ('brew leaves --versions')

### ISSUE THREAD

**Issue by melyux** [Homebrew/brew#12628]
### Provide a detailed description of the proposed feature

Using `brew leaves` is a nice way to see top-level packages. You should be able to do `brew leaves --versions` and have it put the leaves' version numbers next to them.

### What is the motivation for the feature?

It would be a much more semantic alias for the current `brew list --versions $(brew leaves)`.

### How will the feature be relevant to at least 90% of Homebrew users?

They can see the versions of the top-level packages that they actually went out and installed manually without having to type an unintuitive, lengthy, where'd-that-come-from `brew list --versions $(brew leaves)`. 90% of Homebrew users aren't going to remember that or be able to reason towards discovering it. A web search is going to get involved.

### What alternatives to the feature have been considered?

You can type `brew list --versions $(brew leaves)` but it's hard to remember, nigh undiscoverable, and too long to be a user-friendly command.

**Comment by Rylan12** [comment]
Why do you want to run `brew list --versions $(brew leaves)`?

I don't think `brew leaves` is a command that most Homebrew users are familiar with anyway, so I'm not sure that `brew list --versions $(brew leaves)` is much worse than `brew leaves --versions`. Plus, I'm not really sure why one would need this particular output.

**Comment by melyux** [comment]
Well, I want to see the top level packages that I actually installed, and don't want to see all of their dependency garbage. Like when I look at my computer's Applications, I like to see the applications I actually installed instead of all their libraries, etc. That's why I use `brew leaves` instead of `brew list`. 

While doing this, I also want to see their versions (ideally without having to specify `--versions` in the first place given how little space the version numbers occupy, but that's another topic).

**Comment by MikeMcQuaid** [comment]
> You can type `brew list --versions $(brew leaves)` but it's hard to remember, nigh undiscoverable, and too long to be a user-friendly command.

I've never seen anyone else asking for this so: closing this out as there's a workaround you can add an alias for.

Extending `brew list` would be possible but https://github.com/Homebrew/brew/pull/12461 stalled. You might wish to revive it by opening your own PR with the commits cherry-picked.

**Comment by melyux** [comment]
This wasn't a help request, but a suggestion. I can add an alias and already have. But if there is a `--versions` flag for `brew list`, and there's a `brew leaves`, then `brew leaves --versions` is a no-brainer for consistency.
