### ISSUE TITLE
Recommend a Homebrew Linux distribution  

### ISSUE THREAD

**Issue by benjaminyin01** [Homebrew/brew#12626]
### Provide a detailed description of the proposed feature

There are a lot of linux distributions, redhat fedora debian ubuntu archlinux...
But most of them use old software packages, and are difficult to contribute new software.
If people compile software from source, the software is not under the control of package management system.
Homebew is very easy to contribute and keep update frequently. So if there is a homeberw linux distribution that completely use homebrew as its package system, People will feel nice.

### What is the motivation for the feature?

Make a homebrew linux distribution

### How will the feature be relevant to at least 90% of Homebrew users?

Most linuxbrew users will be interested in  it  

### What alternatives to the feature have been considered?

no

**Comment by dawidd6** [comment]
That's not going to happen. Just install Homebrew on your Linux distribution of choice and use it. No need for a dedicated distribution.
