### ISSUE TITLE
Recommend auto remove depeneded packages

### ISSUE THREAD

**Issue by benjaminyin01** [Homebrew/brew#12625]
### Provide a detailed description of the proposed feature

When I install ffmpeg, a lot of other packages are installed which are depended by ffmpeg.
But when I uninstall ffmpeg, these packages are still in my Mac.
How to resolve this problem?
A package can been installed explicitly or implicitly. If it was installed by the dependence of  other package, it  should be auto removed when the depend package are uninstalled.

### What is the motivation for the feature?

keep system clear 

### How will the feature be relevant to at least 90% of Homebrew users?

Every user need this feature

### What alternatives to the feature have been considered?

borrow the idea of apt in debian linux

**Comment by dawidd6** [comment]
`brew autoremove` will do that for you. Read the manpage.
