### ISSUE TITLE
Can't install any kind of library

### ISSUE THREAD

**Issue by khusnetdinov** [Homebrew/brew#1263]
After reinstall brew I faced with problem on OSX El Capitan 10.11.6
$ brew doctor
Your system is ready to brew.
$ brew install [any library]
==> Installing dependencies for erlang: openssl, jpeg, libpng, libtiff, wxmac
==> Installing erlang dependency: openssl
Error: Operation not permitted - /tmp/github_api_headers20161011-22697-1vq1bhw

See [Here](https://monosnap.com/file/Y9CokAH8lO8Eo9lx542h5nT4z0zlMt)

Reinstall won't help

What is broken?

**Comment by khusnetdinov** [comment]
export HOMEBREW_TEMP=/usr/local/tmp_brew is solution

**Comment by MikeMcQuaid** [comment]
If you can't write to `/tmp` you'll likely have issues with other applications too, just FYI.
