### ISSUE TITLE
`brew style --fix` produces a generic error

### ISSUE THREAD

**Issue by robertleeblairjr** [Homebrew/brew#12662]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.9-103-ga0ae4a7
ORIGIN: https://github.com/Homebrew/brew
HEAD: a0ae4a7a02d9b6d886fb99a23ddbe07af7979fb6
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9b79f47c8370c7449aa1470a0c3eb7386e8d5f3d
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.YxWpAFjL9i/org.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew style --fix`

Check for any style errors of installed formula.

### What happened (include all command output)?

Inspecting 1092 files
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

1092 files inspected, no offenses detected
Error: Failure while executing; `patch --get=0 --force --directory=/ --strip=0` exited with 2. Here's the output:

### What did you expect to happen?

Return without error.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew style --fix`
```

**Comment by gromgit** [comment]
What's the output of `brew readall`?

**Comment by MikeMcQuaid** [comment]
@XuehaiPan could you take a look at this?

**Comment by XuehaiPan** [comment]
I found this may be a bug for `patch` command on macOS. I can reproduce this on my Mac but cannot on Linux.

macOS Monterey:

```console
$ patch --get=0 --force --directory=/ --strip=0 < /dev/null
patch: option `--get' doesn't allow an argument
patch: Try `patch --help' for more information.

$ patch -g 0 --force --directory=/ --strip=0 < /dev/null
```

It works when I change the long option `--get` to `-g`. (It's a bug: they should be the same.)

> Run `man patch`

<img width="970" alt="Screen Shot" src="https://user-images.githubusercontent.com/16078332/147938886-54124d4e-552e-439c-8a81-788d9bb1781e.png">

In `patch.rb`, we use short flag `-g`:

https://github.com/Homebrew/brew/blob/ff9691d4ba526c84fcae652f3dd8b80837b6eef7/Library/Homebrew/patch.rb#L155-L160
