### ISSUE TITLE
`brew autoremove` can't recognize dependencies of dependencies of casks

### ISSUE THREAD

**Issue by tianyizheng02** [Homebrew/brew#12660]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.9-101-g26bffd4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 26bffd4051d5a7a5f92ee697a557c35af7e4c038
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9319d2095aec692c9d130e7d71f28de6fd6e6822
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to run `brew autoremove` to uninstall any unneeded dependencies.

### What happened (include all command output)?

`brew autoremove` ran into an error because the 9 formulae that it was trying to uninstall are dependencies of `ghostscript`, which itself is a dependency of `mactex-no-gui`:
```
$ brew autoremove
==> Uninstalling 9 unneeded formulae:
fontconfig
freetype
jbig2dec
jpeg
libidn
libpng
libtiff
little-cms2
openjpeg
Error: Refusing to uninstall /usr/local/Cellar/libpng/1.6.37, /usr/local/Cellar/freetype/2.11.1, /usr/local/Cellar/fontconfig/2.13.1, /usr/local/Cellar/jbig2dec/0.19, /usr/local/Cellar/jpeg/9d, /usr/local/Cellar/libidn/1.38, /usr/local/Cellar/libtiff/4.3.0, /usr/local/Cellar/little-cms2/2.12 and /usr/local/Cellar/openjpeg/2.4.0
because they are required by ghostscript and mactex-no-gui, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies 
```

### What did you expect to happen?

I expected `brew autoremove` to ignore the 9 formulae since they are dependencies of `ghostscript`, which itself is a dependency of `mactex-no-gui`. I've also been able to reproduce the same error with `mactex` since it has the same dependencies as `mactex-no-gui`.

The closure of #11417 suggested that this bug had already been fixed, but that is apparently not the case. My command output is similar but not identical since I'm basically running into the same error except one level lower.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1) Ensure that `ghostscript` and its dependencies (see output above) are not already installed
2) Install either `mactex` or `mactex-no-gui` (will take a while):
   `brew install mactex` or `brew install mactex-no-gui`
3) Run `brew autoremove`
```

**Comment by carlocab** [comment]
@hyuraku, maybe you'd like to take a look at this?

**Comment by hyuraku** [comment]
> @hyuraku, maybe you'd like to take a look at this?

@carlocab, OK!
