### ISSUE TITLE
Linuxbrew should append instead of prepend `$PATH` to bin dir

### ISSUE THREAD

**Issue by kevincianfarini** [Homebrew/brew#12677]
### Provide a detailed description of the proposed feature

Upon installation of Linuxbrew, it's recommended to prepend `$PATH` with the linuxbrew `bin` directory like so. 

```
PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
```

Instead, Homebrew should prefer _appending_ the binary directory on `$PATH`. 

```
PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
```

### What is the motivation for the feature?

Prepending is inadvisable because packages have the possibility of including transitive dependencies which would take precedence over system binaries. One such instance of this is _any_ program which has a transitive dependency on `p11-kit`. 

I filed a bug over on he `p11-kit` repo for a broken installation which was failing to give _any_ valid SSL certificates and broke several applications which were completely unrelated to `flyway` -- the program I installed which had a transitive dependency on `p11-kit`. More specifically, _any_ program which has a dependency on `openjdk` will exhibit this issue. Take a look at my dependency tree. 

```
flyway
└── openjdk
    ├── alsa-lib
    ├── cups
    │   ├── krb5
    │   │   ├── openssl@1.1
    │   │   │   └── ca-certificates
    │   │   ├── bison
    │   │   │   └── m4
    │   │   └── gettext
    │   │       ├── libxml2
    │   │       │   ├── readline
    │   │       │   │   └── ncurses
    │   │       │   └── zlib
    │   │       └── ncurses
    │   ├── zlib
    │   └── gnutls
    │       ├── ca-certificates
    │       ├── gmp
    │       ├── guile
    │       │   ├── bdw-gc
    │       │   ├── gmp
    │       │   ├── libffi
    │       │   ├── libtool
    │       │   │   └── m4
    │       │   ├── libunistring
    │       │   ├── pkg-config
    │       │   ├── readline
    │       │   │   └── ncurses
    │       │   └── gperf
    │       ├── libidn2
    │       │   ├── gettext
    │       │   │   ├── libxml2
    │       │   │   │   ├── readline
    │       │   │   │   │   └── ncurses
    │       │   │   │   └── zlib
    │       │   │   └── ncurses
    │       │   └── libunistring
    │       ├── libtasn1
    │       ├── libunistring
    │       ├── nettle
    │       │   └── gmp
    │       ├── p11-kit
    │       │   └── libffi

```

You can read more about this issue at https://github.com/p11-glue/p11-kit/issues/404

### How will the feature be relevant to at least 90% of Homebrew users?

Certainly it won't be relevant to 90% of overall users, but would certainly be relevant to 90% of linux users. This poses a real risk of prioritizing non-system binaries over system binaries. 

### What alternatives to the feature have been considered?

None.

**Comment by MikeMcQuaid** [comment]
> This poses a real risk of prioritizing non-system binaries over system binaries.

This is the intended behaviour so we don't plan on changing it. We should allowing people to append instead and would be game for code changes to make sure this isn't broken and potentially even an environment variable to configure this.
