### ISSUE TITLE
brew cleanup --help features incorrect linebreaks

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/brew#12671]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.9-122-g578286a-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 578286a94701a2f9c013266e76f02a41079edbaf
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c2eb6bdb7f29f5b341461366b82be847aa6894f5
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Jz9hsDzhLP/org.macosforge.xquartz:0
HOMEBREW_EDITOR: subl
HOMEBREW_GITHUB_PACKAGES_TOKEN: set
HOMEBREW_GITHUB_PACKAGES_USER: mistydemeo
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.31.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false
```
```


### `brew doctor` output

```shell
Only errors about uncommitted changes that I used to generate the "expect to happen" result below.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew cleanup --help` has a surprising line wrap error which causes the last bit of text, `--cache)"`, to be wrapped back to the start of the command alongside the short flag. It incorrectly implies that `--cache` is the long-form flag for `-s`, which has no long-form flag.

This was "introduced" in f426f1f51fb728618a9c1d756a4a5b7c0b6bed8f in that an extra word was added to the switch description that pushed the last word onto a new line, triggering the bug, but I haven't yet identified the root cause.

### What happened (include all command output)?

```
  -s, --cache)"                   Scrub the cache, including downloads for
                                   even the latest versions. Note that
                                   downloads for any installed formulae or
                                   casks will still not be deleted. If you
                                   want to delete those too: rm -rf "$(brew
```

### What did you expect to happen?

```
  -s                               Scrub the cache, including downloads for
                                   even the latest versions. Note downloads
                                   for any installed formulae or casks will
                                   still not be deleted. If you want to delete
                                   those too: rm -rf "$(brew --cache)"
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew cleanup --help`
```

**Comment by mistydemeo** [comment]
Think I figured out what's going on. In our CLI parser code, we dispatch to the underlying `OptionParser`'s `#on` here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cli/parser.rb#L162-L167

In other words, we call `@parser.on(*names, *wrap_option_desc(description))`. `wrap_option_desc(description)` splits the description across multiple lines and, thanks for the aforementioned extra word, pops `--cache` from the description on the last line. `OptionParser`'s underlying `#make_switch` command here doesn't distinguish between arguments positionally: it just gets everything in one `args` array: https://github.com/ruby/optparse/blob/master/lib/optparse.rb#L1325 And operates on them based on whether they "look like" an option: https://github.com/ruby/optparse/blob/master/lib/optparse.rb#L1398-L1407

Which leads to our bug. Because our own line-splitting code has now put the `--cache)"` from the end of the help text on its own line, `OptionParser` sees it as a new switch definition and not a continuation of the description text. This ambiguity is, arguably, a bug in `OptionParser`: I don't think it makes any sense for it to start taking switches again after it's accepted non-switch strings. As written, however, it's doing the "right" thing and our code does have a weird ambiguity here that leads to this.

A workaround here would be to make sure our line-splitter never begins a line with `-` or `--`, gross as that feels.

**Comment by Rylan12** [comment]
I opened #12672 with a possible solution (different from what you suggested)

**Comment by MikeMcQuaid** [comment]
@mistydemeo Nice debugging, thanks ❤️
