### ISSUE TITLE
Restart Cask after upgrade

### ISSUE THREAD

**Issue by DestroyerXyz** [Homebrew/brew#12709]
### Provide a detailed description of the proposed feature

Restart cask after upgrade if the app was closed using "exit" during the "uninstall" stanza.

### What is the motivation for the feature?

Ease of use, especially if a lot of casks are upgraded at the same time.

### How will the feature be relevant to at least 90% of Homebrew users?

A lot of users have continuously running apps like "google-drive" and "bartender".

### What alternatives to the feature have been considered?

N/A

**Comment by miccal** [comment]
Duplicate of https://github.com/Homebrew/homebrew-cask/issues/104074
