### ISSUE TITLE
Brew not upgrading outdated casks/formulae on MBP M1 Pro

### ISSUE THREAD

**Issue by LeonardoMazzoli** [Homebrew/brew#12710]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 385892f3d27dcab0f5a1cb47c3927d9d65ed007c
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c3d7d6ff280e2a907f2e1897d09cb90e77ffb279
Core tap last commit: 52 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to update outdated casks/formulae, but nothing happens. 

### First, tried to use brew update && brew upgrade, in this case firefox is outdated (This problems happens with all the installed formulae/casks, also newly installed )
leonardomazzoli@Leonardos-MacBook-Pro ~ % brew update && brew upgrade
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
netmask
==> Updated Formulae
atop                    conmon                  duck                    haproxy                 lammps                  litecli                 mongosh                 notmuch-mutt            petsc                   rdkit                   terraform-ls            zbctl
caire                   contentful-cli          eksctl                  hello                   libphonenumber          lttng-ust               mycli                   osm2pgrouting           petsc-complex           rhino                   userspace-rcu
certigo                 curaengine              gerbil-scheme           knot                    libpqxx                 luajit-openresty        notmuch                 pdm                     pgcli                   superlu                 yosys
==> New Casks
clover
==> Updated Casks
firefox ✔                           cinch                               flowdock                            isubtitle                           mmhmm                               pictogram                           screens-connect                     tor-browser
accessmenubarapps                   cinebench                           fluid                               itk-snap                            monodraw                            platypus                            scroll-reverser                     townwifi
adobe-acrobat-pro                   cirrus                              fontforge                           itsycal                             mountain-duck                       playmemories-home                   secure-pipes                        transfer
adobe-acrobat-reader                clicker-for-youtube                 forecast                            jazzup                              mousepose                           plex-media-server                   sequel-ace                          transocks
adobe-connect                       clock-bar                           forklift                            jdk-mission-control                 mplayerx                            podcastmenu                         serial                              trayplay
adoptopenjdk                        coda                                fotokasten                          jietu                               mtmr                                podolski                            shortcat                            triplecheese
aether                              coderunner                          fpc-laz                             kapitainsky-rclone-browser          multitouch                          poedit                              shottr                              tropy
agenda                              contraste                           fpc-src-laz                         keka                                mumu                                polyphone                           signet                              tuck
air-video-server-hd                 couleurs                            framer-x                            keyboard-maestro                    musicbrainz-picard                  pomotodo                            silentknight                        tuneinstructor
airdisplay                          cr                                  freecad                             keysmith                            muzzle                              popclip                             sim-genie                           tunnelbear
airtool                             cura-lulzbot                        frhelper                            kodelife                            namechanger                         portx                               simpholders                         tweetbot
alfred                              curseforge                          fsmonitor                           komet                               navicat-for-mariadb                 post-haste                          sizeup                              twitterrific
aliworkbench                        customshortcuts                     fvim                                komodo-edit                         navicat-for-mysql                   postman                             sketchbook                          typeit4me
alternote                           cyberduck                           geany                               komodo-ide                          navicat-for-oracle                  powerword                           sketchup                            ubar
altserver                           cyberghost-vpn                      get-iplayer-automator               lab                                 navicat-for-postgresql              prezi-classic                       skitch                              ukelele
amazon-music                        darwindumper                        gfxcardstatus                       librewolf                           navicat-for-sql-server              privatetunnel                       slicer                              ultimaker-cura
ammonite                            dbngin                              gifox                               liclipse                            navicat-for-sqlite                  processing                          sloth                               unicodechecker
ansible-dk                          deckset                             gitfinder                           lightkey                            navicat-premium-essentials          proclaim                            snip                                uninstallpkg
app-tamer                           decloner                            gitfox                              lightworks                          neteasemusic                        profilecreator                      sonic-visualiser                    usenapp
aria2d                              default-folder-x                    go-agent                            liteicon                            nightingale                         proxyman                            soulver                             uu-booster
arkiwi                              dejalu                              go-server                           lockrattler                         nimble-commander                    prusaslicer                         sound-control                       vanilla
astah-professional                  devutils                            go64                                lookin                              nodeclipse                          pycharm-ce-with-anaconda-plugin     spectacle                           veepn
astah-uml                           disk-expert                         google-drive                        ltspice                             noto                                pycharm-with-anaconda-plugin        spillo                              vidl
astropad                            displays                            grafx                               lyricsx                             noun-project                        pym-player                          sqleditor                           vienna
astropad-studio                     ditto                               gramps                              m3unify                             nvalt                               qcma                                squeak                              virtualbox
audirvana                           divvy                               handshaker                          maccy                               obs-virtualcam                      qdesktop                            ssh-config-editor                   virtualhostx
aurora-hdr                          djview                              haptic-touch-bar                    macgamestore                        ogdesign-eagle                      qlab                                ssh-tunnel-manager                  vmware-fusion
avidcodecsle                        dockmate                            hermes                              macjournal                          one-switch                          querypie                            stay                                vmware-horizon-client
avtouchbar                          dosbox                              historyhound                        mailplane                           onepile                             rclone-browser                      stubbymanager                       voodoopad
backuploupe                         drivedx                             hocus-focus                         manageengine-mibbrowser             openarena                           react-studio                        swiftpm-catalog                     voov-meeting
balance-lock                        dropzone                            hookshot                            maria                               openbci                             reamp                               swiftybeaver                        watchguard-mobile-vpn-with-ssl
base                                duplicate-file-finder               hype                                marked                              opencpn                             recut                               swinsian                            wifi-explorer-pro
batchmod                            duplicati                           icc                                 mars                                openvanilla                         reflector                           swish                               wpsoffice
beamer                              ears                                iconjar                             marvel                              openzfs                             remoteviewer                        syncsettings                        wwdc
bee                                 edfbrowser                          iexplorer                           mds                                 optimus-player                      renamer                             synergy                             wxmacmolplt
better-window-manager               elpass                              iina                                meld                                osculator                           repetier-host                       tableau-public                      xamarin-profiler
bettertouchtool                     encryptme                           image2icon                          messenger                           outline                             replacicon                          tableflip                           xattred
blu-ray-player                      endurance                           inssider                            messenger-unofficial                packetsender                        resolume-arena                      tabtopus                            xcodes
bluestacks                          engine-prime                        intel-power-gadget                  metaimage                           paintbrush                          retro-virtual-machine               taskpaper                           xld
bria                                enjoyable                           intel-psxe-ce-c-plus-plus           metasploit                          paparazzi                           retrobatch                          textexpander                        xmind
burp-suite                          eudic                               intellij-idea-ce                    mi                                  pdf-expert                          robo-3t                             thetimemachinemechanic              xmind-zen
burp-suite-professional             expandrive                          invisionsync                        mia-for-gmail                       pdfpen                              rocket                              thunder                             xscope
c0re100-qbittorrent                 fake                                invisor-lite                        mic-drop                            pdfpenpro                           rowanj-gitx                         thunderbird                         xtorrent
calendar-366                        fetch                               ios-console                         middle                              peakhour                            satellite-eyes                      tiles                               yu-writer
camo-studio                         fig                                 ipa-manager                         miditrail                           pester                              sauerbraten                         tinymediamanager                    zebra2
cardhop                             filepane                            ipvanish-vpn                        minecraft-server                    phew                                screenflow                          toolreleases                        zoomus
celestialteapot-runway              flexiglass                          ishowu-instant                      mini-program-studio                 photosync                           screens                             toptracker                          zulu
### Check for outdated casks/formulae
leonardomazzoli@Leonardos-MacBook-Pro ~ % brew outdated (gives no outdated casks/formulae)
### Firefox is not upgraded
leonardomazzoli@Leonardos-MacBook-Pro ~ % brew info firefox
**firefox: 96.0 (auto_updates)** <---
https://www.mozilla.org/firefox/
**/opt/homebrew/Caskroom/firefox/95.0.2 (121B)** <---
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/firefox.rb
==> Name
Mozilla Firefox
==> Description
Web browser
==> Languages
cs, de, en-CA, en-GB, en, eo, es-AR, es-CL, es-ES, fi, fr, gl, in, it, ja, ko, nl, pl, pt-BR, pt, ru, sv, tr, uk, zh-TW, zh
==> Artifacts
Firefox.app (App)
==> Analytics
install: 18,990 (30 days), 59,681 (90 days), 178,455 (365 days)

### What did you expect to happen?

Upgrade all the outdated casks/formulae

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1) brew update && brew upgrade or brew update and then brew upgrade
2) if something is outdated, should be visible with brew outdated, if not it was upgraded
3) brew info outdated cask/formulae to check that is not upgraded
```

**Comment by carlocab** [comment]
The `auto_updates` part here is important:
```
firefox: 96.0 (auto_updates)
```
`brew upgrade` and `brew outdated` do not consider casks that auto-update.

You probably want one of the flags `--greedy`, `--greedy-latest`, or `--greedy-auto-updates`. These flags are recognised by both `brew upgrade` and `brew install`. See `man brew` or `brew help upgrade` and `brew help outdated` for details.

**Comment by LeonardoMazzoli** [comment]
Thank you, i'm sorry for the inconvenience

**Comment by carlocab** [comment]
No problem. `man brew` contains answers to most questions one might have about using `brew`. Some of the contents are also discussed in a less dry fashion at https://docs.brew.sh. For example: https://docs.brew.sh/FAQ#why-arent-some-apps-included-during-brew-upgrade

There's a link to that FAQ in https://github.com/Homebrew/homebrew-cask#reporting-bugs, which also discusses common Homebrew Cask issues.

**Comment by LeonardoMazzoli** [comment]
Thank you again.
