### ISSUE TITLE
Homebrew failing to detect latest version of Xcode

### ISSUE THREAD

**Issue by scollinson** [Homebrew/brew#12714]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 385892f3d27dcab0f5a1cb47c3927d9d65ed007c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0f63e382f8e3d8acbab1b9cfe186d95d899a1155
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-x86_64
CLT: 13.0.0.0.1.1627064638
Xcode: 13.2.1
```

### `brew doctor` output

```shell
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libgeneral.0.dylib
  /usr/local/lib/libimg4tool.0.dylib
  /usr/local/lib/libimobiledevice-1.0.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libgeneral/macros.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libgeneral.la
  /usr/local/lib/libimg4tool.la
  /usr/local/lib/libimobiledevice-1.0.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/libgeneral.pc
  /usr/local/lib/pkgconfig/libimg4tool.pc
  /usr/local/lib/pkgconfig/libimobiledevice-1.0.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libgeneral.a
  /usr/local/lib/libimg4tool.a
  /usr/local/lib/libimobiledevice-1.0.a
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install the `ipsw` tool, however it is failing as brew is unable to validate that the latest version of Xcode is installed.

### What happened (include all command output)?

==> Downloading https://github.com/blacktop/ipsw/releases/download/v3.1.41/ipsw_3.1.41_macOS_x86_64.tar.gz
Already downloaded: /Users/x/Library/Caches/Homebrew/downloads/915a4bb5e02ca36924c2525c8c07f26606b9e4aefc3e6cb73aa65168de40f613--ipsw_3.1.41_macOS_x86_64.tar.gz
==> Installing ipsw from blacktop/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.

### What did you expect to happen?

That this tool would work without the latest Xcode, and I also tried `softwareupdate --all --install --force` which updated Xcode for me, but still didnt fix the issue. I also tried deleting the command line tools dir and reisntalling and still nothing. I verified the correct version is installed (and checked the xcode.rb source to see how the version was determined) below:

```
xcodebuild -version
Xcode 13.2.1
Build version 13C100
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install blacktop/tap/ipsw`
```

**Comment by carlocab** [comment]
Homebrew is detecting the latest version of Xcode:
```
Xcode: 13.2.1
```

Note that Homebrew is not complaining about the version of Xcode:
```
Your Command Line Tools are too outdated.
```

It is complaining about the version of your CLT, which is outdated:
```
CLT: 13.0.0.0.1.1627064638
```
You can update your CLT by following the advice shown to you by `brew doctor`.

**Comment by scollinson** [comment]
Thanks! I followed the advice through and macOS seemed to say everything was ok. Even the Xcode UI said I had the latest Xcode CLT. I've tried the process again and it's working. I think starting and stopping Xcode during this process seems to have changed something. Strange, sorry for wasting your time.
