### ISSUE TITLE
List all packages that are not depended on by others

### ISSUE THREAD

**Issue by DesWurstes** [Homebrew/brew#12722]
### Provide a detailed description of the proposed feature

`brew toplist` => list all packages that can be removed without a warning

### What is the motivation for the feature?

The use pattern that you download a library to check it out, then install one or more dependencies via brew, which depend on many other things: Once you find out that the library is not of any use, you should be able to remove the unused dependencies. Those are those that can be removed without a dependent warning.  

### How will the feature be relevant to at least 90% of Homebrew users?

"packages that are not depended on by others" will usually be large packages such as llvm or etc. This would be very useful for saving space. Brew has many packages installed, so many that I don't know which ones I chose to install and which ones are unued. I'm sure, **an average brew user will not know the most of the packages listed by `brew list` now**.

### What alternatives to the feature have been considered?

- Rewrite brew list so that the results are shown in two categories, depending ones and the ones being depended on.
- Add "dry run" to brew remove so that I can code a bash script that would list those who call `brew remove` and return without a warning.

**Comment by MikeMcQuaid** [comment]
`brew leaves --help` should get you what you need.
