### ISSUE TITLE
brew how to support that the MacOS 12 installs graphviz

### ISSUE THREAD

**Issue by frankieci** [Homebrew/brew#12730]
### Provide a detailed description of the proposed feature

I want the MacOS 12 supports installing graphviz， now I don't have it,  brew function is ok, brew version 
(
Homebrew 3.1.9-58-g7ae9cc3
Homebrew/homebrew-core (git revision 012ef36e5d; last commit 2021-05-28)
Homebrew/homebrew-cask (git revision 5c0e9f899d; last commit 2021-05-28)
)

### What is the motivation for the feature?

The MacOS 12 supports installing graphviz

### How will the feature be relevant to at least 90% of Homebrew users?

The MacOS 12 supports installing graphviz

### What alternatives to the feature have been considered?

**brew search graphviz, outout log**
==> Formulae
graphviz

If you meant "graphviz" specifically:
It was migrated from homebrew/cask to homebrew/core.

**brew install graphviz, after that, outout log:**

Updating Homebrew...
Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Error: graphviz: no bottle available!
You can try to install from source with:
  brew install --build-from-source graphviz
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

**Comment by gromgit** [comment]
>```
>Homebrew 3.1.9-58-g7ae9cc3
>Homebrew/homebrew-core (git revision 012ef36; last commit 2021-05-28)
>Homebrew/homebrew-cask (git revision 5c0e9f899d; last commit 2021-05-28)
>```

You haven't run `brew update` in many months. Do that, and all the error messages you posted should go away.

**Comment by frankieci** [comment]
> > ```
> > Homebrew 3.1.9-58-g7ae9cc3
> > Homebrew/homebrew-core (git revision 012ef36; last commit 2021-05-28)
> > Homebrew/homebrew-cask (git revision 5c0e9f899d; last commit 2021-05-28)
> > ```
> 
> You haven't run `brew update` in many months. Do that, and all the error messages you posted should go away.

Thank you, maybe the network and proxy are not better, afeter fixed, brew upgrade all, ok
