### ISSUE TITLE
`brew autoremove` can't recognize dependencies of casks

### ISSUE THREAD

**Issue by cppxor2arr** [Homebrew/brew#12749]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 537036ab3627b65d71dfa920b98d43774f861dec
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1c6e59b46ec53b202791115136dd7b5ab15034ea
Core tap last commit: 26 seconds ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to run `brew autoremove` to uninstall any unneeded dependencies.

### What happened (include all command output)?

```shell
% brew autoremove 
==> Uninstalling 1 unneeded formula:
autoconf
Error: Refusing to uninstall /opt/homebrew/Cellar/autoconf/2.71
because it is required by mactex, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies
```

### What did you expect to happen?

I expected `brew autoremove` to ignore `autoconf` because it is a dependency of `mactex` (a cask). This issue seemed to be fixed ([#11417](https://github.com/Homebrew/brew/issues/11417) and [12660](https://github.com/Homebrew/brew/issues/12660) were closed) but I still have this issue.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1) Ensure that `autoconf` is not already installed
2) Run `brew install --cask mactex`
3) Run `brew autoremove`
```

**Comment by MikeMcQuaid** [comment]
@hyuraku Mind taking a look? Thanks ❤️

**Comment by hyuraku** [comment]
@MikeMcQuaid 
It doesn't seem to be caused by a bug in the command.
Because mactex does not depend on autoconf, the messages `it is required by mactex` would not be displayed.
```bash
$ brew deps mactex --tree
mactex
└── ghostscript
    ├── fontconfig
    │   └── freetype
    │       └── libpng
    ├── freetype
    │   └── libpng
    ├── jbig2dec
    ├── jpeg
    ├── libidn
    ├── libpng
    ├── libtiff
    │   └── jpeg
    ├── little-cms2
    │   ├── jpeg
    │   └── libtiff
    │       └── jpeg
    └── openjpeg
        ├── libpng
        ├── libtiff
        │   └── jpeg
        └── little-cms2
            ├── jpeg
            └── libtiff
                └── jpeg
```

**Comment by MikeMcQuaid** [comment]
@hyuraku If something had to be built from source: it would be flagged as a dependency. Any ideas on what might be causing this or what the fix/workaround would be?

**Comment by hyuraku** [comment]
@MikeMcQuaid 
`mactex` depends on `automake` in the following steps.

1. `mactex` depends on `jbig2dec` indirectly.
2. jbig2dec depends on `automake ` for only build-time.
3. `automake` depends on `autoconf`.

```
$ brew deps --tree mactex
mactex
└── ghostscript
    ├── fontconfig
    │   └── freetype
    │       └── libpng
    ├── freetype
    │   └── libpng
    ├── jbig2dec
--< omitted >--
```

```
$ brew deps --tree jbig2dec --include_build
jbig2dec
├── autoconf
│   └── m4
├── automake
│   └── autoconf
│       └── m4
└── libtool
    └── m4
```

```
$ brew deps --tree automake
automake
└── autoconf
    └── m4
```
I will fix the problem that cask runtime_dependencies includes a build-time only dependency's dependency like `autoconf`.

```
cask = Cask::Cask.all.select{|a| a.full_name == "mactex"}.first
CaskDependent.new(cask).runtime_dependencies(ignore_missing: true).map(&:to_formula).map(&:name)
=> ["libpng", "freetype", "fontconfig", "m4", "autoconf", "jbig2dec", "jpeg", "libidn", "libtiff", "little-cms2", "openjpeg", "ghostscript"]
```

**Comment by MikeMcQuaid** [comment]
> I will fix the problem that cask runtime_dependencies includes a build-time only dependency's dependency like `autoconf`.

Great, thanks 🙇🏻. I think the main issue here is the inconsistency; however `brew autoremove` and `brew uninstall` evaluate dependencies they should be the same/consistent.

**Comment by hyuraku** [comment]
@MikeMcQuaid 
I thought `CaskDependent#runtime_dependencies` showed only the dependency's runtime_dependencies instead of their recursive_dependencies. Would I like to change like below?

- before
```ruby
class CaskDependent
  #--< omitted >--

  def runtime_dependencies(ignore_missing: false)
    recursive_dependencies(ignore_missing: ignore_missing).reject do |dependency|
      tags = dependency.tags
      tags.include?(:build) || tags.include?(:test)
    end
  end
```

- after
```ruby
class CaskDependent
  #--< omitted >--

  def runtime_dependencies(ignore_missing: false)
    self.deps.flat_map{|deps| deps.to_formula.runtime_dependencies}.uniq
```

**Comment by carlocab** [comment]
That sounds like it would be wrong if a `CaskDependent` itself depended on another cask.

**Comment by hyuraku** [comment]
> if a CaskDependent itself depended on another cask.

The current `CaskDependent#runtime_dependencies` returns only `formulae` list and doesn`t include any `casks`.

**Comment by MikeMcQuaid** [comment]
@hyuraku Yes, the after looks more correct, thanks 👍🏻

**Comment by hyuraku** [comment]
@MikeMcQuaid 

> @hyuraku Yes, the after looks more correct, thanks 👍🏻

Could you review https://github.com/Homebrew/brew/pull/12795 because I applied https://github.com/Homebrew/brew/issues/12749#issuecomment-1033761472 to it?
