### ISSUE TITLE
Support fetching bottle manifests from non-ghcr.io domains

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#12759]
### Provide a detailed description of the proposed feature

We currently fetch bottle manifests only from ghcr.io. It would be good to support doing this for non-ghcr.io bottle domains as well.

### What is the motivation for the feature?

Not fetching bottle manifests breaks installation from bottle mirrors since these probably won't be hosted at ghcr.io (because why would you do that). See, for example, Homebrew/discussions#2530.

I believe there also have been requests to support hosting bottles in alternative container registries.

### How will the feature be relevant to at least 90% of Homebrew users?

I don't think it will be, but broken bottle mirrors probably impact a significant fraction of our user base.

### What alternatives to the feature have been considered?

Disallowing bottle mirrors and not allowing the use of alternative container registries for third-party taps.

**Comment by MikeMcQuaid** [comment]
Passing on this but will accept a PR.
