### ISSUE TITLE
Opencv with java support failed to install on MacOS Catalina 10.15.7

### ISSUE THREAD

**Issue by iglaweb** [Homebrew/brew#12754]
### `brew config` output

```shell
brew config                             
HOMEBREW_VERSION: 3.3.11-58-g40c895c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 40c895c88e7a85233bbd41e7a0894d288d72933f
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ee6afacfe96da5cd60c0cf647131c8c8e38b5779
Core tap last commit: 65 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.CbCEARoA2V/org.macosforge.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```

### `brew doctor` output

```shell
Too long output
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Output of brew gist-logs opencv:
https://gist.github.com/44aa920944398bc8634d21c2863cd110

### What happened (include all command output)?

Output of 'brew install --build-from-source opencv':

brew install --build-from-source opencv 
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated Homebrew from ec389a6ea to 40c895c88.
Updated 1 tap (homebrew/core).
==> New Formulae
roapi
==> Updated Formulae
Updated 90 formulae.

==> Downloading https://ghcr.io/v2/homebrew/core/p11-kit/manifests/0.24.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/p11-kit/blobs/sha256:dc5592e236946f8a3e57998214d13f1c0db7dab5bdd9602bb0c4a84dacf2d17a
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:dc5592e236946f8a3e57998214d13f1c0db7dab5bdd9602bb0c4a84dacf2d17a?se=2022-01-19T08%3A1
######################################################################## 100.0%
==> Downloading https://github.com/opencv/opencv_contrib/archive/4.5.4.tar.gz
Already downloaded: /Users/igla/Library/Caches/Homebrew/downloads/3dd531a68bbd9bbf3875668a83cecdbda09e89b81c57f7e0e6e4a868d6280d04--opencv_contrib-4.5.4.tar.gz
==> Downloading https://github.com/opencv/opencv/archive/4.5.4.tar.gz
Already downloaded: /Users/igla/Library/Caches/Homebrew/downloads/f41dd9e2e6ae006c84a9758c26863fe53825f958bc11aa5e9870a641136d6e59--opencv-4.5.4.tar.gz
==> Installing dependencies for opencv: p11-kit
==> Installing opencv dependency: p11-kit
==> Pouring p11-kit--0.24.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/p11-kit/0.24.1: 67 files, 3.6MB
==> Installing opencv
==> cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET= -DBUILD_JASPER=OFF -DBUILD_JPEG=OFF -DBUILD_OPENEXR=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_PNG=OFF -DBUILD_PROTOBUF=OFF -DBUILD_TE
==> make
Last 15 lines from /Users/igla/Library/Logs/Homebrew/opencv/02.make:
cd /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DCVAPI_EXPORTS -DHAVE_PROTOBUF=1 -DOPENCV_DNN_EXTERNAL_PROTOBUF=1 -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCV_CPU_COMPILE_AVX=1 -DCV_CPU_DISPATCH_MODE=AVX -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/3rdparty/ippicv/ippicv_mac/icv/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/3rdparty/ippicv/ippicv_mac/iw/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/dnn/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/core/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/imgproc/include -isystem /usr/local/include/eigen3 -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-prototypes -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-sign-compare -Wno-invalid-offsetof -O3 -DNDEBUG  -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -std=c++11  -mavx -MD -MT modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx.cpp.o -MF CMakeFiles/opencv_dnn.dir/layers/layers_common.avx.cpp.o.d -o CMakeFiles/opencv_dnn.dir/layers/layers_common.avx.cpp.o -c /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn/layers/layers_common.avx.cpp
[ 48%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.o
cd /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DCVAPI_EXPORTS -DHAVE_PROTOBUF=1 -DOPENCV_DNN_EXTERNAL_PROTOBUF=1 -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCV_CPU_COMPILE_AVX2=1 -DCV_CPU_COMPILE_AVX=1 -DCV_CPU_COMPILE_FMA3=1 -DCV_CPU_COMPILE_FP16=1 -DCV_CPU_DISPATCH_MODE=AVX2 -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/3rdparty/ippicv/ippicv_mac/icv/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/3rdparty/ippicv/ippicv_mac/iw/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/dnn/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/core/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/imgproc/include -isystem /usr/local/include/eigen3 -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-prototypes -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-sign-compare -Wno-invalid-offsetof -O3 -DNDEBUG  -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -std=c++11  -mf16c -mfma -mavx -mavx2 -MD -MT modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.o -MF CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.o.d -o CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.o -c /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn/layers/layers_common.avx2.cpp
[ 48%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx2.cpp.o
cd /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DCVAPI_EXPORTS -DHAVE_PROTOBUF=1 -DOPENCV_DNN_EXTERNAL_PROTOBUF=1 -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCV_CPU_COMPILE_AVX2=1 -DCV_CPU_COMPILE_AVX=1 -DCV_CPU_COMPILE_FMA3=1 -DCV_CPU_COMPILE_FP16=1 -DCV_CPU_DISPATCH_MODE=AVX2 -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/3rdparty/ippicv/ippicv_mac/icv/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/3rdparty/ippicv/ippicv_mac/iw/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/dnn/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/core/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/imgproc/include -isystem /usr/local/include/eigen3 -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-prototypes -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-sign-compare -Wno-invalid-offsetof -O3 -DNDEBUG  -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -std=c++11  -mf16c -mfma -mavx -mavx2 -MD -MT modules/dnn/CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx2.cpp.o -MF CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx2.cpp.o.d -o CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx2.cpp.o -c /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn/int8layers/layers_common.avx2.cpp
[ 48%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.o
cd /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DCVAPI_EXPORTS -DHAVE_PROTOBUF=1 -DOPENCV_DNN_EXTERNAL_PROTOBUF=1 -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCV_CPU_COMPILE_AVX2=1 -DCV_CPU_COMPILE_AVX512_COMMON=1 -DCV_CPU_COMPILE_AVX512_SKX=1 -DCV_CPU_COMPILE_AVX=1 -DCV_CPU_COMPILE_AVX_512F=1 -DCV_CPU_COMPILE_FMA3=1 -DCV_CPU_COMPILE_FP16=1 -DCV_CPU_DISPATCH_MODE=AVX512_SKX -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/3rdparty/ippicv/ippicv_mac/icv/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/3rdparty/ippicv/ippicv_mac/iw/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/dnn/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/core/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/imgproc/include -isystem /usr/local/include/eigen3 -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-prototypes -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-sign-compare -Wno-invalid-offsetof -O3 -DNDEBUG  -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -std=c++11  -mf16c -mfma -mavx -mavx2 -mavx512f -mavx512f -mavx512cd -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq -MD -MT modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.o -MF CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.o.d -o CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.o -c /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn/layers/layers_common.avx512_skx.cpp
[ 48%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx512_skx.cpp.o
cd /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DCVAPI_EXPORTS -DHAVE_PROTOBUF=1 -DOPENCV_DNN_EXTERNAL_PROTOBUF=1 -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCV_CPU_COMPILE_AVX2=1 -DCV_CPU_COMPILE_AVX512_COMMON=1 -DCV_CPU_COMPILE_AVX512_SKX=1 -DCV_CPU_COMPILE_AVX=1 -DCV_CPU_COMPILE_AVX_512F=1 -DCV_CPU_COMPILE_FMA3=1 -DCV_CPU_COMPILE_FP16=1 -DCV_CPU_DISPATCH_MODE=AVX512_SKX -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/3rdparty/ippicv/ippicv_mac/icv/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/3rdparty/ippicv/ippicv_mac/iw/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/dnn/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/core/include -I/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/modules/imgproc/include -isystem /usr/local/include/eigen3 -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-prototypes -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-sign-compare -Wno-invalid-offsetof -O3 -DNDEBUG  -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -std=c++11  -mf16c -mfma -mavx -mavx2 -mavx512f -mavx512f -mavx512cd -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq -MD -MT modules/dnn/CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx512_skx.cpp.o -MF CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx512_skx.cpp.o.d -o CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx512_skx.cpp.o -c /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn/int8layers/layers_common.avx512_skx.cpp
[ 48%] Linking CXX shared library ../../lib/libopencv_dnn.dylib
cd /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn && /usr/local/Cellar/cmake/3.22.1/bin/cmake -E cmake_link_script CMakeFiles/opencv_dnn.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-prototypes -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-sign-compare -Wno-invalid-offsetof -O3 -DNDEBUG  -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names   -Wl,-dead_strip -compatibility_version 4.5.0 -current_version 4.5.4 -o ../../lib/libopencv_dnn.4.5.4.dylib -install_name @rpath/libopencv_dnn.4.5.dylib CMakeFiles/opencv_dnn.dir/opencv-caffe.pb.cc.o CMakeFiles/opencv_dnn.dir/opencv-onnx.pb.cc.o CMakeFiles/opencv_dnn.dir/attr_value.pb.cc.o CMakeFiles/opencv_dnn.dir/function.pb.cc.o CMakeFiles/opencv_dnn.dir/graph.pb.cc.o CMakeFiles/opencv_dnn.dir/op_def.pb.cc.o CMakeFiles/opencv_dnn.dir/tensor.pb.cc.o CMakeFiles/opencv_dnn.dir/tensor_shape.pb.cc.o CMakeFiles/opencv_dnn.dir/types.pb.cc.o CMakeFiles/opencv_dnn.dir/versions.pb.cc.o CMakeFiles/opencv_dnn.dir/src/caffe/caffe_importer.cpp.o CMakeFiles/opencv_dnn.dir/src/caffe/caffe_io.cpp.o CMakeFiles/opencv_dnn.dir/src/caffe/caffe_shrinker.cpp.o CMakeFiles/opencv_dnn.dir/src/darknet/darknet_importer.cpp.o CMakeFiles/opencv_dnn.dir/src/darknet/darknet_io.cpp.o CMakeFiles/opencv_dnn.dir/src/debug_utils.cpp.o CMakeFiles/opencv_dnn.dir/src/dnn.cpp.o CMakeFiles/opencv_dnn.dir/src/graph_simplifier.cpp.o CMakeFiles/opencv_dnn.dir/src/halide_scheduler.cpp.o CMakeFiles/opencv_dnn.dir/src/ie_ngraph.cpp.o CMakeFiles/opencv_dnn.dir/src/init.cpp.o CMakeFiles/opencv_dnn.dir/src/int8layers/batch_norm_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/int8layers/convolution_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/int8layers/elementwise_layers.cpp.o CMakeFiles/opencv_dnn.dir/src/int8layers/eltwise_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/int8layers/fully_connected_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/int8layers/pooling_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/int8layers/quantization_utils.cpp.o CMakeFiles/opencv_dnn.dir/src/int8layers/scale_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/int8layers/softmax_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/accum_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/batch_norm_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/blank_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/concat_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/const_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/convolution_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/correlation_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/crop_and_resize_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/cumsum_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/detection_output_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/elementwise_layers.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/eltwise_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/flatten_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/flow_warp_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/fully_connected_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/layers_common.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/lrn_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/max_unpooling_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/mvn_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/normalize_bbox_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/not_implemented_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/padding_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/permute_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/pooling_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/prior_box_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/proposal_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/recurrent_layers.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/region_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/reorg_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/reshape_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/resize_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/scale_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/shuffle_channel_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/slice_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/softmax_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/split_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/model.cpp.o CMakeFiles/opencv_dnn.dir/src/nms.cpp.o CMakeFiles/opencv_dnn.dir/src/onnx/onnx_graph_simplifier.cpp.o CMakeFiles/opencv_dnn.dir/src/onnx/onnx_importer.cpp.o CMakeFiles/opencv_dnn.dir/src/op_halide.cpp.o CMakeFiles/opencv_dnn.dir/src/op_inf_engine.cpp.o CMakeFiles/opencv_dnn.dir/src/op_vkcom.cpp.o CMakeFiles/opencv_dnn.dir/src/tengine4dnn/src/tengine_graph_convolution.cpp.o CMakeFiles/opencv_dnn.dir/src/tensorflow/tf_graph_simplifier.cpp.o CMakeFiles/opencv_dnn.dir/src/tensorflow/tf_importer.cpp.o CMakeFiles/opencv_dnn.dir/src/tensorflow/tf_io.cpp.o CMakeFiles/opencv_dnn.dir/src/torch/THDiskFile.cpp.o CMakeFiles/opencv_dnn.dir/src/torch/THFile.cpp.o CMakeFiles/opencv_dnn.dir/src/torch/THGeneral.cpp.o CMakeFiles/opencv_dnn.dir/src/torch/torch_importer.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/avg_pool_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/concat_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/conv48_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/conv_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/dw_conv_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/lrn_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/max_pool_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/permute_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/prior_box_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/relu_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/shader/softmax_spv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/buffer.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/context.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/internal.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_base.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_concat.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_conv.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_lrn.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_permute.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_pool.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_prior_box.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_relu.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_softmax.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/src/tensor.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/vulkan/vk_functions.cpp.o CMakeFiles/opencv_dnn.dir/src/vkcom/vulkan/vk_loader.cpp.o CMakeFiles/opencv_dnn.dir/layers/layers_common.avx.cpp.o CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.o CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx2.cpp.o CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.o CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx512_skx.cpp.o  -Wl,-rpath,/tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/lib ../../lib/libopencv_imgproc.4.5.4.dylib ../../3rdparty/lib/libippiw.a ../../3rdparty/ippicv/ippicv_mac/icv/lib/intel64/libippicv.a /usr/local/lib/libprotobuf.dylib /usr/local/opt/openblas/lib/libopenblas.dylib ../../lib/libopencv_core.4.5.4.dylib 
cd /tmp/opencv-20220118-18052-vmz45g/opencv-4.5.4/build/modules/dnn && /usr/local/Cellar/cmake/3.22.1/bin/cmake -E cmake_symlink_library ../../lib/libopencv_dnn.4.5.4.dylib ../../lib/libopencv_dnn.4.5.dylib ../../lib/libopencv_dnn.dylib
[ 48%] Built target opencv_dnn
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

### What did you expect to happen?

Opencv with java support installed successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --build-from-source opencv
```

**Comment by MikeMcQuaid** [comment]
> ### `brew doctor` output
> ```shell
> Too long output
> ```
> * [x]  I have resolved all warnings from `brew doctor` and that did not fix my problem.

You didn't do this.

> ```shell
> brew install --build-from-source opencv
> ```

We don't support building from source.

Also, in future please open formula issues in homebrew-core (once you've fixed all your `brew doctor` issues).
