### ISSUE TITLE
percona-server56 SSL config option is not correct

### ISSUE THREAD

**Issue by VGerris** [Homebrew/brew#1276]
Hi,

I want to report that after upgrading to MacOS Sierra I was not able to build the Perl DBD::mysql module. I kept getting an error that the -lssl option was incorrect.
After searching I found that it should point to the openssl library, which was not setup correctly.
It was determined by Perl by the command:
 /usr/local/Cellar/percona-server56/5.6.28-76.1/bin/mysql_config

The options there were:
libs=" $ldflags -L$pkglibdir  -lperconaserverclient  -L/usr/local/opt/openssl/lib -lssl -lcrypto "

I changed that to:
libs=" $ldflags -L$pkglibdir  -lperconaserverclient  -L/usr/local/opt/openssl/lib -lssl -lcrypto "
(add -L/usr/local/opt/openssl/lib)
that points to the SSL libraries installed by brew.

I got a hint when I did a brew reinstall openssl and saw something about Apple and their own TLS libraries.

I would submit a pull request if I knew this wat the proper fix, a better fix would probably be to link to the shipped libraries if compatible.

**Comment by MikeMcQuaid** [comment]
> I would submit a pull request if I knew this wat the proper fix, a better fix would probably be to link to the shipped libraries if compatible.

Yes, we will need to specify the path to the buildsystem. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by VGerris** [comment]
Hi Mike,

I tried to find it and ended up here:
https://github.com/VGerris/homebrew-core/blob/master/Formula/percona-server.rb
I do not see any source that would cause the problem.
I have percona-server56 still running, maybe it is a leftover from an older brew, I cannot find this any more in the formulas?
Am I missing something :)?

thank you!

**Comment by MikeMcQuaid** [comment]
Here's the 5.6 version: https://github.com/Homebrew/homebrew-versions/blob/master/percona-server56.rb.

My guess is it's handled automatically in the buildsystem of newer versions. Maybe you need something like this https://github.com/Homebrew/homebrew-versions/blob/master/mysql56.rb#L69?

**Comment by VGerris** [comment]
Thank you for the links. I am unable to find the options there either. The problem is that in the mysql_config command, this parameter ends up wrongly. I did a reinstall of percona-server56 with an up to date brew, so I think the problem still persists. 
I looked in the source package and it is probably going wrong here:
scripts/mysql_config.sh
It has :
# Create options 
# We intentionally add a space to the beginning and end of lib strings, simplifies replace later
libs=" $ldflags -L$pkglibdir @RPATH_OPTION@ -lperconaserverclient @ZLIB_DEPS@ @NON_THREADED_LIBS@"
libs="$libs @openssl_libs@ @STATIC_NSS_FLAGS@ "
libs_r=" $ldflags -L$pkglibdir @RPATH_OPTION@ -lperconaserverclient @ZLIB_DEPS@ @CLIENT_LIBS@ @openssl_libs@ "
embedded_libs=" $ldflags -L$pkglibdir @RPATH_OPTION@ -lmysqld @LIBDL@ @ZLIB_DEPS@ @LIBS@ @WRAPLIBS@ @openssl_libs@ "
embedded_libs="$embedded_libs @QUOTED_CMAKE_CXX_LINK_FLAGS@"

which end up in the mysql_config command.
I am not familiar with the @name@ concept and I do not know if this should be a source patch or a brew action?

**Comment by MikeMcQuaid** [comment]
@VGerris It will be possible to specify the OpenSSL paths to CMake using a `-D` variable.

**Comment by VGerris** [comment]
Hi Mike,

Can you be more specific?
I tried to google this and I cannot find any documentation.
If you know how it's done, can you take the honor to add it :)?

I can't figure it out and this is still an issue.

Kind regards,
Vincent

**Comment by MikeMcQuaid** [comment]
@VGerris I suspect you need one of these variables https://cmake.org/cmake/help/v3.6/module/FindOpenSSL.html#result-variables like so with e.g. `-D OPENSSL_INCLUDE_DIR`
