### ISSUE TITLE
brew update: show old version in update messages

### ISSUE THREAD

**Issue by abitrolly** [Homebrew/brew#12760]
### Provide a detailed description of the proposed feature

`brew update` doesn't show what was the previous version before update.
```
$ brew update    
Updated Homebrew from db648bcde to 249b0439e.
...
==> Homebrew was updated to version 3.3.11
The changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/3.3.11
```
In addition, neither db648bcde or 249b0439e match version hashes listed at https://github.com/Homebrew/brew/releases

The proposal is to change the output to this.
```
$ brew update    
Updated Homebrew from 3.3.9 (db648bcde) to 3.3.11 (249b0439e).
...
==> Homebrew 3.3.9 was updated to version 3.3.11
Changelogs:
  https://github.com/Homebrew/brew/releases/tag/3.3.10
  https://github.com/Homebrew/brew/releases/tag/3.3.11
Commit history:
  https://github.com/Homebrew/brew/compare/3.3.9...3.3.11
```

### What is the motivation for the feature?

I'd like to read what new features/fixes have I got since the last time I've updated - not just about stuff in latest release.

### How will the feature be relevant to at least 90% of Homebrew users?

They could read what exactly had changed in their `brew` install after update, not just about the latest release.

### What alternatives to the feature have been considered?

Finding the first commit hash manually and then figure out what version it was, then go to release pages and scroll to read from that version.

**Comment by MikeMcQuaid** [comment]
Makes sense to me, I'd be up for reviewing a PR for: 

> Updated Homebrew from 3.3.9 (db648bcde) to 3.3.11 (249b0439e).

> Changelogs:
>   https://github.com/Homebrew/brew/releases/tag/3.3.10
>   https://github.com/Homebrew/brew/releases/tag/3.3.11
> Commit history:
>   https://github.com/Homebrew/brew/compare/3.3.9...3.3.11

This part seems harder to calculate and a bit excessive really.

**Comment by abitrolly** [comment]
Added PR, and now I see that `brew update` actually doesn't update to a released version, it fetches latest changes from the `git`. That's why updated hashes don't match releases.
