### ISSUE TITLE
Suggest fix for SSL certificate failures on macOS

### ISSUE THREAD

**Issue by jdempcy** [Homebrew/brew#12775]
### Provide a detailed description of the proposed feature

I was just trying to install Postgres on a new clean Mac install and the curl GET from their server failed due to an expired certificate.

I was able to fix it with:

```
set -x HOMEBREW_FORCE_BREWED_CURL 1
set -x HOMEBREW_FORCE_BREWED_CA_CERTIFICATES 1
```

(Actually, I think either of these would fix it, perhaps! So maybe both are not necessary.)

In any case, that fixed it and I was able to install Postgres without problem!

### What is the motivation for the feature?

It would be nice if SSL failures of curl just had a message that said:
```
If you are OK with an insecure connection, try this:
set -x HOMEBREW_FORCE_BREWED_CURL 1
set -x HOMEBREW_FORCE_BREWED_CA_CERTIFICATES 1
```
Or something along those lines.

### How will the feature be relevant to at least 90% of Homebrew users?

It's only relevant when there are SSL problems. To be honest I haven't seen these very often.  But every now and then they come up and it would be nice to tell people a quick workaround. I was seeing if brew would allow me to pass -k or --insecure (as curl does) and, it doesn't. Luckily I found the solution by looking here on Homebrew issues, in about 2 minutes, so it didn't take up any time. But I could see how someone who was not able to find the solution might get frustrated.

### What alternatives to the feature have been considered?

There's a good workaround, which is to just look on the issue tracker here for "ssl" and find a thread where they talk about exactly this issue. Then you find the solution to set HOMEBREW_FORCE_BREWED_CURL and/or HOMEBREW_FORCE_BREWED_CA_CERTIFICATES.

**Comment by carlocab** [comment]
There should be no need to set `HOMEBREW_FORCE_BREWED_CURL` or `HOMEBREW_FORCE_BREWED_CA_CERTIFICATES` since `brew` handles setting these when they're needed. (They're still available for you to set if you want to, but that's unnecessary.)

If you've found need to, then this is probably a bug rather than a feature request.

What is the output of `brew config` and `brew doctor`?

**Comment by jdempcy** [comment]
Aha! I think I found it. Brew config looks normal, but brew doctor gives me
a warning about this old version of macOS, which would make sense because
older versions often don't have up-to-date security around SSL.

```
brew config
HOMEBREW_VERSION: 3.3.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 537036ab3627b65d71dfa920b98d43774f861dec
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5de767db7b545a0c843197927fe9502b293f287e
Core tap last commit: 13 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 =>
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 11.0.0 build 1100
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1
```

```
brew doctor
Please note that these warnings are just used to help the Homebrew
maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
```
This must be the culprit! The macOS version. Well, since this is an
unsupported version, feel free to go ahead and close this feature request.
Or if it's easy, it would be nice to simply default to using
HOMEBREW_FORCE_BREWED_CA_CERTIFICATES
if macOS is older than x.x version.

Thanks for your help!

--
Jonah Dempcy
T 206.226.2857 | E ***@***.***
Follow on Facebook <https://www.facebook.com/jdempcy> | @jdempcy
<http://www.twitter.com/jdempcy> | /in/jdempcy
<http://www.linkedin.com/in/jdempcy>

**Comment by jdempcy** [comment]
Aha! I think I found it. Brew config looks normal, but brew doctor gives me
a warning about this old version of macOS, which would make sense because
older versions often don't have up-to-date security around SSL.

```
brew config
HOMEBREW_VERSION: 3.3.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 537036a
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5de767db7b545a0c843197927fe9502b293f287e
Core tap last commit: 13 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 =>
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 11.0.0 build 1100
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1

brew doctor
Please note that these warnings are just used to help the Homebrew
maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
```

This must be the culprit! The macOS version. Well, since this is an
unsupported version, feel free to go ahead and close this feature request.
Or if it's easy, it would be nice to simply default to using
HOMEBREW_FORCE_BREWED_CA_CERTIFICATES
if macOS is older than x.x version.

Thanks for your help!

**Comment by Bo98** [comment]
HOMEBREW_FORCE_BREWED_CA_CERTIFICATES should already be automatically set for < 10.15.6: https://github.com/Homebrew/brew/blob/c2c0216e7558f9729d7c03c0f127dbd738d15242/Library/Homebrew/brew.sh#L462-L467
