### ISSUE TITLE
Installing homebrew issue

### ISSUE THREAD

**Issue by JustSteveKing** [Homebrew/brew#12785]
### `brew config` output

```shell
n/a
```

### `brew doctor` output

```shell
n/a
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was attempting to install homebrew on a new MacBook, however this keeps failing.

### What happened (include all command output)?

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew

Press RETURN to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R steve:admin /opt/homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 118 (delta 53), reused 106 (delta 46), pack-reused 0
Receiving objects: 100% (118/118), 51.76 KiB | 1.44 MiB/s, done.
Resolving deltas: 100% (53/53), done.
From https://github.com/Homebrew/brew
 * [new branch]          dependabot/bundler/Library/Homebrew/msgpack-1.4.4 -> origin/dependabot/bundler/Library/Homebrew/msgpack-1.4.4
 * [new branch]          dependabot/bundler/Library/Homebrew/sorbet-0.5.9542 -> origin/dependabot/bundler/Library/Homebrew/sorbet-0.5.9542
   768b17239..129e5bb70  master     -> origin/master
 * [new tag]             3.3.12     -> 3.3.12
HEAD is now at 129e5bb70 Merge pull request #12782 from Homebrew/dependabot/bundler/Library/Homebrew/rubocop-rspec-2.8.0
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
^Cfatal: index-pack failed
Failed during: /opt/homebrew/bin/brew update --force --quiet
```

### What did you expect to happen?

I expected homebrew to install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
n/a
```

**Comment by MikeMcQuaid** [comment]
> ```shell
> n/a
> ```

Don't do this. If you have to do this: it's a sign you're filing in the wrong repository.



> ```shell
> HEAD is now at 129e5bb70 Merge pull request #12782 from Homebrew/dependabot/bundler/Library/Homebrew/rubocop-rspec-2.8.0
> error: Not a valid ref: refs/remotes/origin/master
> fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> ^Cfatal: index-pack failed
> ```

This is an issue with your connection to GitHub. Nothing we can do about it here.

**Comment by carlocab** [comment]
See Homebrew/discussions#666 for related problems and workarounds.

**Comment by JustSteveKing** [comment]
Thanks @carlocab I will check it out
