### ISSUE TITLE
There is no supported (or documented) workflow for tap authors

### ISSUE THREAD

**Issue by rickmark** [Homebrew/brew#12800]
### Provide a detailed description of the proposed feature

Because `brew` is not packaged as a gem
You cannot add it to a `Gemfile` and `rake` the repo to ensure its sane on each PR / commit / `overcommit`
This leads to custom (even in the case of `homebrew-core`) workflows to ensure a tap stays valid

There are two possibilities

1) make `homebrew` a gem to get access to the runtime and `class Formula` for validation
2) create a separate gem for `homebrew-tap` or such that does the validation outside core

### What is the motivation for the feature?

Ensuring tap creation and maintenance is simple

If this is already possible - it is not documented well in the tap authoring documentation

### How will the feature be relevant to at least 90% of Homebrew users?

Taps will be higher quality including `homebrew-core`

### What alternatives to the feature have been considered?

Building our own validation - painful and not reusable - also not in sync with `brew audit`

**Comment by carlocab** [comment]
Have you had a look at the workflows generated by `brew tap-new`?

**Comment by rickmark** [comment]
So just saw that - there's no documentation for existing taps to use those templates

Why I said it might be a doc problem - also brew core doesn't use this model

**Comment by rickmark** [comment]
yes - to be clear - its is `.github/tests.yaml` - you have an implicit dependency on GitHub

a better plan is to be able to `gem homebrew-tap` which brings in `rake tap:tests` 

you're already dependent on rake which is basically de facto in ruby, so why not use it to run the tasks and make the GitHub call that

**Comment by carlocab** [comment]
> So just saw that - there's no documentation for existing taps to use those templates

Here's some documentation:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

It could probably use updating and polishing in some places, but I haven't heard any complaints from people I've referred these docs to.

> Why I said it might be a doc problem - also brew core doesn't use this model

The workflows generated by `brew tap-new` are built around `brew test-bot`, which is the same testing framework we use in Homebrew/core.

> yes - to be clear - its is `.github/tests.yaml` - you have an implicit dependency on GitHub

Actually, this dependency is explicit. From `man brew`:

```
   test-bot [options] [formula]
       Tests the full lifecycle of a Homebrew change to a tap (Git repository). For example, for a GitHub Actions pull request that
       changes a formula brew test-bot will ensure the system is cleaned and set up to test the formula, install the formula, run
       various tests and checks on it, bottle (package) the binaries and test formulae that depend on it to ensure they aren´t broken
       by these changes.

       Only supports GitHub Actions as a CI provider. This is because Homebrew uses GitHub Actions and it´s freely available for public
       and private use with macOS and Linux workers.
```

> a better plan is to be able to `gem homebrew-tap` which brings in `rake tap:tests`
> 
> you're already dependent on rake which is basically de facto in ruby, so why not use it to run the tasks and make the GitHub call that
> 
> ugh toppost nightmare:
> 
> but most validation shouldn't need brew either - thus the "gem" option even if its a validation now `gem install homebrew` to get get enough of the land path to get Formula etc

That would certainly make things more portable, but we've found little need for it, nor have there been many users who've requested such a change. In fact, this is the first I'm hearing of it.

This is probably in large part because `brew test-bot` is really just a wrapper around calling a bunch of `brew` commands: `brew install`, `brew bottle`, `brew audit`, `brew test`, etc. You could probably easily roll your own testing framework if you have an environment with `brew` installed -- in shell scripts, even.

Turning `brew` into a Gem you can `require` will probably take a fairly significant overhaul of the codebase.

**Comment by rickmark** [comment]
so `hack-different/homebrew-jailbreak` is a broadly (probably the most) brew linux community

its kinda expected for our work that `overcommit` be able to validate correctness locally without a PR

this is hard when the entire CI is based on GitHub

an initial version for us is a rake task for tests that does broadly the same thing as the GitHub CI - but there's no technical reason they be on macOS or that it be defined in a proprietary way

Stay tuned as we take it to a x-plat version

**Comment by rickmark** [comment]
oh crud - `brew test-bot` isn't well documented (esp for those who didn't bring up their tap from the template)

**Comment by carlocab** [comment]
> its kinda expected for our work that `overcommit` be able to validate correctness locally without a PR

As mentioned, our testing framework really boils down to just running a few `brew` commands, so this is certainly possible.

> oh crud - `brew test-bot` isn't well documented (esp for those who didn't bring up their tap from the template)

This is also true. PRs to improve documentation welcome.

> `brew commands` does not list it

You probably don't have the tap installed. Do `brew tap homebrew/test-bot` and you will see `test-bot` in `brew commands` under `External Commands`.

**Comment by rickmark** [comment]
Will work on doc PRs

it doesn't seem that taps are 'external' to the non-core team so will work to resolve that

Valid an closing issue

I'd only hope that home-brew can also publish a gem to bring in `Library/` and we can setup `tasks/tests.take` under that to be less GH dependent and more in line with common `Gemfile` / `Rakefile` usage

**Comment by MikeMcQuaid** [comment]
Homebrew is never going to be published as a gem, sorry. As @carlocab has pointed out: `brew tap-new` and `brew test-bot` are our supported options for tap authors. If you want to not use GitHub: that's of course your right but it isn't a paved path so you'll need to be willing to figure it out yourself.
