### ISSUE TITLE
Support issues for private registries

### ISSUE THREAD

**Issue by shaunwarman** [Homebrew/brew#12825]
### `brew config` output

```shell
% brew config
HOMEBREW_VERSION: 3.2.12
HEAD: 48bbc53fb8bbdc7aaf5b8f2996081fea1f51ca4e
Last commit: 5 months ago
Core tap HEAD: 516f0570ebc10d815ad09c64d31470322da5cd3c
Core tap last commit: 29 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_ARTIFACT_DOMAIN: https://internal.artifactory/artifactory/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_DOCKER_REGISTRY_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install brew packages from internal private artifactory which has a remote repo setup to ghcr.io.

### What happened (include all command output)?

% brew install collectd --verbose
==> Downloading https://ghcr.io/v2/homebrew/core/libgpg-error/manifests/1.44
==> Downloading from https://internal.artifactory/artifactory/homebrew/v2/homebrew/core/libgpg-error/manifests/1.44
curl: (22) The requested URL returned error: 401
Error: collectd: Failed to download resource "libgpg-error_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/libgpg-error/manifests/1.44

### What did you expect to happen?

Proxy through artifactory to ghcr.io and install collectd plugin.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I've tried using:
HOMEBREW_DOCKER_REGISTRY_TOKEN
HOMEBREW_ARTIFACT_DOMAIN
HOMEBREW_CORE_GIT_REMOTE
HOMEBREW_BREW_GIT_REMOTE
HOMEBREW_REGISTRY_ACCESS_TOKEN

I've even tried setting `QQ==` as access token. The artifactory instances have access to ghcr.io, but for some reason the authentication is an issue.

Unsetting HOMEBREW_DOCKER_REGISTRY_TOKEN to ideally default to QQ== gives 404.

Relates to: https://github.com/Homebrew/brew/pull/11766
```

**Comment by shaunwarman** [comment]
Relates to: https://github.com/Homebrew/brew/pull/11766

**Comment by MikeMcQuaid** [comment]
We don't support Artifactory, you'll need to speak to JFrog about this.
