### ISSUE TITLE
brew linkapps python fails, but still says succeeded

### ISSUE THREAD

**Issue by ghstridr** [Homebrew/brew#1282]
### Bug reports:

'brew linkapps python' fails, but still says it succeeded

brew linkapps python
Linking: /usr/local/opt/python/IDLE.app
ln: /Applications/IDLE.app: Permission denied
Linking: /usr/local/opt/python/Python Launcher.app
ln: /Applications/Python Launcher.app: Permission denied
Linked 2 apps to /Applications

shouldn't linking be to ~/Applications ?. Linking to the users home directory seems to be in keeping with the Brew standards and leaving the system level stuff alone.

**Comment by tdsmith** [comment]
Probably not; /usr/local is systemwide. I think we'd accept a PR to make the "Linked 2 apps" more correct in the face of errors.
