### ISSUE TITLE
Installation of Homebrew itself fails with syntax errors

### ISSUE THREAD

**Issue by JamesMGreene** [Homebrew/brew#12840]
### `brew config` output

```shell
N/A
```

### `brew doctor` output

```shell
N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install Homebrew

### What happened (include all command output)?

```shell
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

sh: -c: line 385: syntax error near unexpected token `<'
sh: -c: line 385: `  done < <(which -a "$1")'
```

### What did you expect to happen?

Successful installation and/or warning that Homebrew was already installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
N/A
```

**Comment by Bo98** [comment]
Homebrew requires Bash, so use `bash -c` instead.

**Comment by JamesMGreene** [comment]
@Bo98 Thanks for that speedy clarification! Not sure how I ended up with that. 🤔  Maybe because it was within a bash script and I erroneously thought that `sh` would therefore refer to bash rather than the default shell (or whatever it is actually doing). 🤷🏻‍♂️
