### ISSUE TITLE
Allow taps with its formula in the same repository to be installed via `brew install someuser/someformula` 

### ISSUE THREAD

**Issue by KS1019** [Homebrew/brew#12869]
### Provide a detailed description of the proposed feature

This would allow users to install taps that contains its formula in the same repository. The command would look like 
`brew install somerepo/sometap`.

- This assumes the tap and the repository have the same name.
- We could also look for `HomebrewFormula/` and equivalent directory to find the formula when they do not share the same name.

### What is the motivation for the feature?

Currently, this kind of repository requires users to run two lines of command.
```shell
brew tap user/formula URL
brew install formula
```

With this, it could be done as a oneliner
```shell
brew install user/repo
```

So this could potentially save some of the users' time.

### How will the feature be relevant to at least 90% of Homebrew users?

Since we can do `brew install user/repo/formula`, it feels unnatural that we cannot do `brew install user/formula` and it is potentially creating confusion.

### What alternatives to the feature have been considered?

Using `brew tap user/formula URL && brew install formula`

**Comment by MikeMcQuaid** [comment]
`brew install user/repo/formula` already does this 🎉

**Comment by gromgit** [comment]
> Currently, this kind of repository requires users to run two lines of command.
> 
> ```shell
> brew tap user/formula URL
> brew install formula
> ```
> 
> With this, it could be done as a oneliner
> 
> ```shell
> brew install user/repo
> ```

If you have to specify the tap URL explicitly, `brew tap` needs to be explicit too.

And if your formula is at `https://github.com/user/homebrew-tap/Formula/formula.rb`, you already have a one-liner:
```
brew install user/tap/formula
```

**Comment by KS1019** [comment]
@MikeMcQuaid
Hi, thank you for your quick reply!

I should have included this in the first place but I meant taps like [salesforce/policy_sentry: IAM Least Privilege Policy Generator](https://github.com/salesforce/policy_sentry) and I believe this kind of taps cannot be installed via `brew install user/repo/formula` because Homebrew assumes homebrew- prefix which results in failure in resolving the repo name.

@gromgit 
You're right but I still think this could be useful since many repositories use the same name for their formula so if we could assume that repo has the same name as formula, I think explicit tap won't be needed.

Please let me know what you think!

Thank you in advance.

**Comment by gromgit** [comment]
Not a maintainer, but the mandated `homebrew-` prefix has a number of benefits:
1. it greatly increases the likelihood that the repo auto-tapped this way is a proper Homebrew tap
2. it eliminates the need to guess and try multiple repo URL options
3. the formula files are separated from the main software repo, minimizing the tap size

The `salesforce/policy_sentry` repo you linked to illustrates that final point brilliantly. Few folks want to permanently tap multiple megabytes of source code that's only needed once (and will be pulled down separately during the `brew install` anyway), _and_ multiple megabytes of `.git` directory contents that's never needed by most Homebrew users, just to save a few keystrokes in a command that's only run once.

**Comment by KS1019** [comment]
> Few folks want to permanently tap multiple megabytes of source code that's only needed once (and will be pulled down separately during the brew install anyway), and multiple megabytes of .git directory contents that's never needed by most Homebrew users, just to save a few keystrokes in a command that's only run once.

This does make sense a lot. Thanks, @gromgit for your comment!

**Comment by MikeMcQuaid** [comment]
Agreed with @gromgit here!
