### ISSUE TITLE
`brew --prefix openssl` returns a path to `openssl@3` which doesn't exist

### ISSUE THREAD

**Issue by franzinc** [Homebrew/brew#12879]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: d603fd6426ddae27327bb51afb085653eb2d84a7
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5b940ea7dc51725612bcf86fca6e9dd5e49be546
Core tap last commit: 30 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 10.3
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The contents of the SDKs in your Command Line Tools (CLT) installation do not match the SDK folder names.
A clean reinstall of Command Line Tools (CLT) should fix this.

Remove the broken installation before reinstalling:
  sudo rm -rf /Library/Developer/CommandLineTools

Install the Command Line Tools:
  xcode-select --install


Warning: Your Xcode (10.3) is too outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.


Warning: Your Xcode (10.3) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I need the path to the OpenSSL libraries so I can set `DYLD_LIBRARY_PATH`.

### What happened (include all command output)?

On all machines which are up to date, I see this:

    macsup:~ admin$ brew list | grep openssl
    openssl@1.1
    macsup:~ admin$ brew --prefix openssl
    /usr/local/opt/openssl@3
    macsup:~ admin$ ls -ld /usr/local/opt/openssl*
    lrwxr-xr-x 1 admin admin 28 Jan 28 09:23 /usr/local/opt/openssl -> ../Cellar/openssl@1.1/1.1.1m
    lrwxr-xr-x 1 admin admin 28 Jan 28 09:23 /usr/local/opt/openssl@1.1 -> ../Cellar/openssl@1.1/1.1.1m
    macsup:~ admin$ 

### What did you expect to happen?

I expected `brew --prefix openssl` to return what it used to, the path to the installed OpenSSL files.  It wasn't long ago that this worked perfectly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
They are already above.
```

**Comment by carlocab** [comment]
This is (mostly) intended behaviour. The unversioned `openssl` alias refers to `openssl@3`:
```
❯ brew info openssl
openssl@3: stable 3.0.1 (bottled) [keg-only]
```
`openssl` used to refer to `openssl@1.1`, but the convention in Homebrew (with two exceptions) is that the unversioned name refers to the latest version.

**Comment by franzinc** [comment]
How can I find the path to the 1.1 version that is installed?

**Comment by franzinc** [comment]
> This is (mostly) intended behaviour. The unversioned `openssl` alias refers to `openssl@3`:
> 
> ```
> ❯ brew info openssl
> openssl@3: stable 3.0.1 (bottled) [keg-only]
> ```
> 
> `openssl` used to refer to `openssl@1.1`, but the convention in Homebrew (with two exceptions that we aim to rectify) is that the unversioned name refers to the latest version.

How can I find the path to the installed 1.1 version?

**Comment by carlocab** [comment]
Try `brew --prefix openssl@1.1`.

**Comment by franzinc** [comment]
Thanks, @carlocab
