### ISSUE TITLE
Provide info on how to use HOMEBREW_NO_ENV_HINTS 

### ISSUE THREAD

**Issue by ovitrif** [Homebrew/brew#12892]
### Provide a detailed description of the proposed feature

By default, after a fresh brew installation, for every `brew install SOMETHING` command that is run the output ends with:

```
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

I propose we update either the `man` pages or this line with suggestion on how to use the `HOMEBREW_NO_ENV_HINTS` variable to hide the hints.

### What is the motivation for the feature?

It took me a lot of time to figure out how to `HOMEBREW_NO_ENV_HINTS` , and I can imagine it could be the case for many other users.

### How will the feature be relevant to at least 90% of Homebrew users?

Everyone will be able to just use `HOMEBREW_NO_ENV_HINTS` and get rid of the message appearing after each `brew install SOMETHING` command.

### What alternatives to the feature have been considered?

Writing a blog post about it so it can be found when googling.

**Comment by carlocab** [comment]
Is the information in [`man brew`](https://docs.brew.sh/Manpage#environment) not sufficient?

**Comment by MikeMcQuaid** [comment]
> Is the information in [`man brew`](https://docs.brew.sh/Manpage#environment) not sufficient?

Until we have more people asking: I think it is.

**Comment by ovitrif** [comment]
> Is the information in [`man brew`](https://docs.brew.sh/Manpage#environment) not sufficient?

Thank you for asking this @carlocab ! 🙇‍♂️

@MikeMcQuaid has a point 👌, in my case the informtion from `man brew` felt like just repeating the same amount of information from the output 🤷‍♂️
