### ISSUE TITLE
i cant run any more commands after error occur

### ISSUE THREAD

**Issue by credits-16** [Homebrew/brew#12899]
### `brew config` output

```shell
Updating files: 100% (2741/2741), done.
HEAD is now at 374adf7f1 Merge pull request #12868 from SMillerDev/chore/doc/add_service_block
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### `brew doctor` output

```shell
nothing
```

### Verification

- [ ] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

i tried to install homebrew for mtr and my terminal said it had an error so I typed $ brew doctor and % brew doctor and there was nothing I tried other command like $ brew config and it does nothing

### What happened (include all command output)?

Updating files: 100% (2741/2741), done.
HEAD is now at 374adf7f1 Merge pull request #12868 from SMillerDev/chore/doc/add_service_block
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

### What did you expect to happen?

installing homebrew

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
i inputted /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

**Comment by carlocab** [comment]
This isn't a bug in `brew` itself, and is an issue with the installer. Please see related discussions at the [discussions page](https://github.com/Homebrew/discussions/discussions).
