### ISSUE TITLE
Add download strategy to use curl with .netrc file

### ISSUE THREAD

**Issue by nlohmann** [Homebrew/brew#12909]
### Provide a detailed description of the proposed feature

Add a download strategy that calls `curl` with `-n`/`--netrc` parameter to respect a local `.netrc` file.

This could be implemented like this:

```ruby
require "download_strategy"

class CurlNetrcDownloadStrategy < CurlDownloadStrategy
  private

  def _curl_args
    args = ["-n"]
    args
  end
end
```

and then add `:using => CurlNetrcDownloadStrategy` to `url`s.

### What is the motivation for the feature?

If you use private taps, you probably also use some kind of authentication for the files to download. As interactive authentication is not suitable, using some kind of credentials file would be helpful. As `curl` is already used to download files by Homebrew, using its `.netrc` mechanism would be a natural extension.

### How will the feature be relevant to at least 90% of Homebrew users?

It would probably be relevant to at least 90% of Homebrew users that want to use private taps. The [Cask Cookbook](https://docs.brew.sh/Cask-Cookbook) states for Ruby methods

> This should be used sparingly: any method which is needed by two or more Casks should instead be rolled into the core. Care must also be taken that such methods be very efficient.

I think adding the code snippet from above to `Library/Homebrew/test/download_strategies` could benefit.

### What alternatives to the feature have been considered?

I am currently adding the snippet

```ruby
require "download_strategy"

class CurlNetrcDownloadStrategy < CurlDownloadStrategy
  private

  def _curl_args
    args = ["-n"]
    args
  end
end
```

to every cask/formula file in my private tap. This works, but is a lot of copy/paste all over the place.

**Comment by carlocab** [comment]
I don't have an opinion on whether this is suitable for inclusion in `brew` or not, but you can limit the duplication in your tap by defining `CurlNetrcDownloadStrategy` in a separate file and doing `require_relative`. See [this tap](https://github.com/gromgit/homebrew-fuse) for an example.

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this. We're not wanting to add additional download strategies like this that aren't needed in the typical usage of Homebrew.

**Comment by nlohmann** [comment]
I totally can understand your decision. Thanks for the quick feedback.

@carlocab Thanks for the hint to `require_relative`. I tried it, and it works for installations, but I get an error message when I try to uninstall the formula. Is there any subtle difference between extending `CurlDownloadStrategy` and a `Requirement`? Do you have other examples?

**Comment by carlocab** [comment]
It's hard to say without knowing the error message, but I don't think so. Doing `require` is generally quite flexible: see https://github.com/shivammathur/homebrew-extensions (`require_relative` should only differ from `require` in terms of how it resolves paths you give, so that this tap does `require` instead shouldn't be an important distinction)

**Comment by nlohmann** [comment]
> It's hard to say without knowing the error message

Sorry for being so vague. I have the following tap:

```
.
├── Casks
│   └── my-cask.rb
└── require
    └── download_strategy_curl_netrc.rb
```

where `my-cask.rb` is like

```ruby
require_relative "../require/download_strategy_curl_netrc"

cask 'my-cask' do
  version "..."
  sha256 "..."

  url "...", :using => CurlNetrcDownloadStrategy

  app "...app"
end
```

and `download_strategy_curl_netrc.rb` is

```ruby
require "download_strategy"

class CurlNetrcDownloadStrategy < CurlDownloadStrategy
  private

  def _curl_args
    args = ["-n"]
    args
  end
end
```

Installing is as expected:

```shell
$ brew install --cask my-cask.rb
==> Downloading https://...
######################################################################## 100.0%
==> Installing Cask my-cask
==> Moving App '...app' to '/Applications/...app'
🍺  my-cask was successfully installed!
```

However, uninstalling yields an error:

```shell
$ brew uninstall --cask my-cask.rb
Error: Cask 'my-cask' is unreadable: cannot load such file -- /opt/homebrew/Caskroom/my-cask/.metadata/2022-01-13/20220222195947.759/require/download_strategy_curl_netrc
```
