### ISSUE TITLE
Optional Build Environment PATHs

### ISSUE THREAD

**Issue by iAnomaly** [Homebrew/brew#12921]
### Provide a detailed description of the proposed feature

1. Introduce a new environment variable `HOMEBREW_BUILD_ADDITIONAL_PATH` whose `default` is empty/`nil`.
2. Insert env var value either above/before or below/after [path.append("/usr/bin", "/bin", "/usr/sbin", "/sbin")](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/ENV/super.rb#L138):
```ruby
...

  def determine_path
    path = PATH.new(Superenv.bin)

    # Formula dependencies can override standard tools.
    path.append(deps.map(&:opt_bin))
    path.append(homebrew_extra_paths)
    path.append(HOMEBREW_BUILD_ADDITIONAL_PATH)
    path.append("/usr/bin", "/bin", "/usr/sbin", "/sbin")
...
```

### What is the motivation for the feature?

I trying to use Homebrew Linux on my Synology NAS which is a stripped down embedded Linux environment. I does meet/exceed the requirements...
```
GCC 4.7.0 or newer
Linux 2.6.32 or newer
Glibc 2.13 or newer
64-bit x86_64 CPU
```
...but GCC is installed as a non-system package under `/opt/bin`

After spending some time trying to debug why `make` was not respecting my shell PATH, I found [/Library/Homebrew/extend/ENV/super.rb#L138](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/ENV/super.rb#L138) which is explicitly setting path to:
1. Formula provided `:opt_bin`
2. `homebrew_extra_paths`
3. `"/usr/bin", "/bin", "/usr/sbin", "/sbin"`

I would like to propose (and will create the PR) a new optional environment variable that adds additional PATHs to this section of code.

### How will the feature be relevant to at least 90% of Homebrew users?

Likely this will be relevant closer to 10% of users rather than 90%. This would allow Homebrew to build formula on any Linux (or macOS but not really applicable since there is only one: Apple's) distribution/configuration that does not have the C++ toolchain installed under the Homebrew expected `"/usr/bin", "/bin", "/usr/sbin", "/sbin"`.

### What alternatives to the feature have been considered?

Docker. I have tried to use the official [gcc image](https://hub.docker.com/_/gcc) but go figure: that has the toolchain binaries located under `/usr/local/bin` so it suffers the same problem described above (Homebrew only supports `"/usr/bin", "/bin", "/usr/sbin", "/sbin"` currently).

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I don't remember off the top of my head if '`HOMEBREW_CXX`' is an internal environment variable or one that users are supposed to be able to set, but have you tried setting it (and maybe '`HOMEBREW_CC`,' too, if needed) to your compiler's path?  (Anyone, naturally feel free to correct if I'm wrong here.)

**Comment by carlocab** [comment]
`HOMEBREW_C{C,XX}` are internal environment variables that we don't encourage users setting. That said, setting these might work.

**Comment by RandomDSdevel** [comment]
> `HOMEBREW_C{C,XX}` are internal environment variables that we don't encourage users setting.  …

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Right, I just couldn't entirely remember for certain; thanks for jogging my memory.  Carry on…  (_Bows out._)

**Comment by MikeMcQuaid** [comment]
Passing on this specific request but I encourage conversation to continue in the comments or discussions on how best to address your particular workflow.

**Comment by iAnomaly** [comment]
> Passing on this specific request but I encourage conversation to continue in the comments or discussions on how best to address your particular workflow.

Why are you passing on this? Do you normally close issues without any explanation? How can we have an effective discussion with new individuals if this is closed? Other users are going to have to look/search through closed issues to even find if this is relevant to them.

> I don't remember off the top of my head if '`HOMEBREW_CXX`' is an internal environment variable or one that users are supposed to be able to set, but have you tried setting it (and maybe '`HOMEBREW_CC`,' too, if needed) to your compiler's path? (Anyone, naturally feel free to correct if I'm wrong here.)



> `HOMEBREW_C{C,XX}` are internal environment variables that we don't encourage users setting. That said, setting these might work.

I don’t want to use methods that aren’t encouraged/supported but I tried `HOMEBREW_CC=/opt/bin/gcc` but it fails with error because `GNU_GCC_REGEXP` only supports a naked binary and not a path: https://github.com/Homebrew/brew/blob/fa4f239cd6e7b96de54825d779ca2a8ac3ff7ec2/Library/Homebrew/extend/ENV/shared.rb#L348

I tried setting `GNU_GCC_REGEXP=.*` but I don’t think this is actually an exposed environment variable.


Even if this worked I don’t think it would be sufficient for the problem. It’s not just cc and cpp, it’s potentially any other binary in the GC tool chain that a formula’s build makefile could call like ar, etc. I need a way to add an additional path to the tool chain.
