### ISSUE TITLE
Make stats from analytics available as a yearly report

### ISSUE THREAD

**Issue by mbonaci** [Homebrew/brew#1292]
It would be very interesting to see GA-type reports.
E.g.
- top 100 installed programs in the past year
- install/update count by month/country (would show spikes for new and updated programs)
- brew user count by country (some countries are almost 100% Windows, e.g. Croatia)

I think people are generally fine with providing anonymized data, but it would be nice to get something useful "in return".

**Comment by MikeMcQuaid** [comment]
We'll definitely not offer by country to preserve anonymity. How do you suggest we publish this data?

**Comment by tdsmith** [comment]
> We'll definitely not offer by country to preserve anonymity

I think it would be reasonable to report breakout stats for countries with more than _n_ users. Which might not include Croatia. :)

**Comment by tdsmith** [comment]
You can incidentally see top 100 packages and some noodling around visualizing the options with which packages are installed here: http://rpubs.com/tdsmith/198233

**Comment by mbonaci** [comment]
@MikeMcQuaid said:
> How do you suggest we publish this data?
Perhaps in a yearly blog post? Or even better, up to date stats on the web site (e.g. `brew.sh/stats`).
The "country thing" was just my hasty attempt to list some interesting reports. I'm sure you can think of some better examples. What do you find interesting when looking at GA UI?

**Comment by MikeMcQuaid** [comment]
> Perhaps in a yearly blog post? Or even better, up to date stats on the web site (e.g. brew.sh/stats).

This sounds good for now as it's suitably low-effort. I'd love to have a somewhat realtime dashboard but we're lacking resources to work on that right now.

**Comment by MikeMcQuaid** [comment]
My current thoughts on the best approach: Ruby that's run from a `Rakefile` and generates HTML output that can be displayed on our Jekyll site at http://brew.sh somewhere.

**Comment by ianrtracey** [comment]
Is this still up for grabs? Sounds interesting and I have some available bandwidth.

**Comment by MikeMcQuaid** [comment]
@ianrtracey Yes, that would be great. Basically looking for a way to dump analytics data using a `rake` job in https://github.com/homebrew/homebrew.github.io which can be displayed publicly for everyone.

**Comment by ianrtracey** [comment]
@MikeMcQuaid Sounds great. Where would be the best place to find the analytics data?

**Comment by ianrtracey** [comment]
@MikeMcQuaid: Also, are we interested in running this rake task nightly in order to create up-to-date reporting similar to npm? Or are we strictly looking at yearly reports?

**Comment by MikeMcQuaid** [comment]
@iainbeeston Yeh, you'd need to get access. Ideally make something generic that does the Google Analytics handshaking for e.g. something you control and gets that data and then we can work together on getting you authentication and adapting that for our analytics.

I think at first we'll not run it automatically nightly but manually e.g. monthly until it's automated.

**Comment by ianrtracey** [comment]
@MikeMcQuaid sounds good.

**Comment by MikeMcQuaid** [comment]
Available now:
https://brew.sh/analytics/

As of:
https://github.com/Homebrew/homebrew-formula-analytics
https://github.com/Homebrew/homebrew.github.io/pull/159
