### ISSUE TITLE
Autosquash can't squash commits that modify non-formula files

### ISSUE THREAD

**Issue by dpo** [Homebrew/brew#12939]
### `brew config` output

```shell
N/A: issue occurs on GitHub Actions VM
```

### `brew doctor` output

```shell
N/A: issue occurs on GitHub Actions VM
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Merge a PR in a tap by labeling it with "pr-pull". The PR in question only modifies the version of a formula: https://github.com/coin-or-tools/homebrew-coinor/pull/81/files

### What happened (include all command output)?

The job fails with the error message
```
Error: Autosquash can't squash commits that modify non-formula files.
```
https://github.com/coin-or-tools/homebrew-coinor/runs/5365992002?check_suite_focus=true#step:4:20

### What did you expect to happen?

Expected the bottles to be published and the PR to be merged.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
The issue occurs in GitHub Actions on a tap, not by manually running brew commands.

The issue was reported here: https://github.com/Homebrew/discussions/discussions/3033
and I was advised to open an issue on this repository.
```

**Comment by Bo98** [comment]
Specifically, the bug is that this line fails to take into account that formula files can lie outside of a `Formula` subdirectory: https://github.com/Homebrew/brew/blob/b4244bb1608ccf71ecc7cd3b61e014e88009af44/Library/Homebrew/dev-cmd/pr-pull.rb#L227

**Comment by carlocab** [comment]
> Given these commands exist primarily for our workflow: I'm tempted to say "we'll review a PR to fix this but don't plan on doing so ourselves"

The workaround also seems to be pretty straightforward: just move your formulae into a `Formula` or `HomebrewFormula` subdirectory.
