### ISSUE TITLE
HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED=0 in .zprofile does nothing

### ISSUE THREAD

**Issue by tympom** [Homebrew/brew#12932]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.16-64-g103cd0c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 103cd0c94c37df2041c07727215f8f5127bf5d17
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b830a22c856222d846c700477036d8e656ca911e
Core tap last commit: 68 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

unset HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED to see all updates

### What happened (include all command output)?

brew update                                                                                                                   
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/cask-drivers).
Warning: HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED can be unset, it is now the default!

### What did you expect to happen?

list all updates, not only installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
set export HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED=0 in .zprofile

brew update
```

**Comment by MikeMcQuaid** [comment]
This is intentional behaviour. See in https://github.com/Homebrew/brew/pull/12910 and discussion in https://github.com/Homebrew/discussions/discussions/3008.

FYI: setting variables to `0` actually enables them. You need to either `unset` them to disable them or `export HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED=1` to enable them.

**Comment by tympom** [comment]
How do I unset it? Is it documented somwhere?
unset HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED also does nothing 🤔

**Comment by MikeMcQuaid** [comment]
@tympom Remove `export HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED=0` from your `.zprofile`.

**Comment by tympom** [comment]
It was not there, I have added it after this surprise change to brew update.
Whatever I do, I cannot return to previous brew update behaviour...

**Comment by MikeMcQuaid** [comment]
@tympom Yes, this is expected. You cannot return to the previous behaviour. The code has been removed. You can discuss this in https://github.com/Homebrew/discussions/discussions/3008.

**Comment by tympom** [comment]
🙁
OK, thabk you, I will.
Why display "Warning: HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED can be unset, it is now the default!" than? Why this variable exist? Does it do anything? Is it documented?

**Comment by tympom** [comment]
I see, thank you.
