### ISSUE TITLE
Skip postinstall step

### ISSUE THREAD

**Issue by jtanx** [Homebrew/brew#1294]
Is it possible to skip the postinstall step when a package is installed? Like the one when `fontconfig` is installed. It runs every time in a CI build, yet this step is unnecessary (in the context of a CI build) and just adds to the build time.

**Comment by MikeMcQuaid** [comment]
We won't provide an option for this but `brew install --build-bottle` will happen to do this as a side-effect of how bottling works.

**Comment by jtanx** [comment]
Aww... `brew install --build-bottle` kind of defeats the purpose because it forces it to build from source, which is even slower than just running the postinstall. I guess I can always patch the formula before running the install...

**Comment by MikeMcQuaid** [comment]
Yes, that's a better approach, probably.

**Comment by jtanx** [comment]
Yep. For future reference, this seems to work;

~~~~
sed -i '/fc-cache/d' "$(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fontconfig.rb"
~~~~

Saves almost 3 minutes off a build.
