### ISSUE TITLE
install qemu --env=std --cc=gcc-4.2 failed on mac os x 10.11.6-x86_64

### ISSUE THREAD

**Issue by sakopzon** [Homebrew/brew#1295]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[brew_config_log.txt](https://github.com/Homebrew/brew/files/531118/brew_config_log.txt)
[brew_doctor_log.txt](https://github.com/Homebrew/brew/files/531120/brew_doctor_log.txt)
[brew_install_qemu_log.txt](https://github.com/Homebrew/brew/files/531119/brew_install_qemu_log.txt)

**Comment by MikeMcQuaid** [comment]
We don't support issues when using `--env=std` or custom `--cc`, sorry.
