### ISSUE TITLE
Environment variable to auto-update non-standard taps

### ISSUE THREAD

**Issue by maxmelamed** [Homebrew/brew#12950]
### Provide a detailed description of the proposed feature

Brew provides a way to auto-update itself with the `HOMEBREW_AUTO_UPDATE_SECS` environment variable as noted in the [docs](https://docs.brew.sh/Manpage#environment), which say `Run brew update once every HOMEBREW_AUTO_UPDATE_SECS seconds before some commands`. This is not quite accurate, however, since the command that actually gets run is `brew update --preinstall`([source](https://cs.github.com/Homebrew/brew/blob/0afd0d774aa4adbb2faa9249b3c7711a8179cec9/Library/Homebrew/brew.sh#L287)) which behaves differently ([source](https://cs.github.com/Homebrew/brew/blob/0afd0d774aa4adbb2faa9249b3c7711a8179cec9/Library/Homebrew/cmd/update.sh#L6)). I'd like to propose another env var, `HOMEBREW_AUTOUPDATE_TAPS` that will allow the autoupdate to run plain `brew update` without `preinstall`. Failing that, I'd like to propose a docs update to reflect the difference in behavior between `brew update` and `brew update --preinstall` which is what runs with the env var set.

Happy to open a PR for either/both of these things :) 

### What is the motivation for the feature?

The motivation for the feature is that I'd like the ability to update non-standard taps at the same frequency as homebrew/core. It seemed to me from the docs that this was possible using the `HOMEBREW_ATUO_UPDATE_SECS` environment variable, but the actual behavior differs slightly from what's documented.

### How will the feature be relevant to at least 90% of Homebrew users?

I believe this feature is relevant to any user who has any non-standard taps set up, since they may be in the same position as me and want those auto-updated. It's also relevant to all users who read the docs, since they could be slightly confused in the same way that I was.

### What alternatives to the feature have been considered?

If providing a way to autoupdate other taps is infeasible, an update to the docs would be great to prevent future users from needing to look at the source code.

**Comment by Bo98** [comment]
It's not exactly what you're asking but you may be interested in https://github.com/Homebrew/homebrew-autoupdate.

**Comment by maxmelamed** [comment]
> https://github.com/Homebrew/homebrew-autoupdate

Thanks for the link! I've actually seen this, and while it definitely looks useful I would prefer the visibility of the update happening in the foreground based on the command I'm running. Happy to use it if it's the best option, but would love to add the behavior in brew if possible

**Comment by Rylan12** [comment]
I think I'd be in favor of such an option. Maybe we could call it `HOMEBREW_AUTO_UPDATE_FULL` or something like that?

**Comment by MikeMcQuaid** [comment]
@maxmelamed If I'm understanding correctly: is the issue here is that non-standard taps are never or insufficiently often (please clarify!) run as part of the auto-update process? Which taps specifically are you referring to here e.g. are they on GitHub?

**Comment by maxmelamed** [comment]
> @maxmelamed If I'm understanding correctly: is the issue here is that non-standard taps are never or insufficiently often (please clarify!) run as part of the auto-update process? Which taps specifically are you referring to here e.g. are they on GitHub?

The observed behavior is that the tap never updates as part of an auto-update. However, I did some more digging into brew source code here. The tap is hosted on github, however I have it cloned via ssh so [this](https://cs.github.com/Homebrew/brew/blob/0afd0d774aa4adbb2faa9249b3c7711a8179cec9/Library/Homebrew/cmd/update.sh#L589)  condition is not met, since the output of `git config remote.origin.url` is `git@github.com`. Is it intended that a git-hosted tap cloned via ssh behaves this way?

I also now realize that if I want a given tap to be autoupdated, I can just set `homebrew.forceautoupdate` as part of that repo's git config. This certainly solves my immediate problem of getting the tap updated even when the `preinstall` flag is passed. 

I do still think it could be useful to have a global flag along the lines of what @Rylan12 suggested (i.e. a var that, when set, performs a full `brew update` on autoupdates), but I understand if the advice here is just to use `homebrew.forceautoupdate` if I want a tap autoupdated.

Also might be worthwhile to update the docs (specifically the [environment](https://docs.brew.sh/Manpage#environment) section of the manpage) to reflect that `brew update` is not exactly what gets run here, but rather `brew update --preinstall`.

**Comment by MikeMcQuaid** [comment]
> Is it intended that a git-hosted tap cloned via ssh behaves this way?

Yes. We cannot use the GitHub API to verify whether a `git fetch` can be avoided.

> but I understand if the advice here is just to use `homebrew.forceautoupdate` if I want a tap autoupdated.

I think so, yes. I'd want to see more users requesting this and not really having a workaround before adding an option.

> Also might be worthwhile to update the docs (specifically the [environment](https://docs.brew.sh/Manpage#environment) section of the manpage) to reflect that `brew update` is not exactly what gets run here, but rather `brew update --preinstall`.

Yup, works for me. Could you submit a PR? https://github.com/Homebrew/brew/blob/master/Library/Homebrew/env_config.rb is what would need edited for this.

**Comment by maxmelamed** [comment]
> Yup, works for me. Could you submit a PR? 

Sure, can do. Thanks for engaging on this
