### ISSUE TITLE
brew install --only-dependencies should not check arch requirements

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#12965]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.0-59-g67512ae
ORIGIN: https://github.com/Homebrew/brew
HEAD: 67512aed56c0598c427b4be14bade789109514f1
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 01c0f33ce751a621e1560b6dbb6f3de9d1a269ae
Core tap last commit: 8 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.jYvqZuAeC2/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install Julia's dependencies, to test a manual build from head.

### What happened (include all command output)?

```
$ brew install --only-dependencies julia
julia: The x86_64 architecture is required for this software.
Error: julia: An unsatisfied requirement failed this build.
```

### What did you expect to happen?

Since I am only asking for dependencies, it should not matter that Julia itself has an arch requirement: it will not be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install --only-dependencies julia
```

**Comment by fxcoudert** [comment]
Another case with similarly weird output: I've removed the arch requirement in the formula, to bypass the issue, and now:

```
$ brew install --only-dependencies julia
Error: julia: no bottle available!
```

All the dependencies have a bottle, so it's not really relevant to complain about julia since it won't be installed.

**Comment by issyl0** [comment]
I can't reproduce your second weird output here. 😕
