### ISSUE TITLE
Brew stops working all the time on mac m1

### ISSUE THREAD

**Issue by it-pappa** [Homebrew/brew#12972]
### `brew config` output

```shell
-zsh: command not found: brew
```

### `brew doctor` output

```shell
-zsh: command not found: brew
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

(writing this from another computer). 
The issue is very well knows. I install brew, it works fine and later on it just stops working. 

For some reason "tree" is stops working at the same time. After running the export PATH etc fix it works fine, both tree and brew. But stops after an hour or so. I may have reinstalled and ran the quickfix hundred times these last days. 

### What happened (include all command output)?

zsh: command not found: brew
zsh: command not found: tree (i know this is not the correct git, but maby it can help?)

### What did you expect to happen?

brew to work stable on Mac m1. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
terminal: iTerm2 
shell: zsh
quick fix doesnt work for longer then a few mins/hours. 
reinstalled but doesnt help

tree stops working at the same time and will start work same time brew is fixed/reinstalled.
```

**Comment by tcelestino** [comment]
@it-pappa I recommend to add `source ~/.zprofile` in your `.zshconfig`, because all times your open iTerm2, you'll need to refresh file. I did it and sorted out.

**Comment by it-pappa** [comment]
@carlocab yes i did. Sorry if the description was short.

**Comment by it-pappa** [comment]
@tcelestino i have done it, but can try again. Doesnt work today anymore.

**Comment by it-pappa** [comment]
@carlocab i ran it again, and it works now. But after a while it stops working again.

**Comment by carlocab** [comment]
If it stops working then that means your `.zprofile` isn't being sourced by your shell.

The best that I can say is that you need your terminal to do
```
eval $(/opt/homebrew/bin/brew shellenv)
```
on startup.

How to do this exactly depends a lot on your own configuration, so I won't be able to help you further here.

**Comment by it-pappa** [comment]
@carlocab ok thank you :) I dont know how to do it, but i have ran it. But how to do it correctly i cant tell My config is just a clean mac air m1 with iterm2

**Comment by carlocab** [comment]
That's odd. This should work fine on a clean Mac with iTerm2.

Try Googling `zsh startup` and see if that helps you get somewhere. I'm assuming you're using Zsh since that's the default shell on a clean macOS install.

If you're not able to figure it out, try the discussions page at https://github.com/Homebrew/discussions/discussions.

**Comment by it-pappa** [comment]
@carlocab  that is correct. I will have a look thank you. Il comment on my findings

**Comment by gromgit** [comment]
@it-pappa Have you logged out and logged back into your Mac since installing Homebrew? `~/.zprofile` is only sourced on login, and I have no idea how @tcelestino's recommendation of `.zshconfig` would work, as it's not a standard Zsh startup file.

**Comment by it-pappa** [comment]
@gromgit i think so? I can try restart the whole thing maby. I guess i have before offcourse

**Comment by tcelestino** [comment]
@gromgit when I added `source ~/.zprofile` in my `.zshconfig`, `brew` command did work it, same when I restarted my iTerm2. 

I'm using oh-my-zsh and I set my startup scripts in `.zshconfig` and I never had a problem about it.

**Comment by gromgit** [comment]
@tcelestino As I said, `.zshconfig` is [not a standard Zsh startup file](https://www.mankier.com/1/zsh#Startup/Shutdown_Files), so if it's getting sourced, some unknown plugin or config setting is doing the sourcing. It's almost certainly not Oh My Zsh, which [edits `~/.zshrc` during installation](https://github.com/ohmyzsh/ohmyzsh/blob/40f49342f587167292461242dc13fdb93363278a/tools/install.sh#L296-L334) and doesn't mention `.zshconfig` anywhere in its source.

That's why I'm not surprised nothing changed for @it-pappa after doing what you recommended.

If you're willing to experiment, try _commenting out_ `source ~/.zprofile` in your `.zshconfig`, then restart iTerm2. If `brew` still works, that line isn't doing anything useful, and your `.zshconfig` may not be sourced at all.

**Comment by gromgit** [comment]
@it-pappa What's the output of `finger <your_username>`?

If it contains `Shell: /bin/bash`, that means your login shell is still bash, and you should probably add `eval "$(/opt/homebrew/bin/brew shellenv)"` to your `~/.zshrc` instead. See [the Startup/Shutdown Files section](https://www.mankier.com/1/zsh#Startup/Shutdown_Files) of the `zsh` man page for more details.

**Comment by tcelestino** [comment]
> @tcelestino As I said, `.zshconfig` is [not a standard Zsh startup file](https://www.mankier.com/1/zsh#Startup/Shutdown_Files), so if it's getting sourced, some unknown plugin or config setting is doing the sourcing. It's almost certainly not Oh My Zsh, which [edits `~/.zshrc` during installation](https://github.com/ohmyzsh/ohmyzsh/blob/40f49342f587167292461242dc13fdb93363278a/tools/install.sh#L296-L334) and doesn't mention `.zshconfig` anywhere in its source.
> 
> That's why I'm not surprised nothing changed for @it-pappa after doing what you recommended.
> 
> If you're willing to experiment, try _commenting out_ `source ~/.zprofile` in your `.zshconfig`, then restart iTerm2. If `brew` still works, that line isn't doing anything useful, and your `.zshconfig` may not be sourced at all.

Oh man!!! Sorry about that. I said `.zshconfig` but it was `.zshrc` 🤦🏾 I use `zshconfig` as alias to open my file `.zshrc` in VSCode. 😞 

@it-pappa add `source ~/.zprofile` on `.zshrc` it'll works

**Comment by it-pappa** [comment]
@gromgit Hi, it worked for two days but now stopped again. Im using it all the time when working with IAC. 
After fingering my terminal i can see my start shell is: Shell: /bin/zsh.

Can i ask, where do i find the .zshconfig file?

**Comment by it-pappa** [comment]
@gromgit ok, i hat a .zprofile which alot of eval brew etc which i just deleted. 
in my .zshrc file i see export PATH="/opt/homebrew/bin:$PATH"

**Comment by it-pappa** [comment]
@gromgit  now i ran export PATH=/opt/homebrew/bin:$PATH and it works again.. cant see anything changed

**Comment by tcelestino** [comment]
> Can i ask, where do i find the .zshconfig file?

@it-pappa there isn't this file. The `zshconfig` is my alias to open `.zshrc` on VSCode. Sorry about wrong information. 🤦🏾 

You might to add `source ~/.zprofile` in your `.zshrc`, it'll works

**Comment by tcelestino** [comment]
> Can i ask, where do i find the .zshconfig file?

@it-pappa there isn't this file. The `zshconfig` is my alias to open `.zshrc` on VSCode. Sorry about wrong information. 🤦🏾 

You might to add `source ~/.zprofile` in your `.zshrc`, it'll works
