### ISSUE TITLE
Trying install brew on BigSur Mac 

### ISSUE THREAD

**Issue by g1b3r** [Homebrew/brew#12982]
### `brew config` output

```shell
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

### `brew doctor` output

```shell
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I try to install a brew using script from github but its not working 

### What happened (include all command output)?

==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:0cb1cc7af109437fe0e020c9f3b7b95c3c709b140bde9f991ad2c1433496dd42
###################################################################################################################################################################################################################################################### 100.0%
Error: Checksum mismatch.
Expected: 0cb1cc7af109437fe0e020c9f3b7b95c3c709b140bde9f991ad2c1433496dd42
  Actual: f1d81ffe5b7d3c228ff1c99f37183e8ed98dfc1cc2ec70236271736b09e6dc68
 Archive: /Users/<User>/Library/Caches/Homebrew/portable-ruby-2.6.8.yosemite.bottle.tar.gz

### What did you expect to happen?

Install Brew

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I just run

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Provide a password and got error
```

**Comment by MikeMcQuaid** [comment]
You deleted your current directory.

**Comment by g1b3r** [comment]
I i try to reinstall because of 

==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:0cb1cc7af109437fe0e020c9f3b7b95c3c709b140bde9f991ad2c1433496dd42
###################################################################################################################################################################################################################################################### 100.0%
Error: Checksum mismatch.
Expected: 0cb1cc7af109437fe0e020c9f3b7b95c3c709b140bde9f991ad2c1433496dd42
Actual: f1d81ffe5b7d3c228ff1c99f37183e8ed98dfc1cc2ec70236271736b09e6dc68
Archive: /Users//Library/Caches/Homebrew/portable-ruby-2.6.8.yosemite.bottle.tar.gz

Lots users have problem with this can you please provide solution because is annoing 


Before i try a lot stackoverflow answers and nothing helps 

There is no option to install because of this bug

**Comment by gromgit** [comment]
To be clear, @MikeMcQuaid is referring to the errors in your `brew config` and `brew doctor` output:
> ```
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> ```

For your checksum mismatch issue, your download is corrupted or incomplete. Remove the file (`/Users/<your_login>/Library/Caches/Homebrew/portable-ruby-2.6.8.yosemite.bottle.tar.gz`) and try the install again.

> Lots users have problem with this

Nope, there aren't "lots users" with this problem. It's just you.
