### ISSUE TITLE
Analytics for multiple formula should output single table

### ISSUE THREAD

**Issue by michal-piekarski** [Homebrew/brew#12989]
### Provide a detailed description of the proposed feature

`brew info --analytics formula1 formula2` should output single table instead of 2 separate ones

### What is the motivation for the feature?

The whole point of using `brew info --analytics` looks like comparison of "popularity"

### How will the feature be relevant to at least 90% of Homebrew users?

Make better decisions when installing.

### What alternatives to the feature have been considered?

Filtering current output with `grep` or `jq`

**Comment by MikeMcQuaid** [comment]
Would review a pull request for this but passing on this as a feature request for maintainers or soliciting our community for now, sorry!
