### ISSUE TITLE
adding `--zap` to `brew reinstall` in homebrew-cask

### ISSUE THREAD

**Issue by spinofdoom** [Homebrew/brew#12983]
### Provide a detailed description of the proposed feature

Since `brew reinstall` itself has an uninstallation component, I propose utilizing `brew uninstall`'s [fantastic](https://github.com/nrlquaker/homebrew-createzap) `zap` option with `brew reinstall`, such that:

`brew reinstall --zap <cask>` uninstalls `<cask>` according to `<cask>`'s `zap` stanza, then re-installs `<cask>`.

### What is the motivation for the feature?

It seems like a symmetrical & intuitive adoption of the `zap` option from `uninstall` over to `reinstall`. It makes achieving a true "fresh re-installation" of any given Cask an ever-so-slightly simpler and quicker proposition.

### How will the feature be relevant to at least 90% of Homebrew users?

Let's say you realize you got your preferences so wrong in `flux` that you just want to delete all the prefs files, etc. and start over. Or maybe another Cask seems possibly bugged and you want to make sure to uninstall all vestiges of it before re-installing for testing purposes. With many Homebrew users being devs or power users themselves, one can definitely envision many users having at least the occasional desire to `zap` an install of a Cask and install it fresh, be it because of testing/learning, or previous user/dev error.

### What alternatives to the feature have been considered?

`brew uninstall --zap <cask> && brew install <cask>` works, but it's not as elegant or quick to type, and I'd imagine runs slower than if `zap` were integrated directly into the `reinstall` script. I have searched the Discussion pages for this, and have come up short.

**Comment by issyl0** [comment]
Commenting to make stale bot un-stale this issue, I opened a draft PR at #13116.
