### ISSUE TITLE
fatal: invalid branch name: init.defaultBranch =

### ISSUE THREAD

**Issue by jmateos-xt** [Homebrew/brew#12981]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Hi 
trying 
brew tap azure/functions
get error like this
Cloning into '/opt/homebrew/Library/Taps/azure/homebrew-functions'...
fatal: invalid branch name: init.defaultBranch =
Error: Failure while executing; `git clone https://github.com/azure/homebrew-functions /opt/homebrew/Library/Taps/azure/homebrew-functions --origin=origin --template=` exited with 128.
Thanks

### Command that failed

brew tap azure/functions

### Output of command with `--verbose --debug`

```shell
==> Tapping azure/functions
Cloning into '/opt/homebrew/Library/Taps/azure/homebrew-functions'...
fatal: invalid branch name: init.defaultBranch =
Error: Failure while executing; `git clone https://github.com/azure/homebrew-functions /opt/homebrew/Library/Taps/azure/homebrew-functions --origin=origin --template=` exited with 128.
```

### Output of `brew doctor --verbose`

```shell
❯ brew tap azure/functions --verbose --debug
/opt/homebrew/Library/Homebrew/shims/shared/git --version
==> Tapping azure/functions
git clone https://github.com/azure/homebrew-functions /opt/homebrew/Library/Taps/azure/homebrew-functions --origin=origin --template=
Cloning into '/opt/homebrew/Library/Taps/azure/homebrew-functions'...
fatal: invalid branch name: init.defaultBranch =
Error: Failure while executing; `git clone https://github.com/azure/homebrew-functions /opt/homebrew/Library/Taps/azure/homebrew-functions --origin=origin --template=` exited with 128.
/opt/homebrew/Library/Homebrew/utils.rb:304:in `safe_system'
/opt/homebrew/Library/Homebrew/tap.rb:306:in `install'
/opt/homebrew/Library/Homebrew/cmd/tap.rb:65:in `tap'
/opt/homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### Output of `brew tap`

```shell
brew tap azure/functions
==> Tapping azure/functions
Cloning into '/opt/homebrew/Library/Taps/azure/homebrew-functions'...
fatal: invalid branch name: init.defaultBranch =
Error: Failure while executing; `git clone https://github.com/azure/homebrew-functions /opt/homebrew/Library/Taps/azure/homebrew-functions --origin=origin --template=` exited with 128.
```

**Comment by carlocab** [comment]
Can't reproduce.
```
❯ brew tap azure/functions
==> Tapping azure/functions
Cloning into '/usr/local/Homebrew/Library/Taps/azure/homebrew-functions'...
remote: Enumerating objects: 547, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 547 (delta 101), reused 66 (delta 43), pack-reused 402
Receiving objects: 100% (547/547), 75.04 KiB | 1.79 MiB/s, done.
Resolving deltas: 100% (337/337), done.
Tapped 5 formulae (19 files, 107.3KB).
```
This is likely a problem with either your network connection or your Git configuration.
