### ISSUE TITLE
Add `brew dev` as an alias for `brew developer`

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/brew#12995]
### Provide a detailed description of the proposed feature

Add `brew dev` as an alias for `brew developer`.

### What is the motivation for the feature?

It would make it easier to type and I feel like it's pretty intuitive. The `dev` subcommand is currently unused.

### How will the feature be relevant to at least 90% of Homebrew users?

It will probably only be used by those who decide to contribute to the project.

### What alternatives to the feature have been considered?

Keeping it the way it is.

**Comment by Bo98** [comment]
I suppose we could, though are you actually running the command that often?

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Is tab completion or using [Homebrew Aliases](https://github.com/Homebrew/homebrew-aliases) insufficient here?  That's unexpected.

**Comment by apainintheneck** [comment]
Oh, yeah. Homebrew Aliases works perfectly. Thanks
