### ISSUE TITLE
Use Xcode command line tools when possible

### ISSUE THREAD

**Issue by Galaxy0419** [Homebrew/brew#13005]
### Provide a detailed description of the proposed feature

Some bottles like python requires command line tools to be installed on the system first.  However, if the user had already installed Xcode, it also provides a copy of the command line tools.  We can just use the Xcode's command line tools instead of installing two copies of the same toolchains.

### What is the motivation for the feature?

The command line tool package itself takes several Gigs of space.  Not to mention maintaining two different version of the same toolchain can be confusing for the macOS/iOS developers.

### How will the feature be relevant to at least 90% of Homebrew users?

I'm not sure the feature is relevant to 90% of the users.  But since most of the users are programmers.  There's a very high chance that they also installed Xcode, so it will definitely save them some space on their Macs and bandwidth and troubles for updating the command line tool they will never use (Since the xcode-select will use Xcode's toolchains if possible).

### What alternatives to the feature have been considered?

N/A

**Comment by carlocab** [comment]
We do use the tools bundled with the Xcode app whenever possible. You should be able to use a significant majority of formulae packaged by Homebrew even if you don't have the CLT installed.

However, there are a small number of instances where an Xcode installation cannot be used as a substitute for a CLT installation. We require the CLT for these cases. One way to avoid the CLT requirement for these formulae would be to rebuild the bottles to use the Xcode SDK instead. However, this would be undesirable for a number of reasons:

1. We would have to require an Xcode installation in a specific path instead. This would be worse for more users: installing Xcode requires 10+ GB whereas the CLT requires less than 2 GB of storage.
2. The newest available version of Xcode often does not ship the right SDK for the current OS. This usually occurs on older (but still supported) versions of macOS.

If you don't want to have to install the CLT, you can build the relevant formulae from source. Note, however, that source builds are fragile and can fail for any numbers of reasons, so we don't provide support for this.
