### ISSUE TITLE
Hide packages by License

### ISSUE THREAD

**Issue by Pantyhose-X** [Homebrew/brew#13002]
### Provide a detailed description of the proposed feature

Filter arch Linux [packages](https://archlinux.org/packages/)  Hide packages by License

Arch linux and manjaro official software repositories  have begun to promote closed source software and Dependencies. Such as Opera Browser. This is a very dangerous behaviour that does not open source.

### What is the motivation for the feature?

software repositories  have begun to promote closed source software and Dependencies. Such as Opera Browser. This is a very dangerous behaviour that does not open source.

### How will the feature be relevant to at least 90% of Homebrew users?

yes

### What alternatives to the feature have been considered?

no

**Comment by Bo98** [comment]
We do not permit closed source software to exist in homebrew-core.

But if there's even open source licenses you'd like to block, you can do that too: https://docs.brew.sh/License-Guidelines#specifying-forbidden-licenses
