### ISSUE TITLE
Warn when local brew is on non-main branch

### ISSUE THREAD

**Issue by janeklb** [Homebrew/brew#13003]
### Provide a detailed description of the proposed feature

Output a warning if the users brew directory is not on the main (`master`) branch when `brew upgrade` is run.

Consider updating `brew doctor` to do the same.

### What is the motivation for the feature?

A few weeks ago I was tinkering with adding a new formula. While doing so, I created a new branch in my local `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` repo... but forgot to switch back to `master` after pausing the work (and not returning back to it since...). 

Eventually I noticed that running `brew upgrade` was not actually doing any upgrades (despite the fact that `brew update` _seems_ to be working fine.. at least according to stdout).

Finally, after remembering I had switched to another branch in the `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` directory, I switched back to `master` and `brew upgrade` proceeded to work correctly.

### How will the feature be relevant to at least 90% of Homebrew users?

It's unlikely that this feature will be relevant to >90% Homebrew users.

### What alternatives to the feature have been considered?

I have not been able to come up with any reasonable alternatives.

**Comment by carlocab** [comment]
> Consider updating `brew doctor` to do the same.

`brew doctor` already does this.

**Comment by janeklb** [comment]
I don't know what I did before when testing this.. but I clearly did it wrong. Thanks. Closing
