### ISSUE TITLE
C-compiler shim fails on Mac OS unless called via symlink

### ISSUE THREAD

**Issue by constinit** [Homebrew/brew#13013]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.2-19-g600d84e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 600d84e56eda931c3dd3b6a9ee61233d9bf2b054
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: badf65fb722f674b5f7f27b5f6b3b2a4ef8e3747
Core tap last commit: 20 hours ago
Core tap branch: ibazel
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3-arm64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to call `cc` (the C-compiler shim) on Mac OS. Specifically, I am trying to write a formula that builds C++ dependencies using the Bazel build system.

### What happened (include all command output)?

```
cc:479:in `exec': No such file or directory - ./xcrun (Errno::ENOENT)
	from cc:479:in `<main>'
```

### What did you expect to happen?

`shims/super/cc` should correctly locate `xcrun` instead of failing. It currently assumes it is being called via the [symlink](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/shims/mac/super/cc) in `shims/mac/super`; however, this is not always the case, even in the `brew sh` environment.

The relevant line in `cc` is here:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/shims/super/cc#L473

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew sh cc`
```

**Comment by Bo98** [comment]
> It currently assumes it is being called via the [symlink](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/shims/mac/super/cc) in `shims/mac/super`; however, this is not always the case, even in the `brew sh` environment.

`brew sh` should always have `shims/mac/super` in the PATH and not `shims/super`.

I can't reproduce the issue - `brew sh -c "cc --version"` doesn't error for me.

**Comment by constinit** [comment]
Thanks for the fast comment; let me dig further
