### ISSUE TITLE
Development Environments Targeting Different Platforms from Host

### ISSUE THREAD

**Issue by BryanHaley** [Homebrew/brew#13011]
### Provide a detailed description of the proposed feature

Allow creating "development environments" that target versions of macOS different from the host platform. E.g. allowing the installation of libraries built for macOS 11.0 on a macOS 12.0 host. 

In practice, this might be implemented as a sub-directory of the brew directory that has its own ```/opt``` ```/include``` ```/lib``` etc.

For example, a development environment targeting macOS 11.0 might live in the following directory:
```
/opt/homebrew/macos_11-0
/opt/homebrew/macos_11-0/opt
/opt/homebrew/macos_11-0/include
/opt/homebrew/macos_11-0/lib
```

Brew commands could target development environments with a flag. For example:
```
brew --prefix --dev-env=11.0
=> /opt/homebrew/macos_11-0

brew --dev-env=11.0 install libogg
=> Installs libogg built for macOS 11.0 under /opt/homebrew/macos_11-0
```

This could be taken a step further by allowing the specification of architectures as well. For example:
```
brew --prefix --dev-env=11.0_x86_64
=> /opt/homebrew/macos_11-0_x86_64

brew --dev-env=11.0_x86_64 install libogg
=> Installs x86_64 libogg built for macOS 11.0 under /opt/homebrew/macos_11-0_x86_64
```

Another step forward could be to allow specifying Linux or Mac
```
brew --prefix --dev-env=macos_11.0_x86_64
=> /opt/homebrew/macos_11-0_x86_64

brew --prefix --dev-env=linux_arm64
=> /opt/homebrew/linux_arm64

brew --dev-env=linux_arm64 install libogg
=> Installs arm64 libogg built for Linux under /opt/homebrew/linux_arm64
```

In sticking with the homebrewing theme, ```--dev-env``` could perhaps be ```--winery``` or ```--farm``` although that might obfuscate its purpose a bit too much.

### What is the motivation for the feature?

There are two primary motivations for this feature:

1. Make the building of redistributable app bundles/binaries targeting earlier versions of macOS than the host possible using homebrew-provided libraries (e.g. targeting macOS 11.0 on a macOS 12.0 host, or targeting 12.0 on a 12.1 host).
2. Simplify the process of cross-compilation (targeting macOS on Linux or vice versa) by providing an easy way to get libraries built for the target OS.

When combined with something like [dylibbundler](https://github.com/auriamg/macdylibbundler), building libraries for redistributable app bundles targeting earlier versions of macOS would become a very simple process:
```
C_FLAGS += -I$(shell brew --dev-env=11.0 --prefix)/include
L_FLAGS += -L$(shell brew --dev-env=11.0 --prefix)/lib
```
```
brew --dev-env=11.0 install [libraries]
dylibbunder -x app [...]
```

Allowing the specification of architectures would make building universal binaries or separate ARM64 and Intel binaries, which is quite important in the current macOS ecosystem, much simpler. Currently, the accepted solution for this is building the libraries manually from source. This is perfectly valid and possible, but would benefit from this brew feature eliminating the need for setting that up in build systems.

Allowing the specification of operating system (e.g. Mac or Linux) would *greatly* simplify the process of cross compilation. It's always a pain to cross-compile libraries. Having brew either cross compile for you, or retrieve prebuilt binaries for the target OS, would make a lot of developer's lives much, much easier. Currently there are not many good solutions for building macOS apps on Linux hosts for example.

### How will the feature be relevant to at least 90% of Homebrew users?

App bundles are an important part of distributing applications, particularly graphical applications, on macOS. In addition, linking against libraries built for the targeted version of macOS can be important even for pre-built CLI binaries.

Some homebrew users will see direct benefits by being able to simplify their build systems when building redistributable app bundles and binaries. Nearly every homebrew user that uses homebrew-provided libraries in their build system will benefit from being able to target specific versions of macOS, which ensures anyone they share their code with will build against the same macOS SDK level that the original author expected.

Nearly all homebrew users will see indirect benefits from making building and maintenance of pre-built binaries and app bundles easier using homebrew. I.e., making it easier to port and maintain binaries could encourage them to be ported and maintained.

If the aforementioned cross-compilation features are included, I believe ```brew``` would become the de facto way to cross compile libraries from Linux hosts for macOS targets. Many automated distribution build systems run on Linux hosts, so this could have wide-reaching benefits even beyond homebrew users themselves.

An ancillary benefit of this feature would also be allowing users to install libraries/packages they intend to use for development, but don't want linked into their default path environment, into a contained sub-directory of homebrew. For example, I may want to use homebrew-provided SDL2 for a particular project, but by default I want to use SDL2.framework for other projects. I could install brew's SDL2 to ```--dev-env=12.0``` to make any confusion easier to avoid. Perhaps arbitrary dev environments could be allowed too, such as ```--dev-env=MyCoolEnv```.

### What alternatives to the feature have been considered?

Currently, the only options for using homebrew to build redistributable app bundles are as follows:
- Build from a host OS that is the same as the target OS.
- Remote build from a VM or different machine with a host OS that is the same as the target OS.

Neither option is ideal. For starters, most people will *at least* want to build for the major version of macOS (e.g. 12.0), but will keep their device updated to the latest minor version (e.g. 12.1), let alone building for an earlier major version.

Running the target OS in a VM is sometimes an option, but it is first very inconvenient for obvious reasons, and second not always possible. For example, I want to target arm64 11.0 with one of my apps, but running 11.0 (even in a VM) is not supported on my M1 Max device. There is no possible way for me to target 11.0 and build on my M1 Max device (in VM or otherwise) using homebrew-provided libraries. Building from a separate device has its own obvious disadvantage, chief among them being the cost of purchasing such a device if you don't have it already.

Things get more complex when cross compilation across architectures is involved. There is no practical way to virtualize Intel macOS on an Apple Silicon Mac, nor vice versa. 

Ultimately, requiring the target OS to be the same as the host OS makes brew virtually unusable for building redistributable app bundles. The accepted alternative is building libraries from source, which is of course perfectly possible, but makes build systems more complex. Adding this feature to brew would greatly simplify things.

**Comment by BryanHaley** [comment]
I understand this would be a large undertaking; depending on how this is implemented it could take months/years to "fully" support this.

**Comment by Bo98** [comment]
In terms of bottles, this is faily simple on a high level. `Utils::Bottles.tag` pretty much just needs to match the target OS and it'll probably mostly work (unless you are installing Linux on macOS or vice versa - that would require more work.)

For compiling from source, it gets a lot harder. Ideally you would use an SDK matching the target OS - and that may not necessarily be installed. A very good example is stuff that links with system curl - `LIBCURL_VERSION_NUM` will match the headers in the SDK which could be newer than the target OS (which means wrong compilation paths).

Also a notable point: some formulae are _not_ relocatable, but we're improving that with binary relocation we're working on. I'm not entirely sure how that would interface with tools like `dylibbundler` however.

I do see the usefulness of this, but you're probably mostly likely to see progress if someone starts work experimenting this in a tap.

**Comment by BryanHaley** [comment]
If we disregard the cross compilation features and focus just on targeting different versions of macOS, is it not good enough to simply specify ```-mmacosx-version-min``` to the compiler and linker when building from source? In practice this seems to work well enough for building libraries for distributable app bundles without warnings/errors. I see your point for, say, building for Linux on Mac or vice versa though.

```dylibbundler``` walks recursively through dependencies, copies them into the app bundle, and patches all the libraries and the executable to update the paths. In theory it works for everything; I've yet to find something it doesn't work on. I suppose lazy loading with dlopen probably wouldn't work, but I get the feeling that's not very common in libraries.

Only supporting bottles is a good starting point, though. Even just that much would be rather useful. I'll try to find time to experiment with it.

**Comment by Bo98** [comment]
> is it not good enough to simply specify `-mmacosx-version-min` to the compiler and linker when building from source? In practice this seems to work well enough for building libraries for distributable app bundles without warnings/errors.

For most macOS APIs with availability macros - yes. But there's some system headers which are not like that.

A real world example was git when using the system's libcurl. In particular, this code would crash on 10.14 when compiled with the 10.15 SDK: https://github.com/git/git/blob/69a9c10c95e28df457e33b3c7400b16caf2e2962/http.c#L1008-L1033 (via this define https://github.com/git/git/blob/2a97289ad8b103625d3a1a12f66c27f50df822ce/git-curl-compat.h#L121-L127), because `LIBCURL_VERSION_NUM` is a fixed constant and `-mmacosx-version-min` does not change that.

https://github.com/alexey-lysiuk/macos-sdk/blob/af958f6dda704f66022e1799f5dafffea1c2f3b3/MacOSX12.3.sdk/usr/include/curl/curlver.h#L60

> In theory it works for everything; I've yet to find something it doesn't work on.

The specific example I am talking about is if a library contains a fixed installation path reference baked in at compile time. But that's more of an executable thing - most well-written libraries shouldn't do this (but we do not guarantee this).

> Only supporting bottles is a good starting point, though.

Agreed.

**Comment by carlocab** [comment]
> Ultimately, requiring the target OS to be the same as the host OS makes brew virtually unusable for building redistributable app bundles.

Note that building redistributable app bundles isn't a supported use-case of `brew`. (I am aware that some/many use `brew` for this purpose nonetheless.)

While I'm not necessarily opposed to this feature, I don't think the support status of the aforementioned use-case should change even with this feature's implementation. I'm  also a bit wary of adding features designed for a non-supported use-case.

**Comment by Bo98** [comment]
> While I'm not necessarily opposed to this feature, I don't think the support status of the aforementioned use-case should change even with this feature's implementation. I'm also a bit wary of adding features designed for a non-supported use-case.

Yeah, this is exactly why I think if anything like this happens it would be in a tap.

**Comment by Bo98** [comment]
I think I'll close this as it's unlikely a maintainer will work on this in the near future and we don't keep wishlist issues open indefinitely (but if I'm wrong they can tell me and I'll reopen).

I think the best way to go forward is to start up a project to do this. If there's anything specific that can be done in `brew` to enable this and make it easier (in a generic way), specific PRs to do that may be accepted.

**Comment by MikeMcQuaid** [comment]
> Note that building redistributable app bundles isn't a supported use-case of `brew`. (I am aware that some/many use `brew` for this purpose nonetheless.)
> While I'm not necessarily opposed to this feature, I don't think the support status of the aforementioned use-case should change even with this feature's implementation. I'm also a bit wary of adding features designed for a non-supported use-case.

Agreed.

---

What seems like the best fit is something around what @Bo98 mentioned:

> In terms of bottles, this is faily simple on a high level. Utils::Bottles.tag pretty much just needs to match the target OS and it'll probably mostly work (unless you are installing Linux on macOS or vice versa - that would require more work.)

Something to allow folks like yourself to use e.g. older bottles than your macOS version is with an environment variable e.g. `HOMEBREW_MACOS_BOTTLES_TAG=catalina` or something. This should fail if the bottle isn't available for the the given macOS version (or older).

Would accept a pull request for this or a more tightly scoped "help wanted" issue for it.
