### ISSUE TITLE
`brew desc --cask <cask>` does not exist

### ISSUE THREAD

**Issue by voraciousdev** [Homebrew/brew#13021]
### Provide a detailed description of the proposed feature

The command `brew desc <formula>` outputs the description for a formula. A lot of casks also have a `desc` field, but `brew desc --cask <cask>` does not exist, and `brew desc <cask>` fails due to it being a cask instead of a regular formula.

### What is the motivation for the feature?

I like to view the description of a cask before I install it to make sure it's the correct one. I also copy the description into my `Brewfile`.

### How will the feature be relevant to at least 90% of Homebrew users?

I imagine most people would like to view a cask's description just as we can with normal brew formulae.

### What alternatives to the feature have been considered?

I currently have to open the cask on GitHub to view the description.

**Comment by EricFromCanada** [comment]
Implemented with #13033.
