### ISSUE TITLE
`brew doctor` errors without giving advice about how to resolve `No Cask with this name exists.`

### ISSUE THREAD

**Issue by jsoref** [Homebrew/brew#13027]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 600d84e56eda931c3dd3b6a9ee61233d9bf2b054
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 938bc3e868b93605f67fb43f836151af4332f6cd
Core tap last commit: 25 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.35.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3-arm64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Error: Cask 'font-dejavu-sans' is unavailable: No Cask with this name exists.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Reproduce https://github.com/Homebrew/homebrew-cask/issues/71221#issuecomment-799542763 to determine that `brew doctor`'s output is indeed very unhelpful.

### What happened (include all command output)?

1. Simulate having a `font-dejavu-sans` cask from before it was removed (?).
```
mkdir -p /opt/homebrew/Caskroom/font-dejavu-sans
```
2. run `brew doctor`

### What did you expect to happen?

brew doctor should explain that I have an obsolete cask and what I should do to remove it so that brew doctor can work.

At the very least, it should tell me a full path to things it doesn't like so I at least know where to look (I have two instances of `brew` installed, the other runs under rosetta).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
mkdir -p /opt/homebrew/Caskroom/font-dejavu-sans
brew doctor
```

**Comment by MikeMcQuaid** [comment]
Can I see the output of `brew doctor --debug` here? Thanks!
