### ISSUE TITLE
`brew search` should be aware of cask suffix name stripping conventions

### ISSUE THREAD

**Issue by jsoref** [Homebrew/brew#13028]
### Provide a detailed description of the proposed feature

`brew search` should automatically remove any of the suffixes that are supposed to be removed by packagers per https://docs.brew.sh/Cask-Cookbook#token-reference

### What is the motivation for the feature?

Due to brew's cask package naming conventions: https://docs.brew.sh/Cask-Cookbook#token-reference,
`Desktop` and similar are supposed to be stripped from the end of packages.

Unfortunately, not all `brew` users know/understand these conventions, which means it isn't unusual for a user to hear about `rancher-desktop`, and then try `brew search rancher-desktop`, when they do, they get results like this:

```sh
% brew search rancher-desktop
==> Formulae
rancher-compose
% brew search docker-desktop
==> Formulae
docker-ls
```

### How will the feature be relevant to at least 90% of Homebrew users?

Users will be able to do searches for products by the familiar name for the product and easily find the respective brew cask for it.

### What alternatives to the feature have been considered?

1. Asking to undo the https://docs.brew.sh/Cask-Cookbook#token-reference policy (this wasn't a serious consideration)
2. Provide some way for casks to define aliases for searching (I'm not terribly opposed to this approach, but it seems better to have `brew search` do the work than force each cask author to do it).

**Comment by rotu** [comment]
Is it in this scope to remove `homebrew` and `casks` from search terms?

As it is, `brew search home` will bring up every formula instead of just legitimate matches like `home-assistant`. Same with `brew search cas` finding all casks instead of e.g.  `yacas`.

**Comment by jandubois** [comment]
> Is it in this scope to remove `homebrew` and `casks` from search terms?

I think that is a separate problem that should have it's own Github issue.

**Comment by rotu** [comment]
> I think that is a separate problem that should have it's own Github issue.

Roger. https://github.com/Homebrew/brew/issues/13193

**Comment by MikeMcQuaid** [comment]
Partially addressed in https://github.com/Homebrew/brew/pull/13048
