### ISSUE TITLE
Create an installer

### ISSUE THREAD

**Issue by Solicity-dev** [Homebrew/brew#13045]
### Provide a detailed description of the proposed feature

Create an installer for MacOS to install homebrew.

### What is the motivation for the feature?

Simpler installation for all the newbies

### How will the feature be relevant to at least 90% of Homebrew users?

99% of the users want this feature.

### What alternatives to the feature have been considered?

NONE.

**Comment by carlocab** [comment]
There is an installer. See https://brew.sh and/or https://github.com/Homebrew/install.

**Comment by Solicity-dev** [comment]
A real installer not home-brew shit

**Comment by carlocab** [comment]
Yea, I'm about as motivated to do this as the amount of effort and courtesy you put into this issue, so we'll pass.

I'll also remind you that we have a [Code of Conduct](https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md#code-of-conduct). You will be blocked if you continue to fail to adhere to this.
