### ISSUE TITLE
Replace `git clone` with `degit` or `aho`

### ISSUE THREAD

**Issue by AmagiDDmxh** [Homebrew/brew#13046]
### Provide a detailed description of the proposed feature

Haven't dived into the source code of brew, didn't know why is the `git clone` used as the default download tool.

If this is possible, can we replace it to tools like [degit](https://github.com/Rich-Harris/degit) or [aho](https://github.com/egoist/aho). The tool simply downloads the whole repo without the huge bundle of git histories.

### What is the motivation for the feature?

Is too slow when trying to tap homebrew/core in the cloning process.

### How will the feature be relevant to at least 90% of Homebrew users?

Not to say there could be 90% of users can encounter this, but possible people live in where has poor network access to GitHub CDN would.

### What alternatives to the feature have been considered?

No yet.

**Comment by MikeMcQuaid** [comment]
> The tool simply downloads the whole repo without the huge bundle of git histories.

We intentionally want/need this.

> If this is possible, can we replace it to tools like [degit](https://github.com/Rich-Harris/degit) or [aho](https://github.com/egoist/aho).

These tools both require `npm` so cannot be used by most of our users without installing Homebrew first.

--- 

The WIP solution to this problem is `HOMEBREW_INSTALL_FROM_API`; check it out and see if it makes life better for you.
