### ISSUE TITLE
Parallel downloads

### ISSUE THREAD

**Issue by SonOfLilit** [Homebrew/brew#13064]
### Provide a detailed description of the proposed feature

Will you accept a pull request for parallel file downloads, e.g. with the UI agreed on in #1865?

I found a "yes" from 2017 in #1865, a "show us data that proves this will make installation faster" from May 2021 in #11363, and a "not going to do it because it complicates things with our github hosts"[1] from November 2021 in #12489.

Before I look into implementing it, I'd like to get the devs' position on this.

[1] which confuses me: to my understanding, if brew uses 1 or 4 connections at a time, average bandwidth and average open connections at the github servers stay the same (except for the secondary effect of people using brew more because it's more pleasant to use 😄)

### What is the motivation for the feature?

I'd like to spend (a lot) less time staring at `brew install`/`brew upgrade`.

Currently, for small files, download time seems to be dominated by handshake and headers. Downloading multiple resources at a time is considered best practice (browsers keep up to 6 connections per host, HTTP2 formalizes a download queue into the protocol).

### How will the feature be relevant to at least 90% of Homebrew users?

Presumably every brew user would like a much faster `brew install ffmpeg`

### What alternatives to the feature have been considered?

Keeping the current linear behavior.

(There are other solutions but they require changes at the server and that feels like a non-starter.)

**Comment by SonOfLilit** [comment]
The oldest issue I linked seems to have a good specification for the UX
(one thread shows progress, others are silent in the background; I'd maybe
add that whenever it's done with a file the first thread checks if any
files started/ finished downloading in other threads and displays messages
about it).

Deprecating can be done in parallel, but am I wrong that disabling parallel
downloads for formulae that have custom logic is enough to get this working?

**Comment by MikeMcQuaid** [comment]
> * Currently some formulae specify custom download strategies which should be deprecated (and replaced with a better API) to make the first point possible/easier to implement.

Personally: I don't think we should be doing this until this is fully rolled out and users complain about it.

**Comment by SonOfLilit** [comment]
Regarding the "one file at a time" limit: can it be increased to "four files at a time"?

It shouldn't have any serious effect on the server load, because the same numbers and sizes of files are downloaded each timespan, before and after this change.

**Comment by MikeMcQuaid** [comment]
> Regarding the "one file at a time" limit: can it be increased to "four files at a time"?

No. That's inconsiderate to the servers we download from.

> It shouldn't have any serious effect on the server load

It will literally quadruple the load.

**Comment by SonOfLilit** [comment]
I really don't believe it will.

Let me invoke a very very simplified model to explain why I think this way,
keeping in mind that reality is much more complicated.

If package installations were composed of 8 files, 8MB each, that took 1s
each to download, and we had a user installing a package every second, the
load at any given moment would be

8 users downloading 8MB every second

(you'd have the user that is downloading their first file, the user
downloading their second file, ..., up to the eighth file)

If however users would download 4 files at a time (assuming no bandwidth
limitations and no rate limiting), the load at any given time would be:

2 users downloading 4*8MB every second

because each user would finish in 2 seconds instead of 8.

Now, assume instead that each user was limited to a bandwidth of 8MB/second.

It would take a user 4 seconds to finish their first 4 files, then 4 more
seconds to finish the other 4 files.

So at each point in time, the server would be serving

8 users downloading 8MB every second

I was wrong about number of open connections remaining constant in all
cases, here we have x4 open connections, but given that github hosts these
files on Azure Blob and Azure Blob doesn't charge for connection time, only
for storage and bandwidth, and given that modern web servers don't care too
much about open connections, I don't think this would have a measurable
impact on github. (Is it my guess against yours, or do we know from them
that they do care and I should stop bothering you with this?)

**Comment by ivaquero** [comment]
> ### Provide a detailed description of the proposed feature
> Will you accept a pull request for parallel file downloads, e.g. with the UI agreed on in #1865?
> 
> I found a "yes" from 2017 in #1865, a "show us data that proves this will make installation faster" from May 2021 in #11363, and a "not going to do it because it complicates things with our github hosts"[1] from November 2021 in #12489.
> 
> Before I look into implementing it, I'd like to get the devs' position on this.
> 
> [1] which confuses me: to my understanding, if brew uses 1 or 4 connections at a time, average bandwidth and average open connections at the github servers stay the same (except for the secondary effect of people using brew more because it's more pleasant to use 😄)
> 
> ### What is the motivation for the feature?
> I'd like to spend (a lot) less time staring at `brew install`/`brew upgrade`.
> 
> Currently, for small files, download time seems to be dominated by handshake and headers. Downloading multiple resources at a time is considered best practice (browsers keep up to 6 connections per host, HTTP2 formalizes a download queue into the protocol).
> 
> ### How will the feature be relevant to at least 90% of Homebrew users?
> Presumably every brew user would like a much faster `brew install ffmpeg`
> 
> ### What alternatives to the feature have been considered?
> Keeping the current linear behavior.
> 
> (There are other solutions but they require changes at the server and that feels like a non-starter.)

Hi, @SonOfLilit, I would to like to share my workaround for brew casks by using [pueue](https://github.com/Nukesor/pueue), a command-line task management tool written in rust

```bash
function bisc {
        num=$#
        if [[ $num > 1 ]]; then
            echo "Trying to install $num cask in parallel"
            pueue group add brew_update
            pueue parallel $num -g brew_update

            for pkg in $@; do
                pueue add -g brew_update "brew install --cask $pkg"
            done
            sleep 3 && pueue status
        else
            brew install --cask $1
        fi
    }
```

For brew formulae, dependencies should be considered, however, I don't know ruby.

**Comment by SonOfLilit** [comment]
I'm convinced it can't be solved without imposing costs on our gracious
hosts. As far as I'm concerned, the issue can be closed.

**Comment by MikeMcQuaid** [comment]
Thanks for understanding @SonOfLilit!
