### ISSUE TITLE
Error report: Brewfile already exists

### ISSUE THREAD

**Issue by wurining** [Homebrew/brew#13076]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5f5af43244eaece1f09d695603e1a261676713a0
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 05ee6d711f33a7db2c363b3c3cf03096d23756d3
Core tap last commit: 7 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.rw5fhR8p2N/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.35.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.3.0.0.1.1645755326
Xcode: 13.3
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I reinstall the brew and use `brew bundle install --global` with Brewfile. Although I successfully install those old pkgs. But after this, every time I open a new terminal window or tab, brew always reports an error, like:
```
Last login: Fri Apr  1 18:12:13 on ttys000
Error: /Users/username/Brewfile already exists
(base)  wurining@MacBook-Pro-16 >
```

### What happened (include all command output)?

```
Last login: Fri Apr  1 18:12:13 on ttys000
Error: /Users/username/Brewfile already exists
(base)  wurining@MacBook-Pro-16 >
```

### What did you expect to happen?

Dont show the error. And I wanna know the reason.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just open a terminal.
```

**Comment by gromgit** [comment]
Assuming you're running Zsh as your shell, `man zsh` and read the *STARTUP/SHUTDOWN FILES* section. Your error strongly suggests that one of your shell's startup files contains a `brew bundle dump --global` command, which does _not_ overwrite the old Brewfile.

You either want to `brew bundle dump --global --force` to force overwriting, or probably _remove_ that line, as it doesn't make much sense to re-run a bundle dump every time you start a new shell.

**Comment by wurining** [comment]
@gromgit 
Thank you so much! Your advice looks quite useful. There indeed exists a `brew bundle dump` command in the file `.zprofile`. I cannot remember when it was added. Now I've cancelled this action.

.zprofile content:
```
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(/opt/homebrew/bin/brew shellenv)" brew bundle dump
```
