### ISSUE TITLE
Wrong version detected from package URL with `arm64` suffix

### ISSUE THREAD

**Issue by edmorley** [Homebrew/brew#13082]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5f5af43244eaece1f09d695603e1a261676713a0
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d696884e8a23e73b98f82985745bd6862aec6f6c
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Update the version of Pack CLI using `brew update && brew upgrade`.

### What happened (include all command output)?

The latest Pack CLI update was not detected:

```
$ brew update && brew upgrade
Already up-to-date.
```

This is because the Pack version is being auto-detected from the package URL incorrectly:

```
$ brew list pack --versions
pack 64
```

The real version is `0.24.1` - it appears the `64` is coming from the `arm64` suffix in the filename `pack-v0.24.1-macos-arm64.tgz`:
https://github.com/buildpacks/homebrew-tap/blob/3702664d9864cb4d7a17b65d9a6f9a315628d702/Formula/pack.rb#L9

### What did you expect to happen?

Homebrew should either:
1. Output an error (or at a warning) if a package URL contains multiple potential version numbers. Silently picking one of the numbers seems pretty fragile.
2. Or, have better heuristics for picking the version. eg: Favour version strings that have a `v` prefix to them, or have a deny-list of potential false positives (eg `arm64`, `amd64`, `x86_64` etc).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above.
```

**Comment by carlocab** [comment]
> 1. Output an error (or at a warning) if a package URL contains multiple potential version numbers. Silently picking one of the numbers seems pretty fragile.

This would likely lead to dozens (if not hundreds) of errors/warnings in Homebrew/core. We also typically handle issues like this using `brew audit`, but I don't think that's something you run, nor do we usually add audits that are only useful externally.

> 2. Or, have better heuristics for picking the version. eg: Favour version strings that have a `v` prefix to them, or have a deny-list of potential false positives (eg `arm64`, `amd64`, `x86_64` etc).

Homebrew formulae are meant to be built from source, so misdetecting the version of arch-suffixed binary packages is expected behaviour.

One immediate fix that is available to you is to specify the version explicitly in the formula. You will probably need to set `version_scheme 1` as well, or else `brew` will not consider version `0.24.1` newer than what it used to think the version was (`64`).

**Comment by edmorley** [comment]
Hi! Thank you for the fast reply :-)

Yeah I already have a PR to work around this:
https://github.com/buildpacks/pack/pull/1408

To me It feels like version auto-detection is perhaps a feature that is a bit too auto-magical, particularly given it doesn't issue warnings and just picks whatever string it feels like.

> Homebrew formulae are meant to be built from source, so misdetecting the version of arch-suffixed binary packages is expected behaviour.

There are lots of homebrew distributed binary packages, so I don't quite follow this? Do you mean this formula should have been a cask instead? I'm not overly familiar with the homebrew terminology here.

**Comment by carlocab** [comment]
> To me It feels like version auto-detection is perhaps a feature that is a bit too auto-magical, particularly given it doesn't issue warnings and just picks whatever string it feels like.

Perhaps, but note that the heuristics it uses works perfectly for 95+% of the 6000+ formulae in Homebrew/core.

> There are lots of homebrew distributed binary packages, so I don't quite follow this? Do you mean this formula should have been a cask instead? I'm not overly familiar with the homebrew terminology here.

A formula `url` is designed to be an architecture-independent source tarball. I'm aware that many misuse formulae by declaring `url`s in `if` blocks that branch based on the host architecture, but that's not really what formulae were designed for, so you're bound to encounter rough edges.

A cask would indeed be the right way to distribute a pre-built binary package, but we currently don't have support for casks on Linux (and none is planned as far as I am aware).

**Comment by MikeMcQuaid** [comment]
Passing on this. We'll accept specific PRs to fix specific version numbers/patterns.
