### ISSUE TITLE
Grant sudo permission before `brew upgrade`

### ISSUE THREAD

**Issue by jakelinnzy** [Homebrew/brew#13083]
### Provide a detailed description of the proposed feature

Have a `brew upgrade --validate-sudo` flag. When this flag is supplied, prompt the user for sudo password and keep the permission (by running `sudo --validate` every 5 minutes).

### What is the motivation for the feature?

- On a system with many packages installed, performing a full `brew upgrade` can take a significant amount of time. 
- Updating some casks require sudo permission, for example `kindle`.
- In a full `brew upgrade`, formulae are updated before casks. It's likely that a password prompt appears halfway.

Result: user runs `brew upgrade`, takes a nap, and come back the second day to discover a sudo password prompt blocking the upgrade.

### How will the feature be relevant to at least 90% of Homebrew users?

90% of macOS users (hopefully) have casks installed. They update their software from time to time.

### What alternatives to the feature have been considered?

1. Keep it as is.
2. Have a `requires_sudo` field for each cask. In a `brew upgrade` run, check if any cask to be updated has this field set to `true`.
3. Allow `sudo brew upgrade`.

**Comment by stephenwade** [comment]
Feature requests should not be marked as stale.

**Comment by MikeMcQuaid** [comment]
> Feature requests should not be marked as stale.

We disagree. When we add `help wanted` that's a sign we find it a good idea that we want someone to implement. When we don't, we're unsure of the benefit. Will review a PR for this but this isn't something we want to actively solicit a PR for.
