### ISSUE TITLE
Error: undefined method `major' when trying to update a cask

### ISSUE THREAD

**Issue by stephenwade** [Homebrew/brew#13086]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.5-16-gf6ab300
ORIGIN: https://github.com/Homebrew/brew
HEAD: f6ab300fc169777705f025c67c4b7c35605f4a66
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bb8cdb25eb60683f4024882b8ccdd41c46cd5964
Core tap last commit: 43 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3-x86_64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to update the SilentKnight cask.

I ran the command `brew bump-cask-pr --version 1.19 silentknight`.

### What happened (include all command output)?

Error: undefined method `major' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:41:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:62:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:62:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:49:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:37:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:37:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:37:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:134:in `bump_cask_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'

### What did you expect to happen?

A PR to update the cask should be submitted.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump-cask-pr --version 1.19 silentknight
```

**Comment by Bo98** [comment]
The error could be better here, but I believe it's because silentknight needs a version like `1.19,2022.04`.

https://github.com/Homebrew/homebrew-cask/blob/ed715391b2735caa126f33bc3e4506ce2adf9101/Casks/silentknight.rb#L2
