### ISSUE TITLE
brew report absence of command line tools only when I install python3

### ISSUE THREAD

**Issue by julytang** [Homebrew/brew#1309]
I have already installed the command line tools and make it up-to date.
<img width="653" alt="screen shot 2016-10-17 at 4 11 14 pm" src="https://cloud.githubusercontent.com/assets/6831587/19430377/964e7d0e-9486-11e6-95ed-f5718e8f4f0c.png">
<img width="276" alt="screen shot 2016-10-17 at 4 10 16 pm" src="https://cloud.githubusercontent.com/assets/6831587/19430394/a37119d8-9486-11e6-86eb-9514e5258512.png">
I can install other formula without warning but only python3.
<img width="642" alt="screen shot 2016-10-17 at 4 10 35 pm" src="https://cloud.githubusercontent.com/assets/6831587/19430499/0aff7ba8-9487-11e6-96fb-79915911ed76.png">
<img width="347" alt="screen shot 2016-10-17 at 4 31 06 pm" src="https://cloud.githubusercontent.com/assets/6831587/19430539/238e37ae-9487-11e6-8e1b-0bc64f823167.png">
What's wrong and how to resolve.
Thanks!

**Comment by MikeMcQuaid** [comment]
`xcode-select --install` will install them. The command-line tools listen in Xcode are not the ones we're talking about.
