### ISSUE TITLE
Only suggest changing taps to an ssh remote when it would be useful

### ISSUE THREAD

**Issue by eriksw** [Homebrew/brew#13097]
### Provide a detailed description of the proposed feature

Brew will only suggest changing private taps to an ssh origin when it would actually benefit the user.

Currently, the following message is emitted when installing a private tap unless the `--quiet` option is set:

```ruby
    $stderr.puts <<~EOS
      It looks like you tapped a private repository. To avoid entering your
      credentials each time you update, you can use git HTTP credential
      caching or issue the following command:
        cd #{path}
        git remote set-url origin git@github.com:#{full_name}.git
    EOS
```

I propose to add a check that will return early (skipping this message) in circumstances where there is a credential helper configured that renders the reason for the advice inapplicable.

Specifically, I propose to return before emitting that message if either of the following criteria are met:

1. `git config --get credential.https://github.com.helper` is non-empty
2. `git config --get credential.helper` is `manager-core`, `osxkeychain`, or `store`

Note: `manager-core` is [Git Credential Manager](https://github.com/GitCredentialManager/git-credential-manager)

### What is the motivation for the feature?

I help maintain private tools that we distribute to semi-technical users using a private tap.

We walk users through installing Homebrew, installing `gh`, authenticating with GitHub from `gh`, and finally running `gh auth setup-git`. The ability to follow these steps is generally pretty effective.

Where things go wrong is when users see the aforementioned text from brew. If they try to follow its guidance, they wind up going down a rabbit hole of trying to use ssh auth, trying to make an ssh key (a concept we do not expect or need them to be familiar with), etc...

I am proposing this change because I really dislike having to (try to) train users that generally they _should_ follow the advice of Homebrew's messages "... except for [this one thing]! Don't do [this one thing]!"

### How will the feature be relevant to at least 90% of Homebrew users?

I believe this is relevant to most users that tap private repos from github.com.

### What alternatives to the feature have been considered?

*   (Status Quo:) Complicated end-user training; having to support users that got led astray down the useless rabbit hole of making an ssh key.

*   Instructions including `brew tap --quiet` for the sole purpose of suppressing this one message. This is somewhat but not completely effective.

    I'd like to not have to worry about this even if we split things out/add separate taps. It would be much better if "brew install mycompany/mytap/thing" was the extent of directions needed.

**Comment by carlocab** [comment]
Seems reasonable to me. We'll review a pull request that fixes this.
