### ISSUE TITLE
Option to only run tests associated with changed files

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/brew#13146]
### Provide a detailed description of the proposed feature

```sh
$ brew tests --changed
```
I was imagining an option like the one above that would only run tests associated with files that have been modified on a feature branch instead of all of the tests.

### What is the motivation for the feature?

It would be much more convenient to do sporadic testing while working on a new feature or bug fix since you wouldn't have to run all of the tests or manually pick the tests you want to run one-by-one. It should also be faster since you are running fewer tests.

### How will the feature be relevant to at least 90% of Homebrew users?

It won't since it's a developer feature but hopefully it will be useful to contributors.

### What alternatives to the feature have been considered?

Keeping things the same.

**Comment by MikeMcQuaid** [comment]
This is a nice idea, we have something similar at work. My only concern is that this approach is not bullet-proof i.e. you can change one seemingly unrelated file and break many others that are nearly impossible to identify that need tested. Given the total runtime of `brew tests` is <5m I think this also reduces the need.

Thoughts?

**Comment by Bo98** [comment]
Generally files map to rspec files well so if you modify `utils/github.rb`, running `brew tests --only=utils/github` will cover most relevant tests. Definitely not foolproof as changes can have knock on effects to elsewhere in the codebase, but it is a start.

**Comment by MikeMcQuaid** [comment]
Yeh, this is something I've often done. a `brew tests --changed` or something could lean on that, I'm just concerned about whether it would be useful.

**Comment by apainintheneck** [comment]
Yeah, it's definitely not an essential feature, more something that would be nice to have. It would slot in between the `brew tests` and `brew tests --only=filename` options for when you're working on something that involves multiple files but you don't want to run all of the tests yet. The main thing is that you as a developer wouldn't have to think about which tests should be run.

Also, my mac is a bit old but the test suite takes a touch over 10 minutes on my machine.

It also wouldn't be that hard to implement. I got it working last night locally.

**Comment by MikeMcQuaid** [comment]
> The main thing is that you as a developer wouldn't have to think about which tests should be run.

Just a pedantic note: always need to still think about this!

> It also wouldn't be that hard to implement. I got it working last night locally.

👍🏻 to reviewing a PR on this. A `brew tests --changed` flag would make sense to me as something that could be added with little overhead.

Thanks @apainintheneck!
