### ISSUE TITLE
brew reports old command line tools, but they're actually newer

### ISSUE THREAD

**Issue by ohmantics** [Homebrew/brew#13155]
### `brew config` output

```shell
➜  ~ brew config
HOMEBREW_VERSION: 3.4.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 56415326bb8c9eccc6e53f3997b4e062b36402af
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 862bb75feebc1349ebe79f35b7ff99e5f9565777
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.eqVlLbzoLQ/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.0.0.0.1.1627064638
Xcode: 13.3.1
Rosetta 2: false
```

### `brew doctor` output

```shell
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.3.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ext4fuse
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Was just upgrading mcfly and got the complaint about my command line tools being old. They're actually newer, 13.3.1.

### What happened (include all command output)?

➜  ~ brew upgrade mcfly --force                     
==> Upgrading 1 outdated package:
cantino/mcfly/mcfly v0.5.13 -> v0.6.0
==> Downloading https://github.com/cantino/mcfly/releases/download/v0.6.0/mcfly-v0.6.0-x86_64-apple-darwin.tar.gz
Already downloaded: /Users/alexr/Library/Caches/Homebrew/downloads/f5756a00a503e0f49533329edd53d0a0152240917537894186c8a57bebc3a1f6--mcfly-v0.6.0-x86_64-apple-darwin.tar.gz
==> Upgrading cantino/mcfly/mcfly
  v0.5.13 -> v0.6.0 

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.3.

==> Caveats
ONE MORE STEP!

Add the following to the end of your ~/.bashrc, ~/.zshrc, or ~/.config/fish/config.fish file.

Bash:
  eval "$(mcfly init bash)"

Zsh:
  eval "$(mcfly init zsh)"

Fish:
  mcfly init fish | source
==> Summary
🍺  /opt/homebrew/Cellar/mcfly/v0.6.0: 3 files, 3.9MB, built in 1 second
==> Running `brew cleanup mcfly`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/mcfly/v0.5.13... (3 files, 4.1MB)

### What did you expect to happen?

No complaint about the command line tools. The checks in brew/Library/Homebrew/os/mac/xcode.rb need to be updated for Xcode 13.3.1, but also should probably just handle newer versions to avoid this confusing error.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade mcfly --force
or
brew doctor
```

**Comment by carlocab** [comment]
`brew` is not complaining about your Xcode installation, which is up-to-date. The complaint is about your outdated CLT installation, which is a different thing. Your CLT version is shown in the line
```
CLT: 13.0.0.0.1.1627064638
```
Installing the CLT for Xcode 13.3 will remove the warning.

**Comment by ohmantics** [comment]
<img width="381" alt="Screen Shot 2022-04-17 at 10 51 43 PM" src="https://user-images.githubusercontent.com/1445253/163761619-2c1633ce-1640-45cc-bb03-d9adb38dfc2b.png">

Xcode thinks they're up to date.

**Comment by carlocab** [comment]
Those are the command line tools in your Xcode.app, which is different from the Command Line Tools for Xcode.

**Comment by carlocab** [comment]
If you're still skeptical, you can check the output of
```
/Library/Developer/CommandLineTools/usr/bin/clang --version
```
and match it against the version in this table: https://en.wikipedia.org/wiki/Xcode#Xcode_11.x_-_13.x_(since_SwiftUI_framework)_2

**Comment by ohmantics** [comment]
Gah! I'd just blown away /Library/Developer/CommandLineTools and softwareupdate clearly did the wrong thing. The error message has instructions that did not work. Why aren't the set installed by Xcode itself sufficient here?

**Comment by carlocab** [comment]
> Why aren't the set installed by Xcode itself sufficient here?

It depends on what exactly "here" is. For what you were doing above (installing `cantino/mcfly/mcfly`), Xcode itself probably is sufficient.

Most formulae manage just fine with only one of Xcode.app or the CLT, some require neither. Some require choosing between the two at build-time, where the choice you've made must then also be available at run-time. The CLT is, for many reasons (e.g. size), a superior choice for those instances.
