### ISSUE TITLE
Provide an option to auto-update homebrew and check for update when you open a terminal

### ISSUE THREAD

**Issue by igauravsehrawat** [Homebrew/brew#13153]
### Provide a detailed description of the proposed feature

Currently homebrew update runs only when you try to install something and if something is missing or wrong, you are left in-a-fix

One of the example is below
![Screen Shot 2022-04-17 at 13 24 14](https://user-images.githubusercontent.com/3696327/163713070-aa6ceda0-f6e6-400f-aaf5-2cc745f1e7e4.png)

What I believe can be done is what Oh-My-Zsh(https://ohmyz.sh/) does with auto-update?
It's behavior as below
- you can set auto-update on or off
- when you open a terminal, if internet is connected, it will look for an update and ask you if you want to update or not
- since you can do things in parallel you would say "yes"

Please consider this feature
We can take some inspiration from source code here: https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/check_for_upgrade.sh 

### What is the motivation for the feature?

This saves you time, effort and most important being in zone to get things done "in advance".

I have seen my productivity been broken because things were just not ready and then you get distracted(sometimes)
![sad panda gif](https://media.giphy.com/media/7p3e2WCM0VEnm/giphy.gif)

### How will the feature be relevant to at least 90% of Homebrew users?

This feature will be deal-breaker(I think) for 90+% of Homebrew users!

It will not make you a 10x developer...but you may feel like one. 
- Inspired by oh-my-zsh

### What alternatives to the feature have been considered?

I feel the only alternative is to set an alarm or reminder on a frequency basis and do things manually(ewww)

Automation is word of the "year", right?

**Comment by carlocab** [comment]
You may be interested in https://github.com/Homebrew/homebrew-autoupdate.

In case that isn't enough, note that you can also always set up your own automation (e.g. using `launchd`) so that you get exactly the behaviour you are looking for.

**Comment by igauravsehrawat** [comment]
Many thanks @carlocab
