### ISSUE TITLE
brew cleanup skips two Formulae declaring they are not installed (but they are)

### ISSUE THREAD

**Issue by instanttim** [Homebrew/brew#13162]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09e766f83c8a420cce9e2210c46a24ec3864a094
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 057c175d90aad8d82ad5dadb04ab16194bd3ca58
Core tap last commit: 7 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.36.0 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-x86_64
CLT: 13.3.1.0.1.1648687083
Xcode: 13.3.1
```

### `brew doctor` output

```shell
NOTE: my employer/company ends up installing some dylibs, headers, and static libraries. I have redacted them from the doctor output, but since I have no problem building and installing httpd and php, I don’t believe this is important information. My issue is only with the cleanup action failing.

--

Warning: Some frameworks can be picked up by CMake's build system and will likely
cause the build to fail. To compile CMake, you may wish to move these
out of the way:
  /Library/Frameworks/libcurl.framework

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
[redacted]

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
[redacted]

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
[redacted]
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew cleanup (just as periodic maintenance) 

### What happened (include all command output)?

```
> brew cleanup
Warning: Skipping httpd: most recent version 2.4.53_1 not installed
Warning: Skipping php: most recent version 8.1.5 not installed

> brew info httpd
httpd: stable 2.4.53 (bottled)
Apache HTTP server
https://httpd.apache.org/
/usr/local/Cellar/httpd/2.4.53.reinstall (1,662 files, 31.7MB) *
  Poured from bottle on 2022-04-08 at 15:57:43
[…]

> brew info php
php: stable 8.1.5 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/8.1.5.reinstall (514 files, 80MB) *
  Poured from bottle on 2022-04-19 at 11:12:09
[…]
```

### What did you expect to happen?

Running brew update, upgrade, and cleanup should have resulted in no skipping of anything as everything should have been up-to-date.

I realized both of these had their directories suffixed with “.reinstall”. I manually renamed the directories removing the suffix and cleanup no longer skipped php. I realized the httpd version was 2.4.53 where as brew cleanup was claiming 2.4.53_1 was the current version. So I was able to force httpd to update to the _1 version of the formula by manually doing `brew update httpd` 

At that point `brew cleanup` ran without skipping anything. But PHP needed to be relinked manually.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install php
brew install httpd
…
brew update
brew upgrade
brew cleanup
```

**Comment by MikeMcQuaid** [comment]
> I realized both of these had their directories suffixed with “.reinstall”. I manually renamed the directories removing the suffix and cleanup no longer skipped php. I realized the httpd version was 2.4.53 where as brew cleanup was claiming 2.4.53_1 was the current version. So I was able to force httpd to update to the _1 version of the formula by manually doing `brew update httpd`

Closing given this.

**Comment by instanttim** [comment]
I suppose the issue is how did I end up with `.reinstall` directories but not the actual ones? It seems like when a “reinstall” happens it renames the current folder and allows the new installation to go to the proper folder name, then tries to delete the `.reinstall` directory. I had _only_ the `.reinstall` directories for installed and functioning packages. 

Isn’t that weird and an indication of an issue?

**Comment by MikeMcQuaid** [comment]
> I suppose the issue is how did I end up with `.reinstall` directories but not the actual ones? It seems like when a “reinstall” happens it renames the current folder and allows the new installation to go to the proper folder name, then tries to delete the `.reinstall` directory. I had _only_ the `.reinstall` directories for installed and functioning packages.

By cancelling a `reinstall` operation mid-way through.

> Isn’t that weird and an indication of an issue?

If you or someone else can reproduce it: yeh, it's something we'll look into. Without reproduction steps, though, we're kind of in the dark dealing with it.
