### ISSUE TITLE
brew upgrade aborted, brew now thinks everything is up to date

### ISSUE THREAD

**Issue by prasselpikachu** [Homebrew/brew#1316]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
#### What I did:
- I ran `brew update` and then `brew upgrade`
- I cancelled brew upgrade right at the beginning with ^C
#### What I expected:

After running `brew upgrade` again, it would resume upgrading (like apt-get or any linux package manager)
#### What actually happened:

It suddenly acted like all upgrades were already applied. When running `brew cleanup`, it noted that it wouldn't clean up some packages because they're not upgraded to their latest version yet.
Neither `brew update`, `brew doctor` or running `brew upgrade` on a single package did anything.
### Outputs:

**brew update**

```
Already up-to-date.
```

**brew upgrade**

```
<no output>
```

**brew doctor**

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  sshfs
```

**brew link sshfs**

```
Linking /usr/local/Cellar/sshfs/2.8... 
Error: Could not symlink bin/sshfs
Target /usr/local/bin/sshfs
already exists. You may want to remove it:
  rm '/usr/local/bin/sshfs'

To force the link and overwrite all conflicting files:
  brew link --overwrite sshfs

To list all files that would be deleted:
  brew link --overwrite --dry-run sshfs
```

**brew cleanup**

```
Warning: Skipping net-snmp: most recent version 5.7.3 not installed
```

**brew upgrade net-snmp**

```
Error: net-snmp 5.7.3.pre3 already installed
```

**Comment by prasselpikachu** [comment]
After looking around I found the Locks directory and there were .brewing files for several packages and also an update lock file as per https://github.com/Homebrew/legacy-homebrew/issues/8555
brew apparently seems to ignore those.

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by MikeMcQuaid** [comment]
Closing due to no response.
