### ISSUE TITLE
Use livecheck in bump-cask-pr

### ISSUE THREAD

**Issue by nihaals** [Homebrew/brew#13166]
### Provide a detailed description of the proposed feature

Something like `$ brew bump-cask-pr cask-name` or with a required `--livecheck` flag instead of defaulting to it, which uses the livecheck to get the latest version instead of requiring `--version`.

### What is the motivation for the feature?

Currently if you want to bump a cask's version you need to get the latest version either from the site/app or from `brew livecheck`/`brew bump`. Since Homebrew has access to the current latest version already with the livecheck, passing the actual version shouldn't need to be *required* when bumping. You can currently use `brew livecheck --json` to make your own function that passes it for you, but this adds complexity for a new user to use it.

A disadvantage of this is that it might make someone pay less attention to the update and not see e.g. an Apple silicon version being added or new files that could be added to `zap`, although for people already just using the livecheck and making the PR straight away, this wouldn't make a difference. If it did cause an increase of these kinds of PRs it would add more work during review of updates.

### How will the feature be relevant to at least 90% of Homebrew users?

This is for users who update casks, but for those users it will make it a faster process for anyone who sees an app update themselves and wants to PR a version bump.

### What alternatives to the feature have been considered?

I considered writing my own wrapper that uses `brew livecheck --json` but realised this would likely be useful for more people and might make sense to be part of the command as a flag.

**Comment by cho-m** [comment]
Have you tried `brew bump --open-pr`?

**Comment by nihaals** [comment]
> Have you tried `brew bump --open-pr`?

I did, but noticed that it had a lack of config flags compared to `brew bump`. I'm not sure if it makes more sense to try to:
- Add livecheck to `bump-cask-pr`
- Add more flags to `brew bump --open-pr`
- Try to merge the commands in some way

A note on the final suggestion, I wasn't aware of `brew bump` until I tried searching to see if this (`--livecheck`) had already been suggested in the past and saw references to it in relation to CI. As `brew bump --open-pr` and `brew bump-cask/formula-pr` appear quite similar, maybe there should be some docs on why both exist/when to use each one? Having most of the functionality on `brew bump` sounds nice as it could be more general, but I assume there's a reason this hasn't happened already, e.g. avoiding an overly complex command.

**Comment by nihaals** [comment]
> > * Add more flags to `brew bump --open-pr`
> 
> Yeh, this would be the preferred option here.

Should I edit the title and OP/create a new issue or leave it as is?

**Comment by MikeMcQuaid** [comment]
@nihaals whichever you'd prefer!

**Comment by nihaals** [comment]
Closing in favour of #13171
