### ISSUE TITLE
brew search fails with error about missing java cask

### ISSUE THREAD

**Issue by juergenpf** [Homebrew/brew#13168]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09e766f83c8a420cce9e2210c46a24ec3864a094
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d644302666e610e8731c9cd8643457d3ebf1484c
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.SDBAO5ESQI/org.xquartz:0
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.3.1.0.1.1648687083
Xcode: 13.3.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ykclient

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10-config
  /Library/Frameworks/Python.framework/Versions/3.10/bin/python3-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libjson-c.2.dylib
  /usr/local/lib/libpas2jslib.dylib
  /usr/local/lib/libykclient.3.dylib
  /usr/local/lib/libykpers-1.1.dylib
  /usr/local/lib/libyubikey.0.dylib
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Search brew for octave packages with this command

brew search octave

I have octave already installed

### What happened (include all command output)?

Error: Cask 'java_11_0_2' is unavailable: No Cask with this name exists.

### What did you expect to happen?

List of all packages containing the name octave

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew search octave
```

**Comment by MikeMcQuaid** [comment]
Can you include the full output of the command verbatim and the output of `brew search --debug octave` as well? Thanks!

**Comment by juergenpf** [comment]
$ brew search --verbose octave
Error: Cask 'java_11_0_2' is unavailable: No Cask with this name exists.

$ brew search --debug octave
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.4.7\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.3.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/code\?q=user\%3AHomebrew\+path\%3AFormula\+path\%3ACasks\+path\%3A.\+filename\%3Aoctave\+extension\%3Arb\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --dump-header /private/tmp/github_api_headers20220422-96458-tc3nob
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/octant.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/octave.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/buildbot.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/buildbot-worker.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/elfx86exts.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/fig2dev-octave-app.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/gnu-tar-octave-app.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/gnuplot-octave-app.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/gnuplot-qt512.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/gnuplot-qt513.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/gnuplot-qt514.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/gnuplot-qt515.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/librsb.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/lxqt-build-tools.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/netpbm-octave-app.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-default.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-octave-app.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-octave-app-qt512.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-octave-app-qt514@5.2.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-octave-app-vanilla-qt.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-octave-app@4.4.1.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-octave-app@5.1.0.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-octave-app@5.2.0.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-octave-app@6.1.0.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-octave-app@6.2.0.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-octave-app@6.3.0.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave-stable.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave@4.4.1.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave@5.1.0.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave@5.2.0.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave@6.1.0.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave@6.2.0.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/octave@6.3.0.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/openjdk-octave-app.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/proj@5.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/pyqt-octave-app.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/python2.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qscintilla2-octave-app.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qscintilla2-qt512.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qscintilla2-qt513.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qscintilla2-qt514.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qscintilla2-qt515.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qt-octave-app.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qt-octave-app_5.12.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qt-octave-app_5.14.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qt-octave-app_5.15.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qt_5.12.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qt_5.13.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qt_5.14.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qt_5.15.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qt_6_0_beta.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qterminal.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/qtermwidget.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/sip-octave-app.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/sundials@2.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/octave-app/homebrew-octave-app/Formula/sundials@3.rb
Error: Cask 'java_11_0_2' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:196:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/opt/homebrew/Library/Homebrew/extend/os/mac/search.rb:42:in `block in search_casks'
/opt/homebrew/Library/Homebrew/extend/os/mac/search.rb:41:in `map'
/opt/homebrew/Library/Homebrew/extend/os/mac/search.rb:41:in `search_casks'
/opt/homebrew/Library/Homebrew/cmd/search.rb:130:in `search_names'
/opt/homebrew/Library/Homebrew/cmd/search.rb:82:in `search'
/opt/homebrew/Library/Homebrew/brew.rb:110:in `<main>'

**Comment by bayandin** [comment]
It looks like our `FromTapLoader` doesn't recognise `octave-app/octave-app/java_11_0_2` because of the regexp that we use: 
```
# Match taps' casks, e.g. `someuser/sometap/somecask`
HOMEBREW_TAP_CASK_REGEX = %r{^([\w-]+)/([\w-]+)/([a-z0-9\-]+)$}.freeze`
```

I guess we can safely(?) allow using `_` in cask names. Am I missing something @MikeMcQuaid?

**Comment by bayandin** [comment]
@juergenpf should be fixed now, just run `brew update` to get the update:

```
$ brew search octave
==> Formulae
octave                                                         octave-app/octave-app/octave-octave-app@4.4.1                  octave-app/octave-app/qscintilla2-qt513
octave-app/octave-app/buildbot                                 octave-app/octave-app/octave-octave-app@5.1.0                  octave-app/octave-app/qscintilla2-qt514
octave-app/octave-app/buildbot-worker                          octave-app/octave-app/octave-octave-app@5.2.0                  octave-app/octave-app/qscintilla2-qt515
octave-app/octave-app/elfx86exts                               octave-app/octave-app/octave-octave-app@6.1.0                  octave-app/octave-app/qt-octave-app
octave-app/octave-app/fig2dev-octave-app                       octave-app/octave-app/octave-octave-app@6.2.0                  octave-app/octave-app/qt-octave-app_5.12
octave-app/octave-app/gnu-tar-octave-app                       octave-app/octave-app/octave-octave-app@6.3.0                  octave-app/octave-app/qt-octave-app_5.14
octave-app/octave-app/gnuplot-octave-app                       octave-app/octave-app/octave-stable                            octave-app/octave-app/qt-octave-app_5.15
octave-app/octave-app/gnuplot-qt512                            octave-app/octave-app/octave@4.4.1                             octave-app/octave-app/qt_5.12
octave-app/octave-app/gnuplot-qt513                            octave-app/octave-app/octave@5.1.0                             octave-app/octave-app/qt_5.13
octave-app/octave-app/gnuplot-qt514                            octave-app/octave-app/octave@5.2.0                             octave-app/octave-app/qt_5.14
octave-app/octave-app/gnuplot-qt515                            octave-app/octave-app/octave@6.1.0                             octave-app/octave-app/qt_5.15
octave-app/octave-app/librsb                                   octave-app/octave-app/octave@6.2.0                             octave-app/octave-app/qt_6_0_beta
octave-app/octave-app/lxqt-build-tools                         octave-app/octave-app/octave@6.3.0                             octave-app/octave-app/qterminal
octave-app/octave-app/netpbm-octave-app                        octave-app/octave-app/openjdk-octave-app                       octave-app/octave-app/qtermwidget
octave-app/octave-app/octave-default                           octave-app/octave-app/proj@5                                   octave-app/octave-app/sip-octave-app
octave-app/octave-app/octave-octave-app                        octave-app/octave-app/pyqt-octave-app                          octave-app/octave-app/sundials@2
octave-app/octave-app/octave-octave-app-qt512                  octave-app/octave-app/python2                                  octave-app/octave-app/sundials@3
octave-app/octave-app/octave-octave-app-qt514@5.2              octave-app/octave-app/qscintilla2-octave-app                   octant
octave-app/octave-app/octave-octave-app-vanilla-qt             octave-app/octave-app/qscintilla2-qt512

==> Casks
octave-app/octave-app/adoptopenjdk-local                       octave-app/octave-app/java_11_0_2                              octave-app/octave-app/octave-app
```

**Comment by carlocab** [comment]
`brew update` fixes it now only if you're on the development version of `brew`. Users on the stable tag will get it at the next release. That is likely to be early next week.

**Comment by juergenpf** [comment]
Ok thx, so I'll wait until the stable version gets the update and confirm then the problem as solved.

**Comment by juergenpf** [comment]
Thx, works now.
