### ISSUE TITLE
Show notification or ring bell when user input is requested during installation/upgrade

### ISSUE THREAD

**Issue by kashav** [Homebrew/brew#13182]
### Provide a detailed description of the proposed feature

Sometimes I'm upgrading a bunch of packages and one of those packages requires me to input a password (usually Virtualbox). My terminal is in the background so I'm not aware that it's waiting for user input until I check it. I think it'd be helpful if brew sent an os notification or rang the terminal bell whenever user input is requested.

### What is the motivation for the feature?

Mostly described above. It's slightly annoying to come back to the terminal and see that the process was hung waiting on user input.

### How will the feature be relevant to at least 90% of Homebrew users?

It seems like a useful feature to me, but I don't know if it'll be relevant to 90% of Homebrew users.

### What alternatives to the feature have been considered?

I spent a few minutes thinking of alternatives, and came up with one:

Maybe when running `brew upgrade`, Homebrew can check if any of the upgrades will require user input (which is probably a password in most cases?) and ask for that at the start of the process, but I don't think that's better than the proposed solution.

**Comment by kashav** [comment]
Wouldn't mind working on this if there's interest.

**Comment by MikeMcQuaid** [comment]
CC @vitorgalvao @Homebrew/cask as, if I remember correctly, there's not a full-proof way of knowing if `sudo` is required.

**Comment by SMillerDev** [comment]
AFAIK cask just opens the pkg installer and that could prompt for a password (but that is not required)

**Comment by MikeMcQuaid** [comment]
I think this is a CANTFIX for now then, sadly, sorry!

**Comment by kashav** [comment]
No worries, thanks for the discussion.
