### ISSUE TITLE
Membership 2022

### ISSUE THREAD

**Issue by issyl0** [Homebrew/brew#13180]
Every year around the time of the AGM we ask members from the previous year to confirm they are still interested in being a voting member of Homebrew (and all that that entails - membership of the GitHub org, Slack channels, ability to vote in the AGM).

The 2022 AGM took place yesterday, so we're asking those who did not vote[1] to confirm that they wish to remain members in 2022/23.

Those members are:

@cho-m
@cnnrmnn
@claui
@dtrodrigues
@gdams
@igas
@gauthamgoli
@GregBrimble
@maxim-belkin
@tschoonj
@vidusheeamoli
@whoiswillma
@xu-cheng
@zbeekman
@zmwangx

If you **do** wish to remain a voting member of Homebrew please comment on this issue with 👍🏻, or message me on Slack.

If you **do not** wish to remain a voting member of Homebrew please comment on this issue with 🚀 , or message me on Slack.

Members who have not responded will be removed three weeks from now (2022-04-30) [in accordance with the governance procedures](https://github.com/Homebrew/homebrew-governance-private/blob/39611c1f8246485335d6d4a4c983aaf47946f3b0/Homebrew-Governance.md?plain=1#L71).

Thank you!

[1] All votes were anonymous - for those of you not mentioned in this issue who did vote, we do not know who you voted for - we only know who submitted OpaVote ballots as the emailed links were unique to each person.

**Comment by GregBrimble** [comment]
Sorry folks, between a new job and moving city, my time has been pretty stretched. I wish y'all and the Homebrew project, all the best! 🚀

**Comment by issyl0** [comment]
Thanks for the replies.

I removed the four people who responded with 🚀. Thanks, folks, for all your hard work on Homebrew over the years. All the best! ❤️
