### ISSUE TITLE
Update docs because system python changed in macOS 12.3

### ISSUE THREAD

**Issue by davidchall** [Homebrew/brew#13200]
### Provide a detailed description of the proposed feature

In macOS 12.3 (released March 14), Apple removed the system python2 installation. After CLT installation, there is a system python3 installation which includes pip3. See [here](https://www.macrumors.com/2022/01/28/apple-removing-python-2-in-macos-12-3/) and [here](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python) for details.

The Homebrew docs (particularly [Homebrew and Python](https://docs.brew.sh/Homebrew-and-Python) and [Python for Formula Authors](https://docs.brew.sh/Python-for-Formula-Authors)) often says the system Python is python2 and doesn't include pip. This is no longer true for the latest macOS.

### What is the motivation for the feature?

See above. I didn't see an issue template designed for updating documentation, so I chose "feature request".

### How will the feature be relevant to at least 90% of Homebrew users?

N/A. I didn't see an issue template designed for updating documentation, so I chose "feature request".

### What alternatives to the feature have been considered?

N/A. I didn't see an issue template designed for updating documentation, so I chose "feature request".

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by davidchall** [comment]
Hi @MikeMcQuaid - sorry, but I don't think I'm the right person to work on this. I know the relationship between Homebrew and Python is a very complex one, and I've not worked on Homebrew formulae in quite a few years. I just ran into this issue when I recently setup a new laptop.

I expect formulae might need some logic like `if MacOS.full_version >= "12.3"`. It seems like this change could have far-reaching consequences.

**Comment by Bo98** [comment]
> I expect formulae might need some logic like `if MacOS.full_version >= "12.3"`. It seems like this change could have far-reaching consequences.

For formulae, we're deprecating anything that truly only works with Python 2: https://github.com/Homebrew/homebrew-core/issues/93940.
