### ISSUE TITLE
Migrate from Google Analytics to InfluxDB before July, 2023

### ISSUE THREAD

**Issue by SukkaW** [Homebrew/brew#13211]
### Provide a detailed description of the proposed feature

Migrate [homebrew's built-in Google Analytics](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/analytics.rb) to Google Analytics 4 or another platform.

Note there are some catches. Unlike Google Universal Analytics, Google Analytics 4 doesn't have good documentation on the new Measurement Protocol. Google Analytics 4 also has a very limited ability to set custom fields and metrics, and Google Analytics 4 dashboard doesn't have any out-of-box support for viewing custom fields.

IMHO, Google Analytics 4 is only good for E-commerce tracking and no longer fits Homebrew's usage case, so I would suggest other analytics platforms:

- [Sentry](https://sentry.io/welcome/)
- [Segment](https://segment.com/)
  

### What is the motivation for the feature?

Ref:

- https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/

> All standard Universal Analytics properties will stop processing new hits on July 1, 2023, and 360 Universal Analytics properties will stop processing new hits on October 1, 2023. After that, you’ll be able to access your previously processed data in Universal Analytics for at least six months.

- https://support.google.com/analytics/answer/11583528?hl=en

> On July 1, 2023, standard Universal Analytics properties will stop processing new hits. If you still rely on Universal Analytics, we recommend that you [prepare to use Google Analytics 4](https://support.google.com/analytics/answer/10759417) going forward.

### How will the feature be relevant to at least 90% of Homebrew users?

The change would affect all Homebrew users that have the Analytics enabled. However, the userbase shouldn't notice any differences in their daily usage.

### What alternatives to the feature have been considered?

Completely remove the anonymous aggregate analytics. Then we don't need to worry about any of Google's deprecation.

**Comment by Bo98** [comment]
Thanks for the heads up here!

**Comment by deepskydata** [comment]
We had some discussion about this on LinkedIn: https://www.linkedin.com/posts/eike-pierstorff-77a4a166_homebrew-googleanalytics-activity-6947804207689158657-bk5y

Moving away from GA is I think a good idea due to the BlackBox on how Google handles the data.

If this data is still important for you I would look into alternatives that are smaller and more transparent how the data is stored.

Segment is no option since it is simply too expensive for this solution and would be over-engineered.


Other solutions could be:
- Plausible analytics
- Fathom analytics

Both would need a managed account or in Plausible's case could run on a self-hosted env.

I am happy to help with any kind of setup but would need more information about limitations (hosting costs) or other requirements.

**Comment by MikeMcQuaid** [comment]
The migration to InfluxDB has begun as-of today.

**Comment by MikeMcQuaid** [comment]
The remaining work:
- [ ] implement everything in https://github.com/Homebrew/homebrew-formula-analytics/blob/20bf1d644f32b28eb2a33f8c594e75369a412847/cmd/formula-analytics.rb#L358-L397 so we can change the same data with InfluxDB as we currently can with Google Analytics (bar the 365 days where we don't have enough data yet)
- [ ] use this data for the API: https://github.com/Homebrew/homebrew-formula-analytics/pull/384
- [ ] ensure that formulae.brew.sh and the `brew info --analytics` are correctly using the new data and that the data we've gathered looks correct in InfluxDB
- [ ] delete all the Google Analytics related code
- [ ] delete all the Google Analytics Homebrew account(s)

**Comment by SMillerDev** [comment]
The query I wrote before doesn't work anymore with the new analytics schema and after half a day of trying I still can't figure out how to write one that does. Anything I'm currently trying either gives incorrect data or times out when you request more than one day of data. I'm afraid that without package names as a tag this query just won't work since that's the indexed information we need.

**Comment by MikeMcQuaid** [comment]
@SMillerDev Ouch, thanks for trying. I'm not sure what we should be doing here instead, then. Perhaps we should ask the wider community on Twitter or InfluxDB themselves for help? Alternatively, perhaps we need to write our own solution to this problem.

**Comment by SMillerDev** [comment]
Asking the community for help seems like a good plan, I'll write down the current schema here later and then we can tweet/toot/whatever about it after.

**Comment by SMillerDev** [comment]
The problem: our analytics require the number of entries grouped by `package` which doesn't seem to be possible.

---
Bucket schema:
Measurement `build_error`:
Fields: options, os_name_and_version, package, tap_name, version
Tags: arch, ci, default_prefix, devcmdrun, developer, on_request, os, prefix

Measurement `cask_install`:
Fields: os_name_and_version, package, tap_name, version
Tags: arch, ci, default_prefix, devcmdrun, developer, on_request, os, prefix

Measurement `formula_install`:
Fields: options, os_name_and_version, package, tap_name, version
Tags: arch, ci, default_prefix, devcmdrun, developer, on_request, os, prefix

**Comment by Bo98** [comment]
I'm not an expert on whether that's the most efficient schema or not, it could be that adding package to tags fixes the problems if it doesn't make cardinality too extreme.

If that schema is in fact ok, an alternative could be that we have a task that consolidates daily amounts into each day. So it'll tally up each formula's numbers for a 24 hour period and save the result into a new meaurement, which will mean less data to timeout over.

**Comment by MikeMcQuaid** [comment]
> I'm not an expert on whether that's the most efficient schema or not, it could be that adding package to tags fixes the problems if it doesn't make cardinality too extreme.

It does. We did that before and things fell over.

> So it'll tally up each formula's numbers for a 24 hour period and save the result into a new meaurement, which will mean less data to timeout over. InfluxDB supports tasks so this is all setup and run using the database itself.

This seems like a very good idea 👍🏻

**Comment by SMillerDev** [comment]
> InfluxDB 3.0 now supports unlimited [cardinality](https://www.influxdata.com/glossary/cardinality/), which expands the use cases for InfluxDB to any time-stamped data. Unlike other analytics databases, InfluxDB 3.0 features massive gains in ingest performance, scalability, resilience, and efficiency, even as data complexity and cardinality increase.

https://www.influxdata.com/blog/introducing-influxdb-3-0/

---

That would be great, but I can't figure out how we would upgrade. I guess I'll start figuring out tasks.

**Comment by MikeMcQuaid** [comment]
> That would be great, but I can't figure out how we would upgrade.

Could be worth contacting their support on this (and on the issues we're having in general)?

**Comment by SMillerDev** [comment]
Contacted support about the migration and figured out the tasks. Will make a PR based on those soon-ish.
