### ISSUE TITLE
Brew update fails when ssh is configured to use environment variables

### ISSUE THREAD

**Issue by mkw** [Homebrew/brew#13219]
### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 3.4.9-29-gea72240
ORIGIN: https://github.com/Homebrew/brew
HEAD: ea722400cd52bc514475ffccf292ea3ca6463393
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0ceeffe34f55e1d4a14902d0db6f9a998abf0d97
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Th9buwtQgD/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.3.1.0.1.1648687083
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
$ # [None of these warnings are related to my issue]
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  szip

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  docker-machine
  gdub
  ilmbase

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/mwerle/.indeed-dev-tools/bin/create-mesh-local-bootstrap-config

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: A '.pydistutils.cfg' file was found in $HOME, which may cause Python
builds to fail. See:
  https://bugs.python.org/issue6138
  https://bugs.python.org/issue4655

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  gng
  gping
  wireshark
  resty
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I need to forward sockets for GPG signatures to a remote host, so in my SSH configuration, I have something like this:

```
Host *.subdomain.example.com
  RemoteForward /run/user/1001/gnupg/S.gpg-agent ${GPG_AGENT_EXTRA}
```

I also have:
```
Host tap-repo-server.other-subdomain.example.com
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_rsa

  # Keep ssh connections alive for 30*30 seconds (15 minutes) to
  # allow for long running pre-push hooks
  ServerAliveInterval 30
  ServerAliveCountMax 25
```

I also have a tap at: /opt/homebrew/Library/Taps/my-tap-group/my-tap

With the git config:

```
[remote "origin"]
	url = git@tap-repo-server.other-subdomain.example.com: my-tap-group/my-tap.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

### What happened (include all command output)?

```
$ brew update
vdollar_percent_expand: env var ${GPG_AGENT_EXTRA} has no value
/Users/mwerle/.ssh/config line 19: Bad forwarding specification.
/Users/mwerle/.ssh/config: terminating, 1 bad configuration options
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /opt/homebrew/Library/Taps/my-tap-group/my-tap failed!
```

### What did you expect to happen?

The update should succeed because the environment variable configuration is not required in the ssh host configuration relevant to the `brew update` command.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Tap a repository using an SSH URL.
2. Add configuration to any host (can be a fake one) in `~/.ssh/config` including an environment variable.
3. Run `brew update`.
```

**Comment by MikeMcQuaid** [comment]
> The update should succeed because the required environment variable is present in the environment when I execute `brew update`.

Homebrew intentionally filters out all environment variables. We do not support tapped repositories that require environment variables to be passed to work.

**Comment by mkw** [comment]
The repository I'm trying to pull from does not require environment variables at all. The environment variables are for _another_ host. There is no way to pull from _any_ repository using SSH if _any_ SSH configured requires an environment variable.

**Comment by mkw** [comment]
I updated the original report to better reflect this. It's arguably a limitation of SSH, but it means that I cannot effectively use _any_ SSH taps and still use _any_ environment variables, even if they have nothing to do with the taps.

**Comment by MikeMcQuaid** [comment]
Ok, makes more sense. I'm afraid the workaround here would be to allowlist each individual environment variable so the request here, from our end, is whether or not to allow `GPG_AGENT_EXTRA` here.

**Comment by Bo98** [comment]
If there's nothing generic we can do (which I fear there isn't), you could perhaps have a dedicated SSH config file that repo (which you can `Include /some/ssh/config` from the main one if you need it) and have `core.sshCommand "ssh -F /some/ssh/config"` in your git config for the needed taps. If you don't need/want a separate file, you can also alternatively pass any needed options as command args to `ssh` in the git config and set `-F` to `/dev/null`.

**Comment by Bo98** [comment]
It's a `git config` option, but after writing that I've actually realised we have `HOMEBREW_SSH_CONFIG_PATH` already - I've overcomplicated things. See https://docs.brew.sh/Manpage.

**Comment by mkw** [comment]
Thanks -- that sounds exactly what I need; sorry I missed it! I'll report back later today after testing.

**Comment by mkw** [comment]
Using `HOMEBREW_SSH_CONFIG_PATH` to avoid the configuration with the variables works great. Thanks!
