### ISSUE TITLE
Sort `brew upgrade` outdated packages list

### ISSUE THREAD

**Issue by jurajlutter** [Homebrew/brew#13210]
### Provide a detailed description of the proposed feature

The outdated packages list provided by `brew upgrade` coule be sorted by package name.

Example:

```
% brew upgrade
==> Upgrading 59 outdated packages:
imlib2 1.8.1 -> 1.9.0
glib-networking 2.70.1 -> 2.72.0
ffmpeg 5.0 -> 5.0.1
minio-mc 20220317202506 -> 20220416211121
```

could be printed as:

```
% brew upgrade
==> Upgrading 59 outdated packages:
ffmpeg 5.0 -> 5.0.1
glib-networking 2.70.1 -> 2.72.0
imlib2 1.8.1 -> 1.9.0
minio-mc 20220317202506 -> 20220416211121
```

### What is the motivation for the feature?

The motivation is to have better navigation/visibility into what's being upgraded.

### How will the feature be relevant to at least 90% of Homebrew users?

Everyone interested will see better what's going to be upgraded.

### What alternatives to the feature have been considered?

I've considered `brew outdated | sort` (that also implies `-q`).

**Comment by MikeMcQuaid** [comment]
These are sorted by the order that they will be installed which is intentional and desirable, sorry.
