### ISSUE TITLE
arg for inreplace, :patch

### ISSUE THREAD

**Issue by DesWurstes** [Homebrew/brew#13220]
### Provide a detailed description of the proposed feature

There are `__END__` patches and `inreplace` patches inside the ruby file.

It would be nice to `brew install abc --patchfile ./a.patch` or `brew install abc --inreplace "main.c,int,long int"`

### What is the motivation for the feature?

Inreplace is a great patch tool locally and it would be awesome if I could use it in a way that it stays with updates. Updating formulas manually with inreplace/patches: either breaks formula updates or is annulled with each update.

### How will the feature be relevant to at least 90% of Homebrew users?

It'll definitely make ":patch", "inreplace" testing easier for maintainers and contributors.

### What alternatives to the feature have been considered?

This is already an alternative to ":patch" and ":inreplace"

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this, seems too likely to break things.
