### ISSUE TITLE
Allow `brew cleanup` to be run as root

### ISSUE THREAD

**Issue by dwfreed** [Homebrew/brew#1323]
Some packages which contain daemons that need to start as root create files within their prefix as the root user at runtime.  This later causes issues with cleanup of old versions.  Now that brew is shortly likely to disallow running as root for most things, I'm requesting that cleanup be added to the commands which can always be run as root, so that cleanup of these packages is straightforward.

**Comment by MikeMcQuaid** [comment]
> Some packages

Which ones?

> create files within their prefix as the root user at runtime

This should be considered a packaging bug; they should write to e.g. `var` instead.

**Comment by dwfreed** [comment]
> Which ones?

bind, for example

> This should be considered a packaging bug; they should write to e.g. `var` instead.

In the case of bind, technically it is, it's just writing to `var/run/named/session.key` within its prefix, instead of, say, `/usr/local/var/run/named/session.key` (assuming `/usr/local` install location).

Even then, many daemons are configurable on where they place things, and the user may have configured them to use the opt prefix instead, which would have the same problem.

**Comment by MikeMcQuaid** [comment]
I'm going to pass on this request but we'll definitely accept a PR to fix that behaviour for Bind or any other package.
