### ISSUE TITLE
brew search xxx: curl: (35) SSL certificate problem: Couldn't understand the server certificate format

### ISSUE THREAD

**Issue by ssbarnea** [Homebrew/brew#1324]
`brew search xxx` triggers:
```
curl: (35) SSL certificate problem: Couldn't understand the server certificate format
```

Homebrew 1.0.8 on Mac OS Sierra 11.12
Homebrew/homebrew-core (git revision 9c724; last commit 2016-10-19)
Before reporting I did the usuall update, upgrade, doctor. 
```
ssbarnea@smac  .ssh$ which curl
/usr/bin/curl
ssbarnea@smac  .ssh$ curl --version
curl 7.49.1 (x86_64-apple-darwin16.0) libcurl/7.49.1 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

Details https://gist.github.com/ssbarnea/6f6e2883f857de5fa02cd128086d631d

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by ssbarnea** [comment]
@MikeMcQuaid Thanks, that was really quick! In fact I missed only to report the config in a gist, which I did and added the link in the summary. That's a very clean Mac OS Sierra as I installed it fresh less than a week ago. This should ease debugging the issue.

**Comment by MikeMcQuaid** [comment]
What does `curl github.com/Caskroom/cask/mixxx` show?

**Comment by ssbarnea** [comment]
I think this would be irrelevant because I got this error while doing `brew search limechat` in the first place, I tried xxx only after getting the first error. Still, just to be sure here is
```
curl -v github.com/Caskroom/cask/mixxx
*   Trying 192.30.253.113...
* Connected to github.com (192.30.253.113) port 80 (#0)
> GET /Caskroom/cask/mixxx HTTP/1.1
> Host: github.com
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-length: 0
< Location: https://github.com/Caskroom/cask/mixxx
< Connection: close
<
* Closing connection 0
```
I also tried a a `curl -Lv ... >file` and observed that after the 301 redirect it ends-up on a 404 page. 

Shortly, I was not able to reproduce the same error with `curl` itself. It seems to happen only when doing the brew search. I suspect the error comes from a different url. Is there a way to make brew search more verbose in order to find what causes this error?

**Comment by MikeMcQuaid** [comment]
Not more verbose than the output you're already using, unfortunately.

**Comment by MikeMcQuaid** [comment]
Unfortunately there's nothing we can do on our end if `curl` is failing, sorry 😭

**Comment by larstobi** [comment]
@ssbarnea I'm having the exact same problem. Please let me know if you figure out what's wrong.

**Comment by ssbarnea** [comment]
Maybe it would help to disclose what I discovered. This may happen if you are on a corporate network that has HTTPS filtering. This is possible if your company is installing a root CA certificate on your device. Once this happens it means that they hijack the HTTPS traffic for filtering it.

What happens with Brew is that curl from Mac OS does not use the same certificates as the ones used by the browsers, so it would fail to validate the certificate.

I am wondering if we can reconfigure CURL to use the same certificates as the GUI applications. 

In my case I picked a different workaround, the one to use a split DNS and to trust the corporate DNS only for the company domain(s). This means that internet traffic will go outside the VPN so I will not encounter the same problem.

**Comment by MikeMcQuaid** [comment]
Thanks for sharing @ssbarnea.

**Comment by uchuugaka** [comment]
I STILL see this off and on. Both on corporate and external network and VPN and not. So, is there a canonical answer?

**Comment by MikeMcQuaid** [comment]
@uchuugaka This is not something we can address regardless of the underlying problem. It's extremely likely to be an issue with either your network or local SSL certificates.
