### ISSUE TITLE
Homebrew should not sanitize TERMINFO/TERMINFO_DIRS on macOS

### ISSUE THREAD

**Issue by neersighted** [Homebrew/brew#13248]
### Provide a detailed description of the proposed feature

Homebrew sanitizes the `$TERMINFO` and `$TERMINFO_DIRS` environmental variables on macOS. This prevents Homebrew from using an alternate/supplemental terminfo database that is not at the default location (`~/.terminfo`).

See https://github.com/Homebrew/homebrew-core/pull/94093#issuecomment-1025083168 for some additional background.

### What is the motivation for the feature?

A Homebrew developer suggested easing the pain of outdated terminfo entries in macOS system software by supplementing the system database (e.g. `export TERMINFO_DIRS=":/path/to/supplemental/entries"`) instead of using `~/.terminfo`. This is an improvement because any new terminfo entries doctored to work with the system ncurses will not override the newer entries used by Homebrew ncurses.

### How will the feature be relevant to at least 90% of Homebrew users?

As macOS's curses ossifies further, and tools like alacritty/tmux/kitty ship their own terminfo definitions (or rely on a entry in the upstream terminfo database), this is an increasingly relevant sharp edge. Homebrew supporting a better way to mitigate these issues (and being more well-behaved when it comes to well-known system env variables) would help with this effort.

### What alternatives to the feature have been considered?

Do nothing and suffer from degraded emoji support and confusing errors when relying on `$TERMINFO_DIRS` to mitigate terminfo mismatch.

![image](https://user-images.githubusercontent.com/1049222/166839510-6f7517fa-7d9f-4f1b-bb22-e63430d86b8b.png)

**Comment by carlocab** [comment]
Very much in favour of this, but I know @MikeMcQuaid is generally very sceptical about adding environment variables to our whitelist.

**Comment by Bo98** [comment]
`TERMINFO` should already be allowed, so it should just be `TERMINFO_DIRS` that's missing.

**Comment by carlocab** [comment]
If `TERMINFO` is already allowed then it seems to me that `TERMINFO_DIRS` shouldn't hurt.

**Comment by neersighted** [comment]
Good catch -- this is a very straightforward change then (and I was a little off in my test/grep method, oops). I'll see about creating a PR tomorrow if nobody beats me to it.

**Comment by MikeMcQuaid** [comment]
> If `TERMINFO` is already allowed then it seems to me that `TERMINFO_DIRS` shouldn't hurt.

Fine with me 👍🏻
