### ISSUE TITLE
Allow updating tap with --force-auto-update

### ISSUE THREAD

**Issue by marquiswang** [Homebrew/brew#13246]
### Provide a detailed description of the proposed feature

Current behavior for `brew tap [user/repo] [url]` is to do nothing if the tap was already installed.

I propose changing it so we can update the `--force-auto-update` flag.

```brew tap --force-auto-update [user/repo] [url]``` should add the `force-auto-update` flag for previously installed tap.

Also, a new option ```brew tap --no-force-auto-update [user/repo] [url]``` should remove the `force-auto-update` flag for a previously installed tap.

### What is the motivation for the feature?

Right now, you can install a non-Github tap with `--force-auto-update`, else you don't get auto-updates.

However, if you fail to do that, there is no way to change the tap to be auto-update without removing the tap and re-tapping it entirely. This can be especially annoying if you've installed things from it, since you can't untap without uninstalling everything.

### How will the feature be relevant to at least 90% of Homebrew users?

Probably won't affect 90% of users, since most people don't use non-Github taps. However, anyone who uses `--force-auto-update` probably wants the ability to control it without uninstalling the tap entirely.

### What alternatives to the feature have been considered?

Right now you can work around it by modifying the configuration directly with:

```
git config --file /usr/local/Homebrew/Library/Taps/foo/bar-core/.git/config --add homebrew.forceautoupdate true
```

**Comment by MikeMcQuaid** [comment]
Seems like a good idea! Will review a PR for this.
