### ISSUE TITLE
Add SSHPASS

### ISSUE THREAD

**Issue by dingore** [Homebrew/brew#13254]
### Provide a detailed description of the proposed feature

Add SSHPASS.

### What is the motivation for the feature?

SSHPASS exists for a reason. Is the person who decided this stupidity also afraid of crossing the street? Aren't you afraid of living at all? :)))))).

Add SSH or else don't promote Brew as a professional solution. Or for Linux :))) 
If you don't know how to handle passwords maybe you are not fit for programming/administration.

### How will the feature be relevant to at least 90% of Homebrew users?

If you arrive to install packages from the command line using brew, then you are grown up enough to be trusted to not being stupid with passwords.

### What alternatives to the feature have been considered?

Some situations do not allow creating public keys. Or for quick tests.

**Comment by EricFromCanada** [comment]
@dingore There are other taps which offer formulae that are not in `homebrew/core`.

Please re-read our Code of Conduct and adjust your tone accordingly in future issues.
