### ISSUE TITLE
Search triggers notification asking for keychain access

### ISSUE THREAD

**Issue by OJFord** [Homebrew/brew#1327]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

Every time I run `brew search`, or something that triggers it, I see:
![screen shot 2016-10-19 at 17 05 09](https://cloud.githubusercontent.com/assets/3946014/19527016/70bc83a8-961e-11e6-8ce5-eb8c343f3902.png)

Clicking 'deny' (several times - 15? - as seems to be required) doesn't seem to have any ill-effect, so as you can imagine I'm disinclined to 'always allow' it access (seemingly the only way of making it leave me alone) without at least knowing what's going on.

I'm not even clear what it wants access to - I use a GPG key with Github and 2FA for the web login, so I'm not sure what it wants from the keychain that it thinks will be useful.

**Comment by MikeMcQuaid** [comment]
It's trying to use your GitHub credentials so your rate limit isn't expired by GitHub's API so aggressively. This isn't actually giving Homebrew permissions or not but giving Git's credential handler the right to read your keychain.

**Comment by OJFord** [comment]
> It's trying to use your GitHub credentials so your rate limit isn't expired by GitHub's API 

Does that work with 2FA enabled (and not providing a second factor)?

**Comment by MikeMcQuaid** [comment]
Yes if you've done an HTTPS checkout with a personal access token.

**Comment by theorician** [comment]
That's great. Don't really want it. Can I disable this permanently?

**Comment by MikeMcQuaid** [comment]
@theorician `HOMEBREW_NO_GITHUB_API` will stop anything ever using the GitHub API.
