### ISSUE TITLE
add --cc option for reinstall command

### ISSUE THREAD

**Issue by xlla** [Homebrew/brew#13279]
### Provide a detailed description of the proposed feature

I hope the reinstall command should provide an option for using specified compiler, like this

`brew reinstall abc --cc llvm_clang`

### What is the motivation for the feature?

I have installed some packages using

`brew install abc --cc llvm_clang`

and later I want to reinstall them for some reason

` brew reinstall abc --cc llvm_clang`

it raise errors:
<pre>
Error: invalid option: --cc
</pre>

if I use 
` brew reinstall abc `

it will execute, but does not build using llvm_clang.

### How will the feature be relevant to at least 90% of Homebrew users?

Maybe I can use 
`brew uninstall abc `

and use

`brew install abc --cc llvm_clang`

again, but if there are many installed packages were depends on abc,  it is not convenient.

### What alternatives to the feature have been considered?

none

**Comment by MikeMcQuaid** [comment]
Passing on this, this is not a flag we wish to support any more than we are.
