### ISSUE TITLE
FIX do not overwrite common apps across system = Linuxbrew should append instead of prepend $PATH to bin dir #12677++

### ISSUE THREAD

**Issue by allanlaal** [Homebrew/brew#13281]
### `brew config` output

```shell
allan@L4:~$ brew config
HOMEBREW_VERSION: 3.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e3d8883cde265cbc16ff94b49a3ac14137590e
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6685b8c19702d32c5afa90f15972ebd363777adf
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: :0.0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 14.0.0
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.17.2-051702-generic x86_64 GNU/Linux
OS: Ubuntu 22.04 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.2.0
/usr/bin/ruby: 3.0.2
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
brew doctor
allan@L4:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/gtk-layer-shell/gtk-layer-shell.h
allan@L4:~$
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

duplicate of #12677 because of #13280
might be linked to #13170

note: those warnings do not affect this behaviour

I am running a normal Ubuntu Linux 22.04 system, but brew overwrites non brew installed binaries:

included in `.bashrc`:

	eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

which in this case is:

	  export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
	  export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
	  export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
	  export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}";
	  export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
	  export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}";

### What happened (include all command output)?

	  allan@L4:~$ which zip
	  /home/linuxbrew/.linuxbrew/bin/zip
	  
	  allan@L4:~$ whereis zip
	  zip: /usr/bin/zip /home/linuxbrew/.linuxbrew/bin/zip /usr/share/man/man1/zip.1.gz

### What did you expect to happen?

I expect `zip` to be the more universal `/usr/bin/zip`

like in #12677 I would also suggest the brew binary dirs should be appended to `$PATH`, so it wouldn't wreck my bash terminals :)

my goal of including `brew shellenv` in my `.bashrc` is so that I would have access to brew installed custom apps
 
I can't think of any use case where one would want their entire distro overwritten:

	  allan@L4:~$ l /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/sbin | wc -l
	  718

Aren't brew apps run in their own env that uses its own versions of common bins? 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
see above
```

**Comment by Bo98** [comment]
This is largely personal preference. The default behaviour of shellenv is unlikely to change because there are equally a number of people who want that behaviour. Some people install Homebrew for the very reason of wanting to use newer packages than what the system ships, or in some cases because they can't modify what the system ships.

**Comment by MikeMcQuaid** [comment]
Sorry, not interested in changing the default behaviour here. As @Bo98 mentioned this is personal preference that you can handle yourself and ignore the `brew doctor` complaints.

**Comment by Natr1x** [comment]
I very much question the decision of overriding system applications by default.

The kind of person who wants to use brew for everything is also likely to be the kind of person who have no trouble configuring brew themselves. Wheras someone who uses it for some one-of applications is probably less likely to know how/want to configure them.

I know at least I personally was very confused to no longer have man pages for the binutils.

**Comment by Natr1x** [comment]
> > I know at least I personally was very confused to no longer have man pages for the binutils.
> 
> That's a bug rather than anything here.
> 
> `brew shellenv` does _not_ hide system manpages, but it looks like you might actually have Homebrew's binutils installed and it appears that unintentionally contains empty manpages. I'll get them fixed or removed.

Well that would be nice of you, I was not entirely certain who was responsible for the package so I did not really know where I was supposed to submit an issue. Though admittedly I haven't exactly looked very hard. 

It was more an example of how someone who did not plan on replacing apt may find `brew shellenv`'s current defaults to be more confusing than it would be for someone who did plan on replacing apt if they were changed.

**Comment by MikeMcQuaid** [comment]
> I very much question the decision of overriding system applications by default.
> 
> The kind of person who wants to use brew for everything is also likely to be the kind of person who have no trouble configuring brew themselves.

If these people have no trouble configuring brew themselves: they can decide to put brew at the end of their PATH.

**Comment by allanlaal** [comment]
@MikeMcQuaid if I add an extra command flag (to https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/shellenv.sh#L13 ) for us weird people preferring our own Distros, will you accept the PR? :)

**Comment by allanlaal** [comment]
to be fair, it took me ≥1year to figure out whats going on, so would've been awesome if brew installer would've asked me if I want brew to be my secondary or primary almost-distro-like-package-provider

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid if I add an extra command flag (to https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/shellenv.sh#L13 ) for us weird people preferring our own Distros, will you accept the PR? :)

No. Just set your PATH yourself rather than using `brew shellenv` if that's what you want.
