### ISSUE TITLE
Versions policy: specify how/if to migrate from unversioned to versioned formula

### ISSUE THREAD

**Issue by fulldecent** [Homebrew/brew#13330]
*This issue regards our documentation and policies at https://github.com/Homebrew/brew/blob/master/docs/Versions.md.*

I hope we can add a policy to address this specific question:

> If an unversioned formula is tracking a specific (old) major version of upstream then what should we do?

Here is concrete discussion on one such instance: https://github.com/Homebrew/homebrew-core/pull/102250. Regardless of the resolution there, this policy could be clarified in our documentation/policy.

---

Pinging contributors to that file for the related points: @MikeMcQuaid @SMillerDev @EricFromCanada @gromgit @jonchang

**Comment by carlocab** [comment]
Our issue tracker is for bugs and feature requests (or, more generally, tracking work to be done).

This belongs in the [discussions page](https://github.com/orgs/Homebrew/discussions). Please post there if you'd like to continue this.
