### ISSUE TITLE
Formula "rust" is outdated

### ISSUE THREAD

**Issue by FineFindus** [Homebrew/brew#13341]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.11-147-g6188f15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6188f15bbd88ce06181609bbd987f92f0233d968
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9c05f291595f3050b34b71a60673a55483d9626d
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit skylake
Clang: N/A
Git: 2.32.0 => /bin/git
Curl: 7.74.0 => /bin/curl
Kernel: Linux 5.13.0-44-generic x86_64 GNU/Linux
OS: Ubuntu 21.10 (impish)
Host glibc: 2.34
/usr/bin/gcc: 11.2.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

When installing a rust project, that requires a newer rust version, `brew install` fails, since the provided rust version is 1.59.0 The currently newest rust version is 1.61.0.

### What happened (include all command output)?

Install rust with 
`brew install rust`
The check the rust version with `rustc -V`, which returns `rustc 1.59.0`

### What did you expect to happen?

A newer rust version should be install, which should return
`rustc 1.61.0 (fe5b13d68 2022-05-18)`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install rust
rustc -V
```

**Comment by carlocab** [comment]
In progress at https://github.com/Homebrew/homebrew-core/pull/98823.

Please feel free to continue discussion there.
