### ISSUE TITLE
Bug report: `brew style` error: undefined method 'activate_bin_path'

### ISSUE THREAD

**Issue by pkq** [Homebrew/brew#1336]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

On a fresh install of ruby 2.3.1, running `brew style` installs `rubocop-0.43.0` and works as expected. However, when I run  it after running `gem update rubocop`, which installs `rubocop-0.44.1`, I get an `undefined method` error message:

`brew style 
/Users/pkennedy/.rvm/gems/ruby-2.3.1/bin/rubocop:22:in '<main>': undefined method 'activate_bin_path' for Gem:Module (NoMethodError) from /Users/pkennedy/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in 'eval' from /Users/pkennedy/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in '<main>' Error: style check failed`

Originally filed at [caskroom/homebrew-cask](https://github.com/caskroom/homebrew-cask/issues/24725), but the issue does not appear to be cask-specific. Thanks!

**Comment by MikeMcQuaid** [comment]
What happens if you run it outside RVM? It's likely RVM is setting variables that break our setup. We'd accept a pull request to fix that.

**Comment by pkq** [comment]
I got the same error using the system ruby, but was able to resolve it using `gem pristine rubocop`. Thanks!
