### ISSUE TITLE
uninstall should optionally autoremove dependencies

### ISSUE THREAD

**Issue by rhwood** [Homebrew/brew#13362]
### Provide a detailed description of the proposed feature

`uninstall` should automatically run `autoremove` if the environment variable `HOMEBREW_UNINSTALL_AUTOREMOVE ` is set (👋🏻 edited to flip default by @MikeMcQuaid)

### What is the motivation for the feature?

Generally, the less that is installed on a system the better. This implies that packages not explicitly installed by a user should be removed if there are no known installed dependencies.

I found #12625 (and learned about `brew autoremove`) while wondering why this wasn't the default behavior or an option for `brew uninstall`, and saw that #12625 was simply closed without consideration given to changing how `uninstall` works, so I don't think I am the only person who thinks this would be useful.

### How will the feature be relevant to at least 90% of Homebrew users?

It will keep their systems clean.

### What alternatives to the feature have been considered?

None.

**Comment by Bo98** [comment]
> why this wasn't the default behavior

The least destructive option is usually the best default. It's not unreasonable for someone to have installed something but have in the meantime made use of a dependency that happened to install.

We could improve signposting here, but changing the default will likely be too disruptive of a change.

**Comment by rhwood** [comment]
For anyone else who stumbles on this, the proposed behavior matches that of [dnf](https://dnf.readthedocs.io/en/latest/command_ref.html#remove-command), but not that of apt.

**Comment by MikeMcQuaid** [comment]
I feel like something we would consider accepting is a `HOMEBREW_UNINSTALL_AUTOREMOVE` variable that automatically autoremoves on uninstall. I'd personally set that and if we go e.g. a year without seeing people reporting false positive removals: we could consider changing the default.

**Comment by carlocab** [comment]
> I feel like something we would consider accepting is a `HOMEBREW_UNINSTALL_AUTOREMOVE` variable that automatically autoremoves on uninstall. I'd personally set that and if we go e.g. a year without seeing people reporting false positive removals: we could consider changing the default.

Fine with this as long as we retain an opt-out if/when we change the default.
