### ISSUE TITLE
auto update did not update tap

### ISSUE THREAD

**Issue by javian** [Homebrew/brew#1337]
Yesterday I wanted to update brew after not touching it for a couple of days and ran into the following

https://gist.github.com/javian/bb7499bd177abac4addc325a043e7abb

The php tap had not been updated after the brew upgrade command when autoupdate was executed but other taps seems to have been updated in that process. After issuing `brew update` it found the outdated php tap and updated it accordingly.

The last commit to the php tap was done on the 19th so it wasn't a timing issue as far as I could tell and it looked like it should have been caught in the update together with the other taps. Would you have an idea why this would happen ?

```
➜  homebrew-php git:(master) brew --version
Homebrew 1.0.8-41-g5b421b9
Homebrew/homebrew-core (git revision 3e380; last commit 2016-10-20)
```

**Comment by MikeMcQuaid** [comment]
Are you sure it didn't check out an older branch? This could have been related to GitHub's downtime. Not sure there's anything we can do if it's not reproducible.

**Comment by javian** [comment]
Yeah it might be difficult to reproduce but it might be possible. It just happened again.

https://gist.github.com/javian/0cc29c5848c52d7f73866f8948c94c25

these 2 commands were now run in succession so its unlikely there is a timing issue. If the intended behaviour of `brew upgrade` is to run update it seems odd that some taps would not be updated. Is there anything I can do next time to capture before and after state to help with the troubleshooting ?

**Comment by MikeMcQuaid** [comment]
In that case it's intentional; auto-update only updates taps with formulae.
