### ISSUE TITLE
Support `bat` environment variables besides `BAT_CONFIG_PATH`

### ISSUE THREAD

**Issue by kidonng** [Homebrew/brew#13383]
### Provide a detailed description of the proposed feature

Provides `HOMEBREW_*` counterparts for [other environment variables used by `bat`](https://github.com/sharkdp/bat/blob/ed4997c77c24a83d9a3724a96dad8534cc4631b4/tests/syntax-tests/create_highlighted_versions.py#L44-L51) besides the current `BAT_CONFIG_PATH` (via [`HOMEBREW_BAT_CONFIG_PATH`](https://docs.brew.sh/Manpage#environment:~:text=HOMEBREW_BAT_CONFIG_PATH)):

- `BAT_CACHE_PATH`
- `BAT_CONFIG_DIR`
- `BAT_OPTS`
- `BAT_PAGER`
- `BAT_STYLE`
- `BAT_TABS`
- `BAT_THEME`

These are a handful so alternatively just add support for `BAT_THEME` which is the one I care about.

Or even, Homebrew can skip filtering any `BAT_*` environment variables, though I guess that is not appealing.

### What is the motivation for the feature?

I'm specifying the theme used by `bat` via `BAT_THEME` which will also picked up by other programs like [`delta`](https://github.com/dandavison/delta). But Homebrew filters it and `bat` falls back to the default which looks awful with a light terminal background:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/44045911/172057976-f2148b88-2209-4520-835e-0a2c67066678.png">

### How will the feature be relevant to at least 90% of Homebrew users?

Well, I bet at least 90% of Homebrew users doesn't enable `HOMEBREW_BAT`, but that doesn't mean it is not useful.

### What alternatives to the feature have been considered?

- Pipe `brew cat` to `bat --language ruby` myself. This is what I do when I didn't learn about `HOMEBREW_BAT`.
- Provide dedicated config file to specify the theme via `HOMEBREW_BAT_CONFIG_PATH`.
- ~~Abuse `HOMEBREW_NO_ENV_FILTERING`~~

**Comment by MikeMcQuaid** [comment]
> These are a handful so alternatively just add support for `BAT_THEME` which is the one I care about.

Will review a PR for this specifically if it's what you care about. Need to edit `bin/brew` to make it get copied to `HOMEBREW_BAT_THEME` (https://github.com/Homebrew/brew/blob/6b3eb93010cdc8b64bd14131e83f27e4171236dd/bin/brew#L78) and then set it like `BAT_CONFIG_PATH` is: https://github.com/Homebrew/brew/blob/6b3eb93010cdc8b64bd14131e83f27e4171236dd/Library/Homebrew/dev-cmd/cat.rb#L34
