### ISSUE TITLE
Failed to install homebrew on Mojave due to SSL certificate problem: unsupported or invalid name syntax

### ISSUE THREAD

**Issue by alekhyageddam** [Homebrew/brew#13394]
### Provide a detailed description of the proposed feature

Trying to install homebrew using bin/bash via the following command on MacOS Mojave:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Repeatedly running into the same error down below:

<img width="864" alt="Screen Shot 2022-06-07 at 9 39 48 PM" src="https://user-images.githubusercontent.com/22627921/172519511-0c163730-52fb-4e87-a27b-7c16da93a5ea.png">
 

### What is the motivation for the feature?

Figure out a way to navigate and resolve the SSL certificate issue; add remediation steps.

### How will the feature be relevant to at least 90% of Homebrew users?

Helps with triaging a specific SSL issue due to unsupported or invalid name syntax

### What alternatives to the feature have been considered?

TBD

**Comment by Bo98** [comment]
This doesn't look like a feature request. If you're instead looking for help, you can ask questions over [at the discussions](https://github.com/orgs/Homebrew/discussions).

I've never seen this error before. My guess is there is something on your network or your system that's interfering with git connections to GitHub.
