### ISSUE TITLE
brew livecheck --ignore-skipped

### ISSUE THREAD

**Issue by davidchall** [Homebrew/brew#13395]
### Provide a detailed description of the proposed feature

Add an `--ignore-skipped` option to the `brew livecheck` command. This will filter out formulae whose livecheck is skipped.

### What is the motivation for the feature?

I want to output formulae with new versions available, but ignoring expected failures (i.e., skipped livecheck). This would be achieved using `brew livecheck --newer-only --ignore-skipped --tap davidchall/hep`.

### How will the feature be relevant to at least 90% of Homebrew users?

I don't know how to answer this. Probably only `brew install` is relevant to 90% of users.

### What alternatives to the feature have been considered?

`brew livecheck` already has a `--quiet` option that suppresses formulae with a skipped livecheck. But`--quiet` also suppresses warnings (e.g., unable to get versions). The motivation of the proposed `--ignore-skipped` option is to separate expected warnings (i.e., skipped livecheck) from unexpected warnings.

**Comment by MikeMcQuaid** [comment]
CC @samford for thoughts

**Comment by davidchall** [comment]
@samford - that work perfectly (in fact, I prefer your suggestion because I don’t need to change my code 😄)

**Comment by samford** [comment]
#13397 should resolve this, if you would like to try it out.

**Comment by davidchall** [comment]
Hi @samford - thank you for such a fast PR! I'm happy to try it out, but could you please give me advice on how to checkout your branch? (I'm not actually sure where the "brew" git repo lives on my machine when homebrew is installed).

**Comment by carlocab** [comment]
You can find the location of the brew repository at
```
brew --repository
```
Don't forget to switch your branch back when you're done. `brew` does not do that for you automatically.

**Comment by davidchall** [comment]
I've confirmed this branch is working as I expected. Thanks again for working on this feature!
