### ISSUE TITLE
doctor export PATH suggestion

### ISSUE THREAD

**Issue by collinhaines** [Homebrew/brew#1340]
When using `brew doctor` and not having `/usr/local/sbin` part of the `PATH`, a suggestion comes up as `echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile`. On the latest release of macOS, this causes `PATH` to implode, meaning I could no longer do commands such as `ls`, `vi`, or even `brew`.

[Possible Problem Source](https://github.com/Homebrew/brew/blob/bbed7246bc5c5b7acb8c1d427d10b43e090dfd39/Library/Homebrew/utils/shell.rb#L86)

Removing the quotations in `.bash_profile` to make `export PATH=/usr/local/sbin:$PATH` fixed everything. This may be a full solution, however, I'm unable to test it in other environments.

**Comment by MikeMcQuaid** [comment]
`echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile` is correct. If you manually add `'export PATH="/usr/local/sbin:$PATH"'` or do `echo export PATH="/usr/local/sbin:$PATH" >> ~/.bash_profile` they will fail as the quoting is not correct.
