### ISSUE TITLE
brew-audit reports conflicting failures for url verification

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/brew#13415]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: fba051f98f609634ae4392d0053ddfc627f8cdb3
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b2f0485ab0d35be6577232021a524f4df8831bb4
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /usr/local/cache/Homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.0wQPKPoQ8Y/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.36.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Attempting to run brew test-bot on a cask tap.

### What happened (include all command output)?

Given a cask with:
```
  url "https://download.visualstudio.microsoft.com/download/pr/#{version.csv.second}/#{version.csv.third}/dotnet-sdk-#{version.csv.first}-osx-#{arch}.pkg"
  homepage "https://microsoft.com/net/core#macos"
```

When `brew test-bot --only-tap-syntax` on ubuntu-latest

Then

```
Run brew test-bot --only-tap-syntax
  brew test-bot --only-tap-syntax
  shell: /usr/bin/bash -e {0}
==>Using Homebrew/homebrew-test-bot dbfd4e1 (Merge pull request #806 from Homebrew/no_bottle_disabled)
==>Using Homebrew/brew 3.5.2 (Merge pull request #13413 from MikeMcQuaid/update_report_new)
==>Using Homebrew/homebrew-core a98cbb1c7c4 (nmap: update 7.92 bottle.)
==>Testing jasonkarns/homebrew-homebrew 5c814f4 (Merge 217b566370c7ba8db30ec463b5ca4b375d3def1e into 3567b74dd80fa33b4e21d3e72cfc5c22638e48b0):
==>Running TapSyntax#run!
==>brew readall --aliases jasonkarns/homebrew
==>brew style jasonkarns/homebrew
==>brew audit --tap=jasonkarns/homebrew --except=version
==>FAILED
Full audit --tap=jasonkarns/homebrew --except=version output
  audit for dotnet-sdk: failed
  - The URL's domain download.visualstudio.microsoft.com does not match the homepage domain microsoft.com, a 'verified' parameter has to be added to the 'url' stanza. See https://docs.brew.sh/Cask-Cookbook#when-url-and-homepage-domains-differ-add-verified
  Error: The URL's domain download.visualstudio.microsoft.com does not match the homepage domain microsoft.com, a 'verified' parameter has to be added to the 'url' stanza. See https://docs.brew.sh/Cask-Cookbook#when-url-and-homepage-domains-differ-add-verified
  Error: 1 problem in 1 cask detected
Error: 1 failed step!
brew audit --tap=jasonkarns/homebrew --except=version
Error: Process completed with exit code 1.
```

Action run: https://github.com/jasonkarns/homebrew-homebrew/runs/6864273309?check_suite_focus=true

Conversely, when `verified` is _added_ as per required by the linter on ubuntu, then I get a lint error on macOS that says the verification is unnecessary.

Given a cask with:
```
  url "https://download.visualstudio.microsoft.com/download/pr/#{version.csv.second}/#{version.csv.third}/dotnet-sdk-#{version.csv.first}-osx-#{arch}.pkg",
      verified: "download.visualstudio.microsoft.com"
  homepage "https://microsoft.com/net/core#macos"
```

When `brew test-bot --only-tap-syntax` on macos-latest

Then 

```
Run brew test-bot --only-tap-syntax
  brew test-bot --only-tap-syntax
  shell: /bin/bash -e {0}
  
==>Using Homebrew/homebrew-test-bot dbfd4e1 (Merge pull request #806 from Homebrew/no_bottle_disabled)
==>Using Homebrew/brew 3.5.2 (Merge pull request #13413 from MikeMcQuaid/update_report_new)
==>Using Homebrew/homebrew-core a98cbb1c7c4 (nmap: update 7.92 bottle.)
==>Testing jasonkarns/homebrew-homebrew 4454074 (Merge eac2aeb733c27e3cb21509420888d41830c60bb9 into 3567b74dd80fa33b4e21d3e72cfc5c22638e48b0):
==>Running TapSyntax#run!
==>brew readall --aliases jasonkarns/homebrew
==>brew style jasonkarns/homebrew
==>brew audit --tap=jasonkarns/homebrew --except=version
==>FAILED
Full audit --tap=jasonkarns/homebrew --except=version output
  audit for dotnet-sdk: failed
  - The URL's domain download.visualstudio.microsoft.com matches the homepage domain microsoft.com, the 'verified' parameter of the 'url' stanza is unnecessary. See https://docs.brew.sh/Cask-Cookbook#when-url-and-homepage-domains-differ-add-verified
  Error: 1 problem in 1 cask detected
  Error: The URL's domain download.visualstudio.microsoft.com matches the homepage domain microsoft.com, the 'verified' parameter of the 'url' stanza is unnecessary. See https://docs.brew.sh/Cask-Cookbook#when-url-and-homepage-domains-differ-add-verified
  
Error: 1 failed step!
brew audit --tap=jasonkarns/homebrew --except=version
Error: Process completed with exit code 1.
```

Action run: https://github.com/jasonkarns/homebrew-homebrew/actions/runs/2489444965

ie, with the :verified option present, the linter passes on ubuntu but fails on macos. When the option is omitted, it fails on ubuntu (github actions cancels the macos run as soon as the ubuntu run fails, so it's unclear if the macos job _would_ pass. however, `brew audit ./Casks/dotnet-sdk.rb --except=version` does pass locally on macos without the verified option present)

### What did you expect to happen?

I'd expect the linter to produce consistent results given the same cask code across both ubuntu and macos.

### Step-by-step reproduction instructions (by running `brew` commands)

`brew audit ./Casks/dotnet-sdk.rb --except=version` across both ubuntu and macos. Pointing to the cask at: https://github.com/jasonkarns/homebrew-homebrew/blob/eac2aeb733c27e3cb21509420888d41830c60bb9/Casks/dotnet-sdk.rb

**Comment by MikeMcQuaid** [comment]
CC @homebrew/cask folks for thoughts/help.

**Comment by MikeMcQuaid** [comment]
CC @Homebrew/cask again and also @bevanjkay @apainintheneck @samford as I have no idea how this should work. Replying with "I also have no idea" would be helpful, thanks ❤️

**Comment by SMillerDev** [comment]
I have no idea either, although I do know that `brew audit <filename>` is not the same as `brew audit <token>`. So that might explain some issues.

**Comment by carlocab** [comment]
> I'd expect the linter to produce consistent results given the same cask code across both ubuntu and macos.

I agree with this. Unfortunately, I also don't understand why it isn't giving the same results currently. Sorry 😢

**Comment by carlocab** [comment]
> I have no idea either, although I do know that `brew audit <filename>` is not the same as `brew audit <token>`. So that might explain some issues.

Ah, yes.

> ```
> brew audit ./Casks/dotnet-sdk.rb --except=version
> ```

is incorrect usage of of `brew audit` and will produce garbage. I wish we handled that garbage production better, though (e.g. documenting that `brew` doesn't take file name arguments, and behaving less misleadingly when file names are passed).

**Comment by cho-m** [comment]
Taking a look at Tap, I think Cask was https://github.com/jasonkarns/homebrew-homebrew/blob/cb497ca65807e5310652da7f736711e9e99bfe80/Casks/dotnet-sdk.rb, which seems to have mix of `version` syntax from older copy of core Cask with `url` from newer copy.

`version.csv.second` would include a colon character followed by number when `MacOS.version <= :sierra` (inclusive of Linux). This gets incorrectly parsed as port number resulting in domain of `microsoft.com:1076952734`:
https://github.com/Homebrew/brew/blob/b4619fe2dbe26cc14294049574358e92a5bb6dc8/Library/Homebrew/cask/audit.rb#L384

Since macOS runners would be running newer OS than Sierra, they use other `version`, which has character hex and isn't seen as a port number.

**Comment by MikeMcQuaid** [comment]
> > ```
> > brew audit ./Casks/dotnet-sdk.rb --except=version
> > ```
> 
> 
> is incorrect usage of of `brew audit` and will produce garbage. I wish we handled that garbage production better, though (e.g. documenting that `brew` doesn't take file name arguments, and behaving less misleadingly when file names are passed).

@carlocab Should we just fail `brew audit` if you pass a filename? Does this work ok when passed a folder name? Does this work ok for formulae?



> Not sure if we need to change anything as the particular Cask seems to have been broken in current state and `:` is a reserved character in URL encoding. If really wanted, then can add a more specific URL regex.

@cho-m Thanks for digging in. Will consider this as WONTFIX but keep it open for now to discuss the `brew audit $FILENAME` stuff above.
