### ISSUE TITLE
Update to node-based formula withgraphite/tap/graphite resulted in permanent failure to install

### ISSUE THREAD

**Issue by goldjacobe** [Homebrew/brew#13418]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: fba051f98f609634ae4392d0053ddfc627f8cdb3
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 736e1b112a48d77482fe6dc88ce2e023fb594f41
Core tap last commit: 29 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I have just released a new version of `withgraphite/tap/graphite` to brew, and I am trying to install it on my own machine to test that it works as expected for our users. 

### What happened (include all command output)?

Upon testing installation, we found that `brew install withgraphite/tap/graphite` consistently throws (across multiple machines):
`RuntimeError: npm failed to pack`

### What did you expect to happen?

Expected the package to be installed with no error, as with prior versions.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install withgraphite/tap/graphite
```

**Comment by goldjacobe** [comment]
Hey @MikeMcQuaid and @Bo98 ! Our users are still seeing this for our v0.19.0 version that has prepack and postpack scripts.  I'm planning on removing our husky precommit hook that requires having these scripts for v0.19.1 as a workaround — just letting you know that the bug seems still present.

**Comment by Bo98** [comment]
Probably because it's not in a release yet. I could look at tagging a 3.5.3 with this included.
