### ISSUE TITLE
Error: comparison of NilClass with String failed @ 3.5.2 (d23dba67c)

### ISSUE THREAD

**Issue by xerc** [Homebrew/brew#13435]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.2-53-gd23dba6
ORIGIN: https://github.com/Homebrew/brew
HEAD: d23dba67ca70e019a400e1ba421b4f61092bb705
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d6384e413b6ecca857a41cb9b05d3cc74d727fc1
Core tap last commit: 67 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.6cJkQ99AKZ/org.macosforge.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.36.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
```

### `brew doctor` output

```shell
Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  protobuf@3.7
  unrar
  szip

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  curlftpfs
  ilmbase
  php@7.4

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  httpd
  subversion

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install openssl@3
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

$ brew install rustdesk

### What happened (include all command output)?

Running `brew update --auto-update`...
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
==> Auto-updated Homebrew!
Updated Homebrew from 3.5.1 (b75f41c52) to 3.5.2 (d23dba67c).
Updated 9 taps (shopify/shopify, homebrew/cask-versions, homebrew/core, homebrew/cask, homebrew/bundle, homebrew/cask-fonts, homebrew/services, stek29/idevice and blacktop/tap).
Error: comparison of NilClass with String failed
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:697:in 'sort'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:697:in 'output_dump_formula_or_cask_report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:615:in 'dump_new_formula_report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:545:in 'dump'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:203:in 'output_update_report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:42:in 'update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in '>main<'
==> Downloading https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/299354207/3331b92d-a9ce-4ae2-9d61-e1c39c4c5e6f?X-A
######################################################################## 100.0%
==> Installing Cask rustdesk
==> Moving App 'RustDesk.app' to '/Applications/RustDesk.app'
🍺  rustdesk was successfully installed!

### What did you expect to happen?

not telling me to report a bug ?!

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install rustdesk
Please report this issue: [..]

open github, fill out all forms
ignoring "Verification" => SUBMIT

checking installed app ; works!
```

**Comment by Bo98** [comment]
Fixed, thanks!
