### ISSUE TITLE
first install on centos, "brew install hello", brew download too much formula

### ISSUE THREAD

**Issue by Kurt-Shiwz** [Homebrew/brew#13448]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.2-109-g9416032
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9416032ee5d253fc00419f111373af54e1c6bc5d
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d2e9ba93390ec2d26de8ae21afc3a2f2070c34b9
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 3.4.2 build 34
Git: 2.31.1 => /bin/git
Curl: 7.76.0 => /bin/curl
Kernel: Linux 3.10.0-1127.13.1.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.9.2009 (Core) (Core)
Host glibc: 2.18
/usr/bin/gcc: 4.8.5
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /root/anaconda3/bin/freetype-config
  /root/anaconda3/bin/xml2-config
  /root/anaconda3/bin/libpng16-config
  /root/anaconda3/bin/python3.7-config
  /root/anaconda3/bin/python3.7m-config
  /root/anaconda3/bin/ncursesw6-config
  /root/anaconda3/bin/pcre-config
  /root/anaconda3/bin/python3-config
  /root/anaconda3/bin/xslt-config
  /root/anaconda3/bin/libpng-config
  /root/anaconda3/bin/icu-config
  /root/anaconda3/bin/curl-config

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
   D Formula/xmrig.rb
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install hello

### What happened (include all command output)?

brew update --auto-update
==> Downloading https://ghcr.io/v2/homebrew/core/m4/manifests/1.4.19
Already downloaded: /home/username/.cache/Homebrew/downloads/5b2a7f715487b7377e409e8ca58569040cd89f33859f691210c58d94410fd33b--m4-1.4.19.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:f6d1087a51e0ff2e582b3043a25a51b67971b2246cf65167ef3abf1230160f04
Already downloaded: /home/username/.cache/Homebrew/downloads/c3563955b8307af0d683e3987968573fde3f24bb8e49cbb129aa975f064b0d6c--m4--1.4.19.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/gmp/manifests/6.2.1_1
Already downloaded: /home/username/.cache/Homebrew/downloads/a1986a80dafb4e42b8372268a00d8d14aa8294154c876ba82e7ce48db06885cb--gmp-6.2.1_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gmp/blobs/sha256:786ae29f0c0b06ea86e42bd9c6ac2c49bd5757da037dead7053e8bd612c4cf8c
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:786ae29f0c0b06ea86e42bd9c6ac2c49bd5757da037dead7053e8bd612c4cf8c?se=2022-06-20T07%3A05%3A00Z&sig=a1AJErd8h0Pg4L1q0Sf9NAHwYbDBwCaS215VZ34Ul1k%3D&sp=r&spr=
######################################################################## 100.0%
Warning: isl@0.18 has been deprecated because it is a versioned formula!
==> Downloading https://ghcr.io/v2/homebrew/core/isl/0.18/manifests/0.18
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/isl/0.18/blobs/sha256:7d90ca0810ac78ac9357f86cf245ec9dfdc7c2171646d4993972d36c1b84e35b
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:7d90ca0810ac78ac9357f86cf245ec9dfdc7c2171646d4993972d36c1b84e35b?se=2022-06-20T07%3A05%3A00Z&sig=Nj9t9mBsVpIAN8WgtLHlOeW4FkaLSzhXa30ehkDy%2Bao%3D&sp=r&sp
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/manifests/4.1.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/blobs/sha256:4c5f1cfd038e8fbd640795e34e5e23c11244be3eca7781979600ec0d50bb9c0b
......
......
......

### What did you expect to happen?

just install hello

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install hello
```

**Comment by Kurt-Shiwz** [comment]
> ```
> Host glibc: 2.18
> /usr/bin/gcc: 4.8.5
> ```
> 
> Your host `glibc` and `gcc` is too old, so `brew` needs to install `glibc` and `gcc@5` to function.


Requirements  in https://docs.brew.sh/Homebrew-on-Linux
```
GCC 4.7.0 or newer
Linux 2.6.32 or newer
Glibc 2.13 or newer
64-bit x86_64 CPU
```

**Comment by carlocab** [comment]
Yes, `brew` will work if those requirements are satisfied. But it will need to install additional software to work depending on your version of GCC and Glibc.
