### ISSUE TITLE
Config setting "latesttag" is not getting updated when updating with quiet

### ISSUE THREAD

**Issue by dkav** [Homebrew/brew#13467]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.2-145-gfe853fc
ORIGIN: https://github.com/Homebrew/brew
HEAD: fe853fcb9e57249d62e2381b831a884cfa853f37
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ee49b6e70b9dc16a30340cc371e4dc6a2051f632
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 14
HOMEBREW_EDITOR: /usr/local/bin/mvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_EMOJI: set
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 12.0.0 build 1200
Git: 2.36.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew update --quiet

### What happened (include all command output)?
Updated Homebrew from 3.4.0 (65e077aac) to 3.5.2 (fe853fcb9).
Updated 1 tap (homebrew/core).

==> Homebrew was updated to version 3.5.2
No packages to update

### What did you expect to happen?

Updated Homebrew from 65e077aac to fe853fcb9.
Updated 1 tap (homebrew/core).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update --quiet
```

**Comment by dkav** [comment]
Issue is due to change suggested [here](https://github.com/Homebrew/brew/pull/10868#pullrequestreview-617039607) and can found in [update-report.rb](https://github.com/Homebrew/brew/blob/fe853fcb9e57249d62e2381b831a884cfa853f37/Library/Homebrew/cmd/update-report.rb#L242). If `brew update --quiet` is use all the time and an upgrade to a x.x.0 version is missed brew will fail to update `latesttag` setting.

**Comment by dkav** [comment]
The issue also highlights that checking for x.x.0 versions only means than an updates from, for example, x.2.1 to x.3.1 will not highlight the blog version post.

**Comment by apainintheneck** [comment]
> The issue also highlights that checking for x.x.0 versions only means than an update from, for example, x.2.1 to x.3.1 will not highlight the blog version post.

Sounds like it would make more sense to check if the major or minor version has changed and then display the most recent minor version changelog instead of basing it on the patch version being zero.
