### ISSUE TITLE
GitHub Packages HTTP 401 errors

### ISSUE THREAD

**Issue by nre-ableton** [Homebrew/brew#13460]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: fba051f98f609634ae4392d0053ddfc627f8cdb3
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d1945aece64d3c5bbf47d6251311ebfa79f77c04
Core tap last commit: 76 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.7-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 12.5.1
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/ci/.cache/pyenv/shims/python2-config
  /Users/ci/.cache/pyenv/shims/python3.7-config
  /Users/ci/.cache/pyenv/shims/python2.7-config
  /Users/ci/.cache/pyenv/shims/python3.7m-config
  /Users/ci/.cache/pyenv/shims/python-config
  /Users/ci/.cache/pyenv/shims/python3-config

Warning: Your Xcode (12.5.1) is outdated.
Please update to Xcode 13.2.1 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to install various packages that have a dependency on `ca-certificates` (such as `tmux`).

FWIW, I'm using a Big Sur VM that is part of a build farm with different compiler versions, hence I cannot update Xcode to a more recent version. Likewise, the `pyenv` directories are required for other reasons. I highly doubt that either of these things are the cause of the issue here; it seems to be that https://ghcr.io/v2/homebrew/core/ca-certificates/blobs/sha256:c05a44feba2a630de2e1cefba90d3aa3f74e4d57146c0117858f648c419abeae is simply unauthorized and cannot be downloaded.

### What happened (include all command output)?

```
$ brew install ca-certificates
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/manifests/2022-04-26
Already downloaded: /Users/ci/Library/Caches/Homebrew/downloads/21a4c3d0a8e54b4921528b9379605fac4a683424a7a4cb0a2b5f098e18f3e229--ca-certificates-2022-04-26.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/blobs/sha256:c05a44feba2a630de2e1cefba90d3aa3f74e4d5
#=#=#
curl: (22) The requested URL returned error: 401
Error: ca-certificates: Failed to download resource "ca-certificates"
Download failed: https://ghcr.io/v2/homebrew/core/ca-certificates/blobs/sha256:c05a44feba2a630de2e1cefba90d3aa3f74e4d57146c0117858f648c419abeae
```

### What did you expect to happen?

The package to be installed without problems.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew install ca-certificates`
```

**Comment by vagari** [comment]
I'm in a similar boat... With loads of packages. Ran a `brew upgrade` this morning and pretty much everything that tried to update threw a 401 error. 

After seeing some old references to curl being the problem, switched to the more recent `brew` installed version via `HOMEBREW_FORCE_BREWED_CURL`. Still got the the 401s. Think this might be a larger issue. 

@nre-ableton, are you able to install or upgrade other packages?

**Comment by bvnp43** [comment]
yep, cant install new or update existing packages

**Comment by bigboy1122** [comment]
Same issue, getting 401's on installs

**Comment by ntersol-tom** [comment]
```
$ curl https://ghcr.io/v2/ -i
HTTP/2 401
content-type: application/json
docker-distribution-api-version: registry/2.0
www-authenticate: Bearer realm="https://ghcr.io/token",service="ghcr.io",scope="repository:user/image:pull"
date: Wed, 22 Jun 2022 12:32:07 GMT
content-length: 73
x-github-request-id: D402:3C10:15F27:37308:62B30BC7

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
```

**Comment by nre-ableton** [comment]
Glad to hear it isn't just me. :smile: Thanks for the quick response and investigation @MikeMcQuaid.

**Comment by MikeMcQuaid** [comment]
GitHub's reporting an incident here now: https://www.githubstatus.com/incidents/10vm6ctn52gx

**Comment by MikeMcQuaid** [comment]
Can anyone still reproduce this now? There has been a rollback.

**Comment by yermulnik** [comment]
Can confirm the issue is gone.

**Comment by akougblenou** [comment]
I am still ahving the issue, can't perform a `brew upgrade` or install the `ca-certificate` were there people still stuck on the issue ?
I am going to try a fresh install and see if that fixes it.
