### ISSUE TITLE
All commands hang on running `brew tap`

### ISSUE THREAD

**Issue by treet** [Homebrew/brew#1347]
All commands (brew update, brew install, brew doctor, brew --config) hang on the following command:

```
/usr/local/bin/brew tap homebrew/core -q
```

Running only `brew tap` manually also hangs. The terminal window cycles between running "tr", "bash", "ruby" and "xcode".  I've run `cd "$(brew --repo)" && git fetch && git reset --hard origin/master` and `sudo chown -R $(whoami) $(brew --prefix)` successfully, but the problem still persist.
- Is there a way to get more output on homebrew is actually hanging on? (--verbose doesn't seem to work)
- This is the first time I'm running homebrew in a few months, perhaps something in my system is outdated?

OS X El Capitan 10.11.16
Homebrew 1.0.8-44-gc521ff4

**Comment by MikeMcQuaid** [comment]
When you say they "hang": how long did you leave it?

**Comment by treet** [comment]
'Only' 10 minutes or so, given that I couldn't find any process using any significant amount of CPU. Maybe I'm just too impatient :), I'll start a `brew update` and leave it running for 1+ hour or so right now.

**Comment by MikeMcQuaid** [comment]
Thanks. It's not using much CPU because it's downloading over the network.

**Comment by treet** [comment]
Still running after 1.5h hours I'm afraid, no network or CPU activity. Is there anyway to get more output on what `brew tap` is doing?

**Comment by MikeMcQuaid** [comment]
`/usr/local/bin/brew tap homebrew/core --verbose --debug` may help. It'll be doing a `git clone` most likely.

**Comment by MikeMcQuaid** [comment]
Closing due to no response.

**Comment by treet** [comment]
Sorry for not responding. I just tried again and the problem has disappeared, brew tap and other commands finish instantly. Must have been transient network error or something. Thanks for the help!

**Comment by MikeMcQuaid** [comment]
Glad it's sorted now and no worries.
