### ISSUE TITLE
Newline is missing in "write_env_script" emitted shell scripts

### ISSUE THREAD

**Issue by cpurdy** [Homebrew/brew#13475]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.2-156-gf1d04b4
ORIGIN: https://github.com/Homebrew/brew
HEAD: f1d04b4c3dd194265d59751b90f815714058d19b
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 752c412a771cdfcdb2ff2f57f94f83660cf3af67
Core tap last commit: 51 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

### `brew doctor` output

```shell
homebrew$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  xdk
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to use `write_env_script` with `Language::Java.overridable_java_home_env` to produce a script that would be able to invoke Java. The Java executable is located at `$JAVA_HOME/bin/java`. The `write_env_script` method creates a script that (correctly) hard-codes a default location for `$JAVA_HOME`, so I used that `$JAVA_HOME` variable in the command that I asked `write_env_script` to use in the script it created.

### What happened (include all command output)?

I run `brew test` on a formula, and it creates a shell script, and that shell script fails -- but only in `brew test`, where there is no `$JAVA_HOME` variable!

    homebrew$ brew test xdk
    ==> Testing xdk
    ==> /opt/homebrew/Cellar/xdk/0.4.2/bin/xec -help
    Last 15 lines from /Users/cameron/Library/Logs/Homebrew/xdk/test.01.xec:
    2022-06-25 14:49:37 -0400
    
    /opt/homebrew/Cellar/xdk/0.4.2/bin/xec
    -help
    
    /opt/homebrew/Cellar/xdk/0.4.2/bin/xec: line 2: /bin/java: No such file or directory
    /opt/homebrew/Cellar/xdk/0.4.2/bin/xec: line 2: exec: /bin/java: cannot execute: No such file or directory
    Error: xdk: failed
    An exception occurred within a child process:
      BuildError: Failed executing: /opt/homebrew/Cellar/xdk/0.4.2/bin/xec -help
    /opt/homebrew/Library/Homebrew/formula.rb:2296:in `block in system'
    /opt/homebrew/Library/Homebrew/formula.rb:2232:in `open'
    /opt/homebrew/Library/Homebrew/formula.rb:2232:in `system'
    /opt/homebrew/opt/xdk/.brew/xdk.rb:21:in `block in <class:Xdk>'
    /opt/homebrew/Library/Homebrew/formula.rb:2096:in `block (3 levels) in run_test'
    /opt/homebrew/Library/Homebrew/utils.rb:601:in `with_env'
    /opt/homebrew/Library/Homebrew/formula.rb:2095:in `block (2 levels) in run_test'
    /opt/homebrew/Library/Homebrew/formula.rb:938:in `with_logging'
    /opt/homebrew/Library/Homebrew/formula.rb:2094:in `block in run_test'
    /opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
    /opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
    /opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
    /opt/homebrew/Library/Homebrew/formula.rb:2347:in `mktemp'
    /opt/homebrew/Library/Homebrew/formula.rb:2088:in `run_test'
    /opt/homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
    /opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'

### What did you expect to happen?

I expected `brew test` to work. The shell script emitted by [write_env_script](https://github.com/Homebrew/brew/blob/f1d04b4c3dd194265d59751b90f815714058d19b/Library/Homebrew/extend/pathname.rb#L374) appears at first glance to be correct, in that it **could not possibly** allow $JAVA_HOME to be blank:

    #!/bin/bash
    JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home}" exec "${JAVA_HOME}/bin/java" ... "$@"

(I replaced the args with `...`)

-- details --

(Note that the `brew doctor` result only lists the one formula that I am explicitly building locally from source, in order to show this one issue.)

I have been testing and refining an Homebrew Formula for the past several weeks. At the suggestion of a Homebrew contributor @SMillerDev (thanks for the help 😊), I altered my Formula to use the method `write_env_script`, with `Language::Java.overridable_java_home_env` for the environment.

On my Mac M1, and in the Homebrew CI environment, this produces a 100% reproducible bug. Specifically, the script that is emitted by `path.write_env_script cmd, args, Language::Java.overridable_java_home_env` is:

    #!/bin/bash
    JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home}" exec "cmd" args "$@"

(Note: The `/opt` path is obviously specific to my machine, and `cmd` and `args` are replaced with the values thereof.)

The [code that produces this script](https://github.com/Homebrew/brew/blob/f1d04b4c3dd194265d59751b90f815714058d19b/Library/Homebrew/extend/pathname.rb#L382) is very simple:

    write <<~SH
      #!/bin/bash
      #{env_export}exec "#{target}" #{args} "$@"
    SH

Trying to find a solution to the error that occurs when I `brew test` with this script, I discovered that one tiny manual edit to my local script will fix it:

    #!/bin/bash
    JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home}"
    exec "cmd" args "$@"

That's it. A newline before the "exec" command. When there is no newline, the `exec` does not "see" the $JAVA_HOME value that was set immediately to its "left". When there is a newline, the `exec` **does** pick up the $JAVA_HOME value that was set immediately above it.

I am not yet integrated well enough into this project to know how to successfully change, build, and do a pull request to fix this. My biggest concern is that I would fix it for my own machine and for the various M1 CI instances that are used by the Homebrew project, but I might accidentally break some other environment. After all, it seems like this was quite purposefully munged into a single line, but for what reason I am at a loss to explain.

I think that this is the fix, but I don't know the Ruby SH DSL being used here:

    write <<~SH
      #!/bin/bash
      #{env_export}
      #exec "#{target}" #{args} "$@"
    SH

I wanted to capture what I had found, in hopes that it would save someone else from the tremendous frustration that I have been working through. Please do let me know if there's anything else that I can do to help resolve this.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
#write a formula:
#  1) that uses write_env_script with Language::Java.overridable_java_home_env
#  2) that invokes the $JAVA_HOME/bin/java command in the script

# BEGIN EXAMPLE FORMULA xdk.rb
class Xdk < Formula
  desc "Ecstasy Development Kit (XDK)"
  homepage "https://github.com/xtclang/xvm/"
  url "https://github.com/xtclang/xvm/releases/download/v0.4.2/xdk-0.4.2.tar.gz"
  sha256 "b0b5217abf05de986e6211a7c8665b304fa89df1726749e4f1dd7eff1cbbe1fe"
  license "Apache-2.0"

  depends_on "openjdk"

  def install
    libexec.install buildpath.children
    %w[xec xtc xam].each do |cmd|
      java = "${JAVA_HOME}/bin/java"
      #hack fix: java = "${JAVA_HOME:+$JAVA_HOME/bin/}java"
      args = "-Xms256m -Xmx1024m -ea -jar #{libexec}/javatools/javatools.jar" \
             " #{cmd} -L #{libexec}/lib -L #{libexec}/javatools"
      (bin/cmd).write_env_script java, args, Language::Java.overridable_java_home_env
    end
  end

  test do
    system "#{bin}/xec", "-help"
  end
end
# END EXAMPLE FORMULA


#install the formula
$ brew install --build-from-source ~/Development/homebrew-core/Formula/xdk.rb     
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

You have 3 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Error: Failed to load cask: /Users/cameron/Development/homebrew-core/Formula/xdk.rb
Cask 'xdk' is unreadable: wrong constant name #<Class:0x0000000154a935f8>
Warning: Treating /Users/cameron/Development/homebrew-core/Formula/xdk.rb as a formula.
==> Downloading https://github.com/xtclang/xvm/releases/download/v0.4.2/xdk-0.4.2.tar.gz
Already downloaded: /Users/cameron/Library/Caches/Homebrew/downloads/babd7df05adec94deecb91a3de900860451be0dba2738519c2be5d205d55554a--xdk-0.4.2.tar.gz
🍺  /opt/homebrew/Cellar/xdk/0.4.2: 32 files, 5.6MB, built in 1 second
==> Running `brew cleanup xdk`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).


#check obvious stuff (no problems)
$ brew test xdk
==> Testing xdk
==> /opt/homebrew/Cellar/xdk/0.4.2/bin/xec -help
$ brew audit --strict --online xdk


#use the script (no problems)
$ xec
Error: Module file required


#test the formula (fails)
$ brew test xdk
==> Testing xdk
==> /opt/homebrew/Cellar/xdk/0.4.2/bin/xec -help
Last 15 lines from /Users/cameron/Library/Logs/Homebrew/xdk/test.01.xec:
2022-06-25 14:49:37 -0400

/opt/homebrew/Cellar/xdk/0.4.2/bin/xec
-help

/opt/homebrew/Cellar/xdk/0.4.2/bin/xec: line 2: /bin/java: No such file or directory
/opt/homebrew/Cellar/xdk/0.4.2/bin/xec: line 2: exec: /bin/java: cannot execute: No such file or directory
Error: xdk: failed
An exception occurred within a child process:
  BuildError: Failed executing: /opt/homebrew/Cellar/xdk/0.4.2/bin/xec -help
/opt/homebrew/Library/Homebrew/formula.rb:2296:in `block in system'
/opt/homebrew/Library/Homebrew/formula.rb:2232:in `open'
/opt/homebrew/Library/Homebrew/formula.rb:2232:in `system'
/opt/homebrew/opt/xdk/.brew/xdk.rb:21:in `block in <class:Xdk>'
/opt/homebrew/Library/Homebrew/formula.rb:2096:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/utils.rb:601:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2095:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:938:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2094:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2347:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2088:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'


#edit the script generated by "write_env_script"
#(just adding a new line before the word "exec")
$ vi /opt/homebrew/Cellar/xdk/0.4.2/bin/xec
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home}"
exec "${JAVA_HOME}/bin/java" -Xms256m -Xmx1024m -ea -jar /opt/homebrew/Cellar/xdk/0.4.2/libexec/javatools/javatools.jar xec -L /opt/homebrew/Cellar/xdk/0.4.2/libexec/lib -L /opt/homebrew/Cellar/xdk/0.4.2/libexec/javatools "$@"


#use the script again to make sure we didn't break it (no problems)
$ xec
Error: Module file required


#brew test the script again to make sure we fixed it (no problems)
$ brew test xdk
==> Testing xdk
==> /opt/homebrew/Cellar/xdk/0.4.2/bin/xec -help
```

**Comment by Rylan12** [comment]
You might want to take a look at [`write_jar_script`](https://github.com/Homebrew/brew/blob/f1d04b4c3dd194265d59751b90f815714058d19b/Library/Homebrew/extend/pathname.rb#L409-L416) instead of `write_env_script`.

You can also see [this post](https://unix.stackexchange.com/a/56449/531407) for why the newline is necessary in certain cases.

**Comment by Bo98** [comment]
> That's it. A newline before the "exec" command. When there is no newline, the `exec` does not "see" the $JAVA_HOME value that was set immediately to its "left". When there is a newline, the `exec` **does** pick up the $JAVA_HOME value that was set immediately above it.

If you are referencing it within the same line, that correct. It is however works the opposite way round if the variable is being referenced within whatever is being `exec`ed. If you want it to work for both, you'd also need to `export` the ENV.

Though if you are doing this to invoke a jar, I recommend using `write_jar_script` instead anyway.

**Comment by cpurdy** [comment]
@Rylan12 thank you for the advice; that seems likely to be what I need for this, and based on your advice, that is the path that I am working on.

>If you are referencing it within the same line, that correct. It however works the opposite way round if the variable is being referenced within the separate executable that is being execed. If you want it to work for both, you'd also need to export the ENV.

@Bo98 Wow! Talks about "_I was this many years old when I learned ..._"! I guess am no longer surprised when I learn these little corner cases. Based on your comment, `write_env_script` is _supposed_ to work this way? If that is the case, then this issue is not a bug, but I will take the time (once I get everything working) to come back and add some documentation for the next person who hits this same thing.

**Comment by carlocab** [comment]
> `write_env_script` is _supposed_ to work this way? 

Yes.

> this issue is not a bug

I believe so.

> I will take the time (once I get everything working) to come back and add some documentation for the next person who hits this same thing.

Improvements to documentation are much appreciated.

**Comment by Rylan12** [comment]
It sounds like the issue here is resolved so I'm going to close it, but we'd certainly love any documentation improvements you think would be helpful!
