### ISSUE TITLE
glibtoolize /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory

### ISSUE THREAD

**Issue by lexbi** [Homebrew/brew#1348]
This thread seems to be referencing the issue I am having somewhat: https://github.com/Homebrew/legacy-homebrew/issues/43874

I have tried uninstalling libtool and reinstalling it, but, when running `autoreconf -fiv` on the latest version of `mozjpeg` I get the following:

    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force
    autoreconf: configure.ac: tracing
    autoreconf: running: glibtoolize --copy --force
    /usr/local/bin/glibtoolize: line 406: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    /usr/local/bin/glibtoolize: line 2513: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    /usr/local/bin/glibtoolize: line 2513: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    /usr/local/bin/glibtoolize: line 3601: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    /usr/local/bin/glibtoolize: line 3845: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    /usr/local/bin/glibtoolize: line 861: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    : putting auxiliary files in '.'.
    : copying file './ltmain.sh'
    /usr/local/bin/glibtoolize: line 3771: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
    autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoheader --force
    autoreconf: running: automake --add-missing --copy --force-missing
    configure.ac:16: installing './compile'
    configure.ac:8: installing './missing'
    Makefile.am: installing './depcomp'
    autoreconf: Leaving directory `.'

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by lexbi** [comment]
I am not sure what I have missed? I've followed all the steps that I understand at this point. 

I've done brew update/doctor, I've done the common issues, I've search for existing issues...

I'm not sure I am using a formula here so I don't know if I can provide any more info other than I'm on macOS Sierra 10.12.1

What more do you want from me?

**Comment by MikeMcQuaid** [comment]
> Upload debugging information to a Gist:
> If you had a formula error: run brew gist-logs <formula> (where <formula> is the name of the formula that failed to build).
> If you encountered a non-formula bug: upload the output of brew config and brew doctor to a new Gist.

These steps, please.

**Comment by lexbi** [comment]
Hi Mike,

I didn't mean to sound ungrateful by the way, my final sentence was meant to be in jest, here is the brew config & brew doctor outputs, let me know if you need anything else:

[brew config](https://gist.github.com/lexbi/090f7c8b54144ca973601ef556da45f9)

[brew doctor](https://gist.github.com/lexbi/7d313621b80e847779f82c6d76190bad)

**Comment by MikeMcQuaid** [comment]
Try to `brew reinstall libtool; brew reinstall mozjpeg`. Thanks!

**Comment by lexbi** [comment]
I have already reinstalled libtool, though I have run that line and still get the same output:

    Joes-MacBook-Pro:mozjpeg joepagan$ autoreconf -fiv
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force
    autoreconf: configure.ac: tracing
    autoreconf: running: glibtoolize --copy --force
    /usr/local/bin/glibtoolize: line 406: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    /usr/local/bin/glibtoolize: line 2513: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    /usr/local/bin/glibtoolize: line 2513: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    /usr/local/bin/glibtoolize: line 3601: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    /usr/local/bin/glibtoolize: line 3845: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    /usr/local/bin/glibtoolize: line 861: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    : putting auxiliary files in '.'.
    : copying file './ltmain.sh'
    /usr/local/bin/glibtoolize: line 3771: /usr/local/Cellar/../Library/ENV/4.3/sed: No such file or directory
    autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
    autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoheader --force
    autoreconf: running: automake --add-missing --copy --force-missing
    configure.ac:16: installing './compile'
    configure.ac:8: installing './missing'
    Makefile.am: installing './depcomp'
    autoreconf: Leaving directory `.'

**Comment by MikeMcQuaid** [comment]
What does `brew info libtool` say?

**Comment by lexbi** [comment]
What I was trying to do with libtool (and autoreconf) was to install mozjpeg! I'm sure it wasn't an available package with brew yesterday! I was trying to install mozjpeg with the latest version of their repo. [using these steps](https://blarg.co.uk/blog/how-to-install-mozjpeg)

Though if you want it here is `brew info libtool`:

    libtool: stable 2.4.6 (bottled)
    Generic library support script
    https://www.gnu.org/software/libtool/
    /usr/local/Cellar/libtool/2.4.6_1 (70 files, 3.7M) *
      Poured from bottle on 2016-10-23 at 10:22:53
    From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libtool.rb
    ==> Options
    --universal
    	Build a universal binary
    ==> Caveats
    In order to prevent conflicts with Apple's own libtool we have prepended a "g"
    so, you have instead: glibtool and glibtoolize.

**Comment by MikeMcQuaid** [comment]
I'm afraid I'm not sure what the problem is here. You are probably best to take it up with `mozjpeg`.

**Comment by lexbi** [comment]
No problem, I'm happy to leave it as is as I now have mozjpeg installed via brew, thanks Mike

**Comment by VollmondT** [comment]
You need to run `brew install gnu-sed`
