### ISSUE TITLE
Fetching /opt/homebrew failed

### ISSUE THREAD

**Issue by rikola** [Homebrew/brew#13504]
Ran into this bug recently and I have taken a number of steps to debug with no luck. I have already tried reinstalling the Homebrew sourced Git with no effect.

### `brew config` output

```shell
tap HEAD: 74f86cf4aceccd73d0b946450aca9debed59ea48
Core tap last commit: 6 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.1 => /opt/homebrew/bin/git
Curl: 7
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to run `brew update`.

### What happened (include all command output)?

`brew update` repeatedly fails to fetch certain paths.

```
$ brew update
cat: /opt/homebrew/.git/TMP_FETCH_FAILURES: No such file or directory
Error: Fetching /opt/homebrew failed!
Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-cask failed!
Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-core failed!
```

```
$ brew update
Error: Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-cask failed!
Fetching /opt/homebrew failed!
Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-core failed!
```

### What did you expect to happen?

Brew would update installed packages and dependencies normally.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew update`
2. Brew fails to fetch
```

**Comment by Bo98** [comment]
This will be something on your end (e.g. a bad `git config --global http.proxy`), but there is a bug here where error reporting is not working properly due to a race condition so I'll fix that.

**Comment by rikola** [comment]
Got it. 
I only have 1 line that I think is relevant in my config here (both global and user) to set SSH based pulls.
```
url.git@github.com:.insteadof=https://github.com/
```
Do you expect that this is due to a connection error?

**Comment by rikola** [comment]
@Bo98 What is the resolution step now that a fix has been pushed? Do I need to nuke and reinstall homebrew?

**Comment by rikola** [comment]
Got it patched and it works for me now. Thanks!
