### ISSUE TITLE
Create the version variable based upon url when not explicitely set and/or to use it in the url when set

### ISSUE THREAD

**Issue by Porkepix** [Homebrew/brew#13501]
### Provide a detailed description of the proposed feature

Some software use transformed form versions for their download url, eg. instead of x.y.z things such as `xyz` or `x_y_z`.
Based from what I read on other formulas, I tried to tinker something from `#{version}`.
However it seems the bump commands do act on strings after variable evaluation, which leads to erratic results

For an easy explanation, here are some example and some of the solutions I tried to manage them, and their result:

Formula `basex`: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/basex.rb
URL's currently defined as `https://files.basex.org/releases/9.7.2/BaseX972.zip`.
`https://files.basex.org/releases/#{version}/BaseX#{version.to_s.tr('.', '')}.zip` => Tries to download `https://files.basex.org/releases/9.7.3/BaseX972.zip` as variables are evaluated first, and therefore only the first occurrence is replaced, the one with no added value to variabilize here. Result is the same as now, without variable.

Here, would it be possible to somehow evaluate variables after the bump commands replaced what they have to replace, in case it needs to replace fixed part within the url? (I'm not that knowledgeable in ruby and it might just be impossible due to the language).

Formula `ghex`: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ghex.rb
`https://download.gnome.org/sources/ghex/#{version.major}/ghex-3.18.4.tar.xz` => The formula have no `version` variable set, therefore it obviously result in `undefined method `major' for nil:NilClass`

This case is more tricky because it have no `version` defined. So from a url without variables, would it be possible to extract it and initialize the variable with it? Here I guess the problem is double though as I wished to use a variable, which means it should be explicitly created like in the `basex` formula from the first example I guess.

### What is the motivation for the feature?

Avoid some hassle when updating such formulas.

### How will the feature be relevant to at least 90% of Homebrew users?

This is only for people updating casks/formulas, but would avoid the manual editing for these kind of formulas at every update.

### What alternatives to the feature have been considered?

The alternative now is the need to manually manage these updates.

**Comment by carlocab** [comment]
You can still use `bump-formula-pr` if you pass both `--version` and `--url`, I think.

But it would be much nicer if you didn't need to pass `--url`. Maybe we can be a bit more aggressive about substituting things that look like they could be (part of) a transformed version.

We could allow an opt-out for this aggressive substitution for `url`s with false positives. My guess is that these aren't too common, though.

**Comment by Porkepix** [comment]
While I think of it, it curiously seems to work for casks, see for example https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/gzdoom.rb but not for formulas (I thought they were supposed to work the same way though?)

**Comment by Bo98** [comment]
It's an order thing. In casks, the version line is very intentionally before the url line.

**Comment by Porkepix** [comment]
And is there a reason not to do the same with formulas?

**Comment by Bo98** [comment]
That would be quite a major change given we've been parsing versions from URLs up to now rather than the other way round.

**Comment by MikeMcQuaid** [comment]
Yes, we're not going to change that in formulae.

**Comment by carlocab** [comment]
We don't like interpolation in formula `url`s -- that makes the URL much more difficult to use (i.e. copy and paste) elsewhere.

There's much less interest in doing that for cask `url`s, so interpolation is ok there.

**Comment by Porkepix** [comment]
Is it normal for issues marked as feature to also be marked as stale after some time?

> We don't like interpolation in formula `url`s -- that makes the URL much more difficult to use (i.e. copy and paste) elsewhere.
> 
> There's much less interest in doing that for cask `url`s, so interpolation is ok there.

In which case would it be needed to copy and paste it from the formula itself, at a point it would bother to variabilize urls, making updates easier and quicker?

**Comment by MikeMcQuaid** [comment]
> Is it normal for issues marked as feature to also be marked as stale after some time?

Yes. In a case like this it indicates: the only person who seems to care about this is you.

Passing on this for now.
