### ISSUE TITLE
Annotate formula with a `--note` keyword

### ISSUE THREAD

**Issue by vsheg** [Homebrew/brew#13511]
### Provide a detailed description of the proposed feature

`brew install` should provide functionality to annotate formulas and casks with a `--note` keyword:
```zsh
$ brew install --cask --note LaTeX latexit
```

Also, a note can be added to an existing formula or cask:
```zsh
$ brew upgrade --note LaTeX ghostscript
```

Then this annotation can be used to understand installation reason 
```zsh
$ brew list
==> Formulae
gcc
ghostscript [1]
python@3.10

⟹ Casks
latexit [1]

[1] LaTeX
```

Or to uninstall **all** formulas and casks annotated with it
```zsh
$ brew uninstall --note LaTeX
```

### What is the motivation for the feature?

1. The number of installed formulas can be very large. It's hard to remember which formulas are needed, which are not and can be removed. The user loses control of their formulas.
2. When switching to a new computer, I had to spend hours sorting out the formulas that I want to install on it, and which ones I don't need (I know how to check dependencies).
3. Some formulas are needed only to do a specific task one time, they can be annotated as `--note tmp` and then easy deleted

### How will the feature be relevant to at least 90% of Homebrew users?

This feature is relevant for 100% of Homebrew users, it's not something one needs to use every day, but it can provide organization for the working environment and bring clarity.

### What alternatives to the feature have been considered?

1. **Tags** — even more powerful, but more complicated abstraction
2. **Isolated environments** — same, but solves only the "install, use, uninstall" problem

**Comment by issyl0** [comment]
> When switching to a new computer, I had to spend hours sorting out the formulas that I want to install on it, and which ones I don't need (I know how to check dependencies).

You might be interested in [Homebrew/homebrew-bundle](https://github.com/Homebrew/homebrew-bundle) and the resulting `Brewfile`. You can leave comments in that file for why you have the packages installed, and migrating to a new computer is less manual work. (But, of course, it doesn't solve your "why is this dependency installed" question.)

**Comment by carlocab** [comment]
Similarly, you might be interested in
```
brew uses --installed
```
and
```
brew autoremove
```
Do `brew help uses` and `brew help autoremove` for details.

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry. Will consider additions to https://github.com/Homebrew/homebrew-bundle/issues/818 but note that we're not working on a PR for that so if you want to see it happen: you'll likely need to make one.
