### ISSUE TITLE
Brew on CentOS

### ISSUE THREAD

**Issue by PiegoIlTempo** [Homebrew/brew#13535]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.4-32-g8dd96ae
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8dd96ae8bacb4f7eb3ef476af63470e3702aee35
Last commit: 30 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 90ac25acbfc384850f140f1a395ea1c36d02da1e
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /var/www/brew
HOMEBREW_REPOSITORY: /var/www/brew
HOMEBREW_CELLAR: /var/www/brew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_CURL_PATH: /var/www/conda/bin/curl
HOMEBREW_GIT_PATH: /var/www/conda/bin/git
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_TEMP: /var/www/tmp
Homebrew Ruby: 2.6.8 => /var/www/brew/Library/Homebrew/vendor/portable-ruby/2
.6.8_1/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.34.1 => /var/www/conda/bin/git
Curl: 7.82.0 => /var/www/conda/bin/curl
Kernel: Linux 3.10.0 x86_64 GNU/Linux
OS: CentOS Linux release 7.9.2009 (Core)
Host glibc: 2.17
/usr/bin/gcc: N/A
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainer
s
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /var/www/conda/bin/krb5-config
  /var/www/conda/bin/icu-config
  /var/www/conda/bin/pcre2-config
  /var/www/conda/bin/ncursesw6-config
  /var/www/conda/bin/python3-config
  /var/www/conda/bin/curl-config
  /var/www/conda/bin/python3.9-config
  /var/www/conda/bin/xml2-config

Warning: No developer tools installed.
Install Clang or run `brew install gcc`.

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the defaul
t
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Almost running any command generates the same gcc error.

### What happened (include all command output)?

==> Downloading https://ghcr.io/v2/homebrew/core/gmp/manifests/6.2.1_1
Already downloaded: /var/www/.cache/Homebrew/downloads/a1986a80dafb4e42b83722
68a00d8d14aa8294154c876ba82e7ce48db06885cb--gmp-6.2.1_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gmp/blobs/sha256:786ae29f0c0
Already downloaded: /var/www/.cache/Homebrew/downloads/b4fd2f8770dab9531cfeae
2cbc9cdae3bfbccbf4e251c4aa251b75d23beb3fd9--gmp--6.2.1_1.x86_64_linux.bottle.
tar.gz
Warning: isl@0.18 has been deprecated because it is a versioned formula!
==> Downloading https://ghcr.io/v2/homebrew/core/isl/0.18/manifests/0.18
Already downloaded: /var/www/.cache/Homebrew/downloads/3fc6985b8d5510f9483586
e665765877864925065b08361bcd36b6894aef2df9--isl@0.18-0.18.bottle_manifest.jso
n
==> Downloading https://ghcr.io/v2/homebrew/core/isl/0.18/blobs/sha256:7d90ca
Already downloaded: /var/www/.cache/Homebrew/downloads/c1c43eda487e3a482a08c8
e6645c0592c1fd5d5a00ddc3478f5574ef0c03de4c--isl@0.18--0.18.x86_64_linux.bottl
e.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/manifests/4.1.0
Already downloaded: /var/www/.cache/Homebrew/downloads/e8b18e060649c00d9e1e35
1e3e05515c365e52dbd7bd392e2b99808d1f355b5b--mpfr-4.1.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/blobs/sha256:4c5f1cfd03
Already downloaded: /var/www/.cache/Homebrew/downloads/4f5616326bca124978f189
50459d2952bf4c7f89b1fa8bb329d79ca75a45079c--mpfr--4.1.0.x86_64_linux.bottle.t
ar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libmpc/manifests/1.2.1
Already downloaded: /var/www/.cache/Homebrew/downloads/3f193de9dd7f9e68742cf2
07cfadd3a63b695a8026d343b668e10a9b7bcf6e52--libmpc-1.2.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libmpc/blobs/sha256:d74eb5f1
Already downloaded: /var/www/.cache/Homebrew/downloads/b0eefa39efa0e65819ea5d
abcf012f00a06214a76e611e7fd0412dd437ad2c06--libmpc--1.2.1.x86_64_linux.bottle
.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/zlib/manifests/1.2.12
Already downloaded: /var/www/.cache/Homebrew/downloads/bcdc14b1a503ec4a85882f
6714ff61745887ed3635254ba02009e49edea4bd8c--zlib-1.2.12.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/zlib/blobs/sha256:23b1d8f050
Already downloaded: /var/www/.cache/Homebrew/downloads/cd6436a3fcb2a35afbcfab
85fa01b48302ec958430579d632dfd3a76cdd6448a--zlib--1.2.12.x86_64_linux.bottle.
tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/binutils/manifests/2.38_1
Already downloaded: /var/www/.cache/Homebrew/downloads/b4d5c9eb4befe13e9c658f
4f6b297d6984b8847c719c437cc8834ea86f20f38d--binutils-2.38_1.bottle_manifest.j
son
==> Downloading https://ghcr.io/v2/homebrew/core/binutils/blobs/sha256:9a90a3
Already downloaded: /var/www/.cache/Homebrew/downloads/fc8362f52c7edef2aa393c
a4030affa78c37b3c4b643537f5846c4899b9396a8--binutils--2.38_1.x86_64_linux.bot
tle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/linux-headers/4.4/manifests/
Already downloaded: /var/www/.cache/Homebrew/downloads/a09d28bc4becfe68b45b81
68cc36ab876b0e855b7782500defb208b0e313bf60--linux-headers@4.4-4.4.80.bottle_m
anifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/linux-headers/4.4/blobs/sha2
Already downloaded: /var/www/.cache/Homebrew/downloads/9b9abee4c4f94aa83546aa
8a17ab9ffe2f0f0184be9d3e8bf526cca5f62e0ec6--linux-headers@4.4--4.4.80.x86_64_
linux.bottle.tar.gz
Warning: Building glibc from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /var/www/brew/
Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /var/www/brew)
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
Already downloaded: /var/www/.cache/Homebrew/downloads/3c17421daad583cfd4fad5
87b8e1260f19385344f309d7ae11e0c2bb6b75d801--glibc-2.23.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/isl/manifests/0.24
Already downloaded: /var/www/.cache/Homebrew/downloads/cf108f3cbdbad48a5ecbe0
a148e97b47590045a58151ad768bcf7219ec23305a--isl-0.24.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/isl/blobs/sha256:7b58d25de0b
Already downloaded: /var/www/.cache/Homebrew/downloads/293cc043d5e0d52fb35010
d31acf68e6861ea916c0922feac92f282d5d6e176b--isl--0.24.x86_64_linux.bottle.tar
.gz
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/manifests/1.5.2-2
Already downloaded: /var/www/.cache/Homebrew/downloads/8c46fb1c48b918fc37efba
746bfd56937d317bc161cf9fa7d777c36058b2a587--zstd-1.5.2-2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/blobs/sha256:b612ded8e4
Already downloaded: /var/www/.cache/Homebrew/downloads/850eb02ac95aee357d2627
d8fa75c49daddc912b39dda47f13e39b5db9eb1f65--zstd--1.5.2.x86_64_linux.bottle.2
.tar.gz
Warning: Building gcc from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /var/www/brew/
Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /var/www/brew)
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-11.3.0/gcc-11.3.0.tar.xz
Already downloaded: /var/www/.cache/Homebrew/downloads/15b15ec6da8adbc355e2f9
329c6bbda55206eee13a9262850cab2e50da89da27--gcc-11.3.0.tar.xz
Error: The following formula cannot be installed from bottle and must be
built from source.
  gcc
Install Clang or run `brew install gcc`.

### What did you expect to happen?

To install gcc.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Brew has been installed outside of /home because I do not have root access, I know this can cause problem, but I wanted to know if there are workarounds.

I tried everything I could, even installing gcc externally does nothing because it will keep shouting the same error forever.

I installed trough conda updated versions of GIT and CURL, because brew couldn't even run without those.
```

**Comment by Bo98** [comment]
Hmm yeah this seems like an issue. It should be installing `gcc@5` (since you have no host GCC installed at `/usr/bin/gcc`), which is portable and can be installed to any prefix. However, because your system's glibc is too old, so it needs a newer glibc first but glibc is _not_ portable and therefore must be built from source. This leads into a bit of a loop, where it also tries newer GCCs etc which doesn't make the issue any better.

External GCC also currently only works if you have it at `/usr/bin/gcc` but I recognise the point you are using Homebrew is because you can't do that (and that was indeed the motivation for Homebrew on Linux's existence).

I'm not entirely sure how this originally worked. Someone from @Homebrew/linux might know.

**Comment by PiegoIlTempo** [comment]
> Hmm yeah this seems like an issue. It should be installing `gcc@5` (since you have no host GCC installed at `/usr/bin/gcc`), which is portable and can be installed to any prefix. However, because your system's glibc is too old, so it needs a newer glibc first but glibc is _not_ portable and therefore must be built from source. This leads into a bit of a loop, where it also tries newer GCCs etc which doesn't make the issue any better.
> 
> External GCC also currently only works if you have it at `/usr/bin/gcc` but I recognise the point you are using Homebrew is because you can't do that (and that was indeed the motivation for Homebrew on Linux's existence).
> 
> I'm not entirely sure how this originally worked. Someone from @Homebrew/linux might know.

Should I report this to them as well?

**Comment by danielnachun** [comment]
You need to install `glibc` first, and it should be possible to point it to your local GCC by doing `brew install --cc=gcc -v -s glibc` with your local GCC in your PATH.  Then you can install `gcc@5` from the bottle.  We should update that message because you don't actually need the `gcc` formula to bootstrap on CentOS, just `gcc@5` (they are not the same formula).

**Comment by PiegoIlTempo** [comment]
I managed to install gcc in /usr/bin/ I discovered that my environment has a tool that allows to install some packages even without root access, and gcc happened to be in those.

Then I successuflly installed gcc@5 and I tried to install gcc but it failed, the error guided me to https://github.com/Homebrew/homebrew-core/issues/101919 and I managed to successfully install gcc using the command `brew install --force-bottle gcc` suggested there.

But now I'm facing some more problems installing some packages such as ruby:

```==> Installing ocrmypdf dependency: ruby
==> ./configure --prefix=/var/www/.linuxbrew/Cellar/ruby/3.1.2 --enable-shared --with-sitedir=/var/www/.linuxbrew/lib/ruby/site_ruby --with-vendordir=/var/ww
==> make
==> make install
Last 15 lines from /var/www/.cache/Homebrew/Logs/ruby/03.make:
from /tmp/ruby-20220710-5707-1x47ene/ruby-3.1.2/lib/rubygems/ext/builder.rb:195:in `block in build_extensions'
from /tmp/ruby-20220710-5707-1x47ene/ruby-3.1.2/lib/rubygems/ext/builder.rb:192:in `each'
from /tmp/ruby-20220710-5707-1x47ene/ruby-3.1.2/lib/rubygems/ext/builder.rb:192:in `build_extensions'
from /tmp/ruby-20220710-5707-1x47ene/ruby-3.1.2/lib/rubygems/installer.rb:853:in `build_extensions'
from /tmp/ruby-20220710-5707-1x47ene/ruby-3.1.2/lib/rubygems/installer.rb:328:in `install'
from ./tool/rbinstall.rb:899:in `block in install'
from ./tool/rbinstall.rb:713:in `no_write'
from ./tool/rbinstall.rb:899:in `install'
from ./tool/rbinstall.rb:1068:in `block (2 levels) in <main>'
from ./tool/rbinstall.rb:1043:in `foreach'
from ./tool/rbinstall.rb:1043:in `block in <main>'
from ./tool/rbinstall.rb:1127:in `block in <main>'
from ./tool/rbinstall.rb:1124:in `each'
from ./tool/rbinstall.rb:1124:in `<main>'
make: *** [do-install-all] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting```

And I'm stuck again

**Comment by danielnachun** [comment]
The issue you're running into now is problem I have encountered myself in CentOS 7.  It appears to be because the native extensions don't use brewed `glibc` when they should be.  However since this is is not a problem with bootstrapping Homebrew on Linux but with installing a specific package from source, we need to move this to https://github.com/orgs/Homebrew/discussions as the issue tracker for `brew` is only for issues with the package manager and `homebrew-core` does not officially support building from source.  Please make a new thread in "Linux" category if you'd like to continue getting support for this issue.  Since I can reproduce this failure I will also be working on a solution and will open a PR if I find one.
