### ISSUE TITLE
VIM not building

### ISSUE THREAD

**Issue by tundratim** [Homebrew/brew#13540]
### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 3.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88a5fac96752f17280e64f60926f58dff45990e0
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: abcdf885805f8240313a103ee8391d0fc9ac8e0f
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/TundraWare/tools
HOMEBREW_REPOSITORY: /opt/TundraWare/tools
HOMEBREW_CELLAR: /opt/TundraWare/tools/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.8 => /opt/TundraWare/tools/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: hexa-core 64-bit skylake
Clang: N/A
Git: 2.37.0 => /opt/TundraWare/tools/bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.4.0-121-generic x86_64 GNU/Linux
OS: Linux Mint 20.1 (ulyssa)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Upgrade vim package

### What happened (include all command output)?

lto1: fatal error: bytecode stream in file '/opt/TundraWare/tools/opt/python@3.10/lib/python3.10/config-3.10-x86_64-linux-gnu/libpython3.10.a' generated with LTO version 11.0 instead of the expected 11.3

### What did you expect to happen?

Makefile should have completed and created a binary

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade
```

**Comment by MikeMcQuaid** [comment]
> ```shell
> Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
> Some of Homebrew's bottles (binary packages) can only be used with the default
> prefix (/home/linuxbrew/.linuxbrew).
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Twitter or any other official channels. You are responsible for resolving
> any issues you experience while you are running this
> unsupported configuration.
> ```

**Comment by tundratim** [comment]
???

**Comment by MikeMcQuaid** [comment]
@tundratim You pasted a message that tells you to not create issues.
