### ISSUE TITLE
Don't check quarantine support if quarantine is disabled

### ISSUE THREAD

**Issue by m-radzikowski** [Homebrew/brew#13561]
### Provide a detailed description of the proposed feature

The [quarantine support](https://github.com/Homebrew/brew/blob/0c785673d90ed080da50fcae0a85b15f6e038f72/Library/Homebrew/cask/quarantine.rb#L36) is [still checked](https://github.com/Homebrew/brew/blob/0c785673d90ed080da50fcae0a85b15f6e038f72/Library/Homebrew/cask/download.rb#L83) with the `--no-quarantine` flag. Normally this check is relatively quick so it doesn't slow the process much, although it's useless.

The proposal is to make the `Quarantine.available?` check only if the quarantine is not disabled.

### What is the motivation for the feature?

The quarantine script is failing on my Mac for some reason causing Homebrew to hang on for 5 minutes, and I was unable to fix it: https://github.com/Homebrew/homebrew-cask/issues/126180

Disabling quarantine doesn't help, because the quarantine support check is executed anyway.

Removing redundant quarantine support check would solve my problem.

### How will the feature be relevant to at least 90% of Homebrew users?

Honestly, it will not. Under normal conditions, the quarantine support check doesn't take long enough to be noticeable, so this optimization won't do much. But it won't hurt either.

### What alternatives to the feature have been considered?

I have no other ideas on how to solve the problem.

I will happily create a PR with the change if you agree to proceed with that. Please let me know what you think.

**Comment by MikeMcQuaid** [comment]
@m-radzikowski I agree this is an issue but I don't agree with your proposed solution. Instead, we should figure out why it is hanging on your machine. Let's continue conversation in https://github.com/Homebrew/homebrew-cask/issues/126180 instead.
