### ISSUE TITLE
Improve "Invalid bottle tag symbol" error

### ISSUE THREAD

**Issue by glensc** [Homebrew/brew#13585]
### Provide a detailed description of the proposed feature

I tried to add a tap on a new laptop, but it spews errors and doesn't even clone it.
So I cloned it manually and tried to run install on each of the reported formula.

Would be helpful that the messages be more clear about which tag is not supported:

```
$ brew install kubernetes-helm@2.8.2
Error: kubernetes-helm@2.8.2: Invalid bottle tag symbol
```

so which one of them is invalid?

```ruby
  bottle do
    sha256 cellar: :any_skip_relocation, "c105b8e5e29febdaa4e71d4d418550f87d13a75d6585b84e93958c2409ef2723" => :high_sierra
    sha256 cellar: :any_skip_relocation, "101dff96d86c4725437619fc8c1b3691cdcefdddfeacd230559fde2e256f479f" => :sierra
    sha256 cellar: :any_skip_relocation, "ea87d059e4eadb526c3dd12857a4f07cae0080af538a656d04f6617f7cb191b1" => :el_capitan
  end
```

improved error message:

```
$ brew install kubernetes-helm@2.8.2
Error: kubernetes-helm@2.8.2: Invalid bottle tag symbol: high_sierra
Error: kubernetes-helm@2.8.2: Invalid bottle tag symbol: sierra
```

or:

```
$ brew install kubernetes-helm@2.8.2
Error: kubernetes-helm@2.8.2: Invalid bottle tag symbol(s): high_sierra, sierra
```

### What is the motivation for the feature?

Avoid trial and error on upgrading old formulas.

### How will the feature be relevant to at least 90% of Homebrew users?

`¯\_(ツ)_/¯`

### What alternatives to the feature have been considered?

Just go with trial and error, try to remove the offending line.

**Comment by carlocab** [comment]
All of them are invalid bottle lines. They should say
```ruby
  bottle do
    sha256 cellar: :any_skip_relocation, high_sierra: "c105b8e5e29febdaa4e71d4d418550f87d13a75d6585b84e93958c2409ef2723"
    sha256 cellar: :any_skip_relocation, sierra:      "101dff96d86c4725437619fc8c1b3691cdcefdddfeacd230559fde2e256f479f"
    sha256 cellar: :any_skip_relocation, el_capitan:  "ea87d059e4eadb526c3dd12857a4f07cae0080af538a656d04f6617f7cb191b1"
  end
```
`brew style --fix` might fix this automatically; not sure.
