### ISSUE TITLE
`Error: 767` on macOS Big Sur with `HOMEBREW_INSTALL_FROM_API` 

### ISSUE THREAD

**Issue by steveh7812** [Homebrew/brew#13583]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.5-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: f041a59af9daddc7c7afe8537e3858103f8f9ab9
Last commit: 3 days ago
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.7-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

On macOS Big Sur with `HOMEBREW_INSTALL_FROM_API` set and `homebrew/core` not tapped, most `brew` commands return an `Error: 767` due to trying to parse an empty JSON file. This is because `curl` version `7.64.1` included with macOS Big Sur writes a zero-byte file to `cached_formula_json_file` when using `--header "If-Modified-Since:<date>"` and receives a `304` response code (See `curl` [issue 382](https://github.com/curl/curl/issues/382)). This is not applicable to macOS Monterey (`curl` version `7.79.1`, which handles the `304` response without writing to the output file).

Deleting the zero-byte cached json file fixes the problem but only for the next `brew` run, when it will create a new zero-byte file that can't be parsed.

### What happened (include all command output)?

``` bash
❯ brew info rsync
Error: 767: unexpected token at ''
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/api/formula.rb:40:in `all_formulae'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:655:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:541:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:626:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:622:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:622:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:307:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:141:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

``` bash
❯ du -sh ~/Library/Caches/Homebrew/api/formula.json
  0B	/Users/shahn/Library/Caches/Homebrew/api/formula.json
❯ rm -f ~/Library/Caches/Homebrew/api/formula.json
```

``` bash
❯ brew info rsync
rsync: stable 3.2.4 (bottled)
Utility that provides fast incremental file transfer
https://rsync.samba.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/rsync.rb
License: GPL-3.0-or-later
==> Dependencies
Required: lz4 ✘, openssl@1.1 ✘, popt ✘, xxhash ✘, zstd ✘
==> Analytics
install: 18,549 (30 days), 46,176 (90 days), 93,066 (365 days)
install-on-request: 17,966 (30 days), 44,628 (90 days), 89,570 (365 days)
build-error: 2 (30 days)
```

### What did you expect to happen?

I expected `brew` commands to work normally even though I have `HOMEBREW_INSTALL_FROM_API` set and `homebrew/core` untapped. I have a proposed fix and will submit a PR shortly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
export HOMEBREW_INSTALL_FROM_API=1
brew untap homebrew/core
brew info rsync
brew install rsync
```

**Comment by carlocab** [comment]
Thanks for the report and diagnosis.

> I have a proposed fix and will submit a PR shortly.

For bug fixes, feel free to skip the issue and jump straight to a PR next time around, unless the fix touches a lot of code and you want to discuss the approach.

**Comment by steveh7812** [comment]
> For bug fixes, feel free to skip the issue and jump straight to a PR next time around, unless the fix touches a lot of code and you want to discuss the approach.

Understood, will do.

**Comment by carlocab** [comment]
Thanks for the fix @steveh7812!
