### ISSUE TITLE
`brew deps` fails with `--formula` and emits a warning without it

### ISSUE THREAD

**Issue by lkrms** [Homebrew/brew#13592]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0b030b74e2ac518bd0bc4158f96c449198f9957f
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2b5709c32989ba0d1187b64a9cba039c4426cae0
Core tap last commit: 70 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_ARTIFACT_DOMAIN: http://brew.mirror
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 6
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.37.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
```

### `brew doctor` output

```shell
﻿﻿Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.4

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  bash-completion@2
  bash-completion

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install openssl@3

Run `brew missing` for more details.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `brew deps --union --full-name --formula <formula-names>` to generate a definitive list of dependencies for all of the formulae installed, or being installed, by a provisioning script.

Why? To identify orphaned packages. Some formulae may not be installed yet (e.g. if formulae have recently been added to the script), so `brew deps --installed` won't work; and some formulae installed explicitly on a previous run may have been removed from the script, so I can't rely on `brew autoremove` or `brew leaves` to identify orphans -- unless there's a mechanism to mark installed packages "installed as dependency", and no such mechanism seems to exist.

### What happened (include all command output)?

I received the following output when using the command above:

```
Usage: brew deps [options] [formula|cask ...]

Show dependencies for formula. Additional options specific to formula may be
appended to the command. When given multiple formula arguments, show the
intersection of dependencies for each formula.

  -n                               Sort dependencies in topological order.
      --1                          Only show dependencies one level down,
                                   instead of recursing.
      --union                      Show the union of dependencies for multiple
                                   formula, instead of the intersection.
      --full-name                  List dependencies by their full name.
      --include-build              Include :build dependencies for formula.
      --include-optional           Include :optional dependencies for
                                   formula.
      --include-test               Include :test dependencies for formula
                                   (non-recursive).
      --skip-recommended           Skip :recommended dependencies for
                                   formula.
      --include-requirements       Include requirements in addition to
                                   dependencies for formula.
      --tree                       Show dependencies as a tree. When given
                                   multiple formula arguments, show individual
                                   trees for each formula.
      --graph                      Show dependencies as a directed graph.
      --dot                        Show text-based graph description in DOT
                                   format.
      --annotate                   Mark any build, test, optional, or
                                   recommended dependencies as such in the
                                   output.
      --installed                  List dependencies for formulae that are
                                   currently installed. If formula is
                                   specified, list only its dependencies that
                                   are currently installed.
      --all                        List dependencies for all available formulae.
      --for-each                   Switch into the mode used by the --all
                                   option, but only list dependencies for each
                                   provided formula, one formula per line.
                                   This is used for debugging the
                                   --installed/--all display mode.
      --formula, --formulae        Treat all named arguments as formulae.
      --cask, --casks              Treat all named arguments as casks.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.

Error: Invalid usage: `--formula` cannot be passed without `--installed`.
```

After removing the `--formula` option (because `--installed` would generate incomplete output, as explained above), I got the following (truncated for brevity; the formula list isn't a concern):

```
Warning: Treating flock as a formula. For the cask, use homebrew/cask/flock
Warning: Treating unison as a formula. For the cask, use homebrew/cask/unison
Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake
adwaita-icon-theme
aom
apr
apr-util
argon2
aspell
atk
augeas
autoconf
bdw-gc
brotli
c-ares
ca-certificates
cairo
cjson
cmocka
coreutils
cpio
cunit
...
```

Given formula and cask names are both volatile, running the command without `--formula` is problematic regardless, but the fact that it generates a warning for any conflicts is irreconcilable with its refusal to run with `--formula`.

### What did you expect to happen?

A list of formulae should have been output, with no warnings.

My current workaround (for this long-standing issue) is to recursively process JSON output from `brew info` with `jq`, but this is slow and (very) inefficient. A reliable `brew deps` command would be far better.

### Step-by-step reproduction instructions (by running `brew` commands)

I've shortened the formulae list, but it still demonstrates the issue:

```shell
brew deps --union --full-name --formula coreutils diffutils findutils gawk gnu-getopt grep inetutils gnu-sed gnu-tar wget bash-completion flock icdiff jc jq newt pv python-yq rsync trash
```

Try again without --formula:

```shell
brew deps --union --full-name coreutils diffutils findutils gawk gnu-getopt grep inetutils gnu-sed gnu-tar wget bash-completion flock icdiff jc jq newt pv python-yq rsync trash
```

**Comment by carlocab** [comment]
By orphans, do you mean formulae installed as dependencies but no longer needed (because all their dependents are no longer installed)?

Are you interested in this list of orphans for informational purposes only, or is there something specific you wish to do with orphaned formulae?

**Comment by lkrms** [comment]
> By orphans, do you mean formulae installed as dependencies but no longer needed (because all their dependents are no longer installed)?

Not quite (although the formulae you describe are a subset of what I'm referring to). For the purposes of my provisioning script, orphans include formulae installed explicitly in a previous run (or directly via `brew install`) but not currently appearing in a list of required formulae, along with any dependencies that would be orphaned after their removal. Unfortunately it's not possible (as best I can tell) for Homebrew's state to be updated to reflect the formulae I'm keeping / not keeping (i.e. something equivalent to `pacman -D --asexplicit`/`pacman -D --asdeps` on Arch Linux, or `apt-mark auto`/`apt-mark manual` on Debian/Ubuntu), so I'm left with manually enumerating the required formulae and their dependencies and comparing it with installed formulae to determine which formulae will be orphaned *after installing any new formulae*. (Part of the objective is to make provisioning a one-step process--i.e. decide what's being installed and removed before actioning anything).

> Are you interested in this list of orphans for informational purposes only, or is there something specific you wish to do with orphaned formulae?

My provisioning script offers to remove them.

> Does your provisioning script use `brew bundle`?

I looked into moving to `brew bundle` recently, but it's more prescriptive than what I'm currently using and is better suited to CI environments (rather than system-wide provisioning with platform- and configuration-specific variations). TL;DR: no, I'm not using `brew bundle`.

Anyway, interesting as all of this may be, my particular use case has limited relevance to making `brew deps` reliable, effective and consistent for all users 😉

**Comment by lkrms** [comment]
Just checking in on this. Setting my particular use case aside, is there any consensus that it should be possible to run `brew deps --union --full-name --formula <formula-names>` to recurse into the given formulae--irrespective of what is or isn't currently installed--and produce a fully resolved list of every dependency of the given formulae? (As I understand it, the same calculation would already be performed if I were to pass the same list to `brew install --formula` on a clean system -- it's a pretty fundamental question for a package manager to be able to answer.)

I can only assume from the way `brew deps` requires `--installed` if `--formula` is used, despite apparently working as expected without `--formula` -- aside from the cask warnings -- that I'm missing something about the way Homebrew dependency resolution accommodates both formulae and casks, because these constraints don't make immediate sense (albeit without code diving).

**Comment by MikeMcQuaid** [comment]
We'll review PRs to improve this behaviour but we're not considering this a bug for maintainers to address at this time because it's unclear that it is something people other than you care about just now. Sorry!

**Comment by lkrms** [comment]
No worries, thanks for the response :)

**Comment by EricFromCanada** [comment]
One workaround is to adjust your provisioning script to prepend the tap name to each formula name, which would obviate the need for `--formula`, e.g.:
```
$ brew deps --union --full-name homebrew/core/flock homebrew/core/icdiff homebrew/core/jc homebrew/core/jq homebrew/core/newt homebrew/core/pv homebrew/core/python-yq homebrew/core/rsync homebrew/core/trash
ca-certificates
gdbm
gettext
jq
libffi
libpng
lz4
mpdecimal
oniguruma
openssl@1.1
popt
python@3.10
readline
s-lang
sqlite
xxhash
xz
zstd
```
