### ISSUE TITLE
Revive `--dsym` option for MacOS

### ISSUE THREAD

**Issue by lukaso** [Homebrew/brew#13604]
### Provide a detailed description of the proposed feature

Provide ability (generically) to create a build with debug symbols on MacOS by adding a `--dsym` option.

This was proposed in a [legacy proposal and PR](https://github.com/Homebrew/legacy-homebrew/pull/42053) which was rejected at the time because every formula had to be modified which added complexity.

If the solution had been less intrusive, the comments at the time suggest it would have been adopted.

Because of the `--keep-tmp` flag and taking a different approach, I think this is now possible.

In order to get a debug build of a formula, the developer would call `brew build --dsym <Formula>`.

Behind the scenes, the `--dsym` flag would set the `--keep-tmp` and the `-s` flags. It would add the `-g` flag but not change optimization level. Post `install` it would run `dsymutil` on all installed `Mach-O` binaries.

Unlike the legacy proposal, there would be no changes to any formulas. This would work automatically.

I'm looking for validation (or rejection) of this approach before I have a go at it (also depends on me having time).

Thanks.

### What is the motivation for the feature?

Improves the ability of formula writers/maintainers to debug problems with formulas, especially if the formula is working around quirks of how `homebrew` works. In my case, this is about where files are installed to. Gimp (which I maintain for Mac) requires a correctly set up environment to run, and this is different when set up and built in homebrew than when built elsewhere. Gimp has specific code to support the location of a number of different resources which come from other formula/packages.

Others have also requested this feature.

### How will the feature be relevant to at least 90% of Homebrew users?

Users get better and better maintained formulas.

### What alternatives to the feature have been considered?

Build the application/library separately, and then debug issues in homebrew using print statements instead of a debugger.

**Comment by carlocab** [comment]
Being able to produce debug symbols is occasionally useful. On the other hand, doing it this way
1. requires users to build from source (which we don't support)
2. requires use of a temporary directory that is removed on system restart

I don't personally find (1) a dealbreaker (`--dsym` could have the same treatment as `--HEAD`), but I don't think we want (2).

**Comment by MikeMcQuaid** [comment]
`brew install --interactive` is probably a better fit here.

> In order to get a debug build of a formula, the developer would call `brew build --dsym <Formula>`.

If we did want this: we'd not make it a new command but just do `brew install --debug-symbols` or similar naming that would make sense on Linux.

> I'm looking for validation (or rejection) of this approach before I have a go at it (also depends on me having time).

This approach seems reasonable but it's entirely down to how invasive the code is and how much of it there would be. If this added 10 lines of code in places that made sense: it seems like a no-brainer. If it's 1000 lines of code scattered around the codebase, I'm not sure it makes sense (given the number of users that want this compared to the code cost).

---

I'm closing this out not to stop conversation here, let's continue chatting, but just to make it clear that we're not actively soliciting this feature and that we may or may not be able to accept it depending on a PR.

Hope that context helps!

**Comment by lukaso** [comment]
> I'm not sure `--keep-tmp` preserves the `resource` staging directories too. (Or maybe I just didn't look in the right place when I last tried to find one.)

The key reason for using `--keep-tmp` is to ensure the source code is available for debugging. The resources part isn't necessary for that purpose. A new tmp directory is also made for each build, which is somewhat pretty inconvenient for a development workflow. But, to start, I feel the point is to make debugging possible, not necessarily to make it excellent.

For the full feature version, if ever that was desirable, I would suggest putting the source code in the relevant `Cellar` directory, or creating a parallel `Cellar_Source` directory and then doing the building from there, but I am not suggesting that at this time.

**Comment by lukaso** [comment]
> If we did want this: we'd not make it a new command but just do `brew install --debug-symbols` or similar naming that would make sense on Linux.

Yes, sorry, was writing too late at night. `brew install --debug-symbols` and variants is exactly what I had in mind.

**Comment by lukaso** [comment]
> I'm closing this out not to stop conversation here, let's continue chatting, but just to make it clear that we're not actively soliciting this feature and that we may or may not be able to accept it depending on a PR.

Thanks. That's all the validation I was looking for.

**Comment by lukaso** [comment]
OK, I've created a spike [PR](13608) for this feature. As you will quickly notice, it's really very little code, and it's totally *not* complete.
