### ISSUE TITLE
Create a standardised formula convention (+ DSL function) for `source`ing shell function scripts

### ISSUE THREAD

**Issue by chriskilding** [Homebrew/brew#13609]
### Provide a detailed description of the proposed feature

Some Homebrew formulae install shell functions. These functions are then loaded into the user's shell profile by appending the `source <function script>` directive to the end of e.g. the `.zshrc` or `.bashrc`. Typically these functions are shell-independent, so you want the same functions to be made available (without copy-pasting them) in any shell the user might use.

Today the two main approaches for this are:

- Print a message like `Please add 'source <function script>' to your #{shell_profile}` in the formula `caveats`, and rely on the user manually following this instruction.
- Hacking the string into the current user's `.zshrc` / `.bashrc` in the formula `post_install` step. (Since there is no convention for doing this, every formula does it differently.)

I propose that we come up with a single standardised convention for adding the source stanza in Homebrew formulae.

This may entail adding a new Homebrew formula DSL helper function, perhaps `source <something>`, which would:

- take care of appending the source stanza in whichever shell(s) the user uses (e.g. zsh, bash, fish)
- potentially be able to auto-remove the source stanza from the user's shell profile when the formula is uninstalled

### What is the motivation for the feature?

A standardised convention and support for adding/removing the `source` stanza would:

- Improve reliability of this step in all formulae (since formula authors would not have to roll their own logic for it, and there would be no caveat that the user must remember to follow)
- Give formula authors automatic `source` cleanup upon uninstallation 'for free'
- Make formulae look more similar to each other as concerns function sourcing, which will help new maintainers to understand them

### How will the feature be relevant to at least 90% of Homebrew users?

Many popular Homebrew formulae, including the programming language version managers (`rbenv`, `nvm`, `jenv`, `pyenv` and so on) which are widely used, install shell function scripts that need to be `source`d. Therefore many users will benefit from the development of a single standardised Homebrew approach for this.

### What alternatives to the feature have been considered?

It might be possible to copy the shell functions file into the `zsh_function` or `fish_function` directories directly (though I have not verified this), which would implicitly get the functions `source`d when the shell loads.

However:

- these shell function scripts are typically written in a portable way
- if a user is using multiple shells (e.g. legacy Bash on macOS plus Zsh) you typically want the functions to be available in all of them, not just one.
- there is no equivalent `bash_function` DSL macro, so I don't believe this would work for Bash

Therefore I believe that a direct copy to these locations would lead to duplication of code. Instead we want something which can just do the one-liner `source` thing for each shell, which references the centrally installed function script.

**Comment by carlocab** [comment]
I agree that standardising the handling of shell scripts might be useful.

However, I don't think we want to do this:

> This may entail adding a new Homebrew formula DSL helper function, perhaps `source <something>`, which would:
> 
> 
> 
> - take care of appending the source stanza in whichever shell(s) the user uses (e.g. zsh, bash, fish)
> 
> - potentially be able to auto-remove the source stanza from the user's shell profile when the formula is uninstalled

Formulae never write outside of `HOMEBREW_PREFIX` (both for security and for practical reasons), and especially not to a user's shell startup scripts.

**Comment by chriskilding** [comment]
Fair point, perhaps this could be something that the user can decide to opt into with a flag like
 
```
brew install <formula> --source
```

Or perhaps there could be a post-installation Brew command for this along the lines of `brew link <formula>`, which the user can run at their discretion:

```
brew install <formula>
brew source <formula>
```

**Comment by MikeMcQuaid** [comment]
> * Hacking the string into the current user's `.zshrc` / `.bashrc` in the formula `post_install` step. (Since there is no convention for doing this, every formula does it differently.)

If any formulae in homebrew/core do this: they shouldn't and I'm surprised the sandbox doesn't forbid it.



> Formulae never write outside of `HOMEBREW_PREFIX` (both for security and for practical reasons), and especially not to a user's shell startup scripts.

Given this: the best fit for this seems to be an external command that you could create @chriskilding (`brew source`). If there's sufficient uptake, we could consider adding it to Homebrew proper.

**Comment by chriskilding** [comment]
Can external Brew commands add custom macros to the formula DSL? I'd need the Brew formula to tell me what file(s) to source, so would likely need an additional formula `source` macro or method to let them do that. (Although it would probably not be called 'source' exactly... I imagine that name's already taken for build-from-source steps?). The external Brew command would then act on this information.

**Comment by MikeMcQuaid** [comment]
> Can external Brew commands add custom macros to the formula DSL?

No.

> I'd need the Brew formula to tell me what file(s) to source, so would likely need an additional formula `source` macro or method to let them do that.

Feels like this could either be inferred or maintained as a separate list in the tap until we see sufficient uptake to add a DSL.

---

Passing on this for now but happy to continue discussion here.

**Comment by carlocab** [comment]
As a model for how this might work if done externally, you might want to look at the commit history in https://github.com/Homebrew/homebrew-livecheck.

**Comment by chriskilding** [comment]
I've started working on an external command that would do this here:

https://github.com/chriskilding/homebrew-source

Will post with the odd update as I develop it.

**Comment by chriskilding** [comment]
First iteration (hardcoded data for now, demonstrates the possible API we could have)...

A formula will be able to declare one or more shell function scripts that the user needs to `source`. `brew source` sees these and then sources them:

```
$ brew source <foo>
Sourcing the shell functions from '<foo>' in your ~/.zshrc...
...done.
```

If you've already sourced those functions in your shell profile, `brew source` does its best to detect this and then avoids touching your configuration:

```
$ brew source <foo>
Sourcing the shell functions from '<foo>' in your ~/.zshrc...
...this formula's shell functions are already sourced, so no action was taken.
```

If the formula you specify does not declare shell functions, the groundwork is there for `brew source` to detect this and exit early:

```
$ brew source <foo>
Sourcing the shell functions from '<foo>' in your ~/.zshrc...
...this formula does not contain shell functions, so no action was taken.
```

**Comment by MikeMcQuaid** [comment]
> I've started working on an external command that would do this here:
> 
> https://github.com/chriskilding/homebrew-source

Will accept a PR to add this to https://docs.brew.sh/Interesting-Taps-and-Forks#unsupported-interesting-taps!

**Comment by chriskilding** [comment]
Great, will do that once I've developed it a bit further 👍

**Comment by chriskilding** [comment]
Potential extensions:

`brew doctor` could note the existence of installed formulae whose shell functions have **not** been sourced yet, and tell you how to fix this:

```
$ brew doctor
The following installed formulae contain shell functions that are not 'source'd in your shell profile yet:
foo bar baz
Run 'brew source <formula>' to fix this.
```

`brew install` could note the fact that a formula declares shell functions in its output:

```
$ brew install <foo>
==> Installing <foo>
==> Pouring...
🍺  /usr/local/Cellar/<foo>/<version>: 18 files, 1.1MB 

Shell functions were installed to the following locations:
/path/to/foo
/path/to/foo-abc
To make those functions available in <shell>, run 'brew source foo'.
```

A zero-arg version of `brew source` could offer to source all un-sourced shell functions for installed formulae (possibly with a confirmation prompt for each one):

```
$ brew source [-y|--yes]
Detecting installed formulae with un-sourced shell functions...
foo bar baz

foo contains shell functions, do you want to 'source' them in your ~/.zshrc? (y/n)
Sourcing... done
bar contains shell functions, do you want to 'source' them in your ~/.zshrc? (y/n)
Sourcing... done
...
```

**Comment by chriskilding** [comment]
By the by, is there a convention for how to integration test brew extension commands?

I've been able to unit test isolated aspects of my code by breaking some functions out into `lib/` modules. Rspec tests can then require these in just fine, because those modules don't `require` anything from brew.

However I've not been able to `require` the main subcommand file from rspec tests, as that does depend on the brew API, which Rspec knows nothing about. Hence I presume some other approach is required to integration test it.

**Comment by MikeMcQuaid** [comment]
Check the `homebrew-bundle` and `homebrew-services` for examples with integration and unit tests.

**Comment by chriskilding** [comment]
I'm trying to monkey patch a method onto Formula within the extension, so I can simulate the API I'd like it to have in future.

So far I've tried:

```
module Homebrew
    extend T::Sig

    # Patch what we want onto the brew Formula API
    class Formula
        def foo
            "abc"
        end
    end

    # ....

    sig { void }
    def source
        args = source_args.parse
        
        formula_name = args.named.first
        formula = Formulary.resolve(formula_name)

        puts formula.foo      
```

But unfortunately it fails with this error:

```
Error: undefined method `foo' for #<Formulary::FormulaNamespace55cc766e131622497758157bb3afb0c9::<my formula>:0x00007fbee524d0a0>
Did you mean?  for
```

I'm at a loss as to how to fix this, so what is the right place to do the monkey patch?

**Comment by chriskilding** [comment]
I've now got the extension to functioning prototype stage...

Given a formula which has the experimental `source_shell_functions` annotation:

```ruby
class Foo < Formula
  
  def install
    zsh_function.install "foo"
  end

  def source_shell_functions
    ["/usr/local/share/zsh/site-functions/foo"]
  end
```

Running `brew source foo` will read that annotation, and ensure that all paths mentioned in it have corresponding `source` directives in your shell profile:

```bash
# ...

. /usr/local/share/zsh/site-functions/foo
```

Side note: I'm using https://github.com/chriskilding/homebrew-evm as the experimental formula for this. You can tap+install it, then `source` it, to try it out.

**Comment by chriskilding** [comment]
To get the extension 'over the line', I'm interested in feedback about the design of the Formula DSL extension, to see how I can improve it.

In the version you see above, `source_shell_functions` is a standalone method. This works, but I'm not sure it's the best design for a couple of reasons:

- Connascence of strings: it involves duplicating script paths which are defined in the `install` method. It would be better to come up with a design that does not involve duplication if possible.
- It's a method, which is overkill for defining an array of strings (unless there really needs to be conditional logic in how that array is assembled).

I'm therefore wondering if something like this would be better:

```ruby
class Foo < Formula

    def install
        zsh_function.install "foo", { source: true }
        zsh_function.install "bar", { source: true }
    end
end
```

Or some variant like

```ruby
zsh_function.install "foo", [:source]
```

I think this is nicer as it simply marks up the existing install directive with the extra property - no duplication required.

Feedback welcome!

**Comment by MikeMcQuaid** [comment]
> I'm interested in feedback about the design of the Formula DSL

I would plan for not having a Formula DSL for the foreseeable future.

`zsh_function.install "foo", needs_sourced: true` with a new keyword argument seems the nicest option to me.

**Comment by chriskilding** [comment]
As long as I can patch the DSL method that I need onto Formula, that's alright for the time being while I work towards a v1 of the extension.

Onto the edge cases... I've remembered that a formula could put a script that needs `source`ing onto the user's system, without using the `install` or `<shell>_function.install` directive. For example, if the program has its own installer script or makefile:

```
def install
  system "make", "prefix=#{prefix}", "install"
end
```

The `system` command won't know that it was used to install a source-able function script, so we likely can't tack a `source: true` option on the end of that.

What options do we have here? Is it reasonable to tell formula authors that if they install a source-able function script, they must do it with the `<shell>_function.install` or `install` directives, and not rely on the upstream makefile? Or do we basically not have a choice other than to have the formula author specify the source-able functions separately?

**Comment by MikeMcQuaid** [comment]
> As long as I can patch the DSL method that I need onto Formula, that's alright for the time being while I work towards a v1 of the extension.

IMO I would not rely on monkey patches to Homebrew continuing to work in the timescale it takes for a tap like this to hit sufficient adoption to be accepted into Homebrew proper.

> What options do we have here?

Feels similar to `service` or `plist` behaviours; we add some metadata in a formula indicating where a known file was installed.

> Is it reasonable to tell formula authors that if they install a source-able function script, they must do it with the `<shell>_function.install` or `install` directives

No.

**Comment by chriskilding** [comment]
Ah yes, I can see how it's similar to `service`. How about something like this:

```ruby
class Foo < Formula

  def install
        system "make", "install"
  end

  shell do
    source "/usr/local/share/zsh/site-functions/foo"
    source "/usr/local/share/zsh/site-functions/foo-something"
  end
end
```

**Comment by chriskilding** [comment]
As a bonus, for scripts that were installed directly with Brew directives (e.g. `zsh_function`), perhaps we could let formula authors reuse the directive name in `source` (so they don't have to type out the full path)?

```ruby
class Foo < Formula

  def install
    zsh_function.install "foo"
  end

  shell do
    source zsh_function("foo")
  end
end
```
