### ISSUE TITLE
Removing prefix warning for `brew doctor` in arm mac

### ISSUE THREAD

**Issue by sleepymalc** [Homebrew/brew#13620]
### Provide a detailed description of the proposed feature

I find that the warning provided by `brew doctor` is quite confusing: If we simply follow the default installation script, `brew` is installed under `/opt/homebrew/bin/`.
```bash
Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
````
But from some of the [discussion](https://apple.stackexchange.com/questions/437618/why-is-homebrew-installed-in-opt-homebrew-on-apple-silicon-macs), this seems to be a designed choice made officially. I think this warning should either be taken down entirely or directed to discussions like the link above and tell the user that the rosetta-2 version can be installed in `/usr/local` if needed.

### What is the motivation for the feature?

The default prompt is now confusing and not informative.

### How will the feature be relevant to at least 90% of Homebrew users?

There are a LOT arm-mac users nowadays, and it'll keep growing.

### What alternatives to the feature have been considered?

Not sure.

**Comment by carlocab** [comment]
Have you been able to generate that warning with `brew doctor` on an M1 Mac?

**Comment by sleepymalc** [comment]
Yes, see the following.
<img width="852" alt="image" src="https://user-images.githubusercontent.com/60427058/181864379-2ec2e6bd-4dc7-4402-bccc-b657fef302b8.png">

**Comment by carlocab** [comment]
That shouldn't be happening.

What's the output of `brew config`?

Also, please [don't use screenshots](https://meta.stackoverflow.com/a/285557) when sharing the output of commands in your terminal. They're often difficult to read and impossible to reuse (e.g. when looking up error messages). Instead, copy the text here and wrap them in three back-ticks (```) on the line before and on the line after to format them properly.

**Comment by sleepymalc** [comment]
Ah, sure. The output of `brew config` is the following.
```bash
❯ brew config
HOMEBREW_VERSION: 3.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0b030b74e2ac518bd0bc4158f96c449198f9957f
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2c4f76e9687659cac2ca50558c044c9c2459e183
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit westmere
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: true
```

**Comment by carlocab** [comment]
This is your problem:
```
Rosetta 2: true
```
Don't run `brew` under Rosetta (e.g. try prepending `arch -arm64` to your `brew` invocations).
