### ISSUE TITLE
Brew using "master" branch when using --HEAD, despite that not being default branch

### ISSUE THREAD

**Issue by cblecker** [Homebrew/brew#13629]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.7-2-g4baff3e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4baff3eec111af70599c3fb517576d87ca74e9a2
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e0aeb1e4965edde4ceaafd13ecb868e427af434e
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Attempting to install a formula from my personal tap at --HEAD, in order to test unreleased commits.

### What happened (include all command output)?

==> Cloning https://github.com/openshift-online/ocm-cli.git
Cloning into '/Users/cblecker/Library/Caches/Homebrew/ocm--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Installing ocm from cblecker/tap
==> go generate -x ./cmd/... ./pkg/...
==> go build -o /opt/homebrew/Cellar/ocm/HEAD-9f3afbe/bin/ocm ./cmd/ocm
Warning: "/opt/homebrew/bin" is not in your PATH.
You can amend this by altering your /Users/cblecker/.bash_profile file.
==> Caveats
Bash completion has been installed to:
  /opt/homebrew/etc/bash_completion.d
==> Summary
🍺  /opt/homebrew/Cellar/ocm/HEAD-9f3afbe: 7 files, 11.6MB, built in 11 seconds
==> Running `brew cleanup ocm`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

### What did you expect to happen?

That brew would choose the branch named "main" not "master", which is the default branch in github (https://github.com/openshift-online/ocm-cli/branches)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Ensure cache doesn't have cached git pull: `rm -rf $(brew --cache)/ocm--git`
2. Install from tap: `brew install cblecker/tap/ocm --HEAD`
```

**Comment by Bo98** [comment]
You can do `head "https://github.com/openshift/oc.git", branch: "main"`

**Comment by carlocab** [comment]
The branch needs to be specified in the formula. `git clone` knows how to fetch the default branch, but updating a cached repository does not, so we assume the branch is `master` unless specified.

**Comment by cblecker** [comment]
@carlocab This is on a fresh pull, no cache

**Comment by cblecker** [comment]
There's also already a function to query the default branch, which I've confirmed that git command successfully returns "main"

**Comment by carlocab** [comment]
Sure. Let me put what I said earlier differently. Specifying the default branch, when the default branch is not called `master`, is required in the formula. Not specifying the default branch at all is deprecated, so you will likely eventually need to specify it even if it the default branch is `master`.

We'll review a PR that allows `brew` to work out the default branch without having to specify it in the PR.

**Comment by cblecker** [comment]
Thanks, that makes sense!
