### ISSUE TITLE
Update/Upgrade not possible

### ISSUE THREAD

**Issue by ChrisR68** [Homebrew/brew#13622]
### `brew config` output

```shell
HOMEBREW_VERSION: >=2.5.0 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 337c9a0832b6a7c4f714957ea958e36f8b7ebfe6
Core tap last commit: 14 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Missing https://github.com/Homebrew/brew git origin remote.

Without a correctly configured origin, Homebrew won't update
properly. You can solve this by adding the remote:
  git -C "/opt/homebrew" remote add origin https://github.com/Homebrew/brew
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Wanted to upgrade outdated installations

### What happened (include all command output)?

cka@/Users/wrks> brew upgrade
Warning: No remote 'origin' in /opt/homebrew, skipping update!
==> Homebrew has enabled anonymous aggregate formula and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics have been recorded yet (nor will be during this `brew` run).

fatal: not in a git directory
Error: Command failed with exit 128: git
==> Upgrading 26 outdated packages:
rubberband 2.0.2 -> 3.0.0
libtiff 4.4.0 -> 4.4.0_1
ffmpeg 5.0.1_2 -> 5.1
libidn2 2.3.2 -> 2.3.3
little-cms2 2.13.1 -> 2.13.1_1
nettle 3.8 -> 3.8.1
speex 1.2.0 -> 1.2.1
harfbuzz 4.3.0 -> 5.0.1
glib 2.72.2 -> 2.72.3
mbedtls 3.1.0 -> 3.2.1
srt 1.4.4 -> 1.5.0
tesseract 5.1.0 -> 5.2.0
webp 1.2.2 -> 1.2.3_1
sqlite 3.38.5 -> 3.39.2
xz 5.2.5 -> 5.2.5_1
libnghttp2 1.47.0 -> 1.48.0
libvpx 1.11.0 -> 1.12.0
librist 0.2.7 -> 0.2.7_1
ca-certificates 2022-04-26 -> 2022-07-19_1
isl 0.24 -> 0.25
btop 1.2.7 -> 1.2.8_1
leptonica 1.82.0 -> 1.82.0_1
jpeg-xl 0.6.1 -> 0.6.1_1
unbound 1.16.0 -> 1.16.1
fzf 0.30.0 -> 0.31.0
gnutls 3.7.6 -> 3.7.7
Error: snappy: undefined method `<=' for nil:NilClass

### What did you expect to happen?

Installations to be updated.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
cka@/Users/wrks> git -C "/opt/homebrew" remote add origin https://github.com/Homebrew/brew
error: remote origin already exists.

cka@/Users/wrks> brew update
Warning: No remote 'origin' in /opt/homebrew, skipping update!
Already up-to-date.

cka@/Users/wrks> brew upgrade
Warning: No remote 'origin' in /opt/homebrew, skipping update!
==> Upgrading 26 outdated packages:
rubberband 2.0.2 -> 3.0.0
libtiff 4.4.0 -> 4.4.0_1
ffmpeg 5.0.1_2 -> 5.1
libidn2 2.3.2 -> 2.3.3
little-cms2 2.13.1 -> 2.13.1_1
nettle 3.8 -> 3.8.1
speex 1.2.0 -> 1.2.1
harfbuzz 4.3.0 -> 5.0.1
glib 2.72.2 -> 2.72.3
mbedtls 3.1.0 -> 3.2.1
srt 1.4.4 -> 1.5.0
tesseract 5.1.0 -> 5.2.0
webp 1.2.2 -> 1.2.3_1
sqlite 3.38.5 -> 3.39.2
xz 5.2.5 -> 5.2.5_1
libnghttp2 1.47.0 -> 1.48.0
libvpx 1.11.0 -> 1.12.0
librist 0.2.7 -> 0.2.7_1
ca-certificates 2022-04-26 -> 2022-07-19_1
isl 0.24 -> 0.25
btop 1.2.7 -> 1.2.8_1
leptonica 1.82.0 -> 1.82.0_1
jpeg-xl 0.6.1 -> 0.6.1_1
unbound 1.16.0 -> 1.16.1
fzf 0.30.0 -> 0.31.0
gnutls 3.7.6 -> 3.7.7
Error: snappy: undefined method `<=' for nil:NilClass
```

**Comment by gromgit** [comment]
>```
>cka@/Users/wrks> git -C "/opt/homebrew" remote add origin https://github.com/Homebrew/brew
>error: remote origin already exists.
>```

That's weird, considering your main error. What's the output of the following:
```
git -C /opt/homebrew rev-parse --show-toplevel
git -C /opt/homebrew remote -v
```

**Comment by ChrisR68** [comment]
cka@/opt> git -C /opt/homebrew rev-parse --show-toplevel
/opt/homebrew

cka@/opt> git -C /opt/homebrew remote -v
origin	https://github.com/Homebrew/brew (fetch)
origin	https://github.com/Homebrew/brew (push)

**Comment by gromgit** [comment]
Weirder and weirder. What's the output of `git -C /opt/homebrew config -l`?

**Comment by ChrisR68** [comment]
Here we go :)

cka@/opt> git -C /opt/homebrew config -l
credential.helper=osxkeychain
user.name=Chris
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
core.autocrlf=false
remote.origin.url=https://github.com/Homebrew/brew
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
homebrew.analyticsmessage=true
homebrew.caskanalyticsmessage=true
homebrew.analyticsuuid=EF7FEA21-01DA-4CB9-8959-1806B9E95FC1
homebrew.donationmessage=true
homebrew.devcmdrun=true

**Comment by gromgit** [comment]
Try `brew update-reset`, then `brew config` and `brew doctor` again.

**Comment by ChrisR68** [comment]
cka@/opt> brew update-reset
Warning: No remote 'origin' in /opt/homebrew, skipping update and reset!
==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-cask...

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-cask...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-cask-fonts...

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-cask-fonts...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-core...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 4 (delta 3), reused 3 (delta 3), pack-reused 1
Unpacking objects: 100% (4/4), 840 bytes | 35.00 KiB/s, done.
From https://github.com/Homebrew/homebrew-core
 * [new branch]              update-tflint.rb-1659103062 -> origin/update-tflint.rb-1659103062

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-core...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-services...

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-services...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/koekeishiya/homebrew-formulae...

==> Resetting /opt/homebrew/Library/Taps/koekeishiya/homebrew-formulae...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/sidneys/homebrew-homebrew...

==> Resetting /opt/homebrew/Library/Taps/sidneys/homebrew-homebrew...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

cka@/opt> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Missing https://github.com/Homebrew/brew git origin remote.

Without a correctly configured origin, Homebrew won't update
properly. You can solve this by adding the remote:
  git -C "/opt/homebrew" remote add origin https://github.com/Homebrew/brew

cka@/opt> git -C "/opt/homebrew" remote add origin https://github.com/Homebrew/brew
error: remote origin already exists.

cka@/opt> brew upgrade
Warning: No remote 'origin' in /opt/homebrew, skipping update!
==> Upgrading 26 outdated packages:
rubberband 2.0.2 -> 3.0.0
libtiff 4.4.0 -> 4.4.0_1
ffmpeg 5.0.1_2 -> 5.1
libidn2 2.3.2 -> 2.3.3
little-cms2 2.13.1 -> 2.13.1_1
nettle 3.8 -> 3.8.1
speex 1.2.0 -> 1.2.1
harfbuzz 4.3.0 -> 5.0.1
glib 2.72.2 -> 2.72.3
mbedtls 3.1.0 -> 3.2.1
srt 1.4.4 -> 1.5.0
tesseract 5.1.0 -> 5.2.0
webp 1.2.2 -> 1.2.3_1
sqlite 3.38.5 -> 3.39.2
xz 5.2.5 -> 5.2.5_1
libnghttp2 1.47.0 -> 1.48.0
libvpx 1.11.0 -> 1.12.0
librist 0.2.7 -> 0.2.7_1
ca-certificates 2022-04-26 -> 2022-07-19_1
isl 0.24 -> 0.25
btop 1.2.7 -> 1.2.8_1
leptonica 1.82.0 -> 1.82.0_1
jpeg-xl 0.6.1 -> 0.6.1_1
unbound 1.16.0 -> 1.16.1
fzf 0.30.0 -> 0.31.0
gnutls 3.7.6 -> 3.7.7
Error: snappy: undefined method `<=' for nil:NilClass

**Comment by gromgit** [comment]
Sorry, I'm fresh out of ideas. Your Homebrew installation is b0rked so strangely that Git itself is giving contradictory messages.

Unless anyone else has any ideas, you may have to wipe and start from scratch, but run `brew bundle dump --global` first to dump your current Homebrew install state into your home directory first. Make sure it doesn't throw any errors though.

**Comment by ChrisR68** [comment]
No problem, but when I try to dump the bundle I get these errors. 
After I got errors in brew doctor before already from snappy,gcc and x265, I uninstalled them. But it seems they are still somewhere registered:

cka@/opt/homebrew> brew bundle dump --global
Warning: No remote 'origin' in /opt/homebrew, skipping update!
Warning: 'gcc' formula is unreadable: gcc: undefined method `on_arm' for #<Resource::PatchResource:0x000000012142f6b8>
Warning: 'snappy' formula is unreadable: snappy: undefined method `<=' for nil:NilClass
Warning: 'x265' formula is unreadable: x265: undefined method `on_intel' for Formulary::FormulaNamespacea33e4b1aa88dfc4cf6083d9fa695245d::X265:Class

**Comment by carlocab** [comment]
What is the output of
```
git -C /opt/homebrew status
```
?

**Comment by ChrisR68** [comment]
cka@/opt/homebrew> git -C /opt/homebrew status
On branch master
Your branch is behind 'origin/master' by 210 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean

**Comment by carlocab** [comment]
Try doing
```
git -C /opt/homebrew pull --ff-only
```

**Comment by ChrisR68** [comment]
Thanks Carlo, not only the dump is working now. Also the upgrade runs now! 

cka@/Users/christiankaufmann> brew bundle dump --global
fatal: not in a git directory
Warning: No remote 'origin' in /opt/homebrew, skipping update!

The file ha been created and it looks complete.
So, it looks like I still need to cleanup. Means uninstall all packages, remove the directory and then reinstall everything?

**Comment by carlocab** [comment]
> The file ha been created and it looks complete. So, it looks like I still need to cleanup. Means uninstall all packages, remove the directory and then reinstall everything?

You can use the uninstall script to do the uninstalling:
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
```
This will remove all packages you have installed, but you can use the generated `Brewfile` and `brew bundle` to reinstall them after you've reinstalled `brew`.

**Comment by ChrisR68** [comment]
I don't know the installation fails as well:

cka@/opt/Homebrew> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew
==> HOMEBREW_BREW_GIT_REMOTE is set to a non-default URL:
/opt/Homebrew/brew will be used as the Homebrew/brew Git remote.
==> HOMEBREW_CORE_GIT_REMOTE is set to a non-default URL:
/opt/Homebrew/homebrew-core will be used as the Homebrew/homebrew-core Git remote.

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R christiankaufmann:admin /opt/homebrew
==> Downloading and installing Homebrew...
fatal: '/opt/Homebrew/brew' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Failed during: git fetch --force origin


ENV is set:
cka@/opt/Homebrew> env | grep HOMEBREW
HOMEBREW_BREW_GIT_REMOTE=/opt/Homebrew/brew
HOMEBREW_CORE_GIT_REMOTE=/opt/Homebrew/homebrew-core

What are then the correct access rights? I can do anything in /opt/Homebrew

**Comment by carlocab** [comment]
Why do you have
```
HOMEBREW_BREW_GIT_REMOTE=/opt/Homebrew/brew
HOMEBREW_CORE_GIT_REMOTE=/opt/Homebrew/homebrew-core
```
?

Do
```
unset HOMEBREW_BREW_GIT_REMOTE HOMEBREW_CORE_GIT_REMOTE
```
and then try the install script again.

**Comment by ChrisR68** [comment]
I had this because its in the documentation. However, without the env it worked. Thanks

**Comment by carlocab** [comment]
> I had this because its in the documentation.

Where in the documentation? If it's there, then the documentation is wrong and needs to be fixed.

**Comment by ChrisR68** [comment]
https://docs.brew.sh/Installation

However, how I reinstall the dumped bundle? I can't find the brew bundle command to do that.

**Comment by carlocab** [comment]
Those docs say this:

> ## Git Remote Mirroring
> 
> You can use geolocalized Git mirrors to speed up Homebrew's installation and `brew update` by setting `HOMEBREW_BREW_GIT_REMOTE` and/or `HOMEBREW_CORE_GIT_REMOTE` in your shell environment with this script:
> 
> ```bash
> export HOMEBREW_BREW_GIT_REMOTE="..."  # put your Git mirror of Homebrew/brew here
> export HOMEBREW_CORE_GIT_REMOTE="..."  # put your Git mirror of Homebrew/homebrew-core here
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
> ```
> 
> The default Git remote will be used if the corresponding environment variable is unset.

I'm not sure how you concluded from there to set
```
HOMEBREW_BREW_GIT_REMOTE=/opt/Homebrew/brew
HOMEBREW_CORE_GIT_REMOTE=/opt/Homebrew/homebrew-core
```

**Comment by ChrisR68** [comment]
Probably slightly misunderstud.
