### ISSUE TITLE
install brew failed on macOS

### ISSUE THREAD

**Issue by athxx** [Homebrew/brew#13630]
### `brew config` output

```shell
-
```

### `brew doctor` output

```shell
-
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install `brew`

### What happened (include all command output)?

I am trying to install `brew` in a new macOS machine, it's showing that some issue that I can't install it complete, here is the information: 
```shell
x@osx ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R x:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at 4baff3eec Merge pull request #13624 from iMichka/core
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### What did you expect to happen?

Success to install 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
-
```

**Comment by carlocab** [comment]
This is not a bug in `brew`. It is most likely a problem with either your connection or your configuration. Please use this issue tracker only for issues with `brew` itself (as opposed to problems with installing it).

You can check the discussions page for related posts and potential solutions: https://github.com/Homebrew/discussions/discussions?discussions_q=unknown+revision+or+path+not+in+the+working+tree
