### ISSUE TITLE
Enhance `brew contributions`.

### ISSUE THREAD

**Issue by issyl0** [Homebrew/brew#13642]
### Provide a detailed description of the proposed feature

In the review comments of https://github.com/Homebrew/brew/pull/13603, multiple things were suggested as future enhancements to this command. In no particular order:

- Count both commit authors and commit committers.
- Figure out a way to use the GitHub APIs rather than `git log`. There currently doesn't seem to be any support for Co-authored-by authorships in the API though.
- Count "PRs reviewed ✅ or 🟥 by" (which implies write access).

- Also more stuff suggested in https://github.com/Homebrew/brew/pull/14642#issuecomment-1433141855.

### What is the motivation for the feature?

Deal with the leftover feature requests that were too big for the initial MVP.

The third one in the list:

> Count "PRs reviewed ✅ or 🟥 by" (which implies write access).

is the most important in my view. Currently, `brew contributions` only tracks code (co-)authored by a person. That fails to surface a large amount of what Homebrew maintainers do: community contributions, user support, PR reviews (I'm thinking particularly in Homebrew/homebrew-core). Without people reviewing PRs, we couldn't run this project.

### How will the feature be relevant to at least 90% of Homebrew users?

It won't, but this is a development command useful for project leadership to gather stats on project momentum and maintainer engagement.

### What alternatives to the feature have been considered?

Not implementing the features. It works adequately now, at a basic level, if all we care about is raw commits.

**Comment by troymccabe** [comment]
If nobody's taken a look at this I'd be interested in it! Think I have a thread to pull on grabbing the data requested via the graphql api, which should also be able to give us pr activity.

**Comment by troymccabe** [comment]
Would something like the following be beneficial?

```
+------------------------------------------------------------------------------+
| Contributions for <user_or_email>                                            |
+------------------------+-----------------+-----------------+-----------------+
| Repository             | Commits         | Co-authorships  | Signoffs        |
+------------------------+-----------------+-----------------+-----------------+
| brew                   | 31              | 0               | 0               |
| core                   | 256             | 0               | 0               |
| cask                   | 2252            | 503             | 2035            |
| aliases                | 0               | 0               | 0               |
| autoupdate             | 0               | 0               | 0               |
| bundle                 | 0               | 0               | 0               |
| command-not-found      | 0               | 0               | 0               |
| test-bot               | 0               | 0               | 0               |
| services               | 0               | 0               | 0               |
| cask-drivers           | 217             | 29              | 0               |
| cask-fonts             | 472             | 12              | 0               |
| cask-versions          | 325             | 27              | 0               |
+------------------------+-----------------+-----------------+-----------------+
| Total                  | 3553            | 571             | 2035            |
+------------------------+-----------------+-----------------+-----------------+
```

**Comment by issyl0** [comment]
That looks awesome, @troymccabe! Really looking forward to your PR! 😄

**Comment by MikeMcQuaid** [comment]
@troymccabe Yeh this would be great 🎉

**Comment by troymccabe** [comment]
Awesome! Looking for a way to get PR comments & rejections if those would
be valuable as well

**Comment by issyl0** [comment]
The latest desired features here:

- [ ] allow outputting for all maintainers (we've got some code to scrape these from the README)
- [ ] order the maintainers based on their total contributions
- [x] allow filtering to just the core repos (brew, homebrew-core, homebrew-cask) with --repositories=primary or something
   - https://github.com/Homebrew/brew/pull/14712
- [ ] include PR approvals
- [ ] allow ranking against all contributors in a repository
- [ ] count commit authors/commit committers separately
- [x] if not already done: include merge commits for the person who did the merge
   - This is already in the original implementation by default with the `--author` query.

**Comment by issyl0** [comment]
Closing this since the big items are completed. The remaining thing that uses `git log` is the coauthors data retrieval. When the GitHub APIs support that filter (I'm working on it) I'll use it.
