### ISSUE TITLE
Please add support for FreeBSD

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [Homebrew/brew#13653]
### Provide a detailed description of the proposed feature

Currently, `brew` does not support FreeBSD.

### What is the motivation for the feature?

Many packages are not accessible via `ports`, like `aws-cli v2`.

### How will the feature be relevant to at least 90% of Homebrew users?

It will be useful for those, who use BSD systems.

### What alternatives to the feature have been considered?

There are no alternatives at the moment.

**Comment by iMichka** [comment]
Hi. Thanks for the feedback. Can you give us the error message that prevents you to use `brew` on `freebsd`?

**Comment by MikeMcQuaid** [comment]
We have no plans to support FreeBSD ever. We'll review PRs to make it less broken on Homebrew/brew provided they aren't too involved.
