### ISSUE TITLE
Type error in NullVersion due to incorrect use of T.self_type + overriding

### ISSUE THREAD

**Issue by varungandhi-src** [Homebrew/brew#13652]
### `brew config` output

```shell
n/a
```

### `brew doctor` output

```shell
n/a
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I ran `./bin/brew typecheck` with brew `master` (35e4d68a1) with a build of Sorbet `master`.

### What happened (include all command output)?

I got a couple of type errors

```

version/null.rb:72: Return type `Version` does not match return type of overridden method `Version#major_minor` https://srb.help/5035
    72 |    def major_minor
            ^^^^^^^^^^^^^^^
    version.rb:602: Super method defined here with return type `T.self_type()`
     602 |  def major_minor
            ^^^^^^^^^^^^^^^
  Note:
    A method's return type must be a subtype of the return type on the super method.

version/null.rb:77: Return type `Version` does not match return type of overridden method `Version#major_minor_patch` https://srb.help/5035
    77 |    def major_minor_patch
            ^^^^^^^^^^^^^^^^^^^^^
    version.rb:608: Super method defined here with return type `T.self_type()`
     608 |  def major_minor_patch
            ^^^^^^^^^^^^^^^^^^^^^
  Note:
    A method's return type must be a subtype of the return type on the super method.
```

### What did you expect to happen?

The return type for the override should be the same as the receiver based on the [`T.self_type` docs](https://sorbet.org/docs/self-type). However, the type annotation on the `sig` in the overriden version is `Version` and not `T.self_type`. 

There are a couple of possible fixes:
1. Change the type signature in `NullVersion` to use `T.self_type` instead of `Version`.
2. Change the type signature in `Version` to use `Version` instead of `T.self_type`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Download a Sorbet binary from https://github.com/sorbet/sorbet/releases and stick it under `Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/srb`.
2. Run `./bin/brew typecheck`.
```

**Comment by carlocab** [comment]
Thanks for the report. We require the output of `brew config` and `brew doctor` for all bugs reported to Homebrew. We can reopen this when you provide the requested information.

**Comment by Bo98** [comment]
We usually get daily Sorbet updates but turns out we missed the last couple weeks. I'll look into that. The error is likely something new introduced in a recent version.

For now though, `brew typecheck` should automatically install Sorbet binary version 0.5.10175.

**Comment by Bo98** [comment]
I've tracked down the issue causing us to have an outdated version and it's being addressed upstream: https://github.com/dependabot/dependabot-core/issues/5569
