### ISSUE TITLE
There was a problem executing the "brew update" code(fatal: not in a git directory,;Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-services, skipping update! fatal: unable to access 'https://github.com/Homebrew/brew/': Failed to connect to github.com port 443 after 75006 ms: Operation timed out;)

### ISSUE THREAD

**Issue by Evanyang0425** [Homebrew/brew#13654]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: ce8ef89ec0cfe875c48c3a83a843af9074c05930
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: de58b4a8d7847b4b8d4f27aa3eaf7514abf54791
Core tap last commit: 54 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.32.1 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git
Curl: 7.83.1 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.0.0.0.1.1658620134
Xcode: 14.0 => /Applications/Xcode-beta.app/Contents/Developer
Rosetta 2: false
```

### `brew doctor` output

```shell
Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.


Warning: Ruby version 2.6.10 is unsupported on macOS 13. Homebrew
is developed and tested on Ruby 2.6.9, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

try to update the home-brew and install msf

### What happened (include all command output)?

fatal: not in a git directory
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-services, skipping update!
Already up-to-date.

### What did you expect to happen?

get error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
```

**Comment by carlocab** [comment]
Sorry, we don't provide support for unreleased versions of macOS. See

>```
> Warning: You are using macOS 13. We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.


Warning: Ruby version 2.6.10 is unsupported on macOS 13. Homebrew
is developed and tested on Ruby 2.6.9, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
>```

**Comment by Evanyang0425** [comment]
Okay, thanks, hopefully the problem will be fixed in the official version of mac os latest system

**Comment by mshahwerdi70** [comment]
> ### `brew config` output
> 
> ```shell
> HOMEBREW_VERSION: 3.5.7
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: ce8ef89ec0cfe875c48c3a83a843af9074c05930
> Last commit: 4 days ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: de58b4a8d7847b4b8d4f27aa3eaf7514abf54791
> Core tap last commit: 54 minutes ago
> Core tap branch: master
> HOMEBREW_PREFIX: /opt/homebrew
> HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
> HOMEBREW_CASK_OPTS: []
> HOMEBREW_MAKE_JOBS: 8
> Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
> CPU: octa-core 64-bit arm_firestorm_icestorm
> Clang: 14.0.0 build 1400
> Git: 2.32.1 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git
> Curl: 7.83.1 => /usr/bin/curl
> macOS: 13.0-arm64
> CLT: 14.0.0.0.1.1658620134
> Xcode: 14.0 => /Applications/Xcode-beta.app/Contents/Developer
> Rosetta 2: false
> ```
> 
> 
> ### `brew doctor` output
> 
> ```shell
> Warning: You are using macOS 13.
> We do not provide support for this pre-release version.
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Twitter or any other official channels. You are responsible for resolving
> any issues you experience while you are running this
> pre-release version.
> 
> 
> Warning: Ruby version 2.6.10 is unsupported on macOS 13. Homebrew
> is developed and tested on Ruby 2.6.9, and may not work correctly
> on other Rubies. Patches are accepted as long as they don't cause breakage
> on supported Rubies.
> ```
> 
> 
> ### Verification
> 
> - [X] I ran `brew update` and am still able to reproduce my issue.
> - [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
> 
> ### What were you trying to do (and why)?
> 
> try to update the home-brew and install msf
> 
> ### What happened (include all command output)?
> 
> fatal: not in a git directory
> Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-services, skipping update!
> Already up-to-date.
> 
> ### What did you expect to happen?
> 
> get error
> 
> ### Step-by-step reproduction instructions (by running `brew` commands)
> 
> ```shell
> brew update
> ```
> 

نه

**Comment by mshahwerdi70** [comment]
https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
