### ISSUE TITLE
Wrong parameter expansion with "brew shellenv"

### ISSUE THREAD

**Issue by duxsco** [Homebrew/brew#13674]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: ff9c2500195cc357d4a06f99d462f8d8a5d37892
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 882dc1d6e541367fdd4a9d79452dbc1c54b53066
Core tap last commit: 18 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTO_UPDATE_SECS: 86400
HOMEBREW_CASK_OPTS: [--appdir=~/Applications, --fontdir=/Library/Fonts]
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was following the installation steps to install.

### What happened (include all command output)?

I got asked to add `eval "$(/opt/homebrew/bin/brew shellenv)"` to `~/.bash_profile` or equivalent. I can't remember which file it was.

### What did you expect to happen?

I expected for parameter expansion to be used correctly. See `${parameter:+word}` from:
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02

It seems, however, that parameter expansion is used wrongly:
https://github.com/Homebrew/brew/blob/044fefdce91ce1a4dde8945ae6292dce74a0258f/Library/Homebrew/cmd/shellenv.sh#L48-L49

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew shellenv
```

**Comment by gromgit** [comment]
You're misreading the substitution. `${PATH+:$PATH}` literally means:
* if `PATH` is not set, substitute nothing
* if `PATH` _is_ set, substitute _a colon, followed by_ the contents of `PATH`

What you seem to think is correct, i.e. `${PATH:+$PATH}` is actually the wrong one. Simple demonstration:
```
$ echo $PATH
/usr/bin:/bin
$ echo /opt/homebrew/bin${PATH+:$PATH}
/opt/homebrew/bin:/usr/bin:/bin
$ echo /opt/homebrew/bin${PATH:+$PATH}
/opt/homebrew/bin/usr/bin:/bin
```

**Comment by carlocab** [comment]
Changing
```
${PATH+:$PATH}
```
to
```
${PATH:+:$PATH}
```
might be more POSIX-friendly.

Though I'd want to know which shells this fixes things for before changing anything.

**Comment by gromgit** [comment]
> Changing
> 
> ```shell
> ${PATH+:$PATH}
> ```
> 
> to
> 
> ```shell
> ${PATH:+:$PATH}
> ```
> 
> might be more POSIX-friendly.

POSIX actually defines both colon and non-colon variants, so that shouldn't be an issue.

However, I just realized that `${PATH+:$PATH}` results in a trailing colon if `$PATH` is _set but empty_, which effectively adds the _current directory_ to `$PATH`, i.e. it's equivalent to adding `:.`, which is a security no-no.

So yeah, `${PATH:+:$PATH}` is the correct substitution, even if the probability of `$PATH` being empty is low-to-no.

**Comment by duxsco** [comment]
> What you seem to think is correct, i.e. `${PATH:+$PATH}` is actually the wrong one. Simple demonstration:

With `${parameter:+word}`, I was thinking of "PATH" for "parameter" and ":$PATH" for "word". So, `${PATH:+:$PATH}` as @carlocab suggested should be the prefered way. In the 2nd table, it's the 2nd last example:
https://stackoverflow.com/a/16753536

The current approach is shown in the 2nd table in the last row.

**Comment by duxsco** [comment]
I still don't get why this issue got closed. `PATH` is obviously set wrongly as initially stated.

**Comment by carlocab** [comment]
Well, as initially stated, it wasn't at all clear, and definitely not obvious, what was wrong.

Upon further examination by @gromgit in https://github.com/Homebrew/brew/issues/13674#issuecomment-1210870437, maybe there is something wrong, but it's not really obvious either. It also applies to a really narrow edge case that I struggle to find worth keeping an issue open over.

If you could explain more clearly what exactly the consequences of the current usage of parameter expansion in `brew shellenv` is, and how changing the usage of parameter expansion avoids those consequences, preferably with information that hasn't yet been presented earlier in this issue, then maybe we can reconsider closing this.

**Comment by duxsco** [comment]
> Well, as initially stated, it wasn't at all clear, and definitely not obvious, what was wrong.

... and the issue got closed.

Here is some more info:
https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#index-PATH

**Comment by duxsco** [comment]
I'll just use:
```
eval "$(/opt/homebrew/bin/brew shellenv | sed -e 's/${PATH+:$PATH}/${PATH:+:$PATH}/' -e 's/${MANPATH+:$MANPATH}/${MANPATH:+:$MANPATH}/')"
```

**Comment by carlocab** [comment]
Links to documentation are really poor substitutes for explanations.

Do you regularly run `brew shellenv` in a shell where `PATH` and `MANPATH` are set to empty strings? If not, then it seems to me that you're incurring the overhead of calling `sed` to do absolutely nothing:

```
❯ diff -q <(echo foo) <(echo foo) && echo same
same
❯ diff -q <(echo foo) <(echo bar) && echo same
Files /dev/fd/13 and /dev/fd/14 differ
❯ diff -q <(echo ${PATH+:$PATH}) <(echo ${PATH:+:$PATH}) && echo same
same
❯ diff -q <(echo ${MANPATH+:$MANPATH}) <(echo ${MANPATH:+:$MANPATH}) && echo same
same
```
If you do set `PATH` and `MANPATH` to empty strings: why? What's the use case for this?

**Comment by duxsco** [comment]
Let me ask the other way around:
Why bothering with parameter expansion in the first place if only unset `PATH` is taken into consideration and not `PATH` set to empty value?
Instead of using `${PATH+:$PATH}` the homebrew team could have just used `:$PATH`.

And, let me ask further:
What's the use case for mitigating only unset `PATH` and not `PATH` set to empty value?

**Comment by duxsco** [comment]
I am just arguing from the point of view where unset `PATH` is mitigated, but not `PATH` set to emtpy value. And, I just pointed out that the second case is not taken care of. Whether using parameter expansion here is overkill is another field of discussion.

**Comment by duxsco** [comment]
It's not like it's a big step to take care of booth loose ends.

**Comment by carlocab** [comment]
> Let me ask the other way around:

So, does that mean you don't have a use-case for setting `PATH` and `MANPATH` to empty values? Why do [this](https://github.com/Homebrew/brew/issues/13674#issuecomment-1214145157) at all, then?

> Why bothering with parameter expansion in the first place if only unset `PATH` is taken into consideration and not `PATH` set to empty value?

> What's the use case for mitigating only unset `PATH` and not `PATH` set to empty value?

See, for example: https://github.com/Homebrew/brew/commit/59866d25ea39e4c5d25eb7cf78089d39752d88c3, https://github.com/Homebrew/brew/commit/7741672ecd417aac33c8810f0cafb96828fc6d1a, https://github.com/Homebrew/brew/commit/45368c81194379f1baeee86e82eeeb237610003f.

> Instead of using `${PATH+:$PATH}` the homebrew team could have just used `:$PATH`.

I agree, and, in fact, this is my preference, and the original implementation of `brew shellenv`:

https://github.com/Homebrew/brew/blob/44bcf69d1fe7c5bbd77b6cf4790825729ff16fa3/Library/Homebrew/cmd/shellenv.sh#L12-L17

The current version of `brew shellenv` evolved from changes designed to make it work for _concrete_ use-cases. As far as I can tell, there is no concrete use-case here, and only the desire to handle a case for the sake of handling it.

> And, I just pointed out that the second case is not taken care of.

Actually, it was @gromgit that really pointed this out. In any case, given that this second case a really narrow one that is very unlikely to come up for most users, the initial description of "wrong parameter expansion" is plainly wrong, and not really worth an open issue.

> It's not like it's a big step to take care of booth loose ends.

This is true, and, as I've stated [above](https://github.com/Homebrew/brew/issues/13674#issuecomment-1210686231), I'm not necessarily opposed to making this change.

That's different from keeping an issue open, though, because not making this change, given current evidence, seems to affect precisely zero users. I am, of course, willing to consider new evidence once presented. But none seems to be forthcoming despite [several](https://github.com/Homebrew/brew/issues/13674#issuecomment-1214139632) [requests](https://github.com/Homebrew/brew/issues/13674#issuecomment-1214162897) for it.

**Comment by duxsco** [comment]
> So, does that mean you don't have a use-case for setting `PATH` and `MANPATH` to empty values? Why do [this](https://github.com/Homebrew/brew/issues/13674#issuecomment-1214145157) at all, then?

Yes, I don't have an use case, like the homebrew team doesn't have one for the current approach. I could have removed the parameter expansion with `sed` instead, but I wanted to point out the correct way **if** you want to stay with parameter expansion without reason.

> See, for example: [59866d2](https://github.com/Homebrew/brew/commit/59866d25ea39e4c5d25eb7cf78089d39752d88c3), [7741672](https://github.com/Homebrew/brew/commit/7741672ecd417aac33c8810f0cafb96828fc6d1a), [45368c8](https://github.com/Homebrew/brew/commit/45368c81194379f1baeee86e82eeeb237610003f).

The possibility of `set -u` being used and the need for mitigation is not a valid use case, IMHO. Those who have their stuff failing due to unset `PATH` should rethink their setup.

> The current version of `brew shellenv` evolved from changes designed to make it work for _concrete_ use-cases. As far as I can tell, there is no concrete use-case here, and only the desire to handle a case for the sake of handling it.

I can't see an use case here for `${parameter+word}` as stated in my previous paragraph.

> Actually, it was @gromgit that really pointed this out. In any case, given that this second case a really narrow one that is very unlikely to come up for most users, the initial description of "wrong parameter expansion" is plainly wrong, and not really worth an open issue.

Instead of closing this ticket a question could have been asked to get things clarified. But, I on the other hand should have been clearer. I expected, though, what `parameter` and `word` is standing for being clear if parameter expansion such as `${parameter+word}` is used.

> That's different from keeping an issue open, though, because not making this change, given current evidence, seems to affect precisely zero users. I am, of course, willing to consider new evidence once presented. But none seems to be forthcoming despite [several](https://github.com/Homebrew/brew/issues/13674#issuecomment-1214139632) [requests](https://github.com/Homebrew/brew/issues/13674#issuecomment-1214162897) for it.

I can only repeat my first two paragraphs in this comment.

**Comment by MikeMcQuaid** [comment]
There's no reproducible instructions here despite several requests. This issue is not a good use of anyone's time, as-is.
