### ISSUE TITLE
Could not resolve host : github.com

### ISSUE THREAD

**Issue by OldAlosh** [Homebrew/brew#13694]
### `brew config` output

```shell
fatal: unable to access 'https://github.com/Datalux/Osintgram.git/': Could not resolve host: github.com
```

### `brew doctor` output

```shell
fatal: unable to access 'https://github.com/Datalux/Osintgram.git/': Could not resolve host: github.com
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I were trying to clone the Osintgram github project

### What happened (include all command output)?

I used "git clone https://github.com/Datalux/Osintgram.git"
then this happened
![image](https://user-images.githubusercontent.com/95544451/184475358-b52ee820-3041-4aad-80b2-a4fcafe873fd.png)

### What did you expect to happen?

I expected it to clone the Osintgram github and to use its commands normally

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
git clone https://github.com/Datalux/Osintgram.git
```

**Comment by carlocab** [comment]
This does not look related to Homebrew.
