### ISSUE TITLE
Allow downloadable content to be excluded from Time Machine backups

### ISSUE THREAD

**Issue by paul8046** [Homebrew/brew#13696]
### Provide a detailed description of the proposed feature

This issue was first raised and described here: https://github.com/Homebrew/brew/issues/11677#issue-939746768

I would propose a global setting to toggle the inclusion of downloadable content in Time Machine backups.

### What is the motivation for the feature?

A large amount of space is taken un in Time Machine back-ups with content that is superfluous to the needs of snapshotting. Homebrew packages can be re-downloaded and do not need to be backed up locally. Backing up these files slows backups down.

### How will the feature be relevant to at least 90% of Homebrew users?

Time Machine is a commonly used stock application. Similar applications such as docker have this option.

### What alternatives to the feature have been considered?

It was marked as resolved on the basis that the Homebrew cache is already excluded from Time Machine. However, this does not address the feature request. I have confirmed that my Time Machine backups do, in fact, contain Celler and Cackroom by default. Homebrew is not listed in the .exclusions.plist file of the Time Machine backup.

**Comment by MikeMcQuaid** [comment]
> I have confirmed that my Time Machine backups do, in fact, contain Celler and Cackroom by default. Homebrew is not listed in the .exclusions.plist file of the Time Machine backup.

Yes, this is intentional. Some people want this behaviour, others do not. I'd suggest this is something you can just do yourself. Sorry, passing on this.
