### ISSUE TITLE
Some packages install python@3.10 if they depend on it, others don't

### ISSUE THREAD

**Issue by Oleksii-Svintsitskyi** [Homebrew/brew#13709]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.9-117-g6f196ad
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6f196ad9ba2d52b6bbecca8e65643886a8e228db
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6629e1443e070391b4095132bddf98e5cf61e8f3
Core tap last commit: 22 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.GaLF92uvUl/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install pygobject3
brew install six

### What happened (include all command output)?

When I install pygobject3 - it installs python@3.10, if it's not installed yet
When I install six - it does not install any python@3.x, but just tries to install the library to any of [python@3.8, python@3.9, python@3.10]

### What did you expect to happen?

Either pygobject3 not installing python@3.10 if it's not installed yet or six also installing all the pythons it depends on. How do I know whether
`depends_on "python@3.10" => [:build, :test]`
gonna install python or not.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Either pygobject3 not installing python@3.10 if it's not installed yet or six also installing all the pythons it depends on. How do I know whether
`depends_on "python@3.10" => [:build, :test]`
gonna install python or not.
```

**Comment by bayandin** [comment]
`pygobject3` installs `python@3.10` as a transitive dependency through `gobject-introspection`. It will stop doing it after https://github.com/Homebrew/homebrew-core/pull/106045.

**Comment by Oleksii-Svintsitskyi** [comment]
@bayandin thanks
