### ISSUE TITLE
i want install php 8 but i get error 

### ISSUE THREAD

**Issue by 0xezady** [Homebrew/brew#13727]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3748bed378401ed75abdf32bcb3d2674d854a6f9
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d34f256c875a95d03d4d5fda9c54e14c1a52446c
Core tap last commit: 17 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit sandybridge
Clang: 10.0.0 build 1000
Git: 2.37.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
```

### `brew doctor` output

```shell
.
  .
  .
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

i want install php 8 because my php version is 7 and i want install laravel9 

### What happened (include all command output)?

every thing was good but in end i get this error:
curl: (22) The requested URL returned error: 403
Error: webp: Failed to download resource "webp"
Download failed: https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.4.tar.gz

### What did you expect to happen?

I expected PHP 8 to be installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install php@8.0
```

**Comment by gromgit** [comment]
You've already posted about this same error less than a day ago: https://github.com/Homebrew/discussions/discussions/3552

Posting in multiple places under the same organization, while _ignoring suggestions that have already been given_, won't get your problem solved any faster. Why don't you actually try @carlocab's suggestions in the other thread, and follow up there instead?
