### ISSUE TITLE
Major regression in #1253

### ISSUE THREAD

**Issue by scpeters** [Homebrew/brew#1372]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Since #1253 was merged, I'm unable to use the mercurial bottle. I've been [commenting in that pull request](https://github.com/Homebrew/brew/pull/1253#issuecomment-255900676), but I wanted to make an issue to make sure people see this. Feel free to close this if discussion moves to #1253.

The bottom-line is that after installing the mercurial bottle, the `hg` executable doesn't have its `@@HOMEBREW_PREFIX@@` symbol properly resolved:

~~~
$ head -1 /usr/local/opt/mercurial/bin/hg
#!@@HOMEBREW_PREFIX@@/opt/python/bin/python2.7
~~~

There is also a console error during installation (`Error: No such file or directory - /usr/local/opt/mercurial/bin/hg`):

~~~
$ brew install mercurial
==> Downloading https://homebrew.bintray.com/bottles/mercurial-3.9.2.yosemite.bottle.tar.gz
Already downloaded: /Users/jenkins/Library/Caches/Homebrew/mercurial-3.9.2.yosemite.bottle.tar.gz
==> Pouring mercurial-3.9.2.yosemite.bottle.tar.gz
Error: No such file or directory - /usr/local/opt/mercurial/bin/hg
~~~

I checked out e6bce5e and set `HOMEBREW_NO_AUTO_UPDATE` and the problem was gone, so I think it's this PR.

**Comment by zmwangx** [comment]
This is due to https://github.com/Homebrew/brew/pull/1253/files#diff-1f60679eb76b419ad46426e2a3b50621L766.

The old `keg.relocate_text_files` which should be outside `unless formula.bottle_specification.skip_relocation?` has been moved inside, causing text files to not be replaced.

CC @MikeMcQuaid @jawshooah.

**Comment by zmwangx** [comment]
Basically, all `any_skip_relocation` formulae can be expected to be broken. 1279 of them.

**Comment by jawshooah** [comment]
@scpeters Can you `brew update && brew pull https://github.com/Homebrew/brew/pull/1376` and verify that `brew reinstall hg` succeeds?

**Comment by scpeters** [comment]
I just tested it, looks good. Thanks for the quick fix!
