### ISSUE TITLE
Support config file?

### ISSUE THREAD

**Issue by Freed-Wu** [Homebrew/brew#13735]
### Provide a detailed description of the proposed feature

Now, brew use many environment vars named `$HOMEBREW_*` to config. User must `export HOMEBREW_XXX=XXX` in their shellrc.

Why not use a config file like `~/.brew.conf` or `~/.config/brew/brew.conf`? It is more clear and convenient to find, and avoid entangle brew's config with other code in shellrc.

### What is the motivation for the feature?

The most of the programs, which has many configurable items, will use config file to configure. Only when the programs' configurable item is very few, them possibly use environment var to configure for convenience in programming.

### How will the feature be relevant to at least 90% of Homebrew users?

For compatibility, the brew installed in the past will not be effected.

### What alternatives to the feature have been considered?

Provide an environment var named `$HOMEBREW_CONFIG_FILE`, such as:
```
export HOMEBREW_CONFIG_FILE="$HOME/.config/brew.conf"
```

**Comment by MikeMcQuaid** [comment]
Passing on this for now but will consider in future if we get more asks.
