### ISSUE TITLE
[Suggestion for the homepage at e. g. https://formulae.brew.sh/formula/adwaita-icon-theme] Provide "last update" display

### ISSUE THREAD

**Issue by rubyFeedback** [Homebrew/brew#13759]
### Provide a detailed description of the proposed feature

Hey folks,

The homepage of homebrew is really nifty. I refer to:

https://formulae.brew.sh/formula/

Individual formulas can be seen online via:

https://formulae.brew.sh/formula/adwaita-icon-theme

This is a VERY nice webpage. We can insta-see tons of useful
information.

However had, as great as it is, it does not provide any date
or time information.

For instance, I had a look at the argtable formula and then
I went to sourceforge for argtable here:

http://argtable.sourceforge.net/

I was disappointed that it was last updated in 2011 so 11
years (!) ago. It is probably dead at this point.

So if you go to the formula:

https://formulae.brew.sh/formula/argtable

It does not tell you anything about when it was added
to homebrew, and when the source archive itself
was last updated.

You don't necessarily have to provide both, but I think
it may be useful to display SOME kind of information
to users, so that they are not too disappointed when
they find out that the original source archive has been
abandoned many years ago.

### What is the motivation for the feature?

Now - I wrote a "package manager" in ruby starting in 2004. It is
riddled with bugs so I won't promote it here.

One class checks for all formulas here:

https://formulae.brew.sh/formula/

I checked and compared it with my own database and noticed
that I am not tracking 3700 programs that are registered in
homebrew. I counted 4618 formulas at homebrew - I may have
miscounted (my script is not perfect) and some formulas
are inactive or deprecated. But I think 4618 is a good high
number; may also be useful to add /stats or /statistics to
homebrew webpage for people to see that instantly.

Anyway, why do I think showing the last update would be nice?

Well, firstly, selfish - I want to see which programs are still
maintained by upstream devs. These I then want to 
investigate and add to my own local database.

But, even aside from this selfish reason, I believe adding
a date or time stamp may be useful. We could even sort
this via a HTML table and a bit of javascript, like how wikipedia
allows you to typically sort a table via up and down arrays to
sort by date/age.

This can come at a later time, though. First, to effect this,
I believe it may be useful to add when a program was last
updated upstream - and/or when the formula itself was
last changed. The former is better IMO, or you can provide
both informations of course. The latter is kind of already
shown on github when you make any change then git reports
this. But this is not on the homepage of a formula, so I 
propose this functionality to be added at homebrew itself
directly. And thus make it independent of any external
way to track changes such as via github. To clarify: I refer
to the online homepage of homebrew. But I assume that
the date/time information has to be stored somewhere, so
either at the "last change to local file", or perhaps as
an additional entry to the formula itself. Or alternatively
by a script that keeps track of this, without being 
required into the formula. (I assume you guys want to keep
formula simple and clean, so I understand no changes
made - but even then if you upload things, you can kind
of register that meta-information somewhere, even if
not directly in the .rb file itself).

### How will the feature be relevant to at least 90% of Homebrew users?

90% is a bit high limit. I don't think I could reach 90%.

However had I think people don't mind more statistics
and perhaps different people have a similar use case
to think that attaching that information to the display
of a formula (on the homebrew homepage, NOT on
github) would be nice and visually interesting. Personally
I actually need the "project had its last release x months
ago" to scan for active programs. 

### What alternatives to the feature have been considered?

Well, I can write a ruby script and check this automatically I guess. May work
for most packages too. For instance, argtable provides this information on
the homepage:

Version 2.13 ChangeLog http://argtable.sourceforge.net/ChangeLog, released Jan 10, 2011

So I know how old it is and the ruby script can easily run .scan() with a proper regex
to capture that. And I could extend this to work on many more homepages. But I
think it would be easier, simpler and cleaner if homebrew itself would keep track
of release dates and activity of upstream projects.

**Comment by carlocab** [comment]
Are you looking for something like [this](https://github.com/Homebrew/homebrew-core/commits/e571ab12b5d5583faa733b4c9793fc5a2d7281e4/Formula/adwaita-icon-theme.rb)?

**Comment by MikeMcQuaid** [comment]
> It does not tell you anything about when it was added
> to homebrew, and when the source archive itself
> was last updated.

The latter is not information we have access to and the prior is going to be too expensive to generate for every formula. Your best bet is the Git/GitHub history here. Sorry!
