### ISSUE TITLE
brew install <package>@<version> does not work very well

### ISSUE THREAD

**Issue by rkitover** [Homebrew/brew#13768]
### Provide a detailed description of the proposed feature

I'm not sure what the implementation should be, let's discuss.

### What is the motivation for the feature?

Recently I was installing some packages on High Sierra, and I ran into the not uncommon problem of having to use an older version of a formula because the current version did not build. In my case it was llvm and I installed 13 with:

```bash
brew -v install llvm@13
```
. While it did build and install, the behavior of this command leaves much to be desired.

The package was installed into `/usr/local/Cellar/llvm@13` and linked in `/usr/local/opt/llvm@13`.

What this means is that I did not actually have this version of the llvm formula installed, I had a formula called `llvm@13` that was completely unusable by either the rest of brew or me.

What I ended up doing was copying the version directory `13.0.1_1` from `/usr/local/Cellar/llvm@13` to `/usr/local/Cellar/llvm` and making a `/usr/local/opt/llvm` link to it as well.

Then everything worked fine.

### How will the feature be relevant to at least 90% of Homebrew users?

They should be able to use the `brew install <package>@<version>` command and have things work as they expect.

### What alternatives to the feature have been considered?

`brew install ./formula.rb` always works.

**Comment by Bo98** [comment]
This is intentional. You're installing a [separately maintained formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm@13.rb) - this is not a version pinning feature (Homebrew is a rolling release package manager). It allows side-by-side installations too.

> I had a formula called `llvm@13` that was completely unusable by either the rest of brew or me.

How is it "unusable"? If you need LLVM 13 specifically, which it sounds like you do, then you should be pointing to `llvm@13`. The main LLVM formula has a `llvm@14` symlink for similar needs.

If you're referring to other formulae which depend on LLVM, note that major versions of LLVM introduce binary incompatible breaking changes to libLLVM so anything which links to that library will need to recompiling to work properly, so simply swapping out LLVM won't work no matter what we do. If you want to do this, the best route is using `brew extract` to make a copy of those formulae in your own tap and modifying them to compile against `llvm@13` instead.

**Comment by rkitover** [comment]
> How is it "unusable"? If you need LLVM 13 specifically, which it sounds like you do, then you should be pointing to llvm@13. The main LLVM formula has a llvm@14 symlink for similar needs.
> If you're referring to other formulae which depend on LLVM, note that major versions of LLVM introduce binary incompatible breaking changes to libLLVM so anything which links to that library will need to recompiling to work properly, so simply swapping out LLVM won't work no matter what we do. If you want to do this, the best route is using brew extract to make a copy of those formulae in your own tap and modifying them to compile against llvm@13 instead.

So the specific problem I had is that the formula `snappy.rb` has this code in it:

```ruby
# Fix issue where Mojave clang fails due to entering a __GNUC__ block
on_macos do
   depends_on "llvm" => :build if DevelopmentTools.clang_build_version <= 1100
end
```

High Sierra has llvm 10, and installing `llvm@13` does not satisfy this dependency without making the `/usr/local/opt/llvm` symlink to it.

Could at least this be made to work somehow?

**Comment by carlocab** [comment]
> High Sierra has llvm 10, and installing `llvm@13` does not satisfy this dependency without making the `/usr/local/opt/llvm` symlink to it.
> 
> 
> 
> Could at least this be made to work somehow?

No.

```ruby
depends_on "llvm"
```
can be fulfilled only by the `llvm` formula. It cannot be fulfilled by anything provided by macOS, nor can it be fulfilled by a versioned LLVM formula.

**Comment by rkitover** [comment]
> note that major versions of LLVM introduce binary incompatible breaking changes to libLLVM so anything which links to that library will need to recompiling to work properly

This only affects platforms with bottles, platforms like High Sierra with source only builds would build everything anyway.

> can be fulfilled only by the llvm formula. It cannot be fulfilled by anything provided by macOS, nor can it be fulfilled by a versioned LLVM formula.

The actual dependency here is:

```ruby
DevelopmentTools.clang_build_version
```
, the way this is implemented, and I don't understand this exactly but I did some testing, is it always returns the clang version of XCode, even if you have llvm installed.

So in my case, on High Sierra,  it always returns 10, even if I have llvm installed, while llvm is actually used to do the builds by the shims like `/usr/local/Homebrew/Library/Homebrew/shims/mac/super/llvm_clang++`.

These shims only check `/usr/local/opt/llvm/bin` etc., so if you install for example `llvm@13` they will not check `/usr/local/opt/llvm@13/bin` and it will never be used for builds, without making this symlink yourself.

Even worse, if you install an older version of llvm, manually or otherwise, and pin it, the above code block will still always try to install the latest llvm because `clang_build_version` returns the XCode version.

I think this situation is suboptimal, if you agree I can help work on some improvements.

**Comment by carlocab** [comment]
I'm open to trying to improve this, but let's discuss your plans in a new issue to make sure that you don't end up working on changes that we're not willing to adopt.

**Comment by rkitover** [comment]
Opened #13779 and #13780.

**Comment by carlocab** [comment]
It might also be simpler to just fix the build failure for `llvm` -- what problem are you seeing, exactly? Do you have the output of `brew gist-logs llvm`?

**Comment by rkitover** [comment]
I will try to follow up on the llvm build failures as well, they are different for 14 and HEAD.

**Comment by carlocab** [comment]
`HEAD` changes all the time, and isn't worth trying to fix. 14 might be worth taking a look at.

**Comment by rkitover** [comment]
I will ask the llvm people if they are actually interested in maintaining support for High Sierra, otherwise it will always be broken.
