### ISSUE TITLE
Brew warns about outdated Xcode version even when the --quiet option is passed

### ISSUE THREAD

**Issue by acecilia** [Homebrew/brew#13766]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: c5731faf8be1ddc1eeae4b162b88bd76318fc279
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e42f9a000bfd5cbc7168f3a4e98a9bf2991b1442
Core tap last commit: 40 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.2.1 => /Applications/Xcode-13.2.1.app/Contents/Developer
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Xcode (13.2.1) is outdated.
Please update to Xcode 13.4 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Running the following command: 

```shell
brew install --quiet --build-from-source xcodegen
```

### What happened (include all command output)?

I see the following output:

```shell
Warning: Your Xcode (13.2.1) is outdated.
Please update to Xcode 13.4 (or delete it).
Xcode can be updated from the App Store.
```

### What did you expect to happen?

I am explicitly passing the `--quiet` flag to brew, and I would expect the warning about the xcode version to not show up.

Context: the version of Xcode used is responsibility of the developer, and at the moment given the projects I am working on I can not update to the latest version of Xcode. 

Taking this one step further: I do not think is correct to show such message even without `--quiet`. You cannot expect developers to always be using the latest releases of the tooling.

The warning is generated here: https://github.com/Homebrew/brew/blob/2258ba5797c1ea8149a49673b5c080011c366237/Library/Homebrew/extend/os/mac/diagnostic.rb#L144

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --quiet --build-from-source xcodegen
```

**Comment by MikeMcQuaid** [comment]
> the version of Xcode used is responsibility of the developer, and at the moment given the projects I am working on I can not update to the latest version of Xcode.

Things regularly break without the latest Xcode so: no, we don't agree, sorry.

**Comment by acecilia** [comment]
@MikeMcQuaid The issue is not about agreeing. Is about the warning showing up even when passing the `--quiet` flag:

> I am explicitly passing the --quiet flag to brew, and I would expect the warning about the xcode version to not show up

**Comment by MikeMcQuaid** [comment]
You said you didn't think it should show up even without the `--quiet` flag. I think it should show up in both cases.

I don't think `--quiet` should be silencing warnings that things may break based on your configuration.

**Comment by acecilia** [comment]
I will give you more context. I work as member of the platform team, serving 100 developers on a project that cannot update to every latest xcode release instantly. Xcode updates are never smooth or easy in big codebases, and updating takes preparation, work and time.

The warning brew shows is making the developers update their xcodes, leading to issues (as said, the project does not support latest xcode). 

I understand if you want to show the warning, but at least provide a way to silence it for the people that do not want it

**Comment by MikeMcQuaid** [comment]
Sure, that makes sense for your context. 

You'll need to tell your developers to not update their Xcode.

We want to keep warning people that they are in a configuration that breaks things. We don't want to provide a way to silence these warnings (not just this one but these sorts of ones in general).

**Comment by acecilia** [comment]
> I don't think --quiet should be silencing warnings that things may break based on your configuration.

I do not see how updating xcode is going to solve any issues. I would understand it if you were to offer a compatibility matrix between versions of brew and versions of xcode. But that is not the case. Using and old version of brew with the latest xcode will likely break as much as using a new version of brew with an old xcode

> You'll need to tell your developers to not update their Xcode.

That is not a solution for this ticket

> We don't want to provide a way to silence these warnings (not just this one but these sorts of ones in general).

I am raising an issue here, reasonably documenting usecases where silencing this makes sense. I do not understand why you want to force a warning upon consumers if they explicitly want a `quiet` output

**Comment by acecilia** [comment]
Specially weird seeing how already some people have hardcoded special cases for silencing this warning [here](https://github.com/Homebrew/brew/blob/2258ba5797c1ea8149a49673b5c080011c366237/Library/Homebrew/extend/os/mac/diagnostic.rb#L141) and [here](https://github.com/Homebrew/brew/blob/2258ba5797c1ea8149a49673b5c080011c366237/Library/Homebrew/extend/os/mac/diagnostic.rb#L137)

**Comment by acecilia** [comment]
You guys are having this issue in brew repository itself and is documented [here](https://github.com/Homebrew/brew/blob/2258ba5797c1ea8149a49673b5c080011c366237/Library/Homebrew/extend/os/mac/diagnostic.rb#L133), where the CI cannot update to the latest version as fast, resulting in the need of silencing the warning:

```
# CI images are going to end up outdated so don't complain when
# `brew test-bot` runs `brew doctor` in the CI for the Homebrew/brew
# repository. This only needs to support whatever CI providers
# Homebrew/brew is currently using.
```

**Comment by MikeMcQuaid** [comment]
> I am just asking for a proper way of silencing it other than passing an obscured/non-documented env variable

And I am saying: we do not wish to provide this.
