### ISSUE TITLE
brew audit postgresql@14 throws spurious warning

### ISSUE THREAD

**Issue by xrisk** [Homebrew/brew#13772]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.10-60-g98999cc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 98999cc51033c6f1b2aae662024cba8544dcd3fd
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d9833b17d911e922ab5a74e9ac07df9720f06469
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.xtMG3ORoTy/org.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/xrisk/.pyenv/shims/python3.7-config
  /Users/xrisk/.pyenv/shims/python3.10-config
  /Users/xrisk/.pyenv/shims/python3.7m-config
  /Users/xrisk/.pyenv/shims/python-config
  /Users/xrisk/.pyenv/shims/python3-config
  /Users/xrisk/.pyenv/shims/python3.8-config
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `brew audit postgresql@14` before making a PR.

### What happened (include all command output)?

```
❯ brew audit --strict postgresql@14
Warning: Use postgresql@14 instead of deprecated postgresql
```

### What did you expect to happen?

No warning since I used the versioned Postgres.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew audit postgresql@142. 
```
If I understand correctly, the problem stems from https://github.com/Homebrew/brew/blob/98999cc51033c6f1b2aae662024cba8544dcd3fd/Library/Homebrew/formula_auditor.rb#L62 but I’m not sure what a good way to resolve this is.

**Comment by apainintheneck** [comment]
It's interesting that the same error message gets spit out regardless of the `postgresql` version used in the audit.

```shell
$ brew audit postgresql@14
Warning: Use postgresql@14 instead of deprecated postgresql
$ brew audit postgresql@13
Warning: Use postgresql@14 instead of deprecated postgresql
$ brew audit postgresql@12
Warning: Use postgresql@14 instead of deprecated postgresql
$ brew audit postgresql@11
Warning: Use postgresql@14 instead of deprecated postgresql
$ brew audit postgresql@10
Warning: Use postgresql@14 instead of deprecated postgresql
$ brew audit postgresql@9.6
Warning: Use postgresql@14 instead of deprecated postgresql
$ brew audit postgresql@9.5
Warning: Use postgresql@14 instead of deprecated postgresql
$ brew audit postgresql@9.4
Warning: Use postgresql@14 instead of deprecated postgresql
```

Another interesting thing I found was that the audit messages for the old postgresql formulas for versions 9.4 and 9.5 seem to produce even more confusing messages.

```bash
$ brew audit postgresql94
Warning: Use postgresql@9.4 instead of deprecated postgresql94
Warning: Use postgresql@9.4 instead of deprecated postgresql94
Warning: Use postgresql@14 instead of deprecated postgresql
$ brew audit postgresql95
Warning: Use postgresql@9.5 instead of deprecated postgresql95
Warning: Use postgresql@9.5 instead of deprecated postgresql95
Warning: Use postgresql@14 instead of deprecated postgresql
```

I think the line you mentioned is part of the problem. The main thing seems to be that the list of renamed formula ([formula_renames.json](https://github.com/Homebrew/homebrew-core/blob/master/formula_renames.json) over on [Homebrew Core](https://github.com/Homebrew/homebrew-core)) appears to only have one formula that could be misinterpreted for another after stripping the version number and that is postgresql. The warning is being thrown from [`Formulary::Taploader.formula_name_path`](https//github.com/Homebrew/brew/blob/98999cc51033c6f1b2aae662024cba8544dcd3fd/Library/Homebrew/formulary.rb#L433-L464).

**Comment by apainintheneck** [comment]
What is happening here is that there is an attempt to check that each versioned formula has an unversioned alternative that is not working correctly.

The check occurs here in [`formula_auditor.rb`](https://github.com/Homebrew/brew/blob/f765382cb6d312e3cdebd955a2601998390fe0b0/Library/Homebrew/formula_auditor.rb#L54-L70) and the offending line is the one mentioned by @xrisk above.

```ruby
          Formulary.factory(full_name.gsub(/@.*$/, "")).path
```

This line removes the versioned part of the formula name but `Formula#factory` adds it back because of the `formula_rename.json` file in `Homebrew/Core`. Otherwise you would get some errors.

```bash
~/Downloads ❯❯❯ brew audit postgresql@12                                     ✘ 1
postgresql@12:
  * postgresql@12 is versioned but no postgresql formula exists
Error: 1 problem in 1 formula detected
```

```bash
~/Downloads ❯❯❯ brew audit linux-headers@4.4                                 ✘ 1
linux-headers@4.4:
  * linux-headers@4.4 is versioned but no linux-headers formula exists
Error: 1 problem in 1 formula detected
```

The solution to this seems to be to ignore the lack of an unversioned formula if that happens after an explicit rename (for example `postgresql` was deprecated recently in favor of versioned formula).
