### ISSUE TITLE
Make DevelopmentTools class behavior consistent with compiler wrapper shims and make shims detect versioned compiler formulae

### ISSUE THREAD

**Issue by rkitover** [Homebrew/brew#13780]
### Provide a detailed description of the proposed feature

Following up on discussion in #13768:

```ruby
DevelopmentTools.clang_build_version
```
always return the XCode `llvm` version, while compiler shims such as `/usr/local/Homebrew/Library/Homebrew/shims/mac/super/llvm_clang++` will actually use the tools from the `llvm` formula if it is installed, so it should return that version of `llvm`.

Furthermore, the shims look for the installed `llvm` formula via the `/usr/local/opt/llvm` symlink, and this does not detect versioned `llvm` and `gcc` formulae such as `llvm@13`. This problem could potentially be solved by #13779 if implemented.

### What is the motivation for the feature?

Improving how the brew build toolchain works.

### How will the feature be relevant to at least 90% of Homebrew users?

It would not be, it would be relevant mostly to users on older OSes and others who do source builds instead of using bottles.

### What alternatives to the feature have been considered?

Dunno.

**Comment by rkitover** [comment]
In that case, maybe there should be another method in `DevelopmentTools` for a formula to find out what version of `clang` will actually be used for the build, which is the case with `snappy.rb`, the one I was having problems with. In that particular case, that is the information the formula author was trying to find using that method.

**Comment by rkitover** [comment]
Yes, but `/usr/bin/clang` is not actually want is used to do the build if `llvm` is installed, in that case `/usr/local/opt/llvm/bin/clang` is used, and is a newer version. This is the problem.

**Comment by carlocab** [comment]
I think you misunderstand.

`snappy.rb` checks the version of `/usr/bin/clang` to see if it is too old. If it is too old, then it:
1. adds a dependency on `llvm`; and,
2. switches to using `llvm` instead of `/usr/bin/clang`.

Note, in particular, that (2) above is done only if `/usr/bin/clang` is too old. If it is not, then `/usr/bin/clang` is used, regardless of whether `llvm` is installed.

A different method that does something else would not work for the above.

**Comment by carlocab** [comment]
> How does that happen, is that the `fails_with :clang` block?

It happens in the two lines that call `DevelopmentTools.clang_build_version`.

The `fails_with :clang` code probably doesn't actually have any real function in that formula, but it does help make things more explicit. (i.e. at the moment it's just there for documentation)

> In which case is the `/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang` shim **NOT** used when building a formula?

That compiler shim is used, but that eventually just calls `/usr/bin/clang`.

**Comment by rkitover** [comment]
Ok I see now, `depends_on "llvm" => :build` will invoke with shim `llvm_clang` which will use `/usr/local/opt/llvm/bin/clang`, otherwise it just calls `clang++` from the `PATH`.

And that's another problem here, brew sets its own `PATH` and I can't just put another version of `clang` in it before starting a build.

So what I suggested is wrong, but there is still the problem that the actual check here should be for `clang > 1100 || llvm_clang > 1100`.

**Comment by rkitover** [comment]
Also I was wondering, if llvm is installed, is there any reason to not always use it as opposed to the system clang? Would there be any possible incompatibilities?

**Comment by MikeMcQuaid** [comment]
> And that's another problem here, brew sets its own `PATH` and I can't just put another version of `clang` in it before starting a build.

This is intentional.

> Would there be any possible incompatibilities?

Yes.

Passing on this for now. The main ask here is "provide better support for using a non-system LLVM" for which we'll review PRs but aren't soliciting for work as it's only really relevant on unsupported macOS versions, sorry.

**Comment by rkitover** [comment]
> No, depends_on "llvm" => :build does not result in invoking the llvm_clang shim. Adding a dependency on llvm (:build or otherwise) by itself will still have brew use /usr/bin/clang.

So what in that formula actually causes the shim to be called with `llvm_clang` rather than `clang`, which is definitely what is happening here.

**Comment by rkitover** [comment]
> The main ask here is "provide better support for using a non-system LLVM" for which we'll review PRs but aren't soliciting for work as it's only really relevant on unsupported macOS versions, sorry.

Yes I intend to do the work myself, I am just trying to figure out what work to do by discussing in issues first as that's generally the right way to go about such things.

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/blob/dd1adf690c23bdb4d55387e6786575241eedf7d5/Formula/snappy.rb#L46

**Comment by rkitover** [comment]
I see thank you, I will try to come up with a better proposal for this.

**Comment by rkitover** [comment]
How about adding:

```ruby
DevelopmentTools.llvm_clang_build_version
```
, which would get the llvm version of `/usr/local/opt/llvm` and fall-back to:

```ruby
DevelopmentTools.clang_build_version
```
. This would seem to be more in-line with your conventions for this.

**Comment by carlocab** [comment]
The version of `/usr/local/opt/llvm` is supposed to be given by `Formula["llvm"].version` (unless the user has tampered with `/usr/local/opt/llvm`, but that's not a use-case we intend to support).

We don't need to check `Formula["llvm"].version`, so I don't see how adding `DevelopmentTools.llvm_clang_build_version` would be useful anywhere.

**Comment by rkitover** [comment]
As I said, the problem I want to solve is to make it simpler to check, for example, that `system_llvm > 1100 || brew_llvm > 1100` and take the appropriate action, while still keeping formula code simple. If you don't believe this is a worthwhile goal I will drop this discussion.

**Comment by carlocab** [comment]
But we already know the version of Homebrew `llvm`, and we don't need another method in `DevelopmentTools` to query it.

I also don't see what adding a check for the version of Homebrew `llvm` will add to the formula, unless we are considering the case where the user might have a tampered Homebrew `llvm`. As I've mentioned previously, that's not a use-case we wish to support.

**Comment by rkitover** [comment]
It doesn't necessarily need to be tampered, it may just be pinned. It should also support versioned llvm formulae as I proposed in #13779 (if and in whatever way that gets implemented.)

**Comment by carlocab** [comment]
Avoiding build failures that are a consequence of `brew pin` is not something we wish to support either.

That said: I'm not even sure `brew` will let you install/upgrade something when a pinned dependency is outdated.

> It should also support versioned llvm formulae as I proposed in #13779 (if and in whatever way that gets implemented.)

Adding support for alternative compilers other than the one we use in CI isn't something we wish to add to formulae. See also the output of passing `--cc` to `brew install`.

To be clear: I'm not necessarily opposed to `brew` falling back to a versioned LLVM formula if the unversioned one is not available, but I don't think we need to, or should, add checks for this in formulae. That just creates more code paths that never get tested in CI.

**Comment by carlocab** [comment]
Also, note that `Formula["llvm"].any_version_installed` works even if `llvm` is pinned. We haven't added any checks for this because, as mentioned, it doesn't really make sense for the formula to do this.

**Comment by rkitover** [comment]
> To be clear: I'm not necessarily opposed to brew falling back to a versioned LLVM formula if the unversioned one is not available, but I don't think we need to, or should, add checks for this in formulae. That just creates more code paths that never get tested in CI.

How would you propose implementing this then?

There are two parts here that would need to be addressed,

1. The dependency:

```ruby
depends_on "llvm" => :build
```
, would have to allow being satisfied by a versioned llvm as opposed to only the new one. This would still not match the intended llvm version, but the user could deal with that.

2. The compiler shims would need to be able to find a versioned llvm for `llvm_clang`, possibly by implementing #13779 or manually.

**Comment by carlocab** [comment]
I don't necessarily have an implementation in mind. What I do know if that what's been suggested so far is not suitable.

**Comment by rkitover** [comment]
What's wrong with my last one? Either the formula code has to change a bit or these two things have to change, otherwise it's not possible to do is it?

**Comment by rkitover** [comment]
What about something like:

```ruby
depends_on "clang>=11" => :build 
```
, this would do the necessary checks, checking both the macOS llvm version and any installed versions of llvm and automatically add `ENV.llvm_clang` when needed.

This would make the formula code even simpler, instead of more complex.

If neither this nor my last proposal above would not work, I'll just drop this for now as I don't see any way forward, unless you can suggest one.

I am following up on the build failures in llvm-project by the way.

**Comment by carlocab** [comment]
> What's wrong with my last one? Either the formula code has to change a bit or these two things have to change, otherwise it's not possible to do is it?

The issue is that the current calls to `DevelopmentTools.clang_build_version` are hacks/workarounds for limitations of `fails_with`. I don't want to pile on further hacks on top of the existing ones -- that just makes the problem worse.

The correct implementation would be for `fails_with` to handle compiler selection properly/better, so that we can get rid of all of the calls to `DevelopmentTools.clang_build_version` in the formula and just keep `fails_with`.

> I am following up on the build failures in llvm-project by the way.

Do you have a link to an upstream issue?

**Comment by carlocab** [comment]
> Would you support the `fails_with` method automatically handling the llvm dependency and environment setting for a formula? I could start working on this.

I'm not sure, because we would need to make sure this doesn't break the way existing formulae use `fails_with`. For example, `openblas` and `fftw` use `fails_with :clang` because they expect to compile with `gcc`. We don't want to use the `llvm` formula to compile those.

On the other hand, the formulae that do `fails_with :clang do` typically try to build with `llvm`, since this usually avoids an extra runtime dependency (whereas compiling with `gcc` will introduce a runtime dependency on `gcc`).

If there is a sensible way to automatically handle the llvm dependency while also accounting for the cases above, then that would be useful.

**Comment by carlocab** [comment]
Any changes to `fails_with` also needs to make sure [this code](https://github.com/Homebrew/homebrew-test-bot/blob/ff458141632356c62d0e589a1c107fce552cea7a/lib/tests/formulae.rb#L54-L69) doesn't break:
```ruby
      def install_gcc_if_needed(formula, deps)
        installed_gcc = false
        begin
          deps.each { |dep| CompilerSelector.select_for(dep.to_formula) }
          CompilerSelector.select_for(formula)
        rescue CompilerSelectionError => e
          unless installed_gcc
            test "brew", "install", "gcc",
                 env: { "HOMEBREW_DEVELOPER" => nil }
            installed_gcc = true
            DevelopmentTools.clear_version_cache
            retry
          end
          skipped formula.name, e.message
        end
      end
```

**Comment by rkitover** [comment]
Thank you, I'll do some more research.

**Comment by carlocab** [comment]
One way of handling this might be to check the dependencies for `gcc` first and use that if declared.

Otherwise it should fall back to `llvm`. This may need to wait for LLVM 15 (Homebrew/homebrew-core#106925) so we don't get undesirable linkage with LLVM's libc++.

If `llvm` is not available, it can fall back to a versioned `llvm`. We'll probably want a way to avoid this fallback and fail if we're in CI.

This is probably going to be a complicated project. CC @Bo98 for thoughts here.
