### ISSUE TITLE
PHP 7.1 RC5

### ISSUE THREAD

**Issue by bradynpoulsen** [Homebrew/brew#1378]
Release Candidate 5 is set to be public on the 27th. We have not yet updated to RC4, and I feel it would be pointless to update to it to be out of date in 36 hours. 

This issue is for tracking purposes and I am working on a PR right now

**Comment by MikeMcQuaid** [comment]
> This issue is for tracking purposes and I am working on a PR right now

Please do these on the homebrew/php repo instead.

**Comment by bradynpoulsen** [comment]
@MikeMcQuaid I had just noticed that moved it over 👍
