### ISSUE TITLE
Trying to install hyperspy using pip but needs python 3

### ISSUE THREAD

**Issue by aadrych** [Homebrew/brew#1379]
Hi, 

I recently tried to install python3 on my laptop and I already had python 2.7 installed.  I need to use the latest version of the module hyperspy.  I used pip install hyperspy but I get an error of 
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5t/r_4zs4ls7cx9znxw8wzj01d40000gn/T/pip-build-LXsnsc/hyperspy/
Do you know how I might solve this error?
There was nothing noticeable in brew doctor which may have solved this.
Thanks in advance

**Comment by adidalal** [comment]
Should be `brew install python3`and then `pip3 install hyperspy`, I believe.

**Comment by MikeMcQuaid** [comment]
> Should be brew install python3and then pip3 install hyperspy, I believe.

Let me know if this doesn't work.
