### ISSUE TITLE
autoremove: option to consider build dependencies

### ISSUE THREAD

**Issue by jacktose** [Homebrew/brew#13822]
### Provide a detailed description of the proposed feature

Add an option and environment variable to make `brew autoremove` consider build dependencies and not remove them.
Perhaps `--include-build` and `HOMEBREW_AUTOREMOVE_INCLUDE_BUILD` for consistency with `deps` and `uses`.

Current logic resolves [runtime] and [cask] dependencies. It does not appear to consider other dependencies (build, optional, test, recommended, requirement) and there is no way to adjust that behavior.

[runtime]: https://github.com/Homebrew/brew/blob/93bf9e5ba2c9af5195ec5c1c6eca3a5f2484caba/Library/Homebrew/formula.rb#L1723
[cask]: https://github.com/Homebrew/brew/blob/93bf9e5ba2c9af5195ec5c1c6eca3a5f2484caba/Library/Homebrew/formula.rb#L1746

### What is the motivation for the feature?

Consider a user (me) with several formulae installed that must build from source and have build dependencies. `brew autoremove` removes those build dependencies. The next time the dependent formulae are upgraded or reinstalled, the build dependencies must be reinstalled.

<details>
  <summary>Example</summary>

```
$ brew autoremove -n
==> Would autoremove 3 unneeded formulae:
gpatch
linux-headers@5.15
pkg-config

# Those have no *runtime* dependents:
$ brew uses --installed gpatch
$ brew uses --installed linux-headers@5.15
$ brew uses --installed pkg-config

# But they do have *build* dependents:
$ brew uses --installed --include-build gpatch
ncurses
$ brew uses --installed --include-build linux-headers@5.15
glibc
$ brew uses --installed --include-build pkg-config
libidn2     libnsl      libxml2     ncurses     python@3.10     ruby    whois
```
</details>

This strategy is perhaps appropriately aggressive for minimizing disk space, but the cost is long upgrade/reinstall times with increased risk of breakage. As a user, I'd like control over that tradeoff.
Currently, it's too costly for me, so I don't use `autoremove` at all. If this feature were available, I would set `HOMEBREW_AUTOREMOVE_INCLUDE_BUILD` and `HOMEBREW_AUTOREMOVE`, to achieve a reasonably clean and small installation automagically, without repeated slow and fragile builds.

If this is agreeable, I'm happy to start a PR, but I'll need some help filling out the logic.

### How will the feature be relevant to at least 90% of Homebrew users?

I don't know whether 90% of users run `autoremove`, but this would make it much more trustworthy by causing less breakage and unnecessary building. That might allow `HOMEBREW_AUTOREMOVE` to become a default behavior in the future.

As described above for my motivation, this would enable smaller, cleaner installs without repeated slow and fragile builds. In turn, that makes regular `upgrade`s quicker and more reliable.

### What alternatives to the feature have been considered?

- Never run `autoremove`. Obviously possible but inconvenient.
- Run `autoremove -n` or `leaves -p`, manually investigate list, `uninstall` as appropriate. Very inconvenient and prone to user error.
- Run `autoremove -n`, manually investigate list, put build dependencies in `HOMEBREW_NO_CLEANUP_FORMULAE`. Inconvenient, brittle, and unnecessarily changes `cleanup` behavior.

**Comment by MikeMcQuaid** [comment]
> Consider a user (me) with several formulae installed that must build from source and have build dependencies.

Are these built from source manually or because the formula is lacking a bottle?

> Currently, it's too costly for me, so I don't use `autoremove` at all.

**Comment by carlocab** [comment]
> Are these built from source manually or because the formula is lacking a bottle?

This is from building from source when the bottle is not relocatable and you are not in the default prefix. See #13824.

**Comment by jacktose** [comment]
Correct, that's my main use case. I know the non-default prefix is not fully supported, but I think building generally is supported? In any case, I don't see a downside to having an option here, and I'd like to contribute it.

**Comment by jacktose** [comment]
Drafted #13831 to do this, but still need to test it. I'm a ruby noob, so it'll take a bit.

**Comment by apainintheneck** [comment]
#13839 got merged in a few days ago so this should probably be closed. Autoremove now doesn't suggest removing build dependencies when a formula has been built from source.
