### ISSUE TITLE
`brew shellenv` doesn't work when running from powershell installed as a dotnet tool

### ISSUE THREAD

**Issue by jwosty** [Homebrew/brew#13821]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 93ea8cb2c40e1ef25f1489b0267526bd47bc8030
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b152bb02ffa3d55dbfeee07d8184176f960f2af2
Core tap last commit: 31 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Running homebrew from inside a powershell instance running as a dotnet CLI tool. I have a complicated project setup which had trouble finding the globally-installed powershell, but it could invoke dotnet tools. Basically build script magic for one of my projects.

### What happened (include all command output)?

Errors coming from the `brew shellenv` stuff `profile.ps1`:

```
export: The term 'export' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
export: The term 'export' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
export: The term 'export' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
export: The term 'export' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
export: The term 'export' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
export: The term 'export' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

It appears that homebrew isn't able to detect powershell as powershell when it's run from a dotnet tool, so it resorts to the default, bash. You can confirm this by running `dotnet pwsh`, then starting a sub-shell `bash`, then running `/bin/ps -p "${PPID}" -c -o comm=`, and observing that the output is `dotnet` instead of `pwsh`. `shellenv.sh` expects `pwsh`. Observe that this **does** return `pwsh` when run from powershell installed/run by other means.

### What did you expect to happen?

No errors, and able to invoke commands installed by homebrew

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Install dotnet 6 using the microsoft installer directly: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
2. Run `dotnet tool install --global powershell --version 7.2.5` to add powershell as a dotnet tool (mine is in a local repo, but this is fine for reproduction purposes)
3. Add `$(/opt/homebrew/bin/brew shellenv) | Invoke-Expression` to an appropriate `profile.ps1` file (I used `$Profile.CurrentUserAllHosts` in powershell which evaluates to `~/.config/powershell/profile.ps1`)
4. Start a powershell session like so: `dotnet pwsh`
```

**Comment by carlocab** [comment]
Is it safe to assume that we want `pwsh` when
```
/bin/ps -p "${PPID}" -c -o comm=
```
returns `dotnet`?

**Comment by jwosty** [comment]
In theory, no, because dotnet tools are arbitrary tools (it's the same kind of thing as npm global commands). In practice, maybe, since there might not be any other shells as dotnet tools yet... But that could easily change.

However, a different part of the output of `/bin/ps -p "${PPID}"` may be useful:

```
  PID TTY           TIME CMD
74620 ttys002    0:01.90 dotnet /Users/jwostenberg/.nuget/packages/powershell/7.2.5/tools/net6.0/any/unix/pwsh.dll
```

Perhaps it could identify the pattern `dotnet .*/pwsh.dll`?

**Comment by MikeMcQuaid** [comment]
Given this: I think this is a WONTFIX, sorry.

**Comment by jwosty** [comment]
> Given this: I think this is a WONTFIX, sorry.

Would you accept a PR for this?

**Comment by MikeMcQuaid** [comment]
I'm not sure.

> dotnet .*/pwsh.dll

This feels a lot like an implementation detail that may change in future.

**Comment by jwosty** [comment]
> I'm not sure.
> 
> > dotnet .*/pwsh.dll
> 
> This feels a lot like an implementation detail that may change in future.

Could there at least be some sort of escape hatch that I can use to override homebrew's shell detection? Perhaps an environment variable which, if set, homebrew will use?

**Comment by carlocab** [comment]
I'm open to making `brew shellenv` returning nothing if `/bin/ps -p "${PPID}" -c -o comm=` is `dotnet`, since we don't know what the correct shell to assume there, and assuming one can cause problems.
