### ISSUE TITLE
Need OpenSSL 1.x+ in formula's python virtualenv

### ISSUE THREAD

**Issue by rmb938** [Homebrew/brew#1382]
So I created a formula following https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md but it uses the system python to make the virtual environment. How would I go about getting it to install homebrew's python and using that so I can have the newest OpenSSL available?

**Comment by rmb938** [comment]
I was able to get around the issue by doing the following:

```
class Myformula < Formula

  depends_on "python"

  include Language::Python::Virtualenv

  ...

  def install
    venv = virtualenv_create(libexec, "#{HOMEBREW_PREFIX}/bin/python"
    venv.pip_install resources
    venv.pip_install_and_link buildpath
  end
end
```

Is this the recommended way to do it?

**Comment by MikeMcQuaid** [comment]
CC @tdsmith and @ilovezfs who may know this

**Comment by ilovezfs** [comment]
```
class Foo < Formula
  include Language::Python::Virtualenv

  desc "my foo formula"
...

  depends_on :python

  def install
    virtualenv_install_with_resources
  end
end

**Comment by rmb938** [comment]
That still uses the system python which doesn't have the newest OpenSSL. The only way I was able to get it to work was to use the code in my 2nd comment.

**Comment by tdsmith** [comment]
It should be using the python in $PATH. (If that is not Homebrew's python, it will be if you install with `--build-bottle`, which is how the bottles will be built.)

Otherwise, the behavior you're describing is surprising.

**Comment by rmb938** [comment]
Yup it is in my path if I install python ahead of time, but it is still using the system python.

**Comment by tdsmith** [comment]
Can you provide a `gist-logs` link for your formula and a link to the software you're installing?

**Comment by ilovezfs** [comment]
As far as I can tell `depends_on :python` picks brew's python if it's installed even if you have system python first in the PATH.

**Comment by rmb938** [comment]
Ah sorry I had ```depends_on :python if MacOS.version <= :snow_leopard``` switching it to just ```depends_on :python``` used the python installed from brew.

However is brew python isn't installed it falls back to the system python which has an old OpenSSL.

**Comment by ilovezfs** [comment]
>However if brew python isn't installed it falls back to the system python which has an old OpenSSL.

Yup, that's as I expected. If you want to force brew python you have to use `depends_on "python"` or use `depends_on :python` and build a bottle.

**Comment by rmb938** [comment]
Ok great, thanks! That should probably be noted in the documentation.
