### ISSUE TITLE
Homebrew update results in egrep error

### ISSUE THREAD

**Issue by skyzyx** [Homebrew/brew#13835]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.0-26-g6b6b09d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6b6b09deba3c31f1154b2e6865e32c85bf9f5854
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5f7f87675fd46469df5c9383e858db062fb77ec9
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.nB06TmKal3/org.xquartz:0
HOMEBREW_EDITOR: code -w
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.37.3 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
egrep: warning: egrep is obsolescent; using ggrep -E
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  aws-okta
  docker-compose-completion
  libav
  multitail

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib
  /usr/local/lib/libzmq.3.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: Found Ruby file outside tokengen/tvm-admin-client tap formula directory.
(/usr/local/Homebrew/Library/Taps/tokengen/homebrew-tvm-admin-client/Formula):
  /usr/local/Homebrew/Library/Taps/tokengen/homebrew-tvm-admin-client/brew_download_strategy.rb

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  terraform
  shellcheck
  kubernetes-cli
  pre-commit
  bash-completion
egrep: warning: egrep is obsolescent; using ggrep -E
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I lied above when I said that "I have resolved all warnings from brew doctor and that did not fix my problem." Instead, I resolved all _relevant_ issues. I've had this configuration with these same `brew doctor` results for _years_.

----

Update Homebrew-installed packages to their latest versions.

### What happened (include all command output)?

Updated Homebrew like normal.

```bash
brew update
brew upgrade
```

This resulted in the following message being appended to the end of all sorts of CLI commands.

```plain
egrep: warning: egrep is obsolescent; using ggrep -E
```

This seems to happen not just with Homebrew commands, but I even saw it with this:

```bash
$ sha256sum ffmpeg-5.1.1.tar.xz
95bf3ff8c496511e71e958fb249e663c8c9c3de583c5bebc0f5a9745abbc0435  ffmpeg-5.1.1.tar.xz
egrep: warning: egrep is obsolescent; using ggrep -E
```

I updated Homebrew and Homebrew packages as is typical. I ran this on both my work laptop (Intel) and home machine (Apple Silicon) within minutes of each other. Both started showing this message after updating Homebrew and packages. I, as a developer, have not used `egrep` in years because it was deprecated so long ago in favor of `grep -E`.

### What did you expect to happen?

I expected that I would not end up with this `egrep` error message appended to the results of all of my CLI commands.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
```

**Comment by MikeMcQuaid** [comment]
> I lied above when I said that "I have resolved all warnings from brew doctor and that did not fix my problem." Instead, I resolved all _relevant_ issues. I've had this configuration with these same `brew doctor` results for _years_.

Don't do that, please.

I cannot reproduce this on macOS.

> ```shell
> macOS: 12.6-x86_64
> ```

This version is still in beta. We are unlikely to fix this until it is not.

> ```
> egrep: warning: egrep is obsolescent; using ggrep -E
> ```

```console
$ ggrep -E
zsh: command not found: ggrep
```

**Comment by carlocab** [comment]
What's the output of `which -a egrep`?

**Comment by bayandin** [comment]
It looks like you have `grep` formula installed and `grep`'s `gnubin` added to your PATH. The formula was updated to 3.8 recently (https://github.com/Homebrew/homebrew-core/pull/109559) and started to give this warning (https://www.phoronix.com/news/GNU-Grep-3.8-Stop-egrep-fgrep).

Nonetheless, we don't use `egrep` in `brew`, so probably some other scripts call `egrep` and print this warning. Maybe something that's added to you `~/.zprofile`, `~/.zshrc`.

**Comment by MikeMcQuaid** [comment]
> ```shell
> Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.
> 
> Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
> ```

This is why we have warnings like this.

**Comment by skyzyx** [comment]
@MikeMcQuaid said:

> > I lied above when I said that "I have resolved all warnings from brew doctor and that did not fix my problem." Instead, I resolved all _relevant_ issues. I've had this configuration with these same `brew doctor` results for _years_.
> 
> Don't do that, please.

I'm not going to go back and mess-up my `wkhtmltopdf` installation for something that's likely unrelated. Asking me to do so is an extreme position to take for those of us who are experienced and not noobs.

----

@carlocab asked:

> What's the output of `which -a egrep`?

```bash
$ which -a egrep
/opt/homebrew/opt/grep/libexec/gnubin/egrep
/usr/bin/egrep
```

----

@bayandin said:

> It looks like you have `grep` formula installed and `grep`'s `gnubin` added to your `PATH`.

Yes. Because it helps me write scripts across Mac + Linux when I standardize on the GNU versions across both platforms.

> The formula was updated to 3.8 recently (https://github.com/Homebrew/homebrew-core/pull/109559) and this version of grep started to give this warning (https://www.phoronix.com/news/GNU-Grep-3.8-Stop-egrep-fgrep).
>
> Nonetheless, we don't use egrep in brew, so probably some other scripts call egrep and print this warning. Maybe something that's added to your ~/.zprofile, ~/.zshrc.

I didn't find anything on a first pass, but this is helpful in that it confirms for me where I should be looking. _Thank you._

**Comment by MikeMcQuaid** [comment]
> Asking me to do so is an extreme position to take for those of us who are experienced and not noobs.

I don't think "experienced" and "noobs" is helpful language here.

The `coreutils` doctor warning was actually a pointer that this was your user configuration issue.
