### ISSUE TITLE
Patch git repo reads source .gitignore

### ISSUE THREAD

**Issue by davidchall** [Homebrew/brew#13855]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.1-6-g427f646
ORIGIN: https://github.com/Homebrew/brew
HEAD: 427f6465e95eecef9c8c255a8933f593e7548f33
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 212f97b399c71ff7be125d3e1752081d26d5e4d2
Core tap last commit: 20 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: atom
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.36.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

While authoring a formula, I attempted to [create a patch](https://docs.brew.sh/Formula-Cookbook#creating-the-diff) via `brew install -i --git foo`.

### What happened (include all command output)?

After making my changes, I found `git diff` did not output anything. Digging into this, I discovered the file I edited was contained in the source code's .gitignore file. The git repo that brew creates for patch authoring is reading the source code's .gitignore, and so we cannot create patches on these files.

### What did you expect to happen?

I expect the git repo created by brew for patch authoring to ignore any .gitignore files found in the source code. I think we should be able to create a patch on _any_ file found in the source code.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I can't really provide this, since it involves editing the source code.
```

**Comment by MikeMcQuaid** [comment]
Yes, this is expected behaviour and is how `brew install --git` works.
