### ISSUE TITLE
xargs with 2>&1 returns error code

### ISSUE THREAD

**Issue by SunRunAway** [Homebrew/brew#1385]
### Bug reports:

macOS 10.12.1
```bash
[sunrunaway:~]$ echo a | /usr/bin/xargs > /dev/null 2>&1 ; echo $?
0
[sunrunaway:~]$ echo a | /usr/local/bin/xargs > /dev/null 2>&1 ; echo $?
125
```
![qq20161028-0](https://cloud.githubusercontent.com/assets/867381/19795391/aa30269e-9d0d-11e6-8685-759153a96aa1.png)

**Comment by bfontaine** [comment]
Please report this to the upstream developpers instead: https://www.gnu.org/software/findutils/
