### ISSUE TITLE
What's wrong with the sudo "ERROR"?

### ISSUE THREAD

**Issue by xpendous** [Homebrew/brew#1386]
Every time I sudo brew list/prune/install, whatever, it will occur like this: 

Error: Running Homebrew as root is extremely dangerous. As Homebrew does not
drop privileges on installation you are giving all build scripts full access
to your system. As a result of the macOS sandbox not handling the root user
correctly HOMEBREW_NO_SANDBOX has been set so the sandbox will not be used. If
we have not merged a pull request to add privilege dropping by November 1st
2016 running Homebrew as root will be disabled. No Homebrew maintainers plan
to work on this functionality.

What happened?!!!

**Comment by bfontaine** [comment]
Like the error says you shouldn’t use `brew` with `sudo`.

**Comment by xpendous** [comment]
but some packages did need sudo privilege

**Comment by xpendous** [comment]
but some packages did need sudo privilege

**Comment by vitorgalvao** [comment]
> but some packages did need sudo privilege

Running `sudo brew` and inputting your password when `brew` asks you to are different things. The latter will only use the elevated privileges for select actions, while the latter will do everything as root. *That’s* what you should never do.

**Comment by MikeMcQuaid** [comment]
> but some packages did need sudo privilege

No Homebrew packages should require `sudo` for installation.

**Comment by joshvoydik** [comment]
Thanks for the help y'all.
