### ISSUE TITLE
How do I get latest version of `lftp`?

### ISSUE THREAD

**Issue by dzg** [Homebrew/brew#1387]
Seems `lftp` was relegated to the boneyard, and latest version is 4.6.6.

Is there any way for me to install the latest v 4.7.3?
https://lftp.yar.ru/news.html

Thanks

**Comment by bfontaine** [comment]
According to [this comment in the formula](https://github.com/Homebrew/homebrew-boneyard/blob/c4daf887cf6ef32a7c197edcbe362f8b239046ed/lftp.rb#L4) 4.7.x doesn’t build on OS X/macOS :(

**Comment by dunn** [comment]
Upstream issue: https://github.com/lavv17/lftp/issues/223
