### ISSUE TITLE
Allow tagging 3rd party tap dependency formulas as "dropin" replacements to main ones

### ISSUE THREAD

**Issue by DesWurstes** [Homebrew/brew#13881]
### Provide a detailed description of the proposed feature

Example with ocrmypdf and ffmpeg (ocrmypdf relies on ffmpeg):

Brew removed `--arg`s for formulas in `homebrew-core` and encouraged maintaining the same formulas with args in 3rd party taps. So I installed the forked `homebrew-ffmpeg/ffmpeg` after removing `homebrew-core/ffmpeg`. Now I can't update ocrmypdf because:

```
Error: ffmpeg is already installed from homebrew-ffmpeg/ffmpeg!
Please `brew uninstall ffmpeg` first."
```

So allow a modification to ffmpeg in forks such as:

```rb
class Ffmpeg < Formula
  desc "Play, record, convert, and stream audio and video"
  ...
  dropin "homebrew-ffmpeg/ffmpeg"
```

so that when I try to install anything from homebrew-core that depends on ffmpeg, the forked ffmpeg too will satisfy it.

The error message above was perhaps added to solve the problem where a same named executable is provided by two **entirely different** packages such as in https://github.com/Homebrew/homebrew-core/issues/101674 . for forked formulas of same packages it'd be very useful to tag them as drop-in.

### What is the motivation for the feature?

Anything installed from a 3rd party tap cannot be a dependency to a homebrew-core package, which is very annoying.

### How will the feature be relevant to at least 90% of Homebrew users?

Likely to 90% of those who install from 3rd party taps.

Certainly to 100% of those who produce same packages as in homebrew-core in alternative taps with added options.

### What alternatives to the feature have been considered?

 #5515 but the current approach is not only safer but also it's superior since logically only a brew installed thing can be a dependency for a new brew package to be installed.

**Comment by carlocab** [comment]
This is a request we see every now and then. The answer is the same as in #5515, I'm afraid:

> We don't support replacing dependencies with other random versions.

`homebrew-ffmpeg/ffmpeg` should not name their formula `ffmpeg` if they do not with it to conflict with with `homebrew-core/ffmpeg`.

That's why, for example, the nginx replacement at [homebrew-nginx](https://github.com/denji/homebrew-nginx) is called `nginx-full`.
