### ISSUE TITLE
`brew pr-pull` fails on merged PR

### ISSUE THREAD

**Issue by abitrolly** [Homebrew/brew#13886]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.1-58-g7a14ae6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7a14ae61874770d9ceaee716f90e19c3b5674caa
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 223c426e48926d67a5e8177830761462ca5058d6
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit haswell
Clang: N/A
Git: 2.37.3 => /bin/git
Curl: 7.82.0 => /bin/curl
Kernel: Linux 5.19.8-200.fc36.x86_64 x86_64 GNU/Linux
OS: Fedora release 36 (Thirty Six)
Host glibc: 2.35
/usr/bin/gcc: 12.2.1
/usr/bin/ruby: 3.1.2
glibc: N/A
gcc@11: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to update version of formula in my tap. I want to make binaries with GitHub Action.

https://github.com/abitrolly/homebrew-tap/pull/2

I merged the request without adding `pr-pull` label and now the `pr-pull` command fails in action and locally.
```
brew pr-pull --tap abitrolly/tap 2
```

### What happened (include all command output)?

```
$ brew pr-pull --tap abitrolly/tap 2   
==> Fetching abitrolly/tap pull request #2
==> Using 2 commits from #2
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/git -C /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/abitrolly/homebrew-tap cherry-pick --ff --allow-empty 696357c58cd9c8f27d800a4583df0f441602235f aea8078fa255ec1e270b9358edaa5348bb4d0b43` exited with 0. Here's the output:
Auto-merging Formula/tdu.rb
CONFLICT (content): Merge conflict in Formula/tdu.rb
error: could not apply 696357c... tdu 1.36
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
```

### What did you expect to happen?

`brew pr-pull` to detect that commits are already present and continue.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap abitrolly/tap
brew install tdu
brew pr-pull --tap abitrolly/tap 2
```
```

**Comment by MikeMcQuaid** [comment]
This is expected behaviour. We don't really have a good way to detect this given we squash commits. Will review a PR to address it.

**Comment by abitrolly** [comment]
@MikeMcQuaid the problem is in cherry picking that duplicates commits and will always result in conflict. Using merge or rebase should not have this problem. What is the use case that cherry pick is chosen instead?

**Comment by MikeMcQuaid** [comment]
@abitrolly That's the flow we use for homebrew-core which is the primary user of these sort of scripts.

**Comment by abitrolly** [comment]
@MikeMcQuaid I understand that. The question is why the flow doesn't use merge/rebase?

**Comment by carlocab** [comment]
Not merge: we don't like merge commits

Not rebase: it can leave you with a weird Git state when it fails

**Comment by abitrolly** [comment]
> Not rebase: it can leave you with a weird Git state when it fails

But cherry pick also leaves you with a weird Git state, no?
```
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
```
