### ISSUE TITLE
Add GIT_ASKPASS to the list of non filtered variables

### ISSUE THREAD

**Issue by dudarenko-io** [Homebrew/brew#13897]
### Provide a detailed description of the proposed feature

On our CI we want use custom homebrew and homebrew-core mirrors which are hosted on our private repositories. But currently there is no way to authenticate without saving git credentials on the disks of our machines.
One good solution I found (see [The Vanilla DevOps Git Credentials & Private Packages Cheatsheet](https://coolaj86.com/articles/vanilla-devops-git-credentials-cheatsheet)) is to use GIT_ASKPASS, but this variable is filtered in brew script.
I would like to add this variable to the list of non filtered variables (ENV_VAR_NAMES).

### What is the motivation for the feature?

Provide secure way to authenticate in custom git repos without compromising credentials.

### How will the feature be relevant to at least 90% of Homebrew users?

Unfortunately this feature will be relevant to less than 1% of user I think 🙂 

### What alternatives to the feature have been considered?

- Save git credentials in plain text .git-credentials file
- Store git credentials in macOS Keychain

Refer to [The Vanilla DevOps Git Credentials & Private Packages Cheatsheet](https://coolaj86.com/articles/vanilla-devops-git-credentials-cheatsheet)

**Comment by dudarenko-io** [comment]
I had an experiment with this PR and realise that this approach needs forward another env var if askpass script use it for auth like this:
```
cat ~/.git-askpass
#!/usr/bin/env bash
echo "$GIT_AUTH_TOKEN"
```

**Comment by MikeMcQuaid** [comment]
> I had an experiment with this PR and realise that this approach needs forward another env var if askpass script use it for auth like this:

This is why I think this is a bad fit. There are other methods of Git authorisation that don't require this variable. Passing on this, sorry.

**Comment by dudarenko-io** [comment]
Thanks for reply! 🙂 
Can you tell any method that don't require saving credentials on disk?
We can set core.askpass in git config, but Homebrew won't pass the environment with auth token to askpass script anyway.

Do you think that storing credentials in plain text on non-virtualized CI machines is a good idea?

**Comment by carlocab** [comment]
> We can set core.askpass in git config, but Homebrew won't pass the environment with auth token to askpass script anyway.

Try calling the environment variable `HOMEBREW_GIT_AUTH_TOKEN` instead of just `GIT_AUTH_TOKEN`.
