### ISSUE TITLE
Support `brew cat` when `$HOMEBREW_INSTALL_FROM_API` is set

### ISSUE THREAD

**Issue by kidonng** [Homebrew/brew#13892]
### Provide a detailed description of the proposed feature

When `$HOMEBREW_INSTALL_FROM_API` is set, `brew cat` fetches the content of specified formula from GitHub directly.

### What is the motivation for the feature?

Currently using `brew cat` when `$HOMEBREW_INSTALL_FROM_API` is set results in an error:

```shellsession
$ brew cat go
Error: This command cannot be run while HOMEBREW_INSTALL_FROM_API is set!
```

### How will the feature be relevant to at least 90% of Homebrew users?

`$HOMEBREW_INSTALL_FROM_API` is going to be the default, which will make `brew cat` useless in the current status.

### What alternatives to the feature have been considered?

Use `brew info` to see the GitHub URL to formula, and open the URL manually.

**Comment by Bo98** [comment]
We currently don't ever fetch the formula source when under `HOMEBREW_INSTALL_FROM_API`. But we likely will when adding postinstall support, so this could potentially tie into that.

**Comment by MikeMcQuaid** [comment]
Passing on this for now. This is exactly the type of command we should not be attempting to support for now.
