### ISSUE TITLE
Unable to brew `boost --c++11` in Travis CI

### ISSUE THREAD

**Issue by Malvineous** [Homebrew/brew#139]
_I am rephrasing [this newsgroup question](https://groups.google.com/forum/#!topic/homebrew-discuss/15RMrcSC4gg) as an issue at the request of @apjanke._

I don't have access to a Mac environment but I am hoping to make my code compile on a Mac thanks to [Travis CI](https://travis-ci.org/).

My code requires Boost >= 1.59, so I have configured the Travis build to instruct Homebrew to unlink the preinstalled Boost 1.55, and to install Boost 1.60.  It uses the bottled version of Boost and installs successfully.

Once my own code compiles however, it errors out when it gets to the link stage, with [some `iostream` related errors](https://travis-ci.org/Malvineous/libgamecommon/jobs/125212276).  I believe this is because my code is compiled as C++11 and the Boost bottle is not, so the two are using different C libraries (`libc++` vs `libstdc++`).

I see the `boost` brew contains an option `--c++11` which I presume is to address this issue.  However this causes problems in the Travis CI build environment, as the use of this option results in Boost being compiled from source, and the [build terminates after 10 minutes](https://travis-ci.org/Malvineous/libgamecommon/jobs/125306251) with no console output.

I imagine I could solve my problem by having a `boost --c++11` bottle which would install significantly faster than compiling from scratch, however to do this without access to OSX could be tricky. I am guessing I'd have to edit the `boost` brew to make `--c++11` the default, then create a Travis CI build process that would build this custom brew into a bottle, then upload it somewhere that I could then retrieve in my original build process (by downloading the custom bottle file and passing it to `brew install`.)  However presumably if I tried this, I'd still run into the same issue, which is that `boost` cannot be brewed in Travis CI because there's no output for more than 10 minutes.

Is there any way to make `brew install boost --c++11` more verbose so that it won't be terminated by the 10 minute timeout?

**Comment by apjanke** [comment]
I think this may be a simple fix: just add `--verbose` to the `brew install boost --c++11` command, which OP can do because they're running their own Travis instance instead of using BrewTestBot.

But it does bring up an issue with `brew test-bot` which we may have to address: any long-running build for a dependency which is built with non-default options may cause Travis builds to time out under `test-bot` as well, because we don't use `test-bot --verbose` on Jenkins or (IIRC) Travis.

**Comment by Malvineous** [comment]
Oh thanks, that was it!  Now it gives me errors that the log is too long, but I can deal with those and it finishes compiling successfully.  Many thanks :-)

**Comment by xu-cheng** [comment]
Try `HOMEBREW_VERBOSE_USING_DOTS=1 brew install --verbose ...`. `HOMEBREW_VERBOSE_USING_DOTS` is an undocumented variable we used in `brew test-bot` for Travis CI.

**Comment by UniqMartin** [comment]
By default, the `boost` formula builds four different versions of the libraries: static single-threaded, static multi-threaded, shared single-threaded, and shared multi-threaded. It's rare that all of them are needed. In practice, the “shared multi-threaded” variant is sufficient for most projects. Thus a really simple way to drop the build time to about a fourth of the full build time is to install `boost` using

```
brew install boost --c++11 --without-single --without-static
```

The other suggestions regarding `HOMEBREW_VERBOSE_USING_DOTS=1 brew install --verbose <…>` still apply.

**Comment by mikemcquaid** [comment]
A better fit for your project may be just vendoring the parts of Boost you need rather than relying on system libraries.

**Comment by apjanke** [comment]
> A better fit for your project may be just vendoring the parts of Boost you need rather than relying on system libraries.

This does sound like the best approach, based on what we know. ("Vendoring" when you roll your own binary bottle or tarball and include it as part of your package's distribution.) That'd save you 10+ minutes on every Travis run (since you don't care about testing the compilation of `boost` itself), allowing you to test and iterate faster. And it would allow your package to peacefully coexist with the default `boost` installation.

**Comment by Malvineous** [comment]
Thanks for all the help!  Along these lines I am attempting to see whether I can create a GitHub project with a Travis build process to run under OSX, which will compile Boost as recommended above, then bottle it.  If I can then "deploy" that bottle from Travis as a GitHub release, then it will mean my other builds can just download and install that bottle from GitHub at the start of each build.  Hopefully that will work!

**Comment by mikemcquaid** [comment]
Boost will not build under Travis CI. IT takes too long. As mentioned before: I'd strongly recommend vendoring the bits of Boost you need in your project rather than spending an hour building stuff you 90% don't need. Not a Homebrew bug at this point anyway but good luck.

**Comment by Malvineous** [comment]
Well just to finalise this, I have managed to get it to build under Travis.  It takes about half an hour, but as you only have to do that once to create the custom bottle I don't think it's too bad.  The other projects can just download and use the bottle.  I [put the bottle-creation Travis script in a repo](https://github.com/Malvineous/travis-homebrew-bottle) in case anyone else might find such a thing useful in the future.
