### ISSUE TITLE
Linux Homebrew reports developer tools not installed when they are

### ISSUE THREAD

**Issue by stvhay** [Homebrew/brew#13902]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.2-8-g2cacd04
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2cacd04743ec7ccde9c013f865171216468d9462
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c5e56eeb82dc468a9350333fd2441ff5a8d683bc
Core tap last commit: 34 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 1
HOMEBREW_TEMP: /var/services/homes/hays/tmp
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: single-core 64-bit unknown_0x6_0x5c
Clang: N/A
Git: 2.33.0 => /bin/git
Curl: 7.79.1 => /bin/curl
Kernel: Linux 4.4.180+ x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.35
/usr/bin/gcc: N/A
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc@12: 12.2.0
xorg: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: No developer tools installed.
Install Clang or run `brew install gcc`.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Just use homebrew without warnings.

I have a full gcc toolchain in my PATH at .local/bin, as well as a brew-installed gcc. Neither of these register with linux homebrew.

### What happened (include all command output)?

See above.

### What did you expect to happen?

I expected homebrew to detect the gcc installation.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
0. Begin with a machine with no toolchain.
1. On a separate machine, compile gcc.
2. Create a tarball and unzip it in .local/
3. Set your PATH and LD_LIBRARY_PATH variables to include .local/bin, .local/{lib,lib64} respectively
4. Run the Homebrew installer.
```

**Comment by stvhay** [comment]
> /usr/bin/gcc: N/A
> /usr/bin/ruby: N/A

It seems to be looking in a very specific place for these files. Maybe it should be searching the PATH?

**Comment by carlocab** [comment]
This is by design, sorry. We don't want to pick up just any executable that happens to be named `gcc` in `PATH`.

**Comment by ogerardin** [comment]
> ```shell
> gcc@12: 12.2.0
> ```

Looks like gcc@12 is available from Homebrew itself, why not consider that one? 
I think `brew doctor`'s message is not 100% accurate:

```
Warning: No developer tools installed.
Install Clang or run `brew install gcc`.
```

1. Developer tools are installed since gcc@12 is there
2. Running `brew install gcc` won't create `/usr/bin/gcc`

What is the correct way to handle this case, just create a link `/usr/bin/gcc` to wherever gcc-12 is?
