### ISSUE TITLE
Automate deprecating and disabling formulae

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#13904]
### Provide a detailed description of the proposed feature

We should have automation that deprecates and/or disables formulae that are no longer maintained. I suggest deprecating formulae once active support ends and disabling them when security/critical support ends.

For software that only declare a binary support status (i.e. supported/not supported), they can be deprecated three months before support ends and disabled after that.

The above assumes, of course, that these formulae have no dependents.

One way of doing this would be by querying the API at https://endoflife.date.

### What is the motivation for the feature?

Less manual work will need to be done for tracking deprecations.

### How will the feature be relevant to at least 90% of Homebrew users?

We want to avoid users installing outdated software. At the very least, we don't want to be responsible for their doing so.

### What alternatives to the feature have been considered?

Continue the manual deprecation and disabling of formulae.

**Comment by yotsutose** [comment]
Hello, nice to meet you. 
I would love to have this feature. I wanna try to impliment the feature.

Do you want to have a new command ? Or implement it in the commands we have now?
I'm planning Homebrew would check version by using API and indecate it like "outdated" command .

**Comment by MikeMcQuaid** [comment]
There does seem to be at least some automation around deprecation/removing disabled formulae now so: closing.
