### ISSUE TITLE
Homebrew does not respect CURL_CA_BUNDLE environment variable

### ISSUE THREAD

**Issue by DE0CH** [Homebrew/brew#13911]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8b195cc64a29595797651720ebb2ea09affb682
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 206b0381b058735431b0f65dba768fa4849db334
Core tap last commit: 56 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_BROWSER: /vscode/vscode-server/bin/linux-x64/74b1f979648cc44d385a2286793c226e611f59e7/bin/helpers/browser.sh
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit unknown_0x6_0x8c
Clang: N/A
Git: 2.30.2 => /usr/bin/git
Curl: 7.74.0 => /usr/bin/curl
Kernel: Linux 5.19.8-arch1-1 x86_64 GNU/Linux
OS: Debian GNU/Linux 11 (bullseye) (bullseye)
Host glibc: 2.31
/usr/bin/gcc: 10.2.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc@12: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I have a system for which I do not have sudo access that installs the ca bundle at `/etc/pki/tls/certs/ca-bundle.crt` but curl by default reads from `/etc/ssl/certs/ca-certificates.crt`. So I set the environment variable `CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt` to tell curl the place of the ca bundle. 

In order to more clearly illustrate the problem, I replicated the relevant part of the system in a docker container running debian bullseye on own computer. 

### What happened (include all command output)?

curl download failed because it does not know that I set the CURL_CA_BUNDLE environment variable. 
```
$ brew install gcc
==> Downloading https://ghcr.io/v2/homebrew/core/linux-headers/5.15/manifests/5.15.57-1
curl: (77) error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs

Error: gcc: Failed to download resource "linux-headers@5.15_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/linux-headers/5.15/manifests/5.15.57-1
```

### What did you expect to happen?

I expected the brew command to run without problem. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ sudo mkdir -p /etc/pki/tls/certs # create directory to prepare for copying
$ sudo cp /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt # copy the ca bundle
$ sudo mv /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt.backup # make curl unable to find the default ca bundle
$ export CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt # tell curl where to find ca-bundle
$ brew install gcc # install something with homebrew
```

**Comment by carlocab** [comment]
This is intended behaviour.

If you need to specify an alternative CA bundle, set `HOMEBREW_CURLRC` and add the `--cacert` flag to your `.curlrc`.

**Comment by DE0CH** [comment]
I see. Thanks. May I know why this is the intended behaviour?

**Comment by carlocab** [comment]
Environment variables leaking into the build environment can affect or even break builds. To avoid that, we remove all but the most necessary environment variables into `brew` invocations.
