### ISSUE TITLE
Consider downloading archives instead of cloning homebrew-core and homebrew-cask

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [Homebrew/brew#13915]
### Proposal
I suggest that instead of performing a full clone of homebrew-core and homebrew-cask, when tapping them, we download the ZIP file GitHub provides for the master branch of each repository and then extract them to the right place.

I have no insight about the internal infrastructure of GitHub, so I don't know if this affects them as much as shallow clones do. But I strongly believe that's not the case, as the ZIP file should only changes between commits, thus can be easily cached, not requiring additional computation for each user that downloads it, unlike shallow clones.

### If Accepted
This change implies we no longer can perform a simple `git pull` to update these taps. We will actually need to download the ZIP file from GitHub, extract it, and replace the old tap folder with the new one. To decide whether or not the local tap is outdated, we could store the commit hash in the filesystem and check it against the origin's master branch.

### What is the motivation for the feature?

Since #9383, brew no longer shallow clones homebrew-core and homebrew-cask based on a request from GitHub. This resulted in two side effects: the initial clone of these taps takes significantly longer and a lot of space is wasted on disk by keeping the entire commit history of these repositories.

### How will the feature be relevant to at least 90% of Homebrew users?

Right now, performing a `git clone` of homebrew-core requires a 515.5 MB download and homebrew-cask a 317.43 MB download. On disk, the space taken by homebrew-core is 618.8 MB and by homebrew-cask is 372.9 MB.

After this change, homebrew-core would only require a 8.3 MB download and homebrew-cask a 2.3 MB download. When extracted, homebrew-core would only take 15 MB and homebrew-cask 3.2 MB.

The downside of this approach is that, when updating these taps, we would have to re-download the entire archive, not only the changes like `git pull`. But the archives are small and I think it's worth the time and disk savings.

### What alternatives to the feature have been considered?

If GitHub doesn't like this approach, then we can cache the ZIP files ourselves by creating a GitHub Actions Workflow that runs for each commit on the master branch, creates an archive with the contents of the branch at that commit, and uploads it to GitHub Packages, just like we do for Homebrew Bottles. I'm extremely confident that this will have no impact on GitHub, given the heavy use of GitHub Packages we already do.

**Comment by carlocab** [comment]
If you'd like to use Homebrew without cloning homebrew/core and/or homebrew/cask, set
```
HOMEBREW_INSTALL_FROM_API
```
See `man brew` for details.

**Comment by t0rr3sp3dr0** [comment]
I know about this env var and use it on CI jobs. But I wasn't thinking about this use case when I wrote this issue, I was thinking about people using brew on their Macs. 

I personally don't have a lot of free disk space on my computer and I know a lot of people suffer from the same problem because Apple charges a lot for storage upgrade on Macs. When you run out of space, it is frustrating to see that you would have a couple more gigabytes of free space if wasn't for the space wasted by brew taps. My proposal could even be extended to all other taps, but I would start with core and cask.

The alternative, with the unmanaged taps, is very painful to maintain because `brew update` doesn't work.

I'm willing to invest some time and implement this feature on brew. I just want to discuss about it before submitting a PR with changes that might not be accepted.

@carlocab, I ask you to reconsider this issue. I think it would be beneficial for everyone using brew.

**Comment by carlocab** [comment]
What advantages does your alternative approach offer over `HOMEBREW_INSTALL_FROM_API`?

**Comment by MikeMcQuaid** [comment]
Yes, `HOMEBREW_INSTALL_FROM_API` can do all of this.

**Comment by t0rr3sp3dr0** [comment]
@carlocab and @MikeMcQuaid, `brew update` doesn't work with `HOMEBREW_INSTALL_FROM_API`. I know you can manage the taps by yourself, but that's what I've called "very painful to maintain". My proposal is to modify Homebrew and have it support tap updates without relying on a local git repository.

Just to be clear, I'm not think about CI at this point, because it's relativily simple to use `HOMEBREW_INSTALL_FROM_API` on ephemeral environments. But that's not the same for humans using brew on their personal computers.


### Example
For the sake of simplicity, I'm running these commands on a Ubuntu container but running them on a Mac would lead to the same result.

1. Install Homebrew with `HOMEBREW_INSTALL_FROM_API`.
```bash
apt update
apt install -y curl git unzip

export HOMEBREW_INSTALL_FROM_API=1
export NONINTERACTIVE=1
bash -c "$(curl -LSfs https://github.com/Homebrew/install/raw/HEAD/install.sh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
```

2. Download the tap archive from GitHub and extract it on the right place.
```bash
export TAP='homebrew/homebrew-core'
export DIR="$(brew --repo "${TAP}")"
rm -fR "${DIR}"
mkdir -p "${DIR}"
curl -Lo "${DIR}.zip" "https://github.com/${TAP}/archive/HEAD.zip"
unzip "${DIR}.zip" -d "${DIR}"
mv "${DIR}/$(basename "${TAP}")-"*/* "${DIR}"
rm -fR "${DIR}/$(basename "${TAP}")-"*
```

3. Invoke `brew update`.
```bash
brew update
```

4. Homebrew sees that the tap is not a Git repo and clones the entire repository again. Now we returned to the original problem, 500 MB of unused data stored in the local disk and a long wait for the full clone to finish.
```text
Initialized empty Git repository in /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/.git/
remote: Enumerating objects: 1275312, done.
remote: Counting objects: 100% (1051/1051), done.
remote: Compressing objects: 100% (466/466), done.
Receiving objects: 100% (1275312/1275312), 519.11 MiB | 631.00 KiB/s, done.
remote: Total 1275312 (delta 623), reused 999 (delta 585), pack-reused 1274261
Resolving deltas: 100% (879406/879406), done.
From https://github.com/Homebrew/homebrew-core
 * [new branch]              master     -> origin/master
Updating files: 100% (6628/6628), done.
HEAD is now at 4d9c5d1480e circleci: update 0.1.21289 bottle.
Already up-to-date.
```

5. Alternatively, try to shallow clone the taps manually (I know this doesn't work by design).

```bash
export TAP='homebrew/homebrew-core'
export DIR="$(brew --repo "${TAP}")"
rm -fR "${DIR}"
mkdir -p "${DIR}"
git clone --depth 1 "https://github.com/${TAP}" "${DIR}"
```

6. Invoke `brew update`.
```bash
brew update
```

7. Homebrew fails as expected, giving the user no alternative to not have disk space wasted.
```text
Error: 
  homebrew-core is a shallow clone.
To `brew update`, first run:
  git -C /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
This command may take a few minutes to run due to the large size of the repository.
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!
```

**Comment by Rylan12** [comment]
> `brew update` doesn't work with `HOMEBREW_INSTALL_FROM_API`.

By this do you mean "`brew update` does not update my homebrew/core tap when I have `HOMEBREW_INSTALL_FROM_API` set"? If so, that is intentional. The whole point of `HOMEBREW_INSTALL_FROM_API` is to not spend time updating homebrew/core.

Can you elaborate on why `HOMEBREW_INSTALL_FROM_API` does not solve your problem? Third-party taps are unlikely to be nearly as large as homebrew/core and homebrew/cask so I don't think it's a priority of ours to add an alternative way for them to be used since the benefits would be quite small.

**Comment by t0rr3sp3dr0** [comment]
So, it's not that I don't want to have the core and cask taps locally. I just don't want to have a full history of these repository on my local disk. I still want to have the taps updated frequently, but I don't need to keep old versions of it as git does. The objective is to have just the most recent files of these repositories and nothing else.

**Comment by t0rr3sp3dr0** [comment]
Maybe this helps you see the improvements made by this proposal.

### Advantages of the new approach

1. Disk space used by homebrew-core and homebrew-cask is reduced from 991.7 MB to 18.2 MB, a 98% decrease.

2. Consumes a lot less bandwidth when compared with a full clone, only 10.6 MB of downloaded data instead of 832.93 MB, a 98% decrease when downloading both homebrew-core and homebrew-cask.

3. Takes just a few seconds to download, from over 15min to less than 1min. It's important to notice that network is just part of the problem of a full clone, Git has a hard time dealing with repositories of this magnitude and speends a lot of time computing stuff after receiving objects. When resolving deltas, it peaked arround 160% CPU usage and took 10min to complete just this portion of the clone process. So `git clone` is not only I/O Bound but also CPU Bound, even if you have a good Internet connection, it may take a while for the clone to complete depending of your processor. The time of a full clone varies a lot depending on the conditions, so I won't give you an exact decrease expectancy, but `git clone` will always be significantly slower when compared to just downloading an archive.

4. Initially, this approach can be used just for homebrew-core and homebrew-cask, but nothing prevents us from also using it for other taps, maybe all taps.

### Test contitions

1. I have a 1 Gbps Internet link, the download never went faster than 8 Mbps. I don't know if it is a GitHub limitation or just a bad link between my ISP and GitHub.

2. I'm using a MacBook Air (13-inch, 2017) - 1.8 GHz Dual-Core Intel Core i5 - 8 GB 1600 MHz DDR3.

3. I've performed these tests directly on macOS, no Ubuntu container this time.

**Comment by Rylan12** [comment]
I guess the question is really "why do you need the files"?

Very few users care about having the files locally, so it doesn't seem worth it to add support for something like this when most are perfectly content with the current `HOMEBREW_INSTALL_FROM_API` implementation.

I think it's reasonable for us to say that if you need to have the files locally for whatever reason, you can either not set `HOMEBREW_INSTALL_FROM_API` and use the complete git repo, or are responsible for managing some other method of doing it on your own.

**Comment by t0rr3sp3dr0** [comment]
I understand this may not be a priority for you, but I'm willing to implement this myself if you are ok with it. Just want to know if this kind of patch would be acceptable before starting to work on it.

**Comment by MikeMcQuaid** [comment]
Yes, we will not accept a PR for this, sorry.

**Comment by carlocab** [comment]
Maybe I'm misunderstanding you, so forgive me if I have, but I think you seem to misunderstand what `HOMEBREW_INSTALL_FROM_API` does.

The reason I say this is because all the advantages you've listed below, with the possible exception of the fourth, are only advantages of your approach over the old `brew update` mechanism.

Crucially, these are **not** advantages of your proposal over `HOMEBREW_INSTALL_FROM_API`, because using the env variable has these benefits as well:

> ### Advantages of the new approach
> 
> 
> 
> 1. Disk space used by homebrew-core and homebrew-cask is reduced from 991.7 MB to 18.2 MB, a 98% decrease.
> 
> 
> 
> 2. Consumes a lot less bandwidth when compared with a full clone, only 10.6 MB of downloaded data instead of 832.93 MB, a 98% decrease when downloading both homebrew-core and homebrew-cask.
> 
> 
> 
> 3. Takes just a few seconds to download, from over 15min to less than 1min. It's important to notice that network is just part of the problem of a full clone, Git has a hard time dealing with repositories of this magnitude and speends a lot of time computing stuff after receiving objects. When resolving deltas, it peaked arround 160% CPU usage and took 10min to complete just this portion of the clone process. So `git clone` is not only I/O Bound but also CPU Bound, even if you have a good Internet connection, it may take a while for the clone to complete depending of your processor. The time of a full clone varies a lot depending on the conditions, so I won't give you an exact decrease expectancy, but `git clone` will always be significantly slower when compared to just downloading an archive.
> 
> 
> 
> 4. Initially, this approach can be used just for homebrew-core and homebrew-cask, but nothing prevents us from also using it for other taps, maybe all taps.

**Comment by t0rr3sp3dr0** [comment]
@carlocab, you are completely right. I though `HOMEBREW_INSTALL_FROM_API` was an installation only directive that would prevent the installer from tapping homebrew-core ahead of time, but you would still have to provide the tap files under `$(brew --repo homebrew/core)` at some point for Homebrew to work.

I was mislead because I installed Homebrew with `HOMEBREW_INSTALL_FROM_API`, but was executing `brew install` and `brew search` without the env var set, making Homebrew clone homebrew-core when running these command. That's why I though you would need to have a local copy of the repository anyway and was advocating for the local copy to be just a snapshot and not a full clone.

Sorry about the misunderstanding and the time wasted here… I appreciate your attention!

**Comment by carlocab** [comment]
Ok, glad that's been cleared up.

Please read the responses you've been given more carefully in the future, as I find it hard to see where these could have been clearer:

> If you'd like to use Homebrew without cloning homebrew/core and/or homebrew/cask, set
> 
> ```
> HOMEBREW_INSTALL_FROM_API
> ```
> 
> See `man brew` for details.


> Yes, `HOMEBREW_INSTALL_FROM_API` can do all of this.

This is the description for `HOMEBREW_INSTALL_FROM_API` in `man brew`:
```
       HOMEBREW_INSTALL_FROM_API
              If set, install formulae and casks in homebrew/core and homebrew/cask taps using Homebrew´s API instead of needing
              (large, slow) local checkouts of these repositories.
```
