### ISSUE TITLE
HOMEBREW_PREFIX being produced with an extra "/"

### ISSUE THREAD

**Issue by ParamagicDev** [Homebrew/brew#13919]
### `brew config` output

```shell
HOMEBREW_PREFIX="//opt/homebrew"


(Will update with full trace in the morning)
```

### `brew doctor` output

```shell
Improper HOMEBREW_PREFIX

expected "/opt/homebrew" 
got "//opt/homebrew"
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Just trying to run brew normally

### What happened (include all command output)?

brew has the wrong prefix when running "brew config" and running the "shellenv" eval.

### What did you expect to happen?

Expected "/opt/homebrew" to be the prefix

### Step-by-step reproduction instructions (by running `brew` commands)

This is on a brand new Mac M1 with a fresh install from the docs.

Currently my workaround is just manually setting the HOMEBREW_PREFIX in the brew binary here:

https://github.com/Homebrew/brew/blob/4441452f4e7a7efdd5ae8cc98466d8cf6fa410ab/bin/brew#L53

```shell
HOMEBREW_PREFIX="/opt/homebrew"
```

**Comment by carlocab** [comment]
The output of `brew config` and `brew doctor` is required for all bug reports to this repository.

We can reopen this once you've provided the requested information.

**Comment by Bo98** [comment]
This is typically caused by a misconfigured $PATH, so check that.

**Comment by ParamagicDev** [comment]
@Bo98 nailed it!

This is what I had in my `.zshrc`

```shell
  export PATH="/$(brew --prefix)/bin:$PATH"
 ```
