### ISSUE TITLE
Xcode 8.1 is not pre-release software

### ISSUE THREAD

**Issue by chmaynard** [Homebrew/brew#1391]
I just installed Xcode 8.1 via the Mac App Store. However, Homebrew reports that I'm using a pre-release version:

    $ brew doctor
    ...
    Warning: You are using a pre-release version of Xcode.
    You may encounter build failures or other breakages.
    Please create pull-requests instead of filing issues.
    ...

**Comment by bfontaine** [comment]
Thanks; see #1384.
