### ISSUE TITLE
Concurrent Downloading when upgrading

### ISSUE THREAD

**Issue by BlackAsLight** [Homebrew/brew#13924]
### Provide a detailed description of the proposed feature

When you do `brew upgrade` instead of it downloading each thing individually, it downloads them all concurrently to try and speed up the upgrading process.

### What is the motivation for the feature?

It takes quite a long time to upgrade when you're waiting for 22 downloads to happen.

### How will the feature be relevant to at least 90% of Homebrew users?

They won't need to wait as long for their software to be upgraded.

### What alternatives to the feature have been considered?

none

**Comment by gromgit** [comment]
Asked and rejected before: https://github.com/Homebrew/brew/issues/13064

**Comment by carlocab** [comment]
This would multiply Homebrew's bandwidth usage by the average number of concurrent downloads allowed, which wouldn't be great for GitHub's servers, so this isn't something we're interested in implementing for everyone in `brew`. Sorry!

**Comment by BlackAsLight** [comment]
Sad but understandable

**Comment by carlocab** [comment]
Note that `brew` supports writing your own external commands, so you could probably write a `brew parallel-fetch` command if you really wanted to.

It's just not something we want to make readily available to all our users to avoid slamming GitHub's servers.
