### ISSUE TITLE
Error occurs when reinstalling after brew remove

### ISSUE THREAD

**Issue by ghdwlsgur** [Homebrew/brew#13932]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: d5b6b068c15a8df60f0f5e34a4ca80dcf82c48e3
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 86ac48865b7d99af728dbf1c7bb9b680daf50ab8
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/nvim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.37.3 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 14.0
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  fasd

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.9/greenlet/greenlet.h
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew remove govpn 
brew tap ghdwlsgur/govpn
brew install govpn

Whenever I run the above command, the following error occurs.
I should have reinstalled or uninstalled when uninstalling, but I wonder if it's an error that occurred by removing.

### What happened (include all command output)?

==> Downloading https://github.com/ghdwlsgur/govpn/releases/download/v0.1.6/govpn_0.1.6_Da
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset
                                                                           0.3%curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

Error: govpn: Failed to download resource "govpn"
Download failed: https://github.com/ghdwlsgur/govpn/releases/download/v0.1.6/govpn_0.1.6_Darwin_x86_64.tar.gz

### What did you expect to happen?

I just wanted to reinstall. 
The same error occurred when reinstalling after removing the other libraries distributed with git in the same way.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew remove govpn 
brew tap ghdwlsgur/govpn
brew install govpn
```

**Comment by carlocab** [comment]
Are you able to download the source using `curl`? e.g.
```
curl -OL https://github.com/ghdwlsgur/govpn/releases/download/v0.1.6/govpn_0.1.6_Darwin_x86_64.tar.gz
```
?

**Comment by ghdwlsgur** [comment]
curl -OL https://github.com/ghdwlsgur/govpn/releases/download/v0.1.6/govpn_0.1.6_Darwin_x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 13 5986k   13  831k    0     0  40306      0  0:02:32  0:00:21  0:02:11     0
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)


Same error occurs. 😭😭😭

**Comment by carlocab** [comment]
I don't think this is a bug in `brew` then. It may be your connection, something wrong with your `curl`, or even something wrong with GitHub's servers.

None of those are things we can help you with. Sorry!
