### ISSUE TITLE
[Homepage] Add a "top ten most recent updates" entry on the homepage somewhere

### ISSUE THREAD

**Issue by rubyFeedback** [Homebrew/brew#13956]
### Provide a detailed description of the proposed feature

I would like to propose that the homepage at:

https://brew.sh/

Adds a "ten most recent packages updated".

### What is the motivation for the feature?

I would like to know what is new, without necessarily having to go to github. The homepage of brew is also nicer to read and more stylish. Right now github has more information though.

### How will the feature be relevant to at least 90% of Homebrew users?

Well, 90% is usually hard, but I believe showing a simple box with "last 10 recipes updated" can benefit many users. It can flow as a div tag on the right perhaps, or just be positioned in the middle somewhere (perhaps at the bottom or top or close to it).

### What alternatives to the feature have been considered?

We can probably get the information from github and the changes made, but this is a bit tedious to do IMO. So having this on the homepage would be better, IMO.

PS: I was not sure whether to report this here or some other sub-page or something, so I simply went for the main brew github trracker as-is, sorry if that was the wrong tracker to use. ~~~~

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this. You can do this yourself with `brew log`.
