### ISSUE TITLE
Issue with ruby

### ISSUE THREAD

**Issue by miccal** [Homebrew/brew#1396]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I am having a very strange issue with `rubocop-cask`. See a discussion [here](https://github.com/vitorgalvao/tiny-scripts/issues/50).

I have uninstalled and reinstalled `rubocop-cask`, but using the `gem` fails. See below:
```
-bash-4.4.0- /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks [> gem uninstall rubocop-cask && gem install rubocop-cask
Successfully uninstalled rubocop-cask-0.10.4
Fetching: rubocop-cask-0.10.4.gem (100%)
Successfully installed rubocop-cask-0.10.4
Parsing documentation for rubocop-cask-0.10.4
Installing ri documentation for rubocop-cask-0.10.4
Done installing documentation for rubocop-cask after 0 seconds
1 gem installed
-bash-4.4.0- /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks [> brew cask style --fix aquaterm
==> Installing or updating 'rubocop-cask' gem
ERROR:  Could not find a valid gem 'rubocop-cask' (~> 0.10.4), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/specs.4.8.gz)
Error: Failed to install/update the 'rubocop-cask' gem.
```

<details><summary>Output of `brew doctor`</summary>

```
-bash-4.4.0- /Users/$USER [> brew doctor
Your system is ready to brew.
```
</details>

<details><summary>Output of `brew config`</summary>

```
-bash-4.4.0- /Users/$USER [> brew config
HOMEBREW_VERSION: 1.0.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a7317aa8ff5f12067eb65e529a13490bc69deda
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eee3b0a9917da77fec3734311ab80ca95863126b
Core tap last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1_2/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.12.1-x86_64
Xcode: N/A
CLT: 8.1.0.0.1.1476494586
X11: 2.7.10 => /opt/X11
```
</details>

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting) (specifically providing `brew doctor` and `brew config` output).

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by miccal** [comment]
Added, sorry.

**Comment by MikeMcQuaid** [comment]
What does `env | grep -i ruby` and `env | grep -i gem` output? Does this work if you use a non-Homebrew Ruby? Thanks!

**Comment by MikeMcQuaid** [comment]
Also: what country are you in and are you using a proxy server?

**Comment by miccal** [comment]
I am in Australia, I am not having this issue on another machine, and the commands `env | grep -i ruby` and `env | grep -i gem` do not output anything.

I'm sorry, but I don't know what you mean by "Does this work if you use a non-Homebrew Ruby?"

Thanks!

**Comment by miccal** [comment]
After further investigation I made the problem much worse, so reinstalled macOS and the issue has been resolved. Thanks for your help @MikeMcQuaid.
