### ISSUE TITLE
non-expert method to install a specific version of a package

### ISSUE THREAD

**Issue by elenzil** [Homebrew/brew#13973]
### Provide a detailed description of the proposed feature

something like `brew install <thing> --version <version>`

### What is the motivation for the feature?

Scouring the internet for rumors of how to install an older version of a package leads to a couple overly baroque approaches which all require a level of Brew-expertise beyond what this user is ready to develop.  In particular, I want an older version of swiftlint. I don't want to understand Brew's implementation details.

### How will the feature be relevant to at least 90% of Homebrew users?

I guess if it's not in there already perhaps it's not relevant to a large portion of Homebrew users.
Surprising.

### What alternatives to the feature have been considered?

1. painfully finding the versioned 'raw' .rb file for the specific version.
(this required a full local clone of the github repo, because the files apparently have too much history for github to show)

2. brew tap-new, extract, etc.   this seemed hopeful but failed due to MacOS / XCode Tools version issues.

**Comment by participator** [comment]
I ran into this issue last week when attempting to install the older version of certbot v1.22.0 with brew.

**Comment by MikeMcQuaid** [comment]
This is intentionally unsupported.

`brew extract` is the only flow here.
