### ISSUE TITLE
Package file that list all apps install by Brew

### ISSUE THREAD

**Issue by participator** [Homebrew/brew#13974]
### Provide a detailed description of the proposed feature

Similar to many other package managers (package.json for npm, Gemfile for ruby, requirements.txt for pip, and etc), brew should be able to save a list of a user's downloaded applications to a file.  This file would then be able to be easily shared across machines and it would allow simple app downloads including the same version.

### What is the motivation for the feature?

This will enable machine setup without forcing users to write custom scripts.

### How will the feature be relevant to at least 90% of Homebrew users?

This will be intuitive since most command line users would be familiar with other package management systems that have similar functionality.

### What alternatives to the feature have been considered?

Everyone could continue to write their own scripts and I have done this, but it seems so unnecessary.

P.S. I'm a developer looking for Hacktoberfest credits.  I don't know a lot about Mac or Linux OS's, but I would love to help figure out how to implement this.

**Comment by carlocab** [comment]
This is already implemented. See `brew help bundle` and run `brew bundle dump` to generate a `Brewfile` (Homebrew equivalent of a `Gemfile`) in your current working directory.

**Comment by participator** [comment]
Thanks!  I searched the internet and it seems that no one knew about this feature.  Thanks for highlighting it!
