### ISSUE TITLE
No CI jobs are being created when pull requests are opened

### ISSUE THREAD

**Issue by p-linnane** [Homebrew/brew#13970]
### `brew config` output

```shell
N/A
```

### `brew doctor` output

```shell
N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Bump formulae/casks

### What happened (include all command output)?

PR's open successfully but CI jobs are not created. This appears to have started in the last hour. Examples:

https://github.com/Homebrew/homebrew-core/pull/112420
https://github.com/Homebrew/homebrew-cask/pull/132845

### What did you expect to happen?

CI jobs are created as usual

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
N/A
```

**Comment by dawidd6** [comment]
This is not on our side. GitHub is having issues.

**Comment by carlocab** [comment]
https://www.githubstatus.com/incidents/smn1qtqvbsb6

**Comment by chenrui333** [comment]
usually it would be the github action incidents, i will do the re-trigger now.
