### ISSUE TITLE
brew fails (hangs/stalls/timeouts) when IPv6 GIF network exists at router ("authentication issues")

### ISSUE THREAD

**Issue by newyork10023** [Homebrew/brew#13987]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: fb52a12144e80118c112ea744ab65ab6ca997d67
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8cd7ef45bb5cc49ac27c13b65db2882751b63df2
Core tap last commit: 28 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.iYko4kB15c/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.38.0 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.0.0.0.1.1661618636
Xcode: 14.0.1
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

All fail (hangs/stalls/timeout):
brew install
brew upgrade
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

Works:
 brew update worked.

### What happened (include all command output)?

Hangs/stalls/timeouts.  Messages regarding authentication failures (when trying manually with browsers).

### What did you expect to happen?

It would work ... with IPv6 over a GIF interface.  It use to work fine.

I apologize if this is not specifically a brew issue, but brew could solve the problem if it could disable IPv6 support (or if I knew how it can).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
If IPv6 is enabled going out over GIF on router, brew fails.

If IPv6 is disabled (entirely), brew works.

I tried the procedure to create an alternate curl using Microsoft vcpkg (?).  No success.

I manually uninstalled brew (brew uninstall script fails as well!).  Ripped all components and directories out.  Disabling IPv6 was only way to brew.

It would be helpful if brew had a configuration setting (or if I knew what it was if there is) to disable IPv6 support.  Difficult to create firewall rules (and Little Snitch appears not to be IP version sensitive).
```

**Comment by Bo98** [comment]
We don't ship any networking code at all. We invoke `curl` and `git` mainly.

I can't really give any advice without seeing exactly what stage it gets stuck at. You've not provided any command output.

If the issue is curl, then you can do `echo ipv4 >> ~/.curlrc` and then `export HOMEBREW_CURLRC=1`.
