### ISSUE TITLE
JSON support as a livecheck strategy 

### ISSUE THREAD

**Issue by andrewcrook** [Homebrew/brew#13992]
### Provide a detailed description of the proposed feature

- Along with HTML, XHTML, XML and RSS as mentioned in [Fr] Xpath Support as strategy #13991 
- An option to parse JSON data.

### What is the motivation for the feature?

- Some services and websites offer version/changelog/release information as JSON
- This could be a hosted file or an API 
- Used instead of regex or additional to regex
- I see this being most useful for livechecks

### How will the feature be relevant to at least 90% of Homebrew users?

easier to update formula and casks

### What alternatives to the feature have been considered?

scripts

**Comment by MikeMcQuaid** [comment]
> That said, I've had a local implementation of a `Json` strategy completed for some time and I just need to put some finishing touches on it before I create a PR.

@samford any updates here?

**Comment by samford** [comment]
I've been putting some finishing touches on the `Json` strategy over the past few days (these open issues have been on my mind in recent weeks) and I should have a PR up sometime this week. It's complete at this point (along with documentation and tests) and I mostly just need to take a final pass over it.

I've been working on the forthcoming `Xml` strategy at the same time and some of what I've done in the `Json` strategy informed how i approached it (and vice versa), so I've been working on wrapping up the `Xml` strategy and making sure there's no remaining cross-pollination between the two strategies before creating a PR for either. The `Xml` strategy is functional at this point but I need to tidy it up and write tests, so I'm hoping to create a PR for it this week or next.

**Comment by samford** [comment]
The PR to add the `Json` strategy can now be found at #14785. The PR description contains some example `livecheck` blocks to give you an idea of how it's used (though it's probably what you would expect if you've been parsing JSON in `strategy` blocks until now).

As mentioned, I'm working on wrapping up the `Xml` strategy and I will create a separate PR for it. The next couple days are fairly busy for me, so this may not be until the weekend or early next week.
