### ISSUE TITLE
`brew search` fails when `$HOMEBREW_INSTALL_FROM_API` is set

### ISSUE THREAD

**Issue by alexbarton** [Homebrew/brew#14009]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.5-48-g978a452
ORIGIN: https://github.com/Homebrew/brew
HEAD: 978a452ea7ccdff1ed7377f88add3ff0513ba2b7
Last commit: 13 hours ago
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTOREMOVE: set
HOMEBREW_BROWSER: /usr/bin/open
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.KJz7PKFOKZ/org.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/code --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Right now, `brew search` fails (=returns no results) when `$HOMEBREW_INSTALL_FROM_API` is set. Instead, an error message is shown.

### What happened (include all command output)?

`brew search` doesn't return any results, even when there is a 1:1 match:

```
❯ brew search neovim
Error: No formulae or casks found for "neovim".
❯ brew info neovim
==> neovim: stable 0.8.0 (bottled)
Ambitious Vim-fork focused on extensibility and agility
https://neovim.io/
Not installed
…
```

### What did you expect to happen?

`brew search` should return actual results (or at least show a error message that it is not compatible with `$HOMEBREW_INSTALL_FROM_API`?)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
export HOMEBREW_INSTALL_FROM_API=1
brew search neovim
```
```

**Comment by Rylan12** [comment]
This looks like it's the same issue as https://github.com/Homebrew/brew/issues/12557, only now its spread to homebrew/core as well.

One solution was proposed in https://github.com/Homebrew/brew/pull/13520 but it hasn't really moved forward. Might be worth taking another look now that this affects both main taps (CC @Bo98)

**Comment by Bo98** [comment]
Homebrew/core was affected long before Homebrew/cask was.

#13520 is ready to ship as is (will need a rebase by now though). It works fine. It's blocked on the desire to get rid of GitHub code search completely which is not possible until other cask taps are on formulae.brew.sh.

#13520 currently uses Algolia for Homebrew/core and Homebrew/cask and GitHub code search for other taps.

**Comment by MikeMcQuaid** [comment]
> #13520 is ready to ship as is (will need a rebase by now though). It works fine. It's blocked on the desire to get rid of GitHub code search completely which is not possible until other cask taps are on formulae.brew.sh.
> 
> #13520 currently uses Algolia for Homebrew/core and Homebrew/cask and GitHub code search for other taps.

Shout if I can help review once PRs are up-to-date. I think ideally we have Algolia/formulae.brew.sh for all Homebrew/cask* taps.
