### ISSUE TITLE
Dependencies in Cellar use brew editorconfig, but should not

### ISSUE THREAD

**Issue by ArtAndreev** [Homebrew/brew#14007]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: fb52a12144e80118c112ea744ab65ab6ca997d67
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 10a6e2f6da98ea11ed61e562001e4fcab09aa6ab
Core tap last commit: 21 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.38.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.1.0.0.1.1663981106
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I installed Go (`brew install go`) with brew, before I had it installed with official installer in `/usr/local/go` (I removed it). I opened Go source code with Go to definition feature in Vim. I noticed, that `tabstop` is equal to 2, so all my tabs are aligned like 2 spaces. It was unexpected behavior, I thought that formulas should have same indentation style. I suspected `.editorconfig` plugin, that is installed. I looked at package root `/opt/homebrew/Cellar/go/1.19.2` and nested `libexec/src` directory, but haven't found `.editorconfig`. I watched through all directories up to root and found the file in `/opt/homebrew`.

### What happened (include all command output)?

Described above.

### What did you expect to happen?

I expected all formulas to have the same indentation as provided by them. brew editorconfig should not change the style of source code in formulas.

### Step-by-step reproduction instructions (by running `brew` commands)

Described above.

**Comment by ArtAndreev** [comment]
Yes, the problem is on arm64 mac.

```shell
echo $HOMEBREW_REPOSITORY $HOMEBREW_PREFIX
/opt/homebrew /opt/homebrew
```

**Comment by MikeMcQuaid** [comment]
> Simplest option might be to make it ignore `Cellar`, `opt`, `etc`, `var` etc.

Seems best 👍🏻 



> Maybe installer should remove `.editorconfig` from `/opt/homebrew`?

Definitely not, sorry.

**Comment by ArtAndreev** [comment]
> Simplest option might be to make it ignore Cellar, opt, etc, var etc.

As I understood, I should add a parameter to my editor configuration. But I see no solution (except dummy .editorconfig in Cellar) how to get editorconfig to work both for formulas and homebrew too.

**Comment by ArtAndreev** [comment]
I thought, brew can provide the solution to this problem.
