### ISSUE TITLE
brew search no longer honor tty since da193d2

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#14016]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.6-6-g4737289
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4737289259a028469213d0d8d8d561cd4cedc759
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 76200ff370469c6f5f8d1a1684ff259cf9337ac6
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: subl -w
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 6
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.38.0 => /usr/local/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-x86_64
CLT: 14.1.0.0.1.1663981106
Xcode: 14.1 => /Applications/Xcode_14.1_beta_3.app/Contents/Developer
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libgpg-error
  bash-completion
  gnupg
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Pipe `brew search` to `brew install`, e.g. to install all versions of `gcc`.

This is in fact the reopen of #4981, I'm sorry that I didn't answer the closing comment on time.

        This is working as intended, the only commands supported for scripting are `brew search` and `brew search --casks`, since these are the only ones where you can know if they will return formulae or casks.

_Originally posted by @reitermarkus in https://github.com/Homebrew/brew/issues/4981#issuecomment-425629063_

There is indeed an issue with `brew search` that no longer supports scripting.
      

### What happened (include all command output)?

```
Warning: No available formula with the name "==>".
==> Searching for similarly named formulae...
These similarly named formulae were found:
a2ps
a52dec
aacgain
<... tons of formulas listed>
```

### What did you expect to happen?

`brew search` should honor tty as before da193d2f7efc2079db8da8056e53fc458d5e2036.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew search gcc | xargs brew install
```

**Comment by MikeMcQuaid** [comment]
> `brew search` should honor tty as before [da193d2](https://github.com/Homebrew/brew/commit/da193d2f7efc2079db8da8056e53fc458d5e2036).

This was 4 years ago. Passing on this. 

We'll review a PR to add support for `brew search --formula` or `brew search --cask` to not use the `===>` headers.
