### ISSUE TITLE
brew style to support stanzas order inside blocks

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#14017]
### Provide a detailed description of the proposed feature

Currently, `brew style` doesn't detect wrong stanzas order inside blocks in formulae and casks. There were some other cases that work differently inside blocks, but I can't provide another examples now. In short, it will be good if any style issues inside blocks would be threatened just like in general code.

E.g. after making the modifications below, I see no issues reported by style or audit.
```diff
diff --git a/Formula/ruby.rb b/Formula/ruby.rb
index dc13b0db67d..100880d0894 100644
--- a/Formula/ruby.rb
+++ b/Formula/ruby.rb
@@ -21,8 +21,8 @@ class Ruby < Formula
   end
 
   head do
-    url "https://github.com/ruby/ruby.git", branch: "trunk"
     depends_on "autoconf" => :build
+    url "https://github.com/ruby/ruby.git", branch: "trunk"
   end
 
   keg_only :provided_by_macos
@@ -40,8 +40,8 @@ class Ruby < Formula
   # The exception is Rubygem security fixes, which mandate updating this
   # formula & the versioned equivalents and bumping the revisions.
   resource "rubygems" do
-    url "https://rubygems.org/rubygems/rubygems-3.3.11.tgz"
     sha256 "64184aec5bf3d4314eca3b8bae2085c5ddec50564b822340035187431dc1c074"
+    url "https://rubygems.org/rubygems/rubygems-3.3.11.tgz"
   end
 
   def api_version
```

### What is the motivation for the feature?

Implementing stanzas order support inside blocks should simplify review process.

### How will the feature be relevant to at least 90% of Homebrew users?

It's related mostly to Homebrew and tap developers. Users would benefit with faster updates.

### What alternatives to the feature have been considered?

Consider this as a block feature and stop complaining about wrong stanzas order during code review.

**Comment by hyuraku** [comment]
@carlocab 
Do we need a new custom cop to check the order of methods in a `formula`?

**Comment by dduugg** [comment]
It looks like this is a request to add a cop to enforce this: https://docs.brew.sh/Cask-Cookbook#stanza-order

Here is some prior art for cops enforcing line ordering:
https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cop/bundler/ordered_gems.rb
https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cop/gemspec/ordered_dependencies.rb
https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cop/layout/class_structure.rb
https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cop/lint/ordered_magic_comments.rb

This should be in my wheelhouse, should you still be wanting help here, though it may take me a few weeks to find the bandwidth to get it over the line.

**Comment by dduugg** [comment]
I started to take a look, and realized there's an existing `StanzaOrder` cop, it just isn't working in certain contexts: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/rubocops/cask/stanza_order.rb

(It's clear from the description now that I've read it more carefully, just passing along in case anyone else finds it useful. I should be able to tweak this so it applies inside of blocks as well.)

**Comment by issyl0** [comment]
The formula stanza order cop supports order in blocks (`resource` and `head`, at least) since #15060. I can't immediately find places where cask blocks aren't ordered since #15013 and #14976 combined fixed a bunch of them.

**Comment by issyl0** [comment]
If we find Cask block stanzas that are unordered, I'll re-open this, but I think the bulk of the work is done.

**Comment by issyl0** [comment]
Hmmm, the thing I noticed was just the `TODO` for the edge cases of nested blocks that we said we weren't doing in https://github.com/Homebrew/brew/pull/15013#issuecomment-1476601486. I think this is fine? Your idea about a test is a good one though Yurii, thanks!
