### ISSUE TITLE
Cleanup doesn't remove newer package versions

### ISSUE THREAD

**Issue by vraravam** [Homebrew/brew#1403]
I have `erlang` and `elixir` pinned to specific versions due to project-requirements. I have been using homebrew for the past few years, and so have tried the `brew doctor`, complete reinstall of brew, etc.
Issue: As you can see, I have `erlang` pinned to 18.x and `elixir` pinned to 1.2.6 , and did a `brew update` which pulled in `erlang v19`. Now, if I run `brew cleanup -f`, shouldn't it also remove `erlang v19`? (since I have erlang pinned to v18?

<img width="734" alt="pinned-erlang-but-not-cleanedup" src="https://cloud.githubusercontent.com/assets/69629/19834057/525a55d8-9e76-11e6-8f50-008b5e9bcd17.png">

**Comment by vitorgalvao** [comment]
Does `-f` still does anything, even? It’s not in the man page. However, `-s` is, and might be what you’re looking for:

```
If -s is passed, scrubs the cache, removing downloads for even
the latest versions of formulae. Note downloads for any
installed formulae will still not be deleted. If you want to
delete those too: rm -rf $(brew --cache)
```

**Comment by MikeMcQuaid** [comment]
There's an argument for this but I prefer the current behaviour. Homebrew is designed to get you on the latest version of a formula. In your case I'd advise creating your own tap if you need to pin to specific versions.
