### ISSUE TITLE
Output of `brew list` is a broken table, when tab width is 4

### ISSUE THREAD

**Issue by ArtAndreev** [Homebrew/brew#14031]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 978a452ea7ccdff1ed7377f88add3ff0513ba2b7
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 60650f51de6d781afa2bedcb9cf1abb27a5496fe
Core tap last commit: 22 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.38.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.1.0.0.1.1663981106
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I ran `brew list` command to see all installed packages and saw wrong formatted table. I have tab width set to 4 characters in my terminal emulator. When I set it to 8 characters, table is properly formatted. However, when I run `brew list --full-name`, table is OK in both cases.

### What happened (include all command output)?

Tab size is 4:
<img width="1512" alt="изображение" src="https://user-images.githubusercontent.com/26388769/197187662-313e3be1-6b51-44fb-9cc4-8bdc26d5432a.png">

Tab size is 8:
<img width="1512" alt="изображение" src="https://user-images.githubusercontent.com/26388769/197187894-437f599d-4834-4201-9bc2-8fc93d0ccc9a.png">

### What did you expect to happen?

Expected to see properly formatted table.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew list
brew list --full-name
```

**Comment by MikeMcQuaid** [comment]
We'll review a PR to fix this. This is caused by your configuration so not leaving an issue open as you have a workaround.
