### ISSUE TITLE
`HOMEBREW_BAT=1 brew cat` does not respect `less` environment variables

### ISSUE THREAD

**Issue by timhillgit** [Homebrew/brew#14040]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.6-37-g2365c6b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2365c6bed513036d4d1733a42b2a7028c88c7290
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 72163254f4cdcbbec1ae6b6d6f285309625944d0
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs -nw
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.1.0.0.1.1663981106
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

1. I want to use `brew cat` to view the source code of formulae I'm interested in.
2. I like bat, so I have it installed and `HOMEBREW_BAT=1` set in my environment.
3. I don't like less saving history, so I have `LESSHST=-` set in my environment. I also have customized less in other ways e.g. `LESS="--incsearch"`
4. I'd like `brew cat` to respect those choices, but at the moment it does not: it saves history and does not allow me to use incremental search.

One possible solution would be to add `LESS` and `LESSHST` to: https://github.com/Homebrew/brew/blob/3fcd62238ad1e0ae8ccbaf48126e333778927e5f/bin/brew#L130-L135
Those variables are pretty safe so this _should_ be fine, but I didn't want to open a PR as I'm not sure if this would have unintended effects.

### What happened (include all command output)?

The file `~/.lesshst` was created, containing all of the less commands I entered while using `brew cat`

### What did you expect to happen?

`~/.lesshst` should not have been created, no history from less should have been saved.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. rm ~/.lesshst
2. LESSHST=- HOMEBREW_BAT=1 brew cat bat
3. Search for a string in the code (e.g. type /bat and press return)
4. Press q to quit bat
5. [ -f ~/.lesshst ] && echo 'This file should not exist!'
```

**Comment by MikeMcQuaid** [comment]
This environment filtering is by design.

We'd review a PR to allow you to set `HOMEBREW_LESS` or `HOMEBREW_LESSHST` or similar but not passthrough `LESS` or `LESSHST` unconditionally.
