### ISSUE TITLE
brew search fails when there's a network problem

### ISSUE THREAD

**Issue by thomasjachmann** [Homebrew/brew#14052]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.7-28-g560f571
ORIGIN: https://github.com/Homebrew/brew
HEAD: 560f5717ad4dc1e3feed9f3c0b7c84aa1498b84c
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: efcca57c1bfa044b1c0b03607b20dd65b1db91f6
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: nvim -f
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_FORCE_VENDOR_RUBY: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_GITHUB_API: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_UPDATE_REPORT_ALL_FORMULAE: set
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.38.1 => /usr/local/opt/git/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew search lens`

### What happened (include all command output)?

Error: Cask 'transmission-nightly' definition is invalid: invalid 'app' stanza: Failure while executing; `/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.7-28-g560f571\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --fail --silent --location https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/artifact/release/` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 403

### What did you expect to happen?

I expected to see a list of formulae/casks matching the searched name.

The problem is that I'm on a corporate notebook where some domains are blocked by a proxy for security reasons, as sensible as that might be... build.transmissionbt.com seems to be one of them. So the fact that the cask `transmission-nightly` is trying to fetch their release page in order to get the current nightly version which results in a 403 from the proxy raises a CaskInvalidError. I'd have expected this error not to abort the whole search. Maybe a warning should be issued but the search should still continue.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- set up a proxy that blocks certain domains (eg build.transmissionbt.com) returning a 403
- run `brew search anything`
```

**Comment by Bo98** [comment]
Same issue as Homebrew/homebrew-cask#134356. Given two reports, this looks like a regression.

Perhaps this line: https://github.com/Homebrew/brew/commit/b9411ef8a66008e291c3814fccfb520e3099d74b#diff-1e1a1af922d2a8677e78c99c63e03462200f233d7c986b3aed822b45e0f55c64R55

**Comment by MikeMcQuaid** [comment]
> Perhaps this line: [b9411ef#diff-1e1a1af922d2a8677e78c99c63e03462200f233d7c986b3aed822b45e0f55c64R55](https://github.com/Homebrew/brew/commit/b9411ef8a66008e291c3814fccfb520e3099d74b#diff-1e1a1af922d2a8677e78c99c63e03462200f233d7c986b3aed822b45e0f55c64R55)

Yeh, could be. Would love to not just revert this, if possible.

**Comment by 4ooc** [comment]
Same errors, `brew search` is all broken, and I just could use the website to search.
Even I remove this cask but another still returns a 403.

**Comment by thomasjachmann** [comment]
Everything works fine again. Thank you very much! ❤️
