### ISSUE TITLE
`--json` for `brew search`

### ISSUE THREAD

**Issue by shemeshg** [Homebrew/brew#14067]
### Provide a detailed description of the proposed feature

'brew search **--json** --formula qt` will provide

```
[{name: "qt@5", installed: true},
{name:"qt" , installed: true},
{name: "poppler-qt5", installed: false}]
```

### What is the motivation for the feature?

- Almost all brew commands has `--json` as standard
- Parsing with `jq` `nushell` and other tools.

### How will the feature be relevant to at least 90% of Homebrew users?

No, but it is already brew convention to have `--json`

### What alternatives to the feature have been considered?

```
% brew search --formula qt|jq -R '{ name: inputs }'
{
  "name": "fastq-tools"
}
{
  "name": "mqttui"
}
```

But you loose indication is installed...

**Comment by MikeMcQuaid** [comment]
`brew search --formula gcc | grep -v "==>" | xargs brew info --json` works how you'd like.

I think it should be refactored so the `==>` is no longer needed.

**Comment by shemeshg** [comment]
I think, this actually might do.
For now, I'll use you suggested solution.

Thanks

**Comment by MikeMcQuaid** [comment]
Have opened https://github.com/Homebrew/brew/pull/14070 to avoid the nee for the `grep -v "==>"` here.
