### ISSUE TITLE
mandoc: /usr/local/opt/grep/libexec/man/man1/grep.1:XX:XX: UNSUPP: unsupported roff request: do

### ISSUE THREAD

**Issue by hejackson2** [Homebrew/brew#14079]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa2649dde786208da7d151a89bcafdd23a453f4d
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ed822a590aa9ebc7fdf4130157e8f8b5b39a4337
Core tap last commit: 28 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.38.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.1-x86_64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/edjacks/.pyenv/shims/python3.10-config
  /Users/edjacks/.pyenv/shims/python-config
  /Users/edjacks/.pyenv/shims/python3-config

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

man grep

to research grep usage

### What happened (include all command output)?

After manpage was shown and exited from, the output left on the terminal was:

$ man grep
mandoc: /usr/local/opt/grep/libexec/man/man1/grep.1:41:9: UNSUPP: unsupported roff request: do
mandoc: /usr/local/opt/grep/libexec/man/man1/grep.1:42:1: UNSUPP: unsupported roff request: do
mandoc: /usr/local/opt/grep/libexec/man/man1/grep.1:43:1: UNSUPP: unsupported roff request: do

This does not occur for other gnu utils installed (for example, sed, tar, make, find)

### What did you expect to happen?

no error messages to be displayed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install grep

echo "PATH="$(brew --prefix)/opt/grep/libexec/gnubin:$PATH" >> ~/.bashrc

source ~/.bashrc

man grep
```

**Comment by Bo98** [comment]
This is a macOS 12 `man` bug. It might be fixed in macOS 13 though: https://github.com/Homebrew/discussions/discussions/2506#discussioncomment-2893262

**Comment by hejackson2** [comment]
Thank you!
