### ISSUE TITLE
brew services do not stop correctly

### ISSUE THREAD

**Issue by jiayouzl** [Homebrew/brew#14078]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: fa2649dde786208da7d151a89bcafdd23a453f4d
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: edbc4965f09e9f82322464d52dd34bde46d50237
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
 zhanglei  ~  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.4

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

NONE

### What happened (include all command output)?

 zhanglei  ~  brew services stop mysql@5.7
Stopping `mysql@5.7`... (might take a while)

It doesn't work, and the previous version is normal.

### What did you expect to happen?

 zhanglei  ~  brew services stop mysql@5.7
Stopping `mysql@5.7`... (might take a while)

It doesn't work, and the previous version is normal.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
zhanglei  ~  brew services stop mysql@5.7
Stopping `mysql@5.7`... (might take a while)

It doesn't work, and the previous version is normal.
```

**Comment by erwinrachim** [comment]
same with me, and not only mariadb, is on httpd too.
<img width="633" alt="image" src="https://user-images.githubusercontent.com/20570854/199409881-b891d5a8-c78b-4085-93b0-25a7298c88db.png">

**Comment by jiayouzl** [comment]
my xcode version 14.1.

**Comment by erwinrachim** [comment]
> my xcode version 14.1.

yup me too
but this happens when we restart our mac. or the service has been running before.
so after i did the experiment:
- the service has not been run or "none"
- I did `brew services start httpd`
- and I tried `brew service stop httpd` : no problem, it works
- I did again `brew services start httpd`
- restart mac
- and try again `brew services stop`, and it will take a very long time to stop

I also do:
- `rm -rf ~/Library/LaunchAgents/homebrew.mxcl.httpd.plist`
- restart mac
- do it again `brew services start httpd` and `brew service stop httpd` : it's work
- but after I restart again with the service running on login and try to `brew service stop httpd` it will happen like that too

**Comment by jiayouzl** [comment]
> > my xcode version 14.1.
> 
> yup me too but this happens when we restart our mac and the service has been running before. so after i did the experiment:
> 
> * the service has not been run or "none"
> * I did `brew services start httpd`
> * and I tried `brew service stop httpd` : no problem, it works
> * I did again `brew services start httpd`
> * restart mac
> * and try again `brew services stop`, and it will take a very long time to stop
> 
> I also do:
> 
> * `rm -rf ~/Library/LaunchAgents/homebrew.mxcl.httpd.plist`
> * restart mac
> * do it again `brew services start httpd` and `brew service stop httpd` : it's work
> * but after I restart again with the service running on login and try to `brew service stop httpd` it will happen like that too

Wait for the author to fix it.

**Comment by MikeMcQuaid** [comment]
@jiayouzl @erwinrachim if you can reproduce: can you try to revert https://github.com/Homebrew/homebrew-services/pull/512 locally and see if you can still reproduce after that?

**Comment by SMillerDev** [comment]
If that solves it, can you post the content of `~/Library/LaunchAgents/homebrew.mxcl.httpd.plist`?

**Comment by jiayouzl** [comment]
@MikeMcQuaid @SMillerDev hello There is no problem with v3.6.7, this problem only appeared after upgrading v3.6.8.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>homebrew.mxcl.mysql@5.7</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/opt/homebrew/opt/mysql@5.7/bin/mysqld_safe</string>
		<string>--datadir=/opt/homebrew/var/mysql</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>WorkingDirectory</key>
	<string>/opt/homebrew/var/mysql</string>
</dict>
</plist>
```

**Comment by MikeMcQuaid** [comment]
@jiayouzl I strongly suspect the issue is with homebrew-services and not the Homebrew/brew version, I don't think we changed anything here recently?

**Comment by jiayouzl** [comment]
> @jiayouzl I strongly suspect the issue is with homebrew-services and not the Homebrew/brew version, I don't think we changed anything here recently?

I still have a computer, currently v3.6.7 is all normal, and this problem also occurred after upgrading to v3.6.8.

**Comment by jiayouzl** [comment]
> And if you go back to 3.6.7 after?

How to return to v3.6.7?

**Comment by MikeMcQuaid** [comment]
I don't see anything in https://github.com/Homebrew/brew/releases/tag/3.6.8 that looks services related 🤔. https://github.com/Homebrew/homebrew-services/pull/512 was a fairly major change though.

**Comment by jiayouzl** [comment]
> And if you go back to 3.6.7 after?

I also have a computer that is a virtual machine, and the snapshot is restored to v3.6.7, which is normal.

**Comment by MikeMcQuaid** [comment]
@jiayouzl can you verify that homebrew-services is the same revision/SHA-1/version on both? It is what powers `brew services` and `brew update` will also cause it to be updated too.

You can find this with `git -C $(brew --repo homebrew/services) show --oneline`

**Comment by jiayouzl** [comment]
@MikeMcQuaid @SMillerDev OK, I have work on hand now, and I'll test it when I'm done.

**Comment by jiayouzl** [comment]
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/7685337/199496481-f2549c2b-dbbd-4b42-a46b-f681227cc1aa.png">
@MikeMcQuaid

**Comment by jiayouzl** [comment]
MacBook pro m1pro macos13.

**Comment by MikeMcQuaid** [comment]
@jiayouzl is that on the machine that works or the machine that doesn't? Can you try to revert the PR I mentioned above and see if that addresses things? Shout if you need a hand with e.g. what `git` commands to run.

**Comment by jiayouzl** [comment]
> @jiayouzl is that on the machine that works or the machine that doesn't? Can you try to revert the PR I mentioned above and see if that addresses things? Shout if you need a hand with e.g. what `git` commands to run.

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/7685337/199497775-fc34738b-d9e8-4291-b425-e332151820b2.png">
This is a machine that is not working properly.

**Comment by MikeMcQuaid** [comment]
@jiayouzl can you try to run `git -C $(brew --repo homebrew/services) revert 1e90b16f4de81b45763d469815159ec338990561 -m1 --no-edit` on the machine that is not working and see if it fixes things? You can restore the state afterwards to `git -C $(brew --repo homebrew/services) reset --hard origin/master` (although note this will destroy any local modifications you have on homebrew/services).

**Comment by erwinrachim** [comment]
> @jiayouzl can you try to run `git -C $(brew --repo homebrew/services) revert 1e90b16f4de81b45763d469815159ec338990561 -m1 --no-edit` on the machine that is not working and see if it fixes things? You can restore the state afterwards to `git -C $(brew --repo homebrew/services) reset --hard origin/master` (although note this will destroy any local modifications you have on homebrew/services).

@MikeMcQuaid is working, and after I restart my mac and try to `brew services start httpd/mariadb` is work
<img width="682" alt="image" src="https://user-images.githubusercontent.com/20570854/199505789-584c4e94-fd18-4d8f-a605-7318d0d17a2a.png">

**Comment by jiayouzl** [comment]
> 



> > @jiayouzl can you try to run `git -C $(brew --repo homebrew/services) revert 1e90b16f4de81b45763d469815159ec338990561 -m1 --no-edit` on the machine that is not working and see if it fixes things? You can restore the state afterwards to `git -C $(brew --repo homebrew/services) reset --hard origin/master` (although note this will destroy any local modifications you have on homebrew/services).
> 
> @MikeMcQuaid is working, and after I restart my mac and try to `brew services start httpd/mariadb` is work <img alt="image" width="682" src="https://user-images.githubusercontent.com/20570854/199505789-584c4e94-fd18-4d8f-a605-7318d0d17a2a.png">

Did you fall back to this version to be normal?`git -C $(brew --repo homebrew/services) revert 1e90b16f4de81b45763d469815159ec338990561 -m1 --no-edit`

**Comment by erwinrachim** [comment]
> > 
> 
> > > @jiayouzl can you try to run `git -C $(brew --repo homebrew/services) revert 1e90b16f4de81b45763d469815159ec338990561 -m1 --no-edit` on the machine that is not working and see if it fixes things? You can restore the state afterwards to `git -C $(brew --repo homebrew/services) reset --hard origin/master` (although note this will destroy any local modifications you have on homebrew/services).
> > 
> > 
> > @MikeMcQuaid is working, and after I restart my mac and try to `brew services start httpd/mariadb` is work <img alt="image" width="682" src="https://user-images.githubusercontent.com/20570854/199505789-584c4e94-fd18-4d8f-a605-7318d0d17a2a.png">
> 
> Did you fall back to this version to be normal?`git -C $(brew --repo homebrew/services) revert 1e90b16f4de81b45763d469815159ec338990561 -m1 --no-edit`

yup is back to normal

**Comment by jiayouzl** [comment]
@MikeMcQuaid @SMillerDev Our problem is solved, you may need to roll it back and fix it.
