### ISSUE TITLE
PETSc should be built with mumps support

### ISSUE THREAD

**Issue by prudhomm** [Homebrew/brew#14089]
### Provide a detailed description of the proposed feature

PETSc can be compiled with mumps (mpi) support. 

### What is the motivation for the feature?

It brings a parallel direct solver in the PETSc realm of solvers.
it would enable many new solution strategies in sequential and parallel

### How will the feature be relevant to at least 90% of Homebrew users?

it is very relevant to **all** petsc homebrew users as it provides a rock solid solver strategy for many problems!

### What alternatives to the feature have been considered?

there are no parallel direct solvers in the current petsc formula.

I can probably help modify the formula. Note that  mumps needs to be compiled with mpi support.

**Comment by MikeMcQuaid** [comment]
> I can probably help modify the formula.

Please submit a PR, thanks. For future reference: please submit issues to homebrew-core and group very similar issues into one.

**Comment by MikeMcQuaid** [comment]
Just to be explicit: no guarantee we'll accept the PR but it's easier to discuss and we're unlikely to open it for you.
