### ISSUE TITLE
Can't restart/stop a service using homebrew

### ISSUE THREAD

**Issue by toan-tam** [Homebrew/brew#14082]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.8-16-ge7b213c
ORIGIN: https://github.com/Homebrew/brew
HEAD: e7b213c0944e191ff11d61e588cd29a1b6e83867
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: efd28d82fe32e9e98197ba9061b6534562d6170a
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.4
  php@7.3

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
  UD Formula/php@7.4.rb
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to restart mysql@5.7 service after applying some configuration in ~/.my.cnf

### What happened (include all command output)?

It's getting hung up when stopping the service. I waited for about 10 minutes and it still hasn't finished the stopping mysql@5.7 service yet

### What did you expect to happen?

It should stop the mysql@5.7 service after a few second

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
➜  www brew services list
Name               Status     User  File
dnsmasq            none       root
elasticsearch-full error  256 admin ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch-full.plist
mailhog            started    admin ~/Library/LaunchAgents/homebrew.mxcl.mailhog.plist
mysql@5.7          started    admin ~/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx              none       root
php                none
php@7.3            none
php@7.4            started    root  ~/Library/LaunchAgents/homebrew.mxcl.php@7.4.plist
redis              started    admin ~/Library/LaunchAgents/homebrew.mxcl.redis.plist

➜  www brew services restart mysql@5.7
Stopping `mysql@5.7`... (might take a while)
```

**Comment by MikeMcQuaid** [comment]
Please try to run `brew update --force` again and try again.

**Comment by toan-tam** [comment]
> Please try to run `brew update --force` again and try again.

I've tried that and got the same issue:

➜  www brew update --force
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
➜  www brew services list
Name               Status     User  File
dnsmasq            none       root
elasticsearch-full error  256 admin ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch-full.plist
mailhog            started    admin ~/Library/LaunchAgents/homebrew.mxcl.mailhog.plist
mysql@5.7          started    admin ~/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx              none       root
php                none       root
php@7.3            none
php@7.4            started    admin ~/Library/LaunchAgents/homebrew.mxcl.php@7.4.plist
redis              started    admin ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
➜  www brew services restart mysql@5.7
Stopping `mysql@5.7`... (might take a while)

**Comment by toan-tam** [comment]
@MikeMcQuaid I'm not sure if this is the same issue as in https://github.com/Homebrew/brew/issues/14078

`git -C $(brew --repo homebrew/services) show --oneline` return the following commit.

```
b802596 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #517 from Homebrew/revert-512-master

(END)
```

Can you please advise what I should do to fix this?

Thanks

**Comment by MikeMcQuaid** [comment]
> Can you please advise what I should do to fix this?

Sorry, I have no idea.

**Comment by toan-tam** [comment]
> > Can you please advise what I should do to fix this?
> 
> Sorry, I have no idea.

Restarting my Mac did the trick. Maybe we need to do that after `brew update --force`

Anyway, thanks a lot for your help.
