### ISSUE TITLE
PETSc formula should provide the PETSc python bindings : petsc4py

### ISSUE THREAD

**Issue by prudhomm** [Homebrew/brew#14090]
### Provide a detailed description of the proposed feature

petsc4py development is now hosted alongside the petsc library. It is part of the PETSc API now.
the formula should install the bindings 

### What is the motivation for the feature?

petsc4py provides the python bindings for both sequential and parallel computation and it is quite complete with respect to what PETSc does. 

### How will the feature be relevant to at least 90% of Homebrew users?

it would be relevant to most PETSc formula users as it provides scripting capabilities for PETSc

### What alternatives to the feature have been considered?

I don't see any alternatives

**Comment by MikeMcQuaid** [comment]
Please submit a PR for discussion, thanks. For future reference: please submit issues to homebrew-core and group very similar issues into one.

**Comment by MikeMcQuaid** [comment]
Just to be explicit: no guarantee we'll accept the PR but it's easier to discuss and we're unlikely to open it for you.
