### ISSUE TITLE
brew update error

### ISSUE THREAD

**Issue by vitahlin** [Homebrew/brew#1409]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

`brew update`:

``` c
fatal: unable to access 'https://github.com/Homebrew/brew/': SSLRead() return error -9806
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': SSLRead() return error -9806
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': SSLRead() return error -9806
Error: Fetching /usr/local/Homebrew failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask failed!
```

`brew doctor`:

``` c
Your system is ready to brew.
```

My computer is Mac 10.12.1.
Is there something wrong with my net？

**Comment by maoLB** [comment]
i have the same problems as you

**Comment by bfontaine** [comment]
Does `cd "$(brew --repo)" && git fetch` work?

**Comment by vitahlin** [comment]
@bfontaine Thanks for your reply.It did not work after I did like you said.

Then I used this command :`brew update --verbose`,it shows that:
```c
Checking if we need to fetch /usr/local/Homebrew...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...
remote: Counting objects: 40, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 40 (delta 29), reused 32 (delta 21), pack-reused 0
Unpacking objects: 100% (40/40), done.
From https://github.com/caskroom/homebrew-cask
   8c1dcc3..a884391  master     -> origin/master
Updating /usr/local/Homebrew...
Reset branch 'stable'
Current branch stable is up to date.

Updating /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...
First, rewinding head to replay your work on top of it...
Fast-forwarded master to origin/master.

Updated 1 tap (caskroom/cask).
No changes to formulae.
```
It seams to work well.

**Comment by MikeMcQuaid** [comment]
Closing as this seems very likely to be https://github.com/Homebrew/brew/issues/1324#issuecomment-257287604.
