### ISSUE TITLE
Check app version before upgrading a Cask

### ISSUE THREAD

**Issue by WarningImHack3r** [Homebrew/brew#14116]
### Provide a detailed description of the proposed feature

Basically a lot of apps have an integrated auto-update feature, like Chrome and many more. But when the app is installed from Homebrew, an update may be installed twice, once through the app itself (assuming the auto-update has not been disabled) and another time through `brew` (assuming it's ran often enough).

Homebrew currently doesn't (seem to?) check the app's version and seems to act based on the last version the app has been installed from `brew` in.

**What I suggest is `brew upgrade --cask` to check for the _current_ app's version (easily done by using `mdls -raw -name kMDItemVersion /Applications/<App>.app`) instead of sometimes reinstalling the same version.**

### What is the motivation for the feature?

Avoiding installing an update that has already been performed, and greatly increase compatibility with such apps featuring auto-update. Some apps also don't really like to be completely uninstalled and reinstalled, and often in that case a complete setup has to be performed again, which can be painful.

Another step on this feature might be to warn and avoid updating apps when auto-update is enabled in them so Homebrew stops managing their versions entirely.

### How will the feature be relevant to at least 90% of Homebrew users?

It will let the user decide, avoid going through setup at each update for some, and shorten the `brew --upgrade` time.

### What alternatives to the feature have been considered?

Manually disabling every auto-update feature (if applicable) on all apps installed from Homebrew.

**Comment by p-linnane** [comment]
There is an `auto_updates` stanza (see [Cask Cookbook](https://docs.brew.sh/Cask-Cookbook)) which can be added to casks to indicate they are handled in-app and should not be upgraded by `brew`. `brew` will only upgrade casks without that stanza set, unless you pass `--greedy` when running `brew --upgrade`. If you're found any casks you use that autoupdate, but are still being upgraded by `brew`, please feel free to open PR's adding the `auto_updates` stanza.
