### ISSUE TITLE
Homebrew installs extra python3 instead of using active pyenv version

### ISSUE THREAD

**Issue by eugenesvk** [Homebrew/brew#1412]
I've installed **python3** with homebrew **pyenv** and set is as a global version

```
~ > pyenv versions                                                                                                   
  system
  2.7.11
* 3.5.2 (set by /Users/user/.dev/.pyenv/version)
  3.6.0b1

```

Whenever I check formula's requirements in homebrew, they are viewed as met with the pyenv python version

```
~ > brew info asciinema
asciinema: stable 1.3.0 (bottled), HEAD
Record and share terminal sessions
https://asciinema.org
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/asciinema.rb
==> Requirements
Required: python3 ✔
```

However, when I try to install such a formula, Homebrew would always install and additional version of python3, disregarding the version set by pyenv.
Is there a way to prevent Homebrew from installing an extra python version and just use the system version?
# Please follow the general troubleshooting steps first:
- [Y] Ran `brew update` and retried your prior step?
- [Y] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I have the following **doctor warnings**, stemming from the fact that I have pyenv python set as global, but don't think I should fix them

```
Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/user/.dev/.pyenv/shims/python-config
  /Users/user/.dev/.pyenv/shims/python2-config
  /Users/user/.dev/.pyenv/shims/python2.7-config
  /Users/user/.dev/.pyenv/shims/python3-config
  /Users/user/.dev/.pyenv/shims/python3.5-config
  /Users/user/.dev/.pyenv/shims/python3.5m-config
  /Users/user/.dev/.pyenv/shims/python3.6-config
  /Users/user/.dev/.pyenv/shims/python3.6m-config
```

**Comment by DomT4** [comment]
Don't pour the bottle. `brew install asciinema -s` should use your custom Python3 just fine.

**Comment by dunn** [comment]
@eugenesvk the reason the bottle installs our Python is because it was compiled with our Python.

**Comment by eugenesvk** [comment]
Thank you, I forgot about it and somehow this helpful [page](https://github.com/Homebrew/brew/blob/master/docs/Homebrew-and-Python.md) isn't ranked in google high enough to appear for "Homebrew Python installed as a dependency" search string, which is pretty close to the needed title "Why is Homebrew's Python being installed as a dependency?" of the section :)

Last question then - is it possible to somehow fix the dependency check in Homebrew so that it wouldn't show a nice green check mark even when there is no Homebrew's Python installed? Given that Homebrew's goal is to bottle everything, should it not limit dependency checks only to what bottles need, even when dependencies are met for the `--build-from-source` flag?

**Comment by dunn** [comment]
> Last question then - is it possible to somehow fix the dependency check in Homebrew so that it wouldn't show a nice green check mark even when there is no Homebrew's Python installed?

That's a good idea.  We should be able to, yeah.
