### ISSUE TITLE
Could not resolve host: github.com, but I can access it without problem

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [Homebrew/brew#1414]
I have no problem accessing websites through the browser, including github. However, all of a sudden brew returns host resolution errors.

Anything I can do to investigate what's causing it?

```
$ brew update
fatal: unable to access 'https://github.com/Homebrew/brew/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': Could not resolve host: github.com
Error: Fetching /usr/local/Homebrew failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask failed!
```

**Comment by wadkar** [comment]
probably a system/networking error. i don't think `brew` can do much about it. Can you `ping github.com`?
Possible that DNS isn't working and browser is just using its cache.

**Comment by underyx** [comment]
I have the same issue, since today. I can ping github.com, and `curl` connects to it properly, from the same shell environment where I'm running brew.

Updating fails with the same logs as in the OP. Installation also fails when it tries to connect to github.com:

```
$ brew cask install atom
==> Satisfying dependencies
complete
==> Downloading https://github.com/atom/atom/releases/download/v1.11.2/atom-mac.zip

curl: (6) Could not resolve host: github.com
Error: Download failed on Cask 'atom' with message: Download failed: https://github.com/atom/atom/releases/download/v1.11.2/atom-mac.zip
The incomplete download is cached at /Users/underyx/Library/Caches/Homebrew/Cask/atom--1.11.2.zip.incomplete
```

**Comment by MikeMcQuaid** [comment]
> probably a system/networking error. i don't think brew can do much about it.

This, unfortunately. Homebrew can't do anything.

**Comment by MikeMcQuaid** [comment]
> probably a system/networking error. i don't think brew can do much about it.

This, unfortunately. Homebrew can't do anything.

**Comment by underyx** [comment]
What could cause such an error for two people at the same time while being
unreproducible outside Homebrew? Maybe the issue is somehow with ruby?

**Comment by MikeMcQuaid** [comment]
@underyx Any number of issues with ISP, DNS providers, proxy providers, etc.

**Comment by danielsdesk** [comment]
I, too, just had this problem start all of a sudden within the past few days.  It's definitely not Homebrew as mentioned above; I ended up doing 
```
git config --global --unset http.proxy 
git config --global --unset https.proxy
```
and then restarting my term session and it works again

**Comment by samplenull** [comment]
@danielsdesk Thank you so much, I had the exact same issue today, your fix resolved this problem.

**Comment by jian-cui** [comment]
I restarted iTerm2, and it worked.
