### ISSUE TITLE
Allow the usage of aria instead of curl for downloading

### ISSUE THREAD

**Issue by gaetschwartz** [Homebrew/brew#14144]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

It would be great if brew allowed to use other programs tzo download bottles than `curl`, I was mainly thinking of `aria`.

### What is the motivation for the feature?

`aria` can really speed downloads up. 

Scoop does it: https://scoop-docs.vercel.app/docs/misc/Multi-connection-downloads-with-aria2.html

### How will the feature be relevant to at least 90% of Homebrew users?

It would allow them to speed downloads up if they want to use aria.

### What alternatives to the feature have been considered?

Leaving it as it currently is.

**Comment by MikeMcQuaid** [comment]
Sorry, not interested in supporting other downloaders or supporting multi-connection downloads.
