### ISSUE TITLE
Invalid audit failure: “stable version should not decrease”

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#14160]
### What were you trying to do (and why)?

Dispatching bottles jobs on CI for formulas like `doctl grafana dolt`

### What happened (include all command output)?

See https://github.com/Homebrew/homebrew-core/actions/runs/3500369336/jobs/5862964332

```
==> Running Formulae#formula!(dolt)
==> brew audit --strict --only=gcc_dependency dolt
==> brew deps --tree --annotate --include-build --include-test dolt
==> Determining dependencies...
==> brew fetch --retry go
==> Starting build of dolt
==> brew fetch --retry dolt --build-bottle --force
==> brew install --only-dependencies --verbose --build-bottle dolt
==> brew install --verbose --build-bottle dolt
==> brew audit dolt --git --skip-style
==> FAILED
Full audit dolt --git --skip-style output
  dolt:
    * stable version should not decrease (from 0.51.4 to 0.51.3)
  Error: 1 problem in 1 formula detected
```

### What did you expect to happen?

No audit failure.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew dispatch-build-bottle --macos=13 --issue=113717 --upload dolt
```

**Comment by fxcoudert** [comment]
As far as I can see, this has been happening regularly for many years, and fixes had to be reverted every time: https://github.com/Homebrew/brew/issues/1731

**Comment by carlocab** [comment]
We should probably not be passing `--git` to `brew audit` when dispatching additional bottles. Not sure where the `--git` flag is coming from, though.

**Comment by Bo98** [comment]
This one is only sort of invalid - it would have failed (or at least should) on upload anyway.

Dolt was updated to 0.51.4 after you started dispatched the build but before it completed. So you were building on the state of homebrew-core when it was 0.51.3 but the audit runs when it had been updated to 0.51.4.

On upload this would have resulted in an incorrect bottle block, but I'm sure there's further checks to make the upload fail in that scenario.

**Comment by fxcoudert** [comment]
Hum, you're right, I hadn't seen that.
