### ISSUE TITLE
List dependencies to be installed _before_ downloading them.

### ISSUE THREAD

**Issue by alfuken** [Homebrew/brew#14170]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When user issues a command `brew install <whatever>` (for example, "vips"), and \<whatever> has any dependencies, print the message "Installing dependencies for \<whatever>" **before** downloading everything, not **after** the fact.

If that message would include information on the total size of files it is about download, that would be awesome. I know it's not included in the formula definition, but this is something that could potentially be collected via Analytics system for each formula, if not already.

### What is the motivation for the feature?

This issue irks me for quite a while now, but the last drop was today, when I had to install `vips`. After the command `brew install vips`, it spew on me [more than two screens of "Downloading XXX"](https://pastebin.com/raw/m2TTgi9m), generating copious amounts of WTFs/minute with each new line during a process that took what felt like forever. And only _after_ brew downloaded it all, it finally decided to tell me "hey, look, I'm installing dependencies for vips: cfitsio, cgif, isl, mpfr, libmpc, gcc, hwloc, open-mpi, fftw, libexif, libgsf, libimagequant, libaec, hdf5, libmatio, libspng, mozjpeg, libxml2, openslide, orc, nspr, nss and poppler". _Well thank you, Captain Obvious, you may fly away now!_

### How will the feature be relevant to at least 90% of Homebrew users?

My assumption is that 90% of the Homebrew users would agree that it is only logical to list such information in the beginning of the process, not in the middle of it.

### What alternatives to the feature have been considered?

Having a function/alias/shortcut
```bash
brew-install() { brew install --dry-run "$@"; brew install "$@" }
```

Alas, this does not include size information, and is but a dirty fugly duct taped crutch.

**Comment by Bo98** [comment]
I agree. It used to do this but regressed when the fetch stage was moved earlier.

**Comment by MikeMcQuaid** [comment]
`brew install --dry-run` feels like the best solution for now. 

We could move this header earlier, agreed.

This will never include size information, we don't store that anywhere.

**Comment by p-linnane** [comment]
`brew info <formula>` also returns all dependencies, including ones for building from source.
