### ISSUE TITLE
git gui broken in git 2.10.2

### ISSUE THREAD

**Issue by pires** [Homebrew/brew#1417]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] ~~If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?~~

### Bug reports:

After updating to `git` `2.10.2`, `git gui` stopped working.

```
$ git gui
/usr/local/Cellar/git/2.10.2/libexec/git-core/git-gui: line 8: exec: /Users/pires/Work/Projects/docker-elasticsearch/@@HOMEBREW_PREFIX@@/Cellar/git/2.10.2/share/git-gui/lib/Git Gui.app/Contents/MacOS/Wish: cannot execute: No such file or directory
```

**Comment by jawshooah** [comment]
Confirmed this is a bug. `libexec/git-core/git-gui` and `libexec/git-core/git-cvsserver` aren't being added to `changed_files` for some reason.

**Comment by jawshooah** [comment]
AFK right now but will investigate this evening.

**Comment by jawshooah** [comment]
Fix incoming in https://github.com/Homebrew/brew/issues/1420.

**Comment by MikeMcQuaid** [comment]
@pires Let us know if this still isn't fixed as it may need a rebottling.

**Comment by jawshooah** [comment]
@MikeMcQuaid I'm pretty sure it will need a rebottling, unfortunately : disappointed:

**Comment by pires** [comment]
Well, I reinstalled `git` but same thing.

**Comment by jawshooah** [comment]
@pires for now, you can just `brew reinstall git --build-from-source`.

**Comment by pires** [comment]
@jawshooah thanks it worked!
