### ISSUE TITLE
Add automatic proxy detection

### ISSUE THREAD

**Issue by stillhart** [Homebrew/brew#14184]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Homebrew does currently not detect and switch proxies automatically. A user has to set the environment variables `http_proxy` and `https_proxy` in order to use homebrew via a proxy. In my case I can be connected to the internet with and without a proxy. All browsers and many apps can handle this. Therefore it would be if some kind of proxy detection and proxy switching could be added to homebrew.

Right now I have to change the environment variables constantly in order to use homebrew.

Some proxy settings seem to be available via the `scutil` and `networksetup` commands. Sadly, I can not find a command which returns the currently active proxy, only which one is configured. Even then, sometimes an automatic proxy configuration file called `.pac` can be used. I assume there are many more ways to configure and use proxies. Therefore this feature could easily bloat, which I would not want to happen.

Maybe helpful:
- https://dmorgan.info/posts/mac-network-proxy-terminal/
- https://github.com/dotnet/runtime/issues/24799

### What is the motivation for the feature?

All corporate users with proxies are faced with connection errors. They either have to set or unset proxy variables whether they are connected to their proxy or not. Usually, one only finds out after running into network issues. It's a known issue for many corporate users, but still quite annoying.

For many users setting up homebrew is one of the first things to do, therefore this is one of the first issues they run into. That's not a nice user experience, especially for users being introduced to homebrew via their corporation.

I think that the homebrew user experience could be enhanced quite a lot with proxy detection or at least more targeted error messages. 

### How will the feature be relevant to at least 90% of Homebrew users?

No, I don't think so. I do not know how many users in corporations are using homebrew. I think it will be relevant to a large two digit subset of hombrew users.

### What alternatives to the feature have been considered?

Connection errors can be proxy issues. Maybe add more specific errors which could direct one to either network issues or proxy issues.

The error if a proxy is set but not reachable is already quite good:
```
fatal: unable to access 'https://github.com/Homebrew/brew/': Could not resolve proxy: PROXY_URL
fatal: unable to access 'https://github.com/Homebrew/homebrew-cask/': Could not resolve proxy: PROXY_URL
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': Could not resolve proxy: PROXY_URL
fatal: unable to access 'https://github.com/Homebrew/homebrew-services/': Could not resolve proxy: PROXY_URL
Error: Fetching /opt/homebrew failed!
```

**Comment by MikeMcQuaid** [comment]
Sorry, I don't think this is practical for us as it's essentially a feature request for `curl`.
