### ISSUE TITLE
brew update-reset stuck at fetching "homebrew-core"

### ISSUE THREAD

**Issue by fitterfizzle** [Homebrew/brew#14188]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.13-2-gcb355a2
ORIGIN: https://github.com/Homebrew/brew
HEAD: cb355a23a0d4456a26eed6ddc42ddb2509c1df14
Last commit: 4 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 100d6b07afef56c57e79b42c52c9380f5182dc19
Core tap last commit: 2 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.38.1 => /opt/homebrew/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

normal `brew update`

### What happened (include all command output)?

terminal stays frozen

### What did you expect to happen?

to update all outdated packages to perform a `brew upgrade`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
```

**Comment by brandonryan** [comment]
There was a huge package or something, just wait a bit it will get through.

**Comment by fitterfizzle** [comment]
I see thanks for the super quick answer. Will let it stay at fetching and see what happens then. Issue can be closed in that case from my POV.

**Comment by brandonryan** [comment]
I still think its worth investigating what happened in core that caused this huge slowdown. Maybe we can use this issue at a jumping point for that discussion.

**Comment by MikeMcQuaid** [comment]
Moving discussion to https://github.com/Homebrew/brew/issues/14187
