### ISSUE TITLE
Xcode 8.0 outdated?

### ISSUE THREAD

**Issue by Softwave** [Homebrew/brew#1418]
I can't install any homebrew formula because it tells me:

"Error: Your Xcode (8.0) is outdated.
Please update to Xcode 8.1 (or delete it).
Xcode can be updated from the App Store."

I've recently upgraded to Sierra and Xcode 8.0. I figure this can't be true and something else must have gone wrong. Any help would be appreciated - and apologies if this is a simple thing.

**Comment by sharat** [comment]
It will take time to evaluate and make 8.1 as default. It's not a good idea to show it as error.

**Comment by ilovezfs** [comment]
This is intentional behavior. If you want to cheat add `export CI=1`to your environment.
