### ISSUE TITLE
Make creating a brew formula as easy as npm init/publish

### ISSUE THREAD

**Issue by gulachek** [Homebrew/brew#14198]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

1. If no URL is specified in brew create, create the formula file in the local working directory that can be added to the source package's version control system
2. Add either 'brew commit' or 'brew push' to specify a tap to push the formula to

### What is the motivation for the feature?

It's a bit cumbersome to create a brew formula for a software package that I'm developing and intending to support with homebrew.  Brew seems really slick for making an installer for a software package whose developer didn't support brew, and another person who wants to make installation easy can reference that project's source url and script installing it in a separate (brew) repo.  It isn't quite as easy when I develop my own package that I already know that I want to support homebrew, and for every version bump, I need to maintain two repositories.

### How will the feature be relevant to at least 90% of Homebrew users?

I'm sure this would make the lives of several package developers easier.

It could have an impact on average brew consumers by having more up to date formulae because it's easier to keep them up to date for each version bump of the source code.

### What alternatives to the feature have been considered?

I could write my own scripting utilities for this.  That seems a bit hacky and that if I published it for others to use, it would be maintained in the wrong place.

**Comment by MikeMcQuaid** [comment]
> It isn't quite as easy when I develop my own package that I already know that I want to support homebrew, and for every version bump, I need to maintain two repositories.

You can put a homebrew formula in any respository, it's just that for it to be easily tapped that repository needs to begin with `homebrew-`. 

Passing on this I'm afraid as it's not actionable enough as-is. We'll review PRs to make this better!
