### ISSUE TITLE
brew fetch of a mercurial repository fails

### ISSUE THREAD

**Issue by tsparber** [Homebrew/brew#1419]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Fetching a mercurial repository fails if mercurial (`hg`) is not yet installed. 

```
$ brew fetch homebrew/python/pygame
==> Fetching pygame from homebrew/python
==> Cloning https://bitbucket.org/pygame/pygame
Error: Failed to download resource "pygame"
Failure while executing:  clone https://bitbucket.org/pygame/pygame /Users/*/Library/Caches/Homebrew/pygame--hg
```

This is the case on the build bot and the reason the CI fails for https://github.com/Homebrew/homebrew-games/pull/722.
https://bot.brew.sh/job/Homebrew%20Games%20Pull%20Requests/1106/version=el_capitan/console

Installing the formula directly works, as it depends on mercurial which is then automatically installed before installing `pygame`.

Any advice on this?
Possible steps:
* Install mercurial on the CI servers?
* Automatically install mercurial before/while fetching?
* Ignore?

**Comment by scpeters** [comment]
The [pygame url](https://github.com/Homebrew/homebrew-python/blob/master/pygame.rb#L4-L6) is currently:

~~~
  url "https://bitbucket.org/pygame/pygame",
      :revision => "faa5879a7e6bfe10e4e5c79d04a3d2fb65d74a62",
      :using => :hg
~~~

I don't know if that is supported, but you could try the following instead:

~~~
  url "https://bitbucket.org/pygame/pygame/get/faa5879a7e6bfe10e4e5c79d04a3d2fb65d74a62.tar.gz"
  sha256 "..."
~~~

**Comment by MikeMcQuaid** [comment]
I'd in favour of just working around this on CI. Ideally we'd auto-install `hg` in this case.
