### ISSUE TITLE
How to install with pinned dependencies?

### ISSUE THREAD

**Issue by vfonic** [Homebrew/brew#14217]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I understand that this is intended behavior, with which I disagree:

```sh
❯ brew upgrade shopify-cli --ignore-pinned --force
==> Upgrading 1 outdated package:
shopify/shopify/shopify-cli 3.22.1 -> 3.25.0
Error: You must `brew unpin sqlite xz cmake libnghttp2 node ruby` as installing shopify/shopify/shopify-cli requires the latest version of pinned dependencies
```

### What is the motivation for the feature?

Is there any way around this?

### How will the feature be relevant to at least 90% of Homebrew users?

Change the functionality. There have been numerous threads on this. Over and over again.

### What alternatives to the feature have been considered?

Or at least offer an alternative to having to find the exact commit version and then having to `brew update` or something to that exact version or install the old formula. I forgot what the solution was, but it was overly complicated to remember and I believe it should be more straightforward as there are many users with the same issue that I have.

**Comment by vfonic** [comment]
It is _my responsibility_ and I claim that everything will work on _my machine_ after I run `brew upgrade shopify-cli`. I don't want to upgrade my `node` package version from v18 LTS to v19 which is not LTS and I simply don't want to have both.

How can I go around this in the simplest way possible?

**Comment by vfonic** [comment]
Can we agree to disagree here?

I respect your decision to not make this default. But at least I'd be very happy to know there is a way to achieve what I need.

There are even cases when brew is forcing me to upgrade the perfectly working package for the one that doesn't work (on my machine). So instead of ending up with installed new package and working dependency I ended up with broken (upgraded) dependency and that means that both the newly installed package nor its upgraded dependency work now.

I fail to see how this (both packages broken) could be better than allowing "force upgrade/install" if the user wishes so (both packages working).

Similar issues:
https://github.com/Homebrew/homebrew-core/issues/86425
https://github.com/Homebrew/brew/issues/12171
https://github.com/CloverHealth/homebrew-tap
https://gis.stackexchange.com/questions/261525/installing-postgis-on-older-homebrew-versions-of-postgresql-e-g-postgresql9-6
https://gist.github.com/gopperman/18cb66078372d3261420829630230b80
https://github.com/Homebrew/brew/issues/6103
https://stackoverflow.com/questions/55190888/how-to-prevent-homebrew-from-installing-a-certain-formula-dependency

**Comment by MikeMcQuaid** [comment]
No. We specifically do not want to support these sort of footguns. When we did support this sort of behaviour in the past: it caused no end of pain for maintainers and users.

If you want to restrict something to a specific version indefinitely: use `brew extract`. This will not let you use these formulae as dependencies unless you do this on the whole dependency tree, by design.

> Can we agree to disagree here?

We can, yeh, but that will not involve us merging, documenting and supporting behaviour that we do not wish to.
