### ISSUE TITLE
Brew Upgrade Fails

### ISSUE THREAD

**Issue by Pcummings** [Homebrew/brew#14224]
### `brew doctor` output

```shell
e104364@C02F830SMD6P ~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 001bacee18c512657e1535dff757c8cfdaefc116
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 64dbb36bcaf850924b361de143030d2d6f0ce055
Core tap last commit: 13 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.1-x86_64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
```

### What were you trying to do (and why)?

I just updated my box to Monterey and wanted to upgrade by homebrew installations by running brew upgrade

### What happened (include all command output)?

e104364@C02F830SMD6P ~ % brew upgrade
==> Upgrading 2 outdated packages:
glib 2.74.0 -> 2.74.3
xz 5.2.7 -> 5.2.9
==> Downloading https://ghcr.io/v2/homebrew/core/glib/manifests/2.74.3
Already downloaded: /Users/e104364/Library/Caches/Homebrew/downloads/01c3163ee1a0c27ac19bed96f462ae592a3efd7928caf9641ede4238ccbb552c--glib-2.74.3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/glib/blobs/sha256:55aebc872575b
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
curl: (18) transfer closed with 6485792 bytes remaining to read               

Error: glib: Failed to download resource "glib"
Download failed: https://ghcr.io/v2/homebrew/core/glib/blobs/sha256:55aebc872575b6c4a49bc8b45755b030bc0cedd258f955adfd2d44c15cccdc20
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.2.9
Already downloaded: /Users/e104364/Library/Caches/Homebrew/downloads/b948468605557bcd8fe2d2e0dca89971ccfa793d966e4d0daea9c49041b9de93--xz-5.2.9.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:0ad360d7faae284
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
curl: (18) transfer closed with 462255 bytes remaining to read                

Error: xz: Failed to download resource "xz"
Download failed: https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:0ad360d7faae284e54fd50c09a86871ff65be56f78537386d3d97b1df9db34b8

### What did you expect to happen?

I expected the packages to download and install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Simply run brew upgrade
```

**Comment by MikeMcQuaid** [comment]
> as I thought that it perhaps was my network

It is, sorry.
