### ISSUE TITLE
Brew does too much work before deciding a command is unknown

### ISSUE THREAD

**Issue by johnwhitington** [Homebrew/brew#14238]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I make lots of mistakes typing (due to a medical condition). When I get the name of a command wrong like this...

```
intel:repos john$ brew upgraed
Error: Unknown command: upgraed
```

...it takes about 2 or 3 seconds for brew to say it was the misspelt.

### What is the motivation for the feature?

If it is possible to move the check earlier in the process, and fail more quickly, it would be nice.

### How will the feature be relevant to at least 90% of Homebrew users?

Everyone does this occasionally. Just not as much as me!

### What alternatives to the feature have been considered?

None.

**Comment by MikeMcQuaid** [comment]
If you can make this faster without degrading other behaviour: we'll review a PR. There's no obvious speedup here, I'm afraid.
