### ISSUE TITLE
brew commands search and desc errors: wrong number of arguments

### ISSUE THREAD

**Issue by auntchilada** [Homebrew/brew#14231]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config

HOMEBREW_VERSION: 3.6.14-49-g781ffda
ORIGIN: https://github.com/Homebrew/brew
HEAD: 781ffdab8e7c1b78351ea88f1eea7d106ecf7266
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: febd37a1e64ad1c5cf9cbcca8cc63ab7c60fe8bf
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_BAT_THEME: ansi
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 15
HOMEBREW_DISPLAY: :0.0
HOMEBREW_EDITOR: /Users/bduart/bin/beditor.sh
HOMEBREW_EVAL_ALL: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_COLOR: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_VERBOSE_USING_DOTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-x86_64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.1

nb...
 
$ sw_vers 

ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C5059b

this is macOS 13.1 beta 4 (22C5059b)

# ----------------------------------------

$ brew doctor

Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### this used to work fine...

`$ brew search /./ --desc >| filespec`

this runs after my brew update/upgrade tool.

this would enable me to create a catalog of all homebrew packages, ie, formulae, casks and fonts, with one-line descriptions.

### What happened (include all command output)?

`$ brew search /./ --desc`

==> Formulae
Error: wrong number of arguments (given 3, expected 4)
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:16:in 'search'
/usr/local/Homebrew/Library/Homebrew/search.rb:28:in 'block in search_descriptions'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:26:in 'use'
/usr/local/Homebrew/Library/Homebrew/search.rb:26:in 'search_descriptions'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/search.rb:11:in 'search_descriptions'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:85:in 'search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:97:in < main >

###  a variant would get me formulae but choke on casks...

`$ brew desc --search /./ `

Error: wrong number of arguments (given 1, expected 0)
/usr/local/Homebrew/Library/Homebrew/description_cache_store.rb:104:in 'populate_if_empty!'
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:17:in 'search'
/usr/local/Homebrew/Library/Homebrew/cmd/desc.rb:88:in 'block in desc'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:26:in 'use'
/usr/local/Homebrew/Library/Homebrew/cmd/desc.rb:86:in 'desc'
/usr/local/Homebrew/Library/Homebrew/brew.rb:97:in ' < main > '

==> Formulae
a2ps: Any-to-PostScript filter
a52dec: Library for decoding ATSC A/52 streams (AKA 'AC-3')
aacgain: AAC-supporting version of mp3gain
...
zx: Tool for writing better scripts
zxcc: CP/M 2/3 emulator for cross-compiling and CP/M tools under UNIX
zydis: Fast and lightweight x86/x86_64 disassembler library
zyre: Local Area Clustering for Peer-to-Peer Applications
zzuf: Transparent application input fuzzer
zzz: Command-line tool to put Macs to sleep

==> Casks

$

i  tried what is documented in the brew manpage re _desc and search_ with similar failures

### What did you expect to happen?

==> Formulae
a2ps: Any-to-PostScript filter
a52dec: Library for decoding ATSC A/52 streams (AKA 'AC-3')
aacgain: AAC-supporting version of mp3gain
...
zx: Tool for writing better scripts
zxcc: CP/M 2/3 emulator for cross-compiling and CP/M tools under UNIX
zydis: Fast and lightweight x86/x86_64 disassembler library
zyre: Local Area Clustering for Peer-to-Peer Applications
zzuf: Transparent application input fuzzer
zzz: Command-line tool to put Macs to sleep

==> Casks
etc...

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew search /./ --desc
```

**Comment by auntchilada** [comment]
thank you, kindly, sir!

sincere regards,

Brian

**Comment by MikeMcQuaid** [comment]
@auntchilada you're welcome, thanks for the report!
