### ISSUE TITLE
configure: error: cannot run C compiled programs.

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/brew#1423]
_From @sahil912 on November 2, 2016 11:54_

I am following this issue after upgrading to MacOS Seirra
brew config gives me the following details:

> HOMEBREW_VERSION: 1.0.9-20-gf14a3a1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: f14a3a17decdcfd26fc9f2dc0958ee642241ea5a
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0d689da84064b9ef99f766858a87fd22c8305488
Core tap last commit: 86 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/jsahil/.rvm/rubies/ruby-2.2.0/bin/ruby
Java: 1.8.0_25
macOS: 10.12-x86_64
Xcode: 8.1
CLT: 8.0.0.0.1.1472435881
X11: N/A
MacPorts/Fink: /opt/local/bin/port

Could please help? How do I resolve this issue, 

_Copied from original issue: Homebrew/legacy-homebrew#50697_

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by MikeMcQuaid** [comment]
Closing due to no response.

**Comment by benstadin** [comment]
I have the same issue with latest Xcode 8.1 on Sierra. In my case I was cross-compiling protobuf for x86_64 iOS Simulator. All other architectures compiled fine however.

I have followed all of the troubleshooting, updated and upgraded brew, etc. 

I reproduced the issue on two Macs (both on Sierra). The issue can be reproduced by using the protobuf build script from here: https://gist.github.com/palplus/5847a2ee0d4372926ea0

git clone https://gist.github.com/5847a2ee0d4372926ea0.git protobuild
cd protobuild
./build-protobuf.sh

You can turn off other targets in the build scripts to shorten build time, though you'll notice that all targets but x84_64 simulator build fine. 

The build script was working for me previously. I think the only thing that changed on my syste, was an update to xcode, though I can't say for sure unfortunately (not unlikely that I built previous to upgradin to Sierra).

**Comment by MikeMcQuaid** [comment]
You don't seem to reference a Homebrew installation at all?

**Comment by jlgasparrini** [comment]
The same problem here! ✋

**Comment by oorrwullie** [comment]
Try running `xcode-select --install`. This generally solves the "cannot run C compiled programs" error.

**Comment by jlgasparrini** [comment]
My problem was with capybara-webkit ruby gem, I fixed it from [official documentation here](
https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#xcode-80)
