### ISSUE TITLE
Feature request for `brew list` to get the short description

### ISSUE THREAD

**Issue by con-cis** [Homebrew/brew#14244]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Add an argument to `brew list` and `brew list --cask` to get the short description on all installed packages like provided on `/api/formula.json`

### What is the motivation for the feature?

- to many installed packages
- to few time to look up every one
- rediscover long forgotten packages

### How will the feature be relevant to at least 90% of Homebrew users?

- maybe other people are also forgetful on rarely used packages like me

### What alternatives to the feature have been considered?

- build a intersectional request between brew list and the json response short descriptions

**Comment by carlocab** [comment]
Does this command work for you?
```sh
brew desc --eval-all $(brew list)
```
As an aside, I believe `--eval-all` should not be needed here, but `brew desc` seems to fail without it.
