### ISSUE TITLE
Torrent alternative to `git -C ... fetch --unshallow`

### ISSUE THREAD

**Issue by SephReed** [Homebrew/brew#14247]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

The command `git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow` has pretty poor UX.  It hangs for a very long time without any information, takes ~15 min for 500 mb, can not be paused, and ultimately achieves little more than downloading some files.  On a slow connection or weak computer, this command doesn't work at all.  To this date, I have yet to get the command to work on any platform.  It just hangs.

There are better ways of downloading files.

The suggestion here is to host a `.torrent` file which contains the folder in its entirety.

### What is the motivation for the feature?

- The ability to pause a download
- See progress updates on a download
- Not require git (unless used for other things)
- Not require "enumerating objects"
- The ability to access large files on systems with minimal ram
- Gives access to systems with low bandwidth (as it allows pausing)
- Offloads some of the hosting costs to other users (seeders)
- Widely considered the most logical way of giving people access to large downloads

### How will the feature be relevant to at least 90% of Homebrew users?

Popularity is considered a useful metric because it's popular.  If measured by efficacy, it tends to stand less well. 

### What alternatives to the feature have been considered?

A simple download could work, but the ability to pause it important.  I didn't think it would, I thought the data was quite a lot given the amount of time this process takes.  It appears to be 517.6mb.  This shouldn't take 15 minutes to download, it's pretty clear that git is not a great solution in this context.

**Comment by gromgit** [comment]
In my experience, torrents don't work well at all when the fileset being shared changes multiple times each day. Homebrew core does just that.

`export HOMEBREW_INSTALL_FROM_API=1` tells `brew` to query an online formula/cask DB for its operations. No Git required, no local copy of the Homebrew core repos (though I think it caches basic formula/cask info), and therefore no issues of torrenting an ever-changing fileset. See the ENVIRONMENT section of the `brew` man page for details.

**Comment by MikeMcQuaid** [comment]
> The command `git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow` has pretty poor UX.

You should never have to manually run this if you've installed and updated Homebrew through the official commands/installer recently.

> In my experience, torrents don't work well at all when the fileset being shared changes multiple times each day. Homebrew core does just that.

This.

> * Not require git (unless used for other things)

It is.

> `export HOMEBREW_INSTALL_FROM_API=1` tells `brew` to query an online formula/cask DB for its operations. No Git required, no local copy of the Homebrew core repos (though I think it caches basic formula/cask info), and therefore no issues of torrenting an ever-changing fileset. See the ENVIRONMENT section of the `brew` man page for details.

Yes. Beta test this instead. It'll be the default behaviour 🔜.
