### ISSUE TITLE
Remove `rubocop_todo.yml` files.

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#14250]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

We have two `rubocop_todo.yml` files:
- https://github.com/Homebrew/brew/blob/master/Library/Homebrew/.rubocop_todo.yml
- https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/.rubocop_todo.yml

These are used when running `brew style` to filter out these specific rules. However, the editor and non-`brew style` integration here is pretty poor and these are never updated.

Instead, we should (in preferred order):
1. fix these failures
2. move them to `# rubocop:disable` comments (along with another comment explaining why)
3. move them to `Exclude:` rules if we wish to disable an entire file/folder in a `rubocop.yml` file instead

### What is the motivation for the feature?

Improve editor integration and cleanup code.

### How will the feature be relevant to at least 90% of Homebrew users?

Nicer code, nicer Homebrew.

### What alternatives to the feature have been considered?

Doing nothing.

**Comment by dduugg** [comment]
Are you still wanting help here, @MikeMcQuaid @issyl0 ? I think I could start by resolving the `RSpec/VerifiedDoubles` todos with some create `sed` use and cleanup.

**Comment by MikeMcQuaid** [comment]
@dduugg Great, thanks!

**Comment by issyl0** [comment]
Thanks @dduugg! I thought I'd get to this over the Christmas holidays, but I got 🤒 instead.

**Comment by MikeMcQuaid** [comment]
Woohoo, great work getting this over the line @dduggg!
