### ISSUE TITLE
Document that casks should be signed to be accepted

### ISSUE THREAD

**Issue by eugenesvk** [Homebrew/brew#14253]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Homebrew Casks requires applications to be signed. However, this is not documented in
- https://docs.brew.sh/Adding-Software-to-Homebrew#casks or
- https://docs.brew.sh/Acceptable-Casks

### What is the motivation for the feature?

I've tried to add a cask only to realize that the it was a wasted effort because it didn't pass audit due to the original cask not being signed

### How will the feature be relevant to at least 90% of Homebrew users?

This is more relevant to the X% cask contributors

### What alternatives to the feature have been considered?

Docs is the best alternative

**Comment by SMillerDev** [comment]
Documentation was added to that extend.
