### ISSUE TITLE
Print summary after upgrade

### ISSUE THREAD

**Issue by pattyland** [Homebrew/brew#14257]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I think it would be nice if homebrew would print a summary of what packages it upraded when you run `brew upgrade`. Some packages take quite some time so I don't want to look at my terminal but then I might miss what apps were upraded. A summary would be nice to be informend.

### What is the motivation for the feature?

I want to know what was upgraded to look at apps for new features. scrolling is annoying

### How will the feature be relevant to at least 90% of Homebrew users?

I would say thats a common problem for a lot of people. 90% sounds very high, there might be users that are not insterested what happended

### What alternatives to the feature have been considered?

Not giving a summary I would guess

**Comment by gromgit** [comment]
I personally set `HOMEBREW_DISPLAY_INSTALL_TIMES` to get that sort of output.
```bash
$ export HOMEBREW_DISPLAY_INSTALL_TIMES=1
$ brew upgrade
==> Upgrading 6 outdated packages:
libxdmcp 1.1.3 -> 1.1.4
mbedtls 3.2.1 -> 3.3.0
bash 5.2.12 -> 5.2.15
librist 0.2.7_1 -> 0.2.7_2
shellcheck 0.8.0 -> 0.9.0
python@3.10 3.10.8 -> 3.10.9
[...]
==> Installation times
libxdmcp                  0.089 s
mbedtls                   0.159 s
bash                      0.569 s
librist                   0.168 s
shellcheck                0.196 s
python@3.10               1.690 s
```
`man brew` (or [see here](https://docs.brew.sh/Manpage#environment)) to understand the many environment variables that can be set to influence Homebrew behavior.

**Comment by MikeMcQuaid** [comment]
Passing on this for now but will consider it in future if more folks request it.
