### ISSUE TITLE
`brew info [TAB]` completion in ZSH prints errors but suggests nothing

### ISSUE THREAD

**Issue by Kentzo** [Homebrew/brew#14254]
### `brew doctor` output

```shell
Warning: Your Cellar and TEMP directories are on different volumes.
macOS won't move relative symlinks across volumes unless the target file already
exists. Brews known to be affected by this are Git and Narwhal.

You should set the "HOMEBREW_TEMP" environment variable to a suitable
directory on the same volume as your Cellar.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 11cdffb4fef84828a7e02860212b30ce4fac85f5
Last commit: 7 days ago
Core tap: N/A
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTOREMOVE: set
HOMEBREW_CACHE: /Users/brew/.cache/Homebrew
HOMEBREW_CASK_OPTS: ["--appdir=/Applications", "--colorpickerdir=/Users/kentzo/Library/ColorPickers", "--prefpanedir=/Users/kentzo/Library/PreferencePanes", "--qlplugindir=/Users/kentzo/Library/QuickLook", "--mdimporterdir=/Users/kentzo/Library/Spotlight", "--dictionarydir=/Users/kentzo/Library/Dictionaries", "--fontdir=/Users/kentzo/Library/Fonts", "--servicedir=/Users/kentzo/Library/Services", "--input-methoddir=/Users/kentzo/Library/Input Methods", "--internet-plugindir=/Users/kentzo/Library/Internet Plug-Ins", "--audio-unit-plugindir=/Users/kentzo/Library/Audio/Plug-Ins/Components", "--vst-plugindir=/Users/kentzo/Library/Audio/Plug-Ins/VST", "--vst3-plugindir=/Users/kentzo/Library/Audio/Plug-Ins/VST3", "--screen-saverdir=/Users/kentzo/Library/Screen Savers"]
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_LOGS: /Users/brew/.cache/Homebrew/Logs
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

Trying to auto-complete `brew info [TAB]` in ZSH 5.8.1

### What happened (include all command output)?

$ brew info find: /opt/homebrew/Library/Taps: No such file or directory
find: /opt/homebrew/Library/Taps: No such file or directory
find: /opt/homebrew/Library/Taps: No such file or directory
find: /opt/homebrew/Library/Taps: No such file or directory
find: /opt/homebrew/Library/Taps: No such file or directory
find: /opt/homebrew/Library/Taps: No such file or directory

### What did you expect to happen?

Suggest a formula for completion or do nothing without printing errors.

It seems like current autocompletion function requires the "Taps" directory to exist, but it was not created by Homebrew installation. I did not delete this directory manually. Adding this directory removes the errors but there is still no completion.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew info [TAB]` in ZSH 5.8.1
```

**Comment by cho-m** [comment]
`brew`'s ZSH completion probably isn't able to handle `HOMEBREW_INSTALL_FROM_API` yet.

I think the `find` usage is from:
https://github.com/Homebrew/brew/blob/884c4bec14073314ac6e8e9a6a64bc3b26161ab6/Library/Homebrew/items.sh#L21

Which is used by:
https://github.com/Homebrew/brew/blob/884c4bec14073314ac6e8e9a6a64bc3b26161ab6/completions/zsh/_brew#L60

Easiest way would be to just output nothing when Taps directory doesn't exist. For actual completion with `HOMEBREW_INSTALL_FROM_API`, may need to query API and cache.
