### ISSUE TITLE
`sudo brew services list` unclear error message

### ISSUE THREAD

**Issue by ww898** [Homebrew/brew#14263]
Clean install on clean macOS 13.1
`sudo brew services list` dosn't work:

```
>sudo brew services list
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Error: Failure while executing; `/opt/homebrew/bin/brew tap homebrew/services` exited with 1.
```
Running `sudo brew services list` executes two internals commands: `services` and `tap`. The first command works properly, but the second produce the error. Could you please fix the bug in the script?

https://github.com/Homebrew/brew/blob/884c4bec14073314ac6e8e9a6a64bc3b26161ab6/Library/Homebrew/brew.sh#L178-L196

**Comment by gromgit** [comment]
Workaround: Run `brew services list` first, to tap the Homebrew `services` code tap _as you_. Once that's done `sudo brew services list` should work as advertised.

**Comment by ww898** [comment]
Thanks. My own way is executing `brew tap homebrew/services` before `sudo brew services list`.
However, this place make a lot of bad experience because no correct error message about whats was wrong.

**Comment by gromgit** [comment]
Sure, but such fixes are only available to most (read: non-dev-mode) users on the next official release. My suggestion is to solve your (and whoever else ran into the same) problem _now_.
