### ISSUE TITLE
After upgrade, `brew update` would install curl automatic.

### ISSUE THREAD

**Issue by 4ooc** [Homebrew/brew#14276]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.15-53-g4534748
ORIGIN: https://github.moeyy.xyz/https://github.com/Homebrew/brew
HEAD: 4534748f29758a8964688d202705f6f66deadfee
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1637e66b57a7c334f2cc95e449e2331fccb08d38
Core tap last commit: 49 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_INSTALL_CLEANUP: set
all_proxy: socks5://127.0.0.1:7890
http_proxy: http://127.0.0.1:7890
https_proxy: http://127.0.0.1:7890
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Try to run `brew update`, but it install `curl` automatic even I never installed it via `brew`.

### What happened (include all command output)?

```
==> Fetching dependencies for curl: brotli, gettext, libunistring, libidn2, libnghttp2, ca-certificates, openssl@1.1, libssh2, openldap, rtmpdump, lz4, xz and zstd
==> Fetching brotli
==> Downloading https://ghcr.io/v2/homebrew/core/brotli/manifests/1.0.9
^C
Error: 'curl' must be installed and in your PATH!
```

### What did you expect to happen?

`curl` is in my PATH, and I don't want to manage it via `brew `.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just `brew update`.
```

**Comment by carlocab** [comment]
This is your problem:
```
HOMEBREW_FORCE_BREWED_CURL: set
```
Do
```
unset HOMEBREW_FORCE_BREWED_CURL
```
and Homebrew should stop installing `curl` automatically. You may need to remove this setting from your `.zprofile`/`.zshrc`/equivalent.

**Comment by 4ooc** [comment]
> This is your problem:
> 
> ```
> HOMEBREW_FORCE_BREWED_CURL: set
> ```
> 
> Do
> 
> ```
> unset HOMEBREW_FORCE_BREWED_CURL
> ```
> 
> and Homebrew should stop installing `curl` automatically. You may need to remove this setting from your `.zprofile`/`.zshrc`/equivalent.

Thanks. 
I‘m so sorry that I overlook env variables.
