### ISSUE TITLE
Add table of contents to top of docs pages

### ISSUE THREAD

**Issue by PythonCoderAS** [Homebrew/brew#14283]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

A table of contents for documentation pages with links to every section

### What is the motivation for the feature?

Makes it much easier to move around a large page such as https://docs.brew.sh/Formula-Cookbook.

### How will the feature be relevant to at least 90% of Homebrew users?

Easier navigation of docs

### What alternatives to the feature have been considered?

Using Find (Cmd+F). This does not work well if you don't remember the name of the section you're looking for.

**Comment by apainintheneck** [comment]
I like the idea and it doesn't look like it'd be too difficult to add. Kramdown is the default Jekyll markdown renderer and it [supports automatic table of contents generation](https://kramdown.gettalong.org/converter/html.html#toc).

**Comment by PythonCoderAS** [comment]
An alternative is https://github.com/allejo/jekyll-toc.

**Comment by MikeMcQuaid** [comment]
Will review a PR for this.
