### ISSUE TITLE
Curl needs CURL_SSL_BACKEND in environment in some setups

### ISSUE THREAD

**Issue by mikaey** [Homebrew/brew#14305]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 740f9ddcc620d4812770a0f12854ddd79c643874
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2673ff9b78f81bd5980cc7812a65541a2bc21497
Core tap last commit: 16 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew install php`

### What happened (include all command output)?

==> Fetching dependencies for php: apr, ca-certificates, openssl@1.1, apr-util, argon2, aspell, m4, autoconf, brotli, gettext, libunistring, libidn2, libnghttp2, libssh2, openldap, rtmpdump, lz4, xz, zstd, curl, libtool, unixodbc, freetds, libpng, freetype, fontconfig, jpeg-turbo, giflib, highway, imath, openexr, libtiff, webp, jpeg-xl, libvmaf, aom, libavif, gd, gmp, icu4c, krb5, libpq, libsodium, libzip, oniguruma, pcre2, readline, sqlite and tidy-html5
==> Fetching apr
==> Downloading https://ghcr.io/v2/homebrew/core/apr/manifests/1.7.0_3
curl: (60) SSL certificate problem: unsupported or invalid name syntax
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Error: php: Failed to download resource "apr_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/apr/manifests/1.7.0_3

### What did you expect to happen?

I expected PHP to be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install php
```

**Comment by mikaey** [comment]
I'm in a corporate environment that uses a transparent proxy for all HTTP/HTTPS requests -- the kind that generates SSL certificates on-the-fly for all HTTPS requests.

After much trial and tribulation, I managed to narrow down the issue to the fact that `CURL_SSL_BACKEND` is set to `secure-transport` in my environment -- but `/opt/homebrew/bin/brew` is stripping that out of the environment that it passes to brew.sh.  When I added `CURL_SSL_BACKEND` to the list of `ENV_VAR_NAMES` in `/opt/homebrew/bin/brew`, it started working as expected.

**Comment by MikeMcQuaid** [comment]
> the kind that generates SSL certificates on-the-fly for all HTTPS requests.

Presumably this MITMs all secure traffic?

I'm afraid this feels a lot like something your corporate environment needs to workaround rather than Homebrew doing so.

**Comment by mikaey** [comment]
> Presumably this MITMs all secure traffic?

Yes, yes it does.

And I can't be the only one in this situation.  It would be nice if Brew at least had the _option_ of allowing this env variable to be passed through.  I couldn't see any configs or command line options that would have fixed this.

**Comment by carlocab** [comment]
This sounds like something you can use a `.curlrc` for? You'll need to set `HOMEBREW_CURLRC`. See `man brew` for details.

**Comment by mikaey** [comment]
Unfortunately that doesn't work, because `curl` doesn't expose a corresponding command line option -- it only seems to accept it via the environment variable.  (I did try setting different variations of the name in `.curlrc` -- `CURL_SSL_BACKEND`, `SSL_BACKEND`, `curl_ssl_backend`, `ssl_backend`... `curl` just spits out a message saying `warning: 'CURL_SSL_BACKEND' is unknown`)

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry, I'm pretty 👎🏻 on having this functionality in Homebrew because it seems too easy to abuse to bypass all our security measures and corporations can change their settings rather than us changing our code.

I'm open to other maintainers strongly disagreeing and changing my mind here.
