### ISSUE TITLE
`brew info --installed --json=v2` failed `Homebrew 3.6.17-35-ga817105`

### ISSUE THREAD

**Issue by shemeshg** [Homebrew/brew#14329]
### `brew doctor` output

```shell
% brew doctor
Your system is ready to brew.
osx@osxs-Mac-mini ~ %
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
% brew info --installed --json=v2
Error: cannot load such file -- method_source
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:40:in `require'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:40:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:291:in `block in artifacts_list'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:290:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:290:in `artifacts_list'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:243:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:243:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:243:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:117:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:98:in `<main>'
osx@osxs-Mac-mini ~ % brew --version
Homebrew 3.6.17-35-ga817105
Homebrew/homebrew-core (git revision 751c1148c06; last commit 2023-01-03)
Homebrew/homebrew-cask (git revision a7b94350a7; last commit 2023-01-04)
osx@osxs-Mac-mini ~ %
```
```


### What were you trying to do (and why)?

```% brew info --installed --json=v2```

get onstalled formula and casks in v2 mode

### What happened (include all command output)?

```
% brew info --installed --json=v2
Error: cannot load such file -- method_source
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:40:in `require'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:40:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:291:in `block in artifacts_list'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:290:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:290:in `artifacts_list'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:243:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:243:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:243:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:117:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:98:in `<main>'
```

### What did you expect to happen?

get json output

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
% brew info --installed --json=v2
```

### Seems The error points to this

in  /usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb

```ruby
  def to_h
        require "method_source"

        directives.transform_values(&:source)
      end
```

 and could find no  "method_source"
 in that folder:

```shell
osx@osxs-Mac-mini artifact % echo method_*
zsh: no matches found: method_*
osx@osxs-Mac-mini artifact % ls
abstract_artifact.rb		dictionary.rb			pkg.rb				stage_only.rb
abstract_flight_block.rb	font.rb				postflight_block.rb		suite.rb
abstract_uninstall.rb		input_method.rb			preflight_block.rb		symlinked.rb
app.rb				installer.rb			prefpane.rb			uninstall.rb
artifact.rb			internet_plugin.rb		qlplugin.rb			vst3_plugin.rb
audio_unit_plugin.rb		manpage.rb			relocated.rb			vst_plugin.rb
binary.rb			mdimporter.rb			screen_saver.rb			zap.rb
colorpicker.rb			moved.rb			service.rb
osx@osxs-Mac-mini artifact %


osx@osxs-Mac-mini Homebrew % pwd
/usr/local/Homebrew/Library/Homebrew
osx@osxs-Mac-mini Homebrew % find . -type f -name "method_source*"
./sorbet/rbi/gems/method_source@1.0.0.rbi
osx@osxs-Mac-mini Homebrew %
```

**Comment by apainintheneck** [comment]
@Rylan12 This is probably related to https://github.com/Homebrew/brew/pull/14324. My guess is that the `method_source` gem will have to be vendored in.

**Comment by Rylan12** [comment]
> @Rylan12 This is probably related to https://github.com/Homebrew/brew/pull/14324. My guess is that the `method_source` gem will have to be vendored in.

Yes, I agree. I'm away from my computer right now so can't fix it quite yet. Feel free to revert or open a PR to fix if you're interested. Otherwise I'll take care of it later tonight.

**Comment by Rylan12** [comment]
@shemeshg can you run `brew update` and confirm that the issue has been fixed?

**Comment by shemeshg** [comment]
> @shemeshg can you run `brew update` and confirm that the issue has been fixed?

Confirmed.
* Json produced without errors.
* Json is valid
* Case can be closed

Thanks 
shemeshg
