### ISSUE TITLE
brew bump is giving invalid suggestion

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#14336]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.17-57-gea0b786
ORIGIN: https://github.com/Homebrew/brew
HEAD: ea0b7863883d355eb60b82e14155d8d6befc234e
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1926d1fefbc73f074f41df73ebf889260bf7e5a4
Core tap last commit: 52 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.AHMfiKLQ0p/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### The bug

```
$ brew bump --open-pr mpfr
==> mpfr
Current formula version:  4.1.0-p13
Latest livecheck version: 4.2.0
Latest Repology version:  4.2.0
Open pull requests:       none
Error: These pull requests may be duplicates:
mpfr 4.2.0 https://github.com/Homebrew/homebrew-core/pull/118066
Duplicate PRs should not be opened. Use --force to override this error.
```

1. That's weird, is a closed PR considered a duplicate?
2. OK, I will follow the suggestion:

```
$ brew bump --open-pr --force mpfr
Usage: brew bump [options] [formula|cask ...]

Display out-of-date brew formulae and the latest version available. If the
returned current and livecheck versions differ or when querying specific
formulae, also displays whether a pull request has been opened with the URL.

      --full-name                  Print formulae/casks with fully-qualified
                                   names.
      --no-pull-requests           Do not retrieve pull requests from GitHub.
      --formula, --formulae        Check only formulae.
      --cask, --casks              Check only casks.
      --open-pr                    Open a pull request for the new version if
                                   there are none already open.
      --limit                      Limit number of package results returned.
      --start-with                 Letter or word that the list of package
                                   results should alphabetically follow.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.
Error: invalid option: --force
```

So it suggested an invalid option.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump --open-pr --force mpfr
```

**Comment by MikeMcQuaid** [comment]
Yeh, I guess `--force` should be passed through to `brew bump-formula-pr`. Please follow the template format in future, makes reading the email easier to follow 🙇🏻

**Comment by fxcoudert** [comment]
Not directly related, but I'm a bit confused about the template. The main part has 4 sections:

1. What were you trying to do (and why)?
2. What happened (include all command output)?
3. What did you expect to happen?
4. Step-by-step reproduction instructions (by running `brew` commands)

Sections 1, 2 and 4 basically ask for the same thing: what I am trying to do is “the brew commands I was running”, and in step 2 it seems weird to post the output without posting the commands run. So you have to copy-paste 3 times the same commands. And in section 3 is basically part of the same as section 1 (what I expected to happen is what I wanted to achieve).

**Comment by MikeMcQuaid** [comment]
@fxcoudert the intent here is that this would have something like:

> * What were you trying to do (and why)?

Trying to bump the `mpfr` to a new version so it could be updated in homebrew/core.

> * What happened (include all command output)?

The `brew bump --open-pr mpfr` and output you provided.

> * What did you expect to happen?

Expected to either not have a `--force` flag suggested, a `--force` flag to exist and work or closed PRs to not count as duplicates.

> * Step-by-step reproduction instructions (by running `brew` commands)

- pick a formula with a closed bump PR with a matching version
- run `brew bump --open-pr mpfr`

**Comment by MaximoZarsueloJr** [comment]
> @fxcoudert the intent here is that this would have something like:
> 
> > * What were you trying to do (and why)?
> 
> Trying to bump the `mpfr` to a new version so it could be updated in homebrew/core.
> 
> > * What happened (include all command output)?
> 
> The `brew bump --open-pr mpfr` and output you provided.
> 
> > * What did you expect to happen?
> 
> Expected to either not have a `--force` flag suggested, a `--force` flag to exist and work or closed PRs to not count as duplicates.
> 
> > * Step-by-step reproduction instructions (by running `brew` commands)
> 
>     * pick a formula with a closed bump PR with a matching version
> 
>     * run `brew bump --open-pr mpfr`
