### ISSUE TITLE
brew update should use HOMEBREW_GITHUB_API_TOKEN

### ISSUE THREAD

**Issue by alanshutko** [Homebrew/brew#14335]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Many homebrew commands use HOMEBREW_GITHUB_API_TOKEN so that they are not unnecessarily rate-limited by Github.

However, update.sh does not use HOMEBREW_GITHUB_API_TOKEN when checking the upstream SHAs: https://github.com/Homebrew/brew/blob/34979a33d32f4074b34cab9113e4bd04ccdbe299/Library/Homebrew/cmd/update.sh#L626

I propose that curl pass the HOMEBREW_GITHUB_API_TOKEN in the authorization header if it has been set.

### What is the motivation for the feature?

Although update does not commonly hit the rate limit, it can hit the rate limit in environments where multiple users are behind a single egress IP, just as other homebrew commands.

### How will the feature be relevant to at least 90% of Homebrew users?

Update is used by all homebrew users

### What alternatives to the feature have been considered?

Perhaps the output of curl could be parsed to check for the rate limit, and provide error messaging to try again later.

**Comment by MikeMcQuaid** [comment]
Have you personally hit the rate limit here?

**Comment by alanshutko** [comment]
Yes, we hit it this morning, although I forgot to save the charles log.

**Comment by yonkeltron** [comment]
This is a great suggestion. I am in a company which uses a proxy cluster so this issue occurs intermittently when I am on an exit node which has hit the rate limit. Like this morning I was completely unable to `brew update` and got this message:

```bash
$ brew update
error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403
fatal: expected flush after ref listing
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Updated 1 tap (homebrew/cask).
```

A few hours later and everything works fine, oddly enough.
