### ISSUE TITLE
Brew should link prefix/man to prefix/share/man

### ISSUE THREAD

**Issue by dabrahams** [Homebrew/brew#1434]
If you install homebrew in a non-standard location like ~/brew, `man` doesn't find any of the installed docs.  However, if you add a link from ~/brew/man to ~/brew/share/man, and ~/brew/bin is in your path, it works, due to this part of the `man man` output 😉

>       Furthermore, the MANPATH_MAP statements add to the search  path  depending
>      on  your  command  search path (i.e. your PATH environment variable).  For
>       each directory that may be in  the  command  search  path,  a  MANPATH_MAP
>      statement  specifies  a  directory that should be added to the search path
>       for manual page files.  man looks at the PATH variable and adds the corre-
>       sponding  directories to the manual page file search path.  Thus, with the
>       proper use of MANPATH_MAP, when you issue the command man xyz, you  get  a
>       manual  page for the program that would run if you issued the command xyz.

**Comment by MikeMcQuaid** [comment]
As far as I can tell: it does do this: https://github.com/Homebrew/brew/blob/0028cf9fb85e7fecb4ad803a817600068c821dc9/Library/Homebrew/cmd/update-report.rb#L305-L306

Is there additional links that are expecting to be created?

**Comment by dabrahams** [comment]
I don't see the specified link in my homebrew installation.  Are you sure that code is creating the specific link I've requested?

**Comment by MikeMcQuaid** [comment]
> Are you sure that code is creating the specific link I've requested?

I'm not sure; can you reference specific, absolute paths? Thanks!

**Comment by dabrahams** [comment]
? You can replace the tildes (~) in my original report with /Users/dave and you will have the absolute paths on my system

**Comment by MikeMcQuaid** [comment]
I'm still not sure I understand. Can you detail the absolute paths of your HOMEBREW_PREFIX and HOMEBREW_REPOSITORY and the manpages you want to move. Thanks!

**Comment by dabrahams** [comment]
Never mind; I think I was wrong.  Sorry for the trouble.
