### ISSUE TITLE
info installation steps never taken

### ISSUE THREAD

**Issue by dabrahams** [Homebrew/brew#14356]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: 106af035578d5f8716ae9510c1f9ad8c19f73a79
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0676d626ee8dcd02755651a6adfb181af25440b9
Core tap last commit: 9 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 5
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 5-core 64-bit dunno
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

View installed info files associated with homebrew packages, because there's lots of useful documentation there.  Especially for emacs users, but for everyone really.

### What happened (include all command output)?

This is on a fresh VM with a freshly-installed homebrew:

```
admin@admins-Virtual-Machine ~ % brew install texinfo
==> Fetching texinfo
==> Downloading https://ghcr.io/v2/homebrew/core/texinfo/manifests/7.0.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/texinfo/blobs/sha256:2ad2c34157
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Pouring texinfo--7.0.1.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/texinfo/7.0.1: 417 files, 9MB
==> Running `brew cleanup texinfo`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
admin@admins-Virtual-Machine ~ % info
```

That results in this screen, showing no info available.

```
File: dir,      Node: Top,      This is the top of the INFO tree.

This is the Info main menu (aka directory node).
A few useful Info commands:

  'q' quits;
  'H' lists all Info commands;
  'h' starts the Info tutorial;
  'mTexinfo RET' visits the Texinfo manual, etc.













-----Info: (dir)Top, 9 lines --All----------------------------------------------
Welcome to Info version 7.0.1.  Type H for help, h for tutorial.
```

As you can see, brew has some info files installed:

```
admin@admins-Virtual-Machine ~ % ls /opt/homebrew/share/info 
info-stnd.info		texinfo.info		texinfo.info-3
texi2any_api.info	texinfo.info-1
texi2any_internals.info	texinfo.info-2
```

and many brew packages will install more there!  But, one step is missing, that's required to make newly-installed info show up everytime brew makes changes to `$HOMEBREW_PREFIX/share/info`; the step that updates the info directory file.

```
admin@admins-Virtual-Machine ~ % cd $HOMEBREW_PREFIX/share/info
admin@admins-Virtual-Machine info % for file in *; do install-info $file dir; done
admin@admins-Virtual-Machine info % info
```

As you can see, this improved the situation.

```
File: dir,      Node: Top,      This is the top of the INFO tree.

This is the Info main menu (aka directory node).
A few useful Info commands:

  'q' quits;
  'H' lists all Info commands;
  'h' starts the Info tutorial;
  'mTexinfo RET' visits the Texinfo manual, etc.

* Menu:

Texinfo documentation system
* Texinfo: (texinfo).           The GNU documentation format.
* info stand-alone: (info-stnd).
                                Read Info documents without Emacs.
* install-info: (texinfo)Invoking install-info.
                                Update info/dir entries.
* makeinfo: (texinfo)Invoking texi2any.
                                Translate Texinfo source.
* pdftexi2dvi: (texinfo)PDF Output.
                                PDF output for Texinfo.
-----Info: (dir)Top, 36 lines --Top---------------------------------------------
Welcome to Info version 7.0.1.  Type H for help, h for tutorial.
```

Please note, this is not specific to the texinfo package.  Many, many packages install info files.

### What did you expect to happen?

```
File: dir,      Node: Top,      This is the top of the INFO tree.

This is the Info main menu (aka directory node).
A few useful Info commands:

  'q' quits;
  'H' lists all Info commands;
  'h' starts the Info tutorial;
  'mTexinfo RET' visits the Texinfo manual, etc.

* Menu:

Texinfo documentation system
* Texinfo: (texinfo).           The GNU documentation format.
* info stand-alone: (info-stnd).
                                Read Info documents without Emacs.
* install-info: (texinfo)Invoking install-info.
                                Update info/dir entries.
* makeinfo: (texinfo)Invoking texi2any.
                                Translate Texinfo source.
* pdftexi2dvi: (texinfo)PDF Output.
                                PDF output for Texinfo.
-----Info: (dir)Top, 36 lines --Top---------------------------------------------
Welcome to Info version 7.0.1.  Type H for help, h for tutorial.
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install texinfo
info
```

**Comment by MikeMcQuaid** [comment]
What's the output of `env | grep INFOPATH`?

**Comment by dabrahams** [comment]
Nothing.

**Comment by gromgit** [comment]
That's probably why Homebrew didn't automatically run `install-info` at the end of each install, as it should for every install/uninstall:
```
$ brew remove -v --ignore-dependencies m4
Uninstalling /home/linuxbrew/.linuxbrew/Cellar/m4/1.4.19... (39 files, 1.1MB)
rm /home/linuxbrew/.linuxbrew/bin/m4
uninfo /home/linuxbrew/.linuxbrew/share/info/m4.info
rm /home/linuxbrew/.linuxbrew/share/info/m4.info
rm /home/linuxbrew/.linuxbrew/share/info/m4.info-1
rm /home/linuxbrew/.linuxbrew/share/info/m4.info-2
[...]

$ brew install -v m4
[...]
==> Pouring m4--1.4.19.x86_64_linux.bottle.tar.gz
tar --extract --no-same-owner --file /home/aho/.cache/Homebrew/downloads/c3563955b8307af0d683e3987968573fde3f24bb8e49cbb129aa975f064b0d6c--m4--1.4.19.x86_64_linux.bottle.tar.gz --directory /home/linuxbrew/.linuxbrew/tmp/d20230112-2364028-v0cea3
cp -pR /home/linuxbrew/.linuxbrew/tmp/d20230112-2364028-v0cea3/m4/. /home/linuxbrew/.linuxbrew/Cellar/m4
chmod -Rf +w /home/linuxbrew/.linuxbrew/tmp/d20230112-2364028-v0cea3
==> Finishing up
ln -s ../Cellar/m4/1.4.19/bin/m4 m4
ln -s ../../Cellar/m4/1.4.19/share/info/m4.info m4.info
info /home/linuxbrew/.linuxbrew/share/info/m4.info
ln -s ../../Cellar/m4/1.4.19/share/info/m4.info-1 m4.info-1
ln -s ../../Cellar/m4/1.4.19/share/info/m4.info-2 m4.info-2
[...]
```
(Note the `info`/`uninfo` lines above.)

Run `eval "$(brew shellenv)"`, then try the following:
1. Run `env | grep INFOPATH`, ensure that there's a sane value printed.
2. Run `brew rm --ignore-dependencies -v texinfo`, check for an `uninfo` progress line like above.
3. Run `info`, verify that the Texinfo-related entries have been removed.
4. Run `brew install -v texinfo`, check for an `info` progress line like above.
5. Run `info`, verify that the Texinfo-related entries are back.

As for the `brew shellenv` above, that should be in your shell startup file, as the Homebrew installer script explicitly said to do when it finished running.

**Comment by dabrahams** [comment]
> As for the brew shellenv above, that should be in your shell startup file, as the Homebrew installer script explicitly said to do when it finished running.

I'm pretty sure it didn't say that; I explicitly looked for something like that because I remembered on my ARM mac it gave me "Next steps:" for updating my zsh startup.  But I'm repeating the process in a fresh VM and we'll see what happens.

**Comment by MikeMcQuaid** [comment]
> As for the `brew shellenv` above, that should be in your shell startup file, as the Homebrew installer script explicitly said to do when it finished running.

Yup, closing this out.

**Comment by dabrahams** [comment]
@MikeMcQuaid I really don't think you should have done that.  I've attached the [full output](https://github.com/Homebrew/brew/files/10406900/brew-install.txt) of a clean installation on a brand spankin' new Ventura 13.1 Intel Mac.  As you can see there's no mention of `brew shellenv` and the next steps don't imply I have anything left to do:

```
...
==> Next steps:
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh

admin@admins-Mac ~ % env | grep INFOPATH
admin@admins-Mac ~ % 
```

**Comment by dabrahams** [comment]
Since this is closed and I don't know if it will be reopened, I opened #14362.

**Comment by MikeMcQuaid** [comment]
> As you can see there's no mention of `brew shellenv` and the next steps don't imply I have anything left to do:

That's fine: we've told you how to resolve your problem.

> Since this is closed and I don't know if it will be reopened

Don't do this, please.

> A bit premature perhaps

No. Like https://github.com/Homebrew/brew/issues/14279 this seems primarily a "your machine" problem. We don't keep issues open when they are not widely applicable. 

In future: please consider creating discussions or PRs instead of issues, thanks.

**Comment by dabrahams** [comment]
As noted in #14279 this has nothing whatsoever to do with “my machine” and I went to great lengths to ensure that.

**Comment by ywwry66** [comment]
There is actually more to the story. Info installation won't happen even if `INFOPATH` is set because `install-info` is no longer shipped with macOS Ventura. The following functions will no work with `brew install` and `brew uninstall`.
https://github.com/Homebrew/brew/blob/1447f0853bb2e9006e89d8db0289cfef9e7aa05b/Library/Homebrew/extend/pathname.rb#L346-L354

Other parts of `Homebrew` has already adapted to this change (See https://github.com/Homebrew/install/pull/700 for example). But here I don't know how to solve the issue.
