### ISSUE TITLE
Some people think brew installation should give shellenv instructions, but it doesn't

### ISSUE THREAD

**Issue by dabrahams** [Homebrew/brew#14362]
There's an inconsistency between what some brew maintainers think the installer is supposed to do on completion and what it actually does on an intel mac.  See ([#14356](https://github.com/Homebrew/brew/issues/14356#issuecomment-1380557154)) and following comments.  If those maintainers are wrong, there's a problem with info installation as noted in that issue.  If as I suspect they are right, the installer needs some ❤️

**Comment by MikeMcQuaid** [comment]
@dabrahams Please don't open new issues when we've already closed them, thanks.

**Comment by dabrahams** [comment]
@MikeMcQuaid first its arguably a different issue, and second I feel super under appreciated here. Homebrew makes big reporting very difficult, and I put in hours of effort here to get you minimal reproducers for these problems, only to  have them summarily closed. I'm not trying to be a nuisance, but to do the work to make the ecosystem better. Can't understand why you'd treat contributors this way

**Comment by MikeMcQuaid** [comment]
@dabrahams I'm sorry you feel underappreciated, that was not my intention ❤️ 

I know you're trying to help but, to flip it around to our perspective: these cases look an awful lot like things that are specific to your particular setup and not typical to most of our users.

Also, hope this doesn't come across as mean: we don't consider opening issues to be a contribution. Ultimately any issue that is opened and needs code to fix it requires someone to write, test, review and merge that code.

**Comment by dabrahams** [comment]
>  these cases look an awful lot like things that are specific to your particular setup

How can these cases possibly look specific to my setup when I go to the effort to make a clean VM and a fresh brew install for reproduction? I do this precisely to take “my particular setup” out of the equation!

I should add that my normal setup almost NEVER has clean brew doctor output, for whatever reason.
> and not typical to most of our users.
> 
If my reports seem atypical maybe it’s because I am willing to go to great lengths to get you useful information, while many other users can’t get past step 1 with y’all, either because doctor output is unclean and they don’t know how to fix it or because you treat them as nuisances rather than as contributors.
> Also, hope this doesn't come across as mean: we don't consider opening issues to be a contribution. Ultimately any issue that is opened and needs code to fix it requires someone to write, test, review and merge that code.
> 
It’s not mean; it’s just incredibly shortsighted.  I’m not qualified to fix every problem I find, and brew itself, besides being written in a language I don’t know, seems to have a very particular culture that creates an extra learning curve for code contributors.  If you treat even legitimate, well-researched issue reports as a drain on your resources, the overall effort it will take to address problems will be much greater, and will affect many more people than those whose reports you reject, because most people don’t report the problems they encounter.

Seems to me the barrier to entry for even pressing the issue creation button is so high that if you want to continue to improve your project, you ought to treat people who successfully run that gauntlet better.  But, it’s your project, and (you’ve made this quite clear) not mine.  Don’t worry, I won’t waste any more of your time.

**Comment by MikeMcQuaid** [comment]
> How can these cases possibly look specific to my setup

Your setup does not have you running `brew shellenv` or setting `INFOPATH` but relying on `INFOPATH` being used correctly. Ok, this is not specific to only you but it is a niche problem that is not widely raised. We are a small team of volunteers and have to triage and prioritise problems that affect multiple people. If your issues had multiple others jumping in saying "me too!": they would be treated differently.

> they don’t know how to fix it or because you treat them as nuisances rather than as contributors

We do not treat them as nuisances. There is a fine line between "support request" and "bug report" and our issue template is designed to balance that and direct more of the prior to Homebrew's discussions.

> I’m not qualified to fix every problem I find, and brew itself, besides being written in a language I don’t know

I had never written any Ruby or used Git before I worked on Homebrew. I ended up writing some (poor) Ruby and now I write Ruby for a living. Everyone is different, sure, but: this is open source. If you really want your problems resolved, you are capable of learning what's required to do so. Many high school and college students with dramatically less experience than you are too.

> seems to have a very particular culture that creates an extra learning curve for code contributors

Funnily enough: I've had literally hundreds of people say the opposite.

> and will affect many more people than those whose reports you reject

I disagree and I've read a few Homebrew issues over the last 13 years working on it.

> if you want to continue to improve your project

We are improving the project. Time spent resolving and discussing your `INFOPATH` issue is time not spent e.g. [speeding up Homebrew's update and installation time for everyone](https://github.com/Homebrew/brew/issues/14009). Maintainer time is finite and zero-sum. I'm sorry if it's frustrating to hear that the problems you have experienced are not deemed high enough priority to keep open. The best way to resolve this is, as above, to attempt to fix them yourself.

> But, it’s your project, and (you’ve made this quite clear) not mine.

I'm not sure how I've made this quite clear other than to treat you the same as we treat everyone else.

But, yes, you'll notice that I don't make a habit of posting on other project's issue trackers telling their maintainers how they should be running their projects. Perhaps that's something you should consider too.

**Comment by Panajev** [comment]
@MikeMcQuaid given https://github.com/gromgit/homebrew-install/commit/2430c22eecad08ebd32a678fb60335b17f4c525b is it possible that on Intel systems the instructions  are not printed and thus the bug report is valid.

I personally think there a bit of talking over the reporter, but without malice. In short this Issue is not the same issue as the well documented but separate issue: the other was essentially about the effect this is more about the cause and they should be separate.

What I observed Dave doing (not that I am biased because of his Swift past, he likes C++ I mean eew ;) j/k):

Setting up a fresh VM on an Intel machine(macOS I assume), installing Brew itself with full detailed instructions, and printing the whole terminal logs... 


Now, if the shellenv command suggestion is missing in those logs then we have a problem with brew. I assume a lot of macOS people have moved to Apple silicon and others got the warning in other places doing other things with brew or read it online or like me had it in their Starter setup scripts, etc...
In this case this issue is separate and I think well documented Issue reports should be welcomed. It seems some people, see https://github.com/gromgit/homebrew-install/commit/2430c22eecad08ebd32a678fb60335b17f4c525b, are trying to contribute change requests too.
