### ISSUE TITLE
Add a strict flag to the installation command

### ISSUE THREAD

**Issue by bode-fun** [Homebrew/brew#14361]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

If one would specify the --strict flag on the install command and would try to install a formula or cask, which is not available in the specified version, return a non-0 exit code instead of suggesting a different version. This would make scripting easier.

Example:

```sh
brew install --strict python@3.10.5 || echo "not available"
# not available
```

### What is the motivation for the feature?

I wanted to use homebrew in a script.

### How will the feature be relevant to at least 90% of Homebrew users?

I'm not sure, that it is. It would be relevant to everyone who wants to use homebrew in a script. 

### What alternatives to the feature have been considered?

At the moment none. I am however open to suggestions.

**Comment by bode-fun** [comment]
Instead of --strict, --fail-on-warning, which is already part of homebrew in some places, would be a good flag🤔

**Comment by MikeMcQuaid** [comment]
Can you provide the output that you're currently seeing and an example of the output you're wanting to see? Thanks!

**Comment by bode-fun** [comment]
Currently, I am seeing the following output:

![grafik](https://user-images.githubusercontent.com/115655929/212284440-94dfd4c4-91f3-40fa-9e5e-85773fe00f87.png)

I would like to see the following:

![grafik](https://user-images.githubusercontent.com/115655929/212285588-e52bb4fe-93ed-4ca4-99ac-e3f546aa3432.png)

```
Warning: No available formula with the name "python@3.11.1". Did you mean python@3.11 or python@3.10?
==> Searching for similarly named formulae...
==> Formulae
python@3.11 ✔                                                                                  python@3.10 ✔

To install python@3.11 ✔, run:
  brew install python@3.11 ✔
Return Code: 1
````

**Comment by MikeMcQuaid** [comment]
Gotcha. Agreed with exit code change, this behaviour does not seem correct.

**Comment by bode-fun** [comment]
I would love to change it without passing any flags, but I fear that it would break some existing scripts

**Comment by apainintheneck** [comment]
We currently return success whenever a package is installed correctly or we're able to find a similarly named package that might be what the user meant to install. I like the idea of adding something like this to facilitate scripting.

We currently have a `--strict` option for three subcommands. `brew linkage --strict` is similar to how you want `brew install --strict` to behave.

https://github.com/Homebrew/brew/blob/344d32bf7f40183359592ef81ca6486e0587981b/Library/Homebrew/dev-cmd/linkage.rb#L23-L25

https://github.com/Homebrew/brew/blob/344d32bf7f40183359592ef81ca6486e0587981b/Library/Homebrew/dev-cmd/audit.rb#L36-L37

https://github.com/Homebrew/brew/blob/344d32bf7f40183359592ef81ca6486e0587981b/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L45-L46

**Comment by apainintheneck** [comment]
We could just fail whenever we're not able to install a package. Call me an optimist but I doubt people really rely on the current behavior.
