### ISSUE TITLE
git formula breaks brew update

### ISSUE THREAD

**Issue by ddbeck** [Homebrew/brew#1437]
If the `git` formula is installed, then running `brew update` results in the following error messages:

```
fatal: unable to access 'https://github.com/Homebrew/brew/': SSL: can't load CA certificate file /usr/local/share/ca-bundle.crt
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': SSL: can't load CA certificate file /usr/local/share/ca-bundle.crt
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': SSL: can't load CA certificate file /usr/local/share/ca-bundle.crt
fatal: unable to access 'https://github.com/Homebrew/homebrew-dupes/': SSL: can't load CA certificate file /usr/local/share/ca-bundle.crt
Error: Fetching /usr/local/Homebrew failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes failed!
```

I've put an example of this behavior playing out in [this gist](https://gist.github.com/ddbeck/3b905c41492df227c109c70133e19a60) along the output of `brew config`. `brew doctor` returns only `Your system is ready to brew.` If I uninstall the git formula (i.e., run `brew uninstall git`), then `brew update` works as expected.

That said, I found this difficult to narrow down to the git formula. If I reinstall the git formula and immediately re-run `brew update` then there are no errors. It continues to work as expected for a few hours, but at some point the errors always return (e.g., if I reinstall the Git formula in the afternoon, the error has always returned by the next morning, though often sooner). but uninstalling the git formula _always_ immediately eliminates the errors.

I'm not really sure where to go from here to figure out this problem. I would welcome some suggestions to help me figure out if this is a problem with me, my machine, the Git formula, or Homebrew. Thank you!

**Comment by MikeMcQuaid** [comment]
> If I reinstall the git formula and immediately re-run brew update then there are no errors.

It's likely for you `brew update --force` will reproduce this every time.

This is not reproducible for me. You have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by ddbeck** [comment]
You're right, `brew update --force` reproduces the problem.

When I reviewed the troubleshooting page before submitting my issue, this is what I did:

* I ran (the working iteration) of `brew update` twice (after recording the error-and-resolution example in my gist).
* I ran `brew doctor` and there were no errors.
* My issue was not covered by any of the issues on the _Common Issues_ page.
* My issue is not related to Java, so I didn't install Java.
* I checked that XCode and the command line tools are up to date. They were.
* My issue does not concern permissions errors, so I skipped the permission check step.
* I checked the issue tracker for my issue several times.
* My issue does not concern a failed build, so I skipped the `brew gist-logs` step.
* I uploaded the results of `brew config` to [the gist I mentioned previously](https://gist.github.com/ddbeck/3b905c41492df227c109c70133e19a60).
* I quoted the `brew doctor` output.

Upon reading over the _Troubleshooting_ page a second time, I found that I did fail to mention my OS X version (10.11.6) though it's in the gist output from the config command.

What have I missed, exactly?

**Comment by ilovezfs** [comment]
Are you using the git bottle?

**Comment by MikeMcQuaid** [comment]
> My issue does not concern a failed build, so I skipped the brew gist-logs step.

That document should probably clarify that it's useful for any formulae-specific issues. Can we see your `brew gist-logs git` and `brew info git`? Thanks!

**Comment by ddbeck** [comment]
> Are you using the git bottle?

Yes, I've updated the reproduction of the error in [this gist](https://gist.github.com/ddbeck/3b905c41492df227c109c70133e19a60) to reflect the installation of the Git bottle and the reproduction with `brew update --force`.

> That document should probably clarify that it's useful for any formulae-specific issues. Can we see your brew gist-logs git and brew info git? Thanks!

Yes, here's the [the gist from `brew gist-logs git`](https://gist.github.com/anonymous/725ec236362beb02392ff3aecd605281).

And I'd be happy to open a pull request to revise the troubleshooting doc, though `brew help gist-logs` also implies that gist-logs is intended only for failed builds. I'm not sure where I'd look to update that.

**Comment by ilovezfs** [comment]
Do you have any SSL related settings in your environment variables? Is brew openssl installed?

**Comment by ddbeck** [comment]
> Do you have any SSL related settings in your environment variables?

It doesn't look like it (though I'll admit to not recognizing every single thing that shows up when I run `env`).

> Is brew openssl installed?

Yes, it is. I think it was installed when I installed the python formula.

**Comment by ilovezfs** [comment]
I'd try uninstalling `openssl` and `hub` if you have it installed, and see if it's still reproducible.

**Comment by ddbeck** [comment]
I didn't have `hub` installed, but I uninstalled `openssl` and the behavior was the same.

**Comment by ilovezfs** [comment]
Please check if `SSL_CERT_FILE` is set in the environment.

**Comment by ddbeck** [comment]
It is not set.

**Comment by ilovezfs** [comment]
Please try creating a dummy user account and see if it happens there.

**Comment by ddbeck** [comment]
OK, I created a new user account and `brew update` fails complaining about permissions and I wasn't sure whether that was expected or not (I'm willing to go through steps to fix that, if it's needed to diagnose this issue). Trying a command like `git clone https://github.com/Homebrew/brew` still produces a `fatal: unable to access 'https://github.com/Homebrew/brew/': SSL: can't load CA certificate file /usr/local/share/ca-bundle.crt` error on the dummy account. I don't know whether that's permissions-related or not though.

**Comment by ilovezfs** [comment]
The permissions error would be expected, but if you get the same error just running `it clone https://github.com/Homebrew/brew` then it's not specific to the original user, which makes me think it's specific to the brew installation. Is there anything in your `/usr/local/etc/gitconfig`?

**Comment by ddbeck** [comment]
Aha, I think you found the problem! This is the entire contents of `/usr/local/etc/gitconfig/`:

```
[http]
	sslcainfo = /usr/local/share/ca-bundle.crt
```

If I comment out that `sslcainfo` line, everything works as expected. I have no idea where that line came from, unfortunately (I certainly didn't add it myself—I didn't know this file existed until now).

I'm sorry I didn't catch this before; I could've sworn I grepped for `/usr/local/share/ca-bundle.crt` before I opened the issue. Unless you think it's worth investigating the cause, I think this issue is resolved. Thank you for your help!

**Comment by ilovezfs** [comment]
You're welcome! The contents of that file should be
```
[credential]
	helper = osxkeychain
```
If you remove the file and then `brew reinstall git` it should install the default file with those contents.

For what it's worth, I ran `strings /usr/local/bin/git | less` and then searched for instances of `/usr/local` since you said it was specific to brew's git, and one such string is `/usr/local/etc/gitconfig`, which is the hard-coded default location.

The underlying issue is that we respect preexisting files in `/usr/local/etc` so once a file like that gets messed up, reinstalling won't actually help unless you removing the offending file first.
