### ISSUE TITLE
A minimal version of Homebrew

### ISSUE THREAD

**Issue by landinged** [Homebrew/brew#14379]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I suggest to provide a minimal version of Homebrew.
If possible to reduce the size of current Homebrew, it will be better than providing a minimal version.

### What is the motivation for the feature?

My case is: 
1. I just need 2-3 packages (in macOS) which are provided by Homebrew. 
2. The bandwidth is limited. The installation of Homebrew will cost more than 1 hour.
3. I don't want to use un-official repository. 

### How will the feature be relevant to at least 90% of Homebrew users?

I am not sure about this.

### What alternatives to the feature have been considered?

run a container or virtual machine, in order to use Linux command tools.

**Comment by MikeMcQuaid** [comment]
Try `export HOMEBREW_INSTALL_FROM_API=1` to beta test a new approach here. Hopefully that's enough, if not: we can't really do better, sorry.
