### ISSUE TITLE
Homebrew announces "Homebrew has enabled anonymous aggregate user behaviour analytics" even with HOMEBREW_NO_ANALYTICS=1

### ISSUE THREAD

**Issue by DavidCWGA** [Homebrew/brew#144]
To reproduce:

1. Install a version of Homebrew prior to the update with analytics
2. Set HOMEBREW_NO_ANALYTICS=1
3. Run "brew update"

You will receive the message "==> Homebrew has enabled anonymous aggregate user behaviour analytics" - but this should not be true with HOMEBREW_NO_ANALYTICS set to 1.

I'm assuming that analytics weren't *actually* enabled, it's just that the message is output regardless. (Not tested.)

**Comment by achikin** [comment]
Just tried to reproduce - haven't seen any message about analytics at all.

**Comment by pjvandehaar** [comment]
Didn't reproduce for me either.  Did you use `export HOMEBREW_NO_ANALYTICS=1`?

**Comment by DavidCWGA** [comment]
$ echo $HOMEBREW_NO_ANALYTICS
    1

Of course now I've already upgraded it means I can't re-test, but it's slightly concerning that my Homebrew install might be ignoring the opt-out var.

It should provide a way to confirm that analytics are disabled.

**Comment by pjvandehaar** [comment]
Sorry, my mistake.  I meant that you should run `env | grep HOMEBREW_NO_ANALYTICS`.  I think that will check whether you've exported the variable, which will make it available to the programs that you run.

Try `git config --file="$(brew --repository)/.git/config" --get homebrew.analyticsdisabled`.

**Comment by DavidCWGA** [comment]
$ env | grep HOMEBREW_NO_ANALYTICS
    HOMEBREW_NO_ANALYTICS=1

(It's set in my .bashrc so it should always be set.)

    $ git config --file="$(brew --repository)/.git/config" --get homebrew.analyticsdisabled
    true

(Of course this is all post-update.)

**Comment by DomT4** [comment]
> but it's slightly concerning that my Homebrew install might be ignoring the opt-out var.

It's not ignoring the variable.
```
HOMEBREW_ANALYTICS_DEBUG=1 brew info openssl
```

If the start of that `brew info openssl` command isn't prepended with a `curl` output no analytics are being executed, period.

As documented, even if analytics are disabled, running under that env will prevent any analytics from being sent for the duration. Just shows you what the execution would look like:
> You can also view all the information that is sent by Homebrew's analytics by setting HOMEBREW_ANALYTICS_DEBUG=1 in your environment. Please note this will also stop any analytics being sent.

**Comment by mikemcquaid** [comment]
As @DomT4 mentioned this has been fixed (if it was an issue) and you can verify this with `HOMEBREW_ANALYTICS_DEBUG=1` or by tracing through the code.

**Comment by apjanke** [comment]
Details: it was an issue for a while yesterday. The message was being spuriously displayed; `brew` was still respecting `HOMEBREW_NO_ANALYTICS` even when the message was displayed. Fixed by #154 and #155.
