### ISSUE TITLE
Consider removing tcl-tk from uses_from_macos audit

### ISSUE THREAD

**Issue by willcohen** [Homebrew/brew#14405]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

As implemented in https://github.com/Homebrew/brew/blob/8cdb3d2a896d09d46b065fa16f4af90c5832c78b/Library/Homebrew/rubocops/uses_from_macos.rb#L54, `brew audit` for new formulae makes it unworkable to pass CI with new Tcl packages -- the new packages require the homebrew `tclsh`, as noted by @gromgit in https://github.com/Homebrew/homebrew-core/pull/120817#issuecomment-1387202210. Existing formulae, like `expect` use this logic.

### What is the motivation for the feature?

Pass CI with https://github.com/Homebrew/homebrew-core/pull/120817 for `bwidget`'s inclusion as a package.

### How will the feature be relevant to at least 90% of Homebrew users?

`bwidget` will be available as a package -- relevant in the sense that they can use it, not that they are all installing Tcl packages, of course.

### What alternatives to the feature have been considered?

Using `uses_from_macos` instead of `depends`, which has the caveats noted by @gromgit in https://github.com/Homebrew/homebrew-core/pull/120817#issuecomment-1387202210.

Alternately, the formula could be approved ad-hoc for merge with an understanding that audit is providing a 'false positive', even if the audit logic doesn't change.

**Comment by MikeMcQuaid** [comment]
It's acceptable to ignore this `uses_from_macos` audit; it exists to verify that you've tried using the system macOS version rather than jumping straight to the dependency.

**Comment by willcohen** [comment]
Many thanks!
