### ISSUE TITLE
Formula renames are checked even when `--cask` is given

### ISSUE THREAD

**Issue by muzimuzhi** [Homebrew/brew#14438]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-122-g1c85a71
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c85a717ccd49fa0900379896284012b3f43f920
Last commit: 35 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c1408e72eaa44545ead62fff22a0866a42033ae
Core tap last commit: 2 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.2-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

### What were you trying to do (and why)?

Run `brew install --cask racket` to install the cask `racket`.

Why not just `brew install racket`? Because it will install formula `minimal-racket` according to an entry `"racket": "minimal-racket"` in [`formula_renames.json`](https://github.com/Homebrew/homebrew-core/blob/820fbff6f3655f536ccc3abeb06b6197bee9bae5/formula_renames.json#L131).

### What happened (include all command output)?

A warning is thrown,
```
Warning: Use minimal-racket instead of deprecated racket
```
This warning is so misleading that I'm not the only one that believed the formula `minimal-racket` will be installed. But actually it still installs cask `racket`. See https://github.com/orgs/Homebrew/discussions/3510.

```
Warning: Use minimal-racket instead of deprecated racket
==> Downloading https://mirror.racket-lang.org/installers/8.7/racket-8.7-x86_64-macosx-cs.
######################################################################## 100.0%
==> Installing Cask racket
==> Moving App Suite 'Racket v8.7' to '/Applications/Racket v8.7'
==> Linking Binary 'drracket' to '/usr/local/bin/drracket'
...
==> Linking Manpage 'drracket.1' to '/usr/local/share/man/man1/drracket.1'
...
🍺  racket was successfully installed!
```

### What did you expect to happen?

When `--cask` is used, don't check and prompt about formula renaming.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just run `brew install --cask --dry-run racket` and you'll see

Warning: Use minimal-racket instead of deprecated racket
```

**Comment by MikeMcQuaid** [comment]
ooo, good catch here, thanks for reporting!
