### ISSUE TITLE
(bug?) brew install --HEAD no longer working

### ISSUE THREAD

**Issue by vegerot** [Homebrew/brew#14430]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libMsgCom.dylib
  /usr/local/lib/libSysCtlCom.dylib
  /usr/local/lib/libwep_airdrop.dylib
  /usr/local/lib/libwep_burn.dylib
  /usr/local/lib/libwep_cbcarbon.dylib
  /usr/local/lib/libwep_cbcocoa.dylib
  /usr/local/lib/libwep_chrome.dylib
  /usr/local/lib/libwep_dutil.dylib
  /usr/local/lib/libwep_ff.dylib
  /usr/local/lib/libwep_icloud.dylib
  /usr/local/lib/libwep_mail.dylib
  /usr/local/lib/libwep_post.dylib
  /usr/local/lib/libwep_printer.dylib
  /usr/local/lib/libwep_screen.dylib
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-97-g71fab93
ORIGIN: https://github.com/Homebrew/brew
HEAD: 71fab93983b47c73b3a36b24543a1adcea290044
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2b72f7be6e4eccdb7175c4d5ab6f3d7bdfea04f2
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

### What were you trying to do (and why)?

Build HEADs of packages from source

### What happened (include all command output)?

```sh
❯ brew install --HEAD tmux
Error: No head is defined for tmux
```

```sh
❯ brew install --HEAD --build-from-source neovim
Error: No head is defined for neovim
```

```sh
❯ brew install --HEAD git
Error: No head is defined for git
```

etc.

### What did you expect to happen?

Homebrew builds the heads of these packages from source.

This is how I've installed dozens of packages in the past, but now I can no longer install these same packages the same way.  I looked at the formulae and confirmed they still have `head` sections

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
note: I don't think my `brew doctor` output affects this bug


brew install --HEAD neovim
```

**Comment by carlocab** [comment]
Do
```
export HOMEBREW_NO_INSTALL_FROM_API=1
```
then try again.

If that fixes it, we probably want to have a better error message here.

**Comment by steakknife** [comment]
Just what every user wants: a magic environment variable to continue to use things while breaking them in undocumented and unclear ways.

And default-specified branches for gitlab are broken (tries to clone master instead of explicit main). Good luck all. Forget this. Nix is better.

**Comment by vegerot** [comment]
> Do
> 
> ```
> export HOMEBREW_NO_INSTALL_FROM_API=1
> ```
> 
> then try again.
> 
> If that fixes it, we probably want to have a better error message here.

That did fix it!  Thank you.

@carlocab question: what is the point of this environment variable?  With all due respect, `brew install --HEAD neovim` was fine for me before, and there's still lots of documentation on the internet telling users to run `brew install --HEAD`.

**Comment by MikeMcQuaid** [comment]
> With all due respect, `brew install --HEAD neovim` was fine for me before, and there's still lots of documentation on the internet telling users to run `brew install --HEAD`.

We will fix this to make it better supported/more automatic soon.

**Comment by vegerot** [comment]
And why make it stop working before making it better supported?

I totally get this stuff is hard, and it's possible you just forgot about it.  This issue only has three reactions, but given how many people use `brew install --HEAD` every day I suspect waaaay more people ran into this issue.

I'm just trying to figure out if you realized at the time this would [break my workflow](https://xkcd.com/1172/) (but decide that was fine and you'd fix it later) or this was a totally understandable oversight and now working on improving it?

**Comment by MikeMcQuaid** [comment]
> And why make it stop working before making it better supported?

It still works, you just need to pass a different flag.

> This issue only has three reactions, but given how many people use `brew install --HEAD` every day I suspect waaaay more people ran into this issue.

This only affects people who aren't on a stable tag.

> break my workflow

😂 

> (but decided that was fine and you'd fix it later) or this was a totally understandable oversight and now working on improving it?

Honestly: a bit of both. We'd fixed all the issues we knew about or had thought about but, in these cases, with how few maintainers we have on Homebrew, how widely its used and how many people use it: unfortunately the only way to ensure that all these sort of issues get resolved is to test them on real users.

@Rylan12 @SMillerDev and myself have all been using `HOMEBREW_INSTALL_FROM_API` and fixed problems we encountered along the way for ~6 months. I don't use `--HEAD` or I'd have noticed (and fixed!) this. I'm sorry for the inconvenience and thank you for making this PR.

**Comment by strager** [comment]
Possibly related: When bumping a version for my package (quick-lint-js; https://github.com/Homebrew/homebrew-core/pull/122009), I needed to run with `HOMEBREW_NO_INSTALL_FROM_API=1`. Otherwise, Homebrew ignored my local changes in the file opened by `brew edit`, which was very confusing.
