### ISSUE TITLE
Restart services without requiring a network connection

### ISSUE THREAD

**Issue by log-to-code** [Homebrew/brew#14445]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Allow restarting a service from a custom formula without a network connection

```
$ sudo brew services restart brewy
Password:
curl: (28) Operation timed out after 5004 milliseconds with 0 bytes received
curl: (28) Operation timed out after 5000 milliseconds with 1086245 out of 3444951 bytes received
curl: (28) Operation timed out after 5000 milliseconds with 1266478 out of 3444951 bytes received
curl: (28) Operation timed out after 5001 milliseconds with 1019493 out of 3444951 bytes received
```

### What is the motivation for the feature?

Restarting services when you don't have internet

### How will the feature be relevant to at least 90% of Homebrew users?

Being able to work offline

### What alternatives to the feature have been considered?

None

**Comment by MikeMcQuaid** [comment]
Can you do the same thing with no internet and `--debug --verbose`, please? Also, where is the custom formula from, does it do the same thing with homebrew/core formulae or not? Thanks!

**Comment by log-to-code** [comment]
I was able to get the service restart command to work by running `export HOMEBREW_NO_INSTALL_FROM_API=1` first. Would incorrect file permissions cause this? My custom formula had to change ownership of files.
> Warning: Taking root:admin ownership of some brewy paths:

Restarting `postgresql` and `redis` core formulae also doesn't work.

```
$ brew services restart redis
curl: (7) Couldn't connect to server
Error: Failure while executing; `/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-143-g10845a1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --fail --progress-bar --max-time 5 --retry 3 --location --remote-time --output /Users/bob/Library/Caches/Homebrew/api/formula.json --time-cond /Users/bob/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json` exited with 7. Here's the output:
curl: (7) Couldn't connect to server
```

Here's the output with --debug --verbose`:
```
$ sudo brew services restart brewy --debug --verbose
```

```
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/2.X.Y\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/bob/Library/Caches/Homebrew/api/formula.json --time-cond /Users/bob/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
curl: (7) Couldn't connect to server
Error: Failure while executing; `/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/2.X.Y\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/bob/Library/Caches/Homebrew/api/formula.json --time-cond /Users/bob/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json` exited with 7. Here's the output:
curl: (7) Couldn't connect to server

/opt/homebrew/Library/Homebrew/system_command.rb:302:in `assert_success!'
/opt/homebrew/Library/Homebrew/utils/curl.rb:164:in `curl'
/opt/homebrew/Library/Homebrew/utils/curl.rb:197:in `curl_download'
/opt/homebrew/Library/Homebrew/api.rb:50:in `fetch_json_api_file'
/opt/homebrew/Library/Homebrew/api/formula.rb:21:in `all_formulae'
/opt/homebrew/Library/Homebrew/formulary.rb:678:in `loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:561:in `factory'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:89:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

**Comment by rami3l** [comment]
@log-to-code Hi!
I encountered a similar situation where:

* I cannot run `brew cleanup` offline.
* `brew upgrade` is painstakingly slow.

After some investigation it seems that the problem is in the `CaskLoader` class.
The `load` method in this class seems to have launched `curl` more often than necessary, even when we refer to locally-installed casks.

However I don't believe that I know enough of Ruby/Brew to fix this myself :/

**Comment by log-to-code** [comment]
`brew` with `HOMEBREW_NO_INSTALL_FROM_API=1` stopped working but I figured out that homebrew developer mode was enabled.

To restore functionality:
1. Remove all files of your custom formula. Search for them with `find $(brew --prefix) ~/Library/LaunchAgents -iname '*YOUR_FORMULA_NAME*'`.
2. Disable developer mode by running `brew developer off`.
