### ISSUE TITLE
generate_completions_from_executable can cause unexplained hang

### ISSUE THREAD

**Issue by cblecker** [Homebrew/brew#14448]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-143-g10845a1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 10845a1122b916dc91d04f00a4d8b7b888d52654
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a246363012eb92ffe3fc4c3a0f5f4ab0969cde3f
Core tap last commit: 35 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I was updating a formula in my own tap, and the upgrade would hang. After plenty of diagnosis, I was able to identify the culprit as the `generate_completions_from_executable` function.

This function when used in a formula doesn't seem to have a timeout, and if the process it's running is asking for interactive input, it will just run indefinitely.

The utility I was updating the formula for had created an interactive prompt that happened before any command output, including the completion. This was a bug on the utilities side, but it took a while to diagnose because of the hidden output from the `generate_completions_from_executable` function. It would be great if this function was able to output it's actions in some logs, so it's easier to diagnose issues. It may also be helpful to have some sort of timeout able to be applied to this function.

### What happened (include all command output)?

==> Fetching cblecker/tap/osdctl
==> Cloning https://github.com/openshift/osdctl.git
Updating /Users/cblecker/Library/Caches/Homebrew/osdctl--git
==> Checking out tag v0.13.5
HEAD is now at edee89e Merge pull request #318 from wshearn/rotatefixes
HEAD is now at edee89e Merge pull request #318 from wshearn/rotatefixes
==> Reinstalling cblecker/tap/osdctl 
==> goreleaser build --rm-dist --single-target --output=/opt/homebrew/Cellar/osdctl/0.13.5/bin/osdctl

(it would just hang here)

### What did you expect to happen?

The brew command to timeout or provide helpful logs to track down the issue in the application

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Create a formula using `generate_completions_from_executable`, but have the command it runs wait for interactive input. This will cause the install to hang.
```

**Comment by MikeMcQuaid** [comment]
> but have the command it runs wait for interactive input

Note that this is the case for pretty much anything you do in a formula or test, unfortunately. We can't have a timeout here given how long it takes some formulae to build.
