### ISSUE TITLE
`brew update` is not updating Taps but it is updating Formulae

### ISSUE THREAD

**Issue by thecesrom** [Homebrew/brew#14447]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-143-g10845a1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 10845a1122b916dc91d04f00a4d8b7b888d52654
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bbc8cb7036035be77b110af614015e343d11a80a
Core tap last commit: 75 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 3
HOMEBREW_EDITOR: nano
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I tried to run `brew update` because that's what would normally do.

### What happened (include all command output)?

```sh
$ brew update
Already up-to-date.
```

### What did you expect to happen?

It should have updated all Taps.

### Step-by-step reproduction instructions (by running `brew` commands)

1. Run `brew update`
2. It says it's up-to-date
3. `cd /opt/homebrew/Library/Taps/homebrew/homebrew-core`
4. Run
  ```sh
  $ git status
  On branch master
  Your branch is behind 'origin/master' by 4 commits, and can be fast-forwarded.
    (use "git pull" to update your local branch)
  
  nothing to commit, working tree clean
  ```
  

https://github.com/Homebrew/homebrew-core/pull/121684 just got merged and after running `brew update && brew outdated && brew upgrade` this is what I got:

```sh
$ brew update && brew upgrade
Already up-to-date.
gh (2.22.0) < 2.22.1
==> Upgrading 1 outdated package:
gh 2.22.0 -> 2.22.1
```

`gh` installed fine, but still the `homebrew-core` git status says it's behind.

```sh
$ gh --version
gh version 2.22.1 (2023-01-27)
https://github.com/cli/cli/releases/tag/v2.22.1
$ brew livecheck gh                
gh: 2.22.0 ==> 2.22.1
```

Refs: https://github.com/orgs/Homebrew/discussions/4105, https://github.com/orgs/Homebrew/discussions/4134

**Comment by thecesrom** [comment]
I untapped core and cask, tapped again and this is my current status:

```sh
$ git status                  
On branch master
Your branch is behind 'origin/master' by 34 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
$ git log
commit ebae02f411aa5dcd505e9f13649e4eb0b5708ec0 (HEAD -> master)
Author: BrewTestBot <1589480+BrewTestBot@users.noreply.github.com>
Date:   Fri Jan 27 19:04:12 2023 +0000

    gh: update 2.22.1 bottle.
...
```

I have not changed a thing on my machine and started noticing this problem today.

**Comment by thecesrom** [comment]
Furthermore, this seems to only affect core and cask.

```sh
$ pwd
/opt/homebrew/Library/Taps/homebrew
$ tree -d -L 1
.
├── homebrew-bundle
├── homebrew-cask
├── homebrew-cask-drivers
├── homebrew-cask-fonts
├── homebrew-cask-versions
├── homebrew-command-not-found
├── homebrew-core
└── homebrew-services
$ getrepostatus
Getting status for homebrew-bundle
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean


Getting status for homebrew-cask
On branch master
Your branch is behind 'origin/master' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean


Getting status for homebrew-cask-drivers
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean


Getting status for homebrew-cask-fonts
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean


Getting status for homebrew-cask-versions
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean


Getting status for homebrew-command-not-found
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean


Getting status for homebrew-core
On branch master
Your branch is behind 'origin/master' by 34 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean


Getting status for homebrew-services
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by gromgit** [comment]
> ```shell
> HOMEBREW_INSTALL_FROM_API: set
> ```

You have local core/cask repos, but are setting this?

**Comment by thecesrom** [comment]
> `HOMEBREW_INSTALL_FROM_API` is the default now

If this is not set, how would `brew livecheck` work properly?

**Comment by Rylan12** [comment]
> > `export HOMEBREW_NO_INSTALL_FROM_API=1`
> 
> If this is not set, how would `brew livecheck` work properly?

In order to run `brew livecheck`, you need to have the full formula/cask files tapped locally. So, not setting `HOMEBREW_NO_INSTALL_FROM_API` means that you won't be able to use `brew livecheck` at the moment.

I'll admit that we haven't nailed the handing of API installs for Homebrew developers so this is a bit unintuitive at the moment. We're working on improving that.

**Comment by gilzow** [comment]
I too am having the same issue with `gh` and brew. [Initially posted over in the gh repo](https://github.com/cli/cli/issues/6949).  Followed the suggestions above but am still unable to update `gh` to the version brew says is available. 

Happy to provide additional details as needed.

**Comment by starpit** [comment]
Has this been fixed? I have multiple casks, one in the main cask tap, and one in a custom tap, and neither wants to upgrade. Only when I untap the custom tap and retap it will `brew install` correctly pick up the latest version (not sure how to simulate this effect for the main cask tap).

This was fine until recently. I also recently upgraded macos 12 -> 13.2, but i suspect that is a red herring?

**Comment by gromgit** [comment]
@gilzow What's the output of `brew config` and `brew doctor`?

**Comment by MikeMcQuaid** [comment]
@gilzow This is a gh issue, it should probably change how it gathers update information.
