### ISSUE TITLE
`brew update` only reporting some modified taps and formulae/casks even is `HOMEBREW_UPDATE_REPORT_ALL_FORMULAE` is set

### ISSUE THREAD

**Issue by JLP04** [Homebrew/brew#14449]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  tilp
  libtifiles
  gfm
  libudfread
  libticalcs
  OpenGL
  xdg-utils

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  caffe

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  cmake
  python@3.10
  python@3.11
  python@3.8
  python@3.9
  cmake-docs
  OpenGL
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-143-g10845a1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 10845a1122b916dc91d04f00a4d8b7b888d52654
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9ad93a700802b48d4e972e9e8802187ba48f73b2
Core tap last commit: 24 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--colorpickerdir=/Library/ColorPickers", "--prefpanedir=/Library/PreferencePanes", "--qlplugindir=/Library/QuickLook", "--screen_saverdir=/Library/Screen Savers", "--dictionarydir=/Library/Dictionaries", "--fontdir=/Library/Fonts", "--input_methoddir=/Library/Input Methods", "--internet_plugindir=/Library/Internet Plug-Ins", "--audio_unit_plugindir=/Library/Audio/Plug-Ins/Components", "--vst_plugindir=/Library/Audio/Plug-Ins/VST", "--vst3_plugindir=/Library/Audio/Plug-Ins/VST3"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.HGAHaf3UyL/org.xquartz:0
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_UPDATE_REPORT_ALL_FORMULAE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

### What were you trying to do (and why)?

I was running `brew update` to update my package lists. 
NOTE: I have the environment variable `HOMEBREW_UPDATE_REPORT_ALL_FORMULAE` set to 1. 

### What happened (include all command output)?

```
==> Updated Homebrew from 72f10e52c to 10845a112.
Updated 5 taps (homebrew/cask-versions, homebrew/command-not-found, homebrew/formula-analytics, homebrew/cask-fonts and homebrew/cask-drivers).
==> Modified Casks
mullvadvpn-beta
```

When I run `brew outdated` I get the following: 
```
gh (2.22.0) < 2.22.1
mesa (22.3.3) < 22.3.4
openjdk (19.0.1) < 19.0.2
```
which weren't showing as outdated last time I ran `brew update` (about 24 hours before) so it is definitely seeing Formula updates for those Formulae. 

### What did you expect to happen?

I expected it to output all modified/changed formulae and casks from all my taps as well as recognize that it updated other taps (like homebrew-core and homebrew-cask). 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Run `brew update` on a system whose package lists aren't already up to date.
```

**Comment by apainintheneck** [comment]
This seems to be related to `HOMEBREW_INSTALL_FROM_API` as well. Essentially, when that is set the update report skips the `homebrew-core` and `homebrew-cask` taps in the update report.

https://github.com/Homebrew/brew/blob/10845a1122b916dc91d04f00a4d8b7b888d52654/Library/Homebrew/cmd/update-report.rb#L158

#### Example
```
# Set core tap back five commits
/u/l/H/L/T/H/Homebrew-core (master|✔) $ git reset --hard HEAD~5
HEAD is now at 13054ef5013 osm2pgsql 1.8.0

# Without HOMEBREW_INSTALL_FROM_API
/u/l/H/L/T/H/Homebrew-core (master|✔) $ HOMEBREW_UPDATE_REPORT_ALL_FORMULAE=1 HOMEBREW_NO_INSTALL_FROM_API=1 brew update
Updated 1 tap (homebrew/core).
==> Modified Formulae
jruby                                                  osm2pgsql                                              structurizr-cli

# Set core tap back five commits
/u/l/H/L/T/H/Homebrew-core (master|✔) $ git reset --hard HEAD~5
HEAD is now at 13054ef5013 osm2pgsql 1.8.0

# With HOMEBREW_INSTALL_FROM_API
/u/l/H/L/T/H/Homebrew-core (master|✔) $ HOMEBREW_UPDATE_REPORT_ALL_FORMULAE=1 brew update
Already up-to-date.
```

To get the old behavior back you just have to set `HOMEBREW_NO_INSTALL_FROM_API`.

**Comment by apainintheneck** [comment]
@Rylan12 Do you think there is any useful info we can display for the core and cask taps when `HOMEBREW_INSTALL_FROM_API` is set? Just curious.

**Comment by JLP04** [comment]
So setting `HOMEBREW_NO_INSTALL_FROM_API` will fix this?

**Comment by JLP04** [comment]
After setting `HOMEBREW_NO_INSTALL_FROM_API` to 1, I ran `brew upgrade` (not `brew update`) but it triggered an auto-update which resulted in this: 

```
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
xcdiff
==> New Casks
copilot-for-xcode          lotus                      spybuster
==> Modified Formulae
Modified 153 formulae.
==> Modified Casks
Modified 116 casks.
```

so it looks like that is the answer for now.

**Comment by mitchblank** [comment]
I think I just got bit by this as well -- just noticed that `brew update` decided to downgrade one of my casks:
```
==> Upgrading 1 outdated package:
kitty 0.27.0 -> 0.26.5
```
This made me curious why a previous update had apparently been reverted but I couldn't find any evidence in git.  I guess now I need to set `HOMEBREW_NO_INSTALL_FROM_API=1` if I want the current versions of casks?

FWIW, I have done development on formulae but not casks so my formulae setup is probably more git-y while my casks were in the default state.  So it seems that after recent changes it was no longer doing `git pull`'ing the homebrew-cask directly (latest entry in `git log` was 9 days ago) but I've been manually doing `git pull` on the homebrew-core directory.

I'm not sure why it updated to 0.27.0 and then later downgraded though -- I guess the API *had* returned the correct version earlier and updated but then later something changed and it fell back to using the 9-day-old git checkout instead?

Anyway, after doing a `HOMEBREW_NO_INSTALL_FROM_API=1 brew update` the git checkout of homebrew-cask was refreshed and it re-upgraded that package.  I guess that's the solution for now.

**Comment by JLP04** [comment]
> I think I just got bit by this as well -- just noticed that `brew update` decided to downgrade one of my casks

This should probably be put in a new ticket as it looks to be a different issue with the API.

**Comment by mitchblank** [comment]
OK, I'l

> > I think I just got bit by this as well -- just noticed that `brew update` decided to downgrade one of my casks
> 
> This should probably be put in a new ticket as it looks to be a different issue with the API.

OK I'll file it as new.  Just didn't want to cause unnecessary duplication and this looked possibly related.

**Comment by JLP04** [comment]
> > > I think I just got bit by this as well -- just noticed that `brew update` decided to downgrade one of my casks
> 
> > 
> 
> > This should probably be put in a new ticket as it looks to be a different issue with the API.
> 
> 
> 
> OK I'll file it as new.  Just didn't want to cause unnecessary duplication and this looked possibly related.

I was just thinking since it's already been closed as something that won't be implemented.
