### ISSUE TITLE
Please improve messaging when calling "brew desc -s XXX"

### ISSUE THREAD

**Issue by MikeRich88** [Homebrew/brew#14461]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Currently if you call "brew desc -s XXX" it will return like this. It makes it seem as if there are no results. I will use the term "radio" in my examples.

```
MacPro:~ mike$ brew desc -s radio
Warning: Calling brew desc is deprecated! Use brew desc --eval-all or HOMEBREW_EVAL_ALL instead.
==> Formulae

==> Casks
```

This is confusing because this used to deliver results, but with the exact same deprecation message. But now it seems as if there are no results for "radio", when there are certainly are.

If "brew desc -s XXX" feature is fully removed, you should not return as if there might be results (i.e, having the Formulae and Casks headers).

Instead, you should return a message such as `"Warning: Calling brew desc is removed! Use brew desc --eval-all or HOMEBREW_EVAL_ALL instead".` Fully omit the other lines.

Also, if the user is using the -s flag, then the suggestion given is not very helpful. A naive user, having run "brew desc -s radio", and given your suggestion, may immediately then try this:

```
MacPro:~ mike$ brew desc --eval-all radio
Error: No available formula with the name "radio". Did you mean gradio or rtaudio?
```

Instead, brew should know that the -s flag was used, and suggest that the user try "brew desc --eval-all --search".

In that case, then the user might try the following invocation, and would experience success:

```
MacPro:~ mike$ brew desc --eval-all --search radio
==> Formulae
airspy: Driver and tools for a software-defined radio
airspyhf: Driver and tools for a software-defined radio
get_iplayer: Utility for downloading TV and radio programmes from BBC iPlayer
gnuradio: SDK for signal processing blocks to implement software radios
gradio: GTK3 app for finding and listening to internet radio stations
hackrf: Low cost software radio platform
hamlib: Ham radio control libraries
inspectrum: Offline radio signal analyser
libbladerf: USB 3.0 Superspeed Software Defined Radio Source
liquid-dsp: Digital signal processing library for software-defined radios
luaradio: Lightweight, embeddable flow graph signal processing framework for SDR
rtl_433: Program to decode radio transmissions from devices
urh: Universal Radio Hacker

==> Casks
chirp: (CHIRP) Tool for programming amateur radio
cubicsdr: (CubicSDR) Cross-platform software-defined radio application
fldigi: (fldigi) Ham radio digital modem application
flrig: (flrig) Ham radio rig control
gqrx: (Gqrx) Software-defined radio receiver powered by GNU Radio and Qt
gridtracker: (GridTracker) Warehouse of amateur radio information presented in an easy to use interface
jt-bridge: (JT-Bridge) Acts as a bridge between WSJT-X and ham radio logging application
macloggerdx: (MacLoggerDX) Ham radio logging and rig control software
pandora: (Pandora) Desktop client for the Pandora web radio service
radio-silence: (Radio Silence) Network monitor and firewall
remotehamradio: (RemoteHamRadio) Desktop console app for RemoteHamRadio service
tunein: (TuneIn) Free Internet Radio
```

### What is the motivation for the feature?

To make brew as easy to use as possible for all users regardless of skill level.

### How will the feature be relevant to at least 90% of Homebrew users?

It is certainly possible that 90% of former users of "brew desc -s" would appreciate these clarifications.

### What alternatives to the feature have been considered?

Bringing back "brew desc -s" as it was, but this seems unlikely.

**Comment by apainintheneck** [comment]
It sounds like there are two things here.

1. Some parts of the `brew desc` command are deprecated and don't return the expected results without the `--eval-all` flag. This is unfortunately in line with the expected behavior and will be completely disabled with a warning at the next major or minor release (https://github.com/Homebrew/brew/pull/14382). Note that this was originally deprecated for security reasons (more discussion https://github.com/Homebrew/brew/issues/14010).
2. The messaging should be clearer with deprecation/disable warnings and include flags and options. This is a bit bigger of an ask but something I think we should keep in mind. In this case, the `brew desc` doesn't have too many options so it sounds plausible but for other commands having variable deprecation/disable warnings for each set of options sounds a lot more difficult. We wouldn't want to recommend an alternative that is also invalid.

**Comment by MikeRich88** [comment]
> 1. Some parts of the `brew desc` command are deprecated and don't return the expected results without the `--eval-all` flag. This is unfortunately in line with the expected behavior and will be completely disabled with a warning at the next major or minor release

This will definitely help the situation. Because deprecation does not mean "removal" (it means something more like "pending removal"), the behavior right now makes it seem as if there are no search results for "brew desc -s XXX", no matter what one actually puts for "XXX".

I really thought for a few minutes that there were no results for "brew desc -s radio", but I distinctly remembered finding the desired package (gqrx) this way a couple of years ago. (I can never remember gqrx).

As an aside, I really do think there is a lot of value in being able to search the package descriptions easily. Certainly a safer way could be established to do so; even a web service would be acceptable. Did `brew desc -s XXX` really run (Ruby?) code from every repository while conducting the search?

**Comment by MikeRich88** [comment]
Crappy quick example of how a web service might return results:

```
{
   "results" : {
      "formulae" : {
         "blahradioblah" : "This results appears because radio is in the name of the formula.",
         "gqrx" : "Description of a radio related thing."
      },
      "casks" : {
         "radioiswaves" : "Wow waves are neat.",
         "somecask" : "This cask does radio stuff. Wow!"
      }
   }
}
```

**Comment by MikeMcQuaid** [comment]
We will address this in the next release when they are disabled. Sorry for the pain!
