### ISSUE TITLE
Homebrew can end up in a situation where it doesn't update a tap anymore

### ISSUE THREAD

**Issue by Porkepix** [Homebrew/brew#14476]
### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 3.6.20-167-g7a5f614
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7a5f6143d3e7447a64255c548d2e51138c83acd3
Last commit: 30 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 25e0de0968e7e3030405f96068380cff94dc292f
Core tap last commit: 8 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit skylake
Clang: N/A
Git: 2.39.1 => /bin/git
Curl: 7.87.0 => /bin/curl
Kernel: Linux 6.1.7-arch1-1 x86_64 GNU/Linux
OS: Arch Linux
Host glibc: 2.36
/usr/bin/gcc: 12.2.1
/usr/bin/ruby: 3.0.5
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

Just wanted to `brew update`

### What happened (include all command output)?

`brew update` says:
```
$ brew update
Already up-to-date.
```

But while `brew` itself update, it's not the case of the `core` tap.

### What did you expect to happen?

`homebrew-core` tap should update.

### Step-by-step reproduction instructions (by running `brew` commands)
To reproduce it's just a `brew update`; unfortunately I have no idea what led to this situation after months without problem. `homebrew-core` tap got `git reset --hard`, `brew update-reset` was used, but it doesn't change a thing: `brew update` fails to update the tap while just going into the repo and doing `git pull` does the job. This went this way for days.

```shell
$ brew update -v
Checking if we need to fetch /home/linuxbrew/.linuxbrew/Homebrew...
Checking if we need to fetch /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core...
Already up-to-date.
```

```
$ git status
On branch master
Your branch is behind 'origin/master' by 52 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```

**Comment by MikeMcQuaid** [comment]
You need to `export HOMEBREW_NOINSTALL_FROM_API=1` if you wish taps to be updated, otherwise it will use the API instead. Expect better documentation for this in the new release.

**Comment by Porkepix** [comment]
@MikeMcQuaid I don't get it, what does change this variable (I don't get what do you mean by "it will use the API instead")? From what I can see, the release from more than two weeks ago mention it, but `brew updated` started to fail updating a little late, like just a couple of days ago.

Also, note that the "developer mode" is in use here as I bump formulas quite often, if it may make any difference here.

It doesn't seems to change a thing anyway:
```
$ HOMEBREW_NOINSTALL_FROM_API=1 brew update
Already up-to-date.
```

Tap not updated right after.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@MikeMcQuaid forgot an underscore; per '`man brew`,' its '`HOMEBREW_NO_INSTALL_FROM_API`'&thinsp;—&thinsp;note the underscore between 'NO' and 'INSTALL.'

**Comment by Porkepix** [comment]
> @MikeMcQuaid forgot an underscore; per '`man brew`,' its '`HOMEBREW_NO_INSTALL_FROM_API`' — note the underscore between 'NO' and 'INSTALL.'

So, it indeed works if I specify this before the update. But I don't understand what's the story behind this variable and this API thing, nor why suddenly `brew update` would stop working and now require an environment variable to be able to work?

**Comment by gromgit** [comment]
> So, it indeed works if I specify this before the update. But I don't understand what's the story behind this variable and this API thing, nor why suddenly `brew update` would stop working and now require an environment variable to be able to work?

https://github.com/orgs/Homebrew/discussions/4135#discussioncomment-4846718
