### ISSUE TITLE
brew install mysql 

### ISSUE THREAD

**Issue by ngavrish** [Homebrew/brew#14475]
### `brew doctor` output

```shell
Catalina 10.15.7

brew --version
Homebrew 3.6.20-167-g7a5f614
Homebrew/homebrew-core (git revision 8577bfee0f; last commit 2023-02-01)
Homebrew/homebrew-cask (git revision b28a0f4ff2; last commit 2023-02-01)

Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/802619/Library/Caches/Homebrew/downloads/6bbcd09a011bd2cd14da6565b34a8dc3cf836e93d26c3e72985a507ba1e2a16d--3.10-sysconfig.diff
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-167-g7a5f614
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 7a5f6143d3e7447a64255c548d2e51138c83acd3
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8577bfee0fa4cc326846ee97fd8ce5f61f6d0c57
Core tap last commit: 14 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ILNdGFbMGS/org.macosforge.xquartz:0
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_TEMP: /tmp
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```

### What were you trying to do (and why)?

brew install mysql 

### What happened (include all command output)?

Warning: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

==> Fetching dependencies for mysql: python@3.10, protobuf and zlib
==> Fetching python@3.10
==> Downloading https://www.python.org/ftp/python/3.10.9/Python-3.10.9.tgz
Already downloaded: /Users/802619/Library/Caches/Homebrew/downloads/6d5a02c73aff7322336882f7ffa0dfa2791a3969e43d7253802431f4f4a11135--Python-3.10.9.tgz
==> Fetching protobuf
==> Downloading https://github.com/protocolbuffers/protobuf/releases/download/v2
Already downloaded: /Users/802619/Library/Caches/Homebrew/downloads/322b46ea2d2cc0fb0f59ad62fa5f4595321648baa258b35ea7add6a7db1e8e73--protobuf-all-21.12.tar.gz
==> Fetching zlib
==> Downloading https://ghcr.io/v2/homebrew/core/zlib/manifests/1.2.13
Already downloaded: /Users/802619/Library/Caches/Homebrew/downloads/fdccac006bc82ad87194cffa03a899a1a5225cffe5b052b27a5fe2dc8540ee03--zlib-1.2.13.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/zlib/blobs/sha256:4da7de2b14c12
Already downloaded: /Users/802619/Library/Caches/Homebrew/downloads/9dd195e2b9a685706c8da479d37bf69b201473cffd80763881c69c19f5847bed--zlib--1.2.13.catalina.bottle.tar.gz
==> Fetching mysql
==> Downloading https://cdn.mysql.com/Downloads/MySQL-8.0/mysql-boost-8.0.32.tar
Already downloaded: /Users/802619/Library/Caches/Homebrew/downloads/58e7b50cf9e16f8487f7076d16a9cfc85bb5ecbcd1c5a943877b60b21f8bc587--mysql-boost-8.0.32.tar.gz
==> Installing dependencies for mysql: python@3.10, protobuf and zlib
==> Installing mysql dependency: python@3.10
==> Patching
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/802619/Library/Caches/Homebrew/downloads/6bbcd09a011bd2cd14da6565b34a8dc3cf836e93d26c3e72985a507ba1e2a16d--3.10-sysconfig.diff

### What did you expect to happen?

success

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install mysql
```

**Comment by gromgit** [comment]
`export HOMEBREW_NO_INSTALL_FROM_API=1` and try again.

**Comment by marnixhoh** [comment]
I run into exactly the same problem. (Output is exactly the same)
