### ISSUE TITLE
cask "pkg" function do not place apps to user-defined directory

### ISSUE THREAD

**Issue by cedricloneux** [Homebrew/brew#14487]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  mcrypt
  termius
  xcprojectlint

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  yt-dlp
  cutter
  handbrake
  python@3.8
  gnupg
  protobuf
  python@3.9
  silicon

Warning: Xcode is installed to a directory with a space in the name.
This will cause some formulae to fail to build.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 344d32bf7f40183359592ef81ca6486e0587981b
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cd203359e9b673d1d6757bd89e5f693f523edf5e
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--appdir=/Applications/homebrew-casks"]
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.1 => /Users/cedricloneux/Downloads/old app folder/Applications/Xcode-14.1.0-Release.Candidate.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

Today, I decided to sort my Applications directory. 
I created a directory to place apps downloaded manually from internet and an other for those from brew.
For this I used a brew env variable. _HOMEBREW_CASK_OPTS="--appdir=myPath"_

### What happened (include all command output)?

First issue: 
I had to reinstall all the apps in order to move all of them into the new directory.
It would be useful to have a command that do it. 
Another idea could be to move the already installed apps to the correct location in the next update.  

Second issue (and the most important one):
Most of the apps were installed correctly in the custom directory but some didn’t. I investigated and most of the time this issue happen when installer (the cask file) install via `pkg` function rather than `app` function
The other failing cases (less common) use `make install` or `cargo`, `go` etc.. which also not install the app to the correct location.

So at least `pkg` function should be fixed. But it would be also good to add to the guidelines to install the apps to the correct user-defined directory and not arbitrarily.

### What did you expect to happen?

All the apps should have been installed to the directory passed with --app-dir

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
To do so I added these lines into my _~/.zprofile_


# custom directory for casks (guis from homebrew)
CASKS_CUSTOM_DIR='/Applications/homebrew-casks'
mkdir $CASKS_CUSTOM_DIR 2> /dev/null
export HOMEBREW_CASK_OPTS="--appdir=$CASKS_CUSTOM_DIR"
```

then brew install a cask using the "pkg" function instead of "app".
Some of examples: fuse, krisp, nordvpn, santa, adobe-acrobat-reader etc...

Some others use custom installers: make, cargo, go
some example: oversight, xcodes (cask)

None of these will be installed to the correct user-defined location
```

**Comment by gromgit** [comment]
> First issue:  I had to reinstall all the apps in order to move all of them into the new directory. It would be useful to have a command that do it.

UNTESTED: `brew reinstall --cask $(brew ls --cask)`

> Second issue (and the most important one): Most of the apps were installed correctly in the custom directory but some didn’t. I investigated and most of the time this issue happen when installer (the cask file) install via `pkg` function rather than `app` function

`app` installs basically copy the `MyProgram.app` _directory_ to your system's `Applications` folder by default, and can therefore be redirected with `--appdir`.

`pkg` installs use the macOS installer to install the `MyProgram.pkg` _package_, which has hardcoded expectations about which file goes where, and therefore can't be relocated under any arbitrary directory prefix. About the only thing that can be done with packages is to specify the target volume under which the package will be installed:
![image](https://user-images.githubusercontent.com/215702/216517240-00c3beca-a1a2-4a45-af1a-d8f0cb2d1957.png)


> The other failing cases (less common) use `make install` or `cargo`, `go` etc.. which also not install the app to the correct location.

Sounds like you're talking about _formulae_ here, not casks. `--appdir` has zero relevance to formulae, which are always installed under `$HOMEBREW_PREFIX`.

> So at least `pkg` function should be fixed. 

That doesn't seem possible.

**Comment by carlocab** [comment]
As @gromgit points out, this is not possible. Sorry!

**Comment by cedricloneux** [comment]
couldn't `pkg` function be modified to target the same custom directory ?

this:
`HOMEBREW_CASK_OPTS="--appdir=$CASKS_CUSTOM_DIR"`
should apply to both

Even if the function call the macOS installer with hardcoded diretory. `pkg` fucntion could just do that and then move it if needed

**Comment by carlocab** [comment]
No, it is not possible. The `pkg` method just runs a `pkg` installer, and these can install anything anywhere in the file system. There is no way to reliably keep track of what has been installed and then move them to the right place without the risk of breaking them.

**Comment by cedricloneux** [comment]
When moving manualy an app and updating I usually got error because homebrew couldn't find previous version. So brew knew where it was.
Do you mean that this doesn't apply when using pkg ?

As almost all apps are placed to _/Applications/_ directory, Homebrew could at least try to look there once install is finished and move to --appdir

It would also be good to recommand to dev using something else then pkg
