### ISSUE TITLE
Consider add `HOMEBREW_API_DOMAIN` (or reuse `HOMEBREW_{ARTIFCAT,BOTTLE}_DOMAIN`) for Homebrew API mirroring

### ISSUE THREAD

**Issue by XuehaiPan** [Homebrew/brew#14493]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`HOMEBREW_INSTALL_FROM_API` will be the default in `brew` 4.0. Users no longer need to tap the homebrew/core repo from `HOMEBREW_CORE_GIT_REMOTE`. It would significantly reduce the installation time.

- #14412
- Homebrew/install#732
- Homebrew/install#523

Discussed in https://github.com/Homebrew/install/issues/523#issuecomment-787017870. Currently, the API domain <https://formulae.brew.sh> is hard coded.

https://github.com/Homebrew/brew/blob/051895850cd0c8de36bfa5b22f420883be03ef45/Library/Homebrew/api.rb#L21

https://github.com/Homebrew/brew/blob/051895850cd0c8de36bfa5b22f420883be03ef45/Library/Homebrew/cmd/update.sh#L781-L788

I think would be great if we support API mirroring rather than downloading the JSON from the API website (which is hosted by GitHub).

The change would be simple to change the hardcoded URL to a variable. (Fallback handling may be needed)

### What is the motivation for the feature?

Allow Homebrew users to use geolocalized mirrors for Homebrew API. This has the same purpose as `HOMEBREW_CORE_GIT_REMOTE` / `HOMEBREW_ARTICAT_DOMAIN` / `HOMEBREW_BOTTLE_DOMAIN`.

### How will the feature be relevant to at least 90% of Homebrew users?

This feature affects Homebrew users who want to use geolocalized mirrors. This has the same purpose as `HOMEBREW_CORE_GIT_REMOTE` / `HOMEBREW_ARTICAT_DOMAIN` / `HOMEBREW_BOTTLE_DOMAIN`.

### What alternatives to the feature have been considered?

Keep the hardcoded <https://formulae.brew.sh> URL and ask users to clone the homebrew/core tap from `HOMEBREW_CORE_GIT_REMOTE`.

**Comment by MikeMcQuaid** [comment]
@XuehaiPan Good idea. Would accept a PR for this.
