### ISSUE TITLE
The DockerHub `Homebrew/brew` description is not updating from the README

### ISSUE THREAD

**Issue by issyl0** [Homebrew/brew#14498]
### `brew doctor` output

```shell
issyl0 at pictor in /opt/homebrew on master
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ffmpeg
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
issyl0 at pictor in /opt/homebrew on master
❯ brew config
HOMEBREW_VERSION: 3.6.20-214-g791022d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 791022dc2195f5caf819a91552014ec9546b20b8
Last commit: 9 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fc36a19edf46b5ebdd6a16c53746bdf6691590bd
Core tap last commit: 78 minutes ago
Core tap branch: master
Core tap JSON: 04 Feb 10:21
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.UQNInpot0q/org.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.38.1 => /opt/homebrew/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.1 => /Users/issyl0/Downloads/Xcode.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

The "overview" description on https://hub.docker.com/r/homebrew/brew is _very_ out of date. 😬 Hat tip to @EricFromCanada who pointed this out last night.

### What happened (include all command output)?

@EricFromCanada noticed that the description on DockerHub was out of date.

### What did you expect to happen?

That the `Homebrew/brew` description on DockerHub should update on every release with the latest README.

Relevant to the debugging here are https://github.com/Homebrew/brew/actions/workflows/docker.yml, and maybe  https://github.com/peter-evans/dockerhub-description.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Look at DockerHub.
```

**Comment by MikeMcQuaid** [comment]
I've manually edited this to a version that doesn't matter if it's out of date.

**Comment by issyl0** [comment]
Thanks! For future reference, how did you "manually edit this"? I logged in with the DockerHub credentials in 1Password and couldn't find an edit button for the "overview" description?

**Comment by MikeMcQuaid** [comment]
@issyl0 I had to click around for a while, can't remember the exact URL, sorry!
