### ISSUE TITLE
Disabling sudo with audit may cause trouble for Travis users

### ISSUE THREAD

**Issue by alexpearce** [Homebrew/brew#1450]
When you run `brew audit --strict <formula>` on Travis CI with macOS, you get a crash. For example [here](https://travis-ci.org/neomutt/homebrew-neomutt/jobs/173368629#L1445) as seen by the [Neomutt project](https://github.com/neomutt/homebrew-neomutt) and [here](https://travis-ci.org/neovim/homebrew-neovim/jobs/173626261#L4626) by the [Neovim project](https://github.com/neovim/homebrew-neovim). (Related issues I've found are neomutt/homebrew-neomutt#17, neovim/homebrew-neovim#185, and supermarin/xcpretty#243.)

The problem doesn't happen when you run `sudo brew audit --strict <formula>`. I think this is because [Homebrew always uses the system Ruby](https://github.com/Homebrew/legacy-homebrew/issues/44220#issuecomment-142015371), but on Travis you need [superuser privileges to install gems on the system Ruby](https://docs.travis-ci.com/user/osx-ci-environment/#Ruby-versions-implementations).

However, when you [run `sudo brew <whatever>`](https://travis-ci.org/neomutt/homebrew-neomutt/jobs/173694075#L1468), you get a warning:

> Error: Running Homebrew as root is extremely dangerous. As Homebrew does not
drop privileges on installation you are giving all build scripts full access
to your system. As a result of the macOS sandbox not handling the root user
correctly HOMEBREW_NO_SANDBOX has been set so the sandbox will not be used. If
we have not merged a pull request to add privilege dropping by November 1st
2016 running Homebrew as root will be disabled. No Homebrew maintainers plan
to work on this functionality.

If this does come to pass, and `sudo brew` is completely disabled, then as far as I can tell using `brew audit --strict` won't work on macOS instances on Travis. If _this_ is true, then there are two possible solutions I can think of (there might be more):

1. Allow `sudo brew` only for the `audit` subcommand;
2. Allow the `rubocop` gem to be installed using whatever Ruby is current in the user's shell.

I don't know the viability of either of these, as I'm not very familiar with the internals of `brew`, so I'd appreciated the advice of the maintainers.

**Comment by MikeMcQuaid** [comment]
You need to set `rvm: system` in your `.travis.yml`.

**Comment by alexpearce** [comment]
Mind-blowing stuff. [That's done it](https://travis-ci.org/neomutt/homebrew-neomutt/builds/173698166). Thanks!

**Comment by MikeMcQuaid** [comment]
this is the recommended 
Travis configuration: https://github.com/Homebrew/brew/blob/ce2b11fd656e85a2cd73f45b4ac25fd34b1599cf/Library/Homebrew/dev-cmd/tap-new.rb#L47-L76
