### ISSUE TITLE
brew upgrade error

### ISSUE THREAD

**Issue by wjlmelody** [Homebrew/brew#14516]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

brew upgrade error

### Command that failed

brew upgrade

### Output of command with `--verbose --debug`

```shell
--remote-time --output /Users/jeremywang/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-261-gb3a71ba\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 10 --location --remote-time --output /Users/jeremywang/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-261-gb3a71ba\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 10 --location --remote-time --output /Users/jeremywang/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-261-gb3a71ba\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 10 --location --remote-time --output /Users/jeremywang/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
Error: Cannot download non-corrupt https://formulae.brew.sh/api/formula.json!
Error: Kernel.exit
/opt/homebrew/Library/Homebrew/utils.rb:165:in `exit'
/opt/homebrew/Library/Homebrew/utils.rb:165:in `odie'
/opt/homebrew/Library/Homebrew/api.rb:77:in `rescue in fetch_json_api_file'
/opt/homebrew/Library/Homebrew/api.rb:51:in `fetch_json_api_file'
/opt/homebrew/Library/Homebrew/api/formula.rb:21:in `all_formulae'
/opt/homebrew/Library/Homebrew/formulary.rb:667:in `loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:561:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:609:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:582:in `from_rack'
/opt/homebrew/Library/Homebrew/formula.rb:1870:in `block in installed'
/opt/homebrew/Library/Homebrew/formula.rb:1869:in `each'
/opt/homebrew/Library/Homebrew/formula.rb:1869:in `flat_map'
/opt/homebrew/Library/Homebrew/formula.rb:1869:in `installed'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:135:in `upgrade_outdated_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:116:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Warning: formula.json: update failed, falling back to cached version.
Warning: formula.json: update failed, falling back to cached version.
Warning: formula.json: update failed, falling back to cached version.
Warning: formula.json: update failed, falling back to cached version.
Error: Cannot download non-corrupt https://formulae.brew.sh/api/formula.json!
```

### Output of `brew tap`

```shell
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/command-not-found
homebrew/core
majd/repo
```

**Comment by carlocab** [comment]
What's the output of
```
brew config
brew doctor
curl -LI https://formulae.brew.sh/api/formula.json
```
?

**Comment by Kotodian** [comment]
I have the same error
---------------------------------------------
$ brew config
HOMEBREW_VERSION: 3.6.20-261-gb3a71ba
ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HEAD: b3a71ba7cdb7e005c26c86bcc627f0549dfe19d0
Last commit: 12 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 15cc58f490ef218e460352ccd00ebf79f35b2491
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
---------------------------------------------
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/opt/homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/opt/homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
Warning: formula.json: update failed, falling back to cached version.
---------------------------------------------
 $ curl -LI https://formulae.brew.sh/api/formula.json
HTTP/1.1 200 Connection established

HTTP/2 200
server: GitHub.com
content-type: application/json; charset=utf-8
x-origin-cache: HIT
last-modified: Mon, 06 Feb 2023 05:21:13 GMT
access-control-allow-origin: *
etag: "63e08e49-129b66d"
expires: Mon, 06 Feb 2023 05:34:18 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: EDB0:2952:110FC2:1233C7:63E08F02
accept-ranges: bytes
age: 1
date: Mon, 06 Feb 2023 05:24:19 GMT
via: 1.1 varnish
x-served-by: cache-tyo11942-TYO
x-cache: MISS
x-cache-hits: 0
x-timer: S1675661058.074362,VS0,VE973
vary: Accept-Encoding
x-fastly-request-id: cb9d0a76f8e4c0e4e27e70e40b4d6184b109f63c
content-length: 19510893

**Comment by carlocab** [comment]
@Kotodian, please try
```
rm -r "$(brew --cache)/api"
brew update
```
and see if it helps.

**Comment by Kotodian** [comment]
> @Kotodian, please try
> 
> ```
> rm -r "$(brew --cache)/api"
> brew update
> ```
> 
> and see if it helps.
 ~  $ rm -r "$(brew --cache)/api"
-
 ~  $ brew update
-
Already up-to-date.
-
$ brew install --verbose --debug helm
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-261-gb3a71ba\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --fail --max-time 10 --location --remote-time --output /Users/linqiankai/Library/Caches/Homebrew/api/formula.json --time-cond /Users/linqiankai/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-261-gb3a71ba\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --fail --max-time 10 --location --remote-time --output /Users/linqiankai/Library/Caches/Homebrew/api/formula.json --time-cond /Users/linqiankai/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: Illegal date format for -z, --time-cond (and not a file name).
Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.

**Comment by yaohwu** [comment]
> @Kotodian, please try
> 
> ```
> rm -r "$(brew --cache)/api"
> brew update
> ```
> 
> and see if it helps.

This issue same happened to me after upgrading macos to 13.2 and this tip helped.

**Comment by carlocab** [comment]
@Kotodian, try doing
```
export HOMEBREW_NO_INSTALL_FROM_API=1
```
and see if that helps.

**Comment by Kotodian** [comment]
> 

it helps. Thx.

**Comment by LuckyWindsck** [comment]
> @Kotodian, try doing
> 
> ```
> export HOMEBREW_NO_INSTALL_FROM_API=1
> ```
> 
> and see if that helps.

Same problem here. I followed each steps stated in this issue and finally it works. Thank you very much.

**Comment by KarlManong** [comment]
I have the same problem.

**Comment by wjlmelody** [comment]
> ```
> export HOMEBREW_NO_INSTALL_FROM_API=1
> ```
This seems helps.

**Comment by wjlmelody** [comment]
> I have the same problem.

> ```
> export HOMEBREW_NO_INSTALL_FROM_API=1
> ```
This seems helps.

**Comment by scientificworld** [comment]
> @Kotodian, try doing
> 
> ```
> export HOMEBREW_NO_INSTALL_FROM_API=1
> ```
> 
> and see if that helps.

It solves the problem. Thanks.

**Comment by carlocab** [comment]
`HOMEBREW_NO_INSTALL_FROM_API` is the default for now. There is no need to set it once you've done `brew update`.

**Comment by zhangyoufu** [comment]
Run into this issue today with latest Homebrew. (Already upgraded after GitHub API outage.) This issue is not fixed yet.

**Comment by zhangyoufu** [comment]
@gromgit 

```
% brew config
HOMEBREW_VERSION: 3.6.21-26-gb0a74e5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b0a74e532361fab983b596b31509c2e6fd3066c1
Last commit: 9 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4fbf693010429a62c6d6a807750262508000736a
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.MPTbVPDgLP/org.xquartz:0
HOMEBREW_EDITOR: subl -w
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A

% brew doctor --debug
==> Checking check_access_directories
==> Checking check_brew_git_origin
/usr/local/Homebrew/Library/Homebrew/shims/shared/git --version
==> Checking check_broken_sdks
==> Checking check_cask_environment_variables
==> Checking check_cask_install_location
==> Checking check_cask_load_path
==> Checking check_cask_quarantine_support
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Checking check_cask_software_versions
==> Checking check_cask_staging_location
==> Checking check_cask_taps
==> Checking check_cask_xattr
/usr/bin/xattr -h
==> Checking check_casktap_integrity
==> Checking check_clt_minimum_version
==> Checking check_clt_up_to_date
==> Checking check_coretap_integrity
==> Checking check_deleted_formula
==> Checking check_deprecated_caskroom_taps
==> Checking check_deprecated_disabled
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.21-26-gb0a74e5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --progress-bar --max-time 10 --location --remote-time --output /Users/zhangyoufu/Library/Caches/Homebrew/api/formula.json --time-cond /Users/zhangyoufu/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.21-26-gb0a74e5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --progress-bar --max-time 10 --location --remote-time --output /Users/zhangyoufu/Library/Caches/Homebrew/api/formula.json --time-cond /Users/zhangyoufu/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: Illegal date format for -z, --time-cond (and not a file name).
Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.21-26-gb0a74e5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --progress-bar --max-time 10 --location --remote-time --output /Users/zhangyoufu/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.21-26-gb0a74e5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --progress-bar --max-time 10 --location --remote-time --output /Users/zhangyoufu/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.21-26-gb0a74e5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --progress-bar --max-time 10 --location --remote-time --output /Users/zhangyoufu/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.21-26-gb0a74e5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --progress-bar --max-time 10 --location --remote-time --output /Users/zhangyoufu/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
Error: Cannot download non-corrupt https://formulae.brew.sh/api/formula.json!
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/utils.rb:165:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:165:in `odie'
/usr/local/Homebrew/Library/Homebrew/api.rb:77:in `rescue in fetch_json_api_file'
/usr/local/Homebrew/Library/Homebrew/api.rb:51:in `fetch_json_api_file'
/usr/local/Homebrew/Library/Homebrew/api/formula.rb:21:in `all_formulae'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:684:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:578:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:626:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:599:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1870:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1869:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1869:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1869:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:634:in `check_deprecated_disabled'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by HuskyNie** [comment]
> @Kotodian, please try
> 
> ```
> rm -r "$(brew --cache)/api"
> brew update
> ```
> 
> and see if it helps.

thx,its helped

**Comment by gromgit** [comment]
@carlocab has already posted two potential workarounds:

---
> @Kotodian, please try
> 
> ```
> rm -r "$(brew --cache)/api"
> brew update
> ```
> 
> and see if it helps.
---
> @Kotodian, try doing
> 
> ```
> export HOMEBREW_NO_INSTALL_FROM_API=1
> ```
> 
> and see if that helps.
---
Have you tried both of them?

**Comment by fracturedprism** [comment]
`rm -r "$(brew --cache)/api"
brew update` does nothing

`export HOMEBREW_NO_INSTALL_FROM_API=1` fixes the issue, on my computer at least

**Comment by Aspartame-s** [comment]
> export HOMEBREW_NO_INSTALL_FROM_API=1

nice

**Comment by Aspartame-s** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Bo98** [comment]
I've merged something that _might_ help here. Let me know what the output is without HOMEBREW_NO_INSTALL_FROM_API if you still have issues.

There is one known issue that if you have a slow connection then brew startup will also be slow in a non-obvious way. I'll look into improving the output for that and providing further settings that people can use to control network usage.

**Comment by rahji** [comment]
I couldn't install on a clean WSL2 install today without doing the `export HOMEBREW_NO_INSTALL_FROM_API=1` first. Errors below. I am coming back to homebrew after many failed attempts to install in years past. It's unfortunate that the one-line installer on the homepage seems to be broken.

```
HEAD is now at a222a5b Merge pull request #14689 from Homebrew/SMillerDev-patch-1


Error: Failed to download https://formulae.brew.sh/api/cask.json!
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:fc45ee6eddf4c7a17f4373dde7b1bc8a58255ea61e6847d3bf895225b28d072a

curl: (28) Connection timed out after 300225 milliseconds
==> Downloading https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.6.8_1/portable-ruby-2.6.8_1.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.6.8_1.x86_64_linux.bottle.tar.gz
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force --quiet
```

**Comment by rahji** [comment]
It would seem so, but the same curl command works without issue repeatedly in another terminal window, while it fails every time via the installer. It also magically worked after exporting the environment variable above. 

I have given up on installing, however. The purpose of my revisiting Homebrew is that it would be an easy way for would-be users of my single-binary programs to install - without having to understand that they need to place the binary in their path. I can figure out these Homebrew installation issues, but if the idea is to give end-users an easier path, adding the potential challenges they'll encounter installing Homebrew defeats the purpose. :(

**Comment by MikeMcQuaid** [comment]
> It would seem so, but the same curl command works without issue repeatedly in another terminal window, while it fails every time via the installer.

**Comment by MikeMcQuaid** [comment]
> It would seem so, but the same curl command works without issue repeatedly in another terminal window, while it fails every time via the installer.

May be a proxy setup issue, intermittent issue with your connection, GitHub downtime, etc.

Regardless: we can't (and don't) control any of this really.

**Comment by squatto** [comment]
While `export HOMEBREW_NO_INSTALL_FROM_API=1` _does_ temporarily fix the issue, it only seems to mask the real problem. Or at least that's what was happening to me. Here is what I found:

---

## The Error

`brew update` fails to download `formula.json` due to a `Permission denied` error:

```shell
$ brew update
Error: Failed to download https://formulae.brew.sh/api/formula.json!
==> Downloading https://formulae.brew.sh/api/formula.json
Warning: Failed to open the file
Warning: /Users/scott/Library/Caches/Homebrew/api/formula.json: Permission
Warning: denied
curl: (23) Failure writing output to destination

Warning: formula.json: update failed, falling back to cached version.
Error: Permission denied @ apply2files - /Users/scott/Library/Caches/Homebrew/api/formula.json
```

---

## The Cause

Three of the files in `~/Library/Caches/Homebrew/api/` (including `formula.json`, specifically) somehow became owned by `root`:

```shell
$ ls -lah ~/Library/Caches/Homebrew/api/
Permissions Size User  Date Modified Name
.rw-r--r--@ 4.5M scott 22 Feb 21:06  cask.json
.rw-r--r--@  20M root  21 Feb 10:31  formula.json
.rw-r--r--@ 5.3k root  21 Feb 10:31  formula_aliases.txt
.rw-r--r--@  57k root  21 Feb 10:31  formula_names.txt
```

---

## The Fix

Change the ownership of the files back to your user:

```shell
sudo chown -R $(whoami) ~/Library/Caches/Homebrew/api/
```

Verify ownership is fixed:

```shell
$ ls -lah ~/Library/Caches/Homebrew/api/
Permissions Size User  Date Modified Name
.rw-r--r--@ 4.5M scott 22 Feb 21:06  cask.json
.rw-r--r--@  20M scott 21 Feb 10:31  formula.json
.rw-r--r--@ 5.3k scott 21 Feb 10:31  formula_aliases.txt
.rw-r--r--@  57k scott 21 Feb 10:31  formula_names.txt
```

And now `brew update` should work great:

```shell
$ brew update
Updated 2 taps (homebrew/core and homebrew/cask).
...
```

**Comment by gromgit** [comment]
@squatto Did you run `sudo brew services...` at some point? That's the only thing I can think of that would cause an API JSON download as root.

**Comment by Bo98** [comment]
> Did you run `sudo brew services...` at some point?

That's a fair shout actually. Will look into that.

**Comment by squatto** [comment]
> @squatto Did you run `sudo brew services...` at some point? That's the only thing I can think of that would cause an API JSON download as root.

It's entirely possible that I did at some point. That's a good thought. I've run that in the past though, and it never caused this issue.

**Comment by Aspartame-s** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jameshalsall** [comment]
For me, it complains about being unable to set the file time on the file:

```
brew upgrade serverless
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
Warning: Failed to set filetime 1679396178 on
Warning: '/Users/jameshalsall/Library/Caches/Homebrew/api/formula.jws.json':
Warning: No such file or directory
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
Warning: Failed to set filetime 1679396178 on
Warning: '/Users/jameshalsall/Library/Caches/Homebrew/api/formula.jws.json':
Warning: No such file or directory
```

`brew doctor` also produces the same error as above 🤔
