### ISSUE TITLE
Error: undefined method `relative_path_from' for nil:NilClass bump-cask-pr

### ISSUE THREAD

**Issue by grzegorzkrukowski** [Homebrew/brew#14519]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-264-g8edf681
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8edf6811753cfa7298860a4427e887354551f07b
Last commit: 71 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 15cc58f490ef218e460352ccd00ebf79f35b2491
Core tap last commit: 9 hours ago
Core tap branch: master
Core tap JSON: 06 Feb 10:20 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode-14.2.0.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: 14.2 => /Applications/Xcode-14.2.0.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

I am trying to upgrade the cask for our application with:
`brew bump-cask-pr --version 1.47.3 raycast`

### What happened (include all command output)?

Error: undefined method `relative_path_from' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:203:in `check_pull_requests'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:94:in `bump_cask_pr'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'

### What did you expect to happen?

I expected PR to be created with the new version of our cask

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew bump-cask-pr --version 1.47.3 raycast`

Running: `brew update-reset && brew update` before doesn't help.
```

**Comment by gromgit** [comment]
`export HOMEBREW_NO_INSTALL_FROM_API=1` and try bumping again.

**Comment by grzegorzkrukowski** [comment]
@gromgit with this ENV it worked - is it required for some reason from now on, or is it a workaround?

**Comment by gromgit** [comment]
It's a workaround for now, but Homebrew obviously shouldn't crash like that.

cc @Homebrew/brew
