### ISSUE TITLE
allow cron syntax for cron in service

### ISSUE THREAD

**Issue by stsmdt** [Homebrew/brew#14521]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Currently it's only possible to set one integer per minute/hour/day/month in cron in a service block. It should be allowed to use multiple values for each.

Currently not possible:

```ruby
  service do
    run_type :cron
    cron "* 1,4,7,10,13,16,19,22 * * *"
    working_dir etc/"#{f.name}"
  end
```

This configuration leads to the following error:

```
invalid value for Integer(): "1,4,7,10,13,16,19,22"
Error: Failed to install service files
Error: invalid value for Integer(): "1,4,7,10,13,16,19,22"
```

### What is the motivation for the feature?

To allow more granular specification of cron executions.

### How will the feature be relevant to at least 90% of Homebrew users?

To allow more granular specification of cron executions.

### What alternatives to the feature have been considered?

None

**Comment by issyl0** [comment]
The code for this appears to be in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/service.rb#L252-L308.

**Comment by issyl0** [comment]
Do you have an example formula that I can use to play around with this?

**Comment by MikeMcQuaid** [comment]
@SMillerDev any thoughts?

**Comment by carlocab** [comment]
If we're going this route, we may want to allow `cron` to accept a `Hash`:
```ruby
  service do
    run_type :cron
    cron hour: [1, 4, 7, 10, 13, 16, 19, 22]
    working_dir pkgetc
  end
```
with omitted keys equivalent to `*`, I guess.

**Comment by stsmdt** [comment]
@issyl0 unfortunately the formula, where I wanted to use that is one of a private tap. But I guess you could maybe play around with this with the [logrotate](https://github.com/Homebrew/homebrew-core/blob/31bc959595e6d9145aac156ad99c20a82639d6ee/Formula/logrotate.rb) formula for example.

**Comment by stsmdt** [comment]
@carlocab that suggestion looks good to me.

I dont know whether or not you are aware of that, but it seems like its currently not possible, to use `pkgetc` for `working_dir`.

Getting the following error, when using `working_dir pkgetc`:

```
undefined local variable or method `pkgetc' for #<Homebrew::Service:0x00000001236ac510>
Error: Failed to install service files
Error: undefined local variable or method `pkgetc' for #<Homebrew::Service:0x0000000140384af0>
```

**Comment by SMillerDev** [comment]
> If we're going this route, we may want to allow cron to accept a Hash:

I think that might be a nicer way to do this. The cron parser is very naive.

> I dont know whether or not you are aware of that, but it seems like its currently not possible, to use pkgetc for working_dir.

Seems like a good addition to the list of allowed paths
