### ISSUE TITLE
`brew bump*` commands should enable auto-merge

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#14538]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

This could be either conditional through e.g. `--automerge` or through an environment variable such as `HOMEBREW_BUMP_AUTO_MERGE`.

This requires write access to enable so will be limited to maintainers.

Once enabled this will merge when the branch protection requirements are met i.e. a ✅ and, on most repositories, passing CI.

This is possible when using [GitHub's Pull's API](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#update-a-pull-request) and setting the `auto_merge` attribute.

### What is the motivation for the feature?

Save maintainers time and clicks when reviewing PRs from other prolific maintainers.

### How will the feature be relevant to at least 90% of Homebrew users?

Maintainers with more time will do more things users like

### What alternatives to the feature have been considered?

Use an auto-merge action to enable this on all PRs: https://github.com/marketplace/actions/enable-pull-request-automerge

**Comment by MikeMcQuaid** [comment]
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request could do this

I note that we can't really do auto-merge properly on homebrew-core as-is, though, because we don't have required CI jobs.

**Comment by reitermarkus** [comment]
Auto-merge is now automatically enabled for maintainer version bumps in `homebrew/cask`, see https://github.com/Homebrew/homebrew-cask/pull/142896.

The same can be done when it is possible to have a required check in `homebrew/core`.

**Comment by MikeMcQuaid** [comment]
Thanks @reitermarkus.

@Homebrew/core what would you think about having required builds again that requires you to do a manual override (i.e. click the merge button more than once) to merge with the merge button? I would give you all `Maintain` access to make this possible.

**Comment by dawidd6** [comment]
But we mainly don't use the merge button in homebrew/core? We still need to pull the bottles somehow. Are we going to change our workflows? Sorry, I'm a bit lost with this thread :sweat_smile:.

**Comment by SMillerDev** [comment]
Same, I'm not sure how we could do this in core.

**Comment by ZhongRuoyu** [comment]
Also, there may occasionally be pre-releases that are not ready for widespread distribution. If we figure out how to handle bottles (not sure about this either, sorry), we should also figure out how to deal with pre-releases. Maybe, to be more conservative, only enable it for the ones that we can make sure are marked as latest.

**Comment by MikeMcQuaid** [comment]
@dawidd6 @SMillerDev @ZhongRuoyu Sorry, to clarify:
- I'm not proposing (yet/here) to change the homebrew/core workflow
- You are right that we have a different workflow that generally does not support auto-merge and that that's different enough to mean we'd need more changes than what @reitermarkus suggests
- I still think it's worth having "required builds" for everyone except @BrewTestBot with an admin override so that we can use native auto-merge sometimes (rather than never today because it ignores CI)
- I think we should make whatever the existing "auto-merge and pull bottles" workflow is for homebrew/core do the described behaviour here only for maintainers i.e. once you have a ✅ from another maintainer: bottles will be pulled/pushed automatically
- This may already be the existing functionality here, excuse me if so 😅

**Comment by MikeMcQuaid** [comment]
Somewhat unrelated to this thread:
- I want to adjust `brew test-bot` and the various workflows to push to PRs and then we can use native GitHub auto-merge behaviour and have a similar flow between homebrew/core and homebrew/cask

**Comment by reitermarkus** [comment]
> - this enables auto-merge when CI is 🟢 and another maintainer has done a ✅
> - another maintainer does a ✅

So you want to auto-merge when two maintainers have approved a PR?

**Comment by MikeMcQuaid** [comment]
@reitermarkus Every homebrew-core or homebrew-cask PR should have at least one person, other than the person who created the PR, giving a ✅ before it is merged. If it's auto-bumped by @BrewTestBot: only one maintainer needs to ✅ it. If it's bumped by a maintainer: another maintainer should ✅ it other than the one who created it.

Make sense?

**Comment by SMillerDev** [comment]
You can't ✅ your own PR though, so GitHub sets those rules for us already if we require one ✅ .

**Comment by reitermarkus** [comment]
Okay, so exactly like `homebrew/cask` works right now:

1. Maintainer submits a version bump.
2. Enable auto-merge. 
3. Another maintainer approves the PR.
4. GitHub auto-merges once CI passes.

For `homebrew/core` we would need the “pull and upload bottles” step somewhere between 3. and 4. though.

**Comment by dawidd6** [comment]
That's where merge queue comes in, I suppose. The PR goes into the merge queue where we run our workflow that uploads the bottle and pushes the bottle commit back to PR's branch or straight to master? I'm still a bit confused how this would exactly work.

**Comment by MikeMcQuaid** [comment]
> The PR goes into the merge queue where we run our workflow that uploads the bottle and pushes the bottle commit back to PR's branch or straight to master? I'm still a bit confused how this would exactly work.

I think if/when we land https://github.com/Homebrew/homebrew-core/pull/125556: we should be able to do this without the need for the merge queue.

**Comment by reitermarkus** [comment]
Pushing to the PR branch has two issues:

- Required approvals are dismissed.
- Not all contributors allow editing their PR.

**Comment by reitermarkus** [comment]
I'd argue disabling required approvals is more of a workaround than a true solution. Maybe we can have BrewTestBot re-approve the PR once the bottles are pushed.

**Comment by MikeMcQuaid** [comment]
> I'd argue disabling required approvals is more of a workaround than a true solution. Maybe we can have BrewTestBot re-approve the PR once the bottles are pushed.

Could do but I think I'd ideally like to get to a point where BrewTestBot has far reduced permissions for this stuff. Personally, I'm not terribly convinced that bots should be able to do things like this (long-term).

> This may be difficult for PRs from org forks. Just an FYI -- we can decide that we don't care, but I think it's important that this is made explicit.

@carlocab Yeh. We'll need a flow for figuring out how to handle this when it "doesn't work" e.g. a maintainer manually intervenes. Similarly, we may want to consider adding a check for this (somehow?) before PRs are ready to merge so we don't waste time on a branch that will need moved.

**Comment by MikeMcQuaid** [comment]
No longed needed by homebrew/core or homebrew/cask. See discussion in https://github.com/Homebrew/brew/pull/15784
