### ISSUE TITLE
audit: `--new-formula` fails for `uses_from_macos [...], since: :monterey`

### ISSUE THREAD

**Issue by pavelzw** [Homebrew/brew#14539]
### `brew doctor` output

```shell
CI for homebrew/homebrew-core
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
CI for homebrew/homebrew-core
```

### What were you trying to do (and why)?

As already stated in [Homebrew/Discussions#4130](https://github.com/orgs/Homebrew/discussions/4130), I am trying to build a formula for micromamba ([homebrew/homebrew-core#120924](https://github.com/Homebrew/homebrew-core/pull/120924)). For this, I need `curl >= 7.66.0` but macOS 11 ships an older version. To fix this issue, I added `uses_from_macos "curl", since: monterey` to the formula.

```rb
  [...]
  depends_on "yaml-cpp"
  depends_on "zstd"

  uses_from_macos "curl", since: :monterey # uses CURLINFO_RETRY_AFTER, available since curl 7.66.0
  uses_from_macos "krb5"
  uses_from_macos "libarchive", since: :monterey
  uses_from_macos "zlib"
  [...]
```

### What happened (include all command output)?

On macOS 11, the [following happens](https://github.com/Homebrew/homebrew-core/actions/runs/3990623199/jobs/6844571586#step:6:76):

```
==> brew audit micromamba --online --new-formula
==> FAILED
Full audit micromamba --online --new-formula output
  micromamba:
    * Dependency 'curl' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
    * Dependency 'libarchive' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
  Error: 2 problems in 1 formula detected
```

### What did you expect to happen?

`brew audit micromamba --online --new-formula` should pass since I already use `uses_from_macos` with a good reason for `since: monterey`.

The formula for [davix](https://github.com/Homebrew/homebrew-core/blob/d12bdfbac7ae07fade8a1af824a1adc086d9d9d8/Formula/davix.rb#L25) also uses `uses_from_macos "curl", since: monterey`. But this probably went through since the check only happens for new formulae.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Checkout `pavelzw/homebrew-core micromamba` on macOS 11
`brew audit micromamba --online --new-formula`
```

**Comment by MikeMcQuaid** [comment]
This would be nice to address but:

> `brew audit micromamba --online --new-formula` should pass

`--new-formula` is expected to fail in many circumstances in which we manually override it.

Ideally this would be a e.g. non-required CI check instead.

**Comment by pavelzw** [comment]
@MikeMcQuaid could you please take a look at [homebrew-core#122551](https://github.com/Homebrew/homebrew-core/pull/122551) and override the `--new-formula` fails?

(Sorry for creating a second PR for this; when updating micromamba to 1.3.0, I accidentally pushed outdated commits of homebrew-core which lead to the branch being behind master and the PR getting closed -.-)

**Comment by MikeMcQuaid** [comment]
> override the `--new-formula` fails?

Just comment in the PR and the relevant maintainer will take it into account.

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry!
