### ISSUE TITLE
i dont wut the problem is ? help ; - ;

### ISSUE THREAD

**Issue by BilalElhssaini** [Homebrew/brew#14532]
### `brew doctor` output

```shell
==> Downloading https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg
Already downloaded: /Users/user1/Library/Caches/Homebrew/downloads/e163886f3d57674f022eb584f07ef6d71dbbf58fb39c481a2c516ce6bfd4af18--Example.ogg
Error: scrcpy: SHA256 mismatch
Expected: 379071af4fa77bc7dacf892ad81d3f92040a628367d34a451a2cdcc997ef27b0
  Actual: f57b56d8aae4c847cf01224fb45293610d801cfdac43d932b5eeab1cd318182a
    File: /Users/user1/Library/Caches/Homebrew/downloads/e163886f3d57674f022eb584f07ef6d71dbbf58fb39c481a2c516ce6bfd4af18--Example.ogg
To retry an incomplete download, remove the file above.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
brew install scrcpy
```

### What were you trying to do (and why)?

brew install scrcpy

### What happened (include all command output)?

Error: scrcpy: SHA256 mismatch
Expected: 379071af4fa77bc7dacf892ad81d3f92040a628367d34a451a2cdcc997ef27b0
  Actual: f57b56d8aae4c847cf01224fb45293610d801cfdac43d932b5eeab1cd318182a
    File: /Users/user1/Library/Caches/Homebrew/downloads/e163886f3d57674f022eb584f07ef6d71dbbf58fb39c481a2c516ce6bfd4af18--Example.ogg

### What did you expect to happen?

idk scrcpy to work in normal way ??! ; -;

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
pff 
i just did cmd brew install scrcpy
and i think it fallis to open the Example.ogg file ;-;
idk wut happen that why iam here i need help.. ;-;
```

**Comment by MikeMcQuaid** [comment]
Open a discussion instead.
