### ISSUE TITLE
xz install fails on Fedora Silverblue

### ISSUE THREAD

**Issue by aral** [Homebrew/brew#14557]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
==> Fetching xz
Warning: Building xz from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /var/home/linuxbrew/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /var/home/linuxbrew/.linuxbrew)
==> Downloading https://downloads.sourceforge.net/project/lzmautils/xz-5.4.1.tar.gz
```

(On Silverblue, /var/home is /home) :)

### Verification

- [x] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install xz

### What happened (include all command output)?

See above

### What did you expect to happen?

For it to work.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install xz` on Fedora Silverblue
```

**Comment by MikeMcQuaid** [comment]
@iMichka any thoughts/news here?

**Comment by iMichka** [comment]
Yes, just found a solution in https://github.com/Homebrew/discussions/discussions/1282

Look at https://github.com/Homebrew/discussions/discussions/1282#discussioncomment-4766216 and https://github.com/Homebrew/discussions/discussions/1282#discussioncomment-5067527

Not sure if we should try to implement that workaround (if possible); or leave it up to our users.

**Comment by iMichka** [comment]
Closing as fixed as there is a workaround

**Comment by gromgit** [comment]
> Not sure if we should try to implement that workaround (if possible); or leave it up to our users.

I guess we can _suggest_ it. Actually implementing it would require editing `/etc/fstab` to make the bind mounts permanent, and that's quite invasive, even if the installer already has the necessary `sudo` permissions.
