### ISSUE TITLE
Permissions changing instructions are incomplete

### ISSUE THREAD

**Issue by cj13579** [Homebrew/brew#1456]
After getting myself in a pickle and ending up doing an upgrade of brew using `sudo` (based on [this comment in issue #1055 ](https://github.com/Homebrew/homebrew-core/issues/1055#issuecomment-223956084) brew will helpfully remind you to set your permissions back properly:

```bash
Chris-Blakes-MacBook-Pro:local chrisblake$ brew upgrade ruby
Error: /usr/local/Homebrew is not writable. You should change the
ownership and permissions of /usr/local/Homebrew back to your
user account:
  sudo chown -R $(whoami) /usr/local/Homebrew
```

However these instructions are incomplete because you will not actually be able to run any commands as it will give you a permission error when creating a lock file:

```bash
Chris-Blakes-MacBook-Pro:local chrisblake$ brew upgrade ruby
mkdir: /usr/local/var/homebrew/locks: Permission denied
/usr/local/Homebrew/Library/Homebrew/utils/lock.sh: line 19: /usr/local/var/homebrew/locks/update: No such file or directory
-e:1:in `initialize': Bad file descriptor (Errno::EBADF)
	from -e:1:in `new'
	from -e:1:in `<main>'
Error: Another active Homebrew process is already in progress.
Please wait for it to finish or terminate it to continue.
```

I think that the resolution to this is to change the permissions (or ownership) on the `/usr/local/var/homebrew` folder.

**Comment by MikeMcQuaid** [comment]
I'll take a look at this, thanks for the report.
