### ISSUE TITLE
Consider merging required OS and minimum OS version, and displaying a checkmark consistent for your OS

### ISSUE THREAD

**Issue by Porkepix** [Homebrew/brew#14563]
Opening the issue as requested by @nandahkrishna in https://github.com/Homebrew/homebrew-core/pull/122364#issuecomment-1418365739

### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 3.6.21-5-gb761344
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7613444287405c8a853bae980e1883c6899ec69
Last commit: 27 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b16ea1b58663e6284bf4f9d2808ecdd826d1fcd4
Core tap last commit: 23 hours ago
Core tap branch: master
Core tap JSON: 06 Feb 23:19 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit skylake
Clang: N/A
Git: 2.39.1 => /bin/git
Curl: 7.87.0 => /bin/curl
Kernel: Linux 6.1.7-arch1-1 x86_64 GNU/Linux
OS: Arch Linux
Host glibc: 2.37
/usr/bin/gcc: 12.2.1
/usr/bin/ruby: 3.0.5
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

I was just checking information with `brew info`

### What happened (include all command output)?

It displayed this:

```
$ brew info tart
==> tart: stable 0.37.0
macOS and Linux VMs on Apple Silicon to use in CI and other automations
[…]]
Required: arm64 architecture ✘, macOS ✔, macOS ✘
```

### What did you expect to happen?

Considering the command was ran from a Linux computer, macOS should be written only once and the checkmark should be a red cross.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew info tart` on a Linux computer to see an example, but that could happen on many other formulas.
```

**Comment by cho-m** [comment]
I wonder if we should just discard some unnecessary requirements on Linux. Specifically for:
https://github.com/Homebrew/brew/blob/b0a74e532361fab983b596b31509c2e6fd3066c1/Library/Homebrew/dependency_collector.rb#L161-L162

I think the first is only necessary when `tags.blank?` as the `tags` is for version (in)equality checks.

While second is also unnecessary on Linux.

Though not sure how easy it is to handle as I haven't looked further into code

**Comment by Porkepix** [comment]
> I wonder if we should just discard some unnecessary requirements on Linux. Specifically for:
> 
> https://github.com/Homebrew/brew/blob/b0a74e532361fab983b596b31509c2e6fd3066c1/Library/Homebrew/dependency_collector.rb#L161-L162
> 
> I think the first is only necessary when `tags.blank?` as the `tags` is for version (in)equality checks.
> 
> While second is also unnecessary on Linux.
> 
> Though not sure how easy it is to handle as I haven't looked further into code

I don't have a mac to check now, but I don't think it's only a question of Linux here: if I'm guessing correctly, the same command on a mac should display `macOS` twice, they'll just both have the green checkmark. So the requirement for the OS and the minimum version for that OS should either be displayed at one, or the latter could be displayed differently after checking first the OS condition;

**Comment by cho-m** [comment]
> I don't have a mac to check now, but I don't think it's only a question of Linux here: if I'm guessing correctly, the same command on a mac should display `macOS` twice, they'll just both have the green checkmark.

macOS requirement is related to versioning info so they are 2 separate requirements:
```
Required: arm64 architecture ✔, macOS >= 12 ✔, macOS ✔
```

Another example like `zig` which only has minimum requirement:
```
Required: macOS >= 11 ✔
```

**Comment by MikeMcQuaid** [comment]
Agreed this could be outputted better 👍🏻

**Comment by nandahkrishna** [comment]
Now that #14870 has been merged, the output should be better on Linux and macOS. On Linux, we now have:
```
$ brew info zig tcc tart ghz-web
==> zig: stable 0.10.1 (bottled), HEAD
...
==> Requirements
Required: macOS >= 11 (or Linux) ✔
...

==> tcc: stable 0.9.27 (bottled), HEAD
...
==> Requirements
Required: macOS <= 10.15 (or Linux) ✔
...

==> tart: stable 0.38.0
...
==> Requirements
Build: Xcode >= 14.1 (on macOS) ✔
Required: arm64 architecture ✘, macOS >= 12 (or Linux) ✔, macOS ✘
...

==> ghz-web: stable 0.114.0 (bottled)
...
==> Requirements
Build: Xcode >= 14.1 (on macOS) ✔
...
```
This will be available to non-developers after the next tag.

**Comment by Porkepix** [comment]
As I commented on https://github.com/Homebrew/brew/pull/14870#issuecomment-1458739103 isn't this still confusing to have macOS written twice for `tart`? Couldn't this be factored in a single macOS mention, especially the `(or Linux)` when right after it says that it's only for mac.

**Comment by nandahkrishna** [comment]
It isn't really confusing, in my opinion. It states the requirements exactly as they have been specified in the formula. I will admit that this is also the lazier solution, but I think it does the job of conveying things better than previously.

**Comment by cho-m** [comment]
I didn't have chance to finish, but idea I had was removing unnecessary requirements on Linux: #14565
