### ISSUE TITLE
Don't duplicate PATH entries

### ISSUE THREAD

**Issue by allanlewis** [Homebrew/brew#14560]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Currently, `brew-shellenv` prepends `/usr/local/bin` and `/usr/local/sbin` to `PATH`. On Mac OS (I haven't checked multiple versions) `/usr/local/bin` is already at or near the beginning of `PATH` so it's unnecessary. My proposal is that Homebrew checks if each directory is already in `PATH` and, if so, either doesn't add it again or deletes the existing entry before prepending it.

### What is the motivation for the feature?

This will remove duplicate entries from `PATH` on Mac OS, and on any system where `/usr/local/bin` or `/usr/local/sbin` is already in `PATH` when `brew shellenv` is run.

### How will the feature be relevant to at least 90% of Homebrew users?

I presume the majority of Homebrew users are using recent versions of Mac OS, so they probably have this issue of duplicate `PATH` entries.

### What alternatives to the feature have been considered?

Users could instead deduplicate their `PATH`s after running `brew shellenv`.

**Comment by MikeMcQuaid** [comment]
> `/usr/local/bin` is already at or near the beginning of `PATH` so it's unnecessary.

This depends on the user's configuration.

> My proposal is that Homebrew checks if each directory is already in `PATH` and, if so, either doesn't add it again or deletes the existing entry before prepending it.

Would review a PR for this but this seems low impact as-is and not an important change for us to solicit maintainer or other contributor work on.

Sorry!

**Comment by baggiponte** [comment]
Hi! Sorry to necrobump this. I am on a M1 mac and I found out the same behaviour. I call `eval "$(brew shellenv)"` basically at the top of my `.zshrc` (see [here](https://github.com/baggiponte/dotfiles/blob/main/zsh/include/paths.zsh)) and in no other place I modify my `$PATH` before. Nevertheless, I get the double `/opt/homebrew/bin` entry in my `$PATH`.

To check that, I added a `echo "$PATH"` statement inside the system `zshenv` (i.e. `/etc/zshenv`) and I noticed that `/opt/homebrew/bin` is already there well before any user config is loaded. How could this be?

**Comment by gromgit** [comment]
What's the output of `zsh -xl -c exit 2>&1 >/dev/null | grep /opt/homebrew/bin`?

**Comment by baggiponte** [comment]
Thanks for the reply!

> What's the output of `zsh -xl -c exit 2>&1 >/dev/null | grep /opt/homebrew/bin`?

```text
+/etc/zprofile:7> eval 'PATH="/usr/bin:/bin:/usr/sbin:/sbin:/Users/lucabaggi/.local/share/rtx/installs/python/3.10.10/bin:/Users/lucabaggi/.local/share/rtx/installs/nodejs/18.14.2/bin:/Users/lucabaggi/.local/share/pipx/bin:/Users/lucabaggi/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin";' export 'PATH;' 'MANPATH="/usr/share/man:/usr/local/share/man:/opt/homebrew/share/man";' export 'MANPATH;'
+(eval):1> PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Users/lucabaggi/.local/share/rtx/installs/python/3.10.10/bin:/Users/lucabaggi/.local/share/rtx/installs/nodejs/18.14.2/bin:/Users/lucabaggi/.local/share/pipx/bin:/Users/lucabaggi/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin 
```

What should I be looking out for?

**Comment by gromgit** [comment]
Sorry, forgot that adding `-c exit` makes the shell non-interactive, so the . Try this instead:
```sh
# Start a new login shell in tracing mode, logging all output to /tmp/zsh.log
script /tmp/zsh.log zsh -xl
# Hit Ctrl-D to exit the new shell, then...
grep /opt/homebrew/bin /tmp/zsh.log
```

**Comment by baggiponte** [comment]
Thanks! So I reviewed the logs:

```text
+/etc/zshenv:1> export ZDOTDIR=/Users/lucabaggi/.config/zsh
+/Users/lucabaggi/.config/zsh/.zshenv:6> export XDG_CONFIG_HOME=/Users/lucabaggi/.config
+/Users/lucabaggi/.config/zsh/.zshenv:7> export XDG_CACHE_HOME=/Users/lucabaggi/.cache
+/Users/lucabaggi/.config/zsh/.zshenv:8> export XDG_DATA_HOME=/Users/lucabaggi/.local/share
+/Users/lucabaggi/.config/zsh/.zshenv:9> export XDG_STATE_HOME=/Users/lucabaggi/.local/state
+/etc/zprofile:6> [ -x /usr/libexec/path_helper ']'
+/etc/zprofile:7> /usr/libexec/path_helper -s
+/etc/zprofile:7> eval 'PATH="/usr/bin:/bin:/usr/sbin:/sbin:/Users/lucabaggi/.local/share/rtx/installs/python/3.10.10/bin:/Users/lucabaggi/.local/share/rtx/installs/nodejs/18.14.2/bin:/Users/lucabaggi/.local/share/pipx/bin:/Users/lucabaggi/.cargo/bin:/opt/homebrew/bin:/usr/local/bin";' export 'PATH;'
+(eval):1> PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Users/lucabaggi/.local/share/rtx/installs/python/3.10.10/bin:/Users/lucabaggi/.local/share/rtx/installs/nodejs/18.14.2/bin:/Users/lucabaggi/.local/share/pipx/bin:/Users/lucabaggi/.cargo/bin:/opt/homebrew/bin:/usr/local/bin 
+(eval):1> export PATH
```

IIUC, `/usr/libexec/path_helper` stores the path so when downstairs `eval "$(brew shellenv)"` is run parameter expansion duplicates `/opt/homebrew/bin`.

Don't really know how if this is deserves being addressed; in that case, I'd like to help out.

**Comment by gromgit** [comment]
`/usr/libexec/path_helper` reads the contents of all the files in `/etc/paths.d`, and glues them together into a single `PATH`. It looks like one of the files in `/etc/paths.d` contains `/opt/homebrew/bin`, and Homebrew definitely didn't put it there, so it was done by you or someone else with root access.

Which set of instructions were you following, that told you to add an `/etc/paths.d` file for Homebrew?

**Comment by gromgit** [comment]
Sorry, misread your extract. `path_helper` always prepends _and_ deduplicates directories in `PATH`, so in your case, `/opt/homebrew/bin` is being added _before_ `path_helper` is called.

What's the output of `grep /opt/homebrew/bin /tmp/zsh.log`?
