### ISSUE TITLE
Pyenv installed and shim can't find the right executables.

### ISSUE THREAD

**Issue by Arbitrageur** [Homebrew/brew#1457]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I installed the latest pyenv(v1.0.2) using homebrew.
But when I tried to run python, it complains "No such file or directory"
`
/usr/local/var/pyenv/shims/python: line 21: /usr/local/Cellar/pyenv/1.0.2/libexec/pyenv: No such file or directory
`
I found that pyenv is installed at /usr/local/Cellar/pyenv/1.0.2_1, but the shims looking at /usr/local/Cellar/pyenv/1.0.2

How can I solve this without modifying shims or formula by hand?

**Comment by MikeMcQuaid** [comment]
This seems to be a `pyenv` usage question and I'm not sure if any of us use it. If `pyenv` works like `rbenv` then `pyenv rehash` may fix this. Let me know if it does.

**Comment by Arbitrageur** [comment]
@MikeMcQuaid It works! Thanks!
