### ISSUE TITLE
brew outdated doesn't actually list outdated formulae

### ISSUE THREAD

**Issue by penalvch** [Homebrew/brew#14579]
### `brew doctor` output

```shell
brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 3.6.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: 932d2cf3b77c9439a57b6a43577fc8d3b6399a62
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0c46c555dcb43e7ae3147392a71ebc2c1f5e0a26
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

Run:
brew outdated

and have it list formulae that would be upgraded if one runs:
brew upgrade

### What happened (include all command output)?

~ % brew outdated
~ % brew upgrade
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> New Formulae
kuttl        libsolv      micromamba   soplex       tl-expected  utftex
==> New Casks
coherence-x                gpgfrontend                nanosaur2

You have 7 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Upgrading 7 outdated packages:
aom 3.5.0_2 -> 3.6.0
numpy 1.24.1 -> 1.24.2
openssl@3 3.0.7 -> 3.0.8
openssl@1.1 1.1.1s -> 1.1.1t
python@3.10 3.10.9 -> 3.10.10
sdl2 2.26.2 -> 2.26.3
libx11 1.8.3 -> 1.8.4

### What did you expect to happen?

brew outdated
You have 7 outdated formulae installed.
aom 3.5.0_2 -> 3.6.0
numpy 1.24.1 -> 1.24.2
openssl@3 3.0.7 -> 3.0.8
openssl@1.1 1.1.1s -> 1.1.1t
python@3.10 3.10.9 -> 3.10.10
sdl2 2.26.2 -> 2.26.3

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew outdated
```

**Comment by carlocab** [comment]
Run `brew update` before `brew outdated`. `brew upgrade` does this automatically, which is why it picked up outdated formulae after the update.

**Comment by MikeMcQuaid** [comment]
Closing. We could consider making `brew outdated` also run `brew update`.
