### ISSUE TITLE
FreeTDS Upgrade fails due to broken download link 

### ISSUE THREAD

**Issue by sam-s** [Homebrew/brew#1458]
Same as [Issue#158](https://github.com/Homebrew/brew/issues/158):

```
$ brew update && brew upgrade && brew cleanup
==> Upgrading 1 outdated package, with result:
freetds 1.00.16
==> Upgrading freetds
==> Using the sandbox
==> Downloading ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.16.tar.gz

curl: (56) response reading failed
Trying a mirror...
==> Downloading https://fossies.org/linux/privat/freetds-1.00.16.tar.gz

curl: (22) The requested URL returned error: 410 Gone
Error: Failed to download resource "freetds"
Download failed: https://fossies.org/linux/privat/freetds-1.00.16.tar.gz
```

**Comment by sam-s** [comment]
the correct URL is `https://fossies.org/linux/privat/freetds-1.00.18.tar.gz`

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Also, for future reference please file formulae issues on https://github.com/Homebrew/homebrew-core.

Thanks!

**Comment by MikeMcQuaid** [comment]
Thanks for creating the PR @sam-s ❤️
