### ISSUE TITLE
How Do I Fix/Silence "Use new_tap/xxx instead of deprecated old_tap/xxx" Warnings?

### ISSUE THREAD

**Issue by DabeDotCom** [Homebrew/brew#1459]
I have a question...

After ce2b11f/#1371 went in, `brew outdated` (as well as `brew uses --installed <formula>` and maybe others) started spitting out a handful of, e.g.
```
Warning: use homebrew/dups/apple-gcc42 instead of homebrew/core/apple-gcc42
```
messages — which I understand is to allow third-party taps to migrate formulae into and out of core...  (And yes, I'm heavily in favor of future-proofing!)

My problem, though, is: What do I have to do to "use" the new location instead?  These formulae have been installed (and working fine!) forever...

`brew info` seems happy with the status quo:
```
prompt% brew info apple-gcc42
homebrew/dupes/apple-gcc42: stable 4.2.1-5666.3 (bottled)    ### <--
GNU compiler collection
https://r.research.att.com/tools/
/usr/local/Cellar/apple-gcc42/4.2.1-5666.3 (107 files, 74.7M) *
  Poured from bottle on 2013-09-26 at 14:52:37               ### <--
[...]
```

Do I have to manually install all these apps from the new, fully-scoped locations?  When I try that, `brew install` and `brew upgrade` claim everything is already up-to-date:
```
prompt% brew install homebrew/dupes/apple-gcc42
Warning: homebrew/dupes/apple-gcc42-4.2.1-5666.3 already installed

prompt% brew upgrade homebrew/dupes/apple-gcc42
Error: homebrew/dupes/apple-gcc42 4.2.1-5666.3 already installed
```

So does *that* mean I have to uninstall the existing versions, first?  (More importantly: **SHOULD** I have to?!)

Given that I didn't actually /explicitly/ list those formula names when running `brew outdated`, the fact that there's no clear instructions about how to rectify the situation makes these messages a little Less Than Awesome, IMHO.  :-\

**Comment by MikeMcQuaid** [comment]
Thanks for the report. This is a bug and I'll work on a fix.

**Comment by MikeMcQuaid** [comment]
For now a `brew reinstall apple-gcc42` should fix this for you.

**Comment by DabeDotCom** [comment]
I know it's going to void my warranty, but my hackish workaround was just to 'sed' the corresponding `/usr/local/Cellar/**/INSTALL_RECEIPT.json` files...

I `HOMEBREW_BUILD_FROM_SOURCE=1` most things, and was feeling too impatient to sit through a half-a-dozen re-compiles.  :-}  (And I can easily undo it, if necessary...)

**Comment by MikeMcQuaid** [comment]
@DabeDotCom No worries, that's probably a sensible approach if you want to avoid reinstalling. Thanks!

**Comment by MikeMcQuaid** [comment]
PR opened in https://github.com/Homebrew/brew/pull/1485.
