### ISSUE TITLE
Latest merge breaks installation

### ISSUE THREAD

**Issue by ebastos** [Homebrew/brew#14598]
### `brew doctor` output

```shell
N/A - Brew is not installing on a fresh system
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
N/A
```

### What were you trying to do (and why)?

Install brew from fresh

### What happened (include all command output)?

Installation failed:

```bash
==> Downloading and installing Homebrew...
HEAD is now at 1cf53b428 Merge pull request #14589 from MikeMcQuaid/api_auto_update_secs
Error: Failed to download formula.json!
Failed to download cask.json!
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force --quiet
```

### What did you expect to happen?

Installation should succeed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by seagle0128** [comment]
I am experiencing the same issue... Recently brew is not stable.

**Comment by Bo98** [comment]
Can you post the output of:

```
curl --disable --fail --compressed --speed-limit 100 --speed-limit 5 --location --output /dev/null https://formulae.brew.sh/api/formula.json
```

**Comment by seagle0128** [comment]
```
❯ curl --disable --fail --compressed --speed-limit 100 --speed-limit 5 --location --output /dev/null https://formulae.brew.sh/api/formula.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3407k  100 3407k    0     0  13847      0  0:04:12  0:04:11  0:00:01  9735
```

**Comment by Bo98** [comment]
Hmm not sure then if it's not erroring.

It does seem a bit slow, but some people are setting up mirrors (for example: https://github.com/tuna/issues/issues/1666) that may help you a bit there.

**Comment by ebastos** [comment]
For my specific case I got a SSL and after digging a little I found the problem was related to Zscaler injecting itself in my connection, causing the Docker container running the curl command to get an unknown certificate.

Fixed by disabling zscaler and re-running the script. Not related to brew.

I apologize for the confusion.

**Comment by Bo98** [comment]
Thanks for reporting back!

We should definitely improve the error output and I'll open a separate issue for that following 4.0.0.
