### ISSUE TITLE
Introduce a way to disable a package’s telemetry according to its formula/cask

### ISSUE THREAD

**Issue by NonsenseInc** [Homebrew/brew#14604]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Software ideally has a way to disable telemetry. The way to do this is individual to the software. If a cask or formula defines a way to disable the telemetry of a piece of software, brew could then automatically disable the telemetry of that software on installation.

Maybe this could be a flag on install like `brew install —disable-telemetry formula`.

### What is the motivation for the feature?

Software often provides settings to disable telemetry due to concerns about privacy. Sadly this is sometimes only provided in an (one might say obscure) opt-out pattern.

A users stance on privacy might be individual to each package, but generally - I suppose - is a general stance.

Wikipedia defines a package manager as follows: 
> A package manager or package-management system is a collection of software tools that automates the process of installing, upgrading, configuring, and removing computer programs for a computer in a consistent manner.

If homebrew concurs, that configuration is a feature of a package manager, and if its aim is to assist the user in reducing effort in software setup, then it should provide said feature.

### How will the feature be relevant to at least 90% of Homebrew users?

Privacy is a concern of many users. This is shown by the fact, that software provides settings to disable telemetry, and by the fact, that laws are created in many places to address the issue of software ‘phoning home’.

I cannot claim, that 90% of users of homebrew will be disabling telemetry in software, but I suppose they mostly don’t, because it is too much an effort to do so. 

It is well discussed that obscuring privacy options is a common strategy to move users to ignore them. Providing said feature might enable users to enforce their preferences. One might call this an accessibility feature for people that are generally unable to parse through obscure settings.

### What alternatives to the feature have been considered?

The alternative in a homebrew focused perspective would be to limit it’s understanding of the term package manager and leave it to the user to setup their software according to their general stance in an per-package way.

Sadly I am unaware of feasible alternatives.

**Comment by MikeMcQuaid** [comment]
I think this is the sort of thing, like the `brew desc` and licensing additions were, where it's best to start in an external tap/external command and we can consider adding something like this when it's at least partially implemented in that form.

I also don't think that most software has an easy way to disable this and I worry that an argument like this opens Homebrew to being criticised when we don't correctly handle this universally (which will be impossible).

Sorry, passing on this for now.

**Comment by NonsenseInc** [comment]
Thank you for evaluating the idea!
