### ISSUE TITLE
Developer commands should be disabled when developer mode is off

### ISSUE THREAD

**Issue by shonjir** [Homebrew/brew#14606]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When a developer mode command is issued and developer mode is off (the default), current behavior is to display the developer mode warning once and then enable developer mode.

Brew should not automatically assume the user wants to enable developer mode and tap homebrew-core or homebrew-cask.

Proposed behavior would require developer mode to be explicitly enabled by setting HOMEBREW_DEVELOPER or running 'brew developer on'.  When developer mode is off and a developer mode command is issued brew should simply display the developer mode warning and terminate.

### What is the motivation for the feature?

Since installation from API was introduced, I've untapped homebrew-core and homebrew-cask since they're no longer necessary.

Although I have contributed to brew in the past, I do not actively develop brew formula.  However, I frequently will use commands like 'brew cat' to look into formula for dependencies, etc.  There are now alternatives like 'brew info --github' but muscle memory persists.

The current behavior of automatically enabling developer mode has become quite obnoxious as it results in automatically setting 'brew developer on' and re-tapping homebrew-core or homebrew-cask, requiring me to reset 'brew developer off' every time.  

### How will the feature be relevant to at least 90% of Homebrew users?

Developer mode is not relevant for most users simply looking to install a package.

It is counterintuitive to automatically enable this mode since it can have adverse effects on the user's installation.

Because the developer mode warning is only issued once and developer mode uses HEAD most users will not realize the implications resulting in a different and potentially less-stable experience.

In addition, homebrew-core and/or homebrew-cask will no longer be automatically tapped resulting in a large unexpected download.

### What alternatives to the feature have been considered?

I looked for a variable to disable the automatic enabling of developer mode (such as "HOMEBREW_DEVELOPER=disabled" or "HOMEBREW_DISABLE_DEVELOPER_MODE=1" but such configuration is not supported.

**Comment by apainintheneck** [comment]
It seems like the real problem here is that certain commands automatically tap the core and cask repos when you use them even if you're only using the API. I just checked and all of the commands we enable `HOMEBREW_NO_INSTALL_FROM_API` for are developer commands.

https://github.com/Homebrew/brew/blob/ed793811553eb6fca3dd602931e37b7187f86a68/Library/Homebrew/brew.sh#L785-L808

Maybe it would be enough to just make those commands require `HOMEBREW_NO_INSTALL_FROM_API` again and not set it automatically.

Also, for the `brew cat` use case maybe we should add a nudge to use the `brew info` command instead.

**Comment by shonjir** [comment]
That solution would work for me.

**Comment by RandomDSdevel** [comment]
> Because the developer mode warning is only issued once and developer mode uses HEAD most users will not realize the implications resulting in a different and potentially less-stable experience.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aside:  Users who've entered developer mode can still make Homebrew update only to a tagged release and not to the latest commit from '`master`' by setting the environment variable '`HOMEBREW_UPDATE_TO_TAG`.'

**Comment by carlocab** [comment]
> Brew should not automatically assume the user wants to enable developer mode and tap homebrew-core or homebrew-cask.
> 
> Proposed behavior would require developer mode to be explicitly enabled by setting HOMEBREW_DEVELOPER or running 'brew developer on'. When developer mode is off and a developer mode command is issued brew should simply display the developer mode warning and terminate.

This would be a breaking change for `brew`'s CLI behaviour, so it's unlikely we can do this without a protracted transition period (because it would break many users), if we even do it at all.

One thing that might be simple to do is to provide a `HOMEBREW_DISABLE_DEVELOPER_COMMANDS` that will make `brew` exit with an error if a dev command is run.

**Comment by MikeMcQuaid** [comment]
> One thing that might be simple to do is to provide a `HOMEBREW_DISABLE_DEVELOPER_COMMANDS` that will make `brew` exit with an error if a dev command is run.

Let's not provide more options based on a single request.

> Brew should not automatically assume the user wants to enable developer mode

I disagree with this.

> and tap homebrew-core or homebrew-cask.

I agree with this. I see this auto-tapping as being very annoying. Will open a PR.
