### ISSUE TITLE
audit: cask `curl_http_content_headers_and_checksum` audit not passing arguments (referer)

### ISSUE THREAD

**Issue by bevanjkay** [Homebrew/brew#14607]
[This PR](https://github.com/Homebrew/homebrew-cask/pull/141033) is currently failing CI audits due to the `curl_http_content_headers_and_checksum` audit failing.
The binary is able to be downloaded during `brew fetch` however the `referer` argument is not being passed during the failing audit step.

I was able to have the audit pass by manually adjusting the code below to include the `referer` from the cask by adjusting the specs argument here to be `{ "e" => "https://www.toketaware.com/" }`
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/curl.rb#L275

The relevant audit;
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/curl.rb#L365-L379

Relevant PR;
https://github.com/Homebrew/homebrew-cask/pull/141033

**Comment by MikeMcQuaid** [comment]
Feels like the correct solution here is to make the audit pass the `referrer` correctly.
