### ISSUE TITLE
Tabs erroneously generated with `built_as_bottle: true`

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#14619]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.21-99-g2a417f1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2a417f14163aacfb4ffcb754fe9dea71c46f6ad0
Last commit: 12 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0bbb89420e74756a5a5c145ed7efa4a32f7e7e7c
Core tap last commit: 24 hours ago
Core tap branch: master
Core tap JSON: 14 Feb 02:32 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.39.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.4.0-1103-azure x86_64 GNU/Linux
OS: Ubuntu 22.04.1 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

Install any formula, for any reason.

### What happened (include all command output)?

The tab is recorded with `built_as_bottle: true`.

```
linuxbrew@codespaces-07ca68:/workspaces/brew$ brew install --quiet hello
==> Fetching hello
🍺  /home/linuxbrew/.linuxbrew/Cellar/hello/2.12.1: 55 files, 650KB
==> Running `brew cleanup hello`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

linuxbrew@codespaces-07ca68:/workspaces/brew$ jq .built_as_bottle "$(brew --prefix hello)/INSTALL_RECEIPT.json"
true
```

I first discovered this on my Mac, but I hopped on a codespace to make sure it wasn't just my machine.

### What did you expect to happen?

`hello` was not built as a bottle, so
```
jq .built_as_bottle "$(brew --prefix hello)/INSTALL_RECEIPT.json"
```
should return `false`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install jq
jq .built_as_bottle "$(brew --prefix jq)/INSTALL_RECEIPT.json"
```

**Comment by carlocab** [comment]
So I _think_ `brew` has generated tabs that contain this for basically forever, but I suspect the correct behaviour here for poured bottles is for `built_as_bottle` to be `false`. This prevents you from doing things like `brew bottle hello` if you didn't `brew install --build-bottle hello`.

**Comment by Bo98** [comment]
We do somewhat handle this in tab methods:

```rb
def built_bottle?
  built_as_bottle && !poured_from_bottle
end

def bottle?
  built_as_bottle
end
```

So I guess `brew bottle` just checks the wrong one.

**Comment by carlocab** [comment]
```
linuxbrew@codespaces-07ca68:/tmp$ jq .poured_from_bottle $(brew --prefix hello)/INSTALL_RECEIPT.json
true
linuxbrew@codespaces-07ca68:/tmp$ brew bottle hello
==> Determining hello bottle rebuild...
==> Bottling hello--2.12.1.x86_64_linux.bottle.1.tar.gz...
./hello--2.12.1.x86_64_linux.bottle.1.tar.gz
  bottle do
    rebuild 1
    sha256 x86_64_linux: "503ce6cc48f9720d17e5e5602a2ce45244910467bd829c33a2dd2d50bfd650aa"
  end
```

**Comment by carlocab** [comment]
> linuxbrew@codespaces-07ca68:/tmp$ jq .poured_from_bottle $(brew --prefix hello)/INSTALL_RECEIPT.json
> true
> linuxbrew@codespaces-07ca68:/tmp$ brew bottle hello
> ==> Determining hello bottle rebuild...
> ==> Bottling hello--2.12.1.x86_64_linux.bottle.1.tar.gz...
> ./hello--2.12.1.x86_64_linux.bottle.1.tar.gz
>   bottle do
>     rebuild 1
>     sha256 x86_64_linux: "503ce6cc48f9720d17e5e5602a2ce45244910467bd829c33a2dd2d50bfd650aa"
>   end

Yea, something's going wrong somewhere, since I can `brew bottle` bottles I poured, which I shouldn't be able to.

**Comment by Bo98** [comment]
Basically this: 

https://github.com/Homebrew/brew/blob/2a417f14163aacfb4ffcb754fe9dea71c46f6ad0/Library/Homebrew/utils/bottles.rb#L26

should probably be `tab.built_bottle?`

**Comment by MikeMcQuaid** [comment]
> I suspect the correct behaviour here for poured bottles is for `built_as_bottle` to be `false`.

No, this is meant to be true.

> since I can `brew bottle` bottles I poured, which I shouldn't be able to.

This is by design.
