### ISSUE TITLE
Installing Scala 2.12.0 fails with SHA256 mismatch

### ISSUE THREAD

**Issue by naderghanbari** [Homebrew/brew#1461]
Error: SHA256 mismatch
    Expected: d4f485b3f05bbf1224ed5db34d5a5322ce8d1676236757a6cfbf4a11ac59ca22
    Actual: 42be98ff9754518fd5c9a942c94ffba2464667a5e95ed4917e4e95565c96bdfe
    Archive: /Users/Nader/Library/Caches/Homebrew/scala-2.12.0.tgz
    To retry an incomplete download, remove the file above.

**Comment by MikeMcQuaid** [comment]
`brew update`, this has been addressed.
