### ISSUE TITLE
Defining `RunAtLoad` for the service plist file

### ISSUE THREAD

**Issue by DenizUgur** [Homebrew/brew#14612]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

The generated plist files have the `RunAtLoad` set as false by default. It would've been nice to have this as an argument within the `service do` block.

### What is the motivation for the feature?

My bottle runs on an interval but I need it to start as soon as it gets installed.

### How will the feature be relevant to at least 90% of Homebrew users?

Yes, one could create his/her own plist file but wouldn't be nice for people to have this option through homebrew?

### What alternatives to the feature have been considered?

Frankly, I haven't tried anything else since I know that creating my own plist file is a solution here.

**Comment by carlocab** [comment]
Have you tried doing
```ruby
service do
  ...
  run_type :immediate
  ...
end
```
?

**Comment by DenizUgur** [comment]
How about using it with an interval?

**Comment by MikeMcQuaid** [comment]
@DenizUgur Can you clarify your answer to @carlocab's question? I don't understand here.

CC @SMillerDev for any thoughts

**Comment by DenizUgur** [comment]
Alright, sorry for the confusion. Maybe I haven't fully understood @carlocab's answer. No, I haven't tried it just because I'm not so sure how `run_type` can be used with both `interval` and `immediate`. This is because I require my service to run every 15 minutes starting right after the instalaltion.

**Comment by DenizUgur** [comment]
IMO, `immediate` should be a separate type than `run_type`.

https://github.com/Homebrew/brew/blob/2a417f14163aacfb4ffcb754fe9dea71c46f6ad0/Library/Homebrew/service.rb#L374

**Comment by SMillerDev** [comment]
I think it's easier to judge your suggestion as a pull request.

**Comment by DenizUgur** [comment]
@SMillerDev please see PR #14624
