### ISSUE TITLE
The cask is still marked as installed when refusing to enter password for sudo and failing the installation

### ISSUE THREAD

**Issue by Kentzo** [Homebrew/brew#14625]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I've been doing tests for https://github.com/Homebrew/brew/pull/14593 and noticed that interrupting the installation (via ctrl-c) at the password prompt resulted in still being listed as installed:

```
$ sudo -k
$ brew install --cask microsoft-edge
...
==> Running installer for microsoft-edge; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Password:
^C
$ brew list --cask
... microsoft-edge ...
```

That's true for movable casks too.

### Command that failed

N/A

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by MikeMcQuaid** [comment]
@Kentzo in future please always fill out the issue template

**Comment by MikeMcQuaid** [comment]
Will review a PR for this but won't keep it open indefinitely, sorry.
