### ISSUE TITLE
`brew audit` requires admin privileges when run on a local formula

### ISSUE THREAD

**Issue by vszakats** [Homebrew/brew#1462]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Starting a few months ago, `brew audit` is no longer able to run when run from a restricted user account. Here is the error:

```
$ brew audit --strict --online ./podiff.rb 
error: could not lock config file /usr/local/Homebrew/.git/config: Permission denied
Error: Failure while executing: git config --file=/usr/local/Homebrew/.git/config --replace-all homebrew.devcmdrun true
```

Homebrew is (and was) installed under an admin account, and admin is the only account on the sudo-ers list.

Expected behaviour would be that `brew audit` doesn't attempt to modify global state and runs successfully when a local file is passed using a restricted user account.

**Comment by MikeMcQuaid** [comment]
@vszakats Can you run the same command with `--debug --verbose` on the end? Thanks!

**Comment by ilovezfs** [comment]
```
Error: Failure while executing: git config --file=/usr/local/Homebrew/.git/config --replace-all homebrew.devcmdrun true
```
lol

**Comment by vszakats** [comment]
`--debug --verbose`:
```
$ brew audit --strict --online --debug --verbose ./podiff.rb 
git config --file=/usr/local/Homebrew/.git/config --replace-all homebrew.devcmdrun true
error: could not lock config file /usr/local/Homebrew/.git/config: Permission denied
Error: Failure while executing: git config --file=/usr/local/Homebrew/.git/config --replace-all homebrew.devcmdrun true
/usr/local/Homebrew/Library/Homebrew/utils.rb:276:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/brew.rb:68:in `<main>'
```

**Comment by ilovezfs** [comment]
Does it still happen if you set `export HOMEBREW_DEVELOPER=1` in your environment?

**Comment by vszakats** [comment]
@ilovezfs That resolves it. Thank you for this tip!

I'd argue it'd be nice to make it work without this. `brew audit` is useful for Homebrew users just willing to check their custom-rolled formulae.

(I will need to read more about the exact meaning of this setting.)

**Comment by ilovezfs** [comment]
What's going on is that we're trying to record that the user used a dev-cmd even though HOMEBREW_DEVELOPER isn't set in the environment so we can tweak the behavior of things like brew update. So we'll either have to change where that information is saved or make audit a non-dev command (but of course then the same problem will still affect other dev-cmds in that case).

**Comment by vszakats** [comment]
Maybe, if the argument passed to `audit` is a local file (= contains a pathspec), it should not be considered a dev-cmd. (without a pathspec, it would try to `audit` the formula under the main Homebrew installation &mdash; at least this was my experience).

**Comment by MikeMcQuaid** [comment]
I think the fix in this case is just ignore it if we can't write to it.

**Comment by vszakats** [comment]
@MikeMcQuaid Sounds good to me!

**Comment by ilovezfs** [comment]
That's problematic if they _do_ have write access to the core tap, etc. since then we're back to the same old brew-ate-my-homework update problem.
