### ISSUE TITLE
Suggestions for load performance problems caused by the growth of formula.json files in some low-speed network scenarios.

### ISSUE THREAD

**Issue by ljq** [Homebrew/brew#14636]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

As the historical accumulation of formula.json file is increasing and the growth of individual files is increasing, it is recommended to split this file to improve the speed of json parsing and verification, and improve the execution under low network conditions. This suggestion is for my consideration. Thank you.

### What is the motivation for the feature?

Slow or failed load parsing in under low network conditions.

### How will the feature be relevant to at least 90% of Homebrew users?

Some, or more, are not sure.

### What alternatives to the feature have been considered?

Personal suggestion split download the formula.json file, cache hash check, find out the difference part of the update check, the efficiency may be better.

**Comment by MikeMcQuaid** [comment]
Passing on this for now. We will consider it in future.

**Comment by ljq** [comment]
OK
