### ISSUE TITLE
Cleanup CodeCov tests output spam

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#14662]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

CodeCov's coverage reporter outputs a huge string multiple times each test run:
https://github.com/Homebrew/brew/actions/runs/4194693982/jobs/7273227048#step:8:227

This information is not useful to us and makes it harder to quickly pass failing tests output.

### What is the motivation for the feature?

Make GitHub Actions logs more readable.

### How will the feature be relevant to at least 90% of Homebrew users?

Saving maintainer time (which is the project's most precious resource).

### What alternatives to the feature have been considered?

Getting over it.

**Comment by issyl0** [comment]
https://github.com/codeclimate-community/simplecov_json_formatter/blob/a03461117e6a837ca68c08fba98852819664f66a/lib/simplecov_json_formatter.rb#L30-L33

**Comment by MikeMcQuaid** [comment]
@issyl0 That was my first suspect too but it has a "JSON" prefix. Think it's `SimpleCov::Formatter::CoberturaFormatter`.

**Comment by issyl0** [comment]
Ah, it's also in the HTML formatter: https://github.com/simplecov-ruby/simplecov-html/blob/5bc5798aefed312abd189baed8a97bf1febfa8d7/lib/simplecov-html.rb#L34-L36.
