### ISSUE TITLE
How do I point brew at a local formula?

### ISSUE THREAD

**Issue by jaredjstewart** [Homebrew/brew#1468]
I have forked homebrew, edited a formula, and would like to make a pull request.  The steps in the "Contributing to Homebrew" guide say to run:
```
brew install --build-from-source foo
```

It seems like there is a step missing: What do I need to do in order to point homebrew at my edited version of the formula?

**Comment by vitorgalvao** [comment]
To be absolutely sure you’re pointing it at your modified formula, wherever it is located, give it the exact path to the file (`brew install --build-from-source ./foo.rb`, for example).

**Comment by MikeMcQuaid** [comment]
@jaredjstewart It uses your edited version by default. Is it not behaving as expected? Did you use `brew edit` or `brew audit`? Thanks!

**Comment by jaredjstewart** [comment]
My confusion arose from having Homebrew installed at /usr/local/Homebrew, but then also cloning the homebrew-core repo into ~/homebrew-core. Thanks for clearing this up!

**Comment by jaredjstewart** [comment]
I pushed my changes here: https://github.com/jaredjstewart/homebrew-core/tree/fixJavaVersionForApacheGeode

However, I didn't open a PR yet, since I encountered and error when running `brew audit --strict foo`:

```
apache-geode:
  * version should not decrease
Error: 1 problem in 1 formula
```

Can you provide any guidance for how to go about fixing this problem?  (The change I made was for apache-geode to require Java 1.8 instead of 1.8+, as Geode does not play well with Java 9.)

**Comment by MikeMcQuaid** [comment]
@jaredjstewart Open the PR anyway, you can probably ignore that. Glad you got it sorted!
