### ISSUE TITLE
Bash completion is partially broken after introducing cache

### ISSUE THREAD

**Issue by andr1an** [Homebrew/brew#14681]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 17c872fb5275d87922a56416587cb439a5064354
Last commit: 18 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1655c17518c96f9f5c4819b95cbe51539d30d3e9
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 17 Feb 07:03 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.2 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

### What were you trying to do (and why)?

I am using macOS 13.2 Ventura and Homebrew 4.0.1, with a regular macOS Bash 3.2 and a corresponding `bash-completion` formulae. After one of Homebrew upgrades, Bash completion stopped to work for `brew` subcommands (`update`, `cleanup`, `bundle`, `--prefix` etc.), but it does work for package names (i.e. `brew info <TAB>`).

### What happened (include all command output)?

Bash trace:

```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)
Copyright (C) 2007 Free Software Foundation, Inc.
$ set -x
$ brew u+ local i=1 cmd
+ [[ 1 -lt 1 ]]
+ [[ 1 -eq 1 ]]
+ __brew_complete_commands
+ local cur=u
+ local cmds
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ read -r line
++ compgen -W '' -- u
+ export __HOMEBREW_COMMANDS=
+ __HOMEBREW_COMMANDS=
+ return
```

It does not pop up commands `update` or `upgrade` after I type `brew u` and press TAB.

Most likely caused by a missing default value for `HOMEBREW_REPOSITORY` in [da9e29](https://github.com/Homebrew/brew/commit/da9e29ced88c947c2e1894c2e5e824ecaa72d2ee).

### What did you expect to happen?

Bash should suggest the subcommands.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# Install Homebrew on an Intel Mac
# Run `bash`
# Run `source /usr/local/Homebrew/completions/bash/brew`
# Type `brew c` and press TAB – the command does not complete to `cleanup`
```

**Comment by MikeMcQuaid** [comment]
CC @maxim-belkin for thoughts

**Comment by maxim-belkin** [comment]
![image](https://user-images.githubusercontent.com/13123663/219692379-c3b8f035-70c9-438c-9991-46d90ff6642d.png)

@andr1an, you don't have `HOMEBREW_REPOSITORY` set (the third `[[ -n '' ]]` ☝🏻), which means that you haven't added output of `brew shellenv` to your shell's start-up files (you should have `HOMEBREW_PREFIX`, `HOMEBREW_CELLAR`, and `HOMEBREW_REPOSITORY` environment variables set). So, the quickest fix for you is to do this:
```
eval "$(brew shellenv)"
```
and to make this fix permanent, this:
```
echo 'eval "$(brew shellenv)"' >> ~/.bash_profile # or any other file your shell sources
```

@MikeMcQuaid, situations like this can be handled in different ways:
1. Warn users that HOMEBREW_REPOSITORY is not set when Bash completions script is sourced. As an option, we can stop execution of the script.
2. Set HOMEBREW_REPOSITORY if it is not set. This is what Homebrew/services do in their Bash completion script.

And independently of the above:
- Make the conditional block work regardless of whether HOMEBREW_REPOSITORY is set. The downside is that users won't know that completions are slow because they're calling `brew --prefix` every time they try to autocomplete a command

**Comment by maxim-belkin** [comment]
> 2\. This is what Homebrew/services do in their Bash completion script.

I was referring to this: https://github.com/Homebrew/homebrew-services/blob/master/completions/bash/brew-services#L5-L6

**Comment by andr1an** [comment]
How do you think about this?

```diff
diff --git a/completions/bash/brew b/completions/bash/brew
index d7197267f..d783b28dc 100644
--- a/completions/bash/brew
+++ b/completions/bash/brew
@@ -96,17 +96,21 @@ __brew_complete_commands() {
   # Do NOT auto-complete "*instal" aliases for "*install" commands

   local cur="${COMP_WORDS[COMP_CWORD]}"
-  local cmds
+  local cmds repository cache

   if [[ -n ${__HOMEBREW_COMMANDS} ]]
   then
     cmds=${__HOMEBREW_COMMANDS}
-  elif [[ -n ${HOMEBREW_CACHE:-} && -f ${HOMEBREW_CACHE}/all_commands_list.txt ]]
-  then
-    cmds="$(< "${HOMEBREW_CACHE}/all_commands_list.txt" \grep -v instal$)"
-  elif [[ -n ${HOMEBREW_REPOSITORY:-} && -f ${HOMEBREW_REPOSITORY}/completions/internal_commands_list.txt ]]
-  then
-    cmds="$(< "${HOMEBREW_REPOSITORY}/completions/internal_commands_list.txt" \grep -v instal$)"
+  else
+    cache="${HOMEBREW_CACHE:-$(brew --cache)}"
+    repository="${HOMEBREW_REPOSITORY:-$(brew --repo)}"
+    if [[ -n ${cache} && -f ${cache}/all_commands_list.txt ]]
+    then
+      cmds="$(< "${cache}/all_commands_list.txt" \grep -v instal$)"
+    elif [[ -n ${repository} && -f ${repository}/completions/internal_commands_list.txt ]]
+    then
+      cmds="$(< "${repository}/completions/internal_commands_list.txt" \grep -v instal$)"
+    fi
   fi
   while read -r line; do COMPREPLY+=("${line}"); done < <(compgen -W "${cmds}" -- "${cur}")
   export __HOMEBREW_COMMANDS=${cmds}
```

**Comment by MikeMcQuaid** [comment]
> ```diff
> repository="${HOMEBREW_REPOSITORY:-$(brew --repo)}"
> ```

@andr1an Something like this makes sense to me 👍🏻

**Comment by MikeMcQuaid** [comment]
> 2\. Set HOMEBREW_REPOSITORY if it is not set. This is what Homebrew/services do in their Bash completion script.

@maxim-belkin this is preferable. We shouldn't rely on `brew shellenv` but should allow it for optimisation if possible.

**Comment by maxim-belkin** [comment]
> How do you think about this?

We can set variables in the beginning of the script like Homebrew/services:

```
: "${HOMEBREW_PREFIX:=$(brew --prefix)}"
: "${HOMEBREW_CACHE:=$(brew --cache)}"
```
And keep the rest of the script unchanged.
