### ISSUE TITLE
Remove usage of `Exclude` with `rubocop`

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#14685]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When `Exclude` is used in e.g. `.rubocop.yml` files: these are not always handled consistently by e.g. the VSCode `rubocop` integration and they aren't flagged as unnecessary when they on longer are.

We should instead:
- disable all the `rubocop` rules we're never going to realistically fix e.g. `Metrics/ClassLength`
- for those we'd like to tackle some day, use `# rubocop:disable` with a reason in the file itself

### What is the motivation for the feature?

VSCode not to flag all of `formula_installer.rb` as failing `rubocop` :sweat

### How will the feature be relevant to at least 90% of Homebrew users?

It wouldn't be but it will make life easier for maintainers and contributors.

### What alternatives to the feature have been considered?

Fixing all these rules.

**Comment by issyl0** [comment]
> disable all the rubocop rules we're never going to realistically fix e.g. Metrics/ClassLength

Do you mean disable the rules entirely across everything (`Enabled: false`), not just for the specific files? I agree that we are never going to get the big files below the limits any time soon, but that seems like a slippery slope towards a lot more files becoming like `formula.rb`.

**Comment by MikeMcQuaid** [comment]
> Do you mean disable the rules entirely across everything (`Enabled: false`)

Yes.

> but that seems like a slippery slope towards a lot more files becoming like `formula.rb`.

It seems these numbers just keep getting bumped anyway so: I'm not sure it's stopping anything right now and is just annoying for no real reason 😢

**Comment by issyl0** [comment]
This is as done as it's gonna get! The remaining `Exclude`s are for tap paths and `Homebrew/MoveToExtendOS`.

**Comment by MikeMcQuaid** [comment]
Great work, thanks @issyl0!
