### ISSUE TITLE
CoreTap has no git_head when installing from API, breaking brew bundle

### ISSUE THREAD

**Issue by colindean** [Homebrew/brew#14698]
### `brew doctor` output

```shell
==> Downloading https://formulae.brew.sh/api/formula.json

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.11
  virtualenv
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.1-58-g82a36d2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 82a36d24fb96129fd0f398dbb5492a16a03244b7
Last commit: 7 hours ago
Core tap JSON: 17 Feb 23:50 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_BAT_THEME: DarkNeon
HOMEBREW_BROWSER: /usr/bin/garcon-url-handler
HOMEBREW_CASK_OPTS: ["--appdir=/dev/null", "--fontdir=/home/colin/.fonts"]
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit skylake
Clang: N/A
Git: 2.39.2 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.74.0 => /usr/bin/curl
Kernel: Linux 5.10.153-20434-g98da1eb2cf9d x86_64 GNU/Linux
OS: Debian GNU/Linux 11 (bullseye) (bullseye)
Host glibc: 2.31
/usr/bin/gcc: 10.2.1
/usr/bin/ruby: 2.7.4
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

Trying to run `brew bundle` when using install-from-API mode.

See https://github.com/Homebrew/homebrew-bundle/issues/1169.

### What happened (include all command output)?

```
...
Error: No available tap homebrew/core.
```

### What did you expect to happen?

Installation to succeed.

The workaround is to disable the lockfile generation (see https://github.com/Homebrew/homebrew-bundle/issues/1169#issuecomment-1435403749).

### Step-by-step reproduction instructions (by running `brew` commands)

Running `brew bundle` eventually looks at `CoreTap.instance.git_head` [here for macOS](https://github.com/Homebrew/homebrew-bundle/blob/bac31a976d146f35c182dec6f6d65f7a917fd8c0/lib/bundle/locker.rb#L144) or [here for Linux](https://github.com/Homebrew/homebrew-bundle/blob/bac31a976d146f35c182dec6f6d65f7a917fd8c0/lib/bundle/locker.rb#L162).

Running `brew irb`:

```shell
==> Interactive Homebrew Shell
Example commands available with: `brew irb --examples`
irb(main):001:0> CoreTap.instance
=> #<CoreTap:0x0000000003ffce60 @user="Homebrew", @repo="core", @name="homebrew/core", @full_name="Homebrew/homebrew-core", @path=#<Pathname:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core>, @alias_table=nil, @alias_reverse_table=nil>
irb(main):002:0> CoreTap.instance.git_head
Traceback (most recent call last):
        3: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
        2: from (irb):2
        1: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:179:in `git_head'
TapUnavailableError (No available tap homebrew/core.)
```

**Comment by colindean** [comment]
It looks like `CoreTap#git_head` needs to learn from `SystemConfig#core_tap_config`: https://github.com/Homebrew/brew/blob/b7613444287405c8a853bae980e1883c6899ec69/Library/Homebrew/system_config.rb#L142-L155

**Comment by Bo98** [comment]
This is somewhat intentional. What should it return if there's no git repo?

**Comment by Bo98** [comment]
API JSON files also can't be "locked" anyway.

**Comment by Bo98** [comment]
Note that we do support `tap_git_head` on individual formulae.

**Comment by colindean** [comment]
> What should it return if there's no git repo?

@issyl0's implemented something in https://github.com/Homebrew/homebrew-bundle/pull/1172 that will return `api` for the version for now. 

I think the end goal is to record the repo version at which the installation was successful. In the absence of the repo, perhaps the timestamp or hash of the formula.json file, or both, would suffice. I think the timestamp would be best if older copies of the formula.json aren't retrievable (and it doesn't make much sense for them to be... it's updated far too often).

**Comment by Bo98** [comment]
> I think the end goal is to record the repo version at which the installation was successful.

How do you handle third party taps (if you do)?

**Comment by colindean** [comment]
> > I think the end goal is to record the repo version at which the installation was successful.
> 
> How do you handle third party taps (if you do)?

Homebrew-bundle does not record info for third-party taps presently. Just the basics of OS env and core tap repo info. See [here](https://github.com/Homebrew/homebrew-bundle/blob/bac31a976d146f35c182dec6f6d65f7a917fd8c0/lib/bundle/locker.rb#L140-L165).

**Comment by Bo98** [comment]
Ah alright. I asked as my thinking was you could create a list of taps and revisions by iterating through the formulae and do:

```rb
formula.tap_git_head # not formula.tap.git_head
formula.tap.full_name
```

This works on both API and Git.

**Comment by MikeMcQuaid** [comment]
This is resolved in Homebrew/homebrew-bundle now.
