### ISSUE TITLE
`brew audit` should not set `HOMEBREW_NO_INSTALL_FROM_API` for non-core formulae

### ISSUE THREAD

**Issue by Bo98** [Homebrew/brew#14701]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.1-59-gae4fb07
ORIGIN: https://github.com/Homebrew/brew
HEAD: ae4fb0749467f2eb00014279c441d803326da929
Last commit: 13 hours ago
Core tap JSON: 18 Feb 03:30 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_PACKAGES_TOKEN: set
HOMEBREW_GITHUB_PACKAGES_USER: Bo98
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-x86_64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.1
```

### What were you trying to do (and why)?

Run `brew audit` on a third-party tap when Homebrew/core is not tapped.

### What happened (include all command output)?

`brew audit` fails because it forces non-API mode:

```
  bo98/test/test1:
    * Can't find dependency '"cmake"'.
```

### What did you expect to happen?

`brew audit` should pass. We are not modifying Homebrew/core so the API has enough information for it to work with third-party taps without needing an expensive clone operation. The latest Ubuntu 22.04 GitHub Actions image no longer ships Homebrew/core.

Removing `audit` from the forced-`HOMEBREW_NO_INSTALL_FROM_API` list fixes the problem and the full test run works successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

`brew audit` on a third-party formula that depends on a Homebrew/core formula while Homebrew/core is untapped.

**Comment by Bo98** [comment]
https://github.com/orgs/Homebrew/discussions/4237 expresses concern about this for `brew test` (though at least it doesn't _break_ there - just act unexpectedly given it can use a stale tap).

**Comment by Bo98** [comment]
https://github.com/orgs/Homebrew/discussions/4237 expresses similar concern for `brew test`, except the issue there wasn't even down to untapped core - a simply stale tap was enough to cause issues.

**Comment by Bo98** [comment]
Not sure if there's really a general solution for this. I can fix the specific audit issue seen via https://github.com/Bo98/brew/commit/ec083231703757790968c8cbb8c988e573d6b727

**Comment by MikeMcQuaid** [comment]
Good write-up, thanks @Bo98.

I think eventually we'll probably want to remove all these `HOMEBREW_NO_INSTALL_FROM_API` auto-sets in favour of figuring out what makes more sense on a command-by-command basis.

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/Homebrew/brew/pull/14793
