### ISSUE TITLE
`brew update` should show "New Formulae" and "New Casks" when update from API

### ISSUE THREAD

**Issue by XuehaiPan** [Homebrew/brew#14706]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

In old tap-repo-based behavior, `brew update` will show newly added formulae and casks by calculating the git differences. Now, the API-based `brew`, does not have a git repo to do that (or does not update the git repo at all even if the git repo is tapped). Currently, `brew` downloads the new JSONs from API and overwrites the content of the existing file in-place. `brew` can only tell the newest state of the formulae without the historical changes. I think we can keep a backup of the old already downloaded JSON file before fetching the new content. Then calculate the differences after a successful `brew update` call.

```console
$ export HOMEBREW_NO_INSTALL_FROM_API=1
$ brew update
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
clipboard                       mariadb@10.10                   openai-whisper                  pmtiles
==> New Casks
mediainfoex                                pulsar                                     simpleclock
==> Outdated Formulae
cmocka                          node                            oh-my-posh                      python@3.11

You have 4 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.
```

### What is the motivation for the feature?

To show newly added packages are available. This was part of the old no-install-from-API feature.

### How will the feature be relevant to at least 90% of Homebrew users?

This affects all Homebrew users because the core tap is always used.

### What alternatives to the feature have been considered?

Do nothing but prompt a hint to suggest users set `HOMEBREW_NO_INSTALL_FROM_API` if they want this.

**Comment by Bo98** [comment]
This could be possible if we diff with the soon-to-be-introduced formula_names.txt and cask_names.txt files.

The slight snag is the API updates more often than when `update-report` runs, which complicates the matter. `brew update` is run once every 24 hours (1 hour for those with `brew developer` enabled), but API auto-update is by default every 7½ minutes.

**Comment by apainintheneck** [comment]
I think we could just compare the current api json to the api json from the previous update-report. We'd have to cache that somewhere in the meantime though.

**Comment by MikeMcQuaid** [comment]
I think this is a "nice to have" and accepting the PR will be heavily based on how complex/large the PR ends up being.

**Comment by jimscard** [comment]
Being able to report what has changed, and what is new are core features for a package manager.

**Comment by MikeMcQuaid** [comment]
@jimscard It's almost as if I was already working on a PR for this, linked before your 👎🏻 and comment: https://github.com/Homebrew/brew/pull/14802

Please read a bit more carefully before you leave messages like this in future, thanks.
