### ISSUE TITLE
brew update --quiet should be quieter

### ISSUE THREAD

**Issue by gabrielwhite** [Homebrew/brew#14707]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Since upgrading to 4.0 `brew update --quiet` has been noisier than I would have expected:

```
brew update --quiet
==> Downloading https://formulae.brew.sh/api/formula.json
#=#=#
```

Propose that the result of the action is shown only:

```
brew update --quiet
Updated https://formulae.brew.sh/api/formula.json
```

### What is the motivation for the feature?

More consistent --quiet behaviour.

### How will the feature be relevant to at least 90% of Homebrew users?

More consistent brew experience.

### What alternatives to the feature have been considered?

Leave as is.

**Comment by MikeMcQuaid** [comment]
Makes sense. Will review a PR for this/
