### ISSUE TITLE
rubocop: disallow protocol in cask url verified stanza

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/brew#14717]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

A rubocop that will check to ensure that no protocol is included in the `verified:` part of the url stanza.

### What is the motivation for the feature?

Avoid PRs like https://github.com/Homebrew/homebrew-cask/pull/141567#pullrequestreview-1305288267 before they're needed.

### How will the feature be relevant to at least 90% of Homebrew users?

Less manual maintainer work. Happier maintainers. Happier users

### What alternatives to the feature have been considered?

Keeping the current manual checks

**Comment by miccal** [comment]
Thanks @SMillerDev. There are currently only 33 Casks that have the protocol in the `verified:` parameter.
