### ISSUE TITLE
Why do I need to re-download the formula.json to execute any command in 4.0.0

### ISSUE THREAD

**Issue by Clloz** [Homebrew/brew#14716]
### `brew doctor` output

```shell
brew doctor                                                                                                                                                                                                   
==> Downloading https://formulae.brew.sh/api/formula.json
#=#=-#  #
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.1-62-ga222a5b
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a222a5bbc83923e4c9c09ed0ff07dfe64cf7d863
Last commit: 11 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c2f709e26eb8cad67c31b2748d86094de942efa9
Core tap last commit: 3 days ago
Core tap branch: master
Core tap JSON: 20 Feb 01:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.xFsqlqB4gM/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

execute some brew command I think don't need to download the formula.json and cask.json

### What happened (include all command output)?

After upgrade to 4.0.0, I need to re-download formula.json even execute brew doctor, brew services list etc. Is it necessary?

### What did you expect to happen?

Don't re-download the formula.json 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
execute any brew command
```

**Comment by MikeMcQuaid** [comment]
See https://brew.sh/2023/02/16/homebrew-4.0.0/. You can opt-out of this behaviour if desired.
