### ISSUE TITLE
Move JSON API generation to `Homebrew/brew`

### ISSUE THREAD

**Issue by Rylan12** [Homebrew/brew#14730]
### Provide a detailed description of the proposed feature

We should move the API generation that happens in `formulae.brew.sh` into this repository. My recommendation would be to add a `generate-api` command that creates the necessary API files for the `formulae.brew.sh` site.

### What is the motivation for the feature?

We can remove the `Rakefile` from `formulae.brew.sh` and simply call `brew generate-api` in a GitHub action to build the site.

We can also check the output against a JSON schema in `Homebrew/brew` CI to easily catch backward-incompatible API changes (CC @SMillerDev, https://github.com/Homebrew/formulae.brew.sh/pull/751)

Not technically blocked by this issue, but we can easily add JWS signing (CC @Bo98, https://github.com/Homebrew/formulae.brew.sh/pull/771)

### How will the feature be relevant to at least 90% of Homebrew users?

Fewer accidental backward-incompatible changes, higher security with API installs, etc.

### What alternatives to the feature have been considered?

Leaving as-is

**Comment by MikeMcQuaid** [comment]
Thanks for opening this @Rylan12!
