### ISSUE TITLE
Shell Completion doc update

### ISSUE THREAD

**Issue by nrlquaker** [Homebrew/brew#14759]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Then you install `bash` and `bash-completion@2` formulas and add this to your `.bash_profile` like [documentation says](https://docs.brew.sh/Shell-Completion#configuring-completions-in-bash)

```bash
if type brew &>/dev/null
then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
    do
      [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
    done
  fi
fi
```

it will only add completions for bash. And will skip all completions in `/opt/homebrew/etc/bash_completion.d`.

if you modify the script to be like this:

```bash
if type brew &>/dev/null
then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  fi
  for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
  do
    [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
  done
fi
```

it will work like expected.

### What is the motivation for the feature?

To be able to use all completion, not just bash.

### How will the feature be relevant to at least 90% of Homebrew users?

Will be relevant for those who use bash.

### What alternatives to the feature have been considered?

none

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by nrlquaker** [comment]
Will create the PR later today. There is some issue with creating PR at the moment.
