### ISSUE TITLE
`brew doctor` output

### ISSUE THREAD

**Issue by RisenL** [Homebrew/brew#14777]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.ustc.edu.cn/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/opt/homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the yqrashawn/goku tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/yqrashawn/homebrew-goku/Formula/goku.rb:16

(base) RisenL@RisenL ~ % git -C "/opt/homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
(base) RisenL@RisenL ~ % brew doctor
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the yqrashawn/goku tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/yqrashawn/homebrew-goku/Formula/goku.rb:16
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ba6d87eed9ce31f42fa2b33a4e6067d9cf17f13f
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2b49524442fe182abb00503f7fd274c2463013b4
Core tap last commit: 8 days ago
Core tap branch: master
Core tap JSON: 23 Feb 03:44 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles/bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.2yal1HGkPN/org.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.36.0 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

brew install a package

### What happened (include all command output)?

Last login: Tue Feb 21 16:54:41 on ttys001
brew%
(base) RisenL@RisenL ~ % brew search youdao
==> Downloading https://formulae.brew.sh/api/cask.json
######################################################################## 100.0%
==> Casks
yoda                                                                         youdaodict                                                                   youdaonote
==> Downloading https://formulae.brew.sh/api/formula.json
######################################################################## 100.0%
(base) RisenL@RisenL ~ % brew install youdaodict
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask-versions).
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the yqrashawn/goku tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/yqrashawn/homebrew-goku/Formula/goku.rb:16

Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/f2c0c21ce347290f317d8fdfc4fc972232b06e6f/Casks/firefox.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/cmd/update-report.rb:588:in `dump'
/opt/homebrew/Library/Homebrew/cmd/update-report.rb:210:in `output_update_report'
/opt/homebrew/Library/Homebrew/cmd/update-report.rb:43:in `update_report'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
==> Downloading https://codown.youdao.com/cidian/download/MacDict.dmg
### What did you expect to happen?

it works

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew search youdao
brew install youdaodict
brew doctor
```

**Comment by Bo98** [comment]
It seems some of your `brew` files might be outdated, despite `brew config` suggesting you are on the latest version. Can perhaps try `brew update-reset`.

**Comment by RisenL** [comment]
thx！it works

**Comment by RisenL** [comment]
plist_options :manual => "gokuw"

**Comment by RisenL** [comment]
when I run 
brew uninstall youdaodict

**Comment by RisenL** [comment]
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the yqrashawn/goku tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/yqrashawn/homebrew-goku/Formula/goku.rb:16

==> Uninstalling Cask youdaodict
==> Backing App '网易有道词典.app' up to '/opt/homebrew/Caskroom/youdaodict/9.1.6,923/网易有道词典.app'
==> Removing App '/Applications/网易有道词典.app'
==> Purging files for version 9.1.6,923 of Cask youdaodict

**Comment by RisenL** [comment]
then i back to check that line 16.
plist_options :manual => "gokuw"

**Comment by carlocab** [comment]
> ```
> Please report this issue to the yqrashawn/goku tap (not Homebrew/brew or Homebrew/homebrew-core)
> ```
