### ISSUE TITLE
install silently fails for non-admin user

### ISSUE THREAD

**Issue by dmopalmer** [Homebrew/brew#1477]
### Bug reports:

When a non-admin user tries to install brew, it fails silently:
```
% /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
%
```

The lines that are supposed to provide feedback and ask that brew be installed as an admin don't work.  I don't know ruby, so I don't know what the fix is, but the lines are in 
https://raw.githubusercontent.com/Homebrew/install/master/install
```
abort <<-EOABORT unless `dsmemberutil checkmembership -U "#{ENV["USER"]}" -G admin`.include? "user is a member"
This script requires the user #{ENV["USER"]} to be an Administrator. If this
sucks for you then you can install Homebrew in your home directory or however
you please; please refer to our homepage. If you still want to use this script
set your user to be an Administrator in System Preferences or `su' to a
non-root user with Administrator privileges.
EOABORT
```
The abort message never appears in the terminal.  I tracked it down by adding `puts lineXXX` into the code to see where it was returning.  

I then verified:
```
% dsmemberutil checkmembership -U "mynamehere" -G admin
user is not a member of the group
```
so the abort 'worked' properly, but doesn't tell the user why.

**Comment by dmopalmer** [comment]
Also, the warning message should point to instructions on how to use homebrew if you aren't reckless enough to have your main account be in the admin group.

It should be worded strongly enough to prevent anyone from making the mistake of using an admin account to install into /usr/local .

(The advice here: install in your home directory. The FAQ says don't do that.  I'm going back to macports.)

**Comment by MikeMcQuaid** [comment]
> I'm going back to macports.

Bye then.
