### ISSUE TITLE
Sort list of outdated packages

### ISSUE THREAD

**Issue by pinguin999** [Homebrew/brew#14787]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

The list of packages is not sorted an that makes it hard to read / find if a package has ben updated.

```bash
==> Upgrading 38 outdated packages:
libheif 1.14.2_1 -> 1.15.1
asdf 0.11.1 -> 0.11.2
cppcheck 2.10 -> 2.10.1
...
```

Better would be

```
==> Upgrading 38 outdated packages:
asdf 0.11.1 -> 0.11.2
cppcheck 2.10 -> 2.10.1
libheif 1.14.2_1 -> 1.15.1
...
```

In `upgrade.rb` there is the formulae_to_install map that only has to be sorted.
`formulae_upgrades = formulae_to_install.SORT.map do |f|`

### What is the motivation for the feature?

Make it easy to find a package in the list of outdated.

### How will the feature be relevant to at least 90% of Homebrew users?

Make it easy to find a package in the list of outdated.

### What alternatives to the feature have been considered?

Use search in the terminal to look for package names.

**Comment by Rylan12** [comment]
@pinguin999 can you open a PR to implement this?

**Comment by pinguin999** [comment]
No.
It's looks not to complicated but I never used Ruby.

**Comment by MikeMcQuaid** [comment]
This ordering is intentionally not alphabetical because it reflects the order that they will be installed in. If none of the formula depend on each other: they will be in alphabetical order.
