### ISSUE TITLE
Brew should not check if current directory exists, results in errors

### ISSUE THREAD

**Issue by ibehnam** [Homebrew/brew#14788]
### `brew doctor` output

```shell
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: The current working directory doesn't exist, cannot proceed.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: The current working directory doesn't exist, cannot proceed.
```

### What were you trying to do (and why)?

Update and Upgrade Brew packages.

### What happened (include all command output)?

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
Error: The current working directory doesn't exist, cannot proceed.
```

### What did you expect to happen?

I expect Brew to avoid checking if the current directory exists, and continue updating and upgrading.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Create a directory in terminal and `cd` into it.
2. Now delete that directory using another terminal/file explorer/Finder/etc.
3. Now go back to the first terminal and try updating Brew. It checks if the current directory exists (which doesn't) and throws an error.
```

**Comment by gromgit** [comment]
There's a similar check in `.../Library/Homebrew/brew.sh`, which `bin/brew` calls, and this one has an explanatory comment:
```sh
# Many Pathname operations use getwd when they shouldn't, and then throw
# odd exceptions. Reduce our support burden by showing a user-friendly error.
if [[ ! -d "$(pwd)" ]]
then
  odie "The current working directory doesn't exist, cannot proceed."
fi
```
As a occasional software developer, I too would be very annoyed if "current working directory just got nuked" turned out to be the reason I'm getting support calls that I can't replicate.

**Comment by MikeMcQuaid** [comment]
This breaks many things, not just Homebrew, so this is a WONTFIX.

Thanks for explanation @gromgit.

**Comment by ibehnam** [comment]
> This breaks many things, not just Homebrew, so this is a WONTFIX.

What does it break though? The only example I can come up with is when the current directory is exactly one of the directories where Brew packages are installed.

Fixing this helps avoid unexplainable errors in the future.

**Comment by MikeMcQuaid** [comment]
> What does it break though?

@ibehnam Many things including many Homebrew tools.

> Fixing this helps avoid unexplainable errors in the future.

This error is explained quite clearly. It tells you what to do. Do that.

"Fixing this" is not really possible.
