### ISSUE TITLE
Fully qualified (heretofore unknown taps) dependencies  make homebrew run into locking problems

### ISSUE THREAD

**Issue by mulle-nat** [Homebrew/brew#1479]
This problem can be easily reproduced with:

```
brew tap mulle-objc/software
brew install mulle-objc-developer
```

This will not work, but complain about another active Homebrew process (there is none, at least not started by me).

My theory what happens is this:

homebrew puts up a lot of locks for the dependencies of `mulle-objc-developer` ahead of time.
Then it will start tapping `codeon-gmbh/software` and starts another homebrew process for that, which will then run afoul of the locks previously created. Clearing all the locks and starting again does not help.

Version: 1.1.0-23-g9889007 ( a fresh clone into `/tmp`)

**Comment by MikeMcQuaid** [comment]
Can you try to create a minimal formula that reproduces this? Thanks!

**Comment by mulle-nat** [comment]
Honestly, probably not. And the reproduction above will go away soon too. Maybe just close it and keep it in the back of your mind :)

**Comment by MikeMcQuaid** [comment]
Ok, thanks.

**Comment by mulle-nat** [comment]
Actually I think I know now what the problem was. I have two taps with formulas of the same name. Depending on the tap you either install "community" or "vendor".
The "community formula mistakenly accessed the "vendor" fork, so dependencies for both forks were added. The locks are not fully qualified and therefore the problem arose.

**Comment by MikeMcQuaid** [comment]
> The locks are not fully qualified and therefore the problem arose.

This is because they both try to install into the same location.

**Comment by mulle-nat** [comment]
Yes the behaviour is correct, I just didnt get it.

**Comment by MikeMcQuaid** [comment]
Cool, glad you figured it out 👍

**Comment by mulle-nat** [comment]
Thanks for the patience with me :)
