### ISSUE TITLE
Unable to view Github Source Page for Casks using `brew info --github`

### ISSUE THREAD

**Issue by hoium** [Homebrew/brew#14796]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.3-116-g041545d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 041545db2c26e7c5009c7e71d262c08a2d0b7900
Last commit: 74 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9ed22ce451975f6a71ecc09670daa8b36364c1d3
Core tap last commit: 25 hours ago
Core tap branch: master
Core tap JSON: 23 Feb 13:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: nano
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_UPDATE_REPORT_ALL_FORMULAE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/opt/git/bin/git
Curl: 7.88.1 => /opt/homebrew/opt/curl/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

View a Cask Github Source page by running `brew info --github slack`  or `brew info --cask --github slack`

Using **_Slack_** as an example it happens with all Casks.

### What happened (include all command output)?

Error: undefined method `relative_path_from' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/cmd/info.rb:257:in `github_info'
/opt/homebrew/Library/Homebrew/cmd/info.rb:114:in `block in info'
/opt/homebrew/Library/Homebrew/cmd/info.rb:114:in `map'
/opt/homebrew/Library/Homebrew/cmd/info.rb:114:in `info'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'

### What did you expect to happen?

Open the GitHub source page for formula and cask in a browser.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Run `brew info --cask --github $CaskName` or `brew info --github $CaskName`
```

**Comment by hoium** [comment]
Thanks, @MikeMcQuaid!!

**Comment by MikeMcQuaid** [comment]
You're welcome @hoium!
