### ISSUE TITLE
Modify the website's homepage adding more Apple Silicon's instructions

### ISSUE THREAD

**Issue by Tudor44** [Homebrew/brew#14810]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Adding a new scriplet in "What Does Homebrew Do?" section, like the macOs Intel's section, relative to how find the installation's folder on installing Homebrew 4.x.

I propose this example:

`
$ cd /opt/homebrew
`
`$ find Cellar
`
`Cellar/wget/1.16.1
`
`Cellar/wget/1.16.1/bin/wget
`
`Cellar/wget/1.16.1/share/man/man1/wget.1
`

### What is the motivation for the feature?

Facilitate the new macOs' transition and keep more update and concise the homepage website.

### How will the feature be relevant to at least 90% of Homebrew users?

As far as I m concerned I think that this feature will improve the onboarding of new users during the installation's phase of Homebrew , using the new machines.

### What alternatives to the feature have been considered?

Improving a bit the FAQ section, but in my opinion is not so immediate then add a section close to Intel's instructions.

**Comment by MikeMcQuaid** [comment]
We're discussing this in https://github.com/Homebrew/brew.sh/issues/933
