### ISSUE TITLE
brew prune deleting empty dir from /usr/local/etc that I created

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/brew#1482]
### Bug reports:

It appears brew prune is searching for and deleting empty directories everywhere in <homebrew_prefix>. 
I thought it only is supposed to clean out Cellar.

For ex. I'm creating an empty dir in apache settings for later Ansible use:

```
mkdir -p /usr/local/etc/apache2/2.4/other
```

Here's what brew prune does:

```
$ brew prune --dry-run
Would remove (empty directory): /usr/local/etc/apache2/2.4/other
```

Suggestion (maybe naive - is there a reason to clean everywhere?)
- brew prune should not clean in areas outside of the Cellar.

**Comment by MikeMcQuaid** [comment]
`brew prune` never cleans the Cellar, it's specifically for cleaning the prefix.
