### ISSUE TITLE
`brew irb` improvements

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/brew#14832]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

There are two features that would be helpful if added to the `brew irb` command.

1. The ability to pass the `--debug` and `--quiet` options to the command.
2. The ability to have some sort of REPL history.

### What is the motivation for the feature?

The idea here is to improve the debugging/development experience by making IRB easier to use.

#### Debug and Quiet Options

`brew irb` already accepts the `--verbose` option so it seems logical that we'd be able to pass the other two flags as well. This changes internal behavior so is helpful when testing things.

##### Verbose

```rb
~ [1]$ brew irb --verbose
==> Interactive Homebrew Shell
Example commands available with: `brew irb --examples`
Switch to inspect mode.
irb(main):001:0> Context.current.verbose?
Context.current.verbose?
=> true
irb(main):002:0> exit
exit
~ $ brew irb
==> Interactive Homebrew Shell
Example commands available with: `brew irb --examples`
irb(main):001:0> Context.current.verbose?
=> false
irb(main):002:0> exit
```

##### Debug

```rb
~ $ brew irb --debug
==> Interactive Homebrew Shell
Example commands available with: `brew irb --examples`
Error: Unrecognized switch: --debug
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/irb/init.rb:210:in `parse_opts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/irb/init.rb:19:in `setup'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/irb.rb:376:in `start'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/irb.rb:68:in `irb'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

##### Quiet

```
~ [1]$ brew irb --quiet
==> Interactive Homebrew Shell
Example commands available with: `brew irb --examples`
Error: Unrecognized switch: --quiet
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/irb/init.rb:210:in `parse_opts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/irb/init.rb:19:in `setup'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/irb.rb:376:in `start'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/irb.rb:68:in `irb'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### IRB History

It'd also be helpful to have a brew specific IRB history that would allow you to easily retry previous commands. The important thing is that it shouldn't affect the normal IRB history that people have on their machines.

### How will the feature be relevant to at least 90% of Homebrew users?

No, this will probably only be relevant to devs working on the Homebrew codebase. At the same time, it might allow us to troubleshoot issues faster which would help everyone.

### What alternatives to the feature have been considered?

Doing nothing.

**Comment by MikeMcQuaid** [comment]
> 1. The ability to pass the `--debug` and `--quiet` options to the command.

Agreed, makes sense to me and should be an easy lift. It may be a pretty noisy start on `--debug` though.

> 2\. The ability to have some sort of REPL history.

I've tried to fix this a bunch of times and failed. Would definitely welcome someone else doing so as I also find this annoying.

**Comment by Bo98** [comment]
> 2\. The ability to have some sort of REPL history.

This works with newer Ruby from when I tested it.

**Comment by apainintheneck** [comment]
> > 2. The ability to have some sort of REPL history.
> 
> This works with newer Ruby from when I tested it.

Good to know but newer Ruby seems so far away right now.

**Comment by Bo98** [comment]
Ruby 3.1 does work already but requires some hoop jumping in terms of copying vendored gems because we haven't agreed an approach to that yet.

I'll test Ruby 3.2 soon.

**Comment by MikeMcQuaid** [comment]
> Ruby 3.1 does work already but requires some hoop jumping in terms of copying vendored gems (but don't copy native gems) because we haven't agreed an approach to that yet.

IMO newer Rubies should just require you to/automatically always run `bundle install` when needed given they will only be for developer.

> There'll be decisions around WWDC time as, for example, Sorbet will need updating to support macOS 14 but newer versions no longer support Ruby 2.6.

I feel like we've already decided: developer commands/workflows using stuff like Sorbet and perhaps RuboCop will need a newer Ruby, typical user workflows will not.
