### ISSUE TITLE
Formulary.factory fails to load from API

### ISSUE THREAD

**Issue by benknoble** [Homebrew/brew#14841]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  tcl-tk
```

N.B. I have uninstalled `tcl-tk` and many other things to get a "clear" doctor run and still had this issue.

(`tcl-tk` complains about `/usr/local/share/man/mann` ownership and conflicts, but that directory has files from 2013 owned by root about sqlite3 whose presence I cannot explain.)

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.4-86-g7c15dce
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7c15dce285900c85476d445dcbc01418e61be37c
Last commit: 64 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5955e6f39d197a69d5971c0ff88116172e48d6a7
Core tap last commit: 68 minutes ago
Core tap branch: master
Core tap JSON: 28 Feb 16:19 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.1MShWRxOHs/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.39.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.7-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
```

### What were you trying to do (and why)?

I have used `Formulary.factory` to help programatically retrieve information about formulas, like `.opt_libexec/"bin"`, particularly in a shell (see, _e.g._, https://github.com/benknoble/Dotfiles/blob/2f78e30bafce81d41018961815154764dbeca9a4/links/bin/compile-vim#L36).

### What happened (include all command output)?

```sh
# any formula should do
# brew ruby -e 'puts Formulary.factory("python@3.11").opt_libexec/"bin"'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api': uninitialized constant Formula (NameError)
	from /usr/local/Homebrew/Library/Homebrew/formulary.rb:616:in `load_from_api'
	from /usr/local/Homebrew/Library/Homebrew/formulary.rb:607:in `klass'
	from /usr/local/Homebrew/Library/Homebrew/formulary.rb:379:in `get_formula'
	from /usr/local/Homebrew/Library/Homebrew/formulary.rb:647:in `factory'
	from -e:1:in `<main>'
```
Note that the `Formula[…].opt_libexec/…` fails with the same top-level error (`uninitialized constant Formula`).

### What did you expect to happen?

This should spit out something like `/usr/local/opt/python@3.11/libexec/` (I think).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew ruby -e 'puts Formulary.factory("<your_favorite_formula>").opt_libexec/"bin"'
```

**Comment by carlocab** [comment]
Note that `Formulary.factory` is [a private API](https://rubydoc.brew.sh/Formulary.html#factory-class_method), so I don't recommend relying on it. That also means it's unlikely we'll be too interested in making it work from the API (unless it manifests in bugs in a public API).

Is there any reason you don't just use `"$(brew --prefix <formula>)/libexec/bin"`? It'll be faster.

**Comment by MikeMcQuaid** [comment]
> Note that `Formulary.factory` is [a private API](https://rubydoc.brew.sh/Formulary.html#factory-class_method), so I don't recommend relying on it.

I'd go further still: don't open issues when private APIs stop working.

**Comment by Bo98** [comment]
This however is public API:

> Note that the `Formula[…].opt_libexec/…` fails with the same top-level error (`uninitialized constant Formula`).

You are probably missing `require "formula"` - it is not required by default for performance reasons.
