### ISSUE TITLE
Ability to install two copies/instances of a formula

### ISSUE THREAD

**Issue by claude-cp** [Homebrew/brew#14840]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Something like "--another-copy" flag:

brew install my-app --another-copy

It would have to identify and keep track of how many copies there are, and probably suffix the installed ones with an increment, or smth of that sort.

### What is the motivation for the feature?

General motivation is that the possibility of having multiple copies of the same app installed already exists on macos. 
It should also be possible from brew. 

The personal motivation is that I want to install another instance of a certain browser I can only find on brew. 

### How will the feature be relevant to at least 90% of Homebrew users?

It would be relevant to 100% of the users, to **have the possibility**.

It's a very weird question to ask, and already positions feature suggestions to be shot down without consideration.

I want to ask, is it even close to 90% for features such as --keep-tmp, or --force-bottle, or --colorpickerdir, or --screen-saverdir, or many others. 
Or more like... close to 10% (**if that**), of people that use homebrew, have ever used those flags ?
Those are also relevant, **for the possibility**. 

### What alternatives to the feature have been considered?

I don't have any, for the specific thing I am trying to achieve, from what I have seen so far, and the googling I've done. 
If I have missed it and it's already possible, please let me know.

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this. Just copy them outside of Homebrew.

**Comment by claude-cp** [comment]
Not that straightforward - it will still point to the binary executable and both copies will end up running the same instance.

**Comment by MikeMcQuaid** [comment]
You'll need to figure that out yourself.
