### ISSUE TITLE
Cannot install/reinstall packages anymore

### ISSUE THREAD

**Issue by Keyruu** [Homebrew/brew#14852]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d0154fa7926e8a7b06e9b074dd45957e820407c
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eec9e20774f5398bd3513952bfca0ba4d73f29bf
Core tap last commit: 12 days ago
Core tap branch: master
Core tap JSON: 01 Mar 13:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I did a `brew reinstall neovim` and `brew install asciiquarium` and both of them were stalling at downloading something from https://ghcr.io.

This behaviour is also happenning for all my colleagues and I also tried this from another network.

### What happened (include all command output)?

This is the output for neovim:
```
brew reinstall neovim
==> Fetching dependencies for neovim: luajit
==> Fetching luajit
==> Downloading https://ghcr.io/v2/homebrew/core/luajit/manifests/2.1.0-beta3-20230221.4
```
This is the output of asciiquarium:
```
brew install asciiquarium
==> Fetching dependencies for asciiquarium: berkeley-db and perl
==> Fetching berkeley-db
==> Downloading https://ghcr.io/v2/homebrew/core/berkeley-db/manifests/18.1.40_1
```

When I try to request the URL in the browser this is the output:
```
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
```

### What did you expect to happen?

I expected the package to be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install neovim
or
brew install asciiquarium
or
any other brew install/reinstall
```

**Comment by joshuataylor** [comment]
Yeah, seems the service is down.

`service unavailable`

Add --debug to see the full info.

Also try curl:
`curl https://ghcr.io/v2/homebrew/core/parallel/manifests/20230222 -H "Authorization: Bearer QQ=="`

**Comment by Keyruu** [comment]
The curl output is that:
```
curl https://ghcr.io/v2/homebrew/core/parallel/manifests/20230222 -H "Authorization: Bearer QQ=="
{"errors":[{"code":"UNAVAILABLE","message":"service unavailable"}]}
```

**Comment by alebcay** [comment]
This is probably caused by https://www.githubstatus.com/incidents/bypf7bqdh4g0 on the GitHub side.

**Comment by Keyruu** [comment]
Since this probably isn't related to Homebrew and rather a Github Issue I'm closing this.
