### ISSUE TITLE
homebrew is no longer accepting formulas at a tap's repository’s root

### ISSUE THREAD

**Issue by chongj615** [Homebrew/brew#14861]
### `brew doctor` output

```shell
Warning: Found Ruby file outside homebrew/jchong tap formula directory.
(/opt/homebrew/Library/Taps/homebrew/homebrew-jchong/Formula):
  /opt/homebrew/Library/Taps/homebrew/homebrew-jchong/test.rb

accordingly to the doc here:
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
Tap formulae follow the same format as the core’s ones, and can be added under either the Formula subdirectory, the HomebrewFormula subdirectory or the repository’s root.

Looks like the latest homebrew 4.0.4 no longer looks at repository's root anymore
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d0154fa7926e8a7b06e9b074dd45957e820407c
Last commit: 3 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a866d1fb067b15d35a3956fef415da3a324d80d8
Core tap last commit: 7 days ago
Core tap branch: master
Core tap JSON: 02 Mar 04:53 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.1
Rosetta 2: false
```

### What were you trying to do (and why)?

I was trying to add my own tap and notice formula at repository's root is no longer accepted but the doc still claim it does.

### What happened (include all command output)?

simply cannot find the formula at repo root

### What did you expect to happen?

brew should able to find formulas at repo root, or doc should be updated

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap homebrew/jchong https://path_to_repo.git
brew doctor
```

**Comment by carlocab** [comment]
I can't reproduce this, and your reproduction instructions are broken. You don't provide a tap that reproduces this failure.

Here's a tap that places a formula in the repository root: https://github.com/teamookla/homebrew-speedtest.git

This works completely fine for me.
```
linuxbrew@codespaces-f53ef7:/workspaces/brew$ brew tap teamookla/speedtest
==> Tapping teamookla/speedtest
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/teamookla/homebrew-speedtest'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 64 (delta 7), reused 13 (delta 5), pack-reused 43
Receiving objects: 100% (64/64), 10.52 KiB | 1.75 MiB/s, done.
Resolving deltas: 100% (18/18), done.
Tapped 1 formula (13 files, 75.3KB).
linuxbrew@codespaces-f53ef7:/workspaces/brew$ brew doctor
Your system is ready to brew.
```

**Comment by gromgit** [comment]
I managed to replicate it:
```sh
$ brew config
HOMEBREW_VERSION: 4.0.4-113-gf3cf599
ORIGIN: https://github.com/Homebrew/brew
HEAD: f3cf59997139ffde323ded74f438ffa7ea5a4441
Last commit: 15 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b8abee171a65550fe897e0e71d9bf64e542ab500
Core tap last commit: 21 hours ago
Core tap branch: cfengine/fix-dir-perms
Core tap JSON: 24 Feb 03:49 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0.0
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: vim
HOMEBREW_EVAL_ALL: set
HOMEBREW_MAKE_JOBS: 6
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_TEMP: /home/linuxbrew/.linuxbrew/tmp
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: hexa-core 64-bit skylake
Clang: N/A
Git: 2.39.2 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.85.0 => /bin/curl
Kernel: Linux 5.19.0-31-generic x86_64 GNU/Linux
OS: Ubuntu 22.10 (kinetic)
Host glibc: 2.36
/usr/bin/gcc: 12.2.0
/usr/bin/ruby: 3.0.4
glibc: N/A
gcc@11: N/A
gcc: 12.2.0
xorg: N/A

$ brew tap-new test/tube
Initialized empty Git repository in /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/test/homebrew-tube/.git/
[main (root-commit) 03041a6] Create test/tube tap
 3 files changed, 90 insertions(+)
 create mode 100644 .github/workflows/publish.yml
 create mode 100644 .github/workflows/tests.yml
 create mode 100644 README.md
==> Created test/tube
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/test/homebrew-tube

When a pull request making changes to a formula (or formulae) becomes green
(all checks passed), then you can publish the built bottles.
To do so, label your PR as `pr-pull` and the workflow will be triggered.

$ cp $(brew --repo homebrew/core)/Formula/go.rb $(brew --repo test/tube)

$ ls -l $(brew --repo test/tube)
total 20
drwxrwxr-x 2 aho aho 4096 Mar  2 13:39 Formula/
drwxrwxr-x 7 aho aho 4096 Mar  2 13:39 .git/
drwxrwxr-x 3 aho aho 4096 Mar  2 13:39 .github/
-rw-rw-r-- 1 aho aho 3210 Mar  2 13:40 go.rb
-rw-rw-r-- 1 aho aho  247 Mar  2 13:39 README.md

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Found Ruby file outside test/tube tap formula directory.
(/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/test/homebrew-tube/Formula):
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/test/homebrew-tube/go.rb
```
And other `brew` commands can't see it either:
```
$ brew info test/tube/go
Error: No available formula with the name "test/tube/go". Did you mean testkube?
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
```

**Comment by chongj615** [comment]
Sorry, the repo I was testing on was internal, but here's how you reproduce it with the repo you used. 
From my testing, seem like if you tap with homebrew/ prefix, then brew will not read repo's root, but if it is anything else, it will.
I can work around by not naming it homebrew/xxx
thanks

$ brew tap homebrew/speedtest https://github.com/teamookla/homebrew-speedtest.git
==> Tapping homebrew/speedtest
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-speedtest'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 64 (delta 7), reused 13 (delta 5), pack-reused 43
Receiving objects: 100% (64/64), 10.52 KiB | 2.63 MiB/s, done.
Resolving deltas: 100% (18/18), done.
Tapped (13 files, 17KB).
nfml16-jchong:Taps jchong$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Found Ruby file outside homebrew/speedtest tap formula directory.
(/opt/homebrew/Library/Taps/homebrew/homebrew-speedtest/Formula):
  /opt/homebrew/Library/Taps/homebrew/homebrew-speedtest/speedtest.rb

**Comment by MikeMcQuaid** [comment]
> From my testing, seem like if you tap with homebrew/ prefix, then brew will not read repo's root, but if it is anything else, it will.

Correct.



> I can work around by not naming it homebrew/xxx

Yeh, you shouldn't use these for non-official taps.
