### ISSUE TITLE
brew install <package name>  : package downloads but brew won't install 

### ISSUE THREAD

**Issue by AKScoin** [Homebrew/brew#14887]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
imac_m1@iMAC-M1s-iMac:~ ⍉ ➜ brew config                                                                                22:20:53
HOMEBREW_VERSION: 4.0.4-196-g180c89e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 180c89e17426d4fb1562ac1b2bbe0c4c6e1a3cec
Last commit: 25 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3e1ff979e76a8e77c607fa9d59ba7ac911f8d666
Core tap last commit: 3 hours ago
Core tap branch: master
Core tap JSON: 05 Mar 06:19 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.3.0.0.1.1677462456
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

Creating custom tap to install software from a websites. 
To keep things in one place to 'brew bundle dump' and share between other computers. 

### What happened (include all command output)?

imac_m1@iMAC-M1s-iMac:~ ➜ brew install codex                                                                           22:12:00
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
==> Fetching akscoin/codex/codex
==> Downloading https://help.codex.online/?action=asset&id=653936cb-52f1-40c6-a4fa-9d0e07334cd4
Already downloaded: /Users/imac_m1/Library/Caches/Homebrew/downloads/99831e13ae2c0c96d1c58d6652a49a660d4f5bc3457ee079f72bc9fe44825112--vault-7.0.1-05901-codexplatform.pkg
==> Installing codex from akscoin/codex
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - codex

### What did you expect to happen?

download and install package from link in codex.rb file (url "https://help.codex.online/?action=asset&id=653936cb-52f1-40c6-a4fa-9d0e07334cd4")

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Steps to creating new Tap:
1. brew tap-new akscoin/codex
2. brew tap akscoin/codex

3. created folder structure and code.rb file in /opt/homebrew/Library/Taps/akscoin/homebrew-codex/Formula

class Codex < Formula
  desc "ArriStuff"
  homepage "https://help.codex.online/"
  url "https://help.codex.online/?action=asset&id=653936cb-52f1-40c6-a4fa-9d0e07334cd4"
  version "7.0.1-05901"
  sha256 "a5e058b2d777be62cb48ee2863e259f143871aaa2b147f3ed6779fe5c5e4c282"

  def install
    bin.install "codex"
    lib.install Dir["lib/*"]
    prefix.install "LICENSE"
    prefix.install "README.md"
  end
  test do
    system "#{bin}/codex", "--version"
  end
end

4. brew audit --strict --new-formula --online codex 
(returns free of errors)

5.  cd "$(brew --repository akscoin/homebrew-codex)" 
git checkout -b main  
git add Formula/codex.rb 
git commit
git push --set-upstream origin main 

6. brew install codex
```

**Comment by carlocab** [comment]
This is a bug in your formula. Your install method calls `bin.install "codex"` but there is no file called `codex` to install in the working directory.

This isn't a bug in `brew`, so we can't help you with this. Sorry!
