### ISSUE TITLE
`brew edit <formula>` open the formula executable in editor

### ISSUE THREAD

**Issue by axiac** [Homebrew/brew#14895]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.4-202-gb1ef41c
ORIGIN: https://github.com/Homebrew/brew
HEAD: b1ef41c25d12795dc93975e337e8644d0974b53c
Last commit: 3 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 833b95fbfdef6b3c79fda599c7a1c5949cad6775
Core tap last commit: 39 minutes ago
Core tap branch: master
Core tap JSON: 05 Mar 18:52 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vi
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.2 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

### What were you trying to do (and why)?

I ran `brew edit vault` to see some details about the formula definition. Homebrew opened the binary executable `vault` in my editor (`vi`).

Context: After I upgraded Homebrew to version 4, a couple of weeks ago, I untapped `homebrew/core`.
I understand that the formula definition is not available locally any more and consequently cannot be edited. But opening the executable in `vi` does not look like a good idea.

### What happened (include all command output)?

`vi` started and opened a binary file, probably `/usr/local/bin/vault`.
When I exited `vi`, the output of `brew` on terminal was:
```
$ brew edit vault
Editing vault
```

I re-tapped `homebrew/core` and tried again. Nothing changed; `brew edit vault` still opens the `vault` executable.

However, for some formulae, `brew edit` works as expected and opens the formula definition file in editor (`vi`).
Example "good" formulae: `awscli`, `php`, `python@3.10`, `nvm`, `bash-completion@2`, `postgresql@14` etc.

```
$ brew edit awscli
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/awscli.rb
```

For other formulae, it opens the binary executable: `vault`, `mysql`, `jq`, `redis` etc.

**Note:** All the formulae listed above are installed. I think that `brew edit` correctly opens the formula definition file for formulae that are not installed (or, at least, I tried about a dozen and could not find any problem.)

I uninstalled `jq` and then `brew edit jq` worked fine. I installed `jq` again and `brew edit jq` reverted to opening the binary executable.

It could be related to the macOS version or Ruby version. I tried on two other MBPs running macOS 12 (Monterey) and I could not reproduce the behaviour.
This is the output on one of them:

```
$ brew edit jq
Editing /usr/local/opt/jq/.brew/jq.rb
```

Please remark that it opens the formula definition cached next to the executable, not the one from the Homebrew installation directory.

The output of `brew config` on the Monterey system (the one that works fine) is below. I did not re-tap `homebrew/core` on it because `brew edit` works fine.
```
HOMEBREW_VERSION: 4.0.4-202-gb1ef41c
ORIGIN: https://github.com/Homebrew/brew
HEAD: b1ef41c25d12795dc93975e337e8644d0974b53c
Last commit: 4 hours ago
Core tap JSON: 05 Mar 19:45 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vi
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 14.0.0 build 1400
Git: 2.39.2 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

### What did you expect to happen?

If the tap `homebrew/core` is available locally, I expect that Homebrew starts my editor (`vi`) to edit the file `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vault.rb`.

If the tap `homebrew/core` is not available locally, it can show an error message and (preferably) directions about how to get the formula definition (`brew tap` etc.)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# No formula definition locally => opens binary executable
brew edit vault

# Re-tap => still opens the executable
brew tap homebrew/core
brew edit vault

# Uninstall formula => opens the formula definition
brew uninstall vault
brew edit vault

# Install again => opens the executable again
brew install vault
brew edit vault
```

**Comment by MikeMcQuaid** [comment]
Thanks for the issue!

> It could be related to the macOS version or Ruby version. I tried on two other MBPs running macOS 12 (Monterey) and I could not reproduce the behaviour.

Makes me think it may be related to the current working directory you are in. Can you reproduce if you do this?

> Step-by-step reproduction instructions

Do these reproduce on all machines?

**Comment by axiac** [comment]
> Makes me think it may be related to the current working directory you are in. Can you reproduce if you do this?

Indeed, the current directory is the problem. On the computer where I detected the issue I ran the `brew edit` commands in `/usr/local/bin`. On the computers where the problem could not be reproduced, the current directory was a subdirectory of my home directory.
The formulae whose definition files are opened correctly have the executable name different than the formula name, i.e. a file with the name I put in the command line does not exist in the current directory.

I think that I can provide reproducible step-by-step instructions.
If a file or directory named `foo` exists in the current directory, the command `brew edit foo` opens the file or directory named `foo` in the editor.

**Comment by apainintheneck** [comment]
Essentially we use the `NamedArgs#to_path` method to evaluate the params. It checks first to see if the arg is a valid path before trying to get the package path by other means.

https://github.com/Homebrew/brew/blob/58f7cb0d4e53db4df85d167b780cece0fef6762c/Library/Homebrew/cli/named_args.rb#L195-L228

I'm not sure I understand why it'd be super useful to be able to load from a path in this command. In fact, looking at the other commands where this same method is used I feel the same way about them too. We already had to deprecate this behavior in the `brew audit` command a little while ago because it lead to unexpected results.

It's used in the following commands:
- `brew audit`
- `brew bump-unversioned-casks`
- `brew cat`
- `brew edit`
- `brew formula`
- `brew style`

Of those `brew style` is probably the only one that really needs it to allow you to run the linter on individual files.

**Comment by apainintheneck** [comment]
We'd probably have to go through the whole deprecation cycle to remove the ability to pass paths to these commands (other than `brew style` of course). In the meantime, we could just evaluate the arg as a path last instead of trying to do that first which would most likely have the desired effect. It also would be less likely to break anyone's workflow with the current state of these commands.

**Comment by MikeMcQuaid** [comment]
Thanks for jogging my memory here @apainintheneck.

Yes, annoyingly this is desired behaviour by some users/commands and not other users/commands. I know this is used heavily for e.g. `brew edit` in the current working directory by people. In this case therefore the workaround is just: don't do this in `HOMEBREW_PREFIX/bin`, sorry!

**Comment by apainintheneck** [comment]
I don't really understand what the use case is here. If you already know the path, you can just open it in your editor with `$EDITOR file_path`. The `brew edit` command essentially does that for you internally already but doesn't expect you to know the path to the package, just the name.
