### ISSUE TITLE
/usr/local/opt/gcc/bin/gcc equivalent missing for Silicon?

### ISSUE THREAD

**Issue by DesWurstes** [Homebrew/brew#14899]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I memorized `/usr/local/opt/X/bin/X` and I substitute for X for almost any program and it works. There's no equivalent path on Silicon that is independent of version numbers

### What is the motivation for the feature?

Hardcoding at various places, feature parity of Silicon with Intel.

### How will the feature be relevant to at least 90% of Homebrew users?

- Want to implement CMake code that checks for a homebrew install process. The path I have given is standard, it's there or not. The alternative is to run brew and ask if to give us the path, but I'd like the simpler alternative to work as well.
- Want to add alias for non-linked packages, but now I can only do `alias pybr=/opt/homebrew/Cellar/python@3.11/3.11.2_1/bin/python3.11` ie including the version number, which works for short time.

### What alternatives to the feature have been considered?

All that's needed is a Silicon equivalent of the path used on Intel.

**Comment by carlocab** [comment]
Try
```sh
$(brew --prefix X)/bin/Y
```
