### ISSUE TITLE
Include `formula_renames.json` and `tap_migrations.json` data in API

### ISSUE THREAD

**Issue by Rylan12** [Homebrew/brew#14897]
### Provide a detailed description of the proposed feature

Formula renames and tap migrations should be respected when installing from the API.

Also, we should add these features to casks as well. That probably deserves its own issue though... 😅

### What is the motivation for the feature?

See https://github.com/Homebrew/brew/pull/14866#issuecomment-1455021576

### How will the feature be relevant to at least 90% of Homebrew users?

These features worked before the API changes. There are 165 formulae currently in homebrew/core's `formula_renames.json` and 32 in `tap_migrations.json`

### What alternatives to the feature have been considered?

Not implementing this

**Comment by MikeMcQuaid** [comment]
> Also, we should add these features to casks as well. That probably deserves its own issue though... 😅

Casks support tap migrations already but not renames. Definitely a different issue 😁

**Comment by Bo98** [comment]
Formula renames should now be implemented.

Tap migrations is a bit trickier. It's not really something that can be inserted into the existing JSONs so might require a third file to be downloaded.

**Comment by MikeMcQuaid** [comment]
> Tap migrations is a bit trickier. It's not really something that can be inserted into the existing JSONs so might require a third file to be downloaded.

@Bo98 stupid question: what are the current two files?

Even if it's a bit dubious/tricky: I think it'd be really good to shoe-horn this into an existing JSON file where possible or e.g. hardcode the values into Homebrew/brew.

**Comment by MikeMcQuaid** [comment]
@Bo98 also: do we need both `oldname` and `oldnames` in the API output? A nice-to-have issue for when we've dealt with all the current API issues might be to try to slim the `formula.json` as much as possible by stripping out the parts we don't use.

**Comment by Bo98** [comment]
> stupid question: what are the current two files?

formula(.jws).json and cask(.jws).json.

> I think it'd be really good to shoe-horn this into an existing JSON file where possible

Problem is the formulae/casks don't exist anymore as they've been migrated so there is no entry.

> do we need both oldname and oldnames in the API output?

Only the latter, the former is just there for backwards compatibility. Removing things from the JSON is always a breaking change.

**Comment by MikeMcQuaid** [comment]
> Only the latter, the former is just there for backwards compatibility. Removing things from the JSON is always a breaking change.

We should change this for the next minor release. I agree that we should avoid removing things from e.g. https://formulae.brew.sh/api/formula/a2ps.json (as it should match `brew info --json` output which we should maintain the API for) but we should consider the contents of `formula.jws.json` to be an implementation detail and aim to shrink it as much as possible.

> Problem is the formulae/casks don't exist anymore as they've been migrated so there is no entry.

Yeh, I'm wondering if we have some sort of stub entry that indicates where to look for the migration.

> If we assume only migrations between Homebrew/core and Homebrew/cask are possible

If those are the only ones we've done: yeh, I think we should consider that and hardcode it. No need to make it more flexible than we previously have used.

**Comment by MikeMcQuaid** [comment]
@reitermarkus @SMillerDev @Bo98 is this now done?

**Comment by Bo98** [comment]
Renames: yes. Tap migrations: no.

**Comment by Bo98** [comment]
In theory, yes. Though awkwardly, because there is no entry for the older migrated package anymore.

What you could do is have Homebrew/cask generation read Homebrew/core's tap_migrations.json and have Homebrew/core generation read Homebrew/cask's tap_migrations.json and then within the new package's JSON list the older packages in a migrations field. Then when you parse the JSON on the `brew` end, you could go through the list of everything from the other tap's JSON and reconstruct the tap_migrations from that.

You can tell from that the desire for a better solution in the long term, but I could probably try give that method a shot for a short-term fix.

**Comment by MikeMcQuaid** [comment]
> You can tell from that the desire for a better solution in the long term, but I could probably try give that method a shot for a short-term fix.

Yeh, I think it may be fine to just leave as-is for now or have something like e.g. we have a very heavily cached/checksummed version of the current `tap_migrations.json` that we only query very periodically.
