### ISSUE TITLE
`brew search --desc` is broken when taps are installed that use a non-"master" primary branch name

### ISSUE THREAD

**Issue by samdmarshall** [Homebrew/brew#1490]
When running `brew search --desc` I am experiencing an error message:
```
Error: No such file or directory - /usr/local/Homebrew/Library/Taps/samdmarshall/homebrew-formulae/.git/refs/heads/master
```
This is a regression from at least September, but likely more recently than that. I checked the command history on my personal computer and found the last time I ran this command with this specific flag was back in early September:
```
# Sat Nov 12 11:52:37 2016
brew search --desc trace
# Sat Sep 10 18:44:37 2016
brew search --desc make
# Thu Sep  8 21:44:07 2016
brew search --desc build
```

Though I believe that I have run it more recently than that on my work laptop (which I won't have access to until next week).

The problem seems to step from the assumption that my tap uses a primary branch with the name `master`. This is not the case. Interestingly, if I leave out the `--desc` flag, I will not get any errors, and will get the expected search results. 

Here is the output when I run the `brew search --desc` query with the `--debug` and `--verbose` flags:
```
brew search --desc foo --debug --verbose
Error: No such file or directory - /usr/local/Homebrew/Library/Taps/samdmarshall/homebrew-formulae/.git/refs/heads/master
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:43:in `mtime'
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:43:in `block in cache_fresh?'
/usr/local/Homebrew/Library/Homebrew/tap.rb:475:in `block (2 levels) in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:474:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:474:in `block in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:473:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:473:in `each'
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:41:in `cache_fresh?'
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:52:in `ensure_cache'
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:100:in `search'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:46:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>
```

**Comment by MikeMcQuaid** [comment]
As noted by the backtrace the line with the issue is https://github.com/Homebrew/brew/blob/master/Library/Homebrew/descriptions.rb#L43.

I'd like to delicately suggest that you consider setting your default branch back to `master` on your tap. Based on previously issues you may be the only person who hits this edge-case. I've spent about 15m trying to find a good solution but am unable to find one I'm happy with. Alternatively if you wish to not change the branch if you could submit pull-requests rather than issues in future that'd probably be better. Sorry and thanks!

**Comment by samdmarshall** [comment]
Well that is unfortunate to hear. I open issues because I am not versed in Ruby enough to make PRs on these issues myself. If you think the best course of action would be to change the tap's primary branch to master, and if I can do without without breaking existing installs of the tap; then I think that might be the best solution here. I originally ran into issues with this last year which spurred [this change](https://github.com/Homebrew/legacy-homebrew/commit/a71d4a9bd25faaeaadbf4b17d8a978ac779105db) to be made, and after that I saw very few issues with this. I don't want to be a pest about this but since there doesn't seem to be any definitive ruling on this besides convenience in the code being written, then maybe a formal stance should be made in this regard. I checked the [existing documentation](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) which makes no mention on requirements on primary branch name.

**Comment by MikeMcQuaid** [comment]
@samdmarshall You may be well enough versed in Git/GitHub to suggest what's best to use if `.git/refs/heads/master` doesn't exist without requiring a e.g. network connection.

You're definitely not being a pest and I begrudge closing this out but it's mostly because we're pretty understaffed here currently so I'm needing to be selective on where time is spent.

> If you think the best course of action would be to change the tap's primary branch to master, and if I can do without without breaking existing installs of the tap

I think that would be. To verify it won't break things (I don't think it would) you could create a repo with just a `README` through GitHub's UI, set the default branch to `develop`, `brew tap` is, change that branch to `master`, `brew update --force` and see if it doesn't 💥. If it does 💥 let me know here and I'll try harder to get you a good solution. Thanks and sorry again.

**Comment by samdmarshall** [comment]
I understand. I missed it on the first pass but now that you mention it I am noticing that the commit I linked to does make networked git calls. That would be suitable for a networked request, such as `brew update` but not for a search against local formulae. I trust the judgements of you and the other maintainers as to what would be feasible for you to accomplish, and if that means changing my workflow then that is ok by me. I don't mind contributing to the documentation to outline the expectations if I can be told with some degree of certainty as to what those expectation are to help avoid future issues like this.

**Comment by samdmarshall** [comment]
Ok I've tried to migrate my formula repo over to using `master` instead of `develop` and while the repo is updated, telling brew to update doesn't seem to change the branches it is pointed at. This might require some more work.

Also I am noticing that sometimes I can perform the `brew search --desc` command that I originally filed this issue about and other times it fails out in the place reported. This has been noticed prior to performing any change with my formula repo.

**Comment by samdmarshall** [comment]
@MikeMcQuaid hey, just wanted to ping you again about this to make sure you saw my last comment update to this problem. If there is anything I can do or more info I can provide to assist with this I am more than happy to.

**Comment by MikeMcQuaid** [comment]
@samdmarshall I saw your reply, thanks. Honestly got so much else going on at the moment (one of our CI nodes died) that this is fairly low priority unless we get another few reports but I appreciate your regular, helpful explanations of this stuff and for checking in. Thanks for being a great open-source citizen ❤️

**Comment by samdmarshall** [comment]
No problem, I understand. Thank you for the update.
