### ISSUE TITLE
Should all commands always update from API?

### ISSUE THREAD

**Issue by istomyang** [Homebrew/brew#14901]
If there is something wrong with my proxy server, it will wait a long time.

<img width="572" alt="Screenshot 2023-03-06 at 15 15 38" src="https://user-images.githubusercontent.com/67993732/223043072-417d67fa-457a-4a9f-8fa7-35dfa63a38db.png">

**Comment by MikeMcQuaid** [comment]
Renamed to "Should all commands always update from API?"

My take on thinking about this more is: "other than commands that formerly did `brew update` beforehand: no, probably not if we have an existing cache".

Would welcome any other @Homebrew/maintainers thoughts for or against here.

**Comment by istomyang** [comment]
> Renamed to "Should all commands always update from API?"
> 
> My take on thinking about this more is: "other than commands that formerly did `brew update` beforehand: no, probably not if we have an existing cache".
> 
> Would welcome any other @Homebrew/maintainers thoughts for or against here.

Thank you for your correction.

I noticed that I used a Chinese mirror, is it possible that this is because our cache validation mechanism keeps returning false for files downloaded from such mirrors?

**Comment by Rylan12** [comment]
@MikeMcQuaid not sure I totally understand the question here. Is the question whether to make `Homebrew::API` publicly documented to allow external commands to trigger their own updates?

**Comment by apainintheneck** [comment]
I completely agree with defaulting to the cached file for non-autoupdate commands. Should be simple enough to figure out too since we already have all the autoupdate logic already, right?

**Comment by apainintheneck** [comment]
Though there might be some other commands internally which now rely on the new behavior of fetching more frequently.

**Comment by MikeMcQuaid** [comment]
> I noticed that I used a Chinese mirror, is it possible that this is because our cache validation mechanism keeps returning false for files downloaded from such mirrors?

@istomyang Try to play around with `HOMEBREW_API_AUTO_UPDATE_SECS` and see if it still updates every time.

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid not sure I totally understand the question here. Is the question whether to make `Homebrew::API` publicly documented to allow external commands to trigger their own updates?

@Rylan12 No. My thinking was whether we only automatically update if we have no existing cached data for `AUTO_UPDATE_COMMANDS`: https://github.com/Homebrew/brew/blob/9d5b0762fb40163d8b760c4df131b16745a287d2/Library/Homebrew/brew.sh#L272-L279

> Should be simple enough to figure out too since we already have all the autoupdate logic already, right?

@apainintheneck Yeh, I think so. It's probably just a matter of setting something like `export HOMEBREW_IN_AN_AUTO_UPDATE_COMMAND=1` in `brew.sh` and then using `ENV["HOMEBREW_IN_AN_AUTO_UPDATE_COMMAND"].present?` to adjust the auto-update logic accordingly.

> Though there might be some other commands internally which now rely on the new behavior of fetching more frequently.

IMO these should be fine; if they work from a cache, they'll work with this. The only additional one that we should probably add here is `brew outdated`. It's always been a little confusing that `brew outdated; brew upgrade` outdated can say it's not going to update anything and then upgrade auto-updates and does so...

**Comment by MikeMcQuaid** [comment]
> My thinking was whether we only automatically update if we have no existing cached data for `AUTO_UPDATE_COMMANDS`:
> Yeh, I think so. It's probably just a matter of setting something like `export HOMEBREW_IN_AN_AUTO_UPDATE_COMMAND=1` in `brew.sh` and then using `ENV["HOMEBREW_IN_AN_AUTO_UPDATE_COMMAND"].present?` to adjust the auto-update logic accordingly.

Opened https://github.com/Homebrew/brew/pull/14943 for this

> The only additional one that we should probably add here is `brew outdated`. It's always been a little confusing that `brew outdated; brew upgrade` outdated can say it's not going to update anything and then upgrade auto-updates and does so...

Opened https://github.com/Homebrew/brew/pull/14942 for this
