### ISSUE TITLE
How do I install/link an old version of a package without it triggering warnings from `brew doctor`?

### ISSUE THREAD

**Issue by kenbod** [Homebrew/brew#1491]
### Bug reports:

**Summary:** I need to keep an old version of Scala installed/linked on my system. How can I do this without it triggering warnings from `brew doctor`?

**Details:**

I need to ignore new versions of Scala and keep version 2.10.X installed/linked on my system. Yesterday, I accidentally deleted version 2.10.X on my system and had 2.12.X installed in its place. Unfortunately, in this situation, there is no easy way to "go back".

Instead, after searching around the web, I discovered that I could get 2.10.5 installed by following these commands:

```
brew install homebrew/versions/scala210
brew unlink scala
brew link scala210 --force
```

That solved my problem but now when I run `brew doctor` I receive the following warnings:

```
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  scala

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  homebrew/versions/scala210
```

What I would like to be able to do is to tell homebrew that I want 2.10.5 installed on my machine even though 2.12.X is available and have this configuration be considered <q>normal</q> such that it doesn't trigger warnings when I run `brew doctor`.

Is there anyway to achieve this?

**Comment by MikeMcQuaid** [comment]
Don't use `brew link --force` if you want to avoid `brew doctor` warnings. Instead adjust your PATH accordingly so you don't need to link it. Alternatively, ignore `brew doctor`. Another alternatively, please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!
