### ISSUE TITLE
API install does not replace `Dir.home` when pouring bottles

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/brew#14925]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  php-uuid@8.1

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  jsonschema
  php@7.4
  php@8.0

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php-raphf@8.1

Warning: You have uncommitted modifications to Homebrew/homebrew-cask.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-cask && git stash -u && git clean -d -f

Uncommitted files:
   M Casks/virtualbox.rb
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.5-103-gbde256a
ORIGIN: https://github.com/Homebrew/brew
HEAD: bde256a325f60463f14c4d19cd40e0be99befa53
Last commit: 7 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a3a6d385a270d02e75c180949805b12c87331612
Core tap last commit: 7 hours ago
Core tap branch: master
Core tap JSON: 08 Mar 13:31 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2 => /Applications/Xcode_14.2.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

Install any formula that uses a working_dir of `Dir.home` in the service block.

### What happened (include all command output)?

The poured services define a home directory that only applies to the CI runners
```ini
WorkingDirectory=/Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/home
```
```plist
        <key>WorkingDirectory</key>
        <string>/Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/home</string>
```

### What did you expect to happen?

For that value to be replaced by the user's home directory

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gitlab-runner
cat $(brew --prefix gitlab-runner)/homebrew.mxcl.gitlab-runner.plist
cat $(brew --prefix gitlab-runner)/homebrew.gitlab-runner.service
```

**Comment by apainintheneck** [comment]
I talked with @carlocab and @Bo98 about this in #14952 and we think that the best way to solve this is to add the service block info to the formula JSON representation that we return from the API. This will require the least possible changes to `brew services` which makes the most sense. It will also fix a few other install from API related issues that it's having right now.

One important point though is that we will still need to substitute the HOME directory path when building the API JSON and then loading from it.

**Comment by SMillerDev** [comment]
Does that also work for projects that ship their own plist/service file?

**Comment by apainintheneck** [comment]
> Does that also work for projects that ship their own plist/service file?

Wait, there are bottles that ship their own plist/service files to the brew file paths but that don't have service blocks in the formula source? And then they control them with `brew services`?

It seemed like that wasn't 100% supported right now when I looked earlier today and that's part of the reason I closed the above PR.

The idea I had was to remove generated service files from bottles assuming we'd rather include that info in the API JSON and generate them locally.

**Comment by SMillerDev** [comment]
Yeah, if you check for "plist" in core you will find some that do. And generally it would fit our approach of "using upstreams defaults" to do this.

**Comment by Bo98** [comment]
`brew services` doesn't properly support that but we could add DSL for that, e.g.

```
service do
  provided true
end
```

This will give the option to add `require_root` e.g. like we could before with `plist_options`.

**Comment by apainintheneck** [comment]
I was only able to find one instance of a service file being generated by hand in a formula and placed at one of the brew service file paths.

```
/u/l/H/L/T/h/homebrew-core (master|✔) $ git grep -A 4 -E 'homebrew\..*\.(plist|service)'
Formula/isc-dhcp.rb:    (prefix/"homebrew.mxcl.dhcpd6.plist").write plist_dhcpd6
Formula/isc-dhcp.rb:    (prefix/"homebrew.mxcl.dhcpd6.plist").chmod 0644
```

The `ice cream` formula does something similar but it doesn't end up at the expected file path so it wouldn't get covered by this.

Are there any other ones that I'm missing here?

All of the other ones used the `service do` block or the `def plist` method which are both supported when installing service files. The `def plist` method is not fully supported by `brew services` right now since it doesn't have a service block but I think it's a sort of legacy option. Anyway it's only used in 5 formulas.

```
/u/l/H/L/T/h/homebrew-core (master|✔) [1]$ git grep -E 'def plist$'
Formula/cassandra@2.1.rb:  def plist
Formula/cassandra@2.2.rb:  def plist
Formula/elasticsearch.rb:  def plist
Formula/elasticsearch@6.rb:  def plist
Formula/kibana.rb:  def plist
```

Either way we should probably just leave the service files in the bottle to get overwritten which is the current behavior.

**Comment by SMillerDev** [comment]
I think there's also some that override `plist_name`.

**Comment by MikeMcQuaid** [comment]
> I talked with @carlocab and @Bo98 about this in #14952 and we think that the best way to solve this is to add the service block info to the formula JSON representation that we return from the API.

Could we use the `post_install` approach and use the formula from the bottle here instead?

> Either way we should probably just leave the service files in the bottle to get overwritten which is the current behavior.

Agreed.

**Comment by Bo98** [comment]
> Could we use the `post_install` approach and use the formula from the bottle here instead?

We could but there's one notable difference to note here: the formula file for post_install only needs to be valid at install time while the formula file for a service needs to be valid ideally forever (or at least the lifetime of that package version).

Notably: if we deprecate something and change a postinstall then we can just rebottle. If we deprecate something and change the service block we would need to revision bump and hope people haven't done `brew pin`, and provide different deprecation messaging (it's currently aimed at maintainers).

**Comment by Bo98** [comment]
We could even plant this information in the bottle manifest, though maybe that's complicating things too much.

**Comment by MikeMcQuaid** [comment]
Cool, good explanation, thanks @Bo98, agreed given that the API makes the most sense here then.

**Comment by MikeMcQuaid** [comment]
> Alternative option: we could also require all services to run in a working directory that brew controls.

I think this is really reasonable and probably makes this all a lot easier, right?

**Comment by apainintheneck** [comment]
> Alternative option: we could also require all services to run in a working directory that brew controls.

Even if we did that we'd still have to substitute the home directory in the run command which shows up twice in `homebrew/core`. It also wouldn't solve the issues with `brew services` expecting a service block and not functioning as expected without it.

**Comment by carlocab** [comment]
This might already be covered in the `brew services` problems that @Bo98 outlined above, but just in case it isn't, `caveats` for `service` blocks are currently not shown correctly when you don't have `HOMEBREW_NO_INSTALL_FROM_API` set. For example:
```diff
❯ diff -u <(HOMEBREW_NO_INSTALL_FROM_API= brew info socket_vmnet) <(HOMEBREW_NO_INSTALL_FROM_API=1 brew info socket_vmnet)
--- /dev/fd/13  2023-03-17 15:39:33.183107616 +0800
+++ /dev/fd/14  2023-03-17 15:39:33.183970272 +0800
@@ -16,6 +16,11 @@
 socket_vmnet is keg-only, which means it was not symlinked into /usr/local,
 because /usr/local/bin is often writable by a non-admin user.

+
+To restart socket_vmnet after an upgrade:
+  sudo brew services restart socket_vmnet
+Or, if you don't want/need a background service you can just run:
+  /usr/local/opt/socket_vmnet/bin/socket_vmnet --vmnet-gateway=192.168.105.1 /usr/local/var/run/socket_vmnet
 ==> Analytics
 install: 116 (30 days), 664 (90 days), 773 (365 days)
 install-on-request: 116 (30 days), 662 (90 days), 771 (365 days)
```

**Comment by apainintheneck** [comment]
@carlocab It looks like caveats are hardcoded when loaded from the API right now and that's what's probably causing the problem. Probably worth making a separate issue about that.

https://github.com/Homebrew/brew/blob/5550aa215e172f492cbcc137d64e79c57cb784c9/Library/Homebrew/formulary.rb#L266-L270

**Comment by Rylan12** [comment]
This is probably something we should look into addressing globally instead of case-by-case as issues come up. For casks, we already have a degree of this with `HOMEBREW_PREFIX` and `appdir`. Probably worth looking into adding that for formulae as well.

**Comment by apainintheneck** [comment]
@Rylan12 I'm not sure we need such a generic solution for formulae. Right now this seems to only be needed for services and caveats. It's an interesting idea though.

**Comment by MikeMcQuaid** [comment]
> This is probably something we should look into addressing globally instead of case-by-case as issues come up. For casks, we already have a degree of this with `HOMEBREW_PREFIX` and `appdir`. Probably worth looking into adding that for formulae as well.

I agree, personally. Given this only applies to JSON generation: it feels a bit weird to have to do this in multiple sides that are going to end up in the same string in the end and can all be replaced there en-masse.
