### ISSUE TITLE
brew update --auto-update -> shows oudated "New Formulae/Casks" info

### ISSUE THREAD

**Issue by muescha** [Homebrew/brew#14923]
### `brew doctor` output

```shell
brew doctor
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#=#=#
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker

Warning: You have uncommitted modifications to Homebrew/brew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew && git stash -u && git clean -d -f

Uncommitted files:
  ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/public_suffix-4.0.6/data/list.txt
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 4.0.5-115-gb6b3066
ORIGIN: https://github.com/Homebrew/brew
HEAD: b6b30667f0ec19692d1ec01c5a553cac31eb272f
Last commit: 19 minutes ago
Core tap JSON: 08 Mar 13:17 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

I look at the info about new formulae and new casks.

### What happened (include all command output)?

it shows old info (see command output below)

### What did you expect to happen?

up-to-date info should appear

- the new formula aztfexport
- the new cask tastytrade

### Step-by-step reproduction instructions (by running `brew` commands)

i run this install command - but important is the parts `New Formulae` and `New Casks`:

```shell
brew install whatsapp-beta
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from 4.0.4 (4a41f01e8) to 4.0.5 (e5c0fb4ca).
Updated 9 taps (robotsandpencils/made, homebrew/cask-versions, homebrew/bundle, homebrew/cask-fonts, homebrew/services, homebrew/cask-drivers, peripheryapp/periphery, homebrew/core, and homebrew/cask).
==> New Formulae
aztfy
==> New Casks
font-rubik-pixels                                                            tastyworks

You have 3 outdated formulae and 3 outdated casks installed.
You can upgrade them with brew upgrade
or list them with brew outdated.


The 4.0.5 changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/4.0.5
Error: Cask 'whatsapp-beta' conflicts with 'whatsapp'.
```

here this 2 items are not available anymore because they are renamed:

`aztfy` is renamed to `aztfexport` but is not shown as renamed or deprecated ( see [#124971](https://github.com/Homebrew/homebrew-core/pull/124971/files) ) 

```shell
brew home aztfy
Error: No available formula with the name "aztfy". Did you mean atf?
```

`tastyworks` is also renamed - but the show up here:
(see [#142240](https://github.com/Homebrew/homebrew-cask/pull/142240/files))

```shell
brew search tastyworks
==> Casks
tastytrade
```

**Comment by MikeMcQuaid** [comment]
> here this 2 items are not available anymore because they are renamed:

Yeh, we've got an open bug for this one: https://github.com/Homebrew/brew/issues/14897
