### ISSUE TITLE
brew search --desc throws an error

### ISSUE THREAD

**Issue by auntchilada** [Homebrew/brew#14938]
### `brew doctor` output

```shell
$ brew doctor

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config

HOMEBREW_VERSION: 4.0.5-156-gcb5e829
ORIGIN: https://github.com/Homebrew/brew
HEAD: cb5e8298a2a9acad095fa438dde2466bc9b6ccfb
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9565a5ae830bfdb6bfc81abcc32ec2a439ef6349
Core tap last commit: 4 weeks ago
Core tap branch: master
Core tap JSON: 09 Mar 18:36 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_BAT_THEME: ansi
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 15
HOMEBREW_DISPLAY: :0.0
HOMEBREW_EDITOR: /Users/bduart/bin/beditor.sh
HOMEBREW_EVAL_ALL: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_VERBOSE_USING_DOTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.1

$ sw_vers

ProductName:    macOS
ProductVersion: 13.2
BuildVersion:   22D49
```

### What were you trying to do (and why)?

get all formulae/casks listing for /regex/ with descriptions

` $ brew search --desc /./
`

### What happened (include all command output)?

 $ brew search --desc /./

==> Formulae
Error: private method \'select\' called for #<DescriptionCacheStore:0x00007fdb64bb86f8>
Do not report this issue until you\'ve run \'brew update\' and tried again.
/usr/local/Homebrew/Library/Homebrew/search.rb:187:in \'search_regex\'
/usr/local/Homebrew/Library/Homebrew/search.rb:176:in \'search\'
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:20:in \'search\'
/usr/local/Homebrew/Library/Homebrew/search.rb:31:in \'block in search_descriptions\'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:26:in \'use\'
/usr/local/Homebrew/Library/Homebrew/search.rb:29:in \'search_descriptions\'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:83:in \'search\'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in \'\<main\>\'

### What did you expect to happen?

 $ brew search --desc /./

==> Formulae
a2ps: Any-to-PostScript filter
a52dec: Library for decoding ATSC A/52 streams (AKA 'AC-3')
aacgain: AAC-supporting version of mp3gain
...
zx: Tool for writing better scripts
zxcc: CP/M 2/3 emulator for cross-compiling and CP/M tools under UNIX
zydis: Fast and lightweight x86/x86_64 disassembler library
zyre: Local Area Clustering for Peer-to-Peer Applications
zzuf: Transparent application input fuzzer
zzz: Command-line tool to put Macs to sleep

==> Casks

0-ad
010-editor
115browser
1clipboard
1password
1password-beta
1password-cli

etc...

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew search --desc /cows/

==> Formulae
Error: private method `select' called for #<DescriptionCacheStore:0x00007f807c9808d8>
Do not report this issue until you've run `brew update` and tried again.
/usr/local/Homebrew/Library/Homebrew/search.rb:187:in `search_regex'
/usr/local/Homebrew/Library/Homebrew/search.rb:176:in `search'
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:20:in `search'
/usr/local/Homebrew/Library/Homebrew/search.rb:31:in `block in search_descriptions'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:26:in `use'
/usr/local/Homebrew/Library/Homebrew/search.rb:29:in `search_descriptions'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:83:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'


# ----------------------------------------

[expected]

 $ brew search --desc /cows/

==> Formulae
cowsay: Configurable talking characters in ASCII art
```

**Comment by issyl0** [comment]
Looks related to #14916, @dduugg?

**Comment by apainintheneck** [comment]
I'm able to reproduce this locally when using `--eval-all`.

```sh
~ [1]$ brew search --desc --eval-all /cows/
==> Formulae
Error: private method `select' called for #<DescriptionCacheStore:0x00007f82a38e8a78>
/usr/local/Homebrew/Library/Homebrew/search.rb:187:in `search_regex'
/usr/local/Homebrew/Library/Homebrew/search.rb:176:in `search'
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:20:in `search'
/usr/local/Homebrew/Library/Homebrew/search.rb:31:in `block in search_descriptions'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:26:in `use'
/usr/local/Homebrew/Library/Homebrew/search.rb:29:in `search_descriptions'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:83:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

It seems like the code passes in an instance of `DescriptionCacheStore` but expects an `Array`.

**Comment by dduugg** [comment]
@issyl0 thanks for the cc, should be fixed by https://github.com/Homebrew/brew/pull/14941

**Comment by mar10p** [comment]
Confirmed that this is working after running `brew update`. Thanks for the quick fix @dduugg !

**Comment by auntchilada** [comment]
huzzah! thank you, kindly, all.
