### ISSUE TITLE
Nice and ThrottleInterval equivalence in brew services

### ISSUE THREAD

**Issue by jorpilo** [Homebrew/brew#14931]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

As plist has been replaced by service, I would like to know if there is any equivalent to the TrottleInterval and Nice plist keys.
I was not able to find anything in the [formula cookbook](https://docs.brew.sh/Formula-Cookbook) or in [ruby service docs](https://rubydoc.brew.sh/Homebrew/Service.html)

```
      <key>ThrottleInterval</key>
      <integer>30</integer>
```
and
```
      <key>Nice</key>
      <integer>-20</integer>
```

### What is the motivation for the feature?

Be able to set priority for brew services and limit if needed. Matching the actual plist features.

### How will the feature be relevant to at least 90% of Homebrew users?

This parameter can be set in any of the brew services if needed. The services onwers might want to lower priority to some of the homebrew services background tasks.

### What alternatives to the feature have been considered?

Creating the plist manually as previously done before the deprecation but then deprecation warnings keep showing whenever running brew commands.

**Comment by carlocab** [comment]
See `man launchd.plist`.

```
     ThrottleInterval <integer>
     This key lets one override the default throttling policy imposed on jobs
     by launchd.  The value is in seconds, and by default, jobs will not be
     spawned more than once every 10 seconds.  The principle behind this is
     that jobs should linger around just in case they are needed again in the
     near future. This not only reduces the latency of responses, but it
     encourages developers to amortize the cost of program invocation.
```
```
     Nice <integer>
     This optional key specifies what nice(3) value should be applied to the
     daemon.
```

**Comment by carlocab** [comment]
Sorry, I misread the issue. I don't think this is implemented in the service DSL, but we'll review a pull request that does this.

**Comment by jorpilo** [comment]
Here is a PR defining Nice
https://github.com/Homebrew/brew/pull/14936

First time contributing so please let me know what I can improve

**Comment by rami3l** [comment]
Note: I'm just coming by to see what might be the best way to integrate launchd for my own service. It seems that `skhd` and `yabai` have recently moved away from `brew services` ((https://github.com/koekeishiya/yabai/issues/1619#issuecomment-1507686308)), probably due to this issue...

**Comment by MikeMcQuaid** [comment]
This has stalled out. We'll still consider PRs but I don't think having this issue remain open is going to get more eyes here.
