### ISSUE TITLE
Misleading message on audit failure

### ISSUE THREAD

**Issue by Moulick** [Homebrew/brew#14949]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.0.6-6-g921ad96
ORIGIN: https://github.com/Homebrew/brew
HEAD: 921ad96b53fef56102049e32cb05fb55ae0b6208
Last commit: 5 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 51fc1b77b5e8f6ed1e3b628e3d4577084f2539a4
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Running `brew audit --new-cask homebrew/cask/mist` generates a `Signature verification failed` error. The error asks to contact the upstream developer to ask them to notarize the package. The package is actually already correctly notarized.

It seems that `stapler` does not support checking signatures when using the minimal command line installation of Xcode and instead requires the full Xcode.
While the failure is correct, I do not know if it's possible to remove the dependency on the full Xcode.app for signature verification. Else maybe the error handling can be improved to advise installing the full Xcode rather than asking to contact the upstream developers.

### What happened (include all command output)?

❯ brew audit --new-cask homebrew/cask/mist
```
==> Downloading https://github.com/ninxsoft/Mist/releases/download/v0.5/Mist.0.5.pkg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/509050256/9f520b36-ce85-44ac-aa9d-d28bc3241726?X-Amz
######################################################################## 100.0%
==> Downloading https://github.com/ninxsoft/Mist/releases/download/v0.5/Mist.0.5.pkg
Already downloaded: /Users/moulick.aggarwal/Library/Caches/Homebrew/downloads/b1ba8478b0e9546f6666dce9c6880e86724d8d68f01a18a29e7f086b35947dd4--Mist.0.5.pkg
audit for mist: failed
 - Signature verification failed:
xcode-select: error: tool 'stapler' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

macOS on ARM requires applications to be signed.
Please contact the upstream developer to let them know they should notarize their package.
Error: 1 problem in 1 cask detected
```

### What did you expect to happen?

1. The error should say install the full Xcode.app rather than contact the upstream developer
2. Use any alternate method for checking the signature that does not require full Xcode?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew audit --new-cask homebrew/cask/mist
```

**Comment by carlocab** [comment]
CC @SMillerDev

**Comment by MikeMcQuaid** [comment]
@SMillerDev any thoughts here?

**Comment by SMillerDev** [comment]
Yeah, we should probably check for an XCode install too before running this check. It's on my list but since it's a very niche audit error it's not very high on that list.

**Comment by issyl0** [comment]
As of https://github.com/Homebrew/brew/pull/15219 we use `spctl`, not `stapler`, for signing checks, which doesn't require the full XCode. So this shouldn't occur anymore.
