### ISSUE TITLE
M1 Native Support Planned?

### ISSUE THREAD

**Issue by DaniSpringer** [Homebrew/brew#14953]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Run Brew on M1 Macs without enabling Rosetta

### What is the motivation for the feature?

Lots of bugs and errors have occurred when using Brew, ever since switching to an M1 Mac.

### How will the feature be relevant to at least 90% of Homebrew users?

:/

### What alternatives to the feature have been considered?

?

**Comment by carlocab** [comment]
Homebrew has worked on M1 macOS without Rosetta since early 2021. https://brew.sh/2021/02/05/homebrew-3.0.0/

**Comment by DaniSpringer** [comment]
@carlocab ever since using brew on an M1 over Intel, I get warnings and errors about unsupported stuff, wrong paths, etc,  non stop. Doesn't seem like it is supported... But thanks.

**Comment by carlocab** [comment]
That's not my experience, or the experience of very many other users on M1 macOS, so this is likely a problem with your own configuration/setup.

If you need help resolving this you can try the [discussions page](https://github.com/orgs/Homebrew/discussions). Make sure to include the output of `brew config` and `brew doctor`.

**Comment by DaniSpringer** [comment]
@carlocab I completely reset my M1 Mac to new just now, so not much configs.
The discussion page essentially prevented me from asking, by saying that I have to check a checkbox stating that `brew doctor` says "all good".

**Comment by gromgit** [comment]
What's the output of `brew config`?

**Comment by DaniSpringer** [comment]
> What's the output of `brew config`?

```
HOMEBREW_VERSION: 4.0.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0c1031f2fd71016f0f5df699caaed384487bfb16
Last commit: 4 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 17eb27263f58d670023fbff983414164ead54a18
Core tap last commit: 18 hours ago
Core tap branch: master
Core tap JSON: 14 Mar 03:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: subl -w
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

**Comment by gromgit** [comment]
I don't see anything amiss in your `brew config` output, and since `brew doctor` says you're good to go, there's nothing else for you to fix for now.

**Comment by DaniSpringer** [comment]
> I don't see anything amiss in your `brew config` output, and since `brew doctor` says you're good to go, there's nothing else for you to fix for now.

Thank you!
