### ISSUE TITLE
Bash completions for homebrew does not correctly work. 

### ISSUE THREAD

**Issue by y-vectorfield** [Homebrew/brew#14966]
### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew --version
Homebrew 4.0.6
Homebrew/homebrew-core (git revision a0c6d795116; last commit 2023-02-22)
Homebrew/homebrew-cask (git revision fba49e2cbb; last commit 2023-02-22)
yuhkiyano:~ $ brew config
HOMEBREW_VERSION: 4.0.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0c1031f2fd71016f0f5df699caaed384487bfb16
Last commit: 4 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a0c6d795116fcc928b9e326150944750d944a013
Core tap last commit: 3 weeks ago
Core tap branch: master
Core tap JSON: 14 Mar 07:08 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Run the brew command.

### What happened (include all command output)?

Bash completions for homebrew does not correctly work.

### What did you expect to happen?

When we press the tab key, bash completions shows a sub command for brew.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew do(Press Tab key)
brew Documents/
(Desired result: brew doctor)
(Related issue: https://github.com/Homebrew/homebrew-core/issues/125588)
```

**Comment by MikeMcQuaid** [comment]
Please follow https://docs.brew.sh/Shell-Completion#configuring-completions-in-bash and open a discussion if it's not working for you still.

**Comment by MikeMcQuaid** [comment]
@y-vectorfield Someone may be able to help you in a discussion.
