### ISSUE TITLE
brew services  报错

### ISSUE THREAD

**Issue by lichangpei0825** [Homebrew/brew#14993]
### `brew doctor` output

```shell
Warning: Calling formula.plist_path is deprecated! Use formula.launchd_service_path instead.
Please report this issue to the homebrew/services tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:58
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
Homebrew 4.0.6-128-gd0c5202
Homebrew/homebrew-core (git revision 9521762381d; last commit 2023-03-16)
Homebrew/homebrew-cask (git revision 7317d293ec; last commit 2023-03-16)
```

### What were you trying to do (and why)?

brew services  报错

### What happened (include all command output)?

brew services  报错

### What did you expect to happen?

brew services  报错

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew services  报错
```

**Comment by MikeMcQuaid** [comment]
`brew untap homebrew/services; brew tap homebrew/services`.
