### ISSUE TITLE
`provides` or `satisfies` value in formulae

### ISSUE THREAD

**Issue by DestroyerXyz** [Homebrew/brew#14999]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

A `satisfies` or `provides` value that can be provided by package formulae that does not block other packages like `conflicts` but satisfies other packages' dependencies.

### What is the motivation for the feature?

I use [fnm](https://github.com/Homebrew/homebrew-core/blob/master/Formula/fnm.rb) for managing my node versions.
So I have to keep the homebrew node around for packages that require node.
This can be solved if node managers like nvm and fnm can provide a `satisfies` or `provides` value for `node`.

### How will the feature be relevant to at least 90% of Homebrew users?

Many people use language version managers like nvm and fnm (for node), pyenv (for python), jenv (for java), etc.
Can also be useful in other cases as [Arch provides it too](https://wiki.archlinux.org/title/PKGBUILD#:~:text=.-,provides,-An%20array%20of).

### What alternatives to the feature have been considered?

Removing language runtime dependencies from formulae but that can cause problems.

**Comment by reitermarkus** [comment]
The only benefit of doing this is saving a couple MBs of disk space. We did that previously for some languages, but it only adds complexity and more failure points. If you uninstall your externally managed Node version, all programs installed with Homebrew would be broken. We also cannot test with external Node versions in CI, so this would anyways be virtually unsupported.

**Comment by MikeMcQuaid** [comment]
We used to do this, things broke all the time, we're never going to do it again, sorry!
