### ISSUE TITLE
SSLRead error -9806

### ISSUE THREAD

**Issue by China131** [Homebrew/brew#1499]
when i install brew,error as follow.how i can fix this error?
fatal: unable to access 'https://github.com/Homebrew/brew/': SSLRead() return error -9806
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force --depth=1

**Comment by MikeMcQuaid** [comment]
You're having issues connection to GitHub. We can't do anything about that, I'm afraid. I'd suggest rerunning the installer (and uninstalling in between if necessary) multiple times until it installs 🆗.
