### ISSUE TITLE
Handle `HOMEBREW_PREFIX` references in `keg_only` reasons

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#14996]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`brew` should handle `HOMEBREW_PREFIX` references in `keg_only` reasons. Examples of ways to handle this are:
1. Relocate the `HOMEBREW_PREFIX` reference
2. Disallow `HOMEBREW_PREFIX` references by an audit

The above list may not be exhaustive.

### What is the motivation for the feature?

This can lead to confusing `caveats` when installing from the API. For example, the output of `brew info socket_vmnet` produces:

```
==> Caveats
To install an optional launchd service, run the following command (sudo is necessary):
sudo brew services start socket_vmnet

socket_vmnet is keg-only, which means it was not symlinked into /opt/homebrew,
because /usr/local/bin is often writable by a non-admin user.
```

### How will the feature be relevant to at least 90% of Homebrew users?

Fewer confusing caveats.

### What alternatives to the feature have been considered?

Doing nothing.

**Comment by issyl0** [comment]
There's only a reference to `HOMEBREW_PREFIX` in one formula, so I'm not sure it's worth an audit. But we can certainly remove the reference!

```
issyl0 at pictor in /opt/homebrew/Library/Taps/homebrew/homebrew-core on master
❯ git grep keg_only | grep HOMEBREW_PREFIX
Formula/socket_vmnet.rb:  keg_only "#{HOMEBREW_PREFIX}/bin is often writable by a non-admin user"
```

**Comment by carlocab** [comment]
Yea, we could do that. Not even sure the `keg_only` reason is worth it, though -- if an attacker has write access to `$HOMEBREW_PREFIX/bin`, you're already hosed. But CC @Homebrew/maintainers for thoughts.

**Comment by MikeMcQuaid** [comment]
@carlocab strongly agreed.

**Comment by MikeMcQuaid** [comment]
> so I'm not sure it's worth an audit.

Personally: I think it is to avoid backsliding. The audit can be simple, though.

**Comment by issyl0** [comment]
I did the audit in #15003 but then went with #15004 instead as that was similar to what we do for replacing prefix references in caveats when installing from the API. That skips this problem all together, while allowing prefix references in keg_only messages.

**Comment by carlocab** [comment]
Since we're discussing the handling of caveats here, this is related: https://github.com/Homebrew/brew/issues/14925#issuecomment-1473303922
