### ISSUE TITLE
Make Homebrew faster

### ISSUE THREAD

**Issue by k-nearest-neighbor** [Homebrew/brew#15010]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

There should be an initiative to make Homebrew much faster.

- Identify slow operations
- Evaluate and implement mitigations

### What is the motivation for the feature?

It's regularly too slow by far. Pip, npm, yarn, apt, yum, etc are fast. Homebrew by contrast often takes minutes to install a small package, and for some laggy operations lacks visual feedback.

### How will the feature be relevant to at least 90% of Homebrew users?

This should be relevant to 100% of users.

Check out "Why is homebrew so slow?" in your choice search engine.

### What alternatives to the feature have been considered?

Using other package managers.

**Comment by MikeMcQuaid** [comment]
This is not an actionable or helpful feature request.

**Comment by k-nearest-neighbor** [comment]
Can you explain?

Why is "making homebrew faster" not actionable?

And how is caring enough to write a ticket this anything but helpful?

**Comment by carlocab** [comment]
It's not helpful or actionable because we've already done this:

> There should be an initiative to make Homebrew much faster.
> 
> * Identify slow operations
> * Evaluate and implement mitigations

You'll need to be more specific, and more likely, create your own pull requests that improve the speed of `brew`.

**Comment by apainintheneck** [comment]
The thing is that brew is complex enough that telling us that somethings is slow is not specific enough to be actionable.

```
~ $ brew commands | wc -l
     115
```

There are a ton of different commands and they all probably have different performance bottlenecks whether that be bash, git, ruby, network requests or different third-party packagers and compilers.

We're always open to improving the speed of commands. Are there any specific ones that are slow for you?

Also, you can use the `brew prof` command to profile commands if you're interested in investigating further.
