### ISSUE TITLE
Disable curl progress bar when running commands (--no-progress-meter option)

### ISSUE THREAD

**Issue by swrobel** [Homebrew/brew#15017]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Set the [--no-progress-meter](https://curl.se/docs/manpage.html#--no-progress-meter) curl option by default. Previously raised in the discussions board [here](https://github.com/Homebrew/discussions/discussions/4324).

### What is the motivation for the feature?

When running homebrew commands, it regularly updates in the background, which is a nice feature. However, this uses curl, which in turn displays a progress bar:
```
$ brew outdated
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
```

### How will the feature be relevant to at least 90% of Homebrew users?

If I recall correctly, when `brew` used `git` under the hood, it didn't display output from the `git` command as it was syncing the latest changes. This extra output is perhaps useful to some users on unreliable connections, but to most, they're expecting to see the same behavior of zero lines of output to commands like `brew outdated` as was the case before the change to the json-based formula API.

### What alternatives to the feature have been considered?

Create a `~/.curlrc` and disable the progress bar there, and set `HOMEBREW_CURLRC=1`. However, setting this in `.curlrc` will mean that all `curl` commands that I run, even those that aren't run through `brew`, will have the progress meter disabled.

**Comment by MikeMcQuaid** [comment]
I don't think this should be a command-line option, that doesn't make sense to me.

@Bo98 suggested we display this progress bar because users on slow connections otherwise get no connection progress when this is downloaded.

Ideally there'd be some sort of "only show this after a certain amount of time" behaviour in `curl` itself but: I don't think this is possible.

**Comment by swrobel** [comment]
> I don't think this should be a command-line option, that doesn't make sense to me.

Not necessarily saying this should be a command-line option, but I'd like some way to permanently disable the progress meter, given that it seems like it was intentional to start showing progress for commands in brew 4.0.

**Comment by apainintheneck** [comment]
I believe that the `--quiet` option already does this but it disables other output too depending on the command.

**Comment by swrobel** [comment]
> I believe that the `--quiet` option already does this but it disables other output too depending on the command.

Indeed it does. For example, with `brew outdated`, I prefer to pass `--verbose` to see the old & new versions of formulae.

```
  -q, --quiet                      List only the names of outdated kegs (takes
                                   precedence over --verbose).
  -v, --verbose                    Include detailed version information.
```

**Comment by MikeMcQuaid** [comment]
Passing on this for now, sorry, but thanks for the issue. Want to see a few more people request this before we consider it. Feel free to create a PR now but just with the caveat that I think this shouldn't be optional but instead be time-limited if it can be done without using e.g. threads or another overcomplicated implementation.
