### ISSUE TITLE
Cask: No available formula with the name "brew-cask" when using latest version

### ISSUE THREAD

**Issue by gcaracuel** [Homebrew/brew#1503]
Brew version: 1.1.0
OSX version: 10.10.04

Getting errors when trying to install any Cask formula:
`No available formula with the name "brew-cask" 
Error: Cask 'atom' definition is invalid: Bad header line: parse failed`

Same for any other than 'atom' since updated to latest version. Saw some changes related to Cask in this new release.

Note I am using Ansible to provision some test Vagrant boxes so it ensures latest brew updated is installed. I rolled back to 1.0.9 and seems to work fine.

**Comment by MikeMcQuaid** [comment]
What is the `brew` command you (or Ansible) is running and as what user?

**Comment by gcaracuel** [comment]
After Ansible modules failed I tried running brew cask installs using the only user my VM has: vagrant (as I mentioned I am running this in a testing vagrant VM)

**Comment by gcaracuel** [comment]
@MikeMcQuaid seems something related to networking. So I think this could be closed, sorry for inconveniences, now it is failing ~33% of the times only...
