### ISSUE TITLE
TypeError: no implicit conversion of false into String

### ISSUE THREAD

**Issue by derekPrivate** [Homebrew/brew#15037]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d0154fa7926e8a7b06e9b074dd45957e820407c
Last commit: 26 hours ago
Core tap JSON: 28 Feb 15:05 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 1
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: single-core 64-bit haswell
Clang: N/A
Git: 2.38.3 => /usr/bin/git
Curl: 7.61.1 => /usr/bin/curl
Kernel: Linux 4.14.281-144.502.amzn1.x86_64 x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
/usr/bin/ruby: 2.0.0
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Using Amazon Linux 1 (quite an old version of Linux)
installed brew without problems, then wanted to
brew install gcc

reports error
TypeError: no implicit conversion of false into String

### What happened (include all command output)?

(switching on --verbose and --debug) shows this

==> Postinstalling gcc
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /home/linuxbrew/.linuxbrew/opt/gcc/.brew/gcc.rb
Warning: The post-install step did not complete successfully
You can try again using:
brew postinstall gcc
==> An exception occurred within a child process:
TypeError: no implicit conversion of false into String

/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in initialize' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in popen' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:9:in popen_read'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:16:in safe_popen_read' /home/linuxbrew/.linuxbrew/opt/gcc/.brew/gcc.rb:151:in post_install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1160:in block (2 levels) in run_post_install' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:968:in with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1159:in block in run_post_install' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:606:in with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1148:in run_post_install' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/postinstall.rb:24:in 

'

### What did you expect to happen?

gcc to be installed!

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gcc
```

**Comment by MikeMcQuaid** [comment]
> > Does the API generate a different formula than the file in the repo? That's going to make backtraces hard to use 😢
> 
> Yes, unfortunately. Would be good to find a way to map lines to the original formula. Or maybe dump the generated one somehow. CC @Rylan12

There is no generated formula file. It's generating a formula dynamically from JSON.

**Comment by MikeMcQuaid** [comment]
@derekPrivate Is this still a problem for you and can you still reproduce it? If so, can I get you to `brew update` and run a `brew install --verbose --debug` again and supply your latest `brew config` and `brew doctor`? Thanks again!

**Comment by derekPrivate** [comment]
I uninstalled home-brew and started afresh..

The good news is that I have now successfully install gcc without error!

Thanks for your help
—
Derek

**Comment by MikeMcQuaid** [comment]
Great, thanks!
