### ISSUE TITLE
brew update: removed casks are not displayed

### ISSUE THREAD

**Issue by muescha** [Homebrew/brew#15048]
### `brew doctor` output

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker

Warning: You have uncommitted modifications to Homebrew/brew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew && git stash -u && git clean -d -f

Uncommitted files:
  ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/public_suffix-4.0.6/data/list.txt
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 4.0.9-57-g86c518e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 86c518e2d7180b054b7b215dad87f2780379d537
Last commit: 7 hours ago
Core tap JSON: 24 Mar 07:31 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

I run `brew update`

### What happened (include all command output)?

```shell
brew update
==> Updated Homebrew from ea92f56da to 86c518e2d.
Updated 4 taps (homebrew/cask-versions, homebrew/cask-drivers, homebrew/core and homebrew/cask).
==> New Formulae
llvm@15
==> New Casks
zed
==> Outdated Formulae
chezmoi                                    jc                                         sqlite

You have 3 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.
```

### What did you expect to happen?

given:

- removed casks: https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+sort%3Aupdated-desc+remove+is%3Aclosed+label%3A%22marked+for+removal%2Frejection%22
- new casks: https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3A%22new+cask%22+is%3Amerged+

i expect that i see the removed cask: catoclient (https://github.com/Homebrew/homebrew-cask/pull/143610)

NOTE: Interesting that `cask_names.txt` and `cask_names.before.txt` are the same. I expected here to have the previous version available.

```shell
/Users/muescha/Library/Caches/Homebrew/api
$ ll
Permissions       Size User    Date Modified    Name
.rw-r--r--   5,063,589 muescha 2023-03-24 08:31 cask.jws.json
.rw-r--r--      46,266 muescha 2023-03-24 08:31 cask_names.before.txt
.rw-r--r--      46,266 muescha 2023-03-24 08:31 cask_names.txt
.rw-r--r--  22,856,361 muescha 2023-03-24 08:31 formula.jws.json
.rw-r--r--       5,316 muescha 2023-03-24 08:31 formula_aliases.txt
.rw-r--r--      58,071 muescha 2023-03-24 08:31 formula_names.before.txt
.rw-r--r--      58,071 muescha 2023-03-24 08:31 formula_names.txt
```

anyway. I got from time machine the file restored named as `cask_names.1before.txt`

I checked the output of the `git diff` and i see there are both casks are visible:

```shell
/Users/muescha/Library/Caches/Homebrew/api
$ git diff cask_names.1before.txt cask_names.txt
diff --git a/cask_names.1before.txt b/cask_names.txt
index ad0089a..94df9dc 100644
--- a/cask_names.1before.txt
+++ b/cask_names.txt
@@ -511,7 +511,6 @@ cashnotify
 castr
 catch
 catlight
-catoclient
 cave-story
 ccleaner
 ccmenu
@@ -4141,6 +4140,7 @@ zazu
 zdoom
 zebra2
 zecwallet-lite
+zed
 zeebe-modeler
 zeitgeist
 zenbeats
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
==> Updated Homebrew from ea92f56da to 86c518e2d.
Updated 4 taps (homebrew/cask-versions, homebrew/cask-drivers, homebrew/core and homebrew/cask).
==> New Formulae
llvm@15
==> New Casks
zed
==> Outdated Formulae
chezmoi                                    jc                                         sqlite

You have 3 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.
```

### Related Issues

- #15038 cmd/update-report: fix ordering. 
- #15036 removed casks are are displayed as new casks

**Comment by leonardoadame** [comment]
> ### `brew doctor` output
> 
> ```shell
> brew doctor
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry or file an issue; just ignore this. Thanks!
> 
> Warning: You have unlinked kegs in your Cellar.
> Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
> those kegs to fail to run properly once built. Run `brew link` on these:
>   docker
> 
> Warning: You have uncommitted modifications to Homebrew/brew.
> If this is a surprise to you, then you should stash these modifications.
> Stashing returns Homebrew to a pristine state but can be undone
> should you later need to do so for some reason.
>   cd /opt/homebrew && git stash -u && git clean -d -f
> 
> Uncommitted files:
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/public_suffix-4.0.6/data/list.txt
> ```
> 
> 
> ### Verification
> 
> - [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
> - [X] I ran `brew update` twice and am still able to reproduce my issue.
> - [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.
> 
> ### `brew config` output
> 
> ```shell
> brew config
> HOMEBREW_VERSION: 4.0.9-57-g86c518e
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: 86c518e2d7180b054b7b215dad87f2780379d537
> Last commit: 7 hours ago
> Core tap JSON: 24 Mar 07:31 UTC
> HOMEBREW_PREFIX: /opt/homebrew
> HOMEBREW_CASK_OPTS: []
> HOMEBREW_MAKE_JOBS: 10
> Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
> CPU: 10-core 64-bit arm_firestorm_icestorm
> Clang: 14.0.0 build 1400
> Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
> Curl: 7.85.0 => /usr/bin/curl
> macOS: 13.1-arm64
> CLT: 14.2.0.0.1.1668646533
> Xcode: 14.2
> Rosetta 2: false
> ```
> 
> 
> ### What were you trying to do (and why)?
> 
> I run `brew update`
> 
> ### What happened (include all command output)?
> 
> ```shell
> brew update
> ==> Updated Homebrew from ea92f56da to 86c518e2d.
> Updated 4 taps (homebrew/cask-versions, homebrew/cask-drivers, homebrew/core and homebrew/cask).
> ==> New Formulae
> llvm@15
> ==> New Casks
> zed
> ==> Outdated Formulae
> chezmoi                                    jc                                         sqlite
> 
> You have 3 outdated formulae installed.
> You can upgrade them with brew upgrade
> or list them with brew outdated.
> ```
> 
> ### What did you expect to happen?
> 
> given:
> 
> - removed casks: https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+sort%3Aupdated-desc+remove+is%3Aclosed+label%3A%22marked+for+removal%2Frejection%22
> - new casks: https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3A%22new+cask%22+is%3Amerged+
> 
> i expect that i see the removed cask: catoclient (https://github.com/Homebrew/homebrew-cask/pull/143610)
> 
> 
> NOTE: Interesting that `cask_names.txt` and `cask_names.before.txt` are the same. I expected here to have the previous version available.
> 
> ```shell
> /Users/muescha/Library/Caches/Homebrew/api
> $ ll
> Permissions       Size User    Date Modified    Name
> .rw-r--r--   5,063,589 muescha 2023-03-24 08:31 cask.jws.json
> .rw-r--r--      46,266 muescha 2023-03-24 08:31 cask_names.before.txt
> .rw-r--r--      46,266 muescha 2023-03-24 08:31 cask_names.txt
> .rw-r--r--  22,856,361 muescha 2023-03-24 08:31 formula.jws.json
> .rw-r--r--       5,316 muescha 2023-03-24 08:31 formula_aliases.txt
> .rw-r--r--      58,071 muescha 2023-03-24 08:31 formula_names.before.txt
> .rw-r--r--      58,071 muescha 2023-03-24 08:31 formula_names.txt
> ```
> 
> anyway. I got from time machine the file restored named as `cask_names.1before.txt`
> 
> I checked the output of the `git diff` and i see there are both casks are visible:
> 
> 
> ```shell
> /Users/muescha/Library/Caches/Homebrew/api
> $ git diff cask_names.1before.txt cask_names.txt
> diff --git a/cask_names.1before.txt b/cask_names.txt
> index ad0089a..94df9dc 100644
> --- a/cask_names.1before.txt
> +++ b/cask_names.txt
> @@ -511,7 +511,6 @@ cashnotify
>  castr
>  catch
>  catlight
> -catoclient
>  cave-story
>  ccleaner
>  ccmenu
> @@ -4141,6 +4140,7 @@ zazu
>  zdoom
>  zebra2
>  zecwallet-lite
> +zed
>  zeebe-modeler
>  zeitgeist
>  zenbeats
> ```
> 
> ### Step-by-step reproduction instructions (by running `brew` commands)
> 
> ```shell
> brew update
> ==> Updated Homebrew from ea92f56da to 86c518e2d.
> Updated 4 taps (homebrew/cask-versions, homebrew/cask-drivers, homebrew/core and homebrew/cask).
> ==> New Formulae
> llvm@15
> ==> New Casks
> zed
> ==> Outdated Formulae
> chezmoi                                    jc                                         sqlite
> 
> You have 3 outdated formulae installed.
> You can upgrade them with brew upgrade
> or list them with brew outdated.
> ```
> 
> 
> ### Related Issues
> 
> - #15038 cmd/update-report: fix ordering. 
> - #15036 removed casks are are displayed as new casks 
> 
>
