### ISSUE TITLE
Error: uninitialized constant Cask::Reinstall

### ISSUE THREAD

**Issue by gsong** [Homebrew/brew#15043]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.9-46-g8f9caa3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8f9caa3427c4a07bd9bb287109e248f5bcbc0601
Last commit: 23 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fcc29e3819ddfd759d6cb208c4ea9e46e926f0fe
Core tap last commit: 7 minutes ago
Core tap branch: master
Core tap JSON: 23 Mar 16:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: edit
HOMEBREW_INSTALL_BADGE: ☕
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Reinstall a cask. It's part of my maintenance script where if a formula doesn't have a version number, I always try to reinstall it.

### What happened (include all command output)?

```sh
~ $ brew reinstall --cask font-input
Error: uninitialized constant Cask::Reinstall
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/cmd/reinstall.rb:153:in `reinstall'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

For the cask to reinstall properly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap homebrew/cask-fonts
brew reinstall --cask font-input
```
```

**Comment by carlocab** [comment]
Looks like #15040. CC @hyuraku. Will revert shortly if we don't have a fix by then.

**Comment by MikeMcQuaid** [comment]
@carlocab Don't wait: reverting in https://github.com/Homebrew/brew/pull/15044.
