### ISSUE TITLE
Add prompt to overwrite existing application

### ISSUE THREAD

**Issue by weakphish** [Homebrew/brew#15041]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When installing an application that has an existing file, prompt to overwrite. I do not mean overwrite an existing formula/brew install, but usually leftovers from a brew remove. Example:

```
==> Installing Cask emacs-mac
==> Purging files for version emacs-28.2-mac-9.1 of Cask emacs-mac
Error: It seems there is already an App at '/Applications/Emacs.app'.
```
shows after
```
brew remove emacs-mac
brew install --cask emacs-mac
```

### What is the motivation for the feature?

I would like it if I could just have brew overwrite the artifact.

### How will the feature be relevant to at least 90% of Homebrew users?

I'm sure there are plenty of formulas that leave artifacts after removal, and so reinstallation shouldn't require manual cleanup.

### What alternatives to the feature have been considered?

Manual removal is tedious and less pleasurable to the user.

**Comment by carlocab** [comment]
Have you tried
```
brew install --overwrite --cask emacs-mac
```
?

**Comment by MikeMcQuaid** [comment]
Or `brew reinstall --force emacs-mac`.

There's multiple workarounds so passing on this.

**Comment by weakphish** [comment]
Ah, I was unfamiliar with those options @carlocab @MikeMcQuaid thanks for the info & apologies!
