### ISSUE TITLE
Only search for packages relevant for my platform

### ISSUE THREAD

**Issue by henrik242** [Homebrew/brew#15053]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

As mentioned in https://github.com/orgs/Homebrew/discussions/4355, I get both macOS and Linux-only packages when doing a `brew search` on macOS.

I don't see the value of seeing Linux-only packages when searching on macOS.  By default the search result should be filtered for my architecture. 

Context:

When I do a `brew search liberica` I get a lot of results, including `bell-sw/liberica/liberica-jdk@18`. But installing that fails:
```
🐤 brew install bell-sw/liberica/liberica-jdk@18  
liberica-jdk@18: Linux is required for this software.
Error: liberica-jdk@18: An unsatisfied requirement failed this build.
```
I realize that I can install bell-sw/liberica/liberica-jdk18 instead:
```
🐤 brew info bell-sw/liberica/liberica-jdk18  
==> liberica-jdk18: 18.0.2.1,1
https://bell-sw.com
Not installed
From: https://github.com/bell-sw/homebrew-liberica/blob/HEAD/Casks/liberica-jdk18.rb
==> Name
BellSoft Liberica JDK 18
==> Description
100% open-source Java implementation
==> Artifacts
bellsoft-jdk18.0.2.1+1-macos-aarch64.pkg (Pkg)
🐤 brew info bell-sw/liberica/liberica-jdk@18
==> bell-sw/liberica/liberica-jdk@18: stable 18.0.2.1.1
100% open-source Java implementation
https://bell-sw.com/
Not installed
From: https://github.com/bell-sw/homebrew-liberica/blob/HEAD/Formula/liberica-jdk@18.rb
==> Requirements
Required: Linux ✘
```

### What is the motivation for the feature?

It gives no value getting uninstallable packages from `brew search`

### How will the feature be relevant to at least 90% of Homebrew users?

Users won't be presented with packages they cannot use

### What alternatives to the feature have been considered?

I haven't found any alternatives that will only list packages for my architecture.

**Comment by MikeMcQuaid** [comment]
This would be nice-to-have but given how `brew search` is currently implemented: may be a tricky lift.
