### ISSUE TITLE
How to tap a local repo?

### ISSUE THREAD

**Issue by HaraldNordgren** [Homebrew/brew#1505]
I am developing a tap. How do I tap my local repo folder, so I don't have to commit and push the code to test out my changes?

     % brew tap /path/to/local/repo
    Error: Invalid tap name '/path/to/local/repo'

The docs (https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) state that "A tap is usually a git repository available online, but you can use anything as long as it’s a protocol that git understands, or even just a directory with files in it."

**Comment by HaraldNordgren** [comment]
Looking at the source (https://github.com/Homebrew/brew/blob/master/Library/Homebrew/tap.rb), I'm not sure it is currently possible at all:

```
  def self.fetch(*args)
    case args.length
    when 1
      user, repo = args.first.split("/", 2)
    when 2
      user = args[0]
      repo = args[1]
    end

    if [user, repo].any? { |part| part.nil? || part.include?("/") }
      raise "Invalid tap name '#{args.join("/")}'"
    end
```

**Comment by scpeters** [comment]
If you have an `owner` and `tap_name` such that eventually it will live at `https://github.com/owner/homebrew-tap_name`, then the following might work:

~~~
git clone /path/to/local/repo `brew --repo`/Library/Taps/owner/tap_name
~~~

**Comment by MikeMcQuaid** [comment]
> How do I tap my local repo folder, so I don't have to commit and push the code to test out my changes?

You don't have to commit and push to test tap changes. You can edit the files in the local tap directory which is a Git repository using `brew edit $FORMULA` and then only commit and push when you're ready. There's no need to tap a repository that's already on your machine as then you'll have the same files in two places rather than one.

**Comment by bfontaine** [comment]
> If you have an `owner` and `tap_name` such that eventually it will live at `https://github.com/owner/homebrew-tap_name`, then the following might work:
>
> ~~~
> git clone /path/to/local/repo `brew --repo`/Library/Taps/owner/tap_name
> ~~~

Instead of duplicating your code all you have to do is to put your local tap in the location Homebrew expects it:

    mv /path/to/local/repo `brew --repo`/Library/Taps/owner/tap_name

Then edit your formulae like before and Homebrew will find them.
