### ISSUE TITLE
formula.plist_path

### ISSUE THREAD

**Issue by godgamesc** [Homebrew/brew#15071]
### `brew doctor` output

```shell
Warning: Calling formula.plist_path is deprecated! Use formula.launchd_service_path instead.
Please report this issue to the homebrew/services tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:58
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.10-13-g12e7787
ORIGIN: https://github.com/Homebrew/brew
HEAD: 12e7787eb6db23cb8a50c0b1ca350bb9c1301e73
Last commit: 42 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 48313b20c7a7cec93a7ac6168e22dd50a476fc61
Core tap last commit: 8 months ago
Core tap branch: master
Core tap JSON: 27 Mar 08:56 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

brew services start php@7.4

### What happened (include all command output)?

success

### What did you expect to happen?

success

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew services start php@7.4
```

**Comment by gromgit** [comment]
As the warning clearly states:
>```
>Please report this issue to the homebrew/services tap (not Homebrew/brew or Homebrew/homebrew-core)
>```

Someone obeyed those instructions a month ago: https://github.com/Homebrew/homebrew-services/issues/553. See if any of the suggested solutions there apply to you.
