### ISSUE TITLE
brew update: --quiet isn't quiet (on stdout)

### ISSUE THREAD

**Issue by brevilo** [Homebrew/brew#15076]
### `brew doctor` output

```shell
% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
% brew config
HOMEBREW_VERSION: 4.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: cf6614b50eac1c9f4bf386dc6989f0d443148df8
Last commit: 22 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: feac505ccf72c9b7380116d081729aa7af029422
Core tap last commit: 4 weeks ago
Core tap branch: master
Core tap JSON: 28 Mar 08:51 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.4PIdwCn7pQ/org.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-x86_64
CLT: N/A
Xcode: 14.2
```

### What were you trying to do (and why)?

I'm running `brew update --quiet` (or even `brew update --quiet >/dev/null` for that matter) in a cronjob.

### What happened (include all command output)?

It returned the following on `stdout` (which triggers a spurious mail in my use case):
```
Updated 2 taps (homebrew/core and homebrew/cask).
```

### What did you expect to happen?

When using the `--quiet` option, ideally nothing should be written to `stdout`, only `stderr`. Or, alternatively, `stdout` should be allowed to be redirected to `/dev/null`, but that's ineffective right now (see below).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Run `brew update --quiet` after an upstream update
```

The reasons are:
* The [message](https://github.com/Homebrew/brew/blob/ea92f56da4741fb9678d1bcd3e61f24825cee892/Library/Homebrew/cmd/update-report.rb#L236) is being printed without honoring `args.quiet`.
* Unfortunately redirecting `stdout` to, say, `/dev/null` can't be used either, since then the output gets [rerouted](https://github.com/Homebrew/brew/blob/ea92f56da4741fb9678d1bcd3e61f24825cee892/Library/Homebrew/cmd/update-report.rb#L41) to `stderr` instead (part of #12469). `stderr` itself should not be silenced of course.

Thanks

**Comment by MikeMcQuaid** [comment]
The no-op output is silent with `--quiet`. As it's not `--silent`: I don't think it's appropriate that nothing is output on `--quiet in this case.

If you don't care about any of the update: consider `brew update &>/dev/null`. Alternatively, perhaps https://github.com/Homebrew/homebrew-autoupdate would be a better fit.

Passing, sorry!

**Comment by brevilo** [comment]
> consider `brew update &>/dev/null`

That would silence errors as well. Isn't it a pretty standard use case to silence normal output but not errors? If `--quiet` isn't "silent" on purpose, ok, that's a design decision. But forcefully redirecting `stdout` to `stderr` when redirecting to `/dev/null` takes away the only alternative. Is that really necessary?

**Comment by brevilo** [comment]
Well, tough luck then. Still think my use case is pretty common though. Now need to resort to manual filtering...
