### ISSUE TITLE
Remove `brew audit --display-failures-only`

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#15074]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`brew audit --display-failures-only` should be `odeprecated`, made the default behaviour and omitting it replaced with `--strict` (or, if appropriate, `--git`, `--online`, `--new-cask`, etc.)

### What is the motivation for the feature?

It's confusing to have a behaviour like this that applies only for casks when there's an equivalent already there for formulae. Similarly, the default output without `--display-failures-only` is very hard to follow as it's hard to find the actual error over all the warnings.

### How will the feature be relevant to at least 90% of Homebrew users?

Improved contributor and maintainer productivity.

### What alternatives to the feature have been considered?

Doing nothing.

**Comment by issyl0** [comment]
> brew audit --display-failures-only should be odeprecated, made the default behaviour and omitting it replaced with --strict (or, if appropriate, --git, --online, --new-cask, etc.)

I don't understand the last part of this sentence.

1. should be `odeprecated` 👍🏻
2. made the default behaviour 👍🏻
3. omitting it replaced with `--strict` or others ❓

Omitting what? If only showing failures is the default that we want then the user would type a plain `brew audit <cask>` command. Do we need a reverse switch for `--display-everything` or `--all` or something which shows `--strict` and friends?

**Comment by MikeMcQuaid** [comment]
@issyl0 Sorry for confusion. My thinking is aligning formulae and casks on how audits work. Formulae do not have the concept of non-fatal warnings: something is either an audit failure or it is not displayed. `brew audit` is the typical flow, `brew audit --strict` displays optional audit failures.

As a result, I propose that all current cask audit warnings are never displayed as warnings but the underlying audit checks turned into errors displayed only with `--strict` (or one of the other relevant flags).

Does that make more sense?
