### ISSUE TITLE
Alert API users that edited formulae won't be included automatically in commands

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/brew#15073]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Basically, if you're using the API as a homebrew developer, it might not be obvious that local changes won't be reflected when using most commands. It would be nice to warn users that there local changes are not being used unless `HOMEBREW_NO_INSTALL_FROM_API` is set.

Ideally this would mean seeing if the exact formula that is being used is that same one that was modified. This would also probably be useful for casks too.

Beyond that there has been some talk of adding a flag to some commands that turns off the API to make it easier for users to switch between local packages and fetching them from the API.

The idea is outlined in https://github.com/Homebrew/brew/pull/14807 but since that got closed I wanted to create an issue so we don't forget about it.

### What is the motivation for the feature?

The idea here is to lower the barrier to entry to contributing by making the dev experience more intuitive. If you make changes to a local package and try and install it, you would expect to see those changes. We've already had multiple cases where this lead to confusion.

### How will the feature be relevant to at least 90% of Homebrew users?

It is only relevant to dev users but they end up providing package definitions that everyone else benefits from. Improving the local dev tooling helps them update/add more packages.

### What alternatives to the feature have been considered?

Improving documentation around editing formulas/casks as a dev user.

**Comment by Bo98** [comment]
We did have a message in `brew edit` but there was a bug that prevent that from displaying, which I've fixed in #15582.

**Comment by MikeMcQuaid** [comment]
Assuming from @bo98's message that this was fixed in https://github.com/Homebrew/brew/pull/15582 but please reopen anyone if I've misunderstood.

**Comment by apainintheneck** [comment]
The message for `brew edit` is helpful but doesn't cover the main issue with `brew install` not using local changes when `HOMEBREW_NO_INSTALL_FROM_API` is not set. Not sure how I missed that this issue got closed until now though.

**Comment by Bo98** [comment]
[What I've suggested before](https://github.com/Homebrew/homebrew-core/pull/138060#issuecomment-1658291638) is maybe a `--local`  that is basically a `HOMEBREW_NO_INSTALL_FROM_API` without the verbosity of an environment variable or any misuse of setting it globally. Such flag should imply `--build-from-source` too. This splits up the intention much better into:
* I need to install the latest version from bottles - default
* I need to install the latest version from source - `--build-from-source`
* I need to edit this formula - `--local`

In terms of signposting, we never had any signposting for `--build-from-source` already and the plan would be a flag that would effectively replace that flag for contribution-type work.

**Comment by apainintheneck** [comment]
Yep, I really like the idea of having a `--local` option for this.

The question of how wide to scope the implicit without api use of `brew install` is a bit tricky. Wrapping the entire command would be the simplest thing to do and would mimic the current `HOMEBREW_NO_INSTALL_FROM_API=1 brew install` behavior but I'm not sure it works the same way as `brew install --build-from-source`.

**Comment by MikeMcQuaid** [comment]
> Yep, I really like the idea of having a `--local` option for this.

Agreed.

> It's very easy to implement.

@Bo98 Could you give it a go if so?






> The question of how wide to scope the implicit without api use of `brew install` is a bit tricky.

Do you mean implicit with or without `--local`?

**Comment by apainintheneck** [comment]
> > The question of how wide to scope the implicit without api use of `brew install` is a bit tricky.
> 
> Do you mean implicit with or without `--local`?

I meant with `--local` especially if we're going to use it to replace some of the `--build-from-source` use.

**Comment by MikeMcQuaid** [comment]
@apainintheneck Gotcha. Yeh, I think it should replace all `--build-from-source` use for development really.

**Comment by MikeMcQuaid** [comment]
I feel like this is Done Enough for now.

**Comment by apainintheneck** [comment]
I'd like to add something here to clarify things for users but I'm not exactly sure how to do it without possibly causing confusion for other users. Have we seen any recent complaints from users related to this recently?

**Comment by MikeMcQuaid** [comment]
> I'd like to add something here to clarify things for users but I'm not exactly sure how to do it without possibly causing confusion for other users. Have we seen any recent complaints from users related to this recently?

@apainintheneck I have not. I agree I don't think we're at a perfect outcome here yet but I think it's Good Enough For Now.
