### ISSUE TITLE
any plans on supporting fblualib

### ISSUE THREAD

**Issue by kirk86** [Homebrew/brew#1507]
Hi everyone, are there any plans on supporting [fblualib](https://github.com/facebook/fblualib) in brew? Thanks!

**Comment by MikeMcQuaid** [comment]
There are not. If you'd like there to be: could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by kirk86** [comment]
@MikeMcQuaid thanks a lot! I'll go through it and if I find any difficulties I'll reach to you...
