### ISSUE TITLE
RuboCop for trailing slash in verified url stanza

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/brew#15108]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

As apparent from https://github.com/Homebrew/homebrew-cask/pull/144179, cask style dictates that verified stanzas with path components should end in a trailing slash. Homebrew should have a rubocop to enforce this.

### What is the motivation for the feature?

It saves maintainers work and ensures consistency 

### How will the feature be relevant to at least 90% of Homebrew users?

Happy maintainers make happy users

### What alternatives to the feature have been considered?

Leaving it as is

**Comment by MikeMcQuaid** [comment]
Agreed. Thanks for being the squeaky wheel on these sorts of review issues, @SMillerDev!

**Comment by SMillerDev** [comment]
I'm more than happy to make issues for Issy to pick up 😄

**Comment by issyl0** [comment]
There's just something so satisfying about writing RuboCops!

**Comment by SMillerDev** [comment]
There's just something so satisfying about ~writing RuboCops~ teaching brew new ways to tell people they're wrong!
