### ISSUE TITLE
Remove Github code search from `brew search`

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/brew#15107]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Remove Github code search from our codebase and replace it with the Homebrew API. We only use this internally to search for formulas and casks with the `brew search` command and we already have that command set up to use the API right now for the core formula and cask repos.

The `Search.search_taps` and `Github.search_code` code should be removed. This will mean that we don't show casks that are not in the default cask repo in search results. This is less than ideal but can be handled in a few different ways. Either those repos can be merged together which is something we've already discussed in a few different places or we can add those to the API. The other option, of course, would be to just omit those from search results entirely unless you've tapped those repos.

### What is the motivation for the feature?

The idea here is that this doesn't work consistently unless you're using your own token and even in that case it's still inconsistent. This results in an extra network request for users that frequently doesn't return anything of value and also causes some of our online tests to be flaky. We should remove it.

### How will the feature be relevant to at least 90% of Homebrew users?

It will result in one less network request for most users and will help our CI be more consistent which will help everyone indirectly.

### What alternatives to the feature have been considered?

Only using code search if the user has a Github token to increase the likelihood that it works correctly.

**Comment by MikeMcQuaid** [comment]
Agreed, this makes sense to me.

> This will mean that we don't show casks that are not in the default cask repo in search results. This is less than ideal but can be handled in a few different ways. Either those repos can be merged together which is something we've already discussed in a few different places or we can add those to the API. The other option, of course, would be to just omit those from search results entirely unless you've tapped those repos.

Let's definitely just merge these repos. It will make things easier for everyone.

**Comment by issyl0** [comment]
> Let's definitely just merge these repos.

Should we make a new issue for this? I imagine it might take a bit of wrangling and it's a prerequisite to this issue if we don't want to break things.

To clarify, "these repos" are which ones?

**Comment by reitermarkus** [comment]
Will this not completely break searching third-party taps?

**Comment by reitermarkus** [comment]
> To clarify, "these repos" are which ones?

@issyl0, I think we somewhat agreed in https://github.com/Homebrew/formulae.brew.sh/pull/772 on merging all cask taps except `cask-fonts`.

**Comment by apainintheneck** [comment]
> Will this not completely break searching third-party taps?

I believe that it only searches Homebrew repos on Github right now.

https://github.com/Homebrew/brew/blob/c51687009428dd061a2dd90f46c11e0c7c1f9212/Library/Homebrew/search.rb#L60-L65
