### ISSUE TITLE
`CLI::Parser` should parse flag values.

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/brew#15115]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Values passed to flags should be parsed by `CLI::Parser` instead of needing to be handled in the command implementation.

For example, `--url` should parse the value and `args.url` should then return a `URI` object. If the value isn't a URL, output an error and show usage information.

Another example, `--json` is an enum and should parse whether the value is either `v1` or `v2` and then return a `Symbol`.

I assume most arguments should at least not be empty (see https://github.com/Homebrew/brew/pull/15088#discussion_r1153614651) and raise an error in that case.

### What is the motivation for the feature?

Command implementation only needs to distinguish between `nil` and a valid value for a given argument.

### How will the feature be relevant to at least 90% of Homebrew users?

Implementation detail, not relevant to users.

### What alternatives to the feature have been considered?

Changing nothing and raising a `UsageError` in the command implementation, which can get repetitive.

**Comment by MikeMcQuaid** [comment]
I don't think this should be part of `CLI::Parser` but I do think something like an `enrich_flag` method somewhere would be nice to do this.

**Comment by MikeMcQuaid** [comment]
@reitermarkus Happy to have this implemented but probably on you to do so.
