### ISSUE TITLE
Feature request: Exit status of `brew services info xxx` indicates the service status

### ISSUE THREAD

**Issue by mokeyish** [Homebrew/brew#15118]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

The process exit status of `brew services info xxx` indicates the service status.

### What is the motivation for the feature?

For shell scripting:

```shell
brew services info xxx >/dev/null 2>&1 && echo "Service Running" || echo "Service Stopped"
```

This works

```shell
 launchctl list homebrew.mxcl.xxxservice>/dev/null 2>&1 && echo "Service Running" || echo "Service stopped"
```

### What alternatives to the feature have been considered?

It is better to add `status` subcommand for `brew service`.

```shell
brew services status xxx
```

**Comment by MikeMcQuaid** [comment]
I don't think we can change the exit code here without breaking existing scripts. Either use `--json` or `grep` the `brew services list` output. Sorry, passing on this.
