### ISSUE TITLE
`tap-new` creates workflow files that use an outdated `actions/cache@v1`

### ISSUE THREAD

**Issue by muzimuzhi** [Homebrew/brew#15126]
### `brew doctor` output

```shell
irrelevant
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
irrelevant
```

### What were you trying to do (and why)?

Push to a third-party tap, which triggers workflow runs.

### What happened (include all command output)?

The workflow run throws warnings, which is caused by using outdated `actions/cache@v1`, see https://github.com/muzimuzhi/homebrew-texstudio-beta/actions/runs/4589048105
![image](https://user-images.githubusercontent.com/6376638/229358795-6ebc2697-5580-439b-94d4-8cb6f91dfb7d.png)

### What did you expect to happen?

No warnings.

Use either the latest [`actions/cache@v3`](https://github.com/actions/cache/releases), or the more aggressive `actions/cache@main`, like how `actions/upload-artifact` is used.
https://github.com/Homebrew/brew/blob/931327df1f30a3a5b1aa07657c0d1070e61988f9/Library/Homebrew/dev-cmd/tap-new.rb#L103-L108

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# incomplete
brew tap-new user/temp-tap
cd $(brew --repository)/Library/Taps/user/homebrew-temp-tap
git commit --allow-empty -m "Trigger Workflows"
git push
```

**Comment by issyl0** [comment]
Thanks for letting us know. I've got a PR up to fix this now.
