### ISSUE TITLE
Include core formulae when using `--eval-all` and the API with commands

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/brew#15122]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

The core formulae are not included in some commands like `brew info` when using `--eval-all`.

For some commands this is a problem with the `Formula.all` method which loads them from files not names. Of course, local formula files don't exist if you're only using the API. This should get updated to use formula names instead of files to load formulae. The `Formula.full_names` method might work here.

### What is the motivation for the feature?

Commands should work as expected when using the API.

### How will the feature be relevant to at least 90% of Homebrew users?

The `--eval-all` switch is used by a large number of built-in commands but only seems not to work correctly with the following ones.

- `brew deps`
- `brew info`
- `brew options`
- `brew readall`
- `brew uses`

### What alternatives to the feature have been considered?

Ignoring this...

**Comment by MikeMcQuaid** [comment]
IMO this may be a good case for just removing `Formula.all` entirely and replacing each call site which the appropriate version.
