### ISSUE TITLE
FAQ Submission Guidelines and Formula Maintainer Feedback

### ISSUE THREAD

**Issue by iwelch** [Homebrew/brew#15133]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I am looking at the FAQ.  I was trying to find out how to tell a maintainer (wxmaxima) that their package has a problem.  in this case, it is that share/wxMaxma/fonts/isMath-cmti10.ttf is not included, which always causes a bad alert starting up wxmaxima.  (works afterwards, though).  I also think the guideline printed (of setting in preferences) is outdated.

the general brew FAQ should give a description of how to do this (or not to do this).

I then thought, ok, let me request adding this to the FAQ.  alas, again, the general brew FAQ does not tell me how to do this.  so I found my way here.

### What is the motivation for the feature?

clarify methods of feedback

### How will the feature be relevant to at least 90% of Homebrew users?

yes.  it should help.

### What alternatives to the feature have been considered?

nothing.  this is a documentation request that should be easy to do.

**Comment by MikeMcQuaid** [comment]
This is already documented. Not adding to the FAQ because it's not FA (frequently asked): https://docs.brew.sh/Troubleshooting
