### ISSUE TITLE
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!

### ISSUE THREAD

**Issue by 9mm** [Homebrew/brew#15132]
### `brew doctor` output

```shell
➜  ~ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 931327df1f30a3a5b1aa07657c0d1070e61988f9
Last commit: 3 days ago
Core tap JSON: 03 Apr 14:16 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Update homebrew

### What happened (include all command output)?

It fails to update, the link is not found

### What did you expect to happen?

It updates

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
```

**Comment by MikeMcQuaid** [comment]
https://formulae.brew.sh/api/formula.jws.json loads for me. Try again?

**Comment by ciranor** [comment]
Was failing for me at the same time as the original ticket, and yeah, works now. Cheers.

**Comment by fvm** [comment]
I came here with the same issue. It does indeed load now, but it gave a 404 until moments ago. (FWIW)

And, naturally, `brew update --auto-update` also works as expected again (on my end).
