### ISSUE TITLE
"brew list --versions" should follow formula-name aliases

### ISSUE THREAD

**Issue by zbentley** [Homebrew/brew#1514]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X/n/a] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Propose a feature:

`brew list --versions` should "follow" aliases.

When a formula has an alias (say `mobile-shell <-> mosh`), `brew list` and `brew info` for the formula *or* the alias displays the same info entry. `brew search` also "follows" the alias. `brew search` also displays a check-mark if the formula *or* the alias is supplied.

However, `brew list --versions` is inconsistent with this behavior; `brew list --versions $alias` returns nothing, even if a formula was installed under an aliased name, while `brew list --versions $real-name` returns the correctly installed version.

*Specific feature proposal:*
- `brew list --versions;` behaves exactly as before, and lists all installed formulae by their "true" names.
- `brew list --versions $formula;` will "follow" aliases and perform the `list` operations on the "true" formula. Thus, `brew list --versions mosh` and `brew list --versions mobile-shell` will return the exact same output.
- Optional: a flag for `brew list` that enables the display of aliases next to true names, e.g. `brew list --versions --show-aliases;` results in the normal list, but with aliased packages appearing like `mobile-shell (mosh,otheralias) 1.2.6_3` or similar.

**Comment by zbentley** [comment]
This might be a subset of/end up being fixed under #620; I'm not sure.

**Comment by vladshablinsky** [comment]
Both work for me.

```
➜ vlad:~$ brew list mobile-shell
/usr/local/Cellar/mobile-shell/1.2.6_3/bin/mosh
/usr/local/Cellar/mobile-shell/1.2.6_3/bin/mosh-client
/usr/local/Cellar/mobile-shell/1.2.6_3/bin/mosh-server
/usr/local/Cellar/mobile-shell/1.2.6_3/etc/bash_completion.d/mosh
/usr/local/Cellar/mobile-shell/1.2.6_3/share/man/ (3 files)
➜ vlad:~$ brew list mosh
/usr/local/Cellar/mobile-shell/1.2.6_3/bin/mosh
/usr/local/Cellar/mobile-shell/1.2.6_3/bin/mosh-client
/usr/local/Cellar/mobile-shell/1.2.6_3/bin/mosh-server
/usr/local/Cellar/mobile-shell/1.2.6_3/etc/bash_completion.d/mosh
/usr/local/Cellar/mobile-shell/1.2.6_3/share/man/ (3 files)
```

**Comment by zbentley** [comment]
Looks like it's localized to `brew list --versions $PACKAGE`. Updating description and title to reflect that. Thanks!
