### ISSUE TITLE
`brew search` searches tapped files instead of the API

### ISSUE THREAD

**Issue by llimllib** [Homebrew/brew#15153]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  pycparser
  erdtree
  trurl
  szip

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  tcl-tk
  python@3.11
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.11-52-g97d7a5c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 97d7a5c9b4d55f93fa87ccf33526bbd231ba168a
Last commit: 9 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6150d43818deed257e0121e1fa6bbbeb1a7e5c14
Core tap last commit: 10 weeks ago
Core tap branch: master
Core tap JSON: 05 Apr 01:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/nvim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### What were you trying to do (and why)?

Search for the `erdtree` package

### What happened (include all command output)?

```
$ brew search erdtree
Error: No formulae or casks found for "erdtree".
```

### What did you expect to happen?

`brew search` should find the package from the API json, but instead it searches the formula files which are no longer updated.

In [this issue](https://github.com/orgs/Homebrew/discussions/4381) I followed the chain of why this was occurring; I'm not sure how `brew search` is supposed to be using the API instead of the core tap files, but I debugged into it and it's definitely using the core tap files.

> the search method [here](https://github.com/Homebrew/brew/blob/97d7a5c9b4d55f93fa87ccf33526bbd231ba168a/Library/Homebrew/search.rb#L100) searches all formula names given by Formula.full_names [here](https://github.com/Homebrew/brew/blob/97d7a5c9b4d55f93fa87ccf33526bbd231ba168a/Library/Homebrew/formula.rb#L1832), which in turn calls CoreTap.instance.formula_names [here](https://github.com/Homebrew/brew/blob/97d7a5c9b4d55f93fa87ccf33526bbd231ba168a/Library/Homebrew/tap.rb#L590), which in turn calls formula_files.map(&method(:formula_file_to_name)), which plainly reads the formula files and returns their names.

This is also (I presume) why `brew doctor` is telling me that `pycparser`, `erdtree`, `trurl`, and `szip` do not have formulae - it is searching the outdated core tap instead of the API.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. tap the core formula and reset your core tap to commit `6150d43`
2. `brew search erdtree`
3. note that it does not show up, though it is available in the API
4. This leads to the confusing situation that `brew info erdtree` tells me that it's installed, but `brew search erdtree` fails and `brew doctor` tells me that the formula is missing
```

**Comment by apainintheneck** [comment]
Good catch! The problem seems to be that we're deferring to the local core tap even when using the API.

https://github.com/Homebrew/brew/blob/97d7a5c9b4d55f93fa87ccf33526bbd231ba168a/Library/Homebrew/tap.rb#L988-L1003

This is the offending code. It was changed when adding the API to search a few months ago in https://github.com/Homebrew/brew/pull/14407. It seems like we should probably just remove the `installed?` check here. Even if you do have the core tap installed locally you wouldn't expect it show up in search results unless you've set `HOMEBREW_NO_INSTALL_FROM_API`. The important thing is to make sure this change doesn't affect anything else though.

**Comment by MikeMcQuaid** [comment]
> It seems like we should probably just remove the `installed?` check here.

Agreed.



> The important thing is to make sure this change doesn't affect anything else though.

It probably/may well but: it also should, for consistency 😁

**Comment by llimllib** [comment]
Thank you for the quick fix! I can confirm that it works for search.

`brew doctor` is still incorrect, I will file a separate issue about that.
