### ISSUE TITLE
`brew bump-cask-pr` Multi-arch casks only updating one arch

### ISSUE THREAD

**Issue by razvanazamfirei** [Homebrew/brew#15167]
### What were you trying to do (and why)?

Bump casks with the following stanza: 

```
on_arm do
    version "3.15.6.427,7c306041a6c1ed4458be3347e70c68a6"
    sha256 "e85e38e74f3692c17765ce92fe905b239f8fbeda22986fe0258b7def654959ff"
  end
  on_intel do
    version "3.15.6.427,8d3e803535ce65abb7edb972e2e0d144"
    sha256 "de0b5c435c7aa8c90c909c4e533d55229caca223d359993660c431419f85b11c"
  end
```

### What happened (include all command output)?

Only one arch was updated.

### What did you expect to happen?

Both archs are updated

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew bump-cask-pr [cask] --version` or `brew bump --cask [cask] --open-pr`
```

This is similar to https://github.com/Homebrew/brew/issues/13713, yet occurs in situations where the sha256 and versions are nested in a `on_arch` block. Partial fix in https://github.com/Homebrew/brew/pull/13718.

Example PRs where this happened: https://github.com/Homebrew/homebrew-cask/pull/140762, https://github.com/Homebrew/homebrew-cask/pull/144283, https://github.com/Homebrew/homebrew-cask/pull/144282, https://github.com/Homebrew/homebrew-cask/pull/140644, https://github.com/Homebrew/homebrew-cask/pull/144687

**Comment by MikeMcQuaid** [comment]
Thanks @razvanazamfirei, we should fix this. As a maintainer, you may be best placed to do this!
