### ISSUE TITLE
API installs do not handle `plist_name`

### ISSUE THREAD

**Issue by jasonhemann** [Homebrew/brew#15175]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/jasonhemann/821e327dc2606424874915af244ceda7

Note that several of the `brew doctor` warnings are incorrect, including the ones about brew's `bin` and `sbin` not being on path.
```

### Verification

- [ ] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`dbus.rb` installs the plist file as `org.freedesktop.dbus-session.plist`. Following the discussion at https://github.com/orgs/Homebrew/discussions/2318 , it should be `homebrew.mxcl.dbus.plist`. 

Presently, executing `brew services start dbus` fails with an error message.
After `cp org.freedesktop.dbus-session.plist homebrew.mxcl.dbus.plist`, and using sudo, services seems to start just fine.

### What happened (include all command output)?

dbus seems to install just fine, but it looks like the plist doesn't have the appropriate name https://github.com/orgs/Homebrew/discussions/2318

### What did you expect to happen?

Truthfully, I expected to find the plist linked into ~/Library/LaunchAgents/ . 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install dbus
brew services start dbus
cp $(brew --prefix dbus)/org.freedesktop.dbus-session.plist $(brew --prefix dbus)/homebrew.mxcl.dbus.plist
sudo brew services start dbus
```
```

**Comment by apainintheneck** [comment]
It looks like this was just never handled by the API and by your linked discussion it might have been broken before that (https://github.com/orgs/Homebrew/discussions/2318). There are only two formulae that overwrite this method in `homebrew/core` though and the systemd equivalent `service_name` is never overwritten at all.

We could include this in the API JSON but it seems to me like a lot of effort for only two formulae. Is there any other way we can handle this sort of thing?

```
/u/l/H/L/T/h/homebrew-core (master|✔) $ git grep -A 2 'def plist_name'
Formula/dbus.rb:  def plist_name
Formula/dbus.rb-    "org.freedesktop.dbus-session"
Formula/dbus.rb-  end
--
Formula/xinit.rb:  def plist_name
Formula/xinit.rb-    "homebrew.mxcl.startx"
Formula/xinit.rb-  end
```

Maybe we could rename the plist during bottling?

**Comment by carlocab** [comment]
> Maybe we could rename the plist during bottling?

That possible. I don't know if the software cares what the plist is named though. It might; it may not. I'd bet on not, for sufficiently small stakes.

**Comment by MikeMcQuaid** [comment]
> Maybe we could rename the plist during bottling?

Yes, that makes sense to me.

> I don't know if the software cares what the plist is named though

I think for `org.freedesktop.dbus-session` it might but agreed for `xinit` it won't.

**Comment by Bo98** [comment]
> Maybe we could rename the plist during bottling?

The plist isn't really used by homebrew-services, but adding to the API JSON seems extremely trivial to do.

**Comment by apainintheneck** [comment]
Another option might be to add a symlink to original service file as mentioned here (https://docs.brew.sh/Formula-Cookbook#service-files).

```rb
prefix.install_symlink "file.plist" => "#{plist_name}.plist"
prefix.install_symlink "file.service" => "#{service_name}.service"
```

Not sure if this works at all with API installs right now and this pattern isn't present in core even though it's in the docs.

**Comment by Bo98** [comment]
We probably need to support something but that doesn't mean it has to be in its current DSL form. If we're embedding into the API then we cannot allow any dynamic elements so overriding a method makes less sense.

**Comment by apainintheneck** [comment]
I guess I'm wondering if the symlink strategy mentioned above is our preferred way to handle this sort of situation since it's already in the docs and should work with the API, I think.

**Comment by MikeMcQuaid** [comment]
@apainintheneck Worth a try 😁 🤞🏻

**Comment by apainintheneck** [comment]
The symlink option doesn't seem to work that well at all.

```
/u/l/H/L/T/h/homebrew-core (dbus-symlink-plist|✚1) $ brew services start dbus
==> Successfully started `dbus` (label: homebrew.mxcl.dbus)
/u/l/H/L/T/h/homebrew-core (dbus-symlink-plist|✚1) $ brew services list
Name  Status User        File
dbus  none   kevinrobell 
redis none               
/u/l/H/L/T/h/homebrew-core (dbus-symlink-plist|✚1) $ brew services stop dbus
Warning: Service `dbus` is not started.
```

I'm not even sure we should be recommending this since the only part of `brew services` that seems to work with it is the start command. Essentially, it looks for the wrong label so things don't work as expected.

**Comment by MikeMcQuaid** [comment]
> I'm not even sure we should be recommending this

Agreed. If we do anywhere: let's remove the documentation and consider printing a deprecation notice.

**Comment by apainintheneck** [comment]
I feel like we should probably just add this to the service block and then it will get included with the API. The important thing is to make it backwards compatible in case someone outside of the core repo is using a similar pattern in their package definitions.

```rb
service do
  plist_name "name"
  service_name "name"
end
```

This would require some changes with how we check for commands before writing new service files since we shouldn't actually do any of that without a `run` command defined in the service block. It also might require some changes to `brew services` for a similar reason. The point is that if we want to actually support this use case going forward we should give people a better API that is easier to use and also explicitly supported (remember the current use case is never mentioned in the docs).

**Comment by MikeMcQuaid** [comment]
> I feel like we should probably just add this to the service block and then it will get included with the API.

Works for me 👍🏻 



> This would require some changes with how we check for commands before writing new service files since we shouldn't actually do any of that without a `run` command defined in the service block. It also might require some changes to `brew services` for a similar reason.

Agreed 👍🏻 



> The point is that if we want to actually support this use case going forward we should give people a better API that is easier to use and also explicitly supported (remember the current use case is never mentioned in the docs).

Also agreed 👍🏻
