### ISSUE TITLE
Adapt downloading progress bar to terminal size

### ISSUE THREAD

**Issue by kraktus** [Homebrew/brew#15179]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Currently when the lateral size of the terminal is too small, the progress bar visually breaks like this:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/56031107/230777113-c358027d-d354-45db-8928-18454cf2aa38.png">
(I've resized my terminal since so this might not 100% be the exact visual but the issue look the same)

instead of downsizing its length.

### What is the motivation for the feature?

This fill up the terminal screen and make it unpleasant to find back previous command outputs.

### How will the feature be relevant to at least 90% of Homebrew users?

Many devs split their screens for better productivity. This happen probably more often on MacBook Air than other hardware though due to overhaul smaller screen size. 

### What alternatives to the feature have been considered?

Status quo, this is a minor issue.

**Comment by apainintheneck** [comment]
I believe that this status bar is printed out by curl so we'd have to see if there is some way to set the terminal size when calling curl.

**Comment by carlocab** [comment]
This doesn't happen to me, though, despite also running a MacBook Air with a tiny screen.

**Comment by ZhongRuoyu** [comment]
This may happen when the terminal is resized during the download.

**Comment by MikeMcQuaid** [comment]
Passing on this, it's a feature request for `curl` and not us really.

**Comment by kraktus** [comment]
> This doesn't happen to me, though, despite also running a MacBook Air with a tiny screen.
> This may happen when the terminal is resized during the download.

This happens even without resizing the terminal when you split your screen
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/56031107/231872260-e66e7a1e-c6fe-4a9a-8222-c1ded320854a.png">

Thank you for the redirection, will follow up in curl.

**Comment by kraktus** [comment]
@MikeMcQuaid After troubleshooting with `curl` maintainers, this appears to be a brew-specific issue. See following video where a bare curl progress bar works properly but brew one's is broken:

![](https://user-images.githubusercontent.com/56031107/232594120-c3d8987b-6bb6-40d5-a9c5-39777f7d1dc0.mov)

[Raw link](https://user-images.githubusercontent.com/56031107/232594120-c3d8987b-6bb6-40d5-a9c5-39777f7d1dc0.mov) if embed failed.

Output of `brew doctor`:
```
brew doctor          
Your system is ready to brew.
```

Output of `brew config`:
```
HOMEBREW_VERSION: 4.0.14-23-g8548ea1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8548ea17d72a336a7068f221fd132758a4bf2610
Last commit: 66 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e81b712dfaf458002cb70fd7de10f343778540d0
Core tap last commit: 8 weeks ago
Core tap branch: master
Core tap JSON: 17 Apr 19:32 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: subl -w
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_GOOGLE_ANALYTICS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

The issue triggers when the terminal is narrower than 80 columns (excluded)

**Comment by reitermarkus** [comment]
This seems to be a limitation of Ruby's `Open3`, which doesn't seem to inherit the TTY width and hard-codes it to 80, e.g.

```sh
$ ruby -r open3 -e 'p Open3.capture3("/usr/bin/tput cols 2")'
["80\n", "", #<Process::Status: pid 6448 exit 0>]
```
