### ISSUE TITLE
[Analytics] Why Google Analytics? Keen IO would be better – enable stats for packages

### ISSUE THREAD

**Issue by nemo** [Homebrew/brew#152]
One thing I love about [npm](https://npm.org) is the fact that there are stats about every package on their system.

They can afford doing stuff like that since they're a corporation. But I think Homebrew could do the same by using something like [Keen IO](https://keen.io) to track everything and either give out the read key to the community (so people can judge the packages in terms of their download popularity etc.) or create a simple service to show stats on packages to maintainers or the community at large.

I believe they offer a free for OSS deal – so it won't cost anybody anything (other than the time cost to switch from Google to Keen IO) and I for one would love to see it happen.

$5 says if we email them, we can actually get them to help with the integration 💯

**Comment by bfontaine** [comment]
That sounds interesting. Note we already have public stats on bottles (i.e. precompiled packages) via Bintray, e.g.: https://bintray.com/homebrew/bottles/git/view#statistics

**Comment by chr4** [comment]
Google is certianly one of the worst options privacy wise, even though I think Homebrew shouldn't track its users (at least not without an opt-in). I tried explaining my point in [a post](http://chr4.org/blog/2016/04/26/homebrew-betrayed-us-all-to-google/) (including a somewhat clickbaity title)

Please reconsider this change, don't hurt the internet.

**Comment by bfontaine** [comment]
@chr4 If you know of any alternative to Google Analytics that doesn’t require more work on our side and have the same functionalities we’re all ears.

**Comment by nemo** [comment]
@bfontaine cool! Hadn't seen that. Kind of what I was looking for (though I have to go through 3 clicks to get the data)

Anyway – implementing Keen IO shouldn't take any more time than Google Analytics did. I'm surprised GA can support non-web tracking – I expect half the dashboards to be completely useless on it.

I just think it'd be cool to expose the data eventually to the community so others can learn from it and understand homebrew's scale :)

**Comment by mikemcquaid** [comment]
@chr4 Your comment does not relate to this issue.

**Comment by mikemcquaid** [comment]
@nemo Thanks for the issue. A few questions:

- How long has Keen IO been around and what's their revenue model like? I want to avoid moving somewhere that doesn't exist in a year.
- Have you personally used it? Do you like it? Can you make an introduction?
- Can you link to e.g. the OSS plan?

Thanks for this; definitely open to other options here.

**Comment by nemo** [comment]
@mikemcquaid Anytime! Here's a few responses:

- Keen IO has been around for a few years and as far as I know – they're going pretty strong.
- I've been a user through 3 separate companies in the past 4 years and we're currently a user at [Suto](https://asksuto.com) and *very* happy with it :)
- I can definitely make an introduction to someone there – they have a few community folks who could probably help out here. cc: @timfalls 
- Look for "Open Sourcer?" in on [this page](https://keen.io/plans/) for the OSS plan.

**Comment by elof** [comment]
Hey all. I'm a community person from Keen and would be happy to help out. We support OSS projects with free upgraded accounts (but not unlimited).

To answer some of @mikemcquaid's questions.

- The company was founded in Jan of 2012 (went through Techstars) and we are backed by Sequoia. 
- Our business model for small volume accounts (<15million events/month) is to charge for volume, for large volume accounts there can be many factors that go into what we charge.

Here are some examples of OSS teams that we work with: https://github.com/keen/community-team/blob/master/community-projects.md

**Comment by mikemcquaid** [comment]
Thanks @nemo and @elof. That sounds interesting and I'll check it out more.

**Comment by ismailbaskin** [comment]
Google analtytics niye kullanıyonuz olum mal mısınız? Hadi kullanıyonuz insan bir sorar. Yapacağınız işe tüküreyim

**Comment by bfontaine** [comment]
@ismailbaskin Mind translating that in English?

**Comment by anapsix** [comment]
> you know of any alternative to Google Analytics that doesn’t require more work on our side and have the same functionalities we’re all ears.
@bfontaine, imho, keep Google Analytics, just stop quietly enabling tracking for everyone

**Comment by mikemcquaid** [comment]
Anyone else who comments on this thread to complain about our analytics rather than to discuss Keen.io specifically will have their comment deleted and be blocked from the Homebrew organisation temporarily. I want to talk to @nemo and @elof here so cannot lock this thread.

**Comment by chr4** [comment]
While I can understand you want to keep this Issue productive, I find it disturbing how Homebrew deals with massive complaints from an open-source loving community (see HN, Reddit, etc. discussions).
Don't just delete this away and hope everybody just forgets about this.

I know this will probably be deleted in a minute and you guys will probably ban me, but I'm still writing this so people get notified via email/ etc.

There are people out there for whom this is a serious issue. I beg you do not take this lightly.
I want to tell people "Homebrew is good, use it" and not "Homebrew is kinda good, but before you use it make sure to paste this-and-this in your terminal and also block this and that, otherwise you'll be tracked".

**Comment by mikemcquaid** [comment]
@elof Not sure about monthly events yet but got 1,151,671 total events last week. Would this be too many for Keen to handle for free?

**Comment by elof** [comment]
@mikemcquaid that data amount shouldn't be a problem, but I'd like to connect with you to discuss how you plan to surface the data (i.e. what queries you will be running and where the metrics will be embedded)

**Comment by mikemcquaid** [comment]
@elof Ok, feel free to email me at mike@mikemcquaid.com or just chat here. Where's not sure yet what queries we'll be running but most likely just aggregates e.g. how many people did X vs Y.

**Comment by elof** [comment]
Ok, that sounds fine. Do you plan on embedding any of the metrics places
where the public would view?

**Comment by mikemcquaid** [comment]
We do not but we were thinking of providing people with either sporadic data dumps or the read-only key to the data.

**Comment by elof** [comment]
@mikemcquaid 👍 hit me up when you start sending data so I can update your account.

**Comment by mikemcquaid** [comment]
@elof Is there anything else I need to know or do? Just want to make extra sure we're not going to hit any limits in the medium-long term and we'll be able to run queries on that data OK in a performant fashion. Thanks!

**Comment by elof** [comment]
@mikemcquaid all set. When you start running queries that you know you are going to run on a regular basis create a saved query and make sure it's cached. They will be 🏇

**Comment by MikeMcQuaid** [comment]
Thanks for all the input folks. I've played around with the implementation here but we've decided to not move to Keen at this time for a few reasons that I'm happy to detail privately. I am going to look into providing sporadic community data dumps of Google Analytics so our community can check out the data. Thanks!
