### ISSUE TITLE
postgresql fails to start when attempt uses launchd via brew services

### ISSUE THREAD

**Issue by rails-smith** [Homebrew/brew#1521]
After a successful installation of postgres 9.5.4_1

Starting postgres with a direct command starts the server as expected:
pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start

Trying to start with launchd services through the brew interface:
$ brew services start postgresql
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)

system.log:

Nov 15 19:14:19 lapster com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql): This service is defined to be constantly running and is inherently inefficient.
Nov 15 19:14:19 lapster com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql[16325]): Service could not initialize: 15G1108: xpcproxy + 12684 [1462][F7717708-ACF7-307D-B04E-998DFC36598F]: 0xd
Nov 15 19:14:19 lapster com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

Nov 15 19:14:29 lapster com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql[16357]): Service could not initialize: 15G1108: xpcproxy + 12684 [1462][F7717708-ACF7-307D-B04E-998DFC36598F]: 0xd
Nov 15 19:14:29 lapster com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Nov 15 19:14:39 lapster com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql[16362]): Service could not initialize: 15G1108: xpcproxy + 12684 [1462][F7717708-ACF7-307D-B04E-998DFC36598F]: 0xd
Nov 15 19:14:39 lapster com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Nov 15 19:14:49 lapster com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql[16364]): Service could not initialize: 15G1108: xpcproxy + 12684 [1462][F7717708-ACF7-307D-B04E-998DFC36598F]: 0xd
Nov 15 19:14:49 lapster com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Also, please try to run it outside of `launchctl` and tell me if it works.

Thanks!

**Comment by rails-smith** [comment]
Hi Mike,

Thank you for your time to respond.

I am unable to follow the procedure on the previous instance of the server
installation, as it is now permanently removed from the file system.

The behavior was consistently the same on both macOS 10.11 and 10.12.
(sorry for not mentioning the OS versions affected)

Indeed, one of my first sentences in my report was the fact the postgresql
database runs flawlessly when started manually. Maybe you missed that. I
used it with a a few local rails applications that are under development.

thx very much!

**Comment by MikeMcQuaid** [comment]
We need the troubleshooting information on one machine to be able to help here. Closing until we have it.
