### ISSUE TITLE
`brew info --eval-all --json=v2` no longer works

### ISSUE THREAD

**Issue by rhomolka-drw** [Homebrew/brew#15227]
### `brew doctor` output

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  pycparser
  cffi

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  kubeval
  mermaid-cli
  octant

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  bash-completion

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 4.0.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9b60fcf7ac3f82fa589a64091376d0663262f8c6
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f99da7e0c611bd09762fdbf4b6edcc8db7ff393d
Core tap last commit: 8 weeks ago
Core tap branch: master
Core tap JSON: 14 Apr 16:02 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Bl9VQZwLeV/org.xquartz:0
HOMEBREW_EDITOR: codew
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
```

### What were you trying to do (and why)?

Dump a full list of formulae to grep for a new formula

### What happened (include all command output)?

$ brew info --eval-all --json=v2
Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/asdf.rb:33

Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/csound.rb:167

Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg@1.4.rb:77

Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jenv.rb:27

Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lesspipe.rb:33

Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nvm.rb:38

Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:91

Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/piknik.rb:31

Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/resty.rb:55

Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby-build.rb:37

Warning: Calling shell_profile is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/homebrew-core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/virtualenvwrapper.rb:62

Error: no implicit conversion of nil into Hash
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:260:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `refresh'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:86:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:76:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:387:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:125:in `block in os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:310:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:110:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

### What did you expect to happen?

Dump a parseable JSON file

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew info --eval-all --json=v2
```

**Comment by reitermarkus** [comment]
What taps do you have installed (`brew tap`)?

**Comment by rhomolka-drw** [comment]
armosec/kubescape
fluxcd/tap
hashicorp/tap
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
minio/stable

**Comment by reitermarkus** [comment]
Seems to be API related, since it doesn't happen when `HOMEBREW_NO_INSTALL_FROM_API=1` is set.

I can reproduce it with `brew info apparency --json=v2`.

That cask `depends_on macos: ">= :mojave"`, but the `Cask#os_versions` loops through all macOS versions, which seems to be the cause.

cc @Rylan12

**Comment by Rylan12** [comment]
We should probably just remove `os_versions`. I don't think we use it anywhere except `Cask#to_h` and it's pretty much obsolete now that we have `SimulateSystem`
