### ISSUE TITLE
`brew casks` does not show casks from external taps unless HOMEBREW_NO_INSTALL_FROM_API is set

### ISSUE THREAD

**Issue by Omoeba** [Homebrew/brew#15229]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.13-21-g2816c12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2816c1274fa1c29cdb1797222c23fc89e9b58e80
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b14bb2000244736319a529372f257198a5704c0c
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 14 Apr 15:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.QpHrGATtgF/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### What were you trying to do (and why)?

I was trying to list all casks available to install. This issue also affects zsh completions since it uses `brew casks` internally.

### What happened (include all command output)?

Only casks from the homebrew/cask tap were listed.

### What did you expect to happen?

All casks from all taps are listed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap homebrew/cask-fonts
brew casks | grep font-
export HOMEBREW_NO_INSTALL_FROM_API=1
brew casks | grep font-
```

**Comment by apainintheneck** [comment]
Yeah, we only show the lists of casks and formulae available from the API with the `brew casks` and `brew formulae` commands right now. We should probably add those to the casks/formulae found in local non-core taps.

- https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/formulae.sh
- https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/casks.sh
