### ISSUE TITLE
Homebrew for Linux on musl libc

### ISSUE THREAD

**Issue by marfier** [Homebrew/brew#15222]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Homebrew for Linux currently only runs on glibc-based Linux systems.

Many lightweight Linux distributions, in particular embedded and container Linux distros like Alpine Linux and OpenWrt, use musl instead of glibc as their libc implementation.

Running the installation script on a musl-based Linux system outputs the following:
```
root@OpenWrt:~# ./install.sh 
musl libc (x86_64)
Version 1.2.3
Dynamic Program Loader
Usage: ldd [options] [--] pathname
Homebrew requires Ruby 2.6 which was not found on your system.
Homebrew portable Ruby requires Glibc version 2.13 or newer,
and your Glibc version is too old. See:
  https://docs.brew.sh/Homebrew-on-Linux#requirements
Please install Ruby 2.6 and add its location to your PATH.
root@OpenWrt:~# 
```
(Not important, but Ruby _is_ installed.)

The Ruby runtime, and most formulae, have already been ported for musl Linux.

### What is the motivation for the feature?

To allow Homebrew to run in container or embedded Linux systems like Alpine Linux or OpenWrt, which use musl instead of glibc.

### How will the feature be relevant to at least 90% of Homebrew users?

Whoever wants to install a package manager on a container or embedded Linux system will find it useful. Not sure how many people exactly.

### What alternatives to the feature have been considered?

The stock package managers, such as `apk` for Alpine and `opkg` for OpenWrt. Some embedded Linux systems do not even come with a package manager.

**Comment by MikeMcQuaid** [comment]
None of our binary packages would work in this situation and we don't support compiling from source so: no, sorry, can't/won't support this and passing on it.
