### ISSUE TITLE
brew shrc to eval in ~/.profile.

### ISSUE THREAD

**Issue by cederom** [Homebrew/brew#15233]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

* There is a `brew shellenv` command that can be `eval` in `~/.profile` but it only provides limited amount of variables.
* User needs to enter manually `PATH`, `CFLAGS`, `CPPFLAGS` etc for every single package of interest.
* It would be nice if `brew shvars` could be implemented that would auto generate all necessary variables for installed packages that would be then `eval` inside `~/.profile`.
* I know that would produce long environment strings but also it would result in only two lines in `~/.profile`.
* I know that `~/.profile` can be  used by different shells (i.e. `bash`, `zsh`, `csh`) but syntax generation could be automated too I guess.
* Users that do not want to use that option still can put all variables in `~/.profile` by hand.

### What is the motivation for the feature?

* It is painful to provide every single ~/.profile variable when working with brew for every single application.
* It is even more painful when doing automation on a bare metal install.
* It is easy to skip some variables that results in incoherent environment (i.e. some packages are used from brew and some are the system ones with different versions / functionality than expected).

### How will the feature be relevant to at least 90% of Homebrew users?

* Easy scripting and bootstrapping of the automated build environments.
* Only two brew related lines in `~/.profile`.
* Coherent development environment with all-from-brew setup.

### What alternatives to the feature have been considered?

* No such command / functionality exists at this time that I am aware of.
* `brew shellenv` provides only limited scope of variables and not related to installed packages.
* Environment setup right now is a painful every single application type into the `~/.profile`.

**Comment by MikeMcQuaid** [comment]
> * User needs to enter manually `PATH`, `CFLAGS`, `CPPFLAGS` etc for every single package of interest.

Yes but that varies from project to project. Homebrew cannot know what these are. `brew bundle exec` sets some of these for you, though.

Passing on this as the scope is too large and the request to niche, sorry. As mentioned: check out `brew bundle exec` which may help with some of this.
