### ISSUE TITLE
Installing brew changed my XCode path

### ISSUE THREAD

**Issue by eseidel** [Homebrew/brew#15254]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: ac0663ae5d2d4c76bb62363592d77dbad49ac30c
Last commit: 32 hours ago
Core tap JSON: 17 Apr 17:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### What were you trying to do (and why)?

I installed brew this morning and installed one package `bundletool`.  Before that, xcodebuild worked.  After it doesn't.  I read through the bundletool.rb code and it doesn't look like it does anything with xcode-select, but brew does. :)

Now xcodebuild says:
`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

### What happened (include all command output)?

See above.

### What did you expect to happen?

I expected `xcodebuild` to still work after installing brew.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Would require installing on a fresh machine, I suspect.
```

**Comment by eseidel** [comment]
I fixed my install with `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`, but if this was really brew's fault (which I don't see how anything else could have caused this?) then filing this since many other developers may not be so familiar with xcode-select.

**Comment by eseidel** [comment]
Actually `sudo xcode-select -r` would have been better for me to have used.

**Comment by MikeMcQuaid** [comment]
This is intentional behaviour for us to change this on installation:

https://github.com/Homebrew/install/blob/fc8acb0828f89f8aa83162000db1b49de71fa5d8/install.sh#L809-L821

 As you noted, it's easy to switch it back for those users who care.
