### ISSUE TITLE
How should installed dependency resolution handle versions?

### ISSUE THREAD

**Issue by alyssais** [Homebrew/brew#1525]
Currently, keg _A_ is only [considered](https://github.com/Homebrew/brew/blob/e6933b90dc750dc9aadb3bfb6acf1bf395942d57/Library/Homebrew/keg.rb#L349) to be a dependency of keg _B_ if the version of _A_ listed in _B_'s install receipt matches _A_'s version.

This means that, after a `brew upgrade`, the installed dependency resolution might not work any more.

My thinking is that it would be more correct to say _B_ depends on _A_ if _A_ is the currently linked keg for its formula (and maybe if _A_'s version is >= the version of _A_ that _B_ was installed with?).

I'm not entirely sure if I've thought this wrong properly, though, so I'm looking for feedback on this before I try to fix it.

This _might_ be what's causing #1524, but I'm not sure yet.

**Comment by MikeMcQuaid** [comment]
> Currently, keg A is only considered to be a dependency of keg B if the version of A listed in B's install receipt matches A's version.

What would be the downsides of ignoring versions entirely here?

**Comment by alyssais** [comment]
I'm not sure. It feels wrong that we'd consider a _B_ to depend on _A_ if _A_ is older than the version in _B_'s install receipt, but if _B_ is the linked version I guess that doesn't matter..

I think we probably should ignore versions, but only consider the linked version of a keg to have dependents.

**Comment by MikeMcQuaid** [comment]
> I think we probably should ignore versions, but only consider the linked version of a keg to have dependents.

Yep, sounds sensible.
