### ISSUE TITLE
Some tests are run multiple times

### ISSUE THREAD

**Issue by alyssais** [Homebrew/brew#1526]
Here's a weird one (wow, I'm getting a lot of these today!): some of our tests are being run twice, when they shouldn't be.

Here's a simplified example of when it happens:

```ruby
class ATest < Homebrew::TestCase
  def setup
    # some fancy setup
  end

  def test_foo
    # …
  end
end

class BTest < ATest
  def setup
    super # get all A's fancy setup
    # some more fancy setup
  end

  def test_bar
    # …
  end
end
```

Rather counterintuitively (to me, at least), `test_foo` is run twice! Once on an `ATest` instance, and once on a `BTest` instance.

Now, usually, this wouldn't be much of a problem (other than the wasted time), but because `test_foo` isn't designed to be run in `BTest`'s environment, it can fail on the second run (it's really just luck that this hasn't been a problem before (to my knowledge)), when it shouldn't even have been run in the first place.

Instead, we need something like this:

```ruby
class ATestCase < Homebrew::TestCase
  # …
end

class ATest < ATestCase
  # …
end

class BTest < ATestCase
  # …
end
```

This is pretty clunky, but there doesn't seem to be a good way to do this with Minitest.

I think maybe I recall some discussion of transitioning Homebrew's tests to use `Minitest::Spec`. Was anything ever decided there? That would solve the problem because we could use contexts.

**Comment by alyssais** [comment]
Oops, hit the create issue button before I'd finished writing the description. I've finished writing it now!

**Comment by MikeMcQuaid** [comment]
> Rather counterintuitively (to me, at least), test_foo is run twice!

That's weird. Is this the case without using `parallel_test`? Has this always been the case or is a recent regression? Does it always/sometimes run a test twice? Would be great to try and have a failing PR that reproduces this.

**Comment by alyssais** [comment]
I read through the Minitest source and it doesn't look like it does anything to prevent this. It's unlikely that it's a parallel_test issue because these tests tend to be in the same file, and it parallel_test works at a file level — it doesn't know about individual tests.

#1527 fails because of this if dfbf07f isn't included. I can put that up as a separate PR if you want, but all you need to do to see the failure is drop that commit.

**Comment by MikeMcQuaid** [comment]
I guess what I'm trying to understand is: why does this happen for certain tests but not e.g. every test? It's any time you use `super`?

**Comment by alyssais** [comment]
Nothing to do with `super`. It's the fact that, when you subclass a test class, you inherit all the test methods. And Minitest doesn't differentiate between test methods declared on a class, and methods it inherited from a superclass.

**Comment by MikeMcQuaid** [comment]
Ok, I'm confused by: 
```
class ATest < Homebrew::TestCase
...
class BTest < Homebrew::TestCase
```

Did you mean:
```
class ATest < Homebrew::TestCase
...
class BTest < ATest
```

?

**Comment by alyssais** [comment]
Gah, yes, sorry

**Comment by alyssais** [comment]
I will update the issue body so I don't confuse anyone else.

**Comment by MikeMcQuaid** [comment]
Gotcha, makes a lot more sense to me now 😆

**Comment by MikeMcQuaid** [comment]
@alyssais Is this still a problem with RSpec?

**Comment by alyssais** [comment]
Nope! :D
