### ISSUE TITLE
SSL Padding

### ISSUE THREAD

**Issue by Pedroglp** [Homebrew/brew#15288]
### `brew doctor` output

```shell
➜  .ssh brew doctor    
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:905b0c3896164ae8067a22fff2fd0b80b16d3c8bb72441403eedf69da71ec717
curl: (35) OpenSSL/1.1.1s: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding

==> Downloading https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.6.10_1/portable-ruby-2.6.10_1.arm64_big_sur.bottle.tar.gz
curl: (35) OpenSSL/1.1.1s: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding

Error: Failed to download ruby from the following locations:
  - https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:905b0c3896164ae8067a22fff2fd0b80b16d3c8bb72441403eedf69da71ec717
  - https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.6.10_1/portable-ruby-2.6.10_1.arm64_big_sur.bottle.tar.gz

Do not file an issue on GitHub about this; you will need to figure out for
yourself what issue with your internet connection restricts your access to
GitHub (used for Homebrew updates and binary packages).
Error: Failed to upgrade Homebrew Portable Ruby!
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
Can't access due the same ewrror
```

### What were you trying to do (and why)?

I'm just trying to update any library and have this error

### What happened (include all command output)?

It tries to update brew and fails due SSL Padding error

### What did you expect to happen?

To successfully download files using curl and installing it using homebrew

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
```

**Comment by carlocab** [comment]
```
Do not file an issue on GitHub about this; you will need to figure out for
yourself what issue with your internet connection restricts your access to
GitHub (used for Homebrew updates and binary packages).
```

**Comment by Pedroglp** [comment]
If I set curl to insecure i'm able to do the request. So if anyone just want to update everything and is blocked by that do the following:

Create a ~/.curlrc
Edit the file and add --insecure
Run update

@carlocab FYI
I'm able to connect to github this is not an connection restriction.

**Comment by Bo98** [comment]
We don't touch the SSL layer so it sounds like you would have had the same issue running `curl https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.6.10_1/portable-ruby-2.6.10_1.arm64_big_sur.bottle.tar.gz` directly.

> This error message do not help guiding the user

The problem is that it's not like there's a fixed set of instructions to fix the issue - we don't know from what curl tells us what on your system causes the issue: it could be security software, proxy, router settings, enterprise software, etc. We wouldn't recommend `--insecure` as that just bypasses security rather than fixing the problem.
