### ISSUE TITLE
Cleanup Sigil Cop Handling

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#15281]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

As discussed in https://github.com/Homebrew/brew/pull/15274, we don't want to check for types in tests so should avoid the need for adding `typed: false` in those (and other "we'll never typecheck this type of file) files and remove the `typed: false` from their header.

### What is the motivation for the feature?

Fewer lines of code.

### How will the feature be relevant to at least 90% of Homebrew users?

It's not.

### What alternatives to the feature have been considered?

Doing nothing.

**Comment by dduugg** [comment]
I realized that the `Sorbet/FalseSigil` cop serves a slightly useful purpose, which is to flag `# typed: ignore` use. We could:

1. leave things as-is
2. not worry about `typed: ignore` code (it hasn't created a problem where `FalseSigil` is already excluded, e.g. `Library/Homebrew/test/support/fixtures`)
3. add a custom cop to flag any future use of `# typed: ignore`

I think I'm inclined toward option 2, but would like to hear from others

**Comment by MikeMcQuaid** [comment]
> 2\. not worry about `typed: ignore` code (it hasn't created a problem where `FalseSigil` is already excluded, e.g. `Library/Homebrew/test/support/fixtures`)

I'd say this 👍🏻
