### ISSUE TITLE
Opt-in only analytics and get rid of HOMEBREW_NO_ANALYTICS

### ISSUE THREAD

**Issue by lacombar** [Homebrew/brew#153]
Re-opening as the previous thread has been censored.

The current implementation shows a total lack of respect for user privacy.

**Comment by DomT4** [comment]
The previous thread hasn't been censored, ILZ locked it. One of the other maintainers will consider reopening it later potentially, later today. For now simply creating lots of threads on the same issue isn't persuading me to do much except retire from FOSS.
