### ISSUE TITLE
JRE bundled with our software gets corrupted while being installed by brew

### ISSUE THREAD

**Issue by Ahmed3lmallah** [Homebrew/brew#15305]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/Ahmed3lmallah/9c913954578753cc1c2137dea733b92a
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install a binary package that exists at [tar file](https://download.srcclr.com/srcclr-3.8.27-macosx.tgz) using the following [tap](https://github.com/veracode/homebrew-srcclr/blob/master/srcclr.rb) and have it run successfully using: `srcclr --version`

To eliminate the requirements for users to separately install java runtime environment, we bundle it with the package inside the 'jre' folder. 

It seems that the 'jre' folder is getting corrupted or modified somehow when `brew install srcclr` is executed.

### What happened (include all command output)?

The following error was presented:
```
➜  ~ srcclr --version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=90912, tid=11523
#
# JRE version:  (17.0.6+10) (build )
# Java VM: OpenJDK 64-Bit Server VM (17.0.6+10-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# Problematic frame:
# C  0x0000000000000000
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/aelmallah/hs_err_pid90912.log
#
#
[1]    90912 abort      srcclr --version
```

The same error is presented when attempting to run the JRE using the java binary:
```
➜  bin git:(stable) pwd
/opt/homebrew/Cellar/srcclr/3.8.27/libexec/jre/bin
➜  bin git:(stable) ./java --version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=94174, tid=11267
#
# JRE version:  (17.0.6+10) (build )
# Java VM: OpenJDK 64-Bit Server VM (17.0.6+10-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# Problematic frame:
# C  0x0000000000000000
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/homebrew/Cellar/srcclr/3.8.27/libexec/jre/bin/hs_err_pid94174.log
#
#
[1]    94174 abort      ./java --version
```

### What did you expect to happen?

The JRE was expected to work correctly. In fact, deleting the jre folder and replacing it with the folder from the download link works and gives the following result:

```
➜  bin git:(stable) pwd
/opt/homebrew/Cellar/srcclr/3.8.27/libexec/jre/bin
➜  bin git:(stable) ./java --version
openjdk 17.0.6 2023-01-17 LTS
OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu17.40+19-CA (build 17.0.6+10-LTS, mixed mode)
➜  bin git:(stable) srcclr --version
Version: 3.8.27
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap veracode/srcclr
brew install srcclr
srcclr --version
```

To confirm that the 'jre' folder was corrupted/modified and the problem is not from the source:
1. delete the 'jre' folder from `/opt/homebrew/Cellar/srcclr/3.8.27/libexec`
2. download the package from https://download.srcclr.com/srcclr-3.8.27-macosx.tgz
3. unzip the package
4. copy the 'jre' folder from `/Users/***/Downloads/srcclr-3.8.27` to `/opt/homebrew/Cellar/srcclr/3.8.27/libexec`
5. run `srcclr --version`
6. you should get back the correct version
```

**Comment by carlocab** [comment]
Formulae were designed to build things from source, so it's not really unexpected to end up with a broken install when you use them for pre-built binaries.

Have you tried packaging your software as a cask instead?

**Comment by Ahmed3lmallah** [comment]
> Have you tried packaging your software as a cask instead?

Thank you @carlocab for pointing me in the right direction. It seems that using a cask instead of a formula is what we are looking for.
