### ISSUE TITLE
Installing cached bottles now requires an Internet connection after #15117

### ISSUE THREAD

**Issue by boblail** [Homebrew/brew#15302]
### `brew doctor` output

**NOTE:** This is the `brew doctor` output on my laptop (where I can reproduce the issue) but the `brew doctor` output on the CI machine is clear.

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  pycparser

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  tcl-tk
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.15-10-g0841d1a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0841d1a25ef06c1c68d2d28ee77979e81a8dccde
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: deb1fd1f4212dfbfb26cd668d6aa49a17a3f9445
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 24 Apr 18:12 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

We have CI that tests a tool that installs bottled formulae from a private tap.

The CI doesn't have access to the private tap so we set it up with the bottles it should install by seeding the cache:
```
cp bottles/* $(brew --cache)/downloads
```

Then it just runs `brew install X Y Z`.

### What happened (include all command output)?

This was working prior to #15117 and has now stopped working (presumably because of the addition of `result.assert_success!`).

It fails to use the cached location if `resolve_url_basename_time_file_size` fails.

### What did you expect to happen?

I expected it to be able to use the cached file.

After all,
1. [We use the cached bottle regardless of how the URL is resolved](https://github.com/Homebrew/brew/blob/0841d1a25ef06c1c68d2d28ee77979e81a8dccde/Library/Homebrew/download_strategy.rb#L422-L423)
2. [We fail open when attempting to invalidate the cache by comparing the bottle's mtime to the URL's Last-Modified header](https://github.com/Homebrew/brew/blob/0841d1a25ef06c1c68d2d28ee77979e81a8dccde/Library/Homebrew/download_strategy.rb#L418-L419)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew uninstall socat
brew fetch socat --force-bottle
# turn off Wi-Fi
brew install socat --force-bottle
```

**Comment by MikeMcQuaid** [comment]
> `brew doctor` output

@boblail please supply this anyway.

> The CI doesn't have access to the private tap so we set it up with the bottles it should install by seeding the cache:

Note this is an undocumented/unsupported flow. That's not to say we're not going to try and address this but that the fix isn't going to be as high priority as others and you may want to open a PR yourself.

> This was working prior to #15117 and has now stopped working (presumably because of the addition of `result.assert_success!`).

Thanks for bisecting! @reitermarkus can you take a look at this? Thanks.

**Comment by MikeMcQuaid** [comment]
> That's not to say we're not going to try and address this but that the fix isn't going to be as high priority as others and you may want to open a PR yourself.

I didn't see you'd already created a PR for this, whoops, my triage flow could do with work 😅. Thanks for that!

**Comment by boblail** [comment]
👍  Added `brew doctor` output
