### ISSUE TITLE
Don't remove launchctl services when upgrading cask

### ISSUE THREAD

**Issue by stevenlele** [Homebrew/brew#15321]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Don't remove launchctl services when upgrading a cask.

### What is the motivation for the feature?

Upgrading a cask is not the same as removing and reinstalling it. If the services are removed, the app will try/prompt to set them up again after upgrade, which is annoying.

### How will the feature be relevant to at least 90% of Homebrew users?

Upgrading a cask with launchctl services will be much smoother.

### What alternatives to the feature have been considered?

N/A

**Comment by MikeMcQuaid** [comment]
CC @Homebrew/cask for thoughts.

**Comment by bevanjkay** [comment]
> I guess a big issue I see is how to handle situations where services change between versions. 

This would also be my primary concern. What happens when the `launchctl` changes on upgrade.

**Comment by MikeMcQuaid** [comment]
Passing on this for now given a bove, sorry @stevenlele.
