### ISSUE TITLE
Stale homebrew/core checkouts result in mishandling of deleted formulae

### ISSUE THREAD

**Issue by SylvainGarrigues** [Homebrew/brew#15339]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.0.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 763c41f006ab9b44261e313b0aaa24a047431b06
Last commit: 6 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2a72f5600dfb622613a6fb43403475e9d42f0a02
Core tap last commit: 2 months ago
Core tap branch: master
Core tap JSON: 30 Apr 08:50 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gst-plugins-base
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

# brew update && brew upgrade
 There appears to be conflict between gstreamer and gst-plugins-base...

### What happened (include all command output)?

To reproduce, install gstreamer and then try to install gst-plugins-base
```
==> Pouring gst-plugins-base--1.22.0_1.arm64_ventura.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/gst-device-monitor-1.0
Target /opt/homebrew/bin/gst-device-monitor-1.0
is a symlink belonging to gstreamer. You can unlink it:
  brew unlink gstreamer

To force the link and overwrite all conflicting files:
  brew link --overwrite gst-plugins-base

To list all files that would be deleted:
  brew link --overwrite --dry-run gst-plugins-base

Possible conflicting files are:
/opt/homebrew/bin/gst-device-monitor-1.0 -> /opt/homebrew/Cellar/gstreamer/1.22.2/bin/gst-device-monitor-1.0
/opt/homebrew/bin/gst-discoverer-1.0 -> /opt/homebrew/Cellar/gstreamer/1.22.2/bin/gst-discoverer-1.0
/opt/homebrew/bin/gst-play-1.0 -> /opt/homebrew/Cellar/gstreamer/1.22.2/bin/gst-play-1.0
Error: Could not symlink include/gstreamer-1.0/ges/ges-asset.h
Target /opt/homebrew/include/gstreamer-1.0/ges/ges-asset.h
is a symlink belonging to gstreamer. You can unlink it:
  brew unlink gstreamer

To force the link and overwrite all conflicting files:
  brew link --overwrite gstreamer

To list all files that would be deleted:
  brew link --overwrite --dry-run gstreamer
```

### What did you expect to happen?

This makes it impossible to use gst-plugins-bad or gst-plugins-ugly for instance, as they depend on gst-plugins-base which depends on gstreamer 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
For instance,
# brew install gst-plugins-bad
```

**Comment by SylvainGarrigues** [comment]
@carlocab's suggestion solved my problem. However, I would have expected the "brew update && brew upgrade" go smoothly without this manual intervention :)

**Comment by carlocab** [comment]
> However, I would have expected the "brew update && brew upgrade" go smoothly without this manual intervention :)

Yes. That's why I haven't closed this issue and instead migrated it to the right place.

**Comment by MikeMcQuaid** [comment]
> You shouldn't be able to install `gst-plugins-{base,bad}` anymore, but it seems that your very old checkout of Homebrew/core (`Core tap last commit: 2 months ago`) allows you to do it.

Increasingly I think `formulary` should refuse to ever load anything from homebrew/core unless `HOMEBREW_NO_INSTALL_API` is set. I think that would avoid a whole class of these sort of bugs.

Similarly, `brew doctor` should probably tell people who haven't set `HOMEBREW_NO_INSTALL_API`, `HOMEBREW_DEVELOPER` or run a `dev-cmd` to `brew untapped homebrew/core` and `brew untap homebrew/cask`
