### ISSUE TITLE
Deprecate OS::Mac/MacOS usage on Linux

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#15343]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

We should deprecate (and eventually disable, remove) the use of `OS::Mac` and `MacOS` on Linux: 

https://github.com/Homebrew/brew/blob/01e0c20d01c6aab28d844280d130f0e745e2ddd9/Library/Homebrew/os/linux.rb#L50-L51

This module was originally added as a workaround for the fact that Homebrew/brew and Homebrew/homebrew-core both used to only support macOS exclusively. Since then, both support macOS and Linux and we have significantly more and better DSLs (and their corresponding Rubocops) to ensure that `on_macos do` and `if OS.mac?` are used appropriately.

All uses of `MacOS.version` should be gated behind these instead of being defined in the weird way we currently do on Linux.

Note that the generic OS platform (e.g. `brew tests --generic`) already does not have `OS::Mac` or `MacOS` defined so most of Homebrew/brew already works appropriately here.

### What is the motivation for the feature?

It will improve the readability of Homebrew/brew and Homebrew/homebrew-core code that relates to a specific platform.

### How will the feature be relevant to at least 90% of Homebrew users?

More productive maintainers and contributors are better for all users.

### What alternatives to the feature have been considered?

Not caring and defining everything everywhere.

**Comment by MikeMcQuaid** [comment]
> Or, at the very least, I think there are things that are useful inside `MacOS`/`OS::Mac` that we want to expose on Linux when simulating macOS, and the current way of making that work is to define them on Linux.

Simulating macOS is reasonable and that module should be defined when simulating. In general, though, having `MacOS.version` be usable and used on Linux is not intuitive.

**Comment by MikeMcQuaid** [comment]
> and this could lead to weird/unexpected behaviour after using `Homebrew::SimulateSystem`.

I would be very surprised if this it not already the case. You're already having to deal with the fact that there's essentially two `OS::Mac` depending on which OS was required first.

Interested in thoughts from @Rylan12 too.

**Comment by carlocab** [comment]
> I would be very surprised if this it not already the case.

To me that speaks in favour of not caring and defining everything everywhere.

**Comment by MikeMcQuaid** [comment]
> To me that speaks in favour of not caring and defining everything everywhere.

Most maintainers/contributors/users and runs of Homebrew most of the time are not using `SimulateSystem`. It should be the exception rather than the rule.

**Comment by reitermarkus** [comment]
> Not caring and defining everything everywhere.

I think that's the only solution unless we also want to deprecate `SimulateSystem`, which we don't.

Note that everything everywhere means we need to merge these modules rather than using the one required last.

**Comment by MikeMcQuaid** [comment]
> I think that's the only solution unless we also want to deprecate `SimulateSystem`, which we don't.

This really isn't true. `SimulateSystem` can (and does) include things in `os/mac`. This does not mean that `os/linux` needs to define this module.

`OS::Linux` is not defined on macOS but yet I can simulate Linux on macOS. Even if I could/cannot, I can still use formulae with Linux-only definitions on macOS without this module being defined. There is no reason we couldn't do the same thing for `OS::Mac`.

> Note that everything everywhere means we need to merge these modules rather than using the one required last.

We already don't use everything everywhere. We're defining the same module on macOS and Linux with completely differing implementations.

**Comment by carlocab** [comment]
> This really isn't true. `SimulateSystem` can (and does) include things in `os/mac`.

Not currently, I believe:
```
❯ rg require -g'**/simulate_system.rb'
simulate_system.rb
55:require "extend/os/simulate_system"

extend/os/simulate_system.rb
5:  require "extend/os/mac/simulate_system"
7:  require "extend/os/linux/simulate_system"
```
So it's possible `SimulateSystem` currently implicitly relies on `OS::Mac` being defined on Linux. If not, then users of `SimulateSystem` certainly do.

> Most maintainers/contributors/users and runs of Homebrew most of the time are not using `SimulateSystem`.

Most maintainers/contributors/users also currently don't really have any problems with `OS::Mac` being defined on Linux either, so I think this is neither here nor there.

**Comment by MikeMcQuaid** [comment]
> So it's possible `SimulateSystem` currently implicitly relies on `OS::Mac` being defined on Linux.

Yes and this can definitely be changed, which is the stated purpose of this issue.

> Most maintainers/contributors/users also currently don't really have any problems with `OS::Mac` being defined on Linux either, so I think this is neither here nor there.

"Most", sure. Most of them have never looked at the code in Homebrew/brew at all so it's always going to be a stretch.

Off the top of your head: what does `MacOS.version > :catalina` return on Linux? You may know that but I think you'd be very hard pressed to suggest that's a more intuitive API than guarding with `OS.mac? && MacOS.version > :catalina`.

**Comment by carlocab** [comment]
> Yes and this can definitely be changed, which is the stated purpose of this issue.

Sure, but I guess my argument is that by doing that you end up creating something else that looks a lot like `OS::Mac`, and likely duplicates lots of things inside `OS::Mac` in the process. Which kind of raises the question: why not call that replacement `OS::Mac` too?

> Off the top of your head: what does `MacOS.version > :catalina` return on Linux?

`false`.

> You may know that but I think you'd be very hard pressed to suggest that's a more intuitive API than guarding with `OS.mac? && MacOS.version > :catalina`.

If we want to disallow using `MacOS.version > :catalina` on Linux, then let's do that (by, e.g., throwing an error when `MacOS.version` is called on Linux and not simulating macOS). It's not clear to me we need to (or that it's even a good idea to, even if not entirely necessary) throw out all of `OS::Mac` to do this.

**Comment by MikeMcQuaid** [comment]
> If we want to disallow using `MacOS.version > :catalina` on Linux, then let's do that (by, e.g., throwing an error when `MacOS.version` is called on Linux and not simulating macOS). It's not clear to me we need to (or that it's even a good idea to, even if not entirely necessary) throw out all of `OS::Mac` to do this.

All the boolean methods there could be prefixed with `if OS.mac? &&` and make sense. There is no reason you ever need to query a macOS version on Linux.

**Comment by MikeMcQuaid** [comment]
> `false`.

You know this, others do/will not. I think it's pretty hard to argue that that's an intuitive API on Linux.

**Comment by reitermarkus** [comment]
I see quite a few formulae are using `MacOS.version` for `if … else`s in `install`.

I think we could replace something like

```ruby
      hintfile = if MacOS.version >= :mojave
        "macosx10.14"
      else
        "macosx10.10"
      end
```

with

```ruby
      hintfile = if on_mojave :or_later
        "macosx10.14"
      else
        "macosx10.10"
      end
```

i.e. make `on*` blocks return a boolean when no block is given.

**Comment by Bo98** [comment]
We should never be the need to simulate the contents of the `install` block.

**Comment by MikeMcQuaid** [comment]
> This is also the code pattern that made us allow usage of `OS.mac?` and friends inside `install` methods.

Agreed.

`on_mojave` and friends only exist for cases where we need to evaluate the block in multiple OSs (e.g. for calculating URLs). `def install` is one of the cases where it's only an actual conditional so `OS.mac?` is preferable.

**Comment by reitermarkus** [comment]
> There should never be the need to simulate the contents of the `install` block.

Still, using `on*` blocks everywhere would make Formulae look more consistent and avoid having to use `MacOS.version` directly in many cases.

**Comment by reitermarkus** [comment]
I am strongly in favour of using `on_mojave :or_later` instead of using `OS.mac? && MacOS.version >= :mojave` everywhere. It's more concise and makes Formulae look more consistent.

**Comment by MikeMcQuaid** [comment]
> I am strongly in favour of using `on_mojave :or_later` instead of using `OS.mac? && MacOS.version >= :mojave` everywhere. It's more concise and makes Formulae look more consistent.

This debate was settled over a year ago.

The block syntax is only used when it's needed i.e. we need to be able to iterate through the different values and produce different output for e.g. JSON generation on Linux.

**Comment by reitermarkus** [comment]
> This debate was settled over a year ago.

I assume back then noone proposed `OS.mac? && MacOS.version >= :mojave` as a pattern.

> The block syntax is only used when it's needed

I am not talking about using block syntax, I am talking about using `on*` methods without blocks as booleans. We already have the DSL, we just have to return a boolean if no block is provided.  I just don't see a good reason why we should use two different ways of doing the same thing in the same formula.

**Comment by MikeMcQuaid** [comment]
> I just don't see a good reason why we should use two different ways of doing the same thing in the same formula.

Because there are two different modes in which these are used:
- things that will only ever be run on a single platform e.g. `install`, `post_install`
- things that will be run on different platforms e.g. generating `url`s, `service do`, etc.

That these don't always look the same is a feature, not a bug. You need to think differently about these two places and Ruby handles blocks and `if`s very differently.

**Comment by reitermarkus** [comment]
> Because there are two different modes in which these are used:

But why do we need two modes if the second mode (i.e. `on_*` blocks) behaves the same way when not simulating anything? Of course we don't *need* to simulate `install` on another platform, and I don't think we currently run `install` anywhere with `SimulateSystem`.

A formula/cask author shouldn't need to care about which parts Homebrew simulates with `SimulateSystem` internally, so the DSL should look the same for all parts.

**Comment by MikeMcQuaid** [comment]
@reitermarkus Let's agree to disagree.

**Comment by MikeMcQuaid** [comment]
> It turns out that in practice, however, we end up evaluating formulae multiple times for each possible variation of the `on_*` blocks, so the syntactic guarantee isn't really all that useful for us. It may still be eventually, but that relies on work that I don't think will ever happen.

I think this work probably will eventually happen and I'd rather not close the door on it and force another syntax change on homebrew/core and taps _again_.
