### ISSUE TITLE
documentation: how to include Python packages into your formula

### ISSUE THREAD

**Issue by jackjansen** [Homebrew/brew#15362]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

In the formula cookbook (or thereabouts) there should be information on how to create a cask that contains binary Python extension modules _and_ pure-python packages _and_ command line scripts.

It turns out to be very simple but non-intuitive to do this: create a `lib/pythonX.Y/site-packages` in your `prefix` and use `pythonX.Y -m pip install --prefix yourprefix`.

Everything like `brew link` and `brew unlink` and such now works fine. But it took me a very long time to find this.

### What is the motivation for the feature?

For each of the features the documentation is fairly good (from the Python section, or from references to formulae that do this) but not for the combination.

### How will the feature be relevant to at least 90% of Homebrew users?

Interesting for formula-writers only.

### What alternatives to the feature have been considered?

I can't think of any.

**Comment by MikeMcQuaid** [comment]
> how to create a cask

do you mean a formula or cask here?
