### ISSUE TITLE
Switch ```HOMEBREW_OPTIMIZATION_LEVEL``` from ```-Os``` to ```-O2``` or ```-O3``` on macOS

### ISSUE THREAD

**Issue by kimwalisch** [Homebrew/brew#15372]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Use:

```
self["HOMEBREW_OPTIMIZATION_LEVEL"] = "O3"
```

in ```Library/Homebrew/extend/ENV/super.rb```.

### What is the motivation for the feature?

Currently both my [primesieve](https://formulae.brew.sh/formula/primesieve#default)  and [primecount](https://formulae.brew.sh/formula/primesieve#default) C/C++ tools run about 20% slower on my MacBook Air M2 when installed using homebrew vs. when I compile them myself using CMake's default ```-O3``` optimisation flag.

I know this has been discussed a few times in the past (e.g. in my related issue from 2021: https://github.com/orgs/Homebrew/discussions/484), but it just feels crazy to me: people buy the latest Apple PCs because of their awesome performance but then C/C++ libraries & tools installed using homebrew run up to 20% slower than possible because homebrew uses the ```-Os``` optimisation flag on macOS. The Linux distributions on the other hand build virtually all their C/C++ packages using either ```-O2``` or ```-O3``` (CMake uses ```-O3``` by default for release builds).  And I can make an educated guess that the same is true for Windows.

I know that it is possible to use the code below in formulaes to change the default optimisation flag:

```
ENV["HOMEBREW_OPTIMIZATION_LEVEL"] = "O3"
```

But it seems like this is currently not allowed in default homebrew formulaes, because none of the default formulaes uses that code. 

### How will the feature be relevant to at least 90% of Homebrew users?

C/C++ libraries & tools installed using homebrew will run up to 20% faster on macOS. 

### What alternatives to the feature have been considered?

As mentioned in the motivation section, instead of changing the default ```-Os``` optimization flag it would also be possible to officially allow using the code below in homebrew formulaes:

```
ENV["HOMEBREW_OPTIMIZATION_LEVEL"] = "O3"
```

This would have the drawback that the existing C/C++ libraries & tools would only run faster if their formulaes are updated.

**Comment by fxcoudert** [comment]
There is no way we're making `-O3` the default for all formulas, as there are definitely a lot of cases where it will mess things up.

Regarding having `ENV.O3` and using it in a small number of formulas: why not, but the question of “how do we measure things” is definitely a good one. Otherwise, it might just end up being featured in a lot of formulas where it will have no actual purpose, just on the belief that “more optimization is always better”.

**Comment by Bo98** [comment]
Fine with adding `ENV.O3`.

`-Os` is a sensible default - it's the default Apple has in Xcode. But that doesn't mean `-O3` isn't ever suitable, so I'm fine with adding an opt-in for it.

`-O2` is probably not particularly useful - it's very similar to `-Os`. Though I wouldn't be against an option for it for completion sake.

**Comment by MikeMcQuaid** [comment]
> There is no way we're making `-O3` the default for all formulas, as there are definitely a lot of cases where it will mess things up.

Agreed.

> `-Os` is a sensible default - it's the default Apple has in Xcode. But that doesn't mean `-O3` isn't ever suitable, so I'm fine with adding an opt-in for it.

Agreed.

> `-O2` is probably not particularly useful - it's very similar to `-Os`. Though I wouldn't be against an option for it for completion sake if third-party taps would like it.

Disagree unless we'll use it in Homebrew/core.

> On Linux, we currently default to `-O2`.

Probably another good reason to avoid `ENV.Os` or `ENV.O2` to avoid Linux/macOS confusion here.

**Comment by kimwalisch** [comment]
> Regarding having ENV.O3 and using it in a small number of formulas: why not, but the question of “how do we measure things” is definitely a good one.

Unfortunately it is difficult to find extensive benchmark data of GCC/Clang optimization levels on the web that includes ```-Os```. Phoronix regularly publishes such articles (e.g. https://www.phoronix.com/review/clang-12-opt), but those are without ```-Os```.

But here are some Clang optimization level benchmarks of my primesieve & primecount C++ math libraries that I have run on my MacBook Air M2.

## [primesieve](https://github.com/kimwalisch/primesieve) benchmark

This benchmark counts the number of primes ≤ 10^11 using the sieve of Eratosthenes algorithm using a single thread. The runtime is indicated in seconds, lower is better.

<table>
    <tr>
        <td>Clang -O1, primesieve 1e11 -t1:</td>
        <td>Seconds: 13.743</td>
    </tr>
    <tr>
        <td>Clang -Os, primesieve 1e11 -t1:</td>
        <td>Seconds: 12.813</td>
    </tr>
    <tr>
        <td>Clang -O2, primesieve 1e11 -t1:</td>
        <td>Seconds: 9.941</td>
    </tr>
    <tr>
        <td>Clang -O3, primesieve 1e11 -t1:</td>
        <td>Seconds: 9.950</td>
    </tr>
</table>

## [primecount](https://github.com/kimwalisch/primecount) benchmark

This benchmark counts the number of primes ≤ 10^16 using the one of the combinatorial prime counting algorithms using a single thread. The runtime is indicated in seconds, lower is better.

<table>
    <tr>
        <td>Clang -O1, primecount 1e16 -t1:</td>
        <td>Seconds: 10.372</td>
    </tr>
    <tr>
        <td>Clang -Os, primecount 1e16 -t1:</td>
        <td>Seconds: 7.688</td>
    </tr>
    <tr>
        <td>Clang -O2, primecount 1e16 -t1:</td>
        <td>Seconds: 4.311</td>
    </tr>
    <tr>
        <td>Clang -O3, primecount 1e16 -t1:</td>
        <td>Seconds: 4.290</td>
    </tr>
</table>

## Analysis

The performance of the ```-O2``` and ```-O3``` compiler options is very close to each other in both benchmarks.

The performance of ```-Os``` is significantly worse than ```-O2``` and ```-O3``` in both benchmarks. In the primesieve benchmark ```-Os``` is about 28% slower, whereas in the primecount benchmark ```-Os``` is about 79% slower. These speed differences are huge in my opinion.

If homebrew would allow using ```ENV["HOMEBREW_OPTIMIZATION_LEVEL"] = "O2"``` in default formulaes, then I would definetly use it.

**Comment by carlocab** [comment]
TBH I've always found `-O2` a more reasonable default, and carry a patch locally that replaces `Os` with `O2`. I've been meaning to get around to produce meaningful benchmarks, but it's a lot of work: "meaningful" here means _at least_ a few dozen formulae.

Note that aside from performance benchmarks, we should also compare bottle/keg sizes. But also, it's important to be wary of this: https://dl.acm.org/doi/10.1145/2528521.1508275

**Comment by gromgit** [comment]
> But also, it's important to be wary of this: https://dl.acm.org/doi/10.1145/2528521.1508275

Non-paywall link: https://www.researchgate.net/publication/220938759_Producing_Wrong_Data_Without_Doing_Anything_Obviously_Wrong

**Comment by MikeMcQuaid** [comment]
> If homebrew would allow using `ENV["HOMEBREW_OPTIMIZATION_LEVEL"] = "O2"` in default formulaes, then I would definitely use it.

We're never going to do this, sorry.

> TBH I've always found `-O2` a more reasonable default, and carry a patch locally that replaces `Os` with `O2`. I've been meaning to get around to produce meaningful benchmarks, but it's a lot of work: "meaningful" here means _at least_ a few dozen formulae.

It may be with modern Clang/SSDs/M1s: it is better. Regardless, as we all are aware now, making this sort of change without breaking things is going to be very time consuming and bordering on impossible.

**Comment by dimatakoy** [comment]
Is there a way "build and install" package with -O2? Like `--build-from-source`, but with building every dep recursively?

**Comment by MikeMcQuaid** [comment]
> Is there a way "build and install" package with -O2? Like `--build-from-source`, but with building every dep recursively?

No.

**Comment by MikeMcQuaid** [comment]
Closing out this issue because, as originally requested, we aren't going to do that. Will review a PR to add a `ENV.03` in Homebrew/brew and, after that's merged and tagged, PRs to add it to individual formulae in Homebrew/homebrew-core.
