### ISSUE TITLE
Error: unknown keyword: tap on 4.0.16-47-g1120812

### ISSUE THREAD

**Issue by lRoMYl** [Homebrew/brew#15379]
### `brew doctor` output

```shell
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/lib_InternalSwiftSyntaxParser.dylib

Warning: Your Xcode (14.1) is outdated.
Please update to Xcode 14.2 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 01e0c20d01c6aab28d844280d130f0e745e2ddd9
Last commit: 8 days ago
Core tap JSON: 08 May 06:04 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode-14.1.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.1 => /Applications/Xcode-14.1.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

Was trying to install a Formula that fetch from a private repo using headers, this was working 2 weeks ago.

The make formula doesn't use any `tap` command.

Here is the formula, just replaced the private text with `...`
```Makefile
class MyFormula < Formula
  desc "Description..."
  homepage "https://github.com/..."
  url "https://github.com/.../archive/refs/tags/1.0.1.tar.gz",
    headers: [
      "Accept: application/octet-stream",
      "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
    ]
  sha256 "..."
  head "https://github.com/...git"

  depends_on :xcode => :build
  depends_on :macos

  def install
    system "make", "install", "PREFIX=#{prefix}"
  end
end
```

### What happened (include all command output)?

Error: unknown keyword: tap
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Taps/[MyPrivateRepo]/[MyFormula].rb:15:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:404:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:404:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:643:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:315:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
make: *** [install] Error 1

### What did you expect to happen?

Formula installed without any issue

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap [MyPrivateRepo]
brew install [MyFormula]
```

**Comment by reitermarkus** [comment]
Seems like that line was changed in https://github.com/Homebrew/brew/pull/15257.

**Comment by Bo98** [comment]
Do you have an initialize override on line 15 of your formula file?

**Comment by MikeMcQuaid** [comment]
Can't debug private formulae here, please take this to discussions.

**Comment by lRoMYl** [comment]
@Bo98 Here is the new discussion thread.

Btw for regarding your question on 
> Do you have an initialize override on line 15 of your formula file?

No, as can be seen on the Formula I shared above, line 15 doesn't actually have any initializer, only `def install`
