### ISSUE TITLE
 brew install php70 error

### ISSUE THREAD

**Issue by lilien1010** [Homebrew/brew#1539]
Error: Permission denied - /usr/local/opt/gettext

**Comment by vladshablinsky** [comment]
This should help you with your issue and the issue template should have helped you as well.

```
sudo chown -R $(whoami) $(brew --prefix)
```

If it's not your case, please follow the troubleshooting steps, thanks! https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md
