### ISSUE TITLE
Installzation error to assess the instalzation link

### ISSUE THREAD

**Issue by xielab2017** [Homebrew/brew#15415]
### `brew doctor` output

```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
I received the error message
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 14 ms: Connection refused

I check the link https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
it is not assessble. install.sh file real link is https://github.com/Homebrew/install/blob/master/install.sh
However, it does not work.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
I received the error message
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 14 ms: Connection refused

I check the link https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
it is not assessble. install.sh file real link is https://github.com/Homebrew/install/blob/master/install.sh
However, it does not work.
```

### What were you trying to do (and why)?

Install homebrew

### What happened (include all command output)?

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
I received the error message
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 14 ms: Connection refused

I check the link https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
it is not assessble. install.sh file real link is https://github.com/Homebrew/install/blob/master/install.sh
However, it does not work. 

### What did you expect to happen?

successfully installed 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
I received the error message
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 14 ms: Connection refused

I check the link https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
it is not assessble. install.sh file real link is https://github.com/Homebrew/install/blob/master/install.sh
However, it does not work.
```

**Comment by gromgit** [comment]
> install.sh file real link is `https://github.com/Homebrew/install/blob/master/install.sh`

No, that's the GitHub page for that file. Click on the "Raw" button to get the raw script source...which takes you to the same URL that you can't access.

Since you seem to be in China, you may be blocked by your country's firewall, though since you seem to be able to access GitHub itself, it's more likely that the `githubusercontent.com` domain is being blocked by whoever is providing your network access. Perhaps someone else in your part of the world can advise further.

**Comment by xielab2017** [comment]
find the Chinese mirror for homebrew. Have done installation
