### ISSUE TITLE
MacOs Sierra- can't install

### ISSUE THREAD

**Issue by Z-starts** [Homebrew/brew#1541]
brew install upx
upx: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.

[https://github.com/upx/upx/issues/22](https://github.com/upx/upx/issues/22)

**Comment by Z-starts** [comment]
modify the file 
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/upx.rb

#depends_on MaximumMacOSRequirement => :el_capitan

**Comment by MikeMcQuaid** [comment]
@Z-starts It then fails at runtime. In future please open formulae issues on Homebrew/homebrew-core and follow our issue template.
