### ISSUE TITLE
Error `no implicit conversion of nil into String` for `upgrade --greedy`

### ISSUE THREAD

**Issue by Logicer16** [Homebrew/brew#15427]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.18-16-g6c80308
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6c8030829094a5d3f41dd92caddefd45711b68c3
Last commit: 9 hours ago
Core tap JSON: 15 May 04:09 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 300
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/env nvim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 14.0.0 build 1400
Git: 2.40.1 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.6-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

### What were you trying to do (and why)?

Update software with `brew upgrade --greedy`

### What happened (include all command output)?

```
% brew upgrade --greedy
==> Upgrading 4 outdated packages:
Error: no implicit conversion of nil into String
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:84:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:84:in `Pathname'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:84:in `can_load?'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:175:in `can_load?'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:419:in `block in for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:418:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:418:in `for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:405:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/upgrade.rb:105:in `block in upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cask/upgrade.rb:97:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/upgrade.rb:97:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:253:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

The command to run without error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade --greedy
```

**Comment by EastLord** [comment]
same here

**Comment by reitermarkus** [comment]
Please post the output of `brew outdated --greedy`.

**Comment by Logicer16** [comment]
```
% brew outdated --greedy
arduino-ide-nightly (latest) != latest
firefox-nightly () != latest
google-chrome-canary (115.0.5763.0) != 115.0.5771.0
tor-browser (12.0.5) != 12.0.6
```
It doesn't seem to be related to a specific program

**Comment by reitermarkus** [comment]
It should be related to those that show `()`, which means no installed version is found.

Please `brew install tree` and post the output of `tree -a "$(brew --caskroom)/<cask>/.metadata"` for a `<cask>` that shows `()`.

**Comment by Moulick** [comment]
```bash
❯ tree -a "$(brew --caskroom)/font-fira-mono/.metadata"
/opt/homebrew/Caskroom/font-fira-mono/.metadata  [error opening dir]

0 directories, 0 files
```

**Comment by Moulick** [comment]
Running `brew reinstall font-fira-mono` seems to have fixed `font-fira-mono` now

```
❯ tree -a "$(brew --caskroom)/font-fira-mono/.metadata"
/opt/homebrew/Caskroom/font-fira-mono/.metadata
├── 3.206,4.202
│   └── 20230515090911.334
│       └── Casks
│           └── font-fira-mono.rb
└── config.json

4 directories, 2 files
```

**Comment by reitermarkus** [comment]
Yes, `brew reinstall` should fix this. Should be addressed by https://github.com/Homebrew/brew/pull/15432 so the correct error message is actually shown for this case.

**Comment by Moulick** [comment]
Thanks! An reason why it broke in the first place plz?

**Comment by reitermarkus** [comment]
I assume these were silently broken for a while, but recently the logic for determining the installed version changed and is now more strict, which is why it broke now.

**Comment by Moulick** [comment]
hmm, I installed both of the broken ones for me literally last week on a new laptop. ¯\_(ツ)_/¯

**Comment by reitermarkus** [comment]
As to why they were silently broken: Maybe a previous failed installation/upgrade.

**Comment by reitermarkus** [comment]
I just checked, and I actually have a bunch of broken ones myself, which all only have `.metadata/config.json` left. According to my Time Machine backup, this was already the case since at least March. No idea how they got broken though.
