### ISSUE TITLE
DOC: mention `brew style --fix` in Formula cookbook

### ISSUE THREAD

**Issue by corneliusroemer** [Homebrew/brew#15449]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I've just started contributing formulae. Quite a steep learning curve. I would have liked if the docs had pointed me to `brew style --fix`. I only found out about this through ChatGPT.

### What is the motivation for the feature?

Making things easier for first time contributors

### How will the feature be relevant to at least 90% of Homebrew users?

Relevant to all first time contributors

### What alternatives to the feature have been considered?

Doc is best way to do this.

**Comment by reitermarkus** [comment]
Isn't this in the pull request template?

**Comment by corneliusroemer** [comment]
> @reitermarkus: Isn't this in the pull request template?

Not unless I'm missing something?

<img width="1194" alt="image" src="https://github.com/Homebrew/brew/assets/25161793/c82abbe3-f394-46f5-b015-7958589e7619">

https://github.com/Homebrew/homebrew-core/pull/131242

**Comment by reitermarkus** [comment]
Right, `audit` also runs `style`, for formulae at least. So maybe the pull request template should include `--fix`.

**Comment by carlocab** [comment]
Or, perhaps: `brew audit|style` suggests `brew audit|style --fix <file/formulae-names>` if there are autocorrectable errors. Might be more useful since the formula cookbook is quite a lot to read these days.

**Comment by MikeMcQuaid** [comment]
> Or, perhaps: `brew audit|style` suggests `brew audit|style --fix <file/formulae-names>` if there are autocorrectable errors. Might be more useful since the formula cookbook is quite a lot to read these days.

This is the best idea 👍🏻

**Comment by corneliusroemer** [comment]
I think it should be in both places, if you haven't discovered it in formula cookbook it's nice to see in PR template. Or maybe mention it in CI where the formatting errors are reported: "you can fix this automatically with XYZ"
