### ISSUE TITLE
Make brew runnable as super user for linkapps

### ISSUE THREAD

**Issue by alexreg** [Homebrew/brew#1544]
There is one case when it makes sense to run `sudo brew`; that is, to do `linkapps`, since this may install symlinks in `/Applications`, which is (and indeed should be) owned by *root:admin*. Could we have Homebrew allow this please?

**Comment by woodruffw** [comment]
As far as I know, running `brew` as a super user will never be officially supported for security and isolation reasons.

`brew linkapps` should succeed in symlinking to `/Applications`, unless you're a non-administrator (i.e., non `admin` group). In the latter case, `brew` would either need to elevate (probably not going to happen) or apply `chown`/`chgrp` to `/Applications` (probably not a good idea from a multi-user or expected system permission standpoint).

**Comment by MikeMcQuaid** [comment]
@woodruffw is correct here.

**Comment by alexreg** [comment]
Ah, I figured out the problem: I'm using `brewdo`, and the specialised *_homebrew* user needed to be added to the *admin* group to be able to link apps correctly.

Thanks.
