### ISSUE TITLE
Slow internet causes formula.jws.json download to fail

### ISSUE THREAD

**Issue by isaac-mcfadyen** [Homebrew/brew#15443]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.18-38-g111f504
ORIGIN: https://github.com/Homebrew/brew
HEAD: 111f50492585a58324563107453ac7e043351157
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 24406867a7ba978bbb18eb89a51523cd454271c7
Core tap last commit: 42 minutes ago
Core tap branch: master
Core tap JSON: 16 May 20:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### What were you trying to do (and why)?

Run `brew upgrade` (to upgrade formulas) or really any other brew command, even `brew doctor`.

### What happened (include all command output)?

The output begins with `Downloading https://formulae.brew.sh/api/formula.jws.json` and a progress bar.

I am on slow internet (DSL plus others using bandwidth) so the download takes a while (upwards of a minute), and then fails with the error `Warning: Failed to set filetime 1684265154 on '/Users/isaac/Library/Caches/Homebrew/api/formula.jws.json': No such file or directory`. 

The issue seems to be directly related to internet speed, because if I move to faster internet everything works fine.

The workaround here (https://github.com/Homebrew/brew/issues/14516#issuecomment-1418593313) works, preventing the download of the formula.jws.json file at all, but this is obviously suboptimal. Removing the cache directory as suggested here (https://github.com/Homebrew/brew/issues/14516#issuecomment-1418546734) does *not* work, and reinstalling homebrew does not work.

Full output:
```
brew upgrade
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################ 100.0%
Warning: Failed to set filetime 1684265154 on
Warning: '/Users/isaac/Library/Caches/Homebrew/api/formula.jws.json': No such
Warning: file or directory
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################ 100.0%
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################ 100.0%
Error: Cannot download non-corrupt https://formulae.brew.sh/api/formula.jws.json!
```

### What did you expect to happen?

`brew upgrade` or `brew doctor` to complete successfully, or at least get past the `Downloading https://formulae.brew.sh/api/formula.jws.json` step.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Throttle your internet or otherwise move to very slow internet.
2. Run `brew upgrade`.
3. Observe as the `formula.jws.json` download fails and homebrew exits with an error.
```

**Comment by apainintheneck** [comment]
Setting `HOMEBREW_NO_INSTALL_FROM_API` is the only real alternative right now to the using the API if you have very slow internet.

The only real options here for us are to consider not using Github as a CDN (this would be a lot of work and just isn't in the cards at least in the short-term) or provide better messaging around when users are on slow internet to direct them not to use the API.

**Comment by isaac-mcfadyen** [comment]
> Setting `HOMEBREW_NO_INSTALL_FROM_API` is the only real alternative right now to the using the API if you have very slow internet.

Is this due to the fact that the API times out or something? The error message made me think there was some sort of race condition going on between the set filetime operation and the json download... but maybe not?

**Comment by carlocab** [comment]
> Setting `HOMEBREW_NO_INSTALL_FROM_API` is the only real alternative right now to the using the API if you have very slow internet.

This seems like an odd solution, since downloading the JSON should be more reliable than `git pull` on a slow connection.

I wonder if the flags we use to download the API data can be tweaked to handle this better.

**Comment by Bo98** [comment]
How slow are we talking? There is some tolerance of slow connections though there is a lower bound (<100 bytes/s for 5s, though we can adjust that if it improves things).

Certainly though, the error messaging should be improved here regardless of what the issue is.

**Comment by Bo98** [comment]
Actually, it appears `curl` is reporting a _successful_ download but the file doesn't exist? If the download failed and the file doesn't exist locally, it should abort with an entirely different message.

Do you get any more info with `HOMEBREW_CURL_VERBOSE=1`?

**Comment by MikeMcQuaid** [comment]
> This seems like an odd solution, since downloading the JSON should be more reliable than `git pull` on a slow connection.

I disagree here, in my experience `git` is significantly more reliable on very slow connections, despite being a bit slower.
