### ISSUE TITLE
brew install fails with: Bad CPU type in executable

### ISSUE THREAD

**Issue by Sarah-Calumet** [Homebrew/brew#1545]
Help please. Brew fails to install on my machine. I have OS 10.11, Xcode is installed.  

Here's the full output I get:

bash-3.2$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at 947b850 Merge pull request #1130 from aw1621107/allow-brew-llvm-for-openmp
/usr/local/bin/brew: line 9: /sw/sbin/readlink: Bad CPU type in executable
/usr/local/bin/brew: line 9: /sw/sbin/readlink: Bad CPU type in executable
/usr/local/bin/brew: line 47: /usr/local/Library/Homebrew/brew.sh: No such file or directory
Failed during: /usr/local/bin/brew update --force

**Comment by MikeMcQuaid** [comment]
> /sw/sbin/readlink: Bad CPU type in executable

This is from Fink. You should uninstall it or at least remove it from your `$PATH`.

**Comment by Sarah-Calumet** [comment]
Thanks! 
For anyone else who needs to remove Fink, here's how:
fink remove --recursive daemonic xinitrc
sudo rm -rf /sw
