### ISSUE TITLE
Brew still using API with HOMEBREW_NO_INSTALL_FROM_API=1

### ISSUE THREAD

**Issue by Moulick** [Homebrew/brew#15459]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.18-85-g16b2a14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 16b2a14c9408140b04828462b660d30056421fdb
Last commit: 20 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 419d9c8d85ef0724403bdb705432f0fd211b4587
Core tap last commit: 82 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

`sudo brew services start sudo-touchid`

### What happened (include all command output)?

Error: Need to download https://formulae.brew.sh/api/formula.jws.json but cannot as root! Run `brew update` without `sudo` first then try again.

### What did you expect to happen?

Successful service start. With `HOMEBREW_NO_INSTALL_FROM_API=1` set, I do not expect homebrew to still depend on the API to start a service.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
export HOMEBREW_NO_INSTALL_FROM_API=1
brew install artginzburg/tap/sudo-touchid
sudo brew services start sudo-touchid
>> Error: Need to download https://formulae.brew.sh/api/formula.jws.json but cannot as root! Run `brew update` without `sudo` first then try again.
brew update
sudo brew services start sudo-touchid
>> Error: Need to download https://formulae.brew.sh/api/formula.jws.json but cannot as root! Run `brew update` without `sudo` first then try again.
```

**Comment by carlocab** [comment]
Thoughts, @apainintheneck?

**Comment by MikeMcQuaid** [comment]
> ```shell
> sudo brew services start sudo-touchid
> ```

`sudo` doesn't pass through environment variables by default. Use `sudo -E` or `sudo HOMEBREW_NO_INSTALL_FROM_API=1`
