### ISSUE TITLE
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

### ISSUE THREAD

**Issue by Yvettyang** [Homebrew/brew#15479]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

$ brew upgrade pyenv  
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:61029cec31c68a1fae1fa90fa876adf43d0becff777da793f9b5c5577f00567a
########################                                                              29.1%
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
Error: Checksum mismatch.
Expected: 61029cec31c68a1fae1fa90fa876adf43d0becff777da793f9b5c5577f00567a
  Actual: 60077a905384605451fad43eb0109deec9882e5e8c7f9fdec046befa47494354
 Archive: /Users/Yvette/Library/Caches/Homebrew/portable-ruby-2.6.10_1.el_capitan.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade Homebrew Portable Ruby!

### What is the motivation for the feature?

I wanna upgrade pyenv and I get an error about curl which may be due to the compactivity of HTTP version. But what should I do to specify the HTTP version so I can connect to the API? Or Does brew still support upgrading pyenv?

### How will the feature be relevant to at least 90% of Homebrew users?

Lots of users of MacOS and Python need to use this command.

### What alternatives to the feature have been considered?

Sorry, I have no idea about this.

**Comment by MikeMcQuaid** [comment]
This is an issue with your connection to GitHub. We cannot fix it.
