### ISSUE TITLE
brew upgrade for a cask creates a 0-byte file in Applications directory

### ISSUE THREAD

**Issue by bradmurray** [Homebrew/brew#15484]
### `brew doctor` output

```shell
Your system is ready to brew
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.19-24-ge96fd24
ORIGIN: https://github.com/Homebrew/brew
HEAD: e96fd24a7328a4913de2f7c56fd2c97d9aaa4572
Last commit: 5 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 34b732b38991b8b2f26b592d87287ebc77937f19
Core tap last commit: 4 months ago
Core tap branch: master
Core tap JSON: 25 May 15:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### What were you trying to do (and why)?

Upgrade a cask

### What happened (include all command output)?

==> Upgrading 4 outdated packages:
raycast 1.51.3 -> 1.52.0
==> Upgrading raycast
==> Downloading https://releases.raycast.com/releases/1.52.0/download?build=universal
==> Downloading from https://d3jdrrl94b667u.cloudfront.net/Raycast_v1.52.0_71264205ebdf6061183dbe7343efa9de279b19fe_un
############################################################################################################### 100.0%
==> Quitting application 'com.raycast.macos'...
Application 'com.raycast.macos' quit successfully.
==> Backing App 'Raycast.app' up to '/opt/homebrew/Caskroom/raycast/1.51.3/Raycast.app'
==> Removing App '/Applications/Raycast.app'
==> Moving App 'Raycast.app' to '/Applications/Raycast.app'
cp: /Applications/Raycast.app/Contents: Operation not permitted
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents: unable to copy extended attributes to /Applications/Raycast.app/Contents: Operation not permitted
cp: /Applications/Raycast.app/Contents/_CodeSignature: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/_CodeSignature: unable to copy extended attributes to /Applications/Raycast.app/Contents/_CodeSignature: No such file or directory
cp: /Applications/Raycast.app/Contents/_CodeSignature/CodeResources: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/_CodeSignature: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/_CodeSignature: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/_CodeSignature: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/_CodeSignature: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/_CodeSignature: unable to copy ACL to /Applications/Raycast.app/Contents/_CodeSignature: No such file or directory
cp: /Applications/Raycast.app/Contents/MacOS: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/MacOS: unable to copy extended attributes to /Applications/Raycast.app/Contents/MacOS: No such file or directory
cp: /Applications/Raycast.app/Contents/MacOS/Raycast Restart Helper: No such file or directory
cp: /Applications/Raycast.app/Contents/MacOS/Raycast App Uninstall Helper: No such file or directory
cp: /Applications/Raycast.app/Contents/MacOS/Raycast: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/MacOS: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/MacOS: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/MacOS: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/MacOS: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/MacOS: unable to copy ACL to /Applications/Raycast.app/Contents/MacOS: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/Inter-Bold.otf: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/Inter-Regular.otf: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/emoji.json: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/JetBrainsMono-Bold.ttf: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/JetBrainsMono-Italic.ttf: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/AppIcon-Release.icns: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/Inter-SemiBoldItalic.otf: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/JetBrainsMono-Regular.ttf: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/package.json: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/.prettierrc: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/tsconfig.json: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/assets: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/assets: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/assets: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/assets/icon.png: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/assets: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/assets: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/assets: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/assets: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/assets: unable to copy ACL to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/assets: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/.eslintrc.json: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/src: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/src: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/src: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/src/index.tsx: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/src: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/src: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/src: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/src: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/src: unable to copy ACL to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started/src: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started: unable to copy ACL to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/getting-started: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit/.gitignore: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit: unable to copy ACL to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/teams-starter-kit: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/bin: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/bin: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/bin: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/bin/ray: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/bin: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/bin: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/bin: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/bin: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/bin: unable to copy ACL to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/bin: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/hash: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server: unable to copy ACL to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api: unable to copy ACL to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi: unable to copy extended attributes to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi/raycast_napi.darwin-x64.node: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi/index.js: No such file or directory
cp: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi/raycast_napi.darwin-arm64.node: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.52.0/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi: unable to copy ACL to /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/napi: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast: No such file or directory
cp: chown: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast: No such file or directory
cp: 
[SNIPPED BECAUSE OUTPUT WAS TOO LONG FOR GITHUB TO ACCEPT THE REQUEST]

cp: /Applications/Raycast.app/Contents/Info.plist: No such file or directory
cp: /Applications/Raycast.app/Contents/PkgInfo: No such file or directory
cp: utimensat: /Applications/Raycast.app/Contents: No such file or directory
cp: chown: /Applications/Raycast.app/Contents: No such file or directory
cp: chmod: /Applications/Raycast.app/Contents: No such file or directory
cp: chflags: /Applications/Raycast.app/Contents: No such file or directory
cp: /opt/homebrew/Caskroom/raycast/1.51.3/Raycast.app/Contents: unable to copy ACL to /Applications/Raycast.app/Contents: Operation not permitted

### What did you expect to happen?

Process should upgrade the application and replace it. The only solution is to delete the 0-byte application and then run `brew reinstall raycast` to create the new version of the application. I have also seen the same behavior with the following casks:

- obsidian
- stats
- visual-studio-code

I thought this might be a temporary bug that would clear itself, but I have been seeing this happen for about a month for these casks. All other casks seem to upgrade fine.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew upgrade raycast`
```

**Comment by dfioravanti** [comment]
I have the same problem for a similar amount of time with multiple crates. To me it happened with Firefox, Chrome, Spotify, Raycast and some others. Forcing a reinstall fixed it. If it helps, it looks like it happens to the first crate that brew tries to install after asking for the password

**Comment by carlocab** [comment]
@JBYoshi, do you mind taking a look at this?

**Comment by JBYoshi** [comment]
This looks like the same issue as https://github.com/Homebrew/homebrew-cask/issues/147383 and https://github.com/Homebrew/homebrew-cask/issues/147789. A fix should be coming in https://github.com/Homebrew/brew/pull/15483, but the workaround in the meantime is to go to System Settings > Security and Privacy > App Management and turn on the switch for your terminal. You can then fix any broken apps using `brew reinstall --force --cask <cask name>`.

**Comment by dfioravanti** [comment]
The workaround works, thanks a lot, it was getting really annoying to have to manually fix all the updates 🙏
