### ISSUE TITLE
Large .git history is unnecessarily stored locally

### ISSUE THREAD

**Issue by willsheppard** [Homebrew/brew#15497]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I'm frustrated using homebrew because it insists on re-downloading git history every time it is run, and I have very little disk space available.

I don't believe these files are required for normal operation of installing software through brew:
```
$ du -hs /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/.git/
360M	/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/.git/
$ du -hs /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/
434M	/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/
```

Would you consider using something like a shallow clone and/or any of these to reduce the disk space used?
* `--single-branch --branch=master`
* `--filter=blob:none`
* `--filter=tree:0`
* `--depth=1`

### What is the motivation for the feature?

Low disk space

### How will the feature be relevant to at least 90% of Homebrew users?

Everybody needs disk space.

Also it may be faster to update.

### What alternatives to the feature have been considered?

Get a new computer.

Delete the .git directories after every run.

Don't use homebrew, use a different package manager or install from source or dmg.

**Comment by MikeMcQuaid** [comment]
> Would you consider using something like a shallow clone

No, GitHub has asked us not to.

> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/

These aren't needed at all unless you've set `HOMEBREW_NO_INSTALL_FROM_API` and/or contribute to Homebrew.

**Comment by carlocab** [comment]
> It doesn't make sense to me that for example running a command like `brew cleanup --prune=all` to delete files results in re-downloading 700Mb of homebrew-core and homebrew-cask git repos.

Yes, that shouldn't happen.

> I feel like this has been raised many times before but I couldn't find any relevant info when I searched the issues, or the website FAQ, etc.

The experience your having seems out of the ordinary, so it doesn't surprise me for you to not find anything related.

> Does `--depth=1` have the same impact negative on github as a "shallow clone" ?

Yes.

> Is there really no way to prevent brew from downloading homebrew-core and homebrew-cask full git history whenever it runs? What about downloading a github release package instead of doing git clone?

If you install from the API, then you will not need any sort of clone of homebrew/core or homebrew/cask. You only need to download a small JSON file.

> And my final question is "if they're not needed at all, then why does brew download them?" they take up hundreds of gigabytes of space, and it takes 3-4 minutes for Homebrew to complete running the git clone commands for them.

I suspect there is an issue with your configuration.

> The same behaviour occurs whether HOMEBREW_NO_INSTALL_FROM_API is set to 1 or 0, and I am not contributing code changes to Homebrew. Developer mode is disabled.

Setting `HOMEBREW_NO_INSTALL_FROM_API` to any non-empty string (including `0`) will make Homebrew not use the API and result in clones of homebrew/core and/or homebrew/cask. If you want to install from the API, `unset HOMEBREW_NO_INSTALL_FROM_API`.

I suggest using the [discussions page](https://github.com/orgs/Homebrew/discussions) to ask for help if you're still having problems with this. Please include the output of `brew config` and `brew doctor` when you do this.
