### ISSUE TITLE
allow dependencies from user-taps

### ISSUE THREAD

**Issue by umlaeute** [Homebrew/brew#15490]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I propose to extend the `depends_on` clause in a formula to reference arbitrary URIs to formulae as dependencies.
while it is already theoretically possible to state
```ruby
   depends_on "https://example.com/supertap/Formula/aalib.rb"
```

this is practically useless as a `brew install` will just plainly refuse to install such a formula with
> Error: Non-checksummed download of aalib formula file from an arbitrary URL is unsupported! `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.

afaict, this is error is output whenever the formula is a proper URL: https://github.com/Homebrew/brew/blob/e96fd24a7328a4913de2f7c56fd2c97d9aaa4572/Library/Homebrew/formulary.rb#L539

i therefore suggest to extend the `depends_on` command with the possibility to provide a preferred source.

that is: allow the formula to specify non-URL dependencies but record a preference to resolve the dependency with the *current* tap (or some specific other tap):
```ruby
depends_on "aalib", preferred_source: :same # use the same tap as this formula was installed from
depends_on "ablib", preferred_source: :any # default; the current resolution scheme
depends_on "aclib", preferred_source: "foo/bar" # use https://github.com/foo/homebrew-bar/
depends_on "adlib", preferred_source: "https://git.example.com/supertap" # use the tap with this URL (normalized)
```

the last two examples should probably require the user to explicitly enable the taps before they can be used.
if they are not enabled, then the preferred_source is ignored (and resolving the formula falls back to the standard algorithm).
with the last example that (ideally) means, that the user needs to enable a tap (using whatever tap-name they like) that uses the given URL as it's source (e.g. `brew tap my/tap https://git.example.com/supertap`), probably with some URL normalization, so a trailing `/` doesn't change the anything...

### What is the motivation for the feature?

afaiu, a `depends_on` clause in a formula file can either be a `formula`, a tap-prefixed formula or a full URL.

the latter two come in handy, if you are maintaining your own tap and want to make sure, that a dependency is installed from the same tap as the current formula (e.g. if the tap provides some variant of an existing package)

Since the actual tap-name is user-specific (imagine a non-githubhosted tap that was activated with `brew tap my/tap https://git.example.com/supertap`), the tap-prefixed formula is of limited use.

The fully-qualified URI to the path (such as `depends_on "https://example.com/supertap/Formula/aalib.rb"`) might fix this, but unfortunately `brew install` currently refuses to install such formula with an error:
> Error: Non-checksummed download of aalib formula file from an arbitrary URL is unsupported! `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.

afaict this basically means, that there is currently *no way* to express dependencies to come form a specific tap.

### How will the feature be relevant to at least 90% of Homebrew users?

i do not think i can, as most Homebrew users will probably be happy with just the `homebrew/core` tap.

those however, who do use 3rd-party taps, will now have an improved dependency resolution

### What alternatives to the feature have been considered?

alternatives:
- add a brew-command to declare a given base URL to be trust-worthy (and thus not requiring the sha256 validation)
- add the possibility to provide a sha256-sum for the given formula:
   ```ruby
   depends_on "https://example.com/supertap/Formula/aalib.rb", sha256: "12345"
   ```

**Comment by MikeMcQuaid** [comment]
> that a dependency is installed from the same tap as the current formula (e.g. if the tap provides some variant of an existing package)

We intentionally don't allow or support this. If you want this: you need to change the name of the dependency instead. Otherwise you run a risk of breaking homebrew-core formulae.

You can use the `superuser/supertap/aalib` format but, as you've noted, it'll continue to use `aalib` from homebrew/core if already installed. I recommend `superuser/supertap/aalib-supertap` as a result. Sorry!
