### ISSUE TITLE
(3.6.0) "brew doctor" doesn't recognize symlinks, complains about additional "config" scripts (when it's the same)

### ISSUE THREAD

**Issue by nharkins** [Homebrew/brew#15502]
### `brew doctor` output

```shell
$ brew doctor
...
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/nharkins/homebrew/bin/pkg-config
...

$ which brew
/opt/homebrew/bin/brew

$ ls -l ~/homebrew
lrwxr-xr-x  1 nharkins  staff  13 May 31 14:34 /Users/nharkins/homebrew -> /opt/homebrew
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 3.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 93ea8cb2c40e1ef25f1489b0267526bd47bc8030
Last commit: 9 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1dd8cf1bf054a98b9bdbd610c87334186f129b13
Core tap last commit: 9 months ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### What were you trying to do (and why)?

brew doctor

### What happened (include all command output)?

see above

### What did you expect to happen?

warning should not be printed if it's a symlink.
obviously this is a very low priority issue.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
see above
```

**Comment by MikeMcQuaid** [comment]
You can't symlink like this, it's not supported and doesn't work how you want it to.

**Comment by nharkins** [comment]
@MikeMcQuaid, I installed mysql via brew when the directory was located at "~/homebrew", and it somehow baked in that path, such that it no longer works without the symlink:
```
$ sudo mysql -u root
dyld[82469]: Library not loaded: /Users/nharkins/homebrew/opt/zstd/lib/libzstd.1.dylib
  Referenced from: <45446242-F393-3DBD-AD8B-547BEE8EDB93> /opt/homebrew/Cellar/mysql/8.0.30_1/bin/mysql
  Reason: tried: '/Users/nharkins/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/nharkins/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/Users/nharkins/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file, not in dyld cache)
Abort trap: 6
```

**Comment by MikeMcQuaid** [comment]
@nharkins We don't support Homebrew installations outside the default prefix. You can use `brew bundle dump` to dump all your packages to a `Brewfile`, remove this installation and install to the default Homebrew location using `brew bundle`.
