### ISSUE TITLE
brew shellenv should not duplicate PATH entries

### ISSUE THREAD

**Issue by amancevice** [Homebrew/brew#15525]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

The `brew shellenv` helper should only output updates to PATH if `$HOMEBREW_PREFIX/bin` and/or `$HOMEBREW_PREFIX/sbin` are not already included.

### What is the motivation for the feature?

The `brew shellenv` helper currently outputs a command that will prepend the PATH with values for `$HOMEBREW_PREFIX/bin` and `$HOMEBREW_PREFIX/sbin`. However, sometimes the user will have already added these values to their PATH and the evaluated shellenv output duplicates entries in the PATH. This is almost certainly harmless but it would be nicer if the shellenv command checked the PATH first before adding items to it.

### How will the feature be relevant to at least 90% of Homebrew users?

Many of us probably have the recommended `eval "$(/opt/homebrew/bin/brew shellenv)"` directive in our shell profiles, as is recommended by the docs.

### What alternatives to the feature have been considered?

manually replicating the shellenv feature in my own profile

**Comment by amancevice** [comment]
closed in error

**Comment by MikeMcQuaid** [comment]
Closing because you've opened your own PR for this.

**Comment by amancevice** [comment]
Thanks, @MikeMcQuaid I wasn't sure if the protocol was to open an Issue for tracking purposes as well.
