### ISSUE TITLE
no pip command when "brew upgrade python"

### ISSUE THREAD

**Issue by baiyunping333** [Homebrew/brew#1552]
when I "brew upgrade && brew upgrade python", then the pip command missed! 
when upgrade python successfully, the python version is:
```
python --version
```
Python 2.7.12

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

Also, you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by baiyunping333** [comment]
sorry! I resolve this problem in the way: 
```
brew uninstall --ignore-dependencies --force python
brew install python
```

**Comment by MikeMcQuaid** [comment]
Glad you got it fixed. In future please file formulae issues on Homebrew/homebrew-core. Thanks!
