### ISSUE TITLE
Optimise rust-based formulas by setting `target-cpu`

### ISSUE THREAD

**Issue by Tokarak** [Homebrew/brew#15530]
### Verification

- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Rust has optional support for building with certain cpu features enabled. For example, arm-based macs, I would imagine, use only `apple-m1` or `apple-m2` cpus. `rustc --print cfg | grep target_feature | wc -l` gives me 28 features, while the `generic` target only has neon.

Specific features can also be specified — this can be useful if it's feasible to take the common features of a set of cpus.

If a better union set of cpu features can be found than `generic`, that can be an improvement to the ecosystem.

### What is the motivation for the feature?

This can increase peformance (sometimes marginally, other times significantly) for binaries built in Rust. 

### How will the feature be relevant to at least 90% of Homebrew users?

Mac users on official hardware should use only a small set of cpus. This means there is a high potential for improvement.

I'm worried about alienating the small number of hackingtosh and opencore-patcher users. Perphaps if the OS requires specific features, then those can be used. Otherwise, if a Hackingtosh can be built on any hardware, then it would seem that the only way to avoid alienation is to stick to the generic targets, or provide multiple builds (though I'm not looking to inflate the CI minutes).

This is particularly true for silicon based macs. AFAIK, there are no arm-based hackingtoshes, and there are only two, very similar cpu types. This could mean that it's completely safe to add these features cargo_args on silicon builds and distributions.

### What alternatives to the feature have been considered?

- Builds for each official cpu target, with generic target as backup
- Lowest-common-denominator builds for official hardware. Generic backup may or may not be needed.
- Add this only where it is convenient (eg for arm-based targets)
- Add this to local build only (very achievable, but building wastes more power than unspecialised binaries ever will  — alone, this is almost redundant)
- Don't fix what ain't broken

**Comment by carlocab** [comment]
For C/C++-based formulae, we set `-march` to the oldest supported architecture for a given OS version on Intel macOS. Currently that's `nehalem`, which is pretty old, but still an improvement over what you get when you omit `-march` (`penryn`).

It seems reasonable to do something similar for Rust. How do you set the desired `target-cpu` with `rustc`?

**Comment by alex** [comment]
FWIW starting with Rust 1.71 (coming out in 5.5 weeks) rust will default to targeting an M1 in macOS arm64 targets: https://github.com/rust-lang/rust/pull/109899/

**Comment by Bo98** [comment]
Ah excellent - we probably don't need to do anything here for arm64 then.

Not sure if there's anything worth doing for x86_64 or not.

**Comment by carlocab** [comment]
I don't think passing a `-C` flag to `cargo` is correct. From `cargo-install(1)`:
```
       -C PATH
           Changes the current working directory before executing any specified operations. This affects things like where cargo looks
           by default for the project manifest (Cargo.toml), as well as the directories searched for discovering .cargo/config.toml,
           for example.
```
Perhaps you need for this to be set in `RUSTFLAGS`?

**Comment by MikeMcQuaid** [comment]
> I don't know if homebrew differentiates between local and distribution builds.

We used to but intentionally don't any more to reduce the difference (and we don't support local builds anyway).

As a result, 

> -Ctarget-cpu=nehalem

sounds perfect.

**Comment by Tokarak** [comment]
`RUSTFLAGS='-C target-cpu=nehalem'`

**Comment by Tokarak** [comment]
Is anybody going to self-assign this issue? I don't mind creating a PR; I just need general advice or ideas on how to implement this in order to not waste too much time familiarising myself with the codebase.

**Comment by carlocab** [comment]
Off the top of my head, one important thing to note is that we'll want to use the same value returned from here instead of actually hard-coding `nehalem` or `apple-m1`:

https://github.com/Homebrew/brew/blob/9d01e1deafca35f30b709b5f6a031faaff9642ec/Library/Homebrew/extend/ENV/shared.rb#L273-L281

**Comment by MikeMcQuaid** [comment]
Sounds good, looking forward to the PR @Tokarak!

**Comment by MikeMcQuaid** [comment]
Closing to keep discussion in https://github.com/Homebrew/brew/pull/15544.



> Given that Rust already minimaxs the cpu without version context, it may be best to create a function which returns rust flags _with_ version context, similar to

Seems reasonable 👍🏻
