### ISSUE TITLE
`GitDownloadStrategy`:  kvi error since git 2.41.0

### ISSUE THREAD

**Issue by razvanazamfirei** [Homebrew/brew#15537]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/cask) checkout master
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.21-12-g520cfe5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 520cfe5694616facf67a4b0a1e80912203a8b995
Last commit: 24 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 72cb0f2fe6d20c1e8d159e883baab6215d12df3d
Core tap last commit: 27 hours ago
Core tap branch: master
Core tap JSON: 09 Jun 12:04 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTOREMOVE: set
HOMEBREW_BAT: set
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 30
HOMEBREW_EDITOR: subl -w
HOMEBREW_FORCE_BREWED_CA_CERTIFICATES: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_EMOJI: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_UPGRADE_GREEDY: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### What were you trying to do (and why)?

This is an issue that appears to have been introduced with git 2.41.0 (https://github.com/git/git/commit/9828453ff00b330c57daa3a8b672cbb5f0cdce34) and applies to casks using the `GitDownloadStrategy` (limited to `cask-fonts`). 

The initial install proceeds without any issues. However, any additional commands requiring git operations (e.g. `brew upgrade` or `brew fetch`) on the cloned repository error out. This can be reproduced by running `git fetch` in the cloned repository.

The relevant error is: 
```
BUG: config.c:129: kvi should not be set while parsing a config source 
```

### What happened (include all command output)?

```
❯ brew install --verbose --debug --force font-literata
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/git --version
==> Cloning https://github.com/google/fonts.git
/usr/bin/env git --git-dir /Users/Publius/Library/Caches/Homebrew/Cask/font-literata--git-sparse/.git status -s
Updating /Users/Publius/Library/Caches/Homebrew/Cask/font-literata--git-sparse
/usr/bin/env git config remote.origin.url https://github.com/google/fonts.git
/usr/bin/env git config remote.origin.fetch \+refs/heads/main:refs/remotes/origin/main
/usr/bin/env git config remote.origin.tagOpt --no-tags
/usr/bin/env git config advice.detachedHead false
/usr/bin/env git config core.fsmonitor false
/usr/bin/env git config origin.partialclonefilter blob:none
/usr/bin/env git config core.sparseCheckout true
/usr/bin/env git fetch origin
BUG: config.c:129: kvi should not be set while parsing a config source
Error: Download failed on Cask 'font-literata' with message: Failure while executing; `/usr/bin/env git fetch origin` was terminated by uncaught signal ABRT. Here's the output:
BUG: config.c:129: kvi should not be set while parsing a config source

/opt/homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/opt/homebrew/Library/Homebrew/system_command.rb:59:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:34:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:38:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:26:in `system_command!'
/opt/homebrew/Library/Homebrew/download_strategy.rb:161:in `command!'
/opt/homebrew/Library/Homebrew/download_strategy.rb:985:in `update_repo'
/opt/homebrew/Library/Homebrew/download_strategy.rb:878:in `update'
/opt/homebrew/Library/Homebrew/download_strategy.rb:205:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:172:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

Operation to proceed successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew fetch font-literata && brew fetch font-literata
```

**Comment by razvanazamfirei** [comment]
This was initially raised in https://github.com/Homebrew/homebrew-cask/issues/148499.

**Comment by carlocab** [comment]
Might be a Git bug. I suggest reporting this to Git.

**Comment by razvanazamfirei** [comment]
Looks like it! The issue goes away after removing `--filter=blob:none` from the clone call. Perhaps we could use this as an opportunity to move away from download strategies using `only_path`.

**Comment by MikeMcQuaid** [comment]
> Perhaps we could use this as an opportunity to move away from download strategies using `only_path`.

I don't think so, it was added specifically to enable us to move away from Subversion without having to clone the entire repository.

CC @hmarr in case you have any context on the Git issues here.

**Comment by hmarr** [comment]
@MikeMcQuaid I've just spent a bit of time looking into this. I don't have enough context on the git changes to understand why this has started happening now, and it may well be a git bug. It turns out we're using the "non-cone mode" of sparse checkouts, which is apparently [deprecated](https://git-scm.com/docs/git-sparse-checkout#_internalsnon_cone_problems), and it appears the bug is only hit when using non-cone mode.

We probably should report this back to the git team, but I've also put together a PR to move homebrew to cone-mode: https://github.com/Homebrew/brew/pull/15542.

**Comment by kevinm6** [comment]
@hmarr @MikeMcQuaid since I think it's related to the `git sparse-checkout` and to avoid to open another issue or create bad PR, as I've already reported in [Homebrew-Casks repo](https://github.com/Homebrew/homebrew-cask-fonts/issues/7718) to @razvanazamfirei , all casks that are using `git sparse-checkout` are upgraded every time if running `brew upgrade --greedy`.
I've already provided the debug output [here](https://github.com/Homebrew/homebrew-cask-fonts/issues/7718#issuecomment-1588978306)

**Comment by MikeMcQuaid** [comment]
> all casks that are using `git sparse-checkout` are upgraded every time if running `brew upgrade --greedy`

I'm pretty sure that's what `--greedy` does by design.

**Comment by kevinm6** [comment]
@MikeMcQuaid sorry, I meant that they are re-upgraded again every time, even if they are just upgraded.
