### ISSUE TITLE
New man facing error

### ISSUE THREAD

**Issue by Youguang** [Homebrew/brew#1553]
<img width="1163" alt="screen shot 2016-11-23 at 11 06 13 pm" src="https://cloud.githubusercontent.com/assets/7878120/20566858/8b656b10-b1d1-11e6-9826-26aecafae057.png">

Error after reinstall homebrew.

**Comment by MikeMcQuaid** [comment]
`cd $(brew --repo homebrew/core) && git reset --hard origin/master`

**Comment by Youguang** [comment]
Many many thanks!!! 😄
