### ISSUE TITLE
Setting for "prefer IPv4" or "disable IPv6"

### ISSUE THREAD

**Issue by NatoBoram** [Homebrew/brew#15534]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Add a global setting and/or command-line argument to 

* Prefer IPv4
* Prefer IPv6
* Disable IPv4
* Disable IPv6

### What is the motivation for the feature?

My home internet is provided by [TekSavvy](https://www.teksavvy.com/). In my area, they use the infrastructure of [Vidéotron](https://videotron.com).

While Vidéotron does provide IPv6 to its direct customers, it does not provide IPv6 for clients of resellers, such as TekSavvy. This is to encourage people to pay the higher price that they charge and to enforce their monopoly on my region.

Politics aside, I am using an accessibility service, [Hurricane Electric Free IPv6 Tunnel Broker](https://tunnelbroker.net/), at the router level to provide my home network with access to IPv6. However, download speeds with the tunnel brokers are atrocious, which is to be expected.

Being able to restrict Homebrew from downloading (not requesting package versions) via IPv6 would speed up the download process by a lot.

### How will the feature be relevant to at least 90% of Homebrew users?

People who live in Canada, have a monopoly enforced by the government for internet access in their region or otherwise use a tunnel broker or VPN might need such a config for Homebrew's downloads.

Admittedly, it might not be 90%+ of users.

### What alternatives to the feature have been considered?

Being able to offload the download process from Homebrew to another download manager like `aria2c` would also solve this issue, since other download managers are probably able to be configured for this kind of scenario.

**Comment by Bo98** [comment]
There is a curl option to choose IPv4 only (`--ipv4`) you can add it to your `.curlrc` and set `HOMEBREW_CURLRC=1`.

For anything more advanced than that, you're probably looking at something on system or DNS level. Basic rule of thumb is if it's impossible to do with curl alone, there's nothing much we can do ourselves.

**Comment by NatoBoram** [comment]
Thanks, that's exactly what I was looking for
