### ISSUE TITLE
brew audit fails with a false positive running homebrew on arch linux

### ISSUE THREAD

**Issue by ipatch** [Homebrew/brew#15540]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.21-17-gce96e0a
ORIGIN: https://github.com/Homebrew/brew
HEAD: ce96e0aafa3a05543b1ef1a9af10bd6ffd4bf816
Last commit: 3 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a6f3d0f9c395a720cc035bb06852d11f29db3da1
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 09 Jun 22:45 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: localhost:11.0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 15.0.7
Git: 2.40.1 => /bin/git
Curl: 8.1.1 => /bin/curl
Kernel: Linux 5.10.181-1-lts510 x86_64 GNU/Linux
OS: Arch Linux
Host glibc: 2.37
/usr/bin/gcc: 13.1.1
/usr/bin/ruby: 3.0.5
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

trying to understand why when running the below command i see audit exception fail on a gnu+linux system, but do not see any errors on a macos big sur box.

```
brew audit --new-formula -v freecad/freecad/pyside2@5.15.5 -v
```

output

```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/bundle clean
freecad/freecad
  * audit_exceptions/flat_namespace_allowlist.json references
    formulae or casks that are not found in the freecad/freecad tap.
    Invalid formulae or casks: freecad
```

that error 👆 seems to be only happening on gnu+linux install of homebrew

### What happened (include all command output)?

error posted above

### What did you expect to happen?

not see any errors

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap freecad/freecad/freecad
brew audit --new-formula -v freecad/freecad/pyside2@5.15.5 -v
# any of the formula can be used from the tap
```

below is a link to asciicast i recorded earlier in the day, may help for some to see a visual walk through of the issue

https://asciinema.org/a/590683

**Comment by ipatch** [comment]
and pretty issue maybe related to the logic in this ruby file

https://github.com/Homebrew/brew/blob/ce96e0aafa3a05543b1ef1a9af10bd6ffd4bf816/Library/Homebrew/tap_auditor.rb#L59C5-L82

**Comment by Bo98** [comment]
So is the issue that it isn't finding aliases?

Does it find correctly under, for example, `brew info freecad/freecad/freecad`?
Does `brew ruby -e "p Tap.fetch('freecad', 'freecad').aliases` output as you expect?

**Comment by ipatch** [comment]
> So is the issue that it isn't working with aliases?
> 
> I think I see the bug. Though don't understand how it works on macOS for you - the bug happens on my macOS machine. Only thing I can think of is your macOS machine having a `freecad.rb` lying around in your formula directory.

correct i think the audit is failing due to having an alias setup to freecad and that alias points to a _versioned_ version of freecad
