### ISSUE TITLE
formula brew analytics api for `build-error` category does not contain aws/tap/aws-sam-cli formula anymore

### ISSUE THREAD

**Issue by moelasmar** [Homebrew/brew#15570]
### `brew doctor` output

```shell
N/A
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
N/A
```

### What were you trying to do (and why)?

I opened [this issue](https://github.com/Homebrew/brew/issues/15528) before that the analytics APIs `https://formulae.brew.sh/api/analytics/install/30d.json`, and `https://formulae.brew.sh/api/analytics/build-error/30d.json` do not contain any information about our formula `aws/tap/aws-sam-cli`, and it was working fine till 5/30.

Now `https://formulae.brew.sh/api/analytics/install/30d.json` is working fine, but `https://formulae.brew.sh/api/analytics/build-error/30d.json` still does not contain any data about our formula.

### What happened (include all command output)?

when we execute `curl https://formulae.brew.sh/api/analytics/build-error/30d.json | jq -er '.items[] | select(.formula=="aws/tap/aws-sam-cli")'` nothing retuned.

### What did you expect to happen?

we expect some data to be returned, something like the following:
```
{
  "number": 297,
  "formula": "aws/tap/aws-sam-cli",
  "count": "134",
  "percent": "0.06"
}
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
run `curl https://formulae.brew.sh/api/analytics/build-error/30d.json | jq -er '.items[] | select(.formula=="aws/tap/aws-sam-cli")'`
```

**Comment by MikeMcQuaid** [comment]
This data now includes taps but had a certain amount of backfilling, an extremely manual process that will not be repeated. It may be more data here will show up here over time but we cannot debug this specifically for your formula, sorry. We'll review PRs to Homebrew/brew for sending analytics or for Homebrew/homebrew-formula-analytics for generating them if you can figure out and fix any problems there. Sorry.
