### ISSUE TITLE
Build `:all` bottles only on Linux runners

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#15589]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When a formula has an `:all` bottle, we should build it only on a Linux runner.

This will be relatively straightforward to do in [`brew determine-test-runners`](https://github.com/Homebrew/brew/blob/bb23116d3c8101304cc1932a442f568eb0c99c00/Library/Homebrew/dev-cmd/determine-test-runners.rb), but we will need some changes in [`test-bot`](https://github.com/Homebrew/homebrew-test-bot.git) and likely [`brew bottle`](https://github.com/Homebrew/brew/blob/bb23116d3c8101304cc1932a442f568eb0c99c00/Library/Homebrew/dev-cmd/bottle.rb) to support:
1. Creating the built as bottle as an `:all` bottle
2. Installing and then testing the built `:all` bottle on macOS runners to verify compatibility

### What is the motivation for the feature?

This will help conserve our macOS compute resources.

### How will the feature be relevant to at least 90% of Homebrew users?

More efficient use of Homebrew/core CI will be good for 99% of Homebrew users.

### What alternatives to the feature have been considered?

The status quo.

**Comment by dawidd6** [comment]
If we go this route, I think it would be great to have some kind of manual switch so we can use the old behavior. That would allow us to build a bottle for every supported OS separately when upstream decides to add something OS-specific. Otherwise we will have to find a workaround for that later when this happens.

**Comment by Bo98** [comment]
This is tricky because our tests are absolutely not exhaustive enough to test all code paths. For example, there are scripting languages libraries with mixed pure and native code.

Even text files can (rarely) differ between platforms.

**Comment by MikeMcQuaid** [comment]
I think this is a good idea, we should do it and have a label to opt-out of this behaviour. Similarly, if a formula that we expect to be `:all` ends up generating a non-`:all` bottle (which may also always imply `:any_no_relocation`, I can't remember): then that should fail the build.

**Comment by MikeMcQuaid** [comment]
> This is tricky because our tests are absolutely not exhaustive enough to test all code paths.

This is a good point and valid concern. If we had unlimited or even just trivially scalable compute/CI resources: I'd agree. As-is, though, there's enough bottlenecks that that I think this is worth a try as an experiment that we can fix forward or revert if it ends up being problematic.

**Comment by carlocab** [comment]
> This is tricky because our tests are absolutely not exhaustive enough to test all code paths. For example, there are scripting languages libraries with mixed pure and native code.
> 
> Even text files can differ between platforms, like pkg-config files.

We could run the build on a free ARM runner (or one with the shortest queue) and then check that the bottle checksum is identical and fail the build otherwise.

**Comment by Bo98** [comment]
I'd be fine with that yes. x86_64 Linux and arm64 macOS would cover a nice combination of different prefixes, different architectures, different OS.

**Comment by MikeMcQuaid** [comment]
Passing on this for now, there's been no movement in a year.
