### ISSUE TITLE
Honor dependencies found in PATH for new installs

### ISSUE THREAD

**Issue by billyjbryant** [Homebrew/brew#15592]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When installing a formula, homebrew does not currently honor PATH for finding dependencies. This results in dependency clobbering where-in if I have installed something already (outside of brew), the homebrew version may override the version I have installed elsewhere. 

### What is the motivation for the feature?

This can lead to improper or unexpected functionality if the dependency version installed by brew operates differently than the one installed via other means. 

Example is with any formula that has a dependency on `node`. I use `nvm` to manage node versions; however, any time I install or upgrade Homebrew formulae that depend on `node`, I get the brew version installed and it clobbers the `nvm` managed version. 

### How will the feature be relevant to at least 90% of Homebrew users?

Adding this feature reduces un-necessary resource waste by not installing a dependency that is otherwise already satisfied. This means less time to install the formula, less space required to install the formula, and no additional downloads of un-necessary 3rd party packages. 

### What alternatives to the feature have been considered?

The only other alternative is to know beforehand what dependencies your packages need and to use `--ignore-dependencies` which is not ideal as it ignores all dependencies, not just the ones you may already be providing. 

Another alternative is to use `brew unlink <formula>`, but this isn't ideal because it doesn't do anything to save on resource utilization by not installing an un-necessary (and duplicate) dependency in the first place.

**Comment by MikeMcQuaid** [comment]
> I get the brew version installed and it clobbers the `nvm` managed version.

It doesn't. This is an issue with how you've configured your `PATH`. If you want the `nvm` managed version to take priority: you need to ensure it's earlier in your `PATH` than Homebrew is.

> Adding this feature reduces un-necessary resource waste by not installing a dependency that is otherwise already satisfied.

I'm afraid it is not unnecessary and not satisfied. Note: this is how (almost) all package managers work.

**Comment by billyjbryant** [comment]
> Note: this is how (almost) all package managers work.

This is the worse reason NOT to fix something, ever. Just because its how everyone else does it, doesn't mean you can't strive to do better. 

Giving some option for users to block a dependency from being installed should be easy. 

> It doesn't. This is an issue with how you've configured your `PATH`. If you want the `nvm` managed version to take priority: you need to ensure it's earlier in your `PATH` than Homebrew is.

My issue is not isolated, there are plenty of other users with the exact same issue, as a simple google search will prove. 

By default, if you use Brew to install `nvm` then you use `nvm` to install `node`, the `nvm` bin for `node` will fall later in PATH than other `homebrew` installed formula. 

Therefore, without making any changes, if I use brew to install `nvm`, `nvm` to install `node` and then brew to install some other formula that deps on `node`, the brew version of `node` will override the `nvm` installed version. I shouldn't have to manually muck with my PATH to solve for that scenario. 

Either do a simple check for the formula's binary, it isn't that hard, or give a way to control a block list of formulae that should never be installed as a dependency. Hell, even restoring the `--no-node/--without-node` functionality would be better. 

> I'm afraid it is not unnecessary and not satisfied.

It is, if I have `node` already installed, a simple check for version can prove the dep to be satisfied and brew installing it again in a different location is 100% un-necessary. It wastes time, it wastes disk space, ie un-necessary. 

Not sure why you need to place the onus of solving a potential technical blocker on the consumer with the assumption that it is their mis-configuration that causes the issue.

**Comment by MikeMcQuaid** [comment]
@billyjbryant Somehow you repeatedly state how easy the problem is to solve but are unable to solve it yourself. There is more information that could help you here but I am no longer inclined to do so. Adjust your patronising, rude tone in future and you may get better results.
