### ISSUE TITLE
Support for multiple headers in Cask url stanza

### ISSUE THREAD

**Issue by donaldducky** [Homebrew/brew#15590]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

The ability to pass multiple headers similar to how a formula can pass them.

Example [here](https://github.com/homebrew/brew/issues/15169#issuecomment-1504229816):
```
  url "https://api.github.com/repos/Homebrew/homebrew-portable-ruby/releases/assets/103219629",
      headers: [
        "Accept: application/octet-stream",
        "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
      ]
```

One way I was able to see this work, locally, was by updating [Library/Homebrew/cask/url.rb](https://github.com/Homebrew/brew/blob/2ccdb26c45e0ac8c7d4a8c2cc78cd577c28a2707/Library/Homebrew/cask/url.rb#L35) to have a `headers` param next to header that is a `T.nilable(T::Array[String])`.

### What is the motivation for the feature?

I need to pass a couple of headers to trigger a download using the GitHub API and it requires two headers:
- `Accept: application/octet-stream`
- `Authorization: Bearer <token>`

The existing url stanza seems to support passing a [single header](https://docs.brew.sh/Cask-Cookbook#stanza-url).

### How will the feature be relevant to at least 90% of Homebrew users?

It would allow for passing more than one header in a cask, if the need arises.

The API would also be closer to that of a formula that allows passing `headers`.

#### Host assets elsewhere

This is an alternative that would require no code changes.

I would prefer not to take that route as it would introduce more infrastructure -- we already use GitHub and GH Actions, so all of this is already hooked up.

#### Support for Custom Download Strategy

Formulae support [custom download strategies](https://docs.brew.sh/Formula-Cookbook#specifying-the-download-strategy-explicitly).

This would be the most extensible way, opening doors for various other methods of downloading files, but may be quite a bit more involved.

#### Any other ways?

I'm open to trying other approaches, please let me know if there's something I may have missed! Thanks!

**Comment by Bo98** [comment]
Seems reasonable, and will likely be trivial to do with only changes in `cask/url.rb` needed (and ideally the documentation).

**Comment by donaldducky** [comment]
@Bo98 yeah, I tried it locally and it did what I needed.

The weird thing is we'll end up with 2 params: `header` and `headers`

It'd be nice to standardize on `headers` since it can support a single header and be closer to how a Formula defines it. The issue is it would be a breaking change requiring an update to every cask recipe (no thanks!).

Another option could be to re-use header and allow it to support an array as well, which is a bit more complicated.
```
header: T.nilable(T.any(String, T::Array[String]))
```

Let me know if you'd like me to open a PR 👌🏼

**Comment by MikeMcQuaid** [comment]
> Another option could be to re-use header and allow it to support an array as well, which is a bit more complicated.

This seems like it might be a better fit.

**Comment by MikeMcQuaid** [comment]
> Let me know if you'd like me to open a PR 👌🏼

Yes, please 🙇🏻!

**Comment by donaldducky** [comment]
Hi @MikeMcQuaid @Bo98 

The PR should be ready to go if we're still intereseted in this. Please let me know if there's anything else I need to do, thanks!
