### ISSUE TITLE
Add `CoreCaskTap` class

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#15597]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

We have a `CoreTap` class to represent Homebrew/homebrew-core with a `CoreTap.instance` method for repeatedly getting the same `Tap` instance for homebrew-core.

### What is the motivation for the feature?

We use `Tap.fetch("homebrew", "cask")` (or equivalent) in enough places in the Homebrew ecosystem that a `CoreCaskTap` would be useful. This would also allow the homebrew-cask API handling to be implemented in this class instead.

### How will the feature be relevant to at least 90% of Homebrew users?

It's not really but nicer code is nicer.

### What alternatives to the feature have been considered?

Leaving things as-is.

**Comment by osalbahr** [comment]
It looks like there would be a lot of commonality between CoreTap and CoreCaskTap. Would it be useful to have a parent class that includes the common pieces? Or would such inheritance introduce unnecessary complexity? Something akin to an abstract parent class. Not sure if that's a common paradigm in Ruby or in Homebrew.

**Comment by Bo98** [comment]
My thinking too was an abstract class, yes.

It's not really a Ruby thing, but you can see some uses in Homebrew if you search for `abstract!`

**Comment by MikeMcQuaid** [comment]
> It looks like there would be a lot of commonality between `CoreTap` and `CoreCaskTap`.

Hmm, I'm not sure if there would be? At least probably worth trying to implement this and seeing how much commonality there is.

**Comment by Bo98** [comment]
Yeah probably not looking at it further. `ensure_installed!` is probably something we don't need here.
