### ISSUE TITLE
usage of HOMEBREW_ARTIFACT_DOMAIN broken since 4.0.25

### ISSUE THREAD

**Issue by jgarec** [Homebrew/brew#15600]
### `brew doctor` output

```shell
brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.25-9-g3a813c3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3a813c30f36d8e2b1c7e7046ea4594d752aa3d85
Last commit: 4 hours ago
Core tap JSON: 27 Jun 12:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_ARTIFACT_DOMAIN: https://my-artifactory-url/artifactory/ghcr
HOMEBREW_CASK_OPTS: []
HOMEBREW_DOCKER_REGISTRY_BASIC_AUTH_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_GITHUB_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.16833849156
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Trying to download a package, or reinstall a package

### What happened (include all command output)?

```
==> fetching helm
==> Downloading https://ghcr.io/v2/homebrew/core/helm/manifests/3.12.1
curl: (22) The requests URL returned error: 401

Error: Failed to download resource "helm_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/helm/manifests/3.12.1
```

### What did you expect to happen?

switching back to 4.0.24 :
```
==> fetching helm
==> Downloading https://ghcr.io/v2/homebrew/core/helm/manifests/3.12.1
==> Downloading from https://my-artifactory-url/artifactory/ghcr/v2/homebrew/core/helm/manifests/3.12.1
...
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# get latest version
brew update

# install a package
brew install helm # or any package
=> it fails

cd /opt/homebrew
git checkout 4.0.24

# retry
brew install helm
=> it works
```

**Comment by jgarec** [comment]
Regression introduced by this commit : 
https://github.com/Homebrew/brew/commit/6d8b033effdae0efe00c97060c7c5349748d84d1

by @Bo98 

resolve_url_basename_time_file_size does not handle if a domain is set

**Comment by Bo98** [comment]
Yeah `HOMEBREW_ARTIFACT_DOMAIN` feels like a massive hack the way it's currently done but I'll come up with a quick fix anyhow.

**Comment by Bo98** [comment]
Please test #15601 and see if that fixes it for you.
