### ISSUE TITLE
Consider removing or changing the "open issues" message

### ISSUE THREAD

**Issue by Bo98** [Homebrew/brew#15608]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When a build error occurs, we print a list of open issues that happen that have the formula's name in it:

https://github.com/Homebrew/brew/blob/c5f4d040a7d8a405097abb1d881d25138171372d/Library/Homebrew/exceptions.rb#L543-L546

While this is sometimes useful, it's not guaranteed these issues, and in particular pull requests, are actually relevant.

Unfortunately, people treat this as the gospel and will comment on PRs pushing us to get a move on. While a gauge of how widespread an issue can be useful, there's a lot of the time where the issue the user experienced is not actually relevant to what the PR is solving.

We should either make it much more clearer that the issues & PRs may not be relevant, or just remove it entirely.

### What is the motivation for the feature?

One too many occurrences

### How will the feature be relevant to at least 90% of Homebrew users?

Less maintainer stress on tricky PRs -> better project health

### What alternatives to the feature have been considered?

Ignore the comments and move on

**Comment by MikeMcQuaid** [comment]
> Unfortunately, people treat this as the gospel and will comment on PRs pushing us to get a move on. While a gauge of how widespread an issue can be useful, there's a lot of the time where the issue the user experienced is not actually relevant to what the PR is solving.

Would it be better if this only output issues?

> We should either make it much more clearer that the issues & PRs may not be relevant, or just remove it entirely.

Agreed and not opposed to removing this. It also feels like most (all?) build errors are now from source which we don't technically support anyway.

**Comment by Bo98** [comment]
> Would it be better if this only output issues?

Probably. It's PRs that are the annoying ones.

> It also feels like most (all?) build errors are now from source which we don't technically support anyway.

I think so.

**Comment by MikeMcQuaid** [comment]
> Probably. It's PRs that are the annoying ones.

Cool could just drop those for now I reckon then.
