### ISSUE TITLE
Public Ruby API for casks

### ISSUE THREAD

**Issue by Bo98** [Homebrew/brew#15609]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Third-party tools can interface with formulae via Ruby by using `Formula[name]` to load a formula and calling some of the instance methods on those formula objects for gathering information on that formula.

No such API currently exists for casks. The facility to load casks is private API. And even if you get an instance of the cask through other means, all the methods on it are private API.

This is restrictive and will just lead people to ignoring what we call private API, meaning a rough road in terms of what we should and should not deprecate vs removing immediately.

### What is the motivation for the feature?

We should make the CLI parser public API given we use it in homebrew-core, homebrew-autoupdate etc, but it doesn't make sense to do so yet if `to_formulae_and_casks` returns objects that are private API.

### How will the feature be relevant to at least 90% of Homebrew users?

Improved stability of 3rd party tools (less likely to break on updates to Homebrew).

### What alternatives to the feature have been considered?

Don't bother and tell people to use formulae instead.

**Comment by MikeMcQuaid** [comment]
> This is restrictive and will just lead people to ignoring what we call private API, meaning a rough road in terms of what we should and should not deprecate vs removing immediately.

Honestly, I think this does and will happen regardless of how we handle things here.

> We should make the CLI parser public API given we use it in homebrew-core, homebrew-autoupdate etc, but it doesn't make sense to do so yet if `to_formulae_and_casks` returns objects that are private API.

Agreed we should make things public that we're using in `Homebrew/homebrew-*` repository commands.

Do you have a particular use-case you see for e.g. `Cask[token]` or similar specifically?

**Comment by Bo98** [comment]
> > This is restrictive and will just lead people to ignoring what we call private API, meaning a rough road in terms of what we should and should not deprecate vs removing immediately.
> 
> Honestly, I think this does and will happen regardless of how we handle things here.

I'm more talking about people trying to use public API but can't rather than people who don't care/refuse.



> Do you have a particular use-case you see for e.g. `Cask[token]` or similar specifically?

I see not reason why not to have that.

Searching around, I see CaskLoader references in homebrew-cask, as well as a few scattered about third-party stuff on GitHub ([1](https://github.com/Rylan12/homebrew-blame/blob/52e99e7a7635aa3f93b7a60e2a22ea18f3ab9520/cmd/blame.rb#L33, [2](https://github.com/danielbayley/homebrew-alfred/blob/7a115706e93daac28092f2bdf5daf81cd476e53b/Casks/alfred-theme-simple-light.rb#L4), [3](https://github.com/superatomic/homebrew-bundle-extensions/blob/56c97a91960fd66d59780960eab0f9e6dfa453f4/cmd/drop.rb#L63))

**Comment by MikeMcQuaid** [comment]
> I'm more talking about people trying to use public API but can't rather than people who don't care/refuse.

I guess I'm unclear that people are trying particularly hard to use only public APIs but: I do think it'd be helpful if we did have a sharper, clearer divide such that all APIs are either clearly public or clearly private.

> Searching around, I see CaskLoader references in homebrew-cask, as well as a few scattered about third-party stuff on GitHub ([1](https://github.com/Rylan12/homebrew-blame/blob/52e99e7a7635aa3f93b7a60e2a22ea18f3ab9520/cmd/blame.rb#L33), [2](https://github.com/danielbayley/homebrew-alfred/blob/7a115706e93daac28092f2bdf5daf81cd476e53b/Casks/alfred-theme-simple-light.rb#L4), [3](https://github.com/superatomic/homebrew-bundle-extensions/blob/56c97a91960fd66d59780960eab0f9e6dfa453f4/cmd/drop.rb#L63))

Good catch. At least 2) seems like the type of thing that would likely remain a private API.

**Comment by MikeMcQuaid** [comment]
Closing as "nice to have but haven't seen much demand for that". As usual in many of these cases, will review and probably merge a PR.
