### ISSUE TITLE
Cask Upgrade pulling obsolete versions

### ISSUE THREAD

**Issue by mattpackwood** [Homebrew/brew#15616]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.26
ORIGIN: https://github.com/Homebrew/brew
HEAD: eff45ef570f265e226f14ce91da72d7a6e7d516a
Last commit: 5 days ago
Core tap JSON: 02 Jul 13:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### What were you trying to do (and why)?

```
brew update
brew update
brew upgrade --greedy
```
brew tries to install the lower versions shown in "what happened"

If I run
```
brew update
brew update
brew outdated
```
all is fine

but if I run 
```
brew update
brew outdated
```
I get the messed-up version numbers 

### What happened (include all command output)?

Matt-Packwoods-iMac:~ $ brew upgrade
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pa
==> Upgrading 5 outdated packages:
anka-virtualization 3.3.2.166 -> 3.3.1.165
fing 3.4.0 -> 3.3.1
google-cloud-sdk 437.0.1 -> 436.0.0
multipass 1.12.1 -> 1.12.0
nvidia-geforce-now 2.0.53.148 -> 2.0.52.134

### What did you expect to happen?

Versions to be upgraded "up", not "down".

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew update
brew upgrade --greedy
```

**Comment by seanwo** [comment]
I am seeing the same thing, it seems like **https://formulae.brew.sh/api/cask.jws.json** is stale.

Old cask versions listed in https://formulae.brew.sh/api/cask.jws.json

Right now dropbox should be 177.4.5399 (and did yesterday) but is being reported as 176.4.5108 today...

Notice that brew outdated --greedy is showing dropbox at 176.4.5108 (an older version) right now.

$ brew outdated --greedy --verbose
dropbox (177.4.5399) != 176.4.5108
google-chrome (114.0.5735.198) != 114.0.5735.133
plex (1.72.2.3901,b7911c36) != 1.71.1.3888,b32ecaf8
zoom (5.15.2.19786) != 5.15.0.19644

3 days ago dropbox updated (and was updated on my system via brew):

https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/dropbox.rb
https://raw.githubusercontent.com/Homebrew/homebrew-cask/dac028992105c5384371200e5cb904651b5537e1/Casks/dropbox.rb

cask "dropbox" do
  arch arm: "&arch=arm64"

  version "177.4.5399"
...

https://formulae.brew.sh/api/cask.jws.json is being served up as an old file right now (176.4.5108)...

...
service\",\"homepage\":\"https://www.dropbox.com/\",\"url\":\"https://www.dropbox.com/download?plat=mac&full=1\",\"url_specs\":{},\"appcast\":null,\"version\":\"176.4.5108\",\"installed\":null,\"outdated\":false,\"sha256\":\"no_check\",\"artifacts\":[{\"uninstall\":[{\"launchctl\":\"com.dropbox.
...

**Comment by carlocab** [comment]
Might be a CDN issue. Works fine for me:
```
❯ curl -sL https://formulae.brew.sh/api/cask.jws.json | jq -r .payload | jq '.[932] | .token, .version'
"dropbox"
"177.4.5399"
```

**Comment by JedKoo** [comment]
Same issue.  

`curl -sL https://formulae.brew.sh/api/cask.jws.json | jq -r .payload | jq '.[933] | .token, .version'
"dropbox"
"176.4.5108"`

**Comment by carlocab** [comment]
What's the output of
```
curl -LI https://formulae.brew.sh/api/cask.jws.json
```
?

**Comment by Bo98** [comment]
I've found the cause of the issue that could cause the JSON to revert back to an old state and am working on a fix.

There's likely a deeper root cause with fetching the repo itself that will need investigating, but I'm working to make sure that doesn't result in going back to an old copy.

**Comment by JedKoo** [comment]
> What's the output of
> 
> ```
> curl -LI https://formulae.brew.sh/api/cask.jws.json
> ```
> 
> ?

is the output still needed? Bo98 has indentified the cause of the issue. Thanks!

**Comment by Bo98** [comment]
The time travelling issue should now be resolved. Thanks for the reports!
