### ISSUE TITLE
uninstalling python does not remove corresponding usr/local/lib/pythonX.XX/site-packages

### ISSUE THREAD

**Issue by mikeskk** [Homebrew/brew#15622]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.26
ORIGIN: https://github.com/Homebrew/brew
HEAD: eff45ef570f265e226f14ce91da72d7a6e7d516a
Last commit: 7 days ago
Core tap JSON: 04 Jul 04:17 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.FsFHaFG4YX/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
```

### What were you trying to do (and why)?

Uninstall an older python installation on which nothing else depends. 

To have a cleaner system and free up disk space

### What happened (include all command output)?

mihail@MBP-Mihail-3 ~ % brew uninstall python@3.10
Uninstalling /usr/local/Cellar/python@3.10/3.10.12_1... (3,097 files, 56.1MB)
mihail@MBP-Mihail-3 ~ % brew cleanup
mihail@MBP-Mihail-3 ~ % brew autoremove
mihail@MBP-Mihail-3 ~ % du -hs /usr/local/lib/python3.10 
1.1G	/usr/local/lib/python3.10

### What did you expect to happen?

Corresponding directory (/usr/local/lib/python3.10 in this case) to be removed (cleaned up).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
For example, for python@3.10, but same applies to other versions e.g. @3.7, @3.8 etc.:
mihail@MBP-Mihail-3 ~ % brew uninstall python@3.10
Uninstalling /usr/local/Cellar/python@3.10/3.10.12_1... (3,097 files, 56.1MB)
mihail@MBP-Mihail-3 ~ % brew cleanup
mihail@MBP-Mihail-3 ~ % brew autoremove
mihail@MBP-Mihail-3 ~ % du -hs /usr/local/lib/python3.10 
1.1G	/usr/local/lib/python3.10
mihail@MBP-Mihail-3 ~ % du -hs /usr/local/lib/python3.10/site-packages 
1.1G	/usr/local/lib/python3.10/site-packages
```

**Comment by MikeMcQuaid** [comment]
This is expected behaviour, sorry. These directories are intentionally kept between Python versions.

**Comment by mikeskk** [comment]
Thank you for the clarification on this. Would you mind elaborating just a little bit on the rationale behind preserving these directories? It's safe to manually remove these directories with rm -rf, just to confirm?

Understanding the reasoning would help me and potentially others in the community if they encounter this behaviour in the future.

**Comment by Bo98** [comment]
The reason is largely because these directories are not entirely managed by Homebrew. If you run `pip` yourself then it will also install there.

If there's nothing you've installed there that you want to keep, it is safe to delete.
