### ISSUE TITLE
Missing directories

### ISSUE THREAD

**Issue by andy9a9** [Homebrew/brew#15640]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.28-5-g9f9ae1e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9f9ae1edeb07d0e7790f18fd540ca76228a3eec2
Last commit: 2 hours ago
Core tap JSON: 06 Jul 18:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I was trying to bump a new cask following the guide from https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-cask.

### What happened (include all command output)?

```sh
cd "$(brew --repository homebrew/core)"
cd: no such file or directory: /opt/homebrew/Library/Taps/homebrew/homebrew-core
```
```sh
cd "$(brew --repository homebrew/cask)"
cd: no such file or directory: /opt/homebrew/Library/Taps/homebrew/homebrew-cask
```

### What did you expect to happen?

I was expecting, that it enters some correct directory. I completely uninstall the `homebrew`, but it didn't help.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. install `homebrew`
2. execute `cd "$(brew --repository homebrew/core)"`
```

**Comment by Bo98** [comment]
Yeah this looks like a doc issue to me.

The command to document will be `brew tap --force homebrew/cask`.

**Comment by andy9a9** [comment]
@MikeMcQuaid @Bo98 it woks, thanks!
