### ISSUE TITLE
brew update fails due to missing remote cask_tap_migrations.jws.json file

### ISSUE THREAD

**Issue by knksmith57** [Homebrew/brew#15641]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  go@1.16
  go@1.17
  go@1.18

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  openssl@3
  pyyaml
```

### Verification

- [ ] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.28-5-g9f9ae1e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9f9ae1edeb07d0e7790f18fd540ca76228a3eec2
Last commit: 12 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3d6cf55146b459100a6c099ff971ded78c0ecdd6
Core tap last commit: 66 minutes ago
Core tap branch: master
Core tap JSON: 07 Jul 04:01 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
```

### What were you trying to do (and why)?

Any attempt to `brew update` fails for me with the following:

```
❯ brew update
Error: Failed to download https://formulae.brew.sh/api/cask_tap_migrations.jws.json!
```

I enabled verbose/debug logging and narrowed and can confirm that, while I don't know what that file is for, it appears to be required, and it also appears to be missing right now on the remote server.

It looks like formulae.brew.sh builds are also currently failing with the exact same error: https://github.com/Homebrew/formulae.brew.sh/actions/runs/5482554854/jobs/9987998573#step:3:20

### What happened (include all command output)?

```
❯ brew update
Error: Failed to download https://formulae.brew.sh/api/cask_tap_migrations.jws.json!
```

### What did you expect to happen?

I expected `brew update` to succeed without error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
```

**Comment by knksmith57** [comment]
For a visibility boost, here's a link to a broken build: https://github.com/Homebrew/formulae.brew.sh/actions/runs/5482554854/jobs/9987998573#step:3:20

**Comment by knksmith57** [comment]
And here's what appears to be an auto-generated issue for that broken build: https://github.com/Homebrew/formulae.brew.sh/issues/923

**Comment by p-linnane** [comment]
We are aware and currently investigating.

**Comment by p-linnane** [comment]
This appears to be resolved. No changes were made before it started, and no changes have been made since. Seems like it was something on GitHub's end.
