### ISSUE TITLE
Improve error handling when an arch-specific URL isn't available

### ISSUE THREAD

**Issue by colindean** [Homebrew/brew#15646]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When a URL isn't available for the user's particular architecture, it'd be nice if they were explicitly told that or, at least for macOS, given the option to install the app for the architecture with a URL specified.

### What is the motivation for the feature?

An formula on our internal tap was recently updated, so a few people went to upgrade and got this error message.

```
$ brew upgrade myinternalapp
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:286:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:217:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:483:in `new'
```

This is befuddling because our tap has automation that runs `brew audit` as a check. The check passed. Here's the current version of the formula, with many internal names obfuscated:

```ruby
class Myinternalapp < Formula
  desc "CLI for myinternalapp"
  homepage "https://git.mycompany.com/myinternalapp/myinternalapp-cli"
  version "0.0.10"

  on_macos do
    on_intel do
      url "https://artifactory.mycompany.com/artifactory/team/myinternalapp/releases/v0.0.10/myinternalapp-v0.0.10-darwin_amd64.tar.gz"
      sha256 "9b80452635b62e54bce1e7db39d5d1f3c10c5f3bd955055a2abc3965fac1936b"
    end
  end

  resource "linux_distribution" do
    on_linux do
      url "https://artifactory.mycompany.com/artifactory/team/transporter/releases/v0.0.10/myinternalapp-v0.0.10-linux_amd64"
      sha256 "9e9756e9cebb386f9d7499807c6b432f99958c3ca55818e2757fd289f27014c5"
    end
  end

  def install
    if OS.mac?
      bin.install "myinternalapp"
    elsif OS.linux?
      resource("linux_distribution").stage { bin.install "linux/amd64/myinternalapp" }
    end
  end

  # Default test to pass auditing
  test do
    system "false"
  end
end

```

Note the omission of an `on_arm` block for the `on_macos` block.

This likely passed CI because our CI is x86_64, so that path would have been followed.

### How will the feature be relevant to at least 90% of Homebrew users?

This would likely only affect users of private taps since the core tap provides URLs for all supported architectures.

### What alternatives to the feature have been considered?

The obvious workaround is to supply a URL for that architecture, which in our case might end up being the same as the `on_intel` info or we just remove the architecture block. We don't currently have AS ARM64 build infrastructure so we don't build an ARM64 version of this app presently.

**Comment by carlocab** [comment]
I guess the difficulty is that Formula `url`s are supposed to be platform-agnostic source tarballs, so technically wrapping `url` in `on_*` blocks is an abuse of the formula DSL (though admittedly a sadly very common one).

You could probably drop the `on_intel` part of the `on_macos` block and then `odie` inside the `install` method if someone tries to do it on an M1 Mac.

**Comment by colindean** [comment]
Yeah, this is an abuse of the DSL to suit the case where the artifact is not source but a(n) (arch-specific) binary.

Maybe this is a tick on the count of reasons to let bottles take URLs.

**Comment by MikeMcQuaid** [comment]
> Yeah, this is an abuse of the DSL to suit the case where the artifact is not source but a(n) (arch-specific) binary.

Agreed. Think the messaging could be nicer though, I agree, and would review a PR to improve that. Closing out for now though.

> Maybe this is a tick on the count of reasons to let bottles take URLs.

Agreed. Similar, though, it's probably an even better reason to make the bottle DSL easier to use in this way.
