### ISSUE TITLE
"adopt" an already installed app , to upgrade it with brew in the future ?

### ISSUE THREAD

**Issue by avichou** [Homebrew/brew#15654]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

does anyone know the command to "adopt" a cask ? say you installed IINA with a dmg, how can you adopt it with brew, so it can be updated using "brew upgrade" moving onwards?

### What is the motivation for the feature?

ability to simply adopt the files and move them to brew bottles, instead of uninstalling the app, the reinstalling it from scratch with brew install --cask XXXX

### How will the feature be relevant to at least 90% of Homebrew users?

 many people discover homebrew only after they've installed a lot of their apps !

### What alternatives to the feature have been considered?

uninstalling the app and fresh install as cask ...

**Comment by Bo98** [comment]
Check out `brew install --adopt`. I believe that does what you're asking for.

**Comment by avichou** [comment]
> Check out `brew install --adopt`. I believe that does what you're asking for.

Thanks ! Where do I find more infos about this ?haven't found occurrences for this very syntax using Google 

In my case, it's be `brew install --adopt iina`? Or `brew install --adopt --cask iina `?

**Comment by bevanjkay** [comment]
The best option would be to run `brew install --adopt --cask iina` - note that it will only adopt the already installed files if the contents match those that would be installed by running `brew install --cask iina`. The alternative option is to use `brew install --cask --force iina` which will overwrite the application (but would not replace the settings/preferences of the application) [^1] - and then allow the application to be managed with Homebrew going forward.

[^1]: Note that I have not tried this explicitly with `iina` however have used this method with many other casks in the past.
