### ISSUE TITLE
Pruned 1 symbolic links from /usr/local - every day

### ISSUE THREAD

**Issue by guycalledseven** [Homebrew/brew#1566]
I have own brew update script which does

```
cd $(brew --repository) && git reset --hard origin/master
brew doctor
brew update
brew upgrade
brew cask update
brew cleanup
brew cask cleanup
brew prune
```

Since I reinstalled brew month ago, I am getting this error **every day**.

```
Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/share/man/man8/prlexec.8
```

After brew prune executes I get:

```Pruned 1 symbolic links from /usr/local```

After that, brew doctor does not report anything wrong with installation until **next morning** when pruning happens again, on the SAME file.

brew -v reports:
```
Homebrew 1.1.1-53-gc7267b1
Homebrew/homebrew-core (git revision a7f4b; last commit 2016-11-25)
```

system_profiler SPSoftwareDataType reports:
```
 System Version: macOS 10.12.1 (16B2555)
```
Thanks!

**Comment by MikeMcQuaid** [comment]
Can you try to run each command manually and then run `brew prune` and figure out which one produces the error? Then, after that, run `ls -lha /usr/local/share/man/man8/prlexec.8` and paste the output here. Thanks!

**Comment by guycalledseven** [comment]
Ok, I narrowed it down to - happens after reboot, Parallels.

brew doctor reports 

```
Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/share/man/man8/prlexec.8
```


```
$ ls -lha /usr/local/share/man/man8/prlexec.8
lrwxr-xr-x  1 root  staff   143B Dec  4 19:20 /usr/local/share/man/man8/prlexec.8@ -> /Applications/Parallels Desktop.app/Contents/Frameworks/ParallelsVirtualizationSDK.framework/Versions/Current/Resources/English.lproj/prlexec.8
```

**Comment by MikeMcQuaid** [comment]
Is it installed with Homebrew Cask? If so, they may be able to address it. Otherwise: file a bug with Parallels. Regardless, closing as not a Homebrew issue.

**Comment by KMamedoff** [comment]
@guycalledseven Still the same?

**Comment by guycalledseven** [comment]
@KMamedoff yes unfortunately. not even sure what to report to parallels.

**Comment by MikeMcQuaid** [comment]
Tell them they are creating a bad symlink:
`/usr/local/share/man/man8/prlexec.8` pointing to `/Applications/Parallels Desktop.app/Contents/Frameworks/ParallelsVirtualizationSDK.framework/Versions/Current/Resources/English.lproj/prlexec.8` (which doesn't exist).
