### ISSUE TITLE
Homebrew OS version detection broken for non-debian distributions

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/brew#15669]
### `brew doctor` output

```shell
N/A
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
N/A
```

### What were you trying to do (and why)?

Log analytics from non-debian systems

### What happened (include all command output)?

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/brew.sh#L584 evaluates to an empty `HOMEBREW_OS_VERSION` because `lsb_release` isn't installed by default on RedHat based distributions.

### What did you expect to happen?

HOMEBREW_OS_VERSION to represent the OS version as defined in `/etc/redhat-release` as a backup.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install ruby`
Observe that the analytics do not include an OS version
```

**Comment by SMillerDev** [comment]
`/etc/os-release` could work too

**Comment by siyath123** [comment]
[`brew install ruby` Observe that the analytics do not include an OS version](`brew install ruby` Observe that the analytics do not include an OS version) 

> ``
