### ISSUE TITLE
Feature: `brew edit`: auto`tap homebrew/core`

### ISSUE THREAD

**Issue by osalbahr** [Homebrew/brew#15664]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I think `brew edit` should automatically `tap homebrew/core` (maybe only if the formula actually exists in https://formulae.brew.sh/). If my memory serves me well, that used to be the case. Now, the behavior is the following:

```console
$ brew edit cbonsai
Usage: brew edit [options] [formula|cask ...]

Open a formula or cask in the editor set by EDITOR or HOMEBREW_EDITOR,
or open the Homebrew repository for editing if no formula is provided.

      --formula, --formulae        Treat all named arguments as formulae.
      --cask, --casks              Treat all named arguments as casks.
      --print-path                 Print the file path to be edited, without
                                   opening an editor.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.

Error: Invalid usage: cbonsai doesn't exist on disk.
Run brew create --set-name cbonsai $URL to create a new formula!
```

I found that tapping `homebrew/core` fixes it:
```console
$ brew tap homebrew/core
Warning: Tapping homebrew/core is no longer typically necessary.
Add --force if you are sure you need one.
==> Tapping homebrew/core
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 1543905, done.
remote: Counting objects: 100% (1543903/1543903), done.
remote: Compressing objects: 100% (456934/456934), done.
remote: Total 1543905 (delta 1083859), reused 1543817 (delta 1083802), pack-reused 2
Receiving objects: 100% (1543905/1543905), 402.14 MiB | 6.29 MiB/s, done.
Resolving deltas: 100% (1083859/1083859), done.
Tapped 3 commands and 6752 formulae (7,121 files, 460.7MB).
$ brew edit cbonsai
Warning: Unless `HOMEBREW_NO_INSTALL_FROM_API` is set when running
`brew install`, it will ignore your locally edited formula.
Editing /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cbonsai.rb
```

Let me know if not automatically tapping is intentional because of migrating from Git-cloned taps to JSON downloads. I don't think a contributor would mind a little extra storage overhead. And from the `brew edit` warning message, it shouldn't affect the default download method.

### What is the motivation for the feature?

I ran `brew edit` and noticed that 

### How will the feature be relevant to at least 90% of Homebrew users?

It will not. This feature is for beginner contributors who may not have read the full documentation yet (especially the part instructing the contributor to tap).

### What alternatives to the feature have been considered?

1. Manually tapping (what I did)
2. Adding to the error message (an alternative "feature")

---

### System information
```console
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 4.0.28-35-g18b4fc4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 18b4fc4ba5e9ac917479587e147a319adfddfe45
Last commit: 19 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dc62629778adfb8ee0b6be6a0f77c3da00025ea7
Core tap last commit: 24 minutes ago
Core tap branch: master
Core tap JSON: 11 Jul 17:01 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 22.04.2 LTS (jammy)
WSL: 2 (Microsoft Store)
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

**Comment by osalbahr** [comment]
The same goes for `brew audit` (and perhaps other related developer commands):
```console
$ brew doctor
Your system is ready to brew.
$ brew audit
Error: Calling brew audit is disabled! Use brew audit --eval-all or HOMEBREW_EVAL_ALL instead.
$ brew audit --eval-all
Error: No matching formulae or casks to audit!
$ HOMEBREW_EVAL_ALL=1 brew audit
Error: No matching formulae or casks to audit!
$ HOMEBREW_EVAL_ALL=1 brew audit --eval-all
Error: No matching formulae or casks to audit
```

**Comment by Bo98** [comment]
We probably won't do this for eval all given it's not clear from that alone whether you are interested in Homebrew/core, Homebrew/cask, both, or neither (just third-party taps).

I agree that error messages should however be improved at least.

**Comment by osalbahr** [comment]
> We probably won't do this for eval all given it's not clear from that alone whether you are interested in Homebrew/core, Homebrew/cask, both, or neither (just third-party taps).

Fair point. What about for one specific formula? i.e.

```console
$ brew audit cbonsai
Error: No available formula with the name "cbonsai".
```

Not sure what the error message should be, considering edge cases like `docker` being both the name of a formula and the name of a cask.

I'd say either a generic error message, or a behavior that is consistent with pre-api (I don't remember what the behavior was).

**Comment by osalbahr** [comment]
The README might also need to be edited based on the https://github.com/Homebrew/brew#contributine, since `brew audit --strict` without args is a recommended way to contribute.

**Comment by osalbahr** [comment]
I just realized that the `brew edit` behavior is fine since https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request instructs to `brew tap --force homebrew/core`. The issue with argument-less `brew audit` might just require updating the README. Let me know if I should open a new issue.
