### ISSUE TITLE
nmap caveat is using wrong HOMEBREW_CELLAR prefix on M1

### ISSUE THREAD

**Issue by tmoschou** [Homebrew/brew#15668]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs nmap
Error: No logs.

$ brew config
HOMEBREW_VERSION: 4.0.28-43-gdb4a95c
ORIGIN: https://github.com/Homebrew/brew
HEAD: db4a95cfbcf472dbfa43b58ee00f53e0ab373215
Last commit: 5 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6bbed3caa504890feeef0f656ae9b0a83cd2d4db
Core tap last commit: 4 months ago
Core tap branch: master
Core tap JSON: 11 Jul 23:46 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Installing nmap on apple M1 reports
```
==> Caveats
To use `ndiff`, you must do:
  chmod go-w /usr/local/Cellar
```

### What happened (include all command output)?

```
$ brew info nmap
==> nmap: stable 7.94 (bottled), HEAD
Port scanning utility for large networks
https://nmap.org/
Conflicts with:
  cern-ndiff (because both install `ndiff` binaries)
  ndiff (because both install `ndiff` binaries)
/opt/homebrew/Cellar/nmap/7.94_1 (830 files, 26.9MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-07-11 at 15:19:02
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nmap.rb
License: Cannot Represent
==> Dependencies
Required: liblinear ✔, libssh2 ✔, lua ✔, openssl@3 ✔, pcre ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To use `ndiff`, you must do:
  chmod go-w /usr/local/Cellar
==> Analytics
install: 0 (30 days), 0 (90 days), 0 (365 days)
install-on-request: 0 (30 days), 0 (90 days), 0 (365 days)
build-error: 29 (30 days)
```

### What did you expect to happen?

I would expect `/opt/homebrew/Cellar` or an unevaluated  `$(brew --prefix)/Cellar`. Seems `HOMEBREW_CELLAR` is already expanded in https://formulae.brew.sh/api/formula/nmap.json (never gets evaluated locally)

Also why does the formula require chmod change for the root folder `$HOMEBREW_CELLAR` ? - that doesn't seem right or at least why not just `Cellar/<formula>`? - which on my machine it is already `0755` . The change in https://github.com/Homebrew/homebrew-core/pull/133176 didn't make this clear.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install nmap`
```

**Comment by Bo98** [comment]
> Also why does the formula require chmod change for the root folder `$HOMEBREW_CELLAR` ? - that doesn't seem right or at least why not just `Cellar/<formula>`?

Yeah this is a bit weird. I'm not sure why a single formula needs Homebrew-wide changes.

> Seems `HOMEBREW_CELLAR` is already expanded in https://formulae.brew.sh/api/formula/nmap.json (never gets evaluated locally)

`HOMEBREW_CELLAR` is indeed not currently supported in caveats for the API. I'll take a look - seems easy enough to do on paper.

**Comment by carlocab** [comment]
> > Also why does the formula require chmod change for the root folder `$HOMEBREW_CELLAR` ? - that doesn't seem right or at least why not just `Cellar/<formula>`?
> 
> Yeah this is a bit weird. I'm not sure why a single formula needs Homebrew-wide changes.

It's because of this code inside `ndiff`:
```python3
# Check if the given directory, and all its parent directories, are owned and
# writable only by our euid or by root. If symlinks are present, they are
# recursively checked, up to a limit of SYMLINK_LIMIT.
# https://www.securecoding.cert.org/confluence/display/seccode/FIO15-C.+Ensure+that+file+operations+are+performed+in+a+secure+directory
# We use this code for Zenmap too
SYMLINK_LIMIT = 5
def is_secure_dir(path, num_symlinks=0):
    import os
    import os.path
    import stat

    if not os.path.isabs(path):
        return False

    if num_symlinks >= SYMLINK_LIMIT:
        return False

    dirs = []
    while True:
        dirs.append(path)
        dirname = os.path.dirname(path)
        if dirname == path:
            break
        path = dirname
    # Traverse root-to-leaf.
    dirs.reverse()

    for dir in dirs:
        if os.path.islink(dir):
            link = os.readlink(dir)
            if not is_secure_dir(link, num_symlinks + 1):
                return False
            continue
        if not os.path.isdir(dir):
            return False
        buf = os.stat(dir)
        if buf.st_uid != os.geteuid() and buf.st_uid != 0:
            return False
        if buf.st_mode & (stat.S_IWGRP | stat.S_IWOTH) != 0:
            return False

    return True

# Add the install_lib directory to sys.path, the list of directories searched
# for modules, but don't do it if the directory or its parents may be writable
# by other users. The following line is replaced by the installation program.
INSTALL_LIB = '/usr/local/Cellar/nmap/7.94_1/lib/python3.9/site-packages/'
if INSTALL_LIB is not None and is_secure_dir(INSTALL_LIB):
    sys.path.append(INSTALL_LIB) # lgtm[py/unreachable-statement]
```
