### ISSUE TITLE
`brew doctor` reads cask tap when installing from API is enabled

### ISSUE THREAD

**Issue by kidonng** [Homebrew/brew#15696]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unable to read from cask tap: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
```

### Verification

- [ ] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.28-89-g8bfe579
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8bfe579e8a6ebdf336fce3f97b3d6687ea3ffd8d
Last commit: 5 hours ago
Core tap JSON: 18 Jul 06:39 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_BAT_THEME: Tokyo Night Day
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
```

### What were you trying to do (and why)?

Checking my Homebrew installation.

### What happened (include all command output)?

Homebrew tries to read `homebrew/homebrew-cask` tap and failed.

### What did you expect to happen?

It should not do so as the cask tap is available through API, not a locally-cloned tap.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Run `brew doctor`
2. See warning
```

**Comment by MikeMcQuaid** [comment]
@kidonng can I see the output from `brew doctor --debug --verbose` and `brew tap --debug --verbose`? Thanks!
