### ISSUE TITLE
"Re-consider analytics message" showing after every `brew update`

### ISSUE THREAD

**Issue by maxzinkus** [Homebrew/brew#15718]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.29
ORIGIN: https://github.com/Homebrew/brew
HEAD: a2a05f96ef6215643f599e7bfeaacd4f34e7cd9a
Last commit: 2 days ago
Core tap JSON: 19 Jul 21:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_EMOJI: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew update` (for obvious reasons)

### What happened (include all command output)?

```
==> Homebrew's analytics have entirely moved to our InfluxDB instance in the EU.
We gather less data than before and have destroyed all Google Analytics data:
  https://docs.brew.sh/Analytics
Please reconsider re-enabling analytics to help our volunteer maintainers with:
  brew analytics on
```

### What did you expect to happen?

```
Updating Homebrew and Formulae...
<... no output here about brew analytics ...>
Updated 2 taps (homebrew/core and homebrew/cask).
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
```

**Comment by maxzinkus** [comment]
It only occurs when taps, casks, or formulae are being upgraded, not when no updates are available.

**Comment by Bo98** [comment]
This is already fixed and will be a part of next release soon.

**Comment by maxzinkus** [comment]
Thanks! Is there a tracking issue? If there is, can we link it here and close, and otherwise we can close out when the update ships. Appreciate it!
