### ISSUE TITLE
brew print this message "Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!" when i enter brew update

### ISSUE THREAD

**Issue by AlexKris** [Homebrew/brew#15720]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.29
ORIGIN: https://github.com/Homebrew/brew
HEAD: a2a05f96ef6215643f599e7bfeaacd4f34e7cd9a
Last commit: 2 days ago
Core tap JSON: 19 Jul 08:31 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

i enter command "brew update", it print "Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!", and i enter https://formulae.brew.sh/api/formula.jws.json in browser, it show 404 File not found

### What happened (include all command output)?

Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!

### What did you expect to happen?

a normal output of command "brew update"

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew doctor
> Your system is ready to brew.
brew update
> Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!
```

**Comment by webxmsj** [comment]
I have the same problem

**Comment by tucke** [comment]
==> Downloading https://formulae.brew.sh/api/formula.jws.json
curl: (22) The requested URL returned error: 404

**Comment by auto-generated** [comment]
俺也一样

**Comment by andyjhull** [comment]
Same here

works
`curl --fail -o /dev/null https://formulae.brew.sh/api/formula.jws.json`

fails
`curl --fail --compressed -o /dev/null https://formulae.brew.sh/api/formula.jws.json`

**Comment by tinyoverflow** [comment]
If you guys have the same problem but cannot contribute to the issue itself, just hit the 👍 reaction on the issue itself. "Me too" comments do not help help anybody.

Seems to have been fixed, though.

**Comment by Firestl** [comment]
brew upgrade
==> Downloading https://formulae.brew.sh/api/formula.jws.json
curl: (22) The requested URL returned error: 404

brew upgrade
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!

**Comment by andyjhull** [comment]
Yup, working for me now too.

> If you guys have the same problem but cannot contribute to the issue itself, just hit the 👍 reaction on the issue itself. "Me too" comments do not help help anybody.
> 
> Seems to have been fixed, though.

Thought it might help help to contribute that compression has something to do with the problem. ¯\_(ツ)_/¯

**Comment by tinyoverflow** [comment]
> Thought it might help help to contribute that compression has something to do with the problem. ¯\_(ツ)_/¯

Yes. I didn't mean you explicitly.
The brew.sh page is hosted on GitHub pages. It could have been just a coincidence, because the fix seems to have appeared quite recently and may not have made it to all servers/caches yet when you tried that. Just a guess.

**Comment by carlocab** [comment]
Yes, this is a GitHub Pages issue.

It'd be good to try to make access  to the JSON endpoint more reliable, but I'm not really sure what we can do that doesn't require a lot of extra maintenance.

**Comment by AlexKris** [comment]
This issue appears to have been fixed.
