### ISSUE TITLE
audit: `--strict --online`: "should use HTTPS rather than HTTP" false positive

### ISSUE THREAD

**Issue by osalbahr** [Homebrew/brew#15728]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.0-15-g5226cd4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5226cd434494991fae9da7eb6ab6a3095a16f563
Last commit: 5 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0a3bd62fb9b444f562f7e4e30dcedab66ed5a913
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 22 Jul 01:58 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.41.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 6.4.4-arch1-1 x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

What: `brew audit --strict --online xz`

Why: I was experimenting with `brew audit` on the most installed formulae and stumbled across it

### What happened (include all command output)?

```console
$ brew audit --strict --online xz
xz
  * Stable: The source URL http://archive.org/download/xz-5.4.3/xz-5.4.3.tar.gz should use HTTPS rather than HTTP
Error: 1 problem in 1 formula detected.
```

### What did you expect to happen?

I did not expect the [number 1 dependency, `xz` (365d)](https://formulae.brew.sh/analytics/install/365d/), to have `audit` errors, regardless of the flags being used.

Note: I don't know for sure if the same happens with other formulae, but I checked the last box because this seems to be about `brew audit` not `xz` so I decided to open the issue here as opposed to homebrew-core.

It seems that the `http` mirror is an intentional fallback from the url right before it, which is why I think this is a false positive.

```console
$ grep -nC1 'archive.org' "$(brew formula xz)"
5-  homepage "https://tukaani.org/xz/"
6:  # The archive.org mirror below needs to be manually created at `archive.org`.
7-  url "https://downloads.sourceforge.net/project/lzmautils/xz-5.4.3.tar.gz"
8-  mirror "https://tukaani.org/xz/xz-5.4.3.tar.gz"
9:  mirror "https://archive.org/download/xz-5.4.3/xz-5.4.3.tar.gz"
10:  mirror "http://archive.org/download/xz-5.4.3/xz-5.4.3.tar.gz"
11-  sha256 "1c382e0bc2e4e0af58398a903dd62fff7e510171d2de47a1ebe06d1528e9b7e9"
```

I don't know if `--strict --online` is expected to sometimes report false positives. It is not clear from the flags' documentation.
```console
...
      --strict                     Run additional, stricter style checks.
...
      --online                     Run additional, slower style checks that
                                   require a network connection.
...
```

Side note: I was unaware that using the flags in combination runs even more tests. In other words, `brew audit --strict xz` and `brew audit --online xz` both pass, but not `--strict --online`, which is not something I was able to find documented in [`brew help audit`](https://docs.brew.sh/Manpage#audit-options-formulacask-).

---

The http mirror was added in
- xz: add HTTP mirror (https://github.com/Homebrew/homebrew-core/commit/2fbf45c94a7432b6e161a238be1d5a6186436870)
- https://github.com/search?q=org%3AHomebrew%20SHA%3A2fbf45c94a7432b6e161a238be1d5a6186436870

CC @carlocab 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew audit --strict --online xz
```

**Comment by osalbahr** [comment]
If this is not expected behavior, would it be a viable solution for `brew audit --online --strict ...` to check if the http url is an intended fallback? Maybe also making sure that the http mirrors are all at the bottom. Thoughts?

**Comment by MikeMcQuaid** [comment]
Thanks for the write-up @osalbahr. A few notes:
- as a general principle: it's somewhat expected that `brew audit --strict --online` may fail for some stuff in Homebrew/homebrew-core as `--strict` audits are not enabled by default for that reason.
- in this case, though, it's two audits contradicting: https://github.com/Homebrew/brew/blob/3b3300546b5a4e40b74f4ee33cf225cca280defe/Library/Homebrew/resource_auditor.rb#L106-L113 this audit is ensuring that `curl`'s deps do have HTTP mirrors so that `curl` can be built on older systems lacking new enough certificates or protocols. 
- given this: you're right that this audit is a false-positive and should invert the `curl` audit's logic to not complain in those cases

Would you be up for opening a PR to address? Thanks!

**Comment by osalbahr** [comment]
> Would you be up for opening a PR to address? 

Sure! What would be a better behavior? Should the audit handle `curl`’s deps as a special case and ignore that there are http mirrors?

**Comment by MikeMcQuaid** [comment]
> Should the audit handle `curl`’s deps as a special case and ignore that there are http mirrors?

Exactly, thanks!

**Comment by MikeMcQuaid** [comment]
@osalbahr Are you working on a PR for this?

**Comment by osalbahr** [comment]
> @osalbahr Are you working on a PR for this?

Not currently but I do plan to give it a shot soon.
