### ISSUE TITLE
Improve handling of stale homebrew/core clones

### ISSUE THREAD

**Issue by shengslogar** [Homebrew/brew#15775]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.1.2-15-gf56f27b
ORIGIN: https://github.com/Homebrew/brew
HEAD: f56f27b0d65968edbb9d22b56db13021ca6ac56d
Last commit: 38 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dd0746f4307228e1cd5d35c74ece2b6c9efbd911
Core tap last commit: 3 weeks ago
Core tap branch: master
Core tap JSON: 27 Jul 15:50 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.1
  php@7.2
  php@7.4
```

### Verification

- [x] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

_Note: as seen above, my `brew doctor` does output some warnings, but these are all PHP-related which is not dependent on Python._

Install `python@3.11` as a dependency of `brew install aws-sam-cli`.

Interestingly, the installer is looking for `setuptools-67.6.1-py3-none-any.whl`:

```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ensurepip/_bundled/setuptools-67.6.1-py3-none-any.whl'
```

Navigating to the directory, I see a similarly-named file:

```
$ ls /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ensurepip/_bundled
pip-23.2.1-py3-none-any.whl		setuptools-68.0.0-py3-none-any.whl
```

Renaming this file to match the file it's looking for then yields a missing `pip-23.0.1-py3-none-any.whl`:

```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ensurepip/_bundled/pip-23.0.1-py3-none-any.whl'
```

Renaming `pip-23.2.1-py3-none-any.whl` to this filename then yields a missing `wheel-0.40.0-py3-none-any.whl`:

```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/Cellar/python@3.11/3.11.4_1/libexec/wheel-0.40.0-py3-none-any.whl'
```

I don't use Python outside of this so I'm not really sure what these errors are even about, but it seems like some sort of incorrectly-versioned dependency is being installed. I do have `python@3.9` installed successfully.

### What happened (include all command output)?

$ brew install python@3.11
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from 4c612ab32 to f56f27b0d.
No changes to formulae or casks.

==> Fetching python@3.11
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.11/manifests/3.11.4_1-1
##################################################################################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.11/blobs/sha256:0b34eff80378cb1157e1fefee56a89160e7a805226c32a2f24b09d5d17c1710e
##################################################################################################################################### 100.0%
==> Pouring python@3.11--3.11.4_1.arm64_ventura.bottle.1.tar.gz
==> /opt/homebrew/Cellar/python@3.11/3.11.4_1/bin/python3.11 -Im ensurepip
==> /opt/homebrew/Cellar/python@3.11/3.11.4_1/bin/python3.11 -Im pip install -v --no-deps --no-index --upgrade --isolated --target=/opt/home
Last 15 lines from /Users/sheng/Library/Logs/Homebrew/python@3.11/post_install.02.python3.11:
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 643, in _prepare_linked_requirement
    hash = hash_file(local_file.path)[0].hexdigest()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 616, in hash_file
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ensurepip/_bundled/setuptools-67.6.1-py3-none-any.whl'
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall python@3.11
==> Caveats
Python has been installed as
  /opt/homebrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /opt/homebrew/opt/python@3.11/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /opt/homebrew/lib/python3.11/site-packages

tkinter is no longer included with this formula, but it is available separately:
  brew install python-tk@3.11

gdbm (`dbm.gnu`) is no longer included in this formula, but it is available separately:
  brew install python-gdbm@3.11
`dbm.ndbm` changed database backends in Homebrew Python 3.11.
If you need to read a database from a previous Homebrew Python created via `dbm.ndbm`,
you'll need to read your database using the older version of Homebrew Python and convert to another format.
`dbm` still defaults to `dbm.gnu` when it is installed.

For more information about Homebrew and Python, see: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /opt/homebrew/Cellar/python@3.11/3.11.4_1: 3,281 files, 61.9MB
==> Running `brew cleanup python@3.11`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ brew postinstall python@3.11

==> Postinstalling python@3.11
==> /opt/homebrew/Cellar/python@3.11/3.11.4_1/bin/python3.11 -Im ensurepip
==> /opt/homebrew/Cellar/python@3.11/3.11.4_1/bin/python3.11 -Im pip install -v --no-deps --no-index --upgrade --isolated --target=/opt/homebrew/lib/python3.11/site-packages /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ensurepip/_bundled/setuptools-67.6.1-py3-none-any.whl /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/en
Last 15 lines from /Users/sheng/Library/Logs/Homebrew/python@3.11/post_install.02.python3.11:
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 643, in _prepare_linked_requirement
    hash = hash_file(local_file.path)[0].hexdigest()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 616, in hash_file
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ensurepip/_bundled/setuptools-67.6.1-py3-none-any.whl'
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall python@3.11

### What did you expect to happen?

Successful install with no errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
brew install python@3.11
brew postinstall python@3.11
```

**Comment by MikeMcQuaid** [comment]
> * you did not see the warning message about your stale homebrew/core clone

@carlocab is this something we've ever done? Agreed the others were bugs.

**Comment by MikeMcQuaid** [comment]
> * your homebrew/core clone is not being updated even if `brew developer` is on

Should be resolved by https://github.com/Homebrew/brew/pull/15780. Looking at `post_install` now.

**Comment by MikeMcQuaid** [comment]
> * `postinstall` is using a stale homebrew/core clone

Should be resolved by https://github.com/Homebrew/brew/pull/15781

**Comment by shengslogar** [comment]
Y'all are awesome 🔥
