### ISSUE TITLE
Support for installing a IPA files on ARM Macs

### ISSUE THREAD

**Issue by upintheairsheep** [Homebrew/brew#15779]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

IPA files are used to distribute iOS apps similar to APKs in Android. Support for iOS apps was added to macOS in Big Sur for ARM macs. It would be a pleasure to add support for their installation, and there are some apps that only work on iOS but can be bypassed via PlayCover or Sideloady, which I don’t know if it has a command line interface yet.

### What is the motivation for the feature?

iOS is way more used than macOS, similar to how Android is more used than Windows. Users of WinGet have suggested to add APK support to WinGet via the windows subsystem for android.

### How will the feature be relevant to at least 90% of Homebrew users?

It will enable developers of open source iOS applications to publish their packages to Homebrew Cask, allowing for a greater user base.

### What alternatives to the feature have been considered?

N/A

**Comment by MikeMcQuaid** [comment]
We'll review a PR for this but to leave this open as a feature request we'll need a lot more documentation on how this could be implemented. Thanks!
