### ISSUE TITLE
 undefined method `require_root' for nil:NilClass

### ISSUE THREAD

**Issue by DavaGordon** [Homebrew/brew#15785]
### `brew doctor` output

```shell
Im trying to install a package after upgrading brew and the package im trying to install was using plist which was causing an error and advised it should be service.require_root
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.2-28-ge700bc7
ORIGIN: https://github.com/Homebrew/brew
HEAD: e700bc799f0b9998f6c36a3172b5dc6054147f5b
Last commit: 3 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 29b3714e94fd8aa3f5e983c4cfbae1ae2bc81c40
Core tap last commit: 20 minutes ago
Core tap branch: master
Core tap JSON: 28 Jul 13:56 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 11.7.6-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

### What were you trying to do (and why)?

brew install valet-php@8.1  --build-from-source 

### What happened (include all command output)?

Error: valet-php@8.1: undefined method `require_root' for nil:NilClass

### What did you expect to happen?

It to install valet-php 8.1. i have another macbook with all the same spec and same packages which i updated a couple of months ago and all worked fine. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install valet-php@8.1  --build-from-source
```

**Comment by MikeMcQuaid** [comment]
We don't support the `valet-php@8.1` formula (it's not in an official Homebrew repository) or building from source.
