### ISSUE TITLE
macOS .pkg installer has empty "next steps", missing PATH instructions

### ISSUE THREAD

**Issue by svdarren** [Homebrew/brew#15793]
### `brew doctor` output

```shell
N/A, issue is with the .pkg installer
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
N/A
```

### What were you trying to do (and why)?

Install Homebrew on a new Mac using the .pkg installer.

### What happened (include all command output)?

Homebrew install with the .pkg was successful, but the "Next Steps" message was blank.

Installing with the curl command was also successful, including the instructions for setting the path.

### What did you expect to happen?

If the .pkg is not able or unwilling to modify .zprofile directly, then the next steps section should match that of the command line installer.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Download .pkg from GitHub release, follow instructions, read "Next Steps" section after completed install.
```

**Comment by MikeMcQuaid** [comment]
Thanks for the report! I'd seen this inside my VM but assumed it was a VM bug. Will take a look.
