### ISSUE TITLE
bump: can't find Repology for 'bonnie++' (or '*++')

### ISSUE THREAD

**Issue by osalbahr** [Homebrew/brew#15804]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.3-23-gd2863d0
ORIGIN: https://github.com/Homebrew/brew
HEAD: d2863d05b33177626e66fd4be75e92bcc3f14c99
Last commit: 53 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 037e893efc8e9ba8133d0f50766da73ef4ac2da2
Core tap last commit: 17 minutes ago
Core tap branch: master
Core tap JSON: 02 Aug 08:56 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.41.0 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.49-linuxkit-pr x86_64 GNU/Linux
OS: Ubuntu 22.04.2 LTS
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

What: `brew bump bonnie++`
Why: Double-checking that `bonnie++` is up-to-date

### What happened (include all command output)?

I noticed `Latest Repology version:  not found`.

```console
linuxbrew@4ac3d2c05f71:~$ brew bump bonnie++
==> bonnie++
Current formula version:  2.00a
Latest livecheck version: 2.00a
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none
```

### What did you expect to happen?

I expected it to match `livecheck` (according to https://repology.org/project/bonnie++/versions).

I think the "not found" comes from [bump.rb#L240](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump.rb#L240). I don't know how that if statement works.

Note: There is an apparent pattern with formulae that end with `++` (I haven't cross-checked them in https://repology.org).

<details>
<summary> brew bump '*++$' (effectively) </summary>
<pre>
brew bump $(curl -s https://formulae.brew.sh/api/analytics/install/365d.json | grep -o 'formula[^,]*' | awk -F ':' '{print $2}' | grep -o '[^"]*' | grep '++$' | grep -v '/') 
==> bonnie++
Current formula version:  2.00a
Latest livecheck version: 2.00a
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none

==> crf++
Current formula version:  0.58
Latest livecheck version: 0.58
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none

==> kimwitu++
Current formula version:  2.3.13
Latest livecheck version: 2.3.13
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none

==> libsigc++
Current formula version:  3.4.0
Latest livecheck version: 3.4.0
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none

==> libxml++
Current formula version:  2.42.2
Latest livecheck version: 2.42.2
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none

==> mysql++
Current formula version:  3.3.0
Latest livecheck version: 3.3.0
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none

==> mysql-connector-c++
Current formula version:  8.0.33
Latest livecheck version: 8.1.0
Latest Repology version:  not found
Open pull requests:       mysql-connector-c++ 8.1.0 (https://github.com/Homebrew/homebrew-core/pull/136964)
Closed pull requests:     none

==> pcre++
Current formula version:  0.9.5
Latest livecheck version: deprecated
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none

==> png++
Current formula version:  0.2.10
Latest livecheck version: 0.2.10
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none

==> quantum++
Current formula version:  4.3.2
Latest livecheck version: 4.3.2
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none

==> vera++
Current formula version:  1.3.0
Latest livecheck version: 1.3.0
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none

==> voro++
Current formula version:  0.4.6
Latest livecheck version: 0.4.6
Latest Repology version:  not found
Open pull requests:       none
Closed pull requests:     none
</pre>
</details>

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump bonnie++
- OR -
brew bump $(curl -s https://formulae.brew.sh/api/analytics/install/365d.json | grep -o 'formula[^,]*' | awk -F ':' '{print $2}' | grep -o '[^"]*' | grep '++$' | grep -v '/')
```

**Comment by MikeMcQuaid** [comment]
@osalbahr Will review a PR for this. If you're planning on implementing any of these: can you hold off on the new issues until you've got some PRs open? Thanks!

**Comment by osalbahr** [comment]
> If you're planning on implementing any of these

I am currently looking into them to see how I might go by implementing them, actually currently writing a draft reporting on my current progress thus far on one of them. But I thought I'd look into the implementation a bit more first to avoid frequently adding comments.

> can you hold off on the new issues until you've got some PRs open?

I can. But I'm not sure what the benefit of that might be. I stumble across (apparent) minor bugs, either by using Homebrew for my current projects or looking around to familiarize myself with the codebase.

I can see some benefit for holding off on a backlog of enhancement suggestions, but the current issue seemed more of a bug in an already-existing feature. I don't know if the maintainers were already aware, couldn't find an open issue, so I thought it might be a good idea to open one regardless how soon I might draft a PR. I'm not sure how much repology is relevant to the maintainers'/users' workflows compared to `livecheck`. I am also not sure how to interpret the help-wanted label, but it seems to mean that the bug is minor and can wait.

When  shouldn't I hold off? For example, I consistently get a Ruby error with backtrace when running `brew dump` that happens in different environments. Should I not open an issue on that either?

The stacktrace in question, for context:
```console
linuxbrew@1da5ef775864:~$ brew bump
==> Querying outdated formulae from Repology
532 outdated formulae found

==> Querying outdated casks from Repology
350 outdated casks found

Error: Parameter 'string': Expected type String, got type Symbol with value :Formulae
Caller: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:53
Definition: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/tty.rb:69
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:303:in `call_validation_error_handler'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:187:in `report_error'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_6.rb:80:in `block in create_validator_method_fast1'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:53:in `oh1_title'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:58:in `oh1'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bump.rb:139:in `block in bump'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bump.rb:132:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bump.rb:132:in `each_with_index'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bump.rb:132:in `bump'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
linuxbrew@1da5ef775864:~$ 
exit
dracula@REDACTED ~ % brew bump
==> Querying outdated formulae from Repology
532 outdated formulae found

==> Querying outdated casks from Repology
350 outdated casks found

Error: Parameter 'string': Expected type String, got type Symbol with value :Formulae
Caller: /usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:53
Definition: /usr/local/Homebrew/Library/Homebrew/utils/tty.rb:69
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:303:in `call_validation_error_handler'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:187:in `report_error'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_6.rb:80:in `block in create_validator_method_fast1'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:53:in `oh1_title'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:58:in `oh1'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:139:in `block in bump'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:132:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:132:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:132:in `bump'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

Like, it says "Please report this issue" but I'm not sure if I should take that literally. To the best of my knowledge, there are no ["Expected+type+String"](https://github.com/search?q=org%3AHomebrew+%22Expected+type+String%22&type=issues) open issues. I'm not aware if there might be discussion on this error elsewhere (outside of GitHub).

Again, I would like to reiterate that I am mainly trying to make sure I accurately understand when to hold off.

**Comment by osalbahr** [comment]
I see. I was taught to open an issue per PR, but I can see now that it's redundant. Thank you for clarifying!
