### ISSUE TITLE
Feature: `brew bump --installed`

### ISSUE THREAD

**Issue by osalbahr** [Homebrew/brew#15803]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`brew bump --installed`, similarly to `brew livecheck --installed`:
```console
% brew help livecheck | grep installed
...
      --installed                  Check formulae and casks that are currently
                                   installed.
```

### What is the motivation for the feature?

I'd like to be able to `brew bump` all of my installed formulae/casks, just in case `livecheck` was a false negative (example: [repo-location-update](https://github.com/search?q=org%3AHomebrew+label%3Arepo-location-update&type=pullrequests)) and double check with Repology. Or if I want to quickly see if there's already an open PR.

### How will the feature be relevant to at least 90% of Homebrew users?

Somewhat. It adds to automating outdated checks.

### What alternatives to the feature have been considered?

```console
$ brew bump $(brew list)
Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake
Warning: Treating docker as a formula. For the cask, use homebrew/cask/docker
...
```
(I do have the `cmake` formula but I'm actually using the `docker` cask)

**Comment by MikeMcQuaid** [comment]
Good idea, will review a PR to add this.

**Comment by Bo98** [comment]
> ```
> $ brew bump $(brew list)
> Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake
> Warning: Treating docker as a formula. For the cask, use homebrew/cask/docker
> ```

Bit off-topic for this particular issue, but I wonder if `brew list` should return `homebrew/cask/<name>` if it detects that there's a formula with the same name.

**Comment by osalbahr** [comment]
> Good idea, will review a PR to add this.

I'm looking into it. I opened [livecheck.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/livecheck.rb) and [bump.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump.rb) side by side hoping it might be an easy borrow. For `livecheck`, it looks like the filtering is done via `Formula.installed`. I can't find a similar construct in `def bump`. Is it to fetching the list via an `api_response`? If so, how feasible would it be to manually filter the response afterwards vs modify the api call itself?

> Bit off-topic for this particular issue, but I wonder if brew list should return homebrew/cask/<name> if it detects that there's a formula with the same name, maybe even homebrew/core/<name> for the vice versa to silence the warnings.

Maybe. It depends on how `brew list` is used. Is `brew [command] $(brew list)` a common construct? Many commands already have a `--installed` flag. I can also maybe see users running `brew list | grep <...>`.But if I had to guess, it's mostly for visual checking so I'd agree with `homebrew/cask/<name` but not sure about `homebrew/core/<name>`).

**Comment by MikeMcQuaid** [comment]
> 

Not sure off-hand, sorry. Try to hack something together in a draft PR and we can help more there.

> Is `brew [command] $(brew list)` a common construct?

yes

**Comment by EricFromCanada** [comment]
> I wonder if brew list should return homebrew/cask/<name> if it detects that there's a formula with the same name

Or have `brew list --full-name` return the full name for all installed formulae/casks, instead of only those not from core, which has always struck me as odd.

**Comment by apainintheneck** [comment]
I think the approach in `livecheck` should work for `bump` as well.

**Comment by osalbahr** [comment]
> > I wonder if brew list should return homebrew/cask/ if it detects that there's a formula with the same name
> 
> Or have `brew list --full-name` return the full name for all installed formulae/casks, instead of only those not from core, which has always struck me as odd.

I like this idea, then `bump $(brew list --full-name)` would be a de facto `bump --installed`.

> I think the approach in `livecheck` should work for `bump` as well.

I'm not sure how. The way `livecheck` fetches formulae is through `Formula.all` or `Formula.installed`.

https://github.com/Homebrew/brew/blob/22afefce8ea12552de0a8599297a8a8a6f5a78ef/Library/Homebrew/dev-cmd/livecheck.rb#L77-L90

I couldn't find a `Formula.` in [bump.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump.rb) so I'm not sure how it fetches the formulae/casks. But if I had to guess, it happens in `handle_api_response` if no args are given (`formulae_and_casks` is an empty array).

https://github.com/Homebrew/brew/blob/22afefce8ea12552de0a8599297a8a8a6f5a78ef/Library/Homebrew/dev-cmd/bump.rb#L82-L89
