### ISSUE TITLE
Which is getting precedence when installing an app via `brew install <token>`?

### ISSUE THREAD

**Issue by AndyTitu** [Homebrew/brew#15813]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I am mainly interested in determining the order of precedence for the place brew will pull the app from.

With the latest version of brew (on MacOS), `brew install <token>` will automatically detect if the app which was identified with the provided token is a cask or formula, and install the appropriate one. 

If we are only looking at homebrew-core and homebrew-cask for the sources of formula/casks, `brew` will first check if the given token matches an existing formula and, if not, it will check for casks.

The question becomes tricky when taps come into play. I would then expect the order of precedence to be:

1. first check formulas from core against the token
2. then check formulas from tapped taps against the token
3. then check casks from homebrew/cask against the token
4. then check casks from the tapped taps against the token

Is this already the case? Or is there a different order in place?

### What is the motivation for the feature?

-

### How will the feature be relevant to at least 90% of Homebrew users?

1. first check formulas from core against the token
2. then check formulas from tapped taps against the token
3. then check casks from homebrew/cask against the token
4. then check casks from the tapped taps against the token

Is this already the case? Or is there a different order in place?

### What alternatives to the feature have been considered?

-

**Comment by carlocab** [comment]
Please use the [discussions page](https://github.com/orgs/Homebrew/discussions) for questions. Thanks!
