### ISSUE TITLE
Add the ability to undo or rollback package installations

### ISSUE THREAD

**Issue by Joebeazelman** [Homebrew/brew#15857]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Proposed feature

The ability to rollback recipe installs and other local environment changes, such as build variables, would be a very useful feature. It would greatly help build and evaluate source-only distributed projects without polluting your local system with stray installs and environment variables. The feature could be implemented as a modal operation, for instance. The user initiates it by executing a command:

```
brew playground 
... 
brew playground --rollback
```

The command (could be called sandbox, temporary, or taste) creates a temporary environment capturing all the changes.  If the user does nothing and ends the current terminal session, the environment state becomes permanent. If the user, however, decides to restore to its previous state by undoing the captured changes.

### What is the motivation for the feature?

There are quite a few projects are only released as source files and not as binaries.  They must be built locally in order to use them. The build process often requires installing several brew recipes of libraries and tools, including modifying and creating environment variables, most of which are unneeded once the project has been built. It would useful to instruct brew to rollback the local system to its installation and environment state before the install. 

Such a feature could also serve to create an isolated for developing and testing new recipes similar to what Python environment management utilities offer.

### How will the feature be relevant to at least 90% of Homebrew users?

Brew is often used to fetch required tools and libraries to perform builds of popular open source projects.

### What alternatives to the feature have been considered?

The alternative is to painstakingly track all the recipes and environment variables modified before setting up the build environment. Quite often the build environment is highly complex requiring dozens of recipes.

**Comment by MikeMcQuaid** [comment]
The closest thing to this that already exists is making use of `brew bundle dump` and `brew bundle cleanup` to dump and restore state. That gets you the functionality you want. Happy to answer more questions about that here but closing issue for now as we're not implementing this specific version.
