### ISSUE TITLE
HTTPie formula no longer linked when cask also installed

### ISSUE THREAD

**Issue by jkbrzt** [Homebrew/brew#15854]
### `brew config` AND `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

```
$ brew config
HOMEBREW_VERSION: 4.1.4-30-g1a8f1be
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1a8f1be34bed35134ceed285dfaa90b3a82a11c1
Last commit: 16 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1d968739de1ce43d98e62a11896720c0d40c105c
Core tap last commit: 7 months ago
Core tap branch: master
Core tap JSON: 10 Aug 11:22 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: mvim -v
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```
---

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

---

### What were you trying to do (and why)?

HTTPie has both a formula and a cask:

1. [httpie/desktop](https://github.com/httpie/desktop) is in the `httpie` cask
2. [httpie/cli](https://github.com/httpie/cli) is in the `httpie` formula

I wanted to install both:

1. `brew install --cask httpie`
2. `brew install httpie`

---

### What happened (include all command output)?

**1/ HTTPie Desktop got installed ✅**

**2/ HTTPie CLI got installed but not linked ❌**

```
$ httpie --version
-bash: httpie: command not found
```

It’s because:

```
==> httpie cask is installed, skipping link.
```

Full output:

```
$ brew install httpie
Warning: Treating httpie as a formula. For the cask, use homebrew/cask/httpie
==> Fetching httpie
==> Downloading https://ghcr.io/v2/homebrew/core/httpie/manifests/3.2.2_1-1
Already downloaded: /Users/jakub/Library/Caches/Homebrew/downloads/bb5854a02e9fac7da79650872e045c81024c49de88d7cdec295bdd5a726df676--httpie-3.2.2_1-1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/httpie/blobs/sha256:ad6c60de07befbb3c1b87cad3f1032468830cba7886f319
Already downloaded: /Users/jakub/Library/Caches/Homebrew/downloads/b508cef6813471882e0a7ce0a67eb561e01c7bd4bdf2cd9c03c0262fb3620a52--httpie--3.2.2_1.arm64_ventura.bottle.1.tar.gz
==> Pouring httpie--3.2.2_1.arm64_ventura.bottle.1.tar.gz
==> httpie cask is installed, skipping link.
==> Caveats
Bash completion has been installed to:
  /opt/homebrew/etc/bash_completion.d
==> Summary
🍺  /opt/homebrew/Cellar/httpie/3.2.2_1: 483 files, 2.9MB
==> Running `brew cleanup httpie`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

---

### What did you expect to happen?

I expected the HTTPie formula to get linked as always:

```
$ httpie --version
3.2.2
```

The formula and cask are entirely independent. 

For the record, I find using the same name confusing, as do our users, and would prefer to use different names, but my [name change proposal](https://github.com/Homebrew/homebrew-cask/pull/139683) got rejected. I think the best solution would be to have `httpie-cli` formula and `httpie-desktop` cask (if renames could be handled gracefully).

---

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --cask httpie
brew install httpie
httpie --version
```

**Comment by MikeMcQuaid** [comment]
> 1. Is it now possible to rename formulas and/or casks gracefully?

Both.

> 2\. Would a PR introducing an option marking the formula independent of the eponymous cask be accepted?

Yeh, I think so. Would like clarification from @Homebrew/cask maintainers on what they'd prefer. I'd be fine with either option.

Thanks for the considerate responses @jakubroztocil 🙇🏻

**Comment by MikeMcQuaid** [comment]
Will review a PR for this but closing for now.

**Comment by MikeMcQuaid** [comment]
Track progress in https://github.com/Homebrew/homebrew-cask/issues/12822
