### ISSUE TITLE
`FormulaVersions` and `brew-update-report` does not handle sharding changes in git history

### ISSUE THREAD

**Issue by Bo98** [Homebrew/brew#15856]
### `brew doctor` output

```shell
(I'm on my phone, sorry.)

See https://github.com/Homebrew/homebrew-core/actions/runs/5822429562/job/15787035668
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
https://github.com/Homebrew/homebrew-core/actions/runs/5822429562/job/15787035668
```

### What were you trying to do (and why)?

* Build an all bottle with `brew bottle --merge`.
* View the updated casks in `brew update-report`.

### What happened (include all command output)?

`brew bottle` command output, see: https://github.com/Homebrew/homebrew-core/actions/runs/5822429562/job/15787035668
(Can't find the `brew update-report` output currently)

### What did you expect to happen?

Sharding changes in git history are respected correctly.

For `FormulaVersions`, we should detect that if `entry_name` begins with `^((?:Homebrew)?Formula)/(?:[a-z]|lib)/(.*)` that we also try it with `$1/$2` if nothing is found.

Similar logic applies to `brew update-report`. If the `git diff` detects a `A` in a sharded directory and `D` without a sharded directory in the same diff, we should remove those items from consideration (or maybe mark as modified).

### Step-by-step reproduction instructions (by running `brew` commands)

`brew bottle`, please see: https://github.com/Homebrew/homebrew-core/pull/139200. The formula must have not received an update since the sharding.
`brew update-report`, move your homebrew-cask back to before any sharding (with at least one cask installed) and run `brew update`.

**Comment by MikeMcQuaid** [comment]
Thanks for the write-up @Bo98.
