### ISSUE TITLE
Cannot uninstall dependents unless the dependencies' formulae still exist

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#1586]
CC @alyssais @MikeMcQuaid 

Reproducer:
```
$ brew pull https://github.com/Homebrew/homebrew-core/pull/7288
$ brew install -dvs gtkglext
$ brew install open-scene-graph
$ brew uninstall open-scene-graph
Error: No available formula with the name "pangox-compat"
$ brew uninstall --ignore-dependencies open-scene-graph
Uninstalling /usr/local/Cellar/open-scene-graph/3.5.5... (782 files, 36.9M)
```

As a result, I will now have to revision bump open-scene-graph even though it's not at all broken.

Edit: Note that open-scene-graph does not itself even depend on pangox-compat directly, only via gtkglext, which no longer depends on pangox-compat if 7288 has been pulled. So pangox-compat is not actually anywhere in the dependency tree of open-scene-graph when the error occurs:
```
iMac-TMP:homebrew-core joe$ brew deps open-scene-graph|tr '\n' ' '
atk cairo fontconfig freetype gdk-pixbuf gettext glib gobject-introspection gtk+ gtkglext harfbuzz hicolor-icon-theme icu4c jpeg libffi libpng libtiff openssl pango pcre pixman pkg-config shared-mime-info wget
```

**Comment by ilovezfs** [comment]
Oh and it also means that even if I revision bump it, users who are on the current version of open-scene-graph and try to uninstall it, instead of upgrading to the new revision, will hit this bug.

This affects any and all dependents that have boneyarded formulae.

**Comment by alyssais** [comment]
Thanks @ilovezfs.

This should be a pretty straightforward fix. Will have time to investigate properly over the next couple of days (probably mostly Wed).

Noting this here for my own benefit:

The problem is that `Keg#installed_dependents` resolves all of the formulae listed as dependencies in a tab with `Formulary.factory`, which raises an exception when the formula can't be found. Instead of this, it should catch that exception and fail gracefully in such a case.

**Comment by ilovezfs** [comment]
@alyssais thanks. I'll hold off on merging https://github.com/Homebrew/homebrew-core/pull/7288 because right now it contains two unnecessary revision bumps in order to compensate.

**Comment by MikeMcQuaid** [comment]
> The problem is that Keg#installed_dependents resolves all of the formulae listed as dependencies in a tab with Formulary.factory, which raises an exception when the formula can't be found. Instead of this, it should catch that exception and fail gracefully in such a case.

Yep, exactly 👍. `brew uninstall` should silently ignore either the requested formula or any dependencies not existing.

**Comment by ilovezfs** [comment]
Hmm... what if a tap has been uptapped ...

**Comment by MikeMcQuaid** [comment]
Not much we can do in that case. We need `brew uninstall foo` to work if there's `/usr/local/Cellar/foo` even if there's no more `foo` formulae in any tapped taps.

**Comment by ilovezfs** [comment]
I think we should still protect the dependents, though, even if the original formula file isn't there.

>The problem is that Keg#installed_dependents resolves all of the formulae listed as dependencies in a tab with Formulary.factory

Assuming we're not in the fallback code, doesn't the Cellar + the receipt have enough info to protect the kegs without having to have the formula file?

**Comment by ilovezfs** [comment]
Also, aren't we keeping copies of the original formula file in the .brew directory?

**Comment by MikeMcQuaid** [comment]
> I think we should still protect the dependents, though, even if the original formula file isn't there.

Yes, I see your argument now. If `Formula.factory` fails we should try to get a `Keg` with the same name and protect that if possible.

> Also, aren't we keeping copies of the original formula file in the .brew directory?

We are. We also aren't using them for anything currently.

**Comment by ilovezfs** [comment]
Going to proceed with merging https://github.com/Homebrew/homebrew-core/pull/7288 with the revision bumps.

**Comment by alyssais** [comment]
So, if a keg can't be resolved to a formula, just compare the full name in its install receipt to the full name specified in the runtime dependencies list of all the other install receipts?

**Comment by ilovezfs** [comment]
Is the install receipt updated with the new name during a formula rename migration?

**Comment by alyssais** [comment]
I don't believe it is
