### ISSUE TITLE
Remove sshpass from denylist

### ISSUE THREAD

**Issue by sprive** [Homebrew/brew#15879]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Use `fdesetup status` to confirm the Brew user has Filevault set to `On`.  This will signify the user's scripts are protected at rest using OS level encryption.  If `Off`, then blacklist sshpass. If `On`, then issue a caution and a prompt to allow continuing.

### What is the motivation for the feature?

Embedded Linux devices do not allow you to install SSH keys (read-only filesystems are quite common). Yet you must still automate against these targets.

### How will the feature be relevant to at least 90% of Homebrew users?

For the popular workaround, Brew users are being diverted to tap random Github repos.
This means non-novice users to have to vet what the repo is doing, but novice users are blindly pulling in unvetted repos..

### What alternatives to the feature have been considered?

Linux

**Comment by sprive** [comment]
1. https://github.com/Homebrew/brew/issues/13986
2. https://github.com/Homebrew/brew/issues/13254
3. https://github.com/Homebrew/brew/issues/7994
4. https://github.com/Homebrew/brew/issues/6236
5. https://github.com/Homebrew/brew/issues/5167
6. https://github.com/Homebrew/brew/issues/4198

It looks like ThumbsUp voting is disabled on these, but the current mechanism to discourage use does impact a lot of folk.

**Comment by sprive** [comment]
From #4198: _"I think this is the best fit for now. You can create a sshpass formula in a tap and if it's widely used we may consider it being added into Homebrew/core."_

Is that usage number published, and has sshpass reached that criteria?

**Comment by sprive** [comment]
Thanks!  Raising the security concerns I'm aware of, and presenting them as copy pasta, if this looks suitable..:
----

Using SSHpass presents the risk of sensitive server credentials becoming stolen by other accounts or software running on your Mac. If these credentials are work related or sensitive, before using SSHpass please discuss this with your Compliance team.  

When possible, using staged SSH keys is always easier and more secure than SSHpass. Use FileVault. If your Mac is stolen, at least the contents will be encrypted at rest. For the SSH targets, avoid using identical credentials on multiple systems. Use `.gitignore` files to prevent yourself or a coworker from accidentally committing files which you know contain secrets.

Caveats:
* When supplying credentials to your SSH command, it is slightly more secure to use `-f [filename]`, or -e ($SSHPASS env var) than the `-p` option. This is also a general best practice (keep secrets out of code, in case the code is shared or committed to source control).
* It is *always* a risk that any accounts, users or processes on your Mac can expose your plaintext password file or ENV vars.
----
Probably too lengthy for the command warning. Cheers.

**Comment by Gailchester** [comment]
This may be an unusual question but why do I keep receiving these emails
from Homebrew and what does it mean? I have a Samsung s23 ultra. I don't
have an iphone. Will someone please contact me regarding this? Email or Ph
405 -831- 6819 or 580-210-6115 Thanks! Gail Chester

**Comment by sprive** [comment]
What now needs to happen for this proposed change to move forward?

**Comment by MikeMcQuaid** [comment]
Someone needs to open the relevant PR.
