### ISSUE TITLE
Incorrect "run" instructions for arguments that require escaping/quoting

### ISSUE THREAD

**Issue by pzich** [Homebrew/brew#15871]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8b46501e4caa1cad75b30627c123127ab09a6a7
Last commit: 2 days ago
Core tap JSON: 16 Aug 00:03 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### What were you trying to do (and why)?

***BEFORE CLOSING THIS OUT:*** I know this "reference[s] a single formula", but I am 99% sure this issue is with brew and not this specific formula, I just don't know of another example with argument issues like this.

I was trying to install nginx (so I could use it as a web server) 

### What happened (include all command output)?

```
% brew install nginx 
==> Fetching nginx
==> Downloading https://ghcr.io/v2/homebrew/core/nginx/manifests/1.25.1_1
Already downloaded: /Users/pzich/Library/Caches/Homebrew/downloads/0ac25af4c890976dae08285baf4c9424fbd5055bd73c5b6ddbe9e5a9723d6fac--nginx-1.25.1_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/nginx/blobs/sha256:29aa5568ae9d
Already downloaded: /Users/pzich/Library/Caches/Homebrew/downloads/d8804ba46fe52a9cd7ea7aa52d3ed3be9392f48d01527cc15992c766151b10ba--nginx--1.25.1_1.arm64_ventura.bottle.tar.gz
==> Pouring nginx--1.25.1_1.arm64_ventura.bottle.tar.gz
==> Caveats
Docroot is: /opt/homebrew/var/www

The default port has been set in /opt/homebrew/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /opt/homebrew/etc/nginx/servers/.

To start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/nginx/bin/nginx -g daemon off;
==> Summary
🍺  /opt/homebrew/Cellar/nginx/1.25.1_1: 26 files, 2.4MB
==> Running `brew cleanup nginx`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

This states "if you don't want/need a background service you can just run" and the command `/opt/homebrew/opt/nginx/bin/nginx -g daemon off`, however, this is incorrect. Running that verbatim results in

```
% /opt/homebrew/opt/nginx/bin/nginx -g daemon off;
nginx: invalid option: "off"
```

Looking at the [JSON API](https://formulae.brew.sh/api/formula/nginx.json) this provides the following `.service.run` arguments:

```
% curl -s https://formulae.brew.sh/api/formula/nginx.json | jq .service.run
[
  "$HOMEBREW_PREFIX/opt/nginx/bin/nginx",
  "-g",
  "daemon off;"
]
```

It seems the printed command is essentially joining these strings with spaces, but the last argument needs to be escaped or quoted, i.e. `$HOMEBREW_PREFIX/opt/nginx/bin/nginx -g 'daemon off;'` which has the desired behavior.

### What did you expect to happen?

I would expect the `.service.run` arguments to be properly escaped and for the command that is printed to be runnable verbatim.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- `brew install nginx`
- Then read the output above
- See the error with `/opt/homebrew/opt/nginx/bin/nginx -g daemon off`
```

**Comment by MikeMcQuaid** [comment]
> * This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

It affects a single formula. Moving to homebrew-core.

**Comment by MikeMcQuaid** [comment]
Ignore previous comment, misread on first attempt (not had my caffeine yet, sorry!).
