### ISSUE TITLE
/etc/os-release folder does not exist

### ISSUE THREAD

**Issue by vascoferraz** [Homebrew/brew#15876]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.5-35-g020508b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 020508b7b337b7aa6b8ae6cd527a0ad3277c340e
Last commit: 3 hours ago
Core tap JSON: 16 Aug 10:26 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew style --fix`

### What happened (include all command output)?

Inspecting 1178 files
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

1178 files inspected, no offenses detected
Issues were detected, but none were auto-fixable. Use another format to see them.

In /opt/homebrew/Library/Homebrew/brew.sh line 596:
  [[ -n "${HOMEBREW_LINUX}" ]] && HOMEBREW_OS_VERSION="$(source /etc/os-release && echo "${PRETTY_NAME}")"
                                                                ^-------------^ SC1091 (info): Not following: /etc/os-release: openBinaryFile: does not exist (No such file or directory)
                                                                                         ^------------^ SC2154 (warning): PRETTY_NAME is referenced but not assigned.

For more information:
  https://www.shellcheck.net/wiki/SC2154 -- PRETTY_NAME is referenced but not...
  https://www.shellcheck.net/wiki/SC1091 -- Not following: /etc/os-release: o...

### What did you expect to happen?

I expect not to have these errors:

^-------------^ SC1091 (info): Not following: /etc/os-release: openBinaryFile: does not exist (No such file or directory)
^------------^ SC2154 (warning): PRETTY_NAME is referenced but not assigned.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
just run the command:
brew style --fix
```

**Comment by samford** [comment]
@MikeMcQuaid Do we want to also disable SC2154 for this line? #15877 only disabled SC1091, so I still see the SC2154 warning here:

```
In /opt/homebrew/Library/Homebrew/brew.sh line 598:
  [[ -n "${HOMEBREW_LINUX}" ]] && HOMEBREW_OS_VERSION="$(source /etc/os-release && echo "${PRETTY_NAME}")"
                                                                                         ^------------^ SC2154 (warning): PRETTY_NAME is referenced but not assigned.

For more information:
  https://www.shellcheck.net/wiki/SC2154 -- PRETTY_NAME is referenced but not...
```
