### ISSUE TITLE
brew doctor gave me instructions that could have bricked my terminal

### ISSUE THREAD

**Issue by Frazer** [Homebrew/brew#1589]
running brew doctor suggested I:
 Consider setting your PATH so that /usr/local/bin
occurs before /usr/bin. Here is a one-liner:
    echo export PATH='/usr/local/bin:$PATH' >> ~/.bash_profile

this bricked all new terminal windows.

shouldn't it be
    echo export PATH=/usr/local/bin:$PATH >> ~/.bash_profile

**Comment by MikeMcQuaid** [comment]
These instructions are correct if copy-pasted exactly.
