### ISSUE TITLE
Use a link validator for markdown docs

### ISSUE THREAD

**Issue by oregonpillow** [Homebrew/brew#15908]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I've noticed some invalid links within the documentation (i'm about to submit a merge request for some links), however invalid links can easiely be prevented by adding a link validator such as https://github.com/marketplace/actions/markdown-link-check

### What is the motivation for the feature?

Prevent invalid links getting into documentation

### How will the feature be relevant to at least 90% of Homebrew users?

It affects the integrity of all documentation

### What alternatives to the feature have been considered?

I haven't seen any proposed alternatives by others, nor can i think of a better solution than the one i suggested. Open to suggetions.

**Comment by osalbahr** [comment]
Thoughts on adding this as a local command, maybe `brew doc-check-links` or `brew style --links` or similar? An alternative I thought about is adding a CI that runs on edits to the documentation, but it would be cumbersome for someone to have to fix links in unrelated parts. And it wouldn’t be that useful if it only checks the added lines.

It would be easier if there’s already Homebrew formula that checks link rot, and have the dev command (something similarly to how `brew style` uses `shellcheck`). I don’t have a specific tool in mind though.

**Comment by Bo98** [comment]
We already have `html-proofer` (`bundle exec rake test`) but it seems it's not run in the existing docs workflow for some reason.

**Comment by oregonpillow** [comment]
I tested using `markdown-link-check` as a [job](https://github.com/oregonpillow/brew/actions/runs/5969582563/job/16195677442) just to see how many broken links we're dealing with, the majority are broken due to sharding issues (the rest were false positives since i didn't fine tune the link test parameters)

Looks like https://github.com/Homebrew/brew/pull/15891 , https://github.com/Homebrew/brew/pull/15904 will take care of those sharding link issues.

- The only broken internal link is https://github.com/Homebrew/brew/blob/3c8b4949baefb1f8166749ff1a3f0665afadedda/docs/How-To-Organize-AGM.md?plain=1#L147

- The only external broken link is https://github.com/Homebrew/brew/blob/3c8b4949baefb1f8166749ff1a3f0665afadedda/docs/Formula-Cookbook.md?plain=1#L796C6

I'm not familiar with `html-proofer` but since it's already implemented maybe this is best to continue using. Since external links can change sporadically, maybe these should be non-failing events within CI since it could interfere with future merge requests for unrelated issues.

**Comment by MikeMcQuaid** [comment]
> I'm not familiar with `html-proofer` but since it's already implemented maybe this is best to continue using.

Yes, this would be best to use.

> maybe these should be non-failing within CI since it could interfere with future merge requests for unrelated issues

I think it's still worth failing here so they can be addressed rather than ignored.

> Thoughts on adding this as a local command, maybe `brew doc-check-links` or `brew style --links` or similar?

Yeh, I'd rather we didn't add a new command for this.
