### ISSUE TITLE
homebrew-core/Formula/o /openssh.rb: Add configuration option for the LDNS DNSSEC Anchor file

### ISSUE THREAD

**Issue by manonfgoo** [Homebrew/brew#15905]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

To set the LDNS DNSSEC Anchor file one currently needs to set "anchor /path/to/unbound/root.key" in /etc/resolv.conf.  This is Suboptimal as systemprocesses overwrite the /etc/resolv.conf on MacOS or the user may want to use the DNSSEC Anchor different from what is configured in /etc/resolv.conf. This patch allows to set the DNSSEC Anchor File with the option LDNSAnchorFile.

Example:
ssh -oLDNSAnchorFile=/etc/unbound/root.key -oVerifyHostKeyDNS=yes example.com 

The PR has been submitted to the SSH Project as well:

https://github.com/openssh/openssh-portable/pull/432

[LDNSAnchorFile.patch](https://github.com/Homebrew/brew/files/12424764/LDNSAnchorFile.patch)

### What is the motivation for the feature?

Use DNSSEC for VerifyHostKeyDNS Easily

### How will the feature be relevant to at least 90% of [Security Aware] Homebrew users?

Everyone using SSH with VerifyHostKeyDNS on macOS who does not want to run unbound(8) on their computer

### What alternatives to the feature have been considered?

Run a local unbound(8) on your computer

**Comment by manonfgoo** [comment]
Sorry the link "https://github.com/Homebrew/homebrew-core/issues/new/choose" gets me back here

**Comment by ZhongRuoyu** [comment]
Feature requests should be submitted to [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) as pull requests. Also, for this patch specifically: please don't submit a patch that's not accepted by upstream maintainers, because we as packagers do not add new features to packages.

Thanks for your understanding.
