### ISSUE TITLE
Missing header files in GStreamer

### ISSUE THREAD

**Issue by challinan** [Homebrew/brew#15910]
### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 4.1.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3cd72905ce3d36a84994cc6c6b9ebbdafff4e922
Last commit: 6 days ago
Core tap JSON: 24 Aug 18:37 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### What were you trying to do (and why)?

I am trying to compile a C program which depends on some missing Gstreamer header files.  The file I am trying to compile is rtsp-media-factory.c, part of the GStreamer git source.  This file #includes rtsp-server-internal.h, which is missing from the Homebrew GStreamer install.  Upon further inspection, the following two files are missing:

rtsp-latency-bin.h is missing
rtsp-server-internal.h is missing

### What happened (include all command output)?

Compile fails due to missing headers as listed above.

additional info:
`$ which gst-launch-1.0
/opt/homebrew/bin/gst-launch-1.0

$ gst-launch-1.0 --version
gst-launch-1.0 version 1.22.5
GStreamer 1.22.5
https://github.com/Homebrew/homebrew-core`

### What did you expect to happen?

I expect the files to be part of the Homebrew GStreamer package

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above.
```

**Comment by Bo98** [comment]
These are internal headers not for outside use so this is intentional, and is controlled by upstream rather than us. They're unlikely to exist in other distributions (Debian etc.) as well.

See upstream's build script: https://github.com/GStreamer/gstreamer/blob/ff435c80a246ca74c5627aab996584c8a420097d/subprojects/gst-rtsp-server/gst/rtsp-server/meson.build#L28-L56
