### ISSUE TITLE
Allow HOMEBREW_PREFIX replacement in external patches

### ISSUE THREAD

**Issue by gaborbernat** [Homebrew/brew#15925]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

This follows up the recommendation from https://github.com/Homebrew/brew/pull/15841, to use:

```
patch do
  url "file://#{__dir__}/Formula.patch_name.diff"
end
```
for externally stored patches. My problem is that in this the following rule is not applied:

> "In embedded patches, the string “HOMEBREW_PREFIX” is replaced with the value of the constant HOMEBREW_PREFIX before the patch is applied."

So I would like to enable this replacement (perhaps guarded by a boolean flag?).

### What is the motivation for the feature?

This would allow us to move the embeded patches to external diff files.

### How will the feature be relevant to at least 90% of Homebrew users?

Would make maintaining complex formulas with large diffs easier, and easier to configure formatter onto the formula files (as the formatter would not impact the diffs).

### What alternatives to the feature have been considered?

Keeping the diff embeded means I cannot use formatter on the formula file.

**Comment by MikeMcQuaid** [comment]
Passing on this for now. Will still consider a PR but it seems that it's not widely demanded functionality.
