### ISSUE TITLE
Vite dev server crashing due to circular reference in Mechanize gem

### ISSUE THREAD

**Issue by lauren-murj** [Homebrew/brew#15928]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: d4444b563e24ac7c05a93121c464c02dfa04d44f
Last commit: 5 days ago
Core tap JSON: 01 Sep 16:27 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Using Vite dev server for local development of React site

This issue has also been reported by @kolchurinvv
to: [mechanize gem maintainers](https://github.com/sparklemotion/mechanize/discussions/620)
and [Homebrew](https://github.com/orgs/Homebrew/discussions/4624)
but was ultimately directed here
They include more data 

### input
`npm run vite --mode development --open http://localhost:5173/`

### output
VITE v4.4.9  ready in 264 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ELOOP: too many symbolic links encountered, stat '/opt/homebrew/Library/Homebrew/vendor/gems/mechanize-2.9.1/mechanize-2.9.1'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///Users/lauren.orsini/Repos/clientv3/client/node_modules/vite/dist/node/chunks/dep-df561101.js:53727:10)
    at FsEventsHandler._handleFsEventsSymlink (file:///Users/lauren.orsini/Repos/clientv3/client/node_modules/vite/dist/node/chunks/dep-df561101.js:52953:18) {
  errno: -62,
  code: 'ELOOP',
  syscall: 'stat',
  path: '/opt/homebrew/Library/Homebrew/vendor/gems/mechanize-2.9.1/mechanize-2.9.1'
}

### What did you expect to happen?

Development server to run normally and not crash

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
no brew commands
```

**Comment by kolchurinvv** [comment]
@lauren-murj thank you for submitting the issue

**Comment by Bo98** [comment]
We'll fix the stray symlink, because it is there by error, but why is vite looking at random Homebrew files? Seems extremely fragile.

**Comment by kolchurinvv** [comment]
I guess it's worth trying to get in touch with vite maintainers. What a rabbit hole 😀
