### ISSUE TITLE
Homebrew cask versions not tracked (incorrect) for casks with auto update

### ISSUE THREAD

**Issue by alexanderxc** [Homebrew/brew#15932]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When you install any given casks with 'auto_udpate: true' the casks populates brew manifest with a the correct version number. However, as time goes by, and the cask uses its auto-updater tool to install a new version, such version is no longer tracked by Homebrew. This generates a very unpleasant behavior by which the users looses track of the currently installed version.

### What is the motivation for the feature?

Although it might seems irrelevant, brew was born to be THE macOS missing package manager and, as such, it should always be able to keep an updated inventory (casks manifests) that reflect the currently installed version, even after a specific cask has been updated by its self updater.

### How will the feature be relevant to at least 90% of Homebrew users?

It is relevant as per point above. As a user I leverage 'brew list --casks --versions' to list installed packages and their current versions. This currently is not that meaningful as the list will be reflect correct versions only on casks that do not have auto_update, therefore the user does not have a real visibility of the update status with this command.

### What alternatives to the feature have been considered?

The propose solution is to implement a function that, upon execution of `brew update`, it could scan / cat all the manifests of the app with `auto_update: 'true'` and parse their correct version with the correct value and possibly update it's internal manifest (of brew) as that will reflect the correct version of the casks installed. 

This will allow better version monitoring.

**Comment by MikeMcQuaid** [comment]
Passing on this. These are always going to drift because they are updated outside of Homebrew. `brew upgrade --greedy` allows you to keep these in sync if desired.

**Comment by alexanderxc** [comment]
@MikeMcQuaid I beg to differ in regards of version drifting. My reasoning was to implement a script/function to work as follows: 

1. at the end of the `brew update`, once brew has updated formulas and casks by getting the updated manifest, all packages with auto_udpate may be listed and stored in an array with their brew last known version
```
brew info --cask --json=v2 $(brew list --cask) | jq -r '.casks[]|select(.auto_updates==true)|.token'
```
2. based on that list of app, the actual (currently installed) version could be retrieved, e.g. via
```
defaults read /Applications/App.app/Contents/Info.plist CFBundleShortVersionString
```
3. Recursively in this list the current version from app bundle is checked against the last known of brew. If `actual` >= `known` then it might be possible to instruct brew to consider the package as finale and base all future action on the updated formula/manifest. 

I'm not sure about the implication of such workflow in homebrew, however, I recently stumbled upon a possible use-case. 
I recently installed WhatsApp app via its cask and this app is about to be completely updated as a new macOS silicon version has just been released. This app change entirely the folder used and "zap" files and folders structure. I'm afraid that if I download the latest version by auto updated (from the app) and, at a later stage, uninstalled the cask via `brew` the zap instruction would have been incorrect as. brew would have used the reference from the previous version (not knowing which was the actual version installed on disk). 

Again, I realize that this is more a exercise of style rather than a real issue and there are ways and workaround for these (i.e. `--greedy`), however, it would be a real nite to have feature that might make homebrew more elegant and convenient. 

Hope you might reconsider. Unfortunately, I'm not able to create a PR for such a feature. 

Thanks for the great work!

**Comment by MikeMcQuaid** [comment]
> uninstalled the cask via `brew` the zap instruction would have been incorrect as. brew would have used the reference from the previous version (not knowing which was the actual version installed on disk).

If this is the case and it's a reproducible bug: please report it. That's not what you're describing here, though, and it sounds like worries about a hypothetical bug rather than an actual one.



> Again, I realize that this is more a exercise of style rather than a real issue and there are ways and workaround for these (i.e. `--greedy`), however, it would be a real nite to have feature that might make homebrew more elegant and convenient.

`--greedy` is not a workaround: it's the functionality you want. The functionality you describe is not one that e.g. I want.

> Hope you might reconsider. Unfortunately, I'm not able to create a PR for such a feature.

This was unlikely to be accepted even if you created the PR and without it: it seems to just be something you'd like to see that we do not. Sorry!

**Comment by alexanderxc** [comment]
Please do not consider this message as a complaint. I believe the whole homebrew team is doing an amazing job. 

> If this is the case and it's a reproducible bug: please report it. That's not what you're describing here, though, and it sounds like worries about a hypothetical bug rather than an actual one.

I was actually referring to whatsapp cask, which was recently changed (at least in the alpha release, which will soon become mainstream for apple silicon) - this has been already addressed by a PR. 

Instead, `--greedy` is not actually the functionality I was looking for as this would forcefully installed a fresh cask - but in I'm only tying to align the installed version reference inside homebrew without changing anything in the installed packages. I do not want to forcefully reinstall each cask, I'm ok with apps autoupdate functionality. 

That said, I understand why this may not be consider as a feature in homebrew and that would not be pursued.

**Comment by MikeMcQuaid** [comment]
> Please do not consider this message as a complaint. I believe the whole homebrew team is doing an amazing job.

Thanks for the kind words ❤️ 



> Instead, `--greedy` is not actually the functionality I was looking for as this would forcefully installed a fresh cask - but in I'm only tying to align the installed version reference inside homebrew without changing anything in the installed packages. I do not want to forcefully reinstall each cask, I'm ok with apps autoupdate functionality.

The problem is casks are stored in e.g. `/opt/homebrew/Caskroom/1password/8.10.1/1Password.app/`. By the time you're altering these paths and moving them around: it doesn't seem to be much different to me to be doing what `---greedy` does.

I understand what you'd like to have work: I just don't quite see a situation where it can be easily implemented and get you what you want. If you were willing to take a stab at a PR: that might swing things but as you're not: I'm afraid it doesn't.

> That said, I understand why this may not be consider as a feature in homebrew and that would not be pursued.

Thanks for your understanding 🙇🏻

**Comment by alexanderxc** [comment]
Thanks @MikeMcQuaid !

I now have a better understanding of how `Caskroom` is implemented (did some rearming around in homebrew) and I get why this is not easy to implement given the cask folder structure. 

Perhaps, in the future, I might take a attempt a PR.

Thanks for now.
