### ISSUE TITLE
Support multiple named `sockets` in `service` block

### ISSUE THREAD

**Issue by owenthereal** [Homebrew/brew#15945]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

It would be nice to declare multiple `sockets` with names in the `service` block in a formula. For example:

```rb
service do
  sockets "Socket" => "tcp://0.0.0.0:80", "SocketTLS" => "tcp://0.0.0.0:443"
end
```

### What is the motivation for the feature?

Some formulas may expose multiple sockets in a `plist` file. For example, https://github.com/owenthereal/homebrew-candy/commit/92aada6f8ecddfc0ca6edfcc968c878c2d18a694 tries to convert the old `plist` function with both port 80 and 443 set in the `Sockets` plist section but couldn't due to `sockets` in the `service` block only allows [one entry](https://github.com/Homebrew/brew/blob/b53508897b9e761948da9585b3ca55cf9d2abeb3/Library/Homebrew/service.rb#L191-L202), although `sockets` with an `s`.

### How will the feature be relevant to at least 90% of Homebrew users?

This prevents some formula that requires exposing multiple sockets from working. I don't have a number on the number of Homebrew users impacted. But the migration from `plist` to `service` breaks some formulas. 

### What alternatives to the feature have been considered?

I do not know a way. Please share if you have any recommendations.

**Comment by MikeMcQuaid** [comment]
Makes sense to me. What do you think @SMillerDev?

**Comment by apainintheneck** [comment]
I looked at the code yesterday and the `sockets` stanza seems to only be available for `launchd` on MacOS right now. I think it's a no-brainer. I'm not sure why it was never added to the `systemd` on the Linux side though. I'm not sure why we don't allow people to name their sockets either or how useful that would be to add in.

**Comment by SMillerDev** [comment]
Yeah, seems fine to me. I never added it because no formulae I knew of needed it.

**Comment by apainintheneck** [comment]
@owenthereal It would be great if you could test out the changes on this branch (https://github.com/Homebrew/brew/pull/16026) to make sure they solve the problem. Also, I looked at your formula and you'll want to use `service do` instead of `def service` when defining a service.

**Comment by owenthereal** [comment]
@apainintheneck Sorry for not getting back to you sooner. I saw the changes were [reverted](https://github.com/Homebrew/brew/pull/16054). I'm happy to help test it when it's ready again. But I don't know how to test code changes in a branch, though. Is there a doc that I could take a look?

**Comment by apainintheneck** [comment]
@owenthereal No worries. I just like to double-check with people who open issues to see if it fits their use case. I'll fix and reopen the original PR in the next few days and ping you so that you can take a look at it when that's ready.

I don't think we have documentation for that but that sounds useful since this comes up from time to time. Brew is just a git repo of Ruby code so it's not terribly complex to check out a feature branch locally for testing. I'll provide instructions for testing it in the PR.
