### ISSUE TITLE
zlib header & dylib version mismatch on El Cap + Xcode 8.1 (crashes pigz)

### ISSUE THREAD

**Issue by int3h** [Homebrew/brew#1596]
On Mac OS X 10.11.6 and Xcode 8.1, the version of `zlib.h` used during compilation doesn't match the version of `libz.1.dylib` loaded at runtime. Specifically, the header file used during compilation is for zlib v1.2.8, but the dylib file loaded at runtime is for zlib v1.2.5. This is using the system default zlib shipped as part of the OS. 

The big can cause crashes in any Homebrew formula using zlib. As a specific example, `pigz` (from the Homebrew core Tap) will crash at runtime because it tries to call a function that doesn't exist in zlib v1.2.5 (the version provided by the built-in `libz.1.dylib` library). Normally, `pigz` has a `#if ZLIB_VERNUM >= 1.2.6...` guard around this code during compilation, but since the header defines `ZLIB_VERNUM` as 1.2.8, that code is happily compiled.

The reason for this mismatch is that the header is coming from the OS SDK, while the dylib is coming from the OS itself. Xcode 8 compiles code against the macOS 10.12 SDK (even on OS X 10.11) and 10.12 has a different version of zlib than 10.11.

I can fix the `pigz` formula by adding `-I/usr/include` to the `CFLAGS=...` argument passed to `make` during install, e.g.:

<details><summary>diff pigz.rb (click to expand)</summary>

```diff
--- a/Formula/pigz.rb
+++ b/Formula/pigz.rb
@@ -12,7 +12,7 @@ class Pigz < Formula
   end

   def install
-    system "make", "CC=#{ENV.cc}", "CFLAGS=#{ENV.cflags}"
+    system "make", "CC=#{ENV.cc}", "CFLAGS=-I/usr/include #{ENV.cflags}"
     bin.install "pigz", "unpigz"
     man1.install "pigz.1"
     man1.install_symlink "pigz.1" => "unpigz.1"
```

</details><br/>

However, I'm not sure if this is the 'right' way of doing this in Homebrew. It also would have to be repeated for every formula that uses zlib (probably including code to guard that flag with 'if OS X 10.11 && Xcode 8...').

For reference, here's my config:

<details><summary>brew --config (click to expand)</summary>

```
HOMEBREW_VERSION: 1.1.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0f529dae1043639058130092cf35e68d18907cb8
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 085552d27ba3d86763b5a28f433440756027d82a
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.3/bin/ruby
Java: 1.8.0_77
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 7.3.1.0.1.1461711523
X11: N/A
```
</details>

**Comment by lenn4rd** [comment]
I'm seeing the same issue. However, I don't have Xcode installed. Compiling pigz from source after patching the formula mitigates the problem.

My Homebrew config, if needed:

<details>
  <summary>brew --config</summary>
  <pre>
HOMEBREW_VERSION: 1.1.2-3-g8f82e89d0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8f82e89d0b26108e32a10b5d95b67e5e21ff0df6
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ac8363c6f434f5819270f8771e52b09c8c8efee2
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/ltimm/.rbenv/shims/ruby => /Users/ltimm/.rbenv/versions/2.3.1/bin/ruby
Java: 1.8.0_74, 1.8.0_66
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A
  </pre>
</details>

**Comment by ilovezfs** [comment]
>I can fix the pigz formula by adding -I/usr/include to the CFLAGS=... argument passed to make during install

That will not work for Homebrew because we do not require the command line tools (the user should be able to build any formula with Xcode.app only), but the /usr/include headers come from the command line tools pkg. On a machine without the command line tools,
```
Josephs-Mac:~ joe$ ls /usr/include
ls: /usr/include: No such file or directory
```
So one approach is to check the library version in /usr/lib/libz.dylib instead.
```
$ grep -i version /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libz.1.tbd
current-version: 1.2.8
                       _uncompress, _zError, _zlibCompileFlags, _zlibVersion ]
```

```
$ cat zlib-version.c 
#include <zlib.h>
#include <stdio.h>


//ZEXTERN const char * ZEXPORT zlibVersion OF((void));

int main()
{
        printf("zlib version is %s\n", (char *)zlibVersion());
}
```

```
clang zlib-version.c -o zv -lz
```

```
$ ./zv
zlib version is 1.2.5
```
