### ISSUE TITLE
gedit comes with python plugin support disabled

### ISSUE THREAD

**Issue by esgott** [Homebrew/brew#1597]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

When you try to load a plugin written in python, it will fail, and gedit will write the following to the console:

`(gedit:38797): libpeas-WARNING **: The 'python' plugin loader has not been enabled`

**Comment by MikeMcQuaid** [comment]
> When you try to load a plugin written in python, it will fail, and gedit will write the following to the console:
> 
> (gedit:38797): libpeas-WARNING **: The 'python' plugin loader has not been enabled

Yes, this is correct and expected behaviour.

**Comment by esgott** [comment]
Can you explain why?

**Comment by MikeMcQuaid** [comment]
Generally we disable Python by default because Python bindings are tightly bound to the version of Python used at install-time and this is not desirable. If this is just using Python rather than providing bindings and it works then we'd welcome a PR to change this.

**Comment by esgott** [comment]
I don't have a deep understanding, but I think that the current version of gedit accepts plugins written in python3. It seemed logical to me, that it should have a dependency to python3, and then the binding could call out. What do you mean by tightly bound version to python? I can may help with a PR, if what I am suggesting makes sense :)

**Comment by MikeMcQuaid** [comment]
Yep, a PR sounds good. Using Python 3 is fine but Python 2 is tricker 👍 Feel free to make a PR and we can discuss it further then.
