### ISSUE TITLE
Check for valid url, sha256 and version when loading casks

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/brew#15976]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When we load a cask from a file or the API, we don't check if it has basic attributes necessary to install it on a system. This means that we can see some obscure error messages when those attributes are not defined. On the formula side, we check for those things every time we load anything for the first time. We should do the same thing for casks.

### What is the motivation for the feature?

It would improve consistency and give users and package maintainers more helpful error messages.

### How will the feature be relevant to at least 90% of Homebrew users?

Getting better error messages and not trying to load cask files that have errors will improve the experience for all users indirectly by helping us troubleshoot problems faster.

### What alternatives to the feature have been considered?

Adding more checks around the codebase or leaving things as is.

**Comment by apainintheneck** [comment]
Changing this requirement would probably break `brew search` and `brew info` if we just enabled it everywhere since you're able to see results for packages that can't be installed on your system. I'm not sure how that is handled on the formula side to be honest.

**Comment by apainintheneck** [comment]
We also try to use the original cask file when removing casks and that might cause problems so we might want to be able to turn off these checks at times.

**Comment by MikeMcQuaid** [comment]
This seems like a good idea 👍🏻
