### ISSUE TITLE
4.1.10 pkg installer (macOS) installs version 3.6.10

### ISSUE THREAD

**Issue by rmichelena** [Homebrew/brew#15984]
### `brew doctor` output

```shell
not needed
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
not needed
```

### What were you trying to do (and why)?

I used the pkg installer to install latest 4.1.10 version

### What happened (include all command output)?

it installed 3.6.10
brew --version gives "Homebrew 3.6.10-2-g72f7880"

I resorted to installing via command line, and it correctly installed 4.1.10

this is on Apple Silicon

### What did you expect to happen?

to install 4.1.10

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
as explained
```

**Comment by MikeMcQuaid** [comment]
> ```shell
> not needed
> ```

This is needed, thanks, we'd like to know these details about your system as it makes it easier for us to reproduce and fix these issues.

**Comment by rmichelena** [comment]
Mike, what happens is I can't turn back time... when the 4.1.10 pkg installer installed 3.6.10 (which I found out via brew --version), I resorted to install via command line, which turned out fine. Then I had not done brew --config or brew --doctor while I was at 3.6.10 ; but I think such a gaffe (the 4.1.10 pkg installer, installing 3.6.10) is hardly attributable to some obscure configuration difference on one system vs another - I mean, it does have to have the 3.6.10 binaries inside, which it shouldn't! - only relevant information, I believe, is that this is on Apple Silicon... (because that's afaik the only decision the installer makes)... unless, maybe, it's actually installing 4.1.10 but somewhat labeling it as 3.6.10, which also can't see how it could be related to any OS or hardware configuration...

**Comment by MikeMcQuaid** [comment]
@rmichelena Can I see your `brew config` and `brew doctor` output now that things are working?

> only relevant information, I believe, is that this is on Apple Silicon
> which also can't see how it could be related to any OS or hardware configuration...

Please let us decide that. This back and forth is not a good use of anyone's time. We don't tell you we need this information for no reason.

It will make life easier testing and reproducing this.

**Comment by rmichelena** [comment]
**brew doctor output:**
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
  php@7.3

Warning: You have an unnecessary local Core tap!
This can cause problems installing up-to-date formulae.
Please remove it by running:
 brew untap homebrew/core

**brew config output:**
HOMEBREW_VERSION: 4.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 12c8778af976269344f3c0b914243e178fc4ffbd
Last commit: 4 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6fb84e211409321f5a73e182dca78cdf69bf5f4e
Core tap last commit: 2 days ago
Core tap branch: master
Core tap JSON: 09 Sep 01:56 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false

**Comment by MikeMcQuaid** [comment]
@rmichelena Thanks. I'll take more of a look later this week.

**Comment by rmichelena** [comment]
Solved in 4.1.11, just tried in a brand new machine, everything ok
