### ISSUE TITLE
The script in homepage won't work with Fish shell

### ISSUE THREAD

**Issue by mohsen1** [Homebrew/brew#1598]
I have Fish shell and when I paste the script in home screen, it's not working:

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

That script should be independent from the type of shell

**Comment by vitorgalvao** [comment]
What do you mean by “it’s not working”?

Do you get an error? A blank screen and nothing happens? What exactly? From your report, it is not clear that fish is the culprit. There’s also no way to identify and fix the issue without further details.

**Comment by mohsen1** [comment]
```
 /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"                                                                                                                  3687ms  Wed Nov 30 13:41:53 2016
$(...) is not supported. In fish, please use '(curl)'.
fish: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
                        ^
```

**Comment by MikeMcQuaid** [comment]
You need to use Bash or ZSH rather than Fish for the one-line install.

**Comment by vitorgalvao** [comment]
From the error, it’s clear the problem is not with the script, but with the line to call it. It also tells you how to fix it: remove the `$`.

**Comment by mohsen1** [comment]
Can you make it a simple bash script that user can `curl` and pipe it to `sh` instead of this? 

```sh
$ curl https://brew.sh/install | sh
```

That is not using any Bash or Fish feature.

**Comment by vitorgalvao** [comment]
> Can you make it a simple bash script that user can `curl` and pipe it to `sh`

1. [Don’t pipe to your shell](https://www.seancassidy.me/dont-pipe-to-your-shell.html).
2. The install script is over 300 lines of ruby. It would be insane to convert that to bash (and no way would it be simple) for this reason.
3. Fish is a great shell, but they made the decision to not be compatible with other shells. It’s a tradeoff, and fish users constantly have to adapt, for better or worse.
4. As stated, this is an easy fix/change on your part. You don’t even need to run that exact command, just download the file and execute it.

There’s no point to changing the current installation instructions. They work well and are made to be effective to the vast majority of people.

**Comment by reitermarkus** [comment]
> - Don’t pipe to your shell.

Thanks, @vitorgalvao, didn't know about that. Although for bash scripts you could wrap everything inside `{ }` to make sure everything is loaded before executing it.

**Comment by MikeMcQuaid** [comment]
> Fish is a great shell, but they made the decision to not be compatible with other shells. It’s a tradeoff, and fish users constantly have to adapt, for better or worse.

This is the main reason right here. If you use Fish, you should be able to figure this out yourself. If you can't: you should consider using another shell.

**Comment by mohsen1** [comment]
FWIW I know exactly why this was not working. As a Fish user it's not pleasant to see everywhere everyone assumes users have Bash by default.

**Comment by MikeMcQuaid** [comment]
@mohsen1 We don't. I use ZSH on all my machines and this line works on ZSH perfectly.

**Comment by reitermarkus** [comment]
> As a Fish user it's not pleasant to see everywhere everyone assumes users have Bash by default.

I'm a `fish` user myself, but I understand that the defacto default shell is `bash`, or at least something compatible with it, so unless you are using Fish.app as, you are likely going to install Homebrew with `bash` *before* installing `fish` via Homebrew.
