### ISSUE TITLE
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!

### ISSUE THREAD

**Issue by tekumara** [Homebrew/brew#15998]
### `brew doctor` output

```shell
❯ brew doctor
Your system is ready to brew
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4afb8e5602f3ecc9edf67a44257d8eceeaa8a108
Last commit: 35 hours ago
Core tap JSON: 13 Sep 01:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

❯ brew update
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!

### What happened (include all command output)?

❯ brew update
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!

### What did you expect to happen?

No error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
❯ brew update
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!
```

**Comment by tekumara** [comment]
Tried `brew update` about 5 more times and it eventually worked.

**Comment by etr2460** [comment]
I'm seeing this again today and https://formulae.brew.sh/api/formula.jws.json seems to 404 when loading in the browser. Perhaps there's an intermittent issue with this api?

**Comment by etr2460** [comment]
Sorry to tag you directly here @MikeMcQuaid, but looking at https://github.com/Homebrew/formulae.brew.sh/deployments it seems like you've been doing most of the deployments for this page/api. Is there a known issue where these api files don't exist sometimes? Perhaps during deploys?

**Comment by Bo98** [comment]
It's automated deploys - not manual.

GitHub Pages [occasionally does this](https://github.com/actions/deploy-pages/issues/86) with deploys, yes. It's not an issue on our side as the file is definitely there on upload, and the issue always corrects itself after the next automated deploy (every 15 minutes), but it is useful data to know when you notice it happening and how much impact it is having.

**Comment by etr2460** [comment]
Thank you @Bo98 and @MikeMcQuaid for the prompt responses! I don't have numbers currently on how often this happens, but we have a `brew update` before some of our install/setup scripts and this was preventing them from running. It sounds like migrating away from github pages is the fix, so hopefully that won't be too difficult and it'll resolve this once and for all.

**Comment by apainintheneck** [comment]
Would it make sense to pin this issue?

**Comment by MikeMcQuaid** [comment]
@apainintheneck done!

**Comment by minimondo** [comment]
Hi, I'm a bit uncertain from the above what my options are. I went to bed with Brew working fine on macOS Sonoma. When I woke up it was broken:

% brew doctor
Your system is ready to brew.
% brew update
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!

Is there anything I can do to get Brew working again? Thanks.

**Comment by Bo98** [comment]
Works fine for me so don't think it's the 404 seen here, but perhaps wait a 20 minutes or so and try again.

**Comment by minimondo** [comment]
Oh yes. I loaded the JSOn file manually in my browser OK, then saw your reply. Then I tried Brew and it's working now. Cheers!

**Comment by StormPooper** [comment]
Was getting this for https://formulae.brew.sh/api/cask.jws.json but it resolved itself by the time I started writing this. I got a 404 in the browser too.

**Comment by MikeMcQuaid** [comment]
GitHub have said this should be fixed on their end now 🤞🏻 .
