### ISSUE TITLE
Openblas failed to pour the bottle on macOS

### ISSUE THREAD

**Issue by alazarolop** [Homebrew/brew#15990]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I have already installed the formula `openblas` and I wanted to upgrade it. I have seen a similar issue in another formula https://github.com/Homebrew/brew/pull/15805

### What happened (include all command output)?

```
==> Upgrading openblas
  0.3.23 -> 0.3.24

Error: Parameter 'old': Expected type Pathname, got type String with value "@@HOMEBREW_PREFIX@@/opt/gc.../gcc/x86_64-apple-darwin22/13"
Caller: /usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:41
Definition: /usr/local/Homebrew/Library/Homebrew/os/mac/keg.rb:40
```

### What did you expect to happen?

Pouring of the bottle properly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade openblas
```

**Comment by Bo98** [comment]
Looks like `change_rpath` has the wrong type signature (`old` and `new` are always `String` and never `Pathname`)

**Comment by alazarolop** [comment]
Thank you for the quick reply! Is this something I should fix in my installation or it depends on the formula?

**Comment by MikeMcQuaid** [comment]
@alazarolop Can I see your `brew config` output? Working on a fix, thanks.

**Comment by alazarolop** [comment]
Thank you a lot @MikeMcQuaid .

**Comment by MikeMcQuaid** [comment]
You're welcome @alazarolop!

**Comment by scpeters** [comment]
> Looks like `change_rpath` has the wrong type signature (`old` and `new` are always `String` and never `Pathname` and `ruby-macho` expects Strings)

apologies, I added that in #15980 but didn't know what I was doing. It was needed for intermediate form of the pull request, but I think the type declarations aren't needed now. Should I remove the other type signatures that I added to `os/mac/keg`?

**Comment by MikeMcQuaid** [comment]
@scpeters No worries, it happens! I think fine to leave other signatures in unless you know them to be wrong but, lesson learned for me I guess on being wary of these sorts of changes that aren't covered by test.
