### ISSUE TITLE
brew install fails with 'error: only one config file at a time.' until GIT_CONFIG is unset

### ISSUE THREAD

**Issue by rpdelaney** [Homebrew/brew#160]
When running a brew install job, I observed the following output:

```
$ brew install xz
error: only one config file at a time.
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte
    --includes            respect include directives on lookup

Error: Failure while executing: git config --local --replace-all homebrew.private true
```

The error persisted until I ran ```unset GIT_CONFIG```. Unfortunately, that is an undesirable work-around since it unloads the git config from the session.

**Comment by zmwangx** [comment]
One easy fix is to unset `GIT_CONFIG` in `brew.sh`.

**Comment by mikemcquaid** [comment]
CC @xu-cheng for thoughts on this.

**Comment by mikemcquaid** [comment]
(I think I'd like to see more than one user report this before we unset the variable).

**Comment by xu-cheng** [comment]
If we change `--local` to `--file=path/to/config`, will it help to solve this.

**Comment by mikemcquaid** [comment]
@xu-cheng 👍

**Comment by zmwangx** [comment]
> If we change --local to --file=path/to/config, will it help to solve this.

A user-supplied GIT_DIR floating around (most likely not pointing at Homebrew) could potentially have side effects when you run other git commands that might not outright fail. There's no reason to keep this variable during Homebrew's execution.

Try this and you'll see the point:

    GIT_DIR=~/.git brew update

> (I think I'd like to see more than one user report this before we unset the variable).

I think users don't typically export `GIT_DIR`. But there's a legit use once in a while, e.g., when you're running a bunch of git commands for a repo from outside in a single session, but don't want to use `-C` or `--git-dir` every time. The chance of having such a use case and using brew in the same session should be very rare.

**Comment by UniqMartin** [comment]
> If we change `--local` to `--file=path/to/config`, will it help to solve this.

This seems like a reasonable fix, but it makes all `git config` invocations much more ugly. Setting `GIT_CONFIG` globally doesn't sound like something users should do, or if they really have to, that should be limited to a separate session where they don't interact with Homebrew or other tools built on top of Git, as this will easily mess up things. I wonder how other such tools deal with that, if they do at all.

> I think users don't typically export `GIT_DIR`.

I agree with everything that you said and the consequences would probably be very undesirable, but this issue is about `GIT_CONFIG` and not about `GIT_DIR`.

**Comment by zmwangx** [comment]
> I agree with everything that you said and the consequences would probably be very undesirable, but this issue is about GIT_CONFIG and not about GIT_DIR.

Weird, I don't know how and at which point I convinced myself that this issue is about `GIT_DIR`... But looks like at least `GIT_DIR` should be unset.

**Comment by mikemcquaid** [comment]
Closing this out but we'll watch for more people with the same issue. I recommend unsetting this variable @rpdelaney as it'll break pretty much any script relying on `git config`.

**Comment by Fatallis** [comment]
I am having a similar problem. I dont undestand how to solve it.
`[alejandri@omica ~]$ brew update
error: unknown option `list'
usage: git tag [-a|-s|-u <key-id>] [-f] [-m <msg>|-F <file>] <tagname> [<head>]
   or: git tag -d <tagname>...
   or: git tag -l [-n[<num>]] [<pattern>]
   or: git tag -v <tagname>...

    -l                    list tag names
    -n[<n>]               print <n> lines of each tag message
    -d                    delete tags
    -v                    verify tags

Tag creation options
    -a                    annotated tag, needs a message
    -m <msg>              message for the tag
    -F <FILE>             message in a file
    -s                    annotated and GPG-signed tag
    -u <key-id>           use another key to sign the tag
    -f, --force           replace the tag if exists

Tag listing options
    --contains <commit>   print only tags that contain the commit

error: unknown option `list'
usage: git tag [-a|-s|-u <key-id>] [-f] [-m <msg>|-F <file>] <tagname> [<head>]
   or: git tag -d <tagname>...
   or: git tag -l [-n[<num>]] [<pattern>]
   or: git tag -v <tagname>...

    -l                    list tag names
    -n[<n>]               print <n> lines of each tag message
    -d                    delete tags
    -v                    verify tags

Tag creation options
    -a                    annotated tag, needs a message
    -m <msg>              message for the tag
    -F <FILE>             message in a file
    -s                    annotated and GPG-signed tag
    -u <key-id>           use another key to sign the tag
    -f, --force           replace the tag if exists

Tag listing options
    --contains <commit>   print only tags that contain the commit

==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  http://docs.brew.sh/Analytics.html

error: unknown option `local'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    -f, --file <FILE>     use given config file

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 adds a new variable: name value
    --unset               removes a variable: name [value-regex]
    --unset-all           removes all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            opens an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte

Error: Failure while executing: git config --local --replace-all homebrew.analyticsmessage true
`

**Comment by MikeMcQuaid** [comment]
@Fatallis Upgrade your `git`.

**Comment by Fatallis** [comment]
Thank you @MikeMcQuaid.
