### ISSUE TITLE
Critical bug! brew kills all process if it's interrupted?

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/brew#1600]
### version
```
%> brew --version
Homebrew 1.1.2
Homebrew/homebrew-core (git revision 5af1b; last commit 2016-11-30)
```

### problem

When I install a package, and If I press ^C, all processes are killed, chrome, iterm2, dock etc.
What's happening? It happens everytime!

**Comment by CaledoniaProject** [comment]
Anyone can help?

I did a simple verification with this,

```
#!/bin/bash

exec &> /tmp/log
set -x
brew install bison27
```

Launch it and press ^C, all processes killed, wtf?

![screen 2016-12-01 at 15 31 16](https://cloud.githubusercontent.com/assets/1357701/20785470/3edc9c7c-b7db-11e6-8e0c-7d3a7d9221f4.jpg)

**Comment by CaledoniaProject** [comment]
Crap,  this is buggy, comment it out and problem resolved

```
  # kill all of subprocess on interrupt
  trap '{ pkill -P $$; wait; exit 130; }' SIGINT
```

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by CaledoniaProject** [comment]
Oh sure,

```
%> brew update
Updated 1 tap (caskroom/cask).
No changes to formulae.

%> brew update
Already up-to-date.

%> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Cellar and TEMP directories are on different volumes.
macOS won't move relative symlinks across volumes unless the target file already
exists. Brews known to be affected by this are Git and Narwhal.

You should set the "HOMEBREW_TEMP" environmental variable to a suitable
directory on the same volume as your Cellar.

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libass-ct

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
```

**Comment by MikeMcQuaid** [comment]
What does `which pkill` output?

**Comment by CaledoniaProject** [comment]
/usr/local/homebrew/bin/pkill

**Comment by MikeMcQuaid** [comment]
That's your problem (which, to be fair, `brew doctor` warns you about). Remove that from your `PATH` for now to avoid this issue and we'll look at a better fix.

**Comment by bfontaine** [comment]
@MikeMcQuaid Couldn’t we avoid this issue by using e.g. `/usr/bin/pkill` instead of `pkill`? I’m on Linux right now, I can’t check the path for macOS.

**Comment by MikeMcQuaid** [comment]
@bfontaine Yes, that'll be the fix.

**Comment by CaledoniaProject** [comment]
Oh thanks!

**Comment by vitorgalvao** [comment]
> I’m on Linux right now, I can’t check the path for macOS.

Just confirmed. Same path.
