### ISSUE TITLE
`brew doctor` shows "pre-release" disclaimer on stable public release of macOS 14

### ISSUE THREAD

**Issue by KyLeggiero** [Homebrew/brew#16006]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 14.
We do not provide support for this pre-release version.
It is expected behaviour that some formulae will fail to build in this pre-release version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

### Verification

- [ ] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4afb8e5602f3ecc9edf67a44257d8eceeaa8a108
Last commit: 3 days ago
Core tap JSON: 14 Sep 18:56 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0 => /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
```

### What were you trying to do (and why)?

run `brew doctor` (to check my system for potential problems)

### What happened (include all command output)?

`brew doctor` says that Homebrew does "not provide support for this pre-release version", despite me being on a public/stable OS version

### What did you expect to happen?

`brew doctor` prints "Your system is ready to brew."

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Install the latest stable version of macOS (14; Sonoma)
2. run `brew doctor`
```

**Comment by Moulick** [comment]
14.0 (23A339) is still only a release candidate, so I suppose it's still considered `pre-release`

**Comment by Bo98** [comment]
There is no public stable version of macOS 14. It's released on 26th September.

We'll update the pre-release status ahead of then however, likely when a sufficient number of bottles have been built for Sonoma over the next week or so. We started bottle builds yesterday after the first release candidate was released.

**Comment by Bo98** [comment]
Also worth remembering: the last five macOS releases had two release candidates, so the first one isn't necessarily what ends up being the public release. Though it's good enough in our case for bottle building and CI.

**Comment by KyLeggiero** [comment]
Oh cool so the software updater lied to me. Thanks for letting me know; I wish Apple did
