### ISSUE TITLE
Brew can not find installed dependencies if they are installed in nonstandard way

### ISSUE THREAD

**Issue by ZaJarv** [Homebrew/brew#1601]
From title.

Example - package called "ios-sim", in "Dependencies" section, you can see it requires "node".
But Node is already installed, but via nvm (and it added in $PATH), another installation can break already installed version, node itself, npm, etc.

Same for Ruby, it can be installed via brew, and also it can be installed via rbenv, rvm, etc.

So, may be it worth to add option for package installation to ignore dependencies (with BIG warning for users who is going to do so), or add detection of installed packages (what is present in $PATH variable)?

**Comment by MikeMcQuaid** [comment]
> another installation can break already installed version, node itself, npm, etc.

The install itself will not break anything. Homebrew will not overwrite files or override your PATH.

This is being considered for Node in https://github.com/Homebrew/brew/pull/1408 but not in general so passing on this for now.
