### ISSUE TITLE
Suggestions for generating a GUI program for Putty

### ISSUE THREAD

**Issue by dZ8Lx9OwX** [Homebrew/brew#16022]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When compiling putty with Homebrew in MacOS, it was found that after introducing gtk3, it was possible to compile and generate puttyapp programs that were used normally,GUI-based programs. And it doesn't depend on X11, and there is no need to install an additional X window to support its operation.
The latest Homebrew update putty 0.79 does not have a puttyapp program or other GUI program, and it seems that it has not been there. Putty's dependencies include cmake, halibut, pkg-config, and you only need to add gtk3 in Homebrew to achieve puttyapp generation. And there is no need to install X11 to run alone.

### What is the motivation for the feature?

It is convenient to install putty's program through Homebrew, giving users a better experience and choice.

### How will the feature be relevant to at least 90% of Homebrew users?

As long as all users of putty should or will use this change, and putty has always provided, putty under Homebrew will be more perfect.

### What alternatives to the feature have been considered?

GUI support for installing putty via MacPorts is too bloated and dependent on X11; Via GTK-OSX is too complicated and not very convenient. Using gtk3 to compile puttyapp under Homebrew is very convenient and fast. The best I've tried so far.

**Comment by MikeMcQuaid** [comment]
Not sure what's being asked for here, sorry. This feels better placed as either a discussion or a new cask for a Putty precompiled GUI (not a formula).

**Comment by dZ8Lx9OwX** [comment]
Thanks a lot for the reminder. I'm giving feedback on Homebrew for the first time, and it's not clear what the specific classification requirements are. I think maybe I didn't find the right place and clearly described. The handling of the issue is greatly appreciated.

**Comment by dZ8Lx9OwX** [comment]
> Not sure what's being asked for here, sorry. This feels better placed as either a discussion or a new cask for a Putty precompiled GUI (not a formula).

Thanks a lot for the reminder. I'm giving feedback on Homebrew for the first time, and it's not clear what the specific classification requirements are. I think maybe I didn't find the right place and clearly described. The handling of the issue is greatly appreciated.

**Comment by MikeMcQuaid** [comment]
@dZ8Lx9OwX all good, no problem. I did a bit more research and there's no official upstream binaries for Putty for making a cask and we don't like GUIs in formulae so that's why it is how it is.

Could you try and open a pull request to add GTK as a dependency and `brew edit putty` to try to get it working with a GUI? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by dZ8Lx9OwX** [comment]
> @dZ8Lx9OwX all good, no problem. I did a bit more research and there's no official upstream binaries for Putty for making a cask and we don't like GUIs in formulae so that's why it is how it is.
> 
> Could you try and open a pull request to add GTK as a dependency and to try to get it working with a GUI? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.`brew edit putty`
> 
> Thanks!

@MikeMcQuaid This is a very good proposal. I have tried to understand how to make a cask, which is somewhat difficult for me. I didn't find information about the committer of the original PuTTY cask. I want to tell him that, and I thought he would be a better candidate.

I made a version of PuTTY Chinese and generated GUI programs using Homebrew on MacOS, which is very convenient. It was later discovered that there was a PuTTY GUI program in MacPorts, but not in Homebrew. So I want to share this possibility. With MacPorts, I didn't succeed in generating PuTTY, Homebrew is much more convenient and fast. Expect Homebrew to get better and better.
