### ISSUE TITLE
Intermittent Linting Failures for Core Formulae on CI

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/brew#16037]
### `brew doctor` output

```shell
n/a
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
n/a
```

### What were you trying to do (and why)?

Run the `formula audit` step to pass CI.

### What happened (include all command output)?

It failed on the linting step.

![Screen Shot 2023-09-25 at 11 00 05 PM](https://github.com/Homebrew/brew/assets/42982186/43592887-d711-472d-be2a-bdb0d09d785e)

- [CI Run](https://github.com/Homebrew/brew/actions/runs/6303801685/job/17113856522?pr=16034)

It seems like it's trying and failing to load a newly added formulae.

```console
$ brew update
==> Updated Homebrew from 4.1.12 (afbea15d5) to 4.1.13 (f1d345a60).
Updated 6 taps (homebrew/cask-versions, homebrew/bundle, homebrew/cask-fonts, homebrew/services, homebrew/core and homebrew/cask).
==> New Formulae
numbat                                  qalculate-qt                            sqlsmith
==> New Casks
muyu                                                         tsh13

The 4.1.13 changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/4.1.13
```

### What did you expect to happen?

Any CI failures should be reproducible across multiple CI runs as well as locally.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Run the `Formula Audit` step on CI.
2. Fail on the `brew audit --skip-style --except=version --tap=homebrew/core` step. (only fails occasionally)
```

**Comment by apainintheneck** [comment]
These always seem to fail with a similar error message indicating it can't find the formula with the name x.

```
Error: No available formula with the name "sqlsmith". Did you mean sqlite?
```

We only seem to load formulas by name in one spot in the audit command code. We could just switch to loading them directly from files which might solve the problem.

```diff
diff --git a/Library/Homebrew/dev-cmd/audit.rb b/Library/Homebrew/dev-cmd/audit.rb
index 2bfe5419a..7302b62de 100644
--- a/Library/Homebrew/dev-cmd/audit.rb
+++ b/Library/Homebrew/dev-cmd/audit.rb
@@ -122,7 +122,7 @@ module Homebrew
       if args.tap
         Tap.fetch(args.tap).then do |tap|
           [
-            tap.formula_names.map { |name| Formula[name] },
+            tap.formula_files.map { |path| Formulary.factory(path) },
             tap.cask_files.map { |path| Cask::CaskLoader.load(path) },
           ]
         end
```

`brew readall` never seems to fail on CI like this but it always loads formulas from files not by name.

**Comment by MikeMcQuaid** [comment]
> We could just switch to loading them directly from files which might solve the problem.

This seems like a good idea 👍🏻

**Comment by Bo98** [comment]
This looks to me to actually be a race condition bug in brew where the git source is updated but the formula does not yet exist in the API. Removing an entry from your local JSON might force the issue into happening.

The code you reference is wrapped in `Homebrew.with_no_api_env` so it shouldn't be that unless there's a missing check somewhere. (But I do however agree that loading by paths makes sense anyway.)

**Comment by apainintheneck** [comment]
> This looks to me to actually be a race condition bug in brew where the git source is updated but the formula does not yet exist in the API. Removing an entry from your local JSON might force the issue into happening.
> 
> The code you reference is wrapped in `Homebrew.with_no_api_env` so it shouldn't be that unless there's a missing check somewhere. (But I do however agree that loading by paths makes sense anyway.)

Yeah, I agree. This is more treating the symptom instead of the problem but I couldn't figure out what could be causing this since we do wrap all of the `Formulary` calls inside `brew audit` as far as I can tell to avoid using the API.

**Comment by apainintheneck** [comment]
Should we keep this open for a few days to see if the problem reoccurs on CI or are we fine closing this now after #16039? I agree with @Bo98 that there seems to be some other race condition happening here but I haven't been able to reproduce it outside of CI.

**Comment by MikeMcQuaid** [comment]
I'm fine with closing and reopening if it crops up again. Thanks @apainintheneck!
