### ISSUE TITLE
Add a skip checksum feature for already downloaded packages as it waste too much time for verifying checksum repeatly

### ISSUE THREAD

**Issue by acane77** [Homebrew/brew#16033]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Add a skip checksum feature for already downloaded packages as it waste too much time for verifying checksum repeatly, especially you should re-run the commands servals times to resolve dependency issues manually, such as installing svn.

### What is the motivation for the feature?

Save time, do not waste time on meaningless checksum calcutions as it has checked already as it's downloaded already.

### How will the feature be relevant to at least 90% of Homebrew users?

This features will save so much time for 100% users when they known what he is doing.

### What alternatives to the feature have been considered?

I replaced the system checksum command, to directly get checksum result from filename, IMO it's just a workaround for my case.

**Comment by MikeMcQuaid** [comment]
We won't consider this as it's a security feature. We'll review approaches to make it faster.
