### ISSUE TITLE
`brew install gcc` fails on macOS Monterey with a local brew

### ISSUE THREAD

**Issue by tangqi** [Homebrew/brew#16067]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.

Many of Homebrew's bottles (binary packages) can only be used with the default prefix.
Consider uninstalling Homebrew and reinstalling into the default prefix.
It is expected behaviour that some formulae will fail to build in this unsupported configuration.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: a8519f78fb63f2f2266950bdd8141037da69f8bd
Last commit: 6 days ago
Core tap JSON: 01 Oct 06:40 UTC
HOMEBREW_PREFIX: /Users/qtang/.brew
HOMEBREW_REPOSITORY: /Users/qtang/.brew
HOMEBREW_CELLAR: /Users/qtang/.brew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.bR2umSLhOK/org.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.6.9-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

### What were you trying to do (and why)?

I was trying to `brew install gcc` on a local brew at `$HOME/.brew` but it gave some errors. This is perhaps related to the brew is not in the default location. But this local brew used to work fine until recently I upgraded the system to Monterey. I tried to reinstall brew and then install gcc 11, 12 and 13, all leading to some errors. Installing brew to `/usr/local` is not an option. 

Any newer version of the gcc would be sufficient for me. Any workaround will be greatly appreciated. 

### What happened (include all command output)?

With `gcc@11`
```
==> ../configure --prefix=/Users/qtang/.brew/opt/gcc@11 --libdir=/Users/qtang/.brew/opt/gcc@11/lib/gcc/11 --disable-nls --enable-checking=release --with-gcc-major-version-only --enable-languages=c,c++,objc,ob
==> make
Last 15 lines from /Users/qtang/Library/Logs/Homebrew/gcc@11/02.make:
mkdir objc
mkdir objc/.deps
mkdir objcp
mkdir objcp/.deps
mkdir c-family
mkdir c-family/.deps
mkdir common
mkdir common/.deps
mkdir analyzer
mkdir analyzer/.deps
mkdir rtl-ssa
mkdir rtl-ssa/.deps
config.status: executing default commands
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2
```

with `gcc@12`
```
==> ../configure --prefix=/Users/qtang/.brew/opt/gcc@12 --libdir=/Users/qtang/.brew/opt/gcc@12/lib/gcc/12 --disable-nls --ena
==> make
Last 15 lines from /Users/qtang/Library/Logs/Homebrew/gcc@12/02.make:
make[3]: /private/tmp/gccA12-20231001-31122-1lrxn8k/gcc-12.3.0/build/./gcc/xgcc: Permission denied
# multilibs.
/private/tmp/gccA12-20231001-31122-1lrxn8k/gcc-12.3.0/build/./gcc/xgcc -B/private/tmp/gccA12-20231001-31122-1lrxn8k/gcc-12.3.0/build/./gcc/ -B/Users/qtang/.brew/opt/gcc@12/x86_64-apple-darwin21/bin/ -B/Users/qtang/.brew/opt/gcc@12/x86_64-apple-darwin21/lib/ -isystem /Users/qtang/.brew/opt/gcc@12/x86_64-apple-darwin21/include -isystem /Users/qtang/.brew/opt/gcc@12/x86_64-apple-darwin21/sys-include   -fno-checking -g -O2 -O2  -g -O2 -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -mmacosx-version-min=10.8 -fno-common -mmacosx-version-min=10.8 -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -mmacosx-version-min=10.8 -fno-common -mmacosx-version-min=10.8 -I. -I. -I../.././gcc -I../../../libgcc -I../../../libgcc/. -I../../../libgcc/../gcc -I../../../libgcc/../include  -DHAVE_CC_TLS -DUSE_EMUTLS  -o avx_resms64_s.o -MT avx_resms64_s.o -MD -MP -MF avx_resms64_s.dep -DSHARED -c -xassembler-with-cpp ../../../libgcc/config/i386/avx_resms64.S
make[3]: /private/tmp/gccA12-20231001-31122-1lrxn8k/gcc-12.3.0/build/./gcc/xgcc: Permission denied
/private/tmp/gccA12-20231001-31122-1lrxn8k/gcc-12.3.0/build/./gcc/xgcc -B/private/tmp/gccA12-20231001-31122-1lrxn8k/gcc-12.3.0/build/./gcc/ -B/Users/qtang/.brew/opt/gcc@12/x86_64-apple-darwin21/bin/ -B/Users/qtang/.brew/opt/gcc@12/x86_64-apple-darwin21/lib/ -isystem /Users/qtang/.brew/opt/gcc@12/x86_64-apple-darwin21/include -isystem /Users/qtang/.brew/opt/gcc@12/x86_64-apple-darwin21/sys-include   -fno-checking -g -O2 -O2  -g -O2 -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -mmacosx-version-min=10.8 -fno-common -mmacosx-version-min=10.8 -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -mmacosx-version-min=10.8 -fno-common -mmacosx-version-min=10.8 -I. -I. -I../.././gcc -I../../../libgcc -I../../../libgcc/. -I../../../libgcc/../gcc -I../../../libgcc/../include  -DHAVE_CC_TLS -DUSE_EMUTLS  -o avx_resms64x_s.o -MT avx_resms64x_s.o -MD -MP -MF avx_resms64x_s.dep -DSHARED -c -xassembler-with-cpp ../../../libgcc/config/i386/avx_resms64x.S
make[3]: /private/tmp/gccA12-20231001-31122-1lrxn8k/gcc-12.3.0/build/./gcc/xgcc: Permission denied
make[3]: *** [avx_savms64_s.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [avx_resms64_s.o] Error 1
make[3]: *** [avx_resms64x_s.o] Error 1
/bin/sh ../../../libgcc/../move-if-change tmp-libgcc_tm.h libgcc_tm.h
echo timestamp > libgcc_tm.stamp
make[2]: *** [all-stage1-target-libgcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2
```

### What did you expect to happen?

I hope one of `gcc` 11, 12 or 13 can be installed. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
git clone --depth=1 https://github.com/Homebrew/brew ~/.brew
export PATH="$HOME/.brew/bin:$HOME/.brew/sbin:$PATH"
brew upgrade
brew install gcc
```

**Comment by MikeMcQuaid** [comment]
> ```shell
> Do not create any issues about this on Homebrew's GitHub repositories.
> Do not create any issues even if you think this message is unrelated.
> Any opened issues will be immediately closed without response.
> ```

**Comment by tangqi** [comment]
Thanks, is there any workaround at all? Is the only option to install `brew` in the default location? Or is there any place I can ask for help?

**Comment by ZhongRuoyu** [comment]
> is there any workaround at all? Is the only option to install brew in the default location?

Having `brew` outside its default prefix may work for most formulae, either built from source or poured from bottle. However, we don't support fixing source-build failures; otherwise there would be far too many issues to be manageable.

> Or is there any place I can ask for help?

Please read your `brew doctor` output carefully and you'll find an answer:

```
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
```

**Comment by tangqi** [comment]
That's very fair. I appreciate your help. 

What would be other options to build `gcc` through "built from source or poured from bottle"? I tried all the available gcc on brew but all generate a similar error. Missing gcc in brew makes it difficult to install other packages. Alternatively, if I built a gcc by myself, is there a way to tell brew to use that gcc to install other packages (e.g., open-mpi or mpich)?

**Comment by ZhongRuoyu** [comment]
> What would be other options to build `gcc` through "built from source or poured from bottle"?

Either build from source or pour from bottle, these are the two options you have (and the former is not supported). For `gcc`: the latter is only available for default prefixes because the bottle not relocatable.

> Missing gcc in brew makes it difficult to install other packages.

Note that macOS formulae are not built with GCC (although they are on Linux, by default). Most of them are built with Clang from Xcode / Command Line Tools, which you already have.

**Comment by Bo98** [comment]
If you can't use the default prefix then open a [discussion](https://github.com/orgs/Homebrew/discussions) with full logs (`brew gist-logs gcc`) and someone might be able to figure it out. From the snippets given, it's hard to figure out what's wrong and it's not something we've come across in our own CI, which is why we're unable to help or guarantee any solution.

**Comment by tangqi** [comment]
Thanks for all the helpful suggestions. I did have a gist-logs ready and I will open a discussion. 

It is not uncommon that we cannot access the default location in the government owned laptop. Unfortunately.
