### ISSUE TITLE
Following verbiage is a both helpful and vague: Installing from the API is now the default behaviour! You can save space and time by running:   brew untap homebrew/core   brew untap homebrew/cask

### ISSUE THREAD

**Issue by penalvch** [Homebrew/brew#16065]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When one runs the following command:
`brew update`

Brew advises back the following:
[START]
Installing from the API is now the default behaviour!

You can save space and time by running:
  brew untap homebrew/core
  brew untap homebrew/cask
Already up-to-date.
[END]

While the invitation to save space and time is greatly appreciated, it's fairly unclear to those either new to homebrew, non-developers, etc., even after reading the man page, what ramifications if any this would have on already installed casks. While it's presumed that no negative consequences would occur, it would be nice if a doc link was provided in scope of said change to so folks could review to this versus dumpster dive through commits trying to figure out what is going on.

### What is the motivation for the feature?

Help new and current users who are propositioned to a change be provided more helpful context to said change.

### How will the feature be relevant to at least 90% of Homebrew users?

It's presumed that 99%+ users of homebrew would have seen same at some point.

### What alternatives to the feature have been considered?

N/A

**Comment by MikeMcQuaid** [comment]
> what ramifications if any this would have on already installed casks. While it's presumed that no negative consequences would occur,

Correct, there are no negative consequences on installed casks. Trust in future that if we advise something: there aren't negative consequences. This doesn't need dedicated documentation.

**Comment by penalvch** [comment]
> Correct, there are no negative consequences on installed casks. 

Thanks for that.

> Trust in future that if we advise something: there aren't negative consequences.

That's great one has blind confidence. I have high confidence in homebrew and the ecosystem generally. However, blind trust is not how great software works. Trust but verify.

> This doesn't need dedicated documentation.

Not sure what that means. If you are stating having a dedicated website specific to this, sure, potential overkill. The message is still too vague.

Additionally, aside from already installed casks, what actual additional impact would this have on new casks, and tapped formula repositories is opaque.

Having some sort of deeper explanation within the message presented to the user, would help clear this up in a reasonable way.

**Comment by MikeMcQuaid** [comment]
> That's great one has blind confidence. I have high confidence in homebrew and the ecosystem generally. However, blind trust is not how great software works. Trust but verify.

This doesn't scale. Don't open issues to ask questions like this again. If you need to verify the messaging I carefully added in code: I'm not sure why a random comment from my on an issue helps with anything.

> The message is still too vague.

I disagree.



> Having a clearer explanation within the message presented to the user, would be reasonable.
> For example:

I disagree that this is clearer. 


> Given one doesn't install from the API (that's done by the OS)

This is wrong.

**Comment by penalvch** [comment]
@MikeMcQuaid, thanks for the quick review and response on this.

> This doesn't scale.

Fair. I'm not advocating for process around something, but simply a potential improvment on this message, if possible.

> Don't open issues to ask questions like this again.

I noticed there was a feature request venue for Homebrew as per below:
![image](https://github.com/Homebrew/brew/assets/115644052/6ac585ef-9fba-4808-a4aa-672049ae093d)

I submitted an FR and the review was done and closed by you.

Ordering / implied threatening me not to file FRs I genuinely find would be helpful (including this one) would be a bit hostile.

> If you need to verify the messaging I carefully added in code: I'm not sure why a random comment from my on an issue helps with anything.

Additional insight on your submission outside of code is helpful. Thanks for the share.

> The message is still too vague.

>> I disagree.

> Having a clearer explanation within the message presented to the user, would be reasonable.
For example:

>> I disagree that this is clearer.

While I respect your view, given I genuinely was confused, and how I can see others who may not be technically savy, developers, etc. also get confused, it seems there could be a clearer message.

I'll have a think on it and if I can come up with additional alternatives, different take, etc. I hope as a project maintainer you would be receptive to new ideas and potentials to help homebrew users.

> Given one doesn't install from the API (that's done by the OS)

>> This is wrong.

I see why you would say this.

As per example below:
```
brew install -v adobe-acrobat-reader
==> Downloading https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> Downloading https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> Downloading https://ardownload2.adobe.com/pub/adobe/reader/mac/AcrobatDC/2300620320/AcroRdrDC_2300620320_MUI.dmg
Already downloaded: /Users/moniker/Library/Caches/Homebrew/downloads/743d02059df4308e5ea674180efce2425a7adc887dd2e1772f6794f52e05ed94--AcroRdrDC_2300620320_MUI.dmg
==> Verifying checksum for '743d02059df4308e5ea674180efce2425a7adc887dd2e1772f6794f52e05ed94--AcroRdrDC_2300620320_MUI.dmg'
==> Installing Cask adobe-acrobat-reader
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20231001-77785-1dbrnpo /Users/moniker/Library/Caches/Homebrew/downloads/743d02059df4308e5ea674180efce2425a7adc887dd2e1772f6794f52e05ed94--AcroRdrDC_2300620320_MUI.dmg
/usr/bin/env mkbom -s -i /private/tmp/20231001-77785-3djhdi.list -- /private/tmp/20231001-77785-15e3i44.bom
/usr/bin/env ditto --bom /private/tmp/20231001-77785-15e3i44.bom -- /private/tmp/d20231001-77785-1dbrnpo/dmg.qfNh2y /private/tmp/d20231001-77785-1212th6
/usr/bin/env diskutil info -plist /private/tmp/d20231001-77785-1dbrnpo/dmg.qfNh2y
/usr/bin/env diskutil eject /private/tmp/d20231001-77785-1dbrnpo/dmg.qfNh2y
cp -p /private/tmp/d20231001-77785-1212th6/AcroRdrDC_2300620320_MUI.pkg /opt/homebrew/Caskroom/adobe-acrobat-reader/23.006.20320/AcroRdrDC_2300620320_MUI.pkg
==> Running installer for adobe-acrobat-reader; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is Adobe Acrobat Reader (Continuous)
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Adobe Acrobat Reader (Continuous)…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%4.539467
installer:PHASE:Writing files…
installer:%17.744848
installer:PHASE:Writing files…
installer:%47.763111
installer:PHASE:Writing files…
installer:%58.678843
installer:PHASE:Writing files…
installer:%67.312081
installer:PHASE:Running package scripts…
installer:%67.995159
installer:PHASE:Running package scripts…
installer:%68.676432
installer:PHASE:Running package scripts…
installer:%69.358774
installer:PHASE:Running package scripts…
installer:%70.040869
installer:PHASE:Running package scripts…
installer:%70.723079
installer:PHASE:Running package scripts…
installer:%71.405586
installer:PHASE:Running package scripts…
installer:%72.087825
installer:PHASE:Running package scripts…
installer:%72.323508
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:%88.792687
installer:PHASE:Running package scripts…
installer:%89.474835
installer:PHASE:Running package scripts…
installer:%90.157178
installer:PHASE:Running package scripts…
installer:%90.839363
installer:PHASE:Running package scripts…
installer:%91.521633
installer:PHASE:Running package scripts…
installer:%92.203857
installer:PHASE:Running package scripts…
installer:%92.885931
installer:PHASE:Running package scripts…
installer:%93.568208
installer:PHASE:Running package scripts…
installer:%94.250479
installer:PHASE:Running package scripts…
installer:%94.837205
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer:STATUS:Running installer actions…
installer:STATUS:
installer:PHASE:Finishing the Installation…
installer:STATUS:
installer:%100.000000
installer:PHASE:The software was successfully installed.
installer: The install was successful.
🍺  adobe-acrobat-reader was successfully installed!
~ % 
```

homebrew initiated a download from Adobe, and initiated an .app install from the OS as per:
```
==> Running installer for adobe-acrobat-reader; your password may be necessary.
```
Naturally, not all casks involve .app files so no install from the OS in the macOS app sense occurs.

**Comment by apainintheneck** [comment]
@penalvch For these sorts of questions you're better off opening a discussion next time.
- https://github.com/orgs/Homebrew/discussions

For more information about what using the API means you can look at the v4.0 and v4.1 release notes. I don't think we have a general overview of what using the API means outside of these blog posts.
- https://brew.sh/2023/02/16/homebrew-4.0.0/
- https://brew.sh/2023/07/20/homebrew-4.1.0/

The API is only an optimization for the internal taps `homebrew/core` and `homebrew/cask`. All external taps are still using the old Git based method. In fact, the Git based method is still used for internal taps when creating/updating package definitions and bottles (pre-built package binaries) but is not needed when doing normal package manager things like installing, upgrading, uninstalling, etc.

**Comment by penalvch** [comment]
@apainintheneck, thanks for the helpful response!

> @penalvch For these sorts of questions you're better off opening a discussion next time.

As I don't have a question, but a suggestion to change, I think this is a fair venue.

> For more information about what using the API means you can look at the v4.0 and v4.1 release notes. I don't think we have a general overview of what using the API means outside of these blog posts.
> 
> * https://brew.sh/2023/02/16/homebrew-4.0.0/
> * https://brew.sh/2023/07/20/homebrew-4.1.0/
> 
> The API is only an optimization for the internal taps `homebrew/core` and `homebrew/cask`. All external taps are still using the old Git based method. In fact, the Git based method is still used for internal taps when creating/updating package definitions and bottles (pre-built package binaries) but is not needed when doing normal package manager things like installing, upgrading, uninstalling, etc.

Thanks for that additional insight. As I mentioned in my prior comment, I'll have a think and if I can come up with something that may be better, no guarantee, I'll propose and go from there. :)

**Comment by MikeMcQuaid** [comment]
> Fair. I'm not advocating for process around something, but simply a potential improvment on this message, if possible.

I can't figure out a better message here that would tell you what you want without being incorrect.

> I submitted an FR and the review was done and closed by you.
> Ordering / implied threatening me not to file FRs I genuinely find would be helpful (including this one) would be a bit hostile.

No-one is being threatened here. I do not really appreciate your tone in this issue; I'm finding it a bit rude and argumentative; that's why I'm asking you not to open similar feature requests in future.

> @penalvch For these sorts of questions you're better off opening a discussion next time.

Yeh, what @apainintheneck said was a better way of saying it, apologies.

> I hope as a project maintainer you would be receptive to new ideas and potentials to help homebrew users.
> As I mentioned in my prior comment, I'll have a think and if I can come up with something that may be better, no guarantee, I'll propose and go from there. :)

We are and would greatly appreciate this (provided it's done politely and noting we will only merge a PR if it's an improvement).

A PR would be the best vehicle for this.
