### ISSUE TITLE
brew outdated can trigger auto-tapping of the boneyard

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#1607]
This seems like rather undesirable behavior:

```
iMac-TMP:homebrew-core joe$ brew outdated
==> Tapping homebrew/boneyard
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard'...
remote: Counting objects: 278, done.
remote: Compressing objects: 100% (274/274), done.
remote: Total 278 (delta 4), reused 173 (delta 4), pack-reused 0
Receiving objects: 100% (278/278), 176.59 KiB | 0 bytes/s, done.
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.
Tapped 265 formulae (298 files, 595.2K)
jasper (2.0.3-alpha1) < 2.0.3
libunistring (0.9.6) < 0.9.7
mercurial (4.0) < 4.0.1
subversion (1.9.5) < 1.9.5_1
```

**Comment by MikeMcQuaid** [comment]
Lots of weird things can trigger that tapping if installed formulae are moved in. The primary mechanism for this for non-maintainers will always end up being `brew update` (or the autoupdate equivalent), though so I don't see this as a big deal, personally. We still communicate with users on e.g. boneyard formula failures that they shouldn't be reported.

**Comment by ilovezfs** [comment]
Auto-tapping in general seems fine, but I absolutely don't think we should auto-tap the boneyard. That doesn't make any sense.

**Comment by MikeMcQuaid** [comment]
> Auto-tapping in general seems fine, but I absolutely don't think we should auto-tap the boneyard. That doesn't make any sense.

Closing because the current plan is just to kill the boneyard and the relevant migrations after https://github.com/Homebrew/brew/pull/1732 has shipped in a tag.

**Comment by ilovezfs** [comment]
Die, :skull:, die!
