### ISSUE TITLE
Maybe big bug of homebrew services

### ISSUE THREAD

**Issue by hel1o-wor1d** [Homebrew/brew#16075]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I buy a litter vps, and install nginx:  
brew install nginx
brew services start nginx

But I find that when ssh login the vps,  I can visit the default website, when logout the ssh, I cannot visit the default web.

I test it by install nginx in my mac laptop, and visit the default website in my mobile phone,  same result.

It looks like homebrew-services only run when the user login, bug killed when logout.

That's not the same with what I thought. A service should run underground no matter login or logout.

Is there same option that let the homeber services can run underground similar whith system services ? 

### What is the motivation for the feature?

I buy a litter vps, and install nginx:  
brew install nginx
brew services start nginx

But I find that when ssh login the vps,  I can visit the default website, when logout the ssh, I cannot visit the default web.

I test it by install nginx in my mac laptop, and visit the default website in my mobile phone,  same result.

It looks like homebrew-services only run when the user login, bug killed when logout.

That's not the same with what I thought. A service should run underground no matter login or logout.

Is there same option that let the homeber services can run underground similar whith system services ? 

### How will the feature be relevant to at least 90% of Homebrew users?

I buy a litter vps, and install nginx:  
brew install nginx
brew services start nginx

But I find that when ssh login the vps,  I can visit the default website, when logout the ssh, I cannot visit the default web.

I test it by install nginx in my mac laptop, and visit the default website in my mobile phone,  same result.

It looks like homebrew-services only run when the user login, bug killed when logout.

That's not the same with what I thought. A service should run underground no matter login or logout.

Is there same option that let the homeber services can run underground similar whith system services ? 

### What alternatives to the feature have been considered?

I buy a litter vps, and install nginx:  
brew install nginx
brew services start nginx

But I find that when ssh login the vps,  I can visit the default website, when logout the ssh, I cannot visit the default web.

I test it by install nginx in my mac laptop, and visit the default website in my mobile phone,  same result.

It looks like homebrew-services only run when the user login, bug killed when logout.

That's not the same with what I thought. A service should run underground no matter login or logout.

Is there same option that let the homeber services can run underground similar whith system services ?

**Comment by MikeMcQuaid** [comment]
@hel1o-wor1d can you provide (a lot) more debugging information such as:
- the commands you're running and their output
- your `brew config` output
- your `brew doctor` output

Thanks!

**Comment by hel1o-wor1d** [comment]
> @hel1o-wor1d can you provide (a lot) more debugging information such as:
> 
>     * the commands you're running and their output
> 
>     * your `brew config` output
> 
>     * your `brew doctor` output
> 
> 
> Thanks!

not need.

it's just that when you login system, the homebrew services start run ,when you logout system. the homebrew services stop.
But I want that the services keep running even when I logout the system.

**Comment by MikeMcQuaid** [comment]
> it's just that when you login system, the homebrew services start run ,when you logout system. the homebrew services stop.
> But I want that the services keep running even when I logout the system.

This requires using `sudo brew services`. For better security: use with `--sudo-service-user`.
