### ISSUE TITLE
PosixBrew, not macbrew, not linuxbrew

### ISSUE THREAD

**Issue by hel1o-wor1d** [Homebrew/brew#16092]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I wonder why the installation prefixes are different: /usr/local, /opt/homebrew, /home/linuxbrew/.linuxbrew ?

Why not keep same?

### What is the motivation for the feature?

I wonder why the installation prefixes are different: /usr/local, /opt/homebrew, /home/linuxbrew/.linuxbrew ?

Why not keep same?

### How will the feature be relevant to at least 90% of Homebrew users?

I wonder why the installation prefixes are different: /usr/local, /opt/homebrew, /home/linuxbrew/.linuxbrew ?

Why not keep same?

### What alternatives to the feature have been considered?

I wonder why the installation prefixes are different: /usr/local, /opt/homebrew, /home/linuxbrew/.linuxbrew ?

Why not keep same?

**Comment by Bo98** [comment]
On macOS: so you can install x86_64 and arm64 side by side on the same system (using Rosetta). Many people do this, so we intentionally have different install prefixes there.

On Linux: historical reasons when Homebrew for Linux used to be an unofficial fork called "Linuxbrew". Changing it now would break a lot of things, so is not reasonably possible.

If a theoretical third OS was ported, we perhaps would be more consistent on `/opt/homebrew`.
