### ISSUE TITLE
bump-cask-pr ignore parameter --url

### ISSUE THREAD

**Issue by b-reich** [Homebrew/brew#16114]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.15-36-gc0c8a4d
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0c8a4dd4dd19ec16deb429abd50cdf82ea33b27
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ea857d8d20882012199a728ac3deedf34cb98374
Core tap last commit: 3 hours ago
Core tap branch: master
Core tap JSON: 14 Oct 20:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim -f
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

create a pr for an updated cask

### What happened (include all command output)?

```
brew bump-cask-pr bambu-studio --url "https://public-cdn.bambulab.com/upgrade/studio/software/01.07.07.89/b60b436b40/Bambu_Studio_mac-v01.07.07.89.dmg" --sha256 9e69db7bd748b8642ae06b9f4b3ba86a2b65a0624ead7619c21e72e58c4b4409 --version 01.07.07.89
==> Downloading https://public-cdn.bambulab.com/upgrade/studio/software/01.07.07.89/Bambu_Studio_mac-v01.07.07.89.dmg
curl: (22) The requested URL returned error: 403

Error: Download failed on Cask 'bambu-studio' with message: Download failed: https://public-cdn.bambulab.com/upgrade/studio/software/01.07.07.89/Bambu_Studio_mac-v01.07.07.89.dmg
```

### What did you expect to happen?

it should use the provided link. Not the generated one from the newer version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump-cask-pr bambu-studio --url "https://public-cdn.bambulab.com/upgrade/studio/software/01.07.07.89/b60b436b40/Bambu_Studio_mac-v01.07.07.89.dmg" --sha256 9e69db7bd748b8642ae06b9f4b3ba86a2b65a0624ead7619c21e72e58c4b4409 --version 01.07.07.89
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/157696

**Comment by apainintheneck** [comment]
It looks like we're trying to fetch the cask to compute the checksum before we substitute in the new url. We should probably just do the url substitution first.

https://github.com/Homebrew/brew/blob/46a83103904718eb739c455ff7fb43b010e62bf5/Library/Homebrew/dev-cmd/bump-cask-pr.rb#L119-L149

I also wonder if we want to do any extra checks when substituting a url when a cask uses live check. In this case, the PR would have been created successfully I think but it would have been rejected since the change we want here is to update the live check code to handle the new url pattern.

**Comment by MikeMcQuaid** [comment]
> It looks like we're trying to fetch the cask to compute the checksum before we substitute in the new url. We should probably just do the url substitution first.

Agreed 👍🏻 



> I also wonder if we want to do any extra checks when substituting a url when a cask uses live check. In this case, the PR would have been created successfully I think but it would have been rejected since the change we want here is to update the live check code to handle the new url pattern.

Yes, it feels like having a "bumped formulae/casks that will be definitely rejected due to livecheck" sort of check would be useful, similarly to how `brew audit` is automatically run for formulae or casks in that situation (although I'm unsure if that calls through to livecheck in any way already).

**Comment by apainintheneck** [comment]
It looks like there are some casks with livecheck that have static urls so I don't think we can have a general check for that. I'll just make the simple change here.
