### ISSUE TITLE
brew upgrade dont check --cask

### ISSUE THREAD

**Issue by Kurt-Shiwz** [Homebrew/brew#16110]
### `brew doctor` output

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
################################################################################################################# 100.0%
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  six
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: e57a87cfe9c15f192cd4fc6695a2b3b7acf0ddf7
Last commit: 4 days ago
Core tap JSON: 13 Oct 10:31 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew upgrade` ,i want upgrade all package and cask

### What happened (include all command output)?

some app like qlmarkdown/macfuse, i install use `brew install --cask qlmarkdown`,it dont upgrade

### What did you expect to happen?

`brew install --cask xxx`,i want install by `--cask` also can  check and upgrade by `brew upgrade`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew upgrade`
```

**Comment by MikeMcQuaid** [comment]
These casks auto-update. Force upgrades with `brew upgrade --greedy`.
