### ISSUE TITLE
Error: formulae require at least a URL after upgrading MacOS to 14.0

### ISSUE THREAD

**Issue by junwu-cao** [Homebrew/brew#16123]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.16-15-gee9766a
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee9766aa7c72c04b33f309cced3922ad7d9637d1
Last commit: 17 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4b77ad95efcdf33cb2af851943951c30ce8d36c2
Core tap last commit: 44 minutes ago
Core tap branch: master
Core tap JSON: 20 Oct 17:33 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/vim
HOMEBREW_MAKE_JOBS: 16
$ brew config
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.42.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
```

### What were you trying to do (and why)?

$ brew upgrade vagrant

since 'brew outdated' reports that vagrant has a new version.

$ brew outdated
vagrant (2.3.6) != 2.4.0
virtualbox (7.0.6,155176) != 7.0.12,159484

### What happened (include all command output)?

Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
Warning: Removed Sorbet lines from backtrace!
Rerun with --verbose to see the original backtrace
/usr/local/Homebrew/Library/Homebrew/formula.rb:306:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:237:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:494:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:494:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:771:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:655:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:651:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:651:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:323:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:127:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'

### What did you expect to happen?

Normal upgrade messages (just like before upgrading MacOS to 14.0, was 13.5.x)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ sw_vers
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344

$ brew outdated
rpm (4.18.1) < 4.19.0
vagrant (2.3.6) != 2.4.0
virtualbox (7.0.6,155176) != 7.0.12,159484

$ brew upgrade vagrant
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
Warning: Removed Sorbet lines from backtrace!
Rerun with --verbose to see the original backtrace
/usr/local/Homebrew/Library/Homebrew/formula.rb:306:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:237:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:494:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:494:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:771:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:655:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:651:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:651:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:323:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:127:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

**Comment by Bo98** [comment]
What's the output of `brew upgrade vagrant --debug`

**Comment by junwu-cao** [comment]
$ brew upgrade vagrant --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader):
loading
/usr/local/Homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/vagrant.rb
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
Warning: Removed Sorbet lines from backtrace!
Rerun with --verbose to see the original backtrace
/usr/local/Homebrew/Library/Homebrew/formula.rb:306:in
`determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:237:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:494:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:494:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:771:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:655:in `block in
formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:651:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:651:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:323:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:127:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'

**Comment by EricFromCanada** [comment]
This is an issue with the [Hashicorp `vagrant` formula](https://github.com/hashicorp/homebrew-tap/blob/master/Formula/vagrant.rb). I've already reported it to them along with a [suggested fix](https://github.com/hashicorp/homebrew-tap/pull/252), but they haven't responded.

**Comment by Bo98** [comment]
What I'm guessing happened here is you had the Vagrant cask, later tapped `hashicorp/tap` and now the version of Vagrant in that tap is taking priority which only supports Linux.

You can continue to use the cask by doing `brew upgrade --cask vagrant`.

**Comment by junwu-cao** [comment]
Thank you so much. It works!

**Comment by apainintheneck** [comment]
We could always try and catch that error and then it should default to the cask in this case. The output would look like this. Not sure if that would be confusing though.

```shell
$ brew install -n vagrant
Error: Failed to load formula: vagrant
formulae require at least a URL
Warning: Treating vagrant as a cask.
==> Would install 1 cask:
vagrant
$ brew install -n vagrant --formula
Error: formulae require at least a URL
Warning: Removed Sorbet lines from backtrace!
Rerun with --verbose to see the original backtrace
/usr/local/Homebrew/Library/Homebrew/formula.rb:306:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:237:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:494:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:494:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:771:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:126:in `block in load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/api.rb:197:in `with_no_api_env_if_needed'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:118:in `load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:83:in `block in to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:195:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

Changes:
```diff
diff --git a/Library/Homebrew/cli/named_args.rb b/Library/Homebrew/cli/named_args.rb
index e26a8d15f..c6f6f6097 100644
--- a/Library/Homebrew/cli/named_args.rb
+++ b/Library/Homebrew/cli/named_args.rb
@@ -140,7 +140,8 @@ module Homebrew
               warn_if_cask_conflicts(name, "formula") if only != :formula
               return formula
             rescue FormulaUnreadableError, FormulaClassUnavailableError,
-                   TapFormulaUnreadableError, TapFormulaClassUnavailableError => e
+                   TapFormulaUnreadableError, TapFormulaClassUnavailableError,
+                   FormulaSpecificationError => e
               # Need to rescue before `FormulaUnavailableError` (superclass of this)
               # The formula was found, but there's a problem with its implementation
               unreadable_error ||= e
diff --git a/Library/Homebrew/cli/parser.rb b/Library/Homebrew/cli/parser.rb
index c667283ac..993df1a3e 100644
--- a/Library/Homebrew/cli/parser.rb
+++ b/Library/Homebrew/cli/parser.rb
@@ -653,7 +653,7 @@ module Homebrew
 
           begin
             Formulary.factory(arg, spec, flags: argv.select { |a| a.start_with?("--") })
-          rescue FormulaUnavailableError
+          rescue FormulaUnavailableError, FormulaSpecificationError
             nil
           end
         end.compact.uniq(&:name)
```

**Comment by MikeMcQuaid** [comment]
@apainintheneck I think that would make sense, good idea!
