### ISSUE TITLE
brew update is stuck on 

### ISSUE THREAD

**Issue by crispy-tk** [Homebrew/brew#16133]
### `brew doctor` output

```shell
└─$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 2 days ago
Core tap JSON: 23 Oct 00:25 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit unknown_0x6_0x8c
Clang: N/A
Git: 2.40.1 => /bin/git
Curl: 8.2.1 => /bin/curl
Kernel: Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Kali GNU/Linux Rolling (kali-rolling)
WSL: 2 (Microsoft Store)
Host glibc: 2.37
/usr/bin/gcc: 13.2.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

I run `brew update` as usual and this time it stuck. It's been stuck for 3 days already. Tried every tip I found in the internet and run out of ideas.

### What happened (include all command output)?

Last lines of output from `brew update --debug --verbose`

+ echo 'Checking if we need to fetch formula.jws.json...'
Checking if we need to fetch formula.jws.json...
+ JSON_URLS=()
+ [[ -n '' ]]
+ JSON_URLS+=("${HOMEBREW_API_DEFAULT_DOMAIN}/${filename}")
+ for json_url in "${JSON_URLS[@]}"
+ time_cond=()
+ [[ -s /home/kali/.cache/Homebrew/api/formula.jws.json ]]
+ time_cond=("--time-cond" "${cache_path}")
+ curl -q --fail --compressed --silent --speed-limit 100 --speed-time 5 --location --remote-time --output /home/kali/.cache/Homebrew/api/formula.jws.json --time-cond /home/kali/.cache/Homebrew/api/formula.jws.json --user-agent 'Linuxbrew/4.1.17 (Linux; x86_64 Kali GNU/Linux Rolling) curl/8.2.1' https://formulae.brew.sh/api/formula.jws.json
+ [[ -z '' ]]
++ /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/curl --homebrew=print-path
+ CURL_EXECUTABLE=/bin/curl
+ [[ -z /bin/curl ]]
+ /bin/curl -q --fail --compressed --silent --speed-limit 100 --speed-time 5 --location --remote-time --output /home/kali/.cache/Homebrew/api/formula.jws.json --time-cond /home/kali/.cache/Homebrew/api/formula.jws.json --user-agent 'Linuxbrew/4.1.17 (Linux; x86_64 Kali GNU/Linux Rolling) curl/8.2.1' https://formulae.brew.sh/api/formula.jws.json

### What did you expect to happen?

It should update everything.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
----SCENARIO 1----
1. Open Terminal
2. Run `brew update` (it hangs)

----SCENARIO 2----
1. Open Terminal
2. Run `brew update --debug --verbose` (shows the last lines I posted in the report)
```

**Comment by MikeMcQuaid** [comment]
Sorry, this is specific to your machine/ISP/etc.. You may have better luck in Homebrew's discussions.

Debugging this you may want to try running that `curl` command manually. If it can't access GitHub Pages (where formulae.brew.sh is hosted): there's nothing we can do about it.
