### ISSUE TITLE
'brew {outdated,upgrade}' and 'brew {outdated,upgrade} --cask' doesn't find any package to update, but direct upgrade of package works

### ISSUE THREAD

**Issue by edwintorok** [Homebrew/brew#16138]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libctxfuse.2.dylib
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 3 days ago
Core tap JSON: 25 Oct 08:14 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 15.0.0 build 1500
Git: 2.42.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
```

### What were you trying to do (and why)?

List outdated packages:
```
brew outdated
brew outdated --cask
brew upgrade
```

### What happened (include all command output)?

No outdated packages found, the output is empty.

### What did you expect to happen?

visual-studio-code to be updated, since brew knows there is a newer version available (via brew info) and will upgrade when asked to upgrade the package on its own.

Note that the old visual-studio-code got installed on an older version of Mac OS, and then Mac OS got upgraded, don't know if that matters.
Also the 'brew doctor' output doesn't say 'ready to brew', but the dylib is expected to be there and is not related to Homebrew, it does say the warning can be ignored, and I don't think it is related to Homebrew's inability to detect version upgrades.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
% brew outdated
% brew outdated --cask
% brew upgrade
% brew upgrade --cask
% brew info visual-studio-code
==> visual-studio-code: 1.83.1 (auto_updates)
https://code.visualstudio.com/
/usr/local/Caskroom/visual-studio-code/1.77.3 (132B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/v/visual-studio-code.rb
==> Names
Microsoft Visual Studio Code
VS Code
==> Description
Open-source code editor
==> Artifacts
Visual Studio Code.app (App)
/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code (Binary)
==> Analytics
install: 28,134 (30 days), 81,265 (90 days), 184,445 (365 days)

% brew upgrade visual-studio-code
==> Upgrading 1 outdated package:
visual-studio-code 1.77.3 -> 1.83.1
==> Upgrading visual-studio-code
==> Downloading https://update.code.visualstudio.com/1.83.1/darwin/stable
```
```

**Comment by Bo98** [comment]
https://docs.brew.sh/FAQ#why-arent-some-apps-included-during-brew-upgrade

`--greedy` will make it show

**Comment by edwintorok** [comment]
If I start 'visual-studio-code' it won't update itself though, is that a bug in that package?

**Comment by edwintorok** [comment]
Maybe 'brew outdated --cask' and 'brew update --cask' should default to '--greedy'? (or show a warning that --cask is deprecated and --greedy should be used instead?)Otherwise what is the meaning of '--cask' on those commands?

**Comment by MikeMcQuaid** [comment]
> If I start 'visual-studio-code' it won't update itself though, is that a bug in that package?

It will and does for me. If it doesn't: report it to Visual Studio Code themselves, not Homebrew.

> Maybe 'brew outdated --cask' and 'brew update --cask' should default to '--greedy'?

No, they should not. It's a waste of resources.



> Otherwise what is the meaning of '--cask' on those commands?

Upgrade casks, not formulae.
