### ISSUE TITLE
Homebrew mistakes any directory containing a directory with a symlink to the brew binary for its prefix

### ISSUE THREAD

**Issue by therealpxc** [Homebrew/brew#16136]
### `brew doctor` output

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pkg-config
  xmlto
  dbus
  docbook-xsl
  docbook

Warning: You have uncommitted modifications to Homebrew/brew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /Users/pxc/.local/opt/homebrew && git stash -u && git clean -d -f

Uncommitted files:
   D Library/Homebrew/os/mac/pkgconfig/fuse/fuse.pc
   D Library/Homebrew/os/mac/pkgconfig/fuse/osxfuse.pc
   D Library/Homebrew/vendor/gems/mechanize-2.9.1/mechanize-2.9.1

Warning: Your Homebrew's prefix is not /opt/homebrew.

Many of Homebrew's bottles (binary packages) can only be used with the default prefix.
Consider uninstalling Homebrew and reinstalling into the default prefix.
It is expected behaviour that some formulae will fail to build in this unsupported configuration.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.


Warning: You have multiple Cellars.
You should delete /Users/pxc/.local/opt/homebrew/Cellar:
  rm -rf /Users/pxc/.local/opt/homebrew/Cellar
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.17-9-g141ac15-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 141ac157fddd0dbd6c3331c8cc8751412a9acf05
Last commit: 5 hours ago
Core tap JSON: 24 Oct 23:00 UTC
HOMEBREW_PREFIX: /Users/pxc/.local
HOMEBREW_REPOSITORY: /Users/pxc/.local/opt/homebrew
HOMEBREW_CELLAR: /Users/pxc/.local/opt/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Users/pxc/.local/bin/kec
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I want to use Homebrew in a per-user prefix, without putting the binaries of every transitive dependency it installs on my PATH. Thus Homebrew lives in `~/.local/opt/homebrew`, with the `brew` executable at `~/.local/opt/homebrew/bin`, but `~/.local/opt/homebrew/bin` is not on my path.

Instead, select executables from `~/.local/opt/homebrew/bin` are symlinked into `~/.local/bin`, which is on my path. Among the executables so symlinked is `brew` itself, which is the source of my problems.

### What happened (include all command output)?

When the Homebrew executable is accessed via symlink from a directory other than its actual install prefix, for *only some operations*, it mistakenly assumes that its install prefix is whatever directory is grandparent to that symlink. I believe this is related to how I've ended up with two Cellars, as the 'extra' one is is in `~/.local`, directly under the mistaken prefix.

```
$ realpath $(which brew)
/Users/pxc/.local/opt/homebrew/bin/brew

$ which brew
/Users/pxc/.local/bin/brew

$ brew config | grep PREFIX
HOMEBREW_PREFIX: /Users/pxc/.local

$ $(realpath $(which brew)) config | grep PREFIX
HOMEBREW_PREFIX: /Users/pxc/.local/opt/homebrew

$ mkdir -p this/is/not/my/homebrew/prefix/location
$ ln -s $(realpath $(which brew)) this/is/not/my/homebrew/prefix/location
$ this/is/not/my/homebrew/prefix/location/brew config | grep PREFIX
HOMEBREW_PREFIX: /Users/pxc/this/is/not/my/homebrew/prefix
```

### What did you expect to happen?

I expected Homebrew to know that it's not 'installed' at (and entitled and predisposed to install new executables and symlinks *to*) any directory that the `brew` binary happens to by symlinked into. Some common-sense configurability of this behavior (e.g., via environment variable) would be nice. Alternatively, *resolving* such symlinks before assuming it has found the install prefix would be a reasonable zero-config behavior.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Note: I included my original `brew doctor` output above because it indicates how this kind of thing can lead to the dual-Cellar problem. The problem is fully reproducible with Homebrew installed at the standard prefix, however, and I added a Homebrew install at the standard prefix just to confirm that before submitting.

Here is that installation's `brew doctor` output:

Your system is ready to brew.
```

Here is that installation's `brew config`:
```
HOMEBREW_VERSION: 4.1.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 3 days ago
Core tap JSON: 25 Oct 00:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Users/pxc/.local/bin/kec
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

After Homebrew is installed, run

```
mkdir -p ~/this/is/not/my/homebrew/prefix/location
ln -s "$(realpath "$(which brew)")" ~/this/is/not/my/homebrew/prefix/location
~/this/is/not/my/homebrew/prefix/location/brew config
```

Observe the incorrect installation prefix deduction.

To reproduce Cellar duplication:

1. Remove the Cellar from your Homebrew repository, e.g.,  -rf ~/.local/opt/homebrew/Cellar```
2. Source `brew shellenv` where `brew` is invoked from some symlinked path. ```. <(this/is/not/my/homebrew/prefix/location/brew shellenv) ```
3. `brew install` something you don't already have.
4. `brew install` something from another terminal/session, from the full path.

You can reproduce the latter part without actually producing duplicate Cellars or polluting your installation with just

```
. <(brew shellenv)
mv "${HOMEBREW_CELLAR}" "${HOMEBREW_CELLAR}.old"
mkdir -p ~/this/is/not/my/homebrew/prefix/location/brew
~/this/is/not/my/homebrew/prefix/location/brew config
mv "${HOMEBREW_CELLAR}.old" "${HOMEBREW_CELLAR}"
```

Note: There is a somewhat simple workaround to the symlink use case, of course, which is to create a wrapper script instead of a symlink. On my system, I use just:

```
#!/bin/bash
~/.local/opt/homebrew/bin/brew "$@"
```

Still, I think the weird installation prefix deduction logic here is wrong, and deserves to be sorted out.
```

**Comment by MikeMcQuaid** [comment]
> When the Homebrew executable is accessed via symlink from a directory other than its actual install prefix, for _only some operations_, it mistakenly assumes that its install prefix is whatever directory is grandparent to that symlink.
> Still, I think the weird installation prefix deduction logic here is wrong, and deserves to be sorted out.

Sorry, this is not a mistake or wrong but behaviour that's specifically relied upon for macOS Intel and has been in place for a very long time at this point. Changing it to meet your preferences it likely to result in a bunch of issues where it gets broken in another direction.

> There is a somewhat simple workaround to the symlink use case, of course, which is to create a wrapper script instead of a symlink.

Yup, this is the best fix for your situation, sorry.

**Comment by therealpxc** [comment]
I understand. I suspected this might be the kind of quirk that looks gnarly when you stumble upon it but is depended on for other use cases. :-\

I'm curious about the existing use cases and history here! I'll poke around to see if I can quickly surface more information about that, but if you remember more offhand or feel like telling a story, I'd be grateful for a reference to a bit of code or an issue or something.

Thanks for reviewing this long-ass bug report. :)
