### ISSUE TITLE
brew is not following ulimit M2

### ISSUE THREAD

**Issue by Kakcalu13** [Homebrew/brew#16146]
### `brew doctor` output

```shell
bwuk@KOs-Mac-mini ~ % brew doctor                   
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Xcode (14.2) is outdated.
Please update to Xcode 14.3 (or delete it).
Xcode can be updated from the App Store.

bwuk@KOs-Mac-mini ~ %
```

### Verification

- [] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
bwuk@KOs-Mac-mini ~ % brew config
HOMEBREW_VERSION: 4.1.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 4 days ago
Core tap JSON: 26 Oct 00:24 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.2
Rosetta 2: false
bwuk@KOs-Mac-mini ~ %
```

### What were you trying to do (and why)?

Trying to install `brew install gz-harmonic` and because I want to have simulation in my mac. I tried to run `ulimit -n unlimited` and it doesn't read the mac m2's system. See here which is PR'd by one of gazebo developers: https://github.com/Homebrew/brew/pull/14879/files

The PR above reads the system but brew did not read on the M2.

I tried the commands from this issue:
https://github.com/Homebrew/brew/issues/9120#issuecomment-726356297

which is
```
cat /proc/sys/fs/file-max
ulimit -Hn
ulimit -Sn
cat /proc/1234/limits
```

I was able to run on 2nd and 3rd but not 1st and last due to not exist in m2.

See the below

### What happened (include all command output)?

cat /proc/sys/fs/file-max

```
  bwuk@KOs-Mac-mini ~ % cat /proc/sys/fs/file-max
  
  cat: /proc/sys/fs/file-max: No such file or directory
  bwuk@KOs-Mac-mini ~ % 
```

ulimit -Hn
```
bwuk@KOs-Mac-mini ~ % ulimit -Hn
unlimited
bwuk@KOs-Mac-mini ~ % 
```

ulimit -Sn
```
bwuk@KOs-Mac-mini ~ % ulimit -Sn
unlimited
bwuk@KOs-Mac-mini ~ % 
```

cat /proc/1234/limits
```
bwuk@KOs-Mac-mini ~ % cat /proc/1234/limits
cat: /proc/1234/limits: No such file or directory
bwuk@KOs-Mac-mini ~ % 
```

ulimit -a

```
bwuk@KOs-Mac-mini ~ % ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2666
-n: file descriptors                unlimited
bwuk@KOs-Mac-mini ~ % 
```

### What did you expect to happen?

I was expecting that brew was able to read M2's config (not sure if I used the right terminology) 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap osrf/simulation
brew install gz-harmonic
```

**Comment by Kakcalu13** [comment]
btw I need to upgrade my system to 13.4 to get latest xcode. I'm currently using 13.4. Pretty sure it doesnt do anything with brew able to read m2's config. Other than that, my brew is up to latest

**Comment by MikeMcQuaid** [comment]
> ```shell
> brew tap osrf/simulation
> brew install gz-harmonic
> ```

We don't support failing installations from third-party taps here, sorry.

**Comment by Kakcalu13** [comment]
> > ```shell
> > brew tap osrf/simulation
> > brew install gz-harmonic
> > ```
> 
> We don't support failing installations from third-party taps here, sorry.

Gotcha, thanks for your quick response! Does reading ulimit from brew counts as 3rd party? See here: https://github.com/Homebrew/brew/pull/14879/files

The issue is in `brew's lock_file.rb`

it was supposed to read M2's ulimit when using brew. Is that considered as 3rd party taps?

**Comment by MikeMcQuaid** [comment]
@Kakcalu13 I don't see evidence that that's the problem here. You've not provided reproduction with Homebrew commands that don't reference a third-party tap. We do not support issues with third-party taps.

**Comment by Kakcalu13** [comment]
Understood, thank you very much for your time!

**Comment by scpeters** [comment]
After a reboot it appears to be fixed (see https://github.com/gazebosim/gz-sim/issues/2215).

My best guess is that it was failing to open a lock file and printed the `ulimit -n` error message, but that the error was not actually caused by the `ulimit`. Nothing further to act on here.

Thanks for your time @MikeMcQuaid.
