### ISSUE TITLE
Logs ignore XDG_CACHE_HOME env variable while processing HOMEBREW_CACHE and HOMEBREW_LOGS

### ISSUE THREAD

**Issue by Tony-Sol** [Homebrew/brew#16156]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config                                                                                        1 2023-10-28 04:46:38
HOMEBREW_VERSION: 4.1.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 6 days ago
Core tap JSON: 28 Oct 01:43 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/tony/.local/cache/Homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 20-core 64-bit unknown_0x6_0x97
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.123.1-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 22.04.3 LTS (jammy)
WSL: 2 (Microsoft Store)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: 13.2.0
xorg: N/A
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to set homebrew's cache into specific location via `HOMEBREW_CACHE` env, but it's still creates `~/.cache/Homebrew` directory for logs which is not a suitable path in my case

### What happened (include all command output)?

![Screenshot 2023-10-28 050930](https://github.com/Homebrew/homebrew-core/assets/33671815/05185bea-f225-4eec-b417-6de6da98040e)

### What did you expect to happen?

Logs will be created in `${HOMEBREW_CACHE}/Logs`as man page says
![Screenshot 2023-10-28 050727](https://github.com/Homebrew/homebrew-core/assets/33671815/928ae8bd-a4a1-48c0-8333-7cc92d05b396)
![Screenshot 2023-10-28 050818](https://github.com/Homebrew/homebrew-core/assets/33671815/f4c2b631-dbdc-4371-bca9-85b5914c6eaf)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
rm -Rf ~/.cache/Homebrew # drop old cache dir
HOMEBREW_CACHE="${HOME}/.homebrew-cache" brew <anything> # do something
ls -la ~/ # see that there are two dirs - ~/.homebrew-cache AND again ~/.cache/Homebrew/Logs
```

**Comment by apainintheneck** [comment]
The relevant code is here:
https://github.com/Homebrew/brew/blob/97eda6479039d7f91e08da72135fbef28b65ef8d/Library/Homebrew/brew.sh#L35-L45

https://github.com/Homebrew/brew/blob/97eda6479039d7f91e08da72135fbef28b65ef8d/Library/Homebrew/brew.sh#L78-L80

Nothing looks obviously wrong though.

**Comment by Bo98** [comment]
> Nothing looks obviously wrong though.

Probably an env filtering issue

**Comment by apainintheneck** [comment]
Yeah, that's exactly it. I assume we don't allow this to pass through because it could affect build reproducibility.

We need to at least pass it from `bin/brew` to `brew.sh` where these values are set. The obvious thing to do here would be to just create a new `HOMEBREW_XDG_CACHE_HOME` variable that we export internally with the value of `XDG_CACHE_HOME` if it is set.
