### ISSUE TITLE
Mac OS X 10.6 detection broken with latest xcode.rb changes

### ISSUE THREAD

**Issue by semasupport** [Homebrew/brew#1619]
### Bug reports:
 The latest changes to xcode.rb ( if MacOS.version >= :mavericks ) has broken OS X 10.6 CLT detection causing "Your Command Line Tools are too outdated" and "A newer Command Line Tools release is available".  Reverting xcode.rb changes to "if Xcode::Version.new(MacOS.version) >= :mavericks.to_s" allows    10.6 and brew to behave correctly.

**Comment by scpeters** [comment]
I believe this is in reference to #1573

**Comment by semasupport** [comment]
This is correct - the changes stop brew working on 10.6 and prompt for a newer CLT.  Reverting xcode.rb locally allows normal operation on 10.6

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else. 

I don't have a 10.6 machine I can test this on. The revert is not correct but some other logic may be.

Thanks!

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/brew/pull/1621 may address your issue. Can you test it?

**Comment by semasupport** [comment]
I assumed I patch the file using unix patch with the output of your changes.  On 10.6 CLT detection is not working.

**Comment by ssreekanth** [comment]
It is still broken on 10.6.x

**Comment by MikeMcQuaid** [comment]
@ssreekanth We don't support 10.6 so we'll need someone here to create a pull request to fix the issue.
