### ISSUE TITLE
Check versions of auto-update casks for brew outdated --greedy

### ISSUE THREAD

**Issue by matgaj** [Homebrew/brew#16200]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When homebrew installs a cast that updates itself, it doesn't track the app version number after an automatic update. If you do a _brew outdated -g_, if the app gets a version update, brew will acknowledge that it is different than the one that was installed but it will not tell you if you are actually up to date. However, the .app files contain metadata listing their versions. I suggest adding a way to check the installed versions of auto-update casks to be able to check against the repo version and if the installed app is up to date.

### What is the motivation for the feature?

Some apps with automatic updates have trouble when it comes to notifying the user that an update is avalible (eg. messengerm spotify). This means the app stays out of date longer than necessary. This feature would allow the user to look through their apps to see if any have updates avalible to then run them through the app.

### How will the feature be relevant to at least 90% of Homebrew users?

It will be relevant to everyone who installs casks with automatic updates.

### What alternatives to the feature have been considered?

Manually keeping score of what is out of date - this is a non-solution though.

**Comment by MikeMcQuaid** [comment]
We'll review a PR for this but it's a niche behaviour of a non-default (`--greedy`) behaviour that will be hard to ensure is done consistently so not leaving an issue open for it, sorry.
