### ISSUE TITLE
Not able to add brew in mac m3 pro

### ISSUE THREAD

**Issue by Dhanush623** [Homebrew/brew#16201]
### `brew doctor` output

```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 75221 ms: Couldn't connect to server
```

### Verification

- [ ] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [ ] I ran `brew update` twice and am still able to reproduce my issue.
- [ ] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
Try to install brew using git repo getting this
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 75221 ms: Couldn't connect to server
```

### What were you trying to do (and why)?

Install brew

### What happened (include all command output)?

Not able to install brew

### What did you expect to happen?

need to install brew

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
tried to run https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)
```

**Comment by Bo98** [comment]
This is a network problem with likely your ISP. If you are in India, you might be affected by certain ISPs deciding to ban GitHub: https://github.com/orgs/community/discussions/42655.

Solutions include changing DNS servers or finding a mirror. There's nothing much we can do on our side I'm afraid.
