### ISSUE TITLE
BrewTestBot adding back broken symlinks

### ISSUE THREAD

**Issue by brc-dd** [Homebrew/brew#16205]
### `brew doctor` output

Please check "Debug Info" step here - https://github.com/vuejs/vitepress/actions/runs/6835197697/job/18588720961

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 3 weeks ago
Core tap JSON: 11 Nov 15:56 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3650
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: quad-core 64-bit zen3
Clang: 14.0.0
Git: 2.42.0 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 6.2.0-1015-azure x86_64 GNU/Linux
OS: Ubuntu 22.04.3 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: 3.0.2
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

Running vite on GitHub actions is breaking. I wasn't explicitly using brew in CI. This was fixed in #15950 but later regressed by the bot in https://github.com/Homebrew/brew/commit/c35b049b3cd1615fce0597d24f9ccd686a128db0

Related issue: https://github.com/Homebrew/brew/issues/15928

### What happened (include all command output)?

Getting:

```
⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
Error: ELOOP: too many symbolic links encountered, stat '/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/gems/mechanize-2.9.1/mechanize-2.9.1'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { errno: -40, code: 'ELOOP', syscall: 'stat', path: '/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/gems/mechanize-2.9.1/mechanize-2.9.1' }
```

### What did you expect to happen?

No error.

### Reproduction

You can check the workflow file in https://github.com/vuejs/vitepress/actions/runs/6835197697/job/18588720961 but the reproduction provided in #15928 might still apply.

**Comment by Bo98** [comment]
Thanks, will investigate what happened.

**Comment by brc-dd** [comment]
The issue is fixed in vite. But IMO brew still should be packaging mechanize properly.

**Comment by Bo98** [comment]
This isn't actually a Homebrew package. It's a partial vendor of a single file for internal Homebrew purposes, which is why this issue has never been reported outside of the `vite` as nothing except `vite` was reading it.

We'll still clean it up though as it's not supposed to be like that - I've just not found yet what's causing it.
