### ISSUE TITLE
Make progress bars prettier

### ISSUE THREAD

**Issue by chrisgrieser** [Homebrew/brew#16211]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Compared to other package managers, homebrew is somewhat "less pretty". I mostly notice this when updating/installing packages; the progress bars are the `#####` from `curl -#` which are pretty bare compared to progress bars from other package managers (here a comparison with `pip` and `npm`).

![Pasted image 2023-11-13 at 11 04 45@2x](https://github.com/Homebrew/brew/assets/73286100/d7dea651-2df6-4c55-ac5e-52133935c8f8)
![Pasted image 2023-11-13 at 11 06 28@2x](https://github.com/Homebrew/brew/assets/73286100/c2c3a26c-8934-4e93-a86b-00323680a4db)
![Pasted image 2023-11-13 at 11 09 41@2x](https://github.com/Homebrew/brew/assets/73286100/72643999-242f-4565-9f5c-49f17d704e32)

### What is the motivation for the feature?

Making the homebrew experience prettier. Not a crucial feature for sure, but a nice to have feature. I am fully aware that this is a low priority request.

Nonetheless, every package manager I have seen has prettier output than homebrew. So to a degree, this is also about "catching up" to the expectations people nowadays have of their package managers, similar to how colored output is nowadays expected of CLIs, even if it is not "necessary". 

### How will the feature be relevant to at least 90% of Homebrew users?

The improved aesthetic experience would affect every user who updates/installs packages.

### What alternatives to the feature have been considered?

I am not aware of any.

**Comment by MikeMcQuaid** [comment]
These are `curl`'s process bars not Homebrew's so the feature should be submitted there instead, sorry.
