### ISSUE TITLE
Better support for home directory installation

### ISSUE THREAD

**Issue by jevad** [Homebrew/brew#16222]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Make it easy and supported for Mac users to install Homebrew, formulae, casks and everything associated with them in their home directories.

### What is the motivation for the feature?

1) If only one user is going to use an application, which is the usual case for Homebrew, it is best practice for that application and everything associated with it to live in the user's home directory.

2) Like most Mac users, my usual user profile has zero administrative capabilities for obvious security reasons.  Changing the ownership of /usr/local/opt and most other directories in /usr/local breaks other things, so changing ownership of those directories is not an option.  Thus, every time I want to upgrade/update/install/unininstall anything to do with Homebrew, I need to change my user to one with directory ownership (and/or sometimes with sudo capability).  

3) Your current instructions make it clear that installing other than to /usr/local (or /opt/homebrew for Mac silicon) is both not supported and not recommended.

### How will the feature be relevant to at least 90% of Homebrew users?

See items (1) and (2) in the answer to the preceding question.

### What alternatives to the feature have been considered?

Following the advice in your current instructions which caution against installing in other than the default directories, I have not considered alternatives.

**Comment by MikeMcQuaid** [comment]
> 3\. Your current instructions make it clear that installing other than to /usr/local (or /opt/homebrew for Mac silicon) is both not supported and not recommended.

I'm afraid this is because it's currently not possible for us to deliver the majority of binary packages (the only configuration in which Homebrew is supported and works well) outside of the default locations because they are not relocatable (i.e. when installed elsewhere: they do not work).

This is something we're working making better long-term but it will be a long time, perhaps forever, before we ever are able to officially support home directory installation, sorry!
