### ISSUE TITLE
`HOMEBREW_COLOR=1` does not force coloured output

### ISSUE THREAD

**Issue by alexreg** [Homebrew/brew#16223]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.20-20-g71726fc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 71726fc3c8b46d3b0db1ab9856c8cf30bd6f151b
Last commit: 16 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0548a860d12c8148ec5054cb40dcf83be150a287
Core tap last commit: 14 minutes ago
Core tap branch: master
Core tap JSON: 16 Nov 01:20 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open -a Safari.app
HOMEBREW_CASK_OPTS: []
HOMEBREW_COLOR: set
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.LRotpeqouY/org.xquartz:0
HOMEBREW_EDITOR: mate_wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.1 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0.1
Rosetta 2: false
```

### What were you trying to do (and why)?

Redirect output of `brew upgrade` through `tee`, whilst setting `HOMEBREW_COLOR=1` (environment variable).

### What happened (include all command output)?

Output is only partially coloured/formatted.

<img width="706" alt="Screenshot 2023-11-16 at 01 32 25" src="https://github.com/Homebrew/brew/assets/67036/e66b86db-17f6-44cb-9e35-1718eaf51289">

<img width="716" alt="Screenshot 2023-11-16 at 01 32 37" src="https://github.com/Homebrew/brew/assets/67036/88de52cf-75b0-4524-be3d-cbdfe166ca98">

### What did you expect to happen?

All output should be coloured/formatted as usual.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
HOMEBREW_COLOR=1 brew upgrade | tee
```
```

**Comment by Bo98** [comment]
I'm guessing the stuff that is coloured is the lines going through stderr rather than stdout.

Anyhow, `HOMEBREW_COLOR` seems to work for me and also in GitHub Actions.

**Comment by MikeMcQuaid** [comment]
> ```shell
> HOMEBREW_COLOR=1 brew upgrade | tee
> ```

What are you actually trying to do here/how is this useful?

I appreciate the minimal reproduction but an actual reproduction with e.g. `tee some_file.txt` demonstrates why this behaviour is not implemented like how you want: because sticking terminal colour codes into a pipe/file is rarely the behaviour that's wanted.

Can you elaborate a bit more here?

**Comment by alexreg** [comment]
@MikeMcQuaid Sure. Basically what I want to do is log the output to a file at the same time as printing it to the console (with colour codes).

This is my literal usage (sorry).

```bash
brew upgrade | tee >(strip-ansi > log_file_name)
```

**Comment by Bo98** [comment]
The colour is controlled in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/tty.rb

I haven't been able to reproduce the problem you are having, and I don't see anything wrong in the code.

**Comment by alexreg** [comment]
@Bo98 Did you try on macOS 14? It's pretty deterministically reproducible here.

**Comment by Bo98** [comment]
Unfortunately, I don't have macOS 14 compatible hardware (yet).

However the check is as simple as ASCII codes get send if `HOMEBREW_COLOR` is set (TTY check is only considered if envs aren't involved).

**Comment by alexreg** [comment]
@Bo98 Okay, I'll look into this a bit more. Thanks. Good to know the code looks right, in any case.
