### ISSUE TITLE
Problems with OS X Sierra

### ISSUE THREAD

**Issue by andreamoro** [Homebrew/brew#1623]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Every time I ran a brew update or any other brew related command I got an error message. In fact, I cannot even complete the installation.

Previous than Sierra, all components were installed, but I realised today that something was broken. Despite many attempts I can't get out of the loop and complete the install.

The error shown on screen are as follow:

Brew update shows Already up-to-date. But this was just after an

`cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`

Prior than that I was receiving an error similar to the one below

```
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/andreamoro/.gem/ruby/2.0.0/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/andreamoro/.gem/ruby/2.0.0/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

[1]    8704 abort      brew doctor
```

I have manually re-installed rbenv and setup ruby 2.3.3 as a global default. However the path shown in the command line above seems ignoring it.

**Comment by andreamoro** [comment]
When trying to install it "manually", I get the following instead.

```
Error: uninitialized constant Homebrew::HOMEBREW_CASK_TAP_CASK_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:79:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:77:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:77:in `install'
/usr/local/Homebrew/Library/brew.rb:84:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
> However the path shown in the command line above seems ignoring it.

Homebrew uses the system Ruby 2.0.0. You need to `/usr/bin/gem uninstall json --user`

**Comment by andreamoro** [comment]
Hi Mike
Nice try, but I still get the same error message

```
==> Downloading and installing Homebrew...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 8 (delta 7), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/Homebrew/brew
 + 11cf7b9...60b1be6 master     -> origin/master  (forced update)
HEAD is now at 60b1be6 Merge pull request #1629 from zmwangx/bump-formula-pr-download-to-correct-version
To restore the stashed changes to /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git stash pop'
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/andreamoro/.gem/ruby/2.0.0/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/andreamoro/.gem/ruby/2.0.0/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

/usr/local/Homebrew/Library/Homebrew/brew.sh: line 37: 43412 Abort trap: 6           "$HOMEBREW_BREW_FILE" "$@"
Failed during: /usr/local/bin/brew update --force
```

Not sure what was the relationship between the json package and the default ruby language though. My ruby 2.3.3, manually installed, is located elsewhere.

**Comment by MikeMcQuaid** [comment]
> My ruby 2.3.3, manually installed, is located elsewhere.

That's not the Ruby Homebrew uses, it uses the system version. Try to `rm -rf /Users/andreamoro/.gem/ruby/2.0.0/gems/json-1.8.3`

**Comment by andreamoro** [comment]
That doesn't sound like a great option removing the default ruby, does it?

**Comment by MikeMcQuaid** [comment]
That's not removing the default Ruby (macOS won't let you any more even if you tried), it's removing the broken JSON gem you've installed just for your user that's provided with the default Ruby so is unnecessary.

Also, it's up to you whether you wish to follow my advice or not. If you don't wish to that's up to you but I can't help you any further.

**Comment by andreamoro** [comment]
Hey mike thanks, but sometimes it's better giving some explanations too like you did.
I didn't notice the -rf argument in first instance.

I'll give a try and let you know.

**Comment by andreamoro** [comment]
Hey Mike,

Thanks a lot. I made progresses.

Still got an error, but at least is less intimidating that it was used to be.

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kube-aws.rb
dlopen(/Users/andreamoro/.gem/ruby/2.0.0/gems/psych-2.0.15/lib/psych.bundle, 9): Library not loaded: /usr/local/opt/libyaml/lib/libyaml-0.2.dylib
  Referenced from: /Users/andreamoro/.gem/ruby/2.0.0/gems/psych-2.0.15/lib/psych.bundle
  Reason: image not found - /Users/andreamoro/.gem/ruby/2.0.0/gems/psych-2.0.15/lib/psych.bundle
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core
Failed during: /usr/local/bin/brew update --force

The funny thing is that I have now again a fresh install and in the /usr/local/Homebrew/Library/Taps there is nothing.

Any idea?

**Comment by MikeMcQuaid** [comment]
@andreamoro `rm -rf /Users/andreamoro/.gem/ruby/2.0.0/gems/psych-2.0.15`. To be honest it may be worth just doing `rm -rf /Users/andreamoro/.gem/ruby/2.0.0` and deleting all those gems as it appears there's a fair few that are broken.
