### ISSUE TITLE
`brew services` does not respect `HOMEBREW_NO_AUTO_UPDATE`

### ISSUE THREAD

**Issue by JounQin** [Homebrew/brew#16235]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: d3d51d3448966b5250b5c60110c945040054803d
Last commit: 7 days ago
Core tap JSON: 19 Nov 00:58 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.39.3 => /bin/git
Curl: 7.76.1 => /bin/curl
Kernel: Linux 5.14.0-284.30.1.el9_2.x86_64 x86_64 GNU/Linux
OS: Rocky Linux release 9.2 (Blue Onyx)
Host glibc: 2.34
/usr/bin/gcc: 11.3.1
/usr/bin/ruby: N/A
glibc: 2.35_1
gcc@11: N/A
gcc: 13.2.0
xorg: N/A
```

### What were you trying to do (and why)?

```sh
sudo brew services start v2raya -f .services/homebrew.v2raya.service -d
```

I need to start my service with `sudo`

### What happened (include all command output)?

```log
Error: Need to download https://formulae.brew.sh/api/formula.jws.json but cannot as root! Run `brew update` without `sudo` first then try again.
Error: Kernel.exit
Warning: Removed Sorbet lines from backtrace!
Rerun with --verbose to see the original backtrace
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:83:in `exit'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:83:in `odie'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api.rb:48:in `fetch_json_api_file'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api/formula.rb:43:in `download_and_cache_data!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api/formula.rb:65:in `all_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:951:in `loader_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:770:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:103:in `services'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### What did you expect to happen?

No error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
As above
```

**Comment by Bo98** [comment]
One requirement currently for sudo to work is for the `$HOME` variable to be preserved. Exactly whether and when this happens depends on your `sudoers` configuration.

An alternative is to set `XDG_CACHE_HOME` or `HOMEBREW_CACHE` and allow that to passthrough to sudo.

**Comment by Bo98** [comment]
Maybe something we could do is if we detect `HOMEBREW_CACHE` to be `/root/.cache/Homebrew` that we either skip this error or print additional information to it.

**Comment by MikeMcQuaid** [comment]
> Ubuntu behaves this way by default, but some other distros don't and I guess your distro is included in that.

Closing given this as a user-configuration issue. We'll review a PR to improve messaging etc.

**Comment by JounQin** [comment]
> OS: Rocky Linux release 9.2 (Blue Onyx)

I'm not using Ubuntu

**Comment by JounQin** [comment]
I'm not sure to understand how can I do to pass through the error, I do have `$HOME` variable. And what `HOMEBREW_CACHE` variable should be like?

**Comment by Bo98** [comment]
`sudo --preserve-env=HOME` will probably work for you with a sufficiently up-to-date `sudo`.

If not, you'll need to research the behaviour of env preservation for your Linux.

**Comment by JounQin** [comment]
Thanks @Bo98 , that works to me now!

**Comment by JounQin** [comment]
I also find an option `--sudo-service-user`, but it only works on macOS, hope it will be supported on Linux in the future.

**Comment by MikeMcQuaid** [comment]
@JounQin You or someone else will need to make a PR for it before that will happen, sorry!

**Comment by JounQin** [comment]
> @JounQin You or someone else will need to make a PR for it before that will happen, sorry!

Understand, I hope I'll be able to do that after I learn more deeper about homebrew's codebase.

**Comment by JounQin** [comment]
It seems I cann't stop the service now. 😂

```sh
brew service stop v2raya
Error: Service `v2raya` is started as `root`. Try:
  sudo brew services stop v2raya
```

```sh
sudo --preserve-env=HOME brew service stop v2raya
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

**Comment by Bo98** [comment]
Should be `brew services` rather than `brew service`

I didn't know `brew service` even worked - I guess there's an alias somewhere.

**Comment by JounQin** [comment]
@Bo98 Yep, that's my custom alias, and I think the alias should work as same as `services`. It seems like a bug to me.

**Comment by Bo98** [comment]
Yeah I think homebrew-aliases isn't supported under sudo yet.

**Comment by JounQin** [comment]
...I have no idea what's happening...

```sh
sudo --preserve-env=HOME brew services stop v2raya
Error: Service `v2raya` is started as `root`. Try:
  brew services stop v2raya
```

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid Do you think this is a bug that needs to be fixed?

no

**Comment by Bo98** [comment]
> Do you think this is a bug that needs to be fixed?

It's likely very difficult to fix with the way homebrew-aliases work. It just installs shell scripts into your PATH.

> And this, the error message is wrong, v2raya is not started as root

Yeah, looking at the code it might be a visual bug, yes.
