### ISSUE TITLE
Non-standard install location broken on Sierra 10.12.1

### ISSUE THREAD

**Issue by zachwalton** [Homebrew/brew#1624]
When upgrading to Sierra 10.12.1, a previously working `~/.homebrew` installation seems to break.

Specifically, `brew link` now seems to be using a prefix of `/usr/local` even though it was previously using `/Users/$(whoami)/.homebrew`.  This persists even after reinstalling:

```
15:39:37-zachwalton ~ 💫  git clone https://github.com/Homebrew/brew ~/.homebrew
Cloning into '/Users/zachwalton/.homebrew'...
remote: Counting objects: 73590, done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 73590 (delta 2224), reused 2162 (delta 2162), pack-reused 71292
Receiving objects: 100% (73590/73590), 17.59 MiB | 3.35 MiB/s, done.
Resolving deltas: 100% (52538/52538), done.
Checking connectivity... done.
15:42:37-zachwalton ~ 💫   ~/.homebrew/bin/brew --version
Homebrew 1.1.2-31-g29aa1c8
Homebrew/homebrew-core (git revision 6dba9; last commit 2016-12-05)
15:39:49-zachwalton ~ 💫  ~/.homebrew/bin/brew --prefix
/usr/local
```

This causes new packages and symlinks (via `brew link`) to be installed to `/usr/local`.

From the docs, it seems that this is "magically" set by the install location. Am I missing something or is this broken?

**Comment by zachwalton** [comment]
Somehow this fixed it:

```
15:48:43-zachwalton ~ 💫 ~/.homebrew/bin/brew --prefix
/usr/local
15:48:46-zachwalton ~ 💫 find /usr/local/bin/ -type l | xargs rm
15:48:48-zachwalton ~ 💫 ~/.homebrew/bin/brew --prefix
/Users/zachwalton/.homebrew
```

Any idea what symlink in `/usr/local/bin` could cause this behavior?

Anyway, I'm good now. Leaving this open in case you want to investigate but feel free to close if not.

**Comment by MikeMcQuaid** [comment]
> Any idea what symlink in /usr/local/bin could cause this behavior?

`/usr/local/bin/brew` would cause this behaviour as it takes that to mean you're able to write to `/usr/local` and therefore would rather use `/usr/local/Cellar` and get access to our binary packages.
