### ISSUE TITLE
Properly support the rc shell

### ISSUE THREAD

**Issue by dertuxmalwieder** [Homebrew/brew#16264]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I've been using [`rc`](https://github.com/rakitzis/rc), a version of the V10 UNIX (and Plan 9) standard shell (see [Wikipedia](https://en.wikipedia.org/wiki/Rc)), with Homebrew for a while. It works well, but the one thing that bothers me is that the profile output won't work.

Example:

```
; brew info ncurses
...
For compilers to find ncurses you may need to set:

For pkg-config to find ncurses you may need to set:
```

This is rather insufficient, but quite easy to fix. In fact, I fixed it on my machine already (will contribute a PR right after typing this):

```
; brew info ncurses
...
For compilers to find ncurses you may need to set:
  LDFLAGS=(-L/opt/homebrew/opt/ncurses/lib)
  CPPFLAGS=(-I/opt/homebrew/opt/ncurses/include)

For pkg-config to find ncurses you may need to set:
  PKG_CONFIG_PATH=(/opt/homebrew/opt/ncurses/lib/pkgconfig)
```

### What is the motivation for the feature?

See above.

### How will the feature be relevant to at least 90% of Homebrew users?

It probably will not, but I'd *guess* that most supported shells are neither, and I already did (most of?) the work for you. :-)

### What alternatives to the feature have been considered?

Using a different, probably less standard shell (won't happen).

**Comment by MikeMcQuaid** [comment]
> This is rather insufficient, but quite easy to fix. In fact, I fixed it on my machine already (will contribute a PR right after typing this):

Closing this just because how we work on this project is to not require issues to be open when there's a PR opened immediately. Thanks, no worries and just a heads up for next time! ❤️
