### ISSUE TITLE
Use `/usr/bin/env bash` as `brew`'s shebang instead of `/bin/bash`

### ISSUE THREAD

**Issue by ypsah** [Homebrew/brew#16276]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

```patch
diff --git a/bin/brew b/bin/brew
index 34b2e5b3e..936115753 100755
--- a/bin/brew
+++ b/bin/brew
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 set -u
 
 # Fail fast with concise message when not using bash
```

### What is the motivation for the feature?

Hi, as you probably know `bash` on MacOS is stuck at version 3 for licensing reasons, but `brew` conveniently provides a way to get an up-to-date version. One can then tweak their `PATH` environment variable to give priority to the more up-to-date version of `bash`.

However, `brew`, by using `/bin/bash` as its shebang will keep running the built-in version of `bash`, which -- provided you use recent features of `bash` in an exported function -- can lead to annoying error messages getting logged all around the place when invoking `brew`.

### How will the feature be relevant to at least 90% of Homebrew users?

Not going to pretend 90% of `brew`'s users are using recent features of `bash`. :sweat:
But hopefully this is a small and simple enough change that it can be made. :crossed_fingers:

I personally `export` a function that makes use of the `-v` test operator ([doc](https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html)).

### What alternatives to the feature have been considered?

I have tried overwriting `/bin/bash` with a symlink to `$(brew --prefix)/bin/bash`, but unfortunately, that's either not allowed in recent versions of MacOS, or not allowed by my corporate administrator.

**Comment by MikeMcQuaid** [comment]
We're not doing this, sorry, the potential for breakage is non-zero and the benefit to users is zero.

I don't understand why the version of Bash that Homebrew uses affects you in any way, can you elaborate?

**Comment by ypsah** [comment]
> I don't understand why the version of Bash that Homebrew uses affects you in any way, can you elaborate?

Of course, let's say I'm running bash version 5, and export the following function:

```bash
foo() { [[ -v SOME_SHELL_VARIABLE ]] && echo "do something"; }

export -f foo
```

Now, every time I run `brew` (which itself runs `/bin/bash`, version 3 on MacOS, which doesn't support the `-v` test operator), I get the following error message logged in my terminal:

```
/bin/bash: foo: line 0: conditional binary operator expected
/bin/bash: foo: line 0: syntax error near `SOME_SHELL_VARIABLE'
/bin/bash: foo: line 0: `foo () {   [[ -v SOME_SHELL_VARIABLE ]] && echo "do something"'
/bin/bash: error importing function definition for `foo'
```

For the record, using `#!/usr/bin/env bash` appears to be considered good practice by the stackoverflow community: https://stackoverflow.com/a/10383546.

**Comment by ypsah** [comment]
Well, arguably, the second most upvoted answer on this post describes how `/usr/bin/env` may not exist on `SunOS 4`, and the wikipedia link in the answer I shared also points out `OpenServer 5.0.6` and `Unicos 9.0.2` use `/bin/env` instead, so I understand the reluctance to make the change.

**Comment by MikeMcQuaid** [comment]
@ypsah seems like best workaround for you for now is not to export these functions when calling `brew`.

We'll review a pull request if there's a way to handle this somehow in `bin/brew` (e.g. mass unexport functions or something).



> For the record, using `#!/usr/bin/env bash` appears to be considered good practice by the stackoverflow community: https://stackoverflow.com/a/10383546.

They are not speaking to our context: a cross-platform package manager.

**Comment by MikeMcQuaid** [comment]
> I'm not sure I understand, to be cross-platform, must you not aim for portability?

No. We specifically want to control the versions of Bash we use so we aren't having to deal with whatever random version the person happens to have in their `PATH` that day.



> 2\. the version of `bash` that `/usr/bin/env` picks is so ancient (or so novel) that it does not support some feature that `bin/brew` relies on.

This is the concern. Not just ancient or novel but: a version installed from Homebrew which is broken which in turn then makes it impossible to run Homebrew any more.



> You can consider this my last attempt at melting your resolve.

Sorry, not going to happen. Appreciate the polite, kind, grateful and reasonable tone throughout this issue though ❤️
