### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by Pszek** [Homebrew/brew#1627]
@MikeMcQuaid 
Ad #1626 

First of all, if I insulted you or people behind this great (still won't change opinion on that) extension, please accept my apologies. I consider words meaningless, so any time (but soon to be sure I will be still in that city) you will be in Warsaw let me know and I will buy you a beer (or lemonade if you avoid alcohol). Also could send you a bottle (give details where to ship on priv).

Secondly, the message you quoted existed only for 10s. I didn't want to post it in the first place, just typed it to let off steam. Unfortunately, I use Wasavi Chrome addon, which is great, but this time instead of the new line (not accustomed that in issue message one can just press 'enter' for that') I 'summoned' (wrong shortcut) it and posted a message.

Maybe I wasn't clear and forgot to mention it - every brew command gives me that result. I assumed, that it would be obvious that I followed these steps, if I hadn't posted things like "my X-code is up to date".

**Comment by MikeMcQuaid** [comment]
> First of all, if I insulted you or people behind this great (still won't change opinion on that) extension, please accept my apologies.

Your apologies are very much accepted and genuinely appreciated.

> Secondly, the message you quoted existed only for 10s.

Sorry about that, I didn't realise you had deleted it for that reason.

Let's continue the issue discussion in #1626, I've reopened it.
