### ISSUE TITLE
mc recipe does not symlink libexec wrapper scripts

### ISSUE THREAD

**Issue by ssbarnea** [Homebrew/brew#1631]
I discovered that when the mc recipe is installed only the bin executables are symlinked and due to this the wrapper utility scripts are not available in a generic location.

Due to this people cannot use them using an alias pattern like `alias mc='. /usr/libexec/mc/mc-wrapper.sh'`. At this moment the wrappers are installed at a location that looks like `/usr/local/Cellar/midnight-commander/4.8.18/libexec/mc/mc-wrapper.sh` which means that any upgrade of mc will break the aliases.

I tried to fix my bug myself but I am not aware about how the `ln_s` is supposed to be called. I tried `brew edit mc`, added `Dir["#{libexec}/bin/*.sh"].each { |f| ln_s f, bin }` at the end of install block, done a `brew bottle mc && brew reinstall mc` but this did not create the files so I am missing something.

References:
* http://ptspts.blogspot.co.uk/2010/01/how-to-make-midnight-commander-exit-to.html
* http://klimer.eu/2015/05/01/use-midnight-commander-like-a-pro/

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-core#7639
