### ISSUE TITLE
Cannot untap a tap which includes casks that are invalid

### ISSUE THREAD

**Issue by Moisan** [Homebrew/brew#16321]
### `brew doctor` output

```shell
➜  ~ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.25-27-g23f6ad6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 23f6ad6d100c4074ab11d8340fc5800ead757417
Last commit: 59 minutes ago
Core tap JSON: 12 Dec 19:01 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: mvim
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.43.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.2-x86_64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.0.1
```

### What were you trying to do (and why)?

I was trying to untap `AdoptOpenJDK/openjdk` since it's deprecated.

Also calling `brew remove` for any formula (including formulae not in that tap) leads to the same error.

### What happened (include all command output)?

➜  ~ brew untap AdoptOpenJDK/openjdk
Error: Cask 'adoptopenjdk11' definition is invalid: 'appcast' stanza failed with: Calling the `appcast` stanza is disabled! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk11.rb:9
  
  (sqlite is not a formula in that tap)
  
 ➜  ~ brew remove sqlite
Error: Cask 'adoptopenjdk11' definition is invalid: 'appcast' stanza failed with: Calling the `appcast` stanza is disabled! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk11.rb:9

### What did you expect to happen?

Untap the tap without error. Also allow the user to remove other formulae without issue.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap AdoptOpenJDK/openjdk
brew untap AdoptOpenJDK/openjdk
```

The only workaround for now is to manually delete the `/usr/local/Homebrew/Library/Taps/adoptopenjdk` directory.

**Comment by nathaliedd** [comment]
Hello, I got this issue with this command as well:
`brew install --cask adoptopenjdk11`

**Comment by Bo98** [comment]
AdoptOpenJDK was deprecated over a year ago. Please follow the commands under the depreacation notice on the upstream README: https://github.com/AdoptOpenJDK/homebrew-openjdk/blob/master/README.md

**Comment by niuguodong** [comment]
brew update-reset
