### ISSUE TITLE
add `brew install --local` flag

### ISSUE THREAD

**Issue by 0xdevalias** [Homebrew/brew#16325]
Opening this as an issue as it sounds like a good idea, and as best I could tell from a quick search, I don't think it has been done yet/discussed further.

My personal interest in it is probably more focused on casks than formulae, so `--build-from-source` doesn't seem relevant to that use case.

## Proposal

> > May want to consider making an explicit `--build-from-source` always bypass the API CC @Bo98 for thoughts.
> 
> I would rather lean more towards a new flag, e.g. `--local` or whatever, that is much more explicit that the intention is to use a locally edited formula. There's a question however of how should it behave for dependencies. Should those be installed from API or from the local clone? The latter is perhaps useful in some cases, though does mean that the flag would behave differently than how all other `brew install` flags work.
> 
> _Originally posted by @Bo98 in https://github.com/Homebrew/homebrew-core/issues/138060#issuecomment-1658291638_

> > I would rather lean more towards a new flag, e.g. `--local` or whatever, that is much more explicit that the intention is to use a locally edited formula.
> 
> Great idea 👍🏻
> 
> > There's a question however of how should it behave for dependencies. Should those be installed from API or from the local clone?
> 
> Hmm, good question. Feels like probably always using the local clone is better for consistency and because it's needed some of the time?
> 
> _Originally posted by @MikeMcQuaid in https://github.com/Homebrew/homebrew-core/issues/138060#issuecomment-1658409445_

## Workaround / Alternatives

I'm not sure if this is the canonical way, but as a workaround, currently when creating a new formula I just use a direct path to the file; eg.

```shell
brew install --cask $(brew --repository homebrew/cask)/Casks/f/foo.rb
```

This works ok, but is a little annoying/verbose in having to use the full path, or switch to the Casks directory first. It also seems to not play nice with the autocompletions, so I can't just tab my way to completing the filename/path.

- https://github.com/Homebrew/brew/tree/master/completions
  - https://github.com/Homebrew/brew/blob/master/completions/zsh/_brew#L1084-L1140

---

If the `--local` isn't a good option, then perhaps drawing attention to `HOMEBREW_NO_INSTALL_FROM_API=1` (if that's the canonical way) in the text for `brew install -h` would be useful.

It was added to the pull request template for `homebrew-core` in:

- https://github.com/Homebrew/homebrew-core/pull/138060

And there are already other env vars described in the `brew install -h` text:

https://github.com/Homebrew/brew/blob/de224796beb4e2aca73b7ad4a2a9b77f62ab5626/Library/Homebrew/cmd/install.rb#L19-L31

**Comment by Bo98** [comment]
I'd like to discourage `HOMEBREW_NO_INSTALL_FROM_API=1` so I'm still hoping to do this, yeah.

**Comment by MikeMcQuaid** [comment]
Agreed this is a desirable feature, thanks for opening @0xdevalias.

@Bo98 I feel like `--local` should, ideally, just use the named formula from the tap and dependencies from the API (maybe unless they are changed in `git` but that probably starts to get overly complex).

**Comment by 0xdevalias** [comment]
> should, ideally, just use the named formula from the tap and dependencies from the API

Maybe `--local` could do this part; which would handle a majority of needs/cases in the simplest way.

> (maybe unless they are changed in git but that probably starts to get overly complex).

And then some other flag used with it (`--local-with-deps`) could imply this part; for those more nuanced situations where multiple deps are being changed at once.

I also wouldn't be opposed to this only happening if they were changed as well, as 99.9% of the time I'm not going to have local differences unless I'm specifically working on them.

As for how to detect that easily/cleanly/with minimal code.. _shrugs_

**Comment by MikeMcQuaid** [comment]
> > should, ideally, just use the named formula from the tap and dependencies from the API
> 
> Maybe `--local` could do this part; which would handle a majority of needs/cases in the simplest way.

Agreed 👍🏻

**Comment by 0xdevalias** [comment]
If `--local` will have the same effect/semantics as `--build-from-source`; does that make them somewhat duplicates?

I like `--build-from-source` as it's very semantic/obvious, but it doesn't make sense for casks.

I like `--local` for it's simplicity.

Perhaps something could be added to `--build-from-source` that says it implies `--local` or similar to remove ambiguity?

Similar to how the docs for `brew audit --new` say that it implies `--strict` and `--online`

**Comment by Bo98** [comment]
I didn't mean a literal alias. I was talking more in terms of how things like `--build-from-source` don't build dependencies from source - only the formula you selected.

But it will still behave similarly yes. For formulae, `--local` will basically be a scoped no-API load and then it will imply `--build-from-source` to the internal installer. Casks will just be the initial no-API load and that's it as the installer doesn't need to do anything differently beyond that.

**Comment by 0xdevalias** [comment]
> For formulae, `--local` will basically be a scoped no-API load and then it will imply `--build-from-source` to the internal installer.

That's the part that I think should be explicitly mentioned in the `--help` docs (similar to what `build install --new` does); so that people know that there is no reason to pass `--local --build-from-source` for example.
