### ISSUE TITLE
rubocop/cask: sort `zap` stanza's trash array alphabetically

### ISSUE THREAD

**Issue by bevanjkay** [Homebrew/brew#16323]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Currently `zap` stanzas in Casks are being sorted manually so that they are alphabetical.

In terms of the ordering I'm not sure how symbol characters are ordered but we generally do the following;

```
zap trash: [
  "/Library/a....",
  "~/.dotfile/...",
  "~/Library/a..."
]
```

https://github.com/Homebrew/homebrew-cask/commit/152dc18da6ac1f2ef377906f70074695582f4f9c
https://github.com/Homebrew/homebrew-cask/commit/859069a80ff0451dced532a318d9b4111fcf0ab2
https://github.com/Homebrew/homebrew-cask/commit/6cfeb2e407e122ce301415019461334dc8b2f5fa

### What is the motivation for the feature?

It makes `zap` stanzas easier to parse when updating as the individual lines/files are easier to locate.

### How will the feature be relevant to at least 90% of Homebrew users?

It would be useful to contributors / maintainers, but not general Homebrew users.

### What alternatives to the feature have been considered?

Currently, this process is completed manually when `zap` stanzas are added/updated.

**Comment by issyl0** [comment]
I'll take this, something to do over the Christmas break!

**Comment by bevanjkay** [comment]
@issyl0 we should likely apply this to other arrays in cask. But I'll have to have a think about which ones and get back. Others may have some thoughts too. But it's mainly the arrays in the uninstall and zap stanzas.

**Comment by bevanjkay** [comment]
An addition to this, can make a new issue if preferred would be that arrays with one item are turned into a string instead.
