### ISSUE TITLE
Cask 'adoptopenjdk-jre' definition is invalid

### ISSUE THREAD

**Issue by Rockin4Life33** [Homebrew/brew#16343]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  node@14
  node@16
  openssl@1.1
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.25-57-gdc3daf7
ORIGIN: https://github.com/Homebrew/brew
HEAD: dc3daf77a527b5c9da85d90c62f14f57ff6a339e
Last commit: 8 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9bf97a044d99a76ff898c7b8e318124baa262440
Core tap last commit: 23 minutes ago
Core tap branch: master
Core tap JSON: 15 Dec 16:41 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.43.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.2-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.1
```

### What were you trying to do (and why)?

I wanna install a new Cask; first I need to know if it is out there. 

❯ `brew search -v --eval-all --desc vscode`

### What happened (include all command output)?

==> Formulae
code-server: Access VS Code through the browser
dockerfile-language-server: Language server for Dockerfiles powered by Node, TypeScript, and VSCode
vsce: Tool for packaging, publishing and managing VS Code extensions
vscode-langservers-extracted: Language servers for HTML, CSS, JavaScript, and JSON extracted from vscode

==> Casks
Error: Cask 'adoptopenjdk-jre' definition is invalid: 'appcast' stanza failed with: Calling the `appcast` stanza is disabled! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk-jre.rb:9

### What did you expect to happen?

That there would not be an error and it would list out any Casks that match my search criteria.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1) `brew search -v --eval-all --desc vscode`
  — This will cause the error noted in the body of the issue description.
2) `brew desc -sv --eval-all vscode`
  — This will cause the error noted in the body of the issue description.
2) `brew search -v vscode`
  — This will run successfully and return a single CASK, `vscodium`.
Run `brew search` or `brew desc` to reproduce. I have only seen the error under the `CASK` list and not the `FORMULA` list.
```

**Comment by MikeMcQuaid** [comment]
> Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
