### ISSUE TITLE
"undefined method `split' for nil:NilClass" thrown by gpg.rb

### ISSUE THREAD

**Issue by jarcane** [Homebrew/brew#1635]
Found on: MacOS Version 10.10.5 (14F1713)
MacBook Pro (15-inch, Late 2011)

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step? 
- [X] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug reports:

Attempted to install exercism through brew and got a giant stack trace [(see Gist)](https://gist.github.com/jarcane/bddf673c29866ff4a4d1379bc4698495) and have continued to get said error for all formulas, and nearly all commands except, most of the time, `brew update`, and some flags on brew itself. 

`brew update` returns "Already up-to-date", except when it fails and then I get the same stack trace again. A complete uninstall and reinstall restored function long enough for me to reinstall fish, then promptly failed again. `brew doctor` fails with same error. `brew config` fails. Following the instructions on the template and resetting the git repo for `/usr/local/Homebrew` has no effect. Installing gpg2 manually had no effect. 

I am as a result unable to install any formulas.

**Comment by jawshooah** [comment]
So [this](https://github.com/Homebrew/brew/blob/54d18cee17a7af49b5858dd752bf2eda59014472/Library/Homebrew/utils.rb#L302-L313) is the problematic method. It's called from `Gpg.find_gpg` without a second argument, so `path` is set to `ENV["PATH"]` by default. This must be getting set to `nil` elsewhere, but I can't figure out how...
