### ISSUE TITLE
Cannot run brew cleanup

### ISSUE THREAD

**Issue by Tommy0046** [Homebrew/brew#16361]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  packer
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.0-11-g38c5e52
ORIGIN: https://github.com/Homebrew/brew
HEAD: 38c5e52a6d243b5bf87792a88c082cb2be7e68d3
Last commit: 5 minutes ago
Core tap JSON: 19 Dec 12:06 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.1-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I just tried to run brew update, it tried to run brew cleanup and that failed, but there seems to be a problem with "youtube-music" cask pointing to wrong github URL, which made my brew stuck. I do not need this cask anymore, so I have tried to uninstall that with "brew uninstall --force --ignore-dependencies youtube-music" but that ends with the same error.

### What happened (include all command output)?

~ brew upgrade
==> `brew cleanup` has not been run in the last 30 days, running now...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Error: No such file or directory @ rb_sysopen - https://api.github.com/repos/th-ch/youtube-music/releases/latest

~  brew cleanup
Error: No such file or directory @ rb_sysopen - https://api.github.com/repos/th-ch/youtube-music/releases/latest

### What did you expect to happen?

Be able to install/update packages normally and/or run cleanup

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install youtube-music
brew upgrade
brew cleanup
```

**Comment by apainintheneck** [comment]
Is this a core cask or did it come from an external tap? I'm not seeing anything with that name in the search results.

```console
$ brew search youtube-music
==> Formulae
youtube-dlc

==> Casks
youtube-to-mp3                                               ytmdesktop-youtube-music
```

**Comment by cho-m** [comment]
I'm guessing that is external cask maintained by upstream project, i.e.
- Originally https://github.com/th-ch/youtube-music/pull/1357
- Now at https://github.com/th-ch/homebrew-youtube-music

Related to https://github.com/th-ch/youtube-music/pull/1496

I believe Cask file broke when we updated to Ruby 3.

May need to try uninstalling Cask (not too sure if `--force` can handle this or needs manual deletion) and adding upstream's new tap.

**Comment by MikeMcQuaid** [comment]
The fix here is probably turning this error into a warning so one broken cask doesn't prevent `brew cleanup` from being run at all.

**Comment by MikeMcQuaid** [comment]
(this will involved catching and printing but not re-raising exceptions)

**Comment by MikeMcQuaid** [comment]
Closing, it's been most of a year and no-one else seems to be either hitting or fixing this.
