### ISSUE TITLE
Search is inconsistent, can't use `brew search` to find a cask that is available via `brew info`

### ISSUE THREAD

**Issue by manuel-koch** [Homebrew/brew#16378]
### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 4.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ff899e5b3ff6731208564ef502db237e2627e8ba
Last commit: 3 days ago
Core tap JSON: 21 Dec 12:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 11
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 11-core 64-bit dunno
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I want to search for a given functionality ( in my case a music library ).
I know a program ( quodlibet ) that is available via brew.
I tried to search for something similar to discover similar programs, during the search I noticed that the search results are inconsistent, namely I can't find an existing cask by a given (correct) description. 

### What happened (include all command output)?

`brew search` didn't find description of existing cask.

```shell
# check that quodlibet actually exists, notice the description
$ brew info quodlibet
==> quodlibet: 4.4.0
https://quodlibet.readthedocs.io/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/q/quodlibet.rb
==> Name
Quod Libet
==> Description
Music player and music library manager
==> Artifacts
QuodLibet.app (App)
==> Analytics
install: 24 (30 days), 84 (90 days), 158 (365 days)


# now try to search for something similar containing the description snippet "library"
# and check that "quodlibet" is in the results
$ brew search --eval-all --desc library | grep -i libet
libetpan: Portable mail library handling several protocols

# quodlibet is not found !?
```

### What did you expect to happen?

`brew search` can actually find all formula/cask that match the criteria and are available in brew.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
see above
```

**Comment by MikeMcQuaid** [comment]
> ```shell
> $ brew search --eval-all --desc library | grep -i libet
> ```

I get this output:
```
libetpan: Portable mail library handling several protocols
quodlibet: (Quod Libet) Music player and music library manager
```

so not reproducible here.

**Comment by apainintheneck** [comment]
I get the same results as @MikeMcQuaid locally. The only thing that I can think of is that maybe the cask descriptions cache is outdated somehow.

@manuel-koch Can you run this command locally and share the results?

```console
$ grep -Eio '[^"]*libet[^"]*' "$(brew --cache)/cask_descriptions.json"
quodlibet
Quod Libet
```

**Comment by Bo98** [comment]
Cask description searching doesn't currently work without the cask tap installed as `Cask.all` uses `cask_files`

**Comment by manuel-koch** [comment]
I tried
```shell
$ grep -Eio '[^"]*libet[^"]*' "$(brew --cache)/cask_descriptions.json"
grep: /Users/manuel/Library/Caches/Homebrew/cask_descriptions.json: No such file or directory
```
Not sure if this actual proves something, I've installed / uninstalled and pruned stuff since I have reported the issue:
```shell
$ history 50
....
  373* brew info quodlibet
  374* brew search --help
  375* brew search --eval-all --desc library | grep libet
  376* man grep
  377* brew search --eval-all --desc library
  378* brew install quodlibet
....
  396* brew uninstall quodlibet
....
  398* brew info audicious
  399* brew info audacious
  400* brew install audacious
  401* rehash
  402* audacious
....
  404* brew uninstall --help
  405* brew uninstall audacious
  406* brew cleanup
  407* brew cleanup --help
  408* brew cleanup --prune=all
  409* brew search --eval-all --desc library | grep -i libet
....
  415  grep -Eio '[^"]*libet[^"]*' "$(brew --cache)/cask_descriptions.json"
```

**Comment by apainintheneck** [comment]
> Cask description searching doesn't currently work without the cask tap installed as `Cask.all` uses `cask_files`

Good catch @Bo98.

That sounds like the bug we fixed with formulae 6 months ago in https://github.com/Homebrew/brew/pull/15606 and we should probably just make the same type of change here. There was some discussion about removing `Formula.all` at the time and `Cask::Cask.all` maybe should receive the same treatment but that sounds like more of a refactor that's outside the scope of this bug fix.

It seems to affect a few commands and would definitely cause descriptions search not to work if the core cask tap is not tapped which should be the default nowadays.

```console
$ git grep -Fn 'Cask::Cask.all'
Library/Homebrew/cmd/deps.rb:134:      puts_deps sorted_dependents(Formula.all(eval_all: args.eval_all?) + Cask::Cask.all), recursive: recursive,
Library/Homebrew/cmd/info.rb:210:        [Formula.all(eval_all: args.eval_all?).sort, Cask::Cask.all.sort_by(&:full_name)]
Library/Homebrew/cmd/uses.rb:122:        deps += args.installed? ? Cask::Caskroom.casks : Cask::Cask.all
Library/Homebrew/description_cache_store.rb:103:    Cask::Cask.all.each { |c| update!(c.full_name, [c.name.join(", "), c.desc.presence]) }
Library/Homebrew/dev-cmd/audit.rb:148:        [Formula.all(eval_all: args.eval_all?), Cask::Cask.all]
Library/Homebrew/dev-cmd/livecheck.rb:90:        casks = args.formula? ? [] : Cask::Cask.all
```

I'll open a PR to fix it.
