### ISSUE TITLE
Rosetta 2 not detected by brew config

### ISSUE THREAD

**Issue by M-Arnone** [Homebrew/brew#16381]
### `brew doctor` output

```shell
mattOS:~ matteo$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  android-sdk
mattOS:~ matteo$
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
mattOS:~ matteo$ brew config
HOMEBREW_VERSION: 4.2.0-47-g4a8d9ce
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4a8d9ce246196997451c8e54df6d467d2b25c72a
Last commit: 3 hours ago
Core tap JSON: 21 Dec 17:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.mPYECfnoEU/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0
Rosetta 2: false
mattOS:~ matteo$
```

### What were you trying to do (and why)?

.

### What happened (include all command output)?

Rosetta 2 is used by homebrew but the brew config doesn't display the attribute "Rosetta 2" at true

### What did you expect to happen?

Rosetta 2 : true

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew config
```

**Comment by Bo98** [comment]
`/opt/homebrew` is arm64 only so you can't be running under Rosetta 2. Rosetta 2 would use the x86_64 Homebrew install directory of `/usr/local`.
