### ISSUE TITLE
bug: permission denied when install node

### ISSUE THREAD

**Issue by qifuren1985** [Homebrew/brew#1638]
I already created a symbolic link from  /usr/local/lib/node_modules to /Volumes/HD1/ln_src/node_modules with ln command. when I use brew install node, it will failed in postinstall phase.

brew postinstall -v node
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161209-44801-jgdk9r.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb -v
cp -r /usr/local/Cellar/node/7.2.1/libexec/npm/lib/node_modules/npm /usr/local/lib/node_modules/npm
Error: Operation not permitted - /usr/local/lib/node_modules/npm/npm/.github/issue_template.md

The reason is the folder /Volumes/HD1/ln_src/ not in sandbox allowed writable folder. When I add /Volumes/HD1/ln_src/ to /usr/local/Homebrew/Library/Homebrew/sandbox.rb, the bug was fixed.

So, we need a config to add sandbox allow write folder?

**Comment by MikeMcQuaid** [comment]
> I already created a symbolic link from /usr/local/lib/node_modules to /Volumes/HD1/ln_src/node_modules with ln command. when I use brew install node, it will failed in postinstall phase.

Sorry, we don't support symlinking parts of the prefix in this way.
