### ISSUE TITLE
Homebrew Installation (from scratch) on case sensitive FS 

### ISSUE THREAD

**Issue by m0ll3art** [Homebrew/brew#1639]
Hi again 

Related to issue #1430.

So discussing an installation from scratch : on case-insensitive FS it seems to be ok no complain BUT on case-sensitive filesystem, it seems that some brew internals are having troubles. Next an excerpt from a fresh installation 

``` bash 
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.2      -> 1.1.2
HEAD is now at 276d009 Merge pull request #1615 from zachwhaley/fish_functions
fatal: Cannot update paths and switch to branch 'stable' at the same time.
Did you intend to checkout 'refs/tags/1.1.2' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.1.2
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 3782, done.
remote: Compressing objects: 100% (3665/3665), done.
remote: Total 3782 (delta 18), reused 308 (delta 5), pack-reused 0
Receiving objects: 100% (3782/3782), 3.02 MiB | 1.92 MiB/s, done.
```
then `brew --version` output 

```
Homebrew >1.1.0 (no git repository)
Homebrew/homebrew-core (git revision 8b24; last commit 2016-12-09)
```  

whereas the installation on case-insensitive FS does not show any issue  and `brew --version` 

```
Homebrew 1.1.2 
Homebrew/homebrew-core (git revision 8b24; last commit 2016-12-09)
```  

So may I suggest that you warn the guys among us that `brew` is not really supported on **case-sensitive** filesystem and to change 

> Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

since problems are expected . @MikeMcQuaid I'm not reopening the discussion here,  only my 50cents contribution to installation on case-sensitive FS. For me case-sensitive should be the default FS and not the case-insensitive one, since Mac OS is based on Unix (Nextstep) under the hood (BeOS was also an option) ..

**Comment by MikeMcQuaid** [comment]
> Related to issue #1430.

Please continue discussion there, thanks.
