### ISSUE TITLE
Please remove the google analytics part... you should ask the users not spy on them...

### ISSUE THREAD

**Issue by Tristan79** [Homebrew/brew#164]
Also one little line of code to inform the user that it is being spied on...
Really? Ever tried asking the user? Seems the be hard in IT land asking the user...

Vommit...

Please remove asap.

**Comment by DomT4** [comment]
You have the choice to opt-out, which you are more than welcome to do so if you aren't comfortable having your usage data anonymously collected to help the project. Users are informed on both initial installation of Homebrew and the first `brew update` they run after the feature was introduced; no analytics are sent anywhere until the user sees that message.

Thanks for the Issue.
