### ISSUE TITLE
Unable to install portable ruby 3.1.4 (2020 M1 montery macbook)

### ISSUE THREAD

**Issue by epicgamermanns** [Homebrew/brew#16409]
### `brew doctor` output

```shell
"Error: Failed to install ruby 3.1.4!
Error: Failed to install Homebrew Portable Ruby (and your system version is too old)!"
```

### Verification

- [ ] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
Error: Failed to install ruby 3.1.4!
Error: Failed to install Homebrew Portable Ruby (and your system version is too old)!
```

### What were you trying to do (and why)?

I was trying to install yt-dlp

### What happened (include all command output)?

i ran "brew install yt-dlp" it did its thing then i get "Error: Failed to install ruby 3.1.4!
Error: Failed to install Homebrew Portable Ruby (and your system version is too old)!"

### What did you expect to happen?

i expected it to work smoothly and for yt-dlp to install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
not sure it just happened 1 day
```

**Comment by MikeMcQuaid** [comment]
Need you to provide the full output please.

**Comment by epicgamermanns** [comment]
brew doctor= "==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:d783cbeb6e6ef0d71c0b442317b54554370decd6fac66bf2d4938c07a63f67be
Already downloaded: /Users/stredw8504/Library/Caches/Homebrew/portable-ruby-3.1.4.arm64_big_sur.bottle.tar.gz
==> Pouring portable-ruby-3.1.4.arm64_big_sur.bottle.tar.gz
/opt/homebrew/Library/Homebrew/cmd/vendor-install.sh: line 236: ./3.1.4/bin/ruby: Permission denied
Error: Failed to install ruby 3.1.4!
Error: Failed to install Homebrew Portable Ruby (and your system version is too old)!"



brew config = "==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:d783cbeb6e6ef0d71c0b442317b54554370decd6fac66bf2d4938c07a63f67be
Already downloaded: /Users/stredw8504/Library/Caches/Homebrew/portable-ruby-3.1.4.arm64_big_sur.bottle.tar.gz
==> Pouring portable-ruby-3.1.4.arm64_big_sur.bottle.tar.gz
/opt/homebrew/Library/Homebrew/cmd/vendor-install.sh: line 236: ./3.1.4/bin/ruby: Permission denied
Error: Failed to install ruby 3.1.4!
Error: Failed to install Homebrew Portable Ruby (and your system version is too old)!"


and brew update = "==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:d783cbeb6e6ef0d71c0b442317b54554370decd6fac66bf2d4938c07a63f67be
Already downloaded: /Users/stredw8504/Library/Caches/Homebrew/portable-ruby-3.1.4.arm64_big_sur.bottle.tar.gz
==> Pouring portable-ruby-3.1.4.arm64_big_sur.bottle.tar.gz
/opt/homebrew/Library/Homebrew/cmd/vendor-install.sh: line 236: ./3.1.4/bin/ruby: Permission denied
Error: Failed to install ruby 3.1.4!
Error: Failed to install Homebrew Portable Ruby (and your system version is too old)!"

**Comment by MikeMcQuaid** [comment]
You have to resolve this permission error yourself. This is not a bug with Homebrew.
