### ISSUE TITLE
Upgrading pip3 package manager using --upgrade symlinks pip to wrong python bin

### ISSUE THREAD

**Issue by GrayedFox** [Homebrew/brew#1640]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug report:

Using brew to manage multiple python versions, the pip package manager bundled with python3 will upgrade the package manager attached to python. This results in the python package manager that is supposed to be bundled with python actually installing python 3.5 packages. Please check the output of my console for reproduction steps as well as proof of error(?).

Brew doctor reports "Your system is ready to brew".

Brew config:

```
HOMEBREW_VERSION: 1.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f529dae1043639058130092cf35e68d18907cb8
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dd816a7963c8913b14cea29590fa0e25aacf4156
Core tap last commit: 77 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112
macOS: 10.12.1-x86_64
Xcode: 8.1
CLT: N/A
X11: N/A
```

```
$ pip install pip
Requirement already satisfied (use --upgrade to upgrade): pip in /usr/local/lib/python2.7/site-packages
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ pip install --upgrade pip
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-9.0.1
$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
$ pip3 install pip
Requirement already satisfied (use --upgrade to upgrade): pip in /usr/local/lib/python3.5/site-packages
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ pip3 install --upgrade pip
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-9.0.1
$ pip --version
pip 9.0.1 from /usr/local/lib/python3.5/site-packages (python 3.5)
$ pip3 --version
pip 9.0.1 from /usr/local/lib/python3.5/site-packages (python 3.5)
```

### Expected Behaviour
When updating the pip3 package manager bundled with the python3 brew, `pip3 install --upgrade pip` should only upgrade the pip3 package manager linked to python 3.5, and not do anything naughty to pip.

### Actual Behaviour
See above

**Comment by MikeMcQuaid** [comment]
CC @tdsmith as I'm out my depth here.

**Comment by GrayedFox** [comment]
I'm not quite sure if this belongs in the homebrew core repo... I apologise if it does, will move it over if told :)

**Comment by MikeMcQuaid** [comment]
> I'm not quite sure if this belongs in the homebrew core repo... I apologise if it does, will move it over if told :)

Yeh, I think it does. Can you CC @tdsmith when you move it over? Thanks!

**Comment by tdsmith** [comment]
This is a pip behavior we can't change; there are open tickets against pip to provide configuration for this. You can always run `python -m pip` to get a version matched pip.

**Comment by MikeMcQuaid** [comment]
Thanks @tdsmith. You can avoid moving then @GrayedFox.

**Comment by GrayedFox** [comment]
Waaaah I just moved it and saw these. Sorry!!!!!

**Comment by GrayedFox** [comment]
@tdsmith yes I understand, probably the pip post install script which handles symlinking. Good to know that command too thanks.
