### ISSUE TITLE
`bump-formula-pr`: Multi-arch formula only updating one arch 

### ISSUE THREAD

**Issue by 5ouma** [Homebrew/brew#16432]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.2-18-gdcd267b
ORIGIN: https://github.com/Homebrew/brew
HEAD: dcd267ba4caecb253220cb02a8a2bb1c46a7a65b
Last commit: 12 hours ago
Core tap JSON: 05 Jan 04:13 UTC
Core cask tap JSON: 05 Jan 04:13 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTOREMOVE: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.43.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.7.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

### What were you trying to do (and why)?

I ran `brew bump-formula-pr` on GitHub Actions (but also on my machine) for https://github.com/5ouma/homebrew-formula/pull/2 to upgrade [`gh-dash`](https://github.com/dlvhdr/gh-dash).

### What happened (include all command output)?

Because I ran on `Ubuntu-Latest`, only Intel Linux was updated.
https://github.com/5ouma/homebrew-formula/actions/runs/7416446427/job/20181438047

### What did you expect to happen?

Not only the run machine but also other OS or architecture should be updated.

This Issue is similar to https://github.com/Homebrew/brew/issues/13713 and https://github.com/Homebrew/brew/issues/15167.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump-formula-pr --version=3.11.1 5ouma/formula/gh-dash
```

**Comment by MikeMcQuaid** [comment]
This is expected, sorry. We don't support using `on_linux do` or `if Hardware::CPU.intel?` for conditional URLs for formulae as they are expected to be built from source.

CC @Homebrew/maintainers that we may want to provide a better way of providing binary formulae in future.

**Comment by MikeMcQuaid** [comment]
@5ouma Our current best way is through:
- Homebrew Cask but that doesn't support Linux at all or CLI-only software terribly well. 
- Bottles but we don't provide a way really to just generate a bottle from an existing binary like this rather than building from source
