### ISSUE TITLE
Need help with `ln -sf`

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#1643]
There is a simple workaround for [haraldF/homebrew-kf5/kf5-ktexteditor](https://github.com/haraldF/homebrew-kf5/blob/master/kf5-ktexteditor.rb) build failure 
```ln -s  /usr/local/share/kservicetypes5/ ~/Library/Application\ Support/```
as mentioned by me [here](https://github.com/haraldF/homebrew-kf5/issues/49#issuecomment-253863118). 
The problem is that I can't replay that command in brew file. I had tried both `ln_sf` and `system "ln", "-sf",`. The both command can't find corresponding target path. The problem persists when I add `system "mkdir" "-p"` before this command.

**Comment by MikeMcQuaid** [comment]
Homebrew doesn't support writing outside of the prefix during installation. Bugs with https://github.com/haraldF/homebrew-kf5 should be discussed there.
