### ISSUE TITLE
Version comparison method for Sparkle livecheck

### ISSUE THREAD

**Issue by WangEdward** [Homebrew/brew#16444]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Brew uses `pubDate` in the appcast xml to select the newest version, which is different from Sparkle's inbuilt method ( [Test](https://github.com/sparkle-project/Sparkle/blob/2.x/Tests/SUVersionComparisonTest.m) & [Code](https://github.com/sparkle-project/Sparkle/blob/9e9830eb0f0099063cf5ccb8d48a188a122c869f/Sparkle/SUStandardVersionComparator.m) )

https://github.com/Homebrew/brew/blob/b3751bca8c4a3c76107d5aa3b75b81db93cf4bb6/Library/Homebrew/livecheck/strategy/sparkle.rb#L167-L175

### What is the motivation for the feature?

The difference in the version comparison method leads to the newest versions not being able to be parsed by Brew.

e.g. For the cask [Latest](https://github.com/Homebrew/homebrew-cask/blob/e6b5765470d117fb93dafd3709be1cccba1f65a1/Casks/l/latest.rb), in its [appcast](https://max.codes/latest/update.xml)  ([archive](https://archive.is/Z4fbz)), the older version `0.10.2` has a later pubDate than the newer version `0.10.3`. The in-app sparkle updater can recognize the `0.10.3` version, but `brew livecheck latest` returns `0.10.2`. 

### How will the feature be relevant to at least 90% of Homebrew users?

This helps users get the latest version if they use Brew to update their apps.

### What alternatives to the feature have been considered?

Comparing the versions directly with each other may be a better solution. But doing so may break the livecheck for some other casks.

**Comment by miccal** [comment]
See for example https://github.com/Homebrew/homebrew-cask/pull/159357 and https://github.com/Homebrew/homebrew-cask/pull/158372 and https://github.com/Homebrew/homebrew-cask/pull/158170 for a way to address this issue.
