### ISSUE TITLE
`brew cleanup` broke unrelated ffmpeg

### ISSUE THREAD

**Issue by llimllib** [Homebrew/brew#16474]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.3-78-g302e83e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 302e83e9aaa0a3a4c0644f43a0302a582128ed1f
Last commit: 41 minutes ago
Core tap HEAD: 26136ea4927b99f7622c472c4a39fedcc834f256
Core tap last commit: 18 minutes ago
Core tap JSON: 12 Jan 19:52 UTC
Core cask tap HEAD: 31047bd2c3ec667a7995954c2c324071c4112473
Core cask tap last commit: 41 minutes ago
Core cask tap JSON: 12 Jan 19:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: ansi
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/nvim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```

### What were you trying to do (and why)?

I installed an unrelated package (`felinks`) and homebrew broke ffmpeg again; the last time this happened was https://github.com/Homebrew/homebrew-core/issues/153177 which was fixed in #16152

homebrew ran `brew cleanup felinks` after installing felinks, and broke my ffmpeg install. It did print out, amid a giant sea of text, a warning:

```
==> Running `brew cleanup felinks`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Warning: The following dependents of upgraded formulae are outdated but will not
be upgraded because they are not bottled:
  ffmpeg
  visidata
  pixlet
```

I'm filing this issue because as a user it is very confusing and frustrating that running `brew install felinks` would break the installed `ffmpeg` package.

### What happened (include all command output)?

log: https://gist.github.com/llimllib/67cc3f6a773a89f373fb9c89a862107a

After that install, running `ffmpeg` gives:

```
$ ffmpeg --help
dyld[73202]: Library not loaded: /opt/homebrew/opt/libvmaf/lib/libvmaf.1.dylib
  Referenced from: <99C9A833-0757-369A-BD38-C9ED73839C70> /opt/homebrew/Cellar/ffmpeg/6.0-with-options_1/bin/ffmpeg
  Reason: tried: '/opt/homebrew/opt/libvmaf/lib/libvmaf.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libvmaf/lib/libvmaf.1.dylib' (no such file), '/opt/homebrew/opt/libvmaf/lib/libvmaf.1.dylib' (no such file), '/usr/local/lib/libvmaf.1.dylib' (no such file), '/usr/lib/libvmaf.1.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/libvmaf/3.0.0/lib/libvmaf.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/libvmaf/3.0.0/lib/libvmaf.1.dylib' (no such file), '/opt/homebrew/Cellar/libvmaf/3.0.0/lib/libvmaf.1.dylib' (no such file), '/usr/local/lib/libvmaf.1.dylib' (no such file), '/usr/lib/libvmaf.1.dylib' (no such file, not in dyld cache)
zsh: abort      ffmpeg --help
```

### What did you expect to happen?

I expected to be able to install `felinks` without breaking `ffmpeg`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew install felinks` with a non-bottled ffmpeg
2. `ffmpeg --help`
```

**Comment by Bo98** [comment]
`libvmaf` recently shipped a ABI-breaking update: https://github.com/Homebrew/homebrew-core/pull/158706 so you will need to rebuild/upgrade your ffmpeg.

**Comment by llimllib** [comment]
it wasn't customized, I wish had grabbed the `brew info` for it before I tried reinstalling (which fixed it, fwiw)

**Comment by Bo98** [comment]
> Referenced from: <99C9A833-0757-369A-BD38-C9ED73839C70> /opt/homebrew/Cellar/ffmpeg/6.0-with-options_1/bin/ffmpeg

We don't ship `6.0-with-options_1`. I'm guesing this is the [homebrew-ffmpeg tap](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg).

**Comment by llimllib** [comment]
fair enough, I do have that tapped: now I have a vague memory that I needed to support a media type homebrew didn't in its bottle.

The feedback I'll leave and then let it lie: As a user, I feel upset that `brew install felinks` broke an unrelated tap and I had to do a deep dive to figure out why, and only happened to figure it out while I had the output handy; if I'd not seen that message and a few days later `ffmpeg` was broken and there was no information about why, that's a really unpleasant user experience

**Comment by Bo98** [comment]
The message `Warning: The following dependents of upgraded formulae are outdated but will not be upgraded because they are not bottled` is indeed an indication of what needed to be done.

The reason we don't upgrade ffmpeg automatically is that it's not bottled by that tap and thus builds from source and could take a very long time. If it was bottled it would have been automatically handled for you.

If it didn't appear at the very end of the output, it probably should be fixed so that it does.
