### ISSUE TITLE
Completion broken for `brew upgrade` on Linux

### ISSUE THREAD

**Issue by jacktose** [Homebrew/brew#16488]
### `brew doctor` output
```shell
Your system is ready to brew.
```

### Verification
- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output
<details>
<summary><code>brew config</code></summary>

```shell
HOMEBREW_VERSION: 4.2.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c612baa096c69f2fcb221c74e6f5b9979efdcee
Last commit: 27 hours ago
Core tap JSON: 16 Jan 17:08 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 3.1.4 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 20-core 64-bit unknown_0x6_0x9a
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 22.04.3 LTS (jammy)
WSL: 2 (Microsoft Store)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```
</details>

### What were you trying to do (and why)?
Use tab-completion (in bash) to upgrade a formula without typing its full name (because I'm lazy and/or don't want to misspell it).

### What happened (include all command output)?
```shell
$ brew uninstall libg[Tab]  # Instantly completes to:
$ brew uninstall libgit2

$ brew upgrade libg[Tab]  # Hangs ~7s then bells. Never completes.

# Apparently still in the middle of typing the command, so:
$ brew upgrade libg[Enter]
Error: No available formula with the name "libg". Did you mean libgr?
```

### What did you expect to happen?
Formula name should autocomplete without error.

Notably, completion works fine for `brew uninstall`, which I assume should pull from the same list of options.

```shell
$ brew uninstall libg[Tab]  # Instantly completes to:
$ brew uninstall libgit2
```

### Step-by-step reproduction instructions (by running `brew` commands)
```shell
[Run homebrew on linux]
brew install [formula]
brew upgrade [partial formula name][Tab]
```

### Bash completion info

> what is your `bash --version` and `which bash` output?

```shell
$ echo "$SHELL"
/bin/bash

$ which -a bash
/usr/bin/bash
/bin/bash

$ /usr/bin/bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ /bin/bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
...
```

> How have you setup your Bash completion?

The short version is
```shell
source /home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
source /usr/share/bash-completion/bash_completion
```

<details>
<summary>The long version is that my `~/.bashrc` has a bunch of conditional logic for different systems, including these bits, which resolve as above on this system:</summary>

```shell
    if [ ! -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]; then
        # If that exists (from `bash-completion` formula), it will have
        # automatically sourced completions. Otherwise, do it manually:
        for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
            [ -r "${COMPLETION}" ] && source "${COMPLETION}"
        done

# activate bash-completion
if [[ $PS1 ]]; then  # interactive shell
    if   [[ -r "/usr/share/bash-completion/bash_completion" ]]; then
        . "/usr/share/bash-completion/bash_completion"
    elif [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]]; then
        . "/usr/local/etc/profile.d/bash_completion.sh"
    elif can_brew && [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]]; then
        . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    elif [[ -r "$HOME/.linuxbrew/etc/profile.d/bash_completion.sh" ]]; then
        . "$HOME/.linuxbrew/etc/profile.d/bash_completion.sh"
    fi
fi
```
</details>

### Another example
<details>
<summary>I have the same experience on another system, with CentOS 7 & Bash 4. It's not what I'm mainly reporting on because it's a non-standard install and all kinds of buggered. But for another example:</summary>

```shell
centos $ echo "$SHELL"
/bin/bash

centos $ which -a bash
/bin/bash
/usr/bin/bash

centos $ /bin/bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

centos $ /usr/bin/bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
...
```
And the same `.bashrc` which means effectively:
```shell
source /usr/lusers/jacktose/homebrew/etc/bash_completion.d/brew
source /usr/share/bash-completion/bash_completion
```
</details>

### Related issue
I reported this in its previous form in #16424. #16452 hid the stderr message, but the failed completion remains an issue.

**Comment by jacktose** [comment]
Ah, that explains it: there are no outdated `libg*` formulae.

It seems like a clever idea to only complete names of actually outdated formula, but I'd find it a better experience to complete any installed formula name and get the instant feedback of the completion plus the ~2s feedback of the warning:

```shell
$ brew upgrade libgit2
Warning: libgit2 1.7.1 already installed
```

**Comment by MikeMcQuaid** [comment]
> It seems like a clever idea to only complete names of actually outdated formula, but I'd find it a better experience to complete any installed formula name and get the instant feedback of the completion plus the ~2s feedback of the warning

Agreed. Would review and likely accept a PR that did this.

**Comment by Bo98** [comment]
This explains a lot why `brew outdated` previously didn't do auto-updates: the shell completions use `brew outdated`!

At a minimum, auto-updates should be disabled within shell completions. Though even then the ~0.7s+ for `brew outdated` is probably noticeable given `brew formulae` etc take ~0.05s.

**Comment by cho-m** [comment]
> Though even then the ~0.6s+ without auto-updates for `brew outdated` is probably noticeable given `brew formulae` etc take ~0.05s.

Yeah, that isn't ideal. Most likely, we cannot hit Ruby code. Which would mean either just switching to installed formula/casks (revert of line: https://github.com/Homebrew/brew/commit/3af16832d9baa6ebe3d85701734720d0fe75bea4#diff-2b40f539194f871ba5fb8069acf4255481b282877bb7019d90f1844252f0651a) or caching the outdated formulae/casks during `brew update`.

---

Also, since we use `complete -o bashdefault ...` this means an empty `COMPREPLY` (i.e. no outdated formulae/casks) currently outputs default of pwd's files/directories. This probably makes completion look broken.

**Comment by MikeMcQuaid** [comment]
> Though even then the ~0.6s+ without auto-updates for `brew outdated` is probably noticeable given `brew formulae` etc take ~0.05s.

Yeh I think `brew formulae` is worth using. 

> caching the outdated formulae/casks during `brew [update|outdated]`.

Could do but I worry about an outdated `outdated` being worse than just using `formulae`.

**Comment by cho-m** [comment]
The easiest option is then using `installed_*` (i.e. #16528). This does modify manpages and docs too if that matters.

**Comment by cho-m** [comment]
https://github.com/Homebrew/brew/pull/16528 is merged so should be available in next `brew` release tag.

**Comment by cho-m** [comment]
Closing with 4.2.6 release.

**Comment by jacktose** [comment]
Thanks all! The experience in 4.2.6 is much nicer, IMO.
