### ISSUE TITLE
brew bump --installed fails when missing pr listing rights

### ISSUE THREAD

**Issue by nicerloop** [Homebrew/brew#16504]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.4-55-g5a297a7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5a297a7dd5bbbbc50dfad718b58bc58e3dbbb8c4
Last commit: 75 minutes ago
Core tap HEAD: 64b6aa63c41558c004a307f7f2e8fcd98d2d7d8b
Core tap last commit: 35 minutes ago
Core tap JSON: 03 Aug 07:59 UTC
Core cask tap HEAD: 680e8faf3d392299f383cc22b281e764423f9003
Core cask tap last commit: 67 minutes ago
Core cask tap JSON: 13 Sep 16:07 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 730
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 15.0.0 build 1500
Git: 2.43.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6.3-x86_64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
```

### What were you trying to do (and why)?

I tried to check all my installed formulae and casks:

brew bump --installed

### What happened (include all command output)?

After some successful checks, and some PRs opened, the command stopped with the following message:

Error: Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}]

The processed items all have starting names in 'a', the items whose names start with alphabetically following letters not even tried.

After investigation, using --verbose --debug, it appears the failing item is wix/brew/applesimutils. Using --installed --no-pull-requests, the process completed without failure.

### What did you expect to happen?

I expected the failing pr listing to be eventually logged, but mainly the process to continue to check the remaining items.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap wix/brew
brew install wix/brew/applesimutils
brew bump --installed
```

**Comment by issyl0** [comment]
Thanks for the issue.

The repository `wix/homebrew-brew` used to exist, but doesn't anymore. It now redirects in a browser (and when cloning the repo, installing the formula from the tap, etc.) to `wix-incubator/homebrew-brew`. This breaks our detection of if there are any PRs.

Not immediately sure how to fix this, but that's what's happening. You're right that it probably should _not_ horribly fail, it should just note it and continue onwards.
