### ISSUE TITLE
Homebrew initial installation fails

### ISSUE THREAD

**Issue by nelson-global** [Homebrew/brew#16517]
### `brew doctor` output

```shell
Not Applicable since can't install Homebrew, an error occurs on initial installation
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
Not Applicable
```

### What were you trying to do (and why)?

Trying to install homebrew on my mac

### What happened (include all command output)?

alien@Nelsons-MacBook-Pro ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R alien:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 253483, done.
remote: Counting objects: 100% (35383/35383), done.
remote: Compressing objects: 100% (1158/1158), done.
error: RPC failed; curl 18 HTTP/2 stream 5 was reset107.00 KiB/s
error: 2905 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Failed during: /usr/bin/git fetch --force origin
alien@Nelsons-MacBook-Pro ~ % 

<img width="628" alt="Screenshot 2024-01-21 at 22 12 46" src="https://github.com/Homebrew/brew/assets/149663746/00d7ee92-3112-4a47-bf8d-deb7fb69cf34">

### What did you expect to happen?

I expected a smooth initial installation process

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Not Applicable since can't install Homebrew
```

**Comment by MikeMcQuaid** [comment]
This is an issue with your connection to GitHub. We cannot fix this. Please retry. In future: open a discussion for this instead of an issue, thanks.
