### ISSUE TITLE
Packages with shared zappable state

### ISSUE THREAD

**Issue by maia-s** [Homebrew/brew#16523]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Hi, I was asked to open this issue here by @p-linnane .

I recently submitted [a pull request to homebrew-cask to add the nightshade cask](https://github.com/Homebrew/homebrew-cask/pull/164906), which shares state with the glaze cask. They can each be used on their own, or together. Both glaze and nightshade stores many GBs of data in their shared state dir, so it's desirable to be able to zap it on uninstall. However, if both are installed, uninstalling only glaze shouldn't zap the state for nightshade, and vice versa, even if zap is requested.

I'd like for Homebrew to have a way to configure this so that shared state would only be zapped once all packages that use it are uninstalled.

### What is the motivation for the feature?

See above

### How will the feature be relevant to at least 90% of Homebrew users?

Zap wouldn't remove data that's in use.

### What alternatives to the feature have been considered?

Remove zap from the affected packages. This will leave several GBs of stale data behind on uninstall.

**Comment by MikeMcQuaid** [comment]
I'd want to see 3+ casks that would need this before we'd consider adding a DSL for this. For now, the best fit is to add this to `caveats` or similar and omit from the `zap`.

**Comment by bevanjkay** [comment]
I would note that it is referenced in the docs that a `zap` stanza may remove files that are shared with other applications. So this is currently the expected behaviour. 

https://docs.brew.sh/Cask-Cookbook#stanza-zap

> Shared resources such as application updaters. Since shared resources may be removed, other applications may be affected by brew uninstall --zap. Understanding that is the responsibility of the end user.


A `zap` stanza goes to greater lengths to remove files associated with an application than the non-Homebrew uninstall method, and is by no means a requirement when uninstalling.
