### ISSUE TITLE
Error: Could not link main/homebrew/etc/bash_completion.d/brew

### ISSUE THREAD

**Issue by mzachh** [Homebrew/brew#1653]
Hi,

our installation fails now with the following error. It was still working a few hours ago.

Could it be related to #1616

```
==> Searching taps...

Error: Could not link:
.../main/homebrew/etc/bash_completion.d/brew

Please delete these paths and run `brew update`.
Error: Could not link:
.../main/homebrew/share/doc/homebrew

Please delete these paths and run `brew update`.
Error: Could not link:
.../main/homebrew/share/zsh/site-functions/_brew

Please delete these paths and run `brew update`.
Error: Could not link:
.../main/homebrew/share/man/man1/brew-cask.1
.../main/homebrew/share/man/man1/brew.1
```

**Comment by MikeMcQuaid** [comment]
Did you try to delete those paths and run `brew update`?

**Comment by mzachh** [comment]
Still trying to pin down the root cause. If I delete those paths and run `brew update` it works.

But we are currently depending on installing homebrew newly with an automated method. So I think there must be something broken in the homebrew installation itself.

**Comment by mzachh** [comment]
Sorry the problem was with our setup, we pulled in an old dependency.
