### ISSUE TITLE
Terraform version: No update

### ISSUE THREAD

**Issue by wladimirgrf** [Homebrew/brew#16545]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

It's not exactly a new feature but a request for the latest version of Terraform.

Current version: `1.7.1`
Latest version supported by HomeBrew: `1.5.7`

### What is the motivation for the feature?

It is important to keep the package versions as close to the official version as possible. For security reasons and access to new resources.

### How will the feature be relevant to at least 90% of Homebrew users?

100% of Terraform/Homebrew users.

### What alternatives to the feature have been considered?

If Homebrew has dropped any support for future versions of Terraform, the solution will be to find a new package manager.

**Comment by cho-m** [comment]
Please do not ignore details in checkbox:
>  issue's title and/or description do not reference a single formula

Also, Terraform no longer meets Homebrew's license requirements - https://github.com/Homebrew/homebrew-core/pull/139538
