### ISSUE TITLE
Remove use of sorbet's deprecated hidden-definitions

### ISSUE THREAD

**Issue by dduugg** [Homebrew/brew#16557]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`hidden-definitions` is slow, deprecated, and [error-prone](https://github.com/Homebrew/brew/pull/16281). Let's replace it with Tapioca DSL [compilers](https://github.com/Shopify/tapioca?tab=readme-ov-file#writing-custom-dsl-compilers) and RBI files where needed. (It currently masks 160 type errors, though half of them should resolve when https://github.com/Homebrew/brew/pull/16540 merges.)

### What is the motivation for the feature?

☝️ 

### How will the feature be relevant to at least 90% of Homebrew users?

Not so much

### What alternatives to the feature have been considered?

We could maintain the status quo indefinitely

**Comment by MikeMcQuaid** [comment]
Makes sense to me!
