### ISSUE TITLE
Request to create a new cask for the ProtonMail-Beta App

### ISSUE THREAD

**Issue by plsnotracking** [Homebrew/brew#16561]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Hello,

I would like to request a brew cask for [ProtonMail-Beta App](https://proton.me/download/mail/macos/ProtonMail-desktop-beta.dmg) if possible.

Thank you.

### What is the motivation for the feature?

It's a new piece of software recently released.

### How will the feature be relevant to at least 90% of Homebrew users?

They can then package control the app instead of either updating from the app or from the website.

### What alternatives to the feature have been considered?

Just downloading from the link mentioned above.

**Comment by MikeMcQuaid** [comment]
https://docs.brew.sh/Adding-Software-to-Homebrew#casks
