### ISSUE TITLE
Zombie cURL Processes Hanging off of Homebrew

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/brew#1657]
### Please follow the general troubleshooting steps first:

- [x] Run `brew update` and retried your prior step?
- [x] Run `brew doctor`, fixed as many issues as possible, and retried your prior step?
- [x] Confirmed this is a problem with [Homebrew/brew](https://github.com/Homebrew/brew) and not specific formulae?  If it's a formula-specific problem, then please file this issue at [https://github.com/Homebrew/homebrew-core/issues/new](https://github.com/Homebrew/homebrew-core/issues/new).  

### Bug reports:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I keep forgetting to report this, but I often see a zombie cURL process hanging off of Homebrew in the instance of Terminal that I'm using.  This is because I currently have Terminal set up to show the active process name and arguments in its windows' title bars.  I can also confirm this behavior by invoking Terminal's Inspector, which contains a table of the current window's or tab's running processes.  I have observed this happening with/under at least `brew update`, `brew outdated`, `brew cleanup`, and `brew doctor`.  

<hr />

Output of `brew config`:  
```
HOMEBREW_VERSION: 1.1.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0f529dae1043639058130092cf35e68d18907cb8
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 68f3bee60d515971848c5a9838d960902296fcfc
Core tap last commit: 15 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit core2
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.3/bin/ruby
Java: 1.8.0_112, 1.8.0_111
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.11 => /opt/X11
```

Output of `brew doctor`:  
```
Your system is ready to brew.
```

**Comment by MikeMcQuaid** [comment]
Will reopen this if there's more widespread reports but this looks like a one-off. If you can figure out how to make this reproducible I'll happily reopen.

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  Wait, this is the first time you've _heard_ about _anything_ like this ever occurring…?!?  This has happened to me pretty much _every single time I have ever run Homebrew!_  I thought it might have something to do with a bug in the way `brew` worked and that _everyone_ might see it if they looked hard enough.  (I'd suspect, though, that they either usually don't or that their machines are so much newer and faster than the mid-2007 aluminum iMac I'm still using that they'd miss such an event since it would thereby just rush past them as a blip on their screens.)  In any case, how would you recommend I start trying to debug this here on my end&thinsp;—&thinsp;that is, how might I go about instrumenting Homebrew to figure out what's causing me to see this issue in the first place?  Should I just start inspecting places where Homebrew calls into cURL and see if anything weird's happening there?

**Comment by MikeMcQuaid** [comment]
> Wait, this is the first time you've heard about anything like this ever occurring…?!?

Yes.

When you say "zombie" do you mean `curl` processes that outlive Homebrew (expected) or ones that literally never terminate even if left for e.g. a hour (unexpected)?

**Comment by RandomDSdevel** [comment]
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;No, nothing _that_ bad, honest!  What appears to happen is just that Homebrew runs cURL as a sub-process more than it needs to for _much_ longer than necessary, leaving it hanging there in the background until it might need it whether it ever does or not, depending on Homebrew sub-command.  It closes properly upon `brew` exit as far as I'm aware, though, so I'm not any more sure about what's going on under the hood than I've ever been.  What do you mean that it's expected that `curl` processes might outlive Homebrew, by the way?  Wouldn't that be a resource leak that you might want to clean up?

**Comment by MikeMcQuaid** [comment]
That's kinda a feature rather than a bug. Homebrew's analytics `curl` processes are detached which means Homebrew can exit before `curl` has finished doing what it's doing. This means if Homebrew outperforms your network connection then you're not waiting around unnecessarily.

> What do you mean that it's expected that curl processes might outlive Homebrew, by the way? Wouldn't that be a resource leak that you might want to clean up?

I was asking if this was what you were describing. For a learning point, this is generally what are referred to as zombie processes: those that cannot be `kill`ed with `-9`. This doesn't seem to be the case here, it's just processes outliving Homebrew which is intentional.

**Comment by RandomDSdevel** [comment]
> That's kinda a feature rather than a bug.  Homebrew's analytics `curl` processes are detached which means Homebrew can exit before curl has finished doing what it's doing.  This means if Homebrew outperforms your network connection then you're not waiting around unnecessarily.  
>
> …

Oh, duh!  I forgot to take Homebrew's analytics processes into account in my thinking!  Now I get it!   <image src="http://emojipedia-us.s3.amazonaws.com/cache/d7/03/d70331a5a600e63296c9b8f925ce9aae.png" alt="face palm" height="15px" width="15px" style="inline;" />

> …
>
>> …
>>
>> …What do you mean that it's expected that `curl` processes might outlive Homebrew, by the way?  Wouldn't that be a resource leak that you might want to clean up?  
>
> I was asking if this was what you were describing.  For a learning point, this is generally what are referred to as zombie processes:  those that cannot be `kill`ed with `-9`.  This doesn't seem to be the case here, it's just processes outliving Homebrew which is intentional.  

Blargh, now I feel silly for even opening this issue.  Thanks for the clarification, though.
