### ISSUE TITLE
Python readline library error '  Reason: image not found'

### ISSUE THREAD

**Issue by Ajeet-Ganga** [Homebrew/brew#1658]
I am using  brew brew's bash, brew's python.
Using virtual-env.

I get following error which I think is related  to brew:

aganga@my-machine::~
[511]$pip install readline
Requirement already satisfied: readline in ./venvp3/lib/python3.5/site-packages
[512]$python3
>>> import readline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/aganga/venvp3/lib/python3.5/readline.so, 2): Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /Users/aganga/venvp3/lib/python3.5/readline.so
  Reason: image not found

brew config
==============

HOMEBREW_VERSION: 1.1.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0f529dae1043639058130092cf35e68d18907cb8
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 68f3bee60d515971848c5a9838d960902296fcfc
Core tap last commit: 33 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/aganga/venvp3/bin/python => /Users/aganga/venvp3/bin/python3.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45
macOS: 10.12.1-x86_64
Xcode: N/A
CLT: 8.1.0.0.1.1476494586
X11: N/A

brew doctor
=================

[1mPlease note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks![0m

[33mWarning:[0m python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

[33mWarning:[0m "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/aganga/venvp3/bin/python-config

Warning:[0m You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker

brew gist-logs bash
=====================
Error:[0m No logs.

**Comment by vladshablinsky** [comment]
I'm not sure it's related. Possible scenario is that you upgraded readline (from 6 to 7) with Homebrew, but your python stuff is built against readline 6.

**Comment by Ajeet-Ganga** [comment]
I went through few funky steps to get readline6.3 (changing brew's head to older commit and then getting readline6.3).  Even that did not help.

I reinstalled python3.  That did not help.


What helped me finally was, I un-installed readline, and python .
and then  Installed readline and python from  sourcecode.

That worked.

**Comment by vladshablinsky** [comment]
Probably it could have been done a bit differently, but I'm happy you sorted everything out.

**Comment by peterbe** [comment]
@Ajeet-Ganga Did you eventually install readline 6 or 7 with homebrew?

My python3 is currently busted (with that `Reason: image not found`) too and have I have readline 7.0.3 installed apparently. I'm wondering if un-installing and re-installing python3 will solve this.
