### ISSUE TITLE
Brew search returns "invalid tap name"

### ISSUE THREAD

**Issue by sboesebeck** [Homebrew/brew#16607]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.7-43-g6775171
ORIGIN: https://github.com/Homebrew/brew
HEAD: 677517132782b276ba1c4ba77456adf7540d99ba
Last commit: 35 minutes ago
Core tap JSON: 06 Feb 20:10 UTC
Core cask tap JSON: 06 Feb 20:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 20
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 20-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```

### What were you trying to do (and why)?

I want to search the database for packages... well, the reason is obvious...

### What happened (include all command output)?

❯ brew search python
Error: Invalid tap name 'mysql-connector-python/'
❯ brew search hello
Error: Invalid tap name 'helo/'
❯ brew search -d hello
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading jello from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading helm from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading hello from API
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading helo
Error: Invalid tap name 'helo/'
/opt/homebrew/Library/Homebrew/tap.rb:48:in `fetch'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:460:in `tap_cask_token_type'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:502:in `block in for'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:495:in `each'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:495:in `for'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:455:in `load'
/opt/homebrew/Library/Homebrew/search.rb:96:in `block in search_casks'
/opt/homebrew/Library/Homebrew/search.rb:95:in `map'
/opt/homebrew/Library/Homebrew/search.rb:95:in `search_casks'
/opt/homebrew/Library/Homebrew/search.rb:115:in `search_names'
/opt/homebrew/Library/Homebrew/cmd/search.rb:85:in `search'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'

### What did you expect to happen?

get a result

### Step-by-step reproduction instructions (by running `brew` commands)
not really a step, i assume. The error just occurs... undependent on what to search for.
```shell
brew search hello
```

**Comment by michaelmior** [comment]
I'm seeing this with other commands as well. For example, any upgrade or install involving a cask. It looks like there's already a potential fix in #16608.

**Comment by princecodes247** [comment]
This is also happening to me with the install command
```brew install --cask xxx```

**Comment by bevanjkay** [comment]
Thanks for the reports, the issue will be resolved shortly

**Comment by sboesebeck** [comment]
awesome - that was fast, fixed it for me!

**Comment by michaelmior** [comment]
Fixed for me too!
