### ISSUE TITLE
I can't install. /usr/local/Homebrew/.git: Permission denied Failed during: git init -q

### ISSUE THREAD

**Issue by heathkimdev** [Homebrew/brew#1662]
After fresh install macOS Sierra 10.12.1, I tried to install homebrew, but I can't install.

It says

`/usr/local/Homebrew/.git: Permission denied
Failed during: git init -q`

What am I gonna do?

**Comment by heathkimdev** [comment]
Sorry, It caused by my mistake.

**Comment by BarryZhan** [comment]
How to solve？
