### ISSUE TITLE
doctor: "You have a curlrc file" warning shouldn't be needed

### ISSUE THREAD

**Issue by willfaught** [Homebrew/brew#1664]
`brew doctor` prints:

```
Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com
```

Why can't brew just use the `-q` curl flag to ignore the file? brew ought to work cleanly with a .curlrc, otherwise it's basically repurposing a system tool for its own use.

```
HOMEBREW_VERSION: 1.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6b4de315046a8e4d8b8b70418f7ccd15fecb7801
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8366963081de08ac2a069fa5ea22b00a56fece05
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/will.faught/.rbenv/shims/ruby => /Users/will.faught/.dotfiles
Java: 1.8.0_102
macOS: 10.12.1-x86_64
Xcode: N/A
CLT: 8.1.0.0.1.1476494586
X11: 2.7.9 => /opt/X11
```

**Comment by DomT4** [comment]
> Why can't brew just use the -q curl flag to ignore the file?

It used to, people complained a lot. See https://github.com/Homebrew/legacy-homebrew/issues/13836, https://github.com/Homebrew/legacy-homebrew/commit/ef2597847bf1995c4711f929107e71b8cc418b89, etc.

**Comment by willfaught** [comment]
Isn't the root of the issue https://github.com/Homebrew/legacy-homebrew/issues/13836 that brew wasn't using proxy settings? Why not instead check for HTTP_PROXY, HTTPS_PROXY, and NO_PROXY and use that? Using .curlrc isn't going to fix all that person's proxy problems anyway. My understanding is that HTTP_PROXY, HTTPS_PROXY, and NO_PROXY are the standard way to deal with proxies in Unix command-line environments.

**Comment by MikeMcQuaid** [comment]
@willfaught Regardless of what the standard is all our network access goes through `curl` so any arguments about why those variables aren't used correctly should be directed to the `curl` maintainers. As noted by `brew doctor`: you can ignore the warnings unless you have problems.

**Comment by willfaught** [comment]
Isn't it possible that the problem in that issue is that the person hadn't
set those variables? If they had, couldn't Homebrew have worked with curl
correctly?

**Comment by kinjitsu** [comment]
Please excuse the interruption, but I mistakenly subscribed to this topic.
I'm new to github and in training. I thought that I had unsubscribed on the
github website, but the email threads haven't stopped. Please tell me how
do I stop the emails.
Thank you in advance.

**Comment by woodruffw** [comment]
@kinjitsu You should see an "unsubscribe" button on the right side of this page, in your browser. Click on that.
