### ISSUE TITLE
config date format are unknown

### ISSUE THREAD

**Issue by stmtk1** [Homebrew/brew#16659]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`brew config` command outputs `Core tap JSON` date and `Core cask tap JSON` date. These date format is unknown format.  I think ISO 8601 format is better.

### What is the motivation for the feature?

 This format don't write year. So we can't know year information. 

### How will the feature be relevant to at least 90% of Homebrew users?

I don't know

### What alternatives to the feature have been considered?

I think ISO 8601 format is better.

**Comment by MikeMcQuaid** [comment]
@stmtk1 Why do you need to know the year?

**Comment by reitermarkus** [comment]
No opinion on the format, but we should at least use a consistent one:

```
Core tap last commit: 41 minutes ago
Core tap JSON: 14 Feb 21:30 UTC
```

**Comment by MikeMcQuaid** [comment]
> but we should at least use a consistent one:

Not necessarily. The inputs are very different so the outputs may be more useful as they are (which I tend to agree with on last commit being relative).

**Comment by reitermarkus** [comment]
Both answer the question “When was it last updated?”, so they don't seem that different to me.

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this.

**Comment by MikeMcQuaid** [comment]
Will review/consider a PR, though (but cannot promise it will be merged).
