### ISSUE TITLE
brew can't see Formulas aliases if homebrew/core untapped

### ISSUE THREAD

**Issue by andreisidorenko** [Homebrew/brew#16682]
### `brew doctor` output

```shell
> brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.8-125-ga6d539c-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: a6d539cf11a0db5a2c0f6fb78ff1ed09bf576a93
Last commit: 17 minutes ago
Core tap HEAD: a44bd8e98ffee5f800a1c5c94532892ffdcfe822
Core tap last commit: 52 minutes ago
Core tap JSON: 16 Feb 10:14 UTC
Core cask tap HEAD: 2af3e89e4eed25531f6dbd7ded492e07ae50a7e9
Core cask tap last commit: 30 minutes ago
Core cask tap JSON: 16 Feb 10:14 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.1
Rosetta 2: false
```

### What were you trying to do (and why)?

- Tried to install `go@1.22`. Alias for this exists at https://github.com/Homebrew/homebrew-core/blob/a44bd8e98ffee5f800a1c5c94532892ffdcfe822/Aliases/go%401.22
- Checked other Formulas installation using Aliases (for example `ant@1.10`)

### What happened (include all command output)?

`No available formula with the name ...` errors. Outputs examples:
```
❯ brew info go@1.22
Error: No available formula with the name "go@1.22". Did you mean go@1.21, go@1.20, go@1.19, go@1.18, go@1.17 or go@1.16?
Command /opt/homebrew/bin/original-brew info go@1.22 failed!
❯ brew install go@1.22
Warning: No available formula with the name "go@1.22". Did you mean go@1.21, go@1.20, go@1.19, go@1.18, go@1.17 or go@1.16?
==> Searching for similarly named formulae and casks...
==> Formulae
go@1.21 ✔                 go@1.20                   go@1.19                   go@1.18                   go@1.17                   go@1.16

To install go@1.21 ✔, run:
  brew install go@1.21 ✔
Command /opt/homebrew/bin/original-brew install go@1.22 failed!
❯ brew info ant@1.10
Error: No available formula with the name "ant@1.10". Did you mean ant@1.9?
Command /opt/homebrew/bin/original-brew info ant@1.10 failed!
```

### What did you expect to happen?

Expected that formulas to be installed, as we have [aliases](https://github.com/Homebrew/homebrew-core/tree/a44bd8e98ffee5f800a1c5c94532892ffdcfe822/Aliases) for them.

Noticed that it happens if `homebrew/cask` tap is untapped ([default behavior](https://brew.sh/2023/02/16/homebrew-4.0.0/) for brew > 4.0.0). If we have `homebrew/cask` tap  - Aliases work as expected.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Ensure that `homebrew/cask` tap is not added with `brew tap` command (shouldn't be added by default).
2. Try to use any Formula Alias, for example `brew install go@1.22`
```

**Comment by ZhongRuoyu** [comment]
`git bisect` suggests that 46416906745c122068f962d69ecf47c1bca8ef30 is the first bad commit. CC @reitermarkus
