### ISSUE TITLE
`brew update-python-resources` attempts to update resources in `test` blocks

### ISSUE THREAD

**Issue by p-linnane** [Homebrew/brew#16704]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`brew update-python-resources` currently attempts to update resources in `test` blocks. `test` blocks often contain resources that do not need to be updated nor can they be updated normally.

### What is the motivation for the feature?

While updating the `sigstore` formula I ran into issues with getting the Python resources to update. It turns out this is because we were attempting to find updates for the resources in the `test` block. This is unnecessary, and prevents us from auto bumping the formula.

### How will the feature be relevant to at least 90% of Homebrew users?

More formulae will be able to be auto bumped, providing a better user experience.

### What alternatives to the feature have been considered?

Maintain current state and manually update resources.

**Comment by Bo98** [comment]
The concept of a resource in a test block has never been explicitly supported - I didn't even know it was used until now. If it works as expected with `brew fetch -s` etc then might be worth supporting officially.

**Comment by p-linnane** [comment]
There's been some movement on putting test-only resources in that block so that they don't have to be pulled down if just building from source.

**Comment by Bo98** [comment]
Yeah the concept of a test-only resource makes sense, just not something we've ever documented or though about the DSL for.

**Comment by MikeMcQuaid** [comment]
Makes sense to me, good idea @p-linnane.

**Comment by cho-m** [comment]
Closing as completed in #16790.
Also opened a minor doc change PR #16874 to discuss test resource DSL further.
