### ISSUE TITLE
mGBA emulator update

### ISSUE THREAD

**Issue by Eraguzy** [Homebrew/brew#16700]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

[mGBA 0.10.3](https://github.com/mgba-emu/mgba/releases/tag/0.10.3) has been released Jan 8 with a few bug fixes. brew's mGBA version is still at 0.10.2. It would be appreciated if the latest version could be featured on brew.

<img width="967" alt="305906146-9e6ddf2f-5fec-42ad-bad3-4f9c29bb157a" src="https://github.com/Homebrew/brew/assets/122539649/00bfc421-0b0b-4aca-b93b-591a4e55463d">

### What is the motivation for the feature?

brew is by far the most comfortable way to get mgba on macs.

### How will the feature be relevant to at least 90% of Homebrew users?

i doubt there are so much people using mGBA. but it would still be appreciated by mGBA users :)

### What alternatives to the feature have been considered?

none

**Comment by reitermarkus** [comment]
> It would be appreciated if the latest version could be featured on brew.

You can follow the instructions at https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request on how to update it.
