### ISSUE TITLE
Running "brew uses" gives error

### ISSUE THREAD

**Issue by Moulick** [Homebrew/brew#16709]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  meld

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
```

### Verification

- [ ] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.9-47-gaa58637
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa586372018af8bacf16c12172eae509960c0887
Last commit: 3 hours ago
Core tap HEAD: 0d8d67cb4461df657ce222b772a52dab38aac8d1
Core tap last commit: 22 minutes ago
Core tap JSON: 20 Feb 11:01 UTC
Core cask tap HEAD: e4377b4b23cf6c3c249eb99efee54d9c8bdf5480
Core cask tap last commit: 21 minutes ago
Core cask tap JSON: 20 Feb 11:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code --wait --add
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.2 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Trying to run `brew uses --recursive --eval-all --include-build --include-optional --verbose go` or `brew uses --recursive --eval-all --include-build --include-optional --verbose node`

### What happened (include all command output)?

```shell
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:307:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:238:in `initialize'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/formulary.rb:503:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:503:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:745:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/formula.rb:1935:in `block in all'
/opt/homebrew/Library/Homebrew/formula.rb:1934:in `map'
/opt/homebrew/Library/Homebrew/formula.rb:1934:in `all'
/opt/homebrew/Library/Homebrew/cmd/uses.rb:119:in `intersection_of_dependents'
/opt/homebrew/Library/Homebrew/cmd/uses.rb:83:in `uses'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### What did you expect to happen?

Give me a list of all formulas that depend on Go or Node

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew uses --recursive --eval-all --include-build --include-optional --verbose node
brew uses --recursive --eval-all --include-build --include-optional --verbose go
```

**Comment by bevanjkay** [comment]
What is your output for `brew tap`? It looks as if you have a file in one of your taps that is missing a `url`.

**Comment by Moulick** [comment]
```
❯ brew tap
Alias tip: b tap
anchore/grype
anchore/syft
aquasecurity/trivy
buo/cask-upgrade
confluentinc/confluent-hub-client
datawire/blackbird
derailed/popeye
gabrie30/utils
gdubw/gng
goreleaser/tap
grishka/grishka
gromgit/fuse
hashicorp/tap
homebrew-ffmpeg/ffmpeg
homebrew/autoupdate
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/command-not-found
homebrew/core
homebrew/services
homebrew/test-bot
jakehilborn/jakehilborn
jorgelbg/tap
kreuzwerker/taps
mike-engel/jwt-cli
playcover/playcover
reviewdog/tap
systemcraftsman/strimzi-kafka-cli
teamookla/speedtest
warrensbox/tap
```

**Comment by bevanjkay** [comment]
Does running one of the failing commands with `--debug` provide any additional information?

**Comment by Moulick** [comment]
<details><summary>brew uses --recursive --eval-all --include-build --include-optional --verbose --debug node</summary>
<p>

❯ brew uses --recursive --eval-all --include-build --include-optional --verbose --debug node
Alias tip: b uses --recursive --eval-all --include-build --include-optional --verbose --debug node
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading node from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading a2ps from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading a52dec from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading aacgain from API
.
.
.
.
.

/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-async from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-autocomplete from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-autopair from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-autosuggestions from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-completions from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-fast-syntax-highlighting from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-git-prompt from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-history-substring-search from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-lovers from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-navigation-tools from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-syntax-highlighting from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-vi-mode from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsh-you-should-use from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zshdb from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zssh from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zstd from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsxd from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zsync from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zug from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zurl from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zx from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zxcc from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zydis from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zyre from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zzuf from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zzz from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/aquasecurity/homebrew-trivy/trivy.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gdubw/homebrew-gng/Formula/gng.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/afuse-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/archivemount-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/avfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/bindfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/btfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/cryfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/curlftpfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/dislocker-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/encfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/ext2fuse-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/ext4fuse-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/fuse-zip-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/gcsfuse-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/gitfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/gocryptfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/goofys-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/ifuse-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/mp3fs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/ntfs-3g-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/rclone-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/rofs-filtered-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/s3-backer-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/s3fs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/s3ql-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/securefs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/simple-mtpfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/squashfuse-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/sshfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/tup-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/unionfs-fuse.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/wdfs-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/xmount-mac.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/mike-engel/homebrew-jwt-cli/Formula/jwt-cli.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/kreuzwerker/homebrew-taps/awsu.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/kreuzwerker/homebrew-taps/envsec.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/kreuzwerker/homebrew-taps/envplate.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/kreuzwerker/homebrew-taps/docker-compose@2.23.3.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/kreuzwerker/homebrew-taps/m1-terraform-provider-helper.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/derailed/homebrew-popeye/Formula/popeye.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/systemcraftsman/homebrew-strimzi-kafka-cli/strimzi-kafka-cli.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/reviewdog/homebrew-tap/Formula/reviewdog.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/boundary-enterprise.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/boundary.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/consul-aws.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/consul-dataplane.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/consul-enterprise.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/consul-esm.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/consul-k8s.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/consul-template.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/consul-terraform-sync.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/consul.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/copywrite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/envconsul.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/hc-install.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/hcdiag.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/levant.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/nomad-enterprise.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/nomad-pack.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/nomad.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/packer.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/sentinel.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/terraform-ls.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/terraform.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/tfstacks.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/vagrant.rb
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:307:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:238:in `initialize'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/formulary.rb:503:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:503:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:745:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/formula.rb:1935:in `block in all'
/opt/homebrew/Library/Homebrew/formula.rb:1934:in `map'
/opt/homebrew/Library/Homebrew/formula.rb:1934:in `all'
/opt/homebrew/Library/Homebrew/cmd/uses.rb:119:in `intersection_of_dependents'
/opt/homebrew/Library/Homebrew/cmd/uses.rb:83:in `uses'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'

</p>
</details> 

I have cut the output to fix github limits

**Comment by Moulick** [comment]
```ruby
File: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/vagrant.rb
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

class Vagrant < Formula
  desc "Development environment"
  homepage "https://www.vagrantup.com/"
  version "2.4.1"

  if OS.linux? && Hardware::CPU.intel?
    url "https://releases.hashicorp.com/vagrant/2.4.1/vagrant_2.4.1_linux_amd64.zip"
    sha256 "73a3dacf3f36fb4af8ef514aeff245833d086430614f0c183be7e263553dd7c2"
  end

  conflicts_with "vagrant"

  def install
    bin.install "vagrant"
  end

  test do
    system "#{bin}/vagrant --version"
  end
end
```

**Comment by ZhongRuoyu** [comment]
Looks like it's failing due to https://github.com/hashicorp/homebrew-tap/blob/dd32d64f3532a84fb451c57b942b37a0edc9ddcc/Formula/vagrant.rb

**Comment by bevanjkay** [comment]
The file is unreadable on MacOS

**Comment by Moulick** [comment]
I suppose brew should ignore in-case a formula does not support `mac`?

**Comment by bevanjkay** [comment]
The correct way to create the formula is to not have the `url` in a conditional, so that the formula can be parsed on all systems, but have a `depends_on` stanza for the relevant architecture.

**Comment by Moulick** [comment]
I'll try submit an PR there :)

**Comment by MikeMcQuaid** [comment]
We don't support errors with third-party taps here.
