### ISSUE TITLE
Feature request: Hint at new location of migrated formulae

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/brew#1672]
*I'm simply copying the proposal from https://github.com/Homebrew/brew-evolution/pull/15, since [brew-evolution is being deprecated](https://github.com/Homebrew/brew-evolution/pull/25).*

### Introduction

Users are confused when trying to install formulae known to have existed [1], yet getting the "No available formula" error due to said formulae having been migrated to another tap that has not been tapped. This proposal attempts to make the experience less confusing.

### Motivation

When a formula `foo` is migrated to another tap, subsequent attempts to show info or install it produce the unhelpful error

```
Error: No available formula with the name "foo"
```

This error is particularly confusing when it is known to the user that the formula once existed.

Meanwhile, knowledge about where `foo` was migrated to is already preserved in `tap_migrations.json` of the former home of `foo`, so we can encourage the user to look for `foo` in its new home.

Note that currently `install` (but not `info`) follows up the "No available formula" error with a search, but the experience is bad for several reasons:

- `brew search` does not search in homebrew/boneyard, which accounts for half of the migrations from core;
- `brew search` is slow, especially for connections with high latency;
- Without GitHub credentials in system keychain or `HOMEBREW_GITHUB_API_TOKEN`, a user can only search for three or four times before they hit the hourly API rate limit.

### Proposed solution

When a formula is not found when running `brew info` or `brew install`, search `tap_migrations.json` in installed taps and if a matching entry is found, hint at the new location.

### Detailed design

Suppose a formula `foo` was migrated from the `alice/tap` tap to the `bob/pat` tap and hence there is an entry `"foo": "bob/pat"` in `Library/Taps/alice/tap/tap_migrations.json`, the "No available formula" error message could instead be

```
Error: No currently available formula with the name "foo".
A "foo" formula was migrated from alice/tap to bob/pat. You may want to try
  brew install bob/pat/foo
```

Note that the suggested command(s) should match the user's action, so if the user was attempting `brew info`, the command(s) should instead be

```
  brew tap bob/pat
  brew info foo
```

When matches are found in `tap_migrations.json` of multiple taps, multiple hints may be printed.

When a match indicates migration to `homebrew/boneyard`, we may want to print a special warning.

In all cases where a match is found in the migration records, `install` should not initiate a search.

### Alternatives considered

1. One could point a user to http://braumeister.org/formula/foo which documents the history of a core formula even if it was migrated. Even better, it links to each relevant commit which is especially helpful for finding out why a formula was boneyarded. However, there are three major issues with this approach:

   - Most "No available formula" errors are for legitimately never-existent formulae;
   - braumeister.org only indexes core formulae;
   - braumeister.org is operated by a third party.

2. One could also ask a user to try `brew log foo`, which is also capable of turning up relevant commits, but this approach suffers from two problems:

   - Again, most "No available formula" errors are legit;
   - `brew log foo` may not turn up useful information on a shallow clone, which is what most users have on their system.

## References

[1] http://community.brew.sh/t/there-is-no-longer-a-clang-omp-formula-for-macos-sierra/47

**Comment by MikeMcQuaid** [comment]
Let's leave this over there for now and I'll cleanup that repo at some point over the coming vacation period.
