### ISSUE TITLE
Not able to install casks from internal source

### ISSUE THREAD

**Issue by umer-telenordigital** [Homebrew/brew#16726]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  android-sdk

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 15.1.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.9-77-gda44787
ORIGIN: https://github.com/Homebrew/brew
HEAD: da44787e941d1eeb0f392932968274bec29cd4b2
Last commit: 3 hours ago
Core tap JSON: 22 Feb 17:20 UTC
Core cask tap JSON: 22 Feb 17:20 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

We have configured an internal repo for some version clamped casks. The repo itself is stored in gitlab which is on-prem and artifacts are referenced in the artifactory which is on-prem as well. 
We have been installing casks from this repo without an issue until yesterday when this issue was discovered.  

### What happened (include all command output)?

brew install --cask si-perforce@2023.1.2468153 --debug --verbose
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.9-77-gda44787\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3\)\ curl/7.87.0 --header Accept-Language:\ en --fail --remote-time --output /Users/umer.ahmed/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/umer.ahmed/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.9-77-gda44787\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3\)\ curl/7.87.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::NullLoader): loading si-perforce@2023.1.2468153
Warning: Cask 'si-perforce@2023.1.2468153' is unavailable: No Cask with this name exists.
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.9-77-gda44787\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3\)\ curl/7.87.0 --header Accept-Language:\ en --fail --remote-time --output /Users/umer.ahmed/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/umer.ahmed/Library/Caches/Homebrew/api/formula.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.9-77-gda44787\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3\)\ curl/7.87.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> Searching for similarly named casks...
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::NullLoader): loading sigames/devops/si-perforce@2023.1.2468153
Error: Cask 'si-perforce@2023.1.2468153' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:521:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:530:in `load'
/opt/homebrew/Library/Homebrew/search.rb:96:in `block in search_casks'
/opt/homebrew/Library/Homebrew/search.rb:95:in `map'
/opt/homebrew/Library/Homebrew/search.rb:95:in `search_casks'
/opt/homebrew/Library/Homebrew/search.rb:115:in `search_names'
/opt/homebrew/Library/Homebrew/cmd/install.rb:381:in `rescue in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:166:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'

### What did you expect to happen?

The package should be installed without an issue, as nothing has changed with the repo, the casks or the artifactory and this has been working like this for a couple of years now 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I have checked to make sure that there is no issue brewing this internal tap:
>> brew tap sigames/devops https://homebrew-devops:<xxxxtokenxxxxx>@gitlab.sigames.com/devops/homebrew.git

==> Tapping sigames/devops
Cloning into '/opt/homebrew/Library/Taps/sigames/homebrew-devops'...
remote: Enumerating objects: 133, done.
remote: Total 133 (delta 0), reused 0 (delta 0), pack-reused 133
Receiving objects: 100% (133/133), 17.22 KiB | 5.74 MiB/s, done.
Resolving deltas: 100% (61/61), done.
Tapped 11 casks (23 files, 33.3KB).

>> brew tap
sigames/devops

>> brew install --cask si-perforce@2023.1.2468153 --debug --verbose
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::NullLoader): loading si-perforce@2023.1.2468153
Warning: Cask 'si-perforce@2023.1.2468153' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::NullLoader): loading sigames/devops/si-perforce@2023.1.2468153
Error: Cask 'si-perforce@2023.1.2468153' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:521:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:530:in `load'
/opt/homebrew/Library/Homebrew/search.rb:96:in `block in search_casks'
/opt/homebrew/Library/Homebrew/search.rb:95:in `map'
/opt/homebrew/Library/Homebrew/search.rb:95:in `search_casks'
/opt/homebrew/Library/Homebrew/search.rb:115:in `search_names'
/opt/homebrew/Library/Homebrew/cmd/install.rb:381:in `rescue in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:166:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

**Comment by reitermarkus** [comment]
Should be fixed by https://github.com/Homebrew/brew/pull/16689, which changed `HOMEBREW_TAP_CASK_REGEX` to allow `@` in cask tokens.
