### ISSUE TITLE
bump-formula-pr does not respect `HOMEBREW_GITHUB_API_TOKEN` when `--no-fork` is passed

### ISSUE THREAD

**Issue by fauxpark** [Homebrew/brew#16747]
### `brew doctor` output

```shell
Not applicable.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
Not applicable.
```

### What were you trying to do (and why)?

Use `brew bump-formula-pr`, in conjunction with the GitHub Action [dawidd6/action-homebrew-bump-formula](https://github.com/dawidd6/action-homebrew-bump-formula), to automatically create a PR in a tap without having the submitter fork the tap (it is a bot account which has push access to the repo, so it should not have any repos of its own).

### What happened (include all command output)?

The `git push` command fails the run with:
```
fatal: could not read Username for 'https://github.com/': Device not configured
```
https://github.com/qmk/homebrew-qmk/actions/runs/8044314448/job/21967712998

Apparently this is because `HOMEBREW_GITHUB_API_TOKEN` is never used when `--no-fork` is passed.

[In `create_bump_pr()` in `github.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github.rb#L652-L661), the remote URL is taken from the output of `git remote get-url --push origin` if `--no-fork` is passed. Otherwise, the remote URL is obtained from the result of `forked_repo_info()`, which [inserts the API token into the HTTPS clone URL](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github.rb#L605).

### What did you expect to happen?

A pull request should be created by `brew bump-formula-pr`, with its head branch on the same repo as the base branch.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Not applicable. See the workflow file here: https://github.com/qmk/homebrew-qmk/actions/runs/8044314448/workflow
```

**Comment by Bo98** [comment]
Nah you're good - it wasn't documented yet because it had only been discovered for a few hours prior and I hadn't gotten round to doing so yet.
