### ISSUE TITLE
I can't untap `homebrew/cask` and `homebrew/core` 

### ISSUE THREAD

**Issue by benbor** [Homebrew/brew#16761]
### `brew doctor` output

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  dozer

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-platformdirs
  php@7.4
  python-distlib

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  mono
  openssl@1.1
  php@7.4
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: c6d959218f143cd17b1fc3e0f10f143cbd273528
Last commit: 3 days ago
Core tap JSON: 28 Feb 11:00 UTC
Core cask tap JSON: 28 Feb 11:00 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```

### What were you trying to do (and why)?

I try to uninstall two taps "homebrew/cask", and "homebrew/core". 

### What happened (include all command output)?

brew untap homebrew/cask --debug
Error: No available tap homebrew/cask.
Run brew tap --force homebrew/cask to tap homebrew/cask!
/opt/homebrew/Library/Homebrew/cli/named_args.rb:330:in `block in to_installed_taps'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:329:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:329:in `to_installed_taps'
/opt/homebrew/Library/Homebrew/cmd/untap.rb:26:in `untap'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>' 

### What did you expect to happen?

I expect that the "homebrew/cask" tap will be uninstalled successfully 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
> brew tap
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/core 

> brew untap homebrew/cask
Error: No available tap homebrew/cask.
Run brew tap --force homebrew/cask to tap homebrew/cask!
```

**Comment by MikeMcQuaid** [comment]
It's already uninstalled.

**Comment by benbor** [comment]
@MikeMcQuaid  thanks for your answer. 

Could you please specify how did you figure it out? 

command `> brew tap` shows the following output
```bash
> brew tap
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/core 
```

And command `brew bundle` adds taps `homebrew/cask` and `homebrew/core` into Brewfile. 
Even I remove this two taps from Brewfile manually, `brew bundle cleanup` couldn't manage to deal with it 

```bash
> brew bundle cleanup
Would untap:
homebrew/cask
Run `brew bundle cleanup --force` to make these changes.

> brew bundle cleanup --force
Error: No available tap homebrew/cask.
Run brew tap --force homebrew/cask to tap homebrew/cask!
``` 

I'm sure it is still some bug with that two taps in my scenario.

**Comment by Bo98** [comment]
`brew tap` behaviour did indeed change in #16710. I agree it is perhaps unclear that `brew tap` shows things but `brew untap` says they never existed.

`brew cleanup` is a regression since #16710 involved API changes so everything that used it probably needs checking.

**Comment by MikeMcQuaid** [comment]
@benbor Apologies that I saw all except that they were still listed by `brew tap`.

@reitermarkus can you fix this regression, thanks.

**Comment by benbor** [comment]
@MikeMcQuaid  No problem

Thank you so much for maintaining Homebrew! Your hard work makes my daily routine much easier

**Comment by reitermarkus** [comment]
Will take a look.

So I guess it's only the error message that is unclear? Basically, you cannot untap `homebrew/cask` because it's always available when using the API.

**Comment by Bo98** [comment]
It's well-documented that running `brew tap` on `homebrew/core|cask` will give you a local git clone so the concept of "tapped" has largely been around that concept of having a local git clone. Similarly you run `brew untap` to get rid of a local git clone and return to API-only state.

`brew bundle` also seems to also now not work in API-only mode properly after the changes and wants to do a full tap/untap.

**Comment by reitermarkus** [comment]
So should we only show taps that have a local clone, or show something like

```
homebrew/core (using API)
```

?

**Comment by Bo98** [comment]
I'd say show taps with local clone. If you want API information, it maybe could be added with `--verbose` - I'm cautious adding it in regular output given `brew tap` is machine-parsable, as demonstrated by how `$(brew tap)` is used in our shell completions.

**Comment by madAndroid** [comment]
I've worked around the issue for now using:
```
brew tap --force homebrew/core
brew tap --force homebrew/cask
```
... but it would be good if `brew bundle dump` didn't create those entries in the `Brewfile`

**Comment by MikeMcQuaid** [comment]
> ... but it would be good if `brew bundle dump` didn't create those entries in the `Brewfile`

Opened https://github.com/Homebrew/homebrew-bundle/pull/1317 to address this.
