### ISSUE TITLE
-bash: brew: command not found after pkg install and adding brew shellenv to bash

### ISSUE THREAD

**Issue by Jarrod-RDS** [Homebrew/brew#16803]
### `brew doctor` output

```shell
I have read the above, but please understand the software is not working yet, I cannot produce output from non-functioning software. There are no other avenues for support except this github, so this is my only option.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
no output
```

### What were you trying to do (and why)?

use the software

### What happened (include all command output)?

vi .bash_profile
added 'brew shellenv' as the final line, saved.
$ source .bash_profile 
-bash: brew: command not found

I grabbed the full path to brew and edited .bash_profile last line to:
/opt/homebrew/bin/brew shellenv

I sourced the file again and was shown:
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

brew is still not found. 
$ brew help
-bash: brew: command not found
'which brew' returns null

if I echo $PATH the path does not show an entries for /opt/homebrew/bin or /opt/homebrew/sbin

I am trying to follow the Installation instructions but they are not working

Running the command directly produces same results
$ /opt/homebrew/bin/brew shellenv

I have looked in Common Issues, FAQ nothing there about this. The Installation document has zero information on this https://docs.brew.sh/Installation The final page of the pkg installer is what is instructing me to add this to add homebrew to path

If you expect user to manually edit their path because this 'shellenv' does nothing then please provide the steps you would like them to take in Installation document.

### What did you expect to happen?

the software to respond

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
see 'what happened' above for step by step
```

**Comment by Shaxzodbek16** [comment]
I have also the problem . What will I do to fix the problem?

**Comment by ZhongRuoyu** [comment]
You should add `eval "$(/opt/homebrew/bin/brew shellenv)"` to `~/.bash_profile` instead of plain `/opt/homebrew/bin/brew shellenv`.

**Comment by Shaxzodbek16** [comment]
Thank you much more. It works.

Dush, 4-mar, 2024, 03:29 Ruoyu Zhong ***@***.***>:

**Comment by Jarrod-RDS** [comment]
Ok to close. I see less people will have the same confusion moving forward with those commits to improve clarity of directions
