### ISSUE TITLE
Full disk access configuration

### ISSUE THREAD

**Issue by JoranHonig** [Homebrew/brew#16824]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I'm using brew service to manage sketchybar ( it's cool but not necessarily relevant to the feature suggestion ), and it uses a plugin I've written that requires Full Disk Access.

Unfortunately, enabling full disk access to the sketchybar binary has little effect, and it seems like the application starting it needs full disk access instead.

It would be ideal if brew was able to introduce an entry in the Privacy & Security > Full Disk Access menu to enable users to provide the necessary permissions.

### What is the motivation for the feature?

It would allow people to run services that require Full Disk Access permissions.

### How will the feature be relevant to at least 90% of Homebrew users?

🙈  it probably won't

### What alternatives to the feature have been considered?

None as far as I'm aware

**Comment by MikeMcQuaid** [comment]
> brew service to manage sketchybar

Do you mean `brew services`?

> It would be ideal if brew was able to introduce an entry in the Privacy & Security > Full Disk Access menu to enable users to provide the necessary permissions.

Homebrew does result in an entry here if you run it through your Terminal.

**Comment by JoranHonig** [comment]
> Do you mean `brew services`?

Yes!

> Homebrew does result in an entry here if you run it through your Terminal.

I'm not able to find this entry, what should it be called?

**Comment by MikeMcQuaid** [comment]
> > Homebrew does result in an entry here if you run it through your Terminal.
> 
> I'm not able to find this entry, what should it be called?

@JoranHonig It depends on whether or not Homebrew has had to read/write from a given location.

Passing on this, sorry; very unclear how Homebrew would implement this and feels more like an issue for the third-party software to solve. If there's a straightforward PR, though, will definitely review.

Sorry!
