### ISSUE TITLE
Implement POSIX compatibility into the install file allowing it to be installed into different shells other than BASH 

### ISSUE THREAD

**Issue by S0ulflared** [Homebrew/brew#16841]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

the install script currently uses bash, Im suggesting modifying the install script to support all shells

### What is the motivation for the feature?

trying to install homebrew on A-shell for iOS fails because it uses dash and not bash.

### How will the feature be relevant to at least 90% of Homebrew users?

homebrew users that don't have bash or ZSH as their main shell

### What alternatives to the feature have been considered?

honestly none.

**Comment by Bo98** [comment]
While we could port the install script, the problem is Homebrew itself uses Bash and does so a lot more heavily than the install script does.

**Comment by S0ulflared** [comment]
> The installer only supports the officially-supported configurations (x86_64 and arm64 macOS, x86_64 Linux). Also, Homebrew itself requires Bash (specifically `/bin/bash`), Ruby, etc., so even if you manage to install it somehow, you probably won't be able to run it.
> 
> 

I got it working on ISH
