### ISSUE TITLE
vim formula: create symlink vi -> vim

### ISSUE THREAD

**Issue by mcandre** [Homebrew/brew#1686]
Apple offers a built-in symlink from /usr/bin/vi -> (/usr/local/)vim, which presents a minor PATH resolution surprise. Brewers who try to launch Homebrew's `vim` by calling `vi`, may trigger the symlink, which lands you in an Apple `vim` console. Surprise, no `+clipboard` integration!

Could this formula get a similar symlink as a post-install step, for lazy typists?

**Comment by DomT4** [comment]
It's there as an option already: `--with-override-system-vi`.

**Comment by MikeMcQuaid** [comment]
Yes.

Also, please in future fill in the issue template which indicated that formulae-specific issues should be submitted to Homebrew/homebrew-core.
