### ISSUE TITLE
Always force overwrite links

### ISSUE THREAD

**Issue by JOJ0** [Homebrew/brew#16864]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I'm sorry for posting this as an issue here, I would have rather opened a discussion about it, if that where available here. Sorry again, you might not like that I'm simply asking a question and am not sure if I even have a feature request.

homebrew on my machine takes quite some time for any package to install. And after "minutes" or even hours it stops continuing because it asks me questions like this:

```
Error: Could not symlink include/textstyle/stdbool.h
Target /usr/local/include/textstyle/stdbool.h
is a symlink belonging to gettext. You can unlink it:
  brew unlink gettext

To force the link and overwrite all conflicting files:
  brew link --overwrite gettext

To list all files that would be deleted:
  brew link --overwrite gettext --dry-run
```

Which I always answer by tediously copying and pasting. Yes please overwrite, I don't care!

So what I'm asking myself is, is there any options that allow to simply tell brew to just always overwrite links? I tried this but it doesn't seem to work. I still get stops during longish runs:

```
brew install --quiet --overwrite --force somepackage
```

If such an "always overwrite links" option currently is not available then this would actually be the feature I would like to request. Thanks for you consideration! Please get back to me with any thoughts, improvement suggestions of my workflow or criticism on my report! All welcome! Thanks a lot for your time and efforts!

**Comment by carlocab** [comment]
> I'm sorry for posting this as an issue here, I would have rather opened a discussion about it, if that where available here.

We do have a [discussions page](https://github.com/orgs/Homebrew/discussions) for these sorts of questions.

Does `brew install --overwrite` and/or `brew upgrade --overwrite` not do what you need it to?

**Comment by cho-m** [comment]
Probably need a specific example in order to provide context. Like what exact command you were running when it errored and at least some command output before the error.

Without any extra info, I am guessing this is related to linking dependencies since I think `--overwrite` should work but only for input formula. If so, as far as I can tell, we don't support this. A hack would be passing in everything in dependency tree `$(brew deps ...)`, but that will result in a marking all formulae as `installed_on_request` and making it difficult to clean up no longer used formulae.

**Comment by JOJ0** [comment]
> > I'm sorry for posting this as an issue here, I would have rather opened a discussion about it, if that where available here.
> 
> 
> 
> We do have a [discussions page](https://github.com/orgs/Homebrew/discussions) for these sorts of questions.
> 
> 
> 
> Does `brew install --overwrite` and/or `brew upgrade --overwrite` not do what you need it to?

I'm very sorry I missed that discussions is open in this report. 

As said: install --overwrite still asks when dependency links are happening.

**Comment by MikeMcQuaid** [comment]
> As said: install --overwrite still asks when dependency link conflicts are happening.That usually happens with long running compiles. In the end it often takes me literally days to install one piece of software because every other dependency throws such a link overwrite conflict...

Can you be more specific here?

**Comment by JOJ0** [comment]
I'll post a report when not AFK

**Comment by MikeMcQuaid** [comment]
> Does that clarify what I'm asking?

Yes, thanks. It is indeed unexpected/a bug that `brew upgrade --overwrite` will not overwrite in this case. Reopening.

**Comment by cho-m** [comment]
```
==> Installing curl dependency: brotli
...
Possible conflicting files are:
/usr/local/bin/brotli -> /usr/local/Cellar/brotli/1.0.9/bin/brotli
```

This is confusing. Very strange that `brotli` can't handle `brotli`'s own files.

May need to understand your setup better with `brew config`/`brew doctor` output.
