### ISSUE TITLE
Is there any way to disable Auto-updating when installing a package? 

### ISSUE THREAD

**Issue by smartwjw** [Homebrew/brew#1687]
As we all know, China users face the problem of G.F.W. It's really slow for auto updating, I wonder is there is a way to disable this feature.

Thanks for your great work.

**Comment by dunn** [comment]
Yes, you can set `HOMEBREW_NO_AUTO_UPDATE` in your environment.

**Comment by smartwjw** [comment]
May be this should be documented in somewhere, I really did some googling before I open this issue.

**Comment by MikeMcQuaid** [comment]
It is: `man brew`.
