### ISSUE TITLE
`brew install` fails when there's a single visible directory and no other files at the top of a repository

### ISSUE THREAD

**Issue by thoran** [Homebrew/brew#16910]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  authy

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 15.1.


Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-mutagen
  python-brotli

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
  youtube-dl

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  handbrake

Warning: Your Xcode (14.2) is outdated.
Please update to Xcode 15.1 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 780fbbc65e90fbe09629aba180a1839e9e7dbaf2
Last commit: 8 days ago
Core tap JSON: 18 Mar 10:11 UTC
Core cask tap JSON: 18 Mar 10:11 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--appdir=~/Applications", "--fontdir=/Library/Fonts"]
HOMEBREW_DISPLAY: localhost:0.0
HOMEBREW_EDITOR: /usr/bin/vi
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.44.0 => /usr/local/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.2
```

### What were you trying to do (and why)?

`AbstractDownloadStrategy#chdir` changes the staging directory from the top of the repo to inside the bin directory unless I have a `README` or some other visible file (ie. a non `.` file). A formula directive such as:
```ruby
def install
  bin.install 'bin/whatever'
end
```
fails therefore.

### What happened (include all command output)?

It is no longer reproducible for my personal tap as I did a workaround for them all by putting a `README` at the top of the repo. It was reporting that it could find `bin/whatever` because it had `chdir`'d into `bin`. See https://github.com/thoran/homebrew-tap/blob/master/cases.rb, which points to https://github.com/thoran/cases for a case in point of the most recent change to the source repo that fixed it. I had this failing on 3 of my formulae and the same change fixed all of them.

### What did you expect to happen?

I expect that when I'm too lazy to write a README and I've only got `bin/whatever` in my repo that Homebrew doesn't shit itself when attempting to install `bin/whatever`.

I also expect to not be treated like a child and have to lie about these checkboxes: "My "brew doctor output" above says Your system is ready to brew. and am still able to reproduce my issue. *" and about "I ran brew update twice and am still able to reproduce my issue. *"

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap thoran/tap
brew install thoran/tap/whatever # but not any more because I did the aforementioned workaround.
```

**Comment by thoran** [comment]
The reason I raised this as an issue rather than put up a PR is due to being unsure about the use-case where this behaviour makes sense. Presumably there is such a use-case else the logic wouldn't be so explicit. I suspect that that use-case could be handled more narrowly so that what I want will work also.

**Comment by MikeMcQuaid** [comment]
The workaround is `bin.install "whatever"` in this case instead.

This `AbstractDownloadStrategy#chdir` behaviour has been around for a long time. If we change it now: it will break a bunch of formulae, sorry.

> Homebrew doesn't shit itself when attempting to install `bin/whatever`.
> I also expect to not be treated like a child

Please reread our Code of Conduct and adjust your tone accordingly in future: https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md
