### ISSUE TITLE
Proper XDG_CONFIG_HOME usage

### ISSUE THREAD

**Issue by azatoth** [Homebrew/brew#16931]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

if `$XDG_CONFIG_HOME`  is not set, then we should default it to  `$HOME/.config`, and for backward compatibility we should still check `$HOME/.homebrew/brew.env` if `$XDG_CONFIG_HOME/homebrew/brew.env` is missing.

### What is the motivation for the feature?

https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html states:
>  `$XDG_CONFIG_HOME` defines the base directory relative to which user-specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used. 

### How will the feature be relevant to at least 90% of Homebrew users?

Following established standards

### What alternatives to the feature have been considered?

ignoring established standards?

**Comment by carlocab** [comment]
See related discussion at https://github.com/Homebrew/brew/pull/15787#discussion_r1277694615.

**Comment by MikeMcQuaid** [comment]
We can't do this now without breaking backwards compatibility. 

People/places who care about `XDG_CONFIG_HOME` already set it and we respect it. If we don't: that's a bug. We're permanently a macOS package manager where freedesktop.org standards do not apply.

Passing on this, sorry.

**Comment by azatoth** [comment]
> We can't do this now without breaking backwards compatibility.

If you were still looking for `$HOME/.homebrew/brew.env` if the other file didn't exists, how would that break backward compatibility? The only scenario I can think of is if someone has a `$HOME/.config/homebrew/brew.env` but hasn't set `$XDG_CONFIG_HOME`, which wouldn't make much sense.

**Comment by azatoth** [comment]
> People/places who care about `XDG_CONFIG_HOME` already set it and we respect it

I think most people don't set `$XDG_CONFIG_HOME` if they are using the default `$HOME/.config`, but will still infer they are using it as it's part of their system.

**Comment by azatoth** [comment]
> Passing on this, sorry

@MikeMcQuaid I'd like you to reconsider this.

**Comment by MikeMcQuaid** [comment]
It's not just `brew.env` that uses this location, it's also used by `HOMEBREW_LIVECHECK_WATCHLIST` too.

`.config/` is not widely used on macOS and we're primarily a macOS package manager.

Adding a separately default location for Linux for these two files only in cases where the user or the system doesn't set `XDG_CONFIG_HOME` makes the code and documentation unnecessarily complex.

If you care: set `XDG_CONFIG_HOME`. If you don't: just use our default locations.

Alternatively, convince every other project I use that uses a `~/.something` e.g. RubyGems, rbenv, nodenv, npm, pyenv, Bash, ZSH, etc. to go use `.config` instead and, when they all do, we might too.
