### ISSUE TITLE
Auto disable hints if already exists the environment variable

### ISSUE THREAD

**Issue by kallookoo** [Homebrew/brew#16947]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

The idea is not to show the hint when there is any of the variables related to it.

For example, if HOMEBREW_AUTO_UPDATE_SECS or HOMEBREW_NO_AUTO_UPDATE is defined, it is understood that it is already configured and it does not make sense to show it.

### What is the motivation for the feature?

Keeping the console clean.

### How will the feature be relevant to at least 90% of Homebrew users?

By not having extra or unnecessary information, the command information can be seen more clearly.

### What alternatives to the feature have been considered?

You could add a check of the variables before displaying it.

**Comment by MikeMcQuaid** [comment]
Can you provide an example of the specific hints you're seeing that you don't want to?

**Comment by kallookoo** [comment]
Hi @MikeMcQuaid 

Sorry, but after checking it I have seen that in the brew.env file I misspelled the variable and after correcting it it is already hidden.

**Comment by skagedal** [comment]
I have `HOMEBREW_AUTO_UPDATE_SECS` set explicitly to 86400 (in my ~/.zshrc).

```
❯ echo $HOMEBREW_AUTO_UPDATE_SECS
86400
```

I was hoping that this would hide the specific hint about auto updates, while still providing me with other env hints that I might find useful. However, I still get the hint:

```
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

I also got this hint:

```
==> Running `brew cleanup coreutils`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```
In this case, there seems to be no explicit configuration to set get the install cleanups, but that could be used to silence the hints.

**Comment by skagedal** [comment]
Hmm, but I do see now [here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/update.sh#L632-L638) that the `HOMEBREW_AUTO_UPDATE_SECS ` hint should be hidden if explicitly set... so this might be an user error on my side as well, not sure how but looking at it :)

**Comment by skagedal** [comment]
Oh yes, the env var was not exported 🤦 – sorry about that. But how about the `HOMEBREW_NO_INSTALL_CLEANUP` case?

**Comment by MikeMcQuaid** [comment]
> If I read [the code](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cleanup.rb?rgh-link-date=2024-03-29T10%3A28%3A48Z#L215-L221) right, there is no way to silence just this warning without disabling the behavior. So that would be a feature request.

There is: set `HOMEBREW_NO_ENV_HINTS`, as the message says.

Passing on this, sorry.

**Comment by skagedal** [comment]
No, that also disables other hints? But I of course realize that this is a rather specific ask and I perfectly understand that you would pass on it. :)

**Comment by MikeMcQuaid** [comment]
> No, that also disables other hints?

Yes. We don't have hint-by-hint disabling, sorry.
