### ISSUE TITLE
Last digit of formula version number can be omitted when upgrading

### ISSUE THREAD

**Issue by nwhetsell** [Homebrew/brew#16942]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.13-140-g9a1793a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9a1793a5ad5f400df6c2d53166a507c19bd02f93
Last commit: 13 hours ago
Core tap HEAD: 273b1649085d6a66a8995ff235b2204e22a46980
Core tap last commit: 76 minutes ago
Core tap JSON: 23 Mar 15:17 UTC
Core cask tap HEAD: 7e6b88eb16e6ac9e076415e2b445174e039b764a
Core cask tap last commit: 2 hours ago
Core cask tap JSON: 23 Mar 15:17 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 13.6.5-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```

### What were you trying to do (and why)?

Upgrade a formula ([lilypond-unstable](https://github.com/nwhetsell/homebrew-lilypond/blob/63e46c3990e145a671cd791ee4a3f1641cb12c5b/Formula/lilypond-unstable.rb)) from a non-Homebrew tap (https://github.com/nwhetsell/homebrew-lilypond).

### What happened (include all command output)?

The last digit of the new version number was omitted (under `==> Upgrading nwhetsell/lilypond/lilypond-unstable`)

<pre>
% brew upgrade lilypond-unstable     
==> Upgrading 1 outdated package:
nwhetsell/lilypond/lilypond-unstable <strong>2.25.13 -> 2.25.14</strong>
==> Fetching nwhetsell/lilypond/lilypond-unstable
==> Downloading https://github.com/ArtifexSoftware/urw-base35-fonts/archive/refs
Already downloaded: /Users/nathanwhetsell/Library/Caches/Homebrew/downloads/12fa9f20d07e79df9aa22021608f4e04436eb3440c72fcbe19853ec30fd576a1--urw-base35-fonts-20200910.tar.gz
==> Downloading https://lilypond.org/download/source/v2.25/lilypond-2.25.14.tar.
Already downloaded: /Users/nathanwhetsell/Library/Caches/Homebrew/downloads/3fab9b898b80ac147aeb75d204c1e6da366cab20f95e64a55055f89a2686f79f--lilypond-2.25.14.tar.gz
==> Upgrading nwhetsell/lilypond/lilypond-unstable
  <strong>2.25.13 -> 2.25.1</strong>
==> ./configure --datadir=/opt/homebrew/Cellar/lilypond-unstable/2.25.14/share -
==> make
==> make install
==> make bytecode
==> make install-bytecode
==> Caveats
lilypond-unstable is keg-only, which means it was not symlinked into /opt/homebrew,
because this is an alternate version of another formula.

If you need to have lilypond-unstable first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/lilypond-unstable/bin:$PATH"' >> ~/.zshrc

For compilers to find lilypond-unstable you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/lilypond-unstable/lib"
==> Summary
🍺  /opt/homebrew/Cellar/lilypond-unstable/2.25.14: 454 files, 29MB, built in 44 seconds
==> Running `brew cleanup lilypond-unstable`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/lilypond-unstable/2.25.13... (454 files, 29MB)
Removing: /Users/nathanwhetsell/Library/Caches/Homebrew/lilypond-unstable--2.25.13.tar.gz... (18.4MB)
</pre>

### What did you expect to happen?

The full version number of the formula to be displayed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap nwhetsell/lilypond
git -C $(brew --repo nwhetsell/lilypond) checkout c0cc594546d2667f4ec498c8ae9ed6aaf509a3f9
HOMEBREW_NO_AUTO_UPDATE=1 brew install lilypond-unstable
git -C $(brew --repo nwhetsell/lilypond) checkout main
brew upgrade lilypond-unstable
```

**Comment by MikeMcQuaid** [comment]
Cannot reproduce:

```
mikebook # brew upgrade lilypond-unstable                                                  
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#=#=- #                                                                                              
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#=#=- #                                                                                              
==> Upgrading 1 outdated package:
nwhetsell/lilypond/lilypond-unstable 2.25.13 -> 2.25.14
==> Fetching nwhetsell/lilypond/lilypond-unstable
==> Downloading https://github.com/nwhetsell/homebrew-lilypond/releases/download/lilypond-unstable-2.2
^CAlready downloaded: /opt/workbrew/home/Library/Caches/Homebrew/downloads/a4adb36076d79d01ef065b9c904b0e7085b7557be98daba79c1a35d5fc2aede1--lilypond-unstable-2.25.14.arm64_sonoma.bottle.tar.gz
==> Upgrading nwhetsell/lilypond/lilypond-unstable
  2.25.13 -> 2.25.14 
```

> * This issue's title and/or description do not reference a single formula e.g. `brew install wget`.

Please ensure you can reproduce this sort of things with multiple core formulae in future.

**Comment by nwhetsell** [comment]
@MikeMcQuaid Thank you for taking a look at this and for all your work on Homebrew.

I’m not sure why this wasn’t reproducible (sorry about that!), but having taken a closer look, the nature of (what seems to be) the issue suggests that it may not be possible to reproduce this with core formulae, because there is no core formula with a sufficiently long name. The fundamental issue appears to be that a string that contains a newline is passed to [`Tty.truncate`](https://github.com/Homebrew/brew/blob/4.2.15/Library/Homebrew/utils/tty.rb#L69), which then truncates the string as if it was too long for a terminal.

It looks like the affected upgrade message is printed [here](https://github.com/Homebrew/brew/blob/4.2.15/Library/Homebrew/upgrade.rb#L139-L142):

```rb
oh1 <<~EOS
  Upgrading #{Formatter.identifier(formula.full_specified_name)}
    #{version_upgrade} #{fi_options.to_a.join(" ")}
EOS
```

`oh1` passes its argument to `oh1_title` [here](https://github.com/Homebrew/brew/blob/4.2.15/Library/Homebrew/extend/kernel.rb#L57-L59):

```rb
def oh1(title, truncate: :auto)
  puts oh1_title(title, truncate:)
end
```

`oh1_title` passes the `title` argument to [`Tty.truncate`](https://github.com/Homebrew/brew/blob/4.2.15/Library/Homebrew/utils/tty.rb#L69) [here](https://github.com/Homebrew/brew/blob/4.2.15/Library/Homebrew/extend/kernel.rb#L53):

```rb
title = Tty.truncate(title.to_s) if $stdout.tty? && !verbose && truncate == :auto
```

In this case, the `title` being truncated is

```
Upgrading nwhetsell/lilypond/lilypond-unstable
  2.25.13 -> 2.25.14 
```

That’s 68 characters (note the space character after the version number on the 2nd line). However, there are 5 more characters after `Upgrading ` for the ANSI escape of green, and an additional 5 characters to restore text color at the end of the first line. With the newline at the end of the string, that brings the total to 79 characters:

<details>
<summary>Characters</summary>
<table>
<tr><th>Character index</th><th>ASCII code (decimal)</th><th>Character</th></tr>
<tr><td>	0	</td><td>	85	</td><td>	U	</td></tr>
<tr><td>	1	</td><td>	112	</td><td>	p	</td></tr>
<tr><td>	2	</td><td>	103	</td><td>	g	</td></tr>
<tr><td>	3	</td><td>	114	</td><td>	r	</td></tr>
<tr><td>	4	</td><td>	97	</td><td>	a	</td></tr>
<tr><td>	5	</td><td>	100	</td><td>	d	</td></tr>
<tr><td>	6	</td><td>	105	</td><td>	i	</td></tr>
<tr><td>	7	</td><td>	110	</td><td>	n	</td></tr>
<tr><td>	8	</td><td>	103	</td><td>	g	</td></tr>
<tr><td>	9	</td><td>	32	</td><td>		</td></tr>
<tr><td>	10	</td><td>	27	</td><td>	ESC	</td></tr>
<tr><td>	11	</td><td>	91	</td><td>	[	</td></tr>
<tr><td>	12	</td><td>	51	</td><td>	3	</td></tr>
<tr><td>	13	</td><td>	50	</td><td>	2	</td></tr>
<tr><td>	14	</td><td>	109	</td><td>	m	</td></tr>
<tr><td>	15	</td><td>	110	</td><td>	n	</td></tr>
<tr><td>	16	</td><td>	119	</td><td>	w	</td></tr>
<tr><td>	17	</td><td>	104	</td><td>	h	</td></tr>
<tr><td>	18	</td><td>	101	</td><td>	e	</td></tr>
<tr><td>	19	</td><td>	116	</td><td>	t	</td></tr>
<tr><td>	20	</td><td>	115	</td><td>	s	</td></tr>
<tr><td>	21	</td><td>	101	</td><td>	e	</td></tr>
<tr><td>	22	</td><td>	108	</td><td>	l	</td></tr>
<tr><td>	23	</td><td>	108	</td><td>	l	</td></tr>
<tr><td>	24	</td><td>	47	</td><td>	/	</td></tr>
<tr><td>	25	</td><td>	108	</td><td>	l	</td></tr>
<tr><td>	26	</td><td>	105	</td><td>	i	</td></tr>
<tr><td>	27	</td><td>	108	</td><td>	l	</td></tr>
<tr><td>	28	</td><td>	121	</td><td>	y	</td></tr>
<tr><td>	29	</td><td>	112	</td><td>	p	</td></tr>
<tr><td>	30	</td><td>	111	</td><td>	o	</td></tr>
<tr><td>	31	</td><td>	110	</td><td>	n	</td></tr>
<tr><td>	32	</td><td>	100	</td><td>	d	</td></tr>
<tr><td>	33	</td><td>	47	</td><td>	/	</td></tr>
<tr><td>	34	</td><td>	108	</td><td>	l	</td></tr>
<tr><td>	35	</td><td>	105	</td><td>	i	</td></tr>
<tr><td>	36	</td><td>	108	</td><td>	l	</td></tr>
<tr><td>	37	</td><td>	121	</td><td>	y	</td></tr>
<tr><td>	38	</td><td>	112	</td><td>	p	</td></tr>
<tr><td>	39	</td><td>	111	</td><td>	o	</td></tr>
<tr><td>	40	</td><td>	110	</td><td>	n	</td></tr>
<tr><td>	41	</td><td>	100	</td><td>	d	</td></tr>
<tr><td>	42	</td><td>	45	</td><td>	-	</td></tr>
<tr><td>	43	</td><td>	117	</td><td>	u	</td></tr>
<tr><td>	44	</td><td>	110	</td><td>	n	</td></tr>
<tr><td>	45	</td><td>	115	</td><td>	s	</td></tr>
<tr><td>	46	</td><td>	116	</td><td>	t	</td></tr>
<tr><td>	47	</td><td>	97	</td><td>	a	</td></tr>
<tr><td>	48	</td><td>	98	</td><td>	b	</td></tr>
<tr><td>	49	</td><td>	108	</td><td>	l	</td></tr>
<tr><td>	50	</td><td>	101	</td><td>	e	</td></tr>
<tr><td>	51	</td><td>	27	</td><td>	ESC	</td></tr>
<tr><td>	52	</td><td>	91	</td><td>	[	</td></tr>
<tr><td>	53	</td><td>	51	</td><td>	3	</td></tr>
<tr><td>	54	</td><td>	57	</td><td>	9	</td></tr>
<tr><td>	55	</td><td>	109	</td><td>	m	</td></tr>
<tr><td>	56	</td><td>	10	</td><td>	LF	</td></tr>
<tr><td>	57	</td><td>	32	</td><td>		</td></tr>
<tr><td>	58	</td><td>	32	</td><td>		</td></tr>
<tr><td>	59	</td><td>	50	</td><td>	2	</td></tr>
<tr><td>	60	</td><td>	46	</td><td>	.	</td></tr>
<tr><td>	61	</td><td>	50	</td><td>	2	</td></tr>
<tr><td>	62	</td><td>	53	</td><td>	5	</td></tr>
<tr><td>	63	</td><td>	46	</td><td>	.	</td></tr>
<tr><td>	64	</td><td>	49	</td><td>	1	</td></tr>
<tr><td>	65	</td><td>	51	</td><td>	3	</td></tr>
<tr><td>	66	</td><td>	32	</td><td>		</td></tr>
<tr><td>	67	</td><td>	45	</td><td>	-	</td></tr>
<tr><td>	68	</td><td>	62	</td><td>	>	</td></tr>
<tr><td>	69	</td><td>	32	</td><td>		</td></tr>
<tr><td>	70	</td><td>	50	</td><td>	2	</td></tr>
<tr><td>	71	</td><td>	46	</td><td>	.	</td></tr>
<tr><td>	72	</td><td>	50	</td><td>	2	</td></tr>
<tr><td>	73	</td><td>	53	</td><td>	5	</td></tr>
<tr><td>	74	</td><td>	46	</td><td>	.	</td></tr>
<tr><td>	75	</td><td>	49	</td><td>	1	</td></tr>
<tr><td>	76	</td><td>	52	</td><td>	4	</td></tr>
<tr><td>	77	</td><td>	32	</td><td>		</td></tr>
<tr><td>	78	</td><td>	10	</td><td>	LF	</td></tr>
</table>
</details>

A common terminal width is 80 characters (the [default width in `Tty`](https://github.com/Homebrew/brew/blob/4.2.15/Library/Homebrew/utils/tty.rb#L63)), and `Tty.truncate` removes the last 4 characters of a string when it truncates. When the affected message is truncated to 76 characters, the last character (at index 75) happens to be the penultimate digit of the new version number, so it appears that the last digit is omitted.

**Comment by apainintheneck** [comment]
> That’s 68 characters (note the space character after the version number on the 2nd line). However, there are 5 more characters after `Upgrading ` for the ANSI escape of green, and an additional 5 characters to restore text color at the end of the first line. With the newline at the end of the string, that brings the total to 79 characters:

Ideally we wouldn't count non-printable characters when deciding where to truncate strings but that's not the main issue here.
