### ISSUE TITLE
Allow checksum on unversioned URL

### ISSUE THREAD

**Issue by krystof-k** [Homebrew/brew#16956]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I don't think requiring version URL for allowing checksum (as done in #9493 and discussed in homebrew/homebrew-cask#94253) while allowing version number is a correct approach.

```shell
Use `sha256 :no_check` when URL is unversioned.
```

It is removing a security feature which is beneficial even for formulas with an unversioned URL.

### What is the motivation for the feature?

Here is my case. There is an app named _eObčanka_, basically a driver for electronic ID card in the Czech Republic, issued by the government. So a pretty security-sensitive thing.

They always publish only the latest version of the app on the same URL and the checksum is presented below the download link on the [official government website](https://info.identitaobcana.cz/download/#macOS).

As a user, I want to be sure that I always install the official, government-issued version, whose checksum can be easily checked on the official website from a trusted network when manually merging the PR.

### How will the feature be relevant to at least 90% of Homebrew users?

It is relevant to 100% of Homebrew users who wants to be sure they install the actual, manually approved version of an app.

### What alternatives to the feature have been considered?

Forcing the government to publish older versions – impossible.

**Comment by krystof-k** [comment]
Now, it also results in installing a different (newer) version than the one actually listed in the cask.

I really don't see a reasoning behind this, and if there is, then it should not be allowed to use `version` stanza for unversioned URLs as well.

**Comment by bevanjkay** [comment]
We cannot use a checksum when the `url` does not include the version.
Every time the vendor updates the software, the cask will fail on installation or upgrade because the checksum will mismatch. When the `url` includes a `version`, the install/upgrade will work successfully as it will install/upgrade the version that the cask is pointing to.

**Comment by krystof-k** [comment]
Yes, that is expected, as if the checksum changes, it means the version changed, and it should fail, otherwise it will install a different version than is specified in the formula.

**Comment by bevanjkay** [comment]
When there is no versioned `url` available this is the expected behaviour.

**Comment by krystof-k** [comment]
It is wrong behavior. Have you read my comment above?

**Comment by MikeMcQuaid** [comment]
> It is wrong, unsafe behavior. Have you read my comment above?

@krystof-k Please adjust your tone. That's just your opinion and we disagree.

In this case: the issue is with the government distribution of this file not following standard practises of not changing URLs you want to be checksummed. This also makes this hard to cache.

**Comment by krystof-k** [comment]
Sorry, I meant no offense, it just felt like copy-paste replies ignoring the context I described.

I of course agree with this, but you can hardly change this on the vendor side, so the design should consider that we live in the real world.

The current behavior results in installing different version than is specified in the formula. That's not my opinion, it's a fact. I don't know ho is "we", but I don't like closing the issue without any open discussion about this security issue nor any arguments defending the existing situation.

If you don't want for some reason it to *fail on installation or upgrade because the checksum will mismatch*, then there may be other ways how to handle this. For example forbidding using version without versioned URL, adding some `--fail-on-checksum-mismatch` flag for users who want security, etc.

**Comment by krystof-k** [comment]
Also I just found an (locked?) old issue homebrew/homebrew-cask#43822 from 2018 discussing similar thing, quoting:

> As stated, we don’t version casks with unversioned URLs because they tend to break with some frequency. The reason we still version casks with an appcast but unversioned URL is that with an (eventual) automated system in place, we’ll catch those updates more frequently, and the cask won’t break as much.

Which makes sense, but is probably no longer true as the checksum is disallowed without versioned URL.

**Comment by MikeMcQuaid** [comment]
> Sorry, I meant no offense

Thanks for apologising ❤️ 

> but you can hardly change this on the vendor side, so the design should consider that we live in the real world.

The "vendor" here almost certainly has fewer users of this software than Homebrew does so I reject the argument that Homebrew must be the ones to change here.

> I don't know who is "we"

The Homebrew maintainers.

> I don't like closing the issue without any open discussion about this security issue

We are having a discussion. Issues can be closed and reopened without anything changing in the universe.

You asked for the behaviour to change: we disagreed with your reasoning and said no.

I also consider the upstream project to be the ones with poor security practises here. As you've said: we live in the real world and Homebrew has to adapt to that.

In this case: getting a "this cask is broken!" report every time the government here changes things is not tenable for us, hence this workaround. This pattern is fairly commonplace so we behave the way we do.

If you really want to get into the security side here: it's unclear how publishing a checksum on the same site as the package solves anything except a potential MITM (which could just as easily change the checksum, too).

> then there may be other ways how to handle this.

In your case the best way to handle this is:
1) don't use the cask or
2) convince the government to change their practises here

You're asking us to do something which seems to provide no security benefit but will require extra work on our part. Sorry, no.

**Comment by krystof-k** [comment]
Thanks for you comprehensive answer. This issue is not about this one app. I intentionally used the word _vendor_ because there are for sure tens or hundreds of formulas with the same issue.

Let's wrap this up, I tried to express my reasoning behind this as well as I can, maybe someone else will do better.

My last question is not related to the security. Is the situation when user installs a different version than is specified in the cask intentional?

Maybe at least a warning on the formulae site for such formulas would be reasonable (I can try to open a PR).

And yeah, I will try to convince the government, but… ;)

**Comment by MikeMcQuaid** [comment]
> there are for sure tens or hundreds of formulas with the same issue.

This issue only affects casks, not formulae.

Yes, as mentioned above: we're aware if affects other casks. In this case the question is "do the volunteer/unsalaried Homebrew maintainers take on additional burden for little-or-no security benefit when the (often salaried) upstream/vendor could fix it more easily on their end?" and the answer is: "not just now, no".

> Is the situation when user installs a different version than is specified in the cask intentional?

In some cases, such as this: yes.

> Maybe at least a warning on the formulae site for such formulas would be reasonable (I can try to open a PR).

I don't think the warning is necessary, thanks for the offer though.
