### ISSUE TITLE
Show disk space in info command

### ISSUE THREAD

**Issue by ok-coder1** [Homebrew/brew#16967]
### Verification

- [X] This issue's title and/or description do not reference a single formula.

### Provide a detailed description of the proposed feature

This feature will show how much disk space formulaes or casks use. When `brew info <formula>` is used it should also show a line of how much disk space it uses.

### What is the motivation for the feature?

I was installing `llvm` without knowing that it will take 1-3 GB of disk space. If `brew info llvm` had shown the disk space that it is going to use, I would have resorted to `gcc`.

### How will the feature be relevant to at least 90% of Homebrew users?

This feature will be useful if people want to install a formulae but don't know what is the size.

### What alternatives to the feature have been considered?

Opening Finder and checking the space

**Comment by MikeMcQuaid** [comment]
```console
$ brew info wget
==> wget: stable 1.24.5 (bottled), HEAD
Internet file retriever
https://www.gnu.org/software/wget/
/opt/homebrew/Cellar/wget/1.24.5 (91 files, 4.5MB) *
```

It does show the space but only after installation.

We don't have a way of showing the extracted size after installation because of how our API/bottling infrastructure/etc. interact.

Would the size of the compressed tarball be useful to you? That's something it might be possible to show.

**Comment by ok-coder1** [comment]
> Would the size of the compressed tarball be useful to you? That's something it might be possible to show.

Yeah, you can also add like `Compressed size (tarball size) : ** MB`.

**Comment by ok-coder1** [comment]
Or before downloading the formula it will ask for a confirmation before downloading/installing them, like `apt`.

**Comment by ok-coder1** [comment]
> We don't have a way of showing the extracted size after installation because of how our API/bottling infrastructure/etc. interact.

You mean before.

**Comment by MikeMcQuaid** [comment]
@ok-coder1 How useful would that be? We'd probably only be able to get that after it's been downloaded or by reaching out to the server to query an individual formula's download size.
