### ISSUE TITLE
Allow macos 11 to be used

### ISSUE THREAD

**Issue by TGreat2014** [Homebrew/brew#16961]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

i cant use homebrew on macos11

### What is the motivation for the feature?

to let macos 11 users use homebrew

### How will the feature be relevant to at least 90% of Homebrew users?

its only relevant to macos 11 users

### What alternatives to the feature have been considered?

none

**Comment by ok-coder1** [comment]
If you have an issue, please open an issue instead.
