### ISSUE TITLE
Expect full list of removals to be resolved before blocking a remove

### ISSUE THREAD

**Issue by adamv** [Homebrew/brew#1696]
When trying to remove multiple formulae `a` and `b`, where `a` depends on `b`, removal of `b` is blocked even if `a` is the only usage.

```
$ brew rm cmus libcue
Error: Refusing to uninstall /Users/adamv/homebrew/Cellar/libcue/1.4.0
because it is required by cmus, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies libcue
```

Expected behavior is that the full list of removals is resolved before deciding to block a removal.

**Comment by adamv** [comment]
This looks like a duplicate of #1524.

**Comment by MikeMcQuaid** [comment]
Yeh, gonna close as a dupe. Glad to see you around these parts though @adamv!
