### ISSUE TITLE
Allow formulae to set an env for their completion generation

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/brew#16963]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

This proposal would add an option to the `generate_completions_from_executable` that would accept a hash of environment variables to set for the duration of its `safe_popen_read` invocation. The completion-generation helper currently sets the popen_env with a single variable (`SHELL`). This change would allow formulae the ability to add other environment variables that may be required by the completion command.

Possible implementation:

```diff
   sig {
     params(commands: T.any(Pathname, String), base_name: String, shells: T::Array[Symbol],
+           command_env: T::Hash[String, String],
            shell_parameter_format: T.nilable(T.any(Symbol, String))).void
   }
   def generate_completions_from_executable(*commands,
                                            base_name: name,
+                                           command_env: {},
                                            shells: [:bash, :zsh, :fish],
                                            shell_parameter_format: nil)
     completion_script_path_map = {
       bash: bash_completion/base_name,
       zsh:  zsh_completion/"_#{base_name}",
       fish: fish_completion/"#{base_name}.fish",
     }

     shells.each do |shell|
-      popen_read_env = { "SHELL" => shell.to_s }
+      popen_read_env = { "SHELL" => shell.to_s }.merge(command_env)
       script_path = completion_script_path_map[shell]
```

### What is the motivation for the feature?

While attempting to leverage `generate_completions_from_executable`, I have come across some formulae whose completion command _requires_ some particular environment variables to be set. These environment variables are documented as required when _using_ the tool, but naturally are not set within homebrew's build environment.

What's more frustrating (from the tool), is that these environment variables cannot be passed as arguments to the command, which means the completion-generation helper can't be used in its current form for these tools.

### How will the feature be relevant to at least 90% of Homebrew users?

The benefit of this feature would enable more formulae to leverage homebrew's completion helper. In particular, this would allow more formulae to lean on the established convention for their completions and not require the formulae to run bespoke operations that are effectively "generate_completions_from_executable + environment".

This should hopefully allow more formulae to provide completions, while remaining simplified in their formula code.

### What alternatives to the feature have been considered?

The underlying problem is really a limitation of the tools themselves. (The fact their completion commands require particular environment variables is a deficiency in their CLI. All the more deficient that the same vars can't be passed as simple CLI options.) However, it's not feasible to fix every upstream tool's CLI just to enable a package manager's utility.

Another option is to require the formulae to workaround the tool's limitation by leveraging `env` as the completion command. (eg:
```rb
generate_completions_from_executable("env", "WORK_DIR_PATH=#{Dir.home}",
                                     bin/"halo", "completion")
```

This actually works and is feasible. However, it clutters the formula code in a way that obfuscates the actual completion command. I think it would be more clear in a declarative way to accept the required environment as an option. Additionally, accepting it as an option allows homebrew to do further sanitization or filtering for security purposes (if necessary or desired). Requiring formulae to use `env` encourages more formulae to sidestep brew's safety mechanisms instead of making it easier to remain on the paved path.

**Comment by MikeMcQuaid** [comment]
Thanks for the issue!

This API seems reasonable although unclear if it would be a major improvement over just `ENV["whatever"] = "something"` in the formula itself.

Do you have any homebrew/core formulae that would need this?

**Comment by jasonkarns** [comment]
> This API seems reasonable although unclear if it would be a major improvement over just ENV["whatever"] = "something" in the formula itself.

I didn't even think of that! Hrm, the simplicity of that might be enough to not bother with changing the completion-helper api.

One downside is the "blast radius" of the `ENV=` approach extends beyond only the completion command. But in practice, I assume that helper is typically invoked at the very end of `install` anyway, so it's fine.

> Do you have any homebrew/core formulae that would need this?
The only two formulae I ran into are both private taps. Though I haven't looked in core for other potential candidates.

Honestly, I think I'm satisfied to close this and just set ENV as you suggested. I'll try that in our taps and circle back.

**Comment by cho-m** [comment]
> One downside is the "blast radius" of the `ENV=` approach extends beyond only the completion command.

There is also `with_env`, e.g.
```rb
with_env(VAR1: ..., VAR2: ...) do
  generate_completions_from_executable(...)
end
```

> Though I'm not certain how much stuff homebrew does after `#install` is invoked that could be affected.

Should be pretty much nothing. Looks like only writing metadata files which shouldn't be impacted by `ENV`.

https://github.com/Homebrew/brew/blob/c3094acbaf2b0a89bf7f80de93b1e33f6bced925/Library/Homebrew/build.rb#L179-L187

**Comment by jasonkarns** [comment]
@cho-m oh yeah, that's perfect.

Closing in favor of 'with_env'. thank you both!
