### ISSUE TITLE
netpbm missing shared library link

### ISSUE THREAD

**Issue by iltommi** [Homebrew/brew#1697]
When Installing netpbm, I get these libs installed in `/usr/local/lib` : 

``` bash
libnetpbm.a -> ../Cellar/netpbm/10.76_1/lib/libnetpbm.a
libnetpbm.11.dylib -> ../Cellar/netpbm/10.76_1/lib/libnetpbm.11.dylib
libnetpbm.11.75.dylib -> ../Cellar/netpbm/10.76_1/lib/libnetpbm.11.75.dylib
```

As you can see There is a static lib and a shared lib but it's lacking the 

```bash
libnetpbm.dylib -> ../Cellar/netpbm/10.76_1/lib/libnetpbm.11.75.dylib
```
Is there a reason for this? 
would it be possible to install the missing link?

**Comment by MikeMcQuaid** [comment]
You didn't follow or read our issue template so closing this, sorry.
