### ISSUE TITLE
Fine-grained PATs do not work when used as $HOMEBREW_GITHUB_API_TOKEN

### ISSUE THREAD

**Issue by bartekpacia** [Homebrew/brew#16978]
### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 4.2.15-53-g02a0ea8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 02a0ea84492f07d5d3522ba45958166ec0d5481b
Last commit: 14 hours ago
Core tap JSON: 30 Mar 14:21 UTC
Core cask tap JSON: 30 Mar 14:21 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_BAT_CONFIG_PATH: /Users/bartek/.config/bat/bat.conf
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: micro
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_EMOJI: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### What were you trying to do (and why)?

I am trying to use `brew bump-formula-pr` to automate creating a PR that updates a formula in my personal tap.

### What happened (include all command output)?

```
$ brew bump-formula-pr \
    --no-audit \
    --no-browse \
    --message "scripts 0.4.10" \
    --tag "v0.4.10" \
    --revision "$(git rev-parse HEAD)" \
    --force \
    bartekpacia/homebrew-tools/scripts
==> replace /tag:(\s+")v0.4.9(?=")/ with "tag:\\1v0.4.10\\2"
==> replace "a8de90aae81ac40a479ab65b2298412478acb297" with "a8de90aae81ac40a479ab65b2298412478acb297"
==> Skipping `brew audit`
Error: Unable to fork: GitHub API Error: Resource not accessible by personal access token
HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
  https://github.com/settings/tokens
!
```

### What did you expect to happen?

I expect "fine-grained" GitHub PATs to work the same as "classic" PATs.

Important to know:

- "classic" PATs start with `ghp_`
- "fine-grained" PATs start with `github_pat_`

([source](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats))

But [The regex used by Homebrew to check if PAT is a valid one](https://github.com/Homebrew/brew/blob/4.2.15/Library/Homebrew/utils/github/api.rb#L30) does not match `github_pat_`.

### Step-by-step reproduction instructions (by running `brew` commands)

Reproducing this issue requires:
- generating and setting a fine-grained GitHub PAT as `HOMEBREW_GITHUB_API_TOKEN` ([guide](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token))
- a tap repo with formula that you want to update. In my case, my tap repo is [`bartekpacia/homebrew-tools`](https://github.com/bartekpacia/homebrew-tools), and inside this repo is the [`scripts`](https://github.com/bartekpacia/homebrew-tools/blob/d7099482b71f45c5c03851cfb8c4cbb2300fe89c/Formula/scripts.rb) formula.

**Step 1**

```console
export HOMEBREW_GITHUB_API_TOKEN="github_pat_..."
```

**Step 2**

```
brew update-reset
```

**Step 3**

```
$ brew bump-formula-pr \
         --no-audit \
         --no-browse \
         --message "scripts 0.4.10" \
         --tag "v0.4.10" \
         --revision "$(git rev-parse HEAD)" \
         --force \
         bartekpacia/homebrew-tools/scripts
==> replace /tag:(\s+")v0.4.9(?=")/ with "tag:\\1v0.4.10\\2"
==> replace "a8de90aae81ac40a479ab65b2298412478acb297" with "a8de90aae81ac40a479ab65b2298412478acb297"
==> Skipping `brew audit`
Error: Unable to fork: GitHub API Error: Resource not accessible by personal access token
HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
  https://github.com/settings/tokens
!
```

**Comment by bartekpacia** [comment]
I'm no regex expert - what would be the best way to update it to also match `github_pat`?

```
GITHUB_PERSONAL_ACCESS_TOKEN_REGEX = /^(?:[a-f0-9]{40}|gh[po]_\w{36,251})$/
```

Maybe it's better to create a new regex for fine-grainted PATs?

Anyway, I am willing to contribute this small fix. 

And huge thank you, maintainers of the Homebrew project.

**Comment by Bo98** [comment]
Swapping `gh[po]_` with `(?:gh[po]|github_pat)_` should work

**Comment by bartekpacia** [comment]
It does! Thanks:)
