### ISSUE TITLE
Support GitHub App installation access tokens

### ISSUE THREAD

**Issue by toobuntu** [Homebrew/brew#17000]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

In a GitHub Action workflow, one can authenticate with a GitHub App installation access token. This allows fine-grained permissions not possible with classic PATs, similar to the new fine-grained PATs. However, fine-grained PATs are not yet supported in certain use cases where GitHub App tokens are. Additional benefits are time-limited tokens and tokens with restricted scope (to a repo, org, etc.).

This blog post describes the token formats:
https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/

The Docs do, too:
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats

GitHub App installation access tokens have the `ghs_` prefix.

It seems changing the [regex used by Homebrew to validate tokens](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github/api.rb#L30 "https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github/api.rb#L30") from `gh[po]` to `gh[pos]` or `gh[pours]` would resolve this, but haven't tested it.

```bash
GITHUB_PERSONAL_ACCESS_TOKEN_REGEX = /^(?:[a-f0-9]{40}|(?:gh[pours]|github_pat)_\w{36,251})$/
```

More info: https://learn.microsoft.com/en-us/purview/sit-defn-github-personal-access-token

### What is the motivation for the feature?

To use a GitHub App installation access token in a GitHub Action workflow to run `brew bump` on a cask in a self-hosted tap.

### How will the feature be relevant to at least 90% of Homebrew users?

Extends the API token formats possible to be used with Homebrew to include GitHub App tokens. These can be used in GitHub Action workflows with fine-grained permissions and can be scoped to specific repositories.

### What alternatives to the feature have been considered?

Manually bumping the cask version and sha based on information known to the tap repo.

**Comment by carlocab** [comment]
> It seems changing the [regex used by Homebrew to validate tokens](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github/api.rb#L30) from `gh[po]` to `gh[pos]` or `gh[pours]` would resolve this, but haven't tested it.

Can you try changing the regex to `gh[pos]` and see if it works for you?

**Comment by MikeMcQuaid** [comment]
> It seems changing the [regex used by Homebrew to validate tokens](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github/api.rb?rgh-link-date=2024-04-02T03%3A34%3A47Z#L30) from `gh[po]` to `gh[pos]` or `gh[pours]` would resolve this, but haven't tested it.

Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!
