### ISSUE TITLE
`brew bump --open-pr` fails to fetch repology data

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/brew#17021]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash -u && git clean -d -f

Uncommitted files:
   M Formula/a/antiword.rb
   M Formula/e/ecm.rb
   M Formula/f/fastbit.rb
   M Formula/j/jerm.rb
   M Formula/l/lbzip2.rb
   M Formula/l/lv.rb
   M Formula/n/negfix8.rb
   M Formula/r/rc.rb
   M Formula/s/skymaker.rb
   M Formula/t/tcptrace.rb
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.16-69-gfcc190b
ORIGIN: https://github.com/Homebrew/brew
HEAD: fcc190b5c659d9c74454011f094de568789ef8fd
Last commit: 13 hours ago
Core tap HEAD: 8f58412c523bee27dbf22770c0944ff3dba75c8b
Core tap last commit: 12 hours ago
Core tap JSON: 04 Apr 07:36 UTC
Core cask tap HEAD: 8797c74d6fc3fc7f9cf3d9c0c1afff7df240d7f0
Core cask tap last commit: 13 hours ago
Core cask tap JSON: 04 Apr 07:36 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3 => /Applications/Xcode-15.3.0.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

Tried to run `brew bump --open-pr mtbl` to update the version

### What happened (include all command output)?

Got annoyed by the:
```console
Warning: Removed Sorbet lines from backtrace!

JSON::ParserError: unexpected token at '<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
'
```

When running it with verbose it became clear that it came from this command:
```sh
/usr/bin/env /opt/homebrew/opt/curl/bin/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.16-69-gfcc190b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --location --silent https://repology.org/api/v1/project/mtbl
```

So it seems repology blocks brew bump.

### What did you expect to happen?

a version update was created

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump --open-pr mtbl --debug --verbose
```

**Comment by MikeMcQuaid** [comment]
> So it seems repology blocks brew bump.

Sad but unsurprising.

In the short-term we should probably rip out Repology support.

In the medium-term we should consider running our own mirror, proxy or similar.

**Comment by SMillerDev** [comment]
Repology is mostly informational AFAIK. Maybe we can just make it a `--consider-repology` flag or something?

**Comment by SMillerDev** [comment]
> Bulk requests to this API are discouraged, consider requesting a [bulk export](https://github.com/repology/repology-exports). Bulk clients must identify themselves with a custom user-agent, referring to a description of the client and a way to report misbehavior (such as GitHub repository with an issue tracker). Bulk clients must not do more than one request per second. Miscomplying clients will be blocked.

https://repology.org/api

---

Not sure if we're a bulk client. Adding an issue reporting link to the user agent might not be a bad idea though.

**Comment by MikeMcQuaid** [comment]
> Not sure if we're a bulk client.

We are now 😭.

> Bulk requests to this API are discouraged, consider requesting a [bulk export](https://github.com/repology/repology-exports).

Something like this which we then stick in e.g. GitHub Pages seems like a good idea.
