### ISSUE TITLE
How to specify Swift 3.0 dependencies?

### ISSUE THREAD

**Issue by jlyonsmith** [Homebrew/brew#1702]
I searched the whole repository and I cannot find a single mention of the Swift programming language!  If I wanted to write a tool that depends on Swift 3.0 how could I specify a dependency on it?  I'd like to use Swift Package Manager to build a collection of command line tools.  I just want to use `brew` to link them into `/usr/local/bin`

**Comment by MikeMcQuaid** [comment]
We don't support depending on a specific Swift version but you can use `depends_on :xcode` to depend on a given Xcode version. We'd accept a PR for `depends_on :swift`, though. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else such as how you'd go about making a `depends_on :swift` work (i.e. using a new `SwiftRequirement`).

Thanks!

**Comment by jlyonsmith** [comment]
Thanks Mike.  I'll give it a go.
