### ISSUE TITLE
Can not upgrade python on OSX 10.12.2. SSL issue

### ISSUE THREAD

**Issue by x6lab** [Homebrew/brew#1703]
When I tried to upgrade python by "brew upgrade", I got an error related to SSL certificate.

Here is the out put

`==> Upgrading 1 outdated package, with result:
python 2.7.13
==> Upgrading python --with-tcl-tk
==> Using the sandbox
==> Downloading https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
Already downloaded: /Users/xg/Library/Caches/Homebrew/python-2.7.13.tar.xz
==> Downloading https://raw.githubusercontent.com/Homebrew/patches/42fcf22/python/brewed-tk-patch.diff
Already downloaded: /Users/xg/Library/Caches/Homebrew/python--patch-15c153bdfe51a98efe48f8e8379f5d9b5c6c4015e53d3f9364d23c8689857f09.diff
==> Patching
==> Applying brewed-tk-patch.diff
patching file setup.py
Hunk #1 succeeded at 1887 (offset 77 lines).
Hunk #2 succeeded at 1932 (offset 77 lines).
Hunk #3 succeeded at 1956 (offset 77 lines).
==> ./configure --prefix=/usr/local/Cellar/python/2.7.13 --enable-ipv6 --datarootdir=/usr/local/Cellar/python/2.7.13/share --datadir=/usr/local/Cellar/python/2.7.13/share --enable-framework=/us
==> make
==> make install PYTHONAPPSDIR=/usr/local/Cellar/python/2.7.13
==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python/2.7.13/share/python
==> Downloading https://files.pythonhosted.org/packages/26/d1/dc7fe14ce4a3ff3faebf1ac11350de4104ea2d2a80c98393b55c84362b0c/setuptools-32.1.0.tar.gz

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "python--setuptools"
Download failed: https://files.pythonhosted.org/packages/26/d1/dc7fe14ce4a3ff3faebf1ac11350de4104ea2d2a80c98393b55c84362b0c/setuptools-32.1.0.tar.gz` 

Does anyone have idea how I can fix it?

Thanks!

**Comment by x6lab** [comment]
Problem was solved be repair my Keychain Access:

Remove everything under ~/Library/Keychains/ then restart.

**Comment by MikeMcQuaid** [comment]
Glad you fixed this. In future please fill out the issue template so we have enough information to help you.
