### ISSUE TITLE
Install instruction does not work on MacOS 10.11.16

### ISSUE THREAD

**Issue by bf0** [Homebrew/brew#1705]
### Reproduction

1. New macbook.
2. Immediately update to El Capitan 10.11.6 .
3. Install as instructed on the website: `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

### Result
```
Error: Failed to link all completions, docs and manpages:
  Permission denied - (../../Homebrew/docs, /usr/local/share/doc/homebrew)
```

### Workaround

```
sudo chown -R $USER /usr/local; brew update
rm -rf /usr/local/.git
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

The workaround works, but not a good user experience digging around in old tickets to figure it out. Please either amend the documentation or change brew. Can these steps be added to the installer?

Full output from brew install:

```
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Homebrew
/usr/local/Frameworks
/usr/local/bin
/usr/local/etc
/usr/local/include
/usr/local/lib
/usr/local/opt
/usr/local/sbin
/usr/local/share
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown redact /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /bin/mkdir -p /Users/redact/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/redact/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown redact /Users/redact/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/mkdir -p /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown redact /Library/Caches/Homebrew
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
==> Installing Command Line Tools (macOS El Capitan version 10.11) for Xcode-8.2
==> /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ (macOS\ El\ Capitan\ version\ 10.11)\ for\ Xcode-8.2
Software Update Tool
Copyright 2002-2015 Apple Inc.


Downloading Command Line Tools (macOS El Capitan version 10.11) for Xcode
Downloaded Command Line Tools (macOS El Capitan version 10.11) for Xcode
Installing Command Line Tools (macOS El Capitan version 10.11) for Xcode
Done with Command Line Tools (macOS El Capitan version 10.11) for Xcode
Done.
==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
==> Downloading and installing Homebrew...
remote: Counting objects: 4267, done.
remote: Compressing objects: 100% (2809/2809), done.
remote: Total 4267 (delta 2206), reused 2752 (delta 1310), pack-reused 0
Receiving objects: 100% (4267/4267), 2.44 MiB | 3.66 MiB/s, done.
Resolving deltas: 100% (2206/2206), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3
 * [new tag]         0.4        -> 0.4
 * [new tag]         0.5        -> 0.5
 * [new tag]         0.6        -> 0.6
 * [new tag]         0.7        -> 0.7
 * [new tag]         0.7.1      -> 0.7.1
 * [new tag]         0.8        -> 0.8
 * [new tag]         0.8.1      -> 0.8.1
 * [new tag]         0.9        -> 0.9
 * [new tag]         0.9.1      -> 0.9.1
 * [new tag]         0.9.2      -> 0.9.2
 * [new tag]         0.9.3      -> 0.9.3
 * [new tag]         0.9.4      -> 0.9.4
 * [new tag]         0.9.5      -> 0.9.5
 * [new tag]         0.9.8      -> 0.9.8
 * [new tag]         0.9.9      -> 0.9.9
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.0.1      -> 1.0.1
 * [new tag]         1.0.2      -> 1.0.2
 * [new tag]         1.0.3      -> 1.0.3
 * [new tag]         1.0.4      -> 1.0.4
 * [new tag]         1.0.5      -> 1.0.5
 * [new tag]         1.0.6      -> 1.0.6
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.1.4      -> 1.1.4
 * [new tag]         1.1.5      -> 1.1.5
HEAD is now at 0027ded Merge pull request #1674 from MikeMcQuaid/audit-os-mac-linux
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 3799, done.
remote: Compressing objects: 100% (3679/3679), done.
remote: Total 3799 (delta 20), reused 330 (delta 8), pack-reused 0
Receiving objects: 100% (3799/3799), 3.03 MiB | 4.33 MiB/s, done.
Resolving deltas: 100% (20/20), done.
Tapped 3675 formulae (3,828 files, 9.5M)
==> Cleaning up /Library/Caches/Homebrew...
==> Migrating /Library/Caches/Homebrew to /Users/redact/Library/Caches/Homebrew...
==> Deleting /Library/Caches/Homebrew...
Already up-to-date.
Error: Failed to link all completions, docs and manpages:
  Permission denied - (../../Homebrew/docs, /usr/local/share/doc/homebrew)
Failed during: /usr/local/bin/brew update --force```

**Comment by MikeMcQuaid** [comment]
> ==> Cleaning up /Library/Caches/Homebrew...
> ==> Migrating /Library/Caches/Homebrew to /Users/redact/Library/Caches/Homebrew...

If these directories existed it seems you had a previous, older Homebrew installation here or something similar which had created these directories with bad permissions. 

Please in future fill out our issue template so we have enough information to help you.

**Comment by MikeMcQuaid** [comment]
@bf0 If you have additional comments please make them here.

**Comment by bf0** [comment]
@MikeMcQuaid 

`If these directories existed it seems you had a previous, older Homebrew installation here or something similar which had created these directories with bad permissions.`

No - It was a BRAND NEW computer never been touched before, as the ticket said. Not a refurb, fresh install clean machine.

**Comment by bf0** [comment]
@MikeMcQuaid Regarding your comment about "providing me free support" in #1730

This is not a support request. It is a ticket informing you about a defect in the Homebrew project. If anything, I am providing a service to you. You are free to ignore it if you wish.

**Comment by vitorgalvao** [comment]
@bf0 From what I understand, you have already fixed the issue on your machine via a workaround.

In light of that, I suggest we chalk this up to some weirdness at the time of the install and keep an eye out. If this happens again to another user, it’s worth to investigate further, if not, it’s safe to ignore.

**Comment by bf0** [comment]
@vitorgalvao Thanks

**Comment by MikeMcQuaid** [comment]
For what it's worth: I cannot reproduce this on a clean El Capitan machine as described so it seems very likely, as mentioned, that there was some other activity on that machine that's written to the relevant directories before the installer was run.

**Comment by bf0** [comment]
@MikeMcQuaid  Got it.  ... Possibly iCloud Drive related. That's the only thing I can think of which might touch /Library/Caches ... other than that I had installed npm, iTerm, Chrome, a few basics like that.

I'll actually be getting another fresh machine in a few days, and will try to track down what it could be if it repros.

**Comment by MikeMcQuaid** [comment]
@bf0 It's likely npm. Would have been helpful to clarify that it wasn't a completely fresh installation in your original issue.

**Comment by bf0** [comment]
@MikeMcQuaid 

> Would have been helpful to clarify that it wasn't a completely fresh installation in your original issue.


You have a passive aggressive attitude. I don't think it suits you very well.

**Comment by vitorgalvao** [comment]
> You have a passive aggressive attitude. I don't think it suits you very well, or the project.

Lets please be respectful, here. It’s not like the project owes you anything.

You were told multiple times the issue was likely with something else on your machine, and repeatedly you denied that as a possibility, when now we see that it was. People took time of their Christmas day to help you, and you [acted as if you were doing us a favour](https://github.com/Homebrew/brew/issues/1705#issuecomment-269137836).

You may read @MikeMcQuaid’s answer as passive aggressive, but I read as a polite request to consider on subsequent issues. He took no jabs at you, so I ask you extend the same courtesy (especially since you extended your comment on the entire project).

@MikeMcQuaid, with your permission I’m going to lock the issue. For all intents and purposes the issue was solved and we have probable cause. There’s nothing left to be gained from the conversation.

Happy holidays to you both!

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid, with your permission I’m going to lock the issue. For all intents and purposes the issue was solved and we have probable cause. There’s nothing left to be gained from the conversation.

I agree, thanks.

> You have a passive aggressive attitude. I don't think it suits you very well, or the project.

I prefer "polite". The less polite version I initially typed referenced the fact that I spent over an hour trying to reproduce a bug on what you claimed was a fresh install until I demonstrated otherwise. Reporting bugs without disclosing this sort of information does not do Homebrew a favour as that's an hour we could have spent fixing actual bugs.
