### ISSUE TITLE
`brew log` regression after port to `abstract_command`

### ISSUE THREAD

**Issue by mattgauf** [Homebrew/brew#17054]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0476c2e5e4f02b409084553896340b2f4ab3352e
Last commit: 2 days ago
Core tap JSON: 09 Apr 09:11 UTC
Core cask tap JSON: 09 Apr 09:11 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Users/mgauf/.opt/paths/sublime-text/subl --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### What were you trying to do (and why)?

Run `brew log`

### What happened (include all command output)?
```
Error: wrong exec option symbol: args
/opt/homebrew/Library/Homebrew/cmd/log.rb:83:in `system'
/opt/homebrew/Library/Homebrew/cmd/log.rb:83:in `block in git_log'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:139:in `chdir'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:139:in `cd'
/opt/homebrew/Library/Homebrew/cmd/log.rb:56:in `git_log'
/opt/homebrew/Library/Homebrew/cmd/log.rb:45:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

Regular output

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew log
```

### Details

Any invocation of `brew log` with little or no arguments results in the error.

I checked the blame `cmd/log.rb` and noticed it had recent changes to several large blocks. So I copied the source from a prior commit (from before the migration to `abstract_command`) and it works.

So I'm thinking this is just a minor regression... let me know if there's any other system info you need to reproduce.

**Comment by MikeMcQuaid** [comment]
@mattgauf Thanks for clear bug report, have opened that should fix this imminently: https://github.com/Homebrew/brew/pull/17056
