### ISSUE TITLE
option to install package to home directory or a custom directory

### ISSUE THREAD

**Issue by camelcigarettes** [Homebrew/brew#17061]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

you can do

brew install hexchat --homedir and it'll download the files after checking for dependencies, install to a custom directory in the home dir or in general (--homedir-dir ? --custom-dir=/Volumes/5tb/.brew ?) and somehow set paths using zsh

then it can compress and decompress the files to save time

### What is the motivation for the feature?

independant packages, binaries, libraries per user, at the cost of disk space

### How will the feature be relevant to at least 90% of Homebrew users?

it will allow them to easily organize multiple packages through mutiple directories, even the home heirachy

### What alternatives to the feature have been considered?

a custom python/shell script that replicates suggested features

**Comment by MikeMcQuaid** [comment]
We can't install formulae to arbitrary directories, many of them break. You can install Homebrew itself to your home directory but it's not supported (because you'll have to build from source).

Some casks can be installed to the home directory with `brew install --appdir`.
