### ISSUE TITLE
Running the macOS installer changes permissions on `~/.gitconfig`

### ISSUE THREAD

**Issue by raphaelokon** [Homebrew/brew#17067]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Install Homebrew via the official Homebrew .pkg (downloaded from GitHub releases 4.2.17) with a non-admin user on macOS 14.4.1-arm64

## What happened (include command output)

Right after installation I noticed that my `~/.gitconfig` was not applied anymore. I inspected the file permissions, which were changed from my user owning the file to `System`. 

## What you expected to happen

Running the installer should not change `~/.gitconfig` permissions and ownership.

## Step-by-step reproduction instructions (by running `brew` commands)
n/a

**Comment by EricFromCanada** [comment]
Confirmed on macOS 14.4.1-x86:
```
# Before installation
vmuser@14x-Sonoma ~ % ls -la
total 8
drwxr-x---+ 14 vmuser  staff   448 10 Apr 12:01 .
drwxr-xr-x   6 root    admin   192 10 Apr 11:55 ..
-rw-------   1 vmuser  staff     3 10 Apr 11:55 .CFUserTextEncoding
drwx------+  2 vmuser  staff    64 10 Apr 11:55 .Trash
-rw-r--r--   1 vmuser  staff    22 10 Apr 12:01 .gitconfig
drwx------   3 vmuser  staff    96 10 Apr 11:57 .zsh_sessions
...

# After installation
vmuser@14x-Sonoma ~ % ls -la
total 8
drwxr-x---+ 14 vmuser  staff   448 10 Apr 12:12 .
drwxr-xr-x   6 root    admin   192 10 Apr 11:55 ..
-rw-------   1 vmuser  staff     3 10 Apr 11:55 .CFUserTextEncoding
drwx------+  2 vmuser  staff    64 10 Apr 11:55 .Trash
-rw-r--r--   1 root    staff    22 10 Apr 12:12 .gitconfig
drwx------   3 vmuser  staff    96 10 Apr 11:57 .zsh_sessions
...

vmuser@14x-Sonoma ~ % cat .gitconfig 
[alias]
  st = status
```
Also, if no `.gitconfig` is present during install, an empty root-owned file is created.

Likely related to changes in #16082.

**Comment by ZhongRuoyu** [comment]
We could probably do `git -c safe-directory="${homebrew_directory}"` to avoid ever needing to write to `.gitconfig`.

**Comment by ZhongRuoyu** [comment]
The pkg installer for the next release will include the fix for this.

You can `sudo chmod "$(id -un):staff" ~/.gitconfig` to fix the permissions of your Git config file.

**Comment by ZhongRuoyu** [comment]
> Is it possible to make `/opt/homebrew` only accessible for a single user on a macOS multi-user system?

I think it should work if you change the permissions of the `/opt/homebrew` directory (non-recursively) to e.g. `700`.
