### ISSUE TITLE
Using kickstart?

### ISSUE THREAD

**Issue by BetterB0y** [Homebrew/brew#17093]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9edabf02ce29e54d0b717baa757cff38ad0c0e25
Last commit: 35 hours ago
Core tap JSON: 16 Apr 07:27 UTC
Core cask tap JSON: 16 Apr 07:27 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3 => /Applications/Developer/Xcode.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

I was trying to uninstall blackhole.
https://github.com/ExistentialAudio/BlackHole/issues/779

I know that there is problem with update too.

### What happened (include all command output)?

brew uninstall blackhole-16ch
==> Uninstalling Cask blackhole-16ch
==> Uninstalling packages with sudo; the password may be necessary:
Password:
Could not kickstart service "com.apple.audio.coreaudiod": 1: Operation not permitted
Error: Failure while executing; `/usr/bin/sudo -E -- /bin/launchctl kickstart -kp system/com.apple.audio.coreaudiod` exited with 1. Here's the output:
Could not kickstart service "com.apple.audio.coreaudiod": 1: Operation not permitted

### What did you expect to happen?

Should uninstall blackhole.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew uninstall blackhole-16ch
```

**Comment by gnattu** [comment]
The old cask file is still using kickstart and brew uninstall will keep using that (broken) cli even after `brew edit`. did not found a way to workaround that yet.

**Comment by MarkusTiede** [comment]
Thanks for reporting - blackhole-2ch is also affected [by this.](https://forums.developer.apple.com/forums/thread/748228)

**Comment by bevanjkay** [comment]
This is because Brew will always uninstall the currently installed version using the caskfile that was used to install that same version. In this case it uses a method that has been deprecated by Apple.

You could try removing the Caskroom folder for `blackhole-*` (note that Brew will no longer see the application as installed), and then run `brew reinstall blackhole-2ch`.

`rm -rfi /usr/local/Caskroom/blackhole-2ch` on intel. Or `rm -rfi /opt/homebrew/Caskroom/blackhole-2ch`.
Please be careful using `rm` commands, and I would recommend navigating to these folders manually to remove them.

**Comment by BetterB0y** [comment]
https://github.com/ExistentialAudio/BlackHole/issues/779#issuecomment-2058581435
Here is good solution
