### ISSUE TITLE
g++-6 doesn't work on mac

### ISSUE THREAD

**Issue by dongz9** [Homebrew/brew#1711]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this section with a brief summary of your issue **AND** the output of `brew config` and `brew doctor`. Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

I installed gcc using Homebrew on Sierra, however it doesn't work at all.

```
In file included from /usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/bits/postypes.h:40:0,
                 from /usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/iosfwd:40,
                 from /usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/ios:38,
                 from /usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/ostream:38,
                 from /usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/iostream:39,
                 from test.cc:1:
/usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/cwchar:44:19: fatal error: wchar.h: No such file or directory
 #include <wchar.h>
                   ^
```

### Propose a feature:

Please replace this section with a detailed description of your proposed feature, the motivation for it and alternatives considered. Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.
