### ISSUE TITLE
Add `brew asdf-sync`; equivalent to `brew nodenv-sync` / `brew pyenv-sync` / `brew rbenv-sync`

### ISSUE THREAD

**Issue by sindre-nistad** [Homebrew/brew#17111]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Would it be possible to add a command `asdf-sync`, which adds / synchronises the relevant versions of Python, Node.js and Ruby which are installed by brew?
I noticed that the commands `nodenv-sync`, `pyenv-sync`, and `rbenv-sync` already exists, and would like for there to be an equivalent for `asdf`.

### What is the motivation for the feature?

Being a user of `asdf`, and having various versions of Python installed (in my case), it would be great to have them syncroniced so that I don't have to install Python / Node / Ruby multiple times for the same version.

### How will the feature be relevant to at least 90% of Homebrew users?

Most likely not

### What alternatives to the feature have been considered?

It should be fairly straight forward to create an independent shell script that does this, instead of adding it to `brew`.

**Comment by MikeMcQuaid** [comment]
Will review a PR for this but not leaving issue open indefinitely because it's very much in the camp of "whoever cares enough about this will be the one to open the PR and maintainers will not".

**Comment by sindre-nistad** [comment]
fair enough
