### ISSUE TITLE
reinstall of "node" fails due to somehow having installed files as root!

### ISSUE THREAD

**Issue by robohack** [Homebrew/brew#1714]
After a `brew update` today I tried reinstalling 'node':

<pre>
13:37 [2174] $ brew reinstall node --with-full-icu
==> Reinstalling node --with-full-icu
==> Using the sandbox
==> Downloading https://nodejs.org/dist/v7.3.0/node-v7.3.0.tar.xz
Already downloaded: /Users/gaw/Library/Caches/Homebrew/node-7.3.0.tar.xz
==> Downloading https://ssl.icu-project.org/files/icu4c/58.1/icu4c-58_1-src.tgz
Already downloaded: /Users/gaw/Library/Caches/Homebrew/node--icu4c-58.1.tgz
==> ./configure --prefix=/usr/local/Cellar/node/7.3.0 --without-npm --with-intl=full-icu
==> make install
==> Downloading https://registry.npmjs.org/npm/-/npm-3.10.10.tgz
Already downloaded: /Users/gaw/Library/Caches/Homebrew/node--npm-3.10.10.tgz
==> ./configure --prefix=/usr/local/Cellar/node/7.3.0/libexec/npm
==> make install
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/7.3.0: 3,892 files, 67.9M, built in 17 minutes 52 seconds
ksh: exit code: 1
</pre>

So, I do as suggested:

<pre>
13:56 [2193] $ brew postinstall  node
==> Using the sandbox
Error: Permission denied - /usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/assert-plus/AUTHORS
ksh: exit code: 1
</pre>

OK, that's really weird.  How can that be possible?

<pre>
13:58 [2194] $ ls -l /usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/assert-plus/AUTHORS
-rw-rw-r--  1 root  wheel  217 Jun 23 17:14 /usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/assert-plus/AUTHORS
</pre>

Hmmm...  That looks like a problem!

So I cleaned out everything related to `node` from `/usr/local` and ran the post-install step again.

Now I find there are new files and directories from node whichare owned by root:

<pre>
15:19 [2321] $ find /usr/local -user root | fgrep node |wc -l
     410
</pre>
(there are also python-2.7 files owned by root somehow, thus the grep)

As expected there are no SUID files in /usr/local:

<pre>
15:23 [2323] $ find /usr/local -perm +04000 -print | wc -l
       0
</pre>

I have never run 'brew' as root or via sudo, etc.

<pre>
15:12 [2313] $ brew config                                                                                               
HOMEBREW_VERSION: 1.1.5-33-g8f85eb64c4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8f85eb64c4875fed514150dec755cb267a96df74
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7736bdad0e1cc3abf7aa6a7437a1bc1d7c589a2e
Core tap last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: N/A
X11: 2.7.11 => /opt/X11
15:15 [2314] $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docutils
  lesstif

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.kshrc
</pre>

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by MikeMcQuaid** [comment]
Something must have previously written to that directory as the root user. Homebrew cannot do so unless you run it as root (something that it will now stop you doing.

**Comment by robohack** [comment]
As I clearly said, brew has _never_ been run as root (on this machine or ever by me in general).

Also, as I showed, I cleaned out all the root-owned files, re-installed node (as a normal user), and then I found new root-owned files.

I you can't reproduce this very simply by the commands I gave, then please tell me how to gather further tracing or logs, etc., to see what exactly is happening at a filesystem level during the reinstall.

**Comment by MikeMcQuaid** [comment]
> Also, as I showed, I cleaned out all the root-owned files, re-installed node (as a normal user), and then I found new root-owned files.

You cleared out "everything related to node" but it's unclear that that was all root-owned files and directories. Did you confirm that using the same commands?

> I you can't reproduce this very simply by the commands I gave, then please tell me how to gather further tracing or logs, etc., to see what exactly is happening at a filesystem level during the reinstall.

I cannot reproduce. To reemphasize: Homebrew cannot write root-owned files unless run as root. There is likely other things going on. I'd recommend a `sudo chown -R $USER /usr/local`, `brew update`, `brew doctor` and fix any warnings you can. If you're still getting issues I suggest checking your shell environment and background processes on your system to figure out what's writing these files as root.

**Comment by nickofthyme** [comment]
I came across a similar problem here is how I resolved it...  
  
First run what Mike suggested...
```bash
sudo chown -R $USER /usr/local
```  
  

Then run...
```bash
brew update
```
###### Output
> Updated 2 taps (caskroom/cask, homebrew/services).  
  

Then run...
```bash
brew doctor
```
###### Output
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!
>
> Warning: Your XQuartz (2.7.5) is outdated.
> Please install XQuartz 2.7.9 (or delete the current version).
> XQuartz can be updated using Homebrew-Cask by running
> brew cask reinstall xquartz
>
> Warning: You have unlinked kegs in your Cellar
> Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
> those kegs to fail to run properly once built. Run `brew link` on these:
> node  
  

Then resolve the issues by running...
```bash
brew link node
```
###### Output
> Linking /usr/local/Cellar/node/7.4.0...
> Error: Could not symlink share/doc/node/gdbinit
> Target /usr/local/share/doc/node/gdbinit
> already exists. You may want to remove it:
>    rm '/usr/local/share/doc/node/gdbinit'
>
> To force the link and overwrite all conflicting files:
>    brew link --overwrite node
>
> To list all files that would be deleted:
>    brew link --overwrite --dry-run node  
  

```bash
brew cleanup
```
###### Output
> Removing: /usr/local/Cellar/chromedriver/2.26... (4 files, 9.7M)
> Removing: /usr/local/Cellar/elasticsearch/5.1.1... (98 files, 35.2M)
> Removing: /usr/local/Cellar/mongodb/3.4.0... (17 files, 259.0M)
> Removing: /usr/local/Cellar/node/7.0.0... (3,861 files, 44.3M)
> Removing: /usr/local/Cellar/sqlite/3.15.2... (11 files, 2.9M)
> Removing: /Users/Nick/Library/Caches/Homebrew/elasticsearch-5.1.1.tar.gz... (31.7M)
> Removing: /Users/Nick/Library/Logs/Homebrew/openssl... (68B)
> Removing: /Users/Nick/Library/Logs/Homebrew/python3... (3 files, 116.3K)
> ==> This operation has freed approximately 383M of disk space.  
  

Then run...
```bash
brew link node
```
###### Output
> Linking /usr/local/Cellar/node/7.4.0...
> Error: Could not symlink share/doc/node/gdbinit
> Target /usr/local/share/doc/node/gdbinit
> already exists. You may want to remove it:
>    rm '/usr/local/share/doc/node/gdbinit'
> 
> To force the link and overwrite all conflicting files:
>    brew link --overwrite node
> 
> To list all files that would be deleted:
>    brew link --overwrite --dry-run node  
  

Then run...
```bash
brew uninstall node
```
###### Output
> Uninstalling /usr/local/Cellar/node/7.4.0... (4,129 files, 68.7M)  
  

Then run...
```bash
brew install node
```
###### Output
> ==> Downloading https://homebrew.bintray.com/bottles/node-7.4.0.sierra.bottle.tar.gz
> Already downloaded: /Users/Nick/Library/Caches/Homebrew/node-7.4.0.sierra.bottle.tar.gz
> ==> Pouring node-7.4.0.sierra.bottle.tar.gz
> Error: The `brew link` step did not complete successfully
> The formula built, but is not symlinked into /usr/local
> Could not symlink share/doc/node/gdbinit
> Target /usr/local/share/doc/node/gdbinit
> already exists. You may want to remove it:
>    rm '/usr/local/share/doc/node/gdbinit'
>
>To force the link and overwrite all conflicting files:
>    brew link --overwrite node
>
>To list all files that would be deleted:
>   brew link --overwrite --dry-run node
>
> Possible conflicting files are:
> /usr/local/share/doc/node/gdbinit
> /usr/local/share/man/man1/node.1
> /usr/local/share/systemtap/tapset/node.stp
> /usr/local/lib/dtrace/node.d
> ==> Using the sandbox
> ==> Caveats
> Please note by default only English locale support is provided. If you need
> full locale support you should either rebuild with full icu:
>    `brew reinstall node --with-full-icu`
> or add full icu data at runtime following:
>    https://github.com/nodejs/node/wiki/Intl#using-and-customizing-the-small-icu-build
>
> Bash completion has been installed to:
>    /usr/local/etc/bash_completion.d
> ==> Summary
> 🍺  /usr/local/Cellar/node/7.4.0: 4,129 files, 46.3M  
  

Then 'rm' all of the files that already exist, for me it was just...
```bash
rm '/usr/local/share/doc/node/gdbinit'
```  
  

Then install node again...
```bash
brew install node
```
###### Output
> Warning: node-7.4.0 already installed, it's just not linked.  
  

Then uninstall node again
```bash
brew uninstall node
```
###### Output
Uninstalling /usr/local/Cellar/node/7.4.0... (4,129 files, 46.3M)  
  

```bash
brew install node
```
###### Output
> ==> Downloading https://homebrew.bintray.com/bottles/node-7.4.0.sierra.bottle.tar.gz
> Already downloaded: /Users/Nick/Library/Caches/Homebrew/node-7.4.0.sierra.bottle.tar.gz
> ==> Pouring node-7.4.0.sierra.bottle.tar.gz
> Error: The `brew link` step did not complete successfully
> The formula built, but is not symlinked into /usr/local
> Could not symlink share/man/man1/node.1
> Target /usr/local/share/man/man1/node.1
> already exists. You may want to remove it:
>    rm '/usr/local/share/man/man1/node.1'
>
> To force the link and overwrite all conflicting files:
>    brew link --overwrite node
>
> To list all files that would be deleted:
>    brew link --overwrite --dry-run node
>
> Possible conflicting files are:
> /usr/local/share/man/man1/node.1
> /usr/local/share/systemtap/tapset/node.stp
> /usr/local/lib/dtrace/node.d
> ==> Using the sandbox
> ==> Caveats
> Please note by default only English locale support is provided. If you need
> full locale support you should either rebuild with full icu:
>    `brew reinstall node --with-full-icu`
> or add full icu data at runtime following:
>    https://github.com/nodejs/node/wiki/Intl#using-and-customizing-the-small-icu-build
>
> Bash completion has been installed to:
>  /usr/local/etc/bash_completion.d
> ==> Summary
> 🍺  /usr/local/Cellar/node/7.4.0: 4,129 files, 46.3M  
  

Then run...
```bash
brew link --overwrite node
```
###### Output
> Linking /usr/local/Cellar/node/7.4.0... 7 symlinks created  
  

That should resolve the issue. Check if you have the current node version...
```bash
node --version
```
###### Output
> v7.4.0  
  

Then enter node shell
```bash
node
```  
  

Run some sample code to see that it is working correctly
```javascript
> Object.assign({},{a:3})
{ a: 3 }
> let {a, b} = {a: 1, b: 2}
undefined
> a
1
> b
2
```  
  

Node should now be linked. Hope this helps people that encounter this problem in the future.

**Comment by robohack** [comment]
It looks like the main part of the Node/npm installation is done by a huge and massive pile of JS (in the post_install step, by "npm install npm@latest") and that it's anyone's guess as to what it will actually do in any given circumstance.

Perhaps the the thing for brew to do would be to try to clean up the resulting mess.
