### ISSUE TITLE
Documentation is replaced by auto-generated RBI comments.

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/brew#17167]
### `brew doctor` output

```shell
N/A
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
N/A
```

### What were you trying to do (and why)?

Documentation for e.g. `RuboCop`s only shows auto-generated comments from RBI files:

From https://rubydoc.brew.sh/RuboCop/Cop/Homebrew/Blank.html:

> DO NOT EDIT MANUALLY This is an autogenerated file for dynamic methods in `RuboCop::Cop::Homebrew::Blank`. Please instead update this file by running `bin/tapioca dsl RuboCop::Cop::Homebrew::Blank`.

### What happened (include all command output)?

I assume the reason is that `yard-sorbet` is run last. It should be changed to skip any comments in RBI files.

### What did you expect to happen?

Original documentation should be shown.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew rubydoc --open`
1. Look at `RuboCop::Cop::Homebrew::Blank` documentation.
```

**Comment by dduugg** [comment]
I opened a PR upstream: https://github.com/Shopify/tapioca/pull/1885 🤞

**Comment by MikeMcQuaid** [comment]
Thanks for issues @reitermarkus and @dduugg!

**Comment by dduugg** [comment]
We can also patch Tapioca if upstream doesn't accept the patch (early feedback isn't positive) 🙈. Something like: https://github.com/Homebrew/brew/compare/tapioca-patch?expand=1

**Comment by MikeMcQuaid** [comment]
> We can also patch Tapioca if upstream doesn't accept the patch (early feedback isn't positive) 🙈. Something like: [`tapioca-patch`?expand=1 (compare)](https://github.com/Homebrew/brew/compare/tapioca-patch?expand=1)

@dduugg This would work fine for me, monkey-patching like this is IMO fairly inconsequential when we're not exposing it to end-users.

**Comment by reitermarkus** [comment]
@dduugg, fine by me. We can always revert it once it is fixed upstream.

**Comment by dduugg** [comment]
Upstream PR was accepted, this will be fixed in the next tapioca release
