### ISSUE TITLE
Unable to uninstall any packages -- Error: No available formula with the name "mashape/kong/luajit" 

### ISSUE THREAD

**Issue by nurikidy** [Homebrew/brew#1716]
I am unable to remove/uninstall any packages because bre always return the following error message:

### Bug reports:
Error: No available formula with the name "mashape/kong/luajit" 

nuri@jupiter $ brew update
Already up-to-date.

nuri@jupiter $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libarena-39b92f95.dylib
  /usr/local/lib/libflate-39b92f95.dylib
  /usr/local/lib/libfmt_macros-39b92f95.dylib
  /usr/local/lib/libgetopts-39b92f95.dylib
  /usr/local/lib/libgraphviz-39b92f95.dylib
  /usr/local/lib/liblog-39b92f95.dylib
  /usr/local/lib/librbml-39b92f95.dylib
  /usr/local/lib/librustc-39b92f95.dylib
  /usr/local/lib/librustc_back-39b92f95.dylib
  /usr/local/lib/librustc_borrowck-39b92f95.dylib
  /usr/local/lib/librustc_const_eval-39b92f95.dylib
  /usr/local/lib/librustc_const_math-39b92f95.dylib
  /usr/local/lib/librustc_data_structures-39b92f95.dylib
  /usr/local/lib/librustc_driver-39b92f95.dylib
  /usr/local/lib/librustc_errors-39b92f95.dylib
  /usr/local/lib/librustc_incremental-39b92f95.dylib
  /usr/local/lib/librustc_lint-39b92f95.dylib
  /usr/local/lib/librustc_llvm-39b92f95.dylib
  /usr/local/lib/librustc_metadata-39b92f95.dylib
  /usr/local/lib/librustc_mir-39b92f95.dylib
  /usr/local/lib/librustc_passes-39b92f95.dylib
  /usr/local/lib/librustc_platform_intrinsics-39b92f95.dylib
  /usr/local/lib/librustc_plugin-39b92f95.dylib
  /usr/local/lib/librustc_privacy-39b92f95.dylib
  /usr/local/lib/librustc_resolve-39b92f95.dylib
  /usr/local/lib/librustc_save_analysis-39b92f95.dylib
  /usr/local/lib/librustc_trans-39b92f95.dylib
  /usr/local/lib/librustc_typeck-39b92f95.dylib
  /usr/local/lib/librustdoc-39b92f95.dylib
  /usr/local/lib/libserialize-39b92f95.dylib
  /usr/local/lib/libstd-39b92f95.dylib
  /usr/local/lib/libsyntax-39b92f95.dylib
  /usr/local/lib/libsyntax_ext-39b92f95.dylib
  /usr/local/lib/libsyntax_pos-39b92f95.dylib
  /usr/local/lib/libterm-39b92f95.dylib
  /usr/local/lib/libtest-39b92f95.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ngx_openresty
  openresty

nuri@jupiter $ brew uninstall openresty
Error: No available formula with the name "mashape/kong/luajit" 

nuri@jupiter $ brew uninstall wget
Error: No available formula with the name "mashape/kong/luajit" 

nuri@jupiter $ brew list
android-platform-tools	gettext			libpng			luajit			node			php56			rust			unrar
autoconf		go			libssh2			luarocks		openresty		pkg-config		serf			wget
cmake			icu4c			libtiff			lynx			openssl			pyenv			supervisor		xz
composer		imagemagick		libtool			mysql			openssl@1.1		pyenv-virtualenv	swagger-codegen
dnsmasq			jpeg			libxml2			nginx			p7zip			pyenv-virtualenvwrapper	tidy-html5
freetype		kong			links			ngx_openresty		pcre			readline		unixodbc

nuri@jupiter $ brew uninstall go
Error: No available formula with the name "mashape/kong/luajit" 

nuri@jupiter $ brew uninstall lynx
Error: No available formula with the name "mashape/kong/luajit"

**Comment by MikeMcQuaid** [comment]
As the issue template requested: please provide your `brew config`.

**Comment by nurikidy** [comment]
Hi Mike, this is the brew config verbose

nuri@jupiter $ brew config
HOMEBREW_VERSION: 1.1.5-2120-g6648ff1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6648ff130781279de560ad1ac77379a6250d16e4
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 84c76571c9e0222410915fa5136faa1173240390
Core tap last commit: 14 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_66
macOS: 10.11.6-x86_64
Xcode: 8.2
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11

**Comment by MikeMcQuaid** [comment]
Try to `rm -rf /usr/local/Cellar/luajit` and `brew prune` and see if that resolves your issue.

**Comment by sheerun** [comment]
I had the same issue. Only `rm -rf Cellar/luarocks` helped..

Not sure if it's useful but here's `Cellar/luarocks/2.3.0/INSTALL_RECEIPT.json` I had:

```
{"used_options":[],"unused_options":[],"built_as_bottle":false,"poured_from_bottle":false,"time":1471342037,"source_modified_time":1451404257,"HEAD":"dffd556220a726a9916773dc537662bf3eab656a","stdlib":null,"compiler":"clang","source":{"path":"/usr/local/Library/Taps/mashape/homebrew-kong/Formula/luarocks.rb","tap":"mashape/kong","spec":"stable","versions":{"stable":"2.3.0","devel":null,"head":"HEAD"}}}
```

**Comment by MikeMcQuaid** [comment]
Can you `brew update` and see if you can still reproduce this?

**Comment by nurikidy** [comment]
done brew update and everything seems to be back to normal 👍

**Comment by MikeMcQuaid** [comment]
Great!

**Comment by somebehemoth** [comment]
I have the same problem and the recommended steps above do not resolve the issue for me.

``
HOMEBREW_VERSION: 1.1.11-111-g00af5250f
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 00af5250f0a7988178ed8d26520bf1a98a8dea9a
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a34bd21f37e6d9ed1aa66e70591f64d1a34bc4d0
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_60
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A
``

**Comment by ilovezfs** [comment]
You can use `--ignore-dependencies`

**Comment by somebehemoth** [comment]
Thank you for unblocking me.  This should help me figure out whatever is wrong with my setup too.
