### ISSUE TITLE
Homebrew falls back to HTTP mirror even though the mirror is accessible via HTTPS

### ISSUE THREAD

**Issue by christophberger** [Homebrew/brew#1717]
I noticed an issue with two formulae that use the URL's

    "https://savannah.nongnu.org/download/openexr/openexr-2.2.0.tar.gz"

and

    https://download.savannah.gnu.org/releases/texi2html/texi2html-5.0.tar.gz

**Issue: Both URLs switch to an HTTP mirror even though this mirror is accessible via HTTPS:**

```
==> Installing ffmpeg dependency: texi2html
==> Using the sandbox
==> Downloading https://download.savannah.gnu.org/releases/texi2html/texi2html-5.0.tar.gz
==> Downloading from http://mirrors.cicku.me/savannah//texi2html/texi2html-5.0.tar.gz
```

(**https**://mirrors.cicku.me/savannah//texi2html/texi2html-5.0.tar.gz works fine in a browser) 

and

```
~ admin$ brew install openexr
==> Using the sandbox
==> Downloading https://savannah.nongnu.org/download/openexr/openexr-2.2.0.tar.gz
==> Downloading from http://mirrors.cicku.me/savannah//openexr/openexr-2.2.0.tar.gz
```

(**https**://mirrors.cicku.me/savannah//openexr/openexr-2.2.0.tar.gz works fine in a browser)

As a result, installing or updating any of these fails if `HOMEBREW_NO_INSECURE_REDIRECT` is set.

As this happens with two completely independent formulae, I conclude this is a problem of the core functionality rather than of those particular formulae. 

-> Maybe `brew` should try harder forcing HTTPS on a download URL, esp. if the original HTTPS download URL redirects to an HTTP url.

**Comment by MikeMcQuaid** [comment]
> Maybe brew should try harder forcing HTTPS on a download URL, esp. if the original HTTPS download URL redirects to an HTTP url.

We follow the URLs we are told by the mirror selectors at e.g. Savannah. If they are unnecessarily redirecting to a non-HTTPS URL that's a bug you should report to them. Sorry!
