### ISSUE TITLE
`brew list` and `brew uninstall` drop `.rb` suffix from formula name

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/brew#1718]
I have a formula installed via brew-gem.

brew tab-completes the formula correctly, so it "found" on the filesystem as expected:

```
$ brew list gem-<TAB><TAB>
gem-completion   gem-pygments.rb  gem-travis

$ ls /usr/local/Cellar/gem-pygments.rb
1.0.0/
```

However, both `brew list` and `brew uninstall` return an error, despite the formula name being tabl-completed by homebrew itself:

```
$ brew list gem-pygments.rb 
Error: No such keg: /usr/local/Cellar/gem-pygments

$ brew uninstall gem-pygments.rb 
Error: No such keg: /usr/local/Cellar/gem-pygments
```

Based on the error, it appears that brew is truncating the `.rb` suffix from the formula name, despite being able to tab-complete the name correctly.

System info:

```
$ brew doctor 
Your system is ready to brew.

$ brew config
HOMEBREW_VERSION: 1.1.5-33-g8f85eb64c4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8f85eb64c4875fed514150dec755cb267a96df74
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4cfbf8867adc190fbb0f2d29fc0764725688f171
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.1.5/bin/ruby
Java: 1.8.0_77, 1.7.0_51
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
> I have a formula installed via brew-gem.

Can you reproduce this without using `brew-gem`? That's not an officially supported tool. Thanks!

**Comment by jasonkarns** [comment]
The cause can easily be reproduced with any existing formula:

```
$ brew list autoconf
```
and
```
$ brew list autoconf.rb
```

give exactly the same output. Which indicates that `brew list` blindly drops `.rb` from the argument name, presumably assuming that the `.rb` is the file extension for the formula itself; ignoring the possibility that the `.rb` is actually part of the formula name.

Another example:

```
touch $(brew --repo)/Library/Taps/homebrew/homebrew-core/foo.rb.rb
```

This would be the expected filename for a formula of name `Foo.rb`

```
$ brew list foo
Error: No such keg: /usr/local/Cellar/foo
$ brew list foo.rb
Error: No such keg: /usr/local/Cellar/foo
$ brew list foo.rb.rb 
Error: No such keg: /usr/local/Cellar/foo.rb
```

So `brew list` maps both `foo` and `foo.rb` to a formula named Foo. Thus, when brew-gem creates a formula named `gem-pygments.rb`, all of brew's commands which brew-gem invoke (like list and uninstall) _lossly_ truncate the .rb and thus attempt to match for `gem-pygments` when the actual formula name is gem-pygments.rb.

**Comment by MikeMcQuaid** [comment]
Thanks for the reproduction instructions. My concern is that there may be scripts and/or tools that rely on the existing behaviour that may be broken if modified. I think this is something that should be fixed/changed in `brew-gem` so it avoids adding the `.rb` extension.

**Comment by jasonkarns** [comment]
It's not really possible to be changed by `brew-gem`. The formula name that `brew-gem` creates is simply `brew-` + `{gem name}`. In this case, the actual rubygem name is `pygments.rb`. If `brew-gem` did magic to special-case any gem name with `.rb` ending, they would collide with a same-named gem lacking the suffix. (Substitute any lossy name conversion, like replacing `.rb` with `-rb`. The same collision is possible.)

**Comment by MikeMcQuaid** [comment]
It's definitely possible. The question is if the potential collisions are worse than the actual current bug. Regardless, as this only affects `brew-gem` I'm going to consider it an issue there instead, sorry!

**Comment by jasonkarns** [comment]
It doesn't affect only `brew-gem`. This bug affects (or rather, prevents?) any regular formula with a `.rb` extension.

Copied existing (valid) formula as a new one with `foo.rb.rb` filename (and changed class name to `Foo`):

```
$ cp Formula/a2ps.rb Formula/foo.rb.rb
```

Attempted install fails, and gives error message suggesting to run the exact command that failed in the first place:

```
$ brew install foo.rb 
Error: No available formula with the name "foo" 
==> Searching for similarly named formulae...
This similarly named formula was found:
foo.rb
To install it, run:
  brew install foo.rb
```

Accounting for the `.rb` suffix truncating results in same error (and erroneous suggestion):
```
$ brew install foo.rb.rb
Error: No available formula with the name "foo.rb" 
==> Searching for similarly named formulae...
This similarly named formula was found:
foo.rb
To install it, run:
  brew install foo.rb
==> Searching taps...
Error: No formulae found in taps.
```

And again, by just using the string value matching the ruby class name:
```
$ brew install foo
Error: No available formula with the name "foo" 
==> Searching for similarly named formulae...
This similarly named formula was found:
foo.rb
To install it, run:
  brew install foo.rb
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/greenfoot
To install it, run:
  brew install Caskroom/cask/greenfoot
```

So while `brew-gem` may be the first case to make this bug apparent, its effects are clearly not limited to `brew-gem`.

Are there any known consequences of fixing this bug? I still defer potential side effects, but nothing has been mentioned in this thread other than hypotheticals. It seems premature to close a bug that has 2 documented negative behaviors for fear of _potential_ side effects, without actually validating that any exist. (much less that they outweigh)

**Comment by MikeMcQuaid** [comment]
> Are there any known consequences of fixing this bug?

No but equally given this only currently affects people creating formulae with weird names there aren't any known issues either without workarounds.

> I still defer potential side effects, but nothing has been mentioned in this thread other than hypotheticals.

I'm afraid given the userbase of Homebrew and time it's been out we tend to take backwards compatibility around such things fairly seriously. We'd consider accepting a PR for this (and I'm happy to help testing the various edge-cases) but given it's not affecting any official taps and has an easy workaround when naming formulae it's very low priority for us to fix as maintainers, I'm afraid.

**Comment by vladshablinsky** [comment]
> No but equally given this only currently affects people creating formulae with weird names there aren't any known issues either without workarounds.

Haven't seen names with such names before.

That's said, the code can be easily patched like this, If it's OK, I can open a PR.

```diff
diff --git a/Library/Homebrew/formulary.rb b/Library/Homebrew/formulary.rb
index 6ed5b91..7e8811c 100644
--- a/Library/Homebrew/formulary.rb
+++ b/Library/Homebrew/formulary.rb
@@ -333,7 +333,9 @@ class Formulary
       return TapLoader.new(ref, from: from)
     end
 
-    return FromPathLoader.new(ref) if File.extname(ref) == ".rb"
+    if File.extname(ref) == ".rb" && Pathname.new(ref).expand_path.exist?
+      return FromPathLoader.new(ref)
+    end
 
     formula_with_that_name = core_path(ref)
     if formula_with_that_name.file?
```

**Comment by MikeMcQuaid** [comment]
@vladshablinsky A PR would be good. To brain dump briefly: my concern is that'll break e.g. `cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula; brew edit wget.rb` or similar when editing a formula in the same directory. If that's not broken: 👍

**Comment by vladshablinsky** [comment]
@MikeMcQuaid `brew edit wget.rb` works just like `brew edit wget`. But testing these I come up with a question. Supposing we have `ack.rb` and `ack.rb.rb` formula files under 
`/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula`

What should do each of the following commands if we in that directory?

* `brew edit ack` -- _edit Ack_
* `brew edit ack.rb`-- ***edit what***?
* `brew edit ack.rb.rb` -- _edit AckRb_

**Comment by bfontaine** [comment]
@vladshablinsky IMHO `brew edit ack.rb` should edit _AckRb_ and `brew edit ./ack.rb` or `brew edit /absolute/path/to/ack.rb` should edit _Ack_.

**Comment by MikeMcQuaid** [comment]
> brew edit ack.rb-- edit what? UPD (Now it edits Ack since ack.rb exist in that directory).

I think it's fine for that do do either or fail. 

> brew edit wget.rb works just like brew edit wget

After the patch, before or both? How about if it's in e.g. a random directory and not a tap?

**Comment by vladshablinsky** [comment]
> After the patch, before or both? How about if it's in e.g. a random directory and not a tap?

After the patch. Before the patch should work exactly the same.

Basically, now if we see `.rb` in `loader_for`, then we return `FromPathLoader` regardless the pass exist or not. What It does after the change is the following:
It we see `.rb` suffix and the path doesn't exist, then try other loaders like if the formula wasn't supposed to be instantiated from file at the first place.

**Comment by MikeMcQuaid** [comment]
@vladshablinsky Sounds good. Can you make a PR and we can do more testing and discussion there?

**Comment by vladshablinsky** [comment]
> @vladshablinsky IMHO brew edit ack.rb should edit AckRb and brew edit ./ack.rb or brew edit /absolute/path/to/ack.rb should edit Ack.

@bfontaine 
Being able to specify `FromPathLoader` explicitly adding `./` looks OK, but I think we should be able to resolve formula even without explicit `./` or absolute path.

**Comment by jasonkarns** [comment]
w00t!!

```
$ brew list gem-pygments.rb 
/usr/local/Cellar/gem-pygments.rb/1.0.0/cache/ (3 files)
/usr/local/Cellar/gem-pygments.rb/1.0.0/gems/posix-spawn-0.3.12/ (26 files)
/usr/local/Cellar/gem-pygments.rb/1.0.0/gems/pygments.rb-1.0.0/ (331 files)
/usr/local/Cellar/gem-pygments.rb/1.0.0/gems/yajl-ruby-1.3.0/ (165 files)
/usr/local/Cellar/gem-pygments.rb/1.0.0/specifications/ (3 files)
```
