### ISSUE TITLE
Addition of cmake flag FETCHCONTENT_FULLY_DISCONNECTED=ON breaks formulas

### ISSUE THREAD

**Issue by jackjansen** [Homebrew/brew#17187]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.20-26-g45e0ce0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 45e0ce0635f3a98e7f7b797c7953cc5ab0cce1c7
Last commit: 19 minutes ago
Core tap HEAD: ec19424c2a357cfeb1d277812058371e049db6bc
Core tap last commit: 44 minutes ago
Core tap JSON: 30 Apr 11:06 UTC
Core cask tap HEAD: 531029e3b0a4f22c73c7bac95d17aa832d895cfd
Core cask tap last commit: 3 hours ago
Core cask tap JSON: 30 Apr 11:06 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### What were you trying to do (and why)?

Trying to build a formula with `--HEAD` that worked until a few weeks ago. The formula is a tap, `cwi-dis/cwipc`, but I'm pretty convinced that many other formulae will run into this problem.

### What happened (include all command output)?

It did not build. One of the cmake dependencies, `nlohmann_json::nlohman_json`, was not found. The `CMakeLists.txt` of the `cwipc` repo uses the `FetchContent` macro to obtain the `nlohmann_json` package (which is a header-file-only package, and FetchContent is the preferred way of including it in your build.

Since the merge of #17075 brew will disable downloading of additional content by FetchContent. I fully understand the reasoning behind this merge (and I even somewhat agree:-), but as of this merge I presume many formulae have been broken, and moreover there is no clear error message that the formula maintainer gets that indicates what the problem is.

Unfortunately `FetchContent()` does _not_ give an error or warning message if it has to download a package but is not allowed to do so. So the errors occur only much later in the build process, when the package is used but found to be missing.

### What did you expect to happen?

Build should work.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap cwi-dis/cwipc
brew install --HEAD cwipc
```

**Comment by jackjansen** [comment]
@carlocab agreed on all points. I think the change is in principle a good idea, I will change my repo to not use FetchContent when building with `brew`, in stead adding a dependency.

I've opened https://gitlab.kitware.com/cmake/cmake/-/issues/25946

**Comment by jackjansen** [comment]
For reference to others coming across this issue in the future: for my formula the solution was to first try to find the package with a normal `find_package(nlohmann_json)` and only use FetchContent if that couldn't find it.

And then adding a `depends_on` to my formula.

Can be closed for me, but I'll leave that to @carlocab in case you want to keep it open.

**Comment by craigscott-crascit** [comment]
I've responded with a [comment](https://github.com/Homebrew/brew/pull/17075#issuecomment-2087634394) on the PR that added `FETCHCONTENT_FULLY_DISCONNECTED`. I recommend reverting that change, it is an abuse of that option and it violates one of the documented preconditions for using it.

**Comment by alebcay** [comment]
This should be addressed via https://github.com/Homebrew/brew/pull/17310.
