### ISSUE TITLE
psql Library not loaded: /usr/local/lib/libpq.5.dylib

### ISSUE THREAD

**Issue by craigcosmo** [Homebrew/brew#17193]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  ksdiff

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 15.1.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.


➜  ~
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: c2ed3327c605c3e738359c9807b8f4cd6fec09eb
Last commit: 2 days ago
Core tap JSON: 30 Apr 17:13 UTC
Core cask tap JSON: 30 Apr 17:13 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I install postgres 16 and run it. When I try the command `psql`, I got this error

<img width="709" alt="CleanShot 2024-05-01 at 00 16 32" src="https://github.com/Homebrew/brew/assets/538657/360821f5-0164-4a29-9481-00c192ff9a0c">

### What happened (include all command output)?

`dyld[28821]: Library not loaded: /usr/local/lib/libpq.5.dylib
  Referenced from: <4A4C9EBE-1868-317F-A86C-2DAE62CA9064> /usr/local/bin/psql
  Reason: tried: '/usr/local/lib/libpq.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file, not in dyld cache)
[1]    28821 abort      psql`

### What did you expect to happen?

postgres database should run

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install postgresql@16
brew services start postgresql@16
brew services list
psql
```

**Comment by gromgit** [comment]
What's the output of `psql --version`? I'm guessing it's not 16.x, since `postgresql@16` is keg-only.

Also check the output of `ls -l /usr/local/bin/psql`.

**Comment by craigcosmo** [comment]
<img width="712" alt="CleanShot 2024-05-01 at 00 46 36" src="https://github.com/Homebrew/brew/assets/538657/153d6f4c-78d0-46ac-b0da-a314dafbf2ff">

**Comment by craigcosmo** [comment]
<img width="713" alt="CleanShot 2024-05-01 at 00 47 25" src="https://github.com/Homebrew/brew/assets/538657/4a41d123-e0c0-4003-91a5-1404a37289f5">

**Comment by gromgit** [comment]
> <img alt="CleanShot 2024-05-01 at 00 47 25" width="713" src="https://private-user-images.githubusercontent.com/538657/326923258-4a41d123-e0c0-4003-91a5-1404a37289f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDAyMDEsIm5iZiI6MTcxNDQ5OTkwMSwicGF0aCI6Ii81Mzg2NTcvMzI2OTIzMjU4LTRhNDFkMTIzLWUwYzAtNDAwMy05MWE1LTE0MDRhMzcyODlmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNzU4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjJlOWNmMDU1ZmY0MDE2NWRlYzI3MDhkZTkwNGRjNjM3OWNlODAwZGRkOGZiODFkOThmNDc2M2UyODFmZWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gGuoOGTgYKRxuqleAN6eo86ucCzbML0GKg9fF-4VjVQ">

That's not Homebrew's `psql`, and I should've noticed earlier that you're running on an ARM64 Mac, for which Homebrew installs exclusively under `/opt/homebrew`.

You're looking for `/opt/homebrew/opt/postgresql@16/bin/psql` instead.

**Comment by craigcosmo** [comment]
<img width="709" alt="CleanShot 2024-05-01 at 01 03 26" src="https://github.com/Homebrew/brew/assets/538657/1cac6740-cac0-45b9-9f16-d52a50c447f0">

**Comment by gromgit** [comment]
Yeah, that's the `psql` you want to run.

**Comment by craigcosmo** [comment]
How can I run that one ?

**Comment by gromgit** [comment]
Just like that: `/opt/homebrew/opt/postgresql@16/bin/psql`.

**Comment by craigcosmo** [comment]
<img width="725" alt="CleanShot 2024-05-01 at 12 29 09" src="https://github.com/Homebrew/brew/assets/538657/26059b0d-6034-48c0-a41a-5c77dcda724c">

Now I got database not found, how can I create/edit database if I can't run postgres ?

**Comment by MikeMcQuaid** [comment]
You're asking us how to use PostgreSQL at this point which is not an issue with Homebrew.

**Comment by craigcosmo** [comment]
I just to do this `rm -rf /usr/local/bin/psql`
And remove all postgres that were installed by homebrew
Then install postgres app from `https://postgresapp.com/downloads.html`
Now my `psql` commpand works 


<img width="717" alt="CleanShot 2024-05-01 at 15 04 20" src="https://github.com/Homebrew/brew/assets/538657/7049a8cb-ac25-48df-84c8-a1be76dc574f">
