### ISSUE TITLE
Ask for analytics permission

### ISSUE THREAD

**Issue by 4chanmoot** [Homebrew/brew#172]
brew should really be asking the user if they're willing to allow analytics collection. Other than the legal implications of just doing it gung ho, it's The Right Thing To Do™

**Comment by mikemcquaid** [comment]
See https://github.com/Homebrew/brew/issues/153 for discussion.

**Comment by DomT4** [comment]
I'd also like to highlight something that keeps being thrown around; pointing vaguely at legal implications isn't in itself any more convincing that CC'ing a lawyer into an email thread. If you can cite precedent and jurisdiction, great, that's something we could work with, but vaguely hinting at legalities isn't useful.

I'd also like to point out if _providing_ an opt-out violates the law in a certain jurisdiction that message hasn't reached either major products which do run on an opt-out basis (The Atom Editor, being an immediate example) or products which don't provide an opt-out at all.

The latter is the vast majority of cases outside FOSS, and outside of browsers. I fairly regularly get analytics attempting to poke through my firewall via apps, and except the firewall there's no opt-out mechanism.

GitHub themselves have had [this exact debate](https://github.com/atom/atom/issues/4966) and the determination there was:

> We have talked to our lawyers. The plan is currently to add in a notification of some kind with a one click metrics disable. Metrics will not be sent to analytics until the notification is dismissed.

Which is exactly what Homebrew does today.
