### ISSUE TITLE
How to further research "brew upgrading to cabal-install-1.24.0.2 after 8 hours still is busy"

### ISSUE THREAD

**Issue by jpluimers** [Homebrew/brew#1720]
How can I research this further:

2013 Retina MacBook Pro with Maverick: brew upgrading to cabal-install-1.24.0.2 after 8 hours still is busy with `sh bootstrap.sh --sandbox`. Title of Terminal tab rapidly switches between ghc and ruby.

Can I just abort the `brew upgrade` then perform the rest of the steps in the issue template?

Log below:

```
$ brew update
Already up-to-date.
$ brew ugprade 
Already up-to-date.
==> Upgrading 4 outdated packages, with result:
cabal-install 1.24.0.2_2, ghc 8.0.1_4, nmap 7.40, pandoc 1.19.1
==> Upgrading cabal-install 
==> Installing dependencies for cabal-install: ghc
==> Installing cabal-install dependency: ghc
==> Using the sandbox
==> Downloading https://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-src.tar.xz
Already downloaded: /Users/jeroenp/Library/Caches/Homebrew/ghc-8.0.1.tar.xz
==> Downloading https://ftpmirror.gnu.org/gmp/gmp-6.1.2.tar.xz
==> Downloading from http://gnu.xl-mirror.nl/gmp/gmp-6.1.2.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/ghc/8.0.1_4/libexec/integer-gmp --with-pic --disable-shared
==> make
==> make check
==> make install
==> Downloading https://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-x86_64-apple-darwin.tar.xz
Already downloaded: /Users/jeroenp/Library/Caches/Homebrew/ghc--binary-8.0.1.tar.xz
==> ./configure --prefix=/private/tmp/ghc-20161222-29730-prtuef/ghc-8.0.1/binary --with-gmp-includes=/usr/local/Cellar/ghc/8.0.1_4/libexec/integer-gmp/include --with-gmp-libraries=/usr/local/Cellar/ghc/8.0.1_4/libexec/integer-gmp/lib --with-ld=ld --with-gcc=clang --with-c
==> make install
==> ./configure --prefix=/usr/local/Cellar/ghc/8.0.1_4 --with-gmp-includes=/usr/local/Cellar/ghc/8.0.1_4/libexec/integer-gmp/include --with-gmp-libraries=/usr/local/Cellar/ghc/8.0.1_4/libexec/integer-gmp/lib --with-ld=ld --with-gcc=clang --with-clang=clang
==> make
==> make install
==> /usr/local/Cellar/ghc/8.0.1_4/bin/ghc-pkg recache
🍺  /usr/local/Cellar/ghc/8.0.1_4: 5,857 files, 1G, built in 415 minutes 59 seconds
==> Installing cabal-install 
==> Downloading https://hackage.haskell.org/package/cabal-install-1.24.0.2/cabal-install-1.24.0.2.tar.gz
######################################################################## 100.0%
==> sh bootstrap.sh --sandbox
```

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this section with a brief summary of your issue **AND** the output of `brew config` and `brew doctor`. Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

### Propose a feature:

Please replace this section with a detailed description of your proposed feature, the motivation for it and alternatives considered. Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by jpluimers** [comment]
45 minutes later it has continued. Not sure why it took that long as CPU was ~5% (with a truckload of Chrome tabs open so that's normal).

Anyway, now it's finished:

```

==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/cabal-install/1.24.0.2_2: 7 files, 32.3M, built in 114 minutes 45 seconds
==> Upgrading nmap 
==> Downloading https://nmap.org/dist/nmap-7.40.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/nmap/7.40 --with-libpcre=included --with-liblua=included --with-openssl=/usr/local/opt/openssl --without-nmap-update --disable-universal --without-zenmap
==> make
==> make install
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/jeroenp/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/jeroenp/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/nmap/7.40: 762 files, 24.4M, built in 1 minute 45 seconds
==> Upgrading pandoc 
==> Downloading https://hackage.haskell.org/package/pandoc-1.19.1/pandoc-1.19.1.tar.gz
######################################################################## 100.0%
==> cabal sandbox init
==> cabal update
==> cabal install --jobs=8 --max-backjumps=100000 --only-dependencies
==> cabal install --jobs=8 --max-backjumps=100000 --prefix=/usr/local/Cellar/pandoc/1.19.1
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/pandoc/1.19.1: 72 files, 88.6M, built in 10 minutes 53 seconds
```

**Comment by MikeMcQuaid** [comment]
> Please replace this section with a brief summary of your issue AND the output of brew config and brew doctor. Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

Please do this in future. If you'd supplied your `brew config` we could tell you why it's taking so long.

**Comment by jpluimers** [comment]
@MikeMcQuaid I wasn't sure if I could do a `brew config` or `brew doctor` in parallel of a running brew, nor if they would show the "before" or "after" state, nor if I could just terminate the running brew without doing harm. My Google Foo didn't get me anywhere either.

**Comment by MikeMcQuaid** [comment]
@jpluimers No worries, just for future reference. It'd still be useful to have it now if you're still interested on how you may be able to speed this up.

**Comment by jpluimers** [comment]
@MikeMcQuaid these are the `after` dumps:

```
# brew config
HOMEBREW_VERSION: 1.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7b8ec0999a40f42bded8739d7808144c00067987
Core tap last commit: 14 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 6.0 build 600
Git: 1.9.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74
macOS: 10.9.5-x86_64
Xcode: 6.2
CLT: N/A
X11: N/A
```

I know 10.9.5 is unsupported and I should have a new machine with the most recent OS X in 2 weeks, but I had some bad Mac OS X upgrade experiences so without a backup machine at hand, I've not upgraded yet.

```
# brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

**Comment by MikeMcQuaid** [comment]
> I know 10.9.5 is unsupported and I should have a new machine with the most recent OS X in 2 weeks,

Cool, yeh, that'll be why it took so long as there's no binary packages there.

**Comment by jpluimers** [comment]
@MikeMcQuaid thanks, that makes a lot of sense.
in 2 weeks that will be over: brand new Mac to test if everything I run works on the new OS X, and if it does: upgrade the old Mac to the new OS X as well.
Am I overly precautions? Probably yes (:

**Comment by MikeMcQuaid** [comment]
@jpluimers Glad to hear that you're going to have it sorted.
