### ISSUE TITLE
Nushell support

### ISSUE THREAD

**Issue by dougg0k** [Homebrew/brew#17221]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Add support for Nushell in the installation and completions.

### What is the motivation for the feature?

Currently it does not work and the steps required are for bash/sh.

Here are installation examples of why this is necessary. 

```
nu ❯ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
/bin/bash: line 1: #!/bin/bash: No such file or directory

nu ✗ bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
bash: line 1: #!/bin/bash: No such file or directory
```

However if I download the sh and execute with bash, the installation goes through. 

---

But then, the last part of the installation are for sh based setup.

```
- Run these two commands in your terminal to add Homebrew to your PATH:
    (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/user/.bashrc
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
```

Nushell does not have `eval` or at least if it does, does not work the same as bash.

---

Lastly, have completions support with it.

### How will the feature be relevant to at least 90% of Homebrew users?

It will be based on the relevancy of the amount of nushell users. It will add more users to Homebrew, not help the current ones.

### What alternatives to the feature have been considered?

None

**Comment by Bo98** [comment]
Second part of your issue makes sense as a feature request - though we'd probably ask for a pull request to add it.

For the first part however, it seems like either nushell is mangling the curl output or you have an extremely buggy `/bin/bash` executable. In either case, you're not even getting to the bash-specific part: your shell is failing on basic POSIX shell syntax in that it can't even parse a shebang properly. In either case, this likely points to a bug outside of Homebrew.

**Comment by dougg0k** [comment]
That actually could be due to the expression `$()`, might not work with nushell also, it's another thing that does not work like the other shells.

**Comment by dougg0k** [comment]
https://github.com/nushell/nushell/issues/2812

https://www.nushell.sh/book/coming_from_bash.html

Workaround example for `eval` and `$()` https://www.nushell.sh/cookbook/ssh_agent.html#workarounds

**Comment by Bo98** [comment]
We give instructions that work on all POSIX-compliant shells. The homepage would get very full if we started listing every non-compliant shell. Note how we don't have install instructions for PowerShell etc.

The `shellenv` instructions is a little different given we can detect the running shell and show the relevant message. We do support some non-POSIX shells there like PowerShell so would be ok improving that part.

**Comment by dougg0k** [comment]
This would work on Nushell `curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash`

**Comment by MikeMcQuaid** [comment]
We're not going to change this for Nushell, sorry.
