### ISSUE TITLE
docs.brew.sh/Manpage does not wrap text properly on mobile

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#17232]
### What were you trying to do (and why)?

Read https://docs.brew.sh/Manpage on mobile

### What happened (include all command output)?

![35AAA23D-7BFF-4CF9-9AD5-CBB77B05FDE6](https://github.com/Homebrew/brew/assets/125011/4f7c6a6e-14d8-4b6f-8b95-15ba1f300d5c)

### What did you expect to happen?

- "Fork me on GitHub" displayed in top-right
- Text wrapped properly
- No horizontal scrollbars	

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
View https://docs.brew.sh/Manpage on mobile
```

**Comment by ZhongRuoyu** [comment]
Some unwrappable lines are too long to fit in the body it seems:

<img width="1440" alt="image" src="https://github.com/Homebrew/brew/assets/25842576/4ecc19e8-a4e1-465b-8b3a-fbdd26aa6c90">

**Comment by Bo98** [comment]
Adding `overflow-wrap` should do it
