### ISSUE TITLE
Imposible update  using WIFI

### ISSUE THREAD

**Issue by ajmasia** [Homebrew/brew#17253]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: 82c2e743a5bcea725f9ca1429e3e21c3088ff904
Last commit: 2 days ago
Core tap JSON: 08 May 05:38 UTC
Core cask tap JSON: 08 May 05:38 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I'm setting up a new machine (M2 Pro) with MacOS Sonoma
I have installed brew and when I try to update or install some Nerdfonts fonts I always get errors connecting to GitHub or trying to download json files. 

With wired connection works fine.

```shell
fatal: unable to access 'https://github.com/Homebrew/homebrew-cask-fonts/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
```

### What happened (include all command output)?

```shell
% brew update -v
Checking if we need to fetch /opt/homebrew...
==> Updating Homebrew...
Checking if we need to fetch /opt/homebrew/Library/Taps/homebrew/homebrew-cask-fonts...
Fetching /opt/homebrew...
fatal: unable to access 'https://github.com/Homebrew/brew/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
Updating /opt/homebrew...
branch 'master' set up to track 'origin/master'.
Reset branch 'stable'
Current branch stable is up to date.
Checking if we need to fetch formula.jws.json...
Checking if we need to fetch cask.jws.json...
Updated cask.jws.json.
Checking if we need to fetch formula_tap_migrations.jws.json...
Checking if we need to fetch cask_tap_migrations.jws.json...
Error: Fetching /opt/homebrew failed!
Failed to download https://formulae.brew.sh/api/formula_tap_migrations.jws.json!
Updated 1 tap (homebrew/cask).
```

### What did you expect to happen?

I should be able to update without problems and install packages normally as when I connect via network cable.

I have done all kinds of diagnostics of the wifi network without errors I have even been to the Apple Store to check the hardware of the machine and everything is ok.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew update -v`
```

**Comment by ajmasia** [comment]
I test it running iterm using Rosetta2 and works! It's strange! Why works using ARM with wired and don't works using wifi?

**Comment by ajmasia** [comment]
Using `HOMEBREW_FORCE_BREWED_CURL=1` works!

**Comment by MikeMcQuaid** [comment]
This is an issue with your connection to GitHub not a Homebrew one so closing, sorry.
