### ISSUE TITLE
don't write .keepme in `bin` and `sbin` if it isn't needed

### ISSUE THREAD

**Issue by rrotter** [Homebrew/brew#17267]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`.keepme` files are written to several directories, originally to prevent the Catalina installer from deleting these directories if they were empty:

```
~ % fd -uu .keepme /opt/homebrew
/opt/homebrew/sbin/.keepme
/opt/homebrew/share/.keepme
/opt/homebrew/include/.keepme
/opt/homebrew/opt/.keepme
/opt/homebrew/Frameworks/.keepme
/opt/homebrew/bin/.keepme
/opt/homebrew/Cellar/.keepme
/opt/homebrew/lib/.keepme
/opt/homebrew/var/homebrew/linked/.keepme
/opt/homebrew/etc/.keepme
```

These files should not be written if they are not actually needed, especially in directories that are expected to be in `$PATH` as this _causes .keepme to show up in zsh tab completion_.

Ideally we would completely remove this feature (i.e. revert #6464), since Catalina is not supported we can reasonably expect brew users not to upgrade to it.

### What is the motivation for the feature?

.keepme is showing up in zsh tab completion, which is undesirable since it's not actually an executable

### How will the feature be relevant to at least 90% of Homebrew users?

Admittedly, this probably won't be noticed one way or another by most users, but if the user does notice this odd file getting hashed by zsh it's confusing.

### What alternatives to the feature have been considered?

If this isn't acceptable for whatever reason, another option is to only ever write .keepme if `$HOMEBREW_PREFIX` is `/usr/local` (i.e. we're running on macos/x64), as even if there is some other macos process that still deletes empty dirs at `/usr/local/*` that shouldn't affect `/opt/homebrew/*` (maybe `/opt/*` but `/opt` is never empty anyway). This wouldn't clean up the issue for x64 users, but would eventually be fixed by attrition as Intel macs are phased out of support.

**Comment by MikeMcQuaid** [comment]
Good idea, agreed ❤️. Reproducing and reverting. Maybe the oldest PR I've ever successfully one-click reverted? 😅
