### ISSUE TITLE
Upgraded to python3.6, lost all pip packages

### ISSUE THREAD

**Issue by kim0** [Homebrew/brew#1727]
I just brew upgraded my python3.5.2 to 3.6 .. While that worked well, I found that "pip list" now is almost empty, while my old pip installed packages are still in `/usr/local/lib/python3.5/site-packages` .. Wondering if this is the intended behaviour, and how can one carry forward those pip installed packages

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.
