### ISSUE TITLE
HOMEBREW_NO_INSTALL_FROM_API not working for dependencies with bottle

### ISSUE THREAD

**Issue by agowa** [Homebrew/brew#17328]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master
```

### Verification

- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.0-71-g79cb329
ORIGIN: https://github.com/Homebrew/brew
HEAD: 79cb329f5979f5ee4b9a80c585721684b7730eaa
Last commit: 5 hours ago
Core tap HEAD: 5488bde9fe72f4137ad5570589be58e2ef8b6650
Core tap last commit: 5 minutes ago
Core tap branch: agowa-patch-qemu-fix
Core tap JSON: 17 May 13:28 UTC
Core cask tap HEAD: 9b273f4d73b182e0ff35adddf2ccff596dacabf5
Core cask tap last commit: 3 hours ago
Core cask tap JSON: 17 May 13:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 11
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 11-core 64-bit dunno
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

While developing my formulaes (one existing changed and extended by a dependency on a new one I created in my fork). I encountered errors with the dependency resolver as it tries to install the new formulae using ghcr.io even though `HOMEBREW_NO_INSTALL_FROM_API=1`

### What happened (include all command output)?

brew tries to fetch the dependency from ghcr.io and gets a HTTP-404 and therefore fails installing my formulae.

### What did you expect to happen?

Brew not trying to contact ghcr.io and instead also thereby also installing my new (not yet upstreamed) dependency correctly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1st follow the dev instructions: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request
2nd create a new formulae "A" in that fork
3rd extend an existing formulae "B" using `depends_on "A"`
4th `git pull --all` the local homebrew-core
5th `HOMEBREW_NO_INSTALL_FROM_API=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source B`
```

**Comment by carlocab** [comment]
Try
```
HOMEBREW_NO_INSTALL_FROM_API=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source A B
```
or, otherwise:
```
HOMEBREW_NO_INSTALL_FROM_API=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source A
HOMEBREW_NO_INSTALL_FROM_API=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source B
```

**Comment by agowa** [comment]
That's the workaround I'm currently using. But I think I just now found what the error was. I accidentally copied these three lines into my formula:
```
bottle do
    sha256 cellar: :any_skip_relocation, all: "c95213126a4de3d3ab508fbfc7f23f11ece2f0011d3a6d251d7f79034376066e"
  end
```

It's a docs issue. The Developer Docs I referenced before only say:

> If there’s a bottle do block in the formula, don’t remove or change it; we’ll update it when we merge your PR.

however if it's a new formulae and pulled in as dependency then this causes the above HTTP-404 apparently...

**Comment by carlocab** [comment]
This is the first I'm hearing of the issue, so I don't think it's something that trips up many contributors. (At least, not enough for them to complain to us about it.)

We'll review a PR to improve the documentation, but this doesn't seem like a bug to me.
