### ISSUE TITLE
Formula should be able to depend on cask

### ISSUE THREAD

**Issue by agowa** [Homebrew/brew#17326]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Currently a formula cannot have a dependency on a cask. Like e.g. "MaciASL" one. Furthermore I noticed some quirks when trying to use it anyway.
Writing `depends_on "maciasl" => [:build, :cask]` resulted in `brew info` showing that dependency as `maciasl --cask` (which made me think that this was the correct way of specifying it and that it was supported) but when trying to build it did this instead. Here the strange thin is that the cask is named `maciasl`, it says it looked for formulae and casks with that name but then suggests to install `macchina` and `macast` instead? It even outputs `maciasl` (which should have been an exact match)...:
```
Warning: No available formula with the name "maciasl" (dependency of qemu). Did you mean macchina?
==> Searching for similarly named formulae and casks...
==> Formulae
macchina

To install macchina, run:
  brew install macchina

==> Casks
macast                                     maciasl                                    macpass

To install macast, run:
  brew install --cask macast
```

### What is the motivation for the feature?

using the maciasl cask as a build/optional dependency within a formula

### How will the feature be relevant to at least 90% of Homebrew users?

There are a bunch of questions about doing exactly this on stackoverflow, so others clearly have the same issue.
e.g. https://stackoverflow.com/questions/35461948/syntax-for-a-homebrew-formula-depending-on-a-cask, https://stackoverflow.com/questions/52370449/formula-dependency-for-homebrew, https://unix.stackexchange.com/questions/449138/brew-formula-how-can-i-define-cask-and-external-dependencies, 

### What alternatives to the feature have been considered?

crude hacks like:
```
def install
  # Resolve cask dependencies
  system "/usr/local/bin/brew", "cask", "install", "osxfuse"
```

**Comment by MikeMcQuaid** [comment]
As you've noted: formulae cannot depend on casks, by design.

The closest equivalent to this would be to create a `Requirement`.

**Comment by carlocab** [comment]
See https://github.com/gromgit/homebrew-fuse/blob/ac8384ee5e8592e24b953621fbcdd1de61bf0f05/require/macfuse.rb for an example of creating a `Requirement` similar to the one you need.
