### ISSUE TITLE
Can't find socket when using emacsclient as homebrew editor

### ISSUE THREAD

**Issue by tshu-w** [Homebrew/brew#17334]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.0-87-ge9d989b
ORIGIN: https://github.com/Homebrew/brew
HEAD: e9d989bdea3dafe0227c45861d017ccd4a93bd3c
Last commit: 14 hours ago
Core tap JSON: 19 May 05:53 UTC
Core cask tap JSON: 19 May 05:53 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BUNDLE_USER_CACHE: /Users/wangtianshu/.cache/bundle
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacsclient
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I want to use `emacsclient` as my `EDITOR` for brew edit. This command opens a document in an already-running emacs process.

### What happened (include all command output)?

```console
$ brew edit karabiner-elements
Editing /opt/homebrew/Caskroom/karabiner-elements/.metadata/14.13.0/20240416114923.815/Casks/karabiner-elements.json
emacsclient: can't find socket; have you started the server?
emacsclient: To start the server in Emacs, type "M-x server-start".
emacsclient: No socket or alternate editor.  Please use:

	--socket-name
	--server-file      (or environment variable EMACS_SERVER_FILE)
	--alternate-editor (or environment variable ALTERNATE_EDITOR)
Error: Failure while executing; `emacsclient /opt/homebrew/Caskroom/karabiner-elements/.metadata/14.13.0/20240416114923.815/Casks/karabiner-elements.json` exited with 1.
```

Copy from: https://github.com/Homebrew/homebrew-core/issues/72968
> The command fails because brew edit does not preserve the shell's TMPDIR variable. The appropriate /private/var directories seems to be allowed by sandbox-exec in sandbox.rb, but it looks like TMPDIR is set to the value of HOMEBREW_TEMP in build.rb. https://github.com/Homebrew/brew/blob/94431ce104fdf23e62d02c93d9600a59c6c152b3/Library/Homebrew/sandbox.rb#L50-L56
> https://github.com/Homebrew/brew/blob/94431ce104fdf23e62d02c93d9600a59c6c152b3/Library/Homebrew/build.rb#L128-L132

### What did you expect to happen?

> This has worked in the past. It appears to have been broken by the upgrade to emacs version 27. There is a reference to a [change in emacsclient socket behavior](https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS?h=emacs-27#n314) in the changelog, but it is not totally clear that this is the root cause.
> 
> emacsclient will put its socket in a subdirectory of $TMPDIR. The sandbox seems to change this from a subdirectory of /var/folders to /private/tmp

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See here: https://github.com/Homebrew/homebrew-core/issues/72968
```

**Comment by Bo98** [comment]
Original issue analysis is incorrect as the sandbox doesn't apply here.

But setting `HOMEBREW_TEMP` does indeed work: `HOMEBREW_TEMP=$TMPDIR brew edit karabiner-elements`

**Comment by tshu-w** [comment]
> Original issue analysis is incorrect as the sandbox and `build.rb` doesn't apply here.

Thank you for pointing this out.

> But there is overall environment filtering going on and setting HOMEBREW_TEMP does work: HOMEBREW_TEMP=$TMPDIR brew edit karabiner-elements. This perhaps should happen by default for brew edit but currently doesn't.

Is there any side effect if the user sets `HOMEBREW_TEMP` to `TMPDIR` globally? Or do I need to wait for changes from `brew edit`?

**Comment by carlocab** [comment]
> Is there any side effect if the user sets `HOMEBREW_TEMP` to `TMPDIR` globally? 

It could break some builds that get confused by the long paths that `TMPDIR` typically point to.

If you don't build anything from source you'll probably be fine. If you do encounter build failures, you can always try to `unset HOMEBREW_TEMP`.

**Comment by tshu-w** [comment]
Thank you for your reply ;), then I will temporarily leave this issue open. Feel free to close it if your team thinks it should not be implemented for `brew edit`.

**Comment by carlocab** [comment]
You could probably also set
```
TMPDIR=/private/tmp
```
as a likely safer alternative (though I don't think `HOMEBREW_TEMP=$TMPDIR` is that unsafe either).

But we should try fixing this for `brew edit`. PRs welcome -- if you're game to give it a try, we'd be happy to help you finish off even a half-working attempt.

**Comment by tshu-w** [comment]
> PRs welcome -- if you're game to give it a try, we'd be happy to help you finish off even a half-working attempt.

Sure, will give it a try when I am free.

**Comment by MikeMcQuaid** [comment]
> But we should try fixing this for `brew edit`. PRs welcome -- if you're game to give it a try, we'd be happy to help you finish off even a half-working attempt.

Agreed. Please scope this logic entirely into `dev-cmd/edit.rb` if so, thanks!

**Comment by tshu-w** [comment]
Hi, after a rough reading of the [code](https://github.com/Homebrew/brew/blob/49609ecf68b59a1585edf8a0da02695d8fc7fcb6/Library/Homebrew/sandbox.rb#L134) I have some doubts.

I don't quite understand why `HOMEBREW_TEMP=$TMPDIR brew edit karabiner-elements` can work. How does setting `HOMEBREW_TEMP` affect the access to the sock file in `TMPDIR` by [exec](https://github.com/Homebrew/brew/blob/49609ecf68b59a1585edf8a0da02695d8fc7fcb6/Library/Homebrew/dev-cmd/edit.rb#L29-L74) `emacsclient`? Is it because `TMPDIR` is reset to `HOMEBREW_TEMP` during command execution (not found in the code) or is there another reason?

**Comment by MikeMcQuaid** [comment]
> Is it because `TMPDIR` is reset to `HOMEBREW_TEMP` during command execution (not found in the code)

Yes, this is done by `bin/brew`.

**Comment by tshu-w** [comment]
> > Is it because `TMPDIR` is reset to `HOMEBREW_TEMP` during command execution (not found in the code)
> 
> Yes, this is done by `bin/brew`.

But `bin/brew` is just [filter `TMPDIR`](https://github.com/Homebrew/brew/pull/14228) and I miss up the logic that sets `TMPDIR` back to `HOMEBREW_TEMP` in `dev-cmd/edit.rb` or other places like https://github.com/Homebrew/brew/blob/ff950e6629f7a09fabc8fd21048d4ab204a9fd27/Library/Homebrew/utils/gems.rb#L99-L101. So I am really confused why `HOMEBREW_TEMP=$TMPDIR brew edit karabiner-elements` work.
