### ISSUE TITLE
gcc-4.8.5 on Mac does not find C header files.

### ISSUE THREAD

**Issue by efromberg** [Homebrew/brew#1734]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this section with a brief summary of your issue **AND** the output of `brew config` and `brew doctor`. Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

### Propose a feature:

Please replace this section with a detailed description of your proposed feature, the motivation for it and alternatives considered. Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by efromberg** [comment]
Downloaded gcc-4.8 onto my new Mac. Attempted to compile a very simple c++ program, but got errors when reading the first include <cstdlib> : "fatal error: stdlib.h: No such file or directory". The program compiled with the Xcode gcc.  It seems that the C headers are not found, though there is a full complement of C++ headers. Following is the (1) test program, (2) brew update output, (3) brew doctor output, (4) brew config.

(1) 
Installed Xcode CL tools.
  $g++ -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Installed g++ 4.8 with homebrew
$g++-4.8 -v
Edgars-iMac:MatCalc efr$ g++-4.8 -v
Using built-in specs.
COLLECT_GCC=g++-4.8
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@4.8/4.8.5/libexec/gcc/x86_64-apple-darwin16.1.0/4.8.5/lto-wrapper
Target: x86_64-apple-darwin16.1.0
Configured with: ../configure --build=x86_64-apple-darwin16.1.0 --prefix=/usr/local/Cellar/gcc@4.8/4.8.5 --libdir=/usr/local/Cellar/gcc@4.8/4.8.5/lib/gcc/4.8 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.8 --with-gmp=/usr/local/opt/gmp@4 --with-mpfr=/usr/local/opt/mpfr@2 --with-mpc=/usr/local/opt/libmpc@0.8 --with-cloog=/usr/local/opt/cloog@0.18 --with-isl=/usr/local/opt/isl@0.11 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew GCC 4.8.5' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues MAKEINFO=missing --with-build-config=bootstrap-debug --enable-plugin --disable-nls --enable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
Thread model: posix
gcc version 4.8.5 (Homebrew GCC 4.8.5) 

Compiled gcctst.cpp with Xcode g++:
Edgars-iMac:MatCalc efr$ g++ -o gcctst gcctst.cpp      worked well and executed.
Edgars-iMac:MatCalc efr$

Compiled gcctst.cpp with homebrew g++-4.8
Edgars-iMac:MatCalc efr$ g++-4.8 -o gcctst gcctst.cpp
In file included from gcctst.cpp:7:0:
/usr/local/Cellar/gcc@4.8/4.8.5/include/c++/4.8.5/cstdlib:72:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
                    ^
compilation terminated.

Program source: ( gcctst.cpp)
/* using Homebrew gcc 4.8.5
$ g++ -o gcctst gcctst.cpp
ERRORS cannot find C includes

*/

# include <cstdlib>		// fatal error: stdlib.h: No such file or directory
# include <iostream>	// cwchar:44:19: fatal error: wchar.h: No such file or directory
# include <cmath>
# include <ctime>

using namespace std;

int main ( int argc, char *argv[] )
{
  return 0;
}

(2) 
Edgars-iMac:MatCalc efr$ brew update
Updated 1 tap (homebrew/core).
==> Updated Formulae
apache-brooklyn-cli     harfbuzz                libvisio                pazpar2                 yaz
axel                    icu4c                   mitmproxy               sbtenv                  zebra
couchdb                 libcdr                  mpd                     sile                    zorba
dwdiff                  libmspub                p11-kit                 webkitgtk

(3)
Edgars-iMac:MatCalc efr$ brew doctor
Your system is ready to brew.

(4)
Edgars-iMac:MatCalc efr$ brew config
HOMEBREW_VERSION: 1.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e151bf001ec17ff2d6ac5683448a4bfbd083235c
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.2-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A
Edgars-iMac:MatCalc efr$ 


It seems that gcc-4.8 needs to find the c include files somehow.
Thanks very much for any help that you can render.
efromberg

**Comment by MikeMcQuaid** [comment]
> Downloaded gcc-4.8 onto my new Mac.

How did you install it (i.e. what `brew install` command)? Thanks!

> Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

It sounds like this is just a problem with the gcc-4.8 formula, no?

**Comment by efromberg** [comment]
Mike,    I installed Homebrew, then to install gcc:
    $ brew install gcc48
which seemed to work:    $ gcc-4.8 -vgives:        gcc version 4.8.5 (Homebrew GCC 4.8.5)
I found that I could use gcc-4.8 with the options:$ g++-4.8 -o gcctst gcctst.cpp -I/usr/include -L/usr/lib -lquadmath
Is this the normal procedure?  Should some environment variables be set up?gcc-4.8 doesn't seem to have any of the C include files in its download, even though they are referenced in the C++ include files.With the above -I and -L options, it is using the includes and libraries from the Mac/Xcode gcc which is version 4.2.1:
$ gcc -vEdgars-iMac:MatCalc efr$ gcc -vConfigured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1Apple LLVM version 8.0.0 (clang-800.0.42.1)Target: x86_64-apple-darwin16.3.0Thread model: posixInstalledDir: /Library/Developer/CommandLineTools/usr/bin
This mixture of gcc-4.8 and gcc-4.2 could lead to a problem somewhere down the line. Thanks for your help,Edgar Romberg

**Comment by MikeMcQuaid** [comment]
I'm afraid I'm not sure what's going on here but @mistydemeo or @ilovezfs may.

**Comment by ilovezfs** [comment]
Please make sure you have both Xcode.app and the CLT installed first. Then uninstall gcc48, and install it again.

**Comment by efromberg** [comment]
Thanks for your reply.Installed Xcode, deleted, reinstalled gcc48 with $brew install gcc48.Wrote a simple test program which defines a  shared_ptr<double>.  It compiled but also gave warnings:     warning: section "__textcoal_nt" is deprecated,These warnings do not appear in the Xcode  gcc 4.2.1 nor on Ubuntu gcc 4.8.5.Thanks for you help,Edgar Romberg

**Comment by ilovezfs** [comment]
Those warnings are fixed in GCC head but are unlikely to be backported unless people someone opens a PR to do so.

**Comment by ilovezfs** [comment]
>It compiled

Closing since the original problem is no longer affecting you
