### ISSUE TITLE
"arrow" cli output is weird with ligatures enabled

### ISSUE THREAD

**Issue by driverkt** [Homebrew/brew#17362]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Using the [monaspace font](https://monaspace.githubnext.com), with ligatures enabled (specifically stylistic set ss03), makes the arrow (`==>`) in the output look strange. VSCode renders it as one ligature layered over another (`==` and `=>`). [iTerm](https://iterm2.com) just uses the last two characters as a ligature and leaves the first `=` alone. Consider changing this arrow, if possible. 

### What is the motivation for the feature?

Cleaner output for users of fonts with ligatures.

### How will the feature be relevant to at least 90% of Homebrew users?

I can't say for sure how many people use fonts with ligatures. 🤷🏻‍♂️

### What alternatives to the feature have been considered?

No action.

**Comment by MikeMcQuaid** [comment]
Homebrew has used this output format for 15 years. I think the fix here is "don't use ligatures if you don't want this to look weird", sorry.
