### ISSUE TITLE
WTF!  

### ISSUE THREAD

**Issue by mischievous** [Homebrew/brew#17363]
### `brew doctor` output

```shell
Does not matter...

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  logstream
  display_manager
  Foundation
  kextdebug
  emsdk
  sshfs_androidmedia
  import

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isc-dhcp

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  logstream
  display_manager
  Foundation
  kextdebug
  emsdk
  sshfs_androidmedia
  import

Warning: Your Xcode (14.3.1) is outdated.
Please update to Xcode 15.1 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: e0bc557e7b991cb23583679e1cf1c8a92b793aeb
Last commit: 5 days ago
Core tap JSON: 24 May 19:10 UTC
Core cask tap JSON: 24 May 19:10 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.cFkvSgK8L8/org.xquartz:0
HOMEBREW_MAKE_JOBS: 24
Homebrew Ruby: 3.3.1 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 24-core 64-bit skylake
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Volumes/Development/Xcode.14.3.1.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 13.6.4-x86_64
CLT: 15.1.0.0.1.1700200546
Xcode: 14.3.1 => /Volumes/Development/Xcode.14.3.1.app/Contents/Developer
```

### What were you trying to do (and why)?

I brew installed the openjdk

### What happened (include all command output)?

While installing openjdk brew removed my working /usr/local/Celler/openocd, also proceeded to replace my working python3.11 (aka python3) with python3.12 which does not work because it is missing all the installed python3.11 packages!

Brew use to be good then I guess a bunch of mentally deficient people started to help and have mode the system unusable now. 

Brew should never remove something from a Cellar without an express command to do so!  This might be the bloody packages or might be something else in brew but it also needs to stop trying to update my python3.11 to python3.12.  I am a software developer for a large Aerospace company I don't have time for the bullshit to upgrade my bloody tools because someone thinks I should. 

### What did you expect to happen?

Just install openjdk

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openjdk
```

**Comment by p-linnane** [comment]
This should be resolved by https://github.com/Homebrew/brew/pull/17364.

I am also permanently banning you from interacting with Homebrew on GitHub due to your derogatory comment about people with disabilities.
