### ISSUE TITLE
`warning: finalizer references object to be finalized` on every `brew audit --cask`

### ISSUE THREAD

**Issue by unitof** [Homebrew/brew#17374]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.2-14-g44d0d64
ORIGIN: https://github.com/Homebrew/brew
HEAD: 44d0d64e79895b51064ff3ba670de126f463825e
Last commit: 88 minutes ago
Core tap HEAD: 94c4a182ae09dd52d5a66da66eaedb9b3074967b
Core tap last commit: 25 minutes ago
Core tap JSON: 27 May 16:08 UTC
Core cask tap origin: git@github.com:Homebrew/homebrew-cask
Core cask tap HEAD: 70bf2608ea401e809be79cd0191b092c6705c415
Core cask tap last commit: 14 minutes ago
Core cask tap JSON: 27 May 16:08 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: subl
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

Audit casks, in order to submit Cask-related PRs

### What happened (include all command output)?

Any `brew audit` on a Cask now includes the warning:

```
/opt/homebrew/Library/Homebrew/cask/audit.rb:52: warning: finalizer references object to be finalized
```

This is also happening in [GitHub Actions runs](https://github.com/Homebrew/homebrew-cask/actions/runs/9257405937/job/25465500388?pr=174963#step:9:10).

I believe this stems from https://github.com/Homebrew/brew/pull/17358.

### What did you expect to happen?

No warnings related to brew's internal code. No output if `brew audit --cask` passes.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
~ ▶ brew audit --cask mimestream
/opt/homebrew/Library/Homebrew/cask/audit.rb:52: warning: finalizer references object to be finalized
~ ▶ 
```
```

**Comment by samford** [comment]
Thanks for the issue. I didn't see this warning when I was originally testing the `@tmpdir` removal PR but I now see this warning when I run `brew audit`. I created a PR to rework the implementation and avoid this warning (https://github.com/Homebrew/brew/pull/17377).
