### ISSUE TITLE
Add support for excluding packages

### ISSUE THREAD

**Issue by kustodian** [Homebrew/brew#17382]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Almost all Linux package managers support excluding packages so that they can never be installed. For example in YUM you can set in `/etc/yum.conf` you can set `exclude=package1 package2` so those two packages cannot be installed via YUM.

### What is the motivation for the feature?

My use case is that we install dotnet packages from a custom tap, which are in conflict with the official `dotnet` packages so I would like to disallow the official `dotnet` packages to be ever installed especially as a dependency of some other packages. 

### How will the feature be relevant to at least 90% of Homebrew users?

I can't be the only user that has this use case because all other packages managers I used (YUM, APT, Pacman, DNF,...) have this feature. 

### What alternatives to the feature have been considered?

I didn't find a solution to this.

**Comment by MikeMcQuaid** [comment]
`HOMEBREW_FORBIDDEN_FORMULAE` and `HOMEBREW_FORBIDDEN_CASKS` is how you can do this.

**Comment by bevanjkay** [comment]
Have you tried setting the `HOMEBREW_FORBIDDEN_FORMULAE` environment variable?
https://docs.brew.sh/Manpage#environment

**Comment by kustodian** [comment]
I didn't try it. I couldn't find it and none of the AI chat bots suggested this solution. It's very hidden and hard to find, probably because of the strange name compared to other package managers.

**Comment by MikeMcQuaid** [comment]
> I couldn't find it and none of the AI chat bots suggested this solution.
> It's very hidden and hard to find

Don't use AI chat bots to for this, use Google/DuckDuckGo/whatever instead.

AI chat bots only work when their training data includes our documentation and it's up-to-date (which it rarely is). Even then, they will often spit out completely wrong answers.

It's not at all hidden and is clearly documented. Next time, please read the docs before asking for help and please consider saying "thank you" when someone answers your question.
