### ISSUE TITLE
Some codes are written twice in brew and brew.sh

### ISSUE THREAD

**Issue by xycabcd** [Homebrew/brew#17389]
Mostly codes for checking enviroment. 
One of them is "Homebrew must need current working directory exist"

may be one of the reasons why eveytime I run brew it wait few seconds and then run.

**Comment by miccal** [comment]
> Please note we will close your issue without comment if you do not correctly fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
