### ISSUE TITLE
ome codes are written twice in brew and brew.sh

### ISSUE THREAD

**Issue by xycabcd** [Homebrew/brew#17391]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Mostly codes for checking enviroment.
One of them is "Homebrew must need current working directory exist"

may be one of the reasons why eveytime I run brew it wait few seconds and then run.

### What is the motivation for the feature?

Make Homebrew faster.

### How will the feature be relevant to at least 90% of Homebrew users?

They can wait less time before Homebrew say something.

### What alternatives to the feature have been considered?

Delete one copy of these codes

**Comment by MikeMcQuaid** [comment]
We'll review PRs to make Homebrew faster. This issue does not provide any evidence those commands are causing slowdown.
