### ISSUE TITLE
`==> ` prefix for installation status and/or deprecation status (and possibly others)

### ISSUE THREAD

**Issue by retrobit** [Homebrew/brew#17420]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When calling `brew info <formula>` or `brew info --cask <cask>`, installation status and/or deprecation status (and possibly others) should be prefixed with `==> ` and **bold** lettering, like **`Dependencies`** and **`Options`**, etc. are.

I don't know Ruby (yet), but from a brief look it seems like there are "cop" or "helper module" changes that could allow these. Please let me know if this is something you would be interesting in accepting a PR for and I can work on it.

As an example, the following:
```
Deprecated because it has an archived upstream repository!
Installed
```

Would instead print:
```
==> Status
Deprecated because it has an archived upstream repository!
==> Installation
Installed
```

But preferably after the formula description, like the rest of the `==> ` prefixed items

Attached is a screenshot of a current example of output that could benefit:

![`brew info neofetch` output](https://github.com/Homebrew/brew/assets/6226450/a3633dec-ebe0-423d-81b7-1d13c852e79f)

### What is the motivation for the feature?

Subjectively, I think that these two are important enough to be read more easily, along with existing `==> ` prefixed lines.

Installation is user/system-specific, not a part of the project repository.

Deprecation status is arguably separate from the project information itself, as while it's inferred from whether or not the project repository is "discontinued upstream" or "archived", "deprecated" is a status given by Homebrew to the formula or cask itself.

### How will the feature be relevant to at least 90% of Homebrew users?

Instead of finding these details embedded in the description of the formula/cask info somewhere, it will be highly visible and improves overall user experience and polish

### What alternatives to the feature have been considered?

None - could leave as-is, this is simply a quality-of-life (QoL) request.

**Comment by MikeMcQuaid** [comment]
Passing on this for now, will consider if we get future requests along these lines but this seems to be mostly personal preference as it'll trade off length for perceived readability.
