### ISSUE TITLE
Create a 'link --overwrite' equivalent for 'install'

### ISSUE THREAD

**Issue by HaraldNordgren** [Homebrew/brew#1742]
Build sometimes fail on the link step, prompting me to link and overwrite. I would like to be able to do this straight away, as an option for the install command.

Example scenario:

```
==> Installing gcc 
==> Downloading https://homebrew.bintray.com/bottles/gcc-6.3.0.sierra.bottle.tar
==> Pouring gcc-6.3.0.sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/c++
Target /usr/local/include/c++
already exists. You may want to remove it:
  rm '/usr/local/include/c++'

To force the link and overwrite all conflicting files:
  brew link --overwrite gcc

To list all files that would be deleted:
  brew link --overwrite --dry-run gcc
```

**Comment by MikeMcQuaid** [comment]
I'm not sure I understand what advantage this provides over `brew link --overwrite`?

**Comment by HaraldNordgren** [comment]
I want to be able to automate the process. The alternative might be to run 

    brew install <formula> || brew link --overwrite <formula>

which seems pretty insecure considering that the install process could fail in a million other ways not actually related to the linking.

**Comment by slayoo** [comment]
Hi, Let me take the freedom to ask a related question, even though the issue is closed:
Getting the same error (https://travis-ci.org/tvatter/vinecopulib/builds/197634424#L445) I wonder if the later error in the installation (https://travis-ci.org/tvatter/vinecopulib/builds/197634424#L540) is not caused by the link issue? Thanks for help, Sylwester

**Comment by MikeMcQuaid** [comment]
@slayoo We don't provide support for Travis CI builds, sorry.

**Comment by HaraldNordgren** [comment]
This is indeed is the same issue. The error output is telling you to run

    rm '/usr/local/include/c++'

so you could get around the issue by running that before the failing command.

**Comment by HaraldNordgren** [comment]
The obvious problem what this approach is that you have run the job and fail once to figure it what needs to be done. And a script might produce several link errors that have to be handled separately.

**Comment by slayoo** [comment]
Thanks for your replies!

**Comment by luisdavim** [comment]
why is this closed?

**Comment by MikeMcQuaid** [comment]
@luisdavim Because we don't leave open feature requests we're not planning on working on.
