### ISSUE TITLE
Cannot upgrade redis-stack-server

### ISSUE THREAD

**Issue by BrentWilkins** [Homebrew/brew#17458]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  cowsay
  greed
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.3-85-gf8b1d1f
ORIGIN: https://github.com/Homebrew/brew
HEAD: f8b1d1f56cb19212b89e385e000ca3921912abeb
Last commit: 2 days ago
Core tap HEAD: 064b4e05a222c6a3792783394df60bb04f8686ad
Core tap last commit: 12 minutes ago
Core tap JSON: 10 Jun 15:01 UTC
Core cask tap HEAD: 88afdd4ea082029ccf6a2d202f2f3fa0050c566d
Core cask tap last commit: 56 minutes ago
Core cask tap JSON: 10 Jun 15:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.4S5SIdWe5i/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.2 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew upgrade`
Just trying to update my packages.

### What happened (include all command output)?

~ brew upgrade --verbose
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
redis-stack/redis-stack/redis-stack-server 7.2.0-v10 -> 7.2.0-v11
==> Upgrading redis-stack-server
==> Downloading https://redismodules.s3.amazonaws.com/redis-stack/redis-stack-server-7.2.0-v11.monterey.arm64.zip
Already downloaded: /Users/brent/Library/Caches/Homebrew/downloads/cbe9e09e832e343aeee6b5a2d88aa8d93b07a72d575bf828512b600c8664621a--redis-stack-server-7.2.0-v11.monterey.arm64.zip
==> Verifying checksum for 'cbe9e09e832e343aeee6b5a2d88aa8d93b07a72d575bf828512b600c8664621a--redis-stack-server-7.2.0-v11.monterey.arm64.zip'
Warning: Cannot verify integrity of 'cbe9e09e832e343aeee6b5a2d88aa8d93b07a72d575bf828512b600c8664621a--redis-stack-server-7.2.0-v11.monterey.arm64.zip'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "3a219a11af1eb96dac3684512abb1e23c588ff9a2dbe0ba4817a7f1e3f88dda2"
All dependencies satisfied.
==> Purging files for version 7.2.0-v11 of Cask redis-stack-server
Error: redis-stack/redis-stack/redis-stack-server: undefined method `exists?' for class File
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240404151642.382/Casks/redis-stack-server.rb:34:in `block (3 levels) in load'
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240404151642.382/Casks/redis-stack-server.rb:32:in `each'
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240404151642.382/Casks/redis-stack-server.rb:32:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:30:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:474:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:471:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:430:in `start_upgrade'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:195:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:260:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:138:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting

### What did you expect to happen?

Upgrade may out of date packages.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade --verbose
```

**Comment by miccal** [comment]
Please report this to the tap that hosts this Cask: https://github.com/redis-stack/homebrew-redis-stack.
