### ISSUE TITLE
Add a way to append linuxbrew to the end of path.

### ISSUE THREAD

**Issue by s0urce-c0de** [Homebrew/brew#17477]
### Verification

- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Add a flag that adds linuxbrew to the end of path instead of the start.

### What is the motivation for the feature?

On my linux system, I prefer using system installed binaries before homebrew install ones.

### How will the feature be relevant to at least 90% of Homebrew users?

It let them use system installed binaries instead of all homebrew binaries. This may also affect SUID root binaries like `mount`.

### What alternatives to the feature have been considered?

Using some sort of complicated sed statement.

**Comment by MikeMcQuaid** [comment]
> Add a flag

To what?

**Comment by s0urce-c0de** [comment]
`/home/linuxbrew/.linuxbrew/bin/brew shellenv`. Mabye add `--end-of-path`

**Comment by MikeMcQuaid** [comment]
If it's not added to the front of your PATH `brew doctor` will (intentionally) complain. Sorry, passing on this.
