### ISSUE TITLE
Failed to install Homebrew Portable Ruby

### ISSUE THREAD

**Issue by msherafatian** [Homebrew/brew#17481]
### `brew doctor` output

```shell
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:5c86a23e0e3caee1a4cfd958ed7d50a38e752ebaf2e7c5717e5c8eabaa6e9f12
Already downloaded: /Users/username/Library/Caches/Homebrew/portable-ruby-3.3.2.el_capitan.bottle.tar.gz
==> Pouring portable-ruby-3.3.2.el_capitan.bottle.tar.gz
/usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: line 230:  5308 Killed: 9               "./${VENDOR_VERSION}/bin/${VENDOR_NAME}" --version > /dev/null
Error: Failed to install ruby 3.3.2!
Error: Failed to install Homebrew Portable Ruby (and your system version is too old)!
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:5c86a23e0e3caee1a4cfd958ed7d50a38e752ebaf2e7c5717e5c8eabaa6e9f12
Already downloaded: /Users/sherafatianmasih/Library/Caches/Homebrew/portable-ruby-3.3.2.el_capitan.bottle.tar.gz
==> Pouring portable-ruby-3.3.2.el_capitan.bottle.tar.gz
/usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: line 230:  5618 Killed: 9               "./${VENDOR_VERSION}/bin/${VENDOR_NAME}" --version > /dev/null
Error: Failed to install ruby 3.3.2!
Error: Failed to install Homebrew Portable Ruby (and your system version is too old)!
```

### What were you trying to do (and why)?

brew

### What happened (include all command output)?

==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:5c86a23e0e3caee1a4cfd958ed7d50a38e752ebaf2e7c5717e5c8eabaa6e9f12
Already downloaded: /Users/sherafatianmasih/Library/Caches/Homebrew/portable-ruby-3.3.2.el_capitan.bottle.tar.gz
==> Pouring portable-ruby-3.3.2.el_capitan.bottle.tar.gz
/usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: line 230:  5618 Killed: 9               "./${VENDOR_VERSION}/bin/${VENDOR_NAME}" --version > /dev/null
Error: Failed to install ruby 3.3.2!
Error: Failed to install Homebrew Portable Ruby (and your system version is too old)!

### What did you expect to happen?

not give me an error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:5c86a23e0e3caee1a4cfd958ed7d50a38e752ebaf2e7c5717e5c8eabaa6e9f12
Already downloaded: /Users/sherafatianmasih/Library/Caches/Homebrew/portable-ruby-3.3.2.el_capitan.bottle.tar.gz
==> Pouring portable-ruby-3.3.2.el_capitan.bottle.tar.gz
/usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: line 230:  5618 Killed: 9               "./${VENDOR_VERSION}/bin/${VENDOR_NAME}" --version > /dev/null
Error: Failed to install ruby 3.3.2!
Error: Failed to install Homebrew Portable Ruby (and your system version is too old)!
```

**Comment by bevanjkay** [comment]
Please fill out the issue template correctly instead of pasting the same thing in each input.

**Comment by msherafatian** [comment]
I do get the same output from that.

**Comment by bevanjkay** [comment]
You need to include the output of `brew config` and `brew doctor` as asked in the issue template above or the issue will be closed.

**Comment by msherafatian** [comment]
This is the output that these commands will generate.

**Comment by bevanjkay** [comment]
What MacOS version are you running? It looks like it may be unsupported by Homebrew.

@Bo98 Should we be forcing a fallback to system ruby in these cases so that `brew doctor` and `brew config` work even with a broken install? Not sure what's expected here.

**Comment by Bo98** [comment]
99% of the time I've seen `Killed: 9` before it's been third-party security software flagging portable Ruby (potentially from it being unsigned).

See https://github.com/Homebrew/brew/issues/17422 in case this applies to you.

> Should we be forcing a fallback to system ruby

System Ruby on macOS is too old.

**Comment by msherafatian** [comment]
I am on Mac OS Sonoma 14.5. I have looked at [this ](https://github.com/Homebrew/brew/issues/17422) and it is correct that this file is being flagged as "com.apple.quarantine" but I still get the same error when I clear this flag.

**Comment by Bo98** [comment]
Your security software is probably also flagging the contents after its been extracted too.

**Comment by mchakra8** [comment]
> ![Screenshot 2024-06-12 at 10 56 33 AM](https://private-user-images.githubusercontent.com/21034589/338787761-add40ea5-56a6-40a6-a83a-f3646a75f312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzY3NTAsIm5iZiI6MTcxODczNjQ1MCwicGF0aCI6Ii8yMTAzNDU4OS8zMzg3ODc3NjEtYWRkNDBlYTUtNTZhNi00MGE2LWE4M2EtZjM2NDZhNzVmMzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE4NDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMWQ4ZmE1M2U3ZGU3ZDljNDE4ZmNiZTlmODc0ZjhiNTQxNDI3Zjg0ODUxYjdmYjI5ZTUxYTcwYzgxZWY1NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ciMrMeSVPd3AuJybupzC5LoMYL0Qm-Lx5YR9koc4Ick) This is the output that these commands will generate.

Although this issue has been marked as closed, I wanted to report that I experience the exact same error as msherafatian above for portable-ruby-3.3.3.el_capitan.bottle.tar.gz, running the latest Homebrew 4.3.6-26-g907f54a. Clearing xattr permissions on the tar.gz file does not fix the problem, nor does manually downloading the file and extracting it with recursive xattr permissions.

`==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:a5ef040e054444a0eb2cbcc1032fed14702dfbe2e55b25e609f3ce643f23c4ee
Already downloaded: /Users/[username]/Library/Caches/Homebrew/portable-ruby-3.3.3.el_capitan.bottle.tar.gz
==> Pouring portable-ruby-3.3.3.el_capitan.bottle.tar.gz
/usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: line 231: 59690 Killed: 9               "./${VENDOR_VERSION}/bin/${VENDOR_NAME}" --version > /dev/null
Error: Failed to install ruby 3.3.3!
Error: Failed to upgrade Homebrew Portable Ruby!`

**Comment by gromgit** [comment]
Are you running any security/management software on your system (anti-virus, internet security suite, etc.)? If that software, as it seem:
* is running,
* doesn't like what it sees Homebrew doing, and
* kills Homebrew with extreme prejudice

there's nothing that can be done about it except disabling that software while running `brew`.
