### ISSUE TITLE
Add color to the instructions after install.

### ISSUE THREAD

**Issue by tolluset** [Homebrew/brew#17490]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

The current instructions are look like this. It's hard to recognize post instructions, because it's color is same as aboves.

 
![스크린샷 2024-06-13 17 44 38](https://github.com/Homebrew/brew/assets/50096419/67e1ceda-8728-42cd-a848-cf87e8b0c5d7)

If instruction has color, it's easy to recognize.

![스크린샷 2024-06-13 17 57 34](https://github.com/Homebrew/brew/assets/50096419/8ce58e2f-98d4-487e-bcd9-b0a79e775a15)

### What is the motivation for the feature?

Sometime miss the instructions. So maybe it has color it will be more recognizable.

### How will the feature be relevant to at least 90% of Homebrew users?

Most of user see the colored text, so it can be helpful.

### What alternatives to the feature have been considered?

Automatically setup instructions. But homebrew consider many environments, so it is hard to make it. (probably)

**Comment by MikeMcQuaid** [comment]
> so it is hard to make it. (probably)

This would be relatively easy for autogenerated instructions but much harder for updating all those inside formulae themselves.

I'm also unsure whether colour is the best fit here compared to e.g. bold/underline/whitespace changes.

@Homebrew/maintainers thoughts on this?

**Comment by SMillerDev** [comment]
Personally I think that the instructions are the important part, not the commands themselves like they are emphasised here. I do think that colouring the output can be useful.

**Comment by tolluset** [comment]
Thanks for the share context. I was thinking of adding colors, but the comments make me think there are other ways to do it. 

1. Add bold

  Maybe cause problem ANSI color codes.

2. Add emoji

Given that I mostly see colors, bolds, and emoji characters in the output, I'm guessing that if we can't use colors and bolds (the ANSI color codes), we can use emoji, but I'm not sure how much it will catch people's eyes.

e.g.

🚧 If you need to have ... first in your PATH, run:

**Comment by lekhok** [comment]
Something like colouring would be nice, we are pretty much used to reading bland lines of code and personally I don't mind it, but considering accessibility, it's always nice to have a cherry on the cake.

Coloring according to WCAG standards would be definitely be a welcomed step.

**Comment by razvanazamfirei** [comment]
> Given that I mostly see colors, bolds, and emoji characters in the output, I'm guessing that if we can't use colors and bolds (the ANSI color codes), we can use emoji, but I'm not sure how much it will catch people's eyes.

Colors and bolding are fine. I don't feel strongly about it as long as we have clear guidelines. Even better if we could move the formatting logic outside of the cask/formula, as ANSI escape codes are difficult to read and would make our jobs more difficult. 

However, I am strongly against the usage of emojis in any stanzas, unless we make them respect `HOMEBREW_NO_EMOJI`.

**Comment by MikeMcQuaid** [comment]
We seem to have no real agreement of what/how this should be done so: passing on this, sorry.

Will review PRs from anyone but a note of warning that they may not be merged and will require further discussion.
