### ISSUE TITLE
redis-stack-server installation failed with redis-stack/redis-stack/redis-stack-server: undefined method `exists?' for class File

### ISSUE THREAD

**Issue by wschaefer42** [Homebrew/brew#17519]
### `brew doctor` output

```shell
^[[1mPlease note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!^[[0m

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  ^[[4mhttps://developer.apple.com/download/all/^[[24m.
You should download the Command Line Tools for Xcode 15.4.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  consul
  couchdb
  spidermonkey@91
  terraform

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-versions
Untap them with `brew untap`.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.
- [X] I ran `brew update` twice and am still able to reproduce my issue.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3f08c75e7b950d4340dab462f3e7f77e8093fa2b
Last commit: 5 days ago
Core tap JSON: 16 Jun 06:34 UTC
Core cask tap JSON: 16 Jun 06:34 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.2 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.0.1.0.2.5
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

brew uninstall redis-stack-server --force

### What happened (include all command output)?

brew uninstall redis-stack-server --force
==> Uninstalling Cask redis-stack-server
Error: undefined method `exists?' for class File
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240405093707.798/Casks/redis-stack-server.rb:34:in `block (3 levels) in load'
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240405093707.798/Casks/redis-stack-server.rb:32:in `each'
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240405093707.798/Casks/redis-stack-server.rb:32:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:30:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:474:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:471:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:409:in `uninstall'
/opt/homebrew/Library/Homebrew/cask/uninstall.rb:14:in `block in uninstall_casks'
/opt/homebrew/Library/Homebrew/cask/uninstall.rb:9:in `each'
/opt/homebrew/Library/Homebrew/cask/uninstall.rb:9:in `uninstall_casks'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:73:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting

### What did you expect to happen?

uninstall the redis-stack-server to install the newer version
==> Upgrading 1 outdated package:
redis-stack/redis-stack/redis-stack-server 7.2.0-v10 -> 7.2.0-v11

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade redis-stack-server
==> Upgrading 1 outdated package:
redis-stack/redis-stack/redis-stack-server 7.2.0-v10 -> 7.2.0-v11
==> Upgrading redis-stack-server
==> Downloading https://redismodules.s3.amazonaws.com/redis-stack/redis-stack-server-7.2.0-v11.monterey.arm64.zip
Already downloaded: /Users/wernerschafer/Library/Caches/Homebrew/downloads/cbe9e09e832e343aeee6b5a2d88aa8d93b07a72d575bf828512b600c8664621a--redis-stack-server-7.2.0-v11.monterey.arm64.zip
Warning: Cannot verify integrity of 'cbe9e09e832e343aeee6b5a2d88aa8d93b07a72d575bf828512b600c8664621a--redis-stack-server-7.2.0-v11.monterey.arm64.zip'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "3a219a11af1eb96dac3684512abb1e23c588ff9a2dbe0ba4817a7f1e3f88dda2"
All dependencies satisfied.
==> Purging files for version 7.2.0-v11 of Cask redis-stack-server
Error: redis-stack/redis-stack/redis-stack-server: undefined method `exists?' for class File
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240405093707.798/Casks/redis-stack-server.rb:34:in `block (3 levels) in load'
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240405093707.798/Casks/redis-stack-server.rb:32:in `each'
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240405093707.798/Casks/redis-stack-server.rb:32:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:30:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:474:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:471:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:430:in `start_upgrade'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:195:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:260:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:138:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

**Comment by MikeMcQuaid** [comment]
> * [x]  This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at [Homebrew/homebrew-core/issues/new/choose](https://github.com/Homebrew/homebrew-core/issues/new/choose) instead.

It does. Please report this to redis-stack/redis-stack instead.
