### ISSUE TITLE
Warn when URL download is an HTML page instead of archive

### ISSUE THREAD

**Issue by abitrolly** [Homebrew/brew#17558]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  testscript

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  testscript

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core && git stash -u && git clean -d -f

Uncommitted files:
  ?? Formula/t/testscript.rb
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.2-64-g3566d1e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3566d1e78c2df1548639b0480923b5b69818dbf6
Last commit: 3 weeks ago
Core tap HEAD: 6a7b67d2aaac714109e9766227812de8adcffc96
Core tap last commit: 13 minutes ago
Core tap JSON: 25 Jun 07:32 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.2 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/bin/ruby
CPU: quad-core 64-bit haswell
Clang: N/A
Git: 2.45.2 => /bin/git
Curl: 8.6.0 => /bin/curl
Kernel: Linux 6.9.4-200.fc40.x86_64 x86_64 GNU/Linux
OS: Fedora release 40 (Forty)
Host glibc: 2.39
/usr/bin/gcc: 14.1.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: 14.1.0_1
xorg: N/A
```

### What were you trying to do (and why)?

Build new formula.

```ruby
class Testscript < Formula
  desc "Integration tests for command-line applications in .txtar format"
  homepage "https://github.com/rogpeppe/go-internal/tree/master/cmd/testscript"
  url "https://github.com/rogpeppe/go-internal"
  version "1.12.0"
  sha256 "9715effe29a3d7fa4e01f683c9114ae4b74897788b702cbbac5ce55e805991d1"
  license "BSD-3-Clause"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "./cmd/testscript"
  end

  test do
    system "ls", "-la"
    system "#{bin}/testscript"
  end
end
```

### What happened (include all command output)?

```sh
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --verbose --debug testscript
...
cp -p /home/anatoli/.cache/Homebrew/downloads/60dcc0061f5f541534df9d246a6cda820db0f1bdfd0ba1cacd8b25a104043d9e--go-internal /tmp/testscript-20240625-134721-fch9q6/go-internal
==> go build -trimpath -o=/home/linuxbrew/.linuxbrew/Cellar/testscript/1.12.0/bin/testscript -ldflags=-s -w ./cmd/testscript
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
...
BuildError: Failed executing: go build -trimpath -o=/home/linuxbrew/.linuxbrew/Cellar/testscript/1.12.0/bin/testscript -ldflags=-s\ -w ./cmd/testscript
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.
[anatoli@blackred]/tmp/testscript-20240625-134721-fch9q6% ls -la 
total 312
drwx------.  3 anatoli anatoli     80 Jun 25 07:34 .
drwxrwxrwt. 30 root    root       700 Jun 25 07:34 ..
drwxr-xr-x.  3 anatoli anatoli    120 Jun 25 07:34 .brew_home
-rw-r--r--.  1 anatoli anatoli 319329 Jun 25 07:10 go-internal
[anatoli@blackred]/tmp/testscript-20240625-134721-fch9q6%
```

### What did you expect to happen?

`brew audit` and other tools warn that downloaded URL is an HTML page, and should be an archive.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew create --go https://github.com/rogpeppe/go-internal/tree/master/cmd/testscript --set-version v1.12.0`
2. Change contents to the pasted file
3. `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --verbose --debug testscript`
```

**Comment by MikeMcQuaid** [comment]
> `brew audit` and other tools warn that downloaded URL is an HTML page, and should be an archive.

How would Homebrew know what a URL "should" be? Not every `url` is an archive.

**Comment by abitrolly** [comment]
@MikeMcQuaid Homebrew assumes that `url` is either repo or archive, right? So if the URL is archive, it should not be HTML file that starts with  `<!DOCTYPE ` or `<html`.

**Comment by MikeMcQuaid** [comment]
@abitrolly It makes no assumptions, URLs are used for all sorts of things including individual files.

**Comment by abitrolly** [comment]
@MikeMcQuaid but the `def install` unpacks URL and cd's into unpacked copy fir running build commands, no? Or do you want to say that if the unpack fails, change dir does not happen, and the build directory is not the package source, but just temp dir.

**Comment by MikeMcQuaid** [comment]
> but the `def install` unpacks URL and cd's into unpacked copy to run build commands, no?

Not always, no, see `using: :nounzip` in homebrew/core.

It could make sense for this to be flagged when there's an HTML response without this specified? What do you think @Homebrew/maintainers?

**Comment by Bo98** [comment]
> Not always, no, see `using: :nounzip` in homebrew/core.
> 
> 
> 
> It could make sense for this to be flagged when there's an HTML response without this specified?

Nounzip is implicit if it's not an archive. Many third party taps download and install binaries without needing to specify `using: nounzip`

If we want to have a warning somewhere, making it happen in `brew create` when one of the templates are explicitly chosen may make sense.

For other end users, the checksum already covers this really.

**Comment by MikeMcQuaid** [comment]
> Nounzip is implicit if it's not an archive.

TIL.

In that case: definitely passing on this, sorry.

**Comment by abitrolly** [comment]
> If we want to have a warning somewhere, making it happen in brew create when one of the templates are explicitly chosen may make sense. 

Yep. That would be ideal. Although the original URL in `brew create` is still a non-standard case.

```sh
brew create --go https://github.com/rogpeppe/go-internal/tree/master/cmd/testscript --set-version v1.12.0`
```

Next time maybe I will take another look into `brew create` process.
