### ISSUE TITLE
RUSTFLAGS behavior should match CFLAGS when building from source

### ISSUE THREAD

**Issue by git-mann** [Homebrew/brew#17566]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When building a formula from source the `-march=$HOMEBREW_ARCH` flag is added to the appropriate C/C++ compiler flags, but for Rust based formula, the `--codegen target-cpu={}` value for RUSTFLAGS is always set with `oldest_cpu` rather than `$HOMEBREW_ARCH` like the C flags. Ideally the Rust flags follow the same behavior as the C flags.

### What is the motivation for the feature?

The motivation is two fold:
1. It makes the architecture selection consistent across languages for formula built from source.
2. It can drastically improve the performance of Rust applications for most users.

### How will the feature be relevant to at least 90% of Homebrew users?

Really the same as the above motivation, consistency across programming languages. I don't know about other Homebrew users, but I install most formula from source.

### What alternatives to the feature have been considered?

I've tried some various things to override RUSTFLAGS when installing but none of them worked.
* `HOMEBREW_RUSTFLAGS` and `RUSTFLAGS` get overwritten by the superenv as expected.
* Manually interactively editing `RUSTFLAGS` for each install is a non-solution since it doesn't work for automatic updates.

Edit: grammer

**Comment by Bo98** [comment]
Looks like it's simply a case of making it use `ENV.effective_arch` rather than `Hardware.oldest_cpu`, but it might require some small refactoring to archive this as `ENV.effective_arch` shouldn't be called in `hardware.rb` (but could be passed in as a parameter).

Given the function checks `:native`, it was likely always intended to use `ENV.effective_arch` but was either never implemented or is a unintended bug.

**Comment by MikeMcQuaid** [comment]
We'll review a PR for this.
