### ISSUE TITLE
`brew typecheck` fails on arm64 w/o rosetta installed

### ISSUE THREAD

**Issue by rrotter** [Homebrew/brew#17593]
### `brew doctor` output

```shell
~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
~ % brew config
HOMEBREW_VERSION: 4.3.7-38-gfda555d
ORIGIN: https://github.com/Homebrew/brew
HEAD: fda555d7e61d13a142f1505dc58591add3c09d29
Last commit: 8 hours ago
Core tap HEAD: ba10d296e42e15c613daf87b63780b4ecbd4bb60
Core tap last commit: 2 hours ago
Core tap JSON: 29 Jun 22:49 UTC
Core cask tap HEAD: ba2aadd1951bef373d09fc7900df49fde2b8b045
Core cask tap last commit: 49 minutes ago
Core cask tap JSON: 29 Jun 22:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BUNDLE_USER_CACHE: /Users/rrotter/.cache/bundle
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 1
HOMEBREW_EDITOR: mate
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

Run `brew typecheck`, because the PR template asks me to.

### What happened (include all command output)?

```
~ % brew typecheck
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-0.5.11450/bin/srb: line 109: /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-static-0.5.11450-universal-darwin/libexec/sorbet: Bad CPU type in executable
Check https://docs.brew.sh/Typechecking for more information on how to resolve these errors.
```

### What did you expect to happen?

`brew typecheck` would work w/o rosetta, or there would be an error printed that indicated why it failed, or https://docs.brew.sh/Typechecking would contain a caveat about this.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
~ % uname -mrs
Darwin 23.5.0 arm64
~ % brew typecheck
```

**Comment by Bo98** [comment]
Sorbet does not yet support Apple Silicon unfortunately. As soon as it does we will update it to make use of it.

We could perhaps make the error clearer but other than that there's not anything we can do.

**Comment by rrotter** [comment]
I think this is an upstream bug (https://github.com/sorbet/sorbet/issues/6778), that the sorbet gem lacks arm64 support. That being said, posting here because:
1. wanted to raise attention, I assume most devs have rosetta installed and would never notice this
2. if this isn't getting fixed, brew should produce a better error message
