### ISSUE TITLE
Non-recursive git submodule update

### ISSUE THREAD

**Issue by jystic** [Homebrew/brew#1762]
I'd like to write some formulas for projects which already have their transitive dependencies specified as direct git submodules. A [recursive submodule update](https://github.com/Homebrew/brew/blob/45ef7ea0b0ac8665d3eeae8acf0e17ef646be0b3/Library/Homebrew/download_strategy.rb#L760-L764) causes many copies of unnecessary duplicate dependencies to be pulled in for these kind of projects.

I'd be happy to put up a PR with an option for switching off the default recursive behaviour, but I'm not very familiar with homebrew and was unsure of an idiomatic way to expose this feature, so i thought it would be best to post here for guidance.

If anyone with more experience would prefer to implement this I'd be all for it.

**Comment by MikeMcQuaid** [comment]
> A recursive submodule update causes many copies of unnecessary duplicate dependencies to be pulled in for these kind of projects.

Can you elaborate a bit more on this, I'm not sure I understand the issue.

**Comment by jystic** [comment]
Say I have a project with two submodules:
```
lib/foo
lib/bar
```
And `lib/bar` also has the submodule `lib/foo`, when I do a submodule update with `--recursive` I end up with a directory structure like this:
```
.
└─ lib
   ├─ foo
   └─ bar
      └─ lib
         └─ foo
 ```
`lib/foo` shows up twice in the sub-directories.

Ideally I could configure homebrew to update without `--recursive` so that I would get this:
```
.
└─ lib
   ├─ foo
   └─ bar
 ```

It's perhaps not a big deal with only a small number of dependencies as we could modify the build to ignore nested `lib` directories, but as the number of submodules grow this causes a bit of an explosion.

**Comment by MikeMcQuaid** [comment]
I see. Given this case just causes a bit more to be downloaded than is necessary and isn't going to be the case for bottled formulae I think we'll pass on the feature request for now until we get more requests. Thanks for the clear explanation, though!

**Comment by demonixis** [comment]
Hi,

Sorry to comment here, feel free to move my comment in the correct place. I want to create a formula for osvr-RenderManager which have few submodule with NDA. Those modules are pulled with a recursive clone only. That's the same request but not the same problem. Do you think we can do something to prevent this behaviour?

Thanks.

**Comment by MikeMcQuaid** [comment]
@demonixis We cannot move comments. Recursive clones are the default.
