### ISSUE TITLE
Include `brew` in error messages

### ISSUE THREAD

**Issue by jsoref** [Homebrew/brew#17627]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Currently, when brew is run with something it doesn't like, it doesn't include `brew` in the error message:
```sh
% brew --foo
Error: Unknown command: --foo
% brew foo
Error: Unknown command: foo
```

Instead, the error could be prefixed with `brew: `

```sh
% brew --foo
brew: Error: Unknown command: --foo
% brew foo
brew: Error: Unknown command: foo
```

### What is the motivation for the feature?

Friendly programs say hello when run (this is helpful when they're run from other programs which don't report which programs they're running and the arguments they're running)
```
% curl --foo
curl: option --foo: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

### How will the feature be relevant to at least 90% of Homebrew users?

people who run scripts that use brew that have errors will be more easily able to identify that the scripts were incorrectly running `brew` instead of not knowing which program the running script was misusing.

### What alternatives to the feature have been considered?

Suffering from generic error messages

**Comment by MikeMcQuaid** [comment]
> ```shell
> brew: Error: Unknown command: --foo
> ```

I don't think this is better.

I do think `Error: Unknown Homebrew command: --foo` would be better.

**Comment by jsoref** [comment]
I'd take that.
