### ISSUE TITLE
vendor-install.sh: line 232: 96040 Killed: 9 

### ISSUE THREAD

**Issue by sergiolch** [Homebrew/brew#17637]
### `brew doctor` output

```shell
$ brew doctor
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:49847c7a13f7094b211f6d0025900dd23716be07dac894a3d6941d7696296306
Already downloaded: /Users/sergio/Library/Caches/Homebrew/portable-ruby-3.3.3.arm64_big_sur.bottle.tar.gz
==> Pouring portable-ruby-3.3.3.arm64_big_sur.bottle.tar.gz
/opt/homebrew/Library/Homebrew/cmd/vendor-install.sh: line 232: 98644 Killed: 9               "./${VENDOR_VERSION}/bin/${VENDOR_NAME}" --version > /dev/null
Error: Failed to install ruby 3.3.3!
Error: Failed to upgrade Homebrew Portable Ruby!
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:49847c7a13f7094b211f6d0025900dd23716be07dac894a3d6941d7696296306
Already downloaded: /Users/sergio/Library/Caches/Homebrew/portable-ruby-3.3.3.arm64_big_sur.bottle.tar.gz
==> Pouring portable-ruby-3.3.3.arm64_big_sur.bottle.tar.gz
/opt/homebrew/Library/Homebrew/cmd/vendor-install.sh: line 232: 99026 Killed: 9               "./${VENDOR_VERSION}/bin/${VENDOR_NAME}" --version > /dev/null
Error: Failed to install ruby 3.3.3!
Error: Failed to upgrade Homebrew Portable Ruby!
```

### What were you trying to do (and why)?

I was trying to update brew so I can use latest version of git with `brew update` `brew upgrade`, I don't use ruby at all and never will 

### What happened (include all command output)?

```
$ brew update
==> Updating Homebrew...
Already up-to-date.
$ brew upgrade 
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:49847c7a13f7094b211f6d0025900dd23716be07dac894a3d6941d7696296306
Already downloaded: /Users/sergio/Library/Caches/Homebrew/portable-ruby-3.3.3.arm64_big_sur.bottle.tar.gz
==> Pouring portable-ruby-3.3.3.arm64_big_sur.bottle.tar.gz
/opt/homebrew/Library/Homebrew/cmd/vendor-install.sh: line 232: 99631 Killed: 9               "./${VENDOR_VERSION}/bin/${VENDOR_NAME}" --version > /dev/null
Error: Failed to install ruby 3.3.3!
Error: Failed to upgrade Homebrew Portable Ruby!
```

### What did you expect to happen?

Already up-to-date.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
```

**Comment by apainintheneck** [comment]
A little background on why it's trying to download Ruby when you were trying to upgrade a package. Homebrew is written mostly in Ruby with a little bit of Bash glue code as well. We used to use system Ruby on macOS but it's old and no longer receives security updates. We now ship our own version of [portable ruby](https://github.com/Homebrew/homebrew-portable-ruby) that Homebrew runs on locally. This is what is not upgrading correctly on your machine.

**Comment by MikeMcQuaid** [comment]
If this is killed: it's happening through some security software on your machine I'm afraid we have no control over or ability to fix.
