### ISSUE TITLE
Feature Request: display a check mark to the installed packages when searching

### ISSUE THREAD

**Issue by Clumsy-Coder** [Homebrew/brew#1764]
### Propose a feature:

Displaying a check mark to the packages installed when searching for a package (including brew cask). 
Ex: you installed google chrome and you type 'brew search google' and a list of packages are listed (like usual), but the installed packages have a check mark next to it. In this case google chrome package will have a checkmark indicating the package is installed and the user doesn't need to type 'brew cask info google-chrome' to check if the package is installed or not (if the user wants to check later on).

**Comment by MikeMcQuaid** [comment]
This seems like a good idea.

**Comment by vitorgalvao** [comment]
This has been implemented.
