### ISSUE TITLE
Feature request: Include `disable!` `date` in deprecation warning logs

### ISSUE THREAD

**Issue by neil176** [Homebrew/brew#17653]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

When logging deprecation warnings, it would be helpful for formulae that have `disable!` with a `date` set to include that date in the warning log. Something like `Warning: python-packaging has been deprecated! It will be disabled after 2024-07-05` would be very helpful.

### What is the motivation for the feature?

My organization maintains a private tap with some internal formulae that depend on various `homebrew-core` python formulae that are currently progressing through `homebrew-core`'s deprecate -> disable timeline. It would be helpful to know when those formulae will transition from deprecated to disabled when I look through various logs and see something like `Warning: python-packaging has been deprecated!` so that I can make sure my team stays on top of keeping our formulae up to date.

### How will the feature be relevant to at least 90% of Homebrew users?

People will be less caught off guard when something transitions from deprecated to disabled.

### What alternatives to the feature have been considered?

I can't think of any alternatives at the moment, but this seems like a reasonable way to communicate the deprecation timelines that formulae progress through.

**Comment by neil176** [comment]
@MikeMcQuaid  Thanks so much for this one! Will be a big help for me and my team

**Comment by MikeMcQuaid** [comment]
@neil176 You're welcome, it was a good idea that was well articulated! If you have similar issues around this sort of thing: let us know!
