### ISSUE TITLE
renamed formulas results in dupes

### ISSUE THREAD

**Issue by FernandoMiguel** [Homebrew/brew#17669]
### `brew doctor` output

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  vault

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-versions
Untap them with `brew untap`.
```
```


### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 4.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c98a33a376e5b35ebc801d0f7d6ba7b9eb118ac
Last commit: 2 days ago
Core tap JSON: 10 Jul 11:40 UTC
Core cask tap JSON: 10 Jul 11:40 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```
```


### What were you trying to do (and why)?

$ brew cu --all --verbose
$ brew cu --verbose --cleanup
update all packages and casks and remove old versions

### What happened (include all command output)?

```
Already up-to-date.
Warning: Cask homebrew/cask-versions/discord-ptb was renamed to discord@ptb.
Warning: Cask homebrew/cask-versions/firefox-beta was renamed to firefox@beta.
Warning: Cask homebrew/cask-versions/firefox-developer-edition was renamed to firefox@developer-edition.
Warning: Cask microsoft/git/git-credential-manager-core was renamed to git-credential-manager.
Warning: Cask homebrew/cask-versions/google-chrome-canary was renamed to google-chrome@canary.
Warning: Cask homebrew/cask-versions/google-chrome-dev was renamed to google-chrome@dev.
Warning: Cask homebrew/cask-versions/iterm2-beta was renamed to iterm2@beta.
Warning: Cask homebrew/cask-versions/slack-beta was renamed to slack@beta.
Warning: Cask homebrew/cask-versions/utm-beta was renamed to utm@beta.
Warning: Cask homebrew/cask-versions/visual-studio-code-insiders was renamed to visual-studio-code@insiders.
==> Finding outdated apps
       Cask                         Current                                                      Latest                                                       A/U    Result    URL
 1/42  android-platform-tools       35.0.1                                                       35.0.1                                                            [   OK   ]  https://developer.android.com/tools/releases/platform-tools
 2/42  aws-vault                    7.2.0                                                        7.2.0                                                             [   OK   ]  https://github.com/99designs/aws-vault
 3/42  caldigit-docking-utility     1.9.31                                                       1.9.31                                                            [   OK   ]  https://www.caldigit.com/
 4/42  daisydisk                    4.30                                                         4.30                                                          Y   [  PASS  ]  https://daisydiskapp.com/
 5/42  darktable                    4.8.0                                                        4.8.0                                                             [   OK   ]  https://www.darktable.org/
 6/42  dbeaver-community            24.1.2                                                       24.1.2                                                        Y   [  PASS  ]  https://dbeaver.io/
 7/42  diffmerge                    4.2.1.1013                                                   4.2.1.1013                                                        [   OK   ]  https://www.sourcegear.com/diffmerge/
 8/42  discord@ptb                  0.0.122                                                      0.0.122                                                       Y   [  PASS  ]  https://discord.com/
 9/42  discord@ptb                  0.0.122                                                      0.0.122                                                       Y   [  PASS  ]  https://discord.com/
10/42  finch                        1.2.2                                                        1.2.2                                                             [   OK   ]  https://github.com/runfinch/finch
11/42  firefox@beta                 latest                                                       latest                                                            [   OK   ]  https://www.mozilla.org/firefox/channel/desktop/#beta
12/42  firefox@beta                 latest                                                       latest                                                            [   OK   ]  https://www.mozilla.org/firefox/channel/desktop/#beta
13/42  firefox@developer-edition    129.0b1                                                      129.0b1                                                       Y   [  PASS  ]  https://www.mozilla.org/firefox/developer/
14/42  firefox@developer-edition    129.0b1                                                      129.0b1                                                       Y   [  PASS  ]  https://www.mozilla.org/firefox/developer/
15/42  git-credential-manager       2.5.0                                                        2.5.0                                                             [   OK   ]  https://aka.ms/gcm
16/42  git-credential-manager                                                                    2.5.0                                                             [OUTDATED]  https://aka.ms/gcm
17/42  google-chrome@canary                                                                      latest                                                            [   OK   ]  https://www.google.com/chrome/canary/
18/42  google-chrome@canary         latest                                                       latest                                                            [   OK   ]  https://www.google.com/chrome/canary/
19/42  google-chrome@dev            128.0.6559.0                                                 128.0.6559.0                                                  Y   [  PASS  ]  https://www.google.com/chrome/dev/
20/42  google-chrome@dev                                                                         128.0.6559.0                                                  Y   [  PASS  ]  https://www.google.com/chrome/dev/
21/42  iterm2@beta                  3.5.4beta1                                                   3.5.4beta1                                                    Y   [  PASS  ]  https://iterm2.com/
22/42  iterm2@beta                                                                               3.5.4beta1                                                    Y   [  PASS  ]  https://iterm2.com/
23/42  kdiff3                       1.11.2                                                       1.11.2                                                            [   OK   ]  https://invent.kde.org/sdk/kdiff3
24/42  knockknock                   2.5.0                                                        2.5.0                                                             [   OK   ]  https://objective-see.com/products/knockknock.html
25/42  logitech-camera-settings     3.0.23                                                       3.0.23                                                            [   OK   ]  https://support.logi.com/hc/en-us/articles/360049055854
26/42  maccy                        1.0.0                                                        1.0.0                                                         Y   [  PASS  ]  https://maccy.app/
27/42  microsoft-auto-update        4.72.24060916                                                4.72.24060916                                                 Y   [  PASS  ]  https://docs.microsoft.com/officeupdates/release-history-microsoft-autoupdate
28/42  microsoft-teams              24152.405.2925.6762                                          24152.405.2925.6762                                           Y   [  PASS  ]  https://www.microsoft.com/en/microsoft-teams/group-chat-software/
29/42  safari-technology-preview    198,062-20835-20240703-E4CA0D96-97C7-4ABC-9664-DA019810C41F  198,062-20835-20240703-E4CA0D96-97C7-4ABC-9664-DA019810C41F   Y   [  PASS  ]  https://developer.apple.com/safari/resources/
30/42  sequel-ace                   4.0.17,20067                                                 4.0.17,20067                                                      [   OK   ]  https://github.com/Sequel-Ace/Sequel-Ace
31/42  session-manager-plugin       1.2.650.0                                                    1.2.650.0                                                         [   OK   ]  https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html
32/42  silentknight                 2.9,2024.06                                                  2.9,2024.06                                                       [   OK   ]  https://eclecticlight.co/lockrattler-systhist/
33/42  slack@beta                                                                                4.39.90                                                       Y   [  PASS  ]  https://slack.com/beta/osx
34/42  slack@beta                   4.39.90                                                      4.39.90                                                       Y   [  PASS  ]  https://slack.com/beta/osx
35/42  sourcetree                   4.2.8,265                                                    4.2.8,265                                                     Y   [  PASS  ]  https://www.sourcetreeapp.com/
36/42  steam                        4.0                                                          4.0                                                           Y   [  PASS  ]  https://store.steampowered.com/about/
37/42  telegram                     10.15.2,265540                                               10.15.2,265540                                                Y   [  PASS  ]  https://macos.telegram.org/
38/42  utm@beta                     4.5.3                                                        4.5.3                                                             [   OK   ]  https://mac.getutm.app/
39/42  utm@beta                                                                                  4.5.3                                                             [OUTDATED]  https://mac.getutm.app/
40/42  visual-studio-code@insiders                                                               latest                                                            [   OK   ]  https://code.visualstudio.com/insiders
41/42  visual-studio-code@insiders  latest                                                       latest                                                            [   OK   ]  https://code.visualstudio.com/insiders
42/42  vlc                          3.0.21                                                       3.0.21                                                        Y   [  PASS  ]  https://www.videolan.org/vlc/
==> Found outdated apps
     Cask                    Current  Latest  A/U    Result    URL
1/2  git-credential-manager           2.5.0        [OUTDATED]  https://aka.ms/gcm
2/2  utm@beta                         4.5.3        [OUTDATED]  https://mac.getutm.app/
```

### What did you expect to happen?

that when the migration happened no dupes existed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew cu --all --verbose
$ brew cu --verbose --cleanup
```

**Comment by MikeMcQuaid** [comment]
> $ brew cu --all --verbose

This is not a Homebrew command.

> ==> Finding outdated apps
> Cask Current Latest A/U Result URL

This is not Homebrew output.

**Comment by yurikoles** [comment]
https://github.com/buo/homebrew-cask-upgrade/issues
