### ISSUE TITLE
Publish ubuntu 24.04 docker image to hub.docker.com (CD flow exist already)

### ISSUE THREAD

**Issue by andreineculau** [Homebrew/brew#17661]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

We currently don't have a hub.docker.com repository for homebrew/ubuntu24.04 https://hub.docker.com/u/homebrew

despite building for 24.04 (see [workflow](https://github.com/Homebrew/brew/actions/runs/9835311653/workflow) and example [run](https://github.com/Homebrew/brew/actions/runs/9835311653) )

Just create the hub.docker.com repository

### What is the motivation for the feature?

* green Github Actions runs
* enable users to download a homebrew image based on Ubuntu 24.04

### How will the feature be relevant to at least 90% of Homebrew users?

Ubuntu 24.04 was released ~3 months ago and users will want to test linuxbrew in a 24.04 environment .

### What alternatives to the feature have been considered?

Users can build their own docker image based on 24.04 but without a central repository, results will vary from one client to another.

**Comment by MikeMcQuaid** [comment]
Yup, makes sense. Can you submit a PR for this? Should be a straightforward addition to `docker.yml`. [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by andreineculau** [comment]
@MikeMcQuaid my interpretation is that there's nothing to do in code, as [we already have 24.04 in docker.yml](https://github.com/Homebrew/brew/blob/master/.github/workflows/docker.yml#L25), but whoever is admin over https://hub.docker.com/u/homebrew needs to create the repository for homebrew/ubuntu24.04 to fix [the "access to the resource is denied" error](https://github.com/Homebrew/brew/actions/runs/9835311653/job/27148694529#step:7:24) (because the resource doesn't exist)

Rerunning an old job or publishing the next brew version should automatically succeed in publishing the docker image for ubuntu 24.04

**Comment by Bo98** [comment]
Yeah, this is known and I've already raised this. It is available on ghcr.io in the meantime.

**Comment by andreineculau** [comment]
Oh interesting. Wasn't aware of these https://github.com/orgs/Homebrew/packages?repo_name=brew

Thank you

**Comment by andreineculau** [comment]
Updated title. Is ghcr.io preferred over hub.docker.com?

**Comment by MikeMcQuaid** [comment]
> Is ghcr.io preferred over hub.docker.com?

Yup 👍🏻

**Comment by andreineculau** [comment]
In that case, I'll close this ticket and update my references. Reopen if relevant

Thank you

**Comment by MikeMcQuaid** [comment]
Working on this still!

**Comment by MikeMcQuaid** [comment]
Reran. There is a 4.3.9 image there now: https://hub.docker.com/repository/docker/homebrew/ubuntu24.04/general

Should have fixed permissions such that this won't happen again.

Thanks for the clear report @andreineculau!
