### ISSUE TITLE
Add support for downloading formula and cask binaries in the background

### ISSUE THREAD

**Issue by metametapod** [Homebrew/brew#17701]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

It would be cool if there were a way to automatically download formula and cask upgrades in the background without installing. E.g. something like:

```
brew upgrade --download --cask transmit
```

Then when running `brew upgrade` later, it can prefer the cache if it's still up-to-date.

### What is the motivation for the feature?

Currently there is only support for `brew autoupdate start --upgrade`, but that installs the update which can cause incompatibilities.

### How will the feature be relevant to at least 90% of Homebrew users?

Adding an option to download would speed up Homebrew considerably especially for those on limited bandwidth connections, while still allowing one to vet updates before installing.

### What alternatives to the feature have been considered?

As far as I'm aware there is no alternative available, other than running `brew update` which does not download binaries, or `brew autoupdate start --upgrade` which both downloads and installs the update.

**Comment by MikeMcQuaid** [comment]
> Then when running `brew upgrade` later, it can prefer the cache if it's still up-to-date.

`brew fetch --cask transmit` should do this.

**Comment by carlocab** [comment]
If you want it to be done in the background:
```
brew fetch --cask transmit &
```

**Comment by metametapod** [comment]
Thank you, I didn't know about `brew fetch`. To prefetch all pending updates (both formulae and casks):

```sh
brew outdated | awk '{print $1}' | xargs brew fetch
```
