### ISSUE TITLE
How to check BREW install success?

### ISSUE THREAD

**Issue by wubingzhe** [Homebrew/brew#1778]
wubingzhedeMacBook-Pro:~ Beethoven$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /Library/Caches/Homebrew
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown Beethoven /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at fc11f63 Merge pull request #1677 from MikeMcQuaid/formula-prefix-opt
==> Cleaning up /Library/Caches/Homebrew...
==> Migrating /Library/Caches/Homebrew to /Users/Beethoven/Library/Caches/Homebr
==> Deleting /Library/Caches/Homebrew...
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://git.io/brew-analytics

==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://git.io/brew-docs
wubingzhedeMacBook-Pro:~ Beethoven$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
wubingzhedeMacBook-Pro:~ Beethoven$ zsh --version;
zsh 5.2 (x86_64-apple-darwin16.0)
wubingzhedeMacBook-Pro:~ Beethoven$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /Library/Caches/Homebrew
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown Beethoven /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at fc11f63 Merge pull request #1677 from MikeMcQuaid/formula-prefix-opt
==> Cleaning up /Library/Caches/Homebrew...
==> Migrating /Library/Caches/Homebrew to /Users/Beethoven/Library/Caches/Homebr
==> Deleting /Library/Caches/Homebrew...
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://git.io/brew-analytics

==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://git.io/brew-docs

Finally she told me Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://git.io/brew-docs
I don't know what's mean? am i install BREW Success and how to check?

**Comment by adidalal** [comment]
If `brew doctor` doesn't throw up any errors you have installed successfully.
As the message says, https://git.io/brew-docs has further help.

**Comment by MikeMcQuaid** [comment]
> ==> Installation successful!

**Comment by wubingzhe** [comment]
Thanks first flood, you are right
