### ISSUE TITLE
Documentaion: How-To-Open-a-Homebrew-Pull-Request.md - add cleanup instructions

### ISSUE THREAD

**Issue by muescha** [Homebrew/brew#17795]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Add a section on how to "clean up" the development stage.

Consider including a section like this:

````markdown
## Cleanup

To untap your current working directory, use the following command:

```sh
brew untap --force homebrew/cask
```
````

### What is the motivation for the feature?

The documentation on https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request command uses `brew tap --force homebrew/cask`. However, the documentation does not clearly explain how to revert to the previous setup before these changes were made.

### How will the feature be relevant to at least 90% of Homebrew users?

no

### What alternatives to the feature have been considered?

n/a

**Comment by MikeMcQuaid** [comment]
We already have messaging that will tell you to do this so I think adding to the docs is unnecessary. That said: will consider reviewing a PR for this.
