### ISSUE TITLE
Documentaion: How-To-Open-a-Homebrew-Pull-Request.md - missing info about `brew create`

### ISSUE THREAD

**Issue by muescha** [Homebrew/brew#17796]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

add code snippets for the usage of `brew create`	

add link to https://docs.brew.sh/Manpage#create-options-url

### What is the motivation for the feature?

As a newcomer to Homebrew following the instructions on this page, there's no indication that the commands `brew create` and `brew create --cask` exist.

### How will the feature be relevant to at least 90% of Homebrew users?

no - only formula / cask contributors

### What alternatives to the feature have been considered?

n/a

**Comment by MikeMcQuaid** [comment]
This is the standard format for a manpage. We can consider adding these to other docs.
