### ISSUE TITLE
brew link against non-existing formula causes uninitialized constant error

### ISSUE THREAD

**Issue by na-trium-144** [Homebrew/brew#17807]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.9-329-g61f5e2b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 61f5e2b6988aa40e93fe044eb56b1a79e9e7307e
Last commit: 2 hours ago
Core tap JSON: 18 Jul 18:26 UTC
Core cask tap JSON: 18 Jul 18:26 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.XYATgZu4A8/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

I mistyped `brew link python@3.10` as `brew link python3.10`.
But it seems this happens with any non-existing formula name.

### What happened (include all command output)?

similar to #8538. 
```
Error: uninitialized constant Homebrew::CLI::NamedArgs::MissingFormula
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/cli/named_args.rb:331:in `rescue in to_latest_kegs'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:328:in `to_latest_kegs'
/opt/homebrew/Library/Homebrew/cmd/link.rb:52:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

Output an error message that the formula does not exist or is not installed, or suggest similar formula like `brew install python3.10` do:
```
Warning: No available formula with the name "python3.10". Did you mean python@3.10, python@3.12, python@3.11, python-tk@3.10, python@3.9 or python@3.8?
==> Searching for similarly named formulae and casks...
==> Formulae
python@3.10 ✔                python@3.12 ✔                python@3.11 ✔                python-tk@3.10               python@3.9                   python@3.8

To install python@3.10 ✔, run:
  brew install python@3.10 ✔
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew link python3.10
```

**Comment by ah91086** [comment]
[This](https://github.com/Homebrew/brew/pull/17809) addresses the uninitialized constant error and replaces it with the original error `Error: No such keg: /opt/homebrew/Cellar/python3.10`

I can fast follow with something that resembles the `brew install python3.10` error message.

**Comment by apainintheneck** [comment]
Fixed by @ah91086 in https://github.com/Homebrew/brew/pull/17809
