### ISSUE TITLE
getpwuid function doesn't work with LDAP users on Linux

### ISSUE THREAD

**Issue by rgcosma** [Homebrew/brew#17810]
### `brew doctor` output

```shell
can't paste the whole lot, release is 4.3.9-338-g41e362f, installed just today
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
version as above, last commit 2 hours ago
```

### What were you trying to do (and why)?

brew install something

### What happened (include all command output)?

Error: can't find user for 1234567

### What did you expect to happen?

brew install just working

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
To fix this, I just edited in utils/github/api.rb lines 147 and 167 replacing 
`Etc.getpwuid(Process.uid)&.dir`
with
`ENV.fetch("HOME")`
```

**Comment by Bo98** [comment]
`getpwuid` does support LDAP if you've configured NSS correctly.

The use of `getpwuid` is intentional here but adding a fallback seems reasonable.
