### ISSUE TITLE
Homebrew installs Sierra bottles on Mavericks

### ISSUE THREAD

**Issue by jeroenooms** [Homebrew/brew#1781]
Our Mavericks build server recently started giving linking errors. We traced it down to the fact that homebrew is installing Sierra bottles on a mavericks machine when using `--force-bottle`. These builds obviously don't work well. Is this expected? Here is a simplified version of our build script:

```sh
BREWDIR="/tmp/homebrew"
mkdir -p $BREWDIR
curl -fsSL https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C $BREWDIR
HOMEBREW_CACHE="/tmp" $BREWDIR/bin/brew install zeromq --force-bottle
```

And there the output (on mavericks!)

```
Initialized empty Git repository in /private/tmp/homebrew/.git/
remote: Counting objects: 1050, done.
remote: Compressing objects: 100% (959/959), done.
Updating Homebrew...44% (462/1050), 156.00 KiB | 300.00 KiB/s
remote: Total 1050 (delta 99), reused 390 (delta 52), pack-reused 0
Receiving objects: 100% (1050/1050), 1.01 MiB | 469.00 KiB/s, done.
Resolving deltas: 100% (99/99), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
HEAD is now at 98dadd9 Merge pull request #1777 from alyssais/tests_tab_version
==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://git.io/brew-analytics

==> Tapping homebrew/core
Cloning into '/private/tmp/homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 3830, done.
remote: Compressing objects: 100% (3709/3709), done.
remote: Total 3830 (delta 25), reused 349 (delta 8), pack-reused 0
Receiving objects: 100% (3830/3830), 3.07 MiB | 1.19 MiB/s, done.
Resolving deltas: 100% (25/25), done.
Checking connectivity... done.
Tapped 3705 formulae (3,858 files, 9.6M)
==> Downloading https://homebrew.bintray.com/bottles/zeromq-4.2.0.sierra.bottle.
Already downloaded: /tmp/zeromq-4.2.0.sierra.bottle.tar.gz
==> Pouring zeromq-4.2.0.sierra.bottle.tar.gz
🍺  /private/tmp/homebrew/Cellar/zeromq/4.2.0: 22B
```

### Config

```
Jeroens-Mac:Desktop jeroen$ /tmp/homebrew/bin/brew config
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 98dadd907e31bb5f9a16bfb6aa2138b1852c4db5
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1a5176800d1799bb447d3816f2ffc3e53bd421b8
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /private/tmp/homebrew
HOMEBREW_REPOSITORY: /private/tmp/homebrew
HOMEBREW_CELLAR: /private/tmp/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p481
Clang: 6.0 build 600
Git: 1.9.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.9.5-x86_64
Xcode: N/A
CLT: 6.2.0.0.1.1424975374
X11: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
> Our Mavericks build server recently started giving linking errors. We traced it down to the fact that homebrew is installing Sierra bottles on a mavericks machine when using --force-bottle. These builds obviously don't work well. Is this expected?

This is expected behaviour. `--force-bottle` was an undocumented option so the behaviour has changed. May I ask why you were using it on a version of macOS we no longer bottle for?

**Comment by jeroenooms** [comment]
I think `--force-bottle` has been documented via `brew --help` for quite some time?

The `--force-bottle` is default in our scripts because we only need the static libraries, so relocation is not an issue. The previous homebrew behavior for `--force-bottle` was to prefer bottles if available, and otherwise build from source. Therefore we always included this option.

The change in behavior if unfortunate, I think brew should never serve incompatible binaries, even if the user asks for a bottle that might not be available anymore.

**Comment by MikeMcQuaid** [comment]
`brew install --force-bottle` was not documented.

> The --force-bottle is default in our scripts because we only need the static libraries, so relocation is not an issue.

I don't think that's a safe assumption to make. If a library hardcodes a path and then later uses it it will fail under your system.

> The previous homebrew behavior for --force-bottle was to prefer bottles if available, and otherwise build from source. Therefore it was harmless to always included this option.

Sure. It still behaves as you've described it but not in a way that's desirable to you so you'll need to omit the option, sorry.

> The change in behavior if unfortunate, I think brew should never serve incompatible binaries, even if the user asks for a bottle on a platform where this might not be available anymore.

`--force-$ANYTHING` is generally a good sign that you're doing something that may 💥, I'm afraid.
