### ISSUE TITLE
`brew cask install existing-app` uninstalls the app

### ISSUE THREAD

**Issue by jeremy** [Homebrew/brew#1785]
5785f54f4bd48dca58a7550af48217d4c6372ad2 (part of #1620) causes `brew cask install foo` to delete the Foo app if it's already installed.

(`Hbc::Artifact::Moved#preflight_checks` raises CaskError which gets rescued by `Hbc::Installer#install_artifacts`, triggering an uninstall of already-installed artifacts. The artifact wasn't actually installed yet, though! So it gets uninstalled because it already exists which caused the install to fail.)

To reproduce, for example: Install the GitHub Desktop app, then
```bash
$ brew cask install --verbose github-desktop
==> Downloading https://mac-installer.github.com/mac/GitHub%20Desktop%20222.zip
Already downloaded: /Users/jeremy/Library/Caches/Homebrew/Cask/github-desktop--222.zip
==> Verifying checksum for Cask github-desktop
Error: It seems there is already an App at '/Applications/GitHub Desktop.app'.
==> Removing App: '/Applications/GitHub Desktop.app'
Error: An error occured during installation of Cask github-desktop: It seems there is already an App at '/Applications/GitHub Desktop.app'.
Error: nothing to install
Error: Kernel.exit
```

**Comment by MikeMcQuaid** [comment]
CC @reitermarkus and @jawshooah because this seems pretty bad.

**Comment by vitorgalvao** [comment]
Also https://github.com/caskroom/homebrew-cask/issues/28789.

**Comment by monfresh** [comment]
@jeremy Thanks for opening this issue. I see that you've found the source of the bug, but I don't see a pull request. Were you planning on submitting one? If not, I was going to start working on it because I maintain a somewhat popular script that installs certain apps via Cask, and I'd hate for it to remove existing apps from people's machines.

I wanted to reach out first to make sure we're not duplicating efforts. Thanks!

**Comment by jeremy** [comment]
Please do, @monfresh. Thank you! I didn't look into the test suite at all.

Here's the patch I expected would fix the problem:
```diff
diff --git a/Library/Homebrew/cask/lib/hbc/installer.rb b/Library/Homebrew/cask/lib/hbc/installer.rb
index 3875e1c8f..465011735 100644
--- a/Library/Homebrew/cask/lib/hbc/installer.rb
+++ b/Library/Homebrew/cask/lib/hbc/installer.rb
@@ -141,8 +141,8 @@ module Hbc
 
       artifacts.each do |artifact|
         odebug "Installing artifact of class #{artifact}"
-        already_installed_artifacts.unshift(artifact)
         artifact.new(@cask, options).install_phase
+        already_installed_artifacts.unshift(artifact)
       end
     rescue StandardError => e
       begin
```
