### ISSUE TITLE
Could not update to 4.3.10

### ISSUE THREAD

**Issue by Whirlwind** [Homebrew/brew#17853]
### `brew doctor` output

```shell
Your system is ready.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
No important
```

### What were you trying to do (and why)?

The latest tag is v4.3.10 (https://github.com/Homebrew/brew/tags), But I could not update to the tag.

### What happened (include all command output)?

```
> brew update
Already up-to-date.

> brew --version
Homebrew 4.3.9-397-g5edcaf3
```

### What did you expect to happen?

brew update to the latest version (same to the latest tag)

### Step-by-step reproduction instructions (by running `brew` commands)

 > 4.1.9 intentionally tagged off the master branch, so this behaviour is expected yes. It seems you're on the developer path of updates (follows `master` branch) rather than updating from tag to tag, so `4.1.8-21-gce21e47` and later would had the change included in 4.1.9.
>
> It's rare this happens, and it's aligned again now though with 4.1.10.
>
> _Originally posted by @Bo98 in https://github.com/Homebrew/brew/issues/15978#issuecomment-1710117355_
            
I check my brew(`/opt/hombrew`), it is in the master branch. But I never change the git reference to the master. And I try to do:

```shell
❯ cd /opt/homebrew

❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

❯ git checkout 4.3.9
Note: switching to '4.3.9'.

❯ brew update
==> Updating Homebrew...
Already up-to-date.
```

It not works.

Then I try to reinstall the homebrew, it force changes the branch to master.

I check the branch in other macbooks, everyone said the branch is master.

**Comment by bevanjkay** [comment]
Please complete the issue template include the `brew config` output, or the issue will be closed.

**Comment by Bo98** [comment]
Similar to 4.1.9, this is expected behaviour.

The 4.3.9-397 you already have actually has all the changes included in 4.3.10. 4.3.10 is a stripped down release since we weren't ready to ship everything in master.

If you want to downgrade to 4.3.10 however you can do so with `brew developer off && brew update`.

**Comment by Whirlwind** [comment]
@Bo98 Thank you for your answer.

My question is that we do NOT open the developer mode, but it always pull the master branch.

**Comment by Bo98** [comment]
The command I stated above should work but you may need to add `--force` to the end: `brew developer off && brew update --force`

It works for me:

```console
$ brew developer
Developer mode is enabled.
$ brew --version
Homebrew 4.3.9-406-g0f0e2c7
$ brew developer off
$ brew update --force
==> Updating Homebrew...
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:40a1dbc25bb1a8bbdf0bba53d3f16c45416be12d4c6d48b4530f90b2a77d64ce
==> Pouring portable-ruby-3.3.3.x86_64_linux.bottle.tar.gz
Already up-to-date.
$ brew --version
Homebrew 4.3.10
$ brew developer on
$ brew update --force
==> Updating Homebrew...
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:44a5a8e4c5e4f74a346e50232c13b2ec54a72d8cb5d8ebc6965a197eefc9b03f
==> Pouring portable-ruby-3.3.4.x86_64_linux.bottle.tar.gz
Already up-to-date.
$ brew --version
Homebrew 4.3.9-406-g0f0e2c7
```

**Comment by Whirlwind** [comment]
Yeah, it works.

What I mean is that the developer mode of the brew we installed is enabled by default. Is this the expected behavior? Or did we have any incorrect operation that caused it to be turned on?

**Comment by MikeMcQuaid** [comment]
> What I mean is that the developer mode of the brew we installed is enabled by default.

It's expected that it's enabled in some configurations by default.

**Comment by Bo98** [comment]
It will auto-enable if you run any of these commands: https://github.com/Homebrew/brew/tree/master/Library/Homebrew/dev-cmd

**Comment by Whirlwind** [comment]
After I reinstall, it still enable. Is it expected?

**Comment by Bo98** [comment]
Depends on if `/opt/homebrew/.git/config` is deleted or not when you reinstall. That's where the developer setting is stored (among other things - so don't delete it unless you are fully uninstalling).

It shouldn't be enabled on a clean install.

**Comment by Whirlwind** [comment]
I have a request, can you also synchronize the version number of the master branch with the latest version number after releasing the new version?

I have a tool will update the homebrew to the latest version. But if the user is in developer mode, homebrew's version will is not the latest version, my script will be failed by compare the current version and the latest version.

eg:
```
latest_version=$(get_version_from_github)
current_version=$(brew --version)

if [[ "${latest_version}" != "${current_version}" ]]; then
    exit 1
fi
```

**Comment by Bo98** [comment]
For most releases it is. This is one of the exceptions.

We don't manually enter a version number. For developer mode, the version is determined by `git -C "$(brew --repo)" describe --tags --dirty --abbrev=7`. It doesn't pick up 4.3.10 because 4.3.10 is cherry-picks on a separate branch, which is not normal but we were forced to in this case.

I'm not sure the best way to fix that. Maybe if we pushed a `git merge 4.3.10` it might work.

**Comment by MikeMcQuaid** [comment]
> I'm not sure the best way to fix that. Maybe if we pushed a `git merge 4.3.10` it might work, though there will always be a slight delay between release and that merge commit being pushed.

Don't do that, please 😅. We can just wait for the next release.
