### ISSUE TITLE
`brew prune` gives Permission denied error

### ISSUE THREAD

**Issue by paanvaannd** [Homebrew/brew#1788]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug reports:

`brew config` output:

> HOMEBREW_VERSION: 1.1.6
> ORIGIN: https://github.com/Homebrew/brew.git
> HEAD: 619791e83d2781dca1b675e20249a8aebe085c7c
> Last commit: 2 days ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: adf1a90795a656bf98d18a04d904b78da723aa1f
> Core tap last commit: 73 minutes ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_REPOSITORY: /usr/local/Homebrew
> HOMEBREW_CELLAR: /usr/local/Cellar
> HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
> CPU: octa-core 64-bit ivybridge
> Homebrew Ruby: 2.0.0-p648
> Clang: 8.0 build 800
> Git: 2.11.0 => /usr/local/bin/git
> Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
> Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
> Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
> Java: 1.8.0_112, 1.7.0_45, 1.6.0_65-b14-468
> macOS: 10.12.3-x86_64
> Xcode: 8.2.1
> CLT: 8.2.0.0.1.1480973914
> X11: 2.7.11 => /opt/X11

---

`brew doctor` output:

> Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
> 
> Warning: Found Ruby file outside beeftornado/rmtree tap formula directory
(/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/Formula):
>   /usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/brew-rmtree.rb
> 
> Warning: Broken symlinks were found. Remove them with `brew prune`:
 >  /usr/local/share/man/man8/prlexec.8
 >  /usr/local/opt/brew-cask
 >  /usr/local/opt/json-c
 >  /usr/local/opt/pianobar
 >  /usr/local/opt/torsocks

---

Issue report:

Running `brew prune` produces the following error:

> Error: Permission denied - /usr/local/share/man/man8/prlexec.8

with no additional information given about the issue. Here are the details about the file giving the error (used `ls -la | grep prlexec.8` within the directory specified in the error dialog above):

> lrwxr-xr-x   1 <username_censored>  admin   143B Nov  5 15:52 prlexec.8 -> /Applications/Parallels Desktop.app/Contents/Frameworks/ParallelsVirtualizationSDK.framework/Versions/Current/Resources/English.lproj/prlexec.8

It's associated with Parallels Desktop, and it seems like a symlink.

Here is my OS information, if it helps: macOS Sierra (10.12.3 Beta)

Any help would be appreciated!

-- paanvaannd

**Comment by paanvaannd** [comment]
P.S. I have tried `chown` on the `prlexec.8` file to test whether changing its ownership to my user account (admin privileges, as shown in the original post after I changed ownership to me) would work but that did not work. I have since changed it back to `root`:

> llrwxr-xr-x   1 root   admin   143B Nov  5 15:52 prlexec.8 -> /Applications/Parallels Desktop.app/Contents/Frameworks/ParallelsVirtualizationSDK.framework/Versions/Current/Resources/English.lproj/prlexec.8

but I get the same error.

**Comment by MikeMcQuaid** [comment]
`sudo chown -R $USER /usr/local/share/man` but in general this is a bug you need to report to Parallels support.

**Comment by paanvaannd** [comment]
@MikeMcQuaid worked perfectly, and I'll be reporting it to the Parallels team soon. Thank you! :+)

**Comment by swvanderlaan** [comment]
Got the same error - apparently the Parallels team has not solved this yet.
