### ISSUE TITLE
Can't do that brew tap homebrew/homebrew-php

### ISSUE THREAD

**Issue by wubingzhe** [Homebrew/brew#1789]
Many Many Eorror, I don't know how to resolve them.
<img width="682" alt="2017-01-06 12 03 19" src="https://cloud.githubusercontent.com/assets/7846705/21687280/9ed44876-d3a3-11e6-8481-e1634346a40f.png">

**Comment by MikeMcQuaid** [comment]
`brew untap josegonzalez/php`.
