### ISSUE TITLE
virtualenv_create with options.

### ISSUE THREAD

**Issue by devgeist42** [Homebrew/brew#1790]
Currently, `virtualenv_create` does not accept any extra options. For packages that depend on python modules in `homebrew/python`, such as `numpy`, etc., passing `--system-site-packages` to `virtualenv` should be useful.

**Comment by MikeMcQuaid** [comment]
Will want @tdsmith's input on this.

**Comment by ilovezfs** [comment]
I think we already add them if they're declared as dependencies.

**Comment by tdsmith** [comment]
Thanks for the comment. Declared dependencies should already be accessible from the virtualenv; that's handled here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/python.rb#L126

If it isn't working, please open a ticket.

**Comment by kyungminlee** [comment]
I see. At the moment `virtualenv_create` only looks at formulae; python module dependencies are not accessible inside virtualenv. Is it be possible to make the python module deps available inside virtualenv?

**Comment by tdsmith** [comment]
I don't understand what you're suggesting isn't available.

**Comment by kyungminlee** [comment]
Even if you have `depends_on "numpy" => :python` in your formula, `numpy` is not accessible in the `virtualenv`.

**Comment by tdsmith** [comment]
Oh, sure. It would be hard to make that work and modules should just be
vendored as resources instead; maybe it should throw a warning.

**Comment by kyungminlee** [comment]
I see. That's what I thought. Thanks!

**Comment by MikeMcQuaid** [comment]
@kyungminlee It's worth noted that `depends_on "numpy" => :python` is somewhat deprecated (and I've made a note to officially deprecate it).
