### ISSUE TITLE
Issue installing openJDK

### ISSUE THREAD

**Issue by ljmaloney** [Homebrew/brew#17913]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
MacBook-Pro-3:~ luthermaloney$ brew config
HOMEBREW_VERSION: 4.3.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 874d2da45344d3b27aa740e555b0210d8c474220
Last commit: 12 hours ago
Core tap JSON: 30 Jul 18:46 UTC
Core cask tap JSON: 30 Jul 18:46 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 14.0.0 build 1400
Git: 2.45.2 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 12.7.5-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
MacBook-Pro-3:~ luthermaloney$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libical.0.0.0.dylib
  /usr/local/lib/libicalss.0.0.0.dylib
  /usr/local/lib/libicalvcal.0.0.0.dylib
  /usr/local/lib/libltdl.3.1.0.dylib

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libical.la
  /usr/local/lib/libicalss.la
  /usr/local/lib/libicalvcal.la
  /usr/local/lib/libltdl.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libdevkit.a
  /usr/local/lib/libical.a
  /usr/local/lib/libicalss.a
  /usr/local/lib/libicalvcal.a
  /usr/local/lib/libkld.a
  /usr/local/lib/libltdl.a
  /usr/local/lib/libredo_prebinding.a
MacBook-Pro-3:~ luthermaloney$
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

install openjdk

### What happened (include all command output)?

MacBook-Pro-3:~ luthermaloney$ brew install openjdk
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################################################################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openjdk/manifests/22.0.2
######################################################################################################################################################################################### 100.0%
==> Fetching openjdk
==> Downloading https://ghcr.io/v2/homebrew/core/openjdk/blobs/sha256:84795b272691e9ee02b9a0bb9fba35552c1ae8d3b977be2468dc71e57aa4e42f
######################################################################################################################################################################################### 100.0%
Error: invalid byte sequence in UTF-8
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:180:in `[]'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:180:in `block in keychain_username_password'
/usr/local/Homebrew/Library/Homebrew/utils/uid.rb:8:in `drop_euid'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:172:in `keychain_username_password'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:196:in `credentials'
/usr/local/Homebrew/Library/Homebrew/attestation.rb:65:in `enabled?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1280:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:435:in `install'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:237:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:301:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:300:in `each'
/usr/local/Homebrew/Library/Homebrew/install.rb:300:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:300:in `run'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Please report this issue:

### What did you expect to happen?

install openjdk

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
MacBook-Pro-3:~ luthermaloney$ brew install openjdk
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################################################################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openjdk/manifests/22.0.2
######################################################################################################################################################################################### 100.0%
==> Fetching openjdk
==> Downloading https://ghcr.io/v2/homebrew/core/openjdk/blobs/sha256:84795b272691e9ee02b9a0bb9fba35552c1ae8d3b977be2468dc71e57aa4e42f
######################################################################################################################################################################################### 100.0%
Error: invalid byte sequence in UTF-8
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:180:in `[]'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:180:in `block in keychain_username_password'
/usr/local/Homebrew/Library/Homebrew/utils/uid.rb:8:in `drop_euid'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:172:in `keychain_username_password'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:196:in `credentials'
/usr/local/Homebrew/Library/Homebrew/attestation.rb:65:in `enabled?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1280:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:435:in `install'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:237:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:301:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:300:in `each'
/usr/local/Homebrew/Library/Homebrew/install.rb:300:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:300:in `run'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Please report this issue:
```

**Comment by Bo98** [comment]
I believe this was already fixed before you opened the issue. Please try again and get in touch if the problem continues.
