### ISSUE TITLE
brew install summary gives the file size of the /opt/ symlink

### ISSUE THREAD

**Issue by JCount** [Homebrew/brew#1791]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug reports:

When `brew install` prints in the [summary](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L546-L552), rather than the intended output of `#{formula.prefix.abv}` being the size of the installation in total files and disk usage, [compute_disk_usage](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/pathname.rb#L28-L52) hits the `else` block since what is being read is a symlink. This leads to the size of the entire installation to be printed with no reference to the number of files, and solely as the size of the symlink according to the logic dictated as if it were a [one file installation](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/pathname.rb#L23). The fact the only thing being considered is whether `formula.prefix` is a directory, without following the symlink seems to be the issue. 

I have had trouble pinning down when this began for me, but I believe it has to coincide with some of the migration related changes to brew. 

Example:
```
brew install libass
==> Downloading https://homebrew.bintray.com/bottles/libass-0.13.6.el_capitan.bottle.tar.gz
Already downloaded: /Users/James/Library/Caches/Homebrew/libass-0.13.6.el_capitan.bottle.tar.gz
==> Pouring libass-0.13.6.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libass/0.13.6: 23B
```

[doctor and config](https://gist.github.com/JCount/c806139b21f58f5631a32169f361c514)

**Comment by ilovezfs** [comment]
Should be fixed by #1782 or an equivalent.
