### ISSUE TITLE
Failed to install Homebrew Portable Ruby (and your system version is too old)! 

### ISSUE THREAD

**Issue by sonictl** [Homebrew/brew#17923]
### `brew doctor` output

```shell
Failed to install Homebrew Portable Ruby (and your system version is too old)!
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: (I forgot.)
```

### What were you trying to do (and why)?

run `brew update` after indtalled brew with [Homebrew-4.3.12.pkg](https://github.com/Homebrew/brew/releases/download/4.3.12/Homebrew-4.3.12.pkg)

### What happened (include all command output)?

Failed to install Homebrew Portable Ruby (and your system version is too old)!

### What did you expect to happen?

==> Updating Homebrew...
Already up-to-date.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
On MacBookPro_14inch_M1-cpu, install [Homebrew-4.3.12.pkg](https://github.com/Homebrew/brew/releases/download/4.3.12/Homebrew-4.3.12.pkg)

open Terminal

`nano ~/.zshrc`

add `export PATH="/opt/homebrew/bin:$PATH"` into it

press CTRL + X，then press Y confirm save

`source ~/.zshrc`

brew update
```

**Comment by sonictl** [comment]
by the way the install cmd below reports that the curl can not access the .sh :

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

I have to use my browser to download the `install.sh` and run it manually.

**Comment by Bo98** [comment]
You didn't provide full logs so I can only guess, but if you are having issues with `curl` then it is likely that you're continuing to see those issues as `brew` itself uses `curl` extensively.

**Comment by sonictl** [comment]
But the error of `Failed to install Homebrew Portable Ruby (and your system version is too old)!`  is occured by the .pkg file.

**Comment by Bo98** [comment]
The pkg is not a fully offline installer. It doesn't currently bundle Portable Ruby and so downloads it.
