### ISSUE TITLE
Terraform -var-file not working for file present in the same directory

### ISSUE THREAD

**Issue by Snehac** [Homebrew/brew#1794]
I am trying to pass file name as command Line argument and following the examples i found on internet. following is the command i am using :

terraform plan -var-file=cert.tf
and get the following error:
invalid value "cert" for flag -var-file: Error reading cert: open cert: The system cannot find the file specified

Cert.tf is present in the same path where i am executing the command. I am using Windows machine and terraform --version is 0.8.2. 

This might not be the right place to ask this .. But i am not getting help from anywhere else

**Comment by MikeMcQuaid** [comment]
> I am using Windows machine

We only provide support for Homebrew on macOS, sorry. You may want to submit this to the terraform project themselves.
