### ISSUE TITLE
Feature Request: Homebrew updates, tap updates, and formulae updates should be separate commands

### ISSUE THREAD

**Issue by davepgreene** [Homebrew/brew#1800]
### Propose a feature:

Certain taps ([buo/homebrew-cask-upgrade][homebrew-cask-upgrade] specifically) relies on knowing the most up-to-date formulae before attempting to update. Unfortunately, `brew update` has some side effects beyond updating formulae; namely updating taps (including [homebrew-cask-upgrade]) as well as Homebrew core.

I propose that these 3 operations be separated into discrete commands that may or may not be part of the CLI API. `brew update` can tie them all together, but this will allow taps to update formulae separately and not risk self-updating or breaking themselves if the Homebrew API changes.

Also, as a separate note, is there a reason that the `brew update` command is still a shell script? I noticed that most of the [commands](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/cmd) are ruby files.

[homebrew-cask-upgrade]: https://github.com/buo/homebrew-cask-upgrade

**Comment by MikeMcQuaid** [comment]
Sorry, this isn't something we'll implement.

**Comment by MikeMcQuaid** [comment]
> Also, as a separate note, is there a reason that the brew update command is still a shell script? I noticed that most of the commands are ruby files.

For speed, to avoid issues with Ruby code updating itself and to allow updates when there's problems with the current Ruby.
