### ISSUE TITLE
how to pick `revision` field

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#1802]
```
cd $homebrew_D/Library/Taps/homebrew/homebrew-core/Formula
git grep -n revision|less
```

shows lots of revision with what seems like a git hash:
```
ldc.rb:9:        :revision => "3461e00f3531f855f9fc6e92515d7affb8201827"
```
vs ones that look like a single digit number, eg: ` libbtbb.rb:7:  revision 1`

Looks like the latter are more inline with what's suggested in docs https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

Are the former ones incorrect?

**Comment by MikeMcQuaid** [comment]
Those are different parameters; one is for the `GitDownloadStrategy`, the other is for the `Formula`/`SoftwareSpec`.
