### ISSUE TITLE
confusing error when not giving enough arguments to bump-formula-pr

### ISSUE THREAD

**Issue by Habbie** [Homebrew/brew#1805]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Propose a feature:
```
$ brew bump-formula-pr jdnssec-tools
Error: no implicit conversion of nil into String
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:315:in `initialize'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:315:in `new'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:315:in `ext'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:325:in `initialize'
/usr/local/Homebrew/Library/Homebrew/resource.rb:54:in `new'
/usr/local/Homebrew/Library/Homebrew/resource.rb:54:in `downloader'
/usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:138:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

I know my syntax is wrong (I'm missing arguments), but the output could be more helpful about that.

**Comment by MikeMcQuaid** [comment]
CC @ilovezfs for thoughts.

**Comment by ilovezfs** [comment]
```
      elsif !hash_type
        odie "#{formula}: no tag/revision specified!"
 +    elsif !new_url
 +      odie "#{formula}: no url specified!"
      else
```
is probably good enough
