### ISSUE TITLE
Happened ruby runtime error on macOS Sequoia

### ISSUE THREAD

**Issue by 97lily** [Homebrew/brew#18076]
### `brew doctor` output

```shell
brew doctor 
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
Already downloaded: /Users/username/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
Error: Checksum mismatch.
Expected: ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
  Actual: 9712e12bd7af5092617e4c7c907180e1dfa14a5d5ee0cd1582c3049df6ceaba9
 Archive: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade Homebrew Portable Ruby!
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
brew  config                            
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
Already downloaded: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
Error: Checksum mismatch.
Expected: ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
  Actual: 9712e12bd7af5092617e4c7c907180e1dfa14a5d5ee0cd1582c3049df6ceaba9
 Archive: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade Homebrew Portable Ruby!
```

### What were you trying to do (and why)?

firstly im updated macOS Sequoia Beta 15.0 (24A5320a).
and im exectured **brew upgrade**...well resultly dropped the error
and im reinstalled brew but the issued is still happened

### What happened (include all command output)?

❯ brew upgrade
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
Already downloaded: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
Error: Checksum mismatch.
Expected: ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
  Actual: 9712e12bd7af5092617e4c7c907180e1dfa14a5d5ee0cd1582c3049df6ceaba9
 Archive: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade Homebrew Portable Ruby!

~ 
❯ brew doctor 
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
Already downloaded: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
Error: Checksum mismatch.
Expected: ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
  Actual: 9712e12bd7af5092617e4c7c907180e1dfa14a5d5ee0cd1582c3049df6ceaba9
 Archive: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade Homebrew Portable Ruby!

~ 
(NOTE:im not snipped those error output)

### What did you expect to happen?

I would appreciate it if you could update again.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
Already downloaded: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
Error: Checksum mismatch.
Expected: ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
  Actual: 9712e12bd7af5092617e4c7c907180e1dfa14a5d5ee0cd1582c3049df6ceaba9
 Archive: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade Homebrew Portable Ruby!

~ 
❯ brew doctor 
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
Already downloaded: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
Error: Checksum mismatch.
Expected: ce5c135bf98da783bf5964e89aab587e3341c8adc379f36ace17ae7881f53e8c
  Actual: 9712e12bd7af5092617e4c7c907180e1dfa14a5d5ee0cd1582c3049df6ceaba9
 Archive: /Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade Homebrew Portable Ruby!

~
```

**Comment by ZhongRuoyu** [comment]
Please remove `/Users/frisk/Library/Caches/Homebrew/portable-ruby-3.3.4_1.arm64_big_sur.bottle.tar.gz` and try again.
