### ISSUE TITLE
homebrew x11 support

### ISSUE THREAD

**Issue by larryhynes** [Homebrew/brew#1811]
Hi

Following the recent deletion of 21 formulas from homebrew-x11 as 'unused', I've opened [this issue](https://github.com/Homebrew/homebrew-x11/issues/285) to hopefully shed some light on how and why these formulas came to be deleted.

Can I ask the homebrew core devs, please, for a statement on X11 support 'going forward'?

**Comment by woodruffw** [comment]
Closing in favor of your other issue. Thanks for bringing this to our attention!
