### ISSUE TITLE
`man brew` out of sync with `brew --help` (`remove` command)

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#1817]
`man brew` shows a `remove` command in ESSENTIAL COMMANDS that's not in `brew --help`

EDIT: ok i thought the `remove` command didn't exist anymore but looks like it's an alias to `uninstall`; so this is a very minor bug; still though, would be nice to have `ESSENTIAL COMMANDS` be in sync with `brew --help`

And maybe also add in `brew --help` to lookup `man brew` fore more commands

**Comment by MikeMcQuaid** [comment]
Good idea, I agree. Opened https://github.com/Homebrew/brew/pull/1826.
