### ISSUE TITLE
man:`brew rm <foo> && brew install --HEAD <foo>` => reinstall

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#1818]
man brew:
`To install a newer version of HEAD use brew rm <foo> && brew install --HEAD <foo>.`

=>  why not suggest: `brew reinstall --HEAD <foo>` ? is that different?

**Comment by MikeMcQuaid** [comment]
Just a brief CC for @vladshablinsky to check this will work as expected.

**Comment by vladshablinsky** [comment]
Can't it just be removed? We're able to upgrade HEAD now.

**Comment by MikeMcQuaid** [comment]
@vladshablinsky Good point, thanks ⚡️
