### ISSUE TITLE
man: `brew search`:  `-S` option not documented

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#1819]
```
 search, -S
              Display all locally available formulae for brewing (including tapped ones). No online search is performed if called without arguments.
```
couldn't find anything either in `brew command search`
(/home/timothee/.linuxbrew/Library/Homebrew/cmd/search.rb)

Does the above doc mean the following?
```
`brew search`       => all locally available formulae [No online search]
`brew search -S ` => all locally available formulae
```

if so, not sure if that makes sense:
```
brew search      =>5241 lines
brew search -S =>203 lines
```
which doesn't make sense (no online search => more results?)

**Comment by bfontaine** [comment]
`-S` is an alias for `search`: https://github.com/Homebrew/brew/blob/871213932763eac4f62ec3a9d2dcbaffdc2042fa/Library/Homebrew/global.rb#L68

`brew -S foo` is equivalent to `brew search foo`.
