### ISSUE TITLE
Add a more customizable ENV file loading process

### ISSUE THREAD

**Issue by xycabcd** [Homebrew/brew#18198]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Let users choose which ENV file they want to load. 
For example, a file on Library/Configs have few lines written in it, while each line contains a path to a ENV file.
Then Homebrew load these files one by one.

### What is the motivation for the feature?

Users can load costomized ENV file, or choose to not load a ENV file

### How will the feature be relevant to at least 90% of Homebrew users?

They can have their own group of ENV files on their computer, and can organize them better

### What alternatives to the feature have been considered?

N/A

**Comment by Bo98** [comment]
Customisable in what way? For simple cases there is the `~/.homebrew/brew.env` and for more complex cases there is `.zprofile`/`.zshenv` or wherever you already have your `eval $(brew --shellenv)`.

**Comment by MikeMcQuaid** [comment]
@xycabcd You were asked to not make more discussions, this extends to low-context issues like this too.
