### ISSUE TITLE
Hosting a Local Homebrew Cache for Intranet

### ISSUE THREAD

**Issue by pate** [Homebrew/brew#1820]
I'm presenting at a conf with limited bandwidth. I would like to let attendees install a particular app/cask (`brew cask install sonic-pi`) without saturating the network. Assuming we can sort out the trust issues, Is there a way to let users download from a local Homebrew cache I can run off a box, or maybe someone has envisioned an intranet torrenting solution?

Feel free to close if not possible.

**Comment by scpeters** [comment]
I haven't tested it with `cask`, but I know you can pass a formula.rb file or URL directly to `brew install`, so perhaps you could just have them install from a local webserver?

~~~
brew cask install http://conference.local/sonic-pi.rb
~~~

Then if the resources were also available on that local web-server, the formula could reference them.

Maybe that would work?

**Comment by MikeMcQuaid** [comment]
Check out `HOMEBREW_BOTTLE_DOMAIN` and `HOMEBREW_ARTIFACT_DOMAIN` in `man brew`; they should be able to help you use Homebrew binary packages in this way. As for Casks I'm not sure ( @vitorgalvao may be able to help) and formulae there's no easy way of accomplishing this besides asking people to copy files manually to `HOMEBREW_CACHE`.
