### ISSUE TITLE
macos sequoia 15.1 : We do not provide support for this pre-release version.

### ISSUE THREAD

**Issue by FlowerHuaer** [Homebrew/brew#18222]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
☁  ~  brew config
HOMEBREW_VERSION: 4.1.25-50-g2e9d7fb
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2e9d7fbcf81134fbe594d5a18b5387dad76383a1
Last commit: 9 months ago
Core tap JSON: 02 Sep 03:03 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.0.0.0.1.1723780521
Xcode: N/A
Rosetta 2: false
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install software through brew

### What happened (include all command output)?

After upgrading to macOS 15, brew cannot install any software. Please help me

### What did you expect to happen?

Can install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
☁  ~  brew install librdkafka
Warning: You are using macOS 15.
We do not provide support for this pre-release version.
It is expected behaviour that some formulae will fail to build in this pre-release version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

Error: unknown or unsupported macOS version: :dunno
```

**Comment by ZhongRuoyu** [comment]
```
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2e9d7fbcf81134fbe594d5a18b5387dad76383a1
Last commit: 9 months ago
```

Your `brew` is very outdated. Please run `brew update` and try again.

**Comment by iMichka** [comment]
Upgrading brew is the first step. But nevertheless, we do not yet support macOS 15. The message is still true.
I would recommend opening a discussion in https://github.com/orgs/Homebrew/discussions.

**Comment by FlowerHuaer** [comment]
> ```
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: 2e9d7fbcf81134fbe594d5a18b5387dad76383a1
> Last commit: 9 months ago
> ```
> 
> 您的`brew`版本已过时。请运行`brew update`并重试。

感谢,我进行了一下步骤之后貌似已经恢复了""

**Comment by chaxus** [comment]
> > ```
> > ORIGIN: https://github.com/Homebrew/brew
> > HEAD: 2e9d7fbcf81134fbe594d5a18b5387dad76383a1
> > Last commit: 9 months ago
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 您的`brew`版本已过时。请运行`brew update`并重试。
> 
> 感谢,我进行以下步骤之后貌似已经恢复了 1.git -C "/opt/homebrew" remote set-url origin https://github.com/Homebrew/brew 2.brew update
> 
> ```
> ☁  ~  brew config
> HOMEBREW_VERSION: 4.3.18
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: abc0584215659c5a8716d0798ea2801388d01368
> Last commit: 7 days ago
> Core tap JSON: 02 Sep 05:48 UTC
> Core cask tap JSON: 02 Sep 05:48 UTC
> HOMEBREW_PREFIX: /opt/homebrew
> HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
> HOMEBREW_CASK_OPTS: []
> HOMEBREW_MAKE_JOBS: 8
> Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
> CPU: octa-core 64-bit arm_blizzard_avalanche
> Clang: 16.0.0 build 1600
> Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
> Curl: 8.7.1 => /usr/bin/curl
> macOS: 15.1-arm64
> CLT: 16.0.0.0.1.1723780521
> Xcode: N/A
> Rosetta 2: false
> ```

Wow, thank you very much. I had the same problem. The solution works for me, too.

**Comment by carlocab** [comment]
> For some reason `brew update` didn't work for me, but this did:
> 
> ```shell
> cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
> ```

Next time, you it might be simpler to do `brew update-reset "$(brew --repository)"`.
