### ISSUE TITLE
brew cleanup --hlep should raise instead of starting the cleanup

### ISSUE THREAD

**Issue by dwt** [Homebrew/brew#1823]
### Bug reports:

I invoked `brew cleanup --hlep` and only figured out when it started deleting files that I had misspelled the option.

IMO `brew cleanup` should raise if it encounters unknown options to prevent this easy mistake.

**Comment by bfontaine** [comment]
Related to #8937.

**Comment by jshawl** [comment]
Just a question. `ARGV.options_only` allows arbitrary options to be passed to any brew command.

https://github.com/Homebrew/brew/blob/e6933b90dc750dc9aadb3bfb6acf1bf395942d57/Library/Homebrew/test/ARGV_test.rb#L34-L35

I'm interested in implementing a fix (first time contributor), but didn't want to rewrite test cases unless this behavior is intended

**Comment by MikeMcQuaid** [comment]
Thanks for the report. Have described this in a `help wanted` option here: #1860
