### ISSUE TITLE
Better handling of `$ brew list` throwing `Error: You have not agreed to the Xcode license.`

### ISSUE THREAD

**Issue by jpluimers** [Homebrew/brew#1824]
After Migration Assistant of a .dmg Disk Utility backup from my old Mac (with Yosemite 10.10) to my new Mac (with Sierra 10.12) I get this on any `brew` command (I tried `list`, `update`, `doctor`, `config`).

```
$ brew list
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept
```

Since even `brew list` and `brew config` throw this, I cannot find out which formula has an Xcode dependency.

So either this message should indicate the dependency tree, or the commands that can research the dependency tree should not throw this error.

**Comment by bfontaine** [comment]
What is your issue?

**Comment by jpluimers** [comment]
@bfontaine sorry, I pressed the enter key on a new Mac and somehow it submitted instead of putting a new line in the description box.

**Comment by bfontaine** [comment]
This seems to be printed independently of the formulae you have installed: https://github.com/Homebrew/brew/blob/9cce3414fbd39d146d97911dbb3bf07fffaa1080/Library/Homebrew/brew.sh#L167

**Comment by jpluimers** [comment]
Is it possible to "undo" the `sudo xcodebuild -license accept` in order to test `brew.sh` script alterations?

**Comment by MikeMcQuaid** [comment]
If you've got Xcode installed you need to accept the license. As noted, this is not a formula-level requirement.
