### ISSUE TITLE
Document cryptographic signature usage for authenticity

### ISSUE THREAD

**Issue by maltfield** [Homebrew/brew#18248]
### `brew doctor` output

```shell
I don't use `brew` because I'm not sure it's safe
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
I don't use `brew` because I'm not sure it's safe
```

### What were you trying to do (and why)?

This bug ticket is to report that I couldn't find the documentation that describes how `brew` utilizes cryptographic signatures to verify the authenticity of everything that it downloads.

In a recent [discussion](https://github.com/orgs/Homebrew/discussions/691#discussioncomment-10539315) , @p-linnane indicated that at-risk users should not use `brew` because it does not verify the authenticity of packages that it downloads using cryptographic signatures like other package managers do (eg [apt-secure](https://wiki.debian.org/SecureApt))

> If you are in a position where you believe a threat actor is trying to MITM you, change bottle hashes, and get you to install a malicious bottle, then you should not be using Homebrew. Most users retrieve bottle information via our signed JSON API. Users can also opt into our attestation beta by setting the environment variable I previously provided. We are responsible for the contents of Homebrew/core. We are not responsible for the security of your HTTPS connections.

But @Bo98 and @woodruffw both indicated that `brew` *does* verify the signatures of the hash files.

## Problem

Most security experts don't trust `brew` because, unlike most other package managers, it doesn't clearly document if/how it uses cryptographic signatures to verify the authenticity of what it downloads.

It would greatly benefit the community to document this security posture to make it clear what `brew` does to protect its users from malicious actors, and what it doesn't do

## Solution

Update [the `brew` documentation](https://docs.brew.sh/) with a section that describes how `brew` utilizes cryptographic signatures to ensure the authenticity of what it downloads, including a section describing where `brew` does not utilize cryptographic signatures to ensure the authenticity of what it downloads.

 * https://docs.brew.sh/

### What happened (include all command output)?

I don't use `brew` because I'm not sure it's safe

### What did you expect to happen?

I expected to find a `Security` section in the [Brew Documentation](https://docs.brew.sh/)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Go to https://docs.brew.sh/
1. Look for "Security" section
1. ????
1. Get confused and open ticket
```

**Comment by MikeMcQuaid** [comment]
> I don't use `brew` because I'm not sure it's safe

If you don't use Homebrew: don't open issues here.

**Comment by MikeMcQuaid** [comment]
Locking this because this is an ongoing discussion in https://github.com/orgs/Homebrew/discussions/691#discussioncomment-10537831 and this is not a "bug".
