### ISSUE TITLE
update-python-resources munges`--extra-packages` if it's a URL

### ISSUE THREAD

**Issue by ctaintor** [Homebrew/brew#18276]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.19-98-g9978c3d-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9978c3d11ac9108940ee0976a362d0d5872e0916
Last commit: 15 hours ago
Core tap JSON: 07 Sep 07:55 UTC
Core cask tap JSON: 07 Sep 07:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_ARTIFACT_DOMAIN: https://<internal>
HOMEBREW_CASK_OPTS: []
HOMEBREW_DOCKER_REGISTRY_BASIC_AUTH_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_PIP_INDEX_URL: https://<internal>
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.46.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.2 => /Applications/Xcode-15.2.0.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

I'm trying to use `update-python-resources` on an internal library which has internal dependencies. This is proving a pain for two reasons:
* [pypi_info](https://github.com/Homebrew/brew/blob/9978c3d11ac9108940ee0976a362d0d5872e0916/Library/Homebrew/utils/pypi.rb#L63-L67) hardcodes to `https://pypi.org/pypi/`
* our artifact server (artifactory) does not support the JSON api :(

Rather than patch (or send a PR if wanted) brew to fallback to the simple api, I thought I could get away with adding the internal packages as URL arguments to `--extra-packages` since the code _seems_ to support this.

### What happened (include all command output)?

```
$ brew update-python-resources Formula/my-formula.rb --verbose --extra-packages "https://a.b.net/.../...0.2.31"
==> Retrieving PyPI dependencies for "<path-to-my-formula-package> https://a-b-net/.../...-0-2-31-tar-gz"...
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x106704810>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': .../...-0-2-31-tar-gz
...-0-2-31-tar-gz (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x106707090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

(note that the URL has been munged, changing all `.` to be `-`, obviously meaning that the hostname can't be resolved)

### What did you expect to happen?

I did not expect that error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I believe you could reproduce this by adding a URL to a package at PyPi.

I am pretty sure that the offending code is [here](https://github.com/Homebrew/brew/blob/9978c3d11ac9108940ee0976a362d0d5872e0916/Library/Homebrew/utils/pypi.rb#L411). I tried changing it to:


    if name.start_with?("http")
      name
    else
      name.gsub(/[-_.]+/, "-").downcase
    end


and I was able to get farther along in the update (as in, it was able to read the metadata of the URL'd package). However, I will still need to implement the "fallback to simple api".
```

**Comment by carlocab** [comment]
This seems more like a feature request for `--extra-packages` to accept arbitrary URLs rather than just PyPI package names.

Could you answer the questions in the feature request template instead? https://github.com/Homebrew/brew/issues/new?assignees=&labels=features&projects=&template=feature.yml

**Comment by ctaintor** [comment]
Opened #18282 to make it cleaner. Since --extra-packages _did_ do some expected work when I passed a URL, it was unclear if this was a bug or a feature request
