### ISSUE TITLE
`update-python-resources` should support non-PyPI indexes

### ISSUE THREAD

**Issue by ctaintor** [Homebrew/brew#18282]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I'd like to have `--update-python-resources` support `--extra-pacakges` where the package is a URL, not a name. A call would look like:

```
brew update-python-resources Formula/a.rb --include-packages "https://example.com/...../0.2.1.tar.gz#SHA256"
```

### What is the motivation for the feature?

my main motivation is to make minimal changes to allow `--update-python-resource` work when some of the main package dependencies are not in PyPi. In my case, I have a main package (let's call it package A) which depends on a private package B and that package B depends on another private package C. A, B and C all also depend on packages in PyPi.

### How will the feature be relevant to at least 90% of Homebrew users?

It's unlikely that this would be useful to 90% of Homebrew users but it will be relevant to users who are using private packages.

### What alternatives to the feature have been considered?

An alternative is to adjust `--update-python-resources` support non-PyPi sources for the pypi_info call – by e.g. taking a parameter or using `PIP_INDEX_URL`. While this sounds easy, the core problem with supporting this is that package sources are not required to support the JSON API, so one of the most popular private package sources (Artifactory) does not support the JSON api. This means an alternative is to:
* modify `--update-python-resources` to accept a simple api endpoint as a parameter (or similar)
* modify `--update-python-resources` to be ale to use the JSON API _or_ the simple api

the work to support `--extra-packages` which are URLs simple seems a little easier and potentially more flexible.

**Comment by ctaintor** [comment]
I wrote a sort of brute-force patch of this just to see what was necessary and if this made any sense. Seems to work, however [this](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/pypi.rb#L320-L324) prevents running it a 2nd time (unless you delete the "other" resources).

**Comment by carlocab** [comment]
> I wrote a sort of [brute-force patch](https://github.com/ctaintor/brew/commit/0cb10212fb2b3a702dbdf7f23e149aba9dbfa1a0) of this just to see what was necessary and if this made any sense. Seems to work, however [this](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/pypi.rb?rgh-link-date=2024-09-08T14%3A18%3A20Z#L320-L324) prevents running it a 2nd time (unless you delete the "other" resources).

Given this, it seems more generally useful if:
- your non-PyPI `resource`s declared `livecheck` blocks
- `bump-formula-pr` knew to update `resource`s with `livecheck` blocks

The latter has been on our nice-to-have-list for a while now. There is some support for the former, but I'm not sure it's complete.

**Comment by MikeMcQuaid** [comment]
> * `bump-formula-pr` knew to update `resource`s with `livecheck` blocks

Agree that I think this is what should be built here.

**Comment by ctaintor** [comment]
in my exact case, simply supporting non-JSON-api repos would solve the problem. should I look at doing this instead? It just means pulling in another dep (REXML?) and then having two implementations of pypi_info i believe

**Comment by carlocab** [comment]
> in my exact case, simply supporting non-JSON-api repos would solve the problem.

I'm not sure I understand this. Could you elaborate?

> It just means pulling in another dep (REXML?) and then having two implementations of pypi_info i believe

I don't think we should expand the scope of `update-python-resources`. `bump-formula-pr` should handle this correctly instead.

**Comment by Bo98** [comment]
> Given this, it seems more generally useful if:
> 
> * your non-PyPI `resource`s declared `livecheck` blocks
> * `bump-formula-pr` knew to update `resource`s with `livecheck` blocks

This part is a dupe of #17401

**Comment by carlocab** [comment]
Closing as a duplicate of https://github.com/Homebrew/brew/issues/17401.

**Comment by ctaintor** [comment]
@carlocab – let me explain. In this example, I have a CLI that is published privately as a Python package. The CLI depends on another private package and that private package depends on another. Let's call the CLI `my-cli` and it depends on `direct-dep` and that one depends on `indirect-dep`. `my-cli`, `direct-dep` and `indirect-dep` are all available from a private python repository hosted by Artifactory and all of them also rely on public packages. Someone would install `my-cli` by simply running:
```
 PIP_INDEX_URL=https://<host>/artifactory/api/pypi/v-pypi-production/simple pip install my-cli
 ```
 the repository is what Artifactory calls a "virtual repository". It just means that it presents itself as a single repository and will resolve libraries first from the included local repositories (where `my-cli`, `direct-dep` and `indirect-dep` are published) before resolving from the remote pypi repository. So – when pip installs `my-cli`, it will resolve dependencies, finding `direct-dep`, resolving that and finding `indirect-dep` etc etc. It will of course also find and resolve public packages.
 
The problem with `update-python-resources` today is that it only relies on pypi to resolve what content should go into the `resources` blocks. If it instead used my PIP_INDEX_URL above, then everything would work. However, it's not that simple. The JSON API to pypi supports is _relatively_ new and it is _not required that repositories implement it_. This means that Artifactory does not support it and it's also probably unlikely that it would ever support it unless it became mandatory. Artifactory (and I assume many other, similar tools) only supports the simple api, which is an HTML API.
 
 If `update-python-resources` used the simple api then things would "just work" by me changing the URL to be my artifactory URL. Instead, supporting other repository hosts requires updating `update-python-resources` to either support only the simple api (so, remove the JSON api usage to make it universal) _or_ modify it to support both json or simple.

**Comment by carlocab** [comment]
Thanks for the explanation!

In that case, this should be covered by the more general solution proposed at #17401 (but you may need to add `livecheck` blocks to your non-PyPI resources).

**Comment by ctaintor** [comment]
well, not really because a private libraries dependencies could change, such that resource blocks could be added or subtracted.

I'm not sure I see the value of `livecheck` on Python resources – mostly because it would be more correct to run `update-python-resources` in all cases? Or is the livecheck there just to suggest that `update-python-resources` should be run?

**Comment by carlocab** [comment]
Got it; thanks for explaining.

**Comment by very-doge-wow** [comment]
I am having the exact same problem.

I also don't see this as a niche use-case - in any enterprise environment there are usually mirrors of public repositories which need to be used instead of accessing directly e.g. `PyPI.org`, for example because of rate-limits.

Artifactory (which has already been mentioned here) also supports the PyPI API and not only the simple API. So for this to work, only two minor things need to be added to the `update-python-resources` command :

* HOMEBREW_PIP_INDEX_URL needs to be respected
* Add another variable to specify the [PYTHONHOSTED_URL_PREFIX](https://github.com/Homebrew/brew/blob/e49b36d118e276988595907655250063eababeab/Library/Homebrew/utils/pypi.rb#L8C3-L8C26

It would work not only with Artifactory, but with all artifact storage systems which support the PyPI API spec.
