### ISSUE TITLE
brew update doesn't show outdated formulae on second run

### ISSUE THREAD

**Issue by kcarnold** [Homebrew/brew#18280]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libndi.dylib

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  fish_add_path /opt/homebrew/sbin
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1f9bd2de89883ec9a59db3eab0f5475bce06d5bc
Last commit: 5 days ago
Core tap JSON: 07 Sep 16:26 UTC
Core cask tap JSON: 07 Sep 16:26 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 15.0.0 build 1500
Git: 2.46.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

update software

### What happened (include all command output)?

```
ka37@Mac56723 ~> brew update
==> Updating Homebrew...
Already up-to-date.
ka37@Mac56723 ~> brew outdated
corepack (0.29.3) < 0.29.4
json-glib (1.8.0) < 1.10.0
nss (3.103) < 3.104
py3cairo (1.26.1) < 1.27.0
uv (0.4.6) < 0.4.7
```

### What did you expect to happen?

I'd see the normal list of outdated formulae on the second time as well as the first time. The message "Already up to date" is only partially true: the local copy of the formula list is up to date, but that doesn't mean installed formulas are up to date.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew update
```

**Comment by carlocab** [comment]
This is by design. The first `brew update` shows you which formulae have become outdated given the update it acquired. In your second `brew update`, no formulae have become outdated (since you didn't acquire any updates), so there is nothing to show.

If you want a command that updates `brew` and always shows the outdated installed formulae, consider an alias, like [this one](https://github.com/ohmyzsh/ohmyzsh/blob/80fa5e137672a529f65a05e396b40f0d133b2432/plugins/brew/brew.plugin.zsh#L61).

**Comment by kcarnold** [comment]
Ok. Then I'd suggest clarifying the message given by the second `brew update`.

**Comment by carlocab** [comment]
I'm not sure how to clarify it, so pull requests are welcome.
