### ISSUE TITLE
Consider setting `XDG_DATA_DIRS` in `shellenv` on Linux

### ISSUE THREAD

**Issue by notfirefox** [Homebrew/brew#18317]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

It would be nice if the command below would set up everything needed on Linux.
```sh
$ eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
```

It does however not configure `$XDG_DATA_DIRS` as shown below.
```sh
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider adding Homebrew's share directory to XDG_DATA_DIRS like so:
  echo 'export XDG_DATA_DIRS="/home/linuxbrew/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.zshrc
```

The suggestion would be to let the `shellenv` script also handle the `$XDG_DATA_DIRS` environment variable, e.g.
```sh
if [ -n "$XDG_DATA_DIRS" ]; then
    export XDG_DATA_DIRS="/home/linuxbrew/.linuxbrew/share:$XDG_DATA_DIRS"
fi
```

> 

### What is the motivation for the feature?

The `shellenv` script is there to assist the user with the setup of the shell environment. Therefore it might be sensible to also let it handle the `$XDG_DATA_DIRS` environment variable.

### How will the feature be relevant to at least 90% of Homebrew users?

This feature only affects Homebrew users on Linux.

### What alternatives to the feature have been considered?

Keeping the situation as it is, i.e. not setting `$XDG_DATA_DIRS` in the `shellenv` script.

**Comment by MikeMcQuaid** [comment]
This could be set as long as it's Linux-only 👍🏻
