### ISSUE TITLE
Multiple Formula giving `Error: Couldn't find manifest matching bottle checksum.`

### ISSUE THREAD

**Issue by aselder** [Homebrew/brew#18319]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: c5d09b411776547bdbc8e0435deaf690ca632413
Last commit: 21 hours ago
Core tap JSON: 13 Sep 05:39 UTC
Core cask tap JSON: 13 Sep 05:39 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nova -w
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.46.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 16.0.0.0.1.1723780521
Xcode: 16.0
Rosetta 2: false
```

### What were you trying to do (and why)?

Run `brew update`. Weechat failed with the error message. I then uninstalled weechat and tried to reinstall, and `cjson` is blowing up with the same error.

### What happened (include all command output)?

```
❯ brew upgrade
==> Upgrading 1 outdated package:
weechat 4.4.1 -> 4.4.2
==> Downloading https://ghcr.io/v2/homebrew/core/weechat/manifests/4.4.2
Already downloaded: /Users/aselder/Library/Caches/Homebrew/downloads/7d5cd30103b9c73c1c16046315fcef8fae9afa261f606f6fd48c717942bdd8e2--weechat-4.4.2.bottle_manifest.json
==> Fetching weechat
==> Downloading https://ghcr.io/v2/homebrew/core/weechat/blobs/sha256:59b7d3d1a8900eb7c54fa3af1d910d785522b8f44f879f60f471487cb02ad8e7
Already downloaded: /Users/aselder/Library/Caches/Homebrew/downloads/0d6e0f261e51ee3173b39d701bc611110d08c1cc78e019ee410ed1cf3035d8a9--weechat--4.4.2.arm64_sequoia.bottle.tar.gz
==> Upgrading weechat
  4.4.1 -> 4.4.2
==> Pouring weechat--4.4.2.arm64_sequoia.bottle.tar.gz
Error: Couldn't find manifest matching bottle checksum.
```

```
❯ brew install cjson
==> Downloading https://ghcr.io/v2/homebrew/core/cjson/manifests/1.7.18
Already downloaded: /Users/aselder/Library/Caches/Homebrew/downloads/3284084a143535a014f36b2aa7c948c6a28417940feba238b9425e4715e26a2b--cjson-1.7.18.bottle_manifest.json
==> Fetching cjson
==> Downloading https://ghcr.io/v2/homebrew/core/cjson/blobs/sha256:369cf21b89c82a4f1834fb3c8a128f5bf970f22bbb13376652448fbde998dad9
Already downloaded: /Users/aselder/Library/Caches/Homebrew/downloads/e88ec5742f67904c31ad9b486fdb5b3f36546cde525a28be14f52f3c5f0b18d4--cjson--1.7.18.arm64_sequoia.bottle.tar.gz
==> Pouring cjson--1.7.18.arm64_sequoia.bottle.tar.gz
Error: Couldn't find manifest matching bottle checksum.
```

### What did you expect to happen?

Formulas to install successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install weechat
```

**Comment by carlocab** [comment]
Thanks for the report. Can you do the following (in the order listed, please):
1. In your shell, run `tar czf api_cache.tar.gz -C "$(brew --cache)" ./api/`
2. Upload the resulting `api_cache.tar.gz` to this issue
3. Run `rm -rf "$(brew --cache)"`
4. Try `brew install weechat` again

**Comment by aselder** [comment]
@carlocab Blowing away the cache allowed things to proceed smoothly. Thanks for the pointer. I've attached the tarball of the cache.

[api_cache.tar.gz](https://github.com/user-attachments/files/16996035/api_cache.tar.gz)

**Comment by Bo98** [comment]
Looks like a regression with https://github.com/Homebrew/brew/commit/ae6f43921ae0389973fe62b0f74d11ba6bbbd31b

and this line now needs updating: https://github.com/Homebrew/brew/blob/798bfac4831f61c93b76c1efd50e58a4211c89cc/Library/Homebrew/software_spec.rb#L422

**Comment by xakep8** [comment]
we could also make a ChecksumError and do the operation only if this error occurs

**Comment by StarWitch** [comment]
I also had to wipe out the cache as described by @carlocab in the above post, on macOS 15.0.
