### ISSUE TITLE
pkg missing for release 4.3.21 assets

### ISSUE THREAD

**Issue by PatrickRoumanoff** [Homebrew/brew#18335]
### `brew doctor` output

```shell
#NA
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
#NA
```

### What were you trying to do (and why)?

I am trying to install Homebrew-4.3.21.pkg 

### What happened (include all command output)?

file is missing from release assets

### What did you expect to happen?

I expect the pkg file to be published with release assets

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
#NA
```

**Comment by carlocab** [comment]
The installer package workflow failed for 4.3.21: https://github.com/Homebrew/brew/actions/runs/10828788719

You can get the installer package by following the link above and downloading the `Homebrew-4.3.21.pkg` link under **Artifacts** at the bottom of the page.

**Comment by PatrickRoumanoff** [comment]
thank you for the link, I didn't know about this page.

**Comment by Bo98** [comment]
I'll tag 4.3.22 shortly which will fix this. Thanks for reporting.

**Comment by MikeMcQuaid** [comment]
Closing as next tag will fix, thanks for report @PatrickRoumanoff.
