### ISSUE TITLE
discussion: automated tool to spot relevant errors in `brew gist-logs` and fix some

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#1834]
Is there a plan for an automated tool to spot relevant errors in brew gist-logs ?
This could be generated in the brew gist-logs command or elsewhere.

To make it robust would be the topic of an interesting machine learning project [1], but I would assume even a few simple rules based on regex patterns would cover a lot of use cases, eg:

search for (case insensitive) '\berror\b'\bundefined symbol\b etc

Follow-ups: suggesting potential fixes [2] (and maybe even automated PR's that would be submitted to a queue if they actually fix the problem, running in a docker sandbox for security)

[1] ML project to automatically find relevant errors:
training data = submitted PR's
input=brew gist-logs before PR (environmental context should be implicitly in that)
output=first line where logs differ from input (broken logs)
(automatically generated on this training data, no manual annotation needed)
Algorithm: some LSTM

[2] ML project to automatically fix easy issues:
training data = submitted PR's with a small diff (eg <= 3 lines changed)
input=brew gist-logs before PR (environmental context should be implicitly in that)
desired output=git diff for this PR
(automatically generated on this training data, no manual annotation needed)

NOTE: would be particularly relevant for linuxbrew where a lot of the bugs (works in OSX, broken in linuxbrew) tend to be simple small fixes

**Comment by MikeMcQuaid** [comment]
There is no plan for this. This could be useful but its something that would require a lot of work and I'm not sure it would pay off in the medium term, sorry.
