### ISSUE TITLE
Cannot install homebrew

### ISSUE THREAD

**Issue by hepcat72** [Homebrew/brew#1837]
I don't have homebrew installed on this mac yet and when I went to install it (both ways), I got the following errors:

```
bash-3.2$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
curl: (22) The requested URL returned error: 503 first byte timeout
bash-3.2$ exit
exit
```

```
cd /usr/local
mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   128    0   128    0     0    419      0 --:--:-- --:--:-- --:--:--   421
100    27    0    27    0     0      0      0 --:--:--  0:00:31 --:--:--     7
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

Is there a problem with homebrew's installation process or am I doing something wrong?

**Comment by MikeMcQuaid** [comment]
Can you try again? What does `which tar` output?

**Comment by userlerueda** [comment]
@hepcat72 which version of macOS are you using? I just installed today on a clean install of 10.12.2 and it worked fine.

**Comment by hepcat72** [comment]
which tar
/usr/bin/tar

MacOS 10.12.1

I tried it again this morning and it worked. Did you change anything Mike?

**Comment by MikeMcQuaid** [comment]
No, glad it's working, could have been a GitHub availability issue.
