### ISSUE TITLE
NOT support for macOS 15

### ISSUE THREAD

**Issue by code-innovator-zyx** [Homebrew/brew#18385]
### `brew doctor` output

```shell
Warning: You are using macOS 15.
We do not provide support for this pre-release version.
It is expected behaviour that some formulae will fail to build in this pre-release version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

Error: unknown or unsupported macOS version: :dunno
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.14
ORIGIN: https://mirrors.aliyun.com/homebrew/brew.git
HEAD: f6a4f42cc346694fac94fa1643bc2809d383b6f1
Last commit: 6 months ago
Core tap JSON: 24 Sep 06:05 UTC
Core cask tap JSON: 24 Sep 06:05 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
http_proxy: http://127.0.0.1:7890
https_proxy: http://127.0.0.1:7890
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

brew install graphviz

### What happened (include all command output)?

Warning: You are using macOS 15.
We do not provide support for this pre-release version.
It is expected behaviour that some formulae will fail to build in this pre-release version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

### What did you expect to happen?

success install 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install graphviz
```

**Comment by carlocab** [comment]
Your Homebrew version is old:
```
HOMEBREW_VERSION: 4.2.14
```
Your mirror is probably outdated. Please file an issue with them.

**Comment by gavinanderegg** [comment]
I'm also having this issue, and my ORIGIN is set to https://github.com/Homebrew/brew. I would not suggest that anyone update their ORIGIN to the one provided above.

**Comment by code-innovator-zyx** [comment]
> I'm had this issue, and my ORIGIN is set to https://github.com/Homebrew/brew. I was able to resolve it by running `brew update` a second time.

It's been resolved. Thank you.

**Comment by qixiaobo** [comment]
Some problem here!
```
brew install pipx
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-services, skipping update!
Running `brew update --auto-update`...
Installing from the API is now the default behaviour!
You can save space and time by running:
  brew untap homebrew/core
  brew untap homebrew/cask
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> New Casks
backyard-ai                     bentobox                        font-host-grotesk               legcord                         magicquit

Warning: You are using macOS 15.
We do not provide support for this pre-release version.
It is expected behaviour that some formulae will fail to build in this pre-release version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

Error: unknown or unsupported macOS version: :dunno
```

**Comment by qixiaobo** [comment]
> Some problem here!
> 
> ```
> brew install pipx
> Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-services, skipping update!
> Running `brew update --auto-update`...
> Installing from the API is now the default behaviour!
> You can save space and time by running:
>   brew untap homebrew/core
>   brew untap homebrew/cask
> ==> Auto-updated Homebrew!
> Updated 1 tap (homebrew/cask).
> ==> New Casks
> backyard-ai                     bentobox                        font-host-grotesk               legcord                         magicquit
> 
> Warning: You are using macOS 15.
> We do not provide support for this pre-release version.
> It is expected behaviour that some formulae will fail to build in this pre-release version.
> It is expected behaviour that Homebrew will be buggy and slow.
> Do not create any issues about this on Homebrew's GitHub repositories.
> Do not create any issues even if you think this message is unrelated.
> Any opened issues will be immediately closed without response.
> Do not ask for help from Homebrew or its maintainers on social media.
> You may ask for help in Homebrew's discussions but are unlikely to receive a response.
> Try to figure out the problem yourself and submit a fix as a pull request.
> We will review it but may or may not accept it.
> 
> Error: unknown or unsupported macOS version: :dunno
> ```

Just reinstall homebrew to avoid this

**Comment by runaydhaygude** [comment]
In my case, re-installing homebrew worked!

**Comment by MaDycloud-MD** [comment]
> In my case, re-installing homebrew worked!

Yes, it works!

**Comment by denisdefreyne** [comment]
FYI: I ran into this problem and `brew update-reset` resolved it for me.

**Comment by aspatzier** [comment]
> FYI: I ran into this problem and `brew update-reset` resolved it for me.

Thanks for this post. It solved the problem for me too.

I just ran into this problem 2 days ago, though the finale release of macOS 15 was in fall last year. Probably the bug somehow still exists.
