### ISSUE TITLE
Piping password to brew no longer working

### ISSUE THREAD

**Issue by tiiiecherle** [Homebrew/brew#18383]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  brackets
  liteicon
  profilecreator
  ui-browser
  vlc-webplugin
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 4.3.24-5-gbd3c7f8
ORIGIN: https://github.com/Homebrew/brew
HEAD: bd3c7f80530d21e791ccc01b02234b299941dd29
Last commit: 12 hours ago
Core tap JSON: 23 Sep 19:44 UTC
Core cask tap HEAD: 4bf04196d839f5ab7dee8b32df540b914ad29ff6
Core cask tap last commit: 7 hours ago
Core cask tap JSON: 23 Sep 19:44 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.46.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I am piping the password for brew batch installations or brew batch updates in s script for years.
Unfortunately brew is not taking the piped password anymore. I checked that the password is still in the variable and works with other commands at the same point of the script.

Thanks for looking into it.

### What happened (include all command output)?

```
SUDOPASSWORD="MY_PASSWORD"
builtin printf "$SUDOPASSWORD\n" | brew install --cask --force microsoft-teams
==> Upgrading 1 outdated package:
microsoft-teams 24231.507.3099.9636 -> 24231.507.3099.9636
==> Upgrading microsoft-teams
==> Downloading https://statics.teams.cdn.office.net/production-osx/24231.507.30
Already downloaded: /Users/tom/Library/Caches/Homebrew/downloads/bb85ce4d5b635b07c80fbf841354e2fc21c08cf40262d0a5fd66381d22223b06--MicrosoftTeams.pkg
All dependencies satisfied.
==> Removing launchctl service com.microsoft.teams.TeamsUpdaterDaemon
Password:
```

### What did you expect to happen?

Running the installer without asking for the password again.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
SUDOPASSWORD="MY_PASSWORD"
builtin printf "$SUDOPASSWORD\n" | brew install --cask --force microsoft-teams
```

**Comment by Bo98** [comment]
Do you know roughly when it last worked?

**Comment by MikeMcQuaid** [comment]
`SUDO_ASKPASS` is probably a better fit here. If this was working before: it's been accidental rather than documented.

**Comment by reitermarkus** [comment]
I don't think this ever worked given `sudo` doesn't get the password from `/dev/stdin`.

You should use a `SUDO_ASKPASS` script instead.

**Comment by reitermarkus** [comment]
Ah, there is the `-S` switch which does read it from `stdin`, did we use that before?

**Comment by tiiiecherle** [comment]
> Do you know roughly when it last worked?

It started a few weeks (perhaps months) ago, sorry I don't know exactly when.

**Comment by tiiiecherle** [comment]
I had a look at `SUDO_ASKPASS` and if I get it correctly it is another way to store the password.

But as stated above storing the password is not the problem, brew not using the piped password is.

And the way I do it worked for years until a few weeks, probably months ago.

**Comment by reitermarkus** [comment]
> But as stated above storing the password is not the problem, brew not using the piped password is.

You don't need to pipe anything to `brew` if you set `SUDO_ASKPASS`.

You just need a script which echoes your password and `SUDO_ASKPASS` needs to point to it, e.g.

```
echo '#!/usr/bin/env bash' >> my_super_secure_password_script.sh
echo 'echo password123' >> my_super_secure_password_script.sh
chmod +x my_super_secure_password_script.sh

export SUDO_ASKPASS="$(pwd)/my_super_secure_password_script.sh"

brew install something-that-needs-sudo
```

Here's how I do it by temporarily storing it in Keychain: https://github.com/reitermarkus/dotfiles/blob/f507934aafaf974ef74e8460f1718c6df468632a/.sh#L99-L125


> And the way I do it worked for years until a few weeks, probably months ago.

No idea what changed, `brew` never used the `-S` flag as far as I know, so also no idea how it worked before in the first place.

**Comment by gromgit** [comment]
Given the symptoms, I'm almost certain that:
* it's a result of https://github.com/Homebrew/brew/pull/17694 (which was implemented for security reasons), and
* @tiiiecherle's "it worked before" was because `sudo` was using cached credentials when invoked by `brew`, i.e. piping passwords to `sudo` _never_ actually worked (unless you used `-S`).

**Comment by MikeMcQuaid** [comment]
I agree, thanks @gromgit. Closing, sorry.
