### ISSUE TITLE
postgresql@16 service can only be started by sudo

### ISSUE THREAD

**Issue by dxunix** [Homebrew/brew#18392]
### `brew doctor` output

```shell
~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
% brew config
HOMEBREW_VERSION: 4.3.24-9-g73e521e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 73e521ec59004d0c9c262254c3313e0ec0c3a615
Last commit: 3 hours ago
Core tap JSON: 24 Sep 10:49 UTC
Core cask tap JSON: 24 Sep 10:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.46.2 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

after installed postgresql@16, try to start the service normally
`brew service start postgresql@16`

### What happened (include all command output)?

% brew services start postgresql@16 -vd
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading postgresql@16
==> /bin/launchctl print gui/501/homebrew.mxcl.postgresql@16

==> Generated service file for postgresql@16:
   <?xml version="1.0" encoding="UTF-8"?>
   <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
   <plist version="1.0">
   <dict>
   	<key>EnvironmentVariables</key>
   	<dict>
   		<key>LC_ALL</key>
   		<string>C</string>
   	</dict>
   	<key>KeepAlive</key>
   	<true/>
   	<key>Label</key>
   	<string>homebrew.mxcl.postgresql@16</string>
   	<key>LimitLoadToSessionType</key>
   	<array>
   		<string>Aqua</string>
   		<string>Background</string>
   		<string>LoginWindow</string>
   		<string>StandardIO</string>
   		<string>System</string>
   	</array>
   	<key>ProgramArguments</key>
   	<array>
   		<string>/opt/homebrew/opt/postgresql@16/bin/postgres</string>
   		<string>-D</string>
   		<string>/opt/homebrew/var/postgresql@16</string>
   	</array>
   	<key>RunAtLoad</key>
   	<true/>
   	<key>StandardErrorPath</key>
   	<string>/opt/homebrew/var/log/postgresql@16.log</string>
   	<key>StandardOutPath</key>
   	<string>/opt/homebrew/var/log/postgresql@16.log</string>
   	<key>WorkingDirectory</key>
   	<string>/opt/homebrew</string>
   </dict>
   </plist>

/bin/launchctl enable gui/501/homebrew.mxcl.postgresql@16
Could not enable service: 125: Domain does not support specified action
Error: Failure while executing; `/bin/launchctl enable gui/501/homebrew.mxcl.postgresql@16` exited with 125.
/opt/homebrew/Library/Homebrew/extend/kernel.rb:273:in `safe_system'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:269:in `launchctl_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:287:in `service_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:123:in `block in start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:98:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:98:in `start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/start.rb:11:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:147:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
% cat /opt/homebrew/var/log/postgresql@16.log
cat: /opt/homebrew/var/log/postgresql@16.log: No such file or directory

### What did you expect to happen?

is should not need sudo as the postgresql db should not run under privileged user.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install  postgresql@16
brew services start postgresql@16 -vd
```

**Comment by MikeMcQuaid** [comment]
Are you logged in as that current user on the machine or using e.g. SSH etc.?

**Comment by dxunix** [comment]
> Are you logged in as that current user on the machine or using e.g. SSH etc.?

No, logged in locally. but was `su -` to the admin user which has sudo permission.  But this is good now I tried to switched user to the administrator and ran it in the terminal and it worked.  So the plist was created under ~/Library/LaunchAgents/ of the admin user.   I wonder why the shell using su - didnt work.  Maybe it has to do with how the scripts were written??  

But thank you!

**Comment by MikeMcQuaid** [comment]
This is an issue with macOS unfortunately rather than `brew services`; it's quite picky about how it lets you start services.

**Comment by dxunix** [comment]
I see, thank you!!! I see if I close the login session from my admin user the service is also stopped, while I want it to run in the background.
