### ISSUE TITLE
Error: No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by aidinzolghadr** [Homebrew/brew#1841]
(Please note that I'm using linuxbrew on a shared debian host)

When I want to do anything with brew, it says:

`Error: No such file or directory @ rb_sysopen - /$HOME/tmp/homebrew_check_tmpdir_executable20170113-19308-1ohnvsg`

output of 'brew config':

HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: db9437412ba668fbcf8da8b8279427d9440e896b
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 42231dc665facb1b364d5028ec1364465ed390f1
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: //HOME/.linuxbrew
HOMEBREW_REPOSITORY: //HOME/.linuxbrew
HOMEBREW_CELLAR: //HOME/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit penryn
Homebrew Ruby: 2.1.5 => /usr/bin/ruby2.1
Clang: N/A
Git: 2.1.4 => /usr/bin/git
Perl: /usr/local/bin/perl => /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.1
Java: N/A
Kernel: Linux 3.14.0-ui16294-uiabi1-infong-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 8.6 (jessie)
Codename: jessie
OS glibc: 2.19
OS gcc: 4.9.2
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A

output of brew doctor:

`Error: No such file or directory @ rb_sysopen - /HOME/tmp/homebrew_check_tmpdir_executable20170113-26539-c6ng1x`

**Comment by MikeMcQuaid** [comment]
> (Please note that I'm using linuxbrew on a shared debian host)

Please report this to Linuxbrew, not Homebrew.

**Comment by CholtonATX** [comment]
I am getting the same type of error for saml2aws:

`Error: Permission denied @ rb_sysopen - /tmp/github_api_headers20180307-1093-j3cfhq`

Here's my config:

```
HOMEBREW_VERSION: 1.5.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 08f7e8c5887d1c654a1a5d5bc851a9c9d5a00371
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a1e4c2440b5abdde12ed774e146afa7d170f22fb
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_RUBY_WARNINGS: -W0
HOMEBREW_TEMP: /tmp
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/cholton/Library/Enthought/Canopy/edm/envs/User/bin/python => /Users/cholton/Library/Enthought/Canopy/edm/envs/User/bin/python3.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_101
macOS: 10.13.3-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

The preceding instructions were to run these commands to install the saml2aws package:

```
brew tap versent/homebrew-taps
brew install saml2aws
```

**Comment by MikeMcQuaid** [comment]
@CholtonATX What's your `brew doctor` output?
