### ISSUE TITLE
use github notification API's to auto-generate bump-formula-pr

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#1842]
homebrew already automates certain things (bottling, continuous integration).

What about using notification API's to track project releases and automatically generate bump-formula-pr?

* users could subscribe to such candidate PR's
* the PR would only be sent for review when it passes https://github.com/BrewTestBot
* there would be a per-formula setting to manage this, eg:

-default: nothing is auto-generated
-auto_propose: sends PR's that pass BrewTestBot for review
-auto_submit: submit PR's that pass BrewTestBot for review

This could be specified independently for stable, devel, and the trigger could be configured with sensible defaults (eg: upon major or minor version bumps)

Eg of notification API's: http://stackoverflow.com/questions/20839622/notifications-for-new-github-project-releases/20840694#20840694
There's also  Sibbell.com etc.

**Comment by MikeMcQuaid** [comment]
> What about using notification API's to track project releases and automatically generate bump-formula-pr?

@ilovezfs does similar with https://github.com/youtux/homebrew-livecheck. I agree it would be nice to automate that.
