### ISSUE TITLE
`brew list --installed-on-request -tr` Can't sort by time

### ISSUE THREAD

**Issue by alkene0005** [Homebrew/brew#18421]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.24
ORIGIN: https://github.com/Homebrew/brew
HEAD: 916044581862c32fc2365e8e9ff0b1507a98925e
Last commit: 4 days ago
Core tap JSON: 26 Sep 09:05 UTC
Core cask tap JSON: 26 Sep 11:26 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

run: `brew list --installed-on-request -tr`

### What happened (include all command output)?

It's not chronological, it's still alphabetical
![image](https://github.com/user-attachments/assets/cf93150a-29b5-4401-98ca-8da0b0a44b20)

### What did you expect to happen?

Sort by time

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew list --installed-on-request -tr`
```

**Comment by carlocab** [comment]
Yes, the short flags `-l`, `-r`, and `-t` only properly with each other and with `--formulae` or `--casks` (and no named args).

It would be nice to fix this. If not, then it should at least be documented.

**Comment by MikeMcQuaid** [comment]
> It would be nice to fix this. If not, then it should at least be documented.

The fix here would be marking these options as conflicting.
