### ISSUE TITLE
brew command outputs truncated to terminal width and brew test has no logs

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#1843]
is there a way to stop brew command output from being truncated to terminal width (instead just naturally let the terminal wrap)? 
* increasing terminal width after command is run won't show more because of the hard-truncation
* brew test (eg `brew test mongo-c-driver` ) don't even show any logs so we can't use these to get more info.

NOTE: a workaround seems to be to use (eg) `brew test my_formula > /tmp/log.txt` but that's inconvenient

**Comment by GauthamGoli** [comment]
I am getting the following output for `brew test mongo-c-driver` 


` ==> Using the sandbox
==> /usr/bin/clang -o test /usr/local/Cellar/mongo-c-driver/1.5.3/share/mongo-c-driver/libbson/examples/json-to-bson.c -I/usr/local/Cellar/mongo-c-driver/1.5.3/include/libbson-1.0 -
==> ./test test.json
==> /usr/bin/clang -o test /usr/local/Cellar/mongo-c-driver/1.5.3/share/mongo-c-driver/mongoc/examples/mongoc-ping.c -I/usr/local/Cellar/mongo-c-driver/1.5.3/include/libmongoc-1.0 -
==> ./test mongodb://0.0.0.0 2>&1`

**Comment by timotheecour** [comment]
Exactly, this proves my point:
in a terminal with short width:
```
$ brew test mongo-c-driver
Testing mongo-c-driver
==> Using the sandbox
==> /usr/bin/clang -o test /Users/timothee/homebrew/Cellar/mongo-c-driver/1.5.3/sh
==> ./test test.json
==> /usr/bin/clang -o test /Users/timothee/homebrew/Cellar/mongo-c-driver/1.5.3/sh
```

* as you can see the output is truncated to terminal width; once it's written, increasing terminal width doesn't show the hidden truncated part.
* In addition, no logs are shown so when a test fails, you have zero context. By logs I mean the logs saved under `/home/timothee/.cache/Homebrew/Logs/` that are referred to when `brew install` fails with a message eg `Last 15 lines from /home/timothee/.cache/Homebrew/Logs/opencv3/02.make`, not the truncated output that's written to stdout that you see above.

EG: until this PR https://github.com/Homebrew/homebrew-core/pull/8928 is merged on linuxbrew you get:

```
==> /usr/bin/clang -o test /usr/local/Cellar/mongo-c-driver/1.5.3/share/mongo-c-driver/mongoc/examples/mongoc-ping.c -I/usr/local/Cellar/mongo-c-driver/1.5.3/include/libmongoc-1.0 -I/usr/local/Cellar/mongo-c-driver/1.5.3/include/libbson-1.0 -L/usr/local/Cellar/mongo-c-driver/1.5.3/lib -lmongoc-1.0 -lbson-1.0
==> ./test mongodb://0.0.0.0 2>&1
Error: mongo-c-driver: failed
<0> expected but was
<3>.
```

As you can see, not logs, and the output is truncated. If the test takes a while before crashing, you have to either increase your terminal window and rerun (ie takes long) or (best), run the test with a unix pipe.

**Comment by MikeMcQuaid** [comment]
> increasing terminal width after command is run won't show more because of the hard-truncation

This is intentional.

> brew test (eg brew test mongo-c-driver ) don't even show any logs so we can't use these to get more info.

`brew test -v` prints the output.

**Comment by cybertk** [comment]
> as you can see the output is truncated to terminal width; once it's written, increasing terminal width doesn't show the hidden truncated part.

`brew install` also behaves in this way.
