### ISSUE TITLE
`brew tap-info --json=v1` json parsing broken with repo -> repository change

### ISSUE THREAD

**Issue by gibfahn** [Homebrew/brew#18444]
### `brew doctor` output

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### Verification

- [ ] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.3.24-431c884ce1
ORIGIN: https://github.com/Homebrew/brew
HEAD: fe4392dad5b7507f4999328012c087c5cdd3124c
Last commit: 37 minutes ago
Core tap HEAD: 58e0e60a03048568cb4cf1bcdc800df83199ef03
Core tap last commit: 4 minutes ago
Core cask tap HEAD: b61d806459642b5d6f887995187e255493005269
Core cask tap last commit: 58 minutes ago
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: TwoDark
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.46.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
```

### What were you trying to do (and why)?

We have automation that parses `brew tap-info --json=v1 my/tap`. This automation started failing because of the `repo` -> `repository` change, I believe caused by https://github.com/Homebrew/brew/pull/18388 . 

In this case the automation is pretty easy to fix, but I had assumed the existence of `--json=v1` meant that the version would be bumped in case of any breaking changes.

I wanted to ask what our expectations should be here, as this hasn't yet shipped to stable brew.

### What happened (include all command output)?

(this is a simplified example, we were doing more things with the JSON output)

```
❯ brew tap-info --json=v1 my/tap | jq '.[0].repo'
null
```

### What did you expect to happen?

```
❯ brew tap-info --json=v1 my/tap | jq '.[0].repo'
tap
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install jq
brew tap-info --json=v1 homebrew/core | jq '.[0].repo'
```

**Comment by MikeMcQuaid** [comment]
Whoops, yes, this was unintentional and will be fixed before we release 4.4.0 next week.
