### ISSUE TITLE
uses: recursive requirements doesn't respect --include-optional

### ISSUE THREAD

**Issue by alyssais** [Homebrew/brew#1848]
### Bug reports:

I'm fairly sure this is a bug, and I'm also fairly sure I have a pretty straightforward fix (that happily also fixes the errors introduced by #1784 that required it being reverted in #1797), but I want to make sure this isn't intended behaviour first, so **I'm looking for a 👍 from a maintainer to confirm this is a bug before I jump in with a fix.**

#### Steps to reproduce

```ruby
class Dlib < Formula
  # …
  depends_on "openblas" => :optional
  # …
end
```

```ruby
class Openblas < Formula
  # …
  depends_on :fortran
  # …
end
```

```sh
brew tap homebrew/science
brew uses --recursive --include-optional gcc # :fortran's default formula
```

#### Expected Behaviour

<kbd>brew uses</kbd>'s output contains <samp>homebrew/science/dlib</samp>.

#### Actual Behaviour

<kbd>brew uses</kbd>'s output does not contain <samp>homebrew/science/dlib</samp>.

#### Debug Information

<details>
<summary><kbd>brew doctor</kbd></summary>
<pre><samp>Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/freetype-config
  /usr/local/bin/gdal-config
  /usr/local/bin/gdlib-config
  /usr/local/bin/geos-config
  /usr/local/bin/gpg-error-config
  /usr/local/bin/jemalloc-config
  /usr/local/bin/ksba-config
  /usr/local/bin/libassuan-config
  /usr/local/bin/libgcrypt-config
  /usr/local/bin/libpng-config
  /usr/local/bin/libpng16-config
  /usr/local/bin/libusb-config
  /usr/local/bin/Magick++-config
  /usr/local/bin/Magick-config
  /usr/local/bin/MagickCore-config
  /usr/local/bin/MagickWand-config
  /usr/local/bin/onig-config
  /usr/local/bin/pcre-config
  /usr/local/bin/pkg-config
  /usr/local/bin/pth-config
  /usr/local/bin/python-config
  /usr/local/bin/python2-config
  /usr/local/bin/python2.7-config
  /usr/local/bin/python3-config
  /usr/local/bin/python3.6-config
  /usr/local/bin/python3.6m-config
  /usr/local/bin/sdl2-config
  /usr/local/bin/Wand-config

Warning: Suspicious git origin remote found.

With a non-standard origin, Homebrew won't pull updates from
the main repository. The current git origin is:
  git@github.com:alyssais/brew

Unless you have compelling reasons, consider setting the
origin remote to point at the main repository, located at:
  https://github.com/Homebrew/brew.git

Warning: You have uncommitted modifications to Homebrew
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /Users/alyssa/code/brew/Library && git stash && git clean -d -f

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

Warning: /usr/bin occurs before /Users/alyssa/code/brew/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:
  phar
  phar.phar
  php
  php-config
  phpize

Consider setting your PATH so that /Users/alyssa/code/brew/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/Users/alyssa/code/brew/bin:$PATH"' >> ~/.zshrc

Warning: Homebrew's bin was not found in your PATH.
Consider setting the PATH for example like so
  echo 'export PATH="/Users/alyssa/code/brew/bin:$PATH"' >> ~/.zshrc

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /Users/alyssa/code/brew/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/Users/alyssa/code/brew/sbin:$PATH"' >> ~/.zshrc

Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /usr/local/bin/pkg-config

`./configure` may have problems finding brew-installed packages using
this other pkg-config.
</samp></pre>
</details>

<details>
<summary><kbd>brew config</summary>
<pre><samp>HOMEBREW_VERSION: 1.1.7-19-g98281a2de-dirty
ORIGIN: git@github.com:alyssais/brew
HEAD: 98281a2de2b6fe5f7559b449907f0a18c664e815
Last commit: 42 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b30c9506be17b9c0f6dcdc0748990b70bb7bca9e
Core tap last commit: 8 days ago
HOMEBREW_PREFIX: /Users/alyssa/code/brew
HOMEBREW_REPOSITORY: /Users/alyssa/code/brew
HOMEBREW_CELLAR: /Users/alyssa/code/brew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/alyssa/.rubies/ruby-2.4.0/bin/ruby
Java: 1.8.0_112
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
</samp></pre>
</details>

**Comment by alyssais** [comment]
Note that `homebrew/science/openblas` is included in the <kbd>brew uses</kbd> output, and I'm fairly sure if `dlib` required `openblas` then `dlib` would also be in the output. The problem is specifically with a formula not showing up when an optional dependency has a requirement that resolves to the formula passed to <kbd>brew uses</kbd>.

**Comment by MikeMcQuaid** [comment]
Yes, this seems to be a bug 👍
