### ISSUE TITLE
Installation failed.  The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

### ISSUE THREAD

**Issue by mmwwxz** [Homebrew/brew#18498]
### `brew doctor` output

```shell
Installation failed.

The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
Installation failed.

The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
```

### What were you trying to do (and why)?

Installation failed.

The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

### What happened (include all command output)?

Installation failed.

The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

### What did you expect to happen?

Installation failed.

The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Installation failed.

The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
```

**Comment by mmwwxz** [comment]
mac os sequoia

**Comment by Babbz86** [comment]
Will sponsor just need talk to someone first

**Comment by Bo98** [comment]
We'll need the relevant parts from `/var/log/install.log` in order to figure anything out here. The installer works fine for us so further information is required.
