### ISSUE TITLE
sudo pip install error 

### ISSUE THREAD

**Issue by kaguilarcamacho** [Homebrew/brew#185]
```
The directory '/Users/kaguilarcamacho/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/kaguilarcamacho/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting jirabot
  Could not find a version that satisfies the requirement jirabot (from versions: )
No matching distribution found for jirabot
```

any idea how to fix this?

**Comment by UniqMartin** [comment]
How is that a Homebrew issue?

> any idea how to fix this?

Have you tried following the advice given in the error message (“If executing `pip` with `sudo`, you may want `sudo`'s `-H` flag.”)?

**Comment by kaguilarcamacho** [comment]
Thanks for looking into this @UniqMartin . 

Got :   Could not find a version that satisfies the requirement jirabot (from versions: )
No matching distribution found for jirabot :/

**Comment by UniqMartin** [comment]
Sorry @kaguilarcamacho, but this really doesn't look like a Homebrew issue. I'm not sure what the best resource is to find help with that, but we can't help you with using `pip` or issues related to that.
