### ISSUE TITLE
Way to disable casks

### ISSUE THREAD

**Issue by quackerex** [Homebrew/brew#18504]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

A way to disable casks. This will disable the ability to install casks and any of the brew commands won't show any references to casks.

### What is the motivation for the feature?

I prefer to only use brew install formulae. It would be nice to have a way to disable casks entirely. 
So brew won't fetch or install any casks. 
Currently these commands show something related to casks even if you only intend to use it for formulae related stuff:

`brew upgrade`
`brew search`

Related discussion: https://github.com/orgs/Homebrew/discussions/5597#discussion-7166410

### How will the feature be relevant to at least 90% of Homebrew users?

Most people don't make use of casks much and only use brew for formulae(similar to package manager).

### What alternatives to the feature have been considered?

Just ignoring casks related information.

**Comment by stephbowie** [comment]
[celebrate]     Stephanie Bowie reacted to your message:
________________________________
From: quackerex ***@***.***>
Sent: Friday, October 4, 2024 11:04:09 AM
To: Homebrew/brew ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Homebrew/brew] Way to disable casks (Issue #18504)


Verification

  *    This issue's title and/or description do not reference a single formula e.g. brew install wget. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

Provide a detailed description of the proposed feature

A way to disable casks. This will disable the ability to install casks and any of the brew commands won't show any references to casks.

What is the motivation for the feature?

I prefer to only use brew install formulae. It would be nice to have a way to disable casks entirely.
So brew won't fetch or install any casks.
Currently these commands show something related to casks even if you only intend to use it for formulae related stuff:

brew upgrade
brew search

Related discussion: https://github.com/orgs/Homebrew/discussions/5597#discussion-7166410

How will the feature be relevant to at least 90% of Homebrew users?

Most people don't make use of casks much and only use brew for formulae(similar to package manager).

What alternatives to the feature have been considered?

Just ignoring casks related information.

**Comment by MikeMcQuaid** [comment]
> A way to disable casks.

This may be possible one day.



> This will disable the ability to install casks and any of the brew commands won't show any references to casks.

This never will be and seems to be the main ask. Sorry, passing on this.

**Comment by MikeMcQuaid** [comment]
Do you mean `brew update` fetches the cask API JSON file?



> Where you have to explicitly tell to install casks (with --cask flag)

This is not the case. `brew install google-chrome` doesn't require this flag, not `brew search google-chrome`.
