### ISSUE TITLE
update httpd24,not work

### ISSUE THREAD

**Issue by y284663247** [Homebrew/brew#1852]
> sudo apachectl restart
Password:
dyld: Symbol not found: _apr_crypto_block_cleanup
  Referenced from: /usr/local/Cellar/httpd24/2.4.25/bin/httpd
  Expected in: /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib
 in /usr/local/Cellar/httpd24/2.4.25/bin/httpd
/usr/local/bin/apachectl: line 79:  3127 Abort trap: 6           $HTTPD -k $ARGV

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE.md
