### ISSUE TITLE
Toggle for app to not launching after upgrade

### ISSUE THREAD

**Issue by kzssc** [Homebrew/brew#18530]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

An option to choose to *not* launch an app after upgrade (e.g. NordVPN / windscribe)

### What is the motivation for the feature?

App can launch after upgrading even when this is not wanted. One simply wants the upgraded app on the system. 

### How will the feature be relevant to at least 90% of Homebrew users?

less disruption to the frontend

### What alternatives to the feature have been considered?

not upgrading said app...

**Comment by Bo98** [comment]
We don't intentionally launch apps. I checked NordVPN and the installer pkg upstream provide does that itself. If you download it from the website and run it yourself, you get the same behaviour.

Unfortunately, NordVPN does not provide a way to override this behaviour.
