### ISSUE TITLE
Error: Formulae found in multiple taps with `brew install fully-qualified-name`

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#1855]
```
brew tap Linuxbrew/science
brew install linuxbrew/science/opencv3
==> Installing opencv3 from linuxbrew/science
Error: Formulae found in multiple taps:
 * linuxbrew/science/openni
 * homebrew/science/openni

Please use the fully-qualified name e.g. linuxbrew/science/openni to refer the formula.
```

* This makes no sense since I specified the fully-qualified name.

* Furthermore, could we use a different name in the example? because `brew install linuxbrew/science/openni` leads to a hard-to-install formula:
```
==> Installing openni from linuxbrew/science
intltool: Unsatisfied dependency: XML::Parser
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i XML::Parser`
systemd: Unsatisfied dependency: XML::Parser
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i XML::Parser`
Error: Unsatisfied requirements failed this build.
```

NOTE: this seems like a blocker for installing anything from linuxbrew/science

NOTE: moved from https://github.com/Linuxbrew/homebrew-core/issues/1586

**Comment by apjanke** [comment]
It looks like that error message isn't referring to the fully-qualified `linuxbrew/science/opencv3` you specified, but the unqualified `depends_on "openni" => :optional` declared inside the `opencv3` formula. That's why `openni` appears in the message; it's not just an example formula.
