### ISSUE TITLE
docs.brew.sh should show documentation for current stable version, but currenlty docs are linked to master branch

### ISSUE THREAD

**Issue by jbojar** [Homebrew/brew#18579]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

docs.brew.sh should show the documentation for last stable version (today it is 4.4.1).

Currently docs are linked to master branch in the repo.

The effect is that, for example, the documentation for command completion https://docs.brew.sh/Shell-Completion shows instructions which will be valid after changes introduced to `brew shellenv` command in commit f7b8681bc95db17bea12ff7d12c179d57b890246 will be released (probably in future version 4.4.2). But currently they are available only in `master`.
Documentation was updated to early in commits aea87757ff9aa6b304eaa7eef8916d3e85bd5c9e and 94426ba18b8ecaacaa3ae308b7578c9832401431.

If the documentation was linked to the last stable tag `4.4.1`, it would be valid for current publicly available version.

### What is the motivation for the feature?

The documentation should be valid for current stable version.
If changes in documentation are published earlier than actual changes to the codebase, some features may work differently than it is described in the docs. This can lead to user's frustration.

### How will the feature be relevant to at least 90% of Homebrew users?

Not sure what percentage of users ever read the documantation.

### What alternatives to the feature have been considered?

You could also consider enabling users to view docs for specified version (eg. several versions could be choosable in combobox, something like https://docs.python.org/3/)

**Comment by MikeMcQuaid** [comment]
I don't think GitHub Pages really makes this possible for us.

**Comment by jbojar** [comment]
There is a possibility to select a branch from which pages are published: 
<img width="739" alt="image" src="https://github.com/user-attachments/assets/b6ece157-539f-403b-9e94-f6fa914e7821">

Unfortunately you cannot select a tag there.
But maybe there could be a special branch created for docs publishing. During the release process of new version it would be updated to the repo state of released version?

**Comment by Bo98** [comment]
We probaly won't go the branch route. We maybe could do something with GitHub Actions based deploys. It's much more customisable and can be trigger on releases etc.

**Comment by MikeMcQuaid** [comment]
Even that I'm not sure makes sense. I agree for some of the cases of functionality/APIs that don't apply to stable tags yet but I wouldn't want e.g. all the contributor/maintainer centric documentation not get updated.

Passing on this for now but will reconsider in future. Sorry @jbojar and thanks for the issue.
