### ISSUE TITLE
brew reports minimum supported version of Xcode, not actual version

### ISSUE THREAD

**Issue by samdmarshall** [Homebrew/brew#1858]
When running `brew doctor` or `brew config` I see the following:

```
Warning: Your Xcode (8.0) is outdated.
Please update to Xcode 8.2 (or delete it).
Xcode can be updated from the App Store.
```

```
...
Xcode: 8.0 => /Users/Samantha/Desktop/faux-code.app/Contents/Developer
...
```

This can be demonstrated by taking any system with 10.12.x without Xcode.app installed (but with CLT), and make a copy of any application, and change the bundle identifier to be `com.apple.dt.Xcode` so it gets picked up as "Xcode".  In this circumstance brew will not read the actual version number of the bundle and assumes that it must be 8.0 (minimum version supported on 10.12). 

(I was going to submit a PR with a fix for this but the complexity of the related code seems a bit too complicated for my ability with ruby, it seems related to the defaults in the code in `Library/Homebrew/os/mac/xcode.rb` and `Library/Homebrew/extend/os/mac/diagnostic.rb`)

**Comment by MikeMcQuaid** [comment]
I'm not sure I understand the issue. Why is the bundle identifier matching Xcode if it's not Xcode?

**Comment by samdmarshall** [comment]
That is done to demonstrate the problem, that the reported version from brew isn't actually representative of the version of Xcode found.

**Comment by MikeMcQuaid** [comment]
What version of Xcode is it? Thanks!

**Comment by samdmarshall** [comment]
I don't understand your question, my problem is that brew is telling me it found Xcode but is not reporting the version number from the info.plist at the path it found. I don't see how that relates to what the actual number is found in this specific install on my machine?

**Comment by MikeMcQuaid** [comment]
> I don't see how that relates to what the actual number is found in this specific install on my machine?

I'm trying to understand what the actual bug is that doesn't involve incorrectly setting bundle identifiers. If there's a version of Xcode installed in a weird location: what version is it?

**Comment by samdmarshall** [comment]
Let me try to explain this again, because it seems like I did poorly the first time:

1. The behavior I am observing from `brew` is that reports that it has detected an installation of Xcode when there is an application bundle with the identifier of `com.apple.dt.Xcode` that is able to be found.
    - (expected behavior)
2. `brew` reports that the version found is not the most recent version, and that I should update it.
    - (expected behavior)
3. Based on the code, it doesn't seem that `brew` is actually querying the version number from the Info.plist of the bundle that has the identifier of `com.apple.dt.Xcode`. It instead, assumes that it is the minimum supported version of the OS version you are running.
    - (unexpected behavior)

So, as a result, `brew` is showing me the the number `8.0` as part of the reports i posted in this issue originally. The problem isn't with the specific version number I have, but with `brew` giving me misleading/incorrect information about that number.

**Comment by MikeMcQuaid** [comment]
> Based on the code, it doesn't seem that brew is actually querying the version number from the Info.plist of the bundle that has the identifier of com.apple.dt.Xcode. It instead, assumes that it is the minimum supported version of the OS version you are running.
> (unexpected behavior)
> So, as a result, brew is showing me the the number 8.0 as part of the reports i posted in this issue originally. The problem isn't with the specific version number I have, but with brew giving me misleading/incorrect information about that number.

Ok, I think I understand. We don't query the `Info.plist` but instead use either the `xcodebuild` in the Xcode.app or on the system if it's not found. That's why I'm asking about the Xcode version.

**Comment by samdmarshall** [comment]
And if that is not found what do you do? because right now it seems like it reports incorrectly if it cannot locate a version of `xcodebuild`.

**Comment by MikeMcQuaid** [comment]
Yes, that's probably correct. Again, though, can we bring this back to a real-world example? Do you have an working, normal Xcode where it can't find `xcodebuild`? If so, what version is it?

**Comment by chdiza** [comment]
Why would one expect an app that isn't Xcode, but has been cleverly spoofed to look like Xcode, to be correctly identified as a fake by Homebrew?

**Comment by samdmarshall** [comment]
I don't understand why everyone is getting stuck up on this "fake Xcode" thing. The path you are identifying by looking up the bundle identifier has nothing to do with the selected Xcode version via `xcode-select` (which was fixed only recently by @MikeMcQuaid). The issue i'm filing here is that brew reports about the found Xcode.app bundle in a way that is incorrect and misrepresentative to the user.

**Comment by MikeMcQuaid** [comment]
Sorry, @samdmarshall but if you're not going to answer the questions I've asked I'm not going to be able to even attempt to fix this.

**Comment by samdmarshall** [comment]
Sorry? I'm pointing out that whatever `xcodebuild` returns is irrelevant as that uses a completely different means of lookup from the `mdfind` query, so using that as a means of reporting version is incorrect.

**Comment by MikeMcQuaid** [comment]
I need answers to these questions if you'd like this fixed:
- What version of Xcode is it?
- Do you have an working, normal Xcode where it can't find xcodebuild? If so, what version is it?

Without answers for them as far as I can tell the issue is "if I set a bundle identifier to the same as Xcode's weird things happen" which I'm considering a WONTFIX.

**Comment by MikeMcQuaid** [comment]
Also, to be explicit (and I know this needs to be documented): closed issues on Homebrew don't necessarily mean "this is not a bug" but just "this is not something we plan on addressing in the near future". We're extremely understaffed on Homebrew/brew given the scale of the project and I need to try and keep the number of issues here manageable and triaged accordingly.
