### ISSUE TITLE
Fonts cannot be removed after renaming the home folder.

### ISSUE THREAD

**Issue by Sugiton** [Homebrew/brew#18644]
## Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

## Description of the issue

I renamed my home folder following official guidance from Apple:
- [Change the name of your macOS user account and home folder](https://support.apple.com/en-us/102547).

Thereafter, I could install new packages, upgrade formulas, but the upgrade of font casks failed with:
- `"It seems the Font source '... path using the previous home folder name ...' is not there.`

Consequently, the removal of font casks also proves unsuccessful due to the same underlying issue.

Employing the `--zap` stanza triggers the error message (`brew uninstall --zap font-sudo`): 
- `'It seems the Font source '... path using the previous home folder name ...' is not there.`

Interestingly, using the `--cask` flag (`brew uninstall --cask font-sudo`) yields a successful return despite the files remaining intact.

## Command that failed

`brew uninstall --zap font-sudo`

---

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading font-sudo
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading font-sudo
==> Zapping Cask font-sudo
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/font-sudo/.metadata/2.0.0/20241004120515.810/Casks/font-sudo.json
==> Implied `brew uninstall --cask font-sudo`
==> Uninstalling artifacts
==> 2 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::Font:0x000000014c8d3450 @cask=#<Cask font-sudo /opt/homebrew/Caskroom/font-sudo/.metadata/2.0.0/20241004120515.810/Casks/font-sudo.json>, @dsl_args=["sudo/SudoUIVariable.ttf"], @source_string="sudo/SudoUIVariable.ttf", @target_string="">, #<Cask::Artifact::Font:0x000000014c8d3220 @cask=#<Cask font-sudo /opt/homebrew/Caskroom/font-sudo/.metadata/2.0.0/20241004120515.810/Casks/font-sudo.json>, @dsl_args=["sudo/SudoVariable.ttf"], @source_string="sudo/SudoVariable.ttf", @target_string="">}>
==> Uninstalling artifact of class Cask::Artifact::Font
Error: It seems the Font source '/Users/Saito/Library/Fonts/SudoUIVariable.ttf' is not there.
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:160:in `move_back'
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:21:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:491:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:488:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:518:in `zap'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:70:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:65:in `each'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:65:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
```

```
HOMEBREW_VERSION: 4.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35ebf4a047b00b2b3de33ba0081d71293cdadede
Last commit: 6 days ago
Core tap JSON: 26 Oct 12:43 UTC
Core cask tap JSON: 26 Oct 12:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0.1-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/services
```

**Comment by MikeMcQuaid** [comment]
> `Saito` is the previous name of my home folder, so it is not surprising that brew can't find the font files there, the question is why does brew use such an hard coded path that has become obsolete.

If it were just to use e.g. `$HOME` or `~`: if it was run by another user it would fail.

I don't consider Homebrew hardcoding paths here to be a bug. If you can figure out a way to do this without: we'll happily review a PR. Closing for now, sorry!

**Comment by Sugiton** [comment]
> If it were just to use e.g. $HOME or ~: if it was run by another user it would fail.

[On macOS]

My apologies but fonts are typically installed per-user, not globally. Using a relative path like `~` is the correct way to access a user's installed fonts.

There are only two locations where fonts could be installed, the user's fonts folder and the system's fonts folder. The former is brew's default, while the later requires sudo access.

A simple toggle could manage that. Instead brew relies on an absolute path defined at the moment of the font installation.

Therefore a user renaming his home folder is doomed.

Anyway it is easy to remove the files manually, even though the `brew uninstall` command is supposed to handle this. 

Honestly I don't really care if you fix that failure or not. However it is disappointing to see the inability of brew maintainers to fix such a simple thing.

**Comment by MikeMcQuaid** [comment]
> A simple toggle could manage that.
> fix such a simple thing.

If it is simple: presumably it would be simple for you to create a PR to fix it.

I'll assume that if you don't either you're unable to make simple PRs or it's harder than you think it is.

Regardless, reread our Code of Conduct and adjust your tone in future issues or PRs.
