### ISSUE TITLE
brew upgrade -g failed, listxattr for destination failed

### ISSUE THREAD

**Issue by Kurt-Shiwz** [Homebrew/brew#18656]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

run `brew upgrade -g`, upgrade app failed, Caskroom loss version infomation

==> Upgrading 2 outdated packages:
raycast 1.84.5 -> 1.84.6
reqable 2.27.1 -> 2.27.2
...
==> Backing App 'Raycast.app' up to '/usr/local/Caskroom/raycast/1.84.5/Raycast.app'
==> Removing App '/Applications/Raycast.app'
==> Moving App 'Raycast.app' to '/Applications/Raycast.app'
**listxattr for destination failed: 2**
==> Purging files for version 1.84.6 of Cask raycast
==> Purging files for version 1.84.6 of Cask raycast
Warning: Reverting upgrade for Cask raycast
==> Purging files for version 1.84.5 of Cask raycast
...
Error: Problems with multiple casks:
raycast: It seems there is already an App at '/Applications/Raycast.app'.

`echo $(brew --prefix)`
/usr/local

`cd /usr/local/Caskroom && tree -L 2`
.
├── foobar2000
│   └── 2.6.5
...
│   └── 2,1.0
├── raycast
├── reqable

### Command that failed

brew upgrade -g

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.4.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --fail --remote-time --output /Users/user/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/user/Library/Caches/Homebrew/api/formula.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4328k  100 4328k    0     0  2776k      0  0:00:01  0:00:01 --:--:-- 2774k
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/lua-language-server
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/vim
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/tree
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/wget
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/ctags
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libidn2
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/trzsz
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/pandoc
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/autojump
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/go
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/ncurses
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/mpdecimal
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libuv
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/taplo
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/prettier
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/python@3.13
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libunistring
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/clang-format
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libyaml
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/brotli
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/icu4c
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/yaml-language-server
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/typescript
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/python@3.12
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/readline
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/icu4c@75
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/bash-language-server
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/sqlite
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/typescript-language-server
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/c-ares
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/xz
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/shfmt
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libnghttp2
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/lua
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/openssl@3
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/ca-certificates
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gettext
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libsodium
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/oniguruma
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/pcre2
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/pcre
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/helix
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/node
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/zsh
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/jq
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/trzsz-ssh
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/chsrc
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/ruby
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/git
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading gromgit/fuse/ntfs-3g-mac
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/lrzsz
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.4.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --fail --remote-time --output /Users/user/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/user/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1512k  100 1512k    0     0   786k      0  0:00:01  0:00:01 --:--:--  786k
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading homebrew/cask/foobar2000
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading homebrew/cask/itsycal
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading homebrew/cask/jordanbaird-ice
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading latest
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading macfuse
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading maczip
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading homebrew/cask/pearcleaner
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading qlmarkdown
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading qlstephen
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading quicklook-json
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading homebrew/cask/raycast
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading homebrew/cask/reqable
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading homebrew/cask/wezterm
```

### Output of `brew doctor` and `brew config`

```shell
`brew doctor`
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: No Cask quarantine support available: unknown reason.

`brew config`
HOMEBREW_VERSION: 4.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35ebf4a047b00b2b3de33ba0081d71293cdadede
Last commit: 9 days ago
Core tap JSON: 29 Oct 16:00 UTC
Core cask tap JSON: 29 Oct 16:00 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 3.3.5 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 16.0.0 build 1600
Git: 2.47.0 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-x86_64
CLT: 16.0.0.0.1.1724870825
Xcode: N/A
```

### Output of `brew tap`

```shell
`brew tap`
gromgit/fuse
```

**Comment by Bo98** [comment]
Are you running OpenCore? We've seen limited reports of this on that setup.

**Comment by Bo98** [comment]
Also please try update to macOS 15.1 to make sure the issue still persists there.

**Comment by Kurt-Shiwz** [comment]
> Are you running OpenCore? We've seen limited reports of this on that setup.

yes.OpenCore-Patcher 2.0.2

**Comment by cho-m** [comment]
```
Warning: No Cask quarantine support available: unknown reason.
```

May want to try a reinstall of your CLT, e.g. https://github.com/Homebrew/brew/issues/18540 / https://github.com/orgs/Homebrew/discussions/5482

**Comment by Kurt-Shiwz** [comment]
> ```
> Warning: No Cask quarantine support available: unknown reason.
> ```
> 
> May want to try a reinstall of your CLT, e.g. #18540 / https://github.com/orgs/Homebrew/discussions/5482

no helps, reinstall CLT, problem still here

**Comment by MikeMcQuaid** [comment]
> Are you running OpenCore? We've seen limited reports of this on that setup.

@Bo98 do we have a way if detecting that? We should probably add a `brew doctor` warning that we don't support it.

**Comment by MacDefender** [comment]
Same problems here with macOS 15.1. I reinstalled the CLT and now also tried installing XCode (maybe CLT were missing something). But no matter what I install/reinstall I always get 
```
Failure while executing; `/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target x86_64-apple-macosx15 /usr/local/Homebrew/Library/Homebrew/cask/utils/copy-xattrs.swift /usr/local/Caskroom/obsidian/1.7.5/Obsidian.app /Applications/Obsidian.app` exited with 1. Here's the output:
listxattr for destination failed: 2
```
I than modified the copy-xattrs.swift code to output the vars leading to this error handling and for every app it showed:
destinationNamesLength: -1
destinationPath: 0x00007ff7.... (always the same hexcode)

Only happens with brew upgrade. If I brew uninstall and than again brew install --cask ... everything is ok and works as expected

**Comment by Kurt-Shiwz** [comment]
> Same problems here with macOS 15.1. I reinstalled the CLT and now also tried installing XCode (maybe CLT were missing something). But no matter what I install/reinstall I always get
> 
> ```
> Failure while executing; `/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target x86_64-apple-macosx15 /usr/local/Homebrew/Library/Homebrew/cask/utils/copy-xattrs.swift /usr/local/Caskroom/obsidian/1.7.5/Obsidian.app /Applications/Obsidian.app` exited with 1. Here's the output:
> listxattr for destination failed: 2
> ```
> 
> I than modified the copy-xattrs.swift code to output the vars leading to this error handling and for every app it showed: destinationNamesLength: -1 destinationPath: 0x00007ff7.... (always the same hexcode)
> 
> Only happens with brew upgrade. If I brew uninstall and than again brew install --cask ... everything is ok and works as expected

yes，i try `brew reinstall xxx --force`, it can install the new version

**Comment by Bo98** [comment]
> > Are you running OpenCore? We've seen limited reports of this on that setup.
> 
> @Bo98 do we have a way if detecting that? We should probably add a `brew doctor` warning that we don't support it.

I've reflected on these issues for a few days and after seeing one too many reports trigged by one too many root cause I think I'm going to look into porting this stuff to FFI via Fiddle. Swift seems to be overall a bit of a mess right now plus it would be nice to make Casks work without needing development tools installed anyway.

**Comment by carlocab** [comment]
https://github.com/orgs/Homebrew/discussions/5723 seems related, and

> porting this stuff to FFI via Fiddle.

will likely fix it too.

**Comment by kzanev** [comment]
I slightly modified the swift script to dump out the arguments and their count of the mentioned command. Running that without any additional arguments 

`/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target x86_64-apple-macosx15 /usr/local/Homebrew/Library/Homebrew/cask/utils/copy-xattrs.swift`

printed out that 31 arguments are provided to the swift script by this command. 

The script expects that the source folder will be the second argument CommandLine.arguments[1] and the destination the third one CommandLine.arguments[2], so if I shift those arguments with 31, everything works fine. I don't know if this behaviour is somehow related to OpenCore and how exactly it could be fixed.

**Comment by palxex** [comment]
On 15.3.1 the count of arguments become 34... in same way @kzanev have found
The direct cause of the problem seems SIP settings (NVRAM/7C436110-AB2A-4BBB-A880-FE41995C9F82/csr-active-config). When it was set to 0000000, the count of arguments became 3.

**Comment by KingsleyLeung03** [comment]
Hello everyone,

I know this issue is closed as "not planned," but I wanted to share a workaround I've developed for anyone still encountering the `listxattr for destination failed: 2` error, particularly on systems running **OpenCore Legacy Patcher (OCLP)**.

The error seems to be intermittent. A cask upgrade fails on the first try but often succeeds if attempted again immediately. Based on this observation, I've forked the `homebrew-cask-upgrade` tool to automatically retry a failed installation one time. In my testing, this successfully bypasses the issue.

My tool is an external command called `brew-cask-upgrade-oc`.

This doesn't fix the root cause, but has proven to be a reliable workaround for me. The project is available on GitHub, and I hope it can help others facing the same problem.

**Project Link:** [https://github.com/KingsleyLeung03/brew-cask-upgrade-oc](https://github.com/KingsleyLeung03/homebrew-cask-upgrade-oc)

<img width="1280" height="349" alt="Image" src="https://github.com/user-attachments/assets/b2671522-b7d2-4648-bc87-f400e16d7877" />

Thanks\!

**Comment by qianbinbin** [comment]
The arguments could vary when using OCLP on Sequoia. On my 15.7:

```
/Library/Developer/CommandLineTools/usr/bin/swift-frontend, -frontend, -interpret, /usr/local/Homebrew/Library/Homebrew/cask/utils/copy-xattrs.swift, -target, x86_64-apple-macosx15, -enable-objc-interop, -stack-check, -sdk, /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk, -color-diagnostics, -new-driver-path, /Library/Developer/CommandLineTools/usr/bin/swift-driver, -empty-abi-descriptor, -resource-dir, /Library/Developer/CommandLineTools/usr/lib/swift, -module-name, main, -disable-clang-spi, -target-sdk-version, 15.5, -target-sdk-name, macosx15.5, -external-plugin-path, /Library/Developer/Developer/usr/lib/swift/host/plugins#/Library/Developer/Developer/usr/bin/swift-plugin-server, -external-plugin-path, /Library/Developer/Developer/usr/local/lib/swift/host/plugins#/Library/Developer/Developer/usr/bin/swift-plugin-server, -in-process-plugin-server-path, /Library/Developer/CommandLineTools/usr/lib/swift/host/libSwiftInProcPluginServer.dylib, -plugin-path, /Library/Developer/CommandLineTools/usr/lib/swift/host/plugins, -plugin-path, /Library/Develop
er/CommandLineTools/usr/local/lib/swift/host/plugins, --, /usr/local/Caskroom/visual-studio-code/1.104.1/Visual Studio Code.app, /Applications/Visual Studio Code.app
```

The arguments `--` and before should be removed, but somehow didn't.

Hope this helps:

```diff
diff --git a/Library/Homebrew/cask/utils/copy-xattrs.swift b/Library/Homebrew/cask/utils/copy-xattrs.swift
index 794242ed13..9d43c906fb 100755
--- a/Library/Homebrew/cask/utils/copy-xattrs.swift
+++ b/Library/Homebrew/cask/utils/copy-xattrs.swift
@@ -15,7 +15,7 @@ guard CommandLine.arguments.count >= 3 else {
     exit(2)
 }

-CommandLine.arguments[2].withCString { destinationPath in
+CommandLine.arguments.last!.withCString { destinationPath in
     let destinationNamesLength = listxattr(destinationPath, nil, 0, 0)
     if destinationNamesLength == -1 {
         print("listxattr for destination failed: \(errno)", to: &SwiftErr.stream)
@@ -40,7 +40,7 @@ CommandLine.arguments[2].withCString { destinationPath in
     }
     destinationNamesBuffer.deallocate()

-    CommandLine.arguments[1].withCString { sourcePath in
+    CommandLine.arguments.dropLast().last!.withCString { sourcePath in
         let sourceNamesLength = listxattr(sourcePath, nil, 0, 0)
         if sourceNamesLength == -1 {
             print("listxattr for source failed: \(errno)", to: &SwiftErr.stream)
```
