### ISSUE TITLE
`brew --env` support for fish, (t)csh

### ISSUE THREAD

**Issue by gregory-nisbet** [Homebrew/brew#187]
Hi everyone,

At the moment `brew --env` only supports Bourne-like shells. I have the beginnings of a pull request locally. I'm having trouble figuring out how to get the real value of the `SHELL` environment variable since in `cmd/--args.rb` the `ENV` hashmap is shadowed by `extend/ENV`.

Is there another place in the code where `brew` sniffs the value of environment variables that I can use as an example?

Thanks,
Greg

Here's an example of the kind of change I'm proposing, I just can't figure out how to get the value of the `SHELL` environment variable in a way that's consistent with the rest of the codebase.

```ruby
#:  * `--env`:
#:    Show a summary of the Homebrew build environment.

require "extend/ENV"
require "build_environment"

module Homebrew
  def __env
    ENV.activate_extensions!
    ENV.deps = ARGV.formulae if superenv?
    ENV.setup_build_environment
    ENV.universal_binary if ARGV.build_universal?

    if $stdout.tty?
      dump_build_env ENV
    elsif shell.end_with? "csh"
      # csh, tcsh
      build_env_keys(ENV).each do |key|
        puts "setenv #{key} #{ENV[key]}"
      end
    elsif shell.end_with? "fish" 
      build_env_keys(ENV).each do |key|
        puts "set -gx #{key} #{ENV[key]}"
      end
    else
      # bash, sh, ksh, zsh
      build_env_keys(ENV).each do |key|
        puts "export #{key}=\"#{ENV[key]}\""
      end
    end
  end
end
```

**Comment by apjanke** [comment]
You don't want to use `$SHELL` for this anyway: it is the user's preferred default shell (e.g. what they have set in `/etc/passwd`), not the shell that this process is currently running under. There's no standard environment variable that indicates the lowermost shell that a process is actually running under. (And there might not be one anyway, if it was `exec`'ed away.)

To detect the shell, walk up the parent PID tree (gleaned from `ps` or native Ruby code) until you encounter a known shell, and use that command name as the default shell. And we should provide a `--shell <name>` option to override it, for weird cases, or if you wanted to get the commands in a given shell's syntax for incorporating in a profile file or something for a particular shell, regardless of what shell you're calling `brew --env` from.

**Comment by gregory-nisbet** [comment]
@apjanke

Sounds like a good suggestion, walking up the process tree and seeing what things smell shell-like. Here's my first stab a function to do that. The `end_with?("sh")` will be replaced with a better test that'll compare the basename of argv[0] against a known list of shells (and handle that weird login shell thing where argv[0] begins with `-` (e.g. `-tcsh`)).

How exactly would one go about adding support for a new command line argument of a subcommand (is `--env` considered a subcommand?). I've tried looking at a few examples and most of them seem to be checking if ARGV includes a particular string.

``` ruby
  def getshell
    shell_pid = Process.ppid
    if 
      shell_command = `ps -p #{shell_pid} -o command=`.chomp
      if shell_command.end_with?("sh")
        return shell_command
      end
      shell_pid = `ps -p #{shell_pid} -o ppid=`.chomp
      if shell_pid = ""
        return "sh"
      end
    end
  end
```

**Comment by apjanke** [comment]
> How exactly would one go about adding support for a new command line argument of a subcommand (is `--env` considered a subcommand?). I've tried looking at a few examples and most of them seem to be checking if ARGV includes a particular string.

That's basically how we do it, and then parse ARGV directly to get a value for it if you need one. It's a little Wild West out here.

Unfortunately, most of our options are booleans, and we haven't standardized on how to handle options that take arguments. In fact, for the few that do, some use the style `--foo=4` and some use `--foo 4`.

Probably a good time to try to regularize this before more options that take arguments crop up and we diverge even more. Let me get some sleep and I'll put in something for this tomorrow; it really could use some centralized code for it.

**Comment by apjanke** [comment]
Oh, and yes, `--env` is a subcommand even though it looks like an option. Anything that has a corresponding `cmd/--whatever.rb` file is a subcommand.

**Comment by mikemcquaid** [comment]
Hmm, I'm not sure what I think about this. Certainly if you just want Fish support I'd just add Fish rather than other shells you don't use. CC @mistydemeo as, I believe, a Fish user.

**Comment by gregory-nisbet** [comment]
I use tcsh. There are a few other projects out there like opam and virtualenv that generate shell scripts intended to be `source`d or `eval`ed elsewhere that support Bourne-like shells, csh, and fish but not less common things like scsh or rc/es.

In either case since all that `--env` does is export environment variables it'd be simple enough to

     # csh
     brew --env | sed -e 's/export/setenv/' -e 's/=/ /'
     # fish
     brew --env | sed -e 's/export/set -gx/' -e 's/=/ /'

**Comment by apjanke** [comment]
One csh user motivated enough to work on a PR means there's probably plenty more out there among our 30,000 stargazers. I'd say let's do it.

**Comment by gregory-nisbet** [comment]
I've added the functionality to detect the shell and some logic to parse `--shell <shell-name>` and `--shell=<shell-name>` to my fork, but I haven't added tests yet. Is it appropriate to submit a pull request anyway and ask for recommendations/help about tests there?

**Comment by apjanke** [comment]
Yes. If you can submit a partially complete PR, that gives us something concrete to discuss, and it's easy to iterate on code changes. Go ahead and do so. Once you have a PR submitted, you can close this issue out in favor of it.

**Comment by gregory-nisbet** [comment]
Closing issue in favor of PR https://github.com/Homebrew/brew/pull/201
