### ISSUE TITLE
Labeling formulas as "automatically" installed?

### ISSUE THREAD

**Issue by gwerbin** [Homebrew/brew#1870]
Apologies if this has been suggested before -- I did a search in here and homebrew/legacy-homebrew but didn't find anything.

Linux package managers are typically able to distinguish between "manually" installed packages (installed explicitly by the user) and "automatically" installed packages (installed as dependencies for other packages).

Is this something that is worth looking into for Homebrew? The main use case would be to enable a `brew autoremove` command that automatically removes dependencies for packages that are no longer needed, but that the user doesn't actually want.

For instance, [R](https://github.com/Homebrew/homebrew-science/blob/master/r.rb) depends on a relatively long list of packages (gcc, gettext, readline, xz, et al.) that a user might want or need otherwise. If that user ever goes to uninstall R, they will still be left with all those packages, _and_ all the dependencies of those packages, recursively _ad nauseum_. It would be great to be able to `brew remove R && brew autoremove` to take care of the problem in a one-liner.

This technique could probably be extended to keeping track of the _version_ that's installed automatically, so you could in theory have one package depend specifically on GCC 4.8 and another depend simply on the latest GCC. But I know the multiple-versions issue has been discussed before, so I don't want to make it the focus here.

**Comment by MikeMcQuaid** [comment]
I'm working on storing the data for this in https://github.com/Homebrew/brew/pull/1813.
