### ISSUE TITLE
Refusal of homebrew to install openssl@1.1 breaks ruby 

### ISSUE THREAD

**Issue by roddi** [Homebrew/brew#18719]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.4-32-g3ff3ad6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3ff3ad6f6f3ff31116f96f03c866c0e2e971f0e9
Last commit: 2 hours ago
Core tap HEAD: 6e61d33566c3a1bec605974f2f16db951fc8ec62
Core tap last commit: 14 minutes ago
Core tap JSON: 06 Nov 10:57 UTC
Core cask tap JSON: 06 Nov 10:57 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode-15.4.app/Contents/Developer/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4 => /Applications/Xcode-15.4.app/Contents/Developer
```

### What were you trying to do (and why)?

try to install ruby 3.3.6 (latest version) with rvm.

`rvm install ruby-3.3.6`

### What happened (include all command output)?

Searching for binary rubies, this might take some time.
No binary rubies available for: osx/14.5/x86_64/ruby-3.3.6.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Installing requirements for osx.
Updating system..........
Installing required packages: openssl@1.1.There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://docs.brew.sh/Installation
..
Error running 'requirements_osx_brew_libs_install openssl@1.1',
please read /Users/jenkins/.rvm/log/1730890815_ruby-3.3.6/package_install_openssl@1.1.log
Requirements installation failed with status: 1.

### What did you expect to happen?

ruby would be installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openssl@1.1
```

**Comment by gromgit** [comment]
1. OpenSSL 1.1 was EOL'd over a year ago.
2. Current Homebrew Ruby (also 3.3.6) explicitly depends on OpenSSL 3, and builds with no issues.

_Conclusion:_ RVM's Ruby build instructions are out of date, and should be updated.

**Comment by carlocab** [comment]
This is an RVM bug.

**Comment by roddi** [comment]
There's bug tickets over there already.

**Comment by carlocab** [comment]
Great; hopefully they'll fix it soon.

**Comment by roddi** [comment]
I know this is not a homebrew issue at this point but googling people might be stumbling on this ticket. 

So, when I did

`rvm get master`

I could actually install newer ruby versions. (From source but hey 🤷‍♂️) 

Good Luck everyone.

**Comment by Bo98** [comment]
Yes, RVM stable has not been updated for many years now. `rvm get master` is really the only way to install modern Ruby nowadays.

**Comment by MikeMcQuaid** [comment]
Note that Homebrew has better support/integration with `rbenv` so we'd recommend that instead.
