### ISSUE TITLE
Update brew cask xip container extraction

### ISSUE THREAD

**Issue by Quesar** [Homebrew/brew#1874]
### Propose a feature:

Please update what a xip container is and how it is extracted. The current implementation considers xip to be a "cpio inside a gzip inside a xar", but Apple has reused this extension for signed Xcode packages.

I can't find any casks that use such extension, and the Suspicious Package cask, for which the implementation was added for, "is now distributed as .dmg since Apple has removed support for .xip archives (except for those signed by Apple) in Sierra".

If the xip container extraction would be updated to be something like here - https://github.com/KrauseFx/xcode-install/blob/master/lib/xcode/install.rb#L79 - then Xcode could be installed as a cask.

Currently a cask with .xip in url fails to extract:

> ==> Verifying signature for xcode@8.0--8.0.xip
> ==> cpio: Unrecognized archive format: Inappropriate file type or format
> Error: Command failed to execute!
> 
> ==> Failed command:
> /usr/bin/cpio --quiet -i -I #<Pathname:/var/folders/s8/6frjksc91hb2l6mgcfllbr140000gn/T/d20170118-8729-1bq426i/Content>
> 
> ==> Standard Output of failed command:
> 
> 
> ==> Standard Error of failed command:
> cpio: Unrecognized archive format: Inappropriate file type or format
> 
> 
> ==> Exit status of failed command:
> #<Process::Status: pid 8844 exit 1>
> Error: nothing to install

**Comment by reitermarkus** [comment]
Ok, so as I understand it, an `.xip` is now basically a `.cpio.xz.pbzx.xar` archive. This would add a dependency on a `pbzx` and a `xz` utility, so I don't think this is worth supporting at all, since there isn't even *one* cask using it.

**Comment by Quesar** [comment]
I'm not sure what a .xip technically is, but it is already used by Apple to distribute Xcode 8+. Perhaps Apple will reuse the container for distributing other tools such as command line tools in the future.

We are using a private Homebrew tap to manage Xcode installations. For old Xcode packages where the .app is inside a .dmg everything works fine, but as the newer Xcode is packaged as .xip which Homebrew does not support I'm looking for solutions.

I'm not a Ruby dev so I can not make a pull request with the changes, and I'm not sure it would be accepted.

**Comment by reitermarkus** [comment]
As I said you would need a dependency on `xz` and `pbzx`, which we won't add, since there doesn't seem to be an official `pbzx` tool.

But since a cask is just a Ruby block, you can [extract it manually](http://stackoverflow.com/a/39489446/1114002) or with **Archive Utility** using [`system_command`](https://github.com/caskroom/homebrew-cask/search?utf8=✓&q=system_command) in the `preflight` block.
