### ISSUE TITLE
Error: pathname contains null byte

### ISSUE THREAD

**Issue by jamesonquinn** [Homebrew/brew#1875]
Brew doctor gives "Error: pathname contains null byte". I suspect this is a broken symlink in my system somewhere, but brew doctor should tell me where so I can fix it.

https://gist.github.com/jamesonquinn/18d53ca955a872e49f7081b2551c3b8e

**Comment by jamesonquinn** [comment]
Some more symptoms: uninstall doesn't work (this is what actually got me to try brew doctor in the first place) Here:

Jamesons-MacBook-Pro-2:vse-sim chema$ brew install python3
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
youtube-dl

Error: python3-3.4.1 already installed
To install this version, first `brew unlink python3`
Jamesons-MacBook-Pro-2:vse-sim chema$ brew uninstall python3
Error: 757: unexpected token at ''
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
/usr/local/Homebrew/Library/Homebrew/tab.rb:62:in `from_file_content'
/usr/local/Homebrew/Library/Homebrew/tab.rb:57:in `block in from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:57:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tab.rb:57:in `from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:102:in `for_keg'
/usr/local/Homebrew/Library/Homebrew/keg.rb:392:in `block in installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:391:in `select'
/usr/local/Homebrew/Library/Homebrew/keg.rb:391:in `installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:107:in `block in find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:105:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:105:in `find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:90:in `check_for_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:83:in `handle_unsatisfied_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:31:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Jamesons-MacBook-Pro-2:vse-sim chema$ brew uninstallll python3
Error: Unknown command: uninstallll

**Comment by alyssais** [comment]
What does `readlink "$(brew --prefix)/opt/python"` output?

**Comment by jamesonquinn** [comment]
Jamesons-MacBook-Pro-2:local chema$ readlink "$(brew --prefix)/opt/python"
../Cellar/python/2.7.8

**Comment by alyssais** [comment]
Oh, wait, I misread your comment, sorry. Thought it said `python` instead of `python3`. Could you try again with `python3`?

```sh
readlink "$(brew --prefix)/opt/python3"
```

**Comment by jamesonquinn** [comment]
../Cellar/python3/3.4.1

**Comment by alyssais** [comment]
Does `/usr/local/Cellar/python3/3.4.1` exist?

**Comment by jamesonquinn** [comment]
Jamesons-MacBook-Pro-2:vse-sim chema$ cd /usr/local/Cellar/python3/3.4.1 
Jamesons-MacBook-Pro-2:3.4.1 chema$ ls
Frameworks		INSTALL_RECEIPT.json	Python Launcher 3.app	bin
IDLE 3.app		LICENSE			README			share

**Comment by alyssais** [comment]
@jamesonquinn edited your first comment to make the Terminal output a little more readable

**Comment by alyssais** [comment]
Is <kbd>brew uninstall</kbd> broken just for `python3`, or for everything?

**Comment by jamesonquinn** [comment]
It seems to be broken more widely; not just `uninstall`, but `install`:
```
Jamesons-MacBook-Pro-2:local chema$ brew install docker
==> Downloading https://homebrew.bintray.com/bottles/docker-1.13.0.el_capitan.b
######################################################################## 100.0%
==> Pouring docker-1.13.0.el_capitan.bottle.1.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
pathname contains null byte
```

**Comment by alyssais** [comment]
@jamesonquinn thanks for bearing with me. This is a tricky one to debug remotely, but I think we're getting somewhere.

Can you let me know what the output of this is?

```sh
find . -type l ! -exec test -e {} \; -print
```

**Comment by jamesonquinn** [comment]
No output.

**Comment by MikeMcQuaid** [comment]
Closing this as it's not something we've been able to debug, sorry.

**Comment by allejo** [comment]
So I just ran into the same issue. I'm not sure *how* this happened but it happened to me. Here's what I did to fix it.

1. On `/usr/local/Homebrew/Library/Homebrew/tab.rb:62` I added a `puts path` as the first line in that function
2. Then it'll list all of the files that it's parsing. The last `INSTALL_RECEIPT.json` file is the one that will have the issue (there may be more so you may have to repeat this several times).
3. Either fix the JSON file if you can or delete the package folder that contains the issue and just use `brew install` the package again.
4. Then remove the `puts` you wrote in step 1.

**Comment by jamesonquinn** [comment]
I did what Allejo suggested (adding the `puts path` in two functions, self.from_file and self.from_file_content, because line 62 was not right, but it just showed twice so that's OK). The error was in /usr/local/Cellar/gettext/0.19.8.1/INSTALL_RECEIPT.json. Since my gettext is borked, I decided to just reinstall, so I did `rm -rf /usr/local/Cellar/gettext/; brew install gettext`. Result:

```
Updating Homebrew...
To restore the stashed changes to /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git stash pop'
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
ansifilter          cgal                lean-cli            nano                sslscan
argus               ffmpeg ✔            libressl            paket               swift
bind                fluent-bit          mksh                pqiv                terraform
buildifier          hyper               mps-youtube         sonar-scanner       tfenv
cayley              infer               mpv                 speedtest_cli       vc4asm
Error: pathname contains null byte
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:347:in `initialize'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:347:in `readlink'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:347:in `resolved_path'
/usr/local/Homebrew/Library/Homebrew/keg.rb:237:in `optlinked?'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:270:in `each'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:270:in `detect'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:270:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1429:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1427:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1427:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:505:in `migrate_formula_rename'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gettext-0.19.8.1.sierra.bottle.tar.gz
Error: pathname contains null byte
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:347:in `initialize'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:347:in `readlink'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:347:in `resolved_path'
/usr/local/Homebrew/Library/Homebrew/keg.rb:379:in `block in oldname_opt_record'
/usr/local/Homebrew/Library/Homebrew/keg.rb:378:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:378:in `detect'
/usr/local/Homebrew/Library/Homebrew/keg.rb:378:in `oldname_opt_record'
/usr/local/Homebrew/Library/Homebrew/keg.rb:485:in `optlink'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:700:in `link'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:564:in `finish'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:320:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:207:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Jamesons-MacBook-Pro-2:~ chema$ brew link --overwrite gettext --force
Error: pathname contains null byte
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:347:in `initialize'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:347:in `readlink'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:347:in `resolved_path'
/usr/local/Homebrew/Library/Homebrew/keg.rb:379:in `block in oldname_opt_record'
/usr/local/Homebrew/Library/Homebrew/keg.rb:378:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:378:in `detect'
/usr/local/Homebrew/Library/Homebrew/keg.rb:378:in `oldname_opt_record'
/usr/local/Homebrew/Library/Homebrew/keg.rb:294:in `block in lock'
/usr/local/Homebrew/Library/Homebrew/formula_lock.rb:25:in `with_lock'
/usr/local/Homebrew/Library/Homebrew/keg.rb:293:in `lock'
/usr/local/Homebrew/Library/Homebrew/cmd/link.rb:62:in `block in link'
/usr/local/Homebrew/Library/Homebrew/cmd/link.rb:28:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/link.rb:28:in `link'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by jamesonquinn** [comment]
Using allejo's trick of adding debug output to the ruby files (but not just in tab.rb), I eventually found the culprit: a bad symlink at `/usr/local/opt/scons`. Removing that, and then `rm -rf /usr/local/Cellar/scons/`, and then some cleanup as suggested by brew doctor, got me working again.

**Comment by alyssais** [comment]
Glad you got it sorted @jamesonquinn! Sorry I couldn't help much! :)
