### ISSUE TITLE
check_for_opencore false positive

### ISSUE THREAD

**Issue by guycalledseven** [Homebrew/brew#18763]
### `brew doctor` output

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have installed macOS using OpenCore Legacy Patcher.
We do not provide support for this configuration.
It is expected behaviour that some formulae will fail to build in this unsupported configuration.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.5-14-gb421c2f
ORIGIN: https://github.com/Homebrew/brew
HEAD: b421c2f0685bbeab84aaa7f2f77a098bc8f68553
Last commit: 88 minutes ago
Core tap JSON: 13 Nov 10:13 UTC
Core cask tap JSON: 13 Nov 10:13 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.47.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false
```

### What were you trying to do (and why)?

[Newly added](https://github.com/Homebrew/brew/pull/18761) check_for_opencore check is falsely reporting that i've installed macOS using OpenCore Legacy Patcher. 
I have not, but I do have OpenCore Legacy patcher installed for purpose of making bootable usb. 

[The check](https://github.com/Homebrew/brew/blob/b421c2f0685bbeab84aaa7f2f77a098bc8f68553/Library/Homebrew/extend/os/mac/diagnostic.rb#L131) is wrong IMHO - it just checks for existance of those two files:

- `/Library/Application Support/Dortania/OpenCore-Patcher.app`
- `/Library/PrivilegedHelperTools/com.dortania.opencore-legacy-patcher.privileged-helper`

### What happened (include all command output)?

The warning showed up.

### What did you expect to happen?

No warning about OpenCore Legacy patcher.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew doctor
```

**Comment by MikeMcQuaid** [comment]
> [The check](https://github.com/Homebrew/brew/blob/b421c2f0685bbeab84aaa7f2f77a098bc8f68553/Library/Homebrew/extend/os/mac/diagnostic.rb#L131) is wrong IMHO - it just checks for existance of those two files:
> 
> * `/Library/Application Support/Dortania/OpenCore-Patcher.app`
> * `/Library/PrivilegedHelperTools/com.dortania.opencore-legacy-patcher.privileged-helper`

Can you suggest files we should check for instead?

**Comment by ZhongRuoyu** [comment]
> Maybe NVRAM check for bootloader?

I was thinking the same: #18765

> Though would need someone with OpenCore to check how reliable (EDIT: and maybe won't work for older Mac that don't use NVRAM? Though looks like it should emulate it)

Can @EricFromCanada perhaps confirm on your OpenCore enabled device(s)?

**Comment by EricFromCanada** [comment]
[Seems to work…](https://github.com/Homebrew/brew/pull/18765#pullrequestreview-2433609720)
