### ISSUE TITLE
Remove OpenStruct dependency

### ISSUE THREAD

**Issue by dduugg** [Homebrew/brew#18777]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`ostruct` will no longer be a default gem as of Ruby 3.5: https://github.com/ruby/ruby/pull/10428
It's already [discouraged](https://docs.rubocop.org/rubocop/cops_style.html#styleopenstructuse) for "performance, version compatibility, and potential security issues".

We have two instances to clean up:

Library/Homebrew/cli/args.rb
Library/Homebrew/cmd/uses.rb

### What is the motivation for the feature?

☝️ 

### How will the feature be relevant to at least 90% of Homebrew users?

resolution of the performance, version compatibility, and potential security issues described above.

### What alternatives to the feature have been considered?

None

**Comment by MikeMcQuaid** [comment]
Agreed, we should do this.

**Comment by apainintheneck** [comment]
It'd be simple to create a small class that replicates the `OpenStruct` usage in `Homebrew::Cmd::Uses` (I can do this real quick). Removing it from `Homebrew::CLI::Args` will be a bit more involved.

**Comment by dduugg** [comment]
Yep, the class is a single file, and must of the functionality is via an `@table` attr that is accessed via `method_missing`: https://github.com/ruby/ostruct/blob/master/lib/ostruct.rb

It still leaves the major concerns intact though (e.g. performance & security), the code remains difficult to follow, etc. Opening this so we have a bit of time to think of something better (but feel free to self-assign if you have strong opinions).

**Comment by apainintheneck** [comment]
I see your point. The goal here is not just to remove the `OpenStruct` dependency but also refactor the surrounding code so that it doesn't rely on `OpenStruct`-like anti-patterns.

**Comment by MikeMcQuaid** [comment]
> The goal here is not just to remove the `OpenStruct` dependency but also refactor the surrounding code so that it doesn't rely on `OpenStruct`-like anti-patterns.

Exactly. OpenStruct is also pretty Sorbet-unfriendly.
