### ISSUE TITLE
`HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source ` fails due no inaccessible homebrew-c

### ISSUE THREAD

**Issue by norbusan** [Homebrew/brew#18785]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: cc0b5d6d05d1f3af5b2f53e9fbb1e7bfa0c332ab
Last commit: 24 hours ago
Core tap JSON: 18 Nov 10:37 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.5 => /usr/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 18.1.8
Git: 2.47.0 => /bin/git
Curl: 8.11.0 => /bin/curl
Kernel: Linux 6.11.8-zen1-2-zen x86_64 GNU/Linux
OS: Arch Linux
Host glibc: 2.40
/usr/bin/gcc: 14.2.1
/usr/bin/ruby: 3.3.5
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

locally compiling a new version of the cafeobj package

### What happened (include all command output)?

Failure to clone homebrew-c due to authentication error:
```
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source  Formula/c/cafeobj.rb 
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Tapping formula/c
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/formula/homebrew-c'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Formula/homebrew-c/'
Error: Failure while executing; `git clone https://github.com/Formula/homebrew-c /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/formula/homebrew-c --origin=origin --template= --config core.fsmonitor=false` exited with 128.
```

### What did you expect to happen?

Running the build to verify correctness of the updated formula

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Try to compile any formula with

HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source  Formula/x/xxxxx
```
```

**Comment by ZhongRuoyu** [comment]
You should be installing `cafeobj` or `homebrew/core/cafeobj`, not `Formula/c/cafeobj.rb`.

**Comment by norbusan** [comment]
Thanks @ZhongRuoyu 

Thanks for your comment, but I don't understand:

> You should be installing `cafeobj` or `homebrew/core/cafeobj`, not `Formula/c/cafeobj.rb`.

Then how am I supposed to test that the build works? The PR template explicitly states that I need to run this? And with brew a few versions ago this was possible (I tested it today with an old version).

Thanks

**Comment by ZhongRuoyu** [comment]
> Then how am I supposed to test that the build works?

When you do this with `HOMEBREW_NO_INSTALL_FROM_API=1`, the formula from your local tap will be used. So any changes you make to the local formula will be in effect.

> The PR template explicitly states that I need to run this?

The PR template says:

> Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?

Please note that the *name* of the formula is `cafeobj`; `Formula/c/cafeobj.rb` is its path. The template would've been phrased differently if the path is supposed to be used. 

> And with brew a few versions ago this was possible (I tested it today with an old version).

Although it could have worked in the past, installing formulae from paths like this is not really supported. You are advised to use the formula name `cafeobj` (or in its full form, `homebrew/core/cafeobj`) in all situations.

**Comment by norbusan** [comment]
Thanks a lot @ZhongRuoyu 

ok, then I have to change my development flow - I have done this now and submitted a PR for cafeobj update.

I originally when first submitting cafeobj for inclusion, I had a checkout of homebrew-core in some other (my homedir), and did all the test from there. Now I need to do it in the /home/linuxbrew/.linuxbrew/... directory.

Thanks for helping!
