### ISSUE TITLE
macos package installer fails

### ISSUE THREAD

**Issue by hedgehogdrfrink** [Homebrew/brew#18799]
### `brew doctor` output

```shell
n/a
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
n/a
```

### What were you trying to do (and why)?

install brew via macos package installer

### What happened (include all command output)?

Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: @(#)PROGRAM:Install  PROJECT:Install-1000
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: @(#)PROGRAM:Installer  PROJECT:Installer-1301
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Hardware: MacBookPro16,1 @ 2.40 GHz (x 16), 65536 MB RAM
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Running OS Build: macOS 15.1.1 (24B91)
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: MOZ_APP_SILENT_START=
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: XRE_PROFILE_LOCAL_PATH=
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: _NS_SAFE_APERTURE_COMPATIBILITY_MODES=2
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: MallocNanoZone=0
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: USER=user
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: MOZ_CRASHREPORTER_RESTART_ARG_1=
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: MOZ_CRASHREPORTER_PING_DIRECTORY=/Users/user/Library/Application Support/Firefox/Pending Pings
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: __CFBundleIdentifier=com.apple.installer
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: XRE_START_OFFLINE=
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: COMMAND_MODE=unix2003
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: XRE_RESTARTED_BY_PROFILE_MANAGER=
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: XRE_PROFILE_PATH=
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: XUL_APP_FILE=
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: LOGNAME=user
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.fomiUXftqv/Listeners
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: SYSTEM_VERSION_COMPAT=0
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: MOZ_CRASHREPORTER_DATA_DIRECTORY=/Users/user/Library/Application Support/Firefox/Crash Reports
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: XRE_BINARY_PATH=
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: SHELL=/bin/zsh
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: MOZ_CRASHREPORTER_STRINGS_OVERRIDE=/Applications/Firefox.app/Contents/Resources/browser/crashreporter-override.ini
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: MOZ_CRASHREPORTER_EVENTS_DIRECTORY=/Users/user/Library/Application Support/Firefox/Profiles/ylqcnxgm.default-release/crashes/events
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: MOZ_LAUNCHED_CHILD=
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: HOME=/Users/user
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: TMPDIR=/var/folders/8h/qgqvzvq92glcmbcb7rkjy_nm0000gn/T/
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: XPC_SERVICE_NAME=application.com.apple.installer.1152921500312073460.1152921500312073465
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Env: XPC_FLAGS=0x0
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Homebrew  Installation Log
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Opened from: /Users/user/Downloads/Homebrew-4.4.6(1).pkg
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Product archive /Users/user/Downloads/Homebrew-4.4.6(1).pkg trustLevel=350
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: External component packages (1) trustLevel=350
Nov 21 17:41:19 users-MacBook-Pro Installer[6719]: Could not load resource readme: (null)
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: ================================================================================
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: User picked Standard Install
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: Choices selected for installation:
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: 	Upgrade: ""
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: 	Upgrade: "(null)"
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: 		Homebrew-4.4.6(1).pkg#Homebrew.pkg : sh.brew.homebrew : 4.4.6
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: ================================================================================
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: It took 0.00 seconds to summarize the package selections.
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/user/Downloads/Homebrew-4.4.6(1).pkg#Homebrew.pkg
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: Set authorization level to root for session
Nov 21 17:41:49 users-MacBook-Pro Installer[6719]: Authorization is being checked, waiting until authorization arrives.
Nov 21 17:41:51 users-MacBook-Pro Installer[6719]: Administrator authorization granted.
Nov 21 17:41:51 users-MacBook-Pro Installer[6719]: Packages have been authorized for installation.
Nov 21 17:41:51 users-MacBook-Pro Installer[6719]: Will use PK session
Nov 21 17:41:51 users-MacBook-Pro Installer[6719]: Using authorization level of root for IFPKInstallElement
Nov 21 17:41:51 users-MacBook-Pro Installer[6719]: Starting installation:
Nov 21 17:41:51 users-MacBook-Pro Installer[6719]: Configuring volume "Infected"
Nov 21 17:41:51 users-MacBook-Pro Installer[6719]: Preparing disk for local booted install.
Nov 21 17:41:51 users-MacBook-Pro Installer[6719]: Free space on "Infected": 7.91 TB (7913190813696 bytes).
Nov 21 17:41:51 users-MacBook-Pro Installer[6719]: Create temporary directory "/var/folders/8h/qgqvzvq92glcmbcb7rkjy_nm0000gn/T//Install.6719Sny4tg"
Nov 21 17:41:51 users-MacBook-Pro Installer[6719]: IFPKInstallElement (1 packages)
Nov 21 17:41:54 users-MacBook-Pro Installer[6719]: Current Path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Nov 21 17:41:54 users-MacBook-Pro installd[593]: PackageKit: Adding client PKInstallDaemonClient pid=6719, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Nov 21 17:41:54 users-MacBook-Pro Installer[6719]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Nov 21 17:41:54 users-MacBook-Pro installd[593]: PackageKit: Set reponsibility for install to 6719
Nov 21 17:41:54 users-MacBook-Pro installd[593]: PackageKit: Hosted team responsibility for install set to team:(927JGANW46)
Nov 21 17:41:54 users-MacBook-Pro installd[593]: PackageKit: ----- Begin install -----
Nov 21 17:41:54 users-MacBook-Pro installd[593]: PackageKit: request=PKInstallRequest <1 packages, destination=/>
Nov 21 17:41:54 users-MacBook-Pro installd[593]: PackageKit: packages=(
	    "PKLeopardPackage <id=sh.brew.homebrew, version=4.4.6, url=file:///Users/user/Downloads/Homebrew-4.4.6(1).pkg#Homebrew.pkg>"
	)
Nov 21 17:41:54 users-MacBook-Pro installd[593]: PackageKit: Will do receipt-based obsoleting for package identifier sh.brew.homebrew (prefix path=opt/homebrew)
Nov 21 17:41:55 users-MacBook-Pro installd[593]: PackageKit: Extracting file:///Users/user/Downloads/Homebrew-4.4.6(1).pkg#Homebrew.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/EF15B0A9-7391-45A0-81CA-456F10F6B00C.activeSandbox/Root/opt/homebrew, uid=0)
Nov 21 17:41:56 users-MacBook-Pro installd[593]: PackageKit: prevent user idle system sleep
Nov 21 17:41:56 users-MacBook-Pro installd[593]: PackageKit: suspending backupd
Nov 21 17:41:56 users-MacBook-Pro installd[593]: PackageKit (package_script_service): Preparing to execute script "./preinstall" in /private/tmp/PKInstallSandbox.JU1qId/Scripts/sh.brew.homebrew.RPOyda
Nov 21 17:41:56 users-MacBook-Pro package_script_service[4624]: PackageKit: Preparing to execute script "preinstall" in /tmp/PKInstallSandbox.JU1qId/Scripts/sh.brew.homebrew.RPOyda
Nov 21 17:41:56 users-MacBook-Pro package_script_service[4624]: Set responsibility to pid: 6719, responsible_path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Nov 21 17:41:56 users-MacBook-Pro package_script_service[4624]: Hosted team responsibility for script set to team:(927JGANW46)
Nov 21 17:41:56 users-MacBook-Pro package_script_service[4624]: PackageKit: Executing script "preinstall" in /tmp/PKInstallSandbox.JU1qId/Scripts/sh.brew.homebrew.RPOyda
Nov 21 17:41:56 users-MacBook-Pro install_monitor[6724]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Nov 21 17:41:57 users-MacBook-Pro package_script_service[4624]: PackageKit: Hosted team responsible for script has been cleared.
Nov 21 17:41:57 users-MacBook-Pro package_script_service[4624]: Responsibility set back to self.
Nov 21 17:41:57 users-MacBook-Pro installd[593]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/EF15B0A9-7391-45A0-81CA-456F10F6B00C.sandboxTrash for sandbox /Library/InstallerSandboxes/.PKInstallSandboxManager/EF15B0A9-7391-45A0-81CA-456F10F6B00C.activeSandbox
Nov 21 17:41:57 users-MacBook-Pro installd[593]: PackageKit: Shoving /Library/InstallerSandboxes/.PKInstallSandboxManager/EF15B0A9-7391-45A0-81CA-456F10F6B00C.activeSandbox/Root (1 items) to /
Nov 21 17:41:57 users-MacBook-Pro shove[6730]: [dstPath=/opt] is an APFS firmlink, merging instead of renaming.
Nov 21 17:41:57 users-MacBook-Pro installd[593]: PackageKit (package_script_service): Preparing to execute script "./postinstall" in /private/tmp/PKInstallSandbox.JU1qId/Scripts/sh.brew.homebrew.RPOyda
Nov 21 17:41:57 users-MacBook-Pro package_script_service[4624]: PackageKit: Preparing to execute script "postinstall" in /tmp/PKInstallSandbox.JU1qId/Scripts/sh.brew.homebrew.RPOyda
Nov 21 17:41:57 users-MacBook-Pro package_script_service[4624]: Set responsibility to pid: 6719, responsible_path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Nov 21 17:41:57 users-MacBook-Pro package_script_service[4624]: Hosted team responsibility for script set to team:(927JGANW46)
Nov 21 17:41:57 users-MacBook-Pro package_script_service[4624]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.JU1qId/Scripts/sh.brew.homebrew.RPOyda
Nov 21 17:41:59 users-MacBook-Pro package_script_service[4624]: ./postinstall: HEAD is now at cc0b5d6d05 Merge pull request #18782 from Homebrew/sponsors-maintainers-man-completions
Nov 21 17:41:59 users-MacBook-Pro package_script_service[4624]: ./postinstall: Switched to a new branch 'master'
Nov 21 17:41:59 users-MacBook-Pro package_script_service[4624]: ./postinstall: branch 'master' set up to track 'origin/master'.
Nov 21 17:41:59 users-MacBook-Pro package_script_service[4624]: ./postinstall: mv: rename /opt/homebrew to /usr/local/Homebrew/homebrew: Directory not empty
Nov 21 17:41:59 users-MacBook-Pro package_script_service[4624]: PackageKit: Hosted team responsible for script has been cleared.
Nov 21 17:41:59 users-MacBook-Pro package_script_service[4624]: Responsibility set back to self.
Nov 21 17:41:59 users-MacBook-Pro install_monitor[6724]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Nov 21 17:42:00 users-MacBook-Pro installd[593]: PackageKit: releasing backupd
Nov 21 17:42:00 users-MacBook-Pro installd[593]: PackageKit: allow user idle system sleep
Nov 21 17:42:00 users-MacBook-Pro installd[593]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Homebrew-4.4.6(1).pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Users/user/Downloads/Homebrew-4.4.6(1).pkg#Homebrew.pkg, PKInstallPackageIdentifier=sh.brew.homebrew, NSLocalizedDescription=An error occurred while running scripts from the package “Homebrew-4.4.6(1).pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cHomebrew-4.4.6(1).pkg\U201d.";
	    NSURL = "file:///Users/user/Downloads/Homebrew-4.4.6(1).pkg#Homebrew.pkg";
	    PKInstallPackageIdentifier = "sh.brew.homebrew";
	}
Nov 21 17:42:00 users-MacBook-Pro installd[593]: PackageKit: Cleared responsibility for install from 6719.
Nov 21 17:42:00 users-MacBook-Pro installd[593]: PackageKit: Cleared permissions on Installer.app
Nov 21 17:42:00 users-MacBook-Pro installd[593]: PackageKit: Hosted team responsible for install has been cleared.
Nov 21 17:42:00 users-MacBook-Pro installd[593]: PackageKit: Running idle tasks
Nov 21 17:42:00 users-MacBook-Pro installd[593]: PackageKit: Done with sandbox removals
Nov 21 17:42:00 users-MacBook-Pro Installer[6719]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Homebrew-4.4.6(1).pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Users/user/Downloads/Homebrew-4.4.6(1).pkg#Homebrew.pkg, PKInstallPackageIdentifier=sh.brew.homebrew, NSLocalizedDescription=An error occurred while running scripts from the package “Homebrew-4.4.6(1).pkg”.}
Nov 21 17:42:00 users-MacBook-Pro installd[593]: PackageKit: Removing client PKInstallDaemonClient pid=6719, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Nov 21 17:42:00 users-MacBook-Pro Installer[6719]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Nov 21 17:42:00 users-MacBook-Pro Installer[6719]: IFDInstallController D977AD70 state = 8
Nov 21 17:42:00 users-MacBook-Pro Installer[6719]: Displaying 'Install Failed' UI.
Nov 21 17:42:00 users-MacBook-Pro Installer[6719]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

### What did you expect to happen?

install brew

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
n/a
```

**Comment by dduugg** [comment]
Looks similar to https://github.com/Homebrew/brew/issues/17609

Does this resolve the issue for you? https://github.com/Homebrew/brew/issues/17609#issuecomment-2202057406

**Comment by robertsanseries** [comment]
@dduugg 

I've been facing the same "hanging brew update" issue and tried all the usual solutions mentioned in the responses so far, including:

- Turning off my firewall — no change
- Using a proxy server — brew update just failed to start fetching repositories
- Modifying the TMP_FETCH_FAILURES file/directory — no change
- Running git remote-https origin https://github.com/Homebrew/homebrew-core — the command hung
- Restarting macOS — no change
- Running brew cleanup, brew autoremove — unrelated attempts, but no change in the behavior of brew update
- Running brew doctor — no change

After trying everything, the only thing that worked for me was running the following commands:

```shell
export HOMEBREW_NO_INSTALL_FROM_API=1
brew tap homebrew/core
brew tap homebrew/cask
```

These commands seem to have resolved the issue, and now brew update is working as expected.

I hope this helps others who are experiencing the same problem!

**Comment by ZhongRuoyu** [comment]
@robertsanseries, if you are in Brazil, the problem is likely with your connectivity to GitHub Pages -- see https://github.com/orgs/community/discussions/143145 for further details. Unfortunately it is an issue with GitHub, not within Homebrew's control.
