### ISSUE TITLE
Lockfile Concept Exist?

### ISSUE THREAD

**Issue by nmccready** [Homebrew/brew#1880]
Thanks for all that you do! First I am trying to see if the feature below already exists. (I tried searching issues and the docs. So sorry in advanced if this has been answered.)

In many package managers like node or even bundle a lock file of versions exists to keep integrity of versions. Anyway is there any concept of this in existence in brew? Basically I want to able to lock down certain libs like `vips`, and `poppler`. As they easily break node dependent libraries when updated (like poppler-simple). 

I am looking for a way to lock down vips and poppler in /usr/local/bin and cellar so that I can blindly do `brew update` and not go through back track hell.

**Comment by alyssais** [comment]
You can `brew pin vips poppler` and `brew upgrade` will skip them.

**Comment by MikeMcQuaid** [comment]
(unless something else depends on them in which case it'll `brew upgrade` them anyway).

If you need to lock everything down you need to maintain all those formulae in your own tap.

**Comment by nmccready** [comment]
@alyssais perfect thank you.
