### ISSUE TITLE
Allow `brew bump-formula-pr` to create draft PRs

### ISSUE THREAD

**Issue by rgoldberg** [Homebrew/brew#18807]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Allow `brew bump-formula-pr` to create draft PRs by supporting a `--draft` flag.

### What is the motivation for the feature?

This would allow automated release workflows to submit a formula bump to `homebrew-core`, but ensure that maintainers do not approve or merge it before the releaser is ready.

This allows a releaser / automated release process to detect formula bump problems while, e.g., a GitHub Release is still a draft. The releaser / automated release process can inspect, then potentially fix, then publish a release for a validated draft, then change the `homebrew-core` PR from a draft to an actual submission.

If a release suffers from unfixable problems, then the formula bump draft PR can be closed without fear of it having been approved, while, e.g., the GitHub Release draft can be deleted.

### How will the feature be relevant to at least 90% of Homebrew users?

It won't be directly used by users, but rather mainly by developers who bump the formula for new releases of their own software.

It seems useful & relatively easy-to-implement.

### What alternatives to the feature have been considered?

- Creating a non-draft bump PR while a new release is still only a draft, then using `gh pr ready --undo` or equivalent to convert the PR to a draft PR.

- Creating a non-draft bump PR only after publishing a new release.

**Comment by MikeMcQuaid** [comment]
Passing on this for now just because:
- it's the first time we've had this ask and we want to have a few more before such things
- it can be done manually or after the fact without needing our tooling
- we'd like to avoid PRs being created on homebrew/core if they are not yet ready to be merged

Sorry and thanks anyway!

**Comment by rgoldberg** [comment]
@MikeMcQuaid No problem. Thanks for reading the suggestion.

Would you mind if the mas release process creates a bump pr in `homebrew-core`, then immediately changes it to a draft, so that we can ensure that our bump doesn't completely fail while our GitHub Release is a draft, before we publish the GitHub Release draft as a release? Or do you much prefer that we never open a `homebrew-core` draft PR, and instead only open a non-draft `homebrew-core` PR after we've published our GitHub Release?

Any `homebrew-core` PR would be a draft only long enough for the mas releaser to review (& to possibly reword) the autogenerated release notes and to ensure that there are no other release issues in our GitHub Release draft. I imagine that should normally take only 15 or so minutes max.

If the mas releaser proceeds with publishing the GitHub Release draft as a release, then our process would automatically change the `homebrew-core` bump PR from a draft to a non-draft PR.

If the mas releaser aborts the GitHub Release draft, then our process would automatically close the `homebrew-core` bump draft PR.

**Comment by MikeMcQuaid** [comment]
> Or do you much prefer that we never open a `homebrew-core` draft PR, and instead only open a non-draft `homebrew-core` PR after we've published our GitHub Release?

This. It would be better to only create PRs after the release, not before, to avoid unnecessary noise/failures/CI time on our end.

> If the mas releaser aborts the GitHub Release draft, then our process would automatically close the `homebrew-core` bump draft PR.

This is undesirable, definitely want to avoid it being created in this case instead.

**Comment by rgoldberg** [comment]
@MikeMcQuaid Thanks for info. Will follow your procedure: no draft, just a normal bump PR after we've successfully published a GitHub Release to the public.

**Comment by MikeMcQuaid** [comment]
@rgoldberg Thanks!
