### ISSUE TITLE
Intro documentation, please make this more accessible for beginners

### ISSUE THREAD

**Issue by plastikfan** [Homebrew/brew#18817]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

(I did consider starting a new discussion, but this seemed to be incorrect forum for raisng the issue I'm presenting, because it doesn't relate to a specific technical issue, but instead is requesting that documentation is updated)

I have been using homebrew now for a number of years, but I have been doing so without really understanding the fundamentals of what's going on (I know how to use it and get by without fully understanding it). Don't get be wrong, I love open source and I really appreciate the work that projects like homebrew do for the community.

The problem I have is the terminology. I know that on your github page, there is a link that points to a table showing the [terminology](https://docs.brew.sh/Formula-Cookbook#homebrew-terminology), but a lot of the terms described here still don't make sense when you are a beginner. The reason why this came up now for me is that I used chat gpt to explain what the difference was in the 2 different approaches for installing a package (carapace):

1:
> brew install carapace

2:
> brew tap rsteube/homebrew-tap
> brew install rsteube/tap/carapace

and this was the response:

Method 1: Direct Install

> brew install carapace

This method attempts to install carapace directly from the main Homebrew repository (also known as the core repository). However, it's important to note that carapace is not currently available in the core Homebrew repository

Method 2: Tap and Install

> brew tap rsteube/homebrew-tap
> brew install rsteube/tap/carapace

This method is the correct way to install carapace using Homebrew. Here's why:

    Tapping a Custom Repository: The brew tap command adds a custom repository (in this case, rsteube's repository) to your Homebrew installation
    . This repository contains the formula for carapace.
    Installing from the Custom Tap: After tapping, you can install carapace from this custom repository. This ensures you're getting the package from its official source.

These descriptions just lit up light bulbs in my mind and it just made perfect sense instantly as opposed to the terse and meaningless descriptions provided on the github homepage. Needless to say, I ran chatgpt on many of the other concepts and I now have a very clear understanding on homebrew, in just a few minutes and I wish that this information was available to me, many years ago when I first started using homebrew.

This is just meant to be constructive criticism that aims to achieve some update in the docs, that presently feels like its aimed at people who already know about homebrew, which does seem odd.

### What is the motivation for the feature?

Poor initial documentation from the perspective of a new user

### How will the feature be relevant to at least 90% of Homebrew users?

This is for the purposes of allowing new users to understand the basics of homebrew from first principles, which is essential for productive use of homebrew, so that a user can recognise for themselves when issues occur and how to resolve them when they do. And I would hazard a guess that there are many other users in my category, who know how to use homebrew but not really understand it properly.

### What alternatives to the feature have been considered?

Using chatgpt was required to get intelligable answers to common initial queries, but I don;t think I should have needed to resort to chatgpt. This information could easily have been provided in the homebrew documentation. To me whats already there is not adequate; I have been using homebrew for years, under a cloud of confusion because of this. The example I provided relating to the installation of carapace is a perfect illustration of this point.

**Comment by MikeMcQuaid** [comment]
We'll always review and probably accept pull requests that attempt to make the documentation clearer. As-is, though, this issue isn't actionable so: passing for now, sorry.

**Comment by plastikfan** [comment]
@ZhongRuoyu, you are missing my point. The point of me asking chat gpt was to understand what a cask, tap, formula are, not how to install carapace. I said this in my original post. The point was your terse explaination of fundamental concepts is poor at best. I was only using chat-gpt to get a better explanation of concepts, not carapace. I thought I made this clear.

I'll consider opening a pull request, but first I would like to understand what the pre-conditions for pull requests for documentation. I am more than will to contribute, on the proviso that contributions will genuinely be considered for acceptance as opposed to being shutdown with no feedback.

**Comment by gromgit** [comment]
In my experience as a third party, the only documentation PRs that have ever been silently closed are the nonsense ones (bot-driven or otherwise). All others have been commented on before acceptance, rejection, or suggestions for improvement.

**Comment by MikeMcQuaid** [comment]
@plastikfan The only real condition for a documentation PR to be merged is that the changes are correct, agreed to be an improvement (this can be more debatable) and meets our Prose Style Guidelines (https://docs.brew.sh/Prose-Style-Guidelines) and any other automated checks.

Just to take a step back: please remember we're a volunteer run open source project over here. We want to improve things but we also need you to try and operate with a high level of patience and grace. In this thread, @ZhongRuoyu is trying to help you but, instead of saying "thanks" you've been pretty critical. This makes others less inclined to help you in future.

**Comment by plastikfan** [comment]
Ok fare enough I accept the criticism but I was frustrated. The whole point of me making this contribution was trying to tear down the barriers that I see from a beginner's perspective. I can't believe I have been using homebrew now for years in a cloud of confusion and all it took for me to remedy this was a clearer explanation of terms. I can't remember how many times I have tried to research this just to be fobbed off by just look at the docs type of comment.

**Comment by MikeMcQuaid** [comment]
> Ok fare enough I accept the criticism but I was frustrated.

I get that but: taking your frustration out on volunteers who spend their free time building stuff for you to use for free is not a good way of handling your frustration.

> I can't remember how many times I have tried to research this just to be fobbed off by just look at the docs type of comment.

No-one was trying to fob you off. The docs are the best we've tried to make them. Can they be improved? Sure but that requires specifics which we aren't able to glean from overly broad feedback and are best addressed in PRs.
