### ISSUE TITLE
Calling brew audit is disabled!

### ISSUE THREAD

**Issue by anumethod** [Homebrew/brew#18873]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
admin@ghs ~ % brew config
HOMEBREW_VERSION: 4.4.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2e780004c92f16a96036d3d43569c2924c4e54f5
Last commit: 2 days ago
Branch: stable
Core tap JSON: 04 Dec 18:47 UTC
Core cask tap JSON: 04 Dec 18:47 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.47.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I was trying to run `brew audit`

### What happened (include all command output)?

`admin@ghs ~ % brew audit
==> Installing 'bundler' gem
Fetching bundler-2.5.20.gem
Fetching gem metadata from https://rubygems.org/.......
Fetching bindata 2.5.0
Fetching public_suffix 6.0.1
Fetching concurrent-ruby 1.3.4
Fetching plist 3.7.1
Installing bindata 2.5.0
Installing public_suffix 6.0.1
Fetching rexml 3.3.9
Fetching ruby-macho 4.1.0
Installing concurrent-ruby 1.3.4
Installing plist 3.7.1
Fetching sorbet-runtime 0.5.11670
Fetching warning 1.4.0
Installing rexml 3.3.9
Fetching addressable 2.8.7
Installing ruby-macho 4.1.0
Fetching elftools 1.3.1
Installing sorbet-runtime 0.5.11670
Installing warning 1.4.0
Installing addressable 2.8.7
Installing elftools 1.3.1
Fetching patchelf 1.5.1
Installing patchelf 1.5.1
Bundle complete! 38 Gemfile dependencies, 12 gems now installed.
Bundled gems are installed into `../../opt/homebrew/Library/Homebrew/vendor/bundle`
Error: Calling brew audit is disabled! Use brew audit --eval-all or HOMEBREW_EVAL_ALL instead.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
`

### What did you expect to happen?

I expected some answers to why `sudo brew services start [Any given Formulae]` returns an error stating `Error: Need to download https://formulae.brew.sh/api/formula.jws.json but cannot as root! Run `brew update` without `sudo` first then try again.`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
admin@ghs ~ % brew audit --eval-all
Error: No matching formulae or casks to audit!

admin@ghs ~ % brew doctor
Your system is ready to brew.
admin@ghs ~ % brew update
==> Updating Homebrew...
Already up-to-date.
admin@ghs ~ % brew update
==> Updating Homebrew...
Already up-to-date.
admin@ghs ~ % brew audit               
Error: Calling brew audit is disabled! Use brew audit --eval-all or HOMEBREW_EVAL_ALL instead.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
admin@ghs ~ % brew config
HOMEBREW_VERSION: 4.4.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2e780004c92f16a96036d3d43569c2924c4e54f5
Last commit: 2 days ago
Branch: stable
Core tap JSON: 04 Dec 18:47 UTC
Core cask tap JSON: 04 Dec 18:47 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.47.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false
```

**Comment by MikeMcQuaid** [comment]
Please try to reinstall Homebrew.
