### ISSUE TITLE
brew --version doesn't return the current version when run as root

### ISSUE THREAD

**Issue by kluppy** [Homebrew/brew#18907]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
% brew config
HOMEBREW_VERSION: 4.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad356d365837a691a52dfec32b3fb5f282f3aefc
Last commit: 13 hours ago
Branch: stable
Core tap JSON: 09 Dec 21:59 UTC
Core cask tap JSON: 09 Dec 21:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Trying to check the current version of homebrew from package management system which runs as root.

### What happened (include all command output)?

```
% sudo brew --version
Homebrew >=4.3.0 (shallow or no git repository)
```

### What did you expect to happen?

```
% brew --version 
Homebrew 4.4.11
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
% sudo brew --version
```

**Comment by Bo98** [comment]
Homebrew uses `git -C "$(brew --repo)" rev-parse --short --verify --quiet HEAD` to get version information. If you run that manually under sudo, you may get a better error for the issue you face.
