### ISSUE TITLE
brew.sh website search broken, please fix

### ISSUE THREAD

**Issue by checktext00** [Homebrew/brew#18905]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

change/upgrade the Algolia search feature on the [brew.sh](https://brew.sh/) website, and add a static search results page (ie. when pressing enter it should take you to a search results page)

### What is the motivation for the feature?

the Algolia search feature on the website doesn't show search results the first time when typing a search term, you usually have to delete a character or a couple of characters and retype what you want to find.

This is ok on a good internet connection with a good computer, but on mobile, or on a slow connection, it just won't show any results. There should be an option to press "enter" or click a "search" button to get a static list of search results, that would solve the problem. 

here's a video:

https://github.com/user-attachments/assets/7c127823-eb64-4178-b2a5-ed1bc26e86fc

### How will the feature be relevant to at least 90% of Homebrew users?

people want to search

### What alternatives to the feature have been considered?

getting a better search plugin from Algolia or another provider that can do real-time results without this issue

**Comment by apainintheneck** [comment]
> the Algolia search feature on the website doesn't show search results the first time when typing a search term, you usually have to delete a character or a couple of characters and retype what you want to find.

I'm not able to reproduce this locally on Safari or Firefox. Has anyone else run into this problem before?

https://github.com/user-attachments/assets/ffd5485f-9519-4d71-b5ff-4224bd3990fb

**Comment by MikeMcQuaid** [comment]
> but anyway it should be an easy fix to add a static search results page

If it's easy: please submit a PR and we'll review it, thanks!

**Comment by checktext00** [comment]
> > but anyway it should be an easy fix to add a static search results page
> 
> If it's easy: please submit a PR and we'll review it, thanks!

I don't know how to code, I'm just bringing this issue to your attention. If you don't believe it's an issue because you can't reproduce it, I can recommend connection with a slower/higher latency internet connect (you could try setting connection speed limits in a virtual machine, or connecting to brew.sh using Tor)

**Comment by MikeMcQuaid** [comment]
> I don't know how to code

Then you may want to refrain from suggesting things will be easy fixes.
