### ISSUE TITLE
`brew list` output should show fully qualified names for formulae not from Homebrew Core

### ISSUE THREAD

**Issue by vassudanagunta** [Homebrew/brew#18908]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

`brew list` can output misleading formula names when the installed formula is not from Homebrew Core. For example, both `fq` and `wader/tap/fq` will show as "fq".

`brew list` should output fully qualified names when the formula is not from Homebrew Core, such as output by `brew bundle dump --file -`.

### What is the motivation for the feature?

I needed to create a command that listed all the items I installed via brew along with their descriptions (my memory is bad). I tried the following:

```bash
brew desc $(brew list --installed-on-request) | column -t -s ":"
```

I was very confused because the description for `fq` was not something I would have installed. It turns out, it was the description for Homebrew Core's `fq`, not for the `wader/tap/fq` I had installed.

### How will the feature be relevant to at least 90% of Homebrew users?

The point of `brew list` is to show a list of installed formulae. This can be misleading, especially if the user executes other commands using that name, e.g. `brew desc` or `brew info`.

For example, [this Stack Exchange answer](https://apple.stackexchange.com/a/387944/263076) gives incorrect results if you have installed non-Homebrew Core formulae.

### What alternatives to the feature have been considered?

I created a workaround for `brew list --installed-on-request`:

```bash
brew bundle dump --file - | grep '^brew \"' | sed -E 's/brew \"(.+)\"/\1/g'
```

I then incorporated it in my desired listing of my installations with descriptions: 

```bash
brew desc $(brew bundle dump --file - | grep '^brew \"' | sed -E 's/brew \"(.+)\"/\1/g') | column -t -s ":" | sort
```

This correctly shows the description for the actual "fq" that I installed. Though this output *also* does not show its fully-qualified name.

I presume there would be a workaround for the general `brew list` command as well, though I haven't had a need to figure it out.  I don't know if a workaround is possible for all the options supported by `brew list`.

**Comment by MikeMcQuaid** [comment]
`brew list --full-name` outputs in the format you'd like. We won't be adjusting the `brew list` default output to avoid breaking backwards compatibility.

**Comment by vassudanagunta** [comment]
My bad that I missed the `--full-name` option.

That said, when I use `--full-name` with `--installed-on-request`, I get the following:

```
Error: Invalid usage: Options --full-name and --installed-on-request are mutually exclusive.
```

For example, this command won't work:
```
brew desc $(brew list --full-name --installed-on-request) | column -t -s ":"
```

...and the version without `--installed-on-request` will blow up the output with dependencies that I don't want to see,

...and the version without `--full-name` will give incorrect results as I mentioned up top.

If this could be fixed, I could open a new issue. Let me know.

**Comment by ZhongRuoyu** [comment]
@vassudanagunta, now that #18913 is merged, it's possible to run `brew list --full-name --installed-on-request`. If you have developer mode switched on, you can try it now after doing `brew update`. Otherwise, you'll get the update as part of the next stable release.

**Comment by wader** [comment]
Hey, author of fq and "wader/tap/fq" here 👋 This confusion has happen a few times and i've also been asked for a an non-tap formula for fq. If I or someone else would like to create a non-tap formula how does homebrew usually handle formula name and binary name collision for official formulas?

**Comment by wader** [comment]
Sorry should have been clearer. I meant if there is a formula naming convention when two different projects share a name, ex should my fq's formula be named fq-<something> etc? and what if both formulas want to install a binary with same name?

**Comment by MikeMcQuaid** [comment]
> I meant if there is a formula naming convention when two different projects share a name, ex should my fq's formula be named fq- etc?

No fixed convention although if you want them both installed side-by-side you probably want to rename your one to `fq-$SOMETHING`.

> and what if both formulas want to install a binary with same name?

They will have to have `conflicts_with` or one/both will need to be `keg_only`.
