### ISSUE TITLE
Warning: No Cask quarantine support available: unknown reason.

### ISSUE THREAD

**Issue by nodesocket** [Homebrew/brew#18952]
### `brew doctor` output

```shell
MacBook-Pro ➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: No Cask quarantine support available: unknown reason.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3001afe88112c13b5aafdd92e097680897060881
Last commit: 2 days ago
Branch: stable
Core tap JSON: 18 Dec 02:54 UTC
Core cask tap JSON: 18 Dec 02:54 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: subl -w
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.47.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.2-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Running `brew doctor`

### What happened (include all command output)?

What does the warning: `No Cask quarantine support available: unknown reason.` mean?

### What did you expect to happen?

No warning shown `No Cask quarantine support available: unknown reason.`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
macOS 15.2 (24C101)
```

**Comment by carlocab** [comment]
> Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

**Comment by Bo98** [comment]
> What does the warning: `No Cask quarantine support available: unknown reason.` mean?

Usually either:

* A corrupt CLT install. Try delete yours and reinstall from developer.apple.com.
* An incompatibility specific to OpenCore (if you're using that)
