### ISSUE TITLE
Add brew cask: Davinci Resolve by blackmagic

### ISSUE THREAD

**Issue by ab12gu** [Homebrew/brew#18960]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I wanted to reopen the discussion for creating a cask for davinci-resolve?
It's been almost a decade since it was discussed and ignored. 

Is the issue then still pertinant? Would it be worth me making a formula for it?
https://github.com/Homebrew/homebrew-cask/pull/8753
https://github.com/Homebrew/homebrew-cask/issues/33251

### What is the motivation for the feature?

The most common free video editing software.

### How will the feature be relevant to at least 90% of Homebrew users?

Introducing a very common installation application that many users would love to add to their brew cask install.

### What alternatives to the feature have been considered?

None

**Comment by carlocab** [comment]
Please open a pull request at [Homebrew/cask](https://github.com/Homebrew/homebrew-cask) to add it if the concern at https://github.com/Homebrew/homebrew-cask/issues/33251#issuecomment-298216965 no longer applies.
