### ISSUE TITLE
CLT detection fails, even if Xcode installed

### ISSUE THREAD

**Issue by process** [Homebrew/brew#18976]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3001afe88112c13b5aafdd92e097680897060881
Last commit: 6 days ago
Branch: stable
Core tap JSON: 21 Dec 09:31 UTC
Core cask tap JSON: 21 Dec 09:31 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.2-arm64
CLT: N/A
Xcode: 16.2
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew upgrade`

### What happened (include all command output)?

```
 % brew upgrade
==> Upgrading 3 outdated packages:
python@3.12 3.12.7_1 -> 3.12.8
awscli 2.18.2 -> 2.22.22
gcc 14.2.0 -> 14.2.0_1
Error: python@3.12: the bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install

If you're feeling brave, you can try to install from source with:
  brew install --build-from-source python@3.12

It is expected behaviour that most formulae will fail to build from source.
It is expected behaviour that Homebrew will be buggy and slow when building from source.
Do not create any issues about failures building from source on Homebrew's GitHub repositories.
Do not create any issues building from source even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help building from source in Homebrew's discussions but are unlikely to receive a response.
If building from source fails, try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
==> Downloading https://ghcr.io/v2/homebrew/core/awscli/manifests/2.22.22
Already downloaded: /Users/justin/Library/Caches/Homebrew/downloads/661009034b4916322d1d2aff939d38ffa1c8e3600d3e455b90852eccf73b5fa2--awscli-2.22.22.bottle_manifest.json
==> Fetching dependencies for awscli: pkgconf and python@3.12
==> Downloading https://ghcr.io/v2/homebrew/core/pkgconf/manifests/2.3.0_1-1
Already downloaded: /Users/justin/Library/Caches/Homebrew/downloads/4a660f26297baafd06fb3109f473edfa592f4aa00adbd8a2506b05d0374c5c1d--pkgconf-2.3.0_1-1.bottle_manifest.json
==> Fetching pkgconf
==> Downloading https://ghcr.io/v2/homebrew/core/pkgconf/blobs/sha256:6b946f8b716f639a88b6fb05fadf57de8309a53d04d4daef93dda1365f0222e3
Already downloaded: /Users/justin/Library/Caches/Homebrew/downloads/e6b0ced15213e02c1914d4dfc12d9fc60b77cca3b997b96a70e44106a6ef239d--pkgconf--2.3.0_1.arm64_sequoia.bottle.1.tar.gz
Error: python@3.12: the bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install

If you're feeling brave, you can try to install from source with:
  brew install --build-from-source python@3.12

It is expected behaviour that most formulae will fail to build from source.
It is expected behaviour that Homebrew will be buggy and slow when building from source.
Do not create any issues about failures building from source on Homebrew's GitHub repositories.
Do not create any issues building from source even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help building from source in Homebrew's discussions but are unlikely to receive a response.
If building from source fails, try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
Error: gcc: the bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install

If you're feeling brave, you can try to install from source with:
  brew install --build-from-source gcc

It is expected behaviour that most formulae will fail to build from source.
It is expected behaviour that Homebrew will be buggy and slow when building from source.
Do not create any issues about failures building from source on Homebrew's GitHub repositories.
Do not create any issues building from source even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help building from source in Homebrew's discussions but are unlikely to receive a response.
If building from source fails, try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

### What did you expect to happen?

I expect it to upgrade those packages.
I have Xcode installed, and the command line tools are available from that. I do not have the tools at `/Library/Developer/CommandLineTools`.

The problem appears to be at this line of xcode.rb, in `detect_clang_version`: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac/xcode.rb#L407
This code assumes that clang is installed in /Library, but this isn't true for Xcode users.

This change was introduced in this commit: https://github.com/Homebrew/brew/commit/b58fa4ebb1e6b918d8556cba629cb55b79d423f5

**Editing `xcode.rb` and removing the use of `PKG_PATH` fixes it for me, but I realize that will probably break other users.**

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Install Xcode.
Remove /Library/Developer/CommandLineTools.
Verify that the command line utils are available from Xcode: `xcode-select -p`.
Install any package that requires CLT, like Python@3.12.
```

**Comment by carlocab** [comment]
This is intentional. When Homebrew says it needs the CLT, it means that it needs the Xcode CLT installed at
```
/Library/Developer/CommandLineTools
```
Having dev tools provided by an Xcode.app installation does not suffice.

**Comment by process** [comment]
Thanks for the quick error update! I will say I'm a bit surprised that this is the case. Poking around in Xcode.app, it looks like the tools provided there are a _superset_ of the ones provided by the "Xcode CLT" package. I don't have proof of this, but I looked at the file listings in both.

The reason why I bring this up is because having the Xcode CLT installed requires an additional 1.7GB of storage, which seems a bit heavy when Xcode already takes up so much space on its own.

Is there something specific that's needed from the CLT, or is this just a sanity-driven design decision for Homebrew?

**Comment by carlocab** [comment]
> Is there something specific that's needed from the CLT, or is this just a sanity-driven design decision for Homebrew?

We need:
1. the right SDK (i.e. one with the version matching your OS)
2. at a known installation path (because paths get baked into binaries for some formulae)

For macOS versions that aren't the latest release, only the CLT at `/Library/Developer/CommandLineTools` meets the first requirement. Xcode.app will typically always only contain the SDK for the newest version of macOS. For example, Xcode.app 16 contains only `MacOSX15.2.sdk`.

Xcode.app also cannot be relied on to meet the second requirement. It can be installed anywhere on disk, and does not have a fixed canonical location.

If you don't want to install the CLT, you can try:
- building the relevant formulae from source; or
- using the `--force-bottle` flag (i.e. `brew install --force-bottle`)

Note that neither option is supported. The first option will usually work, but takes time and can often fail for arbitrary reasons. The second option will cause you issues as soon as you touch a code path that requires one of the two requirements I stated above. (Example: try compiling anything with `gcc-14` or `g++-14`)

**Comment by process** [comment]
Got it. Thanks for the explanation! Today I learned.
In those cases, the Homebrew requirements indeed make a lot of sense 👍
