### ISSUE TITLE
Interactive search in install

### ISSUE THREAD

**Issue by CodeWithShreyans** [Homebrew/brew#18991]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

A flag for `brew install` that uses the same functionality as `brew search` but lets you interactively select the package you want to install.

### What is the motivation for the feature?

In all my years of using brew, I often need to do `brew search xyz` to find the particular package name before doing `brew install xyz-manager` after learning the exact package name.

### How will the feature be relevant to at least 90% of Homebrew users?

I haven't surveyed anyone, but I think many people would have this issue. Maybe it can be checked through telemetry?

### What alternatives to the feature have been considered?

Just doing `brew search` or even slower — going to the website or Google.

**Comment by CodeWithShreyans** [comment]
I could work on this, not very versed with Ruby so will need some direction but from what I could understand I would need to use functions from `Library/Homebrew/search.rb` and imitate what's being done in `Library/Homebrew/cmd/search.rb` in `Library/Homebrew/cmd/install.rb`.

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry. It's a good fit for an external command.

**Comment by CodeWithShreyans** [comment]
wdym external command, like a different cli? In what way could I approach that?

**Comment by MikeMcQuaid** [comment]
https://docs.brew.sh/External-Commands
