### ISSUE TITLE
brew install logstash filebeat elasticsearch vs download

### ISSUE THREAD

**Issue by scheung38** [Homebrew/brew#1900]
$ brew install filebeat

then it runs with 

$ brew services start filebeat 

but where is the filebeat.yml that would have appeared if I had downloaded the filebeat-5.1.2-darwin-x86_65.tar.gz file? If I download the tar.gz file why would I still need install via brew?  Does it mean now I will have two downloaded versions? Which ones to use?

**Comment by MikeMcQuaid** [comment]
> Please replace this section with a brief summary of your issue AND the output of brew config and brew doctor. Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE.md
