### ISSUE TITLE
How to install homebrew offline

### ISSUE THREAD

**Issue by bertalanimre** [Homebrew/brew#1904]
Dear Dev.Team,

I'm having a nightmare installing homebrew but only because I have to install it on a 10.9.1 and 10.9.5 OS X without internet access. I can't even plug them in temporalily.I've tried to follow Wric Gorrs idea (https://groups.google.com/forum/#!topic/homebrew-discuss/A7qUvMtyunw) but that didn't work. 

My main goal is to install qpdf on the machines, and with internet access it is easy. Install homebrew, then brew install qpdf. Now what should I do without internet? I wanted to install homebrew offline, then put the tar.gz fetched with brew on another machine to the cache folder, so when I tell brew to install qpdf it checks the cache and voala.

The problem with that method is: I can download homebrew, I can even put it into /usr/local. But when I want to install with brew install qpdf, it sais "unknown command: install". I've tried to fix it with brew doctor but it didn't help since it also has to access the internet.

I also have Xcode and command line tools installed 6.1.1.

Please assist, it is very urgent for me. :(

Cheers in advance:
Bert

**Comment by vitorgalvao** [comment]
If it’s that urgent and you want just that package, why not just build it directly?

[Download the source](https://downloads.sourceforge.net/project/qpdf/qpdf/6.0.0/qpdf-6.0.0.tar.gz) and move it to your target machine. Unpack it and `cd` into its directory. Then:

```
./configure --prefix='/usr/local' # or wherever
make # might take a bit
make install
```

Easier and faster than trying to bend Homebrew to do something it doesn’t want to.

**Comment by MikeMcQuaid** [comment]
I agree with @vitorgalvao. Homebrew doesn't support this and I'm not sure even where to start.

> Please assist, it is very urgent for me. :(

Gently, your urgency is on you but not on us.

**Comment by bertalanimre** [comment]
It was only for thinking ahead. I could install qpdf from source certenly, but the situation is a little bit complicated. There is this completly offline system with OS Xs allaround. We might need to install other applications as well, and homebrew would be a very easy sollution. I just fetch the tar.gz on an online mac, transfer it via pendrive, compy it to the cache folder and homebew install it. But without it, I have to install everything from souce which is a lot more complicated.

I've solved my issue but I though there is an offline installer for homebrew.

**Comment by DoomHammer** [comment]
A bit of a different angle. Maybe produce a `linuxbrew/linuxbrew` Docker container image with installed components then `docker save` that container image and distribute it to the target machines? This won't be in any way as good as native applications, but it's just a thought that may help you.

**Comment by bertalanimre** [comment]
I was thinking about this as well, but I wish to install as less applications on the client Macs as few I can. So I've sticked to installing it from source. Plus I'm supposed to be just an advisor, their own sysadmin can't do jigsh*t. If I tell him to install docker on the Macs, that would just be another job for me, not him. And I've got better things to do ATM. :factory: 
However, I still think an offline installer for homebrew would make the community more than happy. Since it has the homebrew fetch option to get all the tar.gz what we could need and we can transfer that to other computers without internet access, I think it is a mayor flaw not having an offline install method.

**Comment by vitorgalvao** [comment]
> I still think an offline installer for homebrew would make the community more than happy. 

I disagree. I think most wouldn’t care (as exemplified by the low demand). And as @MikeMcQuaid [mentioned](https://github.com/Homebrew/brew/issues/1904#issuecomment-274863561), he’s “not sure even where to start”. If the lead maintainer is unsure, you can tell this is not an easy task.

> I think it is a mayor flaw not having an offline install method.

It is not, because it’s not part of the goals. That’s like saying it’s a major flaw for cars not go drive underwater — if it’s not part of their design and goal it’s not a flaw, it’s a decision. Same thing with Homebrew.

You’re confusing what you want with what is the goal of the project.

**Comment by MikeMcQuaid** [comment]
> However, I still think an offline installer for homebrew would make the community more than happy.

Sorry, this is the first request we've ever had for this and even if we had many requests it would likely not be worked on due to the combination of the difficulty of implementation and the few users who would use this.

**Comment by bertalanimre** [comment]
Noted. Thank you for your time and help along the way. :+1:
