### ISSUE TITLE
Homebrew does not always output anything about installing packages.

### ISSUE THREAD

**Issue by AraHaan** [Homebrew/brew#1905]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Unfortunately if I output brew config or brew doctor it is not outputting anything even after force reinstalling it using ruby.

Here are some links that fits with this issue (Note this issue happens when running homebrew on an OSX in travis as I don't really own a real OSX, and I cant run my OSX VM's rn until this computer gets it's new CPU for virtualization just to boot the VMs):
https://travis-ci.org/AraHaan/bin2c/jobs/194318992 and https://travis-ci.org/AraHaan/bin2c/jobs/194318994

**Comment by alyssais** [comment]
This isn't a Homebrew bug. Your commands are failing because you haven't capitalised `Darwin`. If you change them to `if [[ "`uname`" == "Darwin" ]]; then…`. They'll work as expected.

**Comment by AraHaan** [comment]
hmm I see now thanks.
