### ISSUE TITLE
Homebrew vs alternate prefix?

### ISSUE THREAD

**Issue by drosehn** [Homebrew/brew#1906]
Hello.  I've been using homebrew on MacOS off-and-on for maybe two years now.  Initially I seemed to have lots of problems with it, but in the last 6-8 months it has worked well for me.  But my latest attempt to upgrade crystal is running into weird problems.  I suspect the root cause is either (a) that I'm running on MacOS 10.10.5 (Yosemite),  or (b) that I want to isolate homebrew to the directory /opt/homebrew.

Here's the relevant info on my installation:
```cr
# sudo brew config
HOMEBREW_VERSION: 1.1.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: e59ada508727f11464595893783beb914c26f60b
Last commit: 30 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 32b9d6937ef4131706b24e9aac4127db746da3e5
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit penryn
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.5.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: N/A
MacPorts/Fink: /opt/local/bin/port
```

```cr
# sudo brew doctor
Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
brew:   exit code: 1
```
I also have the extra wrinkle that the above `brew` command is not the real `brew` command.  It is installed in `/opt/local/bin/brew`, and what it does is change the effective UID and GID to a specific unprivileged account (named `gilbrew`, although I doubt that matters).  It then adds /opt/homebrew/bin to `$PATH`, removes `/usr/local/bin` & `/opt/local/bin` from `$PATH`, and then executes the real version of brew in `/opt/homebrew/bin/brew`.

Now I can read the text which says that homebrew really wants to have `/usr/local` as its prefix, but I've been using that directory for a variety of other things on a variety of systems (linux, freebsd, macos) for the last 20 years, and I'd really like it if homebrew would leave that alone, the same way that `macports` isolates itself to `/opt/local`.  And that's been working fine, until recently.  (although I can't say for sure when problems started to show up).

I guess I'm asking if things are at the point that I have to give `/usr/local` to `brew`, and remove all my other stuff from it?  I do not want multiple package-handling utilities which think they have total control of the same directory.

**Comment by drosehn** [comment]
Oops.  I never did say what problem I'm seeing right now.

I tried to `brew upgrade crystal`, and was told
```cr
Error: autocode not installed
brew:   exit code: 1
```
(it turned out that `brew` really had installed that before the first time I tried this, but I hadn't realized that.  It might have been an older version of autocode, though).  I thought it was odd that it complained but did not install the dependency, so I:
```cr
# sudo brew install autocode
==> Installing dependencies for autocode: node
==> Installing autocode dependency: node
==> Using the sandbox
==> Downloading https://nodejs.org/dist/v7.4.0/node-v7.4.0.tar.xz
Already downloaded: /Users/gilbrew/Library/Caches/Homebrew/node-7.4.0.tar.xz
==> ./configure --prefix=/opt/homebrew/Cellar/node/7.4.0 --without-npm
==> make install
==> Downloading https://registry.npmjs.org/npm/-/npm-4.0.5.tgz
Already downloaded: /Users/gilbrew/Library/Caches/Homebrew/node--npm-4.0.5.tgz
==> ./configure --prefix=/opt/homebrew/Cellar/node/7.4.0/libexec/npm
==> make install
 ...( skipping )...
🍺  /opt/homebrew/Cellar/node/7.4.0: 4,129 files, 46.7M, built in 20 minutes 26 seconds
==> Installing autocode 
==> Downloading https://homebrew.bintray.com/bottles/autocode-1.3.1.yosemite.bot
Already downloaded: /Users/gilbrew/Library/Caches/Homebrew/autocode-1.3.1.yosemite.bottle.1.tar.gz
==> Pouring autocode-1.3.1.yosemite.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/autocode/1.3.1: 4,243 files, 25.8M
```
and then I retried the upgrade:
```cr
# sudo brew upgrade crystal
Error: autocode 1.3.1 already installed
brew:   exit code: 1
```

**Comment by drosehn** [comment]
Before this adventure with crystal, I also ran into odd problems trying to upgrade the version of `ripgrep` I had installed.  But `ripgrep` was just something I wanted to try out and I don't really need it, so when I got into trouble I just `brew pin`-ed the current version and I'll leave it at that.

**Comment by drosehn** [comment]
Side note:  the way I have things set up, nothing **but** `brew` can modify files under `/opt/homebrew`, and `brew` cannot modify any files under `/opt` or `/usr` ( or most other places) **except** for the files under `/opt/homebrew`.  That seemed like a nice idea at the time.

**Comment by MikeMcQuaid** [comment]
Sorry, I'm afraid we only support Homebrew installed in `/usr/local`. You may be able to also get it working in your home directory but we're unable to support heavily customised configurations like yours.

**Comment by drosehn** [comment]
Okay, that's reasonable.  FWIW, I did do a quick test with the homebrew prefix set to `/usr/local`, and both `crystal-lang` and `ripgrep` were installed without any odd behaviors.  Thanks for the quick reply.
