### ISSUE TITLE
Improve error message for "Error: parent directory is world writable but not sticky"

### ISSUE THREAD

**Issue by dlukes** [Homebrew/brew#1907]
Hi everyone,

I know `brew doctor` tells you how to resolve this issue (see e.g. #477), but still:

1. The message is slightly cryptic for someone not that well acquainted with *nix file permissions, plus it's not even clear *which* directory it's about. If a novice encounters it, they may not have the reflex to run `brew doctor` to discover more. I think it would be more newbie-friendly if this error message got expanded to include the guidelines to solve the issue.

2. The advice provided by `brew doctor` is the following:

```
Warning: /tmp is world-writable but does not have the sticky bit set.
Please execute `sudo chmod +t /tmp` in your Terminal.
```

This is true but incomplete, in the sense that you might be on a machine where you don't have an admin account (this is a frequent use case with the https://github.com/Linuxbrew/brew fork of Homebrew, at least for me), in which case you can't fool around with the permissions on `/tmp`, but the issue can still be solved by setting a custom `HOMEBREW_TEMP` . I think it would be a good idea to include this as an alternate fix, both in the output of `brew doctor` and under 1 above -- something along the lines of:

```
Alternatively, point HOMEBREW_TEMP to a directory you control,
e.g. `mkdir ~/tmp; export HOMEBREW_TEMP=~/tmp`.
```

**Comment by MikeMcQuaid** [comment]
> The message is slightly cryptic for someone not that well acquainted with *nix file permissions, plus it's not even clear which directory it's about. If a novice encounters it, they may not have the reflex to run brew doctor to discover more. I think it would be more newbie-friendly if this error message got expanded to include the guidelines to solve the issue.

`brew doctor` instructions exist primarily for maintainers to be able to debug and help people. We've not seen confusion with this messaging. A note that generally when a non-novice thinks a novice will be confused by something they are often not accurate.

> This is true but incomplete, in the sense that you might be on a machine where you don't have an admin account (this is a frequent use case with the https://github.com/Linuxbrew/brew fork of Homebrew, at least for me)

In that case it should be something that's reported to Linuxbrew. We do not support it here and require an admin user.

**Comment by dlukes** [comment]
> We've not seen confusion with this messaging.

Well, that's exactly what #477 was about -- had the error message been more informative, the user wouldn't have had to post an issue. Though admittedly, it may be the case that people only rarely run into this.

> A note that generally when a non-novice thinks a novice will be confused by something they are often not accurate.

Granted, though when I first came across this, I was a novice and it certainly threw me off balance. I had to spend some time digging around in Homebrew sources to even figure out what exactly was wrong, as it didn't occur to me to run  `brew doctor`.

> In that case it should be something that's reported to Linuxbrew. We do not support it here and require an admin user.

OK, thanks, will do :) I thought it might be worthwhile to report this upstream, but maybe it's a pain point only for Linuxbrew.

**Comment by MikeMcQuaid** [comment]
> Well, that's exactly what #477 was about -- had the error message been more informative, the user wouldn't have had to post an issue. Though admittedly, it may be the case that people only rarely run into this.

Sure. That was in July, though. I should have been clearer that we've not seen _widespread_ confusion.

> I thought it might be worthwhile to report this upstream, but maybe it's a pain point only for Linuxbrew.

Thanks.
