### ISSUE TITLE
Automate merging minor changed PR's by a merge robot

### ISSUE THREAD

**Issue by cemo** [Homebrew/brew#1921]
Given the fact that brew is huge and is actively contributed by people, It would be cool to automate merging minor changed formulas. For example:  [this PR] has changed only `sha256` and version part of the `url`. I believe that merging such kind of PR's can be automated. For such a very very minor changes a verification process can be run and than merge it. 

What do you think?

[this PR]: https://github.com/Homebrew/homebrew-core/pull/9298

**Comment by MikeMcQuaid** [comment]
This is something that sounds simple but would be very complex. Additionally, we prefer to have human verification as it doesn't take long.
