### ISSUE TITLE
Feature Request: recommending one of depended modules

### ISSUE THREAD

**Issue by kkdd** [Homebrew/brew#1926]
The following nearly realizes "either lua or lua51 recommended."

```
# the_formula
depends_on "lua" => :recommended if build.without? "lua51"
depends_on "lua51" => :optional
```

But "brew install --with-lua51 the_formula" installs lua51 and lua.

**Comment by DomT4** [comment]
Isn't the problem just that the dependencies are the wrong way around?

```ruby
depends_on "lua51" => :optional
depends_on "lua" => :recommended if build.without? "lua51"
```
Should work fine, no?

**Comment by MikeMcQuaid** [comment]
Assuming @DomT4 is correct.
