### ISSUE TITLE
cannot load such file -- /usr/local/opt/xclip-mode/Homebrew/emacs_formula

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#1927]
After untapping the emacs tap, but still having `xclip-mode` installed, `brew uninstall protobuf` fails with
```
iMac-TMP:~ joe$ brew uninstall protobuf
Error: cannot load such file -- /usr/local/opt/xclip-mode/Homebrew/emacs_formula
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/opt/xclip-mode/.brew/xclip-mode.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `rescue in from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:269:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1425:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1423:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1423:in `installed'
/usr/local/Homebrew/Library/Homebrew/keg.rb:119:in `find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:90:in `check_for_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:83:in `handle_unsatisfied_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:31:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by ilovezfs** [comment]
CC @alyssais @MikeMcQuaid

**Comment by ilovezfs** [comment]
And attempting to uninstall `xclip-mode` itself:
```
iMac-TMP:~ joe$ brew uninstall xclip-mode
Error: cannot load such file -- /usr/local/opt/xclip-mode/Homebrew/emacs_formula
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/opt/xclip-mode/.brew/xclip-mode.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `rescue in from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/keg.rb:343:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/keg.rb:357:in `block (2 levels) in installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:352:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:352:in `any?'
/usr/local/Homebrew/Library/Homebrew/keg.rb:352:in `block in installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:349:in `select'
/usr/local/Homebrew/Library/Homebrew/keg.rb:349:in `installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:107:in `block in find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:105:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:105:in `find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:90:in `check_for_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:83:in `handle_unsatisfied_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:31:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

(Yes, of course, I can cheat with `--ignore-dependencies`)

**Comment by alyssais** [comment]
Initial thoughts at a fix: raise a `FormulaUnavailableError` if something goes wrong while evaluating a formula:

```diff
diff --git a/Library/Homebrew/formulary.rb b/Library/Homebrew/formulary.rb
index 25df57c..07d3df4 100644
--- a/Library/Homebrew/formulary.rb
+++ b/Library/Homebrew/formulary.rb
@@ -22,7 +22,11 @@ class Formulary
 
     mod = Module.new
     const_set(namespace, mod)
-    mod.module_eval(contents, path)
+    begin
+      mod.module_eval(contents, path)
+    rescue ScriptError
+      raise FormulaUnavailableError, name
+    end
     class_name = class_s(name)
 
     begin
```

Maybe we'd want a new kind of exception for this, though? `FormulaUnreadableError`?

**Comment by ilovezfs** [comment]
For abstract formulae (emacs/php/I-don't-know-what-else), would it make sense to copy the abstract formula into the .brew directory too so that it can load?

**Comment by alyssais** [comment]
How would we locate an abstract formula? They could be anywhere.

**Comment by alyssais** [comment]
I guess we could monkey-patch `require` or something in the module they're evaluated in.

**Comment by ilovezfs** [comment]
or grep the formula text for `require File.expand`?

**Comment by alyssais** [comment]
I usually use `require "#{__dir__}/…"`, or `require_relative`, which that wouldn't catch.

**Comment by ilovezfs** [comment]
wonder if there's a way to un-abstract the file so it has all its marbles in place

**Comment by alyssais** [comment]
(And of course somebody could do `send("req" + ("uire" if rand(0.999)), …)` or something ridiculous like that)

**Comment by alyssais** [comment]
> wonder if there's a way to un-abstract the file so it has all its marbles in place

Don't think there is, and `require`'s semantics are pretty convoluted so it'd be difficult to emulate.

**Comment by ilovezfs** [comment]
Or maybe we just don't support the dependency checking for abstract formulae. There's a reason we don't allow this stuff in core.

**Comment by alyssais** [comment]
That would be the easy solution.

**Comment by alyssais** [comment]
If we decided we needed this, here's what I'd do:

- Intercept `require` and `require_relative` calls in formulae when they're installed, and copy those files into `.brew`. Replace the full dirname of those files with some sort of hash of it so we don't have to create a full `/usr/local/Cellar/…` structure in every `.brew` directory.
- Intercept `require` and `require_relative` _again_ when a `.brew` formula is evaluated, and if the normal way fails, replace the dirname with the hash and try to require it from `.brew`.

**Comment by ilovezfs** [comment]
I don't think we can handle all the crazy things third party taps might do with require, but it does seem like we could tailor a solution that specifically targets the php and emacs cases since we know what we're dealing with there. However, I'm not convinced it's worth bothering. The emacs tap is leaving the Homebrew organization and if the PHP formulae come into they'll either be un-abstracted or if they remain abstracted, those files will indeed be available.

**Comment by alyssais** [comment]
Yeah, I think we should just ignore those formulae for now and we can revisit if it becomes a problem again in future.

fwiw the abstract formula approach is also used in Homebrew/portable, which AFAIK isn't going away, but the use case for that is so limited I don't think it's worth doing anything special.

**Comment by ilovezfs** [comment]
It might be worth unraveling it in portable. It's pretty yuck.

**Comment by ilovezfs** [comment]
FormulaUnavailableError sounds fine, though a specific error class for this might be warranted like FormulaUnparsableError or some such thing.

**Comment by alyssais** [comment]
I think so, if only because then we could provide a backtrack for people writing formulae, because it would be hidden otherwise.

**Comment by MikeMcQuaid** [comment]
> Or maybe we just don't support the dependency checking for abstract formulae. There's a reason we don't allow this stuff in core.

I'm fine with that.

> Initial thoughts at a fix: raise a FormulaUnavailableError if something goes wrong while evaluating a formula:

I'm also fine with that.
