### ISSUE TITLE
Commands fail with "Error: stack level too deep"

### ISSUE THREAD

**Issue by novel** [Homebrew/brew#1929]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

`brew doctor` fails with the following:

```
$ brew doctor
Error: stack level too deep
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:48
$ brew upgrade
Updating Homebrew...
Error: stack level too deep
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/tap.rb:28
$
```

- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

This could be a problem with some specific formulae, but as it breaks a lot of generic brew commands, it looks like a bug in brew.

### Bug reports:

Unfortunately, I'm not exactly sure how to reproduce this on a clean install. Last few things I did with brew before paying attention to that:

 - Installed qemu (`brew install qemu`)
 - qemu fails to start:

``` dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/bin/qemu-system-x86_64
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/bin/qemu-system-x86_64
  Expected in: /usr/lib/libSystem.B.dylib

zsh: trace trap  qemu-system-x86_64
```

I did `xcode-select --install` like it's suggested in some similar bug reports, it showed:

```
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
$
```

Then I decided to remove qemu, I did `brew unlink qemu`, then figured out that I should have used 'remove' instead, then I did `brew link qemu` and then `brew remove qemu` and that's probably the first time I saw this error.

Here's a log of `brew remove --debug qemu`:

https://gist.github.com/novel/f9dcce3246047d9711fa8182e02a1e07

Here goes the `brew config` and `brew doctor` output:

```
$ brew config
HOMEBREW_VERSION: 1.1.8-59-gad4fd014
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad4fd014e1e558207d4eecdafe8667ecba5a8f51
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8ee4dfdf1d6ea0d7ee62741b4fdab9afcba6c58b
Core tap last commit: 5 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/opt/git/libexec/git-core/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.3/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
$ brew doctor
Error: stack level too deep
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:48
$
```

**Comment by MikeMcQuaid** [comment]
What's the output of `brew doctor --debug`?

**Comment by novel** [comment]
`brew doctor --debug`: 

https://gist.github.com/novel/2ac59c09c730edf1ec37a60617fc69a8

**Comment by MikeMcQuaid** [comment]
> Core tap HEAD: 8ee4dfdf1d6ea0d7ee62741b4fdab9afcba6c58b
> Core tap last commit: 5 weeks ago

This is a problem. Please try to run `brew update`.

**Comment by novel** [comment]
> This is a problem. Please try to run brew update.

I did that before submitting a report, it doesn't seem to help:

```
$ date
Sun Jan 29 20:05:00 SAMT 2017
$ brew update
Already up-to-date.
$ brew doctor
Error: stack level too deep
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:48
$ cd $(brew --repo) && git rev-parse HEAD
c5072226871196d2eb3265d930daff87968d23e8
$```

Did I mess something up with the repo?

**Comment by MikeMcQuaid** [comment]
Yes, perhaps. Run `brew update-reset`.

**Comment by novel** [comment]
Whee, it did help. I still have issues with `qemu` it seems, but it doesn't seem to be related to this issue, so I'm closing this one. Thanks!

**Comment by MikeMcQuaid** [comment]
Glad you got it sorted.

**Comment by cybertk** [comment]
`brew update-reset` fixed my issue
