### ISSUE TITLE
[FR]Flag for scripting-friendly output of search

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#1935]
Please provide flag like -q in many package managers. When this flag is enabled only list of found packages is provided with no additional info like
```
==> Exact match
...
==> Partial matches
```
So people can then run `brew <action> $(brew search -q <query>)`

**Comment by MikeMcQuaid** [comment]
> So people can then run brew <action> $(brew search -q <query>)

This already works because we detect if it's a TTY.

**Comment by yurikoles** [comment]
Ok, seems to be a bug in cask.
