### ISSUE TITLE
What are the valid version formats?

### ISSUE THREAD

**Issue by caarlos0** [Homebrew/brew#1936]
Hi, I'm the creator of @goreleaser. 

GoReleaser automates the build and release of go projects to github releases and as well to homebrew-taps.

Recently, we started to add fpm support also (https://github.com/goreleaser/goreleaser/pull/109), and doing that, we find out that Debian, for example, won't allow package versions that don't start with a number.

Are there any rules likes this for homebrew too? I wasn't able to find them...

Thanks!

**Comment by MikeMcQuaid** [comment]
You could consider adding support for `brew bump-formula-pr`. We don't have valid version formats documented but we always allow people to fiddle with what Homebrew considers the version to be so it's valid. Ideally all our versions are semantically versioned like `\d+\.\d+\.\d+(-(alpha|beta|rc)\d*)?`
