### ISSUE TITLE
[FR]Combine search and install "I'm fealing lucky"

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#1939]
For example one may want to install <some-long-formula-name-with-three-words> and he can type only one or two words from it's name and do `brew install -s <one-or-two-words>` which will install formula with exact match. 

Inspired by ArchLinux' yaourt package manager, which prompts user with available package names with numbers in front of it and user can install some of them by putting numbers in prompt. It is default behavior for `yaourt word`, which very useful if you feel boring googling for package names and package manager keys.

**Comment by yurikoles** [comment]
@vitorgalvao thanks for correction.

**Comment by vitorgalvao** [comment]
You can accomplish this by using the shell completions. You `brew install <one-or-two-words>`<kbd>⇥</kbd> and it completes the result. Even better, if the thing you typed was ambiguous (i.e. no suitable match) it’ll let you know.

**Comment by yurikoles** [comment]
I mean for packages like google-chrome-* in cask. For example one may just install `brew -s chrome`

**Comment by vitorgalvao** [comment]
```
$ brew search chrome
chrome-cli                               chromedriver
```

I understand your feature request, but frankly can’t picture the core team spending the time to do it. Maybe a PR would be accepted, but even that I’m doubtful.

Though not my decision in the end. Just wanted to make sure first your request couldn’t be accomplished another way.

**Comment by MikeMcQuaid** [comment]
Sorry, this isn't something we'll implement for now. Thanks anyway.
