### ISSUE TITLE
Confused by output of `brew update`

### ISSUE THREAD

**Issue by kenahoo** [Homebrew/brew#1940]
I just ran `brew update` today and it gave me a couple messages I don't understand:

```
% brew update
Updated 4 taps (caskroom/cask, caskroom/versions, homebrew/core, homebrew/science).
...
==> intellij-idea-ce has been moved to Homebrew.
To uninstall the cask run:
  brew cask uninstall --force intellij-idea-ce
==> Installing intellij-idea-ce...
==> brew cask install caskroom/cask/intellij-idea-ce
Warning: A Cask for intellij-idea-ce is already installed and using auto-updates.

To re-install intellij-idea-ce, run:
  brew cask reinstall intellij-idea-ce
==> pycharm-ce has been moved to Homebrew.
To uninstall the cask run:
  brew cask uninstall --force pycharm-ce
==> Installing pycharm-ce...
==> brew cask install caskroom/cask/pycharm-ce
Warning: A Cask for pycharm-ce is already installed.

To re-install pycharm-ce, run:
  brew cask reinstall pycharm-ce
```

What does "has been moved to Homebrew" mean?  Aren't these things already in Homebrew?  Is it supposed to mean "Homebrew Cask"?  Or maybe it used to be a cask but now it's not?

And why does it say "Installing intellij-idea-ce" and "Installing pycharm-ce" if those things are already installed?  Is it moving them to a new location or something?  Or is it asking me to move them myself?

A subsequent `brew update` had no such messages.  Does that mean it's happier now than it was before, it accomplished something it wanted to do?

**Comment by vitorgalvao** [comment]
We’ve done some small tap restructuring in homebrew-cask. Alternative editions (like CEs) used to be in [caskroom/versions](https://github.com/caskroom/homebrew-versions) but are not in the main repo. That output is referring to that.

If something goes wrong try reinstalling those. Otherwise there’s nothing to worry.

**Comment by kenahoo** [comment]
Thanks - I didn't really think there was anything wrong with my install, but I guess I'm wondering whether the message/warning is misleading and could perhaps be improved.  Or if it's a one-time thing and nobody will hit the same thing again, I guess it doesn't matter.
