### ISSUE TITLE
brew outdated is missing cask updates

### ISSUE THREAD

**Issue by AddictArts** [Homebrew/brew#1941]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

brew outdated does not show the outdated cask apps

**Comment by vitorgalvao** [comment]
Because we (HBC) don’t support it yet. See https://github.com/caskroom/homebrew-cask/issues/29301.
