### ISSUE TITLE
'safe' option for update: exit if there are migrations

### ISSUE THREAD

**Issue by julianrendell** [Homebrew/brew#1942]
### Propose a feature:

Could a "safe" mode be added to `update` such that if there are any migrations required the update is cancelled, giving the user a chance to backup the brew installation directory before proceeding?

Or is there a way to list pending migrations before they're executed?

An update in a package that breaks is relatively easy to fix by reverting/editing the brew file.

But a migration seems to be able to relocate a package, rename it, remove it, replace it with a cask, etc. Much harder to unwind.

Although breaks due to migration issues seem to be rare, they're a big time-suck to unravel if they do happen.

Part of it is user expectation; after using package managers like `apt` I've come to assume `update` is non-destructive to the installed application state; i.e. it only changes package meta-data. I'm used to `upgrade` being the destructive step.

If it's not trivial/won't be considered, can some further verbiage be added to the text that @MikeMcQuaid added in  <https://github.com/Homebrew/brew/commit/664d0c67d5947605c914c4c56ebcfaa80cb6eca0>? (Thanks Mike!)

e.g. something like:

> Migrations are internal updates and changes that brew needs to perform. These typically only affect brews internals, but sometimes involve moving and renaming installed formula. There is a chance update can break packages; you may wish to backup the brew installation before updating.

If it's helpful I can make a pull request to add the above (after suggestions/feedback below...) to the files @MikeMcQuaid edited in <https://github.com/Homebrew/brew/commit/664d0c67d5947605c914c4c56ebcfaa80cb6eca0>. 

Specifically:

- `Library/Homebrew/cmd/update.sh`
- `docs/brew.1.html`
- `manpages/brew.1`

Are there any other spots that that could/should be added to?

(I don't have capacity to learn internals/edit code- but text changes I can handle.)

**Comment by MikeMcQuaid** [comment]
Sorry, not running migrations breaks a bunch of internal assumptions we have and I don't want to recommend a backup for this case. Thanks anyway.

**Comment by julianrendell** [comment]
Thanks @MikeMcQuaid. Is it that by doing the (git) update it might require migrations to keep the metadata etc 'sane'? i.e. to detect that there would be migrations, they in effect become mandatory?

If that's the case, I see where you're coming from. 

Would you be against a pull request adding a bit more description re migrations to the docs?

Admittedly, I've only been bitten by a bad migration once... but it proved to be a royal pain to get myself out of.

**Comment by MikeMcQuaid** [comment]
> Thanks @MikeMcQuaid. Is it that by doing the (git) update it might require migrations to keep the metadata etc 'sane'? i.e. to detect that there would be migrations, they in effect become mandatory?

Yes, pretty much. Basically once Git has been updated if e.g. formulae have been renamed or migrated we need to handle that immediately otherwise there's weird errors and messaging that are hard to figure out unless you're a developer (and there's no particularly easy way around them as our e.g. rename and migration system is heavily hooked into Git itself).



> Assuming detection makes the migration mandatory, would you be against a pull request adding a bit more description re migrations to the docs?

That seems reasonable, we can debate the wording there, thanks for the offer ❤️ 



> Admittedly, I've only been bitten by a bad migration once... but it proved to be a royal pain to get myself out of.

The Inkscape one? Just for reference that's a known problem that won't be recurring.
