### ISSUE TITLE
`brew uninstall $pkg` Error: stack level too deep

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#1945]
```
brew uninstall htop
Error: stack level too deep
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/Users/timothee/homebrew/Library/Homebrew/tap.rb:28
```
happens with other packages (not just htop)
doens't happen if I use a fresh homebrew install, so not sure how to give instructions to reproduce

how would i debug this?
would rather not nix my homebrew repo (lots of packages etc)

```
/Users/timothee/homebrew/Library/Homebrew/tap.rb:28
      28     if [user, repo].any? { |part| part.nil? || part.include?("/") }
      29       raise "Invalid tap name '#{args.join("/")}'"
      30     end
```

```
brew --version
Homebrew 1.1.9-2-gb6f3399cb
```
on OSX

adding `--verbose` didn't help

**Comment by MikeMcQuaid** [comment]
Is this Homebrew or Linuxbrew? Try to `brew uninstall --debug htop` and provide your `brew config` and `brew doctor` output as requested by the issue template and please fill out the issue template every time for every issue.

**Comment by ilovezfs** [comment]
@timotheecour did you resolve the mystery?

**Comment by MikeMcQuaid** [comment]
Closing as requested information wasn't provided.
