### ISSUE TITLE
[grib-api] missing binary files *.so

### ISSUE THREAD

**Issue by andrejreznik** [Homebrew/brew#1959]
I successfully installed grib api:
`brew install grib-api`

Then I'm trying import python's module with grib-api bindigs:
`import gribapi`
And I got an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gribapi/gribapi.py", line 31, in <module>
    import gribapi_swig as _internal
  File "/usr/local/lib/python2.7/site-packages/gribapi/gribapi_swig.py", line 25, in <module>
    _gribapi_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/site-packages/gribapi/gribapi_swig.py", line 17, in swig_import_helper
    import _gribapi_swig
ImportError: No module named _gribapi_swig
```

At first, I add installed package to PYTHONPATH:
`export PYTHONPATH="/usr/local/lib/python2.7/site-packages/gribapi":$PYTHONPATH`

But this doesn't work for me.
SO, the, If we are look at grib folder we can see that there is no grib api bin files.
```
/usr/local/lib/python2.7/site-packages/gribapi$ ls 
__init__.py         _gribapi_swig.dylib gribapi.pyc         gribapi_swig.pyc
__init__.pyc        gribapi.py          gribapi_swig.py
```

I found a solution for me.  I just download [build](https://software.ecmwf.int/wiki/display/GRIB/Mac+OS+X+x86_64) add put `_gribapi_swig.so` from archive to this folder.

**Comment by MikeMcQuaid** [comment]
Please fill out the issue template in future which would tell you which repository to file this to. Closing as your problem appears to be solved.
