### ISSUE TITLE
gcc47 dependency cloog@0.15 fails to download

### ISSUE THREAD

**Issue by mrkapqa** [Homebrew/brew#1964]
==> Installing dependencies for gcc@4.7: cloog@0.15
==> Installing gcc@4.7 dependency: cloog@0.15
==> Using the sandbox
==> Downloading ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-ppl-0.15.11.tar.g

curl: (28) Connection time-out
Trying a mirror...
==> Downloading http://gcc.cybermirror.org/infrastructure/cloog-ppl-0.15.11.tar.

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "cloog@0.15"
Download failed: http://gcc.cybermirror.org/infrastructure/cloog-ppl-0.15.11.tar.gz

**Comment by MikeMcQuaid** [comment]
You didn't fill out the issue template so closing.

**Comment by ilovezfs** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/11663.
