### ISSUE TITLE
Shell scripts should use nullglob

### ISSUE THREAD

**Issue by rgov** [Homebrew/brew#1965]
While investigating another issue, I noticed that `brew update --force` was executing this:

    ++ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
    ++ [[ -d /usr/local/Homebrew/Library/Taps/*/*/.git ]]

Since I don't have any taps, the glob is turning into a path containing literal asterisks, which is probably not intentional.

This and other shell scripts in Homebrew should probably turn on `nullglob` at the top: `shopt -s nullglob`

**Comment by MikeMcQuaid** [comment]
> Since I don't have any taps

This itself is unsupported but I can see an argument for setting it for this particular script. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!
