### ISSUE TITLE
Allow skipping the homebrew/core tap

### ISSUE THREAD

**Issue by rgov** [Homebrew/brew#1966]
I'd like to use Homebrew as a package manager in a network isolated environment. I have a private tap which contains some packages that install from the local network, but I am not able to install any of the public formulae. Therefore I'd like to skip tapping `homebrew/core`.

It is easy to patch the `install` script to clone from an internal mirror of Homebrew/brew but when it runs `brew update --force`, which somehow executes `brew tap homebrew/core`.

It looks like it might be the `install_core_tap_if_necessary` function in  `update-report.sh`. Setting `HOMEBREW_UPDATE_TEST=1` in my environment *does* skip tapping core, but this doesn't seem like a well-supported path.

**Comment by rgov** [comment]
If it's absolutely crucial, I'd also settle for being able to point the core tap to a local mirror (or perhaps an empty local repo), but again I can't reach out to the network to obtain any tarballs.

**Comment by rgov** [comment]
As a workaround, I found that I could run `brew tap homebrew/core ssh://some/empty/repo.git`. It doesn't seem to work for a local-only repo, it needs a remote.

**Comment by MikeMcQuaid** [comment]
We'd accept a PR to add a better, documented environment variable which overrides `install_core_tap_if_necessary`. Such things are not going to be widely used by users so we'll need to rely on you scratching your own itch here.
