### ISSUE TITLE
I try brew update I get a strange error:

### ISSUE THREAD

**Issue by cmzz** [Homebrew/brew#1979]
Hi all, when I user brew, user any command I can got this errors: 

git:(master) brew update
Unknown option: n
Unknown option: 1
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output

**Comment by MikeMcQuaid** [comment]
What does `which head` output?

**Comment by cmzz** [comment]
git:(master) brew install php7-xdebug
Unknown option: n
Unknown option: 1
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output
Unknown option: n
Unknown option: 1
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output

**Comment by cmzz** [comment]
@MikeMcQuaid 

git:(master) which head
/usr/bin/head

**Comment by cmzz** [comment]
brew -v
    Unknown option: n
    Unknown option: 1
    Usage: head [-options] <url>...
        -m <method>   use method for the request (default is 'HEAD')
        -f            make request even if head believes method is illegal
        -b <base>     Use the specified URL as base
        -t <timeout>  Set timeout value
        -i <time>     Set the If-Modified-Since header on the request
        -c <conttype> use this content-type for POST, PUT, CHECKIN
        -a            Use text mode for content I/O
        -p <proxyurl> use this as a proxy
        -P            don't load proxy settings from environment
        -H <header>   send this HTTP header (you can specify several)

        -u            Display method and URL before any response
        -U            Display request headers (implies -u)
        -s            Display response status code
        -S            Display response status chain
        -e            Display response headers
        -d            Do not display content
        -o <format>   Process HTML content in various ways

        -v            Show program version
        -h            Print this message

        -x            Extra debugging output
    Homebrew >1.1.0 (no git repository)
    Homebrew/homebrew-core (git revision 1eec4; last commit 2017-01-24)

**Comment by MikeMcQuaid** [comment]
What does `brew config` and `brew doctor` output?

**Comment by cmzz** [comment]
@MikeMcQuaid Thanks for helping.

brew config: 

    ~ brew config
    Unknown option: n
    Unknown option: 1
    Usage: head [-options] <url>...
        -m <method>   use method for the request (default is 'HEAD')
        -f            make request even if head believes method is illegal
        -b <base>     Use the specified URL as base
        -t <timeout>  Set timeout value
        -i <time>     Set the If-Modified-Since header on the request
        -c <conttype> use this content-type for POST, PUT, CHECKIN
        -a            Use text mode for content I/O
        -p <proxyurl> use this as a proxy
        -P            don't load proxy settings from environment
        -H <header>   send this HTTP header (you can specify several)

        -u            Display method and URL before any response
        -U            Display request headers (implies -u)
        -s            Display response status code
        -S            Display response status chain
        -e            Display response headers
        -d            Do not display content
        -o <format>   Process HTML content in various ways

        -v            Show program version
        -h            Print this message

        -x            Extra debugging output
    HOMEBREW_VERSION: >1.1.0 (no git repository)
    ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
    HEAD: 10b8d27d118c5db7ce4293861cded28e8516e849
    Last commit: 3 weeks ago
    Core tap ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
    Core tap HEAD: 1eec4eb51626b95e8747545dc98cd6b7b9df900d
    Core tap last commit: 2 weeks ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local/Homebrew
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: octa-core 64-bit haswell
    Homebrew Ruby: 2.0.0-p648
    Clang: 8.0 build 800
    Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
    Perl: /Applications/XAMPP/bin/perl => /Applications/XAMPP/xamppfiles/bin/perl
    Python: /usr/bin/python
    Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    Java: 1.8.0_121
    macOS: 10.12.3-x86_64
    Xcode: 8.2.1
    CLT: 8.2.0.0.1.1480973914
    X11: N/A


And brew doctor:

    ~ brew doctor
    Unknown option: n
    Unknown option: 1
    Usage: head [-options] <url>...
        -m <method>   use method for the request (default is 'HEAD')
        -f            make request even if head believes method is illegal
        -b <base>     Use the specified URL as base
        -t <timeout>  Set timeout value
        -i <time>     Set the If-Modified-Since header on the request
        -c <conttype> use this content-type for POST, PUT, CHECKIN
        -a            Use text mode for content I/O
        -p <proxyurl> use this as a proxy
        -P            don't load proxy settings from environment
        -H <header>   send this HTTP header (you can specify several)

        -u            Display method and URL before any response
        -U            Display request headers (implies -u)
        -s            Display response status code
        -S            Display response status chain
        -e            Display response headers
        -d            Do not display content
        -o <format>   Process HTML content in various ways

        -v            Show program version
        -h            Print this message

        -x            Extra debugging output
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!

    Warning: "config" scripts exist outside your system or Homebrew directories.
    `./configure` scripts often look for *-config scripts to determine if
    software packages are installed, and what additional flags to use when
    compiling and linking.

    Having additional scripts in your path can confuse software installed via
    Homebrew if the config script overrides a system or Homebrew provided
    script of the same name. We found the following "config" scripts:
      /Applications/XAMPP/bin/apr-1-config
      /Applications/XAMPP/bin/apreq2-config
      /Applications/XAMPP/bin/apu-1-config
      /Applications/XAMPP/bin/curl-config
      /Applications/XAMPP/bin/freetype-config
      /Applications/XAMPP/bin/gdlib-config
      /Applications/XAMPP/bin/icu-config
      /Applications/XAMPP/bin/libmcrypt-config
      /Applications/XAMPP/bin/libpng-config
      /Applications/XAMPP/bin/libpng15-config
      /Applications/XAMPP/bin/ming-config
      /Applications/XAMPP/bin/ncurses5-config
      /Applications/XAMPP/bin/pcre-config
      /Applications/XAMPP/bin/php-config
      /Applications/XAMPP/bin/sablot-config
      /Applications/XAMPP/bin/xml2-config
      /Applications/XAMPP/bin/xslt-config

    Warning: Python is installed at /Library/Frameworks/Python.framework

    Homebrew only supports building against the System-provided Python or a
    brewed Python. In particular, Pythons installed to /Library can interfere
    with other software installs.

    Warning: Unbrewed header files were found in /usr/local/include.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected header files:
      /usr/local/include/node/android-ifaddrs.h
      /usr/local/include/node/ares.h
      /usr/local/include/node/ares_build.h
      /usr/local/include/node/ares_rules.h
      /usr/local/include/node/ares_version.h
      /usr/local/include/node/libplatform/libplatform.h
      /usr/local/include/node/libplatform/v8-tracing.h
      /usr/local/include/node/nameser.h
      /usr/local/include/node/node.h
      /usr/local/include/node/node_buffer.h
      /usr/local/include/node/node_object_wrap.h
      /usr/local/include/node/node_version.h
      /usr/local/include/node/openssl/aes.h
      /usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
      /usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
      /usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
      /usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
      /usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
      /usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
      /usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
      /usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
      /usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
      /usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
      /usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
      /usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
      /usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
      /usr/local/include/node/openssl/archs/linux32-s390x/opensslconf.h
      /usr/local/include/node/openssl/archs/linux64-s390x/opensslconf.h
      /usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
      /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
      /usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
      /usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
      /usr/local/include/node/openssl/asn1.h
      /usr/local/include/node/openssl/asn1_mac.h
      /usr/local/include/node/openssl/asn1t.h
      /usr/local/include/node/openssl/bio.h
      /usr/local/include/node/openssl/blowfish.h
      /usr/local/include/node/openssl/bn.h
      /usr/local/include/node/openssl/buffer.h
      /usr/local/include/node/openssl/camellia.h
      /usr/local/include/node/openssl/cast.h
      /usr/local/include/node/openssl/cmac.h
      /usr/local/include/node/openssl/cms.h
      /usr/local/include/node/openssl/comp.h
      /usr/local/include/node/openssl/conf.h
      /usr/local/include/node/openssl/conf_api.h
      /usr/local/include/node/openssl/crypto.h
      /usr/local/include/node/openssl/des.h
      /usr/local/include/node/openssl/des_old.h
      /usr/local/include/node/openssl/dh.h
      /usr/local/include/node/openssl/dsa.h
      /usr/local/include/node/openssl/dso.h
      /usr/local/include/node/openssl/dtls1.h
      /usr/local/include/node/openssl/e_os2.h
      /usr/local/include/node/openssl/ebcdic.h
      /usr/local/include/node/openssl/ec.h
      /usr/local/include/node/openssl/ecdh.h
      /usr/local/include/node/openssl/ecdsa.h
      /usr/local/include/node/openssl/engine.h
      /usr/local/include/node/openssl/err.h
      /usr/local/include/node/openssl/evp.h
      /usr/local/include/node/openssl/hmac.h
      /usr/local/include/node/openssl/idea.h
      /usr/local/include/node/openssl/krb5_asn.h
      /usr/local/include/node/openssl/kssl.h
      /usr/local/include/node/openssl/lhash.h
      /usr/local/include/node/openssl/md4.h
      /usr/local/include/node/openssl/md5.h
      /usr/local/include/node/openssl/mdc2.h
      /usr/local/include/node/openssl/modes.h
      /usr/local/include/node/openssl/obj_mac.h
      /usr/local/include/node/openssl/objects.h
      /usr/local/include/node/openssl/ocsp.h
      /usr/local/include/node/openssl/opensslconf.h
      /usr/local/include/node/openssl/opensslv.h
      /usr/local/include/node/openssl/ossl_typ.h
      /usr/local/include/node/openssl/pem.h
      /usr/local/include/node/openssl/pem2.h
      /usr/local/include/node/openssl/pkcs12.h
      /usr/local/include/node/openssl/pkcs7.h
      /usr/local/include/node/openssl/pqueue.h
      /usr/local/include/node/openssl/rand.h
      /usr/local/include/node/openssl/rc2.h
      /usr/local/include/node/openssl/rc4.h
      /usr/local/include/node/openssl/ripemd.h
      /usr/local/include/node/openssl/rsa.h
      /usr/local/include/node/openssl/safestack.h
      /usr/local/include/node/openssl/seed.h
      /usr/local/include/node/openssl/sha.h
      /usr/local/include/node/openssl/srp.h
      /usr/local/include/node/openssl/srtp.h
      /usr/local/include/node/openssl/ssl.h
      /usr/local/include/node/openssl/ssl2.h
      /usr/local/include/node/openssl/ssl23.h
      /usr/local/include/node/openssl/ssl3.h
      /usr/local/include/node/openssl/stack.h
      /usr/local/include/node/openssl/symhacks.h
      /usr/local/include/node/openssl/tls1.h
      /usr/local/include/node/openssl/ts.h
      /usr/local/include/node/openssl/txt_db.h
      /usr/local/include/node/openssl/ui.h
      /usr/local/include/node/openssl/ui_compat.h
      /usr/local/include/node/openssl/whrlpool.h
      /usr/local/include/node/openssl/x509.h
      /usr/local/include/node/openssl/x509_vfy.h
      /usr/local/include/node/openssl/x509v3.h
      /usr/local/include/node/pthread-barrier.h
      /usr/local/include/node/stdint-msvc2008.h
      /usr/local/include/node/tree.h
      /usr/local/include/node/uv-aix.h
      /usr/local/include/node/uv-bsd.h
      /usr/local/include/node/uv-darwin.h
      /usr/local/include/node/uv-errno.h
      /usr/local/include/node/uv-linux.h
      /usr/local/include/node/uv-os390.h
      /usr/local/include/node/uv-sunos.h
      /usr/local/include/node/uv-threadpool.h
      /usr/local/include/node/uv-unix.h
      /usr/local/include/node/uv-version.h
      /usr/local/include/node/uv-win.h
      /usr/local/include/node/uv.h
      /usr/local/include/node/v8-debug.h
      /usr/local/include/node/v8-experimental.h
      /usr/local/include/node/v8-platform.h
      /usr/local/include/node/v8-profiler.h
      /usr/local/include/node/v8-testing.h
      /usr/local/include/node/v8-util.h
      /usr/local/include/node/v8-version.h
      /usr/local/include/node/v8.h
      /usr/local/include/node/v8config.h
      /usr/local/include/node/zconf.h
      /usr/local/include/node/zlib.h

    Warning: Suspicious git origin remote found.

    With a non-standard origin, Homebrew won't pull updates from
    the main repository. The current git origin is:
      https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git

    Unless you have compelling reasons, consider setting the
    origin remote to point at the main repository, located at:
      https://github.com/Homebrew/brew.git

    Warning: Broken symlinks were found. Remove them with `brew prune`:
      /usr/local/lib/node_modules/npm/node_modules/request/node_modules/.bin/uuid

**Comment by MikeMcQuaid** [comment]
What's your macOS version?

**Comment by cmzz** [comment]
10.12.3 (16D32)

**Comment by MikeMcQuaid** [comment]
Somehow `head` is not using the default macOS `/usr/bin/head`. If you've replaced `/usr/bin/head` with a different version: undo that. Otherwise, you'll need to figure out why `which head` doesn't return the actual version being used by Homebrew. Regardless, this is specific to your machine, sorry.

**Comment by derickvn-yellow** [comment]
I had the same error. /Applications/XAMPP/bin was in my path before /usr/bin. This was causing the incorrect 'head' binary to be called.

I added XAMPP to my path for convenience, but it's better to just place symbolic links in /usr/local/bin for the executables you actually want to use (mysql* and php in my case). Don't be lazy, it bites you later.

**Comment by henriqueiv** [comment]
@derickvn-yellow I had the same problem here but I didn't quite get it. Having `/whatever/bin` BEFORE `/usr/whatever/bin` makes the terminal to execute the first binary found in the `PATH`?

If that is true, when I run something like `brew update`, it expects the binaries from `/usr/whatever/bin` right? But what if I need to run something like `xampp something` which expects the binaries from `/Applications/XAMPP...`? What would happen? 

ps. I temporarily fixed removing the XAMPP from `PATH`.

**Comment by derickvn-yellow** [comment]
Yes, the shell scans the $PATH variable for paths from left to right and executes the first binary it finds. Since there is no xamp binary anywhere but /Applications/XAMPP it would still execute the correct one.

The problem we were facing was that 'HEAD' is a binary within /Applications/XAMP and OSX is case insensitive. Because /Applications/XAMP was first in the path, it executed the wrong binary.

You could can rename /Applications/XAMP/bin/HEAD to /Applications/XAMP/HEAD-backup and it seems to have no ill effect on day-to-day usage. It would likely break some XAMP tool, but I haven't seen anything breaking yet.

So you have a few options:

1.  Rename /Applications/XAMP/bin/HEAD to something else and risk breaking some internal XAMP functionality
2.  Make symbolic links to the files you actually use in /usr/local/bin, i.e. `ln -s /Application/XAMP/bin/mysql /usr/local/bin/mysql` which would call these binaries in stead of the OSX versions
3.  Call the full path every time and risk RSI from all the typing :P
