### ISSUE TITLE
oSSierra sh: /usr/local/bin/elm: Permission denied

### ISSUE THREAD

**Issue by gac55** [Homebrew/brew#1980]
This is a clean install of brew on a brand new Sierra MBP.

The installation returned no errors. When I try and build a project, I get an error relating to permissions in `/usr/local/bin`

```

> bower install && elm package install --yes

sh: /usr/local/bin/elm: Permission denied
```

I don't believe this is an issue with elm or bower. 

I've tried changing permissions:

`sudo chown -R $USER /usr/local`

Error persists

**Comment by MikeMcQuaid** [comment]
Closing as you did not fill in (or read) the issue template.
