### ISSUE TITLE
Brew test ENV.cxx11 fails

### ISSUE THREAD

**Issue by aeantipov** [Homebrew/brew#1981]
Hi. I am drafting a simple formula here. 
`brew test` is supposed to compile a piece of code and run it.
This works : 
```
test do
  args_compile = ["-std=c++11", "-stdlib=libc++", "test.cpp", "-o", "test"]
  system ENV.cxx, *args_compile
```

This doesn't 
```
test do
  ENV.cxx11
  args_compile = ["test.cpp", "-o", "test"]
  system ENV.cxx, *args_compile
```

(the lines of populating test.cpp are omitted)
What's a good way to do this? 
P.S. Side note - what's a good way to retrieve a package dependence (headers) at test stage?

**Comment by MikeMcQuaid** [comment]
You didn't fill out the issue template so closing this.

**Comment by aeantipov** [comment]
Sorry for that, fixed it. Can it be reopened?

**Comment by MikeMcQuaid** [comment]
This is expected behaviour; you need to manually set the flag in test blocks. Thanks!
