### ISSUE TITLE
Jenkins/brewbot can't resolve tap dependencies

### ISSUE THREAD

**Issue by javian** [Homebrew/brew#1988]
### Bug reports:

The brew bot can't currently resolve dependencies to taps. See

https://bot.brew.sh/job/Homebrew%20PHP%20Pull%20Requests/2767/version=sierra/console

where it fails to tap a required formula. The error message is
```
Error: No available formula with the name "homebrew/dupes/zlib" 
Please tap it and then try again: brew tap homebrew/dupes
Build step 'Execute shell' marked build as failure
```

**Comment by MikeMcQuaid** [comment]
We don't consider this a bug; this is a feature in disguise as it stops taps from accidentally depending on others.
