### ISSUE TITLE
Rebuild package X when package Y is updated

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/brew#1989]
I'm having problems with `ffmpeg` and `mpv-HEAD`

When `ffmpeg` is updated, `mpv-HEAD` needs a rebuild as well, otherwise it just crash ..

Is there any way to do this automatically?

**Comment by CaledoniaProject** [comment]
Can you also change the behavior of `brew upgrade mpv`?

When the HEAD version is installed, brew should not prompt `Error: mpv HEAD-f89ff14_3 already installed`, but rather upgrade the package

**Comment by vitorgalvao** [comment]
> Can you also change the behavior of `brew upgrade mpv`?

`upgrade` is a global command. It makes no sense to have it behave in a special manner for a single formula.

> When the HEAD version is installed, brew should not prompt `Error: mpv HEAD-f89ff14_3 already installed`, but rather upgrade the package

`brew upgrade --fetch-HEAD`. It’s in the `man` page.

**Comment by MikeMcQuaid** [comment]
> Is there any way to do this automatically?

Not currently, no, sorry.

**Comment by CaledoniaProject** [comment]
@MikeMcQuaid What do you suggest on such situation?

**Comment by MikeMcQuaid** [comment]
`brew reinstall --HEAD mpv`

**Comment by CaledoniaProject** [comment]
@MikeMcQuaid I run `brew upgrade` daily and automatically ... I need a way to know if I package X is updated, so that I can rebuild package Y.

Any suggestion on that?

**Comment by MikeMcQuaid** [comment]
Not automatically, sorry.

**Comment by CaledoniaProject** [comment]
Alright then

**Comment by vitorgalvao** [comment]
@CaledoniaProject Something like

```bash
if [[ "$(brew outdated | grep ffmpeg)" ]]; then
  brew upgrade ffmpeg
  brew reinstall --HEAD mpv
fi
```

before you other `brew upgrade` should work.

**Comment by CaledoniaProject** [comment]
@vitorgalvao Looks good, thanks!
