### ISSUE TITLE
Thoughts on adding abbreviated commands to bin?

### ISSUE THREAD

**Issue by AndrewSB** [Homebrew/brew#200]
Adding commands similar to what `npm` has? `i` would be shorthand for install, `l` for list?

Not sure if this has been discussed in the past

**Comment by UniqMartin** [comment]
Do you literally mean `/usr/local/bin`? If so, placing executables with such a short name is likely to be problematic. Or do you talk about abbreviations you can use with `brew`, e.g. `brew i` would mean `brew install`. If that's what you are looking for, there's already a solution: https://github.com/Homebrew/homebrew-aliases

**Comment by apjanke** [comment]
Yeah, I think for either of these, per-user aliases configured in the shell (for standalone commands) or `brew alias` (for `brew` subcommands) is the way to go, not something global like adding to `/usr/local/bin` or making subcommand aliases for everyone.

**Comment by AndrewSB** [comment]
https://github.com/Homebrew/homebrew-aliases is what I was talking about. Thanks @UniqMartin, wasn't able to find that, satisfies my need :)

@apjanke why not add subcommand aliases (like `brew i` for `brew install`) for everyone? I feel as if it's a common pattern for package managers now?

**Comment by mikemcquaid** [comment]
@AndrewSB We may consider that in future but not now.
