### ISSUE TITLE
feature request: `brew search --type=[bin lib]` to search by bin/lib produced

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#2003]
often it's not clear whether a library or binary is in homebrew, or how to find the homebrew formula that contains the library we want:

* rg is in ripgrep and `brew search rg|grep ripgrep` is empty (so is `brew desc -s rg|grep ripgrep`)
* lldb is in llvm and requires `brew install --with-lldb`
* etc

so you just have to know or guess. How about adding to `brew search` a `--type` argument that searches by type:

```
brew seach --type=[name | bin | lib | etc | include] [TEXT|/REGEX/]
```

* --type=name is the default and behaves likes the existing `brew search`
* --type=bin prints all formula X such that `brew ls --verbose X` contains the searched term under `bin/`
* likewise with --type=lib,etc,include

NOTE: include may be overkill (contains lots of files) but at the very least `bin` and `lib` are very useful.

```
$ brew search --type=bin rg
ripgrep

$ brew search --type=lib /phobos/
dmd
ldc
```

We could also (maybe later) add `--show_output`
```
$ brew search --type=lib --show_output /phobos/
dmd:libphobos2-ldc-debug.a
ldc:libphobos2-ldc-debug.a libphobos2-ldc.a
```

**Comment by MikeMcQuaid** [comment]
We can't do this without a package metadata database which we don't want to add. That said:



> --type=bin prints all formula X such that brew ls --verbose X contains the searched term under bin/

https://github.com/homebrew/homebrew-command-not-found does this.
