### ISSUE TITLE
brew doctor fails to alert that brew update has not run in over 24 hours

### ISSUE THREAD

**Issue by abhishek7** [Homebrew/brew#2004]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

Did my best to check if this update is no longer sent out as part of running `brew doctor`, but have not seen this. May not be the most major of issues, however this may lead to other bugs in the future.

**Comment by MikeMcQuaid** [comment]
Probably because `brew update` is autorun by e.g. `brew install` now.
