### ISSUE TITLE
a2ps and bottle

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/brew#2005]
Hello,

When reinstalling `a2ps` recently (just to get a clean install), I observed that it was no longer working whereas the previously existing install worked fine:
``a2ps: cannot open file `/usr/local/etc/a2ps.cfg': No such file or directory
a2ps: cannot find file `level1.ppd': No such file or directory
``

The reason is quite simple: my `brew --prefix` is not default `/usr/local/` but `/opt/homebrew`.
So a workaround for me was to force compilation from source with `brew reinstall --build-from-source a2ps` to get it run correctly again.

Since it's my first time discovering a bottle not properly working (among my >250 brew install), here follows my question:
is there anything to add in the formula so as to force the compilation from source and avoid the bottle when `HOMEBREW_PREFIX` is not standard `/usr/local`?

**Comment by MikeMcQuaid** [comment]
I've pushed a fix for this. For future reference please always fill out the issue template (which will have told you to fill this out at Homebrew/homebrew-core). Note this is also why we strongly recommend installing Homebrew into /usr/local.
