### ISSUE TITLE
Ruby .rb files are not considered to be libraries

### ISSUE THREAD

**Issue by kke** [Homebrew/brew#2008]
As seen in:

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_cellar_checks.rb#L62

```ruby
    valid_extensions = %w[.a .dylib .framework .jnilib .la .o .so
                          .jar .prl .pm .sh]
```

When creating a formula for a multi-file Ruby application, you get:

```
$ brew audit --new-formula app
  * Non-libraries were installed to "/usr/local/opt/app/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /usr/local/opt/app/lib/app.rb
```

**Comment by MikeMcQuaid** [comment]
This is correct, we don't consider Ruby files (or Python files or Perl files) to be libraries like this. Install them to `libexec` or `share` instead.

**Comment by kke** [comment]
Ok so my formula should rename the lib directory of the ruby app and inreplace the loadpath?

**Comment by kke** [comment]
That's what I ended up doing.
