### ISSUE TITLE
Using the runtime dependencies during install

### ISSUE THREAD

**Issue by kke** [Homebrew/brew#2009]
If a recipe has defined a runtime dependency, such as `depends_on ruby: '2.1'`, what's the preferred way to get the path to that ruby during the installation?

For example:

```ruby
class FormulaX < Formula
  depends_on :ruby => '2.1'

  resource "rake" do
    url "https://rubygems.org/downloads/rake-10.5.0.gem"
    sha256 "2b55a1ad44b5c945719d8a97c302a316af770b835187d12143e83069df5a8a49"
  end

  def install
    # this is probably not the way to go:
    gem_command = File.join(HOMEBREW_PREFIX, "Cellar", "ruby", "2.1.0", "bin", "gem")
    resources.each do |r|
      r.verify_download_integrity(r.fetch)
      system(gem_command, "install", r.cached_download, "--no-document",
             "--install-dir", "#{buildpath}/vendor")
    end
  end
end
```

Using just plain `system('gem', 'install' ..)` will often run a completely different ruby/gem than the one depended on.

Also there doesn't seem to be a way to depend on "ruby >= 2.1.0", so should I create a custom requirement like in the [zpython formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/zpython.rb#L1) and just die unless the ruby / gem that comes from `system('ruby')` is fresh enough?

**Comment by MikeMcQuaid** [comment]
> way to get the path to that ruby during the installation?

`which "ruby"`; we set the path accordingly.

**Comment by kke** [comment]
system('gem', 'install') dies with "ruby version greater than 2.1 required to install this gem" with depends_on :ruby => '2.1'.

**Comment by MikeMcQuaid** [comment]
You may need to manually set the PATH to find `gem` or install `gem` itself.
