### ISSUE TITLE
Ruby version dependency is ignored when rbenv is using system ruby

### ISSUE THREAD

**Issue by kke** [Homebrew/brew#2010]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

#### Summary
Ruby version dependency is ignored when rbenv is using "system" ruby.

#### Details

Having a formula that depends on a ruby version:

```ruby
class Foo < Formula
  depends_on :ruby => '2.4'
  def install
    system(which("ruby"), "--version")
  end
end
````

Using the "system" ruby with rbenv and trying to install the formula:

```sh
$ rbenv local system
$ brew install --verbose foo
==> /usr/bin/ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
```

It ignores the ruby dependency and points to the system ruby.

If you change to an rbenv ruby and try again:

```sh
$ rbenv local 2.3.1 # <-- switch to a non system ruby
$ brew install --verbose foo
==> /usr/local/opt/ruby/bin/ruby --version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]  # <-- a non rbenv ruby
```

It correctly uses the version defined in `depends_on` (and it's not following the current rbenv ruby, as long as it's not "system")

### brew config
```sh
$ brew config
HOMEBREW_VERSION: 1.1.9-165-ge116ba196
ORIGIN: https://github.com/Homebrew/brew
HEAD: e116ba196e2834025c713a2a566e0e150907d6d0
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a73d496eae43d1c015631d54243e6cf2266855ea
Core tap last commit: 16 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/opt/rbenv/shims/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: N/A
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: N/A
X11: N/A
$ brew doctor
Your system is ready to brew.
```

**Comment by kke** [comment]
Also, maybe related:

1) Install ruby 2.4 via brew
2) `depends_on :ruby => '2.4'` works as expected, `which("ruby")` points to the correct binary
3) `depends_on :ruby => '2.1'` now gives you the system ruby 2.0

**Comment by kke** [comment]
I think the culprit is the [RubyRequirement](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/requirements/ruby_requirement.rb).

It uses `which_all("ruby")` to find all rubies, sees that a satisfying Ruby exists somewhere along the path and is happy with that, but the path to the satisfying one is never returned back to the formula.

**Comment by MikeMcQuaid** [comment]
> I think the culprit is the RubyRequirement.
> 
> It uses which_all("ruby") to find all rubies, sees that a satisfying Ruby exists somewhere along the path and is happy with that, but the path to the satisfying one is never returned back to the formula.

Yeh, this is likely the bug. We'd accept a PR for this but it's not something we're going to be actively prioritising. In future I'd personally like to see us only have `Requirements` ever be fulfilled by either casks or formulae.
