### ISSUE TITLE
Error: Failed to install vendor Ruby.

### ISSUE THREAD

**Issue by upadhyay95** [Homebrew/brew#2016]
while installing the homebrew i get the following error ..

HEAD is now at c12f7fd extend/ENV/std.rb: Fix libxml2 style error
Error: Checksum mismatch.
Expected: dbb5118a22a6a75cc77e62544a3d8786d383fab1bdaf8c154951268807357bf0
Actual: 9eedf78f9a318dbf28c15b28102d135ed9d84d974bfbecd4638c84019a525c6c
Archive: /home/krishna/.cache/Homebrew/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.
Failed during: /home/krishna/.linuxbrew/bin/brew tap homebrew/core

*** i have attached the screenshot 
![screenshot from 2017-02-15 07 05 24](https://cloud.githubusercontent.com/assets/14949402/22957286/4e6bac8e-f34d-11e6-91a3-eafe2ea42b08.png)

**Comment by upadhyay95** [comment]
while brew-v it shows :
Error: Failed to install vendor ruby.
Error: Failed to install vendor Ruby.

what does it mean ?
ruby is already installed ...
how to fix this error ??
![screenshot from 2017-02-15 07 11 41](https://cloud.githubusercontent.com/assets/14949402/22957446/4554e498-f34e-11e6-8abe-adedcc3e7311.png)

**Comment by JCount** [comment]
I'd say the first thing to do would be to try removing `/home/krishna/.cache/Homebrew/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz`, see if it fixes your issue, and report back.

(For future reference you should probably post issues like this over on [Linuxbrew/brew](https://github.com/Linuxbrew/brew))

Also, given it being Linuxbrew related, cc @sjackman

**Comment by upadhyay95** [comment]
no it dosent fix the error .. i removed and it shows the same error ...

**Comment by JCount** [comment]
Ok,  so next try running:
`curl -Lo /home/krishna/.cache/Homebrew/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz` 
to manually fetch the portable ruby bottle.

**Comment by upadhyay95** [comment]
its not yet solved ....

i tried uninstalling ruby ,then linuxbrew and installed it ... but again it shows same error ....
is it any problem related to 32-bit x86 platforms ??
as i read somewhere in README that x86 platforms are not supported ... so if this is the problem what should i do ?
![screenshot from 2017-02-15 11 22 47](https://cloud.githubusercontent.com/assets/14949402/22962151/1e98c176-f371-11e6-862a-9b54c67e9854.png)

**Comment by JCount** [comment]
Looking at your screenshots more closely, I noticed that the ruby version you are using is 32 bit. That then brings to mind whether you a running an x86_64 kernel or not. If you are not, then the vendored version of ruby will not work properly. Unfortunately, on top of this:
> Linuxbrew does not currently support 32-bit x86 platforms.

see https://github.com/Linuxbrew/brew#32-bit-x86-platforms

To determine if your kernel is 64 bit is to run `uname -m` in a terminal.

**Comment by upadhyay95** [comment]
yes got it ... its due to the 32 bit kernel ...
thanks ..  :-)

**Comment by JCount** [comment]
I am sorry I can't be of more help.

**Comment by JCount** [comment]
Closing this as it is as resolved as it will be.

**Comment by MikeMcQuaid** [comment]
> Archive: /home/krishna/.cache/Homebrew/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz

Please don't report Linux issues here, thanks.
