### ISSUE TITLE
brew install keg-only formula gives warning "brew install --force"

### ISSUE THREAD

**Issue by smthpickboy** [Homebrew/brew#2017]
I had gettext installed in /usr/local/opt as dependency for some formula.
When I run:
`$brew upgrade gettext`

It gives a warning:
Warning: gettext is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version

But when I do
$brew install --force gettext
It gives:
Warning: gettext-0.19.8.1 already installed, it's just not linked.

I found:
https://github.com/Homebrew/legacy-homebrew/commit/5bddaf2e355e5fe78e05e68113fad830ed12f517
So I suppose `brew install --force` is removed and the warning text should be revised

**Comment by MikeMcQuaid** [comment]
`brew link gettext` will likely address this. Shout again if it doesn't. Thanks!

**Comment by arjunhbo** [comment]
brew link gettext
Warning: gettext is keg-only and must be linked with --force
Note that doing so can interfere with building software.
