### ISSUE TITLE
How to solve the following warning from brew doctor?

### ISSUE THREAD

**Issue by hugeme** [Homebrew/brew#2020]
MacOS Sierra 10.12.2

Recently, I ran into the following issue:

    Warning: Unbrewed .la files were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected .la files:
      /usr/local/lib/psqlodbcw.la

I have tried different approaches like:

    brew unlink postgresql && brew link postgresql
    brew link --overwrite postgresql

But that doesnt seem to resove the warning.

appreciate any help

**Comment by MikeMcQuaid** [comment]
You can manually delete this file with `rm /usr/local/lib/psqlodbcw.la` or just ignore the warning.
