### ISSUE TITLE
Best practice for installing rubygems in formulas

### ISSUE THREAD

**Issue by kke** [Homebrew/brew#2022]
## Background
There are only a handful of formulas for Ruby based applications that are installing gem dependencies.

Not a single one of them are doing it like the [formula cookbook instructs](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#handling-files-that-should-persist-over-formula-upgrades) or in any other reusable manner.

> For example, Ruby 1.9’s gems should be installed to var/lib/ruby/ so that gems don’t need to be reinstalled when upgrading Ruby. You can usually do this with symlink trickery, or better a configure option.

What's the preferred way? (Or an acceptable way if I ever want to get my formula merged?)

I don't think the part about "don't need to be reinstalled when upgrading Ruby" is actually correct, gem directories are ruby version specific, such as `/usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0` or `/usr/local/lib/ruby/gems/2.4.0`

Also, var/lib/ruby is not in the GEM_PATH even in a brew installed ruby, so any reuse of the formula installed gems would require setting GEM_PATH (this could be `caveat`ed in the formula).

I don't think installing to var/lib/ruby during formula is possible, you have to install under buildpath and then `(var/"lib/ruby").install buildpath/"gem_temp"`

### [mikutter](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mikutter.rb)

- Gems are defined as resources.
- Installs to `/usr/local/Cellar/mikutter/#{version}/lib` - not reusable by other ruby apps or even across mikutter versions
- HEAD will not work if it requires any other gems or gem versions
- A formula update that includes gem updates will require generating a new set of resouces.

At first it looks like the "prime example" of how to do it, but all that fancy stuff actually ends up making this maybe the most difficult to maintain and the most likely to break and adds exactly zero gem reusability.

### [cocoapods](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cocoapods.rb)

- Installs dependent gems under cocoapods' own directory (a whole bunch of them)
- Not usable universally or across versions

### [hub](https://github.com/Homebrew/homebrew-core/blob/master/Formula/hub.rb)

Only uses gems during build for creating man pages, installs them privately, ditches them after build.

### [ghi](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ghi.rb)

Uses `depends_on "pygments.rb" => :ruby` which results in: 
```
Homebrew does not provide special Ruby dependencies;
install with: `gem install pygments.rb`
```
..yeah well you could have used `gem install ghi` in the first place

**Comment by MikeMcQuaid** [comment]
I think any of the ways except `ghi` (which should probably be removed, I agree) are fine. We don't aim to have gems reused between versions or software as Homebrew kegs should only depend on other kegs or system-wide things.

We'd also definitely accept PRs to improve/discuss the documentation.

Thanks for some a detailed write-up ❤️.
