### ISSUE TITLE
Isn't caskroom/cask tap migration in update-report too aggressive?

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/brew#2025]
`update-report` does [this](https://github.com/Homebrew/brew/blob/a3bffe70bcf33e6051140b1a93c9f48714605af6/Library/Homebrew/cmd/update-report.rb#L478-L479]) when a formula is migrated to caskroom/cask (this happens automatically):

```rb
          ohai "brew uninstall --force #{name}"
          system HOMEBREW_BREW_FILE, "uninstall", "--force", name
```

IMO this is way too aggressive. Uninstalling a formula without user's consent (I assume most users won't expect their stuff to be auto-uninstalled when running update; I certainly didn't when it happened to me) is bad enough; I don't know what to say about the `--force` flag without making myself look bad.

Note that the formula need not be uninstalled (let alone force uninstalled, wiping out all kegs), because kegs do not interfere with casks. IMO an unlink is as far as we should go. Also note that the cask => formula migration logic immediately above the logic I'm calling into question doesn't uninstall the cask.

---

On a somewhat related note, I think cask => formula or formula => cask migrations, or at least the parts that auto-installs stuff, should be guarded by the `--preinstall` exemption. It's plain weird to have unrelated things installed (and worse still, uninstalled) when you run some command other than update or upgrade. Check out my horror story below.

---

To put things into perspective, here's a little horror story of mine. I was running `bump-formula-pr` just now, unsuspectingly. Then `brew` decided to `uninstall --force` my `keybase` kegs, run `brew prune` without my consent, and install the `keybase` cask, which prompted a GUI password dialog — due to the one time setup run by the cask's postflight — and a Little Snitch dialog about the newly installed app attempting to make Internet connections (look, I'm not arguing the cask shouldn't be auto-installed — which could be a separate topic — but it is indeed crazy when these all happen during a `bump-formula-pr`).

**Comment by ilovezfs** [comment]
This falls into the works-as-designed bucket. See https://github.com/Homebrew/homebrew-core/issues/9316 for prior discussions.

**Comment by zmwangx** [comment]
This is very different from Homebrew/homebrew-core#9316 in that I'm not asking about prompts here (I talked about consent, but what I meant was consent given by explicitly issuing an install/uninstall command), or arguing that update should not perform migrations. What I'm calling into question are

1. When a migration is performed, **specifically a formula => cask migration**, `brew uninstall --force` is called on the formula, which is both unnecessary and destructive, and does not happen in any other circumstance.

    My suggestion: only call `brew unlink` on the formula.

2. New formula/cask may be installed by `brew update --preinstall`.

    My suggestion: not install new formula/cask in `brew update --preinstall`.

**Comment by ilovezfs** [comment]
bump-formula-pr isn't running --preinstall so how is that relevant?

**Comment by zmwangx** [comment]
The second point isn't relevant to bump-formula-pr specifically. (I do think bump-formula-pr and boneyard-formula-pr should run update with --preinstall, but didn't bother to submit a PR.)

But update --preinstall happens for most users all the time. It has a much larger impact than anything bump-formula-pr does.

**Comment by MikeMcQuaid** [comment]
> My suggestion: only call brew unlink on the formula.

This specifically seems like a reasonable ask and I'd personally 👍 a PR doing it.

**Comment by ilovezfs** [comment]
I'm not sure it's wise to have the formula still opt linked if it has supposedly already gone through migration. How exactly will we know when to perform the migration because it hasn't been done yet, and when to skip it because it was already completed, or at least was already attempted but failed, either of its own accord or because it was rejected, reversed, canceled, etc. by the user?

**Comment by zmwangx** [comment]
> How exactly will we know when to perform the migration...

It's only even attempted once, when update-report detects the migration, unless you rewind the history. And I fail to see any harm of keeping the kegs, when the destination is an alternative universe only weakly linked by update-report.

**Comment by ilovezfs** [comment]
That sounds like a bug to me. If the migration fails it should be considered incomplete until it succeeds.

Also, if it's such an altenative universe, that raises the question why we bother with the migration at all.

**Comment by zmwangx** [comment]
> That sounds like a bug to me. If the migration fails it should be considered incomplete until it succeeds.

Sure. Doesn't fit in current logic though, where formula => cask migration only happens in `migrate_tap_migration` in `update-report.rb`, which only deals with changes seen in that update session.

> Also, if it's such an altenative universe, that raises the question why we bother with the migration at all.

Cask installer may write to the same files in `/usr/local`. It shouldn't hurt in most cases because overwritten files are no longer considered to be files belonging to brew, but still it could be messy. Which is why I'm suggesting an unlink. Otherwise brew stuff should be completely harmless IMO.

Also, if cask installer does not, say, write the same binaries to `/usr/local/bin`, unlinking things serves as a reminder that things have changed the next time the user tries to use what was installed by the formula. After all, I run `brew update` in a crontab and never check the logs unless errors occur, and I assume quite some people similarly run `brew update` routinely and non-interactively, which means we won't see the migration messages.

**Comment by ilovezfs** [comment]
I'm perplexed by this idea that somehow it's desirable to have the end result of a migration be a double installation with the formula still opt-linked. Either we're migrating the formula to the cask, or we're not. If you think a given migration is undesirable, that's one thing, but I have no idea why we'd want the default state of affairs post migration to be an unsupported double installation.

**Comment by mistydemeo** [comment]
> I have no idea why we'd want the default state of affairs post migration to be an unsupported double installation.

Think of it by analogy to a `brew upgrade`; the old version of the formula is left around, unlinked, until the user calls `brew cleanup` or `brew rm $formula`. This gives the user a chance to return temporarily to the old version if the upgrade was unexpected, or to provide a safety hatch in case there's some user data they can't access with the newer version. This is especially germane for a formula-to-cask migration, where the target of the upgrade may be packaged in a substantially different way and the user might not be prepared for a major change right away. Leaving the old version, inactive, leaves the user in control of when to activate the migration. Since the user may not have been counting on this sort of migration happening as the result of a `brew update` operation, I think leaving that control in their hands is important.

**Comment by zmwangx** [comment]
Formulae and casks are never equivalent, even if they install the exact same file. For one, there's `brew switch` but not `cask switch`, so force removing all kegs can do damage that's very complicated to recover. (I still think any attempt to treat brew and cask / formulae and casks as equivalents is misguided and wishful thinking, but I'd rather not start another flame war from a very specific and IMO reasonable request that hopefully both sides could reach an agreement eventually.)

Basically, there's no double installation, but the legacy installation of a since-removed formula, and the installation (automatic one) of an overlapping cask. You don't force install a user's kegs when you remove a formula. Likewise you shouldn't do so when migrating a formula to a cask, which is like passing the event horizon of a black hole.

Users (especially power users) should get to decide what to do with harmless kegs.

**Comment by ilovezfs** [comment]
>Think of it by analogy to a brew upgrade; the old version of the formula is left around, unlinked

It is not left around still opt-linked, so the analogy fails.

**Comment by zmwangx** [comment]
In the case of `brew upgrade`, the opt-link *has to* point to the new keg.

In the case of formula => cask migration (basically a formula removal as I argued above), there's no such hard constraint.

**Comment by ilovezfs** [comment]
>I still think any attempt to treat brew and cask / formulae and casks as equivalents is misguided and wishful thinking, but I'd rather not start another flame war from a very specific and IMO reasonable request that hopefully both sides could reach an agreement eventually.

Exactly. The change you're proposing is motivated by a desire to make it easier to undermine the migration and revert to an unsupported state.

>Basically, there's no double installation

Sorry, but if the keg is still in place and opt-linked it is, by definition, installed. Hence, double installation.

>Users (especially power users) should get to decide what to do with harmless kegs.

They are not "harmless kegs" if the they're facilitating unsupported configurations.

>In the case of formula => cask migration (basically a formula removal as I argued above), there's no such hard constraint.

What is the point of having a migration if we're asserting double installation is just peachy?

**Comment by zmwangx** [comment]
> Sorry, but if the keg is still in place and opt-linked it is, by definition, installed. Hence, double installation.

Double installation of two non-equivalent packages in two separate, non-interfering package managers (if brew-cask can be called a package manager).

> They are not "harmless kegs" if the they're facilitating unsupported configurations.

1. `brew install foo`;
2. Formula `foo` removed;
3. (Optional) `brew unlink foo`.

Is this a supported configuration? Depends on your definition of "supported", but it is a routinely achievable configuration.

> What is the point of having a migration 

I don't know what's the point of migration. Here I'm assuming migration (the installing cask part) as a given, and trying to minimize what I perceive as damage.

**Comment by mistydemeo** [comment]
> Exactly. The change you're proposing is motivated by a desire to make it easier to undermine the migration and revert to an unsupported state.

From my perspective, the motivation for the change is a desire to give the user control over *when* they do that migration. `brew update` is not something that most users are going to expect to remove files from disk. If the user continues using the unsupported formula indefinitely, that is their call.

By comparison - unless this has changed, and I don't think it has - migrating a formula between taps leaves the formula installed, but unlinked, at its old name. This gives the user a chance to temporarily undo the migration and continue using the formula under its old name until they're ready to commit to the migration.

**Comment by ilovezfs** [comment]
>From my perspective, the motivation for the change is a desire to give the user control over when they do that migration.

How exactly does that work when the installation of the keybase cask writes symlinks in /usr/local/bin. Relinking the keg will overwrite those symlinks and the only way to restore them will be a full zap and reinstall of the cask. Who exactly is going to step the users through that?

**Comment by mistydemeo** [comment]
> Relinking the keg will overwrite those symlinks and the only way to restore them will be a full zap and reinstall of the cask.

Relinking the keg should warn the user explicitly, yeah? And the keg can be used, unlinked, by setting their `PATH` manually.

**Comment by ilovezfs** [comment]
>Relinking the keg should warn the user explicitly, yeah? And the keg can be used, unlinked, by setting their PATH manually.

So the prior, and by definition ignored, warning is the support mechanism once the installation is completely borked?

**Comment by zmwangx** [comment]
> Relinking the keg will overwrite those symlinks

You assume full responsibility when you run `brew link --overwrite`. Also there's `brew link --overwrite --dry-run` that tells you what's being overwritten, so that you can take a note of the original destinations.

**Comment by ilovezfs** [comment]
I'm seeing a lot of optimizing here for the power user case at the expense of the non-power user case and support burden.

>You assume full responsibility when you run brew link --overwrite.

So we will just close those issue reports and tell people they're on their own at that point? Or worse, our bad behavior in brew will shunt the burden over to the cask team to sort out the mess for us?

**Comment by zmwangx** [comment]
> at the expense of the non-power user case and support burden.

Any proof for that? So far support burden seems to be coming from people who are not happy about the force uninstall.

Also not sure what is completely borked (getting into irrelevant details here). What's preventing people from running `keybase` with the absolute path instead of using the symlink?

> So we will just close those issue reports and tell people they're on their own at that point?

Those imaginary issues are easy to recover from. Fallout of an unwanted brew uninstall --force is not.

**Comment by ilovezfs** [comment]
>(getting into irrelevant details here)

Wow. I'm done.

**Comment by zmwangx** [comment]
> (getting into irrelevant details here)

I meant irrelevant details about the specific case of keybase. It is certainly possible to bork an installation in some other imaginary case, but I don't think it's the general pattern of what you could do with cask.

Also, ignore keybase and let's say mysql is being automagically migrated. Would you be so quick to eliminate every trace of the old installations?

**Comment by mistydemeo** [comment]
> I'm seeing a lot of optimizing here for the power user case at the expense of the non-power user case and support burden.

To give you some perspective on where I'm coming from: I provide developer environment bootstrapping support at a company with a few hundred developers. Major changes to formulae have a tendency to break things for at least some subset of users when something changes in an unexpected way. That's fine - Homebrew can't predict what will or won't break for users, and to an extent the burden of adapting to those changes is up to users and not Homebrew.

However, users depend on being able to roll back to a known-good state when such a major change happens. Forcibly removing all installed versions of the package that worked means that the user has no ability to return their system to a working state until the bootstrap scripts get fixed. That's pretty user-hostile, even if we don't intend it that way, and even if we're trying to prevent a certain class of issues.

The `mysql56` => `mysql@5.6` migration is one example of a migration where users had the ability to uninstall the new formula and relink the old one to keep working if the migration broke something. Given that Homebrew targets developers in particular, I think it's very valuable to provide users with the tools to unblock themselves when a change happens.

And, finally, I think it's been a general understanding that `brew update` doesn't make changes to installed packages - `brew upgrade` does. We've been stretching that with formula migrations, and this change that uninstalls packages breaks the expectation.

**Comment by ilovezfs** [comment]
@mistydemeo You're prioritizing rollback over not breaking the cask, and still have not explained who is going to support un-breaking the cask installs when people re-link the formula.

**Comment by zmwangx** [comment]
- not `uninstall --force`: worst case scenario: non power user messes with things beyond their pay grade; solution: `brew cask reinstall foo`;
- `uninstall --force`: worst case scenario: ???

**Comment by ilovezfs** [comment]
My sense of the overall situation is that automatic formula -> cask migration is a mistake. We now have a system that _by design_ has `brew update` triggering a prompt for privilege escalation so that kernel extensions can be loaded, which is so ridiculous on its face I don't even know where to start.

**Comment by zmwangx** [comment]
> My sense of the overall situation is that automatic formula -> cask migration is a mistake.

I don't like that either. But I don't think it's something I as an outsider could argue about. (I knew it "falls into the works-as-designed bucket" before you pointed that out.)

Meanwhile, abolishing `uninstall --force` is IMO both trivial and overwhelmingly positive; didn't expect this much pushback.

**Comment by mistydemeo** [comment]
> My sense of the overall situation is that automatic formula -> cask migration is a mistake. We now have a system that by design has brew update triggering a prompt for privilege escalation so that kernel extensions can be loaded, which is so ridiculous on its face I don't even know where to start.

Yeah, I agree that those aren't desirable things to have introduced into `brew update`.

**Comment by ilovezfs** [comment]
@mistydemeo is it really any better if it's in `brew upgrade`? A userland-only keybase install is seriously not the same thing as a .app that demands root privileges so it can install and load a kernel extension that implements a file system.

**Comment by ilovezfs** [comment]
>Meanwhile, abolishing uninstall --force is IMO both trivial and overwhelmingly positive; didn't expect this much pushback.

My problem is that `brew link -f keybase` breaks the cask, which seems ... counter-productive if we're really _believing in_ the virtues of formula-to-cask migration.

**Comment by zmwangx** [comment]
Isn't formula-to-cask migration a result of optimizing for non-power users?

> .app that demands root privileges

To be fair, you can deny the privilege. Users do have a choice here.

In the specific case of keybase, personally I'd just keep building the keybase command line client from source. Not really a fan of kbfs, I tried it immediately after its initial announcement and only wanted to get it out of my system.

**Comment by mistydemeo** [comment]
> is it really any better if it's in brew upgrade?

I think it's *better*, in that `brew upgrade` is understood as changing package state and `brew update` is not. But I agree that a user who has done userland-only installations being suddenly prompted to install something with elevated privileges is not user-friendly behaviour and also breaks user expectations.

**Comment by ilovezfs** [comment]
>In the specific case of keybase, personally I'd just keep building the keybase command line client from source.

@zmwangx as you can see that was exactly my preference as well: https://github.com/Homebrew/homebrew-core/pull/9852

**Comment by ilovezfs** [comment]
>a user who has done userland-only installations being suddenly prompted to install something with elevated privileges is not user-friendly behaviour and also breaks user expectations.

This.

**Comment by zmwangx** [comment]
TBH some Homebrew users might not even have heard of Homebrew-Cask.

**Comment by ilovezfs** [comment]
>TBH some Homebrew users might not even have heard of Homebrew-Cask.

I can't wait for the first keybase kernel panic to result from this migration.

**Comment by ilovezfs** [comment]
>I think it's better, in that brew upgrade is understood as changing package state and brew update is not.

There is a bit of a semantic problem with putting it in `upgrade`, which is that a given formula-to-cask migration may in fact be a downgrade (e.g., inkscape was 0.92 -> 0.91).

**Comment by zmwangx** [comment]
lol,

```
brew install caskformula/caskformula/inkscape
```

recommended on https://inkscape.org/en/download/mac-os/. SAD!

**Comment by ilovezfs** [comment]
>SAD!

Don't forget the hashtag.

**Comment by MikeMcQuaid** [comment]
We've been doing this for the best part of a year at this point with minimal user complaints and we've updated `brew update`'s documentation to state that migrations are done by it. Regardless of how we could have best handled this to further change this behaviour now is going to introduce additional confusion. 

Like most things and like I pointed out earlier: we'll review PRs that make this better and if you want to have a say on the PRs that change Homebrew's behaviour please consider watching the Homebrew repository and contributing alternate approaches here.

**Comment by zmwangx** [comment]
#2045.
