### ISSUE TITLE
Mediatomb failing to build from source: patch file returning 404

### ISSUE THREAD

**Issue by bkintanar** [Homebrew/brew#203]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

building mediatomb from scratch fails. It seems that one of the patch file is returning a 404 error. Specifically this file: 

`https://sourceforge.net/p/mediatomb/patches/_discuss/thread/57c47fb9/8ad8/attachment/mediatomb-urifix.patch`

It's no longer there.

Can anyone take a look at this?

@DomT4 I'll tag you with this since you were the one I last converse with regarding this formula.

Thanks.

**Comment by mikemcquaid** [comment]
Please report this to https://github.com/Homebrew/homebrew-core/issues, thanks.
