### ISSUE TITLE
 Failed to download resource "wkhtmltopdf"

### ISSUE THREAD

**Issue by Sasha4ever** [Homebrew/brew#2031]
Error: Failed to download resource "wkhtmltopdf"
Download failed: https://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.11.0_rc1.tar.bz2

**Comment by neutric** [comment]
What were you trying to install? wkhtmltopdf from boneyard? You may have more luck with the [Cask version](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wkhtmltopdf.rb). Please provide more context next time, the [issue template](https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE.md) is a good start.
