### ISSUE TITLE
Please don't remove `linkapps`

### ISSUE THREAD

**Issue by netheril96** [Homebrew/brew#2032]
The current version of `brew` warns us about `linkapps`:

```
Warning: `brew linkapps` has been deprecated and will eventually be removed!

Unfortunately `brew linkapps` cannot behave nicely with e.g. Spotlight using
either aliases or symlinks and Homebrew formulae do not build "proper" `.app`
bundles that can be relocated. Instead, please consider using `brew cask` and
migrate formulae using `.app`s to casks.
```

But I have never encountered problems with `linkapps`. `brew cask`, on the other hand, hardly satisfies my needs, because it can neither be built from source, nor be customized.

**Comment by bfontaine** [comment]
Note you can create your own commands by [maintaining a tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) so even if the command is removed you’re able to re-create it.

**Comment by MikeMcQuaid** [comment]
Sorry, we will be removing this at some point.
