### ISSUE TITLE
Installing Docker Beta for OSX throws error of missing dependencies that I've uninstalled

### ISSUE THREAD

**Issue by betoharres** [Homebrew/brew#204]
Before I've installed the new docker beta for osx, I uninstalled the docker and docker-machine using the commands `brew uninstall docker` and `brew uninstall docker-machine`, then I proceeded to install the docker beta `.dmg`. And here's what I receive running brew doctor:

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:
```
Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install docker docker-machine

Run `brew missing` for more details
```

Any suggestion?

**Comment by mikemcquaid** [comment]
> Any suggestion?

Run `brew missing` for more details?

**Comment by betoharres** [comment]
@mikemcquaid sorry I forgot to mention that:
```
$ brew missing         
dinghy: docker docker-machine```

**Comment by mikemcquaid** [comment]
In that case you need to either `brew uninstall dinghy` and/or convince the `dinghy` formula creator to not `depends_on "docker"`.

**Comment by betoharres** [comment]
@mikemcquaid Thanks a lot Mike! It worked!
