### ISSUE TITLE
How to map Homebrew enforced structure to custom structure

### ISSUE THREAD

**Issue by ErikSchierboom** [Homebrew/brew#2052]
In [this issue](https://github.com/dotnet/cli/issues/533#issuecomment-280691563), a discussion is ongoing on how to create a Homebrew recipe for .NET Core. Apparently, they ran into [an issue](https://github.com/dotnet/cli/issues/533#issuecomment-280691563). Things can be best explained by one of the authors, which made the following comment in that issue:

> Let me explain where the problem lies in more depth. When you install the .NET Core SDK, you get several things:
> 
> 1. A version of the runtime (or, in the case of the MSBuild-based SDKs 2 of them, LTS and Current)
> 1. A version of the command-line tools (CLI)
> 1. A host binary
> 1. A host policy (fxr) file
> 
> All of these components have their own versions that are installed side-by-side. We use the model where we have a root directory where all of the the bits are installed and each of the components above gets a sub-directory in that root. Different versions go into those sub-directories. Here is a sample layout of the installation on one of my machines:
>
<pre>
├───host
│ └───fxr
│ └───1.1.0
├───sdk
│ ├───1.0.0-preview2-003121
│ ├───1.0.0-preview2-003131
│ ├───1.0.0-preview4-004079
│ ├───1.0.0-preview5-004232
│ ├───1.0.0-rc3-004517
│ └───1.0.0-rc4-004769
├───shared
│ └───Microsoft.NETCore.App
│ ├───1.0.0
│ ├───1.0.1
│ ├───1.0.3
│ └───1.1.0
</pre>
> 
> This layout is very important because it drives the way both the SDK and the runtime resolution work. For example, if you have aglobal.json file and you specify a version of the SDK you want to use for a given project, the host will know to go into the sdk directory that is right next to it and try to resolve the version you asked for. This similar process happens when you run an application against the shared framework, but the shared directory is used and a framework is found.
> 
> Homebrew, on the other hand, expects that each formula is a separate version and places them on disk as such. This model would break our side-by-side story. Following the example with the SDK, even if you have the correct versions installed, you would not be able to multiplex between them because the host would not be able to find the SDK folder it needs, unless you keep unlinking and re-linking the correct version you need. This would not be optimal and we believe would confuse a lot of our users.

My question is as follows: how can this problem best be solved in Homebrew? Any help would be much appreciated, as getting .NET Core to install on our Mac's using Homebrew would greatly help increase adoption I feel.

**Comment by MikeMcQuaid** [comment]
It's fine to have multiple versions of SDKs installed under the prefix in pretty much any structure under `prefix` (or `libexec` if `bin` and `lib` directories are used but not wanted to be linked) but given Homebrew doesn't support side-by-side version installation anyway without `@` formulae there shouldn't be an issue there. The best approach is for someone to create a pull request and we can review that; it's pretty hard to do so speculatively. Thanks!

**Comment by haf** [comment]
Where's the documentation for the `@ formulae`?

**Comment by MikeMcQuaid** [comment]
@haf http://docs.brew.sh/Versions.html
