### ISSUE TITLE
`install --force` generates unnecessary warning

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#2053]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

Pick an arbitrary formula, e.g., `wallpaper`, and forcibly install it: `brew install --force wallpaper`.  Observe: `Warning: wallpaper: this formula has no --force option so it will be ignored!`

This warning should not appear.  Rather, "--force" should be scrubbed out of the list of "options" passed to the formula (or should be whitelisted, or whatever).

This warning is especially jarring (and potentially confusing) when a user has just tried `brew install foo` (without the "--force") and been told by `brew` to "try again but with --force".  (E.g., perhaps `foo` is keg-only and and older version is already installed.)

**Comment by MikeMcQuaid** [comment]
Fixed. Thanks for the report.
