### ISSUE TITLE
Feature Request: allow brew pin to work on versions other than the latest version of a formula

### ISSUE THREAD

**Issue by dljsjr** [Homebrew/brew#206]
It would be very nice if `brew pin` could be used to pin to an older version of a formula as long as it's already installed on the system (e.g. it is accessible via `brew switch`), either by doing `brew switch` then pinning or allowing `pin` to accept a version number similar to `switch`.

I recently ran in to a problem with `ffmpeg`, where a (non homebrew) library I use would only work with ffmpeg 2.8.6. ffmpeg is not in `homebrew/versions`, but luckily I had 2.8.6 installed so it was easy enough to `brew switch` to this version. However there was no way for me to keep it from getting upgraded in the future, meaning every time that the formula updated I would need to re-run `brew switch`. I've been fighting this for several months now. Just today to resolve this, I ended up increasing the depth of homebrew-core on disk and manually checking out an old version of the ffmpeg formula, reinstalling, then pinning.

`pin_formula.rb` looks like it supports this via the `pin_at(version)` method, but looking at `pin.rb` in brew's cmd directory it looks like the subcommand is not set up to handle this use case very well at all unless an awkward syntax is introduced as the argument vector is assumed to just contain a list of formulae to be pinned. So possibly switching the `pin()` in `pin_formula.rb` that calls through to `pin_at(version)` to use the current version instead of the max version?

I don't really know much Ruby but I could take a stab at a PR for this if changing this behavior isn't totally offensive to anybody.

**Comment by DomT4** [comment]
>  However there was no way for me to keep it from getting upgraded in the future, meaning every time that the formula updated I would need to re-run brew switch.

This part is actually by design, if I understand what you're saying here. If you have other things installed that `depends_on "ffmpeg"` and they get upgraded, your `ffmpeg` is dragged along with it.

This is because we only test and bottle the latest against the latest in core formulae and it's a rabbit-hole of misery to open ourselves up to configurations where people keep increasingly old versions around and used with up-to-date other formulae and don't expect chaos.

If you're saying that you have `ffmpeg` installed but nothing that `brew uses ffmpeg` I'm more sympathetic to the idea an `upgrade` later shouldn't bump it, if that's happening for you.

**Comment by dljsjr** [comment]
> If you're saying that you have ffmpeg installed but nothing that brew uses ffmpeg I'm more sympathetic to the idea an upgrade later shouldn't bump it, if that's happening for you.

This is the idea. I do not have anything from homebrew that uses ffmpeg, only internal libraries that need it, and I had to come up with my own way to pin at an older version because I didn't pin it when 2.8.6 was the newest version back in February.

**Comment by ilovezfs** [comment]
This usually works
```
bash-3.2$ brew log ffmpeg | grep bottle|grep 2.8|head -1
    ffmpeg: update 2.8.6 bottle.
bash-3.2$ cd /usr/local/Library/Taps/homebrew/homebrew-core
bash-3.2$ git reset --hard 7c988bdb8ffb9d2ffcce7606a43e360d98e4982c
HEAD is now at 7c988bd ffmpeg: update 2.8.6 bottle.
bash-3.2$ HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
==> Installing dependencies for ffmpeg: x264, lame, libvo-aacenc, xvid
==> Installing ffmpeg dependency: x264
==> Downloading https://homebrew.bintray.com/bottles/x264-r2601.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/x264-r2601.el_capitan.bottle.tar.gz
==> Pouring x264-r2601.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/x264/r2601: 10 files, 3.3M
==> Installing ffmpeg dependency: lame
==> Downloading https://homebrew.bintray.com/bottles/lame-3.99.5.el_capitan.bottle.1.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/lame-3.99.5.el_capitan.bottle.1.tar.gz
==> Pouring lame-3.99.5.el_capitan.bottle.1.tar.gz
🍺  /usr/local/Cellar/lame/3.99.5: 26 files, 2M
==> Installing ffmpeg dependency: libvo-aacenc
==> Downloading https://homebrew.bintray.com/bottles/libvo-aacenc-0.1.3.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/libvo-aacenc-0.1.3.el_capitan.bottle.tar.gz
==> Pouring libvo-aacenc-0.1.3.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libvo-aacenc/0.1.3: 16 files, 297.5K
==> Installing ffmpeg dependency: xvid
==> Downloading https://homebrew.bintray.com/bottles/xvid-1.3.4.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/xvid-1.3.4.el_capitan.bottle.tar.gz
==> Pouring xvid-1.3.4.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/xvid/1.3.4: 9 files, 1.3M
==> Installing ffmpeg
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-2.8.6.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/ffmpeg-2.8.6.el_capitan.bottle.tar.gz
==> Pouring ffmpeg-2.8.6.el_capitan.bottle.tar.gz
==> Caveats
FFmpeg has been built without libfaac for licensing reasons;
libvo-aacenc is used by default.
To install with libfaac, you can:
  brew reinstall ffmpeg --with-faac

You can also use the experimental FFmpeg encoder, libfdk-aac, or
libvo_aacenc to encode AAC audio:
  ffmpeg -i input.wav -c:a aac -strict experimental output.m4a
Or:
  brew reinstall ffmpeg --with-fdk-aac
  ffmpeg -i input.wav -c:a libfdk_aac output.m4a
==> Summary
🍺  /usr/local/Cellar/ffmpeg/2.8.6: 228 files, 44.5M
bash-3.2$ brew pin ffmpeg
bash-3.2$ git reset --hard origin/master
HEAD is now at 965c7ad mmix: update 20131017 bottle.
bash-3.2$ brew outdated
ffmpeg (2.8.6 < 3.0.2)
bash-3.2$ brew upgrade
==> No packages to upgrade
==> Not upgrading 1 pinned package:
ffmpeg 3.0.2
bash-3.2$
```

**Comment by ilovezfs** [comment]
If you actually need to pin something in a way that isn't subject to the whims of reverse dependencies' upgrade paths, you'd need to maintain a tap with that version and all its requirements.

It might be convenient if `brew upgrade` of another formula wasn't allowed to override an explicit pin, but that also would need to cause the upgrade of the reverse dependency to fail unless some other kind of force were applied. Such a change is unlikely to be made, I think.

**Comment by mikemcquaid** [comment]
This kinda comes down to a general request for Homebrew to support versions better. This is something we're exploring but, as @ilovezfs, the best bet if you need control over versions is to maintain your own tap for them. Sorry and thanks for the issue.
