### ISSUE TITLE
Outdated note about homebrew-versions tap

### ISSUE THREAD

**Issue by gmile** [Homebrew/brew#2064]
Running `brew versions` suggests that I use `homebrew-versions`:

```
$ brew versions elixir
Error: The `versions` command is no longer supported.
You can use the homebrew-versions tap instead:
  https://github.com/Homebrew/homebrew-versions
Or use `brew log` to browse the git history.
```

However, the [readme for `homebrew-versions`](https://github.com/homebrew/homebrew-versions) says it's deprecated, as the feature is now supported directly by the core.

**Issue 1**: should the note be more specific for those looking for an older version of formula?

Running `brew log elixir` as suggested in the note above brings me to an incomplete history. It was weird until I realized brew's repo is probably a shallow clone of a repo.

**Issue 2**: I think the incomplete history should not come up as surprise. The above note in `brew versions` could have mentioned the fact of brew clones shallowness. Also, maybe a better note could be added regarding what to do when someone's is looking for an older version of a formula? Something like:

> If you're looking for an older version of the formula, try this:
> 1. Find a respective commit on github by scrolling the history for a formula in question: https://github.com/Homebrew/homebrew-core/commits/master/Formula/elixir.rb
> 2. Install the formula by specifying full URL to gihub:
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/59d7802e40ffbe2c7c840354530bc62b5a1538f9/Formula/elixir.rb

**Comment by MikeMcQuaid** [comment]
> Running brew versions suggests that I use homebrew-versions:

I get `Error: Unknown command: versions`.

> It was weird until I realized brew's repo is probably a shallow clone of a repo.

`brew log` notifies you if it's using a shallow clone.

Thanks for the suggestions but passing on these for now.
