### ISSUE TITLE
brew install --universal --java subversion fails on SQLite version

### ISSUE THREAD

**Issue by RonBallard** [Homebrew/brew#2068]
Last 15 lines from /Users/ronballard/Library/Logs/Homebrew/subversion/03.configure:
configure: WARNING: no suitable sqlite found in /usr/local/opt/sqlite

An appropriate version of sqlite could not be found.  We recommmend
3.7.15.1, but require at least 3.7.12.
Please either install a newer sqlite on this system

or

get the sqlite 3.7.15.1 amalgamation from:
    http://www.sqlite.org/sqlite-amalgamation-3071501.zip
unpack the archive using unzip and rename the resulting
directory to:
/private/tmp/subversion-20170220-78522-qsoqzz/subversion-1.9.5/sqlite-amalgamation

configure: error: Subversion requires SQLite

           *           *           *           *           *           *           *

I have SQLite3 3.17.0, which is much later:

Mac$ sqlite3
SQLite version 3.17.0 2017-02-13 16:02:40

I tried the second option (sqlite 3.7.15.1 amalgamation) but that didn't work, it asked me to do the same again with a different number/name in the /subversion-... directory.

I ran brew update and brew doctor.  brew doctor said:

Mac$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /Library/PostgreSQL/9.3/bin/
Mac$ 

That was after I'd taken the other advice.  The directory ending in a slash doesn't seem right.  I've checked it and it seems fine.

brew config says:

Mac$ brew config
HOMEBREW_VERSION: 1.1.10-2826-gafb66d0
ORIGIN: https://github.com/Homebrew/brew
HEAD: afb66d0c69bb7cf691125d082d9e45724d479723
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d861f1e9ca7b80c081c7450c950f6f1adf5fe586
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /opt/local/bin/perl => /opt/local/bin/perl5.16
Python: /usr/bin/python
Ruby: /opt/local/bin/ruby
Java: 1.8.0_31
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
Mac$ 

Thanks,

Ron
ron@thedatastudio.net

**Comment by MikeMcQuaid** [comment]
We don't support `--universal` any more I'm afraid and the option will be removed soon. Also, in future please follow the issue template which will tell you the information we need and what repository to file it at.

**Comment by Lxjazni7** [comment]
I have the same problem How do I solve

**Comment by Lxjazni7** [comment]
OK user new code >>  brew install subversion --with-java

**Comment by ilovezfs** [comment]
What does that mean?

**Comment by Lxjazni7** [comment]
brew install --universal --java subversion can't install
use brew install subversion --with-java success

**Comment by ilovezfs** [comment]
The problem here is that the caveat in subversion.rb wasn't updated when sqlite had the universal option removed: https://github.com/Homebrew/homebrew-core/blob/master/Formula/subversion.rb#L94-L106
