### ISSUE TITLE
Error message from brew update

### ISSUE THREAD

**Issue by vd1** [Homebrew/brew#2098]
Every now and then I get the following message 

`celodv:ml V$ brew update
Updated 1 tap (caskroom/cask).
No changes to formulae.
Error: Failed to link all completions, docs and manpages:
  Permission denied - (../../../Homebrew/completions/zsh/_brew, /usr/local/share/zsh/site-functions/_brew)`

If brew upgrade a second time, the message disappears; brew doctor reports no problem.
Apart from that everything is fine.

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by vd1** [comment]
oops sorry:

`celodv:Code V$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /usr/local/texlive/2014/bin/universal-darwin/`

`celodv:Code V$ brew config
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eca8c042fa6d53fe2a23810d8829709b044eb75e
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
`

**Comment by MikeMcQuaid** [comment]
Try to `sudo chown -R $USER:admin /usr/local/*`

**Comment by vd1** [comment]
thanks!

**Comment by danilopolicarpos** [comment]
great, thanks
