### ISSUE TITLE
Statistics without asking

### ISSUE THREAD

**Issue by TiZeRa** [Homebrew/brew#210]
Since I can not reply to the topic.

https://github.com/Homebrew/brew/issues/164

No, no, no... you assume everybody sees that one line.... buries into a command who in the most part the output is only read when something goed wrong... it can tell you that without any data collection, and you won;t find that anlysis in your data set. From my point of view you hid an one-liner somewhere people are not going to look easily... that downright sneaky.

Make it like this opensource and human worthy like after all other messages show such that it is notice:

*************************************
* WARNING STATICTICS WILL BE SEND TO SERVER
*
* We are sending:  blabla
*
*  see http://blbla 
*  to disable it
*
******

and show that for like 6 months before you remove it...  and assume as default the user is ok with it. 

Have some respect for the user, the only reason I notice was my firewall NOT the little line. And there is still the point what are you sending and why? 

btw if you are really a good guy just ask the user if he wan't to a simple (yes/no) (i agree/not agree) would just fix al problems instead of sneaky sneaky...

Not solved and not closed

**Comment by DomT4** [comment]
> From my point of view you hid an one-liner somewhere people are not going to look easily... that downright sneaky.

For a start, it's not a one liner. It's an entire block of a message, and now has its own separate command `brew analytics` which offers a simple on/off switch.

If you have something productive to add, please let us know. Otherwise there's a queue of people who have insisted we're not decent humans these past couple of weeks you can join, Thanks.
