### ISSUE TITLE
Add the ability to suppress CLT version check

### ISSUE THREAD

**Issue by vmarkovtsev** [Homebrew/brew#2101]
I am using Sierra with Command Line Tools 7.3. I cannot upgrade CLT to newer version because even the latest NVIDIA CUDA compiler does not support 8.0+ and I am not able to build GPGPU code (like this: [src-d/kmcuda](https://github.com/src-d/kmcuda)). There is an option to disable XCode version check on Travis but there is no such option for CLT. I am not a dedicated Mac programmer and I don't want to install the full XCode monster. Effectively, I am unable to use Homebrew and have to short circuit `check_clt_minimum_version` in `extend/os/mac/diagnostic.rb`.

Please add some magic environment variable, e.g. TRAVIS to disable CLT version check.

**Comment by MikeMcQuaid** [comment]
Sorry, the 7.3 CLT has known, unresolvable issues with Sierra so we won't do this.

**Comment by vmarkovtsev** [comment]
All right. It works perfectly fine for bottles though. For those like me, these are the instructions how to disable the 8.0 check:

1. `export HOMEBREW_NO_AUTO_UPDATE=1`
2. Edit `/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb`, insert `return` in the beginning of `check_clt_minimum_version`
