### ISSUE TITLE
GCC5.3 internal compiler error

### ISSUE THREAD

**Issue by insomnia9527** [Homebrew/brew#2102]
Using GCC 5.30 , I met a bug:

**[ 88%] Building CXX object gui/gui/CMakeFiles/Gui.dir/src/TGIcon.cxx.o
[ 88%] Building CXX object geom/geompainter/CMakeFiles/GeomPainter.dir/src/TGeoPainter.cxx.o
/home/user/tools/root/geom/geompainter/src/TGeoChecker.cxx: In member function 'Double_t TGeoChecker::TimingPerVolume(TGeoVolume*)':
/home/user/tools/root/geom/geompainter/src/TGeoChecker.cxx:710:10: internal compiler error: Illegal instruction
 Double_t TGeoChecker::TimingPerVolume(TGeoVolume *vol)
          ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew/issues> for instructions.
make[2]: *** [geom/geompainter/CMakeFiles/GeomPainter.dir/build.make:105: geom/geompainter/CMakeFiles/GeomPainter.dir/src/TGeoChecker.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 88%] Building CXX object montecarlo/eg/CMakeFiles/EG.dir/src/TParticleClassPDG.cxx.o
[ 88%] Building CXX object montecarlo/eg/CMakeFiles/EG.dir/src/TParticlePDG.cxx.**

I don't know weather it's a compiler problem, but the bug report said I should submit a report here, maybe you can help me.

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.
