### ISSUE TITLE
Feature request - brew cleanup exclusion list

### ISSUE THREAD

**Issue by kitsguru** [Homebrew/brew#2103]
I believe I saw a discussion on this sometime ago but have not been able to find it again. I think it was decided not to do this.

That being said I have a use case that warrants reopening the issue.
I install multiple versions of php and use sphp to switch them out while testing. 

I need (would like?) to be able to run cleanup but exclude the non linked versions of php. 

I know others have expressed similar issues with keeping older version. The only current option is to cleanup old versions manually and leave the excluded ones. This is very time consuming to say the least and a real pain...

I humbly request that this be revisited

**Comment by MikeMcQuaid** [comment]
The way to keep multiple versions living side-by-side is to have multiple versions formulae installed e.g. like in the homebrew/php tap. If you need different version please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!
