### ISSUE TITLE
core-tap not updating

### ISSUE THREAD

**Issue by Kyslik** [Homebrew/brew#2111]
>If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

(done that)

- [x] Ran `brew update` (twice) and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug reports:
Basically core tap is not updating. See core tap last commit: **4 months** which is I guess wrong.

```
$ brew config
HOMEBREW_VERSION: 1.1.10-165-gc7121f6be
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c7121f6be50e44784e3e29114617c29715bd9c0f
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c1c345c550a7ae3a1e41151e4008fc1a215f0d4f
Core tap last commit: 4 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_92, 1.8.0_66, 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: N/A
```

**Comment by ilovezfs** [comment]
```
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core status
```

**Comment by Kyslik** [comment]
Oh,  I am on my own forgotten branch... silly me!

Thanks

**Comment by ilovezfs** [comment]
you're welcome

**Comment by MikeMcQuaid** [comment]
@ilovezfs worth adding either a non-`master`/`stable` branch warning into `brew doctor` or branch name into `brew config`?

**Comment by ilovezfs** [comment]
@MikeMcQuaid https://github.com/Homebrew/legacy-homebrew/pull/48873 lol

**Comment by ysalmi** [comment]
I just want to add that I fell prey to this issue and have been scratching my head for a couple hours until I came across this issue. Thank you for the solution.
