### ISSUE TITLE
Analytics opt-out link is broken

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Homebrew/brew#2168]
> ==> Homebrew has enabled anonymous aggregate user behaviour analytics.
> Read the analytics documentation (and how to opt-out) here:
>  https://git.io/brew-analytics

The link is broken.

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by MikeMcQuaid** [comment]
I've updated this in https://github.com/Homebrew/install/commit/77945f23a3458435258f3a41b051ac1f96014963 but this should have been filed in https://github.com/Homebrew/install and you should always fill out the issue template in future, thanks.

**Comment by ahmetalpbalkan** [comment]
Thanks, sorry for the ignorance on my part.
