### ISSUE TITLE
feature request: `brew ls --json|grep '"installed_on_request":true'`

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#2172]
@MikeMcQuaid @ilovezfs 

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

couldn't find in docs or recent issues or PR's a way to list attributes for installed formulas; eg: (among many other use cases): I want to list all the formulas I've installed directly (via brew install X Y Z as opposed to via a dependency). I see https://github.com/Homebrew/brew/pull/1813/files stores the info (installed_as_dependency) but don't see a way to retrieve that info via cmd line. In fact `man brew|grep installed_on_request ` is empty.

* Option 1: `brew ls --installed_on_request ` to only show formulas tagged with `installed_on_request`
This fixes this particular issue but doesn't scale (eg what if i want to see unpinned formulas that are installed_on_request, etc)

So I prefer option 2 below: it's more flexible / scalable (simpler api: just a single `--json`). 

* Option 2: more generally, provide instead `brew ls --json` which would list all formulas along with their attributes formatted as json (1 per line). Then a user can call simply`brew ls --json|grep '"installed_on_request":true'`.  Note: other formats than json could be used if you don't like json, but would be nice to have a standard format to make it easier to integrate with other tools.
It could also accept an optional formula to only show attributes for this formula. 

Eg:
```
brew ls --json
{"name":"curses","full-name":"homebrew/dupes/ncurses","installed_on_request":true,"pinned":false,...}
{"name":"dmd","full-name":"dmd","installed_on_request":true,"pinned":false,...}
```

json fields: we could start with the most basic ones (eg as extracted from https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula.rb ) and add more as needed, eg:
```
name
full-name
tap
version
installed_on_request
pinned
date-installed
install-time-seconds #how long did it take to install
number-of-files-generated
disk-usage # du -sh $(brew --cellar $formula)
binaries-generated # json array containing all binaries generated
install-failed #`brew install X` failed; could keep track of that
#etc
```

This would be extremely useful to have and expose the relevant data with very little added complexity for end-user (just a single `--json` flag).

## follow-up: mongo queries

once this is implemented, it would be relatively easy (and fast) to populate a `mongodb` database with all the output from `brew ls --json` so a user could simply write a mongo query:
```
# find name's of slow to install formulas
> db.brew.find({install-time-seconds: {$gt:3600}},{name:1})
#etc...
```

EDIT: just found `brew info --json=v1 `

**Comment by ilovezfs** [comment]
>EDIT: just found brew info --json=v1

:tada:
