### ISSUE TITLE
Problems installing Homebrew on Mac OS X 10.10.5

### ISSUE THREAD

**Issue by kiwisherk** [Homebrew/brew#2192]
sh-3.2$ brew config
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2401de493d68f341e34b926883f39e404c88173b
Last commit: 6 hours ago
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Error: undefined method `null?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/system_config.rb:146:in `dump_verbose_config'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/system_config.rb:42:in `dump_verbose_config'
/usr/local/Homebrew/Library/Homebrew/cmd/config.rb:12:in `config'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by vitorgalvao** [comment]
From the issue template:

> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.
