### ISSUE TITLE
More discussion surrounding repo split / architectural change to the brew project

### ISSUE THREAD

**Issue by diclophis** [Homebrew/brew#22]
### Feature Requests:

My request is for more discussion in the future surrounding architectural / repo-split / convergence (as in the case of the homebrew-cask convergence). We heavily utilize the brew project to fully automate the setup of our workstations... in the past 6 months or so there have been 3 things that have disrupted this automatic workflow...

1. Changes to package names / versions ... things like making `brew install elasticsearch` install version 2.x, instead of making an `elasticsearch-2.0` package name, and keeping the original 1.0 version tree for the `elasticsearch` package name
2. The convergance of the brew-cask system into the main brew system
3. The most recent is the split of the Formula repos out of the main-line repo

It seems like these changes are more so "just announced as they happen" instead of a more preferable strategy that could include a pre-announcement, discussion, voting, and ideally some sort of news/blog coverage (for example, getting an article on the front page of a couple popular developer centric sites).

Thank you for your consideration...

### all in all this is the sum of the changes to fix our broken automated ansible workstation setup

	diff --git a/ansible/roles/redis/tasks/main.yml b/ansible/roles/redis/tasks/main.yml
	index 93a7abd..8935438 100644
	--- a/ansible/roles/redis/tasks/main.yml
	+++ b/ansible/roles/redis/tasks/main.yml
	@@ -9,7 +9,7 @@
	 
	 # git fetch origin 96de5297df870:refs/remotes/origin/foo-commit
	 - name: get correct version of redis
	-  shell: cd /usr/local/Library && (git fetch --unshallow origin || true) && git checkout d010d61a8cbd92c8ec9b088cb5a6d259209d4b07 Formula/redis.rb
	+  shell: cd /usr/local/Library/Formula && (git fetch origin || true) && git checkout 2190ece4b7d6fbcd477234aeaa160bad84fc12d6 redis.rb
	 
	 - name: install redis brew package
	   command: creates=/usr/local/Cellar/redis/3.0.6 brew reinstall redis
	@@ -26,4 +26,4 @@
	   shell: launchctl unload /Library/LaunchDaemons/homebrew.mxcl.redis.plist
	 
	 - name: unset version of redis
	-  shell: cd /usr/local/Library && (git fetch --unshallow origin || true) && git checkout master Formula/redis.rb
	+  shell: cd /usr/local/Library/Formula && (git fetch origin || true) && git checkout master redis.rb

**Comment by tdsmith** [comment]
I'm glad you were able to adapt quickly.

Wrt your first point, Homebrew formulas in Homebrew/homebrew-core almost always refer to the newest version of a package, including major version changes. The versioned formulas in homebrew/versions are typically tied to a minor version and may be more suitable for you. If one does not exist, you are welcome to contribute one.

Otherwise, you should consider our command line interface the stable API. If you rely on understanding Homebrew's internals, your work may break without warning.

**Comment by mikemcquaid** [comment]
> Changes to package names / versions ... things like making brew install elasticsearch install version 2.x, instead of making an elasticsearch-2.0 package name, and keeping the original 1.0 version tree for the elasticsearch package name

It's worth noting this is how Homebrew has always worked. The alternative is you should only use formulae from https://github.com/Homebrew/homebrew-versions or maintain your own tap and only use those formulae.

> The convergance of the brew-cask system into the main brew system

You'll need to provide more information if you want us to understand this.

> It seems like these changes are more so "just announced as they happen" instead of a more preferable strategy that could include a pre-announcement, discussion, voting, and ideally some sort of news/blog coverage (for example, getting an article on the front page of a couple popular developer centric sites).

We're not going to have voting for these things. Discussion and pre-announcement happen on Homebrew's issue tracker. We cannot control how these things hit the front-page of news sites.

We can't be considered responsible for a system you've built on top of Homebrew breaking and I don't think a two line change is a big deal, honestly. If you want to use tools that are officially supported there is https://github.com/Homebrew/homebrew-bundle and the previously mentioned homebrew-versions for these purposes. https://github.com/mikemcquaid/strap is also designed for initial system setup.

> Otherwise, you should consider our command line interface the stable API. If you rely on understanding Homebrew's internals, your work may break without warning.

This cannot be emphasised more strongly. Your system will continue to break if you make assumptions about paths and revisions.

**Comment by DomT4** [comment]
> The alternative is you should only use formulae from https://github.com/Homebrew/homebrew-versions or maintain your own tap and only use those formulae.

&

>  The versioned formulas in homebrew/versions are typically tied to a minor version and may be more suitable for you. If one does not exist, you are welcome to contribute one.

I'll add on top of this, Versions isn't a dumping ground for everyone's pet projects. It has to meet the eligibility criteria and it has to remain testable by whichever 2 or 3 OS X versions we build against on CI. If you want absolute stability long-term on specific formula with a firm promise of no change please do set up your own tap. 

_Everything_ we can do in our taps you can do in one of your own, including using things like Travis for CI. There are Travis configuration files in the various repos which you can use as a template, as desired.

> It seems like these changes are more so "just announced as they happen" instead of a more preferable strategy that could include a pre-announcement, discussion, voting, and ideally some sort of news/blog coverage (for example, getting an article on the front page of a couple popular developer centric sites).

We try our best to pre-announce things where necessary.

The split PR and Issues had been sat on our GitHub tracker for upwards of a couple months prior to it happening if my memory hasn't misled me. We announced the deprecation of `sha1` 18+ months in advance of that being enforced later this year. We let `md5` sit around for several years with warnings prior to killing it last year and _that still_ "snuck up" on more than a few tap owners.

There's no medium we can use that every Homebrew user will see or remember to check, sadly. If you care about Homebrew fundamentals watching the GitHub repo is one of the more comprehensive ways to keep on top of it, and perhaps ironically given this Issue you'll find that easier now core and formulae no longer share one repo.

**Comment by diclophis** [comment]
@mikemcquaid the brew-cask issue is related to this changed noted at the top of the README in the brew cask repo: https://github.com/caskroom/homebrew-cask#important-december-2015-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system

... I can't find any mention of that change in the announce mailing list ...

As far as "use cli API" and or "use a tap" methods of installing specific versions I think this stack-overflow question/answer discussion outlines most of my frustration ... on the surface there seems to be several "supported methods" ... all of which seem to have changed at some point over the history of the project: http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula

In comparison, other package management systems typically include specifying a version by a simple `--version` CLI argument, or have more aggressively static repos that don't bump versions without a whole "distro upgrade" .... i.e. any `apt` based package repo...

In general brew has "just worked" more than it has "been updated and broken our stuff" so we have not in the past given much weight to the idea of running our own taps / fork. I will discuss the recommendations posted here with my organization (I think we will likely adopt our own set of taps for the super important stuff and rely on the community taps for the remainder of our setup).

I will also try to monitor the brew PRs/Issue-tracker, and, I am now subscribed to the mailing list... I feel comfortable closing this issue out... please just remember that part of what makes `brew` such a great project is that the community can rely on it for getting software installed in a reasonable automatable way (in particular also for getting the latest more-secure version of several CLI utilities). And that big shuffles in the way the project function should be treated with as much gravitas as possible.

**Comment by tdsmith** [comment]
> on the surface there seems to be several "supported methods"

For what it's worth, we support methods 2 (use a Homebrew/versions formula) and 4 (write your own versioned formula). The `versions` command was removed because using formulas from git history cannot be made to work reliably. Thanks for your feedback!
