### ISSUE TITLE
Feature request: pre/post-install hooks for scripting and plugins

### ISSUE THREAD

**Issue by dbkaplun** [Homebrew/brew#2202]
I propose that pre- and post-installation hooks should be added as supported functionality in homebrew. This would be useful in a wide variety of circumstances:

* Automated backups of `brew leaves`/`brew cask list` to store installed packages
* Installation of custom icons for Casks via post-install hook (see caskroom/homebrew-cask#30263)
* Many other such use cases.

One implementation could use environment variables (e.g. `HOMEBREW_HOOK_PREINSTALL`, `HOMEBREW_HOOK_POSTINSTALL`) to find and call the hook script with the arguments passed to `brew`. Another more complicated approach would involve a configuration file to set the script paths.

**Comment by MikeMcQuaid** [comment]
Thanks for the suggestion but passing on this. It's been requested a few times before but the best thing is to wrap your `brew` calls with something that does pre/post hooks rather than needing this in Homebrew itself.



> Automated backups of brew leaves/brew cask list to store installed packages

Note `brew bundle dump` is a better fit for this.
