### ISSUE TITLE
Formula-Cookbook.md should explain how to deal with libtool

### ISSUE THREAD

**Issue by johnhawkinson** [Homebrew/brew#2229]
The Formula Cookbook should explain how to deal with libtool.

It's easy enough to figure out that `libtool` needs to become `glibtool`, but it's not at all clear should should happen on installation. 

`Cleanup.rb` removes installed .la files, so it seems like running `lib.install foo.la` isn't the right thing. Some formulas (ok, just `rtmidi`?) seem to run `lib.install Dir[".libs/*.a", ".libs/*.dylib"]` which seems like an abstraction violation.

In my particular case, I have a Makefile with no install rule, and a build system that uses libtool. What does Homebrew want to install the library?

**Comment by johnhawkinson** [comment]
My attempt was https://github.com/Homebrew/homebrew-core/pull/10431.

**Comment by MikeMcQuaid** [comment]
Let's talk about it there. I'm not really sure what you're being asked and why it would be necessary to install `.la` files. Ideally `make install` handles all such things instead; if there's no `make install` then submitting one upstream is the best bet for other packagers to have an easier life too.
