### ISSUE TITLE
Invoking non-llvm_clang compiler when building with brew LLVM OpenMP results in xcrun script failing

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/brew#2237]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

I'm fairly certain this is my fault...

Normally, when `llvm_clang` is invoked, Cmd#tool replaces `llvm_clang` with the path to the clang executable installed as part of brew LLVM. However, when `clang` is invoked, brew replaces `clang` with `llvm_clang`, which causes the `xcrun` script to fail:

```
bash-3.2$ llvm_clang
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
bash-3.2$ clang

Failed to execute llvm_clang -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/tcl-tk/include -I/usr/local/opt/ncurses/include -I/tmp/brew-llvm-openmp -L/usr/local/opt/tcl-tk/lib -L/usr/local/opt/ncurses/lib -L/usr/local/lib -L/tmp/brew-llvm-openmp -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

Xcode and/or the CLT appear to be misconfigured. Try one or both of the following:
  xcodebuild -license
  sudo xcode-select -switch /path/to/Xcode.app

bash-3.2$
```

This occurs when using brew LLVM to compile `fftw --with-mpi --with-openmp`. `./configure` tests the OpenMPI installation by invoking `/usr/local/bin/mpicc`, which in turn invokes `clang`, which causes configuration to fail with the above error.

A dirty fix would be to replace the `HOMEBREW_CC` environment variable with the full path to the clang executable installed as part of brew LLVM, but obviously a cleaner fix would be preferred.

Thoughts?

**Comment by MikeMcQuaid** [comment]
> A dirty fix would be to replace the HOMEBREW_CC environment variable with the full path to the clang executable installed as part of brew LLVM

Not sure I understand the dirtiness here; seems ok to me?

**Comment by aw1621107** [comment]
I thought that HOMEBREW_CC wasn't supposed to be a full path, given the way Cmd#tool was written. I guess changing it wouldn't be too bad, though...

**Comment by MikeMcQuaid** [comment]
> I thought that HOMEBREW_CC wasn't supposed to be a full path, given the way Cmd#tool was written.

In that case: do we just need to fix up the PATH?

**Comment by aw1621107** [comment]
That might work? Only thing that comes to mind is that the LLVM bin/ directory contains a few executables that are also in the default Xcode toolchain, and I'm not sure whether finding those first would break anything. It doesn't look too likely, though:

```
rp:bin awang$ unalias ls
rp:bin awang$ ls >> ~/Desktop/bin
rp:bin awang$ rm ~/Desktop/bin
rp:bin awang$ ls /usr/local/opt/llvm/bin/ >> ~/Desktop/bin
rp:bin awang$ ls /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ >> ~/Desktop/bin
rp:bin awang$ cat ~/Desktop/bin | sort | uniq -c | sort | tail -n 10
   1 yaml2obj
   2 clang
   2 clang++
   2 llvm-cov
   2 llvm-dsymutil
   2 llvm-dwarfdump
   2 llvm-nm
   2 llvm-objdump
   2 llvm-profdata
   2 llvm-size
```

And I'm not entirely 100% sure I'm correct about whether `HOMEBREW_CC` is supposed to be a full path or not...

**Comment by MikeMcQuaid** [comment]
> Only thing that comes to mind is that the LLVM bin/ directory contains a few executables that are also in the default Xcode toolchain, and I'm not sure whether finding those first would break anything.

I think it's reasonable (perhaps even better) for those to be used if it's using the LLVM Clang.

**Comment by aw1621107** [comment]
That is true. I'll give that a shot then.

**Comment by MikeMcQuaid** [comment]
Pretty sure this will be fixed by https://github.com/Homebrew/brew/issues/2298 but let me know if not @aw1621107.
