### ISSUE TITLE
Bogus "empty installation" error with bin.install

### ISSUE THREAD

**Issue by johnhawkinson** [Homebrew/brew#2238]
As encountered in https://github.com/Homebrew/homebrew-core/pull/10431#issuecomment-283126188, posting a minimal test-case here as requested by @MikeMcQuaid.

Minimal test case formula: https://gist.github.com/johnhawkinson/311cf473352678bf6bdb2b603f109bd0#file-test-empty-rb

where the install rule is:
```ruby
  def install
    system "touch", "test-empty"

    bin.install "test-empty"
  end
```

produces:
```
==> touch test-empty
Error: Empty installation
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:681:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:315:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:47:in `reinstall_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:18:in `block in reinstall'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:13:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

or with this patch to print out some more:
```diff
--- a/Library/Homebrew/formula_installer.rb
+++ b/Library/Homebrew/formula_installer.rb
@@ -677,6 +677,15 @@ class FormulaInstaller
 
     formula.update_head_version
 
+    if !formula.prefix.directory?
+      ohai "prefix.directory?: "
+      ohai formula.prefix
+      ohai formula
+      ohai formula.prefix.directory?
+    end
+    if Keg.new(formula.prefix).empty_installation?
+      ohai "keg empty?"
+    end
     if !formula.prefix.directory? || Keg.new(formula.prefix).empty_installation?
       raise "Empty installation"
     end
```

I get:
```
==> touch test-empty
==> prefix.directory?: 
==> /usr/local/Cellar/test-empty/HEAD-cb10f0
==> test-empty
==> false
```

And of course, the directory is not empty:
```sh
pb3:~ jhawk$ ls -lR /usr/local/Cellar/test-empty/
total 0
drwxr-xr-x  6 jhawk  admin  204 Feb 28 14:07 HEAD-cb10f50

/usr/local/Cellar/test-empty//HEAD-cb10f50:
total 24
-rw-r--r--  1 jhawk  admin   593 Feb 28 14:07 INSTALL_RECEIPT.json
-rw-r--r--  1 jhawk  staff  1270 Feb 28 13:59 LICENSE.txt
-rw-r--r--  1 jhawk  staff  3281 Feb 28 13:59 README.md
drwxr-xr-x  3 jhawk  admin   102 Feb 28 14:07 bin

/usr/local/Cellar/test-empty//HEAD-cb10f50/bin:
total 0
-rw-r--r--  1 jhawk  staff  0 Feb 28 14:07 test-empty
pb3:~ jhawk$ 
```

**Comment by jonchang** [comment]
`git bisect` says

```
2e916110e4c561b3e4175da099fc795e85ddb822 is the first bad commit
commit 2e916110e4c561b3e4175da099fc795e85ddb822
Author: Vlad Shablinsky <vladshablinsky@gmail.com>
Date:   Wed Jul 13 10:11:59 2016 +0300

    Use HeadVersion for install/reinstall

:040000 040000 18186a96896269059a73ec0dd49954125b130086 175763c3ad0a59f8f0a92b5e2704c8633e57d668 M	Library
```

Which points to #478 as the culprit. The proximate cause is installing to `/usr/local/Cellar/test-empty/HEAD-cb10f50` but `formula.prefix` believes that `/usr/local/Cellar/test-empty/HEAD-cb10f0` is the install directory.

**Comment by jonchang** [comment]
Oops, looks like it's normal for `formula.prefix` to believe that `HEAD-cb10f0` is the install directory because you've specified `version "HEAD-cb10f0"`. A lot of machinery assumes that any formula with a version starting with `HEAD` is, in fact, a HEAD build. Some of this machinery will regenerate the "HEAD version number" from scratch which doesn't match what you've put for `version`.

I think this *is* a bug but I don't know if there's an easy way to fix this as this assumption is built into many parts of Homebrew. The workaround would be "don't do that", i.e., ask upstream to tag a stable release. For now a new audit might be preferable.

**Comment by johnhawkinson** [comment]
Well, I've already requested that upstream tag the release and the requested has been agreed to but not yet acted upon :)

I'll just change the version from `HEAD-cb10f0` to `git-cb10f0`, and that seems to address the issue.

If it is a bug, then probably the right thing to do is to detect when a user specifies a version that will cause problems for Homebrew, and to disallow it and provide an intelligible error so the user knows what went wrong — oh hey, looks like you've already submitted a pull request for just, great!

Thanks.

**Comment by johnhawkinson** [comment]
Oh hey, waitasec. #2245 only addresses this in `brew audit`. I don't think that's sufficient.

If I start to write a formula and I run into this problem, I'm going to bash my head against the wall trying to figure out why it's broken for a long time before I get to `brew audit`. I'd really much rather see the check happen when I run `brew install`. Maybe at that point it could be a warning if not a fatal error (but why?).

Am I wrong here, philosophically? [also, should I put these comments in some other place like a new Issue since this one was Closed? Uncertain on the github workflow.]

**Comment by MikeMcQuaid** [comment]
> Am I wrong here, philosophically?

You're not but given you're the first person to complain about this and this would have been flagged by CI when you opened a PR (which is what we encourage people to do early) I don't think we're going to be working on a better solution for this for now.
