### ISSUE TITLE
Formula with no dependents not listed in `brew leaves`

### ISSUE THREAD

**Issue by sedm0784** [Homebrew/brew#224]
### Bug reports:

I have `camlp4` installed. It is *not* listed in the output of `brew leaves`, but I also don't appear to have any other formulae installed which depend upon it:

    > brew update
    Already up-to-date.

    > brew doctor
    Your system is ready to brew.

    > brew uses --recursive camlp4
    coccinelle                                     opam

    > brew list | grep -E "(camlp4|coccinelle|opam)"
    camlp4

    > brew leaves | grep camlp4

    > brew uses --installed camlp4

    >

Am I misunderstanding either of `brew leaves` or `brew uses`, or is one of these functions broken?

**Comment by sedm0784** [comment]
Forgot to write that the machine is running OS X 10.11.4.

**Comment by mikemcquaid** [comment]
I haven't dug in here but `brew uses` is pretty unreliable, unfortunately.

**Comment by ilovezfs** [comment]
This is actually usually correct. The reason is that the build-time deps aren't displayed by default, but they do affect the output of `leaves`. Do you have any of these
```
haxe
lablgtk
mldonkey
ocaml
opam
orpie
wyrd
```

**Comment by sedm0784** [comment]
PEBCAK. I had somehow missed the `--include-build` switch to `brew uses`. Thanks!
