### ISSUE TITLE
Can't upgrade npm within node@4 on fresh brew install with its only package

### ISSUE THREAD

**Issue by mfn** [Homebrew/brew#2240]
Much has been said about brew/node/npm and permissions problems. Today I've encountered a configuration I haven't seen before, so maybe it's worth reporting.

Prerequisite: completely pristine OSX, no previous Homebrew files around

1. Install brew: `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
2. Observe that `/usr/local/lib` is empty
3. Install node4: `brew install node@4`
4. Observe that there is now `/usr/local/lib/node_modules/`
5. Run `npm install -g npm`

💥 
```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node@4/4.8.0/bin/node" "/usr/local/bin/npm" "install" "-g" "npm"
npm ERR! node v4.8.0
npm ERR! npm  v2.15.11
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rmdir

npm ERR! Error: EACCES: permission denied, rmdir '/usr/local/lib'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, rmdir '/usr/local/lib']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: '/usr/local/lib' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/npm-debug.log
```

At this point things are completely foobar because npm and node_modules were removed and no other version installed.

A quick fix is to uninstall/install the brew package:
`brew uninstall node@4 && brew install node@4`

_Fun fact:_ if there is *anything else* in `/usr/local/lib/`, it works!

Same procedure as above, with a new 5):

1. Install brew: `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
2. Observe that `/usr/local/lib` is empty
3. Install node4: `brew install node@4`
4. Observe that there is now `/usr/local/lib/node_modules/`
5. `touch /usr/local/lib/dummy`
6. Run `npm install -g npm`

Everything works 🚀 

It is my understanding this is more likely a problem of how `npm` itself works and not a brew issue.

Note that this is when upgrading from node4's npm which is version 2.

I did not encounter such problems when I manually jumped e.g. from npm 4 to 3 or such, so this seems not a current bug of npm anymore.

But since an older version of npm is installed here, maybe brew can do something as a workaround.

thanks!

**Comment by MikeMcQuaid** [comment]
> Run npm install -g npm

Why do you need to run this, out of interest?

**Comment by mfn** [comment]
Have node4 with a global default newer version of npm (default is npm2, we want 4).

Is there a better way to achieve this?

**Comment by MikeMcQuaid** [comment]
I don't know, I don't use NodeJS. Regardless, this doesn't seem to be a Homebrew bug, sorry 😭

**Comment by DomT4** [comment]
IIRC this version of `node` isn't even supported by `npm` any more, but if you're going to keep the older `node`s around I'd nudge that they shouldn't ship with anything older than the `3.x` branch of `npm`.

**Comment by MikeMcQuaid** [comment]
@DomT4 Do all old nodes work with new NPMs? I have no idea about this stuff but assuming that's the case 👍 to someone updating these to their newest supported versions.

**Comment by DomT4** [comment]
Up until the end of the 3.x branch at least some of the older Nodes were still actively supported. From the final 3.x release:

```
#### UPDATE SUPPORT MATRIX

With the advent of the second official Node.js LTS release, Node 6.x
'Boron', the Node.js project has now officially dropped versions 0.10
and 0.12 out of the maintenance phase of LTS. (Also, Node 5 was never
part of LTS, and will see no further support now that Node 7 has been
released.) As a small team with limited resources, the npm CLI team is
following suit and dropping those versions of Node from its CI test
matrix.

* [`c82ecfd`](https://github.com/npm/npm/commit/c82ecfdbe0b5f318a175714a8753efe4dfd3e4b3)
  [#14503](https://github.com/npm/npm/pull/14503)
  Node 6 is LTS; 5.x, 0.10, and 0.12 are unsupported.
  ([@othiym23](https://github.com/othiym23))
```

The https://github.com/npm/npm/commit/c82ecfdbe0b5f318a175714a8753efe4dfd3e4b3 commit referenced there shows it should be fine to apply the final 3.x release to 0.10, 0.12, and all the 3/4/5 releases.

**Comment by ilovezfs** [comment]
@DomT4 BTW: currently every node and node@* installation is overwriting npm, so your current npm is going to be whichever npm was bundled with whichever node or node@* you installed last.

**Comment by DomT4** [comment]
@ilovezfs Aye, I know. It was one of the reasons I pushed a while back for Homebrew to drop all of the older Nodes and nudge people towards `nvm` or such instead.

Homebrew really doesn't handle mixing and matching newer/older versions of `node` well, and I'm surprised there haven't been more issues. My recommendation was and pretty much still is that Homebrew only supports versions of Node that can ship/use the same version of `npm` without issue, but I appreciate that's not the direction the project has gone down, so just trying to minimise the variation really.

**Comment by ilovezfs** [comment]
I think the npm's bundled with the node@* need to be confined to their opt prefix.

**Comment by DomT4** [comment]
Did you see my comment the other day in [this thread](https://github.com/Homebrew/homebrew-core/issues/10485)? I think this would be a neat idea for the `keg_only` versions of `node` at least. 

You'd lose your `npm` packages every upgrade but I don't think that's too punishing given how infrequently some of these old `node`s are updated now. Not like you'd be having to `npm install -g the world` every 3 weeks or something.

> Now, Homebrew could steal a page out of something like nvm and essentially write a source script for each version of node that when placed in your shell profile then handled ensuring the desired node and any npm packages installed were in your $PATH and I actually think that'd be a really cool system, but I think if I suggested that I might get glared at by both Mike and ILZ 😸

**Comment by ilovezfs** [comment]
I don't object to that in principle. I just wonder if we're equipped to do that well enough that it would actually be better than some "you really should use nvm for that" advice, a :lollipop:, and sending them on their way.

**Comment by DomT4** [comment]
My advice remains that Homebrew should drop everything not supported by a current `npm` without some kind of significant rewrite of the current system, but I'm not sure how much that's on the table as an option. I'd almost be tempted to literally make `brew install node@4` and such an alias for `brew install nvm` 😅. If culling isn't an option I agree the current system is equivalent to poking a bear with a stick and hoping it doesn't eat you at some point.

**Comment by ilovezfs** [comment]
>My advice remains that Homebrew should drop everything not supported by a current npm

Specifically, that would mean removing which ones?
```
bash-3.2$ ls -1 node@*
node@0.10.rb
node@0.12.rb
node@4.rb
node@5.rb
node@6.rb
```

**Comment by DomT4** [comment]
`node@4` could stay and be updated to a current `npm`. I don't think `npm` love having to do it, but they do still run their test suite against that version of `node` as it was the previous LTS branch. They currently test:

```
node (Or node@7 if you prefer)
node@6
node@4
```

**Comment by DomT4** [comment]
Or well, test isn't fair there. They test pretty much everything even semi-recent, so think "support" more than "test". The point more being if you attempt to use a modern `npm` against one of those unsupported `node` releases and something breaks you're own your own.

**Comment by ilovezfs** [comment]
unique install on request events in the last 30 days
```
node        97,752 (and node --without-npm 2,249)
node@6       5,595
node@4       4,721
node@5         744
node@0.12      403
node@0.10      272
```

**Comment by DomT4** [comment]
It would seem safe enough to kill `node@5`, `node@0.12` and `node@0.10` then and simply update `node@6` and `node@4` to use the same `npm` as `node`.

It wouldn't surprise me if the chunk of `--without-npm` installations there are still as a result of Homebrew's reputation for handling `npm` badly in the past and related gists/blog posts/tweets/etc. There was much drama around that way back 😢.

I do think at some point Homebrew is going to have to drastically change the way `npm` is installed for the versioned formulae at the very least, but if you wanted to punt that down the line this is the way to achieve that.

**Comment by MikeMcQuaid** [comment]
> You'd lose your npm packages every upgrade but I don't think that's too punishing given how infrequently some of these old nodes are updated 

👎  to that.

I'd rather we leave the versioned Nodes in here while they still have non-trivial numbers of installs and aren't causing us user issues. If/when the user issues come in: by all means let's kill them rather than fix them.

**Comment by ilovezfs** [comment]
I don't think it makes sense to blow away the node modules on upgrade, but I do think it's time to remove node@5, node@0.12, and node@0.10.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/10577

**Comment by DomT4** [comment]
> 👎 to that.

Was mostly just throwing around ideas. It's not my preference, but I didn't want to be too much like _"Hey here's my advice take it or leave it bye"_ 😄. We could always chase the `pypy` model if not, which would make them "permanent", but ensure each `node`/`npm` tree was unique.

**Comment by ilovezfs** [comment]
Yeah it seems like it would be best to have one npm and one modules tree per node/node@*.

**Comment by ilovezfs** [comment]
@DomT4 the following changes have been made:

node@0.10: made non-keg_only, conflicts with node and node@0.12 added.
node@0.12: made non-keg_only, conflicts with node and node@0.10 added.
node@4: npm upgraded to 4.1.2.
node@5: deleted.
node@6: npm upgraded to 4.1.2.
node: conflicts with node@0.10 and node@0.12 added.

Revision bumps all around.

**Comment by DomT4** [comment]
Are you happy with the layout of things now or do you want me to plow some time into separating the `npm` trees across each `node@` version in the kind of `pypy` model?

**Comment by ilovezfs** [comment]
@DomT4 I'm not sure yet about that. I would appreciate it if you could take a look at enhancing the node DSL so that it's not hard-coding the assumption that the dependency is `depends_on "node"` as opposed to one of the node@* gang. See https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/node.rb#L17.

Regarding what, if anything, to do about the layout, separating the module trees intuitively seems like the soundest approach but it might be possible to continue with the status-quo, and keep rotating out formulae from keg-only to conflicts-with status as soon as they no longer work with the npm that's designated by upstream for the main node formula. Thoughts?

**Comment by Youthink** [comment]
can be solved like this:

1.delete the path `/usr/local/lib/node_modules` under `npm`
2. ```brew reinstall node```
