### ISSUE TITLE
Discussion: ox as Formula

### ISSUE THREAD

**Issue by dlaxar** [Homebrew/brew#2255]
Hi, 

I recently tried to install  [ox](http://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=1028&context=cs_techreports) and was wondering why it wasn't in homebrew/core. Now I first wanted to start a discussion whether or not this is something we'd want to have in core or if the tool is too old/outdated to put in here. 

I'd be happy to open a PR if it's something we'd want to have!

Thanks in advance,
Daniel

**Comment by MikeMcQuaid** [comment]
It seems like it may be too outdated but if it compiles and installs without patching or `inreplace` we may accept it anyway. Thanks!
