### ISSUE TITLE
brew claims installed package is uninstalled

### ISSUE THREAD

**Issue by johnhawkinson** [Homebrew/brew#2259]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

Homebrew seems to think, according to `brew info youtube-dl`, that I do not have `rtmpdump` installed. And yet I have a `homebrew` managed install of `rtmpdump`. What gives?

```
pb3:~ jhawk$ brew info youtube-dl
Unsetting PERL5LIB to protect you from yourself
youtube-dl: stable 2017.02.27 (bottled), HEAD
Download YouTube videos from the command-line
https://rg3.github.io/youtube-dl/
/usr/local/Cellar/youtube-dl/2014.06.25 (7 files, 1.4MB)
  Poured from bottle on 2014-06-25 at 16:25:19
/usr/local/Cellar/youtube-dl/2016.10.02 (11 files, 1.6MB)
  Poured from bottle on 2016-10-09 at 07:53:08
/usr/local/Cellar/youtube-dl/2016.10.21.1 (11 files, 1.6MB) *
  Poured from bottle on 2016-10-22 at 16:10:51
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/youtube-dl.rb
==> Dependencies
Optional: rtmpdump (uninstalled)
==> Options
--with-rtmpdump
	Build with rtmpdump support
--HEAD
	Install HEAD version
==> Caveats
To use post-processing options, `brew install ffmpeg` or `brew install libav`.

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
pb3:~ jhawk$ brew info rtmpdump
Unsetting PERL5LIB to protect you from yourself
rtmpdump: stable 2.4+20151223 (bottled), HEAD
Tool for downloading RTMP streaming media
https://rtmpdump.mplayerhq.hu
Conflicts with: flvstreamer
/usr/local/Cellar/rtmpdump/2.4 (19 files, 403.6KB) *
  Built from source on 2013-02-25 at 00:23:02
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/rtmpdump.rb
==> Dependencies
Required: openssl (installed)
pb3:~ jhawk$ brew ls rtmpdump --versions
Unsetting PERL5LIB to protect you from yourself
rtmpdump 2.4
pb3:~ jhawk$ ls -l `type -p rtmpdump`
lrwxr-xr-x  1 jhawk  admin  35 Aug 24  2015 /usr/local/bin/rtmpdump -> ../Cellar/rtmpdump/2.4/bin/rtmpdump
pb3:~ jhawk$ 
```

---

> Please replace this section with a brief summary of your issue **AND** the output of `brew config` and `brew doctor`. Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

```
pb3:~ jhawk$ brew config
Unsetting PERL5LIB to protect you from yourself
HOMEBREW_VERSION: 1.1.10-453-g8772b021a2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8772b021a28074a70f84fc19d83af6d897c6fb51
Last commit: 46 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe7d7e31d52f80279bfe7c3cdca8117f7cfe41de
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74, 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11
pb3:~ jhawk$ brew doctor
Unsetting PERL5LIB to protect you from yourself
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
  lesstif
  numpy
  poppler
  python
  test-empty
pb3:~ jhawk$          
```

**Comment by ilovezfs** [comment]
The current version of rtmpdump in Homebrew is 2.4+20151223, which doesn't appear to be what you have installed.

**Comment by johnhawkinson** [comment]
So the message is indicating an **outdated** version (or, more charitably, **upgradable**), but it says **uninstalled**?
Is that not a bug?

**Comment by ilovezfs** [comment]
Typically that shows as just a red x, but because you have HOMEBREW_NO_EMOJI set, it displays "uninstalled" instead of the red x. Technically, the dependency is not installed because the dependency is the current version of rtmpdump, not any version of rtmpdump. You're not alone in being confused by this language though: https://github.com/Homebrew/brew/issues/2002

**Comment by johnhawkinson** [comment]
A red x seems even worse, actually. Seems like it should be some sort of yellow symbol indicating things are maybe-ok but maybe-not. Dunno on that.

Is there support for the idea of changing "uninstalled" to "outdated"? Maybe if there's an appropriate emoji as well?

**Comment by ilovezfs** [comment]
It seems fine the way it is to me as a binary. Either the dependency is installed or it's not. If it's not `brew install --with-rtmpdump youtube-dl` (or `brew install --with-rtmpdump --only-dependencies`) will handle installing it for you. The fact that there was some other version of rtmpdump installed isn't really relevant one way or the other.

**Comment by johnhawkinson** [comment]
That seems wrong to me -- `youtube-dl` doesn't depend on the latest version of `rtmpdump`, it depends on some indetermine version of `rtmpdump` that's not "too old." But if I install `rtmpdump` last week and then the Homebrew recipe updates yesterday, I don't want Homebrew to insist that I reinstall `rtmpdump` for `youtube-dl`, if the one I have and installed last week will work just fine.

**Comment by ilovezfs** [comment]
While there are cases where an old version could successfully fulfill a dependency, that's not how Homebrew works.

**Comment by johnhawkinson** [comment]
Hrmm…seems a definite point of confusion. Is that documented somewhere, or where is the right place to improve the documentation of that?

**Comment by ilovezfs** [comment]
As far as I know it's only explicitly documented in the code:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula.rb#L479-L481
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula.rb#L534-L547

**Comment by MikeMcQuaid** [comment]
Although this isn't ideal I think it is something that we can't really fix for the above reasons without causing additional confusion, sorry.

**Comment by johnhawkinson** [comment]
Sorry, meant to come back to this sooner. If we can't fix the code, we should certainly improve the documentation. And maybe the actual messaging.

It still seems to me that **outdated** is a much better term to tell the user than **uninstalled**. 

@MikeMcQuaid were you saying there was a reason not to make that change? If so I missed it?

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid were you saying there was a reason not to make that change?

Because it's been this way for a long time and changing it for one person is not something that's sensible. If we see more confusion here: we'll consider changing it.

**Comment by johnhawkinson** [comment]
OK, so the decision is made not on the merits of the proposal, but rather on the noise people make?

I think the barrier to comment is pretty high: very few people will file Issues or even ask on http://discourse.brew.sh. And it's the people who do engage in those mechanisms who are least likely to look at something like this with fresh eyes and recognize how new homebrew users may feel or get confused. Once you know what it means, it doesn't confuse you anymore -- but that doesn't mean it shouldn't change.

Sorry to soapbox.

**Comment by MikeMcQuaid** [comment]
> OK, so the decision is made not on the merits of the proposal, but rather on the noise people make?

We don't change non-bugs based on the confusion of a single person. We're a project run by volunteers and have to prioritise our limited time. Given infinite time, this is something we'd address.
