### ISSUE TITLE
Incorrect use of `alias_method` for `Formula#plist`

### ISSUE THREAD

**Issue by 13k** [Homebrew/brew#228]
Methods that are expected to be overridden by child classes cannot be `alias_method`'ed.

From the [Ruby docs](http://www.rubydoc.info/stdlib/core/Module#alias_method-instance_method):

```
#alias_method(new_name, old_name) ⇒ self (private)

Makes new_name a new copy of the method old_name. This can be used to retain access to methods that are overridden.
```

In [Formula#plist](https://github.com/Homebrew/brew/blob/5a90e7190b0e06379ea2c94561e5914af9370f0b/Library/Homebrew/formula.rb#L728), we see that the default method (that returns `nil`) is being aliased as `:startup_plist`. This means `Formula#startup_plist` **will always execute the nil-returning plist method**, even when `#plist` is overridden by child classes.

Pure Ruby example:

```ruby
class C
  def f; 13; end
  alias_method :g, :f
end

class D < C
  def f; 31; end
end

# 2.3.0:3> c = C.new; [c.f, c.g]
# => [13, 13]
# 2.3.0:4> d = D.new; [d.f, d.g]
# => [31, 13]
```

_Intended result would be `d.g` to return `d.f == 31`_

This breaks formulae using inline plists (by defining the `#plist` method) and brew-services, which [will invoke `formula.startup_plist`](https://github.com/Homebrew/homebrew-services/blob/55156b7c260f9468f03d4ea8a4735bf3abed32b4/cmd/brew-services.rb#L447).

Formula example:

```
$ brew create "http://example.com/example_app-1.0.tar.gz" --no-fetch
# Add a `plist` method to the formula

$ brew cat example_app
# => https://gist.github.com/f764b0f5fd6d5a9447ac1dfaf44b1e04

$ brew irb
irb(main):001:0> f = Formulary.factory("example_app")
=> #<Formula example_app (stable) /usr/local/Library/Taps/homebrew/homebrew-core/Formula/example_app.rb>
irb(main):002:0> f.plist
=> "<!-- XML content -->\n"
irb(main):003:0> f.startup_plist
=> nil
```

_Here we expected `f.startup_list` to return the XML content in `f.plist`_

**Comment by mikemcquaid** [comment]
> Methods that are expected to be overridden by child classes cannot be alias_method'ed.

What would the correct solution here be, for our learning?

Unrelatedly, `f.startup_plist` is deprecated at this point anyway so should probably just be removed if it's been broken for this long.

**Comment by 13k** [comment]
Simply define `#startup_list` invoking `#plist`:

```ruby
class Formula
  def plist; nil; end
  def startup_plist; plist; end
end

class App < Formula
  def plist; "<!-- XML is like violence -->"; end
end

f = Formula.new; p [f.plist, f.startup_plist]
# => [nil, nil]
app = App.new; p [app.plist, app.startup_plist]
# => ["<!-- XML is like violence -->", "<!-- XML is like violence -->"]
```
