### ISSUE TITLE
`brew audit --strict` returns an error.

### ISSUE THREAD

**Issue by miguelarauj1o** [Homebrew/brew#2285]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

`brew audit --strict` returns:

``` bash
Error: A JSON text must at least contain two octets!
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:77:in `check_style_impl'
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:45:in `check_style_json'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:71:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

brew doctor and brew config follows here: [gist](https://gist.github.com/78ef03c87a0a5cbf361a7f0b81e14991.git).

**Comment by MikeMcQuaid** [comment]
Can you try to run `rubocop --format json` manually and try to figure out which file is causing this?

**Comment by miguelarauj1o** [comment]
Running `rubocop --format json` at Homebrew root folder, I get this: [gist](https://gist.github.com/miguelarauj1o/f47c5cade8d9907fa0e75e6e017670b8).

Output from this input is too long. 
I'll try to figure out a better way to find the file is causing this problem.

**Comment by MikeMcQuaid** [comment]
Have opened #2291 to try and improve the error messaging here.

**Comment by MikeMcQuaid** [comment]
@miguelarauj1o Can you run `brew update` and then try again and see what message you get?

**Comment by miguelarauj1o** [comment]
``` bash
Error: Error running `rubocop --format json --force-exclusion --config /usr/local/Homebrew/Library/.rubocop.yml  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science /usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions`
```

**Comment by miguelarauj1o** [comment]
For the record, `brew audit` works as expected.

**Comment by MikeMcQuaid** [comment]
Can you try to run that manually on each directory and see which one is causing the issues? Thanks!

**Comment by miguelarauj1o** [comment]
I'm getting this error PROBABLY because I made some changes in ruby version and rvm beyond what I should. I can't confirm. But, I did rollback in everything and `brew audit --strict` is working fine now. Strange.

So, I'm closing this issue. Feel free to reopen if you want.
