### ISSUE TITLE
brew can't find brew.sh

### ISSUE THREAD

**Issue by bweissjersey** [Homebrew/brew#2296]
### Bug reports:
Looking for help getting brew to work again. Any help appreciated.

Running MacOS 10.11.5.

Had originally installed brew as a non-root user. brew.sh is owned by root at present, the rest of brew is not. I can't remember if I did that myself at some point when attempting to install software.

I also recently un-installed python and installed it outside of brew. Perhaps that caused brew issues?

In the past brew has resumed working following brew doctor, brew update, etc. No longer.

brew.sh can't find the correct location of brew, see the output below.

$ which brew
/usr/local/bin/brew
$ ls -ltr `which brew`
-rwxr-xr-x  1 root  admin  1681 Mar  6 16:58 /usr/local/bin/brew
$ ls -ltr /usr/local/Homebrew/Library/Homebrew/brew.sh
-rw-r--r--  1 benweiss  wheel  10502 Mar  6 17:10 /usr/local/Homebrew/Library/Homebrew/brew.sh
$ brew update
/usr/local/bin/brew: line 59: /usr/local/Library/Homebrew/brew.sh: No such file or directory
$ sudo brew update
Password:
/usr/local/bin/brew: line 59: /usr/local/Library/Homebrew/brew.sh: No such file or directory

**Comment by MikeMcQuaid** [comment]
Try to `sudo chown -R $USER /usr/local` and then try again.

**Comment by bweissjersey** [comment]
Thanks for the reply Mike. Still no luck. Something about my deployment causes the logic in the script /usr/local/bin/brew to assemble a path that doesn't match mine.

/usr/local and all its sub-directories are now owned by "benweiss:admin".

Is it OK that my brew software is in /usr/local/Homebrew/Library/Homebrew and not /usr/local/Library/Homebrew?

**Comment by MikeMcQuaid** [comment]
Try `sudo chown -R $USER:admin /usr/local` again and then paste the new output and the output of `ls -lha` and `ls -lha $(which brew)`.

**Comment by MikeMcQuaid** [comment]
Closing due to no response.

**Comment by rv-kip** [comment]
I had the same error on line 73. I traced it to the bash-completion invocation in my `.bash_profile` 
I fixed it by removing that and then...
```
$ brew uninstall --force bash-completion
$ brew install bash-completion
```
And followed the instructions for re-adding the `.bash_profile` line.
