### ISSUE TITLE
fatal: repository 'https://github.com/Homebrew/homebrew-core/' not found

### ISSUE THREAD

**Issue by sebastientaggart** [Homebrew/brew#230]
(reposted/moved from [homebrew-core/1031](https://github.com/Homebrew/homebrew-core/issues/1031) by request)

- [x]  Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Gist with errors: https://gist.github.com/sebastientaggart/23db9f525b55faf4cf9870372a79abf7

TL;DR: ''brew doctor'' fails complaining about a repository not found, however the repository appears to be set correctly, and all other troubleshooting steps seem fine (see gist).

I've [looked](http://stackoverflow.com/questions/14113427/brew-update-failed?rq=1) [at](http://stackoverflow.com/questions/21267220/homebrew-cannot-update-and-i-cannot-add-a-git-repository) [a](https://github.com/Homebrew/legacy-homebrew/issues/5128) [few](https://github.com/neovim/neovim/issues/107) similar-looking problems, but none of the suggested steps did the trick (even reinstalling from scratch).

Weirdly, repository not found errors show up for lots of commands:
```
/usr/local (master)$ brew services
==> Tapping homebrew/services
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-services'...
fatal: repository 'https://github.com/Homebrew/homebrew-services/' not found
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-services /usr/local/Library/Taps/homebrew/homebrew-services --config core.autocrlf=false --depth=1
Error: Failure while executing: /usr/local/bin/brew tap homebrew/services
```

Even completely removing /usr/local, starting with fresh directory, and running the install script fails:
```
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown sebastien /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
fatal: repository 'https://github.com/Homebrew/brew/' not found
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1
```

**Comment by mikemcquaid** [comment]
What's the output of  `git clone https://github.com/Homebrew/brew`?

**Comment by mikemcquaid** [comment]
and `git clone https://github.com/Homebrew/homebrew-core /usr/local/Library/Taps/homebrew/homebrew-core --config core.autocrlf=false --depth=1`

**Comment by sebastientaggart** [comment]
```
/usr/local *$ git clone https://github.com/Homebrew/brew
Cloning into 'brew'...
fatal: repository 'https://github.com/Homebrew/brew/' not found
```

```
/usr/local *$ git clone https://github.com/Homebrew/homebrew-core /usr/local/Library/Taps/homebrew/homebrew-core --config core.autocrlf=false --depth=1
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
fatal: repository 'https://github.com/Homebrew/homebrew-core/' not found
```

However, ``git clone https://github.com/Homebrew/brew.git`` at least connects...
```
/usr/local *$ git clone https://github.com/Homebrew/brew.git
Cloning into 'brew'...
remote: Counting objects: 58211, done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 58211 (delta 47), reused 0 (delta 0), pack-reused 58123
Receiving objects: 100% (58211/58211), 11.39 MiB | 3.64 MiB/s, done.
Resolving deltas: 100% (40765/40765), done.
Checking connectivity... done.
```

**Comment by mikemcquaid** [comment]
@sebastientaggart It sounds like you may have some issues with your ISP and/or proxy.

**Comment by sebastientaggart** [comment]
In case anyone happens to run into something similar, @mikemcquaid you are correct, thank you.

I don't have anything messing with the connection locally that I know of, so to test the ISP I SSH tunneled into an offsite machine and ran ``git clone https://github.com/Homebrew/brew``, and voila, worked fine.  Now the install script works as expected, and I found out I've nuked the homebrew install chasing a red herring.  

Oh well, at least it's easy to install everything back.  Thanks very much for the support.

**Comment by ilovezfs** [comment]
@sebastientaggart next time use https://github.com/Homebrew/homebrew-bundle :)

**Comment by sebastientaggart** [comment]
@ilovezfs thanks for the suggestion, why would that have helped me in this situation?  I've never heard of homebrew-bundle

**Comment by ilovezfs** [comment]
It lets you create a template file of your existing install, including customized build options, taps, etc., so that reassembling an equivalent installation can later be triggered with a single command.
