### ISSUE TITLE
Add meta-formula support

### ISSUE THREAD

**Issue by MPLew-is** [Homebrew/brew#2300]
I'd like to request the addition of meta-formulae, i.e. formulae with no actual installed content, just `depends_on` and similar blocks, to allow the bulk installation of related formulae. I realize that this has been requested a few times, as in Homebrew/legacy-homebrew#28445, but I was encouraged on IRC to file an issue for this.

Since I came across that old issue (and one other that I can't seem to find now), and wanted the functionality, I went ahead and implemented an external command that accomplishes the same goal, at [MPLew-is/homebrew-blend](https://github.com/MPLew-is/homebrew-blend), so this is basically how I was thinking of having such functionality behave.

@MikeMcQuaid said (via @ilovezfs) on IRC:
> I think arguably we should do something in Homebrew core that allows installation of metaformulae like that  [6:16]   i.e. a formula with only `depends_on` and no `url` or `homepage` required

I wholeheartedly agree with this, as it would lead to the functionality being more widely available (and better supported as a part of the core), but I'm also concerned about the completeness of such a solution. There currently isn't a way to mix `casks` and `formula` as dependencies other than using something like `brew-bundle` (which is used in the internals of my `brew-blend`), and personally I think that's a key part of meta-formulae like this.

Anyways, please let me know what you think about this idea. I'd be more than happy to try making a pull request to implement something similar in the homebrew core, but my ruby skills are also practically nonexistent, so I might need some pointers on where to get started.

**Comment by MikeMcQuaid** [comment]
> There currently isn't a way to mix casks and formula as dependencies other than using something like brew-bundle (which is used in the internals of my brew-blend), and personally I think that's a key part of meta-formulae like this.

Note this is something we'd probably like to consider. Some `Requirements` have `cask` fields; it would be cool if Homebrew would auto-install the `cask`s when possible. After we have that you could use a Requirement to depend on a Cask indirectly.

> I'd like to request the addition of meta-formulae, i.e. formulae with no actual installed content, just depends_on and similar blocks, to allow the bulk installation of related formulae.

After you can `depends_on` Casks like above this seems like the best approach; just have formulae with a `desc`, `depends_on` and nothing else which pulls in multiple formulae or Casks.

**Comment by MPLew-is** [comment]
I've been poking around some of the core, trying to figure out a possible method of implementing this. I noticed that [requirements already detect casks and display an informative message if they need to be installed](https://github.com/Homebrew/brew/blob/b6d10769d3ac07e4b1322c9fd4781b500720f0fa/Library/Homebrew/requirement.rb#L34-L43); would the correct way of approaching this be to simply replace this with a call to the appropriate `cask` install command? At worst case, this could just be a system call to `brew cask install`, but I'm assuming there's a more elegant way to call the appropriate method via Ruby (even if I haven't done enough exploring to find it).

**Comment by MikeMcQuaid** [comment]
> would the correct way of approaching this be to simply replace this with a call to the appropriate cask install command?

Yes, I think so. Feel free to open a PR early; discussing code is easier than prose!

**Comment by MikeMcQuaid** [comment]
@MPLew-is any news here?

**Comment by MikeMcQuaid** [comment]
Passing on this.
