### ISSUE TITLE
allow formula aliases

### ISSUE THREAD

**Issue by kodabb** [Homebrew/brew#2301]
### Propose a feature

I would like that a package could advertise itself as a possible replacement for another package, and let users who prefer having a given package to keep it rather than being forced to use the one specified in the formula.

An actual example: I use mozjpeg as libjpeg provider, because it produces smaller files and and has better compression. One of its features is that it is completely API/ABI compatible with standard libjpeg.
However every time I upgrade my packages or install a new software depending on libjpeg, brew fails with

```
Error: You must `brew link jpeg` before jasper can be installed
```

Except I don't really need to do that, as mozjpeg can replace libjpeg for jasper transparently. There are a handful of packages that could benefit from this, so I hope you could support this feature one day.

**Comment by MikeMcQuaid** [comment]
Sorry, this isn't something we're going to be able to support because we only want to support one way of resolving dependencies at runtime. This could be accomplished in non-homebrew-core formulae with a `JpegRequirement` which could use either library today, though, but that'd have to live in a custom tap.

**Comment by kodabb** [comment]
> Sorry, this isn't something we're going to be able to support because we only want to support one way of resolving dependencies at runtime.

Can I ask the reasons behind this self-imposed requirement?

**Comment by MikeMcQuaid** [comment]
We don't have enough people to support it well.
