### ISSUE TITLE
Formula documentation is unclear on specifying dependencies

### ISSUE THREAD

**Issue by JoeNyland** [Homebrew/brew#2316]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

[This line](https://github.com/Homebrew/brew/blame/ca0071f/docs/Formula-Cookbook.md#L138) in the documentation suggests that I am able to depend on a system-wide installed package (or binary?) using the syntax `depends_on :foo` in a formula. At least that's the way I interpret the text:

> A Symbol (e.g. `:x11`) specifies a [`Requirement`](http://www.rubydoc.info/github/Homebrew/brew/master/Requirement) which can be fulfilled by one or more formulae, casks or other system-wide installed software (e.g. X11).

I'm trying to build formula that installs a executable that will not *run* without Docker installed. As Docker can be installed from a formula, cask or direct from the Docker website, I don't want to require users to install the Docker formula or cask when they install my formula. On the other hand I don't want users to install my formula and be unaware of it's hard runtime dependency on Docker.

So, I tried `depends_on :docker` in my formula, but when I run `brew info my-formula` I get the following:

```
Error: Unsupported special dependency :docker
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:137:in `parse_symbol_spec'
/usr/local/Homebrew/Library/Homebrew/compat/dependency_collector.rb:25:in `parse_symbol_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:85:in `parse_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:61:in `build'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:156:in `depends_on'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2255:in `block in depends_on'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2255:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2255:in `depends_on'
/usr/local/Homebrew/Library/Taps/joenyland/homebrew-docker/Formula/docker-remove-dangling-images.rb:6:in `<class:DockerRemoveDanglingImages>'
/usr/local/Homebrew/Library/Taps/joenyland/homebrew-docker/Formula/docker-remove-dangling-images.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:259:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:432:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:55:in `block in print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:49:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:49:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:49:in `print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:38:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

What am I doing wrong? Am I interpreting the documentation incorrectly? If so, what is the valid use case of the `depends_on :foo` syntax and how would I go about achieving what I'm trying to do above?

`brew config`:

```
HOMEBREW_VERSION: 1.1.11-32-g76db07e1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76db07e1b5ef096317701a95285b04aa7bf83187
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 66c2ce941ea33ac7817e28232be6d7e0adf20bd8
Core tap last commit: 76 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/joenyland/.rvm/rubies/ruby-2.3.3/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

`brew doctor`:

```
HOMEBREW_VERSION: 1.1.11-32-g76db07e1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76db07e1b5ef096317701a95285b04aa7bf83187
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 66c2ce941ea33ac7817e28232be6d7e0adf20bd8
Core tap last commit: 76 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/joenyland/.rvm/rubies/ruby-2.3.3/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

**Comment by reitermarkus** [comment]
From [`Requirement`](http://www.rubydoc.info/github/Homebrew/brew/master/Requirement): 

> A base class for non-formula requirements needed by formulae.

`docker` is a formula, not a requirement, i. e. this line: 
https://github.com/Homebrew/brew/blame/ca0071f/docs/Formula-Cookbook.md#L136.

**Comment by JoeNyland** [comment]
I'm sorry I don't understand. I'm aware that I can depend on a formula, but I don't want to do that.

I want to depend on docker regardless of whether it's installed via a formula, cask or dmg downloaded from the docker website, which the depends_on :symbol syntax documentation suggeests I can do.

**Comment by ilovezfs** [comment]
Someone would need to code a docker requirement. Here are examples: https://github.com/Homebrew/brew/tree/master/Library/Homebrew/requirements

**Comment by vitorgalvao** [comment]
@JoeNyland Detecting if a particular piece of software is installed can be incredibly hard, unless it was done with HB or HBC (since we control those records). As such, special symbols are made for incredibly common requirements (such as x11, Java, and the others in @ilovezfs).

You can’t say `:docker` and have it work, you need to tell HB how to interpret that requirement. The reason depending on a formula or cask “just works” is that (again) we control the whole stack, there.

**Comment by JoeNyland** [comment]
Ok, thanks @ilovezfs and @vitorgalvao for your explanation. I understand why this didn't work now. I'll take a look at creating a requirement for Docker.

**Comment by MikeMcQuaid** [comment]
Note this will not use an arbitrary Docker when installing from a binary package i.e. like most Homebrew installations.
