### ISSUE TITLE
No curl available

### ISSUE THREAD

**Issue by alator21** [Homebrew/brew#2317]
Cant install on my system(i dont have installed curl and im not admin/root). I modified some lines and replaced curl with wget but the original script itsself downloads prefixed another ones that use curl.any thoughts?

**Comment by ilovezfs** [comment]
I'm confused. Are you saying `/usr/bin/curl` doesn't exist?

**Comment by JCount** [comment]
If it does not, you might want to consider reinstalling macOS, because that means your system installation is corrupted. However if you are not an admin, you might not be in a position to do this.

**Comment by vitorgalvao** [comment]
From the issue template:

> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by alator21** [comment]
I tried to install in on debian..Forgot to mention that.an yes /use/bin/curl doesn't exist

**Comment by JCount** [comment]
You need to be looking at the installation instructions for Linuxbrew at http://linuxbrew.sh
