### ISSUE TITLE
easy documentation/ options of install variants

### ISSUE THREAD

**Issue by monouser7dig** [Homebrew/brew#2323]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Propose a feature:

first, thank you very much for all the work! much appreciated!

goal: make brew more accessible 
issue: want to install something into a different directory for easy removal 
example: brew install https://raw.githubusercontent.com/aleb/homebrew-gui/master/pitivi.rb --verbose
installs all kinds of things and when you want to uninstall it there should be an easy way to do so.

1. install the whole thing into a separate directory (can't find a way to do this easily .e.g by using a -parameter

2. brew xyz command which uninstalls all traces that were installed specifically for this sw

I think this is not a new issue and I already read about something like '2.' but I'm not yet experienced enough to proceed from here.
Thanks very much in advance!

**Comment by MikeMcQuaid** [comment]
We don't plan to support installing to custom directories, sorry.

**Comment by monouser7dig** [comment]
do you plan to offer the option to remove all dependencies of one sw that were specifically installed for that sw and not used by any other sw?

seems like a crucial feature of a package manager to me

thanks

**Comment by vitorgalvao** [comment]
> do you plan to offer the option to remove all dependencies of one sw that were specifically installed for that sw and not used by any other sw?

https://github.com/Homebrew/brew/pull/1881

**Comment by monouser7dig** [comment]
@vitorgalvao thank you, that was the thread I wanted to refer to in the beginning, really good to see this being worked on

nevertheless custom install directories seem like low hanging fruit to me so I actually wonder why this is not considered as it would allow for considerable "safer" install where experimental things could be installed without damaging others, alacrity being another such project in development that tends to flood ones Mac as is, thanks anyway, especially for finally tackling the upgrade procedure for casks!

**Comment by MikeMcQuaid** [comment]
> nevertheless custom install directories seem like low hanging fruit to me so I actually wonder why this is not considered as it would allow for considerable "safer" install where experimental things could be installed without damaging others, alacrity being another such project in development that tends to flood ones Mac as is, thanks anyway, especially for finally tackling the upgrade procedure for casks!

You can do this with multiple Homebrew installs instead. Whether it's low hanging fruit or not we'd need a lot more than just you to request this before adding it.

**Comment by monouser7dig** [comment]
@MikeMcQuaid ok sounds promising, is there a part of documentation that describes which parts of homebrew interact/ are needed and how one can realize a double install?

thanks a lot!

**Comment by MikeMcQuaid** [comment]
See "Alternative Installs" on http://docs.brew.sh/Installation.html
