### ISSUE TITLE
brew install `tap/formula` does not work at first attempt

### ISSUE THREAD

**Issue by Blaisorblade** [Homebrew/brew#234]
### Bug reports:

On OS X 10.10 (with brew b0d906f), `brew install neovim/neovim/neovim` seems to not manage to correctly tap and install neovim. It does the tapping and then things that neovim is installed? I then need `brew reinstall` to fix this.

Removing neovim and untapping, then repeating `brew install neovim/neovim/neovim`, leads to a successful installation, so I couldn't test if `brew update` fixes the problem. And after upgrading, `brew install neovim/neovim/neovim` also works.

```
$ brew info neovim/neovim/neovim
Error: No available formula with the name "neovim/neovim/neovim"
Please tap it and then try again: brew tap neovim/neovim
$ brew install neovim/neovim/neovim
==> Tapping neovim/neovim
Cloning into '/usr/local/Library/Taps/neovim/homebrew-neovim'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 7 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Checking connectivity... done.
Tapped 1 formula (32 files, 36.9K)
Warning: neovim/neovim/neovim-HEAD already installed
$ brew install neovim/neovim/neovim
Warning: neovim/neovim/neovim-HEAD already installed
$ brew upgrade neovim
Error: neovim/neovim/neovim HEAD already installed
$ ls /usr/local/Cellar/neovim/HEAD
INSTALL_RECEIPT.json  README.md
$ which nvim
$ $ cat /usr/local/Cellar/neovim/HEAD/INSTALL_RECEIPT.json; echo
{"stdlib":null,"used_options":[],"built_as_bottle":false,"compiler":"clang","time":1393448248,"poured_from_bottle":false,"tapped_from":"path or URL","HEAD":"dbea0f49bb5baab90e9db77e4da5eab15a1f1ff4","unused_options":[]}
$ brew reinstall neovim
[... finally starts installing neovim...] 
```

I guess that's a bug in Homebrew.
Also, `neovim/neovim/neovim` only works for install, not for `info`; that's minor, but still unfortunate. At least it does instruct me to `brew tap neovim/neovim`, but why can't `brew info neovim/neovim/neovim` do it by itself, since I explicitly specified a tap? The inconsistency seems annoying.

(On the neovim side, this relates to neovim/homebrew-neovim#150, neovim/homebrew-neovim#111).

## Output from brew doctor

`brew doctor` seems to say nothing noteworthy — I've had all these warnings since forever without actual problems. I'm including its output for completeness.

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: A .pydistutils.cfg file was found in $HOME, which may cause Python
builds to fail. See:
  https://bugs.python.org/issue6138
  https://bugs.python.org/issue4655

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libaspell.15.1.4.dylib
    /usr/local/lib/libpspell.15.1.4.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/ublio.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libaspell.la
    /usr/local/lib/libpspell.la

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install ocamlbuild

Run `brew missing` for more details.
```

**Comment by mikemcquaid** [comment]
> Warning: neovim/neovim/neovim-HEAD already installed

Neovim was already installed so it did not install it again.

**Comment by Blaisorblade** [comment]
> Warning: neovim/neovim/neovim-HEAD already installed
Neovim was already installed so it did not install it again.

Please reopen. Later messages show neovim was not installed, only `/usr/local/Cellar/neovim/HEAD` existed. All the data is in the transcript — my summary was probably insufficient.

My point was, that message is false. neovim was not installed, and this part of the transcript sounds evidence to me:
```
$ ls /usr/local/Cellar/neovim/HEAD
INSTALL_RECEIPT.json  README.md
$ which nvim
$
```
Note that `which nvim` gave no output, meaning it found no nvim. (The command name is correct, and `nvim` is found now).

The question is: was the borked `/usr/local/Cellar/neovim/HEAD` created during tapping (as I assumed) or was it there from before, even though `neovim/neovim` was not tapped?

**Comment by mikemcquaid** [comment]
> The question seems (to me): was the borked /usr/local/Cellar/neovim/HEAD created during tapping (as I assumed)

It was not.

> was it there from before, even though neovim/neovim was not tapped?

It was.

At some point you've installed a borked version of `neowin` so, when Homebrew tried to install the new version, it told you the existing version was installed.

**Comment by Blaisorblade** [comment]
Turns out you're probably right.
