### ISSUE TITLE
Migrating to a keg-only formula causes symlinks to be removed silently

### ISSUE THREAD

**Issue by FiloSottile** [Homebrew/brew#2340]
`gnupg21` was renamed to `gnupg@2.1`, causing an automatic migration.

```
==> Migrating gnupg21 to gnupg@2.1
==> Unlinking gnupg21
Moving to: /usr/local/Cellar/gnupg@2.1
==> Linking gnupg@2.1
```

However for some reason `gnupg@2.1` is marked keg-only (not the point of this issue):

```
This formula is keg-only, which means it was not symlinked into /usr/local.

This is an alternate version of another formula.
```

That means `brew link` refuses to create symlinks. However, the migration proceeded with no output or error, **breaking a working installation** on an automatic `brew update` (and causing a weird state where unlink causes "0 symlinks removed").

```
$ brew unlink gnupg@2.1
Unlinking /usr/local/Cellar/gnupg@2.1/2.1.16... 0 symlinks removed
$ brew link gnupg@2.1
Warning: gnupg@2.1 is keg-only and must be linked with --force
$ brew link --force gnupg@2.1
Linking /usr/local/Cellar/gnupg@2.1/2.1.16... 65 symlinks created
```

---

```
$ brew config
HOMEBREW_VERSION: 1.1.11-73-gb6d10769d3
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b6d10769d3ac07e4b1322c9fd4781b500720f0fa
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 182c67be1b25b29759edeb5a67edc3383e69cc7e
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.3/bin/ruby
Java: 1.8.0_66, 1.8.0_31
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  cloog018
  d-bus
  gcc
  libotr
  libsoup-with-gnome

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/git-annex-remote-googledrive
  /usr/local/bin/hashcat
  /usr/local/bin/packer
  /usr/local/bin/packer-builder-amazon-chroot
  /usr/local/bin/packer-builder-amazon-ebs
  /usr/local/bin/packer-builder-amazon-instance
  /usr/local/bin/packer-builder-digitalocean
  /usr/local/bin/packer-builder-docker
  /usr/local/bin/packer-builder-googlecompute
  /usr/local/bin/packer-builder-null
  /usr/local/bin/packer-builder-openstack
  /usr/local/bin/packer-builder-parallels-iso
  /usr/local/bin/packer-builder-parallels-pvm
  /usr/local/bin/packer-builder-qemu
  /usr/local/bin/packer-builder-virtualbox-iso
  /usr/local/bin/packer-builder-virtualbox-ovf
  /usr/local/bin/packer-builder-vmware-iso
  /usr/local/bin/packer-builder-vmware-vmx
  /usr/local/bin/packer-command-build
  /usr/local/bin/packer-command-fix
  /usr/local/bin/packer-command-inspect
  /usr/local/bin/packer-command-validate
  /usr/local/bin/packer-post-processor-compress
  /usr/local/bin/packer-post-processor-docker-import
  /usr/local/bin/packer-post-processor-docker-push
  /usr/local/bin/packer-post-processor-docker-save
  /usr/local/bin/packer-post-processor-docker-tag
  /usr/local/bin/packer-post-processor-vagrant
  /usr/local/bin/packer-post-processor-vagrant-cloud
  /usr/local/bin/packer-post-processor-vsphere
  /usr/local/bin/packer-provisioner-ansible-local
  /usr/local/bin/packer-provisioner-chef-client
  /usr/local/bin/packer-provisioner-chef-solo
  /usr/local/bin/packer-provisioner-file
  /usr/local/bin/packer-provisioner-puppet-masterless
  /usr/local/bin/packer-provisioner-puppet-server
  /usr/local/bin/packer-provisioner-salt-masterless
  /usr/local/bin/packer-provisioner-shell
  /usr/local/lib/libosxfuse.2.7.3.dylib
  /usr/local/lib/libosxfuse_i32.2.7.3.dylib
  /usr/local/lib/libosxfuse_i64.2.7.3.dylib

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install gmp@4 isl@0.14 libmpc@0.8 mpfr@2 qrencode

Run `brew missing` for more details.

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  gnupg@2.1
```

**Comment by ilovezfs** [comment]
This works as designed. If a non-keg-only formula is made keg-only, the symlinks are removed. The fact that migrations occur as part of `brew update` has been a subject of controvery in several other issues, but it's entirely intentional.

**Comment by FiloSottile** [comment]
Thanks for your reply. I honestly disagree that `brew install` could ever be allowed to remove an unrelated tool I rely on, but that is arguable.

I think however there is no case for not printing a big WARNING when a non-keg-only formula (or a forcefully linked formula?) is made keg-only, and symlinks removed. It even prints `==> Linking gnupg@2.1` which is completely misleading.

Anecdotally, this broke and confused at least two colleagues today.

**Comment by ilovezfs** [comment]
>there is no case

The case is: someone would need to open a PR for that.

**Comment by FiloSottile** [comment]
I unfortunately don't have the time or Ruby expertise myself. However, I'd argue the current behavior is nothing short of a bug, so an issue should stay open for someone to pick up and fix. But of course, not my project.

**Comment by MikeMcQuaid** [comment]
> This works as designed. If a non-keg-only formula is made keg-only, the symlinks are removed. The fact that migrations occur as part of brew update has been a subject of controvery in several other issues, but it's entirely intentional.

Agreed here.

> However, I'd argue the current behavior is nothing short of a bug, so an issue should stay open for someone to pick up and fix.

I don't agree it's a bug but the usability of this could be improved, I agree. How do you suggest we make it easier to add these things to people's PATHs and notify people they are keg only beyond what we already do?

**Comment by FiloSottile** [comment]
> How do you suggest we make it easier to add these things to people's PATHs and notify people they are keg only beyond what we already do?

I guess the options are:

1. print a warning message, explaining that symlinks are gone, why, and what command to run to get them back
2. refrain from running automatically migrations that would remove symlinks
3. force-link if there are no conflicts

Personally, I keep thinking that removing symlinks as part of an automated process is not an expected behavior, so my favorite is 3. But I think 1+2 would be good as well. 1 alone risks getting lost in the big output.

**Comment by ilovezfs** [comment]
FWIW, the good news here is that the homebrew/versions (actually all taps) engulfment by homebrew/core is almost finished, and in general non-keg_only -> keg_only migrations are pretty rare, so the bleeding will be stanched soon.
