### ISSUE TITLE
--build_bottle doesn't set -march=core2 for "Illegal Instruction 4" workaround

### ISSUE THREAD

**Issue by destijl** [Homebrew/brew#235]
I'm trying to build software for old macs on newer mac hardware, so I need to go for lowest common denominator to avoid "Illegal Instruction 4":
https://github.com/Homebrew/legacy-homebrew/issues/19567

The advice seems to be to use --build-bottle:
https://github.com/Homebrew/legacy-homebrew/issues/31483

but AFAICT this doesn't work, here's an example clang line from `brew install --build-bottle --verbose python`

```
clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/private/tmp/python-20160512-77389-z6rljc/Python-2.7.11/Mac/Include -I. -IInclude -I./Include -I/usr/local/include -I/private/tmp/python-20160512-77389-z6rljc/Python-2.7.11/Include -I/private/tmp/python-20160512-77389-z6rljc/Python-2.7.11 -c /private/tmp/python-20160512-77389-z6rljc/Python-2.7.11/Modules/operator.c -o build/temp.macosx-10.8-x86_64-2.7/private/tmp/python-20160512-77389-z6rljc/Python-2.7.11/Modules/operator.o
```
no `-march=core2` to be found. Adding print statements here:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/ENV/super.rb#L235

I verified that the return value of `determine_optflags` is `-march=core2` so perhaps it's getting overridden or ignored somewhere else?

If I edit the python formula to pass this explicitly:

```
diff --git a/Formula/python.rb b/Formula/python.rb
index ff95e89..a3dac0a 100644
--- a/Formula/python.rb
+++ b/Formula/python.rb
@@ -110,7 +110,7 @@ class Python < Formula
 
     args << "--without-gcc" if ENV.compiler == :clang
 
-    cflags   = []
+    cflags   = ["-march=core2"]
     ldflags  = []
     cppflags = []
```

I get the clang lines I expect:

```
clang -fno-strict-aliasing -fno-common -dynamic -march=core2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE  -c ./Modules/signalmodule.c -o Modules/signalmodule.o
```

so I think this is my workaround for now, although TBH I still have no idea if this is enough to make code built on this newer machine run on older mac hardware.

My config, running inside a vmware fusion VM:

```
$ sw_vers -productVersion
10.8.5
$ brew --config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2044294a865a85c4c3144a3000bd9a48427e12c6
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 444b3d26f3bcba0891c19e8f9ae66de7eb564964
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit ivybridge
Clang: 5.1 build 503
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: N/A
System Ruby: 1.8.7-p358
OS X: 10.8.5-x86_64
Xcode: 5.1 => /Library/Developer
CLT: 5.1.0.0.1.1396320587
X11: N/A
```

**Comment by ilovezfs** [comment]
The commands you see printed in verbose output are not the commands superenv executes; they're the incoming requests to superenv, which then decides what to actually execute. If you want to see what commands are actually being executed, you need to inspect the log file ~Library/Logs/Homebrew/python/03.make where you will see things like this:
```
clang called with: -g -O2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -o MyDocument.o -c ./MyDocument.m
superenv removed:  -g -O2 -g -O3 -Wall -Wstrict-prototypes
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/openssl/include
superenv executed: clang -pipe -w -Os -march=core2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -fwrapv -o MyDocument.o -c ./MyDocument.m -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/openssl/include
```

**Comment by mikemcquaid** [comment]
> I'm trying to build software for old macs on newer mac hardware, so I need to go for lowest common denominator to avoid "Illegal Instruction 4":
> Homebrew/legacy-homebrew#19567
> 
> The advice seems to be to use --build-bottle:
> Homebrew/legacy-homebrew#31483

We do not support using build bottle for this. If you need software to work on older Macs: you should build it yourself and not in Homebrew. We'll only accept issues that are reproducible building our bottles. Sorry!
