### ISSUE TITLE
Homebrew gets buggy in a non-existent directory

### ISSUE THREAD

**Issue by zg** [Homebrew/brew#2354]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

A lot of errors get printed before Homebrew is able to realize that the current working directory doesn't exist. See below steps to reproduce and subsequent output.

```
$ mkdir foo
$ cd foo
$ rm -r ../foo
$ brew update
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: The current working directory doesn't exist, cannot proceed.
```

**Comment by MikeMcQuaid** [comment]
This applies to a bunch of Unix tools so I don't consider it a bug. That said, if you wish to submit a PR to improve things we'll consider it if it doesn't add too much code complexity.
