### ISSUE TITLE
Broken vim after perl upgrade

### ISSUE THREAD

**Issue by koallen** [Homebrew/brew#2356]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug reports:

I pinned `vim` in homebrew. And recently I ran `brew upgrade` to upgrade to latest packages. After that, when I try to run `vim`, I get the following error:

```
dyld: Library not loaded: /usr/local/opt/perl/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /usr/local/bin/vim
  Reason: image not found
[1]    44267 abort      vim
```

I have to unpin `vim` and reinstall `vim` to open `vim` without this error. Shouldn't there be some mechanism that prevents `perl` from being updated when `vim` is pinned?

`brew config` output:

```
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 18dd3190df1943c1c133a9e8a47e3da1b4ed8e44
Core tap last commit: 37 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/koAllen/.rvm/rubies/ruby-2.3.0/bin/ruby
Java: 1.8.0_101
macOS: 10.12.2-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

`brew doctor` output:

```
Your system is ready to brew.
```

**Comment by MikeMcQuaid** [comment]
> Shouldn't there be some mechanism that prevents perl from being updated when vim is pinned?

No, sorry. This is a known issue with optional dependencies not being rebuilt.

**Comment by koallen** [comment]
So are there any plan to fix the issue? And how should I avoid these kind of issue?

**Comment by MikeMcQuaid** [comment]
> So is there any plan to fix the issue?

No one is currently working on it but we'd accept PRs.



> And how should I avoid these kind of issues?

Broadly: don't use options in formulae. That's not particularly helpful, I realise.

**Comment by koallen** [comment]
But I've only installed `vim` with `--with-lua --with-luajit` to support some vim plugins. I didn't use any options related to perl. Why would perl cause the problem in this case?

**Comment by ilovezfs** [comment]
There is a mechanism:
```
iMac-TMP:homebrew-core joe$ brew upgrade godep
==> Upgrading 1 outdated package, with result:
godep 79_1
Error: You must `brew unpin go` as installing godep requires the latest version of pinned dependencies
```

The mechanism just doesn't work at all for requirements (it's `depends_on :perl` not `depends_on "perl"`).

**Comment by ilovezfs** [comment]
This is basically a variant of https://github.com/Homebrew/brew/pull/2348 where the usual mechanisms (in that case `upgrade`, in this case `pin`) fail to work as expected with requirements even when they're satisfied by the default formula.

**Comment by ilovezfs** [comment]
Actually, I have that in reverse. The mechanism only works when it's the dependency that's pinned, not the dependent. Oh well.

**Comment by DomT4** [comment]
> But I've only installed vim with --with-lua --with-luajit to support some vim plugins.

Pretty sure this doesn't work FWIW. It links to either `lua` or `luajit`, not both.

**Comment by koallen** [comment]
> Pretty sure this doesn't "work" FWIW; It links to either lua or luajit, not both.

Actually, what I did was `brew reinstall vim --with-luajit`. But what `brew` did was `--with-lua --with-luajit`. I don't think this is related to the issue I mentioned though.

**Comment by ilovezfs** [comment]
Reinstall preserves your old options. So if you want the correct command in that case, `brew uninstall vim; brew install --with-luajit vim` rather than `reinstall`

**Comment by liuliangsir** [comment]
I met this issue just now
Because i run `brew upgrade perl`

**Comment by remones** [comment]
I met this issue too when I had ran `brew upgrade`，so I tryed to:
- brew uninstall --ignore-dependencies perl
- brew uninstall vim
- brew install vim

Event though I have to update my VIM version, but it works for me...

**Comment by DomT4** [comment]
Every time `perl`, `python` or `ruby` are upgraded or revision bumped, `vim` needs to be `brew reinstall`'d. It's a known issue. This would be a known issue even against the system Perl if Apple ever gets round to implementing another major Perl update.

**Comment by 7Moses** [comment]
I was getting this error during a build in VSCode:

dyld: Library not loaded: @@HOMEBREW_CELLAR@@/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /usr/local/bin/perl
  Reason: image not found

Followed @remones guidance. Thanks!
