### ISSUE TITLE
All CI failing with FATAL: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#236]
Archiving artifacts
FATAL: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken

**Comment by ilovezfs** [comment]
@apjanke not sure what to do about this one but seems to be failing all builds at the moment.

**Comment by DomT4** [comment]
This one wasn't Andrew's issue. It appears the Jenkins security update applied today causes authentication exclusively on the archiving stage to fail, intermittently. It started earlier, then went away for a while, and now seems to be back.

Doesn't seem to have a direct impact on the builds themselves, both upstream and downstream builds pass okay, just the archiving stage falls on its face. Still looking into the root cause.

**Comment by ilovezfs** [comment]
@DomT4 I know, I just figured Andrew would be awake ;)

**Comment by DomT4** [comment]
You'd be right, by the looks of it 😉. I'm going to try a couple of things but there's not a lot we can do if they don't work; the alternative is downgrading onto a release with 7 known vulnerabilities. One day we can kill off Jenkins and life will be a happy happy place.

**Comment by DomT4** [comment]
Apparently temporarily fixed by just restarting the darn thing `¯\_(ツ)_/¯`.

**Comment by ilovezfs** [comment]
Nice. Who says UNIX cannot be more like Windows?

**Comment by DomT4** [comment]
😆 I laughed far too much at that. I'm hoping that if it can be consistently resolved by effectively restarting it every time it's a Jenkins bug and not some configuration nightmare.

**Comment by ilovezfs** [comment]
Looks like it's back http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1799/version=el_capitan/console

**Comment by mikemcquaid** [comment]
Maybe worth filing an issue upstream about this?

**Comment by DomT4** [comment]
Someone [already did](https://issues.jenkins-ci.org/browse/JENKINS-34775).

**Comment by ilovezfs** [comment]
Looks like a downgrade is in order.

**Comment by ilovezfs** [comment]
Looks like there's a preliminary fix for this: https://github.com/jenkinsci/ghprb-plugin/pull/336

So perhaps we should try that patch even though it's not in a final form.

**Comment by ilovezfs** [comment]
Apparently this may be a workaround:

>Christopher Orr added a comment - 18 minutes ago

>This is related to the fix for SECURITY-243 mentioned here:
https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2016-05-11

>Enabling the system property mentioned in that part of the security advisory should temporarily work around this problem.

**Comment by DomT4** [comment]
We'd already enabled that to resolve other plugin issues but this one proved sticky.

**Comment by ilovezfs** [comment]
Did whitelist all parameters listed?
```
 If using the standard ${sha1} branch spec, builds will fail with "Couldn't find any revision to build".
Pull requests remain in the "pending" state as the plugin fails to update the PR with the build outcome
OpenParameter names used
ghprbActualCommit,ghprbActualCommitAuthor,ghprbActualCommitAuthorEmail,ghprbAuthorRepoGitUrl,
ghprbCommentBody,ghprbCredentialsId,ghprbGhRepository,ghprbPullAuthorEmail,ghprbPullAuthorLogin,
ghprbPullAuthorLoginMention,ghprbPullDescription,ghprbPullId,ghprbPullLink,
ghprbPullLongDescription,ghprbPullTitle,ghprbSourceBranch,ghprbTargetBranch,ghprbTriggerAuthor,
ghprbTriggerAuthorEmail,ghprbTriggerAuthorLogin,ghprbTriggerAuthorLoginMention,GIT_BRANCH,sha1



```

**Comment by DomT4** [comment]
We whitelisted literally everything 😄.

**Comment by ilovezfs** [comment]
Then it sounds like it's time for a downgrade or the experimental PR https://github.com/jenkinsci/ghprb-plugin/pull/336

**Comment by DomT4** [comment]
Check the team chat.
