### ISSUE TITLE
Unable to install `llvm --with-ocaml`— “cannot create directory”, “cannot copy file” errors

### ISSUE THREAD

**Issue by capnslipp** [Homebrew/brew#2360]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [?] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

I'm trying to install LLVM with ocaml support using `brew install llvm --with-lldb --with-ocaml --with-python --with-toolchain` _(note: I know really nothing about OCaml; I'm just trying to `make` a tool written in OCaml & C++)_.

Partway through the first install, it aborted with this error message:

~~~
CMake Error at bindings/ocaml/llvm/cmake_install.cmake:39 (file):
  file cannot create directory: /usr/local/lib/ocaml/llvm.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  bindings/ocaml/cmake_install.cmake:32 (include)
  cmake_install.cmake:56 (include)
~~~

_“So fine”_ I said and I did a `mkdir /usr/local/lib/ocaml/llvm` and tried to install again.  This time I got this error message:

~~~
CMake Error at bindings/ocaml/llvm/cmake_install.cmake:39 (file):
  file INSTALL cannot copy file
  "/tmp/llvm-20170317-32737-soia7o/bindings/ocaml/llvm/llvm.mli" to
  "/usr/local/lib/ocaml/llvm/llvm.mli".
Call Stack (most recent call first):
  bindings/ocaml/cmake_install.cmake:32 (include)
  cmake_install.cmake:56 (include)
~~~

_“So it's having trouble copying things into Homebrew's dir.  I know how to fix that.”_ I thought and proceeded to run `sudo chown -R capnslipp:admin /usr/local; sudo chmod -R g+w /usr/local`.  I also checked that there wasn't anything serious or `llvm`/`ocaml`-related reported by `brew doctor`and `brew uninstall`ed a few things just for the sake of cleanliness.

Running the install takes about an hour on my machine (LLVM is kind of a big deal), so I wanted to avoid any further issue so I ran `chmod 777 /usr/local/lib/ocaml/llvm` before trying the install again: 

~~~
CMake Error at bindings/ocaml/llvm/cmake_install.cmake:39 (file):
  file cannot create directory: /usr/local/lib/ocaml/llvm.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  bindings/ocaml/cmake_install.cmake:32 (include)
  cmake_install.cmake:56 (include)
~~~

_“Wait, what?  It deleted the dir and then complains that it can't recreate it? WTF?”_

Frustrated at this point, I decided that the simplest solution was to just run the install as root (naughty, I know) and then `chmod`/`chown` everything back to `capnslipp:admin` afterwards.  So I `chmod`ed `brew to be owned by root:

~~~
$ which brew
/usr/local/bin/brew
$ chown root:admin /usr/local/bin/brew
$ chown -h root:admin /usr/local/bin/brew
$ ls -l /usr/local/bin/brew
lrwxr-xr-x  1 root  admin  20 Sep 24 12:44 /usr/local/bin/brew -> ../Homebrew/bin/brew
 ls -l /usr/local/Homebrew/bin/brew
-rwxr-xr-x  1 root  admin  1681 Mar  7 17:23 /usr/local/Homebrew/bin/brew
~~~

and then tried the install again as root:

~~~
$ sudo -u root -H bash
$ brew install llvm --with-lldb --with-ocaml --with-toolchain
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
~~~

_“Wait, really?  Well WTF do I do now?”_

At this point I'm completely stuck.  I've just spent the better part of a day trying to build & run some polygon-tri optimization tool I found on GitHub (and am thus still unsure whether it'll fit my needs yet, much less integrated with our build system) and am stuck on either of two issues:

1. `llvm`'s `ocaml` stuff must do some weird *ish with what user it decides to run under.
2. Homebrew apparently doesn't let the user (me) retain control over my computer— it seems to simply refuse to run as root even though I _fully understand and accept all consequences this may entail, and release Homebrew and associated parties of any damages or ill effects, including but not limited to injury or death, from any responsibility._ 

**Halp?**  This level of frustration to a skilled and seasoned dev shouldn't be happening.  I'm on the verge of downloading `llvm` & and doing all the other stuff that `brew` would do by hand as root, just to get it to f-ing work.  I might even reboot into single user mode for good measure.  Please help before I regret everything I may end up doing in the next 24 hours— critical deadlines are justification for just about anything, you know.

**Comment by ilovezfs** [comment]
Thanks for reporting this. Yes, I can reproduce this issue with 4.0.0. I did previously have `--with-opam` working with 3.9, so I'm checking now whether 3.9 is still OK or if it has come down with the same flu.

**Comment by ilovezfs** [comment]
It works fine with 3.9, and this is llvm 4 specific. @JCount has a fix for you.

**Comment by JCount** [comment]
This should fix it:
```
diff --git a/Formula/llvm.rb b/Formula/llvm.rb
index f627060c37..7fcd7e08e7 100644
--- a/Formula/llvm.rb
+++ b/Formula/llvm.rb
@@ -242,6 +242,7 @@ class Llvm < Formula
 
     mktemp do
       if build.with? "ocaml"
+        args << "-DLLVM_OCAML_INSTALL_PATH=#{lib}/ocaml"
         ENV["OPAMYES"] = "1"
         ENV["OPAMROOT"] = Pathname.pwd/"opamroot"
         (Pathname.pwd/"opamroot").mkpath
```

**Comment by JCount** [comment]
Ok, I just merged the fix, so you should be able to do `brew update; brew install llvm --with-lldb --with-ocaml --with-python --with-toolchain`.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/11223.

**Comment by capnslipp** [comment]
Alright, thank you for the help.  However, now I'm getting a different error (I'm not sure if it's related to the original issue or not).

My build now fails on `==> opam install ocamlfind ctypes`

The relevant erroring & env section in the log file listed (`~/Library/Logs/Homebrew/llvm/03.opam`) are:

~~~
…
[ocamlfind: ./configure] Command started
[ERROR] The compilation of ocamlfind failed at "./configure -bindir
        /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/bin
        -sitelib
        /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/lib
        -mandir
        /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/man
        -config
        /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/lib/findlib.conf
        -no-custom -no-topfind".
[ocamlfind: ocamlfind remove] Command started
[ocamlfind: ./configure] Command started
[ocamlfind: make uninstall] Command started
[ocamlfind: rm] Command started

#=== ERROR while installing ocamlfind.1.7.1 ===================================#
# opam-version         1.2.2
# os                   darwin
# command              ./configure -bindir /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/bin -sitelib /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/lib -mandir /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/man -config /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/lib/findlib.conf -no-custom -no-topfind
# path                 /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/build/ocamlfind.1.7.1
# compiler             system (4.04.0)
# exit-code            1
# env-file             /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/build/ocamlfind.1.7.1/ocamlfind-8351-6cc03f.env
# stdout-file          /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/build/ocamlfind.1.7.1/ocamlfind-8351-6cc03f.out
# stderr-file          /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/build/ocamlfind.1.7.1/ocamlfind-8351-6cc03f.err
### stdout ###
…
~~~

Also of note (and what I believe to be the core problem here is what's in `~/Library/Logs/Homebrew/llvm/build.sandbox.log`:

~~~
Mar 18 16:48:37 sandboxd[5560]: ruby(7748) deny forbidden-exec-sugid
Mar 18 16:49:41 sandboxd[5560]: sh(8458) deny forbidden-exec-sugid
Mar 18 16:49:41 sandboxd[5560]: sh(8532) deny forbidden-exec-sugid
Mar 18 16:49:41 sandboxd[5560]: opam(8533) deny forbidden-exec-sugid
Mar 18 16:49:42 sandboxd[5560]: ruby(8536) deny forbidden-exec-sugid
Mar 18 16:49:50 sandboxd[5560]: sh(8551) deny forbidden-exec-sugid

We use time to filter sandbox log. Therefore, unrelated logs may be recorded.
~~~

I suspect sandbox is the culprit because I additionally tried:

1. stopping brew just before `==> opam install ocamlfind ctypes`
2. went to https://opam.ocaml.org/packages/ocamlfind/ocamlfind.1.7.1/ and downloaded the `tar.gz` of `ocamlfind.1.7.1`
3. unzipped and placed it at `/private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/build/ocamlfind.1.7.1/`
4. `cd`ed to `/private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/build/ocamlfind.1.7.1/`
5. and ran `./configure -bindir /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/bin -sitelib /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/lib -mandir /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/man -config /private/tmp/homebrew/llvm-20170318-7747-1iwkfz4/opamroot/system/lib/findlib.conf -no-custom -no-topfind`

And that run without any errors, as did running `make all` afterwards.  Continuing the `brew` process, of course, tried the `./configure …` again, failed, and aborted.

**Comment by capnslipp** [comment]
After discovering and adding the `--no-sandbox` to my invocation (making it `brew install llvm --with-lldb --with-ocaml --with-toolchain --no-sandbox`), `llvm` built & installed as expected.  Thanks!
