### ISSUE TITLE
Homebrew installation error on mcaOS Sierra version10.12.3

### ISSUE THREAD

**Issue by mazano579** [Homebrew/brew#2361]
I failed to install Homebrew by running as suggested on brew website the following command.

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

I get the following error:

==> Downloading and installing Homebrew...
error: Failed to connect to 8.20.189.133: Can't assign requested address while accessing https://github.com/Homebrew/brew/info/refs?service=git-upload-pack
fatal: HTTP request failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force --depth=1

Please help.

**Comment by ilovezfs** [comment]
Are you behind a firewall, proxy, etc.?

**Comment by mazano579** [comment]
It's my personal home computer so I don't think so.

**Comment by ilovezfs** [comment]
Is it repeatable?

**Comment by mazano579** [comment]
yes it is.
everytime i run the command i get the same error.

**Comment by MikeMcQuaid** [comment]
Can continue debugging but closing as this is user specific.
