### ISSUE TITLE
brew tap morse-simulation/morse not brewing, wrong repository name

### ISSUE THREAD

**Issue by giodegas** [Homebrew/brew#2364]
brewing the [morse robotics simulator](http://www.openrobots.org/morse/doc/stable/morse.html) does not work:

    brew tap morse-simulation/morse

it replies:

    ==> Tapping morse-simulation/morse
    Cloning into '/usr/local/Homebrew/Library/Taps/morse-simulation/homebrew-morse'...
    Username for 'https://github.com': giodegas
    Password for 'https://giodegas@github.com':
    remote: Repository not found.
    fatal: repository 'https://github.com/morse-simulation/homebrew-morse/' not found

Well, the actual repository name is:

    https://github.com/morse-simulator/homebrew-morse

how to fix it?

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by MikeMcQuaid** [comment]
`brew tap morse-simulator/morse`
