### ISSUE TITLE
Error pouring Bottle from Tap (is not a directory)

### ISSUE THREAD

**Issue by ryanhomer** [Homebrew/brew#2373]
I am trying to create my own Tap to make it easy to use an older version of flow since the brew versions tend to get updated faster than React Native updates can keep up with and the version mismatch tends to lead to extraneous flow errors.

My tap is located here: https://github.com/ryanhomer/homebrew-flow

When I try to `brew install flow@0.38.0`, this is what happens:
```
==> Installing flow@0.38.0 from ryanhomer/flow
==> Downloading https://raw.githubusercontent.com/ryanhomer/homebrew-flow/master/bottles/flow@0.38.0-0.38.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring flow@0.38.0-0.38.0.sierra.bottle.tar.gz
Error: /usr/local/Cellar/flow@0.38.0/0.38.0 is not a directory
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/facebook/flow/archive/v0.38.0.tar.gz
```

The installation then continues by building from source and succeeds. If I create the missing directories and re-run, I get this:
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing flow@0.38.0 from ryanhomer/flow
==> Downloading https://raw.githubusercontent.com/ryanhomer/homebrew-flow/master/bottles/flow@0.38.0-0.38.0.sierra.bottle.tar.gz
Already downloaded: /Users/ryan/Library/Caches/Homebrew/flow@0.38.0-0.38.0.sierra.bottle.tar.gz
==> Pouring flow@0.38.0-0.38.0.sierra.bottle.tar.gz
Error: undefined method `exist?' for nil:NilClass
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/facebook/flow/archive/v0.38.0.tar.gz
Already downloaded: /Users/ryan/Library/Caches/Homebrew/flow@0.38.0-0.38.0.tar.gz
==> make
```

What do I need to do to be able to successfully use the bottles?

Thanks in advance.

```
$ brew config
HOMEBREW_VERSION: 1.1.11-111-g00af5250f0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 00af5250f0a7988178ed8d26520bf1a98a8dea9a
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 88a629d5d499b649440e979dc8148cda9490b86b
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/ryan/.rvm/rubies/ruby-2.3.0/bin/ruby
Java: 1.8.0_92, 1.8.0_65, 1.6.0_65-b14-468
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
How did you create the bottle, with `brew bottle`? I recommend using `brew test-bot` to build your bottles as it'll run various `audit` and `style` checks for you, too. Happy to help here but closing as this isn't a issue for anyone except you.

**Comment by ryanhomer** [comment]
Thanks @MikeMcQuaid. I managed to figure it out. For posterity... the bottles that I were using were being extracted to the original `flow` folder under `Cellar`, so in my case `.../Cellar/flow/0.38.0` but since I've changed the name of the formula to `flow@0.38.0` I had to repackage the bottles with the "base" folder renamed to `flow@0.38.0` and update the formula with the new SHA values.
