### ISSUE TITLE
brew tap-new creates a broken Travis config

### ISSUE THREAD

**Issue by killerswan** [Homebrew/brew#2378]
When a user (like me) runs `brew tap-new`, a YAML file is created which will cause failures to build with an error like so:
```
$ ln -s "$PWD" "$HOMEBREW_TAP_DIR"
ln: /usr/local/Homebrew/Library/Taps/killerswan/homebrew-sample: No such file or directory

The command "ln -s "$PWD" "$HOMEBREW_TAP_DIR"" failed and exited with 1 during .
```

I believe the code which creates the `.travis.yml` file is [here in tap-new.rb](https://github.com/Homebrew/brew/blob/17cc40f112cbb7e5da5ef6d8eb3e3d5afbbd43e5/Library/Homebrew/dev-cmd/tap-new.rb#L46).

In that script:
* `$TRAVIS_REPO_SLUG` is a path like `killerswan/homebrew-sample`, and
* `$HOMEBREW_TAP_DIR` is a path like `/usr/local/Homebrew/Library/Taps/killerswan/homebrew-sample`.

If `/usr/local/Homebrew/Library/Taps/killerswan` doesn't already exist, that call to `ln -s` is trying to create a link at `killerswan/homebrew-sample` but cannot find `killerswan`, so it fails.

One workaround is to insert some `$(dirname ...)` calls.

**Comment by JCount** [comment]
What directory are you in, as in what is the value of "$PWD"?
