### ISSUE TITLE
Mention DYLD_LIBRARY_PATH in Caveats

### ISSUE THREAD

**Issue by mkdong** [Homebrew/brew#2379]
I recently tried to install Gollum V3 via `gem install gollum`. Everything was fine until I ran `gollum` in my terminal. I got the following errors:

> /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes/charlock_holmes.bundle, 9): Library not loaded: ../lib/libicudata.58.2.dylib (LoadError)
  Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes/charlock_holmes.bundle
  Reason: no suitable image found.  Did find:
        ../lib/libicudata.58.2.dylib: file too short - /usr/local/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes/charlock_holmes.bundle
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes.rb:1:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gitlab-grit-2.8.1/lib/grit.rb:79:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter/git_layer_grit.rb:3:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter.rb:1:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gollum-lib-4.2.2/lib/gollum-lib.rb:13:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gollum-4.1.0/lib/gollum/app.rb:4:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gollum-4.1.0/bin/gollum:242:in `<top (required)>'
        from /usr/local/bin/gollum:22:in `load'
        from /usr/local/bin/gollum:22:in `\<main\>'

It seems that `charlock_holmes` cannot find the dynamic library provided by `icu4c`.

I then reviewed the caveats via `brew info icu4c` and got only the following:

> ==> Caveats
> This formula is keg-only, which means it was not symlinked into /usr/local.  
> 
> macOS provides libicucore.dylib (but nothing else).  
> 
> If you need to have this software first in your PATH run:
>  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.zshrc
>  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.zshrc  
> 
>For compilers to find this software you may need to set:
>    LDFLAGS:  -L/usr/local/opt/icu4c/lib
>    CPPFLAGS: -I/usr/local/opt/icu4c/include  
> 
>For pkg-config to find this software you may need to set:
>    PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig

After days of work, I finally solved the problem by setting DYLD_LIBRARY_PATH to the icu4c path. `echo 'export DYLD_LIBRARY_PATH="/usr/local/opt/icu4c/lib:$DYLD_LIBRARY_PATH"' >> ~/.zshrc`.

Since `icu4c` provides dynamic libraries, I think it's necessary to add DYLD_LIBRARY_PATH stuffs to the caveats to at least remind people who need it.

Thanks :)

**Comment by MikeMcQuaid** [comment]
This is an issue that can (and should) be fixed in `charlock_holmes` instead.
