### ISSUE TITLE
Update to the docs.brew.sh list with a link to basic commands as the first item

### ISSUE THREAD

**Issue by benjaminapetersen** [Homebrew/brew#2380]
On `http://docs.brew.sh/`, the first list is:

Users
- Troubleshooting
- Installation
- Frequently Asked Questions
- Common Issues

It would be great for onboarding if the very first item was `Commands` that would like to a page that summarized each brew command, somewhat of a "cheat sheet" style.  The current list implies initial familiarity, w/o clear "getting started" direction.  

Thx for considering!

**Comment by monouser7dig** [comment]
yes I second that, I now got used to brew, mostly, not an expert but it took more than a month

something like a proper command summary would be good because there are also some less documented commands available that are helpful nevertheless like the usage of leaves.
or the confusion about brew cask upgrade prior to it's proper implementation

for day to day use something like a best-practice would be ideal as well
**more info/ a nice article** about the whole idea of symlinking vs keg only, **about the structure** of the cellar and just an overview about how homebrew operates, I miss(ed) that.

This would go along nicely with the release of brew cask upgrade as this will make the whole system much more user-friendly 🙉 

I'd happily participate in reading through this and at least I can tell if this is something a "normal" user might be able ti understand 😆 

overall this is an amazing tool that I think not only developers should use

**Comment by bfontaine** [comment]
Please make a pull-request.

**Comment by vitorgalvao** [comment]
What’s wrong with `man brew`? If you already have a working installation of Homebrew (which that other list does not assume you do), a `Commands` section will only repeat the manual, basically making extra overhead and more places to forget to update.

**Comment by monouser7dig** [comment]
don't want to hijack @benjaminapetersen topic but my first/ biggest issue was that one does not one how homebrew operates
> more info/ a nice article about the whole idea of symlinking vs keg only, about the structure of the cellar and just an overview about how homebrew operates, I miss(ed) that.

IMO one does not only need to know what the outcome of a command is, but also understand how the commands modify data/folders/programms especially in a program like homebrew which offers more options than a simple/ encapsulated MacAppStore

**Comment by benjaminapetersen** [comment]
@vitorgalvao user experience, onboarding, etc.  Easier to maintain w/o nice docs I won't debate, but def great for community, new users, etc. to keep a nice set of online docs as friendly as possible.

**Comment by vitorgalvao** [comment]
@benjaminapetersen In that case, a link to the [markdown manual page](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/manpages/brew-cask.1.md) should suffice (or parsing that automatically to make the webpage you mention).

**Comment by vitorgalvao** [comment]
@benjaminapetersen Parsing [the manual page](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/manpages/brew.1.md.erb) automatically into said webpage might be the best solution.

**Comment by MikeMcQuaid** [comment]
> Parsing the manual page automatically into said webpage might be the best solution.

This was done and is live on http://docs.brew.sh.

**Comment by benjaminapetersen** [comment]
Great start!  This is def a move in the right direction.  I think there might be a couple bugs & small tweaks that could improve the page.  

- I noticed some leaked `<var>formula</var>` tags in the markup, i think parsing the man page didn't quite process everything:
![screen shot 2017-03-23 at 9 43 59 am](https://cloud.githubusercontent.com/assets/280512/24250431/415ccd76-0fad-11e7-960b-79a75e550446.png) 
vs 
![screen shot 2017-03-23 at 9 44 21 am](https://cloud.githubusercontent.com/assets/280512/24250439/4e58db14-0fad-11e7-9631-f20e431c4c69.png)
- The style sheet might need some tweaks, or adjust the generated markup slightly.  For example, the explanation text is larger than the command itself:
![screen shot 2017-03-23 at 9 46 22 am](https://cloud.githubusercontent.com/assets/280512/24250537/984eae88-0fad-11e7-8297-8a348aecd284.png)
That is difficult to parse, but even just tweaking the font-sizes could be clearer (big difference scrolling a long page of this pattern):
![screen shot 2017-03-23 at 9 49 05 am](https://cloud.githubusercontent.com/assets/280512/24250661/0f7648d6-0fae-11e7-9146-cedcca796910.png)
- Even matching the same indentation hierarchy as the `man brew` output could improve the readability/usability:
![screen shot 2017-03-23 at 9 51 37 am](https://cloud.githubusercontent.com/assets/280512/24250785/6e78d92a-0fae-11e7-9d7c-31d79f6f5f55.png)
![screen shot 2017-03-23 at 9 51 42 am](https://cloud.githubusercontent.com/assets/280512/24250784/6e7445c2-0fae-11e7-8839-ab0a924ccb97.png)
The words `Print`, `Pass` and `See` line up vertically on the command line, giving hierarchy that is a bit broken on the web page.

Is it preferred to open this as a follow-on?
Thanks again.

**Comment by MikeMcQuaid** [comment]
@benjaminapetersen We'll accept pull requests to improve the formatting. I don't plan to work on it myself.

**Comment by benjaminapetersen** [comment]
Awesome, I'm happy to help.  Let me see what I can do.

**Comment by benjaminapetersen** [comment]
If there is anything important to running/building the docs, let me know, otherwise I'll checkout the contributing section in the README.md & see if I can get it running. thx

**Comment by benjaminapetersen** [comment]
Is not 100% clear how to build & run the docs locally.  Any chance to get an extra stanza in the CONTRIBUTING doc?  Seems to be Jekyll.  Got a bit into it before pausing to check if anyone has some info handy.

**Comment by MikeMcQuaid** [comment]
@benjaminapetersen cd `docs` and then it's a typical pages site (`bundle install && jekyll serve`)

**Comment by benjaminapetersen** [comment]
Great, thanks!
