### ISSUE TITLE
The depends_on "cython" => [:python, :build] construct does not work

### ISSUE THREAD

**Issue by iMichka** [Homebrew/brew#2381]
While debugging https://github.com/Homebrew/homebrew-science/pull/5280, I realised the `depends_on "cython" => [:python, :build]` syntax in formulae does not work, and I think it is a bug in brew.

The error is the following:
> nest: Unsatisfied dependency: cython
Homebrew does not provide special Python dependencies; install with:
  `pip install cython`
Error: An unsatisfied requirement failed this build.

Removing the `:build` from `depends_on "cython" => [:python, :build]` fixes it. That's probably fair enough, and we could make python a full requirement, but the error message is still surprising, as cython was installed using pip and was in the path.

Playing around, I found out that these lines may look suspicious:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/requirements/language_module_requirement.rb#L6-L9
When it is initialised, `module_name` == `build`, and `import_name` == `cython`
This makes the to check be: `/usr/bin/env python -c import build`, which fails.

Either `LanguageModuleRequirement` needs to get more logic for that case, or better,  this line needs to be changed: https://github.com/Homebrew/brew/blob/0b762dc3f16dbd5e7d07b5e2273638c28e86c337/Library/Homebrew/dependency_collector.rb#L101

I would propose to change the `tags[1]` argument to something like: `tags[1].is_a?(String) ? tags[1] : nil`. But I am not really sure why `tags[1]` is passed as argument here, so I didn't open a pull request, because my fix is probably quite naive (but the test suite passes).

If the proposed fix seems OK I can open a pull request but I think it's better a core maintainer has a look at this first and maybe can propose a (better) different fix.

**Comment by MikeMcQuaid** [comment]
> If the proposed fix seems OK I can open a pull request but I think it's better a core maintainer has a look at this first and maybe can propose a (better) different fix.

Honestly I think this is a WONTFIX on our end. Language modules should be deprecated (and will be when I get around to it) because they provide a kinda crappy user experience compared to vendoring e.g. check out `ansible`.

**Comment by iMichka** [comment]
Ok so the right way to fix this is to vendor cython, which was the patch that was proposed by the contributor :)

And if the buggy code path is due for removal anyway, that's a good thing.
