### ISSUE TITLE
Percona 5.6 configure error causes configure of DBD-mysql-4.402 to fail

### ISSUE THREAD

**Issue by VGerris** [Homebrew/brew#2385]
Percona 5.6 configure error causes configure of DBD-mysql-4.402 to fail
From the log of cpan:
I will use the following settings for compiling and testing:

  cflags        (mysql_config) = -I/usr/local/opt/percona-server@5.6/include/mysql   -g -fno-omit-frame-pointer -fno-strict-aliasing
  embedded      (mysql_config) =
  ldflags       (guessed     ) =
  libs          (mysql_config) = -L/usr/local/opt/percona-server@5.6/lib/mysql -lperconaserverclient -lz -lssl -lcrypto
  mysql_config  (guessed     ) = mysql_config
  nocatchstderr (default     ) = 0
  nofoundrows   (default     ) = 0
  nossl         (default     ) = 0
  testdb        (default     ) = test
  testhost      (default     ) =
  testpassword  (default     ) =
  testport      (default     ) =
  testsocket    (default     ) =
  testuser      (guessed     ) = vgerris

To change these settings, see 'perl Makefile.PL --help' and
'perldoc DBD::mysql::INSTALL'.

Checking if libs are available for compiling...
Can't link/include C library 'perconaserverclient', aborting.
-> N/A
-> FAIL Configure failed for DBD-mysql-4.042.

**brew config**
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b452fdb347d3dd5dde6e3a9b25bd1bf19a2a697c
Core tap last commit: 22 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.1 => /usr/local/bin/git
Perl: /Users/vgerris/perl5/perlbrew/perls/perl-5.10.1/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11

**brew doctor**
Your system is ready to brew.

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by VGerris** [comment]
I thought I did exactly that. Can you explain what is missing?

**Comment by VGerris** [comment]
Seems to be a package bug. Fix:
#pkglibdir='/usr/local/Cellar/percona-server@5.6/5.6.35-80.0/lib'
pkglibdir='/usr/local/opt/percona-server@5.6/lib'

vim /usr/local/Cellar/percona-server@5.6/5.6.35-80.0/bin/mysql_config

May I suggest to just test the package by doing a cpan DBD::mysql at a next change?

**Comment by MikeMcQuaid** [comment]
@VGerris You didn't fill in the requested checkboxes and you filed this on Homebrew/brew rather than Homebrew/homebrew-core. The 👎 doesn't particularly ingratiate us to help you, either.

For the packaging issue: could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by VGerris** [comment]
Hi Mike,

I was just hoping for a reaction and I found in unpleasant that is was closed while I tried to make the effort to fill in everything properly. I removed the headers perhaps? Still don't get what is wrong there.
I also thought I was posting it in the proper place, by following the text. Why is this core, it is just a package, right? 
Anyway, I just monkey patched my install, because I needed it to work.
I suspect the issue comes from symlinking, I haven't looked much further after it worked.

Could the packager be informed to do:
cpan DBD::mysql
after a change? That would have catched this error and the previous one I reported (SSL related).
Again: I am happy to contribute, but last time I tried I actually spend time to try and find the exact package and it ended up that I was pointed to some SSL flag things that didn't make sense and I could not fix without help. 
There is room for improvement, I don't know exactly how.
I hope it is useful for you to have the solution and push it in the right direction?

Thanks anyway for you help, support and your work in general! 
cheers

**Comment by robd** [comment]
@VGerris Hi. I have a similar type of problem. I just wondered if you know why changing the pkglibdir fixed it? For me, the two paths you mention point to the same directory. How does this make a difference?

`/usr/local/opt/percona-server@5.6/lib`
`/usr/local/Cellar/percona-server\@5.6/5.6.35-81.0/lib`

**Comment by VGerris** [comment]
hi,

I think it may be caused by one path containing a symlink. I haven't checked further on which program had a problem with that.
As I described, I tried to help out the last time, but I don't get to the point of having enough information to contribute a proper fix, and this time the ticket was closed.

If someone wants to take the time for it, feel free to p.m. me or point to the proper documentation. Anyway, I needed this to work for a dev setup so I thought to at least post it here.

I would be happy to read about implementing a solution structurally and help out.
grtz Vincent

**Comment by VGerris** [comment]
I posted this in the linked issue:

After some further research I found by using pkglibdir in /usr/local/opt/percona-server@5.6/bin/mysql_config for:

pkglibdir='/usr/local/Cellar/percona-server@5.6/5.6.35-81.0/lib'  gives:
cflags        (mysql_config) = -I/usr/local/opt/percona-server@5.6/include/mysql   -g -fno-omit-frame-pointer -fno-strict-aliasing
embedded      (mysql_config) = 
ldflags       (guessed     ) = 
libs          (mysql_config) = -L/usr/local/opt/percona-server@5.6/**lib/mysql** -lperconaserverclient -lz -lssl -lcrypto
mysql_config  (guessed     ) = mysql_config
nocatchstderr (default     ) = 0
nofoundrows   (default     ) = 0
nossl         (default     ) = 0
testdb        (default     ) = test
testhost      (default     ) = 
testpassword  (default     ) = 
testport      (default     ) = 
testsocket    (default     ) = 
testuser      (guessed     ) = vgerris


and pkglibdir='/usr/local/opt/percona-server@5.6/lib' gives:
cflags        (mysql_config) = -I/usr/local/opt/percona-server@5.6/include/mysql   -g -fno-omit-frame-pointer -fno-strict-aliasing
embedded      (mysql_config) = 
ldflags       (guessed     ) = 
libs          (mysql_config) = -L/usr/local/opt/percona-server@5.6/**lib** -lperconaserverclient -lz -lssl -lcrypto
mysql_config  (guessed     ) = mysql_config
nocatchstderr (default     ) = 0
nofoundrows   (default     ) = 0
nossl         (default     ) = 0
testdb        (default     ) = test
testhost      (default     ) = 
testpassword  (default     ) = 
testport      (default     ) = 
testsocket    (default     ) = 
testuser      (guessed     ) = vgerris

pkglibdir='/usr/local/Cellar/percona-server@5.6/5.6.35-81.0/lib'
pkglibdir='/usr/local/opt/percona-server@5.6/lib'

Apparently mysql_config does not evaluate the path properly, which causes the cpan command to fail. Any suggestions on how to fix this?
Should it be upstream or in :
https://github.com/Homebrew/homebrew-core/blob/master/Formula/percona-server@5.6.rb

If we need to patch the latter, if anyone can tell me how to patch a file that is in the tar.gz package, I am happy to make a pull request.
An existing example is also ok, or maybe someone who has done this can make it happen.

@MikeMcQuaid building was never the issue, the problem is that resulting mysql_config file is not proper. As described this is easily tested by doing a cpan -m DBD:mysql.

I realise this comment may not be too relevant here. What is relevant is that the install and build seem to work for me. Can you pm me about how to fix this above issue? Thanks a lot.

Since these are both closed, I will make a new one when I have time.

**Comment by MikeMcQuaid** [comment]
To repeat here: it sounds like this is an issue that needs to be submitted upstream. It doesn't sound like it's Homebrew-specific given it doesn't seem to affect MySQL in the same way. That said, if you can figure out a difference/problem with the formula and it is our fault we'd accept a PR to fix it. [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks again for your work here!
