### ISSUE TITLE
Improve the generated docs.brew.sh/Manpage.html

### ISSUE THREAD

**Issue by benjaminapetersen** [Homebrew/brew#2386]
Re: issue #2380 

This is an enhancement issue, opening it separately & intend to help working on it.  

**The original comment:**

Great start!  This is def a move in the right direction.  I think there might be a couple bugs & small tweaks that could improve the page.  

- I noticed some leaked `<var>formula</var>` tags in the markup, i think parsing the man page didn't quite process everything:
![screen shot 2017-03-23 at 9 43 59 am](https://cloud.githubusercontent.com/assets/280512/24250431/415ccd76-0fad-11e7-960b-79a75e550446.png) 
vs 
![screen shot 2017-03-23 at 9 44 21 am](https://cloud.githubusercontent.com/assets/280512/24250439/4e58db14-0fad-11e7-9631-f20e431c4c69.png)
- The style sheet might need some tweaks, or adjust the generated markup slightly.  For example, the explanation text is larger than the command itself:
![screen shot 2017-03-23 at 9 46 22 am](https://cloud.githubusercontent.com/assets/280512/24250537/984eae88-0fad-11e7-8297-8a348aecd284.png)
That is difficult to parse, but even just tweaking the font-sizes could be clearer (big difference scrolling a long page of this pattern):
![screen shot 2017-03-23 at 9 49 05 am](https://cloud.githubusercontent.com/assets/280512/24250661/0f7648d6-0fae-11e7-9146-cedcca796910.png)
- Even matching the same indentation hierarchy as the `man brew` output could improve the readability/usability:
![screen shot 2017-03-23 at 9 51 37 am](https://cloud.githubusercontent.com/assets/280512/24250785/6e78d92a-0fae-11e7-9d7c-31d79f6f5f55.png)
![screen shot 2017-03-23 at 9 51 42 am](https://cloud.githubusercontent.com/assets/280512/24250784/6e7445c2-0fae-11e7-8839-ab0a924ccb97.png)
The words `Print`, `Pass` and `See` line up vertically on the command line, giving hierarchy that is a bit broken on the web page.  Matching the `underline`, `bold`, etc text from the command line with the same text on the web page would also be helpful.  I think you should be able to see them side by side & easily connect the concepts.

Is it preferred to open this as a follow-on?
Thanks again.

**Comment by MikeMcQuaid** [comment]
Please don't copy-paste comments as issues in future and please complete the issue template every time, thanks.

We'll accept PRs to improve this but it's currently just using `ronn` to output the processed Markdown so fixes may need to be there instead. It's good enough from my perspective (particularly given this is already provided by `man brew`) so personally I won't be working on this any more but please feel free to do so and I'll review them.

Thanks!

**Comment by benjaminapetersen** [comment]
Oh sure, wasn't aiming to be annoying with that, I had just copied because I described items to be addressed & was intending to work on them & submit a PR for this issue.

**Comment by MikeMcQuaid** [comment]
@benjaminapetersen No worries; just don't need to submit an issue for planned work. I was going to reply to your previous issue comment. Thanks!

**Comment by MikeMcQuaid** [comment]
> I noticed some leaked <var>formula</var> tags in the markup, i think parsing the man page didn't quite process everything:

This was done in https://github.com/Homebrew/brew/pull/2440
