### ISSUE TITLE
No formulae at all were found in taps

### ISSUE THREAD

**Issue by jleeothon** [Homebrew/brew#2387]
- [x] If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug report

Output for `brew config`:

```
$ brew config
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 54abadb202fcb1f0cd7df057809e841e1930d94c
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/brew
Core tap HEAD: 54abadb202fcb1f0cd7df057809e841e1930d94c
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102, 1.8.0_92
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

Output for `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`:

```
HEAD is now at 54abadb Merge pull request #2359 from ilovezfs/migrator-allow-new-cellar-to-exist-already
Already up-to-date.
```

Output for `brew doctor`:

```
$ brew doctor
Your system is ready to brew.
```

I can basically not install any formula at all. Something like `brew install git` will fail with:

```
$ brew install git
Error: No available formula with the name "git" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
These formulae were found in taps:
homebrew/fuse/gitfs                        Caskroom/cask/gitbook                      Caskroom/cask/gitkraken                    Caskroom/cask/laullon-gitx                 Caskroom/cask/logitech-options             Caskroom/cask/snagit
Caskroom/cask/adobe-digital-editions       Caskroom/cask/gitbox                       Caskroom/cask/gitmoji                      Caskroom/cask/lego-digital-designer        Caskroom/cask/logitech-unifying            Caskroom/cask/subgit
Caskroom/cask/digital-power-station        Caskroom/cask/github-desktop               Caskroom/cask/gitscout                     Caskroom/cask/logitech-gaming-software     Caskroom/cask/nudgit                       Caskroom/versions/adobe-digital-editions2
Caskroom/cask/digital                      Caskroom/cask/githubpulse                  Caskroom/cask/gitter                       Caskroom/cask/logitech-harmony             Caskroom/cask/plotdigitizer                Caskroom/versions/smartgit-rc
Caskroom/cask/git-it                       Caskroom/cask/gitifier                     Caskroom/cask/gitup                        Caskroom/cask/logitech-media-server        Caskroom/cask/rowanj-gitx                  Caskroom/versions/snagit3
Caskroom/cask/gitbook-editor               Caskroom/cask/gitify                       Caskroom/cask/gitx                         Caskroom/cask/logitech-myharmony           Caskroom/cask/smartgit
To install one of them, run (for example):
  brew install homebrew/fuse/gitfs
```

Output for `brew tap` is:

```
$ brew tap
homebrew/core
homebrew/dupes
homebrew/php
homebrew/versions
```

Not sure if related (?), my Cellar is empty:

```
n$ ls -la /usr/local/Cellar
total 0
drwxrwxr-x+  2 othon  brew   68 Mar 23 17:42 .
drwxrwxr-x  13 othon  brew  442 Mar 23 17:42 ..
```

Is there any further piece of information I can provide? Any ideas why I might be unable to find any formulae at all? Thanks!

**Comment by bfontaine** [comment]
> ```
> Core tap ORIGIN: https://github.com/Homebrew/brew
> ```

This should be `https://github.com/Homebrew/homebrew-core`. Not sure how that would happen.

**Comment by jleeothon** [comment]
@bfontaine is the right command:

```
brew tap homebrew/core https://github.com/Homebrew/homebrew-core
```

**Comment by bfontaine** [comment]
No, it won’t do anything because `homebrew/core` is already tapped (and you can’t untap it).

Something like this should work:

```sh
cd $(brew --prefix)/Library/Taps/homebrew && rm -rf homebrew-core && brew tap homebrew/core
```

**Comment by jleeothon** [comment]
In my computer, `$(brew --prefix)/Library` doesn't exist (i.e. `/usr/local/Library`) 😅

**Comment by jleeothon** [comment]
Ah, it's probably `$(brew --prefix)/Homebrew/Library/Taps/homebrew` : )

**Comment by MikeMcQuaid** [comment]
`rm -rf /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core; brew update`

**Comment by jleeothon** [comment]
Using the right directory, it worked! Now I just have to set right the rest of my environment after this mess. Thanks you all!

Shall we close this ticket?
Any ideas on how this could have happened?
Is this kind of situation something that `brew doctor` could as well check for?

**Comment by MikeMcQuaid** [comment]
Closing this as I've opened a new PR to add this to `brew doctor` in https://github.com/Homebrew/brew/pull/2398. Thanks for the report!
