### ISSUE TITLE
Inconsistent link count between link and unlink

### ISSUE THREAD

**Issue by Blaisorblade** [Homebrew/brew#239]
Note the 40 vs 66. I can keep doing this forever, so something's wrong — hopefully, just the command output, and not some actual problem in my installation.
```
$ brew link neovim
Linking /usr/local/Cellar/neovim/0.1.4... 40 symlinks created
$ brew unlink neovim
Unlinking /usr/local/Cellar/neovim/0.1.4... 66 symlinks removed
$ brew link neovim
Linking /usr/local/Cellar/neovim/0.1.4... 40 symlinks created
$ brew unlink neovim
Unlinking /usr/local/Cellar/neovim/0.1.4... 66 symlinks removed
$ brew link neovim
Linking /usr/local/Cellar/neovim/0.1.4... 40 symlinks created
$ brew unlink -n  neovim|wc -l
      41
$ brew unlink -n neovim
Would remove:
[... 40 files to remove ...]
```

**Comment by mikemcquaid** [comment]
This is a known issue and not a high-priority one.

**Comment by xu-cheng** [comment]
> This is a known issue 

This is not issue. This is the correct behavior. The number of symlinks will be changed depending on your other files in the prefix.

**Comment by Blaisorblade** [comment]
And that makes it impossible to count how many links are actually created
or removed?
"A message to the user says nonsense" is an UX issue. I'll agree it's a
low-priority one.

-- 
Paolo Giarrusso
From smartphone, sorry for typos or excessive brevity
On May 13, 2016 10:59, "Xu Cheng" <notifications@github.com> wrote:

This is a known issue

This is not issue. This is the correct behavior. The number of symlinks
will be changed depending on your other files in the prefix.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Homebrew/brew/issues/239#issuecomment-218988959>

**Comment by xu-cheng** [comment]
> And that makes it impossible to count how many links are actually created
or removed?

It is not the problem of counting. The symlink numbers does change between link and unlink.

**Comment by Blaisorblade** [comment]
> It is not the problem of counting. The symlink numbers does change between link and unlink.

That seems absurd. More likely problem: `unlink` counts directory removals too, while there's no directly matching code for `link`:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/pathname.rb#L532-L536

That seems absurd because:
- if `link` and `unlink` are inverses, unlink must destroy what `link` creates
- if they weren't inverses, repeating those two commands is either destroying or creating files.

If the intended behavior is more complicated for good reason, feel free to point me to docs explaining it, or to reopen the issue calling for them to be written.

**Comment by mikemcquaid** [comment]
Your tone is starting to get a little rude @Blaisorblade; please check out our Code of Conduct: https://github.com/Homebrew/brew/blob/master/CODEOFCONDUCT.md.

If you would like to submit a pull request to improve this situation: feel free but we will not reopen something we do not consider to be an issue.

**Comment by Blaisorblade** [comment]
Thanks for offering to consider a pull request, I provided one in #242. Of course, I did not request that you fix the issue, because I agree it is a small one (I filed it anyway while I noticed), and I'm happy to contribute a fix. One strong point of Homebrew is its well-designed interface.

I'm sorry I overreacted to the technical disagreement and violated the CoC.

**Comment by apjanke** [comment]
Thanks for making a concrete PR out of this. It may take us a couple days to respond to it, since we're rolling up on the weekend now and this is a low/non-priority issue, but we appreciate you contributing and respecting the CoC.

**Comment by mikemcquaid** [comment]
> Thanks for offering to consider a pull request, I provided one in #242. Of course, I did not request that you fix the issue, because I agree it is a small one (I filed it anyway while I noticed), and I'm happy to contribute a fix. One strong point of Homebrew is its well-designed interface.

Awesome, will take a look.

> I'm sorry I overreacted to the technical disagreement and violated the CoC.

No worries, we really appreciate the apology ❤️
