### ISSUE TITLE
Feature Request: allow subcommands print help with `brew <command> --help`

### ISSUE THREAD

**Issue by muescha** [Homebrew/brew#2390]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this section with a brief summary of your issue **AND** the output of `brew config` and `brew doctor`. Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

### Propose a feature:

i would like to have help with `brew <command> --help` 

example with https://github.com/buo/homebrew-cask-upgrade : 

```
brew cu --help
```

but a subcommand can not "catch" the `--help` option:

> We cannot use brew cu --help because Homebrew hijacks --help option and shows its banner, I think it's a Homebrew's bug and should be fixed.
 (see https://github.com/buo/homebrew-cask-upgrade/issues/50#issuecomment-289028598)

**Comment by MikeMcQuaid** [comment]
See `brew services --help` and https://github.com/Homebrew/homebrew-services/blob/a5115e47b05e8d2a632ba7775599e698b240e5a2/cmd/brew-services.rb#L1-L31 for an example of how to implement help in external commands.
