### ISSUE TITLE
unknown options should be an error

### ISSUE THREAD

**Issue by mcfedr** [Homebrew/brew#2409]
I think its an error that `brew` just continues when passed unknown options. It should stop and let the user fix the options.

What are the reasons there are unknown options? Most likely its a typo.

For example I just ran

    brew install php71 --with-httpd

`brew` just continues, with a warning

    Warning: php71: this formula has no --with-httpd option so it will be ignored!

When really I want it to stop, and ill fix the option to be the correct version `--with-httpd24`

**Comment by bfontaine** [comment]
See also https://github.com/Homebrew/brew/issues/1860, https://github.com/Homebrew/legacy-homebrew/issues/8937.

**Comment by MikeMcQuaid** [comment]
Also: fill in the issue template.
