### ISSUE TITLE
Permission problems with .pm files

### ISSUE THREAD

**Issue by nkkollaw** [Homebrew/brew#2423]
- [x ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x ] Confirmed this is a problem with Homebrew/brew and not specific formulae

My config: https://gist.github.com/nkkollaw/9ace0e9279ec714f9fa04e49faa02e0e
`brew doctor` says I'm ready to brew (no errors).

# Bug report

## What problem

I'm getting a lot of errors while trying to install software with Homebrew.

All of them are similar to the following:

> Can't locate Getopt/Long.pm:   Permission denied at /usr/bin/pod2man5.18 line 19.
> BEGIN failed--compilation aborted at /usr/bin/pod2man5.18 line 19.

Seems to be a permission problem, but I can't figure out how to fix it.

## How to reproduce

This will trigger the error:

`brew install ack`

Which will print:

> ==> Using the sandbox
> ==> Downloading https://beyondgrep.com/ack-2.18-single-file
> Already downloaded: /Users/nbrogi/Library/Caches/Homebrew/ack-2.18.18-single-file
> ==> pod2man /usr/local/Cellar/ack/2.18/bin/ack ack.1
> Last 15 lines from /Users/nbrogi/Library/Logs/Homebrew/ack/01.pod2man:
> 2017-03-30 22:11:50 +0200
> 
> pod2man
> /usr/local/Cellar/ack/2.18/bin/ack
> ack.1
> 
> Can't locate Getopt/Long.pm:   Permission denied at /usr/bin/pod2man5.18 line 19.
> BEGIN failed--compilation aborted at /usr/bin/pod2man5.18 line 19.

## Additional notes

All of the files in /usr/bin are owned by root, which seems to cause the problem. However, I have not changed these permissions, so _I assume_ this is the default with macOS Sierra.

**Comment by MikeMcQuaid** [comment]
What's the output of `env | grep -i perl`?

**Comment by nkkollaw** [comment]
None.

`which perl` says:

> /usr/bin/perl

**Comment by MikeMcQuaid** [comment]
What does `ls -lha /usr/bin/pod2man5.18` and `/usr/bin/pod2man5.18 --version` output?

**Comment by nkkollaw** [comment]
> -rwxr-xr-x  1 root  wheel    13K Jul 31  2016 /usr/bin/pod2man5.18*

and 

> Can't locate Getopt/Long.pm:   Permission denied at /usr/bin/pod2man5.18 line 19.
> BEGIN failed--compilation aborted at /usr/bin/pod2man5.18 line 19.

I appreciate your help.

**Comment by MikeMcQuaid** [comment]
How about: `ls -lha /System/Library/Perl/5.16/Getopt/ /System/Library/Perl/5.18/Getopt/ `

**Comment by nkkollaw** [comment]
> /System/Library/Perl/5.16/Getopt/:
total 64
drwxr-xr-x    4 root  wheel   136B Jul 31  2016 ./
drwxr-xr-x  130 root  wheel   4.3K Jul 31  2016 ../
-rw-r--r--    1 root  wheel    77K Jul 31  2016 Long.pm
-rw-r--r--    1 root  wheel   8.2K Jul 31  2016 Std.pm

> /System/Library/Perl/5.18/Getopt/:
> total 64
> drwxr-xr-x    4 root  wheel   136B Jul 31  2016 ./
> drwxr-xr-x  130 root  wheel   4.3K Jul 31  2016 ../
> -rw-r--r--    1 root  wheel    79K Jul 31  2016 Long.pm
> -rw-r--r--    1 root  wheel   8.2K Jul 31  2016 Std.pm

**Comment by MikeMcQuaid** [comment]
Sorry, I have no ideas why but there's something broken with your `/usr/bin/pod2man5.18`. You may need to reinstall macOS. Closing as this doesn't affect anyone else.

**Comment by nkkollaw** [comment]
Doesn't seem so: https://github.com/Homebrew/legacy-homebrew/issues/33479

Whatever, though.

**Comment by MikeMcQuaid** [comment]
> Doesn't seem so: Homebrew/legacy-homebrew#33479

That's a different issue, no-one has the same problem you have.

> Whatever, though.

Alternatively: "thanks for spending your free, unpaid time on the weekend trying to help me".
