### ISSUE TITLE
No available formula with the name "android-sdk" when I brew install android-sdk

### ISSUE THREAD

**Issue by tangkunyin** [Homebrew/brew#2424]
Hi there:

I have a wrong with `android-sdk` after  update xcode,`brew doctor`:
```
Error: No available formula with the name "android-sdk" 
```
But I try to `brew list`，`android-sdk` is in the list.In the end,I remove `android-sdk` manually and reinstall with  `brew install android-sdk`:
```
Error: No available formula with the name "android-sdk" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/android-sdk
To install it, run:
  brew install Caskroom/cask/android-sdk
```
So, I `brew install Caskroom/cask/android-sdk`.It is successfully.

How to config the `ANDRIOD_HOME` under `Caskroom/cask/android-sdk` and why `No available formula with the name "android-sdk"`?

My brew version is `1.1.0`

Hope your answers, Thanks...

**Comment by MikeMcQuaid** [comment]
> How to config the ANDRIOD_HOME under Caskroom/cask/android-sdk

See https://github.com/caskroom/homebrew-cask/issues/31550.



> why No available formula with the name "android-sdk"?

We don't provide that formula any longer.

Please fill out the issue template in future.

**Comment by tangkunyin** [comment]
@MikeMcQuaid thanks a lot
