### ISSUE TITLE
No android-ndk formula after update.

### ISSUE THREAD

**Issue by andreyugolnik** [Homebrew/brew#2425]
Hello,

`$ brew update`
`...`
`==> Deleted Formulae`
`android-ndk ✔               android-sdk ✔               fb-adb                      hdf@4                       play@1.4`
`android-platform-tools      dwarf-fortress              gst-ffmpeg@0.10             multirust`
`==> android-ndk has been moved to Homebrew-Cask.`
`To uninstall the formula and install the cask run:`
`  brew uninstall --force android-ndk`
`  brew cask install android-sdk`
`==> android-sdk has been moved to Homebrew-Cask.`
`To uninstall the formula and install the cask run:`
`  brew uninstall --force android-sdk`
`  brew cask install android-sdk`

`$ brew search android-ndk`
`No formula found for "android-ndk".`

But

`$ brew search android-sdk`
`Caskroom/cask/android-sdk`

**Comment by ilovezfs** [comment]
https://github.com/caskroom/homebrew-cask/issues/31234
https://github.com/caskroom/homebrew-cask/pull/31610
https://github.com/caskroom/homebrew-cask/pull/31614
