### ISSUE TITLE
`brew install -d` and `brew install -i` are undocumented

### ISSUE THREAD

**Issue by johnhawkinson** [Homebrew/brew#2437]
Homebrew documentation references `brew install -d` and `brew install -i` in passing, e.g.

https://github.com/Homebrew/brew/blob/master/docs/Manpage.md:
```
  * `HOMEBREW_DEBUG_INSTALL`:
    When `brew install -d` or `brew install -i` drops into a shell,
    `HOMEBREW_DEBUG_INSTALL` will be set to the name of the formula being
    brewed.
```

and

https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md
````
### Check the build system

``` 
sh
brew install -i foo
``` 
```` 

The documentation and cookbook guidance certainly shouldn't reference undocumented options in an offhand fashion. I would also say that undocumented options simply shouldn't exist (maybe this is not agreed-upon, though?)

I assume that `-d` is short for `--debug` and `-i` is short for `--interactive` but I spent more than a reasonable amount of time source-diving and failed to figure out how that is handled, so I'm giving up and filing this without a patch.

I note that some other short options are documented, like `-s` for `--build-from-source`, although it doesn't appear in the usage summary:

```
install [--debug] [--env=(std|super)] [--ignore-dependencies|--only-dependencies] [--cc=compiler] [--build-from-source|--force-bottle] [--devel|--HEAD] [--keep-tmp] [--build-bottle]
```

**Comment by MikeMcQuaid** [comment]
Please fill out the issue template.

**Comment by MikeMcQuaid** [comment]
> Please fill out the issue template.

To note: even although this was fixed without we'd really rather you filled it in without exception for every single issue report, thanks.

**Comment by johnhawkinson** [comment]
> To note: even although this was fixed without we'd really rather you filled it in without exception for every single issue report, thanks.

What's the point of filling out the template for documentation bugs that are referenced to webpages in the master branch on github? The information in the template is entirely irrelevant to the bug?

The template says:

> _You can erase any parts of this template not applicable to your Issue._

which I interpreted to mean I could reasonably delete everything in the template because none of it applied to web docbugs. Maybe it should be reworded.

Anyhow, here you go.

---

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug reports:


```
pb3:~ jhawk$ brew config
Unsetting PERL5LIB to protect you from yourself
HOMEBREW_VERSION: 1.1.11-226-g974b5e2fa2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 974b5e2fa26a162d29f97e996eb687b12a46a952
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eb852b832ab49a4acf184e14734d1c2ff4f26d98
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74, 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11
pb3:~ jhawk$ brew doctor
Unsetting PERL5LIB to protect you from yourself
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
  lesstif
  numpy
  poppler
  python
pb3:~ jhawk$ 
```

**Comment by MikeMcQuaid** [comment]
> which I interpreted to mean I could reasonably delete everything in the template because none of it applied to web docbugs. Maybe it should be reworded.

I will change this, thanks.
