### ISSUE TITLE
[wish] date-based versioning in the RCF 3339 format

### ISSUE THREAD

**Issue by retokromer** [Homebrew/brew#2439]
Currently date based versioning using RFC 3339 (e.g. `v2017-04-02`) is cut (in the example to `04-02` i.e. `/usr/local/Cellar/my_formula/04-02` instead of `/usr/local/Cellar/my_formula/2017-04-02`). Only the less readable writing without separation (`v20170402` i.e. `/usr/local/Cellar/my_formula/20170402`) or with the "wrong" separation (`v2017.04.02` i.e. `/usr/local/Cellar/my_formula/2017.04.02`) seem to work. I suggest to allow also the "correct" separation character.

**Comment by MikeMcQuaid** [comment]
We interpret everything internally using semantic versioning, essentially so this isn't really possible. You can set `version` to whatever you want, though, it's just comparisons may not work as expected.

**Comment by retokromer** [comment]
Thank you for the feedback!

**Comment by retokromer** [comment]
@MikeMcQuaid If I try to add the regex for this in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/version.rb and open a PR, will this be considered or I am loosing my time? I am fine either way, just asking before starting.

**Comment by MikeMcQuaid** [comment]
@retokromer If you can add a regex and tests then it may be accepted, yeh.
