### ISSUE TITLE
Error: undefined method core_formula? for FormulaAuditor

### ISSUE THREAD

**Issue by lordqwerty** [Homebrew/brew#2449]
# Please always follow these steps:
- [X] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

#### What you were trying to do (and why)

Currently I am trying to build a bottle of `haskell-stack` for Linuxbrew see https://github.com/Linuxbrew/homebrew-core/pull/2267. However, build fails because of `undefined method `core_formula?' for #<FormulaAuditor:0x000000028cf738>`.

#### What happened (include command output)
```
==> brew audit haskell-stack --online
Error: undefined method `core_formula?' for #<FormulaAuditor:0x000000028cf738>
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/linuxbrew/.linuxbrew/Library/Homebrew/dev-cmd/audit.rb:469:in `block (2 levels) in audit_deps'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dev-cmd/audit.rb:447:in `block in audit_deps'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dev-cmd/audit.rb:444:in `each'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dev-cmd/audit.rb:444:in `audit_deps'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dev-cmd/audit.rb:1263:in `audit'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dev-cmd/audit.rb:78:in `block in audit'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dev-cmd/audit.rb:74:in `each'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dev-cmd/audit.rb:74:in `audit'
/home/linuxbrew/.linuxbrew/Library/Homebrew/brew.rb:91:in `<main>'
==> FAILED
```

#### What you expected to happen

I would expect this to pass since bottles for OS X exist.

#### Step-by-step reproduction instructions (by running `brew` commands)

See [CircleCI Build](https://circleci.com/gh/Linuxbrew/homebrew-core/4755?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

#### Possible Fix

In https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L479 it feels like it should be:
```diff
-           (core_formula? || !dep_f.versioned_formula?)
+           (dep_f.core_formula? || !dep_f.versioned_formula?)
```

This is also the same in Linuxbrew https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L469

**Comment by MikeMcQuaid** [comment]
> Ran brew config and brew doctor and included their output with your issue?

You didn't do this and there doesn't seem to be any reproduction on a macOS system here so: closing

**Comment by lordqwerty** [comment]
But like https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L414 is it not missing `formula.core_formula?` ?

**Comment by MikeMcQuaid** [comment]
I'll reopen when I get a report from a macOS system that includes `brew config` and `brew doctor` output.

**Comment by sjackman** [comment]
To reproduce the issue with Homebrew/brew on Mac, `brew edit hello` and add
```ruby
depends_on "pkgconfig"
```
and run
```sh
brew audit hello
```
```
Error: undefined method `core_formula?' for #<FormulaAuditor:0x007fdfd51ecb90>
```

**Comment by MikeMcQuaid** [comment]
Thanks @sjackman, I can reproduce from that.

**Comment by MikeMcQuaid** [comment]
> Step-by-step reproduction instructions (by running brew commands)
> 
> See CircleCI Build

Just for future reference: if this has been commands like @sjackman's this would have been fixed earlier today.
