### ISSUE TITLE
Update depends on to allow [OR|XOR|Array] or [Cask|Formula]

### ISSUE THREAD

**Issue by BenjaminHCCarr** [Homebrew/brew#2453]
With the changes to `brew` specifically with regard to the `boneyard` changes, this week I had a bunch of formulas pop up as deleted. Mostly due to the `:tuntap` signed kext problem:
Homebrew/homebrew-core/pull/2075
Homebrew/homebrew-core/pull/2075
An example: Homebrew/homebrew-core/commit/17df29ee0

We have a bunch of problems that could all be solved by changing/adding stanzas, re: `depends_on` and `meta-formulas`:
Homebrew/brew/issues/2300 [meta-formula]
      @MPLew-is posited [MPLew-is/homebrew-blend](https://github.com/MPLew-is/homebrew-blend)
      he also noted

> From
> https://github.com/Homebrew/brew/blob/b6d10769d3ac07e4b1322c9fd4781b500720f0fa/Library/Homebrew/requirement.rb#L34-L43

caskroom/homebrew-cask/issues/19369 [OR / XOR]
caskroom/homebrew-cask/issues/26345 [OR / XOR & Formula vs Cask (R)]
Homebrew/brew/issues/1887 [mariadb vs mysql; breaks doctor]

While we have discussed the use of `caveats` in caskroom/homebrew-cask as a "workaround" this is less than ideal; And if testing isn't possible as mentioned in caskroom/homebrew-cask/issues/15603 and https://github.com/Homebrew/homebrew-core/pull/2076#issuecomment-226948639

Maybe we require some commitment by end user; I don't mean to create more work; but possibly a flag `--untested` for something that requires a `kext` like `tuntap` on a formula.

It seems we have hit a point where we have multiple problems that require similar fixes to the depends_on are; either allowing an array (like all mysql or redis forks) or relying on cask alone (tuntap), or relying on cask or formula (R).

**Comment by MikeMcQuaid** [comment]
We may consider allowing depending on Casks in the future but this isn't something we're actively planning to work on.
