### ISSUE TITLE
[FR]Please allow filter brew list of formulas installed with --HEAD

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#2455]
It may be useful to have following list in order to updated those formulas in script like,
`brew list --head|xargs brew reinstall`
For now It's also possible but it requires awk:
```shell
brew list --versions|grep -i head|awk '{print $1}'|xargs brew reinstall --HEAD
```

**Comment by MikeMcQuaid** [comment]
Given it's possible using pipes we're unlikely to add this, sorry.

Also, please fill out the issue body before submitting the issue so I don't get an email with a blank body 😉
