### ISSUE TITLE
there is always a warning  about Cellar?

### ISSUE THREAD

**Issue by SnuggleE** [Homebrew/brew#2457]
_Warning: your HOMEBREW_PREFIX is set to /usr/local but HOMEBREW_CELLAR is set
to /usr/local/Homebrew/Cellar. Your current HOMEBREW_CELLAR location will stop
you being able to use all the binary packages (bottles) Homebrew provides. We
recommend you move your HOMEBREW_CELLAR to /usr/local/Cellar which will get you
access to all bottles."_

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by frjtrifork** [comment]
For other slow ones like me :) ending up here for the same issue - doing the fix written here removes the warning for me:

https://discourse.brew.sh/t/warning-your-homebrew-prefix-is-set-to-usr-local-but-homebrew-cellar-is-set-to-usr-local-cellar-your-current-homebrew-cellar/229/16

`brew bundle dump
rm -rf /usr/local/Homebrew/Cellar
brew bundle`

**Comment by usmanismail** [comment]
FYI to other coming here this did not fix it for me.
