### ISSUE TITLE
unable to access 'https://github.com/Homebrew/brew/'

### ISSUE THREAD

**Issue by johnwrestler** [Homebrew/brew#2459]
I am trying to install Homebrew using the install/curl command on https://brew.sh/ When I first ran it, it was able to download and install several things, but not brew. Now when I run the install command it results in: 
```
xxxx:~ xxxxx$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
fatal: unable to access 'https://github.com/Homebrew/brew/': Received HTTP code 407 from proxy after CONNECT
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force --depth=1
```

This is on my work computer, however, I have GitHub configured for both personal and enterprise and am able to clone public GitHub.com repos. Any thoughts on why I am receiving the fatal connection issue? 

Thank you for any assistance!!

**Comment by MikeMcQuaid** [comment]
This seems to be an issue with your work proxy. You need to configure `curl` and `git` (and perhaps your work proxy) to allow it to connect. There's nothing we can do to help here.

Also, please always fill out the issue template (as it tells you to do).
