### ISSUE TITLE
Syntax error when trying to install Homebrew on Mac OS Sierra

### ISSUE THREAD

**Issue by jaymie-liuobe** [Homebrew/brew#2460]
I am trying to install Homebrew on Mac OS Sierra. I have already installed Xcode. 

**Last login: Thu Apr  6 14:21:41 on ttys000
sysops-mbp:~ XXXX$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-e:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input
Downloading file '-fsSL' from URL ('https://raw.githubuser...
                             ^
sysops-mbp:~ XXXX$** 

All I did was copying /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" from https://brew.sh and pasting onto the terminal.

**Comment by MikeMcQuaid** [comment]
Sorry, this is an issue affecting only you so you'll need to figure it out yourself. Please always fill out the issue template in future.
