### ISSUE TITLE
brew doctor and most other commands fail after unsuccessful uninstall

### ISSUE THREAD

**Issue by mmakunas** [Homebrew/brew#2464]
# Please always follow these steps:
- [✔️] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [✔️] Ran `brew update` and retried your prior step?
- [✔️] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [✔️] Ran `brew config` and `brew doctor` and included their output with your issue?
[https://gist.github.com/mmakunas/fd074f6787721bd1da18b4477f646939](https://gist.github.com/mmakunas/fd074f6787721bd1da18b4477f646939)

To help us debug your issue please explain:
- What you were trying to do (and why)

I was uninstalling tomcat, tomcat-native, and apr vis brew uninstall. Those worked fine. Then I tried to uninstall maven via brew unistall maven. It failed and almost all brew commands failed after that. 

- What happened (include command output)
`
➜  ~ brew doctor
Error: Version value must be a string; got a NilClass ()
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/version.rb:186:in 'create'
/usr/local/Homebrew/Library/Homebrew/pkg_version.rb:12:in 'parse'
/usr/local/Homebrew/Library/Homebrew/keg.rb:350:in 'version'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:270:in 'each'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:270:in 'max_by'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:270:in 'from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1051:in 'block in check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1048:in 'reject'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1048:in 'check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in 'block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in 'each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in 'doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in '<main>'
`

- What you expected to happen
For it to successfully uninstall kegs and continue working.

- Step-by-step reproduction instructions (by running `brew` commands)
brew doctor

**Please note we may immediately close your issue without comment if you do not fill out the issue template and provide ALL the requested information.**

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it and alternatives considered.
Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
> Step-by-step reproduction instructions (by running brew commands)
> n/a

This definitely is applicable.

**Comment by mmakunas** [comment]
updated

**Comment by MikeMcQuaid** [comment]
Can you paste the output of `brew doctor --debug`? Thanks.

**Comment by MikeMcQuaid** [comment]
@mmakunas Ping on that.

**Comment by mmakunas** [comment]
Apologies for the delayed response. I was blocked on something for work, so I ended up uninstalling homebrew and then reinstalling. Which ended up being much much easier than I expected. Works fine now.

**Comment by wookoouk** [comment]
Same issue on a brand new install:

[pagem@software ~]$ brew doctor --debug
Checking check_access_cache
Checking check_access_cellar
Checking check_access_homebrew_repository
Checking check_access_lock_dir
Checking check_access_logs
Checking check_access_prefix_directories
Checking check_access_site_packages
Checking check_brew_git_origin
Checking check_coretap_git_origin
Checking check_dyld_vars
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: /tsl/software/production/bin/core/../..//hpccore/5/x86_64/lib64:/tsl/software/production/bin/core/../..//hpccore/5/x86_64/lib:
Checking check_for_anaconda
Checking check_for_bad_python_symlink
Checking check_for_config_scripts
Checking check_for_enthought_python
Checking check_for_external_cmd_name_conflict
Checking check_for_gettext
Checking check_for_git
Checking check_for_iconv
Checking check_for_installed_developer_tools
Checking check_for_library_python
Checking check_for_multiple_volumes
Checking check_for_non_prefixed_coreutils
Error: Version value must be a string; got a NilClass ()
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/version.rb:198:in `initialize'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/tap.rb:265:in `new'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/tap.rb:265:in `install'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/cmd/tap.rb:52:in `tap'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Failure while executing: /usr/users/sl/pagem/.linuxbrew/bin/brew tap homebrew/core -q
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/utils.rb:291:in `safe_system'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/tap.rb:584:in `ensure_installed!'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/tap.rb:615:in `formula_dir'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/formulary.rb:416:in `core_path'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/formulary.rb:361:in `loader_for'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/formulary.rb:274:in `factory'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/formula.rb:1492:in `[]'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/diagnostic.rb:974:in `check_for_non_prefixed_coreutils'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/users/sl/pagem/.linuxbrew/Library/Homebrew/brew.rb:100:in `<main>'

**Comment by MikeMcQuaid** [comment]
@wookoouk This is Homebrew not Linuxbrew.
