### ISSUE TITLE
Add a command to install from a list of packages in a file

### ISSUE THREAD

**Issue by chivalry** [Homebrew/brew#2467]
Using Python's `pip` utility, it's possible to install Python packages that are listed in a text file using the command `pip install -r requirements.txt`. This would be nice within brew, allowing users to export installed packages with `brew leaves > packages.txt` and install those packages with something like `brew install -r packages.txt`.

Basically, duplicate the functionality of the script given as an answer to my StackOverflow [question](http://apple.stackexchange.com/questions/279077/how-can-i-install-all-brew-packages-listed-in-a-text-file/279078#279078).

**Comment by reitermarkus** [comment]
This is exactly what [`brew bundle`](https://github.com/homebrew/homebrew-bundle) does! 😉
