### ISSUE TITLE
Add way to avoid adding --browse to "hub pull-request" for bump-formula-pr

### ISSUE THREAD

**Issue by Daniel15** [Homebrew/brew#2468]
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

When running `brew bump-formula-pr`, it always passes the `--browse` argument to `hub pull-request` (code ref: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L322). This doesn't work when running on a headless server such as a CI system, as these systems intentionally don't have a browser configured.

```
To github.com:Daniel15/homebrew-core.git
 * [new branch]      yarn-0.23.0 -> yarn-0.23.0
Branch yarn-0.23.0 set up to track remote branch yarn-0.23.0 from Daniel15.
Please set $BROWSER to a web launcher
Error: Failure while executing: hub pull-request --browse -m yarn\ 0.23.0

Created\ with\ `brew\ bump-formula-pr`.
```

I encountered this on Linuxbrew but the code is exactly the same in Homebrew.

I'd suggest adding some configuration options, or a `--non-interactive` command-line option which would avoid anything that does not work in this environment.

Also see https://github.com/yarnpkg/yarn/issues/2841

`brew config` output:
```
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 59c9ddbc1d9b9dfdeb0514768e0efd0112c63b25
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 304e81be80435d9c169e552c858518e62fbcba8b
Core tap last commit: 5 minutes ago
HOMEBREW_PREFIX: /home/daniel/.linuxbrew
HOMEBREW_REPOSITORY: /home/daniel/.linuxbrew
HOMEBREW_CELLAR: /home/daniel/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: single-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.11.0 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: N/A
Kernel: Linux 4.7.0-1-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 9.0 (stretch)
Codename: stretch
OS glibc: 2.24
OS gcc: 6.3.0
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A
```

**Comment by MikeMcQuaid** [comment]
> I'd suggest adding some configuration options, or a --non-interactive command-line option which would avoid anything that does not work in this environment.

Sounds like a good idea. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by Daniel15** [comment]
I don't have time to work on a PR for this at the moment, but for now I just hacked around it by setting `BROWSER=/bin/true`.

**Comment by MikeMcQuaid** [comment]
Glad you found a solution, thanks for letting us know.

**Comment by MikeMcQuaid** [comment]
I've opened https://github.com/Homebrew/brew/pull/3398 to address this.
