### ISSUE TITLE
Please delete these paths and run `brew update`.

### ISSUE THREAD

**Issue by lqjack** [Homebrew/brew#2469]
10001 ◯ : brew update
Updated 2 taps (caskroom/cask, homebrew/core).
==> New Formulae
alexjs            conjure-up        expect            gnupg@2.0         gzip              lapack            libpcap           ncompress         rsync             tcpdump           xmlsectool
apple-gcc42       diffstat          file-formula      gpatch            heimdal           less              lsof              ncurses           screen            terraform-docs    zlib
awk               diffutils         fzy               gperf             httpflow          libedit           m4                ntp               shfmt             unzip
bc                ed                gitter-cli        grep              jvm-mon           libetpan          make              openldap          streamlink        whois
bzip2             exa               gnupg@1.4         groff             krb5              libiconv          nano              openssh           tcl-tk            write-good
==> Updated Formulae
ack                      coturn                   gearboy                  imlib2                   lldpd                    openttd                  ragel                    sysdig
afl-fuzz                 cppcheck                 gearsystem               influxdb                 logstash                 ophcrack                 re2                      tailor
aha                      crystax-ndk              generate-json-schema     ipfs                     logtalk                  orientdb                 riak                     talloc
amazon-ecs-cli           cucumber-cpp             geoip                    jboss-forge              lumo                     osmfilter                riemann                  tarsnap-gui
ansible                  dar                      geoserver                jenkins                  lynis                    osrm-backend             rlwrap                   tcpreplay
antigen                  davmail                  getdns                   jenkins-lts              macvim                   packetbeat               roswell                  telegraf
apache-geode             dbhash                   giflib                   jetty                    mapserver                paket                    rtags                    terraform
apache-zeppelin          dbus                     git                      jetty-runner             maven                    pango                    rtv                      tfenv
app-engine-java          deis                     git-cola                 jfrog-cli-go             media-info               pari                     ruby                     tgui
aptly                    dialog                   git-lfs                  jmxtrans                 mediaconch               passpie                  ruby-build               todolist
aptly-completion         dirmngr                  git-plus                 json-fortran             mercurial                pdal                     ruby@2.2                 todoman
arangodb                 django-completion        git-town                 jsonschema2pojo          metabase                 pdf2htmlex               ruby@2.3                 tomcat
archi-steam-farm         djview4                  gitbucket                jumanpp                  metricbeat               percona-server           s-search                 tomcat@7
arm                      docker                   github-release           kafkacat                 mg3a                     percona-server@5.5       s6                       transcrypt
armor                    docker-completion        gitlab-ci-multi-runner   khal                     mikutter                 percona-server@5.6       sbcl                     translate-shell
artifactory              docker-compose           glassfish                kibana                   mingw-w64                percona-xtrabackup       scw                      treefrog
asn1c                    dpkg                     glibmm                   knot                     mkdocs                   pgrouting                sflowtool                typescript
astyle                   dspdfviewer              gnome-recipes            knot-resolver            mkvtoolnix               platformio               sha1dc                   ubertooth
ats2-postiats            dvm                      gnupg                    kobalt                   mobile-shell             plustache                shellcheck               urh
aws-sdk-cpp              efl                      gnutls                   kompose                  modd                     pmd                      shyaml                   urweb
awscli                   ejabberd                 go                       ktmpl                    monetdb                  pngquant                 skinny                   uwsgi
azure-cli                elasticsearch            gobject-introspection    kube-aws                 mongo-c-driver           ponyc                    snappystream             vala
b2-tools                 elm-format               godep                    kubernetes-cli           mongodb                  pre-commit               solarus                  vice
bash-git-prompt          etcd                     goenv                    kubernetes-helm          mono                     prettyping               solr                     vim
bit                      exercism                 gollum                   latex2html               mpdas                    protobuf                 sourcekitten             vnu
bmake                    fabio                    gor                      ldc                      nativefier               purescript               spdlog                   webpack
boom-completion          fdroidserver             gosu                     lean-cli                 neo4j                    pushpin                  sphinx-doc               wine
botan                    feedgnuplot              gotags                   lft                      netpbm                   pwntools                 sqldiff                  winetricks
bup                      fftw                     gpa                      libbtbb                  nghttp2                  pybind11                 sqlite                   xdot
byobu                    filebeat                 gpg-agent                libcroco                 node                     pyenv                    sqlite-analyzer          xmake
cake                     fio                      gpgme                    libgosu                  node-build               pypy                     sqlmap                   xplanet
certbot                  flow ✔                   groonga                  libgphoto2               node@4                   qbs                      squid                    xsv
chapel                   fluent-bit               grpc                     libhttpseverywhere       node@6                   qca                      ssh-copy-id              yadm
checkstyle               flyway                   gwenhywfar               liblastfm                nomad                    qcachegrind              statik                   yarn
chromedriver             fonttools                gxml                     liblinear                notmuch                  qjackctl                 stdman                   yaz
clipsafe                 fq                       h2o                      libming                  npth                     qjson                    stern                    youtube-dl
clutter-gst              frege                    haproxy                  libmtp                   nspr                     qscintilla2              stone-soup               zurl
cmake                    g3log                    hashcat                  libosmium                nudoku                   qtads                    strongswan
cockatrice               galen                    hledger                  libphonenumber           nzbget                   quazip                   stunnel
codequery                gammaray                 honcho                   librdkafka               ocrad                    quex                     swiftformat
color-code               gammu                    hunspell                 librsvg                  oniguruma                qwt                      swiftlint
consul                   gauge                    idris                    libsecret                ooniprobe                qwtpolar                 sxiv
consul-template          gdal                     imagemagick              libtins                  openmotif                qxmpp                    syncthing
convox                   gdk-pixbuf               imagemagick@6            libtommath               opensc                   rabbitmq                 sysbench
==> Renamed Formulae
eris -> monax                                                       mongodb30 -> mongodb@3.0                                            swig2 -> swig@2
ledger26 -> ledger@2.6                                              mongodb32 -> mongodb@3.2                                            swig304 -> swig@3.04
libpng12 -> libpng@1.2                                              pyqt5 -> pyqt                                                       thrift090 -> thrift@0.90
libpqxx3 -> libpqxx@3                                               qt5 -> qt                                                           unison240 -> unison@2.40
libxml278 -> libxml2@2.7                                            selenium-server-standalone245 -> selenium-server-standalone@2.45    v8-315 -> v8@3.15
logstash24 -> logstash@2.4                                          solr54 -> solr@5.4                                                  varnish4 -> varnish@4
mapnik2 -> mapnik@2                                                 solr55 -> solr@5.5                                                  vim74 -> vim@7.4
maven31 -> maven@3.1                                                srtp15 -> srtp@1.5                                                  zeromq32 -> zeromq@3.2
maven32 -> maven@3.2                                                subversion18 -> subversion@1.8                                      zeromq40 -> zeromq@4.0
==> Deleted Formulae
fb-adb                       giflib@5                     gnupg2                       gnupg@2.1                    gst-ffmpeg@0.10              multirust                    play@1.4
Error: Could not link:
/usr/local/share/doc/homebrew

Please delete these paths and run `brew update`.

**Comment by ilovezfs** [comment]
```
Error: Could not link:
/usr/local/share/doc/homebrew

Please delete these paths and run `brew update`.
```

Do this.
