### ISSUE TITLE
Wrong homepage in formula for eet

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/brew#247]
Currently `brew home eet` leads to a page displaying "The requested URL /auto/eet/eet_main.html was not found on this server."

It seems that the embedded URL in the formula is 
`https://docs.enlightenment.org/auto/eet/eet_main.html`
instead of
`https://docs.enlightenment.org/auto/eet_main.html`

**Comment by dunn** [comment]
Thanks for the report!  As it happens, though, we just removed `eet` since it's been superseded by EFL: https://github.com/Homebrew/homebrew-core/commit/8716fc67b430e77e20c9223099fba4b08801e2fe
