### ISSUE TITLE
Brew commands no output and not terminating

### ISSUE THREAD

**Issue by cjkonopka** [Homebrew/brew#2488]
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

**Please note we may immediately close your issue without comment if you do not fill out the issue template and provide ALL the requested information.**

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it and alternatives considered.
Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by cjkonopka** [comment]
When I run a brew command the command is never finished or outputs anything. The only sort of response I get is that tr, ruby, and bash and being referenced on top of my terminal.

when I run brew by itself i get a list of the possible commands. However other commands such as brew update, brew config or brew doctor have no output and run indefinitely. This seems to happen idempant of the call as running brew (anything) will also produce the same result

running Seirra 10.12.3

brew -v
Homebrew >1.1.0 (no git repository)
Homebrew/homebrew-core N/A

**Comment by MikeMcQuaid** [comment]
Sorry, we don't have enough detail to help you. Try to reinstall Homebrew. Stop creating duplicate issues or your right to create issues at all would be blocked.

**Comment by cjkonopka** [comment]
I was assuming the first was closed due to me not realizing it was posted without a body, sorry for creating the duplicate

**Comment by MikeMcQuaid** [comment]
That's OK, thanks for the apology.
