### ISSUE TITLE
Brew commands not providing output nor termining

### ISSUE THREAD

**Issue by cjkonopka** [Homebrew/brew#2489]
- [X] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

When I run a brew command the command is never finished or outputs anything. The only sort of response I get is that tr, ruby, and bash and being referenced on top of my terminal.

when I run brew by itself i get a list of the possible commands. However other commands such as brew update, brew config or brew doctor have no output and run indefinitely. This seems to happen independent of the call as running brew (anything) will also produce the same result. (correction brew -v executes)

running Seirra 10.12.3

brew -v
Homebrew >1.1.0 (no git repository)
Homebrew/homebrew-core N/A

**Comment by MikeMcQuaid** [comment]
Stop reposting the same issue when they get closed.
