### ISSUE TITLE
Keg-Only Caveat Python3

### ISSUE THREAD

**Issue by heinemml** [Homebrew/brew#249]
Hi,

as mentioned in https://github.com/Homebrew/homebrew-science/issues/3667 keg-only formulas which build python modules show a message how you can link the generated python modules.
```
If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth
```
 This message only appears for python2.x. The opencv3 formula can be build with python3 support but no message appears. If you disable the python2 build (like `brew install opencv3 --without-python --with-python3`) you get no message at all. 

The current [Implementation](https://github.com/Homebrew/brew/blob/8284fb3fef9860a67f3303f17cb6fd99a2ebc168/Library/Homebrew/caveats.rb#L99) only handles python2. Wouldn't it make sense to show a similar message when building python3 modules? Or should this be handled by the formular directly? I couldn't find any documentation on this.

**Comment by mikemcquaid** [comment]
CC @tdsmith for thoughts.

**Comment by tdsmith** [comment]
It would make sense!

**Comment by MikeMcQuaid** [comment]
If this is still broken for you: we'll accept PRs for this but we're not actively working on it at this time.

**Comment by tdsmith** [comment]
I'm working on this but the details are annoying and I don't like my solution yet; within the next week, for sure.

**Comment by MikeMcQuaid** [comment]
@tdsmith Any news on this?
