### ISSUE TITLE
Add an option to install only if not already installed

### ISSUE THREAD

**Issue by zapashcanon** [Homebrew/brew#2491]
Hi,

We recently added `set -e` in our CI script. We had something like:

```sh
#!/usr/bin/env bash

set -e

PACKAGES="cmake pkg-config fftw libogg libvorbis libsndfile libsamplerate jack sdl stk portaudio node fltk"

brew install $PACKAGES
```

With `set -e`, it failed because brew returned a non-zero exit code for already installed packages. So we had to do:

```sh
#!/usr/bin/env bash

set -e

PACKAGES="cmake pkg-config fftw libogg libvorbis libsndfile libsamplerate jack sdl stk portaudio node fltk"

# removing already installed packages from the list
for p in $(brew list); do
	PACKAGES=${PACKAGES//$p/}
done;

brew install $PACKAGES
```

But it's ugly and buggy. E.g. we used to have `pkgconfig`, so the string replacement didn't work. It now works cause we replaced it by `pkg-config` as it is in `brew list` output.

So, I'd like an option like: `brew install --if-not-installed $PACKAGES` which won't return a non-zero exit code if `$PACKAGES` contains already installed packages.

What do you think about it ? I wish i could implement it myself, but I don't know ruby and I'm not even a brew user so probably not the best option. I'm sure someone knowing ruby and brew could do this really quickly as it doesn't seem hard.

**Comment by JCount** [comment]
The reason that you are getting a non-zero exit status from your original `brew install $PACKAGES`, is probably due to one or more of the formula already having a different version installed and linked.

A likely way to resolve this would be to add something like the following to your CI script:
```
brew update || brew update
brew upgrade
brew install $PACKAGES
```
in the place of the single line.

Another approach would be to look at [homebrew/bundle](https://github.com/Homebrew/homebrew-bundle).

**Comment by zapashcanon** [comment]
I did a quick test. Indeed, now it doesn't return a non-zero exit code but just display a warning. 

Unfortunately, it also make the whole process really much longer, without upgrade `3 min. 47`, but `8 min.` with it.

So, I'd still like to see this option added to avoid getting warnings and also to be able not to upgrade packages when it's not needed.

**Comment by JCount** [comment]
If you are using Travis, try removing/skipping the ones from here, or upgrading their version if they are outdated, instead of upgrading everything: https://docs.travis-ci.com/user/osx-ci-environment/#Compilers-and-Build-toolchain

**Comment by zapashcanon** [comment]
We would like to keep the complete list of packages so the script will be usable for the CI and for users too. So we can't just remove them.

Upgrading only the already installed packages will just lead to the same result we have now: an ugly and buggy script to filter already installed packages.

**Comment by bfontaine** [comment]
Have you seen [Homebrew Bundle](https://github.com/Homebrew/homebrew-bundle)?

**Comment by JCount** [comment]
So, since the primary issue you are running into is a result of `set -e`, could you set it after the `brew install` line? Failing that, in my mind, this seems to at least be a somewhat neater solution:
```
#!/usr/bin/env bash

set -e

PACKAGES="cmake pkg-config fftw libogg libvorbis libsndfile libsamplerate jack sdl stk portaudio node fltk"

brew install $PACKAGES && true
```
You could also use `brew upgrade $PACKAGES 2>/dev/null && true` if you wanted to suppress stderr.

**Comment by zapashcanon** [comment]
> Have you seen Homebrew Bundle?

I had a look at it. I'd rather not adding another tool in the CI just for this, plus, users would have to install it too to build from sources...

Moreover:

> If a dependency is already installed and there is an update available it will be upgraded.

We don't want to upgrade.

> could you set it after the brew install line?

I guess we could, but that doesn't seem a clean solution to me. We should be able to tell brew: install only if not already here, don't upgrade if already here.

> brew install $PACKAGES && true

You mean `|| true` ? But still, the above point is the same here.

So, if you don't want to write this feature, would you accept a PR ? If someone is pointing me to the relevant piece of code, I could try to write this feature.

**Comment by MikeMcQuaid** [comment]
> I had a look at it. I'd rather not adding another tool in the CI just for this, plus, users would have to install it too to build from sources...

It's not another tool, it's part of Homebrew. Just run `brew bundle`. That's our supported way of handling cases like this.

**Comment by lxn2** [comment]
+1. There are valid use cases to the proposed `--if-not-installed` flag. Creating a brewfile shouldn't have to be the only solution.

**Comment by MikeMcQuaid** [comment]
It's not really helpful to state that you're not willing to create a `Brewfile` or use `brew bundle` without elaborating on why that is the case.

**Comment by danielecook** [comment]
I am supplying a script to users in my group that installs a couple of dependencies. I want to be able to send them just the script via a curl command, not an additional `BrewFile`. I don't think a BrewFile should be required for these sorts of simple cases.

**Comment by bfontaine** [comment]
FWIW you can do this in a script without an additional file:
```bash
brew bundle --file=- <<-EOS
brew "formula1"
brew "formula2"
brew "formula3"
EOS
```

**Comment by MikeMcQuaid** [comment]
Yep, you can embed them into your script like @bfontaine points out.

> I don't think a BrewFile should be required for these sorts of simple cases.

To be clear: it's not, you can accomplish all this without `brew bundle` but you will need to write more or the logic yourself which seems to be what the complaints are in this issue. If you're asking for a feature so you can essentially mirror `brew bundle`s functionality without using it: sorry, we're not going to implement that.
