### ISSUE TITLE
Can't list casks

### ISSUE THREAD

**Issue by blogabe** [Homebrew/brew#2492]
# Please always follow these steps:
- [X] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

I believe this to be a brew issue rather than cask, but I can't `brew cask list`.  I'm only seeing this on one of my computers and not another.

Here's the full transcript including the requested steps:
```
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 1.1.12-38-g30582a5fb
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 30582a5fbd35843e183f1591cc8413309fa5e705
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 35eb0880b0b500384d3b9bfee82fbaaa0ba25651
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.4-x86_64
Xcode: 8.3.1
CLT: N/A
X11: 2.7.11 => /opt/X11
$ brew doctor
Your system is ready to brew.
$ brew cask list
Error: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'

Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/utils.rb:96:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:6:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:41:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:40:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:30:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:30:in `installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:63:in `list_installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by bfontaine** [comment]
What is the output of `brew cask doctor`?

**Comment by reitermarkus** [comment]
Do you have `HOMEBREW_DEVELOPER` set? Otherwise this should only be a warning: 

```
Error: Calling "cask :v1 => 'token'" is deprecated!
```

**Comment by blogabe** [comment]
Yes, HOMEBREW_DEVELOPER is set as I like to build directly from source.  Output from `brew cask doctor` also doesn't show any issues:
```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12-38-g30582a5fb
caskroom/homebrew-cask (git revision f3b38; last commit 2017-04-14)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3633 casks)
/usr/local/Homebrew/Library/Taps/blogabe/homebrew-xtg (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

Thank you.

**Comment by reitermarkus** [comment]
> HOMEBREW_DEVELOPER is set as I like to build directly from source.

I don't think `HOMEBREW_DEVELOPER` is necessary to build from source. Either pass `--build-from-source` or set `HOMEBREW_BUILD_FROM_SOURCE`.

**Comment by vitorgalvao** [comment]
This error is happening likely because you installed some casks when `cask :v1 => 'token'` was valid, and have never `reinstall`ed or `--force install`ed or `uninstall`ed them, and they’re being read from their `.metadata` directories.

To fix this *and* keep `HOMEBREW_DEVELOPER` on, you need to first turn `HOMEBREW_DEVELOPER` off then update/reinstall/force install all the casks (well, technically just the old ones) with something like

```bash
for cask in $(brew cask list); do
  brew cask reinstall "${cask}"
done
```

But some of them might need some further manual fixing. Then you can reactivate `HOMEBREW_DEVELOPER`. But as @reitermarkus mentioned, that should not be necessary for your case. In your position, I’d simply turn it off and turn on the option to build from source.

**Comment by blogabe** [comment]
Even with setting `HOMEBREW_DEVELOPER`, and for that matter `HOMEBREW_BUILD_FROM_SOURCE`, to '0', I still cannot `brew cask list`.

Same error message as above.

**Comment by blogabe** [comment]
BTW: I went through and uninstalled/reinstalled all Casks upon the big change however long ago from installing casks to `/opt` to homebrew's location.  I believe that was after v1, but may be wrong.

**Comment by dunn** [comment]
> Even with setting HOMEBREW_DEVELOPER, and for that matter HOMEBREW_BUILD_FROM_SOURCE, to '0'

They need to be completely unset; i.e., `unset HOMEBREW_DEVELOPER`.

**Comment by blogabe** [comment]
That did it.  Thank you.

Is there an easy way to find out with cask(s) I need to reinstall rather than going through and doing them all?

**Comment by reitermarkus** [comment]
> Is there an easy way to find out with cask(s) I need to reinstall rather than going through and doing them all?

If `brew cask list` is not showing any `Calling "cask :v1 => 'token'" is deprecated!` warnings anymore, you should be good.
