### ISSUE TITLE
Mac 10.12.4 Brew downgrades itself automatically to v.1.1.0 (no git repository) 

### ISSUE THREAD

**Issue by Hungry4Sec** [Homebrew/brew#2493]
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

**Brew Config output:** 

HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30582a5fbd35843e183f1591cc8413309fa5e705
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 35eb0880b0b500384d3b9bfee82fbaaa0ba25651
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: N/A
CLT: 8.3.0.0.1.1490382677
X11: N/A

**Brew Doctor output:**

Your system is ready to brew.

To help us debug your issue please explain:
- What you were trying to do (and why)
I was installing a few casks (chrome, spotify, google-drive) and then ran brew config just to check if I needed to update anything. Then I noticed that my Homebrew version downgraded from 1.1.12 to 1.1.0 (no git repository). 
- What happened (include command output)

**brew update** (2x) 
Already up-to-date.

**brew config**
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30582a5fbd35843e183f1591cc8413309fa5e705
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 35eb0880b0b500384d3b9bfee82fbaaa0ba25651
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: N/A
CLT: 8.3.0.0.1.1490382677
X11: N/A

**cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update**
HEAD is now at 30582a5 Merge pull request #2486 from reitermarkus/fix-audit
Already up-to-date.

**brew config**
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30582a5fbd35843e183f1591cc8413309fa5e705
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 35eb0880b0b500384d3b9bfee82fbaaa0ba25651
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: N/A
CLT: 8.3.0.0.1.1490382677
X11: N/A

- What you expected to happen
When I first installed homebrew "brew config" showed Homebrew version as 1.1.12. I'm not sure why the version now changed; but I'm also not sure if this is/will cause any problems 
- Step-by-step reproduction instructions (by running `brew` commands)

Please See above
Gist containing output of 
brew update -vd
brew doctor -vd
brew config
https://gist.github.com/Hungry4Sec/76376559abbe7296d63f9df8b42078d7

**Comment by MikeMcQuaid** [comment]
Can I see the output of your `git -C /usr/local/Homebrew tag --list --sort=-version:refname`?

**Comment by Hungry4Sec** [comment]
Hi Mike, thanks for looking into this. The output of the command is below: 

$ git -C /usr/local/Homebrew tag --list --sort=-version:refname
1.1.12
1.1.11
1.1.10
1.1.9
1.1.8
1.1.7
1.1.6
1.1.5
1.1.4
1.1.3
1.1.2
1.1.1
1.1.0
1.0.9
1.0.8
1.0.7
1.0.6
1.0.5
1.0.4
1.0.3
1.0.2
1.0.1
1.0.0
0.9.9
0.9.8
0.9.5
0.9.4
0.9.3
0.9.2
0.9.1
0.9
0.8.1
0.8
0.7.1
0.7
0.6
0.5
0.4
0.3
0.2
0.1

**Comment by MikeMcQuaid** [comment]
@Hungry4Sec How about `git -C "$(brew --repo)" describe --tags --dirty`?

**Comment by Hungry4Sec** [comment]
Hey Mike; with the recent upgrade to 1.1.13 the issue seems fixed (for now at least); but the output of the command you requested is below. Homebrew autoupdated so I can't reproduce the bug environment unfortunately. 

$ git -C "$(brew --repo)" describe --tags --dirty
1.1.13

**Comment by MikeMcQuaid** [comment]
Ok, cool, glad it's sorted.
