### ISSUE TITLE
-bash: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by jhuh3226** [Homebrew/brew#2500]
# Please always follow these steps:
- [ ] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I have ran `brew gist-logs <formula>` in the process of installing python and opencv (referring http://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/).
- What happened (include command output)
Commanded `brew gist-logs <formula>`, but there occurs error of `-bash: syntax error near unexpected token `newline'`
- Return for the `brew config`
HOMEBREW_VERSION: 1.1.12-3568-g46f6dc4c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 46f6dc4c93b96abd528c3a0a808a5ca5a795c7f3
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 068842d7a070f9db7b975a01c127dccaf5ca669b
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3.1
CLT: 8.3.0.0.1.1490382677
X11: N/A

- Return for the `brew doctor`
Your system is ready to brew.

- Step-by-step reproduction instructions (by running `brew` commands)
Example usage:
  brew search [TEXT|/REGEX/]
  brew (info|home|options) [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install -vd FORMULA

Developers:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]
  http://docs.brew.sh/Formula-Cookbook.html

Further help:
  man brew
  brew help [COMMAND]
  brew home

**Comment by MikeMcQuaid** [comment]
> Ran brew config and brew doctor and included their output with your issue?

Please do this.

**Comment by jhuh3226** [comment]
@MikeMcQuaid 
I updated the output of the brew config and brew doctor.

**Comment by MikeMcQuaid** [comment]
Did you run `brew gist-logs <formula>` or `brew gist-logs python` or `brew gist-logs opencv` or something else?

**Comment by MikeMcQuaid** [comment]
> Did you run brew gist-logs <formula> or brew gist-logs python or brew gist-logs opencv or something else?

Ping on this.
