### ISSUE TITLE
`brew help` does not list the very important `cleanup` command

### ISSUE THREAD

**Issue by xmnboy** [Homebrew/brew#2505]
# Proposed Featured

> Add `brew cleanup` command to help list.

Typing the `brew` and `brew help` commands results in no mention of the `brew cleanup` command, which is a very helpful command for removing old versions of installed packages and, especially, for cleaning up disk space!

Please add `brew cleanup` to the list of commands presented by the brew online help.

I am using what I believe is the most current version of brew:
~~~~~bash
$ brew --version
Homebrew 1.1.13-19-g55c02ae774
Homebrew/homebrew-core (git revision 5b73; last commit 2017-04-18)
~~~~~

**Comment by MikeMcQuaid** [comment]
Thanks for the suggestion. We won't change this right now but may in future. `man brew` does show this FWIW.

**Comment by xmnboy** [comment]
Thanks, no rush.
