### ISSUE TITLE
fatal error: 'libelf.h' file not found #include <libelf.h>

### ISSUE THREAD

**Issue by wenhuizhang** [Homebrew/brew#2506]
```
wenhui-2:sim WenhuiZhang$ brew link gcc@4.8
Linking /usr/local/Cellar/gcc@4.8/4.8.4... 25 symlinks created
wenhui-2:sim WenhuiZhang$ brew install --HEAD osx-cross/avr/simavr
==> Installing simavr from osx-cross/avr
==> Cloning https://github.com/buserror/simavr.git
Updating /Users/WenhuiZhang/Library/Caches/Homebrew/simavr--git
==> Checking out branch master
==> make install DESTDIR=/usr/local/Cellar/simavr/HEAD-1ae1912 HOMEBREW_PREFIX=/usr/local RELEASE=1
Last 15 lines from /Users/WenhuiZhang/Library/Logs/Homebrew/simavr/01.make:
/Applications/Xcode.app/Contents/Developer/usr/bin/make libsimavr run_avr
CC sim/sim_cmds.c
CC sim/sim_cycle_timers.c
CC sim/sim_avr.c
sim/sim_elf.c:32:10: fatal error: 'libelf.h' file not found
#include <libelf.h>
         ^
1 error generated.
make[2]: *** [obj-x86_64-apple-darwin16.4.0/sim_elf.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CC sim/sim_hex.c
CC sim/sim_core.c
CC sim/sim_gdb.c
make[1]: *** [all] Error 2
make: *** [install] Error 2
```

# Please always follow these steps:
- [ ] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

**Please note we may immediately close your issue without comment if you do not fill out the issue template and provide ALL the requested information.**

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it and alternatives considered.
Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
> osx-cross/avr/simavr

report this to that tap.

**Comment by wenhuizhang** [comment]
Got it, thanks @MikeMcQuaid
