### ISSUE TITLE
gpg-zip missing from GnuPG formula

### ISSUE THREAD

**Issue by opteryx** [Homebrew/brew#2507]
gpg-zip used to be included with the GnuPG formula, but appears to have been dropped when the package was upgraded to 2.1. Is it possible to have include it again?

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by DomT4** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/commit/1280015e4351a384946ec858e2a8b4f6f368d259 FYI.
