### ISSUE TITLE
Installation of Homebrew fails on MacOS Sierra 10.12.4

### ISSUE THREAD

**Issue by ivan-fedorov** [Homebrew/brew#2518]
Hello,
I have to install Homebrew on new mac with MacOS Sierra on board. Latest Xcode and Command line tools are installed and mac has access to GitHub but nevertheless when I run installation command I receive error message "fatal: https://github.com/Homebrew/brew/info/refs not valid: is this a git repository".
Details:
**OS**:
MacOS Sierra version 10.12.4
**Xcode**: 
Version 8.3.2 (8E2002)
**Command line tools installed**: 
xcode-select -p returns /Applications/Xcode.app/Contents/Developer
**Git**: 
git version 2.11.0 (Apple Git-81)
**Installation command**: 
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
**Access rights to /usr/local**
I'am the owner of folder /usr/local/
**Output**: 
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
fatal: https://github.com/Homebrew/brew/info/refs not valid: is this a git repository?
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force --depth=1

I've tried to install Homebrew on 2 mac devices with MacOS Sierra and installation has failed on both devices but still was successful on other mac machines with previous MacOS version.

Could you please help me resolve this issue? Thank you!

**Comment by findsaumyahere** [comment]
hi did you get the solution?
