### ISSUE TITLE
`HOMEBREW_EDITOR` does not accept program with arguments

### ISSUE THREAD

**Issue by randy3k** [Homebrew/brew#2533]
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-sxecific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

I have my `HOMEBREW_EDITOR` set as `subl -w`, but it seems that the recent update to  [`which_editor`](https://github.com/Homebrew/brew/commit/69c7a20896813aefa519aaee7b75552731cd672a) breaks  this usage.

**Comment by MikeMcQuaid** [comment]
> Ran brew config and brew doctor and included their output with your issue?

Please do this in future, thanks.
