### ISSUE TITLE
brew update doesn't completely migrate mysql55 to mysql@5.5

### ISSUE THREAD

**Issue by schavery** [Homebrew/brew#2542]
I ran `brew update` and some formulas were migrated from using the version number in the title of the formula to using the new style of using package name + @ + version number. Here's the relevant output.

> ==> Migrating mysql55 to mysql@5.5
> ==> Unlinking mysql55
> ==> Unlinking mysql@5.5
> ==> Moving mysql55 children
> ==> Linking mysql@5.5

After restarting, I had two issues. One was that the plist file for mysql55 in my ~/Library/LaunchAgents file was now empty. The link was still present though:

> homebrew.mxcl.mysql55.plist -> /usr/local/opt/mysql55/homebrew.mxcl.mysql55.plist

Once I fixed this by running `brew services start mysql@5.5`, none of my databases were present. I had to move them from my /usr/local/var/mysql55 directory to the newly created /usr/local/var/mysql directory.

Expected behavior:
- plist file link is changed to the correct path
- database files are correctly migrated

**Comment by MikeMcQuaid** [comment]
Unfortunately `mysql@5.5` wasn't consistent with the other MySQL versions so we fixed that when migrating. `brew services` requires a restart on migration and we intentionally don't integrate it with `brew update`. `brew bundle` can do this, however.

As these migrations from homebrew/versions have now ceased and we're not getting widespread reports this isn't high enough priority to warrant a fix on our end yet (and we'll reopen if that changes). Thanks for the report regardless, though.
