### ISSUE TITLE
installing new version is non-intuitive

### ISSUE THREAD

**Issue by rdp** [Homebrew/brew#2543]
- [x ] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [ x] Ran `brew update` and retried your prior step?

To help us debug your issue please explain:
- What you were trying to do (and why)

Upgrade "crystal-lang"

- What happened (include command output)

```
$ brew install crystal-lang
Error: crystal-lang-0.21.1_1 already installed
To install this version, first `brew unlink crystal-lang`
```

- What you expected to happen

I expected it to be able to upgrade.  Or at least have an intuitive error message, the current one makes it looks like it's trying to re-install 0.21.1_1 when in reality, it's trying to install 0.22.0

I suggest you change it to "install this version" to "install version X" at the least.  At the best, it would either automatically unlink (does install imply upgrade? it does to me but in this case, it appears to be attempting an upgrade...) or provide a prompt.

Cheers!

**Comment by chdiza** [comment]
The correct command to upgrade `crystal-lang` is `brew upgrade crystal-lang`, not `brew install crystal-lang`.  The latter fails because, as the error message says, `crystal-lang` is already installed.

**Comment by rdp** [comment]
a more user friendly error message might be helpful...

**Comment by ilovezfs** [comment]
The purpose of this message is to instruct you how to install devel when stable is already installed, or install stable when devel is already installed, etc.

So arguably it is a bug for the message to be triggered when the user is attempting install the same version as is already installed (in which case reinstall is more appropriate than install), or a new version of the same spec (in which case upgrade is more appropriate than install). That said, it's not lying. `unlink` and then `install` will work.

**Comment by rdp** [comment]
I just used this and it worked great, thanks to all involved (again).

**Comment by MikeMcQuaid** [comment]
Thanks for the kind words, @rdp! They are genuinely motivating ❤️
