### ISSUE TITLE
Error: undefined method `search_tap' for Homebrew:Module

### ISSUE THREAD

**Issue by thecardkid** [Homebrew/brew#2544]
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

I was trying to run `brew audit --new-formula` on my formula, but it infinitely printed this error. Looks like an issue with the source code itself, so to be sure I tried running `brew audit --strict --online cmatrix` (a different formula), and it also had this error. The entire stack trace is here:

```
Error: undefined method `search_tap' for Homebrew:Module
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/compat/global.rb:9:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:374:in `block (2 levels) in audit_formula_name'
```
I'm running Yosemite 10.10.5. `brew doctor` outputs:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Xcode (6.2) is outdated.
Please update to Xcode 7.2.1 (or delete it).
Xcode can be updated from the App Store.
```

and `brew config`:

```
HOMEBREW_VERSION: 1.1.13-113-g36a387da26
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 36a387da26f56f49fb9153c652127fce76225f3c
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7fc329fad1b6c2ea39f4b9b22e05d2f4e5d7efd2
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 6.0 build 600
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_101, 1.7.0_79, 1.6.0_65-b14-466.1
macOS: 10.10.5-x86_64
Xcode: 6.2
CLT: 7.2.0.0.1.1447826929
X11: N/A
```
Please help. Thanks!

Edit: Just checked on my friend's computer whose Brew version was `1.1.13` and `brew audit` ran fine, then I did a `brew update` and it broke too.

**Comment by joshuata** [comment]
This looks like a consequence of #2540. It also appears on the Jenkins bots trying to merge new formulas.

**Comment by thecardkid** [comment]
@joshuata Do you know if there's a fix coming? Should I go ahead and open a PR for my formula anyway?

**Comment by joshuata** [comment]
I don't know. I'm in the same spot as you. I am not familiar enough with Homebrew internals or Ruby to write a fix. Maybe the PR author @MikeMcQuaid can help out.

It looks like the problem is that the [audit script on line 374](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L374) needs to be updated with the new method. It expects there to be a method named `search_taps(regex_or_string)`, but it was removed in the pull request I mentioned above.
