### ISSUE TITLE
Brew migration message of limited help.

### ISSUE THREAD

**Issue by cenkentimist** [Homebrew/brew#2550]
I had an issue with brew. This wasn't all that hard to resolve, but it seems like minor tweaks could make things more user(idiot) friendly. 

The info message:
```
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
```

Is cryptic. As someone who is unfamiliar with brew internals this only let me know the formula I was looking for was in caskroom. It did not explain to me what migration was, why it happens, and it lead me _away_ from the solution to my problem which turned out to be `install caskroom/cask/<formula>`

specifics:
I encountered this message when I did `brew search kdiff3` I'm not sure why the result wasn't caskroom/cask/kdiff3 to begin with
I then tried the following stupid things before figuring out the right command.
- `brew install caskroom/kdiff3`
- `brew tap caskroom/cask`
- `brew install kdiff3`
- `brew tap caskroom/kdiff3`
- `brew tap caskroom/cask kdiff3`
- `brew install caskroom/cask kdiff3`
- `brew install caskroom/cask/kdiff3` (this one works)

### requests:
- better message when brew encounters the 'migration situation'
- some explain or point to an explanation of migration (it's clearly related to moving files I'm just curious as to the various reasons why formulas are moved)

**Comment by MikeMcQuaid** [comment]
Given that you did figure this out I don't think we need to change anything here until we get a bunch of people who weren't able to. No "better message" isn't obvious from this report. Thanks anyway!
