### ISSUE TITLE
Audit can fail inelegantly.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#2551]
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

This is probably by design, but it's quite annoying, and maybe someone here can think of a better way of tweaking it than I can, which is to basically port the `log` command to be more friendly to being called inside Ruby.

Essentially if you forget to pass `--new-formula` whilst auditing a formula with no prior history `audit` erupts unhelpfully:
```
Error: undefined method `[]' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:752:in `block in audit_revision_and_version_scheme'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:751:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:751:in `audit_revision_and_version_scheme'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1239:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1232:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1232:in `audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:82:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:78:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
```
Feel free to close if it's something that only bothers me 😄.

**Comment by ilovezfs** [comment]
CC @MikeMcQuaid here it is again!
