### ISSUE TITLE
brew cask: provide option get verbose output of /usr/sbin/installer

### ISSUE THREAD

**Issue by volker-fr** [Homebrew/brew#2561]
# Propose of feature

## Background
If you run `brew cask install --verbose --debug <package>` of a `pkg` you can't receive detailed messages from the output of `/usr/sbin/installer`.

An example where this would be helpful is if you installed `mactex` while there isn't sufficient free disk. In this case the command output of `/usr/sbin/installer [...] -verboseR` not show the root cause of the installation issue error.  If you use `/usr/sbin/installer [...] -verboseR -dumplog` the root cause can be easily identified.

## Possible solution
The easiest solution might be adding and adding the following line after https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb#L51 This is not tested, hence there is no merge request.

     args << "-dumplog" if CLI.debug?

**Comment by reitermarkus** [comment]
> This is not tested, hence there is no merge request.

Could you send one? Thanks!

**Comment by volker-fr** [comment]
Wow. This policy about closing tickets will stop me providing any bugs to homebrew in the future.

**Comment by bfontaine** [comment]
@volker-fr We keep these kind of issues open only if someone’s planning to work on it. Proposing a feature should be done through a pull-request; even if it’s not complete it’s easier to provide feedback on actual code.

**Comment by MikeMcQuaid** [comment]
@volker-fr That's fine with us, thanks.
