### ISSUE TITLE
Use clang 4.0 for openmp instead of gcc-6

### ISSUE THREAD

**Issue by bhaskarvk** [Homebrew/brew#2564]
By default homebrew uses Apple's clang which does not support OpenMP.

However, gcc-6 (available via gcc formula) and clang 4.0 (available via llvm formula) both support OpenMP via the `-fopenmp` flag. But when I try to brew any formula with `--with-openmp` flags. e.g. `fftw` or `openblas`, homebrew defaults to using `gcc-6` and there is no way to specify to use llvm's clang compiler (the one from llvm formula not Apple's).

It would be ideal to be able to use llvm's clang for OpenMP support, as gcc uses `libstdc++`, and clang uses `libc++`, and I would like all my stuff complied against `libc++`.

I tried passing `--cc=clang` or `--cc=llvm_clang`, both no go.

This could go a long way in being able to build R and related libs properly with OpenMP support, and yet be compatible with libc++.

**Comment by MikeMcQuaid** [comment]
Please fill out the issue template as requested. We don't ask everyone to fill it out for no reason.

> both no go.

Please elaborate a lot more on what "no go" means.

**Comment by bhaskarvk** [comment]
Oops sorry about that. Infact I found my answer in #1130. Though reading the messages after the merge I am not sure if I need to `brew link --force llvm` or not.
