### ISSUE TITLE
New formula - executable file becomes non-executable in Cellar

### ISSUE THREAD

**Issue by kevinjalbert** [Homebrew/brew#2567]
# Please always follow these steps:
- [ ] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

-----

[Gist of longer files -- `brew doctor` | `brew config` | `brew install --verbose --debug adr-tools`](https://gist.github.com/kevinjalbert/719517d3e21467bc692ceae78374f5e1)

I am looking at making a new formula for [adr-tools](https://github.com/npryce/adr-tools). I noticed that there was an attempt [a while back](https://github.com/Homebrew/homebrew-core/pull/3947), although there was issues with the configuration that have since been solved.

I decided to try and make a new formula with the new updated version of `adr-tools`. I mostly borrowed stuff from the old attempt. My initial attempt looks like the following:

```ruby
class AdrTools < Formula
  desc "CLI tool for working with Architecture Decision Records."
  homepage "https://github.com/npryce/adr-tools"
  url "https://github.com/npryce/adr-tools/archive/2.1.0.tar.gz"
  sha256 "1ef028cfeaa1b262a5c62845aa8965be169705370983f9ff73b17ec77bf75f70"

  def install
    # Override adr-config with custom config to point to homebrew bin and prefix dirs
    system "echo 'echo adr_bin_dir=\"#{bin}\"' > src/adr-config"
    system "echo 'echo adr_template_dir=\"#{prefix}\"' >> src/adr-config"

    prefix.install Dir["src/*.md"] # Places the base templates in `prefix`
    bin.install Dir["src/*"]       # Copies the rest of the commands to `prefix/bin`
  end

  test do
    assert_match(/Run 'adr help COMMAND' for help on a specific command./,
                 pipe_output("#{bin}/adr help"))
  end
end
```

So everything install fine with `brew install --verbose --debug adr-tools` although I see `Fixing /usr/local/Cellar/adr-tools/2.1.0/bin/adr-config permissions from 755 to 444` in the output. This `adr-config` file needs to be an executable file for everything to work. I've even went and retried the whole thing without my customizations in the formula to override the old `adr-config` and I still see the same output.

I've looked at the file's permissions from the release's tar, and they are `755` with execution set. I've looked at the permissions after extraction and they still match.

I decided to look at the file permissions in the Cellar for this new formula:

```
❯ ls -la /usr/local/Cellar/adr-tools/2.1.0/bin/
total 144
drwxr-xr-x  20 jalbert  admin   680 29 Apr 21:49 .
drwxr-xr-x   9 jalbert  admin   306 29 Apr 21:49 ..
-r-xr-xr-x   1 jalbert  admin   614 11 Mar 20:01 _adr_add_link
-r-xr-xr-x   1 jalbert  admin   180 11 Mar 20:01 _adr_commands
-r-xr-xr-x   1 jalbert  admin   121 11 Mar 20:01 _adr_dir
-r-xr-xr-x   1 jalbert  admin   101 11 Mar 20:01 _adr_file
-r-xr-xr-x   1 jalbert  admin  1552 11 Mar 20:01 _adr_generate_graph
-r-xr-xr-x   1 jalbert  admin   971 11 Mar 20:01 _adr_generate_toc
-r-xr-xr-x   1 jalbert  admin   146 11 Mar 20:01 _adr_links
-r-xr-xr-x   1 jalbert  admin   539 11 Mar 20:01 _adr_remove_status
-r-xr-xr-x   1 jalbert  admin   108 11 Mar 20:01 _adr_title
-r-xr-xr-x   1 jalbert  admin   163 11 Mar 20:01 adr
-r--r--r--   1 jalbert  admin   136 11 Mar 20:01 adr-config
-r-xr-xr-x   1 jalbert  admin   334 11 Mar 20:01 adr-generate
-r-xr-xr-x   1 jalbert  admin   934 11 Mar 20:01 adr-help
-r-xr-xr-x   1 jalbert  admin   610 11 Mar 20:01 adr-init
-r-xr-xr-x   1 jalbert  admin   711 11 Mar 20:01 adr-link
-r-xr-xr-x   1 jalbert  admin   314 11 Mar 20:01 adr-list
-r-xr-xr-x   1 jalbert  admin  3590 11 Mar 20:01 adr-new
-r-xr-xr-x   1 jalbert  admin   337 11 Mar 20:01 adr-upgrade-repository
``` 

So this explains why the file permissions on the cleanup go to `444`, the permissions here for this one file is non-executable. I have no idea why this is the case. I've looked around an unoffical-formula and noticed they had [the exact same issue](https://github.com/olleolleolle/homebrew-adr-tools/pull/5#issuecomment-282000145). This leads me to believe that something in brew is changing the permissions for this file.

> In the tar file, a load of files have 0775. After installing via brew, they have 0555, and the adr-config file ends up at 0444.

Any help would be appreciated.

**Comment by MikeMcQuaid** [comment]
If you want a text file to stay executable it needs to have a shebang i.e. `#!/bin/bash`. If you try to run your script as-is it will not actually be executable.

**Comment by kevinjalbert** [comment]
@MikeMcQuaid thank! That was exactly the problem :)
