### ISSUE TITLE
macOS 10.12.4 Home Brew Downgrades Itself to 1.1.0 (no git repository) 

### ISSUE THREAD

**Issue by Hungry4Sec** [Homebrew/brew#2569]
Please see [issue #2493](https://github.com/Homebrew/brew/issues/2493) as this seems to be a similar problem which occurred. 

# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Ran brew upgrade and then brew update twice. Then ran brew config to see what version of git I had installed. Got the same message as mentioned in the issue above; for Homebrew version it state 1.1.0 (no git respository) 
- What happened (include command output 
_Ran the following code_ 
└[~]> brew config
zsh: correct 'config' to '.config' [nyae]? n
HOMEBREW_VERSION: 1.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 46f6dc4c93b96abd528c3a0a808a5ca5a795c7f3
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab7ae551d0cb93dcfa62644232f7f21ace01b7cf
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: N/A

- What you expected to happen
For the Homebrew version to stay current.  

- Step-by-step reproduction instructions (by running `brew` commands)

Reproduced all steps and the output is in the following gist:
Reproduced the steps as well as the steps Mike asked in #2493 :

git -C "$(brew --repo)" describe --tags --dirty
git -C /usr/local/Homebrew tag --list --sort=-version:refname

https://gist.github.com/Hungry4Sec/f50ee5c6a772c7d2ffcde758eefd390f

**Comment by MikeMcQuaid** [comment]
What does `HOMEBREW_ENV_FILTERING=1 brew --version` output?

**Comment by MikeMcQuaid** [comment]
Also, just so you don't worry: it's not downgrading, it just can't find the Git repository for the version number.

**Comment by Hungry4Sec** [comment]
Thanks for helping out and for the information, Mike!

I ran the command you suggested, output below:

`└[~]> HOMEBREW_ENV_FILTERING=1 brew --version`
`Homebrew 1.1.13`
`Homebrew/homebrew-core (git revision ab7a; last commit 2017-04-30)`

Brew config now reports the correct version as well: 
└[~]> brew config
zsh: correct 'config' to '.config' [nyae]? n
HOMEBREW_VERSION: 1.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 46f6dc4c93b96abd528c3a0a808a5ca5a795c7f3
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab7ae551d0cb93dcfa62644232f7f21ace01b7cf
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: N/A
┌

seems like it's an inconvenience/annoyance more than anything, but any idea what might be causing it since it came back? 

Thanks again for your help.

**Comment by MikeMcQuaid** [comment]
It will be a combination of the directory you're currently in, your Git configuration either globally or in the directory you're in and/or your environment variables.

**Comment by MikeMcQuaid** [comment]
That said: we would like to fix it so this works regardless so if you can narrow down which of those it is it'll help with a fix.

**Comment by Hungry4Sec** [comment]
I usually run the command from my home directory (~/). 

As for git, I have a global git config that uses my name and e-mail; should there by other information in it as well?

**Comment by MikeMcQuaid** [comment]
Can you try to run `HOMEBREW_ENV_FILTERING=1 brew --version` and `HOMEBREW_ENV_FILTERING=1 brew config` and `brew --version` and `brew config` from your home directory and a few other directories and compare the results?

**Comment by Hungry4Sec** [comment]
Hey Mike; looks like the updated formula fixed it haha, but here's a gist of what you requested. Ran the two formula in my home, tmp, and var since that's usually where I'm working from.

https://gist.github.com/Hungry4Sec/a6170937573ef16134bd41ceba612a5f

**Comment by MikeMcQuaid** [comment]
Ok, glad it's working. Post here if you experience issues again in future.
