### ISSUE TITLE
Upgrading on El Capitan

### ISSUE THREAD

**Issue by runeimp** [Homebrew/brew#2570]
Now that El Capitan is no longer a target for Xcode certain packages such as LLVM and Swift complain about not having Xcode 8.3+ installed. Upgrading those particular items (and probably a few others) is now not an option without upgrading to Sierra. That is fine but when I hit `brew upgrade` it always errors out on one of those packages and I end up having to upgrade all the packages that had an update individually.

I would greatly appreciate a switch, environment variable or some other option to have `brew upgrade` ignore those particular errors and possibly just give a warning about the situation. Please consider this feature request from a humble user of your excellent package manager for OS X/macOS.  👼

**Comment by ilovezfs** [comment]
You can use `brew pin` to pin the relevant formulae at the last compatible version, and then `brew upgrade` will skip them.

**Comment by runeimp** [comment]
Damn, totally overlooked the "see pin, unpin" in `brew help upgrade`. Thank you for the info!  👍
