### ISSUE TITLE
Third-party tap maintainership is loosely documented

### ISSUE THREAD

**Issue by ticky** [Homebrew/brew#2572]
This is more or less three problems;
* `brew tap-new` isn’t mentioned in documentation anywhere (I learned about it today in [the 1.2.0 blog post](https://brew.sh/2017/05/01/homebrew-1.2.0/)!)
* the expected method for testing taps (seemingly [encapsulated in `brew tap-new`](https://github.com/MikeMcQuaid/brew/blob/master/Library/Homebrew/dev-cmd/tap-new.rb#L47)) isn’t really described
* methods of distributing bottles aren’t documented (or, it seems, supported, given even bintray paths are partly hard-coded in `test-bot`!) for third-party repositories

I plan to make some PRs to improve the documentation situation, but functionality-wise, I’d like some input on what’s desired by Homebrew maintainers.

To that end, my questions are;
1. Is `test-bot` intended to be used by third parties?
   1. Is the use of `test-bot` to create binary packages for third-party taps intended?
   2. Would PRs to allow `test-bot` to create PRs on third-party repositories be accepted?
2. Should `tap-new` have a companion command for checking/updating a tap’s Travis configuration against the currently-ordaned template?
   1. Should `test-bot` be checking the travis configuration within taps?

**Comment by vitorgalvao** [comment]
> `brew tap-new` isn’t mentioned in documentation anywhere

Small note on this. It is mention in the `man` page, which should be considered the canonical most important source of information.

**Comment by ticky** [comment]
Okay, correction then, it isn’t mentioned in any of the _tap-related, online_ documentation.

**Comment by MikeMcQuaid** [comment]
Hey @ticky, thanks for the issue, I agree that the code has developed past the documentation here. Let's chat about what's best and then you or I (or someone else) can start updating them.

> brew tap-new isn’t mentioned in documentation anywhere (I learned about it today in the 1.2.0 blog post!)

Yeh, it should be at the very least mentioned in https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap


> the expected method for testing taps (seemingly encapsulated in brew tap-new) isn’t really described

Good point. I figured it was self-explantory but it's not. It's basically: run that command to generate a README/Travis CI configuration for your tap, push your tap to GitHub, enable Travis CI on that repo. After that all PR and branch builds will use `brew test-bot` to autodetect changes and build them accordingly.


> methods of distributing bottles aren’t documented (or, it seems, supported, given even bintray paths are partly hard-coded in test-bot!) for third-party repositories

We do support distributing bottles but we don't have an answer as to how to do so yet. We specifically negotiated free access to Bintray as a project but I'm not sure if this is something any project can do on Bintray or if it requires individual negotiation e.g. per-tap. As a result, the bottles being built is no problem it's just upload and distribution that's harder. The ideal case would be we can infer where to upload to Bintray purely based on your tap name and then you just need to set the relevant Bintray keys.

> Is test-bot intended to be used by third parties?

Yep. It's used by a few third-party taps and Linuxbrew and seems to be working pretty well for everyone.

> Is the use of test-bot to create binary packages for third-party taps intended?

Yes, just the upload/distribution story isn't really there yet.

> Would PRs to allow test-bot to create PRs on third-party repositories be accepted?

They should work pretty much as-is so: yes.

> Should tap-new have a companion command for checking/updating a tap’s Travis configuration against the currently-ordaned template?

I think it could perhaps have an argument which overwrites the existing configuration or dumps it to stdout.

> Should test-bot be checking the travis configuration within taps?

I don't think so or at least not implicitly. It will currently barf if misconfigured in some ways. We could make that barfing and checking stricter for Travis CI taps.

**Comment by scpeters** [comment]
I'll just chime in as maintainer of the `osrf/simulation` tap. We use `brew test-bot` to build bottles on a few dedicated mac mini's in our office, and we upload them to an s3 bucket. I don't know exactly how upstream does things, but I'm pretty sure we do a few things differently for better or worse:

* we try to submit all our internal pull requests from a special github account @osrfbuild so that our CI machines can push new bottle hashes to the open pull requests. we then squash and merge instead of using `brew pull`
* we have scripts that use sed trickery to update the bottle hashes. those scripts don't support bottle revisions, so I just bump formula revisions if something gets messed up and bottle revisions start incrementing

One pain point is finding out that we need to rebuild our bottles when a dependency like `boost` or `protobuf` is updated and our bottles break. `homebrew-core` has too much traffic for me to subscribe; though I would love to be notified about updates of specific formulae so I could be ready to build new bottles and minimize downtime, but I don't think github supports that. I could make a gmail filter I guess.

**Comment by ticky** [comment]
Hi @MikeMcQuaid, thanks for the quick response! Just wanted to comment to say I will follow up on this properly soon. :smile:

**Comment by MikeMcQuaid** [comment]
> We specifically negotiated free access to Bintray as a project but I'm not sure if this is something any project can do on Bintray or if it requires individual negotiation e.g. per-tap. As a result, the bottles being built is no problem it's just upload and distribution that's harder. The ideal case would be we can infer where to upload to Bintray purely based on your tap name and then you just need to set the relevant Bintray keys.

I investigated this a bit and if you're using Bintray for OSS you can get an account for free: https://bintray.com/signup/oss. It seems standardising in our tooling and docs around this assumption is a good idea.
