### ISSUE TITLE
Symlinks from old formulae name are persist after installing formulae with new name

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#2573]
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew install dbus
$ brew doctor 
<reports that I need to link dbus>
$ brew link dbus 
<fails to overwrite because of conflict with d-bus formulae (old name)>
$ brew uninstall d-bus
<uninstalls dbus, while keeping d-bus untouched>
```

**Comment by ilovezfs** [comment]
Your core tap is outdated according to https://github.com/Homebrew/homebrew-core/issues/13152 so not sure what we can infer here especially since all the information in the issue template isn't filled out.

**Comment by yurikoles** [comment]
@ilovezfs I'm unable to reproduce it
