### ISSUE TITLE
Please provide way to install removed formulae with one-liner

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#2575]
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?

> To help us debug your issue please explain:
> - What you were trying to do (and why)

Install gptfdisk

> - What happened (include command output)

```
$ brew install gptfdisk
Updating Homebrew...
Error: No available formula with the name "gptfdisk" 
==> Searching for a previously deleted formula...
gptfdisk was deleted from homebrew/core in commit 850c04b77f:
  gptfdisk: boneyard
  See Homebrew/homebrew#46378.
  Closes Homebrew/homebrew#46398.
  Signed-off-by: Alex Dunn <dunn.alex@gmail.com>

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 850c04b77f^:Formula/gptfdisk.rb

If you still use this formula consider creating your own tap:
  http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html
```

> - What you expected to happen

Easy installation instructions, e.g. one-liner

> - Step-by-step reproduction instructions (by running `brew` commands)

`brew install <any-deleted-formula>`

**Comment by vitorgalvao** [comment]
I think you’re misunderstanding the message. It’s not suggesting you install the formula from the old commit, it’s suggesting that if you want to install it, you should consider maintaining it on your own tap and tells you how to look for the old formula *as a basis to making your own*.

There are many reasons to removing a formula from the main tap, including it being completely broken. I that case, suggesting you install it from an old commit is a recipe for disaster and bug reports that will not be addressed.

**Comment by MikeMcQuaid** [comment]
@vitorgalvao is correct. It's intentional that you can't install this with a one-liner.

**Comment by yurikoles** [comment]
@vitorgalvao @MikeMcQuaid thank you for figuring it out 👍
