### ISSUE TITLE
brew update says "Already up-to-date.", but brew doctor says "Your Homebrew is outdated."

### ISSUE THREAD

**Issue by halloleo** [Homebrew/brew#2583]
I want to update my  brew system, so I ran

    brew update --verbose

and I get:

    $ brew update --verbose
    
    
    
    
    
    
    Already up-to-date.
    $ 

(These are 7 empty lines followed by "Already up-to-date.") On the other hand `brew doctor` gives:

    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!
    
    Warning: You are using a pre-release version of Xcode.
    You may encounter build failures or other breakages.
    Please create pull-requests instead of filing issues.
    
    Warning: You have unlinked kegs in your Cellar
    Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
    those kegs to fail to run properly once built. Run `brew link` on these:
        gcc
        ghostscript
        lesstif
        lua
        markdown
    
    Warning: Broken symlinks were found. Remove them with `brew prune`:
        /usr/local/share/doc/ghc
    
    Warning: Your Homebrew is outdated.
    You haven't updated for at least 24 hours. This is a long time in brewland!
    To update Homebrew, run `brew update`.

*What can I do to get brew to update?*

ps: Here for completeness the output from `brew config`:

    HOMEBREW_VERSION: 0.9.9
    ORIGIN: https://github.com/Homebrew/brew.git
    HEAD: 06fe347de97975dc01e726f87bf07a56a6fb713e
    Last commit: 9 months ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: b163b0d8271500557664422d6fdc3054d0ff7d31
    Core tap last commit: 9 months ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: quad-core 64-bit broadwell
    Homebrew Ruby: 2.0.0-p648
    Clang: 8.0 build 800
    Git: 2.9.2 => /usr/local/bin/git
    Perl: /usr/bin/perl
    Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
    Ruby: /usr/local/opt/ruby/bin/ruby => /usr/local/Cellar/ruby/2.3.1/bin/ruby
    Java: N/A
    OS X: 10.11.6-x86_64
    Xcode: 8.2.1
    CLT: 8.2.0.0.1.1480973914
    X11: 2.7.11 => /opt/X11

**Comment by MikeMcQuaid** [comment]
Looks like you hit the update bug. This should fix it for you: https://github.com/Homebrew/brew#update-bug

**Comment by halloleo** [comment]
Thanks heaps for the pointer, MikeMcQuaid! It did the job. Now I'm on 1.2.0 - and happy! :-)

**Comment by MikeMcQuaid** [comment]
Glad it's working!
