### ISSUE TITLE
Listing formula versions 

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [Homebrew/brew#2588]
From what I can tell `homebrew/versions` was recently deprecated, and `versions` are now available on `homebrew/core` with the new `formula@version` format. This allows one to do e.g. `brew install postgresql@9.5`.

Of course this doesn't work for any arbitrary versions. For example, `brew install tmux@2.3` returns: `"No available formula with the name tmux@2.3`.

Using `homebrew/versions`, one could run `brew versions <formula>` to see available versions.  What's the right way to list available versions today?

**Comment by scpeters** [comment]
I think `brew search` is a decent option:

~~~
$ brew search postgresql
postgresql                 postgresql@9.4             postgresql@9.5
~~~

**Comment by MikeMcQuaid** [comment]
Yep, @scpeters approach is best. `brew search` without argument also links then all.

> Using homebrew/versions, one could run brew versions <formula> to see available versions. What's the right way to list available versions today?

`brew versions` wasn't part of Homebrew/versions and it didn't provide versions that worked consistently or could be fixed if there were any problems.
