### ISSUE TITLE
[cask] Hbc::DSL::Appcast doesn't check HTTP status codes

### ISSUE THREAD

**Issue by 13k** [Homebrew/brew#2592]
[This curl invocation](https://github.com/Homebrew/brew/blob/93d4fdf938779a5cccb4aabed7d82cb533f9506e/Library/Homebrew/cask/lib/hbc/dsl/appcast.rb#L15) can silently fail if the final response is not a successful status code.

Discovered this by recently [trying to create a cask](https://github.com/caskroom/homebrew-cask/pull/33441#issuecomment-299487969) and using appcast.

From that cask example, you can see that the appcast URL (`http://changelog.sodaplayer.com`) inadvertently returns a 404 response when improperly requested (it requires a `Accept: text/html` HTTP header. This is actually a web server idiosyncrasy specific to that app), but `curl` does not exit with an error, it exits with success (`curl` will only exit with an error for non-successful HTTP statuses if using the `--fail`/`-f` flag).

Not only the HTTP status is ignored, but also appcast checkpoints are wrongly generated based on, possibly, error messages in the response body, or even empty responses for that matter. Once this happens (request always returns non-200 responses with the same error message), all checkpoints will be the same for every check.

On the other hand, `Hbc::Audit`, [implements this check correctly](https://github.com/Homebrew/brew/blob/93d4fdf938779a5cccb4aabed7d82cb533f9506e/Library/Homebrew/cask/lib/hbc/audit.rb#L123-L132).

**Comment by reitermarkus** [comment]
@13k, would be great if you could submit a PR for this, since you already seem to know what needs to be fixed. Wanna give it a go?

**Comment by 13k** [comment]
@reitermarkus #2712
