### ISSUE TITLE
brew: line 5: cd: /usr/local/Homebrew/bin: No such file or directory

### ISSUE THREAD

**Issue by akaij** [Homebrew/brew#2600]
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

I wanted to remove my existing installation from `/usr/local` and install it in home directory because of all the permissions errors I was getting on my work laptop. I followed the uninstall steps in the FAQ, ran the script, had to manually remove some folders because of insufficient permissions.

Right now I have installed it in ~/Homebrew and every time I run `brew` (doctor, update, or any args) I get the following:

`/Users/aky/Homebrew/bin/brew: line 5: cd: /usr/local/Homebrew/bin: No such file or directory`

I have tried reinstalling and changing the PATH. At this point I'm not sure if everything works correctly apart from this little error/warning, but I'd still like it to go away if possible.

Here's my config:
```
$ brew config
/Users/aky/Homebrew/bin/brew: line 5: cd: /usr/local/Homebrew/bin: No such file or directory
HOMEBREW_VERSION: 1.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8cba0352e0be94263e2ed96c98bf93d8f2fce8ef
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9c4f788f512c3fdb9f83dace59b2194a778c13bd
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /Users/aky/Homebrew
HOMEBREW_REPOSITORY: /Users/aky/Homebrew
HOMEBREW_CELLAR: /Users/aky/Homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0.390 => /usr/local/git/current/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

Did I forget to remove a reference somewhere?

**Comment by MikeMcQuaid** [comment]
What does `ls -lha /usr/local/bin/brew` output?

**Comment by akaij** [comment]
`$ ls -lha /usr/local/bin/brew`

`lrwxr-xr-x  1 aky  admin    28B Apr  9 20:20 /usr/local/bin/brew -> /usr/local/Homebrew/bin/brew`

**Comment by MikeMcQuaid** [comment]
Remove that symlink as it is broken.
