### ISSUE TITLE
Sandbox operations no longer work (`require': cannot load such file -- macho (LoadError))

### ISSUE THREAD

**Issue by mologie** [Homebrew/brew#2604]
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

Hi,

any installation or post-install command involving the sandbox fail since a recent update. This did not happen yesterday, and my system configuration did not change.

This also happens with a clean Homebrew installation.

```
# oliver @ Windshear in ~ [17:01:15] C:1
$ brew install cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.8.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cmake-3.8.1.sierra.bottle.tar.gz
==> Using the sandbox
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- macho (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/os/mac/mach.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/os/mac/pathname.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/extend/os/mac/hardware/cpu.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/extend/os/hardware.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/hardware.rb:123:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/os/mac.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/os.rb:15:in `<module:OS>'
	from /Users/oliver/.local/Library/Homebrew/os.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/extend/os/emoji.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/emoji.rb:14:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/utils.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/extend/pathname.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oliver/.local/Library/Homebrew/postinstall.rb:3:in `<main>'
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall cmake`
==> Caveats
Emacs Lisp files have been installed to:
  /Users/oliver/.local/share/emacs/site-lisp/cmake
==> Summary
/Users/oliver/.local/Cellar/cmake/3.8.1: 2,208 files, 29.2MB

# oliver @ Windshear in ~ [17:01:29] C:1
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /Users/oliver/.local/bin/blender
  /Users/oliver/.local/include/openssl
  /Users/oliver/.local/share/postgresql95
  /Users/oliver/.local/share/zsh/site-functions/_brew_services

# oliver @ Windshear in ~ [17:05:35] C:1
$ brew config
HOMEBREW_VERSION: 1.2.0-50-g3e4547f52
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 3e4547f52e7ebec633f8bfefc8a396d944edf908
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9c4f788f512c3fdb9f83dace59b2194a778c13bd
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /Users/oliver/.local
HOMEBREW_REPOSITORY: /Users/oliver/.local
HOMEBREW_CELLAR: /Users/oliver/.local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_111, 1.6.0_65-b14-468
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

**Comment by MikeMcQuaid** [comment]
Can you `brew update` and try again?

**Comment by krokofant** [comment]
Had the same problem with:
Homebrew 1.2.0-50-g3e4547f52
Homebrew/homebrew-core (git revision 9c4f7; last commit 2017-05-06)

But solved by `brew update` again.

**Comment by mologie** [comment]
Thanks, this seems to be resolved in the most recent version.

**Comment by mafredri** [comment]
Would it be possible to prevent `brew update` from updating to a broken `master`? E.g. users should not end up with a version of `master` where the build has failed. I haven't given thought for how to implement this in practice, maybe push via a different branch (develop?) + autopush master when CI is successful.

I suffered this yesterday and ended up setting `HOMEBREW_NO_AUTO_UPDATE=1` for my environment (I would prefer not to, but not being able to revert when homebrew breaks is worse).

**Comment by ilovezfs** [comment]
The vast majority of users are not on `master` but are on the [latest stable tag](https://github.com/Homebrew/brew/releases/latest). Those who are on `master` have either set `HOMEBREW_DEVELOPER=1` in their environment or run one of the [developer commands](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/dev-cmd), which will add
```
[homebrew]
	devcmdrun = true
```
to `$(brew --repo)/.git/config`.

**Comment by MikeMcQuaid** [comment]
> users should not end up with a version of master where the build has failed.

They didn't, the build passed.

**Comment by mafredri** [comment]
> The vast majority of users are not on master but are on the latest stable tag. Those who are on master have either set HOMEBREW_DEVELOPER=1 in their environment or run one of the developer commands, which will add

Thank for pointing this out, it seems I have `devcmdrun = true`. However, I was completely unaware of this. Enabling this by simply running a dev command seems very unexpected.

> They didn't, the build passed.

Sorry for my lack of knowledge of the internals, I was looking at this travis status: https://travis-ci.org/Homebrew/brew/builds/229664529 (which failed). Either way, looks like the problem was `devcmdrun`, which I have not knowingly enabled.

Is there any way I can prevent `devcmdrun = true` from being enabled in future?

**Comment by ilovezfs** [comment]
I think arguably we should respect a manually set `devcmdrun = false` though I don''t think that's currently the case.

**Comment by ilovezfs** [comment]
Also, setting `HOMEBREW_UPDATE_TO_TAG=1` may work, though I haven't tested that.

**Comment by mafredri** [comment]
Thanks @ilovezfs, I've set both for now 😄 .

**Comment by MikeMcQuaid** [comment]
> However, I was completely unaware of this. Enabling this (and thus the master branch) by simply running a dev command seems very unexpected.

It's an intentional segmentation of our users. We need to be able to test the `master` branch on a subset of our more technical users.

> Also, setting HOMEBREW_UPDATE_TO_TAG=1 may work, though I haven't tested that.

Yep, `export HOMEBREW_UPDATE_TO_TAG=1` is your best bet to avoid this behaviour.

**Comment by mafredri** [comment]
> It's an intentional segmentation of our users. We need to be able to test the `master` branch on a subset of our more technical users.

It makes sense, but I would have liked to be aware that I had opted into this =/. Not sure if I was ever prompted and I've probably been testing master for a loong time. That way it's less surprising and easier to fix when everything suddenly breaks.

> Yep, export `HOMEBREW_UPDATE_TO_TAG=1` is your best bet to avoid this behaviour.

👍

**Comment by MikeMcQuaid** [comment]
> It makes sense, but I would have liked to be aware that I had opted into this =/. Not sure if I was ever prompted and I've probably been testing master for a loong time. That way it's less surprising and easier to fix when everything suddenly breaks.

I appreciate that but it's intentional that we don't prompt people for this. We want you to be testing this because it helps us.

**Comment by mafredri** [comment]
> I appreciate that but it's intentional that we don't prompt people for this. We want you to be testing this because it helps us.

That's very sneaky, but it's your project, I love Homebrew so can't complain. I guess my point is that I would happily volunteer, however, this behaviour was a betrayal of my trust towards the software and thus I feel reluctant of enabling it again (due to the breakage).

**Comment by MikeMcQuaid** [comment]
> That's very sneaky, but it's your project, I love Homebrew so can't complain. I guess my point is that I would happily volunteer, however, this behaviour was a betrayal of my trust towards the software and thus I feel reluctant of enabling it again (due to the breakage).

It's not "sneaky" and it's not my project. We don't have adequate test coverage to be able to have whatever is on `master` tagged without more widespread testing on our CI and our more technical users. I've been maintaining this project for 8 years and although I don't expect anyone to defer to my knowledge of software development I'd ask people to do so on my knowledge of maintaining Homebrew: there's literally no-one who has been doing that longer than me.

This model is the best balance for all our users and it allows us to get more features and more fixes out to people far quicker than we did before. The consequence is: sometimes things break and when we do we drop whatever is going on in our lives to try and fix it ASAP. You were personally inconvenienced by your setup being broken for a few hours on a Sunday while I frantically worked through the day to fix the issue and you had a workaround to avoid being blocked. I'd ask that you have either cut the project a little more slack or consider using other projects like MacPorts that may better meet your needs.

**Comment by mafredri** [comment]
Sneaky:

> behaving in a secret and usually dishonest manner
> done in a secret and dishonest manner

You're right, sneaky was a bad word, I don't consider it dishonest. I totally stand by the first part of the words meaning though!

Also, I'm very sorry, I did not mean to offend, or complain about the project. I simply wanted to provide my (an advanced users) point of view, for you to do with what you please.

I appreciate the work you do, I'll just leave it at that.

**Comment by MikeMcQuaid** [comment]
> You're right, sneaky was a bad word, I don't consider it dishonest. I totally stand by the first part of the words meaning though!
> 
> Also, I'm very sorry, I did not mean to offend, or complain about the project. I simply wanted to provide my (an advanced users) point of view, for you to do with what you please.
> 
> I appreciate the work you do, I'll just leave it at that.

I genuinlely appreciate the apology and sorry for being a hard-ass earlier ❤️. Sounds like we all have an acceptable outcome now.
