### ISSUE TITLE
HOMEBREW_CURL env car bulldozed by brew.sh

### ISSUE THREAD

**Issue by HakimCassimallyBBC** [Homebrew/brew#2609]
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

To connect to some services locally, I require a curl compiled with openssl, and connected to my .pem file.  However this interacts badly with `brew`.  I would like to be able to both `curl` and `brew` conveniently.

Reproduction steps:

The problem:
- Ran `brew install parallel` (for example)
- notice errors like `curl: (58) SSL: Can't load the certificate "/Users/myuser/myuser.pem" and its private key: OSStatus -25299`  in the output
- attempt to `curl` the failed file, successfully (e.g. my curl executable does *not* fail)

Workaround 1:
- remove the curlrc `mv ~/.curlrc ~/.curlrc-backup` (as suggested by `brew doctor`)
- `brew install parallel` (now works)
- `curl some-url-that-I-need-my-curlrc-for` (now does NOT work, making this workaround inconvenient)

Workaround 2:
- replace the curlrc with `mv ~/.curlrc-backup ~/.curlrc)
- `HOMEBREW_CURL=/usr/local/bin/curl brew install parallel`  (having seen references to this environment variable in the codebase)
- unfortunately this gives same output as previous, making this workaround unsuccessful.

## output of brew config / doctor

```
$ brew config
HOMEBREW_VERSION: 1.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8cba0352e0be94263e2ed96c98bf93d8f2fce8ef
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: abdce97da6538d6e2e7861f32e32762d24501e76
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/myuser/.pyenv/shims/python => /Users/myuser/.pyenv/versions/2.6.6/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_131, 1.6.0_65-b14-468
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.3.0.0.1.1490382677
X11: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/myuser/.pyenv/shims/python-config
  /Users/myuser/.pyenv/shims/python2.6-config

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  curl
```

**Comment by HakimCassimallyBBC** [comment]
It looks like the overriding of HOMEBREW_CURL env var is introduced by https://github.com/Homebrew/brew/commit/77611bafb1dfc68e9cd59fb21163aefa53fccf2c#diff-2b9f1c573350b22cd8b1d6f044e9dde8R79

Perhaps that line could use a shell substitution, e.g. setting the variable only if not provided by the user?

Note that in the meantime, colleagues are solving this issue with a bash function wrapper that removes .curlrc, runs the brew command, then replaces the .curlrc.  I'm hoping there's a more elegant way to resolve this though :-)

**Comment by MikeMcQuaid** [comment]
> To connect to some services locally, I require a curl compiled with openssl, and connected to my .pem file. However this interacts badly with brew. I would like to be able to both curl and brew conveniently.

You can use a Homebrew `curl` compiled with SSL and let Homebrew use the system version.

> HOMEBREW_CURL=/usr/local/bin/curl brew install parallel (having seen references to this environment variable in the codebase)

This is not a public or documented environment variable. That it worked in the past was an implementation detail. We're not interested in letting users on 10.12 use an arbitrary `curl`.

I can't see actionable work on our side here so closing, sorry.

**Comment by HakimCassimallyBBC** [comment]
This doesn't work though (or I'm missing some detail for your suggestion to be a solution perhaps?)

Homebrew *can't* use the system curl, because the system curl doesn't understand the format of the certificate identified by the `cert=` line in my `.curlrc`.

**Comment by HakimCassimallyBBC** [comment]
The issue is documented in more detail in https://github.com/curl/curl/issues/283
I appreciate this may not be a homebrew issue as such, but it is something that is causing us pain while trying to use brew specifically.

**Comment by MikeMcQuaid** [comment]
> Homebrew can't use the system curl, because the system curl doesn't understand the format of the certificate identified by the cert= line in my .curlrc.

This is why we suggest you don't set it in `brew doctor`. I'm afraid this is an issue with your configuration.

> This doesn't work though (or I'm missing some detail for your suggestion to be a solution perhaps?)

I don't have a solution, I'm afraid. This is not a Homebrew issue.

**Comment by HakimCassimallyBBC** [comment]
I'd have thought that "we advise you not to configure a common and critical Unix application, whatever your company's security policies and network setup requirements are" smells a little like an issue ;-P

Anyway, I appreciate this isn't a development priority for you: would you be willing to code review a patch? (If I can find a minimal, non-disruptive code change to brew source that resolves the issue?)

(I suspect doing it within Brew source will make the most sense, even if it's not strictly a Brew issue - honestly, it sounds like it's OSX's openssl policy, but I really think that working around it within Brew source is much likelier than convincing Apple to fix it for us...)

**Comment by MikeMcQuaid** [comment]
> I'd have thought that "we advise you not to configure a common and critical Unix application, whatever your company's security policies and network setup requirements are" smells a little like an issue ;-P

Similarly, I'd have thought invoking that you're expecting volunteers working in their free time to help you fix a problem specific to your company for free would have smelled like something we're not going to do.

> Anyway, I appreciate this isn't a development priority for you: would you be willing to code review a patch? (If I can find a minimal, non-disruptive code change to brew source that resolves the issue?)

I'll always review patches but I can't promise it'll get accepted if it allows the selection of an arbitrary `curl` due to the increased support burden.

> (I suspect doing it within Brew source will make the most sense, even if it's not strictly a Brew issue - honestly, it sounds like it's OSX's openssl policy, but I really think that working around it within Brew source is much likelier than convincing Apple to fix it for us...)

I'd suggest doing something at your company level would make more sense than relying on either Apple or Homebrew to make the changes you need.

**Comment by HakimCassimallyBBC** [comment]
Heh, ok, will have a look at the possible resolutions in-house or as PR.  Thanks for your time and comments in the meantime!

**Comment by MikeMcQuaid** [comment]
My pleasure. Good luck with it (genuinely).

**Comment by bencampion** [comment]
You can override where curl loads the `.curlrc` from by setting the `CURL_HOME` environment variable. You could add an alias for brew to your `.bash_profile` to always set it to some location where there won't be a `.curlrc` so that brew doesn't use the incompatible `.curlrc` in your home directory:
```
alias brew='CURL_HOME=/ brew'
```

**Comment by MikeMcQuaid** [comment]
> This is not a public or documented environment variable. That it worked in the past was an implementation detail. We're not interested in letting users on 10.12 use an arbitrary curl.

As of https://github.com/Homebrew/brew/pull/3482 you can now do this with the `HOMEBREW_FORCE_BREWED_CURL` variable (documented in `man brew`).
