### ISSUE TITLE
`brew audit` on description length isn't strict enough

### ISSUE THREAD

**Issue by jonchang** [Homebrew/brew#2611]
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

-----

`brew audit` on description length is not restrictive enough. See https://github.com/Homebrew/homebrew-science/pull/5608

```
 $ brew desc https://raw.githubusercontent.com/MmgTools/homebrew-science/30777e8/mmg.rb | wc -c
     113
```

yet `brew audit --strict --online` for the same formula doesn't raise an error. The issue is that the string is constructed weirdly:

```
  desc "Simplicial remeshers: mesh improvement,"\
  "isotropic or anisotropic mesh adaptation and isovalue"\
  "discretization."
```

I don't know how to debug rubocops so if someone could point me in that direction that would be great.

**Comment by bfontaine** [comment]
Rubocop is a *static* code analyzer, meaning it analyze the code *without running it*. It can’t detect this. One way to circumvent the issue would be to flag this way of building strings (i.e. `"foo" "bar"` instead of `"foobar"`); I don’t think there’s any valid use-case for those in Homebrew.

**Comment by ilovezfs** [comment]
Perhaps it can reject a description line ending in `\`

**Comment by MikeMcQuaid** [comment]
@GauthamGoli any thoughts on this?

**Comment by GauthamGoli** [comment]
Three string types can result after rubocop parses the code as listed [here](https://github.com/whitequark/parser/blob/master/doc/AST_FORMAT.md#string). I didn't know that when I first wrote the cop. So a multi line string with `\` s is interpreted as an interpolated string.
I need to add these conditions and I'll submit a PR
Can we also expect here docs for formula `desc` ?

**Comment by MikeMcQuaid** [comment]
@GauthamGoli I think it's worth assuming anything can get any format of string input.
