### ISSUE TITLE
use sudo in $PATH instead of hardcoding to /usr/bin/sudo

### ISSUE THREAD

**Issue by nhooyr** [Homebrew/brew#2612]
I am using https://github.com/mattrajca/sudo-touchid to replace the builtin sudo. I have installed the new sudo command into `/usr/local/bin/sudo` and modified my `$PATH` appropriately but home-brew  seems to have `/usr/bin/sudo` hardcoded so it is not using my replaced sudo.

Could the path be changed to use whatever command is found in `$PATH` instead of hardcoding it to `/usr/bin/sudo`?

**Comment by MikeMcQuaid** [comment]
Sorry, this isn't something we're considering at this time as it's too prone to getting less experienced users bitten with errors/hacks.

**Comment by reitermarkus** [comment]
By the way, I just found this, which could be an alternative: https://github.com/hamzasood/pam_touchid

**Comment by nhooyr** [comment]
Thank you for the suggestion, it works great :)
