### ISSUE TITLE
`brew doctor` does interpret `recommended` flag as mandatory

### ISSUE THREAD

**Issue by retokromer** [Homebrew/brew#2625]
- [x] Confirmed this is a problem with running a `brew` command?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?

Running `brew doctor`, after installing `openjpeg`, gives an error message saying that the dependency `doxygen` is missing. However, the `openjpeg` formula has a `recommended` flag:
```
depends_on "doxygen" => [:build, :recommended]
```

**Comment by MikeMcQuaid** [comment]
> **Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

Please, please do this. In this case: please provide your `brew config` output with this and every other issue you file. Also, can I see the output of `cat /usr/local/opt/openjpeg/INSTALL_RECEIPT.json`?

**Comment by retokromer** [comment]
Sorry, @MikeMcQuaid, I did interpret that your colleague knows what is the issue.

Here `brew config` on a fresh installation:

```
HOMEBREW_VERSION: 1.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8cba0352e0be94263e2ed96c98bf93d8f2fce8ef
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 151887da68c0678c594b6909ac2c271958ada9a8
Core tap last commit: 19 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

and here `cat /usr/local/opt/openjpeg/INSTALL_RECEIPT.json`:

```
{"homebrew_version":"1.1.12-40-g02f0189","used_options":[],"unused_options":["--without-doxygen","--with-static"],"built_as_bottle":true,"poured_from_bottle":true,"installed_as_dependency":false,"installed_on_request":true,"changed_files":["INSTALL_RECEIPT.json","lib/openjpeg-2.1/OpenJPEGTargets-release.cmake","lib/pkgconfig/libopenjp2.pc"],"time":1494671397,"source_modified_time":1475086696,"HEAD":null,"stdlib":null,"compiler":"clang","runtime_dependencies":[{"full_name":"little-cms2","version":"2.8"},{"full_name":"jpeg","version":"8d"},{"full_name":"libtiff","version":"4.0.7"},{"full_name":"libpng","version":"1.6.29"}],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openjpeg.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"2.1.2","devel":null,"head":"HEAD","version_scheme":0}}}
```

**Comment by retokromer** [comment]
The message got from `brew doctor` is:

```
Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install doxygen
```

**Comment by MikeMcQuaid** [comment]
> Sorry, @MikeMcQuaid, I did interpret that your colleague knows what is the issue.

That's OK, thanks.

> "used_options":[],"unused_options":["--without-doxygen","--with-static"]

That's what I was looking for. Still a bug but helps narrow it down.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula.rb#L1556-L1561

dep.build? needs to go first.

**Comment by retokromer** [comment]
Thank you!
