### ISSUE TITLE
cannot install via linuxbrew due to gcc-4.9: error: rh6_x86_64: No such file or directory

### ISSUE THREAD

**Issue by sarahtariq93** [Homebrew/brew#2634]
# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [ ] Ran `brew update` and retried your prior step? I did that
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
**Warning: An outdated version (1.7.11.1) of Git was detected in your PATH.
Git 1.8.5 or newer is required to perform checkouts over HTTPS from GitHub and
to support the 'git -C <path>' option.
Please upgrade:
  brew install git**

**I cannot solve it as brew install git produces same error when do brew install node** 

- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

=========brew config
**ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 1d16368a177807663e1b3146d71fcd69e2061e27
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 25de6aef3695fba0495bebe3d3f31d17dcad06eb
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /home/saali/.linuxbrew
HOMEBREW_REPOSITORY: /home/saali/.linuxbrew
HOMEBREW_CELLAR: /home/saali/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 16-core 64-bit nehalem
Homebrew Ruby: 2.0.0-p648 => /home/saali/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 1.7.11.1 => /zin/tools/bin/git
Perl: /zin/tools/bin/perl => /zin/plat/local/perl-5.20.0/bin/perl
Python: /zin/tools/bin/python => /zin/plat/local/certus_dev/bin/python2.6
Ruby: /usr/bin/ruby
Java: openjdk version "1.8.0_131"
Kernel: Linux 2.6.32-279.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.3 (Final) (Final)
Host glibc: 2.12
/usr/bin/gcc: 4.9.2
glibc: N/A
gcc: N/A
xorg: N/A**

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
**install nodejs and npm using brew (working on linux x64 GNOME terminal)**
- What happened (include command output)
**==> perl ./Configure --prefix=/home/saali/.linuxbrew/Cellar/openssl/1.0.2k --openssldir=/home/saali/.linuxbrew/etc/openssl no-ssl2 zlib-dynamic sh
==> make depend
==> make
Last 15 lines from /home/saali/.cache/Homebrew/Logs/openssl/03.make:
2017-05-14 09:58:02 -0700****

**make
making all in crypto...
make[1]: Entering directory `/tmp/openssl-20170514-32584-v8vxv/openssl-1.0.2k/crypto'
/usr/bin/perl ../util/mkbuildinf.pl "gcc-4.9 -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_
DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM
_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM" "
linux-x86_64" >buildinf.h
gcc-4.9 -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstac
k -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_A
SM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  rh6_x86_64 -c -o cryptlib.o cryptlib.c
gcc-4.9: error: rh6_x86_64: No such file or directory
make[1]: *** [cryptlib.o] Error 1
make[1]: Leaving directory `/tmp/openssl-20170514-32584-v8vxv/openssl-1.0.2k/crypto'
make: *** [build_crypto] Error 1**

- What you expected to happen
**installing node successfully** 
- Step-by-step reproduction instructions (by running `brew` commands)

**Comment by sarahtariq93** [comment]
Why did you close the issue ?! 

    On Sunday, May 14, 2017 8:59 PM, Mike McQuaid <notifications@github.com> wrote:
 

 Closed #2634.—

**Comment by MikeMcQuaid** [comment]
Because this isn't Linuxbrew and you didn't read the issue template.

**Comment by sarahtariq93** [comment]
I almost answered all question of the issue template and did all pre-steps of reproducing 

    On Monday, May 15, 2017 9:46 AM, Mike McQuaid <notifications@github.com> wrote:
 

 Because this isn't Linuxbrew and you didn't read the issue template.—

**Comment by MikeMcQuaid** [comment]
Report this to https://github.com/Linuxbrew/brew
