### ISSUE TITLE
GDB broken.

### ISSUE THREAD

**Issue by shahzeb1** [Homebrew/brew#2636]
# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Run a program with GDB which has been installed view brew.
- What happened (include command output)

When I run `$ gdb ./a.out`:

> warning: unhandled dyld version (15)

I've found this [forum thread](https://sourceware.org/bugzilla/show_bug.cgi?id=20981). When I run `gdb) info shared` I get the following:

> No shared libraries loaded at this time.

What does this mean?

- What you expected to happen
GDB program debugging like it use to.
- Step-by-step reproduction instructions (by running `brew` commands)

1. Brew uninstall gdb
2. Brew install gdb
3. Codesign the gdb folder
4. Run `$gdb ./a.out` on any cpp file.

I'm really not sure what's going on here, and would love some guidance. Thank you in advance!

**Comment by alyssais** [comment]
> - [X] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

This _is_ an issue with the `gdb` formula. Please file this issue at https://github.com/Homebrew/homebrew-core/issues/new, where there'll be people who're better able to help you sort it out. :)

**Comment by jhunt** [comment]
Did this ever get reported to the homebrew-core team?

**Comment by MikeMcQuaid** [comment]
@jhunt It's not linked here so: seems not.

**Comment by tyrocca** [comment]
Is there anyway to get around this?
