### ISSUE TITLE
Error: stack level too deep on 10.12.4

### ISSUE THREAD

**Issue by Baoyx007** [Homebrew/brew#2637]
Error: stack level too deep

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:48

[brew_doctor](https://gist.github.com/Baoyx007/c3b408f85284bf08c922acd974699673.js)
[brew_config](https://gist.github.com/Baoyx007/52090397ba500c2d9443747a88467e7c)

**Comment by MikeMcQuaid** [comment]
Please run `brew doctor --debug`, thanks.

Also, in future please always fill out the issue template.
