### ISSUE TITLE
alpha/beta version parsing

### ISSUE THREAD

**Issue by petere** [Homebrew/brew#2639]
There is some inconsistent behavior when parsing certain alpha/beta version numbers.

If a formula tarball has a name like `foo-1.2.3beta4`, that is parsed as version "4".

It's weird that`version.rb` has support for comparing such versions (see `test/version_spec.rb`), but not parsing them. Perhaps this line in `version.rb`

    m = /-((?:\d+\.)*\d+-(?:alpha|beta|rc)\d*)$/.match(stem)

could be changed to something like

    m = /-((?:\d+\.)*\d+-?(?:alpha|beta|rc)\d*)$/.match(stem)

**Comment by MikeMcQuaid** [comment]
Closing not because this isn't legitimate but because our version autodetection rathole is such a mess that we prefer PRs rather than issues.
