### ISSUE TITLE
Getting 407 "Proxy Authentication Required" when behind Proxy

### ISSUE THREAD

**Issue by britztopher** [Homebrew/brew#264]
I commented on this ticket #89  that is closed, so I was told to open a new one:

As i just tried to upgrade to use brew 0.9.9 and ran into a couple issues because im behind a proxy server. First, I kept getting this error:

  Error: Non-HTTP proxy URI: https://myun:mypassword@myproxy.com

Then found a workaround by setting https_proxy=$http_proxy which leads me to the Error: 407 "Proxy Authentication Required I reverted back to the homebrew-legacy github project, which is working as expected

**Comment by mikemcquaid** [comment]
@britztopher Could you post your `brew config` and `env | grep -i proxy`? Thanks!

**Comment by britztopher** [comment]
@MikeMcQuaid Thing is i reverted back and i really dont want to have to go back and try this all over again.  Would homebrew legacy and homebrew 'new' be the same config file?  Also, i have my `http_proxy` and `https_proxy` set in my environment vars.    I have seen talk on SO that states this could be an issue with ruby's uri implementation, however, i dont understand why this works with legacy and not the 0.9.9 release.

**Comment by MikeMcQuaid** [comment]
@britztopher That's fine, still interested in both those values on legacy-homebrew, thanks.

**Comment by britztopher** [comment]
@MikeMcQuaid  here is my brew config 
HOMEBREW_VERSION: 0.9.8
ORIGIN: https://github.com/Homebrew/legacy-homebrew.git
HEAD: f0b70e5725662377ea2feb14f59e407bd7071fe0
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 89833243043754e669be26ea756cab12b150c9a4
Core tap last commit: 32 hours ago
HOMEBREW_PREFIX: /usr/local/legacy-homebrew
HOMEBREW_REPOSITORY: /usr/local/legacy-homebrew
HOMEBREW_CELLAR: /usr/local/legacy-homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.4-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
Clang: 7.3 build 703
X11: N/A
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60, 1.7.0_80

also, i shared my proxy env vars already.

**Comment by MikeMcQuaid** [comment]
@britztopher I'm still interested in the output of `env | grep -i proxy` if you get the chance, thanks!

**Comment by MikeMcQuaid** [comment]
@Homebrew/maintainers Given the dire state of Ruby's proxy support (in relation to `curl`'s) I'm tempted to say we rewrite anything using the Ruby HTTP APIs to use `curl` instead. Any objections?

**Comment by DomT4** [comment]
Presuming we enforce the use of our `curl` where we know the system's is useless, 👍 from me in principle.

**Comment by UniqMartin** [comment]
A quick `grep` indicates that we're currently using Ruby's HTTP/HTTPS APIs for GitHub API access and for uploading Gists via `brew gist-logs`. Have I missed anything? (`brew pull` also uses it, but that's probably less of a concern as this isn't user facing.)

I'm in favor making all those instances use `curl`, if that can be feasibly done (and I guess it can be).

**Comment by MikeMcQuaid** [comment]
> A quick grep indicates that we're currently using Ruby's HTTP/HTTPS APIs for GitHub API access and for uploading Gists via brew gist-logs. Have I missed anything?

@UniqMartin Those are also the main places I thought of.

> (brew pull also uses it, but that's probably less of a concern as this isn't user facing.)

Yeh, that was a case where I thought using the API is fine as no maintainers have complained about it.

**Comment by britztopher** [comment]
@MikeMcQuaid here are my env vars for `env | grep -i proxy`:

https_proxy=https://un:pw@myproxy.com:1234
http_proxy=http://un:pw@myproxy.com:1234
HTTP_PROXY=http://un:pw@myproxy.com:1234
HTTPS_PROXY=https://un:pw@myproxy.com:1234

**Comment by apjanke** [comment]
> > (brew pull also uses it, but that's probably less of a concern as this isn't user facing.)
>
> Yeh, that was a case where I thought using the API is fine as no maintainers have complained about it.

Yeah, and the particular thing it's doing can't be done in pure `curl`; otherwise I would have just used `curl`.

No objections to rewriting other uses in `curl`.

**Comment by xu-cheng** [comment]
@britztopher Kinda curious to me, What will happen if you run `brew gist-logs <any formula you installed>`? If it were a success, I believe the root problem is not Ruby's HTTP proxy support is broken but open-uri's proxy support doesn't work with basic auth.

**Comment by brian-eng** [comment]
After updating homebrew so I got the changes from #295 I no longer need to set the env HOMEBREW_NO_GITHUB_API in order to add taps or install new formula as per https://github.com/Homebrew/brew/issues/193#issuecomment-217742510

Granted, the proxy I'm behind doesn't require authentication so it's not exactly the same issue as @britztopher has.

**Comment by UniqMartin** [comment]
@brian-eng Thanks for the feedback! This sounds encouraging.

**Comment by MikeMcQuaid** [comment]
@brian-eng Glad to hear it. @britztopher I'm going to assume I've fixed this for you but comment if I have not.
