### ISSUE TITLE
What does `Successfully started` mean when status is error?

### ISSUE THREAD

**Issue by TracyDa** [Homebrew/brew#2640]
I still very confused about this:

```
🍀  brew services start nginx
==> Successfully started `nginx` (label: homebrew.mxcl.nginx)
🍀  brew services list
Name    Status  User  Plist
mongodb stopped
mysql   started tracy /Users/tracy/Library/LaunchAgents/homebrew.mxcl.mysql.plist
nginx   error   tracy /Users/tracy/Library/LaunchAgents/homebrew.mxcl.nginx.plist
redis   started tracy /Users/tracy/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

As you can see, the message shows that nginx start successfully, but as a matter of fact, it should  return error, but if I don't run `brew services list` I won't realize the output cheat me.

Also can i get the error log? My nginx.conf is correct, so what's the problem?

**Comment by MikeMcQuaid** [comment]
Issues for homebrew-services should be filed at https://github.com/homebrew/homebrew-services in future.

We cannot identify what the problem is, `brew services` is a thin wrapper around `launchctl`. You could check one of the logs in /usr/local/var/log/nginx/*.log
