### ISSUE TITLE
Issues with reinstall

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#2643]
- [x] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.2.1-7-g2b726383f
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 2b726383f1712e5a34627b4db9bed8b7b81973b2
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e79cb9868db4731996758a1bce713465d26109b1
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.4.1/bin/ruby
Java: 1.8.0_131
macOS: 10.12.5-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

If `brew reinstall` fails apparently it does not remove the failed reinstall/relink the version that existed previously.

```
make[2]: *** [xcheck] Error 22
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

==> Formula
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb
....

~> brew info gnupg
https://www.gnupg.org/
/usr/local/Cellar/gnupg/2.1.21.reinstall (134 files, 10.2MB)
  Built from source on 2017-05-16 at 02:23:01
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnupg.rb
```

And then it remains there:
```
~> brew reinstall gpg -s -v
Error: Directory not empty - (/usr/local/Cellar/gnupg/2.1.21.reinstall, /usr/local/Cellar/gnupg/2.1.21)
```

And is considered a newer version:
```
~> brew rm gpg
Uninstalling /usr/local/Cellar/gnupg/2.1.21... (134 files, 10.2MB)
gnupg 2.1.21.reinstall is still installed.
Remove all versions with `brew uninstall --force gnupg`.
```

**Comment by MikeMcQuaid** [comment]
@DomT4 Can you provide a step-by-step list of `brew` commands that reproduces this?

**Comment by DomT4** [comment]
Apparently not; I reproduced this multiple times before reporting it but can't get it to happen now, so presuming accidentally fixed or some transient issue.

**Comment by pasine** [comment]
FIY, I was facing the exactly same problem with [parity](https://github.com/paritytech/homebrew-paritytech) today, trying upgrading to the latest version running `brew reinstall parity`.
I solved the problem manually deleting the two non-empty directories.

**Comment by DomT4** [comment]
Just reproduced this, heh. Accidentally this time. Was doing some testing with `wget` on an unrelated issue & aborted the build with `ctrl + c` which did this:

```
make[5]: Nothing to be done for `install-data-am'.
Making install in src
  CC       connect.o
  CC       convert.o
  CC       cookies.o
  CC       ftp.o
  CC       css_.o
  CC       css-url.o
  CC       ftp-basic.o
  CC       ftp-ls.o
^CError: Directory not empty - (/usr/local/Cellar/wget/1.19.1.reinstall, /usr/local/Cellar/wget/1.19.1)

~> brew info wget
wget: stable 1.19.1 (bottled), HEAD
Internet file retriever
https://www.gnu.org/software/wget/
/usr/local/Cellar/wget/1.19.1 (41 files, 491.5KB)
  Built from source
/usr/local/Cellar/wget/1.19.1.reinstall (51 files, 2.1MB)
  Built from source on 2017-05-24 at 17:25:57 with: --with-libidn2
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/wget.rb
```

**Comment by MikeMcQuaid** [comment]
@DomT4 Gotcha. Let me know what you think the Ctrl-C behaviour should be and I'll try to implement it.

**Comment by DomT4** [comment]
It's probably subjective, because Ctrl-C isn't "handled" by most things; if you abort a build like that outside Homebrew whichever directory you were installing into is still going to have as much as was installed before you aborted there.

Inside Homebrew I guess I _hoped_ that it would gracefully abort the build (✅) , ditch the temporary build directory (✅), ditch the `.reinstall` directory (❎) & relink the existing version that was unlinked for the reinstall (❎).
