### ISSUE TITLE
Support of "-mmacosx-version-min" and MACOSX_DEPLOYMENT_TARGET < current MacOSX

### ISSUE THREAD

**Issue by remoe** [Homebrew/brew#2647]
I use brew to build application dependencies to distribute an app. I use MacOSX Sierra (10.12) to build. But the signed build doesn't run on older MacOSX like 10.9. Because "codesign" use the LC_VERSION_MIN_MACOSX entry of the binary to determine which hash code should be created: SHA1 or a SHA-256. Older MacOSX only supports SHA1.

This is what brew currently creates:

```
  cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.12
  sdk 10.12
```

This is what is needed:

```
  cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.9
  sdk 10.12
```

Is it possible to build all brew packages with custom settings for

-mmacosx-version-min and MACOSX_DEPLOYMENT_TARGET

? Or is there a better way to solve this ?

Thanks

**Comment by MikeMcQuaid** [comment]
> Is it possible to build all brew packages with custom settings for
> 
> -mmacosx-version-min and MACOSX_DEPLOYMENT_TARGET

We don't support this, sorry.

> ? Or is there a better way to solve this ?

Build them yourself outside of Homebrew.
