### ISSUE TITLE
Cannot download octave because the user agent contains "curl"

### ISSUE THREAD

**Issue by sebma** [Homebrew/brew#2648]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
```
$ brew update
Already up-to-date.
```
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?

Yes I did.

- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config
HOMEBREW_VERSION: 1.2.1-3564-gf0dc1d96
ORIGIN: https://github.com/Homebrew/brew
HEAD: f0dc1d96c50551be69ea418148a9bc2d72cfaf16
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8ad5af42c58305489811f66f82899c8bf3795608
Core tap last commit: 7 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.7.0_80
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

What : Trying to install cask xoctove
Why : Because I need it :)

- What happened (include command output)

```
$ brew cask install xoctave
==> Downloading http://www.xoctave.com/demo/xoctave%20demo.dmg

curl: (22) The requested URL returned error: 406 Not Acceptable
Error: Download failed on Cask 'xoctave' with message: Download failed: http://www.xoctave.com/demo/xoctave%20demo.dmg
The incomplete download is cached at /Users/mansfeld/Library/Caches/Homebrew/Cask/xoctave--latest.dmg.incomplete
Error: nothing to install
```

- What you expected to happen

A normal installation

- Step-by-step reproduction instructions (by running `brew` commands)

`brew cask install xoctave`

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it, how it would be relevant to at least 90% of Homebrew users and alternatives considered.
Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
> brew installing one or more formulae?

Please report this to Homebrew Cask.

**Comment by sebma** [comment]
I'm not sure the useragent has anything to do with Homebrew Cask

**Comment by sebma** [comment]
```
$ curl -#OA "curl" --fail "http://www.xoctave.com/demo/xoctave%20demo.dmg"

curl: (22) The requested URL returned error: 406 Not Acceptable
$ curl -#OA "Homebrew" --fail "http://www.xoctave.com/demo/xoctave%20demo.dmg"
######################################################################## 100.0%
$
```

**Comment by MikeMcQuaid** [comment]
> I'm not sure the useragent has anything to do with Homebrew Cask

This is an issue with a cask and not with a formula or Homebrew.

**Comment by vitorgalvao** [comment]
[Already fixed](https://github.com/caskroom/homebrew-cask/pull/34364/files).
