### ISSUE TITLE
homebrew totally broken on macOS Sierra 10.12.4

### ISSUE THREAD

**Issue by CaptainFatty** [Homebrew/brew#2659]
Hello,

Whatever I do (install, uninstall, doctor, update) I get this error:

Sirenia:$ brew update
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mach (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'

Oh dear. It's never done that before... Does anyone know what's happened and how to get me brewing again?

Thanks.

Cheers,
Matt

**Comment by MikeMcQuaid** [comment]
Please always fill in the issue template as requested.

> Does anyone know what's happened

No idea, sorry.

> how to get me brewing again?

Try to run `brew update-reset` and then `brew update` again.

**Comment by CaptainFatty** [comment]
Ah, ok, sorry.
Same old error - I'll re-install Sierra I think.

Cheers,
Matt

**Comment by vitorgalvao** [comment]
@CaptainFatty You should also put your code in issues in [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks).

> I'll re-install Sierra I think.

Closing, then.

**Comment by jwmapana** [comment]
I'm having this problem after upgrading to High Sierra. No command works at all.

> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

	from /usr/local/Library/brew.rb:15:in `<main>'

**Comment by MikeMcQuaid** [comment]
@jwmapana Run `brew update-reset` if that works or otherwise uninstall and install Homebrew again.

**Comment by ilovezfs** [comment]
It is also worth trying
```
sudo chown -R $(whoami) /usr/local/*
```
if `brew update-reset` doesn't do the trick.

**Comment by LingyanYin** [comment]
I have the similar issue! brew anything won't work, just give me the error:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)

**Comment by MikeMcQuaid** [comment]
@LingyanYin What does `brew update-reset` output?

**Comment by LingyanYin** [comment]
@MikeMcQuaid Thanks for reaching out. It gave me the same output. 

brew update-reset
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'

**Comment by LingyanYin** [comment]
@MikeMcQuaid Still the same error. I also tried to re-start my macbook and same error still occurred. I just upgrade my IOS to high seirra yesterday... Today when I tried to use homebrew, then it failed totally...

cd "$(brew --repo)"

> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/Library/brew.rb:15:in `<main>'

**Comment by MikeMcQuaid** [comment]
@LingyanYin Uninstall and reinstall GitHub through https://github.com/homebrew/install.

**Comment by LingyanYin** [comment]
Thanks. This is my last resort which everything installed through homebrew will be also re-installed, too.

**Comment by MikeMcQuaid** [comment]
@LingyanYin Ok, last thing to try: `cd /usr/local; git fetch; git reset --hard origin/master`

**Comment by LingyanYin** [comment]
Thanks! I have fixed it! :) 👍

**Comment by Gr3g0** [comment]
I'm having the exact same issue LingyanYin - do you recall what steps you took to fix it? Thanks!

**Comment by LingyanYin** [comment]
Hi, there is no walk-around way to solve this. You have to remove and reinstall the homebrew totally (following the instructions through https://github.com/homebrew/install)... and all the stuff you installed through homebrew previously needs reinstalled, too... Hope it helps :)

**Comment by Gr3g0** [comment]
Yes, that is what I wound up doing myself. Then, I just found this which may be the better way to go on High Sierra for other users: 
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

**Comment by eugeniaharris** [comment]
The ruby trick fixed it for me in High Sierra 10.13.3, thank you Gr3g0!
