### ISSUE TITLE
brew install subversion18 --universal --with-java fails due to dependency failing to be located

### ISSUE THREAD

**Issue by kmincks** [Homebrew/brew#266]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

The install of subversion18 fails because the serf-1.3.8.tar.bz2 package has moved from the googlecode.com repo to the following URL:

https://archive.apache.org/dist/serf/serf-1.3.8.tar.bz2

https://serf.googlecode.com redirects to https://code.google.com/archive/p/serf/ where the following is shown:

------------------------------------------
With the closing of Google Code, the serf project has now become Apache Serf!!

Please see our new home page for information, downloads, and issue tracking for the project.
------------------------------------------

The error in from brew is listed below:

$ brew install subversion18 --universal --with-java
==> Installing subversion18 from homebrew/versions
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.8.16.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion18-1.8.16.tar.bz2
==> Patching
patching file configure
Hunk #1 succeeded at 25433 (offset 67 lines).
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Downloading https://serf.googlecode.com/svn/src_releases/serf-1.3.8.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "subversion18--serf"
Download failed: https://serf.googlecode.com/svn/src_releases/serf-1.3.8.tar.bz2

**Comment by kmincks** [comment]
Oh, I did try to manually download the file and move it into the /Library/Caches/Homebrew/ folder, but it is still not picking up the dependency from that location

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-versions/commit/516908f1edff0362d6f1004007c3aff1505062b2. Please `brew update` and try again. 

Note reporting issues that apply to `homebrew/versions` formulae should be done in that tap, Thanks!
