### ISSUE TITLE
brew audit takes forever since 330307b

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/brew#2665]
330307b01a37ea514ec747ebab7a99dd47b79e7c from #2601. Haven't looked into what it does, but

```
$ cd /usr/local/Homebrew
$ git checkout 330307b01a37ea514ec747ebab7a99dd47b79e7c
Previous HEAD position was ade62aa1b1... Add the same check for Formulae.
HEAD is now at 330307b01a... Use `FormulaVersions` for checksum check.
$ time (brew audit youtube-dl)
( brew audit youtube-dl; )  42.81s user 17.03s system 146% cpu 40.864 total
$ git checkout 330307b01a37ea514ec747ebab7a99dd47b79e7c~
Previous HEAD position was 330307b01a... Use `FormulaVersions` for checksum check.
HEAD is now at ade62aa1b1... Add the same check for Formulae.
$ time (brew audit youtube-dl)
( brew audit youtube-dl; )  2.11s user 0.47s system 102% cpu 2.519 total
```

That's a 10-20x increase, and 40s to audit a single formula is rather discouraging.

**Comment by ilovezfs** [comment]
CC @reitermarkus @MikeMcQuaid

**Comment by zmwangx** [comment]
Just took at this. `previous_version_and_checksum` checks every revision since the Big Bang. That's 718 commits (at the moment) for `youtube-dl`, 386 commits for `git`, 93 commits for `gcc`,  etc. There should a limit to the number of revisions checked.

**Comment by MikeMcQuaid** [comment]
> There should be a limit to the number of revisions checked.

Agreed. This should only need to get the current checksum and a single previous one.

@reitermarkus Please prioritise this today if you're working on Homebrew otherwise I think we'll need to revert.

**Comment by reitermarkus** [comment]
I put the `break` inside the wrong loop!

**Comment by ilovezfs** [comment]
@zmwangx this should be fixed now. Thanks for reporting it.
