### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by kousik-envs** [Homebrew/brew#2677]
135: syntax error near unexpected token `source/usr/local/ferret/ferret_paths'

**Comment by ilovezfs** [comment]
**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

**Comment by kousik-envs** [comment]
bash: /home/kd/.bashrc: line 135: syntax error near unexpected token `source/usr/local/ferret/ferret_paths'
bash: /home/kd/.bashrc: line 135: `fi source/usr/local/ferret/ferret_paths'

**Comment by ilovezfs** [comment]
@kousik-envs do you have a question?

**Comment by kousik-envs** [comment]
When opening the terminal it shows above mentioned error msg. It encountered during installation of ferret

**Comment by ilovezfs** [comment]
From the above it looks like you're using Linux and Linxubrew. Is that correct?

**Comment by kousik-envs** [comment]
Yes I am using ubuntu 16.04.2

**Comment by ilovezfs** [comment]
OK. In that case, please report your issue to https://github.com/Linuxbrew/brew (and include a lot more detail when you do).
