### ISSUE TITLE
Feature: Allow `brew pin <formula>` to work with uninstalled formulae, thus preventing future installation

### ISSUE THREAD

**Issue by xml** [Homebrew/brew#2680]
There are [more than](https://github.com/yarnpkg/yarn/issues/1116) [a few](https://discourse.brew.sh/t/yarn-depends-on-node-but-i-have-non-homebrew-node/545) [different](https://github.com/Homebrew/homebrew-core/issues/6187) [conversations](https://github.com/Homebrew/brew/pull/1408#issuecomment-272343833) about packages like yarn, where people want finer control over whether a dependency gets installed or not. In the case of yarn, what they want is to avoid re-installing node through homebrew, if they already have nvm installed or are otherwise managing it separately in the host system. 

It makes perfect sense for the brew community to avoid wading into that fight, and to avoid needing to check outside the brew context for dependency information. But I think you could accomplish what people are asking for in this case with a slight expansion of an existing feature.

Right now, if I want to pin node at its current version within homebrew, preventing upgrades, I can `brew pin node`. But if I don't yet have node installed, and I run that, I get `Error: node not installed`.

What if, instead, it responded: `WARNING: by pinning an uninstalled formula (node), you will prevent it from being installed in the future, even if other formulae declare it as a dependency. Proceed?`

And, optionally, a warning could appear the next time I run `brew install yarn`: 
   `WARNING: formula node was declared as a dependency of yarn, but you have pinned node as uninstalled...`

This would allow people the finer control they want for many use-cases, without substantially complicating brew's interactions with the host system. What do you think?

**Comment by ilovezfs** [comment]
You can use `--ignore-dependencies` for yarn for this.

**Comment by MikeMcQuaid** [comment]
> what they want is to avoid re-installing node through homebrew, if they already have nvm installed or are otherwise managing it separately in the host system.

What we need to know is not that people want this but why they want it. Disk space? Bandwidth? Things being in the PATH?

**Comment by xml** [comment]
@MikeMcQuaid To answer your question in the specific case of node, many of us run node via a system install of nvm (Node Version Manager), so we can precisely control which node we run in which folder, for which project. We do not, under any circumstances, want to have additional versions of node installed via homebrew, nor anywhere else, as those will interfere in various Bad Ways, as when using default node in shell scripts, as a dependency to other apps, etc. 

We go through life adding and removing other packages on a regular basis. Yarn, for instance. Some rely on node. Some do not. We add, we upgrade, we delete and reinstall. Time passes. We allow brew itself to be the source of truth for what we have and don't have, rather than needing to track a million separate things ourselves. 

Sometimes, in that process of installing brew packages, you remember that a given package you're installing depends on node, and that node will be installed as a dependency, and that this would be Bad. Other times, you don't. Sometimes you remember to add `--ignore-dependencies` to the command. Other times, you don't. 

Or, maybe `brew install <whatever>` is run by another script, without even an opportunity for intervention...

Invariably, you eventually wind up with a node installation you don't want, because you let your guard down once; and often, you only realize it after you've spent hours debugging something, only to realize that your code is actually executing in a completely different version of node than you expected.

And this can happen with many different tools/languages/runtimes that brew offers, but which you have good reasons to install elsewhere and manage separately. Ruby and RVM come to mind. I'm sure there are others, and that node is not a special snowflake. 

To ensure that you never create a conflict, you thus have to carefully observe output of each and every `brew install`, and manually, with human eyes, note where any of those unwanted dependencies have been introduced, then manually remove it/them. It's an entirely human-dependent system, and not just once, but many times, every time you install anything that _might_ introduce that dependency.

Or, much more maintainable and programmatic: a user could simply _declare_ what they need: "I don't want node/ruby/python/whatever installed in brew on this system, ever." And the problem is then solved in a way that's reliable, consistent, convenient, and understandable.

Again, the goal is not to put homebrew in the position of needing to worry about other system dependencies. In fact, my proposal is about avoiding that entirely, by letting the user state very clearly what they want installed by brew (or rather, _don't_ want installed), and using that approach as an alternative to any other intervention. (cc: @ilovezfs )

**Comment by ilovezfs** [comment]
> We do not, under any circumstances, want to have additional versions of node installed via homebrew, nor anywhere else, as those will interfere in various Bad Ways

What does that have to do with `brew pin`?

**Comment by ilovezfs** [comment]
Oh I see you want pin to be able to prevent ever installing something. Queue the support issues for broken installations when someone pins something that provides libraries used by various bottles.

**Comment by ilovezfs** [comment]
This should prevent accidental installation of node:
```
iMac-TMP:~ joe$ mkdir /usr/local/Cellar/node
iMac-TMP:~ joe$ chmod 000 /usr/local/Cellar/node
iMac-TMP:~ joe$ brew install yarn
Error: Permission denied - /usr/local/Cellar/node
iMac-TMP:~ joe$ brew install --ignore-dependencies yarn
==> Using the sandbox
==> Downloading https://yarnpkg.com/downloads/0.24.6/yarn-v0.24.6.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/yarn-0.24.6.tar.gz
🍺  /usr/local/Cellar/yarn/0.24.6: 13 files, 3.4MB, built in 1 second
iMac-TMP:~ joe$ brew uninstall yarn
Error: Permission denied - /usr/local/Cellar/node
iMac-TMP:~ joe$ brew uninstall --ignore-dependencies yarn
Uninstalling /usr/local/Cellar/yarn/0.24.6... (13 files, 3.4MB)
```

**Comment by ilovezfs** [comment]
(An inconvenience with that though is you'd always have to pass `--ignore-dependencies` to `brew uninstall` regardless of what you're uninstalling (an alias would achieve that), and that would remove the protections that checking for reverse dependencies before uninstalling provides.)

**Comment by MikeMcQuaid** [comment]
The suggested solution on our end is to adjust your `PATH` such that the first `node` is the desired one and ignore (or even unlink) the Homebrew `node`.

**Comment by ilovezfs** [comment]
Unfortunately unlinking is not persistent across upgrades, so adjusting your PATH is really the only reliable way to go.

**Comment by xml** [comment]
Yes... however many packages have post-install scripts that update your path after they run, thus overriding/supplementing whatever you've done yourself to adjust the PATH. I don't know if Homebrew has some special way of overriding/preventing that behavior with its formulae, but I consistently have to prune the cruft that accumulates in dotfiles after installations, and would assume that brewed packages are not immune.

Further, isn't the point of Homebrew precisely to be able to manage your environment _without_ lots of manual tinkering with dotfiles? 

**_Bottom-line: I think you created Homebrew and go to the effort to maintain it, in order to give people the power to easily, declaratively manage their own environments. To get what they want without lots of muss and fuss, without needing to engage in black-magic just to get the behavior they expect. For most folks, the `PATH` is essentially black-magic, and they'll never touch their dotfiles. They come to Homebrew precisely to avoid that sort of thing. This proposal is about using Homebrew's own declarative conventions to empower users to control their environment, without resorting to the same kinds of imperative, low-level configuration that people are trying to avoid in the first place._**

**Comment by xml** [comment]
In response to your concern about support issues, @ilovezfs, I believe you face the exact same support issue already with the basic behavior of `brew pin`: if I install something that requires node 6, but I have node 4 pinned, I may actually be worse off than if I had no node at all. I can understand why `pin` would itself seem problematic. But once you have it in place, it seems entirely logical to use the feature to its logical conclusion: enabling the user to specify either a particular version of a package, _or no version at all._

I believe it's also well-addressed by simply exposing the feature in the shell output. On first `brew pin node`: "WARNING: by pinning an uninstalled formula (node), you will prevent it from being installed in the future, even if other formulae declare it as a dependency. Proceed?" And, next time I run something like `brew install yarn`: "WARNING: formula <node> was declared as a dependency of <yarn>, but you have pinned <node> as uninstalled. To re-enable homebrew's management of the dependency, please `brew unpin node`"  In fact, it would seem that those behaviors should be consistent whether someone has pinned a specific version of the dependency, or no version at all: the warnings are beneficial in either case. 

(For additional reference, here's a [really, really long thread](https://gist.github.com/DanHerbert/9520689) on challenges people face when running node through homebrew, and thus part of the context for why it's cleaner to run on nvm.)

**Comment by ilovezfs** [comment]
If you try to install something that depends on a formula pinned to a prior version, you will currently be blocked from doing so until you unpin. So that support issue does not currently exist.

**Comment by xml** [comment]
OK, Cool. So what if you simply extend that behavior to items that are pinned to no version? Same behavior, same U/X, just also supporting a version of "none" or `null` or whatever. That way, you'll be prompted to use `--ignore-dependencies` and it shouldn't be possible to accidentally install something unwanted.

**Comment by ilovezfs** [comment]
@xml without us changing anything, you can
```
brew install node
brew pin node
brew unlink node
```
and get basically the same behavior you're asking for.

**Comment by MikeMcQuaid** [comment]
> however many packages have post-install scripts that update your path after they run

This is not the case. We explicitly don't allow (through the macOS sandbox) packages/formulae to change anything that would affect your PATH in post-install.

> Further, isn't the point of Homebrew precisely to be able to manage your environment without lots of manual tinkering with dotfiles?

I don't think that's the point but it could be a valuable extension, I agree.

> For most folks, the PATH is essentially black-magic

I don't think this is the case for most Homebrew users.

> and get basically the same behavior you're asking for.

👍
