### ISSUE TITLE
Nested CAB containers fail on Warnings

### ISSUE THREAD

**Issue by joeyhoer** [Homebrew/brew#2688]
`cabextract` writes warnings (in addition to errors) to stderr, which prevents the correct container type from being detected, and thus throws an error.

The issue lies in the `.stderr.empty?` call here:
https://github.com/Homebrew/brew/blob/19347f3b87917368d7157fe5007d506a4db0c7db/Library/Homebrew/cask/lib/hbc/container/cab.rb#L13

When the test is run:

    # Write only stderr to stdout
    $ cabextract -t -- ~/Library/Caches/Homebrew/Cask/font-microsoft-office--latest/ppviewer.cab 2>&1 >/dev/null
    /Library/Caches/Homebrew/Cask/font-microsoft-office--latest/ppviewer.cab: WARNING; possible 5968 extra bytes at end of file.

I'm trying to install this formula (a font cask): https://github.com/joeyhoer/homebrew-extras/blob/master/Casks/font-microsoft-office.rb

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by joeyhoer** [comment]
Reopened at https://github.com/Homebrew/brew/issues/2689 following the template (I hope)
