### ISSUE TITLE
can not download the wget https://github.com/kersing/multitech-installer/raw/master/installer.sh --no-check-certificate

### ISSUE THREAD

**Issue by MWeidmann** [Homebrew/brew#2701]
we have a multitech multiconnect conduit and would like to donload the

wget https://github.com/kersing/multitech-installer/raw/master/installer.sh --no-check-certificate

it is not run:

admin@mtcdt:~# wget https://github.com/kersing/multitech-installer/raw/master/installer.sh --no-check-certificate
--2017-05-30 11:04:16--  https://github.com/kersing/multitech-installer/raw/master/installer.sh
Resolving github.com... failed: Name or service not known.
wget: unable to resolve host address 'github.com'

please help me..
best regards
Martin

**Comment by MikeMcQuaid** [comment]
This is nothing to do with Homebrew.
