### ISSUE TITLE
Custom user terminfo

### ISSUE THREAD

**Issue by choco** [Homebrew/brew#2707]
- [x] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

Hello, this is a continuation of issue https://github.com/Homebrew/legacy-homebrew/issues/48631
I debugged the issue and found that the error is caused by a call to `tput` here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/tty.rb#L9 used to determine the terminal width each time a message is printed with `ohai`.

`tput` prints that error because custom terminfo are installed in `$HOME/.terminfo` and homebrew overwrites the `HOME` variable during a formula installation. Possible solutions would be:
- use a different way to obtain columns
- silence the tput command (but then the truncate function wouldn't behave correctly)
- restore correct home value when executing this command

Is there an easy way to easily obtain the original HOME value?

**Comment by MikeMcQuaid** [comment]
We'll consider accepting a pull request to fix this but this is an issue with your personal configuration rather than for a majority of Homebrew users. Sorry!
