### ISSUE TITLE
brew install node installs old npm version

### ISSUE THREAD

**Issue by Sibiraj-S** [Homebrew/brew#2711]
recently node 8.0 is released with npm dependency 5.0.0.  [nodejs changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.0.0)

but when I install node with `brew install node`. node 8.0 is installed but with older `npm version`

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/14085
https://github.com/Homebrew/homebrew-core/pull/14091
https://github.com/Homebrew/homebrew-core/issues/14108
https://github.com/Homebrew/homebrew-core/issues/14128

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/14085.
