### ISSUE TITLE
undefined local variable or method `ruby_version' on macOS 10.13 beta

### ISSUE THREAD

**Issue by jnozsc** [Homebrew/brew#2737]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
```brew doctor```
- What happened (include command output)
```bash
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
Error: undefined local variable or method `ruby_version' for #<Homebrew::Diagnostic::Checks:0x007f8ce832a6a0>
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb:202:in `check_ruby_version'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
- What you expected to happen
no error
- Step-by-step reproduction instructions (by running `brew` commands)
install macOS 10.13 and run `brew doctor`

**Comment by DomT4** [comment]
Heh, I was wondering to myself how soon one of these issues would be opened 😄. I should have a VM working later today; will look at this unless Mike/ILZ/Misty/etc beat me to it.

**Comment by constXife** [comment]
As I see, this pretty old undiscovered bug. Someone just deleted variable with ruby version.

https://github.com/Homebrew/brew/commit/8a57fee68c4a52b371d94f878c2fac495fa1ff95#diff-04e700045721a197c725bc15b7f2a173L174

**Comment by walterpalladino** [comment]
Anyone get a solution for this?
