### ISSUE TITLE
Feature request: log pre/post-updated versions of packages

### ISSUE THREAD

**Issue by avetisk** [Homebrew/brew#2739]
**Context**: It happens that I launch a `brew upgrade` and then after few hours of work I notice that there's something wrong and after losing several hours or even days I end up with a package which version is not compatible with my current stack, etc.

**Solution**: On any upgrade, it would be great to log something like:
```
DATETIME:PACKAGE:VERSION_BEFORE_UPGRADE:VERSION_AFTER_UPGRADE
```

BONUS: We could even log any operation (linking, removing, etc.) on packages.

**Comment by MikeMcQuaid** [comment]
You could implement this yourself with a script that does `brew list --versions > before; brew upgrade; brew list --versions > after` or similar.

**Comment by woj-tek** [comment]
I know this is old-ish issue (and closed for that matter, but I decided not to open new one) but I have similar "issue". IMHO adding some information to the output of the upgrade regarding from which version the upgrade was performed would be helpful.

For example instead of:
```
==> Upgrading 4 outdated packages, with result:
mysql@5.5 5.5.59, ykpers 1.18.1, mysql 5.7.21, libtasn1 4.13
```
output
```
==> Upgrading 4 outdated packages, with result:
mysql@5.5 5.5.59 (from x.y.x)
ykpers 1.18.1 (from x.y.x)
mysql 5.7.21 (from x.y.x)
libtasn1 4.13 (from x.y.x)
```
or
```
==> Upgrading 4 outdated packages, with result:
mysql@5.5 x.y.x -> 5.5.59
ykpers x.y.x -> 1.18.1
mysql x.y.x -> 5.7.21
libtasn1 x.y.x -> 4.13
```

**Comment by ilovezfs** [comment]
`brew outdated` shows that information if you need it so you can run `brew outdated && brew upgrade`

**Comment by woj-tek** [comment]
Oh! Great - I've missed that one - thanks.

**Comment by ilovezfs** [comment]
You're welcome :)
