### ISSUE TITLE
Translating Homebrew

### ISSUE THREAD

**Issue by PortableDoor** [Homebrew/brew#2741]
Hi all,

I have been using Homebrew for a few weeks now; having had to switch to a Mac from a Linux machine, I have been extremely impressed by the work that has gone into this project.
However, I was wondering if any of you considered translating the software- or, if not, the manual itself, so that the software would be more understandable/accessible to those who do not speak English as their native language.

Personally I would be happy to help translate the program (or just the manual if you prefer) into French. However, my expertise with Ruby is only basic, hence I was wondering, were any of you to be interesting in having such a feature, if you would be able to assist me with doing so, were the idea to have the 'go ahead'.

Alternatively, if you think that having multiple languages under one program would take up too much space, or slow it down, perhaps a new translated program could be set up for each new language, (each on its own git page?) relying on the same repositories used for Homebrew of course! Following this idea, a separate 'curl' commands could be linked on your website, or something of the sort.

Thank you for having taken your time to read through this.
Any responses will be much appreciated :-)

**Comment by MikeMcQuaid** [comment]
We have a translation for our homepage: https://github.com/Homebrew/homebrew.github.io/blob/master/index_ar.html

Unfortunately to be able to start translating the application would be a major endeavour; we'd need to have a way to extract every user visible string and ensure they were translated. As a result we'd probably need someone to build that framework for us and provide a first translation before we could do this. We'd definitely review a pull request from you to do this but I'd understand if it's too much work. Sorry about this; I wish we could be better here.

**Comment by PortableDoor** [comment]
Hello Mike,

I apologise for such a late reply. I understand that you must be quite busy with other projects in mind. Although I cannot guaranty anything, could you perhaps tell me the general files I should look at modifying (mostly the ones that are going to have visible user output), were I to undertake the project by myself.
Thank you for your time.

**Comment by MikeMcQuaid** [comment]
@PortableDoor I'm afraid the answer to what files to look at are pretty much: all files. 😭
