### ISSUE TITLE
Unable to link Node

### ISSUE THREAD

**Issue by Dalan-Miller** [Homebrew/brew#276]
I am attempting to get node.js to run, I've installed it through brew. Brew doctor informs me that node is not linked. When I attempt to link node I get an error:

```
Dalans-MacBook-Pro:~ dalanmiller$ brew link node
Linking /usr/local/Cellar/node/6.1.0... 
Error: Could not symlink share/systemtap/tapset/node.stp
/usr/local/share/systemtap/tapset is not writable.
```

**Comment by DomT4** [comment]
Can you provide the full `brew doctor` output? Thanks

**Comment by Dalan-Miller** [comment]
`Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Warning: You have external commands with conflicting names.

Found command `brew-cask` in following places:
    /usr/local/bin/brew-cask
    /usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    node
    xz

Warning: Your Xcode (7.3) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.`

**Comment by UniqMartin** [comment]
Please also have a look at our [Troubleshooting Guide](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting), follow (all of) the steps therein, and post the requested information here so we can help you better with your problem. Thanks!

**Comment by Dalan-Miller** [comment]
Ok, I have a Gist if you need it: https://gist.github.com/anonymous/f675385468f52797722fe460e9dc3d21

**Comment by UniqMartin** [comment]
Have you tried following this advice from the [Check for common issues](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#check-for-common-issues) section of the document I linked you to?

- If things fail with permissions errors, check the permissions in `/usr/local`. If you’re unsure what to do, you can `sudo chown -R $(whoami) /usr/local`.

I believe this should resolve your trouble.

----

Regarding this output from `brew doctor`:

> ```
> Warning: You have external commands with conflicting names.
>
> Found command brew-cask in following places:
> /usr/local/bin/brew-cask
> /usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb
> ```

You can run `brew uninstall brew-cask`. It's no longer necessary to install `brew-cask` as a formula, as nowadays tapping `Caskroom/cask` is sufficient.

**Comment by Dalan-Miller** [comment]
> Have you tried following this advice from the Check for common issues section of the document I linked you to?

If things fail with permissions errors, check the permissions in /usr/local. If you’re unsure what to do, you can sudo chown -R $(whoami) /usr/local.
I believe this should resolve your trouble.

This worked, thank you!
