### ISSUE TITLE
Broken API docs site

### ISSUE THREAD

**Issue by mprzybylski** [Homebrew/brew#2760]
# Please always follow these steps:
- [ X] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [ X] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ X] Ran `brew config` and `brew doctor` and included their output with your issue?

http://www.rubydoc.info/github/Homebrew/brew/master/Formula returns an error page with the following message: 

> Oops,
We Couldn't Find That GitHub Project

**Comment by rwhogg** [comment]
It seems to work fine for me; maybe it was just a temporary glitch on Rubydoc's side?
