### ISSUE TITLE
Sha256 conflicts for binary resources - enable file name versioning

### ISSUE THREAD

**Issue by issmirnov** [Homebrew/brew#2765]
# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? - Yes, `brew reinstall` with any binary package.
- [X] Ran `brew update` and retried your prior step? - yes, this is what caused the issue
- [X] Ran `brew doctor`, fixed all issues and retried your prior step? - not needed, since IMo this is a core brew issue.
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.2.2-53-g8ad675790
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8ad675790deef80760fbcc1b5b644dad98a968b8
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2e3bec1594bd0bba12725e49a537754ad87896cb
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: N/A
X11: N/A
```
**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Expand a Feature

Hello team. I'd like to talk about the way binary assets are handled in formulas. I have a [small tap](https://github.com/issmirnov/homebrew-apps/blob/master/Formula/zap.rb) that contains a binary distribution (see [zap](https://github.com/issmirnov/zap)). As per official guidelines, I update the sha256 and version number with every release.

However, whenever I run `brew reinstall zap` I run into the following issue:

```
$ brew reinstall zap                                       
==> Reinstalling issmirnov/apps/zap 
==> Downloading https://github.com/issmirnov/zap/releases/download/v0.9.5/zap_MacOS_64-bit.tar.gz
Already downloaded: /Users/issmirnov/Library/Caches/Homebrew/zap-bit.tar.gz
Error: SHA256 mismatch
Expected: 3d2ab49bdb6b3917f31203f95cc2df77ab7dac64f83f9ef3c640b318b76a6620
Actual: 9993f0107739ef22164f23ea1d6d0818b9389d3fd9c434e29b998eb304c118e3
Archive: /Users/issmirnov/Library/Caches/Homebrew/zap-bit.tar.gz
To retry an incomplete download, remove the file above.
```

Is there a way to force the Formula to ignore old caches? The file name is always called `zap-bit.tar.gz` and I don't see any way to change that in the [official docs](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md). I feel that one of two solutions would work:

1. Include the version file in the `*-bit` name. This fills up the cache with old version, and should be handled by cleanup scripts
2. Allow Formula creators to specify download filename, and some flags indicating clobbering strategy.

Any help is appreciated. 

Thanks!

**Comment by MikeMcQuaid** [comment]
`brew audit issmirnov/apps/zap` points to the issue here; file name versioning does exist but your version was detected as `bit`. Instead you can specify it manually with `version`.

**Comment by issmirnov** [comment]
My bad, I somehow missed that in the docs. Thanks so much for the easy fix!
