### ISSUE TITLE
brew spits out tons of junk

### ISSUE THREAD

**Issue by IronCraftMan** [Homebrew/brew#277]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

When running any brew command, it spits out this line many times:

`/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777`

**Comment by MikeMcQuaid** [comment]
`chmod 775 /usr/local/bin`

**Comment by IronCraftMan** [comment]
Hi, this worked for that directory, but it decided to call out other directories including sbin, lib. etc. I decided to use `brew list` to get a list of installed packages, and just do `sudo rm -rf /usr/local`. It seems as if OS X 10.11 has messed up the permissions of /usr/local for me.

**Comment by MikeMcQuaid** [comment]
@IronCraftMan Glad you got it sorted!
