### ISSUE TITLE
"Checksum change requires version change" audit step inadvertently disabled?

### ISSUE THREAD

**Issue by follower** [Homebrew/brew#2774]
I may be mistaken _[see Postscript below]_ but it seems like 798af254667f6488cc6a1bb554f423d88f2a7b22 (via https://github.com/Homebrew/brew/pull/2601) may have inadvertently disabled the version/checksum audit step **(intended to avoid malware)** for the `audit` command when a change was made (for the `_audit_modified_casks` command?):

```diff
--- a/Library/Homebrew/cask/lib/hbc/audit.rb
+++ b/Library/Homebrew/cask/lib/hbc/audit.rb
@@ -66,6 +66,7 @@ def check_version_and_checksum
       tap = Tap.select { |t| t.cask_file?(@cask.sourcefile_path) }.first
       return if tap.nil?
 
+      return if commit_range.nil?
       previous_cask_contents = Git.last_revision_of_file(tap.path, @cask.sourcefile_path, before_commit: commit_range)
       return if previous_cask_contents.empty?
```

## Contributing factors

A contributing factor to this concern is that [`last_revision_commit_of_file()` in `Library/Homebrew/utils/git.rb`](
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/git.rb#L7) appears to specifically handle the possibility of `before_commit` being `nil`:

```ruby
# ...
args = [before_commit.nil? ? "--skip=1" : before_commit.split("..").first]
# ...
```

## Callers and `commit_range`

As far as I can tell, the `audit` command (in [`Library/Homebrew/cask/lib/hbc/cli/audit.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/cli/audit.rb#L24)
) implementation never includes a `commit_range` value so the check will always be skipped:

```ruby
# ...
 Auditor.audit(cask, audit_download: download?, check_token_conflicts: token_conflicts?)
# ...
```

In contrast, the `_audit_modified_casks` (in 
[`Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb#L91)) always supplies a `commit_range` value--although it may not have been populated on the command line:

```ruby
# ...
        success = Auditor.audit(cask, audit_download:        audit_download,
                                      check_token_conflicts: check_token_conflicts,
commit_range: commit_range)
# ...
```

## The remainder of the program flow

The related code in `Auditor` (in [`Library/Homebrew/cask/lib/hbc/auditor.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/auditor.rb#L51
)) passes along `commit_range`:

```ruby
#...
    def audit_cask_instance(cask)
      download = audit_download? && Download.new(cask)
      audit = Audit.new(cask, download:              download,
                              check_token_conflicts: check_token_conflicts?,
                              commit_range: commit_range)
      audit.run!
#...
```

And the check in question is in `check_version_and_checksum()` (in [`Library/Homebrew/cask/lib/hbc/audit.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/audit.rb#L63)):

```ruby
# ...
    def check_version_and_checksum
# ...
      return if commit_range.nil?
      previous_cask_contents = Git.last_revision_of_file(tap.path, @cask.sourcefile_path, before_commit: commit_range)
# ...
```

## Unrelated code

As far as I can tell, the following `audit` related functionality is not involved:

 * https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L742
 * https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_versions.rb#L67

## Postscript

[_Please note:_

_I noticed this potential issue while working on https://github.com/caskroom/homebrew-cask/pull/35389._

_Apologies for the incomplete and unverified report but I've already taken a significant amount of time to research and write-up this potential issue due its security-related nature._

_Normally I would try to verify that the issue actually exists and isn't just my misunderstanding of the code but I've already spent too much time on this and am unable to invest any more. I hope someone more familiar with the project/code/language can quickly determine if further investigation is warranted despite the incomplete report._

FWIW I found the number of similarly-named files (often differing only in a few characters in their file path), amount of abstraction and lack of internal file/class documentation made reasoning about how this code worked more difficult than one would hope.]

 

# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new _(No. See Postscript above.)_
- [ ] Ran `brew update` and retried your prior step? _(No. See Postscript above.)_
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step? _(No. See Postscript above.)_
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue? _(No. See Postscript above.)_

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
_(See Postscript above.)_
- What happened (include command output)
_(See Postscript above.)_
- What you expected to happen
_(See Postscript above.)_
- Step-by-step reproduction instructions (by running `brew` commands)
1. Change checksum of cask but not the version number.
2. Run cask audit command.
3. ???
_(See Postscript above.)_

**Comment by reitermarkus** [comment]
It was a deliberate decision to only run this audit check on CI, as to not discourage users from still submitting an update to a Cask, even though it may need verification.

**Comment by follower** [comment]
Thank you for clarifying the situation.

> It was a deliberate decision to only run this audit check on CI

Was this the discussion that occurred in https://github.com/Homebrew/brew/pull/2601? If so, I saw that discussion but apparently interpreted this comment incorrectly: https://github.com/Homebrew/brew/pull/2601#issuecomment-300644161.

Can I suggest that given this is connected to security-related functionality that the deliberate decision is documented in either the commit and/or in a code comment? (i.e. specify the *why* not just the what.)

Outside of "institutional knowledge" there's nothing obvious in `return if commit_range.nil` to indicate the check is connected to Continuous Integration and deliberately not intended to be run locally. It would be nice to save the next person that notices a few hours investigation & documentation...

**Comment by reitermarkus** [comment]
It was this comment, actually: https://github.com/Homebrew/brew/pull/2601#issuecomment-300500121

> Can I suggest that given this is connected to security-related functionality that the deliberate decision is documented in either the commit and/or in a code comment?

Would be great if you could submit a PR since you probably know best which kind of comment would have deterred you from digging deeper into this.

**Comment by MikeMcQuaid** [comment]
> It was a deliberate decision to only run this audit check on CI, as to not discourage users from still submitting an update to a Cask, even though it may need verification.

I'll reiterate that I think this is a bad idea and the messaging could just state what you've done here (i.e. please still submit this but it will need verified upstream).
