### ISSUE TITLE
Error: Your Xcode (8.3.3) is too outdated.

### ISSUE THREAD

**Issue by spyhole** [Homebrew/brew#2779]
<img width="585" alt="default" src="https://user-images.githubusercontent.com/1698342/27066394-53660382-4fc9-11e7-88f3-3ca8f9b39be0.png">

**Comment by JCount** [comment]
**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**
(Your Xcode is outdated, as it says)
