### ISSUE TITLE
How to create unversioned links in /usr/local for versioned formulas?

### ISSUE THREAD

**Issue by whenov** [Homebrew/brew#2783]
I was trying to install gcc@4.9, but I can't use it through `gcc` unless I manually created the link. Even so, the libraries like `libstdc++.so`, etc. are not linked.

Is there a way to create unversioned links in /usr/local automatically? If not, how is this problem usually solved? Thanks!

**Comment by MikeMcQuaid** [comment]
> Is there a way to create unversioned links in /usr/local automatically?

No, sorry. You can do so manually anywhere else in your PATH or use shell `alias`es.
