### ISSUE TITLE
Brew doctor showing errors

### ISSUE THREAD

**Issue by ngerasimatos** [Homebrew/brew#2785]
# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [ X] Ran `brew update` and retried your prior step?
- [X ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

➜  ~ brew doctor --verbose
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Found Ruby file outside telemachus/anytap tap formula directory
(/usr/local/Homebrew/Library/Taps/telemachus/homebrew-anytap/Formula):
  /usr/local/Homebrew/Library/Taps/telemachus/homebrew-anytap/brew-any-tap.rb
  /usr/local/Homebrew/Library/Taps/telemachus/homebrew-anytap/brew-any-untap.rb

  ~ brew config --verbose

HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ac7ed4720e96ffc74c88a13552826b167a75f20d
Core tap last commit: 13 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_152
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A

**Comment by apjanke** [comment]
According to [its README](https://github.com/telemachus/homebrew-anytap/blob/master/README.md), `telemachus/anytap` is obsolete because its functionality is now included in `brew tap`. You can just untap it.

**Comment by MikeMcQuaid** [comment]
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!
