### ISSUE TITLE
Please add bashate package

### ISSUE THREAD

**Issue by austin987** [Homebrew/brew#2789]
Hi there,

Sorry if this isn't the place for feature requests, I read through main page and looked on Google, didn't see a better place.

I'd like to request packaging of bashate (https://github.com/openstack-dev/bashate), It's pep8 style warnings for bash code. It's useful for finding:
if foo
then

rather than `if foo ; then` statements, etc. in bash code. I would like to add this to winetrick's TravisCI tests, but since OSX doesn't have it, that complicates things a bit. It would be nice if I could run this on OSX or Linux.

**Comment by vitorgalvao** [comment]
This is the core code for Homebrew. You’re looking for [the main formulae repo](https://github.com/Homebrew/homebrew-core/), where formulae actually are.

But even then, the tool you’re asking for seems to not be too popular (judging by the amount of stars), and [as the issue template states](https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE.md), PRs are preferred to issues requesting.

You’ll likely get more luck by contacting the developers and asking them for help with making a formula that you can submit.

**Comment by austin987** [comment]
Thanks @vitorgalvao, that's very helpful.
