### ISSUE TITLE
It seems that `cleanup` removes `/usr/local/etc/my.cnf.d`

### ISSUE THREAD

**Issue by kud** [Homebrew/brew#2792]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Ran mariadb via `mysql.server start`

## What happened (include command output)

Can't start

`./usr/local/Cellar/mariadb@10.1/10.1.24/bin/my_print_defaults: Can't read dir of '/usr/local/etc/my.cnf.d' (Errcode: 2 "No such file or directory")`

## What you expected to happen

Start with success

## Step-by-step reproduction instructions (by running `brew` commands)

- `brew install mariadb`
- `brew cleanup`
- `mysql.server start`

## `brew doctor`

```
brew doctor                                                                                                                                         fix-deputy ✭
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/kud/.pyenv/shims/python-config
  /Users/kud/.pyenv/shims/python2-config
  /Users/kud/.pyenv/shims/python2.7-config
  /Users/kud/.pyenv/shims/python3-config
  /Users/kud/.pyenv/shims/python3.6-config
  /Users/kud/.pyenv/shims/python3.6m-config

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  mariadb@10.1
```

**Comment by MikeMcQuaid** [comment]
Is this directory empty or a symlink?

**Comment by kud** [comment]
It doesn't exist at all and I have to do `mkdir /usr/local/etc/my.cnf.d` to work it again. :)

**Comment by MikeMcQuaid** [comment]
> Ran brew config and brew doctor and included their output with your issue?

You didn't do this. Please do it (and don't check the box saying you did).

> If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

This is a formula specific problem but we'll deal with this here for now anyway.

**Comment by kud** [comment]
brew doctor added.

Understand that fixing these "troubles" in brew doctor doesn't change anything. And mariadb@10.1 or mariadb have the same trouble.

**Comment by kud** [comment]
I think it could be related to https://github.com/Homebrew/legacy-homebrew/issues/31760

**Comment by MikeMcQuaid** [comment]
Please try to `brew reinstall mariadb@10.1` and see if you can still reproduce.

**Comment by tbnv** [comment]
This problem still occurs, with the same characteristics as above, but I think it's more a `prune` issue.

**Comment by miguelavaqrod** [comment]
I can confirm it still occurs.
my.cf.d is deleted when doing cleanup tasks.
Thanks in advance.

**Comment by MikeMcQuaid** [comment]
You need to add a file into `/usr/local/etc/my.cnf.d` for it not to be pruned.
