### ISSUE TITLE
Could brew stage the new build before unlinking the old one?

### ISSUE THREAD

**Issue by vlovich** [Homebrew/brew#2796]
# Or propose a feature:
It would be neat if homebrew could do upgrades without uninstalling the current version so that the downtime of the availability of an upgraded tool/library could be minimized to the duration it takes to copy/link the new version into the correct place.

An example if brew upgrade wine which takes about 30-60 minutes to upgrade (including dependencies that need to be upgrades like openssl, libtiff, libjpeg, etc).  If the build could be happening without unlinking the old version that would make brew upgrade much less painful to run regularly.  This is similar to how a lot of binary packages work (they uninstall the old version only once they've downloaded & verified the new one).

Obviously there are disk space implications so there should be some kind of preference/command-line option to enable it.  For example, if disk space is below X, then require the an explicit argument to brew upgrade to do it while keeping the old files.  X could be something simple like size of homebrew + 2 GB as a "safe" default.

**Comment by ilovezfs** [comment]
This has caused issues in the past, so probably not: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/upgrade.rb#L132-L134

**Comment by scpeters** [comment]
You could at least `brew fetch --deps` before installation so you don't have to wait for the download time.

**Comment by apjanke** [comment]
Doing an implicit `fetch --deps` seems useful (I personally would like having it), and we've discussed it before; just haven't found the developer time to implement.

Previous discussion here: https://github.com/Homebrew/legacy-homebrew/issues/48986

**Comment by MikeMcQuaid** [comment]
> Please replace this section with a detailed description of your proposed feature, the motivation for it, how it would be relevant to at least 90% of Homebrew users and alternatives considered. Please note we will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

Please follow this description in future.



> If the build could be happening without unlinking the old version that would make brew upgrade much less painful to run regularly.



> You could at least brew fetch --deps before installation so you don't have to wait for the download time.

These are both things that would be useful if they work widely but they aren't being worked on actively at this time so we'd need someone to volunteer and do so.

**Comment by scpeters** [comment]
For the fetch before install idea, I tried naively adding some `system(["brew", "fetch", ...])` commands in `install.rb`, but I don't think it will pass along flags like `--build-from-source` or `--HEAD`. It didn't seem ready for a pull request to me, so I didn't submit one, but the branch is here:

* https://github.com/Homebrew/brew/compare/master...scpeters:fetch_before_install

I guess I could just manually set the relevant arguments like is done in the previous cask section?

**Comment by MikeMcQuaid** [comment]
@scpeters we'd need something that's not shelling out but instead calls the current code. This probably needs some untangling in formula-installer. Note that resources will still not necessarily be downloaded until they are staged; that may need to be another feature.

**Comment by scpeters** [comment]
Gotcha, this seemed a little too easy. :)
