### ISSUE TITLE
Add per command help for cask

### ISSUE THREAD

**Issue by maxnordlund** [Homebrew/brew#2798]
I while back I implemented help-per-command, it would be nice if that was also the case for `brew cask`. I briefly looked into the code and there's a help system already in place so if @reitermarkus could help explain a bit what's going on I could add the help text á la the `brew` commands.

Sounds good?

**Comment by apjanke** [comment]
Might want to hold off on this for a bit. There's a GSoC project to re-do help text support in terms of option-definition DSL over at #2420.

**Comment by MikeMcQuaid** [comment]
Basically `brew cask` will need to support the same `#:`-prefixed magic comments. @reitermarkus and @maxnordlund feel free to chat in here but it's not actionable for maintainers as-is so closing.

**Comment by maxnordlund** [comment]
@apjanke that's some cool stuff. Yeah I guess I'm a bit late to the party, but right now if you type `brew cask <cmd> --help` you get the general help for `brew`, not `brew cask`.

Anyway, I'm happy to help if needed but waiting for #2420 seems reasonable to me.
