### ISSUE TITLE
brew search isn't as useful as in other package managers

### ISSUE THREAD

**Issue by crowell** [Homebrew/brew#2799]
# Feature Request

homebrew's search feature is not so useful, when there are often name collisions.

homebrew should provide a description of what the package is when I search.

for example, with apt, searching for "trafficserver" provides 

```
$ apt-cache search trafficserver
trafficserver - fast, scalable and extensible HTTP/1.1 compliant caching proxy server
```

but searching with brew I only get

```
$ brew search trafficserver
trafficserver
```
In order to get the actual descriptions, I have to run `brew info trafficserver`

```
$ brew info trafficserver
trafficserver: stable 7.0.0 (bottled), HEAD
HTTP/1.1 compliant caching proxy server
```

It would be very useful if brew search would give output in the form
`name : description`
so in this case
`trafficserver : HTTP/1.1 compliant caching proxy server`

**Comment by crowell** [comment]
it seems like `brew search --desc` does almost what I want, but turns out it *only* searches in descriptions, not in titles too!

eg: `brew search trafficserver` finds nothing

so I guess this issue is to make  --desc the default type of search, i'll open another issue for the --desc not searching titles

**Comment by MikeMcQuaid** [comment]
> so I guess this issue is to make --desc the default type of search

We can't change this now, the command-line interface is our main API so we can't change the format. I guess an alternative would be do something clever like detect if the stdout is a pipe or redirected to a file and not output descriptions in that case. Regardless, we'd need a PR rather than issue for that.

> i'll open another issue for the --desc not searching titles

Please open a PR instead of an issue, thanks.

**Comment by crowell** [comment]
detecting if stdout is a pipe or redirection can be done with `IO#tty?`, but this really doesn't work in a lot of situations, like `brew search blah | grep blah`, which i can imagine would be useful, no?

I don't think it's great to just open a PR without first deciding what the change has to be. This isn't as much an engineering issue as it is a ux one.

**Comment by MikeMcQuaid** [comment]
> I don't think it's great to just open a PR without first deciding what the change has to be.

We generally disagree on Homebrew; code is easier to discuss.

> but this really doesn't work in a lot of situations

In which case this change may not be useful at all.
