### ISSUE TITLE
brew search --desc should search titles as well as descriptions

### ISSUE THREAD

**Issue by crowell** [Homebrew/brew#2800]
# feature request

searching with `brew search --desc` seems to *only* search descriptions, and ignores the title.

often when searching for a package, I think i know the name, but want to see the description to make sure that I'm finding the right package.

so searching `brew search --desc trafficserver` I'd like to see the output 

```
trafficserver: HTTP/1.1 compliant caching proxy server
```
but instead, there is no output, because brew is only searching the desciption, and not searching the title.

**Comment by crowell** [comment]
so i guess the patch would be

```diff
diff --git a/Library/Homebrew/cmd/search.rb b/Library/Homebrew/cmd/search.rb
index b2d069744..ee52d17b4 100644
--- a/Library/Homebrew/cmd/search.rb
+++ b/Library/Homebrew/cmd/search.rb
@@ -40,7 +40,7 @@ module Homebrew
     elsif ARGV.include? "--desc"
       query = ARGV.next
       regex = query_regexp(query)
-      Descriptions.search(regex, :desc).print
+      Descriptions.search(regex, :either).print
     elsif ARGV.first =~ HOMEBREW_TAP_FORMULA_REGEX
       query = ARGV.first
       user, repo, name = query.split("/", 3)
```

**Comment by apjanke** [comment]
Searching only the descriptions seems natural to me for `--desc`. And if we changed how it searches, that might break an existing usage. (Though I'd be surprised if anything was actually using this in a way that would cause users problems.) Maybe we could add an `--either` or `--any` option instead. (`--any` might be more future-proof, in case some additional properties ever get added to the `Descriptions`.)

Regardless, adding this behavior makes sense to me; seems like a reasonable use case that's inconvenient to construct by combining multiple `brew search` calls.

**Comment by apjanke** [comment]
BTW, if you want to submit a simple patch, you can just go ahead and make it a PR. Easier to evaluate and merge. Plus you'll get credit in the commit history!

**Comment by crowell** [comment]
`--either` or `--any` as flags don't convey what the search is doing, and instead is talking about the code. so as a user it's kind of confusing, no?

how about -v or --verbose?

**Comment by JCount** [comment]
@crowell I believe `brew`'s current set of commands is capable of doing what you want, you are simply using the wrong cmd. From Homebrew's `manpage`:
```
  * `desc` [`-s`|`-n`|`-d`] (`text`|`/``text``/`):
    Search both name and description (`-s`), just the names (`-n`), or just  the
    descriptions (`-d`) for `text`. If `text` is flanked by slashes, it is interpreted
    as a regular expression. Formula descriptions are cached; the cache is created on
    the first search, making that search slower than subsequent ones.
```
so the command would be `brew desc -s trafficserver`.

Also, for future reference, please try to avoid opening multiple issues for the same thing.

**Comment by crowell** [comment]
ah, thanks, didn't notice that.

for the other issue, it's more about the default behavior. `brew search` as is, is kind of a very useless command... They're certainly two separate issues. Closing this one though, as `brew desc -s` does what I want.

**Comment by apjanke** [comment]
Seems a little odd that that functionality is in `brew desc` instead of `brew search`. Historical reasons? Maybe the `brew search` help text should have a "see also: brew desc" in it? I didn't know about this feature eitehr.

**Comment by JCount** [comment]
Part of it could have been an effort to avoid overloading the one command, or to take the vague idea of  "search" functionality, and separate/modularize it. After all, using the GitHub API, it will try and locate formulae and casks within Homebrew and Caskroom without needing to have anything beyond (probably) homebrew/core tapped.

**Comment by MikeMcQuaid** [comment]
> brew search as is, is kind of a very useless command.

That's not helpful, constructive language.
