### ISSUE TITLE
OSX 10.12 + error

### ISSUE THREAD

**Issue by 4593645** [Homebrew/brew#2810]
appledeMBP:wrt apple$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/etc

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/etc
Password:
mkdir: /usr/local/etc: Not a directory
Failed during: /usr/bin/sudo /bin/mkdir -p /usr/local/etc

**Comment by ilovezfs** [comment]
Maybe run `sudo chown -R $(whoami) /usr/local` and then try again.

**Comment by 4593645** [comment]
@ilovezfs 
appledeMBP:wrt apple$ sudo chown -R apple /usr/local/
Password:
appledeMBP:wrt apple$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/etc

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/etc
mkdir: /usr/local/etc: Not a directory
Failed during: /usr/bin/sudo /bin/mkdir -p /usr/local/etc
appledeMBP:wrt apple$

**Comment by ilovezfs** [comment]
what is the output of
```
ls -al /usr/local/
```

**Comment by 4593645** [comment]
@ilovezfs 
appledeMBP:wrt apple$ ls -al /usr/local/
total 104
drwxr-xr-x  16 apple  wheel    544  6 22 00:37 .
drwxr-xr-x@  9 root   wheel    306 12 16  2016 ..
drwxr-xr-x   2 apple  wheel     68  6 22 00:37 Cellar
drwxrwxr-x   2 apple  admin     68  6 22 00:37 Frameworks
drwxr-xr-x   2 apple  wheel     68  6 22 00:37 Homebrew
drwxr-xr-x  17 apple  staff    578  6  9 02:12 bin
-rwxrwxr--@  1 apple  admin  46737 12  3  2016 etc
drwxrwxr-x   3 apple  admin    102  5  3 00:48 include
drwxrwxr-x   4 apple  admin    136  5  3 00:48 lib
lrwxr-xr-x   1 apple  wheel     28 10 26  2016 mysql -> mysql-5.7.16-osx10.11-x86_64
drwxr-xr-x  12 apple  wheel    408 10 26  2016 mysql-5.7.16-osx10.11-x86_64
drwxr-xr-x   2 apple  wheel     68  6 22 00:37 opt
drwxr-xr-x   3 apple  wheel    102  2 15 06:03 remotedesktop
drwxrwxr-x   2 apple  admin     68  6 22 00:37 sbin
drwxrwxr-x   6 apple  admin    204  6 22 00:37 share
drwxrwxr-x   2 apple  admin     68  6 22 00:37 var
appledeMBP:wrt apple$

**Comment by ilovezfs** [comment]
OK, so that is the problem. Your `/usr/local/etc` is a file not a directory.

```
mv /usr/local/etc ~/etc-file
```
and then try again.

**Comment by ilovezfs** [comment]
@4593645 I'm assuming this is fixed now?

**Comment by 4593645** [comment]
@ilovezfs Yes, its good working. THKS!

**Comment by ilovezfs** [comment]
@4593645 Great. Now you can

```
sudo chown root:wheel /usr/local
```

Out of curiosity, what was in the etc file?
```
cat ~/etc-file
```

**Comment by 4593645** [comment]
@ilovezfs its long string
# By default normal clients are not limited because they don't receive data
# without asking (in a push way), but just after a request, so only
# asynchronous clients may create a scenario where data is requested faster
# than it can read.
#
# Instead there is a default limit for pubsub and slave clients, since
# subscribers and slaves receive data in a push fashion.
#
# Both the hard or the soft limit can be disabled by setting them to zero.
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60

# Redis calls an internal function to perform many background tasks, like
# closing connections of clients in timeout, purging expired keys that are
# never requested, and so forth.
#
# Not all tasks are performed with the same frequency, but Redis checks for
# tasks to perform according to the specified "hz" value.
#
# By default "hz" is set to 10. Raising the value will use more CPU when
# Redis is idle, but at the same time will make Redis more responsive when
# there are many keys expiring at the same time, and timeouts may be
# handled with more precision.
#
# The range is between 1 and 500, however a value over 100 is usually not
# a good idea. Most users should use the default of 10 and raise this up to
# 100 only in environments where very low latency is required.
hz 10

# When a child rewrites the AOF file, if the following option is enabled
# the file will be fsync-ed every 32 MB of data generated. This is useful
# in order to commit the file to the disk more incrementally and avoid
# big latency spikes.
aof-rewrite-incremental-fsync yes

**Comment by ilovezfs** [comment]
And how about

```
xattr -l ~/etc-file
```

**Comment by 4593645** [comment]
@ilovezfs 
appledeMBP:~ apple$ xattr -l ~/etc-file
com.apple.TextEncoding: utf-8;134217984
com.apple.metadata:kMDLabel_52l5oz2hxjijdrv7mnc2q562pm:
00000000  F2 36 31 15 68 CC 9C FA 57 24 8A AD 70 7D 8D 94  |.61.h...W$..p}..|
00000010  00 CE CC F2 18 29 C1 EF CF 0D D0 B6 77 5D AF BF  |.....)......w]..|
00000020  8D 77 60 7C A8 B1 5E AA 6B 3C 1C C2 26 09 93 2E  |.w`|..^.k<..&...|
00000030  46 3B D7 6A 15 7A 57 F7 9C 43 AD B4 4B C9 11 15  |F;.j.zW..C..K...|
00000040  CA 41 16 40 2B 43 C7 D0 ED 9A 38 45 45 CE A4 FC  |.A.@+C....8EE...|
00000050  DB 9C F9 43 C2 28 99 87 87 71 37 01 24 CB 0F E7  |...C.(...q7.$...|
00000060  CA 6A A3 6D 22 46 2A 90 68                       |.j.m"F*.h|
00000069
appledeMBP:~ apple$

**Comment by ilovezfs** [comment]
@4593645 thanks. So I guess you must have installed redis at some point? If so, from where?

**Comment by 4593645** [comment]
@ilovezfs Yes , Redis on System.
