### ISSUE TITLE
Your Xcode is too outdated while attempting to install brew packages

### ISSUE THREAD

**Issue by ruchern** [Homebrew/brew#2812]
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

## Brew config
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b1a20488ab08fe888a0deadb584cc2394f5c8608
Core tap last commit: 87 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 8.1 build 802
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: 8.3.3
CLT: 9.0.0.0.1.1497666128
X11: N/A

## What are you trying to do
Running `brew install` will throw an error pertaining to a Xcode issue.

```
Error: Your Xcode (8.3.3) is too outdated.
Please update to Xcode 9.0 (or delete it).
Xcode can be updated from
  https://developer.apple.com/download/more/
```

## What do you expect to happen
`brew install` should work normally and not being affected by Xcode.

## How to reproduce
Just run the install command for any packages will result in the error. It seemed like Xcode is taking precedence over anything else.

**Comment by MikeMcQuaid** [comment]
> Your Xcode (8.3.3) is too outdated.

It is.

**Comment by ruchern** [comment]
@MikeMcQuaid Is there not workaround to use Xcode 8.3.3 as default?

**Comment by vitorgalvao** [comment]
@ruchern I’m unsure about this, but I’d say the issue lies in your mismatch of the Xcode command-line tools (CLT) with Xcode itself. They have a full major version of difference.

**Comment by ruchern** [comment]
@vitorgalvao It's alright now. I have downloaded Xcode 9 beta 2 from my developer's account and it now works.

**Comment by MikeMcQuaid** [comment]
@ruchern It's not supported on the macOS beta.

**Comment by ruchern** [comment]
@MikeMcQuaid Yes, apparently macOS High Sierra requires a minimum of Xcode 9 now.

**Comment by vitorgalvao** [comment]
@ruchern I think that (at least) since macOS changed to an yearly update schedule that has been the case. They always present the new macOS and Xcode versions at WWDC.

**Comment by thepatrick** [comment]
FWIW Xcode 8.3.3 still works just fine on High Sierra.

The message is misleading, Xcode 8.3.3 is not outdated. If the issue is that there is mismatch between cli tools & the current xcode at `xcode-select --print-path`, then it should say that instead.

**Comment by ilovezfs** [comment]
@thepatrick we require that Xcode 9 be used regardless of whether it still works just fine.

**Comment by ruchern** [comment]
@thepatrick Apparently the 8.3.3 on High Sierra is blocking me from installing packages, so I don't think it could just be as simple as that of yours.

If anyone is curious, I was trying to install `asciinema`.
