### ISSUE TITLE
Homebrew should respect the active Xcode

### ISSUE THREAD

**Issue by jmoody** [Homebrew/brew#2833]
# Please always follow these steps:

- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

### Reproduce

1. Install Xcode 9.0 beta
2. Install Xcode 8.3.3
3. `$ sudo xcode-select --switch /Xcode/8.3.3/Xcode.app/Contents/Developer`
4. `$ brew upgrade`

### Expected

Brew to upgrade using the Xcode 8.3.3 toolchain.

### Found

```
$ brew upgrade
Error: Your Xcode (8.3.3) is too outdated.
Please update to Xcode 9.0 (or delete it).
Xcode can be updated from
  https://developer.apple.com/download/more/
```

### Notes

From the config, Homebrew detects Xcode 8.3.3  is the active Xcode.

```
$ brew config
HOMEBREW_VERSION: 1.2.3
<snip>
Xcode: 8.3.3 => /Xcode/8.3.3/Xcode.app/Contents/Developer
<snip>
```

Is there some way to tell homebrew to use a particular Xcode?

### Related

* https://github.com/Homebrew/brew/pull/2736

### Required

```
$ brew config
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6b31936eee598557390e9b33929b493578f10269
Core tap last commit: 57 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 8.1 build 802
Git: 2.13.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/moody/.rbenv/shims/ruby => /Users/moody/.rbenv/versions/2.3.1/bin/ruby
Java: 1.8.0_101
macOS: 10.13-x86_64
Xcode: 8.3.3 => /Xcode/8.3.3/Xcode.app/Contents/Developer
CLT: N/A
X11: N/A
```

```
$ brew doctor
Warning: Your Xcode (8.3.3) is outdated.
Please update to Xcode 9.0 (or delete it).
Xcode can be updated from
  https://developer.apple.com/download/more/

If 9.0 is installed, you may need to:
  sudo xcode-select --switch /Applications/Xcode.app
Current developer directory is:
  /Xcode/8.3.3/Xcode.app/Contents/Developer
```

**Comment by ilovezfs** [comment]
This is intentional, as we require the use of Xcode 9 on 10.13. Thanks for reporting, though!

**Comment by jmoody** [comment]
I am suggesting this the _wrong_ behavior.

**Comment by ilovezfs** [comment]
@jmoody fair enough. Nonetheless, it's what we intentionally require.

**Comment by MikeMcQuaid** [comment]
> Is there some way to tell homebrew to use a particular Xcode?

To answer this specific question: no. We intentionally require Xcode 9 on High Sierra.

**Comment by afallon02** [comment]
Is this due to it having support for APFS? Or just personal choice to go with latest version. Its a huge download and a pain in the buttocks to have it installed alongside 8.3.3

**Comment by ilovezfs** [comment]
You're using a beta OS which means you need a beta Xcode.

**Comment by afallon02** [comment]
Patently false. The beta OS isn't inclusive of a new version of Xcode and there are perfectly valid reasons to update OS but not update Xcode.

**Comment by MikeMcQuaid** [comment]
> Patently false. The beta OS isn't inclusive of a new version of Xcode and there are perfectly valid reasons to update OS but not update Xcode.

A lot of things Homebrew installs will break if you use Xcode 8.3 so we require a newer version. Feel free to use whatever Xcode you wish but we don't support it.
