### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by sayan-sibyl** [Homebrew/brew#2834]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

Issue
Sayans-iMac:~ sayanhussain$ brew install ettercap --with-gtk+
==> Using the sandbox
==> Downloading https://github.com/Ettercap/ettercap/archive/v0.8.2.tar.gz
Already downloaded: /Users/sayanhussain/Library/Caches/Homebrew/ettercap-0.8.2.tar.gz
==> Downloading https://github.com/Ettercap/ettercap/commit/4ad7f85d.patch
Already downloaded: /Users/sayanhussain/Library/Caches/Homebrew/ettercap--patch-a53322b8f103d92e3947b947083e548a92e05c0c2814ee870ec21a31eb0035c3.patch
Error: SHA256 mismatch
Expected: a53322b8f103d92e3947b947083e548a92e05c0c2814ee870ec21a31eb0035c3
Actual: c26177ce5729518754fb4c6cc31e9f2ec49205db5b7273c18b861b4e64d8237f
Archive: /Users/sayanhussain/Library/Caches/Homebrew/ettercap--patch-a53322b8f103d92e3947b947083e548a92e05c0c2814ee870ec21a31eb0035c3.patch
To retry an incomplete download, remove the file above.

**Comment by ilovezfs** [comment]
This is the same as https://github.com/Homebrew/homebrew-core/pull/13792. Thank you for reporting this. I'll take care of it.

**Comment by sayan-sibyl** [comment]
So what should I do now?

**Comment by ilovezfs** [comment]
@sayan-sibyl if you `brew update` it should be fixed.

**Comment by sayan-sibyl** [comment]
I have tried that

**Comment by sayan-sibyl** [comment]
u r awesome bro it's fixed

**Comment by ilovezfs** [comment]
Hehe thanks! I'm glad it's working again.

**Comment by sayan-sibyl** [comment]
ok now If I completely remove all the home-brew files caches and reinstall it fresh and install ettercap again will I have the same problem again

**Comment by sayan-sibyl** [comment]
btw do u know what does this signify? SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to EUID 65534 EGID 65534...

**Comment by ilovezfs** [comment]
>will I have the same problem again

Nope.

**Comment by ilovezfs** [comment]
>btw do u know what does this signify? SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
>Privileges dropped to EUID 65534 EGID 65534...

No idea, but upstream may know.

**Comment by sayan-sibyl** [comment]
upstream?

**Comment by ilovezfs** [comment]
https://github.com/Ettercap/ettercap
