### ISSUE TITLE
Error while install wine, 404 at remote endpoint for dependency

### ISSUE THREAD

**Issue by jeremyrajan** [Homebrew/brew#284]
Hi,

I have been trying to install wine and it always comes out with 404 errors on one of its dependencies (its libpng)

![image](https://cloud.githubusercontent.com/assets/2890683/15612768/b3714fcc-2462-11e6-8b01-79ed64893bf5.png)

I tried `brew update` but no luck. Any idea?

Any help with will be appreciated.

Thank you!

**Comment by UniqMartin** [comment]
> I tried `brew update` but no luck. Any idea?

What do you mean by that? What's the output of `brew update` and of `brew config`? If your Homebrew is trying to download `libpng` 1.6.18, that means it hasn't been updated in more than six months.

**Comment by ilovezfs** [comment]
My guess is this is a failed migration to brew+homebrew/core.

**Comment by MikeMcQuaid** [comment]
@jeremyrajan Can you paste the output from running `brew update` again? Thanks!

**Comment by jeremyrajan** [comment]
Hi guys,

Apologies for the late reply. It was failing when i tried 'brew update'. In the end what I did was remove brew completely and then install again. That fixed the issue :)

Not sure, why it was happening though. 

Cheers,
Jeremy

**Comment by MikeMcQuaid** [comment]
Glad it's fixed, thanks!
