### ISSUE TITLE
ENV variable to change logs directory

### ISSUE THREAD

**Issue by olosegres** [Homebrew/brew#2844]
I use brew with few system users, via `sudo -u share`, but it's not working correctly, because brew (or macos?) want to write logs to `/Users/notShareUser/Library/Logs`.

Is it possible to change log dir path to another?

To make this alias command work as planned?
`alias brew='sudo -u share HOMEBREW_CACHE=/tmp HOMEBREW_LOG_PATH=/tmp/brew_logs brew'`

**Comment by MikeMcQuaid** [comment]
We do not support running Homebrew in that configuration. That said, `HOMEBREW_LOGS` may be of use to you (it's documented in `man brew`).
