### ISSUE TITLE
Non-strict audits should not cause CI failure (even if they happen to be implemented as cops)

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#2847]
Because [BrewTestBot calls `brew style foo`](https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L832-L836), any audits that have been moved to cops will cause CI to fail, even if they have been explicitly designated as `--strict` audits, which by definition should not cause CI failure (except for new formulae).

So, for example,

```
iMac-TMP:~ joe$ brew audit qemu
iMac-TMP:~ joe$ brew style qemu
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qemu.rb ==
C:  2:  9: Description should start with a capital letter

1 file inspected, 1 offense detected
iMac-TMP:~ joe$ brew audit --strict qemu
qemu:
  * C: 2: col 9: Description should start with a capital letter
Error: 1 problem in 1 formula
iMac-TMP:~ joe$
```

This makes the "description should start with a capital letter" audit fatal for CI even though it was supposed to be a `--strict` failure only.

CC @GauthamGoli @JCount @MikeMcQuaid

**Comment by GauthamGoli** [comment]
I had this in pipeline. Will figure out and push a fix.

**Comment by ilovezfs** [comment]
Thanks @GauthamGoli!

**Comment by JCount** [comment]
@GauthamGoli Great response time! 👍

**Comment by MikeMcQuaid** [comment]
I think ideal behaviour would have a plain 'rubocop' still flag these up but not 'brew style' (so they still show up in editor)

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/issues/2853.
