### ISSUE TITLE
ipython is linked to python 3 not python 2

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/brew#2849]
I installed ipython with `brew install ipython`. It seems like homebrew chose to use the python 3 library. In my path, I have the option to use `ipython` or `ipython3`. It seems like something went wrong. Is this the intended behavior? Why is there no `ipython2`? I tried uninstalling `brew uninstall --force ipython` then reinstalling `brew install ipython` but this behavior persists.

    $ which ipython
    /usr/local/bin/ipython
    
    $ ipython
    Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
    Type 'copyright', 'credits' or 'license' for more information
    IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

    $ /usr/local/Cellar/ipython/6.1.0/bin/ipython
    Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
    Type 'copyright', 'credits' or 'license' for more information
    IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
        
    $ cat /usr/local/Cellar/ipython/6.1.0/INSTALL_RECEIPT.json 
    {"homebrew_version":"1.2.2-59-gaa364fbf1","used_options":[],"unused_options":[],"built_as_bottle":true,"poured_from_bottle":true,"installed_as_dependency":false,"installed_on_request":true,"changed_files":["libexec/bin/easy_install","libexec/bin/easy_install-3.6","libexec/bin/iptest","libexec/bin/iptest3","libexec/bin/ipython","libexec/bin/ipython3","libexec/bin/pip","libexec/bin/pip3","libexec/bin/pip3.6","libexec/bin/pygmentize","libexec/bin/python-config","libexec/bin/wheel","libexec/lib/python3.6/site-packages/pip/_vendor/appdirs.py","libexec/lib/python3.6/site-packages/pkg_resources/_vendor/appdirs.py","INSTALL_RECEIPT.json","libexec/bin/activate","libexec/bin/activate.csh","libexec/bin/activate.fish","libexec/lib/python3.6/orig-prefix.txt","libexec/lib/python3.6/site-packages/IPython/core/application.py","libexec/lib/python3.6/site-packages/IPython/core/magics/osm.py","libexec/lib/python3.6/site-packages/IPython/utils/tests/test_path.py","libexec/lib/python3.6/site-packages/pexpect/run.py","libexec/lib/python3.6/site-packages/pip/cmdoptions.py","libexec/lib/python3.6/site-packages/pip/locations.py","libexec/lib/python3.6/site-packages/setuptools/ssl_support.py","libexec/lib/python3.6/site.py"],"time":1498793471,"source_modified_time":1496270262,"HEAD":null,"stdlib":null,"compiler":"clang","runtime_dependencies":[{"full_name":"python3","version":"3.6.1"}],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ipython.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"6.1.0","devel":null,"head":"HEAD","version_scheme":0}}}

    $ brew gist-logs ipython
    Error: No logs.
    $ brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!
    
    Warning: Unbrewed dylibs were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.
    
    Unexpected dylibs:
      /usr/local/lib/libadjoint.2016.2.0.dylib
      /usr/local/lib/libdolfin.2017.2.0.dev0.dylib
      /usr/local/lib/libmap-1.20.10.dylib
    
    Warning: Unbrewed header files were found in /usr/local/include.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.
    
    Unexpected header files:
      /usr/local/include/dolfin/adaptivity/adapt.h
      /usr/local/include/dolfin/adaptivity/AdaptiveLinearVariationalSolver.h
      /usr/local/include/dolfin/adaptivity/AdaptiveNonlinearVariationalSolver.h
      /usr/local/include/dolfin/adaptivity/adaptivesolve.h
      /usr/local/include/dolfin/adaptivity/dolfin_adaptivity.h
      /usr/local/include/dolfin/adaptivity/ErrorControl.h
      /usr/local/include/dolfin/adaptivity/Extrapolation.h
      /usr/local/include/dolfin/adaptivity/GenericAdaptiveVariationalSolver.h
      /usr/local/include/dolfin/adaptivity/GoalFunctional.h
      /usr/local/include/dolfin/adaptivity/marking.h
      /usr/local/include/dolfin/adaptivity/TimeSeries.h
      /usr/local/include/dolfin/ale/ALE.h
      /usr/local/include/dolfin/ale/dolfin_ale.h
      /usr/local/include/dolfin/ale/HarmonicSmoothing.h
      /usr/local/include/dolfin/ale/MeshDisplacement.h
      /usr/local/include/dolfin/common/Array.h
      /usr/local/include/dolfin/common/ArrayView.h
      /usr/local/include/dolfin/common/constants.h
      /usr/local/include/dolfin/common/defines.h
      /usr/local/include/dolfin/common/dolfin_common.h
      /usr/local/include/dolfin/common/dolfin_doc.h
      /usr/local/include/dolfin/common/Hierarchical.h
      /usr/local/include/dolfin/common/IndexSet.h
      /usr/local/include/dolfin/common/init.h
      /usr/local/include/dolfin/common/MPI.h
      /usr/local/include/dolfin/common/NoDeleter.h
      /usr/local/include/dolfin/common/RangedIndexSet.h
      /usr/local/include/dolfin/common/Set.h
      /usr/local/include/dolfin/common/SubSystemsManager.h
      /usr/local/include/dolfin/common/Timer.h
      /usr/local/include/dolfin/common/timing.h
      /usr/local/include/dolfin/common/types.h
      /usr/local/include/dolfin/common/UniqueIdGenerator.h
      /usr/local/include/dolfin/common/utils.h
      /usr/local/include/dolfin/common/Variable.h
      /usr/local/include/dolfin/common/version.h
      /usr/local/include/dolfin/fem/assemble.h
      /usr/local/include/dolfin/fem/assemble_local.h
      /usr/local/include/dolfin/fem/Assembler.h
      /usr/local/include/dolfin/fem/AssemblerBase.h
      /usr/local/include/dolfin/fem/BasisFunction.h
      /usr/local/include/dolfin/fem/DirichletBC.h
      /usr/local/include/dolfin/fem/DiscreteOperators.h
      /usr/local/include/dolfin/fem/DofMap.h
      /usr/local/include/dolfin/fem/DofMapBuilder.h
      /usr/local/include/dolfin/fem/dolfin_fem.h
      /usr/local/include/dolfin/fem/Equation.h
      /usr/local/include/dolfin/fem/fem_utils.h
      /usr/local/include/dolfin/fem/FiniteElement.h
      /usr/local/include/dolfin/fem/Form.h
      /usr/local/include/dolfin/fem/GenericDofMap.h
      /usr/local/include/dolfin/fem/LinearTimeDependentProblem.h
      /usr/local/include/dolfin/fem/LinearVariationalProblem.h
      /usr/local/include/dolfin/fem/LinearVariationalSolver.h
      /usr/local/include/dolfin/fem/LocalAssembler.h
      /usr/local/include/dolfin/fem/LocalSolver.h
      /usr/local/include/dolfin/fem/MultiMeshAssembler.h
      /usr/local/include/dolfin/fem/MultiMeshDirichletBC.h
      /usr/local/include/dolfin/fem/MultiMeshDofMap.h
      /usr/local/include/dolfin/fem/MultiMeshForm.h
      /usr/local/include/dolfin/fem/NonlinearVariationalProblem.h
      /usr/local/include/dolfin/fem/NonlinearVariationalSolver.h
      /usr/local/include/dolfin/fem/PETScDMCollection.h
      /usr/local/include/dolfin/fem/PointSource.h
      /usr/local/include/dolfin/fem/solve.h
      /usr/local/include/dolfin/fem/SparsityPatternBuilder.h
      /usr/local/include/dolfin/fem/SystemAssembler.h
      /usr/local/include/dolfin/fem/UFC.h
      /usr/local/include/dolfin/function/assign.h
      /usr/local/include/dolfin/function/CoefficientAssigner.h
      /usr/local/include/dolfin/function/Constant.h
      /usr/local/include/dolfin/function/dolfin_function.h
      /usr/local/include/dolfin/function/Expression.h
      /usr/local/include/dolfin/function/Function.h
      /usr/local/include/dolfin/function/FunctionAssigner.h
      /usr/local/include/dolfin/function/FunctionAXPY.h
      /usr/local/include/dolfin/function/FunctionSpace.h
      /usr/local/include/dolfin/function/GenericFunction.h
      /usr/local/include/dolfin/function/LagrangeInterpolator.h
      /usr/local/include/dolfin/function/MultiMeshCoefficientAssigner.h
      /usr/local/include/dolfin/function/MultiMeshFunction.h
      /usr/local/include/dolfin/function/MultiMeshFunctionSpace.h
      /usr/local/include/dolfin/function/MultiMeshSubSpace.h
      /usr/local/include/dolfin/function/SpecialFacetFunction.h
      /usr/local/include/dolfin/function/SpecialFunctions.h
      /usr/local/include/dolfin/generation/BoxMesh.h
      /usr/local/include/dolfin/generation/dolfin_generation.h
      /usr/local/include/dolfin/generation/IntervalMesh.h
      /usr/local/include/dolfin/generation/RectangleMesh.h
      /usr/local/include/dolfin/generation/SphericalShellMesh.h
      /usr/local/include/dolfin/generation/UnitCubeMesh.h
      /usr/local/include/dolfin/generation/UnitDiscMesh.h
      /usr/local/include/dolfin/generation/UnitHexMesh.h
      /usr/local/include/dolfin/generation/UnitIntervalMesh.h
      /usr/local/include/dolfin/generation/UnitQuadMesh.h
      /usr/local/include/dolfin/generation/UnitSquareMesh.h
      /usr/local/include/dolfin/generation/UnitTetrahedronMesh.h
      /usr/local/include/dolfin/generation/UnitTriangleMesh.h
      /usr/local/include/dolfin/geometry/BoundingBoxTree.h
      /usr/local/include/dolfin/geometry/BoundingBoxTree1D.h
      /usr/local/include/dolfin/geometry/BoundingBoxTree2D.h
      /usr/local/include/dolfin/geometry/BoundingBoxTree3D.h
      /usr/local/include/dolfin/geometry/CollisionDetection.h
      /usr/local/include/dolfin/geometry/dolfin_geometry.h
      /usr/local/include/dolfin/geometry/GenericBoundingBoxTree.h
      /usr/local/include/dolfin/geometry/intersect.h
      /usr/local/include/dolfin/geometry/IntersectionTriangulation.h
      /usr/local/include/dolfin/geometry/MeshPointIntersection.h
      /usr/local/include/dolfin/geometry/Point.h
      /usr/local/include/dolfin/geometry/SimplexQuadrature.h
      /usr/local/include/dolfin/graph/BoostGraphColoring.h
      /usr/local/include/dolfin/graph/BoostGraphOrdering.h
      /usr/local/include/dolfin/graph/CSRGraph.h
      /usr/local/include/dolfin/graph/dolfin_graph.h
      /usr/local/include/dolfin/graph/Graph.h
      /usr/local/include/dolfin/graph/GraphBuilder.h
      /usr/local/include/dolfin/graph/GraphColoring.h
      /usr/local/include/dolfin/graph/ParMETIS.h
      /usr/local/include/dolfin/graph/SCOTCH.h
      /usr/local/include/dolfin/graph/ZoltanInterface.h
      /usr/local/include/dolfin/io/base64.h
      /usr/local/include/dolfin/io/dolfin_io.h
      /usr/local/include/dolfin/io/Encoder.h
      /usr/local/include/dolfin/io/File.h
      /usr/local/include/dolfin/io/GenericFile.h
      /usr/local/include/dolfin/io/HDF5Attribute.h
      /usr/local/include/dolfin/io/HDF5File.h
      /usr/local/include/dolfin/io/HDF5Interface.h
      /usr/local/include/dolfin/io/HDF5Utility.h
      /usr/local/include/dolfin/io/RAWFile.h
      /usr/local/include/dolfin/io/SVGFile.h
      /usr/local/include/dolfin/io/VTKFile.h
      /usr/local/include/dolfin/io/VTKWriter.h
      /usr/local/include/dolfin/io/X3DFile.h
      /usr/local/include/dolfin/io/X3DOM.h
      /usr/local/include/dolfin/io/XDMFFile.h
      /usr/local/include/dolfin/io/XMLArray.h
      /usr/local/include/dolfin/io/XMLFile.h
      /usr/local/include/dolfin/io/XMLFunctionData.h
      /usr/local/include/dolfin/io/XMLMesh.h
      /usr/local/include/dolfin/io/XMLMeshFunction.h
      /usr/local/include/dolfin/io/XMLMeshValueCollection.h
      /usr/local/include/dolfin/io/XMLParameters.h
      /usr/local/include/dolfin/io/XMLTable.h
      /usr/local/include/dolfin/io/xmlutils.h
      /usr/local/include/dolfin/io/XMLVector.h
      /usr/local/include/dolfin/io/XYZFile.h
      /usr/local/include/dolfin/la/Amesos2LUSolver.h
      /usr/local/include/dolfin/la/BelosKrylovSolver.h
      /usr/local/include/dolfin/la/BlockMatrix.h
      /usr/local/include/dolfin/la/BlockVector.h
      /usr/local/include/dolfin/la/CoordinateMatrix.h
      /usr/local/include/dolfin/la/DefaultFactory.h
      /usr/local/include/dolfin/la/dolfin_la.h
      /usr/local/include/dolfin/la/EigenFactory.h
      /usr/local/include/dolfin/la/EigenKrylovSolver.h
      /usr/local/include/dolfin/la/EigenLUSolver.h
      /usr/local/include/dolfin/la/EigenMatrix.h
      /usr/local/include/dolfin/la/EigenVector.h
      /usr/local/include/dolfin/la/GenericLinearAlgebraFactory.h
      /usr/local/include/dolfin/la/GenericLinearOperator.h
      /usr/local/include/dolfin/la/GenericLinearSolver.h
      /usr/local/include/dolfin/la/GenericMatrix.h
      /usr/local/include/dolfin/la/GenericTensor.h
      /usr/local/include/dolfin/la/GenericVector.h
      /usr/local/include/dolfin/la/Ifpack2Preconditioner.h
      /usr/local/include/dolfin/la/IndexMap.h
      /usr/local/include/dolfin/la/KrylovSolver.h
      /usr/local/include/dolfin/la/LinearAlgebraObject.h
      /usr/local/include/dolfin/la/LinearOperator.h
      /usr/local/include/dolfin/la/LinearSolver.h
      /usr/local/include/dolfin/la/LUSolver.h
      /usr/local/include/dolfin/la/Matrix.h
      /usr/local/include/dolfin/la/MueluPreconditioner.h
      /usr/local/include/dolfin/la/PETScBaseMatrix.h
      /usr/local/include/dolfin/la/PETScFactory.h
      /usr/local/include/dolfin/la/PETScKrylovSolver.h
      /usr/local/include/dolfin/la/PETScLinearOperator.h
      /usr/local/include/dolfin/la/PETScLUSolver.h
      /usr/local/include/dolfin/la/PETScMatrix.h
      /usr/local/include/dolfin/la/PETScObject.h
      /usr/local/include/dolfin/la/PETScOptions.h
      /usr/local/include/dolfin/la/PETScPreconditioner.h
      /usr/local/include/dolfin/la/PETScUserPreconditioner.h
      /usr/local/include/dolfin/la/PETScVector.h
      /usr/local/include/dolfin/la/Scalar.h
      /usr/local/include/dolfin/la/SLEPcEigenSolver.h
      /usr/local/include/dolfin/la/solve.h
      /usr/local/include/dolfin/la/SparsityPattern.h
      /usr/local/include/dolfin/la/TensorLayout.h
      /usr/local/include/dolfin/la/test_nullspace.h
      /usr/local/include/dolfin/la/TpetraFactory.h
      /usr/local/include/dolfin/la/TpetraMatrix.h
      /usr/local/include/dolfin/la/TpetraVector.h
      /usr/local/include/dolfin/la/TrilinosParameters.h
      /usr/local/include/dolfin/la/TrilinosPreconditioner.h
      /usr/local/include/dolfin/la/Vector.h
      /usr/local/include/dolfin/la/VectorSpaceBasis.h
      /usr/local/include/dolfin/log/dolfin_log.h
      /usr/local/include/dolfin/log/Event.h
      /usr/local/include/dolfin/log/log.h
      /usr/local/include/dolfin/log/Logger.h
      /usr/local/include/dolfin/log/LogLevel.h
      /usr/local/include/dolfin/log/LogManager.h
      /usr/local/include/dolfin/log/LogStream.h
      /usr/local/include/dolfin/log/Progress.h
      /usr/local/include/dolfin/log/Table.h
      /usr/local/include/dolfin/math/basic.h
      /usr/local/include/dolfin/math/dolfin_math.h
      /usr/local/include/dolfin/math/Lagrange.h
      /usr/local/include/dolfin/math/Legendre.h
      /usr/local/include/dolfin/mesh/BoundaryComputation.h
      /usr/local/include/dolfin/mesh/BoundaryMesh.h
      /usr/local/include/dolfin/mesh/Cell.h
      /usr/local/include/dolfin/mesh/CellType.h
      /usr/local/include/dolfin/mesh/DistributedMeshTools.h
      /usr/local/include/dolfin/mesh/dolfin_mesh.h
      /usr/local/include/dolfin/mesh/DomainBoundary.h
      /usr/local/include/dolfin/mesh/DynamicMeshEditor.h
      /usr/local/include/dolfin/mesh/Edge.h
      /usr/local/include/dolfin/mesh/Face.h
      /usr/local/include/dolfin/mesh/Facet.h
      /usr/local/include/dolfin/mesh/FacetCell.h
      /usr/local/include/dolfin/mesh/HexahedronCell.h
      /usr/local/include/dolfin/mesh/IntervalCell.h
      /usr/local/include/dolfin/mesh/LocalMeshData.h
      /usr/local/include/dolfin/mesh/LocalMeshValueCollection.h
      /usr/local/include/dolfin/mesh/Mesh.h
      /usr/local/include/dolfin/mesh/MeshColoring.h
      /usr/local/include/dolfin/mesh/MeshConnectivity.h
      /usr/local/include/dolfin/mesh/MeshData.h
      /usr/local/include/dolfin/mesh/MeshDomains.h
      /usr/local/include/dolfin/mesh/MeshEditor.h
      /usr/local/include/dolfin/mesh/MeshEntity.h
      /usr/local/include/dolfin/mesh/MeshEntityIterator.h
      /usr/local/include/dolfin/mesh/MeshEntityIteratorBase.h
      /usr/local/include/dolfin/mesh/MeshFunction.h
      /usr/local/include/dolfin/mesh/MeshGeometry.h
      /usr/local/include/dolfin/mesh/MeshHierarchy.h
      /usr/local/include/dolfin/mesh/MeshOrdering.h
      /usr/local/include/dolfin/mesh/MeshPartitioning.h
      /usr/local/include/dolfin/mesh/MeshQuality.h
      /usr/local/include/dolfin/mesh/MeshRelation.h
      /usr/local/include/dolfin/mesh/MeshRenumbering.h
      /usr/local/include/dolfin/mesh/MeshSmoothing.h
      /usr/local/include/dolfin/mesh/MeshTopology.h
      /usr/local/include/dolfin/mesh/MeshTransformation.h
      /usr/local/include/dolfin/mesh/MeshValueCollection.h
      /usr/local/include/dolfin/mesh/MultiMesh.h
      /usr/local/include/dolfin/mesh/PeriodicBoundaryComputation.h
      /usr/local/include/dolfin/mesh/PointCell.h
      /usr/local/include/dolfin/mesh/QuadrilateralCell.h
      /usr/local/include/dolfin/mesh/SubDomain.h
      /usr/local/include/dolfin/mesh/SubMesh.h
      /usr/local/include/dolfin/mesh/SubsetIterator.h
      /usr/local/include/dolfin/mesh/TetrahedronCell.h
      /usr/local/include/dolfin/mesh/TopologyComputation.h
      /usr/local/include/dolfin/mesh/TriangleCell.h
      /usr/local/include/dolfin/mesh/Vertex.h
      /usr/local/include/dolfin/multistage/dolfin_multistage.h
      /usr/local/include/dolfin/multistage/MultiStageScheme.h
      /usr/local/include/dolfin/multistage/PointIntegralSolver.h
      /usr/local/include/dolfin/multistage/RKSolver.h
      /usr/local/include/dolfin/nls/dolfin_nls.h
      /usr/local/include/dolfin/nls/NewtonSolver.h
      /usr/local/include/dolfin/nls/NonlinearProblem.h
      /usr/local/include/dolfin/nls/OptimisationProblem.h
      /usr/local/include/dolfin/nls/PETScSNESSolver.h
      /usr/local/include/dolfin/nls/PETScTAOSolver.h
      /usr/local/include/dolfin/nls/TAOLinearBoundSolver.h
      /usr/local/include/dolfin/parameter/dolfin_parameter.h
      /usr/local/include/dolfin/parameter/GlobalParameters.h
      /usr/local/include/dolfin/parameter/Parameter.h
      /usr/local/include/dolfin/parameter/Parameters.h
      /usr/local/include/dolfin/plot/dolfin_plot.h
      /usr/local/include/dolfin/plot/ExpressionWrapper.h
      /usr/local/include/dolfin/plot/GenericVTKPlottable.h
      /usr/local/include/dolfin/plot/plot.h
      /usr/local/include/dolfin/plot/VTKPlottableDirichletBC.h
      /usr/local/include/dolfin/plot/VTKPlottableGenericFunction.h
      /usr/local/include/dolfin/plot/VTKPlottableGenericFunction1D.h
      /usr/local/include/dolfin/plot/VTKPlottableMesh.h
      /usr/local/include/dolfin/plot/VTKPlottableMeshFunction.h
      /usr/local/include/dolfin/plot/VTKPlotter.h
      /usr/local/include/dolfin/plot/VTKWindowOutputStage.h
      /usr/local/include/dolfin/refinement/BisectionRefinement1D.h
      /usr/local/include/dolfin/refinement/dolfin_refinement.h
      /usr/local/include/dolfin/refinement/LocalMeshCoarsening.h
      /usr/local/include/dolfin/refinement/ParallelRefinement.h
      /usr/local/include/dolfin/refinement/PlazaRefinementND.h
      /usr/local/include/dolfin/refinement/refine.h
      /usr/local/include/dolfin/refinement/RegularCutRefinement.h
      /usr/local/include/dolfin.h
      /usr/local/include/FAST_Library.h
      /usr/local/include/libadjoint/adj_adjointer_routines.h
      /usr/local/include/libadjoint/adj_adjointer_visualisation.h
      /usr/local/include/libadjoint/adj_constants.h
      /usr/local/include/libadjoint/adj_core.h
      /usr/local/include/libadjoint/adj_data_structures.h
      /usr/local/include/libadjoint/adj_debug.h
      /usr/local/include/libadjoint/adj_dictionary.h
      /usr/local/include/libadjoint/adj_eps.h
      /usr/local/include/libadjoint/adj_error_handling.h
      /usr/local/include/libadjoint/adj_evaluation.h
      /usr/local/include/libadjoint/adj_fortran.h
      /usr/local/include/libadjoint/adj_gst.h
      /usr/local/include/libadjoint/adj_petsc.h
      /usr/local/include/libadjoint/adj_petsc_data_structures.h
      /usr/local/include/libadjoint/adj_petsc_f.h
      /usr/local/include/libadjoint/adj_simplification.h
      /usr/local/include/libadjoint/adj_test_main.h
      /usr/local/include/libadjoint/adj_test_tools.h
      /usr/local/include/libadjoint/adj_variable_lookup.h
      /usr/local/include/libadjoint/html_encode.h
      /usr/local/include/libadjoint/libadjoint.h
      /usr/local/include/libadjoint/revolve.h
      /usr/local/include/libadjoint/revolve_c.h
      /usr/local/include/libadjoint/uthash.h
      /usr/local/include/MAP_Types.h
      /usr/local/include/OpenFOAM_Types.h
    
    Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.
    
    Unexpected .pc files:
      /usr/local/lib/pkgconfig/dolfin.pc
    
    Warning: Unbrewed static libraries were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.
    
    Unexpected static libraries:
      /usr/local/lib/libadjoint.a
      /usr/local/lib/libaerodyn14lib.a
      /usr/local/lib/libaerodynlib.a
      /usr/local/lib/libbeamdynlib.a
      /usr/local/lib/libelastodynlib.a
      /usr/local/lib/libextptfm_mckflib.a
      /usr/local/lib/libfeamlib.a
      /usr/local/lib/libfoamfastlib.a
      /usr/local/lib/libhydrodynlib.a
      /usr/local/lib/libicedynlib.a
      /usr/local/lib/libicefloelib.a
      /usr/local/lib/libifwlib.a
      /usr/local/lib/libmaplib.a
      /usr/local/lib/libmoordynlib.a
      /usr/local/lib/libnwtclibs.a
      /usr/local/lib/libopenfast_postlib.a
      /usr/local/lib/libopenfast_prelib.a
      /usr/local/lib/libopenfastlib.a
      /usr/local/lib/libopenfoamtypeslib.a
      /usr/local/lib/liborcaflexlib.a
      /usr/local/lib/libservodynlib.a
      /usr/local/lib/libsubdynlib.a
    
    Warning: You have unlinked kegs in your Cellar
    Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
    those kegs to fail to run properly once built. Run `brew link` on these:
      ghostscript

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by kilojoules** [comment]
Noted. 

To anyone that comes across this later: ipython only supports python3 as of version 6. Using `brew install ipython@5` solved my problem.
