### ISSUE TITLE
`brew ls` outputs misaligned formulas.

### ISSUE THREAD

**Issue by sahilm** [Homebrew/brew#2852]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

- What you were trying to do (and why)
List all installed formulae by running `brew ls`.

- What happened (include command output)
The output is misaligned:

<img width="849" alt="screen shot 2017-07-02 at 22 23 17" src="https://user-images.githubusercontent.com/215823/27773601-24ad710e-5f75-11e7-84b4-936faec1101f.png">

- What you expected to happen

I expected the formula names to be aligned. I see aligned formula names if I run `brew ls --full-name`.

- Step-by-step reproduction instructions (by running `brew` commands)
Run `brew ls`. Observe output.

`brew config`:
```
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe79e0721b67c6c2329042fe24429c1b9fbef3db
Core tap last commit: 80 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/sahilm/.rbenv/shims/ruby => /Users/sahilm/.rbenv/versions/2.4.1/bin/ruby
Java: 1.8.0_131
macOS: 10.12.5-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

`brew doctor`:

`Your system is ready to brew.`

**Comment by apjanke** [comment]
Thanks for the detailed bug report!

Looks like a bug all right. I couldn't reproduce it myself. Will look in to it.

Would you mind also copying and pasting the output of `brew ls` as text? Would make it easier to do a repro test case if I can copy and paste the list of packages you have installed.

**Comment by sahilm** [comment]
Here you go:
```
ansible
ant
aria2
autoconf
awscli
bash
bash-completion
brew-cask-completion
coreutils
ctags
curl
direnv
docker
docker-compose
docker-machine
docker-machine-nfs
fasd
findutils
fontconfig
freetype
gawk
gcc
gd
gdbm
gettext
git
gmp
gnu-sed
go
gradle
graphviz
grep
icu4c
isl
jpeg
jq
leiningen
libevent
libmpc
libpng
libtiff
libtool
libxml2
libxslt
libyaml
maven
mpfr
mtr
nmap
node
oniguruma
openssl
openssl@1.1
packer
pcre
pkg-config
postgresql
pstree
python
rbenv
rbenv-default-gems
readline
redis
ruby-build
sqlite
tig
tmux
tree
unrar
vim
watch
webp
```

**Comment by sahilm** [comment]
FWIW, this bug still exists on the latest Homebrew.

**Comment by MikeMcQuaid** [comment]
@sahilm No-one else can reproduce it so no-one else is likely to be able to fix this, sorry. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by sahilm** [comment]
No worries Mike. It's not that serious an error anyway :). I'll try and dig into it soonish.
