### ISSUE TITLE
No available sqlitebrowser

### ISSUE THREAD

**Issue by thanhngvpt** [Homebrew/brew#2867]
Hi all.
I'm trying to install sqlitebrowser but got this message 
`Error: No available formula with the name "sqlitebrowser"
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask`
Please take a look and give me advise.
Thanks.

**Comment by ilovezfs** [comment]
```
brew cask install sqlitebrowser
```

**Comment by thanhngvpt** [comment]
Many thanks, just new to mac

**Comment by ilovezfs** [comment]
@thanhngvpt no worries. You're welcome!
