### ISSUE TITLE
Shall we run `brew update` automatically?

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#288]
Migrated from https://github.com/Homebrew/legacy-homebrew/issues/38818.

Since that issue was opened we have:
- made `brew update`'s no-op case very fast
- added this functionality as an opt-in with `HOMEBREW_AUTO_UPDATE=1`

I need to now tweak this behaviour so it's a little less annoying and then we can 🚢.

**Comment by ilovezfs** [comment]
I've seen the no-op case cause it to hang, but I'm not sure of the exact cause yet, though.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Which no-op case; when there's no updates to perform? `brew update --debug` will spam you relentlessly but may help identify it.

**Comment by ilovezfs** [comment]
Yes, when there's no update to perform because the heads match. Yeah, debug seemed to report the appropriate API error code and then just sit there. I'll pay closer attention if/when it happens again.

**Comment by ilovezfs** [comment]
Also, I think auto-stashing and rebase-as-default, combined with this PR, are going to add up to something super annoying.

**Comment by MikeMcQuaid** [comment]
@ilovezfs after https://github.com/Homebrew/brew/pull/312 it should be a lot less annoying for people with `HOMEBREW_DEVELOPER` set. Arguably we should move a bunch more stuff like `brew pull` and friends to be `dev-cmd` and encourage anyone submitting a PR to set it.

**Comment by MikeMcQuaid** [comment]
Hell, even `brew audit`, `brew create` and `brew edit` arguably.

**Comment by ilovezfs** [comment]
The problem with that is that it causes our experience to diverge significantly from the users', which then interferes with dog-fooding, but oh well, I guess.

**Comment by MikeMcQuaid** [comment]
For anyone following along at home: the final PR to enable this is in https://github.com/Homebrew/brew/pull/679 and @ilovezfs seems to be less annoyed by it now.

**Comment by ilovezfs** [comment]
Indeed! :shipit: :shipit: :shipit:

**Comment by spaghetti-** [comment]
I personally think that this feature is too annoying even for someone with fast internet. 

Please make it opt-in only as opposed to opt-out.

**Comment by vitorgalvao** [comment]
@spaghetti- This is one of those features that will no doubt save a lot of headaches for maintainers. It’s also one of those features that if it were opt-in you might not ever realise it exists, but being opt-out you will *if* it bothers you (which is the case here) and hence you’ll know (read, try to figure out) how to turn off.

On one hand it’s slightly annoying to some users, but on the other it’s an advantage to other users *and* maintainers. The latter side has more benefits, and since being opt-out has no irreversible disadvantages, it makes sense to be like it is.

**Comment by spaghetti-** [comment]
@vitorgalvao I understand why you may think that way, however there is a reason why many of the existing package managers (even the very best: portage) doesn't do it this way.

A heads up when you install Homebrew may be a good idea too. I am also of the opinion that inconveniencing even some users and hammering servers for the developers benefit is bad.

**Comment by ilovezfs** [comment]
I'd put the probability of this being made opt-in, not opt-out, within the next year at about 0.1%.

**Comment by vitorgalvao** [comment]
> for the developers benefit

You make it seem like that’s the sole reason, when it was clearly not my point. Either way, this has been discussed to death in https://github.com/Homebrew/legacy-homebrew/issues/38818, including your points. I seriously doubt rehashing this discussion now will suddenly cause a reversal. Like any other decision, the pros and cons of this were pondered and a conclusion reached with those in mind.

**Comment by joshdekock** [comment]
This is an extremely annoying 'feature', maybe it would be a good idea to tell users how to opt-out, when it is turned on.

**Comment by vitorgalvao** [comment]
> maybe it would be a good idea to tell users how to opt-out, when it is turned on.

`man brew`.

**Comment by MikeMcQuaid** [comment]
> This is one of those features that will no doubt save a lot of headaches for maintainers.

> I'd put the probability of this being made opt-in, not opt-out, within the next year at about 0.1%.

> Like any other decision, the pros and cons of this were pondered and a conclusion reached with those in mind.

> man brew.

All good points. The opt-out is documented and it has saved us huge amounts of work on repeat issues.
