### ISSUE TITLE
Why aren't dependencies being tracked?

### ISSUE THREAD

**Issue by dabockster** [Homebrew/brew#2880]
I just removed a package with a rather large set of dependencies. However, I could not find a way to remove the dependency garbage from my Mac (a la apt autoremove). This is my request that such a feature be considered in a future release of Homebrew.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20autoremove
