### ISSUE TITLE
Xcode warning without Xcode installed

### ISSUE THREAD

**Issue by stefanfrede** [Homebrew/brew#2882]
# Please always follow these steps:
- [x ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

I get the warning while running `brew doctor`.

- [x ] Ran `brew update` and retried your prior step?

Done. The output is `Already up-to-date.`

- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?

Yes.

- [ x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.2.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: b5529084906af89827f6d9befd613457a1615918
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 775a2c347553284d6d35a5db6b56105d4b195e0a
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/stefanfrede/.rbenv/shims/ruby => /Users/stefanfrede
Java: N/A
macOS: 10.12.5-x86_64
Xcode: 8.2.1 => /Volumes/Bran/_CCC SafetyNet/2017-01-25 (January 25) 17-06-47/Applications/Xcode.app/Contents/Developer
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

```
$ brew doctor
Warning: Xcode is installed to a directory with a space in the name.
This will cause some formulae to fail to build.

Warning: Your Xcode (8.2.1) is outdated.
Please update to Xcode 8.3.3 (or delete it).
Xcode can be updated from the App Store.
```

Hi,

since today I get the warning above when running brew doctor. I don't have Xcode installed, at least not as far as I can tell (I uninstalled it a while ago).

How can I get rid of the warnings? Thanks!

Best,
- Stefan

**Comment by ilovezfs** [comment]
```
Xcode: 8.2.1 => /Volumes/Bran/_CCC SafetyNet/2017-01-25 (January 25) 17-06-47/Applications/Xcode.app/Contents/Developer
```
Eject the volume.
