### ISSUE TITLE
Option to brew with all options

### ISSUE THREAD

**Issue by chocol4te** [Homebrew/brew#2886]
An "everything" option, equivalent to selecting every additive option, resulting in an installed program with every feature possible. 

I wanted to just install OpenCV and know that any feature I read on the documentation, I can just use without having to reinstall with the new option and try and remember what I currently have.

Typing out every option can get very tedious, especially with larger formulae.

**Comment by MikeMcQuaid** [comment]
This isn't something we're interested in supporting at this time as we don't recommend this behaviour unless you need a specific option.

**Comment by scpeters** [comment]
I think the recommended approach would be to create your own copy of the OpenCV formula in a tap, rename it (for example `opencv-everything`), and modify it so things that were previously options are enabled by default.

Also, note that enabling all options wouldn't work for all formula. For example, `homebrew/science/opencv3` has some options that are mutually exclusive ([jpeg and jpeg-turbo for example](https://github.com/Homebrew/homebrew-science/blob/master/opencv3.rb#L148-L149)).
