### ISSUE TITLE
Previously working formulae fails with 'contains conflicting version recursive dependencies'

### ISSUE THREAD

**Issue by craigminihan** [Homebrew/brew#2888]
Installing ripcordsoftware/packages/avancedb with 1.1.10 worked fine. 

With 1.2.4 it fails with:
`Error: ripcordsoftware/packages/avancedb contains conflicting version recursive dependencies:
  autoconf@2.13, autoconf`

It looks related to commit: e41f0bf8c8365c150935f03f3ecd14b44187b2ef

A couple of observations:
* Running brew install on each autoconf version works fine
* `brew install` moans even if the packages are already installed
* The deps are only for build, but the check is enforced every time even when the bottle would be used - so nobody can install

Some outputs:
```
craigs-Mac:~ craig$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

craigs-Mac:~ craig$ cc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
craigs-Mac:~ craig$ c++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Apols for being a PITA in advance.

**Comment by MikeMcQuaid** [comment]
> Error: ripcordsoftware/packages/avancedb contains conflicting version recursive dependencies: autoconf@2.13, autoconf

This is an issue that with formula's dependencies so needs to be fixed in that tap.

**Comment by MikeMcQuaid** [comment]
> The deps are only for build, but the check is enforced every time even when the bottle would be used - so nobody can install

Sorry, missed this bit. This may justify a fix but: it still indicates the formula is going to be broken for people building from source so I'm not sure if I think a fix is just papering over the problem.

**Comment by ilovezfs** [comment]
As I've mentioned before, I see similar issues for bottles with locking, where a bottle will refuse to pour because a build-time-only dependency happens to be busy with some source build that is in progress.

**Comment by craigminihan** [comment]
@MikeMcQuaid almost all Linux distros support Autoconf 2.13 and 2.69 installed at the same time - hence my requirement here (sorry blame Mozilla for 2.13 - it is ancient)

brew will do it if launched as:
`brew install autoconf@2.13 && brew install autoconf` with no complaints

Looking at the autoconf formulae looks like the authors have taken multi-install into account - 2.13 builds with "--program-suffix=213" which should render the problem mute at least in this case

Going back to e41f0bf8c8365c150935f03f3ecd14b44187b2ef and the removed line:

```ruby
if ENV["HOMEBREW_CHECK_RECURSIVE_VERSION_DEPENDENCIES"]
```

could this check be reversed? ie. HOMEBREW_*NO*_CHECK_RECURSIVE_VERSION_DEPENDENCIES

**Comment by craigminihan** [comment]
@MikeMcQuaid I should also mention that I wrote both the fomulae and the original source package - and it builds just fine on BSD, Linux and OSX - Intel and ARM - took a lot of effort that did

I'm happy to change my brew related docs so users can get this thing working if that is the easiest way:

```
brew install autoconf@2.13 && brew install autoconf && brew install ripcordsoftware/packages/avancedb
```

will be fine if I remove the offending autoconf lines

**Comment by MikeMcQuaid** [comment]
> almost all Linux distros support Autoconf 2.13 and 2.69 installed at the same time

We do too, we just don't support installing two versions of the same software in the same dependency tree. This is because it's bad packaging.

> could this check be reversed? ie. HOMEBREW_NO_CHECK_RECURSIVE_VERSION_DEPENDENCIES

No, sorry.



> I should also mention that I wrote both the fomulae and the original source package - and it builds just fine on BSD, Linux and OSX - Intel and ARM - took a lot of effort that did

Nice work 👏. I'd recommend switching your use of `autoconf` to the same as your dependencies so you don't require people install multiple versions to build your software and dependencies from source.

**Comment by craigminihan** [comment]
@MikeMcQuaid unfortunately my autoconf deps are dictated by the packages I depend on for build and are out of my control. 

Since I can build by changing the order of installed packages slightly I'm happy to close since I appreciate a regression change isn't massively appealing at your end.

**Comment by MikeMcQuaid** [comment]
Ok, thanks for understanding @craigminihan.
