### ISSUE TITLE
Analytics adds latency to `brew search` invocation

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/brew#29]
The bash and zsh completion scripts use `brew search`; setting HOMEBREW_ANALYTICS makes `brew search` invocations take ~twice as long on my Macbook (500 ms enabled, 250 ms disabled). Ideally, `brew search` should be very fast.

**Comment by UniqMartin** [comment]
And IMO using `brew search` in this context is an internal usage and not a direct invocation by the user, thus it probably shouldn't be counted anyway? (Tab completion can result in many invocations of this without ever leading to an actual `brew` command being executed.)

**Comment by mikemcquaid** [comment]
Should be fixed by #34. I'd rather we take the approach to making analytics completely async rather than disabling it for speed reasons.
