### ISSUE TITLE
Feature: Allow listing with descriptions for all brew packages

### ISSUE THREAD

**Issue by zsprackett** [Homebrew/brew#2902]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

Allow users to learn more about all packages available to them in homebrew by augmenting the brew desc command:

brew desc --all
    Display name and one-line description for all formulae.

brew desc --installed
    Display name and one-line description for all installed formulae.

**Comment by ilovezfs** [comment]
```
find $(brew --repo homebrew/core)/Formula -path "*.rb" -exec brew desc "{}" \+
```

```
brew list | xargs -n1 brew desc
```

**Comment by zsprackett** [comment]
@ilovezfs yes, i added two new options.

**Comment by zsprackett** [comment]
redid the PR.

**Comment by MikeMcQuaid** [comment]
Closing in favour of the PR. FYI we don't need a new issue for new features if you plan on creating a PR.
