### ISSUE TITLE
Installation of brew on macOs Sierra 10.12.5 (16F73)

### ISSUE THREAD

**Issue by devrealtime** [Homebrew/brew#2909]
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
fatal: unable to access 'https://github.com/Homebrew/brew/': Could not resolve host: github.com
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force --depth=1

**Comment by MikeMcQuaid** [comment]
We can't do anything if you can't access GitHub, sorry.

**Comment by devrealtime** [comment]
I installed  **macports** and it worked

**Comment by MikeMcQuaid** [comment]
Consider using that instead.
