### ISSUE TITLE
Better handle sbin missing from PATH

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#291]
Migrated from https://github.com/Homebrew/legacy-homebrew/pull/38778

A few ideas proposed there:
- Move everything from `sbin` to `bin`
- add the caveats suggested in https://github.com/Homebrew/legacy-homebrew/pull/38778

CC @tdsmith who created https://github.com/Homebrew/legacy-homebrew/pull/38778

**Comment by DomT4** [comment]
Tim's solution sounds ideal to me, if it works as expected, FWIW.

**Comment by MikeMcQuaid** [comment]
We currently print: 
```
Warning: /usr/local/sbin is not in your PATH
You can amend this by altering your ~/.zshrc file
```

This seems ideal to me so don't need any additional caveats.
