### ISSUE TITLE
[Suggestion] Any lock file for brew?

### ISSUE THREAD

**Issue by xareelee** [Homebrew/brew#2910]
Is there any plan to add a config file and a lock file for homebrew like other package managers (e.g. RubyGem, [npm](https://docs.npmjs.com/files/package-lock.json), ) to ensure that multiple computers use the same versions of dev tools.

* `~/.brew`: list the semver rule for installed tools
* `~/.brew.lock`: list the locked versions of the  installed tools

To set up a new computer:

1. Copy `.brew` and `.brew.lock` files to the user's home directory of the new Mac
2. Execute `brew install`

To sync dev tools with another Mac:

1. Sync the `.brew` and `.brew.lock` files to another Mac
2. Execute `brew install`

To add new dev tools

* Execute `brew install <package_name>` and it will also update `.brew` and `.brew.lock` files

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-bundle.

**Comment by MikeMcQuaid** [comment]
Someone could add lockfile support to Homebrew/bundle but we have no plans to do so at this time. We won't ever support full semver locking.
