### ISSUE TITLE
CLT not up to date / brew does not run without xcode

### ISSUE THREAD

**Issue by ManuelSchneid3r** [Homebrew/brew#2918]
- What you were trying to do (and why)
Use brew. E.g. to install bash or brew upgrade without having XCode installed.
- What happened (include command output)
Get the warning in the terminal output below. Installation fails. CLT has to be outdated. But app store does not find any updates.
- What you expected to happen
To not fail.
- Step-by-step reproduction instructions (by running `brew` commands)
Well `brew install bash`or `brew upgrade`

```
manuel@xenon ~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.

(1) manuel@xenon ~ $ brew config
HOMEBREW_VERSION: 1.2.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: b5529084906af89827f6d9befd613457a1615918
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c731984e21a7e093d170116ad791eb45d2acf8d6
Core tap last commit: 40 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45, 1.7.0_51
macOS: 10.12.5-x86_64
Xcode: N/A
CLT: (null)
X11: N/A
manuel@xenon ~ $ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by JCount** [comment]
Try running `sudo xcode-select --reset` in case all that has happened is it is not pointing to the correct path.

**Comment by ManuelSchneid3r** [comment]
That does not help

**Comment by MicroTransactionsMatterToo** [comment]
Having a similar problem. I've reset the path, set the path manually to /Applications/Xcode.app. I'm running macOS High Sierra, and XCode 9.0.

**Comment by JCount** [comment]
One thing that may work is to download the manual install package at https://developer.apple.com/download/more/ and try running it to see if it fixes your install.

Try running `xcrun -n -f clang` which should may print out their location if you still have a working `xcrun`.

Otherwise, the broken installation of the CLTs you appear to have will have to be manually located, and likely removed.

**Comment by ManuelSchneid3r** [comment]
Yes I had other problems too. Apple screwed things up un Sierra update. Wiped completely and installed a fresh Sierra. Everything is fine now. Thank you.

**Comment by baskint** [comment]
fyi - started having this issue on a brand new install of macOS High Sierra and installing `Command Line Tools (macOS 10.13) for Xcode 9` had fixed it as I downloaded from here:
https://developer.apple.com/download/more/.

**Comment by shuishoudage** [comment]
have tried @JCount methods, didn't work for me, the way @baskint posted worked for me, Thank you baskint !
