### ISSUE TITLE
Homebrew incorrectly assumes binary compatibility

### ISSUE THREAD

**Issue by btj** [Homebrew/brew#2942]
Homebrew allows a system to get into a state that could not have been reached by building all formulae from source in dependency order.

For example, yesterday I ran `brew upgrade ocaml`, which upgraded my OCaml installation from version 4.04 to 4.05. However, I also had camlp4 4.04+1 installed, which did not get upgraded by that command.

Today, I wanted to build my OCaml project (called VeriFast), which uses both OCaml and camlp4. However, ocaml segfaulted. After a few hours of investigation, I discovered that it was due to an out-of-date camlp4. `brew upgrade camlp4` fixed the problem.

I filed a bug with OCaml, suggesting that they make sure that the incompatibility is detected, so that I get a helpful error message rather than a segfault. However, given the Linux build-from-source culture, a reasonable answer from the OCaml/camlp4 teams could be that it is not their problem that my system got into this state.

So, I would suggest that the Homebrew team consider if the current policy of assuming binary compatibility and fixing particular cases as they arise, is the best one. One possible improvement might be to allow dependencies to be marked as non-binary-compatible, which would mean that 1) the build bot rebuilds dependent bottles whenever a dependency changes, and 2) `brew upgrade` recursively upgrades dependent formulae (which may mean building from source if no new bottle has been built by the bot yet).

A similar effect could perhaps be achieved today by including a test case in dependent formulae that detects the binary incompatibility. However, such a test case may not always be easy to write. For example, I managed to distill a minimal repro that reproduces the ocaml/camlp4 segfault, but this repro will not probably not detect future incompatibilities. Of course, each project should have a test suite that covers all functionality, but I don't think the formula tests are supposed to run a project's complete test suite? And even that might not detect all issues.

**Comment by ilovezfs** [comment]
Since `ocaml`  does not depend on `camlp4`, `brew upgrade ocaml` is not going to automatically upgrade `camlp4` for you. In the future, I suggest you use

```
brew upgrade
```

without any formula arguments to avoid this. We specifically revision bump `camlp4` as part of the `ocaml` upgrade PR for this very reason.
