### ISSUE TITLE
I am using this command brew install ettercap --with-gtk+ so does this command install the latest ettercap files since I have already downloaded the ettercap master folder on my Mac and extracted it

### ISSUE THREAD

**Issue by sayan-sibyl** [Homebrew/brew#2947]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
- What you were trying to do (and why) I was trying to install ettercap

I am using this command brew install ettercap --with-gtk+ so does this command install the latest ettercap files since I have already downloaded the ettercap master folder on my Mac and extracted it

**Comment by MikeMcQuaid** [comment]
@sayan-sibyl Stop creating issues without filling out the issue template or you will be blocked.
