### ISSUE TITLE
Pymol crashes on startup on Mac OS 10.11.6

### ISSUE THREAD

**Issue by byamal** [Homebrew/brew#2956]
Pymol crashes when I try to open it. The terminal output is:

$pymol

PyMOL(TM) Molecular Graphics System, Version 1.8.4.0.
Copyright (c) Schrodinger, LLC.
All Rights Reserved.

Created by Warren L. DeLano, Ph.D. 

PyMOL is user-supported open-source software.  Although some versions
are freely available, PyMOL is not in the public domain.

If PyMOL is helpful in your work or study, then please volunteer 
support for our ongoing efforts to create open and affordable scientific
software by purchasing a PyMOL Maintenance and/or Support subscription.

More information can be found at "http://www.pymol.org".

Enter "help" for a list of commands.
Enter "help <command-name>" for information on a specific command.
Hit ESC anytime to toggle between text and graphics.

Detected OpenGL version 2.0 or greater. Shaders available.
Detected GLSL version 1.20.
OpenGL graphics engine:
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon R9 M370X OpenGL Engine
GL_VERSION: 2.1 ATI-1.42.15
Detected 8 CPU cores. Enabled multithreaded rendering.
/usr/local/bin/pymol: line 4: 72340 Terminated: 15 "/usr/local/opt/python/bin/python2.7" "/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/init.py" "$@"

**Comment by byamal** [comment]
Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk
https://gist.github.com/0817e94cf8ed4f70f15e4ddc0b397e0e

**Comment by fxcoudert** [comment]
This is a `homebrew-science` issue, which is tracked there: https://github.com/Homebrew/homebrew-science/issues/5505
