### ISSUE TITLE
brew tests invokes "trash" noise.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#2974]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
~> brew doctor
Your system is ready to brew.
~> brew config
HOMEBREW_VERSION: 1.2.6-13-g627b1da
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 627b1dae707b4b5ea5e299ff12dd8ac1abbfa056
Last commit: 54 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fb1b524ef335bdfa5f04ec197cc7f3a213ad4409
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/opt/git/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.4.1/bin/ruby
Java: 1.8.0_141
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

This is not a huge deal _to say the least_, so feel free to close if it's a known/desired thing, but running `brew tests` invokes the macOS trash sound. I presume it's a [cask thing](https://github.com/Homebrew/brew/blob/29ffe158903c0528c672da50c2b83b1b5d8cbe1c/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb#L238-L258).

Only really raising it because it did make me stare at my trash folder for 5 minutes with a slightly puzzled expression & wonder why nothing new had appeared in there despite the trash sound being triggered twice in quick succession 🤷‍♂️.

**Comment by reitermarkus** [comment]
Yeah, there's not really a (good) way to turn the sound off I think.

**Comment by DomT4** [comment]
Aye, not to my immediate knowledge. I know you can use `osascript` to both get & set system volume but suddenly having your music or such muted very briefly whenever `brew cask uninstall` or `brew tests` is run isn't really ideal UX either.

**Comment by ilovezfs** [comment]
Yeah, having trash noises emanating from the test suite isn't exactly great.

**Comment by reitermarkus** [comment]
I tried muting the system sound, and it takes just long enough that you can tell. There is another volume setting for only the sound effects, but no idea how to control this.

**Comment by reitermarkus** [comment]
Ok, found a way.

**Comment by apjanke** [comment]
I vote for both keeping this open as a bug, and not having `brew` do anything to modify the system sound effects. Especially if this doesn't result in new items in the user-visible Trash.

One of the first things I do on any new Mac install is turn off OS sound effects, so this doesn't hit me. But it seems like something `brew` should avoid.

**Comment by ilovezfs** [comment]
I think the most straightforward solution here is to simply remove the test.

**Comment by MikeMcQuaid** [comment]
Relatedly: `brew tests` puts a file in my Trash which is annoying. @reitermarkus What's the latest here?

**Comment by reitermarkus** [comment]
Seems like `osascript` always adds `\n` to `stdout`, so the last filename is always wrong.

https://github.com/Homebrew/brew/pull/3247
