### ISSUE TITLE
operation not permitted in brew packages

### ISSUE THREAD

**Issue by smagnuso** [Homebrew/brew#2994]
Since fb310c57b18c3835ed69e25e653cddc3570f64ac I now notice that packages that I have in my own tap are not allowed to write to /usr/local. This has broken quite a few of my recipes and wondering if I can have a way out of this if I brew tap in some specific ways to prevent the sandbox restrictions?

As an alternative maybe would it be reasonable to whitelist /usr/local?

**Comment by Miodec** [comment]
Is it where brew install cant make a directory, but manual mkdir works? 

![screen shot 2017-08-02 at 18 23 02](https://user-images.githubusercontent.com/13181393/28899168-893bb3a4-77e1-11e7-84e3-d12d5e884fc5.png)
![screen shot 2017-08-03 at 00 06 16](https://user-images.githubusercontent.com/13181393/28899179-918bbae0-77e1-11e7-9639-33f12de8331a.png)
![screen shot 2017-08-03 at 00 12 23](https://user-images.githubusercontent.com/13181393/28899188-97c50056-77e1-11e7-8c5f-444661d1f6c6.png)

**Comment by Miodec** [comment]
Got it. Just add --no-sandbox to brew install. Worked for me

**Comment by ilovezfs** [comment]
@Miodec please do not post undocumented commands intended for internal use.

**Comment by ilovezfs** [comment]
@smagnuso please see the discussion on https://github.com/Homebrew/brew/issues/2986.
