### ISSUE TITLE
Should `brew search` return aliases?

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/brew#30]
`brew search` does not include e.g. `zmq`; `brew search zmq` does. Adding alises to `brew search` output will have the pleasant effect of including aliases in bash and zsh autocompletion. Is there a reason not to return aliases as well? (Is it a problem if `search` returns "duplicates"?)

**Comment by UniqMartin** [comment]
Maybe it should offer the option `--include-aliases` to include the aliases, [like `brew commands` already does](https://github.com/Homebrew/brew/blob/3afacc351c44c4cee08c181e7c761f44e8b43722/Library/Homebrew/cmd/commands.rb#L6) and where it's mainly (only?) used for tab completion …

**Comment by tdsmith** [comment]
Or we could add a `brew formula-completion` command and not log it and solve this and #29 with a single stone!? `--include-aliases` feels a little weird because `search` with any arguments already does that, idk.

**Comment by xu-cheng** [comment]
A whole new command may be useful, because we could add it to the blacklist which skip google analytics.

**Comment by mikemcquaid** [comment]
> A whole new command may be useful, because we could add it to the blacklist which skip google analytics.

I'd rather we avoid blacklisting things unless they actually affect performance after https://github.com/Homebrew/brew/pull/34 is merged.

**Comment by mikemcquaid** [comment]
> Or we could add a brew formula-completion command and not log it and solve this and #29 with a single stone!?

I like the idea of a new command or argument rather than including aliases in default output (as they aren't duplicate formulae really)

> --include-aliases feels a little weird because search with any arguments already does that, idk.

This feels like an implementation detail side effect of the way we have aliases as symlinks. I've never noticed this behaviour and it feels weird to me.

**Comment by mikemcquaid** [comment]
Seems we've got some options for moving forward so closing this out in favour of a PR.
