### ISSUE TITLE
Error: Operation not permitted in method ln_s.

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#3002]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Install a formula that creates symlink. The problematic operator looks like: 
```ln_s Dir["#{share}/kf5"], "#{Etc.getpwuid.dir}/Library/Application Support/", :force => true```
- What happened (include command output)
```Error: Operation not permitted - (/usr/local/Cellar/kf5-kdoctools/5.36.0/share/kf5, /Users/yurikoles/Library/Application Support/kf5)```
- What you expected to happen
Symlink is created without errors.
- Step-by-step reproduction instructions (by running `brew` commands)

```brew install haraldf/kf5/kf5-kdoctools```

<details><summary>brew doctor</summary>

```Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.```
</details>
<details><summary>brew config</summary>

```HOMEBREW_VERSION: 1.3.0-55-gae0b7cb
ORIGIN: https://github.com/Homebrew/brew
HEAD: ae0b7cb824cfd0fa08fda1d2c0d0dd53b3c4adaa
Last commit: 10 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e6d5d03bd60ab3a0feaba481163fa50903e0512d
Core tap last commit: 75 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.14.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_144
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```
</details>

------
Ticket in tap: https://github.com/haraldF/homebrew-kf5/issues/127

**Comment by ilovezfs** [comment]
See
https://brew.sh/2017/07/31/homebrew-1.3.0/
https://github.com/Homebrew/brew/issues/2986
https://github.com/Homebrew/brew/issues/2994
