### ISSUE TITLE
Brew audit --strict --online wget hangs with curl active

### ISSUE THREAD

**Issue by SConaway** [Homebrew/brew#3011]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

I was just learning about developing on homebrew and decided to run `brew audit --strict --online wget` on `curl`. This hung so I tried `brew audit --strict --online curl`, and no hang.  I expected it not to hang. (Reasonable I think). I let it run for 45 minutes, but no output was shown. 

I am running macOS High Sierra `17A315i`

Output of `brew doctor` and `brew config`:

`Stevens-MacBook-Pro:~ steven$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers with debugging if you file an issue. If everything you use Homebrew for is working fine: please don't worry and just ignore them. Thanks!`
    
    Warning: You are using macOS 10.13.
    We do not provide support for this pre-release version.
    You may encounter build failures or other breakages.
    Please create pull-requests instead of filing issues.
    Warning: Ruby version 2.3.3 is unsupported on 10.13. Homebrew
    is developed and tested on Ruby 2.0, and may not work correctly
    on other Rubies. Patches are accepted as long as they don't cause breakage
    on supported Rubies.
    
    Warning: Homebrew's sbin was not found in your PATH but you have installed
    formulae that put executables in /usr/local/sbin.
    Consider setting the PATH for example like so
      echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
    
    Stevens-MacBook-Pro:~ steven$ brew config
    HOMEBREW_VERSION: 1.3.0-31-g441bd37
    ORIGIN: https://github.com/Homebrew/brew
    HEAD: 441bd37fd03d3300c655eea1d206644a2718dce2
    Last commit: 7 hours ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 8a27cc46ba590d2db3771924b6e4dd0e1f4e23f8
    Core tap last commit: 6 hours ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local/Homebrew
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: octa-core 64-bit haswell
    Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
    Clang: 9.0 build 900
    Git: 2.14.0 => /usr/local/bin/git
    Perl: /usr/bin/perl
    Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
    Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
    Java: 1.8.0_144, 1.6.0_65-b14-468
    macOS: 10.13-x86_64
    Xcode: 9.0
    CLT: 9.0.0.0.1.1500650180
    X11: N/A

**Comment by MikeMcQuaid** [comment]
What about with no `--online`? Do you have `HOMEBREW_GITHUB_API_TOKEN` set? If not, please set one and try again. Thanks!

**Comment by SConaway** [comment]
With no `--online` it prints a blank line in ~9 seconds.

    Stevens-MacBook-Pro:homebrew-cask steven$ time brew audit --strict wget
    
    real	0m9.522s
    user	0m5.288s
    sys	0m1.574s
    Stevens-MacBook-Pro:homebrew-cask steven$ time brew audit --strict curl
    
    real	0m7.847s
    user	0m3.141s
    sys	0m1.390s

With `--online` I ran`time brew audit --strict --online curl` for a time of ~10 seconds

    Stevens-MacBook-Pro:homebrew-cask steven$ time brew audit --strict --online curl 
    
    real	0m10.712s
    user	0m3.568s
    sys	0m1.560s

**Comment by SConaway** [comment]
Tried `brew audit --strict --online wget` and it works today, any changes in brew:master?

**Comment by MikeMcQuaid** [comment]
No changes. It seems likely you tripped GitHub's rate limit and it was waiting for that to time out.
