### ISSUE TITLE
Don't warn when all dependencies are being removed together

### ISSUE THREAD

**Issue by mqudsi** [Homebrew/brew#3023]
Currently, when a remove or uninstall command is executed, homebrew checks to see if any installed packages are dependent on the package in question, and warns/requires additional, unsafe user intervention if that is the case. 

However, in the case that all packages that depend on x are being removed in the same command, this should actually be a safe operation that does not need to be forced through and also should not generate any warnings. 

Currently, the removals are processed in order. If they are listed in the command line in an order such that no package is removed before any packages that depend on it are removed as well, everything is fine. But in the case of cyclic dependencies or unsorted removals, a warning about dependencies is generated and the operation halts. 

To demonstrate with an example: 

`brew remove depends-on-x x` succeeds but `brew remove x depends-on-x` does not. `brew remove x-depends-on-y y-depends-on-x` never succeeds in any order.

**Comment by MikeMcQuaid** [comment]
Please fill in the issue template like it told you to.



> brew remove depends-on-x x succeeds but brew remove x depends-on-x does not. brew remove x-depends-on-y y-depends-on-x never succeeds in any order.

Please provide an example of a `brew install` and then `brew uninstall` that reproduce your described issue.

**Comment by mqudsi** [comment]
```
[I] mqudsi@QBook ~/R/fish-shell> brew remove boot2docker zsh pandoc docker docker docker-machine docker-machine-driver-xhyve hpn-ssh php56-imagick
Error: Refusing to uninstall /usr/local/Cellar/docker-machine/0.12.2
because it is required by docker-machine-driver-xhyve, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies boot2docker zsh pandoc docker docker docker-machine docker-machine-driver-xhyve hpn-ssh php56-imagick
```

I just had a thought - is this because there are two versions of the dependent package installed and remove would keep the older one which still depends on the same version of the dependency?

**Comment by ilovezfs** [comment]
You could try moving the older one out of the Cellar, and see if it still complains.

**Comment by mqudsi** [comment]
It may be best to just close this. I thought I was reporting a feature suggestion (i.e. I did not realize brew already took pains to avoid warning in this case) and have no reason to believe that there was a bug in the dependency resolution. I was merely reporting something copy-and-pasted out of my terminal history.
