### ISSUE TITLE
Feature Request: Uninstall After Formula Deleted

### ISSUE THREAD

**Issue by cliii** [Homebrew/brew#3024]
I recently tried to uninstall powerline as follows.

`brew uninstall powerline`

That action produced the following message.

`Error: No such keg: /usr/local/Cellar/powerline`

I then tried the following for information.

`brew info powerline`

And the following is the result.

`powerline was deleted from homebrew/core in commit 532c4d870: powerline: migrate to boneyard`

There is no procedure to uninstall deleted formula. As a package manager, brew should be able to uninstall previously installed software with `brew uninstall $package`, including all of the files that brew did install previously - completely reversing the actions that were taken to install it.

**Comment by vitorgalvao** [comment]
`brew uninstall --force powerline` should do it.

**Comment by cliii** [comment]
Thank you, the command completes with no output and exit code `0`, yet `powerline` and the fonts, etc, that were installed still remain.

**Comment by ilovezfs** [comment]
Please fill out the issue template. I cannot reproduce this.

**Comment by cliii** [comment]
nah  - i give up close it - i'll just brute force it, by the way - you can reproduce it if you try

**Comment by ilovezfs** [comment]
@cliii I did try it, and as I said, I couldn't reproduce it. That makes me think maybe your brew is outdated, or something along those line. But since you have not filled out the issue template, there's no `brew config` or `brew doctor` output for me to inspect. That makes it pretty difficult to help you or to understand what might be wrong.

**Comment by MikeMcQuaid** [comment]
@cliii Please don't create issues in future if you're not willing to help us reproduce it or fill out the issue template.
