### ISSUE TITLE
How to disable or get around sandboxing for custom taps

### ISSUE THREAD

**Issue by ethomas2** [Homebrew/brew#3027]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

At Box we have our own custom tap so that users use to install various internal tools. Two of our formulas just broke in brew v1.3.0 because of https://github.com/Homebrew/brew/commit/fb310c57b18c3835ed69e25e653cddc3570f64ac. The first formula installs credentials in the user's home directory. The second installs a LaunchAgent in ~/Library/LaunchAgents. Neither of those work now because the brew install can't write to the user's home directory because of the sandbox.

I have read https://github.com/Homebrew/brew/issues/2994. I think allowing me to whitelist certain file paths would be ideal because then I can maintain my formula's current behavior and still get the added security of the sandbox.

If that is not possible, I would accept the ability to turn off sandboxing for my custom tap (as suggested in  https://github.com/Homebrew/brew/issues/2986). 

Could you reconsider reopening either of these issues? Or advise on the proper way of writing to the user's home directory?

**Comment by ilovezfs** [comment]
The sandbox has been fully enabled in homebrew/core for quite a while. The purpose of the latest change is precisely to enable it in third-party taps as well. Allowing whitelisting would defeat the purpose.

>Or advise on the proper way of writing to the user's home directory?

There isn't one. You can use configuration files in /usr/local/etc, though.

For plists, you should define `def plist` and use [brew services](https://github.com/Homebrew/homebrew-services/). See `postgresql` for an example:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgresql.rb#L118-L144

**Comment by MikeMcQuaid** [comment]
> The second installs a LaunchAgent in ~/Library/LaunchAgents.

`brew services` is the appropriate way of doing this and `brew bundle` (https://github.com/Homebrew/homebrew-bundle) can be told to automatically (re)start services and therefore install the plist for you.

> The first formula installs credentials in the user's home directory.

We have no suggested workaround for this within a formula. Instead consider an external Homebrew command (e.g. https://github.com/github/homebrew-bootstrap/blob/master/cmd/brew-bootstrap-nodenv-node) or a project setup script (e.g. https://github.com/github/scripts-to-rule-them-all/blob/master/script/setup)
