### ISSUE TITLE
brew should check shasum of actual program

### ISSUE THREAD

**Issue by ymarcus93** [Homebrew/brew#3037]
Currently, brew only checks the shasum that the formula creator puts in the file. This checksum is checked when installing, but it is only a check on the custom brew bottle. I think there should be an extra option to check the checksum of the original tar, provided by the developer of the program, so that brew can check that both the bottle hasn't been tampered with and the binary itself. This helps all Homebrew users because it makes the package manager more secure.

**Comment by MikeMcQuaid** [comment]
We already do this.
