### ISSUE TITLE
Error: pkg-config.rb:1: syntax error, unexpected <<

### ISSUE THREAD

**Issue by programmingkidx** [Homebrew/brew#3038]
# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

brew config output:
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 8 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8fda2823a838d226537ae186b996949c89ebf38f
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: 8.1 build 802
Git: 2.11.0 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.0/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A
MacPorts/Fink: /opt/local/bin/port

brew doctor output:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /opt/local/bin/apr-1-config
  /opt/local/bin/apu-1-config
  /opt/local/bin/croco-0.6-config
  /opt/local/bin/curl-config
  /opt/local/bin/freetype-config
  /opt/local/bin/gpg-error-config
  /opt/local/bin/icu-config
  /opt/local/bin/krb5-config
  /opt/local/bin/libgcrypt-config
  /opt/local/bin/libmcrypt-config
  /opt/local/bin/libpng-config
  /opt/local/bin/libpng16-config
  /opt/local/bin/Magick++-config
  /opt/local/bin/Magick-config
  /opt/local/bin/MagickCore-config
  /opt/local/bin/MagickWand-config
  /opt/local/bin/ncurses6-config
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/neon-config
  /opt/local/bin/pcre-config
  /opt/local/bin/pkg-config
  /opt/local/bin/python2.7-config
  /opt/local/bin/Wand-config
  /opt/local/bin/xml2-config
  /opt/local/bin/xslt-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Your default Python does not recognize the Homebrew site-packages
directory as a special site-packages directory, which means that .pth
files will not be followed. This means you will not be able to import
some modules after installing them with Homebrew, like wxpython. To fix
this for the current user, you can run:
  mkdir -p /Users/john/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/john/Library/Python/2.7/lib/python/site-packages/homebrew.pth

Warning: You have leftover files from an older version of Xcode.
You should delete them using:
  /Developer/Library/uninstall-developer-folder

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libfaac.0.dylib
  /usr/local/lib/libfaad.0.dylib
  /usr/local/lib/libmp3lame.0.0.0.dylib
  /usr/local/lib/libmpc.3.dylib
  /usr/local/lib/libmpfr.4.dylib
  /usr/local/lib/libpyglib-gi-2.0-python2.0.dylib
  /usr/local/lib/libSDL-1.2.0.dylib
  /usr/local/lib/libvirt-admin.0.dylib
  /usr/local/lib/libvirt-lxc.0.dylib
  /usr/local/lib/libvirt-qemu.0.dylib
  /usr/local/lib/libvirt.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/faac.h
  /usr/local/include/faaccfg.h
  /usr/local/include/faad.h
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/IOKit/IOCFSerialize.h
  /usr/local/include/IOKit/IOCFUnserialize.h
  /usr/local/include/IOKit/IOKitLib.h
  /usr/local/include/IOKit/kext/KXKext.h
  /usr/local/include/IOKit/kext/KXKextManager.h
  /usr/local/include/IOKit/kext/KXKextRepository.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/lame/lame.h
  /usr/local/include/libavcodec/avcodec.h
  /usr/local/include/libavcodec/avfft.h
  /usr/local/include/libavcodec/dxva2.h
  /usr/local/include/libavcodec/opt.h
  /usr/local/include/libavcodec/vaapi.h
  /usr/local/include/libavcodec/vdpau.h
  /usr/local/include/libavcodec/xvmc.h
  /usr/local/include/libavdevice/avdevice.h
  /usr/local/include/libavformat/avformat.h
  /usr/local/include/libavformat/avio.h
  /usr/local/include/libavutil/adler32.h
  /usr/local/include/libavutil/attributes.h
  /usr/local/include/libavutil/avconfig.h
  /usr/local/include/libavutil/avstring.h
  /usr/local/include/libavutil/avutil.h
  /usr/local/include/libavutil/base64.h
  /usr/local/include/libavutil/common.h
  /usr/local/include/libavutil/crc.h
  /usr/local/include/libavutil/error.h
  /usr/local/include/libavutil/fifo.h
  /usr/local/include/libavutil/intfloat_readwrite.h
  /usr/local/include/libavutil/log.h
  /usr/local/include/libavutil/lzo.h
  /usr/local/include/libavutil/mathematics.h
  /usr/local/include/libavutil/md5.h
  /usr/local/include/libavutil/mem.h
  /usr/local/include/libavutil/pixdesc.h
  /usr/local/include/libavutil/pixfmt.h
  /usr/local/include/libavutil/rational.h
  /usr/local/include/libavutil/sha1.h
  /usr/local/include/libiberty/ansidecl.h
  /usr/local/include/libiberty/demangle.h
  /usr/local/include/libiberty/dyn-string.h
  /usr/local/include/libiberty/fibheap.h
  /usr/local/include/libiberty/floatformat.h
  /usr/local/include/libiberty/hashtab.h
  /usr/local/include/libiberty/libiberty.h
  /usr/local/include/libiberty/objalloc.h
  /usr/local/include/libiberty/partition.h
  /usr/local/include/libiberty/safe-ctype.h
  /usr/local/include/libiberty/sort.h
  /usr/local/include/libiberty/splay-tree.h
  /usr/local/include/libiberty/ternary.h
  /usr/local/include/libswscale/swscale.h
  /usr/local/include/libvirt/libvirt-common.h
  /usr/local/include/libvirt/libvirt-domain-snapshot.h
  /usr/local/include/libvirt/libvirt-domain.h
  /usr/local/include/libvirt/libvirt-event.h
  /usr/local/include/libvirt/libvirt-host.h
  /usr/local/include/libvirt/libvirt-interface.h
  /usr/local/include/libvirt/libvirt-lxc.h
  /usr/local/include/libvirt/libvirt-network.h
  /usr/local/include/libvirt/libvirt-nodedev.h
  /usr/local/include/libvirt/libvirt-nwfilter.h
  /usr/local/include/libvirt/libvirt-qemu.h
  /usr/local/include/libvirt/libvirt-secret.h
  /usr/local/include/libvirt/libvirt-storage.h
  /usr/local/include/libvirt/libvirt-stream.h
  /usr/local/include/libvirt/libvirt.h
  /usr/local/include/libvirt/virterror.h
  /usr/local/include/mach-o/kld.h
  /usr/local/include/mpc.h
  /usr/local/include/mpf2mpfr.h
  /usr/local/include/mpfr.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/neaacdec.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/SDL/begin_code.h
  /usr/local/include/SDL/close_code.h
  /usr/local/include/SDL/SDL.h
  /usr/local/include/SDL/SDL_active.h
  /usr/local/include/SDL/SDL_audio.h
  /usr/local/include/SDL/SDL_byteorder.h
  /usr/local/include/SDL/SDL_cdrom.h
  /usr/local/include/SDL/SDL_config.h
  /usr/local/include/SDL/SDL_cpuinfo.h
  /usr/local/include/SDL/SDL_endian.h
  /usr/local/include/SDL/SDL_error.h
  /usr/local/include/SDL/SDL_events.h
  /usr/local/include/SDL/SDL_getenv.h
  /usr/local/include/SDL/SDL_joystick.h
  /usr/local/include/SDL/SDL_keyboard.h
  /usr/local/include/SDL/SDL_keysym.h
  /usr/local/include/SDL/SDL_loadso.h
  /usr/local/include/SDL/SDL_main.h
  /usr/local/include/SDL/SDL_mouse.h
  /usr/local/include/SDL/SDL_mutex.h
  /usr/local/include/SDL/SDL_name.h
  /usr/local/include/SDL/SDL_opengl.h
  /usr/local/include/SDL/SDL_platform.h
  /usr/local/include/SDL/SDL_quit.h
  /usr/local/include/SDL/SDL_rwops.h
  /usr/local/include/SDL/SDL_stdinc.h
  /usr/local/include/SDL/SDL_syswm.h
  /usr/local/include/SDL/SDL_thread.h
  /usr/local/include/SDL/SDL_timer.h
  /usr/local/include/SDL/SDL_types.h
  /usr/local/include/SDL/SDL_version.h
  /usr/local/include/SDL/SDL_video.h
  /usr/local/include/streams/streams.h
  /usr/local/include/streams/streamsextra.h
  /usr/local/include/tclThread.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/x264.h
  /usr/local/include/x86_64/libiberty/ansidecl.h
  /usr/local/include/x86_64/libiberty/demangle.h
  /usr/local/include/x86_64/libiberty/dyn-string.h
  /usr/local/include/x86_64/libiberty/fibheap.h
  /usr/local/include/x86_64/libiberty/floatformat.h
  /usr/local/include/x86_64/libiberty/hashtab.h
  /usr/local/include/x86_64/libiberty/libiberty.h
  /usr/local/include/x86_64/libiberty/objalloc.h
  /usr/local/include/x86_64/libiberty/partition.h
  /usr/local/include/x86_64/libiberty/safe-ctype.h
  /usr/local/include/x86_64/libiberty/sort.h
  /usr/local/include/x86_64/libiberty/splay-tree.h
  /usr/local/include/x86_64/libiberty/ternary.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libcheck.la
  /usr/local/lib/libfaac.la
  /usr/local/lib/libfaad.la
  /usr/local/lib/libmp3lame.la
  /usr/local/lib/libmpc.la
  /usr/local/lib/libmpfr.la
  /usr/local/lib/libpyglib-gi-2.0-python2.la
  /usr/local/lib/libSDL.la
  /usr/local/lib/libSDLmain.la
  /usr/local/lib/libvirt-admin.la
  /usr/local/lib/libvirt-lxc.la
  /usr/local/lib/libvirt-qemu.la
  /usr/local/lib/libvirt.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/libavcodec.pc
  /usr/local/lib/pkgconfig/libavdevice.pc
  /usr/local/lib/pkgconfig/libavformat.pc
  /usr/local/lib/pkgconfig/libavutil.pc
  /usr/local/lib/pkgconfig/libswscale.pc
  /usr/local/lib/pkgconfig/libvirt-lxc.pc
  /usr/local/lib/pkgconfig/libvirt-qemu.pc
  /usr/local/lib/pkgconfig/libvirt.pc
  /usr/local/lib/pkgconfig/sdl.pc
  /usr/local/lib/pkgconfig/x264.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libavcodec.a
  /usr/local/lib/libavdevice.a
  /usr/local/lib/libavformat.a
  /usr/local/lib/libavutil.a
  /usr/local/lib/libfaac.a
  /usr/local/lib/libfaad.a
  /usr/local/lib/libiberty.a
  /usr/local/lib/libkld.a
  /usr/local/lib/libmp3lame.a
  /usr/local/lib/libmpc.a
  /usr/local/lib/libmpfr.a
  /usr/local/lib/libSDL.a
  /usr/local/lib/libSDLmain.a
  /usr/local/lib/libstreams.a
  /usr/local/lib/libstreams_debug.a
  /usr/local/lib/libstreams_profile.a
  /usr/local/lib/libswscale.a
  /usr/local/lib/libx264.a

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /Users/john/Documents/Development/Projects/Qemu/qemu-1.2.0/ppc-softmmu/

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install isl@0.12 ncurses

Run `brew missing` for more details.

To help us debug your issue please explain:
- What you were trying to do (and why):  
I was trying to install libepoxy.

- What happened (include command output):
This error message displayed: 
Error: pkg-config: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb:1: syntax error, unexpected <<
<<<<<<< HEAD
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb:38: syntax error, unexpected ===, expecting end-of-input
=======
   ^

- What you expected to happen
I expected libepoxy to install.

- Step-by-step reproduction instructions (by running `brew` commands)
brew install libepoxy

**Comment by MikeMcQuaid** [comment]
Try `brew update-reset`.

**Comment by programmingkidx** [comment]
Thank you for the help. This appeared to have fixed the problem.
