### ISSUE TITLE
[Feature-Request] ability to dump linked formula into a new tap

### ISSUE THREAD

**Issue by devrelm** [Homebrew/brew#3040]
There's always much wailing and grinding of teeth around brew's lack of package versioning — an issue which just bit me hard and lost me a couple days' work — but I get it, being able to install a specific version is a feature that's not going to happen.

The common suggestion is to build your own tap, but that itself can be difficult and require rooting around for individual formulas, their dependencies' formulas, and so on.

I would like to suggest a sort-of "snapshot" feature, similar to [`brew bundle dump`](/Homebrew/homebrew-bundle#dump), which creates a new tap with the formula files for all of the *currently linked* kegs.

We could do this as an extension of the `tap-new` command:

`brew tap-new dump user/repo`

or as it's own command:

`brew tap-dump user/repo`

In the latter case, we could have the command dump the formula into an existing tap, or create a new one if the specified tap does not already exist. I'm kinda against dumping into an existing tap as an mvp though, just because then we have to handle overwriting files gracefully (though we could also just go with overwrite-by-default and let the user decide what gets committed.)

#### Notes:

* "currently linked" is highlighted above, because it is relevant. We want the formula for the version that is installed, which is not necessarily the one at the HEAD of whatever tap it came from.
* We  might have to specifically check for when "tap" is `homebrew/homebrew` (and maybe `homebrew/legacy-homebrew` in the install receipt to prevent attempting to get the formula from `Homebrew/homebrew-homebrew`. (This logic may already exist somewhere -- I haven't checked how the tap resolution works.)

**Comment by MikeMcQuaid** [comment]
> an issue which just bit me hard and lost me a couple days' work

You're using an open-source project run by volunteers and provided to you free of charge. As a result, I really don't appreciate this sort of tone on issues: this is the way Homebrew has always worked and always will. Homebrew doesn't do anything without you running a `brew` command first so it's your responsibility and not ours to make sure that doesn't break your work.

You've also not filled out the formula template for features so: closing this.

**Comment by devrelm** [comment]
@MikeMcQuaid No tone implied. I was simply expressing the reason that I tried to think up the idea in the first place, while trying to fulfil the "how it would be relevant" part of the template.

And as someone who has been getting more and more into open-source over the past year, I surely didn't mean to imply that I wouldn't be happy to work on this myself. I merely wanted to put the issue out there for discussion and refinement rather than putting in 10+ hours on a PR that could very well get rejected outright as not relevant, or not the right way to go about doing it.

Also:

> You've also not filled out the formula template for features so: closing this.

The "Or propose a feature" section reads:

> Please replace this section with a detailed description of your proposed feature, the motivation for it, how it would be relevant to at least 90% of Homebrew users and alternatives considered.
Please note we will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

I'm not sure what part I missed. Do I need to also fill out the checklist at the top even though this isn't a bug? Or do I just need to fill out more detail?

**Comment by MikeMcQuaid** [comment]
> No tone implied. I was simply expressing the reason that I tried to think up the idea in the first place, while trying to fulfil the "how it would be relevant" and "the motivation for it" parts of the template.

Ok. For future generally directly or indirectly suggesting Homebrew is responsible for you losing your work is not a good way to start an issue.

> I surely didn't mean to imply that I wouldn't be happy to work on this myself.

Good to know, thanks.

> I'm not sure what part I missed. Do I need to also fill out the checklist at the top even though this isn't a bug? Or do I just need to fill out more detail?

I'm missing the bits for how it would be relevant to 90% of users and what alternatives you've considered.

---

This seems like something that could be a useful external command (e.g. like https://github.com/homebrew/homebrew-bundle) for some people. https://docs.brew.sh/Versions.html is the approach we're taking to support older versions. We wouldn't want to include a command like this in Homebrew/brew as it makes it too easy for users to sit on old versions and never hear about critical security updates.
