### ISSUE TITLE
Installation from URLs

### ISSUE THREAD

**Issue by ozgurakgun** [Homebrew/brew#3042]
Hi,

I'd like to host a formula somewhere and install it via brew. I was not sure if this was possible, but I came across this old [commit](https://github.com/Homebrew/legacy-homebrew/commit/03fa983b5d083443da762bb70bffb612c89cd1fb) which seems to suggest that it is a feature.

Is it supported?

Currently when I try it I get the following output.

```
~/repos/github/conjure> brew install http://raw.githubusercontent.com/conjure-cp/conjure/homebrew/homebrew.rb
######################################################################## 100.0%
Error: undefined method `new' for Homebrew:Module
/usr/local/Homebrew/Library/Homebrew/compat/global.rb:9:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:45:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:43:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:43:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Always fill out the issue template, please.

Your formula needs to be in a file named `conjure.rb`.

**Comment by ozgurakgun** [comment]
Thanks for the reply. I wasn't sure if the template was applicable in this instance, but I'll fill it as much as possible in the future.

**Comment by MikeMcQuaid** [comment]
> but I'll fill it as much as possible in the future.

Please fill it in entirely in every issue, thanks.



> I wasn't sure if the template was applicable in this instance

It says:

> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.
