### ISSUE TITLE
Custom brew installation path causes issue in brew bundle

### ISSUE THREAD

**Issue by ahmetb** [Homebrew/brew#3045]
I installed brew to `~/homebrew` with:

    mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew

then added its bin/ directory to my PATH:

```sh
$ which brew
/Users/ahmetb/homebrew/bin/brew
```

Now when I try to use `brew bundle --global` (I have a ~/.Brewfile), it fails with the following error:

```
$ brew bundle --global
==> Tapping homebrew/bundle
Cloning into '/Users/ahmetb/homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Counting objects: 59, done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 59 (delta 5), reused 14 (delta 0), pack-reused 0
Unpacking objects: 100% (59/59), done.
Tapped 0 formulae (130 files, 166.9KB)
fatal: Not a git repository (or any of the parent directories): .git
Error: no time information in ""
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/time.rb:327:in `parse'
/Users/ahmetb/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:38:in `block in <top (required)>'
/Users/ahmetb/homebrew/Library/Homebrew/extend/pathname.rb:337:in `block in cd'
/Users/ahmetb/homebrew/Library/Homebrew/extend/pathname.rb:337:in `chdir'
/Users/ahmetb/homebrew/Library/Homebrew/extend/pathname.rb:337:in `cd'
/Users/ahmetb/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:37:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/ahmetb/homebrew/Library/Homebrew/utils.rb:20:in `require?'
/Users/ahmetb/homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

- If I run `brew doctor` at this point &rarr; command runs indefinitely

- If I run `brew update`, and then `brew bundle --global` &rarr; it works fine.

It seems like there's an precondition issue in `bundle global` when `brew update` has never been executed.

**Comment by JCount** [comment]
Could you provide the output of `brew config`, or does it behave like `brew doctor`?

**Comment by JCount** [comment]
Corresponding issue https://github.com/Homebrew/homebrew-bundle/issues/282 opened

**Comment by JCount** [comment]
@ahmetb I would suggest just removing `/Users/ahmetb/homebrew/Library/Taps/homebrew/homebrew-bundle`, and trying again, and if that doesn't work it may simplest to just remove the HOME directory installation and start from scratch.

Even though the PR to fix the underlying "bug" closed this issue, please feel free to continue posting to this thread if you continue to have issues.
