### ISSUE TITLE
some Formula of not installed tap appeared, after I run "brew search php".

### ISSUE THREAD

**Issue by mpco** [Homebrew/brew#3049]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?

*****

I run "brew search php"
then it output:

```
homebrew/php/brew-php-switcher
homebrew/php/php-install
homebrew/php/php-plantumlwriter
homebrew/php/php-version
homebrew/php/php-cs-fixer
homebrew/php/php-code-sniffer
homebrew/php/php-build
caskroom/cask/netbeans-php
caskroom/cask/eclipse-php
homebrew/nginx/php-session-nginx-module
homebrew/php/php-code-sniffer@2.9
```
but, I didn't install php tap.
Why? Thank you.

**Comment by MikeMcQuaid** [comment]
We search all official taps.
