### ISSUE TITLE
brew search take 30+ seconds

### ISSUE THREAD

**Issue by forthrin** [Homebrew/brew#3056]
A Brew search takes 30+ seconds, which seems strangely long.

```
$ time brew search urlwatch
No formula found for "urlwatch".

real	0m37.175s
user	0m35.039s
sys	0m0.718s
```

I noticed `traceroute` struggles. Is there a problem in the Github server park? (However, searches and updates have been slow for as long as I can remember, so it doesn't seem like a temporary issue.)

```
$ time traceroute github.com
traceroute: Warning: github.com has multiple addresses; using 192.30.253.112                                                                                                
traceroute to github.com (192.30.253.112), 64 hops max, 52 byte packets
 6  85.19.120.129 (85.19.120.129)  7.791 ms
    85.19.122.237 (85.19.122.237)  7.955 ms
    85.19.120.129 (85.19.120.129)  7.351 ms
 7  4.68.72.25 (4.68.72.25)  7.161 ms  7.898 ms  6.843 ms
 8  * * *
 9  github-inc.bear1.washington111.level3.net (4.53.116.102)  114.132 ms  118.557 ms
    github-inc.bear1.washington111.level3.net (4.15.136.22)  118.196 ms
10  * * *
11  * * *
12  lb-192-30-253-112-iad.github.com (192.30.253.112)  118.241 ms  119.489 ms  117.420 ms

real  0m45.922s
user  0m0.007s
sys 0m0.011s
$

```

- [x] Confirmed this is a problem with running a `brew` command?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 945239ea8908a69dc1466c85fbf61a929becc416
Core tap last commit: 42 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11

```

**Comment by MikeMcQuaid** [comment]
Don't create duplicate issues, please: https://github.com/Homebrew/homebrew-core/issues/16783

**Comment by MikeMcQuaid** [comment]
> You haven't said anything about why the search is taking so long. Is it because Homebrew has to make a roundtrip to thousands of repositories to retrieve information?

I've opened https://github.com/Homebrew/brew/pull/3059 to add output which will explain why it takes the time it does. In short: it's searching local taps, then remote taps on GitHub using their API then blacklisted formulae, then formulae migrated to other taps and finally (if it can't find any results anywhere else) checking the entire history of the Homebrew project to see if this formula was ever present.

> Shouldn't this be cached in a central place, even possibly locally, since Homebrew is updated on a daily basis, and a database table representing relevant search data couldn't take up much space.

Perhaps it should but it currently isn't and implementing this would be a non-trivial task (that we'd welcome pull requests for).

**Comment by forthrin** [comment]
It's not uncommon for successful projects to run into issues where optimisation is needed. I understand that fixing it is not trivial.

How long does each phase take (local, remote, blacklisted, migrated, history)?

If most of the formulae most people are interested in are in the first couple of categories, and these are quick compared to the latter, could a workaround be a command line controlling the search depth?

    brew search popular-brew
    brew search --deep obscure-brew

Another could be to interactively inform the user about each new search stage, so you can Ctrl+C when find you deem it unlikely you'll find what you were looking for, but I think I would find that annoying.

The ideal situation is a search that returns results and the command prompt as soon as possible.

**Comment by MikeMcQuaid** [comment]
> Another could be to interactively inform the user about each new search stage, so you can Ctrl+C when you deem it unlikely you'll find what you were looking for, but I think I would find that annoying.

This now happens.

**Comment by forthrin** [comment]
Well, you're right, but for the novel user the output is not very intuitive (though brevity is mostly a good thing!) Anyway, I hope searches (and updates, since they started happening daily some time ago) will be blazingly fast some day soon. Homebrew is impressively smooth and problem-free, but this is a bit of sirup in the cogwheels.

**Comment by MikeMcQuaid** [comment]
We've tried to make both as fast as possible. Any additional work will need to come from the community.
