### ISSUE TITLE
Node 8.4

### ISSUE THREAD

**Issue by nickmccurdy** [Homebrew/brew#3062]
# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Install Node 8.4 stable.
- What happened (include command output)
Only Node 8.3.x was available.
- What you expected to happen
8.4 is available.
- Step-by-step reproduction instructions (by running `brew` commands)
`brew upgrade node`

**Comment by ilovezfs** [comment]
In the future please open a pull request. In this case, one has already been opened: https://github.com/Homebrew/homebrew-core/pull/16845.

**Comment by nickmccurdy** [comment]
Sorry and thanks, I didn't see that one.

**Comment by MikeMcQuaid** [comment]
> Ran brew config and brew doctor and included their output with your issue?

Do this in all future issues.
