### ISSUE TITLE
FAQ entry for "My Mac .apps don’t find /usr/local/bin utilities!" is outdated

### ISSUE THREAD

**Issue by akalin** [Homebrew/brew#3064]
It says:

> If you’re on Mountain Lion, you can fix this by running launchctl setenv PATH "/usr/local/bin:$PATH".

however this changed again with 10.8.4: see https://apple.stackexchange.com/a/94972 .

Looks like, at least since 10.10, one should do `sudo launchctl config user path /usr/local/bin/:$PATH`, per https://apple.stackexchange.com/a/198282 .

**Comment by MikeMcQuaid** [comment]
> Looks like, at least since 10.10, one should do sudo launchctl config user path /usr/local/bin/:$PATH, per https://apple.stackexchange.com/a/198282 .

Could you try and open a pull request to adjust this? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!
