### ISSUE TITLE
How to figure out what's triggering "Calling fails_with :llvm is deprecated!" in formula.rb and software_spec.rb

### ISSUE THREAD

**Issue by HodorTheCoder** [Homebrew/brew#3065]
Hello,

Recently after updating brew I started getting this output whenever installing or upgrading packages:

> Warning: Calling fails_with :llvm is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Homebrew/formula.rb:2373:in `fails_with'
> 
> Warning: Calling fails_with :llvm is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'
> 
> Warning: Calling fails_with :llvm is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'
> 
> Warning: Calling fails_with :llvm is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'

I've grep'd the entire directory structure but cannot seem to find what package might be causing these warnings-- is there any way to do a super verbose output during an upgrade to see what might be causing these?  I tried doing a 

`brew list -1 | xargs brew install`

to see if I could single out what was causing it but no dice.

Thanks

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

**Comment by HodorTheCoder** [comment]
My bad, I'm an idiot.  Will re-do.
