### ISSUE TITLE
Can't figure out why I am getting "fails_with :llvm is deprecated!" warnings all the sudden.

### ISSUE THREAD

**Issue by HodorTheCoder** [Homebrew/brew#3066]
Since updating homebrew a little while ago-- cannot remember when exactly-- I now get :llvm is deprecated warnings from software_spec.rb and formula.rb every time I run brew doctor, install, or upgrade.  I cannot seem to pinpoint if this is a brew error or a formula error-- I tried grepping for any formulas that use llvm as the compiler but didn't find any.  Is there a way to turn on ultra-verbosity when doing a regular maintenance brew command to find out what's calling the code to evoke the warnings?  If not, that would be a great feature.

I tried doing this to see if I could determine if a specific formula was causing things but it didn't yield any results:

`brew list -1 | xargs brew install`

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

 $ brew config

> HOMEBREW_VERSION: 1.3.1-17-g0933686
> ORIGIN: https://github.com/Homebrew/brew.git
> HEAD: 0933686dea7f65043480f8f7d6a1ceb05bf83238
> Last commit: 9 days ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: 94648578e96a60ca43d3366c033b3c25a0d00bcb
> Core tap last commit: 2 hours ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_REPOSITORY: /usr/local/Homebrew
> HOMEBREW_CELLAR: /usr/local/Cellar
> HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
> CPU: octa-core 64-bit haswell
> Homebrew Ruby: 2.0.0-p648
> Clang: 8.1 build 802
> Git: 2.14.1 => /usr/local/bin/git
> Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
> Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
> Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
> Java: 1.8.0_73
> macOS: 10.12.6-x86_64
> Xcode: 8.3.3
> CLT: 8.3.2.0.1.1492020469
> X11: 2.7.11 => /opt/X11

$ brew doctor

> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!
> 
> Warning: Calling fails_with :llvm is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Homebrew/formula.rb:2373:in `fails_with'
> 
> Warning: Calling fails_with :llvm is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'
> 
> Warning: Calling fails_with :llvm is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'
> 
> Warning: Calling fails_with :llvm is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'
> **Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to install or upgrade any packages causes the llvm warnings above.

- What happened (include command output)
See above warnings.  Happens anytime I do an install, update or upgrade, or brew doctor.

- What you expected to happen
No warnings.

- Step-by-step reproduction instructions (by running `brew` commands)

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it, how it would be relevant to at least 90% of Homebrew users and alternatives considered.
Please note we will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
What's the output of
```
brew tap
find /usr/local/Cellar -regex '.*\.rb' -exec grep -r fails_with {} \;
cd /usr/local/Homebrew/Library/Taps
grep -r fails_with .
```

**Comment by HodorTheCoder** [comment]
I actually just figured it out.  It was google-protobuf.  I used

brew list -1 | xargs brew info

and that was the one that spit out the errors.  Uninstalling that it things work.  Not sure why I had google-protobuf and protobuf installed.

Once removing it the warnings went away.

For some closure, your command:

find /usr/local/Cellar -regex '.*\.rb' -exec grep -r fails_with {} \;

also figured out what could have been the problem by finding fails_with llvm.  I was searching in the wrong spit-- /usr/local/Cellar is the correct spot.  Very nice.

Thanks for helping with this.

**Comment by ilovezfs** [comment]
Glad you've figured it out!

**Comment by Sigfried** [comment]
Thanks, @ilovezfs. Your find command

    find /usr/local/Cellar -regex '.*\.rb' -exec grep -r fails_with {} \;

confirmed that I had the same problem as @HodorTheCoder.

    brew tap

hung and gave me other problems because I had other cleanup to do after migrating to a new machine.

So, getting rid of the annoying warning just required:

    brew uninstall google-protobuf
