### ISSUE TITLE
Add a check for branches of tapped repos

### ISSUE THREAD

**Issue by JasonQSY** [Homebrew/brew#3068]
I think it is a good idea to add at least a check for the branches of tapped repos. Generally, we are always using the `master` branch. However, if it is incorrectly switched to another branch like `patch`, it is better that `brew update` or `brew doctor` could have a warning.

The situation is that if we switch to another branch `patch` in `usr/local/Homebrew/Library/Taps/homebrew/homebrew-core`, `brew update` works correctly because it just pull the remote `master` branch to the local one. However, the active branch is `patch` and there is no warning in both `brew update` and `brew doctor`. And if other formulas work correctly   requires a later version of formulas in `homebrew-core`, the installation fails.

It is not a big problem but tough to find the first time... That's why I think adding a check in `brew update` or at least `brew doctor` is a good idea. I could work on it if such a PR is welcomed.

**Comment by alyssais** [comment]
Having a `doctor` warning sounds good to me. 👍

**Comment by MikeMcQuaid** [comment]
@JasonQSY Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by JasonQSY** [comment]
OK. I'll try to work on it.

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/Homebrew/brew/pull/3089.
