### ISSUE TITLE
Caching general formulae information in JSON

### ISSUE THREAD

**Issue by laughedelic** [Homebrew/brew#3072]
I noticed that there's a cache JSON file with a list of formulae and their descriptions in `$HOMEBREW_CACHE/desc_cache.json`. So I was thinking that it would be nice to have such cache for other types of information that Homebrew provides: there are 3 commands (according to documentation) that support `--json` option: `info`, `outdated`, `tap-info`.

As described in the [Querying Brew](https://docs.brew.sh/Querying-Brew.html) tutorial, JSON output is very useful for integrating other tools with brew. But `brew info --json=v1 --all` for example, is very slow (~20s), while it is a static set of information which won't change until next time `brew update` will be called (by user or some other command). So it could be cached and updated automatically by `brew update`. Same about `brew info --json=v1 --installed` and `brew tap-info --json=v1 --installed` (not sure when this gets updated).

My personal motivation: I wrote `brew` completions for Fish shell, and so far for the lists of suggestions I'm using direct output from `brew` and it's _quite slow_. When you type on command line and press <kbd>TAB</kbd> a delay of ~0.5s is noticeable and a delay over 1s is already annoying. 

I made some tests with using the proposed JSON info all/installed cache and Ruby JSON parsing/filter/formatting as needed by Fish completions and the conclusion is that it works roughly **~7-8 times faster**. Of course, it won't be so if I will call `brew info --json=v1 ...` every time.

So while I can generate those JSON files myself, I cannot keep them up to date without brew's help. I think having such JSON cache managed by brew itself will be very useful for any other tools that integrate with brew (including bash/zsh completions, by the way). I don't know anything about Homebrew internals, but probably it could benefit from such caching as well? Or may there is already something like that and I didn't find it in the code?

**Comment by MikeMcQuaid** [comment]
Can you elaborate why you need the output of `brew info --json=v1 --all` to be fast? I can understand `brew tap-info --json=v1 --installed`. 

I'm not opposed to having a JSON cache for some of these commands as long as they do not noticeably increase the current, non-cached runtime and noticeable increase the cached runtime. 

I'm 🆒 with continuing to talk about it in this issue but just closing as this isn't something the maintainers currently plan to work on right now.

**Comment by laughedelic** [comment]
> Can you elaborate why you need the output of brew info --json=v1 --all to be fast? I can understand brew tap-info --json=v1 --installed.

You're right, that `info --installed` is more useful, but there are still a couple of use cases for `info --all` caching:
* when installing a new formula, you want to get its available build options with their description (what `brew options` gives now with some funky formatting), this
* for commands that accept any formula name (even not installed), it's useful to have names with descriptions. This is actually the content of the `desc_cache.json` file, but I'm not sure if it's the same and when it's updated. 

>I'm not opposed to having a JSON cache for some of these commands as long as they do not noticeably increase the current, non-cached runtime and noticeable increase the cached runtime.
>
> I'm 🆒 with continuing to talk about it in this issue but just closing as this isn't something the maintainers currently plan to work on right now.

OK 👍 I can try to make a pull-request.

**Comment by MikeMcQuaid** [comment]
> OK 👍 I can try to make a pull-request.

Great, thanks!

> for commands that accept any formula name (even not installed)

Gotcha, makes sense. Yeh, a JSON cache that's updated on `brew info --installed` and invalidated on `brew update` seems like a good first step. If it's fast enough to rebuild the cache on `brew update` we could consider that too.

**Comment by MikeMcQuaid** [comment]
There's a similar discussion in https://github.com/Homebrew/brew/issues/3007. In general, as I've noted there, in order of preference/priority we/you should: use https://github.com/Homebrew/homebrew-dev-tools/blob/master/cmd/brew-prof.rb to make sure the current code is as fast as it can be with no caching, add an in-process cache to avoid maintaining state between processes, add an on-disk cache to maintain state between processes. Jumping straight to an on-disk cache and having to deal with the inevitable cache invalidation bugs may not be the best idea, now that I've thought more about it.

**Comment by MikeMcQuaid** [comment]
Another thing worth noting: we'll upgrading to Ruby 2.3 when High Sierra is released (or a bit before) which will provide performance improvements itself and add opportunities for others.

**Comment by laughedelic** [comment]
> use https://github.com/Homebrew/homebrew-dev-tools/blob/master/cmd/brew-prof.rb to make sure the current code is as fast as it can be with no caching

I don't understand what this `brew prof` is supposed to do. Commands run much slower than without it:

```
> time brew info --json=v1 --installed > /dev/null
        0.98 real         0.74 user         0.20 sys
> time brew prof info --json=v1 --installed > /dev/null
        4.59 real         4.00 user         0.48 sys
```

----

I have another question. Suppose I'm going to manage some kind of minimal cache needed for my application separately. Are there any external signs of events happening in Homebrew that I could use to know when I can regenerate cache. Can I check when was the last update? Or some other things like whether formula got installed/uninstalled? I don't know, any kind of clues.

**Comment by MikeMcQuaid** [comment]
@laughedelic It's a profiling tool; it calls [ruby-prof](https://github.com/ruby-prof/ruby-prof) on a given Homebrew command and generates output indicating where the time is spent.

> Are there any external signs of events happening in Homebrew that I could use to know when I can regenerate cache.

No, sorry, that's all implementation details and not public APIs. You could try and hack something looking at the code but I cannot guarantee we won't break it in future.

**Comment by laughedelic** [comment]
aah! now I noticed that it creates `prof/` with some reports..
