### ISSUE TITLE
Brew cask search shouldn't fail when offline

### ISSUE THREAD

**Issue by laughedelic** [Homebrew/brew#3080]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

<details><summary>Output of `brew doctor` and `brew config`</summary>

```
> brew doctor
Your system is ready to brew.

> brew config
HOMEBREW_VERSION: 1.3.1-77-g97c75bfd
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 97c75bfd40084cfa2512fe55a7b292886ff6d023
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 280a946338f565223ba6480e84f3cdf2ea7b9fa2
Core tap last commit: 14 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.2.1 => /usr/local/git/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_66
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

</details>

### What you were trying to do (and why)

Get the list of available casks by running `brew cask search`  (without search query)

### What happened (include command output)

It failed, because I was offline.

<details><summary>Error output</summary>

```
Error: curl failed!
curl: (6) Could not resolve host: api.github.com
curl: (3) <url> malformed

Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:284:in `search'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:239:in `search_code'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:18:in `search_remote'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:44:in `search'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

</details>

### What you expected to happen

I would expect `brew cask search` to work similarly to the `brew search` command:

```
brew search, -S:
    Display all locally available formulae for brewing (including tapped ones).
    No online search is performed if called without arguments.
```

So I expected `brew cask search` to return a list of cask tokens **without performing online search**. But even if it does, it shouldn't completely fail, but rather return an empty result in "Remote matches".

### Step-by-step reproduction instructions (by running `brew` commands)

1. turn off internet connection
2. run `brew cask search`

----

The failing line is [here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/cli/search.rb#L44), would be nice if it just returned an empty list of results when it cannot search online. It could output the error message to stderr.

Another thing is that I think it shouldn't search online at all, when run without arguments. I found [this piece of code](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/scopes.rb#L16-L22) that seems to do what I expect:

```
Tap.flat_map { |t| t.cask_files.map { |p| "#{t.name}/#{File.basename(p, ".rb")}" } }
```

(by the way, how can I call `Hbc.all_tokens` in `brew irb` directly?)

**Comment by laughedelic** [comment]
I have a partial fix here: https://github.com/laughedelic/brew/commit/00803b1a0b2a302a84871a05ae2abbdfe7f01a5c:

> brew cask search without query just outputs all available cask tokens

Unfortunately I have no idea about catching exceptions in Ruby, so I don't know how to solve the other thing (returning an empty list from a failed `search_remote`).

**Comment by reitermarkus** [comment]
> (by the way, how can I call `Hbc.all_tokens` in brew irb directly?)

You have to call `cask` first to load the `Hbc` namespace. This isn't documented, so I think this should probably always be initialized.

> I have a partial fix here

Would be great if you could send a PR, which is easier to review.

> I have no idea about catching exceptions in Ruby,

You don't catch them, you `rescue` them, so grep for `rescue`. 😉

**Comment by laughedelic** [comment]
> You have to call cask first to load the Hbc namespace. This isn't documented, so I think this should probably always be initialized.

Thanks, it works. I'm totally unfamiliar with Ruby and irb, so I thought I'm missing some import/require. 

> Would be great if you could send a PR, which is easier to review.

Sure, I was going to. But I ran tests and got some failure, although I'm getting the same on master. I will open the PR anyway and write the details there.

> You don't catch them, you rescue them, so grep for rescue. 😉

OK, I got something 👍  thanks.

**Comment by laughedelic** [comment]
@reitermarkus I just submitted #3084 with some questions about testing.
