### ISSUE TITLE
Not sure what's happening...

### ISSUE THREAD

**Issue by chrisfinazzo** [Homebrew/brew#309]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Not really a bug per se, but when I ran `brew update` the following happened:

<img width="753" alt="screen shot 2016-06-01 at 11 21 14 am" src="https://cloud.githubusercontent.com/assets/1534882/15715040/03cae72c-27eb-11e6-9e74-7e764e5cee65.png">

Can someone point me to the commit which explains this change?

**Comment by MikeMcQuaid** [comment]
> Can someone point me to the commit which explains this change?

https://github.com/Homebrew/brew/pull/292 should help. If not, ask any other questions you have here.

**Comment by chrisfinazzo** [comment]
Ah. That explains it.

Although Homebrew is reasonably protected from SIP changes by putting formulae in `/usr/local`, using the root level Library for other stuff makes me nervous that something _could_ happen, even if `/Library` is also considered safe.

It's more portable now, too 😀.
