### ISSUE TITLE
brew doctor always reporting "Homebrew/homebrew-core is not on the master branch"

### ISSUE THREAD

**Issue by jabenninghoff** [Homebrew/brew#3092]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

After running `brew update`, `brew doctor` is always reporting:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew/homebrew-core is not on the master branch

Check out the master branch by running:
  git -C "$(brew --repo homebrew/core)" checkout master
```
running `git -C "$(brew --repo homebrew/core)" checkout master` reports:
```
Already on 'master'
Your branch is up-to-date with 'origin/master'.
```
It appears to be related to this commit: https://github.com/Homebrew/brew/commit/db41f9d1182ff8c4c3b42b458e38d5c58b496ffb

Here is my `brew config`:
```
HOMEBREW_VERSION: 1.3.1-107-gdb41f9d
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: db41f9d1182ff8c4c3b42b458e38d5c58b496ffb
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0ee61ba4e9863bfb109e719a29c9690aec27343c
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/agamemnon/.rbenv/shims/ruby => /Users/agamemnon/.rbenv/versions/2.1.10/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```
This appears to be a spurious warning message and not a real problem.

**Comment by ilovezfs** [comment]
Thanks for reporting this @jabenninghoff. It should be fixed now via https://github.com/Homebrew/brew/pull/3093.

**Comment by retokromer** [comment]
Yes, it’s fixed. Thank you!
