### ISSUE TITLE
"brew --prefix <formula>" is slow: ~0.5-0.8s

### ISSUE THREAD

**Issue by henrahmagix** [Homebrew/brew#3097]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

`brew config`
```
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 436f8829ea7895aaabf41e80666bde5bc3f189ce
Core tap last commit: 82 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.14.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/henry/.rbenv/shims/ruby => /Users/henry/.rbenv/versions/2.1.1/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

`brew doctor`
```
Your system is ready to brew.
```

To help us debug your issue please explain:
## What you were trying to do (and why)
I was trying to speed up my "new shell" time and discovered that `source $(brew --prefix autoenv)/activate.sh` was taking a long time. I'm using `brew --prefix <formula>` to get the path to the installed formula.

## What happened (include command output)
Giving any installed formula to `brew --prefix` results in a long wait (well, long in new shell terms).
```
$: time brew --prefix autoenv
/usr/local/opt/autoenv

real    0m1.138s
user    0m0.510s
sys 0m0.372s

$: time brew --prefix autoenv
/usr/local/opt/autoenv

real    0m0.616s
user    0m0.400s
sys 0m0.187s
```

## What you expected to happen
I expected the command to be about as quick as `brew --prefix`, which has been shown to be fast in #2938 (it also takes about 0.03s on my machine).

# Step-by-step reproduction instructions (by running `brew` commands)
This is just more invocations using different formulae.

```
$: time brew --prefix autoenv
/usr/local/opt/autoenv

real    0m0.579s
user    0m0.393s
sys 0m0.172s


$: time brew --prefix git
/usr/local/opt/git

real    0m1.281s
user    0m0.497s
sys 0m0.439s

$: time brew --prefix lftp
/usr/local/Cellar/lftp/4.8.0

real    0m0.638s
user    0m0.427s
sys 0m0.180s

$: time brew --prefix the_silver_searcher
/usr/local/opt/the_silver_searcher

real    0m0.808s
user    0m0.456s
sys 0m0.252s

$: time brew --prefix hub
/usr/local/opt/hub

real    0m0.818s
user    0m0.469s
sys 0m0.257s

$: time brew --prefix imagemagick
/usr/local/opt/imagemagick

real    0m0.596s
user    0m0.399s
sys 0m0.165s

$: time brew --prefix imagemagick
/usr/local/opt/imagemagick

real    0m0.642s
user    0m0.414s
sys 0m0.201s

$: time brew --prefix imagemagick
/usr/local/opt/imagemagick

real    0m0.583s
user    0m0.395s
sys 0m0.167s
```

# Features
N/A

**Comment by henrahmagix** [comment]
Sorry! Submitted too soon: editing now...

**Comment by JCount** [comment]
Try simply avoiding the MRI and just using shell scripting with something like:
```
$(dirname $(dirname $(which brew)))/opt/autoenv/activate.sh
```

**Comment by MikeMcQuaid** [comment]
We'll accept pull requests to make this faster. For future reference: we don't consider things like this to be a bug.

**Comment by henrahmagix** [comment]
Thanks both!
