### ISSUE TITLE
Symlink broken in HOMEBREW_CACHE

### ISSUE THREAD

**Issue by tomyun** [Homebrew/brew#310]
### Bug reports:

Just found a broken link in the HOMEBREW_CACHE after recent migration (#292). In my `/Users/.../Library/Caches/Homebrew/Casks` directory, `java-1.8.0_60-b27.dmg` is still symlinked to `/Library/Caches/Homebrew/java-1.8.0_60-b27.dmg` which no longer exists. I'd simply clear it myself, but just wanted to ensure if it's not a hidden glitch of new migration process.

**Comment by UniqMartin** [comment]
I'm pretty sure this isn't a glitch but a broken symlink that already existed before the migration, as I'm pretty sure `java-1.8.0_60-b27.dmg` shouldn't have been placed directly in the Homebrew cache in the first place. Thanks for the heads up and feel free to clear it yourself!

After all it's only a cache and not vital to the operation of either Homebrew or Cask, as things will be (re)downloaded as needed and the particular file in question is an outdated version of Java.
