### ISSUE TITLE
dependency ignoring (older) already installed version

### ISSUE THREAD

**Issue by ccutrer** [Homebrew/brew#3104]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 793b4238aab2066d3d67cd8f9447a1e30074bc05
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/cody/.rubies/ruby-2.4.1/bin/ruby
Java: 1.8.0_121
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: N/A
X11: 2.7.11 => /opt/X11
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

I'm trying to install `pex`, which has a dependency on `postgresql`, of which I have `postgresql@9.5` installed, and `brew info pex` shows that the dependency is satisfied, but if I try to `brew install pex`, it starts downloading the latest `postgresql` anyway.

To repro:

```
brew install postgresql@9.5
brew install pex
```

More details of the installed packages:

```
$ brew info postgresql@9.5
postgresql@9.5: stable 9.5.8 (bottled) [keg-only]
Object-relational database system
https://www.postgresql.org/
/usr/local/Cellar/postgresql@9.5/9.5.8 (3,173 files, 35.3MB)
  Poured from bottle on 2017-08-29 at 10:23:40
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgresql@9.5.rb
...
```

```
$ brew info pex
pex: stable 1.20140409 (bottled)
Package manager for PostgreSQL
https://github.com/petere/pex
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pex.rb
==> Requirements
Required: postgresql ✔
...
```

```
$ brew install pex
==> Installing dependencies for pex: postgresql
==> Installing pex dependency: postgresql
==> Downloading https://homebrew.bintray.com/bottles/postgresql-9.6.4.sierra.bottle.tar.gz
...
```

**Comment by MikeMcQuaid** [comment]
> I'm trying to install pex, which has a dependency on postgresql, of which I have postgresql@9.5 installed, and brew info pex shows that the dependency is satisfied, but if I try to brew install pex, it starts downloading the latest postgresql anyway.

Installing bottles means that the requirement's `default_formula` will always be used and installed. Either ignore the duplicated versioned installed or `brew install pex --build-from-source` to work around this behaviour.

**Comment by ccutrer** [comment]
yup, that works. it still would be nice if there was a warning when I installed pex along the lines of `Ignoring versioned dependency postgresql@9.5 due to bottle install. To force using this dependency, please use --build-from-source`

**Comment by ccutrer** [comment]
Sigh. Same situation. Different package.

`brew install postgis --build-from-source` is still pouring postgresql 9.6.4 from bottle. It IS showing that `postgresql` dependency isn't satisfied though.

```
$ brew info postgis
brew info postgis
postgis: stable 2.3.2 (bottled), HEAD
Adds support for geographic objects to PostgreSQL
https://postgis.net/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgis.rb
==> Dependencies
Build: pkg-config ✔, gpp ✔
Required: postgresql ✘, proj ✘, geos ✘, json-c ✔, pcre ✘
Recommended: gdal ✘, sfcgal ✘
```

I think brew just really wants me to start using Postgres 9.6 ;)

**Comment by MikeMcQuaid** [comment]
> brew install postgis --build-from-source is still pouring postgresql 9.6.4 from bottle.

Yes, `postgis`doesn't support using arbritrary versions in Homebrew.

> I think brew just really wants me to start using Postgres 9.6 ;)

It really wants you to have it installed, yep.
