### ISSUE TITLE
Can't uninstall packages that I installed with home-brew. 

### ISSUE THREAD

**Issue by MuhammedKpln** [Homebrew/brew#3115]
1. i was trying to uninstall an app that I installed with home-brew. 
2. Then I realize that I can't uninstall and getting 
`Error: No such keg: /usr/local/Cellar/vivaldi`

I have tried brew doctor and it didn't fix the problem. And here is my config file if anyone considering.

[My config file at ubuntu paste.](http://paste.ubuntu.com/25444891/)

[And here is the detailed short video](https://streamable.com/1gyyg)

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by MuhammedKpln** [comment]
Edited.

**Comment by MikeMcQuaid** [comment]
@MuhammedKpln We still don't have your `brew doctor` output or the `brew` commands you've run to produce your error.
