### ISSUE TITLE
`Could not link ...homebrew/share/doc/homebrew` error on install

### ISSUE THREAD

**Issue by akalin** [Homebrew/brew#3117]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new

When doing a manual homebrew install, I get a strange error. From `/tmp`:

```
$ mkdir hbtmp
$ cd hbtmp/
$ mkdir homebrew && curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C homebrew
$ ./homebrew/bin/brew update
Initialized empty Git repository in /private/tmp/hbtmp/homebrew/.git/
remote: Counting objects: 1119, done.
remote: Compressing objects: 100% (1029/1029), done.
remote: Total 1119 (delta 116), reused 379 (delta 50), pack-reused 0
Receiving objects: 100% (1119/1119), 1.20 MiB | 5.45 MiB/s, done.
Resolving deltas: 100% (116/116), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
HEAD is now at 8187776 Merge pull request #3112 from mistydemeo/search_online_failure
To restore the stashed changes to /private/tmp/hbtmp/homebrew run:
  'cd /private/tmp/hbtmp/homebrew && git stash pop'
==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics.html

==> Tapping homebrew/core
Cloning into '/private/tmp/hbtmp/homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4556, done.
remote: Compressing objects: 100% (4345/4345), done.
remote: Total 4556 (delta 36), reused 457 (delta 12), pack-reused 0
Receiving objects: 100% (4556/4556), 3.64 MiB | 6.44 MiB/s, done.
Resolving deltas: 100% (36/36), done.
Tapped 4342 formulae (4,601 files, 11.4MB)
Already up-to-date.
Error: Could not link:
/private/tmp/hbtmp/homebrew/share/doc/homebrew

Please delete these paths and run `brew update`.
```

If I do `rm -rf /path/to/homebrew/share/doc/homebrew` before doing the update, I don't get the error.

Perhaps the tarball shouldn't include that directory at all?

**Comment by MikeMcQuaid** [comment]
We don't support installing in non-default prefixes so I'm afraid you'll need to figure out the solution for this yourself as it's not a widespread issue. We'll accept PRs for fixes, though, if you figure that out.

**Comment by akalin** [comment]
Ah, I see. Interestingly enough, it doesn't happen if I untar to the default prefix. Will investigate more and open a PR...

**Comment by akalin** [comment]
This turned out to be a boneheaded mistake on my part. I had `curl -L https://github.com/Homebrew/homebrew ...` from my notes, which was before the `brew`/`homebrew-core` split, which should now be `curl -L https://github.com/Homebrew/brew ...`. No PR needed!
