### ISSUE TITLE
`brew cleanup -s` does not clean up resources

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#3123]
`brew cleanup -s` fails to clean up all resources that are part of an uninstalled formula.

Example: install wine from source with `brew install -s wine`. Then remove it with `brew rm wine`. Then cleanup with `brew cleanup -s`. After that, in `~/Library/Caches/Homebrew`, the `wine-2.0.2.tar.xz` file has been removed, but the following files — associated with wine resources — are still present:

```
wine--fontconfig-2.12.4.tar.bz2
wine--freetype-2.8.tar.bz2
wine--gd-2.2.4.tar.xz
wine--gecko-x86-2.47.msi
wine--gecko-x86_64-86.64.msi
wine--jpeg-9b.tar.gz
wine--libgphoto2-2.5.14.tar.bz2
wine--libpng-1.6.31.tar.xz
wine--libtiff-4.0.8.tar.gz
wine--libtool-2.4.6.tar.xz
wine--libusb-1.0.21.tar.bz2
wine--little-cms2-2.8.tar.gz
wine--mono-4.7.0.msi
wine--mpg123-1.25.5.tar.bz2
wine--net-snmp-5.7.3.tar.gz
wine--openssl-1.0.2l.tar.gz
wine--patch-1b5086798ce6dc959b3cbb8f343ee236ae06c7910e4bbae7d9fde3f162f03a79.cgi
wine--patch-30766403f5064a115f61de8cacba1defddffe2dd898b59557956400470adc699.cgi
wine--sane-backends-1.0.27.tar.gz
wine--webp-0.6.0.tar.gz
```

**Comment by chdiza** [comment]
If memory serves, `cleanup` has never removed *any* of the resource files besides bottles or the tarballs that correspond to the formula's `url` field.  It might not even remove VCS repos for HEAD builds, I can't recall.

**Comment by fxcoudert** [comment]
As an example, I installed the top 1000 formulas of Homebrew from source. This lead to 9.8 GB of cleanable cache (removed by `brew cleanup -s`) and 6.4 GB of stuff that stays there, even after all formulas are uninstalled and `brew cleanup` is called.

**Comment by ilovezfs** [comment]
I think if you use --prune= it will clean them.

**Comment by MikeMcQuaid** [comment]
Let's fold this into https://github.com/Homebrew/brew/issues/568.
