### ISSUE TITLE
Include a link to Patreon on website?

### ISSUE THREAD

**Issue by nnutter** [Homebrew/brew#3128]
I just stumbled across Linuxbrew which has donation info on their website.  They also linked to the Patreon for Homebrew which I wasn't aware of and was only able to verify it was legit by Googling and finding a reference on a Homebrew [blog entry](https://brew.sh/2017/07/31/homebrew-1.3.0/).  Maybe you should link to Patreon on the Homebrew website?

**Comment by ilovezfs** [comment]
It's in README.md under "Donations."
