### ISSUE TITLE
brew install from source installs unnecessary formulas

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#3130]
# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

----

Having all `mame` dependencies installed (build and run), and installing `mame` from source requires installation of unrelated packages:

```
$ brew info mame
mame: stable 0.189, HEAD
Multiple Arcade Machine Emulator
http://mamedev.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mame.rb
==> Dependencies
Build: pkg-config ✔, sphinx-doc ✔
Required: sdl2 ✔, expat ✔, jpeg ✔, flac ✔, sqlite ✔, portmidi ✔, portaudio ✔, utf8proc ✔
==> Requirements
Required: macOS >= 10.10 ✔

$ brew install -s mame    
==> Installing dependencies for mame: cython
==> Installing mame dependency: cython
[...]
```

I think this is because `cython` is a build dependency of `mame`'s dependency `portmidi`:

```
$ brew info portmidi 
portmidi: stable 217
Cross-platform library for real-time MIDI I/O
https://sourceforge.net/projects/portmedia/
/usr/local/Cellar/portmidi/217_1 (15 files, 192.5KB) *
  Poured from bottle on 2017-09-06 at 14:41:40
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/portmidi.rb
==> Dependencies
Build: cmake ✔, cython ✘
```

However, it still does not make sense: I already have `portmidi` installed, so it should recurse down to its build dependencies.

**Comment by DomT4** [comment]
Same issue as https://github.com/Homebrew/brew/issues/3033 maybe?

**Comment by fxcoudert** [comment]
Right you are!

**Comment by DomT4** [comment]
Confirms it reproduces with formulae other than `wireshark` at least 😭.
