### ISSUE TITLE
macOS 10.13  Upgrading gtk+3

### ISSUE THREAD

**Issue by avelino** [Homebrew/brew#3132]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
```
==> Upgrading gtk+3
==> Installing dependencies for gtk+3: ninja, meson, sphinx-doc, harfbuzz, pango
==> Installing gtk+3 dependency: ninja
==> Downloading https://github.com/ninja-build/ninja/archive/v1.7.2.tar.gz
Already downloaded: /Users/avelino/Library/Caches/Homebrew/ninja-1.7.2.tar.gz
==> python configure.py --bootstrap
Last 15 lines from /Users/avelino/Library/Logs/Homebrew/ninja/01.python:
2017-09-06 10:56:51 -0300

python
configure.py
--bootstrap


Do not report this issue to Homebrew/brew or Homebrew/core!


Error: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Error: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)
```
brew update
brew upgrade
```

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by DomT4** [comment]
> If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new

Since you filed it here though, `brew gist-logs ninja` would be useful for anyone to look at this.
