### ISSUE TITLE
`brew bump-formula-pr` raises error with --devel line of `hub`

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/brew#3136]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue? https://gist.github.com/jasonkarns/7429eb0abd6e3a8bf7ce6764fcc4085b

To help us debug your issue please explain:
- What you were trying to do (and why)

    Trying to bump a formula version to latest, using bump-formula-pr.

- What happened (include command output)

    I received an error about getting the remote from `hub`. I'm currently using the latest pre-release version of hub which will (hopefully?) land soon.

    ```
    HOMEBREW_DEVELOPER=true brew bump-formula-pr --url=https://github.com/nodenv/node-build/archive/v2.6.12.tar.gz --sha256=b0983958ad0dcb746a252473ea20ff1bcccbe200a42ed3332345d350d60b8c41 node-build
    Already up-to-date.
    ==> replace "https://github.com/nodenv/node-build/archive/v2.6.11.tar.gz" with "https://github.com/nodenv/node-build/archive/v2.6.12.tar.gz"
    ==> replace "266170f2a56100125e7a76565ef0796017b3c45891e56db76bd2b233b201194e" with "b0983958ad0dcb746a252473ea20ff1bcccbe200a42ed3332345d350d60b8c41"
    M	Formula/node-build.rb
    Switched to a new branch 'node-build-2.6.12'
    [node-build-2.6.12 ec2f37d81a] node-build 2.6.12
     1 file changed, 2 insertions(+), 2 deletions(-)
    Error: cannot get remote from 'hub'!
    ```

- What you expected to happen

    I expected brew to open a PR with the formula version bumped to latest.

- Step-by-step reproduction instructions (by running `brew` commands)
    1. Be on latest hub:
    ```
    $ hub --version
    git version 2.14.1
    hub version 2.3.0-pre10
    ```
    2. Run brew-bump-formula-pr
    ```
    HOMEBREW_DEVELOPER=true brew bump-formula-pr --url=https://github.com/nodenv/node-build/archive/v2.6.12.tar.gz --sha256=b0983958ad0dcb746a252473ea20ff1bcccbe200a42ed3332345d350d60b8c41 node-build
    ```

Since I'm assuming a lot of homebrew devs rely on hub+bump-formula-pr, I'm assuming that it would be worthwhile to have this issue addressed before the next version of hub officially lands.

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/brew/pull/3061.

**Comment by jasonkarns** [comment]
👍  (i only searched for the error message, so didn't find that one. thanks!)
