### ISSUE TITLE
Using /opt/local instead of /usr/local

### ISSUE THREAD

**Issue by nanocent** [Homebrew/brew#3137]
# Features
Using /opt/local instead of /usr/local to follow the latest standard. 
/opt is recommended for unbundled softwares and /opt/local is the preferred location for installing bundled softwares. Therefore, the users will have the option of installing other packages not via brew in the same location. 
Along with this, the package's configuration can be moved to /etc/opt/<conf>

The main idea came from this thread when I was looking for the standard about the /opt or /usr/local or /usr/local/opt
https://unix.stackexchange.com/questions/11544/what-is-the-difference-between-opt-and-usr-local

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
We will continue using `/usr/local` for the default prefix for the foreseeable future, but thanks for the suggestion. You may be interested in reading https://github.com/Homebrew/brew/blob/master/docs/Installation.md#alternative-installs.

**Comment by nanocent** [comment]
In that case, would it be preferred to install bundled softwares as well at /usr/local/opt ? 
Or is there any other suggestion.

**Comment by ilovezfs** [comment]
I don't know what you mean by "bundled software," but `/usr/local/opt` is already reserved for our unversioned optlinks.

**Comment by nanocent** [comment]
I meant any other software like java or node if installing manually for a specific version.

**Comment by ilovezfs** [comment]
That's up to you, though `brew doctor` will warn about things you manually install in `/usr/local`.

In general, you may want to use `brew cask install` where possible for things like Java.

**Comment by nanocent** [comment]
versioning is currently not possible for some of the softwares like node or java. Any solution for that ?

**Comment by ilovezfs** [comment]
We have node@4, node@6, and node, which is node@8.

**Comment by MikeMcQuaid** [comment]
And random old versions (while they may match your production environment) so aren't a good idea to use.

**Comment by nanocent** [comment]
Brew is doing a great job at providing the softwares for mac os but a bigger thing that is required is simplification for all OS. Ubuntu has apt-get and repos that that is also not organised and users don't know where do the things go in the directory structure. Maybe working on settings the standards is very important so that everything works in sync whether user is using brew or installing directly.
