### ISSUE TITLE
Error: SHA256 mismatch snowboard-1.0.0.tar.gz

### ISSUE THREAD

**Issue by avelino** [Homebrew/brew#3140]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
```
▶ brew install snowboard
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing snowboard from bukalapak/packages
==> Downloading https://github.com/bukalapak/snowboard/releases/download/v0.6.7/snowboard-v0.6.7.darwin-amd64.tar.gz
Already downloaded: /Users/avelino/Library/Caches/Homebrew/snowboard-1.0.0.tar.gz
Error: SHA256 mismatch
Expected: b154026fc945849c09a32a9ab27fe45d20bfd23f8dc3138b277c843257991c74
Actual: a9952539efa488adc7ac57be2612efb7ca133aa08edc21c6155678f296050d20
Archive: /Users/avelino/Library/Caches/Homebrew/snowboard-1.0.0.tar.gz
To retry an incomplete download, remove the file above.
```
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)
```
brew install snowboard
```

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
This should be reported to the tap https://github.com/bukalapak/homebrew-packages/issues not to homebrew/core.

**Comment by avelino** [comment]
Thanks @ilovezfs
