### ISSUE TITLE
All options of OpenCV are gone?

### ISSUE THREAD

**Issue by xionglingfeng** [Homebrew/brew#3155]
This is not a bug report, just a question.

Recently, `OpenCV` is merged from `homebrew/science` to `homebrew/core`. After the merge, it seems the Formula has been entirely changed: all options are gone, `OpenCV` is by default build with many stuffs, including `Python`, `Python3`, `ffmpeg`, etc. There is no way to disable a module (e.g. `Python` and `Python3`), or enable a module (e.g. `CUDA`).
Just wondering if there is a specific reason for removing all the options of this formula?

**Comment by ilovezfs** [comment]
>Just wondering if there is a specific reason for removing all the options of this formula?

To reduce the support burden that arises from unnecessary source builds, and consequent build failures, and to increase the proportion of users that use a configuration that has been tested by our CI.

**Comment by thewoz** [comment]
this is bull shit!
now it is impossible to have opencv with QT
