### ISSUE TITLE
Bottled mongodb not working on High Sierra

### ISSUE THREAD

**Issue by svanimpe** [Homebrew/brew#3157]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/anonymous/b88a23a2e08479c038bc2e8f1106ce1e

After installing mongodb, mongod does not start.

`brew services list` says the service is running, even though it isn't, even after restarting it.

Starting the server manually using `mongod --config /usr/local/etc/mongod.conf` has the same result: nothing happens.

**/usr/local/var/log/mongodb/output.log** is empty.

Running `mongod` directly (after creating `/data/db`) does work.

**Comment by ilovezfs** [comment]
And does it happen if you build from source …

**Comment by MikeMcQuaid** [comment]
> I've managed to install a bottled version of mongodb 3.4.9 using brew install --force-bottle mongodb. This installs fine, but the server never starts.

This is not supported.

Please (rapidly) fill in the issue template or this issue will be closed.

**Comment by svanimpe** [comment]
@ilovezfs I tried that as well, but it has the same problem

@MikeMcQuaid I've updated the issue to use the template. Hope it's OK now.

When you say "not supported", are you referring to `--force-bottle` or High Sierra in general? If it's the latter: I have to run High Sierra for a course I'm teaching so I cannot ignore this problem and hope it gets fixed sometime after High Sierra is publicly released. Sure, there are workarounds, but I'd rather not spend class time on workarounds and would very much prefer it if `brew install mongodb` worked as it did before. That's why I reported this issue.

**Comment by MikeMcQuaid** [comment]
> When you say "not supported", are you referring to --force-bottle or High Sierra in general? If it's the former: the same issue occurs when building from source. If it's the latter: I have to run High Sierra for a course I'm teaching so I cannot ignore this problem and hope it gets fixed sometime after High Sierra is publicly released. Sure, there are workarounds, but I'd rather not spend class time on workarounds and would very much prefer it if brew install mongodb worked as it did before. That's why I reported this issue.

Currently: both. `brew doctor` (which the issue template tells you to run) tells you that High Sierra is not supported, too.

**Comment by ilovezfs** [comment]
This sounds like it could be a general issue with `brew services` on High Sierra. @svanimpe maybe you could try out some other formulae with `brew services` and see if any are similarly afflicted?

**Comment by svanimpe** [comment]
@ilovezfs I only use Homebrew for mongodb and pandoc, so mongod is the only service I'm using.

@MikeMcQuaid I understand that you don't want to support unreleased OS'es, but High Sierra is pretty much GM, so I'm hoping this issue is worth investigating.

**Comment by ilovezfs** [comment]
@svanimpe if it is a more general issue, we will find out in due time. Thanks for reporting it.

**Comment by svanimpe** [comment]
@ilovezfs This issue still exists with the High Sierra bottle for MongoDB.

I would like to point out that MongoDB [recommends](https://docs.mongodb.com/master/tutorial/install-mongodb-on-os-x/?_ga=2.183374115.425473997.1506420319-983500535.1505483546) Homebrew as a way of installing MongoDB on macOS. At the moment, even the following basic scenario is broken:

1. `brew install mongodb` -> works fine, installs a bottle for High Sierra
2. `brew services start mongodb` -> appears to work fine (`brew services list` says it is running)
3. Run `mongo` -> does not work (connection refused).

**Comment by ilovezfs** [comment]
@svanimpe pull requests welcome!

**Comment by MikeMcQuaid** [comment]
@svanimple I cannot reproduce your problem on my High Sierra machine. You may need to `brew reinstall mongodb`. Regardless: this is an issue specific to your machine.

> Confirmed this is a problem with brew installing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run brew? If it's a general brew problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a brew cask problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

Just FYI this is a formula specific problem so should be filed into Homebrew/homebrew-core (or the relevant tap) in future.

**Comment by hvalcourtSerdy** [comment]
I had the same problem,

I did this :

```
mongod
exception in initAndListen: 29 Data directory /data/db not found., terminating
```

Fix this with :
```
sudo mkdir -p /data/db
sudo chmod 777 /data/db
```
