### ISSUE TITLE
ruby 2.4.2 gem update

### ISSUE THREAD

**Issue by yeukfei02** [Homebrew/brew#3161]
After ``brew update`` to ruby 2.4.2

 ``gem update``
Permission denied

``rm -rf /usr/local/lib/ruby/gems/2.4.0/doc/rake-12.1.0``
solve problem

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by monouser7dig** [comment]
Same happened on my side.

I guess this is a known issue as I found the solution in another long old locked thread.
