### ISSUE TITLE
Quick question: run `brew info` without searching deleted formula?

### ISSUE THREAD

**Issue by nrser** [Homebrew/brew#3166]
Is there a way to to tell `brew info <name>` not to search for deleted formula, or a fast alternative method of finding out if a package is currently available? 

`brew info <name>` takes a *long* time on my machine if `name` doesn't exist:

```
$ time brew info yarn@8.8.8
Error: No available formula with the name "yarn@8.8.8"
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.

real	0m28.795s
user	0m26.850s
sys	0m0.857s
```

It almost immediately gets to `Error: No available formula with the name "yarn@8.8.8"`, and it seems to be the search that takes up the time.

This is a problem for me because I have Ansible playbooks that create formulas for versions of packages using a template if it doesn't find the versioned formula, and Ansible's [homebrew][1] module uses `brew info` under the hood.

[1]: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/homebrew.py#L430

I poked around the `brew info` docs and the source a bit but I didn't see anything.

Is there any way to tell `brew` that I don't want it to dig through everything? Is there an approach I (and Ansible) should be using to figure out if a package is currently available?

Thanks, Neil.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by nrser** [comment]
Gee wiz guys it's a user interface question... is there somewhere else those should go?

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.3.2-73-gdbc4a38
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: dbc4a385b9d421b1738c86b4d0ca7cc1b49b3782
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 33d08243ea4dd69f1969deb0234781373fcac1c3
Core tap last commit: 52 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/nrser/.rbenv/shims/ruby => /Users/nrser/.rbenv/versions/2.3.3/bin/ruby
Java: 1.8.0_102, 1.8.0_66
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/docker-credential-osxkeychain
  /usr/local/lib/node_modules/nrser
  /usr/local/lib/node_modules/nrser-dropbox
  /usr/local/share/doc/ghc

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install llvm@4 openssl@1.1

Run `brew missing` for more details.

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  readline
```

**Comment by MikeMcQuaid** [comment]
> Gee wiz guys it's a user interface question... is there somewhere else those should go?

I don't think it's too much to ask for you to provide us with the information we actually ask for when you're asking volunteers for help at the weekend.

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:Homebrew joe$ time brew formula yarn@8.8.8
Error: No available formula with the name "yarn@8.8.8" 

real	0m0.501s
user	0m0.349s
sys	0m0.146s
```

**Comment by nrser** [comment]
@ilovezfs any idea why your version didn't do the

```
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
```

'cause that's the part that seem to take 30s. The portion of work your version seems to have done is fast on my box too.

**Comment by nrser** [comment]
That's what I was wondering about, if it's possible to get it to skip that.

**Comment by ilovezfs** [comment]
@nrser I used the `brew formula` command instead of the `brew info` command as a workaround.

**Comment by nrser** [comment]
Oh, sweet, missed that.

**Comment by nrser** [comment]
@ilovezfs is that command internal/private? I don't see it in `man brew`'s commands section. Use case is automation so API stability is kinda a thing.

**Comment by ilovezfs** [comment]
It's in there
```
       formula formula
              Display the path where formula is located.
```

**Comment by nrser** [comment]
Ah there's separate "Developer commands" down there under everything else. Cool, thanks. 

Assuming that's the preferred way to test for formula availability, or at least there's not problem with stuff depending on it? If the Ansible peeps are down with the change it will possibly result in some larger amount of people relying on it then at the moment.

And sorry I deleted the check list in the OP, I'll make sure to hit that stuff in the future.
