### ISSUE TITLE
could not symlink bin/gfortran

### ISSUE THREAD

**Issue by geoqueen** [Homebrew/brew#3168]
First of all, thank you to whoever will have the patience of an angel to help me.  I am quite new to shell scripting, currently using Mac OS Sierra, running in the tcsh shell.

I recently installed Homebrew to further install things needed for a climate model (called CESM).  I ran: 

brew doctor

and got a bunch of warnings, however this stuck at me the most:

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gcc
  gmp
  libmpc
  mpfr

I processed to do:
brew link gcc

I got this message:
Linking /usr/local/Cellar/gcc/7.2.0... 
Error: Could not symlink bin/gfortran
Target /usr/local/bin/gfortran
already exists. You may want to remove it:
  rm '/usr/local/bin/gfortran'

To force the link and overwrite all conflicting files:
  brew link --overwrite gcc

To list all files that would be deleted:
  brew link --overwrite --dry-run gcc

I installed FORTRAN weeks ago, using this website as guidance, just FYI, and codes run just fine:
https://wiki.helsinki.fi/display/HUGG/GNU+compiler+install+on+Mac+OS+X

What should I do about this? should I force the link? I am lost.  Thank you all!

**Comment by MikeMcQuaid** [comment]
> should I force the link?

Yes, this is probably your best bet. Good luck!
