### ISSUE TITLE
Progress info sent to stdout instead of stderr

### ISSUE THREAD

**Issue by jeroen** [Homebrew/brew#3169]
As of recently one of my scripts has stopped working, which I suspect is a bug:

Some progress info like __*==> Tapping homebrew/core...*__ is now being sent to stdout, messing up the actual output. Here is an example script to illustrate:

```sh
PKG_BREW_NAME="curl"
BREWDIR="/tmp/build-$PKG_BREW_NAME"
BREW="$BREWDIR/bin/brew"
mkdir -p $BREWDIR
curl -fsSL https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C $BREWDIR
BREW_DEPS=$($BREW deps --include-build -n $PKG_BREW_NAME)
echo "BREW_DEPS: $BREW_DEPS"
```

So the problem is that the `BREW_DEPS` variable should only contain package names, but here it actually contains the following:

```
BREW_DEPS: ==> Tapping homebrew/core
Tapped 4354 formulae (4,618 files, 11.5MB)
pkg-config
```

I don't think this is intended?

**Comment by scpeters** [comment]
The "Tapping" message is [printed with ohai](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/tap.rb#L236), which [uses puts](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils.rb#L26-L30), while other console helpers in that function use `$stderr.puts` (like [opoo](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils.rb#L39-L42) and [onoe](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils.rb#L44-L46)).

You could try a pull request that changes that `ohai` to use `$stderr.puts`; I'm not sure if that would break anything.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by jeroen** [comment]
OK I don't think it's relevant (the problem was diagnosed by @scpeters above) but here you go:

- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

Output of `brew config` is here:
```
$BREW config
HOMEBREW_VERSION: >1.2.0 (no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 06f78018d3896bb6ad3444f938b481ad5eb353bb
Core tap last commit: 38 minutes ago
HOMEBREW_PREFIX: /private/tmp/build-curl
HOMEBREW_REPOSITORY: /private/tmp/build-curl
HOMEBREW_CELLAR: /private/tmp/build-curl/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /private/tmp/build-curl/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
> OK I don't think it's relevant

OK, I don't think I'm interested in helping or replying further to your issue, then. Our issue template says that every issue requires the template. If you're able to decide whether or not that information is relevant to the Homebrew maintainers then you should be able to figure out your own issues. Future issues filed without an issue template and you may be blocked from filing future issues (again, as the issue template tells you).

**Comment by jeroen** [comment]
OK just trying to be helpful and only include relevant details in the report. I'll stick with the literal template next time if you prefer this. No need to be mean.

**Comment by MikeMcQuaid** [comment]
> I'll stick with the literal template next time if you prefer this.

Yes, please.

> No need to be mean.

I feel similarly.
