### ISSUE TITLE
Stacktrace instead of error message when `MacOS::Xcode.version` is null

### ISSUE THREAD

**Issue by Blaisorblade** [Homebrew/brew#317]
### Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

After upgrading to OS X 10.11, a few actions trigger a stacktrace, which suggests that `MacOS::Xcode.version` is null. `brew doctor` suggests that developer tools weren't installed; arguably, it'd still a better user experience if `MacOS::Xcode.version` (or a variant for this scenarios) displayed a suitable error message.
However, this is an unsupported configuration (it's about quality of error messages) so I'd this issue is low-priority.

```
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:851:in `keg_only?'
/usr/local/Library/Homebrew/diagnostic.rb:837:in `block in check_for_linked_keg_only_brews'
/usr/local/Library/Homebrew/diagnostic.rb:836:in `select'
/usr/local/Library/Homebrew/diagnostic.rb:836:in `check_for_linked_keg_only_brews'
/usr/local/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Library/brew.rb:87:in `<main>'
```

**Comment by DomT4** [comment]
> After upgrading to OS X 10.11, a few actions trigger a stacktrace

Can you elaborate on this a bit, in terms of which commands cause the issue?

**Comment by Blaisorblade** [comment]
I got it both from `brew upgrade --cleanup`, after it completed `darcs` and at `gd`, and from `brew doctor`.

But the stack traces are slightly different for the two commands, I'm sorry; below there are more accurate ones (the one given was from `brew doctor`). Line numbers should be from commit d363ae53c08abd7e658a0124e7d3bb79d38a1f08.

Some formulas did upgrade successfully. It turns out that one needs to invoke `f.keg_only_reason.valid?` on a formula `f` that is marked as keg-only for reason `:provided_until_xcode43` or `:provided_until_xcode5`.

The upgrade command checks recursive dependencies of the formula to upgrade, to ensure they're either keg-only or linked. So for me this only happened when upgrading `gd`—that can trigger the above bug on any of `autoconf`, `automake`, `libtool` because they're all `:provided_until_xcode43`.

```
$ brew upgrade --cleanup
==> Upgrading 13 outdated packages, with result:
cabal-install 1.24.0.0_1, curl 7.49.1, darcs 2.12.0, gd 2.2.1_1, ghc 8.0.1, graphicsmagick 1.3.24, haskell-stack 1.1.2_3, imagemagick 6.9.4-7, homebrew/dupes/make 4.2, node 6.2.1, poppler 0.44.0, tmux 2.2, vim 7.4.1864_1
[... successful upgrades...]
==> Upgrading darcs
==> Downloading https://homebrew.bintray.com/bottles/darcs-2.12.0.el_capitan.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring darcs-2.12.0.el_capitan.bottle.1.tar.gz
🍺  /usr/local/Cellar/darcs/2.12.0: 7 files, 46.2M
Removing: /usr/local/Cellar/darcs/2.10.3... (7 files, 30.4M)
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:851:in `keg_only?'
/usr/local/Library/Homebrew/formula_installer.rb:148:in `block in check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:147:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:147:in `check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:124:in `prelude'
/usr/local/Library/Homebrew/cmd/upgrade.rb:78:in `upgrade_formula'
/usr/local/Library/Homebrew/cmd/upgrade.rb:56:in `block in upgrade'
/usr/local/Library/Homebrew/cmd/upgrade.rb:55:in `each'
/usr/local/Library/Homebrew/cmd/upgrade.rb:55:in `upgrade'
/usr/local/Library/brew.rb:87:in `<main>'
```

```
[...]
Warning: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install
[...]
Warning: Your Xcode is configured with an invalid path.
You should change it to the correct path:
  sudo xcode-select -switch /Developer
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:851:in `keg_only?'
/usr/local/Library/Homebrew/diagnostic.rb:837:in `block in check_for_linked_keg_only_brews'
/usr/local/Library/Homebrew/diagnostic.rb:836:in `select'
/usr/local/Library/Homebrew/diagnostic.rb:836:in `check_for_linked_keg_only_brews'
/usr/local/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Library/brew.rb:87:in `<main>'
```

```
$ brew irb
> 'gd'.f.recursive_dependencies.map(&:to_formula).select do |f| f.keg_only_reason != nil end.map do |f| [f.name, f.keg_only_reason] end
=> [["autoconf", #<KegOnlyReason:0x007fb2093b3bd0 @reason=:provided_until_xcode43, @explanation="">], ["automake", #<KegOnlyReason:0x007fb2093bb0d8 @reason=:provided_until_xcode43, @explanation="">], ["libtool", #<KegOnlyReason:0x007fb2093c8fa8 @reason=:provided_until_xcode43, @explanation="">], ["gettext", #<KegOnlyReason:0x007fb20889de30 @reason=:shadowed_by_osx, @explanation="OS X provides the BSD gettext library and some software gets confused if both are in the library path.">], ["libpng", #<KegOnlyReason:0x007fb2093b9878 @reason=:provided_pre_mountain_lion, @explanation="">], ["freetype", #<KegOnlyReason:0x007fb2093d03c0 @reason=:provided_pre_mountain_lion, @explanation="">], ["fontconfig", #<KegOnlyReason:0x007fb208837888 @reason=:provided_pre_mountain_lion, @explanation="">]]
```

**Comment by Blaisorblade** [comment]
BTW, since I was looking at this code — I noticed it seems to run afoul of the "deprecation" in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac/xcode.rb#L103-L107.
```
class KegOnlyReason
  # ...
  def valid?
    case @reason
    # ...
    when :provided_until_xcode43
      MacOS::Xcode.version < "4.3"
    when :provided_until_xcode5
      MacOS::Xcode.version < "5.0"
```

**Comment by UniqMartin** [comment]
@Blaisorblade Thanks for the report and for the detailed and spot-on analysis! Fixed this in 25baaa61acc8743e69032233823a5ac33858d49e, so it should no longer fail for you after a `brew update`.

**Comment by DomT4** [comment]
@UniqMartin You're on a roll of fixing things before I swing back online this week, thank you for picking this up ❤️.

**Comment by Blaisorblade** [comment]
Thanks, that's better! But in case others have opinions, I have a nitpick on the fix here... But this nitpick only applies to old configurations, so before you look at it I wonder: do you actually support OS X before Mavericks? You have code but no testbot for it and I couldn't find info in docs.

I ask because I do see a bug, but I'd rather delete the offending feature than spend your time explaining it.

https://github.com/Homebrew/brew/commit/25baaa61acc8743e69032233823a5ac33858d49e#commitcomment-17745007

**Comment by DomT4** [comment]
> do you actually support OS X before Mavericks?

We haven't barred people from running Homebrew on 10.8 or lower but we no longer _officially_ support doing so and people encountering issues are expected to help fix them, essentially. `brew` [issues a warning](https://github.com/Homebrew/brew/blob/9e7b8c61a99c4d4c69da36f95759e375b7a4e116/Library/Homebrew/extend/os/mac/diagnostic.rb#L4-L22) on <10.8 and below.

I don't think any maintainer is running less than 10.9 & as you've noted we've only the CI capacity to continuously test/support 3 OS X releases at a time, so our capacity for testing & fixing things for older OS X releases is fairly slim. CI is sadly very maintenance heavy even supporting "only" the three most recent releases.

**Comment by UniqMartin** [comment]
Additionally, it doesn't make much sense to fully support older OS X releases as they have been abandoned by Apple, too. (But we don't try to actively rip out code so that Homebrew only runs with the OS X releases we and Apple officially support either.)

>  ask because I do see a bug, but I'd rather delete the offending feature than <s>spend your time explaining it</s> EDIT have you spend time reading the issue.
>
> https://github.com/Homebrew/brew/commit/25baaa61acc8743e69032233823a5ac33858d49e#commitcomment-17745007

Thanks for taking the time to look into this more thoroughly! I think the remaining inaccuracy is negligible, as it really only affects legacy systems that don't have Xcode 4.3.x-4.6.x installed, but have the matching Command Line Tools on their systems. Furthermore, it only affects users that have the `cvs` formula installed and the only undesirable (?) effect would be that now our `cvs` is no longer keg-only and thus would take precedence over the one provided by the Command Line Tools. I think this is a sufficiently small attack surface that we should only act on this if prompted by a bug report where this actually creates an issue. Solving the original issue you reported here has a much greater impact and certainly for the good (since we no longer abort with a stack trace).
