### ISSUE TITLE
High Sierra sandbox logging throws compatibility messages

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#3175]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.3.2-80-g81d9f71
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 81d9f71edbd770b60a57f2c44709fca1e0066ca1
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 37110fa368fe4fecc59910ee8328927f418e61ab
Core tap last commit: 73 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.1 => /usr/local/opt/git/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.4.2/bin/ruby
Java: 1.8.0_141
macOS: 10.13-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: N/A

Your system is ready to brew.
```

Can't really explain it more than the title of this Issue. Presumably it's complaining that we use [syslog here](https://github.com/Homebrew/brew/blob/1be06bfd1457a7b5ca2a2db88f12ee2bed945ab6/Library/Homebrew/sandbox.rb#L104). It only happens when you pass `--verbose` FWIW, so most users shouldn't run into it too much.

As far as I remember `syslog` was already soft-deprecated in Sierra but apparently Apple has decided to push a little harder with High Sierra. Must be a recent decision because I can't remember it pre-GM candidate.

Example output:

```
Installed SCons scripts into /usr/local/Cellar/scons/3.0.0/bin
NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
==> Cleaning
==> Finishing up
ln -s ../Cellar/scons/3.0.0/bin/scons scons
ln -s ../Cellar/scons/3.0.0/bin/scons-configure-cache scons-configure-cache
ln -s ../Cellar/scons/3.0.0/bin/scons-time scons-time
ln -s ../Cellar/scons/3.0.0/bin/sconsign sconsign
ln -s ../../../Cellar/scons/3.0.0/share/man/man1/scons-time.1.gz scons-time.1.gz
ln -s ../../../Cellar/scons/3.0.0/share/man/man1/scons.1.gz scons.1.gz
ln -s ../../../Cellar/scons/3.0.0/share/man/man1/sconsign.1.gz sconsign.1.gz
/usr/bin/sandbox-exec -f /tmp/homebrew20170919-71677-20nps0.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/scons.rb -v
NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
==> Summary
🍺  /usr/local/Cellar/scons/3.0.0: 405 files, 3.7MB, built in 7 seconds
```

**Comment by ilovezfs** [comment]
@DomT4 is this still happening post https://github.com/Homebrew/brew/issues/3175?

**Comment by DomT4** [comment]
> post #3175?

Which issue are you trying to reference here?

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/pull/3173

**Comment by DomT4** [comment]
Ah, thanks. Did wonder if it was that one but didn't want to assume & look potentially silly 😸.

Yeah, that did the trick:
```
Installed SCons library modules into /usr/local/Cellar/scons/3.0.0/libexec/scons-local/
Installed SCons scripts into /usr/local/Cellar/scons/3.0.0/bin
==> Cleaning
==> Finishing up
ln -s ../Cellar/scons/3.0.0/bin/scons scons
ln -s ../Cellar/scons/3.0.0/bin/scons-configure-cache scons-configure-cache
ln -s ../Cellar/scons/3.0.0/bin/scons-time scons-time
ln -s ../Cellar/scons/3.0.0/bin/sconsign sconsign
ln -s ../../../Cellar/scons/3.0.0/share/man/man1/scons-time.1.gz scons-time.1.gz
ln -s ../../../Cellar/scons/3.0.0/share/man/man1/scons.1.gz scons.1.gz
ln -s ../../../Cellar/scons/3.0.0/share/man/man1/sconsign.1.gz sconsign.1.gz
/usr/bin/sandbox-exec -f /tmp/homebrew20170921-92329-ve03s4.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/scons.rb -s -v
==> Summary
🍺  /usr/local/Cellar/scons/3.0.0: 405 files, 3.7MB, built in 7 seconds
```

**Comment by ilovezfs** [comment]
Good. I'd be amazed if :apple: were sending that warning to stdout.

**Comment by DomT4** [comment]
Aye, especially since the manpage for `sandbox-exec` has for ages read `The sandbox-exec command is DEPRECATED.` without throwing any sort of user-visible runtime complaints.

**Comment by MikeMcQuaid** [comment]
I'm going to 🙈 on this after https://github.com/Homebrew/brew/pull/3173 until something user-visible breaks but thanks for the report @DomT4.

**Comment by DomT4** [comment]
No worries! Completely understandable.

I'm just hoping Apple doesn't eventually remove the `sandbox-exec` command or we are in for a world of pain trying to replace that 😅.

**Comment by ilovezfs** [comment]
>I'm just hoping Apple doesn't eventually remove the sandbox-exec command or we are in for a world of pain trying to replace that 

That would be a rather strange thing to do.

**Comment by DomT4** [comment]
The block-caps `DEPRECATED` scares me.

**Comment by ilovezfs** [comment]
hehe breathe.
