### ISSUE TITLE
brew is throwing a ruby error after a failed update

### ISSUE THREAD

**Issue by problemss** [Homebrew/brew#3197]
# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

I originally had an issue installing encfs, it kept failing when installing rlog. I came on to submit and ticket and saw the steps that were proposed. So I ran 'brew update' and after updating, it showed this message:

```
warning: unable to unlink .yardopts: Permission denied
warning: unable to unlink CONTRIBUTING.md: Permission denied
warning: unable to unlink SUPPORTERS.md: Permission denied
fatal: cannot create directory at '.github': Permission denied
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
```

Now every time I call brew ('brew update', 'brew doctor', etc..) I get the following message

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
```

**Comment by ilovezfs** [comment]
```
chown -R $(whoami) /usr/local/*
```
will probably fix it

**Comment by problemss** [comment]
operation is not permitted

**Comment by problemss** [comment]
I am using this in OSX

**Comment by problemss** [comment]
Figured it out. Thanks for getting me on the right path. For anyone else i had to do this.

I had to chown the /usr/local path as sudo. Not sure if you have to also do local/* because I did local after already doing *.

and then do this:

$ cd /usr/local/Library/Homebrew  
$ git reset --hard  
$ git clean -df
$ brew update
