### ISSUE TITLE
Feature request: install --upgrade

### ISSUE THREAD

**Issue by xoviat** [Homebrew/brew#3204]
The current behavior of homebrew allows installing or upgrading packages, but as far as I know (and I am not a hombrew expert), it is impossible to specify an environment. In other words, it is impossible to say that regardless of the current system state, I want to end with the following items installed to their newest versions. The proposed solution is simple:

```
brew install --upgrade gcc
```

This would specify that homebrew should install the latest version of gcc regardless of what version is currently installed, and if the latest version is already installed, then nothing should be done. This would simplify CI services and automation scripts.

**Comment by MikeMcQuaid** [comment]
Please fill out the feature request template when making a feature template.

You can use `brew outdated` and `brew list` to identify if things are installed or need to be upgraded in your scripts.

**Comment by xoviat** [comment]
> You can use brew outdated and brew list to identify if things are installed or need to be upgraded in your scripts.

It's always possible to use bash to fix the problem. But that is a less robust and more error-prone solution that takes time and maintenance to implement.

**Comment by MikeMcQuaid** [comment]
I don't agree that it's less robust or error-prone. We take our command-line API seriously specifically so we don't have to implement commands like you've proposed here.

**Comment by xoviat** [comment]
It's probably not worth filling out a feature request then as it's probably not going to be accepted.

**Comment by MikeMcQuaid** [comment]
@xoviat It's less likely to be accepted if you don't fill out the form, yes. In general the form explains why they will be rarely accepted too which is why it is worth reading in future.
