### ISSUE TITLE
[ Feature Request ]  Track package installs to make easy for homebrew users to discover great packages

### ISSUE THREAD

**Issue by esutton** [Homebrew/brew#3212]
# Features
- Track the number of installs for each package.
- Motivation:  Make it easy for homebrew users to discover great packages that other homebrew users are using.

## Examples Using NPM 
- https://www.npmjs.com/browse/depended
- https://gist.github.com/anvaka/8e8fa57c7ee1350e3491

Thank you for sharing your work and making macOS so much more useful!

**Comment by MikeMcQuaid** [comment]
We do this already. See: https://brew.sh/analytics/install-on-request/

**Comment by esutton** [comment]
@MikeMcQuaid Thank you!

I don't know how many times I had Googled for this over the past few years without finding it.

Maybe add this link to the start page on https://brew.sh/ ?

Thank you!  Now I can find out what I what packages I have been missing out on!

**Comment by MikeMcQuaid** [comment]
It is linked from there through one other link.

**Comment by esutton** [comment]
I see the Analytics link at the bottom now. I will be researching the top packages to see what I may be missing.  Please close.

I cannot imagine software development on macOS anymore without Homebrew. It just works!

( And in the rare case when it doesn't I see **helpful** error messages in the console. )

Thank you for your work.

**Comment by MikeMcQuaid** [comment]
Thanks for your kind words, they genuinely mean a lot ❤️
