### ISSUE TITLE
Bottle cache conflicts if same formula exists in multiple taps

### ISSUE THREAD

**Issue by externl** [Homebrew/brew#3213]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

---
```
❯ brew doctor
Your system is ready to brew.
```
```
❯ brew config
HOMEBREW_VERSION: 1.3.4-4-ga589303
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a5893036166b9708d705a5060aa85002d5a6be16
Last commit: 39 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: baf0ef1e36711761ed92cc13760b8115ddd6c6ec
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2/bin/ruby
Java: 9, 1.8.0_131, 1.8.0_121, 1.7.0_79
macOS: 10.13-x86_64
Xcode: 9.0
CLT: N/A
X11: N/A
```
---

Formulae which exist in two taps (in my test case `homebrew-core` and [`zeroc-ice/homebrew-tap`](https://github.com/zeroc-ice/homebrew-tap/) share the same bottle and file download cache.

This causes issues because the sha checksum will typically not match for bottles (building bottles is not really deterministic), or if one formula uses a different source archive but with the same file name.

```
❯ brew install ice
==> Downloading https://homebrew.bintray.com/bottles/ice-3.7.0.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring ice-3.7.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/ice/3.7.0: 1,344 files, 271.4MB

❯ brew uninstall ice
Uninstalling /usr/local/Cellar/ice/3.7.0... (1,344 files, 271.4MB)

❯ brew install zeroc-ice/tap/ice
==> Installing ice from zeroc-ice/tap
==> Downloading https://zeroc.com/download/homebrew/bottles/ice-3.7.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/ice-3.7.0.high_sierra.bottle.tar.gz
Error: SHA256 mismatch
Expected: 639b3164b90d95385e763c08d79c900748c7fc0f63ae8b7b466da01a648da836
Actual: d458dacba532a611e88672698d3839a6be2b6f9905e11f2506d08c7c620fbd2d
...

❯ rm /Users/joe/Library/Caches/Homebrew/ice-3.7.0.high_sierra.bottle.tar.gz

❯ brew install zeroc-ice/tap/ice
==> Installing ice from zeroc-ice/tap
==> Downloading https://zeroc.com/download/homebrew/bottles/ice-3.7.0.high_sierra.bottle.tar.gz
==> Downloading from https://download.zeroc.com/homebrew/bottles/ice-3.7.0.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring ice-3.7.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/ice/3.7.0: 1,346 files, 271.4MB
```

Maybe the cache should be per-tap?

**Comment by MikeMcQuaid** [comment]
Although this is a legitimate error it's something that would need to be part of a wider refactor like https://github.com/Homebrew/brew/issues/568. It's worth noting that the bottle cache is not the only place that will 💥 when using formulae of the same name so we always recommend that taps avoid duplicating the names used in Homebrew/homebrew-core.
