### ISSUE TITLE
problem with either portable ruby or perl? not sure which is the real culprit.

### ISSUE THREAD

**Issue by mlevin2** [Homebrew/brew#3216]
Hello,

I went to update my homebrew today and started getting error messages when running `brew doctor`, `brew config`, and `brew update`. I get an error from perl about a file not being found, then I get an error about the portable ruby checksum being wrong. I am including the output of the commands below. I did try removing the portable ruby bottle to allow it to download again, but that didn't help. If you have any suggestions, please let me know. Thanks!

`[mlevin:~] % brew doctor`
`==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`######################################################################## 100.0%`
`/usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: /Users/mlevin/perl5/bin/shasum: /usr/local/Cellar/perl518/5.18.0/bin/perl: bad interpreter: No such file or directory`
`Error: Checksum mismatch.`
`Expected: 34ce9e4c9c1be28db564d744165aa29291426f8a3d2ef806ba4f0b9175aedb2b`
`Actual:`
`Archive: /Users/mlevin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`To retry an incomplete download, remove the file above.`
`Error: Failed to install vendor Ruby.`

`[mlevin:~] % brew config`
`==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`Already downloaded: /Users/mlevin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`/usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: /Users/mlevin/perl5/bin/shasum: /usr/local/Cellar/perl518/5.18.0/bin/perl: bad interpreter: No such file or directory`
`Error: Checksum mismatch.`
`Expected: 34ce9e4c9c1be28db564d744165aa29291426f8a3d2ef806ba4f0b9175aedb2b`
`Actual:`
`Archive: /Users/mlevin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`To retry an incomplete download, remove the file above.`
`Error: Failed to install vendor Ruby.`

`[mlevin:~] % brew update`
`==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`Already downloaded: /Users/mlevin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`/usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: /Users/mlevin/perl5/bin/shasum: /usr/local/Cellar/perl518/5.18.0/bin/perl: bad interpreter: No such file or directory`
`Error: Checksum mismatch.`
`Expected: 34ce9e4c9c1be28db564d744165aa29291426f8a3d2ef806ba4f0b9175aedb2b`
`Actual:`
`Archive: /Users/mlevin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`To retry an incomplete download, remove the file above.`
`Error: Failed to install vendor Ruby.`

**Comment by ilovezfs** [comment]
rm /Users/mlevin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz

**Comment by mlevin2** [comment]
@ilovezfs thanks, I tried that but I still get the same result. It just downloads the same thing.

`[mlevin:~] % rm /Users/mlevin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`[mlevin:~] % brew update`
`==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`######################################################################## 100.0%`
`/usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: /Users/mlevin/perl5/bin/shasum: /usr/local/Cellar/perl518/5.18.0/bin/perl: bad interpreter: No such file or directory`
`Error: Checksum mismatch.`
`Expected: 34ce9e4c9c1be28db564d744165aa29291426f8a3d2ef806ba4f0b9175aedb2b`
`Actual:`
`Archive: /Users/mlevin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz`
`To retry an incomplete download, remove the file above.`
`Error: Failed to install vendor Ruby.`

**Comment by ilovezfs** [comment]
try `HOMEBREW_ENV_FILTERING=1 brew update`

**Comment by mlevin2** [comment]
Bah! Somehow I had a bad `shasum` binary in `~/perl5/bin`. I deleted that and then it started using the one in `/usr/local/bin` and everything started working. Sorry!

**Comment by ilovezfs** [comment]
Yup, that's what `HOMEBREW_ENV_FILTERING=1` will work around :)
