### ISSUE TITLE
`brew update` does not respect `HOMEBREW_BUILD_FROM_SOURCE=1`

### ISSUE THREAD

**Issue by rw** [Homebrew/brew#3217]
I ran `brew update` yesterday and it installed `portable-ruby` from a bottle, not from sources. This seems like a bug. Personally, I vastly prefer to compile code instead of run binaries, even if they are signed.

I was able to install `portable-ruby` from source using the usual `brew install homebrew/portable/portable-ruby` installation process.

**Comment by MikeMcQuaid** [comment]
This is not a bug. You cannot build this from source as Homebrew now requires Ruby 2.3 which is not provided by macOS on versions before High Sierra.

Additionally, the issue template tells you to run `brew doctor` and `brew doctor` tells you to not report issues with `HOMEBREW_BUILD_FROM_SOURCE`. You will be blocked from submitting issues to Homebrew if you submit future issues without the template.
