### ISSUE TITLE
"started" should be "starting" if it's in yellow, and process hasn't full started

### ISSUE THREAD

**Issue by ORESoftware** [Homebrew/brew#3218]
See this Github issue:

https://stackoverflow.com/questions/46437670/brew-services-not-completely-started-mongodb/46437716#46437716

thanks

**Comment by JCount** [comment]
>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by ORESoftware** [comment]
shucks
