### ISSUE TITLE
audit doesn't detect problematic paths if they use "+"

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#322]
`(share+"nutcracker")` -> no audit error
`(share/"nutcracker")` -> `Use pkgshare instead of (share/"nutcracker")`

**Comment by maxim-belkin** [comment]
1. This part of audit code is under `--strict`.
2. Probable solution: change lines 922&mdash;924 of `Homebrew/cmd/audit.rb` to
```
      if line =~ %r{share(.+)#{Regexp.escape(formula.name)}[/'"]}
        problem "Use pkgshare instead of (share#{$1}#{formula.name}\")"
      end
```

**Comment by ilovezfs** [comment]
1. Right.
2. Feel free to open a PR.

**Comment by maxim-belkin** [comment]
can open a PR but I'm concerned that `(.+)` can match a lot of things...

**Comment by ilovezfs** [comment]
Then make it a more precise solution :)

**Comment by maxim-belkin** [comment]
I think using non-word character makes most sense:
```
 922       if line =~ %r{share(\W*)#{Regexp.escape(formula.name)}[/'"]}
 923         problem "Use pkgshare instead of (share#{$1}#{formula.name}\")"
 924       end
```

**Comment by UniqMartin** [comment]
> I think using non-word character makes most sense:

This seems too permissive and too restrictive at the same time. My proposed improvement is in #328.
