### ISSUE TITLE
The latest 10.13 system brew is not available

### ISSUE THREAD

**Issue by jijl2001** [Homebrew/brew#3224]
The latest version of the 10.13 official system was installed, and a brew was installed

brew install homebrew/nginx/openresty
Updating Homebrew...
==> Tapping homebrew/nginx
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-nginx'...
remote: Counting objects: 71, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 71 (delta 1), reused 44 (delta 0), pack-reused 0
Unpacking objects: 100% (71/71), done.
Tapped 61 formulae (160 files, 133.3KB)
Error: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.

But the brew cask usage is normal and the other command Line Tools must be up to date
Xcode9.0 is normally used

**Comment by scpeters** [comment]
I recommend that you fill out the issue template that shows when you create a new issue as it said the following:

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
