### ISSUE TITLE
Package `fop` semms broken on High Sierra

### ISSUE THREAD

**Issue by kpy3** [Homebrew/brew#3226]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

Here is command output:

```
brew install fop
==> Downloading https://www.apache.org/dyn/closer.cgi?path=/xmlgraphics/fop/binaries/fop-2.2-bin.tar.gz
==> Best Mirror http://mirror.linux-ia64.org/apache/xmlgraphics/fop/binaries/fop-2.2-bin.tar.gz
######################################################################## 100.0%
==> Downloading https://downloads.sourceforge.net/project/offo/offo-hyphenation-utf8/0.1/offo-hyphenation-fop-stable-utf
Already downloaded: /Users/yes/Library/Caches/Homebrew/fop--hyph-8.zip
Error: SHA256 mismatch
Expected: 0b4e074635605b47a7b82892d68e90b6ba90fd2af83142d05878d75762510128
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/yes/Library/Caches/Homebrew/fop--hyph-8.zip
To retry an incomplete download, remove the file above.
```

Here is diagnostic

```
yes@arben:~% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/9.6/bin/gdal-config
```

```
yes@arben:~% brew config
HOMEBREW_VERSION: 1.3.4-18-gcb139ca
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: cb139ca381cb7f00a4dfdc21482515f103aed417
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 05ca93f5fa435695ab65e9f8f3cec7fd3e4b4b25
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_112, 1.8.0_60
macOS: 10.13-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: 2.7.9 => /opt/X11
```

**Comment by ilovezfs** [comment]
You probably hit a bad mirror.

```
brew fetch -fs fop
```

**Comment by kpy3** [comment]
Hmmm.... Seems work now, thank you a lot!

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by MikeMcQuaid** [comment]
> Confirmed this is a problem with running a brew command and not brew installing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new

For future reference: this was related to `brew install`ing a single package so should have been filed to Homebrew/homebrew-core. Please read the issue template in full. Thanks!
