### ISSUE TITLE
The word "started" should be "starting", if it's in yellow, and process hasn't full started 

### ISSUE THREAD

**Issue by ORESoftware** [Homebrew/brew#3227]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:

See this StackOverflow issue:

https://stackoverflow.com/questions/46437670/brew-services-not-completely-started-mongodb/46437716#46437716

thanks

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
Can you please update the issue with the details of what you actually want (following the template) rather than just linking us to an StackOverflwo, thanks?

**Comment by ORESoftware** [comment]
sure, regarding this image:

![screenshot 2017-09-26 17 24 42](https://user-images.githubusercontent.com/11139560/31031816-a594641a-a50e-11e7-88cf-79ad1a322999.png)

"started" in yellow should say "starting" instead. It makes more sense. Because if the process crashed, then it's not started.

**Comment by MikeMcQuaid** [comment]
That's because it's not starting or crashed: we don't have the status on whether it is running or not. In future: please provide significant more details in your issues.

**Comment by ORESoftware** [comment]
mmm, @MikeMcQuaid  let me help you more.

so in this case it was a mongo process, and it definitely crashed..it tried to start and failed. the started in yellow was there for more than 20 minutes, etc. So brew should know that the process did not start successfully.

**Comment by ORESoftware** [comment]
I mean, wouldn't you say that Brew was lying to me when it said "started" in yellow, when the process crashed? that's the point.

**Comment by MikeMcQuaid** [comment]
> So brew should know that the process did not start successfully.

Sorry, we don't as this is a thin wrapper around `launchctl` which doesn't provide this information. Also, please file future issues to the `Homebrew/homebrew-services` repository and provide significantly more information.

> it was neither started

It was started and then it crashed.
