### ISSUE TITLE
Home-brew Scala Older Version Required

### ISSUE THREAD

**Issue by vipulbbd2012** [Homebrew/brew#3231]
Hi,

I am trying to install an older version of Scala on my Mac machine terminal. Currently I have Scala 2.12 installed and I need to install Scala 2.11 version.
I have tried all the options to switch to an older version but it is not working.
I do not have any older version of it previously installed so that I can switch to it.
Tried the "brew search Scala" , here it showing version scala@2.11 but not working.
![screen shot 2017-09-29 at 10 26 00 am](https://user-images.githubusercontent.com/32381407/31001354-b62fe0fa-a500-11e7-9c3c-5a897c75458d.png)

Kindly let me know how can I install the older version of Scala.

Thanks in Advance.
Vipul

**Comment by scpeters** [comment]
Have you tried:

~~~
brew install scala@2.11
~~~

Also, please don't ignore the issue template:

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by vipulbbd2012** [comment]
Hi,

Yeah tried this as well. It is showing as already installed, but when I looked under Cellar.. it is not there.

![screen shot 2017-09-29 at 10 41 23 am](https://user-images.githubusercontent.com/32381407/31001631-f7d18034-a502-11e7-8bc1-803acc0c8649.png)


And where is the issue template, I can't see it here. Please guide me with this :)

Thanks,
Vipul

**Comment by scpeters** [comment]
When you create a new issue, it has a bunch of text in the box that you can edit. That's the issue template.

I believe the installation would be in `/usr/local/Cellar/scala@2.11/`

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ brew install scala@2.11
==> Downloading https://downloads.lightbend.com/scala/2.11.11/scala-2.11.11.tgz
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/scala/scala-tool-support/0a217bc/bash-completion/sr
######################################################################## 100.0%
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/scala@2.11/bin:$PATH"' >> ~/.bash_profile


Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/scala@2.11/2.11.11: 52 files, 31.3MB, built in 6 seconds
```
So as it says
```
If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/scala@2.11/bin:$PATH"' >> ~/.bash_profile
```

or just invoke it as `usr/local/opt/scala@2.11/bin/scala`, etc.

**Comment by vipulbbd2012** [comment]
Hi,

Thanks for this info. But how can I know that when I run some code from clips, then in my terminal scala@2.11 is getting pointed to.??

![screen shot 2017-09-29 at 10 55 35 am](https://user-images.githubusercontent.com/32381407/31001915-cc77cc98-a504-11e7-8ed7-2d93f35f8fe1.png)


Thanks,
Vipul

**Comment by ilovezfs** [comment]
You'd need to point Eclipse at /usr/local/opt/scala@2.11/bin.

**Comment by vipulbbd2012** [comment]
No my question is, how do I know which version of Scala is being used now?

Because when I do brew info Scala.. it is showing only 2.12 version only.

**Comment by ilovezfs** [comment]
`scala` is the main scala formula.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/scala.rb

`scala@2.11` is a totally separate formula.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/scala@2.11.rb

So you want `brew info scala@2.11`.

**Comment by vipulbbd2012** [comment]
Got it. Thank You

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**
