### ISSUE TITLE
Site is offline

### ISSUE THREAD

**Issue by dosjos** [Homebrew/brew#3232]
Hi

Your site is unreachable. and I need my brews.
Hopefulle this is an error with your webhost, and not that you suddenly have taken your service offline

**Comment by ilovezfs** [comment]
It's not offline.

**Comment by dosjos** [comment]
Ok, but why is it not loading? The site is down according to http://isitdownforjustme.appspot.com aswell.
But does it load for you?

![image](https://user-images.githubusercontent.com/609086/31006897-f5016012-a4fe-11e7-9458-333370b0dbce.png)

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**
