### ISSUE TITLE
Installing Kafka 0.10 on Home-brew

### ISSUE THREAD

**Issue by vipulbbd2012** [Homebrew/brew#3233]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ Yes] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [Yes ] Ran `brew update` and retried your prior step?
- [ Yes] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ Yes] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) -  Trying to install Kafka 0.10
- What happened (include command output) - Not getting the formula in brew
- What you expected to happen - Need to install Kafka 0.10
- Step-by-step reproduction instructions (by running `brew` commands)

I ran brew install Kafka command on home-brew and it has installed Kafka 0.11.
But I need to install Kafka 0.10, for this I tried brew search Kafka , but it is not showing any other formula for 0.10 version.
![screen shot 2017-09-29 at 10 55 35 am](https://user-images.githubusercontent.com/32381407/31008776-e9dfd974-a522-11e7-812e-94e4373f31cf.png)

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by vipulbbd2012** [comment]
![screen shot 2017-09-29 at 2 37 49 pm](https://user-images.githubusercontent.com/32381407/31009086-e43338b2-a523-11e7-96de-6aa97f9dc38b.png)

**Comment by MikeMcQuaid** [comment]
> I ran brew install Kafka command on home-brew and it has installed Kafka 0.11.
> But I need to install Kafka 0.10, for this I tried brew search Kafka , but it is not showing any other formula for 0.10 version.

We don't provide Kafka 0.10.
