### ISSUE TITLE
macOS High Sierra - Error: Your Command Line Tools are too outdated.

### ISSUE THREAD

**Issue by uber1geek** [Homebrew/brew#3235]
Error: Your Command Line Tools are too outdated. Update them from Software Update in the App Store.

I have Xcode and the latest Command Line Tools installed.

This is a fresh installation of MacOS High Sierra.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by forwardadvance** [comment]
I'm having the same issue

**Comment by MikeMcQuaid** [comment]
@forwardadvance Then you should upgrade your Command Line Tools.
