### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by davidlapham** [Homebrew/brew#3239]
To help us debug your issue please explain:

- What you were trying to do (and why)
I was running brew doctor

- What happened (include command output)

> Error: 784: unexpected token at '{
>   "httpd24": "homebrew/core",
> }
> '
> /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
> /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
> /usr/local/Homebrew/Library/Homebrew/tap.rb:475:in `tap_migrations'
> /usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `formula_name_path'
> /usr/local/Homebrew/Library/Homebrew/formulary.rb:180:in `initialize'
> /usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `new'
> /usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `loader_for'
> /usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `factory'
> /usr/local/Homebrew/Library/Homebrew/formulary.rb:302:in `from_keg'
> /usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `from_rack'
> /usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
> /usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `map'
> /usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
> /usr/local/Homebrew/Library/Homebrew/diagnostic.rb:855:in `check_missing_deps'
> /usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
> /usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
> /usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
> /usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

- What you expected to happen
It would successfully run doctor

- Step-by-step reproduction instructions (by running `brew` commands)
brew doctor

**Comment by MikeMcQuaid** [comment]
This was fixed. Run `brew update`.

**Comment by ncuesta** [comment]
Can confirm, it works now. Thanks @MikeMcQuaid!

**Comment by vcgnetwork** [comment]
Thank you guys for the quick response. That seemed to work.

**Comment by vcgnetwork** [comment]
Spoke too soon now I am getting the error below. Can you help or should I open a different ticket. 

"Warning: Use httpd instead of deprecated homebrew/apache/httpd24"

**Comment by vcgnetwork** [comment]
here is my output: ```
BillsMacbookPro:~ wacurtis$ brew doctor
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install php70

Run `brew missing` for more details.
BillsMacbookPro:~ wacurtis$ brew services list
Name  Status  User     Plist
httpd started wacurtis /Users/wacurtis/Library/LaunchAgents/homebrew.mxcl.httpd.plist
mysql started wacurtis /Users/wacurtis/Library/LaunchAgents/homebrew.mxcl.mysql.plist
php71 started wacurtis /Users/wacurtis/Library/LaunchAgents/homebrew.mxcl.php71.plist
BillsMacbookPro:~ wacurtis$
```

**Comment by vcgnetwork** [comment]
Im not using php70

**Comment by MikeMcQuaid** [comment]
@vcgnetwork That's not an error, it's a warning and it's telling you what to do: use the `httpd` formula rather than `homebrew/apache/httpd24`.

**Comment by vcgnetwork** [comment]
Forgive me please, I don’t understand. What do I do to do that?

How do I use the httpd formula?  When I view the services thats what I am using

**Comment by vcgnetwork** [comment]
@MikeMcQuaid 

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install php70

Run `brew missing` for more details.
BillsMacbookPro:opt wacurtis$ brew install php70
Error: /usr/local/opt/php70 is not a valid keg

**Comment by vcgnetwork** [comment]
What do I do to fix this?

**Comment by MikeMcQuaid** [comment]
@vcgnetwork Run `brew upgrade`, ignore `brew doctor` and file any Homebrew/homebrew-php issues to that tap.
