### ISSUE TITLE
Brew Doctor not right after ticket#3239

### ISSUE THREAD

**Issue by vcgnetwork** [Homebrew/brew#3242]
To help us debug your issue please explain:
- What you were trying to do (and why)
ran "brew doctor" after a solution to ticket# 3239

- What happened (include command output)
BillsMacbookPro:~ wacurtis$ brew doctor
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some installed formula are missing dependencies.
You should brew install the missing dependencies:
brew install php70

Run brew missing for more details.
BillsMacbookPro:~ wacurtis$ brew services list
Name Status User Plist
httpd started wacurtis /Users/wacurtis/Library/LaunchAgents/homebrew.mxcl.httpd.plist
mysql started wacurtis /Users/wacurtis/Library/LaunchAgents/homebrew.mxcl.mysql.plist
php71 started wacurtis /Users/wacurtis/Library/LaunchAgents/homebrew.mxcl.php71.plist
BillsMacbookPro:~ wacurtis$

- What you expected to happen
for it to run with no errors, I dont use php70, I am using php71.

- Step-by-step reproduction instructions (by running `brew` commands)
brew doctor

**Comment by MikeMcQuaid** [comment]
> Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
