### ISSUE TITLE
[macOS 10.13]Homebrew ignoring --HEAD option when install vim

### ISSUE THREAD

**Issue by KiYugadgeter** [Homebrew/brew#3245]
hombrew is ignoring --HEAD option when install vim despite I have pass --HEAD option.

```
brew reinstall vim --with-luajit --with-python3 --with-override-system-vi --HEAD
```
I have run above command but homebrew executed install without --HEAD option like following gist.
https://gist.github.com/anonymous/ce3f3ce15a4d9378ba90da4372dad68c

**Comment by MikeMcQuaid** [comment]
Does `brew uninstall --force vim; brew install vim --HEAD` or `brew upgrade vim --HEAD` build HEAD?

In future: please file formula-specific issues to the Homebrew/homebrew-core issue (as the issue template told you to).

**Comment by KiYugadgeter** [comment]
Thanks for reply.

This problem has fixed with commands that you told.😃

2017-09-30 17:06 GMT+09:00 Mike McQuaid <notifications@github.com>:
