### ISSUE TITLE
package-request: python-rgain

### ISSUE THREAD

**Issue by timkofu** [Homebrew/brew#325]
I have used both mp3gain and aacgain; rgain (replaygain) actually works better (sound wise, and no freezing), and is actively maintained. Would it be possible to add it?

**Comment by MikeMcQuaid** [comment]
We don't really do package requests. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by timkofu** [comment]
Alright. Starting to make a formula for it.
