### ISSUE TITLE
brew upgrade failing silently and brew cask outdated not returning all outdated packages

### ISSUE THREAD

**Issue by fmechant** [Homebrew/brew#3253]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
[Link to gist ](https://gist.github.com/fmechant/386d313ca4212364ef382c0294aa3c90) containing output of brew config, brew doctor, brew upgrade, brew cask outdated, and example of outdated package that is not mentioned in outdated

To help us debug your issue please explain:
- What you were trying to do (and why)
upgrade all my packages, including my casks (to remain up-to-date)
- What happened (include command output)
brew upgrade: returns without any output, but does not upgrade anything
brew cask outdated: shows some outdated packages, but not all
[Link to gist ](https://gist.github.com/fmechant/386d313ca4212364ef382c0294aa3c90)
- What you expected to happen
brew upgrade: upgrades all my packages
brew cask outdated: shows all outdated packages
- Step-by-step reproduction instructions (by running `brew` commands)
[Link to gist ](https://gist.github.com/fmechant/386d313ca4212364ef382c0294aa3c90) is output of commands run. It shows that:
  - as an example gpgtools should be upgraded to 2017.1, but is at 2016.10_v2 and not upgraded
  - brew upgrade gives no message at all

**Comment by ilovezfs** [comment]
`brew upgrade` does not handle casks, and `brew cask upgrade` isn't a thing yet. See https://github.com/caskroom/homebrew-cask/issues/29301.
