### ISSUE TITLE
[Features?] Parallel installation of multiple packages from source

### ISSUE THREAD

**Issue by ralic** [Homebrew/brew#3261]
# Please always follow these steps:
- [ x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

brew install or brew upgrade different packages in different bash session.
running multiple brew installation at the same time.

- What happened (include command output)

a. xz is locked or used by another process
b. pkg-config is locked  or used by another process
c. Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.

- What you expected to happen

Adding new feature for "--ignore-locks" , and "--skip-updates", which means, the user knows the consequence and wants to run the brew upgrade parallel. 

- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature
**Adding new feature for "--ignore-locks" , and "--skip-updates", which means, the user knows the consequence and wants to run the brew upgrade in parallel.** 

- the motivation for the feature
**--ignore-locks : To speed up automation script to pull or install multiple bottles or initiate several builds for high speed networks/ high end servers.
**--skip-updates : Sometimes, the user may want to reduce the numbers of calls for updates when there is a need to build several packages at the same time.

- how the feature would be relevant to at least 90% of Homebrew users
**As we know, by using 'brew deps --tree ' feature,  experienced user may avoid conflicts in the parallel installation of packages. Once such feature is available, those users who handles stronger server may have chance to create multi-installation recipe, instead of sequential-installation, which may fruther reduce overall fresh installation runtime. 

- what alternatives to the feature you have considered

**Comment by MikeMcQuaid** [comment]
> To speed up automation script to pull or install multiple bottles

Do this with `brew fetch`.

> initiate several builds for high speed networks/ high end servers.

We already maximise the build process for the number of cores on your machine. Running multiple in parallel in this way, as a result, would be slower rather than faster.

Passing on this but thanks for the write-up.

**Comment by ralic** [comment]
Thanks, Mike for your feed back. I tested it out, fetch does help download multiple bottles at a time and help speed up installation. A better logic maybe applied for further need.  
```
brew fetch glassfish& brew fetch jenkins& brew fetch dex2jar& brew fetch tomee-plus
brew install glassfish jenkins dex2jar tomee-plus
```
