### ISSUE TITLE
Another stacktrace instead of error message when `MacOS.clang_version` is null (without CLT)

### ISSUE THREAD

**Issue by Blaisorblade** [Homebrew/brew#327]
## Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:
This is a followup to #317.

FYI, I just upgraded my other computer to El Capitan and got a different error (followed by a stacktrace) on `brew upgrade`. I think this issue is also minor, but since you cared about that I'm reporting this while I have the info.

Again, this stacktrace (like the earlier one) will likely disappear when CLT is installed. After a (bad) quickfix, I've found no other stacktrace on `brew upgrade` — only (bad) error messages.

This issue would disappear if `clang_version` would throw an exception instead of returning `nil`, but some other code would be impacted.

The offending line is in a formula in a tap and reads:
```
  if OS.mac? && MacOS.clang_version < "7.0"
```
I believe it fails because `MacOS.clang_version` is nil.

After replacing that line with:
```
  if OS.mac? && MacOS.clang_version != nil && MacOS.clang_version < "7.0"
```
(which I find a hack, I'm sure), `brew upgrade` completes "successfully" (exit code 0) despite the error:
```
$ brew upgrade
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
$ echo $?
0
```

I'm reporting this here (instead of the formula) because formulas shouldn't check basic build prerequisites, so I wouldn't like fixing this in a formula.

Below's the stacktrace.
```
$ brew upgrade
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:24:in `<class:Octave>'
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:175:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/formulary.rb:234:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1140:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1138:in `map'
/usr/local/Library/Homebrew/formula.rb:1138:in `installed'
/usr/local/Library/Homebrew/cmd/upgrade.rb:21:in `upgrade'
/usr/local/Library/brew.rb:87:in `<main>'
```

## Brew doctor output
`brew doctor` output has no stacktrace, though it is not perfect. It gives:
```
$ brew doctor
Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool
```

**Comment by UniqMartin** [comment]
What is the output of `xcode-select --print-path` on the affected system?

**Comment by Blaisorblade** [comment]
Whoops. I already did `xcode-select --install` to workaround the problem, and now I get:

```
$ xcode-select --print-path
/Library/Developer/CommandLineTools
```

However, logs on the other computer where I had #317 (which was similarly setup — they were originally cloned from each other) show that I got this output also *before* installing the command-line tools.
Is there some code detecting whether CLT is installed that is getting fooled?

**Comment by UniqMartin** [comment]
My theory for your specific scenario is that prior to the update, you had the Command Line Tools installed and `xcode-select --print-path` pointed to them. During the upgrade to 10.11, the Command Line Tools were wiped from your installation (as they are specific to an OS X release), but the link managed by `xcode-select` would continue pointing at the old location. `xcode-select --print-path` then continues to return this path without an error, even though the directory doesn't exist. It's only `xcrun` and the various wrappers in `/usr/bin` (like `/usr/bin/git`) that notice that the link is broken and then complain in exactly the way you have observed …

I guess the morale of the story, though I haven't looked at the code yet, would be to inspect all our code that relies on `xcode-select` (either directly or indirectly) and to make sure `xcode-select` not only returns a path, but that the returned path actually exists (maybe even check for the presence of a tool like `otool` that is expected to always be there).

**Comment by MikeMcQuaid** [comment]
This has been improved as much as it will be for now. If this is still broken for you: we'll accept PRs for this but we're not actively working on it at this time.
