### ISSUE TITLE
Feature Request: An option to upgrade all formulae having a specific version increment

### ISSUE THREAD

**Issue by raphaelstolt** [Homebrew/brew#3275]
# Feature
An option (e.g. `--only=major|minor|patch`) to upgrade all formulae with a major, minor, or patch version increment.

```bash
brew upgrade --only=major
brew upgrade --only=minor
brew upgrade --only=patch
```
To combine the upgrade of two version increment types, it would also be thinkable to combine or group these with a `+` sign or something similar.

```bash
brew upgrade --only=minor+patch
```
## Description
Given there are formulae with a major, minor, or patch version increment after a `brew update`, then it would be useful to run a `brew upgrade --only=minor` which only upgrades formulae meeting this specific condition. Formulae not following [semver](http://semver.org/) have to be ignored, as it's impossible to determine their version increment. 

## Prerequisite
This feature is relevant to at least 90% of Homebrew users, which is something I can't identify, and formulae maintainers tag their formulae in a serious semver-ish way.

## Motivation
This is somehow based on my habit to upgrade the formulae of the packages I've installed, which is scanning through the output of `brew outdated`, picking the ones having a minor version increment, and providing these to `brew upgrade`. Having such an option would reduce this, possibly only to me, inconvenient way of upgrading only the preferred packages.

**Comment by scpeters** [comment]
This is a cool idea, though I don't know when I personally would ever want to upgrade major versions without minor and patch versions too. For myself, I would prefer a cumulative option:

~~~
brew upgrade --no-minor # patch
brew upgrade --no-major # patch+minor
brew upgrade            # patch+minor+major
~~~

**Comment by ilovezfs** [comment]
Formulae require current versions of their dependencies, so `brew upgrade --no-minor` and  `brew upgrade --no-major` would both upgrade things that fell outside the attempted scope.

**Comment by MikeMcQuaid** [comment]
For the reason @ilovezfs mentioned: passing on this, sorry.
