### ISSUE TITLE
CLT: (null) on v1.3.4 and macOS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by vsx-gh** [Homebrew/brew#3276]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

I was working with GPG and attempting to search/install pinentry-mac. I got an error that my CLT install is out of date.
```
$ brew install pinentry-mac  
Error: Your Command Line Tools are too outdated.  
Update them from Software Update in the App Store.
```

I tried to verify with `brew doctor` what was up with CLT:
```
$ brew doctor check_clt_up_to_date  
Your system is ready to brew.
```

I then checked on my config and found that the CLT field is (null). Please see gist output at [https://gist.github.com/vsx-gh/6157861ca262c0e4a36ef360d1978b0e](https://gist.github.com/vsx-gh/6157861ca262c0e4a36ef360d1978b0e) for full `brew config` output. The Gist also includes proof that I have CLT installed.

I have no updates available in the App Store, and I can see an item for when I installed it. I have also re-installed CLT with no luck. I suspect this comes down to shenanigans with new macOS releases, but I don't know where to go next. Thanks for any assistance.

**Comment by scpeters** [comment]
Can you confirm that you have `clang`?

~~~
which clang
ls -l /Library/Developer/CommandLineTools/usr/bin/clang
~~~

I think the xcode detector is [looking for that file specifically](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac/xcode.rb#L273).

**Comment by vsx-gh** [comment]
Here you go:

```
$ ls -l $(which clang)
-rwxr-xr-x  1 root  wheel  18288 Sep 21 00:35 /usr/bin/clang
$ ls -lh /Library/Developer/CommandLineTools/usr/bin/clang
-rwxr-xr-x  1 root  admin    65M Sep  2 11:37 /Library/Developer/CommandLineTools/usr/bin/clang
$ /Library/Developer/CommandLineTools/usr/bin/clang --version
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by scpeters** [comment]
I have a similar setup to you (10.13 with CLT only). The following is used by the xcode detector and gives some output for me:

~~~
$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 9.0.0.0.1.1504363082
volume: /
location: /
install-time: 1506443133
groups: com.apple.FindSystemFiles.pkg-group 
~~~

The [xcode detector](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac/xcode.rb#L188-L275) also runs these other commands, but they don't show anything for me:

~~~
$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLILeo
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLI
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Base
No receipt for 'com.apple.pkg.CLTools_Base' found at '/'.
~~~

**Comment by vsx-gh** [comment]
Ah, that's a bad sign: I have an install time, but no version or location. Looks like I have a more guided research direction, at least.

```
$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: (null)
volume: /
location: (null)
install-time: 1507251099
$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLILeo
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
$ usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLI
-bash: usr/sbin/pkgutil: No such file or directory
$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLI
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Base
No receipt for 'com.apple.pkg.CLTools_Base' found at '/'.
```

**Comment by vsx-gh** [comment]
I was not able to rectify this issue with a manual download/install of CLT for either 10.13 or 10.12. I would like to mention how difficult it is to find those downloads! Anyway, I wiped my disk and re-installed macOS, then re-installed brew with the Ruby one-liner. I let that handle the CLT install, and it's currently looking happy:

```
[Globenheimer: ~/Downloads] $ brew config
HOMEBREW_VERSION: 1.3.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ac8b58537fe3dd71098a43afcc6a1785dcde1d39
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 19b2c19562b6b0acf1cfea87aa59eb887018c233
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: N/A
CLT: 9.0.0.0.1.1504363082
X11: N/A
```
I also installed `tmux` with brew and that worked great.

Not sure what others' experience is, but I definitely do not suggest an in-place upgrade to macOS 10.13. Regardless, this issue was with the OS and not with Homebrew, which has always treated me well. Thanks for the assistance! This one's ready to close.

**Comment by ilovezfs** [comment]
Glad you got it sorted out!

**Comment by guido4000** [comment]
I do have the same problem on 10.13.2. Just didn't want to reinstall yet.
