### ISSUE TITLE
brew <whatever> hangs trying downloading portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz

### ISSUE THREAD

**Issue by ezorzin** [Homebrew/brew#3281]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

Hi,

when I issue any, e.g.:
brew
brew doctor
brew <whatever>

brew hangs in trying downloading "portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz".

Eriks-Air:Homebrew Erik$ brew
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
Already downloaded: /Users/Erik/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
/usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: /usr/local/bin/shasum: /usr/local/opt/perl/bin/perl: bad interpreter: No such file or directory
Error: Checksum mismatch.
Expected: 34ce9e4c9c1be28db564d744165aa29291426f8a3d2ef806ba4f0b9175aedb2b
Actual: 
Archive: /Users/Erik/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.

There is no way of getting out of this for me, I have tried checking out brew to a previous version, killing all ruby processes, deleting cache...brew is not responding to ANY command.
I don't understand what's going on, never had this behaviour.
I apparently did nothing but this morning brew behaves like this.
I am on a MacBook Air - Sierra 10.12.6.
Brew always worked wonderfully on my mac before this morning.

Is there a way to repair this? 

Thanks

**Comment by ilovezfs** [comment]
rm /usr/local/bin/shasum

**Comment by ezorzin** [comment]
...ugh! It worked! You killed me :)

May I ask you an explanation of what was the problem and how could this have solved it?

Thanks

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/blob/ac8b58537fe3dd71098a43afcc6a1785dcde1d39/Library/Homebrew/cmd/vendor-install.sh#L84 was using /usr/local/bin/shasum instead of /usr/bin/shasum and your /usr/local/bin/shasum wasn't working due to an issue finding /usr/local/opt/perl/bin/perl, which apparently doesn't exist on your machine right now.

**Comment by ezorzin** [comment]
Got it.
Thanks a lot!

Best regards

**Comment by chdiza** [comment]
@lovezfs I wonder if `vendor-install.sh` should  stop looking for `$(which shasum)` and just  look for whether `/usr/bin/shasum` is there.

**Comment by ilovezfs** [comment]
@chdiza the theory here is that if `which shasum` is broken you have bigger problems.

**Comment by chdiza** [comment]
> the theory here is that if which shasum is broken you have bigger problems.

Those bigger problems, however, probably would not have interfered with portable-ruby installation---and thus brought Homebrew to a screeching halt---if only `/usr/bin/shasum` were used.

**Comment by ilovezfs** [comment]
@chdiza yeah we'll probably make that change. The theory was just a theory.
