### ISSUE TITLE
Please add an option to disable git resource updating during `brew install`.

### ISSUE THREAD

**Issue by galaxy001** [Homebrew/brew#3297]
A feature needed to totally disable network requirement, including *git resource*s.

I am using Linuxbrew in an offline server, with `HOMEBREW_NO_AUTO_UPDATE=1`.

However, some formula like [go.rb](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/go.rb) will run *Updating ~/.cache/Homebrew/go--gotools--git* with `git fetch -q origin --unshallow` even after I manually clone the repo and upload to the server.

Thus I need a way to disable this updating.

**Comment by ilovezfs** [comment]
Sorry, we don't support fully offline installations.

**Comment by galaxy001** [comment]
Is this OK to add an option to disable unnecessary git update?
This will reduce disk activities for a longer SSD life.
