### ISSUE TITLE
 brew link python3 error on macOs High Sierra

### ISSUE THREAD

**Issue by liaodongxiaoxiao** [Homebrew/brew#3308]
When I was install python3 with Homebrew.
```java
$ brew install python3
Warning: python3 3.6.3 is already installed, it's just not linked.
You can use `brew link python3` to link this version._
```
then I execute `brew link python3`
```java
Linking /usr/local/Cellar/python3/3.6.3... Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks
```
> system: macOs High Sierra 10.13
>homebrew version:1.3.5

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by albinekb** [comment]
Hello @MikeMcQuaid! Closing the issue like that does not help me as a user that just got this exact problem. Why is there more info needed in this case? Is this a duplicate? thanks.

**Comment by albinekb** [comment]
For reference for the next one coming here having problems with python, here's the solution: https://github.com/Homebrew/homebrew-core/issues/20985

**Comment by MikeMcQuaid** [comment]
@albinekb We don't have enough information to work on that problem because they didn't fill out the issue template. There's more information required for every single issue which is why it was closed.
