### ISSUE TITLE
brew pull doesn't understand boneyarding

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#331]
```
Josephs-MacBook-Pro:homebrew-boneyard joe$ brew pull https://github.com/Homebrew/homebrew-boneyard/pull/125
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-boneyard/pull/125.patch
==> Applying patch
Applying: memo: boneyard
Warning: homebrew/boneyard/memo has a bottle: do you need to update it with --bottle?
==> Patch closes issue #125
Warning: Nonstandard bump subject: memo: boneyard
Warning: Subject should be: memo 1.6 (new formula)
==> Patch changed:
 memo.rb | 25 +++++++++++++++++++++++++
 1 file changed, 25 insertions(+)
Josephs-MacBook-Pro:homebrew-boneyard joe$
```

**Comment by UniqMartin** [comment]
It worked flawlessly for me when I pulled Homebrew/homebrew-boneyard#124. It didn't complain about bottles or non-standard commit subjects either.

All of this might be related to the issue that Homebrew/homebrew-boneyard#125 retained the `bottle do` block, something we normally drop when boneyarding (it wouldn't work after the move anyway). I guess that's something your `boneyard-formula-pr` doesn't do yet, though it should. :wink:

**Comment by ilovezfs** [comment]
Interesting. I'll see if that's the cause, and add it to the PR if it is.

**Comment by ilovezfs** [comment]
@UniqMartin Hmm still seems to do it even with bottle block dropped.
```
Josephs-MacBook-Pro:homebrew-boneyard joe$ brew pull https://github.com/Homebrew/homebrew-boneyard/pull/127
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-boneyard/pull/127.patch
==> Applying patch
Applying: visualnetkit: migrate from core
==> Patch closes issue #127
Warning: Nonstandard bump subject: visualnetkit: migrate from core
Warning: Subject should be: visualnetkit 1.4 (new formula)
==> Patch changed:
 visualnetkit.rb | 120 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 120 insertions(+)
Josephs-MacBook-Pro:homebrew-boneyard joe$ 

```

**Comment by ilovezfs** [comment]
Ah, the cause is the order. The message occurs if you do the brew pull + git push for the pr boneyarding it in core before doing the brew pull for the pr importing it into boneyard. It's tripping on `if old[:nonexistent]`.

**Comment by UniqMartin** [comment]
The order here is important. To be on the safe side, you always have to pull and push in the boneyard repository first, then pull and push in the originating repository. If you're doing it the other way round, you're opening up a (small) window where `tap_migrations.json` claims the formula has been migrated to the boneyard, but then `brew` taps the boneyard repository and the formula isn't actually there. Not a likely thing to happen, but not entirely impossible for a project of our size. It is also safer in the unlikely situation that you have a network outage between the pushes. (Actually, all of this applies to migrations in general.)

**Comment by ilovezfs** [comment]
That's all well and good but beside the point. The command is giving bogus output and this is a a bug.

**Comment by UniqMartin** [comment]
> That's all well and good but beside the point.

Nope. You mentioned that you're doing this the other way round, so I felt it important to explain this.

> The command is giving bogus output and this is a bug.

The command is giving bogus output, but this is just a minor inconvenience. Migrations are infrequent compared to all other `brew pull` action, `brew pull` is a developer-facing command, and most boneyard migrations are happening via the GitHub website nowadays (“squash merge” works just fine for cases with one formula per PR because there's no bottle involved).

I don't consider this a bug because it does what you ask it to do and just prints a warning that happens to not apply (because it doesn't have enough information to do better and is optimized for the common case). Just like with `brew doctor` warnings these can be safely ignored if everything is as expected.

**Comment by ilovezfs** [comment]
I think procedure is a poor excuse for a bug, and the order in which the ultimate `git push` commands should occur is a separate matter from what `brew pull` output is or is not correct.

**Comment by UniqMartin** [comment]
Does it produce an invalid result? No, hence it's not a bug. Does it print a warning that *could* mean something is wrong, but in fact isn't? Yes, and tons of tools do this (including your favorite C compiler).

**But let's make this more productive:** I don't think `brew pull` can learn just from the commit it is pulling that this must be a migration. What it could do is to silence the warning if one of two conditions apply:

- The commit subject exactly matches `<formula>: migrate from <repository>` and the commit adds a formula file.
- The commit subject exactly matches `<formula>: migrate to <repository>`, the commit removes a formula file, and the commit changes the contents of `tap_migrations.json` (or adds this file).

If desired, one could go one step further and add a `--migrate` option (similar to the `--bump` option) so the intention of a migration can be expressed very explicitly. This would then check that one of the two conditions from above is met, auto-correct the commit subject if necessary (just like `--bump`), and fail hard if the commit contents (added/modified/deleted files) don't match expectations.

I think that's the way forward if the current behavior bothers you sufficiently (I'm getting the impression). And it shouldn't be too difficult to implement with the existing infrastructure in place.

**Comment by ilovezfs** [comment]
Now we're on the same wavelength again.
