### ISSUE TITLE
Portable Ruby is broken

### ISSUE THREAD

**Issue by CamJN** [Homebrew/brew#3310]
https://github.com/Homebrew/homebrew-portable/blob/master/Formula/portable-ruby.rb#L124-L126

Don't do this, it makes rake refer to `/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/rake` which doesn't exist.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by CamJN** [comment]
# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
technically this happens while installing a formula but it's not an issue with the formula, so i'm reporting here
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
```
brew config && brew doctor
HOMEBREW_VERSION: 1.3.5-8-g30b84ac
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30b84ac6f39d2f0cd3e3993959a11888a047afd5
Last commit: 80 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5b77af770999f089a53b75cb776f82fd093fe6e3
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Volumes/Users/CamdenNarzt/.rbenv/shims/ruby => /Volumes/Users/CamdenNarzt/.rbenv/versions/2.3.3/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
locally brew install passenger (on sierra or earlier, built from source), to check if today's release works fine in homebrew on non-high-sierra macs.
- What happened (include command output)
the rake method in a formula uses the portable ruby that homebrew recently introduced, but it's broken because you deliberately delete rake.
This gets called: `/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/rake apache2` but that path doesn't exist.
- What you expected to happen
I should be able to use rake
- Step-by-step reproduction instructions (by running `brew` commands)
```
brew install passenger --build-from-source 
```

**Comment by CamJN** [comment]
@MikeMcQuaid here's your answers, I can't see how this is helpful though there's no more useful info.

**Comment by MikeMcQuaid** [comment]
> I can't see how this is helpful though

@CamJN Please let us decide that in future, thanks.
