### ISSUE TITLE
brew --prefix formula too slow

### ISSUE THREAD

**Issue by sobrinho** [Homebrew/brew#3327]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

Calling `brew --prefix formula` takes half second, example:

```
$ time brew --prefix
/usr/local

real    0m0.032s
user    0m0.011s
sys     0m0.014s

$ time brew --prefix readline
/usr/local/opt/readline

real    0m0.532s
user    0m0.329s
sys     0m0.136s
```

I'm trying to write automated scripts using the formulas on brew.

For now, I'm work-arounding the issue by using the result of that call in my machine but I can't rely on that for non-my-machine scripts.

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by sobrinho** [comment]
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ruby

$ brew config
HOMEBREW_VERSION: 1.3.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 91ab116ace7f4f97d3440190463c93be9ec6d675
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e9f6189c7393fc6d5d8179cc386bfa84fbbdb095
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/sobrinho/.rbenv/shims/ruby => /Users/sobrinho/.rbenv/versions/2.4.2/bin/ruby
Java: 1.8.0_102
macOS: 10.12.6-x86_64
Xcode: 9.0.1
CLT: 9.0.1.0.1.1506734476
X11: N/A
```

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/brew/issues/3097#issuecomment-325206329

**Comment by scpeters** [comment]
Also, as mentioned in https://github.com/Homebrew/brew/issues/3007#issue-248196472, you can try [brew prof --prefix](https://github.com/Homebrew/homebrew-dev-tools/blob/master/cmd/brew-prof.rb) to profile and get some insight into how to speed it up.

**Comment by ilovezfs** [comment]
Also, `dirname $(dirname $(which brew))` is approximately twice as fast.

**Comment by ilovezfs** [comment]
And `dirname $(dirname $(type -p brew))` is a bit faster than that.
