### ISSUE TITLE
Simple OS name

### ISSUE THREAD

**Issue by maxim-belkin** [Homebrew/brew#3328]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step? 
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? 
- [x] Ran `brew config` and ...
- [ ] ...     `brew doctor` and included their output with your issue?

---

## Features
In order to merge Linuxbrew/brew into Homebrew/brew, sometimes we have to do something like:

```
if OS.mac?
  require "os/mac/something/something"
elsif OS.linux?
  require "os/linux/something/something"
end
```
which, clearly, could be shrunk down to
```
require "os/#{VARIABLE}/something/something
```
if we had that magic `VARIABLE`.

_**This issue is a request to create such a variable.**_

What is currently available:
```
OS_VERSION  => "macOS 10.13"
ENV["HOMEBREW_OS_VERSION"] => "macOS 10.13"
ENV["HOMEBREW_SYSTEM"] =>"Macintosh"
```
Ideally, it should be as simple as `OS_VERSION` (which is defined in `os.rb`), e.g.: `::OS_SIMPLE_NAME` or `::OS_SYSTEM`

---
```
$ brew config
HOMEBREW_VERSION: 1.3.5-16-gb4e1e39
ORIGIN: https://github.com/Homebrew/brew
HEAD: b4e1e39d3b38b722fc554a3665d9b6dbf165d99a
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e9f6189c7393fc6d5d8179cc386bfa84fbbdb095
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/mbelkin/.pyenv/shims/python => /Users/mbelkin/.pyenv/versions/3.6.2/bin/python3.6
Ruby: /Users/mbelkin/.rbenv/shims/ruby => /Users/mbelkin/.rbenv/versions/2.5.0-dev/bin/ruby
Java: 1.8.0_112
macOS: 10.13-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: 2.7.8 => /opt/X11
```
---

**Comment by MikeMcQuaid** [comment]
> which, clearly, could be shrunk down to
> 
> require "os/#{VARIABLE}/something/something

Well, not really because if you run on a non-macOS and non-Linux OS that will fail with a file not found error rather than falling back to the existing, generic code. A helper function could be created instead of this constant to handle this, though:

```ruby
def require_os(path)
  if OS.mac?
    require "os/mac/#{path}"
  elsif OS.linux?
    require "os/linux/#{path}"
  end
end
```

Closing this out in favour of a PR for that.
