### ISSUE TITLE
Feature request: Warning about long-installing formulae

### ISSUE THREAD

**Issue by getaaron** [Homebrew/brew#3340]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

> Requested outputs are at the end of this issue.

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
## Detailed Description

Currently, installing some formulae take a long time (more than a few seconds). For example, installing `macports` took a few minutes:

```bash
$ brew cask install macports
==> Satisfying dependencies
==> Downloading https://github.com/macports/macports-base/releases/download/v2.4.2/MacPorts-2.4.2-10.13-HighSierra.pkg
######################################################################## 100.0%
==> Verifying checksum for Cask macports
==> Installing Cask macports
==> Running installer for macports; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:

==> installer: Package name is MacPorts
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  macports was successfully installed!
```

Homebrew should anonymously track average installation times. If the installation is over 5 seconds, we should inform the user after the password is entered, ideally with a friendly emoji e.g.:

```bash
==> Verifying checksum for Cask macports
==> Installing Cask macports
==> Running installer for macports; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> ⏱ This should take about 45 seconds to complete.
==> installer: Package name is MacPorts
==> installer: Installing at base path /
==> installer: The install was successful.
```

## Motivation

Currently there is no indication of progress and users can worry that installation has hung or failed in some way. This gives users a sense of how long they should wait before worrying.

## Assumptions

- At least 90% of Homebrew users install long-running formulae
- Most users get anxious about installation time when there is no printed information

## Alternatives considered

- An enabled-by-default `--verbose` feature. This seems too noisy but would address the issue.

# Requested `brew` outputs

```bash
$ brew update
Already up-to-date.
```

```bash
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports
```

```bash
$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d71f71ff6fb40e5744cb728678250d61490cebc9
Core tap last commit: 25 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2/bin/ruby
Java: N/A
macOS: 10.13.1-x86_64
Xcode: 9.0
CLT: N/A
X11: N/A
MacPorts/Fink: /opt/local/bin/port
```

**Comment by chdiza** [comment]
Just set `HOMEBREW_VERBOSE` in your profile.  You never have to touch it again.

**Comment by MikeMcQuaid** [comment]
> Homebrew should anonymously track average installation times. If the installation is over 5 seconds, we should inform the user after the password is entered, ideally with a friendly emoji e.g.

This varies far too much between systems to have any useful information on this. We print a progress bar when we can but in these cases we can't. Passing on this, sorry.
