### ISSUE TITLE
Suggested python path for upstream programs?

### ISSUE THREAD

**Issue by sitsofe** [Homebrew/brew#3342]
(This is not a bug but a request for more information)

With [Fedora banning the use of /usr/bin/python](https://pagure.io/packaging-committee/issue/698) and direct `python` (note now number) references what is the correct thing for upstream packages to do when trying to be multi-platform with the hashbang line? Will homebrew fix things up the same way as others (e.g. https://github.com/omniti-labs/omnios-build/blob/master/build/fio/patches/fio2gnuplot.patch )?

**Comment by MikeMcQuaid** [comment]
We do not have any written guidelines for this case at the moment. @ilovezfs may have more thoughts.

**Comment by ilovezfs** [comment]
>Will homebrew fix things up the same way as others

We tend to avoid downstream patching.

>what is the correct thing for upstream packages to do when trying to be multi-platform with the hashbang line

probably `#!/usr/bin/env python2.7`

**Comment by sitsofe** [comment]
@ilovezfs thanks for following up. I've had some additional thoughts:

python2.7 positives:
* It's been around for a while
* It is unlikely there will ever be an official python 2.8 at this point
* I'm not worried about python3
* macOS doesn't ship with python3 by default (obviously homebrew can add this but that's another topic).

python2.7 negative:
* Old (but supported) CentOS 6 doesn't ship with python2.7 (https://distrowatch.com/table.php?distribution=centos).

env negative:
* Using env is a no win situation from avoiding distro packaging patches perspective because the Debian guidelines say "use `/usr/bin/python` / `/usr/bin/python2.7` etc " (see the [Interpreter Location of the Debian Python Policy](https://www.debian.org/doc/packaging-manuals/python-policy/ch-python.html#s-interpreter_loc)). Fedora seem to be moving in that direction too: https://pagure.io/packaging-committee/issue/700 .

I notice pkgsrc takes the attitude of "we'll always patch (Python) hashbang lines (see https://www.netbsd.org/docs/pkgsrc/creating.html#creating.python-module and search for `REPLACE_PYTHON` or `REPLACE_` in general). I suspect there will be incentives for distro default packaging systems to gravitate towards that too.

I guess you can't win them all...

**Comment by ilovezfs** [comment]
`#!/usr/bin/env python` is probably the most straightforward thing to do and then let downstreams replace the shebang as desired. If only upstream Python had enforced strict backwards compatibility …
