### ISSUE TITLE
pain

### ISSUE THREAD

**Issue by DreamerKadars** [Homebrew/brew#3348]
#include<stdio.h>
int main()
{
    int array[]={12,335,4,6763,3,47,65};
    int temp;
    for (int i=0; i<6; i++) {
        for(int j=0;j<6-i;j++)
        {
            if(array[j]<array[j+1])
            {
                temp=array[j];
                array[j]=array[j+1];
                array[j+1]=temp;
            }
                }
    }
    for (int i=0; i<7; i++) {
        printf("%d\t",array[i]);
    }
}

**Comment by ilovezfs** [comment]
6763	335	65	47	12	4	3
