### ISSUE TITLE
Link error for Ruby 2.4.2_1 

### ISSUE THREAD

**Issue by romanlevin** [Homebrew/brew#3354]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

Got a linking error when installing Ruby:
```
$ brew install ruby
==> Downloading https://homebrew.bintray.com/bottles/ruby-2.4.2_1.high_sierra.bottle.tar.gz
Already downloaded: /Users/romanlevin/Library/Caches/Homebrew/ruby-2.4.2_1.high_sierra.bottle.tar.gz
==> Pouring ruby-2.4.2_1.high_sierra.bottle.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.4.0/doc/rubygems-2.6.14
Error: Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.4.0/doc/rubygems-2.6.14
```
```
$ brew link ruby
Linking /usr/local/Cellar/ruby/2.4.2_1... Error: Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.4.0/doc/rubygems-2.6.14
```
```
$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c2bdedc0fc1cac4cf7acd4859a7192cd0e0a29d3
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: 9
macOS: 10.13-x86_64
Xcode: 9.0.1
CLT: 9.0.1.0.1.1506734476
X11: N/A
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/romanlevin/.pyenv/shims/python2-config
  /Users/romanlevin/.pyenv/shims/python3.6m-config
  /Users/romanlevin/.pyenv/shims/python2.7-config
  /Users/romanlevin/.pyenv/shims/python-config
  /Users/romanlevin/.pyenv/shims/python3-config
  /Users/romanlevin/.pyenv/shims/python3.6-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ruby
```

**Comment by ilovezfs** [comment]
What's the output of
```
find /usr/local -not -uid $(id -u)
```

You probably need to
```
sudo chown -R $(whoami) /usr/local/*
```

**Comment by MikeMcQuaid** [comment]
> Confirmed this is a problem with running a brew command and not brew installing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new

This is not the case, FYI. Please read the issue template fully in future.

**Comment by romanlevin** [comment]
@ilovezfs Thanks, that solved the problem.

@MikeMcQuaid Sorry, I must have missed that!

Since this might still be a bug, (that is, haven't touched `/usr/local/*` until today, and no other formulae had this issue) should I leave this open, or should I open a formula specific ticket in homebrew-core?

**Comment by MikeMcQuaid** [comment]
@romanlevin Can leave this open for now. It's a bug specific to your system, though, FYI.

**Comment by ilovezfs** [comment]
@romanlevin did you manage to capture the output of `find /usr/local -not -uid $(id -u)` before running `sudo chown -R $(whoami) /usr/local/*`? If not, I'm not sure there's much more to be learned here since you've already reset the ownership back to "normal."

**Comment by romanlevin** [comment]
@ilovezfs No, sorry. Closing this. Thanks again for the help!

**Comment by ilovezfs** [comment]
@romanlevin You're welcome!

**Comment by trevor-e** [comment]
I'm running into the same issue. Is there another solution besides changing ownership of `/us/local`? I'd really like to avoid doing that.
