### ISSUE TITLE
brew runs 'update' whenever I open a new terminal

### ISSUE THREAD

**Issue by Edward1992** [Homebrew/brew#3359]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

Due to the special network environment in my country, the command 'brew update' always suffers  a terrible lag and ends up with 'Operation timeout'. Likes following:

> Last login: Tue Oct 24 15:31:10 on ttys000
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
> curl: (7) Failed to connect to akamai.bintray.com port 443: Operation timed out
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
Error: Failed to install vendor Ruby.

This annoying situation comes up every time when I open a new terminal tab. 
<img width="834" alt="screen shot 2017-10-24 at 3 43 59 pm" src="https://user-images.githubusercontent.com/3702423/31930442-50840d72-b8d2-11e7-859b-dd0eaa781987.png">

And I set my env variable *HOMEBREW_NO_AUTO_UPDATE* to 1 and it doesn't work as expected. 
<img width="489" alt="screen shot 2017-10-24 at 3 45 59 pm" src="https://user-images.githubusercontent.com/3702423/31930505-8af9c82a-b8d2-11e7-8ee3-a397c4034fd0.png">

<img width="843" alt="screen shot 2017-10-24 at 3 54 05 pm" src="https://user-images.githubusercontent.com/3702423/31930813-9f8cf7ac-b8d3-11e7-9b6a-3180feb5a2ad.png">

If I uninstall brew, then every time I open a new terminal tab, it shows
<img width="319" alt="screen shot 2017-10-24 at 3 47 16 pm" src="https://user-images.githubusercontent.com/3702423/31930550-b1e45982-b8d2-11e7-8d98-5e18e7765df4.png">

It looks like brew command runs automatically when bash is loaded. Any hint to disable this?

**Comment by ilovezfs** [comment]
> Ran brew config and brew doctor and included their output with your issue?

Please post the `brew config` and `brew doctor` output as requested.

**Comment by MikeMcQuaid** [comment]
> It looks like brew command runs automatically when bash is loaded. Any hint to disable this?

This is something you have configured on your personal machine and doesn't happen by default. These are the commands that prompt an update: https://github.com/Homebrew/brew/blob/357b7bb0b72f5f3e2747ffffdad76d694f73b626/Library/Homebrew/brew.sh#L314

As this relates to you personally and not Homebrew this is being closed. Also, you must always follow the issue template in future.

**Comment by Edward1992** [comment]
<img width="844" alt="screen shot 2017-10-24 at 4 06 23 pm" src="https://user-images.githubusercontent.com/3702423/31931290-518e3866-b8d5-11e7-9cfa-bf118f9e0a8a.png">

As I mentioned before, brew just runs updating operation ignoring what you command. What's even worse is that the network lag makes brew almost unusable.

**Comment by MikeMcQuaid** [comment]
That's not an update operation, it's trying to install Ruby so it can run any command.

**Comment by ilovezfs** [comment]
@Edward1992 you need to download that file one way or another and place it in your Homebrew cache (~/Library/Caches/Homebrew).
