### ISSUE TITLE
MacOsX El Capitan, Scipy doesn't work anymore after brew-upgrade, (missing _fblas.so)

### ISSUE THREAD

**Issue by puiseux** [Homebrew/brew#336]
in python2.7, **scipy** was working until i brew-upgrade scipy, but also : octave, imagemagik, qrupdate, gcc, gd, graphicsmagick and libgsf.
Now, scipy.linalg cannot be imported anymore.
Probably something to do with gcc :

`[Mer jui 08][07:43 ]@[axille] $ python
Python 2.7.11 (default, Jan 11 2016, 05:43:22) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import linalg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/__init__.py", line 174, in <module>
    from .misc import *
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/scipy/linalg/_fblas.so, 2): Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/scipy/linalg/_fblas.so
  Reason: image not found
>>> 
`

gcc5 has been unlinked then linked (`brew unlink gcc5` then `brew link gcc5`)
idem for gcc.
So, what can i do ?
At this time, i'm going to fly with my paraglider.

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/issues/1808
