### ISSUE TITLE
error says keychain GitHub credentials may be invalid when they they are correct

### ISSUE THREAD

**Issue by tomjonandy** [Homebrew/brew#3363]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

`brew search` gives error about invalid GitHub credentials in keychain, even though these credentials are correct. The only thing I can think of that could be causing this is symbols in my github password.

`brew config` output:
```
$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0a32f798a1c944bc52b53a3fb36fb04cca99e386
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2/bin/ruby
Java: 1.8.0_112
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 9.0.1.0.1.1506734476
X11: 2.7.11 => /opt/X11
```

`brew doctor` output:
```
$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
   Use `brew search` to search for a package
- What happened (include command output)
   ```
  $ brew search nyancat
   ==> Searching local taps...
   nyancat
   ==> Searching taps on GitHub...
   Error: GitHub
   The GitHub credentials in the macOS keychain may be invalid.
   Clear them with:
     printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
   Or create a personal access token:
     https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
   and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
   ```
- What you expected to happen
   Not to get the error about GitHub credentials (the credentials in the keychain are correct, I have confirmed this by cloning and pushing to a repository)
- Step-by-step reproduction instructions (by running `brew` commands)
   - Have github credentials in your keychain
   - `brew search nyancat` (Any other string instead of `nyancat` also works)

**Comment by MikeMcQuaid** [comment]
Sorry, this isn't a general bug but something specific to your setup. The output provides several alternatives that it's not clear if you've tried.

**Comment by tomjonandy** [comment]
Sorry, I should have included that and is as follows:

Clearing the credentials does work, but then it is unauthenticated and has the lower rate limits that come with that, and when your credentials inevitably get put back in your keychain by git (storing credentials in keychain is a very useful feature of git IMO). Creating a personal access token also works.

However both of these are just workarounds. The fact that you can do something differently and not get the error, doesn't mean that getting the error in the first place is not a bug.

**Comment by MikeMcQuaid** [comment]
> However both of these are just workarounds.

Yes but, for example, most users do not need either of these workarounds and as there are available workarounds we do not consider there to be any changes warranted here. We would welcome a pull request to address your specific bug but there's nothing here for us to be able to debug what it is or why it affects your machine (and not mine, for example).

**Comment by tomjonandy** [comment]
OK, I have tracked down the bug, the only reason I can see for you not seeing it is that you are using a higher precedence authentication method than just the credentials in keychain (I have none of the environment variables set, for example). Anyway a very simple patch should be coming shortly by way of a PR.

**Comment by MikeMcQuaid** [comment]
@tomjonandy thanks for the PR!

**Comment by oblitum** [comment]
This error shows up for me once I login on GitHub in Safari. Is that expected? I just installed Homebrew it it was all without errors until I logged on my GitHub account.

**Comment by oblitum** [comment]
OK, I fixed by creating the token...
