### ISSUE TITLE
brew upgrade blocking issue

### ISSUE THREAD

**Issue by medioevo** [Homebrew/brew#3369]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

----
-------

I run update/upgrade on a daily basis.
Today I had an issue with upgrade and doctor. The brew's answer ask me to 'report this bug'.

Here the output of brew config
https://gist.github.com/anonymous/fc298e817157f8b98a39ef3841f3916b

and the output of brew doctor
https://gist.github.com/anonymous/e11a25de41904b7178f16062cefa21d8

regards
Enrico

**Comment by MikeMcQuaid** [comment]
@medioevo If you keep opening and closing issues like this you will be blocked from this repository.

**Comment by medioevo** [comment]
Ok, excuse me. It's my first post. The first time I opened a new issue but I wanted only to change the title. Then I solved the issue myself so I thought It was better to close the issue. I apologize if I did something wrong.

**Comment by MikeMcQuaid** [comment]
That's OK. You can change the title without creating a new issue. You should run `cd /usr/local; git reset --hard origin/master; brew update --force` and that should sort you out.

**Comment by medioevo** [comment]
thx
