### ISSUE TITLE
Brew should keep track of installed packages in a lock file

### ISSUE THREAD

**Issue by aarohmankad** [Homebrew/brew#3378]
# Features
Please replace this section with:
- **a detailed description of your proposed feature:** I should be able to version control packages I've installed with `brew` to facilitate easy migrating across computers.

- **the motivation for the feature:** A friend of mine recently got a new Macbook and had to manually install brew packages by pulling up `brew list` on the old computer.

- **how the feature would be relevant to at least 90% of Homebrew users:** 90% of Homebrew users will eventually be upgrading their machines, and have to manually install their packages.

- **what alternatives to the feature you have considered:** Nothing yet, but I'm open to any alternatives!

**Comment by DomT4** [comment]
Kinda sounds like you're looking for https://github.com/Homebrew/homebrew-bundle.

**Comment by ilovezfs** [comment]
Please see https://github.com/Homebrew/brew/issues/2910.
