### ISSUE TITLE
Vendor ruby download failing: bintray/bottles misconfigured?

### ISSUE THREAD

**Issue by PJK** [Homebrew/brew#3390]
Hi, all links from https://homebrew.bintray.com/bottles-portable/ are currently broken; bintray status doesn't report any issues (http://status.bintray.com/). The broken ruby link causes all brew commands to fail if vendor ruby is out of date.

Commands output: https://gist.github.com/PJK/dfa0d810cc3b2845f01e7674be8e816c

Could this be a akamai/bintray issue, or is something else misconfigured/broken?

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by ilovezfs** [comment]
Yep, we know. I just contacted them a few minutes ago.

**Comment by PJK** [comment]
Looks like the link works again. Closing, thanks for the super fast response :)
