### ISSUE TITLE
brew is not insatll on mac

### ISSUE THREAD

**Issue by sumitmundra** [Homebrew/brew#3391]
i am facing this error to insall brew on mac
Downloading and installing Homebrew...
HEAD is now at 7caca57 Merge pull request #3380 from jmsundar/apfs_tap-info
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
Error: Failed to install vendor Ruby.
Failed during: /usr/local/bin/brew update --force

**Comment by ilovezfs** [comment]
All of Bintray is down. I contacted them a few minutes ago.

**Comment by ilovezfs** [comment]
It should be working again now.
