### ISSUE TITLE
`brew changelog $package` should open the changelog 

### ISSUE THREAD

**Issue by jbergstroem** [Homebrew/brew#3399]
### Summary

Opens a changelog for the package you provide. The use-case would be:
```console
$ brew update
Updated Homebrew from c59c0d68 to 6c9ff7f6.
Updated 3 taps (homebrew/core, caskroom/versions, caskroom/cask).
==> New Formulae
ydcv
==> Updated Formulae
git ✔                   fswatch                 gtk+3                   libtiff                 open-mpi                subnetcalc
abyss                   gdcm                    htmldoc                 libtorrent-rasterbar    opencoarrays            sundials
boost-mpi               gibo                    hypre                   libwpg                  pandoc                  telegram-cli
bsponmpi                glib-openssl            jenkins                 libxslt                 pandoc-citeproc         yle-dl
checkstyle              gmime                   konoha                  lynis                   scalapack
feedgnuplot             gmsh                    latexila                node-build              shairport-sync
folly                   gspell                  libconfig               offlineimap             sslh
$ brew changelog git
<opens a browser window with the url to the changelog>
```

### Outline

I'd like to propose the following feature:
```console
$ brew changelog git
```

..which would open the outputted url through a url handler or browser. This would essentially open your browser with the link to the changelog (seen above).

`brew info` would also grow support for showing the changelog link.

## Implementation

The `Formula` object would grow a `changelog` attribute. This would be the url to the generic changelog. I don't know homebrew well enough to know if there are generics for hosts like github/gitlab; but if that does exist, we could also fold the releases pages to automatically represent this.

Finally, a potential flag could be linking to the specific version provided:
```console
$ brew changelog git 2.15.0
<opens the release page for this version>
```

**Comment by MikeMcQuaid** [comment]
For this to be a thing it would need to be built like `brew desc` was: a community would need to amass these URLs for every (relevant) package in Homebrew in an external command in a third party tap and we'd consider merging it into Homebrew proper after that process is complete. Sorry!

**Comment by jbergstroem** [comment]
@MikeMcQuaid said:
> For this to be a thing it would need to be built like `brew desc` was: a community would need to amass these URLs for every (relevant) package in Homebrew in an external command in a third party tap and we'd consider merging it into Homebrew proper after that process is complete. Sorry!

Don't be (sorry)! Makes sense. Out of curiosity, was there an issue that started that movement? I'd like to better understand how "people got into helping out".

**Comment by MikeMcQuaid** [comment]
@jbergstroem @telemachus would be the best person to explain that (when he gets a chance!).

**Comment by telemachus** [comment]
@jbergstroem If by *issue*, you mean a literal old issue here on the tracker, there was one (a few in fact), but they seem to be gone now. (Maybe some history was lost when Homebrew divided into multiple repos? Or maybe I'm not searching in the right repos. I'm not sure.)

In a nutshell, several people had posted issues long ago asking if we could add short descriptions to brew's formulas. The maintainers said that they couldn't do all that work themselves, but that they were open to the idea, so I created a [distinct external command (`brew desc`)](https://github.com/telemachus/homebrew-desc). Eventually, with a lot of help from others, we had 100% coverage, and the external command was merged into `brew` proper.

In terms of how I got people to help, it was very unsystematic. I talked about it in IRC, and on Twitter, and the repo was on GitHub. People somehow caught wind of the project and many helped.

**Comment by MikeMcQuaid** [comment]
> @jbergstroem If by issue, you mean a literal old issue here on the tracker, there was one (a few in fact), but they seem to be gone now.

Check https://github.com/Homebrew/legacy-homebrew

**Comment by telemachus** [comment]
My original issue: https://github.com/Homebrew/legacy-homebrew/issues/2889

My announcement of `brew desc` (the external command): https://github.com/Homebrew/legacy-homebrew/issues/2928

**Comment by monouser7dig** [comment]
I‘d certainly be willing to contribute links and think this is a useful feature. 

Two comments:
Not every project has chengelogs so 100% coverage may not be feasible.

And:
Will this also be supported for homebrew cask in the same run?

**Comment by ilovezfs** [comment]
I think locating specifying changelog locations in formulae is redundant with specifying the homepage so I wouldn't support this even if it did achieve full coverage.
