### ISSUE TITLE
Suggestion - brew should retry download before abandoning bottle and D/L'ing source

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/brew#3400]
I had a network hiccup while brew was trying to download a bottle. Instead of retrying or noticing the network problem, brew gave up on the bottle and instead started downloading the source to build from instead.

Suggestion: brew should either retry or determine it's a network issue and not immediately abandon the bottle download and switch to building from source.

**Comment by MikeMcQuaid** [comment]
Most of the time there's a network failure it's not a hiccup but is a legitimate problem retrying won't help. As a result, the current behaviour makes more sense.

Also, from the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

**Comment by edrozenberg** [comment]
Thanks, honest difference of opinion on whether a retry would make sense - in my case a VPN I use causes flakiness at times, and it is not a "legitimate" problem.

For bugs I normally fill out the template, but spending 15-30 minutes on the template for a minor suggestion is not worth it for me personally and I felt the Homebrew project was better served by my sending something in than nothing. The project may disagree, fair enough.

**Comment by MikeMcQuaid** [comment]
> The project may disagree, fair enough.

We do (and the template says we do).
