### ISSUE TITLE
Shall we run `brew update` automatically?

### ISSUE THREAD

**Issue by bronze1man** [Homebrew/brew#3402]
Repeat as https://github.com/Homebrew/brew/issues/288
But I think running `brew update` before `brew install` automatically is a worst idea.

# Features
Please replace this section with:
- a detailed description of your proposed feature
   * Just give me a version of brew that do not try `brew update` before install forever. That will save a lot of energy for us with slow network. `brew update` can hangout for 1 hour and it never finish .I always ctrl+c to let it do the actually work. The rubbish `brew update` step make brew more manually. I want to reinvented the wheel to make it more automatically. Not everybody is in the USA with a good network. Depend too much with network is just a not-working option.
- the motivation for the feature
   * `brew update` can hangout for 1 hour and it never finish .I always ctrl+c to let it do the actually work.
- how the feature would be relevant to at least 90% of Homebrew users
   * Lots of users just do not have a good network to your servers. The network problem will never be solved. 
- what alternatives to the feature you have considered
   * Give me an option that can disable `brew update` before install forever.This option is NOT as automatically as a version of brew that do not try `brew update` before install forever.

If you guys do not accept this `Features`, I think I may change the code myself.

**Comment by ilovezfs** [comment]
You can set HOMEBREW_NO_AUTO_UPDATE

**Comment by MikeMcQuaid** [comment]
> Give me an option that can disable brew update before install forever.This option is NOT as automatically as a version of brew that do not try brew update before install forever.

Please read `man brew` which details both how to make it run less often and how to turn it off altogether.
