### ISSUE TITLE
Homebrew must be run under Ruby 2.3! You're running 2.0.0

### ISSUE THREAD

**Issue by weimingwill** [Homebrew/brew#3404]
Any `brew` command I run (no matter `brew update`, `brew -v`), it gives me this error.
```
/Library/Ruby/Site/2.0.0/rubygems/version.rb:191:in `strip!': can't modify frozen String (RuntimeError)
	from /Library/Ruby/Site/2.0.0/rubygems/version.rb:191:in `initialize'
	from -e:1:in `new'
	from -e:1:in `<main>'
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)
```

I know that there are some related issues with this, but after checking all of them, I still cannot find any solution to it. 

Anyone can help with it?

Thank you.

**Comment by ilovezfs** [comment]
try `brew update-reset`

**Comment by weimingwill** [comment]
@ilovezfs This command can run well. But after resetting it, it still has the same error.

**Comment by ilovezfs** [comment]
OK, what is the output of
```
git --no-pager -C /usr/local/Homebrew tag -l
```

**Comment by weimingwill** [comment]
@ilovezfs

**Comment by ilovezfs** [comment]
And how about
```
git -C /usr/local/Homebrew status
```

**Comment by weimingwill** [comment]
```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

**Comment by ilovezfs** [comment]
And can you run `brew doctor` now?

**Comment by weimingwill** [comment]
No, I can't
```
➜  brew doctor
/Library/Ruby/Site/2.0.0/rubygems/version.rb:191:in `strip!': can't modify frozen String (RuntimeError)
	from /Library/Ruby/Site/2.0.0/rubygems/version.rb:191:in `initialize'
	from -e:1:in `new'
	from -e:1:in `<main>'
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)
```

**Comment by ilovezfs** [comment]
OK. Try this please
```
mkdir ~/rubygems-20171031
sudo mv /Library/Ruby/Site/2.0.0/rubygems ~/rubygems-20171031/
```

And then try `brew doctor` and `brew config`

**Comment by weimingwill** [comment]
It seems that it cannot find needed things.
```
➜  mkdir ~/rubygems-20171031
➜  sudo mv /Library/Ruby/Site/2.0.0/rubygems ~/rubygems-20171031/
Password:
➜ brew doctor
/Library/Ruby/Site/2.0.0/rubygems.rb:1259:in `require': cannot load such file -- rubygems/custom_require (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems.rb:1259:in `<top (required)>'
	from <internal:gem_prelude>:1:in `require'
	from <internal:gem_prelude>:1:in `<compiled>'
/Library/Ruby/Site/2.0.0/rubygems.rb:1259:in `require': cannot load such file -- rubygems/custom_require (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems.rb:1259:in `<top (required)>'
	from <internal:gem_prelude>:1:in `require'
	from <internal:gem_prelude>:1:in `<compiled>'
```

**Comment by MikeMcQuaid** [comment]
Try to uninstall and install Homebrew again using the instructions on https://github.com/Homebrew/install

**Comment by ilovezfs** [comment]
@weimingwill also try moving
```
sudo mv /Library/Ruby/Site/2.0.0/rubygems.rb ~/rubygems-20171031/
```

**Comment by weimingwill** [comment]
@MikeMcQuaid I have tried that previously. Thanks.
@ilovezfs It works now!!! 
May I know why it happens? 
What is the ruby it refers to if it cannot find it at `/Library/Ruby/Site/2.0.0/`? 
Can I put the ruby back to its location?
Thank you!

**Comment by ilovezfs** [comment]
@weimingwill I'm really not sure where your `/Library/Ruby/Site/2.0.0/rubygems` directory and `/Library/Ruby/Site/2.0.0/rubygems.rb` came from. They're not part of a pristine macOS installation so they came from ... somewhere. Maybe you know. I wouldn't put them back, as I would expect the same bug will return if you do.

**Comment by weimingwill** [comment]
@ilovezfs It may be installed 1+ years ago, which I don't remember alr. I thought it is part from macOS and didn't dare to remove it.

**Comment by hofffmancx** [comment]
when I install cmake, I found this problem too. 
I repeat install, and question solved.
