### ISSUE TITLE
brew update fails if there are unstashed changes in homebrew core

### ISSUE THREAD

**Issue by hanxue** [Homebrew/brew#3410]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

## Problem

When running `brew` `install`, `upgrade` or `update` commands, if there unstaged changes, the core library will get mangled:

```
$ brew upgrade ghi
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
ghi 1.2.0_1
Error: ruby: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby.rb:9: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby.rb:13: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby.rb:18: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
```

## How To Reproduce

```
$ brew create http://path/to/file.tar.gz`
```

Leaving the newly generated file in `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core`

```
$ git status --porcelain
 M Formula/ruby.rb
?? Formula/parse.rb

```
## Feature

Perhaps a warning to the user to `stash` changes or clean the working directory before pulling the latest update?

**Comment by MikeMcQuaid** [comment]
This only happens when you have run Homebrew developer commands and the assumption is that you know how to address these merge conflicts.

**Comment by treedom** [comment]
"Error: c-ares: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/c-ares.rb:39: syntax error, unexpected ';', expecting =>
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/c-ares.rb:42: syntax error, unexpected '}', expecting keyword_end"


I come across the problem too, but dont know how to fix it

**Comment by ilovezfs** [comment]
@treedom you can try `brew update-reset`

**Comment by Valloric** [comment]
@ilovezfs Fantastic, thank you! Fixed by problem right away.
@MikeMcQuaid I've never run brew developer commands and I encountered this issue.
