### ISSUE TITLE
How to deprecate a formula

### ISSUE THREAD

**Issue by domoritz** [Homebrew/brew#3415]
I'm trying to deprecate a formula and replace it with a new one in https://github.com/Homebrew/homebrew-core/pull/20185. I couldn't find the right documentation for it, though. Do I just send a PR that removes the old formula?

**Comment by MikeMcQuaid** [comment]
> Do I just send a PR that removes the old formula?

Add the deletion to your existing open PR and we'll guide you through the rest. Thanks!
