### ISSUE TITLE
Error: Checksum mismatch.

### ISSUE THREAD

**Issue by Petelin** [Homebrew/brew#3419]
[~]$ brew install wget
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
Already downloaded: /Users/zhangxiaolin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
Usage: DynaLoader::dl_find_symbol(libhandle, symbolname) at /Users/zhangxiaolin/perl5/lib/perl5/darwin-thread-multi-2level/XSLoader.pm line 89.
Compilation failed in require at /usr/bin/shasum5.18 line 101.
BEGIN failed--compilation aborted at /usr/bin/shasum5.18 line 101.
Error: Checksum mismatch.
Expected: 34ce9e4c9c1be28db564d744165aa29291426f8a3d2ef806ba4f0b9175aedb2b
Actual:
Archive: /Users/zhangxiaolin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.

**Comment by MikeMcQuaid** [comment]
`rm -rf /Users/zhangxiaolin/perl5` and run it again; you have broken `/usr/bin/shasum5.18` which Homebrew needs to function.

**Comment by zuoyou1314** [comment]
I have same  error ,  you can delete   /Users/zhangxiaolin/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz   solve  the problem .
