### ISSUE TITLE
brew tests fails with Git 2.15

### ISSUE THREAD

**Issue by amyspark** [Homebrew/brew#3425]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

> To help us debug your issue please explain:
> - What you were trying to do (and why)

Ran `brew tests`.

> - What happened (include command output)

The following tests failed:
```
Failures:

  1) brew tap taps a given Tap
     Failure/Error:
       expect { brew "tap", "homebrew/bar", path/".git" }
         .to output(/Tapped/).to_stdout
         .and output(/Cloning/).to_stderr
         .and be_a_success
     
       expected block to output /Cloning/ to stderr, but output "Clonando en '/tmp/homebrew-tests-20171105-32745-i47atr/prefix/Library/Taps/homebrew/homebrew-bar'...\nhecho.\n"
     # ./test/dev-cmd/tap_spec.rb:53:in `block (2 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/integration_test.rb:44:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:100:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 19 seconds (files took 2.05 seconds to load)
434 examples, 1 failure, 1 pending

Failed examples:

rspec ./test/dev-cmd/tap_spec.rb:2 # brew tap taps a given Tap
```
> - What you expected to happen

I expected the tests to succeed.

> - Step-by-step reproduction instructions (by running `brew` commands)

Install Git 2.15 with `brew install git`, and set the environment variables `LC_ALL` and `LANG` to a non-English locale. In my case,
```
LC_ALL=es_ES.UTF-8
LANG=es_ES.UTF-8
```
I think these should be unset before executing the tests.

**Comment by MikeMcQuaid** [comment]
> I think these should be unset before executing the tests.

This is something you'll need to do manually, I'm afraid, until https://github.com/Homebrew/brew/issues/932 is completed.
