### ISSUE TITLE
How to run brew without sudo, for unattended upgrade scripts?

### ISSUE THREAD

**Issue by joelparkerhenderson** [Homebrew/brew#3428]
The symptom: run `brew upgrade` and it upgrades many packages, but if a package needs sudo, then the entire upgrade stops, and prompts the user to type in the sudo password. The rest of the upgrade does not proceed.

The problem: there doesn't seem to be a way to tell brew to upgrade as much as possible unattended; this makes it difficult to automate brew.

The goal: I want to run a nightly brew upgrade, unattended, and have the upgrade do as much as possible, without stopping for a password. 

Possible ideas:

1. Unattended nightly upgrade. Do as much as possible .Skip anything that needs sudo.

2. Make `brew install` behave similarly. Do as much as possible. Skip anything that needs sudo.

3. Make `brew fetch` able to behave as a sort of fallback, such that `brew upgrade` and `brew install` can proceed with downloading a sudo-necessary package, so the package is available locally for whenever I have time to do sudo.

Thanks for your consideration.

Edit: I found a related issue that doesn't seem to have any solution yet. https://github.com/Homebrew/brew/issues/1293 (That issue seems to focus more on whether sudo is necessary at all, or can be done one time up front, or can use a longer timeout -- these areas are not what I'm asking about in this issue. I understand why sudo is necessary for some packages. I do *not* want sudo one time up front. I do *not* want sudo to have a longer timeout. I just want to skip anything that needs sudo.)

**Comment by MikeMcQuaid** [comment]
@joelparkerhenderson Please fill out the issue template in future.

`brew install` never needs sudo. `brew cask install` may need sudo on occasion. You can script it not to prompt yourself by making use of the (documented) `SUDO_ASKPASS` variable in `man brew-cask`.

> I understand why sudo is necessary for some packages. I do not want sudo one time up front. I do not want sudo to have a longer timeout. I just want to skip anything that needs sudo

You have a potential workaround but we do not support your exact use-case. That said, you may be able to build something yourself to do this.

**Comment by joelparkerhenderson** [comment]
> we do not support your exact use-case.

I agree. That's why this area is worth a look as an open issue: this use-case can help many users, and help worldwide security, and help authors of brew packages who want to distribute bug fixes quickly. It's a win-win-win.

Can you please keep this issue open? 

If it's ok with you, this open issue can be a place for people to comment on potential implementation ideas. 

I'm interested in a command line option, rather than a workaround or environment variable. I'm interested in a solution that succeeds inside a typical bash script that uses set -uef.

If it's ok with you, I can offer a bounty. If a coder responds to this issue and writes code that's accepted into brew, then I'll donate $100 to the coder, or to their favorite charity.

**Comment by joelparkerhenderson** [comment]
> even if someone were to implement this perfectly I'm not sure if we would accept the PR.

What would/could convince you to accept a PR that does this?

> that's a personal preference that I do not see any basis for believing is a majority one.

What would/could be a basis? I ask because I would be happy to do the legwork to find out, such as contacting leading brew users and developers to see if an option flag is reasonable, if you and your team are open to considering it.

**Comment by MikeMcQuaid** [comment]
> and the minority power users can gain capabilities for automation and security

We do not have the resources to be adding and maintaining just code for minority power users, sometimes. This is why the issue template (which you didn't fill out) asks for "how the feature would be relevant to at least 90% of Homebrew users". You seem to agree in this case: it is not.

> What would/could be a basis for seeing if the feature is desired by people in the community?

Figuring out what things are desired by the community is the job of the maintainers not the community.  As the lead/longest-running maintainer, ultimately these things tend to fall mostly to me to decide.

**Comment by joelparkerhenderson** [comment]
I have good news. >90% of people want automatic updates as a default. 

Because of this new information, I would like increase my donation offer to $200 toward improving brew to do automatic updates as a default, including a way to bypass any sudo blockers.

Any kind of solution is fine, such as what macOS does with a prompt "New updates are available; download and install them?" or what Chrome does, or what Firefox does. 

It turns out there are a bunch of use cases that all converge:

  * Novice use case: "Keep me up to date. Don't make me think."

  * Intermediate use case: "Chrome, Firefox, and many apps have switch from manual updates to automatic updates. Do it like that."

  * Developer use case: "Developers who need stability should not be using the local OS; they should be using (Docker|Vagrant|VMs|containers) and (mas|npm|pip|bundler|pinning) and (ansible|puppet|salt)".

  * Security use case: "Look at semantic versioning to indicate bug fix upgrades. Look at how Debian does this with dpkg-reconfigure unattended-upgrades. Upgrade everything that is a bug fix upgrade, or security upgrade, and is entirely in user space."

  * UI/UX use case: "Try to find anyone anywhere who starts to install an app, gives sudo permission to the app for its installation, then later on starts to upgrade the same app, but then denies permission to the same app."

Thanks again for your consideration and correspondence. Brew is great, and I'm asking for this capability because I love brew, depend on brew, and I want to use it even more.

**Comment by MikeMcQuaid** [comment]
> Because of this new information

This is your opinion, it is not information.

> I would like increase my donation offer to $200 toward improving brew to do automatic updates as a default, including a way to bypass any sudo blockers.

This is definitely not going to get merged.

> "Developers who need stability should not be using the local OS; they should be using (Docker|Vagrant|VMs|containers) and (mas|npm|pip|bundler|pinning) and (ansible|puppet|salt)".

I very heavily disagree with this and it will break Homebrew for many people to take this approach.

> I'm asking for this capability because I love brew, depend on brew, and I want to use it even more.

Diplomatically: you've been told no in many different ways: please accept that.

**Comment by MikeMcQuaid** [comment]
In fact probably the best use of everyone's time at this point is to lock this thread.
