### ISSUE TITLE
bottle tag for private formula

### ISSUE THREAD

**Issue by randy3k** [Homebrew/brew#3429]
I have a private formula and I would like to also provide a bottle for the formula. However, I am a little bit unsure how to specify the bottle block for all macos platforms without building a bottle for each platform. Idealy, I am looking for 

```
  bottle do
    cellar :any
    root_url https://example.com
    sha256 "<HASH>" => :macos
  end
```
and the bottle is located at `https://example.com/<formula>-<ver>.macos.bottle.tar.gz`

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

This your second warning on this. In this case, this is a better question for our Discourse forum: https://discourse.brew.sh

Note, we do not support building a single bottle for all macOS versions.
