### ISSUE TITLE
Unexpected static libraries

### ISSUE THREAD

**Issue by Siri-O** [Homebrew/brew#3438]
Hello!

I am having this warning when run `brew doctor
`
Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libFaceGen_Macosx.a
  /usr/local/lib/libGranny.a
  /usr/local/lib/liblibexpat.a

I read some posts about libraries but any with those names. I would like to know if I ingnore this or need to do something? 

Thanks!

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

Also, from `brew doctor`'s output it says you can ignore them.

**Comment by Siri-O** [comment]
Sorry, but where is this issue checklist?

**Comment by MikeMcQuaid** [comment]
@Siri-O You deleted it when you created the issue.

**Comment by Siri-O** [comment]
So, I need to create again?

**Comment by MikeMcQuaid** [comment]
No, I answered your question. You need to read my reply and, in future, read the issue template.
