### ISSUE TITLE
Use httpd instead of deprecated homebrew/apache/httpd24 when I remove nginx

### ISSUE THREAD

**Issue by webmobiles** [Homebrew/brew#3448]
I had installed apache2 and nginx, then I tried to remove nginx, it works ok, simply I get an warning

$ brew remove nginx
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Uninstalling /usr/local/Cellar/nginx/1.12.2_1... (23 files, 1MB)

I"ve removed apache before, and I've removed nginx, and reinstalled nginx and remove to see if that message disapear but not.  So i think in some place there is something with apache2 that brew dont' like... how to remove it ?

my brew config:

HOMEBREW_VERSION: 1.3.7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 441c212f2dd70f053ee21eac8398c5fe5dfd0551
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0725e7a865344fe73bc37147e964e655b8d6460c
Core tap last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102, 1.8.0_101, 1.8.0_73, 1.6.0_65-b14-466.1
macOS: 10.11.6-x86_64
Xcode: 8.0

**Comment by MikeMcQuaid** [comment]
You can ignore this error.
