### ISSUE TITLE
"Xcode alone is not sufficient on Sierra"

### ISSUE THREAD

**Issue by chrisfinazzo** [Homebrew/brew#3456]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

Just tried to upgrade `mkvtoolnix` and came across this error. As of yesterday everything worked until I installed Mac App Store updates. As usual in these situations, Homebrew warns about outdated Xcode, but the preferences show the 8.3.3 CLT as installed, so other than the fact that they should be updated, the error makes little sense.

<img width="585" alt="screen shot 2017-11-18 at 10 42 00 am" src="https://user-images.githubusercontent.com/1534882/32982227-e389db94-cc4e-11e7-9c16-b162536cc9b3.png">

`brew config` shows the following: 

    HOMEBREW_VERSION: 1.3.7-21-gdbc04b4
    ORIGIN: https://github.com/Homebrew/brew.git
    HEAD: dbc04b4dc701aa1d0aa9197dd12be92c7b1800fc
    Last commit: 4 hours ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 2326a5e30a39cae154ef6deccf0e2bf115e9585c
    Core tap last commit: 56 minutes ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_DEV_CMD_RUN: 1
    HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
    CPU: octa-core 64-bit haswell
    Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
    Clang: 8.1 build 802
    Git: 2.15.0 => /usr/local/bin/git
    Curl: 7.54.0 => /usr/bin/curl
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /Users/Chris/.rbenv/shims/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
    Java: N/A
    macOS: 10.12.6-x86_64
    Xcode: 8.3.3
    CLT: N/A
    X11: N/A

My best guess is this is a side effect of the behavior described [here][] and Xcode expects 9.x to be installed 🤔.

[here]: https://512pixels.net/2017/11/apple-begins-high-sierra-automatic-rollout/

**Comment by MikeMcQuaid** [comment]
> Ran brew doctor, fixed all issues and retried your prior step?

You did not do this.

**Comment by MikeMcQuaid** [comment]
> My best guess is this is a side effect of the behavior described here and Xcode expects 9.x to be installed 🤔.

We now require the CLT to be installed as well as Xcode on Sierra.

**Comment by chrisfinazzo** [comment]
I just found #3453 which explains this change, thanks.

**Comment by apexad** [comment]
Just for anyone coming to look at this issue in the future, `/Library/Homebrew/os/mac.rb` holds the key to disabling this warning temporarily.

```ruby
 def latest_sdk_version
      # TODO: bump version when new Xcode macOS SDK is released
      Version.new "10.12"
 end
``
Change the Version.new to be the version of the SDK your Xcode has, such as 10.12 if using Xcode 8.3.3

**This is not advised and may cause odd behavior, but may be necessary if you are not able to install the Command Line Tools or an Updated version of Xcode.**

**Comment by ilovezfs** [comment]
@apexad please do not post stuff like that here.
