### ISSUE TITLE
Error on 'brew upgrade'

### ISSUE THREAD

**Issue by wkuckro** [Homebrew/brew#3458]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
brew config: 
```
HOMEBREW_VERSION: 1.1.6
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 619791e83d2781dca1b675e20249a8aebe085c7c
Last commit: 11 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8eb2790629b3a4932f9710022968d7d500d8412e
Core tap last commit: 12 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 8.0
CLT: 9.1.0.0.1.1508540944
X11: 2.7.9 => /opt/X11
```
brew doctor: 
```
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:73: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:77: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    can add a "gnubin" directory to your PATH from your bashrc like:
                                ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:77: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:79: dynamic constant assignment
        PATH="#{opt_libexec}/gnubin:$PATH"
             ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: dynamic constant assignment
    Additionally, you can access their man pag...
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    Additionally, you can access their man pages with ...
                         ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:82: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    the "gnuman" directory to your MANPATH from your bashrc as well:
                          ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:82: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:84: dynamic constant assignment
        MANPATH="#{opt_libexec}/gnuman:$MANPATH"
                ^
```
To help us debug your issue please explain:
- brew upgrade
- errors, even after chmod the usr folder.
fatal: 'refs/tags/?[1;35;40m?[K1.3.7?[m?[K' is not a commit and a branch 'stable' cannot be created from it
fatal: Needed a single revision
invalid upstream refs/tags/1.3.7
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/aircrack-ng.rb:36: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/aircrack-ng.rb:37: syntax error, unexpected tIDENTIFIER, expecting keyword_end
...airodump-ng-oui-update` install or update the Airodump-ng OU...
...                               ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/aircrack-ng.rb:37: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
...l or update the Airodump-ng OUI file.
...                               ^

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
> fatal: 'refs/tags/?[1;35;40m?[K1.3.7?[m?[K' is not a commit and a branch 'stable' cannot be created from it
> fatal: Needed a single revision
> invalid upstream refs/tags/1.3.7

This indicates an error with your local Git or Bash configuration that you will need to figure out and resolve yourself, sorry.
