### ISSUE TITLE
Brew doesn't register Brew installed gcc-6 as supporting C++11

### ISSUE THREAD

**Issue by msbit** [Homebrew/brew#346]
- [✓] Ran `brew update` and retried your prior step?
- [✕] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [-] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Firstly, I'm aware that I'm running OS X Lion, so if this doesn't get priority, I understand. Having said that, this looks like it would be an issue across the board for later OS X installs trying to build with Brew installed `gcc` as well.

I've tried installing the `v8` formula, and it goes a bit like this:

    $ brew install v8
    Warning: You are using OS X 10.7.
    We (and Apple) do not provide support for this old version.
    You may encounter build failures or other breakages.
    Error: v8 cannot be built with any available compilers.
    To install this formula, you may need to:
      brew install gcc

Fair enough, I'll do that:

    $ brew install gcc 
    Warning: You are using OS X 10.7.
    We (and Apple) do not provide support for this old version.
    You may encounter build failures or other breakages.
    ==> Installing dependencies for gcc: gmp, mpfr, libmpc, isl 
    ==> Installing gcc dependency: gmp 
    
    ... 
    
    ==> Caveats
    GCC has been built with multilib support. Notably, OpenMP may not work:
      https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
    If you need OpenMP support you may want to
      brew reinstall gcc --without-multilib
    ==> Summary
    🍺  /usr/local/Cellar/gcc/6.1.0: 1,434 files, 282M, built in 95 minutes 39 seconds

and then:

    $ brew install v8
    Warning: You are using OS X 10.7.
    We (and Apple) do not provide support for this old version.
    You may encounter build failures or other breakages.
    ==> Downloading https://github.com/v8/v8-git-mirror/archive/5.1.281.47.tar.gz
    ==> Downloading from https://codeload.github.com/v8/v8/tar.gz/5.1.281.47
    ######################################################################## 100.0%
    Error: The selected compiler doesn't support C++11: gcc-6

With the following changes to my Brew install:

    $ git -C /usr/local diff
    diff --git a/Library/Homebrew/extend/ENV/std.rb b/Library/Homebrew/extend/ENV/std.rb
    index 87eebb7..0bdfd38 100644
    --- a/Library/Homebrew/extend/ENV/std.rb
    +++ b/Library/Homebrew/extend/ENV/std.rb
    @@ -287,7 +287,7 @@ module Stdenv
         if compiler == :clang
           append "CXX", "-std=c++11"
           append "CXX", "-stdlib=libc++"
    -    elsif compiler =~ /gcc-(4\.(8|9)|5)/
    +    elsif compiler =~ /gcc-(4\.(8|9)|5|6)/
           append "CXX", "-std=c++11"
         else
           raise "The selected compiler doesn't support C++11: #{compiler}"
    diff --git a/Library/Homebrew/extend/ENV/super.rb b/Library/Homebrew/extend/ENV/super.rb
    index 7f335ac..a04b9d4 100644
    --- a/Library/Homebrew/extend/ENV/super.rb
    +++ b/Library/Homebrew/extend/ENV/super.rb
    @@ -307,7 +307,7 @@ module Superenv
         when "clang"
           append "HOMEBREW_CCCFG", "x", ""
           append "HOMEBREW_CCCFG", "g", ""
    -    when /gcc-(4\.(8|9)|5)/
    +    when /gcc-(4\.(8|9)|5|6)/
           append "HOMEBREW_CCCFG", "x", ""
         else
           raise "The selected compiler doesn't support C++11: #{homebrew_cc}"

And right now installing `v8` is progressing (currently downloading deps).

**Comment by UniqMartin** [comment]
This is an actual bug and an oversight on our part in #163. Thanks for catching and reporting it!

> With the following changes to my Brew install:

Since you already have a good solution, would you mind submitting it as a pull request, referencing this issue and PR #163 for context? I'd be happy to give you commit credit for finding and fixing this. Thanks!
