### ISSUE TITLE
adding jacktrip to homebrew

### ISSUE THREAD

**Issue by tmm2018** [Homebrew/brew#3475]
## Greetings

**I would suggest you guys to:**
- *add jacktrip to homebrew*

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

As the template says,

>If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core 

And as the [Homebrew/homebrew-core issue template]https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE.md#formula-additions-or-changes) says

>To get formulae added or changed in Homebrew please file a Pull Request We will close issues requesting formulae changes.
