### ISSUE TITLE
MacOS builds in Travis are not reporting Codecov metadata

### ISSUE THREAD

**Issue by amyspark** [Homebrew/brew#3476]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Uploaded a new patch to my pull request (#3396)

- What happened (include command output)

Triggered Travis CI build. But the build log for MacOS includes:
```
{"meta": {"status": 400}, "error": {"reason": "Please provide the repository token to upload reports via `-t :repository-token`", "context": null}}
```

- What you expected to happen

I expect the metadata to be uploaded and the Github status check to appropriately include this information.

- Step-by-step reproduction instructions (by running `brew` commands)

N/A

**Comment by MikeMcQuaid** [comment]
Thanks for the report @amyspark!
