### ISSUE TITLE
Installation of brew fails with error install_brew:280:in `<main>': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by zoltan0907** [Homebrew/brew#3481]
Hi there.

I think i got the same error as in #2831 which sadly was closed. Just for completeness, i was able to solve the problem. I had to run "sudo xcodebuild -license" to aggree the xcode-license. After that the installation went fine. If the licence was not aggreed, xcode prints out an error.

```
$/usr/bin/xcrun clang 2>&1


Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.


```

Thanks and Regards
Tino

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.
