### ISSUE TITLE
curl doesn't respect "http_proxy" environment variable when brew-installing

### ISSUE THREAD

**Issue by kkdd** [Homebrew/brew#3494]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

----------------------
Hello,
I have observed that ```curl``` discontinues respecting "http_proxy" environment variable when executed in homebrew 1.3.8-49-g0d26baa (see below) and the description of proxy setting should be added in a .curlrc file for solving this issue. Is it intended behavior?

```
$ brew install curl
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/curl-7.56.1.el_capitan.bott

curl: (6) Could not resolve host: homebrew.bintray.com
Error: Failed to download resource "curl"
Download failed: https://homebrew.bintray.com/bottles/curl-7.56.1.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://curl.haxx.se/download/curl-7.56.1.tar.bz2

curl: (6) Could not resolve host: curl.haxx.se
Trying a mirror...
==> Downloading http://curl.askapache.com/download/curl-7.56.1.tar.bz2

curl: (6) Could not resolve host: curl.askapache.com
Error: Failed to download resource "curl"
Download failed: http://curl.askapache.com/download/curl-7.56.1.tar.bz2
```

```
% brew doctor
Your system is ready to brew.
% brew --config
HOMEBREW_VERSION: 1.3.8-49-g0d26baa
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0d26baa938db0445b7154d94f1fafe12f45d5285
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fc480fcce726cfbeec342b1323a71f89c2cec4ba
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_ENV_FILTERING: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GIT_CONFIG_DEVELOPERMODE: true
CPU: octa-core 64-bit penryn
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/kkondo/.rbenv/shims/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

When curl is executed outside of homebrew, it continues respecting "http_proxy" environment variable as follows:
```
$ curl -O https://curl.haxx.se/download/curl-7.56.1.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2758k  100 2758k    0     0   400k      0  0:00:06  0:00:06 --:--:--  471k
$ shasum -a 256 curl-7.56.1.tar.bz2
2594670367875e7d87b0f129b5e4690150780884d90244ba0fe3e74a778b5f90  curl-7.56.1.tar.bz2
```

**Comment by MikeMcQuaid** [comment]
Thanks for the report @kkdd! Should be fixed now.

**Comment by AskApache** [comment]
So all good?  First time I've seen a report of a prob with curl.askapache
