### ISSUE TITLE
https_proxy not in FILTERED_ENV

### ISSUE THREAD

**Issue by wtnb75** [Homebrew/brew#3500]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- run `brew update` behind proxy
- got `fatal: unable to access 'https://github.com/Homebrew/brew.git/': Failed to connect to github.com port 443: Operation timed out`
  - git command failed (`/Applications/Xcode.app/Contents/Developer/usr/bin/git fetch --tags --force -q origin refs/heads/master:refs/remotes/origin/master`)

# Features

- https://github.com/Homebrew/brew/blob/master/bin/brew#L91
  - there is no http**s**_proxy in FILTERED_ENV (but http_proxy)
    - see: #3494 / 63408a10ff677909f4397c5c94cfa1f2007c0826
  - please add `https_proxy`, `ftp_proxy`, `no_proxy`

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by benmwebb** [comment]
Note that the `curl` manpage lists `HTTPS_PROXY` rather than `https_proxy` (although both seem to work in my testing) so `FILTERED_ENV` should probably also include capitalized versions.
