### ISSUE TITLE
No available formula

### ISSUE THREAD

**Issue by 497256303** [Homebrew/brew#3502]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features

I want to install opencv today.
I use `brew install opencv` and get an error
Error: No available formula with the name "opencv"
Error: 784: unexpected token at...

Then I use other's suggest `brew tap homebrew/science` and `brew install opencv`
or `brew install homebrew/science/opencv`
it's the same Error.

Another kind person suggested
> `brew update-reset` should fix this.

but after that I use `brew install homebrew/science/opencv` again and got this error
Error: No available formula with the name "opencv"
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

What should I do?

**Comment by ilovezfs** [comment]
>What should I do?

You should fill out the issue template.

**Comment by 497256303** [comment]
> You should fill out the issue template.
Sorry, I'm new here.
Thanks for your suggestion!

**Comment by ilovezfs** [comment]
>Ran brew config and brew doctor and included their output with your issue?

**Comment by 497256303** [comment]
`brew config`
HOMEBREW_VERSION: 1.3.8-54-g2b7ecb4
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: 2b7ecb47934018b95b681ee5a49f86286242c838
Last commit: 11 hours ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: 289c0a835136bca183028bad993c78363e428ccf
Core tap last commit: 10 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/zby/anaconda3/bin/python => /Users/zby/anaconda3/bin/python3.6
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 9.0.1, 1.8.0_151
macOS: 10.13.1-x86_64
Xcode: N/A
CLT: 9.1.0.0.1.1508540944
X11: N/A


`brew doctor`
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Suspicious Homebrew/brew git origin remote found.

With a non-standard origin, Homebrew won't pull updates from
the main repository. The current git origin is:
  https://mirrors.ustc.edu.cn/brew.git

Unless you have compelling reasons, consider setting the
origin remote to point at the main repository by running:
  git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew.git

Warning: Anaconda is known to frequently break Homebrew builds, including Vim and
MacVim, due to bundling many duplicates of system and Homebrew-available
tools.

If you encounter a build failure please temporarily remove Anaconda
from your $PATH and attempt the build again prior to reporting the
failure to us. Thanks!

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/zby/anaconda3/bin/icu-config
  /Users/zby/anaconda3/bin/freetype-config
  /Users/zby/anaconda3/bin/xslt-config
  /Users/zby/anaconda3/bin/libpng16-config
  /Users/zby/anaconda3/bin/python3.6m-config
  /Users/zby/anaconda3/bin/libpng-config
  /Users/zby/anaconda3/bin/xml2-config
  /Users/zby/anaconda3/bin/python3-config
  /Users/zby/anaconda3/bin/curl-config
  /Users/zby/anaconda3/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/librtmp.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python3

**Comment by ilovezfs** [comment]
What's the output of
```
git -C $(brew --repo homebrew/core) status
```

**Comment by 497256303** [comment]
What's the output of
`git -C $(brew --repo homebrew/core) status`

On branch master
Your branch is up to date with 'origin/master'.

You are currently rebasing branch 'master' on '289c0a835'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	added by us:     README.md
	added by us:     tap_migrations.json

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by ilovezfs** [comment]
```
git -C $(brew --repo homebrew/core) rebase --abort
git -C $(brew --repo homebrew/core) reset --hard origin/master
git -C $(brew --repo homebrew/core) status
```

**Comment by 497256303** [comment]
>git -C $(brew --repo homebrew/core) rebase --abort
git -C $(brew --repo homebrew/core) reset --hard origin/master
git -C $(brew --repo homebrew/core) status

`$(brew --repo homebrew/core) rebase --abort`
`$ git -C $(brew --repo homebrew/core) reset --hard origin/master`
HEAD is now at 289c0a835 Remove formulae migrated to homebrew/science.
`$ git -C $(brew --repo homebrew/core) status`
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by ilovezfs** [comment]
```
brew update
git -C $(brew --repo homebrew/core) log -n1 --oneline
```

**Comment by 497256303** [comment]
>brew update
git -C $(brew --repo homebrew/core) log -n1 --oneline

`brew update`
...(The list is too long with no error)
`git -C $(brew --repo homebrew/core) log -n1 --oneline`
a3d5a5d5c0 (HEAD) Readme

**Comment by 497256303** [comment]
>git -C $(brew --repo homebrew/core) status
brew config

`git -C $(brew --repo homebrew/core) status`
rebase in progress; onto 0b6d0848f3
You are currently rebasing branch 'master' on '0b6d0848f3'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    README

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both added:      README.md


`brew config`
HOMEBREW_VERSION: 1.3.8-54-g2b7ecb4
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: 2b7ecb47934018b95b681ee5a49f86286242c838
Last commit: 12 hours ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: a3d5a5d5c02bc4edeba699aebccb51f08a13015a
Core tap last commit: 5 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/zby/anaconda3/bin/python => /Users/zby/anaconda3/bin/python3.6
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 9.0.1, 1.8.0_151
macOS: 10.13.1-x86_64
Xcode: N/A
CLT: 9.1.0.0.1.1508540944
X11: N/A

**Comment by ilovezfs** [comment]
```
cd /usr/local/Homebrew/Library/Taps/homebrew
rm -rf homebrew-core
git clone https://mirrors.ustc.edu.cn/homebrew-core.git
brew config
```

**Comment by 497256303** [comment]
>cd /usr/local/Homebrew/Library/Taps/homebrew
rm -rf homebrew-core
git clone https://mirrors.ustc.edu.cn/homebrew-core.git
brew config

`brew config`
HOMEBREW_VERSION: 1.3.8-54-g2b7ecb4
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: 2b7ecb47934018b95b681ee5a49f86286242c838
Last commit: 12 hours ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: 0b6d0848f360996be94195b8ce9fd25ef0492021
Core tap last commit: 81 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/zby/anaconda3/bin/python => /Users/zby/anaconda3/bin/python3.6
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 9.0.1, 1.8.0_151
macOS: 10.13.1-x86_64
Xcode: N/A
CLT: 9.1.0.0.1.1508540944
X11: N/A

**Comment by ilovezfs** [comment]
```
brew update
git -C $(brew --repo homebrew/core) status
git -C $(brew --repo homebrew/core) rev-parse @
brew install opencv
```

**Comment by 497256303** [comment]
>brew update
git -C $(brew --repo homebrew/core) status
git -C $(brew --repo homebrew/core) rev-parse @
brew install opencv

It really works!
Thank you for your patience and time!
By the way, can you tell me why my brew can't work before?
I remember I never use it to do wrong things, and there isn't any question the same like mine.

**Comment by ilovezfs** [comment]
Your local homebrew/core repository ended up with git rebase conflicts during `brew update`. I'm not sure how that would have happened exactly. It could be your mirror had a force push at some point or something like that.

**Comment by ilovezfs** [comment]
You probably should run `brew upgrade` now too because your brew was very outdated.

**Comment by 497256303** [comment]
>Your local homebrew/core repository ended up with git rebase conflicts during brew update. I'm not sure how that would have happened exactly. It could be your mirror had a force push at some point or something like that.

Oh, maybe. In China, it's slow to connect website outside.
And maybe there's something wrong with the mirror.

>You probably should run brew upgrade now too because your brew was very outdated.

I will try it!
Thanks for helping me!

**Comment by ilovezfs** [comment]
You're welcome!
