### ISSUE TITLE
"Searching for a previously deleted formula" takes 12 seconds, no way to disable

### ISSUE THREAD

**Issue by puddly** [Homebrew/brew#3513]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new

    This has nothing to do with any specific formula, only ones that don't exist.

- [x] Ran `brew update` and retried your prior step?

      $ brew update
      Already up-to-date

- [x] Ran `brew doctor`, fixed all issues and retried your prior step?

      $ brew doctor
      Please note that these warnings are just used to help the Homebrew maintainers
      with debugging if you file an issue. If everything you use Homebrew for is
      working fine: please don't worry and just ignore them. Thanks!

      Warning: "config" scripts exist outside your system or Homebrew directories.
      `./configure` scripts often look for *-config scripts to determine if
      software packages are installed, and what additional flags to use when
      compiling and linking.

      Having additional scripts in your path can confuse software installed via
      Homebrew if the config script overrides a system or Homebrew provided
      script of the same name. We found the following "config" scripts:
        /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config

      Warning: You have unlinked kegs in your Cellar
      Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
      those kegs to fail to run properly once built. Run `brew link` on these:
        youtube-dl

- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

    Above is `brew doctor`. Below is `brew config`:

      HOMEBREW_VERSION: 1.3.8-87-g1b28922
      ORIGIN: https://github.com/Homebrew/brew.git
      HEAD: 1b289226284d87c846825563624661ced315b11a
      Last commit: 4 hours ago
      Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
      Core tap HEAD: 8d3894b5c865c68b6bbaa5932c3d3d6133c5deec
      Core tap last commit: 3 hours ago
      HOMEBREW_PREFIX: /usr/local
      HOMEBREW_DEV_CMD_RUN: 1
      HOMEBREW_ENV_FILTERING: 1
      HOMEBREW_GIT_CONFIG_DEVELOPERMODE: true
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_GITHUB_API: 1
      HOMEBREW_NO_INSECURE_REDIRECT: 1
      CPU: quad-core 64-bit broadwell
      Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
      Clang: 9.0 build 900
      Git: 2.13.6 => /Library/Developer/CommandLineTools/usr/bin/git
      Curl: 7.54.0 => /usr/bin/curl
      Perl: /usr/bin/perl
      Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
      Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_2/bin/ruby
      Java: 1.8.0_40
      macOS: 10.13.1-x86_64
      Xcode: N/A
      CLT: 9.1.0.0.1.1508540944
      X11: 2.7.11 => /opt/X11

To help us debug your issue please explain:
- What you were trying to do (and why)

    I was trying to install a package but got the name wrong.

- What happened (include command output)

      $ time brew install asdoiasoidjasoidj
      Error: No available formula with the name "asdoiasoidjasoidj"
      ==> Searching for a previously deleted formula...
      Error: No previously deleted formula found.
      ==> Searching for similarly named formulae...
      ==> Searching local taps...
      Error: No similarly named formulae found.
      ==> Searching taps...
      Error: No formulae found in taps.
  
      real    0m12.617s
      user    0m6.946s
      sys     0m1.246s

- What you expected to happen

    `brew install asdasdasd` to not take 10 seconds.

- Step-by-step reproduction instructions (by running `brew` commands)

    `brew install asdasdiasjdoi`

# Features

I have never once used this feature and have to <kbd>Ctrl</kbd>-<kbd>c</kbd> every time I make a typo. I propose adding the `HOMEBREW_NO_SEARCH_DELETED` environment variable to allow a user to disable this behavior and let `brew install asdasdiasjdoi` just stop at `Error: No available formula with the name`. I can't imagine on how 90% of Homebrew users will benefit from this, but I would imagine that many people who disable this behavior on Ubuntu will benefit from being able to do the same with Homebrew.

The only "alternative" would be to shallow clone the Homebrew repository, which drops the time to 5 seconds. This is still a really long time.

**Comment by MikeMcQuaid** [comment]
> I have never once used this feature and have to Ctrl-c every time I make a typo.

This is an acceptable workaround.

**Comment by puddly** [comment]
I don't agree with you. `apt install asoidjasoidjaiosd` takes 0.2 seconds to tell me that it's not able to locate the package. `brew install asoidjasoidjaiosd` should not take 12 seconds on a modern computer to do the same thing.

The only change is the inclusion of two lines of code into `Library/Homebrew/cmd/install.rb`. I'm willing to make a pull request with all the necessary documentation changes, but I won't put in the effort if you're rejecting this idea for some other reason.

**Comment by MikeMcQuaid** [comment]
> The only change is the inclusion of two lines of code into Library/Homebrew/cmd/install.rb

While two lines of code seems like not a lot they also need to be documented and maintained. I'll leave this open to see if there's (m)any others with a similar opinion on this but please don't submit a PR for now.

**Comment by puddly** [comment]
Thanks. Searching through the repository history with `git log` is the bottleneck, so I tried a few things to speed it up:

 - Running `git -C "$(brew --repo homebrew/core)" gc` brought my time from 12.617s down to 7.084s.
 - Adding `--diff-filter=D` to the `git log ...` line in `Library/Homebrew/missing_formula.rb` brought my time down to 6.593s.
 - Removing the history of `homebrew/core` by cloning it with `--depth=1` brought my time down to 1.644s.

1.6s is much more manageable than 12.6s, but I do get the following warning:

    Warning: homebrew/core is shallow clone. To get complete history run:
      git -C "$(brew --repo homebrew/core)" fetch --unshallow

If you decide against adding `HOMEBREW_NO_SEARCH_DELETED`, would you at least consider providing a way to silence this warning?

**Comment by MikeMcQuaid** [comment]
> If you decide against adding HOMEBREW_NO_SEARCH_DELETED, would you at least consider providing a way to silence this warning?

Definitely not; the search is pretty pointless if it's a very shallow clone, that's why it's so fast.

> Adding --diff-filter=D to the git log ... line in Library/Homebrew/missing_formula.rb brought my time down to 6.593s.

This is something that could be a good PR candidate.

**Comment by allophilia** [comment]
I'm sorry I think I'm having a similar annoyance by this. Is "Searching for a previously deleted formula" something that should be enabled by default? Couldn't it be a flag? I don't think I've ever used its results. I don't want to bother and annoy, I'm recently getting more into homebrew and would just like to understand why this is the default. If there is a discussion, workaround or something in another place I'm sorry and would appreciate it if you could point me in the right direction. Should I try to understand better the git commands mentioned above as a workaround? Kinda of a newb trying to learn more, sorry for the trouble.
