### ISSUE TITLE
brew update complaining about custom taps

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#352]
I'm pretty sure this is newish.

I have custom taps that aren't git repos.  I was under the impression that this has been supported for some time.  But now I notice that `brew update` yells at me for having a tap that isn't a git repo:
```
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

[some other lines about homebrew/core interleaved here]

Error: Fetching $HOMEBREW_REPOSITORY/Library/Taps/chdiza/homebrew-dizaone failed!
Current branch master is up to date.
fatal: Needed a single revision
invalid upstream origin/master
```

**Comment by UniqMartin** [comment]
> `$HOMEBREW_REPOSITORY/Library/Taps/chdiza/homebrew-dizaone`

Does this path contain a directory named `.git`? If it does, this is assumed to be a Git repository and hence handled by `brew update`. If a `.git` directory doesn't exist, it will definitely be skipped. Particularly the code path that generates the cited error message cannot be triggered in absence of a `.git` directory.

Can you share the output of `ls -AlF` for that tap? Maybe I'll spot something that you overlooked. But really, the tap handling is as simple as I described above and I'd expect to see a `.git` directory.

**Comment by chdiza** [comment]
Good catch.  It does contain a .git folder, but it isn't supposed to.  I must've accidentally symlinked one in.

Sorry for the noise.
