### ISSUE TITLE
brew update asks for github credentials

### ISSUE THREAD

**Issue by arielelkin** [Homebrew/brew#3521]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [ ] Ran `brew update` and retried your prior step? **this issue is about `brew update` behaviour**
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

I'm trying to update Homebrew, but it's asking me for my github credentials, and I wouldn't expect it to ask me for that. Here's all output:

```
$ brew config
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 6 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 918902fd25a44b71bcbfce4baef48028e0261e17
Core tap last commit: 5 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.0.1 => /usr/local/git/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1_2/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 9.1
CLT: 9.1.0.0.1.1508540944
X11: N/A

$ brew doctor
Your system is ready to brew.

$ brew update
Username for 'https://github.com':  ## ??
```

**Comment by MikeMcQuaid** [comment]
What's the output of `ls -lha ~/.gitconfig`?

**Comment by arielelkin** [comment]
```
$ ls -lha ~/.gitconfig
-rw-r--r--  1 Ariel  staff   248B 26 Jun 11:10 /Users/Ariel/.gitconfig
```

**Comment by MikeMcQuaid** [comment]
@arielelkin Try to move it somewhere else and rerun `brew update`.

**Comment by arielelkin** [comment]
@MikeMcQuaid no joy... 

```
$ mv ~/.gitconfig ~/.temp_gitconfig
$ brew update
Username for 'https://github.com': 
```

**Comment by MikeMcQuaid** [comment]
Do you have or require any sort of proxy?

**Comment by arielelkin** [comment]
No. And I'm successfully authenticating to GitHub via SSH otherwise:

```
$ ssh -T git@github.com
Hi arielelkin! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by ilovezfs** [comment]
can you post output of `brew update -dv` in a gist please?

**Comment by arielelkin** [comment]
@ilovezfs here you go:

https://gist.github.com/arielelkin/9cebce329f1995ff5e7e522b3a05f552

**Comment by ilovezfs** [comment]
`brew untap dinkypumpkin/get_iplayer` and try again.

**Comment by arielelkin** [comment]
that worked, thank you very much!

**Comment by ilovezfs** [comment]
You're welcome :)
