### ISSUE TITLE
Cannot 'brew update' without connecting to my work's VPN

### ISSUE THREAD

**Issue by paul-nelson-baker** [Homebrew/brew#3525]
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
  - This is the step I'm having a problem with
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  - Attempted to run `brew update`
- What happened (include command output)
   - ``` ssh: Could not resolve hostname git.wgu.edu: nodename nor servname provided, or not known fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.```
   - git.wgu.edu is where my work has it's bitbucket instance located
- What you expected to happen
  - A regular update to the brew command should occur
- Step-by-step reproduction instructions (by running `brew` commands)
  - I am unsure exactly what happened. I could not update homebrew until I connected to my work's VPN. My shell was just in my home directory, and not in a project that had a remote repository that was inaccessible. I can't tell if this is a git configuration issue or something to do with homebrew. (I contributed to a cask recipe a few months prior. Before that I never had any issue, but since then I've had intermittent errors _similar_ to this. This problem, unlike others, didn't resolve itself or print out a git command to fix the error.)
   - Disconnecting from the VPN thereafter a successful `brew update` prints out the following: 
```ssh: Could not resolve hostname git.wgu.edu: nodename nor servname provided, or not known fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: unable to access 'https://github.com/Homebrew/brew/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/Homebrew/homebrew-boneyard/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/caskroom/homebrew-versions/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/Homebrew/homebrew-completions/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/Homebrew/homebrew-science/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/Homebrew/homebrew-services/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/jkawamoto/homebrew-fgo/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/tcnksm/homebrew-ghr/': Could not resolve host: github.com
Error: Fetching /usr/local/Homebrew/Library/Taps/auto/homebrew-saucelabs failed!
Fetching /usr/local/Homebrew failed!
Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard failed!
Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-completions failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services failed!
Fetching /usr/local/Homebrew/Library/Taps/jkawamoto/homebrew-fgo failed!
Fetching /usr/local/Homebrew/Library/Taps/tcnksm/homebrew-ghr failed!
```

### brew config
```
paul.baker@Paul-Baker-Dragon-Slayer
HOMEBREW_VERSION: 1.3.8-107-g0ad42eb
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0ad42ebbcb735422612a7c6d4edc5ad88044dd4b
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 053f0572e6f5f72ba486fe0d714b10108b556d5c
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_ENV_FILTERING: 1
HOMEBREW_GIT_CONFIG_DEVELOPERMODE: true
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.6 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 9.0.1, 1.8.0_152
macOS: 10.12.6-x86_64
Xcode: 9.1
CLT: 9.1.0.0.1.1508540944
X11: 2.7.11 => /opt/X11
```

### brew doctor
```
paul.baker@Paul-Baker-Dragon-Slayer
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /usr/local/anaconda3/bin/curl-config
  /usr/local/anaconda3/bin/freetype-config
  /usr/local/anaconda3/bin/icu-config
  /usr/local/anaconda3/bin/libpng-config
  /usr/local/anaconda3/bin/libpng16-config
  /usr/local/anaconda3/bin/ncursesw6-config
  /usr/local/anaconda3/bin/pcre-config
  /usr/local/anaconda3/bin/python3-config
  /usr/local/anaconda3/bin/python3.6-config
  /usr/local/anaconda3/bin/python3.6m-config
  /usr/local/anaconda3/bin/xml2-config
  /usr/local/anaconda3/bin/xslt-config
```

**Comment by MikeMcQuaid** [comment]
> fatal: unable to access 'https://github.com/Homebrew/brew/': Could not resolve host: github.com

I'm afraid this error is something on your local machine and not a bug with Homebrew so we're not able to help you here.

**Comment by paul-nelson-baker** [comment]
In case this comes up in someone's google search down the line, the issue was indeed a configuration.

I had created [a custom tap](https://github.com/Homebrew/homebrew-core/pull/19572) that was hosted on our internal git instance. Not being able to connect to that instance from outside the VPN caused the application to fail.

**Comment by TimoJohannes** [comment]
@paul-nelson-baker did you ever find a solution for this problem? I can´t figure out whats wrong with my local config, and I´m getting the same error.
