### ISSUE TITLE
bump-formula-pr fails with an error "You need to configure hub"

### ISSUE THREAD

**Issue by laurent22** [Homebrew/brew#3531]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew doctor && brew config
Your system is ready to brew.
HOMEBREW_VERSION: 1.3.9-8-g497348a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 497348a8b7413e48cf78cf9bf4d7904db627c9ee
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a775893d328b4719eb049bcd6809b35132adcf43
Core tap last commit: 82 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_ENV_FILTERING: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GIT_CONFIG_DEVELOPERMODE: true
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_VISUAL: vim
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.6 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: N/A
macOS: 10.13.1-x86_64
Xcode: 9.1
CLT: 9.1.0.0.1.1508540944
X11: N/A
```

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to update a formula using the command mentioned [here](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

- What happened (include command output)

```
$ brew bump-formula-pr --strict joplin --url=https://registry.npmjs.org/joplin/-/joplin-0.10.78.tgz --sha256=b0dad8f2a918cf7fec6182426eb8c02fb8aa5b7a7e9e83375afea3263079e4
c4
Already up-to-date.
==> replace "https://registry.npmjs.org/joplin/-/joplin-0.10.65.tgz" with "https://registry.npmjs.org/joplin/-/joplin-0.10.78.tgz"
==> replace "52dcd067e670ede25a74d06a10223a9d7e134e56606219621a21dc3915127f8c" with "b0dad8f2a918cf7fec6182426eb8c02fb8aa5b7a7e9e83375afea3263079e4c4"
Error: You need to configure hub
```

- What you expected to happen

The error says `You need to configure hub` but it doesn't say exactly what config is missing. I've tried setting the user name and email but that didn't help.

So it would be helpful if this error message could say what config is required by `bump-formula-pr`.

**Comment by amyspark** [comment]
https://github.com/Homebrew/brew/blob/9e93720e8fddcf3e2184af966a9471b3f0d906be/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L332-L342

`hub` is asking (in the background) for your GitHub username/password.

**Comment by DomT4** [comment]
Running something like `cd $(brew --repo) && hub issue` should be enough for it to walk you through anything it's missing in terms of access, I'd imagine.

**Comment by laurent22** [comment]
Thank you, running `cd $(brew --repo) && hub issue` asked me for my credentials, which fixed the issue.

Would it make sense to update the error message with this information?

Instead of the current error message it could be:

> Please authentify with "hub" (eg. type `cd $(brew --repo) && hub issue`) and try again.

**Comment by MikeMcQuaid** [comment]
The error message is generated by `hub` not by `brew bump-formula-pr`, FYI.

**Comment by amyspark** [comment]
@MikeMcQuaid, `You need to configure hub` is generated by Homebrew. `hub` generates is the `Username:` bit:
https://github.com/Homebrew/brew/blob/9e93720e8fddcf3e2184af966a9471b3f0d906be/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L339-L342

**Comment by ilovezfs** [comment]
Before I added that, in its original implementation bump-formula-pr sat there stuck doing nothing and printing no messages. Homebrew doesn't have interactive commands, so printing an error message seemed preferable to just hanging or becoming interactive, let alone asking people to peck in their GitHub credentials at an interactive prompt.

I'd be in favor of a PR improving the messaging here but don't think we should be handling this interactively.

**Comment by alyssais** [comment]
Is there anything more to do on this after #3551 and #3553 or are we good to close this?

**Comment by MikeMcQuaid** [comment]
Assuming nothing else here, thanks all!
