### ISSUE TITLE
"Xcode alone is not sufficient on Sierra" (again)

### ISSUE THREAD

**Issue by zenspider** [Homebrew/brew#3540]
These steps don't always apply...

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [no] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

`brew install <anything>`

- What happened (include command output)

I can't include command output. Sometimes you file the issue after you've fixed your problem.

Copied from: https://github.com/Homebrew/brew/pull/3453#issuecomment-350098129

The error message for this patch is terribly confusing and diverts people from the actual problem/solution.

> brew: “Xcode alone is not sufficient on Sierra”

versus:

> xcode-select: “command line tools are already installed”

There needs to be a proper distinction between "Xcode alone" vs "you don't have the latest SDK"... 

Also, why do I need the latest SDK if I'm building for my current OS revision? Especially considering the SDK version doesn't determine build-ability? 99+% of the ports don't even touch the SDK, do they?

- What you expected to happen

The thing to install, even tho my CLT doesn't include 10.13 (since I'm on 10.12 AND I'm trying to install something that doesn't even remotely touch the SDK (like `heroku`, which uses `node`).

- Step-by-step reproduction instructions (by running `brew` commands)

1. Be on OSX < latest
2. Have Xcode + CLT installed and up to date for that version of OSX.
3. `brew update`
4. `brew install heroku` (or whatever)
5. `sudo xcode-select --install`
6. Get confused that 5 says that it is already installed.
7. Update Xcode
8. Get confused that there is STILL no update to CLT and 4 keeps erroring out.

I wound up having to `sudo rm -rf /Library/Developer/CommandLineTools` and re-running 5. A newer version does not show up in software update. Presumably because `softwareupdate` knows its up to date for my OS version?

**Comment by ilovezfs** [comment]
Please don't file issues about problems you've already solved.

**Comment by zenspider** [comment]
This problem isn't solved. The error message is wrong and deceiving. I had to dig into the code to figure it out that it was lying about the problem. Please reopen.

**Comment by zenspider** [comment]
Besides, I'm not the only one with this issue. Why shouldn't I file an issue? It helps everyone.

**Comment by MikeMcQuaid** [comment]
@zenspider Your [conduct](https://github.com/Homebrew/brew/blob/master/CODE_OF_CONDUCT.md) on our issue tracker is not acceptable. You are being insulting to multiple maintainers and I debated whether to just block you on the Homebrew organisation to stop you submitting future comments or issues. You are clearly frustrated but it's not acceptable to take out that frustration on us.

**Comment by kballard** [comment]
Please reopen this issue. zenspider's complaint is legitimate and I do not even begin to understand the treatment they're receiving. I see nothing rude or insulting about zenspider's ticket or subsequent response. This ticket was closed inappropriately; zenspider did not solve the issue they were complaining about, they merely fixed their local installation so they don't see the error anymore.
