### ISSUE TITLE
Apple XCode random updates should not break existing processes

### ISSUE THREAD

**Issue by sleekweasel** [Homebrew/brew#3541]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [ moot ] Ran `brew doctor`, fixed all issues and retried your prior step?

This is a moot step: it's precisely the xcode status check I'm questioning.

- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to install fbsimctl 0.4.0 because that's the version we're using.

- What happened (include command output)

It complained that XCode 9.0 is out of date. But it was perfectly happy building fbsimctl 0.4.0 with 9.0 before Apple released 9.1

- What you expected to happen

There would be some option to ignore the XCode version check, because we don't want our machine building/deployment process broken by Apple releasing something we're not yet using.

- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature

An option to pretend that Apple haven't released a new XCode: If a particular install needs XCode 9.1, then fine, but if it worked under 9.0, it should continue working under 9.0.

- the motivation for the feature

Not breaking existing processes.

- how the feature would be relevant to at least 90% of Homebrew users

Not everyone wants to update XCode simply because Apple have released something?

- what alternatives to the feature you have considered

Going through the hassle and possible breakage involved in installing a new version of XCode.

**Comment by sleekweasel** [comment]
Our internal documents weren't up to date with each other. But it's still probably worth considering.

**Comment by MikeMcQuaid** [comment]
> Ran brew config and brew doctor and included their output with your issue?
> This is a moot step: it's precisely the xcode status check I'm questioning.

You didn't do this. Please do this in future. It's not moot for us; that's why we ask for it.

> There would be some option to ignore the XCode version check, because we don't want our machine building/deployment process broken by Apple releasing something we're not yet using.

The Xcode version check is a warning not an error. We cannot support multiple versions of Xcode on each macOS version as we do not have the CI or maintainer resources to do so.
