### ISSUE TITLE
brew doctor warning concerning CLT

### ISSUE THREAD

**Issue by miccal** [Homebrew/brew#3555]
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

Output of `brew config`:
```
-bash-4.4.12- /Users/miccal (33) [> brew config
HOMEBREW_VERSION: 1.3.9-54-g236e884
ORIGIN: https://github.com/Homebrew/brew
HEAD: 236e884511495f466c766b2913cde66099a26e1c
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 136fccadb53a5c812d53e7b4e0ac21de8eedc6b6
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEVELOPER: 1
HOMEBREW_FORCE_BREWED_CURL: 1
HOMEBREW_GIT: /usr/local/opt/git/bin/git
HOMEBREW_NO_ANALYTICS: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.1 => /usr/local/opt/git/bin/git
Curl: 7.57.0 => /usr/local/opt/curl/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.13.2-x86_64
Xcode: N/A
CLT: 9.1.0.0.1.1508540944
X11: 2.7.11 => /opt/X11
```

Output of `brew doctor`:
```
-bash-4.4.12- /Users/miccal (33) [> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```

To help us debug your issue please explain:
- What you were trying to do (and why)

I was reviewing the output of `brew doctor` after performing a clean install, and notice that `brew doctor` is reporting that my Command Line Tools are outdated, however:
```
-bash-4.4.12- /Users/miccal (33) [> softwareupdate --list
Software Update Tool

Finding available software
No new software available.
```

I understand that this is just a warning and not necessarily something to worry over, but I have not experienced this warning before and was concerned that there may be an issue with my clean install.

Thanks.

**Comment by MikeMcQuaid** [comment]
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!

> I understand that this is just a warning and not necessarily something to worry over

Closing.

**Comment by ilovezfs** [comment]
I believe this is an Apple bug. The 9.2 CLT upgrade has not been showing up consistently. I had to manually install it from https://developer.apple.com/download/more/ on the Jenkins boxes when upgrading the base image even though previously it had shown up as an upgrade. I assume this situation will take care of itself eventually.

**Comment by ilovezfs** [comment]
The same 9.2-CLT-upgrade-doesn't-show-up behavior was noted here https://github.com/Homebrew/brew/issues/3466 as well.

**Comment by miccal** [comment]
Thank you for the information @ilovezfs, as always you are most helpful.

**Comment by MikeMcQuaid** [comment]
@miccal I guess I just don't really understand why you can't just ignore this message. Is it displayed anywhere except running `brew doctor`?

**Comment by scpeters** [comment]
My apologies for opening #3562 without reading all my unread email. Any `brew doctor` complaints cause my `brew test-bot` bottle builds to fail, which is why I was wanting that to be fixed.

**Comment by scpeters** [comment]
I'll try downloading from https://developer.apple.com/download/more/

**Comment by scpeters** [comment]
I suppose I can also use `brew test-bot --skip-setup` to avoid the `brew doctor` checks

**Comment by miccal** [comment]
@MikeMcQuaid as I said, I had just performed a clean install and the first time I ran `brew doctor` after installing everything via `brew bundle` I received this warning, which in all the years of using and contributing to `brew` and `brew cask` I have never seen before. I was concerned that something had gone wrong with my clean install, and therefore just wanted to clarify the problem, which @ilovezfs kindly did. 

Obviously you dislike people asking questions by filing issues, so where would you prefer users to ask questions?

**Comment by MikeMcQuaid** [comment]
@miccal Makes sense, thanks for elaborating and apologies for getting unnecessarily irritated by this. Thanks again for all your contributions over the years to Homebrew and Homebrew Cask ❤️ 

https://discourse.brew.sh is a better fit for questions/discussion.

To be fair the `brew doctor` messaging doesn't tell you explicitly to not file an issue about it but I've edited it to do so now.

Thanks again!

**Comment by DomT4** [comment]
> I assume this situation will take care of itself eventually.

It trickled through to me yesterday, FWIW. This has happened a bit lately, and not just with CLT updates. Unsure if Apple has further slowed the rollout of various things to avoid having their infrastructure rammed, but that seems semi-plausible at least.
