### ISSUE TITLE
brew doctor should run git fsck

### ISSUE THREAD

**Issue by easyaspi314** [Homebrew/brew#3558]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
<p><details>

```
~/H/L/Homebrew ❯❯❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libjack.0.1.0.dylib
  /usr/local/lib/libjacknet.0.1.0.dylib
  /usr/local/lib/libjackserver.0.1.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/jack/control.h
  /usr/local/include/jack/intclient.h
  /usr/local/include/jack/jack.h
  /usr/local/include/jack/jslist.h
  /usr/local/include/jack/metadata.h
  /usr/local/include/jack/midiport.h
  /usr/local/include/jack/net.h
  /usr/local/include/jack/ringbuffer.h
  /usr/local/include/jack/session.h
  /usr/local/include/jack/statistics.h
  /usr/local/include/jack/systemdeps.h
  /usr/local/include/jack/thread.h
  /usr/local/include/jack/transport.h
  /usr/local/include/jack/types.h
  /usr/local/include/jack/uuid.h
  /usr/local/include/jack/weakjack.h
  /usr/local/include/jack/weakmacros.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/jack.pc

Warning: You have uncommitted modifications to Homebrew
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /Users/easyaspi/Homebrew/Library && git stash && git clean -d -f

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

Warning: Your XQuartz (2.7.9) is outdated.
Please install XQuartz 2.7.11 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz
~/H/L/Homebrew ❯❯❯ brew config
HOMEBREW_VERSION: 1.3.9-54-g236e884
ORIGIN: https://github.com/Homebrew/brew
HEAD: 236e884511495f466c766b2913cde66099a26e1c
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aa288f2fed35434445392353c66fe573355fd1e0
Core tap last commit: 77 minutes ago
HOMEBREW_PREFIX: /Users/easyaspi/Homebrew
HOMEBREW_REPOSITORY: /Users/easyaspi/Homebrew
HOMEBREW_CELLAR: /Users/easyaspi/Homebrew/Cellar
HOMEBREW_CELLAR: /Users/easyaspi/Homebrew/Cellar
HOMEBREW_DEVELOPER: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_PREFIX: /Users/easyaspi/Homebrew
HOMEBREW_REPOSITORY: /Users/easyaspi/Homebrew
HOMEBREW_VISUAL: nano
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.3.3 => /Users/easyaspi/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.15.0 => /Users/easyaspi/Homebrew/bin/git
Curl: 7.43.0 => /usr/bin/curl
Perl: /Users/easyaspi/Homebrew/bin/perl => /Users/easyaspi/Homebrew/Cellar/perl/5.26.1/bin/perl
Python: /Users/easyaspi/Homebrew/opt/python/libexec/bin/python => /Users/easyaspi/Homebrew/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/easyaspi/Homebrew/bin/ruby => /Users/easyaspi/Homebrew/Cellar/ruby/2.4.2_1/bin/ruby
Java: 9, 1.8.0_152, 1.8.0_131, 1.8.0_25
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
~/H/L/Homebrew ❯❯❯ 
```
</details></p>

```c
/* 
 * To help us debug your issue please explain:
 * - What you were trying to do (and why)
 * - What happened (include command output)
 * - What you expected to happen
 * - Step-by-step reproduction instructions (by running `brew` commands)
 */
```
# Features

For a while, I had to put up with a really slow brew. `git describe` was taking forever, hence why I opened #3339

I eventually found online that a source of that issue might be a corrupt git repo, and that I should run `git fsck`. Low and behold, my git repo was indeed corrupt. After fixing it, `git describe` (and, as a result, almost all `brew` commands) were **a lot** faster.

The way I found to fix this is to run the following:
```
rm -rf <brew prefix>/.git
brew update
```

I don't *think* it would be too much work to implement, and I think that a corrupt git repo is a relatively-hard-to-find, easy-to-fix issue.

It appears that `git fsck` returns 128 when there is an issue.  

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
> Ran brew config and brew doctor and included their output with your issue? – posted in #3557

Please repost these in every issue.

> (which I still think is a good idea anyways but whatever).

Please don't post stuff like this striked out. It may have been intended as being amusing but it comes across as snarky.

> I eventually found online that a source of that issue might be a corrupt git repo, and that I should run git fsck.
> It appears that git fsck returns 128 when there is an issue.

How long does it take `git fsck` to find an issue? Does it make any modifications to the git repository?

**Comment by easyaspi314** [comment]
> Please don't post stuff like this striked out. It may have been intended as being amusing but it comes across as snarky.

Sorry about that. 

> How long does it take git fsck to find an issue? Does it make any modifications to the git repository?

It *can* take a while, directly related to how many commits are in your local repo, but it doesn't change anything. 

On a small commit tree, it takes less than a second.
However, since `brew doctor` isn't really intended to be a fast command, it wouldn't cause a huge issue. 

It might be a good idea to start it on a separate thread and have it run while the other tests are running .If there is a way to stop immediately after finding an error, that would also make things better, because if there is already one thing wrong, you don't need to know if there are other things wrong.

**Comment by MikeMcQuaid** [comment]
> Sorry about that.

That's ok, appreciate the apology.

> On a small commit tree, it takes less than a second.

How long does it take for e.g. Homebrew/brew and Homebrew/homebrew-core on your machine?

**Comment by chdiza** [comment]
Here, core takes about 3-5 seconds.  Brew takes 5-7.  Too long to force into doctor IMHO.

**Comment by MikeMcQuaid** [comment]
I agree; `brew doctor` is run regularly in CI so I don't think we can run `git fsck` every time. I'm open to an approach that takes <1s for both repos, though.

**Comment by scpeters** [comment]
FWIW `git fsck --no-full` is less than 0.1 seconds on my machine for both core and brew

I don't know if it's a useful subset of the default `git fsck` command

**Comment by MikeMcQuaid** [comment]
Any ideas if that catches anything @easyaspi314?
