### ISSUE TITLE
brew update --force fails because /usr/local/bin is not in path

### ISSUE THREAD

**Issue by drewwells** [Homebrew/brew#3561]
I use corkscrew (installed via brew) to proxy ssh connections through our corporate proxy. Since 1.4.0 is changing my $PATH, it can not find /usr/local/bin/corkscrew. If I can provide a path or know which alternate one is used for brew commands, then I can symlink corkscrew there to fix this issue.

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
install brew 1.4.0, brew update failed so ran it again manually
- What happened (include command output)
```
-> % brew update --force
zsh:1: command not found: corkscrew
zsh:1: command not found: corkscrew
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.
```
- What you expected to happen
ssh to run through corkscrew for corporate proxy
- Step-by-step reproduction instructions (by running `brew` commands)
1. brew update --force

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

```
-> % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/current_time.h
  /usr/local/include/endian.h
  /usr/local/include/mach_gettime.h

Warning: Your Xcode (9.1) is outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.

-> % brew config
HOMEBREW_VERSION: 1.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: f42d8acde3907b90ea32cef01445744288984a4c
Last commit: 65 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 99ad884915ba1f67286270f7a6179a1521181925
Core tap last commit: 2 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AWS_ACCESS_KEY_ID: set
HOMEBREW_AWS_SECRET_ACCESS_KEY: set
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.6 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_91, 1.8.0_25, 1.7.0_80
macOS: 10.13.1-x86_64
Xcode: 9.1
CLT: N/A
X11: N/A
```

**Comment by MikeMcQuaid** [comment]
> ssh_exchange_identification: Connection closed by remote host

Which Homebrew tap is causing this issue? Homebrew/brew and Homebrew/homebrew-core should be using HTTPS.

> I use corkscrew (installed via brew) to proxy ssh connections through our corporate proxy. Since 1.4.0 is changing my $PATH, it can not find /usr/local/bin/corkscrew. If I can provide a path or know which alternate one is used for brew commands, then I can symlink corkscrew there to fix this issue.

How is `corkscrew` being configured to be executed; through a `.gitconfig`? It's worth noting this is not a supported configuration so this may not be something we're willing to fix. I'll see, though.

**Comment by drewwells** [comment]
https would work, I'm using git+ssh. Yes corkscrew is in `.gitconfig`

**Comment by MikeMcQuaid** [comment]
Cool, good to know, thanks. I'm going to try and work on something to bypass user `~/.gitconfig`s, I think; that we use Git for our network transport is an implementation detail and there's been too many users with weird bugs related to their local Git configuration.
