### ISSUE TITLE
Single payment donation option

### ISSUE THREAD

**Issue by p1g30n** [Homebrew/brew#3565]
I love Homebrew but not Patreon very much (and assume I'm not alone in that), is there any chance to have an option for single payment donations added?

**Comment by MikeMcQuaid** [comment]
Closing but let's keep discussing here. What would you suggest?

**Comment by p1g30n** [comment]
Most donation pages I know offer PayPal, Bitcoin and VISA. PayPal isn't great either but widespread and also allows for recurring donations, not sure it Bitcoin makes sense at this point but maybe long term and should be easy to set up, VISA might need a payment processor but I think PayPal also offers that.

**Comment by MikeMcQuaid** [comment]
I've remembered we do have options for this but I removed them because I thought no-one was using them. Will reopen this to add them back.

**Comment by MikeMcQuaid** [comment]
Thanks for the nudge, @p1g30n, have opened https://github.com/Homebrew/brew/pull/3568 to resolve this.
