### ISSUE TITLE
Link to Homebrew on Patreon Site

### ISSUE THREAD

**Issue by jphastings** [Homebrew/brew#3567]
Hey folks, could you include a link to [the donations section of the README](https://github.com/Homebrew/brew#donations) on [your Patreon page](https://www.patreon.com/homebrew) so that Patreon has some immediate proof that it is a legitimate way to support you?

Thanks for your hard work! 🍻

**Comment by vitorgalvao** [comment]
> so that Patreon has some immediate proof

If a malicious third-party had set up a fake Patreon page to get money o behalf of Homebrew, couldn’t they just as well post a link to the repo? Or does Patreon require you integrate it with the repo itself to display a link?

**Comment by MikeMcQuaid** [comment]
@jphastings Any thoughts on that? Trying to understand the use-case more and what/where you think we should do.

**Comment by MikeMcQuaid** [comment]
Done.

**Comment by jphastings** [comment]
Sorry @MikeMcQuaid, I missed your replies (good old Winter cold got me) — As you already have a link to the Patreon site [here](https://github.com/Homebrew/brew#donations) it would mean that there's a two-way link I could (have) checked: "the Patreon links to the official page I know and love, the official page links back to where I came from".

Weirdly, the images and other content you've added to your Patreon page makes it seem less fishy too :) Thanks!
