### ISSUE TITLE
/usr/local/Homebrew/Library/Taps/homebrew .git  too large

### ISSUE THREAD

**Issue by bunnyblue** [Homebrew/brew#3571]
![df58dc84-255a-41cc-8687-f90c1d668c23](https://user-images.githubusercontent.com/1221755/33923346-a357b372-e00b-11e7-893d-cdd4801633d1.png)

this foloder too large,can you help me？

**Comment by scpeters** [comment]
It should only be about 158 MB (see `size` field in https://api.github.com/repos/homebrew/homebrew-core ).

**Comment by bunnyblue** [comment]
i don't know what happened, i drop this  folder  and clone git again

**Comment by MikeMcQuaid** [comment]
@bunnyblue Please fill out the issue template for all future issues.

**Comment by chdiza** [comment]
That 158MB gets down to less than half that after a `git gc --aggressive`.  I don't know why github's "copy" isn't garbage collected once in a while.

**Comment by MikeMcQuaid** [comment]
@chdiza iirc it should be every ~30 days.
