### ISSUE TITLE
https://gitlab.sd.apple.com outage causing my brew update issue?

### ISSUE THREAD

**Issue by asadakbar** [Homebrew/brew#3574]
- X Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- X Ran `brew update` and retried your prior step?
- X Ran `brew doctor`, fixed all issues and retried your prior step?
- X Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I am trying to install Homebrew on a new MacBook and hit an error. I am unable to finalize the install of Hombrew due to an error when I run `brew update`.

- What happened (include command output)
I dont recall the exact message when the initial homebrew install happened but here is the message when I run `brew update`
````
jtPro:local asad_a$ brew update
ssh: Could not resolve hostname gitlab.sd.apple.com: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/orchard/homebrew-cider failed!
````
I am able to install packages though

````
jtPro:local asad_a$ brew install rbenv
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Installing dependencies for rbenv: ruby-build
==> Installing rbenv dependency: ruby-build
==> Downloading https://github.com/rbenv/ruby-build/archive/v20170914.tar.gz
==> Downloading from https://codeload.github.com/rbenv/ruby-build/tar.gz/v20170914
######################################################################## 100.0%
==> ./install.sh
🍺  /usr/local/Cellar/ruby-build/20170914: 363 files, 187.9KB, built in 9 seconds
==> Installing rbenv
==> Downloading https://homebrew.bintray.com/bottles/rbenv-1.1.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring rbenv-1.1.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/rbenv/1.1.1: 36 files, 62.9KB
````

- What you expected to happen
I expected homebrew to be updated. I dug into homebrew-ceder and saw in the orchard-cli.rb file line 4 referencing `REPO = "gitlab.sd.apple.com/orchard/cli.git"` which is referenced in the `install` method definition. I looked up this page and it seems to not be live [http://www.websitedown.info/gitlab.sd.apple.com](http://www.websitedown.info/gitlab.sd.apple.com). I wondered if I was barking up the wrong tree but it seems that the url is a legitimate url that homebrew relies on and is referenced by others on the web [https://twitter.com/John011235/status/907320504561934336](https://twitter.com/John011235/status/907320504561934336). It is also referenced on line 78 of the second gist here [https://gist.github.com/zhuowei/f335588e1a10e39fd722](https://gist.github.com/zhuowei/f335588e1a10e39fd722)

- Step-by-step reproduction instructions (by running `brew` commands)

`brew config`
````
jtPro:local asad_a$ brew config
HOMEBREW_VERSION: 1.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: f42d8acde3907b90ea32cef01445744288984a4c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 153bc294782b7ffa4085b77ee3f36f73e2da7ef2
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
````

`brew doctor`
````
jtPro:local asad_a$ brew doctor
Your system is ready to brew.
````

I first ran `brew install`. Then `brew update` which resulted in 
````
jtPro:local asad_a$ brew update
ssh: Could not resolve hostname gitlab.sd.apple.com: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/orchard/homebrew-cider failed!
````

**Comment by MikeMcQuaid** [comment]
> ssh: Could not resolve hostname gitlab.sd.apple.com: nodename nor servname provided, or not known

You should `brew untap orchard/homebrew-cider` as, yeh, that URL seems to no longer be around.
