### ISSUE TITLE
Want to Contribute Core

### ISSUE THREAD

**Issue by hasahmed** [Homebrew/brew#3580]
_Sorry in advance if this isn't the right place for this type of request._

I would like to contribute to Homebrew (not a formula, but to the core it's self) I was thinking of trying to tackle this issue #1860. I have a few questions about some of the things that I've seen in the source code, and I was wondering if these was someone I could talk to answer a few of my questions.

**Comment by MikeMcQuaid** [comment]
@hasahmed Sure thing; ask any questions in that or this issue.
