### ISSUE TITLE
"brew leaves" shows non-leaves

### ISSUE THREAD

**Issue by barreyra** [Homebrew/brew#3585]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Run "brew leaves" to check if I have any software I don't need.

- What happened (include command output)

```
$ brew config
HOMEBREW_VERSION: 1.4.1-3-g426c998
ORIGIN: https://github.com/Homebrew/brew
HEAD: 426c998ff513a182aced1a5a4c4b7ec6f9203288
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5df267c74f2b7d10602a7783e57cce0db4d822db
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.3_1/bin/ruby
Java: 1.8.0_121
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  groff
  xerces-c

$ brew leaves
ant
automake
bash-completion
bison
boost
clang-format
cmake
ctags
dos2unix
doxygen
emacs
exa
ffmpeg
flac
flex
gcovr
ghostscript
global
gnupg
go
graphviz
groff
guile
heirloom-doctools
intltool
json-glib
makedepend
megacmd
mercurial
mit-scheme
mutt
nasm
neovim
netpbm
ninja
nmap
pidgin
plan9port
plowshare
protobuf-c
psutils
pv
python3
ripgrep
rust
shared-mime-info
shorten
socat
sphinx-doc
stdman
swig
texi2html
vim
wine
winetricks
xerces-c
youtube-dl
zlib
$ brew uninstall netpbm
Error: Refusing to uninstall /usr/local/Cellar/netpbm/10.73.17
because it is required by groff 1.22.3, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies netpbm
```

- What you expected to happen

The leaves list should be much smaller, as its showing stuff that is a dependency to other items.

- Step-by-step reproduction instructions (by running `brew` commands)

See above.

**Comment by ilovezfs** [comment]
`leaves` doesn't consider the specific options you used when installing, whereas `uninstall` does.

**Comment by barreyra** [comment]
That makes sense. Seems to me that it's something that could be fixed, or not?

**Comment by ilovezfs** [comment]
Yes it's something that could be changed with a PR if you're willing to work on it but not something any of the maintainers are planning on working on at this point.

**Comment by barreyra** [comment]
Fair enough. I might eventually take a stab at it. Should we leave this open as a known issue?

**Comment by ilovezfs** [comment]
We close issues that no one is actively working on but feel free to keep talking here.
