### ISSUE TITLE
Cant link lftp

### ISSUE THREAD

**Issue by eskwire** [Homebrew/brew#3595]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

$ brew doctor && brew config
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/liblftp-jobs.la
  /usr/local/lib/liblftp-tasks.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/liblftp-jobs.a
  /usr/local/lib/liblftp-tasks.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  lftp

To help us debug your issue please explain:

- What you were trying to do (and why)

Try to connect to LFTP server and get this message: lftp sftp://samuel@armandosierra.nu 
-bash: lftp: command not found

The i try to install it and get the message:
brew install lftp
Warning: lftp 4.8.3 is already installed, it's just not linked.
You can use `brew link lftp` to link this version. try link and it dont work.

- What happened (include command output)

-bash: lftp: command not found

- What you expected to happen

connect to server and vuala download files.
- Step-by-step reproduction instructions (by running `brew` commands)

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information (`brew config` output and evidence you've tried to remove the existing `lftp` files) this issue may be reopened.
