### ISSUE TITLE
Xcode included CLT is not detected on macOS 10.9.5 with Xcode 6.2

### ISSUE THREAD

**Issue by alasf** [Homebrew/brew#3597]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

config:
```
HOMEBREW_VERSION: 1.4.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: b4d43e950fd45c24e48d6ebfd3013357abcd21a9
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c08c42ee603b8cc8c903d21cba30abfa950e6b3f
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 6.0 build 600
Git: 1.9.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.30.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.9.5-x86_64
Xcode: 6.2
CLT: N/A
X11: N/A
```
doctor:
```
Warning: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Xcode alone is not sufficient on Mavericks.
Install the Command Line Tools:
  xcode-select --install
```

I did a clean install of macOS 10.9.5 and installed Xcode 6.2, which includes CLT in the path `/Applications/Xcode.app/Contents/Developer`. Homebrew fails to detect the included CLT and requests that I do `xcode-select --install`. Installing CLT explicitly in this manner does make Homebrew detect CLT. However, the correct behavior, as explained in Homebrew documentation, is that it should be unnecessary to install CLT again when the Xcode installation already includes it.

My previous clean install in August with the exact same setup did not run into this issue.

**Comment by MikeMcQuaid** [comment]
> which includes CLT in the path /Applications/Xcode.app/Contents/Developer

This is not the CLT. You need to run `xcode-select --install`.

> My previous clean install in August with the exact same setup did not run into this issue.

This is an intentional change made after August.

**Comment by alyssais** [comment]
> Warning: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

**Comment by alasf** [comment]
Thanks for the reply and sorry for commenting again, but I have a quick question. After installing CLT as recommended, does it matter if I set the path via `xcode-select -s` to `/Library/Developer/CommandLineTools`? The default points to the folder inside Xcode installation, and homebrew seems to work correctly even when I do not modify the default path.

**Comment by alasf** [comment]
Also, is doing `brew update` sufficient after installing CLT or should I reinstall brew to make sure?

**Comment by MikeMcQuaid** [comment]
`brew update` is fine. Yep, don't need to modify the path.
