### ISSUE TITLE
when brew intall nginx

### ISSUE THREAD

**Issue by pukaicom** [Homebrew/brew#3598]
PuKaideMacBook-Pro:~ pukai$ brew install nginx
Updating Homebrew...
==> Installing dependencies for nginx: openssl, pcre
==> Installing nginx dependency: openssl
git: error: unable to find utility "git", not a developer tool or in PATH
Error: Failure while executing: git config --local --replace-all homebrew.private true
PuKaideMacBook-Pro:~ pukai$ git --version
git version 2.14.1
PuKaideMacBook-Pro:~ pukai$

**Comment by alyssais** [comment]
> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Please fill out the [issue template](https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE.md) and your issue might be reopened.
