### ISSUE TITLE
Allow us to ignore /Applications/Xcode.app

### ISSUE THREAD

**Issue by envygeeks** [Homebrew/brew#3599]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

##  Features

In order to avoid a bug with Spotlight on MacOS that has existed for a very long time, you need to add an empty `/Application/Xcode.app` when using the Xcode non-GUI stuff in terminal -- this way you get access to the Spotlight option to disable "Developer" stuff when searching for apps.  This will result in `brew` complaining that about it, when there is Xcode readily available elsewhere.

It would be great if we `brew` didn't complain when there is Xcode CLI available.

**Comment by alyssais** [comment]
Where do you have Xcode installed? What does `xcode-select -p` output?

**Comment by MikeMcQuaid** [comment]
From the issue template:

> [ ] Ran brew config and brew doctor and included their output with your issue?

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by envygeeks** [comment]
You should really update your ticket template so your arbitrary closures make sense.  Best to ya.

**Comment by MikeMcQuaid** [comment]
@envygeeks It's not arbitrary; we need that information to understand what you are asking in this issue.
