### ISSUE TITLE
tapping homebrew/science stopped working as of 12/22/2017

### ISSUE THREAD

**Issue by berkaydeniz** [Homebrew/brew#3600]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x ] Ran `brew config` and `brew doctor` and included their output with your issue?

`deniz-mac:Homebrew deniz$ brew config
HOMEBREW_VERSION: 1.4.1-11-g583b61f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 583b61fd324643f15bb8017a6b652afbbbfe7cbc
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f1907dea0890ef018d8a8c1a300ecb76a930c9be
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11`
`deniz-mac:Homebrew deniz$ brew doctor
Your system is ready to brew.`

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)
As I am trying to have a fresh install of homebrew, I tried to tap homebrew/science and this happens:
`deniz-mac:Homebrew deniz$ brew tap homebrew/science
==> Tapping homebrew/science
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 625, done.
remote: Compressing objects: 100% (620/620), done.
remote: Total 625 (delta 0), reused 28 (delta 0), pack-reused 0
Receiving objects: 100% (625/625), 536.45 KiB | 13.41 MiB/s, done.
Error: Non-file alias: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/Aliases/samtools@1.6
Error: Cannot tap homebrew/science: invalid syntax in tap!`

**Comment by vitorgalvao** [comment]
That tap [is being deprecated](https://github.com/Homebrew/homebrew-science/issues/6365).

On another note, when posting multiple lines of code please use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks). Otherwise the output is hard to read and all mushed together.

**Comment by berkaydeniz** [comment]
updated the initial post with fenced code blocks, thank you!

**Comment by MikeMcQuaid** [comment]
Please file this issue on that tap, thanks.

**Comment by ilovezfs** [comment]
fixed in https://github.com/Homebrew/homebrew-science/commit/c36b2e103c23fd9898d7f55a7c3113a2ddb6fcc1
