### ISSUE TITLE
Disable option for reinstall

### ISSUE THREAD

**Issue by milch** [Homebrew/brew#3606]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

--

I have a package that I installed with an option that I no longer want (because it does  not work on my machine). I want to disable this option, but I can't find any way to do so ... I tried looking in the docs, but neither `install` or `reinstall` mention this behaviour. Here's the commands I tried:

- `brew reinstall tesseract --with-no-opencl`
- `brew reinstall tesseract --with-opencl false`
- `brew reinstall tesseract --without-opencl`
- `brew reinstall tesseract --no-with-opencl`

However, all of these result in this warning

> Warning: tesseract: this formula has no $option so it will be ignored!

The package was previously installed using 

`brew install tesseract --HEAD --with-all-languages --with-opencl`

Let me know if you actually need the output of `brew config` or whatever, as this is more of a docs issue than anything to do with my environment

**Comment by ilovezfs** [comment]
This is normal. If you want to change an existing option (as opposed to adding an option) you need to `brew uninstall` first (or manually edit the INSTALL_RECEIPT.json).

**Comment by milch** [comment]
Alright, thanks! I edited INSTALL_RECEIPT.json, now it worked.

I didn't think there was a difference between `reinstall` and `uninstall` + `install` since `brew help reinstall` says: 

> brew reinstall formula:
    Uninstall and then install formula.

May I suggest documenting this somewhere? For example, you could change the output above to something like 

> brew reinstall formula:
    Uninstall and then install formula.
Note: All previously activated install options will be applied again. Manually run `brew uninstall formula` and then `brew install formula` or edit the formula's INSTALL_RECEIPT.json

**Comment by alyssais** [comment]
@milch that sounds like a good idea for a PR!
