### ISSUE TITLE
Failure while executing: /usr/bin/otool

### ISSUE THREAD

**Issue by chriskacerguis** [Homebrew/brew#361]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Running brew doctor returns the following error on macOS Sierra (10.12 Beta, build 16A201w)

> Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool

Ran brew update twice, no change in behavior.  I know that beta OS's are not supported, I'm just putting in a bug report :)

**Comment by MikeMcQuaid** [comment]
Run `xcode-select --install`.

**Comment by chriskacerguis** [comment]
That fixed it, thanks!  Looks like I needed to reinstall it.
