### ISSUE TITLE
A labeling / categorization method for Formula

### ISSUE THREAD

**Issue by NewAlexandria** [Homebrew/brew#3619]
# Feature

## a detailed description of your proposed feature

Add a new method, `labels`, to `Formula` that would return an array of strings.  `brew search` would be updated to allow searching by label.

A canonical list of labels could be maintained in the repo, as guidance.  Custom labels could be added.  

Optionally: a local label config file could add more labels to formula, so that custom groups could be formed.  `brew install` could take a label flag, and install all formula with that label.

## the motivation for the feature

Browsing the formula alphabetically is _less than ideal_.  Labels / Categories would solve that.

Organizing which packages should stay with you from machine to machine is a pain.  Enterprise solutions would use a config system like `chef` or otherwise — too heavy of a solution for individuals.  Being able to `brew install --label py-stats` could ease woes, and more-so if a local labels config file can customize the addition of new ones into the local end. 

## how the feature would be relevant to at least 90% of Homebrew users

As mentioned above.

## what alternatives to the feature you have considered

An external / third-party labels site or system could be built.  It would fall out of relevancy quickly, due to formula update frequency.

**Comment by ilovezfs** [comment]
Thank for the proposal. This is something we've discussed before. However, spending time discussing what labels should or shouldn't be added/removed/updated to formulae is not a good use of maintainer or contributor time.

**Comment by NewAlexandria** [comment]
@ilovezfs while I agree with that in-principle, in practice there is little danger in self-regulation (choose your own labels).  

The `label` feature would not conflict with other critical / mainline features.  

'Library science' is important to me, and I would be glad to contrib my time to 
1. developing the feature completely,
1. labeling existing formula, and 
1. attending to PRs that deal with labeling

I'm fine to solicit this around the [forum](https://discourse.brew.sh/) + IRC, for more eyes on how there could be impacts to existing maintainer efforts.

**Comment by ilovezfs** [comment]
@NewAlexandria you may want to look into https://repology.org/ which has mapped all Homebrew formulae onto their metapackages. It doesn't make much sense for each package manager to maintain metadata like this separately.

**Comment by NewAlexandria** [comment]
@ilovezfs  It sounds like I'm not being clear.

The _metapackage_ is just the name of a given tool, like `ack`.

By _label_ I mean there could be a label `mean_stack`.  Each of the packages `mongodb`,`npm`,`nodejs` would have this label.

**Comment by MikeMcQuaid** [comment]
This is like `brew desc` was: an idea that might be cool but most of the work still needs to be done. It's best implemented as an external command in your own tap and once you have labels for all of Homebrew/homebrew-core's formulae we may consider including it into Homebrew itself (but no guarantees on that).

**Comment by ilovezfs** [comment]
@NewAlexandria sorry for not being explicit. The point is that the repology metapackages have their associated labels/categories shown, so there already exists a mapping of Homebrew formulae onto labels/categories, not just onto metapackage names.

**Comment by NewAlexandria** [comment]
Thanks @MikeMcQuaid for the history. @ilovezfs I'll look more at what Repology does.  Overall, I'll float the idea around more and get POVs.  Happy New Year
