### ISSUE TITLE
gpg installation broke after trying to install pinentry-mac

### ISSUE THREAD

**Issue by llbit** [Homebrew/brew#3620]
- What you were trying to do (and why)

I was trying to run

    echo $PASSPHRASE | gpg --passphrase-fd 0 ...

but it failed with an error about "Inappropriate ioctl for device". I found online some comments about a similar issue that suggested installing pinentr, so I ran:

    brew install pinentry-mac

- What happened (include command output)

Homebrew tried to auto-update but failed:

![screen shot 2017-12-31 at 16 41 43](https://user-images.githubusercontent.com/2757386/34462809-f6168d88-ee4b-11e7-8b35-552ca2340be0.png)
..snip...
![screen shot 2017-12-31 at 16 42 20](https://user-images.githubusercontent.com/2757386/34462812-f9051eec-ee4b-11e7-9dbb-0999a4538d76.png)

After this I could not run `gpg`, the command was not found.

Now Homebrew wants me to install Xcode command line tools to continue:

![screen shot 2017-12-31 at 16 43 10](https://user-images.githubusercontent.com/2757386/34462833-6a9523ea-ee4c-11e7-8beb-d1c0148db2c9.png)

- What you expected to happen

I expected Homebrew to still be able to run `gpg` after `brew install pinentry-mac`

I did not want to update all my Homebrew stuff just to install this program, at least not without warning. I prefer to keep all my programs at their current working versions, and not have to deal with my software breaking due to unwanted updates.

- Step-by-step reproduction instructions (by running `brew` commands)

I don't think this is easily reproducible since you have to have an outdated Homebrew installation.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by llbit** [comment]
I don't see what I missed? This is not a feature request, so I didn't fill out the feature section. Could you tell me what was missing?

**Comment by llbit** [comment]
Okay, I see what was missing. I pasted the list back.

**Comment by MikeMcQuaid** [comment]
> Ran brew config and brew doctor and included their output with your issue?

Can you paste this please?

**Comment by llbit** [comment]
Sorry. I pasted that in the issue now.

I got `gpg` working again, by running `xcode-select --install` and then `brew upgrade` and then `brew unlink gpg && brew link gpg`. Not sure if the `brew update` information is still relevant as I ran it now after getting `gpg` back into working order.

**Comment by MikeMcQuaid** [comment]
Glad you got it sorted.
