### ISSUE TITLE
Bash completion for "brew cask" does not work

### ISSUE THREAD

**Issue by rhwood** [Homebrew/brew#3625]
Useful arguments for brew commands except for `brew cask` can be automatically completed in bash.

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  Use tab completion with `brew cask`
- What happened (include command output)
  `brew cask<tab><tab>` listed the contents of the current directory as useful completions
- What you expected to happen
   `brew cask<tab><tab>` to list usable commands
- Step-by-step reproduction instructions (by running `brew` commands)
   Type `brew cask<tab><tab>`

**Note:** installing the formula `brew-cask-completion` seems to make no difference, but I don't think I should need to install that formula anyways--this should just be part of brew.

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

```
Randalls-MacBook-Pro:~ rwood$ brew update
Updated 1 tap (homebrew/core).
==> Updated Formulae
macvim
Randalls-MacBook-Pro:~ rwood$ brew config
HOMEBREW_VERSION: 1.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e08da95c34c27ba6d5ca5f80718fe2788337cdf
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a7bb7a89db59ab518dcf93f849473ec9fba3f6d7
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/rwood/.rvm/rubies/ruby-2.3.0/bin/ruby
Java: 1.8.0_151
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
Randalls-MacBook-Pro:~ rwood$ brew doctor
Your system is ready to brew.
```

**Comment by apjanke** [comment]
Agreed this is a bug in `brew`. We've pulled the `cask` functionality in to core Homebrew, but haven't updated the `Homebrew/completions/bash` to reflect this. It looks like the current `brew` bash completions don't have a hook in to the `brew-cask-completions`, and since this is now core functionality, seems like an additional installation shouldn't be necessary.

I volunteer for fixing this.

**Comment by apjanke** [comment]
Maybe we can just pull in @xyb's `cask` completions from https://github.com/xyb in to core Homebrew. They're easy to integrate; I've tested it locally (https://github.com/apjanke/brew/tree/cask-bash-completion).

I've [asked upstream](https://github.com/xyb/homebrew-cask-completion/issues/4#issuecomment-356202062) how they'd feel about that.
