### ISSUE TITLE
Using --HEAD with mercurial ends up with "Empty installation" error

### ISSUE THREAD

**Issue by maelvalais** [Homebrew/brew#3628]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
<details><summary>output of brew config</summary>
<pre>
HOMEBREW_VERSION: 1.4.1-49-g4e08da9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e08da95c34c27ba6d5ca5f80718fe2788337cdf
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a7bb7a89db59ab518dcf93f849473ec9fba3f6d7
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 3600
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.15.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.3_1/bin/ruby
Java: 1.8.0_45, 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: 8.2.1
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
</pre>
</details>
<details><summary>output of brew doctor</summary>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  perl

Warning: Your Xcode (8.2.1) is outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.
</pre>
</details>

### Description of the bug & steps to reproduce
I was trying to make the `brew install --HEAD` of one of the [formulas I am writting](https://gist.github.com/maelvalais/396dffa5357f065bf32561600b3301a4). But I noticed that any formula that uses a `hg` repo as HEAD has this issue. One minimal working example (i.e., fast to build and that uses `hg`) is:

    brew install csup --HEAD

The output is:
```
==> Cloning https://bitbucket.org/mux/csup
requesting all changes
adding changesets
adding manifests
adding file changes
added 649 changesets with 1332 changes to 73 files
updating to branch default
64 files updated, 0 files merged, 0 files removed, 0 files unresolved
==> make
Error: Empty installation
```

After some digging (using `--debug` with irb and some `raise "test"` in the formula) I discovered that the following block were entered:

https://github.com/Homebrew/brew/blob/73cb1ac265866dd3abd8b6ebccf64fe3a145b2a8/Library/Homebrew/formula_installer.rb#L725-L727

I think this is because `last_commit`:
https://github.com/Homebrew/brew/blob/9a0981e0eb653b9ef27f5148a093ec397d066cef/Library/Homebrew/download_strategy.rb#L1011-L1013

returns an empty string (I printed it using `puts formula.update_head_version`).

In fact, printing `formula.update_head_version` gives a weird `HEAD-_1` instead of expected `HEAD-11754a7a4c26_1`. What is weird is that when I go into `irb` (using `--debug`), using the command
```ruby
    head.downloader.last_commit # returns correct 11754a7a4c26
    update_head_version                # returns correct HEAD-11754a7a4c26_1
```

Is this only broken on my machine? Does anyone have the same issue?

Sorry for the "noise" created in the issue tracker 😐

**Comment by scpeters** [comment]
I can reproduce the issue on my machine. Adding the following debug lines yields:

~~~
diff --git a/Library/Homebrew/formula_installer.rb b/Library/Homebrew/formula_installer.rb
index 1e2d77b..2b12ca3 100644
--- a/Library/Homebrew/formula_installer.rb
+++ b/Library/Homebrew/formula_installer.rb
@@ -722,6 +722,8 @@ class FormulaInstaller
 
     formula.update_head_version
 
+    ohai "formula.prefix #{formula.prefix}"
+    ohai "formula.prefix.directory? #{formula.prefix.directory?}"
     if !formula.prefix.directory? || Keg.new(formula.prefix).empty_installation?
       raise "Empty installation"
     end
~~~

~~~
$ brew install csup --HEAD 
==> Cloning https://bitbucket.org/mux/csup
Updating /Users/jenkins/Library/Caches/Homebrew/csup--hg
==> make
==> formula.prefix /usr/local/Cellar/csup/HEAD-_1
==> formula.prefix.directory? false
Error: Empty installation
~~~

but there is something installed to a different prefix:

~~~
$ $ find /usr/local/Cellar/csup/
/usr/local/Cellar/csup/
/usr/local/Cellar/csup//HEAD-11754a7a4c26_1
/usr/local/Cellar/csup//HEAD-11754a7a4c26_1/bin
/usr/local/Cellar/csup//HEAD-11754a7a4c26_1/bin/csup
/usr/local/Cellar/csup//HEAD-11754a7a4c26_1/INSTALL_RECEIPT.json
/usr/local/Cellar/csup//HEAD-11754a7a4c26_1/README
/usr/local/Cellar/csup//HEAD-11754a7a4c26_1/share
/usr/local/Cellar/csup//HEAD-11754a7a4c26_1/share/man
/usr/local/Cellar/csup//HEAD-11754a7a4c26_1/share/man/man1
/usr/local/Cellar/csup//HEAD-11754a7a4c26_1/share/man/man1/csup.1
/usr/local/Cellar/csup//HEAD-11754a7a4c26_1/TODO
~~~

The formula.prefix seems not to match the install location?

**Comment by ilovezfs** [comment]
Looks like this is an env filtering bug.
```
HOMEBREW_NO_ENV_FILTERING=1 brew install csup --HEAD -dv
```
works as expected.

**Comment by scpeters** [comment]
@maelvalais noted that `last_commit` in download_strategy.rb returns an empty string:

https://github.com/Homebrew/brew/blob/9a0981e0eb653b9ef27f5148a093ec397d066cef/Library/Homebrew/download_strategy.rb#L1011-L1013

I believe this happens when `cached_location` is not a mercurial repository (for example try `hg parent --template "{node|short}" -R /totally/fake`). Tracing that back, to `def cached_location` for VCSDownloadStrategy, it returns `@clone`:

https://github.com/Homebrew/brew/blob/9a0981e0eb653b9ef27f5148a093ec397d066cef/Library/Homebrew/download_strategy.rb#L178-L180

and `@clone` is set to `HOMEBREW_CACHE/cache_filename` in `initialize`:

https://github.com/Homebrew/brew/blob/9a0981e0eb653b9ef27f5148a093ec397d066cef/Library/Homebrew/download_strategy.rb#L140

still digging...

**Comment by scpeters** [comment]
found it: #3643

**Comment by maelvalais** [comment]
Thank you!!! 😄
