### ISSUE TITLE
Add :cxx17 support

### ISSUE THREAD

**Issue by rakhimov** [Homebrew/brew#3629]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features

Support for ``needs :cxx17`` to require C++17.
I guess this would require at least gcc 7.1 or clang 4.0.

**Comment by alyssais** [comment]
Is there a formula that requires this?

**Comment by rakhimov** [comment]
@alyssais I suppose not yet in the core.
I have a tap that will require cxx17 on next releases.
Does that count?

**Comment by alyssais** [comment]
@rakhimov okay, cool. Thanks for the reply.

I'm going to have a go at adding this, but if it's not breaking Homermew/core it probably won't be prioritised.

**Comment by ilovezfs** [comment]
I'm pretty 👎 on a new DSL here given what a mess the `cxx11` DSLs have ultimately become https://github.com/Homebrew/homebrew-core/blob/master/Formula/nzbget.rb#L17-L35.

**Comment by MikeMcQuaid** [comment]
I think the `needs :cxx*` DSLs (if we were to add new ones) should be something that encompasses `fails_with` and automatically adds a `depends_on` (which applies at runtime for C++ stdlib linkage). Essentially we only really care about "can we use the system compiler on your current macOS version and if not which compiler should we use (`depends_on "gcc"`)

**Comment by alyssais** [comment]
Does that mean changing the behaviour of `needs :cxx*` only for new C++ standards, or are you proposing changing the existing ones as well?

**Comment by ilovezfs** [comment]
I'd propose changing nothing at this point. We've been working on removing the cxx11 stuff from core as much as possible and moving toward regular dependencies away from magic requirements.

**Comment by ilovezfs** [comment]
@rakhimov you can use the already existing`fails_with` formula component for your purposes.

**Comment by MikeMcQuaid** [comment]
Passing on this for now, sorry.
