### ISSUE TITLE
Cask install not including HOMEBREW_PREFIX/(s)bin in PATH

### ISSUE THREAD

**Issue by thieman** [Homebrew/brew#3630]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new

* Submitter's note: I believe this is a `brew` problem that manifests itself during `post_install`, so I thought I met this bullet. If not please let me know if there's a better place for me to submit.

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features

A cask I'm trying to install is failing because the Homebrew bin directory is not included in the PATH during its post_install step. This worked until recently but is giving us the following with Homebrew 1.4.2.

The cask we were using is `dusty`, so you should be able to repro with `brew cask install dusty`, though it's pretty heavyweight and installs Docker Toolbox as a dependency. The post_install of this cask will print out the PATH.

It looks like from #3576 and #3581 that it's still expected that the Homebrew bin dir be included in this PATH, but for whatever reason we're not getting it.

`/usr/local` is our `HOMEBREW_PREFIX`. The PATH of the user we're running `brew` as is:

```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

But the PATH during post_install is:

```
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm
```

The full `env` of the user, in case it's useful:

```
SSH_AGENT_PID=2689
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/jz/g13f41n95c106mxy3p1v4fv00000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.v5EwzGaIHP/Render
TERM_PROGRAM_VERSION=400
TERM_SESSION_ID=D9A77ED6-40E6-451F-8AEE-7952A19A3407
USER=redacted_username
SSH_AUTH_SOCK=/var/folders/jz/g13f41n95c106mxy3p1v4fv00000gn/T//ssh-IQ1vzwLvRTmr/agent.2688
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/redacted_username/Desktop
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/redacted_username
LOGNAME=redacted_username
_=/usr/bin/env
OLDPWD=/Users/redacted_username
```

### brew config

```
HOMEBREW_VERSION: 1.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e08da95c34c27ba6d5ca5f80718fe2788337cdf
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 260006b775674e736785a27bef2410cbc45ea47d
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.2-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

### brew doctor

```
Your system is ready to brew.
```

**Comment by ilovezfs** [comment]
@reitermarkus Casks don't have "post_install" do they?

**Comment by thieman** [comment]
My mistake, looks like what I'm talking about is actually the `installer` key. Cask in question: https://github.com/caskroom/homebrew-cask/blob/master/Casks/dusty.rb

Quite possible those linked issues don't apply, in that case. Is removing the Homebrew bin directory from PATH for these installs intentional, then?

**Comment by ilovezfs** [comment]
Try
```
HOMEBREW_NO_ENV_FILTERING=1 brew cask ...
```

**Comment by thieman** [comment]
Ah ok now I think this is probably a dupe of #3191. I'll give that flag a try next time I'm at a computer, or maybe try adding the PATH to our formula as Mike seems to be suggesting in that issue. Sort of a bummer that this broke our Cask but I'm guessing that was anticipated with the env filtering changes.

**Comment by MikeMcQuaid** [comment]
> Quite possible those linked issues don't apply, in that case. Is removing the Homebrew bin directory from PATH for these installs intentional, then?

Yep but it may not be for `brew cask`.

**Comment by reitermarkus** [comment]
Yeah, I think `installer` should always add Homebrew‘s `bin` to the `PATH`.

**Comment by thieman** [comment]
@reitermarkus If this is something you think is worth fixing, do we need to do anything to protect it from being closed by the stalebot?
