### ISSUE TITLE
error on brew upgrade

### ISSUE THREAD

**Issue by kirk86** [Homebrew/brew#3638]
Recently I've been trying to upgrade the packages with `brew upgrade` and I get the following errors:

```
brew cleanup:
Warning: Skipping htop: most recent version 2.0.2_1 not installed
Warning: Skipping sip: most recent version 4.19.6_3 not installed
Warning: Skipping youtube-dl: most recent version 2018.01.07 not installed
Warning: Skipping imagemagick: most recent version 7.0.7-19 not installed
```

```
brew upgrade:
==> Upgrading 4 outdated packages, with result:
htop 2.0.2_1, sip 4.19.6_3, youtube-dl 2018.01.07, imagemagick 7.0.7-19
htop: This formula either does not compile or function as expected on macOS
versions newer than Sierra due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

Any ideas?

**Comment by alyssais** [comment]
`htop` isn't compatible with macOS High Sierra. You should `brew uninstall` it or at least `brew pin htop` to stop Homebrew trying to upgrade it.

See https://github.com/hishamhm/htop/issues/682.

**Comment by alyssais** [comment]
I wonder if `brew upgrade` should just skip packages that fail a macOS version requirement...

**Comment by ilovezfs** [comment]
This is expected behavior. Please see

https://github.com/hishamhm/htop/issues/682.

Also, the template should always be filled out and this issue should have been filed in homebrew/core since it's specific to one formula.
