### ISSUE TITLE
 Support for macOS (OS X) 10.12.0

### ISSUE THREAD

**Issue by stejmurphy** [Homebrew/brew#364]
- [ yep ] Ran `brew update` and retried your prior step?
- [yep ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [yep ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Add support for macOS 10.12.0 
When installing/updating/upgrading any taps, you get the following 
``Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.``

**Comment by DomT4** [comment]
> Warning: You are using OS X 10.12. We do not provide support for this pre-release version. You may encounter build failures or other breakages.

There's basic support for macOS 10.12 already, Homebrew recognises that system & knows which Xcode/CLT people should be using, and `brew tests` will pass. Support is fairly rapidly being added on our side. What will take _significantly_ longer is formulae compatibility, which is more or less out of our hands beside doing some backporting where appropriate.

We're less than 36 hours into 10.12 being a "thing". The message is a warning that you'll see more breakage on 10.12 than you would 10.9-10.11. If nothing breaks, ignore the warning, but we're not going to axe the warning until the system drops stable.

**Comment by chmaynard** [comment]
Maintainers, it's important to be precise and avoid spreading FUD.
```Warning: You are using OS X 10.12.```
Almost correct. Apple changed the name to macOS. 
```We do not provide support for this pre-release version.```
It's unclear who "we" is or what "provide support" means.
```You may encounter build failures or other breakages.```
Build failures occur all the time for many different reasons. Also, there's no such word as "breakage".
```Please create pull-requests instead of filing issues.```
What does this even mean? You don't want to know if your users are experiencing a problem?

**Comment by tdsmith** [comment]
Thanks for the feedback. We is us, support is this, [breakage is absolutely a word](http://www.merriam-webster.com/dictionary/breakage), and while fixing issues on prerelease operating systems is not a priority for us, especially early in the release cycle, we do appreciate and accept fixes.

**Comment by edm00se** [comment]
If anyone (else) comes across this after the fact, you may wish to check to confirm your version of homebrew is updating past 1.0. I found myself getting the message above after `brew update` and `brew upgrade`, but still needed to follow the info in [this thread](http://discourse.brew.sh/t/how-to-upgrade-brew-stuck-on-0-9-9/33) on the homebrew forum to get updated correctly. The message no longer shows after I got upgraded from v 0.9x to 1.x.
