### ISSUE TITLE
Formula installed as a dependency will always be marked as *not* installed_on_request

### ISSUE THREAD

**Issue by chasetopher** [Homebrew/brew#3642]
If formula A is installed "on request," but is then upgraded during an upgrade/install of Formula B (where B depends on A), then the newly installed version of A will always have `installed_on_request` set to `false`.

This is relevant because I like to use `brew bundle dump` to generate a Brewfile of all the formulas I install "on request." But if there are interdependencies in those formulas, under certain circumstances running a `brew upgrade` and another `brew bundle dump`, some formulas get removed from the Brewfile because they were installed as a dependency and therefore get `installed_on_request` set to `false`.

I believe the relevant line is here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L567

Perhaps this should check if `installed_on_request` was already set and default to that?

**Comment by MikeMcQuaid** [comment]
Please fill in the issue template every time e.g. specifically your `brew config` and `brew doctor` output. 

In this case also can you provide step-by-step reproduction commands from an empty Homebrew installation.

Thanks!

**Comment by alyssais** [comment]
I've reproduced this:

```sh
export HOMEBREW_BUILD_FROM_SOURCE=1
git -C "$(brew --repo homebrew/core)" checkout ﻿﻿dd5f216bfe7d8d186853f303fb68cb4c0ecbdba8
brew install libdvdcss
jq .installed_on_request "$(brew --prefix libdvdcss)/INSTALL_RECEIPT.json"
git -C "$(brew --repo homebrew/core)" checkout master
brew install libdvdread
jq .installed_on_request "$(brew --prefix libdvdcss)/INSTALL_RECEIPT.json"
```

**Comment by MikeMcQuaid** [comment]
Thanks @alyssais. Mind taking a look at this one?

**Comment by alyssais** [comment]
Already on it :)
