### ISSUE TITLE
Feature proposal: command aliases

### ISSUE THREAD

**Issue by vinyldarkscratch** [Homebrew/brew#3658]
I ran into a little issue of forgetting to type the actual Brew commands rather than my own aliases for them.  So, I had a thought...  What if those aliases were official to Homebrew?  They're pretty simple ones, like `pour = brew install`, `spill = brew uninstall`, `tox = brew info`, etc., but I think it would be nice to have!  (Hence why I set them up.  😛)

I'm happy to make a PR for this.  (Pretty much just looking for an okay before setting it up for everyone to use!)

**Comment by chdiza** [comment]
You can already make an "external command" that calls a real brew command.  I do this, it's real easy, and doesn't require messing with homebrew code.

I would've thought that one could also make an "external command" that's actually just a symlink to a real brew command, but I just tested it and it doesn't work.  This is probably because the symlink's target (e.g., `deps.rb`) isn't executable.

**Comment by vinyldarkscratch** [comment]
It’s even easier, really: `alias pour=‘brew install’` in `~/.bashrc`.  It’s still a thing that you’d have to set up if you want it.  I’m just thinking it would be nice if everyone had `pour Formula` by default.  😛

**Comment by chdiza** [comment]
That particular one is not a good idea for a built-into-HB alias because `brew install` sometimes builds from source, which is not `pour`ing.

Also, I'd wager that there is no way HB will ever have an alias that covers up the `brew` portion of a CLI call.

**Comment by vinyldarkscratch** [comment]
I mean, it's basically shortening the command to install something by eight characters, and still allowing for all of the known arguments.  All it would be is a `pour.sh` that's added to the path and is executable, that simply reads:

```sh
#!/bin/sh
brew install $@
```

So, `pour --build-from-source Formula` would basically be `brew install --build-from-source Formula`.

Honestly, I know this is a minor thing, and that it seems somewhat redundant, but the little things help, and it's not something that will affect Homebrew in any negative way (as far as I can tell).  But in the end, it's up to what most people think, and more importantly the Homebrew developers.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-aliases and your own Bash aliases are better solutions here. Please follow the format in the feature request part of the issue template in future, thanks.

**Comment by vinyldarkscratch** [comment]
Doesn't quite work the way I was hoping (since it leaves `brew` in the command, which I love Homebrew, but it's more characters to type and can get in the way when I'm trying to work quickly), but ah well, I'll just hold onto my own bash aliases!
