### ISSUE TITLE
Brew 

### ISSUE THREAD

**Issue by ttoine** [Homebrew/brew#366]
When installing homebrew on my mac in the terminal, I get this:
```
==> Homebrew has enabled anonymous aggregate user behaviour analytics
Read the analytics documentation (and how to opt-out) here:
  https://git.io/brew-analytics
```

This is possible in North America, but illegal in Europe. To comply with European laws, you must ask the end user to opt-in.

**Comment by DomT4** [comment]
As far as the law seems to suggest, that _could_ be the case if we were collecting PII, which we aren't.

To quote myself from elsewhere:

<img width="813" alt="screen shot 2016-05-01 at 12 53 27" src="https://cloud.githubusercontent.com/assets/6998367/16084939/648b4070-3312-11e6-8177-4f824bd2756d.png">

**Comment by MikeMcQuaid** [comment]
If this is unacceptable to you, please use another package manager.
