### ISSUE TITLE
Homebrew should use a custom gitconfig

### ISSUE THREAD

**Issue by MindTooth** [Homebrew/brew#3664]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Running `brew log` using _diff-so-fancy_ and _vimpager_. I have set this line in my _.gitconfig_ file.
```
[core]
  pager = diff-so-fancy | vimpager
```

I just wanted to know if there is a way to fix this somehow.  As it works git regular `git diff` inside a repo.
- What happened (include command output)
`brew log` complains that it can find the commands.
```
diff-so-fancy | vimpager: diff-so-fancy: command not found
diff-so-fancy | vimpager: vimpager: command not found
```
- What you expected to happen
`brew log` showing it's output
- Step-by-step reproduction instructions (by running `brew` commands)
1. `brew log`
2. Commands not found

### Includes
```
~ $ brew doctor
Your system is ready to brew.
```

```
~ $ brew config
HOMEBREW_VERSION: 1.4.3-20-g427c6ce
ORIGIN: https://github.com/Homebrew/brew
HEAD: 427c6ce3d57ad50ef73f9ba28b81ddc96179f905
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eae0bcacf6aa1592ee0fdc2d424a1c63a0a2d17a
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.15.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0/bin/ruby
Java: N/A
macOS: 10.13.2-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

**Comment by MikeMcQuaid** [comment]
Yep, this is a known issue. The fix will be to use a custom Homebrew `gitconfig` such that your custom pager is not used.

**Comment by MindTooth** [comment]
Thank you for looking into it.  I've remove any custom settings for now.
