### ISSUE TITLE
Some commands are missing from brew cask completion

### ISSUE THREAD

**Issue by rhwood** [Homebrew/brew#3673]
Thank you for recently adding the tab completion for brew cask! It has been helpful. That said, it appears to be missing some cask commands.

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  Tab complete `brew cask outdated` and `brew cask upgrade` to list outdated casks and then upgrade them without typing everything out
- What happened (include command output)
  Tab completion for `brew cask` did not include the `outdated` and `upgrade` commands (and found while capturing below output, is also missing `reinstall` and `--version`)
- What you expected to happen
  Typing `brew cask o<tab><tab>` to autocomplete to `brew cask outdated`
  Typing `brew cask up<tab><tab>` to autocomplete to `brew cask upgrade`
- Step-by-step reproduction instructions (by running `brew` commands)
  Type `brew cask<tab><tab>` to get list of completions; observe that commands listed in output of `brew cask<return>` differ from commands listed in output of `brew cask<tab><tab>`:
```
$ brew cask<return>
brew-cask provides a friendly homebrew-style CLI workflow for the
administration of macOS applications distributed as binaries.

Commands:

    --version              displays the Homebrew-Cask version
    audit                  verifies installability of Casks
    cat                    dump raw source of the given Cask to the standard output
    cleanup                cleans up cached downloads and tracker symlinks
    create                 creates the given Cask and opens it in an editor
    doctor                 checks for configuration issues
    edit                   edits the given Cask
    fetch                  downloads remote application files to local cache
    home                   opens the homepage of the given Cask
    info                   displays information about the given Cask
    install                installs the given Cask
    list                   with no args, lists installed Casks; given installed Casks, lists staged files
    outdated               list the outdated installed Casks
    reinstall              reinstalls the given Cask
    search                 searches all known Casks
    style                  checks Cask style using RuboCop
    uninstall              uninstalls the given Cask
    upgrade                upgrades all outdated casks
    zap                    zaps all files associated with the given Cask

See also "man brew-cask"
```
```
$ brew cask<tab><tab> 
--appdir              --screen_saverdir     home
--binarydir           --servicedir          info
--caskroom            --verbose             install
--colorpickerdir      -S                    list
--debug               abv                   ls
--fontdir             audit                 remove
--force               cat                   rm
--input_methoddir     cleanup               search
--internet_plugindir  create                uninstall
--no-binaries         doctor                zap
--prefpanedir         edit                  
--qlplugindir         fetch                 
```

Output of `brew config && brew doctor`:
```
$ brew config && brew doctor 
HOMEBREW_VERSION: 1.4.3-27-g02591bd
ORIGIN: https://github.com/Homebrew/brew
HEAD: 02591bdf341b4c33383b5eb537bcff0e49157a82
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 98768651244eeb1d63a3f48a2d1bda243dd86446
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0/bin/ruby
Java: 1.8.0_152, 1.8.0_151
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
Your system is ready to brew.
```

**Comment by MindTooth** [comment]
Bash, fish or zsh?

I've submitted for fish: https://github.com/fish-shell/fish-shell/pull/4647

**Comment by rhwood** [comment]
Sorry, this is for bash

**Comment by rhwood** [comment]
@apjanke Thank you for the quick fix. There is a problem with that fix in that
- `brew upgrade` only lists outdated packages, while `brew cask upgrade` lists all installed cask packages
- `brew outdated` does not offer any completions but `brew cask outdated` lists all installed cask packages

Should I report these in a new issue, or does outdated and upgrade in brew-cask behave differently than in brew?

**Comment by apjanke** [comment]
The `brew cask upgrade` difference is a bug and oversight on my part; it should list only outdated packages. I'll submit a fix.

The different `brew cask outdated` completion reflects an actual difference between `brew outdated` and `brew cask outdated` behavior/interface, as far as I can tell: `brew cask outdated` takes an optional list of formulae to check; the core `brew outdated` does not. That's a minor bummer IMHO, and probably a reflection of the convergent history of `brew` and `brew cask`. But completion is there to reflect the actual command behavior, so I don't think this is a bug in the completion code. If you'd like to open a separate bug to open discussion about unifying the behavior there, go for it.

**Comment by apjanke** [comment]
Here's a fix for `brew cask upgrade <tab>` completion. Is that what you were looking for here? https://github.com/Homebrew/brew/pull/3687

**Comment by rhwood** [comment]
@apjanke It does look like #3687 addresses my concerns. Thank you for doing that.
