### ISSUE TITLE
The shell completion does not work well when cask repo is not cloned.

### ISSUE THREAD

**Issue by correctizer** [Homebrew/brew#3677]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features

Input `brew cask install ...` and press TAB key, the output gets messed up if cask is not cloned yet.

<img width="682" alt="screen shot 2018-01-13 at 10 39 09 am" src="https://user-images.githubusercontent.com/35130945/34902072-06ca4f54-f84f-11e7-9501-fad2a599cd1d.png">

It seems that it takes too long for a completion even if the output log if omitted, so I recommend to disable shell completion in this situation.

**Comment by alyssais** [comment]
> - [x] Ran brew config and brew doctor and included their output with your issue?

Please do this in future.

I've reproduced the bug, though. Thanks for the report.

**Comment by alyssais** [comment]
(For reference, I have so far reproduced this issue with the ZSH completions. I haven't tried the Bash ones yet.)

**Comment by correctizer** [comment]
Apologize for that check, and thank you very much.
