### ISSUE TITLE
vim dependency: ruby and ruby@2.3 issue

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/brew#3681]
Hi there, I have few problems with VIM formula

1. It depends on `ruby` and this is not optional
2. I use ruby@2.3 and it installs ruby 2.5 for me, how can I force VIM to use ruby@2.3 as a dependency instead?
3. There's no `--without-perl --without-python --without-ruby` option for this formula

What do you think?

**Comment by ilovezfs** [comment]
Using a custom ruby with vim is no longer supported. Please fill out the issue template completely in the future and file formula-specific issues in https://github.com/Homebrew/homebrew-core
