### ISSUE TITLE
brew linkage turns path to lowercase

### ISSUE THREAD

**Issue by maelvalais** [Homebrew/brew#3686]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

### Description

The command
```
brew linkage Formula/formula.rb
```
is searching for `formula/formula.rb` instead of `Formula/formula.rb` (capitals are dropped). The error message is:

    Error: No available formula with the name "formula/formula.rb"

This is not a problem on case-insensitive file systems, but it is a problem on linux when trying to test the linkage on travis-ci daily CRON builds.

**Comment by ilovezfs** [comment]
Usage is typically `brew linkage foo` not `brew linkage Formula/foo.rb`

**Comment by maelvalais** [comment]
Ah, sorry 😄 As `brew linkage Formula/foo.rb` worked on mac, I though it was a feature!
But it makes sense as the formula must be installed!
