### ISSUE TITLE
I have problem with brew installing, where should i seek assistance? Thanks

### ISSUE THREAD

**Issue by sagar-m** [Homebrew/brew#3688]
Hi, I get this error when installing homebrew in python 2.7 on mac os. I am using spyder, anaconda. Thank you very much.

poonam@Poonams-MacBook-Air-2:/Users> /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
/usr/bin/ruby -e "$(curl -fsSL https://r
<2:/Users> /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/H
< "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/ins
<.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following existing directories will be made group writable:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/lib/pkgconfig
/usr/local/share/info
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
==> The following existing directories will have their owner set to poonam:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/lib/pkgconfig
/usr/local/share/info
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
==> The following existing directories will have their group set to admin:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/lib/pkgconfig
/usr/local/share/info
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Homebrew
/usr/local/Frameworks
/usr/local/etc
/usr/local/opt
/usr/local/sbin
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var
==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/lib/pkgconfig /usr/local/share/info /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3 /usr/local/share/man/man5
sudo: no tty present and no askpass program specified
Failed during: /usr/bin/sudo /bin/chmod u+rwx /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/lib/pkgconfig /usr/local/share/info /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3 /usr/local/share/man/man5
poonam@Poonams-MacBook-Air-2:/Users>

**Comment by MikeMcQuaid** [comment]
Looks like you're trying to install over SSH. Don't do that.

**Comment by sagar-m** [comment]
Hi Mike, I follow you on twitter! 
Then how should I do it? Sorry I have to complete an assessment on python using xgboost right now. And I read that I need to install brew before installing xgboost. Struggling for last 2 hours...grrr

https://xgboost.readthedocs.io/en/latest/build.html#building-on-osx

Thank you very much. Highly appreciate it.

**Comment by MikeMcQuaid** [comment]
You will need to figure this out yourself. The issue is that you cannot run `sudo`.

**Comment by MikeMcQuaid** [comment]
And don't create any more identical issues or issues without reading and filling in the issue template, please.

**Comment by sagar-m** [comment]
Ok. Thanks for the suggestion. Using the terminal window in mac.
