### ISSUE TITLE
How upgrade software use brew, when this is not newest

### ISSUE THREAD

**Issue by tomoat** [Homebrew/brew#3690]
Please upgrade yarn. I don't know how to change the latest

Use `brew upgrade yarn` 

yarn 1.3.2 already installed

But in fact, the latest version of yarn is 1.4.0

**Comment by ilovezfs** [comment]
1.4.0 is prerelease

**Comment by ilovezfs** [comment]
@tomoat in the future, please file formula-specific issues in https://github.com/Homebrew/homebrew-core/ and always fill out the issue template completely.
