### ISSUE TITLE
Formatting of 1.5.0 announcement at https://brew.sh/2018/01/19/homebrew-1.5.0/ is messed up

### ISSUE THREAD

**Issue by amosshapira** [Homebrew/brew#3701]
The formatting of the announcement at https://brew.sh/2018/01/19/homebrew-1.5.0/ is messed up starting at the `brew postgresql-upgrade-database is a new command to simplify upgrading PostgreSQL databases between major versions.` part.

It looks like the `</a>` tag is put later than it should, and there is a strang `== $0` in the page source after the `</code>` tag. Similar problems seem to repeat in all the following list items.

**Comment by amosshapira** [comment]
Thanks for the pointer.
Opened PR at https://github.com/Homebrew/homebrew.github.io/pull/199
(mention of issue number doesn't seem to have created the link, sorry)

**Comment by MikeMcQuaid** [comment]
@amosshapira FYI I reverted the two PRs as I misread this bug report and the original formatting was intentional (see the 1.4.0 blog post for comparison https://brew.sh/2017/12/11/homebrew-1.4.0/)

**Comment by amosshapira** [comment]
No worries. The original formatting looks unusual IMHO. What's the original bug report which was *for* that format?

**Comment by amosshapira** [comment]
never mind. just curiosity.
