### ISSUE TITLE
depends_on "python2" is preferred?

### ISSUE THREAD

**Issue by kkdd** [Homebrew/brew#3704]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

-------------------

Hello,
I believe that ```depends_on "python2"``` is preferred rather than ```depends_on "python"``` written in homebrew's formulas when specifying homebrew's Python 2. Is it right?

**Comment by alyssais** [comment]
On 1 March `python` will be changed to Python 3, so if you need Python 2 you should use `python@2` for forwards compatibility.

This repo’s issue tracker isn’t really the place to ask questions about formula authorship, though. In future, I recommend you either ask on https://discourse.brew.sh/, IRC, or open a pull request with what you have so far to homebrew-core if you want to submit it there.

Thanks!

**Comment by kkdd** [comment]
Thank you for your explanation.
