### ISSUE TITLE
clang++ shim adds problematic arguments

### ISSUE THREAD

**Issue by ianrrees** [Homebrew/brew#3705]
In working on a formula for [PySide2](https://wiki.qt.io/PySide2) (initially to use for [FreeCAD](http://github.com/FreeCAD/)), we've run in to a problem that relates to the Homebrew shim for clang++.  I'm not totally clear on whether the issue is more to do with PySide2, or with Homebrew's shim.  Since the PySide2 build script works outside of the Homebrew environment, I thought it would be good to start here.

PySide2's build process uses a tool called Shiboken2 (which is now effectively bundled with the PySide2 source) in generating bindings to the Qt C++ source.  Shiboken2 internally calls `clang++ -E -x c++ - -v` to determine the default include paths for the clang++ compiler on the host system.  When Shiboken2 is run in the Homebrew context, the Homebrew clang++ shim adds include paths to everything in the `HOMEBREW_INCLUDE_PATHS` environment variable, which contains the include path for Qt.  Shiboken2 then interprets those paths as the default include paths for clang++, and then doesn't generate the correct bindings.  This then causes the PySide2 build to fail.

On one hand, it's a Shiboken2 problem, because it should generate the right bindings when clang++ has the path to Qt built in to its search paths.

On the other hand, it's a Homebrew shim problem, because the PySide2 install script is getting something unexpected and different when it invokes clang++.

In the mean time, I've worked around the problem [like this](https://github.com/FreeCAD/homebrew-freecad/commit/352f20f8db3ff2f36690884108c0646271a60952#diff-313a6a3d25aa041ee3dc3cbd65d4f22b), but feel like that's a bit ugly.

# Please always follow these steps:
- [well, it is an install problem, but...] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
Your build system should use `xcrun clang++` wherever the canonical clang++, and not the shim, is required. (Or first `xcrun -find clang ++` and then use that path.)

**Comment by ianrrees** [comment]
Thanks @ilovezfs for the quick response.  I might not have explained the situation adequately:

Shiboken2 is a cross-platform C++ program, which invokes clang++ internally.  Shiboken2 needs to persist beyond the Homebrew build environment and work from outside it.

Using `xcrun clang++` in Shiboken2 is certainly possible, but that means an upstream change to special-case for OSX+Homebrew.  From my perspective, it seems cleaner to put the special behaviour in the Homebrew formula, since it's meant to work around the shimmed clang++ which only exists in the Homebrew build environment.

**Comment by ilovezfs** [comment]
Assuming the formula is not for [homebrew/core](https://github.com/Homebrew/homebrew-core/), you could use `env :std`
