### ISSUE TITLE
FEATURE (regression?): `brew doctor` doesn't check permission on /usr/local/man

### ISSUE THREAD

**Issue by sesam** [Homebrew/brew#3708]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Tried a simple `brew upgrade`

- What happened (include command output)

Various permission errors
````
Linking /usr/local/Cellar/cmake/3.10.2... Error: Permission denied @ dir_s_mkdir - /usr/local/share/man/man1
````

- What you expected to happen
Expected `brew upgrade` to function normally.

- Step-by-step reproduction instructions (by running `brew` commands)
1. have a Sierra mac, upgrade to High Sierra
2. run `brew upgrade` now and then normally
3. at some unhappy timepoint, it stops working normally, with complaints about failing to add links to /usr/local/share/man/man1 (and other manX and possibly also other places under /usr/local)
4. `brew update` says all is updated.
5. `brew doctor` says nothing useful and does not help
6. Try all ideas on Stackoverflow etc (also finding #3322 which seems prematurely abandoned)
7. cry a bit about maybe having to make a full brew reinstall
8. cross fingers and run the shell command from https://brew.sh/  `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
`

VOILA! That install script says:
````
==> The following existing directories will be made group writable:
/usr/local/share/man

Press RETURN to continue or any other key to abort
````

So why didn't `brew doctor` suggest or fix this?

# Features

Please, please, make `brew doctor` check all things that the brew install script checks, including permissions on `/usr/local/share/man`

**Comment by sesam** [comment]
$ brew config # (config after things are ok)
````
HOMEBREW_VERSION: 1.5.0-6-gd14fd49
ORIGIN: https://github.com/Homebrew/brew
HEAD: d14fd49b3062ab1d95e86b78a8228c8aee3a3304
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ce18557e997458821f10e7b262b61a3ad17e4d55
Core tap last commit: 73 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
GCC-4.2: build 5666
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/s/.rvm/rubies/ruby-2.2.8/bin/ruby
Java: N/A
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
````

**Comment by sesam** [comment]
$ brew doctor # (before)
````
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libtasn1
  imagemagick

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/var/homebrew/linked/libtasn1
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'


Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install postgresql

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  imagemagick@6
  postgresql@9.6
  srm
````

**Comment by ilovezfs** [comment]
@sesam we'd be happy to review a PR adding such a diagnostic to doctor. I'm glad to hear you figured it out.

**Comment by sesam** [comment]
You don't want any issue # to track this?

**Comment by ilovezfs** [comment]
@sesam we don't leave issues open for things no one is currently intending to work on.

**Comment by sesam** [comment]
So, I've spent >3 hours on this. Unsure what I was supposed to do originally.

People are ["solving" this problem](https://stackoverflow.com/questions/47513024/how-to-fix-permissions-on-home-brew-on-macos-high-sierra/47721925) by randomly doing chown and chmod 777 on anything that seems to try to resist when they need to get brew to work.

And in #3228 @dtamayo writes it was necessary to manually `mkdir /usr/local/include` and `mkdir /usr/local/Frameworks` __before__  running `sudo chown -R $(whoami) $(brew --prefix)/*`

Seeing the list of folders in Library/Homebrew/keg.rb
````
  TOP_LEVEL_DIRECTORIES = %w[bin etc include lib sbin share var Frameworks].freeze
  ALL_TOP_LEVEL_DIRECTORIES = (TOP_LEVEL_DIRECTORIES + %w[lib/pkgconfig share/locale share/man opt]).freeze
````

maybe easiest is if of these are created ahead of time, and permissions adjusted.

Currently there's only a check if the folder is writeable:

````
def check_access_prefix_directories
        not_writable_dirs = []
        Keg::ALL_TOP_LEVEL_DIRECTORIES.each do |dir|
          path = HOMEBREW_PREFIX/dir
          next unless path.exist?
          next if path.writable_real?
...
````

but it seems they also need to be searchable (+x).


Maybe like this

````
      def check_missing_prefix_directories
        missing_dirs = []
        Keg::ALL_TOP_LEVEL_DIRECTORIES.each do |dir|
          path = HOMEBREW_PREFIX/dir
          missing_dirs << path unless path.exist?
        end

        return if missing_dirs.empty?

        <<~EOS
          The following directories are missing:
          #{missing_dirs.join("\n")}
          You should create them:
            mkdir -p #{missing_dirs.join(" ")}
        EOS
      end

      def check_searchable_prefix_directories
        not_searchable_dirs = []

        Keg::ALL_TOP_LEVEL_DIRECTORIES.each do |dir|
          path = HOMEBREW_PREFIX/dir
          next unless path.exist?
          next unless path.executable_real?
          not_searchable_dirs << path
        end

        return if not_searchable_dirs.empty?

        <<~EOS
          The following directories are not searchable:
          #{not_searchable_dirs.join("\n")}

          This can happen on High Sierra and cause installs to
          fail during the link step.

          You should change the permissions of these directories.
          back to your user account:
            sudo chmod -R u+wxg+wx #{not_searchable_dirs.join(" ")}
        EOS
      end

````

**Comment by ilovezfs** [comment]
@sesam can you open a PR for that?

>And in #3228 @dtamayo writes it was necessary to manually mkdir /usr/local/include and mkdir /usr/local/Frameworks before running sudo chown -R $(whoami) $(brew --prefix)/*

Right, because on 10.13 chown'ing/chmod'ing /usr/local does nothing. So `sudo` would still be needed for the `mkdir`.
