### ISSUE TITLE
Executables with RPATH are not relocatable

### ISSUE THREAD

**Issue by sjackman** [Homebrew/brew#371]
The `sailfish` formula is not `cellar :any` because `cmake` sets the `RPATH` of the executable. I believe `keg_relocate` does not modify the `RPATH`. Could someone please confirm that? The `RPATH` should be given the same relocation treatment as `install_name`.

**Comment by sjackman** [comment]
See https://github.com/Homebrew/homebrew-science/pull/3753#issuecomment-226634919

**Comment by MikeMcQuaid** [comment]
I'm not sure if it does and if it doesn't: we'd welcome a PR to do so.

**Comment by sjackman** [comment]
Should the `RPATH` simply be deleted? I believe it's redundant with the absolute path `install_name` mechanism of finding shared libraries on Mac.

**Comment by sjackman** [comment]
`sailfish` includes an `RPATH`, which makes the bottle non-relocatable. Removing the `RPATH` makes it `cellar :any`.

```
❯❯❯ brew install sailfish
❯❯❯ otool -l /usr/local/bin/sailfish |grep RPATH -A2
          cmd LC_RPATH
      cmdsize 56
         path /usr/local/Cellar/sailfish/0.10.1/lib (offset 12)
❯❯❯ brew bottle -v sailfish
Warning: String '/usr/local/Cellar' still exists in these files:
/usr/local/Cellar/sailfish/0.10.1/bin/sailfish
 --> match '/usr/local/Cellar/sailfish/0.10.1/lib' at offset 0x9e4
❯❯❯ chmod u+w /usr/local/bin/sailfish
❯❯❯ install_name_tool -delete_rpath /usr/local/Cellar/sailfish/0.10.1/lib /usr/local/bin/sailfish
❯❯❯ brew bottle -v sailfish
    cellar :any
```

**Comment by MikeMcQuaid** [comment]
If it can be: yes, that makes sense.

**Comment by sjackman** [comment]
There's a relevant discussion on RPATH in Conda at https://github.com/conda/conda-build/issues/279

**Comment by sjackman** [comment]
After some reading, it looks as though `RPATH` aren't used on Mac OS unless explicitly requested by `@rpath` in the `install_name`. If none of the dependent libraries use `@rpath` in the `install_name`, then `RPATH` is not used and can be safely deleted.
e.g.
`install_name = /usr/lib/libncurses.5.4.dylib`
is equivalent to
`install_name = @rpath/libncurses.5.4.dylib` `RPATH=/usr/lib`

**Comment by UniqMartin** [comment]
Indeed, none of our Mach-O handling reads or manipulates the `LC_RPATH` load commands. That's probably because RPATHs haven't been a thing on OS X for too long and were very rarely used. The only thing stopping this from happening is that `otool -l` output is slightly more annoying to parse than `otool -L` and there's no more convenient way (I'm aware of) to list the embedded RPATHs.

Depending on the urgency of this:

- We implement a solution now that uses `otool` and `install_name_tool` to perform the task.
- We wait until later this summer [`ruby-macho`](https://github.com/Homebrew/ruby-macho) learns to manipulate RPATHs and Homebrew switches to it for its Mach-O inspection and manipulation needs. At this point this feature will be trivial to implement as we'd be coding against a Ruby API. (`ruby-macho` is one of this year's Google Summer of Code projects.)

> Should the `RPATH` simply be deleted? I believe it's redundant with the absolute path `install_name` mechanism of finding shared libraries on Mac.

Probably, which is easy enough to do with `install_name_tool` once you know which path to remove. It would be good to collect a few formulae that use RPATHs and to check how they use them (also taking into account the state before our manipulation of `LC_*_DYLIB` load commands).

**Comment by UniqMartin** [comment]
> If none of the dependent libraries use `@rpath` in the `install_name`, then `RPATH` is not used and can be safely deleted.

That's not entirely correct. You'd have to inspect the full tree of dynamic dependencies, including libraries loaded via `dlopen` to make sure none of them depend on that particular RPATH in their `@rpath/`-prefixed dylib load commands. That's not even academic, as a frequent setup (at least in my experience) is that only the main executable contains the `LC_RPATH` load command and then all other dependencies rely on that and express their inter-dependencies using `@rpath/`-prefixed dylib load commands.

**Comment by sjackman** [comment]
Good clarification. Particularly the `dlopen` issue means that it's impossibly to determine statically whether the `RPATH` is used or not. So it's never safe to delete the `RPATH` without manual inspection, in which case it should be relocated using `@@HOMEBREW_CELLAR@@` like `install_name`.

**Comment by UniqMartin** [comment]
Of the 1959 Mach-O binaries in my Homebrew installation, only one has embedded RPATHs. Though that one is truly beautiful (the bottled `shellcheck` binary, it needs none of those):

```
/opt/homebrew/Cellar/shellcheck/0.4.4/bin/shellcheck:
  LC_LOAD_DYLIB=/usr/lib/libiconv.2.dylib
  LC_LOAD_DYLIB=/usr/lib/libSystem.B.dylib
  LC_RPATH=/usr/local/Cellar/shellcheck/0.4.4/lib/x86_64-osx-ghc-7.10.3/ShellCheck-0.4.4-Di0vBeJ5G22HeAaHhOLnuj
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/QuickCheck-2.8.2-8v0RiFeBskC7UIoPaBQj4x
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/array_67iodizgJQIIxYVTp4emlA
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/base_HQfYBxpPvuw8OunzQu6JGM
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/binar_3uXFWMoAGBg0xKP9MHKRwi
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/rts
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/bytes_6VWy06pWzJq9evDvK2d4w6
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/conta_2C3ZI8RgPO2LBMidXKTvIU
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/deeps_6vMKxt5sPFR0XsbRWvvq59
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/direc_0hFG6ZxK1nk4zsyOqbNHfm
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/filep_Ey7a1in9roBAE8bUFJ5R9m
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/ghcpr_8TmvWUcS1U1IKHT0levwg3
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/integ_2aU3IZNMF9a7mQ0OzsZ0dS
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/libexec/integer-gmp/lib
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/json-0.9.1-7kMKfrkn0Qy3BxYPUrdvN9
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/mtl-2.2.1-1XgQYjia7VJ5otlr6LA5f9
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/parsec-3.1.11-3g02YRopkV0859dUlfXjDZ
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/prett_JItwetRppk1H5Uq3xbjDGC
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/primitive-0.6.1.0-CanAn0ZmSDe1O8lK6kBSP2
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/proce_52AgREEfSrnJLlkGV9YZZJ
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/random-1.1-8PKo7QZOLuqJhOvzBKhJvd
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/regex-base-0.93.2-5g5YXZiScrKLs2R8SL8lg0
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/regex-tdfa-1.2.2-8NbBLGNW5Pf3YobyTLo8PR
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/syb-0.6-8Ynz83QzMazFTSpu5qYzrN
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/templ_GJPvtLC64aA4c1Jl10o2qt
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/text-1.2.2.1-8AnM1c81gDP9ebLwfSU223
  LC_RPATH=/private/tmp/shellcheck-20160515-52824-1fxs4fo/shellcheck-0.4.4/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.3/tf-random-0.5-FWUyVDgIgj9L0dx0uEV4dc
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/time_FTheb6LSxyX1UABIbBXRfn
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/trans_GZTjP9K5WFq01xC9BAGQpF
  LC_RPATH=/usr/local/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/unix_KZL8h98IqDM57kQSPo1mKx
```

I agree, we should probably clean them up and adjust the ones pointing into our prefix.

**Comment by sjackman** [comment]
Does `shellcheck` use `dlopen`? Otherwise I see only two `LC_LOAD_DYLIB` neither of which use `@rpath`.

`sailfish`, which has an `RPATH` but no `@rpath` uses, is built using `cmake`. Is the default behaviour to set `RPATH`, or is something amiss with `sailfish`?

**Comment by UniqMartin** [comment]
> Does `shellcheck` use `dlopen`? Otherwise I see only two `LC_LOAD_DYLIB` neither of which use `@rpath`.

No, not that I'm aware of. The libraries might exist in the given paths while `shellcheck` is built by the Glasgow Haskell compiler, but the end result is a statically linked binary that (as you correctly observed) only links to two system libraries. In any case, the binary is working fine though none of those paths specified in the `LC_RPATH` commands exist on my system.

> `sailfish`, which has an `RPATH` but no `@rpath` uses, is built using `cmake`. Is the default behaviour of `cmake` to set `RPATH`, or is something amiss with `sailfish`?

Sorry, I'm not familiar with `sailfish`, but I presume they decided to use RPATHs in their OS X builds to make relocating the binaries and/or libraries easier. Assuming it's a set of libraries, adding a new RPATH in a client binary is easier than adjusting all dylib load commands.

> I'm wondering whether all `cmake`-compiled executables are non-relocatable due to `RPATH`.

Certainly not. A non-trivial amount of my binaries was built by `cmake` and none of them contain any RPATHs. That's totally up to the upstream authors and what they do with their build systems …

**Comment by sjackman** [comment]
`sailfish` does not use `RPATH` on Mac OS to locate any of its libraries, even though `RPATH` is set. Delete its `RPATH` and it works just fine. Perhaps its `cmake` configuration is incorrect.

**Comment by sjackman** [comment]
> In any case, the binary is working fine though none of those paths specified in the LC_RPATH commands exist on my system.

`shellcheck` may be `cellar :any` if you delete all its `RPATH` entries, like `sailfish`.

**Comment by MikeMcQuaid** [comment]
> Perhaps its cmake configuration is incorrect.

I vaguely recall from my CMake days there may be a way to globally disable such things. If not globally, there will be a way my either passing in a config variable or patching an option in.

**Comment by UniqMartin** [comment]
> `sailfish` does not use `RPATH` on Mac OS to locate any of its libraries, even though `RPATH` is set.

So in this regard it is similar to my `shellcheck` example …

> `shellcheck` may be `cellar :any` if you delete all its `RPATH` entries, like `sailfish`.

Quite likely. I guess many of the formulae that are built with `ghc` might fall in that category, so that would be quite a win for relocatable bottles with a comparatively simple change.

**Comment by sjackman** [comment]
`pandoc`, also compiled by `ghc`, does not have any `RPATH`.

**Comment by MikeMcQuaid** [comment]
This has been improved as much as it will be for now. If this is still broken for you: we'll accept PRs for this but we're not actively working on it at this time.

**Comment by UniqMartin** [comment]
*Some additional information:* Once #656 ships, the `ruby-macho` backend for Mach-O manipulation will have full support for enumerating, adding, modifying, and deleting RPATHs. Once it becomes the default backend and the `cctools`-based implementation has been removed, we can start using these new features, e.g. remove bogus RPATHs that point to temporary locations or adjust those that point into the Homebrew prefix to further improve relocatability of bottles.

**Comment by sjackman** [comment]
Thanks, Martin!

**Comment by MikeMcQuaid** [comment]
@woodruffw 👍
