### ISSUE TITLE
New Feature: install/remove commands should append/remove from Brewfile

### ISSUE THREAD

**Issue by JeremyLoy** [Homebrew/brew#3716]
The Brewfile created by [homebrew-bundle](https://github.com/Homebrew/homebrew-bundle) is a great way to keep multiple development machines in-sync with each other (i.e. sysadmin managing a fleet or work/personal machines of a developer). Adding and removing to the Brewfile however, is a manual process that is slightly tedious. I think that `brew install` and `brew remove` should automatically edit your Brewfile (especially if you install something with tricky args and options).

## Why am I making the feature request here?
- The `brew install` and `brew remove` code exist here.
- This is a high level feature request that will probably involve changes in multiple repos. Having the root issue exist in the main repo makes sense, even if only for coordination

## Challenges
Here are a few that I have anticipated (I'm sure there are many, many more though):
- Not everyone uses Brewfile, so this should not be required (preferably automatic detection however).
- Where is it located?  `~/Brewfile`? what about `~/repos/dotfiles/Brewfile`? Everyone is different. It should be configurable

**Comment by MikeMcQuaid** [comment]
> Adding and removing to the Brewfile however, is a manual process that is slightly tedious.

`brew bundle dump` does it for you.

> I think that brew install and brew remove should automatically edit your Brewfile (especially if you install something with tricky args and options).

I'd definitely rather keep these commands separate. You could do so with a Bash alias/script/function for yourself, though.
