### ISSUE TITLE
`brew uses --installed foo` gives results that conflict with `brew remove foo`

### ISSUE THREAD

**Issue by telemachus** [Homebrew/brew#3730]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

Output of `brew config` and `brew doctor` are [here](https://gist.github.com/telemachus/05cc52e2ada3c8a99f88dc489e4630ef).

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to check if any installed software depended on curl. (I do this because I want to see what I need to remove in order to update something. I also do it to avoid exactly what happens below, namely `brew` refusing to remove something unless I enter `--ignore-dependencies`.)

- What happened (include command output)

`brew` says that nothing depends on curl, but then refuses to uninstall curl because git depends on curl.

``` shell
$ brew uses --installed curl
$ brew remove curl
Error: Refusing to uninstall /usr/local/Cellar/curl/7.57.0
because it is required by git 2.16.1, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies curl
```
- What you expected to happen

I expected `brew uses --installed curl` to tell me that git uses curl.

- Step-by-step reproduction instructions (by running `brew` commands)

``` shell
brew uses --installed curl # assuming you have something that uses curl installed
brew remove curl
```

**Comment by alyssais** [comment]
IIRC This happens because `brew uninstall` (which `brew remove` is an alias for) checks the dependencies of the installed version of the formula, whereas `brew uses` checks dependencies of the current version.

I think we should change `brew uses --installed` (not `brew uses` generally) so that it works the same way.

Will leave to see if any other maintainers have thoughts.

**Comment by telemachus** [comment]
@alyssais Thanks for this explanation.

> I think we should change brew uses --installed (not brew uses generally) so that it works the same way.

Another possible thought: I wonder if `brew uses --installed` should be a distinct single command  rather than a subcommand invoked via a flag. I can't speak for other people, but I use `brew uses --installed` far, far more often than `brew uses`. So I've always wanted a simpler way to call it. A split here, given the semantics you're describing, might make sense.

If people think this makes sense, I'm happy to work on a PR.

**Comment by ilovezfs** [comment]
This works as designed, which has been the conclusion each time it comes up. Thanks for raising the issue, though, @telemachus

**Comment by telemachus** [comment]
I should have searched the issues better. For future googlers: the answer seems to be `brew uses --installed --include-optional`.

See here: https://github.com/Homebrew/brew/issues/3512
