### ISSUE TITLE
Error: Xcode alone is not sufficient on Sierra.

### ISSUE THREAD

**Issue by pptaj** [Homebrew/brew#3732]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ /] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [/ ] Ran `brew update` and retried your prior step?
- [ /] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ /] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
   I have been trying to install vault using "brew install vault"
   I checked the previous issues reported by others, and none of it helped.
    https://github.com/Homebrew/brew/issues/3456
    https://github.com/Homebrew/brew/pull/3453
    It says that the issue has been fixed, but nothing seems to be helping.

- What happened (include command output)
   taj.palecanda:~ $ brew install vault
  Error: Xcode alone is not sufficient on Sierra.
  Install the Command Line Tools:
  xcode-select --install

   taj.palecanda:~ $ xcode-select --install
   xcode-select: error: command line tools are already installed, use "Software Update" to install 
   updates
- What you expected to happen
   Have vault installed without complaining about xcode.

- Step-by-step reproduction instructions (by running `brew` commands)
   taj.palecanda:~ $ brew update
Already up-to-date.
taj.palecanda:~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Warning: Xcode alone is not sufficient on Sierra.
Install the Command Line Tools:
  xcode-select --install

taj.palecanda:~ $ brew install vault
Error: Xcode alone is not sufficient on Sierra.
Install the Command Line Tools:
  xcode-select --install

taj.palecanda:~ $ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
taj.palecanda:~ $ brew config
HOMEBREW_VERSION: 1.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 60a30e966b7cece5bd4823dae3fb981ab85106ea
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 18e00f7fa9e010f86da02c8ef32b6a634f7de04a
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_151, 1.7.0_45
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: N/A
X11: N/A

**Comment by MikeMcQuaid** [comment]
Download them from https://developer.apple.com. Don't create new issues because you didn't fill out the old one and it was closed.

**Comment by pptaj** [comment]
@MikeMcQuaid I did download xcode from https://developer.apple.com. It's still complaining.

**Comment by MikeMcQuaid** [comment]
You need the command line tools, not Xcode.

**Comment by pptaj** [comment]
Thank you, @MikeMcQuaid!
