### ISSUE TITLE
htop and pandoc fail to upgrade on High Sierra

### ISSUE THREAD

**Issue by brennan724** [Homebrew/brew#3733]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [?] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) -- brew upgrade all of my brewed programs (after brew update), including htop and pandoc
- What happened (include command output) -- picture below (pandoc error occurred a week ago, and I neglected to take a screenshot)
- What you expected to happen -- I expected it to upgrade.
- Step-by-step reproduction instructions (by running `brew` commands) -- brew update, brew upgrade

Screenshot of issue (for htop, result of 'brew upgrade'):
<img width="547" alt="image" src="https://user-images.githubusercontent.com/8431570/35410313-4f935800-0215-11e8-8b5b-7109bc06a9a7.png">

Brew Config:
<img width="989" alt="image" src="https://user-images.githubusercontent.com/8431570/35410281-32411eae-0215-11e8-9649-32bfde470cca.png">

Brew doctor says the system is ready to brew.

**Comment by scpeters** [comment]
From

https://github.com/Homebrew/homebrew-core/blob/27b9c65d4a6f4a476213965b1400000bdcbb80b5/Formula/htop.rb#L23-L25

"Running htop can lead to system freezes on macOS 10.13" https://github.com/hishamhm/htop/issues/682

**Comment by brennan724** [comment]
Turns out there's a reason htop doesn't upgrade on High Sierra!  Hopefully it gets fixed soon.
https://github.com/Homebrew/homebrew-core/blob/master/Formula/htop.rb#L23

I'm mistaken about pandoc, and it now has been upgraded on my system since it last threw the error.
