### ISSUE TITLE
Brew cask prints 'Warning: Calling <<-EOS.undent is deprecated!'

### ISSUE THREAD

**Issue by DanielThomas** [Homebrew/brew#3738]
When running `brew cask list` (and other `cask` commands), it outputs:

	Warning: Calling <<-EOS.undent is deprecated!
	Use <<~EOS instead.
	/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:94:in `block in load'

## `brew config`

	HOMEBREW_VERSION: 1.5.2
	ORIGIN: https://github.com/Homebrew/brew
	HEAD: 60a30e966b7cece5bd4823dae3fb981ab85106ea
	Last commit: 2 days ago
	Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
	Core tap HEAD: 9c8a9a07a7d90b494a4ccd08885ec235c46aa223
	Core tap last commit: 20 minutes ago
	HOMEBREW_PREFIX: /usr/local
	CPU: octa-core 64-bit skylake
	Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
	Clang: 9.0 build 900
	Git: 2.16.1 => /usr/local/bin/git
	Curl: 7.54.0 => /usr/bin/curl
	Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
	Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
	Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0/bin/ruby
	Java: 9.0.4, 1.8.0_162, 1.7.0_80, 1.6.0_65-b14-468
	macOS: 10.13.3-x86_64
	Xcode: N/A
	CLT: 9.2.0.0.1.1510905681
	X11: N/A

## `brew doctor`

	Your system is ready to brew.

## `brew cask doctor`

	==> Homebrew-Cask Version
	Homebrew-Cask 1.5.2
	caskroom/homebrew-cask (git revision f5732; last commit 2018-01-26)
	==> macOS
	10.13.3
	==> SIP
	Enabled
	==> Java
	9.0.4, 1.8.0_162, 1.7.0_80, 1.6.0_65-b14-468
	==> Homebrew-Cask Install Location
	<NONE>
	==> Homebrew-Cask Staging Location
	/usr/local/Caskroom
	==> Homebrew-Cask Cached Downloads
	~/Library/Caches/Homebrew/Cask
	==> Homebrew-Cask Taps:
	/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3902 casks)
	==> Contents of $LOAD_PATH
	/usr/local/Homebrew/Library/Homebrew/cask/lib
	/usr/local/Homebrew/Library/Homebrew
	/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
	/Library/Ruby/Site/2.3.0
	/Library/Ruby/Site/2.3.0/x86_64-darwin17
	/Library/Ruby/Site/2.3.0/universal-darwin17
	/Library/Ruby/Site
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
	==> Environment Variables
	LC_ALL="en_US.UTF-8"
	PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
	SHELL="/usr/local/bin/zsh"

**Comment by alyssais** [comment]
Can you run this and post the output please?

```sh
grep -RIF .undent "$(brew --repo)"
```

**Comment by patrickmcc** [comment]
Mine too, as your requested here's the outputs.

> patrickmcc@patricks-macbook-pro [01:16:31] [~]
> -> % grep -RIF .undent "$(brew --repo)"
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-nginx/Formula/nginx-full.rb:  def passenger_caveats; <<-EOS.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-nginx/Formula/nginx-full.rb:    s = <<-EOS.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-nginx/Formula/nginx-full.rb:  def plist; <<-EOS.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-nginx/Formula/openresty-debug.rb:  def plist; <<-EOS.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-nginx/Formula/openresty.rb:  def plist; <<-EOS.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:  def plist; <<-EOPLIST.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Requirements/php-meta-requirement.rb:    <<-EOLTEXT.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php70-ref.rb:    <<-EOT.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/composer@1.2.rb:    <<-EOT.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dev-tools/cmd/brew-go-resources.rb:  puts <<-EOS.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd/brew-alias.rb:        f.write <<-EOF.undent
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd/brew-unalias.rb:        f.write <<-EOF.undent
> /usr/local/Homebrew/Library/Homebrew/compat/extend/string.rb:    odeprecated "<<-EOS.undent", "<<~EOS"
> /usr/local/Homebrew/Library/Homebrew/compat/extend/string.rb:  #   if foo then <<-EOS.undent_________________________________________________________72
>

**Comment by DanielThomas** [comment]
What I get is:

	grep -RIF .undent "$(brew --repo)"
	/usr/local/Homebrew/Library/Homebrew/compat/extend/string.rb:    odeprecated "<<-EOS.undent", "<<~EOS"
	/usr/local/Homebrew/Library/Homebrew/compat/extend/string.rb:  #   if foo then <<-EOS.undent_________________________________________________________72
	grep: /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/fuse/osxfuse.pc: No such file or directory
	grep: /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/fuse/fuse.pc: No such file or directory

**Comment by alyssais** [comment]
Could you try `brew pull https://github.com/Homebrew/brew/pull/3742` and then running `brew cask list` again? Should give a more helpful error message.

**Comment by DanielThomas** [comment]
# brew pull https://github.com/Homebrew/brew/pull/3742
	Warning: Current branch is stable: do you need to pull inside master?
	==> Fetching patch
	Patch: https://github.com/Homebrew/brew/pull/3742.patch
	######################################################################## 100.0%
	==> Applying patch
	Applying: Include path in error message when cask load fails
	==> Patch closes issue #3742
	==> Patch changed:
	 Library/Homebrew/cask/lib/hbc/cask_loader.rb | 3 +++
	 1 file changed, 3 insertions(+)
	# brew cask list
	Warning: Calling <<-EOS.undent is deprecated!
	Use <<~EOS instead.
	/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:94:in `block in load'

	1password                     firefox-developer-edition     java6                         spotify
	alfred                        google-chrome                 java7                         steam
	android-sdk                   google-drive                  java8                         sublime-text
	bartender                     istat-menus                   jetbrains-toolbox
	docker                        iterm2                        processing
	dropbox                       java                          slack

**Comment by paulp** [comment]
This is caused by files hiding in `/usr/local/Caskroom/*/.metadata`. In my case, the java and java8 casks both used undent in caveats. Before/after:
```diff
-  caveats <<-EOS.undent
+  caveats <<~EOS
     This Cask makes minor modifications to the JRE to prevent issues with
     packaged applications, as discussed here:
```
It suffices to remove the .metadata directory, it will be regenerated.

**Comment by justinchuch** [comment]
@paulp Great tips!

In my case, I did `grep -irn "EOS.undent" .` under `/usr/local/Caskroom` 
and found out that java7 casks used undent.

For curiosity, I made a `brew update` and ran `grep -irn --include=*.rb "EOS.undent" .` under `/usr/local`

`
./Cellar/ant/1.9.8/.brew/ant.rb:28:    (bin/"ant").write <<-EOS.undent
./Cellar/ant/1.9.8/.brew/ant.rb:45:    (testpath/"build.xml").write <<-EOS.undent
./Cellar/ant/1.9.8/.brew/ant.rb:57:    (testpath/"src/main/java/org/homebrew/AntTest.java").write <<-EOS.undent
./Cellar/cloc/1.74/.brew/cloc.rb:39:    (testpath/"test.c").write <<-EOS.undent
./Cellar/graphviz/2.40.1/.brew/graphviz.rb:93:    (testpath/"sample.dot").write <<-EOS.undent
./Cellar/libevent/2.1.8/.brew/libevent.rb:30:    (testpath/"test.c").write <<-EOS.undent
./Cellar/libpng/1.6.34/.brew/libpng.rb:28:    (testpath/"test.c").write <<-EOS.undent
./Cellar/openjpeg/2.3.0/.brew/openjpeg.rb:26:    (testpath/"test.c").write <<-EOS.undent
./Cellar/pixman/0.34.0_1/.brew/pixman.rb:21:    (testpath/"test.c").write <<-EOS.undent
./Cellar/readline/7.0.3_1/.brew/readline.rb:22:  keg_only :shadowed_by_osx, <<-EOS.undent
./Cellar/readline/7.0.3_1/.brew/readline.rb:34:    (testpath/"test.c").write <<-EOS.undent
./Cellar/tmux/2.6/.brew/tmux.rb:44:  def caveats; <<-EOS.undent
./Homebrew/Library/Homebrew/compat/extend/string.rb:3:    odeprecated "<<-EOS.undent", "<<~EOS"
./Homebrew/Library/Homebrew/compat/extend/string.rb:9:  #   if foo then <<-EOS.undent_________________________________________________________72
./Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-cask-0.16.0/spec/rubocop/cop/cask/stanza_grouping_spec.rb:176:          caveats <<-EOS.undent
./Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-cask-0.16.0/spec/rubocop/cop/cask/stanza_order_spec.rb:229:          caveats <<-EOS.undent
./opt/ant/.brew/ant.rb:28:    (bin/"ant").write <<-EOS.undent
./opt/ant/.brew/ant.rb:45:    (testpath/"build.xml").write <<-EOS.undent
./opt/ant/.brew/ant.rb:57:    (testpath/"src/main/java/org/homebrew/AntTest.java").write <<-EOS.undent
./opt/cloc/.brew/cloc.rb:39:    (testpath/"test.c").write <<-EOS.undent
./opt/graphviz/.brew/graphviz.rb:93:    (testpath/"sample.dot").write <<-EOS.undent
./opt/libevent/.brew/libevent.rb:30:    (testpath/"test.c").write <<-EOS.undent
./opt/libpng/.brew/libpng.rb:28:    (testpath/"test.c").write <<-EOS.undent
./opt/openjpeg/.brew/openjpeg.rb:26:    (testpath/"test.c").write <<-EOS.undent
./opt/pixman/.brew/pixman.rb:21:    (testpath/"test.c").write <<-EOS.undent
./opt/readline/.brew/readline.rb:22:  keg_only :shadowed_by_osx, <<-EOS.undent
./opt/readline/.brew/readline.rb:34:    (testpath/"test.c").write <<-EOS.undent
./opt/tmux/.brew/tmux.rb:44:  def caveats; <<-EOS.undent
./var/homebrew/linked/ant/.brew/ant.rb:28:    (bin/"ant").write <<-EOS.undent
./var/homebrew/linked/ant/.brew/ant.rb:45:    (testpath/"build.xml").write <<-EOS.undent
./var/homebrew/linked/ant/.brew/ant.rb:57:    (testpath/"src/main/java/org/homebrew/AntTest.java").write <<-EOS.undent
./var/homebrew/linked/cloc/.brew/cloc.rb:39:    (testpath/"test.c").write <<-EOS.undent
./var/homebrew/linked/graphviz/.brew/graphviz.rb:93:    (testpath/"sample.dot").write <<-EOS.undent
./var/homebrew/linked/libevent/.brew/libevent.rb:30:    (testpath/"test.c").write <<-EOS.undent
./var/homebrew/linked/libpng/.brew/libpng.rb:28:    (testpath/"test.c").write <<-EOS.undent
./var/homebrew/linked/openjpeg/.brew/openjpeg.rb:26:    (testpath/"test.c").write <<-EOS.undent
./var/homebrew/linked/pixman/.brew/pixman.rb:21:    (testpath/"test.c").write <<-EOS.undent
./var/homebrew/linked/tmux/.brew/tmux.rb:44:  def caveats; <<-EOS.undent
./var/homebrew/pinned/ant/.brew/ant.rb:28:    (bin/"ant").write <<-EOS.undent
./var/homebrew/pinned/ant/.brew/ant.rb:45:    (testpath/"build.xml").write <<-EOS.undent
./var/homebrew/pinned/ant/.brew/ant.rb:57:    (testpath/"src/main/java/org/homebrew/AntTest.java").write <<-EOS.undent
`

Thank you.

**Comment by DomT4** [comment]
@MikeMcQuaid We need to ignore that `.metadata` directory in the same way we do the `.brew` one inside formula prefixes presumably, or this will keep being an issue for people. I'd submit a PR but I'm not sure quite where to start with Cask stuff 😓.
