### ISSUE TITLE
Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool on macOS Developer Preview

### ISSUE THREAD

**Issue by gjmveloso** [Homebrew/brew#374]
I've seeing an error when trying to run `brew doctor`on **macOS Sierra** _Developer Preview_.

>➜  ~ brew doctor
Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool

Per recent commits seems like you guys are working on supporting macOS soon but it's still unsupported. Is this right?

Thanks

**Comment by DomT4** [comment]
That usually means you haven't accepted the license agreement. Try `sudo xcodebuild -license`, agree to that, and then re-run `brew`.

**Comment by ilovezfs** [comment]
I imagine brew could probably print a better message.

**Comment by DomT4** [comment]
We already attempt to in `brew.sh`, `brew doctor` and our `xcrun` wrapper but evidently we still miss a few cases.

**Comment by gjmveloso** [comment]
Worked like a charm @DomT4 😃 

Thanks,
Gustavo

**Comment by gjmveloso** [comment]
With beta 2 of macOS Sierra I've started receiving this message when running ```sudo xcodebuild -license```:

```
~ sudo xcodebuild -license                   
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Thoughts?

Thanks.

**Comment by MikeMcQuaid** [comment]
That's not a Homebrew issue. I suspect you don't have Xcode installed which means that command wont' work.

**Comment by DomT4** [comment]
@gjmveloso That's expected. The `xcodebuild` command only works if your active developer directory is the Xcode installation. You're not supposed to see CLT license issues; when you install it via MAS or the `.pkg` installer you should be given the license dialog at install.

**Comment by bryceadams** [comment]
Try `xcode-select --install` instead @gjmveloso

**Comment by davidkinghorn** [comment]
Thanks bryceadams, you saved me a lot of effort.
I still think it is dumb that I need the objective c development environment (xcode) when I just want the runtime environment, which is already installed - ie jdk vs jre in java land, but then apple has always been one to "think different" :)
