### ISSUE TITLE
ansible: `brew audit` said 'revision 2' can be removed, what gives?

### ISSUE THREAD

**Issue by MindTooth** [Homebrew/brew#3743]
Figured I could begin submitting fixes to packages that gets tagged by `brew audit`.
The first issue were for Ansible, stating I could remove revision 2 from the formula.
Seeing the log, ilovezfs changed to the new syntax for depends_on – meaning a new rev is required I presume.

So, what causes this, can it be fixed, or should it be ignored?  Just from a wannabe contributor.

**Comment by MikeMcQuaid** [comment]
Ensure you don't have a shallow clone which may return invalid returns for that check. Also, please always fill out the issue template in future.

**Comment by MindTooth** [comment]
My bad 👎  Sorry.

Ran `git -C $(brew --repo homebrew/core) fetch --unshallow` yesterday though.

I'll figure it out.  Thank you for at least replying.
