### ISSUE TITLE
`brew audit` seems broken

### ISSUE THREAD

**Issue by makigumo** [Homebrew/brew#3753]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
```
$ brew update
Already up-to-date.
```
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config
HOMEBREW_VERSION: 1.5.2-37-g701ecb4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 701ecb49755d9be3f4c40ce979814027cda1c479
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 77c0a955851b9effb01cc77816eb47bac317e999
Core tap last commit: 89 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_VISUAL: /usr/local/bin/atom
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0/bin/ruby
Java: 9.0.4, 1.8.0_162
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libeb.16.dylib
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Running `brew audit --strict mariadb@10.0` for a PR to homebrew-core.

- What happened (include command output)
The following error message was shown.
```sh
$ brew audit --strict mariadb@10.0
Error: The 'rubocop' gem is installed but couldn't find 'rubocop' in the PATH:
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin:/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/bin:/bin:/usr/sbin:/sbin
```

- What you expected to happen
Successfully running `brew audit` with some result.

- Step-by-step reproduction instructions (by running `brew` commands)
`brew audit --strict mariadb@10.0`

**Comment by MikeMcQuaid** [comment]
`gem uninstall --force rubocop` and run `brew audit` again.

**Comment by makigumo** [comment]
Thx, your suggestion didn't work. But removing `~/.gem` did the trick.
