### ISSUE TITLE
Install stalling out 

### ISSUE THREAD

**Issue by jalanar9** [Homebrew/brew#3755]
Question - I am trying to install the 'fftw' package but I am stalling out at this point: 

==> Patching
==> Applying 6.1.0-jit.patch
patching file gcc/jit/Make-lang.in
==> ../configure --build=x86_64-apple-darwin14.5.0 --prefix=/usr/local/Cellar/gcc/7.3.0 --libdir=/usr/local/Cellar/gcc/7.3.0/
==> make

Has someone experienced this before? 

Thanks!

![snip20180131_1](https://user-images.githubusercontent.com/36025246/35662564-9eb39e06-06cd-11e8-92d8-872edc0331ff.png)

**Comment by scpeters** [comment]
Please read these relevant sections of the issue template:

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
