### ISSUE TITLE
installing brew - fatal: The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by anonym24** [Homebrew/brew#3756]
Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
fatal: The remote end hung up unexpectedly
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
Mac-Pro-USER:~ MacOSX$

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.
