### ISSUE TITLE
brew update & brew upgrade error 'Error: Could not find any assets'

### ISSUE THREAD

**Issue by yash0281** [Homebrew/brew#3759]
I am trying to run brew update and brew upgrade but I keep encountering Error: Could not find any assets.

~ → brew update
Updated 7 taps (caskroom/cask, caskroom/versions, drone/drone, homebrew/core, homebrew/science, johanhaleby/kubetail, pivotal/tap).
==> New Formulae
ballerina                      drone/drone/drone@0.8.0        libbitcoin-consensus           shelltestrunner
...
==> Updated Formulae
elasticsearch ✔                           freeradius-server                         node
...
==> Renamed Formulae
ssreflect -> math-comp                                         tachyon -> alluxio
==> Deleted Formulae
mg3a                     mvptree                  pcap_dnsproxy            qt@5.7                   talk-filters
Error: Could not find any assets

~ → brew upgrade
Updating Homebrew...
Error: Could not find any assets

~ → brew config
HOMEBREW_VERSION: 1.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 60a30e966b7cece5bd4823dae3fb981ab85106ea
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d46a3d04dc8b44d9a16fe31bbb7dd2e71e110759
Core tap last commit: 71 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.1 build 802
Git: 2.15.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/z00290g/miniconda3/bin/python => /Users/z00290g/miniconda3/bin/python3.6
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 9.0.1, 1.8.0_152, 1.8.0_101
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 9.2.0.0.1.1510905681
X11: N/A

~ → brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/z00290g/miniconda3/bin/python3-config
  /Users/z00290g/miniconda3/bin/python3.6-config
  /Users/z00290g/miniconda3/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.6m/pygame/_camera.h
  /usr/local/include/python3.6m/pygame/_pygame.h
  /usr/local/include/python3.6m/pygame/_surface.h
  /usr/local/include/python3.6m/pygame/bitmask.h
  /usr/local/include/python3.6m/pygame/camera.h
  /usr/local/include/python3.6m/pygame/fastevents.h
  /usr/local/include/python3.6m/pygame/font.h
  /usr/local/include/python3.6m/pygame/freetype.h
  /usr/local/include/python3.6m/pygame/mask.h
  /usr/local/include/python3.6m/pygame/mixer.h
  /usr/local/include/python3.6m/pygame/pgarrinter.h
  /usr/local/include/python3.6m/pygame/pgbufferproxy.h
  /usr/local/include/python3.6m/pygame/pgcompat.h
  /usr/local/include/python3.6m/pygame/pgopengl.h
  /usr/local/include/python3.6m/pygame/pygame.h
  /usr/local/include/python3.6m/pygame/scrap.h
  /usr/local/include/python3.6m/pygame/surface.h
Error: Could not find any assets

**Comment by MikeMcQuaid** [comment]
Please run `brew doctor --debug --verbose` and post your output here. Thanks!

**Comment by yash0281** [comment]
z00290g$ brew doctor --debug --verbos
Checking check_access_cache
Checking check_access_cellar
Checking check_access_homebrew_repository
Checking check_access_lock_dir
Checking check_access_logs
Checking check_access_prefix_directories
Checking check_access_site_packages
Checking check_brew_git_origin
Checking check_build_from_source
Checking check_clt_minimum_version
Checking check_clt_up_to_date
Checking check_coretap_git_origin
Checking check_dyld_vars
Checking check_filesystem_case_sensitive
Checking check_for_anaconda
Checking check_for_bad_curl
Checking check_for_bad_install_name_tool
Checking check_for_bad_python_symlink
Checking check_for_beta_xquartz
Checking check_for_config_scripts
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/z00290g/miniconda3/bin/python3-config
  /Users/z00290g/miniconda3/bin/python3.6-config
  /Users/z00290g/miniconda3/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config
Checking check_for_enthought_python
Checking check_for_external_cmd_name_conflict
Checking check_for_gettext
Checking check_for_git
Checking check_for_iconv
Checking check_for_installed_developer_tools
Checking check_for_library_python

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
Checking check_for_multiple_volumes
Checking check_for_non_prefixed_coreutils
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb
Checking check_for_non_prefixed_findutils
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb
Checking check_for_old_homebrew_share_python_in_path
Checking check_for_osx_gcc_installer
Checking check_for_other_frameworks
Checking check_for_other_package_managers
Checking check_for_pth_support
Checking check_for_pydistutils_cfg_in_home
Checking check_for_stray_developer_directory
Checking check_for_stray_dylibs
Checking check_for_stray_headers

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.6m/pygame/_camera.h
  /usr/local/include/python3.6m/pygame/_pygame.h
  /usr/local/include/python3.6m/pygame/_surface.h
  /usr/local/include/python3.6m/pygame/bitmask.h
  /usr/local/include/python3.6m/pygame/camera.h
  /usr/local/include/python3.6m/pygame/fastevents.h
  /usr/local/include/python3.6m/pygame/font.h
  /usr/local/include/python3.6m/pygame/freetype.h
  /usr/local/include/python3.6m/pygame/mask.h
  /usr/local/include/python3.6m/pygame/mixer.h
  /usr/local/include/python3.6m/pygame/pgarrinter.h
  /usr/local/include/python3.6m/pygame/pgbufferproxy.h
  /usr/local/include/python3.6m/pygame/pgcompat.h
  /usr/local/include/python3.6m/pygame/pgopengl.h
  /usr/local/include/python3.6m/pygame/pygame.h
  /usr/local/include/python3.6m/pygame/scrap.h
  /usr/local/include/python3.6m/pygame/surface.h
Checking check_for_stray_las
Checking check_for_stray_pcs
Checking check_for_stray_static_libs
Checking check_for_symlinked_cellar
Checking check_for_tap_ruby_files_locations
Checking check_for_unlinked_but_not_keg_only
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/drone/homebrew-drone/Formula/drone.rb
Error: Could not find any assets
/usr/local/Homebrew/Library/Taps/drone/homebrew-drone/Abstract/abstract-drone.rb:31:in `assets'
/usr/local/Homebrew/Library/Taps/drone/homebrew-drone/Abstract/abstract-drone.rb:7:in `init'
/usr/local/Homebrew/Library/Taps/drone/homebrew-drone/Formula/drone.rb:4:in `<class:Drone>'
/usr/local/Homebrew/Library/Taps/drone/homebrew-drone/Formula/drone.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1002:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:999:in `reject'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:999:in `check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:46:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
zsh: no such file or directory: /Users/z00290g/.rvm/bin/rvm-prompt

**Comment by alyssais** [comment]
This looks like a problem with the drone/drone tap. Please report it there.
