### ISSUE TITLE
Feature request: Discovery system for brews

### ISSUE THREAD

**Issue by forthrin** [Homebrew/brew#3762]
There are thousands of brews, but it's only by *accident* I discover new and useful ones, either from personal recommendations or a spontaneous `brew info` on a curious brew name after an update.

A lot of brews are programming tools (like `cairo`, useful only for Python developer), whereas everyday tools like `googler` and `ncdu` have a wider appeal, but there is no systematic way of discovering them.

Imagine the following:

1. A categorisation system, which separates "general tools", "code tools", "games", etc.
2. A popularity value per brew (eg. number of downloads, number of contributors)
3. A discovery function which shows vital information about the most popular brew you haven't seen, lets you install it or mark it as "not interesting" in a file like `~/.seen-brews` and show the next one.

```
$ brew discover general
ncdu -- NCurses Disk Usage (65K downloads, 1348 contributors)
An interactive tool which helps you find and delete huge files on your hard drive
[h] = Show home page [i] = Install and show next [n] = Skip and show next
```

This way a lot more useful brews would reach a lot more users, rather than stumbling over them by random, or worse, never knowing about them at all.

**Comment by MikeMcQuaid** [comment]
Please fill out the feature request part of the issue template in future.

Sorry, we're not interested in maintaining categories at this time. The number of downloads is available at https://brew.sh/analytics/install-on-request/

**Comment by forthrin** [comment]
The category part is not essential to the feature request. It would be quite simple to make a `brew discover` function which lets the user eliminate his way through the list you referenced.
