### ISSUE TITLE
undefined method `[]' for nil:NilClass when duplicate tap

### ISSUE THREAD

**Issue by meritozh** [Homebrew/brew#3769]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

`brew cleanup`

- What happened (include command output)

```
Error: undefined method `[]' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:185:in `block in initialize'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:183:in `map'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:183:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:377:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:377:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:308:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `installed'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:31:in `cleanup_cellar'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:15:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:22:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

If we add a new tap which content is same as existing one (we transfer our tap repo from GitLab to GitHub), we must untap the existing one first. Otherwise, any other brew sub command that will check formula will raise an exception. code is here: https://github.com/Homebrew/brew/blob/af8f8f11e32fe78677fc1d4cd62c07a29dc6d326/Library/Homebrew/formulary.rb#L377

Unfortunately, seems homebrew can not catch and solve this properly.

**Comment by MikeMcQuaid** [comment]
> If we add a new tap which content is same as existing one (we transfer our tap repo from GitLab to GitHub), we must untap the existing one first. Otherwise, any other brew sub command that will check formula will raise an exception. code is here:

Can you elaborate exactly what commands you've used to reproduce this ideally with public taps and that works on a clean installation (or at least installation with neither of them tapped). Thanks!

**Comment by meritozh** [comment]
Run `brew tap gitlab/homebrew-tools <git_repo_url>` first, **do not untap this**, then just run `brew tap github-ee/dev-tools <git_repo_url>`. Two repo are exactly same but hosted on different instance. Then, run `brew cleanup`, raise an exception. Only `rm -rf <path-to-gitlab/homebrew-tools>` manually can solve the problem.

**Comment by ilovezfs** [comment]
You'll need to give step by step commands using public taps. Since those are private taps, your instructions are not possible to reproduce.

**Comment by ilovezfs** [comment]
I think the problem here is actually that the path to your tap isn't matching the tap regex.

```
bash-3.2$ brew irb
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
irb(main):001:0> path = Pathname.new("/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wget.rb")
=> #<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wget.rb>
irb(main):002:0> match = path.to_s.match(HOMEBREW_TAP_PATH_REGEX)
=> #<MatchData "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wget.rb" user:"homebrew" repo:"homebrew-core">
irb(main):003:0> 
```

What are the actual file system tap paths in your case?

**Comment by meritozh** [comment]
My tap match the tap regex, I sure. Because we just use `gitlab/homebrew-tools` for several months.

I mean brew should address the raised exception properly when user add another tap which is same as existing one. This problem only produced when there are two **same** content tap but exist in different path.

**Comment by ilovezfs** [comment]
I'm afraid we cannot help you with the amount of information you're providing.
