### ISSUE TITLE
Mac "brew update" fails immediately with SSL problems

### ISSUE THREAD

**Issue by joshuawhite929** [Homebrew/brew#3770]
To help us debug your issue please explain:
- What you were trying to do (and why)
    Looking to run "brew update".  This command fails with SSL errors.  See "Example Output" below.
- What happened (include command output)
    See "Example Output" below.
- What you expected to happen
    Expected "brew update" to work as usual.
- Step-by-step reproduction instructions (by running `brew` commands)
    Simply run "brew update".  The command fails immediately.  See "Example Output".

**Background:**
Our corporation uses a web gateway that rewrites certificates with our own internal certificate.  I have a CA I could add, but not clear what needs to be done.  It is already installed/trusted in the Mac Keystore.

**Example Output:**
```
fatal: unable to access 'https://github.com/cloudfoundry/homebrew-tap/': SSL: invalid CA certificate #1 (offset 0) in bundle
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': SSL: invalid CA certificate #1 (offset 0) in bundle
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': SSL: invalid CA certificate #1 (offset 0) in bundle
Error: Fetching /usr/local/Homebrew/Library/Taps/cloudfoundry/homebrew-tap failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask failed!
```

**Brew Config:**
HOMEBREW_VERSION: 1.5.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 985202cf8e3f9e221753dd99adf1e8874fece03a
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ad61dfd51fb20fafe16da7418b9f2fb58bdf6dde
Core tap last commit: 3 weeks ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0/bin/ruby
Java: 9.0.1, 1.8.0_151
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A

**Brew Doctor:**
Your system is ready to brew.

**Comment by MikeMcQuaid** [comment]
You'll need to figure this out yourself, sorry.

**Comment by joshuawhite929** [comment]
Brew provides very little information.  Can you at least share what brew is using under the covers for retrieving resources (curl, wget, other)?

**Comment by MikeMcQuaid** [comment]
`man brew` explains that `git` and `curl` are used.
