### ISSUE TITLE
brew leaves results in an Error

### ISSUE THREAD

**Issue by pattulus** [Homebrew/brew#3771]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:

- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
    - ↑↑↑ at least I think so, if not I'll ask on homebrew-core if you tell me to ↑↑↑
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

🍺💊:

    $ brew doctor
    Your system is ready to brew.

🍺⚙:

    $ brew config
    HOMEBREW_VERSION: 1.5.3
    ORIGIN: https://github.com/Homebrew/brew
    HEAD: af8f8f11e32fe78677fc1d4cd62c07a29dc6d326
    Last commit: 27 hours ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: c276cb9c54ad0cc7a2c6e3a6ae1a6a9c771bd69a
    Core tap last commit: 58 minutes ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_CASK_OPTS: --appdir=/Applications --fontdir=~/Dropbox/Fonts
    HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
    CPU: octa-core 64-bit ivybridge
    Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
    Clang: 9.0 build 900
    Git: 2.16.1 => /usr/local/bin/git
    Curl: 7.54.0 => /usr/bin/curl
    Perl: /usr/bin/perl
    Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
    Ruby: /Users/patte/.rbenv/shims/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
    Java: 1.8.0_121, 1.8.0_60
    macOS: 10.13.2-x86_64
    Xcode: 9.2
    CLT: 9.2.0.0.1.1510905681
    X11: 2.7.11 => /opt/X11

To help us debug your issue please explain:

- What you were trying to do (and why)
    
    Just tried to do `brew leaves`. But…

        $ brew leaves
        Error: No available formula with the name "gmp@4"

- What happened (include command output)

`gmp@4` was listed in my `brew list` output. I did a `brew uninstall gmp@4` after reading it got removed from brews core.

- What you expected to happen

Not seeing the error, but installed formulae that are not dependencies of another installed formula. My `brew list`:

```
ack             faac            gobject-introspection libffi        libyaml        pandoc       sqlite
advancecomp     fdk-aac         gpac                  libgcrypt     little-cms     pcre         ssh-copy-id
autoconf        ffmpeg          gpg-agent             libgpg-error  little-cms2    pinentry     stow
automake        findutils       graphite2             libidn2       lua            pixman       switchaudio-osx
avr-binutils    flac            grep                  libksba       mad            pkg-config   tag
avr-gcc         fontconfig      harfbuzz              libmagic      makedepend     pngcrush     terminal-notifier
bash            freetype        highlight             libmatroska   mas            pngquant     texi2html
bash-completion frei0r          icu4c                 libmpc        media-info     ppl011       theora
bfg             fribidi         id3tool               libmpc08      mkvtoolnix     ppl@0.11     tidy
bison           gawk            imagemagick           libmpc@0.8    movgrab        pth          tidy-html5
boost           gcc             imgcat                libogg        mp3info        python       todo-txt
cabal-install   gcc@4.9         isl                   libpng        mpfr           python3      tor
cairo           gd              isl@0.12              libqalculate  mpfr2          qpdf         torsocks
choose-gui      gdbm            jasper                libsndfile    mpfr@2         ranger       unison
chromaprint     gettext         jbig2dec              libsoxr       nasm           rbenv        webkit2png
clamz           ghc             jpeg                  libssh        node           readline     webp
cln             ghc@8.0         jpegoptim             libssh2       objective-caml recode       wget
cloog           ghostscript     jq                    libtiff       ocaml          remind       x264
cloog-ppl015    gifsicle        lame                  libtool       oniguruma      rtmpdump     x265
cloog@0.15      gist            libass                libunistring  opencore-amr   ruby-build   xmlstarlet
coreutils       git             libassuan             libusb        openjpeg       schroedinger xvid
dateutils       git-archive-all libbluray             libusb-compat openssl        sdl2         xz
dfu-programmer  glib            libbs2b               libvidstab    openssl@1.1    shellcheck   yasm
dirmngr         gmp             libcaca               libvo-aacenc  optipng        snappy       youtube-dl
emacs           gnu-sed         libebml               libvorbis     opus           sox          zeromq
exiftool        gnuplot         libevent              libvpx        orc            speex
```

Other things I tried to: 

   xcode-select --install
   brew upgrade

… this was after reading the [common issues section in the docs](https://docs.brew.sh/Common-Issues.html#upgrading-macos).

I also reinstalled Homebrew. Didn't fix the issue.

Out of desperation I tried to reinstall `gmp@4`:

    $ brew install gmp@4
    Error: No available formula with the name "gmp@4"
    ==> Searching for a previously deleted formula (in the last month)...
    gmp@4 was deleted from homebrew/core in commit 8de2fabd2b:
      gmp@4: remove

    To show the formula before removal run:
      git -C "$(brew --repo homebrew/core)" show 8de2fabd2b^:Formula/gmp@4.rb

    If you still use this formula consider creating your own tap:
      https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html

I feel a bit like a noob now, not nowing how to fix this.

**Comment by ilovezfs** [comment]
```
brew rm -f --ignore-dependencies cloog cloog@0.15 gcc@4.6 gcc@4.7 gcc@4.8 gcc@4.9 isl@0.11 isl@0.12 libmpc@0.8 mpfr@2 ppl@0.11
```
and it should go away

**Comment by pattulus** [comment]
Thanks. `brew leaves` works again.

I went through all the dependencies yesterday comparing them with other dependencies and dependents of other formulas and felt really lost after this because there where intersections in a lot of places. _(Basically I spend the whole day trying to remove formulas and get a clearer picture… I should have asked earlier.)_

The removal looked drastic on paper, but so far everything works like a charm. If not there's always `brew install --only-dependencies <troublesome formula>`. Thanks again.
