### ISSUE TITLE
brew install --interactive: put args in an environment variable for convenience

### ISSUE THREAD

**Issue by carlorosati** [Homebrew/brew#3776]
# Motivation

I am frequently debugging `brew install --build-from-source` build failures. When I `brew install --debug <formula>` and get to the interactive shell, I have to scroll back up the terminal to see how the formula was `./configure`d. Usually the ./configure line is truncated and I have to rerun with the verbose flag to see all of the `./configure` arguments. 

After I successfully `./configure`, I would like to either let the brew formula continue after the configure or let me know what subsequent commands it would issue (e.g. make bootstrap).

# Proposed Solution

## First steps

To make debugging --interactive installs more convenient, the configure args could be stored in an environment variable such as `HOMEBREW_CONFIGURE_ARGS`. 

## Further generalization

To take this idea further, (a more) interactive mode could stop before executing each command (seen preceded by `==> `) and prompt the user to continue to the next command or instead drop down into a shell. If the user chooses to drop into the shell, an environment variable `HOMEBREW_COMMAND_ARGS` could be set and possibly another for the executable such as `HOMEBREW_COMMAND`. After the user exits this shell homebrew will continue through the process.

Thoughts?

**Comment by MikeMcQuaid** [comment]
There's no way really of doing this generically internally. I'm open to other solutions to this problem though. Sorry!

**Comment by carlorosati** [comment]
Is monkey-patching Kernel::system to intercept the ruby system calls out of the question?

**Comment by MikeMcQuaid** [comment]
Yes, sorry.
