### ISSUE TITLE
Maybe provide more build system options with `brew diy`

### ISSUE THREAD

**Issue by fredemmott** [Homebrew/brew#3777]
# Please always follow these steps:
-[x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

Can't do brew doctor due to local admins; hopefully not necessary for a feature request though.

Brew config: https://gist.github.com/fredemmott/75d04828cd7e54e9dbd584ba9bd72fb0

## What you were trying to do (and why)

Manually build master of hhvm with some local changes, inside `brew sh` using `brew diy` to get some configuration.

## What happened (include command output)

```
$ cd $(mktemp -d)
$ touch CMakeLists.txt
$ brew diy --name=foo --version=1.2.3
-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/foo/1.2.3
```

## What you expected to happen

That's what I expected, but it would be nice if there was some extra standard configuration - for example, this would be nice:

```
$ brew diy --name=foo --version=1.2.3
-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/foo/1.2.3 -DCMAKE_INSTALL_SYSCONFDIR=/usr/local/etc
```

## Step-by-step reproduction instructions (by running `brew` commands)

Above.

# Features

## a detailed description of your proposed feature

Automatically configure standard directories with brew diy as listed on:
 - https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html
 - 'Variables for directory locations' on https://github.com/Homebrew/brew/blob/230d630bd6cfd5ec9d317c83caea66a03d2b6c10/docs/Formula-Cookbook.md

## the motivation for the feature

Do 'the right thing' by default.

## how the feature would be relevant to at least 90% of Homebrew users

Given it's in `brew diy`, it probably isn't.

## What alternatives to the feature you have considered

Going through the list and manually specifying

> We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

Understandable, but I probably won't be sending a PR; involves some legal process on my end :(

**Comment by MikeMcQuaid** [comment]
> Understandable, but I probably won't be sending a PR; involves some legal process on my end :(

Given this isn't widely usable I'm closing this out but if anyone sees this and it's closed and wants to send a PR: we'd consider accepting it.
