### ISSUE TITLE
brew cleanup doesn't clean ~/Library/Caches/Homebrew

### ISSUE THREAD

**Issue by galad87** [Homebrew/brew#3784]
I noticed brew keeps a copy of the files it downloads in  ~/Library/Caches/Homebrew , and the "brew doctor" command doesn't clean it.

For example:

> [damians@iMac ~]$ brew cleanup
Removing: /usr/local/Cellar/ffmpeg/3.4.1... (248 files, 50.9MB)
Removing: /usr/local/Cellar/x264/r2795... (11 files, 3.2MB)
==> This operation has freed approximately 54.1MB of disk space.

And in the Cache folder there are still:

> [damians@iMac ~]$ ls ~/Library/Caches/Homebrew
ffmpeg-3.4.1_1.high_sierra.bottle.tar.gz  x264-r2854.high_sierra.bottle.tar.gz

**Comment by chdiza** [comment]
`man brew` will show you the `-s` flag for `cleanup`.

Even then, `cleanup` doesn't always get everything.

**Comment by vitorgalvao** [comment]
The `cleanup` section of `brew`’s `man` page (emphasis mine):

> For all installed or specific formulae, remove  any older  versions from the cellar. In addition, old downloads from the Homebrew download-cache are deleted.
>
> If --prune=days is specified, remove all cache files older  than days.
>
> If --dry-run or -n is passed, show what would be removed, but do not actually remove anything.
>
> If -s is passed, scrub the cache, removing  downloads  for  even the latest  versions  of  formulae. **Note downloads for any installed formulae will still not be deleted.  If  you  want  to delete those too: rm -rf $(brew --cache)**

This is expected behaviour. If you want to remove *everything*, run the suggested `rm` command.

**Comment by galad87** [comment]
Thanks for the answer. What's the use of keeping already installed formulae downloads files around?

**Comment by chdiza** [comment]
In case something goes wrong and you have to reinstall.

**Comment by vitorgalvao** [comment]
Closing issue as solved (clarified).

**Comment by MikeMcQuaid** [comment]
@galad87 In future **always, always, always fill out the issue template**, please.
