### ISSUE TITLE
Won't install?

### ISSUE THREAD

**Issue by frobuddyharry** [Homebrew/brew#3790]
Whenever I put the install command in it shows > and doesn't do anything. I waited several minutes yet it didn't install or do a single thing.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

Also, please ask any questions in Discourse rather than the issue tracker.
