### ISSUE TITLE
Skip repository option for brew update

### ISSUE THREAD

**Issue by StephenWeber** [Homebrew/brew#3794]
I would like to be able, as a user, to choose one or more repositories to skip during a `brew update`. The feature's flag would accept one or more repository names and would simply bypass them in the update loop.

My motivation for this is that some of my tapped repositories are behind a VPN, and I don't always want to bother if I'm just looking to update the main homebrew repository. Current behavior tries to update the tapped repo, fails after a timeout, and continues with the other repositories.

Other possible motivations (that are not my own):
- a tapped repo may have an issue the user is not ready/able to fix
- a tapped repo may have many updates and the user is not ready to become current

Alternatives to this feature could include:
- a hook per-repo that would allow a command to be run (that in my case would check if the VPN is connected)
- do nothing, `brew update` continues successfully and the few seconds I have to wait once a week is acceptable

**Comment by scpeters** [comment]
I usually do `cd $(brew --repo) && git pull` (or `git -C $(brew --repo) pull`) if I just want to update `brew` but not the taps.

**Comment by MikeMcQuaid** [comment]
Please read and fill out the issue template in future, we do ask you to do so. In that specifically it asks you to explain how this is relevant to >90% of Homebrew users. This feature isn't so I'd recommend what @scpeters suggests and writing a script for yourself that `git pull`s your repos of preference. Sorry!

**Comment by StephenWeber** [comment]
Yup, didn't think it met the 90% bar but appreciate being considered!
