### ISSUE TITLE
homebrew.bintray.com repository issue in Iran

### ISSUE THREAD

**Issue by sojoudian** [Homebrew/brew#3796]
I am an Iranian user of brew it seems we have problem with homebrew.bintray.com repository maybe it's related to the sanction or "something else" so, is there any other repository for brew?

**Comment by MikeMcQuaid** [comment]
There is not any other official repository, sorry.

**Comment by sojoudian** [comment]
As I know brew is using github sometimes, how can I force brew to download packages from github ?

**Comment by MikeMcQuaid** [comment]
You can't. It'll fall back to building from source on e.g. GitHub when downloads fail from Bintray.
