### ISSUE TITLE
Broken pipe on brew search

### ISSUE THREAD

**Issue by jwadolowski** [Homebrew/brew#380]
Every time I execute `brew search` I get the following error:

```
$ brew search curl
curl curlish curlpp flickcurl
Error: Broken pipe
```

Noticed that couple days ago. Was working perfectly fine so far.

It seems that's not just myself, as I found this when googled this error: http://stackoverflow.com/questions/37690560/homebrew-brew-seach-returns-broken-pipe-error (raised 11 days ago)

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by jwadolowski** [comment]
Thanks for that @MikeMcQuaid. It was actually really helpful.

I run `brew doctor` and there were some issues on my Mac:

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /opt/chefdk/embedded/bin/curl-config
    /opt/chefdk/embedded/bin/ncurses5-config
    /opt/chefdk/embedded/bin/ncursesw5-config
    /opt/chefdk/embedded/bin/pcre-config
    /opt/chefdk/embedded/bin/pkg-config
    /opt/chefdk/embedded/bin/xml2-config
    /opt/chefdk/embedded/bin/xslt-config

Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /opt/chefdk/embedded/bin/pkg-config

`./configure` may have problems finding brew-installed packages using
this other pkg-config.

Warning: Broken symlinks were found. Remove them with `brew prune`:
    /usr/local/bin/chef-zero
    /usr/local/bin/fauxhai
```

All of them are related to ChefDK and apparently Chef team is already aware of that:
https://github.com/chef/chef-dk/issues/745
https://github.com/chef/chef-dk/issues/313

ChefDK seems to interfere with `brew`, as it provides a separate set of `ruby` binaries that are added to `$PATH`. Without `chefdk` package `brew search` works perfectly fine.
