### ISSUE TITLE
Brew install SHA256 mismatch on zabbix 2.4.6 (OSX)

### ISSUE THREAD

**Issue by pg07gordon** [Homebrew/brew#3804]
Getting a SHA256 mismatch on zabbix 2.4.6 on OSX Sierra.

Ran:
brew update --force
brew cleanup

Tried on two different iMacs, with fresh brew installs.

Bash command: brew install --without-server-proxy zabbix

Output:
==> Downloading https://downloads.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/3.4.6/zabbix-3.4.6.tar.gz
==> Downloading from https://downloads.sourceforge.net/#!/project/zabbix/ZABBIX%20Latest%20Stable/3.4.6/zabbix-3.4.6.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 2c261f967fece8f0f930bc07876e37debdf7a903f65a3a222aed5ba5fc724d6a
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Library/Caches/Homebrew/zabbix-3.4.6.tar.gz
To retry an incomplete download, remove the file above.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

It also should have been filed to homebrew-core.
