### ISSUE TITLE
Interactive brew install (search + info + install)

### ISSUE THREAD

**Issue by tsutsu** [Homebrew/brew#3816]
## Motivation

It's currently a rather fraught process to translate the simple knowledge that there exists a piece of software called `foo`, into an attempt to get that software installed using Homebrew, if you don't already know the exact incantation to do so from the software's website.

You can _guess_ that software named `foo` would likely end up with the formula name `foo`—but this is risky, especially for installing casks, because there might be several different packages named `foo` and some earlier one might have taken precedence (consider someone typing `brew cask install sublime`, expecting to get Sublime Text!) `brew install` doesn't tell you _which_ `foo` it's about to install, so you can't cancel the process.

As well, if you're slightly off about the name (consider, for example, the various names the "native Facebook Messenger client" cask formulae are published under—nobody could guess these on their first try from the name of the app alone) `brew install` won't help you. It will do a search, but this search won't find the same results that `brew search` will, because (AFAIK) the matching algorithm isn't quite the same.

So, if you want to try to install a potentially-existent Homebrew formula, knowing only that it exists as software on the Internet and that Homebrew _probably_ packages it, the best practice right now seems to be the following:

* `brew search foo` to figure out if Homebrew contains anything _like_ a formula with the provided name;
* `brew info foo1`, `brew info foo2`, etc. to figure out which of the matches is the package you actually want;
* `brew install foo1` to actually install that package.

## Proposal

I would like to propose a configuration switch for `brew install` be added, `--interactive` or `-i`, which would do the following:

1. perform a (fuzzy) search for the provided formula name;
2. print the matching formulae, one per line, in this format:

```
[sequence number]. [formula name] - [formula description field] ([formula URL field])
```

3. Then, depending on the number and type of matches found:

- if there was one match, just prompt:

```
Install this formula? [n]
```

- otherwise, if there were multiple matches, first print this additional option line:

```
n. none of these
```

- then, if there was more than one match, where match 1 was an exact match:

```
Install which formula? [1]
```

- or, if there was more than one match, but with no exact matches:

```
Install which formula? [n]
```

- or, finally, if there were no matches, print "No matches" but exit with a 0 status (because this is a success, like `brew search nonexistingformula`; not a failure, like `brew install nonexistingformula`).

## Potential Usage

Probably everybody who uses Homebrew has at one point tried (and maybe failed!) to install a package in the fashion described under the Motivation section.

**Comment by MikeMcQuaid** [comment]
> brew install won't help you. It will do a search, but this search won't find the same results that brew search will, because (AFAIK) the matching algorithm isn't quite the same.

I don't understand your reasoning here; what makes you think they are taking a different approach?

> brew install be added, --interactive or -i,

This already exists.

---

Passing on this I'm afraid; I can't see it being widely used and Homebrew has a policy to never prompt the user.
