### ISSUE TITLE
brew install php56 – error: unable to remove file: Operation not permitted

### ISSUE THREAD

**Issue by derweili** [Homebrew/brew#3823]
I have a error while trying to install php56.

I'm running macOS 10.12.6

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
no issues: Your system is ready to brew.

- [x] ran `brew config` and `brew doctor` and included their output with your issue?

*brew config:*
HOMEBREW_VERSION: 1.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 021fe22e3c982b08346422d1e7897e929a709380
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7679dc9b1226235c927bdcf6dfca4d8cbb571b81
Core tap last commit: 19 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_131
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11

*brew doctor:*
Your system is ready to brew.

**To help us debug your issue please explain:**
- What you were trying to do (and why)
I was tryint to install php56 as decribed in this tutorial: https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions
`brew install php56 --with-httpd`
I already reinstalled homebew.

- What happened (include command output)
```
…
error: error reading '/dev/fd/7'
1 error generated.
clang: error: unable to remove file: Operation not permitted
dtrace: failed to compile script /private/tmp/php56-20180221-46555-z4wo25/php-5.6.33/Zend/zend_dtrace.d: Preprocessor failed to process input program
make: *** [Zend/zend_dtrace_gen.h] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
Installing php55 and php56 makes my mac terminal dead https://github.com/Homebrew/homebrew-php/issues/4602
php56-mongodb _clock_gettime error at runtime https://github.com/Homebrew/homebrew-php/issues/3737
```

- What you expected to happen
I expected php to install correctly

- Step-by-step reproduction instructions (by running `brew` commands)
`brew install php56 --with-httpd`

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
Report this to Homebrew/php (as noted by the issue template).
