### ISSUE TITLE
Homebrew : python module dependency 

### ISSUE THREAD

**Issue by aeantipov** [Homebrew/brew#383]
Hi, while preparing a package for homebrew-science, the following problem has occured. 
The package depends on some python modules, yet doing 
```
depends_on :python => 'mako'
```
does nothing and the ``install`` step is starting to execute, resulting in an error, which typically reads something like `ImportError: No module named mako.template`. 
How do I fix that? I tried looking through both issues at homebrew or homebrew-science, but found nothing. 

Doing 
`system "pip install --upgrade mako"` fixes it, but it does not look like the best practice.

**Comment by UniqMartin** [comment]
I'm not very familiar with this feature of Homebrew when handling Python dependencies, but I believe what you intended to do is, i.e. you mixed up the order of `"mako"` and `:python`:

```ruby
depends_on "mako" => :python
```

**Comment by tdsmith** [comment]
Martin's right, but don't use that construct; it just tells you to pip install the thing :) You may find this guide helpful: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md

**Comment by aeantipov** [comment]
Thanks!
