### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by nikoladev** [Homebrew/brew#3832]
[This commit](https://github.com/Homebrew/brew/commit/e63a2ee8de12f0f938f6a95cdb9763dbe0187b4a) changed all the links in the [docs](https://github.com/Homebrew/brew/blob/master/docs/README.md) and now they are all broken on Github (404 not found).

Example old link: https://github.com/Homebrew/brew/blob/master/docs/Manpage.md

Example new (broken) link: https://github.com/Homebrew/brew/blob/master/docs/Manpage

The easiest fix seems to be to revert the commit, unless the change was done for a specific reason?

---

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

**Comment by MikeMcQuaid** [comment]
I want to fix this without reverting immediately. Note that https://docs.brew.sh are considered the official docs; if we're linking to not-them anywhere, let me know. Out of interest: ow did you end up on https://github.com/Homebrew/brew/blob/master/docs/Manpage.md?

**Comment by nikoladev** [comment]
Yeah, if these are not the official docs, that makes sense :)

I got linked to the [docs readme](https://github.com/Homebrew/brew/blob/master/docs/README.md) from [this post](https://apple.stackexchange.com/questions/97065/how-do-i-write-a-homebrew-recipe/97205#97205).

**Comment by MikeMcQuaid** [comment]
@nikoladev Cool, thanks!
