### ISSUE TITLE
brew search doesn't show all matches for casks

### ISSUE THREAD

**Issue by jgefele** [Homebrew/brew#3834]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

$ brew config
HOMEBREW_VERSION: 1.5.4-88-g650d6db
ORIGIN: https://github.com/Homebrew/brew
HEAD: 650d6dbaac625a758881a215a35d8d4a248de5bf
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 75a516d87b3d8c944085195395e4727ecd09f69a
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

I was searching for a virtual midi keyboard. As I didn't have a specific application in mind I just typed:
```
$ brew search midi
==> Searching local taps...
abcmidi       midicsv         portmidi     rtmidi    timidity
==> Searching taps on GitHub...
caskroom/cask/midi-monitor
==> Searching blacklisted, migrated and deleted formulae...
```
Oh, it's not in homebrew. By chance I also typed:
```
$ brew cask search midi
==> Partial Matches
midi-monitor    midikeys        midistroke         miditrail
```
Wait... there's much more listed than in the section `Searching taps on GitHub... caskroom/cask...`.

If `brew search midi` lists casks then I would expect it to list all the matching casks, not just some of them. It's the same with `anti`: it finds `f-secure-anti-virus` but not `atlantis`, `avg-antivirus`, and `avira-antivirus`.

**Comment by dimonixx** [comment]
I have the same issue with php70-intl extension

**Comment by stvhwrd** [comment]
As it stands now, `cask` has its own `search.rb` at [`brew/Library/Homebrew/cask/lib/hbc/cli/search.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/cli/search.rb) which behaves differently and independently of `brew`'s `search.rb` at [`brew/Library/Homebrew/cmd/search.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/search.rb)

I'm guessing this is just a vestige of casks being a late adoption by Homebrew (?)

When user runs `brew search` it checks formulas first, and then checks other taps.  It treats Casks as just another tap.  I think it's fair game to address this since Caskroom is now integrated with Homebrew itself (or more specifically, it's a default tap).

My teammate @harpreetsingh91 and I are looking into this.

**Comment by stvhwrd** [comment]
@dimonixx can you explain in greater detail what you tried, and what occurred?

**Comment by dimonixx** [comment]
Hi @stvhwrd 

i had several php extensions which i installed like this `brew install php70-intl` 

now i can't find these extensions anymore. Looks like something is broken in my homebrew installation

**Comment by edalzell** [comment]
@dimonixx intl is built into core php now.

**Comment by dimonixx** [comment]
i've installed `php@7.1` and still get the following message `Please install the "intl" extension for full localization capabilities.` Also in `php -i` i can't find `intl`. Am i doing smth. wrong ?

**Comment by vitorgalvao** [comment]
@dimonixx Please open a new issue. Your problem has nothing to do with this issue.

**Comment by MikeMcQuaid** [comment]
@reitermarkus What's the latest here?

**Comment by vitorgalvao** [comment]
This is now fixed.

```
$ brew search midi
==> Formulae
abcmidi         midicsv         portmidi        rtmidi          timidity

==> Casks
midi-monitor        midikeys            midistroke          miditrail
```
```
$ brew search anti
==> Formulae
antigen                                  antiword

==> Casks
atlantis                   font-antic-didone          font-quantico
avg-antivirus              font-antic-slab            font-shanti
avira-antivirus            font-antinoou              font-uncial-antiqua
f-secure-anti-virus        font-glass-antiqua
font-antic                 font-modern-antiqua
```

Can you confirm it works as expected for you, @jgefele?

**Comment by jgefele** [comment]
Yes. It works. Thank you!
