### ISSUE TITLE
Cannot specify S3DownloadStrategy for bottle URLs

### ISSUE THREAD

**Issue by eedwards-sk** [Homebrew/brew#3838]
Homebrew 1.5.4-88-g650d6db
Homebrew/homebrew-core (git revision 50dc; last commit 2018-02-26)

Currently using S3DownloadStrategy to allow downloading source distributions from a private S3 bucket.

Attempting to bottle my private distributions and download them in the same way.

Using a local file works fine, so the bottling process is great.

However, attempting to use an S3 URL fails.

e.g. specifying an S3 url without any additional modifiers:

```
  bottle do
    root_url "https://my-s3-bucket.s3.amazonaws.com/path-to/1.0"
    cellar :any_skip_relocation
    sha256 "[big-long-sha-that-I-redacted]" => :high_sierra
  end
```

```
→ brew install myorg/private/my-thing-1.0
==> Installing my-thing-1.0 from myorg/private
==> Downloading https://my-s3-bucket.s3.amazonaws.com/path-to/1.0/my-thing-1.0-1.0.0.high_sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "my-thing-1.0"
Download failed: https://my-s3-bucket.s3.amazonaws.com/path-to/1.0/my-thing-1.0-1.0.0.high_sierra.bottle.tar.gz
```

Now, for shits and giggles, attempted to use the `, :using => S3DownloadStrategy` modifier on the bottle definition.

```
  bottle do
    root_url "https://my-s3-bucket.s3.amazonaws.com/path-to/1.0", :using => S3DownloadStrategy
    cellar :any_skip_relocation
    sha256 "[big-long-sha-that-I-redacted]" => :high_sierra
  end
```

However, as suspected, this appears to be unsupported.

```
→ brew install myorg/private/my-thing-1.0
Error: wrong number of arguments (given 2, expected 0..1)
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:336:in `root_url'
/usr/local/Homebrew/Library/Taps/myorg/homebrew-private/Formula/my-thing-1.0.rb:10:in `block in <class:MyThing10>'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:100:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:100:in `bottle'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2086:in `bottle'
/usr/local/Homebrew/Library/Taps/myorg/homebrew-private/Formula/my-thing-1.0.rb:9:in `<class:MyThing10>'
/usr/local/Homebrew/Library/Taps/myorg/homebrew-private/Formula/my-thing-1.0.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:45:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:43:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:43:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:115:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

My use case is that I would like to leverage the same functionality that homebrew uses for allowing S3 downloads from source URLs, to also download bottles.

Is there an explicit reason that this is currently unsupported?

I'm happy to attempt to write a PR to add this functionality if it's not going against any 'core tenants' of homebrew.

I'd like to open source some of the tooling I'm working on, but being forced to publicly host bottles is not currently something I can support.

Thanks!

**Comment by eedwards-sk** [comment]
Trying to walk the code to figure out where the relevant sections are.

I'm suspecting this area would need to be touched to support S3DownloadStrategy.

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/software_spec.rb
```
class Bottle
<...>
  def initialize(formula, spec)
    @name = formula.name
    @resource = Resource.new
    @resource.owner = formula
    @spec = spec

    checksum, tag = spec.checksum_for(Utils::Bottles.tag)

    filename = Filename.create(formula, tag, spec.rebuild)
    @resource.url(build_url(spec.root_url, filename))
    @resource.download_strategy = CurlBottleDownloadStrategy
    @resource.version = formula.pkg_version
    @resource.checksum = checksum
    @prefix = spec.prefix
    @cellar = spec.cellar
    @rebuild = spec.rebuild
  end
<...>
end
```

Specifically,
```
resource.download_strategy = CurlBottleDownloadStrategy
```

download_strategy appears to be hardcoded to CurlBottleDownloadStrategy

I suspect we would need to be able to pass additional spec flags to the root_url `bottle` block inside the function def, supporting the `:using => S3DownloadStrategy` flag, and then when set, changing the `download_strategy` either during initialization or before downloading.

Since it's already using a 'DownloadStrategy', it seems like it might be somewhat straightforward to support another already-implemented strategy like S3.

Thoughts?

**Comment by MikeMcQuaid** [comment]
We'd consider accepting a PR for this but it's not considered a bug at this time.

**Comment by eedwards-sk** [comment]
@MikeMcQuaid Thank you so much for your response.

I created pr #3841 in an attempt to address this.

Any comments or suggestions on it would be appreciated.

Thanks for making Homebrew great!
