### ISSUE TITLE
brew installs an old version of XCode Command Line tools

### ISSUE THREAD

**Issue by fabianhenzler** [Homebrew/brew#3842]
installing brew with the provided cmd line `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"?` results in installing an old version of the XCode Command Line Tools, even though the latest version is installed

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by fabianhenzler** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I'm installing brew with the `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
- What happened (include command output)
Within the installation the installer wants to install the XCode 8.2 Commandlinetools, even though I have XCode 9.2 and the XCode 9.2 Commandlinetools already installed. The old tools get overwritten and I have to update them afterwards again 
- What you expected to happen
That the latest XCode Commandlinetools get installed if there are none installed on the system or nothing happens if XCode >=8.2 Commandlinetools are already installed, because the prerequisites are met
- Step-by-step reproduction instructions (by running `brew` commands)
The issues occurs within the installation of homebrew

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
> Within the installation the installer wants to install the XCode 8.2 Commandlinetools, even though I have XCode 9.2 and the XCode 9.2 Commandlinetools already installed. The old tools get overwritten and I have to update them afterwards again

We install from the Mac App Store so not sure what's going on there. We'd accept a pull request to fix the issue, though. Thanks!
