### ISSUE TITLE
Allow user to set HOMEBREW_CELLAR

### ISSUE THREAD

**Issue by cpcallen** [Homebrew/brew#3849]
- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# Detailed description of feature

Allow the user to specify the value of `HOMEBREW_CELLAR` by setting an environment variable of the same name.

# Motivation for the feature

In my organisation, mandatory access controls prevent Homebrew from functioning normally if installed with `HOMEBREW_PREFIX=/usr/local`; instead, we normally install it in `~/Homebrew` or `/usr/local/brew` instead.

Unfortunately, an unrelated system integrity protection system prevents executing any locally-compiled binaries or pre-built binaries installed anywhere other than the default path of `/usr/local/Cellar`.

# Alternative solutions

Two solutions are in use but neither is satisfactory:

   * Manually patch `brew.sh` with a hardcoded value for `HOMEBREW_CELLAR`, then set `HOMEBREW_NO_UPDATE_CLEANUP=1` to try to preserve this hack when `brew` updates itself, or
   * Symlink `$HOMEBREW_PREFIX/Cellar` to point at `/usr/local/Cellar`

The first is an ugly and fragile hack; the second causes avoidable `brew doctor` warnings and actually prevents installation (without `--force`) of certain bottles such as `openssl` that complain the Cellar is not in its default location (despite it *actually* being there).

# Relevancy

This is probably only of interest to a small minority of users, but the change is trivial (see PR #3850) and potentially useful to anyone who needs to maintain a non-standard configuration.

**Comment by MikeMcQuaid** [comment]
> In my organisation, mandatory access controls prevent Homebrew from functioning normally if installed with HOMEBREW_PREFIX=/usr/local; instead, we normally install it in ~/Homebrew or /usr/local/brew instead.
> 
> Unfortunately, an unrelated system integrity protection system prevents executing any locally-compiled binaries or pre-built binaries installed anywhere other than the default path of /usr/local/Cellar.

This is an issue with your organisation's macOS configuration and not with Homebrew, sorry.

**Comment by cpcallen** [comment]
Indeed: that's why this is a feature request (with working implementation, no less), not a bug report.

**Comment by MikeMcQuaid** [comment]
@cpcallen My more blunt explanation: your organisation wants to use Homebrew but also wants to configure their macs so that Homebrew cannot be used in the supported configuration. This requires a change for your organisation and not a change for Homebrew.

**Comment by MikeMcQuaid** [comment]
@cpcallen If you organisation is who it appears to be from your GitHub profile: as Homebrew is used widely inside your large organisation we may be willing to support use-cases that are useful to them in exchange for financial or resource support for Homebrew.
