### ISSUE TITLE
In macOS 10.12 Sierra, /usr/local is readonly.

### ISSUE THREAD

**Issue by mrgaolei** [Homebrew/brew#385]
I ran `sudo chown -R $(whoami) $(brew --prefix)`

But it also prompt me:
```
Error: /usr/local must be writable!
```

I think that macOS 10.12 rootless is also in /usr/local
What should I do?

**Comment by MikeMcQuaid** [comment]
@mrgaolei `sudo chown -R $(whoami) /usr/local`.

**Comment by 2pravin7** [comment]
Thanks... @MikeMcQuaid ! It worked
