### ISSUE TITLE
Analytics for packages beyond top 1000 

### ISSUE THREAD

**Issue by ahmetb** [Homebrew/brew#3856]
https://brew.sh/analytics/install/ shows install events for only top 1000 formulae.

Is there a way to learn stats about my formula which is likely not in top 1000?

**Comment by commitay** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh

**Comment by MikeMcQuaid** [comment]
@ahmetb Just noticed this. This now shows more than 1000 and has for a wee while now! Enjoy!
