### ISSUE TITLE
Brew error with  'No such file or directory'

### ISSUE THREAD

**Issue by Kota-R** [Homebrew/brew#3857]
OS version: 10.13.3

Until 2 weeks ago, I could use brew properly, but right now I could not use brew any longer as every brew command yields the following error:

"env: Workbooks.app/Contents/SharedSupport/path-bin: No such file or directory'"

Maybe error is due to the update of OS. But I do not know how to fix this error.

**Comment by alyssais** [comment]
> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
