### ISSUE TITLE
brew update is destructive linking python3 to python

### ISSUE THREAD

**Issue by PhDuck** [Homebrew/brew#3859]
I just did "brew update" which did the following:

==> Migrating python3 to python
==> Unlinking python3
==> Unlinking python
==> Moving python3 children
==> Linking python

I'm sure that python3 makes sense to use and is the future, but why is this change made without 
prompting the user for input? This is potentially a breaking change that can affect systems.
Furthermore the semantics of running brew update is now blurred; what am I to expect when running the command?

**Comment by ilovezfs** [comment]
This changed was announced in January https://brew.sh/2018/01/19/homebrew-1.5.0/

If you need Python 2, `brew install python@2`

**Comment by MikeMcQuaid** [comment]
Also: please always, always read and fill out the issue template. It tells you to do so.

> why is this change made without prompting the user for input?

No Homebrew change ever prompts the user for input.

**Comment by kevwil** [comment]
> This is potentially a breaking change that can affect systems.
Furthermore the semantics of running brew update is now blurred; what am I to expect when running the command?

I'd love to know the answer to this as well. How should a user guard against unexpected breaking changes? And once broken, how should users proceed and get back to getting work done?

**Comment by MikeMcQuaid** [comment]
> How should a user guard against unexpected breaking changes?

In progressing levels of effort (the lowest level of which would have been sufficient in this case):

1. read our blog posts through the RSS feed or our Twitter feed (or the front page of Hacker News where they normally end up)
2. watch our repository and read pull requests that seem relevant to your organisation
3. watch our repository and test pull requests that seem relevant to your organisation before they are merged
4. create your own tap or fork of Homebrew/homebrew-core for formulae you wish to never be changed

> how should users proceed and get back to getting work done?

That's on you to figure out. We're volunteers running a project that you're using to "get work done" i.e. make money. Our license clearly states we disclaim all warranties and the software is available as-is. Note, your organisation could consider donating money to our project which would provide more resources to make it easier for us to do additional automated testing.

**Comment by MikeMcQuaid** [comment]
And to be clear:



> This is potentially a breaking change that can affect systems.

This is definitely a breaking change. That's why we gave you a month and a half's notice on our primary communication mechanisms (blog on our homepage, our Twitter) to adapt to this change. If you did not do so: that's on you, not us, sorry.

**Comment by MikeMcQuaid** [comment]
@kevinwaddle Would you like to explain your 👎 or would you like to just demotivate the maintainers to this project through drive-by negativity?

**Comment by kevinwaddle** [comment]
I think you are coming off angry and arrogant in your replies to this.  I think this is an issue that should be handled, and the users helped, with less arrogance and negativity from *your* side as well.
