### ISSUE TITLE
sha256 test fails some pages (e.g. duply)

### ISSUE THREAD

**Issue by arbyter** [Homebrew/brew#3866]
Hi folks,

I tried to upgrade duply via brew (brew upgrade duply). All the time it fails with the message _"Error: SHA256 mismatch"_. I uninstalled duply and tried  to reinstall it: same result.
I downloaded the linked file manually and did a checksum test (shasum -a 265 $filenme). The result matches the excepted checksum in the formula. So where is the problem?

---
```
brew config

HOMEBREW_VERSION: 1.5.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 08f7e8c5887d1c654a1a5d5bc851a9c9d5a00371
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6d0671eeb68ff5a32df38eb5a7011814d47683c0
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 9.0.4
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: N/A
X11: 2.7.11 => /opt/X11
```

```
brew doctor

Your system is ready to brew.
```

```
brew install duply

==> Downloading https://downloads.sourceforge.net/project/ftplicity/duply%20%28simple%20duplicity%29/
Already downloaded: /Users/marcus/Library/Caches/Homebrew/duply-2.0.4.tgz
Error: SHA256 mismatch
Expected: efa450b976ff94d29b8f22b99d98aae108e032186c01ffdc526c85c87813048c
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/marcus/Library/Caches/Homebrew/duply-2.0.4.tgz
To retry an incomplete download, remove the file above.
```

**Comment by alyssais** [comment]
> To retry an incomplete download, remove the file above.

Have you tried this?

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

> - [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new.

Please do both of these things in future.

If you still get this error after removing that file and retrying, please open at issue at Homebrew/homebrew-core, making sure to fill out the issue template **in full**.

**Comment by arbyter** [comment]
Thanks for your reply. I removed the file and downloaded it again with the same result.

I reported this issues to this single case but I noticed it on other formula as well.
