### ISSUE TITLE
Homebrew-and-Python seems all wrong

### ISSUE THREAD

**Issue by cclauss** [Homebrew/brew#3869]
https://github.com/Homebrew/brew/blob/master/docs/Homebrew-and-Python.md

### Doc says...

* `python` points to the macOS system Python (with no manual PATH modification)
* `python2` points to Homebrew's Python 2.7.x (if installed)
* `python3` points to Homebrew's Python 3.x (if installed)
* `pip2` points to Homebrew's Python 2.7.x's pip (if installed)
* `pip3` points to Homebrew's Python 3.x's pip (if installed)

### but...

* __python__ points to Python 3.6.4
* __python2__ no longer exists
* __pip2__ no longer exists

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/Homebrew/brew/pull/3863.

In future: please always fill in the issue template.
