### ISSUE TITLE
Homebrew-and-Python seems all wrong -- again

### ISSUE THREAD

**Issue by cclauss** [Homebrew/brew#3871]
Recapitulation of #3869 

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ~~ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?~~

Not applicable -- the webpage is just wrong.

To help us debug your issue please explain:
- What you were trying to do (and why)
Read a webpage because the way that Python is installed changed but the documentation did not.
- What happened (include command output)
__python__ no longer pointed to the system Python
_python2__ no longer pointed to anything
__pip2__ no longer pointed to anything
- What you expected to happen
What is written in the doc
- ~~Step-by-step reproduction instructions (by running `brew` commands)~~
Not applicable -- the webpage is just wrong.

# Features
Please replace this section with:
- a detailed description of your proposed feature
The documentation should match what actually happens.
- the motivation for the feature
It is not helpful to mislead users.
- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)
I am not sure what percentage of brew users install Python
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

I expect that.

https://github.com/Homebrew/brew/blob/master/docs/Homebrew-and-Python.md

### Doc says...

* `python` points to the macOS system Python (with no manual PATH modification)
* `python2` points to Homebrew's Python 2.7.x (if installed)
* `python3` points to Homebrew's Python 3.x (if installed)
* `pip2` points to Homebrew's Python 2.7.x's pip (if installed)
* `pip3` points to Homebrew's Python 3.x's pip (if installed)

### but...

* __python__ points to Python 3.6.4
* __python2__ no longer exists
* __pip2__ no longer exists

**Comment by MikeMcQuaid** [comment]
> Doc says...

No, it doesn't any more (as I told you on the last issue). You didn't follow the issue template on this issue either and you didn't follow the instructions asked of you (posting the information there so the issue could be reopened).

**Comment by MikeMcQuaid** [comment]
> ran brew update and can still reproduce the problem?

You didn't do this, for example. https://github.com/Homebrew/brew/pull/3863 was merged an hour ago.

**Comment by MikeMcQuaid** [comment]
Finally:

> It is not helpful to mislead users.

Watch your tone, here. We're not "misleading users", it's a weekend and documentation changes take time for maintainers to implement. If you want to be helpful in future please consider checking if there are already open pull requests to address the problem and if not: submit one yourself.

**Comment by cclauss** [comment]
Sorry...  I did not realize these were ongoing changes.  My mistake.

**Comment by mrded** [comment]
You may need to install `pip2` separately `easy_install-2.7 pip`.
