### ISSUE TITLE
Custom download strategy fails on gem install

### ISSUE THREAD

**Issue by amancevice** [Homebrew/brew#3872]
Hi Homebrew, I am having a problem with a custom download strategy that attempts to install a gem. Here is my system output:

```
$ brew doctor
Your system is ready to brew
```

```
$ brew config
HOMEBREW_VERSION: 1.5.8-6-gbc3389b
ORIGIN: https://github.com/Homebrew/brew
HEAD: bc3389bdae5be31e5447802cb0eb8e1a967f5b4d
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2d0aaa0caf40d5f67a80d80214fa02735481d909
Core tap last commit: 87 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AWS_ACCESS_KEY_ID: set
HOMEBREW_AWS_SECRET_ACCESS_KEY: set
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_RUBY_WARNINGS: -W0
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/local/Cellar/ruby/2.5.0_2/bin/ruby
Java: N/A
macOS: 10.13.3-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

I am trying to write a custom subclass of the `CurlDownloadStrategy` that installs the `aws-sdk-s3` gem but am running into a permissions error.

I realize the `S3DownloadStrategy` exists, but putting that aside, I am not sure why installing a gem would fail this way.

Here is my download  strategy definition:

```ruby
class PresignDownloadStrategy < CurlDownloadStrategy
  def _fetch

    # Load AWS library
    begin
      require 'aws-sdk-s3'
    rescue LoadError
      Homebrew.install_gem_setup_path! 'aws-sdk-s3', '~> 1.8', 'ruby'
      require 'aws-sdk-s3'
    end

    # Get presigned URL
    signer = Aws::S3::Presigner.new
    uri = URI.parse @url
    url = signer.presigned_url :get_object,
                               :bucket => uri.host,
                               :key => uri.path.sub(/\A\//, '')

    # Download
    curl_download url, to: temporary_path
  end
end
```

Here's what I see on install:

```
brew install <private>/tap/<formula>
==> Installing <formula> from <private>/tap
==> Downloading s3://bucket/<formula>.tar.gz
==> Installing or updating 'aws-sdk-s3' gem
Error: Operation not permitted @ rb_sysopen - /Users/<me>/.gem/specs/api.rubygems.org%443/quick/Marshal.4.8/aws-sdk-s3-1.8.2.gemspec
```

Oddly, if I run `brew irb` and then `Homebrew.install_gem_setup_path! 'aws-sdk-s3', '~> 1.8', 'ruby'` I get no errors.

**Comment by alyssais** [comment]
Download strategies are run inside the sandbox, so you can’t use `install_gem_setup_path!` inside them.

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

> - [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh

Please do both of these things in future.

**Comment by amancevice** [comment]
My bad.
