### ISSUE TITLE
brew tap-pin errors unnecessarily when a tap is already pinned

### ISSUE THREAD

**Issue by cmsj** [Homebrew/brew#3880]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

`brew tap-pin foo/bar` from an Ansible playbook

- What happened (include command output)

It's fine the first run obviously, but subsequent runs fail because `brew tap-pin` fails with an error if the tap is already pinned.

- What you expected to happen

As with `brew tap foo/bar`, running the command multiple times just succeeds because the work was already done previously. IMHO multiple `brew tap-pin foo/bar` commands should also succeed.

- Step-by-step reproduction instructions (by running `brew` commands)

```
brew tap foo/bar
brew tap-pin foo/bar
brew tap-pin foo/bar
```

**Comment by MikeMcQuaid** [comment]
Many Homebrew commands throw errors when run multiple times. I'd rather not get into changing exit codes at this point as it's more likely to break existing scripts. We'd consider accepting a PR so e.g. `brew tap-pin` with no arguments outputs the currently pinned taps.

**Comment by cmsj** [comment]
Fair enough. FWIW, there is already `brew tap --list-pinned` 🙂
