### ISSUE TITLE
Spacing in uninstall file path cause error

### ISSUE THREAD

**Issue by limyunkai19** [Homebrew/brew#3882]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to upgrade logitech-options cask
```
brew cask upgrade logitech-options   
```

- What happened (include command output)
Error: No such file or directory - /Applications/Utilities/LogiMgr

```
==> Upgrading 1 outdated package, with result:
caskroom/drivers/logitech-options 6.80.384
==> Satisfying dependencies
==> Downloading https://www.logitech.com/pub/techsupport/options/Options_6.80.384.zip
Already downloaded: /Users/limyunkai19/Library/Caches/Homebrew/Cask/logitech-options--6.80.384.zip
==> Verifying checksum for Cask logitech-options
==> Starting upgrade for Cask logitech-options
==> Running uninstall process for logitech-options; your password may be necessary
==> Running uninstall script /Applications/Utilities/LogiMgr Uninstaller.app/Contents/Resources/Uninstaller
Error: No such file or directory - /Applications/Utilities/LogiMgr
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open3.rb:199:in `spawn'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open3.rb:95:in `popen3'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:88:in `each_output_line'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:25:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:205:in `uninstall_script'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:362:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:59:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

- What you expected to happen
The upgrade to be success.

- Step-by-step reproduction instructions (by running `brew` commands)
Installing and uninstalling logitech-options cask (or other cask with a space in file path in executable) will cause the problem.
```
brew cask install logitech-options
brew cask uninstall logitech-options
```

After looking on the error call stack trace, and trying to debug myself, I believe that the error comes from the shell commands escaping in the files `brew/Library/Homebrew/cask/lib/hbc/system_command.rb`.

I fix the error by escaping the executable string in https://github.com/Homebrew/brew/blob/067b9c9e88b617661849c4d77c291a24be32e1af/Library/Homebrew/cask/lib/hbc/system_command.rb#L88
Change to
```
        Open3.popen3({ "PATH" => path }, executable.shellescape, *args, **options)
```

And then, I am able to uninstall the logitech-options cask successfully.

**Comment by MikeMcQuaid** [comment]
> ran a brew command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a brew cask problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

As mentioned: please report to brew cask.

**Comment by limyunkai19** [comment]
I believe this is the correct place to report as escaping the string in the cask ruby script will cause the file path check to fail
```
Error: uninstall script /Applications/Utilities/LogiMgr\ Uninstaller.app/Contents/Resources/Uninstaller does not exist.
```

*and* I manage to make it work by changing some code in this repository.

Just trying my best to report bug. Hope that this issue is inspected more carefully.

**Comment by MikeMcQuaid** [comment]
@limyunkai19 I believe this will be addressed by https://github.com/Homebrew/brew/pull/3865 when the next tag is released.
