### ISSUE TITLE
Run-time deps of build-time deps aren't available to builds

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#3883]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

use `depends_on "opam" => :build` and not also have to use `depends_on "aspcud" => :build`

- What happened (include command output)

`aspcud` is not available to the build unless `aspcud` is itself added as a build-time dependency, even though it's a run-time dependency of `opam`.

- What you expected to happen

`/usr/local/opt/aspcud/bin` to be in the `PATH`

- Step-by-step reproduction instructions (by running `brew` commands)

```
iMac-TMP:homebrew-core joe$ git diff -- Formula/corectl.rb 
diff --git a/Formula/corectl.rb b/Formula/corectl.rb
index d21c3c9..5f168d7 100644
--- a/Formula/corectl.rb
+++ b/Formula/corectl.rb
@@ -22,6 +22,7 @@ class Corectl < Formula
   depends_on :macos => :yosemite
 
   def install
+raise "PATH: #{ENV["PATH"]}"
     ENV["GOPATH"] = buildpath
 
     path = buildpath/"src/github.com/TheNewNormal/#{name}"
iMac-TMP:homebrew-core joe$ brew install -s corectl
==> Downloading https://github.com/TheNewNormal/corectl/archive/v0.7.18.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/corectl-0.7.18.tar.gz
Error: PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/go/bin:/usr/local/opt/ocaml/bin:/usr/local/opt/aspcud/bin:/usr/local/opt/opam/bin:/usr/bin:/bin:/usr/sbin:/sbin
iMac-TMP:homebrew-core joe$ brew edit corectl
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/corectl.rb
Warning: Using vim because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR,
or HOMEBREW_EDITOR to your preferred text editor.
iMac-TMP:homebrew-core joe$ git diff -- Formula/corectl.rb 
diff --git a/Formula/corectl.rb b/Formula/corectl.rb
index d21c3c9..17fba92 100644
--- a/Formula/corectl.rb
+++ b/Formula/corectl.rb
@@ -17,11 +17,11 @@ class Corectl < Formula
   depends_on "go" => :build
   depends_on "libev"
   depends_on "ocaml" => :build
-  depends_on "aspcud" => :build
   depends_on "opam" => :build
   depends_on :macos => :yosemite
 
   def install
+raise "PATH: #{ENV["PATH"]}"
     ENV["GOPATH"] = buildpath
 
     path = buildpath/"src/github.com/TheNewNormal/#{name}"
iMac-TMP:homebrew-core joe$ brew install -s corectl
==> Downloading https://github.com/TheNewNormal/corectl/archive/v0.7.18.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/corectl-0.7.18.tar.gz
Error: PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/go/bin:/usr/local/opt/ocaml/bin:/usr/local/opt/opam/bin:/usr/bin:/bin:/usr/sbin:/sbin
iMac-TMP:homebrew-core joe$ 
```

**Comment by scpeters** [comment]
I'll just add that [dev-cmd/audit](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L383-L391) encourages `BUILD_TIME_DEPS` like `cmake` and `pkg-config` to be marked explicitly as `:run` if they are needed at both build and run-time, so I agree that this should be fixed.

**Comment by stek29** [comment]
This is (was?) a feature, see 2fb5ead38a7632ff6f941909474767883a9e0252

**Comment by ilovezfs** [comment]
Misfeature.
