### ISSUE TITLE
Feature Request: Popular/Featured Packages

### ISSUE THREAD

**Issue by Jahhein** [Homebrew/brew#3884]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Feature: Popular / Featured Packages Listing

Homebrew collects analytics that offer them information on where their focus needs to be. Finding packages can be difficult if you don't know that right keywords to search for and new packages are added everyday by the dozen. Sometimes really great packages can slip by and you'll never find them but needed. 

I would like to ask the brew community if the analytics can be used to offer a featured/popular listing available from the CLI. Along with, perhaps adding a popularity output for `brew info $formula`  to let users know if a package is something they should look into or not.

My biggest hope is to see this also integrated into Cask as well along with categorizing packages for better listings. Example: `brew list --category=git` or `brew cask list --category=git`.  This is a whole other feature request however.

I understand the difference between the two projects. I will also create a feature request explaining the same thing to homebrew/Cask if all goes well here.

**Comment by MikeMcQuaid** [comment]
https://brew.sh/analytics/install-on-request/ provides the data for this. Homebrew Cask specifically have disabled all analytics so you'd need to ask them for more information. Until we have an API with more information that's the best we can do for now, sorry!

**Comment by Jahhein** [comment]
Putting aside the popular packages, thoughts on categorizing packages for easier finding?

**Comment by MikeMcQuaid** [comment]
@Jahhein If someone else does it in an external tap for all packages we'd consider bringing it back into core. This is what happened for `desc` (descriptions).
