### ISSUE TITLE
[FEATURE REQUEST] wget backend instead of curl

### ISSUE THREAD

**Issue by NightMachinary** [Homebrew/brew#3888]
How do I force Homebrew to use wget instead of curl?
My network connection is unstable (though rather fast, I can download 2-3 megabytes per second with a download manager), and curl gets stuck a LOT in the middle of a download and I have to cancel the command manually and rerun it. Sometimes curl cancels it itself with errors like `curl: (56) Unexpected EOF`.

**Comment by MikeMcQuaid** [comment]
This is not possible and we're not interested in having it implemented, sorry. Please always fill out the feature request template in future.
