### ISSUE TITLE
site-packages caveat recommends mixing python versions

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/brew#3890]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

The site-packages caveat is broken; it recommends adding a 3.6 site-packages to a 2.7 sys.path, which is likely to cause breakage.

e.g. `brew install protobuf` produces:

```
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/tim/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python3.6/site-packages")' >> /Users/tim/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```

cc @scpeters

**Comment by scpeters** [comment]
can you include `brew doctor` and `brew config` please

**Comment by scpeters** [comment]
I can reproduce this if I install `protobuf` when homebrew `python` is already installed. I also see some hard-coded python versions in the following code:

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/keg.rb#L362-L368

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/caveats.rb#L125

**Comment by DomT4** [comment]
Yeah the change the other day has caused some issues. I started playing around yesterday and got as far as:
```diff
diff --git a/Library/Homebrew/caveats.rb b/Library/Homebrew/caveats.rb
index 8cd1053fb..632dcbe0f 100644
--- a/Library/Homebrew/caveats.rb
+++ b/Library/Homebrew/caveats.rb
@@ -113,8 +113,8 @@ class Caveats
     return unless keg.python_site_packages_installed?
 
     s = nil
-    homebrew_site_packages = Language::Python.homebrew_site_packages
-    user_site_packages = Language::Python.user_site_packages "python"
+    homebrew_site_packages = Language::Python.homebrew_site_packages(2.7)
+    user_site_packages = Language::Python.user_site_packages "python2.7"
     pth_file = user_site_packages/"homebrew.pth"
     instructions = <<~EOS.gsub(/^/, "  ")
       mkdir -p #{user_site_packages}
@@ -123,17 +123,17 @@ class Caveats
 
     if f.keg_only?
       keg_site_packages = f.opt_prefix/"lib/python2.7/site-packages"
-      unless Language::Python.in_sys_path?("python", keg_site_packages)
+      unless Language::Python.in_sys_path?("python2.7", keg_site_packages)
         s = <<~EOS
           If you need Python to find bindings for this keg-only formula, run:
             echo #{keg_site_packages} >> #{homebrew_site_packages/f.name}.pth
         EOS
-        s += instructions unless Language::Python.reads_brewed_pth_files?("python")
+        s += instructions unless Language::Python.reads_brewed_pth_files?("python2.7")
       end
       return s
     end
 
-    return if Language::Python.reads_brewed_pth_files?("python")
+    return if Language::Python.reads_brewed_pth_files?("python2.7")
 
     if !Language::Python.in_sys_path?("python", homebrew_site_packages)
       s = <<~EOS
```
before I ran out of time I could spend looking at it for the day.
