### ISSUE TITLE
Allow downloading bottles via ssh

### ISSUE THREAD

**Issue by ryangreenberg** [Homebrew/brew#3891]
## Motivation
I would like to make it easy to install bottles that are stored in a secure location to further enable internal/corporate use of homebrew. I propose doing this by introducing a file download strategy that uses `scp`.

## Detailed Description

@eedwards-sk's work in #3841 will make it possible to specify download strategies
for bottles. Once that change is merged, you will be able to use `S3DownloadStrategy`,
`GitHubPrivateRepositoryDownloadStrategy`, or
`GitHubPrivateRepositoryReleaseDownloadStrategy` to download bottles from protected locations. A disadvantage to these, however, is that they require
individual developers to have the appropriate environment variables set
(e.g. `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` or `HOMEBREW_GITHUB_API_TOKEN`). This in turns means those credentials have to be provisioned and distributed to individual developer's machines.

Most companies already distribute and maintain ssh keys and configuration for developers, which makes it a natural fit for downloading internal files securely. I would like to introduce an `ScpFileDownloadStrategy` which would support fetching bottles over ssh via `scp`.

The schema for this strategy would be `scp://` and the format would be:

```
scp://(optional user)@host(:optional port)/path
```

The `fetch` method of `ScpFileDownloadStrategy` would translate this to `scp [-P optional port] host:/path`

In a formula this might look like:

```
bottle do
  root_url "scp://bottles.company.com/home/homebrew-bottles", :using => ScpFileDownloadStrategy
  ...
  sha256 "3a75f421c2b52c0fd0ee6e16a3adb6ecc4ac9ed8b4b73182515ff28b7a12a656" => :sierra
  sha256 "cce3572ec0448e5dbbd3719870c15cc534a0b3dd9cfdd048610e8234302f6e1a" => :high_sierra
end
```

## Relevance
The feature template asks "how the feature would be relevant to at least 90% of Homebrew users" and I admit that this is a niche addition (on top of internal/corporate use of Homebrew which is itself probably a niche). My apologies if this seems like a waste of time.

## Alternatives
Write this strategy, distribute it with our internal formulae, and `require` it at the top.

---

I would be happy to create a pull request for this change if the proposal seems acceptable.

**Comment by MikeMcQuaid** [comment]
> I would be happy to create a pull request for this change if the proposal seems acceptable.

Yep, this sounds good. If there's a PR with sufficient test coverage we'd consider accepting this.
