### ISSUE TITLE
Add brew switch to help text

### ISSUE THREAD

**Issue by abraithwaite** [Homebrew/brew#3917]
### Feature Request

I (in)frequently use brew to switch versions of a package (go, python, etc).  Enough to want to see it in help output, but not frequently enough to memorize it.

Motivated by the number of times I've had to look it up.  Ironically, now that I'm making this PR, I'll probably never forget but I'd like to help others.

I imagine >90% of developers have to do this at least every other month or so.

Alternative approach: call out in the help text that it's not an exhaustive list of commands so that developers more readily open the man page.

**Comment by MikeMcQuaid** [comment]
> Alternative approach: call out in the help text that it's not an exhaustive list of commands so that developers more readily open the man page.

It does say: "further help" and "example usage" and mentions `man brew`. Passing on this as this doesn't seem to be a widespread concern. Thanks anyway!

**Comment by abraithwaite** [comment]
Fair enough!  Thanks for your hard work on this project!
