### ISSUE TITLE
zpipe module request 

### ISSUE THREAD

**Issue by yehgdotnet** [Homebrew/brew#3919]
Recently, I find it to difficult to unzip zlib file. Found only two ways, 1) do python code 2) use zpipe.c

I found this pull request before but I can't find it in brew cask.

Homebrew/legacy-homebrew#21947

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by MikeMcQuaid** [comment]
In this case, though, please ask your question on Discourse.

**Comment by yehgdotnet** [comment]
it's alright, man. I can just use compile zpipe module. No issue for me. Just wanted to make brew packages more complete. No offense.

**Comment by yehgdotnet** [comment]
Thanks anyway
