### ISSUE TITLE
Mac 10.13.3 while install HomeBrew it will throw 

### ISSUE THREAD

**Issue by AndreHu88** [Homebrew/brew#3922]
When I use  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" this script to install HomeBrew,the terminal will throw a OpenSSL error。
the error is : fatal: unable to access 'https://github.com/Homebrew/brew/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
How to solve it. thanks

**Comment by MikeMcQuaid** [comment]
This is something specific to your machine that you will need to resolve.

**Comment by MikeMcQuaid** [comment]
Also: 

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.
