### ISSUE TITLE
`brew uses` giving incomplete results

### ISSUE THREAD

**Issue by jimwise** [Homebrew/brew#3927]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
See what installed packages use mango

- What happened (include command output)
```
lorien$ brew uses --installed pango
lorien$ brew uninstall pango
Error: Refusing to uninstall /usr/local/Cellar/pango/1.42.0
because it is required by gnuplot 5.2.2_1, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies pango

```
- What you expected to happen
I expected `brew uses --installed tango` to tell me what installed packages use pango
- Step-by-step reproduction instructions (by running `brew` commands)
Install pango and gnuplot
Run the above commands

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by jimwise** [comment]
Output of `brew doctor && brew config`:

```
Your system is ready to brew.
HOMEBREW_VERSION: 1.5.10-18-g96fd1a8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96fd1a8c2a7a5680c1ce611415018a2c642ba3e4
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f9aec7aa50704c258cb412e2022c752625d1a416
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0_2/bin/ruby
Java: 9.0.4
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

**Comment by scpeters** [comment]
Can you `brew info gnuplot`? I think this might happen if you built `gnuplot` with options `--with-cairo` or `--with-wxmac`

* https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnuplot.rb#L38

**Comment by jimwise** [comment]
Did build with —wxmac, so that does make sense as an explanation.  Any way to make —installed take options into account?

Output follows:

```
lorien$ brew info gnuplot
gnuplot: stable 5.2.2 (bottled), HEAD
Command-driven, interactive function plotting
http://www.gnuplot.info/
/usr/local/Cellar/gnuplot/5.2.2_1 (45 files, 2.9MB) *
  Built from source on 2018-03-14 at 18:51:45 with: --with-cairo --with-wxmac
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnuplot.rb
==> Dependencies
Build: pkg-config ✔
Required: gd ✔, readline ✔
Recommended: lua ✔
Optional: qt ✘, wxmac ✔
==> Requirements
Optional: x11 ✘
==> Options
--with-aquaterm
	Build with AquaTerm support
--with-cairo
	Build the Cairo based terminals
--with-qt
	Build with qt support
--with-wxmac
	Build wxmac support. Need with-cairo to build wxt terminal
--with-x11
	Build with x11 support
--without-lua
	Build without the lua/TikZ terminal
--HEAD
	Install HEAD version
lorien$
```
--
				Jim Wise
				jwise@draga.com

**Comment by MikeMcQuaid** [comment]
> Any way to make —installed take options into account?

Sorry, this is not supported.

**Comment by ilovezfs** [comment]
```
bash-3.2$ grep -l pango $(brew --cellar)/*/*/INSTALL_RECEIPT.json
/usr/local/Cellar/gnuplot/5.2.2_1/INSTALL_RECEIPT.json
/usr/local/Cellar/pango/1.42.0/INSTALL_RECEIPT.json
```
does the job
