### ISSUE TITLE
Error: Cannot tap ros/hydro: invalid syntax in tap!

### ISSUE THREAD

**Issue by srnand** [Homebrew/brew#3928]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [Yes ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [Yes ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [Yes ] ran `brew update` and can still reproduce the problem?
- [ Yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ Yes] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- trying to install ros hydro
- What happened (include command output)
-brew tap ros/hydro
==> Tapping ros/hydro
Cloning into '/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro'...
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 13 (delta 1), reused 8 (delta 1), pack-reused 0
Unpacking objects: 100% (13/13), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/uuid.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/uuid.rb:7:in `<class:Uuid>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/openni2.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/openni2.rb:6:in `<class:Openni2>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/icon-naming-utils.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/icon-naming-utils.rb:6:in `<class:IconNamingUtils>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/tango-icon-theme.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/tango-icon-theme.rb:6:in `<class:TangoIconTheme>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/mongodb-dev.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/mongodb-dev.rb:6:in `<class:MongodbDev>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/yaml-cpp-0.3.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/yaml-cpp-0.3.rb:6:in `<class:YamlCpp03>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/pyassimp.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/pyassimp.rb:6:in `<class:Pyassimp>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/gfortran.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/gfortran.rb:11:in `<class:Gfortran>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/pcl.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ros/homebrew-hydro/pcl.rb:6:in `<class:Pcl>'
Please report this to the ros/hydro tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap ros/hydro: invalid syntax in tap!
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by scpeters** [comment]
~~~
Please report this to the ros/hydro tap!
~~~

Also, I recommend the following instructions for installing ROS on macOS:

* https://github.com/mikepurvis/ros-install-osx
