### ISSUE TITLE
brew cleanup: remove older version, even recent version not installed?

### ISSUE THREAD

**Issue by hibiyasleep** [Homebrew/brew#3930]
I have very insufficient free disk space, and saw many duplicated versions of large utilities (e.g. gcc, ffmpeg etc). however in my situation there's too many packages to manually delete; `brew cleanup` wasn't do any help because many packages are *slightly* outdated.

so I propose one of them:

* flag `--ignore-not-installed` or something, to remove useless versions anyway.
* or don't skip with `most recent version not installed` warning by default.

ps: I ran `cleanup` and `update` 4 times each, freed 5GB of storage spaces.

**Comment by MikeMcQuaid** [comment]
> brew cleanup wasn't do any help because many packages are slightly outdated.

Sorry, we don't support keeping people on old versions.

Also: from the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
