### ISSUE TITLE
brew reinstall tesseract --HEAD Throws an Error

### ISSUE THREAD

**Issue by jsl303** [Homebrew/brew#3931]
I'm trying to install Tesseract on High Sierra using home brew. However, I get an error below. Is there any fix for this?
I'm not sure this is the right place to ask, but I also opened an issue at tesseract.
https://github.com/tesseract-ocr/tesseract/issues/1389
It doesn't complain about keychain anymore after I deleted github login from keychain. However, it still has the error about "filename argument required."
Thanks for your help!

$ brew reinstall tesseract --HEAD
==> Reinstalling tesseract
==> Cloning 
https://github.com/tesseract-ocr/tesseract.git
Updating /Users/user/Library/Caches/Homebrew/tesseract--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/tesseract/HEAD-023e1b3
Last 15 lines from /Users/user/Library/Logs/Homebrew/tesseract/02.configure:
2018-03-14 23:54:58 -0400

./configure
--disable-dependency-tracking
--prefix=/usr/local/Cellar/tesseract/HEAD-023e1b3

./configure: line 5: .: filename argument required
.: usage: . filename [arguments]

READ THIS: https://docs.brew.sh/Troubleshooting

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:210:in raise_api_error': GitHub (GitHub::AuthenticationFailedError) The GitHub credentials in the macOS keychain may be invalid. Clear them with: printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase Or create a personal access
token: https://github.com/settings/tokens/new?scopes=gist,public_repodescription=Homebrew and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:inopen_api'
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in search' from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:insearch_issues'
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in issues_for_formula' from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:infetch_issues'
from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in issues' from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:indump'
from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in rescue in <main>' from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in

**Comment by MikeMcQuaid** [comment]
> READ THIS: https://docs.brew.sh/Troubleshooting

You didn't.

From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

Please read it and report this to the correct place.
