### ISSUE TITLE
audit: Confusing message when detecting incorrectly formatted heredoc

### ISSUE THREAD

**Issue by javian** [Homebrew/brew#3945]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

HOMEBREW_VERSION: 1.5.10-33-g63e8817
ORIGIN: https://github.com/Homebrew/brew
HEAD: 63e8817950aab87a6761155e04f0fbb7e59b3d3a
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 007e3894ffe6c3bfac3528b4996015eb103f2366
Core tap last commit: 11 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BINTRAY_KEY: set
HOMEBREW_DEVELOPER: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_INSECURE_REDIRECT: 1
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0_2/bin/ruby
Java: N/A
macOS: 10.13.3-x86_64
Xcode: 9.2 => /Volumes/Macintosh HD/Applications/Xcode.app/Contents/Developer
CLT: 9.2.0.0.1.1510905681
X11: N/A

When working on a formula recently I discovered that one of the audit messages are not really telling you what the problem is or giving you more information than you would actually need.
```
➜  homebrew-core git:(composer) ✗ brew audit composer --strict
composer:
  * C: 34: col 1: Use 2 spaces for indentation in a heredoc by using `<<~` instead of `<<~`.
  * C: 46: col 1: Use 2 spaces for indentation in a heredoc by using `<<~` instead of `<<~`.
Error: 2 problems in 1 formula
```
Both of these audits trigger because I haven't indented the content of the heredoc but the message indicates that the symbols I used is at fault when they are actually correct. This seems confusing and could confuse contributors as to where the actual problem is. The line indicated is also the heredoc line rather than where the indentation starts but perhaps it would be sufficient to remove `by using...` and just leave the first part in the message.

**Comment by MikeMcQuaid** [comment]
```
  * C: 34: col 1: Use 2 spaces for indentation in a heredoc by using `<<~` instead of `<<~`.
  * C: 46: col 1: Use 2 spaces for indentation in a heredoc by using `<<~` instead of `<<~`.
```

We can't customise these messages as they come from RuboCop. Can you detail the relevant code that it flags?

**Comment by javian** [comment]
Sure.
```
    (testpath/"test/tests/test.php").write <<~EOS
    <?php
    EOS
```
Triggers the audit test and
```
    (testpath/"test/tests/test.php").write <<~EOS
      <?php
    EOS
```
is the change required to make it pass.

**Comment by MikeMcQuaid** [comment]
Yeh, the message isn't ideal here but it is correct (and we have no control over it 😭).

**Comment by javian** [comment]
Looks like it been fixed very recently. https://github.com/bbatsov/rubocop/pull/5665
