### ISSUE TITLE
Is curl meant to be limited by superenv?

### ISSUE THREAD

**Issue by bukzor** [Homebrew/brew#3947]
I have a problem wherein I have curl installed but brew isn't using it. Looking at the code, brew falls back to `which("brew")` but that's not finding my curl because the superenv $PATH has already been set up. This leads to the curl shown by `brew config` not being the curl used by superenv, even though both are computed by [the same code](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/curl.rb#L4).

If this is intended, behavior, and curl is supposed to be limited by superenv, then this which() line is really only looking in superenv/shims and /sbin, neither of which will ever have curl. Otherwise, there's a bug, and `curl_executable` needs to be evaluated differently.

What's the intent?

**Comment by MikeMcQuaid** [comment]
Hey @bukzor, please always fill out the issue template.

This is a Linux-only issue because `/usr/bin/curl` is always in superenv's lookup PATH. In this case perhaps setting `HOMEBREW_CURL` in `curl_executable` or moving all the logic into Bash is a better fit.

**Comment by bukzor** [comment]
Apologies. Will do.

I'll take this over to Linuxbrew.

**Comment by MikeMcQuaid** [comment]
@bukzor No worries and thanks for apologising ❤️
