### ISSUE TITLE
Interrupted install does not gracefully recover

### ISSUE THREAD

**Issue by bcdady** [Homebrew/brew#395]
### Bug report:

If interrupted, install script should be able to determine where it left off, and resume, especially from the **Downloading and installing Homebrew** phase, to at least to the point where `brew update` and/or `brew doctor` can reliable work.

Launching installer `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"` made good progress until:

```
==> Downloading and installing Homebrew...
fatal: unable to access 'https://github.com/Homebrew/brew/': Empty reply from server
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1
```

- Ran `brew update` and got: -bash: brew: command not found (so naturally, `brew doctor` was the same).
- Re-ran installer, but it returned the following:

```
It appears Homebrew is already installed. If your intent is to reinstall you should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
The current contents of /usr/local are azure bin include juniper lib libexec share .git
```

I suspect a network interruption, but regardless, I was unable to recover and proceed. Instead, I had to Uninstall Homebrew and start over. It would be better for the install script to be able to  resume where this was interrupted, and/or check that if brew update cannot run, that there are some additional fixup/repair tasks it should complete.

**Comment by bcdady** [comment]
After uninstall script completed, and I re-ran install, it displayed the following progress:

```
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown [user] /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Counting objects: 496, done.
remote: Compressing objects: 100% (445/445), done.
remote: Total 496 (delta 31), reused 306 (delta 22), pack-reused 0
Receiving objects: 100% (496/496), 774.73 KiB | 80.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
Checking out files: 100% (486/486), done.
HEAD is now at 66cda61 test-bot: fix diff_formulae
==> Tapping homebrew/core
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 3706, done.
remote: Compressing objects: 100% (3588/3588), done.
remote: Total 3706 (delta 12), reused 2251 (delta 8), pack-reused 0
Receiving objects: 100% (3706/3706), 2.88 MiB | 87.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
Checking connectivity... done.
Checking out files: 100% (3709/3709), done.
Tapped 3583 formulae (3,732 files, 8.9M)
==> Installation successful!
```

This is exactly what I had hoped it would do when I first re-ran install.

**Comment by MikeMcQuaid** [comment]
@bcdady We'll welcome pull requests for this but this isn't something I really think we can improve much as it's going to be really difficult to differentiate between a partial and valid install.

**Comment by bcdady** [comment]
I'm not proficient with Ruby, but I'll give it a try.
I'm assuming I'm missing some appreciation of the details ... why do we have to abort if
`#{HOMEBREW_PREFIX}/.git/*` (/usr/local/.git/ in most? default cases) is not empty (line 136)?

Is preemptively deleting the /.git/ directory problematic? I would suppose that most of the time, replacing that directory with a fresh copy of the **brew** repository will be the best option to get an interrupted/incomplete/partial install back on track, and ideally to a point where a new Homebrew user could then run `brew help`, `brew update` and/or `brew doctor`

I can take a crack at updating a copy and preparing a pull request, but please let me know if this proposal won't hold water ... e.g. if there are other install or prerequisite steps that like being repeated.

**Comment by MikeMcQuaid** [comment]
> Is preemptively deleting the /.git/ directory problematic?

Yes, unfortunately so because it could be used by either an existing Homebrew installation or something else. This is why we can't really handle this automatically. What might be a better solution would be to modify the `install` script so it handles failures better and cleans up after itself so that running it again would be successful?
