### ISSUE TITLE
Brew Update of saltstack 2017.7.4 on OSX 10.9 -- Failed 

### ISSUE THREAD

**Issue by pinnaclesystemsgroup** [Homebrew/brew#3956]
brew upgrade saltstack --build-from-source

==> /usr/local/Cellar/saltstack/2017.7.4/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/saltstack--pygit2-20180322-33104-4z550y/pygit2-0.26.3

Last 15 lines from /Users/.../Library/Logs/Homebrew/saltstack/16.pip:
  Removing source in /private/tmp/pip-o1ZLe9-build
Command "/usr/local/Cellar/saltstack/2017.7.4/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-o1ZLe9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_AQn5o-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/saltstack/2017.7.4/libexec/include/site/python2.7/pygit2" failed with error code 1 in /private/tmp/pip-o1ZLe9-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/2017.7.4/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/saltstack/2017.7.4/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/saltstack/2017.7.4/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/Cellar/saltstack/2017.7.4/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/Cellar/saltstack/2017.7.4/libexec/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/saltstack/2017.7.4/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-o1ZLe9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_AQn5o-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/saltstack/2017.7.4/libexec/include/site/python2.7/pygit2" failed with error code 1 in /private/tmp/pip-o1ZLe9-build/

Check on pygit2 python package --

pip2 install pygit2 
Requirement already satisfied: pygit2 in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: cffi in /usr/local/lib/python2.7/site-packages (from pygit2)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from pygit2)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/site-packages (from cffi->pygit2)

Cannot explain this output from the brew installation command:

InstallationError: Command "/usr/local/Cellar/saltstack/2017.7.4/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-o1ZLe9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_AQn5o-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/saltstack/2017.7.4/libexec/include/site/python2.7/pygit2" failed with error code 1 in /private/tmp/pip-o1ZLe9-build/

Also, despite the advisement in the brew update message, this is NOT an OSX version issue.

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Also, wrong repository.
