### ISSUE TITLE
brew install gnu-sed does not link sed.

### ISSUE THREAD

**Issue by vincentb1** [Homebrew/brew#3958]
Not sure whether this is a bug or not.
I have done `brew update` and still have the problem.
When I type
``` bash
brew install gnu-sed
```
it installs gnu-sed without creating any symlink, so just typing sed call the old sed.
Typing `brew link sed` links the info file, but not sed executable, `which sed` is still `/usr/bin/sed` afterwards.
So I had to do this by hand:
```bash
pushd /usr/local/bin
ln -s ../Cellar/gnu-sed/4.4/bin/gsed sed
popd
```
I am on Mac OSX 10.13.2 and default sed has a problem with `-i` option when there is no extension given.

**Comment by ilovezfs** [comment]
Please read the caveat for gnu-sed and always complete the issue template. Note this is the wrong repository to file a formula specific issue as the template says.

```
==> Caveats
The command has been installed with the prefix "g".
If you do not want the prefix, install using the "with-default-names" option.

If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

Additionally, you can access their man pages with normal names if you add
the "gnuman" directory to your MANPATH from your bashrc as well:
  MANPATH="/usr/local/opt/gnu-sed/libexec/gnuman:$MANPATH"
```

**Comment by vincentb1** [comment]
Oops… sorry for the disturbance. I must admit I had missed the gsed thing.
Thank you for your time.
