### ISSUE TITLE
brew install <package>@<version> native support?

### ISSUE THREAD

**Issue by dfuentes77** [Homebrew/brew#3960]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Feature Request
I love the Product.  It's so convenient. 

I've often needed to install an older version of a package, e.g. pipenv 

In my google searches I keep running into old documentation where this was possible.  But it doesn't seem possible now (unless I'm blind).

Would love the ability to do this. I just had to follow this blog post:
https://remarkablemark.org/blog/2017/02/03/install-brew-package-version/
to install it via Git raw url.

It worked but was a pretty lengthy process.

**Comment by MikeMcQuaid** [comment]
This is intentionally not possible, sorry.
