### ISSUE TITLE
Outdated Xcode error when external drive is connected containing old system backup

### ISSUE THREAD

**Issue by johtso** [Homebrew/brew#3961]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

It seems homebrew is too eager to find a copy of Xcode *anywhere*, even if it's not actually intalled.

It seems to be finding a copy of Xcode in an old system backup and complaining about it being an old version, preventing me from installing anything.

**Comment by MikeMcQuaid** [comment]
> It seems homebrew is too eager to find a copy of Xcode anywhere, even if it's not actually intalled.

Yep, this is intentional. We exclude Time Machine backups (`/Backups.backupdb/`).

**Comment by ilovezfs** [comment]
@johtso install the current Xcode in /Applications and the problem should go away.

**Comment by johtso** [comment]
I don't want/need Xcode, I'm using command line tools instead.

The external drive contains a Carbon Copy Cloner backup, so that explains why it's not getting ignored.

**Comment by ilovezfs** [comment]
In that case, you'll need to unplug the drive.

**Comment by MikeMcQuaid** [comment]
If there's a way to detect a Carbon Copy Cloner backup specifically then we'd welcome a PR to add that to the exclusion list.

**Comment by johtso** [comment]
I don't think there's any reliable way of detecting a CCC backup. There *may* be a `_CCC SafetyNet` directory at the top level.

A decent solution I just found was to add the external drive to the Spotlight preferences privacy list to stop it appearing in search results.

**Comment by MikeMcQuaid** [comment]
> A decent solution I just found was to add the external drive to the Spotlight preferences privacy list to stop it appearing in search results.

Good idea, I didn't think about that. I'll let people know that in future. Sorry and thanks!
