### ISSUE TITLE
pyqt issue on Mac OS X El Capitain 10.11.6

### ISSUE THREAD

**Issue by lianne** [Homebrew/brew#3963]
I have just the following error anytime I give a brew command:

"Error: pyqt: --with-python3 must be specified when using --without-python"

here my config [gist](https://gist.github.com/lianne/bbffd36f3e64960646905d72f31dccee)
and my brew doctor [gist](https://gist.github.com/lianne/a7b112acd94c5283a152db8909e5a0da)

If I try to uninstall pyqt I get the same error and nothing happens.
If I brew update the outcome is "Already up-to-date" but as soon as I do brew upgrade the same error appears.
what should I do? is it a python problem?

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by MikeMcQuaid** [comment]
> If you add the necessary information this issue may be reopened.

Although not in this case because it should be submitted to Discourse or the correct repository instead.
