### ISSUE TITLE
brew install python resulting in old version of python

### ISSUE THREAD

**Issue by volt4ire** [Homebrew/brew#3964]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

I have python installed through Homebrew, and when "brew info python" it says I have version 3.6.4.  However, when I run "python --version" to tell me which version of python I have, it says I'm still running python 2 (2.7.10). I thought Homebrew recently switched to having python3 be the default, or is this not correct? If it is correct, how do I get the python 3 version of python to run as python by default? Thanks!!

Also, I've had pyenv installed in the past but have since removed it – I'm not sure if that makes a difference. I've posted the output of brew config at the bottom of this post. Further, the output I get when I run "which python" is /usr/bin/python, and my path file reads as follows: 
/usr/local/opt/coreutils/libexec/gnubin
/Users/rwbarat/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/MacGPG2/bin
/Library/Frameworks/Mono.framework/Versions/Current/Commands

#brew config output
HOMEBREW_VERSION: 1.5.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 85ebe88094f9095871b6ad752077ee1100b20328
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a94dd2dd09626aa33f16ee8eda35c212e1356286
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_INSECURE_REDIRECT: 1
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: N/A
X11: N/A

**Comment by MikeMcQuaid** [comment]
> I thought Homebrew recently switched to having python3 be the default, or is this not correct?

We changed this back.

> If it is correct, how do I get the python 3 version of python to run as python by default?

Read `brew info python`.
