### ISSUE TITLE
Resolved: python2 can't use after brew upgrade

### ISSUE THREAD

**Issue by yi-ge** [Homebrew/brew#3965]
brew升级后python2不能用的解决方案

```

brew install python@2

rm -rf /usr/local/bin/python
rm -rf /usr/local/bin/pip
rm -rf /usr/local/bin/python-config
sudo ln -s /usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /usr/local/bin/python 
sudo ln -s /usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config /usr/local/bin/python-config 
sudo ln -s /usr/local/Cellar/python@2/2.7.14_3/bin/pip2 /usr/local/bin/pip 
```

vim .bash_profile，add：
```
export PATH="/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/Cellar/python@2/2.7.14_3/bin:$PATH"
```

Check:
python --version
python3 --version
pip --version
pip3 --version
virtualenvwrapper is ok.

**Comment by ilovezfs** [comment]
None of that is necessary. Please read https://github.com/Homebrew/brew/blob/master/docs/Homebrew-and-Python.md#python-3x-or-python-2x

In the future, please always fill out the issue template. Also, please note that this is the wrong repository for formula specific issues.

**Comment by yi-ge** [comment]
@ilovezfs Thank you very much. I will fill out the issue template next. Thank you!
