### ISSUE TITLE
Library not loaded: /usr/local/lib/libwep

### ISSUE THREAD

**Issue by falseor** [Homebrew/brew#3989]
when I enter brew doctor，will display this。 
Unexpected dylibs:
  /usr/local/lib/libwep_airdrop.dylib
  /usr/local/lib/libwep_burn.dylib
  /usr/local/lib/libwep_cbcarbon.dylib
  /usr/local/lib/libwep_cbcocoa.dylib
  /usr/local/lib/libwep_chrome.dylib
  /usr/local/lib/libwep_dutil.dylib
  /usr/local/lib/libwep_ff.dylib
  /usr/local/lib/libwep_icloud.dylib
  /usr/local/lib/libwep_mail.dylib
  /usr/local/lib/libwep_outlook.dylib
  /usr/local/lib/libwep_post.dylib
  /usr/local/lib/libwep_printer.dylib
  /usr/local/lib/libwep_screen.dylib
dyld: Library not loaded: /usr/local/lib/libwep
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/git
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libwep: mmap() error 1 at address=0x10EA85000, size=0x0000F000 segment=__TEXT in Segment::map() mapping /usr/local/lib/libwep
	/usr/local/lib/libwep: mmap() error 1 at address=0x10EAA7000, size=0x0000F000 segment=__TEXT in Segment::map() mapping /usr/local/lib/libwep
sh: line 1:  2541 Trace/BPT trap: 5       git status --untracked-files=all --porcelain -- Library/Homebrew/ 2> /dev/null

I try brew install svn, will display

==> Installing dependencies for subversion: apr, openssl, apr-util, readline, sqlite, perl
==> Installing subversion dependency: apr
dyld: Library not loaded: /usr/local/lib/libwep
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/git
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libwep: mmap() error 1 at address=0x10C81F000, size=0x0000F000 segment=__TEXT in Segment::map() mapping /usr/local/lib/libwep
	/usr/local/lib/libwep: mmap() error 1 at address=0x10C83A000, size=0x0000F000 segment=__TEXT in Segment::map() mapping /usr/local/lib/libwep
Error: Failure while executing: git config --local --replace-all homebrew.private true

help me

**Comment by vitorgalvao** [comment]
Hello, @falseor. The template that shows when you open an issue is very clear:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Please try again, and when you do use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to properly format your code.
