### ISSUE TITLE
brew leaves problem (related to /homebrew/science change)

### ISSUE THREAD

**Issue by adah1972** [Homebrew/brew#3995]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?
HOMEBREW_VERSION: 1.5.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f4e22e28d3b65a6c8dbb0f270bb6d262a2429d6
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 628620e3b1c3c9fb3cbf6bb1c90338c7ae9371ee
Core tap last commit: 8 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.13.3-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A

To help us debug your issue please explain:
- What you were trying to do (and why)

Run `brew leaves`.

- What happened (include command output)

I got:

```
Error: No available formula with the name "homebrew/science/qsopt"
```

- What you expected to happen

The correct output of leaves information.

- Step-by-step reproduction instructions (by running `brew` commands)

```
brew leaves
```

# Additional information

I can see that qsopt is installed by `brew list`. I then ran `brew uninstall qsopt`, which was successful. I still got this error in `brew leaves`. I then ran `brew tap /homebrew/science`, I got:

```
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
```

After running `brew untap /homebrew/science`, I still got the same problem, with one more line of output:

```
Error: No available formula with the name "homebrew/science/qsopt" 
Please tap it and then try again: brew tap homebrew/science
```

**Comment by MikeMcQuaid** [comment]
@adah1972 Can you run `brew leaves --debug` and paste the output here? Thanks!

**Comment by adah1972** [comment]
```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tokei.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git-lfs.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lame.rb
…
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/Formula/qsopt.rb
Error: No available formula with the name "homebrew/science/qsopt" 
Please tap it and then try again: brew tap homebrew/science
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:240:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:230:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:281:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:33:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/leaves.rb:15:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/leaves.rb:15:in `block in leaves'
/usr/local/Homebrew/Library/Homebrew/cmd/leaves.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/leaves.rb:14:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cmd/leaves.rb:14:in `leaves'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by adah1972** [comment]
@MikeMcQuaid I have identified the problem. After the /homebrew/science change, brew could no longer recognized the dependency of `concorde` on `qsopt`, thus the problem. To fix my specific problem, reinstalling `concorde` would do.

You may want to consider how to avoid such situations in the future. It is up to you whether this issue should be closed.

**Comment by MikeMcQuaid** [comment]
Thanks for the report and debug information @adah1972. I've fixed this in https://github.com/Homebrew/brew/pull/3999 which you'll get after it's merged in the next tagged release. Thanks again!
