### ISSUE TITLE
"/usr/local is not writeable", can't chown /usr/local in High Sierra (10.13.3)

### ISSUE THREAD

**Issue by fligi7** [Homebrew/brew#4000]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
> $ brew doctor
...
Warning: /usr/local is not writable.
...
You should change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami) /usr/local

> $ brew config
HOMEBREW_VERSION: 1.3.7-32-gc458c90
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c458c902369d039acb818e9f71393084a33df491
Last commit: 4 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 19fe38ea1db512c8796f6a6b4b056b82efd6d4c6
Core tap last commit: 1 year, 11 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_GIT_CONFIG_FILE: /usr/local/.git/config
HOMEBREW_REPOSITORY: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Warning: Calling BottleSpecification.revision is deprecated!
Use BottleSpecification.rebuild instead.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/python.rb:9:in `block in <class:Python>'
Please report this to the homebrew/core tap!
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: N/A
X11: N/A

To help us debug your issue please explain:
- What you were trying to do (and why)
Run brew, at all, in any shape or form on High Sierra (10.13.3)
- What happened (include command output)
> $ brew update
Error: /usr/local is not writable. You should change the
ownership and permissions of /usr/local back to your
user account:
  sudo chown -R $(whoami) /usr/local
- What you expected to happen
Brew to successfully run
- Step-by-step reproduction instructions (by running `brew` commands)
> $ brew update
Error: /usr/local is not writable. You should change the
ownership and permissions of /usr/local back to your
user account:
  sudo chown -R $(whoami) /usr/local

> $ sudo chown -R $(whoami) /usr/local
chown: /usr/local: Operation not permitted

> $ sudo chown -R $(whoami) $(brew --prefix)/*

Executed the above command, per https://github.com/Homebrew/brew/issues/3228. Everything in /usr/local/ is now owned by the current user.

> $ brew update
Error: /usr/local is not writable. You should change the
ownership and permissions of /usr/local back to your
user account:
  sudo chown -R $(whoami) /usr/local

# Features
Please replace this section with:
- a detailed description of your proposed feature
A current working methodology for brew on High Sierra
- the motivation for the feature
I would like to continue using Brew
- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)
I imagine I'm not the only one in this boat, particularly given the following previous issue:
https://github.com/Homebrew/brew/issues/3228
- what alternatives to the feature you have considered
No idea

**Comment by MikeMcQuaid** [comment]
`sudo chown -R $USER /usr/local/* /usr/local/.git; brew update --force`

**Comment by fligi7** [comment]
Sorry, still doesn't work. 

> $ sudo chown -R $(whoami) /usr/local/* /usr/local/.git; brew update --force
Error: /usr/local is not writable. You should change the
ownership and permissions of /usr/local back to your
user account:
  sudo chown -R $(whoami) /usr/local

**Comment by fligi7** [comment]
How can I uninstall without a) removing my brew packages/installs, and b) especially not removing dirs/files like the following says it's going to...

> Would delete:
==> /usr/bin/sudo /usr/bin/find /usr/local/Cellar /usr/local/Frameworks /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/share /usr/local/var -name .DS_Store -print
Would remove directories:
==> /usr/bin/sudo /usr/bin/find /usr/local/Cellar /usr/local/Frameworks /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/share /usr/local/var -depth -type d -empty -print

Those directories should not be deleted/removed with a brew uninstall. I can see it removing directories it has created solely for Brew (i.e. Cellar) but not the other directories.

**Comment by MikeMcQuaid** [comment]
What does `brew update-reset; brew update` output?

> You can't uninstall brew without deleting nearly everything in /usr/local/?

Yes.

**Comment by fligi7** [comment]
Wow, is that in the docs somewhere that I missed? Is there a way we could/should install that avoids that ultimate demise upon uninstall?

> $ brew update-reset; brew update
==> Fetching /usr/local...
remote: Counting objects: 4980, done.
remote: Compressing objects: 100% (1433/1433), done.
remote: Total 4980 (delta 3760), reused 4588 (delta 3403), pack-reused 0
Receiving objects: 100% (4980/4980), 799.08 KiB | 6.24 MiB/s, done.
Resolving deltas: 100% (3760/3760), completed with 375 local objects.
From https://github.com/Homebrew/brew
   c458c90236..40e7ac2632  master     -> origin/master
 * [new tag]               1.3.8      -> 1.3.8
 * [new tag]               1.3.9      -> 1.3.9
 * [new tag]               1.4.0      -> 1.4.0
 * [new tag]               1.4.1      -> 1.4.1
 * [new tag]               1.4.2      -> 1.4.2
 * [new tag]               1.4.3      -> 1.4.3
 * [new tag]               1.5.0      -> 1.5.0
 * [new tag]               1.5.1      -> 1.5.1
 * [new tag]               1.5.10     -> 1.5.10
 * [new tag]               1.5.11     -> 1.5.11
 * [new tag]               1.5.12     -> 1.5.12
 * [new tag]               1.5.13     -> 1.5.13
 * [new tag]               1.5.2      -> 1.5.2
 * [new tag]               1.5.3      -> 1.5.3
 * [new tag]               1.5.4      -> 1.5.4
 * [new tag]               1.5.5      -> 1.5.5
 * [new tag]               1.5.6      -> 1.5.6
 * [new tag]               1.5.7      -> 1.5.7
 * [new tag]               1.5.8      -> 1.5.8
 * [new tag]               1.5.9      -> 1.5.9

> ==> Resetting /usr/local...
error: unable to unlink old '.gitignore': Permission denied
error: unable to unlink old '.travis.yml': Permission denied
error: unable to unlink old 'CONTRIBUTING.md': Permission denied
error: unable to unlink old 'README.md': Permission denied
Branch master set up to track remote branch master from origin.
Reset branch 'master'

> ==> Fetching /usr/local/Library/Taps/homebrew/homebrew-core...
remote: Counting objects: 42159, done.
remote: Compressing objects: 100% (11971/11971), done.
remote: Total 42159 (delta 31271), reused 41021 (delta 30176), pack-reused 0
Receiving objects: 100% (42159/42159), 12.70 MiB | 10.46 MiB/s, done.
Resolving deltas: 100% (31271/31271), completed with 2140 local objects.
From https://github.com/Homebrew/homebrew-core
   58928f341..f655eff82  master     -> origin/master

> ==> Resetting /usr/local/Library/Taps/homebrew/homebrew-core...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

>Error: /usr/local is not writable. You should change the
ownership and permissions of /usr/local back to your
user account:
  sudo chown -R $(whoami) /usr/local

**Comment by MikeMcQuaid** [comment]
> error: unable to unlink old '.gitignore': Permission denied
> error: unable to unlink old '.travis.yml': Permission denied
> error: unable to unlink old 'CONTRIBUTING.md': Permission denied
> error: unable to unlink old 'README.md': Permission denied

You'll need to take ownership of all these and other files in `/usr/local`

**Comment by MikeMcQuaid** [comment]
Sorry, you'll need to figure out the rest yourself, I have no idea what's going on.
