### ISSUE TITLE
HOMEBREW_BUILD_FROM_SOURCE with empty value being ignored

### ISSUE THREAD

**Issue by jeroenk** [Homebrew/brew#4015]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 1.5.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f4e22e28d3b65a6c8dbb0f270bb6d262a2429d6
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0ed72ab5542455989d7809d4c3a5f9bca294543b
Core tap last commit: 64 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_60, 1.8.0_05
macOS: 10.13.4-x86_64
Xcode: 9.3
CLT: 9.3.0.0.1.1521514116
X11: 2.7.11 => /opt/X11
```

- What you were trying to do (and why)

I'm trying to build all packages and their dependencies from source, and I set environment variable `HOMEBREW_BUILD_FROM_SOURCE` to this purpose, unfortunately the variable is being ignored and pre-build versions of dependencies are being downloaded. The same also happens during upgrades when the environment variable is set.

- What happened (include command output)

Either (this is just the start of the output):
```
$ HOMEBREW_BUILD_FROM_SOURCE= brew install --build-from-source wget
==> Installing dependencies for wget: gettext, libunistring, libidn2, openssl
==> Installing wget dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.high_sierr

```

Or (again just the start of the output):
```
$ export HOMEBREW_BUILD_FROM_SOURCE=
$ brew install --build-from-source wget
==> Installing dependencies for wget: gettext, libunistring, libidn2, openssl
==> Installing wget dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.high_sierr

```

- What you expected to happen

I expected the source of (of in this case) gettext to be downloaded and it being built, instead of a pre-build version being downloaded. This happens with every dependency of very package I'm trying to install.

- Step-by-step reproduction instructions (by running `brew` commands)

See above.

**Comment by GauthamGoli** [comment]
You should be using `export HOMEBREW_BUILD_FROM_SOURCE=1`

**Comment by GauthamGoli** [comment]
1. Try uninstalling `wget` first. then 
 `brew uninstall --force --ignore-dependencies wget`

2. Set env var: Don't ignore the `1`
`export HOMEBREW_BUILD_FROM_SOURCE=1`  

3. Install
`brew install wget`

**Comment by MikeMcQuaid** [comment]
We generally treat empty environment variables as not existing so: yep, please do as @GauthamGoli suggests. I'm open to any suggested changes to documentation to make this more clear.

**Comment by jeroenk** [comment]
Adding an example to the documentation and being explicit about empty variables would help a lot. 

Also this is changed behaviour compared to roughly a year back, and the way to compile from source has changed quite a few times by now, which is pretty annoying.

**Comment by jeroenk** [comment]
> Regardless, as mentioned in brew doctor, HOMEBREW_BUILD_FROM_SOURCE is not a supported configuration.

brew doctor also ignored the variable when it was set to something empty.

> Where specifically?

man page at the point where the variable is being mentioned.

**Comment by MikeMcQuaid** [comment]
> brew doctor also ignored the variable when it was set to something empty.

Yep, this applies to all environment variables checked this way.

> man page at the point where the variable is being mentioned.

I'll have a think; we'll need something that applies to all environment variables.
