### ISSUE TITLE
Migrate to secure and sandboxed installation - Feature

### ISSUE THREAD

**Issue by haraldrudell** [Homebrew/brew#4016]
# Feature

Reduce the risk of being hacked by malicious software by

a safer method of installation, where:

> a. my macOS user and the scary software she runs does not have **write privileges** to directories included in PATH
> b. install scripts off the street cannot shadow executables like **sudo**
> 
> It is a mystery why this is not the default way of doing things. It's currently less safe than Windows

Therefore,
1. I created a separate non-Administrator **brew** user and configured brew to be local in this account
2. Then, whenever configuring brew, that is done in a Terminal window: login brew…

steps (I see people on the Internet wondering how to do this):

in Terminal:

**login brew
mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
export PATH=$PATH:~/homebrew/bin**
test:
**brew config**
HOMEBREW_PREFIX: /Users/brew/homebrew
HOMEBREW_REPOSITORY: /Users/brew/homebrew
HOMEBREW_CELLAR: /Users/brew/homebrew/Cellar
**brew --cache**
/Users/brew/Library/Caches/Homebrew
**brew update**
pauses for like 30 s, eventually completes

For other users, that want to execute installed software:
**export PATH=$PATH:/Users/brew/homebrew/bin**

Areas of trouble:
man
bash completion
include

CHECKY CHECKLIST BELOW HERE

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

**Comment by woodruffw** [comment]
As I've pointed out to some other people, this is *not* a security issue from Homebrew's perspective:

* Any time you run a program on macOS (or any other system), you are trusting it to not modify your shell initialization files, startup applications, user settings, and so forth. This is a general failure of the "user" model and has nothing to do with Homebrew.

* One of the standard *expectations* when using Homebrew is that it overrides your system's default software -- most users *want* our `bash` to supersede the system bash, our `ruby`, `emacs`, etc. 

Thanks for the issue, but, for the reasons above, we won't be making the changes you've suggested. That being said, we'll continue to support installing Homebrew as a separate user.

**Comment by haraldrudell** [comment]
I understand.

Another trouble discovered is that if install is not done to the default prefix **/usr/local** “everything” has to be compiled from source, which is somewhat slow

**Comment by chdiza** [comment]
> if install is not done to the default prefix /usr/local “everything” has to be compiled from source

This is not true.  If you replace "everything" with "some things" it would be true.

**Comment by woodruffw** [comment]
What @chdiza said is correct -- most bottles require the `/usr/local` prefix, but there are some that don't (specifically the ones marked bottle `:unneeded` and variants of `cellar :any`). That's mostly a reality of difficulties/complexities in relocation, although we've probably also been overly conservative in the interest of not causing weird failures for end users.

If you're looking for ways to minimize the chance of shadowing programs on other users' accounts, my recommendation is to either remove `/usr/local/bin` from `/etc/paths` or reduce its position to at least below `/bin` and `/usr/bin`.

As for kernel modules: unfortunately, that comes with the territory. I think that's a large part of why we don't ship `osxfuse` in any of the core taps (or any other kexts that I'm aware of).

**Comment by MikeMcQuaid** [comment]
> If you're looking for ways to minimize the chance of shadowing programs on other users' accounts, my recommendation is to either remove /usr/local/bin from /etc/paths or reduce its position to at least below /bin and /usr/bin.

Yep, this. 

I'll just gently note I know people who are literally routinely attacked by nation states but yet still run Homebrew in it's default prefix and PATH configuration. If someone gets to run arbitrary code on your machine as your user there's many other ways of them owning you.
