### ISSUE TITLE
After brew update php@7.1 redis not exsiting..cant fount how to install it..

### ISSUE THREAD

**Issue by pauliuslukosiunas** [Homebrew/brew#4018]
After brew update php@7.1 redis not exsiting..cant fount how to install it..

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
