### ISSUE TITLE
after brew Doctor

### ISSUE THREAD

**Issue by bioinfo24091** [Homebrew/brew#4019]
after running `brew doctor` and it suggested me to remove many directories, and unfortunately i have done what he have asked me , i removed them all even though it seems its important to the system, i have download all dependencies again and run the update many time but im kind of stuck when i try to `make` a tool 

this Error keep showing up from everywhere , anyone have an idea how to fix this 
```
dyld: Library not loaded: /usr/local/lib/libintl.8.dylib
  Referenced from: /usr/local/bin/ar
  Reason: image not found
** FATAL ERROR **: Problem adding to archive [6][ar -cSq c4_model_archive.a /Users/mohanad/Documents/TOOLS/maker/exe/exonerate-2.2.0/codegen/i386_45_apple_45_darwin17_46_5_46_0/optimal_58_ungapped_58_dna2dna_32_find_32_score.o]
exiting ...
make[2]: *** [Makefile:364: c4_model_archive.h] Error 1
make[2]: Leaving directory '/Users/mohanad/Documents/TOOLS/maker/exe/exonerate-2.2.0/src/program'
make[1]: *** [Makefile:116: all-recursive] Error 1
make[1]: Leaving directory '/Users/mohanad/Documents/TOOLS/maker/exe/exonerate-2.2.0/src'
make: *** [Makefile:126: all-recursive] Error 1
```

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.
