### ISSUE TITLE
how install locales?

### ISSUE THREAD

**Issue by letarg0** [Homebrew/brew#4032]
I install program in mac os x, this is terminal program with encurses.
```
$ locale
LANG="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_CTYPE="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_ALL=
```
I have good locale in my system
```
$ set | grep UTF-8
LANG=pl_PL.UTF-8
```

but i still have my program in english language. How install my language locales files?

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

**Comment by letarg0** [comment]
This is not answer.
mutt not running in my language. What i must to do to using program?
