### ISSUE TITLE
Found Ruby file outside rangaofei/saka tap formula directory

### ISSUE THREAD

**Issue by AzhongLee** [Homebrew/brew#4040]
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Found Ruby file outside rangaofei/saka tap formula directory
(/usr/local/Homebrew/Library/Taps/rangaofei/homebrew-saka/Formula):
  /usr/local/Homebrew/Library/Taps/rangaofei/homebrew-saka/install.rb
  /usr/local/Homebrew/Library/Taps/rangaofei/homebrew-saka/sqrt.rb

**Comment by ilovezfs** [comment]
You can report this to the rangaofei/saka tap.

Always fill out the template in the future.
