### ISSUE TITLE
brew switch with new formula naming convention?

### ISSUE THREAD

**Issue by JesseLeite** [Homebrew/brew#4043]
Is the current brew switch implementation now obsolete with the new naming convention?

For example, to switch versions we currently have to:

```
brew unlink php@7.1
brew link --overwrite --force php@7.0
```

It would be sick if we `brew switch` using the new naming convention:

```
brew switch php@7.0
```

Or am I misunderstanding something?

**Comment by MikeMcQuaid** [comment]
> It would be sick if we brew switch using the new naming convention

`brew switch` isn't required there because they can both be installed side-by-side.

Please always fill in the issue template in future and ask questions like this in Discourse.

**Comment by JesseLeite** [comment]
>Please always fill in the issue template in future and ask questions like this in Discourse.

Sorry 😥

**Comment by MikeMcQuaid** [comment]
@JesseLeite That's ok! Thanks for the apology ❤️
