### ISSUE TITLE
Automatic reinstall on broken linkage

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#4054]
We should automatically reinstall formulae when we detect broken linkage after e.g. `brew upgrade`.

This requires [`brew linkage` to be faster](https://github.com/Homebrew/brew/issues/3008).

**Comment by scpeters** [comment]
I assume that the reinstall will be a build from source?

**Comment by ilovezfs** [comment]
@scpeters I think that's a last resort. First it should try just `brew upgrade` on whatever broke, then try to fill in opportunistic linkage with homebrew/core bottles, and only if both of those fail, fall back on a source build.

**Comment by AndrewMcBurney** [comment]
Hi @MikeMcQuaid,

I saw you linked the [brew linkage issue](https://github.com/Homebrew/brew/issues/3008) which I've been working on. Is this automatic-reinstall issue blocked until [the cache optimization PR](https://github.com/Homebrew/brew/pull/3720) is merged in?

My current internship is wrapping up, and I'll be returning to school within the next week. I won't have time to contribute to open-source projects once the school term starts to pick up.

Would it be possible to get my changes reviewed this weekend, and have the portable version of Ruby with DBM built?

I'm writing a blog post about my experiences finding the bottleneck and contrasting the different implementations (`SQLite3`, `pstore`, and `DBM`), which I'm hoping to publish next week. It would be great if the PR could be merged before then.

Thank you for the time you've devoted reviewing the multiple iterations of the PR, and for the subsequent feedback - it has been very helpful!

**Comment by MikeMcQuaid** [comment]
@AndrewMcBurney Annoyingly the slow bit blocking your PR is this:

> have the portable version of Ruby with DBM built?

It's been on my list for a while and I still need to get around to it. I think it's unlikely I'm going to be able to get it done and merged within a week but I'll try my best. If not, I'll finish off any parts of your PR that need done.

**Comment by MikeMcQuaid** [comment]
I no longer care about this.
