### ISSUE TITLE
Better integrate Homebrew Cask with Homebrew

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#4056]
Any `brew` command that can sensibly find output information related to casks (e.g. `brew search`) should do so. Additionally, all Cask commands like `brew cask search` should be sufficiently integrated into `brew search` that they are no longer needed. Finally, duplicated code like `download_strategy.rb` should be better shared between Homebrew Cask and Homebrew itself.\

Additionally, Homebrew/rubocop-cask should be moved into Homebrew/brew to ease RuboCop upgrades. This could be done by perhaps making `public_suffix` optional and using a simple regex when it’s not installed.

**Comment by MikeMcQuaid** [comment]
> Additionally, Homebrew/rubocop-cask should be moved into Homebrew/brew to ease RuboCop upgrades. This could be done by perhaps making public_suffix optional and using a simple regex when it’s not installed.

Added this.

**Comment by chdiza** [comment]
> Any brew command that can sensibly find output information related to casks (e.g. brew search) should do so

I would agree if "be able to" is inserted before the "do so".  This should be hidden behind a switch though.  I never use `cask` stuff, so I wouldn't want that to appear in search results, etc.

**Comment by MikeMcQuaid** [comment]
I consider this done by @reitermarkus. Nice work!

**Comment by MikeMcQuaid** [comment]
> Additionally, Homebrew/rubocop-cask should be moved into Homebrew/brew to ease RuboCop upgrades. This could be done by perhaps making public_suffix optional and using a simple regex when it’s not installed.

@reitermarkus This is the only bit I'd love to see addressed at some point 😉
