### ISSUE TITLE
Output all caveats at the end of a build

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#4057]
After `brew install` or `brew upgrade` multiple formulae we should group the caveats for all the formulae and output them at the end of the build.

**Comment by MikeMcQuaid** [comment]
@apjanke I'm open to either approach. I think doing both might be more obvious for now as long as a single formula doesn't have them duplicated.

**Comment by apjanke** [comment]
A single formula will not have them duplicated in this PR. It includes a check for "installed_count > 1".

**Comment by MikeMcQuaid** [comment]
@apjanke Yeh 👍 just reviewed this comment before the PR 😉
