### ISSUE TITLE
Improve `etc` handling

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#4060]
The `etc.install` and installation of `etc` files in bottles eliminates overwriting of existing files by appending `.default` but this it not ideal.

We should aim to overwrite existing files when possible when they haven't change from an existing version. For example, if poured from a bottle:
- `brew install wget` installs 1.0.0's configuration files into:
  - `$HOMEBREW_PREFIX/etc/wget` 
  - `$HOMEBREW_CELLAR/wget/1.0.0/.bottle/etc`
-`brew upgrade wget` installs 2.0.0's configuration files into:
  - `$HOMEBREW_PREFIX/etc/wget`. 
- The configuration files in `$HOMEBREW_PREFIX/etc/wget` should be compared with `$HOMEBREW_CELLAR/wget/1.0.0/.bottle/etc`. 
- If the collection of files in both `etc` directories are identical, the contents of the files in `$HOMEBREW_PREFIX/etc/wget` should be replaced with the contents of the files in`$HOMEBREW_CELLAR/wget/2.0.0/.bottle/etc`

Additionally, when we do create any new `.default` files in `$HOMEBREW_PREFIX/etc` we should notify the user that we've done so so they can update their configuration.

**Comment by aamarill** [comment]
Hello,

I am looking to make my first open source contribution. Is this a good issue to take on?
If not, feel free to point me other issues that might be good for someone that's new to open source.
Thanks!

**Comment by MikeMcQuaid** [comment]
@aamarill Any issue marked "help wanted" we'll welcome a pull request from you on. You don't need to ask first FYI and in future please don't post the same copy-pasted comment on multiple issues. Look forward to your PR(s)! ❤️ 🎉

**Comment by aamarill** [comment]
@MikeMcQuaid my apologies and thank you for the warm welcome. I am working on a few other issues, but once I free up some time I'll look around here :)

**Comment by whuang8** [comment]
@MikeMcQuaid Can you clarify your last bullet point? Am I interpreting it correctly with the revision below?

- If ~they~ **the collection of files in both `etc` directories** are identical, ~they~ the contents of the files in `$HOMEBREW_PREFIX/etc/wget` should be replaced with the contents **of the files in** `$HOMEBREW_CELLAR/wget/~1~2.0.0/.bottle/etc`

**Comment by MikeMcQuaid** [comment]
@whuang8 yes thanks edited my original comment!

**Comment by MikeMcQuaid** [comment]
I no longer care about this.
