### ISSUE TITLE
brew upgrade reports "Error" for pinned packages

### ISSUE THREAD

**Issue by bondolo** [Homebrew/brew#4063]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- Attempting to brew upgrade after pinning a package with brew pin
- ```
$ brew upgrade
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

Error: Not upgrading 1 pinned package:
wildfly-as 12.0.0.Final
==> No packages to upgrade
```

- expected 
```
$ brew upgrade
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

Warning: Not upgrading 1 pinned package:
wildfly-as 12.0.0.Final
==> No packages to upgrade
```


# Features
-  Since the upgrade continues the "Error: Not upgrading 1 pinned package" message should be issued as a "Warning"


We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

Brew Config:
HOMEBREW_VERSION: 1.6.0-15-g5005999
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 50059990e2b087c6c56fba4d2ea65070ef57d3d9
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 47aeb6c46040c9732ca489b0ae2b2ffd00ef1e49
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_VISUAL: /usr/local/bin/edit -w
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_162, 1.8.0_152, 1.7.0_80
macOS: 10.13.4-x86_64
CLT: N/A
Xcode: 9.3
XQuartz: 2.7.11 => /opt/X11

Brew Doctor (tcl/tk is from previous install of "R"):
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files :
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2

**Comment by MikeMcQuaid** [comment]
This is intentional. Use `brew upgrade --ignore-pinned` if desired.

**Comment by bondolo** [comment]
I guess I would expect something described as an error to stop the given process. Since the upgrade continues in spite of the "Error" a warning would seem more appropriate. In general, to me, error means "cannot continue. You say that use of error is intentional for this case, why error rather than warning? Exit code non-zero if unupgraded pinned perhaps? Is --ignored-pinned not the default for legacy reasons?

**Comment by MikeMcQuaid** [comment]
> I guess I would expect something described as an error to stop the given process.

It returns a non-zero exit code.

> Is --ignored-pinned not the default for legacy reasons?

It's not default because `brew pin` combined with `brew upgrade` often relies on packages built against a newer version that then break.

**Comment by bondolo** [comment]
Thank you for the explanation. It does feel unsatisfying and clunky but understandable.
