### ISSUE TITLE
Fail to install homebrew via command

### ISSUE THREAD

**Issue by iedwin** [Homebrew/brew#4065]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 
- What happened (include command output)
return error:
<img width="1293" alt="wx20180413-092514 2x" src="https://user-images.githubusercontent.com/17739715/38712225-c9783e00-3efc-11e8-9e0e-6d065289b7a7.png">

- What you expected to happen
Homebrew should be installed. My OS is 10.13.4
- Step-by-step reproduction instructions (by running `brew` commands)

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
You'll need to figure this out yourself I'm afraid.

**Comment by iedwin** [comment]
@MikeMcQuaid You're right. I added a syslink before to /usr/local/bin before and for some strange reason the  permission of the folder created by installation script is root. After I remove the syslink and changed all those folder permission to my current user by chown -R, all works now. 
Thanks a lot!
