### ISSUE TITLE
Installing brew with Xcode already installed still installs command line tools

### ISSUE THREAD

**Issue by chaNcharge** [Homebrew/brew#4078]
Running the regular installation on the homebrew webpage still installs the command line tools, even though I already have them included with Xcode. It may be because I'm using Xcode 9.4 beta, but it should still be able to work with it, since the installation page says it requires CLT **OR** Xcode. Why does homebrew need the separate command line tools if they're already included with Xcode?

Steps:
1. Install Xcode (I used the beta, not sure if that affects it)
2. Use the install command on the brew.sh homepage

What I expected: It shouldn't need to install command line tools.
What happened: It installed it anyway.

P.S: I did read the checklist, but this is a different kind of issue that occurs on installation.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.
