### ISSUE TITLE
Installing brew with Xcode already installed still installs command line tools

### ISSUE THREAD

**Issue by chaNcharge** [Homebrew/brew#4079]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I installed python 2 and 3 with homebrew and they all required building from source, which took an extremely long time. I reinstalled homebrew and it installs the CLT even though they are already in the Xcode app. I checked `xcode-select -p` and it points to my xcode app. `brew config` even detects it. 
- What happened (include command output)
`Warning: Building python from source: The bottle needs the Apple Command Line Tools to be installed.`
- What you expected to happen
It should install fine without the separate CLT installed if its able to use the CLT that comes with Xcode. Same goes for `python` and `python@2`
- Step-by-step reproduction instructions (by running `brew` commands)
1. Install xcode
2. Notice how it installs the CLT anyway. Lets say I deleted it to remove unnecessary storage.
3. `brew install python python@2`

# Features
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)
Running the regular installation on the homebrew webpage still installs the command line tools, even though I already have them included with Xcode. It may be because I'm using Xcode 9.4 beta, but it should still be able to work with it, since the installation page says it requires CLT **OR** Xcode. Why does homebrew need the separate command line tools if they're already included with Xcode? Aren't Xcode CLT and the separate CLT the same?

`brew config` output:
```
HOMEBREW_VERSION: 1.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: e3cd9c972f55e9953830f98b4b64eb4ba10727b1
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 76df491c7ab0bca882b46f6f0bbf5fe2d5489175
Core tap last commit: 21 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_162
macOS: 10.13.4-x86_64
CLT: N/A
Xcode: 9.4
XQuartz: N/A
```
`brew doctor`:
```
Your system is ready to brew.
```

**Comment by MikeMcQuaid** [comment]
> I reinstalled homebrew and it installs the CLT even though they are already in the Xcode app.

The Xcode application does not include all the CLT we need.

> brew config even detects it.

It does not detect the CLT though:

> CLT: N/A

> It should install fine without the separate CLT installed if its able to use the CLT that comes with Xcode. 

You can use Homebrew without the CLT on the latest version of macOS. We still install it anyway, though in the installer as there is no harm and it takes up very little space.

> Same goes for python and python@2

This is not possible because of how our binary packages are created. If you can create a pull request with a solution: it would be welcome.
