### ISSUE TITLE
[feature request] - include --verbose tag by default

### ISSUE THREAD

**Issue by tmm2018** [Homebrew/brew#4080]
greetings

it would be nice that whenever you install something on mac using homebrew (no matter if you are using "normal" installation or cask, etc.):

the terminal dumps out all installation data, similarly to what would happen with any linux package manager. this can be achieved with --verbose tag, as far as i am concerned. so an option would be adding it by default, and then adding some extra features
thank you so much :)

**Comment by MikeMcQuaid** [comment]
You can set `HOMEBREW_VERBOSE` in your terminal.

In future please always fill out the issue template.

**Comment by tmm2018** [comment]
dear @MikeMcQuaid 

- thank you so much for the time taken to review my contribution
- I will try to go along with the homebrew contritbution standards next time and fill out the issue template
- although we may sometimes have ideas that we may think to lead to positive improvements on a specific tool, not always we have to agree on everything

thank you so much for helping us making opensource world a better place

**Comment by MikeMcQuaid** [comment]
> thank you so much for helping us making opensource world a better place

Thanks for the kind words @tmm2018!
