### ISSUE TITLE
'pkg-config: command not found' during brew install, but not manual configuration

### ISSUE THREAD

**Issue by rlue** [Homebrew/brew#409]
First off, forgive me if I'm missing something obvious, or this doesn't technically qualify as an issue – I wasn't sure where else to ask.

I'm trying to install elinks with ECMAScript support. I'm not sure this is relevant, but I did a little bit of tweaking in `brew edit elinks` to get it to download the latest experimental build, 0.13 (rather than 0.12pre6, which is what's on tap).

### Configuring manually

To make sure everything would compile correctly, I first manually downloaded the source myself, running `./configure` and then `make`. It didn't recognize my SpiderMonkey install, as evidenced by the following `./config` output:

    checking for pkg-config... /usr/local/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    ...
    checking for SpiderMonkey (1.8.5 or later) in pkg-config mozjs185... no

To fix that, I set the following environment variables,

    export PKG_CONFIG=pkg-config
    export PKG_CONFIG_PATH=/usr/local/Cellar/nspr/4.12/lib/pkgconfig:/usr/local/Cellar/spidermonkey/1.8.5_1/lib/pkgconfig

which got it to work:

    checking for pkg-config... /usr/local/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    ...
    checking for SpiderMonkey (1.8.5 or later) in pkg-config mozjs185... yes

### Homebrew install fails (to find pkg-config)

But then when I go to `brew install --devel -v elinks`, I get the following output:

    checking pkg-config is at least version 0.9.0... ./configure: line 4211: pkg-config: command not found
    no
    ...
    checking for SpiderMonkey (1.8.5 or later) in pkg-config mozjs185... no

Oddly, the output from Homebrew's configuration skips the 'checking for pkg-config' line:

    checking for sparse... no
    checking pkg-config is at least version 0.9.0... ./configure: line 4211: pkg-config: command not found
    no

To my knowledge, I'm working with the exact same source tarball. Any ideas?

**Comment by mistydemeo** [comment]
Homebrew is designed not to allow packages to find other software that wasn't specified as a dependency; you'll need to add these lines to the dependencies for it to work:

```ruby
depends_on "pkg-config" => "build"
depends_on "spidermonkey"
```

**Comment by rlue** [comment]
holy balls, that was fast. you're amazing!

**Comment by DomT4** [comment]
```ruby
depends_on "pkg-config" => :build
```
Just to clarify 😺.
