### ISSUE TITLE
brew style & brew audit do not catch <<-EOS.undent

### ISSUE THREAD

**Issue by BenjaminHCCarr** [Homebrew/brew#4094]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

---

It would be helpful to those who are more than casual but not daily commiters to have either `brew audit` or `brew style` catch `<<-EOS.undent`. I hope this is as an easy `rubocop` update, but don't know where to `PR` for that.

Homebrew/brew#3738 shows a simple bash `grep -RIF .undent "$(brew --repo)"` shows the Formulas with errors, it would be useful for those of us editing the "top" of the Formulas and running the correct pipeline to catch this before the install fails:

```
tyr:~/Code/git/Mine/homebrew-tap/Formula (master) benc$ vim toralpha.rb 
tyr:~/Code/git/Mine/homebrew-tap/Formula (master) benc$ brew style --fix --strict !$
brew style --fix --strict toralpha.rb
==> Installing or updating 'rubocop' gem
Fetching: rubocop-0.55.0.gem (100%)
Successfully installed rubocop-0.55.0
1 gem installed
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.6-compliant syntax, but you are running 2.3.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

1 file inspected, no offenses detected
tyr:~/Code/git/Mine/homebrew-tap/Formula (master) benc$ brew audit --fix --strict toralpha.rb
tyr:~/Code/git/Mine/homebrew-tap/Formula (master) benc$ brew upgrade ./toralpha.rb
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
toralpha 0.3.3.4-alpha -> 0.3.3.5-rc
==> Upgrading toralpha 
==> Downloading https://tor.eff.org/dist/tor-0.3.3.5-rc.tar.gz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/toralpha/0.3.3
==> make install
Error: Failed to install plist file
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/Users/benc/Code/git/Mine/homebrew-tap/Formula/toralpha.rb:33:in `caveats'
Or, even better, submit a PR to fix it!
```
---
```
tyr:~/Code/git/Mine/homebrew-tap/Formula (master) benc$ brew config
HOMEBREW_VERSION: 1.6.1-28-g1d9746d
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1d9746db84d63acd4fd7c2b9b28569892d9a0d9f
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe1bd75adc301de3277ad15e9fda5590c5323f8f
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 1.8.0_102
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: 8.2.1
XQuartz: 2.7.11 => /opt/X11
```
---

**Comment by scpeters** [comment]
If you're interested in implementing this yourself, there is a folder called `rubocops`, and the [homepage_cop.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/rubocops/homepage_cop.rb) seems like a relevant example, in that it uses regexes to complain about stuff.

**Comment by BenjaminHCCarr** [comment]
Thanks @scpeters for the link.
Wondering if a *maintainer* can comment on using the [caveats_cop.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/rubocops/caveats_cop.rb) as a basis for a `plist_cop.rb`.
Given the high variability of both the `caveats` and `plist` blocks, is there a better place to check for `<<-EOS.undent` than in a `plist_cop.rb` or would a generic `EOS_cop.rb` make more sense?

As the migration away from EOS.undent is mostly over, this may not be an issue for much longer except in `Alehouse` and private taps.

**Comment by MikeMcQuaid** [comment]
> would a generic EOS_cop.rb make more sense?

It would, yep. 

> As the migration away from EOS.undent is mostly over, this may not be an issue for much longer except in Alehouse and private taps.

Agreed. As a result we'll accept a PR for this but won't be working on it ourselves.
