### ISSUE TITLE
Indicate whether formulas are installed in the output of `brew search --desc`

### ISSUE THREAD

**Issue by Zirro** [Homebrew/brew#4095]
When `brew search [formula]` is used, the list of results includes a helpful green tick indicating that a formula already is installed. However, this tick does not appear when the `--desc` flag is used.

I think it would be helpful and consistent if the indicator for installed formulas were to be shown in both cases.

**Comment by MikeMcQuaid** [comment]
Please fill out the issue template: https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Zirro** [comment]
Oh, my apologies. I read through it twice, but as I understood this to be a feature request rather than a bug report I got the impression that only the second section was relevant. Here is the remaining information:

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.6.1-28-g1d9746d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1d9746db84d63acd4fd7c2b9b28569892d9a0d9f
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7898cd2f8bdbcc79207fc72aeafb8f08af5b0fbe
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144
macOS: 10.13.5-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3
XQuartz: 2.7.11 => /opt/X11
```

```
$ brew doctor
Your system is ready to brew.
```

The relevant commands and output truncated to four lines:

```
$ brew search gnu
==> Searching local taps...
gnu-barcode ✔                  feedgnuplot                    gnupg
gnu-chess ✔                    gnu-apl                        gnupg-pkcs11-scd
gnu-go ✔                       gnu-cobol                      gnupg@1.4
```

```
$ brew search --desc gnu
apple-gcc42: GNU compiler collection
argtable: ANSI C library for parsing GNU-style command-line options
arm-linux-gnueabihf-binutils: FSF/GNU binutils for cross-compiling to arm-linux
automake: Tool for generating GNU Standards-compliant Makefiles
```

**Comment by MikeMcQuaid** [comment]
Thanks, @Zirro. My take after playing with this is that the output is sufficiently different that a ✅ would be a bit weird/ugly but I'm open to input from other @Homebrew/maintainers.

**Comment by Zirro** [comment]
An alternative might be to change the sorting order and place installed formulas on top. That would also be consistent with the column-based listing, though it might require a separator between installed and non-installed formulas to clarify the difference in this case.

**Comment by javian** [comment]
How about something like this with appropriate colours ?
```
$ brew search --desc gnu
✓ apple-gcc42: GNU compiler collection
x argtable: ANSI C library for parsing GNU-style command-line options
x arm-linux-gnueabihf-binutils: FSF/GNU binutils for cross-compiling to arm-linux
✓ automake: Tool for generating GNU Standards-compliant Makefiles
```

**Comment by fxcoudert** [comment]
Most often, when you search for a formula, it's because you don't have it. So having lots of red `x` show up just looks bad. Also, the meaning could be unclear: does it mean the formula is not available? not working?

**Comment by MikeMcQuaid** [comment]
Passing on this for now, sorry!
