### ISSUE TITLE
check for symlinks

### ISSUE THREAD

**Issue by cbfiddle** [Homebrew/brew#4096]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I installed brew on a system where, unknown to me, /usr/local/bin was a symlink.
- What happened (include command output)
brew happily installed things (e.g. mariadb, marathon-swift) in the pointed to location
the result is that the installed symlinks of the form ../Cellar/... are broken
because ../Cellar is not /usr/local/Cellar.
- What you expected to happen
What should happen is that brew should check for symlinks and warn the user, especially if the links are inconsistent in a way that would break the ../Cellar symlinks.
- Step-by-step reproduction instructions (by running `brew` commands)
on a system without brew, make /usr/local/bin a symlink to /foo/bin and create these directories.
install brew
brew install marathon-swift
look at /usr/local/bin and see symlinks ../Cellar, but Cellar is not in /foo

HOMEBREW_VERSION: 1.6.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5a2817cb023ca5e929fe030d423002992bdabf1b
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7898cd2f8bdbcc79207fc72aeafb8f08af5b0fbe
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_121, 1.7.0_45
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: 2.7.11 => /opt/X11

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have MacPorts or Fink installed:
  /sw/bin/fink

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

**Comment by MikeMcQuaid** [comment]
> What should happen is that brew should check for symlinks and warn the user, especially if the links are inconsistent in a way that would break the ../Cellar symlinks.

We'll consider doing this in future if this is problem for more users. Thanks!
