### ISSUE TITLE
undefined method `revision' for #<BottleSpecification:0x000001030abf28>

### ISSUE THREAD

**Issue by Jonas-Mui** [Homebrew/brew#4097]
use command:brew unistall,upgrade... then error

https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autossh.rb:10:in `block in <class:Autossh>'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:101:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:101:in `bottle'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2086:in `bottle'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autossh.rb:8:in `<class:Autossh>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autossh.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1388:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:35:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) this issue may be reopened.
