### ISSUE TITLE
cURL SSL_ERROR_SYSCALL (OpenSSL\LibreSSL)

### ISSUE THREAD

**Issue by y0y0z** [Homebrew/brew#4099]
seems like there is some inconsistency with curl (binary itself) or\and brew use of curl.
i installed the latest curl and made sure it is in my path environment variable
```bash
$ brew install curl
Warning: curl 7.59.0 is already installed and up-to-date

$ which curl
/usr/local/opt/curl/bin/curl

$ curl --version
curl 7.59.0 (x86_64-apple-darwin17.5.0) libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.11 libidn2/2.0.4 nghttp2/1.31.1
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
```

yet, when i look at my brew configurations, i see that [curl is using a different path](https://github.com/Homebrew/brew/issues/3433) (`/usr/bin/curl`) then the above (`/usr/local/opt/curl/bin/curl`)
```bash
$ brew config
HOMEBREW_VERSION: 1.6.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5a2817cb023ca5e929fe030d423002992bdabf1b
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 94d798a38c48bc5edb49c6c90cfa2a73f684f3ee
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=~/Applications
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3
XQuartz: N/A
```

regardless, when i try to use either of which i get the `SSL_ERROR_SYSCALL` error

```bash
$ /usr/bin/curl https://statics.teams.microsoft.com/production-osx/1.1.00.8752/Teams_osx.dmg > /tmp/test.file
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

$ /usr/local/opt/curl/bin/curl https://statics.teams.microsoft.com/production-osx/1.1.00.8752/Teams_osx.dmg > /tmp/test.file
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```
yet, i have no problem downloading the file using wget.

note sure whether it is a problem with curl itself, as it seems the issue happens regardless on which curl binary is used.

1. is it a curl bug generally, or is it specific to macos?
2. when i pass the `--no-alpn` to curl it bypasses the issue. how can i pass curl parameters when using brew? (placing the parameter within `~/.curlrc` is honored when using curl binary but not when curl is invoked via brew)

**UPDATE**
setting `HOMEBREW_FORCE_BREWED_CURL=1`, is reflected in `brew config` yet, the issue still occurs. 

i came across the issue when running a cask formula
```bash
$ brew cask install microsoft-teams
```

**Comment by MikeMcQuaid** [comment]
> yet, when i look at my brew configurations, i see that curl is using a different path (/usr/bin/curl) then the above (/usr/local/opt/curl/bin/curl)
> setting HOMEBREW_FORCE_BREWED_CURL=1, is reflected in brew config yet, the issue still occurs.

This is intentional.

> $ /usr/bin/curl https://statics.teams.microsoft.com/production-osx/1.1.00.8752/Teams_osx.dmg > /tmp/test.file
> curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
> 
> $ /usr/local/opt/curl/bin/curl https://statics.teams.microsoft.com/production-osx/1.1.00.8752/Teams_osx.dmg > /tmp/test.file
> curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

This is an issue specific to your machine (not Homebrew) you'll need to figure out yourself, I'm afraid.

**Comment by y0y0z** [comment]
@MikeMcQuaid: just to be sure, were you able to reproduce it or not?
and another unrelated question, how can specify which ruby binary brew is using. meaning, when executing `brew config` the `Homebrew Ruby:` will be point to the ruby which i installed via brew?

**Comment by MikeMcQuaid** [comment]
> just to be sure, were you able to reproduce it or not?

I cannot.

> can i pass the --no-alpn to curl when it used by brew?

No, sorry.

> how can specify which ruby binary brew is using

You cannot change this. This is intentional. We do not support using custom Rubies.

**Comment by y0y0z** [comment]
@MikeMcQuaid: 

> I cannot.
meaning that you didn't get any error when running the curl command above without `--no-alpn`.
correct?

thank you.

**Comment by MikeMcQuaid** [comment]
> thank you.

You are welcome.

**Comment by y0y0z** [comment]
@MikeMcQuaid: but why curl does not honor `~/.curlrc`? (if it would have honor the file, i could bypass the issue)

**Comment by MikeMcQuaid** [comment]
@y0y0z You must set `HOMEBREW_CURLRC`.

**Comment by y0y0z** [comment]
@MikeMcQuaid thank you!

**Comment by y0y0z** [comment]
i still didn't find a permanent fix for the issue, but here is why i did in order to bypass my issue.

```bash
echo '--no-alpn' > ~/.curlrc
export HOMEBREW_CURLRC=1
brew cask install ...
```
