### ISSUE TITLE
brew hangs on clean installation

### ISSUE THREAD

**Issue by SirWindfield** [Homebrew/brew#4100]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?
---
I am trying to install homebrew on a clean installation of macOS High Sierra. I use the command listed on brew.sh. As soon as I press enter, the terminal kind of "hangs". No output is given and the script will run indefinitely. I downloaded the file and debugged it. The call that makes the script hang is 
```ruby
Kernel.system "/usr/bin/sudo -n -v 2>/dev/null"
at_exit { Kernel.system "/usr/bin/sudo", "-k" } unless $?.success?
```
Running `sudo -n -v ` alone hangs the terminal. The command doesn't exit.

**Comment by MikeMcQuaid** [comment]
I can't reproduce on my machine. You'll need to figure out why that's the case for you yourself, I'm afraid.

**Comment by SirWindfield** [comment]
That sucks. I have been googling and trying it out for the past 2 days. 
Would you mind giving me more information on your system? Which ruby version do you have installed by default? 
Does `sudo -v -n` hang or exit?

**Comment by MikeMcQuaid** [comment]
> Does sudo -v -n hang or exit?

It prompts for a password. If I enter a password it exits.



> Would you mind giving me more information on your system?

High Sierra with the default system Ruby.

**Comment by SirWindfield** [comment]
Looks like Sudo is the problem. It just doesn't prompt for a password.
