### ISSUE TITLE
runtime_dependencies of uninstalled formulae don't include indirect recommended or optional deps

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#4124]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
iMac-TMP:~ joe$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

```
iMac-TMP:~ joe$ brew config
HOMEBREW_VERSION: 1.6.2-47-g9b56b13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9b56b133a546d0d40cd6b020290f6a59fc14729f
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 661320f1740ef0411bddbc2d8ea276a362a98ce7
Core tap last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEVELOPER: 1
HOMEBREW_FORCE_VENDOR_RUBY: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MERGE: 1
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_SANDBOX: 1
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 10.0.1, 9.0.1, 1.8.0_152, 1.7.0_80
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: 8.2.1
XQuartz: 2.7.11 => /opt/X11
iMac-TMP:~ joe$ 
```

To help us debug your issue please explain:

- What you were trying to do (and why)

See `brew install emscripten` fail if node is built `--with-openssl@1.1` since emscripten depends on python@2 and python@2 depends on openssl (1.0) because we were discussing whether to continue to support a shared openssl option in the node formula given that at least one of its reverse dependencies has a recursive dependency on openssl 1.0.

- What happened (include command output)

`brew install emscripten` succeeded

https://gist.github.com/ilovezfs/9eff147b5d10a3bc4c17bc95bb3758dd
- What you expected to happen

I expected the error
```
iMac-TMP:Homebrew joe$ brew install emscripten
Error: emscripten contains conflicting version recursive dependencies:
  openssl, openssl@1.1
View these with `brew deps --tree emscripten`.
```

- Step-by-step reproduction instructions (by running `brew` commands)

```
brew install --with-openssl@1.1 node
brew install emscripten
```

Note that this problem goes beyond non-default options and affects any indirect recommended dependencies as well. So for example

```
irb(main):001:0> :virtualpg.f.runtime_dependencies
=> [#<Dependency: "proj" []>, #<Dependency: "gdbm" []>, #<Dependency: "openssl" []>, #<Dependency: "readline" []>, #<Dependency: "sqlite" []>, #<Dependency: "python@2" []>, #<Dependency: "geos" []>, #<Dependency: "libspatialite" []>, #<Dependency: "postgresql" []>, #<Dependency: "json-c" []>, #<Dependency: "pcre" []>, #<Dependency: "postgis" []>]
irb(main):002:0>
```
despite the fact that virtualpg depends on libspatialite, which has recommended dependencies on freexl and libxml2.

```
irb(main):002:0> :libspatialite.f.runtime_dependencies
=> [#<Dependency: "proj" []>, #<Dependency: "gdbm" []>, #<Dependency: "openssl" []>, #<Dependency: "readline" []>, #<Dependency: "sqlite" []>, #<Dependency: "python@2" []>, #<Dependency: "geos" []>, #<Dependency: "libxml2" [:recommended]>, #<Dependency: "freexl" [:recommended]>]
irb(main):003:0> 
```
Only libspatialite's required dependencies (geos, proj and sqlite) show up in the runtime dependencies of virtualpg.

**Comment by sjackman** [comment]
Certainly seems to me like a bug that `:recommended` dependencies aren't listed. It seems correct that `:optional` dependencies are not listed (only specified with `--with-foo`).

**Comment by ilovezfs** [comment]
For optional and recommended it "should" reflect the actual install receipt of the dependency if it's installed.
