### ISSUE TITLE
Error initial install on macOS High Sierra 10.13.4 opening "Library/Homebrew/test/support/fixtures/cask/transmission-2.61.dmg"

### ISSUE THREAD

**Issue by morillo** [Homebrew/brew#4129]
Running initial install on a brand new MacBook Pro with macOS High Sierra 10.13.4 I do get the following output:

```
carlos-MBP15:~ carlos$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at b1a92ba14 Merge pull request #3987 from GauthamGoli/bump-formula-pr-args
error: open("Library/Homebrew/test/support/fixtures/cask/transmission-2.61.dmg"): Operation not permitted
fatal: Unable to process path Library/Homebrew/test/support/fixtures/cask/transmission-2.61.dmg
Cannot save the current worktree state
Error: Could not 'git stash' in /usr/local/Homebrew!
Please stash/commit manually if you need to keep your changes or, if not, run:
  cd /usr/local/Homebrew
  git reset --hard origin/master
Failed during: /usr/local/bin/brew update --force
carlos-MBP15:~ carlos$ 
```

I have tried several time and Google for a workaround and also the forum on https://brew.sh/ with no luck.

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template.



> error: open("Library/Homebrew/test/support/fixtures/cask/transmission-2.61.dmg"): Operation not permitted

You have a permissions issue you will need to figure out and fix yourself.

**Comment by MikeMcQuaid** [comment]
The Homebrew installer cannot handle all possible existing configurations and it works for the vast majority of users. More importantly, though, we're not a commercial product and it's not on us to better document or fix this when you've not given us enough information (particularly when you did not follow the instructions requested when you created this issue).
