### ISSUE TITLE
brew update fails when using Include in ssh config

### ISSUE THREAD

**Issue by poochiethecat** [Homebrew/brew#4132]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

`brew doctor`
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/poochiethecat/.pyenv/shims/icu-config
  /Users/poochiethecat/.pyenv/shims/libpng16-config
  /Users/poochiethecat/.pyenv/shims/llvm-config
  /Users/poochiethecat/.pyenv/shims/ncurses5-config
  /Users/poochiethecat/.pyenv/shims/ncursesw5-config
  /Users/poochiethecat/.pyenv/shims/ncursesw6-config
  /Users/poochiethecat/.pyenv/shims/pcre-config
  /Users/poochiethecat/.pyenv/shims/python-config
  /Users/poochiethecat/.pyenv/shims/python2-config
  /Users/poochiethecat/.pyenv/shims/python2.7-config
  /Users/poochiethecat/.pyenv/shims/python3-config
  /Users/poochiethecat/.pyenv/shims/python3.6-config
  /Users/poochiethecat/.pyenv/shims/python3.6m-config
  /Users/poochiethecat/anaconda2/bin/curl-config
  /Users/poochiethecat/anaconda2/bin/freetype-config
  /Users/poochiethecat/anaconda2/bin/icu-config
  /Users/poochiethecat/anaconda2/bin/libdynd-config
  /Users/poochiethecat/anaconda2/bin/libpng-config
  /Users/poochiethecat/anaconda2/bin/libpng16-config
  /Users/poochiethecat/anaconda2/bin/python-config
  /Users/poochiethecat/anaconda2/bin/python2-config
  /Users/poochiethecat/anaconda2/bin/python2.7-config
  /Users/poochiethecat/anaconda2/bin/xml2-config
  /Users/poochiethecat/anaconda2/bin/xslt-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  clingo
  numpy
  ruby

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install emacs

Run `brew missing` for more details.
```
`brew missing`
`auctex: emacs`

Unlinked kegs are dependencies that some other kegs require, but that I have other versions/management systems set up to handle.
 - clingo -> required by ocaml and aspcud, would override `/usr/local/bin/clasp` belonging to clasp
 - numpy -> required by opencv, python managed by pyenv (and packages by conda & pip in their respective environments)
 - ruby -> required by vim, managed by rbenv on my system

`brew config`
```
HOMEBREW_VERSION: 1.6.2-58-g41cb219-dirty
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 41cb219143dda5992bb83dc249bc2df48b4f7b23
Last commit: 6 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f70c1ecf85ff025f28afa6316fb3a7bdee6950b9
Core tap last commit: 87 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=/Applications
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/bin/ruby
Clang: 8.0 build 800
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 10, 9.0.1, 9, 1.8.0_161, 1.8.0_60, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: 8.2.1
XQuartz: 2.7.11 => /opt/X11
```

To help us debug your issue please explain:
- What you were trying to do (and why)
I installed openssh 7.7p1 and changed my `~/.ssh/config`, using the `Include` declaration to split my config into multiple files.

- What happened (include command output)
After the change, `brew update` failed with the following error:
```
/usr/bin/ssh
/Users/linovonburg/.ssh/config: line 1: Bad configuration option: include
/Users/linovonburg/.ssh/config: terminating, 1 bad configuration options
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask failed!
```

- What you expected to happen
`brew update` should have run without failing.

- Step-by-step reproduction instructions (by running `brew` commands)
  - `brew install openssh`
  - Modify `~/.ssh/config` by adding a `Include` declaration including a second file (e.g. `~/.ssh/config.d/test`)
  - `brew update`

I analyzed the `brew update` commands code and identified the problem.
On [line 397](https://github.com/FuegoFro/brew/blob/eb20f594a2729254fddd53b56b5d769d7e105801/Library/Homebrew/cmd/update.sh#L397) `GIT_SSH_COMMAND` is set to `"ssh -oBatchMode=yes"`. Since Homebrew replaces `PATH` when filtering the environment, `ssh` in this case is the system provided executable in `/usr/bin`.
As far as I could find, there is currently no way to make Homebrew use the brewed ssh (although it actually does so in pretty much every other case if I correctly set my `GIT_SSH_COMMAND` environment variable.

I prepared a pull-request that adds an environment variable `HOMEBREW_FORCE_BREWED_SSH`, analogous to `HOMEBREW_FORCE_BREWED_CURL` (see [here](https://github.com/Homebrew/brew/pull/4133)).

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
My recommendation is you adjust your SSH configuration files accordingly, sorry.

**Comment by poochiethecat** [comment]
Could you explain to me why it is not sensible to use a brewed ssh executable in this case? I can see that if the brewed openssh were older than the system provided one or somehow backwards compatibility was not ensured that might be a problem. But since I actually **am** currently using an older version of macOS and thus can't just upgrade the system provided ssh executable, I would expect that to also be less secure, generally speaking.

I'm not trying to change your mind about the change, but it does not sit well with me at all that I can not use a feature of openssh that would allow me to nicely structure my ssh config into several files instead of having it all in one big, messy file. All just because for Homebrew, I cannot use the more recent version, that I installed using Homebrew and that works everywhere else without problems... So I would love to at least understand the reasoning behind the limitation.

Anyway, thank you very much for maintainig Homebrew! It is an awesome tool and obviously has to deal with a lot of complexity, so I'm sure it's not an easy job.

**Comment by MikeMcQuaid** [comment]
Allowing brewed executables opens us up to a larger error and support surface than the macOS system ones. This is something we only really want to do when we have to and in this case until we have a lot more requests: unfortunately we don't have to.

**Comment by MikeMcQuaid** [comment]
> Anyway, thank you very much for maintainig Homebrew! It is an awesome tool and obviously has to deal with a lot of complexity, so I'm sure it's not an easy job.

And thanks for the kind words here, they are much appreciated ❤️

**Comment by poochiethecat** [comment]
Fair enough :) Thanks for taking the time to explain!
