### ISSUE TITLE
brew --prefix performance

### ISSUE THREAD

**Issue by kenji21** [Homebrew/brew#4153]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?
````
brew config
HOMEBREW_VERSION: 1.6.3
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d14d0c25d6bd5a15f3fbca4cb402f0f2245c4631
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e0f3f921ff57ba694b795d386c648e05a5fd8207
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.15.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.1, 1.8.0_25
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3
XQuartz: 2.7.11 => /opt/X11
````

To help us debug your issue please explain:
- What you were trying to do (and why)
getting passwords out of the [passwordstore](https://www.passwordstore.org) using pass command tooks too long (I was using [ansible](https://www.ansible.com)'s [passwordstore module](https://github.com/ansible/ansible/blob/cdd21e2170b9a47d84624c8c2f792a66f2b0fe57/lib/ansible/plugins/lookup/passwordstore.py) to provision servers, then discovered that `pass show` was slow, then debugging using [PS4 variable](https://stackoverflow.com/questions/4336035/performance-profiling-tools-for-shell-scripts)) points me to `brew --prefix gnu-getopt`
- What happened (include command output)
$ time brew --prefix gnu-getopt
/usr/local/opt/gnu-getopt

real	0m0.617s
user	0m0.384s
sys	0m0.201s

$ time brew --prefix colordiff
/usr/local/opt/colordiff

real	0m0.662s
user	0m0.421s
sys	0m0.211s

We should be able to get a prefix path in less than 100ms

- What you expected to happen
brew should be quicker to find gnu getopt path
- Step-by-step reproduction instructions (by running `brew` commands)
$ time brew --prefix gnu-getopt
$ time brew --prefix colordiff

**Comment by ilovezfs** [comment]
We're happy to review PRs improving the performance of `--prefix` but don't consider the current level of performance a bug. Thanks for filling out the template @kenji21.
