### ISSUE TITLE
LibreOffice

### ISSUE THREAD

**Issue by KeithCu** [Homebrew/brew#4162]
It would be nice if LibreOffice could be added to HomeBrew. It's not the best suite, but it's steadily improving ;-)
 
There's been quite a bit of activity of the past years to pay down technical debt, mostly remove Java, polish, improve import / export, etc. There are monthly releases so it's work to keep up to date manually. It's in the Apple store, but it costs money.

Here's a link to the Arch file which could be ported from. There also are language packs:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libreoffice-fresh

I only dabble on the Mac and don't know Ruby, but maybe someone will come along and be interested in this.

**Comment by commitay** [comment]
`brew cask install libreoffice`
https://github.com/caskroom/homebrew-cask/blob/master/Casks/libreoffice.rb

`brew cask install libreoffice-language-pack`
https://github.com/caskroom/homebrew-cask/blob/master/Casks/libreoffice-language-pack.rb

**Comment by KeithCu** [comment]
I see. Thanks!! There's a whole other community I didn't even know about ;-) A mention could be put on brew.sh.
