### ISSUE TITLE
"Homebrew and Python" mentions a bug in distutils without linking to a bug report

### ISSUE THREAD

**Issue by nchammas** [Homebrew/brew#4165]
[Over here](https://github.com/Homebrew/brew/blob/a3d639dc49fd499cce6d2b36bb51acf3a1c88fe3/docs/Homebrew-and-Python.md#note-on-pip-install---user) the docs say:
> The normal pip install --user is disabled for brewed Python. This is because of a bug in distutils, because Homebrew writes a distutils.cfg which sets the package prefix.

It would be helpful if the text "a bug in distutils" linked to a [bug report](https://bugs.python.org/) against distutils describing the problem in detail. That would help users understand the nature of the problem and advocate for an upstream fix.

I raise this issue here because some Python projects [don't work well with Homebrewed Python](https://github.com/sdispater/poetry/issues/36), typically hitting up against the following error:

> distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both

Trying to get to the bottom of the issue leads to the "Homebrew and Python" documentation page, but the trail goes cold at the above mention of that bug in distutils.

**Comment by MikeMcQuaid** [comment]
I don't know what this bug is so can't link to it. Maybe @tdsmith does.

In future please fill out the issue template, thanks.

**Comment by tdsmith** [comment]
you may enjoy https://github.com/pypa/pip/issues/2683 and https://github.com/pypa/pip/issues/4390

**Comment by nchammas** [comment]
> In future please fill out the issue template, thanks.

@MikeMcQuaid - My apologies. I didn't think my issue fit either of the two templates, but in the future I'll just file similar issues as bug reports.

@tdsmith - Thanks for the links. Reading through them, it looks like the referenced "bug in distutils" is perhaps [this one](https://bugs.python.org/issue22269).

**Comment by MikeMcQuaid** [comment]
@nchammas Thanks! If @tdsmith can confirm it's the correct bug: could one of you submit a PR to add it to the docs? Cheers!
