### ISSUE TITLE
Installing brew broke suid apps in /usr/local/bin

### ISSUE THREAD

**Issue by rbur004** [Homebrew/brew#4166]
Install brew changed the ownership of all files in /usr/local to my account, which broke suid apps in /usr/local/bin. They now run as me, and they are meant to run as other users.

This is also a security issue. /usr/local/ shouldn't be a directory a user can just change the contents of. That's what the home directory is for.

**Comment by ilovezfs** [comment]
As I'm sure you've already figured out, you'll need to reset ownership as needed for your local configuration as the generic installer doesn't support that case.

In the future, always fill out the complete template regardless of whether you think it's relevant.

**Comment by rbur004** [comment]
I did a chmod back to root of /usr/local. Changed the suid programs back to their correct ownerships.

I still think this is a bug that will catch the average user, who might not understand what just happened.  Surely you should be more careful about changing existing suid binaries.

**Comment by rbur004** [comment]
For that matter, their config files got their permissions changed too. They weren't meant to be readable.

**Comment by MikeMcQuaid** [comment]
The installer told you what it was going to do and you accepted it.
