### ISSUE TITLE
Error: undefined method `core_tap?' for nil:NilClass

### ISSUE THREAD

**Issue by jiang95** [Homebrew/brew#4173]
when i brew update,there is a Error:Error: undefined method `core_tap?' for nil:NilClass.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue ((don't create a new one, please) then this issue may be reopened.

**Comment by GauthamGoli** [comment]
After filling the template, also please post the whole stack trace for us to be able to debug it.
