### ISSUE TITLE
How to install the old version of ffmpeg?

### ISSUE THREAD

**Issue by euppi98** [Homebrew/brew#4175]
How to install the old version of ffmpeg, via "brew"?

**Comment by scpeters** [comment]
~~~
Please fill out one of the templates on: https://github.com/Homebrew/brew/issues/new/choose

If you want to ask a question please do so on our Discourse: https://discourse.brew.sh

We will close issues asking questions without comment.
~~~

I think this question is better suited for Discourse: https://discourse.brew.sh

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue ((don't create a new one, please) then this issue may be reopened.

**Comment by MikeMcQuaid** [comment]
> If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

Although not in this case: please ask on our Discourse or IRC instead.
