### ISSUE TITLE
installation trouble, mac OS 10.12.6

### ISSUE THREAD

**Issue by jlstiles** [Homebrew/brew#4189]
I am trying to install homebrew and typed
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)
in the terminal as suggested and nothing happens but 
>

I expected the installation to start and instructions/options to arise in the terminal but nothing happened for 10 minutes.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

Regardless: you'll need to figure this out yourself I'm afraid. In future always fill it out.
