### ISSUE TITLE
Can you please whitelist Belgian EID dylibs 

### ISSUE THREAD

**Issue by Kristofp** [Homebrew/brew#4196]
**All Belgian Homebrew users** would be grateful if these could be added to the whitelist as they affect all Belgian users since we need to have this official software installed to file our taxes
This dylibs are the result of installing this software: [https://eid.belgium.be/en](https://eid.belgium.be/en)
Adding hese three lines to **white_list** under **check_for_stray_dylibs** should cover it.

```
"libbeid*.dylib", # Belgian EID software
"libqt-mt.*.dylib", # Belgian EID software
"libxerces-c-*.dylib", # Belgian EID software
```

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template (as it told you to do).

> "libbeid*.dylib", # Belgian EID software

We would accept a PR to whitelist this as it will not be picked up and used by other software.

> "libqt-mt.*.dylib", # Belgian EID software

I'm not sure whether we would accept a PR for this given it's a Qt library (albeit with unconventional name) that may be used by other software.

> "libxerces-c-*.dylib", # Belgian EID software

We would not accept a PR to whitelist this as this will conflict with out `xerces-c` formula.

Furthermore, remember that `brew doctor` says to ignore warnings that aren't causing you problems.
