### ISSUE TITLE
When running `brew` under `bundle exec` I get weird issues.

### ISSUE THREAD

**Issue by jcampbell05** [Homebrew/brew#42]
When `brew` is ran under `bundle exec` I get weird issues about bundler not finding dependencies.
However the dependencies are there and running `brew` normally works.

**Comment by mikemcquaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by mikemcquaid** [comment]
Happy to continue discussion here but I suspect this is expected behaviour; we need to run Bundler ourselves for certain commands (e.g. `tests`) so those will fail if you're nesting bundler invocations. Regardless, the fix is "don't run Homebrew with `bundle exec`".

**Comment by jcampbell05** [comment]
@mikemcquaid normally this would be the case but the issue was this, I was using Fastlane ran under `bundle exec` which invoked `brew bundle`.

Workedaround it though by invoking homebrew on its own.

**Comment by mikemcquaid** [comment]
🆒
