### ISSUE TITLE
homebrew/core showing up twice on 'brew tap'...

### ISSUE THREAD

**Issue by kevmoo** [Homebrew/brew#420]
`brew update` shows every entry twice.
`brew tap` shows `homebrew/core` twice.

**Comment by UniqMartin** [comment]
I'm sorry, but you provided so little information that it's hard to impossible to provide any advice. What is the output of the following commands?

```
brew config
brew doctor
brew tap
ls -AlF "$(brew --repository)"/Library/Taps/*
```

**Comment by kevmoo** [comment]
```console
~/> brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: db76a0f4cc3838658919570b3453edbcb9ed2fcd
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 14be211146d6c3bb0ab1aa278a9349f97c42ecb4
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /Users/kevmoo/homebrew
HOMEBREW_REPOSITORY: /Users/kevmoo/homebrew
HOMEBREW_CELLAR: /Users/kevmoo/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Clang: 7.3 build 703
Git: 2.7.4 => /usr/local/git/current/bin/git
Perl: /usr/bin/perl
Python: /Users/kevmoo/homebrew/bin/python => /Users/kevmoo/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/kevmoo/homebrew/opt/ruby/bin/ruby => /Users/kevmoo/homebrew/Cellar/ruby/2.3.1/bin/ruby
Java: 1.8.0_91, 1.8.0_72, 1.8.0_60
System Ruby: 2.0.0-p648
OS X: 10.11.5-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A
```

```console
~/> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew is not installed to /usr/local
You can install Homebrew anywhere you want, but some brews may only build
correctly if you install in /usr/local. Sorry!
```

```console
~/> brew tap
caskroom/cask
dart-lang/dart
homebrew/core
homebrew/core
homebrew/versions
martido/brew-graph
```

```console
~/> ls -AlF "$(brew --repository)"/Library/Taps/*
/Users/kevmoo/homebrew/Library/Taps/caskroom:
total 0
drwxr-xr-x  29 kevmoo  eng  986 Jun 27 10:29 homebrew-cask/

/Users/kevmoo/homebrew/Library/Taps/dart-lang:
total 0
drwxr-xr-x  6 kevmoo  eng  204 Jun 22 11:09 homebrew-dart/

/Users/kevmoo/homebrew/Library/Taps/homebrew:
total 0
drwxr-xr-x   11 kevmoo  eng   374 Jun 22 11:09 homebrew-core/
drwxr-xr-x    5 kevmoo  eng   170 Jun  1 09:19 homebrew-homebrew/
drwxr-xr-x  217 kevmoo  eng  7378 Jun 27 10:29 homebrew-versions/

/Users/kevmoo/homebrew/Library/Taps/martido:
total 0
drwxr-xr-x  5 kevmoo  eng  170 May 15 17:29 homebrew-brew-graph/
```

**Comment by UniqMartin** [comment]
Thanks! I suspect the problematic duplicate entry is `/Users/kevmoo/homebrew/Library/Taps/homebrew/homebrew-homebrew`. Do you have any idea where it came from? That's a tap directory that should never exist (and there's no corresponding GitHub repository of the same name). It should be safe to remove this directory if you haven't made local modifications to any of the Homebrew formulae. (But you can also move that directory somewhere else, if you aren't entirely sure.) Before you do that, would you mind additionally providing the output of `brew tap-info --installed`?

**Comment by kevmoo** [comment]
That's a whole lota weird

```console
~/> brew tap-info --installed
caskroom/cask: unpinned, 1 formula, 1 command
/Users/kevmoo/homebrew/Library/Taps/caskroom/homebrew-cask (8,198 files, 112.2M)
From: https://github.com/caskroom/homebrew-cask

dart-lang/dart: unpinned, 1 formula
/Users/kevmoo/homebrew/Library/Taps/dart-lang/homebrew-dart (259 files, 224.4K)
From: https://github.com/dart-lang/homebrew-dart

homebrew/core: unpinned, 3588 formulae
/Users/kevmoo/homebrew/Library/Taps/homebrew/homebrew-core (3,970 files, 19M)
From: https://github.com/Homebrew/homebrew-core

homebrew/core: unpinned, 3588 formulae
/Users/kevmoo/homebrew/Library/Taps/homebrew/homebrew-core (3,970 files, 19M)
From: https://github.com/Homebrew/homebrew-core

homebrew/versions: unpinned, 211 formulae
/Users/kevmoo/homebrew/Library/Taps/homebrew/homebrew-versions (1,301 files, 4.5M)
From: https://github.com/Homebrew/homebrew-versions

martido/brew-graph: unpinned, 1 formula
/Users/kevmoo/homebrew/Library/Taps/martido/homebrew-brew-graph (35 files, 23.1K)
From: https://github.com/martido/homebrew-brew-graph
```

**Comment by UniqMartin** [comment]
It's not entirely surprising because `homebrew/homebrew` (or `homebrew/homebrew-homebrew`) is automatically re-interpreted as `homebrew/core` for compatibility when Homebrew was still hosted in a single repository named `Homebrew/homebrew` (now [`Homebrew/legacy-homebrew`](https://github.com/Homebrew/legacy-homebrew)).

Just remove `/Users/kevmoo/homebrew/Library/Taps/homebrew/homebrew-homebrew` and all the duplication should be gone, not to mention that updates should become faster, too.

> I suspect the problematic duplicate entry is `/Users/kevmoo/homebrew/Library/Taps/homebrew/homebrew-homebrew`. Do you have any idea where it came from?

I'd still be interested in an answer to this question.

**Comment by kevmoo** [comment]
All good. Not sure if this would be an interesting candidate for a `brew doctor` check – maybe only if it's reported again?

Thanks much! 😀

**Comment by UniqMartin** [comment]
It's a really weird problem and I'm still not sure how you ended up in this situation. So far this looks like a singular event, but if more users come forward and report the same, we'll certainly take a closer look and see if this can be prevented or at least properly diagnosed.

You're welcome! I'm glad everything is back to normal for you. 😀
