### ISSUE TITLE
Overall progress bar on "brew upgrade"

### ISSUE THREAD

**Issue by Ardutronico** [Homebrew/brew#4203]
Hello, I've searched and I couldn't find this feature anywhere. The problem is that when doing "brew upgrade", it's difficult to know how much has been done and how much is remaining or at least know the size of the download. This is a specially big problem for us with a slow connection to the Internet (even though mine, 8 Mb/s, is relatively fast and stable in comparison to others in my country with 1 Mb/s).
I think it would be a good improvement to make it like apt and put a progress bar at the bottom to know the progress of the upgrade, and, even better, the ETA. 
It would also be nice that it told you an estimate of the total size of the download and press Y to confirm (again like apt).
Even for those with a fibre optic 1 Gb/s connection, the packages are going to take a while to install, especially large ones. So I think this would benefit all the Homebrew users.

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template.



> at least know the size of the download

We show download progress.



> the ETA

There's no way we can do this accurately.

> an estimate of the total size of the download

We don't know this information.

---

We'd accept a pull request to improve some of this but it's not something we'll work on in the near future. Please always fill out the feature request template in future.

**Comment by MikeMcQuaid** [comment]
> I'll make a PR if needed (after I learn Ruby).

I learned Ruby to contribute to Homebrew. Yes, it's needed if you want to see a change made.

> you could at least

I don't think it's "at least" here; the current system works well for most of our users.

> in alphabetical order

We can't do this because of dependency trees.
