### ISSUE TITLE
normalise data before searching

### ISSUE THREAD

**Issue by gregbenner** [Homebrew/brew#4208]
Please replace this section with:
- run toLowerCase() but in ruby on any input `brew install CronniX` should return the same results as `brew install cronnix`

**Comment by MikeMcQuaid** [comment]
We disagree. Always fill out the issue template in future.

**Comment by gregbenner** [comment]
I used feature request and filled it out best I could, apologies. The app installed from searching all lowercase cronnix is in my mac as CronniX but no biggie. Thanks for the response and time.
