### ISSUE TITLE
Attempting to install from a tap before installing tapping into hombrew/cask breaks brew.

### ISSUE THREAD

**Issue by trusktr** [Homebrew/brew#4212]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
  **I'm not sure if this is a problem with how brew handles taps/casks, or a problem with a tap/cask, so posting here first.**
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
❯ brew config
HOMEBREW_VERSION: 1.6.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8381fb8ba98c232ee4d5fac583ad15a278cba94
Last commit: 89 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 28d4210b0c3f4cc4295414167fa73fd0b696c50d
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_VISUAL: nvim
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: N/A
XQuartz: N/A

❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.6m/greenlet/greenlet.h
```

To help us debug your issue please explain:
- **What you were trying to do (and why)**
  I was trying to install Slack. I have a fresh install of `brew`. Then, I installed some stuff (f.e. `brew install git` and others, which all worked fine). Then, I tried `brew search slack` and it showed that `homebrew/cask/slack` was available. Note, I have not install homebrew-cask (i.e. I have not ran `brew tap homebrew/cask`). Then, I tried `brew install homebrew/cask/slack` which did something weird I haven't seen before:
- **What happened (include command output)**
  ```
    ❯ brew install homebrew/cask/slack
  Updating Homebrew...
  ==> Migrating tap caskroom/cask to homebrew/cask...
  Moving /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
  Changing remote from https://github.com/caskroom/homebrew-cask to https://github.com/Homebrew/homebrew-cask...
  ==> Auto-updated Homebrew!
  Updated 2 taps (homebrew/core, homebrew/cask).
  ==> Updated Formulae
  angular-cli          cocoapods            digdag               fn                   google-benchmark     gopass               jupyter              memcached            monero               pony-stable          xtensor
  
  Error: No available formula with the name "homebrew/cask/slack"
  ==> Searching for a previously deleted formula (in the last month)...
  Warning: homebrew/cask is shallow clone. To get complete history run:
    git -C "$(brew --repo homebrew/cask)" fetch --unshallow
  
  Error: No previously deleted formula found.
  ==> Searching for similarly named formulae...
  ==> Searching local taps...
  Error: No similarly named formulae found.
  ```
  As you can see, that strange message `Migrating tap caskroom/cask to homebrew/cask`. No idea what it did there.
- **What you expected to happen**
  I wanted to install homebrew/cask/slack successfully, and I think the mistake was in running `brew install homebrew/cask/slac` before ever running `brew tap homebrew/cask`, which put `brew` in a broken state.
- **Step-by-step reproduction instructions (by running `brew` commands)**
  Already described above.

**Comment by trusktr** [comment]
Okay, I just ran `brew install Caskroom/cask/slack` which worked just fine. The above still holds (brew is telling me to do stuff that doesn't work)

**Comment by reitermarkus** [comment]
This was fixed in https://github.com/Homebrew/brew/pull/4211, and should be working now.

**Comment by trusktr** [comment]
@reitermarkus Thanks! How do I fix my brew to the new version?

**Comment by reitermarkus** [comment]
Just run `brew update` again.

**Comment by trusktr** [comment]
Quick Q: is `brew tap homebrew/cask` required before installing any `homebrew/cask/*` packages? Or does running `brew install homebrew/cask/anything` imply that `brew tap homebrew/cask` will also be ran?

**Comment by trusktr** [comment]
Seems like it still left me with some broken state:

```
❯ brew search atom
==> Searching local taps...
==> Migrating tap caskroom/cask to homebrew/cask...
Moving /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
Error: File exists - /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/homebrew-cask
```

Should I just delete the file and try again? Don't want to break things even more by guessing.

**Comment by vitorgalvao** [comment]
> is `brew tap homebrew/cask` required before installing any `homebrew/cask/*` packages?

Any `brew cask` command will automatically take care of tapping the repo.

> `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/homebrew-cask`

That doesn’t look right (`homebrew-cask/homebrew-cask`). I’d `brew untap homebrew/cask; brew tap homebrew/cask`).

**Comment by MikeMcQuaid** [comment]
@trusktr Please run `brew install atom --debug` and paste the backtrace in here. Thanks!

**Comment by trusktr** [comment]
I nuked brew (hopefully didn't miss anything) with the uninstall script plus manually deleting leftover files, and am starting from the beginning.

I still see output regarding `Caskroom` in the output, f.e.

```
==> brew cask install homebrew/cask/atom 
==> Creating Caskroom at /usr/local/Caskroom
```

Is that correct?

Let me try `--debug` next time if there's more problems.

**Comment by trusktr** [comment]
Everything seems to have worked smoothly this time, I've installed everything I needed without any errors. Thanks!

**Comment by MikeMcQuaid** [comment]
@trusktr Yes, should be correct, thanks!
