### ISSUE TITLE
Package appears as installed but it is not

### ISSUE THREAD

**Issue by jommgoncalves** [Homebrew/brew#422]
> bash-3.2$ brew cask list
> flash-player		    iterm2-beta			mou			    sublime-text		vlc
> google-chrome		    java			pgweb			    virtualbox			xquartz
> intellij-idea-ce	    libreoffice			pycharm-ce		    virtualbox-extension-pack

> bash-3.2$ brew cask info pycharm-ce
> pycharm-ce: 2016.1.4
> Jetbrains PyCharm Community Edition, PyCharm CE
> https://www.jetbrains.com/pycharm
> Not installed
> https://github.com/caskroom/homebrew-versions/blob/master/Casks/pycharm-ce.rb
> ==> Contents
>   PyCharm CE.app (app)

> bash-3.2$ brew cask remove pycharm-ce
> Error: pycharm-ce is not installed

**Comment by UniqMartin** [comment]
I'm sorry, but all problems concerning `brew cask <some-command>` should be reported to [Homebrew Cask](https://github.com/Caskroom/homebrew-cask), not this repository. Thanks for understanding!

**Comment by jommgoncalves** [comment]
My bad :\
