### ISSUE TITLE
Git install error

### ISSUE THREAD

**Issue by naveencpj** [Homebrew/brew#4223]
Please fill out one of the templates on: https://github.com/Homebrew/brew/issues/new/choose

If you want to ask a question please do so on our Discourse: https://discourse.brew.sh

We will close issues asking questions without comment.
![git install error](https://user-images.githubusercontent.com/39589235/40577936-d861504c-6129-11e8-8400-6e36c5a88611.png)

**Comment by reitermarkus** [comment]
You didn't fill out the issue template and this has nothing to do with Homebrew whatsoever.
