### ISSUE TITLE
brew doctor

### ISSUE THREAD

**Issue by marquisXuan** [Homebrew/brew#4226]
when I run brew doctor , then print this on the screen.
```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/hart-xuan/.pyenv/shims/python2-config
  /Users/hart-xuan/.pyenv/shims/python3.6m-config
  /Users/hart-xuan/.pyenv/shims/python2.7-config
  /Users/hart-xuan/.pyenv/shims/python-config
  /Users/hart-xuan/.pyenv/shims/python3-config
  /Users/hart-xuan/.pyenv/shims/python3.6-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2
  python

Warning: Your Xcode (9.2) is outdated.
Please update to Xcode 9.3 (or delete it).
Xcode can be updated from the App Store.
```

**Comment by ilovezfs** [comment]
As it says

>Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Also please always fill out the issue template completely.

**Comment by marquisXuan** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
I have a bit of obsessive-compulsive disorder, want to solve this warning, how to do it?thanks



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    



                



    On 05/29/2018 14:47，ilovezfs<notifications@github.com> wrote： 


As it says

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Also please always fill out the issue template completely.

**Comment by MikeMcQuaid** [comment]
> I have a bit of obsessive-compulsive disorder, want to solve this warning, how to do it?thanks

@marquisXuan Change your `PATH`, `brew link` those formulae and update Xcode. You could have got that from reading the output, though 😉
