### ISSUE TITLE
Force Brew to install Mplayer with OSD / Subtitle Support

### ISSUE THREAD

**Issue by PacoH** [Homebrew/brew#423]
I was trying to toggle `OSD` and `subtitles` in the latest brew-installed build of `mplayer`, `MPlayer 1.3.0-4.2.1`, but nothing happened. A search didn't turn up much but I found the thread [No OSD in mplayer #49861](https://github.com/Homebrew/legacy-homebrew/issues/49861) which indicates that the current versions of 1.3.0 get built with `--disable-x11`. It is necessary to build it with X11 support in order to get `OSD` and `subtitles` to work. So I did some digging and found out an easy workaround.

Note:

Check to see if you have both `freetype` and `fontconfig` installed. If not, install them first.

Install `mplayer` if you haven't already, or ugrade the current version.

After you install the latest version of `mplayer`, you have to edit the file `/usr/local/Library/Formula/mplayer.rb`. Search for `--disable-x11` and delete that line. I moved it outside the brackets and commented it out with a note to myself:

Original:

    args = %W[
      --cc=#{ENV.cc}
      --host-cc=#{ENV.cc}
      --disable-cdparanoia
      --prefix=#{prefix}
      --disable-x11
    ]

Modified:

    args = %W[
      --cc=#{ENV.cc}
      --host-cc=#{ENV.cc}
      --disable-cdparanoia
      --prefix=#{prefix}
    ]
    #--disable-x11 removed because it disabled osd and subs

Then do another search for `depends_on` and find:

    depends_on "yasm" => :build
    depends_on "libcaca" => :optional

Add the line `depends_on :x11 => :build`:

    depends_on "yasm" => :build
    depends_on "libcaca" => :optional
    depends_on :x11 => :build

Save.

Then reinstall mplayer:

`brew reinstall --with-x11 mplayer`

I'm not sure the `--with-x11` is really necessary but it sure didn't hurt.

That's it. Now I have glorious OSD and subtitle support! Wooh hooh!

![img](https://s31.postimg.org/69oz3hb6j/Screen_Shot_2016_06_29_at_3_21_00_PM.png)

**Comment by MikeMcQuaid** [comment]
We don't depend on X11 because it's not provided by OS X. Please make a request to MPlayer to have subtitles not require X11.

**Comment by PacoH** [comment]
Many of us have X11 installed and use it for many apps so why did you close the thread? This obviously works and asking Mplayer devs to change the core code is like asking for the sky…

**Comment by MikeMcQuaid** [comment]
> Many of us have X11 installed and use it for many apps so why did you close the thread? 

Because Homebrew has made the decision to not make formulae depend on X11 that don't require it. You may have it installed but not everyone using MPlayer does. We will not change this back so I closed it.

> asking Mplayer devs to change the core code is like asking for the sky…

If no-one asks it definitely won't get changed. Regardless, the issue here is MPlayer and not Homebrew.

**Comment by PacoH** [comment]
I think you are being unreasonable. Obviously mplayer DOES require X11 for OSD and subtitles. It is very easy to install. It obviously works NOW. You don't have to change anything. What do you have against X11? The issue here is you're not listening to me and you are not considering anyone wanting this feature, or for the work I put in to report on how to do it. It would take years and hard lobbying to get Mplayer to change.

**Comment by MikeMcQuaid** [comment]
@PacoH I'm locking this issue now. Please read our Code of Conduct before opening future issues: https://github.com/Homebrew/brew/blob/master/CODEOFCONDUCT.md
