### ISSUE TITLE
Provide a recipe for "graalvm"

### ISSUE THREAD

**Issue by phdoerfler** [Homebrew/brew#4231]
Provide a recipe for [GraalVM](https://www.graalvm.org). Both the Oracle JDK and GraalVM are downloads from Oracle perhaps the Java recipe is a good source of inspiration for this.

## Why would one want this?
GraalVM is the next great thing in JVM land and manual downloads from anything from the Oracle website involves manually agreeing to their license every single time and a sacrifice. Lots of kittens could be saved from having homebrew do this.

**Comment by vitorgalvao** [comment]
You asking for a formula, so this issue belongs in [Homebrew/core](https://github.com/Homebrew/homebrew-core).

But if I recall correctly, formula requests are not accepted, and if you want it you’ll need to at least try to make a pull request.

**Comment by phdoerfler** [comment]
@vitorgalvao thanks for the clarification!
