### ISSUE TITLE
Cask install reports success on failure.

### ISSUE THREAD

**Issue by uglygus** [Homebrew/brew#4244]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

======

I do not have write permissions to /Applications. When installing a cask sudo asks for my password which I provide which doesn’t work because I do not have sudo privileges. Brew claims that the cask was ‘successfully installed!’ when in fact it was not because it was unable to write to /Applications. I get a warning from sudo but brew seems to believe everything is ok.

Should there be some kind of error or warning from brew instead of the success message?

```
$brew install caskroom/cask/hugin
==> brew cask install caskroom/cask/hugin
==> Satisfying dependencies
==> Downloading https://downloads.sourceforge.net/hugin/Hugin-2018.0.0.dmg
Already downloaded: /Users/[username]/Library/Caches/Homebrew/Cask/hugin–2018.0.0.dmg
==> Verifying checksum for Cask hugin
==> Installing Cask hugin
==> Moving App Suite ‘Hugin’ to ‘/Applications/Hugin’.
Password:
==> [username] is not in the sudoers file. This incident will be reported.
:beer: hugin was successfully installed!
```

**Comment by reitermarkus** [comment]
Can you post the output with `--verbose --debug` added?

**Comment by uglygus** [comment]
$brew cask install hugin --verbose --debug 
Updating Homebrew...
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.sourceforge.net/hugin/Hugin-2018.0.0.dmg
Already downloaded: /Users/joe/Library/Caches/Homebrew/Cask/hugin--2018.0.0.dmg
==> Downloaded to -> /Users/joe/Library/Caches/Homebrew/Cask/hugin--2018.0.0.dmg
==> Verifying download
==> Determining which verifications to run for Cask hugin
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask hugin
==> SHA256 checksums match
==> Installing Cask hugin
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/joe/Library/Caches/Homebrew/Cask/hugin--2018.0.0.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/joe/Library/Caches/Homebrew/Cask/hugin--2018.0.0.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/sg/rs6kj_n16rd2cpl0v65d9kx55z34t_/T/d20180531-45701-1292wgr", "/Users/joe/Library/Caches/Homebrew/Cask/hugin--2018.0.0.dmg"]
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/sg/rs6kj_n16rd2cpl0v65d9kx55z34t_/T/20180531-45701-6eqf6b.list", "--", "/var/folders/sg/rs6kj_n16rd2cpl0v65d9kx55z34t_/T/20180531-45701-1pjkt3n.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/sg/rs6kj_n16rd2cpl0v65d9kx55z34t_/T/20180531-45701-1pjkt3n.bom", "--", "/private/var/folders/sg/rs6kj_n16rd2cpl0v65d9kx55z34t_/T/d20180531-45701-1292wgr/dmg.vuxxFt", "/Users/joe/homebrew/Caskroom/hugin/2018.0.0"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/sg/rs6kj_n16rd2cpl0v65d9kx55z34t_/T/d20180531-45701-1292wgr/dmg.vuxxFt"]
==> Creating metadata directory /Users/joe/homebrew/Caskroom/hugin/.metadata/2018.0.0/20180531213234.826.
==> Creating metadata subdirectory /Users/joe/homebrew/Caskroom/hugin/.metadata/2018.0.0/20180531213234.826/Casks.
==> Installing artifacts
==> 1 artifact/s defined
#<SortedSet:0x00000101c5cd10>
==> Installing artifact of class Hbc::Artifact::Suite
==> Moving App Suite 'Hugin' to '/Applications/Hugin'.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/mv", "/Users/joe/homebrew/Caskroom/hugin/2018.0.0/Hugin", "/Applications/Hugin"]
Password:
Password:==> Sorry, try again.

Password:==> Sorry, try again.

==> joe is not in the sudoers file.  This incident will be reported.
🍺  hugin was successfully installed!

**Comment by vitorgalvao** [comment]
@uglygus Please use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) for code.

**Comment by reitermarkus** [comment]
What is the exit code of 

```bash
/usr/bin/sudo -E -- /bin/mv "/Users/joe/homebrew/Caskroom/hugin/2018.0.0/Hugin" "/Applications/Hugin"
```

if you run it in a Terminal?

**Comment by uglygus** [comment]
The return code from sudo is 1.

```
$/usr/bin/sudo -E -- /bin/mv "/Users/joe/homebrew/Caskroom/hugin/2018.0.0/Hugin" "/Applications/Hugin"
Password:
joe is not in the sudoers file.  This incident will be reported.
$echo $?
1
```
