### ISSUE TITLE
`brew cleanup` should remove old portable-ruby installs

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#4256]
`/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/` can contain multiple installations of portable ruby for which only the most recent is used. `brew cleanup` should remove all old installations of portable ruby here.

**Comment by brianmorton** [comment]
This might be in my wheelhouse, I'll have a look.

**Comment by oswalpalash** [comment]
@brianmorton  just saw that you were already working on it, this might be of some help, I started to fiddle around with it myself.
```ruby
   def cleanup_portable_rubies
      used_ruby = ''
      installed_versions = []
      $LOAD_PATH.each do |ruby_path|
        used_ruby = ruby_path.chomp("lib/ruby/vendor_ruby") if ruby_path.match('lib/ruby/vendor_ruby$')
      end
      Dir.entries("#{used_ruby}/..").each do |version|
        installed_versions.push(version) if version.match(/[0-9]/)
      end
      installed_versions.each do |remove_version|
        path = "#{used_ruby}../#{remove_version}"
        puts path, used_ruby
        cleanup_path(path) { FileUtils.rm_rf path } if !used_ruby.match('#{remove_version}')
      end
    end

**Comment by reitermarkus** [comment]
@oswalpalash, since there is no PR from @brianmorton yet, feel free to submit one yourself.

**Comment by brianmorton** [comment]
@oswalpalash go right ahead with whatever you have and submit a PR :)

**Comment by resistor4u** [comment]
Since I've deleted the extra portable ruby versions, I have been unable to run `brew search`. It fails with this error:
```
Error: No such file or directory @ rb_sysopen - /usr/local/Caskroom/supraudit/latest/tmp/LICENSE
```
Running `brew info` and `brew list` both work fine. If this is an unrelated problem, I'll file a new issue.

**Comment by MikeMcQuaid** [comment]
I no longer care about this.
