### ISSUE TITLE
Invalid formula "phantomjs.rb" causes homebrew/core to be unable to be tapped

### ISSUE THREAD

**Issue by matchai** [Homebrew/brew#4276]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Any operation that requires tapping homebrew/core (eg. brew doctor)

- What happened (include command output)
On a completely fresh macOS installation, after installing a few homebrew-cask apps, I tried to install standard homebrew apps. The following error is shown every time:
```
$ brew doctor
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4780, done.
remote: Compressing objects: 100% (4563/4563), done.
remote: Total 4780 (delta 52), reused 1083 (delta 29), pack-reused 0
Receiving objects: 100% (4780/4780), 3.88 MiB | 82.00 KiB/s, done.
Resolving deltas: 100% (52/52), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/phantomjs.rb
NaN
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core
```

- What you expected to happen
Given it's a clean installation of macOS and brew, no errors to be shown when running `brew doctor`.

- Step-by-step reproduction instructions (by running `brew` commands)
  - Install brew normally: `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
  - `brew doctor`

Here is the output of `brew config` for me:
```
$ brew config
HOMEBREW_VERSION: 1.6.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: e4c02fafdaef5676cf40dd6d16e74976cf54b265
Last commit: 10 days ago
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: N/A
Git: 2.17.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.5-x86_64
Error: NaN
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `detect_version_from_clang_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:144:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/system_config.rb:37:in `clt'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/system_config.rb:51:in `dump_verbose_config'
/usr/local/Homebrew/Library/Homebrew/cmd/config.rb:12:in `config'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by chnyangjie** [comment]
I got the same error message when I trying to install homebrew

**Comment by matchai** [comment]
@DomT4 Yes I am. It seems that is the version of xcode command-line tools that is now installed by default:

```
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.25.5)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by DomT4** [comment]
Yeah, I thought that might be it. https://github.com/Homebrew/brew/pull/4275 _may well_ fix that problem, although if you're not running Homebrew in developer mode you may need to wait for a new tag.
