### ISSUE TITLE
brew error: unable to resolve dependency for rubocop-cask and did_you_mean

### ISSUE THREAD

**Issue by joelparkerhenderson** [Homebrew/brew#4279]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to run `brew audit --strict` on a new formula that I am creating; this is my first time creating a formula, so I presume I have been doing something incorrectly. 

- What happened (include command output)

The command failed with this error message:

    	Error: Unable to resolve dependency: user requested 'did_you_mean (= 1.0.0)'

- What you expected to happen

I expected `brew audit --strict` to succeed. 

- Step-by-step reproduction instructions (by running `brew` commands)

I followed many help pages about how to diagnose the issue. 

The most-relevant information seemed to advise me to first try to get `brew cask style` working. 

For example I tried `rbenv`, custom paths, manually adjusting the PATH env var, etc. 

The solution that eventually worked for me was to do `brew vendor-install ruby`.

Here are my notes, in case they are useful to other brew users and/or to brew documentation authors. 

    $ brew cask style
    ==> Installing or updating 'rubocop-cask' gem
    Error: Unable to resolve dependency: user requested 'did_you_mean (= 1.0.0)'

Do I have Ruby?

    $ ruby --version
    ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

Do I have multiple Ruby programs?

    $ which -a ruby
    /usr/local/bin/ruby
    /usr/bin/ruby

What are the versions?

    $ /usr/local/bin/ruby --version
    ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

    $ /usr/bin/ruby --version
    ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

Do I have the relevant gems?

    $ gem list --exact rubocop
    *** LOCAL GEMS ***
    rubocop (0.56.0)

    $ gem list --exact rubocop-cask
    *** LOCAL GEMS ***
    rubocop-cask (0.19.0)

    $ gem list --exact did_you_mean
    *** LOCAL GEMS ***
    did_you_mean (1.0.0)

Run doctor and maybe there are issues:

    $ brew doctor
    Warning: You have unlinked kegs in your Cellar
    Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
    those kegs to fail to run properly once built. Run `brew link` on these:
        ruby

Fix issues:

    $ brew link --overwrite --force ruby
    Linking /usr/local/Cellar/ruby/2.5.1... 3288 symlinks created

Try cask upgrade and fix any errors:

    $ brew cask upgrade

    …
    ==> Removing App '/Applications/Shortcat.app'.
    Error: Directory not empty @ dir_s_rmdir - /Applications/Shortcat.app
    …

New issue:

    $ brew doctor
    …
	Warning: Homebrew's sbin was not found in your PATH but you have installed
	formulae that put executables in /usr/local/sbin.
	Consider setting the PATH for example like so
	  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

Fix it.

Try StackOverflow suggestion to remove brew then reinstall:

    $ sudo rm -f $(which brew)
    Password: ***

    $ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Try a custom Ruby version:

    $ brew install rbenv
    $ brew install ruby-build 
    $ brew install rbenv-default-gems
    $ brew install rbenv-vars
    $ eval "$(rbenv init -)"
    $ rbenv install 2.5.1
    $ rbenv rehash
    $ rbenv global 2.5.1
    $ ruby --version
    ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

Try StackOverflow suggestion that Xcode may be stuck waiting for a license agreement.

    $ sudo xcodebuild -license

Try looking deeper at the error messages:

    $ brew cask style

The error message shows relevant lines when Homebrew tries to use the macOS Ruby at `/Library/Ruby/Site`:

    …
    /Library/Ruby/Site/2.3.0/rubygems/commands/install_command.rb:156:in `execute'
    /usr/local/Homebrew/Library/Homebrew/utils.rb:228:in `install_gem!'
    …

The relevant file:

    $ more /usr/local/Homebrew/Library/Homebrew/utils.rb

The relevant code:

    def install_gem!(name, version = nil)
      # Match where our bundler gems are.
      ENV["GEM_HOME"] = "#{ENV["HOMEBREW_LIBRARY"]}/Homebrew/vendor/bundle/ruby/# . {RbConfig::CONFIG["ruby_version"]}"
      ENV["GEM_PATH"] = ENV["GEM_HOME"]

Append code so I can see what's happening:

    def install_gem!(name, version = nil)
      # Match where our bundler gems are.
      ENV["GEM_HOME"] = "#{ENV["HOMEBREW_LIBRARY"]}/Homebrew/vendor/bundle/ruby/#{RbConfig::CONFIG["ruby_version"]}"
      ENV["GEM_PATH"] = ENV["GEM_HOME"]

      puts "Homebrew library: " + ENV["HOMEBREW_LIBRARY"]
      puts "Ruby version: " + RbConfig::CONFIG["ruby_version"]
      puts "Gem home: " + ENV["GEM_HOME"]
      puts "Gem path: " + ENV["GEM_PATH"]

Retry:

    $ brew cask style
    Homebrew library: /usr/local/Homebrew/Library
    Ruby version: 2.3.0
    Gem home: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0
    Gem path: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0
    …

Do I have the relevant Ruby directory or any of its parent directories?

    $ ls -d /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby
    ls: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby: No such file or directory

    $ ls -d /usr/local/Homebrew/Library/Homebrew/vendor/bundle
    ls: /usr/local/Homebrew/Library/Homebrew/vendor/bundle: No such file or directory

    $ ls -d /usr/local/Homebrew/Library/Homebrew/vendor
    /usr/local/Homebrew/Library/Homebrew/vendor

Now I know that Brew is not finding what it expects.

What Ruby does Homebrew expect?

    $ brew config | grep Ruby
    Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby

Do I have the version that Homebrew expects?

    $ /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby --version
    ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

Where is Homebrew getting its Ruby version? 

Search for the message text "Homebrew Ruby" by using your favorite full text search command, such as `rg` for Ripgrep, or `ag` for the Silver Searcher, etc.:

    $ cd /usr/local/Homebrew
    $ rg "Homebrew Ruby:"
    Library/Homebrew/system_config.rb
    166:      f.puts "Homebrew Ruby: #{describe_homebrew_ruby}"

Explore the file:

    Library/Homebrew/system_config.rb

Search for this method or variable:

    describe_homebrew_ruby

This code looks most relevant:

    def describe_homebrew_ruby
      "#{describe_homebrew_ruby_version} => #{RUBY_PATH}"
    end

What is setting the variable `RUBY_PATH`?

    $ rg "\bRUBY_PATH *="
    Library/Homebrew/global.rb
    21:RUBY_PATH = Pathname.new(RbConfig.ruby)

This file code looks like a possible dead end for finding our problem, because RbConfig.ruby is providing the 2.3.3 info, and not providing the info I want. This means the problem is probably starts before this file is called.

How does brew start up? 

    $ which brew
    /usr/local/bin/brew

Edit the file to print the Ruby version:

    #!/bin/bash
    set +o posix
    echo "brew ruby version:" $(ruby --version)
    …

Run:

    $ brew
    brew ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    …

Now I know that `brew` launches with the correct Ruby version.

The `brew` command leads to running this code:

     $HOMEBREW_LIBRARY/Homebrew/brew.sh

Edit the file to print the Ruby version:

    echo "brew.sh ruby version:" $(ruby --version)
    # Force UTF-8 to avoid encoding issues for users with broken locale settings.
    …

Run:

    $ brew
    brew ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    brew.sh ruby version: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    …

Now I know that the Ruby version has somehow changed between `brew` and `brew.sh`.

The `brew` command leads to running this code:

     exec /usr/bin/env -i "${FILTERED_ENV[@]}" /bin/bash 
          "$HOMEBREW_LIBRARY/Homebrew/brew.sh" "$@"
    
In the source code nearby I see:

    if [[ -z "$HOMEBREW_NO_ENV_FILTERING" && "$1" != "test-bot" ]]
    then
      PATH="/usr/bin:/bin:/usr/sbin:/sbin"

Try setting the HOMEBREW_NO_ENV_FILTERING to anything:

    $ HOMEBREW_NO_ENV_FILTERING=1 brew
    brew ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    brew.sh ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

Now I see that `brew.sh` is getting the Ruby version that I want.

The `brew.sh` command leads to running this code:

    { update-preinstall; exec "$HOMEBREW_RUBY_PATH" $HOMEBREW_RUBY_WARNINGS "$HOMEBREW_LIBRARY/Homebrew/brew.rb" "$@"; }

Edit the file to print the Ruby version:

    echo "Homebrew ruby path:" $HOMEBREW_RUBY_PATH
    { update-preinstall; exec "$HOMEBREW_RUBY_PATH" $HOMEBREW_RUBY_WARNINGS "$HOMEBREW_LIBRARY/Homebrew/brew.rb" "$@"; }

Run:

    $ HOMEBREW_NO_ENV_FILTERING=1 brew
    brew ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    brew.sh ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    Homebrew ruby path: /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby

Now I know that `brew.sh` has provided a Ruby version that's not the one I want, and it's because of HOMEBREW_RUBY_PATH.

Where does brew set `HOMEBREW_NO_ENV_FILTERING`?

    $ rg "\bHOMEBREW_RUBY_PATH *="
    Homebrew/utils/ruby.sh
    21:      HOMEBREW_RUBY_PATH="$vendor_ruby_path"
    33:        HOMEBREW_RUBY_PATH=
"/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby"
    35:        HOMEBREW_RUBY_PATH="$(type -P ruby)"
    50:        HOMEBREW_RUBY_PATH="$vendor_ruby_path"

The file has this code that looks relevant:

    if [[ -n "$HOMEBREW_MACOS" ]]
    then
      HOMEBREW_RUBY_PATH=
            "/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby"
    else
      HOMEBREW_RUBY_PATH="$(type -P ruby)"
    fi

The first setting could explain why brew is finding the System ruby, which is not what I want.

The second setting could be what I want to happen.

What does `type` do?

    $ type -P ruby
    /Users/brew/.rbenv/shims/ruby

    $ /Users/brew/.rbenv/shims/ruby --version
    ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

If I force the code to run does it work?

    if [[ -n "$HOMEBREW_MACOS" ]]
    then
      #HOMEBREW_RUBY_PATH=
            "/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby"
      HOMEBREW_RUBY_PATH="$(type -P ruby)"
    else
      HOMEBREW_RUBY_PATH="$(type -P ruby)"
    fi

Yes:

    $ HOMEBREW_NO_ENV_FILTERING=1 brew
    brew ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    brew.sh ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    Homebrew ruby path: /Users/brew/.rbenv/shims/ruby

Nearby code shows this:

    if [[ -z "$HOMEBREW_RUBY_PATH" || -n "$HOMEBREW_FORCE_VENDOR_RUBY" || "$ruby_version_new_enough" != "true" ]]
    then
      brew vendor-install ruby

Try it:

    $ brew vendor-install ruby
    …
    ==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
    ==> Pouring portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz

Retry and I now see the portable Ruby is working:

    $ brew cask style
    brew ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    brew.sh ruby version: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    Homebrew ruby path: /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby
    Homebrew library: /usr/local/Homebrew/Library
    Ruby version: 2.3.0
    Gem home: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0
    Gem path: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0
    ==> Installing or updating 'rubocop-cask' gem
    …
    10 gems installed
    5311 files inspected, no offenses detected

Success!

Reset changes:

    $ cd /usr/local/Homebrew
    $ git reset --hard

Try the real goal:

    $ brew audit --strict venn
    … runs as expected …

Success!

Question 1: how should I have done this differently? In other words, is there some kind of documentation that I didn't find in my searching, or some kind of installation process that I should have done differently? 

Question 2: how can the brew team add documentation and/or error messages that make this kind of error easier to diagnose and troubleshoot?

Thank you for your help.

**Comment by MikeMcQuaid** [comment]
> how can the brew team add documentation and/or error messages that make this kind of error easier to diagnose and troubleshoot?

I think in the case that you're running `rbenv` we assume that you're able to debug, diagnose and fix Ruby version issues yourself (as you seem to have done here). Thanks for the write-up.

**Comment by joelparkerhenderson** [comment]
Thanks, but I haven't fixed it. :)

The `rbenv` doesn't seem to have made any difference i.e. as far as I can tell, it was ignored by `brew`.

I don't understand why `brew` isn't using the Ruby in my path (e.g. when I set a custom path and export it) nor in the `rbenv` path. 

I don't know the right/best/preferred way to use the `rbenv` Ruby version, or the Ruby version in my $PATH, instead of the portable ruby.

Any tips or guidance is much appreciated.

**Comment by MikeMcQuaid** [comment]
> I don't understand why brew isn't using the Ruby in my path (e.g. when I set a custom path and export it) nor in the rbenv path.
> 
> I don't know the right/best/preferred way to use the rbenv Ruby version, or the Ruby version in my $PATH, instead of the portable ruby.

This is not supported. We support using the system Ruby (if new enough) or our portable Ruby.
