### ISSUE TITLE
some binaries (doxygen, fakeroot, p7zip, xz) installed non-executable on os 10.14?

### ISSUE THREAD

**Issue by dankegel** [Homebrew/brew#4280]
OMG THERE"S A NEW MAC OS BETA MUST TRY BREW RITE NOW type type type OH SNAP

Installed osx 10.14 beta + xcode 10 beta on a recent macbook pro, more or less freshly installed.

While installing my usual set of brew tools, the first problem I ran into was:
```
$ brew install fakeroot
```
failed because the installed fakeroot binary was not executable.

Same thing happened with p7zip, xz and doxygen.

chmod +x /usr/local/bin/*, and then chmod +x a few other things in the Cellar (e.g. /usr/local/Cellar/p7zip/16.02_1/lib/p7zip/7z), got me past the problem. 

kthxbye

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

**Comment by dankegel** [comment]
OK, moving to https://discourse.brew.sh/t/mac-os-10-14-problems/2327
