### ISSUE TITLE
brew cask upgrade is missing from zsh completion

### ISSUE THREAD

**Issue by ndegory** [Homebrew/brew#4282]
I noticed an inconsistency between the zsh completion of `brew cask` (shipped with Homebrew) and the actual commands.
The `brew cask upgrade` command is missing from the completion hints.
Pressing Tab after entering _brew cask_ should show the list of commands, including _upgrade_

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
