### ISSUE TITLE
Ability to make cask sudo alias configurable

### ISSUE THREAD

**Issue by samm-git** [Homebrew/brew#4289]
> a detailed description of your proposed feature

I would like to see sudo which is now hard-coded as configurable alias. This is required in the configuration when sudo is not enabled for the current user or some other command (e.g. su) is required to get root priviligies

> the motivation for the feature

I am currently not allowed to use `sudo` from the active user. I am pretty confident that it is not an unique use-case. 

> how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)

TBH i dont think that 90% of the users will do see any difference and agreed that it is kind of the edge use case. However, i am ok to create a PR if you think it could be accepted. If not - i will have to think about some workaround, and i would respect your choice

> what alternatives to the feature you have considered

I tried to change this locally, but it does not work because changes are get lost on every `brew upgrade` command. Probably i can create my own fork and keep it synced with a mainstream, but i feel that this is a painful overkill.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue ((don't create a new one, please) then this issue may be reopened.

**Comment by samm-git** [comment]
Description corrected. Apologize for not making it clear enough from the first round. If you believe that this usecase is very unique - please close the PR, i will understand this. And thank you for your time.

**Comment by samm-git** [comment]
@MikeMcQuaid i am not able to reopen it myself.

**Comment by MikeMcQuaid** [comment]
Can you clarify what the alias does?

**Comment by samm-git** [comment]
@MikeMcQuaid sure. Instead of running sudo it will run other command (in my case it is like that:
```
su adminuser -c "sudo id"
uid=0(root) gid=0(wheel) groups=0(wheel),1(daemon),2(kmem),3(sys),4(tty),5(operator),8(procview),9(procmod),12(everyone),20(staff),29(certusers),61(localaccounts),80(admin),33(_appstore),98(_lpadmin),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),701(com.apple.sharepoint.group.1)
```
But i think if it would be configurable everyone may have own special use-case, including removal of the `SUDO_ASKPASS` undocumented variable.

**Comment by reitermarkus** [comment]
We won't add this because running `brew cask` from another user leads to some AppleScript actions not working.
