### ISSUE TITLE
Add `brew cask --json=v1` for JSON output

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#4291]
This should follow as close a format as possible to `brew info --json=v1` and will be consumed and shared [by formulae.brew.sh](https://github.com/Homebrew/formulae.brew.sh/issues/13).

**Comment by albertpaulp** [comment]
Hi @MikeMcQuaid , I'd like to work on this, is there anybody already working on this ?

**Comment by MikeMcQuaid** [comment]
@albertpaulp There's no open PRs so you can feel free to create a PR. Anyone else should feel free to create a PR before you have, though 😄

**Comment by MikeMcQuaid** [comment]
Fixed by @alexbostock in 
https://github.com/Homebrew/brew/pull/4410.

**Comment by MikeMcQuaid** [comment]
@carddamom It'll be available in the next tag which will drop on Monday UK time at the latest.
