### ISSUE TITLE
Xcode alone is not sufficient on Mojave

### ISSUE THREAD

**Issue by qinly** [Homebrew/brew#4292]
brew update && brew upgrade
Already up-to-date.
Error: Xcode alone is not sufficient on Mojave.
Install the Command Line Tools:
  xcode-select --install

My environment：

macOS 10.14 Beta (18A293u)
Xcode-beta 10.0 beta (10L176w)

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by MikeMcQuaid** [comment]
`brew doctor` will also tell you to not file Mojave issues.
