### ISSUE TITLE
Proper Support for macOS Mojave & Xcode 10 Beta

### ISSUE THREAD

**Issue by wjk** [Homebrew/brew#4295]
While Homebrew technically supports macOS Mojave beta (it is installing without error as I write this), the one-line installer script on [brew.sh](https://brew.sh/) does not recognize Xcode 10 beta, and as such downloads and installs the High Sierra command-line tools for Xcode 9.4. I don't know if this will actually cause problems, but I presume it will (differing compiler versions, incompatible system headers/libraries, and all that), hence this bug report.

I don't know enough about brew's internals to find and fix this bug myself at this time. However, if someone could point out what changes need to be made, I'm happy to make them and submit a PR. Thanks so much!

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you had followed it you would note `brew doctor` will tell you to not submit issues for Mojave yet.

**Comment by wjk** [comment]
@MikeMcQuaid My apologies. For some bizarre reason I did not see an issue template when I submitted this issue. Nevertheless, I understand your position and will not bring this up again.
