### ISSUE TITLE
Detect rust binaries as relocatable

### ISSUE THREAD

**Issue by FiloSottile** [Homebrew/brew#4297]
Popular rust CLI tools like ripgrep and fd are relocatable (at least in practice), but `brew bottle` does not detect them as such. This is particularly problematic because rust is not relocatable, and compiling rust from source takes *forever*.

**Comment by MikeMcQuaid** [comment]
This is something we would accept a pull request for but will not be implementing ourselves I'm afraid. Also, for future please note the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
