### ISSUE TITLE
boost: build stuck on OS X 10.11.4

### ISSUE THREAD

**Issue by mdelmans** [Homebrew/brew#43]
Installation of boost with

`brew install boost --c++11`

hangs at 

`...updated 13743 targets...`

been like this for ~12 hours.

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by mdelmans** [comment]
Sorry I did't follow the protocol.

I ran` brew update` (twice)
I fixed all warnings (apart from unbowed headers I believe are from node.js)
My command line tools are up to date (OS is to the latest update as well)

Still stuck at

`...updated 13743 targets...`

Gist logs:
https://gist.github.com/3f391e758d751c78ecc62fbef9f99033

**Comment by UniqMartin** [comment]
This seems to be a legitimate bug. I'm able to reproduce it locally, though I haven't isolated the problem yet. Stay tuned …

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/homebrew-core#133
