### ISSUE TITLE
Brew doesn't work with macOS Mojave and Xcode 10 Beta

### ISSUE THREAD

**Issue by BrunoCerberus** [Homebrew/brew#4313]
![screen shot 2018-06-09 at 01 22 42](https://user-images.githubusercontent.com/10541956/41187624-d0ca7c3c-6b83-11e8-8866-240cfde54f63.png)

I having the problem above, and started when I installed the new macOs Mojave and the Xcode 10 Beta. Does someone has a solution?

**Comment by BrunoCerberus** [comment]
![screen shot 2018-06-09 at 01 27 08](https://user-images.githubusercontent.com/10541956/41187637-3ef0b104-6b84-11e8-988d-1218b8686f33.png)
same thing happens when I try to install something

**Comment by commitay** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you had followed it you would note `brew doctor` will tell you to not submit issues for Mojave yet.

**Comment by littleylv** [comment]
If you have installed Xcode beta 10, you can try this: `sudo xcode-select --switch /Applications/Xcode-beta.app`
