### ISSUE TITLE
Homebrew formulas/taps/etc definition file

### ISSUE THREAD

**Issue by walterdolce** [Homebrew/brew#4317]
> - a detailed description of your proposed feature
> - the motivation for the feature

In the PHP world, developers usually keep a `composer.json` file which contains all the project's dependencies. In the Javascript world, developers usually have a similar one: the `packages.json` file. Ruby projects, instead, define dependencies within the `Gemfile`. Python projects do this within the `Pipfile` or `requirements.txt` file.

I used Homebrew since forever now and the more I look at it and use it, the more I think of it as an "OS packages manager". Users of Homebrew can conveniently just issue `brew install {{package}}` and they are ready to use `{{package}}` straight away. 

What I am not able to do at the moment, though, is to quickly reproduce the installation of the same set of packages, [private] taps, etc on different machines. At this time of writing, I usually alternate between working on my company's laptop and my personal laptop. It happened many times that I had installed a set of packages on a machine but then I had to do the same on the other.

When it happens (and it _did_ and it _will continue to_ happen) that I have to rebuild a machine from scratch, or that I change machine altogether, I then have to start from scratch.

It would be great to have the ability to keep **one** file which would contain the definition of all the taps (private or public), formulas, casks, etc which I could then download on any machine and **just** `brew install` it.

I am not aware Homebrew provides this capability at the moment. Please correct me if I am wrong.

Ideally, I would like to have something like the following:
```
{
   "taps": [
      {
         "user_repo": "walterdolce/homebrew-private",
         "url": "git@my_private_vcs_site.com/walterdolce/homebrew-private.git"
      },
      {
         "user_repo": "my_company/homebrew-private",
         "url": "git@my_company_vcs_site.com/my-company/homebrew-private.git"
      }
   ],
   "formulas": [
      {
         "name": "go",
         "version": "1.10.2"
      },
      // ... other packages
   ]
}
```
Please note this could be a JSON, YAML, text, etc. Whichever makes more sense.

Is something like this possible with Homebrew at the moment? If so, how? 

I tried to Google/search around the web for this but I could not find anything.

> - how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)

I think it would be very relevant to Homebrew users. It would provide the ability to have a consistent set of toolings on all the possible machines they will use. They would not have to remember which tool is used where, which version, etc.

> - what alternatives to the feature you have considered
Implement some sort of script which would:
- Use "brew list --full-name --versions" to show all the installed packages along with their version
- To then compile a "dependencies file" in an easily parsable/processable format
- To then "unpack" this by another script which would trigger a series of `brew tap {{user/repo}} {{url}}` and `brew install {{package}} {{version}}`.

Thank you.

**Comment by commitay** [comment]
See https://github.com/Homebrew/homebrew-bundle

**Comment by walterdolce** [comment]
`Brewfile`! I was not aware of it. I shall peruse the organisation's repositories next time ;)

Thanks @commitay !
