### ISSUE TITLE
ran 'brew install node'

### ISSUE THREAD

**Issue by LohitakshTrehan** [Homebrew/brew#4318]
I am unable to understand the message about setting flags, while installing node by home brew. I am a beginner. so i dont know what these setting compiler flags mean.
Here is the full log:
` brew install node
==> Installing dependencies for node: icu4c
==> Installing node dependency: icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-61.1.high_sierra.bott
######################################################################## 100.0%
==> Pouring icu4c-61.1.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides libicucore.dylib (but nothing else).

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile

**For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/includ**e

==> Summary
🍺  /usr/local/Cellar/icu4c/61.1: 249 files, 67.2MB
==> Installing node
==> Downloading https://homebrew.bintray.com/bottles/node-10.4.0.high_sierra.bot
######################################################################## 100.0%
==> Pouring node-10.4.0.high_sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/10.4.0: 6,793 files, 59.6MB `

The message which is in bold.
Thanks in advance.

**Comment by vitorgalvao** [comment]
This is an issue with a formula. It belongs in [Homebrew/core](https://github.com/Homebrew/homebrew-core).

When you open the issue there, please use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks).

**Comment by vitorgalvao** [comment]
This is a question regarding a formula. It belongs in [Homebrew/core](https://github.com/Homebrew/homebrew-core). Nevertheless, there’s no real issue here, you can ignore that message as it won’t affect you.

In the future, please use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) for enclosing code.
