### ISSUE TITLE
Apache Spark installation failure

### ISSUE THREAD

**Issue by dylanxia2017** [Homebrew/brew#4319]
When I run the command line, there is an error
brew install apache-spark
Downloading https://www.apache.org/dyn/closer.lua?path=spark/spark-2.3.0/spa
Error: Failed to download resource "apache-spark"
Download failed: Couldn't determine mirror, try again later.

What I expected to happen is that I could install apache-spark. I have waited for several days. Still can't solve the problem

**Comment by vitorgalvao** [comment]
This is an issue about a formula. Please open it in [Homebrew/core](https://github.com/Homebrew/homebrew-core) instead, not forgetting to fill the template.

**Comment by vitorgalvao** [comment]
This is an issue about a formula. Please [open it in Homebrew/core](https://github.com/Homebrew/homebrew-core/issues/new?template=Reproducible-Bug-Report.md) instead.
