### ISSUE TITLE
[POTENTIAL BUG] `brew update && brew upgrade` for `youtube-dl 2018.06.11` is spitting AWS access key in the CLI

### ISSUE THREAD

**Issue by avineshwar** [Homebrew/brew#4330]
`brew update && brew upgrade` spits this for **youtube-dl**,

`==> Downloading from https://<REDACTED>s3.amazonaws.com/1039520/06ef318e-6d1b-11e8-9fa4-ccab3dfcaeed?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<REDACTED>%2F20180611%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=`

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue ((don't create a new one, please) then this issue may be reopened.
