### ISSUE TITLE
Problems loading gnuplot library

### ISSUE THREAD

**Issue by Yoshiyuki203** [Homebrew/brew#4340]
Hi,I installed gnuplot using homebrew.
"brew install gnuplot"
This worked out fine, but ,If run gnuplot from the command line, I get the following output.

$ gnuplot
dyld: Library not loaded: /opt/local/lib/libcerf.1.dylib
  Referenced from: /usr/local/bin/gnuplot
  Reason: image not found
Abort trap: 6

Homebrew version is 1.6.8 , I did "brew update" and "brew doctor" , and nothing seems to be wrong.
I have Xcode 9.4.1 installed and I'm running 10.13.5 Mac OS High sierra.

Please Help Me.

**Comment by Yoshiyuki203** [comment]
Sorry,
running "brew doctor"

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/yoiyoi/anaconda3/bin/icu-config
  /Users/yoiyoi/anaconda3/bin/freetype-config
  /Users/yoiyoi/anaconda3/bin/xslt-config
  /Users/yoiyoi/anaconda3/bin/libpng16-config
  /Users/yoiyoi/anaconda3/bin/python3.6m-config
  /Users/yoiyoi/anaconda3/bin/libpng-config
  /Users/yoiyoi/anaconda3/bin/xml2-config
  /Users/yoiyoi/anaconda3/bin/python3-config
  /Users/yoiyoi/anaconda3/bin/curl-config
  /Users/yoiyoi/anaconda3/bin/ncursesw6-config
  /Users/yoiyoi/anaconda3/bin/pcre-config
  /Users/yoiyoi/anaconda3/bin/python3.6-config

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/drawstuff/drawstuff.h
  /usr/local/include/drawstuff/version.h
  /usr/local/include/fftw3.h
  /usr/local/include/ode/collision.h
  /usr/local/include/ode/collision_space.h
  /usr/local/include/ode/collision_trimesh.h
  /usr/local/include/ode/common.h
  /usr/local/include/ode/compatibility.h
  /usr/local/include/ode/contact.h
  /usr/local/include/ode/error.h
  /usr/local/include/ode/export-dif.h
  /usr/local/include/ode/mass.h
  /usr/local/include/ode/matrix.h
  /usr/local/include/ode/memory.h
  /usr/local/include/ode/misc.h
  /usr/local/include/ode/objects.h
  /usr/local/include/ode/ode.h
  /usr/local/include/ode/odeconfig.h
  /usr/local/include/ode/odecpp.h
  /usr/local/include/ode/odecpp_collision.h
  /usr/local/include/ode/odeinit.h
  /usr/local/include/ode/odemath.h
  /usr/local/include/ode/odemath_legacy.h
  /usr/local/include/ode/precision.h
  /usr/local/include/ode/rotation.h
  /usr/local/include/ode/threading.h
  /usr/local/include/ode/threading_impl.h
  /usr/local/include/ode/timer.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libdrawstuff.la
  /usr/local/lib/libfftw3.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/fftw3.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libdrawstuff.a
  /usr/local/lib/libfftw3.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
  gnuplot
  gcc

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/g++
  /usr/local/bin/gcc

Many Warning... ：＿（

**Comment by ilovezfs** [comment]
It built against MacPort's libcerf. Move MacPorts out of the way, as noted by `brew doctor`, and then `brew reinstall gnuplot`.

In the future, please open formula-specific issues in https://github.com/Homebrew/homebrew-core
