### ISSUE TITLE
fix configure options for nghttp2

### ISSUE THREAD

**Issue by tdashton** [Homebrew/brew#4341]
# What you were trying to do (and why)

`brew install nghttp2` as standalone or dependency for php (72)

install `nghttp2` as standalone or dependency (php)

# What happened (include command output)

```
shrpx_log_config.cc:62:1: error: thread-local storage is unsupported for the current target
thread_local std::unique_ptr<LogConfig> config = make_unique<LogConfig>();
^
1 error generated.
make[3]: *** [libnghttpx_a-shrpx_log_config.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/libnghttpx_a-shrpx_worker.Tpo .deps/libnghttpx_a-shrpx_worker.Po
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Error because threading is not supported, also outlined here: 

> Mac OS X users may need the --disable-threads configure option to disable multi-threading in nghttpd, nghttpx and h2load to prevent them from crashing. A patch is welcome to make multi threading work on Mac OS X platform.

source: https://nghttp2.org/documentation/package_README.html

# What you expected to happen

package to compile

# Step-by-step reproduction instructions (by running `brew` commands)

`brew install nghttp2` as standalone or dependency for php (72)

# Reproducible Bug Report 

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Output

## brew config

```
HOMEBREW_VERSION: 1.6.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3081390ff845a6172b9004cf404c3e028e3be745
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4fbabc99fcf13f3e82254fec472f1fee896cbf3f
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 6.0 build 600
Git: 1.9.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.60.0 => /usr/local/opt/curl/bin/curl
Java: N/A
macOS: 10.9.5-x86_64
CLT: 6.2.0.0.1.1424975374
Xcode: 6.2
XQuartz: N/A
```

## brew doctor

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  nghttp2

Warning: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```

**Comment by scpeters** [comment]
> If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose.

**Comment by tdashton** [comment]
Found it already, will do. Thanks!

**Comment by DomT4** [comment]
FYI: https://github.com/Homebrew/homebrew-core/pull/26484
