### ISSUE TITLE
Install php56-intl and php56-xdebug

### ISSUE THREAD

**Issue by StMarsh** [Homebrew/brew#4347]
Hello. After updating the BREW I started to get errors:

`Failed loading /usr/local/opt/php56-xdebug/xdebug.so:  dlopen(/usr/local/opt/php56-xdebug/xdebug.so, 9): image not found
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56-intl/5.6.33_14/intl.so' - dlopen(/usr/local/Cellar/php56-intl/5.6.33_14/intl.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56-intl/5.6.33_14/intl.so' - dlopen(/usr/local/Cellar/php56-intl/5.6.33_14/intl.so, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): image not found in Unknown on line 0
PHP 5.6.36 (cli) (built: Apr 26 2018 22:02:57) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies`

But I can not install these modules using the command.
`brew install php56-intl`
`brew install --build-from-source php56-intl`
Please tell me how I can solve this problem. To my still use versions above 5.6 I can not because Symfony 2.7 can not work with them.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
