### ISSUE TITLE
gobject-introspection-1.56.1.tar.xz from upstream is broken

### ISSUE THREAD

**Issue by falfaro** [Homebrew/brew#4362]
Downloading https://download.gnome.org/sources/gobject-introspection/1.56/gobject-introspection-1.56.1.tar.xz from upstream and trying to "untar" it fails:

$ brew install gobject-introspection
...
gobject-introspection-1.56.1/docs/reference/html/gi-gitypelib.html: Can't unlink already-existing object
tar: Error exit delayed from previous errors.
Error: Failure while executing: tar xJf /Users/falfaro/Library/Caches/Homebrew/gobject-introspection-1.56.1.tar.xz

**Comment by falfaro** [comment]
Actually, it could very well be a problem with the built-in "tar" in macOS 10.14 (beta2). I tried unpacking in Ubuntu 18.10 and it works fine :-/

**Comment by Kush131** [comment]
Think you may be right! I am running into the same problem with texi2html installing.

**Comment by ilovezfs** [comment]
Probably you need to file a rdar with Apple.

Formula specific issues belong in https://github.com/Homebrew/homebrew-core/issues

Please read and fill out the issue template in future, thanks.

**Comment by falfaro** [comment]
For the record, I've opened a bug against Apple for this particular problem.

**Comment by ilovezfs** [comment]
Thanks. rdar number?

**Comment by sidneys** [comment]
Wait, now TAR is broken on macOS? If Steve Jobs was alive for a day, he would donate all of his controlling stock to Microsoft and then happily return to his resting place...
