### ISSUE TITLE
Add Features to help with MacOS Mojave 64-Bit / Metal Transition

### ISSUE THREAD

**Issue by darkmastermindz** [Homebrew/brew#4364]
## Feature Suggestion:
- Implement a way to add switch to only install 64 bit / Metal versions of programs from brew / cask / etc. Providing a warning if only 32 bit / OpenGL / OpenCL is available in brew doctor (on compatible devices). 
- Provide warnings during installation if a package only has a 32-bit / OpenGL / OpenCL version or has a 64 bit / Metal version but is not installed. Allow this warning to be turned on/off and permission to install 64 bit / Metal version instead so it's less invasive. 
- Implement a way to list only 32 bit  / OpenGL / OpenCL packages that do not have 64 bit / Metal.

## Motivation:
- "[Starting with macOS High Sierra 10.13.4, apps that have not been updated to use 64-bit processes produce a one-time alert when opened. This gives users advance notice that they are running 32-bit software, which will not be compatible with macOS in the future. ](https://support.apple.com/en-us/HT208436)"
- "Apps built using OpenGL and OpenCL will continue to run in macOS 10.14, but these legacy technologies are deprecated in macOS 10.14. Games and graphics-intensive apps that use OpenGL should now adopt Metal. Similarly, apps that use OpenCL for computational tasks should now adopt Metal and Metal Performance Shaders." [See Deprecations in the new macOS Mojave](https://developer.apple.com/macos/whats-new/)

## Purpose:
- This allows Homebrew users to circumvent / minimize this warning from happening:
![image](https://user-images.githubusercontent.com/6164335/41691916-3c678516-74cb-11e8-8d25-35eaa031207d.png)
- Further motivates the developer community to update packages to a 64 bit architecture.
- Helps Homebrew's future transition in providing compatible software easier when the transition date is set (see https://support.apple.com/en-us/HT208436).
- Keeps all packages pristine and healthy for when the transition is fully implemented.

## Alternatives considered:
- Manually checking each package and keep track for the architecture before installing it.

**Comment by MikeMcQuaid** [comment]
> This allows Homebrew users to circumvent / minimize this warning from happening

Does this happen with Homebrew applications?

If it does this is an interesting idea but it's something we'd need to review a PR for rather than do ourselves.

**Comment by darkmastermindz** [comment]
@MikeMcQuaid Yes, this happens with Homebrew applications, especially a lot of them within homebrew cask. Will work on doing a PR.
