### ISSUE TITLE
after carry out :brew update && brew upgrade , my mac seems lost all the configuration

### ISSUE THREAD

**Issue by xiaoxiaojuan** [Homebrew/brew#4365]
I was trying to install go, and I run brew update && brew upgrade, then the import xxx in my python dosen't work, no matter I import local file or the package I already installed, for example requests,  it tells me "ImportError: No module named requests" 

![image](https://user-images.githubusercontent.com/23327952/41696353-3f8b3bd6-7546-11e8-8230-9eefec2d1935.png)

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
