### ISSUE TITLE
Installing TeX from source is not actually weird and gross

### ISSUE THREAD

**Issue by jes5199** [Homebrew/brew#437]
If you run, `brew install latex` on any version of homebrew since 2010, you will see this message:

```
Installing TeX from source is weird and gross, requires a lot of patches,
and only builds 32-bit (and thus can't use Homebrew deps on Snow Leopard.)
```

This is factually inaccurate. The TeX source code is definitionally perfect, created with the ur-keyboard though the divine conduit of Donald Knuth.
Attempting to install it should not be considered "weird and gross", https://github.com/Homebrew/brew/commit/78507894577ac03587bc7786254f2a54268fd401 :eyes:. What is truly weird and gross is all the software that has been written that fails, itself, to be TeX! 
In the end, all your abstract factory factories will fall, and only TeX will remain.

**Comment by chdiza** [comment]
It's still the case that *installing* it is weird and gross, even if the exalted nugget at the center of the thicket of weeds that has grown around it is perfect.
