### ISSUE TITLE
bump-formula-pr prompts for username, password then errors

### ISSUE THREAD

**Issue by simonwhitaker** [Homebrew/brew#4370]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

---

I'm trying to update a formula using `bump-formula-pr`, and I'm having a problem with the authentication step. Specifically, I'm getting an "invalid username or password" error. I've tried multiple times, carefully copying and pasting from my password manager each time. I am able to authenticate successfully with the `hub` command-line tool using the same credentials.

Things that might be relevant:

1. I use a password manager and have a long, random password (30 characters, includes alpha-numerics as well as one or more of each of the following non-alphanumeric characters: `.^&`) (**Update**: I changed my password to contain alphanumerics only, and I still get the same error.)
2. I use 2-factor authentication on Github, although I don't get far enough to enter the 6-digit OTP
3. I'm authenticated with `hub`, which works fine. I deleted my `~/.config/hub` and re-authenticated by running `hub create` on a new repo and was prompted for my username, password and OTP. It all worked as expected. Not sure this is relevant but when I searched for others with a similar issue I saw mention of `hub` being used by `bump-formula-pr`.

## Command output

```
$ brew bump-formula-pr --strict --url=https://github.com/simonwhitaker/gibo/archive/2.1.0.tar.gz --sha256=635965c105eb98f56110bc98304669c50ab3ca0a835c2b24277e15dc91038479 gibo
Already up-to-date.
==> replace /https:\/\/github\.com\/simonwhitaker\/gibo\/archive\/2\.0\.0\.tar\.gz/ with "https://github.com/simonwhitak
==> replace "3e6fadfc23080a500353a70231851ed5381067bc99bd3d32058da9abe045b018" with "635965c105eb98f56110bc98304669c50ab
M	Formula/gibo.rb
Switched to a new branch 'gibo-2.1.0'
[gibo-2.1.0 65e11987c3] gibo 2.1.0
 1 file changed, 2 insertions(+), 2 deletions(-)
Username for 'https://github.com': simonwhitaker
Password for 'https://simonwhitaker@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/simonwhitaker/homebrew-core.git/'
Error: Failure while executing: git push --set-upstream https://github.com/simonwhitaker/homebrew-core.git gibo-2.1.0:gibo-2.1.0
```

## Config and doctor output

```
$ brew config; and brew doctor
HOMEBREW_VERSION: 1.6.9-15-g41e2792
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 41e27928c475e2c8ed8c93161269936bd85f8847
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 00dfbfc078206126c47b84a28855266a60403f32
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LINKAGE_CACHE: 1
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_05, 1.6.0_65-b14-468
macOS: 10.13.5-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
Your system is ready to brew.
```

(Aside: I'm using fish shell, but I get the same behaviour in zsh.)

**Comment by GauthamGoli** [comment]
`bump-formula-pr` doesn't use `hub` anymore. It uses GH API now. This could be a bug, I will look into this.

**Comment by MikeMcQuaid** [comment]
This prompt is from Git rather than Homebrew. As when using 2FA for HTTPS on GitHub you need to enter a personal access token and not your password. Hub will create a personal access token for you.

**Comment by simonwhitaker** [comment]
The problem is [this call](https://github.com/Homebrew/brew/blob/b87fc8c53aa500f2b4d6aa44af3ebede38699e83/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L304)  to `git push`.

```
git push --set-upstream https://github.com/simonwhitaker/homebrew-core.git gibo-2.1.0:gibo-2.1.0
```

**Comment by simonwhitaker** [comment]
@MikeMcQuaid Can we leave this one open please? At minimum, if the command fails it should give a more helpful error message, and clean up after itself. (After the command fails, my local brew checkout is left with the <repo>-<version> branch checked out. `brew doctor` will flag this, if I run it. Otherwise the problem isn't visible to me as a regular user.)

**Comment by MikeMcQuaid** [comment]
This is beyond the scope of Homebrew. The issue here is the interaction between Git and GitHub's 2FA.

**Comment by simonwhitaker** [comment]
@MikeMcQuaid Homebrew can at least show a better error message though, right? It can't be desirable behaviour for the command recommended in the Homebrew docs to hose your Homebrew installation if you have 2FA enabled in GitHub, surely.

**Comment by MikeMcQuaid** [comment]
> Homebrew can at least show a better error message though, right?

Please don't say things like "at least"; we're volunteers and it implies we're doing below the bare minimum.

> It can't be desirable behaviour for the command recommended in the Homebrew docs to hose your Homebrew installation if you have 2FA enabled in GitHub, surely.

It doesn't hose your Homebrew installation in any meaningful way. It's a "developer command" (see the manpage) that checks out a branch in Git. If you don't know how to change back to another branch in Git or use 2FA to push with Git on GitHub: I don't think it's that's our responsibility to teach you that. It's not a good use of project time or code to maintain to write a wrapper around `git push` for trying to improve the messaging of the upstream command.

**Comment by simonwhitaker** [comment]
> Please don't say things like "at least"; we're volunteers and it implies we're doing below the bare minimum.

Sorry Mike, that really wasn't my intention. I do appreciate the work everyone does here.

You replied "This is beyond the scope of Homebrew", and while I get the point you're making, the whole beauty of Homebrew for me as a user is that it makes the tricky, laborious process of installing third-party software easy. Homebrew is a time-saver, a pain reliever. 

This issue represents a little wrinkle in the corner of Homebrew where Homebrew actually does the opposite; it inadvertently *costs* me time and *causes* a smidgen of pain. It feels to me like it's very much in the spirit of Homebrew to not do this.

Yes, the underlying issue is the interaction between git and GitHub's 2FA. But the script I'm running, which is exposing this issue and (critically) silently leaving my Homebrew installation in an unexpected state, is part of Homebrew.

> It doesn't hose your Homebrew installation in any meaningful way. It's a "developer command" (see the manpage) that checks out a branch in Git. If you don't know how to change back to another branch in Git or use 2FA to push with Git on GitHub: I don't think it's that's our responsibility to teach you that.

I do know how to do both of those things, and I'm not suggesting that you need to teach me anything. But the consequence of running this command when 2FA is enabled is that my brew installation is left on a branch and there is no indication that it's happened. Whether I know how to fix it or not is immaterial; I don't even realise there's anything that needs fixing.

A comment in [these docs](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) and the manpage for `bump-formula-pr` explaining that, if you use 2FA then, when prompted for your password, you actually need to enter a personal access token instead, would be very useful, and would help to relieve the time/pain burden mentioned above. If you think such an addition would be appropriate, please let me know; I'm happy to make it and send a PR.

**Comment by MikeMcQuaid** [comment]
> Yes, the underlying issue is the interaction between git and GitHub's 2FA. But the script I'm running, which is exposing this issue and (critically) **silently** leaving my Homebrew installation in an unexpected state, is part of Homebrew.
> I do know how to do both of those things, and I'm not suggesting that you need to teach me anything. But the consequence of running this command when 2FA is enabled is that my brew installation is left on a branch and **there is no indication** that it's happened.

To quote your own output:

> Switched to a new branch 'gibo-2.1.0'

> A comment in these docs and the manpage for bump-formula-pr explaining that, if you use 2FA then, when prompted for your password, you actually need to enter a personal access token instead, would be very useful, and would help to relieve the time/pain burden mentioned above. If you think such an addition would be appropriate, please let me know; I'm happy to make it and send a PR.

I don't think such documentation is necessary. Lots of people use 2FA with GitHub and you're one of the few (maybe the first) to report this problem. I appreciate that's annoying but we need to start seeing problems like this occurring again and again to justify the overhead for everyone (hence why the issue was closed).
