### ISSUE TITLE
Alert when user input needed

### ISSUE THREAD

**Issue by jivanpal** [Homebrew/brew#4379]
Hey, all.

I propose that when user input is needed during installation/upgrading of packages (e.g. when a package installer requires the admin/sudo password), that a BEL character is printed to the screen to alert the user that their input is needed.

There have been several times when I have installed many packages simultaneously, only to leave `brew` running in the background, come back later, and see that not even the first package has been installed yet because I needed to input my password.

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template (like it told you to). Homebrew without Cask never prompts for input. Homebrew Cask cannot bell in this case because it’s the installer rather than Homebrew Cask that prompts (correct me if I’m wrong @reitermarkus).

**Comment by reitermarkus** [comment]
We also support `SUDO_ASKPASS` for unattended execution.

**Comment by jivanpal** [comment]
@MikeMcQuaid For reference, I did fill out the issue template (like it told me to).

**Comment by scpeters** [comment]
~~~
Please replace this section with:
- a detailed description of your proposed feature
- the motivation for the feature
- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)
- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.
~~~

@jivanpal  I saw a description and motivation, but I didn't see a discussion of how it would be relevant for at least 90% of Homebrew users or a discussion of alternatives.

**Comment by ilovezfs** [comment]
Would a cask DSL for `sudo_required` or even `input_required` allow this to work?

**Comment by vitorgalvao** [comment]
@ilovezfs The situations where `sudo` is required are predictable enough (`pkg` stanza, `installer` stanza with `sudo: true`, …) that it’s likely we could guess when it will be needed by parsing casks as they are.
