### ISSUE TITLE
Add documentation on which alternative compilers are supported

### ISSUE THREAD

**Issue by afnanenayet** [Homebrew/brew#4387]
[Disclaimer, I'm not sure if this really counts as a "feature" since it would just be some tweaks to the existing documentation, but it's certainly not a bug]

### Description:

I think the docs/manpage should specify the valid options for the `--cc` flag, and which compilers/versions they correspond to, and document the `HOMEBREW_CC` environment variable in the section in the manpage about environment variables.

### Motivation:

Currently the Homebrew documentation could be a bit clearer/less sparse on how a user can specify an alternative compiler for when brew builds anything from source. I wanted to use LLVM Clang instead of Apple's Clang, and it took me a while to figure out how to do it because there seems to be no documentation specifying the flags to pass for each compiler variant, and which flags are valid.

Additionally, the manpage for the `--cc` flag specified

> If --cc=``compiler is passed, attempt to compile using compiler. compiler should be the name of the compiler's executable

This does not apply for `clang-6.0`, which is the version of clang provided by the LLVM package from brew. Its executable name is `clang-6.0`, but the option to specify it is `llvm_clang`.

In order to find the valid options for the flag, I had to dig through the source code until I found the list of valid compilers, which I think many people would find inconvenient. Perhaps generate it from the `compilers.rb` file?

It seems like `HOMEBREW_CC` is not mentioned at all in the manpage, and I ended up stumbling upon it from some GitHub issues -- I really think that having it documented would be helpful.

### Relevance

While I'm not sure how many people choose to build packages from source, whenever you _do_ have to compile a package, it is helpful to know which compilers you can use, and how to select a particular one, and having a more documented tool is a win for everyone, I'd say.

### Alternatives

You could just add a little snippet to the manpage for the `--cc` flag that says "to use brew's Clang, set compiler=llvm_clang", if you wanted to make this a minimal change.

I would be willing to create a PR for this as well.

**Comment by MikeMcQuaid** [comment]
We technically don't "support" any alternative compilers. We'll accept pull requests to improve the help accordingly, though. Thanks!
