### ISSUE TITLE
brew install --HEAD gcc funky suffix stuff....

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/brew#44]
I added a `head` url a while back (#46648 , 1bf2a681cca53db016415de5ea91324c96d4ece8) but upon further inspection the value of `version_suffix` seems to be empty which causes the binaries to be named `gcc-` etc.

I was hoping to submit a PR to fix this, but was wondering, what a decent `version_suffix` for gcc should be when built from GCC trunk.

Currently, I think the version number they are using for trunk is 6.0.0 and then this gets bumped to 6.1.x when they issue a stable release.  (I could be wrong here.) I also heard that the 6.x release is not far away and is due sometime this spring.

As such what is the best way to treat `version_suffix` when building from GCC trunk (aka `--HEAD`)?

On the one hand we could do `version_suffix = "HEAD"` (or `trunk`) which won't ever need updating,  or we could do `version_suffix = 6` when `--HEAD` is passed. Other ideas?

Let me know and I'll work up a PR.

**Comment by mikemcquaid** [comment]
In future submit tickets about formulae to `homebrew-core`, thanks.

In this case I think the best approach is to adjust the `version_suffix` method so it generates a head version suffix based on the stable suffix + 1. Let me know if you need help with that.

**Comment by zbeekman** [comment]
My apologies, I misread the text at brew-legacy...

Great idea about stable +1 :100: I'll start looking into it.

**Comment by zbeekman** [comment]
@mikemcquaid any tips for querying the stable version suffix? My ruby is still very much a WIP

**Comment by zbeekman** [comment]
@mikemcquaid I think I've found an acceptable solution to implement your suggestion... I'll include it in my PR for GCC 6.1

**Comment by zbeekman** [comment]
The more I think about this the more I lean towards a version suffix of `trunk` when compiling with `--HEAD`... when a new major release is issued (like yesterday's 6.1... PR incoming after my tests finish...) having a suffix of stable.version + 1 could be cause for confusion... --HEAD will result in a suffix of say 6, but gcc-trunk will really be at 7. And the latest stable is 6.1, but homebrew only knows about 5.3 until the formula gets updated...

**Comment by mikemcquaid** [comment]
@zbeekman `-trunk` (or `-master` if they use Git) seems fine/appropriate 👍

**Comment by zbeekman** [comment]
Gcc uses SVN and has a canonical `trunk` branch.

I'm also wondering if I should switch this from `--HEAD` to `--devel` which
might be clearer
