### ISSUE TITLE
Improve system upgrade handling

### ISSUE THREAD

**Issue by joshka** [Homebrew/brew#4400]
System updates often happen at a lower frequency than brew updates. My most recent one (to Sierra :/) failed with the following:
```
→ brew upgrade
Updating Homebrew...
==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing: git config --local --replace-all homebrew.analyticsmessage true
==> Upgrading 10 outdated packages, with result:
awscli 1.15.40 -> 1.15.40_1, fswatch 1.11.3 -> 1.12.0, gdbm 1.15 -> 1.16, httpie 0.9.9_3 -> 0.9.9_4, libyaml 0.1.7 -> 0.2.1, mas 1.3.1_1 -> 1.4.1, mitmproxy 4.0.3 -> 4.0.3_1, python 3.6.5_1 -> 3.7.0, ydiff 1.0 -> 1.1, youtube-dl 2018.06.19 -> 2018.06.25
==> Upgrading youtube-dl
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing: git config --local --replace-all homebrew.private true
```
Fixing this was as simple as reinstalling the xcode command line tools. (`xcode-select -install`), but the message wasn't clear on this. I'd suggest improve the message, and this should not continue when things break early on in the process. At the very least detect that a system update has occurred.

- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)

(Everyone updates their system at some point).

- what alternatives to the feature you have considered

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
> Fixing this was as simple as reinstalling the xcode command line tools. (xcode-select -install), but the message wasn't clear on this. I'd suggest improve the message, and this should not continue when things break early on in the process. At the very least detect that a system update has occurred.

Which version of macOS is this?

**Comment by joshka** [comment]
This was moving from El Capitan -> Sierra.

**Comment by MikeMcQuaid** [comment]
@joshka Can you try to submit a PR that checks for this invalid configuration? The relevant similar code is here: https://github.com/Homebrew/brew/blob/61a8c4d1fb8b215b12b51aec69a1b2b5b11ba75a/Library/Homebrew/brew.sh#L173-L198

**Comment by joshka** [comment]
I thought that this might just be a El Cap -> Sierra issue, but it seems Mojave has the same problem according to https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path#comment421727_254381:
>Still applies to macOS Mojave! I think every year I come back to this post.

I'm not entirely sure how to write a test for this due to:
1. The bash script is not tested at all currently
2. I'm not sure how to intentionally break my system's CLT path without doing a system upgrade (or how to test it at all without a machine to run an upgrade from).

It may also be worth adding a diagnostic check similar to:
https://github.com/Homebrew/brew/blob/61a8c4d1fb8b215b12b51aec69a1b2b5b11ba75a/Library/Homebrew/extend/os/mac/diagnostic.rb#L227-L237

I was unsure whether the xcode license check output comes from xcrun or from clang. I'm also unsure if this should break things always. Does brew always use the xcode shimmed version of git (and hence always calls xcrun?). I wonder whether `xcrun --find git` would be a good check instead of trying to run clang with no input files. Diving deeper on [how the xcrun process works](https://macops.ca/developer-binaries-on-os-x-xcode-select-and-xcrun/), it seems that there's a lot of edge cases. I couldn't find any formal docs on this though, mainly just suggestions to just run xcode-select --install.

**Comment by MikeMcQuaid** [comment]
@joshka So is https://github.com/Homebrew/brew/pull/4404 being tested blind?

**Comment by joshka** [comment]
Kinda. It’s informed by a match on the error in the first post in this issue. I can’t repro without a El Capitan install with Xcode that gets upgraded. There’s also no guarantee that this will be the exact error message next time this breaks (the SO posts suggest it does going to Mojave).

I think the PR has little downside and a bunch of upside (at the very least it calls out that this may be a problem and suggests an easy fix for next time it is if the message changes).

**Comment by MikeMcQuaid** [comment]
@joshka I'd like to see at least one person verify that it catches the error as expected as otherwise we may just be adding dead code.

**Comment by joshka** [comment]
I remembered I have a spare laptop that's lying around that should be on El Capitan and ready to break. I'll give it a try there later this week.

**Comment by MikeMcQuaid** [comment]
Great, thanks @joshka 🙇
