### ISSUE TITLE
Mac OS 10.14 Mojave brew upgrade Curl LibreSSL SSL_connect: SSL_ERROR_SYSCALL 

### ISSUE THREAD

**Issue by moosti** [Homebrew/brew#4436]
Hi, I installed mojave public beta few days ago
but now when I try to upgrade a package or install some brand new package when brew try to download it, after many tries exit with this error 
`    curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to example.com:443`

here my brew config 
`       
       brew config       
                                                                                 
        HOMEBREW_VERSION: 1.6.9

      ORIGIN: https://github.com/Homebrew/brew

      HEAD: c814199a791867ab75f90a22715e2475706b13d8

      Last commit: 3 weeks ago

      Core tap ORIGIN: https://github.com/Homebrew/homebrew-core

      Core tap HEAD: a6e9da62b7662f2f72cb58a33cb123a81f7da192

      Core tap last commit: 18 minutes ago

      HOMEBREW_PREFIX: /usr/local

      CPU: quad-core 64-bit ivybridge

      Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby

      Git: 2.17.0 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git

      Curl: 7.54.0 => /usr/bin/curl

     Java: 10.0.1

      macOS: 10.14-x86_64

     CLT: 10.0.0.0.1.1530455945

     CLT headers: 10.0.0.0.1.1530455945

     Xcode: 10.0 => /Applications/Xcode-beta.app/Contents/Developer

     XQuartz: N/A`

and here is curl version 
`     /usr/bin/curl --version       
                                                                        
     curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.4 zlib/1.2.11 nghttp2/1.24.1
     Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs     smtp smtps telnet tftp

      Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy`

**Comment by moosti** [comment]
issue solves by set this env variable:
`export HOMEBREW_FORCE_BREWED_CURL =1`

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
