### ISSUE TITLE
python@2: ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by viztor** [Homebrew/brew#4438]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
trying to use swift
https://askubuntu.com/questions/981663/python2-7-broken-by-weakref-import-error-please-help
- What happened (include command output)
```
 ~ swift                                                                                                         
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Welcome to Apple Swift version 4.2 (swiftlang-1000.0.25 clang-1000.0.28.1). Type :help for assistance.
  1>
```
- What you expected to happen
it is all fine if i remove python@2 according to https://askubuntu.com/questions/981663/python2-7-broken-by-weakref-import-error-please-help
- Step-by-step reproduction instructions (by running `brew` commands)
brew install python@2
swift

**Comment by MikeMcQuaid** [comment]
That’s not a brew command
