### ISSUE TITLE
cargo_install helper

### ISSUE THREAD

**Issue by sonicdoe** [Homebrew/brew#4442]
Several formulas use Rust’s package manager [Cargo](https://doc.rust-lang.org/cargo/). Since there are multiple ways of installing a package (e.g. `cargo install` and `cargo build`—see also https://github.com/Homebrew/homebrew-core/pull/28846), I’d suggest a `cargo_install` helper. There’s already a similar helper for Haskell’s package manager: [`cabal_install `](https://github.com/Homebrew/brew/blob/1.6.9/Library/Homebrew/language/haskell.rb#L47-L59).

I’m not really familiar with Homebrew’s codebase which is why I’m opening this issue first.

**Comment by ilovezfs** [comment]
We have an audit to require use of

```
system "cargo", "install", "--root", prefix
```

There's no need for a special DSL here but thanks for the idea, @sonicdoe!
