### ISSUE TITLE
Context install

### ISSUE THREAD

**Issue by nitrocode** [Homebrew/brew#4443]
Hi. First of all thank you so much for this project. It has mitigated almost all the pain of installing applications on osx.

# Description

I'd like to be able to install [context](http://wiki.contextgarden.net/Main_Page) directly from the brew instead of running this script

```
mkdir $HOME/context
cd $HOME/context
rsync -av rsync://contextgarden.net/minimals/setup/first-setup.sh .
sh ./first-setup.sh --modules=all --engine=luatex
```

# Motivation

To make it easier to install the dependency for pandoc and tex related support. See [pandoc_resume](https://github.com/mszep/pandoc_resume) project.

# Relevance

It's relevant in the tex, latex, pandoc world of scientific documents and typesetting. Pandoc is already formulated in brew.

# Alternatives

I haven't found an alternative that can do what context can do. I did find a suboptimal, alternative way to install it using the sh[ell script provided by contextgarden.net](http://wiki.contextgarden.net/ConTeXt_Standalone#Single_user_installation) as mentioned above.

Also a [previous attempt was made at this](https://discourse.brew.sh/t/cannot-set-the-man-page-for-context-app-after-shell-install/1601) but it doesn't look like it met standards.

**Comment by RandomDSdevel** [comment]
@nitrocode:  ConTeXt should be available as part of TeX Live, distributed for OS X/macOS from [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) using the TeX Users' Group's upstream MacTeX package; run `brew cask install mactex` to get it.

**Comment by nitrocode** [comment]
I did not know about this. :tada:

**Comment by RandomDSdevel** [comment]
Glad I could help, @nitrocode!

**Comment by nitrocode** [comment]
@RandomDSdevel wait sorry. I spoke to soon. I ran `brew cask install mactex` but it did not install the command line app `context`.

**Comment by ilovezfs** [comment]
@nitrocode please read the upstream ConTeXt documentation on how to set up ConTeXt with MacTeX: http://wiki.contextgarden.net/Mac_Installation and contact them if you need more help with that.

This issue tracker is for bugs related to the `brew` package manager itself.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Couldn't have said it better myself, @ilovezfs.  @nitrocode probably should have filed this issue with [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) instead in the first place, too, since he was initially asking for a new formula for ConTeXt, but that's water under the bridge now; on with the day…
