### ISSUE TITLE
`brew doctor` produces incorrect error message

### ISSUE THREAD

**Issue by grahampugh** [Homebrew/brew#4447]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [*] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [*] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [*] ran `brew update` and can still reproduce the problem?
- [*] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [8] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
**- What you were trying to do (and why)**

Run `brew doctor`

**- What happened (include command output)**

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: /usr/local is not writable.

You should change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami) /usr/local
```

**- What you expected to happen**

There should be no error message suggesting that `/usr/local` permissions should be changed, as this is not possible to do from macOS 10.13 onwards. `brew doctor` should only check if the folders **within** `/usr/local` that are required by Homebrew are correctly owned, and only report an error if they are not.

**- Step-by-step reproduction instructions (by running `brew` commands)**

* Simply run `brew doctor` or `brew update` to see the error message.

**Comment by MikeMcQuaid** [comment]
You didn’t provide the brew config output as requested.

**Comment by grahampugh** [comment]
That doesn't work.

```$ brew update
Error: /usr/local is not writable. You should change the
ownership and permissions of /usr/local back to your
user account:
  sudo chown -R $(whoami) /usr/local
itscdimacpro:erase-install gpugh$ brew update-reset
==> Fetching /usr/local/Library/Taps/homebrew/homebrew-core...

==> Resetting /usr/local/Library/Taps/homebrew/homebrew-core...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

itscdimacpro:erase-install gpugh$ brew update
Error: /usr/local is not writable. You should change the
ownership and permissions of /usr/local back to your
user account:
  sudo chown -R $(whoami) /usr/local
```

Note I just installed it for the first tim on this computer today.

**Comment by MikeMcQuaid** [comment]
> HOMEBREW_VERSION: >=1.4.0 (shallow or no git repository)
> ORIGIN: (none)
> HEAD: (none)
> Last commit: never

This is pretty screwed. How did you install it?

**Comment by grahampugh** [comment]
```curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C /usr/local 2>&1```

**Comment by MikeMcQuaid** [comment]
Please follow the instructions on https://brew.sh instead.

**Comment by MikeMcQuaid** [comment]
I don't know where those instructions are from but they are incorrect.

**Comment by grahampugh** [comment]
Yeah, looks like. I got them here, looking for a non-interactive way to deploy Homebrew:
https://www.jamf.com/jamf-nation/discussions/24803/deploy-homebrew

I've now figured out a better non-interactive way to do it via:
```
    osascript <<'EOF'
    tell application "Terminal"
        activate
        do script ("yes | /usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\"") in window 1
    end tell
EOF
```

Thanks for your help.

**Comment by MikeMcQuaid** [comment]
You’re welcome.
