### ISSUE TITLE
brew installing postgres as root (I think) and not finishing

### ISSUE THREAD

**Issue by geuis** [Homebrew/brew#445]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

`brew install postgres` seems to be installing as root. This is creating /usr/local/var/postgres with the owner as `root` and this prevents `initdb` from completing the db setup.

If I manually chown and chmod on /usr/local/var/postgres, there is a `server.log` file also indicating a missing postgres configuration file.

This is a log of all the steps I've gone through to diagnose this. https://gist.github.com/geuis/d12634d9a20263686534bdaa6f48f1ea

This is the gist of `brew gist-logs postgresql`. https://gist.github.com/6075d7ccac60268e02ae2faf5794f740

**Comment by tdsmith** [comment]
What's the ownership of /usr/local/var? You may need to change that as well.

**Comment by tdsmith** [comment]
I take it back:
`drwxr-xr-x   9 geuis  admin  306 Jul  3 16:26 .`

What user owns `brew`? Homebrew shouldn't have way to run things as root.

**Comment by geuis** [comment]
@tdsmith hmm how would I check what user it runs under?

**Comment by tdsmith** [comment]
On Sun, Jul 3, 2016 at 5:09 PM, Charles Lawrence
<notifications@github.com> wrote:
>
> @tdsmith hmm how would I check what user it runs under?

`ls -l $(which brew)` should tell you who owns `brew`.

**Comment by geuis** [comment]
@tdsmith yeah, that's it. Show's me as owner.

**Comment by dunn** [comment]
This is a persistent issue; see https://github.com/Homebrew/legacy-homebrew/issues/35240, https://github.com/Homebrew/legacy-homebrew/issues/48558, https://github.com/Homebrew/legacy-homebrew/issues/48766.

**Comment by MikeMcQuaid** [comment]
Figured this out finally and opened a PR in https://github.com/Homebrew/homebrew-core/pull/4478.

**Comment by geuis** [comment]
@MikeMcQuaid that's great news! Thanks for fixing this.

**Comment by MikeMcQuaid** [comment]
@geuis Thanks for the kind words. My pleasure.
