### ISSUE TITLE
misleading error message when multiple simultaneous installs attempted

### ISSUE THREAD

**Issue by rdp** [Homebrew/brew#4458]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Ruby version 2.3.7 is unsupported on 10.13. Homebrew
is developed and tested on Ruby 2.3.3, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.

$ brew config
HOMEBREW_VERSION: 1.6.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1957a9d04f9fd16fc3520cb37b50270c68a109e
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1ba57c1606971fdf724b6bd734ddd6bdcb4404a3
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: N/A

To help us debug your issue please explain:
- What you were trying to do (and why)

Install a package when another homebrew install was already going on.

- What happened (include command output)

$ brew install crystal

# another terminal:
$ brew install mysql@5.7
Error: Operation already in progress for sphinx-doc.formula
Another active Homebrew process is already using sphinx-doc.formula.
Please wait for it to finish or terminate it to continue.

- What you expected to happen

I expected it to fail, but to mention something vaguely related to the packages I was installing, who is this sphinx-doc and why is it in progress? ...

- Step-by-step reproduction instructions (by running `brew` commands)

See above.

**Comment by MikeMcQuaid** [comment]
That package is locked by both formulae. We don’t really support simultaneous installation but will consider PRs to improve the message if you have ideas.

**Comment by MikeMcQuaid** [comment]
Sorry missed a bit: locked by both formulae because they both depend on it.
