### ISSUE TITLE
Erroneous doctor warning re ruby version

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#4459]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [NA] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

I'm on 10.13.6, and when I run `brew doctor` I'm now seeing the following warning:
```
Warning: Ruby version 2.3.7 is unsupported on 10.13. Homebrew
is developed and tested on Ruby 2.3.3, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
```
2.3.7 is the system ruby on 10.13.6, so this shouldn't be shown.

Doctor shows *only* the above warning.
```
$ brew --config

HOMEBREW_VERSION: 1.6.14-4-g4ffc8b1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4ffc8b137bd4d21a92343cc27d509265fe724a7d
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cc5d499e2410ef5f49e30d17c4675e67d4f69a4f
Core tap last commit: 9 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/hb
HOMEBREW_CACHE: /stuff/brache
HOMEBREW_TEMP: /Users/chdiza/.tmp/tmpdir
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/chdiza/Library/Homebrew
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_NO_EMOJI: 1
HOMEBREW_NO_GITHUB_API: 1
HOMEBREW_VERBOSE: 1
CPU: quad-core 64-bit arrandale
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

**Comment by vdobrynin** [comment]
I have same problem Ruby version 2.3.7 is the system ruby on 10.13.6, so this shouldn't be shown.

Warning: Ruby version 2.3.7 is unsupported on 10.13. Homebrew
is developed and tested on Ruby 2.3.3, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.

$ brew --config
HOMEBREW_VERSION: 1.6.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1957a9d04f9fd16fc3520cb37b50270c68a109e
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b41c9959d250f380e736741d5d7ebd51bd46589e
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_121
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1527767617
Xcode: 9.4.1
XQuartz: 2.7.11 => /opt/X11

**Comment by MikeMcQuaid** [comment]
I'm working on it.

**Comment by vdobrynin** [comment]
Thanks.
:)

**Comment by microsby0** [comment]
Still seeing this issue after running `brew update` and `brew doctor`

`
HOMEBREW_VERSION: 1.6.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1957a9d04f9fd16fc3520cb37b50270c68a109e
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a5284b2f0171692029bef7b7632f2f87712816c8
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10, 1.8.0_172, 1.6.0_65-b14-468
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1527767617
Xcode: N/A
XQuartz: N/A
`

**Comment by ilovezfs** [comment]
There's no new tag yet, but it'll be fixed for you once that happens.

**Comment by chdiza** [comment]
Works, thanks :)

I confess I'm not really sure what that doctor check is trying to find.  It looks like it will only yell when the system ruby is either less than the portable ruby or greater than the portable ruby.  In the former case, there's no need for the doctor warning because the appropriate portable ruby gets automatically and immediately poured.  In the latter case, the content of the warning is misleading and makes for bad UX, particularly for brand-new installs.

Unless there is a real risk that someone has manually replaced their system ruby with something newer, I suggest changing the warning message.

**Comment by MikeMcQuaid** [comment]
@chdiza People can (and do) override Homebrew to use a non-system-or-portable Ruby and things go 💥.
