### ISSUE TITLE
postgresql failed to build on 10.13.4

### ISSUE THREAD

**Issue by ynfle** [Homebrew/brew#4475]
https://gist.github.com/c1b5d286e03bce1e09bbc99f6e08e8ab

**Comment by vitorgalvao** [comment]
Issues regarding formulae belong in [Homebrew/brew-core](https://github.com/Homebrew/homebrew-core). Don’t forget to fill the template.

**Comment by ynfle** [comment]
Thx it works fine after updating now!!!

**Comment by MikeMcQuaid** [comment]
@vitorgalvao No apologies needed, thanks!
