### ISSUE TITLE
`brew desc` should also include results from casks

### ISSUE THREAD

**Issue by crowell** [Homebrew/brew#4490]
now that `brew cask search` is deprecated, the suggestion is to use `brew search`

as i've mentioned before, `brew search` is a bit lacking, and `brew desc -s` is preferable.

however, `brew desc -s` doesn't include cask results.

I suggest that including cask results in `brew desc` would be useful

maybe with a syntax for the result like 
`CASK: <name>` to remove confusion

the image shows what the current behavior is

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/616288/42793644-ee9fe944-892f-11e8-8b16-d123178be7a4.png">

**Comment by MikeMcQuaid** [comment]
Casks do not include descriptions so this isn't possible.

**Comment by MikeMcQuaid** [comment]
It’s not impossible but it would be a really large job that people would need to do in a separate tab first (like with brew desc).
