### ISSUE TITLE
The Command Line Tools header package must be installed on Mojave.

### ISSUE THREAD

**Issue by mharris3960** [Homebrew/brew#4491]
Brew config: 
HOMEBREW_VERSION: 1.7.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7e8fb9a0f8ab5e841763ec6c7fefa72a8462b594
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 30f1aa57bbfa69460ffcb1d52d5c8b3bbf74b793
Core tap last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1530455945
CLT headers: N/A
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
Brew install (any package):
The Command Line Tools header package must be installed on Mojave.

**Comment by MikeMcQuaid** [comment]
Yes, it must.

**Comment by mharris3960** [comment]
I have installed it.

**Comment by ilovezfs** [comment]
@mharris3960 

```
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```
