### ISSUE TITLE
brew tap brewsci/science invalid formula error

### ISSUE THREAD

**Issue by santiag95** [Homebrew/brew#4493]
I´ve received an error by trying to tap brewsci/science

`brew tap brewsci/science
Updating Homebrew...
==> Tapping brewsci/science
Cloning into '/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science'...
remote: Counting objects: 468, done.
remote: Compressing objects: 100% (465/465), done.
remote: Total 468 (delta 1), reused 153 (delta 1), pack-reused 0
Receiving objects: 100% (468/468), 429.98 KiB | 1.40 MiB/s, done.
Resolving deltas: 100% (1/1), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/ome-common.rb
uninitialized constant #<Class:0x0000000101615e20>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/ome-files.rb
uninitialized constant #<Class:0x0000000101578210>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/ome-xml.rb
uninitialized constant #<Class:0x00000001014d3c60>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/osgearth.rb
uninitialized constant #<Class:0x00000001028fdf10>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Cannot tap brewsci/science: invalid syntax in tap!`

I already have hombrew up to date.

In case it is needed this is my gcc --version report
`Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by MikeMcQuaid** [comment]
We do not support this tap. Please file the issue with them.

In future please always fill out the issue template.
