### ISSUE TITLE
Ignore --c++11 on OS X ≥ Mavericks?

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/brew#45]
AFAICT --c++11 does nothing but act as an alias for `--build-from-source` on 10.9+; can we safely globally ignore the option on recent OS X? This works around e.g. https://github.com/Homebrew/homebrew-core/issues/133. Cargo-culting the --c++11 option seems pretty common in my anecdotal experience.

cc @mistydemeo for C++ whispering

**Comment by mistydemeo** [comment]
The default C++ stdlib on 10.9+ has C++11 support, but not every package might build its C++11 support if that's an option, at least not without nudging? In the case of boost we're not telling the buildsystem anything, just the compiler, so I suspect you're right they're actually the same thing.

This also influences compiler choice, but for clang it may often not make a difference.

**Comment by mikemcquaid** [comment]
I'd be in favour of doing something smart in our internals which provides a `build.cxx11?` method which always returns `true` on >=10.9 and returns `true` or `false` depending on the option passed on `<10.9`.

**Comment by mikemcquaid** [comment]
Closing this in favour of a future PR.
