### ISSUE TITLE
Error: Cannot tap kyslik/php: invalid syntax in tap!

### ISSUE THREAD

**Issue by georgehao** [Homebrew/brew#4503]
~ brew tap kyslik/php

Updating Homebrew...
==> Tapping kyslik/php
Cloning into '/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php'...
remote: Counting objects: 785, done.
remote: Compressing objects: 100% (314/314), done.
remote: Total 785 (delta 527), reused 550 (delta 464), pack-reused 0
Receiving objects: 100% (785/785), 309.03 KiB | 164.00 KiB/s, done.
Resolving deltas: 100% (527/527), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php72-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php72-trader.rb:18:in `<class:Php72Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php70-mcrypt.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php70-mcrypt.rb:19:in `<class:Php70Mcrypt>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php55-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php55-trader.rb:18:in `<class:Php55Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php71-mcrypt.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php71-mcrypt.rb:19:in `<class:Php71Mcrypt>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php54-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php54-trader.rb:18:in `<class:Php54Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php56-mcrypt.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php56-mcrypt.rb:18:in `<class:Php56Mcrypt>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php53-mcrypt.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php53-mcrypt.rb:19:in `<class:Php53Mcrypt>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php70-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php70-trader.rb:18:in `<class:Php70Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php55-mcrypt.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php55-mcrypt.rb:19:in `<class:Php55Mcrypt>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php71-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php71-trader.rb:18:in `<class:Php71Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php56-trader.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php56-trader.rb:18:in `<class:Php56Trader>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php54-mcrypt.rb
Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php54-mcrypt.rb:19:in `<class:Php54Mcrypt>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap kyslik/php: invalid syntax in tap!

**Comment by MikeMcQuaid** [comment]
> Please report this to the kyslik/php tap!
> Or, even better, submit a PR to fix it!
