### ISSUE TITLE
Analytics opt-out by default or ask rather than auto opt-in

### ISSUE THREAD

**Issue by macmichael01** [Homebrew/brew#4504]
We know that analytic helps to make homebrew better, I get it. However, I don not recommend auto opt-in. Your end users should have a choice. I was very sad to see a message presented to me today stating that I was auto volunteered to send this.

==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics

Yes its anonymous and yes I am Uber paranoid regardless. especially in the time of privacy related concerns, I thinks it very important to ensure that a great tool such as homebrew follows strict guidelines. Therefore, I advise against auto opt-in but rather keeping it as a choice for the end user.

**Comment by MikeMcQuaid** [comment]
Thanks for your input but, as previously discussed, we will be leaving this as-is.
