### ISSUE TITLE
Documentation bug: `brew bottle --merge` help says it take a formula, actually takes a JSON file

### ISSUE THREAD

**Issue by fredemmott** [Homebrew/brew#4519]
```
brew bottle --merge [--keep-old] [--write [--no-commit]] formulae:
    Generate a bottle from a formula and print the new DSL merged into the
    existing formula.

    If --write is passed, write the changes to the formula file. A new
    commit will then be generated unless --no-commit is passed.
```

It doesn't take formulae - it takes a JS file that's the result of `brew bottle [options] --json formula` (`--json` also being undocumented)

**Comment by MikeMcQuaid** [comment]
@fredemmott I'll take a look at this. thanks. As a general comment this stuff is a bit of an implementation detail; I'd strongly advise using `brew test-bot` to build your bottles and we'll accept PRs to help make that more suitable.
