### ISSUE TITLE
jenkins.brew.sh needs the cert updating.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#4553]
_Technically_ speaking this probably isn't the right place to file this, my apologies. Normally I'd ding Mike privately but given it's after midnight in the UK that'd likely not make me _super_ popular.

```
* Server certificate:
*  subject: CN=jenkins.brew.sh
*  start date: Apr 26 23:05:23 2018 GMT
*  expire date: Jul 25 23:05:23 2018 GMT
```

CC @MikeMcQuaid @ilovezfs ❤️.

**Comment by MikeMcQuaid** [comment]
The certificate was automatically renewed but nginx wasn't correctly restarted. Did that and fixed.

**Comment by DomT4** [comment]
Thanks Mike.
