### ISSUE TITLE
`brew bottle --merge --keep-old` broken if root_url specified

### ISSUE THREAD

**Issue by fredemmott** [Homebrew/brew#4554]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae?
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

Skipped some of these the bug is fairly clear from the source of homebrew itself:

To reproduce, build a bottle with a root url including URI scheme, and with `--json`. Then try to use `brew bottle --merge --json`.

This will fail, as the `:` gets removed from the old root url here: https://github.com/Homebrew/brew/blob/b993c7745ef7dba9e874ca0888f177adc7969fb7/Library/Homebrew/dev-cmd/bottle.rb#L450

As can be demonstrated by:

```
irb(main):003:0> '"https://example.com"'.delete ":\""
=> "https//example.com"
```

... and can be verified by inserting `p` statements here: https://github.com/Homebrew/brew/blob/b993c7745ef7dba9e874ca0888f177adc7969fb7/Library/Homebrew/dev-cmd/bottle.rb#L465

`--keep-old` will fail as `https//example.com` !== `https://example.com`

**Comment by MikeMcQuaid** [comment]
Nice fine. Any chance of a PR here?

**Comment by fredemmott** [comment]
I'll start that process; will probably take a few weeks.

**Comment by fredemmott** [comment]
Actually yes, looks like that got approved when I was on vacation :)

**Comment by scpeters** [comment]
I just ran into this issue as well.

**Comment by scpeters** [comment]
I've made an attempt at solving this in https://github.com/scpeters/brew/commit/5d4df3b952a172416bf469f47abf6a1fb24109fe, but now it's inserting double `""` around the old `sha256` values:

~~~
$ brew bottle --merge --write --no-commit ./ignition-math2--2.9.0.mojave.bottle.json --keep-old --verbose --debug
==> osrf/simulation/ignition-math2
  bottle do
    root_url "http://gazebosim.org/distributions/ign-math/releases"
    cellar :any
    sha256 "9b8c15784c4b1c6fa1237d8810576cdba6095d40c073989e2af335328939148d" => :mojave
    sha256 ""2f48914f690352add2d2fce6cd22a260e43ea54a02da386bef4bba1470bf7750"" => :high_sierra
    sha256 ""5e313d779a496c3963d57495723506400fc1d71bf831d3cfff0f9e9d09bb46fc"" => :sierra
    sha256 ""59eb583fb73e998510a3571a794e96b57a49b68ddca4cd03119d748c6d51d655"" => :el_capitan
    sha256 ""401ecbcc6c53af2ba8161790115a0df3cefbe393cafa72358fd92441bccdb633"" => :yosemite
  end
~~~

**Comment by scpeters** [comment]
fixed in https://github.com/scpeters/brew/commit/9f9bb7c03404a136222904cddd6e2384d9029ee3

I'll submit a PR

**Comment by scpeters** [comment]
see #4892
