### ISSUE TITLE
install fail due to pkg-config

### ISSUE THREAD

**Issue by jokerlck** [Homebrew/brew#4556]
https://gist.github.com/jokerlck/e721b7b6561eecd38f64e9cf838d3a0f

`brew update`
Already up to date
`brew doctor`
Warning: An outdated version (1.8.3.1) of Git was detected in your PATH.
Git 1.8.5 or newer is required to perform checkouts over HTTPS from GitHub and
to support the 'git -C <path>' option.
Please upgrade:
  brew install git

But I cannot install git as pkg-config cause error

**Comment by MikeMcQuaid** [comment]
Report this to Linuxbrew.
