### ISSUE TITLE
Base64 installs a version incompatible with BSD or GNU

### ISSUE THREAD

**Issue by rayfoss** [Homebrew/brew#4558]
Please add the gnu version of base64 to brew. The current version is 1.5, which automatically word wraps unlike the built in mac one, and offers no way to disable word wrapping. 

- the motivation for the feature
The base64 included in brew is useful to practically no one, as it's not compatible with mac scripts or linux ones.

**Comment by chdiza** [comment]
Also, the GNU version wraps by default at 76 characters.

**Comment by rayfoss** [comment]
@chdiza yes but you can use `-w0` to disable that, which you can't do on the brew version. Thank you! I was looking for it everywhere... a `brew search` yielded no results... I could have sworn I tried gbase64, my mistake
