### ISSUE TITLE
Please report this bug:     https://git.io/brew-troubleshooting

### ISSUE THREAD

**Issue by elharo** [Homebrew/brew#4560]
Ran brew doctor. It asked me to report this crash bug to a  URL that no longer seems to exist

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

~/tmp$ brew doctor

Error: /usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:72: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:76: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    can add a "gnubin" directory to your PATH from your bashrc like:
                                ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:76: syntax error, unexpected ':', expecting keyword_end
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:78: dynamic constant assignment
        PATH="#{opt_libexec}/gnubin:$PATH"
             ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:80: dynamic constant assignment
    Additionally, you can access their man pag...
                 ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:80: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    Additionally, you can access their man pages with ...
                         ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    the "gnuman" directory to your MANPATH from your bashrc as well:
                          ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: syntax error, unexpected ':', expecting keyword_end
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:83: dynamic constant assignment
        MANPATH="#{opt_libexec}/gnuman:$MANPATH"
                ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formula.rb:1183:in `[]'
/usr/local/Library/Homebrew/diagnostic.rb:1205:in `check_for_non_prefixed_coreutils'
/usr/local/Library/Homebrew/cmd/doctor.rb:34:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `doctor'
/usr/local/Library/brew.rb:84:in `<main>'
~/tmp$

**Comment by MikeMcQuaid** [comment]
> ran brew config and brew doctor and included their output with your issue?

From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
