### ISSUE TITLE
Why not port homebrew to all UNIX-like system ?

### ISSUE THREAD

**Issue by iamybj** [Homebrew/brew#4575]
I find a linuxbrew https://github.com/Linuxbrew, and install it in my xubuntu system.
So, why not make homebrew-core be a all unix-like system package manager? 
We can use subcommand install system separated software. 

brew install xxx
brew install mac/xxx
brew install linux/xxx
brew install bsd/xxx

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

**Comment by iamybj** [comment]
@MikeMcQuaid
fuck you,stupid and naive, white skin pig!
