### ISSUE TITLE
Overcommit forbids installation

### ISSUE THREAD

**Issue by boardfish** [Homebrew/brew#4577]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6a245c05110c240e680da594c2cc6038998b82e
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6412ad0f88e842197e596703aa5914611349cec3
Core tap last commit: 3 weeks ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

Your system is ready to brew.

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to install shfmt so I can autoformat my shell scripts.

- What happened (include command output)

```
└─[$] brew install focusaurus/homebrew-shfmt/shfmt                                                                                          [8:55:19]
This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
Install it with `gem install overcommit`.
This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
Install it with `gem install overcommit`.
The pre-rebase hook refused to rebase.
This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
Install it with `gem install overcommit`.
The pre-rebase hook refused to rebase.
This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
Install it with `gem install overcommit`.
The pre-rebase hook refused to rebase.
This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
Install it with `gem install overcommit`.
The pre-rebase hook refused to rebase.
This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
Install it with `gem install overcommit`.
The pre-rebase hook refused to rebase.
==> Tapping focusaurus/shfmt
Cloning into '/usr/local/Homebrew/Library/Taps/focusaurus/homebrew-shfmt'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
Install it with `gem install overcommit`.
Error: Failure while executing; `git clone https://github.com/focusaurus/homebrew-shfmt /usr/local/Homebrew/Library/Taps/focusaurus/homebrew-shfmt --depth=1` exited with 64.
```

- What you expected to happen

shfmt should've been installed without error.

- Step-by-step reproduction instructions (by running `brew` commands)

Make sure `overcommit` is installed, then `brew install focusaurus/homebrew-shfmt/shfmt`.

**Comment by MikeMcQuaid** [comment]
> focusaurus/homebrew-shfmt

Report this to https://github.com/focusaurus/homebrew-shfmt instead.

**Comment by boardfish** [comment]
The issue seems to be with brew's internal Ruby version and how it deals with Overcommit, on further diagnosis. How can I use a different Ruby version when running `brew install`?

**Comment by MikeMcQuaid** [comment]
You can't, that's not supported.
