### ISSUE TITLE
RPC failed; curl 56 SSLRead()

### ISSUE THREAD

**Issue by tomihasa** [Homebrew/brew#4578]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

System: macOS Sierra 10.12.6. Location: Finland. I installed MacPorts 2.5.3 for macOS Sierra. Immediately after that I decided to install Homebrew, because I am going to install OpenCV and most of the tutorials mention Homebrew, not MacPorts, when installing OpenCV.

At the end of the Homebrew installation I get:

==> Downloading and installing Homebrew...
remote: Counting objects: 106111, done.
error: RPC failed; curl 56 SSLRead() return error -980600 KiB/s   
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force

![screen shot 2018-07-31 at 10 56 30](https://user-images.githubusercontent.com/11370077/43446089-a7ada4cc-94b0-11e8-8ac5-a5196ba22721.png)

**Comment by MikeMcQuaid** [comment]
You're having issues connecting to GitHub. You'll need to figure that out with GitHub.
