### ISSUE TITLE
homebrew Error: stack level too deep

### ISSUE THREAD

**Issue by rwv** [Homebrew/brew#4580]
- [x] are reporting a bug others will be able to reproduce and not asking a question.
- [x] ran a `brew` command and reproduced the problem with multiple formulae?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

****

`brew doctor` and `brew config` output: https://gist.github.com/rwv/7de202f4644f56f9943b9c8942819ddb

To help us debug your issue please explain:
- What you were trying to do (and why)
Nearly all homebrew commands fail expect `brew update` works properly.
- What happened (include command output)
``` bash
$ brew outdated # other commands have the same issue
Error: stack level too deep
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/tap.rb:24:in `any?'
/usr/local/Homebrew/Library/Homebrew/tap.rb:24:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:189:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:209:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:209:in `formula_name_path'
......
```
- What you expected to happen
commands work properly

**Comment by MikeMcQuaid** [comment]
> Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-cask.git

This needs to be homebrew-core.

**Comment by MikeMcQuaid** [comment]
Note we do not support using custom GitHub mirrors. You'll need to figure out any issues you have when using them yourself, sorry.
