### ISSUE TITLE
Unexpected prompt for git credentials

### ISSUE THREAD

**Issue by stevepeak** [Homebrew/brew#4605]
<details>

<summary>Yes, to all checkmarks</summary>

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

</details>

----

Unexpected git login with installing from github:

<img width="668" alt="screen shot 2018-08-05 at 11 47 48" src="https://user-images.githubusercontent.com/2041757/43684711-6478c4c2-98a5-11e8-8f4d-1a3ce7e588a0.png">

> Previously it did not ask for github username/password.

Upon adding proper username/password:

<img width="668" alt="screen shot 2018-08-05 at 11 48 33" src="https://user-images.githubusercontent.com/2041757/43684716-7dfb62a6-98a5-11e8-80a6-bbcea1676ebe.png">

> **This was replicated by a colleague.**
> **I can `git` private repos no problem.**

## Details

```py
$ brew config
HOMEBREW_VERSION: 1.7.1-116-gc2ba0082
ORIGIN: https://github.com/Homebrew/brew
HEAD: c2ba00822dcc9d3e179350af5fb05f0a76cc8833
Last commit: 44 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b4df42959f762ad5f2442901603a445ff3b553cf
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: N/A
XQuartz: N/A

$ brew update
Already up-to-date.

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  asyncy
  docker
  docker-compose
  docker-machine

$ cat ~/.gitconfig
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[user]
	name = Steve Peak
	email = steve@stevepeak.net
```

**Comment by commitay** [comment]
`brew install heroku/brew/heroku`
