### ISSUE TITLE
Problem installing python3

### ISSUE THREAD

**Issue by dufferzafar** [Homebrew/brew#461]
```
> brew install python3                                                                                                                              

==> Downloading https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz
Already downloaded: /Users/dufferzafar/Library/Caches/Homebrew/python3-3.5.2.tar.xz
==> ./configure --prefix=/Users/dufferzafar/.apps/brew/Cellar/python3/3.5.2 --enable-ipv6 --datarootdir=/Users/dufferzafar/.apps/brew/Cellar/python3/3.5.2/share --datadir=/Users/dufferzafar/.apps/brew/Cella
==> make
==> make install PYTHONAPPSDIR=/Users/dufferzafar/.apps/brew/Cellar/python3/3.5.2
==> make frameworkinstallextras PYTHONAPPSDIR=/Users/dufferzafar/.apps/brew/Cellar/python3/3.5.2/share/python3
Error: No such file or directory - (/Users/dufferzafar/.apps/brew/Cellar/python3/3.5.2/IDLE.app, /Users/dufferzafar/ 3.apps/brew/Cellar/python3/3.5.2/IDLE.app)
```

I've installed `brew` in my home folder. Is that the cause of the problem? 

I also tried commenting out the `make frameworkinstallextras` line from the formula, but then the same error came on the `make install` line.

**Comment by dufferzafar** [comment]
I'm new to ruby. What line can I add to the formula so that the process just stops there? 

This will help me debug the problem better.

**Comment by dufferzafar** [comment]
Just for completeness. 

I ended up installing Python 3 via [pyenv](https://github.com/yyuu/pyenv).

```
brew install pyenv
pyenv install 3.5.2
```

**Comment by UniqMartin** [comment]
Sorry, but you have not followed the requested steps in our [Troubleshooting Guide](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting). Please follow (all of) these steps, particularly the one that asks you to post the output of `brew gist-logs python 3`, and post the information here so we can try to help you with your problem. Thanks!

> I ended up installing Python 3 via pyenv.

That's probably not what you originally wanted, but feel free to close the issue if you're happy with that and not interested in debugging this further.

**Comment by tdsmith** [comment]
Heh; oops. The `python3` formula does string matching against `.app`, which is tripping on `~/.apps`. This is our bug.

**Comment by UniqMartin** [comment]
@dufferzafar Should be fixed by the change in Homebrew/homebrew-core@d14d435bdeb56d9f9f3bf8d59198d58447395a98, if you want to give it another try. (Make sure to run `brew update` first.)

**Comment by dufferzafar** [comment]
@UniqMartin Thanks for this. I'll test it out!
