### ISSUE TITLE
better support for pre-release versions in formula class names

### ISSUE THREAD

**Issue by eedwards-sk** [Homebrew/brew#4615]
Currently if you're using semantic versioning (semver.org) and you promote to a pre-release (e.g. an rc) you get something like this:

`1.0.0-rc.1`

If I'm making formulas for specific versions, then I'll have a class name of `MyPackageATX.Y.Z` which corresponds to `my-package@x.y.z` with the dashes removed and each 'word' capitalized.

This is not too difficult to deal with when going from a known package name (e.g. `my-package`) as you can simply hard code `MyPackage` into the class name.

However, for versions, this is much more difficult.

e.g. when generating the formula name, I already have to strip any dots or dashes from the version to make it compatible with the class name (e.g. `-rc.1` becomes `rc1`)

However, homebrew expects that the version is also capitalized for each `-` separated segment.

e.g. if your version is `1.0.0-rc.1-eedwards-1234` then it would expect `MyPackageAT100Rc1Eedwards1234`

(or in the case of my actual repro, I received: `Expected to find class BashUtil00AT000Rc1, but only found: BashUtil00AT000rc1`)

As you can imagine, parsing the version to capitalize it just to match what homebrew expects is a lot of extra work and prone to breakage.

So this is a request to instead support a lower-cased class name after the `AT` or to not mangle the capitalization of the class name's version segment at all, and allow it to pass through as-is.

**Comment by eedwards-sk** [comment]
I believe the code responsible for this is in `Library/Homebrew/formulary.rb`:

lines 54-60

```
  def self.class_s(name)
    class_name = name.capitalize
    class_name.gsub!(/[-_.\s]([a-zA-Z0-9])/) { Regexp.last_match(1).upcase }
    class_name.tr!("+", "x")
    class_name.sub!(/(.)@(\d)/, "\\1AT\\2")
    class_name
  end
```

**Comment by eedwards-sk** [comment]
The first line (`name.capitalize`) just upper cases the first name part (so `foo-bar@1.0.0-rc.1` to `Foo-bar@1.0.0-rc.1`)

The next line `.upcase` is what is upper casing the version:

`class_name.gsub!(/[-_.\s]([a-zA-Z0-9])/) { Regexp.last_match(1).upcase }`

If I remove the `.upcase` it will leave just the first part capitalized:

```
'my-project-0.0@0.0.0-rc.1'.capitalize.gsub!(/[-_.\s]([a-zA-Z0-9])/) { Regexp.last_match(1) }
=> "Myproject00@000rc1"
```

**Comment by MikeMcQuaid** [comment]
We'll welcome a PR to improve this but given we don't officially support or recommend creating versioned formulae on specific, prerelease versions this isn't something we'll be working on. Thanks!

**Comment by eedwards-sk** [comment]
@MikeMcQuaid 

Thanks for the response, Mike!

I found a workaround which was to leverage the pre-existing ruby code to create the expected class name before generating the formula

Here's a bash script for posterity:

```bash
_convert_formula_name_to_ruby_class_name() {
  # 1) formula name

  ruby_script=$(cat <<EOL
name = '${1}'
class_name = name.capitalize
class_name.gsub!(/[-_.\\s]([a-zA-Z0-9])/) { Regexp.last_match(1).upcase }
class_name.tr!("+", "x")
class_name.sub!(/(.)@(\\d)/, "\\\\1AT\\\\2")
puts class_name
EOL
)

  "${ruby_exe}" -e "${ruby_script}"
}
```

**Comment by RandomDSdevel** [comment]
@eedwards-sk:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Well, the internal implementation details of `Formulary.class_s()` could always change without notice in the future, so I'm not sure you should rely on them.  You could always call that member function inside of `brew irb`, though.  I admit that it would be nice if there were an easy way to script this, however.
