### ISSUE TITLE
Cache migration to `--` format is broken.

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#4624]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

The migration of tarballs in the cache to the double-dash form is broken.  Instead of migrating a previously-existing tarball, a brand-new one is created and the old one is still there.

For instance, the tarball `markdown-1.0.1.zip` is already in my cache because `markdown` is already installed.  Then I uninstall `markdown`, and then do `brew install markdown`.  Instead of the old tarball being renamed as `markdown--1.0.1.zip`, I now have two markdown tarballs: one called `markdown-1.0.1.zip` and the other called `markdown--1.0.1.zip`.

(I confess I can't see what purpose this double-dash stuff is serving anyway.)

```
$ brew config
HOMEBREW_VERSION: 1.7.1-154-g9f370a3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9f370a35767f9af94ab2c519770754421a82bcd6
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 919c57196e6964ad8370e2d84c96db644c4b9512
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/hb
HOMEBREW_CACHE: /stuff/brache
HOMEBREW_TEMP: /Users/chdiza/.tmp/tmpdir
HOMEBREW_BUILD_FROM_SOURCE: 1
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/chdiza/Library/Homebrew
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_NO_EMOJI: 1
HOMEBREW_NO_GITHUB_API: 1
HOMEBREW_VERBOSE: 1
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

The Doctor only complains about HOMEBREW_VERBOSE being set, but I checked and that doesn't affect the reported behavior.

**Comment by reitermarkus** [comment]
I cannot reproduce this, did you run `brew update`?

If I put `markdown-1.0.1.zip` in my cache and run `brew update`, it renames it to `markdown--1.0.1.zip` as expected.

**Comment by chdiza** [comment]
> did you run brew update?

Yes.

Maybe it makes a difference that I have `HOMEBREW_CACHE` set?

**Comment by chdiza** [comment]
I ran `update` again just now and still it doesn't work.

**Comment by chdiza** [comment]
I can reproduce this on multiple machines.

**Comment by chdiza** [comment]
Another interesting fact about this: neither `brew cleanup -n` nor `brew cleanup -ns` will list the old tarball names as ready for cleanup.

**Comment by chdiza** [comment]
> If I put markdown-1.0.1.zip in my cache and run brew update

I am not running `brew update`.  I am running `brew install` after a `brew remove`.

**Comment by chdiza** [comment]
I meant to say, in my edit, that I *did* run `brew update`.  Then a `remove` followed by an `install` fails to rename the tarballs in the cache.

**Comment by reitermarkus** [comment]
Try `brew update --force`.

**Comment by chdiza** [comment]
`brew update --force` did work.  Seems like one shouldn't have to do that.  (Despite having `HOMEBREW_DEVELOPER` unset, my brew repo is still updated "between" the tags.  I think this has something to do with "having run a developer cmd at one point".)

BTW, though this worked, there was no message to the terminal telling me what was going on while the cache was migrated.  It kind of took a long time and it made it look like brew had hung.  Maybe a "Migrating cache..." message would be helpful.

**Comment by reitermarkus** [comment]
> Seems like one shouldn't have to do that.

You won't, once a new tag is released, which will force a full update in any case.

> Maybe a "Migrating cache..." message would be helpful.

Will add a message.

**Comment by chdiza** [comment]
> You won't, once a new tag is released

I did have to, though.  That's why this issue exists.

**Comment by chdiza** [comment]
> This has to do with "having run a developer cmd at one point", which switched you to the master branch.

Right.  And then I had to force, which neither I nor anyone else who ran a developer cmd at some point should have had to do.

**Comment by reitermarkus** [comment]
> which neither I nor anyone else who ran a developer cmd at some point should have had to do

Anyways, this is a separate issue.
