### ISSUE TITLE
brew reinstall inconsistent with passed in formula options

### ISSUE THREAD

**Issue by chrmoritz** [Homebrew/brew#4636]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

I've found this while trying to debug https://github.com/Homebrew/homebrew-core/issues/30614.

<details>
<summary>Old bug report, with the assumption that the intended behavior of brew reinstall is to use the existing install options and completly ignore the passed in formula options.</summary>

#### Issue description

According to the manpage `brew reinstall` should 

> Uninstall and then install formula **(with existing install options)**.

and should not honor passed in formula options (e.g. `--without-dependency`) unlike `brew install`.
But it looks like that this is only partly the case (they are ignored in some cases but taken into account in other cases) leading to a few inconsistencies. After a `brew upgrade` of that formula they are completely taken into account for said formula, which is the opposite of what is documented.

#### Reproduction:

0. `brew uninstall yarn node` if needed first
1. `brew install yarn` (installing `node` and `yarn`)
2. `cat $(brew --prefix yarn)/INSTALL_RECEIPT.json` will include (unimportant properties omitted): `used_options":[],"unused_options":["--without-node"],"runtime_dependencies":[{"full_name":"node","version":"10.8.0"}]` with `--without-node` correctly tagged as a `unused_options` and `node` correctly tagged as a `runtime_dependencies`
3. now run `brew reinstall yarn --without-node`
    * **Actual behavior**: `cat $(brew --prefix yarn)/INSTALL_RECEIPT.json` will include `"used_options":["--without-node"],"unused_options":[],"runtime_dependencies":[{"full_name":"node","version":"10.8.0"}]` On the one hand `node` is still a `runtime_dependencies` dependency and the passed in formula option (`--without-node`) is ignored and the existing install options are used instead as documented. But on the other hand `--without-node` is tagged as a `used_options` (it honors the passed in formula option here), while it should still be tagged as `unused_options` (the existing install options behavior as documented). This is quite inconsistent.
    * **Expected behavior** (as documented): Have `node` tagged as a `runtime_dependencies` and `--without-node` as a `unused_options` option = reinstall follows existing install options completely.
4. `brew upgrade yarn` to a new version (adding a fake `revision` to the formula is enough for the reproduction) and run `cat $(brew --prefix yarn)/INSTALL_RECEIPT.json`:
    * **Actual behavior** `"used_options":["--without-node"],"unused_options":[],"runtime_dependencies":[]` Now we completely respect the `--without-node` formula option passed to `brew reinstall`, which should have been ignored following the documentation.
    * **Expected behavior** (as documented): `used_options":[],"unused_options":["--without-node"],"runtime_dependencies":[{"full_name":"node","version":"10.8.0"}]` (the same as the expected behavior of 3.)

#### Possible fix
`brew reinstall` should set `used_options` and `unused_options` according to the existing install options and not the the one which are passed to `brew reinstall`. All passed in formula options should be ignored as documented.

#### Alternative fix
Reading the code at https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/reinstall.rb#L36-L39 I think the intended behavior might be to merge the newly passed in formula options with the existing ones (which is to be honest what I've expected before checking the man page). If that's the case it should be documented more clearly in the man page and we still have kind of the opposite bug: `node` shouldn't be a `runtime_dependencies` already after the `brew reinstall yarn --without-node` in step 3 anymore.

**Note:** The issue can also be reproduced by replacing `brew reinstall yarn --without-node` with `brew upgrade yarn --without-node` in step 3 too.

Can someone please confirm if it is intended that `brew reinstall <formula>` and `brew upgrade <formula>`  accept formula options and a supposed the merge them with the previously used ones (unlike documented in the manpage)?
</details>

#### Issue description

According to the desired behavior described in https://github.com/Homebrew/brew/issues/4636#issuecomment-411760848 `brew reinstall` (and `upgrade`) should merge the newly passed in formula options (to said commands) with the already existing install options (previously used for these formulas), You can also see this behavior implemented in code here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/reinstall.rb#L36-L39.

But it looks like that these newly passed in formula options are only honored in half the cases leading to some inconsistencies. More precisely the `(un)used_options` part of `INSTALL_RECEIPT.json` is on the one hand taken these into account, while on the other hand the code which calculates the `runtime_dependencies` is still ignoring them and is using the `runtime_dependencies` from the previous installation. Using `--without-dependency` with `brew reinstall` has no effect on the newly calculated `runtime_dependencies` for example. This can lead to incorrect `brew missing` output.

#### Reproduction:

0. `brew uninstall yarn node` if needed first
1. `brew install yarn` (installing `node` and `yarn`)
2. `cat $(brew --prefix yarn)/INSTALL_RECEIPT.json` will include (unimportant properties omitted): `used_options":[],"unused_options":["--without-node"],"runtime_dependencies":[{"full_name":"node","version":"10.8.0"}]` with `--without-node` correctly tagged as a `unused_options` and `node` correctly tagged as a `runtime_dependencies`
3. now run `brew reinstall yarn --without-node` (or `brew upgrade yarn --without-node`)
    * **Actual behavior**: `cat $(brew --prefix yarn)/INSTALL_RECEIPT.json` will include `"used_options":["--without-node"],"unused_options":[],"runtime_dependencies":[{"full_name":"node","version":"10.8.0"}]` On the one hand `--without-node` is correctly tagged as a `used_options` (the passed in option has overriden the old one). But on the other hand `node` is still incorrectly tagged as a `runtime_dependencies` (the passed in formula option is ignored here). This is quite inconsistent.
    * **Expected behavior**: `node` shouldn't be tagged as a `runtime_dependencies` here = reinstall correctly merged the newly passed in formula options with the exiting ones to calculate the runtime dependencies.
4. `brew upgrade yarn` to a new version (adding a fake `revision` to the formula is enough for the reproduction) and run `cat $(brew --prefix yarn)/INSTALL_RECEIPT.json`:
    *  `"used_options":["--without-node"],"unused_options":[],"runtime_dependencies":[]` Now the problem has fixed itself, because upgrade just looks at the `used_options`, which already correctly includes `--without-node` and then correctly calculates the `runtime_dependencies` on it's own.

#### Possible fix
Reading the code at https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/reinstall.rb#L36-L39 I think the intended behavior might be to merge the newly passed in formula options with the existing ones (which is to be honest what I've expected before checking the man page). If that's the case it should be documented more clearly. Also `node` shouldn't be a `runtime_dependencies` already after the `brew reinstall yarn --without-node` in step 3 anymore, which causes incorrectly `brew missing` output for example, which could possible the cause for https://github.com/Homebrew/homebrew-core/issues/30614.

Note: Same issue happens also with `brew upgrade yarn --without-node`.

#### brew doctor and config
```
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 1.7.1-170-gf565646
ORIGIN: https://github.com/Homebrew/brew
HEAD: f5656463dd0e3ff1d4f40248e6833fe41ae7ca6d
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 258820d458b0bc6dace635474a55b89cec25d282
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

**Comment by MikeMcQuaid** [comment]
> Can someone please confirm if it is intended that brew reinstall <formula> and brew upgrade <formula> accept formula options and a supposed the merge them with the previously used ones (unlike documented in the manpage)?

Yeh, I think this would be the ideal behaviour. At this point: who knows what's intended 😆

**Comment by chrmoritz** [comment]
> Yeh, I think this would be the ideal behaviour. At this point: who knows what's intended 😆

So than this bug report should be about having `node` still as a `brew reinstall yarn --without-node`  in step 3 after `brew reinstall yarn --without-node`, which is incorrect and about updating the man page to document the formula option merging for `reinstall` more clearly.
