### ISSUE TITLE
bump-formula-pr fails with key not found: "clone_url"

### ISSUE THREAD

**Issue by alexanderharm** [Homebrew/brew#4641]
- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

Using the `bump-formula-pr` command trying to update `s-nail` formula fails with

```
brew bump-formula-pr --strict --url=http://www.sdaoden.eu/downloads/s-nail-14.9.11.tar.gz --sha256=279202687409b8e7b4f267e178aed1bd4c68b79c01c10b80f07197f2f73d6695 s-nail
Already up-to-date.
==> replace /^  revision \d+\n(\n(  head "))?/m with "\\2"
==> replace /https:\/\/www\.sdaoden\.eu\/downloads\/s\-nail\-14\.9\.10\.tar\.gz/ with "http://www.sdaoden.eu/downloads/s-nail-14.9.11.tar.gz"
==> replace "87ade7bbeb110250afce8221b2bb553a3d9661327dfca3f622994fb017c49ccb" with "279202687409b8e7b4f267e178aed1bd4c68b79c01c10b80f07197f2f73d6695"
Error: key not found: "clone_url"
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:288:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:288:in `block in bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:271:in `block in cd'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:271:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:271:in `cd'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:264:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

Below the output of `brew doctor` and `brew config`:

```
HOMEBREW_VERSION: 1.7.1-195-g232de9d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 232de9d9dabd3b8a1939eb40e863d7cfde338057
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3d2420e8afc4ec5a5456c96eb4b47d8ed769bd4d
Core tap last commit: 68 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

```
Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

**Comment by mistydemeo** [comment]
Are you able to repro this when you retry? If so, could you add `puts response` above line 288 in `/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb` and then show what the response is? It looks like you received an API response from GitHub, but it was missing the `clone_url` parameter.

**Comment by alexanderharm** [comment]
Thanks for your reply, which pointed me into the right direction. Apparently hub fails to access the password in the macos keychain when run from su-shell.

**Comment by Zialus** [comment]
I'm having the same problem.

This is the status of the the response variable when I add `puts response` :

`{"message"=>"You must be logged in to do that.", "documentation_url"=>"https://developer.github.com/v3/#authentication"}`

I'm not running the shell su mode, btw.

**Comment by GauthamGoli** [comment]
@alexanderharm  Just a note. `bump-formula-pr` doesn't use `hub` anymore. It uses GH API. 

@Zialus: Thanks for posting the response. I'll take a look at this later today.

**Comment by Zialus** [comment]
I ran `git -C "$(brew --repo homebrew/core)" reset --hard`, as described in https://github.com/Homebrew/homebrew-core/issues/30828, but it didn't make a difference.

**Comment by DomT4** [comment]
FWIW I get the same `key not found: "clone_url"` error and this is the response:
```
{"message"=>"Not Found", "documentation_url"=>"https://developer.github.com/v3/repos/forks/#create-a-fork"}
Error: key not found: "clone_url"
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:289:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:289:in `block in bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:278:in `block in cd'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:278:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:278:in `cd'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:264:in `bump_formula_pr'
```

**Comment by deniogun** [comment]
In my case I was hitting API rate limits. I got around this by generating a personal access token and setting the following environment variable:

`export HOMEBREW_GITHUB_API_TOKEN=`

**Comment by GauthamGoli** [comment]
@deniogun Was an error message shown saying that you were exceeding the rate limits? or was it `Error: key not found: "clone_url"`  ?

**Comment by deniogun** [comment]
It was masked under the error message _key not found_. Printing the response showed that it was API rate limiting

{"message"=>"API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url"=>"https://developer.github.com/v3/#rate-limiting"}
Error: key not found: "clone_url"
