### ISSUE TITLE
command line tools are already installed, use "Software Update" to install updates

### ISSUE THREAD

**Issue by 751811032** [Homebrew/brew#465]
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
Failed during: /usr/bin/sudo /usr/bin/xcode-select --install

how can I solve it

**Comment by MikeMcQuaid** [comment]
Run "Software Update".

**Comment by MikeMcQuaid** [comment]
Where are you seeing this error?

**Comment by 751811032** [comment]
thank you
have been solved,because I have two versions Xcode

**Comment by abhinavmandloi** [comment]
Software Update
-bash: Software: command not found

how can I solve it???
