### ISSUE TITLE
Latest `cleanup` is broken

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#4650]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

Sometime within the last 24 hours, `cleanup -n` is now (a) listing stuff twice, and (b) listing stuff that (i) it didn't use to list and (ii) should not be cleaned up.

For instance, in the output below you can see the duplication.  Also,  every single thing listed there is both installed and current.  (Some of it is from my own custom tap but e.g., `jpeg` is not.

```
$ brew cleanup -n
Would remove: /stuff/brache/browser--7 (419B)
Would remove: /stuff/brache/jpeg--9c.high_sierra.bottle.tar.gz (297.6KB)
Would remove: /stuff/brache/jpeg--9c.tar.gz (1004.1KB)
Would remove: /stuff/brache/jq--1.5.d2.tar.xz (3.6MB)
Would remove: /stuff/brache/lynx--2.8.9rel1.tar.xz (3.5MB)
Would remove: /stuff/brache/screenresolution--1.6i.txz (34KB)
Would remove: /stuff/brache/browser--7 (419B)
Would remove: /stuff/brache/jpeg--9c.high_sierra.bottle.tar.gz (297.6KB)
Would remove: /stuff/brache/jpeg--9c.tar.gz (1004.1KB)
Would remove: /stuff/brache/jq--1.5.d2.tar.xz (3.6MB)
Would remove: /stuff/brache/lynx--2.8.9rel1.tar.xz (3.5MB)
Would remove: /stuff/brache/screenresolution--1.6i.txz (34KB)
```

None of that was listed yesterday.

```
$ brew config
HOMEBREW_VERSION: 1.7.1-204-g8e703e3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8e703e30ba53f8089686b0fc90f87803b4fd5d90
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b450b805d3fe4ca94310b31e2583c1a497cf7fa8
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/hb
HOMEBREW_CACHE: /stuff/brache
HOMEBREW_TEMP: /Users/chdiza/.tmp/tmpdir
HOMEBREW_BUILD_FROM_SOURCE: 1
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/chdiza/Library/Homebrew
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_NO_EMOJI: 1
HOMEBREW_NO_GITHUB_API: 1
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

```
$ brew doctor
Your system is ready to brew.
```

**Comment by chdiza** [comment]
The bad commit is 78658e430259bc030389668d6f
```
Author: Markus Reiter <me@reitermark.us>
Date:   Wed Aug 8 22:23:55 2018 +0200

    Add cask cleanup and per-formula cache cleanup.
```

**Comment by chdiza** [comment]
Evidently some new regex is messed up.

**Comment by nwhitmont** [comment]
Is this why I'm getting error when I run update?

`Error: Unknown command: clean`

**Comment by reitermarkus** [comment]
@nwhitmont, please open a separate issue for that.
