### ISSUE TITLE
Formula-Cookbook does not contain all available download strategies

### ISSUE THREAD

**Issue by starthal** [Homebrew/brew#4655]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Documentation does not correctly represent the available download strategies. Also, it does not explain that download strategies can be used for bottle downloads (from #3966).

- What happened (include command output)

From (https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md):

Download strategies offered by Homebrew are:

| `:using` value | download strategy             |
|----------------|-------------------------------|
| `:bzr`         | `BazaarDownloadStrategy`      |
| `:curl`        | `CurlDownloadStrategy`        |
| `:cvs`         | `CVSDownloadStrategy`         |
| `:git`         | `GitDownloadStrategy`         |
| `:hg`          | `MercurialDownloadStrategy`   |
| `:nounzip`     | `NoUnzipCurlDownloadStrategy` |
| `:post`        | `CurlPostDownloadStrategy`    |
| `:svn`         | `SubversionDownloadStrategy`  |

- What you expected to happen
The actual strategies from (https://github.com/Homebrew/brew/blob/master/Library/Homebrew/download_strategy.rb):

```ruby
    when :hg                     then MercurialDownloadStrategy
    when :nounzip                then NoUnzipCurlDownloadStrategy
    when :git                    then GitDownloadStrategy
    when :github_private_repo    then GitHubPrivateRepositoryDownloadStrategy
    when :github_private_release then GitHubPrivateRepositoryReleaseDownloadStrategy
    when :bzr                    then BazaarDownloadStrategy
    when :s3                     then S3DownloadStrategy
    when :scp                    then ScpDownloadStrategy
    when :svn                    then SubversionDownloadStrategy
    when :curl                   then CurlDownloadStrategy
    when :cvs                    then CVSDownloadStrategy
    when :post                   then CurlPostDownloadStrategy
    when :fossil                 then FossilDownloadStrategy
```
- Step-by-step reproduction instructions (by running `brew` commands)
N/A

**Comment by MikeMcQuaid** [comment]
The Formula Cookbook is not and is not intended to be a comprehensive document. If you would like to add some additional values we'll happily accept a pull request, thanks.

**Comment by starthal** [comment]
Thanks, this makes sense. It was just the only documentation I could find on the download strategies without searching the source. I guess tracking down [this](https://www.rubydoc.info/github/Homebrew/brew/master/AbstractDownloadStrategy) would have worked as well. Please consider editing `Download strategies offered by Homebrew are:` to clarify it's not comprehensive.
