### ISSUE TITLE
Feature: Record Usage Stats on Packages

### ISSUE THREAD

**Issue by kidcosmic** [Homebrew/brew#4657]
The motivation:

In a world where our package needs are fulfilled with a single line in terminal, one can and may install every package under the sun. This is good, until we hit that upgrade line and our faces contort into an unusual shape as homebrew goes on the journey of upgrading all the brews even for the packages you don't need anymore.

The solution:

Have homebrew wrap bundled execs with simple usage recording. Provide a command like `brew usage` that'll list all packages by they're last used dates and they're usage counts. All users are now at easy with cleaning out their brew closets.

Thoughts?

**Comment by MikeMcQuaid** [comment]
We record usage stats and display them here: https://formulae.brew.sh/analytics/

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I think @kidcosmic means he wants the availability of a local display of user analytics per formula per Homebrew installation, not just the global display of aggregate user analytics.  So, like this (as a hypothetical invocation scenario:)  

```
⋮
…$ brew usage
# For each installed formula:  
"$FORMULA" last installed on "$DATE".  Total # of installation events:  "$NUMBER_OF_INSTALL_EVENTS".  
# Or:  
## "$FORMULA":  
##   - Last installed on:  "$DATE".  
##   - Total # of installation events:  "$NUMBER_OF_INSTALL_EVENTS".  
# (End loop.)  
…$ brew usage "$FORMULA"
"$FORMULA" last installed on "$DATE".  Total # of installation events:  "$NUMBER_OF_INSTALL_EVENTS".  
# Or:  
## "$FORMULA":  
##   - Last installed on:  "$DATE".  
##   - Total # of installation events:  "$NUMBER_OF_INSTALL_EVENTS".  
# Only print statistics for the specified formula(s.)  
⋮
```

'`usage`' might not be the best name, though, as I know of other command-line programs that alias a `usage` sub-command to repeat whatever their `help` sub-command and/or `--help` option prints, and, IIRC, I believe 'Usage:  …' is a string commonly used to prefix the kinds of messaging provided by those latter sorts of invokable behaviors.  

---

@kidcosmic:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I thought Homebrew might already store this information internally, at least transiently, as part of collecting it for uploading to the analytics server.  In that case, you would be able to extract it (while its still around) by writing a script or [external command](https://docs.brew.sh/External-Commands).  Upon further investigation, however, I don't see `install`/`install_on_request` events, etc., recorded in formula package installation receipts.

**Comment by kidcosmic** [comment]
@MikeMcQuaid indeed, @RandomDSdevel has the right idea. Personal usage statistics to help use clean out our brew closets. I've got at least 60+ brews installed and a grip of them are libs for x thing, so being able to actually clean this out sensible, gets difficult pretty quickly. On top of that, recording and displaying personal usage statistics is pretty trivial to implement while enabling people to keep their installed brews pristine.

@RandomDSdevel I do think this could be an option on `brew list` like `brew list --stats` or can bring it top level as `brew stats`

**Comment by MikeMcQuaid** [comment]
> recording and displaying personal usage statistics is pretty trivial to implement

No it isn't.
