### ISSUE TITLE
brew doctor fails on check_for_beta_xquartz

### ISSUE THREAD

**Issue by twoseat** [Homebrew/brew#466]
Running `brew doctor` gives the error shown in this gist: https://gist.github.com/twoseat/cf451a68a944190afb97bdcf87b22f74

This is running under ruby 2.3.1, though the same happens under 2.2.1

Xcode command line tools are installed, Xcode is not.

Other operations (e.g. `upgrade`, `update`) appear to work correctly.

**Comment by xrigau** [comment]
I'm in the same situation as @twoseat 
https://gist.github.com/xrigau/06a68b3dee3c659653238db5520a769c

**Comment by MikeMcQuaid** [comment]
Fixed in cc01d3f59aedfa6acefc82660e52d615f3165df5.

**Comment by xrigau** [comment]
Can confirm this is fixed now.
Thanks! 💯
