### ISSUE TITLE
GSoC Summary: Improve Cask Integration

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/brew#4661]
This is a summary of the work done for my Google Summer of Code project “Improving Cask Integration”: https://summerofcode.withgoogle.com/projects/#5834734450507776

### Migrating Taps from [Caskroom](https://github.com/Caskroom) to [Homebrew](https://github.com/Homebrew)

The first sub-project was to migrate all cask taps from the Caskroom organization into the Homebrew organization, which required renaming them on GitHub and writing migration code for renaming locally installed taps. The tracking issue can be found here: https://github.com/Homebrew/brew/issues/4193

### Merging `brew search` and `brew cask search`

The second sub-project was to merge `brew cask search` into `brew search`, so that both casks and formulae can be found with a single command. Casks are now also searchable by name with `brew search --desc`, `brew cask search` has been deprecated. The tracking issue can be found here: https://github.com/Homebrew/brew/issues/4254

### Merging Cask and Formula Download Strategies

The third sub-project was to merge the download strategies used by `brew cask` and the default ones. Despite the cask download strategies originally being forked from the default ones, these had diverged considerably over the years. The tracking issue can be found here: https://github.com/Homebrew/brew/issues/4401

### Merging `brew cleanup` and `brew cask cleanup`

In the same vein as merging `brew search` and `brew cask search`, the fourth and final sub-project was to merge `brew cleanup` and `brew cask cleanup`. With the download strategies merged, adjusting the cleanup logic was quite easy in comparison. `brew cleanup` will now clean up both formulae and casks. The tracking issue can be found here: https://github.com/Homebrew/brew/issues/4660

---

Thank you for mentoring me, @JCount and @MikeMcQuaid!

**Comment by iMichka** [comment]
Nice work! I just followed a little bit the download strategies refactoring, and it looked like it was a lot of work. Necessary work which really improves the code. Thanks!

**Comment by MikeMcQuaid** [comment]
👏. Closing as this is a write-up.
