### ISSUE TITLE
Installing suggest

### ISSUE THREAD

**Issue by microdesign** [Homebrew/brew#467]
### Bug reports:

$ brew install gzip

Output:
Error: No available formula with the name "gzip" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
homebrew/dupes/gzip
**To install it, run:
  brew install homebrew/dupes/gzip**

$brew install homebrew/dupes/gzip

Output:
Error: No available formula with the name "homebrew/x11/gzip" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

**Comment by UniqMartin** [comment]
Why do you want to install `gzip`? It comes pre-installed with OS X and usually doesn't need to be installed separately.

On your transcript: Are you sure you've invoked `brew install homebrew/dupes/gzip` and that is indeed the invocation that caused the `Error: No available formula with the name "homebrew/x11/gzip"` output? This doesn't really make sense and I was unable to confirm this locally. When I run `brew install homebrew/dupes/gzip` the `homebrew/dupes` tap gets installed and then the installation of `gzip` starts. Can you please provide the output of `brew config`, `brew doctor`, and `brew tap-info --installed`?

**Comment by ilovezfs** [comment]
@UniqMartin Isn't this just another unwelcome incarnation of this gem: https://github.com/Homebrew/brew/issues/415

**Comment by UniqMartin** [comment]
@ilovezfs I can't rule it out completely, but it seems to be unlikely. The weird metamorphosis of the input (on the second `brew install` invocation) already happens before the search is kicked off. And `gzip` indeed lives in the `homebrew/dupes` tap. But if you can reproduce this or you have more clues, I'm happy to take a closer look.

Closing this as we haven't heard back from the original issue author in quite a while, but I'm happy to reopen once there's new information and the issue remains unsolved.
