### ISSUE TITLE
Alias `brew update <arg>` to `brew upgrade <arg>`

### ISSUE THREAD

**Issue by mhartl** [Homebrew/brew#4672]
Huge fan of Homebrew here. One tiny bit of friction I've run into is this: I have difficulty remembering whether to use `update` or `upgrade` to update packages, and probably 3/4 of the time I guess wrong and get a message like this:

```
$ brew update pandoc
Error: This command updates brew itself, and does not take formula names.
Use 'brew upgrade pandoc' instead.
```

Since, per the error message, Homebrew obviously knows what I want to do, a possible fix would be to alias `brew update <arg>` to `brew upgrade <arg>`. AFAICT this wouldn't create any conflicts with existing uses of `brew update` (though I could be wrong about that).

**Comment by MikeMcQuaid** [comment]
Thanks for the suggestion but we'll pass for now. In future please always fill out the issue template.
