### ISSUE TITLE
Unable to search for formulas

### ISSUE THREAD

**Issue by virajchitnis** [Homebrew/brew#4681]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to search for formulas.
- What happened (include command output)
```
# brew search <any formula name>
Error: execution expired
```
- What you expected to happen
View a list of formulas that match the search criteria, if any match
- Step-by-step reproduction instructions (by running `brew` commands)
I am not sure if this is particular to my Mac or not. Up until yesterday, I was able to search for and install formulas as expected. I have been facing this issue since updating homebrew via `brew update` yesterday. 

- Additional info: 
```
# brew config
HOMEBREW_VERSION: 1.7.1-224-ga985f0a
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a985f0a5d0cd7e73ea6cafe842a08aba82cee4b5
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 80c925623934231f7c924467114cc9f09b13e024
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_25
macOS: 10.13.6-x86_64
CLT: N/A
Xcode: 9.4.1
XQuartz: 2.7.11 => /opt/X11
```

```
# brew doctor
Your system is ready to brew.
```

**Comment by MikeMcQuaid** [comment]
Can you rerun with `brew search --debug`?

**Comment by MikeMcQuaid** [comment]
@virajchitnis It's OK, it's not a Homebrew bug in that case.

**Comment by pvtmert** [comment]
hi there, i am having same issues

here is terminal output:

```
Merts-MacBook-Air:projects mert$ brew search --debug
Error: invalid option: --debug
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:82:in `parse'
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:9:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:41:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Merts-MacBook-Air:projects mert$ brew search --debug  tmux
Error: invalid option: --debug
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:82:in `parse'
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:9:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:41:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Merts-MacBook-Air:projects mert$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  cocoapods
  docker
  docker-compose
  docker-credential-helper
  docker-machine
  librtlsdr
  numpy
  pyqt
  python@2
  screen
Merts-MacBook-Air:projects mert$ brew config
HOMEBREW_VERSION: 1.7.2-59-g0af24cf
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0af24cf8bc6ae9572de19c1f1209320f81cf31e2
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0259c66b03f81bd174959493ad8cdcaef4025224
Core tap last commit: 6 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: nano
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 10.0.2, 1.8.0_181
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: 8.2.1
XQuartz: 2.7.11 => /opt/X11
Merts-MacBook-Air:projects mert$ 
```

**Comment by pvtmert** [comment]
hello there, i was able to solve the problem by updating all repos and taps

`find /usr/local/Homebrew -name ".git" -exec dirname {} \; | xargs -n1 -I% -- bash -c 'cd %; pwd; git pull'`
