### ISSUE TITLE
`brew update` generates a file for `brew cleanup` every time

### ISSUE THREAD

**Issue by JBallin** [Homebrew/brew#4689]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 1.7.1-250-g2c68176
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2c68176ac21b7c5fd53a2e02617376fac9fc6f4c
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7ece5465d21b3544d5e0ea9b1b90c9e3788b125b
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2
macOS: 10.13.6-x86_64
CLT: N/A
Xcode: 9.4.1
XQuartz: N/A
```

---

```
$ brew cleanup
$ brew update
$ brew cleanup
Removing: /usr/local/var/homebrew/locks/update... (0B)
```

Should `brew update` be creating that file every time and showing its removal every time `brew cleanup` is run? 

Likely introduced in #4639 @reitermarkus

**Comment by reitermarkus** [comment]
> Should `brew update` be creating that file every time

Yes.

> and showing its removal every time `brew cleanup` is run?

Debatable, but I don't think it's worth special-casing this just to hide the output.

**Comment by MikeMcQuaid** [comment]
@reitermarkus The lock file should be either removed by `brew update` when it's no longer needed or not removed and recreated by `brew update`.
