### ISSUE TITLE
How to add alias for formula ?

### ISSUE THREAD

**Issue by deepak** [Homebrew/brew#469]
How to add an alias for a formula ?

for example: the `zeromq` formula has an alias `zmq`
ie. `zmq` is linked under /usr/local/Library/Aliases 
and can do a `brew search` for `zmq` and `zeromq`

but do not understand, how is that done ?
looked at:
- the zeromq formula
- [cookbook](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md)

wanted to know for, adding an alias for the `node` formula

right now, we have to remember to, do a brew install `node4-lts`
but want to install `node-lts` which will alias `node4-lts` now
and `node6-lts` when a new LTS is released in a few months

**Comment by dunn** [comment]
For aliases you create a symlink in the Aliases directory, pointing at the formula you want to alias: https://github.com/Homebrew/homebrew-core/tree/master/Aliases

But I can't see any way to have a symlink automatically change where it points to; from `node4-lts` to `node6-lts` in your case.

**Comment by deepak** [comment]
ok. thanks @dunn for answering

one more question, 
where does the `zeromq` formula create an alias for `zmq` ?
do not see anything for alias in the `zeromq` formula

**Comment by dunn** [comment]
It doesn't.  We create aliases manually.
