### ISSUE TITLE
Added support for 10.10

### ISSUE THREAD

**Issue by Krzysztow** [Homebrew/brew#4693]
Hi,

it happened I needed to use brew on OSX 10.10 Yosemite:
```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27
```
Initially, when I was trying to install it, I was getting bash errors about functions with non-existing identifiers. Eventually, I realised it's because some of the functions' names are written with dashes, and this OS particular version of bash 
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
```
doesn't support such names. Moreover, it seems that POSIX standard doesn't allow dashes in names. Fortunately (for me), there were just few functions named in this manner. I managed to get them renamed by replacing underscores, and updating value of HOMEBREW_COMMAND before calling appropriate script.

Then, running brew installation with `HOMEBREW_DEV_CMD_RUN=1` environment variable worked without issues.

Please find attached the script with the changes I made.
[change_bash_function_names_dashes_to_underscores.patch.txt](https://github.com/Homebrew/brew/files/2290810/change_bash_function_names_dashes_to_underscores.patch.txt)

**Comment by MikeMcQuaid** [comment]
Please submit patches as a pull request in future. This does not seem to be necessary for me on older versions of macOS so passing on this.
