### ISSUE TITLE
Odd message just started - awk?

### ISSUE THREAD

**Issue by kernel-task** [Homebrew/brew#47]
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

All above done, clean, up to date system.
Everything working as expected......but

### Bug report:

Every command involving 'brew' results in the following output preceding the command going ahead and completing successfully!

**$ brew update**
awk: syntax error at source line 1
 context is
	 >>> {print <<<  $1"/"$2}
awk: illegal statement at source line 1
awk: syntax error at source line 1
 context is
	 >>> {print <<<  $1"/"$2}
awk: illegal statement at source line 1
**Already up-to-date.**

brew update/upgrade/doctor/install etc (everything!) shows the same behaviour - "error" message followed by successful completion.

Anyone else seen this?

Regards and Thanks to all.

FC

**Comment by UniqMartin** [comment]
Thanks for your report! I think we need more information to be able to help you. Can you please provide the complete output of the following commands: `brew config`, `brew doctor`, `awk --version`, `which curl`, and `curl --version`?

**Comment by kernel-task** [comment]
**[FC-Mac-Pro:local admin$ brew config**
awk: syntax error at source line 1
 context is
	 >>> {print <<<  $1"/"$2}
awk: illegal statement at source line 1
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d7aa0c0335dd67e4151503f3a29d7089c57059c3
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4b444310f26fb8350e05ca1eee54e1b39ad227c2
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.11.4-x86_64
Xcode: 7.3
CLT: 7.3.0.0.1.1457485338
Clang: 7.3 build 703
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
**FC-Mac-Pro:local admin$  brew doctor**
awk: syntax error at source line 1
 context is
	 >>> {print <<<  $1"/"$2}
awk: illegal statement at source line 1
Your system is ready to brew.
**FC-Mac-Pro:local admin$ awk --version**
awk version 20121220
**FC-Mac-Pro:local admin$ which curl**
/usr/bin/curl
**FC-Mac-Pro:local admin$ curl --version**
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

and so it goes!

Regards
FC

**Comment by UniqMartin** [comment]
> ```
> $ awk --version
> awk version 20121220
> ```

This looks suspicious. I'm also on OS X 10.11.4, but for me this prints `awk version 20070501`. What does `which awk` print on your system? (It should be `/usr/bin/awk` if it is the one provided by OS X.) Do you remember installing `awk` from some external source?

**Comment by kernel-task** [comment]
OK you fixed it!!!

**[FC-Mac-Pro:local admin$ which awk**
/usr/local/bin/awk

Then the output from
**brew list**
indicated that I, at 'some stage', installed the brew version.
I removed and reinstalled it.
Problem cleared up.

Obvious as it is now, it simply did not register with me that awk was a component in the chain of events involved in the execution of a brew command. Yes it's right there, but yet.....My bad.
I need to allocate some time to study and understand the details of brew.

Your help is greatly appreciated.
Thank You.
Regards
FC

**Comment by UniqMartin** [comment]
You're welcome; great we were able to resolve this one! :smile_cat: Your input is still valuable, as it helps us to improve Homebrew and make it more resilient against different user configurations.

**Comment by alexanderfrey** [comment]
Same problem here. 'brew uninstall awk' helped. Thanks !

**Comment by kenorb** [comment]
Same here, uninstalling Brew `awk` helped.

Failing example:

```
$  echo foo bar | awk '{print $1}'
awk: syntax error at source line 1
 context is
	 >>> {print <<<  $1}
awk: illegal statement at source line 1
```

**Comment by sdhull** [comment]
This happened for me randomly yesterday. For me, `awk --version` started with `2007` (!) and `which awk` was `/usr/local/bin`

No idea what happened (everything was fine the day before), but `brew install awk` fixed it for me.
