### ISSUE TITLE
expose configuration for object download binary/command

### ISSUE THREAD

**Issue by ak2k** [Homebrew/brew#4704]
I think it would be great if brew allowed the configuration of the utility used to download/stage resources to provide users control over download behavior. Personally, I would enjoy leveraging a utility that parallelizes downloads, but I can also imagine that others users may wish to throttle downloads for slower links or adjust download retry behavior for unreliable links.

While it is currently possible to [stage downloads by hand](https://docs.brew.sh/Tips-N'-Tricks#pre-downloading-a-file-for-a-formula), and this is a reasonable solution for occasional use, it would be vastly more useful if it were possible to configure the object download utility used throughout.

**Comment by MikeMcQuaid** [comment]
Sorry but we're not interested in providing that level of customisation. A middle ground may be for you to build an external command that uses internal Homebrew logic to implement a `brew fetch` alternative using a non`-curl` downloader. Please fill out the issue template in future.
