### ISSUE TITLE
S3DownloadStrategy Support for STS Session Token IDs

### ISSUE THREAD

**Issue by bwarminski** [Homebrew/brew#4706]
## Motivation

As a homebrew user in a corporate environment that builds custom tooling on top of open source components, I need a way to fetch artifacts from private S3 buckets. In some larger AWS deployments, users authenticate with an AWS bastion account and then assume roles into various other accounts. Similarly, users of tools such as aws-vault do not pass their raw AWS access key and id to applications, instead they lock the keypair away onto the OSX keychain and use STS to generate temporary access key pairs. In both cases, an additional variable is required to authenticate with the AWS SDK, called the session token.

The Ruby SDK included in the S3Download strategy supports this functionality natively by looking for an environment variable called AWS_SESSION_TOKEN, but because brew filters out this variable before running formulae, it's impossible to use without setting HOMEBREW_NO_ENV_FILTERING. 

In this case, a simple incancation such as `aws-vault exec myawsprofile -- brew install mycustom tool` turns into `aws-vault exec myawsprofile -- bash -c "HOMEBREW_NO_ENV_FILTERING=false brew install"` in the best case, in the worst case if the formula depends on multiple other formulae, the polluted environment variables may prevent dependent components from building properly.

## Proposal

My proposal is to include AWS_SESSION_TOKEN in the env var whitelist in the brew command, and to update the S3DownloadStrategy to lookup HOMEBREW_AWS_SESSION_TOKEN in addition to the access key and secret pair it's already looking up.

This seems like a minor change that could greatly improve usability. I'm also more than happy to make the PR.

**Comment by MikeMcQuaid** [comment]
> My proposal is to include AWS_SESSION_TOKEN in the env var whitelist in the brew command, and to update the S3DownloadStrategy to lookup HOMEBREW_AWS_SESSION_TOKEN in addition to the access key and secret pair it's already looking up.

You can pass through `HOMEBREW_AWS_SESSION_TOKEN` as-is without it needing whitelist; the code will just need modified to use it. PR would be great, thanks!
