### ISSUE TITLE
homebrew ignores depends_on formula tap name when installing dependencies

### ISSUE THREAD

**Issue by eedwards-sk** [Homebrew/brew#4711]
Currently, if I have two repos tapped on a local system:

`alpha/repo`

and

`beta/repo`

and I have a formula alias called `my-formula-1.0` inside both repos

I am able to install a specific one of those formulas by specifying the fully qualified tap name e.g.

`brew install alpha/repo/my-formula-1.0`

or

`brew install beta/repo/my-formula-1.0`

However, when homebrew is using the `depends_on` section of a formula to install a formula, if the formula is specified with a fully qualified tap name (e.g. `depends_on "beta/repo/my-formula-1.0"`), it ends up installing the version of `my-formula-1.0` from a different tap (`alpha/repo/my-formula-1.0`) even though the tap name was fully qualified

**To be clear, I'm aware that without specifying the fully qualified tap name, and a formula exists in multiple taps, it may come from any of those taps. This is specifically an issue for when the tap name IS being fully qualified.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [N\A] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [N\A] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [see below] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Attempting to install dependency from formula which specifies a tap name

- What happened (include command output)
The tap name was ignored and formula was installed from a different tap

The dependency in the formula was specified with a tap name:

```
depends_on "snapkitchen/private-dev/bash-util-1.0"
```

That formula has a dist url and root url both in s3. However, you can see that the file it attempts to download to satisfy the dependency actually comes from the location specified in a formula in a different tap (note it's downloading from minio rather than s3):

```
==> Installing dependencies for homebrew-ci/bottling-4042/snap-dev: snapkitchen/private-dev/bash-util-1.0
==> Installing homebrew-ci/bottling-4042/snap-dev dependency: snapkitchen/private-dev/bash-util-1.0
git config --local --replace-all homebrew.private true
==> Downloading http://minio.service.local.consul:9000/bash-util-dev-bottles/bash-util-1.0@1.0.0-1.0.0.high_sierra.bottle.tar.gz
```

- What you expected to happen
What should have happened, was that the `brew install` it is executing on my behalf, should be keeping the fully qualified tap name, and thus installing the dependency from that tap.

As it stands it appears that it's somehow stripping the tap name away and just installing based on the formula name.

- Step-by-step reproduction instructions (by running `brew` commands):

This is from a ci process for private repos so you will not be able to reproduce directly from these examples, but the problem is clear enough. So I'm providing this for additional detail:

```
brew tap --full --force-auto-update snapkitchen/private-dev file:///opt/concourse/local/worker/volumes/live/185bde8f-0a5e-4b4f-611b-9cc153f1d818/volume/homebrew-repo/.git

brew tap --full homebrew-ci/bottling-4042 file:///opt/concourse/local/worker/volumes/live/8a33399a-e2ad-47de-537e-0369cd6aa2c2/volume/homebrew-output-repo/.git

brew fetch --force --build-from-source homebrew-ci/bottling-4042/snap-dev

brew install --verbose --build-bottle --build-from-source homebrew-ci/bottling-4042/snap-dev --without-bats-core
```

`brew config`

```
HOMEBREW_VERSION: >=1.4.0 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: file:///opt/concourse/local/worker/volumes/live/efafb667-0140-4c40-6338-effaabe3c1bc/volume/homebrew-core/.git
Core tap HEAD: 836f4870e93842b73caf6bcd5c32a58b06b877b2
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /opt/concourse/local/worker/volumes/live/293a64e8-b9e1-4d75-6bef-5da0ac0fad7b/volume/homebrew-install/Homebrew
HOMEBREW_REPOSITORY: /opt/concourse/local/worker/volumes/live/293a64e8-b9e1-4d75-6bef-5da0ac0fad7b/volume/homebrew-install/Homebrew
HOMEBREW_CELLAR: /opt/concourse/local/worker/volumes/live/293a64e8-b9e1-4d75-6bef-5da0ac0fad7b/volume/homebrew-install/Homebrew/Cellar
HOMEBREW_CACHE: /opt/concourse/local/worker/volumes/live/293a64e8-b9e1-4d75-6bef-5da0ac0fad7b/volume/homebrew-cache
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_USER_GROUP: staff
HOMEBREW_USER_NAME: eedwards
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

`brew tap`

```
homebrew/core
snapkitchen/private-dev
```

`brew tap-info --installed`

```
homebrew/core: unpinned, private, 2 commands, 4613 formulae
/opt/concourse/local/worker/volumes/live/293a64e8-b9e1-4d75-6bef-5da0ac0fad7b/volume/homebrew-install/Homebrew/Library/Taps/homebrew/homebrew-core (4,870 files, 12.3MB)
From: file:///opt/concourse/local/worker/volumes/live/efafb667-0140-4c40-6338-effaabe3c1bc/volume/homebrew-core/.git

snapkitchen/private-dev: unpinned, private, 4 formulae
/opt/concourse/local/worker/volumes/live/293a64e8-b9e1-4d75-6bef-5da0ac0fad7b/volume/homebrew-install/Homebrew/Library/Taps/snapkitchen/homebrew-private-dev (30 files, 79.5KB)
From: file:///opt/concourse/local/worker/volumes/live/ec228674-5c4f-498e-70ff-f6be230a5c89/volume/homebrew-repo/.git
```

**Comment by eedwards-sk** [comment]
Here's each formula, with sensitive data removed:

snap-dev formula

```
class SnapDev < Formula
  desc "SnapKitchen Local Mac Development Tool"
  homepage "https://github.com/our_repo"
  url "http://minio.service.local.consul:9000/snap-dev-dev-sources/snap-dev-0.0.0+1534460393.4b13908.eb1d862.tar.gz"
  version "0.0.0"
  sha256 "4b13908160f17aff55ca5f2f993c41fbbc4b28a3dbca2fe148ba014c0c8490b5"
  option "without-bats-core", "does not use bash automated testing system"
  depends_on "snapkitchen/private-dev/bash-util-1.0"
  depends_on "bats-core" => [:build, :recommended]
  def install
    require 'securerandom'
    ENV['BUILD_ID'] = SecureRandom.uuid unless ENV.has_key?('BUILD_ID')
    # ENV.deparallelize
    system "./configure", "--disable-silent-rules",
                          "--prefix=#{prefix}"
    system "make"
    if build.with? "bats-core"
      system "make", "check"
    end
    system "make", "install"
    system "make", "installcheck"
  end
end
```

`snapkitchen/private-dev/bash-util-1.0` formula
(this is what it SHOULD have been using when it was installing `snapkitchen/private-dev/bash-util-1.0` as a dependency)... note the URLs are S3 based (sanitized)

```
class BashUtil10AT100 < Formula
  desc "Bash Utility Library"
  homepage "https://github.com/snapkitchen/bash-util"
  url "s3://foo-dev-source-distributions/bash-util/bash-util-1.0-1.0.0+1534196612.9accc26.fa65359.tar.gz"
  version "1.0.0"
  sha256 "9accc26a4c816f4110dc2965a09d30ca6e9e650fc68f541fb6f67884ae253788"
  bottle do
    root_url "s3://foo-dev-homebrew-bottles/bash-util/repo"
    cellar :any_skip_relocation
    rebuild 1
    sha256 "abb42e6625508febbd3abd9811fe813bd43bc033bf7fe6485db5fae60b127550" => :high_sierra
  end

  option "without-bats-core", "does not use bash automated testing system"
  depends_on "bats-core" => [:build, :recommended]
  def install
    require 'securerandom'
    ENV['BUILD_ID'] = SecureRandom.uuid unless ENV.has_key?('BUILD_ID')
    # ENV.deparallelize
    system "./configure", "--disable-silent-rules",
                          "--prefix=#{prefix}"
    system "make"
    if build.with? "bats-core"
      system "make", "check"
    end
    system "make", "install"
    system "make", "installcheck"
  end
end
```

this formula existed in the bottling repo (`homebrew-ci/bottling-4042`) and thus also is a valid option for `bash-util-1.0`... note the URLs are what was used, even though the dependency installation output says it's installing `snapkitchen/private-dev/bash-util-1.0`

```
class BashUtil10AT100 < Formula
  desc "Bash Utility Library"
  homepage "https://github.com/snapkitchen/bash-util"
  url "http://minio.service.local.consul:9000/bash-util-sources/bash-util-1.0-1.0.0-cf0713b88c84fb61e7b1f39c6dd4b0d390be4fbb.tar.gz"
  version "1.0.0"
  sha256 "3270c1db23c6d2ccf5cff666a77be273c655841110eef4f4393b407998c33522"
  bottle do
    root_url "http://minio.service.local.consul:9000/bash-util-dev-bottles"
    cellar :any_skip_relocation
    sha256 "617a6347466b249feb55d1fd013b68f01dae259913ad1cfdb8d9423fc4b05ccb" => :high_sierra
  end

  option "without-bats-core", "does not use bash automated testing system"
  depends_on "bats-core" => [:build, :recommended]
  def install
    require 'securerandom'
    ENV['BUILD_ID'] = SecureRandom.uuid unless ENV.has_key?('BUILD_ID')
    # ENV.deparallelize
    system "./configure", "--disable-silent-rules",
                          "--prefix=#{prefix}"
    system "make"
    if build.with? "bats-core"
      system "make", "check"
    end
    system "make", "install"
    system "make", "installcheck"
  end
end
```

both repos (`private-dev` and the bottling repo) have aliases in them which point `bash-util-1.0` to `bash-util-1.0@1.0.0`

**Comment by eedwards-sk** [comment]
Finally, for some more context...

Assume I have developers who are tapping a private repo `foo/private`

One developer is having issues with a specific tool from the repo (`my-tool-1.0`), so I build a 'dev version' of that tool, and publish it under a dev private repo `foo/private-dev`.

I instruct the dev to reinstall the problematic tool by first tapping the dev repo and then specifying the fully qualified tap name (e.g. `foo/private-dev/my-tool-1.0`) when installing

This currently works fine.

However, if `my-tool-1.0` has a `depends_on` dependency for `foo/private-dev/my-lib-1.0`, but `my-lib-1.0` exists in `foo/private`, it may try to install `foo/private/my-lib-1.0` instead of the `private-dev` version.

This is why pinning a tap does not solve it, because dependencies may be coming from various different taps that are particular to that dependency's state in a release cycle (dev channel or released).

**Comment by eedwards-sk** [comment]
from `Library/Homebrew/formula_installer.rb`

Note that it's using the full name to output to the console, but I suspect `install_dependency` is not using the full name when installing? I'll dig into it more this weekend hopefully.

```
  def install_dependencies(deps)
    if deps.empty? && only_deps?
      puts "All dependencies for #{formula.full_name} are satisfied."
    elsif !deps.empty?
      oh1 "Installing dependencies for #{formula.full_name}: #{deps.map(&:first).map(&Formatter.method(:identifier)).join(", ")}",
        truncate: false
      deps.each { |dep, options| install_dependency(dep, options) }
    end

    @show_header = true unless deps.empty?
  end
```

**Comment by MikeMcQuaid** [comment]
> formula is specified with a fully qualified tap name (e.g. depends_on "beta/repo/my-formula-1.0"), it ends up installing the version of my-formula-1.0 from a different tap (alpha/repo/my-formula-1.0)

Have you verified this is the case with taps with those names? I'm looking at:

> brew tap
> homebrew/core
> snapkitchen/private-dev

and it's not clear to me this isn't just an issue with duplicating homebrew/core formulae names elsewhere.

> This is from a ci process for private repos so you will not be able to reproduce directly from these examples, but the problem is clear enough.

Can you provide a reproduction using public repos?

> [N\A] ran brew doctor, fixed all issues and can still reproduce the problem?

This isn't "not applicable"; you haven't done it. Can you please include your `brew doctor` output? I'm seeing a lot of issues here.

> This is why pinning a tap does not solve it

Can you elaborate on this? If you pin `snapkitchen/private-dev` repo and fully-qualify the dependencies it still prioritises `homebrew/core`?

**Comment by eedwards-sk** [comment]
@MikeMcQuaid 

Thanks for the response. Apologies as this is a bit of a convoluted setup on my part and I was trying to simplify the description of the issue somehow. `alpha/repo` and `beta/repo` were just examples.

```
homebrew/core
snapkitchen/private-dev
```

The tap missing from this list is the bottling tap (`homebrew-ci/bottling-4042` from above), which is tapped shortly after.

It's the taps `snapkitchen/private-dev` and `homebrew-ci/bottling-4042` which both contain the formula alias `bash-util-1.0` which both point to formula `bash-util-1.0@1.0.0` in their respective repos.

The core issue is that if I have multiple private taps that contain the same formula name, homebrew is installing the wrong formula, even though I'm using the fully qualified tap name.

That was the example from the top, thus `alpha/repo` and `beta/repo` both contain `my-formula-1.0`, and if I do a `brew install` and specify the tap e.g. `brew install alpha/repo/my-formula-1.0` then I get the `my-formula-1.0` from that `alpha/repo` even though there's another `my-formula-1.0` available in the `beta/repo`. Meaning homebrew is respecting the fully qualified tap name and looking for that tap.

However, when it's a dependency in a formula (`depends_on "alpha/repo/my-formula-1.0"`), then homebrew is NOT respecting the fully qualified tap name, and in the above case might end up installing `beta/repo/my-formula-1.0` even when it says `"Installing alpha/repo/my-formula-1.0..."`

I'll do a `brew doctor` as soon as I get the stack up again. I was under the impression `brew doctor` possibly tried to 'auto fix' issues, so I was hesitant to run it.

**Comment by MikeMcQuaid** [comment]
> The core issue is that if I have multiple private taps that contain the same formula name, homebrew is installing the wrong formula, even though I'm using the fully qualified tap name, WHEN it's specified as a dependency in a formula.

Is it installing from homebrew/core even when told to use a tap or installing from the wrong, non-core tap?

**Comment by eedwards-sk** [comment]
@MikeMcQuaid 

It's installing from the wrong, non-core tap.

**Comment by MikeMcQuaid** [comment]
@eedwards-sk Cool, gotcha. Yes, that's definitely a valid bug in that case; we might not have considered it one if it was using core when not intended. If you can create public repos to reproduce that'll make fixing it much easier. Thanks for explaining!

**Comment by eedwards-sk** [comment]
Okay, I created a public repo repro (lol), but it's failing to reproduce the exact problem.

I created two public repos:
https://github.com/eedwards-sk/homebrew-alpha
https://github.com/eedwards-sk/homebrew-beta

a formula in alpha with a beta dependency:
https://github.com/eedwards-sk/homebrew-alpha/blob/master/Formula/my-formula.rb

the beta dependency formula:
https://github.com/eedwards-sk/homebrew-beta/blob/master/Formula/my-dependency-1.0%401.0.0.rb

an alpha version, as well (in the original issue, this would be the dependency which gets incorrectly grabbed):
https://github.com/eedwards-sk/homebrew-alpha/blob/master/Formula/my-dependency-1.0%401.0.0.rb

and then aliases in each repo which point `my-dependency-1.0` to `my-dependency-1.0@1.0.0` in their respective repos:
https://github.com/eedwards-sk/homebrew-alpha/blob/master/Aliases/my-dependency-1.0
https://github.com/eedwards-sk/homebrew-beta/blob/master/Aliases/my-dependency-1.0

the first run was an inverse from the original, in this case I tapped the alpha repo before the beta repo... the beta repo is the 'correct repo' for the dependency

[here's the gist](https://gist.github.com/eedwards-sk/35af70a905d987bffe1aed21d72e5719)

The correct file was attempted to be downloaded:

```
==> Installing dependencies for eedwards-sk/alpha/my-formula: eedwards-sk/beta/my-dependency-1.0
==> Installing eedwards-sk/alpha/my-formula dependency: eedwards-sk/beta/my-dependency-1.0
git config --local --replace-all homebrew.private true
==> Downloading http://www.example.com/beta-bottles/my-dependency-1.0@1.0.0-1.0.0.high_sierra.bottle.tar.gz
```

Had this repro'd the original issue, it would have displayed `Downloading <snip>/alpha-bottles/<snip>` instead of `/beta-bottles/`.

So then I thought maybe I needed to tap the dependency repo (beta) before the 'build' repo (alpha), like in the original repro...

[here's the gist](https://gist.github.com/eedwards-sk/0a9f3971e4ec6ef892e7b723475c7658)

In this case, it still worked, as well:

```
==> Installing dependencies for eedwards-sk/alpha/my-formula: eedwards-sk/beta/my-dependency-1.0
==> Installing eedwards-sk/alpha/my-formula dependency: eedwards-sk/beta/my-dependency-1.0
git config --local --replace-all homebrew.private true
==> Downloading http://www.example.com/beta-bottles/my-dependency-1.0@1.0.0-1.0.0.high_sierra.bottle.tar.gz
```

Again, correctly going to `beta-bottles`.

I'm going to do another test now with 's3 style' paths, which is the next difference between this public repro and my original issue, and see if that changes it.

Otherwise, if I still can't repro, I'll do further digging into my ci process environment and see if I can debug what's confusing the state (e.g. if I can confirm the behavior fully works in a normal Homebrew install then it's gotta be my ci and not Homebrew).

**Comment by eedwards-sk** [comment]
Yep, Unable to reproduce... because I got it working :)

I reworked my ci system a couple times to optimize caching and a few other things, and now I've got homebrew pulling the correct dependency. I'm not sure what was causing the original issue and with my complex setup it's clearly edge case at best.

I'll reopen should I somehow get a consistent public repro.

Thanks

**Comment by MikeMcQuaid** [comment]
Thanks for keeping us updated!
