### ISSUE TITLE
Add --without-perl and --without-ruby option for VIM?

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/brew#4712]
Is it possible to add the following option for VIM:
* --without-perl 
* --without-ruby

There's one for python already, aka `--without-python`, but not others

**Comment by CaledoniaProject** [comment]
Is there any reason to add these configure options by default?

```
opts = ["--enable-perlinterp", "--enable-rubyinterp"]
```

**Comment by DomT4** [comment]
> There's one for python already, aka --without-python, but not others

It's not really intended as an option... as such. It's not so much _"We're cool with you building with no python"_ but more a _"If you don't build with python@2 we pretty strongly encourage you to build with python"_.

> Is there any reason to add these configure options by default?

Yes. Options aren't CI tested by Homebrew, which means inevitably they have a much higher rate of failure or potential for failure than simply having something on or off by default, and that degrades both user experience and formula maintainability.

I think this sort of request has been shot down in Homebrew enough that it's unlikely to be any different this time around, and consequently I'm going to close this. I'll gently ping @MikeMcQuaid here as the `vim` changes were kinda his project originally and consequently if he _wants_ to say something different to me here that's cool, but barring that there's no appetite for change on this particular issue.

**Comment by CaledoniaProject** [comment]
I've cleared the opt array and it still works. Now I can safely remove perl and ruby2.5.
