### ISSUE TITLE
`brew cleanup` should `git prune`

### ISSUE THREAD

**Issue by JBallin** [Homebrew/brew#4714]
I ran `git prune` in brew's repo and it removed 5k+ items:

```shell
Homebrew (master) $ brew cleanup
Homebrew (master) $ git prune
Checking connectivity: 51957, done.
```

Is there a downside to doing this? I believe this would clear space on the users' computers, which I find beneficial.

**Comment by MikeMcQuaid** [comment]
There's not. Please fill out the issue template in future though (which would point you towards Discourse for similar issues 😄).

**Comment by JBallin** [comment]
@MikeMcQuaid I actually filled out the "New Feature" template and I tried searching discourse for `"git prune"` and found nothing?

**Comment by MikeMcQuaid** [comment]
Ok, it doesn't look to me like you followed the template but this is still an issue worth keeping open. A PR would be great!

**Comment by DomT4** [comment]
I assume the intention would be to _only_ apply this to the `brew` repo? Mostly asking because even after doing multiple `git prune` operations in core I still pop an average of 27 seconds per `git prune` there.

**Comment by JBallin** [comment]
@MikeMcQuaid, on second thought you're right about template and asking the downside to `git prune` question on discourse. Sorry about that!

I looked into putting ``git prune`` in [Library/Homebrew/cleanup.rb](https://github.com/Homebrew/brew/blob/b3e3b1c8ba2ae9525c052250fe39be3c9c4cd047/Library/Homebrew/cleanup.rb) but I'm wondering if it should actually go in [Library/Homebrew/cmd/update.sh](https://github.com/Homebrew/brew/blob/f2163d0f6e3d77bf224b7d82775b8989a2db7324/Library/Homebrew/cmd/update.sh) so that users don't need to run `cleanup` and it sort've fits in with the other git commands.

1. Which file should it go in?
2. Any guidance on where to place it within that file?
3. Do you agree that the user shouldn't see any output (`> /dev/null`)?

---

@DomT4 I'm running it on `$(brew --prefix)/Homebrew`? Is core installed on our machines?

**Comment by DomT4** [comment]
> I'm running it on $(brew --prefix)/Homebrew? Is core installed on our machines?

Aye, it's the primary tap for formulae and ships by default. `brew --repo homebrew/core` will give you its location.
