### ISSUE TITLE
Error: 'english' cannot be parsed to a Locale

### ISSUE THREAD

**Issue by ajcarr** [Homebrew/brew#4718]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to search for Clozure Common Lisp, and if available, to install it. Note that prior to this search, Homebrew was working just fine. I can't remember if I did a brew update just before the problem manifested, I'm afraid.

- What happened (include command output)

I don't understand why Tor Browser cask appears twice in the traceback.
```
$ brew search clozure
Error: 'english' cannot be parsed to a Locale
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/locale.rb:15:in `parse'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl.rb:141:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl.rb:141:in `language_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl.rb:115:in `language'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/torbrowser.rb:84:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:36:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:36:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:67:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:15:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:113:in `cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/torbrowser.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:20:in `block in each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:27:in `select'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:27:in `search_string'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:7:in `search'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/search.rb:29:in `search_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:83:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

- What you expected to happen

I expected it to return the name of the clozure-cl package. I get the same error message with other brew search <package> commands such as "brew search python" and "brew search sbcl". 

Note that another user has also reported this problem elsewhere (this time for Portuguese):

https://github.com/Homebrew/homebrew-core/issues/30124

- Step-by-step reproduction instructions (by running `brew` commands)

See above. Note that I have LC_ALL="en_IE.UTF-8" set in .profile.

Brew doctor only reports the components of Cocoaspell as being unbrewed:
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libaspell.15.dylib
  /usr/local/lib/libpspell.15.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/aspell.h
  /usr/local/include/pspell/pspell.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libpspell.la
```

Brew config output:
```
$ brew config
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6a245c05110c240e680da594c2cc6038998b82e
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aaa69d507eff8c0296433611031fc4d0cc926f27
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: nvi
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2, 1.6.0_65-b14-468
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: 2.7.11 => /opt/X11
```

**Comment by reitermarkus** [comment]
What's the output of `defaults read -g AppleLanguages`? It should not contain `english`, but `en` instead.

**Comment by ajcarr** [comment]
Many thanks for the quick response. Here's the output:

$ defaults read -g AppleLanguages
(
    "en-IE",
    "en-GB",
    "english (united kingdom) [ize-IE",
    "english (United Kingdom) [ize-wo"
)


> On 18 Aug 2018, at 01:41, Markus Reiter <notifications@github.com> wrote:
> 
> What's the output of defaults read -g AppleLanguages? It should not contain english, but en instead.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--

Dr Alun J. Carr
Senior Lecturer in Materials
School of Mechanical and Materials Engineering
UCD Engineering and Materials Science Centre
University College Dublin
Belfield, Dublin 4, Ireland

Homepage: <http://goo.gl/mWxIn>
OpenPGP key: <http://bit.ly/1lBsM9n>
Fingerprint: D294 0DE3 BD75 3A41 D5DB  E796 C783 69F5 D60B 7C0F
My photos: <http://goo.gl/SDDCB>

Unless you need me to edit documents, please send me PDFs rather than MS
Office files: <http://goo.gl/tWI9>
Free software for creating PDFs in Windows: <http://goo.gl/YGaf>

**Comment by reitermarkus** [comment]
Those last two are the problem. What is System Preferences -> Language showing?

**Comment by ajcarr** [comment]
Markus,

I've deleted the last two from System Preferences -> Language and the problem's gone away. They were present from dictionaries specified in the Spelling PrefPane of cocoAspell. The thing is, cocoAspell was previously active with no problems, and deleting the unbrewed components identified by brew doctor didn't change the result. CocoAspell is usually installed by (La)TeX users on macOS as part of MacTeX. It can also be installed via brew cask install cocoaspell.

Here's the web page for cocoAspell:

<http://people.ict.usc.edu/~leuski/cocoaspell/>

Many thanks for your efforts.

Best regards,

Alun

> On 18 Aug 2018, at 01:52, Markus Reiter <notifications@github.com> wrote:
> 
> Those last two are the problem. What is System Preferences -> Language showing?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--

Dr Alun J. Carr
Senior Lecturer in Materials
School of Mechanical and Materials Engineering
UCD Engineering and Materials Science Centre
University College Dublin
Belfield, Dublin 4, Ireland

Homepage: <http://goo.gl/mWxIn>
OpenPGP key: <http://bit.ly/1lBsM9n>
Fingerprint: D294 0DE3 BD75 3A41 D5DB  E796 C783 69F5 D60B 7C0F
My photos: <http://goo.gl/SDDCB>

Unless you need me to edit documents, please send me PDFs rather than MS
Office files: <http://goo.gl/tWI9>
Free software for creating PDFs in Windows: <http://goo.gl/YGaf>
