### ISSUE TITLE
install failed on new machine because I installed MacGPG2 first

### ISSUE THREAD

**Issue by grant-olson** [Homebrew/brew#472]
I'm not sure if anything can be done to fix this, but thought I should submit something to at least document the issue even if it can't be fixed. I set up a new machine and installed my standard software. Went to install brew and it failed half way through. I couldn't re-install because it thought it was installed, but the `brew` command wouldn't run.

After changing the permissions on `/usr/local/` and running the uninstall, I noticed it left over MacGPG2 files. I presume this install created `/usr/local` and locked in permissions that brew didn't like.

**Comment by DomT4** [comment]
Can you elaborate on this a bit? Any MacGPG2 from the last 3 or so years is designed to not smash permissions in `/usr/local` _outside_ of `/usr/local/MacGPG2`. Can you talk me through your steps?

>  I couldn't re-install because it thought it was installed, but the brew command wouldn't run.

Was `/usr/local/bin` in your `$PATH`?

You can solve the problem where it thinks it's completely installed by running `rm -rf /usr/local/.git` or using Homebrew's `uninstall` script [from this repo](https://github.com/Homebrew/install).

**Comment by grant-olson** [comment]
I had a pretty clean system, so I might have blamed the wrong software.

1. Got a laptop from an old co worker. It had full disk encryption and I didn't have the password, so I was forced to repartition and start with a clean install of El Capitan from the recovery console.

2. Installed the following programs, using current versions available directly from the website:

    * Firefox
    * Thunderbird
    * KeepassX
    * LibreOffice
    * GpgSuite

3. After that tried to install brew via the curl command, and it blew up with an error I unfortunately don't have.

Its possible brew didn't work because I was in the same terminal tab and didn't get a new shell with a new environment. I can't rule that out.

An attempt to reinstall complained that it wouldn't proceed because I already had brew installed, and instructed me to perform a curl command with uninstall option.

Running that command and then the install command succeeded. I'm also unsure at this point if I was in the same bash shell with the same environment or if I was in a new terminal when I ran `brew install git`

**Comment by grant-olson** [comment]
Actually one more thing.

4. I ran `sudo chown 'whoami`' /usr/local` with backticks instead of quotes around whoami to set permissions on the directory based on some stackoverflow link I found.

**Comment by MikeMcQuaid** [comment]
I'm afraid we don't have enough here to do anything with. If you can let us know exactly what commands you ran we can try and make fixes. Sorry and thanks!

**Comment by DomT4** [comment]
I'm pretty much 100% sure this was some local issue rather than specific to MacGPG2, but please do poke if you stumble into this again so we can look again.
