### ISSUE TITLE
brew style doesn't report that url is not in top of head spec

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#4724]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
```ruby
  head do
    depends_on "automake"
    depends_on "autoconf"
    depends_on "gettext"
    url "git://git.savannah.gnu.org/tar.git"
  end
```
- What happened (include command output)
`brew style --fix` doesn't report any issues.
- What you expected to happen
`brew style --fix` should report and fix the problem
- Step-by-step reproduction instructions (by running `brew` commands)
re-arrange `url` and `depends_on` in any head spec.

<details>
  <summary>brew config</summary>
 
```
HOMEBREW_VERSION: 1.7.1-298-gbab5b02
ORIGIN: https://github.com/Homebrew/brew
HEAD: bab5b0229387870979ea459126eb5b2ecedb1638
Last commit: 19 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d02d24271e09e53f0bd81318320c2370b58b3d4e
Core tap last commit: 77 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_EMOJI: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1533942731
CLT headers: N/A
Xcode: 10.0 => /Applications/Xcode-beta.app/Contents/Developer
XQuartz: N/A
```
</details>

<details>
  <summary>brew doctor</summary>
 
 ```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: You are using macOS 10.14.
We do not provide support for this pre-release version.
You will encounter build failures and other breakages.
Please create pull-requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this pre-release version,
you are responsible for resolving any issues you experience.
```
</details>

**Comment by yurikoles** [comment]
BTW, there should be an empty line between `url` and `depends_on`

**Comment by yurikoles** [comment]
https://github.com/Homebrew/homebrew-core/pull/31245

**Comment by DomT4** [comment]
`url` placement should be enforced as on-top. We kinda assume people will check other `HEAD` formulae in core and follow that style but audits are safer than assumptions.

I'm not that fussed about whether or not people prefer an empty line between `url` and `depends_on` in `head do` blocks _but_ I personally have a preference towards an empty line because I think it helps minimise confusion; people rather often leave no gap between `sha256` and the first `depends_on` in new formulae and I'm not sure inconsistency between `head do` and stable-only helps this.

If we enforce a line or lack thereof though I think it's only worth doing so on new formulae, personally. I don't think it's something worth getting contributors to fix.

**Comment by yurikoles** [comment]
bump?
