### ISSUE TITLE
brew audit exits 0 with symlinks

### ISSUE THREAD

**Issue by jedahan** [Homebrew/brew#4725]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
When making a new formula, running `brew audit` (with and without `--strict` and `--online`)

- What happened (include command output)
Exit 0, wow my formula has no issues!

- What you expected to happen
Some sort of issues, no way I wrote it correctly the first time.

- Step-by-step reproduction instructions (by running `brew` commands)
* Edit any formula to have audit issues (reorder dependencies for example)
* Check that brew audit has issues
* Move it from homebrew-core to a different directory
* Symlink the full path to homebrew-core/Formula
* Check that brew audit shows no issues

brew config
```bash
HOMEBREW_VERSION: 1.7.1-285-gb8e276a
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8e276ad8a85f14cd556834318b45d80074d11a8
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a3da5c81a8856ea67d248b0f63e5d1041d0a6204
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_UPGRADE_CLEANUP: 1
HOMEBREW_VISUAL: amp
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: 2.7.11 => /opt/X11
```

brew doctor
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Volumes/data/tmp/cargo/bin/cargo-install-update-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.6m/greenlet/greenlet.h
```

**Comment by MikeMcQuaid** [comment]
Don't symlink in future. This doesn't warrant a maintainers' change but we'll accept a PR if you fix the issue.

**Comment by jedahan** [comment]
Is there any documentation anywhere, or any error message to help point people in the right direction? Where would be the most appropriate place to help future formula contributors to avoid thinking their formulas are fine when they aren't?

**Comment by MikeMcQuaid** [comment]
@jedahan You're the first person I've seen that has run into this problem. We have millions of users so don't write documentation for things until we're confident they will be needed by a non-trivial number of people. There will always be undocumented edge cases.

**Comment by jedahan** [comment]
I was just asking in response to "we'll accept a PR" where I should start looking - either in documentation or code to help fix this.

**Comment by MikeMcQuaid** [comment]
I don't think it's a priority to fix this, honestly, but I was suggesting if you do we won't reject your work out of hand.
