### ISSUE TITLE
There should be a mechanism stopping inadvertent major-version upgrades

### ISSUE THREAD

**Issue by ellmo** [Homebrew/brew#4726]
When performing `brew upgrade` or `brew upgrade <formula>`, the default behaviour should not allow for major version upgrades – at least not for complicated software like PostrgreSQL.

The reason behind this is that those upgrades often stop software from working as intended, as many major-version updates are not fully backwards compatible – and in the case of PostgreSQL they are actually worlds apart.

5 minute googling session showed that I was **by far** not the only one who managed to unwillingly jump from PosgtreSQL 9.6 to 10.5 in a mere console command – and, while I do admit, that I erroneously used `brew upgrade` instead of `brew update` – there was no way to simply reverse what I did when I realised my mistake.

---

**On a side note:** I managed to broke my databases completely when I decided to just _go with it_ and use `brew postgresql-upgrade-database` which failed and now my local databases for both 9.6 and 10.5 are completely empty.

If anyone knows wether `brew postgresql-upgrade-database` creates a backup of databases before attempting to update and where to find it – I'd be much obliged

**Comment by MikeMcQuaid** [comment]
Do not run `brew upgrade` without arguments if you wish to avoid this behaviour. Also, I recommend using Time Machine or similar so you can recover from similar incidents. Finally, please always fill out the issue template (as it told you to do).
