### ISSUE TITLE
shut down daemons on uninstall

### ISSUE THREAD

**Issue by rdp** [Homebrew/brew#4732]
If there is a "brew services" component, at uninstall time, make sure it is shut down before uninstalling.

- the motivation for the feature

Today you can (for instance) install msyql, start it, uninstall it, and *it will still be running* with the files gone from underneath it.

- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)

All homebrew users would like their services to uninstall "cleanly"

- what alternatives to the feature you have considered

none

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

Originally reported here:
https://github.com/Homebrew/homebrew-core/issues/29995#issuecomment-413589972

Cheers!

**Comment by MikeMcQuaid** [comment]
`brew services` cannot tell if it's been used or the server has been started manually outside of Homebrew. This would be a fairly large change in behaviour that may result in unexpected behaviours for some users. As a result: passing on this, sorry.
