### ISSUE TITLE
High Sierra LibreSSL SSL_read error on brew install

### ISSUE THREAD

**Issue by tech4242** [Homebrew/brew#4733]
- What you were trying to do (and why)
Trying to use homebrew as I have for the past X years :) I just switched to a new MacBook Pro 2018 from my late 2013 (with the same OS) yesterday and I ran `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"` The output of brew doctor etc. is below.

- What happened (include command output)
After every brew install that I tried (wget, node, htop ...) I got the following log:

```
user ~ $ brew install wget
==> Installing dependencies for wget: gettext, libunistring, libidn2, openssl
==> Installing wget dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/99/99d2dbd4c9ebfe9bf2a64bd99f3a695a18635f0d9110eaff34bab8022abef6a8?__gda__=exp=15
#####                                                                      7.6%
curl: (56) LibreSSL SSL_read: error:060BC064:digital envelope routines:AEAD_AES_GCM_OPEN:bad decrypt, errno 0

curl: (56) LibreSSL SSL_read: error:060BC064:digital envelope routines:AEAD_AES_GCM_OPEN:bad decrypt, errno 0
Error: Failed to download resource "gettext"
Download failed: https://homebrew.bintray.com/bottles/gettext-0.19.8.1.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz
################                                                          23.4%^C
```

- What you expected to happen
Well, a normal brew install I guess. Instead this led to a `make` on each dependency.

- Step-by-step reproduction instructions (by running `brew` commands)
Not really much to say here except all the provided logs. Just ran `brew install <insert any formula you can think of>`

**System**

Macbook Pro 2018, i5
MacOS High Sierra 10.13.6

Brand new system without a timemachine restore or anything like that.

**brew doctor output**

```
user ~ $ brew doctor
Your system is ready to brew.
```

**brew config output**
```
user ~ $ brew config
HOMEBREW_VERSION: 1.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b119591c6963bff320501f52f9029e4862c00e97
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d1923e8df8a85d6b20618fe46a98b55aaf0fd6aa
Core tap last commit: 80 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

**Comment by MikeMcQuaid** [comment]
This is not something we can do anything about, I'm afraid, as it's a problem with your ability to download from our bottle host.

**Comment by tech4242** [comment]
@MikeMcQuaid thanks for the quick feedback on this. While I agree that it is probably on my end, this is a brand new setup without any custom installs whatsoever, so I figured someone could have an idea as I've never had that issue on any Macs that I've used before.

**Comment by tech4242** [comment]
Update: Actually installing e.g. `htop` does work but I have this issue with `node` and `wget`. But it _is_ a network issue as I tried a hotspot just now. Thank you again for your message.
