### ISSUE TITLE
There is a problem installing brew in termux

### ISSUE THREAD

**Issue by 821938089** [Homebrew/brew#4734]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Install brew in termux
According to the tutorial:https://github.com/Linuxbrew/brew/wiki/Android

- What happened (include command output)
$ brew
Traceback (most recent call last):
        13: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/brew.rb:15:in `<main>'
        12: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/brew.rb:15:in `require_relative'
        11: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/global.rb:15:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         8: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/config.rb:47:in `<top (required)>'
         7: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/pathname.rb:578:in `mkpath'
         6: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
         5: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:193:in `each'
         4: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
         3: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
/data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Read-only file system @ dir_s_mkdir - /tmp (Errno::EROFS)

- What you expected to happen

fix it

- Step-by-step reproduction instructions (by running `brew` commands)

$  brew config
Traceback (most recent call last):
        13: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/brew.rb:15:in `<main>'
        12: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/brew.rb:15:in `require_relative'
        11: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/global.rb:15:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         8: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/config.rb:47:in `<top (required)>'
         7: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/pathname.rb:578:in `mkpath'
         6: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
         5: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:193:in `each'
         4: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
         3: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
/data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Read-only file system @ dir_s_mkdir - /tmp (Errno::EROFS)

$ brew doctor
Traceback (most recent call last):
        13: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/brew.rb:15:in `<main>'
        12: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/brew.rb:15:in `require_relative'
        11: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/global.rb:15:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         8: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/config.rb:47:in `<top (required)>'
         7: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/pathname.rb:578:in `mkpath'
         6: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
         5: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:193:in `each'
         4: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
         3: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
/data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Read-only file system @ dir_s_mkdir - /tmp (Errno::EROFS)

$ brew update
Checking if we need to fetch /data/data/com.termux/files/home/prefix/brew...
Already up-to-date.

**Comment by MikeMcQuaid** [comment]
> 1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:in fu_mkdir' /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:inmkdir': Read-only file system @ dir_s_mkdir - /tmp (Errno::EROFS)

You'll need to fix this. Please note Linuxbrew is not supported here (yet).
