### ISSUE TITLE
Dependency resolution of brew uses --installed seems to display erronous result compared to brew uses

### ISSUE THREAD

**Issue by Porkepix** [Homebrew/brew#4737]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
It's reproducible wth one formula (`gdbm here`) and will depend on other installed ones, but it's possible install the same ones to reproduce.
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
It's reproducible from one formula but does not come from the formula itself, therefore should be reproducible on different ones.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
Listed issues are not issues but warning and unrelated here.
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
Joining here the result of `brew doctor`, but the output is unrelated to the issue:
```
mbp :: ~ » brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ansible-lint
  gnupg

Warning: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You will encounter build failures and other breakages.
Please create pull-requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this old version,
you are responsible for resolving any issues you experience.

Warning: Your Xcode (6.1.1) is outdated.
Please update to Xcode 6.2 (or delete it).
Xcode can be updated from the App Store.
```
`brew config`:
```
mbp :: ~ » brew config
HOMEBREW_VERSION: 1.7.2-4-g713532e
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 713532e763c3cc6f86b89f5a40994cd624eaec55
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f181ec7bd36c12c4b584e48a0d8be18afa7314f5
Core tap last commit: 9 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 6.0 build 600
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.61.0 => /usr/local/opt/curl/bin/curl
Java: N/A
macOS: 10.9.4-x86_64
CLT: 6.2.0.0.1.1424975374
Xcode: 6.1.1
XQuartz: 2.7.11 => /opt/X11
```

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to know why a formula was installed, hence which installed formulas were depending on it (`brew uses --installed`)
- What happened (include command output)
```
mbp :: ~ » brew uses --installed gdbm
ansible                cython                 livestreamer           python                 streamlink             vim
ansible-lint           gobject-introspection  perl                   python@2               thefuck
```
- What you expected to happen
The list seemed to include surprising formulas, so after that I decided to check it with `brew uses` without the `--installed`. `brew uses --installed` should only display a subset of `brew uses` if I'm not mistaken. However, here's the result:
```
mbp :: ~ » brew uses gdbm
gnu-smalltalk               pypy                        pypy3                       python                      python@2
```

We can see that `brew uses`display less formulas than `brew uses --installed`, which it shouldn't.
- Step-by-step reproduction instructions (by running `brew` commands)
Just comparing outputs from `brew uses` and `brew uses --installed`

**Comment by MikeMcQuaid** [comment]
`brew uses --installed` uses the dependency resolution information from your installed formulae whereas `brew uses` alone does not.

**Comment by MikeMcQuaid** [comment]
What is the output of `brew linkage ansible`?

**Comment by Porkepix** [comment]
Sure, here it is:
```
mbp :: ~ » brew linkage ansible
System libraries:
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libexslt.0.dylib
  /usr/lib/libffi.dylib
  /usr/lib/libxml2.2.dylib
  /usr/lib/libxslt.1.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/gmp/lib/libgmp.10.dylib (gmp)
  /usr/local/opt/libyaml/lib/libyaml-0.2.dylib (libyaml)
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
Variable-referenced libraries:
  @executable_path/../.Python
Undeclared dependencies with linkage:
  gmp
```

**Comment by MikeMcQuaid** [comment]
So you can see from this it's linked to `gmp`. What does `brew linkage gmp` output?

**Comment by Porkepix** [comment]
Here for gmp, which doesn't seem to be linked to anything else:
```
mbp :: ~ » brew linkage gmp
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
Homebrew libraries:
  /usr/local/Cellar/gmp/6.1.2_2/lib/libgmp.10.dylib (gmp)
```

And for Ansible, why does it link to something not listed as dependencies? (Or more generally, why can this happen?)

**Comment by MikeMcQuaid** [comment]
@Porkepix When built from source some things pick up dependencies opportunistically i.e. they link against stuff without us trying to make them do so. The other thing where this kicks in is if you've built a formula with a particular, non-default option. We now store these links in the formula itself and use it for certain commands so you get a result that's correct for your system (i.e. `brew uses --installed` doesn't miss results that will break things if uninstalled). Opportunistically linking is technically a formula bug but it's very hard to avoid with some buildsystems (e.g. CMake).

**Comment by Porkepix** [comment]
Oh, that's the reason cmake ask me to install Java everytime and I need to deny it everytime? (And it's not resulting in a formula install fail).

As for the current case, looking at result of `brew linkage gmp`, it seems that it is nowhere depending on `gdbm`, right? So, it is listing dependencies it shouldn't?

**Comment by MikeMcQuaid** [comment]
@Porkepix `brew deps --installed --tree` should reveal some insights; can I see the output of that? Thanks!

**Comment by Porkepix** [comment]
Here it is, on a paste because it would have been really really long for a GitHub comment: https://privatebin.net/?c6ef06b08df766ea#ljXDqm02igaB34C8uu1C1gt579zHyU8nvN5nwJ1Bw7c=

**Comment by MikeMcQuaid** [comment]
Yeh, so your `python@2` and `python` depend on `gdbm` so that's where your dependency is coming from.

**Comment by Porkepix** [comment]
And is it intended to not show only direct dependencies but also recursive ones? Especially, to show them the same way/at the same level?
I think if it's intended to display both direct and undirect dependencies it could be nice to do so differently.

**Comment by MikeMcQuaid** [comment]
Yeh, it's not ideal but would welcome PRs to improve the current behaviour/visualisation 😁
