### ISSUE TITLE
`brew style --fix` to sort dependencies automatically

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#4738]
One may encounter dependency hell in `audit` when adding new formula, because it requires them to be sorted alphabetically, and build-only deps to be on top, and so on. I think such an operation must be automated, to not require human to go through fix-and-re-run-audit.

**Comment by MikeMcQuaid** [comment]
@yurikoles Please always fill out the template. CC @GauthamGoli for thoughts.

**Comment by GauthamGoli** [comment]
@yurikoles Please provide a list of dependencies that you are trying to add. 
I think the functionality you are talking about is already present.

**Comment by MikeMcQuaid** [comment]
@yurikoles Did you try to `brew style --fix`?

**Comment by yurikoles** [comment]
I had figured out that this only happens with `--new-formula`.

To reproduce: resort deps in any formula in random order, `brew style --fix` is happy, but `brew audit --strict --new-formula` wants them to be in alphabetical order.

For example: change deps in `ruby` formula as follows: 
```
  depends_on "readline"
  depends_on "openssl"
  depends_on "pkg-config" => :build
  depends_on "libyaml"
```

```
$ brew style --fix ruby

1 file inspected, no offenses detected

$ brew audit ruby --strict --new-formula
ruby:
  * C: 25: col 3: dependency "openssl" (line 25) should be put before dependency "readline" (line 24)
  * C: 26: col 3: dependency "pkg-config" (line 26) should be put before dependency "readline" (line 24)
  * C: 27: col 3: dependency "libyaml" (line 27) should be put before dependency "readline" (line 24)
  * Formulae should not have a `HEAD` or `devel` spec
```

**Comment by GauthamGoli** [comment]
Please try
`brew audit --new-formula --fix <name_of_formula>`

If you want only dependency order to be fixed, run
`brew audit --fix --only-cops=NewFormulaAudit/DependencyOrder <name_of_formula>`

**Comment by GauthamGoli** [comment]
Yeah, Thanks! Please open a new issue. I'm closing this.
