### ISSUE TITLE
Access denied during installing Homebrew on macOS High Sierra v 10.13.4

### ISSUE THREAD

**Issue by ashu123mae** [Homebrew/brew#4739]
RiteshK:rsa-soap-client Ritesh$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
/usr/local/Homebrew/.git/branches/: Permission denied
Failed during: git init -q

**Comment by woodruffw** [comment]
Please reopen this with the issue template filled out. Per the header:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
