### ISSUE TITLE
PHP server failing to start because of brew libpng version

### ISSUE THREAD

**Issue by ruffiem** [Homebrew/brew#474]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

```bash
$ php -v
dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /usr/local/bin/php
  Reason: Incompatible library version: php requires version 40.0.0 or later, but libpng16.16.dylib provides version 38.0.0
Trace/BPT trap: 5
```

I don't really know where to post this but libpng formula should be updated 1.6.23, then it works like a charm.

```bash
  url "ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.23.tar.xz"
  mirror "http://download.sourceforge.net/libpng/libpng-1.6.23.tar.xz"
  sha256 "6d921e7bdaec56e9f6594463ec1fe1981c3cd2d5fc925d3781e219b5349262f1"
```

Cheers

**Comment by DomT4** [comment]
Seems like your Homebrew is out-of-date if `libpng` isn't already that version. We adopted that on Jun 11 2016. I'd try a `brew update`.

**Comment by ruffiem** [comment]
Thanks for your answer Dom but I did, I also removed libpng, php56, cleaned up everything and reinstalled it but it didn't solve the problem.

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by MikeMcQuaid** [comment]
Also post `which php`, thanks.

**Comment by BlakeBeus** [comment]
I had this same issue.  I fixed it by running:

`brew update`
`brew update`
`brew upgrade`
`brew doctor`

And fixing everything the doctor told me to fix.  I think the main thing that fixed it was the `brew upgrade` but might as well fix up everything else.

**Comment by ruffiem** [comment]
I guess we can close the issue then ^^

**Comment by halleytl** [comment]
I fixed it by running
`brew update
brew upgrade libpng
`
