### ISSUE TITLE
1.7.2 breaks versioned bottle filenames

### ISSUE THREAD

**Issue by eedwards-sk** [Homebrew/brew#4740]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [NO] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [YES] ran `brew update` and can still reproduce the problem?
- [NO] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [NO] ran `brew config` and `brew doctor` and included their output with your issue?

I apologize in advance, I'm skipping some of the above initially as it should be irrelevant, but I'll happily provide more environment detail, as needed.

This is a fairly simple breaking change between 1.7.1 and 1.7.2

on 1.7.2, versioned bottle filenames are now being generated similar to their cached name, but the installer is still looking for their previous name...

e.g.:

**on 1.7.1, note the following snippets from the below bottling run**

bottle json file name
```
bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.json
```

bottle json filename
```
"filename":"bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz"
```

bottle filename
```
bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz
```

specifically, note that it's `0.0@0.0.0-0.0.0` with a single dash `-` inbetween `0.0.0` and `0.0.0`

<details>

```
==> Determining bash-util/repo/bash-util-0.0@0.0.0 bottle rebuild...
==> Bottling bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz...
./bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz
  bottle do
    root_url "file:///opt/concourse/local/worker/volumes/live/d1a5056e-ad93-41cf-6bc7-347879f125d9/volume/bottle"
    cellar :any_skip_relocation
    sha256 "3f67f1fa8ddcf9782533eee2d247159f8e09ee63cd992c4000b4845934278790" => :high_sierra
  end
+ cat ./bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.json
{"bash-util/repo/bash-util-0.0@0.0.0":{"formula":{"pkg_version":"0.0.0","path":"Library/Taps/bash-util/homebrew-repo/Formula/bash-util-0.0@0.0.0.rb"},"bottle":{"root_url":"file:///opt/concourse/local/worker/volumes/live/d1a5056e-ad93-41cf-6bc7-347879f125d9/volume/bottle","prefix":"/usr/local","cellar":"any_skip_relocation","rebuild":0,"tags":{"high_sierra":{"filename":"bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz","sha256":"3f67f1fa8ddcf9782533eee2d247159f8e09ee63cd992c4000b4845934278790"}}},"bintray":{"package":"bash-util-0.0:0.0.0","repository":"bottles-repo"}}}+ homebrew_ci__brew /opt/concourse/local/worker/volumes/live/d1a5056e-ad93-41cf-6bc7-347879f125d9/volume/homebrew-install bottle --merge --write --no-commit ./bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.json
+ /opt/concourse/local/worker/volumes/live/d1a5056e-ad93-41cf-6bc7-347879f125d9/volume/homebrew-install/Homebrew/bin/brew bottle --merge --write --no-commit ./bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.json
error: could not lock config file /opt/concourse/local/worker/volumes/live/d1a5056e-ad93-41cf-6bc7-347879f125d9/volume/homebrew-install/Homebrew/.git/config: No such file or directory
==> bash-util/repo/bash-util-0.0@0.0.0
  bottle do
    root_url "file:///opt/concourse/local/worker/volumes/live/d1a5056e-ad93-41cf-6bc7-347879f125d9/volume/bottle"
    cellar :any_skip_relocation
    sha256 "3f67f1fa8ddcf9782533eee2d247159f8e09ee63cd992c4000b4845934278790" => :high_sierra
  end
+ local local__homebrew_bottle_file_path=
++ ls ./bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz
+ local__homebrew_bottle_file_path=./bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz
```

</details>

**now on 1.7.2 note the following snippets and how it changes**

bottle json file name
```
bash-util-0.0@0.0.0--0.0.0.high_sierra.bottle.json
```

bottle json filename
```
"filename":"bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz"
```

bottle filename
```
bash-util-0.0@0.0.0--0.0.0.high_sierra.bottle.tar.gz
```

note that there are now two dashes in the json filename and the bottle filename `0.0@0.0.0--0.0.0` (and this seems to be similar to what the filenames look like when downloaded to the cache)

**however**, note that the filename inside the bottle json is still expecting the previous filename with a single dash: `bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz`

thus in my output below, you can see that it fails to download the bottle from the expected path, even though I just generated and put the bottle it made there!

```
Error: Failed to download resource "bash-util-0.0@0.0.0"
File does not exist: /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/bottle/bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz
```

<details>

```
==> Determining bash-util/repo/bash-util-0.0@0.0.0 bottle rebuild...
==> Bottling bash-util-0.0@0.0.0--0.0.0.high_sierra.bottle.tar.gz...
./bash-util-0.0@0.0.0--0.0.0.high_sierra.bottle.tar.gz
  bottle do
    root_url "file:///opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/bottle"
    cellar :any_skip_relocation
    sha256 "e3c34fc038ad26d1af1d61de3086c52826b016433483243b1a53e6c7bcf3da24" => :high_sierra
  end
+ cat ./bash-util-0.0@0.0.0--0.0.0.high_sierra.bottle.json
{"bash-util/repo/bash-util-0.0@0.0.0":{"formula":{"pkg_version":"0.0.0","path":"Library/Taps/bash-util/homebrew-repo/Formula/bash-util-0.0@0.0.0.rb"},"bottle":{"root_url":"file:///opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/bottle","prefix":"/usr/local","cellar":"any_skip_relocation","rebuild":0,"tags":{"high_sierra":{"filename":"bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz","sha256":"e3c34fc038ad26d1af1d61de3086c52826b016433483243b1a53e6c7bcf3da24"}}},"bintray":{"package":"bash-util-0.0:0.0.0","repository":"bottles-repo"}}}+ homebrew_ci__brew /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/homebrew-install bottle --merge --write --no-commit ./bash-util-0.0@0.0.0--0.0.0.high_sierra.bottle.json
+ /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/homebrew-install/Homebrew/bin/brew bottle --merge --write --no-commit ./bash-util-0.0@0.0.0--0.0.0.high_sierra.bottle.json
error: could not lock config file /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/homebrew-install/Homebrew/.git/config: No such file or directory
==> bash-util/repo/bash-util-0.0@0.0.0
  bottle do
    root_url "file:///opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/bottle"
    cellar :any_skip_relocation
    sha256 "e3c34fc038ad26d1af1d61de3086c52826b016433483243b1a53e6c7bcf3da24" => :high_sierra
  end
+ local local__homebrew_bottle_file_path=
++ ls ./bash-util-0.0@0.0.0--0.0.0.high_sierra.bottle.tar.gz
+ local__homebrew_bottle_file_path=./bash-util-0.0@0.0.0--0.0.0.high_sierra.bottle.tar.gz
+ cp ./bash-util-0.0@0.0.0--0.0.0.high_sierra.bottle.tar.gz /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/bottle/
+ popd
/opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume
+ build_it__test_bottled_install
+ homebrew_ci__brew /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/homebrew-install uninstall bash-util/repo/bash-util-0.0@0.0.0
+ /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/homebrew-install/Homebrew/bin/brew uninstall bash-util/repo/bash-util-0.0@0.0.0
Uninstalling /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/homebrew-install/Homebrew/Cellar/bash-util-0.0@0.0.0/0.0.0... (10 files, 297.3KB)
+ local local__install_output=
++ homebrew_ci__brew /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/homebrew-install install --verbose --env=std --force-bottle bash-util/repo/bash-util-0.0@0.0.0
++ /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/homebrew-install/Homebrew/bin/brew install --verbose --env=std --force-bottle bash-util/repo/bash-util-0.0@0.0.0
No entry for terminal type "unknown";
using dumb terminal settings.
curl: (37) Couldn't open file /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/bottle/bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz
Error: Failed to download resource "bash-util-0.0@0.0.0"
File does not exist: /opt/concourse/local/worker/volumes/live/a26ecf3f-b806-452c-714e-c79c7d5133b8/volume/bottle/bash-util-0.0@0.0.0-0.0.0.high_sierra.bottle.tar.gz
```

</details>

**Comment by eedwards-sk** [comment]
highly suspect it's related to https://github.com/Homebrew/brew/pull/4612

**Comment by eedwards-sk** [comment]
Looking at the related thread, it seems like this was a regression from supporting private bottling. Why do we suddenly need two dashes in the filename?

This is an additional burden where now, if I'm supposed to rename the bottle before publishing, that I have to read and parse the `json` file and extract the name... so now I have to have `jq` as an additional dependency. It also means I have to do filename orchestration between the `install` / `build-bottle` and `merge` steps.

Apologies for my frustration, but this change makes no sense to me! Any more context would be helpful.

**Comment by scpeters** [comment]
It is related to #4612, and I recommend reading the comments in that thread (e.g. https://github.com/Homebrew/brew/pull/4612#commitcomment-29994607) as several people noticed the issue shortly after it was merged (I didn't notice it until the 1.7.2 release).

There is also some discussion in https://github.com/Homebrew/homebrew-test-bot/issues/172, and I made a pull request to add the `local_filename` (with `--`) to the json in https://github.com/Homebrew/brew/pull/4736 (`filename` still has `-`). It's a little more work, but it should be doable with both file names provided in the json now.

**Comment by eedwards-sk** [comment]
Thanks @scpeters! I did read all the comments already.

I'm still confused over what was solved by adding this breaking change. From my perspective, homebrew is now generating filenames that don't match what is expected in the repo.

I'm also concerned over what `local_filename` implies? Does that mean the filename for `root_url` and the one that bottling process makes are still different? That's the problem!!

The process that works flawlessly in 1.7.1 is

`brew install`
`brew bottle --json`
`brew merge`

as the bottle it makes can be used directly in a following

`brew install`

step, where the `root_url` points to the bottle dir of the bottle generated by `brew bottle`

so I would LOVE to know if anyone can answer what was solved or gained by making that process now broken and require introspecting into a json file and renaming the file?

**Comment by eedwards-sk** [comment]
Another argument against this...

I now need jq on my system. Which is one more tool to build and compile during CI runs (my CI runs in isolation).

It also means I need to know the system I'm on in advance (high sierra), when before my automation was completely ignorant of it...

e.g. to grab the filename I want from the json requires denoting 'high_sierra' in the query path:

```
jq .[].bottle.tags.high_sierra.filename
```

before I can just do an `ls ./*.tar.gz` and get the filename... easy!

I could also do a regex parse and replace `--` with `-` after the fact... and hope that there aren't any valid `--`s anywhere else in the package name etc.

I'd rather not have to add more workaround hacks :(

**Comment by eedwards-sk** [comment]
Sorry for a million comments...

For posterity, and my sanity, I've made a workaround in my CI script for the mean time until further information is gained on this.

In case anyone else is doing something similar, this should work provided there aren't any needed double dashes in the string:

```sh
    # merge bottle output
    homebrew_ci__brew "${local__homebrew_install_dir}" \
      bottle --merge --write --no-commit ./*.json &&
    
    local local__homebrew_bottle_file_path= &&
    local__homebrew_bottle_file_path="$(ls ./*.tar.gz)" &&

    # workaround due to `--` instead of `-` in output bottle filename
    # see https://github.com/Homebrew/brew/issues/4740

    local local__homebrew_bottle_file_name= &&
    local__homebrew_bottle_file_name="$(basename "${local__homebrew_bottle_file_path}")" &&

    # this strips '--' and replaces it with '-'
    local__homebrew_bottle_file_name="${local__homebrew_bottle_file_name//--/-}"

    # copy bottle artifact to output dir as proper name
    cp "${local__homebrew_bottle_file_path}" "${local__homebrew_bottle_output_dir}/${local__homebrew_bottle_file_name}"
```

**Comment by scpeters** [comment]
> I'm still confused over what was solved by adding this breaking change.

I think the original rationale was described in https://github.com/Homebrew/brew/pull/4601 and that #4612 was a follow-up to fix a few things that got broken, so it didn't include the entire rationale. I think the filenames are nicer with the `--`, especially for packages with a `-` in their name.

This has changed the workflow for private bottlers (like myself), but the workarounds are pretty straightforward.

> I'm also concerned over what local_filename implies? Does that mean the filename for root_url and the one that bottling process makes are still different?

Yeah, the filenames are different. The bottle file on the server will have `-` and is given by `filename` in the json file. The local bottle files will have `--` and are given by `local_filename`. The reason for the discrepancy is the large number of bottle files that have already been uploaded.

> Was the process of bottling locally considered when making this change?

I would refer you to this comment from @MikeMcQuaid (https://github.com/Homebrew/brew/pull/4612#commitcomment-30139889): "`brew test-bot` remains the recommended, supported workflow for building and uploading bottles and efforts would be best spent there because that's what the official and a bunch of widely used external taps use."

If you are willing to use bintray, then I think you can use `brew test-bot` for private bottling, and it is supported. I am not using bintray for private bottling, so my use case isn't supported, but the maintainers were happy to merge my pull request in #4736 that makes my unsupported use case a little easier.

**Comment by scpeters** [comment]
@eedwards-sk you also don't necessarily need `jq`, since you can use `brew ruby` to get some json parsing (though its syntax is not as concise):

~~~
json_file=file.json
brew ruby -e \
  "puts JSON.load(IO.read(\"${json_file}\")).values[0]['bottle']['tags'].values[0]['local_filename']")
~~~

**Comment by reitermarkus** [comment]
The original problem was that `brew test-bot` relied on the implementation detail that the file produced by `brew bottle` had the same name as the upload filename, which broke because `brew test-bot` links the produced bottles to the cache using this name.

And as already mentioned , `brew test-bot` is the supported way to build and upload bottles. Closing this as `wontfix`, but we'd accept a PR to improve `brew test-bot` or `brew bottle`.

**Comment by MikeMcQuaid** [comment]
> Unfortunately that means I also can't easily use the brew test bot lifecycle for it, at least from what I understand.

You could submit PRs to adjust `brew test-bot` to better fit your needs.

**Comment by fabriciomurta** [comment]
I also faced this issue today while innocently building a bottle on an updated version of homebrew... So many surprises, every update.

Just my two cents but, if you are going to introduce a change for an specific end and introduce backwards compatibility issues for everyone else, why not add a runtime flag instead of breaking everyone else's build to fit your new model?..
