### ISSUE TITLE
option-based conflicts

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#4741]
I want to introduce a feature: conflict that is triggered only by some option.

One may want to have some feature provided by one of the possible implementations and keeping both formulas installed, while disabling particular feature in one of the formulas.
Example: there is two uuid implementations `ossp-uuid` and `util-linux`, I want to make `util-linux` conflict with `ossp-uuid` only if it's build `--with-uuid`, e.g.

```
conflicts_with "ossp-uuid" if build.with? "uuid"
```

As in https://github.com/Homebrew/homebrew-core/pull/31378

**Comment by DomT4** [comment]
I think the `conflicts_with` mechanism is already fairly unpleasant from a UX perspective and I'm not keen to expand its usage more than absolutely necessary, and options by being _options_ aren't absolutely necessary. I would be very reluctant to see core go down this path.

**Comment by MikeMcQuaid** [comment]
@yurikoles Please ease off on the feature request issues. We're trying to remove options rather than add more so I don't see us adding more DSLs around it, sorry.

**Comment by yurikoles** [comment]
@MikeMcQuaid sorry for disturbing.

**Comment by MikeMcQuaid** [comment]
@yurikoles That's ok, don't worry about it 😄
