### ISSUE TITLE
special characters (eg spaces) in commands should be escaped

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#4745]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

a command (eg `system`) ran with arguments having special characters (eg spaces) shows displayed in terminal without escaping it:
for example for this: https://github.com/timotheecour/homebrew-timutil/blob/master/ripgrep.rb
the following
system "cargo", "install", "--features", "pcre2 avx-accel", "--root", prefix
shows as:
==> cargo install --features pcre2 avx-accel --root /Users/timothee/homebrew/Cellar/ripgrep/HEAD-f1e0258
instead of:
==> cargo install --features pcre2\ avx-accel --root /Users/timothee/homebrew/Cellar/ripgrep/HEAD-f1e0258
or
==> cargo install --features 'pcre2 avx-accel' --root /Users/timothee/homebrew/Cellar/ripgrep/HEAD-f1e0258

**Comment by MikeMcQuaid** [comment]
This is a feature request rather than a bug. Note that that line is also truncated by the width of your terminal; it's not intended to be a copy-pasteable shell line.

> ran brew config and brew doctor and included their output with your issue?

You didn't. Please do in future.
