### ISSUE TITLE
Accept Bitcoin for donations

### ISSUE THREAD

**Issue by lucasgadams** [Homebrew/brew#4749]
Hello, feel free to delete this. I'd like to send some crypto your way as a donation for maintaining this wonderful tool. Should be easy enough to include a BTC address (or other crypto if you prefer) down in the donation section. I'll be sure to send a little your way!

**Comment by MikeMcQuaid** [comment]
Sorry, it's not easy for us to accept Bitcoin.

**Comment by 5hanth** [comment]
+1
