### ISSUE TITLE
Updating Homebrew 

### ISSUE THREAD

**Issue by omi10859** [Homebrew/brew#4757]
I'm not sure if this is right place ask this but 
Whenever I try to install something using command brew install something 
it shows Updating Homebrew... for while 
- why we always check for update 

even if the package name is wrong or the asked package does not exits Updating Homebrew take time We can speed this up process
- By first checking the package details (if it exists or not )

**Comment by MikeMcQuaid** [comment]
Read the manpage which provides options to not check for update every time.

**Comment by omi10859** [comment]
Thanks for information 
this looks similar : https://github.com/Homebrew/brew/issues/4755 to what i want to say
