### ISSUE TITLE
Official Linux support 

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#4758]
Homebrew/brew should seek to become the official, default Git remote for Linuxbrew. This will require upstreaming or removing all differences between Homebrew/brew and Linuxbrew/brew and adjusting our README and documentation accordingly to note that we support Linux now. Note that we should still frame Homebrew as primarily a macOS package manager as the number of Mac users is (and likely will be for the foreseeable future) much larger than Linux users.

**Comment by iMichka** [comment]
I would like to change "🍺 The missing package manager for macOS" on the main brew page to "🍺 The missing package manager for macOS and Linux". Thoughts?

There are also some doc/readme changes to be done, but these can be done through pull requests.

**Comment by sjackman** [comment]
@MikeMcQuaid Here's the list of supported distributions of Linux. Your thoughts? Shall I open a PR to create `docs/Linux.md`?

Homebrew on Linux requires…

- GCC 4.4 or newer, 4.7 or newer recommended
- Linux 2.6.32 or newer
- Glibc 2.12 or newer, 2.23 or newer recommended
- 64-bit x86

These distributions of Linux are supported.

- Ubuntu 16 or newer
- Debian 9 or newer
- Linux Mint 17 or newer
- Fedora 24 or newer
- CentOS 7 or newer
- Red Hat 7 or newer

Older distributions work, but are not actively supported.

- Ubuntu 12 or newer
- Debian 7 or newer
- CentOS 6 or newer
- Raspbian 7 or newer on Raspberry Pi

Installing Linuxbrew in its default location of `/home/linuxbrew/.linuxbrew` is strongly recommended to make use of precompiled binary packages and avoid compiling from source.

**Comment by sjackman** [comment]
Linuxbrew/core builds its bottles on Ubuntu 16.04 LTS (Xenial Xerus). This distribution of Linux is the only one that is tested by CI.

Linuxbrew does not use libraries of the host operating system other than Glibc and GCC, and then only if they are new enough, otherwise brewed `glibc` and `gcc` are used. All other libraries are provided by Linuxbrew.  For this reason, Linuxbrew has little dependency on the host distribution of Linux.

**Comment by MikeMcQuaid** [comment]
@imichka can you elaborate on which page specifically you mean? I don’t think that wording quite works because Linux is far from missing a package manager. Additionally I’d like to wait until Linux support is “official” (likely Homebrew 2.0) before we change too much user facing stuff.

**Comment by iMichka** [comment]
On https://github.com/Homebrew/brew (on the top, the line you can manually edit). On linuxbrew we had "The missing package manager for Linux". I am aware that Linux is not really missing package managers, but still, we have been (and still are) the missing package manager for Linux :D

Of course we can wait for user-facing stuff: the documentation can be updated I think, because that does no harm. The final things to change will be some minor changes to the readme and that's all.

**Comment by sjackman** [comment]
The comment line on https://github.com/Linuxbrew/brew reads…
The Homebrew package manager for Linux

**Comment by sjackman** [comment]
Linuxbrew is the missing no-root-needed package manager for Linux.

**Comment by iMichka** [comment]
Sorry, I misread that. Or maybe I read that somewhere else.

Anyway, it is one of the first things you see on that page. But I do not want to bike-shed that part too much :) Maybe it could just be `The Homebrew package manager`

**Comment by sjackman** [comment]
I suggest: The Homebrew package manager for macOS and Linux

**Comment by ycmjason** [comment]
Just passed by this issue and realise linuxbrew and homebrew are going to merge! What a great news! Thank you for the hard work! 🎉🎉🎉🎉🎉🎉

**Comment by rfay** [comment]
Thanks so much for the coaching, @sjackman - We got Linuxbrew into our tap, https://github.com/drud/homebrew-ddev - It's a huge step forward for us. A majority of our users are on macOS but a significant number use Linux with a wide variety of distros, and to be able to support them in a consistent way is beyond awesome. Thanks!

**Comment by sjackman** [comment]
Excellent! I'm glad to hear that Linuxbrew is working for you, Randy. I agree entirely that it simplifies life to be able to use a single package manager on all three common OS.

**Comment by MikeMcQuaid** [comment]
Now considering this 🚢d! 2.0.0 will land some time in the next week or so and all the changes are on `master` that are needed for this. Great work everyone but particularly to @sjackman and @iMichka!

**Comment by sjackman** [comment]
Woohoo! Big day! Thank you for your efforts in bringing Homebrew to Linux, Mike!
🍺🐧   🎆 🥂
