### ISSUE TITLE
"Error: /usr/local must be writable!" (Sierra 10.12 Beta (16A239j) )

### ISSUE THREAD

**Issue by pookah-net** [Homebrew/brew#476]
Just an FYI, and to get some advice on a better way of solving this! When running `brew doctor` I get this error: 

`Warning: /usr/local is not writable.`

And when running 'brew update', I get this:

`Error: /usr/local must be writable!`

I "solved" the problem by running `sudo chown -R `whoami` /usr/local`. That seems to have cleared the issue up.

Thanks!
Ian

**Comment by gentlecat** [comment]
Also see #385.

**Comment by DomT4** [comment]
We should probably consider either nudging people towards `brew doctor` or reprinting the chown instruction from `brew doctor`. It's fair that in itself simply saying we can't write to the directory isn't particularly helpful.

**Comment by pookah-net** [comment]
@gentlecat Thanks! I did look, but completely missed that one.

**Comment by itcuihao** [comment]
running sudo chown -R whoami /usr/local;
show: "chown: whoami: illegal user name";
must running "sudo chown -R `whoami` /usr/local ";
But still thank !

**Comment by itcuihao** [comment]
```
running sudo chown -R whoami /usr/local;
show: "chown: whoami: illegal user name";
must running "sudo chown -R \`whoami\` /usr/local ";
But still thank you

```

**Comment by itcuihao** [comment]
running sudo chown -R whoami /usr/local;
show: "chown: whoami: illegal user name";
must running "sudo chown -R \`whoami\` /usr/local ";
But still thank you

**Comment by MikeMcQuaid** [comment]
`$(whoami)` rather than `whoami`.

**Comment by JayBrown** [comment]
To my knowledge you can leave out the `-R` option. Chowning `/usr/local` hierarchies is not necessary for homebrew to function properly.

Best thing would be to require `sudo` for `brew` commands, but give users an opt-out as well.

**Comment by MikeMcQuaid** [comment]
`sudo chown -R` may be required as a one-off on occasion to allow Homebrew or Homebrew Cask to migrate to the new directory format. It is not required for new installs.

> Best thing would be to require sudo for brew commands, but give users an opt-out as well.

It's not required for day-to-day operation but is required for initial installation/migration. The opt-out is to install into a different directory.

**Comment by khaledannajar** [comment]
This did it `sudo chown -R $(whoami) /usr/local`
