### ISSUE TITLE
Reinstall formulae with broken linkage on `brew upgrade`

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#4761]
We `revision` bump things that have mandatory dependencies to other formulae that would otherwise be broken on a `brew upgrade`. Unfortunately this does not cover optionally or opportunistically linked dependencies which will be broken by a `brew upgrade` and require a manual `brew reinstall`. 

Thankfully we now have a fast cache for `brew linkage` so it's possible to quickly query on every upgrade whether there's any broken linkage and reinstall applications accordingly.

**Comment by amyspark** [comment]
I've had tons of these errors when updating `python@2`; implementing this would trigger rebuilding e.g. Weechat if it was built `--with-python@2`.

After reading `LinkageChecker` and its CLI command, the only way I found to do this would be to  `brew linkage --test` after every upgrade and `reinstall_formula` every keg which has `broken_deps`.

Is this correct?

**Comment by MikeMcQuaid** [comment]
> I've had tons of these errors when updating python@2; implementing this would trigger rebuilding e.g. Weechat if it was built --with-python@2.

Yes, that's what I'm thinking.

> After reading LinkageChecker and its CLI command, the only way I found to do this would be to brew linkage --test after every upgrade and reinstall_formula every keg which has broken_deps.

More or less although it wouldn't shell out to the actual command but just make use of the underlying linkage database, yeh 👍
