### ISSUE TITLE
Improve Homebrew/brew code coverage

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#4763]
It would be good to increase [our code coverage](https://codecov.io/gh/Homebrew/brew/tree/master/Library/Homebrew). This can be done by adding integration tests (only) for missing `cmd` and `dev-cmd` commands (e.g. https://codecov.io/gh/Homebrew/brew/src/master/Library/Homebrew/cmd/diy.rb), figuring out why some coverage is currently missing (e.g. https://codecov.io/gh/Homebrew/brew/src/master/Library/Homebrew/dev-cmd/ruby.rb despite https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/dev-cmd/ruby_spec.rb) and adding unit tests for files with low coverage (e.g. https://codecov.io/gh/Homebrew/brew/src/master/Library/Homebrew/hardware.rb).

**Comment by reitermarkus** [comment]
@alexbostock, many small PRs are easier to review than a huge one.

**Comment by MikeMcQuaid** [comment]
I think this is now good enough (>70%) that we don't need an open issue.
