### ISSUE TITLE
Add `brew configure-shell` to make installs outside of /usr/local easier

### ISSUE THREAD

**Issue by jamescostian** [Homebrew/brew#4780]
_Originally this was done for [Linuxbrew](https://linuxbrew.sh/) because it doesn't install to `/usr/local`, but the [leader of Linuxbrew mentioned that this is helpful for non-standard installations of Homebrew for macOS as well](https://github.com/Linuxbrew/brew/pull/829#issuecomment-417446720). For more information and to see some of the deliberation, check out [the issue for Linuxbrew](https://github.com/Linuxbrew/brew/issues/812)._

When installing outside of `/usr/local/` one must update their `PATH`, `MANPATH`, and `INFOPATH` (or at least just their `PATH`). Doing so is tedious and easy to automate. With this PR, [the alternative install guide](https://docs.brew.sh/Installation#untar-anywhere) would have this appended to its oneliner: ` && homebrew/bin/brew configure-shell`.

In addition to simplifying installs outside of `/usr/local` for macOS users, it's important to realize that this command has been created for Linuxbrew users, and after the merge of Linuxbrew and Homebrew, it would be nice if Linuxbrew users could still have this simple way of setting up their `PATH` and friends (that is, `PATH`, `MANPATH`, and `INFOPATH`).

# Code

It's 42 SLoC for the feature, 54 SLoC for tests for said feature, and 8 LoC to document it in `brew.1` and `Manpage.md`.

I'd make the same PR here as I made for Linuxbrew (that is, I'd make [this PR](https://github.com/Linuxbrew/brew/pull/829)). The only difference would be that I would use a regex with `^\s*source #{env_path}` to check if `brew.env` is already being sourced -  [here's the source of that idea](https://github.com/Linuxbrew/brew/pull/829/files#r214203970)

# Motivation

If you're installing outside of `/usr/local` then it's nice for your `PATH` and friends to all be updated. Users can do this manually, but it's tedious and this makes non-`/usr/local` installs feel more like first-class citizens

# Relevancy

This is relevant for 99% of non-`/usr/local` installs, but when you consider the merger with Linuxbrew I think that there will be a lot of non-`/usr/local` installs because Linuxbrew doesn't install to `/usr/local` ([see this](https://github.com/Linuxbrew/brew/wiki/FAQ#why-install-in-homelinuxbrewlinuxbrew)). In addition, there are already users who have non-`/usr/local` installs on their macs.

# Alternatives

The best alternative is to manually edit your `~/.profile` and change your `PATH` and friends

**Comment by MikeMcQuaid** [comment]
> This is relevant for 99% of non-/usr/local installs

It's worth noting we intentionally don't support these.

I'm up for reviewing a PR here but a warning that we're unlikely to merge the Linuxbrew implementation as-is and I think this may warrant an interface change (which may warrant a naming change) to be something like `eval $(brew shellenv)`.

**Comment by jamescostian** [comment]
Ok thanks!

I'm up for something like `eval $(brew shellenv)` but note that this command must also write to the user's `~/.profile` and friends (that way every time the user logs in, they have brew in their `PATH` and friends).

With that in mind, do you still want to call it `shellenv`? I'm afraid that `shellenv` sounds more like something that prints out the details but does not persist them. Other ideas from the previous issue/PR include:

- brew setenv
- brew write-environment
- brew configure
- brew setup

It's up to you :man_shrugging:

**Comment by jamescostian** [comment]
> I'm 👎 on having any Homebrew commands that write to ~/.profile

Ok, what if in the documentation on alternative installs, right after the oneliner [here](https://docs.brew.sh/Installation#untar-anywhere), you were to list the steps manually like this:

> To include brew in your `PATH`, `MANPATH`, and `INFOPATH` in your current shell session, use this:
> 
> ```
> eval $(homebrew/bin/brew shellenv)
> ```
> 
> To make brew permanently included in all of your login shells, use this:
> ```
> homebrew/bin/brew shellenv >> ~/.profile
> ```

(obviously I'm fine with this wording changing, I'm just wondering how visible we can make these notices).

In addition, `eval $(brew shellenv)` will allow for things to leak out from `brew shellenv` via stderr so maybe we could have stderr give them a notice about the intended ways to use the command, e.g. `eval $(brew shellenv)` would print to stderr something like:

```
Please note that shellenv has 2 main use-cases:
   eval $(#{HOMEBREW_PREFIX/"bin/brew"} shellenv)
   #{HOMEBREW_PREFIX/"bin/brew"} shellenv >> ~/.profile
The first only changes your current shell, the other changes every interactive login.
Feel free to change the second one to write to other files, e.g. ~/.bashrc
```

**Comment by colindean** [comment]
I'm OK incurring the hit to new terminal ready time if I can have the assurance that my dotfiles aren't going to get modified. There certainly is a balance to be struck, though: if it adds more than say 100 ms, I'll want to persist the output even if to a locally-included file (think .env.local).

I _detest_ when installing things do that because I keep my PATH managed in a separate file that gets sourced from `.profile`/`.bash_profile`/`.bashrc`. Half of the time it's wrong or it doesn't touch the right file!

Putting `eval $(#{HOMEBREW_PREFIX/"bin/brew"} shellenv)` into my PATH resolver is more futureproof than 

    #{HOMEBREW_PREFIX/"bin/brew"} shellenv >> ~/mydotfiles/setup_path.sh

and having to redo that when something changes/breaks.

**Comment by jamescostian** [comment]
The same futureproofing argument came up when discussing with Linuxbrew, and it was argued that this command could even be used to set `HOMEBREW_VERBOSE` and other environment variables. But ultimately we decided that those configurations belong elsewhere (e.g. a YAML or JSON file) and the purpose of this command was simply to make `brew` and things it installs accessible.

If you think about what changes will go on here from a futureproofing perspective, I'm sure it's clear that we're not going to add another `*PATH` variable, so the only real change happens when you move Homebrew (an event that probably happens once in a blue moon) - in which case, manual intervention is required either way.

The real reason I'm more in favor of having `export PATH=...` being written directly to a dotfile is that you may want to make Homebrew be the last place in your `PATH`. This is as simple as moving text around in your dotfile as long as you have `export PATH=...` directly in your dotfile - if you put `eval $(#{HOMEBREW_PREFIX/"bin/brew"} shellenv)` and you want to move Homebrew to be at the end of your `PATH` then you'll be very annoyed.

In addition, if you want Homebrew to be the last thing in your path, it's probably because you have other conflicting installations of things, in which case you probably wouldn't like `export MANPATH="#{HOMEBREW_PREFIX/"bin/brew/share/man"}:$MANPATH"` either. I think this flexibility is valuable for people who want alternative installations.

**Comment by MikeMcQuaid** [comment]
> Ok, what if in the documentation on alternative installs, right after the oneliner here, you were to list the steps manually like this

Yes, something like that would make sense.

> Putting eval $(#{HOMEBREW_PREFIX/"bin/brew"} shellenv) into my PATH resolver is more futureproof

Agreed. I also think if the output is even vaguely human readable we don't need to advertise `#{HOMEBREW_PREFIX/"bin/brew"} shellenv >> ~/.profile`; people who need it and care will figure it out.

> But ultimately we decided that those configurations belong elsewhere (e.g. a YAML or JSON file)

This is never going to happen 😉. We use environment variables for configuration and this has worked well for us.

> you want to move Homebrew to be at the end of your PATH, well, get ready for having some very ugly dotfiles.

People can manually add it to their dotfiles if they care about a custom configuration.

> I think this flexibility is valuable for people who want alternative installations.

Flexibility is often the enemy of good design. I think this applies here where this is a helper script that people can trivially implement themselves, too.

**Comment by jamescostian** [comment]
Seeing as this has drifted far off from the original idea (from one command that "just works" for 90% of people who run it, to giving users suggestions to tinker around), I personally do not consider this command to be worth having anymore.

If anyone wants the functionality that was asked for, it's as simple as adding a file called `Library/Homebrew/cmd/shellenv.rb` with these (BSD-2-Clause licensed) contents:

```ruby
#:  * `shellenv`:
#:    Prints export statements - run them in a shell and this installation of
#:    Homebrew will be included into your PATH, MANPATH, and INFOPATH.
#:    Tip: have your dotfiles eval the output of this command

module Homebrew
  module_function
  def shellenv
    puts <<~EOS
      # Homebrew environment
      # Created by running brew configure-shell
      export PATH="#{HOMEBREW_PREFIX}/bin:#{HOMEBREW_PREFIX}/sbin:$PATH"
      export MANPATH="#{HOMEBREW_PREFIX}/share/man:$MANPATH"
      export INFOPATH="#{HOMEBREW_PREFIX}/share/info:$INFOPATH"
    EOS
  end
end
```

Thank you for your feedback @MikeMcQuaid and @colindean, and thanks for the great work you two have put into Homebrew.

I do have a question though: since Linuxbrew's standard installation is *not* to `/usr/local`, after the merge, what's the plan with regards to that?

**Comment by sjackman** [comment]
To give the background for my motivation to merge this PR. When I teach introductory command line workshops, the participants have never used the command line before. Installing Linuxbrew is close to the first thing that we do, because we use it to install the tools that we'll be learning in the workshop. The students are not yet at the point where they have the ability to manually modify their `~/.bashrc`, though that task seems trivial to us.

I agree with not modifying any shell profile files without the user's explicit request, which is why `brew configure-shell` is a separate command and not run automatically by the installer.

For a surprise-free user experience, two things need to work after the user installs Linuxbrew:

1. Running `brew` in the current shell
2. Running `brew` in a new shell

To configure the current shell, the `sh -c` installation instructions can be changed to `eval` (with a corresponding change to `install.sh`).

```sh
eval "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

after which the user's shell profile can be configured with…

```sh
brew shellenv >> ~/.profile
```

**Comment by MikeMcQuaid** [comment]
> You've also asked that PRs be first merged into Linuxbrew for testing before being merged into Homebrew, so you see my quandary.

@sjackman Yes, my apologies for being unclear on that. I'd suggest that incremental Linux changes/tweaks go straight into Linuxbrew but any new commands etc. go into Homebrew/brew. How does that sound?

> I'll tag you in the PR Mike to request your input, if you're open to that.

Yeh, that works too 👍 



> To give the background

@sjackman Ok, I understand a bit more. I agree having:

> brew shellenv >> ~/.profile

work would be easier. I think it would be good to avoid an `eval` on `install` to avoid some fairly nasty potential attacks (our `ruby -e` is kinda bad enough but at least cannot modify the shell).

**Comment by sjackman** [comment]
> I'd suggest that incremental Linux changes/tweaks go straight into Linuxbrew but any new commands etc. go into Homebrew/brew. How does that sound?

👍 Sounds good to me.

> I agree having`brew shellenv >> ~/.profile` work would be easier. I think it would be good to avoid an eval on install to avoid some fairly nasty potential attacks (our ruby -e is kinda bad enough but at least cannot modify the shell).

I believe that `ruby -e`, or `sh -c`, or `eval` are all equally nasty. Any of these commands could start a new interactive shell that appears normal to the user but is somehow malicious.

**Comment by MikeMcQuaid** [comment]
> I believe that ruby -e, or sh -c, or eval are all equally nasty. Any of these commands could start a new interactive shell that appears normal to the user but is somehow malicious.

In theory, yes, but in practice there's a higher risk of us accidentally and unintentionally modifying the shell environment with `eval` of our install script so I'd rather we avoid it and instead e.g. output to tell people to run `eval /tmp/foo` after the fact.
