### ISSUE TITLE
'brew bottle --root-url" fails with "undefined method `start_with?'"

### ISSUE THREAD

**Issue by FiloSottile** [Homebrew/brew#4790]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
https://gist.github.com/FiloSottile/b9c9fa8db08025101d7f93bbf9ad20b5

To help us debug your issue please explain:
- What you were trying to do (and why)

Bottling my Formula `filosottile/musl-cross/musl-cross` as I did for previous versions, at revision FiloSottile/homebrew-musl-cross@fca606c53f8448b67513f957f654543e9e58055b.

- What happened (include command output)

```
$ brew bottle --root-url musl-cross
==> Determining filosottile/musl-cross/musl-cross bottle rebuild...
==> Bottling musl-cross--0.9.7_1.high_sierra.bottle.1.tar.gz...
==> Detecting if musl-cross--0.9.7_1.high_sierra.bottle.1.tar.gz is relocatable...
Error: undefined method `start_with?' for true:TrueClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
(erb):2:in `block in bottle_output'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/erb.rb:864:in `eval'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/erb.rb:864:in `result'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:186:in `bottle_output'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:373:in `bottle_formula'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:91:in `block in bottle'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:90:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:90:in `bottle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

- What you expected to happen

A successful `brew bottle` execution.

- Step-by-step reproduction instructions (by running `brew` commands)

```
brew install --build-bottle --verbose filosottile/musl-cross/musl-cross
brew bottle --root-url musl-cross
```

Note that `brew bottle` without `--root-url` works, and while it's an issue with an unofficial Formula, nowhere it invokes `start_with?`.

**Comment by DomT4** [comment]
If you replace `--root-url` with `--root-url="https://dl.bintray.com/filosottile/generic"` it should work, I believe?

**Comment by FiloSottile** [comment]
It does indeed. I suppose it should still fail more gracefully if a naked `--root-url` is not supported anymore?

**Comment by DomT4** [comment]
To be honest I can't remember us ever formally supporting naked `--root-url`s being passed, but I could be misremembering.

Not personally opposed to the idea of trying to fall over a little more helpfully than the command currently manages. Something like this may work:
```diff
diff --git a/Library/Homebrew/dev-cmd/bottle.rb b/Library/Homebrew/dev-cmd/bottle.rb
index 90b3bcc45..8fc8e839c 100644
--- a/Library/Homebrew/dev-cmd/bottle.rb
+++ b/Library/Homebrew/dev-cmd/bottle.rb
@@ -85,6 +85,13 @@ module Homebrew
       flag   "--root-url"
     end
 
+    if args.root_url.empty? || args.root_url !~ %r{^(https|http|ftp)://}
+      odie <<~EOS
+        root-url seems to be invalid. The syntax is:
+          brew bottle --root-url=<URL> <formula>
+      EOS
+    end
+
     return merge if args.merge?
     ensure_relocation_formulae_installed!
     ARGV.resolved_formulae.each do |f|
```

CC @MikeMcQuaid for thoughts.

**Comment by DomT4** [comment]
```
~> brew bottle --root-url bearssl 
==> Determining domt4/crypto/bearssl bottle rebuild...
==> Bottling bearssl--0.6.mojave.bottle.tar.gz...
==> Detecting if bearssl--0.6.mojave.bottle.tar.gz is relocatable...
Error: undefined method `start_with?' for true:TrueClass
(erb):2:in `block in bottle_output'
```

```
~> brew bottle --root-url= bearssl
==> Determining domt4/crypto/bearssl bottle rebuild...
==> Bottling bearssl--0.6.mojave.bottle.tar.gz...
==> Detecting if bearssl--0.6.mojave.bottle.tar.gz is relocatable...
./bearssl--0.6.mojave.bottle.tar.gz
  bottle do
    root_url ""
    cellar :any
    sha256 "4e24998cc333e286f0f0447cbafc28a579c1a90b69c1b50e58f613fc13bdf5b9" => :mojave
  end
```
