### ISSUE TITLE
brew reinstall <formula> --HEAD doesn't install deps defined in head

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#4793]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install some formula with some build-only deps defined only in `devel`/`head`, remove those deps and try to reinstall formula.
- What happened (include command output)
```
$ brew reinstall gnu-tar --HEAD 
==> Reinstalling gnu-tar 
Error: /usr/local/opt/automake not present or broken
Please reinstall automake. Sorry :(
```
- What you expected to happen
`brew` installs build-only deps for head spec.
- Step-by-step reproduction instructions (by running `brew` commands)
```
$ brew install gnu-tar --HEAD
<skip>
$ brew uninstall autoconf automake
<skip>
$ brew reinstall gnu-tar --HEAD 
```

<details>
<summary>brew config</summary>

```
HOMEBREW_VERSION: 1.7.2-104-g449c3ff
ORIGIN: https://github.com/Homebrew/brew
HEAD: 449c3ffac3aee77886bf9e703e3fe25cbe4cd1cc
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3ccc276850d6382efb72bde8b42aceebd8066927
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_EMOJI: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1533942731
CLT headers: N/A
Xcode: 10.0 => /Applications/Xcode-beta.app/Contents/Developer
XQuartz: 2.7.11 => /opt/X11
```
</details>
<details>
<summary>brew doctor</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Applications/Wine Staging.app/Contents/Resources/wine/bin/xslt-config
  /Applications/Wine Staging.app/Contents/Resources/wine/bin/xml2-config

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: You are using macOS 10.14.
We do not provide support for this pre-release version.
You will encounter build failures and other breakages.
Please create pull-requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this pre-release version,
you are responsible for resolving any issues you experience.
```
</details>

**Comment by MikeMcQuaid** [comment]
`--HEAD` is not a documented flag for `reinstall`, sorry.
