### ISSUE TITLE
brew install go 

### ISSUE THREAD

**Issue by int03h** [Homebrew/brew#48]
Trying to brew install go on debian SID .. (I did try it on testing too) .. it does compile natively on the OS, not problem. ( tried with and without export HOMEBREW_BUILD_FROM_SOURCE=1 ) 

I compiled ethereum-cpp successfully but I can't get GETH ( go version to compile because of it's dependency on golang ) 
- [ Yes ] Ran `brew update` and retried your prior step?
- [ Yes ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ No ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

https://gist.github.com/1b3367f01fd05e67af2c027782cab3f9

/tmp/go20160408-29305-1dninkg/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/tmp/go20160408-29305-1dninkg/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
# cmd/go
/tmp/go20160408-29305-1dninkg/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/tmp/go20160408-29305-1dninkg/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
thanks! 

int

**Comment by xu-cheng** [comment]
This issue was moved to Linuxbrew/linuxbrew#1057
