### ISSUE TITLE
Installing Astrill from China

### ISSUE THREAD

**Issue by gillesdreu23** [Homebrew/brew#4802]
Hello, I have installed Astrill successfully on my iPhone, but I would like to install it on my macbook pro as well.

My problem is, I am in China and it doesn't seems to work... 

Here's the message received in Terminal after installing homebrew

curl: (7) Failed to connect to www.astrill.com port 443: Operation timed out
Error: Download failed on Cask 'astrill' with message: Download failed: https://www.astrill.com/downloads/astrill-setup-mac.pkg

What should I do !

Thanks for your fast reply !

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template. Sorry, we cannot help with local connectivity issues.
