### ISSUE TITLE
error: unknown option `shallow-since=refs/tags/1.7.3' on MacOS 10.11

### ISSUE THREAD

**Issue by jeroen** [Homebrew/brew#4818]
As of [this commit](https://github.com/Homebrew/brew/commit/bdc2458c1512c836cc6fb6a2663c5e317d8c99b6) by @reitermarkus my El Capitain server shows an error about an unsupported `git` feature. This version of MacOS has `git version 2.10.1 (Apple Git-78)`.

Homebrew is installed in a non-default location. Below a minimal reproducible example:

```sh
BREWDIR="/tmp/homebrew"
export HOMEBREW_TEMP="/tmp/hbtmp"
mkdir -p $BREWDIR
curl -fsSL https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C $BREWDIR
$BREWDIR/bin/brew install --force-bottle ffmpeg
```

![screen shot 2018-09-04 at 3 18 46 pm](https://user-images.githubusercontent.com/216319/45033808-fc83b980-b055-11e8-9565-4fc9db976558.png)

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
$BREWDIR/bin/brew config
HOMEBREW_VERSION: >=1.7.1 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 733fa0ce6f3b3f47d84dff88e65e93a16c8de191
Core tap last commit: 31 minutes ago
HOMEBREW_PREFIX: /private/tmp/homebrew
HOMEBREW_REPOSITORY: /private/tmp/homebrew
HOMEBREW_CELLAR: /private/tmp/homebrew/Cellar
HOMEBREW_CACHE: /tmp/hbtmp
HOMEBREW_TEMP: /private/tmp/hbtmp
HOMEBREW_GIT: git
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /private/tmp/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: N/A
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

```
$BREWDIR/bin/brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

Warning: Homebrew's bin was not found in your PATH.
Consider setting the PATH for example like so
  echo 'export PATH="/private/tmp/homebrew/bin:$PATH"' >> ~/.bash_profile
```

**Comment by MikeMcQuaid** [comment]
@jeroen Can you see if this is fixed by https://github.com/Homebrew/brew/pull/4828? Please note that El Capitan will no longer be supported when Mojave is released (expected this month).

**Comment by jeroen** [comment]
It's not fixed.

**Comment by MikeMcQuaid** [comment]
@jeroen Can you try to run `brew install git` and see if that resolves the problem for you temporarily?

**Comment by jeroen** [comment]
Well in my setup `brew` is not on the `PATH` so that  complicates things a bit perhaps. After installing `git` the original error seems to be gone but I do see:

```
warning: templates not found in /usr/local/Cellar/git/2.18.0/share/git-core/templates
Initialized empty Git repository in /private/tmp/homebrew/.git/
fatal: Unable to find remote helper for 'https'
fatal: Unable to find remote helper for 'https'
```

Anyway the original error is not the end of the world, things still seem to work. 

What is the benefit of using `--shallow-since` the latest tag, as opposed to `--depth=1`?

**Comment by MikeMcQuaid** [comment]
> What is the benefit of using --shallow-since the latest tag, as opposed to --depth=1?

It's needed for `git describe` to return correct results which in turn is needed for our cache migration logic.

> Well in my setup brew is not on the PATH so that complicates things a bit perhaps

Yes, that's an unsupported configuration.
