### ISSUE TITLE
1.7.3 curl fails to download to cache dir when downloads dir is missing

### ISSUE THREAD

**Issue by eedwards-sk** [Homebrew/brew#4820]
in `1.7.3`, downloaded files are now being staged in a subdirectory of the `brew --cache` directory, called `downloads/` and a symlink is created where the file originally would have been downloaded

it appears that in some situations, when the `downloads/` cache subdirectory does not exist, calls to `curl` when the file is being downloaded will fail, as curl is not creating the directory automatically

compare paths between `1.7.2` and `1.7.3`:

path/filename 1.7.2

```
bash-util-1.0@1.0.2--1.0.2.high_sierra.bottle.tar.gz.incomplete
```

path/filename 1.7.3

```
downloads/6c9812555a180612fe7895d63111ffe8ef825465f754ea7bafdc1b02acfd9450--bash-util-1.0@1.0.2-1.0.2.high_sierra.bottle.tar.gz.incomplete
```

```
==> Downloading s3://snapkitchen-homebrew-bottles/bash-util/repo/bash-util-1.0@1.0.2-1.0.2.high_sierra.bottle.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/1.X.Y\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /opt/concourse/local/worker/volumes/live/35d4426a-c997-4e19-7949-285e522dbf3a/volume/homebrew-downloads/downloads/6c9812555a180612fe7895d63111ffe8ef825465f754ea7bafdc1b02acfd9450--bash-util-1.0@1.0.2-1.0.2.high_sierra.bottle.tar.gz.incomplete <SNIPPED AUTH>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file 
Warning: /opt/concourse/local/worker/volumes/live/35d4426a-c997-4e19-7949-285e5
Warning: 22dbf3a/volume/homebrew-downloads/downloads/6c9812555a180612fe7895d631
Warning: 11ffe8ef825465f754ea7bafdc1b02acfd9450--bash-util-1.0@1.0.2-1.0.2.high
 45 35613   45 16360    0     0  17793      0  0:00:02 --:--:--  0:00:02 17782
curl: (23) Failed writing body (0 != 16360)
Error: Failed to download resource "bash-util-1.0@1.0.2"
Download failed: s3://snapkitchen-homebrew-bottles/bash-util/repo/bash-util-1.0@1.0.2-1.0.2.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

See my following comment below for a simple repro.

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [N\A] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [N\A] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [N\A] ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by eedwards-sk** [comment]
If anyone else hits this (likely anyone using non-default cache dir or doing CI like me), I'm attempting to work around it by generating a temp directory with a shorter prefix as my cache dir:

```bash
global__temp_dir="$(mktemp -d '/tmp/snap-dev-ci.XXXXXXXX')" || exit 64
readonly global__temp_dir

readonly work__homebrew_download_dir="${global__temp_dir}/hbdl"
```

(note that I'm specifying the full directory and template with `-d`, this ensures it goes in `/tmp` rather than the much longer default osx temp path e.g. `/var/folders/dm/2_68m_h13h5dxq2f05wsc47c0000gq/T/`)

this leaves me with a download cache dir of

```
/tmp/snap-dev-ci.wsaKS173/hbdl/
```

compared to my previous prefix of

```
/opt/concourse/local/worker/volumes/live/baee6e97-8093-4bdf-4867-51b47ac9e5a2/volume/homebrew-downloads/
```

the down side is that my ci tool normally cleans up its workspace, but since this is outside of that, I have to track and clean it up manually (ensuring I still remove it even if one of the steps fails)

**Comment by eedwards-sk** [comment]
I did some further testing and I believe the issue is due to missing `downloads` directory inside the cache dir

curl apparently does not create the directory automatically

I was able to repro pretty easily by doing this

```
mkdir /tmp/homebrew-test
cd /tmp/homebrew-test
```

working:

```
/usr/bin/curl -q --show-error --user-agent Homebrew/1.X.Y\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /tmp/homebrew-test/file-directly-in-dir.incomplete http://example.com/
```

fails (adds `downloads/` to output path`):

```
/usr/bin/curl -q --show-error --user-agent Homebrew/1.X.Y\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /tmp/homebrew-test/downloads/file-in-downloads-dir.incomplete http://example.com/
```

**Comment by eedwards-sk** [comment]
I can confirm the current workaround is to create the `downloads/` directory manually before running any brew commands.

Here's a snippet from an execution run in bash where I check for the folder and create it when it's found missing:

```
+ HOMEBREW_CACHE=/opt/concourse/local/worker/volumes/live/89deabe7-b041-4d00-775d-86d3db13ad90/volume/homebrew-downloads
+ [[ -e /opt/concourse/local/worker/volumes/live/89deabe7-b041-4d00-775d-86d3db13ad90/volume/homebrew-downloads/downloads ]]
+ mkdir -p /opt/concourse/local/worker/volumes/live/89deabe7-b041-4d00-775d-86d3db13ad90/volume/homebrew-downloads/downloads
```

once I made this change, I was able to proceed building on 1.7.3 just as I did on 1.7.2

To fix this in homebrew, perhaps we can check for existence of the `downloads/` directory and create it if missing?

**Comment by eedwards-sk** [comment]
This also breaks clients using `1.7.3`, they also have to manually create the cache `downloads/` dir, or downloads fail e.g.:

```
(snap-api) Tue Sep 04 04:52 PM SnapAPI $ brew upgrade snapkitchen/private/snap-dev
==> Upgrading 1 outdated package, with result:
snapkitchen/private/snap-dev 1.1.0 -> 1.2.0
==> Upgrading snapkitchen/private/snap-dev 
==> Downloading s3://snapkitchen-homebrew-bottles/snap-dev/repo/snap-dev-1.2.0.high_sierra.bottle.3.tar.gz
Warning: Failed to create the file 
Warning: /Users/NCONROY/Library/Caches/Homebrew/downloads/e215e5d9f13d40c2690e1
Warning: 4ce764da2acd3973a536e2e3ae0462f4311e975cc16--snap-dev-1.2.0.high_sierr
Warning: a.bottle.3.tar.gz.incomplete: No such file or directory
#################################                                         46.2%
curl: (23) Failed writing body (0 != 16360)
Error: Failed to download resource "snap-dev"
Download failed: s3://snapkitchen-homebrew-bottles/snap-dev/repo/snap-dev-1.2.0.high_sierra.bottle.3.tar.gz
Warning: Bottle installation failed: building from source.
```

**Comment by reitermarkus** [comment]
So which `brew` command actually reproduces this?

**Comment by nodefortytwo** [comment]
I have replicated this as well. Installing a tap from a github private github release resulted in:

```
Warning: Failed to create the file 
Warning: /Users/richard.burgess/Library/Caches/Homebrew/downloads/563f9cd4a029d
Warning: c7581df147fe5a89fe4320a523565197c6a6bba9265eee6d7b6--dazn-cli_0.0.1-rc
Warning: 7_darwin_amd64.tar.gz.incomplete: No such file or directory
```
this tap uses `GitHubPrivateRepositoryReleaseDownloadStrategy`

which may or may not be related.

creating the downloads directory fixes the problem.
