### ISSUE TITLE
BREW on Sierra

### ISSUE THREAD

**Issue by highacid** [Homebrew/brew#484]
==> ./configure --prefix=/usr/local/Cellar/unixodbc/2.3.4 --enable-gui=no
Last 15 lines from /Users/kosmos/Library/Logs/Homebrew/unixodbc/01.configure:
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for gawk... (cached) awk
checking for bison... bison -y
checking for style of include used by make... GNU
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/unixodbc-20160710-28379-1np8aua/unixODBC-2.3.4':
_**configure: error: cannot run C compiled programs.**_
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

**Comment by MikeMcQuaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting
> If reporting this issue please do so at (not Homebrew/brew):
> https://github.com/Homebrew/homebrew-core/issues
> 
> Warning: You are using OS X 10.12.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.

Closing as you didn't seem to read any of that.
