### ISSUE TITLE
Bug in brew cleanup <formula>

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/brew#4856]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

When I run `brew upgrade neovim --fetch-HEAD && brew cleanup neovim`, I found that the cleanup step fails to cleanup the old version of the neovim. 

In fact, `brew cleanup <formula>` will fail whenever the formula is a HEAD/devel spec, or other corner cases. The culprit comes from:
https://github.com/Homebrew/brew/blob/a2f5355ca8d9dea11542cfcc7b64d09d3dc9e333/Library/Homebrew/cleanup.rb#L169

There should be some formula resovling logic similar to `ARGV.resovled_formulae`.

https://github.com/Homebrew/brew/blob/a2f5355ca8d9dea11542cfcc7b64d09d3dc9e333/Library/Homebrew/extend/ARGV.rb#L57-L85

```
$ brew config
HOMEBREW_VERSION: 1.7.3-77-ga2f5355
ORIGIN: https://github.com/Homebrew/brew
HEAD: a2f5355ca8d9dea11542cfcc7b64d09d3dc9e333
Last commit: 69 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6e742cd0efbb32dd6539c661adee4bf636f77146
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEVELOPER: true
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: true
HOMEBREW_NO_AUTO_UPDATE: true
HOMEBREW_SANDBOX: true
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

**Comment by MikeMcQuaid** [comment]
@xu-cheng Is this a regression e.g. can you reproduce this with `1.7.0` or `1.6.0`? Thanks!

**Comment by xu-cheng** [comment]
It is a regression since https://github.com/Homebrew/brew/commit/03b93da2969914193a16b52b273f4b0fb1850c82

**Comment by MikeMcQuaid** [comment]
@xu-cheng Thanks for checking!
