### ISSUE TITLE
Unable to uninstall specific version of formulae

### ISSUE THREAD

**Issue by mcandre** [Homebrew/brew#4859]
`brew` doesn't appear to support at signs (`@`) when instructing `brew uninstall` to remove a specific version of a formula :/

The currently recommended workaround, `rm -rf <path>` is lazy and risky. If I wanted to manage packages at such a low level, I wouldn't bother using Homebrew in the first place.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
