### ISSUE TITLE
Can't uninstall lua because clingo (NOT INSTALLED) depends on lua

### ISSUE THREAD

**Issue by mcandre** [Homebrew/brew#4860]
Trace:

```console
$ brew missing
clingo: lua

$ brew uninstall clingo
Error: No such keg: /usr/local/Cellar/clingo
```

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
