### ISSUE TITLE
Brew command doesn't work.

### ISSUE THREAD

**Issue by Lokidiscool** [Homebrew/brew#4869]
I was trying to do the command, 'brew install python'. This resulted in '-bash: brew: command not found' appearing. I have found that no brew commands are working and need help.

**Comment by iMichka** [comment]
From the issue template:

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
