### ISSUE TITLE
Consider replacing Jenkins with Azure Pipelines

### ISSUE THREAD

**Issue by cglong** [Homebrew/brew#4878]
With the [introduction of Azure DevOps](https://azure.microsoft.com/en-us/blog/introducing-azure-devops/), Microsoft has announced that their build and release pipeline, called [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/), is [free for OSS projects](https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/).

I know there was earlier talk of [wanting to migrate off Jenkins to a hosted setup](https://news.ycombinator.com/item?id=17708548), and this seems like it may address the concerns brought up in that comment. Specifically:

* Support for multiple (10, specifically) parallel jobs with unlimited build minutes
* Support for hosted macOS agents as well as [bringing your own](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=vsts)

There are obviously other solutions as well (such as Travis or Circle CI), but neither of those seem to offer the level of customization that Azure Pipelines provides 😄 For full disclosure, I do work at Microsoft, but not on this product; I'm just a happy user!

**Comment by MikeMcQuaid** [comment]
@cglong Can I mark this as "fixed" because we are considering it? 😆. Seriously, though, we're in some discussions with Microsoft about tweaking this so better suits our needs but it's looking good for some repos (including this one) as a starting test point.

**Comment by cglong** [comment]
Haha, that's awesome news! And sure, I mostly wanted to use this issue to raise awareness of it, so glad to hear that ball's already rolling 🙂

**Comment by monouser7dig** [comment]
@cglong 
> unlimited build minutes

Does this mean one job can run more than one hour or just that you can run as many jobs as you want? 

Thanks

**Comment by cglong** [comment]
@MikeMcQuaid Nice! It looks like, from those PRs, that it fits nicely 😄 I'd be curious to know what the additional requirements are for homebrew-core, but understand if that's a more private discussion for the Azure DevOps people you've been working with.

@monouser7dig You'd want to ask the Azure DevOps team to be sure, but [from this article](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs-vsts?view=vsts), it sounds like you can run as many jobs as you want (up to 10 at a time). If you use the build machines hosted by Microsoft, the build phase can take up to 30 minutes, but if you host the build agent yourself, there's no time limit. They also sound pretty flexible about the 30 minute cap if you work with them 😄

**Comment by MikeMcQuaid** [comment]
> I'd be curious to know what the additional requirements are for homebrew-core, but understand if that's a more private discussion for the Azure DevOps people you've been working with.

It's not too private! Basically beefy workers, longer timeouts and support for newer and older macOS versions.

**Comment by monouser7dig** [comment]
>  longer timeouts 

https://www.reddit.com/r/programming/comments/9enz31/announcing_azure_pipelines_with_unlimited_cicd/e5sda7y/

seems to get you up to 360minutes 

(maybe this excuses my interruption 😃)

**Comment by cglong** [comment]
> beefy workers, longer timeouts and support for newer and older macOS versions

@MikeMcQuaid Ah, that makes sense! You may be able to explore migrating your existing MacStadium infrastructure to self-hosted agents, but I get wanting to remove that dependency if you're moving to a cloud-based CI anyway 🙂

**Comment by MikeMcQuaid** [comment]
@cglong Yeh, that's the fallback option.
