### ISSUE TITLE
Add delimiters to numbers in brew info's analytics output

### ISSUE THREAD

**Issue by zgracem** [Homebrew/brew#4889]
## A detailed description of your proposed feature

Since #4830, <kbd>brew info</kbd> displays formula analytics, but for formulae with > 1,000 downloads, the count is printed without delimiters:

```
install: 3223 (30d), 7946 (90d), 33655 (365d)
install_on_request: 2773 (30d), 6605 (90d), 26234 (365d)
```

I propose adding commas before each group of three digits, after which the above output would be:

```
install: 3,223 (30d), 7,946 (90d), 33,655 (365d)
install_on_request: 2,773 (30d), 6,605 (90d), 26,234 (365d)
```

## The motivation for the feature

To improve readability for formulae with > 1,000 downloads/year.

The [Ruby Style Guide](https://github.com/rubocop-hq/ruby-style-guide#underscores-in-numerics) acknowledges that long numeric literals are hard to read, and recommends underscore notation in code (`1_000_000` vs. `1000000`). While Homebrew's prose obviously isn't meant to follow code style, the point about readability is well-taken in any medium (imho).

## How the feature would be relevant to at least 90% of Homebrew users

Assuming at least 90% of Homebrew users have analytics enabled (I admit I do not know how to check this), this feature would improve the output of <kbd>brew info</kbd> for the top 2,660 packages listed [here](https://formulae.brew.sh/analytics/install/365d/).

## What alternatives to the feature you have considered

* Maintaining the current format. The outcome of this alternative would be lower-than-optimal readability in the output of <kbd>brew info</kbd>.
* Changing the output of `output_analytics` to a tabular format, with rows corresponding to install type and columns corresponding to date ranges. This alternative would produce (arguably) even better readability, at the (prohibitive, imo) cost of more complicated code.
* No other options were considered.

* * *

I believe this could be accomplished by changing [`cmd/info.rb` @ L219](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/info.rb#L219) from:

```
"#{results.values.inject("+")} (#{range})"
```

to:

```
"#{number_readable(results.values.inject("+"))} (#{range})"
```

I'm only a hobbyist at Ruby (and a Git n00b besides), but I'd be happy to try making a pull request to the above effect if there's interest.

**Comment by colindean** [comment]
I'm overall 👍 on this but it ignores user locale settings.

**Comment by zgracem** [comment]
> it ignores user locale settings

This gave me pause too. I'd certainly prefer if it didn't. Is there somewhere else that Homebrew behaves differently based on locale? I could use that as a starting point.

**Comment by zgracem** [comment]
I just discovered that `utils.rb` has [`number_readable`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils.rb#L461), and have edited my proposal above.

However, @colindean's objection still applies: `number_readable` ignores user locale too. But that would be a much more sensible place to add l10n than here.

**Comment by MikeMcQuaid** [comment]
@zgracem 👍 to using `number_readable` here. 
Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Eventually it'd be good to import this from e.g. ActiveSupport instead.

Thanks!

**Comment by zgracem** [comment]
Closed by https://github.com/Homebrew/brew/commit/1b45666518289edbd7f54460e7d858ac7a09ad97. :tada:
