### ISSUE TITLE
Installation helper for command line tools written in Swift

### ISSUE THREAD

**Issue by pepibumur** [Homebrew/brew#4893]
The Swift Package Manager (SPM) allows creating command line tools that are compiled into binaries that can be distributed and installed on someone's machine.

Those packages can be distributed using Homebrew. The formula needs to compile the package, copy the binaries and frameworks to the right folders, and make some changes on the binary so that it knows the path where the frameworks have been moved to.

Since that process looks pretty much the same for any Swift package that wants to be distributed via Homebrew, I think there could be a helper method on the Formula DSL that:

- Checks  whether Xcode exists in the system, something that is necessary to compile the tool.
- Run the steps mentioned above.

This feature would make it easier for Swift devs to distribute their tools via Homebrew. I can contribute to the project and code it myself, but I first wanted to get some feedback and thoughts from the maintainers beforehand.

**Comment by colindean** [comment]
This sounds like what Homebrew already does for the Python and Rust
ecosystems, among others. Seems like adding another would be OK.

**Comment by pepibumur** [comment]
> This sounds like what Homebrew already does for the Python and Rust
ecosystems, among others. Seems like adding another would be OK.

That's great to hear. Where can I look at in the codebase to see how those are implemented?

**Comment by MikeMcQuaid** [comment]
> Checks whether Xcode exists in the system, something that is necessary to compile the tool.

@pepibumur Homebrew already does this. You can restrict this to specific versions already with e.g. `depends_on :xcode => ["9.0", :build]`.

> The formula needs to compile the package, copy the binaries and frameworks to the right folders, and make some changes on the binary so that it knows the path where the frameworks have been moved to.

Let's see this pattern at use in at least 10+ formulae in https://github.com/homebrew/homebrew-core/ before we start thinking about a DSL or similar. A DSL should be a last resort rather than a first one.

Also, in future please always fill out the feature request template.

Thanks!

**Comment by pepibumur** [comment]
> Let's see this pattern at use in at least 10+ formulae in https://github.com/homebrew/homebrew-core/ before we start thinking about a DSL or similar. A DSL should be a last resort rather than a first one.

Totally agree.

> Also, in future please always fill out the feature request template.

Thanks for the suggestion. I'll do that the next time.
