### ISSUE TITLE
Install bottle from homebrew/bottles

### ISSUE THREAD

**Issue by hijxf** [Homebrew/brew#4896]
Seems either 1. this isn't possible and requires manual curl/wget the tarball then put into /Cellar/ or 2. there is no documentation on how to do this.

### Description
Install bottle from homebrew's bintray.

### Motivation
Install more versions of a particular library, than what's in the formula. (e.g. boost).

### Feature Relevency
I'm sure people need older versions of dependencies, not just what is on the upstream formula.

### Alternatives
Building from source without brew or using bottles manually.

**Comment by MikeMcQuaid** [comment]
> Install more versions of a particular library, than what's in the formula.

https://docs.brew.sh/Versions explains how our versions work.

**Comment by hijxf** [comment]
thank you. sorry about that.

**Comment by MikeMcQuaid** [comment]
No need to apologise!
