### ISSUE TITLE
`brew upgrade` not respecting `--build-from-source` anymore

### ISSUE THREAD

**Issue by smancill** [Homebrew/brew#4903]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

**What you were trying to do (and why)**

Upgrade a formula installed with `--build-from-source`.

**What happened (include command output)**

The bottle gets installed instead of rebuilding from source.

**What you expected to happen**

Download the sources and rebuild the formula, which worked fine before (not sure until how long ago, maybe a month).

**Step-by-step reproduction instructions (by running `brew` commands)**

```
$ brew info git
git: stable 2.19.0 (bottled), HEAD
Distributed revision control system
https://git-scm.com
/usr/local/Cellar/git/2.19.0 (1,498 files, 34.9MB) *
  Built from source on 2018-09-11 at 17:31:19
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb

$ brew upgrade git
==> Upgrading 1 outdated package, with result:
git 2.19.0 -> 2.19.0_1
==> Upgrading git
==> Downloading https://homebrew.bintray.com/bottles/git-2.19.0_1.sierra.bottle.tar.gz
##################                                                        26.0%^C
```

The same with a couple of another packages (like vim). Previous upgrades did rebuild from source.

---

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

$ brew config
HOMEBREW_VERSION: 1.7.4-52-g04e3344
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 04e3344f8e5831a4c7efd9863d00be9e288f2203
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d196e1615d1f5953daa2a7537ca9d960bd4f9a9e
Core tap last commit: 49 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT: git
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_NO_GITHUB_API: 1
HOMEBREW_VISUAL: vim
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
`--build-from-source` is not a documented argument for `brew upgrade`. It's likely in Git's case you previously specified an option and there are no options on that formula any more.
