### ISSUE TITLE
Error on install root:  gcc was built with a different C++ standard library (libstdc++ from clang)

### ISSUE THREAD

**Issue by AwooBear** [Homebrew/brew#4904]
When I try to install root I get this error:
`root dependency gcc was built with a different C++ standard library (libstdc++ from clang). This may cause problems at runtime.`

And when I try to run the root it gives me errors:
```
input_line_1:1:10: fatal error: 'new' file not found
input_line_3:37:10: fatal error: 'string' file not found
input_line_9:1:10: fatal error: 'iostream' file not found
```

I have tried `brew reinstall $(brew deps root)` but it does not help.

**Comment by intrepid42** [comment]
@AwooBear Same issue here.. How did you solve it?

**Comment by XueqiLi** [comment]
> @AwooBear Same issue here.. How did you solve it?

Nope, I repost it here https://github.com/Homebrew/homebrew-core/issues/32112

**Comment by intrepid42** [comment]
Ah ok, thank you!

**Comment by calemhoffman** [comment]
Also same issue, tried similar solutions as previously posted to no avail...
`HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f239b7a62790cfb4f33bda9aab7597d43f1b1e3b
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3bceae3ba10334345a6f14b7e3777080c00a179d
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
HOMEBREW_MACOS_VERSION_NUMERIC: 101400
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
`

**Comment by XueqiLi** [comment]
@calemhoffman Hi, can you repost it on [here](https://github.com/Homebrew/homebrew-core/issues/32112)? Thank you!
