### ISSUE TITLE
Neo4J gets uninstalled and then comes back installed after computer was asleep

### ISSUE THREAD

**Issue by Stargator** [Homebrew/brew#4905]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? (**Note:** Cannot update Xcode, company laptop I don't have the rights)
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) - **Trying to uninstall neo4j and not have it come back.**

- What happened (include command output)
Summary: I uninstalled neo4j, but after the computer would be asleep for a period of time (30 minutes to an hour), neo4j would be listed as installed. **It should be noted:** that the version of neo4j remains the same version that was uninstalled (3.3.4), despite that a newer version is available.

Later as proof that neo4j was removed:
```bash
09:57 $ brew leaves
bash-completion@2
bash-git-prompt
curl
dart-lang/dart/dart
dart-lang/dart/dart@1
git
gnupg
go
gradle
ideviceinstaller
ios-deploy
maven
neo4j
nginx
node@8
openssl@1.1
putty
ruby
scala@2.11
yarn
```
```bash
10:36 $ brew uninstall -f neo4j && brew cleanup -s && brew prune
Uninstalling neo4j... (37.8KB)
```

```bash
10:37 $ brew cleanup -s
Removing: /Users/johnmcmahon/Library/Caches/Homebrew/curl--7.61.1.high_sierra.bottle.tar.gz... (972.0KB)
==> This operation has freed approximately 972.0KB of disk space.
```
```bash
10:37 $ brew update
Already up-to-date.
```
```bash
10:38 $ brew list
adns			dart@1			gnupg			ios-deploy		libksba			libyaml			node@8			pcre2			scala@2.11
bash			encfs			gnutls			libassuan		libplist		libzip			npth			pinentry		sqlite
bash-completion@2	gdbm			go			libffi			libtasn1		maven			openssl			putty			usbmuxd
bash-git-prompt		gettext			gradle			libgcrypt		libunistring		nettle			openssl@1.1		python@2		yarn
boost			git			icu4c			libgpg-error		libusb			nginx			p11-kit			readline
dart			gmp			ideviceinstaller	libimobiledevice	libxml2			node			pcre			ruby
```
```bash
11:21 $ brew list
adns			dart@1			gnupg			ios-deploy		libksba			libyaml			node@8			pcre2			scala@2.11
bash			encfs			gnutls			libassuan		libplist		libzip			npth			pinentry		sqlite
bash-completion@2	gdbm			go			libffi			libtasn1		maven			openssl			putty			usbmuxd
bash-git-prompt		gettext			gradle			libgcrypt		libunistring		nettle			openssl@1.1		python@2		yarn
boost			git			icu4c			libgpg-error		libusb			nginx			p11-kit			readline
dart			gmp			ideviceinstaller	libimobiledevice	libxml2			node			pcre			ruby
```
```bash
12:31 $ brew list
adns			dart@1			gnupg			ios-deploy		libksba			libyaml			node			pcre			ruby
bash			encfs			gnutls			libassuan		libplist		libzip			node@8			pcre2			scala@2.11
bash-completion@2	gdbm			go			libffi			libtasn1		maven			npth			pinentry		sqlite
bash-git-prompt		gettext			gradle			libgcrypt		libunistring		neo4j			openssl			putty			usbmuxd
boost			git			icu4c			libgpg-error		libusb			nettle			openssl@1.1		python@2		yarn
dart			gmp			ideviceinstaller	libimobiledevice	libxml2			nginx			p11-kit			readline
```

- What you expected to happen
I expect that once I uninstalled neo4j, it would not come back unless I choose to install it.

- `brew config`
```bash
17:59 $ brew config
HOMEBREW_VERSION: 1.7.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88e69f5a8835bd9a05c37dadfcc25b3e9dada340
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f4bdb425cff8aacc5c0332d04f2ad191bbc9883a
Core tap last commit: 34 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_141
macOS: 10.13.1-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.2
XQuartz: N/A
```

- `brew doctor`
```bash
18:01 $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Xcode (9.2) is outdated.
Please update to Xcode 9.4 (or delete it).
Xcode can be updated from the App Store.
```

- Step-by-step reproduction instructions (by running `brew` commands)
  1. `brew uninstall neo4j && brew cleanup -s`
  1.  Put the computer to sleep. Leave the computer and come back after an hour or two.
  1. `brew list` (Observe that neo4j is back)

**Comment by Stargator** [comment]
I wanted to ensure I got all the information before having this issue open.

**Comment by MikeMcQuaid** [comment]
> * I uninstalled neo4j, but after the computer would be asleep for a period of time (30 minutes to an hour), neo4j would be listed as installed. **It should be noted:** that the version of neo4j remains the same version that was uninstalled (3.3.4), despite that a newer version is available.

Homebrew never runs without you asking it to. Another service or script must be running Homebrew. Figuring that out isn't something we can help you with, sorry.

**Comment by Stargator** [comment]
@MikeMcQuaid No service/script should be using Homebrew, but thank you.

**Comment by Stargator** [comment]
FYI, I don't know what changed in the last 18 hours or so, but this has been resolved:

```bash
brew uninstall -f neo4j && brew cleanup -s && brew prune && brew update && brew outdated
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
node ✔                       b2-tools                     docker-compose               euler-py                     goolabs                      monero                       skaffold                     ydcv
ansible-cmdb                 bde                          docker-squash                eye-d3                       howdoi                       mongo-orchestration          stormpath-cli                ykman
arcade-learning-environment  blueutil                     docutils                     fobis                        iproute2mac                  ocrmypdf                     urweb                        yle-dl
atdtool                      consul                       duo_unix                     ford                         jfrog-cli-go                 percol                       watchman
awslogs                      credstash                    eralchemy                    gitless                      livestreamer                 pius                         watson
azure-cli                    dnstwist                     erlang@17                    golang-migrate               mdv                          sceptre                      wireshark
node (10.11.0) < 10.12.0
```

What's missing is before `Updated Formulae", there would be this `Uninstalling neo4j... (37.8KB)`
