### ISSUE TITLE
Brew failed to install completely on Mac OS 10.7 server

### ISSUE THREAD

**Issue by JBVeenstra** [Homebrew/brew#491]
Xserve with 10.7.5
Tried to install Brew with command:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Output:
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown admin /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/bin/chgrp admin /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Counting objects: 509, done.
remote: Compressing objects: 100% (453/453), done.
remote: Total 509 (delta 29), reused 365 (delta 27), pack-reused 0
Receiving objects: 100% (509/509), 795.23 KiB, done.
Resolving deltas: 100% (29/29), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
HEAD is now at 4a73249 Merge pull request #487 from MikeMcQuaid/requirement-tweaks
/usr/local/Library/ENV/scm/git:30:in `exec': Permission denied - /usr/local/bin/git (Errno::EACCES)
	from /usr/local/Library/ENV/scm/git:30:in `exec'
	from /usr/local/Library/ENV/scm/git:42
/usr/local/Library/ENV/scm/git:30:in `exec': Permission denied - /usr/local/bin/git (Errno::EACCES)
	from /usr/local/Library/ENV/scm/git:30:in `exec'
	from /usr/local/Library/ENV/scm/git:42
Error: Git is unavailable
Failed during: /usr/local/bin/brew tap homebrew/core

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?

Output:
/usr/local/Library/ENV/scm/git:30:in `exec': Permission denied - /usr/local/bin/git (Errno::EACCES)
	from /usr/local/Library/ENV/scm/git:30:in `exec'
	from /usr/local/Library/ENV/scm/git:42
/usr/local/Library/ENV/scm/git:30:in `exec': Permission denied - /usr/local/bin/git (Errno::EACCES)
	from /usr/local/Library/ENV/scm/git:30:in `exec'
	from /usr/local/Library/ENV/scm/git:42
Error: Git must be installed and in your PATH!

- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

Output:
/usr/local/Library/ENV/scm/git:30:in `exec': Permission denied - /usr/local/bin/git (Errno::EACCES)
	from /usr/local/Library/ENV/scm/git:30:in `exec'
	from /usr/local/Library/ENV/scm/git:42
/usr/local/Library/ENV/scm/git:30:in `exec': Permission denied - /usr/local/bin/git (Errno::EACCES)
	from /usr/local/Library/ENV/scm/git:30:in `exec'
	from /usr/local/Library/ENV/scm/git:42
/usr/local/Library/ENV/scm/git:30:in `exec': Permission denied - /usr/local/bin/git (Errno::EACCES)
	from /usr/local/Library/ENV/scm/git:30:in `exec'
	from /usr/local/Library/ENV/scm/git:42
/usr/local/Library/ENV/scm/git:30:in `exec': Permission denied - /usr/local/bin/git (Errno::EACCES)
	from /usr/local/Library/ENV/scm/git:30:in `exec'
	from /usr/local/Library/ENV/scm/git:42
Error: Git is unavailable
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core -q

xserve:homebrew admin$ which git
/usr/bin/git
xserve:homebrew admin$ git version
git version 1.7.12.4 (Apple Git-37)

Any ideas? I need brew to install gnumeric

Regards,
JB

**Comment by MikeMcQuaid** [comment]
> Permission denied - /usr/local/bin/git (Errno::EACCES)

This is your issue.

**Comment by MikeMcQuaid** [comment]
You probably need to remove that file or fix permissions on it (and all of `/usr/local`)

**Comment by JBVeenstra** [comment]
/usr/local/bin/git is a directory.
and what are the right permissions for it? (and /usr/local)

**Comment by MikeMcQuaid** [comment]
If it's a directory you may want/need to remove it. CC @xu-cheng for thoughts on better handling this.

**Comment by xu-cheng** [comment]
#493

**Comment by JBVeenstra** [comment]
I removed the directory /usr/local/bin/git 
then ran the command "brew update"
that worked
command "brew doctor"
All seems to be fine.
"brew install gnumeric" is running now flawlessly

Thanks guys, you save my life (well, sort of)

Cheers,
JB
