### ISSUE TITLE
TLS issues on https://homebrew.bintray.com

### ISSUE THREAD

**Issue by deployable** [Homebrew/brew#4911]
- [x] are reporting a bug others will be able to reproduce and not asking a question.
- [x] ran a `brew` command and reproduced the problem with multiple formulae? 
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

Trying to `brew install` anything results in various TLS errors for [homebrew.bintray.com](https://homebrew.bintray.com) and `brew` reverts to installing from source. 

`curl https://homebrew.bintray.com/bottles/curl-7.61.1.el_capitan.bottle.tar.gz`

Various TLS errors are thrown by curl on different systems 
- "Invalid certificate chain" 
- "unable to get local issuer certificate"
- "Peer's Certificate issuer is not recognized"

SSL Labs reports the certificate chain is incomplete:
https://www.ssllabs.com/ssltest/analyze.html?d=homebrew.bintray.com&s=52.39.244.1

Chrome and Firefox produce similar errors.

**Comment by deployable** [comment]
Looks like the certificate has been updated to include the complete certificate chain rather than just the *.bintray.com  certificate, all working now.

**Comment by iMichka** [comment]
I confirm that there were some transient problems, I also saw them for the linuxbrew domain. Looks they fixed their certificate now.
