### ISSUE TITLE
brew copies entire .git directory when building head

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#4914]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
```brew install boost --HEAD -vd```
- What happened (include command output)
brew copies entire `.git` directory
```cp -pR /Users/yurikoles/Library/Caches/Homebrew/boost--git/.git/. /private/tmp/d20180916-36770-1g2zcr1/.git```
- What you expected to happen
brew ignores `.git` 
- Step-by-step reproduction instructions (by running `brew` commands)
```brew install boost --HEAD -vd```

**Comment by MikeMcQuaid** [comment]
Is this a recent change? Why is this a problem? What do you think should be done instead?

**Comment by reitermarkus** [comment]
I think this is intentional because some build scripts expect to be run inside an intact repo.
