### ISSUE TITLE
Link GNU netcat to gnc

### ISSUE THREAD

**Issue by NightMachinary** [Homebrew/brew#4916]
Since there a multitude of implementations of netcat around, we benefit greatly by linking brew's GNU netcat to gnc (I mean something in the lines of ` ln -s  /home/linuxbrew/.linuxbrew/Cellar/netcat/0.7.1/bin/netcat /usr/bin/gnc`). This way we can freely use gnc in our scripts and keep them portable across OSes.
PS: It'd be a nice feature to support custom links for brew packages in general; I currently used ` ln -s  /home/linuxbrew/.linuxbrew/Cellar/netcat/0.7.1/bin/netcat /usr/bin/gnc`, but this would not work with upgrades, removals, and the such.

**Comment by MikeMcQuaid** [comment]
If this is something that is supported by the GNU netcat buildsystem we'll review a pull request to amend the formula accordingly. Otherwise, I'd suggest creating your own alias.

Please always fill out the issue template in future.
