### ISSUE TITLE
Add a flag to remove data when uninstalling

### ISSUE THREAD

**Issue by zlotnika** [Homebrew/brew#4925]
When uninstalling tools and applications (especially `cask` things), sometimes I'd like to completely remove its data. Examples of this is when I say uninstall `postgres` or `virtualbox`, I might want to remove the databases and virtual machine data.

I (and I assume many others) trust homebrew to touch things in my system over whatever installer I may find lying around. It currently cannot fully reverse installations, and I don't think this goes with the ethos of a package manager.

I propose adding a flag (maybe `--full` or something) that does whatever is needed in order to get your system to how it was before the first installation of the thing. Of course, the full uninstallation would have to be a script specified in the formula (since objects might be added during installation and/or during usage of the tool). The default (so that it doesn't break all existing formulae) could just be to do nothing different.

**Comment by colindean** [comment]
Casks make an attempt to uninstall cleanly with an `uninstall` block but formulae do not. I'm not sure that formulae, in general, should make this attempt beyond _perhaps_ conveying that the program creates content that lives outside of the installation directory in the `caveats` block. The possibilities are pretty wide.

If formulae were more containerized, this would be more effective. Until such a time, I don't think it's wise to make a change outside of installation directory, lest there be a deleterious effect on user data.

**Comment by zlotnika** [comment]
I recommend that this not be a default behavior. Maybe it would be more clear to call the flag `--delete-user-data`. Further, I think it's totally reasonable to require a password, an answer "yes" to an "this would delete blah blah", and maybe a `--dry-run` option.

**Comment by MikeMcQuaid** [comment]
Please always fill out the feature request template.

In this case this command already exists: `brew cask zap`.

**Comment by zlotnika** [comment]
Wonderful, thank you!
