### ISSUE TITLE
brew install command on homepage doesn't work for tcsh

### ISSUE THREAD

**Issue by kvijaykiran** [Homebrew/brew#4931]
Hello,
The brew install command that's on homebrew home page works only with bash shell by default. Those who set their terminal to tcsh will either need to change to bash shell or use an appropriate change in command.

Can the homepage be updated to reflect that the command works only on bash terminals, and that users should change to it if their default shell is tcsh?

Thanks,
Vijay.

**Comment by colindean** [comment]
Can you suggest a version that that will work with tcsh _and_ bash?

**Comment by colindean** [comment]
Messing around with it myself, I think

    /usr/bin/ruby -e "`curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install`"

would work. tsch doesn't like `$()` subcommands.

**Comment by MikeMcQuaid** [comment]
@kvijaykiran This is intentional. If you're using a non-Bash compatible shell you should be able to figure out how to adjust the terminal command accordingly (or run `bash` temporarily).
