### ISSUE TITLE
Install History

### ISSUE THREAD

**Issue by stanislavkozlovski** [Homebrew/brew#4953]
- Have a way to see what you've recently installed in historical order
- Motivation is pretty simple: I personally installed something yesterday but forgot the tool's name. I wanted to quickly see what it is and if there was a history command I could find it in a second.
- Every user can be interested in what he's installed in order. He might want to uninstall some tools that were temporarily installed
- Alternative: Have a way to sort the `--list` output via time installed

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by chdiza** [comment]
You can just `cd` to the cellar and do `ls -l` and look at the dates.  Or do the corresponding thing in the Finder.

**Comment by stanislavkozlovski** [comment]
Is there a reason to not have a quick way to do it through the tool? Especially since most people using it don't know of the internals and can't navigate to the cellar in seconds

**Comment by colindean** [comment]
Related: https://github.com/Homebrew/homebrew-bundle/issues/365

**Comment by stanislavkozlovski** [comment]
`brew list -l` seems to do the job

**Comment by MikeMcQuaid** [comment]
Passing on this due to the workarounds above and this being the first request for this feature. Thanks for the issue anyway @stanislavkozlovski!
