### ISSUE TITLE
Reinstalling `moreutils --without-parallel` still conflicts with `parallel`

### ISSUE THREAD

**Issue by optix2000** [Homebrew/brew#4956]
Copied from https://github.com/Homebrew/homebrew-core/issues/32208

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
% brew doctor
Your system is ready to brew.
 % brew config
HOMEBREW_VERSION: 1.7.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: d639559c4de48faad79d3ecb1ec84dc851ea66f2
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4bd74e69ba025f6123e7e31498c830e9b9e37ed2
Core tap last commit: 36 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Reinstall `moreutils`
- What happened (include command output)
```
% brew reinstall moreutils
==> Reinstalling moreutils --without-parallel
Error: Cannot install moreutils because conflicting formulae are installed.
  parallel: because Both install a `parallel` executable.

Please `brew unlink parallel` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```
- What you expected to happen
Similar to https://github.com/Homebrew/homebrew-core/issues/23837, where brew should be able to understand there is no conflict and reinstall without the need for `--force`
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install parallel
brew install moreutils --without-parallel
brew reinstall moreutils
```

**Comment by optix2000** [comment]
Depending on how the usage is intended to be, this may or may not be a bug.

Running the reinstall with the correct flags works as expected
```
brew reinstall moreutils --without-parallel
```

Running a straight reinstall without any flags is a bit more ambiguous.
Arguably, running `brew reinstall moreutils` could imply a reinstall of `moreutils` with default options, a la _with_ `parallel`. 
As there's no `--with-parallel` option to negate `--without-parallel`, this would make sense if the intent was to reinstall it _with_ `parallel`.

On the flip side, if the intent of `brew reinstall moreutils` is to reinstall with current flags, this would mean the only way to install `moreutils` _with_ `parallel` would be to completely uninstall `moreutils` and then install it from scratch.

Can someone clarify what the intended usage of `brew reinstall` is supposed to be? Is it supposed to use existing flags, or does it imply a reinstall with default flags.

**Comment by MikeMcQuaid** [comment]
> On the flip side, if the intent of `brew reinstall moreutils` is to reinstall with current flags

It is, yes.
