### ISSUE TITLE
Upgrade for GO results in segfault

### ISSUE THREAD

**Issue by andywenk** [Homebrew/brew#4961]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I did `brew update` and then `brew upgrade`

- What happened (include command output)

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/pathname.rb:388: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin9.0]

See also the crash report. While doing brew upgrade the bug arose at 

[ruby_2018-09-21-155044_andwen-5.crash.txt](https://github.com/Homebrew/brew/files/2405664/ruby_2018-09-21-155044_andwen-5.crash.txt)
[ruby_2018-09-21-160243_andwen-5.crash.txt](https://github.com/Homebrew/brew/files/2405665/ruby_2018-09-21-160243_andwen-5.crash.txt)
```
==> Upgrading go
==> Downloading https://homebrew.bintray.com/bottles/go-1.11.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/d2/d2dfd9846bc03498dd69c01eaccc0a3018a66d00864d7433d70f07645aac6a40?__gda__=exp=1537538495~hmac=7c1b9617b9ebe14ca0d68f3b649a76803116c07cf28829ebc40809670c84254c&response-content-disposition
######################################################################## 100.0%
==> Pouring go-1.11.high_sierra.bottle.tar.gz
==> Caveats
A valid GOPATH is required to use the `go get` command.
If $GOPATH is not specified, $HOME/go will be used by default:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
==> Summary
🍺  /usr/local/Cellar/go/1.11: 9,273 files, 403.9MB
```
- What you expected to happen

hat GO will be upgraded

- Step-by-step reproduction instructions (by running `brew` commands)

as mentioned above

**Comment by MikeMcQuaid** [comment]
> * [ ]  ran `brew config` and `brew doctor` and included their output with your issue?

We need this.

**Comment by andywenk** [comment]
why are you closing this issue? It took me half an hour to get all info and I hoped it would help you.  Telling me that I missed sth is ok. But closing it because of that is simply demotivating.

**Comment by MikeMcQuaid** [comment]
> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.

**Comment by MikeMcQuaid** [comment]
That's why; we can't help you if you don't provide the information. You're asking us for help and we can only do that if you provide the information. We can consider reopening this once we have the information that we need and if it's not a duplicate of an existing issue.

**Comment by MikeMcQuaid** [comment]
In this case it's almost certainly a duplicate of https://github.com/Homebrew/brew/issues/4923

**Comment by andywenk** [comment]
thanks for coming back to me. I followed the instructions in #4923 and ran `brew doctor`, `brew update` and `brew upgrade` again without an error. Thanks @MikeMcQuaid
