### ISSUE TITLE
Fake install option

### ISSUE THREAD

**Issue by liyishuai** [Homebrew/brew#4963]
## Description
`brew install --fake D` registers the installation of `D` without actually performing anything.

## Motivation
Suppose package `P` depends on packages `D1 D2 D3 ...`, and the user hopes to use their own `D1` rather than that from Homebrew, they could ask Homebrew to believe that `D1` was installed.

## Relevance
Many packages have very common and customizable dependencies *e.g.* Emacs, Python. Some users might prefer using the native Python on macOS; some have already installed Emacs via Cask.

## Alternatives
The user could use `brew install D2 D3 ...; brew install --ignore-dependencies P`, but that could be as verbose as `P`'s dependency list.

**Comment by MikeMcQuaid** [comment]
Homebrew (deliberately) doesn't support using Homebrew-packaged dependencies from outside Homebrew, sorry.

**Comment by MikeMcQuaid** [comment]
@liyishuai In that case we will throw various warnings/errors, though, and be able to detect that if you file other issues.
