### ISSUE TITLE
Mounty.dmg was not quarantined properly.

### ISSUE THREAD

**Issue by lbdhr** [Homebrew/brew#4965]
Hi, I was trying to install Mounty for NTFS on my MAC, but once I ran the command `brew cask install mounty`, there is an error occurred `Mounty.dmg was not quarantined properly`. I have tried the conmmand `brew doctor` and ran `brew prune`, than `brew update`. 
I even tried the command `cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask && git stash pop`, but the problem cannot disappear.  The details are shown below:
```
Updating Homebrew...
Ignoring path homebrew-cask/
To restore the stashed changes to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask && git stash pop'
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Satisfying dependencies
==> Downloading http://mounty.app/releases/Mounty.dmg
==> Downloading from https://mounty.app/releases/Mounty.dmg
######################################################################## 100.0%
==> No SHA-256 checksum defined for Cask 'mounty', skipping verification.
==> Installing Cask mounty
==> Purging files for version latest of Cask mounty
Error: /Users/uav/Library/Caches/Homebrew/downloads/272ff9c177655c8fe36be3c3c6659733ffb515071b938743f7b06e3a58747831--Mounty.dmg was not quarantined properly.
```

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
