### ISSUE TITLE
[FR]brew install --stable

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#4969]
Please replace this section with:
- a detailed description of your proposed feature
Please allow to switch back to stable via `brew install $formula --stable`
- the motivation for the feature
We already have `--devel` and `--HEAD` switches, lack of `--stable` confuses newbies.
- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)
Provide convenience way to switch back to stable version without knowledge of `brew switch`, because it isn't documented in `brew install --help`
- what alternatives to the feature you have considered
`brew switch $formula`,  `brew uninstall $formula; brew link $formula` but this is too complicated ways, as for newbies.
We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
Please fill out the feature request template. Additionally, please provide some example output and commands you've tried to run.

**Comment by yurikoles** [comment]
```
brew install gcc --HEAD
<experiment, then go back>
brew install gcc --stable
```

**Comment by MikeMcQuaid** [comment]
> Please fill out the feature request template
> Additionally, please provide some example output

Please do these or this will be closed, thanks.

In the above case you could use `brew switch` or `brew uninstall; brew link`. Where would you expect that to be noted? Does this work as expected when going from stable to devel or HEAD to devel?

**Comment by yurikoles** [comment]
@MikeMcQuaid 
Sorry for delaying, I had updated OP.

**Comment by yurikoles** [comment]
@MikeMcQuaid yes it works, but this way is not so obvious.

**Comment by MikeMcQuaid** [comment]
@yurikoles What commands did you try and what worked?

**Comment by yurikoles** [comment]
I had found that switching back from `devel` or `HEAD` to stable via switch or `uninstall` && `link` works only if stable version was intalled prior. I I have `devel` or `HEAD` without stable, then I should unlink or uninstall it first. So I think `--stable` switch will allow to install stable version alongside with unstable without unlinking or uninstalling unnstable.

**Comment by yurikoles** [comment]
Simply doing reinstall of unstable formula does reinstall with same unstable flag. But we can do reinstall of stable or unstable with switching to different flag, except reinstalling back to stable.

**Comment by MikeMcQuaid** [comment]
@yurikoles So to be explicit:

- `brew switch` does allow you to switch between versions but is not obvious
- `brew uninstall` allows you to switch between versions but is not obvious

What about `brew install --devel` or `brew install --HEAD`?

**Comment by yurikoles** [comment]
```
$ brew install tor
==> Downloading https://homebrew.bintray.com/bottles/tor-0.3.4.8.mojave.bottle.tar.gz
Already downloaded: /Users/yurikoles/Library/Caches/Homebrew/downloads/cd6282c5acb31b936da1bf82ac168cb589d2202eadca8bbce7b8aef6c9eefdc5--tor-0.3.4.8.mojave.bottle.tar.gz
==> Pouring tor-0.3.4.8.mojave.bottle.tar.gz
==> Caveats
To have launchd start tor now and restart at login:
  brew services start tor
Or, if you don't want/need a background service you can just run:
  tor
==> Summary
/usr/local/Cellar/tor/0.3.4.8: 21 files, 11.4MB

$ brew install --devel tor
Error: tor 0.3.4.8 is already installed
To upgrade to 0.3.5.2-alpha, run `brew upgrade tor`
```

**Comment by yurikoles** [comment]
```brew reinstall --devel tor``` works

**Comment by MikeMcQuaid** [comment]
What about `brew upgrade --devel tor`? Also, same thing in reverse would be interesting to try too. I think this may be something where even just improving the messaging could be enough.

**Comment by yurikoles** [comment]
Yes, it works, but I want to remind you about #4793

**Comment by yurikoles** [comment]
```
$ brew upgrade --devel tor
<...>
$ brew upgrade tor -vd
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tor.rb
Error: tor 0.3.5.2-alpha already installed
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:58:in `exit'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:58:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
@yurikoles Please try to be more verbose. I'm struggling to understand what you mean just from command output.

**Comment by yurikoles** [comment]
>Also, same thing in reverse would be interesting to try too.
I had tried installing devel, then `upgrade`.

**Comment by MikeMcQuaid** [comment]
Sorry @yurikoles I'm afraid I cannot understand what you're trying to say here. I'm afraid I'm going to ask you to not submit any more feature requests to Homebrew.
