### ISSUE TITLE
jenkins.brew.sh expired certificate and currently unreachable due to HSTS

### ISSUE THREAD

**Issue by skunkworker** [Homebrew/brew#4973]
Earlier tonight while trying to see why a jenkins homebrew-core pull request failed I was greeted with a warning due to an invalid HTTPS certificate:
```
jenkins.brew.sh uses an invalid security certificate. The certificate expired on September 23, 2018, 5:35:22 PM GMT-6. The current time is September 23, 2018, 11:45 PM. 
```

Currently I am unable to visit due to HSTS being enabled on the server with Chrome 69.

**Comment by MikeMcQuaid** [comment]
`nginx` needed restarted. Fixed now, thanks.
