### ISSUE TITLE
a lot of error after updating to mojave

### ISSUE THREAD

**Issue by xhaythemx** [Homebrew/brew#4975]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
to update homebrew after installing mojave
- What happened (include command output)
brew update
Ignoring bigdecimal-1.3.5 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.5
Ignoring bigdecimal-1.3.5 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.5
- What you expected to happen
brew to update 
- Step-by-step reproduction instructions (by running `brew` commands)

brew config
Ignoring bigdecimal-1.3.5 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.5
HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f239b7a62790cfb4f33bda9aab7597d43f1b1e3b
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe7334d3c60777926ec25d42e40546601ea3c662
Core tap last commit: 89 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
HOMEBREW_MACOS_VERSION_NUMERIC: 101400
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2
macOS: 10.14-x86_64
CLT: N/A
Xcode: 10.0
XQuartz: N/A

brew doctor
Ignoring bigdecimal-1.3.5 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.5
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

**Comment by yoavmmn** [comment]
+1.
After updating to Mojave I get this when running `brew doctor`:
```
Warning: Missing Homebrew/brew git origin remote.

Without a correctly configured origin, Homebrew won't update
properly. You can solve this by adding the Homebrew remote:
  git -C "/usr/local/Homebrew" remote add origin https://github.com/Homebrew/brew.git

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install


Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun```

I only tried setting the remote origin of the git repository but I got `fatal: remote origin already exists.`.
Meanwhile I can't upgrade or install any packages.
Hope to get a fix soon :)

My config:
```
HOMEBREW_VERSION: 1.7.6-6-g899bfbc
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: (none)
Core tap HEAD: (none)
Core tap last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.14-x86_64
CLT: N/A
Xcode: N/A
XQuartz: N/A
```

**Comment by rockymadden** [comment]
This worked for me. Open Xcode, go to Preferences, go to Locations, update the Command Line Tools in the drop down to Xcode 10.0.

**Comment by yoavmmn** [comment]
> try `xcode-select --install` in Terminal.

Worked for me. Thanks!

**Comment by MikeMcQuaid** [comment]
Run `xcode-select --install`, rerun `brew doctor` and fix any permissions errors using the instructions it gives you.

**Comment by FradSer** [comment]
`xcode-select --install` does't work for me. Reinstall ruby doesn't works, too.
Try `sudo chown -R $(whoami) /usr/local/lib/ruby/gems/*` to fix permissions error, but same problem cones.

**Comment by MikeMcQuaid** [comment]
@FradSer What is the specific error you're seeing?

**Comment by kirkegaard** [comment]
I just did a fresh install of Mojave and installed xcode as the first thing. Then installed brew using the installer off brew.sh. `brew doctor` is telling me that command line tools are outdated and `xcode-select --install` says command line tools are already installed and that i should use Software Update to install updates. Software Updates says i've got the newest version already. Ive also selected the newest version inside xcode > preferences > locations.

I think the installer might be installing an old version of command line tools which cause some kind of confligt since the installer tried to install command line tools for High Sierra.

**Comment by MikeMcQuaid** [comment]
@FradSer None of those errors are from Homebrew.

**Comment by FradSer** [comment]
@kirkegaard I've uninstall command line tools with `sudo rm -rf /Library/Developer/CommandLineTools` and reinstall it, still get the the warnings.

**Comment by monouser7dig** [comment]
```
$ brew update
Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Already up-to-date.
```

I'm also getting this on a secondary install (like not on my main Mac) and have not yet found a solution that worked.

**Comment by jonleopard** [comment]
This isn't really an issue of Homebrew. Running `brew update` seems to trigger something that causes the following to display:

```
$ brew update
Ignoring bigdecimal-1.3.5 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.5
Ignoring bigdecimal-1.3.5 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.5
```

I've tried running the suggested `gem pristine bigdecimal --version 1.3.5`

```
$ gem pristine bigdecimal --version 1.3.5
Restoring gems to pristine condition...
Building native extensions. This could take a while...
Restored bigdecimal-1.3.5
```

After running, I still get the same results. 


Has anyone else found a solution for this yet?

**Comment by mbbroberg** [comment]
Hey @monouser7dig and @jonleopard, I had success with Mike's solution: 

> Run `xcode-select --install`, rerun `brew doctor` and fix any permissions errors using the instructions it gives you.

Any luck for you two?

**Comment by mbbroberg** [comment]
@FradSer if I can help you reproduce the issue I'd be happy to do so. I'd be curious to see the error on `xcode-select` because that seems to be the key.

**Comment by Chen-Hu** [comment]
> ```
> $ brew update
> Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
> Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
> Already up-to-date.
> ```
> I'm also getting this on a secondary install (like not on my main Mac) and have not yet found a solution that worked.
same issuse

**Comment by luisdavim** [comment]
I also have this problem, here's what I've tried:
```
$ brew update
Ignoring bigdecimal-1.3.3 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.3
Ignoring bigdecimal-1.3.3 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.3
Already up-to-date.
```
```
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
```
$ /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/gem pristine bigdecimal --version 1.3.3
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["bigdecimal"] = 1.3.3
```
```
$ /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/gem install bigdecimal --version 1.3.3
Fetching: bigdecimal-1.3.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing bigdecimal:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/bigdecimal-1.3.3/ext/bigdecimal
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby -r ./siteconf20180928-38536-1gab5h7.rb extconf.rb
checking for labs() in stdlib.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/$(RUBY_BASE_NAME)
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:535:in `block in try_link0'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:532:in `try_link0'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:1051:in `block in have_func'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/mkmf.rb:1050:in `have_func'
        from extconf.rb:22:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/extensions/universal-darwin-9/2.3.0-static/bigdecimal-1.3.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/bigdecimal-1.3.3 for inspection.
Results logged to /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/extensions/universal-darwin-9/2.3.0-static/bigdecimal-1.3.3/gem_make.out
```

**Comment by luisdavim** [comment]
and here's the log:
```
$ cat /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/extensions/universal-darwin-9/2.3.0-static/bigdecimal-1.3.3/mkmf.log
"cc -o conftest -I/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0/universal-darwin9.0 -I/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0/ruby/backward -I/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0 -I.  -I/usr/local/opt/portable-readline/include -I/usr/local/opt/portable-libyaml/include -I/usr/local/opt/portable-openssl/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -pipe conftest.c  -L. -L/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib -L/usr/local/opt/portable-readline/lib -L/usr/local/opt/portable-libyaml/lib -L/usr/local/opt/portable-openssl/lib -L. -Wl,-search_paths_first -fstack-protector -L/usr/local/lib -L/usr/local/opt/portable-readline/lib -L/usr/local/opt/portable-libyaml/lib -L/usr/local/opt/portable-openssl/lib   -arch x86_64 -arch i386   -lruby-static -framework Foundation  -lpthread -ldl -lobjc "
In file included from conftest.c:1:
In file included from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0/ruby.h:33:
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0/ruby/ruby.h:929:1: warning: attribute 'deprecated' is ignored, place
it after "struct" to apply attribute to type declaration [-Wignored-attributes]
DEPRECATED_TYPE(("RClass is internal use only"),
^
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0/universal-darwin9.0/ruby/config.h:128:49: note: expanded from macro 'DEPRECATED_TYPE'
#define DEPRECATED_TYPE(mesg,x) __attribute__ ((deprecated mesg)) x
                                                ^
1 warning generated.
ld: warning: directory not found for option '-L/usr/local/opt/portable-readline/lib'
ld: warning: directory not found for option '-L/usr/local/opt/portable-libyaml/lib'
ld: warning: directory not found for option '-L/usr/local/opt/portable-openssl/lib'
ld: warning: directory not found for option '-L/usr/local/opt/portable-readline/lib'
ld: warning: directory not found for option '-L/usr/local/opt/portable-libyaml/lib'
ld: warning: directory not found for option '-L/usr/local/opt/portable-openssl/lib'
In file included from conftest.c:1:
In file included from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0/ruby.h:33:
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0/ruby/ruby.h:929:1: warning: attribute 'deprecated' is ignored, place
it after "struct" to apply attribute to type declaration [-Wignored-attributes]
DEPRECATED_TYPE(("RClass is internal use only"),
^
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0/universal-darwin9.0/ruby/config.h:128:49: note: expanded from macro 'DEPRECATED_TYPE'
#define DEPRECATED_TYPE(mesg,x) __attribute__ ((deprecated mesg)) x
                                                ^
1 warning generated.
ld: warning: directory not found for option '-L/usr/local/opt/portable-readline/lib'
ld: warning: directory not found for option '-L/usr/local/opt/portable-libyaml/lib'
ld: warning: directory not found for option '-L/usr/local/opt/portable-openssl/lib'
ld: warning: directory not found for option '-L/usr/local/opt/portable-readline/lib'
ld: warning: directory not found for option '-L/usr/local/opt/portable-libyaml/lib'
ld: warning: directory not found for option '-L/usr/local/opt/portable-openssl/lib'
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libdl.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libdl.tbd
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libpthread.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libpthread.tbd
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libobjc.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libobjc.tbd (2 slices)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//Foundation.framework/Foundation.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//Foundation.framework/Foundation.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

I think the problem is:
```
missing required architecture i386
```

**Comment by luisdavim** [comment]
this is a problem with the portable version of ruby that comes with Homebrew, if I use the version of ruby that I have installed on my mac I can install `bigdecimal`:

```
$ gem install bigdecimal
Building native extensions. This could take a while...
Successfully installed bigdecimal-1.3.5
Done installing documentation for bigdecimal after 0 seconds
1 gem installed
```

**Comment by davosian** [comment]
> this is a problem with the portable version of ruby that comes with Homebrew, if I use the version of ruby that I have installed on my mac I can install `bigdecimal`:
> 
> ```
> $ gem install bigdecimal
> Building native extensions. This could take a while...
> Successfully installed bigdecimal-1.3.5
> Done installing documentation for bigdecimal after 0 seconds
> 1 gem installed
> ```

While this installs bigdecimal-1.3.5, it looks like brew is not picking it up, resulting in the same error message:

`Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2`

**Comment by luisdavim** [comment]
it doesn't pick it up because it uses it's own embedded ruby, not the one from your system.

**Comment by davosian** [comment]
so that means that it actually is an issue related to homebrew and cannot be resolved by some other measure other than an update for homebrew, right?

**Comment by luisdavim** [comment]
Yeah

**Comment by ramet** [comment]
same conclusion from my side.

**Comment by MikeMcQuaid** [comment]
I'm also on Mojave, a Ruby developer and cannot reproduce this using either Homebrew's Ruby or the system Ruby with Homebrew.

If someone can submit a pull request or provide step-by-step instructions that are reproducible on my or a clean Mojave install we can look at this further.

**Comment by ramet** [comment]
Here is my brew config:
```
HOMEBREW_VERSION: 1.7.6-33-g1ee8c60
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1ee8c6083470208c4c81becee053ab59093ef3ba
Last commit: 41 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9a9147bcb6593a5457e321deee77439533e17b99
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181, 1.8.0_172
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

brew doctor says that my 'command line tools' should be updated:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```

But I have the last version available with App Store...
```
xcode-select -v
xcode-select version 2354
```

My homebrew repository is clean and updated:
```
cd `brew --repository`

git status
Sur la branche master
rien à valider, la copie de travail est propre

1ee8c608 (HEAD -> master, origin/master) Merge pull request #4994 from MikeMcQuaid/config-hide-optional
```

But when I ask for 'brew update' or 'brew upgrade', there are the following warnings:
```
Ignoring bigdecimal-1.3.4 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.4
Ignoring bigdecimal-1.3.4 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.4
```

The ruby 'bigdecimal' package is installed (1.3.5, but I also switch on 1.3.4) in the system repository.
When I try to install or pristine this package with the portable version of ruby provided by HomeBrew, I have the same errors than @luisdavim  in the current issue.

It is not critical, since everything is working !

**Comment by MikeMcQuaid** [comment]
> brew doctor says that my 'command line tools' should be updated:

You should do that and try again.

**Comment by ramet** [comment]
Since `xcode-select` and "Software Update" complain that 'command line tools' is already installed and up-to-date, I download the .dmg for "Command Line Tools (macOS 10.14) for Xcode 10" from:
https://developer.apple.com/download/more/
I a force to install the package.
Unfortunately, I still have the issue...

**Comment by FradSer** [comment]
@ramet Same issue as me.
```
$ xcode-select -v
xcode-select version 2354.
```
`version 2354` is the newest version. Reinstalling `xcode-select` has nothing help.

**Comment by MikeMcQuaid** [comment]
That's not the version. The version is from `brew config`.

**Comment by ndreca** [comment]
Workaround solution for me ( I had ruby 2.5.1 installed by brew due to vim dependency)
- uninstalled vim, ruby and restarted terminal (so now system ruby is active, v 2.3.7)
- installed bigdecimal: sudo gem install bigdecimal
- reinstalled vim (and with it ruby 2.5.1 as dep)

**Comment by ramet** [comment]
The solution from @ndreca is also working for me:

- First uninstall rbenv with dep on ruby-build

- Then run `sudo gem install bigdecimal`
```
Ignoring bigdecimal-1.3.4 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.4
Building native extensions. This could take a while...
Successfully installed bigdecimal-1.3.5
Parsing documentation for bigdecimal-1.3.5
Done installing documentation for bigdecimal after 0 seconds
1 gem installed
```

- And also `sudo gem pristine bigdecimal --version 1.3.4`
```
Ignoring bigdecimal-1.3.4 because its extensions are not built. Try: gem pristine bigdecimal --version 1.3.4
Restoring gems to pristine condition...
Building native extensions. This could take a while...
Restored bigdecimal-1.3.4
```

- I can brew without warnings :)

**Comment by jonleopard** [comment]
@ndreca's solution worked for me as well. Remove brew installed rbenv, install bigdecimal, and then reinstall rbenv. 

```
$ brew remove rbenv
$ sudo gem install bigdecimal
$ brew install rbenv
```

**Comment by bmfkai** [comment]
> I solved the problem by identifying the gem command actually used by brew, which is (for me, with mojave just installed) under /usr/bin/gem. Use this absolute path
> sudo /usr/bin/gem pristine bigdecimal --version 1.3.3
> sudo /usr/bin/gem pristine bigdecimal --version 1.3.4
> 
> and everything's fine now. Hope it helps

This worked for me, thanks!

**Comment by FradSer** [comment]
@davosian 🙏
`sudo /usr/bin/gem pristine bigdecimal --version 1.3.2` works for me.

**Comment by MikeMcQuaid** [comment]
Locking this thread to avoid more "me too" comments and it seems the above solutions are resolving this for people.
