### ISSUE TITLE
Sending SIGTERM/SIGSTOP does not cancel "brew install"

### ISSUE THREAD

**Issue by kevinburke** [Homebrew/brew#4976]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem? (Not relevant)
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? (Not relevant)
- [ ] ran `brew config` and `brew doctor` and included their output with your issue? 

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

I was trying to install version 2.9 of kubernetes-helm (the current version of kubernetes-helm is v2.10). I ran:

```
cd $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core
git log -p # find commit where version 2.9.1 of helm was installed
git checkout 78d64252f30a12b6f4b3ce29686ab5e262eea812
```

Then I ran:

```
brew install kubernetes-helm
```

With the hopes of being able to run:

```
brew pin kubernetes-helm
```

However, when I ran `brew install`, I got the following output:

```
$ brew install kubernetes-helm
Updating Homebrew...
```

I tried to kill this process by sending `ctrl+c` and then `ctrl+\` to the terminal. With most programs, this terminates the running command. However, homebrew ignored these signals and kept trying to update the repository. 

It would be good if Homebrew stopped doing what it was doing when a user issued `ctrl+c` to the program. You can reproduce by checking out a sufficiently old commit and then running `brew install`.

Alternatively, explain how to install a version from an old commit without updating Homebrew first. The documentation for `brew install -h` does not explain how to install without updating Homebrew first. I found the answer on [another issue](https://github.com/Homebrew/brew/issues/1670#issuecomment-267096602) - set `HOMEBREW_NO_AUTO_UPDATE=1` in the environment before installing.

**Comment by kevinburke** [comment]
I don't think my Homebrew config is going to be relevant to this issue but just in case.

```
$ brew config
HOMEBREW_VERSION: 1.7.6-6-g899bfbc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 899bfbcaf184bdda50f635e11c269675d3b7cda5
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 78d64252f30a12b6f4b3ce29686ab5e262eea812
Core tap last commit: 4 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_152, 1.8.0_131
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 9.1
XQuartz: N/A
```

**Comment by MikeMcQuaid** [comment]
Can you try to update to Xcode 10 and see if you can reproduce this? I've seen this previously but I think it's a version mismatch issue.

If you can reproduce this with `brew update` alone that would be helpful; particularly if `brew update --debug --verbose` makes it reproducible and what it's hanging on when you Ctrl-C.
