### ISSUE TITLE
reopen #2861

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#4977]
Please reopen #2861, it had returned.

**Comment by commitay** [comment]
https://github.com/Homebrew/brew/pull/2861 is a pull request, it can't be reopened.

**Comment by MikeMcQuaid** [comment]
@yurikoles If you open any more issues without filling in the issue template you will be blocked from the Homebrew organisation. Please be more considerate, detailed and verbose when you create issues and ask yourself if a comment on another issue would be better. Thanks ❤️
