### ISSUE TITLE
Failure to bottle due to "Failed changing dylib ID"

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#4979]
This currently only occurs with `carthage`, but I believe it might be a Ruby MachO issue. While trying to bottle `carthage`, either the current version or the new update (https://github.com/Homebrew/homebrew-core/pull/32403):

```
Error: Failed changing dylib ID of /usr/local/Cellar/carthage/0.30.1/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle
  from @rpath/Tentacle.framework/Versions/A/Tentacle
    to @@HOMEBREW_PREFIX@@/opt/carthage/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle
Error: Failed changing dylib ID of /usr/local/Cellar/carthage/0.30.1/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle
  from @rpath/Tentacle.framework/Versions/A/Tentacle
    to /usr/local/opt/carthage/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle
Error: Updated load commands do not fit in the header of /usr/local/Cellar/carthage/0.30.1/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle. /usr/local/Cellar/carthage/0.30.1/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle needs to be relinked, possibly with -headerpad or -headerpad_max_install_names
```

Not sure how to debug that further…

**Comment by woodruffw** [comment]
This error

```
Error: Updated load commands do not fit in the header of /usr/local/Cellar/carthage/0.30.1/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle. /usr/local/Cellar/carthage/0.30.1/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle needs to be relinked, possibly with -headerpad or -headerpad_max_install_names
```

indicates that the rewritten install name would cause the Mach-O header to exceed its link-time max size, so ruby-macho refused to modify it. Upstream needs to change their build to include `-headerpad <size>` where `<size>` is sufficiently large, or `-headerpad-max-install-names`, which'll relink that object so that all current install names in it could expand to up to `MAXPATHLEN`. (I usually recommend `-headerpad-max-install-names`, since it's easier to set-and-forget).

**Comment by jdhealy** [comment]
@woodruffw, are we overlooking an aspect of being a good Homebrew citizen with [our use of `install_name_tool` in our Makefile](https://github.com/Carthage/Carthage/blob/0.31.0/Makefile#L74-L76)?

**Comment by woodruffw** [comment]
@jdhealy I don't think so; those `install_name_tool` calls look reasonable to me. But thank you for linking them!

@blender Yep, I forgot about this. In that case, we may have an environment masking issue somewhere, or possibly a deeper issue that's getting obscured by this error. I'll investigate.
