### ISSUE TITLE
Regression of brew search, it doesn't honor tty

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#4981]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I want to combine output of brew search with some other command via pipe, e.g. install.
- What happened (include command output)
```
$ brew search apple-gcc42|xargs brew install
Error: No available formula with the name "==>" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
These similarly named formulae were found:
a2ps
<lists a lot of formulas>
zzz
```
- What you expected to happen
brew search detects that its used in pipe and prints only formula/cask names.
- Step-by-step reproduction instructions (by running `brew` commands)
```$ brew search apple-gcc42|xargs brew install```

<details>
<summary>brew doctor</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Applications/Wine Staging.app/Contents/Resources/wine/bin/xslt-config
  /Applications/Wine Staging.app/Contents/Resources/wine/bin/xml2-config

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```
</details>
<details>
<summary>brew config</summary>

```
HOMEBREW_VERSION: 1.7.6-9-g2ea3aee
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ea3aee461f4b2f22ccc9b6f72b4426448bc1039
Last commit: 68 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bb29454d2a50f8fc24173dc188e4402d1bade79b
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_EMOJI: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: 10.0.0.0.1.1535735448
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
```
</details>

Related: #2861 https://github.com/Homebrew/homebrew-cask/issues/29596

**Comment by yurikoles** [comment]
Example of search of cask:
```
$ brew search dotnet|xargs brew cask install 
Error: Cask '==>' is unavailable: No Cask with this name exists. Did you mean one of these?
0-ad                       1password-cli              4k-slideshow-maker
010-editor                 1password6                 4k-stogram
0xed                       245cloud                   4k-video-downloader
115browser                 33-rpm                     4k-video-to-mp3
1clipboard                 360safe                    4k-youtube-to-mp3
1password                  3cxphone                   4peaks
1password-beta             3dconnexion```

**Comment by yurikoles** [comment]
Same with ```brew search gcc@7|xargs brew install``` 

It works in f7d0c89c21bc843b1f69cc5c028a9044e1e43c0d, but broken in da193d2f7efc2079db8da8056e53fc458d5e2036

**Comment by reitermarkus** [comment]
This is working as intended, the only commands supported for scripting are `brew search` and `brew search --casks`, since these are the only ones where you can know if they will return formulae or casks.
