### ISSUE TITLE
Homebrew ignores Xcode10's command line tools?

### ISSUE THREAD

**Issue by zj299792458** [Homebrew/brew#4985]
Homebrew is trying to install command line tools for xcode 9.4 during installation. But I already have xcode 10 installed from app store and the xcode-select path properly setup. 

After homebrew installation it also resets my environment variable "xcode-select -p " to the 9.4 command line tools, totally ignoring my xcode 10 path.

And it also triggers the app store to upgrade the standalone command line tools from 9.4 to 10 automatically, which means now I have 2 exactly same sets of command line tools. In which case now I can switch between them for fun ironically…

I checked the installation script myself:

```
def should_install_command_line_tools?
   return false if force_curl?
   return false if macos_version < "10.9"
 
   if macos_version > "10.13"
     !File.exist?("/Library/Developer/CommandLineTools/usr/bin/git")
   else
     !File.exist?("/Library/Developer/CommandLineTools/usr/bin/git") ||
     !File.exist?("/usr/include/iconv.h")
   end
end
```

You can see it's forcing users to install standalone command line tools on Mac OS above 10.13? Is standalone command line tools mandatory other than xcode? Is it designed to be like that?

Appreciate any help.

**Comment by colindean** [comment]
You should fill out the issue template. That will help people help you more quickly.

**Comment by MikeMcQuaid** [comment]
> You can see it's forcing users to install standalone command line tools on Mac OS above 10.13? Is standalone command line tools mandatory other than xcode? Is it designed to be like that?

Yes. 

Please fill out the issue template in future.
