### ISSUE TITLE
PHP 7.2 and 7.1 not working with Mac OS Mojave

### ISSUE THREAD

**Issue by Creationsphere** [Homebrew/brew#4986]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

I apologise if this is the wrong place to seek support for this, i am only just starting to use homebrew and do not know where to ask if not here...

I have used apache, php installations on my macs for several years, but this time decided to do it via homebrew. I was following a guide here - https://gist.github.com/karlhillx/5cd68430aeb25e5e242a3e2c30f238d1

Apache is installed and working. I am having trouble with php. So far i have tried php 7.2 via `brew install php@7.2` and the same for 7.1. I then (after removing again) also tried simple 'brew install php'.

All three attempts produce the same issue... 

firstly `dyld: Library not loaded: /usr/local/opt/openldap/lib/libldap-2.4.2.dylib
  Referenced from: /usr/local/Cellar/php/7.2.10/bin/php
  Reason: image not found
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall php` and `Syntax error on line 187 of /usr/local/etc/httpd/httpd.conf: Cannot load /usr/local/opt/php@7.2/lib/httpd/modules/libphp7.so into server: dlopen(/usr/local/opt/php@7.2/lib/httpd/modules/libphp7.so, 10): Library not loaded: /usr/local/opt/openldap/lib/libldap-2.4.2.dylib\n  Referenced from: /usr/local/opt/php@7.2/lib/httpd/modules/libphp7.so\n  Reason: image not found` when trying to restart apache. 

I eventually fixed this one with `brew install openldap` and reinstalled php. I then got a seemingly more thorough install of php and was confident it would work.

However, I now get this message and am stuck `httpd: Syntax error on line 187 of /usr/local/etc/httpd/httpd.conf: Cannot load /usr/local/opt/php/lib/httpd/modules/libphp7.so into server: dlopen(/usr/local/opt/php/lib/httpd/modules/libphp7.so, 10): Symbol not found: _libiconv\n  Referenced from: /usr/local/opt/php/lib/httpd/modules/libphp7.so\n  Expected in: /usr/lib/libiconv.2.dylib\n in /usr/local/opt/php/lib/httpd/modules/libphp7.so`.

Could anyone please help? Thanks.

**Comment by Creationsphere** [comment]
brew config `HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f239b7a62790cfb4f33bda9aab7597d43f1b1e3b
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ae68a80c0257579b3c109cb56c53c6dcc979d984
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
HOMEBREW_MACOS_VERSION_NUMERIC: 101400
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.14-x86_64
CLT: 9.4.0.0.1.1526532315
Xcode: 10.0
XQuartz: N/A`

brew doctor

`Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.


Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.


Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile`

**Comment by MikeMcQuaid** [comment]
Try to run `xcode-select` to update your command-line tools. Run `brew uninstall --force openldap` and try to install `php` again.
