### ISSUE TITLE
HOMEBREW_GITHUB_API_TOKEN in gist-logs

### ISSUE THREAD

**Issue by mischnic** [Homebrew/brew#499]
`brew gist-logs` just posted my HOMEBREW_GITHUB_API_TOKEN as part of config.log.
I only noticed this after receiving an email from Github telling me that they revoked a token to secure my account.
Could you please add some check to prevent that from happening (like replacing the actual token with a placeholder, should be quite simple with sed, ...)?

The mentioned gist: https://gist.github.com/mischnic/56e60e7cfdb5528240242e0c46986363#file-config-log-L4263

**Comment by dunn** [comment]
Yeah that's not good.

Is it common practice for config scripts to dump the user's environment to a log file, or is this just ffmpeg being weird?

**Comment by mischnic** [comment]
> Is it common practice for config scripts to dump the user's environment to a log file, or is this just ffmpeg being weird?

configure just dumped all env-variables.

**Comment by DomT4** [comment]
FWIW, although this is less than ideal & we should look at doing something about it the actual risk to end users _should be_ minimal here. We recommend creating a token with extremely minimal permissions for `HOMEBREW_GITHUB_API_TOKEN`.

Theoretically the worst case scenario to it being dumped is someone using your API token to spam GitHub & you being blocked from making API calls for an hour, or if you've bumped the permissions to create gists they'd be able to programmatically create gists. Both could be annoying, but the actual risk should be minimal.

**Comment by mischnic** [comment]
The worst case scenario is that you have to create a new API token each time the old one got into a gist.

Like I **already said in my first post**, Github automatically revokes the old one. 
![bildschirmfoto 2016-07-13 um 09 22 53](https://cloud.githubusercontent.com/assets/4586894/16795043/811446fe-48db-11e6-943f-2320d0028164.png)

**Comment by xu-cheng** [comment]
We could try to delete `HOMEBREW_GITHUB_API_TOKEN` for build/postinstall/test.

**Comment by apjanke** [comment]
What do folks think about introducing a `file:...` format for `*_API_TOKEN` and `*_KEY` environment variable values, which would allow you to specify a file that `brew` reads the token from as needed? This would keep actual token values out of the environment.

```
export HOMEBREW_GITHUB_API_TOKEN="file:$HOME/.ssh/my_github_api_token.txt"
export BINTRAY_KEY="file:$HOME/.ssh/my_bintray_key.txt"
```

I've had this on my mind, since I like to keep plaintext passwords out of my environment.

Valid GitHub and Bintray tokens can't contain `:`, so this could be introduced without breaking any current uses, I think.

**Comment by MikeMcQuaid** [comment]
@apjanke 👎 on that personally; I think having sensitive values in your environment is relatively common so we should feel the pain for now until we have a more general solution (i.e. remove all environment we don't need).

**Comment by ilovezfs** [comment]
>I think having sensitive values in your environment is relatively common

I think that's probably true, and so I'd consider this an upstream bug for ffmpeg that they're dumping the entire environment to a log without someone specifically asking the software to do that.

**Comment by MikeMcQuaid** [comment]
Closing this as I consider it an `ffmpeg` issue.
