### ISSUE TITLE
macOS Mojave

### ISSUE THREAD

**Issue by hk05** [Homebrew/brew#4996]
Just (freshly) installed macOS Mojave. One of the first things I did in install brew. When installing brew logs that it is installing older (High Sierra)  command line tools automatically. Installation of brew seems successful but when I try to install my first package (Carthage) brew complains:

Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.

It seems brew has not yet been updated for macOS Mojave. Could anybody arrange this, or including instructions on how to install correctly on Mojave? Thanks!

**Comment by colindean** [comment]
Please always complete the issue template. It helps the team more quickly assess the problem without having to request more information from you. Without the information requested in the issue template, this issue may be closed until you supply that information, preferably in the original text but a follow-up comment is acceptable, too.

**Comment by hk05** [comment]
> Please always complete the issue template. It helps the team more quickly assess the problem without having to request more information from you. Without the information requested in the issue template, this issue may be closed until you supply that information, preferably in the original text but a follow-up comment is acceptable, too.

I am sorry I did not follow conventions. I (falsely) assumed the context + logged error from brew would be clear enough.

**Comment by alebcay** [comment]
Have you tried `sudo xcode-select --install`?

**Comment by ahmedelgabri** [comment]
Same issue here & I did `sudo xcode-select --install` it didn't work

**Comment by hk05** [comment]
Hi Alebcay. I did a clean install of macOS Mojave + xcode 10, so one can safely assume xcode was installed properly and there are no leftovers from other versions etc...

**Comment by zbwu** [comment]
The softwareupdate returned list is not in order

Example:

$ /usr/sbin/softwareupdate -l
Software Update Tool

Finding available software
Software Update found the following new or updated software:
   * Command Line Tools (macOS El Capitan version 10.11) for Xcode-8.2
	Command Line Tools (macOS El Capitan version 10.11) for Xcode (8.2), 150374K [recommended]
   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.0
	Command Line Tools (macOS High Sierra version 10.13) for Xcode (10.0), 190520K [recommended]
   * Command Line Tools (macOS Mojave version 10.14) for Xcode-10.0
	Command Line Tools (macOS Mojave version 10.14) for Xcode (10.0), 187321K [recommended]
   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.3
	Command Line Tools (macOS High Sierra version 10.13) for Xcode (9.3), 187312K [recommended]
   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4
	Command Line Tools (macOS High Sierra version 10.13) for Xcode (9.4), 187380K [recommended]

**Comment by zbwu** [comment]
The code in install script get last line in the list of softwareupdate returned

  clt_label = `/usr/sbin/softwareupdate -l | grep -B 1 -E "Command Line (Developer|Tools)" | awk -F"*" '/^ +\\*/ {print $2}' | sed 's/^ *//' | tail -n1`.chomp

**Comment by hk05** [comment]
> > (falsely) assumed the context + logged error from brew would be clear enough.
> 
> > so one can safely assume xcode was installed properly
> 
> We can’t assume anything. It’s by assuming that we waste several hours trying to debug something when it was a simple oddity on the user’s machine. There’s a reason the issue template is comprehensive. It’s to avoid needless back and forth that consumes volunteer time that could be better spent improving Homebrew. All due respect, it’s not for you to decide which information is relevant or not — that’s the maintainer’s job.
> 
> You still haven’t obliged @colindean’s request. Until you do, we can’t look into your issue properly.

I Victor, no need for a rant. My reply about having performed a fresh install was towards Alebcay who asked if Xcode was installed properly. And I did apologise, so I see no need to start a rant. For what it is worth: I uninstalled brew. So if you are not interested in the problem, I suggest the thread is closed and just wait for someone else to report it again. Again, for the last time: sorry I did not follow conventions.

**Comment by candh** [comment]
I am experiencing the same thing @hk05  I stopped the installation process and removed all the directories created by the script up until the CLT installation. waiting for this to be patched.

**Comment by vitorgalvao** [comment]
> no need for a rant

In the half a decade I’ve been maintaining Homebrew (Cask) and giving similar explanations, I don’t recall it ever being called a rant. Usually users understand the point, thank going in depth for the reasons the details are needed, and proceed to fill the information. To each their own, I guess, text is indeed a bad medium to express mood.

> For what it is worth: I uninstalled brew. So if you are not interested in the problem

We are interested in the problem, but we can’t fix it with the information we (don’t) have now. Since you’ve uninstalled, it’s unreasonable to ask you to install it again just to make the report.

> I am experiencing the same thing @hk05

Sorry to hear, but good news since we have another point from where to try a replication.

> waiting for this to be patched.

We still have no idea where the issue lies. Please open a new bug report and fill the template so we can look into this. Thank you in advance.

With everyone’s permission, I’m closing the issue. We’ll revisit it in the new one opened by @candh. Thank you, everyone.

**Comment by MikeMcQuaid** [comment]
@hk05 @vitorgalvao was not ranting. If you create future issues without filling in the issue template you will be blocked from creating issues on this repository.
