### ISSUE TITLE
Brew update on macOS Mojave.

### ISSUE THREAD

**Issue by maximbadarau** [Homebrew/brew#4997]
Hello,
Yesterday made update to official release of macOS Mojave.
Was trying to ```brew update``` first time failing with:
```
==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing; `git config --local --replace-all homebrew.analyticsmessage true` exited with 1.
```
On recurring attempts displays "Already up to date".
Running ```brew doctor``` end with results:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Missing Homebrew/brew git origin remote.

Without a correctly configured origin, Homebrew won't update
properly. You can solve this by adding the Homebrew remote:
  git -C "/usr/local/Homebrew" remote add origin https://github.com/Homebrew/brew.git

Warning: The following directories do not exist:
/usr/local/Frameworks
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/Frameworks /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/Frameworks /usr/local/sbin

Warning: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install
```
Brew config output:
```
HOMEBREW_VERSION: 1.7.6-22-gdae4791
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: (none)
Core tap HEAD: (none)
Core tap last commit: never
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: N/A
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.14-x86_64
CLT: N/A
Xcode: N/A
XQuartz: N/A
```

**Comment by MindTooth** [comment]
Did you run `xcode-select --install`?

**Comment by maximbadarau** [comment]
> Did you run `xcode-select --install`?

No, I've understood from a lot of previous posts that is not solving the issue. Also to mentioned that is already installed

**Comment by MindTooth** [comment]
Care to try `brew update-reset && brew update`?  And you've done the steps in `brew doctor`?

**Comment by maximbadarau** [comment]
> > > Did you run `xcode-select --install`?
> > 
> > 
> > No, I've understood from a lot of previous posts that is not solving the issue. Also to mentioned that is already installed
> 
> Believe I needed to run it once after I updated to Mojave.
> 
> Care to try `brew update-reset && brew update`? And you've done the steps in `brew doctor`?

Yes, tried both. No changes :(

**Comment by maximbadarau** [comment]
> Seems to be related to a license agreement that has not been agreed upon. At least from this Stack issue[1], which many have participated.
> 
> The following:
> `sudo xcode-install --reset`
> `sudo xcode-install --install`
> `softwareupdate -ir`
> `xcode-select --switch /Library/Developer/CommandLineTools`
> 
> [1] https://apple.stackexchange.com/questions/254380/macos-mojave-invalid-active-developer-path

Git is working. Thus not an issue in dev tools. (or at least it's running under the brew and not embedded one)

**Comment by maximbadarau** [comment]
Close the issue please

**Comment by maximbadarau** [comment]
https://developer.apple.com/download/more/ 
Command Line Tools (macOS 10.14) for Xcode 10 fixed.
```brew doctor``` output:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories do not exist:
/usr/local/Frameworks
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/Frameworks /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/Frameworks /usr/local/sbin
```

**Comment by codevski** [comment]
> https://developer.apple.com/download/more/
> Command Line Tools (macOS 10.14) for Xcode 10 fixed.
> `brew doctor` output:
> 
> ```
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry or file an issue; just ignore this. Thanks!
> 
> Warning: The following directories do not exist:
> /usr/local/Frameworks
> /usr/local/sbin
> 
> You should create these directories and change their ownership to your account.
>   sudo mkdir -p /usr/local/Frameworks /usr/local/sbin
>   sudo chown -R $(whoami) /usr/local/Frameworks /usr/local/sbin
> ```

Do we need to do the following? I have left it for now it hasn't caused any issues not sure if its due to Mojave working differently because before the upgrade this warning didn't occur

**Comment by MikeMcQuaid** [comment]
It says at the top of the `brew doctor` output that you can ignore it.
