### ISSUE TITLE
how about use Warn instead of Error for use `brew upgrade` with package pinned

### ISSUE THREAD

**Issue by specter119** [Homebrew/brew#5007]
Please replace this section with:
- a detailed description of your proposed feature: use Warn instead of Error for use `brew upgrade` with package pinned
- the motivation for the feature:  it seems I do something wrong, but actually not.
- how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request): relate all users with pinned packages
- what alternatives to the feature you have considered: no alternatives

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by colindean** [comment]
Please always complete the issue template. It helps the team more quickly assess the problem without having to request more information from you. Without the information requested in the issue template, this issue may be closed until you supply that information, preferably in the original text but a follow-up comment is acceptable, too.
