### ISSUE TITLE
Bash hash problems upon removal / installation

### ISSUE THREAD

**Issue by maxim-belkin** [Homebrew/brew#5013]
## Problem 1

When removing packages (`brew rm <formula(e)>`), information about them can still be in Bash's hash preventing users from executing corresponding commands that might be provided by the underlying operating system or other packages.

Example:
```sh
hash -d git # or simply do that in a newly opened shell
brew install git
git
hash -t git
# output: /usr/local/bin/git
brew remove git
git
# output: -bash: /usr/local/bin/git: No such file or directory
```

The problem is caused by Bash's algorithm that remembers used paths and tries to use them:
```sh
hash -t git
# output: /usr/local/bin/git
```

**Feature request**: before removing the package, for every executable in a `bin` directory execute 
`hash -d <executable>` if hash points to the binary being removed.

## Problem 2

When installing new apps, their usage can be hindered due to path hashing done by Bash.

Example:

```sh
type -a git
# output: git is /usr/bin/git  ## no Homebrew'd git
hash -t git
# output: /usr/bin/git
git --version
# output: git version 2.17.1 (Apple Git-112)
brew install git
git --version
# output: git version 2.17.1 (Apple Git-112)
```

**Feature request**: after installing the package, for every executable in a `bin` directory execute 
`hash -d <executable>` if hash does NOT point to the newly installed binary. This way we will allow `PATH` to come into play and decide the right executable to be called.

This should be relevant to 100% of Homebrew users.

Alternatives: run `hash -d <executable>` or `hash -r` manually. The latter command is easier to remember but removes ALL remembered (hashed) paths. Proposed mechanism could provide a more targeted solution than `hash -r`.

**Comment by MikeMcQuaid** [comment]
@maxim-belkin Come on, fill in the issue template, you really know better by now.

**Comment by maxim-belkin** [comment]
😕 
I did! 
- Detailed descriptions and motivations are there.
- Assessment of relevance to Homebrew users is there.
- Alternatives are listed.

**Comment by apjanke** [comment]
This might be *quite* difficult to do, since it would require running `hash` in the parent `bash` shell that called the `brew` command, not the subshell that is executing `brew`. The `hash` state is internal to each `bash` process.

**Comment by maxim-belkin** [comment]
Agreed. But some sort of a recommendation or a reminder could be issued, right?

**Comment by MikeMcQuaid** [comment]
> This might be _quite_ difficult to do, since it would require running `hash` in the parent `bash` shell that called the `brew` command, not the subshell that is executing `brew`. The `hash` state is internal to each `bash` process.

I think given this it's worth passing on, sorry @maxim-belkin.

> I did!

I would like to apologise @maxim-belkin for my comment earlier; it wasn't polite or kind.
