### ISSUE TITLE
brew cleanup deletes portable-ruby

### ISSUE THREAD

**Issue by csi-adziahel** [Homebrew/brew#5041]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
> What you were trying to do (and why)

Free up disk space by cleaning clutter up.

> What happened (include command output)

Homebrews' `portable-ruby` is gone:
```
⋊> ~  ls /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby
ls: /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby: No such file or directory
```

> What you expected to happen

`portable-ruby` wasn't deleted

> Step-by-step reproduction instructions (by running `brew` commands)

```
⋊> ~ brew config
HOMEBREW_VERSION: 1.7.6-103-g7f6dc99
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7f6dc994456d3aaf03be306be7c01bffa6f27589
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ea6acbb9679cdfc52477dcd9e7a355a6dea76f31
Core tap last commit: 25 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181, 1.8.0_172
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0
⋊> ~ brew cleanup
⋊> ~  ls /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby
ls: /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby: No such file or directory
⋊> ~ brew doctor
Your system is ready to brew.
⋊> ~  brew config
HOMEBREW_VERSION: 1.7.6-103-g7f6dc99
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7f6dc994456d3aaf03be306be7c01bffa6f27589
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ea6acbb9679cdfc52477dcd9e7a355a6dea76f31
Core tap last commit: 13 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181, 1.8.0_172
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0
```

**Comment by MikeMcQuaid** [comment]
> Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby

Your system Ruby is new enough that you do not need portable Ruby.
