### ISSUE TITLE
curl: (56) SSLRead() return error -9806

### ISSUE THREAD

**Issue by anytaaly** [Homebrew/brew#5049]
I am trying to install homebrew using this terminal command, 
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

and getting this error: Any Idea how I can resolve this issue: 
curl: (56) SSLRead() return error -9806

**Comment by leglagladu13** [comment]
Me too !!! I cannot install homebrew!!

**Comment by MikeMcQuaid** [comment]
If you cannot connect to GitHub securely you'll need to figure out how to resolve that yourself.
