### ISSUE TITLE
 NoMethodError: undefined method `factory' for Formula:Class

### ISSUE THREAD

**Issue by TachikakaMin** [Homebrew/brew#5065]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

`brew install i386-elf-gcc`

- What happened (include command output)

`Error: An exception occurred within a child process:
  NoMethodError: undefined method `factory' for Formula:Class`

brew config
HOMEBREW_VERSION: 1.7.6-143-gc6acab6
ORIGIN: https://github.com/Homebrew/brew
HEAD: c6acab66feb63743fe69b38dab7dc7b90710e838
Last commit: 18 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1cec55d758c10e85a01634c2e00fbb11519d8f66
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.16.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_161, 1.8.0_101, 1.7.0_79
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0

**Comment by reitermarkus** [comment]
Please report this to the tap hosting the `i386-elf-gcc` formula.
