### ISSUE TITLE
Error in update-reset.sh

### ISSUE THREAD

**Issue by WeirdCircumstances** [Homebrew/brew#5066]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- x ] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

When using latest version it shows:

`$ brew update-reset && brew update
/usr/local/Homebrew/Library/Homebrew/cmd/update-reset.sh: line 29: ${REPOS[]}: bad substitution`

Using version from before still works.

**Comment by MikeMcQuaid** [comment]
`brew update` and this should be fixed.

**Comment by WeirdCircumstances** [comment]
```
$ brew update
Already up-to-date.
Error: Cask 'anaconda2' definition is invalid: Token '{:v1_1=>"anaconda2"}' in header line does not match the file name.
```

I will try later again, in case something changes.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/brew/pull/5069

**Comment by WeirdCircumstances** [comment]
Ok, works ;)
Thanks!
