### ISSUE TITLE
`brew info` could also search for cask formulas

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#5071]
* after `brew cask install anaconda` , `brew info anaconda` doesn't work; I figured that `brew cask info anaconda` does work however this is less discoverable and IIUC, there should never be a clash between regular and cask formulas (please correct if I'm wrong)
* not sure whether this is related but `brew caveats` doesn't work with cask formulas (see https://github.com/rafaelgarrido/homebrew-caveats/issues/3)  ; the code [here](https://github.com/rafaelgarrido/homebrew-caveats/blob/master/cmd/brew-caveats.rb) uses `require caveats`  and I'm not sure how it could be changed to read caveats from cask formulas

**Comment by MikeMcQuaid** [comment]
Almost all `brew` commands do not work with casks. This is expected behaviour for now given e.g. name clashes.

**Comment by timotheecour** [comment]
ok I didn't know there could be formula name clashes; what about `caveats` for cask formulas; do you know how to expose it? or shall I write a separate issue for that

**Comment by MikeMcQuaid** [comment]
@timotheecour Casks and formulae are completely independent; they don't share terminology, code or the commands used to install/list/uninstall them. It would be a nice long-term thing for them to be more interlinked but that's something we won't accept a feature request for as it's not really actionable. If you're interested in submitting PRs: we'll review them.

**Comment by J-Swift** [comment]
@MikeMcQuaid - Just wanted to put a comment here rather than open a separate issue. It's a little disorienting for me as a user that certain commands (e.g. search) are explicitly unified, but others (e.g. info) are not.

Here is my recent interaction that led me here:

```
$ brew cask search unity
Error: Calling `brew cask search` is disabled! Use `brew search` instead.

$ brew search unity
==> Casks
[...]   unity   [...]

$ brew info unity
Error: No available formula with the name "unity"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.

$ brew cask info unity
unity: 2018.2.11f1,38bd7dec5000
```

Not sure if this a CLI ergonomic issue, or a technical limitation, but just wanted to bring it up. (Thanks for all the work you and the rest of the team does on homebrew btw, its invaluable to me!)
