### ISSUE TITLE
OS X Mojave: The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist

### ISSUE THREAD

**Issue by nogurenn** [Homebrew/brew#5082]
- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
Glenn-MBP:~ glenn$ brew config
HOMEBREW_VERSION: 1.7.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: c54a657cd5987cba2718f7012a55101324fde8b1
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 683982a01204ddce1165daff00efc129d2e11adb
Core tap last commit: 47 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0

Glenn-MBP:~ glenn$ brew doctor
Your system is ready to brew.
```
To help us debug your issue please explain:
- What you were trying to do (and why)
`brew search postgresql` for a fresh install on my new work laptop. Appears to happen with my `brew search <package>` in general

- What happened (include command output)
```
Glenn-MBP:~ glenn$ brew search postgresql
2018-10-11 02:56:26.353 defaults[39503:147682] 
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist
==> Formulae
postgresql                postgresql@9.4            postgresql@9.5            postgresql@9.6

==> Casks
navicat-for-postgresql                               photo-supreme-postgresql
```
- What you expected to happen
Usual package install. No weird error like this.
- Step-by-step reproduction instructions (by running `brew` commands)
`brew search postgresql`. Tried with `brew search mysql` and `brew search scala`. Appears to be `brew search` in general.

If any, I hope you can help me fix this as none of the solutions around the internet has helped me so far. I think `defaults write` has something to do with this.

**Comment by nogurenn** [comment]
It was a problem with my user account. I changed the account name as per Apple's instructions online, but I think the preference list wasn't updated properly.

**Comment by reitermarkus** [comment]
Which languages do you have set in System Preferences?

**Comment by nogurenn** [comment]
English (en-PH) only. I tried adding more, but on the preference list level, I believe I broke the connection between the preference lists and account name of my computer account so I wasn't detecting a thing, even after executing `defaults write` manually, and adding languages via System Preferences > Language & Region.
