### ISSUE TITLE
Download failed: http://downloads.webmproject.org/releases/webp/libwebp-0.5.1.tar.gz

### ISSUE THREAD

**Issue by zhou9197** [Homebrew/brew#509]
==> Upgrading 2 outdated packages, with result:
gd 2.2.2_2, webp 0.5.1
==> Upgrading gd
==> Installing dependencies for gd: webp
==> Installing gd dependency: webp
==> Downloading http://downloads.webmproject.org/releases/webp/libwebp-0.5.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "webp"
Download failed: http://downloads.webmproject.org/releases/webp/libwebp-0.5.1.tar.gz

**Comment by DomT4** [comment]
Does this reproduce for you consistently? I can't repro locally, so potentially a configuration or firewalling issue on your side if it does.

```
==> Downloading http://downloads.webmproject.org/releases/webp/libwebp-0.5.1.tar.gz
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 http://downloads.webmproject.org/releases/webp/libwebp-0.5.1.tar.gz -C 0 -o /usr/local/var/homebrew/cache/webp-0.5.1.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1183k  100 1183k    0     0   279k      0  0:00:04  0:00:04 --:--:--  279k
Downloaded to: /usr/local/var/homebrew/cache/webp-0.5.1.tar.gz
SHA256: 6ad66c6fcd60a023de20b6856b03da8c7d347269d76b1fd9c3287e8b5e8813df
==> Verifying webp-0.5.1.tar.gz checksum
```

**Comment by zhou9197** [comment]
thanks

**Comment by zhou9197** [comment]
hi bro
Sorry to bother again, but I can not work it out.
With socks5 proxy, I CAN **download it through Safari**, but **failed via curl** which brew uses.

10:07:47  [~]  curl www.google.com   
curl: (56) Recv failure: Connection reset by peer

10:07:47  [~]  curl -I -s --socks5 127.0.0.1 www.google.com
HTTP/1.1 200 OK
...

10:07:47  [~]  curl -I -s --socks5 127.0.0.1 http://downloads.webmproject.org/releases/webp/libwebp-0.5.1.tar.gz
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Content-Length: 1595
Date: Fri, 15 Jul 2016 02:03:50 GMT

10:07:47  [~]  curl -I www.google.com
curl: (56) Recv failure: Connection reset by peer

10:07:47  [~]  export http_proxy=socks5://127.0.0.1:1080
10:07:47  [~]  curl -I www.google.com
HTTP/1.1 200 OK
...

10:07:47  [~]  curl -I http://downloads.webmproject.org/releases/webp/libwebp-0.5.1.tar.gz
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Content-Length: 1595
Date: Fri, 15 Jul 2016 02:06:09 GMT

So I downloaded the package with my browser and put it into [~/Library/Caches/Homebrew]. However, brew did not consider it as "Already downloaded" and started to download , which is not expected. Is there any methods to mark it as "downloaded"?

10:07:47  [~/Library/Caches/Homebrew]  ls
Casks                                        libwebp-0.5.1.tar.gz 

I will be very grateful if you could tell me what else can I do. Thanks a lot.

**Comment by DomT4** [comment]
Are you located in China by any chance?

**Comment by zhou9197** [comment]
yes

**Comment by DomT4** [comment]
Can you `brew update` & try `brew install webp` again? I've added a non-Google-hosted mirror.

**Comment by zhou9197** [comment]
@DomT4  Thanks, it works. BTW, if there is any method that  USERS download the package and put it into the Cache folder and let brew do the INSTALLING JOB in case of DOWNLOADING FAILURE?

**Comment by DomT4** [comment]
You can see how Homebrew expects a downloaded package to be named by doing:
```bash
brew --cache webp -s
```
For example, presuming you're building from source. If you're using a bottle instead of building from source you can drop the `-s` from that argument list. If you rename the fetched file to that expected name `brew` should find it okay.
