### ISSUE TITLE
Create an ethereum wallet for Homebrew donations

### ISSUE THREAD

**Issue by Josh-Smith** [Homebrew/brew#5093]
I'm creating a software library to make blockchain development really easy via CLI tools. I'd like to make sending donations to any of the software tools I rely on really easy. I imagine I'll be using homebrew. 

It's better if you create the wallet than if I do and if you guys manage the governance of your funds without any involvement whatsoever from www.blockwell.ai

Also this would allow paid blockwell tools that leverage homebrew directly using the system to automatically donate a cut to you. We're doing that for any open source we use in paid products (even if just paid for in ERC20 tokens).

**Comment by MikeMcQuaid** [comment]
We already have ways to accept donations, thanks.

**Comment by Josh-Smith** [comment]
So you have no interest in receiving automated donations from people who
use your work via Smart Contract? I can't engineer the automated
contribution of value via Visa/paypal, but I can with smart contracts. ;)

**Comment by MikeMcQuaid** [comment]
Correct. We currently have no interest in donations from people who are unwilling to use one of our existing donation methods: https://github.com/Homebrew/brew#donations
