### ISSUE TITLE
folder should be whitelisted 

### ISSUE THREAD

**Issue by xhaythemx** [Homebrew/brew#5097]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
prune file and folder 
- What happened (include command output) 
with brew prune , those folder will got deleted
Would remove (empty directory): /usr/local/share/man/man8
Would remove (empty directory): /usr/local/share/man/man4
Would remove (empty directory): /usr/local/share/man/man2
Would remove (empty directory): /usr/local/share/locale
Would remove (empty directory): /usr/local/lib/python3.7/site-packages

but after brew upgrade the comeback
- What you expected to happen
that those folder get whitelisted or got deleted for ever
- Step-by-step reproduction instructions (by running `brew` commands)

brew config   
HOMEBREW_VERSION: 1.7.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: c54a657cd5987cba2718f7012a55101324fde8b1
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6ada89e003411006ee467eb764cc32f96aa3c924
Core tap last commit: 17 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0

brew doctor
Your system is ready to brew.

**Comment by MikeMcQuaid** [comment]
> but after brew upgrade the comeback

I cannot reproduce this. Can you show the commands you are running? This was a problem that should have been fixed in 1.7.7.

**Comment by xhaythemx** [comment]
it good fixed after reinstalling homebrew
