### ISSUE TITLE
npm is broken every time what I update node

### ISSUE THREAD

**Issue by unluisco** [Homebrew/brew#51]
Every time what I update node, I can't use npm, I must uninstall and reinstall node, and even I must install each global package of npm again.

```
➜ npm
module.js:341
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by tomByrer** [comment]
Would have to add an extra command to remember, but I use [`nvm`](https://github.com/creationix/nvm#node-version-manager-) for NodeJS installs.  Helps with switching between older versions also.

**Comment by mikemcquaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

Also, as this relates to a formula, please file future issues like this in https://github.com/homebrew/homebrew-core.

**Comment by unluisco** [comment]
- What you were trying to do (and why):
    - I have installed Node from Cakebrew, and an update of node was released, so I update Node from Cakebrew, but whenever I update node, npm is broken.
- What happened:
    - I was going to look the list of the npm packages installed globally and just jumps me that error.
- What you expected to happen:
    - I expected the terminal to show me my packages installed.
- Step-by-step reproduction instructions (with as minimal input data as possible):
    - Install node from cakebrew (npm is included)
    - Wait for a new version of node and update from cakebrew
    - npm will break

Note: However I CAN use my packages, only the npm commands are damaged.
Previously I installed node from the official site and runs easely npm

**Comment by DomT4** [comment]
Can you roll back Node to an earlier version and then execute the update _outside_ Cakebrew to see if this reproduces?

```
git checkout be537884daa24a856e6f3a2da7bffb71719e90cd
brew rm node && brew install node
git checkout master
brew update
brew upgrade node
```

**Comment by mikemcquaid** [comment]
Also, can you please paste your `brew config` and `brew doctor` output in here?

**Comment by unluisco** [comment]
- brew config

```
➜ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 4a7cd160c31969b79979ae9bd20afcf82d9513c0
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 530b134420af9a419c38a4f2e1da2d13e18b16f9
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
OS X: 10.11.4-x86_64
Xcode: N/A
CLT: 7.3.0.0.1.1457485338
Clang: 7.3 build 703
X11: N/A
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60
```

- brew doctor

```
➜ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
    /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
    /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
```

**Comment by UniqMartin** [comment]
@DomT4 @mikemcquaid Ping? I'd like to help, but I have zero experience with `node`.

**Comment by mikemcquaid** [comment]
> in which directory should switch branch?

`cd /usr/local` and then do what @DomT4 suggested. For future issues, please submit them to https://github.com/homebrew/homebrew-core.

**Comment by UniqMartin** [comment]
Closing as we haven't heard back from the issue author for quite a while. I'm happy to reopen once there's some activity and there's still an issue that needs to be addressed by Homebrew, but it currently looks like this is a user-specific problem.

**Comment by unluisco** [comment]
does not seem to be only my problem, I solved following the gist guide: https://gist.github.com/DanHerbert/9520689

**Comment by DomT4** [comment]
It's potentially worth noting this patently isn't true:

> Also, using the Homebrew installation of npm will require you to use sudo when installing global packages. Since one of the core ideas behind Homebrew is that apps can be installed without giving them root access, this is a bad idea.

Homebrew's `npm` has no `sudo` problem and I've lost count of the amount of times I've told people to use `npm` without calling it with `sudo`.

The _vast majority_ of permission problems we've seen reported to Homebrew with `npm` is people  having used `sudo` in the first place and then wonder why a non-`sudo` process (whether that be Homebrew or another `npm` call) can't alter the now root-tarnished directories.

If anyone stumbles across this, I implore you to not mix & match `sudo` usage whilst using a Homebrew-installed `npm`.
