### ISSUE TITLE
"brew desc" search returning limited/no results

### ISSUE THREAD

**Issue by jconley** [Homebrew/brew#5109]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

trying to use `brew desc -s` to search for formulae, and it's producing limited/no results.
same results with `-n` and `-d` options

```
$ brew desc -s network
$
```

```
$ brew desc -s database
tarantool: In-memory database and Lua application server
```

using regex wildcard, only 12 results:
```
$ brew desc -s /./
alluxio: Open Source Memory Speed Virtual Distributed Storage
annie: Fast, simple and clean video downloader
asdf: Extendable version manager with support for Ruby, Node.js, Erlang & more
chisel: Collection of LLDB commands to assist debugging iOS apps
convox: Command-line interface for the Rack PaaS on AWS
faas-cli: CLI for templating and/or deploying FaaS functions
libtorrent-rasterbar: C++ bittorrent library by Rasterbar Software
micronaut: Modern JVM-based framework for building modular microservices
pipenv: Python dependency management tool
planck: Stand-alone ClojureScript REPL
ponyc: Object-oriented, actor-model, capabilities-secure programming language
tarantool: In-memory database and Lua application server
```

```
$ brew config
HOMEBREW_VERSION: 1.7.7-57-g1cf020a
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1cf020a82321c69d89379df0b7d729ba8482c6f5
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a064bd1701151191fd9ff26b3144bc96d5ae352f
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_AUTO_UPDATE: 1
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11, 1.8.0_181
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libant.dylib
  /usr/local/lib/libd2xx_table.dylib
  /usr/local/lib/libftd2xx.1.2.2.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  mp4v2
```

**Comment by jconley** [comment]
@MikeMcQuaid after your update i'm still getting the same improper results in the examples above... except now the regex wildcard example above returns 36 instead of 12 results.

**Comment by jconley** [comment]
@MikeMcQuaid HOMEBREW_CACHE/descriptions.json only had a few entries in it... "fixed" by deleting so it would repopulate from empty

**Comment by MikeMcQuaid** [comment]
@jconley My apologies, I meant to follow up and mention that you'd have to delete it and then it would be fine. Sorry you had to work it out yourself!
