### ISSUE TITLE
Compatibility check for all formulae before upgrading

### ISSUE THREAD

**Issue by pbov** [Homebrew/brew#5116]
macOS Mojave is out for a while now and I'm wondering if all my installed formulae will work after upgrading from High Sierra. My feature suggestion would be a command like "brew upgrade-check [-v 10.14]" which checks all installed formulae on compatibility and outputs a list of all non-compatible formulae (including these which are connected to them).

With a function like this I know the consequences BEFORE upgrading.

The alternative is looking for all installed formulae manually if it would work on the next major OS version.

**Comment by MikeMcQuaid** [comment]
That's a nice idea but we're always ready for Mojave by the time it's released. There's a few formulae that still don't work but the best bet to figure them out is from a tracking issue like https://github.com/Homebrew/homebrew-core/issues/28817.

Thanks!
