### ISSUE TITLE
[FEATURE] Adding typo3scan to homebrew

### ISSUE THREAD

**Issue by tomasnorre** [Homebrew/brew#5125]
I would like to suggest adding the typo3scan tool by @tuurlijk to the homebrew. 

The Software is in short: 

TYPO3 publishes breaking changes and deprecations since version 7.
This tool scans a folder for any code that is broken or deprecated. It's a wrapper around the TYPO3 scanner library that has been extracted from the TYPO3 v9 core. You can scan for deprecations and breaking changes for v7, v8 and v9.

See More:
https://github.com/Tuurlijk/typo3scan

I would be happy to do the work if feature gets approved.

**Comment by tomasnorre** [comment]
Any reason for rejecting?

**Comment by GauthamGoli** [comment]
>  how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)

@Tomassnore I'm not sure how this would be relevant to `Homebrew/brew`'s codebase. 
Do you mean to add `typo3scan` as a brew `formula` ? 

If so, feel free to open a PR in `Homebrew/homebrew-core` repository. Maintainers there would decide on if the package will be accepted.

**Comment by tomasnorre** [comment]
Sorry, didn't see

> how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request) 

I find it a high percentage though, but it's your rules, so I need to play by them. 

I don't know how it should be added, just wanted to make it installable over homebrew, to ease it for the users needed it.. But it will never be even close to 90%.

**Comment by GauthamGoli** [comment]
>  just wanted to make it installable over homebrew, to ease it for the users needed it

Okay. So you need to add a new formula in https://github.com/homebrew/homebrew-core for `typo3scan` to  make it installable using `brew install typo3scan`
 
Please read the relevant docs 
 - https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request
 - https://docs.brew.sh/Formula-Cookbook
 - Acceptable formulae: https://docs.brew.sh/Acceptable-Formulae

**Comment by tomasnorre** [comment]
Thanks, Will do.
