### ISSUE TITLE
Force use homebrew without CLT on old OS?

### ISSUE THREAD

**Issue by ffffwh** [Homebrew/brew#5126]
Though Mojave has been released, I am on High Sierra. `brew install <somthing not bottled>` complains that

```
Error: Xcode alone is not sufficient on High Sierra.
Install the Command Line Tools:
  xcode-select --install
```

Could I take the risk and force it to build without a standalone CLT?

It would be better if there is an explanation about what exactly 'is not sufficient'.

**Comment by MikeMcQuaid** [comment]
> Could I take the risk and force it to build without a standalone CLT?

No, sorry.

> It would be better if there is an explanation about what exactly 'is not sufficient'.

It does not provide the necessary, consistent SDK headers.
