### ISSUE TITLE
brew update broke php artisan.

### ISSUE THREAD

**Issue by behnampmdg3** [Homebrew/brew#5128]
php artisan was working fine. 

I did a brew update and now I get:

php artisan serve 
-bash: /usr/local/bin/php: No such file or directory

Why did Brew move php? What's going on? None of the commands are working.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
