### ISSUE TITLE
sbcl failed to build on 10.13.3

### ISSUE THREAD

**Issue by mnsanghvi** [Homebrew/brew#5132]
https://gist.github.com/adf90f23bbf88f28ae9388edd0e56bd5

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by mnsanghvi** [comment]
Where is the checklist ?  I don't see any "checklist below".  This was submitted using `brew gist-logs --new-issue sbcl` shouldn't that have already taken care of filling out the checklist automatically ?

**Comment by MikeMcQuaid** [comment]
@mnsanghvi https://github.com/Homebrew/homebrew-core/issues/new?template=Reproducible-Bug-Report.md
