### ISSUE TITLE
It’s been an hour since I’ve been parked here. What’s going on?

### ISSUE THREAD

**Issue by giantss** [Homebrew/brew#5135]
Execute the following command:
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.c
om/Homebrew/install/master/install)"
```
It’s been an hour since I’ve been parked here. What’s going on?
![image](https://user-images.githubusercontent.com/13778798/47223127-09345500-d3eb-11e8-9bce-efaaba2ff40c.png)

**Comment by MikeMcQuaid** [comment]
I have no idea, you've not given us enough information to help you figure that out.
