### ISSUE TITLE
Analytics not displayed for versioned formulas

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#5147]
`brew info perl@5.18` gives:

```
==> Analytics
install: 0 (30 days), 0 (90 days), 0 (365 days)
install_on_request: 0 (30 days), 0 (90 days), 0 (365 days)
build_error: 3 (30 days)
```

which is [not true](https://formulae.brew.sh/analytics/install/30d/). It appears to be the case of all versioned formulas I tried to query.

**Comment by MikeMcQuaid** [comment]
```
==> Analytics
install: 120 (30 days), 328 (90 days), 1,270 (365 days)
install_on_request: 93 (30 days), 281 (90 days), 1,100 (365 days)
build_error: 0 (30 days)
```

**Comment by MikeMcQuaid** [comment]
(In future it's worth checking whether the HTML and/or JSON data on formulae.brew.sh is correct/incorrect to speed up narrowing this down 👍)
