### ISSUE TITLE
brew upgarde output (Error: pathname contains null byte)

### ISSUE THREAD

**Issue by foxleoly** [Homebrew/brew#5151]
Hi team,
Today. I met this issue. Any workaround? 

`myhostname ➜  ~ brew upgrade
==> Upgrading 1 outdated package:
ruby 2.5.1 -> 2.5.3
==> Upgrading ruby
Error: pathname contains null byte
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:273:in `initialize'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:273:in `readlink'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:273:in `resolved_path'
/usr/local/Homebrew/Library/Homebrew/keg.rb:331:in `block (2 levels) in unlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:563:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:49:in `block (2 levels) in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:48:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:48:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:43:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:43:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:563:in `find'
/usr/local/Homebrew/Library/Homebrew/keg.rb:324:in `block in unlink'
/usr/local/Homebrew/Library/Homebrew/keg.rb:321:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:321:in `unlink'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:161:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:161:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:109:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:84:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
`

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by foxleoly** [comment]
> From the issue template:
> 
> > **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
> 
> If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

Hi Mike,
What kind of necessary  information? OS type or Env?

My OS: macOS Mojave 10.14
myhostname  ➜  / brew --version
Homebrew 1.8.0
Homebrew/homebrew-core (git revision 2c76b9; last commit 2018-10-19)
Homebrew/homebrew-cask (git revision 2943f5; last commit 2018-10-26)

**Comment by MikeMcQuaid** [comment]
@foxleoly Please read the new issue template which tells you.
