### ISSUE TITLE
Show loading indicator on brew update

### ISSUE THREAD

**Issue by muuvmuuv** [Homebrew/brew#5162]
Today I noticed that `brew update` takes so much time to actually do something that is visible for me (printing text to the console). I think it would be helpful for people to have a more verbose output, so it is clear _brew_ does update something and not just showing the result when it is finished.

**Comment by MikeMcQuaid** [comment]
`brew update -v` provides verbose output.

Please fill out the feature request or issue template in future.

**Comment by muuvmuuv** [comment]
Thanks, @MikeMcQuaid! I did a `brew update --help` and this did not show up there, that is why I have asked, sorry

**Comment by MikeMcQuaid** [comment]
@muuvmuuv No worries!

@GauthamGoli @EricFromCanada do you think we should (eventually) list `--verbose` as an option for every command that does anything with it?

**Comment by GauthamGoli** [comment]
@MikeMcQuaid  It would be shown eventually very soon. `update` doesn't use `CLI::Parser` yet.  

I have started adding `CLI::Parser` support for user commands starting from https://github.com/Homebrew/brew/pull/5175

**Comment by MikeMcQuaid** [comment]
@GauthamGoli Cool, good news. I'm wondering if we want some mechanism to describe precisely what `--verbose` does to change the output per command.

**Comment by GauthamGoli** [comment]
Yeah, I can add that functionality. There's a choice between: 
1. `switch :verbose, description: 'Whatever command specific description'`
or 
2. `switch "-v", "--verbose", description: 'Whatever command specific description'` 
this would work as-is.

**Comment by MikeMcQuaid** [comment]
@GauthamGoli 🆒. I think the prior would be lovely!
