### ISSUE TITLE
curl: (22) The requested URL returned error: 401 authenticationrequired Error: Failed to download resource "openssl"

### ISSUE THREAD

**Issue by evelyn-qi-liu** [Homebrew/brew#5177]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
```
 brew doctor
Your system is ready to brew.
```
```
brew config
HOMEBREW_VERSION: 1.8.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdd8e9b7cf1e53322492e1e90f685c19bdfde506
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ae66485e2d750626b848fd37fb603f0d713ffac2
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_172
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: N/A

```
1. What you were trying to do (and why)
I ran "brew update && brew install azure-cli" to install azure cli
2. What happened (include command output)
```
==> Installing dependencies for azure-cli: openssl, gdbm, readline, sqlite, xz and python
==> Installing azure-cli dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2p.sierra.bottle.tar.gz
######################################################################## 100.0%
curl: (22) The requested URL returned error: 401 authenticationrequired
Error: Failed to download resource "openssl"
Download failed: https://homebrew.bintray.com/bottles/openssl-1.0.2p.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Installing dependencies for openssl: makedepend
==> Installing openssl dependency: makedepend
==> Downloading https://homebrew.bintray.com/bottles/makedepend-1.0.5.sierra.bottle.1.tar.gz
######################################################################## 100.0%
curl: (22) The requested URL returned error: 401 authenticationrequired
Error: Failed to download resource "makedepend"
Download failed: https://homebrew.bintray.com/bottles/makedepend-1.0.5.sierra.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.bz2
######################################################################## 100.0%
curl: (22) The requested URL returned error: 401 authenticationrequired
Trying a mirror...
==> Downloading http://xorg.mirrors.pair.com/individual/util/makedepend-1.0.5.tar.bz2
==> Downloading from http://som01pxswg01:8082/mwg-internal/de5fs23hu73ds/plugin?target=Auth&reason=Auth&ClientID=1200419875&ttl=1200&url=aHR0cDovL3hvcmcubWlycm9ycy5wYWlyLmNvbS9pbmRpdmlkdWFsL3V0aWw

curl: (22) The requested URL returned error: 401 authenticationrequired
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "makedepend"
Download failed: http://xorg.mirrors.pair.com/individual/util/makedepend-1.0.5.tar.bz2

```

3. What you expected to happen
install azure cli succesfully
4. Step-by-step reproduction instructions (by running `brew` commands)
`brew update && brew install azure-cli`
I'm behind company's proxy. I have tried to download above dependencies manually, and move them to /Library/Caches/Homebrew. It didn't work.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by evelyn-qi-liu** [comment]
I have updated the description of the issue, thanks

**Comment by evelyn-qi-liu** [comment]
> From the issue template:
> 
> > **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
> 
> If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

I have updated the description of the issue. Thanks.

**Comment by scpeters** [comment]
I think these posts might help:

* https://discourse.brew.sh/t/error-when-i-try-to-install-homebrew-im-behind-a-corporate-proxy/666/3
* https://apple.stackexchange.com/questions/228865/how-to-install-an-homebrew-package-behind-a-proxy

**Comment by evelyn-qi-liu** [comment]
> I think these posts might help:
> 
> * https://discourse.brew.sh/t/error-when-i-try-to-install-homebrew-im-behind-a-corporate-proxy/666/3
> * https://apple.stackexchange.com/questions/228865/how-to-install-an-homebrew-package-behind-a-proxy

I tried  
`http_proxy=http://user:pwd@proxy:8080 https_proxy=http://user:pwd@proxy:8080 brew install azure-cli`
and 
```
export http_proxy=http://user:pwd@proxy:8080
export https_proxy=http://user:pwd@proxy:8080
```
and I got the error:
```
curl: (22) The requested URL returned error: 407
Error: Failed to download resource "openssl"
Download failed: https://homebrew.bintray.com/bottles/openssl-1.0.2p.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

**Comment by MikeMcQuaid** [comment]
@evelyn-qi-liu I'm afraid you'll need to figure out your proxy by yourself or based on help in Discourse, sorry.
