### ISSUE TITLE
SSH proxies that require write access don't work within formula's sandbox

### ISSUE THREAD

**Issue by tal** [Homebrew/brew#5188]
We are making some formulas that are only accessible behind an ssh proxy. The software we use to access this `duoconnect` needs to write out to an external directory. This means that we cannot clone repos within the sandbox that the formula is run within.

Is there a way to either disable or poke holes in the sandbox?

## Checklist
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.8.0-38-gc573408
ORIGIN: https://github.com/Homebrew/brew
HEAD: c573408a652a4c4e620bafed572b4c64abdd7056
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f878db3dadc6b5f56837093afae4f9c856cb0b9c
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2, 1.8.0_131
macOS: 10.14-x86_64
aCLT: N/A
Xcode: 10.0
```

**Comment by MikeMcQuaid** [comment]
> Is there a way to either disable or poke holes in the sandbox?

No, sorry. Certainly not at a formula level which would defeat the point of the sandbox.

**Comment by tal** [comment]
@MikeMcQuaid any other solutions for our problem? We cannot get internal formulas to work at all under the current situation

**Comment by MikeMcQuaid** [comment]
@tal Use another method such as a private GitHub repository that does not require `duoconnect` or a non-Homebrew solution.

**Comment by tal** [comment]
though code diving installing with `--no-sandbox` solved the problem. Thanks for all the help @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
Glad you got it sorted, @tal. I wouldn't make a habit of using that flag where possible as it turns off a pretty big security feature.
