### ISSUE TITLE
Warning: git-2.9.1 already installed

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#520]
```
Josephs-MacBook-Pro:~ joe$ brew update
Checking for Homebrew updates...
Warning: git-2.9.1 already installed
Error: Git must be installed and in your PATH!
Warning: git-2.9.1 already installed
Error: Git must be installed and in your PATH!
Josephs-MacBook-Pro:~ joe$ brew update
Checking for Homebrew updates...
Warning: git-2.9.1 already installed
Error: Git must be installed and in your PATH!
Warning: git-2.9.1 already installed
Error: Git must be installed and in your PATH!
```

**Comment by DomT4** [comment]
Discussion @ https://github.com/Homebrew/homebrew-core/issues/3029 may be useful. @MikeMcQuaid may want to use you for more troubleshooting though.

**Comment by MikeMcQuaid** [comment]
`git fetch; git reset --hard origin/master`. Already fixed; hopefully we don't see too many people who hit this window :sob:

**Comment by ilovezfs** [comment]
If only we had a magic autoupdater ...

**Comment by ilovezfs** [comment]
Yup, the explicit git fetch got it going.

**Comment by MikeMcQuaid** [comment]
Closing as this is fixed, crossing fingers we don't get a million of these reports and re-adding the CI job in https://github.com/Homebrew/brew/pull/521 which would have caught this.

**Comment by ilovezfs** [comment]
Beat you!

**Comment by yatesco** [comment]
This works for me. Might be worth pointing out that this needs to be run in `/usr/local/Library/Homebrew'

**Comment by ilovezfs** [comment]
It will work there, but the root of the repository is actually just `/usr/local`.
