### ISSUE TITLE
How can I fix brew cleanup Warning?

### ISSUE THREAD

**Issue by airhuman** [Homebrew/brew#5210]
Hi, when I run "brew cleanup", it shows some warnings.
![warning](https://user-images.githubusercontent.com/1021047/47692753-d5023500-dc31-11e8-95e9-e33846894588.png)

Homebrew 1.8.0-72-g18bac4f
macOS Mojave 10.14
iTerm2 3.2.4

**Comment by scpeters** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by scpeters** [comment]
If you fill in the issue template, please also include the results of `brew cleanup --verbose --debug`, since this may be caused by outdated formulae.

**Comment by airhuman** [comment]
I'm sorry. 
But brew cleanup command doesn't support --verbose and --debug options.
