### ISSUE TITLE
Can't chown /usr/local in MacOS Mojave

### ISSUE THREAD

**Issue by stineb** [Homebrew/brew#5214]
I cannot `brew update` after updating to MacOS Mojave. I get the error
```
Error: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami):admin /usr/local
```
And did (according to the suggestion):
```
sudo chown -R $(whoami):admin /usr/local
```
Unfortunately, that's just not possible. I get
```
chown: /usr/local: Operation not permitted
```
I even tried a `brew bundle dump` but get `Error: Your Homebrew is outdated. Please run 'brew update'.` 
The snake bites its own tail.

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template.

Your version of Homebrew is too old for those instructions to be correct. Instead do `sudo chown -R $(whoami):admin /usr/local/* /usr/local/.git`

**Comment by stineb** [comment]
I did that and still get the error:

    Error: The /usr/local directory is not writable.
    Even if this directory was writable when you installed Homebrew, other
    software may change permissions on this directory. Some versions of the
    "InstantOn" component of Airfoil are known to do this.

    You should probably change the ownership and permissions of /usr/local
    back to your user account.
      sudo chown -R $(whoami):admin /usr/local
