### ISSUE TITLE
Retry bottle download a few times before switching to source build

### ISSUE THREAD

**Issue by letmaik** [Homebrew/brew#5219]
```
==> Downloading https://homebrew.bintray.com/bottles/gcc-8.2.0.sierra.bottle.1.tar.gz 
curl: (56) SSLRead() return error -9806
Error: Failed to download resource "gcc"
Download failed: https://homebrew.bintray.com/bottles/gcc-8.2.0.sierra.bottle.1.tar.gz 
Warning: Bottle installation failed: building from source.
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.xz 
```

IMO, this is a very suboptimal behaviour. Homebrew should retry download a couple of times before reverting to a source build. The reason is that for large software this can easily lead to timeouts in continuous integration scenarios (Travis CI etc.) where an install of gcc suddenly takes an hour instead of a few seconds.

**Comment by MikeMcQuaid** [comment]
We'd consider accepting a pull request to add a single retry. This isn't a widespread issue we've heard complaints about, though, and is probably something that should be fixed or worked around in Travis CI.

Please fill out the issue or feature request template in future.

**Comment by letmaik** [comment]
Can you give some more details on how you would fix/work around that in Travis CI?

**Comment by MikeMcQuaid** [comment]
@letmaik `brew fetch --retry` or `travis_retry`.

**Comment by letmaik** [comment]
Ah, interesting, it's a bit odd that `--retry` only exists for fetch and not install.

The doc for fetch says:
> Download the source packages for the given formulae.

I would need the bottles though. Or is this just a documentation issue and it actually downloads bottles?

Apart from that, is there a reason why `--retry` is not on by default?

**Comment by letmaik** [comment]
Regarding `travis_retry`, this would be useless given that https://github.com/Homebrew/brew/issues/5221 is not implemented as brew would immediately fall back to a long source build, but instead I want to retry the bottle-based install.

**Comment by MikeMcQuaid** [comment]
> Ah, interesting, it's a bit odd that `--retry` only exists for fetch and not install.

No-one has requested it on `install` before. Additionally, `--retry` on install might imply "retry the build" rather than just the download so it might need a new name. That'd be a good candidate for the PR, though.



> I would need the bottles though. Or is this just a documentation issue and it actually downloads bottles?

Not sure off the top of my head; I think it'll do the bottles.



> Apart from that, is there a reason why `--retry` is not on by default?

Avoid unnecessarily hammering servers on failures.



> Regarding `travis_retry`, this would be useless given that #5221 is not implemented as brew would immediately fall back to a long source build, but instead I want to retry the bottle-based install.

As mentioned `HOMEBREW_DEVELOPER` could be used for that.

**Comment by jerith** [comment]
The current behaviour (building from source whenever a bottle install encounters any error at all) hurts me regularly, usually when I `brew upgrade` on my consumer DSL internet connection. As well as taking much longer, a source build typically requires extra build dependencies which also need to be downloaded. As a result, I can't just type `brew install <thing>` or `brew upgrade` and then go make coffee or something -- I need to continually check if a network blip caused the download to fail and then manually cancel the build so I can try again with bottles.

I would be happy with a `--retry-download` option on install/upgrade/whatever to enable retries and/or a `--no-source-fallback` option to disable falling back to source builds if the bottle install fails.

**Comment by scpeters** [comment]
~~~
brew fetch --retry --force-bottle ${formula} \
 && brew install ${formula}
~~~

**Comment by letmaik** [comment]
> If --force-bottle is passed, download a bottle if it exists for the current or newest version of macOS, even if it would not be used during installation.

Is this really what we're looking for? I find the text a bit confusing.

**Comment by MikeMcQuaid** [comment]
> or a `--no-source-fallback` option to disable falling back to source builds if the bottle install fails.

This seems like good idea that could be easily implemented.

**Comment by scpeters** [comment]
Here is  a key part of the code where `--no-source-fallback` could be added:

* https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L303-L306

**Comment by jerith** [comment]
Does `brew fetch --retry --force-bottle ${formula}` fetch dependencies as well? If not, is there a way to list the dependencies (including transitive deps) so I can fetch them explicitly?

**Comment by MikeMcQuaid** [comment]
> Does `brew fetch --retry --force-bottle ${formula}` fetch dependencies as well?

No.



> If not, is there a way to list the dependencies (including transitive deps) so I can fetch them explicitly?

`brew deps --help`. In general, check `man brew` for such questions.

**Comment by MikeMcQuaid** [comment]
> and/or a `--no-source-fallback` option to disable falling back to source builds if the bottle install fails.

This was done in https://github.com/Homebrew/brew/pull/5528.

Between this and `brew fetch --retry` I consider the cases mentioned here to be addressed.
