### ISSUE TITLE
Option to disallow source builds

### ISSUE THREAD

**Issue by letmaik** [Homebrew/brew#5221]
```
==> Downloading https://homebrew.bintray.com/bottles/gcc-8.2.0.sierra.bottle.1.tar.gz 
curl: (56) SSLRead() return error -9806
Error: Failed to download resource "gcc"
Download failed: https://homebrew.bintray.com/bottles/gcc-8.2.0.sierra.bottle.1.tar.gz 
Warning: Bottle installation failed: building from source.
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.xz 
```

Sometimes bad things happen, and even though brew could have [tried harder](https://github.com/Homebrew/brew/issues/5219) here there may be a legitimate network outage. Or the bottle just may not be available anymore for the given target system.

I think brew should have the option of disallowing switching to source builds. In Python/pip, one can do just that: `pip install --only-binary :all: pkgabc`. In certain scenarios this is exactly what I would want to happen, a failure instead of a source build. Giving more control over how brew behaves is in general a good thing I think.

**Comment by MikeMcQuaid** [comment]
You can set `HOMEBREW_DEVELOPER` to make this error out. That has many other effects though so your mileage may vary.

> Giving more control over how brew behaves is in general a good thing I think.

I disagree. It results in more complex, buggy software with worse defaults.

**Comment by letmaik** [comment]
> HOMEBREW_DEVELOPER: If set, Homebrew will tweak behaviour to be more relevant for Homebrew developers (active or budding) e.g. turning warnings into errors.

I think you're right that this is probably not exactly what I'd like since I quite often see warnings when doing brew install, e.g. just now while installing gcc and hdf5:
> Warning: hdf5 dependency gcc was built with a different C++ standard

Even though this warning sounds bad I don't want it to fail the build since this looks like an upstream issue that I don't have immediate influence on and it will probably still work. So, I still think there should be such an option similar to pip. If you still disagree then let's leave it closed until there is more demand from other devs.
