### ISSUE TITLE
brew install failed with message "Library not loaded: /usr/local/lib/libwep"

### ISSUE THREAD

**Issue by wk2557** [Homebrew/brew#5222]
Failure while executing; `git config --local --replace-all homebrew.analyticsmessage true` exited with .
dyld: Library not loaded: /usr/local/lib/libwep
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/git
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libwep: mmap() error 1 at address=0x1088C8000, size=0x0000F000 segment=__TEXT in Segment::map() mapping /usr/local/lib/libwep
	/usr/local/lib/libwep: mmap() error 1 at address=0x1088EA000, size=0x0000F000 segment=__TEXT in Segment::map() mapping /usr/local/lib/libwep

**Comment by wk2557** [comment]
brew install failed with message "dyld: Library not loaded: /usr/local/lib/libwep
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/git
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libwep: mmap() error 1 at address=0x100B5A000, size=0x0000F000 segment=__TEXT in Segment::map() mapping /usr/local/lib/libwep
	/usr/local/lib/libwep: mmap() error 1 at address=0x100B75000, size=0x0000F000 segment=__TEXT in Segment::map() mapping /usr/local/lib/libwep
Error: Failure while executing; `git config --local --replace-all homebrew.analyticsmessage true` exited with ."

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by wk2557** [comment]
How can I submit the issue?
