### ISSUE TITLE
Homebrew allows duplicate formula installation (for example, a users tapped formula) if that formula is a dependency in another formula

### ISSUE THREAD

**Issue by blogabe** [Homebrew/brew#5224]
Edited to reflect the conversation below:

Homebrew currently has the ability to stop duplicate formulas from installing.  For example, if a user has `foo` installed, Homebrew will disallow `user/tap/foo` from installing.  Similarly, if a user has `user/tap/foo` installed, Homebrew will disallow `foo` from installing.

However, if `bar` depends on `foo`, Homebrew will not stop any duplicate installation.  It should stop the installation with a message to the user to uninstall the offending formula.

I think this is an important change to make given the recent policy changes to move custom compile options to user taps where different dependencies may overwrite one another.  User should be able to decide which version is getting installed and for what reason.  As of right now, there is no way to easily know there is more than one version of a formula unless you check in `Cellar`.

**Comment by MikeMcQuaid** [comment]
Does `depends_on "blogabe/yourtap/foo"` not handle this as expected?

**Comment by blogabe** [comment]
That does work.  But if someone has Homebrew's foo, my tap's foo will clobber it, no?

**Comment by MikeMcQuaid** [comment]
I'm not sure of that behaviour off the top of my head. Try it out and see. I'm pretty sure there will be behaviour that will warrant discussion from that.

**Comment by blogabe** [comment]
It does clobber it.  Lemme know if you need anything from my end to show you what it looks like.

Just think this is something we need to incoporate to help users' maintain their own taps in a semi-standard way.  I'm not suggesting there will be dozwens of versions of a particular formula, but there may be some tapped version that conflict with one another.

Furthermore, a user trying to install a tapped formula may not want a particular dependency changed to a different tapped version.

**Comment by MikeMcQuaid** [comment]
> Lemme know if you need anything from my end to show you what it looks like.

The output would be good, please.

> Furthermore, a user trying to install a tapped formula may not want a particular dependency changed to a different tapped version.

We deliberately don't want to allow a "choice" beyond deciding whether you want to install the software or not. Rather than a check in the tap formula I'd suggest perhaps the check should be in Homebrew itself which requires manual intervention rather than "clobbering".

**Comment by blogabe** [comment]
Output looks totally normal as you expect.  Only way to know that it was clobbered is be looking in the Cellar or bin directories.

Whether in the tap formula or in Homebrew sounds good to me.  How do you think it would happen in Homebrew?

**Comment by MikeMcQuaid** [comment]
@blogabe I don't have an expectations for this output 😉. It'd be handy if you could paste what you see.

**Comment by blogabe** [comment]
No problem.  BTW: I think we're half way there.  If Homebrew Xplanet is installed, Homebrew does not allow me to install my tapped version.  Also if my tapped version is installed, Homebrew does not allow me to install the Homebrew version.  However, when I have my tap's version of Xplanet as a dependency in xplanetFX, Homebrew will install my tap's version even if the Homebrew version already exists.

Output is below:

```
$ brew install xplanet
==> Downloading https://downloads.sourceforge.net/project/xplanet/xplanet/1.3.1/xplanet-1.3.1.tar.gz
Already downloaded: /Users/blogabe/Library/Caches/Homebrew/downloads/46659b06c38c4a00d9fb22bc0338bd76251e3bb69bccfae57caf35f5b720751d--xplanet-1.3.1.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/f952f1d/xplanet/xplanet-1.3.1-ntimes.patch
Already downloaded: /Users/blogabe/Library/Caches/Homebrew/downloads/c7c62d8240b19b06572f0fb55ebff3192b4c02501f3cc0908c5a7bb93e82cca8--xplanet-1.3.1-ntimes.patch
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/master/xplanet/xplanet-1.3.1-giflib5.patch
Already downloaded: /Users/blogabe/Library/Caches/Homebrew/downloads/b2f4beb276aa6694adee0dd49c0fc7cb2c4032524fffbabb38ebabf8b7cfed1b--xplanet-1.3.1-giflib5.patch
==> Patching
==> Applying xplanet-1.3.1-ntimes.patch
patching file src/libdisplay/DisplayOutput.cpp
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 51 with fuzz 1.
==> Applying xplanet-1.3.1-giflib5.patch
patching file src/libimage/gif.c
==> ./configure --prefix=/Users/blogabe/local/Cellar/xplanet/1.3.1_2 --with-aqua --without-cspice --without-cygwin --without-gif --without-jpeg --without-libpng --without-libtiff --without-pango --without-
==> make install
🍺  /Users/blogabe/local/Cellar/xplanet/1.3.1_2: 56 files, 2.3MB, built in 43 seconds
$ brew install ./xplanetfx.rb
==> Installing dependencies for xplanetfx: blogabe/xplanet/xplanet
==> Installing xplanetfx dependency: blogabe/xplanet/xplanet
==> Downloading https://downloads.sourceforge.net/project/xplanet/xplanet/1.3.1/xplanet-1.3.1.tar.gz
Already downloaded: /Users/blogabe/Library/Caches/Homebrew/downloads/46659b06c38c4a00d9fb22bc0338bd76251e3bb69bccfae57caf35f5b720751d--xplanet-1.3.1.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/f952f1d/xplanet/xplanet-1.3.1-ntimes.patch
Already downloaded: /Users/blogabe/Library/Caches/Homebrew/downloads/c7c62d8240b19b06572f0fb55ebff3192b4c02501f3cc0908c5a7bb93e82cca8--xplanet-1.3.1-ntimes.patch
==> Downloading https://raw.githubusercontent.com/blogabe/homebrew-xplanet/master/xplanet-1.3.1-2017leapsecond.patch
Already downloaded: /Users/blogabe/Library/Caches/Homebrew/downloads/e996c7eac2e6a37ca733889b88184e54e388411103daafcf8c2068b6de285f7f--xplanet-1.3.1-2017leapsecond.patch
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/master/xplanet/xplanet-1.3.1-giflib5.patch
Already downloaded: /Users/blogabe/Library/Caches/Homebrew/downloads/b2f4beb276aa6694adee0dd49c0fc7cb2c4032524fffbabb38ebabf8b7cfed1b--xplanet-1.3.1-giflib5.patch
==> Patching
==> Applying xplanet-1.3.1-ntimes.patch
patching file src/libdisplay/DisplayOutput.cpp
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 51 with fuzz 1.
==> Applying xplanet-1.3.1-2017leapsecond.patch
patching file src/xpUtil.cpp
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 434 with fuzz 1.
==> Applying xplanet-1.3.1-giflib5.patch
patching file src/libimage/gif.c
==> ./configure --prefix=/Users/blogabe/local/Cellar/xplanet/1.3.1_3 --without-cygwin --with-aqua --without-x --without-xscreensaver --without-pango --without-pnm --without-cspice
==> make install
🍺  /Users/blogabe/local/Cellar/xplanet/1.3.1_3: 56 files, 2.3MB, built in 43 seconds
==> Installing xplanetfx
==> Downloading http://repository.mein-neues-blog.de:9000/archive/xplanetfx-2.6.14_all.tar.gz
Already downloaded: /Users/blogabe/Library/Caches/Homebrew/downloads/41f9d2d2a0205d3edc58802c086c14e04fa6858e0b9e265a1388560052fb2633--xplanetfx-2.6.14_all.tar.gz
==> /Users/blogabe/local/bin/gdk-pixbuf-query-loaders --update-cache
🍺  /Users/blogabe/local/Cellar/xplanetfx/2.6.14: 207 files, 38.4MB, built in 6 seconds
```

**Comment by MikeMcQuaid** [comment]
Yes, agreed that behaviour is undesirable; I think in that case it should refuse to install an identical version and require a `brew uninstall`. What do you think?

**Comment by blogabe** [comment]
Sounds good to me.  Thanks @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
@blogabe Mind retitling/editing the original issue body to reflect this? After that I'll mark this as `help wanted` or maybe get to it myself. Thanks!

**Comment by blogabe** [comment]
Hope title and explanation are all clear now @MikeMcQuaid 

Let me know if I left out anything important.  Thanks for your help.
