### ISSUE TITLE
No way to upgrade a --HEAD formula without removing the existing install first

### ISSUE THREAD

**Issue by alexchandel** [Homebrew/brew#523]
Unless I'm missing something, there's no way to upgrade a formula installed with `--HEAD` without unlinking/removing the current keg first. This is a problem when it's desirable to be able to use the previous keg while compilation occurs.

**Comment by cmdcolin** [comment]
Just ran into this. Would be a nice update!

**Comment by MikeMcQuaid** [comment]
@vladshablinsky has addressed this.
