### ISSUE TITLE
Create a new node-lts package?

### ISSUE THREAD

**Issue by jharris4** [Homebrew/brew#5230]
Currently, there is the general `node` package that gives you the absolute newest version of node, or you can manually install specific version with `node@#` where # is a version like 10.

I recently updated `node` and it installed version `11.0` which I have since discovered has quite a few bugs that are breaking a few of my tools (express server and webpack started developing issues).

Since node 11 is not LTS it perhaps makes sense that its a little flaky, so I decided to downgrade back to the last LTS version which is node 10. This did indeed resolve the issues I was seeing with node 11.

Installing the `node@10` package was not altogether trivial, as I had to do the following:

1) `brew uninstall node` (required `brew uninstall yarn` first due to dependency)
2) `brew install node@10` (required `rm -rf /usr/local/lib/node_modules` to silence warnings about conflicts)
3) `brew link node@10 --force`

Maybe there's an easier/better way to do the above, in which case I'm all ears! ;-)

But my general idea was that it might make sense for a `node-lts` package to exist which tracks the latest version of whatever the latest LTS version of node is.

I'm a bit of a n00b with actual creating/maintaining brew packages, but I'd be happy to help if people think it's a good idea and someone could give me some pointers.

**Comment by MikeMcQuaid** [comment]
> * `brew uninstall node` (required `brew uninstall yarn` first due to dependency)

Why did you need to uninstall?



> * `brew install node@10` (required `rm -rf /usr/local/lib/node_modules` to silence warnings about conflicts)

Had you manually installed node modules?



> 3\. `brew link node@10 --force`

You can instead add the relevant directories to your PATH.



> But my general idea was that it might make sense for a `node-lts` package to exist which tracks the latest version of whatever the latest LTS version of node is.

If we had a node-lts package it would still require following all the same steps you did above. As a result, I'd rather we stuck to the current `@version` convention.

Thanks for the suggestions, though!

**Comment by jharris4** [comment]
Thanks for taking the time to review the feature idea.

My thinking was that with a `node-lts` package, it would still be on version 10, so the above steps would never have been needed, that's kind of the point of this feature proposal!

To answer your questions:

- I uninstalled the general `node` package to be sure that it was properly removed and that it did not have any lingering presence. The fact that other packages depended on it led me to believe that uninstall was the best way to go. Would you have suggested another route? Should I have used `brew switch` instead or something?

- I had manually installed node modules. Brew complained about that when I went to install the other node package, so I opted to nuke it and reinstall my global packages.

**Comment by MikeMcQuaid** [comment]
> My thinking was that with a `node-lts` package, it would still be on version 10, so the above steps would never have been needed, that's kind of the point of this feature proposal!

If you had `brew install node@10` I believe it wouldn't have been upgraded to a new major version.



> * Would you have suggested another route?

If other stuff depends on it I'd suggest just leaving it and using the other version.
