### ISSUE TITLE
"brew update" bug??? Can't upgrade???

### ISSUE THREAD

**Issue by springleng** [Homebrew/brew#526]
![91 pic](https://cloud.githubusercontent.com/assets/1900972/16892253/9e4d9b92-4b3f-11e6-8d89-bf12c89fd9df.jpg)

Can't upgrade???

**Comment by DomT4** [comment]
```bash
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```
Sorry for the inconvenience! Will only need to run that once, and then you'll be all sorted again.
