### ISSUE TITLE
A better way to deal with incompatible packages

### ISSUE THREAD

**Issue by deepj** [Homebrew/brew#5268]
The following text I wrote in this PR https://github.com/Homebrew/homebrew-core/pull/33131#issuecomment-436027856, I feel this place is better for this kind of "request".

>Hello,
is possible to change the release rules in this context? Or improve a way to deal with incompatible  packages? PostgreSQL 11 is released for a while and it's still not in `homebrew`. I guess the most of PostgreSQL users using it through `homebrew` don't use the most of the above mentioned packages (let's say except `postgis`).

>What I want to say, it's to find some better way how to notice users if they want to use xxx package incompatible with this new one and offer some options how to deal with it.

When I look at Homebrew analytics for the last 30 days. PostgreSQL is at #66 place, and its the most downloaded extension PostGIS is until at #364 place. In other words, just minority of Homebrew users use these extensions/packages in comparison of users of vanilla PostgreSQL only. If someone use them, then the newer incompatible version of PostgreSQL wouldn't be allowed to be installed for them.

The current situation is, waiting on minor extensions/packages until they are fixed for the new PostgreSQL. And it can takes weeks/months than someone fixes it. I use only vanilla PostgreSQL via Homebrew. And I would appreciate to use the newest PostgreSQL via Homebrew.

**Comment by MikeMcQuaid** [comment]
Please fill out the issue or feature request template in future, there's no proposed solution here. I'll reply on that issue.
