### ISSUE TITLE
Bottle pouring does not replace @@HOMEBREW_PREFIX@@ placeholder

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#5271]
This is a problem with the `fb-client` bottle, which when it is poured has an occurrence of `@@HOMEBREW_PREFIX@@` which is not replaced as it should be.

Running `brew install fb-client` followed by `brew test --verbose fb-client` gives:

```
  File "/usr/local/Cellar/fb-client/2.0.3_4/libexec/bin/fb", line 15, in <module>
    import pycurl
ImportError: dlopen(/usr/local/Cellar/fb-client/2.0.3_4/libexec/vendor/lib/python3.7/site-packages/pycurl.cpython-37m-darwin.so, 2): Library not loaded: @@HOMEBREW_PREFIX@@/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/Cellar/fb-client/2.0.3_4/libexec/vendor/lib/python3.7/site-packages/pycurl.cpython-37m-darwin.so
  Reason: image not found
```

because:

```
$ otool -L /usr/local/Cellar/fb-client/2.0.3_4/libexec/vendor/lib/python3.7/site-packages/pycurl.cpython-37m-darwin.so
/usr/local/Cellar/fb-client/2.0.3_4/libexec/vendor/lib/python3.7/site-packages/pycurl.cpython-37m-darwin.so:
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
	@@HOMEBREW_PREFIX@@/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

I believe this `@@HOMEBREW_PREFIX@@` placeholder should have been replaced. Maybe it is because the bottle has `cellar :any_skip_relocation` while it shouldn't have.

----

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

```
rmeur ~ $ brew config
HOMEBREW_VERSION: 1.8.2-15-gf625d7c
ORIGIN: https://github.com/Homebrew/brew
HEAD: f625d7ca7fc4c9ee5b1baaddf5db65560ef177e2
Last commit: 15 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d1cd80515e1229860a1cd15d9f9cd1a9d228aab6
Core tap last commit: 10 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BINTRAY_KEY: set
HOMEBREW_BINTRAY_USER: fxcoudert
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144
macOS: 10.14.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
rmeur ~ $ brew doctor
Your system is ready to brew.
```

**Comment by fxcoudert** [comment]
I ran another testing job (https://jenkins.brew.sh/job/Homebrew%20Bottles/39117/console), confirming that Homebrew considers the bottle `:any_skip_relocation`:

```
brew bottle --merge --write fb-client--2.0.3_4.mojave.bottle.json fb-client--2.0.3_4.high_sierra.bottle.json fb-client--2.0.3_4.sierra.bottle.json
==> fb-client
  bottle do
    cellar :any_skip_relocation
    rebuild 2
    sha256 "8f0ad2228a93176a510e841d0641bf0f7fbfa10826423aa3a58e99e30c97801e" => :mojave
    sha256 "ce52ac4ae45609f5d2c85eb1ae7cc654e9ebcb676bcfe261f825f9b464c6b161" => :high_sierra
    sha256 "bff9c2e2c17941e4ac302a1bc9b60dda69c90b28d8978618a120798ba0a29469" => :sierra
  end
```

**Comment by MikeMcQuaid** [comment]
> Maybe it is because the bottle has `cellar :any_skip_relocation` while it shouldn't have.

Yeh, this is the bug. `:any_skip_relocation` means no relocation will be done.

**Comment by fxcoudert** [comment]
You win, stale bot. You win. (This time)
