### ISSUE TITLE
Having a clear documentation for SSH download strategy (#3891)

### ISSUE THREAD

**Issue by chris-fran** [Homebrew/brew#5278]
I am used to create a new GitHub API Token everytime I have to provision a new device. However, I also have to setup SSH keys so that I can use Git over SSH.

I figured maybe brew supports using my SSH key instead of having to generate a token. I found #3891 which I believe is the feature I'm looking for, but I see no documentation regarding on how to set it up. Since I already setup my SSH keys on GitHub, and `brew` is still giving me `Warning: Error searching on GitHub: GitHub Bad credentials:HOMEBREW_GITHUB_API_TOKEN may be invalid or expired` I assume it's not an automatic setup, but I probably have to do some manual steps. 

Documentation on this would be perfect!

**Comment by MikeMcQuaid** [comment]
We don't officially support using SSH keys for Homebrew clones, sorry. You shouldn't need a token when cloning public repositories. `HOMEBREW_GITHUB_API_TOKEN` is used for searches rather than cloning.
