### ISSUE TITLE
Installed package should not be marked as ✘

### ISSUE THREAD

**Issue by sgon00** [Homebrew/brew#5287]
I just met the confusion reported at https://github.com/Homebrew/brew/issues/2259. 
Since that issue `locked and limited conversation to collaborators`, I have to open a new one. Otherwise, I will simply comment on that issue.  (Please don't lock conversation if you don't want any duplicated bugs)
I don't think the decision made in that issue is correct. It definitely should not be ✘. This confused me a lot. It's an incorrect behavior.

**Comment by MikeMcQuaid** [comment]
> Although this isn't ideal I think it is something that we can't really fix for the above reasons without causing additional confusion, sorry.

Please don't open duplicate issues and always fill out the issue template in future.
