### ISSUE TITLE
brew bump-formula-pr doesn't work with two factor authentication

### ISSUE THREAD

**Issue by barthel** [Homebrew/brew#5288]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

At github I'm using two factor authentication for my account.
I tried several times ```brew bump-formula-pr``` like:
```
barthel $ brew bump-formula-pr --verbose --strict --url=https://github.com/bitwarden/cli/releases/download/v1.5.0/bw-macos-1.5.0.zip bitwarden-cli
==> Downloading https://github.com/bitwarden/cli/releases/download/v1.5.0/bw-macos-1.5.0.zip
Already downloaded: /Users/barthel/Library/Caches/Homebrew/downloads/302038a82ddab1aee05b4b28ae6dae5a008cb0081286a372801c934bea9cc0bb--bw-macos-1.5.0.zip
brew update
Already up-to-date.
==> replace /https:\/\/registry\.npmjs\.org\/@bitwarden\/cli\/\-\/cli\-1\.3\.0\.tgz/ with "https://github.com/bitwarden/cli/releases/download/v1.5.0/bw-macos-1.5.0.zip"
==> replace "75bee4713cbf738d7140973b44d068f36155b8888418b07ed036eb0b0088e0fb" with "1eaf77029d51e1647f19d5f1666423b97aaa1401cef5e3e1b4e2d714946b107e"
/usr/local/bin/brew audit --strict /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bitwarden-cli.rb
git config --local --get-regexp remote..*.url git@github.com:.*
git checkout --no-track -b bitwarden-cli-1.5.0 origin/master
M	Formula/bitwarden-cli.rb
Switched to a new branch 'bitwarden-cli-1.5.0'
git commit --no-edit --verbose --message=bitwarden-cli 1.5.0 -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bitwarden-cli.rb
[bitwarden-cli-1.5.0 a0c5fd9d01] bitwarden-cli 1.5.0
 1 file changed, 2 insertions(+), 2 deletions(-)
git push --set-upstream https://github.com/barthel/homebrew-core.git bitwarden-cli-1.5.0:bitwarden-cli-1.5.0
Username for 'https://github.com': barthel
Password for 'https://barthel@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/barthel/homebrew-core.git/'
Error: Failure while executing; `git push --set-upstream https://github.com/barthel/homebrew-core.git bitwarden-cli-1.5.0:bitwarden-cli-1.5.0` exited with 128.
```

If I disable the two factor authentication for my account this command finished successfully.

**Comment by MikeMcQuaid** [comment]
It does work, you need to use a personal access token.

**Comment by barthel** [comment]
I tried with a personal access token too, but ```brew bump-formula-pr``` asks for the username and the password.
