### ISSUE TITLE
The options command should be renamed as to make it clear that it's available only for the install command

### ISSUE THREAD

**Issue by revolter** [Homebrew/brew#5298]
Following the discussion in #5142, I think it would make more sense for the `options` command to be renamed to something clearer like `install-options`:

`brew install-options package`

This way, it's obvious that the returned options don't apply to the `reinstall` command too.

What do you think?

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue or feature request template.

We can't rename existing commands as we will break people's workflows.
