### ISSUE TITLE
brew keeps installing node while i have it with nvm

### ISSUE THREAD

**Issue by xhaythemx** [Homebrew/brew#5311]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
i am trying to install cash-cli 
- What happened (include command output)
brew installed node while i have it installed via nvm 
- What you expected to happen
that cash cli uses node the one installed with nvm
- Step-by-step reproduction instructions (by running `brew` commands)
brew install cash-cli

brew config           
HOMEBREW_VERSION: 1.8.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6f458aaed494eaab92622f41f9f1967add00b0f4
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6f74a34777569efa2d2699c5ddfaad3e47d784cf
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1

brew doctor
Your system is ready to brew.

**Comment by MikeMcQuaid** [comment]
Yes. This is intentional and how all package managers work. Just ignore it and adjust your PATH.

**Comment by MikeMcQuaid** [comment]
Yes. This is intentional and how all package managers work. Just ignore it and adjust your PATH.
