### ISSUE TITLE
Allow projects to use their own version names

### ISSUE THREAD

**Issue by muuvmuuv** [Homebrew/brew#5313]
I have currently worked on a project which required Node.js and some NPM packages. I had installed Node.js at the very beginning with `brew install node`. In my project, I use a package (NativeScript) which requires the LTS version of Node and is not particularly working with the latest version. So I tried installing a previous version of Node with `brew install node@x` but this failed because it does not install NPM correctly. So I tried to get some help from the Node.js team (see: https://github.com/nodejs/help/issues/1599).

So what I actually aiming to is that it would help packages like Node to create there own version names like in this case `node@lts` and `node@latest` to point to exactly this version they describe on their website. This would help users and would reduce error when working with latest features that are not completely saved to use in some projects.

**Comment by MikeMcQuaid** [comment]
They can create their own packages if they wish in their own tap. The current packages are the supported path.

> with `brew install node@x` but this failed because it does not install NPM correctly.

This isn't enough information to help you with this. Please fill out the issue template and create a more detailed for this in Homebrew/homebrew-core.
