### ISSUE TITLE
Calling the `gpg` stanza is disabled

### ISSUE THREAD

**Issue by sinall** [Homebrew/brew#5318]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
`HOMEBREW_NO_AUTO_UPDATE=1 brew search xdebug`

- What happened (include command output)

> Error: Calling the `gpg` stanza is disabled! There is no replacement.
> Please report this to the homebrew/cask tap:
>   /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/1password-cli.rb:11
> 

- What you expected to happen
I should show 'xdebug' packages for install.

- Step-by-step reproduction instructions (by running `brew` commands)
$ brew --version
Homebrew 1.8.2
Homebrew/homebrew-core (git revision 9a7a4; last commit 2018-03-05)
Homebrew/homebrew-cask (git revision eeacc; last commit 2018-03-05)
$ HOMEBREW_NO_AUTO_UPDATE=1 brew search xdebug
Error: Calling the `gpg` stanza is disabled! There is no replacement.
Please report this to the homebrew/cask tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/1password-cli.rb:11

----
$ brew config
HOMEBREW_VERSION: 1.8.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 6f458aaed494eaab92622f41f9f1967add00b0f4
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9a7a4861e0bac012f38ec941c09987e57d3da63b
Core tap last commit: 8 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_AUTO_UPDATE: 1
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_131, 1.7.0_80
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node.bak/ares.h
  /usr/local/include/node.bak/ares_version.h
  /usr/local/include/node.bak/nameser.h
  /usr/local/include/node.bak/node.h
  /usr/local/include/node.bak/node_buffer.h
  /usr/local/include/node.bak/node_internals.h
  /usr/local/include/node.bak/node_object_wrap.h
  /usr/local/include/node.bak/node_version.h
  /usr/local/include/node.bak/openssl/opensslconf.h
  /usr/local/include/node.bak/uv-private/ngx-queue.h
  /usr/local/include/node.bak/uv-private/stdint-msvc2008.h
  /usr/local/include/node.bak/uv-private/tree.h
  /usr/local/include/node.bak/uv-private/uv-bsd.h
  /usr/local/include/node.bak/uv-private/uv-darwin.h
  /usr/local/include/node.bak/uv-private/uv-linux.h
  /usr/local/include/node.bak/uv-private/uv-sunos.h
  /usr/local/include/node.bak/uv-private/uv-unix.h
  /usr/local/include/node.bak/uv-private/uv-win.h
  /usr/local/include/node.bak/uv.h
  /usr/local/include/node.bak/v8-debug.h
  /usr/local/include/node.bak/v8-preparser.h
  /usr/local/include/node.bak/v8-profiler.h
  /usr/local/include/node.bak/v8-testing.h
  /usr/local/include/node.bak/v8.h
  /usr/local/include/node.bak/v8stdint.h
  /usr/local/include/node.bak/zconf.h
  /usr/local/include/node.bak/zlib.h

**Comment by wodin** [comment]
I had the same problem and finally managed to figure it out. I think this issue was closed because it was posted in the wrong place.

Basically, there were a bunch of old files in `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask`. You should be able to fix this as follows:

```
$ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
$ git clean -xdf
```

See https://discourse.brew.sh/t/brew-search-fails-with-error-calling-the-gpg-stanza-is-disabled-there-is-no-replacement/3472
