### ISSUE TITLE
Error: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by mikeboers** [Homebrew/brew#5324]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh **NOTE: I went to Discourse first; see <https://discourse.brew.sh/t/parent-directory-is-world-writable-but-not-sticky/3386/5>**
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? **NOTE: I can't upgrade the OS here.**
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

## What you were trying to do (and why)

I was attempting to use Homebrew/Linuxbrew in any capacity. Installation of Homebrew fails. Installation of packages (with a previous installation) fail.

The key point here is that I'm stuck on macOS 10.11, which `brew doctor` calls out as being unsupported. I'm having very similar failures on CentOS 7.

I first brought this up on the Discourse: <https://discourse.brew.sh/t/parent-directory-is-world-writable-but-not-sticky/3386/5>.

In that post I discuss how my Homebrew was in a non-standard location, but just now I've cleared up my environment and tried with a fresh Homebrew at `/usr/local`, and I get the same problems.

## What happened (include command output)

Please see https://gist.github.com/mikeboers/c9b222de6598903ef313fd8c3829c768 for command output.

I tried to debug this, but I'm a Python dev who isn't very familiar with Ruby. I added tons of `puts` all over the place, and it seems that all of my various errors go through `/usr/local/vee/homebrew/Library/Homebrew/extend/pathname.rb:167:in atomic_write`.

Printing out the path returned from `Dir.mktempdir`, I get (with my non-standard location of `/usr/local/vee/homebrew`):

- `/usr/local/vee/homebrew/Cache/.d20181106-21948-1xpbf73/.linkage.json20181106-21948-pef1lk`
- `/usr/local/vee/homebrew/Cellar/gmp/6.1.2_2/.d20181106-21948-zs3nsx/.INSTALL_RECEIPT.json20181106-21948-1ppv98h`

and a few others.

What seems very strange is that sometimes `INSTALL_RECEIPT` ones go through, and sometimes not.

## What you expected to happen

Temp directories to be creatable for the various processes.

## Step-by-step reproduction instructions (by running `brew` commands)

Failed clean installation:

```
sudo rm /usr/local
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

Installing packages does much the same thing.

Honestly... if this is going to be declared that you don't support these OSes, that is fine. My client will have to deal with paying me to work around it. I'd just like to know and move on. Homebrew is one part of the stack here, and I have the capability of building my own packages, but it has been such an immense convenience for the ~5 years that I've used Homebrew in this way for my clients. I'd really rather hope that someone sees an easy fix despite not being officially supported.

**Comment by reitermarkus** [comment]
There are two PRs related to this which might help you with debugging this:

- https://github.com/Homebrew/brew/pull/5009
- https://github.com/Homebrew/brew/pull/5127

**Comment by mikeboers** [comment]
@reitermarkus thanks for the PRs.

I think I read through those while trying to uncover the commit that this behaviour started for me. I'm using the current `stable` which appears to include them.

There might be something else weird about my environment. I guess I'll have to assert those methods make sense line by line to figure out where the discrepancy is.

**Comment by MikeMcQuaid** [comment]
> * `/usr/local/vee/homebrew/Cache/.d20181106-21948-1xpbf73/.linkage.json20181106-21948-pef1lk`

@mikeboers Have you set a custom `HOMEBREW_CACHE`?

**Comment by mikeboers** [comment]
I did have a custom cache set at that point of debugging, but before opening this I tested with a completely clean environment, and I get the same error even during the install. I don't have it pinpointed what files were attempting to be written at that point.

**Comment by mikeboers** [comment]
... I don't have them pinpointed because I don't know how to do that during the install process. Once it is in there, I'll go and edit whatever code (and disable the auto-updater) and then can add print statements to my heart's content.

I'd love to hear any better suggestions on debugging Ruby that you think a Python dev could deal with.

**Comment by MikeMcQuaid** [comment]
@mikeboers have you tried running with `--debug`?

**Comment by mikeboers** [comment]
With `--debug` and its tracebacks, I can see all my problems are in `tmpdir.rb:Dir.mktmpdir` via `extend/pathname.rb:atomic_write`.

First one for `/Volumes/home/mikeb/Library/Caches/Homebrew/linkage.json`:

```
==> Installing dependencies for git: gettext and pcre2
==> Installing git dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.el_capitan.bottle.tar.gz
Updating Homebrew...
######################################################################## 100.0%
==> Pouring gettext-0.19.8.1.el_capitan.bottle.tar.gz
Error: parent directory is world writable but not sticky
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:167:in `atomic_write'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:43:in `close_if_open!'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:16:in `use'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1802:in `undeclared_runtime_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1564:in `runtime_dependencies'
<snip>
```

and second for `/usr/local/vee/packages/homebrew/Cellar/gmp/6.1.2_2/INSTALL_RECEIPT.json`:

```Error: parent directory is world writable but not sticky
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:167:in `atomic_write'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:43:in `close_if_open!'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:16:in `use'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:642:in `finish'
<snip>
```


I started adding a pile of `puts` in `atomic_write` and `Dir.mktmpdir` to check all the logic and so forth. I thought maybe my filesystem is doing something weird (I am on macOS 10.11 with my home mounted via NFS):

- The directory there has permissions `777`; it is world_writable, but not sticky; `should_fix_sticky_bit` is true, and so it sets the directory to be sticky
- The file gets writen.
- Since `should_fix_sticky_bit`, it removes the sticky bit.
- `Dir.mktmpdir` then checks `stat.world_writable? and !stat.sticky?`, which is true... and then raises the error.

It really feels to me like `atomic_write` is exactly causing the problem that `Dir.mktmpdir` is complaining about. Should the resetting of the sticky bit not be outside of the `mktmpdir` block?

This is literally the first Ruby I've written, but [this appears to fix my problem](https://github.com/mikeboers/brew/commit/037eef12385765f8b78f36f47af4e953199fcf48).

Also setting the sticky bit manually fixes the problem. I'm not sure why I stopped having Cellar problems at this point... I'll keep looking the next time I trigger it.

**Comment by reitermarkus** [comment]
Feel free to submit your fix as a PR, it's easier to review that way.

**Comment by MikeMcQuaid** [comment]
Agreed on submitting the PR.

> I am on macOS 10.11 with my home mounted via NFS

It would be good to disclose this earlier in future. This is almost certainly the root of the problems.

**Comment by mikeboers** [comment]
To be fair, I did say the bit about 10.11 in my opening message, and the errors are occurring on the local (HFS+) volume. I think I tried it with a local user too. I'll try that tomorrow to be sure.

I'll open the PR, but be nice. I don't know what I'm doing. ;)

**Comment by mikeboers** [comment]
I'm pretty sure my client isn't going to care to have me put more effort into this, and I don't have this problem with this setup elsewhere. So... I'm going to close this unless I have to come back to it.

Thanks, everyone, for your time.

**Comment by convenient** [comment]
@mikeboers than you so much for this commit https://github.com/mikeboers/brew/commit/037eef12385765f8b78f36f47af4e953199fcf48

This error was happening when installing `blackfire-php70` for one of my team.

I hotfixed your code change and it worked like a charm.

```
nano +167 /usr/local/Homebrew/Library/Homebrew/extend/pathname.rb
# apply patch
HOMEBREW_NO_AUTO_UPDATE=1 brew install blackfire-php70
brew install blackfire-php70 # to clean up hack
```

**Comment by MikeMcQuaid** [comment]
Does someone want to submit a pull request for it?

**Comment by convenient** [comment]
@mikeboers I'm sure we can open the PR from your fork like this?

https://github.com/Homebrew/brew/compare/master...mikeboers:ensure_sticky?expand=1

Perhaps if you sync it up with `master` so no merge conflicts? 

Otherwise i'll cherry-pick it in and sort a PR.

**Comment by MikeMcQuaid** [comment]
@convenient I'd suggest creating your own PR so you can push to it.

It may also be worth verifying this hasn't been fixed by https://github.com/Homebrew/brew/pull/5338

**Comment by mikeboers** [comment]
@convenient Thanks for bringing this back up. I'd ask that you take the reigns on this from me. I'm not comfortable with it, and I don't think I can justify taking the time to fix aspect.
