### ISSUE TITLE
reinstall with options

### ISSUE THREAD

**Issue by vitalyster** [Homebrew/brew#5327]
Current flow:
```
$ brew install emacs
Updating Homebrew...
[..]
==> Downloading https://homebrew.bintray.com/bottles/emacs-26.1_1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/emacs/26.1_1: 3,985 files, 103.6MB
$ emacs
```
(oh, still apple emacs, how to start new one?)
```
$ /usr/local/bin/emacs
```
(great, but without gui, what option to install gui?)
```
$ brew edit emacs
```
(great, `--with-cocoa`)
```
$ brew install emacs --with-cocoa
Warning: emacs 26.1_1 is already installed and up-to-date
To reinstall 26.1_1, run `brew reinstall emacs`
$ brew reinstall emacs --with-cocoa
Error: invalid option: --with-cocoa
```
(ah, need to remove and install again!)
```
$ brew remove emacs
Uninstalling /usr/local/Cellar/emacs/26.1_1... (3,985 files, 103.6MB)
$ brew install emacs --with-cocoa
==> Downloading https://ftp.gnu.org/gnu/emacs/emacs-26.1.tar.xz
##################################                                        48.3%
```
Is it possible to simplify at least with `reinstall --with-option` ?

**Comment by MikeMcQuaid** [comment]
> Is it possible to simplify at least with `reinstall --with-option` ?

Sorry, no. That said, when you `brew reinstall` it will use all your existing options.

**Comment by vitalyster** [comment]
@MikeMcQuaid so you didn't saw anything unusual in my log and considering this as day to day workflow with brew?

**Comment by MikeMcQuaid** [comment]
@vitalyster The unusual thing is you're passing `--with-cocoa` when it's not necessary as it's implicit.

**Comment by Capt0r** [comment]
I'd like to reopen this as it is not at all desirable behaviour nor is it an unusual thing at all - in my case I need to enable flags that weren't enabled when I initially installed ffmpeg (it has... a lot of options):

```
brew reinstall ffmpeg --with-fdk-aac
Error: invalid option: --with-fdk-aac
```

Forcing people to run `uninstall` then `install` while having a `reinstall` command is... nonsensical, and cost a lot of wasted time and headaches for me and my team.

The ideal here would be to retain the flags that were used on first install implicitly so I don't have to list them all again, while still allowing me to add additional flags - and simply ignore any duplicates I provide explicitly (as in @vitalyster's case).  Could also have a `--reset` option or something to clear all those implicit flags for a fresh (re)install.

**Comment by MikeMcQuaid** [comment]
> cost a lot of wasted time and headaches for me and my team.

Homebrew costs you nothing and I'd suggest you and your team be a bit more grateful for the work of volunteers that helps you accomplish your job.
