### ISSUE TITLE
Add option for openssh with readline support

### ISSUE THREAD

**Issue by MagnusBrzenk** [Homebrew/brew#5328]
Feature: add an option for installation of openssh such that sftp has autocomplete and log-history support (aka 'readline' support, as is the case with e.g. ssh).

Motivation: I can't believe I'm the first Mac user to want sftp tab-autocomplete, etc. Is everyone else suffering in silence?

**Comment by MikeMcQuaid** [comment]
We're not interested in adding new options. We'll review a PR to add it by default, though. Thanks!
