### ISSUE TITLE
Add outdated alias

### ISSUE THREAD

**Issue by nrlquaker** [Homebrew/brew#5330]
# A detailed description of the proposed feature
Is it possible to add `out` alias to `outdated`?

# The motivation for the feature
To be more convenient. `npm` has one.

# How the feature would be relevant to at least 90% of Homebrew users
Will be useful I think.

# What alternatives to the feature have been considered
Typing `outdated` all the time.

**Comment by scpeters** [comment]
The relevant code is here:

* https://github.com/Homebrew/brew/blob/master/Library/Homebrew/brew.sh#L269-L286

**Comment by MikeMcQuaid** [comment]
Use https://github.com/Homebrew/homebrew-aliases or a Bash alias.
