### ISSUE TITLE
readline support for sftp

### ISSUE THREAD

**Issue by MagnusBrzenk** [Homebrew/brew#5334]
# A detailed description of the proposed feature

Make readline support default for openssh installations so that sftp has autocomplete and log history. 

# The motivation for the feature

Navigating around filesystems with an sftp connection is incredibly tedious when you have to spell out the full names of the files/dirs. I recall wanting this support when using sftp-ing into linux ~10 years ago. I'm astonished that all these years later I still seem to be the only one suffering in silence.

# How the feature would be relevant to at least 90% of Homebrew users

I havent done a poll, but just cant imagine why sftp users wouldnt want autocomplete and log-history support.

# What alternatives to the feature have been considered

I googled combinations such as `sftp autocomplete mac` and there's very little by way of solution available in the forums. What suggestions I found were outdated/deprecated.

**Comment by MikeMcQuaid** [comment]
We'll consider a PR to add this but it's not a "feature" per-se.
