### ISSUE TITLE
Change lists fetching to APT way or similar

### ISSUE THREAD

**Issue by misha-plus** [Homebrew/brew#5339]
# A detailed description of the proposed feature
Replace homebrew source lists to the lists system which will be similar to APT Lists in the Debian (read plain list without Git).

# The motivation for the feature

Updating of Homebrew lists is very slow. It takes a few minutes because brew takes full repository from GitHub.

# How the feature would be relevant to at least 90% of Homebrew users

The speed of downloading a fresh list will be fast. This will work for all users. So most Homebrew users will see the speed boost.

# What alternatives to the feature have been considered

Maybe just fetch only the top commit of the repository through Git is enough to work fast.

**Comment by MikeMcQuaid** [comment]
This would require rewriting the way we do updates so won't happen, sorry.

> It takes a few minutes because brew takes full repository from GitHub.

The first time. Afterwards it's only an incremental diff. What you propose would make the first fetch faster but each additional one would be slower.
