### ISSUE TITLE
Add Some Way To Quickly Sync One's Personal `brew` and Tap Forks With Upstream

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/brew#5345]
## A detailed description of the proposed feature

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There should be some easy way to quickly push updates pulled down from upstream into your local `brew` and tap installations when you run '`brew update`' up into each of your corresponding personal GitHub forks for them.  This could get implemented as a new command (tentatively proposed here named as '`brew update-forks`' prior to expected bikeshedding.)  

## The motivation for the feature

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Contributors to Homebrew's internals and official taps likely desire to update their personal GitHub forks of the relevant repositories to reflect the latest upstream state on more then the odd occasion.  (This aids in preparing and staging changes against '`master`' in a new branch in any such fork in question, as one cannot easily demonstrate on it that these changes do not conflict against upstream before creating a PR without mirroring its state inside that fork to compare against.)  In order for users to update their personal forks against upstream after fetching their changes locally, they must currently drop down into their corresponding repositories' local copies and perform the Git operations needed for this manually.  This could be streamlined through automation.  

## How the feature would be relevant to at least 90% of Homebrew users

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This feature will be relevant for all contributors to Homebrew's internals and core taps, as it will shorten the lifecycle of changes meant to be submitted as PRs and expedite their Git flow.  

## What alternatives to the feature have been considered

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Adding this functionality to '`brew`' as a new flag to its '`update`' sub-command instead of as a new sub-command altogether was briefly considered.  I quickly realized, however, that such an implementation had the potential to easily confuse users, who might mistake invoking '`brew update`' with this new flag to mean that a normal '`brew update`' would be performed first before the new functionality was triggered.  If such functionality is ever desired, it should be considered later as a potential future extension, which I have also listed just below in a section on these.  

## What possible future extensions have been considered

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The following possible future extensions might prove desirable at a later date:  

1. As mentioned above, a variant of '`brew update`' triggered with a new flag one could pass to it that performs a normal '`brew update`' first before triggering the new functionality could add still another further potential workflow improvement contributors could use.  
1. Additionally, it might, at some time, come in handy to be able to specify only a subset of repositories to synchronize in the way described here instead of only allowing all of them to have their personal GitHub forks updated.  

## What proposals aren't considered here

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As it might require non-trivial interaction on the part of users to rebase their PR-staging branches against their containing repositories' default branches should conflicts arise between the latter and any of the former, the ability to automate the pulling of changes from upstream and pushing of rebased changes to the corresponding personal fork's relevant branch is not proposed at this time.

**Comment by MikeMcQuaid** [comment]
Again, I don’t understand what you’re actually wanting to happen here. What git commands would you expect this to run? Why would it be better than running those git commands yourself?

As a more general comment: please try and answer questions on existing issues before opening more and please edit your writing more to be considerably more concise. You tend to err on very verbose yet ambiguous and unclear communication.

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  

> …What git commands would you expect this to run?  …

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I'd expect the new command to run:  

```
git checkout master
git push
git checkout stable
git push
```

for Homebrew/brew if you have a personal fork of it and:  

```
git push
```

for all other taps of which you have personal forks.  (This naturally assumes you've already set up remotes for each of the repositories for which you've made personal forks and added the following lines to each of their Git configurations:  

```
⋮
[push]
        default = current
[remote]
        pushDefault = <name of your fork's remote>
⋮
```

to set them up to fit into a triangular Git workflow by default.)  

> …Why would it be better than running those git commands yourself?
>
> ⋮

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It's not terribly hard to forget to push changes for one of the repositories you've forked to your GitHub user copy of it.  The automation of the relevant Git operations would help in limiting human error.  

> ⋮
>
> As a more general comment: please try and answer questions on existing issues before opening more…

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sorry, I hadn't seen any comments appear on that other issue thread yet when I created this one.  

> …and please edit your writing more to be considerably more concise. You tend to err on very verbose yet ambiguous and unclear communication.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I'm unsure quite how I could keep things shorter without violating the format/spirit/intent of the required issue templates at times while still including all relevant information, but, thanks, I'll do my best to keep that in mind.  My apologies, though, if I've ever left anybody scratching their heads for too long.

**Comment by MikeMcQuaid** [comment]
> for Homebrew/brew if you have a personal fork of it

Why would you want/need the master branch to be updated on your forks?



>      It's not terribly hard to forget to push changes for one of the repositories you've forked to your GitHub user copy of it.

Why do you need to do this if you're not creating a pull request?



>      I'm unsure quite how I could keep things shorter without violating the format/spirit/intent of the required issue templates at times while still including all relevant information, but, thanks, I'll do my best to keep that in mind. My apologies, though, if I've ever left anybody scratching their heads for too long.

It's a general comment on your issues and comments. In most threads you're in it's worth checking out the length of your comments compared to that of others and asking how many piece of information you have for each comment. Bullet point lists and avoiding prose may help you be more concise.

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  

>> for Homebrew/brew if you have a personal fork of it
>
> Why would you want/need the master branch to be updated on your forks?
>
> ⋮

1. You might be about to create a pull request against it.  Having Git state synchronized between all instances of a given repository or any of its branches reduces the chance for conflicts between your personal GitHub fork of said repository and upstream even if your local working copy is up to date.  

> ⋮
>
>> It's not terribly hard to forget to push changes for one of the repositories you've forked to your GitHub user copy of it.
>
> Why do you need to do this if you're not creating a pull request?
>
> ⋮

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You don't, but I've been making PRs lately.  It was, however, admittedly slightly naïve of me to assume that implementing the core logic for this would be as trivial as using a simple loop through all repositories which one has local copies of, as the code couldn't necessarily safely assume that you had corresponding personal GitHub forks for all of them.  Given that such repository filtering would have to be implemented even before my suggested future extension to allow users to provide only specific repositories to sync on the command line, it could make sense to just include that latter functionality initially.  

> ⋮
>
>> I'm unsure quite how I could keep things shorter without violating the format/spirit/intent of the required issue templates at times while still including all relevant information, but, thanks, I'll do my best to keep that in mind. My apologies, though, if I've ever left anybody scratching their heads for too long.
>
> It's a general comment on your issues and comments. In most threads you're in it's worth checking out the length of your comments compared to that of others and asking how many piece of information you have for each comment. Bullet point lists and avoiding prose may help you be more concise.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OK, thanks.

**Comment by RandomDSdevel** [comment]
Aside:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I thought this would be useful for more people than just myself, but perhaps a personal shell script might be more suited for what I have in mind here, at least for now.

**Comment by MikeMcQuaid** [comment]
> 1. You might be about to create a pull request against it.

That doesn't use the `master` of your fork. Nothing does, really.

---

I think this would be best implemented as an external command: https://docs.brew.sh/External-Commands

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  

> ⋮
>
> I think this would be best implemented as an external command: https://docs.brew.sh/External-Commands

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Agreed; I now have an initial attempt at an implementation set up in [a personal 'homebrew-update-forks' tap](https://github.com/RandomDSdevel/homebrew-update-forks).  I can't quite seem to get it working all the way, though; would you mind checking over my '`bash`' syntax any?  In particular, [issue #1](https://github.com/RandomDSdevel/homebrew-update-forks/issues/2) befuddles me.  (You don't have to agree with my ill-defined reasoning for wanting to track various Homebrew-upstream repositories.  I suppose a more valid motivation for doing this would generally be just to make repeated branching off of '`master`' easier, in the sense that the results would always be up to date against it to start with, if one planned to continue making contributions to a project, but I digress…)
