### ISSUE TITLE
Manage shell profile additions automatically

### ISSUE THREAD

**Issue by yschimke** [Homebrew/brew#5347]
# A detailed description of the proposed feature

Similar to bash completion hooks, support installing startup script into the appropriate of https://www.rubydoc.info/github/Homebrew/brew/Utils/Shell#profile-class_method

# The motivation for the feature

Many recipes print out things like

```
==> Caveats
google-cloud-sdk is installed at /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk. Add your profile:

  for bash users
    source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc'
    source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc'

  for zsh users
    source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
    source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
```

# How the feature would be relevant to at least 90% of Homebrew users

Most receipes needing these features installed do not work well without, also when installing multiple transitive recipes, there may be assumptions this is already done.

# What alternatives to the feature have been considered

Each recipe edits the user profile directly, but that is awkward to revert.

**Comment by MikeMcQuaid** [comment]
We will never do this automatically as we don't modify home directory files.

**Comment by yschimke** [comment]
@MikeMcQuaid Can it be done by a user opting in to loading a central script that sources all per app scripts? That is similar to the bash completion hook approach.
