### ISSUE TITLE
Installing Qt triggers local compilation

### ISSUE THREAD

**Issue by yshurik** [Homebrew/brew#5354]
# What you were trying to do (and why)

on osx 10.11:

brew install qt

# What happened (include command output)

It trys to compile qt locally which completely undesired (time, cpu, space, resources!)

<details>
  <summary>Command output</summary>
  <pre>
  
==> Installing qt
==> Downloading https://download.qt.io/official_releases/qt/5.11/5.11.2/single/q
==> Downloading from http://qt.mirror.constant.com/archive/qt/5.11/5.11.2/single
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e8fe6
...  

  </pre>
</details>

# What you expected to happen

Expected just binary install...
<pre>
==> Downloading https://homebrew.bintray.com/bottles/qt-5.11.2.el_capitan.bottle
######################################################################## 100.0%
==> Pouring qt-5.11.2.el_capitan.bottle.tar.gz
</pre>

# Step-by-step reproduction instructions (by running `brew` commands)

on osx 10.11:

brew install qt

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by yshurik** [comment]
Added

**Comment by MikeMcQuaid** [comment]
> * [ ]  ran `brew config` and `brew doctor` and included their output with your issue?

You didn't do this.

**Comment by yshurik** [comment]
Ok, added

**Comment by MikeMcQuaid** [comment]
> Warning: You are using macOS 10.11. We (and Apple) do not provide support for this old version. You will encounter build failures and other breakages.

This is your issue. We don't build binary packages for 10.11 any longer, sorry.

**Comment by scpeters** [comment]
The qt bottle was rebuilt recently as a consequence after merging https://github.com/Homebrew/homebrew-core/pull/34412 to fix https://github.com/Homebrew/homebrew-core/issues/34340

Old bottles can last as long as a formula is unchanged, but new bottles are only built for the 3 most recent versions of macOS, so the 10.11 bottle was removed when the new bottle hashes were added:

* https://github.com/Homebrew/homebrew-core/commit/5eb54ced793999e3dd3bce7c64c34e7ffe65ddfd

This isn't a bug, so if you want any further information, please ask a question on 
https://discourse.brew.sh/

**Comment by yshurik** [comment]
I see, just my note that mojave is not really widely adopted yet, so in reality now you support only about 2 most recent. I see el capitan is still in wide use by my experience. (sure it is up to project policy)

**Comment by MikeMcQuaid** [comment]
In the last 30 days 55% of our installs were on Mojave and 3% on El Capitan: https://formulae.brew.sh/analytics/os-version/30d/
