### ISSUE TITLE
CurlDownloadStrategy producing unnecessary, duplicate network requests

### ISSUE THREAD

**Issue by kabel** [Homebrew/brew#5357]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Download a formula resource.

# What happened (include command output)

Curl downloaded resources that are not cached are having the URL resolved multiple times (duplicate curl --head requests sent). This is unnecessary network traffic.

<details>
  <summary>Command output</summary>
  <pre>
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/php.rb
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4-7-gaed895c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --location --silent --head https://php.net/get/php-7.2.12.tar.xz/from/this/mirror
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4-7-gaed895c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --location --silent --head https://php.net/get/php-7.2.12.tar.xz/from/this/mirror
==> Downloading https://php.net/get/php-7.2.12.tar.xz/from/this/mirror
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4-7-gaed895c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --location --silent --head https://php.net/get/php-7.2.12.tar.xz/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-7.2.12.tar.xz
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4-7-gaed895c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/kabel/Library/Caches/Homebrew/downloads/55b491e15e68a5aa001cebb8ad0cbb934dfdf962e14b567d8de5eab1af400871--php-7.2.12.tar.xz.incomplete https://secure.php.net/distributions/php-7.2.12.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.5M  100 11.5M    0     0  11.6M      0 --:--:-- --:--:-- --:--:-- 11.6M
Downloaded to: /Users/kabel/Library/Caches/Homebrew/downloads/55b491e15e68a5aa001cebb8ad0cbb934dfdf962e14b567d8de5eab1af400871--php-7.2.12.tar.xz
SHA256: 989c04cc879ee71a5e1131db867f3c5102f1f7565f805e2bb8bde33f93147fe1
==> Verifying 55b491e15e68a5aa001cebb8ad0cbb934dfdf962e14b567d8de5eab1af400871--php-7.2.12.tar.xz checksum
  </pre>
</details>

# What you expected to happen

Only a single HEAD request is issued for the lifetime of the resource object.

# Step-by-step reproduction instructions (by running `brew` commands)

`brew fetch php --verbose --debug --build-from-source`

**Comment by MikeMcQuaid** [comment]
HEAD requests use really negligible amounts of bandwidth. We’d review a PR to cache these but I’m not convinced it’s a bug (particularly with the combination of flags you’re using). CC @reitermarkus who can provide more context.
