### ISSUE TITLE
Unable to install Homebrew

### ISSUE THREAD

**Issue by wmedali** [Homebrew/brew#5363]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
it tells me that : 
Already up-to-date.
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
<details>
  <summary>`brew doctor ` Command output</summary>
  <pre>
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
Already downloaded: /Users/g516706/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
Error: Checksum mismatch.
Expected: 033ac518bb14abdb1bb47d968dc9e967c3ae2035499383a21a79b49d523065d1
Actual: 64318e17bc7739e8fb0b6ff950ddf88e3ad3482a57c4f059fb13a11f5017f739
Archive: /Users/g516706/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.
</pre>
</details>
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?
<details>
  <summary>`brew config`  Command output</summary>
  <pre>
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
Already downloaded: /Users/g516706/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
Error: Checksum mismatch.
Expected: 033ac518bb14abdb1bb47d968dc9e967c3ae2035499383a21a79b49d523065d1
Actual: 64318e17bc7739e8fb0b6ff950ddf88e3ad3482a57c4f059fb13a11f5017f739
Archive: /Users/g516706/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.
</pre>
</details>

# What you were trying to do (and why)

I am trying to install brew command

# What happened (include command output)

It always stops due to checksum mismatch error here is the output of the command 
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

even if I delete /Users/MyUser/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz and try again It doesn't work.

I work on the following environment 

Mac OS X High Sierra 10.13.1
<details>
  <summary>Command output</summary>
  <pre>
  
  mac-C07KJ1LCDY3H:~ g516706$ /usr/bin/ruby -e "$(curl -f https://raw.githubusercontent.com/Homebrew/install/master/install)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14537  100 14537    0     0  24218      0 --:--:-- --:--:-- --:--:-- 24228
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /Users/g516706/Library/Caches/Homebrew
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /Users/g516706/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown g516706 /Users/g516706/Library/Caches/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at 30c90dcc3 Merge pull request #5359 from claui/tls-coming-home
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
######################################################################## 100.0%
Error: Checksum mismatch.
Expected: 033ac518bb14abdb1bb47d968dc9e967c3ae2035499383a21a79b49d523065d1
Actual: 64318e17bc7739e8fb0b6ff950ddf88e3ad3482a57c4f059fb13a11f5017f739
Archive: /Users/g516706/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.
Failed during: /usr/local/bin/brew update --force
mac-C07KJ1LCDY3H:~ g516706$ clear

mac-C07KJ1LCDY3H:~ g516706$ /usr/bin/ruby -e "$(curl -f https://raw.githubusercontent.com/Homebrew/install/master/install)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14537  100 14537    0     0  22225      0 --:--:-- --:--:-- --:--:-- 22193
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at 30c90dcc3 Merge pull request #5359 from claui/tls-coming-home
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
Already downloaded: /Users/g516706/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
Error: Checksum mismatch.
Expected: 033ac518bb14abdb1bb47d968dc9e967c3ae2035499383a21a79b49d523065d1
Actual: 64318e17bc7739e8fb0b6ff950ddf88e3ad3482a57c4f059fb13a11f5017f739
Archive: /Users/g516706/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.
Failed during: /usr/local/bin/brew update --force
  
  </pre>
</details>

# What you expected to happen

I expected that brew would be installed

**Comment by MikeMcQuaid** [comment]
> Archive: /Users/g516706/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
> To retry an incomplete download, remove the file above.

Did you try this?

**Comment by wmedali** [comment]
@MikeMcQuaid 
Yes 
even if I delete .../Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz and try again It doesn't work.

**Comment by MikeMcQuaid** [comment]
You’ll need to figure out why you cannot download that file required for Homebrew.
