### ISSUE TITLE
macOS 10.14.1 (case sensitive APFS) brew audit fails with "Error installing rubocop"

### ISSUE THREAD

**Issue by MoritzFago** [Homebrew/brew#5372]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
Only warnings remain, both accounted for.
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
Output: https://gist.github.com/MoritzFago/456fd7b8b5f52def47f6ecb8c00f7da5

# What you were trying to do (and why)
Run `brew audit` on any formula, because I wanted to submit a new one.

# What happened (include command output)
`brew audit` fails to install rubocop (I think).

<details>
  <summary>Command output</summary>
  <pre>
  
==> Installing or updating 'rubocop' gem
Building native extensions.  This could take a while...
ERROR:  Error installing rubocop:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.1/ext/jaro_winkler
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181203-73184-qt24n4.rb extconf.rb
creating Makefile

current directory: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.1/ext/jaro_winkler
make "DESTDIR=" clean

current directory: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.1/ext/jaro_winkler
make "DESTDIR="
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `adj_matrix.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.1 for inspection.
Results logged to /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1/gem_make.out
Error: Failed to install/update the 'rubocop' gem.
  
  </pre>
</details>

# What you expected to happen

Some output about what to fix in my new formula.
# Step-by-step reproduction instructions (by running `brew` commands)
1. run `brew audit fastd`

**Comment by MikeMcQuaid** [comment]
This is something specific to either your machine or case-sensitive APFS I'm afraid so you'll need to figure it out yourself. If you do figure out something that warrants a PR: we'll review it.

**Comment by MoritzFago** [comment]
The fix was: `brew vendor-install ruby` as per [this issue](https://github.com/Homebrew/brew/issues/4998), this is also known by [upstream](https://github.com/tonytonyjan/jaro_winkler/issues/22).
I suspect it only applies if you have reinstalled for mojave instead of upgraded. 
Maybe add a check to `brew doctor`, also I couldn't find `vendor-install` in the man page or somewhere else documented. Is there documentation?

**Comment by MikeMcQuaid** [comment]
> The fix was: `brew vendor-install ruby` as per [this issue](https://github.com/Homebrew/brew/issues/4998), this is also known by [upstream](https://github.com/tonytonyjan/jaro_winkler/issues/22).

That's not an issue on 10.14.



> Maybe add a check to `brew doctor`, also I couldn't find `vendor-install` in the man page or somewhere else documented. Is there documentation?

This is not a supported fix yet.
