### ISSUE TITLE
Create `brew donate`

### ISSUE THREAD

**Issue by purp** [Homebrew/brew#5386]
# A detailed description of the proposed feature

`brew donate` should open `https://github.com/Homebrew/brew#donations`

I'm happy to offer a pull request.

# The motivation for the feature

I happened to see the call to donate while updating and it occurred to me that it would be handy to see this any time.

# How the feature would be relevant to at least 90% of Homebrew users

It would be a helpful if a brew user wants to donate and can't remember the URL or how to find it.

# What alternatives to the feature have been considered

Not doing anything.

**Comment by purp** [comment]
Added a pull request #5387

**Comment by MikeMcQuaid** [comment]
Let's discuss on the pull request. For future reference we don't need an issue if there's already a PR.
