### ISSUE TITLE
pkg-config doesn't pickup the homebrew pkg-config path

### ISSUE THREAD

**Issue by andyli** [Homebrew/brew#539]
Discovered from our [TravisCI build](https://travis-ci.org/andyli/neko/jobs/145340092) that suddenly fails recently.

In the build, after migrating Homebrew to v0.9.9, the pkg-config path search path is not updated:
```
$ pkg-config --variable pc_path pkg-config
/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.9
```
where `/usr/local/Library/ENV/pkgconfig/10.9` should be `/usr/local/Library/Homebrew/os/mac/pkgconfig/10.9`.

**Comment by ilovezfs** [comment]
You need to brew update. This was fixed.
https://github.com/Homebrew/brew/commit/356018501b83364ac4f41aad26ca795c3b2fb8cb

**Comment by andyli** [comment]
But my build log shows that brew was upgraded to 092d471, which was the most recent commit as of writing.

**Comment by ilovezfs** [comment]
@andyli It looks like your problem may be here:
https://github.com/andyli/neko/blob/master/.travis.yml#L44-L49

It doesn't upgrade anything but cmake, and the path is hard coded in the pkg-config binary, so you need to at least upgrade pkg-config too, but I'd suggest just making it `brew upgrade` and see what else is outdated in that image.

**Comment by andyli** [comment]
Doing `brew upgrade pkg-config` after `brew update` fixed it. Thanks!
FYI, I tried `brew upgrade` too, which worked, but it takes too long in TravisCI.

**Comment by ilovezfs** [comment]
@andyli that's great! Glad you got it working.
