### ISSUE TITLE
bad URI(is not URI?): :pserver:anonymous:@

### ISSUE THREAD

**Issue by sjackman** [Homebrew/brew#5398]
This issue arose on Linux. It seems that it should affect macOS as well (unconfirmed).

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

`brew udpate`

# What happened (include command output)

```console
$ brew update
Updated Homebrew from 78b2b7fac to 0739202ea.
Updated 1 tap (homebrew/core).
==> Migrating cache entries...
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/curlftpfs.rb
bad URI(is not URI?): :pserver:anonymous:@curlftpfs.cvs.sourceforge.net:/cvsroot/curlftpfs
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/global.rb
bad URI(is not URI?): :pserver:anonymous:@cvs.savannah.gnu.org:/sources/global
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/id3lib.rb
bad URI(is not URI?): :pserver:anonymous:@id3lib.cvs.sourceforge.net:/cvsroot/id3lib
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libowfat.rb
bad URI(is not URI?): :pserver:cvs:@cvs.fefe.de:/cvs
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mandoc.rb
bad URI(is not URI?): anoncvs@mandoc.bsd.lv:/cvs
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/myman.rb
bad URI(is not URI?): :pserver:anonymous:@myman.cvs.sourceforge.net:/cvsroot/myman
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ncp.rb
bad URI(is not URI?): :pserver:cvs:@cvs.fefe.de:/cvs
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/percona-toolkit.rb
no implicit conversion of nil into String
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/schroedinger.rb
no implicit conversion of nil into String
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/squid.rb
no implicit conversion of nil into String
Error: Failed to import: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/terminator.rb
no implicit conversion of nil into String
==> Migrating cache entries...
==> New Formulae
…
```

# What you expected to happen

Update successfully.

# Step-by-step reproduction instructions (by running `brew` commands)

```sh
docker run -it --rm linuxbrew/brew
brew update
```

**Comment by sjackman** [comment]
A second `brew update` is fine, so perhaps this issue is a non-issue. Feel free to close if so.

**Comment by MikeMcQuaid** [comment]
I also saw this on macOS actually. The issue here was with a shallow clone of Homebrew/brew which meant that `initial_version` wasn't set in the updater causing `Migrating cache entries` to be called unnecessarily. The CVS issue looks like trying to create a URI from a CVS "URL" (which isn't really one).

To be honest it's been enough time we could probably tear out all the cache migration code now.
