### ISSUE TITLE
option for brew audit to relax github notable status (for unofficial taps)

### ISSUE THREAD

**Issue by kaos** [Homebrew/brew#54]
### Bug reports:

Hosting a tap, and like to run basic audit checks on it using travis. But fails due to formulas using github repos that are not notable enough according to core requirements.

### Feature Requests:

Add option to test-bot / audit to relax / skip the github repo checks.

I'm willing to implement this if it is something that is acceptable.

**Comment by mikemcquaid** [comment]
You can just use `brew audit --strict` and skip `--online` in this case. We don't plan to ever offer specific opt-outs for rules, sorry.

**Comment by xu-cheng** [comment]
For your own purpose, you can try `export HOMEBREW_NO_GITHUB_API=1`.

**Comment by kaos** [comment]
Ah, thanks @xu-cheng that sounds like a nice option.

@mikemcquaid my issue, I realize I didn't put clearly enough, was that I use `brew test-bot`, so was not in control of which options were being passed to `audit`.

But it may very well be that I could simply just use `brew audit` instead of the `test-bot`. Will have a go with that.

**Comment by mikemcquaid** [comment]
@kaos I'd recommend continuing to use the `test-bot`. We would definitely accept a patch to disable e.g. `--online` or set that environment variable on the `test-bot` as we want that to be useful for project CI.

**Comment by kaos** [comment]
@mikemcquaid This can be solved with documentation. The option suggested by @xu-cheng works wonders :)

I had a new formula pass the audit step, with the `--online` check present.
