### ISSUE TITLE
Virtualenv installation error with system python

### ISSUE THREAD

**Issue by arthaud** [Homebrew/brew#5409]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Hello,

I'm the maintainer of a tap (nasa-sw-vnv/core).
Some of my users reported a bug when installing a package, see nasa-sw-vnv/homebrew-core#1
My formula `ikos` needs python, so I'm using a virtualenv, as recommended in the documentation at  https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md
The users are getting an error during the installation of virtualenv, when using the system python.

# What happened (include command output)

```
$ brew install nasa-sw-vnv/core/ikos
==> Installing nasa-sw-vnv/core/ikos
==> Downloading https://github.com/nasa-sw-vnv/ikos/releases/download/v2.1/ikos-2.1.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/107311216/9
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/ikos--homebrew-vi
Last 15 lines from /Users/dennis/Library/Logs/Homebrew/ikos/01.python:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/ikos--homebrew-virtualenv-20181212-49529-ennkdu/target
--install-scripts=/private/tmp/ikos--homebrew-virtualenv-20181212-49529-ennkdu/target/bin
--single-version-externally-managed
--record=installed.txt

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
error in virtualenv setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
```

It looks like the system `setuptools`(18.5) is outdated and cannot handle the `setup.py` of virtualenv.

I kept digging and got the following error in the `setup.py`:

```
Traceback (most recent call last):
  File "setup.py", line 107, in <module>
    'pytest-timeout >= 1.3.0, <2; platform_python_implementation!="Jython"',
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2945, in parse_requirements
    "version spec")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2910, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected version spec in mock;python_version<"3.3" at ;python_version<"3.3"
```

# Step-by-step reproduction instructions (by running `brew` commands)

Start with a freshly installed homebrew, using the system python, just run `brew install nasa-sw-vnv/core/ikos`.

# Question

From the documentation at https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md, homebrew supports the system python, so it should work.

Should I proceed and report a bug in the virtualenv bug tracker?

Or should I force my users to use python from homebrew?
In that case, the documentation at https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md should probably be updated?

Thank you.

**Comment by MikeMcQuaid** [comment]
This should work with a system Python. Can you reproduce any of these issues with a formula in Homebrew/homebrew-core? Our Discourse may be able to provide more help but I'm afraid we cannot offer support for third-party formulae here (at least not without a minimally reproducible test case).

**Comment by MikeMcQuaid** [comment]
@arthaud Gotcha. It may be that it's an implicit or explicit requirement then. Does your formula work when you add a `python` dependency? Does it work if you use a newer `setuptool`§? If so I think we should document this and make the error more graceful.

**Comment by arthaud** [comment]
Yes, my formula works when I add the explicit `python` dependency.

I also think that it is an implicit requirement and we should probably make it explicit by adding it in the documentation.

Thanks.

**Comment by MikeMcQuaid** [comment]
@arthaud Agreed this should ideally be a document and/or code fix.
