### ISSUE TITLE
'show' alias for 'info' subcommand

### ISSUE THREAD

**Issue by fridtjof** [Homebrew/brew#5415]
# A detailed description of the proposed feature

`brew show` does the same thing as `brew info`

# The motivation for the feature

I find myself regularly typing `brew show <package name>` to view info about a package, after working on linux servers with apt, which has the equivalent of `brew info` called `apt-get show`.

# How the feature would be relevant to at least 90% of Homebrew users

I believe that many users of Homebrew nowadays work with Linux machines over SSH in some way or another, be it a sysadmin or a developer. Often, this is a Debian flavour of Linux, which uses apt. apt has a very similar set of commands to brew, except for this small discrepancy. Adding this alias would be a small, but welcome improvement :)

# What alternatives to the feature have been considered

There's not really any alternatives to consider here, I think.

**Comment by MikeMcQuaid** [comment]
https://github.com/homebrew/homebrew-aliases will solve your problem.

**Comment by fridtjof** [comment]
Thanks, I did not know about this yet.
However, is there a reason not to include this one alias in stock brew?
Because, although not documented in the help message, `brew remove` (akin to `apt-get remove`) is a direct alias of `brew uninstall`.

**Comment by MikeMcQuaid** [comment]
> However, is there a reason not to include this one alias in stock brew?

Yep, we haven't had enough requests for it yet.
