### ISSUE TITLE
v1.8.6 Parsing Core Before Pinned Taps

### ISSUE THREAD

**Issue by jclausen** [Homebrew/brew#5418]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

The package `commandbox` has an official package without a `devel` block ( due to the fact that the SHA is constantly changing as the bleeding edge version is overwritten on builds ).  The tap located at ( https://github.com/Ortus-Solutions/homebrew-boxtap/blob/master/commandbox.rb ) has the `devel` block, which is is updated with the SHA when Travis builds a new bleeding edge release 

- What happened (include command output)

When the tap above is pinned, the `brew install commandbox` command fails due to the core file being parsed first ( which is contrary to the order of parsing specified in the documentation ).  When that file is parsed the installation fails with the error:

`Error: No devel block is defined for commandbox`

- What you expected to happen

Pinned taps should be parsed first before core package versions

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew tap ortus-solutions/boxtap
brew tap-pin ortus-solutions/boxtap
brew install --devel commandbox
```

**Comment by jclausen** [comment]
I haven't seen any activity on this or notification that the parsing order has changed. Has this been resolved, or should it be reopened?

**Comment by MikeMcQuaid** [comment]
@jclausen This hasn't been resolved but no-one is working on it or more people reporting they are affected by it so it's been auto-closed. 
Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by jclausen** [comment]
I'll take a look at it.  The issue is that this line of code, along with all of the other checks: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/install.rb#L148

are executing before the formula file used for the installation has been identified as coming from the tap or from the core.  

A quick look at it says that those checks need to be moved to evaluate item in the completed `formulae` array or need to be moved inside of the `install_formula` method.

**Comment by MikeMcQuaid** [comment]
@jclausen Perfect, thanks!

**Comment by MikeMcQuaid** [comment]
Note tap-pinning has now been deprecated: https://github.com/Homebrew/brew/pull/5925
