### ISSUE TITLE
[brew commands --include-aliases] Does not show aliases

### ISSUE THREAD

**Issue by rprimus** [Homebrew/brew#5419]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Show command aliases - `brew commands --include-aliases`

## Why:

Read @MikeMcQuaid https://github.com/Homebrew/brew/issues/5415#issuecomment-447877917 

Add an alias for up:
```
brew alias up='update'
 Error: 'up' is a reserved command. Sorry.
```

Decided to check current commands and their aliases.
 
# What happened (include command output)

No visible difference between `brew commands` and `brew commands --include-aliases`

<details>
  <summary>Command output</summary>
  <pre>
  
: ; brew commands
Built-in commands
--cache          --repository     cat              config           doctor           home             link             missing          postinstall      search           switch           tap-unpin        unpin            update-reset
--cellar         --version        cleanup          deps             fetch            info             list             options          prune            sh               tap              uninstall        untap            upgrade
--env            analytics        command          desc             gist-logs        install          log              outdated         readall          shellenv         tap-info         unlink           update           uses
--prefix         cask             commands         diy              help             leaves           migrate          pin              reinstall        style            tap-pin          unpack           update-report    vendor-install

Built-in developer commands
audit                   bump-formula-pr         edit                    formula                 linkage                 mirror                  pull                    ruby                    test                    update-test
bottle                  create                  extract                 irb                     man                     prof                    release-notes           tap-new                 tests

External commands
alias                             aspell-dictionaries               bundle                            emacs                             postgresql-upgrade-database       services                          unalias
➜  cmd git:(master)
: ; brew commands --include-aliases
Built-in commands
--cache          --repository     cat              config           doctor           home             link             missing          postinstall      search           switch           tap-unpin        unpin            update-reset
--cellar         --version        cleanup          deps             fetch            info             list             options          prune            sh               tap              uninstall        untap            upgrade
--env            analytics        command          desc             gist-logs        install          log              outdated         readall          shellenv         tap-info         unlink           update           uses
--prefix         cask             commands         diy              help             leaves           migrate          pin              reinstall        style            tap-pin          unpack           update-report    vendor-install

Built-in developer commands
audit                   bump-formula-pr         edit                    formula                 linkage                 mirror                  pull                    ruby                    test                    update-test
bottle                  create                  extract                 irb                     man                     prof                    release-notes           tap-new                 tests

External commands
alias                             aspell-dictionaries               bundle                            emacs                             postgresql-upgrade-database       services                          unalias
➜  cmd git:(master)
  
  </pre>
</details>

<details>
<summary>brew config output</summary>
<pre>
: ; brew config
HOMEBREW_VERSION: 1.8.6-10-g149ded3
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 149ded30aac8fd107cdbf821bc63a7324abac157
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6f546acb032029a78ea03e0587b09f7f8b7a19b6
Core tap last commit: 48 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_VISUAL: vim
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_77, 1.8.0_60
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
</pre>
</details>

<details>
<summary>brew doctor output</summary>
<pre>
: ; brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/rprimus/.pyenv/shims/python2-config
  /Users/rprimus/.pyenv/shims/python3.6m-config
  /Users/rprimus/.pyenv/shims/python3.7-config
  /Users/rprimus/.pyenv/shims/python2.7-config
  /Users/rprimus/.pyenv/shims/python3.7m-config
  /Users/rprimus/.pyenv/shims/python-config
  /Users/rprimus/.pyenv/shims/python3-config
  /Users/rprimus/.pyenv/shims/python3.6-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libpcre.0.dylib
  /usr/local/lib/libr_diff.0.10.5.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.6m/greenlet/greenlet.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libpcre.la
  /usr/local/lib/libpcrecpp.la
  /usr/local/lib/libpcreposix.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libr-ios.a
  /usr/local/lib/out.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  emacs
  mono
</pre>
</details>

# What you expected to happen

1. At least see `up` in command listing.
2. See *all* aliases listed matching:
```
: ; HOMEBREW_FORCE_VENDOR_RUBY=1 brew ruby -e "puts HOMEBREW_INTERNAL_COMMAND_ALIASES.keys"
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
Already downloaded: /Users/rprimus/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
==> Pouring portable-ruby-2.3.7.leopard_64.bottle.tar.gz
ls
homepage
-S
up
ln
instal
uninstal
rm
remove
configure
abv
dr
--repo
environment
--config
-v
```

# Step-by-step reproduction instructions (by running `brew` commands)

1.  diff <(brew commands) <(brew commands --include-aliases)
2. visually inspect output of:
    - `brew commands`
    - `brew commands --include-aliases`

**Comment by rprimus** [comment]
Tue Dec 18 10:47:03 GMT 2018

The second point above was not checked as the command is not formula related.

**Comment by MikeMcQuaid** [comment]
> * brew commands --include-aliases

You need to specify `--quiet` to use `--include-aliases` (as documented):
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/commands.rb#L1

This will emit an error when https://github.com/Homebrew/brew/issues/1860 is completed.
