### ISSUE TITLE
/usr/local/bin/yarn symlink randomly gets removed

### ISSUE THREAD

**Issue by ahmedelgabri** [Homebrew/brew#5423]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

`brew config`

```
HOMEBREW_VERSION: 1.8.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 709ebb0315c8c06237b1919360afd64c396b5ddd
Core tap last commit: 22 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_FORCE_BREWED_GIT: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_BADGE: ⚽️
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_ROOT: /usr/local
HOMEBREW_VISUAL: nvim
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/opt/git/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

`brew doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```

# What you were trying to do (and why)

Use installed formula `yarn`

# What happened (include command output)

`Yarn` is not found in path in `/usr/local/bin/yarn` 

### Command output

```
$ yarn
zsh: command not found: yarn

$ file /usr/local/bin/yarn
/usr/local/bin/yarn: cannot open `/usr/local/bin/yarn' (No such file or directory)

$ brew list yarn
/usr/local/Cellar/yarn/1.12.3/bin/yarn
/usr/local/Cellar/yarn/1.12.3/bin/yarnpkg
/usr/local/Cellar/yarn/1.12.3/libexec/bin/ (5 files)
/usr/local/Cellar/yarn/1.12.3/libexec/lib/ (2 files)
/usr/local/Cellar/yarn/1.12.3/libexec/package.json

$ brew info yarn 
yarn: stable 1.12.3
JavaScript package manager
https://yarnpkg.com/
Conflicts with:
  hadoop (because both install 'yarn' binaries)
/usr/local/Cellar/yarn/1.12.3 (14 files, 4.7MB) *
  Built from source on 2018-12-17 at 10:44:12
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb
==> Dependencies
Recommended: node ✔
==> Options
--without-node
        Build without node support

$ brew list hadoop
Error: No such keg: /usr/local/Cellar/hadoop
```

# What you expected to happen

`yarn` to be symlinked properly & the symlink doesn't disappear 

# Step-by-step reproduction instructions (by running `brew` commands)

That's the tricky & difficult part, I still have no clue how the symlink gets removed & why it only happens with `yarn` only _till now_ because `brew install yarn` & `brew reinstall yarn` both work fine, but then the symlink gets lost somehow...

**Comment by MikeMcQuaid** [comment]
I can't reproduce this. This seems specific to your machine and you'll need to figure out what's removing this symlink yourself.

**Comment by ahmedelgabri** [comment]
@MikeMcQuaid 	Ok, any pointers how to debug this?

**Comment by ahmedelgabri** [comment]
@MikeMcQuaid I understand, I was looking for some suggestions otherwise I wouldn't have opened the issue. Anyway thanks.
