### ISSUE TITLE
Allow download strategy to be specified with a `brew bottle` flag alongside `root-url`

### ISSUE THREAD

**Issue by izaid** [Homebrew/brew#5424]
# A detailed description of the proposed feature

Bottles are allowed to use download strategies, particularly since https://github.com/Homebrew/brew/pull/3966. These currently need to be specified as `url "http://somewhere.com", :using => SomeDownloadStrategy`. However, when using `brew bottle --root-url=http://somewhere.com ...` to generate JSON files and merge them, there is currently no way to specify a download strategy for bottles (to my knowledge). It would be great to add a flag like `--download-strategy` to brew bottle that works with `--root-url`. I would also be happy with any feature that makes specifying a download strategy for a bottle possible (and not clobbered by `brew bottle --merge`).

# The motivation for the feature

This feature is the counterpart to `root-url` in `brew bottle`. It would allow users to easily specify download strategies for bottles in their own formulae while updating them.

In my particular case, I'm storing private bottles on Bintray. My understanding is there is no built-in support for this, hence I need a custom download strategy to deal with usernames and keys.

# How the feature would be relevant to at least 90% of Homebrew users

It would be very relevant to Homebrew users that maintain their own packages. It is consistent with the new changes for download strategies, for which there appears to be a lot of desire (judging by issues and comments).

# What alternatives to the feature have been considered

The only alternative to this feature is putting the download strategy into the bottle `root_url` by hand after a merge, which seems unnecessary.

Thanks for the incredible work on Homebrew!

**Comment by MikeMcQuaid** [comment]
We'll accept a pull request for this but given it's not used by any of the official taps we won't be working on it ourselves. Thanks!
