### ISSUE TITLE
"undefined method `shelljoin' for nil:NilClass" error when patches failed

### ISSUE THREAD

**Issue by apjanke** [Homebrew/brew#5427]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap. *I can only reproduce it with the one formula.*
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Building `octave-head`, my custom variant of the `octave` formula.

(I've also added an `octave-head-test` formula which reproduces the same issue, but is much quicker to build so it'll be easier for people to test this.)

# What happened (include command output)

Some patches failed, and instead of getting a nice error message, `brew` threw an exception and printed a stack trace.

I don't know if this is _because_ of the patch failures, but that's when it appeared to happen.

<details>
  <summary>Command output</summary>
  <pre>
$ brew install -s octave-head
==> Installing octave-head from octave-app/octave-app-bases
==> Cloning https://hg.savannah.gnu.org/hgweb/octave
Updating /Users/janke/Library/Caches/Homebrew/octave-head--hg
pulling from https://hg.savannah.gnu.org/hgweb/octave
searching for changes
no changes found
==> Checking out branch default
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
(leaving bookmark @)
==> Downloading https://savannah.gnu.org/support/download.php?file_id=44041
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/a1e44d4b6fcd4c0ca6d151fc8927da5900a8a26214f9da6cc7fdcf1798f7be78--high_res_update5.patch
==> Downloading https://gist.githubusercontent.com/apjanke/da92f70978aa8db01f484c782aed89a9/raw/37e1
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/c65a78393cee8793375c63683c8fbd075ed2a38eaa5bf681039a368ddab59310--fix-java-char-boxing-segfault.patch
==> Patching
==> Applying high_res_update5.patch
patching file libgui/graphics/Figure.cc
Hunk #1 FAILED at 41.
Hunk #2 succeeded at 125 with fuzz 2 (offset -10 lines).
Hunk #3 succeeded at 980 (offset -106 lines).
1 out of 3 hunks FAILED -- saving rejects to file libgui/graphics/Figure.cc.rej
patching file libgui/graphics/Figure.h
Hunk #1 FAILED at 32.
Hunk #2 FAILED at 129.
2 out of 2 hunks FAILED -- saving rejects to file libgui/graphics/Figure.h.rej
patching file libgui/graphics/FigureWindow.cc
Hunk #1 succeeded at 54 with fuzz 1 (offset 6 lines).
patching file libgui/graphics/FigureWindow.h
Hunk #1 FAILED at 37.
1 out of 1 hunk FAILED -- saving rejects to file libgui/graphics/FigureWindow.h.rej
patching file libgui/graphics/GLCanvas.cc
Hunk #1 FAILED at 68.
Hunk #2 succeeded at 187 with fuzz 2 (offset 11 lines).
1 out of 2 hunks FAILED -- saving rejects to file libgui/graphics/GLCanvas.cc.rej
patching file libinterp/corefcn/gl-render.cc
Hunk #1 FAILED at 593.
Hunk #2 succeeded at 703 (offset 9 lines).
Hunk #3 FAILED at 1135.
Hunk #4 FAILED at 3545.
Hunk #5 FAILED at 3718.
Hunk #6 FAILED at 3976.
Hunk #7 FAILED at 4126.
6 out of 7 hunks FAILED -- saving rejects to file libinterp/corefcn/gl-render.cc.rej
patching file libinterp/corefcn/gl-render.h
Hunk #1 FAILED at 222.
1 out of 1 hunk FAILED -- saving rejects to file libinterp/corefcn/gl-render.h.rej
patching file libinterp/corefcn/graphics.cc
Hunk #1 succeeded at 909 with fuzz 1 (offset 40 lines).
Hunk #2 FAILED at 6643.
Hunk #3 FAILED at 7718.
Hunk #4 FAILED at 7736.
Hunk #5 FAILED at 8764.
Hunk #6 FAILED at 8809.
Hunk #7 succeeded at 9225 (offset 410 lines).
Hunk #8 FAILED at 9282.
6 out of 8 hunks FAILED -- saving rejects to file libinterp/corefcn/graphics.cc.rej
patching file libinterp/corefcn/graphics.in.h
Hunk #1 FAILED at 3177.
1 out of 1 hunk FAILED -- saving rejects to file libinterp/corefcn/graphics.in.h.rej
patching file m4/acinclude.m4
Hunk #1 succeeded at 696 (offset 30 lines).
Hunk #2 succeeded at 2169 with fuzz 1 (offset 35 lines).
patching file scripts/plot/util/print.m
Hunk #1 succeeded at 497 with fuzz 2 (offset 115 lines).
Error: undefined method `shelljoin' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:539:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `rewrite_child_error'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:84:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:402:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:60:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:28:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:743:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:317:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:329:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:259:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:257:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:257:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
  
  </pre>
</details>

My config/doctor output:

```

[~]
$ brew config
HOMEBREW_VERSION: 1.8.6-14-ga2b4d4a
ORIGIN: https://github.com/Homebrew/brew
HEAD: a2b4d4aac294ec0872cd84d44f65bd5bd507e166
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1e763c8e81b8fc68b46b2a585c4b1c372581ea31
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEVELOPER: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_SANDBOX: 1
HOMEBREW_VISUAL: subl -w
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.1, 10.0.2, 9, 1.8.0_144
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1 => /Applications/Xcode-10.1.app/Contents/Developer
XQuartz: 2.7.11 => /opt/X11
[~]
$ brew doctor
Your system is ready to brew.
```

# What you expected to happen

An error message complaining about a failed patch, or something similar.

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew tap octave-app/octave-app-bases
brew unlink octave
brew install -s octave-head-test
```

**Comment by MikeMcQuaid** [comment]
@woodruffw Can you check how a `ErrorDuringExecution` is getting created with a `nil` `cmd`?

**Comment by woodruffw** [comment]
Yup. I'll take a look tonight or tomorrow morning.

**Comment by woodruffw** [comment]
Opened #5440 as a fix.

**Comment by apjanke** [comment]
That fixed the issue for me. Thanks!
