### ISSUE TITLE
Failure to git the submission history of pcl.rb

### ISSUE THREAD

**Issue by yountreeg** [Homebrew/brew#5428]
I want to install  the old version of pcl (pcl 1.8.1) by homebrew. The latest version is pc l 1.9.1. So I went to check the commit history of the pcl.rb. Hope to find the commit version of pcl1.8.1. So I clicked the “history” button for pcl.rb。

[in this new page](https://github.com/Homebrew/homebrew-core/commits/master/Formula/pcl.rb)(https://github.com/Homebrew/homebrew-core/commits/master/Formula/pcl.rb) ,Shown a hint “Sorry, this commit history is taking too long to generate. Refresh the page to try again, or view this history locally using the following command:”
`git log master -- Formula/pcl.rb`

But I can't successfully execute this command.A fatal appears:

`git log master -- Formula/pcl.rb `
`fatal: bad revision 'master'`

Can someone help me find the old version(pcl 1.8.1) of the pcl.rb please?

 I will be very grateful.

**Comment by iMichka** [comment]
Hi.

I would recommend to clone the repo somewhere on you hard disk:
`git clone https://github.com/Homebrew/homebrew-core.git`

Then you can run `git log` on the pcl file, or use gitk.
Use `git checkout` to checkout the older version.

For these kind of support questions it is better to ask help on https://discourse.brew.sh.

Please always fill out the issue template when opening an issue here!
