### ISSUE TITLE
Some Homebrew Commands ('`tap`' & '`uninstall`') Fail To Parse Some Global Options ('`-v`' & '`-d`')

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/brew#5438]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Please make sure that you:  

- [x] are reporting a bug others will be able to reproduce and not asking a question.  If you're not sure or want to ask a question, do so on our Discourse:  https://discourse.brew.sh.  
- [x] ran a '`brew`' command and reproduced the problem with multiple formulae?  If it's a problem with a single, official formula (not a cask,) please file this issue at Homebrew/homebrew-core:  https://github.com/Homebrew/homebrew-core/issues/new/choose.  If it's a '`brew cask`' problem, please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose.  If it's a tap&thinsp;—&thinsp;e.g.:  Homebrew/homebrew-php&thinsp;—&thinsp;problem, please file this issue at the tap.  
- [x] ran '`brew update`' and can still reproduce the problem?  (I also ran '`brew update-reset`,' just in case, but this didn't help.)  
- [ ] ran '`brew doctor`,' fixed all issues, and can still reproduce the problem?  (As much as possible; see the notes at the end of my included '`brew doctor`' output.)  
- [x] ran '`brew config`' and '`brew doctor`' and included their output with your issue?  

   ```
   Bryces-HD-1-TB:~ zadmin$ brew config
   HOMEBREW_VERSION: 1.8.6
   ORIGIN: https://github.com/Homebrew/brew.git
   HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
   Last commit: 6 days ago
   Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
   Core tap HEAD: f7fde25990c05787fc8e39fe0c54d16d1163808b
   Core tap last commit: 87 minutes ago
   HOMEBREW_PREFIX: /usr/local
   HOMEBREW_CASK_OPTS: --appdir=/Applications --prefpanedir=/Library/PreferencePanes --colorpickerdir=/Library/ColorPickers --dictionarydir=/Library/Dictionaries --servicedir=/Library/Services --qlplugindir=/Library/QuickLook --fontdir=/Library/Fonts --input_methoddir=/Library/Input\ Methods --screen_saverdir=/Library/Screen\ Savers --internet_plugindir=/Library/Internet\ Plug\-Ins
   HOMEBREW_DEV_CMD_RUN: 1
   HOMEBREW_FORCE_BREWED_CURL: 1
   HOMEBREW_FORCE_BREWED_GIT: 1
   HOMEBREW_GITHUB_API_TOKEN: set
   HOMEBREW_NO_AUTO_UPDATE: 1
   HOMEBREW_UPDATE_TO_TAG: 1
   CPU: dual-core 64-bit core2
   Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
   Clang: 8.0 build 800
   Git: 2.20.1 => /usr/local/opt/git/bin/git
   Curl: 7.63.0 => /usr/local/opt/curl/bin/curl
   Java: 11.0.1
   macOS: 10.11.6-x86_64
   CLT: 8.2.0.0.1.1480973914
   Xcode: 8.2.1
   XQuartz: 2.7.11 => /opt/X11
   Bryces-HD-1-TB:~ zadmin$ brew doctor
   Please note that these warnings are just used to help the Homebrew maintainers
   with debugging if you file an issue. If everything you use Homebrew for is
   working fine: please don't worry or file an issue; just ignore this. Thanks!
   
   Warning: You are using macOS 10.11.
   We (and Apple) do not provide support for this old version.
   You will encounter build failures and other breakages.
   Please create pull requests instead of asking for help on Homebrew's
   GitHub, Discourse, Twitter or IRC. As you are running this old version,
   you are responsible for resolving any issues you experience.
   
   Warning: Broken symlinks were found. Remove them with `brew prune`:
     /usr/local/lib/libpng.la
   ```
   
   (Note that the second warning is due to Homebrew/homebrew-core#35269.  I'm also reporting this issue despite the first warning since I think it should be reproducible under newer versions of macOS.)  

### What you were trying to do (and why)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Run either:  

1. '`brew tap -vd`' (as a minimal test case, picked somewhat at random,) or
1. '`brew uninstall -vd <formula>`,' sometimes with the '`--ignore-dependencies`' option, either:  
    1. as a test case after backing up the formula specified or
    1. prior to reinstalling the formula in question with different local state as part of debugging, troubleshooting, and/or working around some outstanding personal formula/package issues.  

A similar issue also occurs if one passes the short options involved in the opposite order&thinsp;—&thinsp;that is, as '`-dv`,' instead.  This issue may be more widespread than just the commands tested, but no others have yet been checked.  

### What happened (include command output)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'`brew`' exited due to a fatal exception:  

<details>
  <summary>Logs</summary>
  <pre style="white-space:  pre-wrap">
    Bryces-HD-1-TB:~ zadmin$ brew tap -vd
    brew: no version found in package d
    Error: Kernel.exit
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1002:in `abort'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1002:in `block (2 levels) in <class:OptionParser>'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1578:in `block in parse_in_order'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1631:in `parse'
    /usr/local/Homebrew/Library/Homebrew/cli_parser.rb:126:in `parse'
    /usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:77:in `tap'
    /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
    Bryces-HD-1-TB:~ zadmin$ brew tap -dv
    brew Version
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1008:in `exit'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1008:in `block (2 levels) in <class:OptionParser>'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1578:in `block in parse_in_order'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1631:in `parse'
    /usr/local/Homebrew/Library/Homebrew/cli_parser.rb:126:in `parse'
    /usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:77:in `tap'
    /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
    Bryces-HD-1-TB:~ zadmin$ brew uninstall -vd …
    brew: no version found in package d
    Error: Kernel.exit
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1002:in `abort'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1002:in `block (2 levels) in <class:OptionParser>'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1578:in `block in parse_in_order'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1631:in `parse'
    /usr/local/Homebrew/Library/Homebrew/cli_parser.rb:126:in `parse'
    /usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:36:in `uninstall'
    /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
    Bryces-HD-1-TB:~ zadmin$ brew uninstall -dv …
    brew Version
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1008:in `exit'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1008:in `block (2 levels) in <class:OptionParser>'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1578:in `block in parse_in_order'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
    /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1631:in `parse'
    /usr/local/Homebrew/Library/Homebrew/cli_parser.rb:126:in `parse'
    /usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:36:in `uninstall'
    /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
  </pre>
</details>

### What you expected to happen

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I expected Homebrew to carry my tap and formula installation management requests out successfully.  

### Step-by-step reproduction instructions (by running `brew` commands)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Run any of the following:  

1. '`brew tap -vd`'
1. '`brew tap -dv`'
1. '`brew uninstall -vd <formula>`'
1. '`brew uninstall -vd --ignore-dependencies <formula>`'
1. '`brew uninstall -dv <formula>`'
1. '`brew uninstall -dv --ignore-dependencies <formula>`'

As also noted above, this issue may be more widespread than just the commands tested, but no others have yet been checked.  

---

CC @GauthamGoli since you wrote the code that handles option parsing using your CLI parser.

**Comment by MikeMcQuaid** [comment]
`brew uninstall -vd` or `brew uninstall -vd` are not documented. While a nicer error message could be produced this is not behaviour that's expected.

**Comment by GauthamGoli** [comment]
> brew uninstall -vd or brew uninstall -vd are not documented.

Yes, they don't have `verbose` switches, so they should be showing an error saying "Unknown Option". 

I just did a quick debug and it seems OptionParser has inbuilt option for `version` due to which the error message is not being shown. I will push a fix for this. If anyone else wants to do it before, feel free to do so.

**Comment by MikeMcQuaid** [comment]
Closing this out given the above.

**Comment by RandomDSdevel** [comment]
@GauthamGoli:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I took [a naïve stab](https://github.com/Homebrew/brew/compare/master...RandomDSdevel:fix-5438) at fixing this to present a more descriptive error message, but it wasn't enough:  

```
…:~ …$ brew uninstall -vd --ignore-dependencies <formula>
brew: no version found in package d
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1002:in `abort'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1002:in `block (2 levels) in <class:OptionParser>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1578:in `block in parse_in_order'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/optparse.rb:1631:in `parse'
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:131:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:36:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

Sorry I wasn't of more help.
