### ISSUE TITLE
Update deletes /usr/local/Library/ENV

### ISSUE THREAD

**Issue by jwhite007** [Homebrew/brew#544]
### Bug reports:

I recently issued 'brew update && brew upgrade' (ecc329e to 092d471) and then noticed that I was having problems with my brew installed R which was looking for /usr/local/Library/ENV/4.3/sed. I noticed that the update of brew coincided with deletion of the directory ENV. What's going on here? Thanks.

Cheers,
James

**Comment by MikeMcQuaid** [comment]
That's intentional we've moved it. Please create an issue for whatever tap you installed R from to ask them to rebuild their bottle.

**Comment by DomT4** [comment]
Probably `homebrew/science`, IIRC. CC @Homebrew/science.

**Comment by jwhite007** [comment]
Mike,

Thanks for your response. I figured that it was probably intentional. It appears that maintainer of the tap fixed the issue.

Cheers,
James
