### ISSUE TITLE
Syntax of `brew info --installed <formula>` changed, but semantics didn't.

### ISSUE THREAD

**Issue by CamJN** [Homebrew/brew#5449]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.8.6-40-g406272f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 406272f0078daac77e5bc7e235eb300beaeac575
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 49a9141d7f652c242962c20acba1fff6915c0ad5
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 86400
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_INSTALL_BADGE: 🍷
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  passenger
```

# What you were trying to do (and why)

I was just running the Passenger CI, which generates a pull request to homebrew when we release. Part of that process involves checking if the nginx formula is installed and uninstalling it if so. We use `brew info` as part of this check. We didn't change the command we run but homebrew started rejecting it.

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ brew info --installed nginx
Error: `installed` cannot be passed without `json`
$ brew info --installed --json nginx
nginx: stable 1.15.8 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.15.7 (8 files, 3.9MB) *
  Built from source on 2018-11-28 at 11:01:17 with: --with-passenger
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nginx.rb
==> Dependencies
Required: openssl ✔, pcre ✔
Optional: passenger ✔
==> Options
--with-passenger
	Compile with support for Phusion Passenger module
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To activate Phusion Passenger, add this to /usr/local/etc/nginx/nginx.conf, inside the 'http' context:
  passenger_root /usr/local/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
  passenger_ruby /usr/bin/ruby;

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 37,828 (30 days), 111,331 (90 days), 431,596 (365 days)
install_on_request: 35,036 (30 days), 102,257 (90 days), 385,437 (365 days)
build_error: 0 (30 days)
  </pre>
</details>

# What you expected to happen

I expected either the `brew info --installed` command would continue to work without the `--json` flag, or if that is going to be the new syntax, that json output would be returned from the command to match the expected semantics.

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew info --installed nginx
brew info --installed --json nginx
```

This commit: https://github.com/Homebrew/brew/commit/78b2b7fac0618fb60d1f3141b60ee017b6942596 makes it look like the syntax change was intentional, so I _think_ that the intention is to require `--json` which is cool, json is easier to parse, but there's no json output so that's kinda confusing.

**Comment by MikeMcQuaid** [comment]
> * `--json` requires a parameter like `--json=v1`. The fact that `brew info` doesn't warn or error when just `--json` is passed seems like a bug

CC @GauthamGoli FYI.

Closing this otherwise as our documentation explains how to use this command.

**Comment by colindean** [comment]
> shouldn't we just eliminate the need for --json to take a value?

Negative. Usage of `--json` is likely to be scripted. If the output format were to be changed, it might break automation reliant on the format. So, `v1` stays and `v2` comes. `v1` gets deprecated and then removed when it's too unmanageable to retain.

**Comment by MikeMcQuaid** [comment]
> If the output format were to be changed, it might break automation reliant on the format.

It's never changed before and we're moving towards another major version. `--json` should at least be a valid flag if we don't have any plans for a `v2` the `v1` should be implied.
