### ISSUE TITLE
Error installing homebrew (502 Error)

### ISSUE THREAD

**Issue by anndroid9000** [Homebrew/brew#545]
I'm having an issue installing Homebrew. I keep getting the following results.

> $ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
> curl: (22) The requested URL returned error: 502

I thought this was a server issue but I haven't been able to install Homebrew for days now. What's worse is that I was able to install Homebrew on another Mac computer **through the same exact network minutes apart**.  Does anyone know where I might find log files for the installation process so I might start debugging?

**Comment by DomT4** [comment]
Can you try:
```
curl -L -v https://raw.githubusercontent.com/Homebrew/install/master/install
```
And see if it's more obvious there where the breakage is?

**Comment by anndroid9000** [comment]
Sure thing, 

> $ curl -L -v https://raw.githubusercontent.com/Homebrew/install/master/install
> *   Trying ::1...
> * connect to ::1 port 3128 failed: Connection refused
> *   Trying 127.0.0.1...
> * connect to 127.0.0.1 port 3128 failed: Connection refused
> * Failed to connect to localhost port 3128: Connection refused
> * Closing connection 0
> curl: (7) Failed to connect to localhost port 3128: Connection refused

Unfortunately, I'm not sure what to make of this...

**Comment by DomT4** [comment]
Looks like you're rerouting GitHub to localhost, either to block it or because you're running a proxy. The latter seems likely given the output. Is the machine part of a corporate network/are you running a proxy locally?

**Comment by anndroid9000** [comment]
I was running a local proxy without realizing. The issue has been resolved. Thanks!
