### ISSUE TITLE
Allow "brew info ..." to show info for cask.

### ISSUE THREAD

**Issue by rhwood** [Homebrew/brew#5456]
# A detailed description of the proposed feature

When using the command `brew info name`, if a formula `name` does not exist, but a cask `name` does exist, provide the user with the info for the cask, as if `brew cask info name` had been the issued command.

# The motivation for the feature

I frequently find that the first command issued after a `brew [cask] search ...` is `brew [cask] info ...` on one of the results returned from the search.

Since the consolidation of `brew search ...` and `brew cask search ...` commands and removal of `brew cask search ...`, I often find that I fail to use `brew cask info ...` and that `brew info ...` merely gives me an error getting the info for a result returned in the prior search.

It would be beneficial if the behaviors of search and info were the same in regard to handling of casks since the two commands are likely used together.

# How the feature would be relevant to at least 90% of Homebrew users

It would be beneficial if the behaviors of search and info were the same in regard to handling of casks since the two commands are likely used together by brew users (for example, searching for a youtube downloaders using `brew search youtube` returns 7 results (2 formulas and 5 casks). Being able to run a single command to get the infos for all results would be preferable to having to think about which command to use for which result.

# What alternatives to the feature have been considered

- Do nothing and maintain the current behavior.

- Have `brew info name` (and other commands that act on formulas suggest the `brew cask ...` equivalent command if both an equivalent cask command and a cask matching `name` exists).

**Comment by MikeMcQuaid** [comment]
We would consider a pull request for this but have no plans for further integration of commands between `brew` and `brew cask` at this time, thanks!

**Comment by MikeMcQuaid** [comment]
Actually, will leave this open and `help wanted` for now.

**Comment by zachauten** [comment]
I’d like to take a crack at this if that’s alright!

I’ve currently got the feature working and I’d appreciate if someone could answer a quick question:

 I’d like to add tests that create dummy casks in the test setup/before, similar to how `info_spec.rb` calls `setup_test_formula "testball”` on line 5. What’s the standard way to generate that test data?

**Comment by MikeMcQuaid** [comment]
> I’d like to take a crack at this if that’s alright!

Feel free.

> What’s the standard way to generate that test data?

I'm not sure. Check out other cask tests or just use one of the existing cask fixtures. Open a PR; it's easier to discuss code when able to look at it.

**Comment by MikeMcQuaid** [comment]
Fixed by @zachauten's great PR in https://github.com/Homebrew/brew/pull/5538. Will be in the next tagged version of Homebrew/brew.
