### ISSUE TITLE
brew update fails to find git

### ISSUE THREAD

**Issue by c256** [Homebrew/brew#547]
### Bug reports:

I'm attempting to "brew update" on my macOS 10.11.5 machine, with a fully-functional git-2.9.1 installed (via homebrew.)  I get warning about git-2.9.1 already being installed, followed by an error that git must be installed. 

> ; brew update
> Warning: git-2.9.1 already installed
> Error: Git must be installed and in your PATH!
> Exit 1

This continues if I remove git (I had several bottled versions lying around) and reinstall, and if I uninstall git and leave it for `brew update':

> ; brew update
> ==> Downloading https://homebrew.bintray.com/bottles/git-2.9.1.el_capitan.bottle.tar.gz
> Already downloaded: /Users/yandros/Library/Caches/Homebrew/git-2.9.1.el_capitan.bottle.tar.gz
> ==> Pouring git-2.9.1.el_capitan.bottle.tar.gz
> ==> Caveats
> Bash completion has been installed to:
>   /usr/local/etc/bash_completion.d
> 
> zsh completion has been installed to:
>   /usr/local/share/zsh/site-functions
> 
> Emacs Lisp files have been installed to:
>   /usr/local/share/emacs/site-lisp/git
> ==> Summary
> 🍺  /usr/local/Cellar/git/2.9.1: 1,427 files, 31.3M
> Error: Git must be installed and in your PATH!
> Exit 1

`brew doctor' reports nothing other than the warning that I haven't run `brew update' in a long time.

**Comment by DomT4** [comment]
```bash
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```

Will only need to execute that once & you'll be okay afterwards. You can also `brew rm git` if you're happy with the system `git`; was never intentionally made mandatory.

**Comment by c256** [comment]
Worked like a charm; thanks!
