### ISSUE TITLE
Make bot.brew.sh available to everyone (no sign in, no request for permissions)

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/brew#548]
Currently bot.brew.sh is behind a login wall and a request for read-only access to organizations and teams. This has proven to be somewhat confusing and occasionally alarming (the permissions bit) to some casual contributors and upstream maintainers (when build failures are reported upstream with links to build logs on the test bot). Even after being explained to about why bot.brew.sh needs such info, some may still refuse to grant access, which has to be worked around by someone manually posting logs elsewhere.

Our issues and pull requests are fully public, viewable by anyone with or without a GitHub account,  so one would imagine that in principle, one should not have to sign in to GitHub to view results on the CI, less grant it extra permissions.

Therefore, is it possible to tweak Jenkins' settings so that login is optional, and permissions are asked for only when the logged-in user actively requests admin access?

Disclaimer: I have zero experience managing Jenkins or other CI products, so this could either be impossible or a hell lot of work. Just a thought.

**Comment by MikeMcQuaid** [comment]
> Therefore, is it possible to tweak Jenkins' settings so that login is optional, and permissions are asked for only when the logged-in user actively requests admin access?

Yes and mostly just because you asked very politely and explained it very well. Done!

**Comment by zmwangx** [comment]
Cool, thanks.

**Comment by UniqMartin** [comment]
Cool, thanks for asking @zmwangx and thanks for making the change @MikeMcQuaid! :tada:

Even for me this might come in handy at some point in time when I want to see what a regular contributor would be seeing instead of always having the unlimited view of an admin user.
