### ISSUE TITLE
Installation failure on fresh install of High Sierra

### ISSUE THREAD

**Issue by TonyWorkThrowaway** [Homebrew/brew#5487]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I am attempting to install homebrew for the first time on a High Sierra computer. I've installed this before on Sierra or earlier without any problems.
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" `

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
  
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
/usr/local/Homebrew/.git: Permission denied
Failed during: git init -q
  
  </pre>
</details>

# What you expected to happen

Installation successful!

# Step-by-step reproduction instructions (by running `brew` commands)

N/A

**Comment by MikeMcQuaid** [comment]
This was not a completely fresh install of High Sierra if that directory already existed. Run the uninstall script and then run install again after that.
