### ISSUE TITLE
brew install without github access

### ISSUE THREAD

**Issue by yhjhoo** [Homebrew/brew#5496]
I can access github, but I can't git clone from github, during to company policies which blocks github clone.

# A detailed description of the proposed feature

Allow to use an alternative way to install without github clone

# The motivation for the feature

Allow enterprise users to use brew

# How the feature would be relevant to at least 90% of Homebrew users

might not, only enterprise users.

# What alternatives to the feature have been considered

brew install with another git repos

**Comment by MikeMcQuaid** [comment]
Sorry, this is an issue for your organisation and not for the Homebrew project.
