### ISSUE TITLE
brew install solfege hangs

### ISSUE THREAD

**Issue by sbocconi** [Homebrew/brew#550]
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

#### brew --version
Homebrew 0.9.9 (git revision a3a6; last commit 2016-07-17)
Homebrew/homebrew-core (git revision 552e4; last commit 2016-07-17)

#### brew doctor
jack is a software that I installed

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/jack/control.h
    /usr/local/include/jack/intclient.h
    /usr/local/include/jack/jack.h
    /usr/local/include/jack/jslist.h
    /usr/local/include/jack/metadata.h
    /usr/local/include/jack/midiport.h
    /usr/local/include/jack/net.h
    /usr/local/include/jack/ringbuffer.h
    /usr/local/include/jack/session.h
    /usr/local/include/jack/statistics.h
    /usr/local/include/jack/systemdeps.h
    /usr/local/include/jack/thread.h
    /usr/local/include/jack/transport.h
    /usr/local/include/jack/types.h
    /usr/local/include/jack/uuid.h
    /usr/local/include/jack/weakjack.h
    /usr/local/include/jack/weakmacros.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/jack.pc

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    jack

#### output of brew install solfege

Error: No available formula with the name "solfege" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...

hangs...

**Comment by DomT4** [comment]
It does seem to, to be fair. Can reproduce the hang on any formula I _know_ doesn't exist in an official Homebrew tap. For example, `brew install dogs`:

```
Error: No available formula with the name "dogs"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
```
Has currently been there for... 3 minutes & counting. Interesting.

**Comment by DomT4** [comment]
Finally timed out in a little over 5 minutes:
```
Error: No formulae found in taps.
```

**Comment by DomT4** [comment]
Can you a few times? Wondering if the GitHub API is having a blip this morning rather than a more fundamental bug:
```
brew install dogs  2.66s user 0.30s system 71% cpu 4.132 total
brew install dogs  2.51s user 0.29s system 71% cpu 3.941 total
brew install dogs  2.69s user 0.29s system 76% cpu 3.878 total
brew install dogs  2.68s user 0.31s system 6% cpu 48.102 total
brew install dogs  2.66s user 0.31s system 75% cpu 3.957 total
```

Seems like it could be:
```
Error: No available formula with the name "dogs"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: undefined method `[]' for nil:NilClass
```

**Comment by sbocconi** [comment]
solfege once existed, that might be the reason of the problem.
I do not get any time-out, I need to Ctrl-C the program which I did after 66 min this time, but previously without timing even after a longer period.

time brew install solfege
Error: No available formula with the name "solfege" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
^C

real	66m53.730s
user	0m1.281s
sys	0m0.485s

**Comment by ilovezfs** [comment]
I think it's just a GitHub blip.
```
Josephs-MacBook-Pro:~ joe$ time brew install solfege
Error: No available formula with the name "solfege" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

real	0m5.188s
user	0m3.145s
sys	0m0.244s
```

**Comment by UniqMartin** [comment]
I'm also considering this a GitHub issue. The performance has been very inconsistent for me during the past 24 hours, mostly for the GitHub website, but wouldn't be surprised about related GitHub API woes.

We might want to time out the requests ourselves after some reasonable time frame to avoid the impression that `brew` is stuck. But might be not worth the effort given that most conditions will be handled just fine by `curl` and GitHub API issues aren't that frequent.

**Comment by sbocconi** [comment]
Hi, the behaviour here is consistent, it always hangs, it must be something in my installation.

time brew install solfege
Error: No available formula with the name "solfege" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
^C

real	1362m40.725s
user	0m2.208s
sys	0m0.880s

**Comment by DomT4** [comment]
Does a completely vanilla:
```bash
curl https://api.github.com/repos/Homebrew/homebrew-versions/git/trees/HEAD\?recursive\=1
```
Work for you, or does that hang as well?

**Comment by sbocconi** [comment]
This works very fast:
real	0m1.361s
user	0m0.025s
sys	0m0.018s

**Comment by MikeMcQuaid** [comment]
Is this still broken for you @sbocconi?

**Comment by MikeMcQuaid** [comment]
Do you have a proxy server or difficulties connecting to GitHub itself?

**Comment by sbocconi** [comment]
No I have a direct connection and in general no problem with github

**Comment by MikeMcQuaid** [comment]
Hmm, no idea what's going on here then, sorry. Will close this out as there's not much more we can do. If you can dig into the code you may be able to figure it out and we'd accept PRs (and will help turn imperfect ones into shippable ones). Sorry!

**Comment by MikeMcQuaid** [comment]
Setting `HOMEBREW_NO_GITHUB_API` may also be a workaround for you.

**Comment by sbocconi** [comment]
This works indeed:
``export HOMEBREW_NO_GITHUB_API=true; time brew install dogs``

Error: No available formula with the name "dogs" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
==> You haven't updated Homebrew in a while.
A formula for dogs might have been added recently.
Run `brew update` to get the latest Homebrew updates!

real	0m0.500s
user	0m0.362s
sys	0m0.152s

**Comment by ilovezfs** [comment]
```
brew update
brew config
brew doctor
```

**Comment by sbocconi** [comment]
I tried reinstalling homebrew by deleting all the installed formulas, and the problem is still there.

Moreover, it seems I am not the only one to have it: https://groups.google.com/forum/#!topic/homebrew-discuss/aPO9R7BQkLU

Output of the commands:

**brew update**
Already up-to-date.

**brew config**
HOMEBREW_VERSION: 1.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: edf042ee97f80955b077724119e717a51eb25e29
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 61cd7d124ccd2dda51dbf4dd118e3fe5a1bbd229
Core tap last commit: 18 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_65, 1.7.0_80, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11

**brew doctor**
Your system is ready to brew.

**Comment by ilovezfs** [comment]
Can you try in a new dummy user account please?

**Comment by sbocconi** [comment]
I tried with a guest account on Mac an search worked:

**brew search solfege**
No formula found for "solfege".
==> Searching pull requests...

Now it also works with the normal user:

**brew search solfege**
No formula found for "solfege".
==> Searching pull requests...

I really do not understand why it works now but I am very happy that it does!!

**Comment by ilovezfs** [comment]
OK, so it has something to do with your configuration in the other user. I'd start with moving your bash profile out of the way and trying again.

**Comment by sbocconi** [comment]
As I said, after logging out to try with the guest user (I did that instead of sudo su guest) and logging in again as the normal user, it works.

It might be temporary, but it seems that either running as another user or logging in/out fixed the issue.
