### ISSUE TITLE
openblas failed to build on 10.13.6

### ISSUE THREAD

**Issue by nadavrap** [Homebrew/brew#5502]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Updating openblas from 0.3.4 -> 0.3.5 as part of upgrading R from 3.5.2 -> 3.5.2_1
- What happened (include command output)
Compilation errors:
`cc1: error: bad value ('penryn') for '-march=' switch
cc1: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
cc1: error: bad value ('penryn') for '-march=' switch
cc1: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
make: *** [getarch] Error 1
Makefile.system:201: Makefile.conf: No such file or directory
Makefile.system:1069: Makefile.: No such file or directory
make: *** No rule to make target `Makefile.'.  Stop.
`

- What you expected to happen
Successful installation.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew upgrade openblas`
The failure.

See [gist here](https://gist.github.com/nadavrap/ba7677b9e18ad0465ae47858aeec3764)

**Comment by fxcoudert** [comment]
Thanks for reporting this issue. The problem is that `brew` is passing `-march=penryn` to the compiler, but the compiler in this case is GCC 8 (latest version), which does not accept this flag.

**Comment by MikeMcQuaid** [comment]
@fxcoudert @claui @sjackman Any idea what the closest GCC-supported equivalent is? Could either set this to that just for GCC, set to the same for both or remove the Penryn flag entirely and go back to Core 2.

**Comment by claui** [comment]
@MikeMcQuaid We should be able to use `-march=core2`, which I believe has the exact same effect as `-march=penryn` ([source](https://github.com/Homebrew/brew/issues/5425#issuecomment-448678873)).

**Comment by sjackman** [comment]
Here's the relevant GCC docs:
https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

> ‘core2’ Intel Core 2 CPU with 64-bit extensions, MMX, SSE, SSE2, SSE3 and SSSE3 instruction set support.
> ‘nehalem’
Intel Nehalem CPU with 64-bit extensions, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2 and POPCNT instruction set support.
