### ISSUE TITLE
Warning: this formula has no --bottle-arch= option so it will be ignored

### ISSUE THREAD

**Issue by sjackman** [Homebrew/brew#5504]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Build a bottle for a specified architecture to test `brew install --bottle-arch`.

# What happened (include command output)

```console
$ brew install --build-bottle --bottle-arch=nehalem hello
Warning: hello: this formula has no --bottle-arch= option so it will be ignored!
…
```

The option `--bottle-arch=nehalem` does work, but produces a warning.

# What you expected to happen

No warning.

# Step-by-step reproduction instructions (by running `brew` commands)

```sh
brew install --build-bottle --bottle-arch=nehalem hello
```

**Comment by Genora51** [comment]
I'm having a similar issue with `brew install gdb --with-python`. Maybe this is an issue across brew?
`brew options gdb` gives no output.

**Comment by sjackman** [comment]
@Genora51 See https://github.com/Homebrew/homebrew-core/issues/31510

**Comment by sjackman** [comment]
Thanks for the fix, Mike!
