### ISSUE TITLE
Error: No such file or directory @ rb_sysopen - ~/Library/Caches/Homebrew/.cleaned

### ISSUE THREAD

**Issue by timkgh** [Homebrew/brew#5509]
Per man page under `cleanup` one can run `rm -rf "$(brew --cache)"`

But then `brew cleanup` fails:
`Error: No such file or directory @ rb_sysopen - ~/Library/Caches/Homebrew/.cleaned`

This started happening recently, used to work.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by timkgh** [comment]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [] ran `brew config` and `brew doctor` and included their output with your issue?



# What you were trying to do (and why)
```
rm -rf "$(brew --cache)"
brew cleanup
```


# What happened (include command output)

`Error: No such file or directory @ rb_sysopen - ~/Library/Caches/Homebrew/.cleaned`

<details>
  <summary>Command output</summary>
  <pre>
  
  Error: No such file or directory @ rb_sysopen - ~/Library/Caches/Homebrew/.cleaned
  
  </pre>
</details>

# What you expected to happen

Should work. This is a recent regression, used to work without error.

# Step-by-step reproduction instructions (by running `brew` commands)

```
rm -rf "$(brew --cache)"
brew cleanup
```
