### ISSUE TITLE
Git Errors

### ISSUE THREAD

**Issue by chasingtheflow** [Homebrew/brew#551]
### Bug reports:

When I run brew I get errors related to my git installation which both say that git is installed and then errors that git is not installed:

```
 ~> brew update
Warning: git-2.9.1 already installed
Error: Git must be installed and in your PATH!
 ~> which git
/usr/local/bin/git
 ~> 
```

I don't think I've knowingly changed anything related to this recently, so not sure why I'm seeing this....

I've tried uninstalling and reinstalling git but it did not resolve the issue.

**Comment by UniqMartin** [comment]
```sh
cd "$(brew --repository)" && git fetch && git reset --hard origin/master
```

You will only need to execute this once and you'll be okay afterwards. You can also `brew rm git` if you're happy with the system Git; it was never intentionally made mandatory.

Sorry about that! We've made a mistake during a refactoring and some people (who updated in the brief period before we realized our mistake) were stuck just like you are right now …

**Comment by chasingtheflow** [comment]
That fixed it! Thanks for the help :-)
