### ISSUE TITLE
HB 1.9 release - HOMBREW_BUILD_FROM_SOURCE clairification

### ISSUE THREAD

**Issue by blogabe** [Homebrew/brew#5514]
@MikeMcQuaid the 1.9 release notes state, "The HOMEBREW_BUILD_FROM_SOURCE environment variable has been deprecated in favour of passing --build-from-source to individual formulae installs."

If I install a formula or multiple formulae using the cl flag, will `brew upgrade` respect that moving forward when the package updates, should I `brew upgrade --build-from-source`, or is it advised to individually re-install each formula with the cl flag?

**Comment by MikeMcQuaid** [comment]
Please always read and fill out the issue template, @blogabe (which would have directed this question to Discourse).

> will `brew upgrade` respect that moving forward when the package updates

It will not. Building from source is not a supported configuration. Given the CFLAGS are now the same it's a waste of your time (and ours when we get building from source issues).
