### ISSUE TITLE
"Brew pin" for not-installed formulae

### ISSUE THREAD

**Issue by DesWurstes** [Homebrew/brew#5515]
## Background

NodeJS installed by Brew doesn't work for me. So, I use the Node downloaded from website. I want to use Emscripten installed by Brew, but it requires me to install Node. There should be an option that makes Brew assume the user has the dependency installed...

## Solution

There should be an option that makes Brew assume the user has the dependency installed, which should (*might*?) have the same effect as `brew install emscripten; brew remove --ignore-dependencies --force node`. A way to solve the problem is to allow `brew pin` for uninstalled software. Of course, it'll cause errors if misused.

## Alternatives considered

Another solution that is less preferable is to download the dependency, and remove it after the software is installed (which might not work, if the dependency doesn't work, which is the case for me).

## Otherwise

Currently the issue exists. Every time I update emscripten, it installs Node as a dependency, and installs emscripten. However, emscripten doesn't work due to broken Node. First I force-remove Node, and then download it from nodejs.org

**Comment by MikeMcQuaid** [comment]
> NodeJS installed by Brew doesn't work for me.

This is a bug you can report to Homebrew/homebrew-core. 

We don't support replacing dependencies with other random versions.
