### ISSUE TITLE
Revision as string not detected.

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#5522]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

- What you were trying to do (and why)
Specify revision as string by error, e.g. `revision "1"`
```brew audit --strict --online $formula```
- What happened (include command output)
`brew style --fix $formula` is clean, but audit:
```
brew audit --strict --online --fix llvm
Error: comparison of String with 0 failed
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:856:in `<'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:856:in `audit_revision_and_version_scheme'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1014:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1007:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1007:in `audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:157:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:152:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:152:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:88:in `<main>'
```
- What you expected to happen
Some useful message, that revision must be `int`.

**Comment by MikeMcQuaid** [comment]
@yurikoles Please don't create issues just for `audit` not detecting things you think it should, thanks.

**Comment by yurikoles** [comment]
@MikeMcQuaid should I create a FR?

**Comment by MikeMcQuaid** [comment]
@yurikoles No, thanks.
