### ISSUE TITLE
installed python 3x but check version it show 2x

### ISSUE THREAD

**Issue by craigcosmo** [Homebrew/brew#5525]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

installed python 3x 

# What happened (include command output)

installed python 3x but check version it show 2x

<details>
  <summary>Command output</summary>
  <pre>
  
  ➜  ~ brew install python
Warning: python 3.7.2 is already installed, it's just not linked
You can use `brew link python` to link this version.
➜  ~ brew link python
Linking /usr/local/Cellar/python/3.7.2... Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks
➜  ~ sudo brew link python
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
➜  ~ python -V 
Python 2.7.10
  
  </pre>
</details>

# What you expected to happen

see python version 3x

# Step-by-step reproduction instructions (by running `brew` commands)

brew install python
brew link python
sudo brew link python
python -V

**Comment by lembacon** [comment]
We're following [PEP 394](https://www.python.org/dev/peps/pep-0394/), therefore this is the expected behavior for now.

**Comment by lembacon** [comment]
If you do want `python` to point to the Python 3 installed via Homebrew, you should read and follow caveats by running `brew info python`.
