### ISSUE TITLE
Brewed version of R expects /usr/local/Library/ENV to still exit

### ISSUE THREAD

**Issue by K20shores** [Homebrew/brew#553]
### Bug reports:

After updating to the newest version of Homebrew, some commands that deal with a brewed version of R no longer work. Two versions of this problem can be found below:

1.) http://stackoverflow.com/questions/38441722/error-using-rscript
2.) http://stackoverflow.com/questions/38440350/sed-directory-not-found-when-running-r-with-e-flag

It seems that /usr/local/Library/ENV was moved in the most recent update, but scripts that expect this directory to exist were not updated. 1. is my post. The version of Homebrew that produced this at the time was Homebrew 0.9.9 (git revision 45bf; last commit 2016-07-18).

**Comment by scpeters** [comment]
See also #544

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-science#3839
