### ISSUE TITLE
Formula installed as bottle now upgrades as a bottle (does not run postinstall hook)

### ISSUE THREAD

**Issue by heptathlon** [Homebrew/brew#5532]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? Yes fixed all issues except I`m using osx 10.11.6.
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

brew config:
HOMEBREW_VERSION: 1.9.1-16-gab7a3c9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ab7a3c966fbcc33dd3561fe74fe83a005be23a91
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e27422dcd5a3b9056ac533818b7e4b18ffe60252
Core tap last commit: 77 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/john/Library/Logs/Homebrew
HOMEBREW_VISUAL: nano
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 8.0 build 800
Git: 2.20.1 => /usr/local/opt/git/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 11.0.1, 1.8.0_25, 1.7.0_71
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: 8.2.1
XQuartz: 2.7.11 => /opt/X11

brew doctor:
Warning: You are using macOS 10.11. etc.

# What you were trying to do (and why)

I have the same issue as https://github.com/Homebrew/brew/issues/3047 but it`s locked.
Formula on osx 10.11.6 which were installed from bottle (when bottles still existed for 10.11) are now upgraded in a way which doesn't run postinstall hook.

# What happened (include command output)

brew upgrade postgresql
==> Upgrading postgresql
==> Downloading https://ftp.postgresql.org/pub/source/v11.1/postgresql-11.1.tar.bz2
Already downloaded: /Users/john/Library/Caches/Homebrew/downloads/f93658149da8077ee7cd540cf792578164ec3a6b4c4eeec310d8d9863e735e02--postgresql-11.1.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/postgresql/11.1_1 --datadir=/usr/local/share/postgresql --libdir=/usr/local/lib --sysconfdir=/usr
==> make
==> make install-world datadir=/usr/local/Cellar/postgresql/11.1_1/share/postgresql libdir=/usr/local/Cellar/postgresql/11.1_1/lib pkglibdir
==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall postgresql`

Notice the last two lines of output ("Not running post_install as we're building a bottle").

# What you expected to happen

Formula should upgrade and run the postinstall hook even on old osx / if bottles do not exist.

# Step-by-step reproduction instructions (by running `brew` commands)

1. Install formula for which there exists a bottle (brew install postgresql)
2. Wait for new version of formula without provided bottle (brew edit postgresql, increase version)
3. Upgrade formula (brew upgrade postgresql)

**Comment by MikeMcQuaid** [comment]
Please provide all the information requested in the issue template or this will be closed.

**Comment by heptathlon** [comment]
I have updated my description @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
> brew doctor:
> Warning: You are using macOS 10.11. etc.

@heptathlon Can I see the full output for that?

Also, can I see the contents of `/usr/local/Cellar/postgresql/$WHATEVER_THE_OLD_VERSION_WAS/INSTALL_RECEIPT.json`

Thanks!

**Comment by heptathlon** [comment]
Full output of brew doctor:
"Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You may encounter build failures and other breakages.
Please create pull requests instead of asking for help on
Homebrew's GitHub, Discourse, Twitter or IRC. You are
responsible for resolving any issues you experience, as
you are running this old version.
"

I can no longer see the contents of the file, the only directory in "/usr/local/Cellar/postgresql" is "11.1_1" and the contents of "/usr/local/Cellar/postgresql/11.1_1/INSTALL_RECEIPT.json" are:

{"homebrew_version":"1.9.1-16-gab7a3c9","used_options":[],"unused_options":["--with-python"],"built_as_bottle":true,"poured_from_bottle":false,"installed_as_dependency":false,"installed_on_request":true,"changed_files":null,"time":1547398258,"source_modified_time":1541548829,"HEAD":"ab7a3c966fbcc33dd3561fe74fe83a005be23a91","stdlib":null,"compiler":"clang","aliases":["postgres","postgresql@11"],"runtime_dependencies":[{"full_name":"icu4c","version":"63.1"},{"full_name":"openssl","version":"1.0.2q"},{"full_name":"readline","version":"8.0.0"}],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/postgresql.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"11.1","devel":"","head":"HEAD","version_scheme":0}}}

"built_as_bottle":true but "poured_from_bottle":false, that is the issue. I have never used --build-bottle and only used "brew upgrade", "brew upgrade formula" and "brew upgrade --build-from-source formula".

I can check my backups for other INSTALL_RECEIPT.json from postgresql if required.

Hope this helps.

**Comment by heptathlon** [comment]
By the way: the same issue not only occurs for postgres but every time I upgrade a formula which uses a postinstall hook. I already wanted to report this a few months ago but forgot to.

**Comment by MikeMcQuaid** [comment]
Thanks, have opened https://github.com/Homebrew/brew/pull/5536 to address this.
