### ISSUE TITLE
Loading progress bar always prints on a new line

### ISSUE THREAD

**Issue by dijonkitchen** [Homebrew/brew#5563]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Install or update a package with feedback on one line.

Seems like #981 still exists and it's PR #1002 was not merged. I think most people don't touch their defaults and `$COLUMNS` is usually set to length 78. 

# What happened (include command output)

Mulit-line output of progress

<details>
  <summary>Command output</summary>
  <pre>
  
                                                                           0.1                                                                           0.2                                                                           0.3                                                                           0.4                                                                           0.6                                                                           0.7                                                                           0.9                                                                           1.0                                                                           1.3                                                                           1.4#                                                                          1.7#                                                                          2.2#                                                                          2.4#                                                                          2.8##                                                                         3.2##                                                                         3.5###                                                                        4.2###                                                                        5.2###                                                                        5.5####                                                                       6.0#####                                                                      7.1#####                                                                      7.6#####                                                                      8.3#######                                                                   10.2########                                                                  11.4########                                                                  11.9#########                                                                 13.7###########                                                               15.4###########                                                               15.8############                                                              17.0#############                                                             19.3###############                                                           21.4################                                                          23.3###################                                                       27.4#####################                                                     29.6#######################                                                   32.5##########################                                                37.2###########################                                               38.2#############################                                             40.6###############################                                           43.4#################################                                         46.1##################################                                        47.6####################################                                      51.0#####################################                                     52.5######################################                                    52.9######################################                                    53.9#######################################                                   55.3########################################                                  56.2#########################################                                 57.8##########################################                                58.8##########################################                                59.7############################################                              61.5#############################################                             62.7##############################################                            64.8###############################################                           66.2################################################                          67.9#################################################                         69.0##################################################                        70.2##################################################                        70.7###################################################                       71.7####################################################                      73.2#####################################################                     73.9#######################################################                   76.7########################################################                  77.9########################################################                  78.4########################################################                  79.1#########################################################                 79.3#########################################################                 79.5#########################################################                 79.8#########################################################                 80.0#########################################################                 80.2#########################################################                 80.5##########################################################                80.9##########################################################                81.4############################################################              83.5#############################################################             85.6##############################################################            86.3##############################################################            87.2###############################################################           88.6#################################################################         90.9##################################################################        92.6###################################################################       93.8####################################################################      94.7####################################################################      95.2####################################################################      95.4#####################################################################     95.9#####################################################################     96.2######################################################################## 100.0%

  
  </pre>
</details>

# What you expected to happen

Just output on one-line. 

# Step-by-step reproduction instructions (by running `brew` commands)

`brew install` or `brew upgrade` any package I didn't have before. 

`brew config`:
```
HOMEBREW_VERSION: 1.9.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 7be9ac1e9d550df18392550d611c5ff10b91292b
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7d4c03e53ee9bfa5fb938cf6572b2269075e75f2
Core tap last commit: 46 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/username/Library/Logs/Homebrew
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_92
macOS: 10.14.2-x86_64
CLT: N/A
Xcode: 10.1
```

`brew doctor`:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h

```

**Comment by MikeMcQuaid** [comment]
What size is your terminal? Can you reproduce this using `curl` outside of Homebrew?

**Comment by dijonkitchen** [comment]
Interesting, when I change the size of my terminal (normally `$COLUMNS` is 78 because I'm using exactly half my screen) I can get both results. As noted in other issue, under 80, it'll output it on multiple lines, but if I make it wider, it'll stick to one line. 

Is there a way to make the progress bar just detect the `$COLUMNS` length and stick to one line?

**Comment by MikeMcQuaid** [comment]
> Can you reproduce this using `curl` outside of Homebrew?

can you answer this, please?

> Is there a way to make the progress bar just detect the `$COLUMNS` length and stick to one line?

It's a `curl` issue so would need changed there.

**Comment by dijonkitchen** [comment]
Yes, running this command has the same problem:
`curl --progress-bar https://www.openssl.org/source/openssl-1.0.2m.tar.gz -o tmp`.

Closing this and made https://github.com/curl/curl/issues/3492.

**Comment by MikeMcQuaid** [comment]
Thanks!

**Comment by dijonkitchen** [comment]
Reopening since after updating to the latest version of `curl` (version 7.63.0), `brew install` still has this problem, while `curl` does not.

**Comment by RandomDSdevel** [comment]
@dijonkitchen:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Have you tried setting '`HOMEBREW_FORCE_BREWED_CURL`?'  Homebrew uses the system '`curl`' by default.

**Comment by dijonkitchen** [comment]
That solves it @RandomDSdevel ! So maybe the "too old" version should be bumped up to `7.58.0` or greater?

**Comment by MikeMcQuaid** [comment]
@dijonkitchen We like to use the macOS system versions where possible. This doesn't seem to be a major issue so it's not worth bumping the minimum version for everyone just for this (we save that for security or SSL certificate issues). Glad you have a solution to your problem and good idea @RandomDSdevel on a solution here.
