### ISSUE TITLE
MethodDeprecatedError: Calling GitHubPrivateRepositoryReleaseDownloadStrategy is disabled!

### ISSUE THREAD

**Issue by pieterza** [Homebrew/brew#5573]
My Formula stopped working, now install/upgrade presents:
`
MethodDeprecatedError: Calling GitHubPrivateRepositoryReleaseDownloadStrategy is disabled! Use a vendored GitHubPrivateRepositoryReleaseDownloadStrategy in your own formula or tap (using require_relative) instead.`

Any recent changes made by homebrew?

Formula below:

class FooRun < Formula
  include Language::Python::Virtualenv
  desc "CLI for foo containers"
  homepage "https://acme.org/"
  url "https://github.com/foo/eng-sysdev-foo-cli/releases/download/v1.4/foo_run.tgz", :using =>      GitHubPrivateRepositoryReleaseDownloadStrategy
  version "1.4"
  sha256 "2ebe14d1830c5c52710c7168d4858a01c4f51e4bf8cd20a096795cfb04eff905"
  head "https://github.com/foo/eng-sysdev-foo-cli.git"

  bottle :unneeded
  depends_on "python@3"

  def install
    venv = virtualenv_create(libexec)
    system libexec/"bin/pip3", "install", "-v", "--ignore-installed", "-r", "requirements.txt"
    env = {
      :PATH => "#{libexec}/bin:$PATH",
    }
    (bin/"foo_run").write_env_script(libexec/"foo_run", env)
    libexec.install "foo_run"
    libexec.install "libs"
  end

  test do
    system "echo", "TEST"
  end

  def caveats; <<~EOS
    Jumo run has been installed.
    Please run 'foo_run' which should now be in your path.
  EOS
  end

end

I require the private strategy and I pass a HOMEBREW_GITHUB_API_TOKEN 

Please advise

**Comment by MikeMcQuaid** [comment]
> I require the private strategy

This is no longer supported. You need to copy this into your formula yourself (as the message says).

**Comment by eiel** [comment]
> This is no longer supported. You need to copy this into your formula yourself (as the message says).

I tried, but japanese only.
https://qiita.com/eielh/items/812206e77696f947396f

**Comment by victorcoder** [comment]
Why this has been removed?

**Comment by MikeMcQuaid** [comment]
@victorcoder Because it wasn't used by any of Homebrew's supported formulae and we're a a volunteer run project who has to adjust our scope accordingly.
