### ISSUE TITLE
brew style fails with undefined method `/' for "./Formula/objconv.rb":String

### ISSUE THREAD

**Issue by olemis** [Homebrew/brew#5588]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Style check for some brew formulae.

# What happened (include command output)

Internal command error

<details>
  <summary>Command output</summary>
  <pre>
  
Error: undefined method `/' for "./Formula/objconv.rb":String
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/style.rb:64:in `check_style_impl'
/usr/local/Homebrew/Library/Homebrew/style.rb:8:in `check_style_and_print'
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:82:in `style'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
  
  </pre>
</details>

# What you expected to happen

Style checks [used to work](https://travis-ci.org/skycoin/homebrew-skycoin/builds/481040750#L205-L208)

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew tap skycoin/homebrew-skycoin
brew style $(brew --repo skycoin/homebrew-skycoin)/Formula/*.rb
```

**Comment by MikeMcQuaid** [comment]
In the mean time (until we make a better error) please use `brew style skycoin/skycoin`.
