### ISSUE TITLE
brew doctor: uninitialized constant MissingEnvironmentVariables

### ISSUE THREAD

**Issue by rodrigobdz** [Homebrew/brew#5592]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I tried to run `brew doctor`.

# What happened (include command output)

Since I updated my brew to the latest master commit 7be9ac1e9d550df18392550d611c5ff10b91292b I am getting this error. I already tried reinstalling via `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"` without success.

<details>
  <summary>Command output</summary>
  <pre>
  
/u/l/Homebrew (stable|✔) $ brew doctor
/usr/local/Homebrew/Library/Homebrew/brew.rb:15:in `rescue in <main>': uninitialized constant MissingEnvironmentVariables (NameError)
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in `<main>'
/u/l/Homebrew (stable|✔) $ brew config
/usr/local/Homebrew/Library/Homebrew/brew.rb:15:in `rescue in <main>': uninitialized constant MissingEnvironmentVariables (NameError)
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in `<main>'
/u/l/Homebrew (stable|✔) $ brew update
Already up-to-date.
/u/l/Homebrew (stable|✔) $ brew --help
/usr/local/Homebrew/Library/Homebrew/brew.rb:15:in `rescue in <main>': uninitialized constant MissingEnvironmentVariables (NameError)
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in `<main>'
  
  </pre>
</details>

# What you expected to happen

I expect brew not to throw an error while running `doctor`.

# Step-by-step reproduction instructions (by running `brew` commands)

Run `brew doctor`, `brew config` or `brew --help`.

**Comment by rodrigobdz** [comment]
`git -C /usr/local/Homebrew show --oneline`

> 7be9ac1e9 (HEAD -> stable, tag: 1.9.2) Merge pull request #5531 from maxim-belkin/completions-1

**Comment by MikeMcQuaid** [comment]
@rodrigobdz Thanks, working on a fix.
