### ISSUE TITLE
Brew cask info --json=v1 throws an error on conflicts-with field

### ISSUE THREAD

**Issue by cmbernard333** [Homebrew/brew#5596]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Trying to get a json representation using `brew cask info --json=v1` of the `firefox` and `google-chrome` cask formulae. 

# What happened (include command output)

Ruby emits an error message and stack trace and does not produce the json.

<details>
  <summary>Command output</summary>
  <pre>
  
 christianbernard@Dirac-MBP ~ $ brew cask info --json=v1 firefox
Error: undefined method `to_a' for #<Cask::DSL::ConflictsWith:0x00007fd8d2023688>
Did you mean?  to_yaml
               to_s
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:136:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/info.rb:15:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/info.rb:15:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
  
  </pre>
</details>

# What you expected to happen

Produce the correct json output for the `firefox` cask

# Step-by-step reproduction instructions (by running `brew` commands)

1. Run `brew cask info --json=v1 firefox`
2. Observe ruby error message and stacktrace

**Comment by MikeMcQuaid** [comment]
Closing in favour of PR: https://github.com/Homebrew/brew/pull/5597

You can skip creating an issue if you're going to make a PR yourself.

**Comment by cmbernard333** [comment]
Awesome. I'll keep that in mind for the future. Thanks.
