### ISSUE TITLE
brew upgrade breaks terminal, requiring reset

### ISSUE THREAD

**Issue by spl** [Homebrew/brew#560]
### Bug report:

_Note: I have described [the issue](https://apple.stackexchange.com/questions/245872/brew-upgrade-breaks-terminal-requiring-reset) on StackExchange. No answer so far, so I thought I'd post it here._

When I run `brew upgrade` in my Bash shell, it breaks the terminal display (in both iTerm2 and Terminal) such that I can't see anything I type in the following prompt and I can't see the history. For example, here is what my terminal looks like after typing `brew upgrade\necho hello\n` at an empty prompt:

```
$ brew upgrade
$ hello
$
```

The only way I've found to fix the current terminal is to use `reset`.

The following do not cause this problem:

```
$ brew upgrade 1> /dev/null # piping stdout
$ brew upgrade | cat
```

However, I still see the problem with:

```
$ brew upgrade 2> /dev/null # piping stderr
```

I don't see the problem in `zsh`.

I do have a custom prompt, but the problem still exists after disabling it by removing my `.bashrc`.

When I [check the output for ANSI color codes](http://unix.stackexchange.com/q/4527/137060), I don't see any.

The problem might have started when I upgraded to OS X from Yosemite to El Capitan (10.11). It's been some time, so I don't remember exactly.

I suppose the problem might be discovered by reviewing [the current Homebrew `upgrade.rb` code](https://github.com/Homebrew/brew/blob/3a127e405e45a4d95a809651553ff4a30ed95e3d/Library/Homebrew/cmd/upgrade.rb), but I wouldn't know where to start.

**Comment by apjanke** [comment]
Do you mind copying the body of the post over, so we have the full report here instead of having to go to an external site?

I can't reproduce locally on my 10.11 box. But the fact that `brew upgrade | cat` fixes it means it's highly likely something to do with ANSI escape sequences emitted by `brew` or a program it calls. But none of the color/styling sequences used by `brew` seem like they'd have that effect where *nothing* appears in response to your typing, not even a new line.

What happens if you run `brew upgrade` twice in a row?

Could you use `script` to capture the results of you running `brew upgrade` and attach it (preferably in a zip file) to this issue? That should capture any terminal control sequences, while `brew upgrade | cat` will prevent them from being emitted in the first place.

**Comment by MikeMcQuaid** [comment]
> Do you mind copying the body of the post over, so we have the full report here instead of having to go to an external site?

Agreed.

**Comment by spl** [comment]
> Do you mind copying the body of the post over, so we have the full report here instead of having to go to an external site?

Done.

**Comment by spl** [comment]
> What happens if you run brew upgrade twice in a row?

This is me typing `brew upgrade\n` twice:

```
$ brew upgrade
$
$
```

**Comment by spl** [comment]
> Could you use `script` to capture the results of you running `brew upgrade` and attach it (preferably in a zip file) to this issue?

Does this help?

```
home:~ spl$ mkdir tmp-script
home:~ spl$ cd tmp-script/
home:tmp-script spl$ script
Script started, output file is typescript
bash-3.2$ brew upgrade
bash-3.2$ ls
typescript
bash-3.2$ exit

Script done, output file is typescript
home:tmp-script spl$ hexdump -C typescript
00000000  53 63 72 69 70 74 20 73  74 61 72 74 65 64 20 6f  |Script started o|
00000010  6e 20 54 68 75 20 4a 75  6c 20 32 31 20 30 38 3a  |n Thu Jul 21 08:|
00000020  30 32 3a 31 37 20 32 30  31 36 0a 1b 5b 3f 31 30  |02:17 2016..[?10|
00000030  33 34 68 62 61 73 68 2d  33 2e 32 24 20 62 72 65  |34hbash-3.2$ bre|
00000040  77 20 75 70 67 72 61 64  65 0d 0a 62 61 73 68 2d  |w upgrade..bash-|
00000050  33 2e 32 24 20 6c 73 0d  0a 74 79 70 65 73 63 72  |3.2$ ls..typescr|
00000060  69 70 74 0d 0a 62 61 73  68 2d 33 2e 32 24 20 65  |ipt..bash-3.2$ e|
00000070  78 69 74 0d 0a 0a 53 63  72 69 70 74 20 64 6f 6e  |xit...Script don|
00000080  65 20 6f 6e 20 54 68 75  20 4a 75 6c 20 32 31 20  |e on Thu Jul 21 |
00000090  30 38 3a 30 32 3a 32 37  20 32 30 31 36 0a        |08:02:27 2016.|
0000009e
home:tmp-script spl$
```

**Comment by spl** [comment]
Hmm, that's interesting. As seen above, it didn't happen after the first `brew upgrade` in a new shell. But I tried it again, and it happened after the second. Here, I'm typing `brew upgrade\nls\nbrew upgrade\nls`:

```bash
home:~ spl$ mkdir tmp-script
home:~ spl$ cd tmp-script/
home:tmp-script spl$ script
Script started, output file is typescript
bash-3.2$ brew upgrade
bash-3.2$ ls
typescript
bash-3.2$ brew upgrade
bash-3.2$ typescript
bash-3.2$ exit

Script done, output file is typescript
home:tmp-script spl$ hexdump -C typescript
00000000  53 63 72 69 70 74 20 73  74 61 72 74 65 64 20 6f  |Script started o|
00000010  6e 20 54 68 75 20 4a 75  6c 20 32 31 20 30 38 3a  |n Thu Jul 21 08:|
00000020  31 32 3a 34 37 20 32 30  31 36 0a 1b 5b 3f 31 30  |12:47 2016..[?10|
00000030  33 34 68 62 61 73 68 2d  33 2e 32 24 20 62 72 65  |34hbash-3.2$ bre|
00000040  77 20 75 70 67 61 72 08  1b 5b 4b 08 1b 5b 4b 72  |w upgar..[K..[Kr|
00000050  61 64 65 0d 0a 62 61 73  68 2d 33 2e 32 24 20 6c  |ade..bash-3.2$ l|
00000060  73 0d 0a 74 79 70 65 73  63 72 69 70 74 0d 0a 62  |s..typescript..b|
00000070  61 73 68 2d 33 2e 32 24  20 62 72 65 77 20 75 70  |ash-3.2$ brew up|
00000080  67 72 61 64 65 0d 0a 62  61 73 68 2d 33 2e 32 24  |grade..bash-3.2$|
00000090  20 74 79 70 65 73 63 72  69 70 74 0d 0a 62 61 73  | typescript..bas|
000000a0  68 2d 33 2e 32 24 20 65  78 69 74 0d 0a 0a 53 63  |h-3.2$ exit...Sc|
000000b0  72 69 70 74 20 64 6f 6e  65 20 6f 6e 20 54 68 75  |ript done on Thu|
000000c0  20 4a 75 6c 20 32 31 20  30 38 3a 31 33 3a 30 30  | Jul 21 08:13:00|
000000d0  20 32 30 31 36 0a                                 | 2016.|
000000d6
home:tmp-script spl$
```

Still, nothing unusual showing up in the `script` output.

**Comment by spl** [comment]
I actually had a few deletes in the above typed sequence. I did it again with `brew upgrade\nls\nbrew upgrade\nls` (no deletes), and the result was different.

```
home:~ spl$ mkdir tmp-script
home:~ spl$ cd tmp-script
home:tmp-script spl$ script
Script started, output file is typescript
bash-3.2$ brew upgrade
bash-3.2$ typescript
bash-3.2$ bash-3.2$ typescript
bash-3.2$ exit

Script done, output file is typescript
home:tmp-script spl$ hexdump -C typescript
00000000  53 63 72 69 70 74 20 73  74 61 72 74 65 64 20 6f  |Script started o|
00000010  6e 20 54 68 75 20 4a 75  6c 20 32 31 20 30 38 3a  |n Thu Jul 21 08:|
00000020  31 39 3a 30 31 20 32 30  31 36 0a 1b 5b 3f 31 30  |19:01 2016..[?10|
00000030  33 34 68 62 61 73 68 2d  33 2e 32 24 20 62 72 65  |34hbash-3.2$ bre|
00000040  77 20 75 70 67 72 61 64  65 0d 0a 62 61 73 68 2d  |w upgrade..bash-|
00000050  33 2e 32 24 20 74 79 70  65 73 63 72 69 70 74 0d  |3.2$ typescript.|
00000060  0a 62 61 73 68 2d 33 2e  32 24 20 62 61 73 68 2d  |.bash-3.2$ bash-|
00000070  33 2e 32 24 20 74 79 70  65 73 63 72 69 70 74 0d  |3.2$ typescript.|
00000080  0a 62 61 73 68 2d 33 2e  32 24 20 65 78 69 74 0d  |.bash-3.2$ exit.|
00000090  0a 0a 53 63 72 69 70 74  20 64 6f 6e 65 20 6f 6e  |..Script done on|
000000a0  20 54 68 75 20 4a 75 6c  20 32 31 20 30 38 3a 31  | Thu Jul 21 08:1|
000000b0  39 3a 32 33 20 32 30 31  36 0a                    |9:23 2016.|
000000ba
home:tmp-script spl$
```

So, the result is nondeterministic. I suspected that might be the case, but now I've reproduced it a bit more rigorously.

**Comment by spl** [comment]
By the way, each of the above was from a new shell opened in iTerm2 with no `.bashrc`.

**Comment by apjanke** [comment]
Thanks for the additional diagnostics.

I'm a little befuddled here. I don't see any clues in that script output either. That `\e[?1034h` sequence just [enables the meta key setting the eighth bit](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Functions-using-CSI-_-ordered-by-the-final-character_s_). And I see no other escape characters in there.

I see a similar sequence in my normally-behaving `brew upgrade` in bash.

```
eilonwy:upgrade-terminal-breakage janke$ script typescript-02 bash
Script started, output file is typescript-02
bash-3.2$ brew upgrade
bash-3.2$ ls
typescript-01	typescript-02
bash-3.2$ exit
exit

Script done, output file is typescript-02
eilonwy:upgrade-terminal-breakage janke$ hexdump -C typescript-02
00000000  53 63 72 69 70 74 20 73  74 61 72 74 65 64 20 6f  |Script started o|
00000010  6e 20 54 68 75 20 4a 75  6c 20 32 31 20 31 33 3a  |n Thu Jul 21 13:|
00000020  35 30 3a 33 36 20 32 30  31 36 0a 1b 5b 3f 31 30  |50:36 2016..[?10|
00000030  33 34 68 62 61 73 68 2d  33 2e 32 24 20 62 72 65  |34hbash-3.2$ bre|
00000040  77 20 75 70 67 72 61 64  65 0d 0a 62 61 73 68 2d  |w upgrade..bash-|
00000050  33 2e 32 24 20 6c 73 0d  0a 74 79 70 65 73 63 72  |3.2$ ls..typescr|
00000060  69 70 74 2d 30 31 09 74  79 70 65 73 63 72 69 70  |ipt-01.typescrip|
00000070  74 2d 30 32 0d 0a 62 61  73 68 2d 33 2e 32 24 20  |t-02..bash-3.2$ |
00000080  65 78 69 74 0d 0a 65 78  69 74 0d 0a 0a 53 63 72  |exit..exit...Scr|
00000090  69 70 74 20 64 6f 6e 65  20 6f 6e 20 54 68 75 20  |ipt done on Thu |
000000a0  4a 75 6c 20 32 31 20 31  33 3a 35 30 3a 35 30 20  |Jul 21 13:50:50 |
000000b0  32 30 31 36 0a                                    |2016.|
000000b5
eilonwy:upgrade-terminal-breakage janke$
```

That makes me think something in there may be emitting a control sequence directly to `/dev/tty` instead of to `stdout` for you. But I don't know what would be doing it.

The fact that it happens under `bash` but not under `zsh` makes me think maybe it's some other `bash`-specific configuration. `brew` doesn't alter its behavior based on what shell it's running under (except to change the profile file path in some caveats it emits).

Any chance you have `$BASH_ENV` set? What's your `$TERM` set to?

Did you also disable `.bash_profile` and `.profile`?

What does `which brew` give you? Any chance you have a wrapper or extension set up?

**Comment by apjanke** [comment]
> When I [check the output for ANSI color codes](http://unix.stackexchange.com/q/4527/137060), I don't see any.

Oh, BTW, that technique generally won't work, unless you capture the output using `script` first instead of piping it directly to the filter that checks for escape sequences. Many programs, including `brew`, will check `stdout` to see if it is attached to a tty, and only emit terminal control escape sequences in that case. If you pipe or redirect `stdout`, it's no longer attached to a tty, and the program will change its behavior to not emit terminal control sequences, and you could get get a false negative. Same reason doing `brew upgrade | cat` could change its behavior.

**Comment by MikeMcQuaid** [comment]
Can you reproduce the same issue in Terminal.app? If not, I'm not sure how this is a Homebrew rather than iTerm bug.

**Comment by spl** [comment]
@apjanke: Thanks for your help and questions.

I moved `.bashrc` to `.bashrc.tmp` before all of the following.

> Any chance you have `$BASH_ENV` set? What's your `$TERM` set to?

```
home:~ spl$ echo $BASH_ENV

home:~ spl$ echo $TERM
xterm-256color
```

> Did you also disable `.bash_profile` and `.profile`?

```
home:~ spl$ cat .bash_profile 
# ~/.bash_profile

# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
[[ -f ~/.bashrc ]] && . ~/.bashrc
home:~ spl$ ls .profile
ls: .profile: No such file or directory
```

> What does `which brew` give you?

```
home:~ spl$ which brew
/usr/local/bin/brew
```

> Any chance you have a wrapper or extension set up?

I don't think so.

> Oh, BTW, that technique generally won't work [...]

Thank. That's good to know.

@MikeMcQuaid:

> Can you reproduce the same issue in Terminal.app?

Yes, the same thing happens in `Terminal.app`. I just tried it again and saw the same `script` output as the previous comment I had using `script`.

**Comment by spl** [comment]
I tried running `brew upgrade` within the following shell but still had the same problem.

```
home:~ spl$ /bin/bash --debug --norc --noprofile --restricted --noediting
```

**Comment by spl** [comment]
Hmm. I think I might have found the culprit. Once I do the following, `brew upgrade` doesn't break the terminal:

```
home:~ spl$ mv .editrc .editrc.tmp
```

This is what's in `.editrc`:

```
edit on
bind ^R em-inc-search-prev
```

Is `brew` using `editline` or conflicting with it somehow?

**Comment by spl** [comment]
If I `mv .editrc.tmp .editrc`, the problem comes back.

**Comment by apjanke** [comment]
That is a new one to me.

Sure sounds like you've identified the culprit. But I don't know what in `brew` would be using `.editrc`. I don't think we're intentionally using it. I used `otool -L` on `ruby`, `bash`, and a couple other commands, and didn't see any of them linking `libedit`, which is the library that `editrc` uses, according to `man editrc`.

If someone's familiar with `dtruss`, maybe it could be used to see what is opening `.editrc`.

**Comment by UniqMartin** [comment]
I was able to reproduce the issue after creating `~/.editrc` (the single line `edit on` was sufficient). Notice how this not only affects `brew upgrade`, but also `brew install` and a few other Homebrew commands (but not all).

The way `libedit` is pulled into the Homebrew session is via the `readline` extension in Ruby, that is most prominently used by IRB, which in turn is used to power some of Homebrew's interactive debug features during formula build. The IRB code is loaded even if those features aren't used.

I don't understand yet why this is causing the observed behavior and I'm also unclear on what the intended effect of `edit on` is (the documentation I found wasn't exactly enlightening). Anyway, maybe this additional information helps others to investigate this further.

**Comment by spl** [comment]
@UniqMartin: Great! I'm glad somebody could reproduce this. I also saw the problem with other `brew` commands, though I didn't do an exhaustive check to determine which ones.

Can someone reproduce it on Mac OS X 10.10 Yosemite? My fuzzy memory tells me that I didn't have the problem there, and I've had the `.editrc` longer than I've had El Capitan.

**Comment by scpeters** [comment]
I can reproduce it on yosemite 10.10.5 after `echo edit on > ~/.editrc`

**Comment by apjanke** [comment]
And I can reproduce on 10.9.5 with `echo "edit on" > ~/.editrc`. Looks like we've found the "what", but I don't know the "why".

I think Martin's right about it being related to IRB. I spent some time bisecting for a cause by sticking `puts "foo.rb - before XXX"; exit(1)` calls near the beginning of `cmd/upgrade.rb` and its dependencies, and chased it through a bunch of requires. I ended up at `require "debrew/irb"` in `debrew.rb`, which is included indirectly by `cmd/upgrade.rb` (through `require "install"`, another command which is affected). Commenting this out consistently made the problem disappear for me.

This makes some sense. IRB and readline show up in searches for "ruby editrc". IRB is an interactive tool that does line editing.

@spl, can you try reproducing this? Edit `Library/Homebrew/debrew.rb` and comment out line 2 where it does `require "debrew/irb"`.

```
require "mutex_m"
#require "debrew/irb"
```

When I do that, the disappearing text never happens.

**Comment by spl** [comment]
@apjanke:

> can you try reproducing this?

Yep, I can confirm that removing `require "debrew/irb"` from `/usr/local/Library/Homebrew/debrew.rb` fixes the issue and restoring it re-introduces the issue.

**Comment by UniqMartin** [comment]
On the other hand, a Ruby 2.0.0-p648 built against GNU Readline (e.g. `ruby20` from the homebrew/versions tap) doesn't have that issue, though it obviously also reads from `~/.inputrc` instead of `~/.editrc` and doesn't have an equivalent to the `edit on` command as far as I can tell.

I think this is simply a subtle incompatibility between `readline` and `libedit` as the system Ruby is built against the latter. `libedit` is supposed to be a drop-in replacement, but a Google search reveals quite a few instances where `libedit` failed to deliver on this promise.

I think there's nothing we can do on the Homebrew side to address this bug. My suggestion is to remove the `edit on` command from your `~/.editrc` file. If that's unacceptable, you can scope that line to programs where it's actually needed (cf. `editrc(5)` man page for details). That way it won't disturb `ruby` instances where it's not needed. And I'm still interested in an answer to my earlier question: What is the purpose of `edit on` command and what changes if it is omitted?

**Comment by spl** [comment]
@UniqMartin:

> What is the purpose of `edit on` command and what changes if it is omitted?

From my reading ([`el.c` rev 1.10](http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libedit/el.c?rev=1.10&content-type=text/x-cvsweb-markup&only_with_tag=MAIN) [diff](http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libedit/el.c.diff?r1=1.9&r2=1.10&only_with_tag=MAIN&f=h), [`parse.c` rev 1.8](http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libedit/parse.c?rev=1.8&content-type=text/x-cvsweb-markup&only_with_tag=MAIN) [diff](http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libedit/parse.c.diff?r1=1.7&r2=1.8&only_with_tag=MAIN&f=h)), which have the comment:

```
* add "edit  on | off" editrc command, which modifies EL_EDITMODE.
  users can now add '*:edit off' in ~/.editrc as an advisory to
  disable editing.
```

`edit on` sets `EL_EDITMODE`. According to `editline(3)`:


> EL_EDITMODE, int flag
> If flag is non-zero, editing is enabled (the default).  Note that this is only an indication, and does not affect the operation of editline.  At this time, it is the caller's responsibility to check this (using el_get()) to determine if editing should be enabled or not.

and

> BUGS
>     At this time, it is the responsibility of the caller to check the result of the EL_EDITMODE operation of el_get() (after an el_source() or el_parse()) to determine if editline should be used for further input.  I.e., EL_EDITMODE is purely an indication of the result of the most recent editrc(5) edit command.

I wrote my `.editrc` several years ago, and I don't remember what tool uses it. It may be that `edit on` is not strictly necessary.
