### ISSUE TITLE
Issue during installing HomeBrew

### ISSUE THREAD

**Issue by lowki93** [Homebrew/brew#5603]
Since 2h hours (after your last update) I can't install homebrew with this commande:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
I have this error:
` undefined method each' for "/Users/distiller/Library/Caches/Homebrew":String (NoMethodError)`

**Comment by MikeMcQuaid** [comment]
This has been fixed.
