### ISSUE TITLE
Install homebrew in macOS 10.14.2

### ISSUE THREAD

**Issue by fenixsolorzano** [Homebrew/brew#5608]
# What you were trying to do (and why)

Can't install homebrew

# What happened (include command output)

While running the install command I get the following output:

<details>
  <summary>Command output</summary>
  <pre>
  
Jonathans-MacBook-Pro:local jonathan$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/Homebrew
==> The Xcode Command Line Tools will be installed.

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/Homebrew
==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown jonathan /usr/local/Homebrew
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Homebrew
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
==> Installing Command Line Tools (macOS Mojave version 10.14) for Xcode-10.1
==> /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ (macOS\ Mojave\ version\ 10.14)\ for\ Xcode-10.1
Software Update Tool

Downloading Command Line Tools (macOS Mojave version 10.14) for Xcode
Error downloading Command Line Tools (macOS Mojave version 10.14) for Xcode: A server with the specified hostname could not be found.
Done.

Error downloading updates.
==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
xcode-select: error: invalid developer directory '/Library/Developer/CommandLineTools'
Failed during: /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
Jonathans-MacBook-Pro:local jonathan$ sudo /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Don't run this as root!
Jonathans-MacBook-Pro:local jonathan$
  
  </pre>
</details>

**Comment by fenixsolorzano** [comment]
Why did you close it @iMichka ?

**Comment by iMichka** [comment]
You did not fully fill out the issue template. Even if some points do not apply, it helps us keep the issues formatted the same for all issues.

Anyway, the problem you have looks like a user configuration problem. There is some problem with your Xcode/command line tools installation. The installer works fine for most of the people, so to me it looks like something weird is happening on your computer.
