### ISSUE TITLE
-bash: qemu: command not found

### ISSUE THREAD

**Issue by RizenLord** [Homebrew/brew#5609]
I tried to install qemu, and it installed successfully, but then when i tried to use it, bash gave me an error that red -bash: qemu: command not found   ((im on mac)

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
