### ISSUE TITLE
"Homebrew Shell Completion" instructions not working on macOS 10.14.2

### ISSUE THREAD

**Issue by samuela** [Homebrew/brew#5610]
I followed the bash instructions here: https://docs.brew.sh/Shell-Completion but kept getting the error 
```
nuvemfs 🔥 source ~/.bash_profile
-bash: /usr/local/etc/bash_completion.d/*: No such file or directory
```
which isn't so cool. Replacing it with 
```bash
if type brew 2&>/dev/null; then
    source "$(brew --prefix)/etc/bash_completion"
else
  echo "run: brew install git bash-completion"
fi
```
works just fine however.

**Comment by MikeMcQuaid** [comment]
This was changed by @iandol in https://github.com/Homebrew/brew/pull/5511. @iandol could you provide some help/thoughts here? Thanks!

**Comment by iandol** [comment]
Yes, there may be some confusion from bash-completion package vs auto installed completion files.  https://docs.brew.sh/Shell-Completion is talking about the auto installed completion files, so I assume it is `/bash_completion.d/` while the bash-completion package appears to use `/bash_completion`?

**Comment by MikeMcQuaid** [comment]
@iandol @samuela I think ideally the docs would handle either/both and also if neither/none is installed.

**Comment by maxim-belkin** [comment]
One should source only one file:
```sh
$(brew --prefix)/etc/profile.d/bash_completion.sh
```
This file checks that Bash has the right version and then sources the right `bash_completion` file. In case you have `bash-completion` formula installed, it will source 
```
/usr/local/Cellar/bash-completion/1.3_3/etc/bash_completion
```
If you have `bash-completion@2` installed, it will source
```
/usr/local/Cellar/bash-completion@2/2.8/share/bash-completion/bash_completion
```
This `bash_completion` file provides some bash Bash-specific completions and also loads all the right program-specific completions.

**Comment by iandol** [comment]
But why does @samuela not even have a `bash_completion.d/` on his system, as the completions files include `brew` and `brew-services` so  I would have imagined they'd be present on all homebrew installs whether `bash_completion` was installed or not?

As for the docs, I wonder if  the `else ... echo "run: brew install git bash-completion"` should be removed — as it only talks about `Homebrew’s completions` which is IINM not related at all to the bash-completion project. 

While we're here, why does it recommend to use: `if type brew 2&>/dev/null; then` — why not just look for the folder directly?

**Comment by iandol** [comment]
@maxim-belkin thanks for your knowledge. However I don't have that file:

```
 ❯ ll $(brew --prefix)/etc/profile.d/bash_completion.sh
ls: /usr/local/etc/profile.d/bash_completion.sh: No such file or directory
```

**Comment by maxim-belkin** [comment]
`bash-completion` and `bash-completion@2` store program-specific programmable completions in different folders (this is what I have on my Mac):
```sh
$ brew list bash-completion
/usr/local/Cellar/bash-completion/1.3_3/etc/bash_completion.d/ (180 files)
/usr/local/Cellar/bash-completion/1.3_3/etc/profile.d/bash_completion.sh
/usr/local/Cellar/bash-completion/1.3_3/etc/bash_completion

$ brew list bash-completion@2
/usr/local/Cellar/bash-completion@2/2.8/etc/profile.d/bash_completion2.sh  // this file should be 
/usr/local/Cellar/bash-completion@2/2.8/share/bash-completion/ (657 files)
/usr/local/Cellar/bash-completion@2/2.8/share/cmake/ (2 files)
/usr/local/Cellar/bash-completion@2/2.8/share/pkgconfig/bash-completion.pc
```

@iandol what does `brew list bash-completion` or `brew list bash-completion@2` return to you?

**Comment by iandol** [comment]
I have neither of them installed on my macOS system; I only have the default auto-installed completion files.

**Comment by maxim-belkin** [comment]
Then you shouldn't be surprised that you don't have `$(brew --prefix)/etc/profile.d/bash_completion.sh`

**Comment by MikeMcQuaid** [comment]
@maxim-belkin Please note what I wrote above:

> I think ideally the docs would handle either/both and also if neither/none is installed.

Would be good to have something that handles `bash-completion` being installed or just `bash_completion` files being installed by formulae.

**Comment by maxim-belkin** [comment]
> Would be good to have something that handles bash-completion being installed or just bash_completion files being installed by formulae.

Currently, the situation is as follows:
1. `$(brew --prefix)/etc/bash_completion.d/` is used by:
        - brew
        - completions installed by individual formulae
        - `bash-completion` formula
2. `bash-completion@2` formula installs its completion files in `#{share}/bash-completion/`

Both `bash-completion` and `bash-completion@2` formulae provide special scripts that safe-guard against sourcing their completions under wrong Bash version.

Our options

1. Change `bash-completion@2` formula to install its completions in `$(brew --prefix)/etc/bash_completion.d/` and instruct users to blindly source all files in that directory. In that case we don't care about those special scripts that `bash-completion` and `bash-completion@2` formula provide.

2. Don't change installation locations anywhere but make sure users understand that programmable completions installed by `bash-completion` formula will be sourced automatically if they source all files in `$(brew --prefix)/etc/bash_completion.d/`

3. Change `bash-completions` formula to install its completions in a different folder. In this case users will have to

   - source all files in `$(brew --prefix)/etc/bash_completion.d/` (Brew + individual formulae-provided bash completions)
   - source one more script provided by either of the `bash-completion*` formulae

**Comment by samuela** [comment]
> But why does @samuela not even have a bash_completion.d/ on his system, as the completions files include brew and brew-services so I would have imagined they'd be present on all homebrew installs whether bash-completion was installed or not?

I do in fact have that directory on my system. I think bash was complaining because that directory has no file named "*".

**Comment by maxim-belkin** [comment]
Bash translates `*` to a literal symbol `*` only when the directory is completely empty (0 non-hidden files/directories).

Brew installs its own completions in `$(brew --prefix)/etc/bash_completion.d/`, so this directory must exist. There might be something wrong with your setup. A quick-and-dirty fix would be to manually add a symbolic link to `brew` completions in there:
```
cd $(brew --prefix)/etc/profile.d/
ln -s ../../Homebrew/completions/bash/brew
```

**Comment by maxim-belkin** [comment]
I’m traveling today. Will leave my comments as soon as I get back.

**Comment by MikeMcQuaid** [comment]
@iandol Can we move discussion to https://github.com/Homebrew/brew/pull/5625, it's hard to keep track of both place.
