### ISSUE TITLE
brew install php71-mcrypt not working

### ISSUE THREAD

**Issue by abuzer-firdousi-confiz** [Homebrew/brew#5612]
Abuzers-MBP:php abuzer$ brew install php71-mcrypt
Error: No available formula with the name "php71-mcrypt" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
^[[AError: No formulae found in taps.
Abuzers-MBP:php abuzer$  brew search php71-mcrypt
No formula or cask found for "php71-mcrypt".
Closed pull requests:
php@7.1: import from homebrew/php (https://github.com/Homebrew/homebrew-core/pull/24766)
php71: migrate to homebrew/core (https://github.com/Homebrew/homebrew-php/pull/4798)
enchant 2.2.0 (https://github.com/Homebrew/homebrew-core/pull/21807)
Add PHP 7.2.0-alpha.1 core formula (php72) (https://github.com/Homebrew/homebrew-php/pull/4211)
php71-mcrypt: update bottle (https://github.com/Homebrew/homebrew-php/pull/3698)
php71-mcrypt: update bottle (https://github.com/Homebrew/homebrew-php/pull/3606)
Add php71-mcrypt formula (https://github.com/Homebrew/homebrew-php/pull/3404)
Abuzers-MBP:php abuzer$  brew search php71-mcrypt

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
