### ISSUE TITLE
Missing 'setup.py' argument when invoked from Language::Python.setup_install_args

### ISSUE THREAD

**Issue by albertosottile** [Homebrew/brew#5618]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem ~~with multiple formulae~~?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Bumping the `pyside` formula (Qt for Python) to the new version. See this PR https://github.com/Homebrew/homebrew-core/pull/35910 for further details. Please note that this issue occurs also during the building tests performed on your Jenkins system for the PR.

# What happened (include command output)

Compiling the new release fails. The argument `setup.py` is missing from the invocation made by `Language::Python.setup_install_args` in the formula, which is (for python3):
`/usr/local/opt/python/bin/python3.7 -c --no-user-cfg install --prefix=/usr/local/Cellar/pyside/5.12.0 --install-scripts=/usr/local/Cellar/pyside/5.12.0/bin --single-version-externally-managed --record=installed.txt --install-lib /usr/local/Cellar/pyside/5.12.0/lib/python3.7/site-packages --ignore-git --no-examples --macos-use-libc++ --jobs=3 --install-scripts /usr/local/Cellar/pyside/5.12.0/bin --internal-build-type=shiboken2`

`setup.py` should be after `-c`. Running `setup.py` manually works, even while in superenv.

<details>
  <summary>Command output</summary>
  <pre>
  
  /usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: python3 -c import\ setuptools,\ tokenize
__file__\ =\ 'setup.py'
exec(compile(getattr(tokenize,\ 'open',\ open)(__file__).read()
\ \ .replace('\r\n',\ '\n'),\ __file__,\ 'exec'))
 --no-user-cfg install --prefix=/usr/local/Cellar/pyside/5.12.0 --install-scripts=/usr/local/Cellar/pyside/5.12.0/bin --single-version-externally-managed --record=installed.txt --install-lib /usr/local/Cellar/pyside/5.12.0/lib/python3.7/site-packages --ignore-git --no-examples --macos-use-libc++ --jobs=4 --install-scripts /usr/local/Cellar/pyside/5.12.0/bin
  
  </pre>
</details>

# What you expected to happen

The formula should have compiled and installed pyside correctly.

# Step-by-step reproduction instructions (by running `brew` commands)

`brew bump-formula-pr -n --write -f --url=https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.12.0-src/pyside-setup-everywhere-src-5.12.0.tar.xz pyside` 
(the `-f` is needed because the PR has been already opened)

`brew install --verbose --debug -s pyside`

# brew config

```
HOMEBREW_VERSION: 1.9.3-22-g0670282
ORIGIN: https://github.com/Homebrew/brew
HEAD: 06702829080aaf1e8b741ff34f7a2f4118b7e411
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c30b22bca85fb1320cabcda2746e7c8ed1bc44d0
Core tap last commit: 67 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/alberto/Library/Logs/Homebrew
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

# brew doctor

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/alberto/miniconda2/bin/python2-config
  /Users/alberto/miniconda2/bin/python2.7-config
  /Users/alberto/miniconda2/bin/python-config
  /Users/alberto/miniconda2/bin/ncursesw6-config
```

**Comment by MikeMcQuaid** [comment]
Can you explain why this is a bug in Homebrew itself? Is `setup.py` literally always needed in this case? What has changed to mean that this no longer works in Pyside?

**Comment by albertosottile** [comment]
The content of the `setup.py` file probably changed, but the thing is that the code in `Language::Python.setup_install_args` is supposed to work with any file, and right now it is trying to execute this: `python3 -c import\ setuptools,\ tokenize file\ =\ 'setup.py' exec(compile(getattr(tokenize,\ 'open',\ open)(file).read() \ \ .replace('\r\n',\ '\n'),\ file,\ 'exec')) --no-user-cfg install [...]`

so that's why I thought it was a Homebrew bug.

**Comment by tdsmith** [comment]
@albertosottile tagged me in on IRC --

>  Is setup.py literally always needed in this case? 

No, it's never needed; the snippet executed with `-c` loads and executes setup.py in a modified environment, so specifying setup.py again on the command line will just be ignored.

I think the failure was misattributed because the way we censor the snippet from the console looks funny; setup.py is failing but the specific way we're invoking setup.py probably isn't related. We can close this and continue debugging in the pyside issue.

**Comment by MikeMcQuaid** [comment]
:wave: and thanks @tdsmith!
