### ISSUE TITLE
 Error: Calling keg_only :provided_pre_mountain_lion is disabled! There is no replacement.

### ISSUE THREAD

**Issue by gtollefson** [Homebrew/brew#5630]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew config` and `brew doctor` and included their output with your issue?

> Georges-MacBook-Pro:~ George$ brew config
> HOMEBREW_VERSION: 1.9.3-41-g76b3c3d
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: 76b3c3dbe2ea1dcfb76b0036ef06804be7c590a4
> Last commit: 3 hours ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: 63063c790f814ff24a6d66631b7174f59e2dbeaa
> Core tap last commit: 3 hours ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_DEV_CMD_RUN: 1
> HOMEBREW_LOGS: /Users/George/Library/Logs/Homebrew
> CPU: quad-core 64-bit broadwell
> Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
> Clang: 9.1 build 902
> Git: 2.20.1 => /usr/local/bin/git
> Curl: 7.54.0 => /usr/bin/curl
> Java: 10, 1.8.0_131, 1.6.0_65-b14-468
> macOS: 10.13.6-x86_64
> CLT: 9.4.0.0.1.1526532315
> Xcode: N/A

> Georges-MacBook-Pro:~ George$ brew update
> Already up-to-date.
> Georges-MacBook-Pro:~ George$ brew doctor
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry or file an issue; just ignore this. Thanks!
> 
> Warning: A newer Command Line Tools release is available.
> Update them from Software Update in the App Store.
> 
> 
> Warning: "config" scripts exist outside your system or Homebrew directories.
> `./configure` scripts often look for *-config scripts to determine if
> software packages are installed, and what additional flags to use when
> compiling and linking.
> 
> Having additional scripts in your path can confuse software installed via
> Homebrew if the config script overrides a system or Homebrew provided
> script of the same name. We found the following "config" scripts:
>   /Users/George/anaconda3/bin/icu-config
>   /Users/George/anaconda3/bin/freetype-config
>   /Users/George/anaconda3/bin/xslt-config
>   /Users/George/anaconda3/bin/libpng16-config
>   /Users/George/anaconda3/bin/python3.6m-config
>   /Users/George/anaconda3/bin/libpng-config
>   /Users/George/anaconda3/bin/xml2-config
>   /Users/George/anaconda3/bin/python3-config
>   /Users/George/anaconda3/bin/curl-config
>   /Users/George/anaconda3/bin/ncursesw6-config
>   /Users/George/anaconda3/bin/pcre-config
>   /Users/George/anaconda3/bin/python3.6-config
> 
> Warning: Unbrewed dylibs were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected dylibs:
>   /usr/local/lib/libtk8.6.dylib
> 
> Warning: Unbrewed header files were found in /usr/local/include.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected header files:
>   /usr/local/include/fakemysql.h
>   /usr/local/include/fakepq.h
>   /usr/local/include/fakesql.h
>   /usr/local/include/itcl.h
>   /usr/local/include/itcl2TclOO.h
>   /usr/local/include/itclDecls.h
>   /usr/local/include/itclInt.h
>   /usr/local/include/itclIntDecls.h
>   /usr/local/include/itclMigrate2TclCore.h
>   /usr/local/include/itclTclIntStubsFcn.h
>   /usr/local/include/mysqlStubs.h
>   /usr/local/include/odbcStubs.h
>   /usr/local/include/pqStubs.h
>   /usr/local/include/tcl.h
>   /usr/local/include/tclDecls.h
>   /usr/local/include/tclOO.h
>   /usr/local/include/tclOODecls.h
>   /usr/local/include/tclPlatDecls.h
>   /usr/local/include/tclThread.h
>   /usr/local/include/tclTomMath.h
>   /usr/local/include/tclTomMathDecls.h
>   /usr/local/include/tdbc.h
>   /usr/local/include/tdbcDecls.h
>   /usr/local/include/tdbcInt.h
>   /usr/local/include/tk.h
>   /usr/local/include/tkDecls.h
>   /usr/local/include/tkPlatDecls.h
> 
> Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected .pc files:
>   /usr/local/lib/pkgconfig/tcl.pc
>   /usr/local/lib/pkgconfig/tk.pc
> 
> Warning: Unbrewed static libraries were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected static libraries:
>   /usr/local/lib/libtclstub8.6.a

# What you were trying to do (and why)
I am trying to install the RSVG and Cairo packages through the Julia REPL with Pkg.build("pkg") and receive errors from homebrew. 

> julia> Pkg.build("RSVG")
> INFO: Building Homebrew
> Already up-to-date.
> INFO: Building Cairo
> Error: Calling keg_only :provided_pre_mountain_lion is disabled! There is no replacement.
> ================================[ ERROR: Cairo ]================================
> 
> LoadError: ArgumentError: `brew info` failed for String["staticfloat/juliadeps/fontconfig"]!
> while loading /Users/George/.julia/test/v0.6/Cairo/deps/build.jl, in expression starting on line 165
> 
> ================================================================================
> INFO: Building RSVG
> Error: No available formula with the name "libgio" 
> objc[65462]: Class GNotificationCenterDelegate is implemented in both /usr/local/opt/glib/lib/libgio-2.0.0.dylib (0x1165e2498) and /Users/George/.julia/test/v0.6/Homebrew/deps/usr/lib/libgio-2.0.dylib (0x12589b498). One of the two will be used. Which one is undefined.
> Error: No available formula with the name "libgio" 
> 
> ================================[ BUILD ERRORS ]================================
> 
> WARNING: Cairo had build errors.
> 
>  - packages with build errors remain installed in /Users/George/.julia/test/v0.6
>  - build the package(s) and all dependencies with `Pkg.build("Cairo")`
>  - build a single package by running its `deps/build.jl` script
> 
> =====================================================================
> 
> 

I tried the fix for the similar issue in #4093 but this didn't work. They recommended running brew tap to list packages tapped at old versions then untap and tap at the new version. I did this with homebrew/core and homebrew/cask with no effect. The list of warnings produced with `brew doctor` is confusing to me and I don't want to delete files to resolve warnings without feeling confident.

**Comment by MikeMcQuaid** [comment]
This needs to be fixed in Julia and not Homebrew.

**Comment by MikeMcQuaid** [comment]
(and reported to them rather than us)
