### ISSUE TITLE
Upgrade step order

### ISSUE THREAD

**Issue by cncolder** [Homebrew/brew#5634]
# A detailed description of the proposed feature

For now, brew upgrade step is:
*remove* > download > verify > clean > finish

I think the better order is:
download > verify > *remove* > clean > finish

Or even:
download > verify > clean > *remove* > finish

# The motivation for the feature

Most time upgrade fail is download fail. If we remove symbol link after download. Maybe we can simple stop or retry, and we don't need rollback symbol link.

This can give user a shorter **downtime**. When I upgrade `node`. I don't need waiting the bottle download finish. I can run old version `node` until upgrade success.

# How the feature would be relevant to at least 90% of Homebrew users

I'm not sure If package developer work flow relay on this order.

# What alternatives to the feature have been considered

**Comment by MikeMcQuaid** [comment]
There is no separate remove/clean step; they are the same. `brew upgrade` doesn't remove before cleaning up. Can you paste the output you're seeing that makes you think otherwise?

> I don't need waiting the bottle download finish.

`brew fetch` may be a better fit to pre-download packages.

**Comment by cncolder** [comment]
```shell
> brew upgrade --verbose
Updating Homebrew...
==> Upgrading 1 outdated packages:
youtube-dl 2019.01.24 -> 2019.01.27
==> Upgrading youtube-dl
rm /usr/local/bin/youtube-dl
rm /usr/local/etc/bash_completion.d/youtube-dl.bash-completion
rm /usr/local/share/fish/vendor_completions.d/youtube-dl.fish
rm /usr/local/share/man/man1/youtube-dl.1
rm /usr/local/share/zsh/site-functions/_youtube-dl
rmdir /usr/local/share/fish/vendor_completions.d
rmdir /usr/local/share/fish
/usr/bin/sandbox-exec -f ... /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/youtube-dl.rb --verbose
==> Downloading https://github.com/rg3/youtube-dl/releases/download/2019.01.27/youtube-dl-2019.01.27.tar.gz
...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  3 3029k    3 95593    0     0   1388      0  0:37:15  0:01:08  0:36:07     0
```

```shell
> which youtube-dl
youtube-dl not found
```

**Comment by MikeMcQuaid** [comment]
@cncolder Those are all symlinks that are removed rather than the application itself. They need to be removed before install so the new ones can be created.

**Comment by cncolder** [comment]
Ye. But why not remove symlinks after download?

**Comment by MikeMcQuaid** [comment]
@cncolder Downloads are pretty built-in to the install process. We would review a PR to improve this but aren't planning work around it.

**Comment by cncolder** [comment]
Thanks @MikeMcQuaid 

Only a suggestion. I'm not dig into brew source codes yet. I understand maybe it's not easy to implement.

**Comment by MikeMcQuaid** [comment]
@cncolder No worries, thanks for understanding ❤️
