### ISSUE TITLE
Add audit to automatically detect insecure URLs

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#564]
Perhaps based on @vszakats' work in https://github.com/vszakats/https-check/blob/master/chkhttps.sh and be part of `audit --online`.

**Comment by broder** [comment]
I was thinking of taking a look at this issue and noticed that there are already a couple of steps to deal with this within this method https://github.com/Homebrew/brew/blob/f73b4eafcf5a57ec64b5c8d2f363b0e44a34d4df/Library/Homebrew/dev-cmd/audit.rb#L1219. Do you think it would still be worth curling both the https and http URLs for cases not covered by the existing checks?

**Comment by MikeMcQuaid** [comment]
> Do you think it would still be worth curling both the https and http URLs for cases not covered by the existing checks?

Yep, definitely! Based on your work so far in https://github.com/Homebrew/brew/pull/1637 I'm confident you'll be able to do a good job at this. Thanks!

**Comment by MikeMcQuaid** [comment]
Done by @broder in https://github.com/Homebrew/brew/pull/1722 🎉

**Comment by MikeMcQuaid** [comment]
(and https://github.com/Homebrew/brew/pull/1637)
