### ISSUE TITLE
coreutils is creating symlinks for just some tools without the `g` prefix

### ISSUE THREAD

**Issue by ericbn** [Homebrew/brew#5641]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] it's a problem with a single, official formula (not cask) and I filed this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

On MacOS High Sierra, after upgrading to coreutils-8.30_1.high_sierra, I noticed its installation creates symlinks without the `g` prefix for some tools, which it should absolutely not do according to the "Caveats". Plus just doing it for some utilities yields an invalid setup, like having a GNU `dircolors` but not a GNU `ls`, which makes no sense.

# What happened (include command output)

I have a general dotfiles setup that tests for the presence of GNU `dircolors` and created a GNU `ls` alias accordingly (it is also used outside MacOS).

<details>
<summary>Command output</summary>
<pre>
% ls
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
% type ls
ls is an alias for ls --group-directories-first --color=auto
% type dircolors
dircolors is /usr/local/bin/dircolors
% brew config
HOMEBREW_VERSION: 1.9.3-56-ga198b0e
ORIGIN: https://github.com/Homebrew/brew
HEAD: a198b0ef43f48e9ab18df668a94b6b2a82be41dd
Last commit: 4 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d5b669e1eaa131c1d0b00c72fb37ca7a03e6d33d
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/eric/Library/Logs/Homebrew
HOMEBREW_VISUAL: vim
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_192, 1.7.0_80, 1.6.0_65-b14-468
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
</pre>
</details>

It fails because after the broken coreutils upgrade/install, I got a GNU `coreutils`, but not a GNU `ls`. The coreutils "Caveats" explictly state that:

```
All commands have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```

which is not being accomplished.

# What you expected to happen

None of the symlinks created in /usr/local/bin for coreutils should have a `g` prefix.

# Step-by-step reproduction instructions (by running `brew` commands)

```
% brew uninstall coreutils
Uninstalling /usr/local/Cellar/coreutils/8.30_1... (478 files, 8.9MB)
% brew update
Already up-to-date.
% brew install coreutils
Updating Homebrew...
...
==> Downloading https://homebrew.bintray.com/bottles/coreutils-8.30_1.high_sierra.bottle.tar.gz
Already downloaded: /Users/eric/Library/Caches/Homebrew/downloads/4073e98fa34d4ab16cb5976bba588d09fce0cd2cd53d671cdf6e1c4bf2fc9461--coreutils-8.30_1.high_sierra.bottle.tar.gz
==> Pouring coreutils-8.30_1.high_sierra.bottle.tar.gz
==> Caveats
All commands have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
==> Summary
🍺  /usr/local/Cellar/coreutils/8.30_1: 478 files, 8.9MB
% command ls -la /usr/local/bin | grep -F -- '-> ../Cellar/coreutils' | awk '{print $9}' | grep -v '^g'
b2sum
base32
chcon
dir
dircolors
hostid
md5sum
nproc
numfmt
pinky
ptx
realpath
runcon
sha1sum
sha224sum
sha256sum
sha384sum
sha512sum
shred
shuf
stdbuf
tac
timeout
truncate
vdir
%  
```

**Comment by ericbn** [comment]
I see this was changed in https://github.com/Homebrew/homebrew-core/commit/3ae3966d96eddf899904aa75f0f9353041972ce8. The idea of "non-conflicting GNU tools" might be not as simple as "any tool that BSD does not have", as for example having GNU dircolors (that sets LS_COLORS) together with BSD ls (which uses the LSCOLORS environment variable) makes no sense. I wonder which other combinations of GNU + BSD tools could be conflicting too.

**Comment by MikeMcQuaid** [comment]
Please discuss on that PR, thanks.
