### ISSUE TITLE
Please correct wrong triggering of brew cleanup

### ISSUE THREAD

**Issue by tiiiecherle** [Homebrew/brew#5644]
First of all thanks for the brew projects. I really like them and use them very often on a lot of macs ;)

In some cases (submitting bug reports, etc.) it is suggested to reset the branches like the following:

`brew update-reset 1> /dev/null 2> >(grep -v "Reset branch" 1>&2) && brew analytics off 1> /dev/null && brew update 1> /dev/null && brew doctor 1> /dev/null`

So for avoiding issues I integrated it in my update script and it really solved problems in the past.

It seems like there has been an a recent implementation of code that checks if brew cleanup has been run in the last 30 days.

After resetting the repos like described above the feature seems to be triggered
`==> brew cleanup has not been run in 30 days, running now...`
even though is has been used right before resetting.

I hope it can be corrected as the message is missleading here. I don't know where it is stored if the command was run or not, but perhaps this file / place / entry shall not be wiped by the reset.

Thanks in advance

Kind regards

**Comment by MikeMcQuaid** [comment]
> I hope it can be corrected as the message is missleading here. I don't know where it is stored if the command was run or not, but perhaps this file / place / entry shall not be wiped by the reset.

It's stored in Homebrew's cache i.e. `~/Library/Caches/Homebrew/.cleaned`

Please always fill in the issue template.

**Comment by tiiiecherle** [comment]
Thanks for the fast response. So it was not triggered by the reset command above but by cleaning the cache directory at the end of the script. Solved by changing orders in the cleaning process. Thanks again.
