### ISSUE TITLE
Consider making `brew --help` show `man brew` output

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#565]
The output of `man brew` is much more complete and helpful at this point than `brew --help`. We should consider making it shown on `brew --help`.

**Comment by DomT4** [comment]
I'm unsure about this. There's an ocean of information in `man brew` and I'm not sure that isn't overwhelming to suddenly encounter. To me `brew --help` is largely there to explain the basic commands & nudge towards more detailed help where necessary, which is more or less what we already do.

Would like to see some more user feedback before changing this, but it's not something I'm going to die on a hill over if others are particularly passionate about the proposed change.

**Comment by MikeMcQuaid** [comment]
Arguably we could put the `brew --help` output at the top of `man brew`. `git --help` is an example that outputs the manpage.

**Comment by DomT4** [comment]
Looking at the output between `man git` and `git --help` I see the similarities, but the latter seems quite a bit more summarised/compressed than the full `man` output?

**Comment by MikeMcQuaid** [comment]
I'm wrong and was thinking of `git` subcommands where it's the same, ignore me. Perhaps we could just fill out our `--help` to provide a description of what each command does?

**Comment by UniqMartin** [comment]
I'm not sure how helpful `brew --help` is for new users, but I always liked that it is brief. While it doesn't formally explain the `brew` invocation it does so by example and doesn't fail to point out that there's a man page and command-specific help via `brew help COMMAND`. The latter is identical to the command-specific information in the man page. Only the more general usage instructions also contained in the man page are missing.

> I'm wrong and was thinking of `git` subcommands where it's the same, ignore me.

We could consider moving to a per-command model like Git uses, but I'm not sure whether the comparatively low complexity of most of our commands (or sometimes just the brevity of our documentation) would make this look silly. One advantage of individual man pages is that this results in more seamless integration of help provided by external commands, `brew cask` and the accompanying `brew-cask(1)` man page probably being the most prominent example.

> Perhaps we could just fill out our `--help` to provide a description of what each command does?

Do you have certain entries in mind where you feel they are non-obvious? I just checked the printed list and all of the terminology (in the name of the command) from “Example usage” felt natural, particularly if one is already familiar with a different package manager. Someone less familiar might have trouble telling apart `update` and `upgrade` (and maybe `search` and `list`).

**Comment by tdsmith** [comment]
> The output of man brew is much more complete and helpful at this point than brew --help.

I'd always thought this was by design. I've gotten used to `brew --help` being a hit-the-ground-running primer as opposed to complete documentation and I think that's still a fine decision. I don't have very strong feelings.

**Comment by Eitot** [comment]
(From a user’s perspective:) I believe that it is unconventional to blend `--help` and `man`, because both have distinct and expected purposes which were already touched upon by others. ``--help`` is supposed to be a quick-start guide or cheat sheet, whereas `man` is a more extensive manual. I do not recall any CLI program, on Mac or Linux, that does this and I would find it undesirable to not have the advantage of `--help`. I personally do not see a compelling reason to go against the grain here, given that `--help` mentions `man brew` and `brew help [command]` explicitly anyway. I have no opinion on a more fleshed-out `brew help`, as long as `--help` and `man` stay true to what they are generally used for.

**Comment by MikeMcQuaid** [comment]
Passing on this.
