### ISSUE TITLE
brew upgrade, reinstall are removing old versions without being asked

### ISSUE THREAD

**Issue by sj26** [Homebrew/brew#5654]
This is really just some feedback: I just ran `brew update && brew upgrade` as usual and it removed a lot of old keg versions that I relied upon. It broke a lot of python and ruby extensions which were linked to keg versioned libraries. I did not ask it to do this, and I cannot find a way to turn this behaviour off. This is new behaviour that has been added and executee without notifying me and severely hampered my system and my workflow, and undermines something I understood about homebrew — that it keeps versions seperate and allows me to retain compatibility with old versions nicely. Please provide an option to turn this behaviour off.

**Comment by sj26** [comment]
Okay, I found `HOMEBREW_NO_INSTALL_CLEANUP` after digging into homebrew's code. But I was *very* surprised that this behaviour changed implicitly, and cannot find any mention of cleanup or previous versions being removed in the brew upgrade or reinstall built-in docs:

```
$ brew upgrade --help
Usage: brew upgrade [options] formula

Upgrade outdated, unpinned brews (with existing and any appended install options).

If formula are given, upgrade only the specified brews (unless they
are pinned; see pin, unpin).

    -d, --debug                      If brewing fails, open an interactive
                                     debugging session with access to IRB or a
                                     shell inside the temporary build directory
    -s, --build-from-source          Compile formula from source even if a
                                     bottle is available.
        --force-bottle               Install from a bottle if it exists for the
                                     current or newest version of macOS, even if
                                     it would not normally be used for
                                     installation.
        --fetch-HEAD                 Fetch the upstream repository to detect if
                                     the HEAD installation of the formula is
                                     outdated. Otherwise, the repository's HEAD
                                     will be checked for updates when a new
                                     stable or development version has been
                                     released.
        --ignore-pinned              Set a 0 exit code even if pinned formulae
                                     are not upgraded.
        --keep-tmp                   Don't delete the temporary files created
                                     during installation.
    -f, --force                      Install without checking for previously
                                     installed keg-only or non-migrated
                                     versions.
    -v, --verbose                    Print the verification and postinstall
                                     steps.
        --display-times              Print install times for each formula at the
                                     end of the run.
    -h, --help                       Show this message.
```

```
$ brew reinstall --help
Usage: brew reinstall [options] formula

Uninstall and then install formula (with existing and any appended install options).

    -d, --debug                      If brewing fails, open an interactive
                                     debugging session with access to IRB or a
                                     shell inside the temporary build directory
    -s, --build-from-source          Compile formula from source even if a
                                     bottle is available.
        --force-bottle               Install from a bottle if it exists for the
                                     current or newest version of macOS, even if
                                     it would not normally be used for
                                     installation.
        --keep-tmp                   Don't delete the temporary files created
                                     during installation.
    -f, --force                      Install without checking for previously
                                     installed keg-only or non-migrated
                                     versions.
    -v, --verbose                    Print the verification and postinstall
                                     steps.
        --display-times              Print install times for each formula at the
                                     end of the run.
    -h, --help                       Show this message.
```

A mention of cleanup and version removal, and ideally a `--no-cleanup` option would be great.

**Comment by MikeMcQuaid** [comment]
I’m sorry for the inconvenience. This was mentioned on our Twitter, 1.9.0 release notes on our blog, issue tracker and manpage.

**Comment by sj26** [comment]
The man page does not say that upgrade or reinstall will remove old versions:

```
   upgrade [options] formula
       Upgrade  outdated,  unpinned  brews  (with  existing  and  any appended
       install options).

       If formula are given, upgrade only the specified brews (unless they are
       pinned; see pin, unpin).

       -s, --build-from-source
              Compile formula from source even if a bottle is available.

       --force-bottle
              Install  from  a  bottle  if it exists for the current or newest
              version of macOS, even if it would  not  normally  be  used  for
              installation.

       --fetch-HEAD
              Fetch the upstream repository to detect if the HEAD installation
              of the formula is outdated.  Otherwise,  the  repository's  HEAD
              will  be  checked  for  updates when a new stable or development
              version has been released.

       --ignore-pinned
              Set a 0 exit code even if pinned formulae are not upgraded.

       --keep-tmp
              Don't delete the temporary files created during installation.

       --display-times
              Print install times for each formula at the end of the run.
```

```
   reinstall [options] formula
       Uninstall  and  then  install  formula  (with existing and any appended
       install options).

       -s, --build-from-source
              Compile formula from source even if a bottle is available.

       --force-bottle
              Install from a bottle if it exists for  the  current  or  newest
              version  of  macOS,  even  if  it would not normally be used for
              installation.

       --keep-tmp
              Don't delete the temporary files created during installation.

       --display-times
              Print install times for each formula at the end of the run.
```

**Comment by sj26** [comment]
Given homebrew automatically updates it itself when issued install/upgrade/reinstall commands this creates a significant change in behaviour in a minor release, which is *very* surprising.

**Comment by sj26** [comment]
`brew update` should print a notice about such significant behaviour changes at least, and the man pages and help output for these commands should mention that they also remove old versions./

**Comment by MikeMcQuaid** [comment]
> The man page does not say that upgrade or reinstall will remove old versions

It did but only under the `HOMEBREW_NOT_INSTALL_CLEANUP` variable. This has instead been documented more fully in https://github.com/Homebrew/brew/pull/5658.

> apologies, I see this was in homebrew 2.0.

No worries, you're welcome.

**Comment by sj26** [comment]
Thanks for the speedy response @MikeMcQuaid, and congrats on the 2.0!

**Comment by Char-Aznable** [comment]
I have got the same issue here and I have to rebuild a bunch of tools in older versions for my projects. I would suggest disable the auto cleanup by default or allow a transition period for the users to adapt to it.  Disk space is cheap and cron jobs are cheaper and I don't see why automating cleanup really helps.

**Comment by vitorgalvao** [comment]
@Char-Aznable There was a transition period. `1.9.0` warned this behaviour was going to be the default in `2.0.0`.

> Disk space is cheap and cron jobs are cheaper and I don't see why automating cleanup really helps.

This change was made because for the majority of users, it is beneficial. Most didn’t know about `cleanup`, so they didn’t have the chance to `cron` (which should really be `launchd`) and didn’t know how much space was being taken up until they found out about the command.

This matter has been discussed *ad nauseam*. The decision has been made, and is the right one for the majority of users. I the future, if you want to catch the discussions where these decisions are made, I suggest you follow one (or more) of the channels where they are communicated, such as the Twitter account, Github repo, or Blog.

**Comment by Char-Aznable** [comment]
> This matter has been discussed _ad nauseam_. The decision has been made, and is the right one for the majority of users

@vitorgalvao Just out of curiosity, did the discussion of turning this on involve the majority of the users? Do you have any data to support the claim? On the contrary, I have seen quite a few of related issues complaining about this feature. The fact that @sj26 and I had to dig up the env variable from the source code to know how to disable it means that your transition period doesn't really help warning the users. Your suggestion of relying on social media to catch such surprising behavior seems quite impractical too -- yeah, now I really need to follow the twitter to prevent the software from making important decision for me

**Comment by MikeMcQuaid** [comment]
> Just out of curiosity, did the discussion of turning this on involve the majority of the users?

No.

> Do you have any data to support the claim?

Yes.

> On the contrary, I have seen quite a few of related issues complaining about this feature.

And I have seen quite a few comments and heard people in person at conferences saying "hooray for this feature".

> The fact that @sj26 and I had to dig up the env variable from the source code to know how to disable it means that your transition period doesn't really help warning the users.

It helps warn the users who read the release notes or our Twitter or the manpage. It's now displayed more prominently in the manage.

> I really need to follow the twitter to prevent the software from making important decision for me

Social media or our release notes on our blog if you wish to avoid being caught unaware by deprecations and breaking changes: yes. 

> Disk space is cheap and cron jobs are cheaper and I don't see why automating cleanup really helps.

People shouldn't have to learn that `brew cleanup` exists to have Homebrew not (literally) increase space until it fills their disk. 

---

I'm 99.9% sure you found other, locked issues and decided to comment on this one because the others are locked. Hint for future reference: unless you have an _actual bug report_ then our issue tracker is not a place for you to just vent about things you don't like.
