### ISSUE TITLE
HB2, can't initialize empty git repository

### ISSUE THREAD

**Issue by blogabe** [Homebrew/brew#5657]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

`brew update` a new homebrew installation

# What happened (include command output)

```
$ brew update
Initialized empty Git repository in /Users/abe/local/src/homebrew/xpfx-hb2/.git/
fatal: The remote end hung up unexpectedly
```

<details>
  <summary>Command output</summary>
  <pre>
  
  
  
  </pre>
</details>

# What you expected to happen

Init .git folder

# Step-by-step reproduction instructions (by running `brew` commands)

```
mkdir homebrew
curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
brew update
```

**Comment by blogabe** [comment]
Thanks @reitermarkus but wouldn't that merge have resolved my issue?  Or are you saying that's the merge that caused the issue?  Merge happened 5+ hours ago, and my issue within past hour.

**Comment by blogabe** [comment]
Hi Mike.  It's already set to 1

**Comment by MikeMcQuaid** [comment]
@blogabe Can you still reproduce this? It seems like it was an intermittent GitHub issue.

**Comment by blogabe** [comment]
@MikeMcQuaid Confirmed.  All good now.  Will close this out.
