### ISSUE TITLE
`brew cleanup` frequency controlled via config option

### ISSUE THREAD

**Issue by vraravam** [Homebrew/brew#5662]
# A detailed description of the proposed feature

Its great the there's the environment variable to handle the "no cleanup" option. But, what I like to do is to actively cleanup caches, etc that `brew` leaves behind. To make this happen, I have been running a command via `cron`, but, I see that you have implemented the cleanup to happen every 30 days. Instead of hardcoding the "30", can you please expose it via a user-definable configuration?

# The motivation for the feature

Users should be able to control how frequently they would want the cleanup to happen

# How the feature would be relevant to at least 90% of Homebrew users

For those on Macs, the 256 GB SSD seems to fill very quickly, and cleaning up the caches would save a lot of disk space.

# What alternatives to the feature have been considered

Cron job running `brew cleanup prune` every day.

**Comment by MikeMcQuaid** [comment]
`brew cleanup` is run in full every 30 days but is run for each individual formula on an install/upgrade/reinstall. You can still continue if desired to run your command with cron if you wish it to be run more often. We will consider adding an option in future to adjust the time period if we get more requests. Thanks!
