### ISSUE TITLE
Error: Calling 'brew upgrade --cleanup' is disabled! There is no replacement.

### ISSUE THREAD

**Issue by grosch** [Homebrew/brew#5664]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

brew upgrade --cleanup

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
  
Error: Calling 'brew upgrade --cleanup' is disabled! There is no replacement.
  
  </pre>
</details>

# What you expected to happen

Used to always do the full upgrade and then remove stuff no longer necessary

# Step-by-step reproduction instructions (by running `brew` commands)

% /usr/local/bin/brew upgrade --cleanup
Error: Calling 'brew upgrade --cleanup' is disabled! There is no replacement.
[griffon:operations/projects/final] scott% % brew config
HOMEBREW_VERSION: 2.0.0-6-g8df3d20
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8df3d20f5ed6d954e8665fd4c7c83dc03bbd1fcf
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d59f3fdfca26f58df5456172d810646de427e538
Core tap last commit: 4 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /Users/scott/Library/Logs/Homebrew
CPU: dodeca-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_131
macOS: 10.14.2-x86_64
CLT: N/A
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
% brew doctor
Your system is ready to brew.

**Comment by MikeMcQuaid** [comment]
`brew upgrade --cleanup` is now the default behaviour.

**Comment by grosch** [comment]
Thanks.  I think it would make much more sense if the message said that, instead of what basically looks like an error condition.

**Comment by grosch** [comment]
@MikeMcQuaid What you said isn't the behavior I'm seeing.  I ran `brew upgrade` by itself.  Then to check I immediately ran `brew cleanup` and it went through and removed a bunch of stuff.

**Comment by MikeMcQuaid** [comment]
It printed out a deprecation message previously and we note in the manpage and release notes. That is what the cleanup flag did too so it is as I described although perhaps not what you wanted.

**Comment by grosch** [comment]
I’m confused. When run with the cleanup flag previously it both upgraded and did the removal. Now I have to run it as two separate commands.

**Comment by MikeMcQuaid** [comment]
You do not in Homebrew 2.0.0. `--cleanup` is now the default behaviour unless you set `HOMEBREW_NO_INSTALL_CLEANUP`. It never ran a full `brew cleanup` which means running `brew cleanup` could have still had stuff to clean up.
