### ISSUE TITLE
"java-beta" cask breaks brew's java dependencies

### ISSUE THREAD

**Issue by gcbartlett** [Homebrew/brew#5671]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

With the `java-beta` cask installed, dependencies on `java` fail even when the correct java installations are present (e.g. installing/upgrading `tomcat` fails).  This appears similar to issue #2405, except that in this case the output to `java -version` has no `'.'` character, so I suspect this causes problems for brew's regexp (see below):
```
$ brew cask install java-beta
==> Satisfying dependencies
==> Downloading https://download.java.net/java/early_access/jdk12/30/GPL/openjdk-12-ea+30_osx-x64_bin.tar.gz
Already downloaded: /Users/garybartlett/Library/Caches/Homebrew/downloads/1baf871f2fd7e0eb7836531d05029647d13ec5afebf1cc43c09d98833f1e26c2--openjdk-12-ea 30_osx-x64_bin.tar.gz
==> Verifying SHA-256 checksum for Cask 'java-beta'.
==> Installing Cask java-beta
🍺  java-beta was successfully installed!

$ brew config
HOMEBREW_VERSION: 2.0.0-16-g81b6623
ORIGIN: https://github.com/Homebrew/brew
HEAD: 81b6623774089c5eaff9eb52066d46717e56f286
Last commit: 74 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 385c946a4ad879cde422d33b84fdbcccb2b7d5bd
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /Users/garybartlett/Library/Logs/Homebrew
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_VISUAL: vi
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12, 11.0.2, 10.0.2, 9.0.4, 1.8.0_202, 1.7.0_80
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1

$ brew info tomcat
tomcat: stable 9.0.14
Implementation of Java Servlet and JavaServer Pages
https://tomcat.apache.org/
/usr/local/Cellar/tomcat/9.0.14 (711 files, 25MB) *
  Built from source on 2018-12-15 at 06:21:53
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tomcat.rb
==> Requirements
Required: java >= 1.8 ✘
==> Caveats
To have launchd start tomcat now and restart at login:
  brew services start tomcat
Or, if you don't want/need a background service you can just run:
  catalina run
==> Analytics
install: 4,225 (30 days), 16,111 (90 days), 74,384 (365 days)
install_on_request: 3,756 (30 days), 13,808 (90 days), 60,558 (365 days)
build_error: 0 (30 days)

$ /usr/libexec/java_home --failfast --version 1.8+
/Library/Java/JavaVirtualMachines/openjdk-12.jdk/Contents/Home

$ /Library/Java/JavaVirtualMachines/openjdk-12.jdk/Contents/Home/bin/java -version
openjdk version "12-ea" 2019-03-19
OpenJDK Runtime Environment (build 12-ea+30)
OpenJDK 64-Bit Server VM (build 12-ea+30, mixed mode, sharing)
```

Uninstalling `java-beta` returns brew to a functioning state:
```
$ brew cask remove java-beta
==> Uninstalling Cask java-beta
==> Running uninstall process for java-beta; your password may be necessary
==> Removing files:
/Library/Java/JavaVirtualMachines/openjdk-12.jdk
==> Purging files for version 12,30 of Cask java-beta

$ brew info tomcat
tomcat: stable 9.0.14
Implementation of Java Servlet and JavaServer Pages
https://tomcat.apache.org/
/usr/local/Cellar/tomcat/9.0.14 (711 files, 25MB) *
  Built from source on 2018-12-15 at 06:21:53
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tomcat.rb
==> Requirements
Required: java >= 1.8 ✔
==> Caveats
To have launchd start tomcat now and restart at login:
  brew services start tomcat
Or, if you don't want/need a background service you can just run:
  catalina run
==> Analytics
install: 4,225 (30 days), 16,111 (90 days), 74,384 (365 days)
install_on_request: 3,756 (30 days), 13,808 (90 days), 60,558 (365 days)
build_error: 0 (30 days)
```

**Comment by colindean** [comment]
It does seem that there is an assumption that the Java version will have a period in it:

https://github.com/Homebrew/brew/blob/be02faff4b405d8ac26911d7b4289081021372fe/Library/Homebrew/requirements/java_requirement.rb#L132

**Comment by gcbartlett** [comment]
Maybe something like `/\d+(\.\d)?/` would work.

**Comment by MikeMcQuaid** [comment]
Could someone submit a pull request to adjust this? Thanks!

**Comment by hannahmendez** [comment]
Hello, I'm new here :)

I propose using this regex expression instead:
(\d+\.)?(\d+\.)?(\*|\d+)$

which will cover any version number up to three fields (e.g. 12, 1.23, 1.2.4) 

i can submit a PR for this

**Comment by gcbartlett** [comment]
> I propose using this regex instead:
> (\d+.)?(\d+.)?(*|\d+)$
> 
> which will cover any version number up to three fields (e.g. 12, 1.23, 1.2.4)

That regex doesn't look right to me (but I don't know what ruby uses for regex).  Doesn't your `.` match **any** character, not just a literal `.`?  And the `$` will anchor the regex to the end of the line, instead of finding the first version number inside the `java -version` output.  And I though the original was only interested in the first two components.

**Comment by MikeMcQuaid** [comment]
@gcbartlett I'm a bit frustrated that you have time to critique the regexes of others but not to create a PR yourself. The person whose regex you disagreed with was a first time contributor who has since closed their PR and deleted their comment here. I'm sure that was not your intention but please be aware of such things in future, thanks.

**Comment by gcbartlett** [comment]
@MikeMcQuaid, no, of course it wasn't my intention to offend anyone (sorry @hannahmendez if you were).  My only reason for replying about the regex was to open up discussion about it and to ensure that the right regex was committed, or for someone to educate me about why my original suggestion wouldn't work and the newly proposed one would.
I am not familiar with ruby and have no experience building and debugging homebrew either, so did not feel comfortable generating and testing a PR myself.  I am more than happy to continue this discussion, or help Hannah or anyone else test any solution to this issue.

**Comment by gcbartlett** [comment]
I can submit a PR for my change: https://github.com/gcbartlett/brew/commit/ff5dddab9935f304ba73fadcf42170c13c88c59b, but am unable to run `brew tests` (I see lots of errors including "Gem::Ext::BuildError: ERROR: Failed to build gem native extension.").

**Comment by MikeMcQuaid** [comment]
@gcbartlett Please do, thanks.

**Comment by gcbartlett** [comment]
PR: https://github.com/Homebrew/brew/pull/5682

**Comment by MikeMcQuaid** [comment]
Also, now I'm not on my phone, thanks for both the apology and the PR @gcbartlett, we greatly appreciate both.
