### ISSUE TITLE
Brew is removing old versions during upgrade!

### ISSUE THREAD

**Issue by At0micMac** [Homebrew/brew#5675]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)
Ran `brew upgrade` and it's automatically removing old versions!

# What happened (include command output)
(I couldn't add the entire output, as it's too long)
<details>
  <summary>Command output</summary>
  <pre>
  
 ```
==> Upgrading 13 outdated packages:
coreutils 8.30_1 -> 8.30_2, ffmpeg 4.1_2 -> 4.1_4, gtk+3 3.24.4 -> 3.24.5, cmake 3.13.3 -> 3.13.4, binutils 2.31.1_2 -> 2.32, wine 3.0.4 -> 4.0, libgpg-error 1.34 -> 1.35, unrar 5.6.8 -> 5.7.1, swiftformat 0.37.5 -> 0.38.0, youtube-dl 2019.01.24 -> 2019.01.30.1, node 11.8.0 -> 11.9.0, imagemagick 7.0.8-24 -> 7.0.8-25, gnutls 3.6.5 -> 3.6.6
...output truncated...
==> Summary
🍺  /usr/local/Cellar/gnutls/3.6.6: 1,200 files, 8.9MB
Removing: /usr/local/Cellar/gnutls/3.6.5... (1,195 files, 8.9MB)
==> Caveats
==> binutils
binutils is keg-only, which means it was not symlinked into /usr/local,
because because Apple provides the same tools and binutils is poorly supported on macOS.

If you need to have binutils first in your PATH run:
  echo 'export PATH="/usr/local/opt/binutils/bin:$PATH"' >> ~/.bash_profile

For compilers to find binutils you may need to set:
  export LDFLAGS="-L/usr/local/opt/binutils/lib"
  export CPPFLAGS="-I/usr/local/opt/binutils/include"

==> cmake
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> wine
You may also want winetricks:
  brew install winetricks
==> youtube-dl
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> node
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> coreutils
Commands also provided by macOS have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```
  
  </pre>
</details>

# What you expected to happen

I expect brew to keep old versions until I explicitly tell it to remove them.

# Step-by-step reproduction instructions (by running `brew` commands)

1. Update Brew
2. Upgrade Brew
3. Old versions are missing!

**Comment by MikeMcQuaid** [comment]
Thanks @rhannekan. Yes that’s correct.

**Comment by bdashrad** [comment]
This broke the workflow for a large number of developers. If you're going to introduce a breaking change like this, I'd expect more notification from the tool itself, since it also auto updates. I know I personally don't follow your twitter or watch the github for every change, and I'm sure I'm not the only one.

**Comment by vitorgalvao** [comment]
@bdashrad For the vast majority of users this is a positive change, which is why it was introduced. Apologies for the trouble, but every change has tradeoffs, and we try to communicate them in several channels.

I recommend [the blog](https://brew.sh/blog/), since it highlights the most important bits and the posts are short, to the point, and sporadic.

**Comment by MikeMcQuaid** [comment]
@bdashrad Actually finally: don't go 👎 the comments of helpful people like @rhanneken who decided to come to our issue tracker and help others rather than just complain.
