### ISSUE TITLE
Suggested command from check_access_directories isn’t fish compatible

### ISSUE THREAD

**Issue by robinwhittleton** [Homebrew/brew#5680]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I ran `brew upgrade`.

# What happened (include command output)

received the error message from [`check_access_directories`](https://github.com/Homebrew/brew/blob/5eaf4e5c28e7605cd9d8e1631d376b0e46c98624/Library/Homebrew/diagnostic.rb#L328).

<details>
  <summary>Command output</summary>
  <pre>
  
Error: The following directories are not writable by your user:
/usr/local/bin
/usr/local/etc
/usr/local/sbin

You should change the ownership of these directories to your user.
  sudo chown -R $(whoami) /usr/local/bin /usr/local/etc /usr/local/sbin
  
  </pre>
</details>

# What you expected to happen

The suggest command to run should work in my fish shell.

# Step-by-step reproduction instructions (by running `brew` commands)

1. Use fish shell.
2. Change the ownership of /usr/local/sbin to a different user.
3. Run `brew upgrade`.
4. Try to run the suggested command.

# Suggested fix

Fish doesn’t use the syntax `$(whoami)`, it wants bare parentheses like `(whoami)`. It seems reasonable to add this line to shells.rb with a switch statement that checks for fish and provides a working command for that environment.

I’m happy to try a PR for this if it’s wanted.

**Comment by MikeMcQuaid** [comment]
The Homebrew install instructions also aren't Fish compatible. Fish doesn't ship with macOS and if you're using a custom shell we assume you have sufficient knowledge to convert the instructions or change back your shell. We're not interested in a switch statement as it will make the code clearer for the majority use-case (as POSIX compatible shell).
