### ISSUE TITLE
Prompt to uninstall forumuae upon upgrade

### ISSUE THREAD

**Issue by jhabdas** [Homebrew/brew#5687]
# A detailed description of the proposed feature

The current behavior of `brew install upgrade <formulae>` is to remove all other installed versions. If a package has previously been installed using `brew install <formulae>@tag` then `brew upgrade` should not remove those.

# The motivation for the feature

I'm no longer able to back down to `hugo@0.44` or reinstall it using `brew install` and the current version feels slower perceptually during the development workflow. I'm unable to debug. I also have `0.44` signified as the minimum required version for a design system I need to be able to quickly toggle back and forth between versions of this pre-1.0.0 software.

# How the feature would be relevant to at least 90% of Homebrew users

Whatever happened to Pareto?

# What alternatives to the feature have been considered

I could stop using using Homebrew and run the Docker container I created to build from source.

**Comment by jhabdas** [comment]
```
docs master* ❯ brew upgrade hugo
==> Upgrading 1 outdated package:
hugo 0.44 -> 0.54.0
==> Upgrading hugo 
==> Downloading https://homebrew.bintray.com/bottles/hugo-0.54.0.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring hugo-0.54.0.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/hugo/0.54.0: 31 files, 38.0MB
Removing: /usr/local/Cellar/hugo/0.40.1... (32 files, 28.2MB)
Removing: /usr/local/Cellar/hugo/0.40.2... (32 files, 28.2MB)
Removing: /usr/local/Cellar/hugo/0.42.1... (32 files, 28.3MB)
Removing: /usr/local/Cellar/hugo/0.44... (32 files, 54.6MB)
Removing: /usr/local/Cellar/hugo/0.46... (32 files, 54.9MB)
Removing: /usr/local/Cellar/hugo/0.53... (31 files, 37.9MB)
```

**Comment by MikeMcQuaid** [comment]
> I'm no longer able to back down to `hugo@0.44` or reinstall it using `brew install` and the current version feels slower perceptually during the development workflow.

We do not support installing older versions. You can use `brew extract` to add it to your own tap.

> Whatever happened to Pareto?

That's not a design principle we're adopting. Please fill out the template in future.

> I could stop using using Homebrew

Again, this is not helpful language. It makes no difference to us whether you choose to use Homebrew or not: use whatever is best for you.

You may be interested in the `HOMEBREW_NO_INSTALL_CLEANUP` variable. Please ensure you read `man brew` in future before creating issues, thanks.

**Comment by jhabdas** [comment]
A simple no would've sufficed, @MikeMcQuaid. But based on your response I feel you didn't take my request to heart. This is obviously a valuable feature as the knee-jerk reaction when someone does a `tldr brew` and can't figure out how to do simple things is to run `brew upgrade`.

**Comment by jhabdas** [comment]
> You may be interested in the `HOMEBREW_NO_INSTALL_CLEANUP` variable. Please ensure you read `man brew` in future before creating issues, thanks.

This could indeed be helpful. But I would expect 99.7 percent of developers don't want dependencies they expressly installed removed without a simple prompt for cleanup.

**Comment by jhabdas** [comment]
> You may be interested in the `HOMEBREW_NO_INSTALL_CLEANUP` variable. Please ensure you read `man brew` in future before creating issues, thanks.

This could indeed be helpful. But I would expect 99.7 percent of developers don't want dependencies they expressly installed removed without a simple prompt for cleanup *especially* if Homebrew can't maintain historical packages and doesn't afford its users a method of recovery.

**Comment by jhabdas** [comment]
> You may be interested in the `HOMEBREW_NO_INSTALL_CLEANUP` variable.

This could indeed be helpful. But I would expect 99.7 percent of developers don't want dependencies they expressly installed removed without a simple prompt for cleanup *especially* if Homebrew can't maintain historical packages and doesn't afford its users a method of recovery.

P.s. Please work on your soft skills.

**Comment by iMichka** [comment]
Please be nice with the maintainers, which work on this project on their free time. We all do our best. Watch your tone. Thanks!
