### ISSUE TITLE
How to Install Deleted Formulas After a Brew Upgrade

### ISSUE THREAD

**Issue by jhabdas** [Homebrew/brew#5688]
I didn't see any instructions on how to install formulae deleted during `brew upgrade formula` in the FAQ and maintainers [seem intent](https://github.com/Homebrew/brew/issues/5687) at pointing others to the `man` page I thought I'd do the honors of simplifying what 1854 people [have upvoted](https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula) on SO:

```sh
FORMULA=hugo && \
COMMIT=2aedd26426 && \
RAW_PATH=https://raw.githubusercontent.com/Homebrew/homebrew-core && \
brew unlink ${FORMULA} && \
brew install ${RAW_PATH}/${COMMIT}/Formula/${FORMULA}.rb
```

Where `hugo` is the name of your formula and `2aedd26426` is the commit hash of the version you want to install based on commit history in [`homebrew-core`](https://github.com/Homebrew/homebrew-core).

**Comment by MikeMcQuaid** [comment]
@jhabdas Please do not:

- create issues and immediately close them
- create issues to continue discussion of locked issues
- ignore our issue template
- post with a snarky tone

or you will find yourself blocked from creating issues in future.

Note that your approach above will fail over time as formulae DSL are deprecated, build fixes are needed and URLs no longer resolve. That is why I mentioned using `brew extract` before in your previous issue: did you try using that?
