### ISSUE TITLE
Use Rubocop for some `brew audit`s

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#569]
We should investigate using Rubocop for some (maybe all) `brew audit`s rather than just regex as Rubocop can actually parse Ruby.

**Comment by maxnordlund** [comment]
I might be able to take a stab at this, seems doable. But I would like some pointers though. May I please have some? (Also maybe you could ping the right persons @MikeMcQuaid)

**Comment by jawshooah** [comment]
Take a look at [rubocop-cask](https://github.com/caskroom/rubocop-cask) as an example of custom cops and parsing logic.

**Comment by maxnordlund** [comment]
Nice, will do 👍 . But should I then point a PR to that repo or put inside here somewhere (and then what is a good place)?

**Comment by maxnordlund** [comment]
Or make a new repo, but that seems like overkill.

**Comment by MikeMcQuaid** [comment]
@maxnordlund That would be so great! I agree that probably having it inside this repo would be ideal, if that's possible (similarly maybe with rubocop-cask one day). @jawshooah any thoughts on why you made it a separate repo to avoid hitting any issues you may have hit?

Regardless, I wouldn't worry too much about location or even completeness for now; I'd pick a single rule from `brew audit` that looks like a good candidate for Rubocop and try and get the flow working end-to-end and then we can look at porting other rules across.

**Comment by maxnordlund** [comment]
Sounds like a plan, I'll make a new repo and steal/borrow the cask rubocop structure and do as you say and implement a single rule. We can always move the code around if needed I guess.

**Comment by MikeMcQuaid** [comment]
A suggestion for an easy single rule that requires understanding Ruby more than `audit` really can currently: `revision` in a `bottle do` block should be renamed to `rebuild` and Rubocop should autocorrect it to `rebuild`.

**Comment by maxnordlund** [comment]
I haven't been able to get this rolling because a lot of stuff have cropped up at work. I still will try to do this, but it may take quite some time.

**Comment by MikeMcQuaid** [comment]
@maxnordlund No worries or rush.

**Comment by GauthamGoli** [comment]
@MikeMcQuaid I could work on implementing this feature. I implemented a basic cop that you mentioned above https://github.com/GauthamGoli/rubocop-brew

> `revision` in a `bottle do` block should be renamed to `rebuild` and Rubocop should autocorrect it to `rebuild`

I tested it on a formula and its working fine. Here is the link to the code. I'm still trying to understand how to write custom cops, and also am a ruby novice.

Command to run the custom cop 
`$rubocop --require /absolute/path/to/custom_cop.rb --only CustomCops/CorrectBottleBlock --auto-correct /path/to/test/formula.rb`

**Comment by MikeMcQuaid** [comment]
@GauthamGoli That looks like a great start, nice work! Next step and I'd consider this done would be to submit a PR to add `bottle_block_cop.rb` to Homebrew somewhere so it can be run without needing manual arguments. @jawshooah may have input on how to (or how best to) do this such that it'll also work for people running `rubocop` locally without configuration (that's my end goal/dream).

**Comment by GauthamGoli** [comment]
@MikeMcQuaid We can place `bottle_block_cop.rb` (and other custom cops) in a directory, I used `Library/Homebrew/cops/` and then used the `require` directive in `.rubocop.yml` file to specify them. Without further configuration, the custom cop was getting executed locally and detecting violations when `--strict` argument is passed to `brew audit`. There is one final issue though, `--strict` just checks for cop violations, but for autocorrecting the code, may be a new option should be added to `brew audit`, let's say `--fix` may be ?

**Comment by MikeMcQuaid** [comment]
> I used Library/Homebrew/cops/ and then used the require directive in .rubocop.yml file to specify them.

Nice! I think `Library/Homebrew/rubocops/` would be best.


> There is one final issue though, --strict just checks for cop violations, but for autocorrecting the code, may be a new option should be added to brew audit, let's say --fix may be ?

Yeh, that works. It's already there on `brew style`: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/style.rb#L8-L9

**Comment by GauthamGoli** [comment]
@MikeMcQuaid Can porting audit rules to use Rubo Cop be a GSoC project?

**Comment by MikeMcQuaid** [comment]
@GauthamGoli Yep, that seems like a good one 👍

**Comment by MikeMcQuaid** [comment]
Going to consider this basically done at this point. Great work again, @GauthamGoli and hope that you'll keep doing some bits on this!
