### ISSUE TITLE
Proposal: Formula#plist stanza update to enable ability to specify a Ruby {hash} instead of raw <xml>

### ISSUE THREAD

**Issue by danielbayley** [Homebrew/brew#5691]
# A detailed description of the proposed feature

The Formula#`plist` stanza could be refactored to enable the ability to specify a Ruby `{hash}` instead of raw `<xml>`.

So this could enable something like:
~~~ rb
def plist
  {
    Label: plist_name,
    ProgramArguments: ["#{opt_bin}/example", "--do-this"],
    RunAtLoad: true,
    KeepAlive: true,
    StandardErrorPath: "/dev/null",
    StandardOutPath: "/dev/null"
  }
end
~~~
which would populate the `<dict>` (with the surrounding `<DOCTYPE plist>` etc. boilerplate taken care of behind the scenes), instead of:
~~~ rb
def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>Label</key>
          <string>#{plist_name}</string>
        <key>ProgramArguments</key>
        <array>
          <string>#{opt_bin}/example</string>
          <string>--do-this</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>StandardErrorPath</key>
        <string>/dev/null</string>
        <key>StandardOutPath</key>
        <string>/dev/null</string>
      </dict>
    </plist>
  EOS
end
~~~
🤢

# The motivation for the feature

This would be much better, and cut down on a lot of the duplicate boilerplate across many formulae.

# How the feature would be relevant to at least 90% of Homebrew users

Maybe 90% is a stretch… but the easier a formula is to create (and importantly maintain), the better for everyone…

# What alternatives to the feature have been considered

I couldn't find any related issues.

**Comment by MikeMcQuaid** [comment]
@danielbayley This is a good idea. Would you be able to open a pull request? The Homebrew maintainers are unlikely to do so.

**Comment by danielbayley** [comment]
@MikeMcQuaid Please see #5695 for my initial attempt…
