### ISSUE TITLE
Issues related to auto cleanup after install/update

### ISSUE THREAD

**Issue by Char-Aznable** [Homebrew/brew#5694]
Basically #5654 I don't know why @MikeMcQuaid locked the issue. I commented there because I was sincerely curious about whether the decision of turning automatic cleanup on is based on scientific evidence.  Now, can @MikeMcQuaid point to the data he believes that this feature is "right one for the majority of users"?

> I'm 99.9% sure you found other, locked issues and decided to comment on this one because the others are locked. Hint for future reference: unless you have an _actual bug report_ then our issue tracker is not a place for you to just vent about things you don't like.

No. Please be specific if you found anything offending (and I should apology for it) because I'm simply trying to understand how things work.

**Comment by MikeMcQuaid** [comment]
I quote the issue template (which you ignored):

> Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

This is your final warning. If you open another issue without reading the issue template you will be blocked.

I and the Homebrew project do not owe you an explanation of why we lock issues or implement features. The right place to ask for clarification and satisfy your intellectual curiosity is our Discourse (if you can be polite) or anywhere else on the internet e.g. Twitter if you want to speak your mind.

**Comment by Char-Aznable** [comment]
It's not really a big deal. I didn't know about the segregation between the Issues and Discourse. Again, no trying to hold anyone responsible for the issue but I believe the users have the right to understand what the software is doing and the right to ask question. Anyway, I posted a question on discourse about the availability of the data you mentioned.
