### ISSUE TITLE
brew upgrade and Error: undefined method `b' for nil:NilClass

### ISSUE THREAD

**Issue by gyzclw** [Homebrew/brew#5698]
when i use brew upgrade , this error happened : Error: undefined method `b' for nil:NilClass.
brew config
HOMEBREW_VERSION: 2.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: e32c1515432a938093d5ef1d8c4b4408991873df
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9f62ed12d968fde9e5ab32ae27e093c506ff98a6
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/hjg/Library/Logs/Homebrew
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_60, 1.7.0_79
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11

**Comment by GauthamGoli** [comment]
Does it happen every time you run the command? If so, can you run the command again with debug option enabled (`brew upgrade -d`) and post the stack trace ?

**Comment by fxcoudert** [comment]
@gyzclw please open a new bug report and fill out the full template. In particular, we cannot do anything without information such as:

> - [ ] ran `brew update` and can still reproduce the problem?
> - [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
> - [ ] ran `brew config` and `brew doctor` and included their output with your issue?
