### ISSUE TITLE
bump-formula-pr invalid multibyte char

### ISSUE THREAD

**Issue by dmlemos** [Homebrew/brew#5701]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I wanted to bump the `vifm` formula using `bump-formula-pr`

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.1-10-g7ce517c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://github.com/vifm/vifm/releases/download/v0.10/vifm-0.10.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.1-10-g7ce517c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --fail --progress-bar --location --remote-time --continue-at 0 --output /Users/dmlemos/Library/Caches/Homebrew/Formula/vifm-0.10.tar.bz2 https://github.com/vifm/vifm/releases/download/v0.10/vifm-0.10.tar.bz2
######################################################################## 100.0%
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromUrlLoader): loading /Users/dmlemos/Library/Caches/Homebrew/Formula/vifm-0.10.tar.bz2
Error: vifm-0.10.tar.bz2: /Users/dmlemos/Library/Caches/Homebrew/Formula/vifm-0.10.tar.bz2:1: invalid multibyte char (UTF-8)
/Users/dmlemos/Library/Caches/Homebrew/Formula/vifm-0.10.tar.bz2:1: syntax error, unexpected end-of-input
BZh91AY&SYc,...
           ^
/usr/local/Homebrew/Library/Homebrew/formulary.rb:28:in `rescue in load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:128:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:201:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:118:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:310:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:48:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:46:in `formulae'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:79:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
  </pre>
</details>

# What you expected to happen

Updated formula with new URL and sha256.

# Step-by-step reproduction instructions (by running `brew` commands)

`brew bump-formula-pr --debug --url 'https://github.com/vifm/vifm/releases/download/v0.10/vifm-0.10.tar.bz2' --sh
a256 'e05a699f58279f69467d75d8cd3d6c8d2f62806c467fd558eda45ae9590768b8' vifm`

**Comment by fxcoudert** [comment]
Options are `--url=` and `--sha256=` and expect the value after the `=`. Here, the command is interpreting your URL as a formula, which it tries to load, and that fails.

**Comment by dmlemos** [comment]
That's right! I always assume CLIs cater for both `\s` and `=`, but I was wrong. Thanks

I think the usage output should explicit mention this.

**Comment by scpeters** [comment]
This reminds me of an issue I had with `brew bottle --root-url`, which I was able to improve in #5207 by appending an `=` to the parser args definition. I just checked `bump-formula-pr.rb`, and it does already have an `=` in the flag definitions:

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L48-L51

Sure enough, I see an error message with minimal arguments and `--url`:

~~~
$ brew bump-formula-pr --url
Error: missing argument: --url
~~~

I would expect that same error message to show up if I add an additional argument without the `=`, but it doesn't:

~~~
$ brew bump-formula-pr --url https://github.com/vifm/vifm/releases/download/v0.10/vifm-0.10.tar.bz2
######################################################################## 100.0%
Error: vifm-0.10.tar.bz2: /Users/scpeters/Library/Caches/Homebrew/Formula/vifm-0.10.tar.bz2:1: invalid multibyte char (UTF-8)
/Users/scpeters/Library/Caches/Homebrew/Formula/vifm-0.10.tar.bz2:1: syntax error, unexpected end-of-input
BZh91AY&SY?c,?????????????????????????...
           ^
~~~

This seems like it could be a  bug in the `Homebrew::CLI::Parser`.

cc @GauthamGoli
