### ISSUE TITLE
Unrecognized Mach-O magic: 0x00

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#5702]
This is a bug we're currently seeing, on High Sierra only, in the testing of some PRs:

- https://github.com/Homebrew/homebrew-core/pull/36359
- https://github.com/Homebrew/homebrew-core/pull/36376
- https://github.com/Homebrew/homebrew-core/pull/36582

The error itself is:

```
        ==> Determining knot bottle rebuild...
Error: Failed changing install name in /usr/local/Cellar/knot/2.7.6/sbin/kjournalprint
  from /usr/local/Cellar/knot/2.7.6/lib/libdnssec.6.dylib
    to @@HOMEBREW_CELLAR@@/knot/2.7.6/lib/libdnssec.6.dylib
Error: Failed changing install name in /usr/local/Cellar/knot/2.7.6/bin/kdig
  from @@HOMEBREW_CELLAR@@/knot/2.7.6/lib/libdnssec.6.dylib
    to /usr/local/Cellar/knot/2.7.6/lib/libdnssec.6.dylib
Error: Unrecognized Mach-O magic: 0x00
```

which occurs during `brew bottle --verbose --json knot`. CC @woodruffw for his wizardry

**Comment by woodruffw** [comment]
Huh, that's interesting. ruby-macho should only attempt to modify files that it positively identified as valid Mach-Os before hand. I'll grab the `graphite2` bottle and see if I can root-cause it.

**Comment by woodruffw** [comment]
Both the `harfbuzz` and `graphite2` errors (potentially) indicate something badly broken further up the stack: exec format error (for `graphite2`) indicates a corrupted executable, and the `meson` failure (for `harfbuzz`) either indicates a filename with a `NULL` byte in it somewhere or a *very* badly corrupted Python interpreter.

Seeing how both errors happen in Python code and only on the High Sierra VM, some maintenance might be in order. I'll follow up on Slack.

**Comment by scpeters** [comment]
Looks like it affects the pcl build in https://github.com/Homebrew/homebrew-core/pull/35030

* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/37821/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install___pcl__1_9_1_2_high_sierra_bottle_tar_gz/

**Comment by scpeters** [comment]
That pcl failure did not recur in a subsequent build.

**Comment by fxcoudert** [comment]
Seems to be fixed for `knot` too. Closing.
