### ISSUE TITLE
RT

### ISSUE THREAD

**Issue by WandererO** [Homebrew/brew#571]
==> Installing nginx-full from homebrew/nginx
==> Downloading https://nginx.org/download/nginx-1.10.1.tar.gz
Already downloaded: /Users/wanderer_xiang/Library/Caches/Homebrew/nginx-full-1.10.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nginx-full/1.10.1 --with-http_ssl_mod
Last 15 lines from /Users/wanderer_xiang/Library/Logs/Homebrew/nginx-full/01.configure:
--http-client-body-temp-path=/usr/local/var/run/nginx/client_body_temp
--http-proxy-temp-path=/usr/local/var/run/nginx/proxy_temp
--http-fastcgi-temp-path=/usr/local/var/run/nginx/fastcgi_temp
--http-uwsgi-temp-path=/usr/local/var/run/nginx/uwsgi_temp
--http-scgi-temp-path=/usr/local/var/run/nginx/scgi_temp
--http-log-path=/usr/local/var/log/nginx/access.log
--error-log-path=/usr/local/var/log/nginx/error.log
--add-module=/usr/local/share/rtmp-nginx-module

checking for OS
 + Darwin 15.6.0 x86_64
checking for C compiler ... not found

./configure: error: C compiler clang is not found

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-nginx/issues

**Comment by DomT4** [comment]
> READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
https://github.com/Homebrew/homebrew-nginx/issues

😉
