### ISSUE TITLE
Infinite loop in upgradable_dependents

### ISSUE THREAD

**Issue by Frizlab** [Homebrew/brew#5711]
Picking up where we left off on issue #5431 which got restricted to collaborator by a bot due to a too long inactivity.

I got some time to work on it and I'm _almost sure_ I have a reproducible setup. I'm not 100% sure because my homebrew setup involves a custom prefix, but I think this report is worth a read anyway, if only because I have a potential easy fix.

Brew doctor: https://gist.github.com/Frizlab/fecb7f7abc5112e1f1ce035239ab7731
Brew config: https://gist.github.com/Frizlab/d77fdb9500f417489523ff07c20366cf

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

run `brew upgrade --build-from-source`

# What happened (include command output)

brew upgraded the packages. When everything was up-to-date it froze in an infinite loop. See command output.

<details>
  <summary>Command output</summary>
  <pre>
  
Error: stack level too deep
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:40:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:358:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:350:in `+'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:416:in `join'
/Users/frizlab/usr/homebrew/Library/Homebrew/extend/pathname.rb:264:in `resolved_path'
/Users/frizlab/usr/homebrew/Library/Homebrew/formulary.rb:171:in `initialize'
/Users/frizlab/usr/homebrew/Library/Homebrew/formulary.rb:410:in `new'
/Users/frizlab/usr/homebrew/Library/Homebrew/formulary.rb:410:in `loader_for'
/Users/frizlab/usr/homebrew/Library/Homebrew/formulary.rb:310:in `factory'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1223:in `current_installed_alias_target'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1229:in `installed_alias_target_changed?'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1219:in `new_formula_available?'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1200:in `block in _outdated_kegs'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1190:in `each'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1190:in `_outdated_kegs'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1182:in `block in outdated_kegs'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1184:in `outdated_kegs'
/Users/frizlab/usr/homebrew/Library/Homebrew/formula.rb:1263:in `outdated?'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:231:in `block (2 levels) in upgradable_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:227:in `each'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:227:in `block in upgradable_dependents'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:306:in `each'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:215:in `upgradable_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:247:in `block in upgradable_dependents'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:306:in `each'
………… lines repeated many many times …………
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:215:in `upgradable_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:247:in `block in upgradable_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:215:in `each'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:215:in `upgradable_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:329:in `check_dependents'
/Users/frizlab/usr/homebrew/Library/Homebrew/cmd/upgrade.rb:60:in `upgrade'
/Users/frizlab/usr/homebrew/Library/Homebrew/brew.rb:105:in `&lt;main>'

  
  </pre>
</details>

# What you expected to happen

No infinite loop.

# Step-by-step reproduction instructions (by running `brew` commands)

On a fresh install of homebrew (I tested on commit 7ce517cb2d882f7ad130c89de5189c7dc3971084),
- Go in the homebrew-core project and checkout 72b71edb2859437d53070bfac9dac8801e601386 (or any commit where `libidn2` is at version 2.1.0);
- Install `ffmpeg` and all its dependencies _from source_.
- Upgrade homebrew-core to c5b7c329d87f141a0198e8b0dd95cc37cb49ba3d (or any commit where `libidn2` is at a version more recent than 2.1.0);
- Then simply `brew upgrade` (again, from source).

I also tried to find the source of the problem, and it turns out (unsurprisingly) it all boils down to the `upgradable_dependents` method (in `upgrade.rb`). Calling the method with the `ffmpeg` formula for instance make it go into an infinite loop. `ffmpeg` has two “descendants,” `gpac` and `x264`, which in turn have two “descendants,” `ffmpeg` and `ffmpeg@2.8`, which have two “descendants” etc.

 I have an idea on how to fix this (simply store the list of descendants, pass it in the method, and if a descendant found is already in the list of the found ones, just skip to the next). I might be able to PR if needed, but I’d need help, especially if I have to implement tests.

**Comment by MikeMcQuaid** [comment]
> `ffmpeg` has two “descendants,” `gpac` and `x264`, which in turn have two “descendants,” `ffmpeg` and `ffmpeg@2.8`, which have two “descendants” etc.

This sounds like an infinite dependency loop for which this won't be the only problem and is no longer present. What am I missing here?

> I have an idea on how to fix this (simply store the list of descendants, pass it in the method, and if a descendant found is already in the list of the found ones, just skip to the next). I might be able to PR if needed, but I’d need help, especially if I have to implement tests.

This would be ideal. We can see if it warrants a test after the PR is created without it.
