### ISSUE TITLE
Error: protobuf: Unsupported special dependency :python3

### ISSUE THREAD

**Issue by readygo586** [Homebrew/brew#5712]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)
I try to install protobuf 3.5.1 using brew  

# What happened (include command output)
meet the following error "Error: protobuf: Unsupported special dependency :python3"

![](https://user-images.githubusercontent.com/41469645/52609177-51561680-2eb7-11e9-91a0-64fb9c15f7a9.png)

using brew doctor and brew config, the following info.
![](https://user-images.githubusercontent.com/41469645/52609447-4d76c400-2eb8-11e9-89ab-3a4cb99ec031.png)

After run brew update, this problem still exist. 

When I use "brew install protobuf", protobuf is installed successfully. 
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/41469645/52610081-93348c00-2eba-11e9-9217-3f4863712d51.png">

<details>
  <summary>Command output</summary>
  <pre>
  
  
  
  </pre>
</details>

# What you expected to happen
install protobuf 3.5.1 successfully.

# Step-by-step reproduction instructions (by running `brew` commands)

<

**Comment by scpeters** [comment]
So it looks like you checked out an old revision of `homebrew-core` in a folder outside of where the taps are normally located in `/usr/local/Homebrew/` and tried to install the locally checked out copy of the old formula? This is not supported behavior. You may ask for help on discourse, but this is not a bug in homebrew.

**Comment by readygo586** [comment]
I just use  "git clone git@github.com:Homebrew/homebrew-core.git" @ "~/go/src", as shown below.
<img width="889" alt="image" src="https://user-images.githubusercontent.com/41469645/52623711-f4268900-2ee7-11e9-8a87-61b8a59e11ea.png">

So you mean I should clone the git at /usr/local/Homebrew/?

**Comment by MikeMcQuaid** [comment]
@readygo586 You should never manually clone but instead use `brew update` to manage your Homebrew updates.
