### ISSUE TITLE
when i brew install any Formula ,undefined method `b' for nil:NilClass will happen

### ISSUE THREAD

**Issue by gyzclw** [Homebrew/brew#5713]
`brew config`

> HOMEBREW_VERSION: 2.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: e32c1515432a938093d5ef1d8c4b4408991873df
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab8c097670f76880b4e3927f013c9510860689b1
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/hjg/Library/Logs/Homebrew
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_60, 1.7.0_79
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

`brew doctor`

> Your system is ready to brew.

`brew install macvim -d`

```/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/macvim.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cscope.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lua.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb
==> Installing dependencies for macvim: cscope, lua, gdbm, openssl, sqlite, xz and python
==> Installing macvim dependency: cscope
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --location --silent --head http://7xkcej.dl1.z0.glb.clouddn.com/bottles/cscope-15.8b.mojave.bottle.tar.gz
### Error: undefined method `b' for nil:NilClass
Warning: Bottle installation failed: building from source.
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cscope.rb
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --location --silent --head https://downloads.sourceforge.net/project/cscope/cscope/15.8b/cscope-15.8b.tar.gz```

**Comment by gyzclw** [comment]
i have reinstall the brew,but it doesn't help me

**Comment by gyzclw** [comment]
git reset --hard to 1.9.3 ,it works well, when i update 2.0.0, this error happened

**Comment by MikeMcQuaid** [comment]
Can you try to run `HOMEBREW_DEVELOPER=1 brew install macvim -d` and paste the output here inside three backticks? Thanks!

**Comment by gyzclw** [comment]
> /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nginx.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pcre.rb
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --location --silent --head http://7xkcej.dl1.z0.glb.clouddn.com/bottles/nginx-1.15.8.mojave.bottle.1.tar.gz
Error: undefined method `b' for nil:NilClass
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/uri/common.rb:384:in `decode_www_form_component'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:376:in `block in resolve_url_basename_time'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:382:in `map'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:382:in `resolve_url_basename_time'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:335:in `resolved_url_and_basename'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:232:in `resolved_basename'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:216:in `cached_location'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:196:in `temporary_path'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:283:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `fetch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:947:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:287:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'

**Comment by jonchang** [comment]
`brew fetch -v cscope` shouldn't be redirecting to `clouddn.com`; is there an intercepting proxy somewhere on your network? Homebrew is attempting to parse a malformed Content-Disposition header, which as far as my knowledge goes Bintray does not send.

```console
$ /usr/bin/curl -q --show-error --user-agent Homebrew/2.0.1-29-g9084a62-dirty\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --location --silent --head https://homebrew.bintray.com/bottles/cscope-15.8b.mojave.bottle.tar.gz
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 13 Feb 2019 05:06:45 GMT
Content-Type: application/gzip
Content-Length: 182703
Connection: keep-alive
Last-Modified: Sun, 19 Aug 2018 17:24:07 GMT
Accept-Ranges: none
ETag: d13055e5d40c7b29ca273be19d611db2d9c157198bddbaf85bf6ca58323e0dc4
X-Checksum-Sha1: 18b018d4891adeea8b37ded0ad6cc2561d974611
X-Checksum-Sha2: d13055e5d40c7b29ca273be19d611db2d9c157198bddbaf85bf6ca58323e0dc4
```
