### ISSUE TITLE
Please incorporate --with-fdk-aac into ffmpeg

### ISSUE THREAD

**Issue by montagne27** [Homebrew/brew#5714]
Hello,

Your questionnable move to remove all options from Homebrew has left me without access to the "libfdk_aac" encoder for ffmpeg, which is the highest-quality AAC encoder, as [ffmpeg's own documentation](https://trac.ffmpeg.org/wiki/Encode/AAC) says here:

> Fraunhofer FDK AAC (libfdk_aac)
> This is currently the highest-quality AAC encoder available with ffmpeg.

and here:

> For AAC-LC: libfdk_aac > Native FFmpeg AAC encoder (aac).
> For HE-AAC you have one choice: libfdk_aac.

Furthermore, if I look at [the Homebrew analytics for the ffmpeg formula](https://formulae.brew.sh/formula/ffmpeg), "--with-fdk-aac" was easily one of the most commonly used options. Please incorporate "--with-fdk-aac" into ffmpeg.

**Comment by montagne27** [comment]
Hmm... Looks like this issue belongs to "homebrew-core" instead of "brew". I will move it there. Very confusing naming conventions.

**Comment by MikeMcQuaid** [comment]
Please read and always fill out the issue template which will direct you accordingly.
