### ISSUE TITLE
Integrate `brew cask install` into `brew install`

### ISSUE THREAD

**Issue by yzgyyang** [Homebrew/brew#5716]
*I did a quick search but didn't find such discussions. Sorry for the noise if it has already been discussed somewhere.*

# A detailed description of the proposed feature

Make `brew install` be able to also install casks. (Assuming there doesn't exist such cask whose name is also a brew package)

# The motivation for the feature

Currently there is inconsistency and confusion for me when installing cask apps:
- We can only use `brew search <name>` to search available casks (instead of `brew cask search` which is deprecated and integrated into `brew search`).
- We can only use `brew cask install <name>` to install cask (instead of `brew install` which comes naturally after the search).

# How the feature would be relevant to at least 90% of Homebrew users

Many users use brew cask have to use different commands for cask search and install.

# What alternatives to the feature have been considered

To maintain consistency, we can also keep `brew cask search` as an alias to `brew search --casks`.

Related:
https://github.com/Homebrew/brew/issues/4254

**Comment by jonchang** [comment]
You may also be interested in related discussion in https://github.com/Homebrew/brew/issues/5456 and a pull request in https://github.com/Homebrew/brew/pull/5538. I don't think any maintainers have plans to integrate `brew install` and `brew cask install` but pull requests similar to the one above would of course be welcome.

**Comment by MikeMcQuaid** [comment]
> Assuming there doesn't exist such cask whose name is also a brew package

There does.

We want to ensure a separation between installing casks and installing formulae as the latter from Homebrew/homebrew-core are open source software. We could consider something that required a user to manually e.g. tap Homebrew/homebrew-cask before this was possible. Happy to keep talking here but it's going to be a fairly complex ask to solve these problems.

**Comment by yzgyyang** [comment]
> We want to ensure a separation between installing casks and installing formulae as the latter from Homebrew/homebrew-core are open source software.

I agree that users should have an awareness of whether they are installing a cask or a formulae, and that is why I personally prefer keeping `brew cask install/search/info`. However, since the integrations are already happening at `brew search/info` (per #4254, #5456, #5538 mentioned above), and they are dealing with the exact same challenges that `brew install` integration will be facing, for example:

> #5538 brew 'info' will show info for cask if formula with same name does not exist

So at this point, I would vote for consistency and hope different `brew` subcommands have similar behaviors dealing with the "formulae vs cask" situation.

**Comment by MikeMcQuaid** [comment]
I think we need to pass on this I'm afraid; a `brew cask install` can do so much more than a `brew install` can do in terms of writing to places on the system that are unexpected. We also have a hard requirement from our foundation that we have a separation between installation of open source and closed source software with our default installation methods. Other commands should be integrated but `brew cask install` should remain separate.
