### ISSUE TITLE
Homebrew must be renamed

### ISSUE THREAD

**Issue by simayosi** [Homebrew/brew#5719]
# A detailed description of the proposed feature
Homebrew must be renamed "factorybrew (the single taste with no options)".

# The motivation for the feature

Homebrew is not home-brew now.
It is not what I expected from the name.  Current naming is extremely confusing.

# How the feature would be relevant to at least 90% of Homebrew users

# What alternatives to the feature have been considered

**Comment by jonchang** [comment]
The justification for removing options [has been clearly laid out](https://github.com/Homebrew/homebrew-core/issues/31510); unless you have a solution for these (e.g., options aren't tested, they're built from source, we don't have enough CI infrastructure or maintainer time), please don't open issues in bad faith.
