### ISSUE TITLE
Homebrew must be renamed

### ISSUE THREAD

**Issue by simayosi** [Homebrew/brew#5720]
# A detailed description of the proposed feature

Homebrew must be renamed "factorybrew (the single taste with no options)".

# The motivation for the feature

Homebrew is not home-brew now.
It is not what I expected from the name. Current naming is extremely confusing.

This is not an argument on removing options.
This is a strong suggestion to rename its name, because the current name does not show the current functionality.

# How the feature would be relevant to at least 90% of Homebrew users

Most new users would be confused due to the current name.

# What alternatives to the feature have been considered

**Comment by jonchang** [comment]
I asked you to not open issues in bad faith in https://github.com/Homebrew/brew/issues/5719. Either work with us productively or not at all. This does not help with solving any of the problems I or other maintainers outlined.
