### ISSUE TITLE
Latest brew issue, brew install freetds --with-unixodbc fails with invalid option --with-unixodbc 

### ISSUE THREAD

**Issue by raagha-b** [Homebrew/brew#5728]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ yes] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ yes] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ yes] ran `brew update` and can still reproduce the problem?
- [ yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ yes] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
  
  
  
  </pre>
</details>

# What you expected to happen

# Step-by-step reproduction instructions (by running `brew` commands)

**Comment by MikeMcQuaid** [comment]
That's because it's an invalid option because it was removed.

You also didn't fill out (or read the issue template).

**Comment by raagha-b** [comment]
I filled it but may be there was some formatting issue.
It was serving a purpose, is there a replacement for it ?

**Comment by MikeMcQuaid** [comment]
> I filled it but may be there was some formatting issue.

You did not provide the command output, `brew doctor` output, `brew config` output etc.

> It was serving a purpose, is there a replacement for it ?

No, there is not, sorry.
