### ISSUE TITLE
Error: Broken pipe when running brew search

### ISSUE THREAD

**Issue by victorhooi** [Homebrew/brew#573]
I'm running OSX 10.11.6 with Homebrew. I've just run `brew update`, so it should be up to date.

When I try to search for any packages, I get a `broken pipe` error at the end:
```
bash-3.2$ brew search csvkit
Error: Broken pipe
```
This is the output of `brew doctor`:
```
bash-3.2$ brew doctor
Your system is ready to brew.
```

Any things I should check?

**Comment by ilovezfs** [comment]
Are you behind a firewall/proxy/whatever?

**Comment by victorhooi** [comment]
Yes, I am.

Is that possibly related? Can you get detailed logs/output somewhere to
check?

On 24 Jul 2016 02:20, "ilovezfs" <notifications@github.com> wrote:

Are you behind a firewall/proxy/whatever?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Homebrew/brew/issues/573#issuecomment-234726689>, or mute
the thread

**Comment by DomT4** [comment]
@ilovezfs We've been trying to narrow this down for ages. Happened in https://github.com/Homebrew/homebrew-core/pull/2372 seemingly just because there _was_ `brew doctor` output. Doesn't seem to have a single fixed trigger, which is making it irritatingly elusive.

**Comment by MikeMcQuaid** [comment]
@victorhooi Can you try to run `brew update` and then `brew search csvkit --verbose --debug` and paste the output here? Thanks!

**Comment by victorhooi** [comment]
Sure, here is the output:

```
bash-3.2$ brew update
Updated Homebrew from 2b9a283 to 1455aa3.
Updated 4 taps (caskroom/cask, caskroom/versions, homebrew/core, neovim/neovim).
==> New Formulae
tbox
==> Updated Formulae
afl-fuzz            caddy               cfitsio             eigen               git-annex           gource              heroku              libphonenumber      libxmp-lite         logstalgia          monetdb             notmuch             opencsg             parallel            pup                 rbenv-gemset        tile38              youtube-dl ✔
antigen             casperjs            cmake ✔             fio                 glew                groovyserv          imagemagick ✔       libtiff ✔           little-cms2 ✔       mal4s               nghttp2             offlineimap         opus                poco                racket              sphinx-doc          xplanetfx
bash-3.2$ brew search csvkit --debug --verbose
Error: Broken pipe
/usr/local/Library/Homebrew/utils/github.rb:56:in `write'
/usr/local/Library/Homebrew/utils/github.rb:56:in `puts'
/usr/local/Library/Homebrew/utils/github.rb:56:in `block in api_credentials'
/usr/local/Library/Homebrew/utils/popen.rb:18:in `block in popen'
/usr/local/Library/Homebrew/utils/popen.rb:15:in `popen'
/usr/local/Library/Homebrew/utils/popen.rb:15:in `popen'
/usr/local/Library/Homebrew/utils/github.rb:55:in `api_credentials'
/usr/local/Library/Homebrew/utils/github.rb:121:in `open'
/usr/local/Library/Homebrew/cmd/search.rb:133:in `block in search_tap'
/usr/local/Library/Homebrew/cmd/search.rb:150:in `yield'
/usr/local/Library/Homebrew/cmd/search.rb:150:in `search_tap'
/usr/local/Library/Homebrew/cmd/search.rb:117:in `block (2 levels) in search_taps'
bash-3.2$
```

**Comment by UniqMartin** [comment]
That's valuable information in the backtrace; thanks! What do you get if you run the following?

```sh
git credential-osxkeychain get <<<$'protocol=https\nhost=github.com\n'
```

(If it succeeds and you have saved your credentials in the macOS Keychain, don't post the output as it will contain your GitHub password.)

And with the following?

```sh
git credential-osxkeychain
```

My guess would be that for whatever reason, the Git you're using with Homebrew (see `Git:` line in `brew config` output) lacks the `git-credential-osxkeychain` helper and we simply fail to properly handle this case in our search for credentials we can use with the GitHub API.

**Comment by UniqMartin** [comment]
Et voilà: PR #581 should hopefully fix the broken pipe error.

**Comment by victorhooi** [comment]
Hmm, interesting - the `git credential-osxkeychain` commaand definitely doesn't work here:
```
bash-3.2$ git credential-osxkeychain get <<<$'protocol=https\nhost=github.com\n'
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
bash-3.2$ git credential-osxkeychain
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
bash-3.2$
```

Here is the output of `brew config`:
```
bash-3.2$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1455aa3da6335b1eeb284e61171cff524c620fa3
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6b78abf4b09e39cb8b81880c6394a7bf02e55229
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.8.0 => /usr/local/git/current/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_91, 1.8.0_72
OS X: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A
```

Not sure if this tells you much - is there other stuff you'd want to know about this `git` binary?
```
bash-3.2$ /usr/local/git/current/bin/git --version
git version 2.8.0.rc2
```

**Comment by ilovezfs** [comment]
You could try switching to Homebrew's git and see if the problem does indeed go away.
