### ISSUE TITLE
No longer uses "--with-default-names" option

### ISSUE THREAD

**Issue by chris-hailstorm** [Homebrew/brew#5731]
# What you were trying to do (and why)

Install GNU coreutils using "normal" unix names (no "g" prefix).

# What happened (include command output)

Attempted `brew install coreutils --with-default-names`. Failed with error.

<details>
  <summary>Command output</summary>
  <pre>
  
  Error: invalid option: --with-default-names

  </pre>
</details>

# What you expected to happen

Install of utils with "normal" unix names (no "g" prefix).

This command has worked consistently with older versions of Brew.

# Step-by-step reproduction instructions (by running `brew` commands)

brew update
brew install coreutils --with-default-names

**Comment by jonchang** [comment]
Hi @chris-hailstorm, this is more properly filed in the homebrew-core repository. Regardless this option has been deprecated. The suggested replacement is in the Caveats section, which you can see by running `brew info coreutils`:

```
Commands also provided by macOS have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```
