### ISSUE TITLE
Unable to complete brew update

### ISSUE THREAD

**Issue by matteodisabatino** [Homebrew/brew#5734]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I simply wanted to update brew

# What happened (include command output)

I ran `brew update` and I received an error the says it was unable to find two repositories

<details>
  <summary>Command output</summary>
  <pre>
    remote: Repository not found.
    fatal: repository 'https://github.com/Homebrew/homebrew-completions/' not found
    remote: Repository not found.
    fatal: repository 'https://github.com/Homebrew/homebrew-gui/' not found
    Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-gui failed!
    Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-completions failed!
  </pre>
</details>

# What you expected to happen

I expected brew had completed the update

# Step-by-step reproduction instructions (by running `brew` commands)

`brew update`

# Other information

<details>
  <summary>brew doctor output</summary>
  <pre>
    Your system is ready to brew.
  </pre>
</details>

<details>
  <summary>brew config output</summary>
  <pre>
    HOMEBREW_VERSION: 2.0.1-44-g058bd4b
    ORIGIN: https://github.com/Homebrew/brew
    HEAD: 058bd4bf7c093eb753b238fb2e19ac27ff4242c8
    Last commit: 3 hours ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 8a369d7d7e59e56c034ddcda46799f4e31f19620
    Core tap last commit: 50 minutes ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_DEV_CMD_RUN: 1
    HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.agrbSDcY30/org.macosforge.xquartz:0
    HOMEBREW_LOGS: /Users/disa/Library/Logs/Homebrew
    CPU: quad-core 64-bit haswell
    Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
    Clang: 10.0 build 1000
    Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
    Curl: 7.54.0 => /usr/bin/curl
    Java: 11.0.2, 11.0.1, 1.8.0_25
    macOS: 10.14.3-x86_64
    CLT: 10.1.0.0.1.1539992718
    Xcode: 10.1
    XQuartz: 2.7.11 => /opt/X11
  </pre>
</details>

<details>
  <summary>Assurance that some repositories are unaccessible</summary>
  <pre>
    $ curl -sL -w "Status code: %{http_code}" -I https://github.com/Homebrew/brew -o /dev/null
    Status code: 200%

    $ curl -sL -w "Status code: %{http_code}" -I https://github.com/Homebrew/homebrew-core -o /dev/null
    Status code: 200%

    $ curl -sL -w "Status code: %{http_code}" -I https://github.com/Homebrew/homebrew-gui/ -o /dev/null
    Status code: 404%

    $ curl -sL -w "Status code: %{http_code}" -I https://github.com/Homebrew/homebrew-completions/ -o /dev/null
    Status code: 404%
  </pre>
</details>

**Comment by retokromer** [comment]
On my side I got:

```
$ brew update
remote: Repository not found.
fatal: repository 'https://github.com/Homebrew/homebrew-dev-tools/' not found
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dev-tools failed!
```

Hope this is useful!

**Comment by MikeMcQuaid** [comment]
@matteodisabatino @retokromer You both have tapped very old, long deprecated repositories. Please `brew untap` them and `brew update` will continue again.

**Comment by MikeMcQuaid** [comment]
Actually going to reopen this until we handle it a bit better in `brew update`.

**Comment by MikeMcQuaid** [comment]
Nothing to change here; `brew update` is completing in the case and updating everything as expected except the taps that no longer exist.

**Comment by SCdF** [comment]
Since no one has said it explicitly, as the error output doesn't contain the tap's name, you can either guess (!) or use `brew tap-info --installed`, and then match the failed URLs with the taps listed there, and _then_ pass that name to `brew untap`

**Comment by zhugejun** [comment]
I am having another issue:

`
➜  ~ brew update                
remote: Repository not found.
fatal: repository 'https://github.com/Homebrew/homebrew-x11/' not found
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-x11 failed!
`

**Comment by iMichka** [comment]
You also need to I tap the x11 repo.

**Comment by mikem** [comment]
I have slightly a slightly different error message for the `homebrew-devel-only` repo:

```
$ brew update
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-devel-only failed!
```

The "could not read Username" leads me to believe that maybe the `homebrew-devel-only` repo became private? Doesn't matter of course. I thought I'd leave this comment here for anyone else using "homebrew-devel-only" in their web searches.

Un-tapping `homebrew-devel-only` fixes the issue:

```
$ brew untap homebrew/devel-only
Untapping homebrew/devel-only...
Untapped (68 files, 36.7KB).
$ brew update
Already up-to-date.
```

**Comment by bartonfriedland** [comment]
I am getting this error again, this time with taps that do not appear to be deprecated:
`brew update
ssh: connect to host github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ssh: connect to host github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!`

**Comment by MikeMcQuaid** [comment]
@bartonfriedland This is unrelated to this issue. Please read the output you have pasted.
