### ISSUE TITLE
Show changelog for formulae and casks

### ISSUE THREAD

**Issue by danielbayley** [Homebrew/brew#5744]
See [homebrew-changelog](https://github.com/danielbayley/homebrew-changelog)

@MikeMcQuaid @jbergstroem @shamrin @telemachus

# A detailed description of the proposed feature

Following on from https://github.com/Homebrew/brew/issues/3399#issuecomment-340488771, this is an effort to introduce a `changelog` stanza into Home`brew` and `cask`.

> For this to be a thing it would need to be built like `brew desc` was: a community would need to amass these URLs for every (relevant) package in Homebrew in an external command in a third party tap and we'd consider merging it into Homebrew proper after that process is complete.

Hopefully this will follow the process of the `desc`ription stanza, and so I am hoping to raise awareness of this external command I have implemented in [this tap](https://github.com/danielbayley/homebrew-changelog):
~~~ sh
brew tap danielbayley/changelog
brew changelog #formula
brew cask changelog #cask
~~~

Contributions for `changelog` URLs are very welcome, and extremely easy to add; just a line of _YAML_ in either [`brew`.yml](https://github.com/danielbayley/homebrew-changelog/blob/master/brew.yml), or [`cask`.yml](https://github.com/danielbayley/homebrew-changelog/blob/master/cask.yml).

Related to https://github.com/Homebrew/legacy-homebrew/pull/39911.

# The motivation for the feature

Ability to quickly and easily view changelogs after formula/Cask updates.

# How the feature would be relevant to at least 90% of Homebrew users

This feature would be very useful for anyone wanting to do the same, and has been requested a few times already. See https://github.com/Homebrew/brew/issues/2935 and https://github.com/Homebrew/brew/issues/3399.

# What alternatives to the feature have been considered

The end goal is to eventually replace this external command with a `changelog` stanza.

**Comment by MikeMcQuaid** [comment]
Thanks @danielbayley! Added help wanted to this won't get closed. Are you on Twitter? If so if you've tweeted about this can you link it here and I'll RT it on the official Homebrew account. If not: do you mind if I tweet about it?

**Comment by mfriedenhagen** [comment]
Hello, having the changelog available would be great. Could you outline the required format? E.g. projects built with Apache Maven often use an XML file, there are several different almost-plain-text formats and some projects use GitHub or GitLab issues and pull or merge requests bound to milestones or collections of JIRA or Bugzilla entries. Should all of these be referenced in brew.yml?

**Comment by danielbayley** [comment]
> Are you on Twitter? If so if you've tweeted about this can you link it here and I'll RT it on the official Homebrew account. If not: do you mind if I tweet about it?

@MikeMcQuaid Sure, I just tweeted about it [here](https://twitter.com/danielbayley/status/1097521541074554882). Also just followed you.

**Comment by danielbayley** [comment]
> Hello, having the changelog available would be great. Could you outline the required format? E.g. projects built with Apache Maven often use an XML file, there are several different almost-plain-text formats and some projects use GitHub or GitLab issues and pull or merge requests bound to milestones or collections of JIRA or Bugzilla entries. Should all of these be referenced in brew.yml?

@mfriedenhagen All links are to be opened in a browser tab with `brew [cask] changelog <token>`, to be read by the user. If you look at the logic in the [`cmd/*.rb`](https://github.com/danielbayley/homebrew-changelog/tree/master/cmd) files, whatever URL you specify in the `.yml` files takes precidence… so these should preferably be the official release notes, on the vendor website, if any. After that, if the project is hosted on GitHub, then it uses the `appcast` URL (minus the `.atom` extension) to open the GitHub releases page… so if in those cases, if that is the only changelog available then it doesn't need to be mapped in the `.yml` files. But sometimes there is a `CHANGELOG.md` file or similar in the repo, which currently does need to be specified. Failing any of those, it just falls back to the `homepage`. Hope that helps.

Also, if you think this algorithm can be improved, feel free to submit a PR… 👍

**Comment by mfriedenhagen** [comment]
OK. Probably for e.g. Maven a link to https://maven.apache.org/docs/3.6.0/release-notes.html etc. would be appropriate, then. I'll prepare an PR to `brew.yml` for the different Maven taps.

**Comment by issyl0** [comment]
Is this still a project that’s ongoing? I submitted [a PR](https://github.com/danielbayley/homebrew-changelog/pull/5) in April (with a view to submitting more afterwards) but heard nothing.

**Comment by danielbayley** [comment]
Hey @issyl0, sorry I didn't notice! Just merged it… you're welcome to add more, thanks!

**Comment by MikeMcQuaid** [comment]
It looks like this has stalled with <100 formulae so passing on this for now. I still think this is a useful external command but I'm less convinced it will or should be merged in Homebrew proper. Sorry and thanks @danielbayley!
