### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by slackmage** [Homebrew/brew#575]
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
y
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
all issues
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
tried, no use

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

bash-3.2$ brew
dyld: Library not loaded
: libuuid.1.1.dylib
  Referenced from: /usr/local/bin/uuidgen
  Reason: image not found

![homebrew_bug](https://cloud.githubusercontent.com/assets/230274/17071482/beeced36-502f-11e6-9e7d-b3d1324b7677.gif)

**Comment by DomT4** [comment]
That's an interesting one. Any idea where the `uuidgen` in `/usr/local/bin` came from?

**Comment by slackmage** [comment]
Not sure exactly. I had uninstalled and reinstalled brew after noticing brew packages weren't on my path since installing zsh. That's when the error appeared.

After removing the uuidgen binary from /usr/local/bin and installing oss-uuid things appear to be working.

**Comment by ilovezfs** [comment]
Did you have MacPorts on this machine?
Did you ever install e2fsprogs?
What's `brew doctor` output?

**Comment by slackmage** [comment]
I managed to fix all brew doctor issues before ticketing.

Macports - yes ages ago before brew :)
e2fsprogs - not match on the fs currently, but I do have macfuse

**Comment by DomT4** [comment]
@xu-cheng @MikeMcQuaid Any reason we're not specifically using `$(/usr/bin/uuidgen)` [here](https://github.com/Homebrew/brew/blob/b1811f2ef3255dab74a0ee42447a5a747b37753d/Library/Homebrew/utils/analytics.sh#L42)? Feels like might be a bit more robust.

**Comment by MikeMcQuaid** [comment]
@DomT4 To provide a fall-back for non-OS X but we could definitely hard-code it for OS X.

**Comment by DomT4** [comment]
Thanks Mike! Was on my radar for tonight but I've been out all evening till about... 20 minutes ago.
