### ISSUE TITLE
Fatal error from broken boneyard git remote.

### ISSUE THREAD

**Issue by JustinTArthur** [Homebrew/brew#5750]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
  * **Is not related to formula-specific brew commands.**
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)
Update homebrew.

# What happened (include command output)
Every time I run `brew update`, I'm faced with a fatal error. See _Command output_ below.

<details>
  <summary>Command output</summary>
  <pre>
remote: Repository not found.
fatal: repository 'https://github.com/Homebrew/homebrew-boneyard/' not found
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard failed!
  </pre>
</details>

# What you expected to happen
An update of the homebrew infrastructure without error.

# Step-by-step reproduction instructions (by running `brew` commands)
```
$ brew doctor
Your system is ready to brew.
```
```
$ brew config
HOMEBREW_VERSION: 2.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: e32c1515432a938093d5ef1d8c4b4408991873df
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5ea5509e1ce88a3660c1443df08f2b7a26aefb71
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/jarthur/Library/Logs/Homebrew
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_101
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
```
```
$ brew update
remote: Repository not found.
fatal: repository 'https://github.com/Homebrew/homebrew-boneyard/' not found
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard failed!
```

**Comment by zbeekman** [comment]
Boneyard has been archived/deprecated/gone for quite some time now. Congratulations for being such a long-time homebrew user!

I'm not 100% sure that this is the best course of action, but I would try:

```
brew untap homebrew/boneyard
```

Depending on whether or not you've tapped other taps that are now deprecated, like `homebrew/science`, `homebrew/versions` etc. you may need to repeat this process. I *suspect* this should resolve the issue for you 🤞

**Comment by JustinTArthur** [comment]
That did the trick. Thanks, @zbeekman! We may want to have `brew doctor` look for any "official" taps that are deprecated or gone.

**Comment by MikeMcQuaid** [comment]
> brew untap homebrew/boneyard

This is the best course of action yes 👍.
