### ISSUE TITLE
terminal prompts disabled 

### ISSUE THREAD

**Issue by ruurd** [Homebrew/brew#5754]
# What you were trying to do (and why)

Run brew update

# What happened (include command output)

<pre>
ruurd@mcfoo 13:01:51 ~
$ brew update
fatal: could not read Username for 'https://github.com': terminal prompts disabled
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-completions failed!
</pre>

# What you expected to happen

No complaints about terminal prompts or errors fetching taps

**Comment by iMichka** [comment]
`brew untap homebrew-boneyard`
`brew untap homebrew-completions`

Please always fill out the full issue template.

**Comment by ruurd** [comment]
Are those deprecated then?

**Comment by iMichka** [comment]
Yes, sorry, I fixed my commands, the homebrew- part was not needed.

Yes, these have been deprecated since ages.

**Comment by ruurd** [comment]
I'm such a laggard :-) BTW did I ever tell you all I hugely appreciate brew?
