### ISSUE TITLE
[Feature Request] `brew cask style` check for comment removal when homepage matches URL again

### ISSUE THREAD

**Issue by 404NetworkError** [Homebrew/brew#5763]
# A detailed description of the proposed feature

As part of the requirement for a Cask, when the [download URL differs from the homepage URL](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment), a comment is required to be added. When the download URL changes back to matching the homepage URL, the comment is unnecessary and could be removed.

# The motivation for the feature

I noticed a problem in `cask-repair` (vitorgalvao/tiny-scripts#162), which has already been resolved by that maintainer, where a comment is required for Casks when the homepage URL differs from the download URL. The [maintainer suggested](https://github.com/vitorgalvao/tiny-scripts/issues/162#issuecomment-464494536) that I look into the situation where a Cask which already has differing URLs and the comment, then changes the download URL back to one which matches the homepage URL. Therefore, the comment is no longer necessary. Unfortunately, the [cop](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/rubocops/cask/homepage_matches_url.rb) currently does not check and the `style --fix` does not remove the offending comment in this situation.

# How the feature would be relevant to at least 90% of Homebrew users

This check would make sure that Cask styles are consistent in situations where the download URL differs from the homepage URL and when download URLs are reverted back to matching the homepage URL. It also sets a good example for first time and infrequent Cask contributors by showing them the required format for a Cask file.

# What alternatives to the feature have been considered

Leave the current implementation as is. This missing feature does not break fundamental `brew cask` functionality.

**Comment by MikeMcQuaid** [comment]
CC @Homebrew/cask for thoughts.

**Comment by vitorgalvao** [comment]
I encouraged this issue, so I’m for it. This is as low priority as can be, but it does make sense
