### ISSUE TITLE
brew audit --strict <formula> fail on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by Maecenas** [Homebrew/brew#5767]
- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/Maecenas/2beedc4842261cada6c02f8a0b31fc1d

# What you were trying to do (and why)

Running `brew audit --strict <formula>` when doing Homebrew/homebrew-core#37059

# What happened (include command output)

<details>
  <summary>brew audit --strict wget</summary>

```bash
$ brew audit --strict wget
Error: cannot load such file -- jaro_winkler
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.64.0/lib/rubocop/string_util.rb:3:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.64.0/lib/rubocop.rb:21:in `require_relative'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.64.0/lib/rubocop.rb:21:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/Homebrew/Library/Homebrew/style.rb:21:in `check_style_impl'
/usr/local/Homebrew/Library/Homebrew/style.rb:14:in `check_style_json'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:112:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

</details>

# What you expected to happen

This function should work

# Step-by-step reproduction instructions (by running `brew` commands)

**Comment by MikeMcQuaid** [comment]
This is an issue with your Ruby setup. `rm -rf /usr/local/Homebrew/Library/Homebrew/vendor/bundle` may fix it.
