### ISSUE TITLE
Creating bottle fails with odd error.

### ISSUE THREAD

**Issue by CamJN** [Homebrew/brew#578]
I'm working on a new tap and decided to try my hand at bottling a formula. When I ran `brew reinstall --build-bottle ~/Developer/Ruby/homebrew-core/formula/new.rb` everything seemed fine. However when I ran `brew bottle ~/Developer/Ruby/homebrew-core/formula/new.rb` I got the error `Error: Formula not from core or any taps: new`.

Any ideas?

**Comment by MikeMcQuaid** [comment]
It'll be getting confused because it's not in `Library/Taps`.

**Comment by CamJN** [comment]
Ok so I published my tap with the intention of using `brew tap` and now homebrew is prompting for my github username & password, which won't work b/c of 2FA.

**Comment by MikeMcQuaid** [comment]
> Ok so I published my tap with the intention of using brew tap and now homebrew is prompting for my github username & password

It'll only do that if it's a private repo or a 404 (i.e. you typod the name).

> github username & password, which won't work b/c of 2FA.

https://help.github.com/articles/providing-your-2fa-authentication-code/#through-the-command-line

**Comment by UniqMartin** [comment]
> Renaming my repo to have a `homebrew-` prefix fixed that, but it's annoying.

That's how tap repositories are supposed to be named and I don't think we're going to change that. One reason is that it would make accidentally cloning arbitrary repositories that are definitely not taps with `brew tap` much more likely. However, `brew help tap` would have revealed that you can arbitrarily diverge from this naming convention and even host your tap repository anywhere. This should have worked before the rename:

```console
$ brew tap CamJN/passenger-enterprise https://github.com/CamJN/passenger-enterprise
```

**Comment by CamJN** [comment]
Thanks
