### ISSUE TITLE
It seems that `cleanup` removes `/usr/local/etc/my.cnf.d`

### ISSUE THREAD

**Issue by cjf** [Homebrew/brew#5783]
This still happens:

https://github.com/Homebrew/brew/issues/2792

Discussion was closed over a year ago, but it's still happening.

**Comment by jonchang** [comment]
`brew cleanup` now runs `brew prune` which cleans out empty directories. https://github.com/Homebrew/brew/issues/2792#issuecomment-340260207 should solve the issue.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

It only removes that directory if it's empty. If it's empty and you created it manually: put a file in there. If it's empty and you didn't create it manually: reinstall the relevant formula.

**Comment by cjf** [comment]
Regarding the issue template:  
I would have happily commented on the original issue but comments were locked on a bug that didn't get fixed. Plus, I didn't think the requested information was necessary since it it literally a duplicate. 

On to the issue:
I know it removed the directory if it's empty.  I know the comment contains the fix.  That's not fixing the issue however.  `brew prune`, or `brew cleanup` if you prefer, causes a default, non-custom, working system to no longer work.  Providing the "documentation" to fixing it in github issue comments is hardly a fix.

The BUG is that `brew prune` breaks a properly installed (with no customizations) application and the fix is a hack only for those that have experienced the bug and come here to search for a fix.  

On top of that, there is not necessarily a need to have a file in that directory, nor is it recommended to put one there upon installation.  

Again, `brew prune` shouldn't break an application that is property installed without modification.

I don't believe I'm being unreasonable, but perhaps I am.  I don't frequent the GitHub repo for this project to track issues.  Is this not considered a bug?  Is this sort of thing common in dealing with various formulas?  I just don't understand why this is ignored as it seems like a fairly obvious problem.

**Comment by MikeMcQuaid** [comment]
> I would have happily commented on the original issue but comments were locked on a bug that didn't get fixed.

It did.

> I didn't think the requested information was necessary since it it literally a duplicate.

We always need the information.

> Is this not considered a bug?

Correct. It's intentional that `brew cleanup` removes empty directories from `HOMEBREW_PREFIX`.

**Comment by cjf** [comment]
> It did.

How is it that a brew command breaks a default install, and the "fix" is a comment on a github issue?  At the VERY least that should be in docs on the homebrew site.  What you have is not a fix at all.  Googling error messages and hoping someone else had the same issue is not a fix.

> It's intentional that `brew cleanup` removes empty directories from `HOMEBREW_PREFIX`.

I get that.  The problem is that is has a side effect that it breaks a properly installed package with no indication that it was the problem.  The only saving grace is that homebrew is popular enough that people have posted this issue already and google deemed it search-result-worthy, but homebrew didn't "fix" anything!  

What could a fix be?  Maybe have the package installer put a dummy file in that directory?  Have a warning on cleanup/purge that certain package are likely to break after running?

**Comment by MikeMcQuaid** [comment]
> How is it that a brew command breaks a default install, and the "fix" is a comment on a github issue?

It's not. The fix was the formula was modified and, more recently, the bottle was rebuilt.

> Maybe have the package installer put a dummy file in that directory?

It does.

**Comment by MikeMcQuaid** [comment]
> If it's empty and you didn't create it manually: reinstall the relevant formula.

@cjf Did you do this?

**Comment by cjf** [comment]
I ended up recreating the directory and putting a dummy file in it myself.
