### ISSUE TITLE
apache-flink solution outdated.

### ISSUE THREAD

**Issue by chiddekel** [Homebrew/brew#5789]
Issue automatic version detect for outdated solution - now 1.7.1 removed from server -1.7.2 available instead. Alternative can be use script for detect version and choice to change for available.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
