### ISSUE TITLE
`brew update` hangs forever when $SHELL is fish

### ISSUE THREAD

**Issue by zgracem** [Homebrew/brew#5791]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Update Homebrew from fish, my new login shell.

# What happened (include command output)

The command never finished, and output a strange message when aborted with `^C`. During the infinite wait, iTerm reported the frontmost process as `fish`. I'm used to seeing `ruby`, `git`, `bash`, or `sh` most of the time when Homebrew is running.

<details>
  <summary>Command output</summary>
  <pre>
~ ¶ brew update --verbose
Checking if we need to fetch /usr/local/Homebrew...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/bramstein/homebrew-webfonttools...
Fetching /usr/local/Homebrew...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/sass/homebrew-sass...
<kbd>\^C</kbd>
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fish:
SSH-2.0-OpenSSH_7.9
^
  </pre>
</details>

<details>
  <summary>brew config</summary>
  <pre>
HOMEBREW_VERSION: 2.0.2
ORIGIN: git@github.com:Homebrew/brew.git
HEAD: 117c24f4b6294e037431d3a850ced6955d53e26f
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d85a6e77835a964adba81b90fc508f0f672bb974
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /Users/zozo/Library/Logs/Homebrew
HOMEBREW_UPDATE_TO_TAG: 1
HOMEBREW_VISUAL: /Users/zozo/bin/subl-wait
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
CLT headers: 10.1.0.0.1.1539992718
  </pre>
</details>

<details>
  <summary>brew doctor</summary>
  (These warnings have come up every time I've run Homebrew for years. The potential problems with building have never materialized for me.)
  <pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
  </pre>
</details>

# What you expected to happen

Homebrew to update itself normally, using bash.

# Step-by-step reproduction instructions (by running `brew` commands)

1. `brew install fish`
2. `chsh -s /usr/local/bin/fish` (per the installation caveats)
3. Open a login session in a new terminal window.
4. `brew update`

# Workaround

From within fish, `env SHELL=(type -P bash) brew update` works as expected.

*****

This may very well be a "user configuration" issue. Please let me know if you need any other information from me.

**Comment by MikeMcQuaid** [comment]
@reitermarkus and @mistydemeo use Fish, I believe. Can either of you reproduce this?

**Comment by reitermarkus** [comment]
I cannot reproduce this. Maybe an issue with the `sass/sass` tap, since you're getting a `Could not read from remote repository.` error?

**Comment by zgracem** [comment]
I untapped `sass/sass` and now it just hangs after `homebrew/services` instead.

**Comment by MikeMcQuaid** [comment]
Can continue to discuss here but closing as not reproducible, sorry.

**Comment by zgracem** [comment]
No worries! The problem does seem to be specific to my setup, and there's a dead easy workaround in the meantime.

**Comment by zgracem** [comment]
This was indeed a problem on my end. My git configuration was expecting an ssh-agent in the environment, but I hadn't ported the initialization for that over to my fish config files yet, hence git exiting with that weird SSH-related error. Sorry about that.
