### ISSUE TITLE
Warn about formula being reinstalled from Homebrew-core instead of pinned tap

### ISSUE THREAD

**Issue by slhck** [Homebrew/brew#5796]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I have ffmpeg installed from Homebrew core, and I have a new tap pinned:

```
brew tap varenc/ffmpeg
brew tap-pin varenc/ffmpeg
```

I want to re-install ffmpeg from this tap, using additional options, using `brew reinstall ffmpeg [options]`.

# What happened (include command output)

I run a reinstall command (since just running `install` tells me that the formula is already installed, obviously):

```
➜ brew reinstall ffmpeg --with-fdk-aac --with-openssl --with-srt
Warning: ffmpeg is provided by core, but is now shadowed by varenc/ffmpeg/ffmpeg.
To refer to the core formula, use Homebrew/core/ffmpeg instead.
==> Reinstalling ffmpeg
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-4.1.1.high_sierra.bottle.tar.gz
Already downloaded: /Users/werner/Library/Caches/Homebrew/downloads/7ad8da91a75907ea22f0a2a0188c694bb40208ed13dd75bbfb890989690e5423--ffmpeg-4.1.1.high_sierra.bottle.tar.gz
==> Pouring ffmpeg-4.1.1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/ffmpeg/4.1.1: 282 files, 59MB
```

However, ffmpeg got installed by pouring the bottle from Homebrew core instead of building from the tap. Since `brew` warns me about the tap shadowing the main formula, this is very counterintuitive..

# What you expected to happen

I expected `brew` to either:

- install the correct formula from the pinned tap, with all the options, and not pour the bottle from Homebrew core, or
- error out, saying that I still have the formula from Homebrew core installed, and that I first need to uninstall it

I can successfully build from the tap if I first uninstall the existing formula:

```
➜ brew uninstall --ignore-dependencies ffmpeg
Uninstalling /usr/local/Cellar/ffmpeg/4.1.1... (282 files, 59MB)
Taps/varenc/homebrew-ffmpeg on  master
➜ brew install ffmpeg --with-fdk-aac --with-openssl --with-srt
Warning: ffmpeg is provided by core, but is now shadowed by varenc/ffmpeg/ffmpeg.
To refer to the core formula, use Homebrew/core/ffmpeg instead.
Warning: ffmpeg is provided by core, but is now shadowed by varenc/ffmpeg/ffmpeg.
To refer to the core formula, use Homebrew/core/ffmpeg instead.
==> Installing ffmpeg from varenc/ffmpeg
...
```

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew install ffmpeg
brew tap varenc/ffmpeg
brew tap-pin varenc/ffmpeg
brew reinstall ffmpeg --with-fdk-aac
```

Brew config / doctor:

```
➜ brew config
HOMEBREW_VERSION: 2.0.2-72-g6c55fe1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6c55fe1c35606d783ce2a04eb1447ae9d4002e18
Last commit: 21 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8ba60f79c153b611fefadb0f2f05633c13606c4e
Core tap last commit: 13 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_DISPLAY: :0.0
HOMEBREW_LOGS: /Users/werner/Library/Logs/Homebrew
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11

➜ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/werner/.pyenv/shims/python3.6m-config
  /Users/werner/.pyenv/shims/python-config
  /Users/werner/.pyenv/shims/python3-config
  /Users/werner/.pyenv/shims/python3.6-config

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/fuse-ext2.pc
```

**Comment by MikeMcQuaid** [comment]
The message is confusing but I think the rest of the behaviour is correct; `brew reinstall` should reinstall the formula that's currently installed.

**Comment by slhck** [comment]
If that is the intended behavior of `brew reinstall`, it would be best if there was a warning telling the user that despite having another tap pinned, the existing version of the formula gets reinstalled:

> WARNING: You are reinstalling #{formula} from #{tap}, but it is shadowed by #{otherformula} from #{othertap}. If you intended to install #{otherformula} from #{othertap}, please run "brew uninstall #{formula}" first.

… or similar. The fact that options got silently ignored also made it hard for me to tell that I didn't get the correct version—the only giveaway was the fact that the third-party tap doesn't provide bottles.

Looking into the Homebrew source code, I actually don't understand how it can happen that `brew reinstall <formula>` prints a warning about `<formula>` being pinned, but then resolves to the already existing version. Hard to tell where such logic should be implemented.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/brew/issues/5418 has also been open for a while. I'm increasingly thinking that tap-pinning doesn't really work well enough and should be deprecated in favour of fully scoping tapped formulae names when they clash which works consistently and as expected (including and especially for dependencies).

**Comment by luispuerto** [comment]
hey! just jumping in to ask-suggest something. 

@MikeMcQuaid perhaps you have already mention this in other thread or issue, but whey dependencies aren't installed from pinned taps? In the end, when you pin a tap is because you want to those formule take precedence always, don't you?

**Comment by slhck** [comment]
@Luispuerto That seems like an entirely different issue. Dependencies of core formulae should be resolved from core, I believe, since otherwise Homebrew could not guarantee that they successfully build.

**Comment by luispuerto** [comment]
@slhck that was a lot of sense... but problem is when you prefer formulae in other taps because they provide options. You need to uninstall/install (build?) every time you want update packages with those dependencies.

**Comment by MikeMcQuaid** [comment]
@luispuerto We don't support replacing dependencies with ones from arbitrary taps because we have no idea if they will even work for the formula that depends on them. Say you have a stripped-down formula (or a formula with extra options in a tap): there are no guarantees that will work with Homebrew/homebrew-core formulae. Additionally, when things do fail it's very hard to debug exactly what in the dependency tree led to that.

As I noted above: I suspect tap pinning will just go away as a feature; it doesn't work well, it's not used by any of the maintainers and no-one else is stepping up to fix the (fairly major) bugs. A better solution is to make formulae in taps use different names to Homebrew/homebrew-core formulae and fully-scope the dependencies to specific taps in your own formulae when desired.

**Comment by luispuerto** [comment]
Pinning would be a great feature if it worked as that way. Prioritizing that tap' formulae everywhere including dependencies. 

I understand about debuging and so... if you have eveything under a totally controled environment it's much more easier to pinpoint error. 

However, renaming will lead to duplicate software and linking problems.

**Comment by slhck** [comment]
I'd appreciate if this discussion was moved to a separate thread. This issue is about usability with pinned taps and users installing formulae.

**Comment by luispuerto** [comment]
@slhck sorry if I _assaulted_ your issue

**Comment by MikeMcQuaid** [comment]
@slhck Discussion of the tap pinning feature's future may continue in this thread as it's relevant to this thread. I'll stop additional explanation of the feature here, though.

**Comment by slhck** [comment]
There is activity in a PR, so this isn't stale.

**Comment by MikeMcQuaid** [comment]
Closing this out as tap-pinning has now been deprecated.
