### ISSUE TITLE
how to install older version package from local

### ISSUE THREAD

**Issue by 631068264** [Homebrew/brew#5797]
`brew install http://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz`

download too slow, so download it by other tools.
I try `brew install -f /Users/wyx/Downloads/spark-2.3.0-bin-hadoop2.7.tgz`
```
Updating Homebrew...
^CError: spark-2.3.0-bin-hadoop2.7.tgz: /Users/wyx/Downloads/spark-2.3.0-bin-hadoop2.7.tgz:1: Invalid char `\x1F' in expression
/Users/wyx/Downloads/spark-2.3.0-bin-hadoop2.7.tgz:1: invalid multibyte char (UTF-8)
```

**Comment by iMichka** [comment]
> **Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
