### ISSUE TITLE
Interrogate taps with `brew readall` on tap.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#58]
I keep forgetting to do something about this so I'll note it here.

Martin closed [this Issue](https://github.com/Homebrew/legacy-homebrew/issues/44837) over at Legacy which reminded me that for a couple months we had regular reports of Homebrew borking in places because one of the popular `homebrew-avr` taps had a syntax problem.

I proposed at the time that we ensure users' installations can't start misbehaving because of a problematic tap via executing `brew readall` on the `brew tap` tap and killing the `brew tap` operation if a problem is raised with a simple explanation. Other maintainers seemed keen on the idea when it was proposed, so here's floating that balloon back out there.

`brew readall` is a really quick operation, even `homebrew/versions` which has hundreds of formulae only takes ~0.3 seconds consistently, which is in the region of being barely appreciable to humans.

**Comment by mikemcquaid** [comment]
Seems like a good idea 👍

**Comment by chdiza** [comment]
Would this execute readall on `homebrew/homebrew-core`, just because I tap some `foo/homebrew-bar`?  That seems like it would be a big lag.

**Comment by DomT4** [comment]
No, just the tap itself. That functionality is already available today, if you do something like `brew readall homebrew/dupes -d` you'll see it only checks the `dupes` formulae.

**Comment by UniqMartin** [comment]
:+1: Sounds like a really good idea. Sorry if I'm complicating things a little, but I wonder whether that should somehow deal with the possibility of a tap's formula becoming broken after a `brew update`?

@DomT4 Glad I was able to remind you. :wink:

**Comment by mikemcquaid** [comment]
> Sorry if I'm complicating things a little, but I wonder whether that should somehow deal with the possibility of a tap's formula becoming broken after a brew update?

That also seems like a good idea as it's likely to happen.

**Comment by DomT4** [comment]
Thanks @MikeMcQuaid! You went about it in a more comprehensive way than I initially planned, so possibly for the best I'd left it alone to date 😄.
