### ISSUE TITLE
How do you install specific version of python?

### ISSUE THREAD

**Issue by Vadorequest** [Homebrew/brew#5800]
It's 3am, meaning it's been more than 3h I've been trying to switch my python 2 to python 3. 
I eventually succeeded and I now have 2.7.15 and 3.7.2 installed.... Only to figure out that I needed 3.6.8 because AWS Lambda doesn't support 3.7.

And now, I'm stuck. I don't know how to install a specific version of python, I tried using venv, pyenv, found out my Mac Mojave has additional issues and makes it even more painful to configure.

With node, I have nvm and do a nvm install 6.8.0 and it just works.
With brew, I'm still looking for a solution. Could use some help.

**Comment by iMichka** [comment]
Hi. You did not fill out the issue template. Please discuss these kind of questions on our discourse: https://discourse.brew.sh
