### ISSUE TITLE
Provide a way for third-party recipes to specify a minimum bottle architecture, and support custom architectures

### ISSUE THREAD

**Issue by fredemmott** [Homebrew/brew#5815]
# A detailed description of the proposed feature

Some software heavily depends on modern CPU features and is borderline-unusable on older systems. For example, HHVM has real-world workloads that are 19x slower when built for nehalem than when built for sandybridge.

This is really two tightly related feature requests:

1. allow specifying a default `bottle-arch` in the recipe

2. allow third-party recipes to define custom architectures that brew doesn't recognize out the box: for example, if I specify `--bottle-arch=sandybridge`, brew install errors out with "Unrecognized architecture for --bottle-arch: sandybridge`

# The motivation for the feature

1. several of our corporate users build their own slightly different bottles, and it would be good to be able to provide a recipe that 'just works' without custom instructions.

2. HHVM wants to target a microarchitecture that brew doesn't recognize

# How the feature would be relevant to at least 90% of Homebrew users

It probably isn't, and I'd expect it to only be used by taps. Perhaps `ffmpeg` could be a use case.

Opening anyway as Mike indicated on #5765 that this might be worth adding. I'm expecting this to be something I need to submit a pull request for - not for anyone else to volunteer to do, but it might be valuable to dump the ideas and motivation somewhere public anyway :)

# What alternatives to the feature have been considered

- specifying `--bottle-arch=native`: too non-portable
- specifying `--bottle-arch=nehalem`: I was surprised to discover this isn't the default on high sierra (we're getitng penryn). It's a bit faster, but still 19x slower than sandybridge for us
- specifying `--bottle-arch=nehalem` and monkeypatching `Hardware::CPU.optimization_flags` to change the `-march=` flag this resolves to: this is obviously a bad fix, and misleading. Currently doing it as a temporary band-ai
- in the past, we did a slightly cleaner monkeypatch by setting `ARGV.bottle_arch` to `:sandybridge` and monkeypatching `Hardware::CPU.optimization_flags` to recognize sandybridge. This is no longer possible now that ARGV is frozen

**Comment by MikeMcQuaid** [comment]
> * specifying `--bottle-arch=nehalem`: I was surprised to discover this isn't the default on high sierra (we're getitng penryn). It's a bit faster, but still 19x slower than sandybridge for us

We'd make it default on High Sierra but unfortunately there are Penryn machines still running High Sierra.

> * specifying `--bottle-arch=nehalem` and monkeypatching `Hardware::CPU.optimization_flags` to change the `-march=` flag this resolves to: this is obviously a bad fix, and misleading. Currently doing it as a temporary band-ai

I think modifying `OPTIMIZATION_FLAGS` and `Hardware::CPU.optimization_flags` to blindly passthrough a specified `bottle-arch` that's unrecognised to us would make sense. The compiler will blow up if it's unsupported and kill the build process.

> * allow specifying a default `bottle-arch` in the recipe

👍 I think either something in `bottle do` or a separate `bottle_arch :sandybridge` DSL would be acceptable here. In an ideal world we'd also verify the CPU is new enough on pouring but this doesn't need to block its inclusion.

> I'm expecting this to be something I need to submit a pull request for - not for anyone else to volunteer to do, but it might be valuable to dump the ideas and motivation somewhere public anyway :)

Yup, PR would be good for this. Happy to answer any questions here first, though.

**Comment by fredemmott** [comment]
Thanks - to clarify, the bad and misleading hack that I'm doing is `{nehalem: "-march=sandybridge"}`, not the general idea of extending OPTIMIZATION_FLAGS  - i.e. --bottle-arch=nehalem doesn't get you a nehalem HHVM bottle :p

**Comment by fredemmott** [comment]
Not sure it'll be me, but it seems fairly likely that someone at FB will end up doing at this - in case that happens, FB T41189241 is the internal reference for this issue.

**Comment by MikeMcQuaid** [comment]
> Not sure it'll be me, but it seems fairly likely that someone at FB will end up doing at this - in case that happens, FB T41189241 is the internal reference for this issue.

Happy to have people go on the issue as reference if that happens but closing out until it looks like it will.
