### ISSUE TITLE
Brew hands asking for github authentication information

### ISSUE THREAD

**Issue by grant-olson** [Homebrew/brew#5820]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Trying to install a python library to run the software chirp.

# What happened (include command output)

```
master-blaster:chirp.hg grant$ brew install libxml2 --with-python
Username for 'https://github.com': Updating Homebrew...
```
The install hangs here. If I enter random username it then asks for password:

```
master-blaster:chirp.hg grant$ brew install libxml2 --with-python
Username for 'https://github.com': Updating Homebrew...
stupiduser
Password for 'https://stupiduser@github.com': 
```

Once I enter any random password, brew works as normal.

The tab in my terminal indicates `git-remote-https * brew install libxml2 --with-python`

# What you expected to happen

Brew wouldn't need any authentication to install software, or it if did for particular software, it would need to be valid github credentials.

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew install libxml2
```

I imagine this won't be instantly reproducible everywhere, but documenting in case other reports roll in.

**Comment by grant-olson** [comment]
Running brew update as indicated in the checklist:

```
master-blaster:chirp.hg grant$ brew update
Username for 'https://github.com': sdfsdafsdf
Password for 'https://sdfsdafsdf@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Homebrew/homebrew-boneyard/'
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard failed!
```

**Comment by MikeMcQuaid** [comment]
You need to `brew untap homebrew/boneyard`.
