### ISSUE TITLE
Incomplete brew untap instructions

### ISSUE THREAD

**Issue by jonhadfield** [Homebrew/brew#5823]
# What you were trying to do (and why)
I ran brew doctor to check everything was clean and it gave the following instruction:

    Warning: You have the following deprecated, official taps tapped:
       Homebrew/homebrew-fuse
       completions
       versions
       x11
       Untap them with `brew untap`.

I successfully untapped the first one with command `brew untap Homebrew/homebrew-fuse`.
When I tried to untap the second item by running `untap completions` it failed.

# What happened (include command output)

    $ brew untap completions
    

<details>
  <summary>Command output</summary>
  <pre>
  
  Error: Invalid tap name 'completions'
  
  </pre>
</details>

# What you expected to happen

After running brew doctor again, it gave the correct name to untap:

    Homebrew/homebrew-completions
    versions
    x11
    Untap them with `brew untap`.

The output assumes the user knows to prefix everything with **Homebrew/homebrew-**.

# Step-by-step reproduction instructions (by running `brew` commands)

Have a number of deprecated taps set up, run `brew doctor`, follow instructions.

Version details:
Homebrew 2.0.2
Homebrew/homebrew-core (git revision 456a2d; last commit 2019-03-01)
Homebrew/homebrew-cask (git revision 77e6a; last commit 2019-03-01)

**Comment by jonchang** [comment]
Thanks for reporting this. We've fixed this already in https://github.com/Homebrew/brew/pull/5775, but the fix won't be released to most users until we release v2.0.3. If you'd like to see the updated message now you can run `HOMEBREW_DEVELOPER=1 brew update && brew doctor`
