### ISSUE TITLE
Error when running brew cleanup

### ISSUE THREAD

**Issue by Omniscimus** [Homebrew/brew#5824]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I was trying to run `brew cleanup`.

# What happened (include command output)

I got the error below. There was no other output. I get this every time I run `brew cleanup`.

<details>
  <summary>Command output</summary>
  <pre>
  
  ➜  ~  brew cleanup
Error: No such file or directory @ rb_file_s_lstat - /usr/local/Cellar/ruby/2.5.3_1/share/ri/2.5.0/system/DRb/DRbArray
➜  ~  brew config
HOMEBREW_VERSION: 2.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 117c24f4b6294e037431d3a850ced6955d53e26f
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 456a2dff404d81c4d0faa7c6251e63b3177b1211
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/omniscimus/Library/Logs/Homebrew
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
➜  ~  brew doctor
Your system is ready to brew.
  
  </pre>
</details>

# What you expected to happen

I was expecting brew to run the cleanup command without errors.

# Step-by-step reproduction instructions (by running `brew` commands)

```bash
brew cleanup
```
I'm afraid that this bug is somehow specific to my installation, but I simply installed Homebrew using the command from brew.sh (quite long ago).

**Comment by beaudh** [comment]
Looks like the brewed Ruby is out of date. I'd suggest perhaps a `brew update && brew upgrade ruby`

**Comment by Omniscimus** [comment]
> Looks like the brewed Ruby is out of date. I'd suggest perhaps a `brew update && brew upgrade ruby`

```
➜  ~/notes  brew update
Already up-to-date.
➜  ~/notes  brew upgrade ruby
Error: ruby 2.6.1 already installed
```
😕

**Comment by reitermarkus** [comment]
Try `brew uninstall --force ruby`.

**Comment by Omniscimus** [comment]
```
➜  ~ brew uninstall --force ruby
Error: Refusing to uninstall /usr/local/Cellar/ruby/2.6.1
because it is required by vim, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies ruby
➜  ~ brew uninstall --ignore-dependencies ruby
Uninstalling /usr/local/Cellar/ruby/2.6.1... (19,340 files, 32.3MB)
ruby 2.5.3_1 is still installed.
Remove all versions with `brew uninstall --force ruby`.
➜  ~ brew uninstall --force ruby
Error: No such file or directory @ rb_file_s_lstat - /usr/local/Cellar/ruby/2.5.3_1/share/ri/2.5.0/system/DRb/DRbArray
➜  ~ brew upgrade ruby
==> Upgrading 1 outdated package:
ruby 2.6.1
==> Upgrading ruby
[...]
==> Summary
🍺  /usr/local/Cellar/ruby/2.6.1: 19,340 files, 32.3MB
Error: No such file or directory @ rb_file_s_lstat - /usr/local/Cellar/ruby/2.5.3_1/share/ri/2.5.0/system/DRb/DRbArray
```
Haha it's quite stubborn, I guess my best option is reinstalling brew entirely..? 😰

**Comment by reitermarkus** [comment]
Try removing it manually: `rm -r /usr/local/Cellar/ruby`

**Comment by Omniscimus** [comment]
> Try removing it manually: `rm -r /usr/local/Cellar/ruby`

It worked, everything is working now, tyvm!
