### ISSUE TITLE
`brew update` fails after TimeMachine recovery of macOS Sierra on a new Mac

### ISSUE THREAD

**Issue by deepj** [Homebrew/brew#583]
See:
```console
$ brew update
/usr/local/Library/Homebrew/cmd/update.sh: line 14:  1017 Illegal instruction: 4  "$GIT_EXECUTABLE" "$@"
/usr/local/Library/Homebrew/cmd/update.sh: line 14:  1018 Illegal instruction: 4  "$GIT_EXECUTABLE" "$@"
Error: Fetching /usr/local failed!
Fetching /usr/local/Library/Taps/homebrew/homebrew-core failed!
```

`brew doctor` doesn't say anything special:

```console
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.
```

Git version is built 2.9.2 using homebrew on the previous Mac:

**Comment by MikeMcQuaid** [comment]
You can't do Homebrew Time Machine restores from one Mac to another as Homebrew builds binaries for your specific machine. Instead use `brew bundle dump` and `brew bundle` to migrate.

**Comment by deepj** [comment]
@MikeMcQuaid binaries work fine, but not many `brew` commands. I tried `brew bundle dump` and `brew bundle`. And got this:

```console
$ brew bundle dump
==> Tapping homebrew/bundle
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-bundle'...
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-bundle /usr/local/Library/Taps/homebrew/homebrew-bundle --depth=1
Error: Failure while executing: /usr/local/bin/brew tap homebrew/bundle
```

I must say I have done many Time Machines restores from one Mac to another without any problems. Now I am quite confused what's happening with a lot of errors in `brew` itself :(

**Comment by deepj** [comment]
@MikeMcQuaid Ah, I see. You are correct. Is it possible to add some detection in `brew doctor` for these cases? I think it would help a lot.

**Comment by MikeMcQuaid** [comment]
We can't really detect this, unfortunately.

**Comment by MikeMcQuaid** [comment]
@deepj The errors you're likely seeing are with your `git` failing; have you tried running that command manually and seeing what the failures are?

**Comment by happicamper** [comment]
@MikeMcQuaid Hello, I have the same error output and scenario from time machine backup with @deepj. Upon running simple git status displays:  
 `Illegal instruction:4` 
Do you have other fixes with this error?
@deepj did you manage to solve this error?
Thank you in advance!

**Comment by deepj** [comment]
@happicamper Hi, I deleted all homebrew installed packages and then install them again. I guess this is only possible solution.

**Comment by MikeMcQuaid** [comment]
Yes. `brew bundle dump && brew uninstall --force $(brew list); brew bundle` is your best bet.
