### ISSUE TITLE
Linuxbrew documentation is confusing

### ISSUE THREAD

**Issue by andrew** [Homebrew/brew#5835]
Since Linuxbrew has now been officially merged into Hombrew, the documentation on the difference (or lack of) is quite confusing for new users. Here are a few things that could be updated to reduce the confusion:

## 1. Remove `brew` as a pinned repo from the [Linuxbrew](https://github.com/Linuxbrew/) GitHub org:

Having the old archived `brew` pinned to the top of the linuxbrew org makes it look like it's still a separate project. GitHub doesn't help there either as it doesn't show when a pinned repo is archived.

![screenshot 2019-03-04 at 14 24 30](https://user-images.githubusercontent.com/1060/53739276-458fbb80-3e89-11e9-9f48-b11ab58f36a6.png)

## 2. Documentation suggests searching for formula on https://formulae.brew.sh/

![screenshot 2019-03-04 at 14 31 21](https://user-images.githubusercontent.com/1060/53739668-34937a00-3e8a-11e9-9f8d-464a8f3b5819.png)

The documentation on http://linuxbrew.sh suggests searching https://formulae.brew.sh/ for formula, but on https://formulae.brew.sh/ it says:

> Homebrew Formulae is an online package browser for Homebrew – the macOS package manager. 

And as far as I can tell, the list is generated from the macOS formula tap, which may have some cross-over with linuxbrew but all the details on a formula page appear to be macOS specific.

Either there should be a separate formula browser for linxbrew or https://formulae.brew.sh/ should be updated to allowing searching and showing linux specific formula and details.

## 3. Two different linuxbrew doc pages: https://docs.brew.sh/Linuxbrew and http://linuxbrew.sh

The content differs between these two pages and confuses the branding somewhat, it caused me to question if the merge was complete because linuxbrew still appears to standalone, even though it's now just a part of homebrew.

Those two pages should probably be combined, perhaps with http://linuxbrew.sh/ redirecting to https://docs.brew.sh/Linuxbrew

## Extra opinion:

Personally now that linuxbrew isn't it's own separate project, I think that the linuxbrew terminology should be dropped completely, Homebrew now just works on linux and there's a separate set of formula for linux. To go one step further than that, I'd move the linuxbrew formula under the homebrew org and call it https://github.com/homebrew/linux or similar, the Homebrew brand actually has a lot of weight behind it, and having a separate brand just for installing it on a different OS dilutes that.

**Comment by MikeMcQuaid** [comment]
I agree with pretty much all this.

**Comment by iMichka** [comment]
Thanks for feedback!

I'll go through the points one by one.

1) Done, I removed the pinned `brew` repo.
https://github.com/Homebrew/brew is the official "linuxbrew" repo (the package manager)
https://github.com/Homebrew/linuxbrew-core is the official "linuxbrew" core formulae repo.

**Comment by iMichka** [comment]
2. Yes, the https://formulae.brew.sh page is mac only. Even the analytics in there are mac only.

Migrating that part was not in our initial scope. I think this is something which will take a little bit of time. As a short-term solution we could add a line on that page telling people that this page is mac-only. Would this have helped?

**Comment by andrew** [comment]
@iMichka yeah that would help, or just removing the link from the linuxbrew docs

**Comment by iMichka** [comment]
3. I would even go as far as to redirect http://linuxbrew.sh/ directly to https://brew.sh.

https://brew.sh probably also needs a little bit more love regarding linux support. I would also like to get the same install script for mac/linux, this is also planned for later.

**Comment by iMichka** [comment]
> Personally now that linuxbrew isn't it's own separate project, I think that the linuxbrew terminology should be dropped completely, Homebrew now just works on linux and there's a separate set of formula for linux. To go one step further than that, I'd move the linuxbrew formula under the homebrew org and call it https://github.com/homebrew/linux or similar, the Homebrew brand actually has a lot of weight behind it, and having a separate brand just for installing it on a different OS dilutes that.

The linuxbrew terminology will maybe disappear a little bit, but we can not remove it completely. In the linux context, we may still use Linuxbrew.

We already moved the core repo to https://github.com/Homebrew/linuxbrew-core a few days ago.
Before you ask, there is no plan to merge the two core repos right now, as there are too many differences. I need to make a short FAQ on that later, as we got that question quite often.

**Comment by MikeMcQuaid** [comment]
> The linuxbrew terminology will maybe disappear a little bit, but we can not remove it completely. In the linux context, we may still use Linuxbrew.

Out of interest: why can the terminology not disappear? I'm not saying it can but would be good to be explicit here.

**Comment by sjackman** [comment]
Hi, Andrew. Thanks for the suggestions. I largely agree.

> > The linuxbrew terminology will maybe disappear a little bit, but we can not remove it completely. In the linux context, we may still use Linuxbrew.
> 
> Out of interest: why can the terminology not disappear? I'm not saying it can but would be good to be explicit here.

The term "Linuxbrew" is a convenient abbreviation for "Homebrew on Linux". I'm fine with phasing out the term Linuxbrew in documentation.

There are no current plans to change these two uses of the term `linuxbrew`:

1. The core tap is https://github.com/Homebrew/linuxbrew-core
2. The default installation prefix is `/home/linuxbrew/.linuxbrew`

**Comment by MikeMcQuaid** [comment]
> There are no current plans to change these two uses of the term `linuxbrew`:
> 
> 1. The core tap is https://github.com/Homebrew/linuxbrew-core
> 2. The default installation prefix is `/home/linuxbrew/.linuxbrew`

Yup, these seem fine. I'd suggest we aim to have no user-visible documentation or messages specifically referring to it as a current name and, where necessary, go for "formerly known as Linuxbrew" or similar.

> just removing the link from the linuxbrew docs

👍 

> https://brew.sh probably also needs a little bit more love regarding linux support. I would also like to get the same install script for mac/linux, this is also planned for later.

I think it's fine for now, personally. I'd also rather see http://linuxbrew.sh/ go away first.

---

If we've got a vague consensus on the above I'm happy to open some PRs.

**Comment by iMichka** [comment]
> Out of interest: why can the terminology not disappear? 

@sjackman was faster than me to answer that question.

> If we've got a vague consensus on the above I'm happy to open some PRs.

Go ahead :)

> I'd also rather see http://linuxbrew.sh/ go away first.

Not sure we want to give up the domain name. Anybody could then buy it and use it for malicious purposes. We have already seen fishy things around the `homebrew` brand.

**Comment by sjackman** [comment]
>> just removing the link from the linuxbrew docs

> 👍

Done.

> I think it's fine for now, personally. I'd also rather see http://linuxbrew.sh/ go away first.

There's a link to the installation instructions for Homebrew on Linux at https://brew.sh, but the one-line installation command is not found there without clicking. That's my number one reason to keep https://linuxbrew.sh around. I'm otherwise more than happy to retire it. I would love for the one-line installation command at https://brew.sh to work on both macOS and Linux.

**Comment by MikeMcQuaid** [comment]
Sorry, to be clear what I mean by "go away first": I mean go away as standalone content and instead redirect to e.g. the Homebrew Linux docs.

**Comment by andrew** [comment]
Updated the links on http://linuxbrew.sh in the interim: https://github.com/Linuxbrew/linuxbrew.github.io/pull/11

**Comment by andrew** [comment]
I also noticed that there's two separate patreon accounts, is it worth merging those now?

**Comment by sjackman** [comment]
>

**Comment by sjackman** [comment]
> I also noticed that there's two separate patreon accounts, is it worth merging those now?

Yep, that's the plan.

**Comment by MikeMcQuaid** [comment]
All done (I think), thanks for the issue @Andrew!
