### ISSUE TITLE
Ruby error:  cannot load such file -- concurrent/map

### ISSUE THREAD

**Issue by saviofelixmuniz** [Homebrew/brew#5836]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I was trying to install a new dependency on brew (yarn, to be more specific). `brew install yarn`.

# What happened (include command output)

I ended up with a fail log from ruby. "cannot load such file -- concurrent/map (LoadError)"

<details>
  <summary>Command output</summary>
  <pre>
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- concurrent/map (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/core_ext/object/blank.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:10:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:17:in `require_relative'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:17:in `<main>'
  </pre>
</details>

# What you expected to happen

I expected the package to be installed

# Step-by-step reproduction instructions (by running `brew` commands)

I don't know how it came out to show these logs so I don't know how to reproduce it. But it's coming out in every brew action (update, doctor, cleanup). I have tried to delete the portable ruby and to delete linkage info, as stated in issue #5561 but no success.

**Comment by MikeMcQuaid** [comment]
This is specific to your machine. Try to run `brew update-reset` to address this.
