### ISSUE TITLE
linuxbrew does not support services

### ISSUE THREAD

**Issue by morgo** [Homebrew/brew#5847]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Linuxbrew currently does not support brew services.  This was [confirmed on Twitter](https://twitter.com/sjackman/status/1103712101153923072).

# What happened (include command output)

There is no note in the install about the service (or how to manually start the program) at the end of install like there is in macOS ([my service](https://github.com/Homebrew/homebrew-core/pull/37634)):

```
morgo@ryzen:/tmp$ brew install tidb-server.rb 
==> Cloning https://github.com/pingcap/tidb.git
Updating /home/morgo/.cache/Homebrew/tidb-server--git
==> Checking out tag v2.1.5
HEAD is now at 4dc3093 CHANGELOG: add changelog for v2.1.5 (#9501)
HEAD is now at 4dc3093 CHANGELOG: add changelog for v2.1.5 (#9501)
==> make server
==> Caveats
This install of TiDB uses goleveldb as the storage engine instead of TiKV,
and is slower than a production install. Any benchmarks will be unreliable.

tidb-server does not bundle any clients. To use the MySQL client:
brew install mysql-client
mysql -h 127.0.0.1 -P4000 -uroot
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/tidb-server/2.1.5: 7 files, 43.8MB, built in 37 seconds

```

Also trying to list or start services produces errors:

```
morgo@ryzen:/tmp$ brew services start tidb-server
sh: 1: list: not found
sh: 1: list: not found
Error: Failure while executing; `'' load -w /home/morgo/Library/LaunchAgents/homebrew.mxcl.tidb-server.plist` exited with 1.

morgo@ryzen:~$ brew services list
sh: 1: list: not found
sh: 1: list: not found
Name        Status  User  Plist
mysql       stopped       
tidb-server started morgo /home/morgo/Library/LaunchAgents/homebrew.mxcl.tidb-server.plist

```

# What you expected to happen

If services is not yet supported, I think it is fine to print a warning if a plist is defined.  The `plist_options :manual ` should be printed regardless though.

# Step-by-step reproduction instructions (by running `brew` commands)

Try with any Formula that uses a plist:
```
brew install mysql
brew services start mysql
```

**Comment by MikeMcQuaid** [comment]
Linuxbrew cannot support `plist` services as-is as they are specific to macOS's `launchctl`.

**Comment by sjackman** [comment]
Yep, @morgo has suggested printing an error message to this effect.

**Comment by sjackman** [comment]
Here's the link to the `brew services` command: https://github.com/Homebrew/homebrew-services/blob/c7e22c9a4f6eae437884c53c3c6cfd760208e0b0/cmd/brew-services.rb#L91
You can print an error message with…
```ruby
odie "brew services is supported only on macOS" unless OS.mac?
```

**Comment by morgo** [comment]
Thank you, I will take a look.

**Comment by sjackman** [comment]
Here's the function that prints the services information with `brew info`:
https://github.com/Homebrew/brew/blob/01bd14be616904f6ebbb8e01492dea54740942f1/Library/Homebrew/extend/os/mac/caveats.rb#L4

Copy the `plist_manual` code
https://github.com/Homebrew/brew/blob/01bd14be616904f6ebbb8e01492dea54740942f1/Library/Homebrew/extend/os/mac/caveats.rb#L34-L37
from there to
https://github.com/Homebrew/brew/blob/01bd14be616904f6ebbb8e01492dea54740942f1/Library/Homebrew/caveats.rb#L139
