### ISSUE TITLE
brew update lists new/updated formulae twice

### ISSUE THREAD

**Issue by lewisinc** [Homebrew/brew#585]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [N/A] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Running my regular `brew update` lists new and updated formulae twice. Running `brew doctor` doesn't fix the issue.

<img width="1280" alt="screen shot 2016-07-24 at 2 52 39 pm" src="https://cloud.githubusercontent.com/assets/6754950/17110224/c84b2bb8-5250-11e6-857f-363d077a57cd.png">
<img width="1280" alt="screen shot 2016-07-25 at 9 35 03 am" src="https://cloud.githubusercontent.com/assets/6754950/17110230/cd5af11a-5250-11e6-8752-5950412d9f31.png">

**Comment by DomT4** [comment]
You seem to have two `homebrew/core`s, which is unusual. Can you provide the output of:

```bash
ls $(brew --prefix)/Library/Taps/homebrew
```

Your `brew config` could be useful as well.

**Comment by lewisinc** [comment]
`ls $(brew --prefix)/Library/Taps/homebrew` yields
`homebrew-completions/ homebrew-core/        homebrew-homebrew/`
`brew config` yields
```HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1455aa3da6335b1eeb284e61171cff524c620fa3
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 14eaa685169edf4283e1dadd5818646f67d09f30
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /Volumes/Datacron/anaconda/bin/python => /Volumes/Datacron/anaconda/bin/python3.5
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1/bin/ruby
Java: N/A
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11```

**Comment by lewisinc** [comment]
I think it's worth noting that the `homebrew-homebrew/` folder is empty.

**Comment by bfontaine** [comment]
@lewisinc FYI I edited your comment to fix the code block; you have to make a newline after and before the triple-backquotes otherwise it shows as inline code:

    ```this doesn't
    work.```
    
    ```
    this does.
    ```

**Comment by lewisinc** [comment]
Well, thanks for the tip - I'll try to format things properly in the future. This double listing thing is pretty annoying, though. Any tips on whether this is a bug or just a faulty installation / how does I fix?

**Comment by UniqMartin** [comment]
> I think it's worth noting that the `homebrew-homebrew/` folder is empty.

I think in this case it's perfectly safe and also the correct solution to just delete this directory. This should resolve the issue. Normally, this directory should have never been created.

> Any tips on whether this is a bug or just a faulty installation / how does I fix?

I suspect it is a subtle bug in our code that allows this directory to be created. Do you have any idea where it came from? Maybe have a look at the creation and/or modification date of that directory to see when it came into existence and think about whether you can draw a connection to something you did with Homebrew. (You're not the first one to report this issue, but we currently don't have any clues what is causing this, so every bit of information helps.)

**Comment by lewisinc** [comment]
It looks like the creation date of the file is the same day and time that I tapped into `homebrew-completions`. I'm attaching relevant command I ran in my bash console around that time.
```
brew search bash-completion
brew info bash-completion
bash --verison
bash --version
brew info bash
brew search bash-completion
brew info bash-completion
brew search bash-completion
brew info bash-completion
brew info bash
brew install bash
which bash
bash --version
chsh
chpass -s /usr/local/Cellar/bash/4.3.46/bin/bash
chsh
chsh
brew install bash-completiob
brew install bash-completion
cd /usr/local/etc/bash_completion.d/
ls -n /Applications/Docker.app/Contents/Resources/etc/docker.bash-completion
ls -n /Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion
ls -n /Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion
ls /Applications/Docker.app/Contents/Resources/etc/
ln -s /Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion
ln -s /Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion
ln -s /Applications/Docker.app/Contents/Resources/etc/docker.bash-completion
brew search git
brew info git-integration
brew search completion
brew info homebrew/completions/apm-bash-completion
brew tap homebrew completions
brew tap homebrew/homebrew/completions/apm-bash-completion
brew tap homebrew/completions
brew info homebrew/completions/apm-bash-completion
brew install homebrew/completions/apm-bash-completion
ls /usr/local/etc/bash_completion.d/
ls /usr/local/etc/bash_completion.d/ | atpm
ls /usr/local/etc/bash_completion.d/ | rep apm
ls /usr/local/etc/bash_completion.d/ | grep apm
source /usr/local/etc/bash_completion.d/apm
```

I don't know how much of this is actually helpful, but it's what I can think of. Maybe a malformed `tap` command created a directory it shouldn't have or something. Let me know if you'd like any more info.

**Comment by scpeters** [comment]
~~~
brew tap homebrew/homebrew/completions/apm-bash-completion
~~~
looks suspicious to me

**Comment by lewisinc** [comment]
Okay, so I deleted the folder `homebrew-homebrew` and I'm no longer experiencing the issue I was before. Maybe it would be a good idea for `brew doctor` to look for empty folders such as the one I just deleted and remove them?

**Comment by MikeMcQuaid** [comment]
> Maybe it would be a good idea for brew doctor to look for empty folders such as the one I just deleted and remove them?

@lewisinc Yes, this would be a good idea 👍

**Comment by lewisinc** [comment]
I think I'm gonna try and implement that and make a pull request, if that's cool.

**Comment by MikeMcQuaid** [comment]
@lewisinc Please do! [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by lewisinc** [comment]
Cool! Is there an IRC/Gitter channel I can join as well?

**Comment by MikeMcQuaid** [comment]
#machomebrew on Freenode but not everyone (i.e. me) is there.

**Comment by UniqMartin** [comment]
> It looks like the creation date of the file is the same day and time that I tapped into `homebrew-completions`. I'm attaching relevant command I ran in my bash console around that time.

Thanks! This was super helpful! The problematic command is:

```console
$ brew tap homebrew/homebrew/completions/apm-bash-completion
==> Tapping homebrew/homebrew/completions/apm-bash-completion
Cloning into '/opt/brewery/dummy/Library/Taps/homebrew/homebrew-homebrew/completions/apm-bash-completion'...
fatal: repository 'https://github.com/Homebrew/homebrew-homebrew/completions/apm-bash-completion/' not found
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-homebrew/completions/apm-bash-completion /opt/brewery/dummy/Library/Taps/homebrew/homebrew-homebrew/completions/apm-bash-completion
```

This creates the empty directory that ended up in your installation. I guess we should be a tad more careful with validating tap names (a name with three slashes is certainly not valid).

The other reason why this is causing the duplicated output is that `homebrew/homebrew` is somewhat special due to legacy reasons. Just try `brew tap-info homebrew/homebrew` in a Homebrew installation without that bogus empty directory. It will show you the information for `homebrew/core` instead.

**Comment by UniqMartin** [comment]
I created a PR that prevents this from happening in the future: #591.

However, adding a check to `brew doctor` might still be useful for those who have already ended up with the empty directory that causes the duplicate `brew update` output. (And other empty directories as many invalid tap names will cause an empty directory to be created.)
