### ISSUE TITLE
S3DownloadStrategy disappeared

### ISSUE THREAD

**Issue by acgray** [Homebrew/brew#5854]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

<details>
<summary>`brew config` output</summary>
<pre>
HOMEBREW_VERSION: 2.0.3-20-ga00570b
ORIGIN: https://github.com/Homebrew/brew
HEAD: a00570be77da7b5a32208d645013a8bb353af941
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7be50eb2d1dbe7aa885ce349279f71baadca87c6
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/agr/Library/Logs/Homebrew
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.14-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
</pre>
</details>

<details>
<summary>`brew doctor` output</summary>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/11/bin/gdal-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libnnz11.dylib
  /usr/local/lib/libociei.dylib
  /usr/local/lib/libocijdbc11.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  bash-completion
</pre>
</details>

# What you were trying to do (and why)

Download a formula from a tap hosted in a private S3 bucket.  Tried with `:using => :s3` and `:using => S3DownloadStrategy` as documented [here](https://www.rubydoc.info/github/Homebrew/brew/S3DownloadStrategy) and [here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula.rb#L2158).

However, the `S3DownloadStrategy` seems to have been removed in 599ecc9.

# What happened (include command output)

Therefore, unsurprisingly, the formula does not install correctly with either approach.

<details>
  <summary>Command output</summary>
  <pre>
Error: Unknown download strategy s3 was requested.
  </pre>
</details>

# What you expected to happen

The formula should install correctly.

# Step-by-step reproduction instructions (by running `brew` commands)

`brew install my-s3-hosted-tap/my-formula`

----
I can obviously submit a PR to make the docs consistent, but is this intended, and if so what is the correct way to host formulae on S3, if supported at all?

**Comment by MikeMcQuaid** [comment]
> as documented [here](https://www.rubydoc.info/github/Homebrew/brew/S3DownloadStrategy) and [here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula.rb#L2158).

rubydoc is sufficiently outdated that unfortunately we should remove it from the docs entirely and perhaps just point to e.g. the source instead or use GitHub Actions to build our own version. The other reference should be removed though; a PR for that would be great, thanks!

> if so what is the correct way to host formulae on S3, if supported at all?

It's not supported but: copying the existing download strategy into your formulae.
