### ISSUE TITLE
intersection of brew outdated + brew leaves (brew outdated --leaves ?)

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/brew#5858]
# A detailed description of the proposed feature

I would like `brew outdated` to have a `--leaves` flag.

# The motivation for the feature

I don't necessarily want to run `brew upgrade` without a token all the time - sometimes I just want certain packages updated. It can be difficult from running `brew outdated` to figure out which are dependencies and which are the packages i have installed. I currently have to try and pipe `brew outdated` into `brew leaves` (or write a script...) to see the intersection.

# How the feature would be relevant to at least 90% of Homebrew users

I believe others have this issue but are either not aware it is an issue or solve it themselves with the workaround I proposed above (external script).

# What alternatives to the feature have been considered

See above.

If this is desirable I would be happy to work on the PR.

**Comment by MikeMcQuaid** [comment]
Have you investigated using something like `brew bundle` for this? I mentioned it because I have the same use-case and that's what I use.

**Comment by brianmorton** [comment]
I'm not 100% sure I understand the usage here.

```
brew bundle dump
brew bundle check --verbose
```

that should spit out everything that needs updating without actually doing any updates, right?

**Comment by MikeMcQuaid** [comment]
Yes, pretty much. Could even use a pipe from one to the other with `--file=-`

**Comment by MikeMcQuaid** [comment]
@brianmorton Any thoughts on this?

**Comment by brianmorton** [comment]
@MikeMcQuaid I was letting it simmer a bit... ;)

I would agree your solution is acceptable... I still feel like I would enjoy first-party support for this (eg. `brew outdated --leaves` or similar) but would understand if this is a low-priority (or no-priority ;)) thing.

**Comment by MikeMcQuaid** [comment]
Cool, thanks. Closing this out for now just because it's something I'd want to see a bit more widely requested before it's something we build/ask for help building. Thanks anyway ❤️
