### ISSUE TITLE
Please find a better way to store GitHub API token

### ISSUE THREAD

**Issue by gelraen** [Homebrew/brew#5863]
# A detailed description of the proposed feature

Please introduce a better way of storing GitHub API token. E.g. put it into OS X keychain or just a simple file somewhere?

# The motivation for the feature

Here's how the prompt to set API token looks today:

```
Create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.zshrc
```

Doing it that way is risky due to a combination of 2 factors:
1) Every program launched from a shell with that variable set will have it in memory. And therefore the token is pretty much guaranteed to leak through any core dumps or text dumps of debugging information.
2) [`public_repo`](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes) scope gives write access to public repositories. Unfortunately, I don't see a scope that could be used here instead that would provide read-only access to public information.

# How the feature would be relevant to at least 90% of Homebrew users

It will reduce the risk of accidentally leaking API tokens for anyone opting in to let HomeBrew use GitHub API.

**Comment by MikeMcQuaid** [comment]
We will use your GitHub Git HTTP API token if it's in your keychain. We don't recommend that as a route because it's significantly more involved to setup.

**Comment by gelraen** [comment]
Do you have a link to setup instructions?
