### ISSUE TITLE
`brew cleanup` removed dependencies of existing packages

### ISSUE THREAD

**Issue by andreareina** [Homebrew/brew#5866]
I had an existing install of gnuplot (v5.2.0). This was installed via homebrew some months ago. The other day I `brew install`ed something, which triggered an upgrade of several libraries, which triggered a `brew cleanup` of the old versions. Except that gnuplot depended on those old versions:

```
$ gnuplot
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /usr/local/bin/gnuplot
  Reason: image not found
Trace/BPT trap: 5
```

Homebrew version:

```
$ brew --version
Homebrew 2.0.4
Homebrew/homebrew-core (git revision c9a5f; last commit 2019-03-11)
Homebrew/homebrew-cask (git revision 75af4; last commit 2019-03-12)
```

**Comment by jonchang** [comment]
Please always fill out the issue template. You need to update `gnuplot`.
