### ISSUE TITLE
Add built-in alias 'brwe' as it is so easy to mistype a command

### ISSUE THREAD

**Issue by ussserrr** [Homebrew/brew#5869]
# A detailed description of the proposed feature
My suggestion is pretty simple — add alias `brwe == brew` as a built-in feature.

# The motivation for the feature
Personally, I often mistype `brew` command as `brwe` and ...

# How the feature would be relevant to at least 90% of Homebrew users
... I believe that I am not the only one with such issue 😉.

# What alternatives to the feature have been considered
Of course you can always add an alias using your shell (e.g. bash).

P.S. Actually, I've already seen similar feature in some other CLI utilities (unfortunately, I can't remember them right now). For example, it can hint that the command for your exact input isn't found but suggest the closest match for it.

**Comment by jonchang** [comment]
I don't think we'll be adding this feature since we intentionally only install a single `brew` binary by default. This is better served by adding an alias to your `.bashrc` or similar.
