### ISSUE TITLE
brew outdated brew

### ISSUE THREAD

**Issue by ronaldmannak** [Homebrew/brew#5871]
# A detailed description of the proposed feature

Add `brew outdated brew` feature to check if brew itself is outdated.

# The motivation for the feature

I believe `brew doctor` used to check if the installed brew version was up to date, but was removed at some point. While `brew outdated` can be used to check if a formula is outdated, there currently is no (straightforward) way to check if brew itself is outdated.

Npm has a similar 'npm outdated npm' feature.

# How the feature would be relevant to at least 90% of Homebrew users

I'm working on Mac app that uses Homebrew and npm under the hood. I am providing my users a one-click update functionality for these tools. If npm is up to date, I simply hide the 'update' button. I'm unable to do the same with brew, since the app can't see if brew itself is outdated or now. Showing the 'update' button while brew is updated confuses users, so the alternative I'm considering is removing the update button for brew all together. 

# What alternatives to the feature have been considered

A Github API call or curl command to fetch the latest version could be an alternative.

**Comment by vitorgalvao** [comment]
`brew` updates itself on `brew update`, which itself (by default) runs automatically with a short timeout (60 seconds), so there’d be no point to checking if `brew` is outdated, because by the point you ran the command to check, it’d no longer be. `brew`’s update mechanism is zero-click, in that sense.

So just run your `brew` commands at will in the app. Any user that knows enough about Homebrew to turn off auto-updating should be smart enough to understand the consequences.

**Comment by ronaldmannak** [comment]
@vitorgalvao Thanks for the quick answer. I wasn't aware brew auto-updates. Whether that's a good design principle is a different discussion, but it works for me. I guess an outdated command would only make sense for the small minority who has auto-update disabled.

**Comment by vitorgalvao** [comment]
> Whether that's a good design principle is a different discussion

It is. Only good things came out of it, less breakage and less bug reports.

> I guess an outdated command would only make sense for the small minority who has auto-update disabled.

Not even for those. You need `brew update` to update the formulae and casks definition anyway. There’s no situation where that command would be useful.
