### ISSUE TITLE
I am trying to install Linuxbrew but to no avail. 

### ISSUE THREAD

**Issue by vivianfrench2** [Homebrew/brew#5872]
For some reason, when I install Linuxbrew, it doesn't allow me to use the brew command. I don't know what to do.

**Comment by iMichka** [comment]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

We will need more details too. I would propose that you start discussing this on discourse to get more help: https://discourse.brew.sh
