### ISSUE TITLE
linuxbrew tap changes clone url

### ISSUE THREAD

**Issue by enplotz** [Homebrew/brew#5874]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

First of all, I did mark the "reproduction with multiple formulae" checkbox since my issue neither concerns a single formula, nor cask, nor a single tap formula. Second, I could not remove the doctor output completely (see below), since I'm using a non-standard brew prefix (I know the disclaimer! But I really suspect that a different prefix is not the issue here!).

*Note:* This is a fresh install of the OS (Ubuntu) and linuxbrew. Trying to tap was literally the first thing after running `brew doctor` after the install to verify that everything is set up correctly.

Anyway, I have a tap I wanted to set up for some Linux stuff `enplotz/linuxbrew-formulae`.
While adding the tap `brew tap enplotz/linuxbrew-formulae`, I hit a *bug that replaces "linuxbrew" with "homebrew" in the git clone url*, which is really an issue since this repository does not exist (nor is it the one I wanted to tap).
I think the issue might have been introduced in #5809. However I'm new to using taps and especially linuxbrew.

# What happened (include command output)

In short, while adding my tap `linuxbrew-formulae`, the git clone url got changed:

<details>
  <summary><code>$ brew tap enplotz/linuxbrew-formulae</code ></summary>
  <pre>
==> Tapping enplotz/formulae
Cloning into '/home/enplotz/.linuxbrew/Homebrew/Library/Taps/enplotz/homebrew-formulae'...
Username for 'https://github.com': enplotz
Password for 'https://enplotz@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/enplotz/homebrew-formulae/' not found
Error: Failure while executing; `git clone https://github.com/enplotz/homebrew-formulae /home/enplotz/.linuxbrew/Homebrew/Library/Taps/enplotz/homebrew-formulae --depth=1` exited with 128.
  </pre>
</details>

The output clearly shows that the tap repository name gets changed:
```
fatal: repository 'https://github.com/enplotz/homebrew-formulae/' not found
```

<details>
  <summary><code>$ brew doctor</code ></summary>
  <pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this unsupported configuration.
  </pre>
</details>

<details>
  <summary><code>$ brew config</code ></summary>
  <pre>
HOMEBREW_VERSION: 2.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f07fe5c5cdfdf0f424bba7b879faa38aedc8ee4
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 63ae376fa279eca589c618333057eccc65caecec
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /home/enplotz/.linuxbrew
HOMEBREW_REPOSITORY: /home/enplotz/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/enplotz/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/enplotz/.cache/Homebrew
HOMEBREW_LOGS: /home/enplotz/.cache/Homebrew/Logs
CPU: 64-core 64-bit unknown_0x17_0x1
Homebrew Ruby: 2.3.7 => /home/enplotz/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.15.0-46-generic x86_64 GNU/Linux
OS: Linux Mint 19.1 Tessa (tessa)
Host glibc: 2.27
/usr/bin/gcc: 7.3.0
glibc: N/A
gcc: N/A
xorg: N/A
  </pre>
</details>

# What you expected to happen

Being able to use formulas at my tap `enplotz/linuxbrew-formulae`.

# Step-by-step reproduction instructions (by running `brew` commands)

Create tap `username/linuxbrew-foo`.
```
brew tap username/linuxbrew-foo
```
Watch how it tries to clone `username/homebrew-foo`.

If you need anything else or I should modify the issue/do additional steps, please say so. I'm new to the process here.

**Comment by reitermarkus** [comment]
Do we actually want to support `linuxbrew-` for anything other than `linuxbrew-core`, where it's basically a workaround to avoid the name clash?

**Comment by reitermarkus** [comment]
I guess it's working as expected, and your tap should be named `homebrew-formulae` instead of `linuxbrew-formulae`.

**Comment by enplotz** [comment]
Thanks for responding so quickly!
I am totally fine with renaming my tap (I was originally planning to only use it on my Linux machines). I was not aware that the prefix (homebrew or linuxbrew) is removed for non-core taps.

In this sense, however, I would not say it is working as *I* expected.
As a user, I think the binary could complain about a reserved prefix and not do something non-obvious under the hood that then fails and surfaces a git command. Or the workaround could only be limited to `linuxbrew-core` and everything else that does not start with `homebrew-` is left alone.

Thanks for the great project, I really appreciate being able to install software as non-root on my machines!

**Comment by sjackman** [comment]
For now, I suggest outputting an error message when a tap is named `*/linuxbrew-*` and is not the core tap `homebrew/linuxbrew-core`.

**Comment by jonchang** [comment]
> For now, I suggest outputting an error message when a tap is named `*/linuxbrew-*` and is not the core tap `homebrew/linuxbrew-core`.

For consistency, shouldn't `brew tap jonchang/linuxbrew-formula` point to a git remote `jonchang/homebrew-linuxbrew-formula`? I think special casing `linuxbrew-core` is fine, but we should use `homebrew-*` for everything else.

**Comment by iMichka** [comment]
As you said, `linuxbrew-core` is an exception, and `homebrew-*` should be used for everything else.

The only action I see here would be to improve `brew tap` to either not accept anything else than `homebrew-*` and `linuxbrew-core`, or rework completely the concept. I also find that there is way too much magic in the code around trying to guess how a tap should be named.

As this is just cosmetics right now, and not a huge priority, I'll close this issue. If anybody wants to work on this, feel free to do so.

**Comment by sjackman** [comment]
@enplotz If you'd like to open a PR to address this issue, here's the relevant code:
https://github.com/Homebrew/brew/blob/db42dd0420f57125498e079886684122b55b370c/Library/Homebrew/tap.rb#L29
