### ISSUE TITLE
`brew deps --installed --include-requirements` error for formulae with dependency version requirements

### ISSUE THREAD

**Issue by ChrisBaker97** [Homebrew/brew#5878]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

<details>
<summary>brew config</summary>
<pre>
$ brew config
HOMEBREW_VERSION: 2.0.4-27-gab06303
ORIGIN: https://github.com/Homebrew/brew
HEAD: ab06303ee62a236de53b2929100cb50a3471c5a6
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d78f6f37813a44312bc56a72ad7fce6185d68c97
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_BADGE: 
HOMEBREW_LOGS: /Users/chris/Library/Logs/Homebrew
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2, 9.0.4, 1.8.0_202
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
CLT headers: 10.1.0.0.1.1539992718
</pre>
</details>

<details>
<summary>brew doctor</summary>
<pre>
Your system is ready to brew.
</pre>
</details>

# What you were trying to do (and why)

Certain formulae specify requirements in addition to dependencies. For example:

```
$ brew deps go --include-requirements 
:macOS >= 10.10

$ brew deps ffmpeg --include-requirements
:java >= 1.8
# [and many more...]
```

However, if you combine the `--installed` command line option with `--include-requirements`, an error is produced on these formulae. The error does not occur when either option is specified independent of the other.

# What happened (include command output)

```
$ brew deps go --include-requirements --installed 
Error: undefined method `installed?' for #<MacOSRequirement: "macos" []>
Did you mean?  instance_of?
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/deps.rb:100:in `select!'
/usr/local/Homebrew/Library/Homebrew/cmd/deps.rb:100:in `deps'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

$ brew deps ffmpeg --include-requirements --installed
Error: undefined method `installed?' for #<JavaRequirement: [] version="1.8+">
Did you mean?  instance_of?
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/deps.rb:100:in `select!'
/usr/local/Homebrew/Library/Homebrew/cmd/deps.rb:100:in `deps'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

# What you expected to happen

The output should be identical to that of `brew deps --include-requirements` for formulae that are installed.

# Step-by-step reproduction instructions (by running `brew` commands)

```
$ if ! [[ $(brew list -1 | grep -E ^go$) ]]; then brew install go; fi && \
brew deps go --include-requirements --installed
```

**Comment by EricFromCanada** [comment]
`brew desc`'s `--installed` and `--all` aren't intented to be used with a formula argument.

**Comment by EricFromCanada** [comment]
I see the problems: 1) when `--installed` is passed, each item in the dependency list has its `.installed?` called, but requirements use `.satisfied?`; and 2) the docs don't mention this use of the `--installed` flag.
