### ISSUE TITLE
brew deletes work-in-progress version of package if it runs automatic cleanup after upgrading said package

### ISSUE THREAD

**Issue by spikegrobstein** [Homebrew/brew#5880]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

output of `brew config`:

```
HOMEBREW_VERSION: 2.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f07fe5c5cdfdf0f424bba7b879faa38aedc8ee4
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e3b68bc0d53b38669b4035ff5b291623ccd0d3a2
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /Users/spike/Library/Logs/Homebrew
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2, 1.8.0_202
macOS: 10.14.3-x86_64
CLT: 10.1.1.0.1.1545116021
Xcode: 10.1
CLT headers: 10.1.1.0.1.1545116021
```

# What you were trying to do (and why)

I manage a homebrew Tap and a collection of packages that's internal to my organisation. During development, I clone the repo of my package to `/usr/local/Cellar/<pkg>/dev` (sometimes `dev` is something else, but that's generally the convention that I use). This morning, I was updating one of the packages that I manage.

# What happened (include command output)

While testing out a feature, I `brew install`'d a package that I needed, which depended on the package that I was currently working on, which caused homebrew to upgrade to a newer version that I didn't have installed. This unlinked `dev` and then linked version `3.95.0`, which happens all the time and isn't an issue. Normally I `brew switch <pkg> dev` to go back and I'm a-ok.

This time, homebrew automatically ran `brew cleanup` after it installed my package and upgraded my currently working-on package, which caused it to delete my `dev` branch. This was a pretty serious issue since although I had made commits for some of my changes, I hadn't pushed _anything_. So now I lost ~3 hours of work.

Some details have been redacted:

 * `my/org` -- my Tap
 * `wip-package` -- the package that I'm working on
 * `new-package` -- the package that I `brew install`'d

<details>
  <summary>Command output</summary>
  <pre>
==> Installing my/org/new-pkg dependency: my/org/wip-package
==> Downloading https://XXXXXXXXXXXXXXXXXXXXXX.tar.gz
######################################################################## 100.0%
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

To have launchd start my/org/wip-package now and restart at login:
  brew services start my/org/wip-package
==> Summary
🍺  /usr/local/Cellar/wip-package/3.95.0: 132 files, 832.2KB, built in 40 seconds
==> Installing my/org/new-package dependency: hub
==> Downloading https://homebrew.bintray.com/bottles/hub-2.10.0.mojave.bottle.ta
######################################################################## 100.0%
==> Pouring hub-2.10.0.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/hub/2.10.0: 36 files, 8MB
==> Installing my/org/new-package
==> Downloading https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.tar.gz
######################################################################## 100.0%
🍺  /usr/local/Cellar/new-package/1.8.0: 6 files, 14.8KB, built in 3 seconds
==> `brew cleanup` has not been run in 30 days, running now...
...
Removing: /usr/local/Cellar/wip-package/dev... (3,576 files, 46MB)
...
  </pre>
</details>

# What you expected to happen

I would have expected it to not wipe this out. I'm realizing now that I probably should not have _expected_ this, but what would be nice is if the cleanup command could detect if the version it's deleting is a git repo and if so, either skip it or skip it if it's got modified files or maybe skip it if it doesn't have an install receipt for this particular version (which might signal that it wasn't installed via `brew install`

As a homebrew package author, I would like some mechanism to prevent this catastrophic loss in the future. Either better safety net or a way to disable automatic homebrew cleanup entirely on my development machine. But the former is probably best since I would like to `cleanup` occasionally.

I considered switching to using `git worktree` to check out my branch to the `/usr/local/Cellar/<pkg>/dev` path, but that won't save me from uncomitted changes. It'll just save me from losing completed commits.

EDIT: I have since added `export HOMEBREW_NO_INSTALL_CLEANUP=1` to my `~/.bash_profile`. I still think there should be better treatment for this, though since I like the idea of cleanup, I just want it to be a little safer.

# Step-by-step reproduction instructions (by running `brew` commands)

The best way to do this is to have a package that you're working on that does not have the latest version installed. Then clone something to a new version directory called `dev`. I'll use the `hub` package as an example, currently I have version 2.10.0 of `hub` installed.

```console
$ cp -R /usr/local/Cellar/hub/2.10.0 /usr/local/Cellar/hub/dev # simulate development version
$ mv /usr/local/Cellar/hub/2.10.0 /usr/local/Cellar/hub/2.9.0 # fake out to make it look out of date
$ brew link hub dev # link the development version
```

At this point, if you look at `brew outdated` you should see that it's reporting that `hub` is out of date. if you upgrade it, and a `cleanup` gets triggered, the `dev` directory will be erased.

This is a very contrived example since it doesn't have a git repo, etc, but it's effectively what happened to me.

I hope this is enough information.

**Comment by MikeMcQuaid** [comment]
> I have since added `export HOMEBREW_NO_INSTALL_CLEANUP=1` to my `~/.bash_profile`. I still think there should be better treatment for this, though since I like the idea of cleanup, I just want it to be a little safer.

This is the best solution for you. Your workflow here is unusual enough I don't think it's reasonable for Homebrew to deal with it by default.

**Comment by spikegrobstein** [comment]
That’s fair. Thanks for considering. I’m also going to play with pinning my WIP packages to see if that is a viable solution too. 

Now I’m just curious what kind of workflows other authors have; especially ones who manage collections of packages for internal Taps that interoperate with each other. We can’t be the only ones.
