### ISSUE TITLE
Fix timeout for `brew test` invocations

### ISSUE THREAD

**Issue by scpeters** [Homebrew/brew#5885]
There was a homebrew-core PR that had been running for 13 hours in the `brew test` stage, possibly because it left behind a second process:

* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/39299/

I'm not sure exactly why it happened, but it would be nice to have a timeout for `brew test` to keep a single package from locking up the buildfarm until a maintainer intervenes.

**Comment by MikeMcQuaid** [comment]
@scpeters Have opened https://github.com/Homebrew/brew/pull/6037 to address this. It may not handle the specific case here but it does seem to result in processes being more forcefully killed on a timeout.

@Homebrew/maintainers Please keep a watch out for any hanging `brew test`s and let me know; would love figure out a good way to reproduce this locally.
