### ISSUE TITLE
Installing bottles of arbitrary versions

### ISSUE THREAD

**Issue by sjackman** [Homebrew/brew#589]
I'd like to be able to install bottles of older versions of a formula. Pouring the bottle (extracting the tarball) is easy enough. The bottle's dependencies and its `post_install` are the needed missing info. One simple way of storing this info is to store the Ruby formula that generated the bottle alongside the bottle. To that end, when uploading bottles to Bintray, I'd also like to upload the Ruby formula that generated the bottle. That Ruby formula could alternatively be stored inside the bottle, with the caveat that it would be necessary to remove the bottle `sha256`, as it wouldn't be possible to store the `sha256` of the bottle inside the bottle, lest the universe implode. As a bonus, it would be a nice feature of the bottle file format if the bottle itself contained all of the necessary information to install the bottle.

The motivation for this feature is to install specified versions of software to repeat a data analysis pipeline, an oft-requested feature of Homebrew-Science, which could be happily stored in a Brewfile. See https://github.com/Homebrew/homebrew-science/issues/1191 @Homebrew/science

**Comment by scpeters** [comment]
This might be a bad idea, but I wonder if some of this could be embedded in the `INSTALL_RECEIPT.json`?

**Comment by sjackman** [comment]
It would be nice to store the versions of the dependencies that were used to build a keg in its `INSTALL_RECEIPT.json`.

**Comment by MikeMcQuaid** [comment]
As in the issue template:

Instead of creating an issue here, please create a pull request with your change proposal in the [Homebrew Evolution](https://github.com/Homebrew/brew-evolution) repository using the [proposal template](https://github.com/Homebrew/brew-evolution/blob/master/proposal_template.md).

---

To aid your creating of this: I'm broadly in favour of this as have thought in the past it might be useful to have the formula stored inside the bottle but we'd need a proposal and, probably, a pull request. 

I don't think version dependencies is something that we'd be handling here as our solution for this is to have resources or separate versions a la homebrew/versions.

**Comment by UniqMartin** [comment]
I think if the goal is to recreate an environment from a previous installation as accurately as possible you'd need to do the following:

- On initial installation:
  - Start with an empty Homebrew installation.
  - Save the HEAD commit of the Homebrew repository and all taps.
  - Install your formulae.
  - Dump the list of installed formulae to a `Brewfile`.
  - Backup the contents of the Homebrew cache (optional, but highly recommended).

- When replaying this installation:
  - Restore cache contents as some downloads may have disappeared from servers.
  - Rewind all repositories to the recorded commits.
  - Install formulae from the `Brewfile`.

---

If the goal is to make the circumstances under which a bottle was built easier to reproduce (which sounds like a somewhat different goal), here's the information that I think would be useful to retain (while keeping the amount of information as limited as possible):

- The hash of the most recent commit in the Homebrew repository and all taps that is already in `origin/master`. (That is the state reconstructible from publicly available information.)
- The diff between the aforementioned commit and `master` after pulling the PR. (Essentially the PR diff at the time of the build.)
- Other formulae installed at the time of the build. (The dependencies alone won't be sufficient as some/many formulae also tend to opportunistically pick up stuff from installed formulae not formally declared as a dependency.)
- Some environmental information like macOS release, Xcode release, CLT version, installed Java versions, etc. Basically everything that has a reasonable chance to impact the outcome of the build and that is not captured in the hash/diff of involved repositories.

**Comment by scpeters** [comment]
A virtual machine image could capture the full environment, though it's a heavy approach.

I've found the python [vcstool](https://github.com/dirk-thomas/vcstool) to be convenient for quickly extracting the head revision of taps:

~~~
$ vcs export --exact /usr/local/Library/Taps/
  homebrew/homebrew-core:
    type: git
    url: https://github.com/Homebrew/homebrew-core
    version: ee927da44ade67ea04236558b08906d2ce2fe5bd
  homebrew/homebrew-dev-tools:
    type: git
    url: https://github.com/Homebrew/homebrew-dev-tools
    version: 6cc02b0322991775d82e5483b782aa6211664091
  homebrew/homebrew-dupes:
    type: git
    url: https://github.com/Homebrew/homebrew-dupes
    version: 36b6b7cd76a482319611eeb71e51f3134018a21c
...
~~~

**Comment by MikeMcQuaid** [comment]
I think there's two things here:

1. allowing installation bottles of arbitrary versions
2. be able to rebuild bottles reproducibly

I think it's worth treating them separately as neither has a hard requirement on the other. We could have a minimal version that embeds the formula to at least allow them to be installed.

**Comment by sjackman** [comment]
I've opened a evolution PR: https://github.com/Homebrew/brew-evolution/pull/6
