### ISSUE TITLE
Can't install atlassian-cli

### ISSUE THREAD

**Issue by nnnikolay** [Homebrew/brew#5891]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 2.0.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 417a16fbafa97a5740d355ed33bfbfd2823452e7
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 13f7d78c69690373c340a86f3213239e8d69ca06
Core tap last commit: 77 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/n/Library/Logs/Homebrew
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_192
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
```

# What you were trying to do (and why)

`brew install atlassian-cli`

# What happened (include command output)

The package was not installed instead of that I saw the following output

```
=> Downloading https://bobswift.atlassian.net/wiki/download/attachments/16285777/atlassian-cli-8.0.0-distribution.zip
==> Downloading from https://api.media.atlassian.com/file/382b5b89-4988-4c1d-89f2-fa7a9746e89a/binary?token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxYzZjOWRlMy05NDAyLTQwZjItYTM1YS0zYmM3MzVjOGQzNWMiLCJhY2Nlc3MiOnsidX
######################################################################## 100.0%
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - lib
```

# What you expected to happen

Expected to have the package to be installed

# Step-by-step reproduction instructions (by running `brew` commands)

just need to run `brew install atlassian-cli`

**Comment by MikeMcQuaid** [comment]
And please provide your `brew doctor` and the `gist-logs` output, thanks.
