### ISSUE TITLE
[BUG] brew.sh (Homebrew 2.0.5-dirty)

### ISSUE THREAD

**Issue by AndrianD** [Homebrew/brew#5896]
here is the context:
I run this command:
brew update && brew upgrade && brew cleanup
and at the end of execution it gives me these error in console.
`
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in  parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in  parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:565:in  tap_migrations'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:287:in  block in migrate_tap_migration'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:285:in  each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:285:in  migrate_tap_migration'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:126:in  each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:126:in  update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in  <main>'
`
Thank you very much for your help

**Comment by SMillerDev** [comment]
Could you fill out the [issue template](https://github.com/Homebrew/brew/issues/new?template=Reproducible-Bug-Report.md) please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
