### ISSUE TITLE
Update should be more resilient to local changes

### ISSUE THREAD

**Issue by UniqMartin** [Homebrew/brew#590]
`brew update` does a decent job moving aside uncommitted local modifications. However, if local modifications are committed to `master`, results can be less than ideal, as the update in this case is basically a glorified `git rebase`. Depending on the nature of the local changes, they may:

- disappear (if they have been merged to `origin/master`),
- remain (changes that don't conflict with upstream changes), or
- cause a merge conflict (demonstrated below, IMO most problematic case).

*Note:* The exact steps below might not be reproducible at a later time, as the PR used here for demonstration purposes is still in progress and might change in a way that no longer causes a merge conflict. But any local change that would create a conflict will do.

Here's a transcript of commands and corresponding output (slightly trimmed) that shows the undesirable behavior (notice the merge conflict near the bottom of the `brew update` output and the resulting mid-rebase state of the working copy):

```console
$ git -C "$(brew --repo homebrew/core)" reset --hard b4ac4e50
HEAD is now at b4ac4e50 keybase: update 1.0.16 bottle.

$ brew pull https://github.com/Homebrew/homebrew-core/pull/1200
==> Fetching patch
Patch: https://github.com/Homebrew/homebrew-core/pull/1200.patch
==> Applying patch
Applying: boost 1.61.0
Applying: boost-bcp 1.61.0
Applying: boost-python 1.61.0
Applying: boost boost-python: Fix test for non-standard homebrew location
Applying: Bump revision to require build against updated boost
Warning: boost-bcp has a bottle: do you need to update it with --bottle?
Warning: boost-python has a bottle: do you need to update it with --bottle?
Warning: boost has a bottle: do you need to update it with --bottle?
Warning: cucumber-cpp has a bottle: do you need to update it with --bottle?
Warning: folly has a bottle: do you need to update it with --bottle?
Warning: freeling has a bottle: do you need to update it with --bottle?
Warning: ledger has a bottle: do you need to update it with --bottle?
Warning: metaproxy has a bottle: do you need to update it with --bottle?
Warning: mkvtoolnix has a bottle: do you need to update it with --bottle?
Warning: ncmpcpp has a bottle: do you need to update it with --bottle?
Warning: source-highlight has a bottle: do you need to update it with --bottle?
Warning: uhd has a bottle: do you need to update it with --bottle?
==> Patch closes issue #1200
==> Patch changed:
 Formula/boost-bcp.rb        |  4 ++--
 Formula/boost-python.rb     |  6 +++---
 Formula/boost.rb            | 35 +++--------------------------------
 Formula/cucumber-cpp.rb     |  1 +
 Formula/folly.rb            |  1 +
 Formula/freeling.rb         |  2 +-
 Formula/ledger.rb           |  2 +-
 Formula/metaproxy.rb        |  2 +-
 Formula/mkvtoolnix.rb       |  1 +
 Formula/ncmpcpp.rb          |  2 +-
 Formula/source-highlight.rb |  2 +-
 Formula/uhd.rb              |  2 +-
 12 files changed, 17 insertions(+), 43 deletions(-)

$ brew update --verbose
Fetching /opt/brewery/dummy...
Fetching /opt/brewery/dummy/Library/Taps/homebrew/homebrew-core...
Updating /opt/brewery/dummy...
Current branch master is up to date.

Updating /opt/brewery/dummy/Library/Taps/homebrew/homebrew-core...
[…snip…]
First, rewinding head to replay your work on top of it...
Applying: boost 1.61.0
Using index info to reconstruct a base tree...
M	Formula/boost.rb
Falling back to patching base and 3-way merge...
Auto-merging Formula/boost.rb
CONFLICT (content): Merge conflict in Formula/boost.rb
error: Failed to merge in the changes.
Patch failed at 0001 boost 1.61.0
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".


Updated 1 tap (homebrew/core).
[…snip…]

$ git -C "$(brew --repo homebrew/core)" status
rebase in progress; onto 54c5531e
You are currently rebasing branch 'master' on '54c5531e'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:   Formula/boost.rb

no changes added to commit (use "git add" and/or "git commit -a")
```

This behavior is independent of whether `HOMEBREW_DEVELOPER` is set or not. The only difference, if it is set, is this additional piece of output (immediately preceding “Updated 1 tap (homebrew/core).”):

```console
Error: /opt/brewery/dummy/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:17: syntax error, unexpected <<, expecting keyword_end
<<<<<<< 54c5531edd987f39d458297f90790a49166841d7
  ^
/opt/brewery/dummy/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:32: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/opt/brewery/dummy/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:33: no .<digit> floating literal anymore; put 0 before dot
>>>>>>> boost 1.61.0
                   ^
/opt/brewery/dummy/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:33: syntax error, unexpected tINTEGER, expecting '('
```

**Subsequent invocations of `brew update`.** Despite the in-progress rebase and the corresponding local changes, subsequent invocations of `brew update` won't be able to overcome this. [This code](https://github.com/Homebrew/brew/blob/0be204aab5878284d8466b141a82d56a166abe7b/Library/Homebrew/cmd/update.sh#L211-L224) will abort the rebase, leaving no local changes to be stashed, but will also return `master` to a state where it has still diverged from `origin/master`. The following `git rebase` will fail in the exact same way if no rebase-relevant changes have happened to the upstream branch.

**Comment by MikeMcQuaid** [comment]
My proposed solution would be to demand `HOMEBREW_DEVELOPER` fix the merge conflict before allowing another `brew update` and reset `master` to `origin/master` and refuse to run `brew update` on non-`master` branches for other folks.

**Comment by MikeMcQuaid** [comment]
Alternatively: make the `master` assumption for everyone and basically refuse to let people `brew update` with a non-`origin/master` `master` branch (which is probably good `git` practise anyway).

**Comment by UniqMartin** [comment]
Yep, something along those lines. Making sure `master` hasn't diverged from `origin/master` is a good practice and something we should enforce.

If we wanted to be extra nice, we can check if the local `master` has diverged ([we already do that here](https://github.com/Homebrew/brew/blob/0be204aab5878284d8466b141a82d56a166abe7b/Library/Homebrew/cmd/update.sh#L230)) and auto-create a branch for the user if that's the case before doing `git checkout -B master origin/master`. This shouldn't be too hard to do and would be equally nice like stashing away local modifications. (I'm also sympathetic to completely refusing to update, but this might be a support burden. I'm definitely in favor of bailing if the “offender” has `HOMEBREW_DEVELOPER` set.)

**Comment by MikeMcQuaid** [comment]
Creating a separate branch feels sensible; `preupdate` or something and refusing for `HOMEBREW_DEVELOPER` folks. This could also simplify (and perhaps speed up) our update a fair bit by making it do a lot less.

**Comment by ilovezfs** [comment]
@UniqMartin this is why I set HOMEBREW_MERGE=1, which basically makes these problems go away naturally.

**Comment by MikeMcQuaid** [comment]
@ilovezfs If it's definitely better: I'm open to setting the default back to how it was.

**Comment by ilovezfs** [comment]
@MikeMcQuaid I don't think it can be fairly characterized as "definitely better."

It's a trade-off between more automation and potentially annoying silent merge commits, or less automation and all conflicts deliberately blocking. To achieve more automation with rebase, and put them on an even playing field, I believe we'd have to do a `rebase -Xtheirs` strategy, which I'm afraid would do more harm than good.

Personally, I prefer the silent merge commits and more automation because it means I can usually delay dealing with the conflict until it's convenient.

**Comment by MikeMcQuaid** [comment]
Given we've got most users on tags now and we force-checkout of the exact tag commit I think it's worth closing this out.
