### ISSUE TITLE
`brew tap-new` is not sufficiently documented

### ISSUE THREAD

**Issue by remorse** [Homebrew/brew#5901]
- [x] are reporting a bug others will be able to reproduce and not asking a question.
- [x] ran a `brew` command and reproduced the problem?
- [x] ran `brew update` and can still reproduce the problem?

# What you were trying to do (and why)

The provided formula for `groff` is broken for my purposes, and apparently will not be fixed, so I was trying to create a new "tap" (as I was told to do) to replace the existing `groff` formula with one that is sufficient.

# What happened (include command output)

I ran:

```
buxtehude:brewtapfoo rem16$ brew tap-new pukku/groff
buxtehude:brewtapfoo rem16$
```

I also ran:

```
buxtehude:brewtapfoo rem16$ brew help tap-new
Usage: brew tap-new user/repo

Generate the template files for a new tap.

    -v, --verbose                    Make some output more verbose.
    -d, --debug                      Display any debugging information.
    -h, --help                       Show this message.
buxtehude:brewtapfoo rem16$
```

# What you expected to happen

I expected:

- the tap template to be created in the directory I was currently in
- or to be told where it *was* created (I did eventually discover where it was, but only by running `find / -name "*groff*" -print`, and then looking at a *lot* of paths).

I also expected either the `README.md` file or the man page to describe what I need to do to make this tap available via github (I suppose?). I think, based on things that people have posted in other bug reports about non-related issues, that I'm now supposed to create a repository on GitHub (under the appropriate account) named `homebrew-groff`, and then add it as a new remote origin to the existing directory, but maybe I'm wrong?

**Comment by MikeMcQuaid** [comment]
> * or to be told where it _was_ created (I did eventually discover where it was, but only by running `find / -name "*groff*" -print`, and then looking at a _lot_ of paths).

This will be addressed by https://github.com/Homebrew/brew/pull/5912.

> I also expected either the `README.md` file or the man page to describe what I need to do to make this tap available via github (I suppose?). I think, based on things that people have posted in other bug reports about non-related issues, that I'm now supposed to create a repository on GitHub (under the appropriate account) named `homebrew-groff`, and then add it as a new remote origin to the existing directory, but maybe I'm wrong?

Yes, that's correct. https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap provides more information but creating a repository on GitHub is documented by them and not us.

---

In future please fully fill out the formula template or your issue may be closed without being addressed.

**Comment by remorse** [comment]
I've rewritten this response several times, but if you think that the documentation there is clear, I don't think there's anything I can say that will change your mind.

I will suggest that the newly created tap should be initialized as a git repository by default, because I spent fifteen minutes trying to guess what I needed to `git init` when the folder I finally found wasn't already a git repo.

**Comment by MikeMcQuaid** [comment]
> I've rewritten this response several times, but if you think that the documentation there is clear, I don't think there's anything I can say that will change your mind.

I cannot state whether you find the documentation clear or unclear. I can state that 1) you had not made any statements that provide a "gotcha, the docs need to say X" realisation and 2) that just because you found the documentation/command confusing it does not necessitate a change. In general we're unlikely to make changes based on the feedback of a single individual. If you can submit a PR: that's easier to evaluate whether it's an improvement to the documentation or not.

> I will suggest that the newly created tap should be initialized as a git repository by default

This might be a good idea. I'm wondering whether it would be annoying to those who don't want it to be a Git repository but they can always remove `.git` if desired. @Homebrew/maintainers: any thoughts?

**Comment by sjackman** [comment]
I'm in favour of creating an empty `.git` repo by default. If we do that, perhaps we should also provide instructions on how to add a remote and push it to GitHub?
