### ISSUE TITLE
Roll back the last update.

### ISSUE THREAD

**Issue by ashleyharvey** [Homebrew/brew#5918]
# A detailed description of the proposed feature

The ability to run a command to roll back the last (x) update(s) to a previous state.
Say I run `brew update && brew upgrade`, and it updates five packages, three of which are dependencies.  I have no way of knowing which version(s) I had, which package(s) the dependencies are for, and then which are the actual packages that I use, are being updated, easily.

# The motivation for the feature

So, I ran `brew update && brew upgrade`, and Brew updated 14 packages, including bash.  After that, my CPU and RAM usage went up, my terminal got real slow, and a bunch of things I was working on slowed to a crawl.  I narrowed the issue down to my terminal, made sure to restart it and make sure I was using the new bash version, then moved on to restarting my machine when that didn't take care of it.  I am still seeing issues, and the fastest way for me to sort this out would be to roll-back the changes that Brew made, because I'm fairly certain that's what kicked this off.  Now, of those 14 packages, I'm not sure exactly which is/are causing the issue, but I have suspicions.  I wish I knew what my previous version numbers were for those 14 packages, so that I could roll them all back and pin them, and update them one-by-one by unpinning them in order to find the issue.

# How the feature would be relevant to at least 90% of Homebrew users

Well, this is literally the first time in years of using Brew across multiple machines I've ever had an issue, and technically I can argue that it's not Brew's fault at all.  I can't even argue that it would be useful for 90% of Homebrew users, because I don't know that that's even true.  But the feature is self-evidently useful enough that it needs no extra justification.

# What alternatives to the feature have been considered

I mean, I suppose I could write a shell script to run `brew leaves`, then loop through all of the packages, and query brew for their dependencies, then take all of those and list out versions -- but that would be tricky at best because each app implements version queries differently.  Maybe there's a way to get installed-version numbers out of Brew and dump those out to a log file before each update.

There is also `brew list -l -t -r` which is how I figured out which packages were most recently installed -- but there's no way to know which versions I came from, so rolling them back manually is going to be a serious pain.

**Comment by vitorgalvao** [comment]
> But the feature is self-evidently useful enough that it needs no extra justification.

I won’t be the one to make the final decision, but I disagree. The point of that question (“How the feature would be relevant to at least 90% of Homebrew users”) is “will enough people benefit from the feature to justify that the core maintainers spend their limited volunteer time working on it?”.

In this case, the answer is clearly “no”. By your own admission this seldom happens, which means every other planned feature is more important than this. This is a nice-to-have for when everything else is done. At this moment, it is likely not worth pursuing.

**Comment by ashleyharvey** [comment]
You may well be right.

I would argue that it happening seldomly doesn't make it less important necessarily.

But I appreciate the comment and you have a valid point. I guess we'll see how they evaluate it.

**Comment by vitorgalvao** [comment]
> I would argue that it happening seldomly doesn't make it less important necessarily.

But it does make it less *urgent*. And non-urgent issues get stale, which get closed.

**Comment by MikeMcQuaid** [comment]
Sorry, this would require an enormous amount of work to be able to make it work how you describe and would be very rarely used so doesn't justify the effort right now. Thanks for the issue regardless, though.
