### ISSUE TITLE
brew update does not work

### ISSUE THREAD

**Issue by khvn12** [Homebrew/brew#5927]
# What you were trying to do (and why)

`brew update`

# What happened (include command output)

I cant update brew.

<details>
  <summary>Command output</summary>
  <pre>
  
  ==> Installing dependencies for curl: pkg-config and openssl
==> Installing curl dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
Already downloaded: /home/kanbanmediana/.cache/Homebrew/downloads/5bdbf3b3fdadaf72744884b98b74a2ff887bd63a20b246f811a222a146ad7b64--pkg-config-0.29.2.tar.gz
==> ./configure --prefix=/home/kanbanmediana/.linuxbrew/Cellar/pkg-config/0.29.2_1 --disable-host-tool --with-internal-glib --with-pc-path=/home/kanbanmediana/.linuxbrew/lib/pkgconfig:/home/kanbanmedia
Last 15 lines from /home/kanbanmediana/.cache/Homebrew/Logs/pkg-config/01.configure:
2019-03-26 11:02:54 +0500

./configure
--disable-debug
--prefix=/home/kanbanmediana/.linuxbrew/Cellar/pkg-config/0.29.2_1
--disable-host-tool
--with-internal-glib
--with-pc-path=/home/kanbanmediana/.linuxbrew/lib/pkgconfig:/home/kanbanmediana/.linuxbrew/share/pkgconfig:/home/kanbanmediana/.linuxbrew/Homebrew/Library/Homebrew/os/linux/pkgconfig

READ THIS: https://docs.brew.sh/Troubleshooting
  
  </pre>
</details>

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
