### ISSUE TITLE
Replace the term ¨Return key¨ to ¨Enter key¨ on the Linux/Windows installed.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Homebrew/brew#5929]
# A detailed description of the proposed feature

That line.
![image](https://user-images.githubusercontent.com/13170204/55005117-b97e3900-4fdb-11e9-9d45-07d25a5eca4c.png)

# The motivation for the feature

Well, I will be honest, I´ve never used a macintosh, and tho, aren´t familiar with those different keys, and names. 

# How the feature would be relevant to at least 90% of Homebrew users

Oh... Well, I sadly doubt that they´re 90% of Homebrew users, but since it concern the separate installer for Linux in my case, It will surely be less confusing for more than 90% of those Linux/Windows users.

# What alternatives to the feature have been considered

Searching what a ¨a return key¨ was.

**Comment by MikeMcQuaid** [comment]
I use a Windows PC (almost) daily. Return key and Enter key are often used interchangeably in documentation and your keyboard will almost certainly have both keys on them.
