### ISSUE TITLE
brew analytics off requires a git repo

### ISSUE THREAD

**Issue by dimo414** [Homebrew/brew#5933]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Trying to disable analytics, as discussed [here](https://github.com/Homebrew/brew/blob/master/docs/Analytics.md#opting-out)

# What happened (include command output)

Got an error related to git:

<details>
  <summary>Command output</summary>
  <pre>
$ brew analytics off
error: could not lock config file /Users/dimo414/homebrew/.git/config: No such file or directory
Error: Failure while executing; `git config --file=/Users/dimo414/homebrew/.git/config --replace-all homebrew.analyticsdisabled true` exited with 255.
  </pre>
</details>

# What you expected to happen

Analytics to be disabled

# Step-by-step reproduction instructions (by running `brew` commands)

* Install homebrew using the [untar instructions](https://docs.brew.sh/Installation#untar-anywhere) (i.e. without a git repo)
* run `brew update`
* run `brew analytics off`

---

<details>
  <summary>config and doctor output</summary>
  <pre>
$ brew config
HOMEBREW_VERSION: >=1.7.1 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 581e64c67e8ca4641150c2c72f84ffc489f9af03
Core tap last commit: 24 minutes ago
HOMEBREW_PREFIX: /Users/dimo414/homebrew
HOMEBREW_REPOSITORY: /Users/dimo414/homebrew
HOMEBREW_CELLAR: /Users/dimo414/homebrew/Cellar
HOMEBREW_LOGS: /Users/dimo414/Library/Logs/Homebrew
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1, 9
macOS: 10.14.3-x86_64
CLT: N/A
Xcode: 10.0

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this unsupported configuration.

Warning: Your Xcode (10.0) is outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.
  </pre>
</details>

**Comment by colindean** [comment]
@dimo414: As a workaround, you can set `HOMEBREW_NO_ANALYTICS` envvar, perhaps by placing `export HOMEBREW_NO_ANALYTICS=1` in `~/.bash_profile`.

Others: [A quick search](https://github.com/Homebrew/brew/search?q=%22git+config%22&unscoped_q=%22git+config%22) leads me to believe that disabling analytics is the only usage of `git config` that is unrelated to actual use of git, with perhaps another exception being a Homebrew developer mode feature [here](https://github.com/Homebrew/brew/blob/eece1f00f029e9ffcf07976dd0e001e6343ce4e1/Library/Homebrew/brew.rb#L72).

**Comment by jonchang** [comment]
The first `brew update` will initialize a git repo.

I think we would welcome a pull request for `cmd/analytics.rb` that checks that a git repo is initialized, and if it isn't, runs `HOMEBREW_NO_ANALYTICS=1 brew update` then sets the proper git config variable.

**Comment by MikeMcQuaid** [comment]
Closing but we'll consider accepting a PR for this as the untar instructions are not the support installation method.
