### ISSUE TITLE
Fish: Recommend universal variable usage in prepend_path_in_profile

### ISSUE THREAD

**Issue by slice** [Homebrew/brew#5934]
# What should be done?

I feel that it would be better to recommend setting `fish_user_paths` via `set -U` instead of echoing a line to `~/.config/fish/config.fish`, like this:

```
set -U fish_user_paths "/usr/local/opt/ruby/bin" $fish_user_paths
```

instead of:

```
echo 'set -g fish_user_paths "/usr/local/opt/ruby/bin" $fish_user_paths' >> ~/.config/fish/config.fish
```

# Why?

Fish has universal variables, which seamlessly update between live shells and automatically persist to disk. I feel like this could better be taken advantage of in the `prepend_path_in_profile` function. Instead of having the user echo a line to their config, they can just `set -U fish_user_paths [...]`.

As far as I know, using `set -U` yields the same behavior as echoing to `config.fish`. Perspective from a more experienced Fish user would be appreciated! 🐟 

Edit: [It's also the recommended way to add to path according to Fish's tutorial.](https://fishshell.com/docs/current/tutorial.html#tut_path)

**Comment by MikeMcQuaid** [comment]
We'd accept a PR with this change.

Please always fill out the issue template, thanks.
