### ISSUE TITLE
 brew-perms.sh: script to make brew multi-user

### ISSUE THREAD

**Issue by UnixJunkie** [Homebrew/brew#5935]
Hello,

Shouldn't we have such a script in here:
```
#!/bin/sh
# Configure homebrew permissions to allow multiple users on MAC OSX.
# Any user from the admin group will be able to manage the homebrew and cask installation on the machine.

# allow admins to manage homebrew's local install directory
sudo chgrp -R admin /usr/local/*
sudo chmod -R g+w /usr/local/*

# allow admins to homebrew's local cache of formulae and source files
sudo chgrp -R admin /Library/Caches/Homebrew
sudo chmod -R g+w /Library/Caches/Homebrew

# if you are using cask then allow admins to manager cask install too
sudo chgrp -R admin /opt/homebrew-cask
sudo chmod -R g+w /opt/homebrew-cask
```

Inspired from https://gist.github.com/jaibeee/9a4ea6aa9d428bc77925

Regards,
F.

**Comment by MikeMcQuaid** [comment]
No. Setting up permissions is the job of the installer. We'll accept PRs to fix cases where the installer is incorrect.

Also, from the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

**Comment by UnixJunkie** [comment]
It seems that there are issues in a multi-user context.
So some users ended-up with that kind of script.

**Comment by MikeMcQuaid** [comment]
> It seems that there are issues in a multi-user context.

If there are issues with the installer which configures permissions: an issue can be created on that repo with a reproducible test-case to demonstrate the problem or, ideally, a pull request.

Additionally, the multi-user setup is unusual amongst Homebrew users (particularly on macOS) so is not something that's critical to support perfectly (although we do our best).

**Comment by UnixJunkie** [comment]
Well, Mac OS X is a server operating system, so in some places it is used on shared computers.
I'll try to send more info, and maybe open a new issue, when I will see the symptoms in the future (some permission denied things).
Currently, I reinstalled brew and all packages because I was in a hurry.
But I don't feel that's how a unix software is supposed to be used.

**Comment by MikeMcQuaid** [comment]
> Well, Mac OS X is a server operating system, so in some places it is used on shared computers.

In some places: yes. In most places: no.

> and maybe open a new issue

Please instead open a pull request, thanks.
