### ISSUE TITLE
Provide a way to obtain the install path of an installed pf

### ISSUE THREAD

**Issue by ecerulm** [Homebrew/brew#5946]
# A detailed description of the proposed feature

Currently to obtain the installation path of `asciidoctor` I need to do something like this:

     echo $(brew --cellar asciidoctor)/$(brew info --json asciidoctor | jq -r '.[0].installed[0].version')

which requires `bash` and `jq`  

# The motivation for the feature

This would make easier for scripts that need access to the installation path of brew packages. 

For example I want to have a script that does

```
brew install asciidoctor
GEM_HOME= $(brew --cellar asciidoctor)/$(brew info --json asciidoctor | jq -r '.[0].installed[0].version') gem install asciidoctor-diagram
GEM_HOME= $(brew --cellar asciidoctor)/$(brew info --json asciidoctor | jq -r '.[0].installed[0].version') gem install asciidoctor-coderay
...
```

It would me much easier if there was a `brew info --installpath asciidoctor` that gives the path to the currently installed version. 

# How the feature would be relevant to at least 90% of Homebrew users

wow, 90% of the users. There is no way this would be relevant to 90% of the users. But it would be useful during troubleshooting and enable some powerusers to script more. 

# What alternatives to the feature have been considered

     echo $(brew --cellar asciidoctor)/$(brew info --json asciidoctor | jq -r '.[0].installed[0].version')

**Comment by colindean** [comment]
Does `brew --prefix asciidoctor` meet your needs?

**Comment by MikeMcQuaid** [comment]
> Does `brew --prefix asciidoctor` meet your needs?

Assuming it does.
