### ISSUE TITLE
[Linux] Wrong GCC is picked as default compiler

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/brew#5953]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

If any gcc newer than gcc-5 is installed (such as `gcc@8`), the newer gcc will be picked as the default compiler. This would cause other formulae (if being built from source) to be linked to the libraries from `gcc@*`. As a result, if `gcc@*` were later uninstalled, these formulae may not work probably. We should always use `gcc` formula as the default compiler.

This issue is due to the downstream code https://github.com/Linuxbrew/brew/pull/676 is not merged back into Homebrew/brew.

<details>
  <summary>brew config</summary>
  <pre><code>$ brew config
HOMEBREW_VERSION: 2.0.6-61-g372a8d4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 372a8d45325f53355c36c0f1b264b72cc186bcb0
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 20b90d90b178b950c36ad1be71310eb53e198e71
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /home/comp/chengxu/usr
HOMEBREW_REPOSITORY: /home/comp/chengxu/usr
HOMEBREW_CELLAR: /home/comp/chengxu/usr/Cellar
HOMEBREW_CACHE: /tmp/chengxu/cache/homebrew
HOMEBREW_DEVELOPER: true
HOMEBREW_FORCE_BREWED_GIT: true
HOMEBREW_FORCE_VENDOR_RUBY: true
HOMEBREW_LOGS: /tmp/chengxu/cache/homebrew/logs
HOMEBREW_NO_ANALYTICS: true
HOMEBREW_NO_AUTO_UPDATE: true
HOMEBREW_SANDBOX: true
HOMEBREW_SYSTEM_CURL_TOO_OLD: 1
CPU: 24-core 64-bit westmere
Homebrew Ruby: 2.3.7 => /home/comp/chengxu/usr/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 8.0 build 800
Git: 2.21.0 => /home/comp/chengxu/usr/opt/git/bin/git
Curl: 7.64.0 => /home/comp/chengxu/usr/opt/curl/bin/curl
Java: 1.8.0_201
Kernel: Linux 2.6.32-754.10.1.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.10 (Final) (Final)
Host glibc: 2.14
/usr/bin/gcc: 4.4.7
glibc: 2.23
gcc: 5.5.0_4
xorg: N/A
</code></pre>
</details>

**Comment by MikeMcQuaid** [comment]
> This issue is due to the downstream code [Linuxbrew/brew#676](https://github.com/Linuxbrew/brew/pull/676) is not merged back into Homebrew/brew.

@xu-cheng Good catch, thanks! Could you open a PR for that here? Thanks again!
