### ISSUE TITLE
Bash Completion script gives error

### ISSUE THREAD

**Issue by dev-mansonthomas** [Homebrew/brew#5955]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [N/A] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Adding Bash completion support following the instructions here : 
https://docs.brew.sh/Shell-Completion

```
if type brew &>/dev/null; then
  for COMPLETION in $(brew --prefix)/etc/bash_completion.d/*
  do
    [[ -f $COMPLETION ]] && source "$COMPLETION"
  done
  if [[ -f $(brew --prefix)/etc/profile.d/bash_completion.sh ]];
  then
    source "$(brew --prefix)/etc/profile.d/bash_completion.sh"
  fi
fi
```

# What happened (include command output)

I'm adding the code to my .bash_profile and open a new term.
And then a lot of command not found error is displayed and some syntax error.

**Note:** the instruction says to add it to .bashrc, but on my freshly reinstalled macbook with Mojave, **.bashrc is not read**.

See attached file for the output (long output)

Here are some env info : 

```
[21:30] tom@toms-typewriter:~$ brew config
HOMEBREW_VERSION: 2.0.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 649d1427f5fe41323c436608f5c21513f8f34f71
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b196924abf02be1b43bcfbe5d023a72882648943
Core tap last commit: 31 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/tom/Library/Logs/Homebrew
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.4-x86_64
CLT: 10.2.0.0.1.1552586384
Xcode: 10.2
CLT headers: 10.2.0.0.1.1552586384
[21:30] tom@toms-typewriter:~$

===============================================
===============================================

[21:30] tom@toms-typewriter:~$ bash --version
GNU bash, version 5.0.3(1)-release (x86_64-apple-darwin18.2.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[21:31] tom@toms-typewriter:~$

===============================================
===============================================

[21:31] tom@toms-typewriter:~$ brew info bash
bash: stable 5.0.3 (bottled), HEAD
Bourne-Again SHell, a UNIX command interpreter
https://www.gnu.org/software/bash/
/usr/local/Cellar/bash/5.0.3 (150 files, 9.4MB) *
  Poured from bottle on 2019-03-26 at 16:09:45
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/bash.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
In order to use this build of bash as your login shell,
it must be added to /etc/shells.
==> Analytics
install: 30,271 (30 days), 96,825 (90 days), 228,122 (365 days)
install_on_request: 24,250 (30 days), 76,571 (90 days), 180,997 (365 days)
build_error: 0 (30 days)
[21:31] tom@toms-typewriter:~$
[bash_completion.log](https://github.com/Homebrew/brew/files/3024436/bash_completion.log)

===============================================
===============================================

[21:31] tom@toms-typewriter:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
[21:34] tom@toms-typewriter:~$

```

# What you expected to happen

my new term is opening silently and bash completion is available.

# Step-by-step reproduction instructions (by running `brew` commands)

Paste the code from the documentation in .bash_profile, save, open a new term, notice the errors.

**Comment by MikeMcQuaid** [comment]
> See attached file for the output (long output)

There is no attached file.

We'll accept pull requests to improve this but the instructions work for me and we cannot support every user with figuring this out. I'll adjust the documentation so it says `.bash_profile`.

**Comment by dev-mansonthomas** [comment]
Hi Mike,

weird, I've used the drag & drop feature... I must have missed something

Here is another try: 
[bash_completion.log](https://github.com/Homebrew/brew/files/3025432/bash_completion.log)

In my previous setup (I'm setting up a new mac from scratch), I had only this as instruction.

```
# brew bash completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

```

I don't know what the loop is supposed to do in the current documentation.
Also, I don't understand why this piece of code is not within the script (and detect the current shell)

It's better to have a simple include vs a complex one.

Strangely, the file is also still there: 

```
[13:21] tom@toms-typewriter:~$ file  /usr/local/etc/bash_completion
/usr/local/etc/bash_completion: UTF-8 Unicode text, with very long lines
[13:21] tom@toms-typewriter:~$
```

**Comment by MikeMcQuaid** [comment]
I do not see this issue so you'll need to figure it out yourself, sorry.

**Comment by dev-mansonthomas** [comment]
my system do not have the "have" function or command.

It seems that all files in "/usr/local/etc/bash_completion.d" start with 

have _command name_

Example: 
```
# wol(1) completion

have wol &&
_wol()
...
```

There's a post on stack :
https://stackoverflow.com/questions/12874920/have-keyword-for-bash-completion

So I'm not sure why I don't have this function, and you do.
For sure, I've got a fresh system, I'm not sure on what you're testing.

Can you check where it is defined on your system ?

**Comment by MikeMcQuaid** [comment]
Sorry, you'll need to figure this out yourself.

**Comment by MikeMcQuaid** [comment]
Or our Discourse (https://discourse.brew.sh) may have people who will debug this with you.
