### ISSUE TITLE
Documentation doesn't describe terminology

### ISSUE THREAD

**Issue by dovecode** [Homebrew/brew#5957]
# A detailed description of the proposed feature

Documentation should be amended with information about what the terminology used in brew actually refers to.

# The motivation for the feature

I have used brew for years and I still don't quite understand what a cask or a tap or a fomula is. It makes it a black box where I just know which magic commands that I need to invoke in order to install, update, and remove features.

# How the feature would be relevant to at least 90% of Homebrew users

90% of users are not maintainers of the project, so they would not know other than through reading 3rd-party blogs or Stackoverflow posts. Definition of terminology should be established by the project owners. Especially when it is non-standard.

# What alternatives to the feature have been considered

Not sticking to a brew terminology. I mean, that's really the underlying problem. We're trying to retrofit one domain language to another.

**Comment by MikeMcQuaid** [comment]
https://docs.brew.sh/Formula-Cookbook#homebrew-terminology

**Comment by dovecode** [comment]
The terminology is a preface to the "Formula Cookbook", which in a section a section of the documentation for contributors.

Am I the only one seeing a problem with that?

**Comment by MikeMcQuaid** [comment]
> Am I the only one seeing a problem with that?

Probably not but I'm not sure I see any actionable outcomes from your request. We cannot at this stage rename everything (it would make it confusing to all existing users) and we have documented this and it shows up for a search of "homebrew mac terminology".

**Comment by dovecode** [comment]
It could be a topic in the Users section of the documentation. As of now, there is no description of what these items mean. In fact, the first item in the list at https://docs.brew.sh/ is a link to the man page, which makes little sense without an understanding of the terminology.

**Comment by MikeMcQuaid** [comment]
> In fact, the first item in the list at https://docs.brew.sh/ is a link to the man page, which makes little sense without an understanding of the terminology.

I disagree.

> 1. A list of terms from "Troy Prog Blog"

Which defines the terminology almost completely correct.





> 2\. The homebrew FAQ, which has no mention of terminology

https://docs.brew.sh/FAQ#is-there-a-glossary-of-terms-around which uses the word "terminology"

> 3\. "Formula Cookbook", which as an end-user gives me no hints as to this is where I should go to look for terminology. I mean, I don't even know what a "Formula" is at this piont...

Search for "terminology" on the page (as hinted by the search result).



> That should probably tell you that it is not in a good place for an end-user...

No, it tells me _you_ do not think it's in a good place and not that the majority of users agree with you.



> It could be a topic in the Users section of the documentation.

We'd consider a PR that moved this from the Formula Cookbook to that section.

**Comment by dovecode** [comment]
The fact that you think the man page makes sense without understanding the terminology probably is a consequence of you already having a great first-hand understanding of said terminology. The command listed is:

    install formula:
        Install formula.

That's it. What's a formula? It's something I install.

Also, I'd argue that the fact that Troy felt it necessary to create his own list of terms at a time where the terminology list in the contributor section already existed should speak to the fact that it might not be located and descriped all too well.

Anyway, I can see that there is no way I can convince you that it is important that users understand the non-standard brewery domain terminology used in homebrew.

> We'd consider a PR that moved this from the Formula Cookbook to that section.

I'd love to, but your dismissiveness makes me think that this would just be a waste of time. I don't want to spend hours on a PR that then festers for months because you think users' understanding of terminology isn't important...

**Comment by MikeMcQuaid** [comment]
> Anyway, I can see that there is no way I can convince you that it is important that users understand the non-standard brewery domain terminology used in homebrew.

There's not no way but you've been unsuccessful so far in convincing me that for Homebrew to be useful to a user you need to understand our definition of "formula".

> I'd love to, but your dismissiveness makes me think that this would just be a waste of time.

What you decide to do is up to you. I've spent my weekend discussing this issue with you. "Dismissiveness" would be to ignore what you are saying rather than spend my time pointing out where you've said things that aren't accurate.

> I don't want to spend hours on a PR that then festers for months because you think users' understanding of terminology isn't important...

If you can find a single PR in a project I currently actively maintain in which I've ignored a request for review on a PR for months at a time I'll be very surprised. If you can find any PR in this project that has gone ignored for months (without unaddressed feedback) I'll also be surprised. I don't appreciate the insinuation here and I'd recommend against throwing around these sort of accusations on open source projects. Locking this because this conversation has become unproductive: I'll happily review a PR.
