### ISSUE TITLE
Not able to upgrade or change permission

### ISSUE THREAD

**Issue by stefdelec** [Homebrew/brew#596]
- [ ] Ran `brew update` and retried your prior step?

```
Error: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. For example, upgrading
to OS X El Capitan has been known to do this. Some versions of the
"InstantOn" component of Airfoil or running Cocktail cleanup/optimizations
are known to do this as well.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami):admin /usr/local
```

**`chown -R $(whoami):admin /usr/local`**:

```
chown: /usr/local/share/man/whatis: Operation not permitted
chown: /usr/local: Operation not permitted
```

- [ ] Ran `brew doctor`:

seems to work fine.

- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

```
chown: /usr/local/share/man/man1/xsd.1: Operation not permitted
chown: /usr/local/share/man/man1/xsp.1: Operation not permitted
chown: /usr/local/share/man/whatis: Operation not permitted
chown: /usr/local: Operation not permitted
```

### Bug reports:

Any way, I don't know where it comes from, but I can't update brew, so I can't install .Net...
https://www.microsoft.com/net/core#macos
Any help? I am lost.

**Comment by UniqMartin** [comment]
(I reformatted your message a bit to make it more readable. I hope that's okay with you.)

I suspect the problem in your case is that you haven't exactly followed our instructions. Could it be that you have issued the `chown` command without prefixing them with `sudo`?

**Comment by stefdelec** [comment]
Thanks! that's it!!

**Comment by UniqMartin** [comment]
I'm glad this worked. Thanks for the feedback! I guess this means we can close the issue.
