### ISSUE TITLE
Install options are not appended when using `brew upgrade`

### ISSUE THREAD

**Issue by klanchman** [Homebrew/brew#5967]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Trying to upgrade packages that were provided the `--ignore-dependencies` option when installed.

e.g.

```
# Originally installed with
# brew install --ignore-dependencies yarn

brew upgrade yarn
```

# What happened (include command output)

The package was upgraded, but dependencies were _also_ installed unexpectedly, which causes other issues in my environment.

<details>
  <summary>Command output</summary>
  <pre>
  
==> Upgrading 1 outdated package:
yarn 1.12.3 -> 1.15.2
==> Upgrading yarn 
==> Installing dependencies for yarn: node
==> Installing yarn dependency: node
==> Downloading https://homebrew.bintray.com/bottles/node-11.13.0.mojave.bottle.tar.gz
Already downloaded: /Users/klanchman/Library/Caches/Homebrew/downloads/0a818793b2cd5d3f9d480d515bbf3987b57e88b7f78b36a8264667f0fdefe056--node-11.13.0.mojave.bottle.tar.gz
==> Pouring node-11.13.0.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/11.13.0: 4,417 files, 50.4MB
==> Installing yarn
==> Downloading https://yarnpkg.com/downloads/1.15.2/yarn-v1.15.2.tar.gz
Already downloaded: /Users/klanchman/Library/Caches/Homebrew/downloads/3bcbb19bee227218e877e51b3aa3387de2e2cdfc9e65f6190a73a9550cb3b283--yarn-v1.15.2.tar.gz
🍺  /usr/local/Cellar/yarn/1.15.2: 14 files, 4.7MB, built in 3 seconds
==> Caveats
==> node
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
  
  </pre>
</details>

# What you expected to happen

The package is upgraded, and dependencies are _not_ installed.

# Discussion

The help text for `brew upgrade` reads as follows:

```
Usage: brew upgrade [options] formula

Upgrade outdated, unpinned brews (with existing and any appended install
options).
```

So I'd expect the `--ignore-dependencies` option would be appended to the `upgrade` command. (Although, it seems `--ignore-dependencies` is not a valid option for `upgrade`.)

I usually upgrade all my packages at once using `brew upgrade`, so even if `--ignore-dependencies` was a valid option, it still wouldn't accomplish my goal of ignoring dependencies _only_ on packages that were originally installed ignoring dependencies.

# Step-by-step reproduction instructions (by running `brew` commands)

```
# Install, ignoring dependencies, an outdated version of Yarn so we can upgrade it
brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/533d40af8ce3a932ab68be51ca2f20a2786669b6/Formula/yarn.rb

# Upgrade Yarn
brew upgrade yarn
```

# Config/Doctor Output

<details>
  <summary>Command output</summary>
  <pre>

➤ brew config
HOMEBREW_VERSION: 2.0.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 649d1427f5fe41323c436608f5c21513f8f34f71
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4516ee029aac77079a6b1368d8d5402ed573a94b
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/klanchman/Library/Logs/Homebrew
HOMEBREW_NO_AUTO_UPDATE: true
HOMEBREW_NO_INSTALL_CLEANUP: true
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_172
macOS: 10.14.4-x86_64
CLT: N/A
Xcode: 10.2

➤ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install node

Run `brew missing` for more details.
</pre>
</details>

**Comment by MikeMcQuaid** [comment]
> (Although, it seems `--ignore-dependencies` is not a valid option for `upgrade`.)

Yes, this is intentional. `--ignore-dependencies` is a developer flag for testing the dependency system. Instead of trying very hard to not install `node` adjust your `PATH` so your `node` of choice is before it and ignore it.

**Comment by MikeMcQuaid** [comment]
Opened https://github.com/Homebrew/brew/pull/5970 to address the documentation on both these cases.

**Comment by klanchman** [comment]
Thanks for the documentation update, that definitely helps!

---

> adjust your `PATH`

Sorry, I should have been more specific about the "other issues in my environment".

I use `nvm` to manage Node versions. My `PATH` is set with my `nvm`-installed Node before the `brew`-installed version (truncated `PATH` below):

```
... /Users/klanchman/.nvm/versions/node/v10.15.2/bin ... /usr/local/bin ...
```

When there is a `brew`-installed version of Node, `nvm` starts throwing errors when launching a terminal in VS Code, leaving me with the `brew` version of Node. VS Code's documentation essentially says to [remove the global version of Node to fix the issue](https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md#why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched) (in this case, the `brew` version).

So I can't really "ignore" the `brew` version of Node. The fact that it's there at all causes me issues, regardless of my `PATH`. 😓 

---

With the new documentation update clarifying that `--ignore-dependencies` is an unsupported option, I also plan to open an issue against Yarn's documentation, because [they say to use the option if you use something like `nvm`](https://yarnpkg.com/en/docs/install#mac-stable). However, I want to make sure I have some alternative to suggest to them. Based on other issues I've seen in this repo, I think a tap might be one alternative. Are there any other alternatives you'd suggest?

**Comment by MikeMcQuaid** [comment]
> So I can't really "ignore" the `brew` version of Node. The fact that it's there at all causes me issues, regardless of my `PATH`. 😓

I see. That's the underlying thing we should figure out how to fix or at least communicate more effectively. Reading that guide it still sounds a bit like it should be possible to adjust your `.bash_profile` such that `which node` in VS Code gets what's expected?

> With the new documentation update clarifying that `--ignore-dependencies` is an unsupported option, I also plan to open an issue against Yarn's documentation, because [they say to use the option if you use something like `nvm`](https://yarnpkg.com/en/docs/install#mac-stable).

Yeh, thanks, that would be a great update.

> Are there any other alternatives you'd suggest?

I think we should figure out a way to make the `node` that Homebrew installs behave nicely so that these workarounds aren't needed. It's not normal for a package manager to install a package (`yarn` in this case) that doesn't work unless you have manually installed some software outside the package manager.

**Comment by klanchman** [comment]
> it still sounds a bit like it should be possible to adjust your `.bash_profile` such that `which node` in VS Code gets what's expected

I saw something that alluded to that, which felt unfortunate for me to need to deal with since I use Fish.

I set up my `.bash_profile` to load `nvm` and installed Node via Homebrew again. VS Code's terminal was still not happy with this configuration. I also saw some people talking about [changing some shell options in VS Code](https://github.com/Microsoft/vscode/issues/36987), which also didn't work.

Finally I upgraded `nvm` from v0.33.11 to v0.34.0 after looking through [this thread](https://github.com/creationix/nvm/issues/855#issuecomment-456414894). I am no longer seeing errors in VS Code, so I suppose `nvm` is handling this scenario now.

Thanks!

**Comment by MikeMcQuaid** [comment]
> Finally I upgraded `nvm` from v0.33.11 to v0.34.0 after looking through [this thread](https://github.com/creationix/nvm/issues/855#issuecomment-456414894). I am no longer seeing errors in VS Code, so I suppose `nvm` is handling this scenario now.

Nice, that's good to know 👍. Thanks for providing more information here!
