### ISSUE TITLE
error on install rabbitmq - undefined method `undent' for #<String:0x00007f80a3f32778>

### ISSUE THREAD

**Issue by mmadrid2csc** [Homebrew/brew#5968]
install a depreciated version of rabbitmq
- What happened (include command output)
rabbitmq: stable 2.8.7
http://www.rabbitmq.com
/usr/local/Cellar/rabbitmq/2.8.7 (165 files, 3.3MB) *
  Built from source on 2019-03-31 at 22:29:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/rabbitmq.rb
==> Dependencies
Required: erlang ✔
Error: undefined method `undent' for #<String:0x00007f80a3f32778>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rabbitmq.rb:49:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:17:in `caveats'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `empty?'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:214:in `info_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:88:in `block in print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:77:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:77:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:77:in `print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:64:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula]$ brew doctor rabbitmq
No check available by the name: rabbitmq
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula]$ less rabbitmq.rb
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula]$ less -N rabbitmq.rb
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula]$ brew test rabbitmq.rb
Error: rabbitmq defines no test

- What you expected to happen
rabbitmq 2.8.7 install 

- Step-by-step reproduction instructions (by running `brew install` commands)

1. brew create http://www.rabbitmq.com/releases/rabbitmq-server/v2.8.7/rabbitmq-server-generic-unix-2.8.7.tar.gz

2. brew install rabbitmq

https://gist.github.com/bfca09266d86e6f445bf565ef3465a45

**Comment by MikeMcQuaid** [comment]
We don't support installing old versions in this way.

From the issue template for future issues:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
