### ISSUE TITLE
$ brew install node -g -s --debug

### ISSUE THREAD

**Issue by cerebrowang** [Homebrew/brew#5971]
can not run in mac.

MacBookAir8,1
Intel Core i/51.6 GHz

macOS 10.14.4/Darwin 18.5.0
Command Line Tools (macOS Mojave version 10.14) for Xcode

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by cerebrowang** [comment]
now, it's run.

**Comment by cerebrowang** [comment]
you can delete this issue.
