### ISSUE TITLE
non-interactive installation of fails: Error: no implicit conversion of false into String

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/brew#5976]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
N/A: happens during intallation of brew
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
N/A: happens during intallation of brew
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
N/A: happens during intallation of brew

# What you were trying to do (and why)
I'm on linux (ubunty 18.04), trying to to automate installation of brew(linuxbrew) (eg on AWS machines), and avoid the prompt `Press RETURN to continue or any other key to abort`

# What happened (include command output)

<details>
  <summary>Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force  </summary>
  <pre>
HEAD is now at 11e5dd990 Merge pull request #5954 from reitermarkus/ditto
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Tapping homebrew/core
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 5011, done.
remote: Counting objects: 100% (5011/5011), done.
remote: Compressing objects: 100% (4805/4805), done.
remote: Total 5011 (delta 53), reused 721 (delta 13), pack-reused 0
Receiving objects: 100% (5011/5011), 4.20 MiB | 15.26 MiB/s, done.
Resolving deltas: 100% (53/53), done.
Tapped 3 commands and 4791 formulae (5,052 files, 13.1MB).
Error: no implicit conversion of false into String
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:25:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:25:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:25:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:3:in `popen_read'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:728:in `block in []'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:256:in `block in cd'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:256:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:256:in `cd'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:727:in `[]'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:611:in `read_or_set_private_config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:196:in `private?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:303:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/tap.rb:54:in `tap'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/brew tap homebrew/core` exited with 1.
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force  
  
  </pre>
</details>

# What you expected to happen

it should work without crashing; note that running `sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"` and then pressing ENTER on terminal does work. 

# Step-by-step reproduction instructions (by running `brew` commands)

```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" </dev/null
# also tried:
yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

**Comment by jonchang** [comment]
This is more properly an issue for the install repository. If standard input is a tty or if the `CI` environment variable is set the install script shouldn't prompt for user input, so both of those methods should have worked. Indeed, the install script already had gotten past the prompt, in which case, something else is going on.

I couldn't reproduce this error on an `ubuntu:xenial` Docker image. If you can show the steps that can cause this error (ideally via Docker) feel free to re-open.

**Comment by timotheecour** [comment]
indeeded adding `export CI=temp` avoids the prompt, but the error remains; 
I'm currently working around this issue by running the command twice, which succeeds the 2nd time:
```
export CI=temp
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

**Comment by jonchang** [comment]
Yes, I believe that you're seeing the error, but I can't reproduce it locally and therefore can't help out. If you can figure out a way to reproduce the error (ideally with a Docker image), or point to the part in the Homebrew code that is causing this problem, that would be appreciated.

**Comment by MikeMcQuaid** [comment]
Please report this to Linuxbrew/install, thanks.
