### ISSUE TITLE
Brew doctor Warning

### ISSUE THREAD

**Issue by Zudva** [Homebrew/brew#5988]
Hi all!

I have this "Warning!"

`Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /opt/local/bin/krb5-config
  /opt/local/bin/python2.7-config
  /opt/local/bin/curl-config
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/pcre2-config
  /opt/local/bin/pcre-config
  /opt/local/bin/ncurses6-config`

What i must do to this config?
 Im not understand (

Thank you )

**Comment by jonchang** [comment]
Please always fill out the issue template. The very first message `brew doctor` says is:

> Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

**Comment by Zudva** [comment]
I want to understand the relationships.
Previously, the brew doctor gave me an error regarding installed libraries and node.js, as well as curl.
   I I want to understand what Brew is offering me.

**Comment by iMichka** [comment]
We understand that you see some warnings in brew doctor. But do you have any other issue with brew? If not, the you can if ignore the things in brew doctor. It is reserved to people which know how to read that output.

If your goal is to learn about that output, the it is better to discuss this with the community at https://discourse.brew.sh. This issue tracker is reserved for real issues or bugs.

**Comment by Zudva** [comment]
> We understand that you see some warnings in brew doctor. But do you have any other issue with brew? If not, the you can ignore the things in brew doctor. It is reserved to people which know how to read that output.
> 
> If your goal is to learn about that output, the it is better to discuss this with the community at https://discourse.brew.sh. This issue tracker is reserved for real issues or bugs.

I not have problem with brew. Ok, i understand )))
