### ISSUE TITLE
brew doesn't have permission to access '/usr/local/Cellar/php@7.1/7.1.20/var/log/php-fpm.log' after mac mojave

### ISSUE THREAD

**Issue by luvvien** [Homebrew/brew#5995]
When I updated the new mac os - mojave, I couldn't get the permission to edit  '/usr/local/Cellar/php@7.1/7.1.20/var/log/php-fpm.log', which caused I couldn't run `brew uninstall php71`.

There is the exception:

```
➜  Cellar brew uninstall --force php@7.1
Error: Permission denied @ rb_file_s_lstat - /usr/local/Cellar/php@7.1/7.1.20/var/log/php-fpm.log
➜  Cellar sudo brew uninstall --force php@7.1
Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
➜  Cellar As Homebrew does not drop privileges on installation you would be giving all
```

How to fix it?

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
