### ISSUE TITLE
Not able to install brew in windows OS for running React-Redux-decoupling-with-stateless-components..

### ISSUE THREAD

**Issue by kumarbikash411** [Homebrew/brew#5999]
i am installed the brew application in MAC successfully and able to run React-Redux-decoupling-with-stateless-components but when i was truing to install the brew in windows i was not able to install.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
