### ISSUE TITLE
brew search : 422 Unprocessable Entity

### ISSUE THREAD

**Issue by avetamine** [Homebrew/brew#6]
when i try to search for a formula it returns with an error : 

brew search dsniff
No formula found for "dsniff".
==> Searching pull requests...
Error: 422 Unprocessable Entity
Validation Failed

**Comment by chamini2** [comment]
For me it happens when it tries pull requests only:

```
$ brew search dnuos
No formula found for "dnuos".
==> Searching pull requests...
Error: Your OS X keychain GitHub credentials do not have sufficient scope!
Scopes they have: []
Create a personal access token: https://github.com/settings/tokens
and then set HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
Error: 422 Unprocessable Entity
Validation Failed
```

```
$ brew search ffmpeg
ffmpeg                                                                          
ffmpeg2theora                                                                   
ffmpegthumbnailer
homebrew/versions/gst-ffmpeg010                                                                                        
Caskroom/cask/ffmpegx
```

**Comment by avetamine** [comment]
Same thing for me.. funny thing is yesterday worked just fine

**Comment by UniqMartin** [comment]
Thanks everyone for the reports! It should be fixed after a `brew update`.

> Same thing for me.. funny thing is yesterday worked just fine

Quite a few things have changed under the hood in the past 48 hours (see, e.g., [this announcement](https://groups.google.com/forum/#!topic/homebrew-discuss/D_weS6pZesg)). :wink: And that's one thing we unfortunately missed when during our changes.
