### ISSUE TITLE
`brew update` lists a bunch of gems which are ignored

### ISSUE THREAD

**Issue by AdrianTP** [Homebrew/brew#6004]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Literally anything involving Homebrew. It pops up these warnings/errors every single time I run it since I uninstalled rvm (I followed [these instructions](https://richonrails.com/articles/uninstalling-rvm)) and installed chruby.

I have done *everything* I can think of short of just deleting *everything* even *remotely* related to Ruby or Homebrew and starting from scratch.

All I managed to figure out is that Homebrew seems to rely on ruby-2.3.3, because that's the version on my system which has the gem issues (even after deleting and reinstalling and manually installing the correct versions of those gems), and those very same gem issues happen whenever I run any `brew` command.

Google has been decidedly unhelpful at finding any other possible causes or solutions.

Please help, this is driving me insane.

# What happened (include command output)

`brew update`

<details>
  <summary>Command output</summary>
  <pre>
  
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Already up-to-date.
  
  </pre>
</details>

# What you expected to happen

I expect Homebrew not to complain every single time I run it.

# Step-by-step reproduction instructions (by running `brew` commands)

`brew update`

<details>
  <summary>Command output</summary>
  <pre>
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Already up-to-date.
  </pre>
</details>

# Output of `brew doctor`
<details>
  <summary>Click to expand...</summary>
  <pre>
$ brew doctor
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /opt/local/bin/icu-config
  /opt/local/bin/python2.7-config
  /opt/local/bin/xml2-config
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/ncurses6-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcgunwind.1.0.dylib
  /usr/local/lib/libusbpp-0.1.4.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.7m/greenlet/greenlet.h
  /usr/local/include/usbpp.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libusb.la
  /usr/local/lib/libusbpp.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libusbpp.a

Warning: Some installed formulae are not readable:
  qt@5.5: unknown version :mountain_lion

Warning: Your Xcode (10.0) is outdated.
Please update to Xcode 10.2 (or delete it).
Xcode can be updated from the App Store.
  </pre>
</details>

# Output of `brew config`
<details>
  <summary>Click to expand...</summary>
  <pre>
$ brew config
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
HOMEBREW_VERSION: 2.1.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1337da0f891aebb85accb094d63e401da1b53cba
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9e64f0318f85c12ce363d6dfe72d3077446e8e2f
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.MTx9AkGKKt/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/user/Library/Logs/Homebrew
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_202, 1.8.0_131
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
  </pre>
</details>

# Ruby stuff
With base ruby (installed by Homebrew):
<details>
  <summary>Click to expand...</summary>
  <pre>
$ chruby
   ruby-2.3.0
   ruby-2.3.1
   ruby-2.3.3
   ruby-2.4.1
   ruby-2.5.0
   ruby-2.5.1
$ ruby --version
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
$ which ruby
/usr/local/bin/ruby
$ gem --version
3.0.3
$ which gem
/usr/local/bin/gem
$ echo $GEM_HOME

$ echo $GEM_PATH

$ gem info bcrypt

*** LOCAL GEMS ***

bcrypt (3.1.10)
    Author: Coda Hale
    Homepage: https://github.com/codahale/bcrypt-ruby
    License: MIT
    Installed at: /usr/local/lib/ruby/gems/2.6.0

    OpenBSD's bcrypt() password hashing algorithm.
$ gem pristine bcrypt --version 3.1.10
Restoring gems to pristine condition...
Building native extensions. This could take a while...
Restored bcrypt-3.1.10
$ brew update
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Already up-to-date.
  </pre>
</details>

After changing version with chruby and trying the whole "pristine" fix suggested by Homebrew:
<details>
  <summary>Click to expand...</summary>
  <pre>
$ chruby ruby 2.5.1
$ which ruby
/Users/user/.rubies/ruby-2.5.1/bin/ruby
$ which gem
/Users/user/.rubies/ruby-2.5.1/bin/gem
$ gem info bcrypt

*** LOCAL GEMS ***

bcrypt (3.1.10)
    Author: Coda Hale
    Homepage: https://github.com/codahale/bcrypt-ruby
    License: MIT
    Installed at: /Users/user/.gem/ruby/2.5.1

    OpenBSD's bcrypt() password hashing algorithm.
$ gem pristine bcrypt --version 3.1.10
Restoring gems to pristine condition...
Building native extensions. This could take a while...
Restored bcrypt-3.1.10
$ brew update
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Already up-to-date.
  </pre>
</details>

# Verification of chruby install
<details>
  <summary>Click to expand...</summary>
  <pre>
$ brew info chruby
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
brew inchruby: stable 0.3.9 (bottled), HEAD
Ruby environment tool
https://github.com/postmodern/chruby#readme
/usr/local/Cellar/chruby/0.3.9 (12 files, 50.8KB) *
  Poured from bottle on 2019-04-03 at 16:10:51
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/chruby.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
Add the following to the ~/.bash_profile or ~/.zshrc file:
  source /usr/local/opt/chruby/share/chruby/chruby.sh

To enable auto-switching of Rubies specified by .ruby-version files,
add the following to ~/.bash_profile or ~/.zshrc:
  source /usr/local/opt/chruby/share/chruby/auto.sh
==> Analytics
install: 986 (30 days), 2,934 (90 days), 10,717 (365 days)
install_on_request: 981 (30 days), 2,919 (90 days), 10,633 (365 days)
build_error: 0 (30 days)
  </pre>
</details>

# Verification of rvm uninstall
<details>
  <summary>Click to expand...</summary>
  <pre>
$ ls -la ~ | grep rvm
$ ls -la /etc | grep rvm
$ which rvm
$ command -v rvm
$ cat ~/.bash_profile | grep rvm
$ cat ~/.bashrc | grep rvm
$ cat ~/.profile | grep rvm
$ ruby --version; gem list | grep rvm
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
$ chruby
   ruby-2.3.0
   ruby-2.3.1
   ruby-2.3.3
   ruby-2.4.1
   ruby-2.5.0
   ruby-2.5.1
$ chruby ruby-2.3.0
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
$ which ruby
/Users/user/.rubies/ruby-2.3.0/bin/ruby
$ gem --version
 2.5.1
$ which gem
/Users/user/.rubies/ruby-2.3.0/bin/gem
$ gem list rvm

*** LOCAL GEMS ***

$ chruby ruby-2.3.1
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
$ which ruby
/Users/user/.rubies/ruby-2.3.1/bin/ruby
$ gem --version
2.5.1
$ which gem
/Users/user/.rubies/ruby-2.3.1/bin/gem
$ gem list rvm

*** LOCAL GEMS ***

$ chruby ruby-2.3.3
Ignoring bcrypt-3.1.10 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built. Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built. Try: gem pristine debug_inspector --version 0.0.2
$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin18]
$ which ruby
/Users/user/.rubies/ruby-2.3.3/bin/ruby
$ gem --version
3.0.3
$ which gem
/Users/user/.rubies/ruby-2.3.3/bin/gem
$ gem list rvm

*** LOCAL GEMS ***

$ chruby ruby-2.4.1
$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin18]
$ which ruby
/Users/user/.rubies/ruby-2.4.1/bin/ruby
$ gem --version
2.6.11
$ which gem
/Users/user/.rubies/ruby-2.4.1/bin/gem
$ gem list rvm

*** LOCAL GEMS ***

$ chruby ruby-2.5.0
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin18]
$ which ruby
/Users/user/.rubies/ruby-2.5.0/bin/ruby
$ gem --version
3.0.3
$ which gem
/Users/user/.rubies/ruby-2.5.0/bin/gem
$ gem list rvm

*** LOCAL GEMS ***

$ chruby ruby-2.5.1
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
$ which ruby
/Users/user/.rubies/ruby-2.5.1/bin/ruby
$ gem --version
3.0.3
$ which gem
/Users/user/.rubies/ruby-2.5.1/bin/gem
$ gem list rvm

*** LOCAL GEMS ***

  </pre>
</details>

Addressing the issue that appears with ruby-2.3.3:
<details>
  <summary>Click to expand...</summary>
  <pre>
$ chruby ruby-2.3.3
Ignoring bcrypt-3.1.10 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built. Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built. Try: gem pristine debug_inspector --version 0.0.2
$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin18]
$ which ruby
/Users/user/.rubies/ruby-2.3.3/bin/ruby
$ gem --version
3.0.3
$ which gem
/Users/user/.rubies/ruby-2.3.3/bin/gem
$ gem install bcrypt -v 3.1.10
Fetching bcrypt-3.1.10.gem
Building native extensions. This could take a while...
Successfully installed bcrypt-3.1.10
Parsing documentation for bcrypt-3.1.10
Installing ri documentation for bcrypt-3.1.10
Done installing documentation for bcrypt after 0 seconds
1 gem installed
$ gem install binding_of_caller -v 0.7.2
Building native extensions. This could take a while...
Successfully installed binding_of_caller-0.7.2
Parsing documentation for binding_of_caller-0.7.2
Installing ri documentation for binding_of_caller-0.7.2
Done installing documentation for binding_of_caller after 0 seconds
1 gem installed
$ gem install byebug -v 8.2.1
Fetching byebug-8.2.1.gem
Building native extensions. This could take a while...
Successfully installed byebug-8.2.1
Parsing documentation for byebug-8.2.1
Installing ri documentation for byebug-8.2.1
Done installing documentation for byebug after 14 seconds
1 gem installed
$ gem install debug_inspector -v 0.0.2
Building native extensions. This could take a while...
Successfully installed debug_inspector-0.0.2
Parsing documentation for debug_inspector-0.0.2
Installing ri documentation for debug_inspector-0.0.2
Done installing documentation for debug_inspector after 0 seconds
$ gem info bcrypt

*** LOCAL GEMS ***

bcrypt (3.1.11, 3.1.10)
    Author: Coda Hale
    Homepage: https://github.com/codahale/bcrypt-ruby
    License: MIT
    Installed at (3.1.11): /Users/user/.gem/ruby/2.3.3
                 (3.1.10): /Users/user/.gem/ruby/2.3.3

    OpenBSD's bcrypt() password hashing algorithm.
$ brew update
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Updated 2 taps (homebrew/cask-versions and homebrew/cask).
  </pre>
</details>

And some more attempts to get it to stop complaining:
<details>
  <summary>Click to expand...</summary>
  <pre>
$ rm -rf $HOME/.gem/ruby/2.3.3
$ rm -rf $HOME/.rubies/ruby-2.3.3
$ ruby-install ruby-2.3.3
<cut for brevity>
>>> Successfully installed ruby 2.3.3 into /Users/user/.rubies/ruby-2.3.3
$ sudo gem update --system
<cut for brevity>
RubyGems installed the following executables:
	/Users/user/.rubies/ruby-2.3.3/bin/gem
	/Users/user/.rubies/ruby-2.3.3/bin/bundle

RubyGems system software updated
$ gem install bcrypt -v 3.1.10
Fetching bcrypt-3.1.10.gem
Building native extensions. This could take a while...
Successfully installed bcrypt-3.1.10
Parsing documentation for bcrypt-3.1.10
Installing ri documentation for bcrypt-3.1.10
Done installing documentation for bcrypt after 0 seconds
1 gem installed
$ gem install binding_of_caller -v 0.7.2
Fetching binding_of_caller-0.7.2.gem
Fetching debug_inspector-0.0.3.gem
Building native extensions. This could take a while...
Successfully installed debug_inspector-0.0.3
Building native extensions. This could take a while...
Successfully installed binding_of_caller-0.7.2
Parsing documentation for debug_inspector-0.0.3
Installing ri documentation for debug_inspector-0.0.3
Parsing documentation for binding_of_caller-0.7.2
Installing ri documentation for binding_of_caller-0.7.2
Done installing documentation for debug_inspector, binding_of_caller after 0 seconds
2 gems installed
$ gem install byebug -v 8.2.1
Fetching byebug-8.2.1.gem
Building native extensions. This could take a while...
Successfully installed byebug-8.2.1
Parsing documentation for byebug-8.2.1
Installing ri documentation for byebug-8.2.1
Done installing documentation for byebug after 14 seconds
1 gem installed
$ gem install debug_inspector -v 0.0.2
Fetching debug_inspector-0.0.2.gem
Building native extensions. This could take a while...
Successfully installed debug_inspector-0.0.2
Parsing documentation for debug_inspector-0.0.2
Installing ri documentation for debug_inspector-0.0.2
Done installing documentation for debug_inspector after 0 seconds
1 gem installed
$ brew update
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Updated 1 tap (homebrew/cask).
No changes to formulae.
$ chruby 2.3.3
Ignoring bcrypt-3.1.10 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built. Try: gem pristine byebug --version 8.2.1
Ignoring debug_inspector-0.0.2 because its extensions are not built. Try: gem pristine debug_inspector --version 0.0.2
  </pre>
</details>

**Comment by MikeMcQuaid** [comment]
Homebrew doesn't install any of those gems so this isn't a Homebrew bug. `rm -rf ~/.gem` may solve this problem for you (and will require you to reinstall all your gems).

**Comment by AdrianTP** [comment]
Nuking my whole Ruby environment (reverting to default Mac OS system Ruby, uninstalling chruby, ruby-install, deleting my `~/.rubies` and `~/.gem` folders, etc.) and restarting from scratch seems to have fixed the issue.

Thanks!
