### ISSUE TITLE
Installation of old versions of PHP and icu4c

### ISSUE THREAD

**Issue by bernashaw** [Homebrew/brew#6011]
Recently, PHP version 5.4 is needed, but through brew search php@5.4, no information can be found. After checking, it is found that it is no longer supported, and it has to install its own source code. I don't know why it is no longer supported. And the previous php-version has disappeared, which is very inconvenient.
When I tried to install php5.4, I found that the version of icu4c was 63.1, but the version of php5.4 needed 62.1. After brew search icu4c found that icu4c did not support the low version, why delete the low version?

**Comment by MikeMcQuaid** [comment]
PHP 5.4 is no longer supporter by PHP: https://www.php.net/downloads.php
