### ISSUE TITLE
Sandbox forbids setting the set[ug]id bits

### ISSUE THREAD

**Issue by tavianator** [Homebrew/brew#6019]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Run the tests for a formula in my tap: https://github.com/tavianator/homebrew-tap/blob/8d134618c9193aff2c61c78973c4032a1a872a62/Formula/bfs.rb

# What happened (include command output)

The tests failed, because setuid/setgid files created during the tests weren't actually marked setu/gid due to the sandbox.  See https://travis-ci.org/tavianator/homebrew-tap/builds/521023627 for the build output.

To isolate the issue, I made a branch that just this for the tests:

```
touch ./file
chmod u+s ./file
ls -l ./file
```

From the output, you can see that the u+s bit is not set: https://travis-ci.org/tavianator/homebrew-tap/builds/521032863#L1591

```
==> touch ./file
==> chmod u+s ./file
==> ls -l ./file
-rw-r--r--  1 travis  admin  0 Apr 17 00:39 ./file
```

MacPorts once had a similar issue: https://trac.macports.org/ticket/54963.  Apparently `file-write-setugid` needs to be explicitly allowed in addition to `file-write*`.

# What you expected to happen

`chmod u+s` and `g+s` should succeed.  The files are owned by the current user so there shouldn't be a security issue with allowing it.  In my case, the files aren't even executable.

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew install tavianator/bfs
brew test -v bfs
```

**Comment by jonchang** [comment]
Can you open a pull request to make this change? It should be in either `sandbox.rb` or `dev-cmd/test.rb`.

**Comment by MikeMcQuaid** [comment]
Sorry, until a core formula has a reason to make this change I'm not in favour of it. I don't think setuid/setgid binaries are widely understood enough (particularly their security implications) for Homebrew to be creating and distributing them.
