### ISSUE TITLE
brew extract help doesn't show proper syntax for --version

### ISSUE THREAD

**Issue by espoelstra** [Homebrew/brew#6034]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Was looking to extract a formula at a specific version to a custom tap per this issue https://github.com/Homebrew/brew/issues/6028 as the workaround.

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
brew tap-new $USER/custom-tap
==> Created $USER/custom-tap
/usr/local/Homebrew/Library/Taps/$USER/homebrew-custom-tap

brew extract --version 4.4.23 bash $USER/custom-tap
Usage: brew extract [options] formula tap

Look through repository history to find the most recent version of formula and
create a copy in tap/Formula/formula@version.rb. If the tap is not
installed yet, attempt to install/clone the tap before continuing. To extract a
formula from a tap that is not homebrew/core use user/repo/formula.

        --version                    Extract the provided version of formula
                                     instead of the most recent.
    -f, --force                      Override warnings and enable potentially
                                     unsafe operations.
    -d, --debug                      Display any debugging information.
    -h, --help                       Show this message.
Error: Invalid usage
  </pre>
</details>

# What you expected to happen

I expected it to give me the proper syntax ie `--version=desiredversion` in the help OR in the error.

# Step-by-step reproduction instructions (by running `brew` commands)

brew tap-new $USER/custom-tap
brew extract --version 4.4.23 bash $USER/custom-tap
# Works with =
brew extract --version=4.4.23 bash $USER/custom-tap

**Comment by MikeMcQuaid** [comment]
@GauthamGoli Could you take a look at this?

**Comment by espoelstra** [comment]
Just a note to those that aren't sure what the changes did, it works now with `=` or without, ie `--version 4.4.23` or `--version=4.4.23`.

Thanks guys!
