### ISSUE TITLE
Can brew be made faster? It is quite slow in general.

### ISSUE THREAD

**Issue by rsn8887** [Homebrew/brew#6043]
# A detailed description of the proposed feature

Is there any way to make brew faster? When I run `brew update` on my Macbook Pro 15 inch, which runs almost everything very snappily, there's several second wait before anything happens. Brew upgrade and other commands are also very slow.

Maybe multi-threading or compiler optimizations -O3 can be enabled or some such?

# The motivation for the feature

Brew is just slow and sometimes sluggish, takes forever to respond, update or upgrade, or even just checking if there are any upgrades takes forever. Even just checking if a certain package name exists sometimes takes several seconds (!).

# How the feature would be relevant to at least 90% of Homebrew users

Making brew faster would benefit everyone using it, because it would save time.

# What alternatives to the feature have been considered

Buying a faster computer lol. But this is just a simple package manager, I don't understand why it should be slow. Can it be compiled with -O3 and -pthreads maybe (or some other quick fix?)?

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by vitorgalvao** [comment]
[This has been discussed in the past](https://github.com/Homebrew/brew/issues/3901).

Most of the slowness happens [outside of the control of Homebrew](https://github.com/Homebrew/brew/issues/3901#issuecomment-371875985).
