### ISSUE TITLE
add ranlib and ar to shims/super

### ISSUE THREAD

**Issue by clouds56** [Homebrew/brew#6050]
# A detailed description of the proposed feature

provide `ar`/`ranlib` for corresponding cc in `/usr/local/Homebrew/Library/Homebrew/shims/mac/super/`

# The motivation for the feature

The `cmake` would find `ar`/`ranlib` in `_CMAKE_TOOLCHAIN_LOCATION` (where `cc` locates), if not there, it would randomly pick one in `/usr/local/bin` (gnu binutils) or `/usr/bin` (xcode), which may make the build (from source) fail.

# How the feature would be relevant to at least 90% of Homebrew users

No, but I think it is essential for developers.

# What alternatives to the feature have been considered

carefully specify `ar`/`ranlib` when using `cmake`, while `cmake` [does not follows AR/RANLIB environment variables](https://gitlab.kitware.com/cmake/cmake/issues/18277), it would take some effort.

**Comment by MikeMcQuaid** [comment]
Would need to see Homebrew/homebrew-core formulae that require this before it is added. Sorry.

**Comment by clouds56** [comment]
Sorry for that, I haven't seen this commit https://github.com/Homebrew/homebrew-core/commit/db433a5e3d8c26ec504b8e67bd5bd219db71c7d7, the binutils in core in now keg-only, I installed binutils several years ago and recently upgrade my mac to Xcode 10, so everything breaks since binutils in my `/usr/local/bin/ar`.

Now there's no impact on different toolchains (means it would behaves normal at most cases).
I've run `brew unlink binutils` manually and got that fixed (FYI, I'm working on the built of https://github.com/Homebrew/homebrew-core/pull/30465)

BTW, I still suggest that we should add ar/ranlib to shims since it is the right way to do.

<details>

When I built the formula it stops on `Undefined symbol error`, and when I remove the `-w` option passed to `clang`, it shows additional warning
```
file was built for archive which is not the architecture being linked (x86_64)
```

I investigated into the log and see it (cmake) uses `/usr/local/bin/ar` and `/usr/local/bin/ranlib` to create static libraries.
further more, this path is set in the CMakeCache.txt (`CMAKE_AR` and `CMAKE_RANLIB`)
However my path is set to `/usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/cmake/bin:/usr/bin:/bin:/usr/sbin:/sbin` when building, why cmake would find `/usr/local/bin` for the wrong `ranlib` version?
it is in `CMakeFindBinUtils.cmake` (see also [find_program](https://cmake.org/cmake/help/v3.0/command/find_program.html), it would fallback search `CMAKE_PREFIX_PATH` after hints)
```
# _CMAKE_TOOLCHAIN_LOCATION is where `cc` or `$ENV{VAR}` locates
find_program(CMAKE_RANLIB NAMES ${_CMAKE_TOOLCHAIN_PREFIX}ranlib HINTS ${_CMAKE_TOOLCHAIN_LOCATION})
```
a normal resolve of toolchain should be
```
set(CMAKE_CXX_COMPILER /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ )
set(CMAKE_AR /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar )
set(CMAKE_RANLIB /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib )
set(CMAKE_LINKER /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld )
```
while here it is
```
set(CMAKE_CXX_COMPILER /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ )
set(CMAKE_AR /usr/local/bin/ar ) # after brew unlink binutils, it is /usr/bin/ar
set(CMAKE_RANLIB /usr/local/bin/ranlib )
set(CMAKE_LINKER /usr/local/Homebrew/Library/Homebrew/shims/mac/super/ld )
```
you could see here's conflict of `ranlib` and `ld` version and that's why I'm asking to add `ar`/`ranlib` to shims (even if it works now)

</details>
