### ISSUE TITLE
Installing a brew from the GutHub URL shortener results in an incorrect brew name

### ISSUE THREAD

**Issue by dnicolson** [Homebrew/brew#6052]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Attempting to install a brew from a URL created by the GitHub URL Shortener results in an error.

# What happened (include command output)

```
brew install https://git.io/fj3Sv
```

<details>
  <summary>Command output</summary>
  <pre>
  
```
Error: No available formula with the name "fj3Sv"
In formula file: /Users/dave/Library/Caches/Homebrew/Formula/fj3Sv
Expected to find class Fj3sv, but only found: Bluetoothkeyboardenhancer.
```

  </pre>
</details>

# What you expected to happen

The brew to be installed as [redirects](https://github.com/Homebrew/legacy-homebrew/issues/8531) are followed.

# Step-by-step reproduction instructions (by running `brew` commands)

1. Use GitHub to create a shortened URL resulting in a `git.io` URL.
2. Attempt to install the brew via a URL.

Adding the following code to the `curl_download` method in `utils/curl.rb` results in the request being saved successfully but the name is unable to be matched in `cmd/install.rb`:

```
  final_url = %r{^.*Location: (.*?)\r.*$}.match(headers)&.[](1)
  file_name = URI(final_url).path.split('/').last
  if (destination.basename != file_name)
    destination = destination.dirname.join(file_name)
  end
```

**Comment by MikeMcQuaid** [comment]
We are unlikely to accept a pull request to improve this behaviour because installing from a URL is generally a bad experience/idea compared to a tap.
