### ISSUE TITLE
Bare `brew info` crashes with error: can't modify frozen Pathname

### ISSUE THREAD

**Issue by bcc32** [Homebrew/brew#6055]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Just running `brew info`.

# What happened (include command output)

`brew config`

<details>
  <summary>Command output</summary>
  <pre>HOMEBREW_VERSION: 2.1.1-57-ge5f722c
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: e5f722ca029104e6ff9b30b838de46140f725c26
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 963a3c49ce6050b1ee6a891bfe50489f4af59005
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_VISUAL: vim
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1, 1.8.0_172
macOS: 10.14.4-x86_64
CLT: 10.2.0.0.1.1552586384
Xcode: N/A
CLT headers: 10.2.0.0.1.1552586384
XQuartz: 2.7.11 => /opt/X11</pre>
</details>

`brew doctor`

<details>
  <summary>Command output</summary>
  <pre>Your system is ready to brew.</pre>
</details>

`brew info`

<details>
  <summary>Command output</summary>
  <pre>Error: can't modify frozen Pathname</pre>
</details>

# What you expected to happen

IIRC, it should show the total space usage of homebrew packages on my system.

# Step-by-step reproduction instructions (by running `brew` commands)

Just `brew info`.

**Comment by MikeMcQuaid** [comment]
What's the output of `brew info --debug`? Thanks!

**Comment by amyspark** [comment]
@MikeMcQuaid --

```
amalia@Sakura:~ $ brew info --debug
Error: can't modify frozen Pathname
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:46:in `compute_disk_usage'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:23:in `abv'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:76:in `print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:66:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```
`git bisect` tells me this started happening in d1ea6f38d3ea1ad8d1665ad18267ed1a2ad08b8c (#6039).

**Comment by bcc32** [comment]
Works now.  Thanks!
