### ISSUE TITLE
Endless warnings about sha1 being deprecated...

### ISSUE THREAD

**Issue by seclorum** [Homebrew/brew#606]
This is causing hiccups with some of our local developers.  Any particular reason its started happening this evening:

$ brew update && brew upgrade
Already up-to-date.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/osx-cross/homebrew-avr/avr-binutils.rb:8:in `<class:AvrBinutils>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:4:in `sha1'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:11:in `sha1'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osx-cross/homebrew-avr/avr-binutils.rb:14:in `block in <class:AvrBinutils>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osx-cross/homebrew-avr/avr-binutils.rb:14:in `block in <class:AvrBinutils>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osx-cross/homebrew-avr/avr-binutils.rb:14:in `block in <class:AvrBinutils>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/killercup/homebrew-openresty/Formula/ngx_openresty.rb:8:in `block in <class:NgxOpenresty>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:11:in `sha1'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/killercup/homebrew-openresty/Formula/ngx_openresty.rb:13:in `block in <class:NgxOpenresty>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:11:in `sha1'

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:4:in `sha1'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:11:in `sha1'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/osx-cross/homebrew-avr/avr-binutils.rb:8:in `<class:AvrBinutils>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:4:in `sha1'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:11:in `sha1'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osx-cross/homebrew-avr/avr-binutils.rb:14:in `block in <class:AvrBinutils>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osx-cross/homebrew-avr/avr-binutils.rb:14:in `block in <class:AvrBinutils>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osx-cross/homebrew-avr/avr-binutils.rb:14:in `block in <class:AvrBinutils>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/killercup/homebrew-openresty/Formula/ngx_openresty.rb:8:in `block in <class:NgxOpenresty>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:11:in `sha1'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/killercup/homebrew-openresty/Formula/ngx_openresty.rb:13:in `block in <class:NgxOpenresty>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:11:in `sha1'

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:4:in `sha1'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:11:in `sha1'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'

**Comment by DomT4** [comment]
> This is causing hiccups with some of our local developers. Any particular reason its started happening this evening

People executing `brew install` or `brew fetch` on SHA1 formulae have been seeing a warning for a while. It was turned into a more severe fail yesterday as the deprecation timetable edges ahead, without the formulae actually needing to be executed by a user. We may need to see how that goes.

Essentially carrying around so much old code is problematic on a number of levels & makes looking after Homebrew considerably harder, which degrades UX over time. Consequently, we try & gently nudge external taps to follow our lead and update the syntax/checksum every now and again with tools like `brew audit` but sometimes that's not noisy enough for people to take notice of 😕.

In the very short term I'd recommend reporting it to the upstream taps that they need to move their formulae over to SHA256. I've done that for every tap you've listed in your post & https://github.com/killercup/homebrew-openresty have already fixed their issue at least.

Despite the noise things _should_ actually be updating & upgrading fine.

CC @MikeMcQuaid.

**Comment by MikeMcQuaid** [comment]
Sorry for the noise but, as @DomT4 points out, they are issues that need reported and fixed. Thanks for the report!

**Comment by seclorum** [comment]
Thanks @DomT4 and @MikeMcQuaid for the info .. I will chase it up as I encounter the errors and report it to the appropriate places upstream ..

**Comment by UniqMartin** [comment]
> I will chase it up as I encounter the errors and report it to the appropriate places upstream ..

Thanks! :heart: You might have noticed that after some tweaking it should now be always printing the path of the offending formula file (which was not yet the case when you opened this issue). This should make reporting those warnings to the right tap a lot easier.

**Comment by apjanke** [comment]
How should this interact with boneyarded formulae? #615 `brew tap` is now balking at tapping `homebrew/boneyard`, and `brew uses` gets lots of warnings when the boneyard is tapped.
