### ISSUE TITLE
Abitility to install specific version of cask

### ISSUE THREAD

**Issue by kelbyers** [Homebrew/brew#6065]
# Description

I would like the ability to specify which version of an application gets installed from brew cask.

# The motivation for the feature

For example, the docker GUI application, kitematic, is currently at version 0.17.7. That version is broken, and the many requests for fixes have been ignored by the developers (along with every other issue opened) for the last 2-3 months. The suggested workaround is to install an older version.

# What alternatives to the feature have been considered

I have seen several requests for the ability to pin a version, which have been rejected along the lines of "we want this to work as closely like the manual process of downloading and installing an app as possible." I will counter that for most applications that I can download and install, I have the ability to choose which version I download.

I have found a method posted online for a way to specify which version of the application gets installed, but it is kludgy, and involves passing in the URL to the raw github contents of the version that is desired. E.g.:
```
brew cask uninstall vagrant &&
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/e511469d8d746f1d925084ec79e51e6626322cbd/Casks/vagrant.rb
```

**Comment by MikeMcQuaid** [comment]
This is intentionally unsupported, sorry.

**Comment by kelbyers** [comment]
That means that this tool in fact does not work exactly like installing from a download. What use is it, if it takes all control away from the user? The only control this gives me is the ability to install or uninstall an application. I can do that without the tool just fine.

**Comment by vitorgalvao** [comment]
> That means that this tool in fact does not work exactly like installing from a download.

It does if you want the latest version. Most people want just that, they don’t hunt around for old versions.

> What use is it, if it takes all control away from the user? 

That is quite hyperbolic. You make it sound like we’re locking down your system and preventing you from installing apps. Homebrew takes no control away from you; it only gives you more possibilities. If those are possibilities you want is another matter. Here are a few suggestions:

* Get an older version from [homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions).
* Install manually just the ones you need.
* Make your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).
* Use a third-party tap.

> The only control this gives me is the ability to install or uninstall an application.

Judging by the amount of satisfied users we have, I’d say that’s pretty useful. Also don’t forget we also install fonts, drivers, screensavers, and a buttload of other stuff.

> I can do that without the tool just fine.

Then do. No software is perfect for everyone. There’re people using Nix, people using MacPorts, people using Homebrew, and people doing it by hand. Pick whatever suits you best. We’ll go the direction that serves most users best.

**Comment by MikeMcQuaid** [comment]
> What use is it, if it takes all control away from the user?

@kelbyers That's an unnecessarily rude statement. Please adjust your tone before creating future issues or comments.
