### ISSUE TITLE
add -1 to brew search

### ISSUE THREAD

**Issue by jakevossen5** [Homebrew/brew#6067]
# Description

When using brew search, allow for the `-1` option, which will put all the results on their own line instead of seperated by tabs (as it currently it)

# The motivation for the feature

I am trying to get a list of all available casks and use that in a program I am writing. Having it operated it by lines would be much easier when getting the output of `brew search` (specifically, casks)

# How the feature would be relevant to at least 90% of Homebrew users

Increasing the programability is a plus for everyone. 

# What alternatives to the feature have been considered

I would be able to get all the names from https://formulae.brew.sh/api/cask.json , but the actual name of the package (that you would use in `brew cask install`) is not there, unless I am missing something

**Comment by MikeMcQuaid** [comment]
> Having it operated it by lines would be much easier when getting the output of `brew search` (specifically, casks)

Have you tried this already? `brew search` doesn't use taps unless writing to a TTY. See `brew search | cat`.
