### ISSUE TITLE
Homebrew Not Working: 

### ISSUE THREAD

**Issue by raguay** [Homebrew/brew#607]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
No permission errors

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Brew update gives this twice:

Use 'depends_on "autoconf" => :build' instead.
/usr/local/Library/Homebrew/compat/dependency_collector.rb:11:in `parse_symbol_spec'

Therefore, I can not update brew anymore. Just started yesterday, 07/29/2016.
OS X 10.11.6 (15G31)

**Comment by DomT4** [comment]
We tweaked some things to make our deprecations less silent, because most of them were getting ignored & it makes making Homebrew work more difficult. We may need to tweak the messaging depending on how much this proves very noisy.

`brew update` should be identifying the problematic file along with that message. Is that not the case?

**Comment by raguay** [comment]
No, it just gives that message. Nothing else. It really messes up my BitBar
script.

**Comment by DomT4** [comment]
Can you run `brew update -v` & see if we hit a more obvious failure point? Thanks.

**Comment by raguay** [comment]
Weird. brew update now shows nothing but everything is up to date. But,
brew upgrade still shows the errors. I ran the command:

brew upgrade -v                                                      
Warning: Calling 'depends_on :autoconf' is deprecated!
Use 'depends_on "autoconf" => :build' instead.
/usr/local/Library/Homebrew/compat/dependency_collector.rb:11:in
`parse_symbol_spec'

Warning: Calling 'depends_on :automake' is deprecated!
Use 'depends_on "automake" => :build' instead.
/usr/local/Library/Homebrew/compat/dependency_collector.rb:11:in
`parse_symbol_spec'

It's doesn't give anymore information than that.

**Comment by UniqMartin** [comment]
In 0a33cc591d258e07f2279bc0440d62e38983fd67 I improved the logic that determines which code location to point out in the message a bit, so that it will hopefully always point out the formula where the warning originated from. Can you please `brew update` and see if it now shows the offending formulae in the message?

**Comment by raguay** [comment]
Okay. It looks like the last emacs is the cause:

Warning: Calling 'depends_on :autoconf' is deprecated!
Use 'depends_on "autoconf" => :build' instead.
/usr/local/Library/Taps/railwaycat/homebrew-emacsmacport/Formula/emacs-mac.rb:10:in
`<class:EmacsMac>'

Warning: Calling 'depends_on :automake' is deprecated!
Use 'depends_on "automake" => :build' instead.
/usr/local/Library/Taps/railwaycat/homebrew-emacsmacport/Formula/emacs-mac.rb:11:in
`<class:EmacsMac>'

I believe Emacs had just updated before this started showing up as well.

**Comment by UniqMartin** [comment]
Thanks and sorry for the trouble! Could you report this to the railwaycat/emacsmacport tap?

**Comment by DomT4** [comment]
https://github.com/railwaycat/homebrew-emacsmacport/issues/70

**Comment by raguay** [comment]
Just added the issue. Thanks for the help.

**Comment by DomT4** [comment]
The cause of the problem here has been kindly fixed upstream. Should be alright now, at least for that tap.
