### ISSUE TITLE
[Linux] Fail to compile formulae using `gcc@*` due to incorrect LD flags

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/brew#6070]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

This issue is related to `ccls` formula (https://github.com/Homebrew/linuxbrew-core/issues/12518)  but can be applied to other formulae. 

The `ccls` formula requires C++17. Therefore it cannot be compiled by the default `gcc` formula, which is GCC 5 on Linuxbrew. To get the correct compiler, users need to manually pass `HOMEBREW_CC`/`HOMEBREW_CXX` environment or apply the fixes in https://github.com/Homebrew/linuxbrew-core/pull/12785

However, even with correct compilers (i.e. using `gcc@7` or `gcc@8` formulae), the formula still cannot be compiled unless efficient new system gcc is used. (See https://github.com/Homebrew/linuxbrew-core/issues/12518#issuecomment-482532011 for details)

The reason is due to `-L#{HOMEBREW_PREFIX}/lib` is incorrectly passed in the last link step (no matter whether it is super or std build environment). As a result, incorrect libstdc++ from `gcc` formula is picked over libstdc++ from `gcc@7`/`gcc@8`. The related brew codes are in the below:

* For superenv:
https://github.com/Homebrew/brew/blob/e18c5c1291e3b2a900d2437a9e993d45034c766b/Library/Homebrew/extend/ENV/super.rb#L175
* For stdenv:
https://github.com/Homebrew/brew/blob/e18c5c1291e3b2a900d2437a9e993d45034c766b/Library/Homebrew/extend/os/linux/extend/ENV/std.rb#L8

To fix this issue, we need to do either of the followings:
* Do not pass `-L#{HOMEBREW_PREFIX}/lib` if brew gcc is used. Noted that we already pass this flag in the correct way inside gcc spec file.
https://github.com/Homebrew/linuxbrew-core/blob/2b32159a09762bd1d7f3141ddc9f557128b3b03b/Formula/gcc.rb#L293
https://github.com/Homebrew/linuxbrew-core/blob/2b32159a09762bd1d7f3141ddc9f557128b3b03b/Formula/gcc%408.rb#L228
* Pass additional `-L#{path to gcc libraries}` flag before `-L#{HOMEBREW_PREFIX}/lib` if brew `gcc@*` is used.

/cc @sjackman

**Comment by xu-cheng** [comment]
A side question: should we stop passing`-L#{HOMEBREW_PREFIX}/lib` for all cases (both Mac and Linux) as we already passed library path for each individual dependencies in the formal of opt paths.

**Comment by sjackman** [comment]
https://github.com/Homebrew/brew/blob/e18c5c1291e3b2a900d2437a9e993d45034c766b/Library/Homebrew/extend/ENV/super.rb#L173-L176
The `-L` paths of the dependencies come before `HOMEBREW_PREFIX/"lib"`. Adding `depends_on "gcc@8" unless OS.mac?` should I think resolve the issue.

**Comment by xu-cheng** [comment]
>The -L paths of the dependencies come before HOMEBREW_PREFIX/"lib". Adding depends_on "gcc@8" unless OS.mac? should I think resolve the issue.

No, it won’t solve the issue. Because it is the path `HOMEBREW_PREFIX/"lib/gcc/#{version_suffix}"` need to be put before `#{HOMEBREW_PREFIX}/lib`

**Comment by sjackman** [comment]
Ah, yep, that's a problem. I think that Superenv should probably be responsible for adding `"HOMEBREW_PREFIX/"lib/gcc/#{version_suffix}"` to the front of the `-L` paths when the compiler is `gcc@*`.
cc @iMichka

**Comment by sjackman** [comment]
Alternatively as you mention we could remove `-LHOMEBREW_PREFIX/"lib"`, but I'm worried that will break things in ways that we don't yet anticipate. It would be nice though.

**Comment by sjackman** [comment]
Does GCC have a compiler option to add a library path to its search path with super low priority have GCC has search its default search paths?

**Comment by xu-cheng** [comment]
> Does GCC have a compiler option to add a library path to its search path with super low priority, after GCC has searched its default search paths?

FYI, the whole issue happens is because we tell gcc not to search its default paths because of whole brew glibc. Noted the `-nostdlib` flag in the code. 

https://github.com/Homebrew/linuxbrew-core/blob/2b32159a09762bd1d7f3141ddc9f557128b3b03b/Formula/gcc%408.rb#L228

I suspect it will work just fine for system with sufficient new glibc. Though I cannot test it myself.

**Comment by sjackman** [comment]
Ah right. I'm caught up now.

> Do not pass `-L#{HOMEBREW_PREFIX}/lib` if brew gcc is used. Noted that we already pass this flag in the correct way inside gcc spec file.

This solution seems to make sense to me, since `-L#{HOMEBREW_PREFIX}/lib` is in the `specs` file. If any brewed `gcc` or `gcc@*` is used, do not pass `-L#{HOMEBREW_PREFIX}/lib`, since it's in the `specs` file.

**Comment by MikeMcQuaid** [comment]
> Alternatively as you mention we could remove `-LHOMEBREW_PREFIX/"lib"`, but I'm worried that will break things in ways that we don't yet anticipate.

Agreed.

**Comment by sjackman** [comment]
> This solution seems to make sense to me, since `-L#{HOMEBREW_PREFIX}/lib` is in the `specs` file. If any brewed `gcc` or `gcc@*` is used, do not pass `-L#{HOMEBREW_PREFIX}/lib`, since it's in the `specs` file. 

@xu-cheng Would you like to take a shot at implementing this fix in Superenv?

**Comment by xu-cheng** [comment]
This problem is not solved. However, I don't think I have enough free time to work on this for the moment. Sorry.

**Comment by MikeMcQuaid** [comment]
Closing this out until someone wants to pick it up.
