### ISSUE TITLE
glibtoolize:   error: $pkgauxdir is not a directory

### ISSUE THREAD

**Issue by z2014** [Homebrew/brew#6078]
# What you were trying to do (and why)

i am trying to `brew install opencv@2` in docker build from centos7

# What happened (include command output)

so i get this error `glibtoolize:   error: $pkgauxdir is not a directory`
, but when i exec `brew install libtool`,
i get ` libtool 2.4.6_2 is already installed and up-to-date`
so i cd `/usr/local/` find no `/bin` or `/Cellar`,
and i found out when i install brew in docker build from centos7, i first run this
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
 i get 
```
 To install Linuxbrew, paste at a terminal prompt:
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```
 so i run like that, and then i get
```
Don't run this as root!
```
so i run this
```
su zcl -c"sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)""
```
and it worked,
but my package installed from brew were installed at `/home/zcl/.linuxbrew/`,
so i link  
`ln -s /home/zcl/.linuxbrew/bin /usr/local/bin` and 
` ln -s /home/zcl/.linuxbrew/Cellar /usr/local/Cellar`,
and run `brew install opencv@2`again, and i get the same error,
so how to fix this problem

**Comment by MikeMcQuaid** [comment]
> so how to fix this problem

There is no problem, that's the expected installation location.

**Comment by z2014** [comment]
i want to know why i get do not run this as an root

**Comment by z2014** [comment]
And I had installed libtool.why I get plaguxdir is not a directory

**Comment by MikeMcQuaid** [comment]
Because it's insecure. You can check out the code if you want answers to such questions.

Also, from the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

**Comment by abcfy2** [comment]
I have the same issue. I try to install libtool from source, it works.

```bash
brew rm libtool
brew install -s libtool
```
