### ISSUE TITLE
Ability to select a different bottle

### ISSUE THREAD

**Issue by razzfox** [Homebrew/brew#6091]
# A detailed description of the proposed feature

A command line option, or environment variable that selects a bottle version ('mojave', 'high_sierra', 'sierra', etc).

# The motivation for the feature

I am using Mojave on a 2010 MacBook Air (Core 2 Duo). This machine normally runs High Sierra, but it will run Mojave with modification that is easy to do (dosdude1's patch). 

Some Mojave bottles result in the error: `Illegal Instruction: 4`. This means that the bottle was compiled without support for my cpu. The High-Sierra bottles do continue to work. 

I have only run into this issue for `node` and `ffmpeg` so far. 

# How the feature would be relevant to at least 90% of Homebrew users

From the homebrew documentation: 
> By default, bottles will be built for the oldest CPU supported by the OS/architecture you're building for (Core 2 for 64-bit OSs). 

This may not be strictly true. 

> Just remember that if you build for a newer architecture some of your users might get binaries they can't run and that would be sad!

As the docs warn, any user could find that a bottle was compiled without support for their cpu. Since multiple bottles are available, users need a way to select a compatible bottle, especially when the brew default is incompatible.

# What alternatives to the feature have been considered

The workaround without the ability to specify a bottle version is:
1. First discover that there is a problem with the binary after installing the default bottle.
2. Uninstall the package.
3. Run `brew edit [package]` and use your shell EDITOR to remove the Mojave bottle sha256 line. 
4. Run `brew install [package]` (repeat when updated).

**Comment by MikeMcQuaid** [comment]
Sorry, given this issue only occurs on unsupported macOS setups we won't be adding support for this feature. We would consider reviewing a PR that detects configurations like yours and builds from source, though.
