### ISSUE TITLE
Ghostscript with x-11 version no longer available

### ISSUE THREAD

**Issue by keslers** [Homebrew/brew#6096]
I am working with Generic Mapping Tools.  Why is Ghostscript with x11 support no longer available for macOS 10.14.4?  The brew formula is specific for without x11.

**Comment by MikeMcQuaid** [comment]
No more options are provided in Homebrew/homebrew-core: https://brew.sh/2019/02/02/homebrew-2.0.0/

From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

Please always fill this out in future.
