### ISSUE TITLE
Better Output Format for brew info --installed

### ISSUE THREAD

**Issue by danielhelfand** [Homebrew/brew#6100]
# Better Output Format for brew info --installed 

As mentioned in this [issue](https://github.com/minishift/minishift/issues/3232) for `MiniShift`, the json output produced by running the following: `brew info --installed docker-machine-driver-xhyve --json` is a difficult format to interpret. 

In the `MiniShift` documentation for macOS [here](https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#for-macos), installing the `docker-machine-driver-xhyve` is verified by using `brew info --installed docker-machine-driver-xhyve`. However, as mentioned in the `MiniShift` issue above, this results in the following error: 
```
Error: `installed` cannot be passed without `json`.
```

I am not aware if there is a way to make the output for `brew info --installed` more human readable or if there is a more human readable way to verify the installation of a formulae. 

The goal would be to have something similar to what the documentation for `MiniShift` expects for output:

```
docker-machine-driver-xhyve: stable 0.3.3 (bottled), HEAD
Docker Machine driver for xhyve
https://github.com/zchee/docker-machine-driver-xhyve
/usr/local/Cellar/docker-machine-driver-xhyve/0.3.3 (3 files, 10.3MB) *
  Poured from bottle on 2017-08-18 at 14:46:20
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-driver-xhyve.rb
```

# The motivation for the feature

More human readable format to verify the installation of a homebrew formulae rather than json.

# How the feature would be relevant to at least 90% of Homebrew users

It would make the information returned by `brew info --installed` easier to interpret.

# What alternatives to the feature have been considered

If there is already is an alternative format for `brew info --installed`, that would address the issue.

**Comment by MikeMcQuaid** [comment]
`brew info $(brew ls)` will output what you want. A `brew info --installed` option doesn't make sense without `--json` as it outputs a potentially huge amount of information.

If you want to view `brew info` for a single formula: use `brew info docker-machine-driver-xhyve`.

**Comment by danielhelfand** [comment]
@MikeMcQuaid Thanks! This appears to be what I'm looking for: 

```
brew info $(brew ls) | grep docker-machine-driver-xhyve
```

Output:
```
docker-machine-driver-xhyve: stable 0.3.3 (bottled), HEAD
https://github.com/machine-drivers/docker-machine-driver-xhyve
/usr/local/Cellar/docker-machine-driver-xhyve/0.3.3_1 (7 files, 9MB) *
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-driver-xhyve.rb
    sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
    sudo chmod u+s /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
```

**Comment by MikeMcQuaid** [comment]
`brew info docker-machine-driver-xhyve` is what you are looking for.

In future please try `brew info --help` and `brew man`; they detail the options for the commands.
