### ISSUE TITLE
Building ffmpeg without libbluray

### ISSUE THREAD

**Issue by UnknownLocation** [Homebrew/brew#6101]
How to compile ffmpeg from brew without this heavy dependency? I need a build with a small set of libraries for transcoding only online video via youtube-dl. However, --without-libbluray flag doesn't exist.

**Comment by retokromer** [comment]
You can use a [tap](https://github.com/varenc/homebrew-ffmpeg).

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
