### ISSUE TITLE
subcommand completion is very slow

### ISSUE THREAD

**Issue by nhooyr** [Homebrew/brew#6106]
```
brew in<TAB>
```

Completion at `<TAB>` takes nearly a second or two.

I've narrowed it down to the `brew commands --quiet --include-aliases ` command in the completion script. It takes nearly 0.75s for me which is unreasonably high.

**Comment by colindean** [comment]
Please always complete the issue template. It helps the team more quickly assess the problem without having to request more information from you. Without the information requested in the issue template, this issue may be closed until you supply that information, preferably in the original text but a follow-up comment is acceptable, too.

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by nhooyr** [comment]
Come on, this is ridiculous, my bug report is very clear.

Here is the slow line: https://github.com/Homebrew/brew/blob/039885c95dc9ca4d80c2c3e1fa15a420b71414e0/completions/bash/brew#L803

**Comment by iMichka** [comment]
> Come on, this is ridiculous, my bug report is very clear.

Please watch your tone, and do not tell us that something is ridiculous. You removed the issue template, which leads the issue to be closed. These are the rules here. This is the only way for us to manage all the issues being opened during the day in a sane way.

If you think something is slow: please open a pull request to fix it, with a benchmark of the improvement. If nobody on our side is impacted by this specific slowness, it is unlikely that anybody will work on this for you.

**Comment by nhooyr** [comment]
> Please watch your tone, and do not tell us that something is ridiculous.

I apologize for my aggressive tone. My point was that I believed I provided enough information to easily debug this. The instant closure of the issue was very abrasive. You could have just requested I reread the issue template and include the relevant information and I would have done so.

Anyway, here is information you want:

```
$ brew config
HOMEBREW_VERSION: 2.1.2-8-g039885c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 039885c95dc9ca4d80c2c3e1fa15a420b71414e0
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6f34b1f9c73b7bcfe8fef1d15ef6ed7e3de7c6c8
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.4-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11
```

```
$ brew doctor
Your system is ready to brew.
```

```
$ time brew commands --quiet --include-aliases > /dev/null
        0.78 real         0.50 user         0.25 sys
```

**Comment by MikeMcQuaid** [comment]
> You removed the issue template, which leads the issue to be closed.

Furthermore: the issue template tells you that it will be closed if you don't fill it in. You either did not read it or you decided to ignore it. Neither are respectful of our time.

> I apologize for my aggressive tone.

Thank you for the apology.

> The instant closure of the issue was very abrasive.

Similarly, we find it abrasive when people don't fill in the issue template.

> It takes effort on your part to triage issues, but it also takes effort on mine to report them in the first place.

This is true. However, we're triaging many more issues than you are filing and you're asking for our help and not vice-versa.

Onto the actual issue itself:

> If you think something is slow: please open a pull request to fix it, with a benchmark of the improvement. If nobody on our side is impacted by this specific slowness, it is unlikely that anybody will work on this for you.

Agreed with this. "X is slow" isn't itself a bug or issue. Is it possible to noticeably improve this performance? Quite possibly. We'd welcome, review and provide help with a pull request for that if so.
