### ISSUE TITLE
docs: tap-pin still referred to in documentation

### ISSUE THREAD

**Issue by cblecker** [Homebrew/brew#6110]
https://docs.brew.sh/Taps still refers to and explains how to pin an entire tap, however, the command output throws an error saying it's been deprecated.

I don't know the motivations for deprecating the previous tap-pin functionality, so I don't feel comfortable updating the docs myself, but I wanted to advise that they are out of date.

**Comment by jonchang** [comment]
**Please always fill out the issue template**. Feel free to open a pull request suggesting this change. Tap pinning was deprecated in https://github.com/Homebrew/brew/pull/5925, for context.

**Comment by MikeMcQuaid** [comment]
Opened a PR in https://github.com/Homebrew/brew/pull/6111. Agreed with @jonchang it's always helpful to use the issue template but thanks for the issue regardless in this case, @cblecker.
