### ISSUE TITLE
HEAD is now at ea0b36f69 Merge pull request #6113 from amyspark/azure_mojave_only

### ISSUE THREAD

**Issue by 1191102363** [Homebrew/brew#6117]
Always follow the instructions above when installing

**Comment by 1191102363** [comment]
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Failed during: /usr/local/bin/brew update --force

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by Halpmewithdis** [comment]
help HEAD is now at 4973f6707 Merge pull request #6844 from MikeMcQuaid/download_strategy_typeerror
