### ISSUE TITLE
brew services start mongodb-community@4.0 fails - uninitialized constant

### ISSUE THREAD

**Issue by hemedani** [Homebrew/brew#6118]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I want to install mongodb from the [mongodb doc](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x) on mac os
it installed properly but brew services is not running and throw an error

# What happened (include command output)

it's throw an gem err for running `brew services start mongodb-community@4.0` 

`mongod` command run mongo daemon in foreground without issues 

<details>
  <summary>Command output</summary>
  <pre>
  
`brew doctor` says :
```shell
Warning: Some installed formulae are not readable:
  mongodb-community: uninitialized constant #<Class:0x00007f812bc009c8>::Gem
```
`brew services start mongodb-community@4.0` says :
```shell
Error: mongodb-community: uninitialized constant #<Class:0x00007f8ec1832820>::Gem
```
`brew services start mongodb/brew/mongodb-community` says :
```shell
Error: mongodb/brew/mongodb-community: uninitialized constant #<Class:0x00007fb657098110>::Gem
```
my brew config
```shell
HOMEBREW_VERSION: 2.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4025eadc2c3b9b71aa7029d7ddc6ede1cb88d482
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 35c9cbb38f446b1efe6432ed8c2b7a69eba6824e
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_121
macOS: 10.14.4-x86_64
CLT: N/A
Xcode: 10.2.1
```
  
  </pre>
</details>

# What you expected to happen

running mongo daemon in background as brew services

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew tap mongodb/brew
```

```
brew install mongodb-community@4.0
```

```
brew services start mongodb-community@4.0
```

mongo is installed but brew services is not working and for running mongo shell we most be run `mongod` command on another terminal tab

**Comment by MikeMcQuaid** [comment]
> * If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

This is the case so please report to https://github.com/mongodb/homebrew-brew instead.
