### ISSUE TITLE
Failed during: /usr/local/bin/brew update --force

### ISSUE THREAD

**Issue by earth2travis** [Homebrew/brew#6119]
- [X] reporting a bug others will be able to reproduce

This is not a `brew install`, Linux, `brew cask` or general `brew` problem. 

## [Reviewed all post within last 30 days on Discourse](https://discourse.brew.sh)

- [Reinstalling homebrew & caskroom, and getting all packages/apps back?](https://discourse.brew.sh/t/reinstalling-homebrew-caskroom-and-getting-all-packages-apps-back/4697)
- [Why I can’t install homebrew successful?](https://discourse.brew.sh/t/why-i-cant-install-homebrew-successful/4645)
- [Why the default installation path is better?](https://discourse.brew.sh/t/why-the-default-installation-path-is-better/4581)

### Learned

- [Homebrew Bundle](https://github.com/Homebrew/homebrew-bundle) easily installs dependencies
- You can’t install or use Homebrew unless you have a functioning network
- Something about enlightening bottles

## Issue 

Trying to fix some permissions issues on my MacBook (Mojave Version 10.14.4). Completely hosed my dev machine so I was attempting to rebuild. 

`xcode-select version 2354`

Downloading and installing Homebrew...

## Error

```shell
HEAD is now at 7da51b4a7 Merge pull request #6092 from gmkey/patch-1
Failed during: /usr/local/bin/brew update --force
```

## Search

"Failed during: /usr/local/bin/brew update --force"

### Related Issues

- [20393](https://github.com/Homebrew/homebrew-core/issues/20393)
- [4156](https://github.com/Homebrew/brew/issues/4156)
- [35596](https://github.com/Homebrew/homebrew-core/issues/35596)
- [5649](https://github.com/Homebrew/brew/issues/5649)

1. Uninstalled Homebrew

```shell
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
```

```shell
==> Homebrew uninstalled!
The following possible Homebrew files were not deleted:
/usr/local/.yardopts
/usr/local/bin/
/usr/local/.com.apple.installer.keep
/usr/local/include/
/usr/local/etc/
/usr/local/Homebrew/
/usr/local/n/
/usr/local/.gitignore
/usr/local/lib/
/usr/local/.travis.yml
/usr/local/share/
You may wish to remove them yourself.
```

2. Removed `Homebrew' directory from '/usr/local/'

### Trying to (and why)

[Install](https://docs.brew.sh/Installation) Homebrew to manage packages on personal development machine. 

### What happened (include command output)

Denied permission and installation errors

### Expected

Successful installation of Homebrew

### Reproduction Instructions

1. Navigate to directory: `/usr/local`

```shell
/usr/local
```
2. List all files

```shell
ls -a
```

```shell
.				bin
..				etc
.com.apple.installer.keep	include
.gitignore			lib
.travis.yml			n
.yardopts			share
```
3. Untar anywhere

```shell
mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
```

```shell
mkdir: homebrew: Permission denied
```

4. Searched on StackExchange

- [sudo: /var/db/sudo/ts is owned by uid](https://apple.stackexchange.com/questions/307933/sudo-var-db-sudo-ts-is-owned-by-uid-501-should-be-0)

```shell
cd /var/db/sudo/
```

```shell
ls -ln
```

```shell
total 0
drwx------  6 0  0  192 May  1 22:47 ts
```

```shell
ls -la
```

```shell
total 0
drwx--x--x   3 nautes  wheel    96 Mar 28 03:38 .
drwxr-xr-x  94 root    wheel  3008 May  2 03:58 ..
drwx------   6 root    wheel   192 May  1 22:47 ts
```

```shell
sudo chown -R root:wheel /var/db/sudo/ts/
```

3. Untar anywhere

```shell
mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
```

```shell
mkdir: homebrew: Permission denied
```

```shell
sudo mkdir Homebrew
```

```shell
sudo mkdir Homebrew
```

```shell
cd Homebrew
```

```shell
curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1
```

See: [error-exit-delayed-1.md](https://gist.github.com/earth2travis/a4e39e37b2ecdea1702dd9e0a5042ca3)

```shell
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

```shell
echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

```shell
cd Homebrew
```

```shell
curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1
```

See: [error-exit-delayed-2.md](https://gist.github.com/earth2travis/a4c38bbd475666df5eab20d1d77007b0)

**Comment by MikeMcQuaid** [comment]
I don't really understand your current issue using the format you have. Can you paste the last commands that failed and their full output? Thanks.
