### ISSUE TITLE
line after each `brew cask info` (as for `brew info`)

### ISSUE THREAD

**Issue by vogler** [Homebrew/brew#6126]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Show the info of multiple casks, read them and visit the website for some.

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
brew cask info git-it gitahead gitblade gitbox gitee gitfinder gitfox gitifier gitnote gitscout gitx nudgit rowanj-gitx smartgit-rc subgit
git-it: 4.4.0
https://github.com/jlord/git-it-electron
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/git-it.rb
==> Name
Git-it
==> Artifacts
Git-it-Mac-x64/Git-it.app (App)
gitahead: 2.5.5
https://github.com/gitahead/gitahead
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gitahead.rb
==> Name
GitAhead
==> Artifacts
GitAhead.app (App)
gitblade: 1.0.6
https://gitblade.com/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gitblade.rb
==> Name
GitBlade
==> Artifacts
GitBlade.app (App)
gitbox: 1.6.2
http://gitboxapp.com/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gitbox.rb
==> Name
Gitbox
==> Artifacts
Gitbox.app (App)
...
  </pre>
</details>

# What you expected to happen

There should be a new line after each info so that it's easier to go through them. `brew info` does this - `brew cask info` somehow not.

# Step-by-step reproduction instructions (by running `brew` commands)

E.g.
`brew cask info git-it gitahead gitblade gitbox gitee gitfinder gitfox gitifier gitnote gitscout gitx nudgit rowanj-gitx smartgit-rc subgit`

**Comment by issyl0** [comment]
This is done in the main `brew info` command by [`puts unless i.zero?`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/info.rb#L79-L80), which inserts a new line if there's more than one formula passed as an argument. This looks like it could be fairly quickly replicated in [brew cask's info command](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/cmd/info.rb#L20-L23) if that switched to using `.each_with_index` instead of a plain `.each` loop.

**Comment by MikeMcQuaid** [comment]
> This looks like it could be fairly quickly replicated in [brew cask's info command](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/cmd/info.rb#L20-L23) if that switched to using `.each_with_index` instead of a plain `.each` loop.

This seems like the best solution 👍

**Comment by issyl0** [comment]
@MikeMcQuaid :+1: I’ll do a PR given I still have the code up.
