### ISSUE TITLE
depends_on should be satisfied by system binaries in PATH

### ISSUE THREAD

**Issue by 0xdevalias** [Homebrew/brew#6129]
# A detailed description of the proposed feature

When a formulae has a `depends_on` ([`brew` ref](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#specifying-other-formulae-as-dependencies), [cask ref](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/depends_on.md)) requirement, check if that can be satisfied by binaries in the existing `PATH` (new feature?), before falling back to installing a new `brew` formulae to support it (existing functionality).

For example, if I have a `depends_on "node"`, and I already have a `node` binary in my `PATH`, then homebrew shouldn't go and install a new one just to satisfy that.

# The motivation for the feature

I was initially looking to see how i could stop `yarn` installing `node`, since I already use `nodenv`. This lead me down a rabbit-hole of threads (ref: https://github.com/yarnpkg/yarn/issues/1116) about custom `depends_on` (https://github.com/Homebrew/brew/pull/1408), and adding/removing (https://github.com/Homebrew/homebrew-core/issues/31510) options on formulae.

Looking at [the current master for the yarn formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb#L10), it has:
```
depends_on "node"
```

So as per the above thread, I want to attempt to not have `brew` install this. Seemingly the only current way to do that is with an unsupported dev flag (`--ignore-dependencies`):
```
⇒  brew install yarn --ignore-dependencies
Warning: --ignore-dependencies is an unsupported Homebrew developer flag!
Adjust your PATH to put any preferred versions of applications earlier in the
PATH rather than using this unsupported flag!
```

It talks about adjusting my `PATH` to put preferred versions of applications earlier, which seems totally valid and a useful idea.

But when I look at `brew info yarn`, it tells me the dependency isn't met. Presumably because I don't have a `brew`-managed version of node installed:
```
⇒  brew info yarn
..snip..
==> Dependencies
Required: node ✘
```

Even though I have one in my `PATH` (and it's before all homebrew related paths):
```
⇒  which node
/Users/devalias/.nodenv/shims/node

⇒  node --version
v8.12.0
```

```
⇒  echo $PATH
/Users/devalias/.nodenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Obviously, when it comes to running them, my already installed version will be correctly preferenced by my `PATH` and will work, but now I have this excess/never used homebrew version laying around cluttering up my system.

# How the feature would be relevant to at least 90% of Homebrew users

Would make use of existing installs, rather than only working for `brew`-managed installs.

# What alternatives to the feature have been considered

- Using `--ignore-dependencies`

**Comment by jonchang** [comment]
This can be solved in a third-party tap by using a custom Requirement. This wouldn't be accepted in Homebrew/core since this would cause many support problems with e.g., random or broken `node` installs on end-users' machines. This has historically been a problem for Homebrew as the support requests for `depends_on` ruby, python, perl, mpi, fortran, mysql and so on were overwhelming.

 See https://docs.brew.sh/Building-Against-Non-Homebrew-Dependencies; you can also search the issue tracker for "requirement" to see the history of the Great Requirement Deprecation.

**Comment by MikeMcQuaid** [comment]
> now I have this excess/never used homebrew version laying around cluttering up my system.

This is how every package manager works. Just ignore that `node` if you don't need it as Homebrew does.

**Comment by 0xdevalias** [comment]
How about just a power user option to say 'never install this dependency under any circumstance'? Like a 'blocklist'. Then I could block things if/as I need (eg. node), and not have to worry about it?

**Comment by MikeMcQuaid** [comment]
@0xdevalias The "power user" option is to create your own formulae that work however you want.

**Comment by 0xdevalias** [comment]
I get that if you’re not going to include it, you’re not going to include it. There is a very different reality to having to solve a problem in every single package it exists, vs a tool existing higher up that would allow people to solve the problem more wholistically, for their needs, without impacting on those that don’t need it/changing the current defaults.

Sorry for even raising an idea/asking though. Clearly it’s not welcome here. I’ll keep that in mind for future :)
