### ISSUE TITLE
Cleanup: Calling Formula.md5 is disabled!

### ISSUE THREAD

**Issue by rgormley** [Homebrew/brew#614]
- [ X] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [NA ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Running brew cleanup reports the following:

```
Error: Calling Formula.md5 is disabled!
Use Formula.sha256 instead.
/Users/rsg/Library/Caches/Homebrew/Formula/sshpass.rb:6:in `<class:Sshpass>'
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils.rb:153:in `odeprecated'
/usr/local/Library/Homebrew/utils.rb:161:in `odisabled'
/usr/local/Library/Homebrew/compat/md5.rb:3:in `md5'
/Users/rsg/Library/Caches/Homebrew/Formula/sshpass.rb:6:in `<class:Sshpass>'
/Users/rsg/Library/Caches/Homebrew/Formula/sshpass.rb:3:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/formulary.rb:227:in `from_rack'
/usr/local/Library/Homebrew/cleanup.rb:80:in `block in cleanup_cache'
/usr/local/Library/Homebrew/cleanup.rb:48:in `each'
/usr/local/Library/Homebrew/cleanup.rb:48:in `cleanup_cache'
/usr/local/Library/Homebrew/cleanup.rb:11:in `cleanup'
/usr/local/Library/Homebrew/cmd/cleanup.rb:20:in `cleanup'
/usr/local/Library/Homebrew/brew.rb:87:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by rgormley** [comment]
Gist here for brew config and brew doctor:

https://gist.github.com/rgormley/61e298cc6705e8d16b901c9c0b915089

**Comment by MikeMcQuaid** [comment]
@rgormley We no longer provide a formula for `sshpass` so you should probably `brew uninstall --force sshpass`.

**Comment by spuder** [comment]
I think the link for troubleshooting is now https://github.com/Homebrew/brew/blob/master/docs/README.md#troubleshooting
