### ISSUE TITLE
Homebrew GitHub Pages sites do not display all URLs correctly.

### ISSUE THREAD

**Issue by xama5** [Homebrew/brew#6140]
No idea where the docs are at, so I'm creating this issue here.

Since about 10 minutes ago all links on docs.brew.sh result in a 404.

Example: https://docs.brew.sh/Homebrew-on-Linux/

**Comment by faizanahemad** [comment]
+1 Facing the same issue.

**Comment by MikeMcQuaid** [comment]
This is a GitHub Pages issue that is being worked on. Please don't post 👍s.

**Comment by MikeMcQuaid** [comment]
Fixed now.
