### ISSUE TITLE
Add HOMEBREW_CURL_RETRIES

### ISSUE THREAD

**Issue by letmaik** [Homebrew/brew#6142]
# A detailed description of the proposed feature

Since brew uses `curl` to download bottles it would be useful to have a `HOMEBREW_CURL_RETRIES=n` environment variable which sets the `--retry <n>` flag of `curl`.

# The motivation for the feature

brew commands sometimes fail due to network issues. This is unfortunate in automated scenarios because wrapping brew as a whole in retry logic would also retry failed installations.

# How the feature would be relevant to at least 90% of Homebrew users

Hard to quantify, but personally I experienced many failed CI builds caused by brew failing due to sporadic network issues. This wastes people's time as each failed build has to be looked at.

# What alternatives to the feature have been considered

Wrapping the whole command in a retry. This is more a hack and would also retry long source builds in case they failed, and in effect make CI builds unnecessarily long (and maybe even hit CI time limits) and obscure logs.

**Comment by MikeMcQuaid** [comment]
This seems like a good idea we'd accept a PR for!
