### ISSUE TITLE
allow link formula if force

### ISSUE THREAD

**Issue by meritozh** [Homebrew/brew#6152]
# A detailed description of the proposed feature

Allow link formula if user force to do it.

# The motivation for the feature

I understand the reason described in #4441. But I doubt the solution:

1. force link formula, cause some strange behavior only occurs on several formulas
2. if I pass the correct compiler flags, I must write macOS specific configurations in my _CMakeLists.txt_, etc.
3. why not just add a strong notice, let user install system headers first?
4. when people open an issue, notice them check whether them link force formula before, them should unlink and try again.

# How the feature would be relevant to at least 90% of Homebrew users

compatible.

# What alternatives to the feature have been considered

If people does not agree my suggestion, please just delete `--force` option. It doesn't works and confuse me.

**Comment by MikeMcQuaid** [comment]
Sorry, this is intentional behaviour.
