### ISSUE TITLE
Homebrew refuses to build formulas from source when Xcode 10.1 is installed

### ISSUE THREAD

**Issue by shawwn** [Homebrew/brew#6154]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I am trying to run `brew install <literally-anything>`, where `<literally-anything>` is a formula that tries to build from source.

# What happened (include command output)

Homebrew insists that Xcode be updated to 10.2, even though my Xcode 10.1 is perfectly fine. 

<details>
  <summary>Command output</summary>
  <pre>
  
$  brew install python@2
Error: Your Xcode (10.1) is too outdated.
Please update to Xcode 10.2.1 (or delete it).
Xcode can be updated from the App Store.
  
  </pre>
</details>

# What you expected to happen

It's absurd that Homebrew completely refuses to even *attempt* to build anything if Xcode 10.1 is installed. Not only does Xcode 10.1 work flawlessly for most builds, but all the devs I know seem to be running Xcode 10.1.

Why is it absurd for Homebrew to demand people upgrade their Xcode? Because in order to upgrade your Xcode, you have to upgrade your whole operating system:

![image](https://user-images.githubusercontent.com/59632/58069946-d018ba80-7b5c-11e9-8bb4-9d05fe29d953.png)

So what started out as a simple "Oh, I need to `brew install <x>`? No problem" quickly became "whyyyyy do I have to update my entire operating system *right now*? I have a crapload of editors and terminals open and it's insane that I have to reboot this instant with no recourse. Actually, it's insane that homebrew is forcing me to risk upgrading to the latest macOS, because the latest version of macOS *usually* has problems and I don't want to risk it."

# Step-by-step reproduction instructions (by running `brew` commands)

```brew install python@2```

(More like `brew install a package manager that gives users a workaround rather than forcing them to upgrade their whole operating system just to use basic build system functionality`)

**Comment by shawwn** [comment]
Thanks for ruining an otherwise productive night of hacking.

![](https://i.imgur.com/Y1P6s9q.jpg)

**Comment by shawwn** [comment]
That's ok, I didn't want to get anything done tonight anyway. /s

![image](https://user-images.githubusercontent.com/59632/58072760-4ec62580-7b66-11e9-843e-a0569d32db1d.png)

Time for a rousing game of "How long will it take to finish installing?" It's always exciting because it could be 2 minutes, it could be 40 minutes. Apple's progress bar will always seem like it's 70% done until it's finally done. Fun for the whole family.

**Comment by shawwn** [comment]
(inb4 closed as "this is intentional homebrew behavior.")

Look, I'm not saying that you should support every Xcode version. It would be silly to support Xcode 9 at this point. Even 10.1 is pretty reasonable. But Xcode 10.2 came out in *march*:

![image](https://user-images.githubusercontent.com/59632/58072968-f2173a80-7b66-11e9-978a-67f59a17f5aa.png)

And that's March 25, so pretty much April. Today, April 20th, is less than two months later. Is it *really* an intentional decision to force all macOS devs to upgrade to something that is less than two months old?

**Comment by shawwn** [comment]
....
![image](https://user-images.githubusercontent.com/59632/58073686-e298f100-7b68-11e9-957c-c7c57d7c276f.png)

The point of homebrew is to make developers more productive. It doesn't feel like a productive decision to force the entire developer community to upgrade to an Xcode version that is less than two months old. Nor does it seem rational to make this decision knowing that it requires a full operating system upgrade for most of those devs.

Sweet! The progress bar moved another pixel while I was typing this:

![image](https://user-images.githubusercontent.com/59632/58073828-43c0c480-7b69-11e9-89de-f988ef800c1f.png)

Maybe the gods of hacking will grace unto me the blessing of "being able to get back to work pretty soon."

**Comment by shawwn** [comment]
The gods said no.

![image](https://user-images.githubusercontent.com/59632/58074098-f1cc6e80-7b69-11e9-8340-72ad0aef0eba.png)

But that's ok, because that means round 2 of Game of Progress Bars!

![image](https://user-images.githubusercontent.com/59632/58074130-0d377980-7b6a-11e9-8bdb-b3a821ec263f.png)

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/brew/pull/5940 and https://github.com/Homebrew/brew/pull/6083 explain why this is done. The required version is Xcode 10.2 although our messaging will encourage you to upgrade to the latest version.

You need to [read our Code of Conduct](https://github.com/Homebrew/brew/blob/master/CODE_OF_CONDUCT.md) and adjust your tone in future comments or issues.

**Comment by shawwn** [comment]
I have read the code of conduct. Which parts do you feel this violates?

Also, why is tone more important to the project than building a good product that developers want to use?

**Comment by shawwn** [comment]
I have read the issues you linked. They do not explain why you force developers to upgrade their entire operating system just to use basic homebrew functionality. In fact, none of the criticisms listed in this issue seem to be addressed at all.

Is it Homebrew’s position that you are not allowed to criticize the choices of the project, even when those choices are ridiculous and harm developer productivity?

**Comment by MikeMcQuaid** [comment]
> Also, why is tone more important to the project than building a good product that developers want to use?

Because it's developed by volunteers in their free time.

**Comment by MikeMcQuaid** [comment]
> Is it Homebrew’s position that you are not allowed to criticize the choices of the project, even when those choices harm developer productivity?

The unedited version that was emailed to me:

> Is it Homebrew’s position that you are not allowed to criticize the choices of the project, even when those choices are ridiculous and harm developer productivity?

"those choices are ridiculous" when you've just been warned about your tone means you're no longer welcome in this community.
