### ISSUE TITLE
Support `brew cask --cache <cask>` command

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/brew#6157]
Currently we have `brew --cache <formula>` command to print the local path for downloaded artefact. For example:

```
$ brew --cache gcc
/Users/chengxu/Library/Caches/Homebrew/downloads/73106c6dda7b91002502638469c02b5e352f8d7651ca7b93dcc4284d1501bb8a--gcc-9.1.0.mojave.bottle.tar.gz
```

It would be beneficial to support the same function in the cask. The reason is that some casks are notoriously hard to download. `mactex` is one of such casks due to its large size and unstable mirrors. Therefore, in such case, users may want to download the files in other means such as BitTorrent or using local cache. However, it is non-trivial to let brew cask use such external resource. If `brew cask --cache` command is support, we could do just:
```
cp <downloaded file> $(brew cask --cache <cask>)
```

**Comment by MikeMcQuaid** [comment]
`brew --cache --cask` would be another option. Would accept a PR for this. CC @homebrew/cask for thoughts.

**Comment by MikeMcQuaid** [comment]
Also, @xu-cheng: please always use the feature request template.

**Comment by vitorgalvao** [comment]
Fine by me.
