### ISSUE TITLE
brew install <URL> should automatically imply --build-from-source

### ISSUE THREAD

**Issue by mcandre** [Homebrew/brew#6161]
When the user explicitly instructs Homebrew to install a formula from a special URL, then Homebrew should not ignore the request and build from a separate binary package. Homebrew should automatically infer the `--build-from-source` flag and respect the user's wishes.

**Comment by fxcoudert** [comment]
Installing from a URL will respect the content of the formula, as it should. If the formula provides bottles, they will be used. If the formula does not point to bottles, it will build from source.

**Comment by MikeMcQuaid** [comment]
Please also always fill out the issue template, @auxten.
