### ISSUE TITLE
HOMEBREW_GIT is not picked up by brew config

### ISSUE THREAD

**Issue by cmbernard333** [Homebrew/brew#6167]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Trying to run a minimal `brew` environment with the intention of using local recipes and `brew cask`. This is deployed from a zip snapshot from github.com/Homebrew/brew. This includes the latest git from git-scm.com.

Casks can be dependency free and do not require the XCode developer tools in many cases.

# What happened (include command output)

The command `brew --config`  does not show git is installed.

<details>
  <summary>Command output</summary>
  <pre>
  
Christians-Mac:brew-master christianbernard$ brew --config
HOMEBREW_VERSION: >=1.7.1 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap: N/A
HOMEBREW_PREFIX: /Users/christianbernard/Downloads/brew-master
HOMEBREW_CELLAR: /Users/christianbernard/Downloads/brew-master/Cellar
HOMEBREW_REPOSITORY: /Users/christianbernard/Downloads/brew-master
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: 1
HOMEBREW_NO_COLOR: 1
HOMEBREW_NO_EMOJI: 1
HOMEBREW_NO_INSECURE_REDIRECT: 1
CPU: dual-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: N/A
Git: N/A
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.5-x86_64
CLT: N/A
Xcode: N/A
  
  </pre>
</details>

# What you expected to happen

I would assume that `brew --config` uses `HOMEBREW_GIT` to detect and use `git` as the SCM shim clearly is, but `brew --config` does not find it.

# Step-by-step reproduction instructions (by running `brew` commands)

I have a script that sets some variables for the minimal environment

```
Christians-Mac:brew-master christianbernard$ cat ~/Scripts/homebrew-cask.env 
#!/bin/bash
source ~/Scripts/util-functions.sh
BREW_DIR=$HOME/Downloads/brew-master
GIT_DIR=$HOME/Downloads/git-master
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_COLOR=1
export HOMEBREW_NO_EMOJI=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK=1
export HOMEBREW_GIT=${GIT_DIR}/git
# export PATH=${BREW_DIR}:$PATH
add_to_path ${GIT_DIR}
eval $(${BREW_DIR}/bin/brew shellenv)
Christians-Mac:brew-master christianbernard$ which brew
/Users/christianbernard/Downloads/brew-master/bin/brew
Christians-Mac:brew-master christianbernard$ which git
/Users/christianbernard/Downloads/git-master/git
Christians-Mac:brew-master christianbernard$ ./Library/Homebrew/shims/scm/git --version
git version 2.6.2
```
In the above output `brew` and `git` are in the path and the shim for `git` also can return the version.

**Comment by MikeMcQuaid** [comment]
`HOMEBREW_GIT` is not a documented/supported variable for this purpose, sorry. `HOMEBREW_FORCE_BREWED_GIT` may be what you're looking for.
