### ISSUE TITLE
lib curl with Apple Secure Transport fails

### ISSUE THREAD

**Issue by smuellerDD** [Homebrew/brew#6170]
# What you were trying to do (and why)

Use lib curl with Apple Secure Transport by setting a server and client certificate. (i.e. brew install curl).

# What happened (include command output)

Please see bug discussion at https://github.com/curl/curl/pull/3933

# What you expected to happen

Please see bug discussion at https://github.com/curl/curl/pull/3933

Please apply the patch provided there.

**Comment by MikeMcQuaid** [comment]
We will consider including this patch once it has been merged into curl. In future please fully explain the issue rather than just linking elsewhere and fill out the full issue template (which would direct you to filing this as Homebrew/homebrew-core). Thanks!
