### ISSUE TITLE
error: python is already installed from !

### ISSUE THREAD

**Issue by Aiamjay** [Homebrew/brew#6171]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I tried to install jupyter by using brew, brew install jupyter.

# What happened (include command output)

An error occured, 
Error: python is already installed from
Please `brew uninstall python` first."

<details>
  <summary>Command output</summary>
  <pre>
  
  Before using jupyter, I've already install python3.6 by using brew. And I've been using python3 for a while. Now I cannot just simply uninstall python3. So, since python is already exist, why brew just skip the installing of python?  
  
  </pre>
</details>

# What you expected to happen

I want jupyter to be installed on my mac with my current python environment unchanged.

# Step-by-step reproduction instructions (by running `brew` commands)

brew update
brew install jupyter

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by Aiamjay** [comment]
I've provided all the infos and details. Could you please help me find out the reason?

**Comment by iMichka** [comment]
> ran brew config and brew doctor and included their output with your issue?

No you did not.

**Comment by amitsharma8891** [comment]
Getting same error on `brew install php`

**Comment by ivanovaos** [comment]
Same error with brew install googler. 
I have python2(2.7) and python3(3.7) installed on mac os x mojave (v 10.14). I also have anaconda. Python3 locations: 
```
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
/usr/local/bin/python3
```
