### ISSUE TITLE
Can fish shell completions live in this repo?

### ISSUE THREAD

**Issue by lwolfsonkin** [Homebrew/brew#6172]
# A detailed description of the proposed feature

Currently, the fish shell completions for Homebrew exist primarily in two locations (of which I'm aware): the [main fish shell repo](https://github.com/fish-shell/fish-shell/blob/master/share/completions/brew.fish) and an [extensive external repo](https://github.com/laughedelic/brew-completions/blob/master/completions/brew.fish). I would propose combining these two into fish shell completions that would live here alongside [the bash and zsh completions in the completions directory](https://github.com/Homebrew/brew/tree/master/completions).

# The motivation for the feature

The completions existing bundled with the fish shell itself (which doesn't ship updates so often) can cause the completions to go out of date, especially when there are breaking API changes (like the `brew cask search` removal) that the completions would need to (relatively) swiftly deal with. Having the completions exist with Homebrew itself (which is nearly always up to date) would certainly alleviate this.

# How the feature would be relevant to at least 90% of Homebrew users

Having functional and up to date completions for all the most popular shells is certainly of benefit to most Homebrew users.

# What alternatives to the feature have been considered

Leaving the completions in their aformentioned locations.

# Additionally

I would be totally willing to author this PR, and I would be interested in the feedback of @MindTooth and @laughedelic who primarily authored the aforementioned completions.

**Comment by MindTooth** [comment]
That would be a better fit for sure.  I've submitted changes that won't be included until the next minor feature release, making the completion "broken" as of now.

Having my 👌 .  Good initiative.

**Comment by MikeMcQuaid** [comment]
I would be 👍 to this happening if all the upstream sources agree. Closing in favour of a PR, thanks!

**Comment by lwolfsonkin** [comment]
@MikeMcQuaid  I was just going to get to doing this, but had a quick question.

How would/does Homebrew deploy this? Can it use the same mechanism as `fish_completion.install` to install the completions in the right place and do so whenever Homebrew upgrades itself? Do the bash/zsh completions do this with `bash_completion.install` and `zsh_completion.install` respectively?

I figured that the fact that this isn't a package but part of Homebrew itself may make it a bit different.

Thanks!

**Comment by MikeMcQuaid** [comment]
See https://github.com/Homebrew/brew/tree/master/completions https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/update-report.rb#L138-L171  https://github.com/Homebrew/brew/blob/14755541b0e786e190d415a6d9d74c2e5023802a/Library/Homebrew/utils/link.rb#L62-L72
