### ISSUE TITLE
Archived repository removed?

### ISSUE THREAD

**Issue by tomyun** [Homebrew/brew#6173]
Just found out some of deprecated/archived Homebrew taps are entirely removed from GitHub. For example, my personal https://github.com/tomyun/Homebrew-games was once forked from https://github.com/Homebrew/Homebrew-games, but then now it shows up as if it was forked from https://github.com/ziz/homebrew-games which I didn't have any relations.

It's quite astounding that Homebrew decided to erase a part of its history and permanently remove access to old issues/PR which could have been useful for reference. I appreciate your hard work on moving the project forward and totally understand you sometimes need to leave something out, but it's hard to see good reasonings for what just happened this time. As I no longer have access to Slack channel since a while ago, could someone explain how it's been planned for what reasons?

**Comment by MikeMcQuaid** [comment]
These were removed but these repositories were still showing up and causing issues in bug reports and user errors.

Please always read/fill in the issue template which would direct questions like this to Discourse.
