### ISSUE TITLE
Question: Redirecting/Remapping dependencies?

### ISSUE THREAD

**Issue by ahundt** [Homebrew/brew#62]
I'm trying to work around an issue described in:
https://github.com/Homebrew/brew/issues/61
https://github.com/Homebrew/homebrew-science/pull/3512

If I'm maintaining my own tap per #61 , how can I redirect listed dependencies to the source I desire? If one app has a lot of dependencies, do I have to physically modify every `depends_on vtk` to `depends_on ahundt/vtk6` in `*.rb` files or is there a way to simplify that task via command line?

While this is specific to this dependency right now when using homebrew-science, it is a question about using the brew command itself for this task.

**Comment by mikemcquaid** [comment]
> do I have to physically modify every depends_on vtk to depends_on ahundt/vtk6 in *.rb files or is there a way to simplify that task via command line?

Yes, unfortunately.

**Comment by ahundt** [comment]
Could this question be converted to a feature request to that effect? 

No worries if you think it may not be worthwhile, or if changes based on #60 render this point moot.  Either way, at least the manual solution should work so thanks!

**Comment by mikemcquaid** [comment]
Will discuss this more in https://github.com/Homebrew/brew/issues/60.
