### ISSUE TITLE
brew install ideviceinstaller failure

### ISSUE THREAD

**Issue by acekingke** [Homebrew/brew#6201]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)
I install the flutter env , all steps are success but brew install ideviceinstaller failure
The config result is here:
```
➜  development brew config
HOMEBREW_VERSION: 2.1.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: d5a90f6f4af0a8e3d0ff1d806fb65e1b3bdbbe42
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 00d5cffd9b900f1934506b7c559dcc66fe8d6d20
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.7.0_79
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
```

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  ➜  development brew install ideviceinstaller 
==> Installing dependencies for ideviceinstaller: usbmuxd, libimobiledevice and libzip
==> Installing ideviceinstaller dependency: usbmuxd
==> Downloading https://homebrew.bintray.com/bottles/usbmuxd-1.0.10_1.mojave.bot
Already downloaded: /Users/kyc/Library/Caches/Homebrew/downloads/4c553d1494698a85e85d8dc6de76b96e23ab1ac6450b0f8200050c6cc994e2fe--usbmuxd-1.0.10_1.mojave.bottle.tar.gz
==> Pouring usbmuxd-1.0.10_1.mojave.bottle.tar.gz
cp: /usr/local/Cellar/usbmuxd/./1.0.10_1/bin/iproxy: Permission denied
cp: /usr/local/Cellar/usbmuxd/./1.0.10_1/lib/pkgconfig/libusbmuxd.pc: Permission denied
cp: /usr/local/Cellar/usbmuxd/./1.0.10_1/lib/libusbmuxd.4.dylib: Permission denied
cp: /usr/local/Cellar/usbmuxd/./1.0.10_1/lib/libusbmuxd.a: Permission denied
Error: Failure while executing; `cp -pR /var/folders/2b/1y4yppdd7zq7k9xmggqp0hqh0000gn/T/d20190601-23121-882ecb/usbmuxd/. /usr/local/Cellar/usbmuxd` exited with 1. Here's the output:
cp: /usr/local/Cellar/usbmuxd/./1.0.10_1/bin/iproxy: Permission denied
cp: /usr/local/Cellar/usbmuxd/./1.0.10_1/lib/pkgconfig/libusbmuxd.pc: Permission denied
cp: /usr/local/Cellar/usbmuxd/./1.0.10_1/lib/libusbmuxd.4.dylib: Permission denied
cp: /usr/local/Cellar/usbmuxd/./1.0.10_1/lib/libusbmuxd.a: Permission denied

Warning: Bottle installation failed: building from source.
==> Downloading https://www.libimobiledevice.org/downloads/libusbmuxd-1.0.10.tar
Already downloaded: /Users/kyc/Library/Caches/Homebrew/downloads/134bead73c944ab56dbdca5fa6798689e28a2ea209521f255b72712aaec4c02b--libusbmuxd-1.0.10.tar.bz2
==> Downloading https://github.com/libimobiledevice/libusbmuxd/commit/4397b3376d
Already downloaded: /Users/kyc/Library/Caches/Homebrew/downloads/9a1471dea3f507c0c5af79f3451f52e1fd0fc3fc6eaea873b013f187ea62e3a7--4397b3376dc4.patch
==> Patching
==> Applying 4397b3376dc4.patch
patching file common/socket.c
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/usbmuxd/1.0.10
==> make install
Error: File exists @ dir_s_mkdir - /usr/local/Cellar/usbmuxd/1.0.10_1/.brew
  
  </pre>
</details>

# What you expected to happen
No error

# Step-by-step reproduction instructions (by running `brew` commands)
```
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
```
the all success , then run 
`  brew install ideviceinstaller`

**Comment by MikeMcQuaid** [comment]
> * If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose.

This should be reported to homebrew-core.

> * ran `brew doctor`, fixed all issues and can still reproduce the problem?

You have not done this.

> cp: /usr/local/Cellar/usbmuxd/./1.0.10_1/bin/iproxy: Permission denied
> 
> cp: /usr/local/Cellar/usbmuxd/./1.0.10_1/lib/pkgconfig/libusbmuxd.pc: Permission denied

You will need to fix these errors with your local permissions.
