### ISSUE TITLE
Fortran should respect `--cc=...`

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/brew#6207]
The purpose of this issue is to test the waters, and foster discussion before I jump into coding.

# A detailed description of the proposed feature

Ensure that when a user passes `-cc=...` (which I realize is 100% unsupported) should also adjust which gfortran gets used. Currently I think the shims/superenv force `gfortran` as the compiler, which is not present for versioned GCCs.

# The motivation for the feature

Fortran does not have a standardized ABI, and GFortran's RTLs have been getting soversion bumps recently with every major GCC release. Furthermore, some packages install binary modules (think pre-compiled header files) which may not portable between major versions of GFortran. Allowing (unsupported) users to build formula with older gcc and g++ but not gfortran seems unfair.

For some projects, and using CI services like travis CI, sometimes one needs to build with an older GFortran. Being able to build libraries like MPICH this way would be nice.

# How the feature would be relevant to at least 90% of Homebrew users

It wouldn't... 

# What alternatives to the feature have been considered

Currently, I think the only way I can achieve this locally is through building outside of the superenv, even if I modify the formula to depend on gcc@8 and unlink gcc.

**Comment by MikeMcQuaid** [comment]
This seems fine as long as e.g. the `clang` case is handled accordingly.

**Comment by zbeekman** [comment]
I think the clang case would just use the latest GFortran. No obvious way how to map a clang version to GFortran. Once f18 (officially accepted into the llvm project) gets released and is stable and in Homebrew then there may be additional things to discuss/consider.

**Comment by tueda** [comment]
I am struggling with installing `open-mpi` together with `gcc@9` on Linux. I think it is best if the `--cc=gcc-9` option would select `gfortran-9` and the following commands work:
```shell 
brew install gcc@9
brew install open-mpi --only-dependencies
brew install open-mpi --build-from-source --cc=gcc-9
```

**Comment by zbeekman** [comment]
@tueda: I still haven't implemented this feature yet, but I recently gained more experience and insight as to what happens on Linux.

If my understanding is correct, on linux the compiler used is, from lowest to highest precedence:

- System C/C++/Fortran compiler
- Brewed gcc@<version>, with most recent versions taking precedence over older versions, with the one possible caveat that the alias for the default gcc, currently gcc@5, may take the highest precedence.
- Brewed gcc (this is currently gcc@5) will always be used if present.

@sjackman can correct me if I happen to have misspoken.

As a consequence of this, if your OS/machine supports the latest GCC (gcc@9, currently) without issues, then my recommendation would to never install the `gcc` formula on linux, and, after a fresh install of Homebrew on linux, install `gcc@9`, and then all of your packages will be built with `gcc@9`. You may run into problems if you pour bottles with non-C code on linux as they will be built with gcc 5, but hopefully Homebrew will see you don't have gcc (gcc@5) installed and compile things with runtime dependencies on gcc from source.

So the TL;DR of it is basically this: if you uninstall `gcc` and then run the commands you listed you should end up in the state you are looking for. The caveat here is that if you have a bunch of stuff that was compiled or poured from a bottle with runtime dependencies on gcc those all may break.

**Comment by tueda** [comment]
@zbeekman Thank you for sharing this information.
Unfortunately, in the current case, on CentOS 7, I have already many pieces of stuff poured from bottles and I am not sure which one may have runtime dependencies on gcc (all?), so the safest way seems to be building OpenMPI from the source outside Homebrew with using gcc-9, g++-9 and gfortran-9... (Actually I need an MPI implementation with gfortran >= 8.0.)
