### ISSUE TITLE
macOS Catalina and Scripting Language Runtime Deprecations

### ISSUE THREAD

**Issue by ming13** [Homebrew/brew#6211]
[macOS 10.15 deprecates scripting runtimes](https://developer.apple.com/documentation/macos_release_notes/macos_10_15_beta_release_notes).

> Scripting language runtimes such as Python, Ruby, and Perl are included in macOS for compatibility with legacy software. Future versions of macOS won’t include scripting language runtimes by default, and might require you to install additional packages. If your software depends on scripting languages, it’s recommended that you bundle the runtime within the app. (49764202)

Since Homebrew relies on Ruby to even download itself (as least brew.sh tells to do so) this might be a potential issue in the future.

* The least intrusive idea is to rewrite the installation process to download and install Ruby first.
* The most intrusive one is rewriting Homebrew in something like Rust to provide a single executable instead of requiring a runtime.

**Comment by vitorgalvao** [comment]
https://twitter.com/MacHomebrew/status/1136249501252038662:

> Homebrew will be just fine without system ruby. Minor re-write of our installer, in order, but we have a "portable ruby" that we can use in a pinch!

**Comment by pcr910303** [comment]
@vitorgalvao Sorry for spamming the issue thread, but does that mean I can’t install `ruby` with `brew`? That’s pretty concerning...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ladislas** [comment]
@pcr910303 no, you will be able to install ruby with brew.

see discussion [here](https://discourse.brew.sh/t/mac-os-deprecating-system-scripting-languages/4941)

**Comment by pcr910303** [comment]
@ladislas Thanks for pointing out 👍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
