### ISSUE TITLE
`brew upgrade FORMULA` should not upgrade FORMULA's dependents

### ISSUE THREAD

**Issue by leonklingele** [Homebrew/brew#6216]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

When upgrading a single formula (`brew upgrade $FORMULA`), brew currently also upgrades its dependents.

# What happened (include command output)

```sh
$ brew outdated -v | grep -v '\[pinned at .*\]'
nghttp2 (1.35.1) < 1.38.0
curl-openssl (7.65.0) < 7.65.1

$ brew upgrade nghttp2
==> Upgrading 1 outdated package:
nghttp2 1.35.1 -> 1.38.0
==> Upgrading nghttp2
[..]
==> Upgrading 1 dependent:
curl-openssl 7.65.0 -> 7.65.1
==> Upgrading curl-openssl
[..]
```

# What you expected to happen

When explicitly specifying formulas to upgrade, brew shouldn't upgrade their dependents.

**Comment by MikeMcQuaid** [comment]
> When upgrading a single formula (`brew upgrade $FORMULA`), brew currently also upgrades its dependents.

This is intentional. Not doing so will break binary packages.
