### ISSUE TITLE
brew rm --with-dependencies

### ISSUE THREAD

**Issue by hrls** [Homebrew/brew#6224]
# A detailed description of the proposed feature
Uninstall formula and its dependencies graph (if there no other packages depends from).

# The motivation for the feature
Usual task.

# What alternatives to the feature have been considered

https://stackoverflow.com/questions/7323261/uninstall-remove-a-homebrew-package-including-all-its-dependencies

**Comment by MikeMcQuaid** [comment]
> don't create a new one, please

@hrls ☝️
