### ISSUE TITLE
brew rm --with-dependencies

### ISSUE THREAD

**Issue by hrls** [Homebrew/brew#6225]
# A detailed description of the proposed feature

Uninstall formula and its dependencies graph (if there no other packages depends from).

# The motivation for the feature

Usual task, nuff said.

# How the feature would be relevant to at least 90% of Homebrew users

Batching few `brew rm` and `brew deps` commands and custom scripts into the single one basic feature.

# What alternatives to the feature have been considered

https://stackoverflow.com/questions/7323261/uninstall-remove-a-homebrew-package-including-all-its-dependencies

**Comment by MikeMcQuaid** [comment]
`brew bundle dump` and `brew bundle cleanup` is your best bet for this or combining `brew rm` and `brew deps` as you've mentioned.

In future please don't recreate issues when told not to by the bot.

**Comment by hrls** [comment]
Thank for your comment. `brew bundle` is nice feature. But how about the following?
Install FOO package. Then install BAR package. Then remove FOO package with all dependencies (except both BAR and FOO deps for sure).

**Comment by MikeMcQuaid** [comment]
We will not implement that feature, sorry.
