### ISSUE TITLE
The option --force-bottle does still install from source

### ISSUE THREAD

**Issue by jum** [Homebrew/brew#6227]
- [X ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X ] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I use brew upgrade --force-bottle to update my packages.

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
  
==> Upgrading 3 outdated packages:
exiftool 11.30 -> 11.50, glib 2.60.3 -> 2.60.4, imagemagick 7.0.8-48 -> 7.0.8-49
==> Upgrading exiftool
==> Downloading https://homebrew.bintray.com/bottles/exiftool-11.50.mojave.bottl
==> Downloading from https://akamai.bintray.com/1f/1f94aa499cdd29681af5edd77803e
######                                                                     9.4%
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
Error: Failed to download resource "exiftool"
Download failed: https://homebrew.bintray.com/bottles/exiftool-11.50.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-11.50

  
  </pre>
</details>

# What you expected to happen

If I specify --force-bottle it should try to install from a bottle and not fall back on network errors to attempt to install from source. In my case, installing from source requires many more packages which makes the network problems even worse.

# Step-by-step reproduction instructions (by running `brew` commands)

You will need a flakey network connection, I happen to have one in central america where this happens basically all the time on larger upgrades.

brew upgrade --force-bottle

Here is the output of brew doctor and brew config:

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libSwiftPM.dylib
$ brew config
HOMEBREW_VERSION: 2.1.5-11-g3ca10fb
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 3ca10fb59c1a6448d929f150b7bd1c7846a3db85
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aa43abb88be9e56f917b66d3ffbb1b397f31bb0f
Core tap last commit: 68 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AWS_ACCESS_KEY_ID: set
HOMEBREW_AWS_SECRET_ACCESS_KEY: set
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_101
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11
$

**Comment by MikeMcQuaid** [comment]
It did attempt to install the bottle but it failed. Consider setting `HOMEBREW_CURL_RETRIES` instead.
