### ISSUE TITLE
Don't exit with error code 1 if pin of formula exists

### ISSUE THREAD

**Issue by alexs77** [Homebrew/brew#6231]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Wanted to get my system up to date.

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
  
```bash
alex@Alexander-MacBookPro:~$ brew update; brew upgrade; echo Exit code: $?
Updated Homebrew from 755123d2c to 5abce1b51.
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
terragrunt ✔   ammonite-repl  angular-cli    cocoapods      helmfile       istioctl       lxc            presto         typescript     yarn
Error: Not upgrading 1 pinned package:
terragrunt 0.19.3
==> No packages to upgrade
Exit code: 1
```
  
  </pre>
</details>

# What you expected to happen

It should have exit with a code of 0, as it's not an error. A user set a
pin and brew **is** now behaving as expected; it updated a formula, but
not the installed package.

If there were other formulae that have been updated and all went well, then
this exit code "1" sending a wrong information.

# Step-by-step reproduction instructions (by running `brew` commands)

```bash
brew pin $some-package
# wait for some-package to be updated
brew update
brew upgrade
```

**Comment by MikeMcQuaid** [comment]
It is an error as we did not upgrade anything despite there being outdated passand you ran `brew upgrade`. Homebrew considers the command-line status codes part of our API so to change this would be a breaking change. Passing on this, sorry.

**Comment by alexs77** [comment]
Well, but OTOH it behaved exactly as expected - all the packages that could be upgraded were upgraded.

But yes, I guess that fixing/changing this might have a lot of consequences that aren't so easy to foresee.
