### ISSUE TITLE
brew should respect DEVELOPER_DIR

### ISSUE THREAD

**Issue by dbalakirev** [Homebrew/brew#6241]
# A detailed description of the proposed feature

We are installing multiple versions of Xcode for our CI/CD machines, so that projects can simply select one by specifying the DEVELOPER_DIR (pointing to the version they prefer).
We also rely on said environment variable during our ansible playbooks, so we do not change the globally selected xcode version all the time by using 'xcode-select -s ...'.

Homebrew seems to ignore this variable and can only be pursued to use a given Xcode version via xcode-select, which requires sudo permission and comes with a 'global change'.

# The motivation for the feature

By respecting DEVELOPER_DIR one would be able to work with homebrew in a more convenient way, without changing global state via a command that requires escalation rights.

# How the feature would be relevant to at least 90% of Homebrew users

All users who have to work on multiple projects with different SDK versions (hence different Xcode) and those providing infrastructure for this are affected.

# What alternatives to the feature have been considered

We are currently using xcode-select which is subpar for the reasons explained above.

**Comment by MikeMcQuaid** [comment]
We'd consider accepting a PR for this but a warning that it's likely to be a non-trivial amount of work and require significant amounts of testing.
