### ISSUE TITLE
Can't upgrade glib after canceling upgrade

### ISSUE THREAD

**Issue by albertmichaelj** [Homebrew/brew#6244]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

NOTE: I have also reported this issue [here](https://github.com/Homebrew/homebrew-core/issues/41071) at homebrew/homebrew-core because at the time, I thought that it was a problem with the formula. In the details you'll see why I do not think it is a problem with the formula.

# What you were trying to do (and why)

I was upgrading the formula `glib` and I had to cancel the upgrade do to having to shutdown my computer. I then tried to upgrade `glib` at a later time. Now `glib` fails to upgrade.

# What happened (include command output)

Now, `glib` will not upgrade with the following error:

<details>
  <summary>Command output</summary>
  <pre>

```
$ brew upgrade glib
==> Upgrading 1 outdated package:
glib 2.60.3 -> 2.60.4_1
==> Upgrading glib 
==> Downloading https://download.gnome.org/sources/glib/2.60/glib-2.60.4.tar.xz
Already downloaded: /Users/Michael/Library/Caches/Homebrew/downloads/0b257e9910276994ee9384ec16938c91bb73b22839e2c1002a21e6de8e8bb54a--glib-2.60.4.tar.xz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/6164294a7/glib/hardcoded-paths.diff
Already downloaded: /Users/Michael/Library/Caches/Homebrew/downloads/7a31846424d243e8c4ab3c738fb92a52aa1a0522d78af7b1ec92cc3729cad494--hardcoded-paths.diff
==> Patching
==> Applying hardcoded-paths.diff
patching file gio/gdbusprivate.c
patching file gio/xdgmime/xdgmime.c
patching file glib/gutils.c
==> meson --prefix=/Users/Michael/.brew/Cellar/glib/2.60.4_1 -Diconv=native -Dgio_module_dir=/Users/Michael/.brew/lib/gi
Last 15 lines from /Users/Michael/Library/Logs/Homebrew/glib/01.meson:
Checking if "strerror_r() returns char *" compiles: NO
Checking for function "snprintf" : YES
Checking for function "strcasecmp" : YES
Checking for function "strncasecmp" : YES
Header <sys/sysmacros.h> has symbol "major" : NO
Header <sys/mkdev.h> has symbol "major" : NO
Header <sys/types.h> has symbol "major" : YES
Header <dlfcn.h> has symbol "RTLD_LAZY" : YES
Header <dlfcn.h> has symbol "RTLD_NOW" : YES
Header <dlfcn.h> has symbol "RTLD_GLOBAL" : YES
Message: Checking whether to use statfs or statvfs .. statfs

meson.build:620:2: ERROR: Unknown compiler(s): [['clang']]

A full log can be found at /private/tmp/glib-20190618-86589-1ibp44/glib-2.60.4/build/meson-logs/meson-log.txt

Do not report this issue to Homebrew/brew or Homebrew/core!
```

  
  </pre>
</details>

However, I created a new installation of homebrew on the same machine, but different prefix (`~/brew-test` vs `~/.brew` for the original prefix), and `glib` installed just fine. So, it is not an issue with the `glib` formula or the `meson` build process.

# What you expected to happen

I expect to be able to upgrade `glib` after canceling an upgrade.

# Step-by-step reproduction instructions (by running `brew` commands)

Upgrade `glib` from `2.60.3` to `2.60.4` and cancel the upgrade at some point in between. Then try to upgrade again. I do not know if the point of cancellation is important.

# Output of `brew config` and `brew doctor`

Output of `brew config`:
```
HOMEBREW_VERSION: 2.1.6-11-g0b8ad71
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0b8ad710e3e56d4cc27b3251bc38a065100f6394
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ef210630ba36ecc2ff3f69e0fc67ddbfeeb2f4fd
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /Users/Michael/.brew
HOMEBREW_CELLAR: /Users/Michael/.brew/Cellar
HOMEBREW_REPOSITORY: /Users/Michael/.brew
HOMEBREW_DEV_CMD_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.22.0 => /Users/Michael/.brew/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1
macOS: 10.14.5-x86_64
CLT: 11.0.0.0.1.1559496560
Xcode: N/A
CLT headers: 11.0.0.0.1.1559496560
XQuartz: 2.7.11 => /opt/X11
```

Output of `brew doctor`:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libnnz11.dylib
  /usr/local/lib/libociei.dylib
  /usr/local/lib/libocijdbc11.dylib
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this unsupported configuration.


Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /Users/Michael/.brew/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/Users/Michael/.brew/sbin:$PATH"' >> ~/.zshrc

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install glib

Run `brew missing` for more details.
```

**Comment by MikeMcQuaid** [comment]
Sorry, this is too specific for your machine for us to debug. If you can narrow this down to something reproducible we can take a closer look.

**Comment by albertmichaelj** [comment]
@MikeMcQuaid I'm going to be honest, this is a really frustrating response. I understand if you can't reproduce a bug, but just closing an issue without asking for more specific details when I have included all of the information requested in a bug report feels very dismissive and arrogant.

If you would like more information, please ask for it, and I will do my best to provide it. However, I have reported an issue with this project. I have demonstrated that it is not a problem with the formula. I have provided all requested information. Just closing the issue is a very community unfriendly response and makes me much less likely to be involved in any future contributions or bugfixes to this project.

If there are any other maintainers who disagree with this policy, I would appreciate this issue being reopened so that we can do our best to identify and fix the problem instead of just dismissing it out of hand.

**Comment by MikeMcQuaid** [comment]
> feels very dismissive and arrogant.

Please do not call me "arrogant" on the issue tracker of the project I spend my free time running where you are asking me for help regardless whether you feel that way or not.

> when I have included all of the information requested
> ran brew doctor, fixed all issues and can still reproduce the problem?

Quoting your `brew doctor` output:

> If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.
> Warning: Your Homebrew's prefix is not /usr/local.
> Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this unsupported configuration.

- you did not fix the `brew doctor` issues as requested. this may be enough to fix your problem.
- you are running Homebrew in the non-default prefix which involves building from source. We do not support this configuration and we tell you to not file issues in the output you pasted on this issue.

> Just closing the issue is a very community unfriendly response and makes me much less likely to be involved in any future contributions or bugfixes to this project.

Similarly, I consider your comment and given the context I have provided above to be a maintainer unfriendly response.

**Comment by albertmichaelj** [comment]
@MikeMcQuaid That's perfectly fine. You can do whatever you'd like. I tried to report a bug (which has since been confirmed by a second person at my issue on meson https://github.com/mesonbuild/meson/issues/5506#issuecomment-504026316 opened up at the request of another homebrew maintainer), I demonstrated that it was not due to a custom location (making the brew doctor issue moot), and I'm trying my best to diagnose it and help improve brew. If you do not want valid bug reports from people willing to do whatever is needed to diagnose the problem, that's completely your prerogative, but I really think this kind of attitude is pretty unfortunate for the project.

I genuinely wish I could help more because I've really appreciated homebrew, and I am sorry for both of us that this interaction has gone so badly.

**Comment by MikeMcQuaid** [comment]
> I demonstrated that it was not due to a custom location

You also demonstrated that you could not reproduce it in another custom location.

> If you do not want valid bug reports from people willing to do whatever is needed to diagnose the problem

We do not want bug reports from people whose output tells them not to file bug reports. We do not consider them valid and that is the reason we have those messages.

What you need to be willing to do is:

- install Homebrew in the default location
- remove all the files noted by `brew doctor`
- install `glib` from the binary package

Given this issue is with building from source: this will not reproduce the problem. Again: this is why we told you not to submit a bug report.

> I really think this kind of attitude is pretty unfortunate for the project.

I'm sure you do think that. I happen to think that "this attitude" (of mine) is what has allowed me to remain a Homebrew maintainer for 10 years without burning out (longer than any other maintainer) and what enables this project to keep running.

> I am sorry for both of us that this interaction has gone so badly.

If you are sorry for something you have done: please say that. Do not express that you are sorry for me as that, intentionally or not, negates your attempt at an apology.

I am sorry that members of the open source community think it is OK to come into the issue tracker of a volunteer run project and throw various accusations at the volunteers just because we're not willing to do things your way.

I'm locking this issue because there's no way this interaction is going to move in a positive direction. If you file future issues where your own output tells you to not file issues and continue to call maintainers names like "arrogant" you will be blocked from submitting issues in future.
