### ISSUE TITLE
Better suggestion in command line when running brew install instead of brew cask install

### ISSUE THREAD

**Issue by wholewheattoast** [Homebrew/brew#6245]
# A detailed description of the proposed feature

Running `brew install kdiff3` returns the following error message;
```
$ brew install kdiff3
Error: No available formula with the name "kdiff3" 
Found a cask named "kdiff3" instead.
```

Suggesting to reword the error message to better guide the user to the correct command;
```
$ brew install kdiff3
Error: No available formula with the name "kdiff3" 
Found a cask named "kdiff3".
Try "brew cask install kdiff3", instead?
```

# The motivation for the feature

I use Homebrew frequently but do not often need to run `brew cask install`.  Every time I see the above error It takes me a bit to figure out I just need to run `brew cask install` instead.  Messaging this on the command line might reduce confusion and save users time.

# How the feature would be relevant to at least 90% of Homebrew users

I imagine many Homebrew users, especially casual or first time users, may benefit from more helpful and explicate messaging.

# What alternatives to the feature have been considered

I see that there have been issues filed to merge the funcionality of `brew install` and `brew cask install` like https://github.com/Homebrew/brew/issues/5716 but these seems to be a lighter touch, only effecting messaging.

**Comment by MikeMcQuaid** [comment]
Unfortunately this is a generic message that isn't just output on `brew install`. Any thoughts for improvements that could apply outside of `install`?

**Comment by zachauten** [comment]
If I recall correctly `brew install` and `brew info` are the only commands that can generate this error. The code for this message is in `extend/os/mac/missing_formula.rb`. Would it be possible to grab the argument brew was called with from the arg parser at the time the missing formula reason is being generated? If so we could generate a suggested command as a part of the reason.

I'd be happy to open a pull request for this.

**Comment by wholewheattoast** [comment]
That [commit](https://github.com/zachauten/brew/commit/ecef81a9516e5ce87ad9e138719b6a73520ed217)looks like a good option to me.  Sorry I don't know enough about Homebrew's internals to better answer @MikeMcQuaid's question above.

**Comment by zachauten** [comment]
Does anyone have an opinion on whether or not it should suggest a command for `brew info`? It already outputs the info so I don't know that there's much of a point.

**Comment by MikeMcQuaid** [comment]
@zachauten I'd say not output a command for `brew info` 👍
