### ISSUE TITLE
brew upgrade fails silently if the network is not working

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/brew#6253]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```brew config               
HOMEBREW_VERSION: 2.1.6-26-gf0d2032
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: f0d20329bb0e9f53d48cc6b387d2f5e3aba95aa8
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bacd78012c1023819dddc312ca35938914527290
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: /usr/bin/emacs
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11
```

```
brew doctor                
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libchkp.dylib
  /usr/local/lib/libifcore.dylib
  /usr/local/lib/libifcoremt.dylib
  /usr/local/lib/libifport.dylib
  /usr/local/lib/libifportmt.dylib
  /usr/local/lib/libimf.dylib
  /usr/local/lib/libintlc.dylib
  /usr/local/lib/libiompstubs5.dylib
  /usr/local/lib/libirc.dylib
  /usr/local/lib/libirng.dylib
  /usr/local/lib/libjlinkpic32.6.34.6.dylib
  /usr/local/lib/libjpeg.8.dylib
  /usr/local/lib/libmkl_avx.dylib
  /usr/local/lib/libmkl_avx2.dylib
  /usr/local/lib/libmkl_avx512.dylib
  /usr/local/lib/libmkl_blacs_mpich_ilp64.dylib
  /usr/local/lib/libmkl_blacs_mpich_lp64.dylib
  /usr/local/lib/libmkl_cdft_core.dylib
  /usr/local/lib/libmkl_core.dylib
  /usr/local/lib/libmkl_intel_ilp64.dylib
  /usr/local/lib/libmkl_intel_lp64.dylib
  /usr/local/lib/libmkl_intel_thread.dylib
  /usr/local/lib/libmkl_mc.dylib
  /usr/local/lib/libmkl_mc3.dylib
  /usr/local/lib/libmkl_rt.dylib
  /usr/local/lib/libmkl_scalapack_ilp64.dylib
  /usr/local/lib/libmkl_scalapack_lp64.dylib
  /usr/local/lib/libmkl_sequential.dylib
  /usr/local/lib/libmkl_tbb_thread.dylib
  /usr/local/lib/libmkl_vml_avx.dylib
  /usr/local/lib/libmkl_vml_avx2.dylib
  /usr/local/lib/libmkl_vml_avx512.dylib
  /usr/local/lib/libmkl_vml_mc.dylib
  /usr/local/lib/libmkl_vml_mc2.dylib
  /usr/local/lib/libmkl_vml_mc3.dylib
  /usr/local/lib/libnettle.6.3.dylib
  /usr/local/lib/libsvml.dylib
  /usr/local/lib/libtbb.dylib
  /usr/local/lib/libtbbmalloc.dylib
  /usr/local/lib/libtbbmalloc_proxy.dylib

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libpspell.la
```

# What you were trying to do (and why)

brew upgrade

while there was no network connectivity

# What happened (include command output)

Nothing - no command output at all

<details>
  <summary>Command output</summary>
  <pre>
    </pre>
</details>

# What you expected to happen

Some sort of warning or error message saying brew upgrade was unable to perform the request as the network was offline / site could not be reached, etc, in the same way that brew update does.

# Step-by-step reproduction instructions (by running `brew` commands)

turn network off

brew upgrade

**Comment by MikeMcQuaid** [comment]
How did the command fail; did it hang or terminate? Were there outdated packages or not? How long did it take before you killed it or it terminated?

**Comment by ralphrmartin** [comment]
It terminated apparently normally - but did nothing. It did so pretty quickly.

There were no packages that needed updating before a brew update, but a brew update then revealed some packages that did need updating:
brew upgrade normally performs a brew update before trying to do upgrades. What isn't apparent is that this automatically-performed brew update failed, and that brew upgrade was therefore presumably relying on its existing knowledge of the state of the packages.

**Comment by MikeMcQuaid** [comment]
It's expected behaviour that `brew upgrade` produces no output if there's nothing to upgrade. Similarly, if you have no network connection it's expected behaviour that it cannot update.

**Comment by ralphrmartin** [comment]
While I agree "It's expected behaviour that brew upgrade produces no output if there's NOTHING to upgrade. ", in this case there MAY be something to upgrade, and brew upgrade cannot tell without a network connection. 
The user may not be aware that the network is not working.
Thus, I still believe the correct behaviour is to report something like:
"Unable to determine what can be upgraded due to lack of network connection"
as without it, the user is unable to tell the difference between
"All packages are at their latest versions" and
"brew cannot tell whether packages are at their latest versions or not as the network is not working".
Please reconsider giving different output to distinguish these cases.
Indeed, it would be helpful if the network is working, to report 
"All packages are up to date".

**Comment by MikeMcQuaid** [comment]
> "Unable to determine what can be upgraded due to lack of network connection"

We cannot tell the difference between a lack of network connection, GitHub downtime, a misconfigured proxy and a misbehaving internet connection. We intentionally don't show output from auto-update failures in this way. If you run `brew update` explicitly you can see an error.
