### ISSUE TITLE
Brew uninstall cask helpful error message/fallback

### ISSUE THREAD

**Issue by teddy-error** [Homebrew/brew#6261]
# A detailed description of the proposed feature

When attempting to uninstall a cask with incorrect syntax a generic error message is displayed:

```shell
$ brew uninstall discord
Error: No such keg: /usr/local/Cellar/discord
```

A more useful error message might be to suggest the correct syntax:

```shell
$ brew uninstall discord
Found a cask named "discord" instead. Try `brew cask uninstall discord`
```

This would be just like the error-handling behavior exhibited when incorrectly installing a cask:

```shell
$ brew install discord
Error: No available formula with the name "discord-canary"
Found a cask named "discord-canary" instead.
```

# The motivation for the feature

I was removing a brew-installed application that stopped working and I was stumped for much longer than I would have imagined when seeing the error message above. Although I was well-aware of the need to specify `cask` when installing, I don't remember ever needing to use it when uninstalling.

I thought, because the app had totally broken, that some permissions issues might be preventing uninstall. And so I tried with the `--force` flag, which has does not fail and so has no output whatsoever. Then I was even more confused for a bit.

# How the feature would be relevant to at least 90% of Homebrew users

Any user that forgets `cask` syntax should be provided some hint towards using `brew` with success.

# What alternatives to the feature have been considered

As there should be no namespace conflicts, it might even be more beneficial to users to simply fallback to removing the cask installed application, rather than forcing the syntax change.

**Comment by MikeMcQuaid** [comment]
Please edit and comment on https://github.com/Homebrew/brew/issues/6260 rather than creating a duplicate issue.
