### ISSUE TITLE
Let upgrade and use Homebrew without matter the Mac's OS release

### ISSUE THREAD

**Issue by manueljordan** [Homebrew/brew#6267]
# Description

I use `Homebrew` since 2013, thanks so much for this!. I bought my MacBook Pro in 2013 and it came with `Mountain Lion`, 2 years later due `Homebrew` upgrade (it was my only reason to upgrade the MacOS version) I did an OS upgrade to the `El Capitan`, sadly the my Mac became 15% slower. 

I am a `Java` developer

Now this situation arised again, I need upgrade `Homebrew`, but it asks for `Mojave`, I am afraid if I do an upgrade about the Mac OS, my Mac is going to become more slower. 

Thus has no sense buy other Mac, my other tools, Java, STS (IDE), Jenkins, etc work fine until now in this old Mac.

# Motivation

Let a developer work in peace with `Homebrew` and any development tool (`Git`, `cURL`) and any type of server (`MySQL`, `PostgreSQL`, `redis`, `rabbitmq` )  without matter the version Mac' OS.

Therefore, letting for a developer upgrade `Homebrew` without matter the Mac' OS version

# How the feature would be relevant to at least 90% of Homebrew users

I think, a lot, it because my unique reason to do a `MacOS` upgrade was due `Homebrew`.
It to let any developer (`Java` world) install the servers and tools for development.

Thus would be fantastic have `Homebrew` generic for any `MacOS` release.

Now I can't because has no sense for me buy a new `MacBook Pro` to accomplish this goal.

# What alternatives to the feature have been considered

None. 

I am assuming behind the scene is involved compiled code to apply this constrain about the OS version.

Open for suggestions. Perhaps I am missing something.

Again thanks a lot for this tool.

**Comment by manueljordan** [comment]
Hello, the link shared is broken. 

I want fix this issue to avoid it be closed. 

Thank you

**Comment by vitorgalvao** [comment]
> I need upgrade `Homebrew`, but it asks for `Mojave`

Homebrew supports macOS from Mavericks on. What command did you run that asked you to update to Mojave? What was the exact messaging?

**Comment by manueljordan** [comment]
I have in my Mac currently the `El Capitan`, I have the following scenario with `brew doctor`

```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.


Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version.
```

I assumed the risk in some way, but is problematic.

I was able to upgrade some formulas (if my memory does not fail me `Git`) but I was not able to upgrade `MySQL`

**Comment by vitorgalvao** [comment]
Well, there you, that message explains everything. Some things will work, some won’t, and they’re not all under our control. In [MySQL’s case](https://github.com/Homebrew/homebrew-core/blob/bd0e85061856a653bc01a572d1a8d4eaee3073db/Formula/mysql.rb#L15L21), *they* don’t support your old macOS version, and presumably for good reason: there’s an incurred maintenance burden to supporting old versions.

Your request is definitely not relevant to 90% of users, as the template asks. Other tools evolve, and we need to evolve with them.

**Comment by manueljordan** [comment]
Thanks for the explanation. I understand the situation
