### ISSUE TITLE
Output of `brew list`

### ISSUE THREAD

**Issue by maxim-belkin** [Homebrew/brew#6275]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

### What you were trying to do (and why)

System: Homebrew on Linux
What I was trying to do: get a _clean_ list of installed formulae.
This issue doesn't seem to affect Homebrew on macOS

### What happened (include command output)

 
<details>
  <summary>brew list</summary>
  <pre>
ls /home/linuxbrew/.linuxbrew/Cellar
berkeley-db  groff    m4	pcre	    sqlite
bzip2	     less     man-db	perl	    unzip
dbus	     libbsd   meson	pkg-config  util-linux
expat	     libcap   ncurses	python	    vim
gdbm	     libffi   ninja	python@2    xz
gettext      libyaml  openssl	readline    zlib
gperf	     lua      patchelf	ruby
  </pre>
</details>

### What you expected to happen

I expected `brew list` to **not print `ls /home/linuxbrew/.linuxbrew/Cellar`** as the first line

### Step-by-step reproduction instructions (by running `brew` commands)

1. Install Homebrew on Linux in a Ubuntu 16.04.6 LTS Docker container
2. Install a few formulae
3. Run `brew list`

<details>
  <summary>brew config</summary>
  <pre>
HOMEBREW_VERSION: 2.1.6-44-g895467a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 895467ad9f57a9245c36def26abca729f2559fbb
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c276c7c49d044173f69b8fbacfc7c3e0faa00741
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/linuxbrew/.cache/Homebrew
HOMEBREW_LOGS: /home/linuxbrew/.cache/Homebrew/Logs
HOMEBREW_BINTRAY_KEY: set
HOMEBREW_BINTRAY_USER: maxim-belkin
HOMEBREW_DEVELOPER: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_VERBOSE: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.22.0 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 4.9.125-linuxkit x86_64 GNU/Linux
OS: Ubuntu 16.04.6 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A
  </pre>
</details>

<details>
  <summary>brew doctor</summary>
  <pre>
Your system is ready to brew.
  </pre>
</details>

**Comment by maxim-belkin** [comment]
Turns out I had `HOMEBREW_VERBOSE` set...

**Comment by yumitsu** [comment]
I have the same problem. Thanks for your help, @maxim-belkin.
Althought such  is look pretty @all
