### ISSUE TITLE
brew upgrade should have a '--no-dependents' option

### ISSUE THREAD

**Issue by nmusolino** [Homebrew/brew#6279]
# A detailed description of the proposed feature

Currently, when a user runs `brew upgrade <package>`, homebrew will upgrade all the package's dependents, i.e. all those packages that depend on `<package>`.

The proposed feature is a command line option `--no-dependents` that would disable this cascade of upgrades.

# The motivation for the feature

When using Homebrew, a user may wish to upgrade specific packages that the user's project depends on.  However, homebrew's upgrade behavior (i.e. upgrading all dependents) often performs unnecessary work, by upgrading packages that are not relevant to the user.

This means that upgrading a low-level package for a build (such as `openssl` or `boost`) can take several minutes:  the package itself is upgraded quickly, but there may be dozens of "downstream" (dependent) packages that are also upgraded.  This feature would cut down the upgrade time in these scenarios by a factor of 10 or 100.

This may be most useful in VM-like environments (such as the Travis CI build environment) where a user starts with a known image, and is willing to modify the homebrew packages "at your own risk", knowing that the whole system will be torn down at the end of the VM lifetime.

# How the feature would be relevant to at least 90% of Homebrew users

It is not clear to me how often homebrew users work in a VM or similar environment where this feature would be desirable.

It is clear from other issues and forum posts that the current behavior is surprising, and this would be useful to other users:
[`brew upgrade FORMULA` should not upgrade FORMULA's dependents](https://github.com/Homebrew/brew/issues/6216) (closed WONTFIX)
[brew upgrade python@2 installs opencv and pyqt as dependents](https://github.com/Homebrew/brew/issues/5382) (closed without comment)
[Can I install a new version without having to upgrade runtime dependents?](https://discourse.brew.sh/t/can-i-install-a-new-version-without-having-to-upgrade-runtime-dependents/4443)

The forum question is the same situation I am in:

> I’ve recently switched [...] to Travis xcode8.3 environment (MacOS 10.12) and it [strikes] me as a very unpleasant surprise that now I cannot just brew upgrade a dependency package. Trying to do so now leads to upgrading all its “runtime dependents”. E.g. for openssl, brew tries to upgrade more than 60(!) packages 1, none of which is relevant to my build.

# What alternatives to the feature have been considered

It may be possible to get dependents and pin them before upgrading a package.

**Comment by MikeMcQuaid** [comment]
Sorry, but no. Opting out of this behaviour leads to known breakages in packages which is why it's on by default.

> Trying to do so now leads to upgrading all its “runtime dependents”. E.g. for openssl, brew tries to upgrade more than 60(!) packages 1, none of which is relevant to my build.

The solution to this problem is to uninstall the packages that are not relevant to your build.

Thanks anyway for the issue!
