### ISSUE TITLE
 SSL certificate problem

### ISSUE THREAD

**Issue by kingkarki** [Homebrew/brew#628]
I m getting following error while installing with command line. 
```

com/Homebrew/install/master/install)"
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
Is it possible to install without using curl? Can i download the master zip and install it manually?

**Comment by MikeMcQuaid** [comment]
What version of OS X are you on?

**Comment by kingkarki** [comment]
I m on 10.11.4 @MikeMcQuaid El mac el capitan

**Comment by MikeMcQuaid** [comment]
Can you still reproduce it? It could be GitHub was having an intermittent issue.

**Comment by kingkarki** [comment]
Yes i m still having issue. Please check the screenshot. Can i download source and install manually?
<img width="609" alt="screen shot 2016-08-04 at 3 38 14 pm" src="https://cloud.githubusercontent.com/assets/756162/17397809/7e150044-5a59-11e6-9166-31b811f9fa3c.png">

**Comment by MikeMcQuaid** [comment]
What happens if you view that URL in a browse on the same machine? Are you SSHd into that machine or using a local console?

**Comment by kingkarki** [comment]
it opens on browser. It is my local computer not in VM. 
<img width="1280" alt="screen shot 2016-08-04 at 4 12 26 pm" src="https://cloud.githubusercontent.com/assets/756162/17398807/6504d994-5a5e-11e6-9387-8f893175155f.png">

**Comment by MikeMcQuaid** [comment]
What does `which curl` show? What does `curl https://github.com` show?

**Comment by kingkarki** [comment]
which curl returns 
/Applications/XAMPP/xamppfiles/bin/curl

curl github.com shows same issue 

```
$ curl https://github.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
 
```

**Comment by javian** [comment]
Can you try using /usr/bin/curl instead of the XAMPP curl ?

**Comment by kingkarki** [comment]
how to do that @javian . Actually i m new to commands lines. Some examples would be awesome.

**Comment by MikeMcQuaid** [comment]
`/usr/bin/curl https://github.com`

**Comment by kingkarki** [comment]
it works when i do /`usr/bin/curl https://github.com`
but this issue when i do 
`
/usr/bin/ruby -e "$(/usr/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
output on screen shot 
<img width="584" alt="screen shot 2016-08-04 at 11 17 23 pm" src="https://cloud.githubusercontent.com/assets/756162/17411854/a74ed512-5a99-11e6-8ecb-fbc389e2cb5f.png">

**Comment by MikeMcQuaid** [comment]
@kingkarki Follow the instructions to `intent to reinstall`.

**Comment by kingkarki** [comment]
Finally it worked with this
`/usr/bin/ruby -e "$(/usr/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

First i had to uninstall  with this 

`/usr/bin/ruby -e "$(/usr/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"`

Thank you @MikeMcQuaid and @javian you guys are awesome.

**Comment by javian** [comment]
@kingkarki You probably should also have a look at your PATH setting since XAMPP seems to have a higher priority which might cause issues similar to this one in other places.

**Comment by kingkarki** [comment]
Yes you are right. Where can i find path variables on mac?

**Comment by chocolatewheelchair** [comment]
@MikeMcQuaid As requested on #630:

`'What happens if you view that URL in a browse on the same machine?`'
It opens in the browser, as shown in the screenshot attached by kingkarki above.

"Are you SSHd into that machine or using a local console?"
The issue happens when trying to build a VM via packer, which communicates with it via SSH, however all the checks following instructions in this thread were done by manually typing in the local command line of a VM (also built with Packer).

"What does which curl show?"
/usr/bin/curl

"What does curl https://github.com show?"
It displays the html from the page in the terminal

**Comment by MikeMcQuaid** [comment]
@chocolatewheelchair Not sure what your issue is; it sounds like it could be an issue with the VM or the version. Sorry!
