### ISSUE TITLE
[Meta]Make organization repos descriptions more consistent

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#6285]
Some organization repos have extraneous dots at the end of descriptions and lack homepage. This seems inconsistent with other repos. Dot issue is obvious to fix, but homepage is more tricky, but why don't just put https://brew.sh/?

# The motivation for the feature
Make repos descriptions more consistent.

# How the feature would be relevant to at least 90% of Homebrew users
Above mentioned issues looks strange if you navigate trough organization repos.

# What alternatives to the feature have been considered
Leave it as is and finally ban @yurikoles from reporting stupid tickets.

**Comment by yurikoles** [comment]
What's wrong again?

**Comment by yurikoles** [comment]
@reitermarkus,

Help me, please.

**Comment by MikeMcQuaid** [comment]
This is not important and you did not fill in the issue template.
