### ISSUE TITLE
It seems that there is already a rebase-apply directory

### ISSUE THREAD

**Issue by L1cardo** [Homebrew/brew#6288]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [yes] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [yes] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [yes] ran `brew update` and can still reproduce the problem?
- [yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [yes] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I wanted to update brew with `brew update`

# What happened (include command output)
output a fatal error
<details>
  <summary>Command output</summary>
  <pre>
licardo@LicardodeMacBook-Pro ~ % brew update
fatal: It seems that there is already a rebase-apply directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr ".git/rebase-apply"
and run me again.  I am stopping in case you still have something
valuable there.

Already up-to-date.
licardo@LicardodeMacBook-Pro ~ %
  </pre>
</details>

# What you expected to happen

I do not want the error show up.  I have tried running `git rebase --abort` and `rm -fr ".git/rebase-apply"`, but it still shows up.

# Step-by-step reproduction instructions (by running `brew` commands)
![截屏2019-07-10上午1 21 13](https://user-images.githubusercontent.com/33802186/60909522-03e8a480-a2b1-11e9-84f4-483b4cf78c3d.png)
![截屏2019-07-10上午1 21 43](https://user-images.githubusercontent.com/33802186/60909551-182ca180-a2b1-11e9-8bcb-9f5e8e679822.png)
![截屏2019-07-10上午1 22 10](https://user-images.githubusercontent.com/33802186/60909573-25499080-a2b1-11e9-83a3-34bfd01b0113.png)

**Comment by L1cardo** [comment]
solved by deleting `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/.git/rebase-apply`
This directory is difficult to find.

**Comment by L1cardo** [comment]
solved by deleting `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/.git/rebase-apply`
This directory is difficult to find.

**Comment by mnich** [comment]
i find this folder "rebase-apply" use commend  `find / -name "rebase-apply"`

**Comment by L1cardo** [comment]
@mnich thanks！but I wish I would never come across such error.

**Comment by joshuapinter** [comment]
Instead of manually finding the `rebase-apply` directory, just run `brew update-reset` instead. 

Found this from one of the contributors [here](https://github.com/Homebrew/brew/issues/3410#issuecomment-343922422).
