### ISSUE TITLE
Suggestion - move CODEOFCONDUCT, LICENSE, README to $PREFIX/doc/homebrew

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/brew#629]
A suggestion to move the docs CODEOFCONDUCT.md, LICENSE.txt, README.md to a location such as $PREFIX/doc/homebrew (for example /usr/local/doc/homebrew) - it's a small thing but it's always bothered me to have these docs "dumped" into my /usr/local which is otherwise clean. I used to delete them but then would get git errors/messages about stashing changes when updating homebrew so I gave up on that.

**Comment by DomT4** [comment]
See https://github.com/Homebrew/brew/issues/391. It's something we've discussed before & it remains under consideration. Something may well happen, but need to decide the best way to achieve that whilst keeping some of the most prominent documentation accessible.

**Comment by MikeMcQuaid** [comment]
We need/want to keep these in the repository root but may figure out a way that that doesn't need to be in the `/usr/local` root.
