### ISSUE TITLE
Error when running homebrew install script on VM

### ISSUE THREAD

**Issue by chocolatewheelchair** [Homebrew/brew#630]
### Bug reports:

Trying to install homebrew on VM's via packer (https://www.packer.io/), using the curl install script fails with the following error:

SSLRead() return error -9806
Closing connection 0
error: RPC failed; curl 56 SSLRead() return error 
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-core /usr/local/Library/Taps/homebrew/homebrew-core --depth=1
Failed during: /usr/local/bin/brew tap homebrew/core

Although the failure is not happening in 100% cases, the installation of homebrew fails more often than it succeeds. 

Looking at the timestamps, when the git clone command succeed it succeeds almost immediately, whereas it takes about 15 minutes to fail when it does.
This would point to a timeout issue(?) but no idea what could be the cause.

Any hints?

Let me know if I can provide further info to help understand the issue.

**Comment by MikeMcQuaid** [comment]
What country are you in? What OS X version is the VM?

**Comment by chocolatewheelchair** [comment]
Located in Germany. The OSX version seems to be irrelevant, as I have had the issue with both OSX 10.10 and 10.11 (haven't tried with other versions though)?

Not sure why you ask about the country, but FWIW we thought it could be a time sync issue and tried to force sync with ntp, as well as changing the timezone the VM's were on to the actual timezone (they were on US pacific by default) 

Also I stumbled on this  SO question (http://stackoverflow.com/questions/30385939/git-clone-fails-with-sslread-error-on-os-x-yosemite/30441332) which describes an issue that looks very similar to the one I encounter, however the suggested fix is to install curl with openssl... via homebrew. 

Lastly, this could be completely coincidental, but the packer builds were run as a daily job in jenkins (setup around the end of April 2016), and were mostly succeeding in May/June and then started failing much more often at the end of June / beginning of July. At which point the jenkins job was set to run every two hours so we could understand what was going on.
There doesn't seem to be a pattern with regard to the time the build is ran and whether or not it fails.

Mind, we had already encountered this same error before the builds started failing so often but shrugged it off as a random network error, so I don't think the issue comes from a change in the curl script (and also tried to run jenkins builds that "manually" try to install homebrew in a way that mimicks what the curl script does, to the best of my ability, but this one succeeded 100% of the time).

Probably should have included all that info in my initial post... My bad...

**Comment by MikeMcQuaid** [comment]
Can you still reproduce this? It could be an intermittent GitHub issue. Regardless it looks like an issue connecting to GitHub rather than Homebrew specifically which is something we can't do anything about, sorry 😢

**Comment by MikeMcQuaid** [comment]
Folding into #628 as it looks related.

**Comment by chocolatewheelchair** [comment]
I definitely can still reproduce it, although what I'm missing is precisely what causes the issue to happen as some builds succeed. 

As I said, I definitely don't think the issue comes from Homebrew itself, but was hoping someone more familiar with how the Homebrew install script works under the hood could help shedding light on the issue. Will keep an eye on that other possibly related issue, thanks.

**Comment by MikeMcQuaid** [comment]
It's basically: you can't connect to GitHub 😭

**Comment by chocolatewheelchair** [comment]
But the homebrew install does succeed sometimes and running a Jenkins build that just git clones the homebrew repo again and again succeeds 100% of the time.

**Comment by MikeMcQuaid** [comment]
Cloning is done through Git, not Curl. Please answer the questions in #628, thanks.
