### ISSUE TITLE
Adding an environmental variable to set --display-times as the default

### ISSUE THREAD

**Issue by brucehs** [Homebrew/brew#6300]
**Note to maintainers. I believe I included all the information requested in the feature request template (Description, Motivation, Relevance, & Alternatives). If I've missed something, please let me know. Much thanks.**

## Description

I suggest `HOMEBREW_DISPLAY_TIMES` as an environmental variable for setting --display-times as a default option for all intallation commands.

## Motivation for feature  

I was testing the difference in performance between the 2015 and 2017 versions of the MacBook. Using `brew` to build from source was a good way to see both how responsive each was under load and the difference between the processors. 

## Relevance to users  

If users wanted to use `brew` as a performance test or simply track its performance overtime, setting --display-times as the default would be useful.

## Considered alternatives  

I searched both open and closed issues on GitHub and could not find any discussion of it.

**Comment by MikeMcQuaid** [comment]
Sorry, ignore our zealous bot. This is a good idea. 
Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

You'll need to add lines like https://github.com/Homebrew/brew/blob/bf0f1bd3043a6e49521c13414c01ffcebd87d94e/Library/Homebrew/dev-cmd/irb.rb#L30 to all `cmd/` and `dev-cmd/` files referencing the flag like https://github.com/Homebrew/brew/blob/bf0f1bd3043a6e49521c13414c01ffcebd87d94e/Library/Homebrew/cmd/install.rb#L80-L81 and add it to the manpage (running `brew man`) to generate the results.

Thanks!
