### ISSUE TITLE
brew install --build-bottle exits with 0 before building bottle

### ISSUE THREAD

**Issue by milljm** [Homebrew/brew#6310]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

I am the tap, but brew exit's with 0 before finishing _at_ a Homebrew-core formula

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

```bash
[milljm][~]> brew update
Already up-to-date.
[milljm][~]> brew doctor
Your system is ready to brew.
[milljm][~]> brew config
HOMEBREW_VERSION: 2.1.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b83463091513826127c14acae81a7c354dfce69
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b0978ccccac55b2d34723e2012523509461c705d
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
XQuartz: 2.7.11 => /opt/X11
```
# What you were trying to do (and why)

I need to supply a specifically built PETSc not available in core formula.

```bash
[milljm][~]> brew tap milljm/moose
[milljm][~]> brew install --build-bottle moose-petsc@3105
```
# What happened (include command output)

<details>
  <summary>Command output</summary>
<pre>
|[milljm][~]> brew install --build-bottle moose-petsc@3105
|==> Installing moose-petsc@3105 from milljm/moose
|==> Installing dependencies for milljm/moose/moose-petsc@3105: cmake, gmp, isl, mpfr, libmpc, gcc@9, libffi, pcre, swig, llvm@8, gcc, openssl, libevent and openmpi
|==> Installing milljm/moose/moose-petsc@3105 dependency: cmake
|==> Downloading https://homebrew.bintray.com/bottles/cmake-3.15.0.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/859f5964c50d9d25e72c35ce794d1e9e001f7c49217620d6d290f5e258ef9728--cmake-3.15.0.mojave.bottle.tar.gz
|==> Pouring cmake-3.15.0.mojave.bottle.tar.gz
|==> Caveats
|Emacs Lisp files have been installed to:
|  /usr/local/share/emacs/site-lisp/cmake
|==> Summary
|🍺  /usr/local/Cellar/cmake/3.15.0: 5,797 files, 53.2MB
|==> Installing milljm/moose/moose-petsc@3105 dependency: gmp
|==> Downloading https://homebrew.bintray.com/bottles/gmp-6.1.2_2.mojave.bottle.1.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/8d4cf0dd9e2e02e37e5aca4a0bd3860fe4acccd8e0ba76c237c9f2b37ecb759d--gmp-6.1.2_2.mojave.bottle.1.tar.gz
|==> Pouring gmp-6.1.2_2.mojave.bottle.1.tar.gz
|🍺  /usr/local/Cellar/gmp/6.1.2_2: 18 files, 3.1MB
|==> Installing milljm/moose/moose-petsc@3105 dependency: isl
|==> Downloading https://homebrew.bintray.com/bottles/isl-0.21.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/f85b0673a69cc5edad84131d27d19ee4a5b95ecf99a9662f4db5ff3b9dd9f76f--isl-0.21.mojave.bottle.tar.gz
|==> Pouring isl-0.21.mojave.bottle.tar.gz
|🍺  /usr/local/Cellar/isl/0.21: 72 files, 4.3MB
|==> Installing milljm/moose/moose-petsc@3105 dependency: mpfr
|==> Downloading https://homebrew.bintray.com/bottles/mpfr-4.0.2.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/3acf350557ad53525a1bab6fd74037b2efca1ec1e87bd3a4be8515c6442f7344--mpfr-4.0.2.mojave.bottle.tar.gz
|==> Pouring mpfr-4.0.2.mojave.bottle.tar.gz
|🍺  /usr/local/Cellar/mpfr/4.0.2: 28 files, 4.7MB
|==> Installing milljm/moose/moose-petsc@3105 dependency: libmpc
|==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.1.0.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/b2f71f595511594f22d503148070442792165a80c2ea3f05e7fab4db777d672d--libmpc-1.1.0.mojave.bottle.tar.gz
|==> Pouring libmpc-1.1.0.mojave.bottle.tar.gz
|🍺  /usr/local/Cellar/libmpc/1.1.0: 12 files, 354KB
|==> Installing milljm/moose/moose-petsc@3105 dependency: gcc@9
|==> Downloading https://homebrew.bintray.com/bottles/gcc-9.1.0.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/73106c6dda7b91002502638469c02b5e352f8d7651ca7b93dcc4284d1501bb8a--gcc-9.1.0.mojave.bottle.tar.gz
|==> Pouring gcc-9.1.0.mojave.bottle.tar.gz
|🍺  /usr/local/Cellar/gcc/9.1.0: 1,461 files, 287MB
|==> Installing milljm/moose/moose-petsc@3105 dependency: libffi
|==> Downloading https://homebrew.bintray.com/bottles/libffi-3.2.1.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/89b4ef328be250153e7a2b39982ac446e0b3bbfe7f3e2708912ba1976862c302--libffi-3.2.1.mojave.bottle.tar.gz
|==> Pouring libffi-3.2.1.mojave.bottle.tar.gz
|==> Caveats
|libffi is keg-only, which means it was not symlinked into /usr/local,
|because some formulae require a newer version of libffi.
|
|For compilers to find libffi you may need to set:
|  export LDFLAGS="-L/usr/local/opt/libffi/lib"
|
|==> Summary
|🍺  /usr/local/Cellar/libffi/3.2.1: 16 files, 296.8KB
|==> Installing milljm/moose/moose-petsc@3105 dependency: pcre
|==> Downloading https://homebrew.bintray.com/bottles/pcre-8.43.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/1b7cb2cf34420d2f3d54b8e13288869193823eaff14a83f0f38be292f7c0e488--pcre-8.43.mojave.bottle.tar.gz
|==> Pouring pcre-8.43.mojave.bottle.tar.gz
|🍺  /usr/local/Cellar/pcre/8.43: 204 files, 5.5MB
|==> Installing milljm/moose/moose-petsc@3105 dependency: swig
|==> Downloading https://homebrew.bintray.com/bottles/swig-4.0.0.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/e7ee5776a38ecccbd509f89e35c92494ed22815396cee6d3845844f8d6ccee04--swig-4.0.0.mojave.bottle.tar.gz
|==> Pouring swig-4.0.0.mojave.bottle.tar.gz
|🍺  /usr/local/Cellar/swig/4.0.0: 722 files, 5.3MB
|==> Installing milljm/moose/moose-petsc@3105 dependency: llvm@8
|==> Downloading https://homebrew.bintray.com/bottles/llvm-8.0.0_1.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/b0801e71c67e9c0bb06f9af9844cf81ceef973259736805618a74468cbccdb20--llvm-8.0.0_1.mojave.bottle.tar.gz
|==> Pouring llvm-8.0.0_1.mojave.bottle.tar.gz
|==> Caveats
|To use the bundled libc++ please add the following LDFLAGS:
|  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
| 
|llvm is keg-only, which means it was not symlinked into /usr/local,
|because macOS already provides this software and installing another version in
|parallel can cause all kinds of trouble.
| 
|If you need to have llvm first in your PATH run:
|  echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
| 
|For compilers to find llvm you may need to set:
|  export LDFLAGS="-L/usr/local/opt/llvm/lib"
|  export CPPFLAGS="-I/usr/local/opt/llvm/include"
| 
|==> Summary
|🍺  /usr/local/Cellar/llvm/8.0.0_1: 6,807 files, 3.3GB
|==> Caveats
|==> cmake
|Emacs Lisp files have been installed to:
|  /usr/local/share/emacs/site-lisp/cmake
|==> libffi
|libffi is keg-only, which means it was not symlinked into /usr/local,
|because some formulae require a newer version of libffi.
| 
|For compilers to find libffi you may need to set:
|  export LDFLAGS="-L/usr/local/opt/libffi/lib"
| 
|==> llvm
|To use the bundled libc++ please add the following LDFLAGS:
|  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
| 
|llvm is keg-only, which means it was not symlinked into /usr/local,
|because macOS already provides this software and installing another version in
|parallel can cause all kinds of trouble.
| 
|If you need to have llvm first in your PATH run:
|  echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
| 
|For compilers to find llvm you may need to set:
|  export LDFLAGS="-L/usr/local/opt/llvm/lib"
|  export CPPFLAGS="-I/usr/local/opt/llvm/include"
| 
|[milljm][~]> echo $?
|0
|[milljm][~]> 
</pre>

If I attempt the command again, immediately following this exit, it continues installing other necessary Homebrew-core formula:

<pre>
|[milljm][~]> brew install --build-bottle moose-petsc@3105
|==> Installing moose-petsc@3105 from milljm/moose
|==> Installing dependencies for milljm/moose/moose-petsc@3105: openssl, libevent and openmpi
|==> Installing milljm/moose/moose-petsc@3105 dependency: openssl
|==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2s.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/209640018f2d231e0bf28c69d0bac3cb886609ff2d81e8ac32cbbe270f897aad--openssl-1.0.2s.mojave.bottle.tar.gz
|==> Pouring openssl-1.0.2s.mojave.bottle.tar.gz
|==> Caveats
|A CA file has been bootstrapped using certificates from the SystemRoots
|keychain. To add additional certificates (e.g. the certificates added in
|the System keychain), place .pem files in
|  /usr/local/etc/openssl/certs
|
|and run
|  /usr/local/opt/openssl/bin/c_rehash
|
|openssl is keg-only, which means it was not symlinked into /usr/local,
|because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.
|
|If you need to have openssl first in your PATH run:
|  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile
|
|For compilers to find openssl you may need to set:
|  export LDFLAGS="-L/usr/local/opt/openssl/lib"
|  export CPPFLAGS="-I/usr/local/opt/openssl/include"
|
|==> Summary
|🍺  /usr/local/Cellar/openssl/1.0.2s: 1,795 files, 12.0MB
|==> Installing milljm/moose/moose-petsc@3105 dependency: libevent
|==> Downloading https://homebrew.bintray.com/bottles/libevent-2.1.10.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/786f6d255727103697cdb2ef2bffd5eb18cf42b6d192c7b0738de06c97b780d5--libevent-2.1.10.mojave.bottle.tar.gz
|==> Pouring libevent-2.1.10.mojave.bottle.tar.gz
|🍺  /usr/local/Cellar/libevent/2.1.10: 857 files, 2.2MB
|==> Installing milljm/moose/moose-petsc@3105 dependency: openmpi
|==> Downloading https://homebrew.bintray.com/bottles/open-mpi-4.0.1_1.mojave.bottle.tar.gz
|Already downloaded: /Users/milljm/Library/Caches/Homebrew/downloads/7c17a37f5c16175cf8fb332cde7a225473717f80ee0bb4121a0ea64ef6fc9f54--open-mpi-4.0.1_1.mojave.bottle.tar.gz
|==> Pouring open-mpi-4.0.1_1.mojave.bottle.tar.gz
</pre>

...and eventually finishes building my bottle without errors.

</details>

# What you expected to happen

I excepted brew to proceed and build the bottle without exiting part-way through _with_ an exit code of 0.

# Step-by-step reproduction instructions (by running `brew` commands)

```bash
brew tap milljm/moose
brew install --build-bottle moose-petsc@3105
brew install --build-bottle moose-petsc@3105
```

Additional info; this only started happening when I added `@version` information to all my formula.

**Comment by milljm** [comment]
Now that I have all my bottles built, the only I can make this work, is to run the install command twice:

```bash
brew tap milljm/moose
brew install moose
brew install moose
```

**Comment by MikeMcQuaid** [comment]
Can you try to use `--debug` and `--verbose`? Can you reproduce this with any homebrew-core formulae? Can you figure out a minimal formula that reproduces this? Thanks!

**Comment by milljm** [comment]
I will attempt to find one. Not sure if I mentioned this clearly, but everything was fine until I started adding `@version` information to all my formulas. Maybe a few homebrew-core recipes with aliases (I think they are called?) will exhibit the issue. I'll look into it!

**Comment by milljm** [comment]
I have not abandoned this issue. But I have decided against version control within our own tap. It made little sense to do so once I started successfully performing my own [CI via Civet/homebrew-moose](https://civet.inl.gov). Admittedly, I still have _lots_ to learn.
