### ISSUE TITLE
Instructions to add to path don't work

### ISSUE THREAD

**Issue by endolith** [Homebrew/brew#6311]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

(Of course these all fail because `brew` isn't installed.)

To help us debug your issue please explain:

- What you were trying to do (and why)

Install Homebrew (to [build SciPy](https://scipy.github.io/devdocs/dev/contributor/quickstart_ubuntu.html#quickstart-ubuntu))

- What happened (include command output)

The installer says:

```
- Add Linuxbrew to your PATH
    eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
```

and the website https://docs.brew.sh/Homebrew-on-Linux says 

```
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
```
But neither of these work:

```
$ test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
bash: set: -g: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
bash: set: -g: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
bash: set: -g: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
bash: set: -g: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
bash: set: -q: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
or: command not found
bash: set: -g: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
bash: set: -q: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
or: command not found
bash: set: -g: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
```

- What you expected to happen

Add Linuxbrew to your PATH                                                                                                                                  

- Step-by-step reproduction instructions (by running `brew install` commands)

Ubuntu 18.04

1. Open bash terminal
2. `sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"`
3. ` eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)`

**Comment by jonchang** [comment]
To workaround your current problem: there's a binary in your path called `set` that you need to remove. Try temporarily changing your `PATH` environment variable.

**Comment by MikeMcQuaid** [comment]
Closing as user-specific issue.

**Comment by endolith** [comment]
This is what I had to do, for anyone else with this problem:

```
set -U fish_user_paths /home/linuxbrew/.linuxbrew/bin $fish_user_paths
```

This is a permanent change, you don't need to do it each time.

http://fishshell.com/docs/current/tutorial.html#tut_path

**Comment by danmackinlay** [comment]
I also had this problem with the Ubuntu `homebrew-wrapper` installed fish shell, which seems to have skipped installing the fish shell init in my fish profile but which executes erroneously from the bash.profile which is AFAICT always executed at login as part off some ubuntu setup step. For me the fix was to append

```shell
eval (/bin/brew shellenv)
```

to `~/.config/fish/config.fish`

and to modify the init line in `.profile` to read

```shell
eval $(SHELL=bash /bin/brew shellenv)
```

Then the correct vars seem to be initialized for both the compulsory bash shell and also my fish shell.
