### ISSUE TITLE
/usr/local/bin/brew: line 91: /usr/bin/env: Argument list too long

### ISSUE THREAD

**Issue by 280482431** [Homebrew/brew#6314]
When I run brew command,it Error“/usr/local/bin/brew: line 91: /usr/bin/env: Argument list too long”
Ex:
lvfeijundeMacBook-Pro:~ lvfeijun$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD 现在位于 203980ac5 Merge pull request #6309 from Homebrew/dependabot/bundler/docs/html-pipeline-2.11.1
/usr/local/bin/brew: line 91: /usr/bin/env: Argument list too long
/usr/local/bin/brew: line 91: /usr/bin/env: Undefined error: 0
Failed during: /usr/local/bin/brew update --force
lvfeijundeMacBook-Pro:~ lvfeijun$ /usr/local/bin/brew update --force
/usr/local/bin/brew: line 91: /usr/bin/env: Argument list too long
/usr/local/bin/brew: line 91: /usr/bin/env: Undefined error: 0
lvfeijundeMacBook-Pro:~ lvfeijun$ brew list
/usr/local/bin/brew: line 91: /usr/bin/env: Argument list too long
/usr/local/bin/brew: line 91: /usr/bin/env: Undefined error: 0
lvfeijundeMacBook-Pro:~ lvfeijun$ brew list
/usr/local/bin/brew: line 91: /usr/bin/env: Argument list too long
/usr/local/bin/brew: line 91: /usr/bin/env: Undefined error: 0

**Comment by MikeMcQuaid** [comment]
@280482431 Don't recreate duplicate issues. Instead fill out the issue template (https://github.com/Homebrew/brew/issues/new/choose) in this issue.
