### ISSUE TITLE
Implement "zap" command in brew

### ISSUE THREAD

**Issue by GauthierPLM** [Homebrew/brew#6315]
# A detailed description of the proposed feature

Add the `zap` command to brew to extend the command available in cask to all formulae and software installable with brew.

Many software available as formulae will write preferences, cache, etc... in the system. For the end user, it is not easy to keep track of this and without a good amount of researches, it is hard to know how to properly clean the system after uninstalling a software.

Good example of software that would benefit this are databases (mysql, postgresql, ...) and many development tools such as yarn, ruby gem, ...

Zap should behave in the same way as cask to keep consistency between tools.

# The motivation for the feature

When uninstalling a software, most user expect it to be completely removed from the system (including configuration and cache files).
The `zap` command is available in cask and is very useful to perform system cleaning at the same time as the uninstall. However, casks are not the only software that write files all around the system and a user uninstall a formulae currently have to manually remove the files after searching where they are stored.

# How the feature would be relevant to at least 90% of Homebrew users

Most people that use Homebrew use it for its simplicity and to avoid the pain of managing their system manually. A huge part of them also use cask and are familiar with `brew cask zap`.

Adding `zap` to brew would extend this behaviour so it covers formulae, and would help users to keep their system clean without the need of doing a lot of research and manual steps when they uninstall a formulae that put data all over the system.

# What alternatives to the feature have been considered

A similar feature was requested in #4925 in the form of a flag for `brew uninstall`. However, most people don't read enough documentation to know about flags and I don't think it is a good thing to mix behaviours in the same command.

Cask already implement zap in a separate command and I think it's the right thing to do: people can easily choose if they want to only uninstall the formulae (as it works now) or do the additional cleaning step of zap.

**Comment by MikeMcQuaid** [comment]
> When uninstalling a software, most user expect it to be completely removed from the system (including configuration and cache files).

I strongly disagree. Most package managers do not do this.

---

This is something that would require a huge amount of effort to cover even a small number of formulae. The best fit if you're interested would be to make a external command (https://docs.brew.sh/External-Commands) with the metadata in the same repository as the command (like `brew livecheck` https://github.com/Homebrew/homebrew-livecheck) and once it's got a reasonable percentage of formulae we'll consider merging it back into Homebrew proper.
