### ISSUE TITLE
brew install @lts

### ISSUE THREAD

**Issue by gireeshpunathil** [Homebrew/brew#6317]
# A detailed description of the proposed feature

Ability to issue `brew install node@lts` that installs the latest stable release

# The motivation for the feature

being able to consume the stable versions as opposed to specific versions

# How the feature would be relevant to at least 90% of Homebrew users

because most users aspire to use `lts` versions of any software

# What alternatives to the feature have been considered

manually identify the lts version and use it in the command line

reference: https://github.com/nodejs/help/issues/1599

Thanks in advance!

**Comment by MikeMcQuaid** [comment]
@Homebrew/core for thoughts on this for node specifically with an alias or formula (`jenkins-lts` is some prior art).

**Comment by gireeshpunathil** [comment]
is it closed by mistake? just wondering about the issue life cycle - the above comment suggests that it is forwarded for further considerations, but where that will be tracked, that I can follow? thanks!

**Comment by MikeMcQuaid** [comment]
@gireeshpunathil In general we close those out we don't have specific plans to do.

**Comment by gireeshpunathil** [comment]
ah! ok. I then mis-interpreted as forwarded for further consideration.

Any reason why this cannot be taken up? invalid requirement / not a common use case / anything else?

**Comment by MikeMcQuaid** [comment]
@gireeshpunathil A combination of not enough demand, existing solutions (being able to install by version number) perhaps being sufficient and there be no clear implementation in Homebrew for this solution.

**Comment by MikeMcQuaid** [comment]
Also it being pretty specific to NodeJS and a few other tools rather than most formulae.

**Comment by vitorgalvao** [comment]
> Ability to issue `brew install node@lts` that installs the latest stable release

I’ve never seen `LTS` to mean “latest stable release”. To me it always meant [Long Term Support](https://wiki.ubuntu.com/LTS), which is the latest stable only for a short while, then becoming an older and older version that still gets patches.

> because most users aspire to use `lts` versions of any software

With that definition, I agree most users want the latest stable, but only a few (generally a company) want the LTS.

**Comment by gireeshpunathil** [comment]
@vitorgalvao - I did not mean to expand lts into `latest stable release`. If the requested tag is confusing, please treat it as `brew install xyz@lsr` or something, you got the idea.

suggestion to install by specifying the version does not yield a good user experience, as it requires going through the software's website and reading deeper which, kind of defeats the premise of the tool's flexibility?

**Comment by vitorgalvao** [comment]
Then what’s the issue with `brew install node`? You don’t *need* to specify a version or any `@`. The default behaviour is to install the latest stable version, isn’t it?

**Comment by gireeshpunathil** [comment]
default install installs current version (v12.x) , not the stable one (v10.x). ref: https://nodejs.org/en/

**Comment by vitorgalvao** [comment]
> not the stable one (v10.x)

That’s the long term support version. [They even state as much on the website](https://nodejs.org/en/about/releases/).

You’re conflating things. “Latest Stable” is not the same as “Long Term Support”. What you want is a version for long term support. In that case, no, I don’t think this is “relevant to at least 90% of Homebrew users”.

**Comment by gireeshpunathil** [comment]
I do not wish to pursue this any further, however the data points suggest usage of lts
https://nodejs.org/en/user-survey-report/#version
