### ISSUE TITLE
After installing NPM with brew I can't use NPM to install Bootstrap

### ISSUE THREAD

**Issue by eno812** [Homebrew/brew#632]
I get the following error

npm WARN enoent ENOENT: no such file or directory, open '/Users/myusername/package.json'
npm WARN mysername No description
npm WARN myusername No repository field.
npm WARN myusername No README data
npm WARN myusername No license field.

How can I fix this ?

**Comment by MikeMcQuaid** [comment]
Ask `npm`, we don't support it.

**Comment by DomT4** [comment]
I'm 99% sure this isn't `brew` related looking at those errors, so yeah, probably best to check in with `npm` or their documentation. If they say otherwise, let us know!

**Comment by eno812** [comment]
Ok, thanks.
