### ISSUE TITLE
Error brew install express - collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by rafaeltiveron** [Homebrew/brew#633]
Hello again

I tryed to install express when at make event I've got this error message:

`brew install express`

`==> Installing express from homebrew/science`

`
==> Downloading http://bio.math.berkeley.edu/eXpress/downloads/express-1.5.1/express-1.5.1-src.tgz
Already downloaded: /home/bioroot/.cache/Homebrew/express-1.5.1.tgz
`

`==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/bio`

`
==> make install
Last 15 lines from /home/bioroot/.cache/Homebrew/Logs/express/02.make:
/home/bioroot/.linuxbrew/bin/g++-5   -Wall -DNDEBUG   -L/home/bioroot/.linuxbrew/lib -Wl,--dynamic-linker=/home/bioroot/.linuxbrew/lib/ld.so -Wl,-rpath,/home/bioroot/.linuxbrew/lib CMakeFiles/express.dir/biascorrection.cpp.o CMakeFiles/express.dir/bundles.cpp.o CMakeFiles/express.dir/directiondetector.cpp.o CMakeFiles/express.dir/fragments.cpp.o CMakeFiles/express.dir/lengthdistribution.cpp.o CMakeFiles/express.dir/main.cpp.o CMakeFiles/express.dir/mapparser.cpp.o CMakeFiles/express.dir/markovmodel.cpp.o CMakeFiles/express.dir/mismatchmodel.cpp.o CMakeFiles/express.dir/robertsfilter.cpp.o CMakeFiles/express.dir/sequence.cpp.o CMakeFiles/express.dir/targets.cpp.o CMakeFiles/express.dir/threadsafety.cpp.o CMakeFiles/express.dir/alignments.pb.cc.o CMakeFiles/express.dir/targets.pb.cc.o  -o express -rdynamic /home/bioroot/.linuxbrew/lib64/libboost_thread-mt.so /home/bioroot/.linuxbrew/lib64/libboost_system-mt.so /home/bioroot/.linuxbrew/lib64/libboost_filesystem-mt.so /home/bioroot/.linuxbrew/lib64/libboost_program_options-mt.so /home/bioroot/.linuxbrew/lib64/libboost_date_time-mt.so /home/bioroot/.linuxbrew/lib64/libboost_chrono-mt.so /home/bioroot/.linuxbrew/lib64/libboost_atomic-mt.so /home/bioroot/.linuxbrew/lib64/libz.so ../bamtools/lib/libbamtools.a -lz -lpthread -Wl,-Bstatic -lprotobuf -Wl,-Bdynamic -Wl,-rpath,/home/bioroot/.linuxbrew/lib64 
`
```
CMakeFiles/express.dir/mapparser.cpp.o: In function `MapParser::MapParser(Library*, bool)':
mapparser.cpp:(.text+0x3ca): undefined reference to `BamTools::BamReader::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
mapparser.cpp:(.text+0x4a0): undefined reference to `BamTools::BamWriter::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, BamTools::SamHeader const&, std::vector<BamTools::RefData, std::allocator<BamTools::RefData> > const&)'
CMakeFiles/express.dir/mapparser.cpp.o: In function `BAMParser::header[abi:cxx11]() const':
mapparser.cpp:(.text._ZNK9BAMParser6headerB5cxx11Ev[_ZNK9BAMParser6headerB5cxx11Ev]+0x2e): undefined reference to `BamTools::BamReader::GetHeaderText[abi:cxx11]() const'
CMakeFiles/express.dir/mapparser.cpp.o: In function `bool BamTools::BamAlignment::AddTag<float>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float const&)':
mapparser.cpp:(.text._ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_[_ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_]+0x52): undefined reference to `BamTools::BamAlignment::IsValidSize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
mapparser.cpp:(.text._ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_[_ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_]+0xe6): undefined reference to `BamTools::BamAlignment::FindTag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char*&, unsigned int const&, unsigned int&) const'
```

`collect2: error: ld returned 1 exit status`
`make[2]: ** [src/express] Erro 1`
`make[2]: Saindo do diretório '/tmp/express-20160803-22305-11g4yt5/express-1.5.1-src'`
`make[1]: ** [src/CMakeFiles/express.dir/all] Erro 2`
`make[1]: Saindo do diretório '/tmp/express-20160803-22305-11g4yt5/express-1.5.1-src'`
`make: ** [all] Erro 2`

```
READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues
```

```
These open issues may also help:
Building express fails: library not found for -lprotobuf https://github.com/Homebrew/homebrew-science/issues/3828
```

Any idea?
My system: Centos 7 x64 bits / 8 gb RAM / 4 CPUs
* I have updated and upgraded Linuxbrew recently.

**Comment by DomT4** [comment]
> If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues

You'll need to do this I'm afraid. We don't handle Science issues here.

**Comment by rafaeltiveron** [comment]
Oh, sorry, thanks
