### ISSUE TITLE
`brew cleanup` results in `Error: Permission denied @ utime_internal`

### ISSUE THREAD

**Issue by balupton** [Homebrew/brew#6331]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

tried to run `brew cleanup`

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
  
07:36:45:/Users/balupton:master
> brew cleanup -v
Error: Permission denied @ utime_internal - /Users/balupton/Library/Caches/Homebrew/.cleaned
07:37:14:/Users/balupton:master
> brew doctor
Your system is ready to brew.
07:38:24:/Users/balupton:master
> brew update
Already up-to-date.
07:38:30:/Users/balupton:master
> brew doctor
Your system is ready to brew.
07:38:35:/Users/balupton:master
> brew config
HOMEBREW_VERSION: 2.1.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 549a40bedb32171912a449d8d0e7bcae02d5b432
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3a949103ed29c96759195e81ba4efdd02931d226
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_COLOR: \e[0m
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
07:38:38:/Users/balupton:master
> brew cleanup -v
Error: Permission denied @ utime_internal - /Users/balupton/Library/Caches/Homebrew/.cleaned
  
  </pre>
</details>

# What you expected to happen

it to work correctly

# Step-by-step reproduction instructions (by running `brew` commands)

```
07:36:45:/Users/balupton:master
> brew cleanup -v
Error: Permission denied @ utime_internal - /Users/balupton/Library/Caches/Homebrew/.cleaned
07:37:14:/Users/balupton:master
> brew doctor
Your system is ready to brew.
07:38:24:/Users/balupton:master
> brew update
Already up-to-date.
07:38:30:/Users/balupton:master
> brew doctor
Your system is ready to brew.
07:38:35:/Users/balupton:master
> brew config
HOMEBREW_VERSION: 2.1.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 549a40bedb32171912a449d8d0e7bcae02d5b432
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3a949103ed29c96759195e81ba4efdd02931d226
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_COLOR: \e[0m
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
07:38:38:/Users/balupton:master
> brew cleanup -v
Error: Permission denied @ utime_internal - /Users/balupton/Library/Caches/Homebrew/.cleaned
```

**Comment by balupton** [comment]
ok doing `rm  /Users/balupton/Library/Caches/Homebrew/.cleaned` resolved it

**Comment by EricFromCanada** [comment]
The above applies to new installations, but existing installs can be fixed with: `sudo chown $(whoami) $(brew --cache)/.cleaned`

**Comment by sm44** [comment]
> The above applies to new installations, but existing installs can be fixed with: `sudo chown $(whoami) $(brew --cache)/.cleaned`
<img width="682" alt="屏幕快照 2019-09-22 12 38 15" src="https://user-images.githubusercontent.com/36100167/65382352-ecf51280-dd35-11e9-9867-824cf459c4e7.png">
what should I do?

**Comment by balupton** [comment]
@sm44 not sure what the fish shell is, I'd say type `bash -il` then enter the aforementioned bash command(s)

**Comment by EricFromCanada** [comment]
I've updated my comment above.
