### ISSUE TITLE
Cannot install brew cli on Mac 10.14

### ISSUE THREAD

**Issue by BoazWarshawsky** [Homebrew/brew#6336]
When running:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

My terminal stuck with this output:

Ignoring curb-0.9.10 because its extensions are not built.  Try: gem pristine curb --version 0.9.10
Ignoring curb-0.9.7 because its extensions are not built.  Try: gem pristine curb --version 0.9.7
Ignoring curb-0.9.3 because its extensions are not built.  Try: gem pristine curb --version 0.9.3
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at 3dab11263 Merge pull request #6335 from Homebrew/dependabot/bundler/Library/Homebrew/rubocop-performance-1.4.1

I have being waiting over 10 minutes but nothing change

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Trying to install brew on mac

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
  

Ignoring curb-0.9.10 because its extensions are not built.  Try: gem pristine curb --version 0.9.10
Ignoring curb-0.9.7 because its extensions are not built.  Try: gem pristine curb --version 0.9.7
Ignoring curb-0.9.3 because its extensions are not built.  Try: gem pristine curb --version 0.9.3
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at 3dab11263 Merge pull request #6335 from Homebrew/dependabot/bundler/Library/Homebrew/rubocop-performance-1.4.1

  
  </pre>
</details>

# What you expected to happen

brew should finish installing

# Step-by-step reproduction instructions (by running `brew` commands)

from terminal type this in:
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by genuinezack** [comment]
I'm running into this same issue both when attempting to run the install script and when trying to run `brew update` on an already installed copy of brew. `brew doctor` reports the system is good and ready.

**Comment by genuinezack** [comment]
Edit with more details:
1. I had an install where `brew update` was hanging. `brew doctor` reported everything was good.
2. Tried to reinstall by re-running the install script. Encountered the issue listed above.
3. Had to CTRL-C the install.
4. Ironically, running `brew doctor` again after the failed installation showed a slew of updates and now `brew update` says my system is up to date?

**Comment by rdp** [comment]
I ran into some connectivity (stalling) issues earlier today with github FWIW...

**Comment by genuinezack** [comment]
Yeah, that makes sense. Fingers crossed that’s all it was - I’ll check if it’s cleared up tomorrow.

**Comment by vitorgalvao** [comment]
As far as we know, these are Github issues. The solution is to wait for it to be sorted.

**Comment by BoazWarshawsky** [comment]
@vitorgalvao Can we please keep the ticket open as long as we still having the problem? according to github there are no issues currently: https://www.githubstatus.com/

**Comment by genuinezack** [comment]
Agreed with @BoazWarshawsky - have come back today and checked again. Github status still shows all green, but `brew update` is hanging on the step "Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...". When I try to `cd` into that directory and run `git pull` manually, it hangs. I think this might be a more complex issue than just "Github having issues".

**Comment by genuinezack** [comment]
Further experiments:
1. `git fsck && git gc --prune=now` runs successfully in the cask, no local repository issues.
2. Other github-hosted repositories clone and pull fine.
3. Clean clone in a new location of `homebrew-cask` also hangs.

**Comment by spencerhakim** [comment]
Assuming this is GitHub related, it'd still be helpful to have a ticket open to track any responses from their team, and to track if/when the issue gets resolved.

Also, not for nothing, but they might give more weight to an issue raised by maintainers of one of the more popular macOS tools than they would that same issue raised by a random user. ¯\\_(ツ)_/¯

**Comment by MikeMcQuaid** [comment]
I've pinned this rather than reopening.

**Comment by genuinezack** [comment]
While it's far from a sanctioned fix, based on my earlier investigations I was able to unstick my local machine this way:
```bash
$ cd /usr/local/Homebrew/Library/Taps/homebrew/
$ rm -rf homebrew-cask
$ git clone git@github.com:Homebrew/homebrew-cask.git
```

After that replacement, `brew doctor` is still happy, and `brew update` no longer gets hung at updating the cask. (Interestingly, though, trying to use `git remote set-url origin <ssh>` didn't work)

**Comment by spencerhakim** [comment]
I changed the remote to use SSH on my machine and tried to pull with `GIT_TRACE=1`, here's what happened the first time:

```
12:02:22.723295 git.c:439               trace: built-in: git pull
12:02:22.730749 run-command.c:663       trace: run_command: git merge-base --fork-point refs/remotes/origin/master master
12:02:22.739930 run-command.c:663       trace: run_command: git fetch --update-head-ok -v
12:02:22.744397 git.c:439               trace: built-in: git fetch --update-head-ok -v
12:02:22.746394 run-command.c:663       trace: run_command: unset GIT_PREFIX; ssh git@github.com 'git-upload-pack '\''Homebrew/homebrew-cask.git'\'''
12:02:58.913443 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet
12:02:58.923427 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet
12:02:58.927834 git.c:439               trace: built-in: git rev-list --objects --stdin --not --all --quiet
From github.com:Homebrew/homebrew-cask
 = [up to date]          master     -> origin/master
12:02:58.988501 run-command.c:1616      run_processes_parallel: preparing to run up to 1 tasks
12:02:58.988562 run-command.c:1648      run_processes_parallel: done
12:02:58.988633 run-command.c:663       trace: run_command: git gc --auto
12:02:58.992686 git.c:439               trace: built-in: git gc --auto
fatal: Cannot rebase onto multiple branches.
```

I had no local changes and only have one branch, so I have no idea what that error is about or why it couldn't fast-forward. After manually resetting my local `master` to the same commit as `origin/master`, I tried again:

```
12:05:13.548636 git.c:439               trace: built-in: git pull
12:05:13.553900 run-command.c:663       trace: run_command: git merge-base --fork-point refs/remotes/origin/master master
12:05:13.562011 run-command.c:663       trace: run_command: git fetch --update-head-ok
12:05:13.566258 git.c:439               trace: built-in: git fetch --update-head-ok
12:05:13.568140 run-command.c:663       trace: run_command: unset GIT_PREFIX; ssh git@github.com 'git-upload-pack '\''Homebrew/homebrew-cask.git'\'''
12:05:57.655797 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet
12:05:57.663982 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet
12:05:57.667800 git.c:439               trace: built-in: git rev-list --objects --stdin --not --all --quiet
12:05:57.727493 run-command.c:1616      run_processes_parallel: preparing to run up to 1 tasks
12:05:57.727577 run-command.c:1648      run_processes_parallel: done
12:05:57.727640 run-command.c:663       trace: run_command: git gc --auto
12:05:57.732246 git.c:439               trace: built-in: git gc --auto
12:05:57.735235 run-command.c:663       trace: run_command: git merge --ff-only FETCH_HEAD
12:05:57.739817 git.c:439               trace: built-in: git merge --ff-only FETCH_HEAD
Already up to date.
12:05:57.742999 run-command.c:663       trace: run_command: git rebase --onto b8c67034bd78f9585b1316564f223b97055bc0dc b8c67034bd78f9585b1316564f223b97055bc0dc
12:05:57.746659 git.c:439               trace: built-in: git rebase --onto b8c67034bd78f9585b1316564f223b97055bc0dc b8c67034bd78f9585b1316564f223b97055bc0dc
Current branch master is up to date.
12:05:57.751418 run-command.c:663       trace: run_command: git gc --auto
12:05:57.755406 git.c:439               trace: built-in: git gc --auto
```

`git-upload-pack` seems to be taking an awfully long time for some reason.

**Comment by frankli0324** [comment]
this definitely has something to with the 91,414 commits I think XD

**Comment by BoazWarshawsky** [comment]
I have stopped seeing the issues, we need to remember that brew has lots of issues in the past few months according to the changes made in new xCodes releases. Brew's installs depends on that.
