### ISSUE TITLE
Make `brew bump-formula-pr` behave more usefully on Homebrew on Linux

### ISSUE THREAD

**Issue by issyl0** [Homebrew/brew#6341]
# A detailed description of the proposed feature
​
For Homebrew formulae, there's a command that encourages users to contribute version bumps for formulae they use: [`brew bump-formula-pr`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb).
​
This works great in Homebrew/homebrew-core for macOS, but not so great in Homebrew/linuxbrew-core as the version bump mechanism for the majority of Homebrew on Linux formulae is via merges from the macOS repo into the Linux repo, roughly once per day, done by maintainers.
​
Currently, Homebrew on Linux users who employ `brew bump-formula-pr` as their tool of choice raise their formulae PRs against `Homebrew/linuxbrew-core` as that's the default tap on Linux. This is a bad user experience, as users who try to be helpful end up with their pull-request closed by maintainers, because they've unknowingly submitted it to the wrong repo.

If the tap's remote is `Homebrew/linuxbrew-core`, `brew bump-formula-pr` could somehow:
​
- Check that the formula that a user is trying to update exists in `Homebrew/homebrew-core`, then either:​
  - Raise the version bump PR against Homebrew/homebrew-core instead of Homebrew/linuxbrew-core
  - Signpost users towards Homebrew/homebrew-core with some text explaining why
  - Some other solution - feedback and ideas welcome!
​
# The motivation for the feature

Currently, users who submit formulae updates are redirected by maintainers to submit their changes to Homebrew/homebrew-core in most cases, or they realise that themselves. This takes up maintainers' time. It's also potentially discouraging for the submitter, because their PR is closed through no fault of their own.

The tools that we advertise as being good entry points for contributing should work according to our workflows, across both macOS and Linux.

Evidence:

- https://github.com/Homebrew/linuxbrew-core/pull/14541 (a user needed signposting)
- https://github.com/Homebrew/linuxbrew-core/pull/14280 (a user realised themselves)
- https://github.com/Homebrew/linuxbrew-core/pull/14599 (a dummy test)

# How the feature would be relevant to at least 90% of Homebrew users
​
A _lot_ of users update formulae with `brew bump-formula-pr` in Homebrew/homebrew-core, and as Homebrew on Linux gains more users, we'll run into this problem more and more.
​
# What alternatives to the feature have been considered
​
- Maintainers signposting users manually, as we have been doing. But that takes up time that could be used elsewhere.
- Not allowing users to `brew bump-formula-pr` while running Homebrew on Linux. This has the side effect of discouraging initial contributions from users, decreasing the likelihood that they will get more involved in the future.

**Comment by MikeMcQuaid** [comment]
This makes sense to me. Good idea @issyl0!

> * Not allowing users to `brew bump-formula-pr` while running Homebrew on Linux. This has the side effect of discouraging initial contributions from users, decreasing the likelihood that they will get more involved in the future.

This may make sense to do as a quick PR while the other one is in development.

**Comment by issyl0** [comment]
> [Not allowing users to `brew bump-formula-pr` while running Linux] may make sense to do as a quick PR while the other one is in development.

I was going to do a quick `odie "Unsupported on Linux." unless OS.mac?` edit to address this, then I remembered that `brew bump-formula-pr` is used for Linux-specific taps other than linuxbrew-core (for example linuxbrew/extra and xorg), and that would disable it for _everyone_ no matter what formula they were trying to update in which tap. Due to this, I feel we should just wait for the actual improvements rather than dealing with these edge cases temporarily. :crossed_fingers: :pray:

**Comment by dawidd6** [comment]
I just run into this issue. Good it is already tracked.

Can I ask if there are any ideas on how to make `bump-formula-pr` work on linux too?

**Comment by jonchang** [comment]
> Can I ask if there are any ideas on how to make `bump-formula-pr` work on linux too?

Yes, this is under the header "A detailed description of the proposed feature" in the original post. Please feel free to open a pull request working on this; I'd be happy to review it.

**Comment by morganrconnolly** [comment]
I'd like to tackle this

**Comment by reitermarkus** [comment]
@morganrconnolly, please go ahead! 👍

**Comment by dawidd6** [comment]
@morganrconnolly any progress on this?

**Comment by morganrconnolly** [comment]
@dawidd6 apologies for the delay. Here's a first stab https://github.com/Homebrew/brew/pull/6538 . I'm not sure what the appropriate development workflow is for brew commands, e.g. how do modify a command, rebuild brew and then test the modified command. Is there any documentation about this you can point me towards?

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/pull/6718
