### ISSUE TITLE
`brew extract` returns errors for some formula-version combinations

### ISSUE THREAD

**Issue by simonrouse9461** [Homebrew/brew#6345]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
```bash
> brew config
HOMEBREW_VERSION: 2.1.9-7-gde72a23
ORIGIN: https://github.com/Homebrew/brew
HEAD: de72a2310930c3f0903292770b433f197a8d8a6c
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e58c5f3df889abc9f7ba16b37a0becff972f9237
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.4, 1.8.0_211
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11

> brew doctor
Your system is ready to brew.
```

# What you were trying to do (and why)
I want to extract a specific version of a formula (in this case python 3.6.2) to my own tap.

# What happened (include command output)
Extraction failed with an error.

<details>
  <summary>Command output</summary>
  <pre>
Error: python: undefined method `undent' for #&lt;String:0x00007f832a57b0e8&gt;
  </pre>
</details>

# What you expected to happen
This shouldn't return an error.

# Step-by-step reproduction instructions (by running `brew` commands)
This works fine:
```bash
> brew extract --version=3.7.2 python <my_repo>/versions
==> Searching repository history
==> Writing formula for python from revision 0940099 to /usr/local/Homebrew/Library/Taps/<my_repo>/homebrew-versions/Formula/python@3.7.2.rb
```
This gives an error:
```bash
> brew extract --version=3.6.2 python <my_repo>/versions
==> Searching repository history
Error: python: undefined method `undent' for #<String:0x00007f832a57b0e8>
```
**Note:** this is not only for python. I've tried other formulae, same thing happens.

**Comment by jonchang** [comment]
If you run this with `--debug` you'll see that it never actually gets to version 3.6.2, because the `python` formula changes from 2.7 to 3.6.4 at some point in the past. Furthermore, because `brew extract` needs to load each formula, our internal formula interface has changed and some formula code is no longer valid in e.g., brew 2.0.

I think we would be interested in a pull request that caught these cases and improved the error message.

**Comment by MikeMcQuaid** [comment]
Agreed, will accept PR that fixes that, thanks.
