### ISSUE TITLE
brew info passes argument as lowercase

### ISSUE THREAD

**Issue by YoYo-Pete** [Homebrew/brew#6348]
- [√] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [√ ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [√] ran `brew update` and can still reproduce the problem?
- [√] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [√] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

`brew info Caskroom/cask/dbeaver-community`
Trying to see if new version of a cask is out.

# What happened (include command output)

The argument of `Caskroom/cask/dbeaver-community` was changed to lowercase on execution causing the command to error.

It suggests a cask of the same name and capitalization which just seems odd to a user.

<details>
  <summary>Command output</summary>
  <pre>brew info Caskroom/cask/dbeaver-community
Error: No available formula with the name "caskroom/cask/dbeaver-community" 
Found a cask named "Caskroom/cask/dbeaver-community" instead.
  </pre>
</details>

<details>
  <summary>brew doctor output</summary>
  <pre>brew doctor                              
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  nano
  r
</pre>
</details>

<details>
  <summary>brew config output</summary>
  <pre>brew config 
HOMEBREW_VERSION: 2.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3dab11263c7d3ae568bd585932b393ef526fc5b2
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 91efd0ce3f57f0eb48b20f7a029ea6014e0ee21b
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_171
macOS: 10.14.6-x86_64
CLT: 11.0.0.0.1.1559496560
Xcode: N/A
CLT headers: 11.0.0.0.1.1559496560
</pre>
</details>

# What you expected to happen

To execute the command with no error or suggestion.

# Step-by-step reproduction instructions (by running `brew` commands)

run command: `brew info Caskroom/cask/dbeaver-community`

<img width="1004" alt="Screen Shot 2019-08-05 at 12 14 26 PM" src="https://user-images.githubusercontent.com/3034349/62479799-47351680-b77c-11e9-9c74-90b9b7ff20de.png">

**Comment by zachauten** [comment]
The reason you're getting the error is because you're using `brew info` on a cask instead of `brew cask info`. See #5456. 

If you use `brew cask info dbeaver-community` brew should output the same information without the error message.
