### ISSUE TITLE
Icons in Casks

### ISSUE THREAD

**Issue by cagcoach** [Homebrew/brew#6354]
# A detailed description of the proposed feature
I wish to have a field "icon" in the casks files which contains a downloadlink to an Image/Icon-File corresponding to the Program-Icon. 

# The motivation for the feature
I am currently working on a project which I named BrewStore[1].
Homebrew has a lot advantages for everyday use, but the needed knowlage about terminals are stopping Non-Computer-People in using it (e.g. my Grandma)
To change this I started working on a GUI-Tool which should work a bit like the AppStore or the Ubuntu-Software-Center. 
My problem: At the moment all casks look exactly the same. So I need program icons.
Furthermore: Adding an icon field is only a design-decision for the cask files. The only thing which changes is the template file for creating new casks and some of the existing casks (even if the change might come quite slowly). 
[1] https://github.com/cagcoach/BrewStore

# How the feature would be relevant to at least 90% of Homebrew users
Icons are a necessity to make homebrew available for the large majority of Computer-Users. So they are a necessity for a large majority of future homebrew users.

# What alternatives to the feature have been considered
- Providing icon-files directly, BUT I am not a layer and I don't know whether there are some Copyright issues.
- An alternative for me would be to fork the Cask-Database. But maintaining and syncing the image-database to the actuall available cask library would be a hell.

**Comment by MikeMcQuaid** [comment]
I would suggest you do this in your GUI store yourself or auto extract them after installation.
