### ISSUE TITLE
Wrong tcl-tk version when run "brew install python3"

### ISSUE THREAD

**Issue by Rhythmicc** [Homebrew/brew#6357]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

When I run `brew install python3`, the tcl-tk version is wrong.
I've try several test including:

- Running `brew install python3 --with-tcl-tk` doesn't work.

- The above is also tested with an uninstall/install cycle.

- Python keeps using system Tcl/TK after installing latest ActiveTcl,  even though I move `tcl8.6` to `/usr/local/lib`.

# What happened (include command output)

This makes it impossible for me to use the tkinter library properly, such as not being able to input Chinese and not displaying button content.

<details>
  <summary>Command output</summary>
  <pre>
  
  None
  
  </pre>
</details>

# What you expected to happen

I expected that:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/29839231/62837564-6dd6de00-bca3-11e9-83eb-3d9f9a5e6e33.png">

# Step-by-step reproduction instructions (by running `brew` commands)

Just `brew install python3`. I think it's a simple problem, but it hasn't been fixed for more than a month.

**Comment by MikeMcQuaid** [comment]
Homebrew/homebrew-core (the default repository/tap) no longer provides options for any formulae since Homebrew 2.0.0.

**Comment by EricFromCanada** [comment]
Would it be possible to change the `python3` formula to use a Tcl/Tk version other than Apple's? This would solve a few of [these issues](https://www.python.org/download/mac/tcltk/).

**Comment by MikeMcQuaid** [comment]
See https://github.com/Homebrew/homebrew-core/issues/41338#issuecomment-507267450. TL;DR: it needs a patch which someone needs to submit upstream before we could use it.
