### ISSUE TITLE
Errors with HOMEBREW_DEBUG enabled with `redact_secrets` and nil secrets

### ISSUE THREAD

**Issue by geoff-nixon** [Homebrew/brew#6363]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

`brew search ...` w/ `HOMEBREW_DEBUG=1` exported and no `HOMEBREW_GITHUB_API_TOKEN` or other "sensitive" environmental variables set. (Because... I wanted to perform a search.)

# What happened (include command output)

Error was returned ~~due to incorrect formatting of regular expression syntax with combination of methods `Enumerable#reduce` and `String#gsub` in `utils.rb`~~.

<details>
  <summary>Command output</summary>
  <pre>
 
```
$  brew search ''
Error: wrong argument type nil (expected Regexp)
/Users/Shared/Developer/Homebrew/Library/Homebrew/utils.rb:505:in `gsub'
/Users/Shared/Developer/Homebrew/Library/Homebrew/utils.rb:505:in `block in redact_secrets'
/Users/Shared/Developer/Homebrew/Library/Homebrew/utils.rb:505:in `each'
/Users/Shared/Developer/Homebrew/Library/Homebrew/utils.rb:505:in `reduce'
/Users/Shared/Developer/Homebrew/Library/Homebrew/utils.rb:505:in `redact_secrets'
/Users/Shared/Developer/Homebrew/Library/Homebrew/system_command.rb:37:in `run!'
/Users/Shared/Developer/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/Users/Shared/Developer/Homebrew/Library/Homebrew/system_command.rb:15:in `system_command'
/Users/Shared/Developer/Homebrew/Library/Homebrew/utils/curl.rb:82:in `curl_output'
/Users/Shared/Developer/Homebrew/Library/Homebrew/utils/github.rb:198:in `open_api'
/Users/Shared/Developer/Homebrew/Library/Homebrew/utils/github.rb:357:in `search'
/Users/Shared/Developer/Homebrew/Library/Homebrew/utils/github.rb:273:in `search_code'
/Users/Shared/Developer/Homebrew/Library/Homebrew/search.rb:41:in `search_taps'
/Users/Shared/Developer/Homebrew/Library/Homebrew/cmd/search.rb:82:in `search'
/Users/Shared/Developer/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```
  
  </pre>
</details>

# What you expected to happen

A successful search.

# Step-by-step reproduction instructions (by running `brew` commands)

<details>
  <summary>Command output</summary>
  <pre>
 
```
$ brew search ''
usr/bin/curl -q --show-error --user-agent Homebrew/2.1.10-dirty\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --location https://api.github.com/search/code\?q=user\%3AHomebrew\+path\%3AFormula\+path\%3ACasks\+path\%3A.\+filename\%3A\+extension\%3Arb\&per_page=100 --header application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --dump-header /private/tmp/github_api_headers...
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::AliasLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zero-install.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::AliasLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zeromq.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::AliasLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/twoping.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::AliasLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fourstore.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::AliasLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tass64.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/a2ps.rb
```
  </pre>
(Or something to that effect.)
</details>

---

~~I believe the issue is that~~
```ruby
{ |str, secret| str.gsub secret, "******" }
```
~~needs to be~~
```ruby
{ |str, secret| str.gsub /secret/, "******" }
```
(Nope!)
... or something to that effect. Apologies not submitting a patch as I don't myself use these methods with this syntax (and  I don't actually know if that is the _correct_ syntax, nor how to test if `redact_secrets` is doing what it should). `/secret/ does, however, eliminate or repress the error.

---

#### `brew config; brew doctor`

<details>
  <summary>Command output</summary>
  <pre>

```
$ brew search ''
```
$ brew config; brew doctor
HOMEBREW_VERSION: 2.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 925ec737fba1db97d0170c56de982900711cacd3
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b7d38f247d646975d6186b005729a1343ad96e21
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1, 11.0.2, 1.8.0_222, 1.6.0_65-b14-468
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
Your system is ready to brew.
```
  </pre>
</details>

**Comment by jonchang** [comment]
I can't reproduce this bug. `HOMEBREW_DEBUG=1 brew search ''` returns a list of all formulae, as expected.

**Comment by geoff-nixon** [comment]
> I can't reproduce this bug. `HOMEBREW_DEBUG=1 brew search ''` returns a list of all formulae, as expected.

I unfortunately don't know how to trace it further without something breaking (it yells at me if I try to run `brew.rb` directly, etc.) ...?

But FWIW, this is reproducible for me with a brand new user and a brand new, standard Homebrew install in /usr/local without any other variables manually or in a rc or profile files. 😕

**Comment by geoff-nixon** [comment]
Update:
@jonchang do you happen to have HOMEBREW_GITHUB_API_TOKEN set, or something similar?

Looking at 
https://github.com/Homebrew/brew/blob/925ec737fba1db97d0170c56de982900711cacd3/Library/Homebrew/system_command.rb#L37
https://github.com/Homebrew/brew/blob/925ec737fba1db97d0170c56de982900711cacd3/Library/Homebrew/system_command.rb#L67

and 

https://github.com/Homebrew/brew/blob/925ec737fba1db97d0170c56de982900711cacd3/Library/Homebrew/extend/ENV.rb#L33

if I have HOMEBREW_GITHUB_API_TOKEN set (to anything) this goes away. However, if `@secrets` is nil, there's the error.

**Comment by MikeMcQuaid** [comment]
@geoff-nixon Can you `brew pull` or `hub checkout` (or equivalent) https://github.com/Homebrew/brew/pull/6364 and see if you can still reproduce with that PR? Thanks!

**Comment by geoff-nixon** [comment]
@MikeMcQuaid Yup, https://github.com/Homebrew/brew/pull/6364 does the trick! For posterity, I've edited the issue slightly to reflect that fact I was incorrect about the `redact_secrets` function.

👍 

Thanks for the quick fix!
