### ISSUE TITLE
Travis complaining about "uninitialized constant Language::Python::Virtualenv" in php tap

### ISSUE THREAD

**Issue by javian** [Homebrew/brew#637]
### Bug reports:

Since a few days back the Travis instance of homebrew-php is not able to do what its supposed to.  It currently throws out 2 errors

`Error: Cannot tap homebrew/core: invalid syntax in tap!`
and
`uninitialized constant Language::Python::Virtualenv`

An example can be seen here
https://travis-ci.org/Homebrew/homebrew-php/builds/149986898

Do you have any idea on what could be causing this ?

**Comment by ilovezfs** [comment]
The Travis image is not up to date and the php tap is trying to `brew tap homebrew/dupes`   and `brew tap homebrew/versions` before running `brew update`.

**Comment by ilovezfs** [comment]
@javian it should be fixed now.
