### ISSUE TITLE
speedup `brew search`

### ISSUE THREAD

**Issue by palxex** [Homebrew/brew#6371]
# A detailed description of the proposed feature
Yes I know there're already such issue before, BUT my situation is unacceptable. `time brew search xxx` cost me 15 MINUTES.

# The motivation for the feature
Please give me a method resolve it or at least address it.

# How the feature would be relevant to at least 90% of Homebrew users
Everybody requires search before installing, I think.

# What alternatives to the feature have been considered
I've tried use `brew search|grep xxx` as instead( since it only list local formula, much faster, and fit MOST of my need ), it at least able to give result in several seconds. BUT it does not work with cask, after `brew cask search xxx` merged into `brew search xxx`, but the `brew search` without argument only list all  local formula, no casks.

Environment: brew 981269
brew-config: 
[brew-config.txt](https://github.com/Homebrew/brew/files/3511954/brew-config.txt)
After the 15 minute result I've disabled brew auto update & GitHub token. After that the result is 2 minute, still unacceptable, and much much higher than `brew search` without argument.

brew-doctor:
[brew-doctor.txt](https://github.com/Homebrew/brew/files/3511957/brew-doctor.txt)

**Comment by MikeMcQuaid** [comment]
> unacceptable

If it's unacceptable to you you have two options:
- Don't use `brew search`
- Submit a pull request to speed up `brew search`.
