### ISSUE TITLE
Error: stack level too deep

### ISSUE THREAD

**Issue by gregorywright** [Homebrew/brew#6386]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Been a long time since I upgrade, so I tried, here is my command history just before brew went infinitely recursing and asked me to file a bug report (I am not after any particular fix since running `brew upgrade` after this crash shows that it actually upgraded everything):

```
14514  brew install xteddy
14515  brew upgrade
14516  xcode-select --install
14517  brew upgrade
```

- What happened (include command output)

```
Error: stack level too deep
Please report this bug:
  https://docs.brew.sh/Troubleshooting
```
See: https://gist.github.com/gregorywright/9ae22e2b65eed4ce59162fa55c4824e1

- What you expected to happen

Don't crash. 

- Step-by-step reproduction instructions (by running `brew install` commands)

```
14514  brew install xteddy
14515  brew upgrade
14516  xcode-select --install
14517  brew upgrade
```

- Brew Doctor

```
~(:|✔) % brew doctor
Your system is ready to brew.
```

- Brew config

```
~(:|✔) % brew config
HOMEBREW_VERSION: 2.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 925ec737fba1db97d0170c56de982900711cacd3
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 17c88e364dbda7a5e108341efde064b38388552a
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_211
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```

**Comment by fxcoudert** [comment]
So as a maintainer I can't actually reopen an issue and override the bot? That is going to make migration of issues useless :(

**Comment by fxcoudert** [comment]
@gregorywright can you please file it as a new issue, and provide the requested information?

**Comment by MikeMcQuaid** [comment]
@fxcoudert If you want to migrate issues in that way you can tweak https://github.com/Homebrew/brew/blob/master/.github/issue-close-app.yml and https://github.com/Homebrew/homebrew-core/blob/master/.github/issue-close-app.yml so they match the same strings.

@gregorywright Can you test if https://github.com/Homebrew/brew/pull/6387 fixes your problem?

**Comment by MikeMcQuaid** [comment]
@amyspark Would love your help with this as you wrote the original code ❤️

**Comment by georgexsh** [comment]
I have seen this issue again with 2.1.15-107-g5da322d, which has patch #6397:

```
/usr/local/Homebrew $ git br --contains 4822241
* master
```

```
$ brew config
HOMEBREW_VERSION: 2.1.15-107-g5da322d
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5da322d6be314e5f8b1729e91e60be743a1e7d8e
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aebd7fc2b250ad6755cad30281e9a0fec13e41c9
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_72
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
This is being tracked in https://github.com/Homebrew/brew/issues/6671#issuecomment-548887465.
