### ISSUE TITLE
Brew install crashes when ran from a non-existent folder

### ISSUE THREAD

**Issue by revolter** [Homebrew/brew#639]
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

`brew install` crashes when ran from a non-existent folder:

```
~ ❯ mkdir test
------------------------------------------------------------
~ ❯ cd test
------------------------------------------------------------
~/test ❯ rm -rf ../test
------------------------------------------------------------
~/test ❯ brew install sqlcipher
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: The current working directory doesn't exist, cannot proceed.
```

**Comment by MikeMcQuaid** [comment]
We'll accept a PR to fix this but given this applies to lots of Unix commands: don't do that 😉

**Comment by revolter** [comment]
The thing is that it was already installed, so it's odd to get an error for accessing a non-existent folder for just a `Warning: sqlcipher-3.4.0 already installed` message.
