### ISSUE TITLE
How do I get deprecated packages?

### ISSUE THREAD

**Issue by clubery** [Homebrew/brew#6396]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Homebrew will only let me install phpunit 8.0 with php 7+, I don't have a clue about taps and all the other stuff. It used to just work for me with php 5.x and phpunit 6.1.4, now I have a new laptop, nothing works and it won't install what I need. Upgrading this legacy piece of software just because homebrew has decided to stop me from downloading it is out of the question as I just need to fix a bug for a client.

How can I get all the previous packages I had using homebrew without having to update the whole application?

# What happened (include command output)

Latest versions installed

# What you expected to happen

install older versions

# Step-by-step reproduction instructions (by running `brew` commands)

brew install blah@blah
brew search blah - returns no older versions

**Comment by MikeMcQuaid** [comment]
> * [x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh

This is not a bug. You have a question on how to use Homebrew: ask it in Discourse.
