### ISSUE TITLE
Java tests (and maybe other `java` use) may fail under sandbox

### ISSUE THREAD

**Issue by apjanke** [Homebrew/brew#64]
With newer releases of Java 1.7 and 1.8, it looks like most uses of `java` will fail under sandboxing with the JRE's default configuration.

Example: the new test for neo4j is failing.

```
$ brew test --verbose neo4j
Testing neo4j
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160410-45054-1ru5j4o.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/neo4j.rb --verbose
==> /usr/local/Cellar/neo4j/2.3.3/bin/neo4j start
Starting Neo4j Server.../private/tmp/neo4j20160410-45055-787qej/libexec/data/log/neo4j.log was missing, recreating...
WARNING: not changing user
process [45165]... waiting for server to be ready.. Failed to start within 120 seconds.
Neo4j Server may have failed to start, please check the logs.
==> Sandbox log
Apr 10 21:00:26 sandboxd[122]: java(45145) deny file-write-data /Users/janke/.oracle_jre_usage/42d8591bd1e10f3f.timestamp
Apr 10 21:00:26 sandboxd[122]: java(45147) deny file-write-data /Users/janke/.oracle_jre_usage/42d8591bd1e10f3f.timestamp
Apr 10 21:00:26 sandboxd[122]: java(45165) deny file-write-data /Users/janke/.oracle_jre_usage/42d8591bd1e10f3f.timestamp
Error: neo4j: failed
Failed executing: /usr/local/Cellar/neo4j/2.3.3/bin/neo4j start
/usr/local/Library/Homebrew/formula.rb:1481:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1418:in `open'
/usr/local/Library/Homebrew/formula.rb:1418:in `system'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/neo4j.rb:44:in `block in <class:Neo4j>'
/usr/local/Library/Homebrew/formula.rb:1327:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:36:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1323:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

Those writes to `/Users/janke/.oracle_jre_usage/` are from the [Java Usage Tracker](https://docs.oracle.com/javacomponents/usage-tracker/overview/) which was recently introduced, and seems to be enabled by default in the current JDKs on OS X.

It does not seem to respect the `$HOME` environment variable. Looks like it's doing a `getpwent` instead, so it always goes to the actual home directory even if `$HOME` is set.

Changing this behavior on a per-program basis would require setting Java system properties inside launch scripts, which sounds like a pain. I think we should consider whitelisting this specific directory under our sandbox for build and test.

**Comment by tdsmith** [comment]
related: https://github.com/Homebrew/legacy-homebrew/pull/44567

**Comment by DomT4** [comment]
This problem is why `ENV.java_cache` exists. Try setting that inside `test do` and see if it works.

**Comment by apjanke** [comment]
Looks like this might be a red herring: once whitelisting `~/.oracle_jre_tracking` in the sandbox, that `neo4j` formula is still failing at about the same spot, and only under the sandbox.

I'll try the `ENV.java_cache` thing.

**Comment by apjanke** [comment]
The `ENV.java_cache` thing isn't working - the deny writes still happen - but expanding that `$_JAVA_OPTS` would let us tweak the JRE Tracking configuration to repoint the logs, without having to open the sandbox more. I had forgotten about `$_JAVA_OPTS`. Thanks.

**Comment by DomT4** [comment]
More specifically, to answer your broader question, I don't think we should deviate from our policy that running Homebrew formulae installs and tests shouldn't write to user's `$HOME` directories.

It's perhaps worth noting that sandbox errors _can_ be false positives. Not all sandbox errors are fatal, for example, it dumps the sandbox log whether the errors were actually problematic or not. For example here:

```
==> /usr/local/Cellar/neo4j/2.3.3/bin/neo4j start
Unable to find any JVMs matching version "1.7".
Starting Neo4j Server.../private/tmp/neo4j20160411-41946-fa9z5n/libexec/data/log/neo4j.log was missing, recreating...
WARNING: not changing user
process [42058]... waiting for server to be ready.. Failed to start within 120 seconds.
Neo4j Server may have failed to start, please check the logs.
Error: neo4j: failed
```

And then without `ENV.java_cache`:
```
==> /usr/local/Cellar/neo4j/2.3.3/bin/neo4j start
Unable to find any JVMs matching version "1.7".
Starting Neo4j Server.../private/tmp/neo4j20160411-42371-1fko2pd/libexec/data/log/neo4j.log was missing, recreating...
WARNING: not changing user
process [42482]... waiting for server to be ready.. Failed to start within 120 seconds.
Neo4j Server may have failed to start, please check the logs.
==> Sandbox log
Apr 11 02:41:15 sandboxd[140]: java(42462) deny file-write-create /Users/Dominyk/.oracle_jre_usage
Apr 11 02:41:15 sandboxd[140]: java(42462) deny file-write-create /Users/Dominyk/.oracle_jre_usage
Apr 11 02:41:15 sandboxd[140]: java(42464) deny file-write-create /Users/Dominyk/.oracle_jre_usage
Apr 11 02:41:15 sandboxd[140]: java(42464) deny file-write-create /Users/Dominyk/.oracle_jre_usage
Apr 11 02:41:15 sandboxd[140]: java(42482) deny file-write-create /Users/Dominyk/.oracle_jre_usage
Apr 11 02:41:15 sandboxd[140]: java(42482) deny file-write-create /Users/Dominyk/.oracle_jre_usage
Error: neo4j: failed
```

But those files not being created doesn't seem to be the error, otherwise the `ENV.java_cache` one would  have passed.

**Comment by DomT4** [comment]
FWIW the `.oracle_jre_usage` logs, when `ENV.java_cache` is applied, are created in `HOMEBREW_CACHE/java_cache`. You'll find them created in there okay.

**Comment by apjanke** [comment]
Okay. Maybe I was getting a false positive from multiple test runs.

Agree we shouldn't open up anything under `$HOME` if we can help it.

Closing this out since it looks like `ENV.java_cache` takes care of it.

**Comment by DomT4** [comment]
`ENV.java_cache` is pretty much undocumented at the moment, so my apologies if that was a pain in trying to poke around this issue.
