### ISSUE TITLE
Devel/HEAD ignored by analytics

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#640]
For some reason, our anonymous usage data is excluding `--devel` & `--HEAD` from the install options passed, which makes gathering data on how urgent/desired features like `devel` bottles & https://github.com/Homebrew/brew/pull/625 are difficult.

Need to look into this at some point so we can chart a path ahead on `devel` that reflects how people are really using the existing features & whether it's worth us building on them & maintaining that code indefinitely.

**Comment by ilovezfs** [comment]
Analytics aside, devel bottles sound generally like a :-1: idea since they lower the barriers to entry for potentially unstable/insecure software.

**Comment by DomT4** [comment]
Devel bottles have been planned & promised for a _long_ time now. Unlike `--HEAD` we have actually supported `--devel`, we accept patches for it, we test it builds with every CI run, we execute `brew test` on it, we have an upgrade process for it. The only switch left to flip is the bottle one.

Frankly, package management as a whole lowers the barriers to potentially unsafe/insecure software. `brew install vim`, did anyone bother reading the `vim` source code in the most recent release to check nothing nasty had slipped in there? Doubt it.

I don't consider `devel` any more heinous than anything else we do around here. Nonetheless, let's try to keep this discussion relevant to the actual analytics issue, since that's why it was opened.

**Comment by ilovezfs** [comment]
:see_no_evil:

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/brew/commit/19920e18a129a21890d9d8bd6443cd1afd32208b.
