### ISSUE TITLE
brew install  php@7.1  --enable-fpm

### ISSUE THREAD

**Issue by aixiaoxiang** [Homebrew/brew#6401]
brew install  php@7.1  --enable-fpm

result ：
 
 `Error: invalid option: --enable-fpm`

**Comment by aixiaoxiang** [comment]
resolved ， thanks

**Comment by durban89** [comment]
> resolved ， thanks

how? i want to enabled zts ,beacause i want to usw ptheads

**Comment by Jossnaz** [comment]
> resolved ， thanks

really? what was the solution? you letting everyone down here.

**Comment by aixiaoxiang** [comment]
> > resolved ， thanks
> 
> really? what was the solution? you letting everyone down here.

see Homebrew/homebrew-core

https://github.com/Homebrew/homebrew-core/blob/deb8bf1a7af8987f990b0214085cabe27638206a/Formula/php%407.1.rb#L106

option --enable-fpm is default enable

**Comment by aixiaoxiang** [comment]
> > resolved ， thanks
> 
> really? what was the solution? you letting everyone down here.

see Homebrew/homebrew-core

https://github.com/Homebrew/homebrew-core/blob/4d780df39c0672ad6147aac3bcdf95f1d3bf9bc8/Formula/php%407.1.rb

**Comment by MikeMcQuaid** [comment]
> you letting everyone down here.

No, they aren't. Please be more polite.
