### ISSUE TITLE
Gedit install, no icon in Applications

### ISSUE THREAD

**Issue by mgscreativa** [Homebrew/brew#6402]
# What you were trying to do (and why)

Trying to install Gedit text editor

# What happened (include command output)

brew install gedit works fine, but afret finishing, I have no Gedit app in applications

<details>
  <summary>Command output</summary>
  <pre>
  
Everything seems right
  
  </pre>
</details>

# What you expected to happen

Have Gedit icon in Applications

# Step-by-step reproduction instructions (by running `brew` commands)

brew install gedit

**Comment by mgscreativa** [comment]
Filled out the checklist

**Comment by MikeMcQuaid** [comment]
> brew install gedit works fine, but afret finishing, I have no Gedit app in applications

Homebrew doesn't install links into `/Applications`. `brew cask` does.

**Comment by mgscreativa** [comment]
Ohh I see, is there a `cask` for it available?

**Comment by MikeMcQuaid** [comment]
No, sorry.
