### ISSUE TITLE
Cannot read termcap database OR No entry for terminal type

### ISSUE THREAD

**Issue by feliperaul** [Homebrew/brew#6415]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Use my Rails console without errors and with a functional up arrow.

# What happened (include command output)

Fresh install in a new mac (Mojave). 

Every time I start a rails console in ANY project (even a brand new rails one), I get a random error message (one of the following variations), which I can only assume is a bug related to the bugfix reported here (https://github.com/Homebrew/brew/pull/5445), which hasn't been fixed completely.

Not only that exact same error messages get echoed in my Rails console, but the up arrow breaks inside the rails console (so I can't use command history).

Here are some example messages:

This is the most common:
```
rails c
Running via Spring preloader in process 35560
Loading development environment (Rails 5.2.2.1)
Cannot read termcap database;
using dumb terminal settings.
```

```
rails c
Running via Spring preloader in process 40631
Loading development environment (Rails 5.2.2.1)
No entry for terminal type "s/myself/.oh-my-zsh";
using dumb terminal settings.
```
This path "s/myself" is actually "Users/myself", I don't know why it was clipped.

```
rails c
Running via Spring preloader in process 32098
Loading development environment (Rails 5.2.2.1)
No entry for terminal type "s/myself/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'";
using dumb terminal settings.
```

```
rails c
Running via Spring preloader in process 41257
Loading development environment (Rails 5.2.2.1)
No entry for terminal type "s/myself/dev/new_rails_project/lib";
using dumb terminal settings.
```

```
rails c
Running via Spring preloader in process 61975
Loading development environment (Rails 5.2.3)
No entry for terminal type "2.5.0/irb/slex";
```

# What you expected to happen

My Rails console to work fine without random error messages and up arrow working.

This is a fresh install, I have 8+ years in Rails development, never seen anything like this before.

I have:
- Read every single google / stackoverflow post regarding "No entry for terminal type", "Cannot read termcap database" and "using dumb terminal settings" and tried every other possible fix (there are very few entries).
- Changed my terminal advanced settings from x-term-256-color to x-term (was suggested in SO);
- Tried with mac default terminal (Bash) and with Oh My Zsh;
- Uninstalled ruby using rbenv and installed it again, including all gems;
- Uninstalled readline and installed it again;
- Tried in various rails projects, including brand new ones;

➜  ~ brew config
```
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 670c569cd41cc594d2939eada8514fad980e043c
Core tap last commit: 22 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_222
macOS: 10.14.5-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
```

**Comment by feliperaul** [comment]
I have filled up the template!

**Comment by jonchang** [comment]
Can you please post the exact commands you use from a working system, including `brew install` etc commands and the commands you are using in rails?

`No entry for terminal type "s/myself/.oh-my-zsh";` suggests that some aspect of your `bashrc` or similar is setting the `TERM` variable to something unrelated.

**Comment by jonchang** [comment]
Please add the steps to reproduce under the header `Step-by-step reproduction instructions (by running `brew` commands)`.

**Comment by MikeMcQuaid** [comment]
I see no evidence this has anything to do with Homebrew but instead Rails.
