### ISSUE TITLE
`brew audit` falsely reports some HTTP status codes as errors

### ISSUE THREAD

**Issue by alebcay** [Homebrew/brew#6431]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Update `talloc` to version 2.3.0 ([homebrerw-core PR](https://github.com/Homebrew/homebrew-core/pull/43992)).

# What happened (include command output)

CI reported `brew audit` failure regarding stable URL not being reachable. I was able to reproduce the failure locally.

<details>
  <summary>Command output</summary>
  <pre>
❯ brew audit talloc --strict --online
talloc:
  * Stable: The URL https://www.samba.org/ftp/talloc/talloc-2.3.0.tar.gz is not reachable (HTTP status code 103)
Error: 1 problem in 1 formula detected
  </pre>
</details>

# What you expected to happen

Successful audit without any problems.

# Step-by-step reproduction instructions (by running `brew` commands)

`brew audit --strict --online talloc`

-----

<details>
<summary>brew config output</summary>
<pre>
❯ brew config
HOMEBREW_VERSION: 2.1.11-36-g7dd0466
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7dd0466bf3073f8ffa4fad0eb9e353dff538780a
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 781334577ed3e81ea421c848a3403ec1896ce177
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.1, 1.8.0_172
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
</pre>
</details>

<details>
<summary>brew doctor output</summary>
<pre>
❯ brew doctor
Your system is ready to brew.
</pre>
</details>

-----
HTTP 1xx status codes (e.g. 103, like encountered here with `talloc`) are informational. It is usually not the final response to be returned, so at least the 1xx status codes probably should not be treated as errors.

**Comment by MikeMcQuaid** [comment]
Is it still possible to download the referenced URL? If so: yes, the `audit` should be addressed to handle this case. Would you be able to open a PR @alebcay?

Also, can you check your Slack messages on the Homebrew Slack when you get a chance? Want to talk to you about the great work you've been doing recently ❤️

**Comment by alebcay** [comment]
Yes, the `talloc` download works just fine (other browsers/clients seem to get a 200 instead of the 103, probably because 103 is just a preliminary response of some kind). Should `audit` be addressed to handle just 103, or all 1xx codes?

**Comment by MikeMcQuaid** [comment]
@alebcay Either 103 or all 1xx code: up to you!

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/Homebrew/brew/pull/6463
