### ISSUE TITLE
--build-from-source ignored for dependencies

### ISSUE THREAD

**Issue by Midar** [Homebrew/brew#6434]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I tried installing easy-tag and all its dependencies from source, using --build-from-source.

# What happened (include command output)

Some dependencies were installed from source, some were bottled. I only realized once it started downloading the rust bottle.

<details>
  <summary>Command output</summary>
  <pre>
  
  brew -v install --build-from-source easy-tag
  
  </pre>
</details>

# What you expected to happen

I expected everything being built from source.

# Step-by-step reproduction instructions (by running `brew` commands)

Run the above brew command.

**Comment by Midar** [comment]
I just noticed that apparently, this is documented behavior now. I think this was different before:

```
    -s, --build-from-source          Compile formula from source even if a
                                     bottle is provided. Dependencies will still
                                     be installed from bottles if they are
                                     available.
```

So I guess this should be changed to a feature request to allow to build everything from source?

There also used to be an environment variable for this that seems to have disappeared, but I cannot find any rationale why it was removed.

**Comment by MikeMcQuaid** [comment]
> So I guess this should be changed to a feature request to allow to build everything from source?

We intentionally do not support this. It provides no benefit to you, wastes electricity (thus destroying the planet) and increases Homebrew's support burden.

**Comment by Midar** [comment]
This is not true: It requires trusting your build infrastructure. You do not do reproducible builds, so this is not possible. On top of that, you had issues with security in the past: https://brew.sh/2018/08/05/security-incident-disclosure/
On top of that, there’s corporations that by policy disallow using binaries that have not been vetted, but allow building from source. So there’s a real need for this feature. I can understand why you don’t want it by default, but it should at least be an expert setting.

**Comment by MikeMcQuaid** [comment]
> I can understand why you don’t want it by default, but it should at least be an expert setting.

No. Homebrew is not a from-source package manager. If you need one: I suggest you find one that meets your needs instead.

> On top of that, you had issues with security in the past: https://brew.sh/2018/08/05/security-incident-disclosure/

Literally every sizeable project has had security issues at some point in the past although not every one may disclose it responsible as we and the security researcher have done.
