### ISSUE TITLE
Error: Failure while executing; `/bin/launchctl enable gui/501/homebrew.mxcl.mysql` exited with 112.

### ISSUE THREAD

**Issue by simplenotezy** [Homebrew/brew#6438]
- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# Brew doctor 
```
[admin:~]$ brew doctor
Your system is ready to brew.
```

# Brew config
```
[admin:~]$ brew config
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b70b0fb73fe6b44db6c3c043348ef418335670d2
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.4
macOS: 10.14.4-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
```

# What you were trying to do (and why)
Installing MySQL so I can work with mysql database locally

# What happened (include command output)
Running: `brew install mysql` then `brew services start mysql` resulting in `Error: Failure while executing; `/bin/launchctl enable gui/501/homebrew.mxcl.mysql` exited with 112.`

```
[admin:~]$ brew install mysql
==> Installing dependencies for mysql: openssl@1.1
==> Installing mysql dependency: openssl@1.1
==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.1c.mojave.bottle.tar.
==> Downloading from https://akamai.bintray.com/e4/e4c85922978ded43321679e00ecb35b47d3924e
######################################################################## 100.0%
==> Pouring openssl@1.1-1.1.1c.mojave.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because openssl/libressl is provided by macOS so don't link an incompatible version.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1c: 7,963 files, 17.9MB
==> Installing mysql
==> Downloading https://homebrew.bintray.com/bottles/mysql-8.0.17_1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/07/07c53f2a0373372d2f613d604b9c17aceedd1a3
######################################################################## 100.0%
==> Pouring mysql-8.0.17_1.mojave.bottle.tar.gz
==> /usr/local/Cellar/mysql/8.0.17_1/bin/mysqld --initialize-insecure --user=admin --based
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

To have launchd start mysql now and restart at login:
  brew services start mysql
Or, if you don't want/need a background service you can just run:
  mysql.server start
==> Summary
🍺  /usr/local/Cellar/mysql/8.0.17_1: 284 files, 272.4MB
==> Caveats
==> openssl@1.1
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because openssl/libressl is provided by macOS so don't link an incompatible version.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

==> mysql
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

To have launchd start mysql now and restart at login:
  brew services start mysql
Or, if you don't want/need a background service you can just run:
  mysql.server start
[admin:~]$ brew services start mysql
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 14 (delta 0), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), done.
Tapped 1 command (43 files, 59.6KB).
Could not find domain for
Error: Failure while executing; `/bin/launchctl enable gui/501/homebrew.mxcl.mysql` exited with 112.

```
# What you expected to happen
MySQL to start.

I cannot access MySQL. If I connect using SequelPro I get: `MySQL said: Can't connect to MySQL server on '127.0.0.1' (61)`
If I connect via terminal using `mysql -uroot` I get: `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)`

# Notes
- I have a multi user setup, with an admin account, and a regular user account as per latest macos security recommendations. I ran all above accounts on my admin account.
- Prior to this, I completely uninstalled brew and mysql. I followed guide: https://coderwall.com/p/os6woq/uninstall-all-those-broken-versions-of-mysql-and-re-install-it-with-brew-on-mac-mavericks

**Comment by untoldone** [comment]
@MikeMcQuaid -- Metapoint related to the handling of this issue ... it seems you left https://github.com/Homebrew/brew/issues/6439 closed (which appears to have been opened as this issue was auto-closed) ... I think that is completely fair.

This said -- locking the thread when there is a dialog going on ... which appeared to have been productive ... gave me a pretty bad impression of the stewardship of the homebrew project as a whole.

It feels like the homebrew project isn't open to discussion that disagrees with its opinions and would rather quash dialog than let it play out. Again, I totally get closing the issue to prevent open issues getting out of hand / limited bandwidth / etc... but stopping the dialog seems to prevent progress to me ...

**Comment by MikeMcQuaid** [comment]
@untoldone Non-bug or longer-form discussion is for our Discourse and not our GitHub issue tracker. Even if all the post-close comments were agreeing with my opinions it would have been locked once the issue was closed and conversation continued.

For my own meta-point: I consider it pretty rude to leave drive-by comments on how we (a small team of volunteers for a project used by millions) are running our project. I've been a maintainer on Homebrew for over 10 years now (and was democratically elected to my current position) and I can tell you that leaving that issue unlocked would not have resulted in any "progress" for our users. In summary, we'll run this project how we feel is best and I recommend you run your projects how you feel is best.

**Comment by untoldone** [comment]
@MikeMcQuaid I'm sorry you feel my feedback was rude -- it was intended to be constructive and not critical for the sake of being critical.

I appreciate the hard work you've put into this and any other project that supports others.

**Comment by MikeMcQuaid** [comment]
@untoldone Thanks for the apology and the kind words.
