### ISSUE TITLE
Error: Failure while executing; `/bin/launchctl enable gui/501/homebrew.mxcl.mysql` exited with 112.

### ISSUE THREAD

**Issue by simplenotezy** [Homebrew/brew#6439]
# What you were trying to do (and why)

Installing MySQL so I can work with mysql database locally

# What happened (include command output)

Running: `brew install mysql` then `brew services start mysql` resulting in `Error: Failure while executing; `/bin/launchctl enable gui/501/homebrew.mxcl.mysql` exited with 112.`

<details>
  <summary>Command output</summary>
  <pre>

[admin:~]$ brew install mysql
==> Installing dependencies for mysql: openssl@1.1
==> Installing mysql dependency: openssl@1.1
==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.1c.mojave.bottle.tar.
==> Downloading from https://akamai.bintray.com/e4/e4c85922978ded43321679e00ecb35b47d3924e
######################################################################## 100.0%
==> Pouring openssl@1.1-1.1.1c.mojave.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because openssl/libressl is provided by macOS so don't link an incompatible version.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1c: 7,963 files, 17.9MB
==> Installing mysql
==> Downloading https://homebrew.bintray.com/bottles/mysql-8.0.17_1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/07/07c53f2a0373372d2f613d604b9c17aceedd1a3
######################################################################## 100.0%
==> Pouring mysql-8.0.17_1.mojave.bottle.tar.gz
==> /usr/local/Cellar/mysql/8.0.17_1/bin/mysqld --initialize-insecure --user=admin --based
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

To have launchd start mysql now and restart at login:
  brew services start mysql
Or, if you don't want/need a background service you can just run:
  mysql.server start
==> Summary
🍺  /usr/local/Cellar/mysql/8.0.17_1: 284 files, 272.4MB
==> Caveats
==> openssl@1.1
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because openssl/libressl is provided by macOS so don't link an incompatible version.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

==> mysql
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

To have launchd start mysql now and restart at login:
  brew services start mysql
Or, if you don't want/need a background service you can just run:
  mysql.server start
[admin:~]$ brew services start mysql
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 14 (delta 0), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), done.
Tapped 1 command (43 files, 59.6KB).
Could not find domain for
Error: Failure while executing; `/bin/launchctl enable gui/501/homebrew.mxcl.mysql` exited with 112.
  
  </pre>
</details>

# What you expected to happen

MySQL to start.

I cannot access MySQL. If I connect using SequelPro I get: `MySQL said: Can't connect to MySQL server on '127.0.0.1' (61)`
If I connect via terminal using `mysql -uroot` I get: `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)`

# Step-by-step reproduction instructions (by running `brew` commands)

Instal mysql then `brew services start mysql` resulting in `Error: Failure while executing; `/bin/launchctl enable gui/501/homebrew.mxcl.mysql` exited with 112.`

# Notes
- I have a multi user setup, with an admin account, and a regular user account as per latest macos security recommendations. I ran all above accounts on my admin account.
- Prior to this, I completely uninstalled brew and mysql. I followed guide: https://coderwall.com/p/os6woq/uninstall-all-those-broken-versions-of-mysql-and-re-install-it-with-brew-on-mac-mavericks
- After installing brew, I ran `mysql` just to check, and I noticed that mysql was installed. It seems as though brew install this by default?

**Comment by simplenotezy** [comment]
I did post everything.
Sidenote: I believe this has to do with troubles running brew on a multi user setup (e.g. one admin account, and one normal user account)

**Comment by MikeMcQuaid** [comment]
@simplenotezy Please don't create duplicate issues in future.

> Could not find domain for

This is your error message. We cannot help you here as it's not a Homebrew bug but you can post in our Discourse.

**Comment by joelparkerhenderson** [comment]
IMHO the root cause is that brew is installing programs (e.g. mysql) in such a way that fails for headless accounts, such as when macOS has a separate user account for brew-related activities, and the account is not using the macOS GUI. IMHO one solution is to change ownership of the relevant files to the correct system user (e.g. mysql).

Here are my notes below, in case they may be useful to other people who find this issue.



Issue:

  * Brew fails to launch MySQL.

  * Brew prints an error message about "launchctl enable GUI".

Symptom:

```sh
brew services start mysql    
Unrecognized domain-target specifier.
Please refer to `man launchctl` for explanation of the domain-target specifiers.
Usage: launchctl enable <service-target>
Error: Failure while executing; `/bin/launchctl enable gui/502/homebrew.mxcl.mysql` exited with 64.
```

Environment:

  * For me, the issue is caused by the missing GUI.

  * This is because I have created a separate user account, named "brew", that I use for brew-related use.

  * This is because I generally want to separate brew-related use from my normal user accounts.

Diagnosis:

  * Use the macOS user switcher to sign in a the brew user. The sign in may take a while, and may require some setup, depending on your macOS version, and whether if you have ever signed in as the brew user after a recent macOS system upgrade.

  * Try the usual `brew services start mysql`. For me, this succeeds. This demonstratres that the issue is dependent on the brew user account.

  * Sign out of the brew user account, and sign in to your usual user account.

Treatment:

```sh
$ sudo brew services start mysql
Password:
Warning: Taking root:admin ownership of some mysql paths:
  /usr/local/Cellar/mysql/8.0.17_1/bin
  /usr/local/Cellar/mysql/8.0.17_1/bin/mysqld_safe
  /usr/local/opt/mysql
  /usr/local/var/homebrew/linked/mysql
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
==> Successfully started `mysql` (label: homebrew.mxcl.mysql)
```

Can you connect to MySQL?

```sh
$ mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

Can you start mysql manually?

```sh
$ sudo mysql.server start
Starting MySQL
. ERROR! The server quit without updating PID file (/usr/local/var/mysql/….local.pid).
```

Is the directory owned by the mysql user? If not, then we'll fix it.

```
$ ls -lad /usr/local/var/mysql/ 
drwxr-xr-x  41 brew  admin  1312 Oct 23 15:42 /usr/local/var/mysql/
```

Before we fix the directory, we must find any mysql processes that are currently running, then kill them.

```
$ ps -ef | grep [m]ysql
$ kill <pid>
$ kill -9 <pid>
... repeat until there are no more processes
```

Fix the directory so it's owned by the mysql user:

```
$ sudo chown -R mysql /usr/local/var/mysql/
```

Retry:

```sh
$ sudo mysql.server start
Starting MySQL
 SUCCESS!
```

**Comment by MikeMcQuaid** [comment]
> IMHO the root cause is that brew is installing programs (e.g. mysql) in such a way that fails for headless accounts, such as when macOS has a separate user account for brew-related activities, and the account is not using the macOS GUI.

This is not a documented or supported workflow so it is unsurprising that it may not work as expected.

> * This is because I generally want to separate brew-related use from my normal user accounts.

To be explicit to anyone following along: we do not recommend this and, as indicated above, you will likely experience issues from this.
