### ISSUE TITLE
"brew list" results in error

### ISSUE THREAD

**Issue by leafy7382** [Homebrew/brew#6445]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)
List installed packages

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
  
$ brew list
ls -v --verbose /Users/username/homebrew/Cellar
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
Error: Failure while executing; `ls -v --verbose /Users/username/homebrew/Cellar` exited with 1.  
  </pre>
</details>

# What you expected to happen

List installed packages

# Step-by-step reproduction instructions (by running `brew` commands)

run 'brew list'

**Comment by jonchang** [comment]
> ran brew doctor, fixed all issues and can still reproduce the problem?
> ran brew config and brew doctor and included their output with your issue?

Please do these and edit it into the original post.

**Comment by jonchang** [comment]
Please paste the contents of `type ls` and `which -a ls`.

**Comment by GauthamGoli** [comment]
Ah, this is a bug in implementation here https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cli/args.rb#L24
There has to be an extra boolean check on the flags. 

@maxim-belkin  I am afraid just removing them in `cmd/list.rb` won't fix the bug everywhere else.

**Comment by parkr** [comment]
This is working for me now on macOS Mojave.

**Comment by MikeMcQuaid** [comment]
Thanks for reproduction @parkr!
