### ISSUE TITLE
Consider adding Recommended dependencies to gperftools

### ISSUE THREAD

**Issue by jacobcvt12** [Homebrew/brew#645]
I installed gperftools today and came across a few issues. It would be simpler if `binutils` (for `objdump`) and `graphviz` (for `dot`) were added as recommended dependencies. Both are required for visualizing profiles via `pprof`.

**Comment by DomT4** [comment]
Mind filing this over at https://github.com/Homebrew/homebrew-core? That's where core formulae reside. Thanks!

**Comment by jacobcvt12** [comment]
Yep will do! Thanks!
