### ISSUE TITLE
linuxbrew rust based formula fail to install

### ISSUE THREAD

**Issue by sim4life** [Homebrew/brew#6452]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

`$ brew doctor`  
`Your system is ready to brew.`  
`$ brew config`  
```
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: af552669bcd455f59a0719ed45e5f34fe87de756
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/<username>/.cache/Homebrew
HOMEBREW_LOGS: /home/<username>/.cache/Homebrew/Logs
CPU: 16-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.23.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 5.0.0-27-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.3 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.4.0
glibc: N/A
gcc: N/A
xorg: N/A
```

# What you were trying to do (and why)

On my ubuntu linux, I'm trying to install some formula developed in rust like rustup-init, starship etc.

# What happened (include command output)

The commands fail with the same message even though all the required dependencies are met.

<details>
  <summary>Command output</summary>
  <pre>
  
 ==> Downloading https://github.com/starship/starship/archive/v0.16.0.tar.gz
Already downloaded: /home/shah/.cache/Homebrew/downloads/538a80bc57d0754a4d81bf4cd5cfb7b26563cdd5f92da4b354c04d875adc746c--starship-0.16.0.tar.gz
==> cargo install --root /home/linuxbrew/.linuxbrew/Cellar/starship/0.16.0 --path .
Last 15 lines from /home/shah/.cache/Homebrew/Logs/starship/01.cargo:

It looks like you're compiling on Linux and also targeting Linux. Currently this
requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config`
could not be found. If you have OpenSSL installed you can likely fix this by
installing `pkg-config`.

', /home/shah/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.49/build/find_normal.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `starship v0.16.0 (/tmp/starship-20190913-19561-i8vwlc/starship-0.16.0)`, intermediate artifacts can be found at `/tmp/starship-20190913-19561-i8vwlc/starship-0.16.0/target`

Caused by:
  build failed
  
  </pre>
</details>

# What you expected to happen

These formula should be install without any errors after all the required dependencies are met.

# Step-by-step reproduction instructions (by running `brew` commands)

`$ brew install rustup-init`  
OR  
`$ brew install starship`

**Comment by MikeMcQuaid** [comment]
> * [x]  ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
> *

Please report this in linuxbrew-core.
