### ISSUE TITLE
Make Homebrew more flexible with a manifest?

### ISSUE THREAD

**Issue by AdrianTP** [Homebrew/brew#6456]
# A detailed description of the proposed feature

It would be amazing to have Homebrew keep a manifest or something so a user can uninstall and reinstall Homebrew without deleting every app that user used Homebrew to install. Why not just have a db or a file or something that Homebrew can leave behind (with a note during uninstallation notifying the user so they can delete that if they want)? A separate script to handle actual complete removal of all installed apps could also exist for people truly desiring a nuclear option. Then when you reinstall Homebrew, it can read the file and still be in charge of managing all the packages it installed.

# The motivation for the feature

Postgres stopped working. Everything I researched could be summarised as "just reinstall it". So I reinstalled it. It still didn't work. I uninstalled it, wiped all traces of it, rebooted, reinstalled. Still wouldn't run. I did some diagnostics and found that Homebrew was not installing and linking a dependency for postgres. I manually installed it but it said it was already installed. I told brew to link it, and it said that it did, but the dependency still did not show up in /usr/local/opt. I made sure I updated Homebrew, but that didn't help. So I said "screw it" and uninstalled Homebrew, deciding that reinstalling it might help. Nobody told me it would delete *everything* (including Bash 4, which was my default shell, within which I was running the uninstallation process). So basically I ended up nuking my entire development environment in the process of trying to fix a mysterious issue with Postgres suddenly refusing to work properly, despite me not having done anything (to my knowledge) to break it within the past few days since I last used it.

# How the feature would be relevant to at least 90% of Homebrew users

It would be relevant by making Homebrew easier and more secure to use, and more stable. On Mac, for software developers, Homebrew is basically the best and most popular package manager available, with the widest array of apps supported by it. Managing a development environment on Mac without it is a huge pain in the ass unless you only ever work on one application all the time or unless you only use or develop native GUI apps.

# What alternatives to the feature have been considered

RTFM, obviously. I should have read the script rather than just trusting that Homebrew would uninstall only itself, even though that's a perfectly reasonable explanation.

**Comment by AdrianTP** [comment]
As a side note: uninstalling and reinstalling Homebrew did fix the problem I was having with Postgres and its dependencies. Luckily I had exported a list of all my installed apps to a Brewfile. This doesn't fix the fact that now any GUI app I installed with Caskroom in the past are no longer connected to Homebrew, but hey...better a small victory than a total loss.

**Comment by vitorgalvao** [comment]
> I had exported a list of all my installed apps to a Brewfile. This doesn't fix the fact that now any GUI app I installed with Caskroom in the past are no longer connected to Homebrew

Using the Brewfile to `brew cask reinstall --force` all casks should work.

As for the feature request as a whole, it likely doesn’t pass the “relevant to at least 90% of Homebrew users” requirement because I doubt even 50% of users do a full reinstall of Homebrew, but I do agree that if the messaging didn’t explain you’d lose all installed packages, it should.

**Comment by MikeMcQuaid** [comment]
> It would be amazing to have Homebrew keep a manifest or something so a user can uninstall and reinstall Homebrew without deleting every app that user used Homebrew to install.

`brew bundle dump && brew bundle` will do this.

> Using the Brewfile to `brew cask reinstall --force` all casks should work.

Yup.

**Comment by AdrianTP** [comment]
Regarding the dump/bundle approach, that is essentially what I did, as I kept a running Brewfile for my "new environment setup" script, but in the end having to uninstall and reinstall every package was a huge pain and took a long time, when the issue was just that Homebrew was misbehaving. I would argue that as a solution it's incredibly brute-force and very inconvenient -- it seems like a ["do not use a cannon to kill a mosquito"](https://www.quotes.net/quote/1255) situation to uninstall/reinstall Homebrew and have it take all of its managed packages with it. So maybe add an option to the uninstaller to leave the installed packages, and just uninstall Homebrew itself? Your solution `brew bundle dump && brew bundle` seems like it will reinstall all the _packages managed by Homebrew_, whereas what I was trying to do was _reinstall only Homebrew itself_.

As for reinstalling all casks, my understanding of Homebrew's behaviour and command structure is that running `brew cask reinstall --force` will tell Homebrew to reinstall all Casks. My intention is simply to "link" all of the still-installed apps which I installed with `brew cask install` so Homebrew can continue to manage them -- not to completely reinstall each of them from scratch. Uninstalling Homebrew did not remove any of the apps I installed using Cask, so reinstalling them seems unnecessary. Am I misunderstanding?

**Comment by vitorgalvao** [comment]
> my understanding of Homebrew's behaviour and command structure is that running `brew cask reinstall --force` will tell Homebrew to reinstall all Casks.

Correct.

> My intention is simply to "link" all of the still-installed apps which I installed with `brew cask install` so Homebrew can continue to manage them -- not to completely reinstall each of them from scratch.

Yes, I understood what you want, but we don’t support that. My suggestion was the “best *available* solution” option.

> Uninstalling Homebrew did not remove any of the apps I installed using Cask

For a slew of reasons, HB’s method of managing CLI tools doesn’t work for HBC’s managing of apps (we know because we tried). For casks, we try to emulate whatever result you’d get from a manual installation and then leave it alone. See https://github.com/Homebrew/homebrew-cask/issues/13201 for further context.

> so reinstalling them seems unnecessary.

If it’s unnecessary or not that’s for you to decide. But it is the way to relink them. I guess that theoretically you could remake the directory structure under `Caskroom`, but honestly I think you’d be wasting your time. Reinstalling is considerably less effort.

**Comment by MikeMcQuaid** [comment]
> whereas what I was trying to do was _reinstall only Homebrew itself_.

That's possible but you'll need to figure out how to do it yourself because it's not a widely used desire/need. In future you may find `brew update-reset` sorts out your problems.



> Reinstalling is considerably less effort.

Agreed.

**Comment by AdrianTP** [comment]
Ok cool. Thank you both for the clarifications; next time I will RTFS (read the fabulous script) before I run something, even from a maintainer/org I explicitly trust. And if there is a next time where I need to uninstall Homebrew, I will see about removing it manually (or backing up the Cellar and Cask directories) before reinstalling it.

As for the Casks, I'll think about what I want to do, but at the moment, leaving them unlinked seems preferable to reinstalling all of them, not the least because of the possibility of breaking configs during unintended version bumps. Thanks for walking me through the logic there.

I do have one more question on the subject: if this happens again in the future, would simply re-running the install script work, or would there still be the possibility of issues due to old code hanging around? `brew update-reset` ([this?](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/update-reset.sh)) seems to only reset homebrew's and all taps' repositories to their latest origin/master...is that synonymous with updating Homebrew to its latest version? If so, I will definitely try that first, if something like this ever happens again.

Thanks again for your help!

**Comment by MikeMcQuaid** [comment]
> `brew update-reset` ([this?](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/update-reset.sh)) seems to only reset homebrew's and all taps' repositories to their latest origin/master...is that synonymous with updating Homebrew to its latest version?

Yes.



> Thanks again for your help!

You're very welcome!
