### ISSUE TITLE
passenger config being detected as a configure script

### ISSUE THREAD

**Issue by cmckni3** [Homebrew/brew#646]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

```
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
~/.rbenv/shims/passenger-config
```

Actual: `passenger-config` is detected as a config script when running `brew doctor`
Expected: `passenger-config` is a ruby tool for managing instances of the passenger application server.

[My suggestion is to change](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/diagnostic.rb#L644):

```ruby[
scripts += Dir.chdir(p) { Dir["*-config"] }.map { |c| File.join(p, c) }
```

to:

```ruby
scripts += Dir.chdir(p) { Dir["*-config"] }.reject { |c| c.casecmp('passenger-config').zero? }.map { |c| File.join(p, c) }
```

Do you think this is a good idea?

**Comment by dunn** [comment]
I'd prefer Passenger renamed their manager tool, since `<application>-config` is conventionally used for build-time scripts like we're scanning for.

**Comment by cmckni3** [comment]
That was my other thought as well. I don't think they will change the name of it though.

**Comment by dunn** [comment]
Can't hurt to ask! Would you mind opening an issue with them?

**Comment by cmckni3** [comment]
@dunn Done and referenced this issue

**Comment by dunn** [comment]
<3

**Comment by FlowerWrong** [comment]
[install nginx + passenger on mac](https://www.phusionpassenger.com/library/install/nginx/install/oss/osx/)

**Comment by cmckni3** [comment]
@dunn can you lock this conversation so it doesn't receive anymore spam?
