### ISSUE TITLE
Brew should allow users to fully control pip arguments

### ISSUE THREAD

**Issue by ginsburgnm** [Homebrew/brew#6469]
# A detailed description of the proposed feature
Brew does not appear to allow users to control what pip does under the hood;
"Offending" Line:
./Library/Homebrew/language/python.rb:262

# The motivation for the feature
So my main motivation for this is a package I want to provide via Homebrew needs to be installed without --no-deps. The reason for this is currently due to python2 vs python3; which while Python2 will be EOL'd at the end of this year, the fact that I ran into this issue means that it could crop up again(python 4?), or another flag needs to be absent or present.

I need to allow pip to resolve dependencies because in the case for python2 the cryptography library installs enum34, in the case of python3 enum34 is known to break functionality, so it should not be present there. 

This is obviously not an exhaustive list of benefits that could come from allowing the Formula developer to control these arguments.

# How the feature would be relevant to at least 90% of Homebrew users
Allowing flexibility tends to be welcomed by the developer community :)

It would also make it consistently possible to do something like this to install all dependencies necessary
```
    venv = virtualenv_create(libexec)
    venv.pip_install "-rrequirements.txt"
    venv.pip_install_and_link buildpath
```

Instead of having to explicitly do this
```
  resource "dnspython" do
    url "https://files.pythonhosted.org/packages/ec/c5/14bcd63cb6d06092a004793399ec395405edf97c2301dfdc146dfbd5beed/dnspython-1.16.0.zip"
    sha256 "36c5e8e38d4369a08b6780b7f27d790a292b2b08eea01607865bf0936c558e01"
  end
```
for every dependency; The earlier one is a lot easier to maintain, as many projects already have a requirements file. 

# What alternatives to the feature have been considered
It would be possible to just maintain multiple copies of requirements files with different requirement definitions depending on what is processing the installation, but this feels like the wrong answer.

# Pull Request consideration
I started working on a pull request for this, but master appears to currently be broken for handling virtualenv, as it cannot create a virtualenv (Incidentally this was the issue I started looking at as a user reported the No such file or directory error), and then requests that I not report this issue (so I didn't create an issue ;) ). This of course makes testing changes difficult.
Though it is possible I missed something with regards to how to set it up for development purposes.

**Comment by MikeMcQuaid** [comment]
I think we'd need to see a use for this in Homebrew/homebrew-core packages before we'd accept it. You can pass whatever `pip` arguments you like if you choose to run the commands manually with `system` rather than using the DSL (which is simplified/limited by design).

**Comment by ginsburgnm** [comment]
Well, the use case for it, is to keep the requirements in a single location. And to not have to generate a file over 500 lines of code (take a look at ansible's: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ansible.rb 543 lines of this are dependency declarations). anytime your requirements file gets updated. The current way Homebrew's pip venv stuff works, is to encourage these massive, unmanageable files that are completely unnecessary due to them containing redundant information that you are already persisting elsewhere. 

Whereas those 543 lines could be completely eliminated with this change, the entire file could be about 50 or 60 lines. A tenth the size.

Maybe I don't properly understand the use case for the DSL in this instance. Because it seems like when you use it, you are setting yourself up for future failures due to having to have multiple sources of authority of what your dependencies are, one in your repository another in your tap.
