### ISSUE TITLE
brew installs test dependencies by default

### ISSUE THREAD

**Issue by iMichka** [Homebrew/brew#6470]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
brew config
HOMEBREW_VERSION: 2.1.11-90-g605a9c6
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 605a9c6057dc40eef80648db4cd36af6e8c0851c
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 823eecea753a7bd7932b0a3ec81ed27c392c5cc9
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BINTRAY_KEY: set
HOMEBREW_BINTRAY_USER: imichka
HOMEBREW_DEVELOPER: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GITHUB_USER: iMichka
HOMEBREW_NO_AUTO_UPDATE: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_102
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  nss
  podofo

Warning: Some installed formulae are not readable:
  pillow: Unsupported special dependency :python3

  matplotlib: Unsupported special dependency :python3
```

# What you were trying to do (and why)

Install a formula without installing test dependencies on my computer.

# What happened (include command output)

It tried to install `brew-php-switcher`:
> ==> Installing dependencies for brew-php-switcher: apr-util, argon2, aspell, brotli, c-ares, libmetalink, libssh2, jansson, libev, libevent, nghttp2, openldap, rtmpdump, curl-openssl, freetds, python, glib, libpq, libsodium, libzip, tidy-html5 and php

The same happens with other formulae.

# What you expected to happen

It should not install `php`, as the dependency is marked as `:test`.

Note that `brew deps brew-php-switcher` returns nothing.

# Step-by-step reproduction instructions (by running `brew` commands)

> brew install brew-php-switcher

**Comment by scpeters** [comment]
see https://github.com/Homebrew/brew/pull/6471

**Comment by MikeMcQuaid** [comment]
Thanks for quick turnaround @scpeters! The existing behaviour was because we were initially just using `:test` when we also used `:build`.
