### ISSUE TITLE
make cask.pkg lazyloading

### ISSUE THREAD

**Issue by holymonson** [Homebrew/brew#6473]
# A detailed description of the proposed feature

Make stanza `cask.pkg` accept block argument and become lazyloading, like `cask.url`.

# The motivation for the feature

To fix https://github.com/Homebrew/homebrew-cask-versions/issues/7838 .

# How the feature would be relevant to at least 90% of Homebrew users

Reduce unnecessary http requests to third-part url.

**Comment by holymonson** [comment]
# What alternatives to the feature have been considered

no

**Comment by holymonson** [comment]
@reitermarkus Would you please check it out?

**Comment by holymonson** [comment]
@MikeMcQuaid Would you please check this out?

**Comment by MikeMcQuaid** [comment]
@holymonson I'll defer to @reitermarkus but I suspect the best thing is to create a pull request for discussion. Alternatively, create an issue on Homebrew/homebrew-cask.
