### ISSUE TITLE
plan9port disappeared from brew?

### ISSUE THREAD

**Issue by ipstone** [Homebrew/brew#6478]
Hello, I am trying to `brew install plan9port`, which was working a few weeks/days back, but it's no longer available - what happened to the formula?

thanks!

**Comment by vitorgalvao** [comment]
`plan9port` was removed. See https://github.com/Homebrew/homebrew-core/pull/38394 and the linked issues as to why.

In the future, for formula questions you want https://github.com/Homebrew/homebrew-core, not this repo.

**Comment by ipstone** [comment]
Thanks for the info - just as a note for future reference here - that plan9port compiles well on mac os x - which is the route that I end up solving my problem.
