### ISSUE TITLE
[Documentation] Please consider adding a link from the main README towards the linux-subsection, if possible

### ISSUE THREAD

**Issue by rubyFeedback** [Homebrew/brew#6486]
Hello homebrew devs,

Would it be possible to:

a) add a link from the main README to how to work with homebrew on linux?

and

b) improve that aspect, from a tutorial point of view?

I remember some months ago I tried to run homebrew on linux. It worked 
somewhat but not perfect; so I had hoped that after some time it may work
better now. But as I am just looking at the main README, I can not find the
old documentation; I think it may have been noted down elsewhere e. g.
the linux-specific part. Might it be possible to somehow align or link it to
some existing documentation? Could be another file or just a link to the
wiki (I will actually look at the wiki after writing this request, so this may
just be an issue of finding the appropriate links).

Thanks!

**Comment by jonchang** [comment]
The installation instructions for Homebrew on Linux are linked from the [homepage](https://brew.sh/), which should be sufficient.
