### ISSUE TITLE
brew installation - no user interaction 

### ISSUE THREAD

**Issue by henri** [Homebrew/brew#6487]
#5808 - A detailed description of the proposed feature
Interested in the possibly of a wrapper script which you can run as root to install brew without any user interaction. A package install could also be an option? Just investigating this possibility. Maybe you pass in the admin short name details for brew to be connected via the terminal as an argument.

# The motivation for the feature
Ability to setup brew from a management system like JAMF / MUNKI etc

# How the feature would be relevant to at least 90% of Homebrew users
This would allow very fast installation of Homebrew on systems were user interaction for installation is not possible or desired. You just want to install and not sit by the terminal waiting for prompts. You know you want it and just want the install to proceed. You have  installed it before. 

# What alternatives to the feature have been considered
I started modifying the install script and got something working. With some bits being done by root before the install script is run and apple script being called from the command line for the developer tools install. Then I thought, maybe others would find this useful? Why not see what the master Home Brewers think about such an installation option. Maybe one already exists which I did not spot?

Also... I think HomeBrew is just fantastic! Thank you very much for all the efforts!

**Comment by MikeMcQuaid** [comment]
You can run the install script non-interactively by not running on a TTY or use an alternate install method. For example, Strap does this: https://github.com/MikeMcQuaid/strap

We'd consider accepting PRs to the Homebrew/install repo to make this easier/more obvious.
