### ISSUE TITLE
brew update doesn't 'fail' - expected?

### ISSUE THREAD

**Issue by Clpsplug** [Homebrew/brew#65]
### Bug (?) reports:

Running `brew update` without internet connection will yield tons of (as many taps you've done) error messages, but I found a case where `brew update` **itself** didn't fail - by which I mean its return code is somehow **zero**  despite all those errors. Here's my sample output without internet connection.

```zsh
_( _・ω)_<CPlug@localhost H28 04/11 11:14:19) 
> brew update  #no internet connection                                                             [~]
fatal: unable to access 'https://github.com/Homebrew/brew.git/': Could not resolve host: github.com
Error: Fetching /usr/local failed!
fatal: unable to access 'https://github.com/caskroom/homebrew-versions/': Could not resolve host: github.com
Error: Fetching /usr/local/Library/Taps/caskroom/homebrew-versions failed!
fatal: unable to access 'https://github.com/Homebrew/homebrew-boneyard/': Could not resolve host: github.com
Error: Fetching /usr/local/Library/Taps/homebrew/homebrew-boneyard failed!
fatal: unable to access 'https://github.com/Homebrew/homebrew-brewdler/': Could not resolve host: github.com
Error: Fetching /usr/local/Library/Taps/homebrew/homebrew-brewdler failed!
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': Could not resolve host: github.com
Error: Fetching /usr/local/Library/Taps/homebrew/homebrew-core failed!
fatal: unable to access 'https://github.com/Homebrew/homebrew-games/': Could not resolve host: github.com
Error: Fetching /usr/local/Library/Taps/homebrew/homebrew-games failed!
fatal: unable to access 'https://github.com/Homebrew/homebrew-x11/': Could not resolve host: github.com
Error: Fetching /usr/local/Library/Taps/homebrew/homebrew-x11 failed!
fatal: unable to access 'https://github.com/phinze/homebrew-cask/': Could not resolve host: github.com
Error: Fetching /usr/local/Library/Taps/phinze/homebrew-cask failed!
Already up-to-date.
_( _・ω)_<CPlug@localhost H28 04/11 11:14:26) 
>
```

I was writing one of those automation script for `brew update` & `brew upgrade`, and I was designing it so that when `brew update` fails for any reason, it would ask me to retry - but that didn't work because `brew update` wouldn't return nonzero in the first place like above. I can see the return code by looking at the prompt - the `_( _・ω)_` will turn into `・ω)┌┘’,;’;≡三` upon nonzero return.

### Feature Requests:

As this pretty much *always* happen when condition (= no internet connections) is met, this *might* be an expected result - but I want it to (and I think it should) fail when the fetching fails.
I wish I could contribute - but right now I lack in knowledge... sry 😞

**Comment by chdiza** [comment]
I was about to report this, except that what I found weird was that brew still prints "Already up-to-date" even though everything it tried failed.

**Comment by Clpsplug** [comment]
@chdiza Yeah right! I forgot to mention that. Thanks!

**Comment by mikemcquaid** [comment]
Thanks for the report, I'll investigate this.
