### ISSUE TITLE
Producing bottle block gives different results on macOS

### ISSUE THREAD

**Issue by dawidd6** [Homebrew/brew#6506]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I run `brew bottle --merge` on macOS with two bottle JSONs, one for mojave and one for linux.
I mean `brew test-bot` run it and I found the issue in this command.

# What happened (include command output)

I don't have access to macOS machine (besides CI), so I replaced `Homebrew::DEFAULT_PREFIX` on linux to `/usr/local` just for testing and to prove this bug is real. But I also attach links to CI jobs where this bug occurs and where it is not appearing.

Here is where the bug occurs:
https://github.com/dawidd6/homebrew-tap/runs/240053060#step:5:222
Here it does not occur:
https://github.com/dawidd6/homebrew-tap/runs/240054363#step:5:223

See the order of arguments passed to `bottle --merge`. Seems like passing mojave first adds the additional unnecessary `prefix` line.

I was able to reproduce this locally:
<details>
  <summary>Command output</summary>
  <pre>
  ➜  dawidd6/brew master ✗  bin/brew bottle --merge ~/Downloads/keybase-cli--4.4.1.x86_64_linux.bottle.json ~/Downloads/keybase-cli--4.4.1.mojave.bottle.json
/usr/local
==> dawidd6/tap/keybase-cli
  bottle do
    root_url "https://dl.bintray.com/dawidd6/bottles-tap"
    cellar :any_skip_relocation
    rebuild 1
    sha256 "6f90ff414529a6683e0f954991d93280011b7d549ef1c426ecc5102a927fe6bd" => :mojave
    sha256 "4fc93e20f54f13399612b3d2eec0e0404658408cefd4b4c3a361908e6e8eabaf" => :x86_64_linux
  end
➜  dawidd6/brew master ✗  bin/brew bottle --merge ~/Downloads/keybase-cli--4.4.1.mojave.bottle.json ~/Downloads/keybase-cli--4.4.1.x86_64_linux.bottle.json
/usr/local
==> dawidd6/tap/keybase-cli
  bottle do
    root_url "https://dl.bintray.com/dawidd6/bottles-tap"
    prefix "/home/linuxbrew/.linuxbrew"
    cellar :any_skip_relocation
    rebuild 1
    sha256 "6f90ff414529a6683e0f954991d93280011b7d549ef1c426ecc5102a927fe6bd" => :mojave
    sha256 "4fc93e20f54f13399612b3d2eec0e0404658408cefd4b4c3a361908e6e8eabaf" => :x86_64_linux
  end
  </pre>
</details>

# What you expected to happen

A bottle block without `prefix` as it should be.

# Step-by-step reproduction instructions (by running `brew` commands)

See above output. The bug does not happen when running `brew` on linux, only on macOS.

**Comment by dawidd6** [comment]
Patch seems to be fairly simple:
```diff
diff --git a/Library/Homebrew/dev-cmd/bottle.rb b/Library/Homebrew/dev-cmd/bottle.rb
index 6b82aa8c1..6e19d5970 100644
--- a/Library/Homebrew/dev-cmd/bottle.rb
+++ b/Library/Homebrew/dev-cmd/bottle.rb
@@ -16,7 +16,7 @@ BOTTLE_ERB = <<-EOS.freeze
     <% if !root_url.start_with?(HOMEBREW_BOTTLE_DEFAULT_DOMAIN) %>
     root_url "<%= root_url %>"
     <% end %>
-    <% if ![Homebrew::DEFAULT_PREFIX, "/usr/local"].include?(prefix) %>
+    <% if ![Homebrew::DEFAULT_PREFIX, "/usr/local", "/home/linuxbrew/.linuxbrew"].include?(prefix) %>
     prefix "<%= prefix %>"
     <% end %>
     <% if cellar.is_a? Symbol %>
```

**Comment by MikeMcQuaid** [comment]
@dawidd6 Something like that makes sense but would be nice to make those values into constants e.g. `HOMEBREW_DEFAULT_PREFIX` and `LINUXBREW_DEFAULT_PREFIX` or similar based on where they are currently set in `Library/Homebrew/global.rb` and `Library/Homebrew/os/linux/global.rb`.

**Comment by dawidd6** [comment]
Yep, that's a good idea, I thought about that, too. Will see what I can do and submit a PR.

**Comment by dawidd6** [comment]
`Library/Homebrew/os/linux/global.rb` is loaded before `Library/Homebrew/global.rb`. At least on linux. So, I'm going to declare those two constants in `Library/Homebrew/global.rb`, as I don't know if `Library/Homebrew/os/linux/global.rb` is even loaded on macOS.
