### ISSUE TITLE
Homebrew installation problem

### ISSUE THREAD

**Issue by rajeesh1969** [Homebrew/brew#6513]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Homebrew installation for developing website

# What happened (include command output)

Installing Homebrew in windows 10 is giving the messages "sh: line 27: /usr/bin/sudo: No such file or directory" and "ln: failed to create symbolic link '/c/Users/CEK/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/2.3.7': No such file or directory" and failed to install.

<details>
  <summary>Command output</summary>
  <pre>
  
  sh: line 27: /usr/bin/sudo: No such file or directory
  
  </pre>
</details>

# What you expected to happen

Homebrew succesful installation

# Step-by-step reproduction instructions (by running `brew` commands)

sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

**Comment by dawidd6** [comment]
Homebrew does not support windows. If you meant WSL, then install `sudo` with your distro's package manager first.

**Comment by MikeMcQuaid** [comment]
Please do not create duplicate issues and post stuff like this in Discourse instead.
