### ISSUE TITLE
`HOMEBREW_AUTO_UPDATE_SECS` doesn't seem to have any effect

### ISSUE THREAD

**Issue by stouset** [Homebrew/brew#6517]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Setting `HOMEBREW_AUTO_UPDATE_SECS` doesn't appear to have any effect, as best I can tell. I am trying to speed up `brew install` and `brew upgrade` invocations by setting it in my shell environment.

# What happened (include command output)

When installing or upgrading formulae, a `brew update` is performed automatically even if homebrew has been updated more recently than the configured number of seconds.

```sh
$ time env HOMEBREW_AUTO_UPDATE_SECS=86400 brew update
Updated 1 tap (homebrew/cask).
No changes to formulae.
        8.34 real         1.39 user         1.72 sys
$ time env HOMEBREW_AUTO_UPDATE_SECS=86400 brew install xz
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.4.mojave.bottle.tar.
Already downloaded: /Users/stephen/Library/Caches/Homebrew/downloads/f041c42abd74f027d1745193fe8c4d82d7df407e498726e107a3d3a165b6f16a--xz-5.2.4.mojave.bottle.tar.gz
==> Pouring xz-5.2.4.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.4: 92 files, 1MB
        8.79 real         2.22 user         1.92 sys
```

# What you expected to happen

If `HOMEBREW_NO_AUTO_UPDATE` is set, the auto-update is skipped as expected:

```sh
$ time env HOMEBREW_NO_AUTO_UPDATE=true brew install xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.4.mojave.bottle.tar.
Already downloaded: /Users/stephen/Library/Caches/Homebrew/downloads/f041c42abd74f027d1745193fe8c4d82d7df407e498726e107a3d3a165b6f16a--xz-5.2.4.mojave.bottle.tar.gz
==> Pouring xz-5.2.4.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.4: 92 files, 1MB
        2.52 real         1.76 user         1.02 sys
```

I would expect equivalent behavior from `brew` when `HOMEBREW_AUTO_UPDATE_SECS` set, after a fresh `brew update`:

```sh
$ time env HOMEBREW_AUTO_UPDATE_SECS=86400 brew update
Updated 1 tap (homebrew/cask).
No changes to formulae.
        8.34 real         1.39 user         1.72 sys
$ time env HOMEBREW_AUTO_UPDATE_SECS=86400 brew install xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.4.mojave.bottle.tar.
Already downloaded: /Users/stephen/Library/Caches/Homebrew/downloads/f041c42abd74f027d1745193fe8c4d82d7df407e498726e107a3d3a165b6f16a--xz-5.2.4.mojave.bottle.tar.gz
==> Pouring xz-5.2.4.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.4: 92 files, 1MB
        2.52 real         1.76 user         1.02 sys
```

# Step-by-step reproduction instructions (by running `brew` commands)

The `brew` commands above should suffice.

# `brew config` && `brew doctor`

<details>
  <summary>`brew config` and `brew doctor` output</summary>
  <pre>
$ brew config
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 6 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 54e9311c86e88194b4f5a90fbfe2c0e590664e20
Core tap last commit: 77 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 86400
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.0
$ brew doctor
Your system is ready to brew.
</pre>
</details>

**Comment by stouset** [comment]
Everything for this ticket should be in order.

**Comment by MikeMcQuaid** [comment]
The `HOMEBREW_AUTO_UPDATE_SECS` works by setting the modification time for each Git repository when it is checked and if it has been checked recently avoid checking the GitHub API or running `git fetch` for that repository but still e.g. checks out the right branches etc. The `Updating Homebrew...` messaging is printed if any part of the update process (including e.g. checking the modification times) takes more than ~3 seconds.

I'm closing this for now because this is working as implemented so is more of a feature request than a bug but I'd love thoughts from @stouset and @Homebrew/maintainers about whether this logic should be simpler (e.g. `HOMEBREW_AUTO_UPDATE_SECS` sets a single, global timestamp and skips running any update/branch checkout at all if it's recent enough).

**Comment by stouset** [comment]
Honestly, that behavior seems surprising to me. I would expect that the purpose of the `HOMEBREW_AUTOUPDATE_SECS` flag would be to dramatically speed up `brew install` and `brew upgrade` in the event that you know you've done a `brew update` recently.

It sounds like that's not what it does, but it's unclear to me if its current behavior is actually adding much value. Consider:

```sh
$ time brew install xz
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.4.mojave.bottle.tar.
Already downloaded: /Users/stephen/Library/Caches/Homebrew/downloads/f041c42abd74f027d1745193fe8c4d82d7df407e498726e107a3d3a165b6f16a--xz-5.2.4.mojave.bottle.tar.gz
==> Pouring xz-5.2.4.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.4: 92 files, 1MB
        9.88 real         2.26 user         1.93 sys

$ brew uninstall xz
Uninstalling /usr/local/Cellar/xz/5.2.4... (92 files, 1MB)

$ time env HOMEBREW_AUTO_UPDATE_SECS=86400 brew install xz
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.4.mojave.bottle.tar.gz
Already downloaded: /Users/stephen/Library/Caches/Homebrew/downloads/f041c42abd74f027d1745193fe8c4d82d7df407e498726e107a3d3a165b6f16a--xz-5.2.4.mojave.bottle.tar.gz
==> Pouring xz-5.2.4.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.4: 92 files, 1MB
        7.85 real         2.49 user         2.03 sys
```

That's a 20% difference, but it's still nowhere near as performant as

```sh
time env HOMEBREW_NO_AUTO_UPDATE=true brew install xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.4.mojave.bottle.tar.gz
Already downloaded: /Users/stephen/Library/Caches/Homebrew/downloads/f041c42abd74f027d1745193fe8c4d82d7df407e498726e107a3d3a165b6f16a--xz-5.2.4.mojave.bottle.tar.gz
==> Pouring xz-5.2.4.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.4: 92 files, 1MB
        2.64 real         1.87 user         1.10 sys
```

Why shouldn't there be an environment setting that prevents any sort of update logic from happening if a `brew update` is recent-enough?

**Comment by MikeMcQuaid** [comment]
> Honestly, that behavior seems surprising to me. I would expect that the purpose of the `HOMEBREW_AUTOUPDATE_SECS` flag would be to dramatically speed up `brew install` and `brew upgrade` in the event that you know you've done a `brew update` recently.

@stouset You have convinced me that this needs to change. As a result I've opened https://github.com/Homebrew/brew/pull/6532 to change the functionality to (I think) what you'd expect. Let me know what you think and thanks again!

**Comment by stouset** [comment]
Awesome, thank you!
