### ISSUE TITLE
brew update always triggers boneyard error, etc.

### ISSUE THREAD

**Issue by Hultner** [Homebrew/brew#6522]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Update/upgrade home-brew to fetch newer versions of packages.

# What happened (include command output)
Every time I run `brew update` I get a bunch of errors of unknown reasons (not sure if they are related), fit a couple about github username (github works fine with git-ssh over cli), then coupled with equal amount of `homebrew/homebrew-x does not exist!`, I'm not sure if these errors are trigged due to the github error or if the repositories actually doesn't exist (and if they done then why are they there in the first place?).  This have been bugging me for a while, but I haven't noticed any further damage.

<details>
  <summary>Command output</summary>
  <pre>

```sh
$ > brew update
fatal: could not read Username for 'https://github.com': terminal prompts disabled
fatal: could not read Username for 'https://github.com': terminal prompts disabled
fatal: could not read Username for 'https://github.com': terminal prompts disabled
fatal: could not read Username for 'https://github.com': terminal prompts disabled
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: homebrew/homebrew-boneyard does not exist! Run 'brew untap homebrew/homebrew-boneyard'
homebrew/homebrew-binary does not exist! Run 'brew untap homebrew/homebrew-binary'
homebrew/homebrew-dupes does not exist! Run 'brew untap homebrew/homebrew-dupes'
homebrew/homebrew-fuse does not exist! Run 'brew untap homebrew/homebrew-fuse'
homebrew/homebrew-x11 does not exist! Run 'brew untap homebrew/homebrew-x11'
```
  </pre>
</details>

# What you expected to happen

Brew to update repositories without any errors.

# Step-by-step reproduction instructions (by running `brew` commands)

Run `brew update`

**Comment by MikeMcQuaid** [comment]
> ```shell
> homebrew/homebrew-boneyard does not exist! Run 'brew untap homebrew/homebrew-boneyard'
> homebrew/homebrew-binary does not exist! Run 'brew untap homebrew/homebrew-binary'
> homebrew/homebrew-dupes does not exist! Run 'brew untap homebrew/homebrew-dupes'
> homebrew/homebrew-fuse does not exist! Run 'brew untap homebrew/homebrew-fuse'
> homebrew/homebrew-x11 does not exist! Run 'brew untap homebrew/homebrew-x11'
> ```

The message literally tells you what to run to fix this.
