### ISSUE TITLE
show size of downloaded files

### ISSUE THREAD

**Issue by rdp** [Homebrew/brew#6524]
Today when downloading "very large" bottles it can take awhile:

```
==> Downloading https://homebrew.bintray.com/bottles/llvm@8-8.0.1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/de/de26cfd906d55496acf1eb4927dca3d003e89a771c954495da1f905cf387b17d?__gd
##################################################################        92.0%
```
Especially on slow connections.  It would be nice if it showed more than just percentage.  Things that come to mind: total size, or possibly even "expected time remaining" in the download.

# The motivation for the feature

It's confusing for me not being able to estimate how much longer a download is going to take.  I want to know if it's going to take seconds or minutes or what not.  Or know how much size is left to be able to estimate the same based on the percent already downloaded.

# How the feature would be relevant to at least 90% of Homebrew users

Many Homebrew users will run into a larger bottle every so often, would be nice to have some more info to the user as it downloads.

# What alternatives to the feature have been considered

Already mentioned above.  Thanks!

**Comment by MikeMcQuaid** [comment]
> Especially on slow connections. It would be nice if it showed more than just percentage. Things that come to mind: total size, or possibly even "expected time remaining" in the download.

This output is from `curl` and not Homebrew so we cannot change this, sorry.

**Comment by EricFromCanada** [comment]
If you pass `-v` or set `HOMEBREW_VERBOSE=1`, `curl` will use its standard progress meter that displays total download size.

**Comment by rdp** [comment]
It's too bad curl's output isn't customizable.  I guess workarounds would be to get the size from "the recipe" (maybe just for very large files?) or possibly do a HEAD first to determine it, where possible.  Both a bit painful... :)
