### ISSUE TITLE
Non fatal error/warning on brewbot for git cleanup on php tap

### ISSUE THREAD

**Issue by javian** [Homebrew/brew#653]
### Bug reports:

An error is raised by git on the brew bot on the php tap. It doesn't break builds but is probably something that should be addressed.

Snippet from https://bot.brew.sh/job/Homebrew%20PHP%20Pull%20Requests/2062/version=el_capitan/console

```
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-versions'...
Tapped 212 formulae (238 files, 2.9M)
+ brew update
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the file is removed.

error: prune died of signal 15
error: failed to run prune

Already up-to-date.
```

**Comment by ilovezfs** [comment]
@javian The error was too many unreachable objects in the homebrew/core tap. Removing that file and manually running git prune fixed it.
