### ISSUE TITLE
bundle dump fails when ZDOTDIR defined

### ISSUE THREAD

**Issue by davidosomething** [Homebrew/brew#6533]
```
 I  (master)% b bundle dump --force
Error: No such file or directory @ rb_sysopen - /Users/davidosomething/.zshrc

 I  (master)% touch ~/.zshrc

 I  (master)% b bundle dump --force

(success)
```

When `$ZDOTDIR` is defined in `.zshenv`, allowing user to place `.zshrc` in a different directory from `.zshenv`, `brew bundle dump` fails. The ruby syscall always tries to open `.zshrc` from `$HOME`. Creating a temporary `.zshrc` in `$HOME` is a workaround.

**Comment by MikeMcQuaid** [comment]
You'll need to address this yourself, we don't do anything with `zsh`.

**Comment by davidosomething** [comment]
Homebrew/brew does do stuff with shells -- it's that the RC file path is hardcoded here:

```ruby
https://github.com/Homebrew/brew/blob/9a6d7dd2fa52265ed6bfdaa8809f26fea1301336/Library/Homebrew/utils/shell.rb#L75
```

Ideally it should defer to zsh's settings, which is `$ZDOTDIR/.zshrc`
http://zsh.sourceforge.net/Intro/intro_3.html

The issue arises when referencing the `shell_profile` util, e.g. when using a tapped formula like this
https://github.com/Schniz/homebrew-tap/blob/master/Formula/fnm.rb#L21
`shell_profile` is wrong because it does not support zsh environment variables.

**Comment by MikeMcQuaid** [comment]
Ok. We'll review a PR to add that functionality.

**Comment by davidosomething** [comment]
@MikeMcQuaid I gave it a shot, but not sure what's going on with the gh actions
