### ISSUE TITLE
Support and test with Ruby 2.6.3 for macOS Catalina

### ISSUE THREAD

**Issue by nickmccurdy** [Homebrew/brew#6551]
# A detailed description of the proposed feature

Homebrew currently supports Ruby 2.3.7 which comes with older versions of macOS, but it should also support Ruby 2.6.3 since it is the system Ruby version on macOS Catalina. This would involve fixing the warning and preferably adjusting the Ruby version used in CI.

# The motivation for the feature

`brew doctor` reports:
```
Warning: Ruby version 2.6.3 is unsupported on 10.15. Homebrew
is developed and tested on Ruby 2.3.7, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
```

# How the feature would be relevant to at least 90% of Homebrew users

macOS and iOS tend to have very high upgrade percentages, just days to weeks after they are released. This issue will soon affect the majority of Homebrew users that have upgraded to Catalina now that it is stable.

# What alternatives to the feature have been considered

Supporting multiple Ruby versions, though this probably isn't worth the effort as the system Ruby version is deprecated and unlikely to change until it's removed.

**Comment by ricknox** [comment]
Currently there is a PR at #6556 that solves the `brew doctor` warning.

**Comment by iamtonyarthur** [comment]
> When the fix is ready and merged will we be using `brew upgrade` and should be set straight?

Fixed was released earlier today. Run `brew update`. It should do the magic. Also run `brew doctor` to validate all is good. It worked for me on macOS Catalina. Thanks to @MikeMcQuaid for the Catalina fix.

**Comment by tr1s** [comment]
@iamtonyarthur yup can confirm it's all good now. Thx @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
This issue is not done completely until https://github.com/Homebrew/brew/pull/6556 is merged.

**Comment by frederikkunze** [comment]
Not working for me can't do brew update it is stuck for ever
