### ISSUE TITLE
brew doctor reports macOS 10.15 is a pre-release version

### ISSUE THREAD

**Issue by mikemadden42** [Homebrew/brew#6557]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

After upgrading to macOS 10.15, I ran brew doctor to check for issues.

A few warnings were output.  When will macOS 10.15 be fully supported?

# What happened (include command output)

```bash
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 10.15.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.
```

```bash
$ brew config
zsh: correct 'config' to '.config' [nyae]? n
HOMEBREW_VERSION: 2.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7e0eaae2bd6600500c961ac342b5d817b25b571
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a035f9f7cbc4de3353b703a250280d5e2e78b064
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: N/A
CLT headers: 11.0.0.0.1.1567737322
```

# What you expected to happen

Since macOS 10.15 was released yesterday, I would expect there to be no warning about using a pre-release version of macOS.

# Step-by-step reproduction instructions (by running `brew` commands)

```bash
$ brew update -v
$ brew doctor
$ brew config
```

**Comment by DaveKT** [comment]
Quick note... this message is also showing up with 'brew update'. 10.15 is no longer pre-release.

DTassara@Gauss ~ % brew upgrade
Warning: You are **using macOS 10.15**.
We do not provide support for **this pre-release version.**
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

**Comment by MikeMcQuaid** [comment]
This is fixed in `master`. It will no longer be printed when we make a new stable release. Please be patient, it has been less than 24 hours.

**Comment by DaveKT** [comment]
No worries. Just reporting information. Totally get that this release will trail 10.15. 

Cheers.
