### ISSUE TITLE
update to mac os catalina 'brew' report error 'in `require': cannot load such file -- plist (LoadError)'

### ISSUE THREAD

**Issue by hantmac** [Homebrew/brew#6565]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

My vim did not work and report error 
```
dyld: Library not loaded: /usr/local/opt/perl/lib/perl5/5.26.2/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /usr/local/bin/vim
  Reason: image not found
Abort trap: 6
```
Then I try to fix it and run `brew uninstall --ignore-dependencies perl`, but I have an error:
```
Traceback (most recent call last):
        7: from /usr/local/Homebrew/Library/Homebrew/brew.rb:15:in `<main>'
        6: from /usr/local/Homebrew/Library/Homebrew/brew.rb:15:in `require_relative'
        5: from /usr/local/Homebrew/Library/Homebrew/global.rb:14:in `<top (required)>'
        4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        2: from /usr/local/Homebrew/Library/Homebrew/system_command.rb:3:in `<top (required)>'
        1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- plist (LoadError)
```
# What happened (include command output)
I just run `brew` and the commond output is ：

<details>
  <summary>Command output</summary>
  <pre>
  
Traceback (most recent call last):
        7: from /usr/local/Homebrew/Library/Homebrew/brew.rb:15:in `<main>'
        6: from /usr/local/Homebrew/Library/Homebrew/brew.rb:15:in `require_relative'
        5: from /usr/local/Homebrew/Library/Homebrew/global.rb:14:in `<top (required)>'
        4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        2: from /usr/local/Homebrew/Library/Homebrew/system_command.rb:3:in `<top (required)>'
        1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- plist (LoadError)

  
  </pre>
</details>

# What you expected to happen

 I expect the command `brew` run successfully.

# Step-by-step reproduction instructions (by running `brew` commands)
1. Run the command `brew` on mac os catalina

**Comment by MikeMcQuaid** [comment]
@hantmac I closed https://github.com/Homebrew/brew/issues/6564 without comment because you did not read or fill in the issue template (you have not provided any `brew doctor` or `brew config` output and you've submitted this to the wrong repository). Please stop creating duplicate issues.

**Comment by hantmac** [comment]
Sorry, I will read the document carefully.

**Comment by bjackson** [comment]
I get the same issue. Running `brew config` and `brew doctor` produces the same error.

**Comment by MikeMcQuaid** [comment]
@bjackson Run `brew update-reset`.
