### ISSUE TITLE
A newer Command Line Tools is available despite no update available - macOS Catalina

### ISSUE THREAD

**Issue by ruchern** [Homebrew/brew#6576]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Running `brew doctor` after upgrading to macOS Catalina (10.15) to check if anything is required to take action.

# What happened (include command output)

Ran the command `brew doctor`

<details>
  <summary>Command output</summary>
  <pre>Warning: A newer Command Line Tools release is available. Update them from Software Update in System Preferences.</pre>
</details>

# What you expected to happen

There should be no command output since there is no newer command line tools release available.

# Step-by-step reproduction instructions (by running `brew` commands)

1. Run `brew doctor` on macOS Catalina (10.15)
2. Command output as above

**Comment by MikeMcQuaid** [comment]
> * [ ]  ran `brew config` and `brew doctor` and included their output with your issue?

Closing as you didn't do this.

**Comment by ruchern** [comment]
Closing after fixing partially with https://github.com/Homebrew/brew/issues/5561#issuecomment-537616161

**Comment by ruchern** [comment]
Closing after fixing with https://github.com/Homebrew/brew/issues/5561#issuecomment-537616161
