### ISSUE TITLE
brew update doesn't ask for SSH key passphrase for private taps

### ISSUE THREAD

**Issue by satorg** [Homebrew/brew#6583]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

  <details>
    <summary>brew doctor</summary>
    <pre>
    Your system is ready to brew.
    </pre>
  </details>
  <details>
    <summary>brew config</summary>
    <pre>
  HOMEBREW_VERSION: 2.1.13
  ORIGIN: https://github.com/Homebrew/brew
  HEAD: aa043c1d678afd26f50156a83417c296cb9d5a4b
  Last commit: 3 days ago
  Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
  Core tap HEAD: 49ec13c7327ba8e0b9e8cff65102c142ae6f32ad
  Core tap last commit: 88 minutes ago
  HOMEBREW_PREFIX: /usr/local
  CPU: dodeca-core 64-bit kabylake
  Homebrew Ruby: 2.3.7 => 
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
  Clang: 10.0 build 1001
  Git: 2.23.0 => /usr/local/bin/git
  Curl: 7.54.0 => /usr/bin/curl
  Java: 11.0.2, 1.8.0_222
  macOS: 10.14.6-x86_64
  CLT: 10.3.0.0.1.1562985497
  Xcode: N/A
  CLT headers: 10.3.0.0.1.1562985497    </pre>
  </details>

# What you were trying to do (and why)

We have a private git repo with some internal formulaes (intended to be installed with **homebrew**).
I want to `brew tap` this repo, install some tools from that repo and be able to keep them updated.

# What happened (include command output)

I have an SSH key with a passphrase which I use to access our private git repo.
When I tap the repo, brew asks me for the passphrase, which is expected:

<details>
  <summary>brew tap privaterepo/tools git@github.<some-company-name>.com:privaterepo/homebrew-tools.git</summary>
  <pre>
==> Tapping privaterepo/tools
Cloning into '/usr/local/Homebrew/Library/Taps/privaterepo/homebrew-tools'...
Enter passphrase for key '/Users/satorg/.ssh/id_rsa':
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Receiving objects: 100% (7/7), done.
Tapped 4 formulae (30 files, 29.8KB).
  </pre>
</details>

So, the repo is successfully tapped and I'm able to install the tools I need from there.
But now, if I try to run `brew update`, it fails on the private repo with the "Permission denied" error:

<details>
  <summary>brew update</summary>
  <pre>
git@github.<some-company-name>.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/privaterepo/homebrew-tools failed!
  </pre>
</details>

So, it seems is not possible to update from private repos if your SSH key has a passphrase, because `brew update` doesn't ask for it.

# What you expected to happen

I would expect, that `brew update` should ask for passphrase for those tapped repositories which require my own SSH key, in the same way as `brew tap` does.

# Step-by-step reproduction instructions (by running `brew` commands)

1. Have a private **homebrew** repository which is restricted for specific users only.
2. Have an SSH key protected by a passphrase which is required to access the aforementioned private repo.
3. Tap this repository with `brew tap`, enter your passphrase as requested.
4. Try to update **homebrew(( with `brew update`.
5. `brew update` fails to update the private repo, because it doesn't ask for the passphrase.

**Comment by MikeMcQuaid** [comment]
> I would expect, that `brew update` should ask for passphrase for those tapped repositories which require my own SSH key, in the same way as `brew tap` does.

We'll consider accepting a pull request for this but it's not something we're planning on working on or using ourselves.

**Comment by pjestin** [comment]
It seems there is a reason behind this:
https://github.com/Homebrew/brew/commit/9d6a1a693e7ce164869c082059e488c6c9596320
> We execute too many `git fetch` at once for this to be useful. Just let
them fail instead and make it up to users to setup username/password
caching or SSH agents.
