### ISSUE TITLE
brew cleanup error after brew upgrade of outdated packages

### ISSUE THREAD

**Issue by matthewrees** [Homebrew/brew#6586]
- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

First a `brew update` then a `brew upgrade $(brew outdated)` which then ran a `brew cleanup` since it hadn't been run in 30 days. The error happened while the cleanup was running. There was quite a pause between lines 1 and 2 of the error section of the gist below.

# What happened (include command output)

https://gist.github.com/matthewrees/2de498425e750cbf0642e0aecb01c35e

# What you expected to happen

The `upgrade` completed successfully but the `cleanup` should have too.

# Step-by-step reproduction instructions (by running `brew` commands)

I have since run `upgrade` and `cleanup` again but both produce no output so I am unable to reproduce it. For what it's worth I haven't experienced this before.

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/pull/6591

**Comment by matthewrees** [comment]
@MikeMcQuaid got a similar error today when doing another `brew upgrade $(brew outdated)`, gist available here: https://gist.github.com/matthewrees/060e25ff881053a4ef64759eadfa2ece

**Comment by MikeMcQuaid** [comment]
@matthewrees Can I see your `brew config`?

**Comment by matthewrees** [comment]
```
HOMEBREW_VERSION: 2.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2bf8015bc44878d432fb9da4f11e1d8abcef8f32
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 80c190fa2d7b283c857a0e1bfb70a03a9ca11587
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.1
CLT headers: 10.3.0.0.1.1562985497
```

**Comment by MikeMcQuaid** [comment]
CC @amyspark for thoughts/help.

**Comment by sashkab** [comment]
I'm still seeing this happening. Just in case:


```sh
$ brew config
HOMEBREW_VERSION: 2.1.15-109-g5f3302b
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5f3302b3f7b85a308289cc62a9cd7a00ffe527d4
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 40d7edfb0548493ddf9871fbd879095d36167978
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```


```
$ brew doctor
Your system is ready to brew.
```

**Comment by dbvisel** [comment]
Seeing this on 10.14.6!

**Comment by stevenjoezhang** [comment]
I see the same output when upgrading `harfbuzz` formula using `brew`.

```
% brew config
HOMEBREW_VERSION: 2.1.15-109-g5f3302b
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5f3302b3f7b85a308289cc62a9cd7a00ffe527d4
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: 9fc6eaac4c4cc7e3d76c30ee8cfe098fd8fc4177
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.1-x86_64
CLT: 1100.0.33.8
Xcode: 11.2
XQuartz: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
Tracked in https://github.com/Homebrew/brew/issues/6671.
