### ISSUE TITLE
Xcode is updated but continues to give warning about updating

### ISSUE THREAD

**Issue by dreonwo** [Homebrew/brew#6587]
Please update to Xcode 11.1 (or delete it).
Xcode can be updated from the App Store.

Warning: Your Xcode (dunno) is outdated.
Please update to Xcode 11.1 (or delete it).
Xcode can be updated from the App Store.

HOMEBREW_VERSION: 2.1.13-45-g70f232a
Xcode: dunno => /Users/*******/Desktop/Xcode-beta.app/Contents/Developer

**Comment by dreonwo** [comment]
@MikeMcQuaid Why did you close the issue?

**Comment by jonchang** [comment]
> Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md
