### ISSUE TITLE
Error: stack level too deep Please report this bug:

### ISSUE THREAD

**Issue by MikeStL87** [Homebrew/brew#6588]
[ no ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh

[no ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

 [yes-ish ] ran `brew update` and can still reproduce the problem?

 [ n/a] ran `brew doctor`, fixed all issues and can still reproduce the problem?

 [n/a ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I wanted to know if brew had/could install pandoc. I ran brew info pandoc. then its been a day since I ran update and upgrade, so I wanted to do that before I installed pandoc. brew update executed fine. brew upgrade threw an error asking me to report this. I goggled to find a possible sol'n which was to run brew update-reset, which I ran. I then ran update and upgrade again and both executed with no error. I then installed pandoc w/o error. I am reporting this because the system asked me to. I do not need any assistance. if you need anything further from me please let me know. I am on MacBook Pro 10.14.6. 
Thank you for all you do to keep this program awesome! 
-Mike

[Terminal-Saved-Output.txt](https://github.com/Homebrew/brew/files/3720187/Terminal-Saved-Output.txt)

**Comment by MikeMcQuaid** [comment]
Glad you got it sorted.
