### ISSUE TITLE
macOS 10.15 (19A602) breaks Homebrew CLT recognition

### ISSUE THREAD

**Issue by ruychi** [Homebrew/brew#6614]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Routine brew update/upgrade after installing latest macOS 10.15 (19A602) fix.

# What happened (include command output)

brew doctor warns of missing Command-Line-tools, although CLT (latest) are installed.

<details>
  <summary>Command output</summary>
  <pre>
  
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install

$ xcode-select -v
xcode-select version 2370.

$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

$ brew config
HOMEBREW_VERSION: 2.1.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: f1702e51392fd4afcae2b8c521511e43479a1156
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: db608065cdbc75bf848c3a0b4f131e3a104a9bf5
Core tap last commit: 41 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: N/A
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13, 12.0.2, 12.0.1, 12, 11.0.2, 11.0.1, 11, 1.8.0_222
macOS: 10.15-x86_64
CLT: N/A
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
  
  </pre>
</details>

# What you expected to happen

To have Homebrew recognise that latest CLT were installed and available. 

# Step-by-step reproduction instructions (by running `brew` commands)

$ brew upgrade
$ brew doctor
$ xcode-select --install
$ brew config

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/Homebrew/brew/releases/tag/2.1.15, please `brew update`.
