### ISSUE TITLE
how can i stipulate a formula depends on a cask?

### ISSUE THREAD

**Issue by tjt263** [Homebrew/brew#6616]
i'm not a ruby coder.

how can i stipulate a formula depends on a cask? 
specifically java8 (`adoptopenjdk8`)

can i use something like:
`its(:cask) { is_expected.to eq("homebrew/cask-versions/adoptopenjdk8") }`?

it's a line i found in `/usr/local/Homebrew/Library/Homebrew/test/java_requirement_spec.rb`.

thanks.

- - - 
ps: i would just create a new cask, which can `depends_on cask: 'dependency_name'`, but the package in question is not a binary or .dmg, so a formula is most suitable.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Please ask this in Discourse, thanks.
