### ISSUE TITLE
Issue in Homebrew installation

### ISSUE THREAD

**Issue by rajeesh1969** [Homebrew/brew#6630]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Trying to install homebrew through CLI

# What happened (include command output)

Not installed and producing the output "curl: (23) Failed writing body (0 != 6842)"

<details>
  <summary>Command output</summary>
  <pre>
  
  curl: (23) Failed writing body (0 != 6842)
  
  </pre>
</details>

# What you expected to happen

Homebrew installation

# Step-by-step reproduction instructions (by running `brew` commands)

C:\usr\local>curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C Homebrew
t a r%:  TEortraolr   o p e%n iRnegc eairvcehdi v%e :X fFearidl e dA vteor aogpee nS p'e\e\d. \ t aTpiem0e'
   Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   128    0   128    0     0    128      0 --:--:-- --:--:-- --:--:--   149
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (23) Failed writing body (0 != 6842)

**Comment by MikeMcQuaid** [comment]
This is an issue with your machine you'll need to fix yourself.
