### ISSUE TITLE
brew traceback on almost all commands

### ISSUE THREAD

**Issue by q-b** [Homebrew/brew#6631]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Using homebrew after the Catalina upgrade ( macOS 10.15 (19A602) )

# What happened (include command output)

The `brew` command traceback, including `brew doctor` and `brew config`, so I won't be able to paste their output here.

<details>
  <summary>Command output</summary>
  <pre>
  
  Traceback (most recent call last):
	3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
	2: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	1: from /usr/local/Homebrew/Library/Homebrew/global.rb:12:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/global.rb:12:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
  
  </pre>
</details>

Strangely, `brew update` works most of the time, but happens to traceback too.

# What you expected to happen

Normal usage.

# Step-by-step reproduction instructions (by running `brew` commands)

Run any one of those commands:
```
brew doctor
brew search vim
brew upgrade
...
```

**Comment by q-b** [comment]
It looks like I'm up-to-date:
```
/usr/local/Homebrew master*
❯ git log -n 1 HEAD
commit cddf402365e83608f5dbd1bec44d7b544936a370 (HEAD -> master, origin/master)
Merge: 368b80aa8 20e85acec
Author: Mike McQuaid <mike@mikemcquaid.com>
Date:   Tue Oct 22 09:15:51 2019 +0100

    Merge pull request #6620 from scpeters/must_exist_frameworks

    os/mac/keg: Frameworks -> MUST_EXIST_DIRECTORIES
```

**Comment by jonchang** [comment]
Can you try running `brew update-reset`?

**Comment by MikeMcQuaid** [comment]
> * If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh

This is not an issue everyone is experiencing so closing with assumption `brew update-reset` will fix things. Please take future similar issues to Discourse.

**Comment by q-b** [comment]
Thank you guys, I wasn't aware of the `brew update-reset` command but it fixed my issue.
I'll remember to try discourse first next time, sorry for wasting your time!

**Comment by MikeMcQuaid** [comment]
No worries @q-b, glad you got it sorted!

**Comment by mgol** [comment]
I've just hit the same issue after I upgraded Xcode on macOS Catalina 10.15.1 from 11.1 to 11.2. Running `brew update-reset` fixed the issue.

Just posting to state this is not an isolated incident and more people may be affected.

**Comment by bmario** [comment]
I also run into this issue once I executed `brew cleanup` some time after the upgrade from 10.14 to 10.15. `brew update-reset` fixed the problem for me as well.

**Comment by hernimen** [comment]
I'm just hit this issue! Macosx Catalina 10.15 . Can't install homebrew :( 
`==> Downloading and installing Homebrew...
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 129957 (delta 35), reused 47 (delta 29), pack-reused 129878
Receiving objects: 100% (129957/129957), 31.08 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (95356/95356), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3
 * [new tag]         0.4        -> 0.4
 * [new tag]         0.5        -> 0.5
 * [new tag]         0.6        -> 0.6
 * [new tag]         0.7        -> 0.7
 * [new tag]         0.7.1      -> 0.7.1
 * [new tag]         0.8        -> 0.8
 * [new tag]         0.8.1      -> 0.8.1
 * [new tag]         0.9        -> 0.9
 * [new tag]         0.9.1      -> 0.9.1
 * [new tag]         0.9.2      -> 0.9.2
 * [new tag]         0.9.3      -> 0.9.3
 * [new tag]         0.9.4      -> 0.9.4
 * [new tag]         0.9.5      -> 0.9.5
 * [new tag]         0.9.8      -> 0.9.8
 * [new tag]         0.9.9      -> 0.9.9
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.0.1      -> 1.0.1
 * [new tag]         1.0.2      -> 1.0.2
 * [new tag]         1.0.3      -> 1.0.3
 * [new tag]         1.0.4      -> 1.0.4
 * [new tag]         1.0.5      -> 1.0.5
 * [new tag]         1.0.6      -> 1.0.6
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.10     -> 1.1.10
 * [new tag]         1.1.11     -> 1.1.11
 * [new tag]         1.1.12     -> 1.1.12
 * [new tag]         1.1.13     -> 1.1.13
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.1.4      -> 1.1.4
 * [new tag]         1.1.5      -> 1.1.5
 * [new tag]         1.1.6      -> 1.1.6
 * [new tag]         1.1.7      -> 1.1.7
 * [new tag]         1.1.8      -> 1.1.8
 * [new tag]         1.1.9      -> 1.1.9
 * [new tag]         1.2.0      -> 1.2.0
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.2.3      -> 1.2.3
 * [new tag]         1.2.4      -> 1.2.4
 * [new tag]         1.2.5      -> 1.2.5
 * [new tag]         1.2.6      -> 1.2.6
 * [new tag]         1.3.0      -> 1.3.0
 * [new tag]         1.3.1      -> 1.3.1
 * [new tag]         1.3.2      -> 1.3.2
 * [new tag]         1.3.3      -> 1.3.3
 * [new tag]         1.3.4      -> 1.3.4
 * [new tag]         1.3.5      -> 1.3.5
 * [new tag]         1.3.6      -> 1.3.6
 * [new tag]         1.3.7      -> 1.3.7
 * [new tag]         1.3.8      -> 1.3.8
 * [new tag]         1.3.9      -> 1.3.9
 * [new tag]         1.4.0      -> 1.4.0
 * [new tag]         1.4.1      -> 1.4.1
 * [new tag]         1.4.2      -> 1.4.2
 * [new tag]         1.4.3      -> 1.4.3
 * [new tag]         1.5.0      -> 1.5.0
 * [new tag]         1.5.1      -> 1.5.1
 * [new tag]         1.5.10     -> 1.5.10
 * [new tag]         1.5.11     -> 1.5.11
 * [new tag]         1.5.12     -> 1.5.12
 * [new tag]         1.5.13     -> 1.5.13
 * [new tag]         1.5.14     -> 1.5.14
 * [new tag]         1.5.2      -> 1.5.2
 * [new tag]         1.5.3      -> 1.5.3
 * [new tag]         1.5.4      -> 1.5.4
 * [new tag]         1.5.5      -> 1.5.5
 * [new tag]         1.5.6      -> 1.5.6
 * [new tag]         1.5.7      -> 1.5.7
 * [new tag]         1.5.8      -> 1.5.8
 * [new tag]         1.5.9      -> 1.5.9
 * [new tag]         1.6.0      -> 1.6.0
 * [new tag]         1.6.1      -> 1.6.1
 * [new tag]         1.6.10     -> 1.6.10
 * [new tag]         1.6.11     -> 1.6.11
 * [new tag]         1.6.12     -> 1.6.12
 * [new tag]         1.6.13     -> 1.6.13
 * [new tag]         1.6.14     -> 1.6.14
 * [new tag]         1.6.15     -> 1.6.15
 * [new tag]         1.6.16     -> 1.6.16
 * [new tag]         1.6.17     -> 1.6.17
 * [new tag]         1.6.2      -> 1.6.2
 * [new tag]         1.6.3      -> 1.6.3
 * [new tag]         1.6.4      -> 1.6.4
 * [new tag]         1.6.5      -> 1.6.5
 * [new tag]         1.6.6      -> 1.6.6
 * [new tag]         1.6.7      -> 1.6.7
 * [new tag]         1.6.8      -> 1.6.8
 * [new tag]         1.6.9      -> 1.6.9
 * [new tag]         1.7.0      -> 1.7.0
 * [new tag]         1.7.1      -> 1.7.1
 * [new tag]         1.7.2      -> 1.7.2
 * [new tag]         1.7.3      -> 1.7.3
 * [new tag]         1.7.4      -> 1.7.4
 * [new tag]         1.7.5      -> 1.7.5
 * [new tag]         1.7.6      -> 1.7.6
 * [new tag]         1.7.7      -> 1.7.7
 * [new tag]         1.8.0      -> 1.8.0
 * [new tag]         1.8.1      -> 1.8.1
 * [new tag]         1.8.2      -> 1.8.2
 * [new tag]         1.8.3      -> 1.8.3
 * [new tag]         1.8.4      -> 1.8.4
 * [new tag]         1.8.5      -> 1.8.5
 * [new tag]         1.8.6      -> 1.8.6
 * [new tag]         1.9.0      -> 1.9.0
 * [new tag]         1.9.1      -> 1.9.1
 * [new tag]         1.9.2      -> 1.9.2
 * [new tag]         1.9.3      -> 1.9.3
 * [new tag]         2.0.0      -> 2.0.0
 * [new tag]         2.0.1      -> 2.0.1
 * [new tag]         2.0.2      -> 2.0.2
 * [new tag]         2.0.3      -> 2.0.3
 * [new tag]         2.0.4      -> 2.0.4
 * [new tag]         2.0.5      -> 2.0.5
 * [new tag]         2.0.6      -> 2.0.6
 * [new tag]         2.1.0      -> 2.1.0
 * [new tag]         2.1.1      -> 2.1.1
 * [new tag]         2.1.10     -> 2.1.10
 * [new tag]         2.1.11     -> 2.1.11
 * [new tag]         2.1.12     -> 2.1.12
 * [new tag]         2.1.13     -> 2.1.13
 * [new tag]         2.1.14     -> 2.1.14
 * [new tag]         2.1.15     -> 2.1.15
 * [new tag]         2.1.16     -> 2.1.16
 * [new tag]         2.1.2      -> 2.1.2
 * [new tag]         2.1.3      -> 2.1.3
 * [new tag]         2.1.4      -> 2.1.4
 * [new tag]         2.1.5      -> 2.1.5
 * [new tag]         2.1.6      -> 2.1.6
 * [new tag]         2.1.7      -> 2.1.7
 * [new tag]         2.1.8      -> 2.1.8
 * [new tag]         2.1.9      -> 2.1.9
 * [new tag]         2.2.0      -> 2.2.0
 * [new tag]         2.2.1      -> 2.2.1
HEAD is now at 2749c52d3 Merge pull request #6840 from GauthamGoli/argv-cleanup-6
Traceback (most recent call last):
        9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
        8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
        7: from /usr/local/Homebrew/Library/Homebrew/global.rb:109:in `<top (required)>'
        6: from /usr/local/Homebrew/Library/Homebrew/global.rb:109:in `new'
        5: from /usr/local/Homebrew/Library/Homebrew/PATH.rb:10:in `initialize'
        4: from /usr/local/Homebrew/Library/Homebrew/PATH.rb:73:in `parse'
        3: from /usr/local/Homebrew/Library/Homebrew/PATH.rb:73:in `flat_map'
        2: from /usr/local/Homebrew/Library/Homebrew/PATH.rb:73:in `each'
        1: from /usr/local/Homebrew/Library/Homebrew/PATH.rb:73:in `block in parse'
/usr/local/Homebrew/Library/Homebrew/PATH.rb:73:in `split': invalid byte sequence in UTF-8 (ArgumentError)
Failed during: /usr/local/bin/brew update --force`
