### ISSUE TITLE
'keep' packages and 'orphaned' dependencies...

### ISSUE THREAD

**Issue by georgalis** [Homebrew/brew#6637]
# A detailed description of the proposed feature

* List packages that have been specifically installed (and not their respective dependencies)
* Remove orphaned dependencies (packages that were installed as dependencies, for packages that have since been removed) 
* and/or make this procedure more straightforward with existing functionality

# The motivation for the feature

Difficult to identify packages suitable for removal and their respective dependencies.

# How the feature would be relevant to at least 90% of Homebrew users

It is simple to try out new packages, recently I unsuccessfully tried several OCR packages to convert some pdf to plain text. These packages installed a lot of dependencies. This is a common pattern when looking for new software, but how do we identify and remove the packages (and dependencies) we no longer want?

# What alternatives to the feature have been considered

There is probably a way to do this with brew commands.... but it is not intuitive and certainly not straightforward. The pkgin package management system has commands (from the main help)
```
show-keep           (sk  ) - Display keep packages
show-no-keep        (snk ) - Display autoremovable packages
autoremove          (ar  ) - Remove orphaned dependencies
clean               (cl  ) - Remove downloaded package files
```
eg
```
pkgin sk
nmap-7.70nb1 is marked as non-autoremovable
netcat-1.10nb3 is marked as non-autoremovable
mtr-0.92nb5 is marked as non-autoremovable
fping-4.2 is marked as non-autoremovable
...
```
so if I were to execute
```
pkgin remove nmap && pkgin autoremove && pkgin clean
```
nmap and all the dependencies (not required by other packages) would be removed and the cache files cleaned.

The 'keep' and 'orphaned' concepts are very helpful. It may be possible to use `brew leaves` to create a keep list, then iterate removal of leaves not in the keep list? Would be great to see that pattern integrated as part of the `brew clean` options.

**Comment by georgalis** [comment]
# A command sequence to achieve the needful...

```
brew leaves | while read a ; do brew desc "$a" >>brew.keep.desc ; done
```
* remove packages you don't want from `brew.keep.desc`
```
brew leaves | while read a ; do \
    grep -q "^${a}: " brew.keep.desc \
        || echo "brew remove $a"
    done
```
* exec the commands, after visual inspection, be careful, _as packages are removed, you may find new leaves, which you want to keep, and which were not part of the original list_, in this case,  append the list
```
brew desc newleaf >>brew.keep.desc
```
* repeat the second step as required
* cleanup remaining
```
brew cleanup -s
```

**Comment by dawidd6** [comment]
If I understand correctly, `brew leaves` should give you the list of formulae installed on request.

There are external commands available, that provide the autoremove-like procedure, for example: https://github.com/dawidd6/homebrew-autoremove (shameless plug).

**Comment by MikeMcQuaid** [comment]
> If I understand correctly, `brew leaves` should give you the list of formulae installed on request.

Yes.

`brew bundle` and `brew bundle cleanup` is your best bet for this workflow.
