### ISSUE TITLE
Provide an easy way to change homebrew's origins.

### ISSUE THREAD

**Issue by qiulang** [Homebrew/brew#6640]
# A detailed description of the proposed feature

Provide an easy way to change brew's origin setting so people can use other source than github.

```
brew --config
HOMEBREW_VERSION: 2.1.15
ORIGIN: https://github.com/Homebrew/brew // easy way to change this  
HEAD: 2bf8015bc44878d432fb9da4f11e1d8abcef8f32
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core //and this
...
```

For example for npm I can just run `npm config set registry <registry url>`to change the default registry but brew does not have such command.

# How the feature would be relevant to Homebrew users

The feature would be relevant to all Homebrew users in China for example, b/c access to github can be very slow in China. 

There are already several famous Chinese Universities, i.e.  [tsinghua univ](https://mirror.tuna.tsinghua.edu.cn/help/homebrew/) provides brew source mirror.

But we have to replace source one by one. Besides, people do not always know the difference between core and cask.

**Comment by qiulang** [comment]
Hi I only know these 2 mirrors
1. tsinghua univ    https://mirror.tuna.tsinghua.edu.cn/help/homebrew/
2. ustc univ  https://lug.ustc.edu.cn/wiki/mirrors/help/brew.git

**Comment by aaronliu0130** [comment]
I'm in china and, for me, gihub isn't slow. Good proposion though.

**Comment by ayaz115** [comment]
[Fixed iphone problem](https://www.fixiphone.site) Thats Good... Fix iphone
