### ISSUE TITLE
brew audit --online hangs forever (including CI) sometimes

### ISSUE THREAD

**Issue by bayandin** [Homebrew/brew#6648]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I'm working on [upgrading Python to 3.8 for Homebrew](https://github.com/Homebrew/homebrew-core/pull/45337).

# What happened (include command output)

After some hours of building on Homebrew's CI Catalina build hangs on `brew audit ... --online` command (for example [this one](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50498/version=catalina/console)). All the previous builds had the same problem

# What you expected to happen

I expect `brew audit ... --online` not to hang

<details>
  <summary>Command output</summary>
  <pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew/homebrew-core is not on the master branch.

Check out the master branch by running:
  git -C "$(brew --repo homebrew/core)" checkout master

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.7m/greenlet/greenlet.h

$ brew config
HOMEBREW_VERSION: 2.1.15-63-g090259b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 090259b97304cd303fb0e4b3cefdf7bf9a2596fd
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6acdd16ac6a6afe3c90337ffc9c0288b61937df2
Core tap last commit: 24 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13, 1.8.0_202
macOS: 10.15-x86_64
CLT: 1100.0.33.8
Xcode: 11.1 => /Applications/Xcode-11.1.app/Contents/Developer
  </pre>
</details>

# Step-by-step reproduction instructions (by running `brew` commands)

```bash
# here is the way I reproduced it locally:
for i in $(seq 100); do echo "ATTEMPT $i"; brew audit --debug anime-downloader --online; done
```

For me, usually, it hangs after 20-50 tries.

**Comment by MikeMcQuaid** [comment]
How long does it hang for? How many seconds/minutes/hours/days?

**Comment by bayandin** [comment]
[This one on CI](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50498/version=catalina/) was hang for 26 hours and killed after all.
Locally I killed it after 30 minutes.

**Comment by bayandin** [comment]
Looks like it's not a Catalina only problem.
Currently, a [High Sierra build](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50586/version=highsierra/console) is hanging on `brew audit fdroidserver --online` already for 2 hours

**Comment by bayandin** [comment]
And another one hanging build on High Sierra: [`brew audit salt --online`](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50594/version=highsierra/console). Together with  [`brew audit fdroidserver --online`](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50586/version=highsierra/console) they block CI completely (sorry both PRs from me 😞).
I don't know if anyone wants to debug the particular example, but probably at least one should be killed to let CI work.

//cc @fxcoudert who usually helps me with killing hanging jobs

**Comment by MikeMcQuaid** [comment]
I've killed that job.

**Comment by MikeMcQuaid** [comment]
If you can pin down (perhaps with `--debug --verbose`) exactly what it's hanging on that would be useful.

**Comment by MikeMcQuaid** [comment]
Something like https://github.com/Homebrew/brew/pull/6037 will likely be needed.

**Comment by dawidd6** [comment]
I couldn't reproduce this on linux. Looks like macOS specific issue.

**Comment by bayandin** [comment]
> If you can pin down (perhaps with --debug --verbose) exactly what it's hanging on that would be useful.

Funny enough, it has stopped to reproduce for me locally. Will attach it as soon as I get it

**Comment by chenrui333** [comment]
I just did 100 times run on my Mac machine (Mojave OS), and I did not see any hanging. Glad it resolved on your end!
