### ISSUE TITLE
brew not installing postgresql and memcached properly

### ISSUE THREAD

**Issue by deborah-ufw** [Homebrew/brew#665]
After brew update, brew doctor, and brew doctor fixes, today brew installed postgresql and memcached on MacOSX, which recently updated with some interesting issues.

Brew confirmed installation and, after brew tap services, started both services and confirmed they started.

Then tried to work on my app. Although pgAdminIII showed a healthy database, the app was unable to connect and use it. This was resolved by brew uninstalling postgres, and re-installing using a different party's installer. The app was able to connect and use.

Then the app was unable to find or use memcached. 

`brew services list`  returns

`memcached started deborah /Users/deborah/Library/LaunchAgents/homebrew.mxcl.memcached.plist`

but `lsof | grep memcach` returns nothing.

I tried to install memcached manually, but it turns out there is a libevent dependency that can not be met, due to a recent OSX update that changed how openssl is accessed. 

So, I am back here hoping someone can recommend a fix or workaround. ? :)

**Comment by MikeMcQuaid** [comment]
Can you paste the output you get from `brew config`, `brew install memcached` and `brew services list`? Thanks!

**Comment by deborah-ufw** [comment]
oh you were too fast. With appalled shock, I noticed I had accidentally emptied my etc/hosts file while pasting documentation in notepad. After restoring localhost, it works as expected. 

Still do not know why the brew install of postgres did not work, though!

**Comment by MikeMcQuaid** [comment]
> oh you were too fast. With appalled shock, I noticed I had accidentally emptied my etc/hosts file while pasting documentation in notepad. After restoring localhost, it works as expected.

No worries!


> Still do not know why the brew install of postgres did not work, though!

We can try to fix that with you if you want to uninstall the package you used. Otherwise: I think we're done here, right?

**Comment by MikeMcQuaid** [comment]
Assuming this is fixed for now, shout if not!
