### ISSUE TITLE
pkg-config files are wrong on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by pcr910303** [Homebrew/brew#6656]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to use [`pkg-config`](https://github.com/Homebrew/homebrew-core/tree/master/Formula/pkg-config.rb) to automatically detect system-provided libxml2 when building Emacs.

Related threads are [[0]](https://lists.gnu.org/archive/html/emacs-devel/2019-09/msg00550.html) and [[1]](https://lists.gnu.org/archive/html/emacs-devel/2019-10/msg00392.html).

## What happened (include command output)

macOS 10.15 ships system header files to `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/`. There is no `/usr/include` directory, but `brew` provided `pkg-config` [.pc files](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac/pkgconfig/10.15/) point to `/usr/include`.

## What you expected to happen

`brew` provided `pkg-config` [.pc files](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac/pkgconfig/10.15/) should point to the exact directory.

## Step-by-step reproduction instructions (by running `brew` commands)

```shellsession
$ brew install pkg-config
$ pkg-config --cflags --libs "libxml-2.0 > 2.6.17" # Expected output: -l/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ -lxml2
-I/usr/include/libxml2 -lxml2
```

**Comment by MikeMcQuaid** [comment]
Merging into https://github.com/Homebrew/brew/issues/6656.
