### ISSUE TITLE
Need updated version of DAR with strong encryption enabled

### ISSUE THREAD

**Issue by pablolarrimbe** [Homebrew/brew#666]
Thanks for supporting DAR, this is very appreciated.  The current version of DAR in the repository is a bit older and doesn't support strong encryption (which needs to be enabled at compiling time).

For that you only need to have libgcrypt pre installed which is quite easy to get (brew install libgcrypt).

Is there any chance someone can help with this?

Thanks a lot.

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by pablolarrimbe** [comment]
Hey Mike, thanks for the quick response.

I'm not sure I follow.  I'm not intending to upload the new version myself, I'm just requesting someone to do it.  I honestly wouldn't know how to deploy a new homebrew packet.

Regards,
Pablo.

**Comment by MikeMcQuaid** [comment]
That documentation describes how to do it. If you'd like it: you should try and do it.

**Comment by pablolarrimbe** [comment]
Hey Mike, no worries thanks for your help.  I found the version I needed in ports. 
Regards,
Pablo.

**Comment by ilovezfs** [comment]
Actually the use of the "old" version is intentional right now because the "new" version does not support Mavericks. But since we're dropping Mavericks support soon, this will take care of itself shortly unless we choose to jump the gun and drop Mavericks support for this one early in which case it can happen immediately.

**Comment by DomT4** [comment]
> this will take care of itself shortly unless we choose to jump the gun and drop Mavericks support for this one early in which case it can happen immediately.

Since nothing in Homebrew seems to be using `dar` & apparently nobody on Mavericks has attempted to install `dar` in the last ~3 months, this seems reasonable enough.

**Comment by MikeMcQuaid** [comment]
> Since nothing in Homebrew seems to be using dar & apparently nobody on Mavericks has attempted to install dar in the last ~3 months, this seems reasonable enough.

👍 from me too.

**Comment by ilovezfs** [comment]
OK, so strong crypto is available in the 2.4* series as well. OP just needs to build `--with-libgcrypt`, which we could consider making the default.

As for 2.5 series, I opened this: https://github.com/Homebrew/homebrew-core/pull/3888

I've only tested it with gcc5 and gcc6, but the `thread_local` feature is apparently also available with both Xcode 8's clang and llvm clang.
