### ISSUE TITLE
Not require upgrade on every command

### ISSUE THREAD

**Issue by syuraj** [Homebrew/brew#6662]
# A detailed description of the proposed feature

Brew doesn't need to upgrade on every brew commands like `brew install <some package>`.

# The motivation for the feature

It is annoying to have to upgrade each time and slows down the installation.

# How the feature would be relevant to at least 90% of Homebrew users
Everyone will encounter this issue while trying to hit brew commands.

# What alternatives to the feature have been considered

**Comment by jonchang** [comment]
Closing as this is already addressed in the documentation.
