### ISSUE TITLE
Missing string sanitation on `brew install` input

### ISSUE THREAD

**Issue by chris--** [Homebrew/brew#6678]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Tried to install a package in a specific version and mistakenly used "colon" instead of "@" for the version specification syntax.

## What happened (include command output)

brew throws an error which shouldn't be user-visible and asks to report it as a bug. 

<details>
  <summary>Command output</summary>
  <pre>

christian@Christians-MBP dev % brew install nodejs:12
Error: No available formula with the name "nodejs:12"
Error: no implicit conversion of nil into String
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:89:in `basename'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:89:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:190:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:190:in `block in for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:189:in `for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:178:in `load'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/missing_formula.rb:36:in `suggest_command'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/missing_formula.rb:25:in `cask_reason'
/usr/local/Homebrew/Library/Homebrew/missing_formula.rb:9:in `reason'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:278:in `rescue in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

  </pre>
</details>

## What you expected to happen

A user-friendly message about syntactic problems with the input.

## Step-by-step reproduction instructions (by running `brew install` commands)

* <pre>brew update</pre>
* <pre>brew install nodejs:12</pre>

## System config

<details>
  <summary>brew config and doctor output</summary>
  <pre>

christian@Christians-MBP dev % brew config && brew doctor
HOMEBREW_VERSION: 2.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2bf8015bc44878d432fb9da4f11e1d8abcef8f32
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4e348daa8e76c1750a20803e716afd9362ce313b
Core tap last commit: 10 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13, 1.8.0_231
macOS: 10.15-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: N/A
CLT headers: 11.0.0.0.1.1567737322
Your system is ready to brew.
  </pre>
</details>

**Comment by zachauten** [comment]
Seems like the colon in "nodejs:12" is causing `FromURILoader.can_load?` to return true, and the cask loader tries to load it from a URI. Later, `URI.path` resolves to nil when being passed into `File.basename` and causes the error.

A nil check could be added to `FromURILoader.initialize`, or `FromURILoader.can_load` could be modified to return false if the parsed URI doesn't have a path.
