### ISSUE TITLE
brew tap asks for git credentials 

### ISSUE THREAD

**Issue by ahmedelgabri** [Homebrew/brew#6679]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
- [x] also ran `brew update-reset`

```
$ brew config

HOMEBREW_VERSION: 2.1.15-107-g5da322d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5da322d6be314e5f8b1729e91e60be743a1e7d8e
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8859bbe64cb9e735cd1ceb4efaf170eae5b21004
Core tap last commit: 22 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_FORCE_BREWED_GIT: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_VISUAL: nvim
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/opt/git/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_222
macOS: 10.15.1-x86_64
CLT: 1100.0.33.8
Xcode: 11.2
```

```
$ brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```

## What you were trying to do (and why)

`brew tap dandavison/delta`

## What happened (include command output)

```
$ brew tap dandavison/delta
==> Tapping dandavison/delta
Cloning into '/usr/local/Homebrew/Library/Taps/dandavison/homebrew-delta'...
Username for 'https://github.com':
```

I'm already authenticated with Github using SSH 

```
$ ssh -T git@github.com
Hi ahmedelgabri! You've successfully authenticated, but GitHub does not provide shell access.
```

And if I clone any repo using `https` it works fine without issues because credentials are cached in Keychain. 

## What you expected to happen

To be able to tap the formula

## Step-by-step reproduction instructions (by running `brew` commands)

`brew tap dandavison/delta`

**Comment by jonchang** [comment]
`brew tap` by default clones via HTTPS, not SSH. You will need to use the two-argument form to specify the e.g., `git@github.com:...` URL. See `brew tap --help` for details.

**Comment by ahmedelgabri** [comment]
> `brew tap` by default clones via HTTPS, not SSH. You will need to use the two-argument form to specify the e.g., `git@github.com:...` URL. See `brew tap --help` for details.

I mentioned already that cloning any `http` repo works fine. So, I dunno why is `brew tap` asking for my credentials?

**Comment by jonchang** [comment]
I can't see https://github.com/dandavison/homebrew-delta, so I assume it's a private repository that you need to authenticate against.

**Comment by ahmedelgabri** [comment]
This is the right URL https://github.com/dandavison/delta

**Comment by jonchang** [comment]
```console
$ brew tap --help
Usage: brew tap [options] user/repo [URL]

Tap a formula repository.

If no arguments are provided, list all installed taps.

With URL unspecified, tap a formula repository from GitHub using HTTPS. Since
so many taps are hosted on GitHub, this command is a shortcut for brew tap
user/repo https://github.com/user/homebrew-repo.

With URL specified, tap a formula repository from anywhere, using any
transport protocol that git(1) handles. The one-argument form of tap
simplifies but also limits. This two-argument command makes no assumptions, so
taps can be cloned from places other than GitHub and using protocols other than
HTTPS, e.g. SSH, GIT, HTTP, FTP(S), RSYNC.
```

> With URL unspecified, tap a formula repository from GitHub using HTTPS. Since so many taps are hosted on GitHub, this command is a shortcut for brew tap user/repo https://github.com/user/homebrew-repo.

**Comment by jonchang** [comment]
If you need further help: post on the Discourse forum.
