### ISSUE TITLE
audit errors with bitbucket repos

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/brew#6681]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Audit new formula with `brew audit --strict`

## What happened (include command output)

Ruby error on Jenkins, see https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50866/version=catalina/testReport/junit/brew-test-bot/catalina/audit_mpi4py___online___new_formula/

<details>
  <summary>Command output</summary>
  <pre>
  failed: brew audit mpi4py --online --new-formula
          Error: undefined method `[]' for nil:NilClass
  /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:621:in 
  `audit_bitbucket_repository'
  /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1006:in `block in audit'
  /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:999:in `each'
  /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:999:in `audit'
  /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:123:in `block in audit'
  /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:116:in `each' 
  /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:116:in `audit'
  /usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
  </pre>
</details>

## What you expected to happen

Audit succeeds or fails telling user why it failed

## Step-by-step reproduction instructions (by running `brew` commands)

`brew audit mpi4py --strict --online` on brew testbot

Looks like [dev-cmd/audit.rb:621](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L621) is to blame.

**Comment by jonchang** [comment]
Note that Jenkins audits on Mojave are currently disabled due to some Ruby gem issues.

**Comment by zbeekman** [comment]
Thanks Jon!
