### ISSUE TITLE
Homebrew gets stuck in an infinite loop after installing items

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/brew#6686]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew upgrade

## What happened (include command output)

In summary
 <pre>
...
==> Upgrading 4 outdated packages:
cmake 3.15.4 -> 3.15.5
harfbuzz 2.6.2 -> 2.6.4
mercurial 5.1.1_2 -> 5.1.2
git 2.23.0_1 -> 2.24.0
...
These got installed OK (link step omitted for cmake as I have cmake cask installed).
...
==> Summary
🍺  /usr/local/Cellar/git/2.24.0: 1,547 files, 45.5MB
Removing: /usr/local/Cellar/git/2.23.0_1... (1,543 files, 44.9MB)
Removing: /Users/ralph/Library/Caches/Homebrew/git--2.23.0.mojave.bottle.tar.gz... (17.1MB)
Removing: /Users/ralph/Library/Caches/Homebrew/git--2.23.0_1.mojave.bottle.tar.gz... (17.1MB)
 </pre>

Then the command hung. I quit out of it with ctrl c (several times). 
The traceback appear to show an infinite loop.

Hundreds of repetitions like this:
  <pre>
	  37: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
	  36: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
	  35: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
	  34: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
	  33: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
	  32: from /usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
	  31: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
	  30: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
	  29: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
	  28: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
	  27: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
	  26: from /usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
	  25: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
	  24: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
	  23: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
	  22: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
	  21: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
	  20: from /usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
	  19: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
	  18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
	  17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
	  16: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
	  15: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
	  14: from /usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
	  13: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
	  12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
	  11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
	  10: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:274:in `block (2 levels) in broken_dependents'
	   9: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:274:in `each'
	   8: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:280:in `block (3 levels) in broken_dependents'
	   7: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:280:in `new'
	   6: from /usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:27:in `initialize'
	   5: from /usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:86:in `check_dylibs'
	   4: from /usr/local/Homebrew/Library/Homebrew/linkage_cache_store.rb:53:in `fetch'
	   3: from /usr/local/Homebrew/Library/Homebrew/linkage_cache_store.rb:23:in `keg_exists?'
	   2: from /usr/local/Homebrew/Library/Homebrew/cache_store.rb:31:in `get'
	   1: from /usr/local/Homebrew/Library/Homebrew/cache_store.rb:88:in `db'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:157:in `parse': Interrupt
	2: from /usr/local/Homebrew/Library/Homebrew/brew.rb:38:in `<main>'
	1: from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
/usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `exit': exit (SystemExit)
/usr/local/Homebrew/Library/Homebrew/brew.rb: Interrupt
 </pre>
 </details>

## What you expected to happen

Command to terminate normally.

## Step-by-step reproduction instructions (by running `brew` commands)

brew upgrade

Note: This does not happen every time, but it has happened to me a few times now, on 2 different machines.

**Comment by ralphrmartin** [comment]
Oops, forgot to include brew config and brew doctor output:

<pre>
brew config                                                        
HOMEBREW_VERSION: 2.1.15-109-g5f3302b
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5f3302b3f7b85a308289cc62a9cd7a00ffe527d4
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 89bf3a54383d884f8b8511c6237325dd5b5ae6ba
Core tap last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: /usr/local/bin/emacs
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.1, 1.8.0_231, 1.8.0_221
macOS: 10.15.1-x86_64
CLT: N/A
Xcode: 11.2
</pre>

<pre>
brew doctor               
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libjlinkpic32.6.34.6.dylib

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libpspell.la

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  cmake
</pre>

**Comment by ralphrmartin** [comment]
I did not like cmak as I have cmake cask installed, so linking of cmake is skipped.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/brew/issues/6586

**Comment by MikeMcQuaid** [comment]
Tracked in https://github.com/Homebrew/brew/issues/6671.
