### ISSUE TITLE
If i git clone this project, how can i install homebrew???

### ISSUE THREAD

**Issue by Planeswalker23** [Homebrew/brew#6689]
as title

cause i can‘t install homebrew by 
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
so i want to ask if where are other ways to install homebrew

**Comment by dawidd6** [comment]
https://docs.brew.sh/Installation#untar-anywhere

**Comment by Planeswalker23** [comment]
> https://docs.brew.sh/Installation#untar-anywhere

Thanks!!!
