### ISSUE TITLE
'brew upgrade ruby-build' Error due to typo on <Mac OS 10.15.1> <Homebrew v. 2.1.16-34-g6521dbb-dirty>

### ISSUE THREAD

**Issue by papz** [Homebrew/brew#6712]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew upgrade ruby-build

To upgrade versions 20170523 to 20191105

## What happened (include command output)

<details>
  <summary>Error: undefined local variable or method `upgradable' for Homebrew:Module</summary>
  <pre>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:252:in `check_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:114:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
paulangell@Pauls-MacBook-Pro Library % vi /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb
paulangell@Pauls-MacBook-Pro Library % vi /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:252
paulangell@Pauls-MacBook-Pro Library % vi -n 252 /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb
2 files to edit
  </pre>
</details>

## What you expected to happen

No Error occuring.   

'upgradeable' is method used instead of 'upgradable'

## Step-by-step reproduction instructions (by running `brew` commands)
Simply execute on the same Homebrew version outlined in [this gist](https://gist.github.com/papz/a994094531dbd114f9aa57ed955838ba)
brew upgrade ruby-build

**Comment by scpeters** [comment]
closed by #6713
