### ISSUE TITLE
brew.sh cant parse dev curl version (brew.sh: line 64: printf: 0-DEV: invalid number)

### ISSUE THREAD

**Issue by evgkrsk** [Homebrew/brew#6721]
- [-] ran `brew update` and can still reproduce the problem?
- [-] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [-] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to do https://docs.brew.sh/Homebrew-on-Linux#alternative-installation

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
 evg at latitude in ~ $eval $(~/.linuxbrew/bin/brew shellenv)
/home/evg/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 64: printf: 0-DEV: invalid number
  </pre>
</details>

Additional curl info:
<details>
<summary>curl --version</summary>
<pre>
evg at latitude in ~ $curl --version
curl 7.66.0-DEV (x86_64-alt-linux-gnu) libcurl/7.66.0-DEV OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) nghttp2/1.39.2
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
</pre>
</details>

## What you expected to happen

Nothing printed in stdout/stderr

## Step-by-step reproduction instructions (by running `brew` commands)

1. git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
2. mkdir ~/.linuxbrew/bin
3.  ln -s ../Homebrew/bin/brew ~/.linuxbrew/bin
4. eval $(~/.linuxbrew/bin/brew shellenv)

**Comment by MikeMcQuaid** [comment]
Sorry, we don't support development `curl` versions. We'll accept a PR to handle this case.
