### ISSUE TITLE
Who builds and maintains bottles?

### ISSUE THREAD

**Issue by VoidingWarranties** [Homebrew/brew#673]
Apologies if this information is already out there somewhere, but I couldn't find it in the [Bottles docs](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Bottles.md). Who builds and maintains bottles? Are bottles rebuilt automatically when a formula is updated?

**Comment by dunn** [comment]
It's mentioned in the readme that bottles are hosted by Bintray: https://github.com/Homebrew/brew#sponsors

We build the bottles on our Jenkins CI server; they're created for each formula version and `revision`.
