### ISSUE TITLE
brew unpin cause Error: No available formula with the name "firefox"

### ISSUE THREAD

**Issue by TYZRPVX** [Homebrew/brew#6740]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I use `brew cu -f -a` update apps, but I do not need update firefox, then I pinned it. Recently, I try to `brew unpin firefox`, an error happens: Error: No available formula with the name "firefox"

## What happened (include command output)

`brew unpin firefox`, an error happens:

<details>
  <summary>Command output</summary>
  <pre>

 Error: No available formula with the name "firefox"

  </pre>
</details>

## What you expected to happen

brew cu -f -a
enter [i]nteractive mode
pin firefox
brew unpin firefox

**Comment by MikeMcQuaid** [comment]
`firefox` is a cask and not a formula so cannot be pinned or unpinned.

**Comment by TYZRPVX** [comment]
> `firefox` is a cask and not a formula so cannot be pinned or unpinned.

![image](https://user-images.githubusercontent.com/7645818/68990353-168d6e80-088d-11ea-89c3-5978c5b179ab.png)

brew cu -f -a, then you can pin it.

**Comment by reitermarkus** [comment]
`brew cu` is not an official command.
