### ISSUE TITLE
cannot install linuxbrew when git version is v1.7.1

### ISSUE THREAD

**Issue by randy3k** [Homebrew/brew#6746]
I couldn't install `linuxbrew` on a linux server because git version is too old and it doesn't understand `git config --local`

```bash
Error: Failure while executing; `git config --local --replace-all homebrew.donationmessage true` exited with 129.
Failed during: /home/cslai/.linuxbrew/bin/brew update --force
```

I just to want to make sure what a minimum requirement of `git` linuxbrew assumes.

Update: I am not an admin of the server, so updating `git` is not an option (of course, I could ask the admin to update it, but it's another story).

**Comment by dawidd6** [comment]
https://github.com/Homebrew/brew/blob/2e0c703cb6a5965932e9842f825f941500ea5ecc/Library/Homebrew/brew.sh#L163

**Comment by randy3k** [comment]
It seems that it wasn't checked on linux. Futhermore, setting `HOMEBREW_FORCE_BREWED_GIT="1"` doesn't help neither.

**Comment by randy3k** [comment]
Oh, should I report to https://github.com/Linuxbrew/install instead?

**Comment by issyl0** [comment]
Yes, please report this to `Linuxbrew/install` as this is a Linux install issue and the scripts are different between macOS and Linux for now. Thanks!
