### ISSUE TITLE
Pouring large bottles uses lots of memory

### ISSUE THREAD

**Issue by wirelyre** [Homebrew/brew#6757]
## Checklist

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## Problem

This has been happening for at least a year.

I just ran `brew upgrade llvm` and it took well over 30 minutes. The Ruby process repeatedly bloated to 3GB and unbloated down to 0.5GB. This made the computer swap very hard and rendered the system completely unusable, except during the unbloats where I could check the Activity Monitor.

By contrast, I can untar the bottle manually in 4 minutes and 1.2 MB RAM:

<details>
  <summary>Command output</summary>
  <pre>$ time -l tar -xf ~/Library/Caches/Homebrew/llvm--9.0.0_1.catalina.bottle.tar.gz
      224.38 real        16.45 user         7.09 sys
   1228800  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
       358  page reclaims
         4  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
      5182  voluntary context switches
     65349  involuntary context switches</pre>
</details>

This doesn't happen with small bottles, even when `brew upgrade` pours a bunch of small bottles in a row.

I'm using a case-sensitive APFS volume.

Now, this *is* a 2012 MacBook without SSD and with 4GB RAM. But the whole bottle is also only 1.2GB packed and 3.8GB unpacked. I expect that, if this also happens on other systems, fixing it would make upgrades noticeably faster.

## brew doctor and config

<details>
  <summary>doctor</summary>
  <pre>$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
&nbsp;
Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
&nbsp;
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.6
&nbsp;
Warning: Homebrew's sbin was not found in your PATH but you have installed formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish</pre>
</details>

<details>
  <summary>config</summary>
  <pre>$ brew config
HOMEBREW_VERSION: 2.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0c5930b3e5dd9bc366924a2d7a99acc6b55d77d9
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12
macOS: 10.15.1-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: N/A
CLT headers: 11.0.0.0.1.1567737322</pre>
</details>

**Comment by MikeMcQuaid** [comment]
Memory is there to be used. An algorithm using less memory will be slower. This may be related to your case-sensitive filesystem. We can talk more about this if you provide the full output of a slow `brew upgrade` run (with annotations about where is slow) but we don't consider large memory usage to be a bug.

**Comment by wirelyre** [comment]
Okay!

```
$ brew remove llvm
Uninstalling /usr/local/Cellar/llvm/9.0.0_1... (6,839 files, 3.7GB)
$ rm -r ~/Library/Caches/Homebrew
$ brew install llvm
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/llvm-9.0.0_1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a8/a8e2475a1fc5a81f0da83a73d17fd54cc2a686f
######################################################################## 100.0%
```

Everything is fine so far. Then:

```
==> Pouring llvm-9.0.0_1.catalina.bottle.tar.gz
```

I turned on a stopwatch when this line appeared. Times are (minutes:seconds).

- **00:00.** Nothing interesting is happening. There's some `cp` process that's handling about 4GB on disk but I don't know what it's doing.
- **13:31.** Suddenly the Ruby process increases steadily to 1GB of RAM. It climbs slowly until…
- **14:48.** It rises quickly to 3.2GB of RAM. The Activity Monitor stops responding to keypresses. The window manager freezes. The pointer is a spinning ball. The computer is now useless.
- **18:12.** The computer unfreezes. There's about 2.5GB in swap memory. The Ruby process drops back to 0.5GB but quickly climbs back to 1GB. It holds steady.
- **22:18.** The Ruby process rises quickly to 3.2GB. The computer completely freezes again.
- **26:08.** The computer unfreezes. The Ruby process drops to 0.5GB, then grows to 1GB and holds steady.
- **29:38.** The computer freezes again.
- **32:58.** The computer unfreezes.
- **34:08.** The computer freezes.
- **37:01.** The computer unfreezes and…

```
==> Caveats
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

llvm is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH run:
  echo 'set -g fish_user_paths "/usr/local/opt/llvm/bin" $fish_user_paths' >> ~/.config/fish/config.fish

For compilers to find llvm you may need to set:
  set -gx LDFLAGS "-L/usr/local/opt/llvm/lib"
  set -gx CPPFLAGS "-I/usr/local/opt/llvm/include"

==> Summary
🍺  /usr/local/Cellar/llvm/9.0.0_1: 6,839 files, 3.7GB
$
```

A few minutes later we've unswapped most of the memory and have a normal system again.

---

I know this isn't much to go on, but it's reproducible. And since it happens between "Pouring…" and "Caveats…" we're not even looking at the whole code base.

I'm hoping this happens on other systems. Specifically, I'm hoping that, when `brew install llvm` pours `llvm-9.0.0_1.catalina.bottle.tar.gz`, the Ruby process often uses 3GB of RAM. I would expect the freezing on my machine given that RAM usage fluctuates between 0.5GB and 3.2GB. I would also expect that other machines with more RAM do not freeze, and machines with an SSD and 4GB RAM swap so quickly that you can't notice.

**Comment by MikeMcQuaid** [comment]
For future reference pasting the full, continuous output would be more helpful. `brew install moreutils` and piping to `ts` will provide a timestamp on each line which would be helpful for debugging.

> I'm hoping this happens on other systems.

I'm afraid we've not had any other reports of this. It takes 1m15s to extract on my fairly fast SSD so it's unfortunately unsurprising it may take a much longer time on a non-SSD. I'm open to a pull request that makes this better but I'm afraid this probably needs filed under "modern macOS experience on a non-SSD is terrible" for now, sorry.
