### ISSUE TITLE
Contradictory output from different commands about dependents of py2cairo

### ISSUE THREAD

**Issue by rgoldberg** [Homebrew/brew#6758]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Tried to uninstall py2cairo.

## What happened (include command output)

Got error.  See command output.

<details>
  <summary>Command output</summary>
  <pre>
$ brew uninstall py2cairo                                                         
Error: Refusing to uninstall /usr/local/Cellar/py2cairo/1.18.2
because it is required by pygobject3, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies py2cairo

$ brew uses py2cairo
pygtk

$ brew uses --include-build --include-test --include-optional py2cairo 
pygtk

$ brew uses --installed py2cairo
pygobject3

$ brew uses --installed --include-build --include-test --include-optional py2cairo

$ brew deps --1 pygobject3
gobject-introspection
py3cairo
python

$ brew deps --1 --include-build --include-optional --include-test --include-requirements --annotate pygobject3 
gobject-introspection
meson [build]
ninja [build]
pkg-config [build]
py3cairo
python

$ brew deps pygobject3
cairo
fontconfig
freetype
gdbm
gettext
glib
gobject-introspection
libffi
libpng
lzo
openssl@1.1
pcre
pixman
pkg-config
py3cairo
python
readline
sqlite
xz

brew deps --include-build --include-optional --include-test --include-requirements --annotate pygobject3 
cairo
fontconfig
freetype
gdbm
gettext
glib
gobject-introspection
libffi
libpng
lzo
meson [build]
ninja
openssl@1.1
pcre
pixman
pkg-config
py3cairo
python
readline
sqlite
xz</pre>
</details>

## What you expected to happen

Either no error for `brew uninstall py2cairo`, or A) py2cairo listed in output of `brew deps --1 pygobject3` & B) pygobject3 listed in output of `brew uses --include-build --include-test --include-optional py2cairo`

## Step-by-step reproduction instructions (by running `brew` commands)

See Command output above.

<details>
  <summary>brew config</summary>
  <pre>
HOMEBREW_VERSION: 2.1.16
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2a369a82c7f5b3b2ab2704ff0796635514aae955
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.1-x86_64
CLT: 1100.0.33.8
Xcode: 11.2.1
XQuartz: 2.7.11 => /opt/X11</pre>
</details>

<details>
  <summary>brew doctor</summary>
  <pre>
Your system is ready to brew.</pre>
</details>

**Comment by MikeMcQuaid** [comment]
The output can contradict because one is based on the formula specification and the other based on the actual linkage from the installation. The `uninstall` messaging is correct here.

**Comment by rgoldberg** [comment]
Isn’t this ability for contradiction a problem?

Shouldn’t this remain open as an issue to fix?

Maybe formula specification should be verified against linkage, and bad formula specs should be rejected.

There should at least be a brew command that reports these discrepancies. Maybe it should be run by the commands that could have discrepancies, and output to stderr when discrepancies found for formulas relevant to the normal output.

Closing this is just sweeping a real problem under the rug.

**Comment by MikeMcQuaid** [comment]
> Isn’t this ability for contradiction a problem?

No. The formula and on-disk installation always have the potential to deviate. It's practically impossible to avoid.

> Shouldn’t this remain open as an issue to fix?

No. There's no action item here.

> Maybe formula specification should be verified against linkage, and bad formula specs should be rejected.

It's not as simple as that because the behaviour is non-deterministic and depends on the other state on the system.

> There should at least be a brew command that reports these discrepancies, so a user can easily run it to find these problems

These are not problems and there's nothing actionable for the user.

> Closing this is just sweeping a real problem under the rug.

You are welcome to run your open source projects how you choose and we will do the same, thanks. Please bear in mind that we're all volunteers here working in our free time to help you. Additionally, I've been working on this package manager for 10 years and have a better insights on what is and isn't a "real" problem for us to address.
