### ISSUE TITLE
brew cask search command doesn't exist

### ISSUE THREAD

**Issue by diasjorge** [Homebrew/brew#6761]
I find the API a bit confusing where to manage casks, you need to use commands like `brew cask install` but to search you need to do `brew search` and look in the Cask results.

# The motivation for the feature

Ideally one would be able to do `brew cask search` and only search Casks.

# How the feature would be relevant to at least 90% of Homebrew users

I don't have numbers but I'm sure this confuses people all the time (it happens to me every time I need to install a cask after a while without using brew).

# What alternatives to the feature have been considered

No alternative considered.

I would make a PR for this feature, but first I'd like to validate the idea and if it's something worth pursuing. Also any hints into were to look at in the code would be greatly appreciated.

Thanks a lot for your time and building such a great tool.

**Comment by MikeMcQuaid** [comment]
> Ideally one would be able to do `brew cask search` and only search Casks.

`brew search --casks`. Check out `man brew` or `brew search --help` in future.



> Thanks a lot for your time and building such a great tool.

Thanks for the kind words!

**Comment by EricFromCanada** [comment]
`brew cask` commands reside in `Library/Homebrew/cask/cmd` and documented under `man brew-cask`, although it might be simpler to add support for making `brew search --casks <text>` return only cask results.

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/Homebrew/brew/pull/7094
