### ISSUE TITLE
Dependency changes don't propagate down the chain of tabs

### ISSUE THREAD

**Issue by Bo98** [Homebrew/brew#6769]
I'm going to explain this by practical example. I think it'll make it a lot clearer.

First, I have a tap set up here: https://github.com/Bo98/homebrew-experimental

```sh
brew tap Bo98/homebrew-experimental
```

In Bo98/homebrew-experimental@09db5bb (please ignore the typos), I added three formulae: A, B and C. C depends on B and B depends on A. Inspect the formula files in that commit to see what I mean. Ignore subsequent commits for now and install C (which will install B and A):

```sh
cd /usr/local/Homebrew/Library/Taps/bo98/homebrew-experimental
git checkout 09db5bb26261247622ed858fca231bccd7f4a9ef
HOMEBREW_NO_AUTO_UPDATE=1 brew install C
```

So we now have a state where running `brew uses --installed A` outputs:

```
bo98/experimental/b                      bo98/experimental/c
```

In the next commit, Bo98/homebrew-experimental@0d84fbc, I removed B's dependency on A. So now the only dependency link should be C depending on B. Upgrade B as per usual:

```
brew update
brew upgrade B
```

Now observe `brew uses --installed A` again:

```
bo98/experimental/c
```

C has not been updated to show that it no longer depends on A (via B). And indeed doing `brew uninstall A` will return:

```
Error: Refusing to uninstall /usr/local/Cellar/a/1
because it is required by c, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies A
```

This is corrected when you do a `brew reinstall C`:

```
$ brew reinstall C
==> Reinstalling bo98/experimental/c 
==> Downloading https://www.w3.org/TR/PNG/iso_8859-1.txt
Already downloaded: /Users/bo/Library/Caches/Homebrew/downloads/70b505c2dee92e588030e72b28ce641ed4dd0fe3d8405006191016637359c268--iso_8859-1.txt
==> clang -dynamiclib -L/usr/local/opt/b/lib -lB -olibC.dylib test.c
🍺  /usr/local/Cellar/c/1: 4 files, 11.8KB, built in 4 seconds
$ brew uninstall A
Uninstalling /usr/local/Cellar/a/1... (4 files, 11.6KB)
```

(and then please do `brew uninstall C B` as well because me creating something called `libC.dylib` was a terrible idea and I didn't `keg_only` them properly as I somehow put a colon there. I also can't spell the word "keg" apparently)

**Comment by Bo98** [comment]
I apparently can't spell in the title either.

**Comment by MikeMcQuaid** [comment]
This behaviour is intentional. Dependencies are "locked" at formula installation time. To have consumers see their changes requires a reinstall which will update the `Tab` and the formula stored in the `.brew` subdirectory of the `Keg`. If you (as a maintainer) need to push dependency changes that you care about being reflected by `brew uninstall` you must use `revision`.

**Comment by Bo98** [comment]
Thanks that's useful to know.

This was why Cairo etc. was still detected as depending on OpenSSL 1.0, so I wasn't sure if it was intentional.

I believe the problematic change in Cairo's case was a couple levels up in Python (https://github.com/Homebrew/homebrew-core/commit/290e56ad8e46832288ea679fc0201a8e8bb50d30) which would've required revision bumps in 705 formulae.

**Comment by MikeMcQuaid** [comment]
Cool, thanks. I'm tempted to adjust the `brew deps` behaviour accordingly too.
