### ISSUE TITLE
Error: Invalid formula: /usr/local/Library/Taps/ska-sa/homebrew-tap/wcslib-old.rb No available formula with the name "wcslib-old"  In formula file: /usr/local/Library/Taps/ska-sa/homebrew-tap/wcslib-old.rb Expected to find class WcslibOld, but only found: Wcslib. Error: Cannot tap ska-sa/tap: invalid syntax in tap!

### ISSUE THREAD

**Issue by allison-matthews** [Homebrew/brew#678]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue.

### Propose a feature:

Instead of creating an issue here, please create a pull request with your change proposal in the [Homebrew Evolution](https://github.com/Homebrew/brew-evolution) repository using the [proposal template](https://github.com/Homebrew/brew-evolution/blob/master/proposal_template.md).

**Comment by MikeMcQuaid** [comment]
Please report this to https://github.com/ska-sa/homebrew-tap/issues, thanks!
