### ISSUE TITLE
Uninstalling formula should stop related running service

### ISSUE THREAD

**Issue by JBallin** [Homebrew/brew#6780]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Downgrade `postgresql` from the default v12 to `postgresql@11` because the project required that version.

## What happened (include command output)

After uninstalling `postgresql`, the service was not stopped. So I had to re-install it, stop the service, and then uninstall it.

<details>
  <summary>Command output</summary>
  <pre>

$ brew config
HOMEBREW_VERSION: 2.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 38c65969be3bcfec20ab9e8be6aae37ab55fd6fc
Core tap last commit: 21 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
$ brew doctor
Your system is ready to brew.

  </pre>
</details>

## What you expected to happen

**Uninstalling a formula that is running a service should stop the service.**

I believe the issue was caused for me because of two conflicting versions of `postgresql`.

I already had `postgresql` running with brew services, and then installed `postgresql@11` which left `postgresql` running in brew services even after I uninstalled `postgresql`.

I fixed this by stopping `postgresql` in brew services, despite it not showing up in `brew services list`.

**SEPARATE but related ISSUE: `brew services list` should show running services even if the formula is uninstalled.** - let me know if I should open a new issue for that.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install postgresql
$ brew services start postgresql

$ brew install postgresql@11
$ brew uninstall postgresql

$ brew services start postgresql@11
```

## Temporary work around

```
$ brew services stop postgresql
```

**Comment by MikeMcQuaid** [comment]
This change would be unexpected based on previous behaviour and there's a workaround so closing. This is something that could be done by e.g. `brew bundle`; please submit a pull request there rather than creating an issue (which would be closed). 

> **SEPARATE but related ISSUE: `brew services list` should show running services even if the formula is uninstalled.** - let me know if I should open a new issue for that.

Please do not open an issue for this. This is intentional for `brew services` behaviour which acts on the state of formulae installation. We would accept a pull request for this if you can figure out a way to work around this without interfering with existing behaviour.

Thanks!
