### ISSUE TITLE
extract: semver awareness

### ISSUE THREAD

**Issue by figroc** [Homebrew/brew#6793]
# A detailed description of the proposed feature

The `brew extract` command should be able to create a versioned formula that reference the latest patch version in the specified major/minor `--version`. 

# The motivation for the feature

As https://docs.brew.sh/Versions.html states:
```
Versioned formulae should differ in major/minor (not patch) versions from
the current stable release. This is because patch versions indicate bug or
security updates and we want to ensure you apply security updates.
```
That philosophy should be preserved in the `extract` command too.

**Comment by MikeMcQuaid** [comment]
I don't understand what you're asking for. Please elaborate further on what the current behaviour is and what you'd want.

**Comment by figroc** [comment]
There are 3.10.0 and 3.10.1 for protobuf formulae. By invoking `brew extract` with `--version` 3.10, we get version 3.10.0. It should be 3.10.1.

**Comment by dawidd6** [comment]
Invoking `brew extract` with `--version 3.10.1` does not work for you? Cause it is for me, just checked it.

**Comment by figroc** [comment]
@dawidd6 That works, definitely. But that would be a manually probing process. Or you have to dig into `git log` to find out the latest version.

**Comment by MikeMcQuaid** [comment]
Cool, I see. This isn't something we currently support and could be a bit difficult to fix. That said, if it's something you're interested in we will review a pull request. Thanks!
