### ISSUE TITLE
Latest Command Line Tools versions in Homebrew doesn't match Xcode.

### ISSUE THREAD

**Issue by renatohcampos** [Homebrew/brew#6796]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Tried running brew doctor to see if my last upgrade has caused any errors.
I typically do this after every update & upgrade.

## What happened (include command output)

Brew suggested I update Command Line Tools to a newer version. I've attempted to update Xcode via the terminal, but was given a prompt stating I was at the latest version. I also tried updating the Xcode app but it is also the correct version.

<details>
  <summary>Command output</summary>
  <pre>

 ➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

  </pre>
</details>

## What you expected to happen

Typically I get a message that says "your system is ready to brew".

## Step-by-step reproduction instructions (by running `brew` commands)

1. Run `brew update`.
2. Run `brew upgrade`.
3. Run`brew doctor`.

## Output of `brew config` and `brew doctor` commands

<pre>
➜  ~ brew config
HOMEBREW_VERSION: 2.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d7de295dfbc5e581106e2b1f674496b5e25a773
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8b2877e0d998a500a3a373df48c2369184e74e7c
Core tap last commit: 28 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.1-x86_64
CLT: 1100.0.33.8
Xcode: 11.2.1

➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.
</pre>

**Comment by bpzhang** [comment]
I also encountered this problem when installing openresty, but there are no new updates

**Comment by Bo98** [comment]
Does downloading the latest CLT (11.2) from https://developer.apple.com/xcode/download/more help?

**Comment by snakeh36** [comment]
thanks, it's ok!

```bash
➜  ~ brew config
HOMEBREW_VERSION: 2.2.0-47-g6decac5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6decac5875f763e6c7a87a99842474701a35fd12
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 426e46554969764449905ce883c24a1f7b43f396
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_221
macOS: 10.15.1-x86_64
CLT: 11.2.0.0.1.1571444319
Xcode: N/A
CLT headers: 11.2.0.0.1.1571444319
➜  ~ brew doctor
Your system is ready to brew.
➜  ~
```
