### ISSUE TITLE
cairo in homebrew-core built with X11 drivers by default?

### ISSUE THREAD

**Issue by danieljprice** [Homebrew/brew#6798]
# A detailed description of the proposed feature

cairo in homebrew-core needs to be built with X11 drivers by default.

# The motivation for the feature

since the removal of the --with-x11 option to the cairo package, programs that rely on the Cairo x11 drivers must actively AVOID the homebrew packaged cairo, since this essentially disables functionality that is available by default in the cairo installed by Xquartz.

This change completely broke the functionality of two open source packages I maintain (giza and splash, tapped from danieljprice/all).

# How the feature would be relevant to at least 90% of Homebrew users

Removes the need for an x11 option (supporting the removal of options from formulae), since the maximum functionality is always compiled. Removes need for separate (and conflicting) taps of cairo package. Also blocks future incorporation of giza and splash into homebrew-core, which would benefit many users in the scientific community

# What alternatives to the feature have been considered

renamed private tap of cairo => cairox11 is a workaround (see github.com/danieljprice/homebrew-all/cairox11.rb). But not ideal because requires a conflict with the homebrew-core cairo package, forcing the user to unlink the homebrew-core cairo package in order to reinstall a version with x11 support activated

**Comment by MikeMcQuaid** [comment]
X11 does not ship with macOS so we will not be making this change.

> renamed private tap of cairo => cairox11 is a workaround (see github.com/danieljprice/homebrew-all/cairox11.rb). But not ideal because requires a conflict with the homebrew-core cairo package, forcing the user to unlink the homebrew-core cairo package in order to reinstall a version with x11 support activated

A `cairo-x11` formula is the right solution for this. To avoid conflicts I would recommend making it keg-only instead.
