### ISSUE TITLE
sha1 warnings even after updating formulae to sha256

### ISSUE THREAD

**Issue by spaghetti-** [Homebrew/brew#681]
Hi I was updating some formulae from sha1 to sha256 and yet brew is still issuing me warnings on them. I am not sure why.

Relevant changes: https://github.com/ros/homebrew-deps/commit/1ba82a084024c614d0ce74ac9dde0b18944a3cd6
`brew audit` log on `urdfom.rb`:
```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/ros/homebrew-deps/urdfdom.rb:6:in `<class:Urdfdom>'
Please report this to the ros/deps tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/ros/homebrew-deps/urdfdom.rb:6:in `<class:Urdfdom>'
Please report this to the ros/deps tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/ros/homebrew-deps/urdfdom.rb:6:in `<class:Urdfdom>'
Please report this to the ros/deps tap!
```

**Comment by MikeMcQuaid** [comment]
It could be that you hit a `brew update` bug. Can you try `cd /usr/local; git reset --hard origin/master`, run `brew update` and see if you can reproduce? Thanks!

**Comment by UniqMartin** [comment]
The warnings are not your fault. That's a side effect of us tightening up the deprecation handling and the way `brew audit` works. It walks the Git recent history of the given formula (to check that a `revision` line has been removed after a version bump) and by doing so also loads older version of the formula (that hadn't been updated to avoid the deprecated functionality yet). This is what is most likely causing you to see these warnings.

The warnings should disappear if you run `brew audit` in developer mode, i.e.:

```console
$ HOMEBREW_DEVELOPER=1 brew audit ros/deps/urdfom
```

We haven't figured out yet how to suppress these spurious warnings for users that don't set `HOMEBREW_DEVELOPER=1` (while keeping them enabled when they indeed should be shown).

**Comment by ilovezfs** [comment]
For what it's worth, I think we should probably disable the deprecation of sha1 until it's working better since it seems to be the outlier in terms of causing problems.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/pull/691.

**Comment by MikeMcQuaid** [comment]
@ilovezfs @UniqMartin Do you have a way to reproduce this?

**Comment by ilovezfs** [comment]
brew audit without HOMEBREW_DEVELOPER=1 on anything that has old revisions containing sha1

**Comment by MikeMcQuaid** [comment]
I can reproduce, will fix.

**Comment by spaghetti-** [comment]
Cheers.

**Comment by MikeMcQuaid** [comment]
Sorry, had to revert that fix as it caused other issues. Will work on a better one, though.
