### ISSUE TITLE
brew doctor says a new command line tools release is available

### ISSUE THREAD

**Issue by esetnik** [Homebrew/brew#6812]
- [x] ran `brew update` and can still reproduce the problem?
```
❯ brew update
Already up-to-date.
```
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Check `brew doctor` for issues

## What happened (include command output)

```
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.
```
```
❯ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
```
❯ softwareupdate --list
Software Update Tool

Finding available software
No new software available.
```
  

  </pre>
</details>

## What you expected to happen

No warning about command line tools version since I have latest available version.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew doctor`

## Output of `brew config` and `brew doctor` commands
```
❯ brew config
HOMEBREW_VERSION: 2.2.0-49-g4a7ea6d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4a7ea6dbc4698c5c897ee667f19ed0127868bfb1
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: df7bdec3bf05a359433ff558e5541ac94c826850
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 9, 1.8.0_144
macOS: 10.15.1-x86_64
CLT: 1100.0.33.8
Xcode: 11.2.1
```

Related to #6576

**Comment by MikeMcQuaid** [comment]
> Update them from Software Update in System Preferences or
> https://developer.apple.com/download/more/.

**Comment by esetnik** [comment]
I tried to update them with software update in system preferences and it says no update available. The latest available version on https://developer.apple.com/download/more/ is already installed on my system.

![image](https://user-images.githubusercontent.com/664434/70156208-91be9500-1681-11ea-8106-b9da7e3a0233.png)

**Comment by MikeMcQuaid** [comment]
Try again to install that CLT 11.2 on your system.

**Comment by esetnik** [comment]
Reinstalling CLT 11.2 from apple resolved the issue. Thanks for the tip. Any idea why this is occurring?

**Comment by MikeMcQuaid** [comment]
You didn't have the latest version of the CLT so had to install a newer one.

**Comment by brainsik** [comment]
Thanks for opening this @esetnik. I was bitten by this along with some coworkers and we also are wondering why it suddenly was necessary to manually download that DMG.

For others following along, here's a link to the DMG, though you'll need to login to the developer site:
https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_11.2/Command_Line_Tools_for_Xcode_11.2.dmg

**Comment by MikeMcQuaid** [comment]
The best thing you can do is file bug reports (radars) with Apple.

**Comment by cluzier** [comment]
> Thanks for opening this @esetnik. I was bitten by this along with some coworkers and we also are wondering why it suddenly was necessary to manually download that DMG.
> 
> For others following along, here's a link to the DMG, though you'll need to login to the developer site:
> https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_11.2/Command_Line_Tools_for_Xcode_11.2.dmg

Ive got this issue as well, If this works I will update this.

**Comment by spilth** [comment]
I've been having this issue the last few days and had to manually download and install CLT 11.3.

Here's the direct link to 11.3: <https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_11.3/Command_Line_Tools_for_Xcode_11.3.dmg>
