### ISSUE TITLE
Provide a way to known the installed formula removed from homebrew-core

### ISSUE THREAD

**Issue by markwu** [Homebrew/brew#6815]
# A detailed description of the proposed feature

Provide a way to known the installed formula removed from homebrew-core.

# The motivation for the feature

Openssl(1.0.2t) removed from homebrew-core recently, and you also add openssl alias to openssl@1.1. It takes me 4-5 hours to find out why my php can't compiled. After remove my installed openssl and reinstall openssl@1.1, everything just works.

# How the feature would be relevant to at least 90% of Homebrew users

It's easier for us to know which installed formula removed by homebrew-core team when we need to debug.

**Comment by MikeMcQuaid** [comment]
> Provide a way to known the installed formula removed from homebrew-core.

This is output by `brew update`.

**Comment by markwu** [comment]
Nope, it only shows once. If I missed it, then I have no chance to see it again.

**Comment by MikeMcQuaid** [comment]
You can query it manually yourself beyond that using Git.

**Comment by markwu** [comment]
Yes, I can find this change in PR/github or git manually. But I have no idea how many this kind of messages I missed, That's why I request a way to find out these information and give me overall current installed formulas healthy information.
