### ISSUE TITLE
brew unable to update after installation on macOS Mojave

### ISSUE THREAD

**Issue by achekulaev** [Homebrew/brew#6819]
## What you were trying to do (and why)

1. macOS Mojave
2. Install brew with `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
3. `brew update`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
Updating Homebrew...
error: waitpid for config failed: No child processes
error: waitpid for gc failed: No child processes
  </pre>
</details>

## What you expected to happen

brew updated

## Output of `brew config` and `brew doctor` commands

<pre>
16:02:37 ~
§ brew config
HOMEBREW_VERSION: 2.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d7de295dfbc5e581106e2b1f674496b5e25a773
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 70ee7daeb9b6c8c82eee6edb2204a88f9b174820
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.2.1
CLT headers: 10.3.0.0.1.1562985497

16:09:08 ~
§ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
</pre>

## Comments

This issue seems related to https://github.com/Homebrew/brew/issues/3228
Looks like either something should be done to installer to automatically perform `sudo chown -R $(whoami) $(brew --prefix)/*` after installation, or this manual step should be added to installation steps.
Because otherwise `brew` seems unable to update until it is done.
After I performed it, it was fine:

```bash
16:02:05 ~
§ sudo chown -R $(whoami) $(brew --prefix)/*
Password:

16:02:32 ~
§ brew update
Already up-to-date.
```

**Comment by MikeMcQuaid** [comment]
This is an issue specific to you you'll need to figure out yourself. Please report similar issues to Discourse in future.

**Comment by achekulaev** [comment]
@MikeMcQuaid sorry you mean it's not a generic Mojave issue? Because I would expect it is.

**Comment by MikeMcQuaid** [comment]
> you mean it's not a generic Mojave issue?

It's not.

> Have you even read before closing?

Yes.
