### ISSUE TITLE
brew bump-formula-pr broken when given a path (regression)

### ISSUE THREAD

**Issue by fredemmott** [Homebrew/brew#6821]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Use `bump-formula-pr` to update the version number in https://github.com/hhvm/homebrew-hhvm/blob/master/Formula/hhvm-nightly.rb as part of the nightly builds for that project

## What happened (include command output)

```
Error: undefined method `full_name' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:104:in `use_correct_linux_tap'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:120:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

## What you expected to happen

Version number to be updated in www
## Step-by-step reproduction instructions (by running `brew` commands)

```
$ git clone https://github.com/hhvm/homebrew-hhvm.git
$ cd homebrew-hhvm
$ git checkout ad0dcd13cdcf51185203ecddf6055ad99ac33cf1 # 2019.12.05
$  brew bump-formula-pr --dry-run --write --url=https://dl.hhvm.com/source/nightlies/hhvm-nightly-2019.12.06.tar.gz --sha256=614f98c2073817729750634fadaab1dad2994603b686d58dbba74009979cb648 Formula/hhvm-nightly.rb
```

## Output of `brew config` and `brew doctor` commands

<pre>
fredemmott@fredemmott-mm1 homebrew-hhvm % brew config
HOMEBREW_VERSION: 2.2.0-65-g2b34c10-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b34c1055fce2609de3aa6ea28fc251c9d875485
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8875c0dbf15d89bd453603d58e27ef439dbaaf5f
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_VISUAL: nvim
CPU: hexa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.2
macOS: 10.15.1-x86_64
CLT: 1100.0.33.8
Xcode: N/A
</pre>

brew doctor is very spammy, output at https://gist.github.com/fredemmott/2b73a5dfbadf20c6d8972e0ba1e314b7

> Warning: You have uncommitted modifications to Homebrew.

This is just the hacky fix below.

**Comment by fredemmott** [comment]
Appears caused by f90612ccf0db03681dc6cbf6585cca5bc27b84b1

Potential dumb fix:

```
diff --git a/Library/Homebrew/dev-cmd/bump-formula-pr.rb b/Library/Homebrew/dev-cmd/bump-formula-pr.rb
index 278f7914b..cce9a0eb6 100644
--- a/Library/Homebrew/dev-cmd/bump-formula-pr.rb
+++ b/Library/Homebrew/dev-cmd/bump-formula-pr.rb
@@ -101,7 +101,7 @@ module Homebrew
         end
       end
     end
-    [formula.tap.full_name, "origin/master", "-"]
+    [formula.tap ? formula.tap.full_name : nil, "origin/master", "-"]
   end

   def bump_formula_pr
```

**Comment by fredemmott** [comment]
re f90612ccf0db03681dc6cbf6585cca5bc27b84b1

This case used to be handled by `tap = options[:tap] || CoreTap.instance` in `issues_for_formula`, but now that the `.tap` is read earlier to separately track tap name, that doesn't help

**Comment by dawidd6** [comment]
Can you revert Homebrew repo to the state before https://github.com/Homebrew/brew/commit/f90612ccf0db03681dc6cbf6585cca5bc27b84b1 commit and then check if it works?

**Comment by fredemmott** [comment]
>  ran brew doctor, fixed all issues and can still reproduce the problem?

Sorry, working on this; corporate system management is making it a bit painful. Hopefully the code pointers/diff are enough :)

> Can you revert Homebrew repo to the state before f90612c commit and then check if it works?

For my reference, this needs `export HOMEBREW_NO_AUTO_UPDATE=1`

```
% cd /usr/local/Homebrew/library
% git checkout f90612ccf0db03681dc6cbf6585cca5bc27b84b1^
% git rev-parse HEAD
e2c76cce8e01fd80e0910ddbf8d03092d8753673
% <repo steps> # works fine
% git checkout f90612ccf0db03681dc6cbf6585cca5bc27b84b1
% <repo steps> # fails with: Error: undefined method `full_name' for nil:NilClass
```

**Comment by dawidd6** [comment]
Please submit a PR if the fix you attached above works.
