### ISSUE TITLE
No Command Line Feedback

### ISSUE THREAD

**Issue by pBread** [Homebrew/brew#6823]
# A detailed description of the proposed feature
`brew update` provides no command line feedback on initialization. There should be a log like... `brew update initiated`

# The motivation for the feature
Users don't know if the process has kicked off or not. I was in a low-bandwidth area & had no feedback for at least a minute.

# How the feature would be relevant to at least 90% of Homebrew users
90% of Homebrew users use Homebrew sparsely. I immediately thought "oh, maybe Homebrew sucks now."

# What alternatives to the feature have been considered

**Comment by jonchang** [comment]
You can run `brew update --verbose` which should give you more feedback.
