### ISSUE TITLE
filter .pyc messages out of sandbox log

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/brew#683]
_From @tdsmith on January 3, 2016 18:51_

Messages of the form `.*Python(\d+) deny file-write-create.*pyc` are just noise and aren't fatal; it would be nice to hide them from the sandbox log summary.

_Copied from original issue: Homebrew/legacy-homebrew#47640_

**Comment by tdsmith** [comment]
_From @MikeMcQuaid on January 3, 2016 18:57_

:+1:

**Comment by tdsmith** [comment]
_From @DomT4 on January 3, 2016 19:1_

No objections.

**Comment by tdsmith** [comment]
_From @bfontaine on January 3, 2016 19:59_

We could maybe set `ENV["PYTHONDONTWRITEBYTECODE"] = "1"` to avoid that?

**Comment by tdsmith** [comment]
Either way; filtering has a small risk of filtering out messages we actually care about and setting `PYTHONDONTWRITEBYTECODE` doesn't. Morally, filtering feels a little better because it doesn't change the behavior of the interpreter for the test, but that seems like an unlikely source of bugs.

**Comment by tdsmith** [comment]
_From @MikeMcQuaid on January 3, 2016 21:21_

> We could maybe set ENV["PYTHONDONTWRITEBYTECODE"] = "1" to avoid that?

:+1:

**Comment by tdsmith** [comment]
_From @MikeMcQuaid on August 10, 2016 9:18_

If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.

**Comment by MikeMcQuaid** [comment]
Repeating myself from https://github.com/Homebrew/brew/issues/680:

@tdsmith Are you currently actively working on this?
