### ISSUE TITLE
Brew hangs when detecting clang version (check_for_installed_developer_tools)

### ISSUE THREAD

**Issue by koliyo** [Homebrew/brew#6845]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
No, brew doctor hangs
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?
No brew config hangs

## What you were trying to do (and why)
I want to run brew upgrade, but it hangs.

## What happened (include command output)

`brew upgrade` hangs, `brew doctor` hangs, and `brew config` also hangs.

See output below:

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew doctor --debug --verbose
==> Checking check_access_directories
==> Checking check_brew_git_origin
==> Checking check_casktap_git_origin
==> Checking check_clt_minimum_version
==> Checking check_clt_up_to_date
==> Checking check_coretap_git_branch
==> Checking check_coretap_git_origin
==> Checking check_deprecated_official_taps
==> Checking check_exist_directories
==> Checking check_filesystem_case_sensitive
==> Checking check_for_anaconda
==> Checking check_for_bad_python_symlink
==> Checking check_for_bitdefender
==> Checking check_for_config_scripts
==> Checking check_for_external_cmd_name_conflict
==> Checking check_for_gettext
==> Checking check_for_git
==> Checking check_for_iconv
==> Checking check_for_installed_developer_tools
</pre>

`brew config` hangs here
<pre>
$ brew config
HOMEBREW_VERSION: 2.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2fe99bd9823fadea1cf918b1ed8366de7f40d336
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0ec3228bd07c5f35294d4c1b36d6160980823a21
Core tap last commit: 42 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 3600
HOMEBREW_GITHUB_API_TOKEN: set
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang:
</pre>

This is a brand new MacBook with MacOS 10.15.1. NOTE: I have not installed XCode, only command line tools.

**Comment by koliyo** [comment]
Exactly the same issue as https://github.com/Homebrew/legacy-homebrew/issues/16964

Can work around it by killing `mdfind` explicitly.

**Comment by MikeMcQuaid** [comment]
> Can work around it by killing `mdfind` explicitly.

It is expected that it will wait for `mdfind` to complete.
