### ISSUE TITLE
Can install brew

### ISSUE THREAD

**Issue by Halpmewithdis** [Homebrew/brew#6847]
When i install brew it says HEAD is now at 4973f6707 Merge pull request #6844 from MikeMcQuaid/download_strategy_typeerror

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
