### ISSUE TITLE
Traceback  error in all Homebrew's commands

### ISSUE THREAD

**Issue by hernimen** [Homebrew/brew#6854]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing the newest version of homebrew in **Macosx Catalina 10.15** . Can't install homebrew !
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

## What happened (include command output)

`==> Downloading and installing Homebrew...
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 129957 (delta 35), reused 47 (delta 29), pack-reused 129878
Receiving objects: 100% (129957/129957), 31.08 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (95356/95356), done.
From https://github.com/Homebrew/brew

[new branch] master -> origin/master
[new tag] 0.1 -> 0.1
[new tag] 0.2 -> 0.2
[new tag] 0.3 -> 0.3
[new tag] 0.4 -> 0.4
[new tag] 0.5 -> 0.5
[new tag] 0.6 -> 0.6
[new tag] 0.7 -> 0.7
[new tag] 0.7.1 -> 0.7.1
[new tag] 0.8 -> 0.8
[new tag] 0.8.1 -> 0.8.1
[new tag] 0.9 -> 0.9
[new tag] 0.9.1 -> 0.9.1
[new tag] 0.9.2 -> 0.9.2
[new tag] 0.9.3 -> 0.9.3
[new tag] 0.9.4 -> 0.9.4
[new tag] 0.9.5 -> 0.9.5
[new tag] 0.9.8 -> 0.9.8
[new tag] 0.9.9 -> 0.9.9
[new tag] 1.0.0 -> 1.0.0
[new tag] 1.0.1 -> 1.0.1
[new tag] 1.0.2 -> 1.0.2
[new tag] 1.0.3 -> 1.0.3
[new tag] 1.0.4 -> 1.0.4
[new tag] 1.0.5 -> 1.0.5
[new tag] 1.0.6 -> 1.0.6
[new tag] 1.0.7 -> 1.0.7
[new tag] 1.0.8 -> 1.0.8
[new tag] 1.0.9 -> 1.0.9
[new tag] 1.1.0 -> 1.1.0
[new tag] 1.1.1 -> 1.1.1
[new tag] 1.1.10 -> 1.1.10
[new tag] 1.1.11 -> 1.1.11
[new tag] 1.1.12 -> 1.1.12
[new tag] 1.1.13 -> 1.1.13
[new tag] 1.1.2 -> 1.1.2
[new tag] 1.1.3 -> 1.1.3
[new tag] 1.1.4 -> 1.1.4
[new tag] 1.1.5 -> 1.1.5
[new tag] 1.1.6 -> 1.1.6
[new tag] 1.1.7 -> 1.1.7
[new tag] 1.1.8 -> 1.1.8
[new tag] 1.1.9 -> 1.1.9
[new tag] 1.2.0 -> 1.2.0
[new tag] 1.2.1 -> 1.2.1
[new tag] 1.2.2 -> 1.2.2
[new tag] 1.2.3 -> 1.2.3
[new tag] 1.2.4 -> 1.2.4
[new tag] 1.2.5 -> 1.2.5
[new tag] 1.2.6 -> 1.2.6
[new tag] 1.3.0 -> 1.3.0
[new tag] 1.3.1 -> 1.3.1
[new tag] 1.3.2 -> 1.3.2
[new tag] 1.3.3 -> 1.3.3
[new tag] 1.3.4 -> 1.3.4
[new tag] 1.3.5 -> 1.3.5
[new tag] 1.3.6 -> 1.3.6
[new tag] 1.3.7 -> 1.3.7
[new tag] 1.3.8 -> 1.3.8
[new tag] 1.3.9 -> 1.3.9
[new tag] 1.4.0 -> 1.4.0
[new tag] 1.4.1 -> 1.4.1
[new tag] 1.4.2 -> 1.4.2
[new tag] 1.4.3 -> 1.4.3
[new tag] 1.5.0 -> 1.5.0
[new tag] 1.5.1 -> 1.5.1
[new tag] 1.5.10 -> 1.5.10
[new tag] 1.5.11 -> 1.5.11
[new tag] 1.5.12 -> 1.5.12
[new tag] 1.5.13 -> 1.5.13
[new tag] 1.5.14 -> 1.5.14
[new tag] 1.5.2 -> 1.5.2
[new tag] 1.5.3 -> 1.5.3
[new tag] 1.5.4 -> 1.5.4
[new tag] 1.5.5 -> 1.5.5
[new tag] 1.5.6 -> 1.5.6
[new tag] 1.5.7 -> 1.5.7
[new tag] 1.5.8 -> 1.5.8
[new tag] 1.5.9 -> 1.5.9
[new tag] 1.6.0 -> 1.6.0
[new tag] 1.6.1 -> 1.6.1
[new tag] 1.6.10 -> 1.6.10
[new tag] 1.6.11 -> 1.6.11
[new tag] 1.6.12 -> 1.6.12
[new tag] 1.6.13 -> 1.6.13
[new tag] 1.6.14 -> 1.6.14
[new tag] 1.6.15 -> 1.6.15
[new tag] 1.6.16 -> 1.6.16
[new tag] 1.6.17 -> 1.6.17
[new tag] 1.6.2 -> 1.6.2
[new tag] 1.6.3 -> 1.6.3
[new tag] 1.6.4 -> 1.6.4
[new tag] 1.6.5 -> 1.6.5
[new tag] 1.6.6 -> 1.6.6
[new tag] 1.6.7 -> 1.6.7
[new tag] 1.6.8 -> 1.6.8
[new tag] 1.6.9 -> 1.6.9
[new tag] 1.7.0 -> 1.7.0
[new tag] 1.7.1 -> 1.7.1
[new tag] 1.7.2 -> 1.7.2
[new tag] 1.7.3 -> 1.7.3
[new tag] 1.7.4 -> 1.7.4
[new tag] 1.7.5 -> 1.7.5
[new tag] 1.7.6 -> 1.7.6
[new tag] 1.7.7 -> 1.7.7
[new tag] 1.8.0 -> 1.8.0
[new tag] 1.8.1 -> 1.8.1
[new tag] 1.8.2 -> 1.8.2
[new tag] 1.8.3 -> 1.8.3
[new tag] 1.8.4 -> 1.8.4
[new tag] 1.8.5 -> 1.8.5
[new tag] 1.8.6 -> 1.8.6
[new tag] 1.9.0 -> 1.9.0
[new tag] 1.9.1 -> 1.9.1
[new tag] 1.9.2 -> 1.9.2
[new tag] 1.9.3 -> 1.9.3
[new tag] 2.0.0 -> 2.0.0
[new tag] 2.0.1 -> 2.0.1
[new tag] 2.0.2 -> 2.0.2
[new tag] 2.0.3 -> 2.0.3
[new tag] 2.0.4 -> 2.0.4
[new tag] 2.0.5 -> 2.0.5
[new tag] 2.0.6 -> 2.0.6
[new tag] 2.1.0 -> 2.1.0
[new tag] 2.1.1 -> 2.1.1
[new tag] 2.1.10 -> 2.1.10
[new tag] 2.1.11 -> 2.1.11
[new tag] 2.1.12 -> 2.1.12
[new tag] 2.1.13 -> 2.1.13
[new tag] 2.1.14 -> 2.1.14
[new tag] 2.1.15 -> 2.1.15
[new tag] 2.1.16 -> 2.1.16
[new tag] 2.1.2 -> 2.1.2
[new tag] 2.1.3 -> 2.1.3
[new tag] 2.1.4 -> 2.1.4
[new tag] 2.1.5 -> 2.1.5
[new tag] 2.1.6 -> 2.1.6
[new tag] 2.1.7 -> 2.1.7
[new tag] 2.1.8 -> 2.1.8
[new tag] 2.1.9 -> 2.1.9
[new tag] 2.2.0 -> 2.2.0
[new tag] 2.2.1 -> 2.2.1
HEAD is now at 2749c52 Merge pull request #6840 from GauthamGoli/argv-cleanup-6
Traceback (most recent call last):
9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in <main>' 8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in require_relative'
7: from /usr/local/Homebrew/Library/Homebrew/global.rb:109:in <top (required)>' 6: from /usr/local/Homebrew/Library/Homebrew/global.rb:109:in new'
5: from /usr/local/Homebrew/Library/Homebrew/PATH.rb:10:in initialize' 4: from /usr/local/Homebrew/Library/Homebrew/PATH.rb:73:in parse'
3: from /usr/local/Homebrew/Library/Homebrew/PATH.rb:73:in flat_map' 2: from /usr/local/Homebrew/Library/Homebrew/PATH.rb:73:in each'
1: from /usr/local/Homebrew/Library/Homebrew/PATH.rb:73:in block in parse' /usr/local/Homebrew/Library/Homebrew/PATH.rb:73:in split': invalid byte sequence in UTF-8 (ArgumentError)
Failed during: /usr/local/bin/brew update --force
I had run **brew update-reset** and **brew cleanup** and every command that brew has,  but I always get the same error

**Comment by MikeMcQuaid** [comment]
You'll need to adjust your `PATH` so it doesn't contain the `invalid byte sequence`

**Comment by hernimen** [comment]
@mikejs How do I do this? Can you explain? nothing seems to work. Thanks
