### ISSUE TITLE
Some sub commands / options giving wrong output. 

### ISSUE THREAD

**Issue by wangyandong-ningxia** [Homebrew/brew#6861]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

```brew --version```
```brew --prefix```

Try to fix some issues reported by ```brew doctor```:
```brew untap Homebrew/homebrew-versions```
```brew uninstall universal-ctags```

## What happened (include command output)

These commands give the the output ```brew Version```.

<details>
  <summary>Command output</summary>
  <pre>

wangyandong@iMac ~
» brew --version
brew Version
wangyandong@iMac ~
» brew --prefix
brew Version
wangyandong@iMac ~
» brew uninstall universal-ctags
brew Version
wangyandong@iMac ~
» brew untap Homebrew/homebrew-versions
brew Version
wangyandong@iMac ~
»
  </pre>
</details>

## What you expected to happen

```brew update```,```brew upgrade```,```brew info```,```brew install``` work fine, and other commands should do the right thing.

## Step-by-step reproduction instructions (by running `brew` commands)

```
wangyandong@iMac ~
» brew --version
brew Version
wangyandong@iMac ~
» brew --prefix
brew Version
wangyandong@iMac ~
» brew uninstall universal-ctags
brew Version
wangyandong@iMac ~
» brew untap Homebrew/homebrew-versions
brew Version
wangyandong@iMac ~
»
```
## Output of `brew config` and `brew doctor` commands

<pre>
» brew config
HOMEBREW_VERSION: 2.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2fe99bd9823fadea1cf918b1ed8366de7f40d336
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: e10d306105b4dcaf80587637b14f180751a385a9
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_GITHUB_API: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.1, 1.8.0_73
macOS: 10.15.1-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: 11.3
CLT headers: 11.0.0.0.1.1567737322
XQuartz: 2.7.11 => /opt/X11

» brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-versions
Untap them with `brew untap`.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ctags
</pre>

**Comment by MikeMcQuaid** [comment]
Closing this because I can't reproduce it.

Try to run `brew --version --debug --verbose`. What's the output of `which brew`?

**Comment by EricFromCanada** [comment]
I have found that if you add `--version` to an arbitrary `brew` command that doesn't handle it, Ruby's optparse kicks in:
```
$ brew info --version
brew Version
$ brew doctor --version
brew Version
$ brew --version
Homebrew 2.2.1-76-gaf98c15
Homebrew/homebrew-core (git revision 1d8285; last commit 2019-12-20)
Homebrew/homebrew-cask (git revision 87ef3; last commit 2019-12-20)
$ brew --version --version
brew Version
```

**Comment by wangyandong-ningxia** [comment]
Thanks. I've reinstalled homebrew and it works again.
