### ISSUE TITLE
Suggestion: Ask before installing breaking changes.

### ISSUE THREAD

**Issue by JonRowe** [Homebrew/brew#6868]
Moved from: Homebrew/homebrew-core#48259

# A detailed description of the proposed feature

If homebrew formulas had a "ask before upgrade" flag, then packages which are known to not upgrade smoothly could warn the user about this and ask for confirmation before installing. This is especially useful when a user is not aware a package is being upgraded.

e.g.
```
$> brew upgrade package_y
WARNING: 
This upgrade requires manual intervention to succeed are you sure you wish to continue?
[y/n]

$> brew upgrade package_x
WARNING: package_x will upgrade package y
This upgrade requires manual intervention to succeed are you sure you wish to continue?
[y/n]
```

# The motivation for the feature

I performed `brew upgrade numpy` today which upgraded my postgres from 11 to 12, (postgres upgrades always being problematic) without my knowledge, requiring me to spend 2 hours digging around manually to get a working postgres install again.

# How the feature would be relevant to at least 90% of Homebrew users

Postgres is a pretty popular package, its upgrades always require manual intervention and often more than just `brew postgresql-upgrade-database`, I'm sure there are other similar packages which should not be upgraded in the background. People expect `brew upgrade package_y` to not break other package installs...

# What alternatives to the feature have been considered

An alternative would be to explain the upgrade like apt-get does, this would allow someone to see "hey thats going to upgrade postgres and that will break for me" and stop the upgrade. 

---

I actually consider this a bug, (hence why I originally opened it on homebrew-core) doing a `brew update package_x` should not break my package_y install, I know upgrades can't always be provided cleanly but if you at least ask before upgrading something in the background.

**Comment by dawidd6** [comment]
You can use `brew pin FORMULA`, so it won't be updated without your explicit permission.

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/pin.rb#L12-L15

**Comment by JonRowe** [comment]
Thanks for the tip, so theres already half the implementation there then, if the pin logic was usable on a forumla basis rather than user then it could prevent this situation for other people.

**Comment by iMichka** [comment]
If I remember well, `brew pin` is there if you know what you do. It's a little bit experimental and may break stuff in the long run. We won't support any breakages related to pinned formulae (there may be untested side-effects not under our control).

Also, you could use `brew outdated` to know which packages will be upgraded.

**Comment by JonRowe** [comment]
> Also, you could use brew outdated to know which packages will be upgraded.

I had used `brew outdated` but I requested a specific package to be updated and other packages were then updated without my permission, that is at least "surprising" behaviour... 

To compound matters an auto clean then removed the older packages required to upgrade the postgres database forcing me to manually build packages to restore the database.

All of this could be avoided by having a way of marking packages as dangerous to upgrade and having a confirmation prompt. (I do keep postgres up to date, I just do it when I know I have the time to deal with it) or by having `brew upgrade n` confirm what it's going to upgrade before doing it when there is more than just the requested package requested. 

Thank you for your hard work it is appreciated, I just don't want this dismissed as "user error" when its unexpected behaviour...

Happy Holidays!

**Comment by MikeMcQuaid** [comment]
> People expect `brew upgrade package_y` to not break other package installs...

This is why your `postgresql` was upgraded: without doing so it would have been broken.

Homebrew is a rolling-release package manager: we assume you will `brew pin` or use `@` versioned formulae if you need a specific version.

> All of this could be avoided by having a way of marking packages as dangerous to upgrade and having a confirmation prompt.

`brew pin`.

> `brew upgrade n` confirm what it's going to upgrade before doing it when there is more than just the requested package requested.

`brew upgrade --dry-run`.

---

I'm open to other solutions but not one that involves an interactive prompt as Homebrew doesn't use these. This probably would need to be a PR rather than an issue as, even as described, it's not clear how you'd implement the code to decide that this is the case and without having loads of noisy, false negatives.

Happy Christmas!
