### ISSUE TITLE
brew stopped updating taps

### ISSUE THREAD

**Issue by okket** [Homebrew/brew#688]
Tested on several machines:

```
→ brew update
Already up-to-date.
```

```
→ brew info offline-imap
offlineimap: stable 7.0.4 (bottled), HEAD
[...]
```

Current version in the `homebrew-core` tap is 7.0.5

**Comment by MikeMcQuaid** [comment]
@okket Pushed a fix in 985c672bac4dc20d369b451c484eb6553762dbcf. Can you see if that running `brew update` (without any manual `git` commands) correctly updates the taps now? Thanks!

**Comment by okket** [comment]
I imported the commit into a fresh branch

```
→ git merge 985c672bac4dc20d369b451c484eb6553762dbcf
Updating 06fe347..985c672
Fast-forward
 Library/Homebrew/cmd/outdated.rb |  7 ++++---
 Library/Homebrew/cmd/update.sh   | 15 +++++++++------
 Library/Homebrew/cmd/upgrade.rb  |  7 ++++---
 share/doc/homebrew/brew.1.html   | 14 ++++++++------
 share/man/man1/brew.1            |  4 ++--
 5 files changed, 27 insertions(+), 20 deletions(-)
```
and it seems to work:

```
→ brew update
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
gor        libphonenumber        micropython        offlineimap
```

**Comment by MikeMcQuaid** [comment]
Great, thanks. That fixes the problem but now anyone who updated in between will be stuck in a limbo I need to figure out how to get them out of 😭

**Comment by okket** [comment]
Great, thanks for the quick fix!

I guess the problem is that a `brew update` won't even update brew itself without this? I had to `git pull` in `/usr/local/` manually to get homebrew working again on another machine. Or is this unrelated?

**Comment by MikeMcQuaid** [comment]
> I guess the problem is that a brew update won't even update brew itself without this? I had to git pull in /usr/local/ manually to get homebrew working again on another machine. Or is this unrelated?

Yes, this is the (big) problem. There's no code fix that can address that, it'll need to be just communicated that anyone who updated in that 20 hour period will have to manually intervene as you have :sob.

**Comment by proski** [comment]
I just thought somebody went on vacation :)

Would it be possible to put the instructions to get unstuck on brew.sh? I tried the installer. It suggested that I uninstall Homebrew first. I ran the uninstaller as suggested, then the installer, and it looks like I need to reinstall all packages now.

**Comment by MikeMcQuaid** [comment]
@proski That's something we'll consider if this keeps cropping up, thanks!

**Comment by fuzzy76** [comment]
I think you need to do something, this one bit me.

**Comment by MikeMcQuaid** [comment]
@fuzzy76 I think you need to read this thread and understand that we've done all we can do.

**Comment by fuzzy76** [comment]
I found #706 which explained that you had done all you could do. So yes. :)
