### ISSUE TITLE
`brew upgrade elang --dry-run` list of actions is incomplete

### ISSUE THREAD

**Issue by JonRowe** [Homebrew/brew#6883]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew upgrade erlang --dry-run`

To see what upgrading erlang would do before ugprading it.

## What happened (include command output)

`brew upgrade erlang --dry-run`

Indicated it would upgrade erlang to OTP 22.2 as expected.

`brew upgrade erlang`

Then upgraded erlang and elixir. (From 1.9.1 to 1.9.4).

## What you expected to happen

I expected `brew upgrade erlang --dry-run` to output a complete list of packages it would upgrade.

## Output of `brew config` and `brew doctor` commands

<details>
  <summary>brew config</summary>
  <pre>
HOMEBREW_VERSION: 2.2.2-32-g53bb918-dirty
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 53bb918565b4ec545d66403a0aa763dc11e76f5f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6fcb18732bc4bd8a2c2d33569f66767d9286f41b
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BREW_GIT_REMOTE: https://github.com/Homebrew/brew
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_51
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3
XQuartz: 2.7.8 => /opt/X11
  </pre>
</details>

<details>
  <summary>brew doctor</summary>
  <pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-versions
Untap them with `brew untap`.

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libimobiledevice.4.dylib
  /usr/local/lib/libplist.3.dylib
  /usr/local/lib/libusbmuxd.4.dylib
  /usr/local/lib/libwkhtmltox.0.12.4.dylib
  /usr/local/lib/libxml2.2.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/liblwgeom.la

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  proj@11
  openssl098
  libmpc@0.8
  isl@0.11
  numpy
  mpfr@2
  gmp@4
  cloog@0.15
  ppl@0.11
  bfg
  node
  unbound

Warning: Some installed formulae are not readable:
  qt@5.5: unknown version :mountain_lion

  phantomjs: uninitialized constant #<Class:0x00007ffc91ca4dc0>::MinimumMacOSRequirement

Warning: You have uncommitted modifications to Homebrew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library && git stash && git clean -d -f

Warning: Your XQuartz (2.7.8) is outdated.
Please install XQuartz 2.7.11 (or delete the current version).
XQuartz can be updated using Homebrew Cask by running:
  brew cask reinstall xquartz
  </pre>
</details>

**Comment by MikeMcQuaid** [comment]
> elixir. (From 1.9.1 to 1.9.4).

This was upgraded as otherwise it would have been broken by the Erlang upgrade.

**Comment by JonRowe** [comment]
> This was upgraded as otherwise it would have been broken by the Erlang upgrade.
The issue is that `--dry-run` did not inform me that it was needed

**Comment by MikeMcQuaid** [comment]
I've opened https://github.com/Homebrew/brew/pull/6885 to tweak this behaviour. Note the list cannot be fully complete (and prints a warning accordingly) because we do not know what will result in broken linkage after an upgrade. This will print a more complete list than currently, however, and will handle your case.

**Comment by JonRowe** [comment]
Might you consider also warning about packages that may be upgraded if they are broken? I'm not sure if #6885 does that too?

**Comment by MikeMcQuaid** [comment]
It does.
