### ISSUE TITLE
Quadratic behaviour in `brew upgrade`

### ISSUE THREAD

**Issue by tomsmeding** [Homebrew/brew#6888]
# A detailed description of the proposed feature

`brew upgrade` currently exhibits quadratic behaviour, because to check dependents of upgraded formulae, brew loops over all installed formulae for each upgraded formula. As a result, the post-upgrade step indicated by `Checking for dependents of upgraded formulae...` can take a very long time (>~10min) on well-used systems.

This check can be rewritten to perform only one pass over the installed packages: this pass would accumulate a hashmap, mapping each formula to a hashset of its dependent formulae. Using this hashmap, the remaining work is linear in the upgraded formulae and their dependencies.

# The motivation for the feature

`brew upgrade` currently has a very slow postprocessing stage, as explained above.

# How the feature would be relevant to at least 90% of Homebrew users

Performance optimisations are relevent, I believe.

# What alternatives to the feature have been considered

A performance optimisation is not strictly necessary for anything, but it is nice-to-have. I'm not sure what alternatives would be, preserving existing functionality.

**Comment by MikeMcQuaid** [comment]
See https://github.com/Homebrew/brew/pull/6698: these are already cached using several hashes based on profiling. The behaviour being quadratic is somewhat irrelevant because the expensive operations are cached.

I'm open to accepting pull requests to improve this.
