### ISSUE TITLE
Vagrant installs with wrong permissions in /opt.

### ISSUE THREAD

**Issue by Oddly** [Homebrew/brew#6891]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I installed vagrant and wanted to do "vagrant up" after this.

## What happened (include command output)

"vagrant up" gave me an error. 

<details>
  <summary>Command output</summary>
  <pre>
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
</pre>
</details>

## What you expected to happen

Vagrant up should just run. Everything is installed as needed.
Upon investigation, it seems that vagrant installs in the /opt directory with root:wheel permissions. Running chown -R user:group /opt/vagrant resolves the issue.
After this, there is no error and vagrant works as expected.

## Step-by-step reproduction instructions (by running `brew` commands)

<pre>
$ brew cask install vagrant
$ vagrant up
</pre>

## Output of `brew config` and `brew doctor` commands
brew config:
<pre>
Clang: 11.0 build 1100
Git: 2.24.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.2-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: N/A
samcrauwels@LinuxBook-Pro /opt % brew config
HOMEBREW_VERSION: 2.2.2-34-g7aacca3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7aacca366ab3798249927132907b03848af38748
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 57443e9285b521de15c498b6dce1fd519eb785c3
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BREW_GIT_REMOTE: https://github.com/Homebrew/brew
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.2-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: N/A
</pre>

brew doctor:
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.
</pre>

**Comment by Oddly** [comment]
Sorry, this Issue is no longer an issue. Can be closed,

**Comment by MikeMcQuaid** [comment]
For future reference this was the wrong repository for this.
