### ISSUE TITLE
Ruby-related error in 'require' while using standard brew commands

### ISSUE THREAD

**Issue by Alessi0X** [Homebrew/brew#6893]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to run `brew outdated` to check outdated formulas for upgrade.

## What happened (include command output)

This is the resulting output.

<details>
  <summary>Command output</summary>
  <pre>

  Traceback (most recent call last):
	19: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	17: from /usr/local/Homebrew/Library/Homebrew/global.rb:152:in `<top (required)>'
	16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /usr/local/Homebrew/Library/Homebrew/tap.rb:4:in `<top (required)>'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /usr/local/Homebrew/Library/Homebrew/readall.rb:3:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:13:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Homebrew/Library/Homebrew/software_spec.rb:8:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:4:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dependencies (LoadError)

  </pre>
</details>

## What you expected to happen

List outdated formulas.

## Step-by-step reproduction instructions (by running `brew` commands)

Just run `brew outdated` and the error appears.
I tried also `brew update-reset` and a lot of `error: unable to read sha1 file` errors appear.
Running `brew update` says everything's up to date after running `brew update-reset`. After some time it returns
`error: Could not read dc0492178d710889bb28cee91006232eed6061f7
fatal: unresolved deltas left after unpacking
fatal: unpack-objects failed
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!`
along with the ruby traceback below.

## Output of `brew config` and `brew doctor` commands

Both of them return this output.

<pre>
Traceback (most recent call last):
	19: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	17: from /usr/local/Homebrew/Library/Homebrew/global.rb:152:in `<top (required)>'
	16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /usr/local/Homebrew/Library/Homebrew/tap.rb:4:in `<top (required)>'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /usr/local/Homebrew/Library/Homebrew/readall.rb:3:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:13:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Homebrew/Library/Homebrew/software_spec.rb:8:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:4:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dependencies (LoadError)
</pre>

**Comment by MikeMcQuaid** [comment]
> I tried also `brew update-reset` and a lot of `error: unable to read sha1 file` errors appear.
> Running `brew update` says everything's up to date after running `brew update-reset`. After some time it returns
> `error: Could not read dc0492178d710889bb28cee91006232eed6061f7 fatal: unresolved deltas left after unpacking fatal: unpack-objects failed Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!`
> along with the ruby traceback below.

You have issues with your Git repositories. You'll need to figure this out yourself. It may involve uninstalling and reinstalling Homebrew.
