### ISSUE TITLE
Homebrew install fails with 'unable to read sha1 file' errors

### ISSUE THREAD

**Issue by Alessi0X** [Homebrew/brew#6897]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install Homebrew

## What happened (include command output)

The install fails for some git-related (I think) errors. After running the install command on brew.sh, the following output appears

<details>
  <summary>Command output</summary>
  <pre>

  ==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /Users/USER/Library/Caches/Homebrew
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /Users/USER/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown USER /Users/USER/Library/Caches/Homebrew
==> Downloading and installing Homebrew...
error: unable to read sha1 file of Library/Homebrew/cmd/deps.rb (b7f21155bdc36c8cc119f36292b31201267551ed)
error: unable to read sha1 file of Library/Homebrew/dependencies.rb (1431ec2507b3b44a9e720d8a66928d7e2f4c0941)
error: unable to create file Library/Homebrew/dev-cmd/linkage.rb: No such file or directory
error: unable to read sha1 file of Library/Homebrew/formula_installer.rb (c2abe1ef56d6528224b51bb4070d33cbea288edf)
error: unable to create file Library/Homebrew/test/ARGV_spec.rb: No such file or directory
fatal: Could not reset index file to revision 'origin/master'.
Failed during: git reset --hard origin/master

  </pre>
</details>

## What you expected to happen

Succesfull homebrew installation.

## Step-by-step reproduction instructions (by running `brew` commands)

Simply `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

## Output of `brew config` and `brew doctor` commands
Not applicable.
<pre>

</pre>

**Comment by MikeMcQuaid** [comment]
You'll need to figure this out yourself, it's not reproducible.
