### ISSUE TITLE
brew export and brew import

### ISSUE THREAD

**Issue by voxsim** [Homebrew/brew#690]
I know that I should open a pull request, but first i want to understand if it already exists.

Is it possible to export which packages are installed on a machine via brew?

This would be useful if I want to uninstall and reinstall some packages on the same machine.
I thought that could be similar to the Gemfile.lock or Composer.lock, where I have the list of gems or php packages with specified a version per project.

Is there something that already do that stuff or it would be useful if I try to code that and make a pull request?

thanks in advance,
voxsim

**Comment by MikeMcQuaid** [comment]
> Is it possible to export which packages are installed on a machine via brew?

`brew bundle dump` handles this!

**Comment by voxsim** [comment]
thanks!

**Comment by voxsim** [comment]
@MikeMcQuaid I generated the file but it misses every version, is it possible to specify one in some way?

I understand this note:
```
Homebrew does not support installing specific versions of a library, only the most recent one, so there is no good mechanism for storing installed versions in a .lock file.

If your software needs specific versions then perhaps you'll want to look at using Vagrant to better match your development and production environments.
```

But the problem arises just from vagrant that has an issue in the last version and I am running the last version of homebrew.

Maybe I should open an issue in https://github.com/Homebrew/homebrew-bundle, sorry to bother you.

**Comment by MikeMcQuaid** [comment]
> But the problem arises just from vagrant that has an issue in the last version and I am running the last version of homebrew which supports the versions if I understand correctly.

Your best bet in that case is to consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) with an old version of `vagrant`.

**Comment by voxsim** [comment]
ok thanks for the help
