### ISSUE TITLE
Consent for GitHub credentials

### ISSUE THREAD

**Issue by ryanccn** [Homebrew/brew#6900]
# A detailed description of the proposed feature

Can there be a consent window for using the GitHub credentials stored in the macOS keychain first before you fetch it?

Reference [this function](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github.rb#L101) for how Homebrew gets the credentials (without consent).

# The motivation for the feature

I did not know that my GitHub credentials were being used to access the GitHub API to search for formulae and casks on Homebrew.

# How the feature would be relevant to at least 90% of Homebrew users

Most people who uses Homebrew use GitHub and have their GitHub credentials stored in the macOS keychain.

**Comment by MikeMcQuaid** [comment]
Sorry, requiring consent for this will mean that this functionality is less likely to "Just Work". We'd review and consider accepting a PR to opt-out of this behaviour.  See https://github.com/Homebrew/brew/issues/6862 for related work.
