### ISSUE TITLE
Package Manifest - Auto Install/Upgrade & More

### ISSUE THREAD

**Issue by thejeff77** [Homebrew/brew#6925]
# A detailed description of the proposed feature

I'd love to see a brew.json or brew manifest file option of some sort available for brew.  This would be very similar to the package.json file for npm.

I know that brew installs are usually global for the system, however having a file like this would be amazing for the following use case:

As a developer creating programs in tracked repositories, there are a large amount of dependencies that are required to be installed by brew for the app to work and function properly. I'd like to be able to run "brew install" in the same directory as the manifest file and have brew do the following: A) Check if each package is installed already B) update/skip/install the package per the manifest C) Get a convenient summary at the end - this is helpful over writing a script because I can have a once-over visual if everything worked, or if anything failed and scrolling back over all of the output is required.  

I'd also like warnings if there are newer packages available but the manifest isn't configured to upgrade to that version.

Possible options:

- compact (least amount of output -> shows console loading bars instead of detailed brew output (unless there are errors or warnings))

- version specification with common operators (~, >, <, etc..)

- auto-upgrade: <true/false> (auto - upgrade the package if a new one is available - default to true.)

- stop-on-fail: stop installing packages if there is any failure  (harder to script in bash, but very useful).  (also stop-on-warning might be useful)

- logfile: Will also output the result to a log along with any errors or warnings. 

- manifestDescription: "This manifest is for installing dependencies for the <appname> development environment"    - I.E. required brew packages documentation is the manifest! 

# The motivation for the feature

Having setup scripts with friendly output can be much larger than scripts just installing brew packages. If you want to fail on error or anything this requires more scripting and it is harder to maintain across teams with varying levels of scripting skills.

Furthermore, separate scripts are needed to upgrade packages or check for upgrades to all packages. 

large lists of brew installs in a script results in a lot of output parsing to even know if everything was successful, unless you've manually coded up a fail on error so the script stops installing on the first brew install failure. 

Always writing up brew dependencies on wikis - this is cumbersome and a manifest file would be sooo much better 👍 

# How the feature would be relevant to at least 90% of Homebrew users

- Developers could more easily scale setup of local macs.
- Normal users could share a manifest to help their friend install required packages.
- Could be used as a troubleshooting mechanism - can post log output, and manifest.
- Users or companies could template manifests for different purposes in public template docs - install all of the dependencies for a certain purpose.

# What alternatives to the feature have been considered

1. Manual scripting
2. Ansible (for remote/distributed setup automaton)

Both kinda suck for the use case.

**Comment by EricFromCanada** [comment]
This already exists as [Homebrew Bundle](https://github.com/Homebrew/homebrew-bundle/).

**Comment by thejeff77** [comment]
Thanks!
