### ISSUE TITLE
brew gist-logs crashes with undefined method `length` for nil:NilClass

### ISSUE THREAD

**Issue by thedrow** [Homebrew/brew#6933]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Report a bug to homebrew-core.

## What happened (include command output)

The command crashed with an exception.

<details>
  <summary>Command output</summary>
  <pre>
 brew gist-logs rustup-init
Error: undefined method `length' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/gist-logs.rb:145:in `gist_logs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:102:in `<main>
  </pre>
</details>

## What you expected to happen

Either the command should work or report what went wrong.

## Step-by-step reproduction instructions (by running `brew` commands)

brew gist-logs rustup-init

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.2.2-99-g212de9e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 212de9e564030dd28fd00507f4efa28535a8b9ec
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: fef6ed070f43eb19a5fc7b8f3cbaaba5d8b36a30
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/thedrow/.cache/Homebrew
HOMEBREW_LOGS: /home/thedrow/.cache/Homebrew/Logs
HOMEBREW_BREW_GIT_REMOTE: https://github.com/Homebrew/brew
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/linuxbrew-core
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.25.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 5.0.0-37-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.3 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.4.0
glibc: N/A
gcc: N/A
xorg: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/thedrow/.pyenv/shims/python3.5-config
  /home/thedrow/.pyenv/shims/python3.8-config
  /home/thedrow/.pyenv/shims/python3.7-config
  /home/thedrow/.pyenv/shims/python3.7m-config
  /home/thedrow/.pyenv/shims/python-config
  /home/thedrow/.pyenv/shims/python3.6m-config
  /home/thedrow/.pyenv/shims/python3.5m-config
  /home/thedrow/.pyenv/shims/python3.6-config
  /home/thedrow/.pyenv/shims/python3-config
</pre>

**Comment by thedrow** [comment]
It's possible that we should also raise `FormulaUnspecifiedError` when `Homebrew.args.resolved_formulae` is nil.
https://github.com/Homebrew/brew/blob/959b88266d315bb4d65b032e55f69f73d6b80759/Library/Homebrew/cmd/gist-logs.rb#L145

**Comment by issyl0** [comment]
Hi @thedrow, thanks for this issue.

I can reproduce the error you're seeing. It could _possibly_ be related to https://github.com/Homebrew/brew/pull/6857 as that's a recent PR that changes argument parsing in the affected file. But also I'd hope that someone would have reported this issue before now if it came from that PR! 😅  This error also occurs on other formulae that I try to `gist-logs` (eg `hello` and `kubectl`), so it's not confined to just `rustup-init`.

Your idea of raising `FormulaUnspecifiedError` when `Homebrew.args.resolved_formulae` works to get rid of the immediate error message, but it doesn't seem like users will be able to use `brew gist-logs` at all until the underlying bug is fixed.

I've never looked at this code before in any detail, so hopefully tomorrow someone who has will see this, but for now I'm going to continue 🕵️‍♀️.

**Comment by issyl0** [comment]
I fixed this in the PR linked above. Please `brew update` and try to upload gist logs again. Thanks for using Homebrew!
