### ISSUE TITLE
git fatal error when running `brew doctor`

### ISSUE THREAD

**Issue by samdmarshall** [Homebrew/brew#694]
### Bug reports:

When running `brew doctor` I am getting an error from git, but I unfortunately cannot track down the source of.

<details>
<summary>`brew doctor` Output</summary>
```
$ brew doctor 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libusb-1.0.0.dylib

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install python

Run `brew missing` for more details.
fatal: ambiguous argument 'HEAD': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
</details>

<details>
<summary>`brew doctor --debug` Output</summary>
```
$ brew doctor --debug
/usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libusb-1.0.0.dylib
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/gettext.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/libffi.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/samdmarshall/homebrew-formulae/aosd.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/clang-format.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/cloc.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/colordiff.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/cppcheck.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/diff-so-fancy.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/ffmpeg.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/fish.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/fzf.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/geoip.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/git.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/glib.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/goaccess.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/samdmarshall/homebrew-formulae/hotkeyd.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/httpie.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/samdmarshall/homebrew-formulae/iosconsole.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/jasonmp85/homebrew-iwyu/iwyu.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/keybase.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/lame.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/lynx.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/mercurial.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/ngrep.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/ninja.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/nmap.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/pandoc.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/pcre.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/pcre2.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/pyenv.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/python3.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/thefuck.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/wget.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/x264.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/samdmarshall/homebrew-formulae/xcrunner.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/xvid.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/youtube-dl.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/python.rb

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install python

Run `brew missing` for more details.
fatal: ambiguous argument 'HEAD': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
</details>

**Comment by MikeMcQuaid** [comment]
What does `brew config`, `which git` and `git --version` say? Thanks!

**Comment by samdmarshall** [comment]
```
 $ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 44a80e693a0dc0b28b4814b2897a9cc1cdd544c2
Last commit: never
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b163b0d8271500557664422d6fdc3054d0ff7d31
Core tap last commit: 14 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: N/A
X11: N/A
```

```
$ which git
/usr/local/bin/git
```

```
$ git --version
git version 2.9.2
```

**Comment by MikeMcQuaid** [comment]
Can you see what `brew doctor --debug` prints?

**Comment by samdmarshall** [comment]
I included that in my initial post.

**Comment by MikeMcQuaid** [comment]
My apologies, I can't read 😀.

**Comment by MikeMcQuaid** [comment]
@samdmarshall I've pushed something to improve `brew doctor --debug` output in 984ed83 so can I see your new `brew doctor --debug`? Also, can I see the output of `brew tap` and `find /usr/local -name HEAD`? Thanks!

**Comment by samdmarshall** [comment]
<details>
<summary>`brew doctor --debug`</summary>
$ brew doctor --debug
Checking check_DYLD_vars
Checking check_access_Frameworks
Checking check_access_bin
Checking check_access_cache
Checking check_access_cellar
Checking check_access_etc
Checking check_access_homebrew_repository
Checking check_access_include
Checking check_access_lib
Checking check_access_lib_pkgconfig
Checking check_access_logs
Checking check_access_prefix_opt
Checking check_access_sbin
Checking check_access_share
Checking check_access_share_locale
Checking check_access_share_man
Checking check_access_site_packages
Checking check_access_usr_local
Checking check_access_var
Checking check_clt_up_to_date
Checking check_filesystem_case_sensitive
Checking check_for_anaconda
Checking check_for_bad_curl
Checking check_for_bad_install_name_tool
Checking check_for_bad_python_symlink
Checking check_for_beta_xquartz
Checking check_for_config_scripts
Checking check_for_enthought_python
Checking check_for_external_cmd_name_conflict
Checking check_for_gettext
Checking check_for_git
Checking check_for_iconv
Checking check_for_installed_developer_tools
Checking check_for_latest_xquartz
Checking check_for_library_python
Checking check_for_multiple_volumes
Checking check_for_non_prefixed_coreutils
/usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb
Checking check_for_non_prefixed_findutils
/usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb
Checking check_for_old_env_vars
Checking check_for_old_homebrew_share_python_in_path
Checking check_for_osx_gcc_installer
Checking check_for_other_frameworks
Checking check_for_other_package_managers
Checking check_for_prerelease_xcode
Checking check_for_pth_support
Checking check_for_pydistutils_cfg_in_home
Checking check_for_stray_developer_directory
Checking check_for_stray_dylibs
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libusb-1.0.0.dylib
Checking check_for_stray_headers
Checking check_for_stray_las
Checking check_for_stray_pcs
Checking check_for_stray_static_libs
Checking check_for_symlinked_cellar
Checking check_for_unlinked_but_not_keg_only
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/gettext.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/libffi.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
Checking check_for_unsupported_curl_vars
Checking check_for_unsupported_osx
Checking check_git_newline_settings
Checking check_git_origin
Checking check_git_status
Checking check_git_version
Checking check_homebrew_prefix
Checking check_path_for_trailing_slashes
Checking check_ruby_version
Checking check_tmpdir
Checking check_tmpdir_sticky_bit
Checking check_user_curlrc
Checking check_user_path_1
Checking check_user_path_2
Checking check_user_path_3
Checking check_which_pkg_config
Checking check_xcode_license_approved
Checking check_xcode_prefix
Checking check_xcode_prefix_exists
Checking check_xcode_select_path
Checking check_xcode_up_to_date
Checking check_for_broken_symlinks
Checking check_missing_deps
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/samdmarshall/homebrew-formulae/aosd.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/clang-format.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/cloc.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/colordiff.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/cppcheck.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/diff-so-fancy.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/ffmpeg.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/fish.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/fzf.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/geoip.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/git.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/glib.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/goaccess.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/samdmarshall/homebrew-formulae/hotkeyd.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/httpie.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/samdmarshall/homebrew-formulae/iosconsole.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/jasonmp85/homebrew-iwyu/iwyu.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/keybase.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/lame.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/lynx.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/mercurial.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/ngrep.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/ninja.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/nmap.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/pandoc.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/pcre.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/pcre2.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/samdmarshall/homebrew-formulae/pyconfig.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/pyenv.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/python3.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/thefuck.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/wget.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/x264.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/samdmarshall/homebrew-formulae/xcrunner.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/xvid.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/youtube-dl.rb
/usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/python.rb

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install python

Run `brew missing` for more details.
Checking check_for_outdated_homebrew
fatal: ambiguous argument 'HEAD': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Checking check_for_linked_keg_only_brews
</details>

<details>
<summary>`brew tap`</summary>
$ brew tap
caskroom/cask
homebrew/core
jasonmp85/iwyu
mistydemeo/formulae
samdmarshall/formulae
</details>

<details>
<summary>`find /usr/local -name HEAD`</summary>
$ find /usr/local/ -name HEAD
/usr/local//.git/HEAD
/usr/local//.git/logs/HEAD
/usr/local//HEAD
/usr/local//Library/Taps/caskroom/homebrew-cask/.git/HEAD
/usr/local//Library/Taps/caskroom/homebrew-cask/.git/logs/HEAD
/usr/local//Library/Taps/caskroom/homebrew-cask/.git/logs/refs/remotes/origin/HEAD
/usr/local//Library/Taps/caskroom/homebrew-cask/.git/refs/remotes/origin/HEAD
/usr/local//Library/Taps/homebrew/homebrew-core/.git/HEAD
/usr/local//Library/Taps/homebrew/homebrew-core/.git/logs/HEAD
/usr/local//Library/Taps/homebrew/homebrew-core/.git/logs/refs/remotes/origin/HEAD
/usr/local//Library/Taps/homebrew/homebrew-core/.git/refs/remotes/origin/HEAD
/usr/local//Library/Taps/jasonmp85/homebrew-iwyu/.git/HEAD
/usr/local//Library/Taps/jasonmp85/homebrew-iwyu/.git/logs/HEAD
/usr/local//Library/Taps/jasonmp85/homebrew-iwyu/.git/logs/refs/remotes/origin/HEAD
/usr/local//Library/Taps/jasonmp85/homebrew-iwyu/.git/refs/remotes/origin/HEAD
/usr/local//Library/Taps/mistydemeo/homebrew-formulae/.git/HEAD
/usr/local//Library/Taps/mistydemeo/homebrew-formulae/.git/logs/HEAD
/usr/local//Library/Taps/mistydemeo/homebrew-formulae/.git/logs/refs/remotes/origin/HEAD
/usr/local//Library/Taps/mistydemeo/homebrew-formulae/.git/refs/remotes/origin/HEAD
/usr/local//Library/Taps/samdmarshall/homebrew-formulae/.git/HEAD
/usr/local//Library/Taps/samdmarshall/homebrew-formulae/.git/logs/HEAD
/usr/local//Library/Taps/samdmarshall/homebrew-formulae/.git/logs/refs/remotes/origin/HEAD
/usr/local//Library/Taps/samdmarshall/homebrew-formulae/.git/refs/remotes/origin/HEAD
</details>

**Comment by MikeMcQuaid** [comment]
> /usr/local//HEAD

I'll still make a proper fix for this but I'm pretty sure deleting that file will provide a workaround for this for now.

**Comment by samdmarshall** [comment]
Yup, that seems to have worked!
