### ISSUE TITLE
Add a command to determine log file locations

### ISSUE THREAD

**Issue by andyw8** [Homebrew/brew#6941]
# A detailed description of the proposed feature

This is an idea originally from @olivierlacan and @brandur:

https://twitter.com/olivierlacan/status/1217521015082967041

Perhaps Homebrew could provide a convenient, uniform way to look up the log path for a service. For example:
```
$ brew services logpath postgresql
/usr/local/var/log/postgres.log
```
The path could either be derived from a Cask's metadata, or from parsing the result of a call to the program.

Taking things further, the logfile location could also be displayed when listing services, e.g.
```
$ brew services list
Name              Status  User   Log Path
mongodb-community started awaite /usr/local/var/log/mongodb/mongo.log
mysql@5.7         started awaite /usr/local/var/mysql/localhost.err
postgresql        started awaite /usr/local/var/log/postgres.log
redis             started awaite /usr/local/var/log/redis.log
```

Another neat feature might be a `tail` command, which could then be piped to another command, e.g.:
```
brew services tail postgresql | grep 'fatal'
```

I'm not too familiar with the internals of Homebrew, so I'm not sure feasible such a feature would be, but I think a lot of people would find it useful.

# The motivation for the feature

It's very common to troubleshoot issues or analyse behaviour by examining log files. But finding where a service's log file is located is often awkward due to the variation between programs.

The path is almost usually given in the documentation, but a first resort is often, for me at least, is to use Google and hope to find a StackOverflow post with a solution which matches the version, platform and package manager in use.

# How the feature would be relevant to at least 90% of Homebrew users

Technical users often need to refer to log files to troubleshoot problems.

# What alternatives to the feature have been considered

Nothing yet.

**Comment by MikeMcQuaid** [comment]
We would consider something like this but, like https://github.com/Homebrew/brew/issues/5540 and https://github.com/Homebrew/brew/issues/5744, it would need to exist outside Homebrew proper and be sufficiently populated before we'd consider it being merged back.
