### ISSUE TITLE
`update` reports changes to non-version-changed formulae.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#695]
For a while now we've only been reporting changes to formulae that are either version or revision related, allowing us to make style tweaks without generating confusing noise. This seems to have changed at some point in the last... 36 hours or so, at a guess.

None of these listed below received a version change:

<img width="771" alt="screen shot 2016-08-11 at 15 28 49" src="https://cloud.githubusercontent.com/assets/6998367/17593235/1946b05c-5fdd-11e6-9c96-aaeb812ce4d9.png">

Simple reproduction:
```
brew tap homebrew/versions --full
cd /usr/local/Library/Taps/homebrew/homebrew-versions
git checkout b74a9a0088cdabf900d01e024a797b4134835347
brew update
```

**Comment by MikeMcQuaid** [comment]
> brew tap homebrew/versions --full
> cd /usr/local/Library/Taps/homebrew/homebrew-versions
> git checkout b74a9a0088cdabf900d01e024a797b4134835347
> brew update

That doesn't reproduce for me.

**Comment by DomT4** [comment]
Interesting, I can't reproduce it either now. I tried both separately on my box & a VM, so it definitely seemed to be a real thing before, but I don't spot anything in the core that seems relevant to the behaviour reverting to expected nature.

Guess I'll close & see if it pops back up in future.
