### ISSUE TITLE
brew extract does not correctly read formula history

### ISSUE THREAD

**Issue by joelmarty** [Homebrew/brew#6953]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew extract -d --version=1.9.6 haproxy <mytap>`

I need to have version 1.9.6 installed on my machine.

## What happened (include command output)

brew fails to find the 1.9.6 version although it is in the formula history.

<details>
  <summary>Command output</summary>
  <pre>

==> Searching repository history
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/haproxy.rb
==> Trying 2.1.2 from revision 38812f7 against desired 1.9.6
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/haproxy.rb
==> Trying 2.1.2 from revision a45b254 against desired 1.9.6
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/haproxy.rb
==> Trying 2.0.10 from revision e103c6a against desired 1.9.6
Error: Could not find haproxy! The formula or version may not have existed.
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/utils.rb:127:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:127:in `odie'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:136:in `block in extract'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:133:in `loop'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:133:in `extract'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

  </pre>
</details>

## What you expected to happen

brew should have been able to find the version.

## Step-by-step reproduction instructions (by running `brew` commands)

```
$ brew tap-new <user/haproxy>
$ brew extract -d --version=1.9.6 haproxy jmarty/haproxy
```
It looks like the issue comes from that line:
`==> Trying 2.0.10 from revision e103c6a against desired 1.9.6`

Revision `e103c6a` has the following commit message:
```
azure-cli: update 2.0.79_1 bottle.
```
which has nothing to do with haproxy.
I guess [`Git.last_revision_commit_of_files`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/extract.rb#L135) does not work as expected

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config                                           
HOMEBREW_VERSION: 2.2.4-2-g23108f3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 23108f3c736030070ca1e4673652c20c503a7d02
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cc0bceefd6a0b779c58ee3698097125344c3c539
Core tap last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/jmarty/.pyenv/shims/python3.7-config
  /Users/jmarty/.pyenv/shims/python3.7m-config
  /Users/jmarty/.pyenv/shims/python-config
  /Users/jmarty/.pyenv/shims/python3-config
</pre>

**Comment by MikeMcQuaid** [comment]
I cannot reproduce this. Please ensure your clone of Homebrew/homebrew-core is not shallow. You may wish to `rm -rf $(brew --repo homebrew/core); brew tap homebrew/core` and try again.

**Comment by joelmarty** [comment]
It's kind of worse now:
```
$ brew extract -d --version=1.9.6 haproxy jmarty/haproxy
==> Searching repository history
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/haproxy.rb
==> Trying 2.1.2 from revision e8a9116 against desired 1.9.6
Error: Could not find haproxy! The formula or version may not have existed.
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/utils.rb:127:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:127:in `odie'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:136:in `block in extract'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:133:in `loop'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/extract.rb:133:in `extract'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
> Please ensure your clone of Homebrew/homebrew-core is not shallow.

Did you try this?

Given I cannot reproduce: we do not consider this a Homebrew bug so please consider taking it to https://discourse.brew.sh instead.

**Comment by joelmarty** [comment]
I did try it and it produced the [second error message](https://github.com/Homebrew/brew/issues/6953#issuecomment-578039170) I listed.

**Comment by EricFromCanada** [comment]
I also cannot reproduce this issue.

**Comment by MikeMcQuaid** [comment]
@joelmarty If two maintainers cannot reproduce this: I'm afraid this is insufficient for us to consider it a bug.

**Comment by joelmarty** [comment]
fair enough
