### ISSUE TITLE
`brew doctor` makes bash specific suggestions

### ISSUE THREAD

**Issue by mikedamm** [Homebrew/brew#6954]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Attempting to run `brew doctor` to troubleshoot an issue. Doctor is not aware of the running shell and suggests bash specific syntax such as `$(whoami)`

## What happened (include command output)

Doctor produced incorrect instructions.

<details>
  <summary>Command output</summary>
  <pre>
$ sudo chown -R $(whoami) /usr/local/sbin
fish: $(...) is not supported. In fish, please use '(whoami)'.
sudo chown -R $(whoami) /usr/local/sbin
  </pre>
</details>

## What you expected to happen

Doctor should have detected the parent process and given shell aware syntax.

## Step-by-step reproduction instructions (by running `brew` commands)

1. Run `brew doctor`

## Output of `brew config` and `brew doctor` commands

Not relevant.

**Comment by MikeMcQuaid** [comment]
> Doctor should have detected the parent process and given shell aware syntax.

We won't be producing Fish-compatible output for all commands. If you're running an alternate shell you can figure out how to convert those commands or run `bash` as a one-off.

**Comment by mikedamm** [comment]
@MikeMcQuaid I understand that supporting every shell isn't an option. However you should be aware that [bash is no longer the default shell for macOS](https://support.apple.com/en-us/HT208050) so I think this is at least an issue worth leaving open until a solution is found.

**Comment by MikeMcQuaid** [comment]
> However you should be aware that [bash is no longer the default shell for macOS](https://support.apple.com/en-us/HT208050)

I am aware. Those snippets all work on ZSH.
