### ISSUE TITLE
Show full command used to invoke `bump-formula-pr`

### ISSUE THREAD

**Issue by waldyrious** [Homebrew/brew#6955]
When a PR is created via `brew bump-formula-pr`, the PR message is simply

> Created with `brew bump-formula-pr`.

That's great for discoverability, but as a new/occasional contributor, I ran into issue issues the first few times I tried to use the command, such as missing parameters or using incorrect ones. [Here's an example](https://github.com/Homebrew/homebrew-core/pull/48677).

It would have been much easier if the PRs included the actual command-line used to create them. For example, for https://github.com/Homebrew/homebrew-core/pull/49357, it could be something like this:

> Created with `brew bump-formula-pr`.
>
> Full command used: `brew bump-formula-pr --version=0.31.0 --url=https://github.com/denoland/deno/releases/download/v0.31.0/deno_src.tar.gz --sha256=5bfb45c7f2c15a740d388b6bbd19bfe6a2fa9ea3de5ad10fadab2fef7536607e deno`.

I noticed that that string is defined in [`Library/Homebrew/dev-cmd/bump-formula-pr.rb`](https://github.com/Homebrew/brew/blob/master@{2020-01-24}/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L367), but knowing next to no Ruby, I couldn't figure out how to include the entire command's arguments in that message.

If anyone could give me hints at how to proceed, I'd be happy to submit a PR.

**Comment by MikeMcQuaid** [comment]
I'd like to see multiple requests for this before we include it as it's a bit "noisy". 

Please always fill out the issue template in future, thanks.

**Comment by waldyrious** [comment]
Here's a potentially less noisy way to show the command:

```
brew bump-formula-pr \
  --version=0.31.0 \
  --url=https://github.com/denoland/deno/releases/download/v0.31.0/deno_src.tar.gz \
  --sha256=5bfb45c7f2c15a740d388b6bbd19bfe6a2fa9ea3de5ad10fadab2fef7536607e \
  deno
```
