### ISSUE TITLE
Support v2-build for Haskell packages

### ISSUE THREAD

**Issue by athas** [Homebrew/brew#6957]
(Note up front: if this is considered a good idea, I volunteer to also implement it.)

# A detailed description of the proposed feature

Homebrew currently provides [haskell.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/haskell.rb) with helper functions for writing formulae that use the Haskell build system `cabal`.  These functions currently use `cabal`s "v1 commands" (`v1-build`, `v1-install`) which have been superceded by the "v2 commands" (e.g. `v2-build`) in newer versions of `cabal`.  They do mostly the same from a user-visible point of view, but are internally very different.  Most importantly, the v2 commands are naturally sandboxed, and automatically handle the installation of standard build tools (particularly `happy` and `alex`).  They also have superior support for freezing dependencies, which can perhaps offset some of the fragility of the Haskell formulae (but that's a bigger problem).  I suggest that either `haskell.rb` should be changed to use v2 commands by default, probably by supplying it concurrently with v1 commands in a transitory period (and for testing).

# The motivation for the feature

I don't think the v1 commands are going away in the short term, but they are not developed actively anymore.  The improved isolation from the v2 commands are very helpful to a package manager like Homebrew.  The v1 commands modify user state by default, and the current haskell.rb helper functions jump through hoops to avoid this.

# How the feature would be relevant to at least 90% of Homebrew users

Honestly, I doubt 90% of Homebrew users install any of the Haskell packages.  Well, maybe big ones like pandoc or shellcheck, but this is not supposed to be a user-visible change.

# What alternatives to the feature have been considered

NA, I think.

**Comment by athas** [comment]
It's also possible that the v2 commands are good enough that Homebrew doesn't really need any of the helper framework anymore.  I will investigate.

**Comment by jonchang** [comment]
> It's also possible that the v2 commands are good enough that Homebrew doesn't really need any of the helper framework anymore. I will investigate.

Would it be possible to use the v2 commands in some formula like e.g., pandoc to see how it works?

**Comment by athas** [comment]
Yes, but it looks like we do want some kind of framework still.  Even the v2 commands will read from $HOME/.cabal (and also write various cache things there), which we do not want.  We'll need less than for the v1 commands, though - merely rebinding $HOME might actually be enough.

**Comment by jonchang** [comment]
We also have another haskell install method proposed using stack here: https://github.com/Homebrew/brew/pull/6945

**Comment by MikeMcQuaid** [comment]
> We also have another haskell install method proposed using stack here: #6945

👍. To be explicit: I'd like to see us decide on one solution and double-down on it.

**Comment by athas** [comment]
Closed by #6974.
