### ISSUE TITLE
Allow homebrew to be installed as root user

### ISSUE THREAD

**Issue by Ignas2526** [Homebrew/brew#6959]
# A detailed description of the proposed feature

Allow homebrew to be installed under root user. In other words, offer a way to bypass the _Don't run this as root!_ It can be an optional parameter or an environment variable.

# The motivation for the feature

Currently, Installing homebrew is unnecessarily difficult in bitbucket pipeline.

# How the feature would be relevant to at least 90% of Homebrew users

Pretty much everyone who uses bitbucket pipelines or something similar would benefit from this, because the user is pretty much always root by default.

# What alternatives to the feature have been considered

The only option now is to do unnecessary commands which achieve nothing but extra work and frustration.

**Comment by MikeMcQuaid** [comment]
We'd review a PR that adds BitBucket Pipelines detection to https://github.com/Homebrew/brew/blob/a20fd7895a62a5ad0caa2e63ad59d469d6eda742/Library/Homebrew/brew.sh#L413-L414
