### ISSUE TITLE
SIP prevents brew doctor from accurately assessing whether DYLD envvars are set

### ISSUE THREAD

**Issue by puxlit** [Homebrew/brew#6961]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

In looking at <https://github.com/Homebrew/homebrew-core/issues/49304>, my suspicion was that unexpected DYLD envvars were causing the user grief. This scenario should be [accounted for](https://github.com/Homebrew/brew/blob/2.2.4/Library/Homebrew/diagnostic.rb#L477-L497) by `brew doctor`, yet the user's supplied logs did not suggest anything was afoul. Thus, attention turned to the efficacy of this diagnostic case.

## What happened (include command output)

```
$ export DYLD_PRINT_LIBRARIES=
$ brew doctor
Your system is ready to brew.
$ brew irb <<'EOF'
> ENV.keys.grep(/^(|DY)LD_/)
> EOF
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
Switch to inspect mode.
ENV.keys.grep(/^(|DY)LD_/)
[]

```

## What you expected to happen

```
$ export DYLD_PRINT_LIBRARIES=
$ brew doctor
dyld: loaded: /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby
[omitted for brevity]
dyld: loaded: /usr/lib/libxslt.1.dylib
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Setting DYLD_* or LD_* variables can break dynamic linking.
Set variables:
  DYLD_PRINT_LIBRARIES: 
$ brew irb <<'EOF'
> ENV.keys.grep(/^(|DY)LD_/)
> EOF
dyld: loaded: /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby
[omitted for brevity]
dyld: loaded: /usr/lib/libxslt.1.dylib
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
Switch to inspect mode.
ENV.keys.grep(/^(|DY)LD_/)
["DYLD_PRINT_LIBRARIES"]

```

There are a few reasons (at least on High Sierra). Firstly, `/bin/bash` is SIP-protected, so DYLD variables are stripped when [/usr/local/Homebrew/bin/brew](https://github.com/Homebrew/brew/blob/2.2.4/bin/brew) executes. Secondly, by default that script permits only a [whitelisted](https://github.com/Homebrew/brew/blob/2.2.4/bin/brew#L85-L101) set of environment variables through to [/usr/local/Homebrew/Library/Homebrew/brew.sh](https://github.com/Homebrew/brew/blob/2.2.4/Library/Homebrew/brew.sh) (via the SIP-protected `/usr/bin/env`, no less).

## Step-by-step reproduction instructions (by running `brew` commands)

See above.

## Output of `brew config` and `brew doctor` commands

<details><summary><code>brew config</code></summary><pre>
HOMEBREW_VERSION: 2.2.4-2-g23108f3
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 23108f3c736030070ca1e4673652c20c503a7d02
Last commit: No signature
4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1ff573fe3ffa9db3d7884cb53369201d44fbf8a2
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_NO_INSECURE_REDIRECT: 1
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1000
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 13.0.1, 11.0.1
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
</pre></details>

<details><summary><code>brew doctor</code></summary><pre>
Your system is ready to brew.
</pre></details>

**Comment by MikeMcQuaid** [comment]
That we strip these variables is intentional behaviour, thanks.

**Comment by puxlit** [comment]
If this is the case, then should the ineffectual [`check_ld_vars`](https://github.com/Homebrew/brew/blob/2.2.4/Library/Homebrew/diagnostic.rb#L477-L497) diagnostic case be removed?

**Comment by MikeMcQuaid** [comment]
Yes, it probably should.
