### ISSUE TITLE
macfusion uses the wrong (outdated) github repository

### ISSUE THREAD

**Issue by mpathy** [Homebrew/brew#697]
The only properly working macfusion is in this repository:
https://github.com/ElDeveloper/macfusion2

mgorbach abadoned the project quite a while ago, this here:
https://github.com/mgorbach/macfusion2/issues/36
..is only one of countless bugs, issues and so on - using the version from the other repo all problems are gone.

Please switch to this repo, so I can get back on the brew package management also with this software..

**Comment by DomT4** [comment]
I think you're looking for https://github.com/caskroom/homebrew-cask. We don't ship a `macfusion` formula as far as I can see, but the Cask does ship a `macfusion` [cask](https://github.com/caskroom/homebrew-cask/blob/1bfdb2a07c39c02b0a81e5a45b60e1c649ed04e0/Casks/macfusion.rb), which is the 2.0.4 version.

Please report this to them. Thanks!
