### ISSUE TITLE
Reinstate `brew cask search`

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/brew#6975]
# A detailed description of the proposed feature

Originated as part of the discussion in https://github.com/Homebrew/brew/issues/6950.

Having flags that mimic subcommands is a poor interface—they have low discoverability and are confusing. The one command that does it is `brew search`, and my argument is users would be better served by reinstating `brew cask search`.

Let’s look at the current `search` situation:

```
brew search                    # lists all formulae
brew search <argument>         # search for <argument> in formulae and casks
brew search --casks            # lists all casks
brew search --casks <argument> # searches for <argument> in formulae and casks
```

So without the `--casks` flag, half the time you only get formulae, the other half you get formulae and casks; if you give the `--casks` flag, half the time you only get casks, the other half you get formulae and casks. That’s wholly unintuitive. One of the commands is useless (`brew search --casks <argument>`) but you wouldn’t know without trying and could be forgiven for thinking it only showed casks.

Compare that to reinstating `brew cask search`:

```
brew search                 # lists all formulae
brew search <argument>      # searches for <argument> in formulae
brew cask search            # lists all casks
brew cask search <argument> # searches for <argument> in casks
```

All commands do what they say all the time. We lose the ability to show both casks and formulae at once but gain clarity, which is more important. We already require two commands for every other task—like [`upgrade`](https://github.com/Homebrew/brew/issues/6950), which I’d wager is called way more often (do we have data on that?).

If having a single command to search both formulae and casks is a must, I’d recommend an `--all`, or `--both`, or `--fac` (**f**ormulae **a**nd **c**asks) flag.

In essence, every command that needs the option to run on just formulae or just casks should be under their respective subcommand. `update` works as standalone because it deals with *taps*, not formulae and casks. One could also make a case for the consolidation of `info` (if there’s a formulae and a cask share a name, it doesn’t seem problematic that `info` would show both).

# The motivation for the feature

Make Homebrew’s interface more consistent, thus clearer.

# How the feature would be relevant to at least 90% of Homebrew users

Following the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) is a benefit to every user.

# What alternatives to the feature have been considered

#### Alternative 1

Get rid of the `--casks` flag and make `brew search` always show both:

```
brew search            # lists all formulae and casks
brew search <argument> # search for <argument> in formulae and casks
```

#### Alternative 2

Make `brew search` always show both; make `--casks` always search *only* for casks; add a `--formulae` flag to search *only* for formulae. **I don’t think this is a good idea, but it’s still better than the current situation**:

```
brew search                       # lists all formulae and casks
brew search <argument>            # search for <argument> in formulae and casks
brew search --formulae            # lists all formulae
brew search --formulae <argument> # search for <argument> in formulae
brew search --casks               # lists all casks
brew search --casks <argument>.   # search for <argument> in casks
```

**Comment by MikeMcQuaid** [comment]
> Make `brew search` always show both; make `--casks` always search _only_ for casks; add a `--formulae` flag to search _only_ for formulae. **I don’t think this is a good idea, but it’s still better than the current situation**:

👍 this sounds good to me.

**Comment by Elethom** [comment]
Always showing both improves the discoverability of cask formulae themselves.

**Comment by vitorgalvao** [comment]
> Always showing both improves the discoverability of cask formulae themselves.

Just so we don’t get confused: there’re casks and there’re formulae, we consider them different things.

But to your point, I don’t think lack of discoverability in casks is a thing. In fact, many people straight up prefer casks, or just use casks, or just submit casks because they find them easier to build. I regularly have to send people to non-Cask Homebrew for submissions because they’ve made a cask for an open-source CLI-only tool, which should default to Homebrew. Going by number of stars alone, `homebrew-cask` has over twice as many stars as `homebrew-core`.

**Comment by yumitsu** [comment]
@vitorgalvao Well, without denying that your information is quite surprising, I have to agree - keys as logic switches never seemed to be a good solution. I can't remember for how many occasions my fingers have typed `brew cask search` without any doubt in their confidence.

Let me suggest my option:
```
brew search <formulae>         - search for formulæs
brew cask search <cask>		   - search for casks
brew search --desc text|regexp - cross-referencing search
```

Why so? Well, my point is that cross-search is mainly used to search tools by description, i.e. to find a suitable utility with  certain functionality, and it is most likely that the user will not care whether it is a formula, or cask.

**Comment by vidusheeamoli** [comment]
Hello, I would like to work on this. Would appreciate pointers to get started. 

> Make brew search always show both; make --casks always search only for casks; add a
> --formulae flag to search only for formulae.

This looks like a good solution to me. What do you think @MikeMcQuaid @vitorgalvao ? :)

**Comment by SMillerDev** [comment]
Having casks behave as a completely separate part of homebrew always seemed weird to me so I'm in favor of anything that removes the need to specify that you're operating on casks (while keeping the option).

**Comment by MikeMcQuaid** [comment]
@vidusheeamoli Sounds like a good solution to me! If you have more specific questions we can provide pointers.

**Comment by vidusheeamoli** [comment]
Hello! After lurking around the codebase for a few days now, things make a lot more sense to me and I am focusing on this issue now. 😄

This may be a stupid question, but I am unable to figure out how to test out the changes i have made to `brew/Library/Homebrew/cmd/search.rb` locally?

**Comment by vidusheeamoli** [comment]
Hello! After exploring the codebase for a few days now, things make a lot more sense to me and I am focusing on this issue now. 😄

This may be a trivial thing, but I am unable to figure out how to test out the changes i have made to `brew/Library/Homebrew/cmd/search.rb` locally on my system. 

Prior to this, while working on issues related to a formula, all I did was reinstall the formula from the shallow clone of my repository. How do you suggest I test out the changes in this case?

**Comment by issyl0** [comment]
Hi @vidusheeamoli, thanks for your contributions so far! :rocket:

You'll find `brew`'s source code - this repository - cloned into `brew --repo` on your system. So `cd $(brew --repo)` will put you into `/usr/local/Homebrew`, then you can make changes to `Library/Homebrew/cmd/search.rb` and run `brew search` as you normally would. Then you'll see your changes immediately.

For making changes to formulae, it's the same approach but with `cd $(brew --repo homebrew/core)` - you end up in `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core`.

Let me know how you get on. If you have any further questions about this I'm happy to help!

**Comment by vidusheeamoli** [comment]
Thank you @issyl0! I'll get started right away 😄

**Comment by vitorgalvao** [comment]
Am I mistaken , or is this closed by https://github.com/Homebrew/brew/pull/7094?

**Comment by vidusheeamoli** [comment]
@vitorgalvao 
Here is what brew search looks like now:
```
brew search							#default, only lists formulae
brew search --formulae				#lists only formulae
brew search --casks 				#lists only casks
brew search <arg>					#lists both formulae and casks
brew search --formulae <arg>		#lists only formulae
brew search --casks <arg>			#lists only casks
```
If this looks good, then I think this issue can be closed. :)

**Comment by MikeMcQuaid** [comment]
Yup, fixed by @vidusheeamoli, great work!
