### ISSUE TITLE
Installing gnuplot seems to have broken Postgres or at least psql

### ISSUE THREAD

**Issue by mnatz** [Homebrew/brew#6979]
Hello - installed gnuplot using brew a short time ago.  The result seems to be a broken postgresql 's   psql. 
the follow command results in the error below.    

psql <databasename>

dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/postgresql/11.2/lib/libpq.5.11.dylib
  Reason: image not found
Abort trap: 6

openssl was installed as a dependency for gnuplot. Postgres also uses it .  Does any one have a work around.  I did try  removing openssl and reinstalling it. I also removed gnuplot with the brew rmtree command and reinstall. Also no change.

**Comment by mnatz** [comment]
Mike - why is this being closed? Need some help? If you have send a solution have not received one?

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

You didn't read it or fill it in. Even if you had: this type of post is an issue with your local system and should be posted to Discourse.

**Comment by MikeMcQuaid** [comment]
Also: please do not email me to my personal email address about such things: it's quite rude.

**Comment by mnatz** [comment]
Mike - was not being rude - not my intent. I very seldom post anything and first time here. I was looking for a way to reply and found your email first. I later scrolled down and found this form. 
As to the proper way.. glad to. Did not see a checklist. Saw a place to write and a button to commit. I am just looking for some help. Will attempt again. Will look for more instructions. If you have a URL to the them I will follow those.

**Comment by MikeMcQuaid** [comment]
Use https://github.com/Homebrew/brew/issues/new/choose to create new issues and, in this case, choose "Get help on Discourse".
