### ISSUE TITLE
Feature request: "provides" property for packages

### ISSUE THREAD

**Issue by Elethom** [Homebrew/brew#6980]
Many package managers provide a key called something like "provides", to specify what packages this package can replace in the dependency tree. Doing so allows forks/patches to be used without breaking the tree. 

# The motivation for the feature
The utility [`n`](https://github.com/tj/n), which has a Homebrew formula, manages a set of nodejs versions and installs them in `/usr/local/bin` like brew does for the package `node`. However, nodejs-based packages in node depend on `node`, so one more copy of nodejs always has to be installed. That is 60 MB of wasted space.

# How the feature would be relevant to at least 90% of Homebrew users
People run into versions of things that will substitute for each other from time to time. PyPy for Python, n's version management for nodejs, different implementations of other "basic" tools on the command-line level...

# What alternatives to the feature have been considered
depends_on could use an "or" syntax for individual occurrences, but it requires editing every dependency.

**Comment by MikeMcQuaid** [comment]
Homebrew used to do this (it was called "requirements") but it's practically impossible to support without issue so we choose not to. WONTFIX, sorry.
