### ISSUE TITLE
portable-ruby poured after each cleanup

### ISSUE THREAD

**Issue by marcfrederick** [Homebrew/brew#6987]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to `brew update` after a `brew cleanup`

## What happened (include command output)

`portable-ruby` was reinstalled.

<details>
  <summary>Command output</summary>
  <pre>

[marcfrederick@Marcs-MacBook-Pro ~]$ brew upgrade
[marcfrederick@Marcs-MacBook-Pro ~]$ brew cleanup

[marcfrederick@Marcs-MacBook-Pro ~]$ brew upgrade
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3.mavericks.bottle.tar.gz
Already downloaded: /Users/marcfrederick/Library/Caches/Homebrew/portable-ruby-2.6.3.mavericks.bottle.tar.gz
==> Pouring portable-ruby-2.6.3.mavericks.bottle.tar.gz
[marcfrederick@Marcs-MacBook-Pro ~]$

  </pre>
</details>

## What you expected to happen

`portable-ruby` not to be upgraded each time.

## Step-by-step reproduction instructions (by running `brew` commands)

1. `brew cleanup`
2. `brew upgrade`

## Output of `brew config` and `brew doctor` commands

<pre>
[marcfrederick@Marcs-MacBook-Pro ~]$ brew config
HOMEBREW_VERSION: 2.2.4-35-g8aa7cd2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8aa7cd2a76f3d7f4d8d3c75a5b50730c5acdf108
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e240db108d7909a74d8dcd370695a26c38b6a950
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: true
HOMEBREW_NO_INSECURE_REDIRECT: true
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.2
macOS: 10.15.3-x86_64
CLT: 11.0.33.8
Xcode: 11.3.1
[marcfrederick@Marcs-MacBook-Pro ~]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.

[marcfrederick@Marcs-MacBook-Pro ~]$
</pre>

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/pull/6986
