### ISSUE TITLE
brew update broken

### ISSUE THREAD

**Issue by therealprof** [Homebrew/brew#700]
On my system the git checkouts are updated but not rebased anymore after commit 11116c2467710c9b3df37164dce2bb012a205d33.

> $ git checkout 11116c2467710c9b3df37164dce2bb012a205d33^
> HEAD is now at 33912e2... xcode: update expected clang for macOS 10.12
> $ brew update -verbose
> Updating /usr/local...
> First, rewinding head to replay your work on top of it...
> Fast-forwarded HEAD to origin/master.
> Updating /usr/local/Library/Taps/caskroom/homebrew-cask...
> Current branch master is up to date.
> Updating /usr/local/Library/Taps/homebrew/homebrew-core...
> Current branch master is up to date.
> ... 
> Updated Homebrew from 33912e2 to 97a66aa.
> Updated 1 tap (homebrew/core).
> ==> Updated Formulae
> git-fixup                                                                              leveldb

So that's fine.

> $ git checkout 11116c2467710c9b3df37164dce2bb012a205d33
> HEAD is now at 11116c2... update.sh: further speed up `brew update`.
> $ brew update -verbose
>  .
>  .
>  .
>  .
>  .
>  .
>  .
>  .
>  .
>  .
>  .
>  .
> Already up-to-date.

(periods inserted by me to visualize the blank lines in output)

And here it is not.

**Comment by MikeMcQuaid** [comment]
Sorry about this, this was a known bug with a 20 hour window that should be resolved by `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`. Let me know if it is not.

**Comment by therealprof** [comment]
Works, thanks.

**Comment by michaeljpeake** [comment]
Yay!

**Comment by kiding** [comment]
This solution solved my problem where `$ brew update` kept saying `Already up-to-date.` when it’s clearly not after upgrading to macOS Sierra.
