### ISSUE TITLE
Can't install Dart Sass properly on MacOs Catalina

### ISSUE THREAD

**Issue by interglobalmedia** [Homebrew/brew#7002]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem? yes
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? yes
- [ ] ran `brew config` and `brew doctor` and included their output with your issue? I will!

## What you were trying to do (and why)

Trying to install Sass on my computer

## What happened (include command output)

I got this error after linking everything I was told to link:  

sass --version                                                        ⏎
Traceback (most recent call last):
	10: from /Users/mariacam/.rbenv/versions/2.7.0-dev/bin/sass:23:in `<main>'
	 9: from /Users/mariacam/.rbenv/versions/2.7.0-dev/bin/sass:23:in `load'
	 8: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/bin/sass:6:in `<top (required)>'
	 7: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/lib/sass.rb:99:in `<top (required)>'
	 4: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/lib/sass/engine.rb:2:in `<top (required)>'
	 1: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (LoadError)
  Referenced from: /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle\n  Reason: image not found - /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle
	11: from /Users/mariacam/.rbenv/versions/2.7.0-dev/bin/sass:23:in `<main>'
	10: from /Users/mariacam/.rbenv/versions/2.7.0-dev/bin/sass:23:in `load'
	 9: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/bin/sass:5:in `<top (required)>'
	 8: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/bin/sass:8:in `rescue in <top (required)>'
	 7: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/lib/sass.rb:99:in `<top (required)>'
	 4: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/lib/sass/engine.rb:2:in `<top (required)>'
	 1: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (LoadError)
  Referenced from: /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle\n  Reason: image not found - /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle

<details>
  <summary>Command output</summary>
  <pre>

sass --version                                                        ⏎
Traceback (most recent call last):
	10: from /Users/mariacam/.rbenv/versions/2.7.0-dev/bin/sass:23:in `<main>'
	 9: from /Users/mariacam/.rbenv/versions/2.7.0-dev/bin/sass:23:in `load'
	 8: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/bin/sass:6:in `<top (required)>'
	 7: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/lib/sass.rb:99:in `<top (required)>'
	 4: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/lib/sass/engine.rb:2:in `<top (required)>'
	 1: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (LoadError)
  Referenced from: /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle\n  Reason: image not found - /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle
	11: from /Users/mariacam/.rbenv/versions/2.7.0-dev/bin/sass:23:in `<main>'
	10: from /Users/mariacam/.rbenv/versions/2.7.0-dev/bin/sass:23:in `load'
	 9: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/bin/sass:5:in `<top (required)>'
	 8: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/bin/sass:8:in `rescue in <top (required)>'
	 7: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/lib/sass.rb:99:in `<top (required)>'
	 4: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/sass-3.7.3/lib/sass/engine.rb:2:in `<top (required)>'
	 1: from /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (LoadError)
  Referenced from: /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle\n  Reason: image not found - /Users/mariacam/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/x86_64-darwin18/digest/sha1.bundle

  </pre>
</details>

## What you expected to happen

To get the version of Sass that I have on my computer

## Step-by-step reproduction instructions (by running `brew` commands)
brew config
HOMEBREW_VERSION: 2.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4493f27db28be7f083737424cecd8edb863ec3f6
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2da0dc898a663118daf535515a9d8eb4052e160f
Core tap last commit: 30 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_131, 1.7.0_80
macOS: 10.15.3-x86_64
CLT: 11.0.33.16
Xcode: 11.3

## Output of `brew config` and `brew doctor` commands

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libical.0.0.0.dylib
  /usr/local/lib/libicalss.0.0.0.dylib
  /usr/local/lib/libicalvcal.0.0.0.dylib
  /usr/local/lib/libltdl.3.1.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/jack/control.h
  /usr/local/include/jack/intclient.h
  /usr/local/include/jack/jack.h
  /usr/local/include/jack/jslist.h
  /usr/local/include/jack/midiport.h
  /usr/local/include/jack/net.h
  /usr/local/include/jack/ringbuffer.h
  /usr/local/include/jack/session.h
  /usr/local/include/jack/statistics.h
  /usr/local/include/jack/systemdeps.h
  /usr/local/include/jack/thread.h
  /usr/local/include/jack/transport.h
  /usr/local/include/jack/types.h
  /usr/local/include/jack/weakjack.h
  /usr/local/include/jack/weakmacros.h
  /usr/local/include/node/android-ifaddrs.h
  /usr/local/include/node/ares.h
  /usr/local/include/node/ares_build.h
  /usr/local/include/node/ares_rules.h
  /usr/local/include/node/ares_version.h
  /usr/local/include/node/libplatform/libplatform.h
  /usr/local/include/node/libplatform/v8-tracing.h
  /usr/local/include/node/nameser.h
  /usr/local/include/node/node.h
  /usr/local/include/node/node_buffer.h
  /usr/local/include/node/node_object_wrap.h
  /usr/local/include/node/node_version.h
  /usr/local/include/node/openssl/aes.h
  /usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
  /usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
  /usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux32-s390x/opensslconf.h
  /usr/local/include/node/openssl/archs/linux64-s390x/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
  /usr/local/include/node/openssl/asn1.h
  /usr/local/include/node/openssl/asn1_mac.h
  /usr/local/include/node/openssl/asn1t.h
  /usr/local/include/node/openssl/bio.h
  /usr/local/include/node/openssl/blowfish.h
  /usr/local/include/node/openssl/bn.h
  /usr/local/include/node/openssl/buffer.h
  /usr/local/include/node/openssl/camellia.h
  /usr/local/include/node/openssl/cast.h
  /usr/local/include/node/openssl/cmac.h
  /usr/local/include/node/openssl/cms.h
  /usr/local/include/node/openssl/comp.h
  /usr/local/include/node/openssl/conf.h
  /usr/local/include/node/openssl/conf_api.h
  /usr/local/include/node/openssl/crypto.h
  /usr/local/include/node/openssl/des.h
  /usr/local/include/node/openssl/des_old.h
  /usr/local/include/node/openssl/dh.h
  /usr/local/include/node/openssl/dsa.h
  /usr/local/include/node/openssl/dso.h
  /usr/local/include/node/openssl/dtls1.h
  /usr/local/include/node/openssl/e_os2.h
  /usr/local/include/node/openssl/ebcdic.h
  /usr/local/include/node/openssl/ec.h
  /usr/local/include/node/openssl/ecdh.h
  /usr/local/include/node/openssl/ecdsa.h
  /usr/local/include/node/openssl/engine.h
  /usr/local/include/node/openssl/err.h
  /usr/local/include/node/openssl/evp.h
  /usr/local/include/node/openssl/hmac.h
  /usr/local/include/node/openssl/idea.h
  /usr/local/include/node/openssl/krb5_asn.h
  /usr/local/include/node/openssl/kssl.h
  /usr/local/include/node/openssl/lhash.h
  /usr/local/include/node/openssl/md4.h
  /usr/local/include/node/openssl/md5.h
  /usr/local/include/node/openssl/mdc2.h
  /usr/local/include/node/openssl/modes.h
  /usr/local/include/node/openssl/obj_mac.h
  /usr/local/include/node/openssl/objects.h
  /usr/local/include/node/openssl/ocsp.h
  /usr/local/include/node/openssl/opensslconf.h
  /usr/local/include/node/openssl/opensslv.h
  /usr/local/include/node/openssl/ossl_typ.h
  /usr/local/include/node/openssl/pem.h
  /usr/local/include/node/openssl/pem2.h
  /usr/local/include/node/openssl/pkcs12.h
  /usr/local/include/node/openssl/pkcs7.h
  /usr/local/include/node/openssl/pqueue.h
  /usr/local/include/node/openssl/rand.h
  /usr/local/include/node/openssl/rc2.h
  /usr/local/include/node/openssl/rc4.h
  /usr/local/include/node/openssl/ripemd.h
  /usr/local/include/node/openssl/rsa.h
  /usr/local/include/node/openssl/safestack.h
  /usr/local/include/node/openssl/seed.h
  /usr/local/include/node/openssl/sha.h
  /usr/local/include/node/openssl/srp.h
  /usr/local/include/node/openssl/srtp.h
  /usr/local/include/node/openssl/ssl.h
  /usr/local/include/node/openssl/ssl2.h
  /usr/local/include/node/openssl/ssl23.h
  /usr/local/include/node/openssl/ssl3.h
  /usr/local/include/node/openssl/stack.h
  /usr/local/include/node/openssl/symhacks.h
  /usr/local/include/node/openssl/tls1.h
  /usr/local/include/node/openssl/ts.h
  /usr/local/include/node/openssl/txt_db.h
  /usr/local/include/node/openssl/ui.h
  /usr/local/include/node/openssl/ui_compat.h
  /usr/local/include/node/openssl/whrlpool.h
  /usr/local/include/node/openssl/x509.h
  /usr/local/include/node/openssl/x509_vfy.h
  /usr/local/include/node/openssl/x509v3.h
  /usr/local/include/node/pthread-barrier.h
  /usr/local/include/node/stdint-msvc2008.h
  /usr/local/include/node/tree.h
  /usr/local/include/node/uv-aix.h
  /usr/local/include/node/uv-bsd.h
  /usr/local/include/node/uv-darwin.h
  /usr/local/include/node/uv-errno.h
  /usr/local/include/node/uv-linux.h
  /usr/local/include/node/uv-os390.h
  /usr/local/include/node/uv-sunos.h
  /usr/local/include/node/uv-threadpool.h
  /usr/local/include/node/uv-unix.h
  /usr/local/include/node/uv-version.h
  /usr/local/include/node/uv-win.h
  /usr/local/include/node/uv.h
  /usr/local/include/node/v8-debug.h
  /usr/local/include/node/v8-experimental.h
  /usr/local/include/node/v8-inspector-protocol.h
  /usr/local/include/node/v8-inspector.h
  /usr/local/include/node/v8-platform.h
  /usr/local/include/node/v8-profiler.h
  /usr/local/include/node/v8-testing.h
  /usr/local/include/node/v8-util.h
  /usr/local/include/node/v8-version.h
  /usr/local/include/node/v8.h
  /usr/local/include/node/v8config.h
  /usr/local/include/node/zconf.h
  /usr/local/include/node/zlib.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libical.la
  /usr/local/lib/libicalss.la
  /usr/local/lib/libicalvcal.la
  /usr/local/lib/libltdl.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/jack.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libdevkit.a
  /usr/local/lib/libhelium_mac.a
  /usr/local/lib/libical.a
  /usr/local/lib/libicalss.a
  /usr/local/lib/libicalvcal.a
  /usr/local/lib/libkld.a
  /usr/local/lib/libredo_prebinding.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  numpy
  node
  unbound

<pre>
HOMEBREW_VERSION: 2.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4493f27db28be7f083737424cecd8edb863ec3f6
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2da0dc898a663118daf535515a9d8eb4052e160f
Core tap last commit: 32 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_131, 1.7.0_80
macOS: 10.15.3-x86_64
CLT: 11.0.33.16
Xcode: 11.3
</pre>

**Comment by interglobalmedia** [comment]
Even though I linked everything I was told to link, unbound could not be linked. Node could not either, but I use nvm anyway, which works just fine. I have been having this issue with Sass since I upgraded to Catalina. My old Sass (pre Dart) no longer worked. That has been deprecated anyway. I don't think it  even works anymore with Catalina.

**Comment by MikeMcQuaid** [comment]
@interglobalmedia This is not a reproducible issue with Homebrew and is specific to your machine. Please read the issue template and make your future requests for help on our Discourse instead.

**Comment by interglobalmedia** [comment]
@MikeMcQuaid Thanks for letting me know. I will checkout Discourse. Thanks.
