### ISSUE TITLE
--verbose option no longer prints system commands in formula

### ISSUE THREAD

**Issue by ankane** [Homebrew/brew#7008]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Use the `--verbose` option when building formula.

## What happened (include command output)

`system` commands in formula are no longer verbose.

<details>
  <summary>Command output</summary>
  <pre>brew install argon2 --build-from-source --verbose
Warning: Your Xcode (10.2.1) is outdated.
Please update to Xcode 11.3 (or delete it).
Xcode can be updated from the App Store.

/usr/bin/sandbox-exec -f /private/tmp/homebrew20200205-7526-1bk3yj5.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/argon2.rb --verbose
==> Downloading https://github.com/P-H-C/phc-winner-argon2/archive/20190702.tar.gz
Already downloaded: /Users/andrew/Library/Caches/Homebrew/downloads/f25e20786542ab640ff347dd02f1029d96a018fa8b4e0efc4bd5012018071240--phc-winner-argon2-20190702.tar.gz
==> make PREFIX=/usr/local/Cellar/argon2/20190702_1 ARGON2_VERSION=20190702
==> make test
==> make install PREFIX=/usr/local/Cellar/argon2/20190702_1 ARGON2_VERSION=20190702
==> Cleaning
==> Finishing up
ln -s ../Cellar/argon2/20190702_1/bin/argon2 argon2
ln -s ../Cellar/argon2/20190702_1/include/argon2.h argon2.h
ln -s ../../Cellar/argon2/20190702_1/share/doc/argon2 argon2
ln -s ../Cellar/argon2/20190702_1/lib/libargon2.1.dylib libargon2.1.dylib
ln -s ../Cellar/argon2/20190702_1/lib/libargon2.a libargon2.a
ln -s ../Cellar/argon2/20190702_1/lib/libargon2.dylib libargon2.dylib
ln -s ../../Cellar/argon2/20190702_1/lib/pkgconfig/libargon2.pc libargon2.pc
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200205-7752-1sb40rn.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/argon2.rb
==> Summary
🍺  /usr/local/Cellar/argon2/20190702_1: 12 files, 591KB, built in 25 seconds
  </pre>
</details>

## What you expected to happen

To see the output of `make`, `make test`, and `make install`.

## Step-by-step reproduction instructions (by running `brew` commands)

```sh
brew install argon2 --build-from-source --verbose
```

Also happens with `reinstall`.

## Output of `brew config` and `brew doctor` commands

<pre>
brew config
HOMEBREW_VERSION: 2.2.5-19-g2555e43
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2555e43a6dcfa6357f7bcf3e1341e36c97b885ee
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b5ce2d4f171f4ac2260e57bd51a8b3e1769c8b36
Core tap last commit: 36 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_192
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.2.1
XQuartz: 2.7.11 => /opt/X11
</pre>

<pre>
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ipython

Warning: Your Xcode (10.2.1) is outdated.
Please update to Xcode 11.3 (or delete it).
Xcode can be updated from the App Store.
</pre>

**Comment by ankane** [comment]
Looks like this was introduced in https://github.com/Homebrew/brew/pull/6983.

**Comment by ankane** [comment]
Temp solution for others that experience this

```sh
cd /usr/local/Homebrew/Library                   
git checkout 52a7c15cc80f021762152fe3754e91f8ae45bdb4
```

**Comment by sramsay** [comment]
Thanks ankane!  Verbosity restored (for now).  Is there any downside to what's going on this branch?  It seemed like this was the accidental side effect of a refactor.  Does this role that back, or does it actually fix the problem?

**Comment by sramsay** [comment]
That branch still isn't working for me.  It won't show the output of either configure or make (with both --build-from-source and --verbose on the brew command, as well as HOMEBREW_VERBOSE=1).

**Comment by EricFromCanada** [comment]
Seems like `Homebrew.args` is coming up empty in `formula.rb`.

**Comment by GauthamGoli** [comment]
> Seems like Homebrew.args is coming up empty in formula.rb

build is done in a separate thread, due to which the issue happening. I'm looking into this.

**Comment by ankane** [comment]
Thanks @GauthamGoli, that fixed it for me.
