### ISSUE TITLE
brew should be able to list infos on formulas that it turns up when searching

### ISSUE THREAD

**Issue by JMoVS** [Homebrew/brew#701]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Brew showed me available formulas to install. I would have expected to list details via brew info, but then said that it didn't find the formula:

`````
unknown002608E8FB53:~ justin$ brew search conda
Caskroom/cask/anaconda                  Caskroom/cask/miniconda                 Caskroom/versions/anaconda2           
unknown002608E8FB53:~ justin$ brew info Caskroom/cask/anaconda
Error: No available formula with the name "caskroom/cask/anaconda"

`````

**Comment by MikeMcQuaid** [comment]
This is something we're going to improve in future as we bring Homebrew and Homebrew Cask closer together but at the moment it's intentional, sorry!
