### ISSUE TITLE
List casks when running brew update

### ISSUE THREAD

**Issue by evitalis** [Homebrew/brew#7011]
# A detailed description of the proposed feature

`brew update` right now only shows formula that have updates but not casks. This can lead to not knowing to run the upgrade for casks in some cases.

# The motivation for the feature

https://github.com/Homebrew/homebrew-cask/issues/76002

# How the feature would be relevant to at least 90% of Homebrew users

Easier notification of updated casks allowing for users to update sooner.

# What alternatives to the feature have been considered

An issue was opened to add this to the `brew cask` subcommand (linked above) but was referred here as the right place for the request.

**Comment by evitalis** [comment]
I still am noticing this issue, not stale.

**Comment by MikeMcQuaid** [comment]
We'll consider a PR that implements this but we don't leave such feature requests open indefinitely (unless @Homebrew/cask wants to do so).

**Comment by vitorgalvao** [comment]
@imichka @reitermarkus May I suggest this as an example of something to stick into the TSC’s plan/timeline?

It’s low priority (far from critical) but highly desirable (I can’t imagine anyone thinking having this would be detrimental), so it seems like a good step to include.

**Comment by reitermarkus** [comment]
This is definitely a feature that definitely needs to happen at some point, so reopening with “help wanted”.

**Comment by MikeMcQuaid** [comment]
Thanks @reitermarkus, @vitorgalvao and @evitalis!

**Comment by johndbritton** [comment]
@michellenguy has a solution for this in #7101.
