### ISSUE TITLE
Feature Request: Update the website with where users can ask for ports?

### ISSUE THREAD

**Issue by StewAlexanderACC** [Homebrew/brew#7012]
Hi all,

Is it possible to add a site or a location or email drop where we the loyal users of homebrew can ask for linux tools we like to be ported to Homebrew for the Mac?

I love the tool [inxi](https://smxi.org/docs/inxi.htm), doesn't appear to be loaded on homebrew (sigh)

Thanks ...

**Comment by StewAlexanderACC** [comment]
From community discussion it appears the process is to attempt to convince the software owner, somehow, to port their tool to homebrew?

That in itself is a process, that I would love to see documented, if it isn’t already.

I suggest this is isn't a user-centric policy, that leaves us at the whim of the developers we do not control.

I understand the difficulties, and perhaps legalities, of porting over someone else's code, so I get it, it just leaves us admins adrift waiting on the intentions of package developers.

Sigh ....

**Comment by StewAlexanderACC** [comment]
Well that last comment is an error, since you only accept open source projects anyone can port the software to homebrew, if they have the skills and the time.

From Homebrew's point of view it appears to be a push process (people push projects to homebrew), rather than a pull ... 

Unfortunately I don't have the immediate skills or the time to port tools to homebrew, but if and when I do, I might as it seems a great way of helping the community.

I still think this could be communicated if it isn't already.

**Comment by iMichka** [comment]
I think that everything is very well documented in the docs: https://brew.sh

> Unfortunately I don't have the immediate skills or the time to port tools to homebrew

You can either learn (the docs explain how to create a pull request), or pay somebody to do it for you.

I'll close this here as I am unsure how and what we should communicate more.
