### ISSUE TITLE
Feature Request: Process to change homebrew to another user on the Mac

### ISSUE THREAD

**Issue by StewAlexanderACC** [Homebrew/brew#7013]
Had a situation where I needed to give my mac to another user, thought I could continue to use homebrew under the new user but chaos happened.

So, if there is a way to move homebrew to another user account on the Mac, is this documented somewhere? If not (and the process exists) can somewhere please write up how to do this and post it somewhere?

If it doesn't exist, is it possible for someone to look into this issue? Thanks ...

**Comment by iMichka** [comment]
This is not a bug in homebrew, and you are posting on the issue tracker here.
Please always fill out the issue template.

You should ask this question on our discourse: https://discourse.brew.sh
