### ISSUE TITLE
All HEAD formulas are broken after installing git-lfs

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#7014]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Install `git-lfs` and keep using `brew` with `--HEAD` version for some formulas.

## What happened (include command output)

After installing `git-lfs` `brew` fails to install/upgrade `HEAD` formulas. `git-lfs --uninstall [--system]` and uninstalling `git-lfs` formula doesn't help. But my git works fine, since I'm able to use it with any other repo, even to clone repos, which `brew` is unable to clone.

<details>
  <summary>Command output</summary>
  <pre>

  brew upgrade --fetch-HEAD 
==> Upgrading 1 outdated package:
winetricks HEAD-1b3a7db -> HEAD-dc9a7c2e86128ef14e2d60b6d18142df25973da4
==> Upgrading winetricks 
==> Cloning https://github.com/Winetricks/winetricks.git
Updating /Users/yurikoles/Library/Caches/Homebrew/winetricks--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "winetricks"
Failure while executing; `git checkout -f master --` exited with 1. Here's the output:
Already on 'master'
Your branch is up to date with 'origin/master'.

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

  </pre>
</details>

## What you expected to happen

`brew` continues to work well despite the fact that `git-lfs` is installed or not.

## Step-by-step reproduction instructions (by running `brew` commands)

```
brew install git-lfs
git-lfs install --system
brew install <any_formula> --HEAD
```

## Output of `brew config` and `brew doctor` commands

<pre>
brew config                   
HOMEBREW_VERSION: 2.2.5-28-gb8c2e96
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8c2e96ee6390803df7bbbc39e66d400b8ebcf52
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1911cda6d4cf4dbf894de73c10417a5561528dc9
Core tap last commit: 70 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: hexa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.2, 13.0.1, 1.8.0_242
macOS: 10.15.4-x86_64
CLT: 11.0.33.16
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

brew doctor               
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  hunspell
  winetricks
  gnupg

</pre>

**Comment by MikeMcQuaid** [comment]
This is a `git-lfs` configuration issue not a Homebrew one, sorry.

**Comment by yurikoles** [comment]
But plain Git commands just work for me, the only issue is brew's wrapped git commands, like checkout of HEAD formulas.

**Comment by yurikoles** [comment]
@MikeMcQuaid sorry for bad report, you are right, I was able to resolve issue in my local setup.

For historical purposes, this line had broke git repos:
```
[core]
hooksPath = ~/.githooks
```

In before I wanted to use some shared hook that removes unwanted white spaces, but when I had enabled `lfs` for one repo it put its hooks to this shared dir, so all git repos become broken.

**Comment by MikeMcQuaid** [comment]
Cool, thanks.
