### ISSUE TITLE
brew deps produces different output when used with --tree option

### ISSUE THREAD

**Issue by dawidd6** [Homebrew/brew#7016]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  ➜  homebrew/homebrew-core neovim ✓  brew deps --tree  neovim
neovim
├── gettext
│   └── ncurses
├── libtermkey
│   ├── unibilium
│   └── ncurses
├── libuv
├── libvterm
├── luajit
├── msgpack
├── unibilium
├── gperf
└── libnsl
    └── libtirpc

➜  homebrew/homebrew-core neovim ✓  brew deps neovim
bzip2
gdbm
gettext
gperf
libnsl
libtermkey
libtirpc
libuv
libvterm
luajit
msgpack
ncurses
openssl@1.1
python@2
readline
sqlite
unibilium
zlib

  </pre>
</details>

## What you expected to happen

I expected `brew deps --tree` to output the same list of formulae as `brew deps`.

## Step-by-step reproduction instructions (by running `brew` commands)

1. Run `brew deps neovim`.
2. Run `brew deps --tree neovim`.
3. See differences in the output.

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.2.5-28-gb8c2e96
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8c2e96ee6390803df7bbbc39e66d400b8ebcf52
Last commit: 3 days ago
Core tap ORIGIN: git@github.com:Homebrew/linuxbrew-core.git
Core tap HEAD: f317076a62d1f45f3a3a8bafa2db38ea06bb8243
Core tap last commit: 50 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/dawidd6/.cache/Homebrew
HOMEBREW_LOGS: /home/dawidd6/.cache/Homebrew/Logs
HOMEBREW_BAT: 1
HOMEBREW_BINTRAY_KEY: set
HOMEBREW_BINTRAY_USER: dawidd6
HOMEBREW_DEVELOPER: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GITHUB_USER: dawidd6
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: 1
HOMEBREW_NO_EMOJI: 1
CPU: quad-core 64-bit unknown_0x6_0x45
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 9.0 build 900
Git: 2.25.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 5.0.0-37-generic x86_64 GNU/Linux
OS: Ubuntu 19.04 (disco)
Host glibc: 2.29
/usr/bin/gcc: 8.3.0
glibc: N/A
gcc: 5.5.0_7
xorg: N/A

-----------------------------

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/linuxbrew-core git origin remote found.
The current git origin is:
  git@github.com:Homebrew/linuxbrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/linuxbrew-core

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /sbin/update-texmf-config
  /bin/apt-config
  /bin/xdelta-config
  /bin/im-config
</pre>

**Comment by jonchang** [comment]
Hmm, dunno if I can repro this. From a fresh `homebrew/brew` docker container:

```console
root@a01e180ace0f:/home/linuxbrew# brew deps --tree neovim
neovim
├── gettext
│   └── ncurses
├── libtermkey
│   ├── unibilium
│   └── ncurses
├── libuv
├── libvterm
├── luajit
├── msgpack
├── unibilium
├── gperf
└── libnsl
    └── libtirpc

root@a01e180ace0f:/home/linuxbrew# brew deps neovim
gettext
gperf
libnsl
libtermkey
libtirpc
libuv
libvterm
luajit
msgpack
ncurses
unibilium
root@a01e180ace0f:/home/linuxbrew# brew ls
gettext  libnsl      libtirpc  libvterm  msgpack  neovim    unibilium
gperf	 libtermkey  libuv     luajit	 ncurses  patchelf
```

**Comment by jonchang** [comment]
Aha, figured it out

```console
root@94b1d38065fd:/home/linuxbrew# git -C $(brew --repo homebrew/core) reset --hard eba35626b052bdc58c82dfbe8088a5b328418442
HEAD is now at eba35626b0 pympress: update 1.5.2 bottle.

root@94b1d38065fd:/home/linuxbrew# brew deps neovim
bzip2
gdbm
gettext
gperf
libnsl
libtermkey
libtirpc
libuv
libvterm
luajit
msgpack
ncurses
openssl@1.1
python@2
readline
sqlite
unibilium
zlib

root@94b1d38065fd:/home/linuxbrew# brew deps --tree neovim
neovim
├── gettext
│   └── ncurses
├── libtermkey
│   ├── unibilium
│   └── ncurses
├── libuv
├── libvterm
├── luajit
├── msgpack
├── unibilium
├── python@2
│   ├── gdbm
│   ├── openssl@1.1
│   ├── readline
│   │   └── ncurses
│   ├── sqlite
│   │   ├── readline
│   │   │   └── ncurses
│   │   └── zlib
│   ├── bzip2
│   ├── ncurses
│   └── zlib
├── gperf
└── libnsl
    └── libtirpc
```

`brew deps` is reading from the formula file in the `.brew` folder of your bottle, whereas `brew deps --tree` seems to be looking at the current state of the repository.

```console
root@94b1d38065fd:/home/linuxbrew# git -C $(brew --repo homebrew/core) reset --hard origin/master                           
HEAD is now at 28646858ea formulae: depend of macos due to Python2
root@94b1d38065fd:/home/linuxbrew# brew deps neovim
bzip2
gdbm
gettext
gperf
libnsl
libtermkey
libtirpc
libuv
libvterm
luajit
msgpack
ncurses
openssl@1.1
python@2
readline
sqlite
unibilium
zlib
root@94b1d38065fd:/home/linuxbrew# brew deps --tree neovim
neovim
├── gettext
│   └── ncurses
├── libtermkey
│   ├── unibilium
│   └── ncurses
├── libuv
├── libvterm
├── luajit
├── msgpack
├── unibilium
├── gperf
└── libnsl
    └── libtirpc
```
