### ISSUE TITLE
tap-new creates pipeline configuration for  unsupported provider 

### ISSUE THREAD

**Issue by sashkab** [Homebrew/brew#7031]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Create new tap with `brew tap-new`

## What happened (include command output)

New tap was created, with unsupported CI provider -- azure pipelines. Support for Azure Pipelines was removed in https://github.com/Homebrew/homebrew-test-bot/pull/325.

## What you expected to happen

CI configuration for the supported CI provider created.

## Step-by-step reproduction instructions (by running `brew` commands)

<details>
```sh
$ brew tap-new sashkab/test01
==> Created sashkab/test01
/usr/local/Homebrew/Library/Taps/sashkab/homebrew-test01
$ ls -la /usr/local/Homebrew/Library/Taps/sashkab/homebrew-test01
total 16
drwxr-xr-x  5 testuser01 admin  160 Feb 13 10:18 .
drwxr-xr-x  4 testuser01 admin  128 Feb 13 10:18 ..
drwxr-xr-x  2 testuser01 admin   64 Feb 13 10:18 Formula
-rw-r--r--  1 testuser01 admin  422 Feb 13 10:18 README.md
-rw-r--r--  1 testuser01 admin  451 Feb 13 10:18 azure-pipelines.yml
```
</details>
## Output of `brew config` and `brew doctor` commands

<pre>
```sh
$ brew doctor                                                                                                                                                           
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 2.2.5-52-g1b2bb23
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1b2bb2380ee1c7515e7fe217061a5276967e2ea7
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e9746a2d19c4ef99733beb17d2c2d7a905563e42
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 14400
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_CLEANUP: y
HOMEBREW_NO_ANALYTICS: 1
CPU: 20-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.3-x86_64
CLT: 11.0.33.16
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```
</pre>

**Comment by MikeMcQuaid** [comment]
Thanks for the report. Yep, we need to address this.
