### ISSUE TITLE
[Request] Can homebrew ignore dependencies that were installed outside of `brew`?

### ISSUE THREAD

**Issue by GingkathFox** [Homebrew/brew#7048]
# A detailed description of the proposed feature

I have Node installed through the .pkg from the site instead of homebrew. if i try to install something that requires node, homebrew downloads node, and then fails to symlink cause node already exists. Can homebrew check for deps before it tries to install them?

# The motivation for the feature

Motivation is not having to type `brew uninstall --ignore-dependencies <package>` every time i install something @w@

# How the feature would be relevant to at least 90% of Homebrew users

Same as above, reduces annoyance for anyone who has installed a cli tool outside of homebrew.

# What alternatives to the feature have been considered

One alternative would be to uninstll the external package and reinstall with homebrew, but ive had issues before by doing that (wine) and it didnt work as well as just getting the .app or .pkg from the site.

**Comment by MikeMcQuaid** [comment]
No, we can't do this, sorry. We did so in the past but it was too unreliable and error-prone.

**Comment by GingkathFox** [comment]
ouch, alrighty. thanks!
