### ISSUE TITLE
brew update is "Already up-to-date." 3 days later?

### ISSUE THREAD

**Issue by ajlowndes** [Homebrew/brew#705]
- [Y] Ran `brew update` (twice) and keep getting "Already up-to-date."
- [Y] Ran `brew doctor`, which always shows "Your system is ready to brew."

### Bug reports:

Considering `brew doctor` used to warn me that 24 hours was a long time in brew-land and that I should update it, it is strange that it still comes up with the above messages when I run either. This hasn't happened to me before, it seems to have always run smoothly

I also ran `brew log`, which showed me the latest commit is 06fe347de97975dc01e726f87bf07a56a6fb713e dated 10 Aug 2016

On the github repo I can see the above commit is dated on 11th August, and there are plenty of commits after this.

**Comment by dunn** [comment]
You got caught in a nasty update bug; the only fix is to manually update the git repository: `cd $(brew --repo); git fetch; git reset --hard origin/master`.

Sorry about that!

**Comment by ajlowndes** [comment]
that worked - thank you!

**Comment by philcook** [comment]
I also got caught out by this, I believe when I upgraded to OSX 10.11.6. This is the only thing I can think.

But it appears that @dunn suggestion fixed this.

**Comment by leesmith** [comment]
Got bit by this too. Thanks for the solution!
