### ISSUE TITLE
brew install URL with encoded characters fail. 

### ISSUE THREAD

**Issue by seivan** [Homebrew/brew#7056]
It's not a big deal and there is a "workaround" for my problem at least, but it should technically work since it's a valid URL. 

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to install this [formula](https://raw.githubusercontent.com/Homebrew/homebrew-core/683015cadb92b38ddf50795eebdc7905e5806c11/Formula/postgresql%4011.rb) using `brew install <url>`

## What happened (include command output)

It failed to install, even though both the formula and the url is valid. 
<details>
  <summary>Command output</summary>
  <pre>

Error: No available formula with the name "postgresql%4011" 
In formula file: ~/Library/Caches/Homebrew/Formula/postgresql%4011.rb
Expected to find class Postgresql%4011, but only found: PostgresqlAT11.

  </pre>
</details>

## What you expected to happen
I expected it to figure out that the formula url path `postgresql%4011.rb` is the same as `postgresql@11.rb`

## Step-by-step reproduction instructions (by running `brew` commands)

```zsh
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/683015cadb92b38ddf50795eebdc7905e5806c11/Formula/postgresql%4011.rb
```

## Output of `brew config` and `brew doctor` commands

<pre>
─➤  brew config                                                                                                       [11:42:57]⎈  
brew doHOMEBREW_VERSION: 2.2.6-18-g5b126ec
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5b126ec850b688cba57a9cf17be08d321ad4d10f
Last commit: 22 hours ago
cCore tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c3f06e4f17853bea8c35742923a9c43d3a244d35
Core tap last commit: 15 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.2-x86_64
CLT: N/A
torXcode: 11.3.1

╰─➤  brew doctor                                                                                                       [11:46:48]⎈  
Your system is ready to brew.

</pre>

## Workaround
Since containing `@`  in an URL is valid, changing the raw address outputted by Github to `https://raw.githubusercontent.com/Homebrew/homebrew-core/683015cadb92b38ddf50795eebdc7905e5806c11/Formula/postgresql@11.rb` actually works. 

So, changing the last path in the URL from `postgresql%4011.rb` to `postgresql@11.rb` fixes it.

**Comment by MikeMcQuaid** [comment]
Glad you found a workaround. We don't support or recommend installing formulae from GitHub URLs like that so closing this out.

**Comment by seivan** [comment]
@MikeMcQuaid 
What is the recommend approach for an older formula that isn't available using `AT` tags? 

Can also mention that it breaks even is a local file path, is that also not recommended?

**Comment by MikeMcQuaid** [comment]
> What is the recommend approach for an older formula that isn't available using `AT` tags?

Adapt the output of `brew extract` to meet your needs. More specifically: stop using `python@2` as it's EOL.

**Comment by seivan** [comment]
@MikeMcQuaid Who mentioned Python? Are you saying stop using the `Postgres@11.6` syntax for using older published formulas?

**Comment by MikeMcQuaid** [comment]
Sorry, confused with another issue, my apologies.
