### ISSUE TITLE
Documentation Issue for macOS 10.15

### ISSUE THREAD

**Issue by kreig303** [Homebrew/brew#7059]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

This is a documentation issue (and `zsh` shell configuration only) not a `brew` issue per se. The above steps are not specifically relevant.

Would have added comment to #6590 (filed by @realnc) but that issue is locked.

## What happened (include command output)

```
% rm -f ~/.zcompdump; compinit
```
<details>
  <summary>Command output</summary>
  <pre>

zsh: command not found: compinit

  </pre>
</details>

## What you expected to happen

No output; command accepted.

## Step-by-step reproduction instructions (by running `brew` commands)

n/a

## Output of `brew config` and `brew doctor` commands

```
% brew doctor
Your system is ready to brew.
% brew config
HOMEBREW_VERSION: 2.2.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 27fa87c94a6cf7be40fc8f8fc96bc7c387b7781e
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 55a880ba621d6faa321ed05cf3c6a5d88c07ee45
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.3-x86_64
CLT: 11.0.33.16
Xcode: 11.3.1
```
---

cf. https://github.com/Homebrew/brew/issues/6590#issuecomment-541582407. It was asked by @MikeMcQuaid  if other users ran into the issue; I ran into the issue just now.

The `.zshrc` config suggested by @vernadsky in https://github.com/Homebrew/brew/issues/6590#issuecomment-549205215 would seem to be the appropriate addition to the documentation. This resolved the issue for me.

**Comment by MikeMcQuaid** [comment]
> The `.zshrc` config suggested by @Vernadsky in [#6590 (comment)](https://github.com/Homebrew/brew/issues/6590#issuecomment-549205215) would seem to be the appropriate addition to the documentation. This resolved the issue for me.

Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by kreig303** [comment]
@MikeMcQuaid 

Absolutely! I'll sort that today.

**Comment by kreig303** [comment]
@MikeMcQuaid 

Two scenarios exist which would be good to validate:

1. **User has/does not have `oh-my-zsh.sh` installed.**
I am wondering if the issue is not macOS per se but `zsh` shells which don't have that in place.
1. **Linux.**
I don't have a Linux installation at the moment.

Nevertheless I have included the revised docs in a PR which should land soon. I highly doubt the invocation will conflict with `oh-my-zsh` and will not cause issue on "the other Unix".

**Comment by MikeMcQuaid** [comment]
> * I am wondering if the issue is not macOS per se but `zsh` shells which don't have that in place.

This is not the case, I don't have it and it works for me.



> Nevertheless I have included the revised docs in a PR which should land soon. I highly doubt the invocation will conflict with `oh-my-zsh` and will not cause issue on "the other Unix".

Thanks!

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/pull/7065, nice work!

**Comment by ziyi-yan** [comment]
I just had the same issue and I think these startup script documentation should also be added to the Caveats of `brew info zsh-completions` output, which is still lack of the information now.
```
~ $ brew info zsh-completions
zsh-completions: stable 0.31.0, HEAD
Additional completion definitions for zsh
https://github.com/zsh-users/zsh-completions
/usr/local/Cellar/zsh-completions/0.31.0 (136 files, 1MB) *
  Built from source on 2020-02-24 at 00:26:39
From: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/Formula/zsh-completions.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
To activate these completions, add the following to your .zshrc:

  fpath=(/usr/local/share/zsh-completions $fpath)

You may also need to force rebuild `zcompdump`:

  rm -f ~/.zcompdump; compinit

Additionally, if you receive "zsh compinit: insecure directories" warnings when attempting
to load these completions, you may need to run this:

  chmod go-w '/usr/local/share'
==> Analytics
install: 11,053 (30 days), 36,687 (90 days), 171,448 (365 days)
install-on-request: 10,663 (30 days), 35,214 (90 days), 164,277 (365 days)
build-error: 0 (30 days)
~ $ brew info zsh-completions
zsh-completions: stable 0.31.0, HEAD
Additional completion definitions for zsh
https://github.com/zsh-users/zsh-completions
/usr/local/Cellar/zsh-completions/0.31.0 (136 files, 1MB) *
  Built from source on 2020-02-24 at 00:26:39
From: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/Formula/zsh-completions.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
To activate these completions, add the following to your .zshrc:

  fpath=(/usr/local/share/zsh-completions $fpath)

You may also need to force rebuild `zcompdump`:

  rm -f ~/.zcompdump; compinit

Additionally, if you receive "zsh compinit: insecure directories" warnings when attempting
to load these completions, you may need to run this:

  chmod go-w '/usr/local/share'
==> Analytics
install: 11,053 (30 days), 36,687 (90 days), 171,448 (365 days)
install-on-request: 10,663 (30 days), 35,214 (90 days), 164,277 (365 days)
build-error: 0 (30 days)
```
