### ISSUE TITLE
No updates for three days

### ISSUE THREAD

**Issue by elpres** [Homebrew/brew#706]
Running `brew update` simply says `Already up-to-date.` `brew doctor` says `ready to brew`. What can I do to diagnose/fix?

```bash
% brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 06fe347de97975dc01e726f87bf07a56a6fb713e
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bcb5cf680ae83de77e0ab35657f6d7fd014b28a0
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
OS X: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11

% brew update
Already up-to-date.

% date
Sat Aug 13 09:34:47 CEST 2016
```

**Comment by MikeMcQuaid** [comment]
You hit a bug unfortunately. The fix is `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`.

**Comment by elpres** [comment]
Great, thank you very much!

**Comment by eccstartup** [comment]
Great!

**Comment by ska80** [comment]
Thanks! I had the same problem.

**Comment by davidfokkema** [comment]
I had it too. How  many people have this problem and are unaware of the fix? I had to scroll down the list of open issues, and then the list of closed issues. Maybe there is a better place?

**Comment by MikeMcQuaid** [comment]
It's in the README (https://github.com/Homebrew/brew#update-bug), ISSUE_TEMPLATE (https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE.md) and was posted on Twitter.

**Comment by davidfokkema** [comment]
How did I miss all that? I'll shut up now. Thanks!

**Comment by zviratko** [comment]
How can people know they have an issue when there's no error? I was wondering if this was a slow week with no updates until I found time to look for it.
No idea what the bug is, but maybe you should break "brew update" in some way to make people aware of the issue?

**Comment by MikeMcQuaid** [comment]
> No idea what the bug is, but maybe you should break "brew update" in some way to make people aware of the issue?

We cannot do anything to `brew update`s broken in this manner because it won't check for updates to itself. We've advertised it everywhere we think people would look but I'm open to suggestions of anywhere else to put it.

**Comment by zviratko** [comment]
I don't know what "brew update" does under the hood, I suppose something similiar to "git pull"? Can't you make that origin url return 404 so brew update returns an error?

Something like
1) create new URL that clients should use
2) update brew to use this url
3) wait 14 days for "non broken" brew clients to update themselves
4) drop the original URL
5) broken clients now get a clear error so people know they have an issue and start googling

**Comment by MikeMcQuaid** [comment]
The problem with this bug was: it wasn't looking at any URL, ever. Trust me, if it was possible I'd have done it rather than asking people to run commands manually 😭

**Comment by zviratko** [comment]
Oops. Never mind, then :-) Thanks.

**Comment by retokromer** [comment]
Seriously, I don’t think it’s _per se_ a bad thing, if people have exceptionally to run a few commands… Kudos to the maintainers for their great job!

**Comment by aren55555** [comment]
@MikeMcQuaid perhaps adding a `brew reset` command that executed `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update` would help folks have a recourse path if an issue like this ever happened again

**Comment by MikeMcQuaid** [comment]
@aren55555 We have that now pretty much in `brew update --force` which I added almost immediately afterwards.

**Comment by fuzzy76** [comment]
I guess this is really a duplicate of #688

**Comment by MikeMcQuaid** [comment]
Yes.
