### ISSUE TITLE
`brew audit` fails on Linux without zlib headers

### ISSUE THREAD

**Issue by xanderlent** [Homebrew/brew#7062]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

I've reproduced it in multiple environments, [see below](#reproduce) for one such case.

## What you were trying to do (and why)

I was fixing a formula with Linuxbrew. (The mandoc formula [did not specify a zlib dependency](https://github.com/Homebrew/homebrew-core/pull/50457).) As is required for contributions to core taps, I invoked `brew audit --strict mandoc`.

## What happened (include command output)

The command, `brew audit --strict mandoc`, failed because the nokogiri gem failed to build native extensions. The output of this process helpfully notes that zlib was not found. (Note that the output differs on subsequent runs with the failure because previously-installed gems are re-used.) Installing my OS's zlib headers and retrying the command caused it to succeed.

<details>
<summary>Command output</summary>
<pre>
Fetching gem metadata from https://rubygems.org/.........
Fetching concurrent-ruby 1.1.6
Fetching minitest 5.14.0
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Installing minitest 5.14.0
Installing concurrent-ruby 1.1.6
Fetching zeitwerk 2.2.2
Fetching ast 2.4.0
Installing zeitwerk 2.2.2
Installing ast 2.4.0
Using bundler 1.17.2
Fetching connection_pool 2.2.2
Fetching json 2.3.0
Fetching docile 1.3.2
Installing connection_pool 2.2.2
Installing docile 1.3.2
Installing json 2.3.0 with native extensions
Fetching simplecov-html 0.10.2
Using sync 0.5.0
Fetching thor 1.0.1
Installing thor 1.0.1
Installing simplecov-html 0.10.2
Fetching diff-lcs 1.3
Fetching unf_ext 0.0.7.6
Installing diff-lcs 1.3
Fetching hpricot 0.8.6
Installing unf_ext 0.0.7.6 with native extensions
Installing hpricot 0.8.6 with native extensions
Fetching jaro_winkler 1.5.4
Installing jaro_winkler 1.5.4 with native extensions
Fetching mime-types-data 3.2019.1009
Installing mime-types-data 3.2019.1009
Fetching net-http-digest_auth 1.4.1
Installing net-http-digest_auth 1.4.1
Fetching mini_portile2 2.4.0
Installing mini_portile2 2.4.0
Fetching ntlm-http 0.1.1
Installing ntlm-http 0.1.1
Fetching webrobots 0.1.2
Installing webrobots 0.1.2
Fetching mustache 1.1.1
Installing mustache 1.1.1
Fetching parallel 1.19.1
Installing parallel 1.19.1
Fetching plist 3.5.0
Installing plist 3.5.0
Fetching rainbow 3.0.0
Installing rainbow 3.0.0
Fetching rdiscount 2.2.0.1
Installing rdiscount 2.2.0.1 with native extensions
Fetching rexml 3.2.4
Installing rexml 3.2.4
Fetching rspec-support 3.9.2
Installing rspec-support 3.9.2
Fetching ruby-progressbar 1.10.1
Installing ruby-progressbar 1.10.1
Fetching unicode-display_width 1.6.1
Installing unicode-display_width 1.6.1
Fetching ruby-macho 2.2.0
Installing ruby-macho 2.2.0
Fetching tzinfo 1.2.6
Installing tzinfo 1.2.6
Fetching parser 2.7.0.2
Fetching i18n 1.8.2
Installing i18n 1.8.2
Installing parser 2.7.0.2
Fetching net-http-persistent 3.1.0
Installing net-http-persistent 3.1.0
Fetching tins 1.24.1
Fetching simplecov 0.16.1
Installing tins 1.24.1
Installing simplecov 0.16.1
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching mime-types 3.3.1
Fetching nokogiri 1.10.8
Installing mime-types 3.3.1
Fetching parallel_tests 2.31.0
Installing parallel_tests 2.31.0
Fetching rspec-core 3.9.1
Installing rspec-core 3.9.1
Fetching rspec-expectations 3.9.0
Installing nokogiri 1.10.8 with native extensions
Installing rspec-expectations 3.9.0
Fetching rspec-mocks 3.9.1
Installing rspec-mocks 3.9.1
Fetching activesupport 6.0.2.1
Installing activesupport 6.0.2.1
Fetching rubocop 0.80.0
Installing rubocop 0.80.0
Fetching domain_name 0.5.20190701
Installing domain_name 0.5.20190701
Fetching term-ansicolor 1.7.1
Installing term-ansicolor 1.7.1
Fetching rspec-retry 0.6.2
Installing rspec-retry 0.6.2
Fetching rspec-its 1.3.0
Installing rspec-its 1.3.0
Fetching rspec 3.9.0
Installing rspec 3.9.0
Fetching rubocop-performance 1.5.2
Installing rubocop-performance 1.5.2
Fetching rubocop-rspec 1.38.1
Installing rubocop-rspec 1.38.1
Fetching http-cookie 1.0.3
Installing http-cookie 1.0.3
Fetching coveralls 0.8.23
Installing coveralls 0.8.23
Fetching rspec-wait 0.0.9
Installing rspec-wait 0.0.9
Fetching ronn 0.7.3
Installing ronn 0.7.3
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.<br />
current directory:
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.8/ext/nokogiri
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby -I
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0 -r
./siteconf20200221-14907-k1mg1h.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.<br />
Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build<br />
To see why this extension failed to compile, please check the mkmf.log which can be found here:<br />
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0-static/nokogiri-1.10.8/mkmf.log<br />
extconf failed, exit code 1<br />
Gem files will remain installed in
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.8 for inspection.
Results logged to
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0-static/nokogiri-1.10.8/gem_make.out<br />
An error occurred while installing nokogiri (1.10.8), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.8' --source 'https://rubygems.org/'` succeeds before bundling.<br />
In Gemfile:
  mechanize was resolved to 2.7.6, which depends on
    nokogiri
</pre>
</details>

## What you expected to happen

I expected `brew audit` to successfully install its dependencies and complete the audit.

I don't expect to need to install my OS's zlib headers, because under normal circumstances Homebrew/Linuxbrew is self-contained outside of `curl`, `file`, `git` and `build-essential` or `Development Tools` or equivalent. (This list comes from the [Linuxbrew documentation](https://docs.brew.sh/Homebrew-on-Linux).)  For example, Homebrew/Linuxbrew downloads portable Ruby, and any formula that `uses_from_macos "zlib"` will be provided with a brewed zlib on Linux.

## <a name="reproduce"></a>Step-by-step reproduction instructions (by running `brew` commands)

Start with a fresh minimal install of a Debian-based system. I can reproduce this in multiple environments, including [Canonical's multipass](https://multipass.run/), used below. You can use any formula you like, including `hello`, though `mandoc` is used below.

In an environment provided by `multipass shell`:

1.) [Install Linuxbrew and required dependencies](https://docs.brew.sh/Homebrew-on-Linux)
2.) `brew install -s mandoc`
3.) `brew test mandoc`
4.) `brew audit --strict mandoc`
5.) `sudo apt-get install zlib1g-dev`
6.) `brew audit --strict mandoc`

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.2.6-25-g5ebc478
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5ebc47872757c0a797edb441306aa72ebda0781f
Last commit: 37 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: cc6c24aa6bc86e46894d8ba844fa41fc08ac0d8d
Core tap last commit: 4 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/ubuntu/.cache/Homebrew
HOMEBREW_LOGS: /home/ubuntu/.cache/Homebrew/Logs
HOMEBREW_DEV_CMD_RUN: 1
CPU: single-core 64-bit &lt;cpu model&gt;
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.15.0-88-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.4 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.4.0
glibc: N/A
gcc: N/A
xorg: N/A
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by xanderlent** [comment]
I'm still seeing this issue on Debian stretch and Debian buster. I wasn't able to test Ubuntu bionic, but I suspect it also appears there. This isn't a major issue, since it's in a developer command and doesn't happen on macOS.

I'm not sure what an acceptable resolution would be. The simplest option is probably documenting the system-level zlib dependency for `brew audit` on Linux. We might try outputting a warning when attempting to audit without zlib headers. I think other possible solutions might be using brewed zlib for audit on Linux or shipping zlib with the portable binaries provided by Homebrew.

**Comment by MikeMcQuaid** [comment]
> We might try outputting a warning when attempting to audit without zlib headers.

I'd suggest an error rather than warning. This seems like a good resolution. Someone who cares sufficiently should submit a PR.
