### ISSUE TITLE
Should `brew audit` complain about incorrect file permissions?

### ISSUE THREAD

**Issue by alexreg** [Homebrew/brew#7068]
Should `brew audit` actually complain about incorrect file permissions for formulas when the permissions aren't actually committed by Git? (I have them changed because I use `brewdo` but need group-write permissions to the tap for using Git there in an ergonomic manner.)

**Comment by MikeMcQuaid** [comment]
I think it should, yes.

Please always fill in the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by alexreg** [comment]
@MikeMcQuaid Okay, lots more info now.

**Comment by MikeMcQuaid** [comment]
> That said, it would be of great use to brewdo users, and is trivial to implement.

Given this: we'll review a PR.

**Comment by alexreg** [comment]
@MikeMcQuaid Thanks. I'll have a go.
