### ISSUE TITLE
Allow tap installation with options

### ISSUE THREAD

**Issue by rdp** [Homebrew/brew#7084]
# A detailed description of the proposed feature

I would like to be able to install taps "with options".

# The motivation for the feature

One liner vs. two liner for being able to install taps with options.

ex: $ brew install rdp/homebrew-openssh-gssapi/openssh-patched --with-gssapi-support

# How the feature would be relevant to at least 90% of Homebrew users

More efficient tap usage.

# What alternatives to the feature have been considered

Today it says the following:
```
$  brew install rdp/homebrew-openssh-gssapi/openssh-patched --with-gssapi-support

Usage: brew install [options] formula

Install formula. Additional options specific to formula may be appended to
the command.
...
Error: invalid option: --with-gssapi-support
```

Suggestion/feature request: make it work with options on taps.  Another option: change the error message, ex: "if this is a tap, please run tap first..." [?] The current output seems inaccurate since it is a valid option, and the output seems to imply that "options specific to formula may be appended"...

See also #6242 

Thanks!

**Comment by MikeMcQuaid** [comment]
We need to have parsed the arguments before we can resolve the formula names so I don't see an easy way to handle this. We'll review a PR to update the command document (in `cmd/install` and generated with `brew man`), though!
