### ISSUE TITLE
try install opencv 

### ISSUE THREAD

**Issue by fabriciofconde** [Homebrew/brew#7097]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem? Yes
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? Yes
- [ ] ran `brew config` and `brew doctor` and included their output with your issue? Yes

## What you were trying to do (and why)

Install lib opencv to study IA face recognition

## What happened (include command output)

After cmd "brew install --build-from-source opencv"...

<details>
  <summary>Command output</summary>
  <pre>
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.

==> Downloading https://github.com/opencv/opencv/archive/4.2.0.tar.gz
Already downloaded: /Users/fabricio/Library/Caches/Homebrew/downloads/2606bd5bbd9d3231837dd3bc1f76c1a935cb4ce0eae9c2a472fd15c77dfbb510--opencv-4.2.0.tar.gz
==> Downloading https://github.com/opencv/opencv_contrib/archive/4.2.0.tar.gz
Already downloaded: /Users/fabricio/Library/Caches/Homebrew/downloads/47ad25f9dd163b753420e122bad3928281696bdb5cd1c925fc90cf82e91ccda5--opencv_contrib-4.2.0.tar.gz
==> cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET= -DBUILD_JASPER=OFF -DBUILD_JPEG=ON -DBUILD_OPENEXR=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_PNG=OFF -DBUILD_TESTS=OFF
==> make
Last 15 lines from /Users/fabricio/Library/Logs/Homebrew/opencv/02.make:
[ 24%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/wrappers.pb.cc.o
cd /tmp/opencv-20200301-37502-6pq40p/opencv-4.2.0/build/3rdparty/protobuf && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DHAVE_PTHREAD=1 -I/tmp/opencv-20200301-37502-6pq40p/opencv-4.2.0/build/3rdparty/ippicv/ippicv_mac/icv/include -I/tmp/opencv-20200301-37502-6pq40p/opencv-4.2.0/build/3rdparty/ippicv/ippicv_mac/iw/include -I/tmp/opencv-20200301-37502-6pq40p/opencv-4.2.0/build -isystem /tmp/opencv-20200301-37502-6pq40p/opencv-4.2.0/3rdparty/protobuf/src  -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wstrict-prototypes -Winit-self -Wpointer-arith -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-prototypes -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-sign-compare -Wno-sign-promo -Wno-undef -Wno-tautological-undefined-compare -Wno-ignored-qualifiers -Wno-extra -Wno-unused-function -Wno-unused-const-variable -Wno-shorten-64-to-32 -Wno-invalid-offsetof -Wno-enum-compare-switch -Wno-suggest-override -Wno-inconsistent-missing-override -Wno-implicit-fallthrough -Wno-array-bounds -DNDEBUG  -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC   -std=c++11 -o CMakeFiles/libprotobuf.dir/src/google/protobuf/wrappers.pb.cc.o -c /tmp/opencv-20200301-37502-6pq40p/opencv-4.2.0/3rdparty/protobuf/src/google/protobuf/wrappers.pb.cc
[ 24%] Linking CXX static library ../lib/liblibprotobuf.a
cd /tmp/opencv-20200301-37502-6pq40p/opencv-4.2.0/build/3rdparty/protobuf && /usr/local/Cellar/cmake/3.16.4/bin/cmake -P CMakeFiles/libprotobuf.dir/cmake_clean_target.cmake
cd /tmp/opencv-20200301-37502-6pq40p/opencv-4.2.0/build/3rdparty/protobuf && /usr/local/Cellar/cmake/3.16.4/bin/cmake -E cmake_link_script CMakeFiles/libprotobuf.dir/link.txt --verbose=1
/usr/bin/ar qc ../lib/liblibprotobuf.a  CMakeFiles/libprotobuf.dir/src/google/protobuf/arena.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/arenastring.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/extension_set.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/generated_message_table_driven_lite.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/generated_message_util.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/io/coded_stream.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/io/zero_copy_stream.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/io/zero_copy_stream_impl_lite.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/message_lite.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/repeated_field.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/bytestream.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/common.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/int128.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/io_win32.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/once.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/status.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/statusor.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/stringpiece.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/stringprintf.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/structurally_valid.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/strutil.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/time.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/wire_format_lite.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/any.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/any.pb.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/api.pb.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/descriptor.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/descriptor.pb.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/descriptor_database.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/duration.pb.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/dynamic_message.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/empty.pb.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/extension_set_heavy.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/field_mask.pb.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/generated_message_reflection.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/generated_message_table_driven.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/io/gzip_stream.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/io/printer.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/io/strtod.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/io/tokenizer.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/io/zero_copy_stream_impl.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/map_field.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/message.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/reflection_ops.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/service.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/source_context.pb.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/struct.pb.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/mathlimits.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/substitute.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/text_format.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/timestamp.pb.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/type.pb.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/unknown_field_set.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/delimited_message_util.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/field_comparator.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/field_mask_util.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/datapiece.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/default_value_objectwriter.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/field_mask_utility.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/json_escaping.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/json_objectwriter.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/json_stream_parser.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/object_writer.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/proto_writer.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/protostream_objectsource.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/protostream_objectwriter.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/type_info.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/utility.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/json_util.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/message_differencer.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/time_util.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/util/type_resolver_util.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/wire_format.cc.o CMakeFiles/libprotobuf.dir/src/google/protobuf/wrappers.pb.cc.o
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(arenastring.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(io_win32.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
/usr/bin/ranlib ../lib/liblibprotobuf.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(arenastring.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(io_win32.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
[ 24%] Built target libprotobuf
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.
  </pre>
</details>

## What you expected to happen

No problem!

## Step-by-step reproduction instructions (by running `brew` commands)

brew install --build-from-source opencv

## Output of `brew config` and `brew doctor` commands

<pre>
brew config
HOMEBREW_VERSION: 2.2.6-69-g6a42a66
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6a42a66e034a7ae4b4b279a7ff487a8f4941e1ff
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5c961940b126c9958c1a9ae889aa4676d2e1b794
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_231, 1.6.0_65-b14-468
macOS: 10.15.3-x86_64
CLT: 11.0.33.8
Xcode: 11.3.1

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
</pre>

**Comment by vitorgalvao** [comment]
From [the templates list](https://github.com/Homebrew/brew/issues/new/choose):
![image](https://user-images.githubusercontent.com/1699443/75631912-d14c3d00-5bee-11ea-8c27-4b500177b831.png)

You’re on the wrong repo. You want https://github.com/Homebrew/homebrew-core/issues/new/choose.
