### ISSUE TITLE
installation of lammps fails without vim

### ISSUE THREAD

**Issue by jfikar** [Homebrew/brew#7106]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew install lammps

## What happened (include command output)

the package kim-api fails, cannot find xxd
it is in vim, brew install vim cures the problem
kim-api should depend on vim

<details>
  <summary>Command output</summary>
  <pre>

-- Found KIM-API: kim-api (Required is at least version "2.0") 
-- Could NOT find XXD (missing: XXD_EXECUTABLE) 
CMake Error at cmake/kim-api-config.cmake:463 (message):
  The xxd utility is required to build models and drivers.
Call Stack (most recent call first):
  examples/model-drivers/ex_model_driver_P_LJ/CMakeLists.txt:55 (add_kim_api_model_driver_library)

-- Configuring incomplete, errors occurred!
See also "/tmp/kim-api-20200303-71272-zxtvfd/kim-api-2.1.3/CMakeFiles/CMakeOutput.log".

  </pre>
</details>

## What you expected to happen

should install

## Step-by-step reproduction instructions (by running `brew` commands)

brew install lammps

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.2.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69ad3d09730aedd62ba44c02cfd8483d695fdcd9
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 091075a972b9667441e47284411f5903a45d69c6
Core tap last commit: 17 hours ago
HOMEBREW_PREFIX: /home/1T/fik/.linuxbrew
HOMEBREW_CELLAR: /home/1T/fik/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/1T/fik/.cache/Homebrew
HOMEBREW_LOGS: /home/1T/fik/.cache/Homebrew/Logs
HOMEBREW_REPOSITORY: /home/1T/fik/.linuxbrew/Homebrew
HOMEBREW_SYSTEM_CURL_TOO_OLD: 1
CPU: 40-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/1T/fik/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.25.0 => /home/1T/fik/.linuxbrew/bin/git
Curl: 7.68.0 => /home/1T/fik/.linuxbrew/opt/curl/bin/curl
Kernel: Linux 3.10.0-1062.4.3.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.7.1908 (Core)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.23
gcc: 5.5.0_7
xorg: N/A

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

</pre>

**Comment by issyl0** [comment]
Hi! You raised this in the wrong repo - it should have been raised in Homebrew/linuxbrew-core where the Linux package definitions are. However, you've found the fix! :muscle:

Please [raise a pull request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#formulae-related-pull-request) to add `uses_from_macos "vim"` below the other `depends_on` lines in the formula in Homebrew/linuxbrew-core, then on the next install, Homebrew will pull in `vim`.

Thanks!
