### ISSUE TITLE
Installing (linux)brew fails with: Error: Git is unavailable (but git 2.19.1 is installed)

### ISSUE THREAD

**Issue by ckeeling** [Homebrew/brew#7107]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [?] ran `brew update` and can still reproduce the problem?
- [?] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [?] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Fresh install of brew locally onto linux system, where:
```bash
git --version
git version 2.19.1
which git
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/bin/git
```

```bash
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

## What happened (include command output)

It failed with error.

<details>
  <summary>Command output</summary>
  <pre>

```bash
...
==> Pouring portable-ruby-2.6.3.x86_64_linux.bottle.tar.gz
Error: Git is unavailable
Error: Failure while executing; `/home/ckeeling/.linuxbrew/bin/brew tap homebrew/core` exited with 1.
Error: Git must be installed and in your PATH!
Failed during: /home/ckeeling/.linuxbrew/bin/brew update --force
```

  </pre>
</details>

## Output of `brew config` and `brew doctor` commands

<pre>
brew not installed so brew command is not found
</pre>

**Comment by MikeMcQuaid** [comment]
Please report this to the Linuxbrew/install repo.
