### ISSUE TITLE
`brew bump-formula-pr` did not catch the already opened PR

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/brew#7108]
https://github.com/Homebrew/homebrew-core/pull/51046 is essentially the duplicate PR of https://github.com/Homebrew/homebrew-core/pull/50895 (besides the sha256 difference). 

Not quite sure what would be reason for `brew bump-formula-pr` failed to check the already opened PR.

**Comment by EricFromCanada** [comment]
`bump-formula-pr#fetch_pull_requests` searches for open pull requests whose title contains the name of the changed formula followed by either a colon or space. It missed #50895 because the formula name is followed by a dash.

**Comment by MikeMcQuaid** [comment]
Given @EricFromCanada's comment I don't think is is actionable, sorry!

**Comment by chenrui333** [comment]
yeah, that is what I thought too.  Thanks for confirming it.
