### ISSUE TITLE
Error after updating to brew version 2.2.8

### ISSUE THREAD

**Issue by tokawpl** [Homebrew/brew#7115]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing [carthage-copy-frameworks](https://github.com/lvillani/carthage-copy-frameworks) via brew.
Why? Avoiding [error prone](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos) iOS framework adding .

## What happened (include command output)

Installation failed with a Ruby error.

<details>
  <summary>Command output</summary>
  <pre>
  Error: An exception occurred within a child process:
  NoMethodError: undefined method `delete' for nil:NilClass
  </pre>
</details>

## What you expected to happen

Successful installation.

## Step-by-step reproduction instructions (by running `brew` commands)

<pre>
brew install lvillani/tap/carthage-copy-frameworks
</pre>

## Output of `brew config` and `brew doctor` commands
`brew doctor`:
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/<username>/.pyenv/shims/python-config
  /Users/<username>/.pyenv/shims/python3-config
  /Users/<username>/.pyenv/shims/python3.8-config
</pre>

`brew config`
<pre>
HOMEBREW_VERSION: 2.2.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 89fd3cc234c5f47bb807eb97613eb614184d51c3
Last commit: 57 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 999e8d8129268ccafa9f4e4e785724044be6eb2e
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AWS_ACCESS_KEY_ID: set
HOMEBREW_AWS_SECRET_ACCESS_KEY: set
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.2, 11.0.5, 1.8.0_232
macOS: 10.15.3-x86_64
CLT: N/A
Xcode: 11.3.1
</pre>

**Comment by MikeMcQuaid** [comment]
Please run `brew install --debug ...` and paste the output.

**Comment by tokawpl** [comment]
<pre>
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/lvillani/homebrew-tap/Formula/carthage-copy-frameworks.rb
==> Installing carthage-copy-frameworks from lvillani/tap
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::AliasLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/lvillani/homebrew-tap/Formula/carthage-copy-frameworks.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::AliasLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
==> Downloading https://github.com/lvillani/carthage-copy-frameworks/archive/v2.0.0.tar.gz
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.8\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --location --silent --head --request GET https://github.com/lvillani/carthage-copy-frameworks/archive/v2.0.0.tar.gz
Already downloaded: /Users/tka/Library/Caches/Homebrew/downloads/882ec6d16c8039878574289d942d75a8476d63d117aa79a10dee7c756b26795b--carthage-copy-frameworks-2.0.0.tar.gz
tar xof /Users/tka/Library/Caches/Homebrew/downloads/882ec6d16c8039878574289d942d75a8476d63d117aa79a10dee7c756b26795b--carthage-copy-frameworks-2.0.0.tar.gz -C /private/tmp/d20200304-30341-115o0ha
cp -pR /private/tmp/d20200304-30341-115o0ha/carthage-copy-frameworks-2.0.0/. /private/tmp/carthage-copy-frameworks-20200304-30341-1vlvys/carthage-copy-frameworks-2.0.0
/usr/local/Homebrew/Library/Homebrew/language/python.rb:177:in `virtualenv_install_with_resources'
NoMethodError: undefined method `delete' for nil:NilClass
1. raise
2. backtrace
3. shell
Choose an action:
</pre>

**Comment by MikeMcQuaid** [comment]
CC @iMichka that https://github.com/lvillani/homebrew-tap/blob/master/Formula/carthage-copy-frameworks.rb is no longer a valid formula after the Python changes.

**Comment by benjohnde** [comment]
Ah that's good news, so we could fork that one over there and could modify it according to your changes. Could you give us a hint what should be changed? I highly believe it has something to do with the virtualenv usage. Still, we couldn't find any information at all that there were breaking changes released, that's a bit sad :( Thanks a lot for your fast response!!

**Comment by MikeMcQuaid** [comment]
> Could you give us a hint what should be changed?

I'm not sure anything needs to be changed, I need @iMichka to verify why this is an error. It's likely a bug.

**Comment by iMichka** [comment]
I can have a look in 3-4 hours when I am back. I am travelling right now, but I will be able to connect in the train back home.

**Comment by iMichka** [comment]
Here is the failing code: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/python.rb#L168-L181

**Comment by iMichka** [comment]
> depends_on "python@3"

That's unusual. It should be `depends_on "python"` or `depends_on "python@3.8"`

**Comment by benjohnde** [comment]
That's not relevant here, both version descriptions are valid. I just found out that for the case if you want to build from source or your formula does not contain a bottle brew is broke right now.

Can easily be tested with any python formula which uses `virtualenv_install_with_resources`, for instance `brew install --build-from-source git-revise`. We also got other ci processes which fail because of that.

**Comment by Bo98** [comment]
> Here is the failing code: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/python.rb#L168-L181

The removal of `python = wanted.first || "python2.7"`. Is problematic. Now `wanted` isn't used at all and `python` won't be set at all in that `if` block.

**Comment by MikeMcQuaid** [comment]
@Bo98 Good catch, could you submit a PR?

**Comment by benjohnde** [comment]
Thanks for all the quick help! Nice catch @Bo98!

**Comment by Bo98** [comment]
#7116.

**Comment by benjohnde** [comment]
@MikeMcQuaid Is there any ETA für an upcoming release? As mentioned above, all Python builds are currently broken if there exists no bottle or building from sources.

**Comment by MikeMcQuaid** [comment]
@benjohnde There is a new release now.

**Comment by benjohnde** [comment]
That's super awesome! Thanks a million for the quick help ❤️!

**Comment by iMichka** [comment]
Thanks all for the fixes ! :)

**Comment by mitch-seymour** [comment]
We're seeing the same issue with one of our internal packages. We're also using `virtualenv_install_with_resources`  but our package depends on python 2, not python 3. We're also using the latest brew version, which should have @Bo98 's fix.

```bash
$ brew --version
Homebrew 2.2.9-23-g78140ce
```

What's interesting is if we change `depends_on "python@2"` to `depends_on "python@3"`, the package installs (but our python code isn't compatible with python 3, so this isn't really a fix).

Unfortunately, our package and formula aren't open source. But I was able to reproduce by copying the formula mentioned in this bug report to a personal tap, and changing the dependency to `python@2`.

You can therefore reproduce this ongoing bug using the following command:

```bash
$ brew install mitch-seymour/tap/carthage-copy-frameworks
==> Auto-updated Homebrew!
Updated 1 tap (mitch-seymour/tap).
No changes to formulae.

Updating Homebrew...
==> Installing carthage-copy-frameworks from mitch-seymour/tap
==> Downloading https://github.com/lvillani/carthage-copy-frameworks/archive/v2.0.0.tar.gz
Already downloaded: /Users/mseymour/Library/Caches/Homebrew/downloads/882ec6d16c8039878574289d942d75a8476d63d117aa79a10dee7c756b26795b--carthage-copy-frameworks-2.0.0.tar.gz
Error: An exception occurred within a child process:
  NoMethodError: undefined method `delete' for nil:NilClass
```

**Comment by Bo98** [comment]
That'll be because Homebrew no longer has any knowledge of what "python@2" is and thus does not recognise it as a Python formula.

You could use `virtualenv_install_with_resources, :using => "python2"`.

**Comment by mitch-seymour** [comment]
Thanks @Bo98 , that fixed our issue :)
