### ISSUE TITLE
Installed Homebrew formulas are always preferred over other ways to satisfy dependencies

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/brew#712]
Build#expand_reqs has the following logic:

``` ruby
      elsif req.satisfied? && req.default_formula? && (dep = req.to_dependency).installed?
        deps << dep
        Requirement.prune
      end
```

This is what we want _if_ the requirement was satisfied by the installed default_formula. It is probably _not_ what we want if `satisfy` found some other way to satisfy the requirement.

**Comment by MikeMcQuaid** [comment]
Can you elaborate on why this is a problem and what formulae (if any) it's currently negatively affecting? Thanks!

**Comment by tdsmith** [comment]
The way I discovered this was I was trying to test macvim against a pyenv python3 with Homebrew python3 installed. Even though the pyenv python3 was first in PATH, `--with-python3` (which triggers a `Python3Requirement`) ended up building against the Homebrew python3.

We sometimes describe the behavior of the `PythonRequirement`s as "building against the first python in PATH," which is not exactly the observed behavior.

We could wontfix as a documentation bug; I'd prefer that we finally fully-bake an API for adding paths to superenv environments as the result of a satisfy operation.

**Comment by tdsmith** [comment]
(Sorry, filed this on a plane, didn't want to forget about it)

**Comment by MikeMcQuaid** [comment]
> Even though the pyenv python3 was first in PATH, --with-python3 (which triggers a Python3Requirement) ended up building against the Homebrew python3.

I see. Makes sense to tweak this (but obviously will need tested with a bunch of other things as this code is prone to 💥).

> I'd prefer that we finally fully-bake an API for adding paths to superenv environments as the result of a satisfy operation.

Something beyond Requirements? Feels like that may be overkill.

**Comment by ilovezfs** [comment]
@tdsmith I think this may work:
```
diff --git a/Library/Homebrew/build.rb b/Library/Homebrew/build.rb
index 8915e94..22b1dd9 100644
--- a/Library/Homebrew/build.rb
+++ b/Library/Homebrew/build.rb
@@ -49,7 +49,7 @@ class Build
         Requirement.prune
       elsif req.build? && dependent != formula
         Requirement.prune
-      elsif req.satisfied? && req.default_formula? && (dep = req.to_dependency).installed?
+      elsif req.satisfied? && req.default_formula? && req.uses_default? && (dep = req.to_dependency).installed?
         deps << dep
         Requirement.prune
       end
diff --git a/Library/Homebrew/requirement.rb b/Library/Homebrew/requirement.rb
index 7a40d41..f653b00 100644
--- a/Library/Homebrew/requirement.rb
+++ b/Library/Homebrew/requirement.rb
@@ -56,9 +56,17 @@ class Requirement
   def satisfied?
     result = self.class.satisfy.yielder { |p| instance_eval(&p) }
     @satisfied_result = result
+    if default_formula? && Pathname === result
+      installed_prefix = Formula[default_formula].installed_prefix
+      @uses_default = result.realpath.to_s.include? installed_prefix
+    end
     !!result
   end
 
+  def uses_default?
+    @uses_default
+  end
+
   # Overriding #fatal? is deprecated.
   # Pass a boolean to the fatal DSL method instead.
   def fatal?
diff --git a/Library/Homebrew/requirements/python_requirement.rb b/Library/Homebrew/requirements/python_requirement.rb
index 2800f52..7948f4c 100644
--- a/Library/Homebrew/requirements/python_requirement.rb
+++ b/Library/Homebrew/requirements/python_requirement.rb
@@ -11,7 +11,7 @@ class PythonRequirement < Requirement
     version = python_short_version
     next unless version
     # Always use Python 2.7 for consistency on older versions of OSX.
-    version == Version.create("2.7")
+    version == Version.create("2.7") ? python : false
   end
 
   env do
```

**Comment by MikeMcQuaid** [comment]
> We could wontfix as a documentation bug

I'd prefer this, actually. We know building against our `default_formula` is definitely going to work so I do think it should be preferable if already installed.
