### ISSUE TITLE
--quiet is an unrecognized option

### ISSUE THREAD

**Issue by noloader** [Homebrew/brew#7121]
According to the [brew docs](https://docs.brew.sh/Manpage), `--quiet` is a global option available to all commands:

```
GLOBAL OPTIONS

These options are applicable across all sub-commands.

    -q, --quiet: Suppress any warnings.
    -v, --verbose: Make some output more verbose.
    -d, --debug: Display any debugging information.
    -f, --force: Override warnings and enable potentially unsafe operations.
```

When I attempt to use `--quiet` to cut down on the irrelevant noise from Brew ([from Travis](https://travis-ci.org/noloader/unbound/jobs/658382456)):

```
brew update --quiet
brew install --quiet autoconf automake libtool
```

It results in an error:

```
Updated 2 taps (homebrew/cask and homebrew/core).
==> New Formulae
abseil                                   killswitch
ansible@2.8                              kind
...
homebrew/cask/x-lite
homebrew/cask/ynab

Usage: brew install [options] formula

Install formula. Additional options specific to formula may be appended to
the command.

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will then be run for

the installed formulae or, every 30 days, for all formulae.

    -d, --debug                      If brewing fails, open an interactive
                                     debugging session with access to IRB or a
    ...
                                     shell inside the temporary build directory.
    -h, --help                       Show this message.

Error: invalid option: --quiet
```

**Comment by MikeMcQuaid** [comment]
Please fill in the issue template.

**Comment by noloader** [comment]
Keep i broke. Great engineering :)

**Comment by MikeMcQuaid** [comment]
Don't read or fill in issue templates that provide us with the information we need to do our work: great issue reporting.

**Comment by noloader** [comment]
As simple as the following on Travis:

```
brew update --quiet
brew install --quiet autoconf automake libtool
```

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by noloader** [comment]
My job is to report the errors. Your job is to reporduce them.

Don't worry about blocking me. I won't waste my time in the future.
