### ISSUE TITLE
delete old package after download the new package.

### ISSUE THREAD

**Issue by s7v7nislands** [Homebrew/brew#7135]
# A detailed description of the proposed feature

delete old package after download the new package. 

# The motivation for the feature

when the network is slow, you can't use the old package.

# How the feature would be relevant to at least 90% of Homebrew users

# What alternatives to the feature have been considered

**Comment by s7v7nislands** [comment]
why close this issue?

**Comment by MikeMcQuaid** [comment]
You didn't fill out the template and what you have written makes very little sense.
