### ISSUE TITLE
Allow for two headers to be set when pulling a formula

### ISSUE THREAD

**Issue by ctompkinson** [Homebrew/brew#7138]
# A detailed description of the proposed feature

Currently, you cannot set more than one header when using homebrew, see:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/download_strategy.rb#L424

I would like to be able to set two or more headers on a homebrew request

# The motivation for the feature

Currently, I am using homebrew as a private repository and would like to pull some built artefacts from Github but that requires the header `Accept: application/octet-stream` but as per deprecation notices from github for the URL parameter `access_token` I should also use the header `Authorization: token TOKEN`

Currently, this isn't possible as you can only set one header :(

# How the feature would be relevant to at least 90% of Homebrew users

It makes it difficult to comply with github deprecation notices and have a private repository

# What alternatives to the feature have been considered

I'd have to move from github to separate system for storing my artefacts (not releases) which would be a hassle, I wondered if I could overload the existing header field but I couldn't find a way.

Maybe we could have a separate meta field called `headers` that splits the result and appends `--header` to each.

**Comment by MikeMcQuaid** [comment]
> Maybe we could have a separate meta field called `headers` that splits the result and appends `--header` to each.

We'll consider accepting a PR that implements this. Thanks!
