### ISSUE TITLE
`brew doctor` should list deleted formulae

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#7139]
As inspired by https://discourse.brew.sh/t/list-removed-formulae/6898/3 we should list deleted formulae that a user has installed in the `brew doctor` output. This would be useful in nudging users to uninstall them or find replacements.

No need to say "I'm planning on working on this" or similar in this issue but feel free to open a PR that doesn't work (yet!) and ask for help.

**Comment by whathebug** [comment]
Hi @MikeMcQuaid  I am new to Homebrew can I work on this with your guidance?

**Comment by MikeMcQuaid** [comment]
Feel free!

**Comment by ivy-2000** [comment]
Hi! I would like to take up this issue. 
My approach would be to first create a list of deleted formulae and then call it in the brew doctor output.
Could you direct me to the file that can possibly contain a list of all formulae so a list of deleted formulae could be created there as well. @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/diagnostic.rb

**Comment by MikeMcQuaid** [comment]
That's for `brew doctor` and getting the list of formula would be from methods in `formula.rb`

**Comment by vitorgalvao** [comment]
This would be welcome for casks as well. Pointing it out because even if it’s not done in the initial PR, it would be desirable to at least build it in a way that the person that continues the work for casks doesn’t have to rewrite a lot of the code.

**Comment by hyuraku** [comment]
@MikeMcQuaid 
I have a question.
Which `deleted formulae` means `deleted formula in the last month` or `all deleted formula`?
I thought `brew doctor` would search deleted formula in the last month like `brew info` below.
```bash
brew info Foo
Error: No available formula with the name "Foo"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
```

**Comment by MikeMcQuaid** [comment]
@hyuraku All deleted formulae. There should be no need to search through the history; this would be a formula that's already installed (i.e. has a `Keg`) but `Formula[f]` cannot find it.

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/pull/7585
