### ISSUE TITLE
Duplicate homebrew/core

### ISSUE THREAD

**Issue by nickeb96** [Homebrew/brew#714]
I have the exact same issue with homebrew/core being duplicated as in #420. brew update shows everything twice and brew tap shows two homebrew/core. No issues from doctor and I have run update and nothing has changed.

```
Nick$ ls -AlF "$(brew --repository)"/Library/Taps/*
/usr/local/Library/Taps/caskroom:
total 16
-rw-r--r--@  1 Nick  admin  6148 Jun 13 12:36 .DS_Store
drwxr-xr-x  31 Nick  admin  1054 Aug 12 08:57 homebrew-cask/

/usr/local/Library/Taps/homebrew:
total 24
-rw-r--r--@   1 Nick  admin  8196 Jun 13 12:36 .DS_Store
drwxr-xr-x   42 Nick  admin  1428 Aug 11 19:49 homebrew-completions/
drwxr-xr-x   11 Nick  admin   374 Aug 14 16:14 homebrew-core/
drwxr-xr-x  160 Nick  admin  5440 Aug 14 16:14 homebrew-games/
drwxr-xr-x    4 Nick  admin   136 Aug 12 08:46 homebrew-homebrew/
drwxr-xr-x    7 Nick  admin   238 Aug 12 08:46 homebrew-tex/
```

```
Nick$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 4309a19a7cbaec0cce496a5a1fe459cee087dfd7
Last commit: 79 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c4eb468d80dfff6e5d05df1d8e32d0ee11686045
Core tap last commit: 43 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102, 1.6.0_65-b14-468
OS X: 10.11.5-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

```
Nick$ brew tap
caskroom/cask
homebrew/completions
homebrew/core
homebrew/games
homebrew/core
homebrew/tex
```

Please check out this closed issue #420 as it is pretty much the same issue and covers a lot. I would have just reopened it if I could.

My output is mostly the same as the mentioned issue and I imagine I can fix with the same solution. However it is clearly not a "singular event" as described in that issue. I will refrain from fixing it for a few days in case people want me to test things that might help them figure out the root cause. There was some interest and curiosity in finding out how it happened.

On that note I believe I started having the issue when I tapped homebrew/games and homebrew/tex and the following output supports that statement.

```
Nick$ ls /usr/local/Library/Taps/homebrew/homebrew-homebrew
games
tex
```

If you read through #420 you would see that homebrew-homebrew is the cause of duplicates.

**Comment by MikeMcQuaid** [comment]
> My output is mostly the same as the mentioned issue and I imagine I can fix with the same solution. However it is clearly not a "singular event" as described in that issue. I will refrain from fixing it for a few days in case people want me to test things that might help them figure out the root cause. There was some interest and curiosity in finding out how it happened.

https://github.com/Homebrew/brew/pull/591 should stop it recurring so I think it's worth just manually fixing for now and then filing another issue if it crops up again after https://github.com/Homebrew/brew/pull/591 being merged. How's that sound?

**Comment by nickeb96** [comment]
I have fixed it and it is no longer showing duplicates and if it happens again I will open a new issue. Thanks
