### ISSUE TITLE
Seriously? How do I stop a service?

### ISSUE THREAD

**Issue by blaasvaer** [Homebrew/brew#7148]
With all that documentation and the entire internet to search ... how is it possible to not be able to find anything about how to stop a service I started using:
```
brew service start ... yadda yadda
```
Why isn't there a corresponding stop command!?

**Comment by blaasvaer** [comment]
Well, ONLY after posting this I find homebrew-services  ... but still NOTHING of the sort in the docs. Please, at least make a note, as it seems A LOT of users EXPECT this since you get a start command ... this is pure UX. But important none the less.

**Comment by jonchang** [comment]
`brew services --help`

> Please, at least make a note, as it seems A LOT of users EXPECT this since you get a start command ... this is pure UX. But important none the less.

Feel free to open a pull request if you find the documentation to be insufficient.

**Comment by MikeMcQuaid** [comment]
@blaasvaer In future:
- adjust your communication to be significantly more diplomatic or you will end up being blocked
- read the `man brew` which points you towards both https://github.com/Homebrew/homebrew-services and `brew services --help`.
- always fill out the issue template

**Comment by blaasvaer** [comment]
@MikeMcQuaid how exactly would you prefer I "adjust my communication to be significantly more diplomatic"? What 'diplomatic standard' did I violate? Was it the CAPITALs? Which to some people come of as yelling … ? If that is what you mean (please, be more specific) I'm sorry, maybe I should have just wrapped them in  * **asterisks** * ... to make then stand out instead?

**Comment by blaasvaer** [comment]
On the documentation page for Homebrew (https://docs.brew.sh/Manpage) I can search the documentation (allegedly) by typing into the search field ... but, if I type 'stop' I get nothing. If I search the entire page (in the browser) for 'stop' I get nothing ... I'm just wondering why leave out a basic command like this in the docs ... by just refering to the '--help' command? It seems like one has actually made an effort in hiding stuff.

**Comment by MikeMcQuaid** [comment]
> how exactly

Ok, I'll break it down:

> With all that documentation and the entire internet to search

This is hyperbole and unhelpful. You also made it clear you did not read all the documentation (it's not clear how much of it you have read at all).

> how is it possible to not be able to find anything

This is also hyperbole. It is possible.

> Why isn't there a corresponding stop command!?

There is. The `!?` is a bit heated.

> Well, ONLY after posting this I find homebrew-services ... but still NOTHING of the sort in the docs.

The capital letters are generally treated in online communication as shouting. Additionally, there is something in the docs.

> Please, at least make a note, as it seems A LOT of users EXPECT this since you get a start command ... this is pure UX.

More "shouting".

Metacomment: from the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

You did not read, fill this out or provide any of the requested information. If you had you would have submitted this to Discourse as it is a question not a reproducible bug or feature request.

> If that is what you mean (please, be more specific) I'm sorry, maybe I should have just wrapped them in * **asterisks** * ... to make then stand out instead?

There is no need to make them stand out. Again, your tone in this response is unnecessarily confrontational and aggressive.

I expect your response may be (and excuse me if it isn't or wouldn't be) "I don't think there has been any problem with my communication and you (@MikeMcQuaid) have misunderstood me". Regardless, if you're going to ask for help on our project then you need to ask in a way that we consider polite and respectful even if you think it is unnecessary. To be clear, I'm not making any claims that you think or feel that way but I'm just preempting responses we have seen in previous similar situations.

I've treated your request for more details in good faith. I hope this provides clarification, thanks!

**Comment by MikeMcQuaid** [comment]
> On the documentation page for Homebrew (https://docs.brew.sh/Manpage) I can search the documentation (allegedly) by typing into the search field ... but, if I type 'stop' I get nothing.

If you type "services" you get directed to `--help` and https://github.com/Homebrew/homebrew-services.

> It seems like one has actually made an effort in hiding stuff.

This is another bad faith accusation. This is my final warning: adjust your communication or you will be blocked.

**Comment by blaasvaer** [comment]
@MikeMcQuaid thanks for clearing that out. On the other hand I will (try to) break down how one usually approach this whole thing of using other peoples packages. Now remember, we're in the process of actually getting some work done, right. So, installing Homebrew in an effort to become more effiecient ... I guess that's part of the purpose of Homebrew, we make a search ... get a link ... click it ... and end up on the Homebrew website. And let's be honest, we both know very well that reading the docs is not the first thing we do, right. We look for "How to install" or "How to download" or whatever. Done. Now we need to start a service ... we google "how to start a service using homebrew" ... get a link ... click it ... get a command `"brew services start ..."` We get on with doing work. Then at some point we need to stop the service ... we google ... and get ... well, nothing ... we then turn to the home of Homebrew and start looking ... and that's more of an effort than it really needs to be. Why not simply add all the good stuff to the already very long page of stuff?

And may I suggest then that you add words like start and stop to services? That way we're just a tad closer to find what where looking for ... pretty please, with sugar on top.

And now, please feel free to block me if I stepped on anybody toes ...

**Comment by MikeMcQuaid** [comment]
> Why not simply add all the good stuff to the already very long page of stuff?

Because it's not simple to do so, I'm afraid.

> And may I suggest then that you add words like start and stop to services?

They are in the services documentation. They aren't in the `man brew` documentation. We may consider doing so in future.

> pretty please, with sugar on top.

Please avoid the sarcasm.

**Comment by blaasvaer** [comment]
I would do:

```
$ brew services --help
Usage: brew services subcommand

Manage background services with macOS' launchctl(1) daemon manager.

If sudo is passed, operate on /Library/LaunchDaemons (started at boot).
Otherwise, operate on ~/Library/LaunchAgents (started at login).

    [sudo] brew services [list]
      List all running services for the current user (or root).

    [sudo] brew services run (formula|--all)
      Run the service formula without registering to launch at login (or
boot).

    [sudo] brew services start (formula|--all)
      Start the service formula immediately and register it to launch at login
(or boot).

    [sudo] brew services stop (formula|--all)
      Stop the service formula immediately and unregister it from launching at
login (or boot).

    [sudo] brew services restart (formula|--all)
      Stop (if necessary) and start the service formula immediately and
register it to launch at login (or boot).

    [sudo] brew services cleanup
      Remove all unused services.

        --all                        Run subcommand on all services.
    -h, --help                       Show this message.
samblaasvaer@sams-macbook-pro htdocs $ 
```

and then copypaste it into the rest of the markup under the corresponding seciton ... but as you said: it's not so simple to do. Let's just leave it at that then. Thanks.

**Comment by MikeMcQuaid** [comment]
> but as you said: it's not so simple to do

Indeed because that would become outdated because it's dynamically generated.



> Let's just leave it at that then. Thanks.

Will do. You're welcome, thanks!

**Comment by MikeMcQuaid** [comment]
I've opened https://github.com/Homebrew/brew/pull/7156 to hopefully autogenerate this properly in future.

**Comment by blaasvaer** [comment]
Great, crossing my fingers ; )
