### ISSUE TITLE
Python3 not working

### ISSUE THREAD

**Issue by qingkaikong** [Homebrew/brew#715]
# Please follow the general troubleshooting steps first:

- [Yes ] Ran `brew update` and retried your prior step?
- [ Yes] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:
I have a version of python 2 from miniconda, today I try to use python 3 on my mac, I tried to install from 'brew install python3', but when I start the python3 shell, I got an error:

<img width="1438" alt="screen shot 2016-08-14 at 10 30 31 pm" src="https://cloud.githubusercontent.com/assets/1621324/17656420/cc90dac8-626e-11e6-9e4a-8fc37a42c1f9.png">

It seems python3 get access to the python 2 site-packages. Not sure if this is the problem due to the homebrew install version of the python3, or some other issues. Thanks!

**Comment by mistydemeo** [comment]
Do you have `PYTHONPATH` set? Python 3 uses it too, so it would see your miniconda Python 2 site-packages if so.

**Comment by qingkaikong** [comment]
Great, thanks for the quick response! It does seem the problem comes from the PYTHONPATH! After I modify it, everything works fine now. Thanks!
