### ISSUE TITLE
invalid attribute for formula '**' version (nil)

### ISSUE THREAD

**Issue by duwanqiebi** [Homebrew/brew#7150]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I want to execute the command `brew tap riscv/riscv`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  ➜  ~ brew tap riscv/riscv
==> Tapping riscv/riscv
Cloning into '/usr/local/Homebrew/Library/Taps/riscv/homebrew-riscv'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 467 (delta 4), reused 10 (delta 4), pack-reused 457
Receiving objects: 100% (467/467), 65.97 KiB | 8.00 KiB/s, done.
Resolving deltas: 100% (289/289), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/riscv/homebrew-riscv/riscv-pk.rb
invalid attribute for formula 'riscv/riscv/riscv-pk': version (nil)
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/riscv/homebrew-riscv/riscv-gnu-toolchain.rb
invalid attribute for formula 'riscv/riscv/riscv-gnu-toolchain': version (nil)
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/riscv/homebrew-riscv/riscv-isa-sim.rb
invalid attribute for formula 'riscv/riscv/riscv-isa-sim': version (nil)
Error: Cannot tap riscv/riscv: invalid syntax in tap!

  </pre>
</details>

## What you expected to happen

execute the command successfully

## Step-by-step reproduction instructions (by running `brew` commands)

```
brew tap riscv/riscv
```

## Output of `brew config` and `brew doctor` commands

<pre>
➜  ~ brew config
HOMEBREW_VERSION: 2.2.10
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 48a1637b24a0c329905a981f4cff547c7fa47943
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: 9443972f6a0efcdd07ba36ca123e9412e44f6887
Core tap last commit: 83 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_231
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
</pre>

**Comment by EricFromCanada** [comment]
The listed formula in that tap [fail to validate](https://github.com/Homebrew/brew/issues/7110#issuecomment-594201528) because they don't have a version that can be parsed from the URL nor a declared `version`.
