### ISSUE TITLE
homebrew suggests running an upgrade command that doesn't upgrade

### ISSUE THREAD

**Issue by andrew** [Homebrew/brew#7154]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade from a previously installed version of [qri](https://github.com/qri-io/homebrew-qri) (0.7.3) to the latest (0.9.6)

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew install qri-io/qri/qri
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 30c4383e8 to 776e8fd37.
No changes to formulae.

==> Installing qri from qri-io/qri
Error: qri 0.7.3 is already installed
To upgrade to 0.9.6, run `brew upgrade qri`.
$ brew upgrade qri
Warning: qri 0.7.3 already installed

  </pre>
</details>

## What you expected to happen

homebrew suggests running `brew upgrade qri` but then only prints a warning that 0.7.3 is already installed

## Step-by-step reproduction instructions (by running `brew` commands)

```
brew install https://raw.githubusercontent.com/qri-io/homebrew-qri/78d8e7b67dee8b159c7fbef9956db6d25f573d34/qri.rb

brew upgrade qri
```

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.2.10-20-g776e8fd
ORIGIN: https://github.com/Homebrew/brew
HEAD: 776e8fd37378b63e31799e4c693f85c626215b4d
Last commit: 7 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cae58c2e8f4652b2520d17f11ef66fe11c522984
Core tap last commit: 71 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 9.0.1, 1.8.0_172
macOS: 10.15.4-x86_64
CLT: 11.0.33.17
Xcode: N/A
</pre>

**Comment by MikeMcQuaid** [comment]
I still cannot reproduce this using your instructions (including with my own additions).

> brew install https://raw.githubusercontent.com/qri-io/homebrew-qri/78d8e7b67dee8b159c7fbef9956db6d25f573d34/qri.rb

```

==> Consider using `brew extract qri ...`!
This will extract your desired qri version to a stable tap instead of
installing from an unstable URL!

######################################################################## 100.0%
==> Downloading https://github.com/qri-io/qri/releases/download/v0.7.3/qri_darwi
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
🍺  /usr/local/Cellar/qri/0.7.3: 3 files, 46.2MB, built in 13 seconds
```

This presents a "Consider using" warning that could be more strongly worded, I'll admit. Improved in https://github.com/Homebrew/brew/pull/7155

> ```
> brew upgrade qri
> ```

```
Warning: qri 0.7.3 already installed
```

This is expected because you've installed from a URL.

If I run `brew tap qri-io/qri` and then `brew upgrade qri`:

```
==> Upgrading 1 outdated package:
qri-io/qri/qri 0.7.3 -> 0.9.6
==> Upgrading qri-io/qri/qri 0.7.3 -> 0.9.6 
==> Downloading https://github.com/qri-io/qri/releases/download/v0.9.6/qri_darwi
Already downloaded: /Users/mike/Library/Caches/Homebrew/downloads/b5544cf49efb4ae05c8898372437b6654ecb812ce6210970f3b9bdbec97d8aa2--qri_darwin_amd64.zip
🍺  /usr/local/Cellar/qri/0.9.6: 4 files, 61.3MB, built in 4 seconds
Removing: /usr/local/Cellar/qri/0.7.3... (3 files, 46.2MB)
Removing: /Users/mike/Library/Caches/Homebrew/qri--0.7.3.zip... (22.5MB)
==> Checking for dependents of upgraded formulae...
==> No dependents found!
```

This upgrades as expected.

> ## Output of `brew config` and `brew doctor` commands

What did/does `brew doctor` output? 

Was this how you originally installed `qri`? Can you still reproduce the originally issue somehow on your machine?

**Comment by andrew** [comment]
I had not originally installed 0.7.3 from a commit, when I originally installed it last year, it was with `brew install qri-io/qri/qri`, but i couldn't find any other way to be able to install the older version to make this reproducible. 

I didn't originally report it because I knew it would be difficult to reproduce.

Brew doctor said everything was fine: `Your system is ready to brew.`

Weird thing I get when listing `brew info qri` now: 

```
$ brew info qri
qri: stable 0.7.3
Global dataset version control system built on the distributed web
https://qri.io/
/usr/local/Cellar/qri/0.7.3 (3 files, 46.2MB) *
  Built from source on 2020-03-11 at 12:03:55
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qri.rb
```

**Comment by andrew** [comment]
Same result after uninstalling qri 0.7.3 and attempting again:

```
$ brew uninstall qri
Uninstalling /usr/local/Cellar/qri/0.7.3... (3 files, 46.2MB)
$ brew cleanup
Warning: Skipping composer: most recent version 1.10.0 not installed
Warning: Skipping python: most recent version 3.7.7 not installed
$ brew install https://raw.githubusercontent.com/qri-io/homebrew-qri/78d8e7b67dee8b159c7fbef9956db6d25f573d34/qri.rb
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
cocktail                                 zoho-mail

==> Consider using `brew extract qri ...`!
This will extract your desired qri version to a stable tap instead of
installing from an unstable URL!

######################################################################## 100.0%
==> Downloading https://github.com/qri-io/qri/releases/download/v0.7.3/qri_darwi
Already downloaded: /Users/andrewnesbitt/Library/Caches/Homebrew/downloads/52a5bba0e9445f7e49161290817b26b5d1d868fc737c27d11fee26f0268e7013--qri_darwin_386.zip
🍺  /usr/local/Cellar/qri/0.7.3: 3 files, 46.2MB, built in 4 seconds
$ brew tap qri-io/qri
$ brew upgrade qri
Warning: qri 0.7.3 already installed
```

**Comment by MikeMcQuaid** [comment]
@andrew Can I see the output of `cat /usr/local/Cellar/qri/*/INSTALL_RECEIPT.json` and `brew tap-info --installed`? Thanks!

**Comment by MikeMcQuaid** [comment]
And also: `find /usr/local/Homebrew/Library/Taps -name qri.rb`

**Comment by andrew** [comment]
```
$ cat /usr/local/Cellar/qri/*/INSTALL_RECEIPT.json
cat: /usr/local/Cellar/qri/*/INSTALL_RECEIPT.json: No such file or directory
```

```
$ brew tap-info --installed
brewsci/science: unpinned, 414 formulae
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science (469 files, 1.3MB)
From: https://github.com/brewsci/homebrew-science

homebrew/bundle: unpinned, 1 command
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle (453 files, 651.8KB)
From: https://github.com/Homebrew/homebrew-bundle

homebrew/cask: unpinned, 1 command, 3494 casks
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3,764 files, 92.7MB)
From: https://github.com/Homebrew/homebrew-cask

homebrew/cask-versions: unpinned, 156 casks
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (1,992 files, 60.9MB)
From: https://github.com/Homebrew/homebrew-cask-versions

homebrew/core: unpinned, 2 commands, 4928 formulae
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (5,660 files, 104.5MB)
From: https://github.com/Homebrew/homebrew-core

homebrew/services: unpinned, 1 command
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (267 files, 296.2KB)
From: https://github.com/Homebrew/homebrew-services

qri-io/qri: unpinned, 1 formula
/usr/local/Homebrew/Library/Taps/qri-io/homebrew-qri (28 files, 28.8KB)
From: https://github.com/qri-io/homebrew-qri
```

```
$ find /usr/local/Homebrew/Library/Taps -name qri.rb
/usr/local/Homebrew/Library/Taps/qri-io/homebrew-qri/qri.rb
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qri.rb
```

**Comment by MikeMcQuaid** [comment]
> ```
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qri.rb
> ```

This is your problem. That's a file you've created somehow in homebrew/homebrew-core which confuses things because it's what you installed from (and `brew upgrade` won't try to upgrade you from a homebrew-core package to a random one in a tap for security reasons).

**Comment by andrew** [comment]
Ah, I guess that must be left over from when I helped qri write their tap last year, it doesn't show up as an untracked file in git for the homebrew directory (looks like its .gitignored).

I wonder if there's a way brew doctor can help diagnose that?

Still very confusing that brew told me to upgrade but they wouldn't actually do the upgrade though.

**Comment by MikeMcQuaid** [comment]
> Still very confusing that brew told me to upgrade but they wouldn't actually do the upgrade though.

Tweaking the messaging in https://github.com/Homebrew/brew/pull/7159



> I wonder if there's a way brew doctor can help diagnose that?

Good idea, done in https://github.com/Homebrew/brew/pull/7160
