### ISSUE TITLE
"HOMEBREW_DEVELOPER" description in man page could use an update

### ISSUE THREAD

**Issue by justinclift** [Homebrew/brew#716]
The man page info for `HOMEBREW_DEVELOPER` seems a bit out of date these days, compared to it's actual functionality:

```
If set, Homebrew will print warnings that are only relevant to Homebrew developers
(active or budding).
```

It seems like there's some kind of auto-update mechanism around now, which forcibly resets /usr/local back to master branch.  And blows away all uncommitted changes at the same time.

Guess how I found out? 😁 

@tdsmith mentioned on IRC that the `HOMEBREW_DEVELOPER` variable should probably stop that from happening. (thanks @tdsmith!)

It would be pretty useful to have that documented better so others can avoid this same mishap. :wink:

**Comment by ilovezfs** [comment]
You need to git stash pop if you don't have HOMEBREW_DEVELOPER set. It's running git stash, not blowing your work away.

**Comment by MikeMcQuaid** [comment]
> You need to git stash pop if you don't have HOMEBREW_DEVELOPER set. It's running git stash, not blowing your work away.

(which a printed message told you).

I'm not convinced I want to get into the habit of documenting everything HOMEBREW_DEVELOPER does but we could tweak it to be a bit more encompassing.

**Comment by justinclift** [comment]
Guys, if a printed message told me that, I would have seen it. 😦

**Comment by justinclift** [comment]
Thinking about it more, it's possible some message was printed out and lost in the `--verbose` output.

But I didn't run `--verbose` every time, and I really don't remember seeing a message. 😦 

Anyway, the point is more that this variable should be a bit more prominent in the man page, along with it's purpose and what it does. :smile:

**Comment by ilovezfs** [comment]
I don't think we want most users ever setting it, so making it prominent in the man page seems somewhat counterproductive since the effect will be more users setting it.

**Comment by MikeMcQuaid** [comment]
> I don't think we want most users ever setting it, so making it prominent in the man page seems somewhat counterproductive since the effect will be more users setting it.

I agree.

**Comment by justinclift** [comment]
Heh Heh Heh

I guess I'm misunderstanding the target audience for that variable then.

So far my understanding is that it's for people working on Homebrew or the various formulas.

Is that wrong?

**Comment by ilovezfs** [comment]
For most contributors, setting `HOMEBREW_NO_AUTO_UPDATE` while editing files in-place is probably a less sledgehammery approach.

**Comment by justinclift** [comment]
Yep, reading the description of that in the man page, it sounds like the right kind of thing:

```
HOMEBREW_NO_AUTO_UPDATE
              If set, Homebrew will not auto-update before running brew install and brew upgrade.
```

Is tweaking to say something like this feasible?

```
HOMEBREW_NO_AUTO_UPDATE
              If set, Homebrew will not auto-update before running brew install and brew upgrade.

              If you are making manual changes in formulas, such as editing them prior to submission,
              you'll want to set this.  Otherwise Homebrew will `git stash` your changes, and
              they'll seem to disappear.  
```

**Comment by MikeMcQuaid** [comment]
@justinclift I don't think so. `brew update` tells you when it's stashed your changes and this is unrelated to autoupdate as `brew update` itself has the same behaviour.

**Comment by justinclift** [comment]
k.  Is this a recent change, or is it just something I've managed to miss through luck?

**Comment by ilovezfs** [comment]
It's related in that someone working on a formula upgrade is likely to be running brew install multiple times while doing that work, and wouldn't want to have to keep popping the changes, so it'd be one or the other, HOMEBREW_DEVELOPER or HOMEBREW_NO_AUTO_UPDATE that they'd want to set for the duration of the work.

But I agree that these subtleties don't belong in the man page. More so, it would belong in the docs on how to contribute to Homebrew, etc.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/pull/679#issuecomment-239663569

2 days ago is an eternity, so no not recent ;)

**Comment by justinclift** [comment]
Ahhh got it.  Feel free to change the title of this issue to reflect "in the docs" (etc) rather than in the manpage.

It's just the man page was one of the first things I checked after the conversation on IRC.  For someone coming at this from a different direction (eg not hitting the problem at the time), yeah, the man page may not be the right place for them to learn about it before experiencing it. 😁

**Comment by ilovezfs** [comment]
The brew-update-stashes-but-doesn't-pop-unless-developer thing has been around for months though. It's only auto update that's new.

**Comment by justinclift** [comment]
Ok.  As a data point, for me it's extremely rare for me to run brew update.  I may have only run it 5 times (total) ever if that.

That's because I blow away all of my formulas very often:

    $ brew remove `brew list` --force

... generally prior to doing new formula development, Qt development, etc.  So... they don't last long enough to need an update.  Rarely more than 2-3 days.

`brew install` though, I run all the time. :smile:

**Comment by MikeMcQuaid** [comment]
Do you mean `update` or `upgrade`?

**Comment by justinclift** [comment]
Ahhh, yeah, `upgrade`.

**Comment by justinclift** [comment]
`brew update` I run often... but don't think I've ever done that with any manual changes in the tree.

Not trusting git to not getting mixed up in that situation.

**Comment by ilovezfs** [comment]
>Not trusting git to not getting mixed up in that situation.

I suggest you set HOMEBREW_DEVELOPER=1 for a while and see how it goes. brew update is pretty smart about the whole stash/pop dance.

**Comment by justinclift** [comment]
k, will do. :smile:
