### ISSUE TITLE
Create an audit to disallow pre-release versions of software in the core tap

### ISSUE THREAD

**Issue by issyl0** [Homebrew/brew#7177]
# A detailed description of the proposed feature

When a user submits a formula version bump, a new audit could be written to ensure that the version is officially published - i.e. not a pre-release.

A lot of the formulae we provide are for projects on GitHub, and [GitHub provide a releases API](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name) with a `prerelease` boolean field for a specified tag.

Our `brew bump-formula-pr` command runs `brew audit` before submitting the PR, so an audit feels like the best place for this as it's where we do other checks on formulae. An audit would surface the problem for users that submit version bumps manually, too.

# The motivation for the feature

Inspired by conversation on https://github.com/Homebrew/homebrew-core/pull/51506 and us having (almost) let in some pre-release formulae accidentally (https://github.com/Homebrew/homebrew-core/pull/50025 and https://github.com/Homebrew/homebrew-core/pull/51510). This is for formulae version bumps that may look like a "non-beta" release, ie have "normal" `x.y.z` versioning, but not be officially published yet.

# How the feature would be relevant to at least 90% of Homebrew users

Users would be assured to get stable, officially released software all of the time from the main Homebrew core tap. This [aligns with our policies on stable versions](https://docs.brew.sh/Acceptable-Formulae#stable-versions).

# What alternatives to the feature have been considered

- Maintainers manually checking whether the version bumped in the PR is a pre-release. This would put more pressure on already overworked maintainers to have to do this for every PR given how many PRs homebrew/core gets per day. I've done about ten of these and it's time-consuming and error-prone.
- Trusting those who run `brew bump-formula-pr` to only submit for official "latest" releases - the same as the above, really - there should be tooling so people don't forget.

**Comment by samford** [comment]
If we can account for the majority while only needing a minimum number of whitelisted formulae (if any), then it would certainly be nice to automate this check.

Before implementing this (or as part of it), it would probably be good to go through all the GitHub-hosted formulae and see what their situation is like in terms of tagging pre-release, latest, etc. I've seen some repos that mark all their releases as "pre-release" until they hit some milestone (e.g., version 1.0). These kind of patterns might arise when looking through the repos and it would be good to account for them.

**Comment by MikeMcQuaid** [comment]
Agreed with automating this using a GitHub API. See also https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L787-L797 for some examples of doing this for non-GitHub stuff.

**Comment by LooTKinGz** [comment]
Repository update

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/pull/7231
