### ISSUE TITLE
Version: Comparison of NumericToken and StringToken

### ISSUE THREAD

**Issue by samford** [Homebrew/brew#7181]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

When running `brew livecheck cataclysm`, the newest version is reported as `0.9`, though this is older than the current version of `0.D`. This formula uses a version scheme where versions go 0-9 and then roll into capital letters (A, B, etc.), as seen on the [releases page](https://cataclysmdda.org/releases/). I'm not sure whether they're using hex numbering (0-9, A-F) or if it's A-Z but I guess time will tell.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
Trying with url https://github.com/CleverRaven/Cataclysm-DDA.git
Possible git repo detected at https://github.com/CleverRaven/Cataclysm-DDA.git
0.1 =&gt; #&lt;Version:0x00007f8567426370 @version=&quot;0.1&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::NumericToken 1&gt;]&gt;
0.2 =&gt; #&lt;Version:0x00007f8567426190 @version=&quot;0.2&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::NumericToken 2&gt;]&gt;
0.3 =&gt; #&lt;Version:0x00007f8567425fd8 @version=&quot;0.3&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::NumericToken 3&gt;]&gt;
0.4 =&gt; #&lt;Version:0x00007f8567425d80 @version=&quot;0.4&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::NumericToken 4&gt;]&gt;
0.5 =&gt; #&lt;Version:0x00007f8567425c90 @version=&quot;0.5&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::NumericToken 5&gt;]&gt;
0.6 =&gt; #&lt;Version:0x00007f8567425b00 @version=&quot;0.6&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::NumericToken 6&gt;]&gt;
0.7 =&gt; #&lt;Version:0x00007f8567425948 @version=&quot;0.7&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::NumericToken 7&gt;]&gt;
0.7.1 =&gt; #&lt;Version:0x00007f8567425718 @version=&quot;0.7.1&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::NumericToken 7&gt;, #&lt;Version::NumericToken 1&gt;]&gt;
0.8 =&gt; #&lt;Version:0x00007f8567425560 @version=&quot;0.8&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::NumericToken 8&gt;]&gt;
0.9 =&gt; #&lt;Version:0x00007f85674253a8 @version=&quot;0.9&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::NumericToken 9&gt;]&gt;
0.A =&gt; #&lt;Version:0x00007f85674252e0 @version=&quot;0.A&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::StringToken &quot;A&quot;&gt;]&gt;
0.B =&gt; #&lt;Version:0x00007f8567425218 @version=&quot;0.B&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::StringToken &quot;B&quot;&gt;]&gt;
0.C =&gt; #&lt;Version:0x00007f8567425150 @version=&quot;0.C&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::StringToken &quot;C&quot;&gt;]&gt;
0.D =&gt; #&lt;Version:0x00007f8567425088 @version=&quot;0.D&quot;, @tokens=[#&lt;Version::NumericToken 0&gt;, #&lt;Version::StringToken &quot;D&quot;&gt;]&gt;
cataclysm : 0.D ==&gt; 0.9
  </pre>
</details>

## What you expected to happen

Version `0.D` should be interpreted as the newest version (since D > 9).

## Step-by-step reproduction instructions (by running `brew` commands)

`brew livecheck cataclysm`

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.2.10-64-g4d5424c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d5424c7faaa53313f08fd67f2a861036cd3cd55
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 71079f20cf15b162588b007e7677328f607754e2
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.3-x86_64
CLT: N/A
Xcode: 11.3.1
</pre>

## General Comments

From what I've seen in trying to resolve this issue, I imagine this is related to the comparison that happens in `Version` between `NumericToken` and `StringToken`. I've tinkered with this to see if I could resolve the issue but haven't had any luck so far.

**Comment by MikeMcQuaid** [comment]
Is this not a `brew livecheck` issue?

**Comment by samford** [comment]
I previously started by troubleshooting it in Homebrew/homebrew-livecheck but livecheck is only doing `Version` comparisons. The main areas of interest in livecheck are:

* [`heuristic.rb`'s `version_heuristic()`, where the highest identified `Version` is returned using `match_version_map.values.max`](https://github.com/Homebrew/homebrew-livecheck/blob/8e09cec901e200ffe5207c7d359c14d8d0af20f0/livecheck/heuristic.rb#L229)
* [`livecheck.rb`'s `print_latest_version()`, where the `current` and `latest` versions are compared](https://github.com/Homebrew/homebrew-livecheck/blob/master/cmd/livecheck.rb#L125-L126)

The implementation details of how two `Version`s are compared is something that's handled in `version.rb` and would occur outside of livecheck as well. This ultimately arises due to how comparisons are handled between `NumericToken` (e.g., 9) and `StringToken` (e.g., "D").

I worked on this some more and found that modifying the conditions in the loop where token comparison occurs in `Version.<=>` can achieve the desired effect:

```patch
diff --git a/Library/Homebrew/version.rb b/Library/Homebrew/version.rb
index 27116a243e94a30c138070333a05013067e53791..8b55b5bbdb16ac4ff187ce0f783344d22a1b7b7d 100644
--- a/Library/Homebrew/version.rb
+++ b/Library/Homebrew/version.rb
@@ -412,6 +412,10 @@ class Version
         next
       elsif a.numeric? && b.numeric?
         return a <=> b
+      elsif a.numeric? && b.is_a?(StringToken)
+        return -1
+      elsif a.is_a?(StringToken) && b.numeric?
+        return 1
       elsif a.numeric?
         return 1 if a > NULL_TOKEN
```

This basically means "If we're comparing a numeric token and a `StringToken`, always treat the `StringToken` as greater". I imagine we may want to approach this in a more intelligent manner but hopefully this will further the discussion.

**Comment by MikeMcQuaid** [comment]
@samford A patch like that makes sense to me! Could you submit a PR?

**Comment by samford** [comment]
If it's fine with you, I would like to see how this change shakes out when I do my next full livecheck run tonight (comparing it to yesterday's output). I usually compare output between runs (with/without a change) before creating PRs that can potentially affect the checks for all formulae (or a large number of them). It helps to confirm that the fix is working as expected and that we're not introducing issues into other formulae.

Once I've gone through the output I'll gladly create a PR and link it to this issue.

**Comment by MikeMcQuaid** [comment]
Works for me, thanks 👍

**Comment by samford** [comment]
After looking at the livecheck output, I'm going to have to think a little more about how to best address this.

The big blocker right now is that the Sourceforge strategy in the livecheck heuristic returns a lot of `files` versions, so they're always interpreted as the newest version with this change. Without the change, only 121 formulae checks were giving `files` as the newest version. With the change, the number is 258.

There are also some other individual issues that will need to be accounted for (e.g., `3.10-gtk3` being given as newer than `3.10.1-gtk3` with the `audacious` formula, due to "gtk3" always being greater than 1).

This can be mitigated to some extent through improving the Sourceforge strategy and/or restricting version matching for formulae using livecheckables regexes. However, I'm not yet sure whether the issue can be totally resolved in this manner. In the end, it may require changes in livecheck as well as approaching the version comparison in a less heavy-handed manner.

I'm going to hold off on creating a PR for this until livecheck and/or the version comparison is in a state where it wouldn't break any checks. I'm temporarily avoiding adding large numbers of livecheckables until I've finished implementing all the forthcoming features, so I likely won't get to this for a good while.

**Comment by MikeMcQuaid** [comment]
> I'm going to hold off on creating a PR for this until livecheck and/or the version comparison is in a state where it wouldn't break any checks. I'm temporarily avoiding adding large numbers of livecheckables until I've finished implementing all the forthcoming features, so I likely won't get to this for a good while.

Ok, given this: let's close this out for now. Happy to review a PR when it appears. Thanks for the explanation!
