### ISSUE TITLE
CMake can pick up Fink/MacPorts paths

### ISSUE THREAD

**Issue by apjanke** [Homebrew/brew#72]
Under our current `superenv` implementation, CMake-based build scripts can still pick up programs and libraries from Fink (`/sw`) and MacPorts (`/opt/local`) under some circumstances. We do not support building against Fink or MacPorts packages, so this can cause either unexpected behavior or broken builds.

We should probably sanitize more aggressively to prevent this, using CMake-specific configuration and/or sandbox "read deny" rules.

Not high priority, since this will probably only affect unusual configurations, like side-by-side Homebrew + Fink installs.

###  Description

CMake has functions like `find_program()` and `find_library()` that search in a lot of different places, using both build-specific paths, environment variables, and fallback locations defined in `CMAKE_SYSTEM_*_PATH` `cmake` variables. The [default system path set for Darwin](https://github.com/Kitware/CMake/blob/9ac11bc25d6b9f5e7db786034f922d96613e6143/Modules/Platform/Darwin.cmake) includes hardcoded references to `/sw` and `/opt/local`, so it can pick up Fink or MacPorts commands or libraries even if those paths have been entirely sanitized from your environment variables and the program build script does not reference them.

First found this with a build failure for `weechat --with-ruby` that broke when there was a Fink-supplied `ruby2.0` in addition to the system `ruby` and Homebrew-built `ruby`; https://github.com/Homebrew/homebrew-core/issues/117#issuecomment-208323722.

Which things are affected depend on how the CMake lookups are implemented. `FindRuby.cmake`, at least in its older form, and that adapted by `weechat`, is vulnerable to this because its lookups for the Ruby command, headers, and shared libraries are not tightly bound to each other. Using `PATHS` instead of `HINTS` in the `find_*` arguments can affect this.

###  Approach

Sanitizing `$PATH` and other environment variables is not sufficient. We probably need to override CMake's `CMAKE_SYSTEM_*_PATH` cmake variables to remove Fink and MacPorts paths (and possibly to limit them to paths explicitly included by `superenv`). This probably needs to be done with a `cmake` wrapper like the `cc` wrapper that modifies the command line arguments, using `-D` to set the `CMAKE_*` variables. Unlike `CMAKE_*_PATH` (without `SYSTEM`), environment variables with those names don't seem to be supported by CMake.

Maybe we should switch from `CMAKE_*_PATH` to `CMAKE_SYSTEM_*_PATH` entirely in our `cmake` environment setup. The non-SYSTEM `CMAKE_*_PATH` variables are high-precedence, coming before both `PATHS` and `HINTS` that are computed inside the build script. This could have unexpected effects on build scripts that are not expecting that customization or have sloppy detection implementations.

Or maybe we need to establish a policy of requiring CMake-based builds to be robust WRT `CMAKE_*_PATH` variables. That doesn't seem unreasonable either.

**Comment by mikemcquaid** [comment]
> We probably need to override CMake's CMAKE_SYSTEM_*_PATH cmake variables to remove Fink and MacPorts paths (and possibly to limit them to paths explicitly included by superenv). This probably needs to be done with a cmake wrapper like the cc wrapper that modifies the command line arguments, using -D to set the CMAKE_* variables. Unlike CMAKE_*_PATH (without SYSTEM), environment variables with those names don't seem to be supported by CMake.

I think in CMake's case this would be something they'd be willing to take a patch for (if one is necessary; it may be possible to just do this at either compilation or runtime).

> Maybe we should switch from CMAKE_*_PATH to CMAKE_SYSTEM_*_PATH entirely in our cmake environment setup. The non-SYSTEM CMAKE_*_PATH variables are high-precedence, coming before both PATHS and HINTS that are computed inside the build script. This could have unexpected effects on build scripts that are not expecting that customization or have sloppy detection implementations.

This may work :+1:

**Comment by mikemcquaid** [comment]
@apjanke Any more thoughts on this or my comments above?

**Comment by apjanke** [comment]
Not yet – I've been focused on the analytics and `brew pull` stuff lately. I'm also learning CMake for real: about halfway through the "Mastering CMake" book. Give me a little time to finish that so I actually know what I'm talking about, and I'll give you a useful response?

**Comment by mikemcquaid** [comment]
Sure thing.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
