### ISSUE TITLE
Looking for an example of creating package for use with brew services

### ISSUE THREAD

**Issue by ORESoftware** [Homebrew/brew#7201]
I want to create a package which can be listed as a brew service and used like a systemd service. I google for examples and it's hard to find. I also put this question on Quora: https://www.quora.com/unanswered/Where-is-there-an-example-of-creating-a-homebrew-package-which-can-launch-a-systemd-service-or-brew-service-on-MacOS

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

In future please always fill out the issue template. In the case of this issue: ask questions like this in [Discourse](https://discourse.brew.sh) instead
