### ISSUE TITLE
The `install.sh` will still abort if the `SUDO_ASKPASS` exists.

### ISSUE THREAD

**Issue by Whirlwind** [Homebrew/brew#7206]
I have the `SUDO_ASKPASS` environment variable, but I still get:
```
Need sudo access on macOS!
```
I check the `install.sh`, and I found:
```
have_sudo_access() {
  if [[ -z "${HAVE_SUDO_ACCESS-}" ]]; then
    /usr/bin/sudo -l mkdir &>/dev/null
    HAVE_SUDO_ACCESS="$?"
  fi

  if [[ -z "${HOMEBREW_ON_LINUX-}" ]] && [[ "$HAVE_SUDO_ACCESS" -ne 0 ]]; then
    abort "Need sudo access on macOS!"
  fi

  return "$HAVE_SUDO_ACCESS"
}
```
The `/usr/bin/sudo -l mkdir &>/dev/null` will not pick the `SUDO_ASKPASS`( the `-A` flag ). I will always be failed in my GUI App.

Should I pass the `HAVE_SUDO_ACCESS=1` to skip the check?

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template. I suggest you either ask in [Discourse](https://discourse.brew.sh] or open a PR. Thanks!
