### ISSUE TITLE
Gtk+3 cannot locate libgtk-3.0.dylib (macosx) after installing gtk (or glade)

### ISSUE THREAD

**Issue by pedrohex** [Homebrew/brew#7211]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Installed in this particular order :

gtk+3
(all my gtk3 applications got to work)

glade
gnome-themes-standard
gtk+

(after this, gtk+3 apps cannot locate ibgtk-3.0.dylib)

## What happened (include command output)
My guess, Glade version is using gtk+ and somehow mess with DYLD_LIBRARY_PATH

<details>
  <summary>Command output</summary>
  <pre>

 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()

( running dotnet core with csharp bindings)
  </pre>
</details>

## What you expected to happen

libgtk-3.0.dylib should be located

## Output of `brew config` and `brew doctor` commands

<pre>
brew config
HOMEBREW_VERSION: 2.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 48a1637b24a0c329905a981f4cff547c7fa47943
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f17771f62cc0a4de98214586732effae391776aa
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.3-x86_64
CLT: 11.0.33.17
Xcode: 11.3.1

brew config

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/12/bin/gdal-config

</pre>

**Comment by MikeMcQuaid** [comment]
> ## Step-by-step reproduction instructions (by running `brew` commands)

We need this.
