### ISSUE TITLE
Feature: Ability to tell brew something is already installed outside of brew

### ISSUE THREAD

**Issue by Fryguy** [Homebrew/brew#7218]
I think it would useful to be able to tell brew that something is already installed outside of brew.

For example, I want to manage my node installations with `nvm`.  However, if later I do `brew install yarn`, the `yarn` package expects `node` to be installed.  I have no simple way of telling brew that `node` is already installed, so I am forced to play games with deleting dependencies.  However, then `brew doctor` complains forever after that (and I can hack around that too with symlinks, but then I'm really not letting `brew doctor` do its job, so I don't really want to do that)

I'm picturing it similar to `brew pin`, so
- something like `brew pin-installed <package> /path/to/installed/location`
- `brew doctor` can be aware of this and just warn with `"Warning: package 'node' is managed outside of brew at '/path/to/installed/location'"
- `brew install` can be aware of this an *not* install the dependency, perhaps also warning in the output.

I think this is useful for people that might need to externally manage packages.  In particular, perhaps, developers who are building those packages locally and need to pin brew to their custom build.

I tried searching for this, and couldn't find it, so apologies if this has been already asked before.

**Comment by MikeMcQuaid** [comment]
First, please always fill out the issue template. 

This has been asked many times before. We supported it long ago, it broke loads of stuff so we aren't ever going to again. Just ignore the `node` package. You do not need to delete it. Fix your `PATH` so your `nvm` is before it. I do this for Ruby: it works great (and always has).

**Comment by Fryguy** [comment]
> This has been asked many times before.

Ah, thanks.  I honestly tried to search for this 😄 

> Just ignore the node package. You do not need to delete it. Fix your PATH so your nvm is before it. I do this for Ruby: it works great (and always has)

Yeah, I got it working by uninstalling the node package with `--ignore-dependencies`, but it felt gross that brew doctor complains.

Thank you!

**Comment by MikeMcQuaid** [comment]
> Yeah, I got it working by uninstalling the node package with `--ignore-dependencies`, but it felt gross that brew doctor complains.

Don't do this. It's a bad idea and will break things. Fix your `PATH`. If you don't understand how to do that yet, I strongly recommend Googling and learning: it's a must-have skill on a Unix system.
