### ISSUE TITLE
Unable to install from HEAD if using a primary branch that isn't "master"

### ISSUE THREAD

**Issue by samdmarshall** [Homebrew/brew#722]
### Bug reports:

When attempting to install a formula from `HEAD` i get an error of brew being unable to find a `master` branch on the remote. This is because there is no branch named `master`, the primary branch i use is called `develop` instead.

```
$ brew install samdmarshall/formulae/pyconfig --HEAD
==> Installing pyconfig from samdmarshall/formulae
==> Cloning https://github.com/samdmarshall/pyconfig.git
Cloning into '/Users/Samantha/Library/Caches/Homebrew/pyconfig--git'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
Error: Failed to download resource "pyconfig"
Failure while executing: git clone --depth 1 --branch master https://github.com/samdmarshall/pyconfig.git /Users/Samantha/Library/Caches/Homebrew/pyconfig--git
```

I am pretty sure this is a regression as this was working at some point last year or earlier this year. It might be worth adding a test case to this.

**Comment by MikeMcQuaid** [comment]
CC @vladshablinsky for thoughts on this but the short-term fix (which may also be the long-term fix) is to append `,  :branch => "develop"` to your `head` line in that formula.

**Comment by MikeMcQuaid** [comment]
That it worked previously may be a quirk/implementation detail of how GitHub supports default branches compared to other Git providers.

**Comment by samdmarshall** [comment]
I am fairly confident this is a regression because I originally filed this: https://github.com/Homebrew/legacy-homebrew/issues/43865 about taps not updating if the primary branch was not "master" and didn't need to file a follow-up issue as all my taps with non-master primary branches worked before and after that fix went into brew.

**Comment by MikeMcQuaid** [comment]
It may be a regression but one that we cannot restore without breaking new functionality as we now specify the branch when cloning and that defaults to `master` unless it's been specified as another branch.

**Comment by samdmarshall** [comment]
Ok, if that is the case can some more helpful messaging be added to this instead then? I feel like if it fails to locate the default branch name on the remote, then it should display a message to the user that the formula may be broken and that the actual primary branch should be specified instead.

**Comment by MikeMcQuaid** [comment]
Also paging @xu-cheng who oversaw this feature.

**Comment by vladshablinsky** [comment]
Well, seems like it shouldn't have worked at the first place. Also, [Formula Cookbook](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#head) says that if you want to specify branch, you should use `:branch` option, but it doesn't say the default branch is `master`, but it probably should.

**Comment by UniqMartin** [comment]
> I am fairly confident this is a regression because I originally filed this: https://github.com/Homebrew/legacy-homebrew/issues/43865 about taps not updating if the primary branch was not "master" and didn't need to file a follow-up issue as all my taps with non-master primary branches worked before and after that fix went into brew.

This seems unrelated. The referenced issue and the subsequent fix was about updating taps (the Git repositories containing the formulae) while the issue you're having here is about cloning a Git repository as part of a formula installation, which is handled by completely different code. Maybe this comment helps a bit, in case this distinction wasn't entirely clear.

**Comment by samdmarshall** [comment]
@UniqMartin you seem to have misunderstood my comment entirely. I was the one that opened the issue that was fixed by the referenced commit. That issue was because my taps repo was using a non-master branch as the primary branch. The repos that the formulae that are in my tap also use non-master branches as the primary branch. Thus, I was commenting that if I wasn't able to install from --HEAD on a non-master branch, then I would have opened an issue following that, but I didn't therefore I didn't run into this then, thus I am calling this a "regression" in behavior.

**Comment by UniqMartin** [comment]
I afraid I don't understand. To me, handling of the tap repositories (as part of `brew update`) and handling of arbitrary Git repositories (as part of the formula installation process, e.g. `brew install --HEAD`) are two different and basically unrelated topics.

Anyway, I have to agree with the others that you should specify `:branch => "devel"` to resolve this particular issue (and that it worked without previously is probably accidental and thus the change in behavior not exactly a regression). The only thing that remains is maybe a more friendly error message and certainly a small tweak to the documentation as suggested by @vladshablinsky. If you could address either or both in a PR, that would be awesome.

**Comment by samdmarshall** [comment]
Yes, they are completely unrelated, but due to the way my tap, and repos of the formulae in said tap, are configured; I would have run into this problem immediately after the referenced issue was resolved. The two, otherwise unrelated subjects, are specifically related to my context of my formulae.

So based on the info in this thread, I do need to update my formulae to use the `:branch => "develop"` attribute to make the `--HEAD` installs work again. My additional suggestion was add more informative logging behavior when the build fails.

**Comment by MikeMcQuaid** [comment]
This is documented in https://github.com/Homebrew/brew/blob/105d7aa5346553408281ca8f7c4eeb02ea8a7c3f/Library/Homebrew/formula.rb#L1861 but I'm adding additional documentation in https://github.com/Homebrew/brew/pull/756 which will close this issue.
