### ISSUE TITLE
Upgrade wxWidgets for BOINC COVID-19 research

### ISSUE THREAD

**Issue by mcandre** [Homebrew/brew#7226]
Could we please upgrade the wxWidgets formula to v3.1.0, so that developers can contribute to BOINC research more easily?

https://github.com/Homebrew/homebrew-core/blob/master/Formula/wxmac.rb

https://github.com/BOINC/boinc/blob/master/mac_build/HowToBuildBOINC_XCode.pdf

**Comment by mcandre** [comment]
Started a draft of a pull request for this change. Unfortunately, getting a compile error.

https://github.com/Homebrew/homebrew-core/pull/52177

**Comment by iMichka** [comment]
Yes, the best way to get this going is through a pull request. I'll close the issue as #52177 is now open.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

@mcandre Please follow that in future. Also, from https://github.com/Homebrew/brew/issues/7209  it's not helpful to tell the Homebrew maintainers what you think we should be doing for COVID research: please do so yourself.
