### ISSUE TITLE
Providing installation logs like apt's history.log and term.log

### ISSUE THREAD

**Issue by alb-i986** [Homebrew/brew#7232]
# A detailed description of the proposed feature

If I'm not mistaken, you're not providing any installation logs, are you?
I think it would be really nice if you did.
I'm thinking of apt's history.log and term.log, you know?

# The motivation for the feature

For troubleshooting / "archaeology".
For archaeology I mean, for example, to find out when you installed that unknown library which you see you have now installed but you don't remember anymore why.

# How the feature would be relevant to at least 90% of Homebrew users

Users would have a good "tool" for troubleshooting.

# What alternatives to the feature have been considered

**Comment by MikeMcQuaid** [comment]
> If I'm not mistaken, you're not providing any installation logs, are you?

You are mistaken. Search for `logs` in `man brew` or, if you're on macOS, look in `~/Library/Logs/Homebrew/`
