### ISSUE TITLE
PostgreSQL build failure due to conflicting SDK root on macOS

### ISSUE THREAD

**Issue by eagletmt** [Homebrew/brew#7248]
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I'd like to build and install postgresql via Homebrew.
I need to build it because my HOMEBREW_PREFIX is not /usr/local.

## What happened (include command output)
`brew install --build-from-source postgresql` fails with strange compile errors.

<details>
  <summary>Command output</summary>
  <pre>
% brew install --build-from-source postgresql
Updating Homebrew...
Warning: Your Xcode (11.3.1) is outdated.
Please update to Xcode 11.4 (or delete it).
Xcode can be updated from the App Store.

==> Downloading https://ftp.postgresql.org/pub/source/v12.2/postgresql-12.2.tar.bz2
Already downloaded: /Users/kohei-suzuki/Library/Caches/Homebrew/downloads/8c78435b1b3de8f3d3d60b486351161a0f00e8bbef18e25c493ca294db1816c7--postgresql-12.2.tar.bz2
==> ./configure --prefix=/opt/brew/Cellar/postgresql/12.2 --datadir=/opt/brew/share/postgresql --libdir=/opt/brew/lib --includedir=/opt/brew/include --sysconfdir=/opt/brew/etc --docdir=/opt/brew/Cellar/postgresql/12.2/share/
==> make
Last 15 lines from /Users/kohei-suzuki/Library/Logs/Homebrew/postgresql/02.make:
In file included from ../../src/include/c.h:1291:
../../src/include/port.h:429:15: error: conflicting types for '__builtin___strlcpy_chk'
extern size_t strlcpy(char *dst, const char *src, size_t siz);
              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_string.h:112:3: note: expanded from macro 'strlcpy'
                __builtin___strlcpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
                ^
../../src/include/port.h:429:15: note: '__builtin___strlcpy_chk' is a builtin with type 'unsigned long (char *, const char *, unsigned long, unsigned long)'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_string.h:112:3: note: expanded from macro 'strlcpy'
                __builtin___strlcpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
                ^
6 errors generated.
make[2]: *** [ip.o] Error 1
make[1]: *** [all-common-recurse] Error 2
make: *** [all-src-recurse] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
libpq and postgresql@x: link against MIT Kerberos https://github.com/Homebrew/homebrew-core/pull/51958

Error: Your Xcode (11.3.1) is outdated.
Please update to Xcode 11.4 (or delete it).
Xcode can be updated from the App Store.
  </pre>
</details>

I digged into this compile error and found that `configure` fails to detect `strlcpy` declaration because compiling `#include <stdlib.h>` produces many warnings.
The minimum reproducible code is here.

```
% cat conftest.c
#include <stdlib.h>
% clang -c -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include conftest.c -o /dev/null -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
(many warnings are printed)
```

The warnings are caused by the conflicting `-I` and `-isysroot`.
This situation happens while running `brew install --build-from-source postgresql`:

- PostgreSQL's configure script adds Xcode SDK root `-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include`
    - Xcode SDK root is printed by `xml2-config --cflags`, which runs `xcrun --show-sdk-path`
- Homebrew adds CLT SDK root `-isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk`

Before #7134, Homebrew adds Xcode SDK root `-isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`, so there's no conflicts. Both use Xcode SDK.
I reverted #7134 locally and then `brew install --build-from-source postgresql` finished successfully.

It might affect other formula using libxml2.

## What you expected to happen
It successfully builds.

## Step-by-step reproduction instructions (by running `brew` commands)
- Install Xcode and CLT
    - Confirm Xcode SDK root: `xcrun --show-sdk-path` prints /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
    - Confirm SDK root used by Homebrew: `brew ruby -e 'puts OS::Mac.sdk_path'` prints /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
- Run `brew install --build-from-source postgresql`

## Output of `brew config` and `brew doctor` commands

<pre>
% brew config
HOMEBREW_VERSION: 2.2.11-56-ged09857
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed0985783aab8e9e8702a4aad27fbb4108f8c29a
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 89d93309ba2bc0e931d1ed4e6ee968a7a3af0b47
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /opt/brew
HOMEBREW_CELLAR: /opt/brew/Cellar
HOMEBREW_REPOSITORY: /opt/brew/Homebrew
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /opt/brew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.2 => /opt/brew/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.3, 1.8.0_212
macOS: 10.15.4-x86_64
CLT: 11.4.0.0.1.1583798712
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

Warning: /usr/bin occurs before /opt/brew/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:

Consider setting your PATH so that /opt/brew/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/opt/brew/bin:$PATH"' >> ~/.zshrc
  cpan
  rview
  vim
  cmp
  instmodsh
  db_upgrade
  perlivp
  vi
  pod2usage
  corelist
  db_hotbackup
  git-receive-pack
  vimdiff
  libnetcfg
  diff3
  python3
  xxd
  encguess
  db_printlog
  db_archive
  pip3
  pod2text
  ptardiff
  db_stat
  json_pp
  perl
  ex
  perlbug
  db_load
  piconv
  ptargrep
  h2ph
  rvim
  vimtutor
  prove
  podchecker
  shasum
  git-upload-archive
  diff
  ptar
  pl2pm
  db_verify
  perlthanks
  xsubpp
  perldoc
  view
  h2xs
  db_checkpoint
  pod2man
  enc2xs
  git-shell
  podselect
  sdiff
  db_deadlock
  git-upload-pack
  openssl
  splain
  pod2html
  db_recover
  db_dump
  git
  zipdetails

Warning: Your Xcode (11.3.1) is outdated.
Please update to Xcode 11.4 (or delete it).
Xcode can be updated from the App Store.
</pre>

**Comment by MikeMcQuaid** [comment]
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC. You are responsible for resolving any issues you
> experience while you are running this unsupported configuration.


@Bo98 may be interested in this but I'm afraid we do not support your configuration (outdated Xcode, non-default Homebrew prefix), sorry.

**Comment by Bo98** [comment]
I will look at `xcrun`. We have a shim for that but we don't sufficiently control what it outputs. See #7250 which I've opened to track this.

`ENV["SDKROOT"] = MacOS.sdk_path_if_needed` is a workaround if you need it urgently.
