### ISSUE TITLE
`brew update` outputs `Successfully rebased and updated refs/heads/master` twice with recent `git`.

### ISSUE THREAD

**Issue by globau** [Homebrew/brew#7259]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run `brew update`, to update brew :)

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

Successfully rebased and updated refs/heads/master.                                                                        
Successfully rebased and updated refs/heads/master.

  </pre>
</details>

## What you expected to happen

No output.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew update` with pending changes to pull from git.

Likely a recent change to git; I have git version 2.26.0.

Looks like the fix in https://github.com/Homebrew/brew/commit/b2614ddcb665013a09eb3a1db087cc458b93d15b isn't sufficient anymore.

## Output of `brew config` and `brew doctor` commands

<pre>

~$ brew config
HOMEBREW_VERSION: 2.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa8fe0fc396550c23156043cd07550fc6ae6a27a
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8f31a9689b5da8b9c3364ea742fbb78bbc55acac
Core tap last commit: 86 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.2
macOS: 10.15.4-x86_64
CLT: N/A
Xcode: 11.4
~$ brew doctor
Your system is ready to brew.

</pre>

**Comment by globau** [comment]
`git` does honour the `--quiet` arg when displaying this message:

https://github.com/git/git/blob/3bab5d56259722843359702bc27111475437ad2a/sequencer.c#L4092-L4098
```
		if (!opts->quiet) {
			if (!opts->verbose)
				term_clear_line();
			fprintf(stderr,
				"Successfully rebased and updated %s.\n",
				head_ref.buf);
		}
```

Maybe `${QUIET_ARGS[@]}` should be passed to the `git rebase` command at https://github.com/Homebrew/brew/blob/1824435f678d1209cf787dbdfb1fcc261a199803/Library/Homebrew/cmd/update.sh#L256

**Comment by MikeMcQuaid** [comment]
Thanks, opened https://github.com/Homebrew/brew/pull/7260 as I could reproduce this too. Feel free to open a PR in future if you're digging in the code; makes it easier to jump straight into it. Regardless: thanks for the helpful and detailed issue report!
