### ISSUE TITLE
Upgrade to Cabal Nix-style Local Builds

### ISSUE THREAD

**Issue by fishtreesugar** [Homebrew/brew#7274]
# A detailed description of the proposed feature
Currently brew use Cabal sandbox to a build a haskell program bottle, this issue purpose brew upgrade to Cabal's [Nix-style Local Builds](https://www.haskell.org/cabal/users-guide/nix-local-build-overview.html)

# The motivation for the feature

Cabal already make "Nix-style Local Builds" as default, and may remove sandbox in next version (3.4): haskell/cabal#6445

**Comment by Bo98** [comment]
An approach to this was agreed in #6974.
