### ISSUE TITLE
shorthand "brew i" absent

### ISSUE THREAD

**Issue by garmoshka-mo** [Homebrew/brew#728]
```
brew i fswatch
Error: Unknown command: i
```
😧 

This is pretty inconvenient.
Why it is required? Because it is de facto standard for modern tools
```
gem i
npm i 
bower i jquery
```

**Comment by MikeMcQuaid** [comment]
See https://github.com/homebrew/homebrew-aliases

**Comment by garmoshka-mo** [comment]
@MikeMcQuaid thank you for link 👍 

Issue is that common solution is not easily available for people (informational barrier - it is a problem)
If there is strong arguments agains not having aliases by default, 
then error message `Error: Unknown command: i` should be extended with something like `Error: Unknown command: i. To assign alias run: brew tap homebrew/aliases; brew alias i="install"`

It wouldn't be so important for other system tools, like `lsyncd` - which requires a lot of specific knowledges before let "monkey to use grenades" 🙈 

Though `brew` - looks like was initially created for convenience and simplicity of usage, isn't it

**Comment by MikeMcQuaid** [comment]
It's something we may consider in future but not at the present time, thanks.
