### ISSUE TITLE
HOMEBREW_SDKROOT not set on macOS 10.13

### ISSUE THREAD

**Issue by deus0ww** [Homebrew/brew#7290]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
brew install -s libass (or any package depending on pkg-config to build)

## What happened (include command output)
Example from libass:
...
checking pkg-config is at least version 0.9.0... --define-variable argument does not have a value for the variable
...

## What you expected to happen
Not that...

## Step-by-step reproduction instructions (by running `brew` commands)
brew install -s xxx (where xxx is any package depending on pkg-config to build)

## Output of `brew config` and `brew doctor` commands
HOMEBREW_VERSION: 2.2.11-132-g64fd839-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 64fd839c955b3c32855067d26fed7daf65183877
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d5b88cb32af096274f57a672a3d7410791c9faf3
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CURL_RETRIES: 3
HOMEBREW_DEVELOPER: 1
HOMEBREW_DISPLAY_INSTALL_TIMES: 1
HOMEBREW_FORCE_BREWED_CURL: 1
HOMEBREW_FORCE_BREWED_GIT: 1
HOMEBREW_FORCE_VENDOR_RUBY: 1
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_TAPS: /usr/local/Homebrew/Library/Taps
HOMEBREW_VISUAL: /usr/local/bin/bbedit
CPU: octa-core 64-bit penryn
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1000
Git: 2.26.0 => /usr/local/opt/git/bin/git
Curl: 7.69.1 => /usr/local/opt/curl/bin/curl
Java: 14, 1.8.0_241
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11

Your system is ready to brew.

## My Workaround:
Deleted line 4 (  "--define-variable=homebrew_sdkroot=$HOMEBREW_SDKROOT" \  ) from
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config

This fixes it (for 10.13).

**Comment by Bo98** [comment]
Turns out it is impossible to set a variable to an empty string in pkg-config. I suppose though that'll never need to happen in the scenarios where we use `homebrew_sdkroot` in the *.pc files.

I'll get this fixed, thanks for the report!

**Comment by deus0ww** [comment]
Working for me. Thank you!
