### ISSUE TITLE
pkg-config cannot find zlib after 0.29.2_1 update

### ISSUE THREAD

**Issue by whitty** [Homebrew/brew#7292]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Link an application with libpng/zlib. Specifically:

```
pkg-config --libs-only-l zlib 
```

This looks likely to be caused by https://github.com/Homebrew/homebrew-core/pull/52565

## What happened (include command output)

zlib was not found by package config

<details>
  <summary>Command output</summary>
  <pre>

$ pkg-config --libs-only-l zlib 
Package zlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `zlib.pc'
to the PKG_CONFIG_PATH environment variable
No package 'zlib' found

  </pre>
</details>

## What you expected to happen

```
pkg-config --libs-only-l zlib 
```

should output

```
-lz
```

## Step-by-step reproduction instructions (by running `brew` commands)

```
brew install pkg-config
brew install png++
pkg-config --libs-only-l zlib 
pkg-config --libs-only-l libpng
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config 
HOMEBREW_VERSION: 2.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa8fe0fc396550c23156043cd07550fc6ae6a27a
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6949fc6f36de1261dffbe37f3b2216cf903431ed
Core tap last commit: 41 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_191
macOS: 10.14.4-x86_64
CLT: 10.2.0.0.1.1552586384
Xcode: 11.2.1

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.

Warning: Your Xcode (11.2.1) is outdated.
Please update to Xcode 11.3 (or delete it).
Xcode can be updated from the App Store.
</pre>

**Comment by tschoonj** [comment]
see https://github.com/Homebrew/brew/issues/5068 for a discussion about this

**Comment by MikeMcQuaid** [comment]
Closing in favour of reopening https://github.com/Homebrew/brew/issues/5068.
