### ISSUE TITLE
duplicate items when running `update` and `upgrade`

### ISSUE THREAD

**Issue by njm2112** [Homebrew/brew#7295]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Update/upgrade of installed formulae/casks when running any of `brew install [formula]`, `brew upgrade`, or `brew cask upgrade`.

**NB:** This is identical to [#420](https://github.com/Homebrew/brew/issues/420) and [#714](https://github.com/Homebrew/brew/issues/714), both of which were resolved/closed without identifying the root cause of the issue. Also, unlike those two prior reports of this problem where it appeared the problem might be caused by `homebrew-hombrew` being tapped twice, it doesn't appear that my install has that tapped twice... 

## What happened (include command output)

Outdated formulae/casks appear to upgrade without issue, but every formula in the output list appears twice

<details>
  <summary>Command output</summary>
  <pre>

![image](https://user-images.githubusercontent.com/10353532/78610710-716f3480-7833-11ea-805c-23266bd765ba.png)

  </pre>
</details>

## What you expected to happen

Would expect that the items in the output list appear only once.

## Step-by-step reproduction instructions (by running `brew` commands)

This issue occurs whether I run `brew install [formula]`, `brew update`, or `brew upgrade`.

## Output of `brew config` and `brew doctor` commands

<pre>
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/local/bin/icu-config
  /opt/local/bin/freetype-config
  /opt/local/bin/libpng16-config
  /opt/local/bin/libpng-config
  /opt/local/bin/xml2-config
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/uuid-config
  /opt/local/bin/ncurses6-config

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/bin/zoom-us-wrapper
➜  ~ brew config
HOMEBREW_VERSION: 2.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa8fe0fc396550c23156043cd07550fc6ae6a27a
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ca173c85d4734c1a083f5d7c9d545f49eaee6399
Core tap last commit: 14 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14
macOS: 10.15.4-x86_64
CLT: 1103.0.32.29
Xcode: N/A
</pre>

**Comment by Bo98** [comment]
> it doesn't appear that my install has that tapped twice

You appear to have both `caskroom/cask` and `homebrew/cask` tapped. They are aliases to each other. I'd try untap the older `caskroom/cask`.
