### ISSUE TITLE
Overlap downloading with installation, and perform simultaneous downloading

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/brew#7302]
# A detailed description of the proposed feature
When doing brew (cask) install (upgrade) p q r s, the process should simultaneously commence downloading all of p q r s at the start, and then install them as they become available.
The current way of download p, install p, download q, install q, ...potentially takes (much) longer overall.

# The motivation for the feature
Reduce the overall time the user waits for brew (cask) install (upgrade) p q r s to finish

# How the feature would be relevant to at least 90% of Homebrew users
Improved speed helps all users

# What alternatives to the feature have been considered
The current single task approach, which is slow. 

The main work need for this approach is that asynchronous control would be needed with a dependency forest to determine when each item can be installed, once the things it depends on have been downloaded / installed.

**Comment by MikeMcQuaid** [comment]
See https://github.com/Homebrew/brew/issues/6374.

As for the multithreaded simultaneous approach: it's going to be too hard for us to maintain given the state of Ruby's multithreading support.
