### ISSUE TITLE
SDK Path broken on macOS 10.13

### ISSUE THREAD

**Issue by deus0ww** [Homebrew/brew#7305]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
brew sh
xcrun --sdk macosx --show-sdk-path

## What happened (include command output)
Your shell has been configured to use Homebrew's build environment;
this should help you build stuff. Notably though, the system versions of
gem and pip will ignore our configuration and insist on using the
environment they were built under (mostly). Sadly, scons will also
ignore our configuration.
When done, type `exit`.
brew ~$ xcrun --sdk macosx --show-sdk-path
xcrun: error: missing DEVELOPER_DIR path: 
brew ~$ 

## What you expected to happen
Your shell has been configured to use Homebrew's build environment;
this should help you build stuff. Notably though, the system versions of
gem and pip will ignore our configuration and insist on using the
environment they were built under (mostly). Sadly, scons will also
ignore our configuration.
When done, type `exit`.
brew ~$ xcrun --sdk macosx --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
brew ~$ 

## Output of `brew config` and `brew doctor` commands
<pre>
HOMEBREW_VERSION: 2.2.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ae26808a6793c78f749835aed2ab84cd2fa6544
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d4bad9e5f94c2bddc15c9238b8696eca14b04c13
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEVELOPER: set
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: /usr/local/bin/bbedit
HOMEBREW_FORCE_BREWED_CURL: 1
HOMEBREW_FORCE_BREWED_GIT: 1
HOMEBREW_FORCE_VENDOR_RUBY: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
CPU: octa-core 64-bit penryn
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1000
Git: 2.26.0 => /usr/local/opt/git/bin/git
Curl: 7.69.1 => /usr/local/opt/curl/bin/curl
Java: 14, 1.8.0_241
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11

Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment]
Can you `brew update` and try again? Thanks!

**Comment by deus0ww** [comment]
Seems like it's fixed. Thank you!
