### ISSUE TITLE
`brew doctor` warns about newer Command Line Tools being available, while they got updated today

### ISSUE THREAD

**Issue by pro-sumer** [Homebrew/brew#7314]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
## What you were trying to do (and why)

Run `brew doctor`

## What happened (include command output)

Warning that newer Command Line Tools are available:

<pre>
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.
</pre>

## What you expected to happen

No warning, since I have the latest Command Line Tools (they got updated today, after installing the macOS Catalina 10.15.4 Supplemental Update):

<pre>
❯ xcodebuild -version
Xcode 11.4
Build version 11E146
</pre>

* On the suggested Apple web site the latest version is 11.4, from Mar 24, 2020
* Software Update reports "Your Mac is up to date - macOS Catalina 10.15.4" (Last checked today)

## Step-by-step reproduction instructions (by running `brew` commands)

`brew doctor`

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.2.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ae26808a6793c78f749835aed2ab84cd2fa6544
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 35893bb4a37f94127cd4727cdd664a0d97af91a2
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: subl -w
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_242
macOS: 10.15.4-x86_64
CLT: 11.0.33.16
Xcode: 11.4
</pre>

<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.
</pre>

**Comment by MikeMcQuaid** [comment]
> CLT: 11.0.33.16
> Xcode: 11.4

`xcodebuild` is not testing the CLT version.

> https://developer.apple.com/download/more/.

There is a newer version available here. For some reason Apple seem to not be reliably pushing these versions out through software update.

> include command output

You omitted:

> Please note that these warnings are just used to help the Homebrew maintainers with debugging if you file an issue. If everything you use Homebrew for is working fine: please don't worry or file an issue; just ignore this. Thanks!

We're exploring changing this in https://github.com/Homebrew/brew/pull/7313.
