### ISSUE TITLE
`brew extract` should instruct users to run `git fetch --unshallow`

### ISSUE THREAD

**Issue by phil-blain** [Homebrew/brew#7315]
# A detailed description of the proposed feature

When `brew extract` fails to find a previous version of a formula, it fails with:
https://github.com/Homebrew/brew/blob/e12da9491d2dc557636458c265196fedde34a30a/Library/Homebrew/dev-cmd/extract.rb#L135

However, it can fail to find the desired version simply because `hombrew-core` is shallow, and running `git -C $(brew --repository homebrew/homebrew-core) fetch --unshallow` before retrying `brew extract` simply solves the problem.

# The motivation for the feature

For people that are not aware that Homebrew uses Git, or what even is a shallow clone, it could be great to have the error message instruct them to try to "unshallow" the tap repository.

# How the feature would be relevant to at least 90% of Homebrew users

I don't know about 90%, but I'd say this would be helpful for 90% of `brew extract` users!

# What alternatives to the feature have been considered

`brew extract` could run `git fetch --unshallow` itself, but I guess that some people would not like that because of disk space.

**Comment by MikeMcQuaid** [comment]
Sounds good! Could you submit a PR? See https://github.com/Homebrew/brew/blob/c382dbc94fb1e4724aadd545160b9555651a227b/Library/Homebrew/missing_formula.rb#L142-L147 for some example code.

**Comment by phil-blain** [comment]
I'll try to do that.
