### ISSUE TITLE
Use zsh path array

### ISSUE THREAD

**Issue by camsteffen** [Homebrew/brew#7319]
When printing example code to fix my `PATH` variable in my `.zshrc`, use the `path` array. This only applies to zsh.

Current output:
```
If you need to have gettext first in your PATH run:
  echo 'export PATH="/homebrew/opt/gettext/bin:$PATH"' >> ~/.zshrc
```

Expected output
```
If you need to have gettext first in your PATH run:
  echo 'path=("/homebrew/opt/gettext/bin" $path); export PATH' >> ~/.zshrc
```

Pros:
* more idiomatic code
* teaches people a cool feature of zsh

Cons:
* ???

I would be willing to open a pull request if desired.

**Comment by MikeMcQuaid** [comment]
Would rather have code that's compatible with Bash and ZSH. I say this as a ZSH user of many years. 

Please always fill out the issue template, as requested.
