### ISSUE TITLE
`brew cleanup` sometimes removes downloads for installed casks and formulae

### ISSUE THREAD

**Issue by jabenninghoff** [Homebrew/brew#7320]
- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Running `brew cleanup -s` to remove outdated versions of downloaded casks.

## What happened (include command output)

`brew cleanup -s` removed outdated casks, logs, _and_ the download for the most current version of an installed cask (airtool).

<details>
  <summary>Command output</summary>
  <pre>
Removing: /Users/agamemnon/Library/Caches/Homebrew/Cask/tor-browser--9.0.8.dmg... (75.7MB)
Removing: /Users/agamemnon/Library/Caches/Homebrew/Cask/airtool--1.9.pkg... (2.4MB)
Removing: /Users/agamemnon/Library/Caches/Homebrew/Cask/slack--4.4.1.zip... (69.4MB)
Removing: /Users/agamemnon/Library/Caches/Homebrew/Cask/wireshark--3.2.2.dmg... (93.0MB)
Removing: /Users/agamemnon/Library/Caches/Homebrew/Cask/vlc--3.0.8.dmg... (49.1MB)
Removing: /Users/agamemnon/Library/Logs/Homebrew/nethack... (64B)
  </pre>
</details>

## What you expected to happen

Per the help, `brew cleanup -s` should always preserve downloads for installed casks, and should not have deleted the installed & current version of airtool (1.9).

```
$ brew cask info airtool
airtool: 1.9
https://www.adriangranados.com/apps/airtool
/usr/local/Caskroom/airtool/1.9 (2.4MB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/airtool.rb
```

## Step-by-step reproduction instructions (by running `brew` commands)

Run `brew cleanup -s`. I've noticed this behavior on multiple machines, but only older downloads are deleted (making it harder to reproduce). I've been running `brew fetch` and `brew cask fetch` to re-cache the downloads as a workaround.

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.2.12-18-g740e024
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 740e0242fa1e8dddc5a56ded6bdb08b912262cb0
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eb01d33982148a156b8e58e60f3f689e6f1b0641
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 14
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
</pre>

**Comment by jonchang** [comment]
I think this is expected behavior?

```
    -s                               Scrub the cache, including downloads for
                                     even the latest versions.
```

**Comment by jabenninghoff** [comment]
I would expect that the latest version be cleaned, but not for any installed versions.
```
    -s                               Scrub the cache, including downloads for
                                     even the latest versions. Note downloads
                                     for any installed formulae or casks will
                                     still not be deleted. If you want to delete
                                     those too: rm -rf "$(brew --cache)"
```

**Comment by jabenninghoff** [comment]
Update: I've found that this affects the behavior of `brew cleanup` as well, for both casks and formulae. Here, `brew cleanup` correctly proposes removing meld (old version no longer installed) but also the downloads for the installed versions of hr, netnewswire and wakeonlan:

```
$ brew cleanup -n
Would remove: /Users/agamemnon/Library/Caches/Homebrew/hr--1.2.tar.gz (2.3KB)
Would remove: /Users/agamemnon/Library/Caches/Homebrew/Cask/netnewswire--5.0.3.zip (4.9MB)
Would remove: /Users/agamemnon/Library/Caches/Homebrew/Cask/wakeonlan--1.0.zip (894.3KB)
Would remove: /Users/agamemnon/Library/Caches/Homebrew/Cask/meld--3.19.2-r6,osx-15.dmg (23.0MB)
==> This operation would free approximately 28.7MB of disk space.
```
Directory listing for removed downloads:
```
-rw-r--r--  1 agamemnon  staff     2396 Dec 14 12:33 Library/Caches/Homebrew/downloads/2ead7171279848122383650f8f909af71f89dfbf1241b96ea8873a3abfab7ac5--hr-1.2.tar.gz
-rw-r--r--@ 1 agamemnon  staff  5152201 Oct 22 11:09 Library/Caches/Homebrew/downloads/ee94af92007f6c0a767e0f7407c285a23843c8c160d33eb562c8b51ed145dc94--NetNewsWire5.0.3.zip
-rw-r--r--@ 1 agamemnon  staff   915781 Jul  9  2019 Library/Caches/Homebrew/downloads/9fbd907ac12107154b1dfbc43a8eb82b2b958d22d7a4af4cad959cbbf9cdb0a3--WakeOnLan1.0.zip
```

**Comment by MikeMcQuaid** [comment]
@jabenninghoff Can you confirm that it removes `hr` and that you have the newest version installed? If so, can you adjust the title of the issue? Thanks!

**Comment by jabenninghoff** [comment]
Confirmed, and updated the title to reflect the issue.

**Comment by jabenninghoff** [comment]
It seems that `brew cleanup` is removing downloads that are older than 120 days: (note that Dec 20 is 121 days ago). This makes the issue harder to detect since it only impacts Formulae and Casks that haven't been updated in the past 120 days.
```
$ brew cleanup -n
Would remove: /Users/agamemnon/Library/Caches/Homebrew/libvpx--1.8.2.mojave.bottle.tar.gz (1MB)
==> This operation would free approximately 1MB of disk space.

$ ls -l /Users/agamemnon/Library/Caches/Homebrew/libvpx--1.8.2.mojave.bottle.tar.gz
lrwxr-xr-x  1 agamemnon  staff  109 Apr 17 12:38 /Users/agamemnon/Library/Caches/Homebrew/libvpx--1.8.2.mojave.bottle.tar.gz -> downloads/6431c14563058a2018e6ba090c47b8de02af65551c81a3e957fb528935ee3eff--libvpx-1.8.2.mojave.bottle.tar.gz
$ ls -l /Users/agamemnon/Library/Caches/Homebrew/downloads/6431c14563058a2018e6ba090c47b8de02af65551c81a3e957fb528935ee3eff--libvpx-1.8.2.mojave.bottle.tar.gz 
-rw-r--r--  1 agamemnon  staff  1055190 Dec 20 21:16 /Users/agamemnon/Library/Caches/Homebrew/downloads/6431c14563058a2018e6ba090c47b8de02af65551c81a3e957fb528935ee3eff--libvpx-1.8.2.mojave.bottle.tar.gz

$ brew cleanup
Removing: /Users/agamemnon/Library/Caches/Homebrew/libvpx--1.8.2.mojave.bottle.tar.gz... (1MB)

**Comment by MikeMcQuaid** [comment]
Ah, yes, this is intentional behaviour: https://github.com/Homebrew/brew/blob/ef3b148147717e0f317d6e51f9b56e50558e6d5f/Library/Homebrew/cleanup.rb#L10

It should probably be documented accordingly.

**Comment by jabenninghoff** [comment]
Thanks - is there a way to override this? I'd like an option to keep downloads & potentially logs for installed packages indefinitely.

**Comment by MikeMcQuaid** [comment]
There's no way to override this currently. We'd consider reviewing a pull request for an environmental variable that sets this value (you could set it to e.g. 10 years).

**Comment by MikeMcQuaid** [comment]
Actually, will open a PR myself.

**Comment by jabenninghoff** [comment]
Thanks @MikeMcQuaid !

**Comment by MikeMcQuaid** [comment]
You're welcome!

**Comment by jabenninghoff** [comment]
Hi @MikeMcQuaid, while this fix works for Casks, for some reason it appears to not be working for formulae - i.e. cleanup -s is respecting `HOMEBREW_CLEANUP_MAX_AGE_DAYS` for casks but not for formulae.

**Comment by MikeMcQuaid** [comment]
@jabenninghoff Can you open a new (reproducible?) issue. Thanks!

**Comment by jabenninghoff** [comment]
Will do. Repro will be challenging, because it relies on modifying ctime, which seems to [require changing the system time](https://apple.stackexchange.com/questions/99536/changing-creation-date-of-a-file). Working on isolating the issue.
