### ISSUE TITLE
Display list of versions when using "switch"

### ISSUE THREAD

**Issue by kud** [Homebrew/brew#7329]
# A detailed description of the proposed feature

It could be great by doing `brew switch name-of-the-formula`, it displays the list of versions available.

# The motivation for the feature

Sometimes, homebrew tells me to switch to another version but I really do not know what it is installed.

# How the feature would be relevant to at least 90% of Homebrew users

# What alternatives to the feature have been considered

**Comment by MikeMcQuaid** [comment]
Please fully fill out the issue template.

We'll consider a PR for this.
