### ISSUE TITLE
Failed to detect gcc 10 with Linux's brew

### ISSUE THREAD

**Issue by runlevel5** [Homebrew/brew#7330]
## What happened (include command output)

I am using Fedora 32 Linux (which comes with GCC 10)

Whenever I try to install a formula, I got following error:

```
Error: An exception occurred within a child process:
  CompilerSelectionError: pkg-config cannot be built with any available compilers.
Install Clang or run `brew install gcc`.
```

## What you expected to happen

gcc is correctly picked up

## Discussion

I could cook up a new PR if the team is okay with supporting GCC-10

**Comment by Bo98** [comment]
I suppose it's expected that we haven't added support for GCC 10 considering it isn't released yet.

**Comment by runlevel5** [comment]
@Bo98 fair enough. What about other distros that have shipped GCC10? Do we want to support that?

**Comment by Bo98** [comment]
I'd be surprised if any (stable) distro have shipped a GCC version that isn't stable yet.

Feel free to open a PR though. I imagine any changes would be minor anyway. Just don't expect us to fix any issues that arise from using GCC 10 between now and final release.

**Comment by runlevel5** [comment]
Let's revisit this issue when GCC10 is released. Closed for now.

**Comment by MikeMcQuaid** [comment]
Please submit a PR when this it is released and, if you file an issue in future fully fill out the template. Thanks!

**Comment by runlevel5** [comment]
It is now time to re-open this issue. Fedora 32 has been released and it comes with GCC10.

**Comment by MikeMcQuaid** [comment]
> I could cook up a new PR if the team is okay with supporting GCC-10

Yeh, we'll review a PR!

**Comment by runlevel5** [comment]
@MikeMcQuaid GCC 10.1 is now officially released https://gcc.gnu.org/pipermail/gcc-announce/2020/000163.html

**Comment by alebcay** [comment]
Progress tracking on shipping GCC 10.1.0 is happening at https://github.com/Homebrew/homebrew-core/pull/54364.
