### ISSUE TITLE
Prematurely removed python@2? 

### ISSUE THREAD

**Issue by mcstrassell09** [Homebrew/brew#7338]
Python 2.7, while technically deprecated as of Jan 2020, is still a required dependency by many programs in the github community. I've read the some of the issues that have been closed were the  executive decision to pull python@2 from the homebrew formulae was made. The version that macOS ships with has yet to be updated. I feel that for the homebrew users that require homebrew as a depedency manager are at an obvious loss.  I request python@2 it be reinstitued into the core formula until a more appropriate fix is available.  Or..  provide some reasonable direction to bridge the gap. Thank you.

**Comment by claui** [comment]
@mcstrassell09 For a few suggestions how to bridge the gap, see https://github.com/Homebrew/homebrew-core/pull/49796. Another solution would be to look for the deleted formula in the Changes tab of the PR, then copy it to a personal tap.
If you have any questions, read: [How to create and maintain a tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template, as requested.
