### ISSUE TITLE
Error: undefined method `provided_by_macos?' for nil:NilClass on brew audit

### ISSUE THREAD

**Issue by Zymergen-nkitagawa** [Homebrew/brew#7341]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am authoring a new formula and while brew install --build-from-source works, I seem to be getting an exception from inside audit.rb on brew audit.  I have attached brew config/doctor/audit logs with --debug and --verbose enabled.

## What happened (include command output)

$ brew audit --online --new-formula --debug --verbose ./hh-suite.rb
<details>
  <summary>Command output</summary>
  <pre>
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /Users/zymergen/git/homebrew-bio/Formula/hh-suite.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
**Error: undefined method `provided_by_macos?' for nil:NilClass**
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:406:in `block (2 levels) in audit_deps'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:378:in `block in audit_deps'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:375:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:375:in `audit_deps'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1017:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1010:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1010:in `audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:117:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:110:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:110:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'  </pre>
</details>

## What you expected to happen

I expected the audit to pass as it did just 24 hours ago.

## Step-by-step reproduction instructions (by running `brew` commands)

$ brew install --build-from-source ./hh-suite.rb
$ brew audit --strict --new-formula ./hh-suite.rb

## Output of `brew config` and `brew doctor` commands
$ brew config
<pre>
HOMEBREW_VERSION: 2.2.12-58-g9e4dfaf
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9e4dfaf72601270d0d47d2b13d5b65e1ca637e4e
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 478f95c325102ca092a78c9edb004145913c25f1
Core tap last commit: 68 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 1103.0.32.29
Xcode: 11.4</pre>

$ brew doctor
<pre>
Your system is ready to brew.
</pre>

**Comment by jonchang** [comment]
Probably caused by https://github.com/Homebrew/brew/pull/7328

**Comment by Zymergen-nkitagawa** [comment]
> Probably caused by #7328

Hi @jonchang - by applying that one-liner manually on my Homebrew instance the issue goes away.  Thank you very much - looking forward to the merge!
