### ISSUE TITLE
brew info on casks doesn't work

### ISSUE THREAD

**Issue by captnblood** [Homebrew/brew#7345]
- [ yes ] ran `brew update` and can still reproduce the problem?
- [ yes ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ yes ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
i was trying to get info on available 'casked' packages

## What happened (include command output)
i wanted to install wine, so i searched for availability with `brew search wine`.
i saw there was a few, i wanted to confirm version number with `brew info`  to decide which one i wanted to install. but that didn't produced expected results.
with a quick search i saw this issue was raised before ([#5538](https://github.com/Homebrew/brew/pull/5538)), and marked as solved.
the problem remains in this particular case apparently.
worse, trying to get info for a cask using full line `brew info homebrew/cask/wine-stable` will result in brew actualy trying to install it while i only asked for info.
please see term output below.

<details>
  <summary>Command output</summary>
  <pre>
```
captnblood@mbp ~ % brew search wine                   
==> Formulae
twine-pypi                 winetricks                 winexe
==> Casks
homebrew/cask-versions/wine-devel        homebrew/cask/wine-stable
homebrew/cask-versions/wine-staging
captnblood@mbp ~ % brew info wine-stable
Error: No available formula with the name "wine-stable" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
captnblood@mbp ~ % 
captnblood@mbp ~ % brew info homebrew/cask/wine-stable
Error: No available formula with the name "homebrew/cask/wine-stable" 
Please tap it and then try again: brew tap homebrew/cask
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
^C ^C ^C ceiving objects:   6% (25574/426231), 4.46 MiB | 4.43 MiB/s
captnblood@mbp ~ % 
```
  </pre>
</details>

## What you expected to happen
i expected `brew info` to work on casked packages.

## Step-by-step reproduction instructions (by running `brew` commands)
`brew info wine-stable`
or
`brew info homebrew/cask/wine-stable`

## Output of `brew config` and `brew doctor` commands

<pre>
captnblood@mbp ~ % brew doctor          
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
captnblood@mbp ~ % 
</pre>

**Comment by MikeMcQuaid** [comment]
> Output of `brew config`

You didn't include this. I cannot reproduce this on my machine.

**Comment by captnblood** [comment]
sorry i forgot to include it.
here it is:
```
captnblood@mbp ~ % brew help  
Example usage:
  brew search [TEXT|/REGEX/]
  brew info [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install --verbose --debug FORMULA

Contributing:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]

Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh
captnblood@mbp ~ % brew help |grep cask
captnblood@mbp ~ % brew help |grep info
  brew info [FORMULA...]
captnblood@mbp ~ % brew config
HOMEBREW_VERSION: 2.2.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ae26808a6793c78f749835aed2ab84cd2fa6544
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 06a8b116f145b20ee67d83e2bb94f9d7426f24f6
Core tap last commit: 64 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 1103.0.32.29
Xcode: N/A
captnblood@mbp ~ % 
```

**Comment by MikeMcQuaid** [comment]
> ==> Tapping homebrew/cask

Why did you cancel this running? It's expected it won't work if it's not tapped.

**Comment by captnblood** [comment]
i did not expect that brew needed to clone the whole package localy to just get info on it (specificaly version number of the package).  if this is how brew work in this particular case, then this is probably not optimal. 
i got a download of 200mb just for getting a version string ?
```
captnblood@mbp ~ % brew info homebrew/cask/wine-stable
Error: No available formula with the name "homebrew/cask/wine-stable" 
Please tap it and then try again: brew tap homebrew/cask
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 426235 (delta 8), reused 8 (delta 4), pack-reused 426217
Receiving objects: 100% (426235/426235), 192.46 MiB | 4.83 MiB/s, done.
Resolving deltas: 100% (301388/301388), done.
Tapped 1 command and 3521 casks (3,637 files, 206.5MB).
Found a cask named "homebrew/cask/wine-stable" instead.

wine-stable: 5.0
https://wiki.winehq.org/MacOS
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/wine-stable.rb
==> Name
WineHQ-stable
==> Artifacts
winehq-stable-5.0.pkg (Pkg)
/Applications/Wine Stable.app/Contents/Resources/start/bin/appdb (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/msiexec (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/notepad (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/regedit (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/regsvr32 (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/wine (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/wine64 (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/wineboot (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/winecfg (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/wineconsole (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/winedbg (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/winefile (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/winemine (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/winepath (Binary)
/Applications/Wine Stable.app/Contents/Resources/wine/bin/wineserver (Binary)
/Applications/Wine Stable.app/Contents/Resources/start/bin/winehelp (Binary)
==> Caveats
wine-stable installs support for running 64 bit applications in Wine, which is considered experimental.
If you do not want 64 bit support, you should download and install the wine-stable package manually.
captnblood@mbp ~ 

```
suppose that now i can see version number is `wine-stable: 5.0` and i decide it would be better to install another version, i will need to repeat this and get a localy copy of the whole packages i wish to find version number for ? so it could result in more than 600mb just to get a few version string, plus 200mb again the one i finally decide to install (if any).

**Comment by MikeMcQuaid** [comment]
> if this is how brew work in this particular case, then this is probably not optimal.

If you can figure out how to do it without and submit a pull request: we'll review it.



> so it could result in more than 600mb just to get a few version string, plus 200mb again the one i finally decide to install (if any).

No. It will need to download that repository once and then `brew update` will keep it up to date.



> i can understand why you're so quick at closing issues. but, hiding problems under the carpet never made them disapear you know ? please don't smash your belongings in rage. this is just light humor, and i'm contributing here.

We do not consider filing issues "contributions". Furthermore, we do not appreciate issues filed without the requested information provided. Additionally, this was closed quickly because it was not an issue (I tried it on my machine and it worked therefore it is not reproducible).

**Comment by captnblood** [comment]
in case you have trouble understanding the benefit of issue reporting, let me explain it:
it helps in that by mass testing your software, and having people reporting problems as they get discovered, you get a sense of what need to be done to solve problems and make your software better.
mass testing and using people's issue reports accelerate tremendously bug spotting. and give you a chance to correct them, whereas if you'd do without, some problem scould take much longer to be discovered. this is basic logic.
you consider badly people that give a bit of their time to help you finding bugs.
this isn't nice. what are we to you ? bug reporting drone squad ?

**Comment by MikeMcQuaid** [comment]
This conversation has gone as far as is productive, I think.
