### ISSUE TITLE
Fresh install of Home-brew causes oh-my-zsh permission errors when using zsh

### ISSUE THREAD

**Issue by JackWH** [Homebrew/brew#7350]
## What you were trying to do (and why)

I have a fresh copy of macOS Catalina, which is using `zsh` as the default shell. I have installed `oh-my-zsh` too.

I just finished installing Homebrew, and now, every time I open a new Terminal session, I see permission warnings from `oh-my-zsh`.

I appreciate I can add `ZSH_DISABLE_COMPFIX` to my `.zshrc` file, but this doesn't seem like a good idea.

## What happened (include command output)

New Terminal windows now show the following warning:

<details>
  <summary>Command output</summary>
  <pre>

  [oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x  3 jack  admin   96 Apr 13 20:08 /usr/local/share/zsh
drwxrwxr-x  4 jack  admin  128 Apr 13 20:11 /usr/local/share/zsh/site-functions

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.

  </pre>
</details>

## What you expected to happen

There should not be a warning, Homebrew should install its completions with the correct permissions.

## Step-by-step reproduction instructions (by running `brew` commands)

```
 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew help
brew update
brew doctor
brew config
```

## Output of `brew config` and `brew doctor` commands

<pre>
▶ brew doctor
Your system is ready to brew.

▶ brew config
HOMEBREW_VERSION: 2.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3d9cf83fec45a75af61551f53d25383abe009d31
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ae7ff1293bc1c8a62946d4aaa107651321c33baa
Core tap last commit: 22 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 11.4.0.0.1.1583798712
Xcode: 11.4
</pre>

**Comment by MikeMcQuaid** [comment]
Can you reproduce this with plain `zsh` (i.e. not with `oh-my-zsh`)?

**Comment by JackWH** [comment]
I haven't tried it, but logic would suggest it can't be reproduced on plain `zsh`.

`ZSH_DISABLE_COMPFIX` and the specific error message output are all contained in `~/.oh-my-zsh/lib/compfix.sh`, meaning they are part of the `oh-my-zsh` installation.

**Comment by MikeMcQuaid** [comment]
In that case given it doesn't apply to software shipping with macOS: we'll accept a PR to Homebrew/install to fix this but don't consider it our bug, sorry.
