### ISSUE TITLE
why i can not run ./uninstall.sh

### ISSUE THREAD

**Issue by TorMoor** [Homebrew/brew#7362]
i can not install any software in brew
so i want to uninstall an install it

i download the install-master form repository
and run ./uninstall.sh
but it shows this :

fczhao@iMac install-master % ./uninstall.sh
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out

how can solve it ?

**Comment by MikeMcQuaid** [comment]
If you can't connect to GitHub: I'm afraid that's nothing to do with Homebrew.
