### ISSUE TITLE
Do tapped formulae need to use the full formula name for depends_on statements in that tap?

### ISSUE THREAD

**Issue by scpeters** [Homebrew/brew#738]
I maintain the [osrf/simulation](https://github.com/osrf/homebrew-simulation) tap, which has a few formula that depend on formulae from that tap. For example, [osrf/simulation/gazebo6](https://github.com/osrf/homebrew-simulation/blob/master/gazebo6.rb#L25) depends on [osrf/simulation/sdformat3](https://github.com/osrf/homebrew-simulation/blob/master/sdformat3.rb). My question is: does the `depends_on` statement have to use the fully qualified name or is the short name ok?

ie:

~~~
  depends_on "osrf/simulation/sdformat3"
~~~
vs
~~~
  depends_on "sdformat3"
~~~

I've been using the short name without problems for quite a while, but I recently noticed an issue with `test-bot` that I've traced to the use of the full name vs. the short name. I created a pull request to bump the formula revision of `sdformat3` and `gazebo6` ( https://github.com/osrf/homebrew-simulation/pull/129 ), and since gazebo6 depends on sdformat3, test-bot should build sdformat3 first. However, the [Homebrew::Test::formulae function in test-bot.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/test-bot.rb#L763-L782) is given the full names as arguments (`["osrf/simulation/gazebo6", "osrf/simulation/sdformat3"]`) but doesn't match any of those names in the output of `brew deps` since it gives short names, re-order them so that sdformat3 is built first. Instead they are built in alphabetical order.

Sorry if that's a bit long-winded. I could work around this issue by using full names in all my depends_on statements, but I'd prefer if test-bot was intended to handle that case. I'll work on a pull request if so.

**Comment by scpeters** [comment]
To reproduce the error:

~~~
brew test-bot --tap=osrf/simulation --ci-pr https://github.com/osrf/homebrew-simulation/pull/129
~~~

**Comment by scpeters** [comment]
I've made a small modification to test-bot in https://github.com/scpeters/brew/commit/d62fd50f8c6422e1f0a3c55cca1fafd5870f44b0 but it's not perfect. Instead of building `["osrf/simulation/gazebo6", "osrf/simulation/sdformat3"]` in alphabetical order, it builds `sdformat3` and then `["osrf/simulation/gazebo6", "osrf/simulation/sdformat3"]` in alphabetical order. So it builds sdformat3 twice, but at least it doesn't fail this time.

**Comment by MikeMcQuaid** [comment]
In short: no, this should not be necessary.

The best solution is probably to coax e.g. `brew deps` and friends to always output the full names and use them for comparisons. We'd accept a PR for this.

**Comment by scpeters** [comment]
Thanks, that makes more sense than my first attempt. I'll start working on a pull request.

**Comment by MikeMcQuaid** [comment]
@scpeters Great, thanks!

**Comment by scpeters** [comment]
I submitted #830 to allow `brew deps` to optionally print full formula names.
