### ISSUE TITLE
Improve autocompletion

### ISSUE THREAD

**Issue by mcandre** [Homebrew/brew#7383]
Currently, any local development `.RB` files are ignored when performing `brew install <...>[TAB]`; only already published formula names complete. This can lead to glitches during testing.

**Comment by jonchang** [comment]
You've been asked before to fill out the issue template prior to filing issues.

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
