### ISSUE TITLE
brew deps gets confused if formula is installed

### ISSUE THREAD

**Issue by dankessler** [Homebrew/brew#7386]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I have a personal tap that contains customized versions of formulae that exist in `homebrew-core`.  with the same name (`git-annex-remote-rclone`). If I edit the formula in one of the taps to change the dependencies, then `brew deps formula-name `brew deps` reports the dependencies for the installed version even if I edit the formula. For example, when preparing for a recent [pull request](https://github.com/Homebrew/homebrew-core/pull/53286) I was experimenting with reducing a set of dependencies, which I'd prefer to do in a tap that is isolated from homebred-core. 

## What happened (include command output)

I tapped my repo (dankessler/dmisc), and reported on the deps for both the core formula and my version of the formula. They reflected changes I'd made to the formula. I installed the formula from homebrew-core. Now, brew deps reports the dependencies for the installed version regardless of whether I specify the other tap. 

For reproducibility/demonstration purposes, the formula for `git-annex-remote-rclone` in `dankessler/dmisc` is the same as the one in `homebrew/core` except that I've deleted the dependency on `rclone` from `dankessler/dmisc/git-annex-remote-rclone`. In the command output below, I
1. tap my custom tap `dankessler/dmisc`
2. Show that `git-annex-remote-rclone` has an `rclone` dependency, whereas `dankessler/dmisc/git-annex-remote-rclone` does not have an `rclone` dependency
3. Install `git-annex-remote-rclone`
4. Now, `brew deps dankessler/dmisc/git-annex-remote-rclone` reports that `rclone` *is* a dependency
5. `brew rm git-annex-remote-rclone` and show that the problem is resolved
6. Do the opposite (install from `dankessler/dmsic`) and see that now `brew deps` never reports an `rclone` dependency, but that this is one again fixed by uninstalling

<details>
  <summary>Command output</summary>
  <pre>

➜  ~ git:(kesslerd-mbp.stat) brew tap dankessler/dmisc
Updating Homebrew...
==> Tapping dankessler/dmisc
Cloning into '/usr/local/Homebrew/Library/Taps/dankessler/homebrew-dmisc'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 25 (delta 4), reused 20 (delta 3), pack-reused 0
Receiving objects: 100% (25/25), 4.87 KiB | 2.43 MiB/s, done.
Resolving deltas: 100% (4/4), done.
Tapped 1 formula (28 files, 33.4KB).
➜  ~ git:(kesslerd-mbp.stat) brew deps git-annex-remote-rclone | grep rclone
rclone
➜  ~ git:(kesslerd-mbp.stat) brew deps dankessler/dmisc/git-annex-remote-rclone | grep rclone
➜  ~ git:(kesslerd-mbp.stat) brew install git-annex-remote-rclone
Updating Homebrew...
==> Downloading https://github.com/DanielDent/git-annex-remote-rclone/archive/v0.6.tar.gz
Already downloaded: /Users/kesslerd/Library/Caches/Homebrew/downloads/85ad954996bf1fc389d190bfe0d41b5f499c18403b7ed2312c97f0dc49c8ddb9--git-annex-remote-rclone-0.6.tar.gz
🍺  /usr/local/Cellar/git-annex-remote-rclone/0.6: 5 files, 53.4KB, built in 4 seconds
➜  ~ git:(kesslerd-mbp.stat) brew deps git-annex-remote-rclone | grep rclone                 
rclone
➜  ~ git:(kesslerd-mbp.stat) brew deps dankessler/dmisc/git-annex-remote-rclone | grep rclone
rclone
➜  ~ git:(kesslerd-mbp.stat) brew rm git-annex-remote-rclone
Uninstalling /usr/local/Cellar/git-annex-remote-rclone/0.6... (5 files, 53.4KB)
➜  ~ git:(kesslerd-mbp.stat) brew deps git-annex-remote-rclone | grep rclone                 
rclone
➜  ~ git:(kesslerd-mbp.stat) brew deps dankessler/dmisc/git-annex-remote-rclone | grep rclone
➜  ~ git:(kesslerd-mbp.stat) brew install dankessler/dmisc/git-annex-remote-rclone
Updating Homebrew...
==> Installing git-annex-remote-rclone from dankessler/dmisc
==> Downloading https://github.com/DanielDent/git-annex-remote-rclone/archive/v0.6.tar.gz
Already downloaded: /Users/kesslerd/Library/Caches/Homebrew/downloads/85ad954996bf1fc389d190bfe0d41b5f499c18403b7ed2312c97f0dc49c8ddb9--git-annex-remote-rclone-0.6.tar.gz
🍺  /usr/local/Cellar/git-annex-remote-rclone/0.6: 5 files, 52.6KB, built in 4 seconds
➜  ~ git:(kesslerd-mbp.stat) brew deps git-annex-remote-rclone | grep rclone                 
➜  ~ git:(kesslerd-mbp.stat) brew deps dankessler/dmisc/git-annex-remote-rclone | grep rclone
➜  ~ git:(kesslerd-mbp.stat) brew deps homebrew/core/git-annex-remote-rclone | grep rclone
➜  ~ git:(kesslerd-mbp.stat) 

  </pre>
</details>

## What you expected to happen

I expect `brew deps tap-name/formula-name` to report the correct dependencies whether `other-tap-name/same-formula-name` is installed or not.

## Step-by-step reproduction instructions (by running `brew` commands)

brew tap dankessler/dmisc
brew deps git-annex-remote-rclone | grep rclone
brew deps dankessler/dmisc/git-annex-remote-rclone | grep rclone
brew install git-annex-remote-rclone
brew deps git-annex-remote-rclone | grep rclone
brew deps dankessler/dmisc/git-annex-remote-rclone | grep rclone
brew rm git-annex-remote-rclone
brew deps git-annex-remote-rclone | grep rclone
brew deps dankessler/dmisc/git-annex-remote-rclone | grep rclone
brew install dankessler/dmisc/git-annex-remote-rclone
brew deps git-annex-remote-rclone | grep rclone
brew deps dankessler/dmisc/git-annex-remote-rclone | grep rclone
brew deps homebrew/core/git-annex-remote-rclone | grep rclone

## Output of `brew config` and `brew doctor` commands

Note: most of the noise in `brew doctor` is expected because of previously installing the `r` cask (I think)

<details>
  <summary>Output from brew doctor and brew config</summary>
<pre>
➜  ~ git:(kesslerd-mbp.stat) brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a
➜  ~ git:(kesslerd-mbp.stat) brew config
HOMEBREW_VERSION: 2.2.13-60-ge8d6265
ORIGIN: https://github.com/Homebrew/brew
HEAD: e8d6265560848c50097c4f5c51f21e41d2e07da2
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b4525fb991e9750456a99b730b9ecc6f360441db
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.q3TCdEHr5y/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_252
macOS: 10.15.4-x86_64
CLT: 1103.0.32.29
Xcode: 11.4.1
XQuartz: 2.7.11 => /opt/X11
➜  ~ git:(kesslerd-mbp.stat) 
</pre>
</details>

Interestingly, `brew deps tap-name/formula-name --1` seems to be unaffected (i.e., it gives the expected result) whereas without the `--1` option it does not. I wonder if this behavior is similar/related to what is described in [this issue](https://github.com/Homebrew/brew/issues/7016) and addressed in [this PR](https://github.com/Homebrew/brew/pull/7025).

**Comment by MikeMcQuaid** [comment]
> I have a personal tap that contains customized versions of formulae that exist in `homebrew-core`.

Don't do this. It doesn't work well at all.

We'll review PRs to address issues like this but there are (many) known problems with shadowing Homebrew/core formulae names in taps and most will never be addressed.

**Comment by dankessler** [comment]
Based on your response, I’ve reread the [guide to taps](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and now see that the `tap-name/formula-name` syntax is *only* suggested for installation, and moreover as a shortcut for tapping then installing and not suggested as a way to shadow. I see now that I was wrong to think of this syntax as a consistent way to specify fully-qualified formulae but instead as a convenient way to tap/install in one command. 

Thanks for the clarification!

**Comment by MikeMcQuaid** [comment]
You're welcome ❤️
