### ISSUE TITLE
Migrate audit rules to rubocops

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#7392]
In https://github.com/Homebrew/brew/pull/7371/files I have added lots of `# TODO: check could be in RuboCop` comments to `Library/Homebrew/dev-cmd/audit.rb`. These indicate that the audit check/problem below does not rely on `Formula` state so could be moved to a RuboCop (https://github.com/Homebrew/brew/tree/master/Library/Homebrew/rubocops) to be faster, more reliable and provided in-editor to users.

No need to say "I'm planning on working on this" or similar in this issue but feel free to open a PR that doesn't work (yet!) and ask for help.

**Comment by MikeMcQuaid** [comment]
@Rylan12 one for you if you hadn't seen this 😉

**Comment by Rylan12** [comment]
> @Rylan12 one for you if you hadn't seen this 😉

Hmm looks like my contributions have been following a little bit of a pattern... 🤔 

Thanks for pointing it out!

**Comment by Rylan12** [comment]
#7909 Takes care of all but two of these.

Here are the remaining ones:

- `system "foo", "#{bar}"` should become `system "foo", bar`: RuboCop currently warns saying ``Prefer `to_s` over string interpolation.`` Is this sufficient? If not, should this rubocop check be removed for formulae so users don't get two style messages for the same problem?
- `require "formula"` is unnecessary: I can't figure out how to check for lines outside of the formula's class with rubocop so I'm not sure exactly how to do this.

**Comment by MikeMcQuaid** [comment]
> * `system "foo", "#{bar}"` should become `system "foo", bar`: RuboCop currently warns saying `` Prefer `to_s` over string interpolation. `` Is this sufficient? If not, should this rubocop check be removed for formulae so users don't get two style messages for the same problem?

Yeah, I think just remove this one 👍.

**Comment by Rylan12** [comment]
Sounds good!
