### ISSUE TITLE
Rehash after install on zsh systems

### ISSUE THREAD

**Issue by sophistifunk** [Homebrew/brew#7411]
# A detailed description of the proposed feature

It'd be great if `rehash` was automatically run after every executable install when running on zsh systems (Catalina). Obviously it's not the fault of Homebrew that this is needed, but it's stupid to install something and have it not work for autocomplete straight away.

# The motivation for the feature

Save the user having to remember to run it after every install that adds binaries.

# How the feature would be relevant to at least 90% of Homebrew users

I guess as soon as 90% of users are on zsh

# What alternatives to the feature have been considered

The alternative is having to do it yourself

**Comment by MikeMcQuaid** [comment]
I'm pretty sure this isn't possible given that Homebrew is executed in a non-ZSH shell at all times. If you can figure it out and submit a PR, though: we'll review it. Thanks!
