### ISSUE TITLE
brew installation fails to upgrade ruby 

### ISSUE THREAD

**Issue by kamau-edwin** [Homebrew/brew#7416]
## What you were trying to do (and why)
Deleted brew to perform a fresh installation as brew installed sqlite3 needed an upgrade  but I could not update it due to ruby upgrade issue

## What happened (include command output)

Problem revolves around the initial ruby installation which is version 2.3.7 but brew  requires version 2.6. 
While ruby 2.3.7 and brew  installs successfully however, when brew attempts to upgrade ruby to version 2.6 the upgrade  fails. 

The error below persists during brew installation and upon all brew commands

<details>
<summary>Command output</summary>

sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
......
Checking out files: 100% (1879/1879), done.
HEAD is now at cc6ccc4 Merge pull request #7413 from MikeMcQuaid/actions-linuxbrew
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 5] Input/output error
Error: Another active Homebrew vendor-install-ruby process is already in progress.
Please wait for it to finish or terminate it to continue.
Error: Failed to upgrade vendor Ruby.
$.linuxbrew/Homebrew/Library/Homebrew/brew.rb:10:in `<main>': Homebrew must be run under Ruby 2.6! You're running 2.3.7. (RuntimeError)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 5] Input/output error
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
Failed during: brew update --force

$ brew update --force
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 5] Input/output error
Error: Another active Homebrew vendor-install-ruby process is already in progress.
Please wait for it to finish or terminate it to continue.
Error: Failed to upgrade vendor Ruby.
</details>

## What you expected to happen
Running the above commands on 
System: GNU/Linux
Release: 3.10.0-514.10.2.el7.x86_64
Version:  #1 SMP Fri Mar 3 00:04:05 UTC 2017 
Processer: x86_64
Installation with errors and or recommendation that fixes any issues. 
I do not have sudo permission for installation so brew has to install in my home directory as .linuxbrew/

I have performed the following in an attempt to fix the issue 
1. rm -rf ./linuxbrew/var/homebrew/locks # to remove any locks 

2. ps -aux |grep ruby|brew # to check for active ruby processes

I think the problem is a related to a wrong path but I cannot figure out which one 
perhaps in this file 
     .linuxbrew/Homebrew/Library/Homebrew/utils/ruby.sh 

## Step-by-step reproduction instructions (by running `brew` commands)

All the `brew` commands raise the above error 

[similar previous issue ](https://github.com/Homebrew/homebrew-core/issues/5159)

## Output of `brew config` and `brew doctor` commands
<pre>
</pre>

**Comment by MikeMcQuaid** [comment]
Please post this on our [Discourse](https://discourse.brew.sh) instead: this is an issue specific to your machine. Sorry!
