### ISSUE TITLE
Should Homebrew be unsetting group write bits?

### ISSUE THREAD

**Issue by alexreg** [Homebrew/brew#7420]
Currently, it appears that Homebrew is unsetting some group write bits on certain directories when it runs. Is this intentional? It is getting in the way of brewdo operation, which expects everything in `/usr/local` to be group-writeable (specifically the `/usr/local/bin` and `/usr/local/share/man/man1` dirs in my instance).

I appreciate this more of a request for clarification rather than a feature request or bug, but hopefully it's something that can be answered pretty easily, and then turned into a request or PR depending on the answer.

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template. If you feel it isn't relevant: that's a sign you should post on Discourse instead.
> It is getting in the way of brewdo operation

`brewdo` is unsupported. This should be submitted as an issue in that.



> Is this intentional?

No but we don't try to set group write bits ever, either. We'll accept PRs to optionally improve this based on user configuration (e.g. a `umask` or environment variable) as we don't want to be setting group write globally by default.

**Comment by alexreg** [comment]
Hah, well I maintain brewdo, so not much point of submitting an issue there!

I wasn't sure if any project maintainers of brew like yourself were on Discourse, but fair enough.

I'll have a look at the codebase, but if you could point me to where it unsets group write bits, that would be much appreciated.

**Comment by MikeMcQuaid** [comment]
> I'll have a look at the codebase, but if you could point me to where it unsets group write bits, that would be much appreciated.

It never does this intentionally. More likely is that any group write bits aren't being intentionally set.

**Comment by alexreg** [comment]
Interesting. The `/usr/local/bin` dir isn't newly-created though, so I wonder what's modifying permissions on that. Maybe I should double-check that brewdo isn't doing it!

Anyway, thanks for clarifying.
