### ISSUE TITLE
Support json output for `brew cask outdated`

### ISSUE THREAD

**Issue by libinvarghese** [Homebrew/brew#7432]
# A detailed description of the proposed feature

I would like to get the output of `brew cask outdated` in json format. eg: 
```
brew cask outdated --json
```

# The motivation for the feature
It would be great to have `brew cask outdated` support the similar features of `brew outdated`.

# How the feature would be relevant to at least 90% of Homebrew users
Since `brew outdated --json` provides a json output, to help tools that depend on json output to have common logic.

**Comment by FTLam11** [comment]
Mind if I volunteer taking on this issue?

**Comment by vitorgalvao** [comment]
> Mind if I volunteer taking on this issue?

Sure, thank you for offering.

> Also, I don't think there is currently pinned/pinned_version information for `Cask::Cask`.

By design, casks cannot be pinned. Many macOS apps auto-update, and we can’t really avoid that, so pinning wouldn’t work.

**Comment by vitorgalvao** [comment]
Thank you, @FTLam11!
