### ISSUE TITLE
brew cask update duplicates

### ISSUE THREAD

**Issue by JeremyCavanagh** [Homebrew/brew#7449]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew update && brew upgrade && brew cleanup

## What happened (include command output)

Everything works fine. However, rather strangely, the updated casks list every cask twice?

## What you expected to happen

each updated cask listed once.

## Step-by-step reproduction instructions (by running `brew` commands)

brew update && brew upgrade && brew cleanup

## Output of `brew config` and `brew doctor` commands

<pre>
╰─>$ brew config
HOMEBREW_VERSION: 2.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3d9cf83fec45a75af61551f53d25383abe009d31
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 629e85d80500b57dc622fdc6dc27ebc54017b27f
Core tap last commit: 28 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.UOGBDSDSMJ/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 2
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1000
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 14.0.1, 13.0.3, 11.0.7, 11.0.6, 1.8.0_252
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11

╰─>$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/opt/pkg-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/SUVMMFaker.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
  fontforge
  wireshark
![updated casks](https://user-images.githubusercontent.com/5337880/80361619-8e6eb480-8881-11ea-9885-852efdf6e224.png)

</pre>

**Comment by Bo98** [comment]
What's the output of `brew tap`?

**Comment by J-Siu** [comment]
I see same duplicate when doing search, update etc. Following is `brew tap` output"

```sh
$ brew tap
caskroom/cask
go-swagger/go-swagger
homebrew/bundle
homebrew/cask
homebrew/core
homebrew/services
jeffreywildman/virt-manager
```

Should I untap `caskroom/cask` ?

**Comment by MikeMcQuaid** [comment]
> Should I untap `caskroom/cask` ?

Yes.

**Comment by MikeMcQuaid** [comment]
`brew doctor` will warn on these after https://github.com/Homebrew/brew/pull/7525 is merged.
