### ISSUE TITLE
Brew Is Totally Messed Up

### ISSUE THREAD

**Issue by spencerthayer** [Homebrew/brew#745]
- [YES] Ran `brew update` and retried your prior step?
```
$ brew update
/usr/local/Library/brew.rb: line 1: syntax error near unexpected token `('
/usr/local/Library/brew.rb: line 1: `std_trap = trap("INT") { exit! 130 } # no backtrace thanks'
```
- [YES ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
```
$ brew doctor
/usr/local/Library/brew.rb: line 1: syntax error near unexpected token `('
/usr/local/Library/brew.rb: line 1: `std_trap = trap("INT") { exit! 130 } # no backtrace thanks'
```
- [YES ] Ran `brew config`, fixed as many issues as possible and retried your prior step?
```
$ brew config
/usr/local/Library/brew.rb: line 1: syntax error near unexpected token `('
/usr/local/Library/brew.rb: line 1: `std_trap = trap("INT") { exit! 130 } # no backtrace thanks'
```
- [YES ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Any attempt to run brew results in:
```
/usr/local/Library/brew.rb: line 1: syntax error near unexpected token `('
/usr/local/Library/brew.rb: line 1: `std_trap = trap("INT") { exit! 130 } # no backtrace thanks'
```

Attempts to run the GIT fetch and update results in:
```
$  cd $(brew --repo); git fetch; git reset --hard origin/master; brew update
/usr/local/Library/brew.rb: line 1: syntax error near unexpected token `('
/usr/local/Library/brew.rb: line 1: `std_trap = trap("INT") { exit! 130 } # no backtrace thanks'
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
/usr/local/Library/brew.rb: line 1: syntax error near unexpected token `('
/usr/local/Library/brew.rb: line 1: `std_trap = trap("INT") { exit! 130 } # no backtrace thanks'
```

### Issue With Uninstaller

The Brew Uninstall is absolute madness. You want me to consent to removing `/usr/local/Library/`? That's insane. Do you honestly think BREW is the only application running in that directory? 

Further why is Brew dumping files like the `README.md` into the `/usr/local/`? This is totally amature. Clean that up and move these files into their own relevant directories, like I don't know,  `/usr/local/brew` for example. While you're at it also do that for the `.git` directories. I don't like them being in `/usr/local/` either.  

```
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
/usr/local/Library/brew.rb: line 1: syntax error near unexpected token `('
/usr/local/Library/brew.rb: line 1: `std_trap = trap("INT") { exit! 130 } # no backtrace thanks'
Warning: This script will remove:
/Users/spencerthayer/Library/Logs/Homebrew/
/usr/local/.git/
/usr/local/.github/
/usr/local/.gitignore
/usr/local/CODEOFCONDUCT.md
/usr/local/Cellar/
/usr/local/LICENSE.txt
/usr/local/Library/
/usr/local/README.md
/usr/local/bin/brew
/usr/local/share/doc/homebrew/
/usr/local/share/man/man1/brew.1
Are you sure you want to uninstall Homebrew? [y/N] N
```

**Comment by dunn** [comment]
Can you post the outputs of `brew config` and `brew doctor`, please?

> Do you honestly think BREW is the only application running in that directory?

`/usr/local/Library` does not exist by default and I'm not aware of any other applications that use it.  What else do you have in it?

**Comment by MikeMcQuaid** [comment]
> The Brew Uninstall is absolute madness. You want me to consent to removing /usr/local/Library/? That's insane. Do you honestly think BREW is the only application running in that directory?
> 
> Further why is Brew dumping files like the README.md into the /usr/local/? This is totally amature.

Not interested in spending our free time helping people who are going to call us names.

**Comment by ihoskins** [comment]
I too am getting the exact same results as @spencerthayer. I am running OX X 10.10.5

**Comment by DomT4** [comment]
@ihoskins Better to open a new Issue in this sort of case, but try:
```bash
cd /usr/local && git fetch && git reset --hard origin/master
```
Presuming your Homebrew is in `/usr/local`, first.

**Comment by ihoskins** [comment]
That worked. Thank you!
