### ISSUE TITLE
Outdated warning appears after running brew doctor

### ISSUE THREAD

**Issue by 0wnrepo** [Homebrew/brew#7452]
![image](https://user-images.githubusercontent.com/6357768/80401915-c5ff5000-88c5-11ea-88b2-209aa99460b5.png)
![image](https://user-images.githubusercontent.com/6357768/80402333-70777300-88c6-11ea-9e47-37ea3137b2a3.png)

- [ yes ] ran `brew update` and can still reproduce the problem?
- [ this is the issue actually ] ran `brew doctor`, fixed all issues and can still reproduce the problem? - NO, this is the issue actually.
- [ yes ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install brew on a new machine / run brew doctor while having Bitdefender installed on macOS 10.14.5 and 10.15.4.
Traffic scan is running ok, the traffic filtering issue was fixed in Bitdefender.

## What happened (include command output)

Got a warning that homebrew is incompatible with Bitdefender's Traffic Scan.
```
Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See:
  https://github.com/Homebrew/brew/issues/5558
```
Discussed here: https://github.com/Homebrew/brew/issues/5558

## What you expected to happen

Not get a warning, since this is not the case anymore, as it has been fixed.

## Step-by-step reproduction instructions (by running `brew` commands)

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

brew doctor
```

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3d9cf83fec45a75af61551f53d25383abe009d31
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe68b9635017a5b9500916325932120b006630c4
Core tap last commit: 19 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.h13pYVg4go/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_161
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
XQuartz: 2.7.11 => /opt/X11

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See:
  https://github.com/Homebrew/brew/issues/5558

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gettext

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish

Warning: Your Xcode (10.2.1) is outdated.
Please update to Xcode 11.3.1 (or delete it).
Xcode can be updated from the App Store.

</pre>

**Comment by MikeMcQuaid** [comment]
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry or file an issue; just ignore this. Thanks!

Ignore this message. We'll remove it when we see fit. Thanks!
