### ISSUE TITLE
[Suggestion] Support GCC 4.8

### ISSUE THREAD

**Issue by runlevel5** [Homebrew/brew#7471]
Quite a number of institutions and companies are still running on RHEL 7 / CentOS 7 which runs GCC 4.8. It would be great if brew could lower the minimal requirement for GCC from 4.9 to 4.8. I could cook up a new PR if the team is happy to support.

**Comment by MikeMcQuaid** [comment]
Please always fill out the issues template @runlevel5!

For suggestions Discourse is probably a better bet (or, perhaps, the feature request template).

Closing but will let @Homebrew/linux chime in with thoughts.

**Comment by runlevel5** [comment]
I will post this on discourse. Cheers

**Comment by sjackman** [comment]
@runlevel5 GCC 4.7 or later is new enough to build glibc 2.23, which is a hard requirement, unless you are able to install in `/home/linuxbrew/.linuxbrew`, in which case you don't need any compiler at all. Then `brew install gcc` will install GCC 5, and you're off to the races. Open an issue and tag me if you have encounter an error installing Homebrew.

**Comment by runlevel5** [comment]
I've created a new thread in the discourse https://discourse.brew.sh/t/suggestion-support-for-gcc-4-8/7632

Please continue with the discussion there.
