### ISSUE TITLE
Can we add `brew update packagename` for ease-of-use?

### ISSUE THREAD

**Issue by dainmiller** [Homebrew/brew#7473]
# A detailed description of the proposed feature

`brew update packagename` calls `brew upgrade packagename`, instead of printing to the console 
```
Error: This command updates brew itself, and does not take formula names.
Use `brew upgrade tmux` instead.
```

# The motivation for the feature

99% of the time when trying to update a package, I accidentally type `brew update X` instead of `brew upgrade X`. Brew trains us to use the `update` command by linking it to the concept of updating Brew, but then breaks that for packages.

# Downsides

I'm aware `brew update` has its own purpose, but I think the difference between `brew update` and `brew update packagename` is significant enough, both logically and in code, to split this up from the existing functionality.

**Comment by vitorgalvao** [comment]
Have you considered not using `update` at all, and just run `upgrade` every time? Homebrew runs `update` by default when you run other commands, if it hasn’t updated itself in the last 60 seconds. These days, there’s little reason to run `update` manually.

**Comment by MikeMcQuaid** [comment]
As @vitorgalvao said: you don't need to run `brew update` at all now; `brew install` and `brew upgrade` will do it for you.

This would be unnecessarily complex to achieve given the command separation and we don't want to "train" people to use the wrong command.
