### ISSUE TITLE
`brew test` fais with Stdenv supports switching compilers on Linux

### ISSUE THREAD

**Issue by jdbruijn** [Homebrew/brew#7482]
# `brew test` fais with Stdenv supports switching compilers on Linux

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm trying to run `brew tests` on a Homebrew installation on linux in a Docker (Ubuntu 18.04) container.

## What happened (include command output)

The `brew test` command resulted in a failure.

```
Stdenv supports switching compilers
     Failure/Error: subject.clang
```

<details>
  <summary>Command output</summary>
  <pre>
  
```
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Homebrew::Diagnostic::Checks #check_access_directories
     # User is root so everything is writable.
     # ./test/diagnostic_checks_spec.rb:28

  2) UnpackStrategy::Zip when unzip is available #extract
     # unzip not installed.
     # ./test/unpack_strategy/shared_examples.rb:12

Failures:

  1) Stdenv supports switching compilers
     Failure/Error: subject.clang

     FrozenError:
       can't modify frozen Hash
     Shared Example Group: EnvActivation called from ./test/ENV_spec.rb:175
     # ./extend/ENV/std.rb:118:in `clang'
     # ./test/ENV_spec.rb:11:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:185:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

Finished in 25.2 seconds (files took 1.24 seconds to load)
407 examples, 1 failure, 2 pending

Failed examples:

rspec ./test/ENV_spec.rb[1:1] # Stdenv supports switching compilers
```

  </pre>
</details>

## What you expected to happen

I expected the tests to pass, as they did before 2.2.13.

## Step-by-step reproduction instructions (by running `brew` commands)

To reproduce install the latest version of Homebrew in a Ubuntu Docker container (I've used `ubuntu:bionic-20200311@sha256:e5dd9dbb37df5b731a6688fa49f4003359f6f126958c9c928f937bec69836320`) and run `brew tests`.

I've used [this](https://github.com/vidavidorra/docker-linux-images/blob/511d8e3d6c196ab21cfec9a47e6d9201a6576d17/src/install_homebrew.sh) as my installation script as from my [docker-linux-images](https://github.com/vidavidorra/docker-linux-images) repo.

The way I've been reproducing this to track down exactly which commit causes this failure is listed in the section below, where `9b8762f` is the last working commit and `c5c161a` is the first failing commit.

Using the reproduction method below I've tracked down this issue to commit [Homebrew/brew@c5c161a](https://github.com/Homebrew/brew/commit/c5c161adb3d795aaa9869671e7a659c3bcb4e5ec), originating from a PR [Homebrew/brew#7334](https://github.com/Homebrew/brew/pull/7334).

I would be happy to help fixing this issue in any way.

<details>
  <summary>Reproduction steps with specific Homebrew versions</summary>

1. Start a docker container:
```

docker run --rm -it ubuntu:bionic-20200311@sha256:e5dd9dbb37df5b731a6688fa49f4003359f6f126958c9c928f937bec69836320

```
2. Prepare for homebrew (inside the docker container).

```

apt-get update \
 && apt-get install -y --no-install-recommends \
 apt-utils \
 ca-certificates \
 uuid-runtime \
 build-essential \
 curl \
 file \
 git ruby-dev \
 patch \
 zlib1g-dev \
 liblzma-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/_ \
 && apt-get update \
 && apt-get install -y --no-install-recommends locales \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/_ \
 && localedef -i en_US -c -f UTF-8 \
 -A /usr/share/locale/locale.alias en_US.UTF-8 \
 && export LANG='en_US.utf8' \
 && apt-get install \
 && export homebrew_user='linuxbrew' \
 && useradd -m -s /bin/bash "${homebrew_user}" \
     && echo "${homebrew_user} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
 && su - "\${homebrew_user}"

```

3. Install Homebrew and run the tests.
```

git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew \
 && cd ~/.linuxbrew/Homebrew \
 && git checkout c5c161a \
 && mkdir ~/.linuxbrew/bin \
 && ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin \
 && eval \$(~/.linuxbrew/bin/brew shellenv) \
 && HOMEBREW_NO_AUTO_UPDATE=1 brew --version \
 && HOMEBREW_NO_AUTO_UPDATE=1 brew install hello \
 && hello \
 && HOMEBREW_NO_AUTO_UPDATE=1 brew tests

```

</details>

## Output of `brew config` and `brew doctor` commands

<pre>
+ brew doctor
Your system is ready to brew.
+ brew config
HOMEBREW_VERSION: 2.2.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: e2bc0fa6879ce4c74ea2d8f8c654c9812f776b43
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: dd11fe1f022edcc639c30019d9f06b37b815bc83
Core tap last commit: 19 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 5.4.27-1-MANJARO x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.27
/usr/bin/gcc: 7.5.0
glibc: N/A
gcc: N/A
xorg: N/A
</pre>

**Comment by Bo98** [comment]
> Homebrew/brew@c5c161a

Ooh, that's an interesting one. Does it work when you changes this line to `map = Hardware::CPU.optimization_flags.dup`?

https://github.com/Homebrew/brew/blob/c5c161adb3d795aaa9869671e7a659c3bcb4e5ec/Library/Homebrew/extend/ENV/std.rb#L115

**Comment by jdbruijn** [comment]
I tried that on c5c161a and adding `.dup` works. The tests did not fail. I've also made this change in 2.2.14 as wel as the latest commit of master (bffe4dd) and both worked!

I don't understand what this change does exactly, but should I create a PR to fix this?

**Comment by Bo98** [comment]
I've opened a PR. Basically `Hardware::CPU.optimization_flags` is a frozen constant and assigining it to `map` just takes a reference of that, so the assignment on line 118 fails as `map` is read-only. The fix is to instead create a copy (`dup`).

**Comment by jdbruijn** [comment]
Awesome, thanks for the explanation!

**Comment by Bo98** [comment]
Thanks for the bug report!
