### ISSUE TITLE
Adding options to add directories when using a sandbox when testing

### ISSUE THREAD

**Issue by pcr910303** [Homebrew/brew#7501]
# A detailed description of the proposed feature

Currently various `brew` operations including `brew test` are executed in a sandbox with `sandbox-exec` - I think it would be great if there's an option to add some specific directories.

# The motivation for the feature

When writing homebrew tests, there are a lot of cases where it's not possible to write useful tests to check. For example, the direct reason I'm writing this issue is due to the Swift script executable tool [Beak](https://github.com/yonaskolb/Beak) - which communicates with Xcode's SourceKit Daemon via [SourceKitten Framework](https://github.com/jpsim/SourceKitten). This errors in the sandbox environment with an error like below, logged in system.log (newlines inserted for clarity).

```
not allowed in target domain:
type = pid, 
path = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/XPCServices/SourceKitService.xpc 
error = 147: The specified service did not ship in the requestor's bundle, 
origin = /usr/local/Cellar/beak/0.5.1/bin
```

AFAIK there are various tests in `brew` that isn't checking enough behavior to check for breakage - for example the [`swift-sh`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/swift-sh.rb) formula only tests the `eject` functionality, which is not really the main functionality of the binary. (It's main functionality needs to download packages & executing a swift script with the packages.) The formula [`sourcery`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sourcery.rb) does something similar, due to [sandboxing reasons](https://github.com/Homebrew/homebrew-core/blob/d6e1f35b46fc4aa864ba1273af3f7e79fbaa1145/Formula/sourcery.rb#L23).

(Actually it turns out... testing `swift-sh`'s executing functionality does work with the current version of `brew`. Did anything change about the sandbox since [February](https://github.com/Homebrew/homebrew-core/pull/49956)?)

I don't know more of them, but I'm sure plenty of formula tests would benefit if there is a way to selectively escape the sandbox.

# How the feature would be relevant to at least 90% of Homebrew users

This will allow more comprehensive testing for various formulas, which means that all Homebrew users & maintainers will benefit by finding regressions more promptly.

# What alternatives to the feature have been considered

I originally considered to remove the sandbox for tests. Sandboxing tests looks like it was introduced in [this commit](https://github.com/Homebrew/brew/commit/b621edf89dba704f7165fff0f0311f9e0c05bc34) which was shortly after [the PR introducing sandboxes](https://github.com/Homebrew/legacy-homebrew/pull/38361), and [this comment](https://github.com/Homebrew/legacy-homebrew/issues/37552#issuecomment-93990933) mentions that the basic sandbox implementation is finished. I tried to research for reasons why tests are also sandboxed, but unfortunately I couldn't find any rationals - I can only guess. I guessed that sandboxes might be useful for CI, but I'm not really sure because I don't really know how they work.

What are the reasons for sandboxing tests? IMHO, since the test code itself is under Homebrew's control (or the tap author's control) which the user has already decided to trust (unlike the multi-megabyte makefiles that are provided from somewhere else), it's not as a security concern as installing formulas. I just assumed that there are valid reasons, but maybe there isn't a clear reason, and in that case just removing sandboxes while testing might be more easier to implement and more easier to the formula contributor.

**Comment by MikeMcQuaid** [comment]
> What are the reasons for sandboxing tests?

To ensure that tests do not right to random places on the filesystem. This is Homebrew's alternative to dropping privileges.

> (Actually it turns out... testing `swift-sh`'s executing functionality does work with the current version of `brew`. Did anything change about the sandbox since [February](https://github.com/Homebrew/homebrew-core/pull/49956)?)

I can't recall off the top of my head but: nothing major I can think of.

---

In general we'd welcome PRs to adjust the sandbox globally for places that are useful and not invasive. For example, we'll never want to whitelist all of `$HOME` but if there's some harmless `/dev` location needed for proper Xcode integration: we'll consider it.
