### ISSUE TITLE
Warning: Refusing to link: openssl

### ISSUE THREAD

**Issue by cdekok** [Homebrew/brew#751]
I have a problem with compiling php 5.4 with phpbrew it fails on openssl.
Now i read on most posts i need to install and link it with brew but the link fails.

```
➜  ~ brew link openssl
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

```
➜  ~ which openssl
/usr/bin/openssl
```

**Comment by MikeMcQuaid** [comment]
> Now i read on most posts i need to install and link it with brew but the link fails.

Those posts are now wrong, unfortunately. I'm not sure what you need to do with phpbrew now. Better to ask them. Sorry!

**Comment by cdekok** [comment]
Ok i found out already you can specify the path, i guess most posts are outdated i found on google.
phpbrew --debug install 5.4 -- --with-openssl=/usr/local/opt/openssl

**Comment by drem-darios** [comment]
I'm seeing this issue just trying to install openssl. I run the command brew link --force openssl and I see the error above. I don't think it has anything to do with phpbrew. Is there a solution to this issue?

**Comment by MikeMcQuaid** [comment]
@drem-darios We don't support `brew link --force openssl` any more for the reasons described when you run the command.
