### ISSUE TITLE
bump-formula-pr: misleading error message when API token lacks scope

### ISSUE THREAD

**Issue by twpayne** [Homebrew/brew#7515]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Bump a version of a formula using the `brew bump-formula-pr` command.

## What happened (include command output)

I ran:

    brew bump-formula-pr --strict chezmoi --tag=v1.8.1 --revision=4def4f3b96cb01cefe8d7887e8dbfb77908ef267 -v

and got the error message:

    Error: Unable to fork: Not Found!

<details>
  <summary>Command output</summary>
  <pre>
==> replace /^  revision \d+\n(\n(  head "))?/m with "\\2"
==> replace "v1.8.0" with "v1.8.1"
==> replace "017a83f4055a98ac90b030d5739aa560dde239b7" with "4def4f3b96cb01cefe8d7887e8dbfb77908ef267"
/usr/local/bin/brew audit --strict /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chezmoi.rb
Error: Unable to fork: Not Found!
  </pre>
</details>

## What you expected to happen

I expected the bump formula PR to create a PR, or to give a helpful error message as to why it couldn't.

## Step-by-step reproduction instructions (by running `brew` commands)

I did some digging into the code and I found the following:

* The GitHub personal access token I was using for Homebrew did not have `public_repo` scope, it only had public access.
* Consequently the call to `Github.create_fork` (https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L419) was raising an exception, presumably because the GitHub API was returning a 404 somewhere.
* Using a new access token with the `public_repo` scope allowed `brew bump-formula-pr` to complete successfully (https://github.com/Homebrew/homebrew-core/pull/54333).

So, this issue should be reproducible with:

1. Create a GitHub access token with no scopes (i.e. just public access).
2. Use the access token with `brew bump-formula-pr`.

brew already has nice code for reporting insufficient scopes (e.g. https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github.rb#L131), however it looks like the GitHub API is returning a 404 Not Found, not a 401 Unauthorized. I have not verified this.

## Output of `brew config` and `brew doctor` commands

Likely not relevant but included for completeness.

<details>
  <summary>brew config</summary>
<pre>
HOMEBREW_VERSION: 2.2.15-18-g61b98a5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 61b98a5e2ed3d8d00ae93ae325a8fe5363ae2ac2
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cb163da7f4d59dd5634ea41bddf1b5aa2dac90f1
Core tap last commit: 45 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.qHAJpoqlvu/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.1
macOS: 10.15.4-x86_64
CLT: 11.0.33.17
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
</pre>
</details>

<details>
  <summary>brew doctor</summary>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
</pre>
</details>

**Comment by MikeMcQuaid** [comment]
> it looks like the GitHub API is returning a 404 Not Found, not a 401 Unauthorized. I have not verified this.

Can you verify this?

Obviously/unfortunately if the API returns 404 we cannot tell whether it's an invalid scope or the resource doesn't exist.

**Comment by zmwangx** [comment]
This should be fixed by #7634.

**Comment by twpayne** [comment]
Wow, thanks @zmwangx!

**Comment by zmwangx** [comment]
No problem!
