### ISSUE TITLE
brew doctor should suggest `~/.profile` instead of `~/.bash_profile`

### ISSUE THREAD

**Issue by CircleOnCircles** [Homebrew/brew#7516]
> my os is windows 10 wsl2 ubuntu
# While 
installation of brew ask to put `eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)` into the `.profile`
# but
`brew doctor` suggest `~/.bash_profile`
```
Warning: umask is currently set to 000. Directories created by Homebrew cannot
be world-writable. This issue can be resolved by adding "umask 002" to
your ~/.bash_profile:
echo 'umask 002' >> ~/.bash_profile
```
# Causing
`~/.profile` is not read by bash(1), if `~/.bash_profile`  exists.

**Comment by sjackman** [comment]
Note that Ubuntu (and I assume WSL Ubuntu?) uses `~/.profile` by default, and not `~/.bash_profile`. If you create a `~/.bash_profile` from scratch, you effectively disable any configuration that the user has in `~/.profile`, including the system defaults, which can lead to unexpected behaviour.

**Comment by CircleOnCircles** [comment]
> Note that Ubuntu (and I assume WSL Ubuntu?) uses `~/.profile` by default, and not `~/.bash_profile`. If you create a `~/.bash_profile` from scratch, you effectively disable any configuration that the user has in `~/.profile`, including the system defaults, which can lead to unexpected behaviour.

Yes it is Ubuntu WSL
