### ISSUE TITLE
Brew install fails because all formula arguments are promoted to brew

### ISSUE THREAD

**Issue by abbaswasim** [Homebrew/brew#7517]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing `emacs-head` with `--with-cocoa`. Why? because I needed the cocoa version of emacs.

## What happened (include command output)

Calling `brew install emacs-head --debug --HEAD --with-cocoa --with-imagemagick --with-jansson` results in `Error: invalid option: --with-cocoa`. But actually if you put any argument after `--HEAD` it will be flagged as `invalid option`. I think the bug is introduced `20a1199375417ba49cf435dccb0104c0ad8fe8d0 : Refactor CLI to remove "unless args_parsed"`

<details>
  <summary>Command output</summary>
  <pre>

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Deleted Casks
hab

Usage: brew install [options] formula

Install formula. Additional options specific to formula may be appended to
the command.

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will then be run for
the installed formulae or, every 30 days, for all formulae.

    -d, --debug                      If brewing fails, open an interactive
                                     debugging session with access to IRB or a
                                     shell inside the temporary build directory.
        --env                        If std is passed, use the standard build
                                     environment instead of superenv. If super
                                     is passed, use superenv even if the formula
                                     specifies the standard build environment.
        --ignore-dependencies        An unsupported Homebrew development flag to
                                     skip installing any dependencies of any
                                     kind. If the dependencies are not already
                                     present, the formula will have issues. If
                                     you're not developing Homebrew, consider
                                     adjusting your PATH rather than using this
                                     flag.
        --only-dependencies          Install the dependencies with specified
                                     options but do not install the formula
                                     itself.
        --cc                         Attempt to compile using the specified
                                     compiler, which should be the name of the
                                     compiler's executable, e.g. gcc-7 for GCC
                                     7. In order to use LLVM's clang, specify
                                     llvm_clang. To use the Apple-provided
                                     clang, specify clang. This option will
                                     only accept compilers that are provided by
                                     Homebrew or bundled with macOS. Please do
                                     not file issues if you encounter errors
                                     while using this option.
    -s, --build-from-source          Compile formula from source even if a
                                     bottle is provided. Dependencies will still
                                     be installed from bottles if they are
                                     available.
        --force-bottle               Install from a bottle if it exists for the
                                     current or newest version of macOS, even if
                                     it would not normally be used for
                                     installation.
        --include-test               Install testing dependencies required to
                                     run brew test formula.
        --devel                      If formula defines it, install the
                                     development version.
        --HEAD                       If formula defines it, install the HEAD
                                     version, aka. master, trunk, unstable.
        --fetch-HEAD                 Fetch the upstream repository to detect if
                                     the HEAD installation of the formula is
                                     outdated. Otherwise, the repository's HEAD
                                     will only be checked for updates when a new
                                     stable or development version has been
                                     released.
        --keep-tmp                   Retain the temporary files created during
                                     installation.
        --build-bottle               Prepare the formula for eventual bottling
                                     during installation, skipping any
                                     post-install steps.
        --bottle-arch                Optimise bottles for the specified
                                     architecture rather than the oldest
                                     architecture supported by the version of
                                     macOS the bottles are built on.
    -f, --force                      Install without checking for previously
                                     installed keg-only or non-migrated
                                     versions.
    -v, --verbose                    Print the verification and postinstall
                                     steps.
        --display-times              Print install times for each formula at the
                                     end of the run.
    -i, --interactive                Download and patch formula, then open a
                                     shell. This allows the user to run
                                     ./configure --help and otherwise
                                     determine how to turn the software package
                                     into a Homebrew package.
    -g, --git                        Create a Git repository, useful for
                                     creating patches to the software.
    -h, --help                       Show this message.
Error: invalid option: --with-cocoa
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:160:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.

  </pre>
</details>

## What you expected to happen

Should be able to install `emacs-head` without any issues.

## Step-by-step reproduction instructions (by running `brew` commands)

Pick brew master and try to build emacs-head
```
brew tap daviderestivo/emacs-head
brew install emacs-head --HEAD --with-cocoa
```
You should get the error.
I have also reproduced it with a simple reproducer.

```
class Foo < Formula
  desc ""
  homepage ""
  url "https://example.com/foo-0.1.tar.gz"
  sha256 "85cc828a96735bdafcf29eb6291ca91bac846579bcef7308536e0c875d6c81d7"

  # depends_on "cmake" => :build

  option "with-ham", "Description of the option"
  option "without-spam", "Another description"

  if build.with? "ham"
    puts ">>> with-ham"
  else
    puts ">>> without-ham"
  end

  def install
    # ENV.deparallelize
    system "./configure", "--disable-debug",
                          "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--prefix=#{prefix}"
    # system "cmake", ".", *std_cmake_args
    system "make", "install"
  end

  test do
    system "false"
  end
end
```
Use the above formula as `foo.rb` and install using `brew install foo.rb --with-ham` 

You get the following error:

```
Usage: brew install [options] formula

Install formula. Additional options specific to formula may be appended to
the command.

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will then be run for
the installed formulae or, every 30 days, for all formulae.

    -d, --debug                      If brewing fails, open an interactive
                                     debugging session with access to IRB or a
                                     shell inside the temporary build directory.
        --env                        If std is passed, use the standard build
                                     environment instead of superenv. If super
                                     is passed, use superenv even if the formula
                                     specifies the standard build environment.
        --ignore-dependencies        An unsupported Homebrew development flag to
                                     skip installing any dependencies of any
                                     kind. If the dependencies are not already
                                     present, the formula will have issues. If
                                     you're not developing Homebrew, consider
                                     adjusting your PATH rather than using this
                                     flag.
        --only-dependencies          Install the dependencies with specified
                                     options but do not install the formula
                                     itself.
        --cc                         Attempt to compile using the specified
                                     compiler, which should be the name of the
                                     compiler's executable, e.g. gcc-7 for GCC
                                     7. In order to use LLVM's clang, specify
                                     llvm_clang. To use the Apple-provided
                                     clang, specify clang. This option will
                                     only accept compilers that are provided by
                                     Homebrew or bundled with macOS. Please do
                                     not file issues if you encounter errors
                                     while using this option.
    -s, --build-from-source          Compile formula from source even if a
                                     bottle is provided. Dependencies will still
                                     be installed from bottles if they are
                                     available.
        --force-bottle               Install from a bottle if it exists for the
                                     current or newest version of macOS, even if
                                     it would not normally be used for
                                     installation.
        --include-test               Install testing dependencies required to
                                     run brew test formula.
        --devel                      If formula defines it, install the
                                     development version.
        --HEAD                       If formula defines it, install the HEAD
                                     version, aka. master, trunk, unstable.
        --fetch-HEAD                 Fetch the upstream repository to detect if
                                     the HEAD installation of the formula is
                                     outdated. Otherwise, the repository's HEAD
                                     will only be checked for updates when a new
                                     stable or development version has been
                                     released.
        --keep-tmp                   Retain the temporary files created during
                                     installation.
        --build-bottle               Prepare the formula for eventual bottling
                                     during installation, skipping any
                                     post-install steps.
        --bottle-arch                Optimise bottles for the specified
                                     architecture rather than the oldest
                                     architecture supported by the version of
                                     macOS the bottles are built on.
    -f, --force                      Install without checking for previously
                                     installed keg-only or non-migrated
                                     versions.
    -v, --verbose                    Print the verification and postinstall
                                     steps.
        --display-times              Print install times for each formula at the
                                     end of the run.
    -i, --interactive                Download and patch formula, then open a
                                     shell. This allows the user to run
                                     ./configure --help and otherwise
                                     determine how to turn the software package
                                     into a Homebrew package.
    -g, --git                        Create a Git repository, useful for
                                     creating patches to the software.
    -h, --help                       Show this message.
Error: invalid option: --with-ham
```

## Output of `brew config` and `brew doctor` commands

Output of `brew update && brew doctor` together:

<pre>
Already up-to-date.
Your system is ready to brew.
</pre>

**Comment by varenc** [comment]
I can confirm I'm seeing this too.

This bug makes it impossible to use any of the options on the popular [homebrew-ffmpeg/ffmpeg](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg) tap.

It looks like this bug was introduced in #7509 ( paging @MikeMcQuaid  )

On homebrew master:
```
$ pwd
/usr/local/Homebrew

$ brew reinstall homebrew-ffmpeg/ffmpeg/ffmpeg  --with-zimg
Usage: brew reinstall [options] formula
...
Error: invalid option: --with-zimg

$ git checkout a5a5a1a83a4c5e9c07d7aee6a62ec2da529065d3    # (commit before PR 7509)
$ brew reinstall homebrew-ffmpeg/ffmpeg/ffmpeg  --with-zimg
==> Reinstalling homebrew-ffmpeg/ffmpeg/ffmpeg
...
```

**Comment by varenc** [comment]
Thanks for the speedy fix! 

I know that I and others really appreciate this functionality even though it's become a much more obscure use case since the removal of all formula options in homebrew-core.  Hopefully the maintenance burden isn't to disproportionate.  🙏

**Comment by MikeMcQuaid** [comment]
@varenc You're very welcome, sorry that we kept breaking it. As mentioned in https://github.com/Homebrew/brew/pull/7521: I've now added a (sadly slow but necessary) integration test that verifies when valid formula options are passed they are considered valid and they are handled correctly inside `install` to install things conditionally. I can verify that this works because my time boxed attempts to revert https://github.com/Homebrew/brew/pull/7499 were thwarted by the new test I added 😂/ 😭.

**Comment by abbaswasim** [comment]
@MikeMcQuaid thanks a lot for the quick fix. 

> it's become a much more obscure use case since the removal of all formula options in homebrew-core

What's the reason for this? Is there any write up on that so I can read. Just curious how are formulas suppose to provide options if this is being removed?

**Comment by MikeMcQuaid** [comment]
> What's the reason for this?

This was done several years ago at this point. Options still work in taps.
