### ISSUE TITLE
how to check on packages availability ?  Nexus 3 

### ISSUE THREAD

**Issue by mshahat** [Homebrew/brew#753]
I'd like to install Nexus 3.x and I can only see nexus 2.13 available ... 

How best can i get the newer version ? 

Thanks,

**Comment by MikeMcQuaid** [comment]
Someone will need to open a pull request. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!
