### ISSUE TITLE
support for brew install python --with-mkl

### ISSUE THREAD

**Issue by kirk86** [Homebrew/brew#754]
does brew provide support for install python/numpy with mkl support similar to openblas.
I know that one can install numpy by using `brew install numpy --with-blas`, but I'm not quite sure if we can do the same thing with mkl for instance:

`brew install python --with-mkl`
`brew install numpy --with-mkl`

since one can do the same with openblas

`brew install numpy --with-blas`

Also I would like to ask if we can issue the same command with just python

`brew install python --with-blas`?

**Comment by MikeMcQuaid** [comment]
We don't currently support this but if you're interested then we'll review and may consider including a PR to add this. CC @tdsmith in case he disagrees!

**Comment by kirk86** [comment]
@MikeMcQuaid certainly many would find that useful including myself. Thanks
