### ISSUE TITLE
resource downloads not happening

### ISSUE THREAD

**Issue by pahjbo** [Homebrew/brew#7546]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I want to make some changes to the git formula (to compensate for apple removing subversion - but that is a side issue) and I noticed that the man page resource is not being downloaded

## What happened (include command output)

a simpler example of this sort of problem is below with zlib - the test resource is not being downloaded

<details>
  <summary>Command output</summary>
  <pre>

  % rm -rf "$(brew --cache)"
% brew reinstall zlib
==> Downloading https://homebrew.bintray.com/bottles/zlib-1.2.11.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Reinstalling zlib 
==> Pouring zlib-1.2.11.catalina.bottle.tar.gz
==> Caveats
zlib is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find zlib you may need to set:
  export LDFLAGS="-L/usr/local/opt/zlib/lib"
  export CPPFLAGS="-I/usr/local/opt/zlib/include"

For pkg-config to find zlib you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/zlib/1.2.11: 12 files, 376.4KB
% brew test -d zlib
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
Testing zlib
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.16-28-gfa980e9\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.4\)\ curl/7.64.1 --retry 3 --location --silent --head --request GET https://zlib.net/zpipe.c
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:13:in `binread'
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/pharriso/Library/Caches/Homebrew/downloads/6b99a7b557e7d1bb38d5a9d3b9dd3f3a550dd320b53aac337cd40f8ce930e7e9--zpipe.c
1. raise
2. backtrace
3. shell
Choose an action: 1
==> Kept temporary files
Temporary files retained at /private/tmp/zlib-test-20200511-46477-1ip0dwp
Error: zlib: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/pharriso/Library/Caches/Homebrew/downloads/6b99a7b557e7d1bb38d5a9d3b9dd3f3a550dd320b53aac337cd40f8ce930e7e9--zpipe.c
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:13:in `binread'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:13:in `binread'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:13:in `magic_number'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/fossil.rb:14:in `can_extract?'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:99:in `block in detect'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:99:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:99:in `find'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:99:in `detect'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:58:in `stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:96:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:172:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:171:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:95:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:75:in `stage'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:83:in `block in install'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:80:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:80:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb:33:in `block in <class:Zlib>'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:32:in `block in test'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:94:in `debrew'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:32:in `test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1815:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1814:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:886:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1813:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2057:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2056:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1807:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'

  </pre>
</details>

## What you expected to happen

it looks to me as if the problem is that the generated curl command has --head option

## Step-by-step reproduction instructions (by running `brew` commands)

see above (command output)

## Output of `brew config` and `brew doctor` commands

<pre>
% brew config
HOMEBREW_VERSION: 2.2.16-28-gfa980e9
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa980e9c427b41db245a15c4bbcd510963b52169
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dfb8775da03dc2ff23b0a2f3200641f4f6846d09
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_INSTALL_CLEANUP: set
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.2, 11.0.6, 1.8.0_241, 1.8.0_212, 1.7.0_80
macOS: 10.15.4-x86_64
CLT: N/A
Xcode: 11.4.1
XQuartz: 2.7.11 => /opt/X11

brew doctor is bit ugly as I created a debug version of grpc

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libaddress_sorting.dylib
  /usr/local/lib/libgpr.dylib
  /usr/local/lib/libgrpc++.dylib
  /usr/local/lib/libgrpc++_alts.dylib
  /usr/local/lib/libgrpc++_error_details.dylib
  /usr/local/lib/libgrpc++_reflection.dylib
  /usr/local/lib/libgrpc++_unsecure.dylib
  /usr/local/lib/libgrpc.dylib
  /usr/local/lib/libgrpc_cronet.dylib
  /usr/local/lib/libgrpc_unsecure.dylib
  /usr/local/lib/libgrpcpp_channelz.dylib
  /usr/local/lib/libupb.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/grpc++/alarm.h
  /usr/local/include/grpc++/channel.h
  /usr/local/include/grpc++/client_context.h
  /usr/local/include/grpc++/completion_queue.h
  /usr/local/include/grpc++/create_channel.h
  /usr/local/include/grpc++/create_channel_posix.h
  /usr/local/include/grpc++/ext/health_check_service_server_builder_option.h
  /usr/local/include/grpc++/ext/proto_server_reflection_plugin.h
  /usr/local/include/grpc++/generic/async_generic_service.h
  /usr/local/include/grpc++/generic/generic_stub.h
  /usr/local/include/grpc++/grpc++.h
  /usr/local/include/grpc++/health_check_service_interface.h
  /usr/local/include/grpc++/impl/call.h
  /usr/local/include/grpc++/impl/channel_argument_option.h
  /usr/local/include/grpc++/impl/client_unary_call.h
  /usr/local/include/grpc++/impl/codegen/async_stream.h
  /usr/local/include/grpc++/impl/codegen/async_unary_call.h
  /usr/local/include/grpc++/impl/codegen/byte_buffer.h
  /usr/local/include/grpc++/impl/codegen/call.h
  /usr/local/include/grpc++/impl/codegen/call_hook.h
  /usr/local/include/grpc++/impl/codegen/channel_interface.h
  /usr/local/include/grpc++/impl/codegen/client_context.h
  /usr/local/include/grpc++/impl/codegen/client_unary_call.h
  /usr/local/include/grpc++/impl/codegen/completion_queue.h
  /usr/local/include/grpc++/impl/codegen/completion_queue_tag.h
  /usr/local/include/grpc++/impl/codegen/config.h
  /usr/local/include/grpc++/impl/codegen/config_protobuf.h
  /usr/local/include/grpc++/impl/codegen/core_codegen.h
  /usr/local/include/grpc++/impl/codegen/core_codegen_interface.h
  /usr/local/include/grpc++/impl/codegen/create_auth_context.h
  /usr/local/include/grpc++/impl/codegen/grpc_library.h
  /usr/local/include/grpc++/impl/codegen/metadata_map.h
  /usr/local/include/grpc++/impl/codegen/method_handler_impl.h
  /usr/local/include/grpc++/impl/codegen/proto_utils.h
  /usr/local/include/grpc++/impl/codegen/rpc_method.h
  /usr/local/include/grpc++/impl/codegen/rpc_service_method.h
  /usr/local/include/grpc++/impl/codegen/security/auth_context.h
  /usr/local/include/grpc++/impl/codegen/serialization_traits.h
  /usr/local/include/grpc++/impl/codegen/server_context.h
  /usr/local/include/grpc++/impl/codegen/server_interface.h
  /usr/local/include/grpc++/impl/codegen/service_type.h
  /usr/local/include/grpc++/impl/codegen/slice.h
  /usr/local/include/grpc++/impl/codegen/status.h
  /usr/local/include/grpc++/impl/codegen/status_code_enum.h
  /usr/local/include/grpc++/impl/codegen/string_ref.h
  /usr/local/include/grpc++/impl/codegen/stub_options.h
  /usr/local/include/grpc++/impl/codegen/sync_stream.h
  /usr/local/include/grpc++/impl/codegen/time.h
  /usr/local/include/grpc++/impl/grpc_library.h
  /usr/local/include/grpc++/impl/method_handler_impl.h
  /usr/local/include/grpc++/impl/rpc_method.h
  /usr/local/include/grpc++/impl/rpc_service_method.h
  /usr/local/include/grpc++/impl/serialization_traits.h
  /usr/local/include/grpc++/impl/server_builder_option.h
  /usr/local/include/grpc++/impl/server_builder_plugin.h
  /usr/local/include/grpc++/impl/server_initializer.h
  /usr/local/include/grpc++/impl/service_type.h
  /usr/local/include/grpc++/resource_quota.h
  /usr/local/include/grpc++/security/auth_context.h
  /usr/local/include/grpc++/security/auth_metadata_processor.h
  /usr/local/include/grpc++/security/credentials.h
  /usr/local/include/grpc++/security/server_credentials.h
  /usr/local/include/grpc++/server.h
  /usr/local/include/grpc++/server_builder.h
  /usr/local/include/grpc++/server_context.h
  /usr/local/include/grpc++/server_posix.h
  /usr/local/include/grpc++/support/async_stream.h
  /usr/local/include/grpc++/support/async_unary_call.h
  /usr/local/include/grpc++/support/byte_buffer.h
  /usr/local/include/grpc++/support/channel_arguments.h
  /usr/local/include/grpc++/support/config.h
  /usr/local/include/grpc++/support/error_details.h
  /usr/local/include/grpc++/support/slice.h
  /usr/local/include/grpc++/support/status.h
  /usr/local/include/grpc++/support/status_code_enum.h
  /usr/local/include/grpc++/support/string_ref.h
  /usr/local/include/grpc++/support/stub_options.h
  /usr/local/include/grpc++/support/sync_stream.h
  /usr/local/include/grpc++/support/time.h
  /usr/local/include/grpc/byte_buffer.h
  /usr/local/include/grpc/byte_buffer_reader.h
  /usr/local/include/grpc/census.h
  /usr/local/include/grpc/compression.h
  /usr/local/include/grpc/fork.h
  /usr/local/include/grpc/grpc.h
  /usr/local/include/grpc/grpc_cronet.h
  /usr/local/include/grpc/grpc_posix.h
  /usr/local/include/grpc/grpc_security.h
  /usr/local/include/grpc/grpc_security_constants.h
  /usr/local/include/grpc/impl/codegen/atm.h
  /usr/local/include/grpc/impl/codegen/atm_gcc_atomic.h
  /usr/local/include/grpc/impl/codegen/atm_gcc_sync.h
  /usr/local/include/grpc/impl/codegen/atm_windows.h
  /usr/local/include/grpc/impl/codegen/byte_buffer.h
  /usr/local/include/grpc/impl/codegen/byte_buffer_reader.h
  /usr/local/include/grpc/impl/codegen/compression_types.h
  /usr/local/include/grpc/impl/codegen/connectivity_state.h
  /usr/local/include/grpc/impl/codegen/fork.h
  /usr/local/include/grpc/impl/codegen/gpr_slice.h
  /usr/local/include/grpc/impl/codegen/gpr_types.h
  /usr/local/include/grpc/impl/codegen/grpc_types.h
  /usr/local/include/grpc/impl/codegen/log.h
  /usr/local/include/grpc/impl/codegen/port_platform.h
  /usr/local/include/grpc/impl/codegen/propagation_bits.h
  /usr/local/include/grpc/impl/codegen/slice.h
  /usr/local/include/grpc/impl/codegen/status.h
  /usr/local/include/grpc/impl/codegen/sync.h
  /usr/local/include/grpc/impl/codegen/sync_abseil.h
  /usr/local/include/grpc/impl/codegen/sync_custom.h
  /usr/local/include/grpc/impl/codegen/sync_generic.h
  /usr/local/include/grpc/impl/codegen/sync_posix.h
  /usr/local/include/grpc/impl/codegen/sync_windows.h
  /usr/local/include/grpc/load_reporting.h
  /usr/local/include/grpc/slice.h
  /usr/local/include/grpc/slice_buffer.h
  /usr/local/include/grpc/status.h
  /usr/local/include/grpc/support/alloc.h
  /usr/local/include/grpc/support/atm.h
  /usr/local/include/grpc/support/atm_gcc_atomic.h
  /usr/local/include/grpc/support/atm_gcc_sync.h
  /usr/local/include/grpc/support/atm_windows.h
  /usr/local/include/grpc/support/cpu.h
  /usr/local/include/grpc/support/log.h
  /usr/local/include/grpc/support/log_windows.h
  /usr/local/include/grpc/support/port_platform.h
  /usr/local/include/grpc/support/string_util.h
  /usr/local/include/grpc/support/sync.h
  /usr/local/include/grpc/support/sync_abseil.h
  /usr/local/include/grpc/support/sync_custom.h
  /usr/local/include/grpc/support/sync_generic.h
  /usr/local/include/grpc/support/sync_posix.h
  /usr/local/include/grpc/support/sync_windows.h
  /usr/local/include/grpc/support/thd_id.h
  /usr/local/include/grpc/support/time.h
  /usr/local/include/grpc/support/workaround_list.h
  /usr/local/include/grpcpp/alarm.h
  /usr/local/include/grpcpp/alarm_impl.h
  /usr/local/include/grpcpp/channel.h
  /usr/local/include/grpcpp/channel_impl.h
  /usr/local/include/grpcpp/client_context.h
  /usr/local/include/grpcpp/completion_queue.h
  /usr/local/include/grpcpp/completion_queue_impl.h
  /usr/local/include/grpcpp/create_channel.h
  /usr/local/include/grpcpp/create_channel_impl.h
  /usr/local/include/grpcpp/create_channel_posix.h
  /usr/local/include/grpcpp/create_channel_posix_impl.h
  /usr/local/include/grpcpp/ext/channelz_service_plugin.h
  /usr/local/include/grpcpp/ext/channelz_service_plugin_impl.h
  /usr/local/include/grpcpp/ext/health_check_service_server_builder_option.h
  /usr/local/include/grpcpp/ext/proto_server_reflection_plugin.h
  /usr/local/include/grpcpp/ext/proto_server_reflection_plugin_impl.h
  /usr/local/include/grpcpp/generic/async_generic_service.h
  /usr/local/include/grpcpp/generic/generic_stub.h
  /usr/local/include/grpcpp/generic/generic_stub_impl.h
  /usr/local/include/grpcpp/grpcpp.h
  /usr/local/include/grpcpp/health_check_service_interface.h
  /usr/local/include/grpcpp/health_check_service_interface_impl.h
  /usr/local/include/grpcpp/impl/call.h
  /usr/local/include/grpcpp/impl/channel_argument_option.h
  /usr/local/include/grpcpp/impl/client_unary_call.h
  /usr/local/include/grpcpp/impl/codegen/async_generic_service.h
  /usr/local/include/grpcpp/impl/codegen/async_stream.h
  /usr/local/include/grpcpp/impl/codegen/async_stream_impl.h
  /usr/local/include/grpcpp/impl/codegen/async_unary_call.h
  /usr/local/include/grpcpp/impl/codegen/async_unary_call_impl.h
  /usr/local/include/grpcpp/impl/codegen/byte_buffer.h
  /usr/local/include/grpcpp/impl/codegen/call.h
  /usr/local/include/grpcpp/impl/codegen/call_hook.h
  /usr/local/include/grpcpp/impl/codegen/call_op_set.h
  /usr/local/include/grpcpp/impl/codegen/call_op_set_interface.h
  /usr/local/include/grpcpp/impl/codegen/callback_common.h
  /usr/local/include/grpcpp/impl/codegen/channel_interface.h
  /usr/local/include/grpcpp/impl/codegen/client_callback.h
  /usr/local/include/grpcpp/impl/codegen/client_callback_impl.h
  /usr/local/include/grpcpp/impl/codegen/client_context.h
  /usr/local/include/grpcpp/impl/codegen/client_context_impl.h
  /usr/local/include/grpcpp/impl/codegen/client_interceptor.h
  /usr/local/include/grpcpp/impl/codegen/client_unary_call.h
  /usr/local/include/grpcpp/impl/codegen/completion_queue.h
  /usr/local/include/grpcpp/impl/codegen/completion_queue_impl.h
  /usr/local/include/grpcpp/impl/codegen/completion_queue_tag.h
  /usr/local/include/grpcpp/impl/codegen/config.h
  /usr/local/include/grpcpp/impl/codegen/config_protobuf.h
  /usr/local/include/grpcpp/impl/codegen/core_codegen.h
  /usr/local/include/grpcpp/impl/codegen/core_codegen_interface.h
  /usr/local/include/grpcpp/impl/codegen/create_auth_context.h
  /usr/local/include/grpcpp/impl/codegen/delegating_channel.h
  /usr/local/include/grpcpp/impl/codegen/grpc_library.h
  /usr/local/include/grpcpp/impl/codegen/intercepted_channel.h
  /usr/local/include/grpcpp/impl/codegen/interceptor.h
  /usr/local/include/grpcpp/impl/codegen/interceptor_common.h
  /usr/local/include/grpcpp/impl/codegen/message_allocator.h
  /usr/local/include/grpcpp/impl/codegen/metadata_map.h
  /usr/local/include/grpcpp/impl/codegen/method_handler.h
  /usr/local/include/grpcpp/impl/codegen/method_handler_impl.h
  /usr/local/include/grpcpp/impl/codegen/proto_buffer_reader.h
  /usr/local/include/grpcpp/impl/codegen/proto_buffer_writer.h
  /usr/local/include/grpcpp/impl/codegen/proto_utils.h
  /usr/local/include/grpcpp/impl/codegen/rpc_method.h
  /usr/local/include/grpcpp/impl/codegen/rpc_service_method.h
  /usr/local/include/grpcpp/impl/codegen/security/auth_context.h
  /usr/local/include/grpcpp/impl/codegen/serialization_traits.h
  /usr/local/include/grpcpp/impl/codegen/server_callback.h
  /usr/local/include/grpcpp/impl/codegen/server_callback_handlers.h
  /usr/local/include/grpcpp/impl/codegen/server_callback_impl.h
  /usr/local/include/grpcpp/impl/codegen/server_context.h
  /usr/local/include/grpcpp/impl/codegen/server_context_impl.h
  /usr/local/include/grpcpp/impl/codegen/server_interceptor.h
  /usr/local/include/grpcpp/impl/codegen/server_interface.h
  /usr/local/include/grpcpp/impl/codegen/service_type.h
  /usr/local/include/grpcpp/impl/codegen/slice.h
  /usr/local/include/grpcpp/impl/codegen/status.h
  /usr/local/include/grpcpp/impl/codegen/status_code_enum.h
  /usr/local/include/grpcpp/impl/codegen/string_ref.h
  /usr/local/include/grpcpp/impl/codegen/stub_options.h
  /usr/local/include/grpcpp/impl/codegen/sync.h
  /usr/local/include/grpcpp/impl/codegen/sync_stream.h
  /usr/local/include/grpcpp/impl/codegen/sync_stream_impl.h
  /usr/local/include/grpcpp/impl/codegen/time.h
  /usr/local/include/grpcpp/impl/grpc_library.h
  /usr/local/include/grpcpp/impl/method_handler_impl.h
  /usr/local/include/grpcpp/impl/rpc_method.h
  /usr/local/include/grpcpp/impl/rpc_service_method.h
  /usr/local/include/grpcpp/impl/serialization_traits.h
  /usr/local/include/grpcpp/impl/server_builder_option.h
  /usr/local/include/grpcpp/impl/server_builder_option_impl.h
  /usr/local/include/grpcpp/impl/server_builder_plugin.h
  /usr/local/include/grpcpp/impl/server_initializer.h
  /usr/local/include/grpcpp/impl/server_initializer_impl.h
  /usr/local/include/grpcpp/impl/service_type.h
  /usr/local/include/grpcpp/resource_quota.h
  /usr/local/include/grpcpp/resource_quota_impl.h
  /usr/local/include/grpcpp/security/alts_context.h
  /usr/local/include/grpcpp/security/alts_util.h
  /usr/local/include/grpcpp/security/auth_context.h
  /usr/local/include/grpcpp/security/auth_metadata_processor.h
  /usr/local/include/grpcpp/security/auth_metadata_processor_impl.h
  /usr/local/include/grpcpp/security/credentials.h
  /usr/local/include/grpcpp/security/credentials_impl.h
  /usr/local/include/grpcpp/security/server_credentials.h
  /usr/local/include/grpcpp/security/server_credentials_impl.h
  /usr/local/include/grpcpp/security/tls_credentials_options.h
  /usr/local/include/grpcpp/server.h
  /usr/local/include/grpcpp/server_builder.h
  /usr/local/include/grpcpp/server_builder_impl.h
  /usr/local/include/grpcpp/server_context.h
  /usr/local/include/grpcpp/server_impl.h
  /usr/local/include/grpcpp/server_posix.h
  /usr/local/include/grpcpp/server_posix_impl.h
  /usr/local/include/grpcpp/support/async_stream.h
  /usr/local/include/grpcpp/support/async_stream_impl.h
  /usr/local/include/grpcpp/support/async_unary_call.h
  /usr/local/include/grpcpp/support/async_unary_call_impl.h
  /usr/local/include/grpcpp/support/byte_buffer.h
  /usr/local/include/grpcpp/support/channel_arguments.h
  /usr/local/include/grpcpp/support/channel_arguments_impl.h
  /usr/local/include/grpcpp/support/client_callback.h
  /usr/local/include/grpcpp/support/client_callback_impl.h
  /usr/local/include/grpcpp/support/client_interceptor.h
  /usr/local/include/grpcpp/support/config.h
  /usr/local/include/grpcpp/support/error_details.h
  /usr/local/include/grpcpp/support/error_details_impl.h
  /usr/local/include/grpcpp/support/interceptor.h
  /usr/local/include/grpcpp/support/message_allocator.h
  /usr/local/include/grpcpp/support/proto_buffer_reader.h
  /usr/local/include/grpcpp/support/proto_buffer_writer.h
  /usr/local/include/grpcpp/support/server_callback.h
  /usr/local/include/grpcpp/support/server_callback_impl.h
  /usr/local/include/grpcpp/support/server_interceptor.h
  /usr/local/include/grpcpp/support/slice.h
  /usr/local/include/grpcpp/support/status.h
  /usr/local/include/grpcpp/support/status_code_enum.h
  /usr/local/include/grpcpp/support/string_ref.h
  /usr/local/include/grpcpp/support/stub_options.h
  /usr/local/include/grpcpp/support/sync_stream.h
  /usr/local/include/grpcpp/support/sync_stream_impl.h
  /usr/local/include/grpcpp/support/time.h
  /usr/local/include/grpcpp/support/validate_service_config.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/gpr.pc
  /usr/local/lib/pkgconfig/grpc++.pc
  /usr/local/lib/pkgconfig/grpc++_unsecure.pc
  /usr/local/lib/pkgconfig/grpc.pc
  /usr/local/lib/pkgconfig/grpc_unsecure.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libaddress_sorting.a
  /usr/local/lib/libgpr.a
  /usr/local/lib/libgrpc++.a
  /usr/local/lib/libgrpc++_alts.a
  /usr/local/lib/libgrpc++_error_details.a
  /usr/local/lib/libgrpc++_reflection.a
  /usr/local/lib/libgrpc++_unsecure.a
  /usr/local/lib/libgrpc.a
  /usr/local/lib/libgrpc_cronet.a
  /usr/local/lib/libgrpc_unsecure.a
  /usr/local/lib/libgrpcpp_channelz.a
  /usr/local/lib/libupb.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  minikube
  handbrake
  kubernetes-cli
  wireshark

</pre>

**Comment by okorz001** [comment]
I'm having the same problem trying to install `python@3.8` which uses resources to install setuptools, pip, and wheel.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/python@3.8.rb#L43-L56

As a workaround I am downloading the tarballs manually into the location homebrew expects it to be but this is quite tedious...

**Comment by okorz001** [comment]
https://github.com/Homebrew/brew/compare/2.2.16..master

Maybe an issue introduced here? https://github.com/Homebrew/brew/commit/2264c08cee95f0c829a6826d23c6285762e2d515

**Comment by stek29** [comment]
I'm experiencing this issue with custom formulas.

Minimal example:

```ruby
class TestResource < Formula
  url "https://github.com/Homebrew/brew/archive/2.2.16.zip"
  version "0"

  resource "test" do
    url "https://github.com/Homebrew/brew/archive/2.2.15.zip"
  end

  def install
    resource("test").stage do
        system "sh", "-c", "exit 1"
    end
  end
end
```

Output:
```
==> Installing test-resource
==> Downloading https://github.com/Homebrew/brew/archive/2.2.16.zip
==> Downloading from https://codeload.github.com/Homebrew/brew/zip/2.2.16
######################################################################## 100.0%
==> Downloading https://github.com/Homebrew/brew/archive/2.2.16.zip
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/662ccc7f4897e01299ff1a2b3ea4864921a2c74a755797910724d07506ad9344--brew-2.2.16.zip
Warning: Cannot verify integrity of 662ccc7f4897e01299ff1a2b3ea4864921a2c74a755797910724d07506ad9344--brew-2.2.16.zip
A checksum was not provided for this resource.
For your reference the SHA-256 is: f06fab0687ff66bfb7aeb806a154d5d48aad02b32c3e4bf6b79e39f96be848da
Error: Failure while executing; `unzip -qq -o /Users/user/Library/Caches/Homebrew/downloads/a452d5d342c6df296f69569226dd79bf1bd610b536ad343c06d67d830ed220e6--brew-2.2.15.zip -d /private/tmp/d20200512-59152-18e3grh` exited with 9. Here's the output:
unzip:  cannot find or open /Users/user/Library/Caches/Homebrew/downloads/a452d5d342c6df296f69569226dd79bf1bd610b536ad343c06d67d830ed220e6--brew-2.2.15.zip, /Users/user/Library/Caches/Homebrew/downloads/a452d5d342c6df296f69569226dd79bf1bd610b536ad343c06d67d830ed220e6--brew-2.2.15.zip.zip or /Users/user/Library/Caches/Homebrew/downloads/a452d5d342c6df296f69569226dd79bf1bd610b536ad343c06d67d830ed220e6--brew-2.2.15.zip.ZIP.
```

**Comment by stek29** [comment]
It's definitely 2264c08cee95f0c829a6826d23c6285762e2d515.

```
$ export HOMEBREW_UPDATE_PREINSTALL=0
$ git -C $(brew --repo) checkout 2264c08cee95f0c829a6826d23c6285762e2d515
HEAD is now at 2264c08cee95 Fetch formula resources before unlinking during upgrade.

$ brew install test-resource.rb # broken
❯ brew install test-resource.rb
==> Downloading https://github.com/Homebrew/brew/archive/2.2.15.zip
==> Downloading from https://codeload.github.com/Homebrew/brew/zip/2.2.15
######################################################################## 100.0%
==> Downloading https://github.com/Homebrew/brew/archive/2.2.15.zip
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/a452d5d342c6df296f69569226dd79bf1bd610b536ad343c06d67d830ed220e6--brew-2.2.15.zip
Warning: Cannot verify integrity of a452d5d342c6df296f69569226dd79bf1bd610b536ad343c06d67d830ed220e6--brew-2.2.15.zip
A checksum was not provided for this resource.
For your reference the SHA-256 is: 99e3ee6623c8a91aca7520135c4273547d00e9787bf5b1bf7a18074d0f1c5c63
Error: Failure while executing; `unzip -qq -o /Users/user/Library/Caches/Homebrew/downloads/662ccc7f4897e01299ff1a2b3ea4864921a2c74a755797910724d07506ad9344--brew-2.2.16.zip -d /private/tmp/d20200512-94250-qd0zn9` exited with 9. Here's the output:
unzip:  cannot find or open /Users/user/Library/Caches/Homebrew/downloads/662ccc7f4897e01299ff1a2b3ea4864921a2c74a755797910724d07506ad9344--brew-2.2.16.zip, /Users/user/Library/Caches/Homebrew/downloads/662ccc7f4897e01299ff1a2b3ea4864921a2c74a755797910724d07506ad9344--brew-2.2.16.zip.zip or /Users/user/Library/Caches/Homebrew/downloads/662ccc7f4897e01299ff1a2b3ea4864921a2c74a755797910724d07506ad9344--brew-2.2.16.zip.ZIP.

$ git -C $(brew --repo) checkout HEAD~1
Previous HEAD position was 2264c08cee95 Fetch formula resources before unlinking during upgrade.
HEAD is now at fc56a3d35473 Merge pull request #7536 from MikeMcQuaid/official-vendor-taps

$ brew install test-resource.rb # working
==> Downloading https://github.com/Homebrew/brew/archive/2.2.15.zip
==> Downloading from https://codeload.github.com/Homebrew/brew/zip/2.2.15
######################################################################## 100.0%
Warning: Cannot verify integrity of a452d5d342c6df296f69569226dd79bf1bd610b536ad343c06d67d830ed220e6--brew-2.2.15.zip
A checksum was not provided for this resource.
For your reference the SHA-256 is: 99e3ee6623c8a91aca7520135c4273547d00e9787bf5b1bf7a18074d0f1c5c63
==> Downloading https://github.com/Homebrew/brew/archive/2.2.16.zip
==> Downloading from https://codeload.github.com/Homebrew/brew/zip/2.2.16
######################################################################## 100.0%
==> sh -c exit 1
```

**Comment by stek29** [comment]
Workaround:

```sh
git -C $(brew --repo) checkout 2.2.16
export HOMEBREW_UPDATE_PREINSTALL=0
```

**Comment by Bo98** [comment]
Thanks all. I managed to reproduce and have just merged a fix that worked for me. Let me know if there's further issues.
