### ISSUE TITLE
bump-formula-pr fails when attempting to create PR

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/brew#755]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Failed command (bumping nodenv-each formula in nodenv/homebrew-nodenv tap):

```
HOMEBREW_DEVELOPER=true brew bump-formula-pr --dry-run --url=https://github.com/nodenv/nodenv-each/archive/v1.1.0.tar.gz --sha256=b398dabc5569f084b64b1daa377c5fd7ae508a166c5583f9eace00a6aeadf029 nodenv-each
```

Everything succeeded down (and including) the git-push and then:

```
Aborted: head branch is the same as base ("master")
(use `-h <branch>` to specify an explicit pull request head)
Error: Failure while executing: hub pull-request --browse -m nodenv-each\ 1.1.0

Created\ with\ `brew\ bump-formula-pr`.
```

Looking in the tap, the branch was set to use `origin/master` as upstream. The current command that creates the branch is `git checkout -b <branch> origin/master`. On my machine, this results in a local branch `<branch>` tracking `origin/master`. The push still works because the remote is specified explicitly (rather than defaulting to `@{upstream}`), but then the `hub pr` fails because it's trying to open a pr from `origin/master` to `origin/master`.

There are a couple ways to fix this:

1. Pass the `--no-track` option to `git checkout` so that the new branch doesn't set `origin/master` as the upstream
2. Explicitly pass `-h <remote>/<branch>` to `hub pull-request` so that hub uses the proper upstream as head instead of whatever the locally-configured upstream is.

I will shortly be opening a PR that addresses this by implementing option 1 above. Option 2 feels like treating the symptom rather than the cause.

**Comment by MikeMcQuaid** [comment]
> I will shortly be opening a PR that addresses this by implementing option 1 above. Option 2 feels like treating the symptom rather than the cause.

Cool, thanks. Just FYI I'm going to close this great write-up out just because if you're going to open a PR then we can defer to that PR rather than keeping this issue open. Thanks again!
