### ISSUE TITLE
[FR] Add --external-downloader  --external-downloader-args

### ISSUE THREAD

**Issue by NightMachinary** [Homebrew/brew#7564]
These flags allow users to use their own downloader, which can help increase speed and stability. I guess most contributors here enjoy high-speed internet, but in a lot of rural places and developed countries, internet connection is a lot more unstable/slow. Especially since the pandemic, this issue has become more prominent. The default downloader sometimes stalls on slow connections, and can't use split connections. With these flags added, we can use `aria2` like so:
`--external-downloader aria2c  --external-downloader-args '-c -j 3 -x 3 -s 3 -k 1M'`

This feature had been previously requested in the legacy repo, too, by someone else. It follows the Unix philosophy of allowing each tool to do one thing well and delegate tasks to other tools.

**Comment by NightMachinary** [comment]
@MikeMcQuaid Why close the issue without comment?

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE/bug.md#please-note-we-will-close-your-issue-without-comment-if-you-delete-do-not-read-or-do-not-fill-out-the-issue-checklist-below-and-provide-all-the-requested-information-if-you-repeatedly-fail-to-use-the-issue-template-we-will-block-you-from-ever-submitting-issues-to-homebrew-again

**Comment by NightMachinary** [comment]
@MikeMcQuaid I've updated the issue to follow the guidelines.

**Comment by MikeMcQuaid** [comment]
> `brew` used to not support resuming broken downloads, which was really bad, but aside from that, nothing seems to be considered.

Homebrew does support resuming broken downloads.

I'm not sure about this for a new PR. We'd consider it but it would need to handle all proxy settings etc. and be opt-in/optional. The relevant code would probably be in `download_strategy.rb` and I'd suggest it would be an environment variable like `HOMEBREW_DOWNLOADER` and `HOMEBREW_DOWNLOADER_ARGS` or something similar.
