### ISSUE TITLE
Casks: Include usage analytics in `brew cask info ...`, just like `brew info ...`

### ISSUE THREAD

**Issue by varenc** [Homebrew/brew#7566]
Extend `brew cask info ...` so that it returns usage analytics just like `brew info ...` already returns.

With this recent fix on formulae.brew.sh (https://github.com/Homebrew/formulae.brew.sh/issues/221),  this info can now be fetched with a single query.

For example, `brew cask info` could return information like this:
```
$ brew cask info dropbox
dropbox: latest
https://www.dropbox.com/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dropbox.rb
==> Name
Dropbox
==> Artifacts
Dropbox.app (App)
==> Analytics
install: 2,083 (30 days), 6,551 (90 days), 29,937 (365 days)
```

The analytics returned at the end is my proposed addition.  This just mirrors `brew info`

Usage analytics give users some insight into the popularity of a Cask.  This can information can inform their decision to install it or not.  

I believe all the reasoning that lead to usage analytics being included in `brew info ...` would apply to casks as well.

**Comment by MikeMcQuaid** [comment]
We'd accept PRs for this.

**Comment by tharun208** [comment]
I like to work on this

**Comment by varenc** [comment]
@tharun208 nice job again on implementing this!

Though now I realize the new analytics info is missing when you do `brew info <some cask>`

Of course, if you know you're looking up a cask you should do `brew cask info ...`, but if you accidentally do `brew info ...` and your usage isn't ambiguous, brew tries to be smart and helpfully. The output used to exactly match `brew cask info` but now it's missing the new analytics info!

Here's an example showing this.

```
$ brew info dropbox
Error: No available formula with the name "dropbox"
Found a cask named "dropbox" instead.

dropbox: latest
https://www.dropbox.com/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dropbox.rb
==> Name
Dropbox
==> Artifacts
Dropbox.app (App)

$ brew cask info dropbox
dropbox: latest
https://www.dropbox.com/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dropbox.rb
==> Name
Dropbox
==> Artifacts
Dropbox.app (App)
==> Analytics
install: 2,095 (30 days), 6,517 (90 days), 29,650 (365 days)
```

**Comment by tharun208** [comment]
@varenc, Yes, this has to be added and I raise a PR for this.
