### ISSUE TITLE
I can't seem to run anything associated with brew

### ISSUE THREAD

**Issue by kolharsam** [Homebrew/brew#7569]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I use iTerm and on that, on opening a new session or tab I get this error. The same error is also
prevalent when I run anything associated with brew apart from `brew update-reset`.

## What happened (include command output)

This is the error that I get:

<details>
  <summary>Command output</summary>
  <pre>
Traceback (most recent call last):
	13: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
	12: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	11: from /usr/local/Homebrew/Library/Homebrew/global.rb:36:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Homebrew/Library/Homebrew/config.rb:56:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:578:in `mkpath'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:200:in `each'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir': Permission denied @ dir_s_mkdir - /private/tmp (Errno::EACCES)
  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew` commands)

`brew`
`brew install XXX`
`brew doctor`

All of these commands are producing the same output that I have mentioned above

## Output of `brew config` and `brew doctor` commands

The same as the output I've listed above.

**Comment by MikeMcQuaid** [comment]
> Permission denied @ dir_s_mkdir - /private/tmp (Errno::EACCES)

This is an issue specific to your machine you'll need to figure out yourself (or on our Discourse).
