### ISSUE TITLE
Analytics for private taps (feature offer)

### ISSUE THREAD

**Issue by jphastings** [Homebrew/brew#7571]
# A detailed description of the offered feature

Currently Homebrew can push [anonymous analytics to a specific Google Analytics account](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/analytics.sh#L70) on [installs](https://github.com/Homebrew/brew/blob/1a7525ee2d31da6a878a95d81765c427c175958a/Library/Homebrew/formula_installer.rb#L287) and [build failures](https://github.com/Homebrew/brew/blob/1a7525ee2d31da6a878a95d81765c427c175958a/Library/Homebrew/brew.rb#L149).

Installs from private taps appear to be tracked too, but not [build failures](https://github.com/Homebrew/brew/blob/1a7525ee2d31da6a878a95d81765c427c175958a/Library/Homebrew/utils/analytics.rb#L67).

Would Homebrew consider approving a PR that allowed configuration within a tap to have analytics sent to a Google Analytics ID specified within that tap, that would be used instead of, or in addition to, the Homebrew Google Analytics ID? (eg. have a file called `analytics` in the root of the repo with contents like `UA-XXXXXXXX-1`)

# The motivation for the feature

I help manage a private Homebrew tap, and analytics would be very useful for [similar reasons](https://github.com/Homebrew/brew/blob/728189d3e946b900720eca98d48fc2c9bc309116/docs/Analytics.md#why) to homebrew-core: knowing where to effectively spent time and energy.

# How the feature would be relevant to at least 90% of Homebrew users

This feature would likely not impact 90% of Homebrew users; I'm proposing providing a PR for producing the feature so we can discuss the cost of maintaining it.

# What alternatives to the feature have been considered

Having users of my private tap override `HOMEBREW_ANALYTICS_ID` on their machines, so all Homebrew analytics is routed to a Google Analytics account I have access to.

- This would stop analytics from the core repos going to you (but for a trivially small number of users)
- This would still not share `build_error` events for my private tap

**Comment by MikeMcQuaid** [comment]
> Installs from private taps appear to be tracked too

They aren't actually: https://github.com/Homebrew/brew/blob/1a7525ee2d31da6a878a95d81765c427c175958a/Library/Homebrew/formula_installer.rb#L285-L290

I'm afraid I'm uneasy about any sort of expanded analytics for private taps. Even our gathering is heavily locked down (the majority of Homebrew maintainers have no access to Google Analytics and we all consume only the public data from formulae.brew.sh).

Given the tap formulae are essentially Ruby and able to make network calls at will: you could send analytics from `def install` with no changes or intervention required from us.

**Comment by jphastings** [comment]
This makes a lot of sense; I'll subclass `Formula` and use that for formula in this repo. Thanks for the careful response, I'll close ☺️🙇‍♂️
