### ISSUE TITLE
zsh completions are insecure in multiuser setup

### ISSUE THREAD

**Issue by spapanik** [Homebrew/brew#7573]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to start my terminal, as a different user than the one that installed brew

## What happened (include command output)

zsh completion complains about insecure directories and files. This happens because according to compinit:

> For security reasons compinit also checks if the completion system would use files not owned by root or by the current user, or files in directories that are world- or group-writable or that are not owned by root or by the current user

but brew installs them as the other user, who is the user who owns brew.

<details>
  <summary>Command output</summary>
  <pre>

  zsh compinit: insecure directories and files, run compaudit for list.
Ignore insecure directories and files and continue [y] or abort compinit [n]? 
compinit: initialization aborted

  </pre>
</details>

## What you expected to happen

I expect my zsh to start without issues

## Step-by-step reproduction instructions (by running `brew` commands)

* make zsh the default shell
* install brew
* create another user with zsh as his default shell

## Output of `brew config` and `brew doctor` commands

<pre>
***@*** $ brew doctor
Your system is ready to brew.
</pre>

<pre>
***@*** $ brew config                            
HOMEBREW_VERSION: 2.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0f5a52d85d3606e7600162a9d38936ab4b46f4f
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ac9bf6e3506ff2e6aa9c0cbcfc65f4f905d77a2d
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: N/A
Xcode: 11.4.1
</pre>

**Comment by MikeMcQuaid** [comment]
> brew installs them as the other user, who is the user who owns brew.

We only support running Homebrew as the owning user. We'll accept pull requests to address issues that come along from multiuser setups.

**Comment by cosmeg** [comment]
I'm seeing this on a system without any other users.

```sh
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? 
```

```sh
> compaudit
There are insecure directories:
/usr/local/share/zsh/site-functions
/usr/local/share/zsh
```
