### ISSUE TITLE
Non-admin installation

### ISSUE THREAD

**Issue by ak2022** [Homebrew/brew#7574]
# A detailed description of the proposed feature

Be able to install homebrew and packages as a non-sudo/admin user.

# The motivation for the feature

I'm using a managed pc, so I don't have access to the administrator account. However there are packages that it would be very useful for me to use (for example `hmmer`). I have gotten around this personally by using the location option in the installation script, however it was a non-trivial fix to work out the specifics of doing this.

This feature is already available for preexisting users of homebrew, given that homebrew is already installed, however the bootstrapping up to that point still requires Administrator access.

# How the feature would be relevant to at least 90% of Homebrew users

This would expand the use case of homebrew far further than it is currently to provide a high quality package manager to people who are using managed machines, but who can't easily go via their IT department (see the whole WFH situation currently). 

# What alternatives to the feature have been considered

This feature is already there for most of homebrew but it is not yet there for the inital installer, which still requires Administrator access.

# Aside regarding security

There may be concerns regarding non-techical users using homebrew to break work computers, however the prerequisite of actually getting homebrew installed (being able to use the terminal) should filter out the vast majority of them. Additionally if a non-technical user is able to install homebrew they will also with sufficient time be able to install whatever program that they want to install. Homebrew just makes it faster for them to do so.

**Comment by MikeMcQuaid** [comment]
You can use a different installation method: https://docs.brew.sh/Installation#untar-anywhere.

This won't be something we officially support as you cannot use binary packages in this configuration.
