### ISSUE TITLE
Recent builds fail to install on older CentOS

### ISSUE THREAD

**Issue by HariSekhon** [Homebrew/brew#7583]
## What you were trying to do (and why)

Install LinuxBrew on CentOS 6 using script:

https://raw.githubusercontent.com/Homebrew/install/master/install

This used to work until March 28th 2020 and is now failing my CI builds with what appears to be a bug failing to find `git` in the `$PATH` when it is clearly available at `/usr/bin/git`:

See these 2 scheduled builds, one succeeded and the next failed with this error (and all subsequent builds since):

succeeded:
https://github.com/HariSekhon/DevOps-Bash-tools/runs/597422743?check_suite_focus=true

next scheduled build failed:
https://github.com/HariSekhon/DevOps-Bash-tools/runs/599034715?check_suite_focus=true

## What happened (include command output)

Fails to detect `/usr/bin/git` which is in the `$PATH`:

<details>
  <summary>Command output</summary>
  <pre>

```
Error: Git must be installed and in your PATH!
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force

# which git
/usr/bin/git

# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
  </pre>
</details>

## What you expected to happen

Expected it to install on Linux

## Step-by-step reproduction instructions (by running `brew` commands)

Installed by this script, full details and line here:

https://github.com/HariSekhon/DevOps-Bash-tools/blob/master/setup/install_homebrew.sh#L31

## Output of `brew config` and `brew doctor` commands

<pre>
N/A
</pre>

**Comment by HariSekhon** [comment]
ping

**Comment by iMichka** [comment]
We don't support centos 6 anymore. It has glibc 2.12 and we require glibc 2.13: https://docs.brew.sh/Homebrew-on-Linux#requirements

**Comment by xuzhaofangxzf** [comment]
> We don't support centos 6 anymore. It has glibc 2.12 and we require glibc 2.13: https://docs.brew.sh/Homebrew-on-Linux#requirements

if I have not the sudo authority and my linux environment is CentOS6 with glibc = 2.12, but I installed the glibc manualy in other place such as /home/usr/libs/bin, how can i make thee homeBrew to find my own glibc in my path?

**Comment by iMichka** [comment]
You will need to read the source code and see how to make that work by yourself. We do not support this, even if you installed yet another glibc somewhere else.
