### ISSUE TITLE
Incorrect Shell Completion Docs for oh-my-zsh users

### ISSUE THREAD

**Issue by diminutivesloop** [Homebrew/brew#7584]
(Sorry for deleting parts of the issue template but it doesn’t seem designed for reporting documentation issues.)

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to enable shell completions for the Github CLI which I’ve installed via Homebrew. I added the Homebrew completion [snippet](https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh) to `.zshrc`. after the call to `oh-my-zsh.sh` and opened a new terminal but when I typed ‘gh’ and pressed <kbd>tab</kbd> I got file-path completion options instead of Github CLI completion options.

My solution was to add the following to `.zshrc` after `source $ZSH/oh-my-zsh.sh`:
```
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
    rm -f ~/.zcompdump; compinit
fi
```

Assuming this is not an issue specific to my machine the docs should be updated as follows:
1. Replace the snippet with the one I provided.
2. Specify that the snippet should be included *after* calling `oh-my-zsh.sh` rather than before.

I also reported a [related issue](https://github.com/cli/cli/issues/716) on the Github CLI because they link to the Homebrew Shell Completion docs.

## Output of `brew config` and `brew doctor` commands

<pre>
➜  ~ brew config
HOMEBREW_VERSION: 2.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0f5a52d85d3606e7600162a9d38936ab4b46f4f
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ed660bb2cebacacfc8d7f3569d9de1c049ea7792
Core tap last commit: 24 minutes ago
HOMEBREW_PREFIX: /usr/local/homebrew
HOMEBREW_REPOSITORY: /usr/local/homebrew
HOMEBREW_CELLAR: /usr/local/homebrew/Cellar
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: N/A
Xcode: 11.4.1 
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python
  gettext

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/homebrew/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/homebrew/sbin:$PATH"' >> ~/.zshrc

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install node
</pre>

**Comment by MikeMcQuaid** [comment]
This looks like it's pretty specific to your machine (or at least: your scripts). Could you submit a PR to edit the docs? It'll be easier to discuss that. Thanks!
