### ISSUE TITLE
Unable to install Homebrew (attempting to install it under /var/empty/)

### ISSUE THREAD

**Issue by gmyrianthous** [Homebrew/brew#7595]
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I want to install Homebrew

## What happened (include command output)

Using an account with admin rights, I executed: 

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

<details>
  <summary>Command output</summary>
  <pre>

```
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
Password:
==> /usr/bin/sudo /bin/mkdir -p /var/empty/Library/Caches/Homebrew
mkdir: /var/empty/Library/Caches/Homebrew: Operation not permitted
Failed during: /usr/bin/sudo /bin/mkdir -p /var/empty/Library/Caches/Homebrew
```
  </pre>
</details>

## What you expected to happen

Get homebrew installed on my machine

## Step-by-step reproduction instructions (by running `brew` commands)

Simply run 
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```
## Output of `brew config` and `brew doctor` commands

No output as I am unable to install homebrew

I don't quite understand why it attempts to place it under `/var/empty/` - I think this is the reason why it fails.

**Comment by Bo98** [comment]
Looks like your `$HOME` is `/var/empty`. This can happen for a few reasons, for example if you lose connection to your LDAP server or if you are in a chroot jail with ssh.

I imagine this would break other operations, like git pushing over SSH.
