### ISSUE TITLE
Usused variable crashes RuboCop in `brew style`

### ISSUE THREAD

**Issue by zub** [Homebrew/brew#7608]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Submit a formua to homebrew/homebrew-core

## What happened (include command output)

CI failed on `brew style`, with no usable error information. Traced the problem and tried rerunning `brew style` on my local machine, and it seems to be crashing if there is an unused variable somewhere in the formula. I managed to provoke a crash by something as simple as

```ruby
class CrashStyle < Formula
  def install
    some_variable = "crash"
  end
end
```

<details>
  <summary>Command output</summary>

```bash
brew style -d formula_name 
```
  <pre>
configuration from /usr/local/Homebrew/Library/.rubocop.yml
Inheriting configuration from /usr/local/Homebrew/Library/.rubocop_shared.yml
configuration from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-performance-1.5.2/config/default.yml
configuration from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-performance-1.5.2/config/default.yml
Default configuration from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/config/default.yml
configuration from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-rspec-1.39.0/config/default.yml
configuration from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-rspec-1.39.0/config/default.yml
Running parallel inspection
An error occurred while VariableForce cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crash-rubocop.rb.
uninitialized constant DidYouMean::SpellChecker
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/name_similarity.rb:18:in `find_similar_names'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/name_similarity.rb:9:in `find_similar_name'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:97:in `similar_name_message'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:77:in `message_specification'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:68:in `message_for_useless_assignment'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:52:in `block in check_for_unused_assignments'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:49:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:49:in `check_for_unused_assignments'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:42:in `block in after_leaving_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:41:in `each_value'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:41:in `after_leaving_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/force.rb:33:in `block in run_hook'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/force.rb:30:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/force.rb:30:in `run_hook'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:400:in `block (2 levels) in <class:VariableForce>'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force/variable_table.rb:17:in `invoke_hook'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force/variable_table.rb:36:in `pop_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:96:in `inspect_variables_in_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:296:in `process_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:86:in `process_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:103:in `block in process_children'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/ast/node.rb:187:in `block in each_child_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/ast/node.rb:184:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/ast/node.rb:184:in `each_child_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:100:in `process_children'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:95:in `inspect_variables_in_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:296:in `process_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:86:in `process_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:80:in `investigate'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:108:in `block (2 levels) in invoke_custom_processing'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:136:in `with_cop_error_handling'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:107:in `block in invoke_custom_processing'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:104:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:104:in `invoke_custom_processing'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:43:in `investigate'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/team.rb:124:in `investigate'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/team.rb:112:in `offenses'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:301:in `inspect_file'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:249:in `block in do_inspection_loop'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:281:in `block in iterate_until_no_changes'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:274:in `loop'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:274:in `iterate_until_no_changes'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:245:in `do_inspection_loop'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:124:in `block in file_offenses'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:148:in `file_offense_cache'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:122:in `file_offenses'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:509:in `call_with_index'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:471:in `process_incoming_jobs'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:453:in `block in worker'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:444:in `fork'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:444:in `worker'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:435:in `block in create_workers'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:434:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:434:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:434:in `create_workers'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:373:in `work_in_processes'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:277:in `map'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:227:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:59:in `warm_cache'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:38:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/command.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/environment.rb:17:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli.rb:65:in `run_command'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli.rb:72:in `execute_runners'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/exe/rubocop:13:in `block in <top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/exe/rubocop:12:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/rubocop:23:in `load'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/rubocop:23:in `<main>'
Scanning /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crash-rubocop.rb
An error occurred while VariableForce cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crash-rubocop.rb.
uninitialized constant DidYouMean::SpellChecker
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/name_similarity.rb:18:in `find_similar_names'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/name_similarity.rb:9:in `find_similar_name'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:97:in `similar_name_message'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:77:in `message_specification'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:68:in `message_for_useless_assignment'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:52:in `block in check_for_unused_assignments'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:49:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:49:in `check_for_unused_assignments'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:42:in `block in after_leaving_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:41:in `each_value'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:41:in `after_leaving_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/force.rb:33:in `block in run_hook'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/force.rb:30:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/force.rb:30:in `run_hook'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:400:in `block (2 levels) in <class:VariableForce>'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force/variable_table.rb:17:in `invoke_hook'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force/variable_table.rb:36:in `pop_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:96:in `inspect_variables_in_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:296:in `process_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:86:in `process_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:103:in `block in process_children'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/ast/node.rb:187:in `block in each_child_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/ast/node.rb:184:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/ast/node.rb:184:in `each_child_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:100:in `process_children'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:95:in `inspect_variables_in_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:296:in `process_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:86:in `process_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:80:in `investigate'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:108:in `block (2 levels) in invoke_custom_processing'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:136:in `with_cop_error_handling'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:107:in `block in invoke_custom_processing'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:104:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:104:in `invoke_custom_processing'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:43:in `investigate'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/team.rb:124:in `investigate'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/team.rb:112:in `offenses'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:301:in `inspect_file'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:249:in `block in do_inspection_loop'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:281:in `block in iterate_until_no_changes'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:274:in `loop'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:274:in `iterate_until_no_changes'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:245:in `do_inspection_loop'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:124:in `block in file_offenses'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:148:in `file_offense_cache'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:122:in `file_offenses'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:113:in `process_file'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:92:in `block in each_inspected_file'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:91:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:91:in `reduce'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:91:in `each_inspected_file'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:78:in `inspect_files'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:39:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/command.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/environment.rb:17:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli.rb:65:in `run_command'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli.rb:72:in `execute_runners'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/exe/rubocop:13:in `block in <top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/exe/rubocop:12:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/rubocop:23:in `load'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/rubocop:23:in `<main>'
== Formula/crash-rubocop.rb ==
C:  1:  1: FormulaAudit/Desc: Formula should have a desc (Description).
C:  1:  1: FormulaAudit/Homepage: Formula should have a homepage.
C:  2:  3: FormulaAudit/Miscellaneous: Define method install in the class body, not at the top-level

1 file inspected, 3 offenses detected

1 error occurred:
An error occurred while VariableForce cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crash-rubocop.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.83.0 (using Parser 2.7.1.2, running on ruby 2.6.3 x86_64-darwin13)
Finished in 0.9924678200040944 seconds
  </pre>
</details>

## What you expected to happen

A comprehensible style error message to appear

## Step-by-step reproduction instructions (by running `brew` commands)

```bash
brew style some_formula
```

## Output of `brew config` and `brew doctor` commands

```bash
brew config
```

<pre>
HOMEBREW_VERSION: 2.2.17-22-g98ad4fe
ORIGIN: https://github.com/Homebrew/brew
HEAD: 98ad4fe826579205891c059c5fbb5b10cad73619
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dbc60b9f9058a7be37a7bb7324c104ed84494147
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 13
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
</pre>

```bash
brew doctor
```

<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew/homebrew-core is not on the master branch.

Check out the master branch by running:
  git -C "$(brew --repo homebrew/core)" checkout master

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
  ?? Formula/crash-rubocop.rb

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish
</pre>

**Comment by MikeMcQuaid** [comment]
This is a bug in `rubocop`, could you submit it there? Thanks!

**Comment by Bo98** [comment]
@MikeMcQuaid Looks like we explicitly disable `did_you_mean`.

**Comment by MikeMcQuaid** [comment]
@Bo98 yes but I'd say `rubocop` shouldn't be crashing in that case.

**Comment by Bo98** [comment]
As in they should disable the cop if `did_you_mean` is not available?

**Comment by MikeMcQuaid** [comment]
@Bo98 based on my playing around with it the cop should be fine but they should disable the "did you mean" functionality (or require/include it).

**Comment by Bo98** [comment]
`require` would make sense, but does not appear to work with Homebrew's `setup_gem_environment` which blocks gems shipped with Ruby from being in the path.

**Comment by MikeMcQuaid** [comment]
If that fixed it on our end it'd be great.
