### ISSUE TITLE
Vault UI not available in this binary - solution from source 

### ISSUE THREAD

**Issue by abuxton** [Homebrew/brew#7614]
What you were trying to do (and why)
Use the Vault UI

vault server -dev
What happened (include command output)
http://127.0.0.1:8200/ui/

In the browser:
Vault UI is not available in this binary

What you expected to happen
A usable UI in dev mode

Step-by-step reproduction instructions (by running brew install commands)
brew install vault
vault server -dev
open http://127.0.0.1:8200/ui/

This was raised and discussed previously in https://github.com/Homebrew/homebrew-core/issues/46881 and allowed to become outdated

the solution is to update the brew to use `make dev-ui` to include the UI capability.  https://github.com/hashicorp/vault/blob/master/Makefile#L40

**Comment by MikeMcQuaid** [comment]
From that issue:

> We welcome a pull request to add it.

Please always fill out the issue template.

**Comment by abuxton** [comment]
I did, I just removed the speal from the front as unnecessary! do you want the note maintaining

**Comment by MikeMcQuaid** [comment]
We consider it always necessary.
