### ISSUE TITLE
Pygobject3: No module named 'gi'

### ISSUE THREAD

**Issue by muello** [Homebrew/brew#7616]
# Please note...

- [ X] ran `brew update` and can still reproduce the problem?
- [ X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install and run gajim as per [these instructions](https://dev.gajim.org/gajim/gajim/-/wikis/help/Gajim-on-macOS).

The issue seems to be the same as [reported on the gajim issues page](https://dev.gajim.org/gajim/gajim/-/issues/10068). The same thread contains an idea for [a workaround](https://dev.gajim.org/gajim/gajim/-/issues/10068#note_199190).

## What happened (include command output)

ModuleNotFoundError: No module named 'gi'

Unfold for details:

<details>
  <summary>Command output</summary>
  <pre>

user@Users-machine ~ % ./git/gajim/launch.py
No translations found
Dirs searched: [PosixPath('/usr/local/share'), PosixPath('/usr/share')]
Traceback (most recent call last):
  File "./git/gajim/launch.py", line 4, in <module>
    gajim.main()
  File "/Users/terence/git/gajim/gajim/gajim.py", line 123, in main
    _init_gui('GTK')
  File "/Users/terence/git/gajim/gajim/gajim.py", line 49, in _init_gui
    _init_gtk()
  File "/Users/terence/git/gajim/gajim/gajim.py", line 53, in _init_gtk
    import gi
ModuleNotFoundError: No module named 'gi'

  </pre>
</details>

## What you expected to happen

Gajim launches.

## Step-by-step reproduction instructions (by running `brew` commands)

1. Install python and dependencies for gajim (as per https://dev.gajim.org/gajim/gajim/-/wikis/help/Gajim-on-macOS)

brew install gettext python3 librsvg git
brew install gtk+3 pygobject3 adwaita-icon-theme libsoup
brew link --force gettext
pip3 install --upgrade nbxmpp pyOpenSSL pyasn1 pyobjc pillow idna precis-i18n certifi cssutils

2. Clone gajim and run it

git clone https://dev.gajim.org/gajim/gajim.git
cd gajim
git checkout gajim_1.1
./launch.py

## Output of `brew config` and `brew doctor` commands

<pre>
user@Users-machine ~ % brew config
HOMEBREW_VERSION: 2.2.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: ca5eac845dc11e991d7d8f8c85aebb82dd454f37
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 894388b4ac839d05adfc7f2d40af1de26f351c20
Core tap last commit: 68 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 11.4.1.0.1.1586360307
Xcode: 11.4.1 => /Volumes/Macintosh HD/Applications/Xcode.app/Contents/Developer

user@Users-machine ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Xcode is installed to a directory with a space in the name.
This will cause some formulae to fail to build.
</pre>

**Comment by MikeMcQuaid** [comment]
Report this to Gajim, not Homebrew.

**Comment by lovetox** [comment]
The problem seems to be that people who use python with brew have version 3.7 installed and `python` cmd points to that.

if one installs pygobject via brew, it installs it into python 3.8, so when python is started and points to 3.7 it does not find it.

I dont get why brew would install 2 different python versions, and how to get out of this again

**Comment by MikeMcQuaid** [comment]
> I dont get why brew would install 2 different python versions, and how to get out of this again

Read `brew info python@3.8` and set your PATH according to the version you want to use.
