### ISSUE TITLE
When building a formula, brew complains that an already-installed dependency's build-depends are not installable

### ISSUE THREAD

**Issue by jwatzman** [Homebrew/brew#7618]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install `ffmpeg` while using a non-standard brew prefix. This means that `ffmpeg` bottles are not usable, but bottles for its dependency `libbluray` are relocatable, available, and installed.

## What happened (include command output)

Even though `libbluray` is already installed from bottle and up-to-date, brew complains that its build-dependency on Java is not satisfied.

<details>
  <summary>Command output</summary>
  <pre>
$ brew install ffmpeg
libbluray: Java 1.8 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: An unsatisfied requirement failed this build.

$ brew info libbluray
libbluray: stable 1.2.0 (bottled), HEAD
Blu-Ray disc playback library for media players like VLC
https://www.videolan.org/developers/libbluray.html
/Users/josh/homebrew/Cellar/libbluray/1.2.0 (21 files, 1.5MB) *
  Poured from bottle on 2020-04-08 at 22:15:47
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libbluray.rb
==> Dependencies
Build: ant ✘, pkg-config ✔
Required: fontconfig ✔, freetype ✔
==> Requirements
Build: java = 1.8 ✘
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 85,620 (30 days), 224,203 (90 days), 701,708 (365 days)
install-on-request: 792 (30 days), 2,290 (90 days), 6,935 (365 days)
build-error: 0 (30 days)
  </pre>
</details>

## What you expected to happen

Brew should be able to install `ffmpeg` even though `libbluray`'s build dependency is not available, because `libbluray` is already installed (from bottle).

This used to work properly, and I bisected the issue to commit 89a0984d4206d5af25d2badfc3fe3a2bf0a9971f (PR #7613) from just a few hours ago; the issue does *not* occur on its parent, d254730e7859e27b5182046365844df9f34a7ba2.

I realise this is technically an unsupported configuration, and so understand if you want to just summarily close this issue. But since this is a regression, and a very recent one at that, which I was able to bisect, I suspected you might want to know about it. I would love to try to fix this and submit a PR myself, but given that I don't understand this area very well, let alone what that specific commit is doing, and I don't have much of a commit message or any automated tests to make sure I don't re-break whatever it was fixing, I'm afraid I'm likely to do more harm than good here :)

## Step-by-step reproduction instructions (by running `brew` commands)

`brew install ffmpeg` while using a non-standard prefix.

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.2.17-46-g89a0984
ORIGIN: git://github.com/Homebrew/brew
HEAD: 89a0984d4206d5af25d2badfc3fe3a2bf0a9971f
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d6369c8537e7de31f76a1a3d0e1b2589022ed6b1
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /Users/josh/homebrew
HOMEBREW_REPOSITORY: /Users/josh/homebrew
HOMEBREW_CELLAR: /Users/josh/homebrew/Cellar
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_VERBOSE: set
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /Users/josh/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  git://github.com/Homebrew/brew

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/Users/josh/homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  python@2

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.
</pre>

**Comment by Bo98** [comment]
> I don't understand this area very well, let alone what that specific commit is doing, and I don't have much of a commit message or any automated tests to make sure I don't re-break whatever it was fixing, I'm afraid I'm likely to do more harm than good here

Yeah, I can relate a bit. Requirements are a bit complex.

I can reproduce this issue and think I know what's happening.

**Comment by Bo98** [comment]
Let me know if #7620 fixes it for you.

**Comment by jwatzman** [comment]
Yeah, that fixes it -- fantastic, thanks so much!

**Comment by Bo98** [comment]
Thanks for testing it out!
