### ISSUE TITLE
Error: homebrew/dupes was deprecated. This tap is now empty as all its formulae were migrated.

### ISSUE THREAD

**Issue by nicholascloud** [Homebrew/brew#7628]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew update && brew upgrade

## What happened (include command output)

Error: homebrew/dupes was deprecated. This tap is now empty as all its formulae were migrated.

<details>
  <summary>Command output</summary>
  <pre>

  Error: homebrew/dupes was deprecated. This tap is now empty as all its formulae were migrated.

  </pre>
</details>

## What you expected to happen

Upgrade outdated packages.

## Step-by-step reproduction instructions (by running `brew` commands)

brew update && brew upgrade

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.2.17-74-g02733db
ORIGIN: https://github.com/Homebrew/brew
HEAD: 02733db7c74d5178dc29f92e2861ea22445604d1
Last commit: 23 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6678be6be53b3362d62c607c3eb49f572a103d8c
Core tap last commit: 13 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_252
macOS: 10.15.4-x86_64
CLT: N/A
Xcode: 11.5

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  python@2
  igbinary
Error: homebrew/dupes was deprecated. This tap is now empty as all its formulae were migrated.
</pre>

**Comment by MikeMcQuaid** [comment]
`brew untap homebrew/dupes`. I'll improve this error message.

**Comment by rbrown** [comment]
I'm getting a similar message, but brew untap home-brew/dupes it won't let me

```
$ brew untap homebrew/dupes
Error: No available tap homebrew/dupes.
```

I don't think the command line tools warning is relevant, but I will upgrade it just in case.

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Error: homebrew/dupes was deprecated. This tap is now empty as all its formulae were migrated.
```

**Comment by nicholascloud** [comment]
> I'm getting a similar message, but brew untap home-brew/dupes it won't let me

Yeah, I'm experiencing the same thing.

```
$ brew untap homebrew/dupes
Error: No available tap homebrew/dupes.
```

**Comment by MikeMcQuaid** [comment]
We're on this, it'll be closed as soon as the relevant PR passes CI.
