### ISSUE TITLE
Add option to `brew list` to see only user-installed packages.

### ISSUE THREAD

**Issue by websocket98765** [Homebrew/brew#7630]
# A detailed description of the proposed feature

I'd like to suggest adding an option to `brew list` to see only user-installed packages, excluding dependencies of user-installed packages to not clutter the list.

For example: When using NPM, it's possible to use `npm list --depth 0` to list only packages installed directly by the user (and not packages that are _dependencies_ for ones the user installed).  
```
❯ npm list -g --depth 0
├── node-gyp@6.1.0
├── npm@6.14.5
└── npm-check-updates@4.1.2
```

Another option would be to offer this via: `brew list --user`

# The motivation for the feature

This is very useful because it allows the user to see what packages they installed so they can delete those no longer needed.

However currently with `brew list`, it lists user installed packages _and their dependencies_, making it difficult to know if a package was one installed by the user long ago for a forgotten project and can be removed or if it's is a dependency of a package that the user still uses and needs to remain installed.

# How the feature would be relevant to at least 90% of Homebrew users

Helps users to see packages that they installed, and not have the list cluttered up by dependencies. 

# What alternatives to the feature have been considered

I tried `brew help list` and didn't see any alternatives.

**Comment by jonchang** [comment]
`brew leaves` should be able to do this: https://docs.brew.sh/Manpage#leaves

**Comment by websocket98765** [comment]
oh wow, never would have expected to find it there. Thank you!
