### ISSUE TITLE
Progress bar for brew cleanup

### ISSUE THREAD

**Issue by tbodt** [Homebrew/brew#7632]
# A detailed description of the proposed feature

I would like to see a progress bar showing the status of brew cleanup, similar to the progress bar that appears during downloading.

# The motivation for the feature

brew cleanup can take a while if a lot of formulae are installed. I'd like to be able to have some sense of how long it will take to finish.

# How the feature would be relevant to at least 90% of Homebrew users

brew cleanup automatically runs every 30 days, so this is relevant to every user who hasn't turned that off.

# What alternatives to the feature have been considered

Not sure what would be an alternative, other than not having this feature

**Comment by MikeMcQuaid** [comment]
We don't implement the progress bar, it comes from `curl`. We'd consider a PR to do this but it'll likely be pretty tricky.
