### ISSUE TITLE
Automatic plist caveat always shows "sudo"

### ISSUE THREAD

**Issue by FiloSottile** [Homebrew/brew#7641]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to provide a Formula that provides a service that can be managed with `brew service`. This service needs to run as the logged in user, not as root. This formula comes with a `plist` stanza.

https://github.com/FiloSottile/yubikey-agent/blob/master/HomebrewFormula/yubikey-agent.rb

## What happened (include command output)

On installation, a caveat is automatically shown, which is convenient. However, the suggested command includes `sudo` which starts the service as root, and causes the service to break (FiloSottile/yubikey-agent#16, FiloSottile/yubikey-agent#25).

```
To have launchd start yubikey-agent now and restart at startup:
  sudo brew services start yubikey-agent
```

`brew services start` without `sudo` works well.

<details>
  <summary>Command output</summary>
  <pre>

brew reinstall yubikey-agent
==> Downloading https://homebrew.bintray.com/bottles/go-1.14.3.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/e3/e3c4f834acba4e4db3f2b848860a040de1d8dec158545e8aaa3dd2f380c9c950?__gda__=exp=1590253514~hmac=23ef415fd0892b05a6003490bae373809d23cf5524c4474f1171b39210
######################################################################## 100.0%
==> Downloading https://github.com/FiloSottile/yubikey-agent/archive/v0.1.1.zip
Already downloaded: /Users/filippo/Library/Caches/Homebrew/downloads/53c03a96f64ebea6b983932b643ff0fa33b1390ea9e376033c0d6469850776f6--yubikey-agent-0.1.1.zip
==> Reinstalling yubikey-agent
==> Installing dependencies for yubikey-agent: go
==> Installing yubikey-agent dependency: go
==> Pouring go-1.14.3.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/go/1.14.3: 9,441 files, 424.6MB
==> Installing yubikey-agent
==> go build -ldflags -X main.Version=v0.1.1 /usr/local/Cellar/yubikey-agent/0.1.1/bin filippo.io/yubikey-agent
==> Caveats
To set up a new YubiKey, run this command:
  yubikey-agent -setup

To use this SSH agent, set this variable in your ~/.zshrc and/or ~/.bashrc:
  export SSH_AUTH_SOCK="/usr/local/var/run/yubikey-agent.sock"

To have launchd start yubikey-agent now and restart at startup:
  sudo brew services start yubikey-agent
==> Summary
🍺  /usr/local/Cellar/yubikey-agent/0.1.1: 6 files, 6.0MB, built in 21 seconds
==> Caveats
==> yubikey-agent
To set up a new YubiKey, run this command:
  yubikey-agent -setup

To use this SSH agent, set this variable in your ~/.zshrc and/or ~/.bashrc:
  export SSH_AUTH_SOCK="/usr/local/var/run/yubikey-agent.sock"

To have launchd start yubikey-agent now and restart at startup:
  sudo brew services start yubikey-agent

  </pre>
</details>

## What you expected to happen

I would like to be able to configure the caveat not to suggest using `sudo`, or be able to turn it off so I can replace it with my own text.

## Step-by-step reproduction instructions (by running `brew` commands)

```
brew tap filippo.io/yubikey-agent https://filippo.io/yubikey-agent
brew install yubikey-agent
```

## Output of `brew config` and `brew doctor` commands

<pre>
brew config
HOMEBREW_VERSION: 2.2.17-78-g9265ea0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9265ea0c505cd06773d89ccd26770f0d0683592c
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c40b0f25552c3d1a254ef61635ccff6a2dac286b
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 3600
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.eOllW3lTPU/org.macosforge.xquartz:0
HOMEBREW_EDITOR: code -w
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_141
macOS: 10.15.4-x86_64
CLT: 11.4.1.0.1.1586360307
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  gomod-ww
  gomod-gotests
  go-get-go1.13rc2
  gomod-dlv
  go-get-gvt
  gomod-staticcheck
  go-get-goimports
  go-get-go1.8.7
  go-get-go1.8
  go-get-gosumcheck
  go-get-benchstat
  go-get-git-cleanup
  go-get-go1.9.5
  go-get-vgo
  go-get-ct-submit
  go-get-go1.11.13
  go-get-go1.11rc1
  go-get-gostatus
  go-get-rmapi
  go-get-tcat
  go-get-vendorcheck
  go-get-go1.14rc1
  go-get-unconvert
  go-get-git-codereview
  go-get-git-codereview
  go-get-maintserve
  phantomjs
  go-get-go1.9rc2
  go-get-go1.12.14
  go-get-go1.11beta1
  go-get-gohack
  gomod-gotip
  go-get-go1.11rc2
  go-get-macos-roots-test
  go-get-pprof

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libykcs11.copy.dylib
</pre>

**Comment by MikeMcQuaid** [comment]
The `sudo` here is due to using `plist_options :startup => true`. If you remove that line it will start as the current user at user login rather than system startup. We do not provide a supported way to run at system startup as the current user/not using `sudo` in this situation. 

Does that explain the behaviour?

Thanks!

**Comment by FiloSottile** [comment]
> The `sudo` here is due to using `plist_options :startup => true`. If you remove that line it will start as the current user at user login rather than system startup. We do not provide a supported way to run at system startup as the current user/not using `sudo` in this situation.

Oh that makes sense, I misinterpreted `:startup` to mean "not just on request", but that's controlled by using `brew services run` instead. Fixed, thanks.

Maybe it should be an error to run a non-`:startup` service with `sudo`, or a `:startup` one without?

**Comment by MikeMcQuaid** [comment]
@FiloSottile Good idea, done in https://github.com/Homebrew/homebrew-services/pull/226

**Comment by MikeMcQuaid** [comment]
(@FiloSottile well, to be specific: not erroring as there is a use-case for that but instead printing warning noting if the user is doing what the formula doesn't recommend as it might not be what they expect).

**Comment by FiloSottile** [comment]
Awesome!
