### ISSUE TITLE
brew shellenv fails in tcsh

### ISSUE THREAD

**Issue by AprilArcus** [Homebrew/brew#7645]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

run `brew shellenv` in `tcsh` on macOS

## What happened (include command output)

An undefined variable error was emitted:

<details>
  <summary>Command output</summary>
  <pre>
MANPATH: Undefined variable.</pre>
</details>

## What you expected to happen

successful initialization of the `MANPATH` environment variable

## Step-by-step reproduction instructions (by running `brew` commands)

```
chsh -s /bin/tcsh
```

in a new terminal:

```
~> brew shellenv
```

## Output of `brew config` and `brew doctor` commands

```
~> brew config
HOMEBREW_VERSION: 2.2.17-103-ga56c305
ORIGIN: git@github.com:Homebrew/brew.git
HEAD: a56c305f87bb45dd3850c302d9ab4173df0adb23
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c981c315760ca691f69fce99f5d422dd3a6c302d
Core tap last commit: 4 days ago
HOMEBREW_PREFIX: /opt/brew
HOMEBREW_REPOSITORY: /opt/brew
HOMEBREW_CELLAR: /opt/brew/Cellar
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_221
macOS: 10.15.4-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: N/A
```

```
~> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  git@github.com:Homebrew/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/opt/brew" remote set-url origin https://github.com/Homebrew/brew

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.
```

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/pull/7646. In future if you're going to open a PR you can skip the issue. Thanks for the PR ❤️!
