### ISSUE TITLE
farmotive/k8s/kpoof 3.1.0 download results in HTTP 404

### ISSUE THREAD

**Issue by robspekschoor** [Homebrew/brew#7655]
I'm trying to update brew and it tries to download version 3.1.0 from farmotive/kpoof but fails in 404 error:

`> brew upgrade; brew cask upgrade;
==> Upgrading 1 outdated package:
farmotive/k8s/kpoof 3.0.0 -> 3.1.0
==> Upgrading farmotive/k8s/kpoof 3.0.0 -> 3.1.0 
==> Downloading https://github.com/farmotive/kpoof/archive/3.1.0.tar.gz
==> Downloading from https://codeload.github.com/farmotive/kpoof/tar.gz/3.1.0
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "kpoof"
Download failed: https://github.com/farmotive/kpoof/archive/3.1.0.tar.gz`

I would expect brew to download from:
https://github.com/farmotive/kpoof/archive/v3.1.0.tar.gz

Note the "v" in "v3.1.0.tar.gz" which is missing in the brew download

----------------------------------------------------------
- [ ] ran `brew update` and can still reproduce the problem?
Yes

- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
Yes

- [ ] ran `brew config` and `brew doctor` and included their output with your issue?
`> brew doctor 
Your system is ready to brew.`

`> brew config
HOMEBREW_VERSION: 2.2.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: ca5eac845dc11e991d7d8f8c85aebb82dd454f37
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5d836e80efab6ea53b4d5e94cc5fdf80ff987935
Core tap last commit: 46 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: N/A`

**Comment by Bo98** [comment]
This is a problem with the [farmotive/k8s tap](https://github.com/farmotive/homebrew-k8s) you have installed and should be reported there.
