### ISSUE TITLE
Why all the directories in PATH?

### ISSUE THREAD

**Issue by uberhacker** [Homebrew/brew#7664]
Why does brew install formulae/casks in so many different paths in `~/.bash_profile`?  Why not just install everything in `/usr/local` and not require the path to be updated?  Also, I'm confused when I see something like below:
```
formulae is keg-only, which means it was not symlinked into /usr/local,
because macOS provides formulae.dylib (but nothing else).

If you need to have formulae first in your PATH run:
  echo 'export PATH="/usr/local/opt/formulae/bin:$PATH"' >> /Users/ME/.bash_profile
```
Why not just go ahead and symlink so PATH doesn't need updated?

Another feature I would like to see is the ability for brew to install a cask without the keyword.  In other words, if I just type `brew install <cask>`, it would be smart enough to know I meant a cask and go ahead and install it without an unnecessary message that says I need the `cask` parameter.  Sorry for the rant.  Just things I noticed and suggested ways to make it more convenient for the end user.

**Comment by uberhacker** [comment]
And your point is?

**Comment by uberhacker** [comment]
Closing this without an explanation just shows a pretentious attitude.  This was meant to be a suggestion, not a rude comment.  Take it as a challenge.

**Comment by iMichka** [comment]
You did not fill out the issue template. We immediately close non-properly formatted issues to help triaging faster. Suggestions are better discussed at https://discourse.brew.sh, or by providing a pull request with the needed changes.

**Comment by uberhacker** [comment]
Thank you for the explanation @iMichka.  The project maintainer could have been more welcoming rather than closing.  Don't assume we should already know.

**Comment by iMichka** [comment]
I mean we try to guide you as much as possible with https://github.com/Homebrew/brew/issues/new/choose

At one point we even had a bot that was auto-closing issues that were not properly filled out. You must understand that sometimes we are flooded with issues/suggestions/discussions and are working on triaging stuff on our free time.

Regarding your suggestions: this is probably not on our top priority list, so only a pull request from someone would make stuff move forward.

**Comment by uberhacker** [comment]
I know all about trying to manage an OSS project on free time.  Would it make sense to redirect issues to Discourse?  I appreciate that you are actively trying to address things to keep the project maintainable.

**Comment by iMichka** [comment]
We have a discourse link here: https://github.com/Homebrew/brew/issues/new/choose

If you went through the "New issue for Feature Suggestion" page there is an issue template: 
https://github.com/Homebrew/brew/issues/new?template=feature.md

Not sure what we can do better than that :D

**Comment by uberhacker** [comment]
OK, I see the "issue".  I noticed the bug template has the notice at the top but the feature template does not.  Might want to add there too.  That is something you can do better. :)

**Comment by MikeMcQuaid** [comment]
As @iMichka said: you didn't read or fill out any of issue templates. If you can't be bothered to do that: I'm not sure why we should be bothered to respond. Jumping straight to calling me "pretentious" doesn't exactly encourage me to reply, either.

**Comment by MikeMcQuaid** [comment]
That said: genuinely thank you for the PR to improve this for the next person ❤️
