### ISSUE TITLE
brew postinstall node

### ISSUE THREAD

**Issue by dlekhak** [Homebrew/brew#7676]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Output of `brew config` and `brew doctor` commands

<pre>

</pre>

**Comment by dlekhak** [comment]
I was trying to brew upgrade node and it displayed Warning: The post-install step did not complete successfully. You can try again using `brew postinstall node'. However, when I retried with the suggested command, it shows the warning again and again.

**Comment by iMichka** [comment]
You did not fill out the issue template, and you did not post the error message.

This can be reopened once you provided all the needed information.
