### ISSUE TITLE
`brew list` seeming to run slow

### ISSUE THREAD

**Issue by bsolomon1124** [Homebrew/brew#7701]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

It takes about ~1.5 seconds to run a simple `brew list`.  Does this seem slow?  Are there any places I could investigate for causing that slowdown?  I do apologize that I can't provide more useful debugging information at this time, but I'm not sure where to find it.  

```bash
$ time brew list -1
ack
autoconf
autojump
automake
bash
bash-completion
bat
clang-format
cloc
colordiff
coreutils
cppcheck
diff-so-fancy
dos2unix
fd
findutils
gawk
gdbm
gettext
gmp
gnu-indent
gnu-sed
gnu-tar
gnutls
grep
hadolint
htop
httpie
jq
libevent
libffi
libidn2
libtasn1
libunistring
libyaml
mpfr
ncurses
nettle
nmap
oniguruma
openssl@1.1
p11-kit
pcre
pcre2
pkg-config
pre-commit
pygments
python@3.8
readline
ripgrep
scalafmt
shellcheck
shfmt
shyaml
sqlite
tree
unbound
unrar
watch
wget
xz
zlib

real	0m1.432s
user	0m0.397s
sys	0m0.988s

$ time brew info
62 kegs, 27,471 files, 331MB

real	0m2.681s
user	0m0.810s
sys	0m1.774s
```

## Step-by-step reproduction instructions (by running `brew` commands)

1. Buy a MacBook
2. `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`
3. Install stuff

## Output of `brew config` and `brew doctor` commands

```bash
$ brew config
HOMEBREW_VERSION: 2.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 77e09fc166f5fb7197b239d5e2727ddc0791c121
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 467e04e806d986ebc451420fcb4185a616605b8a
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: subl -w
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1
macOS: 10.15.5-x86_64
CLT: 1103.0.32.62
Xcode: N/A

$ xcode-select --version
xcode-select version 2373.

$ brew doctor
Your system is ready to brew.
```

**Comment by MikeMcQuaid** [comment]
> It takes about ~1.5 seconds to run a simple `brew list`. Does this seem slow?

This does not seem slow to me. `brew help` (which prints out a preconfigured string) takes 1s. Ruby (with the libraries we need) is slow to boot.

If you can speed this up: we'd welcome a pull request. `brew prof` may be useful.

**Comment by bsolomon1124** [comment]
@MikeMcQuaid roger, I'll look into that profiler.  And thank you otherwise for the treasure that is Homebrew!

**Comment by MikeMcQuaid** [comment]
You're welcome!
