### ISSUE TITLE
Feature request: use 'i' as 'install' alias

### ISSUE THREAD

**Issue by hugojerez** [Homebrew/brew#7729]
I suggest adding alias "i" to brew CLI

the "i" alias can be seen in various environments and languages, you can see it on `dpkg -i softwarename` , `npm i softwarename`, etc..

Today it sounds pretty irrelevant, but in some time when the new generations take the control they will reopen this thread

**Comment by claui** [comment]
Thanks @hugojerez for the feature request.

Until the new generation inevitably takes control, `brew i` is unlikely to be used by a majority and thus not worth the support burden. I’d recommend to implement `brew i` as an [external command](https://docs.brew.sh/External-Commands) in a tap if you really want it. If it ever gets popular, we’ll be happy to reconsider.

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template.
