### ISSUE TITLE
Error: No such file or directory - /usr/local/Cellar when running brew reinstall mono

### ISSUE THREAD

**Issue by MaurGi** [Homebrew/brew#774]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`.

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Installed brew today from scratch on OsX 10.11.6:
- /usr/bin/ruby -e "$(curl -fsSLhttps://raw.githubusercontent.com/Homebrew/install/master/install)"
- brew update
- brew reinstall mono

result:
==> Reinstalling mono
==> Downloading https://homebrew.bintray.com/bottles/mono-4.4.2.11.el_capitan.bo
Already downloaded: /Users/Mauro/Library/Caches/Homebrew/mono-4.4.2.11.el_capitan.bottle.tar.gz
Error: No such file or directory - /usr/local/Cellar
Warning: Bottle installation failed: building from source.
==> Installing dependencies for mono: autoconf, automake, pkg-config
==> Installing mono dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.el_capitan.bo
Already downloaded: /Users/Mauro/Library/Caches/Homebrew/autoconf-2.69.el_capitan.bottle.4.tar.gz
Error: No such file or directory - /usr/local/Cellar
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading https://ftpmirror.gnu.org/autoconf/autoconf-2.69.tar.gz
Already downloaded: /Users/Mauro/Library/Caches/Homebrew/autoconf-2.69.tar.gz
Error: Operation not permitted - /usr/local/Cellar

did run sudo chown on the /usr/local and then run again brew reinstall mono - same result.

**Comment by MikeMcQuaid** [comment]
> did run sudo chown on the /usr/local and then run again brew reinstall mono - same result.

What command exactly did you run? Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by MaurGi** [comment]
Before I run this:
sudo chown -R $(whoami) $(brew --prefix)

Now it got fixed with the following:
   44  brew update
   45  brew update
   46  brew doctor
   47  sudo chown -R $(whoami) /usr/local
   48  gcc
   49  xcode-select --install
   50  brew upgrade
   54  brew reinstall mono

closing the issue, thx
