### ISSUE TITLE
Brew files are large

### ISSUE THREAD

**Issue by RDIL** [Homebrew/brew#7741]
Hello!  

Recently, I have added Homebrew to a docker image of mine, and have realized that the homebrew install layer (only downloads Homebrew, *not any apps through brew*), and this layer is a huge (for docker images) ~300 MB.  

If possible, I think the install script should run something like `git gc --aggressive`, in order to conserve space.

Any feedback on this proposal is welcome 😃 

Thanks in advance!

**Comment by jonchang** [comment]
How much space does `git gc` save? I think we would consider a pull request for this but benchmarks that it does indeed save a lot of space would be necessary.

For tips on how to save space in Docker images see [this Discourse post](https://discourse.brew.sh/t/slimming-down-installation-for-docker-images/7890/7).

**Comment by jonchang** [comment]
Please always fill in the issue template.
