### ISSUE TITLE
brew cleanup cleans vendored portable-ruby prerequisite, next brew command verbosely resolves it again

### ISSUE THREAD

**Issue by sslavic** [Homebrew/brew#7743]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Use brewski alias to keep brew and installed formulas up-to-date

```
brewski='brew update && brew upgrade && brew cleanup; brew doctor'
```
See https://superuser.com/a/975878

## What happened (include command output)

Next `brew` command (e.g. `brew doctor` run as last in `brewski` alias or `brew config`) that gets to be run after running `brew cleanup`, includes an ugly error message:

<details>
  <summary>Command output</summary>
  <pre>
  Error: Failed to find usable Ruby 2.6!
  ==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_1.x86_64_linux.bottle.tar.gz
  Already downloaded: /home/foo/.cache/Homebrew/portable-ruby-2.6.3_1.x86_64_linux.bottle.tar.gz
  ==> Pouring portable-ruby-2.6.3_1.x86_64_linux.bottle.tar.gz
  </pre>
</details>

## What you expected to happen

- I expect brew cleanup not to cleanup brew prerequisites so they don't have to be resolved again.
- Alternatively or in addition to previous expectation, I expect follow up brew commands to silently resolve prerequisites, if not configured to run in verbose mode; I still expect brew commands to report actual errors in resolving prerequisites (e.g. if download fails).

## Step-by-step reproduction instructions (by running `brew` commands)

Assuming there's no other ruby on the system, and brew has been installed following official instructions, then run:

- `brew cleanup`
- `brew config`

## Output of `brew config` and `brew doctor` commands

<pre>
~ brew cleanup
~ brew config
Error: Failed to find usable Ruby 2.6!
==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/foo/.cache/Homebrew/portable-ruby-2.6.3_1.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.3_1.x86_64_linux.bottle.tar.gz
HOMEBREW_VERSION: 2.4.0-37-g797507f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 797507fa4c11242d55888fde3915b48dda6dcc95
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: ed8f870cb3f030e4d58013f4369a59810e724eb9
Core tap last commit: 17 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: atom --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_1/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.25.1 => /usr/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-7634-generic x86_64 GNU/Linux
OS: Pop!_OS 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
glibc: N/A
gcc: 5.5.0_7
xorg: 20170115_1
~ brew doctor
Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment]
@sslavic Can you paste the `brew cleanup` removal messaging too? I'm looking for e.g. `brew cleanup; brew config; brew cleanup; brew config` output? Thanks!

CC @maxim-belkin that the "Error" here probably shouldn't be output given it's able to download and use a portable ruby afterwards?

**Comment by sslavic** [comment]
@MikeMcQuaid thanks for looking into this! There's nothing in `brew cleanup` output, it just completes/exits successfully. 

If before running `brew cleanup` I run any other brew command, it would fetch portable ruby, which would be listed in
```
~ ls -lart /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/       
total 12
drwxr-xr-x 8 foo foo 4096 Apr 17  2019 2.6.3_1
drwxr-xr-x 4 foo foo 4096 Jun 11 10:34 ..
lrwxrwxrwx 1 foo foo    7 Jun 17 10:55 current -> 2.6.3_1
drwxr-xr-x 3 foo foo 4096 Jun 17 10:55 .
```

After running `brew cleanup` there's only left over broken symlink
```
~ ls -lart /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/
total 8
drwxr-xr-x 4 foo foo 4096 Jun 11 10:34 ..
lrwxrwxrwx 1 foo foo    7 Jun 17 10:55 current -> 2.6.3_1
drwxr-xr-x 2 foo foo 4096 Jun 17 10:56 .
```

Hope this helps.

**Comment by maxim-belkin** [comment]
@sslavic, could you please install portable ruby and then run `brew cleanup --dry-run`?
@MikeMcQuaid, I think the function at fault is `cleanup_portable_ruby` in `$(brew --repo)/Library/Homebrew/cleanup.rb`.

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid, I think the function at fault is `cleanup_portable_ruby` in `$(brew --repo)/Library/Homebrew/cleanup.rb`.

Yep, for sure. Could you try to adjust that so it uses the same logic as your `ruby.sh` changes? I almost wonder if a pure-bash, undocumented Homebrew command for something like `brew use-portable-ruby` which we can shell out to would be the right call here?

**Comment by maxim-belkin** [comment]
> I almost wonder if a pure-bash, undocumented Homebrew command for something like `brew use-portable-ruby` which we can shell out to would be the right call here?

It might be a good idea (this would allow us to avoid code repetition in two different places in two different languages (Bash/Ruby))  _if_ the cleanup logic has to be similar to that in `ruby.sh`. My feeling is that it shouldn't be really checking if Ruby is usable but that the link is broken or that  a more recent version of portable Ruby is already installed... After all, this is a "cleanup" step, not "verify Homebrew works" step.

**Comment by MikeMcQuaid** [comment]
> My feeling is that it shouldn't be really checking if Ruby is usable but that the link is broken or that a more recent version of portable Ruby is already installed... After all, this is a "cleanup" step, not "verify Homebrew works" step.

What we're doing primarily here is removing portable Ruby if it's no longer needed i.e. there's a system version that fulfils the same requirement.

**Comment by sslavic** [comment]
> could you please install portable ruby and then run brew cleanup --dry-run?

```
~ brew cleanup --dry-run
Would remove: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_1 (4,174 files, 31.4MB)
```

**Comment by sslavic** [comment]
> removing portable Ruby if it's no longer needed i.e. there's a system version that fulfills the same requirement

there is no other Ruby that I'm aware of on my machine - so `brew cleanup` shouldn't remove one previous runs of brew commands resolved?

**Comment by MikeMcQuaid** [comment]
@sslavic Would you mind running `brew cleanup; brew config; brew cleanup; brew config` and pasting the output here? We've just updated portable Ruby so I want to confirm it's not that that we're seeing here.

**Comment by sslavic** [comment]
@MikeMcQuaid I ran `brewski` first before noticing your message, so it downloaded the new version
```
~ brewski                            
==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
####################################################################################################################################################################################### 100.0%
==> Pouring portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
...
```

Output you requested is below. Empty lines are from `brew cleanup`, and error from `brew config`.
```
~ brew cleanup; brew config; brew cleanup; brew config                                                                          

Error: Failed to find usable Ruby 2.6!
==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
Already downloaded: /home/foo/.cache/Homebrew/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
HOMEBREW_VERSION: 2.4.0-53-g748af98
ORIGIN: https://github.com/Homebrew/brew
HEAD: 748af9897eba7f7c0c39a1207aebf1725716c3ba
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: bbfab7b870bdd3405dc27d05485a05059da989a1
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: atom --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.25.1 => /usr/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-7634-generic x86_64 GNU/Linux
OS: Pop!_OS 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
glibc: N/A
gcc: 5.5.0_7
xorg: 20170115_1

Error: Failed to find usable Ruby 2.6!
==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
Already downloaded: /home/foo/.cache/Homebrew/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
HOMEBREW_VERSION: 2.4.0-53-g748af98
ORIGIN: https://github.com/Homebrew/brew
HEAD: 748af9897eba7f7c0c39a1207aebf1725716c3ba
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: bbfab7b870bdd3405dc27d05485a05059da989a1
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: atom --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.25.1 => /usr/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-7634-generic x86_64 GNU/Linux
OS: Pop!_OS 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
glibc: N/A
gcc: 5.5.0_7
xorg: 20170115_1
```

**Comment by MikeMcQuaid** [comment]
Perfect, thanks @sslavic, yeh that definitely looks wrong.

**Comment by sslavic** [comment]
As of recently I don't see the error anymore. With every run of brewski portable-ruby keeps on being cleaned up and re-resolved, from cache, which is less of a problem than the error.

```bash
$ brewski
Already up-to-date.

==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
Already downloaded: /home/foo/.cache/Homebrew/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.8
```

**Comment by MikeMcQuaid** [comment]
Sorry, reopening. @sslavic can you output the full being installed/being cleaned-up/being installed again cycle? Can you reproduce outside `brewski`?

**Comment by sslavic** [comment]
As I reported in previous comment, there is no more error, just portable-ruby keeps being re-resolved, and it seems from local cache, so it's not as big deal:

```bash
~ brew cleanup; brew config; brew cleanup; brew config

==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
Already downloaded: /home/foo/.cache/Homebrew/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
HOMEBREW_VERSION: 2.4.7-66-ge1fdb81
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1fdb8117cac8113892ff2f40abdbe816dbfa08d
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 66e78e5d08c7e3edeebe4d8d68e85d1b88f80a40
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: atom --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.25.1 => /usr/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-7634-generic x86_64 GNU/Linux
OS: Pop!_OS 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
glibc: N/A
gcc: 5.5.0_7
xorg: 20170115_1

==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
Already downloaded: /home/foo/.cache/Homebrew/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
HOMEBREW_VERSION: 2.4.7-66-ge1fdb81
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1fdb8117cac8113892ff2f40abdbe816dbfa08d
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 66e78e5d08c7e3edeebe4d8d68e85d1b88f80a40
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: atom --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.25.1 => /usr/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-7634-generic x86_64 GNU/Linux
OS: Pop!_OS 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
glibc: N/A
gcc: 5.5.0_7
xorg: 20170115_1
```

**Comment by maxim-belkin** [comment]
@sslavic, what do you see when you do:

```
which -a ruby
/usr/bin/ruby -e "puts RUBY_VERSION"
```
?

**Comment by sslavic** [comment]
```bash
~ which -a ruby
/usr/bin/ruby
```

```bash
~ /usr/bin/ruby -e "puts RUBY_VERSION"
2.7.0
```

So https://github.com/Homebrew/brew/issues/7743#issuecomment-645333747 turned out not to be true.

That 2.7.0 Ruby was installed with system package manager. I've just removed it:

```bash
~ sudo apt remove ruby                                                                             
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  fonts-lato python-pkg-resources python-setuptools ruby-minitest ruby-net-telnet ruby-power-assert ruby-test-unit ruby-xmlrpc rubygems-integration
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  libruby2.7 linuxbrew-wrapper rake ruby ruby2.7
0 upgraded, 0 newly installed, 5 to remove and 0 not upgraded.
After this operation, 17.8 MB disk space will be freed.
Do you want to continue? [Y/n]  
(Reading database ... 283598 files and directories currently installed.)
Removing linuxbrew-wrapper (20180923-1) ...
Removing libruby2.7:amd64 (2.7.0-5ubuntu1.1) ...
Removing rake (13.0.1-4) ...
Removing ruby (1:2.7+1) ...
Removing ruby2.7 (2.7.0-5ubuntu1.1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9) ...
```

Now when I run:

```bash
~ brewski                             
Already up-to-date.
Your system is ready to brew.
```

```bash
~ brew cleanup; brew config
HOMEBREW_VERSION: 2.4.9-334-g984e926
ORIGIN: https://github.com/Homebrew/brew
HEAD: 984e926d19cbb8ab1eab474c115ab0ed825eda70
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 44b128435345a477f2c3f30f13b134946bb0ed4e
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: atom --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.25.1 => /usr/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-7634-generic x86_64 GNU/Linux
OS: Pop!_OS 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
glibc: N/A
gcc: 5.5.0_7
xorg: 20170115_1
```

```bash
~ brew cleanup --dry-run
```
