### ISSUE TITLE
Search for closed duplicate PRs as part of bump-formula-pr

### ISSUE THREAD

**Issue by dtrodrigues** [Homebrew/brew#7744]
# A detailed description of the proposed feature
Update `brew bump-formula-pr` to search for both open and closed PRs with titles that exactly match the auto-generated bump PR title (`formulaname new.version.number`). It currently only searches for open PRs with the formula name anywhere in the title.

# The motivation for the feature
This will prevent opening PRs that duplicate previous formula bump attempts that were closed for whatever reason. https://github.com/Homebrew/homebrew-core/pull/56197 is a case where this happened. With this proposed feature in place, a warning of a possibly duplicate PR would be printed, but it would allow a person to override with the `--force` flag that exists.

# How the feature would be relevant to at least 90% of Homebrew users
The feature would save time of contributors/maintainers as well as reduce strain on CI in cases where a person submitting a PR has no reason to believe it should succeed this time since they weren't aware it failed the previous time.

# What alternatives to the feature have been considered
* Users manually searching all PRs in GitHub prior to running `brew bump-formula-pr`.
* Allowing the PR submission to continue and let CI catch it again.

**Comment by zachauten** [comment]
I think this is a good idea! Looking at the PR now.

**Comment by dtrodrigues** [comment]
Corresponding PR has been merged.
