### ISSUE TITLE
Requirements Are Not Listed in `brew info` Output

### ISSUE THREAD

**Issue by Eitot** [Homebrew/brew#775]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug report

`brew info mpv` does not mention the Python3 [dependency](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb#L17). Is this intentional? `brew deps mpv` works correctly.

```
~ $ brew info mpv
mpv: stable 0.19.0, HEAD
Free, open source, and cross-platform media player
https://mpv.io
/Users/user/.homebrew/Cellar/mpv/0.19.0 (349 files, 32.9M) *
  Built from source on 2016-08-21 at 20:06:29 with: --with-bundle --without-jpeg --without-little-cms2 --without-lua
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb
==> Dependencies
Build: pkg-config ✔
Required: libass ✔, ffmpeg ✔
Recommended: jpeg ✘, little-cms2 ✘, lua ✘, youtube-dl ✔
Optional: libarchive ✘, libcaca ✘, libdvdread ✘, libdvdnav ✘, libbluray ✘, libaacs ✘, vapoursynth ✘, uchardet ✘
==> Options
--with-bundle
	Enable compilation of the .app bundle.
--with-libaacs
	Build with libaacs support
--with-libarchive
	Build with libarchive support
--with-libbluray
	Build with libbluray support
--with-libcaca
	Build with libcaca support
--with-libdvdnav
	Build with libdvdnav support
--with-libdvdread
	Build with libdvdread support
--with-uchardet
	Build with uchardet support
--with-vapoursynth
	Build with vapoursynth support
--with-x11
	Build with x11 support
--without-jpeg
	Build without jpeg support
--without-little-cms2
	Build without little-cms2 support
--without-lua
	Build without lua support
--without-youtube-dl
	Build without youtube-dl support
--HEAD
	Install HEAD version
==> Caveats
zsh completion has been installed to:
  /Users/user/.homebrew/share/zsh/site-functions

.app bundles were installed.
Run `brew linkapps mpv` to symlink these to /Applications.
```

**Comment by tdsmith** [comment]
cf https://github.com/Homebrew/brew/pull/770, https://github.com/Homebrew/homebrew-core/issues/4049

**Comment by apjanke** [comment]
Have a look at #1004 and let me know what you think.

```
$ brew info mpv
mpv: stable 0.20.0 (bottled), HEAD
...
==> Requirements
Required: python3 ✔, minimummacos = 10.8 ✔
Optional: x11 ✔
```

**Comment by zmwangx** [comment]
`minimummacos` isn't very recognizable, might need a better `display_s`.

**Comment by apjanke** [comment]
How about `MinMacOS = 10.8`? Or are you concerned about the numeric vs. names like `:yosemite`/`:el_cap`/etc?

**Comment by apjanke** [comment]
Probably, `MinimumMacOS` and `MaximumMacOS` are better, because they align with the DSL and are readable.

**Comment by zmwangx** [comment]
I think `minimum/min macOS version` and `maximum/max macOS version` would be clearer and look nicer, but no objection to `MinimumMacOS`.

> Or are you concerned about the numeric vs. names like :yosemite/:el_cap/etc?

Not at all. One day some people will forget what Lion is, just like I don't know what Panther is right now.

**Comment by apjanke** [comment]
Cool. I think the numbers work better too.

I lean toward the run-together `MinimumMacOS`/`MaximumMacOS` because they're closer to the DSL. Pushed an amended commit to the PR.

Shall we move this conversation over to the PR itself? https://github.com/Homebrew/brew/pull/1004

**Comment by zmwangx** [comment]
Sure.
