### ISSUE TITLE
After installing brew compinit complains about insecure directories.

### ISSUE THREAD

**Issue by igielskv** [Homebrew/brew#7750]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem? Yes
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? Yes
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I have just installed homebrew with command provided at https://github.com/homebrew/install#install-homebrew:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

## What happened (include command output)

Whenever new zsh Terminal window opens I get following complaint:

zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]?

When I try compaudit, I get following output:

<details>
  <summary>Command output</summary>
  <pre>

Last login: Tue Jun 16 13:17:33 on ttys001
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y%
manoli@Manolis-iMac ~ % compaudit
There are insecure directories:
/usr/local/share/zsh/site-functions
/usr/local/share/zsh

  </pre>
</details>

## What you expected to happen

I did not expect to have 'insecure directories' after homebrew installation.

## Step-by-step reproduction instructions (by running `brew` commands)

Just open new zsh Terminal window.

## Output of `brew config` and `brew doctor` commands

<pre>
manoli@Manolis-iMac ~ % brew config
HOMEBREW_VERSION: 2.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 28ed0801ed5807e176e62a3ba66e47ec867ec17d
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 68980d5a77004e713a83b1f6b558419fe026d352
Core tap last commit: 30 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.5

manoli@Manolis-iMac ~ % brew doctor 
Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment]
This is not an error with Homebrew but with ZSH. We'll accept a pull request to address this to Homebrew/install if such a fix is possible.

**Comment by alebcay** [comment]
[Docs already address this issue/behavior](https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh).
```
chmod go-w "$(brew --prefix)/share"
```

**Comment by igielskv** [comment]
> [Docs already address this issue/behavior](https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh).
> 
> ```
> chmod go-w "$(brew --prefix)/share"
> ```

Thanks for an advice, I believe this, what you propose should work as well.

Meanwhile I have uninstalled Homebrew with command from https://github.com/Homebrew/install#uninstall-homebrew

Than I reinstalled latest version of macOS (10.15.5 (19F101)), just to make sure I have everything in a mint condition I reinstalled Xcode with it's command line tools as well, and then I tried to install Homebrew again, now with command from https://brew.sh/ homepage, which I believe is exactly same as one from https://github.com/Homebrew/install#install-homebrew

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

Now script doesn't ask to change the group permissions on /usr/local/share directories, everything went through ok, and I don't have any complains from zsh and compinit or compaudit about insecure directories any more.

That's strange that I did everything exactly same as for the first time but now everything worked. I'm happy that the problem is gone, but unfortunately can't identify what was the cause of troubles for the first time.
