### ISSUE TITLE
Rewrite homebrew frontend/CLI in a compiled language

### ISSUE THREAD

**Issue by nhooyr** [Homebrew/brew#7755]
# The motivation for the feature

I think it'd be a good idea to switch the homebrew CLI to a compiled language like Go or Rust for a more snappy experience.

I have a brand new 13" MBP maxed out and when I run `time brew --version`, I get:

```zsh
~
$ /usr/bin/time brew --version
Homebrew 2.3.0-71-g3a7213c
Homebrew/homebrew-core (git revision aadffd; last commit 2020-06-09)
Homebrew/homebrew-cask (git revision 73058; last commit 2020-06-09)
        0.92 real         0.48 user         0.40 sys
```

It takes nearly 1 full second just to print the homebrew version.

This isn't a deal breaker but the latency makes `brew` feel clunky. It's also the reason why brew's cli completions are slow. See https://github.com/Homebrew/brew/issues/7749 and https://github.com/Homebrew/brew/issues/6106.

Fish/bash don't support completion caching so brew's subcommand completion will never be fast on them like it is on zsh with completion caching enabled.

Of course we can hard code subcommand completions and maybe work around these completion issues but in general, the CLI is slow.

i.e `brew help bump-formula-pr`, `brew cat code-server`, `brew commands`, `brew info go`, `brew list go` all take nearly one second for me, which given `--version` also takes nearly a second, leads me to believe the delay is nearly entirely due to the ruby interpreter starting up and loading all libraries.

If we were to rewrite the CLI in a compiled language, we would have no such latency and all CLI commands would become extremely responsive.

# Caveats

To be clear, I am not proposing we replace ruby formulas with a compiled language, we would still use ruby there to avoid massive churn. Only the CLI that users interact with would be written in a compiled language.

# How the feature would be relevant to at least 90% of Homebrew users

See https://danluu.com/term-latency/

Latency is **extremely** important to good UX. Few people may complain about it now but as soon as it's improved, it'll be extremely well received.

# What alternatives to the feature have been considered

I'm not aware of any other way we could speed up the CLI. Perhaps we could split it up better to avoid loading unnecessary libraries based on which command will run as ruby on its own takes only 100ms for me.

```
$ /usr/bin/time ruby -v -e 'puts "hello"'
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
hello
        0.09 real         0.06 user         0.02 sys
```

**Comment by jonchang** [comment]
If there are parts of Homebrew that are particularly slow, we would welcome pull requests that speed them up. Rewriting Homebrew in a different language is the responsibility of an entirely different project. It is not productive to open issues asking for a full rewrite (thousands of person-hours of work) of software that is maintained by volunteers, for free.

Finally, https://github.com/Homebrew/brew/issues/3901 says:

> Homebrew's performance is dominated by networking and housekeeping operations, not the Ruby runtime. Fetching large archives over the network and exploding them is a fundamental constraint on every package manager's performance. Ruby is slow, but Homebrew isn't slow because of it.

**Comment by MikeMcQuaid** [comment]
> It takes nearly 1 full second just to print the homebrew version.

The version is being parsed from the Git repository. It's not hardcoded.

As mentioned by @jonchang this would be such a vast, buggy undertaking to shave off relatively small amounts of time on the less commonly run commands.

**Comment by MikeMcQuaid** [comment]
Note for anyone following along: because of the joys of LLMs/AI we were able to try this out: https://github.com/Homebrew/brew-rs

It was faster for some things and slower for others.

Instead, we've put lots of time and energy into steadily increasing Homebrew's performance.

**Comment by MikeMcQuaid** [comment]
Also for a direct comparison to original post:
```console
$ /usr/bin/time brew --version
Homebrew 6.0.14-8-g935053a
Homebrew/homebrew-core (git revision 0e2ce7e9709; last commit 2026-07-30)
Homebrew/homebrew-cask (git revision 11bf565c222; last commit 2026-07-30)
        0.11 real         0.02 user         0.03 sys
```
