### ISSUE TITLE
Trying to use java binary in the current directory in macos

### ISSUE THREAD

**Issue by omuomugin** [Homebrew/brew#7768]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
After installed application that depends on java (or openjdk) and run those applications.

e.g
```
$ brew install bnd
$ bnd version 
```

## What happened (include command output)
Fail running the application since it will try to use `java` binary in the current directory.

<details>
  <summary>Command output</summary>
  <pre>

$ bnd version                                           

/usr/local/bin/bnd: line 2: /my/current/path/java  -jar /usr/local/Cellar/bnd/5.1.0/libexec/biz.aQute.bnd-5.1.0.jar: No such file or directory
/usr/local/bin/bnd: line 2: exec: /my/current/path/java  -jar /usr/local/Cellar/bnd/5.1.0/libexec/biz.aQute.bnd-5.1.0.jar: cannot execute: No such file or directory

  </pre>
</details>

## What you expected to happen
Use java which is set in `JAVA_HOME` or some other valid java (e.g `usr/bin/java`)

## Step-by-step reproduction instructions (by running `brew` commands)
1. use macos
2. run `brew install bnd`
3. run `bnd version` 
4. it will reproduce

## Output of `brew config` and `brew doctor` commands

<pre>

$ brew config

HOMEBREW_VERSION: 2.4.0-62-g11adee5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 11adee55ea172525dda0758560ac7c7ee6c55f23
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 160390c6f5b7fda3668fd8983c66dd908be3af82
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1, 1.8.0_252
macOS: 10.15.4-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.5

$ brew doctor

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  docker-compose

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f
</pre>

**Comment by omuomugin** [comment]
Still not seemed to fixed.
my brew config is this right now

```
$ brew config

HOMEBREW_VERSION: 2.4.0-69-g67c843b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 67c843b91ef272d5408fc2cb74ce8b39042ec1bf
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e598dd2bb3ac09a11242212e485418663a7ac6ad
Core tap last commit: 54 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1, 1.8.0_252
macOS: 10.15.4-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.5
```

**Comment by MikeMcQuaid** [comment]
@omuomugin Can you try to `brew reinstall bnd` and paste the `bnd version` errors if you're still seeing them? Thanks!

**Comment by omuomugin** [comment]
@MikeMcQuaid 
`brew reinstall bnd`

reinstalling worked for me!
Thanks for fixing it :+1:

**Comment by MikeMcQuaid** [comment]
@omuomugin you're welcome (but @bayandin fixed it)!

**Comment by omuomugin** [comment]
@bayandin Thanks for fixing !
