### ISSUE TITLE
Disambiguate Tty

### ISSUE THREAD

**Issue by AnastasiaSulyagina** [Homebrew/brew#777]
Now we have two different Ttys here: [homebrew's](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils.rb#L14) and [cask's](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/utils/tty.rb). They are quite different so it's probably worth discussing how to merge them. 
(Last time I accidentally applied Homebrew's Tty to Cask it seemed to be not very nice)

cc  @MikeMcQuaid @jawshooah @vitorgalvao @reitermarkus

**Comment by reitermarkus** [comment]
Off the top of my head I can only remember `ohai` being white for some reason instead of bold black.

**Comment by MikeMcQuaid** [comment]
I'm obviously biased but personally I think Cask should seek to use as much Homebrew code as possible and discuss global changes to both Homebrew and Cask when needed. There's going to be a lot of "duplicate but similar" code and I think it's worth being willing to make small changes to both projects now that they are one.

**Comment by AnastasiaSulyagina** [comment]
Theoretically it would be nice to remove cask's Tty since as I understood it's older version of Homebrew's one but I would want to know what in HB's Tty is not ok for cask to fix it so created this issue

**Comment by MikeMcQuaid** [comment]
@AnastasiaSulyagina I think (but @reitermarkus should feel free to contradict me) that it's worth making a PR to make Cask use only Homebrew's and then we can discuss/iterate on that.

**Comment by reitermarkus** [comment]
Well, I like the meta-programming going on in Cask's version. Maybe we could completely rewrite it to have something like `Tty.format("Lorem ipsum.", color: :blue, style: :underline)`.

**Comment by MikeMcQuaid** [comment]
I think the metaprogramming is harder to follow but I'm 👍 on rewriting once we have them combined. Doing both at once is a recipe for 💥

**Comment by AnastasiaSulyagina** [comment]
So first - just remove cask's version?

**Comment by MikeMcQuaid** [comment]
Aye, let's try that.

**Comment by apjanke** [comment]
This might be easier to understand if you view Cask's `Tty` as a pretty complete implementation of ANSI terminal control sequences for color and styling, and Homebrew's `Tty` as an implementation of the specific styling that `brew` uses, along with just the necessary control sequences for those. (And what Homebrew's `Tty` calls `escape` is actually an entire control sequence, bracketed by CSI (which starts with an `Esc` character) and `m`.)

Homebrew's approach has generally been "don't include implementation code that isn't actually used by our functionality. Which would agree with just expanding the Homebrew `Tty` to cover the specific uses in `brew cask`, removing Cask's `Tty`, and pulling in stuff from there as needed.

(FWIW, I find the table-style metaprogramming and fuller implementation in Cask's `Tty` easier to read, but there's a good deal more of it.)

**Comment by MikeMcQuaid** [comment]
> Homebrew's approach has generally been "don't include implementation code that isn't actually used by our functionality.

Yep 👍
