### ISSUE TITLE
`brew tests` requires Catalina or newer?

### ISSUE THREAD

**Issue by gromgit** [Homebrew/brew#7777]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was running through the SOP for submitting a formula PR, when `brew tests` failed in a surprising manner.

## What happened (include command output)

<details>
  <summary>Command output</summary>
<pre>
$ brew tests
Randomized with seed 43064
4 processes for 282 specs, ~ 70 specs per process
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F...............................*.........................******.***..*........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) brew cask list returns a list of installed Casks
     # Requires network connection.
     # ./test/cmd/cask_spec.rb:5

  2) GitHub::get_artifact_url fails to find artifacts that don't exist
     # Requires network connection.
     # ./test/utils/github_spec.rb:52

  3) GitHub::get_artifact_url fails to find a nonexistant workflow
     # Requires network connection.
     # ./test/utils/github_spec.rb:46

  4) GitHub::get_artifact_url gets an artifact link
     # Requires network connection.
     # ./test/utils/github_spec.rb:58

  5) GitHub::search_issues queries GitHub issues with the passed parameters
     # Requires network connection.
     # ./test/utils/github_spec.rb:35

  6) GitHub::search_code queries GitHub code with the passed parameters
     # Requires network connection.
     # ./test/utils/github_spec.rb:7

  7) Language::Java::java_home_env returns java_home path without version if version is not specified
     # Java not installed.
     # ./test/language/java_spec.rb:24

  8) Language::Java::java_home returns valid JAVA_HOME if version is specified
     # Java not installed.
     # ./test/language/java_spec.rb:7

  9) Language::Java::java_home returns valid JAVA_HOME if version is not specified
     # Java not installed.
     # ./test/language/java_spec.rb:12

  10) Language::Java::overridable_java_home_env returns java_home path without version if version is not specified
     # Java not installed.
     # ./test/language/java_spec.rb:36

  11) brew services allows controlling services
     # Requires network connection.
     # ./test/cmd/services_spec.rb:4

  12) brew pull fetches a patch from a GitHub commit or pull request and applies it
     # Requires network connection.
     # ./test/dev-cmd/pull_spec.rb:10

Finished in 3 minutes 4.6 seconds (files took 3.47 seconds to load)
588 examples, 0 failures, 12 pending

........................................................................................*..........................................................................................................................................................................................................................................................................................................................................................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) brew bundle check checks if a Brewfile's dependencies are satisfied
     # Requires network connection.
     # ./test/cmd/bundle_spec.rb:5

Finished in 3 minutes 32.6 seconds (files took 3.52 seconds to load)
931 examples, 0 failures, 1 pending

...........................................................................................................................................*..............................................*..............................................................................................................................................................................................................................................................................................................................................................*..

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Cask::Cmd::Info can run be run with a url twice and returns analytics
     # Requires network connection.
     # ./test/cask/cmd/info_spec.rb:143

  2) Utils#self.svn_remote_exists? when svn is available returns true when remote exists
     # Requires network connection.
     # ./test/utils/svn_spec.rb:35

Failures:

  1) Satisfy Dependencies and Requirements depends_on macos given a comparison does not raise an error
     Failure/Error: expect { install }.not_to raise_error

       expected no Exception, got #<Cask::CaskError: macOS Catalina or newer is required.> with backtrace:
         # ./cask/installer.rb:260:in `macos_dependencies'
         # ./cask/installer.rb:250:in `satisfy_dependencies'
         # ./cask/installer.rb:65:in `fetch'
         # ./cask/installer.rb:90:in `install'
         # ./test/cask/depends_on_spec.rb:7:in `block (2 levels) in <top (required)>'
         # ./test/cask/depends_on_spec.rb:46:in `block (5 levels) in <top (required)>'
         # ./test/cask/depends_on_spec.rb:46:in `block (4 levels) in <top (required)>'
         # ./test/support/helper/spec/shared_context/homebrew_cask.rb:52:in `block (2 levels) in <top (required)>'
         # ./test/spec_helper.rb:185:in `block (2 levels) in <top (required)>'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
     # ./test/cask/depends_on_spec.rb:46:in `block (4 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/homebrew_cask.rb:52:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:185:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

Finished in 4 minutes 59 seconds (files took 3.54 seconds to load)
648 examples, 1 failure, 2 pending

Failed examples:

rspec ./test/cask/depends_on_spec.rb:45 # Satisfy Dependencies and Requirements depends_on macos given a comparison does not raise an error

.....*.....................................***

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Utils::git_remote_exists? when git is available returns true when git remote exists
     # Requires network connection.
     # ./test/utils/git_spec.rb:133

  2) brew search falls back to a GitHub tap search when no formula is found
     # Requires network connection.
     # ./test/cmd/search_spec.rb:11

  3) Bintray::file_published? fails on a non-existant file
     # Requires network connection.
     # ./test/bintray_spec.rb:13

  4) Bintray::file_published? detects a published file
     # Requires network connection.
     # ./test/bintray_spec.rb:8

  5) Bintray::package_exists? detects a package
     # Requires network connection.
     # ./test/bintray_spec.rb:20

Finished in 5 minutes 46 seconds (files took 3.59 seconds to load)
602 examples, 0 failures, 5 pending

Tests Failed

2769 examples, 1 failure, 20 pendings

Took 349 seconds (5:49)
</pre>
</details>

For clarity, the only test failure is this:
```
Failures:

  1) Satisfy Dependencies and Requirements depends_on macos given a comparison does not raise an error
     Failure/Error: expect { install }.not_to raise_error

       expected no Exception, got #<Cask::CaskError: macOS Catalina or newer is required.> with backtrace:
         # ./cask/installer.rb:260:in `macos_dependencies'
         # ./cask/installer.rb:250:in `satisfy_dependencies'
         # ./cask/installer.rb:65:in `fetch'
         # ./cask/installer.rb:90:in `install'
         # ./test/cask/depends_on_spec.rb:7:in `block (2 levels) in <top (required)>'
         # ./test/cask/depends_on_spec.rb:46:in `block (5 levels) in <top (required)>'
         # ./test/cask/depends_on_spec.rb:46:in `block (4 levels) in <top (required)>'
         # ./test/support/helper/spec/shared_context/homebrew_cask.rb:52:in `block (2 levels) in <top (required)>'
         # ./test/spec_helper.rb:185:in `block (2 levels) in <top (required)>'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
     # ./test/cask/depends_on_spec.rb:46:in `block (4 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/homebrew_cask.rb:52:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:185:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```
## What you expected to happen

I was expecting `brew tests` to not fail an OS version check when I'm running non-deprecated Mojave.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew tests`

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.4.0-87-g8c21e8b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8c21e8b2dbda1cf1ecdbad9b76acdf10ca14a39e
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9097beb3f26aa4be0130f3f881db144cf60c2bb5
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.14zxDoeafl/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 11.0 build 1100
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew/homebrew-core is not on the master branch.

Check out the master branch by running:
  git -C "$(brew --repo homebrew/core)" checkout master

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  rtv

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libpgtcl.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  moreutils
  libzip

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
   M Formula/libtcod.rb
</pre>
The first and last `brew doctor` warnings are related to the formula PR I'll be submitting, once I sort this issue out.

**Comment by miccal** [comment]
I also have a question about `brew tests`, hope it is ok to ask it here @gromgit: roughly how long should `brew tests` take to complete -- I am not sure if it is hanging on my machine, or if it just takes a while?

Thanks.

**Comment by gromgit** [comment]
@miccal The age-old answer applies: _it depends on your environment_. In my case, as you can see at the end of my command output, it took 5m46s to fail out after 2700+ checks on a mid-2013 MacBook Air with 8GB RAM running Mojave. The first run downloaded a whole slew of gems, and therefore took longer.

Anyway, it if looks like nothing's happening after a minute or so, it's a good bet something's hung up.

**Comment by miccal** [comment]
Thanks @gromgit, so an hour is definitely indicating a problem then :)

Would you know how I could narrow down the problem to find which particular `spec` is looping?

**Comment by miccal** [comment]
https://github.com/Homebrew/brew/issues/7781

Sorry to bother you in your own issue @gromgit.

**Comment by gromgit** [comment]
FWIW, I did a full Homebrew uninstall and (re)install, followed _immediately_ by `brew tests`, and the same failure popped up:
<details>
<summary>`brew config` output after reinstallation</summary>
<pre>
HOMEBREW_VERSION: 2.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 28ed0801ed5807e176e62a3ba66e47ec867ec17d
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 991f0866d231d9ee9851d5e2c0a0824912a63b90
Core tap last commit: 57 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.14zxDoeafl/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_1/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 14.0.1
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11
</pre>
</details>
<details>
<summary>`brew doctor` output after reinstallation</summary>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libpgtcl.h

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/bin/kitty
  /usr/local/etc/bash_completion.d/brew-services
  /usr/local/share/zsh/site-functions/_brew_services
</pre>
</details>
<details>
<summary>`brew tests` output after reinstallation</summary>
<pre>
Fetching gem metadata from https://rubygems.org/.........
Fetching thread_safe 0.3.6
Fetching concurrent-ruby 1.1.6
Fetching minitest 5.14.1
Installing minitest 5.14.1
Installing thread_safe 0.3.6
Installing concurrent-ruby 1.1.6
Fetching zeitwerk 2.3.0
Installing zeitwerk 2.3.0
Fetching ast 2.4.1
Using bundler 1.17.2
Fetching byebug 11.1.3
Installing ast 2.4.1
Installing byebug 11.1.3 with native extensions
Fetching connection_pool 2.2.3
Installing connection_pool 2.2.3
Fetching json 2.3.0
Installing json 2.3.0 with native extensions
Fetching docile 1.3.2
Installing docile 1.3.2
Fetching simplecov-html 0.10.2
Installing simplecov-html 0.10.2
Using sync 0.5.0
Fetching thor 1.0.1
Installing thor 1.0.1
Fetching diff-lcs 1.3
Installing diff-lcs 1.3
Fetching unf_ext 0.0.7.7
Installing unf_ext 0.0.7.7 with native extensions
Fetching hpricot 0.8.6
Installing hpricot 0.8.6 with native extensions
Fetching mime-types-data 3.2020.0512
Installing mime-types-data 3.2020.0512
Fetching net-http-digest_auth 1.4.1
Installing net-http-digest_auth 1.4.1
Fetching mini_portile2 2.4.0
Installing mini_portile2 2.4.0
Fetching ntlm-http 0.1.1
Installing ntlm-http 0.1.1
Fetching webrobots 0.1.2
Installing webrobots 0.1.2
Fetching mustache 1.1.1
Installing mustache 1.1.1
Fetching parallel 1.19.1
Installing parallel 1.19.1
Fetching plist 3.5.0
Installing plist 3.5.0
Fetching rainbow 3.0.0
Installing rainbow 3.0.0
Fetching rdiscount 2.2.0.1
Installing rdiscount 2.2.0.1 with native extensions
Fetching regexp_parser 1.7.1
Installing regexp_parser 1.7.1
Fetching rexml 3.2.4
Installing rexml 3.2.4
Fetching rspec-support 3.9.3
Installing rspec-support 3.9.3
Fetching ruby-progressbar 1.10.1
Installing ruby-progressbar 1.10.1
Fetching unicode-display_width 1.7.0
Installing unicode-display_width 1.7.0
Fetching ruby-macho 2.2.0
Installing ruby-macho 2.2.0
Fetching tzinfo 1.2.7
Installing tzinfo 1.2.7
Fetching parser 2.7.1.3
Installing parser 2.7.1.3
Fetching net-http-persistent 4.0.0
Installing net-http-persistent 4.0.0
Fetching i18n 1.8.3
Installing i18n 1.8.3
Fetching tins 1.25.0
Installing tins 1.25.0
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching mime-types 3.3.1
Installing mime-types 3.3.1
Fetching nokogiri 1.10.9
Installing nokogiri 1.10.9 with native extensions
Fetching parallel_tests 3.0.0
Installing parallel_tests 3.0.0
Fetching rspec-core 3.9.2
Installing rspec-core 3.9.2
Fetching rspec-expectations 3.9.2
Installing rspec-expectations 3.9.2
Fetching rspec-mocks 3.9.1
Fetching rubocop-ast 0.0.3
Installing rspec-mocks 3.9.1
Installing rubocop-ast 0.0.3
Fetching activesupport 6.0.3.1
Installing activesupport 6.0.3.1
Fetching term-ansicolor 1.7.1
Installing term-ansicolor 1.7.1
Fetching domain_name 0.5.20190701
Installing domain_name 0.5.20190701
Fetching ronn 0.7.3
Installing ronn 0.7.3
Fetching simplecov 0.16.1
Installing simplecov 0.16.1
Fetching rspec-retry 0.6.2
Fetching rspec-its 1.3.0
Installing rspec-retry 0.6.2
Installing rspec-its 1.3.0
Fetching rspec 3.9.0
Fetching rubocop 0.85.1
Installing rspec 3.9.0
Fetching http-cookie 1.0.3
Installing http-cookie 1.0.3
Installing rubocop 0.85.1
Fetching coveralls 0.8.23
Installing coveralls 0.8.23
Fetching rspec-wait 0.0.9
Installing rspec-wait 0.0.9
Fetching rubocop-performance 1.6.1
Fetching rubocop-rspec 1.39.0
Installing rubocop-performance 1.6.1
Installing rubocop-rspec 1.39.0
Fetching mechanize 2.7.6
Installing mechanize 2.7.6
Bundle complete! 17 Gemfile dependencies, 60 gems now installed.
Bundled gems are installed into `../../../../../../../usr/local/Homebrew/Library/Homebrew/vendor/bundle`
Post-install message from i18n:

HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.

If you are upgrading your Rails application from an older version of Rails:

Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.

If you are starting a NEW Rails application, you can ignore this notice.

For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0

Randomized with seed 32485
4 processes for 282 specs, ~ 70 specs per process
.....................................................................................*........................................................................................................................................................................****....*.........................................................................................................................................................................................................................................................................................................................................*....................................*.......................................*.......................................................................................................................................................................................***.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*.........................................................F.............................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) brew pull fetches a patch from a GitHub commit or pull request and applies it
     # Requires network connection.
     # ./test/dev-cmd/pull_spec.rb:10

  2) Utils#self.svn_remote_exists? when svn is available returns true when remote exists
     # Requires network connection.
     # ./test/utils/svn_spec.rb:35

  3) brew cask list returns a list of installed Casks
     # Requires network connection.
     # ./test/cmd/cask_spec.rb:5

  4) Bintray::file_published? detects a published file
     # Requires network connection.
     # ./test/bintray_spec.rb:8

  5) Bintray::file_published? fails on a non-existant file
     # Requires network connection.
     # ./test/bintray_spec.rb:13

  6) Bintray::package_exists? detects a package
     # Requires network connection.
     # ./test/bintray_spec.rb:20

  7) brew services allows controlling services
     # Requires network connection.
     # ./test/cmd/services_spec.rb:4

Failures:

  1) Satisfy Dependencies and Requirements depends_on macos given a comparison does not raise an error
     Failure/Error: expect { install }.not_to raise_error

       expected no Exception, got #<Cask::CaskError: macOS Catalina or newer is required.> with backtrace:
         # ./cask/installer.rb:260:in `macos_dependencies'
         # ./cask/installer.rb:250:in `satisfy_dependencies'
         # ./cask/installer.rb:65:in `fetch'
         # ./cask/installer.rb:90:in `install'
         # ./test/cask/depends_on_spec.rb:7:in `block (2 levels) in <top (required)>'
         # ./test/cask/depends_on_spec.rb:46:in `block (5 levels) in <top (required)>'
         # ./test/cask/depends_on_spec.rb:46:in `block (4 levels) in <top (required)>'
         # ./test/support/helper/spec/shared_context/homebrew_cask.rb:52:in `block (2 levels) in <top (required)>'
         # ./test/spec_helper.rb:185:in `block (2 levels) in <top (required)>'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
     # ./test/cask/depends_on_spec.rb:46:in `block (4 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/homebrew_cask.rb:52:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:185:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

Finished in 4 minutes 1.8 seconds (files took 3.8 seconds to load)
839 examples, 1 failure, 7 pending

Failed examples:

rspec ./test/cask/depends_on_spec.rb:45 # Satisfy Dependencies and Requirements depends_on macos given a comparison does not raise an error

.....................................................................................................................................................................................................................................................................

Finished in 4 minutes 49.2 seconds (files took 3.7 seconds to load)
607 examples, 0 failures

..........................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Cask::Cmd::Info can run be run with a url twice and returns analytics
     # Requires network connection.
     # ./test/cask/cmd/info_spec.rb:143

  2) GitHub::search_issues queries GitHub issues with the passed parameters
     # Requires network connection.
     # ./test/utils/github_spec.rb:35

  3) GitHub::get_artifact_url fails to find artifacts that don't exist
     # Requires network connection.
     # ./test/utils/github_spec.rb:52

  4) GitHub::get_artifact_url gets an artifact link
     # Requires network connection.
     # ./test/utils/github_spec.rb:58

  5) GitHub::get_artifact_url fails to find a nonexistant workflow
     # Requires network connection.
     # ./test/utils/github_spec.rb:46

  6) GitHub::search_code queries GitHub code with the passed parameters
     # Requires network connection.
     # ./test/utils/github_spec.rb:7

Finished in 5 minutes 12 seconds (files took 3.74 seconds to load)
634 examples, 0 failures, 6 pending

......................................................*...........................................................................................................................................................................................*...................................................................................................................................*.......................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) brew bundle check checks if a Brewfile's dependencies are satisfied
     # Requires network connection.
     # ./test/cmd/bundle_spec.rb:5

  2) Utils::git_remote_exists? when git is available returns true when git remote exists
     # Requires network connection.
     # ./test/utils/git_spec.rb:133

  3) brew search falls back to a GitHub tap search when no formula is found
     # Requires network connection.
     # ./test/cmd/search_spec.rb:11

Finished in 7 minutes 31 seconds (files took 3.76 seconds to load)
670 examples, 0 failures, 3 pending

Tests Failed

2750 examples, 1 failure, 16 pendings

Took 455 seconds (7:35)
</pre>
</details>

**Comment by MikeMcQuaid** [comment]
>        expected no Exception, got #<Cask::CaskError: macOS Catalina or newer is required.> with backtrace:

This is unintentional. We should update the relevant test cask so it depends on `yosemite` instead. @gromgit would you be able to take a look? I can help however desired.

**Comment by gromgit** [comment]
Thanks for the hint, @MikeMcQuaid. Wasn't sure where to start looking otherwise.
