### ISSUE TITLE
Universal 2 (Apple Silicone) binary support

### ISSUE THREAD

**Issue by crunchtime-ali** [Homebrew/brew#7792]
# A detailed description of the proposed feature

Homebrew will need to support both "classic" binaries compiling for x64 and Universal 2 binaries which will likely include both a x64 binary and an ARM binary _(Will add data about Universal 2 as more information about it becomes available)_.
At the same time ARM based Macs with MacOS 10.16 "Big Sur" will also support installing iPad OS apps natively (most likely only through the app store).

Starting with a similar approach as Linuxbrew which does not have bottles but compiles ARM applications might be a good idea.

![Screenshot from XCode's new architecture choice dialogue](https://user-images.githubusercontent.com/7140800/85325114-5f647000-b4cb-11ea-9add-2f9048e7a92e.png)

# The motivation for the feature

With the announcement of using Apple's own ARM-based A12/A13 SoC chips for new Macs during [Apple's WWDC 2020 Keynote](https://youtu.be/GEZhD3J89ZE?t=5284) they will also introduce a new binary format called "Universal 2" which will contain Intel and ARM compiled binaries. As with the transition from PowerPC to Intel Apple will migrate towards their so-called "Apple Silicone" within 2 years while starting to deliver hardware by the end of 2020. 

![Screenshot from WWDC keynote of Universal 2](https://user-images.githubusercontent.com/7140800/85324967-1ca29800-b4cb-11ea-8416-0c92e849e53d.png)

# How the feature would be relevant to at least 90% of Homebrew users

Apple will transition to only sell ARM-based Macs within two years so all users will need it at some point.

**Comment by iMichka** [comment]
Hi.

We are aware of this. The first pull requests have already started flowing in, and we are working on the support for the new hardware.

Please let the maintainers work on this. Your issue does not really help, as there is nothing actionnable here.

We will make a release once we are ready.

**Comment by sjackman** [comment]
See @mistydemeo 's PRs https://github.com/Homebrew/brew/pull/7793 and https://github.com/Homebrew/brew/pull/7794.
