### ISSUE TITLE
Migrate custom workflow logic into self-contained GitHub Actions

### ISSUE THREAD

**Issue by jonchang** [Homebrew/brew#7805]
# A detailed description of the proposed feature

Homebrew uses GitHub Actions as its continuous integration provider. There are a number of places where we have extensive custom logic written in GitHub Script or bash. We should move these into custom Actions that live in [Homebrew/actions](https://github.com/Homebrew/actions).

Some possible candidates for migration:

* Push with random retry
    * https://github.com/Homebrew/homebrew-core/blob/3abba3ee9598c926176611b95fd4282e73fc8e31/.github/workflows/publish-commit-bottles.yml#L78-L90
    * https://github.com/Homebrew/linuxbrew-core/blob/9524c86c71f432dfa3bb9b6c37cddec6b9528919/.github/workflows/dispatch-build-bottle.yml#L53-L73
* Set up git information for the maintainer who triggered the workflow
    * https://github.com/Homebrew/homebrew-core/blob/3abba3ee9598c926176611b95fd4282e73fc8e31/.github/workflows/publish-commit-bottles.yml#L14-L26
* Posting a comment when a build fails
    * https://github.com/Homebrew/homebrew-core/blob/257a1cb95132b4195d5ffae595aa008dfb09e36e/.github/workflows/publish-commit-bottles.yml#L91-L135
    * https://github.com/Homebrew/linuxbrew-core/blob/9524c86c71f432dfa3bb9b6c37cddec6b9528919/.github/workflows/dispatch-build-bottle.yml#L74-L106
* Setting up Homebrew (ideally cross-platform and Docker/GitHub VM-agnostic)
    * https://github.com/Homebrew/homebrew-core/blob/3abba3ee9598c926176611b95fd4282e73fc8e31/.github/workflows/tests.yml#L13-L59
    * https://github.com/Homebrew/brew/blob/2d54b9b1370f976d1992c9d9ccb0225fa4ca5bfa/.github/workflows/tests.yml#L17-L53
    * https://github.com/Homebrew/linuxbrew-core/blob/9524c86c71f432dfa3bb9b6c37cddec6b9528919/.github/workflows/tests.yml#L10-L48

# The motivation for the feature

* Modularizing and centralizing the workflows in Homebrew/actions mean that there will be more cross-repository consistency in how we e.g. build bottles or set up Homebrew on CI.
* We should be able to more easily test modularized workflows in a contained CI environment on Homebrew/actions, rather than potentially messing up workflows in Homebrew/homebrew-core or Homebrew/brew.

# How the feature would be relevant to at least 90% of Homebrew users

* Maintainers would be able to spend more time working on Homebrew rather than fixing issues with our custom workflows.
* Maintainers who focus on ops would be able to more easily trial staged migrations via development tags on Homebrew/actions, rather than constantly updating a `do not merge` pull request in Homebrew/homebrew-core.
* Maintainers of third-party taps would be able to replicate our exact workflows to have a better experience for their users, who are our users as well.
* Users would be less likely to encounter odd breakages due to workflow quirks.

# What alternatives to the feature have been considered

* Continuing to use custom bash and GitHub-script workflows
    * This doesn't need new code, and is quite easy to iterate on since you're working directly in the repository itself. The disadvantages are listed above.

**Comment by dawidd6** [comment]
> Push with random retry

Started an implementation here: https://github.com/dawidd6/action-git-try-push. Will move to `Homebrew/actions` later and work on it there.

**Comment by dawidd6** [comment]
Push with random retry is live in `homebrew-core` now: https://github.com/Homebrew/homebrew-core/commit/4501ee0d440618d152b95dc024f52e11bdcc26a2

**Comment by jonchang** [comment]
Composite actions are coming which I think will help reduce the amount of JavaScript necessary to maintain our custom Actions, though I don't know how long it will take for this to move from "experimental" to "stable":

https://github.com/actions/runner/pull/549

**Comment by dawidd6** [comment]
Seems like last thing is:

> Setting up Homebrew (ideally cross-platform and Docker/GitHub VM-agnostic)

**Comment by MikeMcQuaid** [comment]
> > Setting up Homebrew (ideally cross-platform and Docker/GitHub VM-agnostic)

Yup! Ideally this would be something that could be shared with e.g. Homebrew/brew, Homebrew/homebrew-core, Homebrew/linuxbrew-core and work on both self-hosted and hosted runners. Feel free to scope that back initially if it's too involved, though.

**Comment by dtrodrigues** [comment]
Something that's currently manually done that could be automated by a GitHub Action is the labeling of `homebrew-core` PRs containing "(new formula)" in the title with the `new formula` label.

**Comment by dawidd6** [comment]
Good point. If no one steps out to implement this, I will try in next week.

**Comment by MikeMcQuaid** [comment]
@dawidd6 that'd be great. Ideally done not on the title but the created files from the git diff in the `Formula` directory.

**Comment by jonchang** [comment]
> Something that's currently manually done that could be automated by a GitHub Action is the labeling of `homebrew-core` PRs containing "(new formula)" in the title with the `new formula` label.

See also https://github.com/actions/labeler. Note that this would need to be done as a scheduled task, since as that repository shows, pull requests on forked repositories don't have sufficient permissions to add labels. https://github.com/actions/stale/ is an example of a labeler that runs on a schedule.

**Comment by dtrodrigues** [comment]
Another idea - create/re-use a label for the `homebrew-core` repo that an Action applies based on having `bottle :unneeded` in the formula definition so that after CI passses, it gives an indication that the PR should be manually merged vs just approved and later picked up by @BrewTestBot.

**Comment by MikeMcQuaid** [comment]
@dtrodrigues That's a good idea 👍

**Comment by jonchang** [comment]
Thanks so much for your work on this @dawidd6!! This is excellent.

**Comment by MikeMcQuaid** [comment]
Great work @dawidd6 👏🏻
