### ISSUE TITLE
Trying=> Downloading wimlib Error: You are using macOS 10.16.

### ISSUE THREAD

**Issue by chris1111** [Homebrew/brew#7819]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

Error: You are using macOS 10.16.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.
<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Output of `brew config` and `brew doctor` commands

<pre>

</pre>

**Comment by MikeMcQuaid** [comment]
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC. You are responsible for resolving any issues you
> experience while you are running this pre-release version.
