### ISSUE TITLE
Brew cleanup should remove brew cask image ( or brew --cache should output brew cask image dir )

### ISSUE THREAD

**Issue by huyhoang8398** [Homebrew/brew#7824]
# A detailed description of the proposed feature

Brew cleanup should remove brew cask image ( or brew --cache should output brew cask image dir)
For example `brew --cache` wont print directory for cask cache image `/usr/local/Caskroom`

# The motivation for the feature

It is better for user, so we dont have to manually delete cask cache.

# How the feature would be relevant to at least 90% of Homebrew users

I came from Linux, all the package managers there has this feature, so why not bring it to MacOS

# What alternatives to the feature have been considered

`brew --cache should include /usr/local/Caskroom`

**Comment by claui** [comment]
Not sure if I understand what you mean. `/usr/local/Caskroom` is a staging area for currently installed casks.
It also contains some bookkeeping (metadata) and the occasional residual file copied from
the original DMG. All of that is supposed to be removed on `brew cask uninstall` and `brew cask upgrade` already.

What would be a simple example for something in `/usr/local/Caskroom` that the `brew cleanup` command you feel should remove, and at what time?
Please include the specific `brew cask` command(s) you used.
