### ISSUE TITLE
`brew audit --strict` finds nonexistent issue

### ISSUE THREAD

**Issue by gromgit** [Homebrew/brew#7848]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm in the process of fixing the `john` formula, and decided to audit my current draft. `brew audit` gave it a clean bill of health, but `brew audit --strict` complains about a path that isn't even in my draft.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ brew audit --strict john
john:
  * Use pkgshare instead of (share/"john")
Error: 1 problem in 1 formula detected
  </pre>
</details>

## What you expected to happen

Since I'm already using `pkgshare` everywhere in my draft, I was _not_ expecting this error.

## Step-by-step reproduction instructions (by running `brew` commands)

```
$ brew audit --strict https://gist.githubusercontent.com/gromgit/72c9bd4cb4a57ec61519efa09af6eba0/raw/be4b78ba104d5be13272e1a00fb4480e6b30b079/john.rb
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.4.2-35-gb4cd99c
ORIGIN: https://github.com/Homebrew/brew
HEAD: b4cd99c67c80dfb3eb7a907c18f460c90d0a1b3f
Last commit: 31 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6a0e2dd12de9ab34d19438d9a97d55746b78422a
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 11.0 build 1100
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew/homebrew-core is not on the master branch.

Check out the master branch by running:
  git -C "$(brew --repo homebrew/core)" checkout master

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  rtv

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libpgtcl.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  parallel
  moreutils

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
   M Formula/john.rb
</pre>

**Comment by MikeMcQuaid** [comment]
> Since I'm already using `pkgshare` everywhere in my draft, I was _not_ expecting this error.

It's detected from the inline patch. Fixing this is going to be part of https://github.com/Homebrew/brew/issues/7392.

I'd suggest moving the patch to an `inreplace` or Homebrew/formula-patches too (which will also solve this).
