### ISSUE TITLE
"support for this pre-release version."

### ISSUE THREAD

**Issue by AbbyJanke** [Homebrew/brew#7851]
Installing a fresh install of Homebrew as I cleared my MacOS and installed MacOS Big Sur. I get the standard information about pre-release not being supported but one thing I caught was this:

"Warning: You are using macOS 10.16."

Big Sur is actually MacOS 11.0. I looked into figuring out how I could submit a PR to address this but honestly don't know much about the core system of HomeBrew or core of Mac OS.

Not a priority just wanted to share if somebody else was able to find a way.

**Comment by iMichka** [comment]
See #7806/#7810

**Comment by MikeMcQuaid** [comment]
> Big Sur is actually MacOS 11.0.

Not on Intel.

Please always fill out the issue template.
