### ISSUE TITLE
Can not upgrading plantuml 1.2020.14 -> 1.2020.15, macOS Big Sur

### ISSUE THREAD

**Issue by smoothdvd** [Homebrew/brew#7864]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

brew upgrade plantuml

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

==> Upgrading plantuml 1.2020.14 -> 1.2020.15 
==> Downloading https://downloads.sourceforge.net/project/plantuml/1.2020.15/plantuml.1.2020.15.jar
Already downloaded: /Users/alexgao/Library/Caches/Homebrew/downloads/7b242130fab13d4a87930b751a9c94692f6aa1ec952d4c4995bfb3e2f3bbb12d--plantuml.1.2020.15.jar
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths

  </pre>
</details>

**Comment by jonchang** [comment]
> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

`brew doctor` would have told you:

> Warning: You are using macOS 10.16.
> We do not provide support for this pre-release version.
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC. You are responsible for resolving any issues you
> experience while you are running this pre-release version.
