### ISSUE TITLE
Error: cmake: undefined method `on_linux' for #<Class:0x00007fd9f81ea828>

### ISSUE THREAD

**Issue by jerryjee** [Homebrew/brew#7865]
When i use brew upgrade it says:
Error: cmake: undefined method `on_linux' for #<Class:0x00007fd9f81ea828>

**Comment by jerryjee** [comment]
`brew doctor` return :

Warning: Some installed formulae are not readable:
  fontconfig: undefined method `on_linux' for #<Class:0x00007fdc2d1684b8>

  glib: undefined method `on_linux' for Formulary::FormulaNamespace1b33d7b036781a8c4dc38a980a07e0d5::Glib:Class

  go: undefined method `on_macos' for #<Resource:0x00007fdc2dae12b0>

  wget: undefined method `on_linux' for Formulary::FormulaNamespaceb9dd1c776502f226ac47565f079b2a92::Wget:Class

**Comment by jonchang** [comment]
> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

You need to update Homebrew. The `on_linux` feature was included in v2.2.13, which was released on April 14.
