### ISSUE TITLE
Error while HomeBrew installing

### ISSUE THREAD

**Issue by alexanderhk1** [Homebrew/brew#7873]
## What you were trying to do (and why)
I'm trying to install homebrew on MacBook with macOS Catalina 10.15.5

## What happened (include command output)
I'm getting invalid formula error within the pandoc-include-code.rb file

<details>
  <summary>Command output</summary>
  <pre>

 ==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 741450 (delta 18), reused 21 (delta 10), pack-reused 741417
Receiving objects: 100% (741450/741450), 298.75 MiB | 5.61 MiB/s, done.
Resolving deltas: 100% (490916/490916), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pandoc-include-code.rb
pandoc-include-code: undefined method `license' for #<Class:0x00007fd066c60a50>
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing; `/usr/local/bin/brew tap homebrew/core` exited with 1.

  </pre>
</details>

## Output of `brew config` and `brew doctor` commands

<pre>
brew doctor: The same thing while installing. It still trying to download the data and I'm getting the same error
brew config:
HOMEBREW_VERSION: 2.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: f7c7e2e793ed35f354974f2fcdb5fb22a3d924a3
Last commit: 7 days ago
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: N/A
</pre>

**Comment by alexanderhk1** [comment]
I home you can fix this problem 🙏

**Comment by Bo98** [comment]
Should be fixed now.
