### ISSUE TITLE
brew tap homebrew/cask-cask always ask for password github

### ISSUE THREAD

**Issue by ViniciusDeep** [Homebrew/brew#7876]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I'm trying to made brew tap to cask.

## What happened (include command output)
When a trying to put a command brew tap homebrew/cask-cask, brew ask for github credentials and when a put the credential the output is a failure, I have access to github and I put the right password but the answer is a invalid username of password.

This is appear when I run the brew update -dv: https://gist.github.com/ViniciusDeep/52b212b3a6bde4dbd69906a4cfed63dd

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Output of `brew config` and `brew doctor` commands

Output
```
==> Tapping homebrew/cask-cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-cask'...
Username for 'https://github.com': ViniciusDeep
Password for 'https://ViniciusDeep@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Homebrew/homebrew-cask-cask/'
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-cask-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-cask` exited with 128.
```

brew config output:
```
HOMEBREW_VERSION: 2.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: f7c7e2e793ed35f354974f2fcdb5fb22a3d924a3
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eb8ceabaf6e32648a02260803f79db29184a7468
Core tap last commit: 31 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: 11.5
```

Brew doctor:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  cocoapods
```

<pre>

</pre>

**Comment by Bo98** [comment]
`homebrew/cask-cask` does not exist. Did you mean `brew tap homebrew/cask`?
