### ISSUE TITLE
Homebrew GCC --HEAD install not properly detected

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/brew#789]
When trying to build OpenBLAS, Homebrew appears to not recognize GCC as being installed and/or useable if GCC had been installed with `--HEAD`.

I originally installed GCC with `brew install gcc --with-all-languages --with-java --with-jit --with-nls --HEAD`. I then tried to install OpenBLAS using the command `brew install openblas --with-openmp --HEAD`, which failed with the following:

    Error: homebrew/science/openglas cannot be built with any available compilers. Install GNU's GCC

`brew info gcc` shows that GCC is installed, though. If GCC is reinstalled without `--HEAD`, Homebrew appears to find it just fine.

**Comment by UniqMartin** [comment]
What are the names of the compiler frontend binaries when installing `--HEAD`, i.e. what does `ls -l "$(brew --prefix)"/bin/{g++,gcc,gfortran}*` list? I think our compiler selection logic currently only recognizes `gcc-X` where `X` is 4.5 to 4.9, 5, or 6 (and similarly for the other frontends), so that might be one clue why the `--HEAD` installation isn't recognized …

**Comment by aw1621107** [comment]
I've seen both `g++-` and `g++-2`, along with the equivalents for the other binaries. The 2 on the end is inconsistent, and I'm not sure when a build would produce one or the other.

**Comment by MikeMcQuaid** [comment]
It's probably worth trying to fix up the formula so that it installs with a known suffix and then we can whitelist that.

**Comment by aw1621107** [comment]
Alright, from a fresh `--HEAD` install, the suffix appears to be `2` in nearly all cases. The only exceptions are that both `x86_64-apple-darwin16.0.0-gcc-2` and `x86_86-apple-darwin16.0.0-gcc-7.0.0` and `gfortran` and `gfortran-2` are present.

**Comment by UniqMartin** [comment]
I think the [`version_suffix` method](https://github.com/Homebrew/homebrew-core/blob/7e26b69789c3b2fa373fdb974b5b347351fc931d/Formula/gcc.rb#L74-L76) in the `gcc` formula is a bit too naive and needs some additional logic to handle the HEAD case correctly. Would be great if you could look into this!

**Comment by MikeMcQuaid** [comment]
> I think the version_suffix method in the gcc formula is a bit too naive and needs some additional logic to handle the HEAD case correctly. Would be great if you could look into this!

Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by aw1621107** [comment]
Alright, should be fixed with PR #955 here and PR #4783 in homebrew-core.

**Comment by apjanke** [comment]
:+1: on the approach you're taking here.

I think #955 needs a bit more work (see comment there); there's another version-parsing location that'll need updating too. https://github.com/Homebrew/homebrew-core/pull/4783 looks good to go.
