### ISSUE TITLE
`brew deps --tree` gives wrong info

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#7892]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

List dependencies of a formula.

## What happened (include command output)

```
$ brew deps --tree glib
glib
├── gettext
├── libffi
├── pcre
├── gdbm
├── openssl@1.1
├── readline
├── sqlite
│   └── readline
├── xz
└── python@3.8
    ├── gdbm
    ├── openssl@1.1
    ├── readline
    ├── sqlite
    │   └── readline
    └── xz
```

This is wrong because `xz` and `readline` are not direct dependencies.

**Comment by fxcoudert** [comment]
Also: it seems now the output of `brew deps` is recursive by default… it wasn't before. Not sure if that is intentional.

**Comment by MikeMcQuaid** [comment]
> Also: it seems now the output of `brew deps` is recursive by default… it wasn't before. Not sure if that is intentional.

This is intentional.

> This is wrong because `xz` and `readline` are not direct dependencies.

As noted by @Bo98: these are calculated based on the actual linkage on your system rather than specified dependencies.
