### ISSUE TITLE
`brew search --casks` outputs nothing, which breaks `brew cask install ` completion in Zsh

### ISSUE THREAD

**Issue by marlonrichert** [Homebrew/brew#7893]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to use completion in Zsh on `brew cask install `, but nothing happened.

## What happened (include command output)

It turns out this is because `brew search --casks` produces zero output.

## What you expected to happen

If I type `brew cask install ` and press <kbd>Tab</kbd>, then something should be shown.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew search --casks`

## Output of `brew config` and `brew doctor` commands

<pre>
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/marlon/.pyenv/shims/python-config
  /Users/marlon/.pyenv/shims/python3-config
  /Users/marlon/.pyenv/shims/python3.8-config

❯ brew config
HOMEBREW_VERSION: 2.4.3-31-gf1e4c4e
ORIGIN: https://github.com/Homebrew/brew
HEAD: f1e4c4ed56a9f719534b8db04af13a8c4617c537
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 68e9ded385cc6a45f2525707a11153533bb3bb35
Core tap last commit: 58 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.yQkvCOnBbO/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_144
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.5
XQuartz: 2.7.11 => /opt/X11
</pre>

**Comment by marlonrichert** [comment]
I ran `brew cask doctor`, which tapped `homebrew/cask`, which solved the problem.

`brew search --cask` should automatically tap `homebrew/cask`. Then this wouldn't happen.

**Comment by Bo98** [comment]
It's intentional that shell completion doesn't change files on your system, so I don't think `brew search --cask` auto-tapping will happen. Or if it does then an exception will be made to make it not happen in shell completion.

For example, the completion for `brew cask upgrade` invokes `brew cask list` (which would ordinarily auto-tap), but there's a check to not do so if `homebrew/cask` isn't tapped.

**Comment by marlonrichert** [comment]
Well, at least it should tell me _why_ it's not showing any completions. I wasn't aware I had to first tap `homebrew/cask`.

**Comment by marlonrichert** [comment]
The same goes for `brew search --cask`. It just outputs nothing. That's not very helpful.

**Comment by MikeMcQuaid** [comment]
> so I don't think `brew search --cask` auto-tapping will happen

Agreed. Passing on this, sorry.

> It just outputs nothing.

That's not uncommon for Unix commands in general.
