### ISSUE TITLE
Idea / RFC: support virtual brew environments

### ISSUE THREAD

**Issue by dd-ssc** [Homebrew/brew#7902]
(NOTE: I know nothing about Ruby; I know something about Python. I'm writing this from a Python perspective hoping the paradigms are similar enough in Ruby for this to make sense in both worlds.)

# A detailed description of the proposed feature

**Support installing brew in a virtual environment.**

This is analog to the concept of virtual environments supported by programming languages (e.g. [RVM](http://rvm.io) or [bundler](https://bundler.io) in Ruby, built-in [venv](https://docs.python.org/3.7/library/venv.html) or [pipenv](https://pypi.org/project/pipenv) in Python, etc.) and has the same intention: Create an isolated environment / installation that serves a specific purpose independent of /  in addition to the "regular" / "main" installation. Just like Ruby / Python / etc. venvs, the virtual env should be trivial to create and remove.

# The motivation for the feature

To give some context, I believe the motivation for Python/Ruby virtual environments is fairly well known:

### Python/Ruby virtual environments

**Problem:** If I work on a Python/Ruby project and need a package/gem, I should not install that to the system Python/Ruby installation (or update one that exists there) because

- that might break other (system) applications that rely on that system package/gem in a certain version
- installing packages to the system for a number of projects over time messes up the system Python/Ruby, rendering it unmanageable:
- a large number of packages exists in _some_ version (typically current at installation time)
- different projects might require different (possibly conflicting) versions
- I might not even remember what project I installed a package for and what package version that project requires - and as there typically is no "configuration" of package/gems to install, updating _all_ system packages/gems might fix one problem in one project, but break other projects

**Solution:** I leave the system Python/Ruby installation in its pristine state and instead create a Python/Ruby virtual environment, install the package/gem there and use that venv in my project.

### Homebrew virtual environments

IMO, the constellation described above applies to Homebrew in an analogous fashion: 

**Problem:** If the same Python/Ruby project as above for example needs a command line tool provided by a brew formula, I should not install that formula to the "system" brew installation - _for the very same reasons_:

- it might break other (system) applications that rely on that "system" formula in a certain version
- a large number of formulae exists (albeit not in _some_, but in the most recent version - assuming a recent `brew update && brew upgrade`)
- different projects might require different (possibly conflicting) versions
- I might not even remember what project I installed a formula for and what formula version that project requires - and as there typically is no "configuration" of formulae to install, updating _all_ system formulae might fix one problem in one project, but break other projects

**Solution:** I leave the system Homebrew installation in its pristine state and instead create a Homebrew virtual environment, install the formulae there and use that venv in my project.

# How the feature would be relevant to at least 90% of Homebrew users

I would imagine that every Homebrew user sooner or later runs into a situation where a certain brew formula is only required for one short term (but possibly repeatedly necessary) task or not the most recent, but an earlier version of a formula is required. I suppose the latter was the reason why [`brew switch`](https://docs.brew.sh/Tips-N'-Tricks#activate-a-previously-installed-version-of-a-formula) exists. Virtual brew environments would creating a reproducible venv for the short term task and allow `switch`ing inside that venv only - while leaving the system brew in its pristine, up to date state, providing the latest and greatest formulae.

# What alternatives to the feature have been considered

Right now, I create a Docker container, install (Linux) brew inside it and install formulae in the required version. Solves the problem, but requires a huge amount of effort and has other drawbacks.

# What other advantages might this feature provide

I could imagine this also helps with brew core and formula development: Not talking from own practical experience here, but running brew core / installing formulae under development in an isolated environment, independent from the system brew, might eliminate some existing annoyances, open up possibilities not currently available and facilitate automated testing.

# What existing solutions might provide inspiration

As mentioned before, I don't work with Ruby, so I don't know how well the various venv implementations work in practice. Python has gone through quite a few iterations in the last couple of years, but in my (obviously subjective) opinion has now come to a point where [pipenv](https://pypi.org/project/pipenv) absolutely nails it and provides the last word in that respect (BTW drawing itself inspiration from JavaScript / node.js `npm` package concepts, i.e. `package.json`, `package-lock.json` / `Pipfile`, `Pipfile.lock`, etc.); a brew env implementation could possibly copy `pipenv` concepts 1:1, avoiding said unsuccessful iterations:

A Homebrew venv is defined by [two files](https://pipenv-fork.readthedocs.io/en/latest/basics.html#example-pipfile-pipfile-lock):

1. a primary file called `brewfile` that contains the formulae requested - in version `"*"` if the current formula version is fine; in _pinned_ version `"1.2.3"` if a specific version is needed; [package dependency semver syntax](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept) optional
2. a secondary `brewfile.lock` file contains the formulae in the version actually installed: the current one if `"*"` in `brewfile`, a specific one if specified in `brewfile`; it also contains some meta data, e.g. the `.tar.gz` package download sha256 sum

- both `brewfile`  and `brewfile.lock` should be kept under version control
- the actual brew venv files are nowhere near the current folder, but instead in `~/.local/share/brewenvs/<env name>-<uuid>` (determined reproducibly, based on the current path).
- the brew venv (and `brewfile.lock`) can be re-created at any time using `brewfile` at a reproducible folder underneath `./local`
- `brewfile` only changes if a project's package (version) requirements change, `brewfile.lock` changes upon `brewenv update` if new versions of unpinned formulae are available

The command line API could be just `sed 's|pip|brew|g`:

- `brewenv install` with no `brewfile` present in the current folder creates a new virtual brew env, creating said boilerplate `brewfile` and `brewfile.lock` files
- `brewenv install <formula>`, run in the same folder, installs that formula to the venv, updating `brewfile` and `brewfile.lock`
- `brewenv uninstall <formula>` removes that formula from the venv, again updating `brewfile`and `brewfile.lock`
- `brewenv update` updates all venv formulae to their most recent versions (unless pinned)
- `brewenv --rm` deletes the entire brew venv from `~/.local`; does not change `brewfile` nor `brewfile.lock`

**Comment by claui** [comment]
While the proposed system would be without doubt extremely useful, and I would definitely use it myself if it were available, I sincerely doubt the proposal fits Homebrew’s scope and long-term mission. It would introduce several new _dimensions_ of support burden at the same time (e. g. going back to building formulae from source instead of using bottles; pinning formulae to arbitrary versions; having to add semver restrictions in many places, including `depends_on`; and so on.)

With that out of the way: I use a very primitive, low-tech version of this on my development machine. It’s not endorsed by Homebrew, and it’s not nearly as powerful as what you’re proposing here but feel free to experiment with it.

1. Clone secondary Homebrew directly from Git. This directory would be equivalent to the _brew venv_ from your RFC.
2. `cd` to the root directory of the brew venv.
3. Use `bin/brew` instead of `brew` for everything.

The biggest nuisance is that `bin/brew update` doesn’t really work. So I use the following workaround for updating:

```
(
  set -eux;

  HOMEBREW_PREFIX=[set this to your secondary Homebrew’s Git root directory]
  HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}"
  HOMEBREW_BREW_FILE="${HOMEBREW_PREFIX}/bin/brew"
  HOMEBREW_LIBRARY="${HOMEBREW_REPOSITORY}/Library"
  git -C "${HOMEBREW_REPOSITORY}" checkout master
  git -C "${HOMEBREW_REPOSITORY}" \
    pull --autostash
  # Repeat for all taps
  git -C "${HOMEBREW_LIBRARY}/Taps/homebrew/homebrew-core" \
    checkout master
  git -C "${HOMEBREW_LIBRARY}/Taps/homebrew/homebrew-core" \
    pull --autostash
  "${HOMEBREW_BREW_FILE}" update
)
```

Note: I do not endorse or support the crude thing I described; it’s purely FYI.

**Comment by MikeMcQuaid** [comment]
> * a primary file called `brewfile` that contains the formulae requested - in version `"*"` if the current formula version is fine; in _pinned_ version `"1.2.3"` if a specific version is needed; [package dependency semver syntax](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept) optional

https://github.com/homebrew/homebrew-bundle does part of this.

---

As for the rest: you'd need to have a separate Homebrew installation for each virtual environment. Given they couldn't share the default location: they'd been to be built from source. As a result, I think the user experience would be pretty terrible so we're not interested in officially supporting it. Sorry!
