### ISSUE TITLE
Enable Automatic PR Rebase using Github Action

### ISSUE THREAD

**Issue by awasum** [Homebrew/brew#7907]
Add ability to automatically rebase PRs when a Developer comments on the PR. See: https://github.com/marketplace/actions/automatic-rebase

This may reduce time when reviewing and addressing feedback on PRs

**Comment by claui** [comment]
Thanks @awasum. Please fill out the issue template if you’d like us to add this feature.

**Comment by MikeMcQuaid** [comment]
I'd rather we didn't add this as it will add complexity for users who don't understand how to handle e.g. a force push on their branch.

**Comment by awasum** [comment]
> I'd rather we didn't add this as it will add complexity for users who don't understand how to handle e.g. a force push on their branch.

Thanks.
