### ISSUE TITLE
Respect DO_NOT_TRACK to opt out of telemetry

### ISSUE THREAD

**Issue by jnordberg** [Homebrew/brew#7914]
Brew should respect the `DO_NOT_TRACK` environment variable, as per https://github.com/Homebrew/brew/pull/6745 this standard has been adopted by several projects and it's time to re-evaluate.

Software currently respecting `DO_NOT_TRACK`:
 - https://github.com/netdata/netdata
 - https://github.com/tilt-dev/tilt (and https://github.com/tilt-dev/tilt.build)
 - https://github.com/Automattic/vip

Also see https://github.com/beatcracker/toptout and https://consoledonottrack.com

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by MikeMcQuaid** [comment]
It's been adopted (from https://consoledonottrack.com) by three projects of which I've heard of/used none. Given the conversation in https://github.com/Homebrew/brew/pull/6745 rapidly turned unpleasant and resulted in multiple blocks: I'm not going to entertain more of this bad behaviour (of which I include "not filling out our issue templates") until there's substantial adoption (100+ projects).
