### ISSUE TITLE
Respect DO_NOT_TRACK to opt out of telemetry

### ISSUE THREAD

**Issue by jnordberg** [Homebrew/brew#7916]
# A detailed description of the proposed feature

Brew should respect the `DO_NOT_TRACK` environment variable, as per https://github.com/Homebrew/brew/pull/6745 this standard has been adopted by several projects and it's time to re-evaluate.

Software currently respecting `DO_NOT_TRACK`:
 - https://github.com/netdata/netdata
 - https://github.com/tilt-dev/tilt (and https://github.com/tilt-dev/tilt.build)
 - https://github.com/Automattic/vip

Also see https://github.com/beatcracker/toptout and https://consoledonottrack.com

# The motivation for the feature

Respecting users privacy

# How the feature would be relevant to at least 90% of Homebrew users

Improved privacy and control of their choices

# What alternatives to the feature have been considered

N/A

**Comment by vitorgalvao** [comment]
The standard seems to lack a proposal for opting in to specific cases. What can a user do if they want to allow analytics for some tools and not others?

It’s not inconceivable to me to want analytics disabled for most tools but allow exceptions when they produce a tangible benefit. For example, in Homebrew Cask I make extensive usage of analytics to decide if a severely broken cask is worth the trouble of fixing or should just be removed (no one is using it anyway). By opting-out of those, you’re reducing the attention given to a cask for a software you care about, so may want those on.

Without a rule for exceptions, the standard doesn’t adequately replace each tool’s own variables/flags.

**Comment by jnordberg** [comment]
The privacy respecting way of doing that would be to use an actual opt-in for tracking and informing the users of the benefits of enabling it.

**Comment by iMichka** [comment]
`would be to use an actual opt-in`: we have chosen opt-out a long time ago, and this is not going to change anytime soon.

I am not in favour of implementing this. Adoption still seems very low right now. And I agree with @vitorgalvao's point too.

If you can convince 5 or 10 maintainers from homebrew that this is necessary, I would reconsider this. We have also a technical comitee that can cast a vote on this if needed, but I prefer to keep that option as a last resort.

Not sure if there is any actionable thing here right now that can move this issue forward. I'll let this issue open for 1 or 2 days, but if it does not gets traction I'll close it.

**Comment by MikeMcQuaid** [comment]
> Brew should respect the `DO_NOT_TRACK` environment variable, as per #6745 this standard has been adopted by several projects and it's time to re-evaluate.

It's been adopted (from https://consoledonottrack.com) by three projects of which I've heard of/used none. Given the conversation in https://github.com/Homebrew/brew/pull/6745 rapidly turned unpleasant and resulted in multiple blocks: we want to wait until there's substantial adoption (100+ projects) before we'll consider (which doesn't mean "we'll do it" but "we'll have a conversation about it").
