### ISSUE TITLE
`brew install remake` fails if `make` already installed and linked

### ISSUE THREAD

**Issue by yumitsu** [Homebrew/brew#7921]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>`?

## What you were trying to do (and why)

`brew upgrade remake`. `brew reinstall remake` fails as well.

## What happened (include command output)

https://gist.github.com/yumitsu/099ff179b3a0cd5ed1de3a07aea5c4dd

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading https://homebrew.bintray.com/bottles/remake-4.3-1.5.high_sierra.bottle.tar.gz
Already downloaded: /Users/yumitsu/Library/Caches/Homebrew/downloads/26223072dc15c121528464112959236c8c22a602255bf4fbc48258c473dd3a02--remake-4.3-1.5.high_sierra.bottle.tar.gz
==> Verifying 26223072dc15c121528464112959236c8c22a602255bf4fbc48258c473dd3a02--remake-4.3-1.5.high_sierra.bottle.tar.gz checksum
==> Pouring remake-4.3-1.5.high_sierra.bottle.tar.gz
tar xof /Users/yumitsu/Library/Caches/Homebrew/downloads/26223072dc15c121528464112959236c8c22a602255bf4fbc48258c473dd3a02--remake-4.3-1.5.high_sierra.bottle.tar.gz -C /var/folders/gk/sctmxj9s1v34xg05ww_4hc8w0000gn/T/d20200706-50405-1qvuvl4
cp -pR /var/folders/gk/sctmxj9s1v34xg05ww_4hc8w0000gn/T/d20200706-50405-1qvuvl4/remake/. /usr/local/Cellar/remake
chmod -Rf +w /var/folders/gk/sctmxj9s1v34xg05ww_4hc8w0000gn/T/d20200706-50405-1qvuvl4
==> Finishing up
ln -s ../Cellar/remake/4.3-1.5/bin/remake remake
ln -s ../Cellar/remake/4.3-1.5/include/gnuremake.h gnuremake.h
rm /usr/local/bin/remake
rm /usr/local/include/gnuremake.h
Error: no implicit conversion of nil into Array
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:1122:in `+'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1122:in `link_overwrite?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:860:in `rescue in link'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:856:in `link'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:673:in `finish'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:336:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:262:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:260:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:260:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'

  </pre>
</details>

## What you expected to happen

I guess there should be an error regarding symlinking.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install make
brew link make
brew install remake
```

**Comment by MikeMcQuaid** [comment]
Fix in https://github.com/Homebrew/brew/pull/7922
