### ISSUE TITLE
services not loaded

### ISSUE THREAD

**Issue by revolter** [Homebrew/brew#7926]
Simply running `brew services start gitlab-runner` fails with

```
/Users/user/Library/LaunchAgents/homebrew.mxcl.gitlab-runner.plist: service already loaded
Error: Failure while executing; `/bin/launchctl bootstrap gui/502 /Users/user/Library/LaunchAgents/homebrew.mxcl.gitlab-runner.plist` exited with 37.
```

**Comment by MikeMcQuaid** [comment]
> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
