### ISSUE TITLE
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist

### ISSUE THREAD

**Issue by Archerious** [Homebrew/brew#7936]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [Y] ran `brew update` and can still reproduce the problem?
- [Y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Y] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

To install and search for brave browser and other packages.

## What happened (include command output)

The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist

<details>
  <summary>Command output</summary>
  <pre>

brew search brave
2020-07-07 19:38:01.615 defaults[93934:854672] 
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist

  </pre>
</details>

## What you expected to happen

For it to tell me if brave is available or not.

## Step-by-step reproduction instructions (by running `brew` commands)

brew search brave

## Output of `brew config` and `brew doctor` commands

<pre>

kazuma@Air ~ % brew config
HOMEBREW_VERSION: 2.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: f455fe28a7a47b51af090b308e95535d6cf0a423
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0bd6d5083b5942a3e726366a6ebc1658ad53e3f1
Core tap last commit: 23 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit icelake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 1103.0.32.62
Xcode: N/A

kazuma@Air ~ % brew doctor
Your system is ready to brew.

</pre>

**Comment by Archerious** [comment]
After restarting my MacBook Air it seems to be now searching brew but it is still giving the error.

Am I safe to ignore it?

<img width="694" alt="Screen Shot 2020-07-07 at 7 43 14 PM" src="https://user-images.githubusercontent.com/26941475/86860301-31198f80-c08a-11ea-8b61-4ccd68ea6634.png">

`
kazuma@Air ~ % brew search brave
2020-07-07 19:42:40.823 defaults[95723:861067] 
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist
==> Casks
brave-browser
homebrew/cask-versions/brave-browser-beta
homebrew/cask-versions/brave-browser-dev
homebrew/cask-versions/brave-browser-nightly
kazuma@Air ~ % 
`

**Comment by Archerious** [comment]
<img width="673" alt="Screen Shot 2020-07-07 at 7 45 24 PM" src="https://user-images.githubusercontent.com/26941475/86860426-7047e080-c08a-11ea-9982-4378dff2796a.png">

**Comment by Bo98** [comment]
> Am I safe to ignore it?

It's non-critical so I think you can. It's printed from `defaults read -g AppleLanguages`.

I guess something about your setup means there isn't a language setting in your user profile for some reason. Does `defaults read /Library/Preferences/.GlobalPreferences AppleLanguages` print anything?

**Comment by Archerious** [comment]
```
kazuma@Air ~ % defaults read /Library/Preferences/.GlobalPreferences AppleLanguages
(
    "en-US"
)
kazuma@Air ~ % 

```

**Comment by Archerious** [comment]
I guess this isn't anything for me to be concerned about since the issue was closed.

**Comment by MikeMcQuaid** [comment]
Yup 👍

**Comment by Archerious** [comment]
Sounds good

**Comment by Bo98** [comment]
By the way, I made some adjustments to prevent the warning appearing and to better handle the case where `defaults read -g AppleLanguages` returns nothing: #7940
