### ISSUE TITLE
Homebrew picks Xcode from /Volumes/Macintosh HD on multi-partition/system

### ISSUE THREAD

**Issue by jozefvaclavik** [Homebrew/brew#7938]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm installing emacs on Big Sur thats installed on separate partition. I know macOS 10.16/11 is not supported, but this seems to be multi-partition issue rather then Big Sur issue.

## What happened (include command output)

I have Big Sur installed on separate partition `/Volumes/Big Sur`. I have command line tools installed. It noticed few times that when I was installing something via homebrew and it had to be compiled, it picked up Xcode from mounted Catalina partition. Once I unmount it in Disc Utility and run the same install command, it all runs fine.

<details>
  <summary>Command output</summary>
  <pre>
~ > brew install emacs-plus@27 --with-jasson
...
installing bunch of dependencies
...
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-black-variant.icns
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-nuvola.icns
######################################################################## 100.0%
==> Cloning https://github.com/emacs-mirror/emacs.git
Cloning into '/Users/jozefvaclavik/Library/Caches/Homebrew/emacs-plus@27--git'...
Updating files: 100% (4023/4023), done.
==> Checking out branch emacs-27
Already on 'emacs-27'
Your branch is up to date with 'origin/emacs-27'.
Error: Your Xcode (11.4.1 => /Volumes/Macintosh HD/Applications/Xcode.app/Contents/Developer) is too outdated.
Please update to Xcode 12.0 (or delete it).
Xcode can be updated from:
  https://developer.apple.com/download/more/

~ >
  </pre>
</details>

## What you expected to happen

It should not try to access Xcode from non-system partition.

## Step-by-step reproduction instructions (by running `brew` commands)

1. Get two systems running
2. One on `/Volumes/Macintosh HD`
3. One on `/Volumes/Whatever
4. Run system from `/Volumes/Whatever` partition and Install something that requires compiling
5. It _should_ fail on `Xcode` version mismatch
6. Unmount `/Volumes/Macintosh HD`
7. Try again and it will pass

## Output of `brew config` and `brew doctor` commands

<pre>
# UNMOUNTED /Volumes/Macintosh HD

~ ❯ brew config
HOMEBREW_VERSION: 2.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: f455fe28a7a47b51af090b308e95535d6cf0a423
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c6c126b7fffc19d501a9a7a2951ad03bebd027e2
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 12.0 build 1200
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.16-x86_64
CLT: 12.0.0.0.1.1592862858
Xcode: N/A

# MOUNTED /Volumes/Macintosh HD

~ ❯ brew config 
HOMEBREW_VERSION: 2.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: f455fe28a7a47b51af090b308e95535d6cf0a423
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c6c126b7fffc19d501a9a7a2951ad03bebd027e2
Core tap last commit: 12 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 12.0 build 1200
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.16-x86_64
CLT: 12.0.0.0.1.1592862858
Xcode: 11.4.1 => /Volumes/Macintosh HD/Applications/Xcode.app/Contents/Developer

~ ❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  emacs-mac
  emacs-plus@27
  python@3.8

Warning: You are using macOS 10.16.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.
</pre>

**Comment by MikeMcQuaid** [comment]
> We do not provide support for this pre-release version.
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC. You are responsible for resolving any issues you
> experience while you are running this pre-release version.

On this issue specifically: point to the right Xcode with `xcode-select`.

**Comment by jozefvaclavik** [comment]
I never selected Xcode from Catalina. I have cmdline tools installed and its running fine on Big Sur, but as soon as I mount Catalina partition homebrew is picking up Xcode from there? What am I missing here?

**Comment by MikeMcQuaid** [comment]
> Im simply pointing out that homebrew is picking up Xcode from other system.

Ok, in this case: this is intentional behaviour.
