### ISSUE TITLE
Assuming wrong shell in .profile

### ISSUE THREAD

**Issue by nihaals** [Homebrew/brew#7965]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Add Homebrew to my PATH as suggested by [the docs](https://docs.brew.sh/Homebrew-on-Linux#install)

## What happened (include command output)

`set: -g: invalid option` (more extensive but not relevant in my opinion as the issue is known)

## What you expected to happen

It adds it to my PATH

## Step-by-step reproduction instructions (by running `brew` commands)

1. Use GNOME
2. Set `fish` as your default shell, possibly making sure `$SHELL` is fish.
3. Run `echo "eval \$($(brew --prefix)/bin/brew shellenv)" >> ~/.profile` (in Bash)
4. Log out and back in
5. Notice `.profile` error

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.4.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6d2c39579e22d0ee9baccdccdd8a12efb8b00304
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 5c3e01d57e4bb18d4b338b6893800cfaa65bc197
Core tap last commit: 50 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: N/A
Git: 2.27.0 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-40-generic x86_64 GNU/Linux
OS: Ubuntu 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
glibc: N/A
gcc: N/A
xorg: N/A

$ brew doctor
Your system is ready to brew.
</pre>

## Additional Context

GNOME sources `~/.profile` on login. I believe this is always with Bash and is not affected by the login shell.
Output of `ps --forest`:
```
    PID TTY          TIME CMD
  23877 tty2     00:00:00 gdm-x-session
  23879 tty2     00:00:00  \_ Xorg
  23903 tty2     00:00:00  \_ Xsession
  23908 tty2     00:00:00      \_ ps
```
It seems `brew shellenv` is impacted by `$SHELL`, and returns Fish env vars setup code.
Output:
```
$ brew shellenv
set -gx HOMEBREW_PREFIX "/home/linuxbrew/.linuxbrew";
set -gx HOMEBREW_CELLAR "/home/linuxbrew/.linuxbrew/Cellar";
set -gx HOMEBREW_REPOSITORY "/home/linuxbrew/.linuxbrew/Homebrew";
set -q PATH; or set PATH ''; set -gx PATH "/home/linuxbrew/.linuxbrew/bin" "/home/linuxbrew/.linuxbrew/sbin" $PATH;
set -q MANPATH; or set MANPATH ''; set -gx MANPATH "/home/linuxbrew/.linuxbrew/share/man" $MANPATH;
set -q INFOPATH; or set INFOPATH ''; set -gx INFOPATH "/home/linuxbrew/.linuxbrew/share/info" $INFOPATH;
```
This also happens in `.profile` as `SHELL` is set to Fish, however, as `.profile` is sourced with Bash, `eval $(brew shellenv)` errors as the returned commands are for Fish. A workaround:
```
$ SHELL=bash brew shellenv
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}";
export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH}";
```
As this is not included in the docs, maybe `shellenv` should detect if it is running part of this GNOME source or use a different way of detecting the shell as using `SHELL` is not accurate in this context. If this wasn't added then maybe a warning in the docs should be included explaining this.

Full workaround:
Run `echo "eval \$(SHELL=/bin/bash $(brew --prefix)/bin/brew shellenv)" >> ~/.profile` instead (in Bash)

Workaround part of first installation (replacement for docs):
```
> bash
$ test -d ~/.linuxbrew && eval $(SHELL=/bin/bash ~/.linuxbrew/bin/brew shellenv)
$ test -d /home/linuxbrew/.linuxbrew && eval $(SHELL=/bin/bash /home/linuxbrew/.linuxbrew/bin/brew shellenv)
$ test -r ~/.bash_profile && echo "eval \$(SHELL=/bin/bash $(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
$ echo "eval \$(SHELL=/bin/bash $(brew --prefix)/bin/brew shellenv)" >>~/.profile
```

**Comment by gromgit** [comment]
Currently, https://docs.brew.sh/Homebrew-on-Linux assumes the user uses a Bourne-type login shell. That needs to be fixed.

@nihaals, please try removing the `shellenv` invocation from your `~/.profile`, and add the following to your `~/.config/fish/config.fish` instead:
```
if status --is-login
    if test -f /home/linuxbrew/.linuxbrew/bin/brew
        /home/linuxbrew/.linuxbrew/bin/brew shellenv | source
    end
end
```
Then logout and login again, and let us know if you're still seeing issues.

**Comment by nihaals** [comment]
Didn't work. I'm not sure why, `status --is-login` is exactly what is used in the fish docs and running just the test and actual source worked fine in a normal shell.

**Comment by nihaals** [comment]
After testing, it seems that `status --is-login` is always failing.
```
> getent passwd $LOGNAME | cut -d: -f7
/usr/bin/fish
```
I added the following to my `~/.config/fish/config.fish` (which is definitely executed when creating a new interactive shell)
```fish
if status --is-login
  date >> ~/login-times.log
   ...
end
```
and had no file created when logging out and back in, but `fish -l` *did* work.

According to https://askubuntu.com/a/598072, GNOME does not execute the login shell by default (this was also unticked for me, 20.04). This means that adding this to the documentation *wouldn't* be a good idea. I'm not sure what the best path for this is as having documentation that a user can use without simply adjusting the commands for their standard setup purely based on their DE is fairly important, but this seems to be fairly exclusive to GNOME. Improving shell detection and continuing to recommend using `.profile` would probably be best, but I believe if the user is not using GNOME nor a Bourne shell as their login shell, this will either error or not be executed:
- Using GNOME
  - Using Bourne login shell
    Currently works fine
  - Using non Bourne login shell
    As explained in `Additional Context` in the original issue, this errors (`$SHELL` mismatches the shell currently executing `.profile`
- Not using GNOME (or another DE with the same behaviour if there are any?)
  - Using Bourne login shell
    Currently works fine
  - Not using Bourne login shell
    `.profile` is probably not executed, depends on the setup of the user. They may do something like `bass ~/.profile` [[bass](https://github.com/edc/bass)], in which case see `GNOME > non Bourne`. They may rewrite `~/.profile` in their shell and simply source it in their "on shell" script or not have a `~/.profile` and have all the equivalent commands only in their "on shell" script, in which case this is currently fine as the user will know how to make it specific to their setup.

So the current problems are using GNOME with a non Bourne shell set as their login shell or not using GNOME, using a non Bourne shell as their login shell and execute their `.profile` with a Bourne shell. I'm assuming latter can be ignored as this is pretty user specific so they will know to make a change when setting it up, however, I didn't know basically anything I mentioned in any of these comments a day ago and I was impacted with a "standard" setup, so having the former be supported or for there to be clear documentation may be important for new users.

**Comment by gromgit** [comment]
Actually, I'm starting to think that `shellenv` should be returning exports based on the _calling shell_ (`$PPID`) rather than the _login shell_ (`$SHELL`), especially since the current set of instructions embed a runtime call to `brew shellenv`, rather than the exports determined at install time.

@Homebrew/brew , if you agree, I'd be happy to issue a PR to fix this.

**Comment by claui** [comment]
> Actually, I'm starting to think that `shellenv` should be returning exports based on the _calling shell_ (`$PPID`) rather than the _login shell_ (`$SHELL`), especially since the current set of instructions embed a runtime call to `brew shellenv`, rather than the exports determined at install time.

Another way would be a few lines of feature detection code (along with the returned exports, not at the time `shellenv` is called.)
I can’t tell though whether that would or wouldn’t be as robust as detecting the shell via `$PPID`.

**Comment by nihaals** [comment]
> feature detection code

As in it would check for the existence of features/commands in the current shell then execute whichever ones exist?

> $PPID

Didn't realise this existed, that would cover the better shell detection I was explaining. However, I'm assuming it would return the same as `ps`, and as my output shows, it's not necessarily the shell, but could be something part of the DE. This might get messy as a variety of DEs would need to be checked to see if they do the same as GNOME and what process calls it

**Comment by claui** [comment]
> As in it would check for the existence of features/commands in the current shell then execute whichever ones exist?

Yes, that’s exactly what I had in mind. I don’t have a strong opinion about it though.

**Comment by nihaals** [comment]
I think if it was reliable it would definitely be the best as it avoids the identification I just explained. Not sure how easy it is to make shell code that works on any shell and identifies it though, other than just calling `/bin/sh` (I think *every* sane setup has it?)

**Comment by gromgit** [comment]
> As in it would check for the existence of features/commands in the current shell then execute whichever ones exist?

That would be nice if doable, though I can't imagine a code fragment that can be correctly parsed by both Bourne and C shells, yet do the necessary tests and run the necessary commands.

> I'm assuming it would return the same as ps, and as my output shows, it's not necessarily the shell, but could be something part of the DE.

The parent of `brew shellenv` is either a shell (interactive, or running a script), or not. If it's a shell, `ps -p $PPID -o comm=` should print its name to be matched. If it's not (e.g. a binary, or Python script), odds are good that `/bin/sh` was invoked anyway to run `brew shellenv`, so the current default Bourne-style output would still be the most appropriate.

**Comment by claui** [comment]
> That would be nice if doable, though I can't imagine a code fragment that can be correctly parsed by both Bourne and C shells, yet do the necessary tests and run the necessary commands.

I was thinking about something along the following (untested) lines:

```bash
if (set -gx __probe 1 >/dev/null 2>&1); then
  set -gx HOMEBREW_PREFIX […]
else
  export HOMEBREW_PREFIX=[…]
fi
```

But as I said, I don’t feel I prefer one approach over the other.

**Comment by miccal** [comment]
@gromgit just an FYI, on my machine:
```
-bash-5.0.18- /Users/miccal (29) [> echo $SHELL
/usr/local/bin/bash
-bash-5.0.18- /Users/miccal (29) [> ps -p $PPID -o comm=
login
```
while:
```
-bash-5.0.18- /Users/miccal (29) [> ps -o comm=
-bash
```

**Comment by gromgit** [comment]
That shouldn't be an issue, since `$PPID` in `brew shellenv` would point to the process that spawned it, i.e. your interactive session (bash) or whatever script ran it (the shell that said script was written in).

**Comment by jonchang** [comment]
I think if you wrap it in a script it works properly, and that should be the case for `brew shellenv`:

```console
% bash script.sh
-zsh

% /bin/bash

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
$ bash script.sh 
/bin/bash
```

**Comment by miccal** [comment]
Ah, I see -- thanks for the explanation @gromgit

**Comment by gromgit** [comment]
@nihaals Please `brew update` and see if the `shellenv` fix solves your issue,

**Comment by nihaals** [comment]
It didn't, about to debug

**Comment by nihaals** [comment]
```
> /home/linuxbrew/.linuxbrew/bin/brew update
Already up-to-date.
> /home/linuxbrew/.linuxbrew/bin/brew --version
Homebrew 2.4.6
Homebrew/linuxbrew-core (git revision 28e0f3; last commit 2020-07-13)
> /home/linuxbrew/.linuxbrew/bin/brew shellenv
set -gx ...
...
> SHELL=bash /home/linuxbrew/.linuxbrew/bin/brew shellenv
export ...
...
```
Looking at https://github.com/Homebrew/brew/commit/0f6bc6274f8fc0cfc19636688fc8aa6752d0c296, it doesn't seem to be part of the 2.4.6 tag and isn't listed in the [changelog](https://github.com/Homebrew/brew/releases/tag/2.4.6)

**Comment by miccal** [comment]
@nihaals unless you have `HOMEBREW_DEVELOPER` set you will not see this change until a new tag is released.

**Comment by nihaals** [comment]
Oh, didn't realise that was a feature. Yep, works great!
