### ISSUE TITLE
Wrong dependency when installing tap package with the same name in core

### ISSUE THREAD

**Issue by ncihnegn** [Homebrew/brew#7973]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I install a custom glib to remove dependency on python@3.8.

## What happened (include command output)

 But brew still **implicitly** believes that package depends on python@3.8. 

<details>
  <summary>Command output</summary>
  <pre>
➜  Formula git:(master) ✗ brew remove python@3.8
Error: Refusing to uninstall /usr/local/Cellar/python@3.8/3.8.3_2
because it is required by cairo, graphviz, gts, harfbuzz, and pango, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies python@3.8
➜  Formula git:(master) ✗ brew info ncihnegn/formulae/glib
ncihnegn/formulae/glib: stable 2.64.3 (bottled)
Core application library for C
https://developer.gnome.org/glib/
/usr/local/Cellar/glib/2.64.3 (436 files, 15.7MB) *
  Poured from bottle on 2020-07-10 at 00:46:16
From: https://github.com/ncihnegn/homebrew-formulae/blob/HEAD/glib.rb
License: LGPL-2.1
==> Dependencies
Build: meson ✘, ninja ✔, pkg-config ✔
Required: gettext ✔, libffi ✔, pcre ✔
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Analytics
install: 209,764 (30 days), 854,647 (90 days), 3,386,704 (365 days)
install-on-request: 21,593 (30 days), 70,013 (90 days), 231,416 (365 days)
build-error: 0 (30 days)  

  </pre>
</details>

## What you expected to happen

Since the custom glib doesn't depend on python@3.8, cairo/gts should not require python anymore.

## Step-by-step reproduction instructions (by running `brew` commands)
```
brew install cairo
brew remove --ignore-depencies glib
brew install ncihnegn/formulae/glib
brew remove python@3.8
```
## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.4.5-2-gb8018b4
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8018b49dae2f5ef8c680239d74b16fc6fa4e907
Last commit: 17 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3df657b805ed3422f638110c160a1266e4192a3c
Core tap last commit: 20 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Xod8eQbNaf/org.macosforge.xquartz:0
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_252-b09, 1.8.0_231
macOS: 10.15.5-x86_64
CLT: 1103.0.32.62
Xcode: 11.5
XQuartz: 2.7.11 => /opt/X11

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/ncihnegn/.cargo/bin/cargo-install-update-config
</pre>

**Comment by MikeMcQuaid** [comment]
We recommend you use different names for formulae in taps shadowing homebrew/core formulae. I can't see a confirmed bug here but we'll consider a PR if you find one.
