### ISSUE TITLE
brew install sublime-text3   Error: No formulae found in taps.

### ISSUE THREAD

**Issue by ideasotw** [Homebrew/brew#798]
I am running OS X Yosemite. I am getting the following error when I try to install sublime-text3 -Error: No formulae found in taps. Any help will do. Thanks

IE11Win7:~ E$ brew cask install sublime-text3
Error: No available Cask for sublime-text3
Error: nothing to install
IE11Win7:~ E$ brew install sublime-text3
Error: No available formula with the name "sublime-text3"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
IE11Win7:~ E$

**I have tried the following commands and I am still getting errors;**

brew uninstall brew-cask
brew untap caskroom/cask
brew tap caskroom/cask
brew install brew-cask

brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

**Comment by jawshooah** [comment]
You can `brew cask install sublime-text`. It was recently upgraded from 2 to 3, and `sublime-text2` is now available in the [caskroom/versions](https://github.com/caskroom/homebrew-versions) tap.

**Comment by ideasotw** [comment]
Works! thank you

**Comment by scottie-schneider** [comment]
Thanks for the help, found this and saved myself some frustration 👍 @jawshooah
