### ISSUE TITLE
Error: Failed to download resource "glib"

### ISSUE THREAD

**Issue by juanpc2018** [Homebrew/brew#7987]
http://macappstore.org/glib/

> ==> Downloading https://download.gnome.org/sources/glib/2.64/glib-2.64.4.tar.xz
> 
> curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect
> Error: Failed to download resource "glib"
> Download failed: https://download.gnome.org/sources/glib/2.64/glib-2.64.4.tar.xz
> MacPro1:~ a$ 

i always had problems with glib...
Yosemite 10.10.5
El Capitan 10.11.3

different machines, 
MacPro 5,1 2010
MacBookPro Early 2013

**Comment by claui** [comment]
This issue is not related to Homebrew. See also: https://github.com/Homebrew/brew/issues/7667

Also, please use the issue template next time. Thank you!
