### ISSUE TITLE
Compatibility checker for major macOS updates

### ISSUE THREAD

**Issue by mikestecker** [Homebrew/brew#7998]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

# A detailed description of the proposed feature

It would be great to get a command where we could check upgradability of currently installed kegs against the compatibility table on #7857.

# The motivation for the feature

Before upgrading major OS versions, it would be great to be able to check to ensure everything is going to work properly.

# How the feature would be relevant to at least 90% of Homebrew users

Anyone upgrading can run this checker before deciding to upgrade to the next major MacOS version.

# What alternatives to the feature have been considered

none

**Comment by MikeMcQuaid** [comment]
Our equivalent of this is our announced "supported" versions.
