### ISSUE TITLE
gcc not searching /usr/local/include

### ISSUE THREAD

**Issue by dl1ycf** [Homebrew/brew#8024]
Did "brew update; brew upgrade" today. This replaced gcc-9 with gcc-10 and now I have to define

CC = "gcc-10 -I/usr/local/include"

otherwise nothing works. By default, all the include files in /usr/local are not found.

**Comment by jonchang** [comment]
Please always fill out the issue template.

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

**Comment by dl1ycf** [comment]
I will surely never again report an error.
