### ISSUE TITLE
Improve `brew bump-formula-pr` for Python formulae

### ISSUE THREAD

**Issue by SeekingMeaning** [Homebrew/brew#8032]
# Description

`brew bump-formula-pr` has some problems when dealing with some Python formulae

These are the main issues:

1. `bump-formula-pr <formula> --version <x.y.z>` doesn't retrieve the correct URL for packages hosted on `file.python.hosted.org`
    - The filename (`foo-x.y.z.tar.gz`) is updated but the middle of the URL isn't
    - Example of what `bump-formula-pr` **currently** does:
        ```patch
        -  url "https://files.pythonhosted.org/packages/44/5e/d0785bd787af5f37b7f0b69c2b36a731cf222163a474aeb1be109252f4a7/python-openstackclient-5.3.0.tar.gz"
        +  url "https://files.pythonhosted.org/packages/44/5e/d0785bd787af5f37b7f0b69c2b36a731cf222163a474aeb1be109252f4a7/python-openstackclient-5.3.1.tar.gz"
        ```
    - Example of what `bump-formula-pr` **should** do:
        ```patch
        -  url "https://files.pythonhosted.org/packages/44/5e/d0785bd787af5f37b7f0b69c2b36a731cf222163a474aeb1be109252f4a7/python-openstackclient-5.3.0.tar.gz"
        +  url "https://files.pythonhosted.org/packages/84/19/e2453fa06c4f481beda7a6c2326e65884cd1c623177d13c8efc7850bc05e/python-openstackclient-5.3.1.tar.gz"
        ```
1. Python formulae often have many resources. `bump-formula-pr` ignores these, so version bumps for these resources can be neglected accidentally
    - A good example of this is `jenkins-job-builder`: https://github.com/Homebrew/homebrew-core/commit/8149d2bd370621c3df7c0c8bf3f469ab4916d03e
    - Currently, maintainers have the responsibility to check if a formula has resources and check/ask if they require updates.

See further discussion in #8029

# Solutions

- [ ] Have `brew bump-formula-pr` automatically retrieve the correct `files.pythonhosted.org` URL based on the results of `https://pypi.org/pypi/<formula>/json` (#8037)
- [ ] Require `--force` (or another flag) for `bump-formula-pr` to open a PR for a formula with `resource` blocks (#8036)
    - The user should be prompted to update the `resource` blocks (probably with a link to [`homebrew-pypi-poet`](https://docs.brew.sh/Python-for-Formula-Authors#installing))
    - `--force` would allow the PR to be opened anyway (useful if resources don't need to be updated)

**Comment by Rylan12** [comment]
Thanks, @SeekingMeaning 

Was there also an issue with `bump-formula-pr` not being able to follow the `files.pythonhosted.org` urls?

Maybe I misunderstood or made something up...

**Comment by SeekingMeaning** [comment]
Oh yeah, you're right

I think `bump-formula-pr` failing on `files.pythonhosted.org` urls is acceptable since it'll let us know that the package is a PyPI package and then we can check for resource updates using `homebrew-pypi-poet`

Or if the feature mentioned in this issue is implemented, then I suppose we could fix the urls

**Comment by Rylan12** [comment]
I'm not sure I totally understand the issue. Can you give me an example of something that fails (or would fail)?

**Comment by SeekingMeaning** [comment]
For example `brew bump-formula-pr openstackclient --version 5.3.2`

```patch
-  url "https://files.pythonhosted.org/packages/84/19/e2453fa06c4f481beda7a6c2326e65884cd1c623177d13c8efc7850bc05e/python-openstackclient-5.3.1.tar.gz"
+  url "https://files.pythonhosted.org/packages/84/19/e2453fa06c4f481beda7a6c2326e65884cd1c623177d13c8efc7850bc05e/python-openstackclient-5.3.2.tar.gz"
```

`5.3.1` is replaced with `5.3.2` but the middle part isn't updated

**Comment by Rylan12** [comment]
Ah, I see. Thanks for the clarification!

**Comment by maxim-belkin** [comment]
you could determine the package, then its "short" url, then use curl to determine there it redirects.

**Comment by Rylan12** [comment]
> you could determine the package, then its "short" url, then use curl to determine where it redirects.

Is this a better solution than querying the json from `https://pypi.org/pypi/<formula>/json`? (Genuine question because I'm not sure)

I know we have some [`curl`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/curl.rb) methods (I haven't looked in detail at them yet) so maybe that's a good way to do it. I'm not sure yet how to do it the other way, so I guess this is the top option right now. Thanks for pointing it out!

**Comment by maxim-belkin** [comment]
What you suggest sounds great! My point was that it should be doable.

**Comment by jonchang** [comment]
We might not be able to access `curl` and friends in a Rubocop but we can certainly do it in a regular audit.

**Comment by Rylan12** [comment]
> We might not be able to access `curl` and friends in a Rubocop but we can certainly do it in a regular audit.

I was thinking this would be in `bump-formula-pr` rather than in a rubocop or an audit. Is that not a good assumption?

**Comment by jonchang** [comment]
Sorry, thought this was the rubocop pypi issue, about an autocorrecter for the cop. Yes, doing it in bump-formula-pr would be perfectly fine.

**Comment by MikeMcQuaid** [comment]
> * The user should be prompted to update the `resource` blocks (probably with a link to [`homebrew-pypi-poet`](https://docs.brew.sh/Python-for-Formula-Authors#installing))

Maybe `homebrew-pypi-poet` could be brought into Homebrew/brew and run automatically for Python formulae?

**Comment by Rylan12** [comment]
> Maybe `homebrew-pypi-poet` could be brought into Homebrew/brew and run automatically for Python formulae?

Where are you thinking this would be used? A separate `update-python-resources` command? In an audit? Just trying to get a sense.

And, are you suggesting a rewrite of `homebrew-pypi-poet` in ruby for Homebrew or just wrapping what already exists?

**Comment by MikeMcQuaid** [comment]
> Where are you thinking this would be used? A separate `update-python-resources` command? In an audit? Just trying to get a sense.

I'm thinking it could be separate command which could also be called by `brew bump-formula-pr` when needed.



> And, are you suggesting a rewrite of `homebrew-pypi-poet` in ruby for Homebrew or just wrapping what already exists?

I think a Ruby rewrite would be preferable, if possible 👍

**Comment by dtrodrigues** [comment]
This is what I envisioned as an end-ish goal for python formulae in homebrew:
1. For python formulae that only need `homebrew-pypi-poet` functionality resources and don't have other python dependencies that aren't required, add something to the formula DSL to indicate that this is the case. eg `snakemake` and `twarc` don't need special handling but `diffoscope` and `molecule` do. Most python formulae that require special handling have a comment in the resource section, so it would be better to formalize that.
2. A user runs `brew bump-formula-pr <formula_name>`.
3.  `bump-formula-pr` uses `pypi-poet`-like functionality to update both the primary url and add/remove/update resources as required. A version isn't even needed to be provided since `pypi-poet` will grab the latest version or the logic @Rylan12 added #8037 (`json["releases"][version].find { |url| url["packagetype"] == "sdist" }["url"]`)
4. The required changes get made to the URL and resource blocks and PR is opened, possibly with an enhanced message saying that this has auto-bumped resources.
5. A maintainer spot-checks the PR after tests pass to ensure nothing funky happened and approves it.

Note that with this workflow, 2. doesn't even need to be done by a human and could instead be done as an automated Github action on python formulae. I'm not sure if this is something that `livecheck` would do or if this would complement `livecheck.

**Comment by samford** [comment]
I just want to add a friendly reminder that, however this is done, it's important to respect the dependency requirements when updating Python resource blocks. I've seen resources naively bumped to the latest available version on PyPI without consideration of dependency requirements a number of times and this is something we want to avoid.

`ansible` in particular seems to be a constant challenge and I ended up writing some [lengthy instructions](https://github.com/Homebrew/homebrew-core/pull/50504#issuecomment-592743222) in the past on how to update it properly. This formula consistently trips up contributors and, unfortunately, maintainers have sometimes recommended inappropriate ways of updating Python resource blocks (i.e., using the latest version of each resource, like https://github.com/dawidd6/homebrew-update-pypi-resources does).

I agree with Mike that it would be great to have this as a separate command that can also be leveraged in `bump-formula-pr`.

**Comment by Rylan12** [comment]
Thanks for the reminder, @samford (also, nice instructions)!

Don't worry, this will definitely not go away in the rewrite.

@dtrodrigues can you give a brief example of what you're envisioning? (no need to go in too much depth but I'm curious what you're thinking a formula with python resources would look like)

**Comment by dtrodrigues** [comment]
What part would you like more information on? I'm thinking that a person could type `brew bump-formula-pr <formula>` for a formula that is `poet-upgradable` and the latest version would be pulled from PyPI as well as the addition/removal/updates to any resource blocks, and a PR would be created.

**Comment by Rylan12** [comment]
Ah, so it sounds like the function of the `poet-upgradable` line (or whatever it ends up being called) is just an indicator saying "this formula's resources can be automatically bumped using `homebrew-pypi-poet` logic"

So, once the new brew command is added, it will only work for formulae that have specified that they are `poet-upgradable`.

Without this, the solution would likely be to just check for resources with `files.pythonhosted.org` URLs and only work on those.

Is that what you're thinking?

**Comment by MikeMcQuaid** [comment]
I'm not sure why this would need a new DSL. I'd say our tooling can have a built-in allowlist initially but would ideally infer from the existing formulae resources that aren't needed.

As a first pass I'd love to just see "run homebrew-pypi-poet on `brew bump-formula-pr` on all formulae which have resources with `files.pythonhosted.org` URLs.

**Comment by dtrodrigues** [comment]
It doesn't need a new DSL, but a way to differentiate which python ones can and can't be bumped with just `homebrew-pypi-poet` is needed. As @samford described for `ansible` as well as for other formulae to include `molecule`, `sphinx-doc`, `diffoscope`, and `cloudformation-cli`, we definitely do not want `homebrew-pypi-poet` in its current form run on those automatically as part of `bump-formula-pr`, even though they have python dependencies. 

A separately-managed allowlist will work, and based on the conversation in https://github.com/Homebrew/brew/pull/8048, it seems like the intention is to decouple attributes of formulae in the core tap (eg their throttle rate, whether `pypi-poet` works on them) from the formulae themselves and instead keep that information within the `brew` repository. Keeping the formula-specific attribute of whether `pypi-poet` works within the `bump-formula-pr/run-homebrew-pypi-poet` commands would be consistent with that decision.

**Comment by MikeMcQuaid** [comment]
> we definitely do not want `homebrew-pypi-poet` in its current form run on those automatically as part of `bump-formula-pr`, even though they have python dependencies.

That's fine, it's not going to be. 

Let's move this conversation to https://github.com/Homebrew/brew/pull/8059 and focus on the requirements of an actual implementation.
