### ISSUE TITLE
Online audit error: undefined method `[]' for nil:NilClass 

### ISSUE THREAD

**Issue by crunchtime-ali** [Homebrew/brew#8062]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Update the `aws-cdk` formula

## What happened (include command output)

```
Error: undefined method `[]' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/utils/notability.rb:12:in `github_repo_data'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:531:in `audit_github_repository_archived'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:893:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:886:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:886:in `audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:132:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:117:in `each'

```
The full CI log can be seen here https://github.com/Homebrew/homebrew-core/pull/58377/checks?check_run_id=898421691

The error happens in CI as well as locally.

This is likely caused by:
https://github.com/Homebrew/brew/commit/dab18076fad3fd331793786e042d11cfec93c681

/cc @SMillerDev

**Comment by SMillerDev** [comment]
Fixed by #8063

**Comment by crunchtime-ali** [comment]
@SMillerDev that was quick. Can you kick the CI server here https://github.com/Homebrew/homebrew-core/pull/58377 again? If the build succeeds I will close this issue.

**Comment by SMillerDev** [comment]
Already donee
