### ISSUE TITLE
Brew install gcc installed version 5.5 instead of 10

### ISSUE THREAD

**Issue by robertwt7** [Homebrew/brew#8074]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I tried to install in linuxbrew from fresh server with `brew install gcc`

Was expecting to get gcc@10 according to the [formula](https://formulae.brew.sh/formula/gcc#default)

## What happened (include command output)

Instead I got gcc@5.5

```
robertwt7@Southern_Education:~/DotFiles/tmux$ gcc --version
gcc (Homebrew GCC 5.5.0_7) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Thus I can't install tmux etc

Am i missing something guys?

Can anyone please help?

Thanks

## Output of `brew config` and `brew doctor` commands

Brew doctor:
```
robertwt7@Southern_Education:~/DotFiles/tmux$ brew update
Already up-to-date.
robertwt7@Southern_Education:~/DotFiles/tmux$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gcc@9
```

Brew config:
```
robertwt7@Southern_Education:~/DotFiles/tmux$ brew config
HOMEBREW_VERSION: 2.4.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 13f0d4ad2b0773c01c5fdd5f8cba3e4f312c1c96
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: b9f0b496b967abee4c445529cb76b6c371605332
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_MAKE_JOBS: 1
CPU: single-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.15.0-106-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.4 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: N/A
glibc: N/A
gcc: 5.5.0_7
xorg: N/A
```

**Comment by gromgit** [comment]
GCC 10 on Linux is in the works: https://github.com/Homebrew/linuxbrew-core/pull/20241

In the meantime, consider using GCC 9 instead: `brew install gcc@9`.

Also, issues with specific formulae should be raised in [homebrew/core](https://github.com/Homebrew/homebrew-core/issues) instead.

**Comment by robertwt7** [comment]
Oh i didn't know that, sorry

Thanks for clarifying!

**Comment by iMichka** [comment]
I'll close this, as we are working on a solution: #20241
