### ISSUE TITLE
 Uninstalling node formula doesn't remove npm

### ISSUE THREAD

**Issue by ssw99** [Homebrew/brew#8078]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to completely uninstall 'node' formula because i wanted to.

## What happened (include command output)

I typed into terminal: ```brew uninstall node```. And pressed enter. (Basically uninstalled node formula.)
But npm was still accessible and I could use it if I install node from somewhere else. I think it's relevant to npm can be installed standalone. But I can't see it when I type ```brew list```.

Uninstall node output:

<details>
  <summary>Command output</summary>
  <pre>

Uninstalling /home/linuxbrew/.linuxbrew/Cellar/node/14.5.0... (4,658 files, 68.8MB)

  </pre>
</details>

## What you expected to happen

I was expecting to npm binary to be uninstalled too since it comes with node formula.

## Step-by-step reproduction instructions (by running `brew` commands)

brew install node
node -v : ```v14.5.0```
npm -v : ```6.14.5```
brew uninstall node
node -v : ```bash: node: command not found```
npm -v : ```/usr/bin/env: ‘node’: No such file or directory```
which npm : ```/home/linuxbrew/.linuxbrew/bin/npm```

## Output of `brew config` and `brew doctor` commands

<details>
  <summary>brew config output</summary>
  <pre>
  HOMEBREW_VERSION: 2.4.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 13f0d4ad2b0773c01c5fdd5f8cba3e4f312c1c96
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c480f5d152a01a7e21e8b980e71dfc48f0da8aad
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: N/A
Git: 2.20.1 => /bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 4.19.0-9-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 10 (buster) (buster)
Host glibc: 2.28
/usr/bin/gcc: 8.3.0
glibc: N/A
gcc: N/A
xorg: N/A

  </pre>
</details>

<details>
  <summary>brew doctor output</summary>
  <pre>
Your system is ready to brew.
  </pre>
</details>

**Comment by MikeMcQuaid** [comment]
This is intentional. We install `npm` separately but part of the `node` formula into `HOMEBREW_PREFIX` (as-per upstream recommendations).
