### ISSUE TITLE
More cases for cask name clash in two taps

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#8079]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

To install additional adoptopenjdk versions that is unavailable in HBC. As suggested by `adoptopenjdk` cask caveat:

```
==> Caveats
More versions are available in the AdoptOpenJDK tap:
  https://github.com/AdoptOpenJDK/homebrew-openjdk

  brew tap adoptopenjdk/openjdk
```

## What happened (include command output)

```
Error: Cask adoptopenjdk8 exists in multiple taps:
```

<details>
  <summary>Command output</summary>
  <pre>
```
brew cask info adoptopenjdk8
Error: Cask adoptopenjdk8 exists in multiple taps:
  homebrew/cask-versions/adoptopenjdk8
  adoptopenjdk/openjdk/adoptopenjdk8
```
  </pre>
</details>

## What you expected to happen

HBC shouldn't fail with error. It may track from which tap user installed cask and upgrade via this tap channel. Or maybe at least default to official repo and work with other taps by full name.

## Step-by-step reproduction instructions (by running `brew` commands)

```
brew tap AdoptOpenJDK/openjdk
brew cask info adoptopenjdk8
brew cask reinstall adoptopenjdk8
brew cask uninstall adoptopenjdk8
brew cask upgrade adoptopenjdk8
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config                      
HOMEBREW_VERSION: 2.4.8-105-g1b7c498
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1b7c498d354a098572cfcf06e18d54ff25c4c0b8
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 371fa3ff9a4f247f46fc7fcd4730b45fd475b466
Core tap last commit: 32 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Pe0Riapr8q/org.macosforge.xquartz:0
HOMEBREW_EDITOR: subl -w
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 6
CPU: hexa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 12.0 build 1200
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1, 1.8.0_262
macOS: 10.15.6-x86_64
CLT: 12.0.0.0.1.1595091463
Xcode: 12.0 => /Applications/Xcode_12_beta_3.app/Contents/Developer
XQuartz: 2.7.11 => /opt/X11

$  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libdiskmgt.1.dylib
  /usr/local/lib/libnvpair.1.dylib
  /usr/local/lib/libuutil.1.dylib
  /usr/local/lib/libzfs.2.dylib
  /usr/local/lib/libzfs_core.1.dylib
  /usr/local/lib/libzpool.1.dylib

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libdiskmgt.la
  /usr/local/lib/libnvpair.la
  /usr/local/lib/libuutil.la
  /usr/local/lib/libzfs.la
  /usr/local/lib/libzfs_core.la
  /usr/local/lib/libzpool.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libdiskmgt.a
  /usr/local/lib/libnvpair.a
  /usr/local/lib/libuutil.a
  /usr/local/lib/libzfs.a
  /usr/local/lib/libzfs_core.a
  /usr/local/lib/libzpool.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  hunspell
  mono
  bash-completion
  gnupg
</pre>

Started here: https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/106, reported by many users in this thread. @MikeMcQuaid asked to create a ticket here. But ticket was create only for brew cleanup, #6112.

**Comment by MikeMcQuaid** [comment]
> HBC shouldn't fail with error. It may track from which tap user installed cask and upgrade via this tap channel. Or maybe at least default to official repo and work with other taps by full name.

We'd accept a PR for this but it's going to be relatively involved and as-is we don't consider this a bug.
