### ISSUE TITLE
Can we automatically call upgrade the given package.

### ISSUE THREAD

**Issue by metacritical** [Homebrew/brew#8080]
Can we just automatically call `brew upgrade X` instead of issuing a message when some user calls 
`brew update pkg'
https://github.com/Homebrew/brew/blob/6049227c0a12bb5c817d7c2a2e8c05c52f51cd38/Library/Homebrew/cmd/update.sh#L324

**Comment by issyl0** [comment]
> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.

**Comment by metacritical** [comment]
Aah apologies didn't notice.

**Comment by MikeMcQuaid** [comment]
> Can we just automatically call `brew upgrade X`

No. Then `update` would need to handle all the flags that `upgrade` does.
