### ISSUE TITLE
`brew prune` command needed a deprecation cycle

### ISSUE THREAD

**Issue by andschwa** [Homebrew/brew#8096]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run the same command I have aliased and have used for half a decade, `brew cleanup && brew prune`.

## What happened (include command output)

```
Error: Unknown command: prune
```

## What you expected to happen

Pruning to take place of old downloaded formulae etc.

## Step-by-step reproduction instructions (by running `brew` commands)
```
$ brew prune
```

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.4.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 13f0d4ad2b0773c01c5fdd5f8cba3e4f312c1c96
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 437654be635d47353445cdd1b5461e6a660b0cdd
Core tap last commit: 21 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.feDSK8R9y7/org.macosforge.xquartz:0
HOMEBREW_EDITOR: ec
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 11.0.33.16
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.8
</pre>

I went to the `CHANGELOG.md` file expecting to at least find out what happened, it pointed me to the GitHub releases page, I Ctrl-F'd that for "prune" and found nothing. I spent a while digging and finally found https://github.com/Homebrew/brew/pull/5467. You can close this bug, I'm just trying to point out that this was an unfriendly breaking change that was hardly documented. Please next time consider the users who have used brew since it started, and at this point only need to use it on the rare occasion (because it's a great piece of software that generally just works!). When you remove a command, replace it with a stub that says what happened so I don't have to waste time wading through tens of thousands of issues and PRs to find out how to replace what I was doing (or keep a searchable changelog; seriously my searches of the repo code, changelog file, GitHub releases page, and docs.brew.sh all yielded nothing). It could have been as simple as:

```
$ brew prune
Sorry! The `prune` command has been deprecated (see #5467) and you can now just use `cleanup`.
```

That's it. It would have made everything so much easier. Sorry for being cranky!

P.S. I would have just left a comment on that PR and not had to open another issue, but it's locked.

**Comment by jonchang** [comment]
It was deprecated in 1.9.0, over a year ago. The deprecation was announced on the Homebrew blog: https://brew.sh/2019/01/09/homebrew-1.9.0/

**Comment by MikeMcQuaid** [comment]
> Pruning to take place of old downloaded formulae etc.

It literally never did this. 

> I'm just trying to point out that this was an unfriendly breaking change that was hardly documented.

It's unfriendly to have it so you only need to run one command rather than two? As @jonchang points out: it was documented as extensively as _any_ Homebrew breaking change is.

> When you remove a command, replace it with a stub that says what happened

We did.

> Sorry for being cranky!

If you find yourself apologising for being cranky at the end of a (long) issue: I'd recommend one of two options:

1) don't post the issue at all and rely on the fact that writing it made you feel better (I do this often)
2) delete the issue text and rewrite it in a form that isn't cranky



> I would have just left a comment on that PR and not had to open another issue, but it's locked.

This comment would have been equally unhelpful posted on that PR.
