### ISSUE TITLE
Implement missing `VCSDownloadStrategy#source_modified_time`  methods

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/brew#81]
Just a note here.

`DownloadStrategy#source_modified_time` is used to detect the latest modified time of source, which is an essential part for reproducible bottle. Among all kinds of `VCSDownloadStrategy`, so far only `GitDownloadStrategy#source_modified_time` has been implemented. Below is the list of methods need to be implemented.

- [x] `SubversionDownloadStrategy#source_modified_time`
- [x] `CVSDownloadStrategy#source_modified_time`
- [x] `MercurialDownloadStrategy#source_modified_time`
- [x] `BazaarDownloadStrategy#source_modified_time`
- [x] `FossilDownloadStrategy#source_modified_time`

**Comment by UniqMartin** [comment]
Closing as all missing implementations have been contributed by @vladshablinsky. Thanks a bunch!
