### ISSUE TITLE
brew upgrade attempts to upgrade unrequested cask packages

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/brew#8107]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I ran `brew upgrade` on a single package. Normally, I expect this to upgrade a single package as requested.

## What happened (include command output)

In addition to upgrading the single package I requested, it also proceeded to upgrade casks I hadn't requested to be upgraded.

<details>
  <summary>Command output</summary>
  <pre>
==> Upgrading 1 outdated package:
overmind 2.2.0
==> Upgrading overmind -> 2.2.0
==> Downloading https://homebrew.bintray.com/bottles/overmind-2.2.0.catalina.bottle.tar.gz
Already downloaded: /Users/mistydemeo/Library/Caches/Homebrew/downloads/d94bc7f1290122b018e76d52fbce4fdf7ed4f73274cbbd42c9dc9bc94f8a260d--overmind-2.2.0.catalina.bottle.tar.gz
==> Pouring overmind-2.2.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/overmind/2.2.0: 5 files, 5.2MB
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 8 outdated packages:
  </pre>
</details>

It looks like this broke in 210d22e8199f2482b28f550838a33cca47380ce4. I ran `git bisect` and determined this is the commit that introduced the bug.

## What you expected to happen

The single package is upgraded without also upgrading cask packages.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew upgrade foo`, where `foo` is any outdated package.

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.4.7-43-g210d22e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 210d22e8199f2482b28f550838a33cca47380ce4
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bef7bcc99b338fa99ada3081b4f4c0128b968990
Core tap last commit: 35 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BINTRAY_KEY: set
HOMEBREW_BINTRAY_USER: mistydemeo
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.1jC8EJ3XyZ/org.macosforge.xquartz:0
HOMEBREW_EDITOR: subl
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.1-zulu-11.2+3, 1.8.0_232-zulu-8.42.0.23, 1.8.0_102, 1.8.0_92, 1.8.0_77, 1.8.0_74
macOS: 10.15.5-x86_64
CLT: 1103.0.32.62
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unknown support status

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  ghc@8.0
  python@2
  go13
  portable-curl
  dirmngr
  pack
  wine
  ruby186
  minikube-binary
  elasticsearch@2.4
  gpg-agent
  phantomjs
  portable-ruby@2.3
  portable-ruby@2.4
  go@1.8
  portable-ruby@2.2
  toxiproxy
  isl@0.14
  wander
</pre>

**Comment by MikeMcQuaid** [comment]
CC @whoiswillma
