### ISSUE TITLE
Use "Squash and merge" for single-commit PRs on Homebrew/brew

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/brew#811]
I was looking at the recent commit history of Homebrew/brew and went :scream: due to the sheer number of merge commits:

![screen shot 2016-08-25 at 9 02 42 pm](https://cloud.githubusercontent.com/assets/4149852/17970437/35e7b0d0-6b09-11e6-84cf-e16d67832a31.png)

and understandably the graphical log is like a multi-laned highway with traffic weaving in and out:

<img width="1552" alt="screen shot 2016-08-25 at 9 03 22 pm" src="https://cloud.githubusercontent.com/assets/4149852/17970458/4eff3eda-6b09-11e6-9f60-fb118fa9b0ec.png">

I checked the nine PRs in the first screenshot and turns out six of them are single-commit, meaning that they could probably use "Squash and merge" without any downside (correct me if I'm wrong). The PR # could still be included at the end of the commit message for context. What about using "Squash and merge" more often?

**Comment by MikeMcQuaid** [comment]
> What about using "Squash and merge" more often?

It's preferable to have a single style of PR merging in this repo and using the merge commits in this way means it's easier to adopt a single, PR-only strategy. I'm aware of the graphical log but that's something that applies to pretty much any project using GitHub's merge button. For the taps that still rely on `brew pull` I'm not convinced that the button will ever see widespread usage but for core it's easier to adopt a single flow.

**Comment by zmwangx** [comment]
Okay, thanks for the explanation!

**Comment by zmwangx** [comment]
> Reading the history with git log --topo-order works well for me and if you add --no-merges you essentially get the same linear history that you would have gotten before we started to do merge commits. 

Good point, but that doesn't help when reading the history on GitHub web. Or maybe there's a query I can add to https://github.com/Homebrew/brew/commits/master that I'm unaware of (like adding `?w=1` to a diff URL)?

**Comment by MikeMcQuaid** [comment]
> Or maybe there's a query I can add to https://github.com/Homebrew/brew/commits/master that I'm unaware of (like adding ?w=1 to a diff URL)?

Pretty sure there is not.

What's the specific thing you're e.g. looking for but unable to find now that you could before?

**Comment by zmwangx** [comment]
> What's the specific thing you're e.g. looking for but unable to find now that you could before?

No. There's more distraction and less information on each page, that's all. Not a big deal.
