### ISSUE TITLE
Executing `brew --repo homebrew/core` causes bundler gems installation

### ISSUE THREAD

**Issue by dawidd6** [Homebrew/brew#8120]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run `brew --repo homebrew/core` on Linux.

This issue is also visible on CI:

Previous workflow run: https://github.com/Homebrew/homebrew-core/runs/918492860?check_suite_focus=true
Commit: https://github.com/Homebrew/homebrew-core/commit/8f0331d2b9e91e1e747b8f0c5f8f89b822044533
New workflow run after commit: https://github.com/Homebrew/homebrew-core/runs/918977289?check_suite_focus=true

Notice `Setup tap` step execution time.

Most likely caused by those lines: https://github.com/Homebrew/brew/blob/f797392dae823f0eef2b9f4806d55ab0fbdfd97e/Library/Homebrew/os/linux/elf.rb#L3-L6

## What happened (include command output)

`brew` installs bundler gems.

<details>
  <summary>Command output</summary>
  <pre>

  ➜  ~  brew --repo homebrew/core
Warning: the running version of Bundler (1.17.2) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/.........
Using concurrent-ruby 1.1.6
Using zeitwerk 2.4.0
Using ast 2.4.1
Using bindata 2.4.8
Using bundler 1.17.2
Using byebug 11.1.3
Using colorize 0.8.1
Using json 2.3.1
Using docile 1.3.2
Using simplecov-html 0.12.2
Using connection_pool 2.2.3
Using diff-lcs 1.4.4
Using unf_ext 0.0.7.7
Using hpricot 0.8.6
Using mime-types-data 3.2020.0512
Using net-http-digest_auth 1.4.1
Using mini_portile2 2.4.0
Using ntlm-http 0.1.1
Using webrobots 0.1.2
Using mustache 1.1.1
Using parallel 1.19.2
Using plist 3.5.0
Using rainbow 3.0.0
Using minitest 5.14.1
Using regexp_parser 1.7.1
Using rexml 3.2.4
Using rdiscount 2.2.0.1
Using ruby-progressbar 1.10.1
Using unicode-display_width 1.7.0
Using ruby-macho 2.2.0
Using i18n 1.8.5
Using elftools 1.1.2
Using parser 2.7.1.4
Using rspec-support 3.9.3
Using simplecov 0.18.5
Using unf 0.1.4
Using mime-types 3.3.1
Using nokogiri 1.10.10
Using parallel_tests 3.1.0
Using thread_safe 0.3.6
Using patchelf 1.1.1
Using ronn 0.7.3
Using rspec-core 3.9.2
Using rspec-mocks 3.9.1
Using net-http-persistent 4.0.0
Using rubocop-ast 0.2.0
Using domain_name 0.5.20190701
Using tzinfo 1.2.7
Fetching codecov 0.2.3
Using rspec-expectations 3.9.2
Using rubocop 0.88.0
Using http-cookie 1.0.3
Using activesupport 6.0.3.2
Using rspec-retry 0.6.2
Using rspec 3.9.0
Using rspec-its 1.3.0
Using rubocop-rspec 1.42.0
Using mechanize 2.7.6
Using rspec-wait 0.0.9
Using rubocop-performance 1.7.1
Installing codecov 0.2.3
Bundle complete! 18 Gemfile dependencies, 60 gems now installed.
Bundled gems are installed into `../linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle`
Removing codecov (0.2.2)
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
  </pre>
</details>

## What you expected to happen

To get the path for desired tap quickly.

## Step-by-step reproduction instructions (by running `brew` commands)

1. `brew --repo homebrew/core`

## Output of `brew config` and `brew doctor` commands

N/A, happens on CI too.

**Comment by dawidd6** [comment]
cc @rmNULL

**Comment by rmNULL** [comment]
@dawidd6  thanks for reporting.
ruby is conservative about the ways `using` can be invoked(e.g: it wont allow it be invoked inside a method).

a patch has been submitted upstream, once the gem is updated there we can remove this code,
or we'll figure out a workaround here (whichever happens first).
