### ISSUE TITLE
git 2.28.0 bottle exits with signal 4 on Linux

### ISSUE THREAD

**Issue by metcalfc** [Homebrew/brew#8121]
https://gist.github.com/92af5b5c6cdb3aa1d8a6fc84ff9dda49

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Add the necessary information from the linuxbrew-core issue template and recreate it there.

**Comment by metcalfc** [comment]
You should fix the tool. I followed the instructions with `brew gist-log` and this is where the tool sent the results.
