### ISSUE TITLE
late-July 2020 update causing "warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory"

### ISSUE THREAD

**Issue by jokeyrhyme** [Homebrew/brew#8124]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

- just updated brew and formula

## What happened (include command output)

- new warnings in brew's output (you can even see it in the output from `brew config` and `brew doctor` below

## What you expected to happen

- no unexpected warnings about locales

## Step-by-step reproduction instructions (by running `brew` commands)

- run `brew` or `brew config` or `brew doctor` or virtually any brew command

## Output of `brew config` and `brew doctor` commands

<pre>
❯ brew config
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 15: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
HOMEBREW_VERSION: 2.4.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: e6b066a3d9fc5435009428fcd2855fddf9b455c0
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 8f364d1e8f9c47e0879fa628720c682cd1ef3e8f
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: /usr/bin/nvim
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit unknown_0x17_0x8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.27.0 => /bin/git
Curl: 7.71.1 => /usr/bin/curl
Kernel: Linux 5.7.10-zen1-1-zen x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.31
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/usr/bin/gcc: 10.1.0
glibc: N/A
gcc: N/A
xorg: N/A

❯ brew doctor
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 15: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  guile@2
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/ron/.local/bin/ansible-config
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)

❯ localectl
   System Locale: LANG=en_AU.UTF-8
       VC Keymap: n/a
      X11 Layout: n/a

~
❯ localectl list-locales
en_AU.UTF-8
en_US.UTF-8

❯ locale -a
C
en_AU.utf8
en_US.utf8
POSIX

</pre>

**Comment by jokeyrhyme** [comment]
Looks like C.UTF-8 is missing from certain distributions including Arch (what I'm using) and nixOS:

https://github.com/electron-userland/electron-builder/issues/2340

https://github.com/signalapp/Signal-Desktop/issues/1829

**Comment by maxim-belkin** [comment]
Thanks for the report @jokeyrhyme!
The fix (#8072) will be included in the next Homebrew release -- it has been already merged into the main branch. You can switch to using the latest Homebrew/brew (rather than releases) by setting `HOMEBREW_DEVELOPER` env. variable to `1`.

**Comment by maxim-belkin** [comment]
I interpret the above emoji reactions as "it works now" :)
