### ISSUE TITLE
brew bottle build fail in apache tap saying "fatal: Not a git repository"

### ISSUE THREAD

**Issue by javian** [Homebrew/brew#813]
This job (and at least 2 other recent jobs)

https://bot.brew.sh/job/Homebrew%20Bottles/56729/console

fails with
```
git checkout -f master
fatal: Not a git repository: '/Users/brew/Jenkins/jobs/Homebrew Bottles/workspace/Library/Taps/homebrew/homebrew-apache/.git'
Error: Failure while executing: git checkout -f master
```

Can this be fixed ?

The original PR is here https://github.com/Homebrew/homebrew-apache/pull/121

**Comment by javian** [comment]
An example build is here https://bot.brew.sh/job/Homebrew%20Apache%20Pull%20Requests/69/ .

If the downstream job failed shouldn't it also create a failure in the upstream job ?

**Comment by DomT4** [comment]
Should be fixed now. Let me know otherwise.
