### ISSUE TITLE
Homebrew not installing on alpine

### ISSUE THREAD

**Issue by naumannt** [Homebrew/brew#8130]
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

**Brew never successfully installs, so these commands can not run.**

## What you were trying to do (and why)

I am trying to build a lightweight docker image to run a brew-managed software in a CI/CD-pipeline. For this, I use the most recent stable Alpine image (alpine:3.12.0).

## What happened (include command output)
When docker reaches the step to install homebrew, it fails.

<details>
  <summary>Command output</summary>
  <pre>

musl libc (x86_64)
Version 1.2.0
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
Homebrew requires Ruby 2.6 which was not found on your system.
Homebrew portable Ruby requires Glibc version 2.13 or newer,
and your Glibc version is too old.
See https://docs.brew.sh/Homebrew-on-Linux#requirements
Install Ruby 2.6 and add its location to your PATH.

  </pre>
</details>

## What you expected to happen

[This page](https://github.com/Linuxbrew/brew/wiki/Alpine-Linux) seems to be outdated - trying it pops up a message about linuxbrew no longer being it's own thing, instead now merged with the main homebrew installation script, also giving the command I am directed to run instead:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" \`

Note that the used Alpine image does include a recent version of ruby ([see here](https://pkgs.alpinelinux.org/package/v3.12/main/x86/ruby)).

## Step-by-step reproduction instructions (by running `brew` commands)
Dockerfile looks like this:

```
FROM alpine:3.12.0

\# install base dependencies
RUN apk update
RUN apk add bash coreutils curl file g++ grep git libc6-compat make ruby ruby-bigdecimal ruby-etc ruby-irb ruby-json ruby-test-unit sudo

\# install patchelf for homebrew installation
RUN wget http://nixos.org/releases/patchelf/patchelf-0.11/patchelf-0.11.tar.bz2
RUN tar xf patchelf-0.11.tar.bz2
RUN patchelf-0.11.20200609.d6b2a72/configure --disable-dependency-tracking --prefix="$HOME/.local"
RUN make install
RUN strip --strip-unneeded ~/.local/bin/patchelf
RUN gzip -9 ~/.local/share/man/man1/patchelf.1

\# install Homebrew
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" \
```

## Output of `brew config` and `brew doctor` commands
Homebrew never successfully installs, so these commands can not be ran.
<pre>
-
</pre>

**Comment by jonchang** [comment]
It's probably a combination of a `musl` vs `glibc` detection issue, and our version detection in the install script not working properly. We would accept a pull request to fix this behavior but I don't think any maintainers will be working on this immediately. As a workaround, you can also use one of the alternative install mechanisms listed in our documentation: https://docs.brew.sh/Homebrew-on-Linux#alternative-installation
