### ISSUE TITLE
Consider using either homebrew ignore/detach or pin for casks

### ISSUE THREAD

**Issue by GhostLyrics** [Homebrew/brew#8131]
_Yes, I have read https://github.com/Homebrew/homebrew-cask/issues/44914 and https://github.com/Homebrew/brew/issues/4898 but none of those provided an example of breaking existing workflows._

# A detailed description of the proposed feature

Allow some formulae that were installed to be ignored by `brew upgrade` - either by pinning or by completely making homebrew forget they were installed via its system.

# The motivation for the feature

I'm currently on v12 of `navicat-for-mysql`. v15 which has at some point become the default for homebrew will require my company to purchase a new license. I don't have plans to upgrade currently, but would still like to use `brew upgrade` (without arguments) for everything else I have installed.

With the new behaviour of `brew upgrade` now also upgrading casks, `brew upgrade` will always do the wrong thing for me - upgrade to a new major and essentially force a purchase.

# How the feature would be relevant to at least 90% of Homebrew users

Avoid upgrading a commercial cask to a new major version that requires a new, potentially unavailable license.

# What alternatives to the feature have been considered

- Detaching the app from homebrew inventory completely after initial installation

**Comment by claui** [comment]
@GhostLyrics If there’s no `navicat-for-mysql12` cask available on homebrew-cask-versions, you can create a custom tap and copy/paste that cask there (it’s documented and takes a few minutes) and you should be good to go.

In fact, migrating individual casks to a custom tap is straightforward enough that adding any pinning/detaching feature wouldn’t justify the development and maintenance resources needed for the feature.

Closing for now but feel free to comment for further discussion.

**Comment by GhostLyrics** [comment]
I created [my own custom tap](https://github.com/GhostLyrics/homebrew-custom) to solve my problem. It took me a while to find out that `extract` does not work with casks, which I had previously used to create a custom (local) tap for a different issue.

Thank you for your hints.
_Do you think it's worth submitting that as a PR to homebrew-cask-versions?_

**Comment by claui** [comment]
> Thank you for your hints.

You’re welcome @GhostLyrics!

> Do you think it's worth submitting that as a PR to homebrew-cask-versions?

I’d say it’s not. Looking at [cask analytics](https://formulae.brew.sh/api/analytics/cask-install/homebrew-cask/365d.json), even the latest version has less than two installs per day. Having a _N − 2_ version on cask-versions is probably not useful enough.

**Comment by gromgit** [comment]
> I created [my own custom tap](https://github.com/GhostLyrics/homebrew-custom) to solve my problem.

Side note: Custom taps (at this stage of Homebrew evolution, anyway) _need not be managed by Git at all_, much less require remote hosting. I personally did a `brew tap-new gromgit/test` some months back as a formula testbed tap. It resides only on my MacBook's SSD (and my backup drive), and it doesn't have a `.git` subdirectory. Homebrew still recognizes it as a tap, since it's in the right place with the right contents, but simply skips over it when it comes time to `brew update`.

So if anyone thinks "aw hell, I gotta maintain my own repos just for one tap?!?!", think again. Taps are ridiculously easy to deal with.
