### ISSUE TITLE
License showing up as Ruby array with info command

### ISSUE THREAD

**Issue by ankane** [Homebrew/brew#8132]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

```rb
brew info libtorch
```

## What happened (include command output)

```txt
libtorch: stable 1.5.1 (bottled)
Tensors and dynamic neural networks
https://pytorch.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libtorch.rb
License: ["BSD-3-Clause"]
```

## What you expected to happen

```
License: BSD-3-Clause
```

Likely related to https://github.com/Homebrew/brew/pull/7953

## Step-by-step reproduction instructions (by running `brew` commands)

```sh
brew info libtorch
```

## Output of `brew config` and `brew doctor` commands

Config

```sh
HOMEBREW_VERSION: 2.4.9-40-g7713e92
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7713e92fb01ed4e2581f1d63604e113564bbffdd
Last commit: 68 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bebc62aedd16946466e8c78989768969e8b9641c
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit icelake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 1103.0.32.62
Xcode: N/A
```

Doctor: N/A

**Comment by ankane** [comment]
Thanks @MikeMcQuaid!

**Comment by miccal** [comment]
Hi @MikeMcQuaid :wave:

I may have discovered another issue as a result of https://github.com/Homebrew/brew/pull/7953.

When running `brew bump-revision` on a formula with `license`, for example [`vim`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vim.rb), the command fails:
```
-bash-5.0.18- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (11) [> brew bump-revision vim --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb
Error: inreplace failed
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb:
  expected replacement of "license \"[\"Vim\"]\"\n" with "license \"[\"Vim\"]\"\n  revision 1\n"
/usr/local/Homebrew/Library/Homebrew/utils/inreplace.rb:43:in `inreplace'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-revision.rb:75:in `bump_revision'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```
while for a formula without a `license`, for example [`qt`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb), everything is fine:
```
-bash-5.0.18- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (11) [> brew bump-revision qt --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb
git commit --no-edit --verbose --message=qt: revision bump  -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb
[test f9d01766ac] qt: revision bump
 1 file changed, 1 insertion(+)
```
I believe [this line](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-revision.rb#L47) of `bump-revision.rb` needs updating, but I am afraid I am not sure what to?

Thank you.

**Comment by Rylan12** [comment]
Good find, @miccal! Thanks for pointing it out. I opened a PR to fix this and another `bump-revision` issue in #8139

**Comment by miccal** [comment]
Thanks @Rylan12, as always.
