### ISSUE TITLE
installing one package results in unrequested upgrade of many others

### ISSUE THREAD

**Issue by masukomi** [Homebrew/brew#8136]
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew config` and `brew doctor` and included their output with your issue?

The above checks are lies because while this issue is reproducable it's being reproduced across multiple people's devices and (as you'll see) it's a one-way thing so you can't do it twice unless you happen to know what's causing it and can reset your system to that state. 

The prerequisites seem to be having a system with 1+ packages that could be upgraded and then trying to install something new.

## What you were trying to do (and why)

install pygments

a coworker experienced the same thing when attempting to install git. 

## What happened (include command output)

pygments installation:

downloaded and built all the dependencies for pygments. Installed pygments Then what follows in the details below. I don't know if _any_ of these packages listed have _anything_ to do with pygments but i'm confident that many of them are wholly unrelated: for example syntax highlighting doesn't require an email client (neomutt) an image manipulator (imagemagick) amazon's cli (awscli) a commercial snippets manager (snipline) etc....

<details>
  <summary>Command output</summary>
  <pre>
(expected output about installing the dependencies of pygments)
....
==> Installing pygments
==> Pouring pygments-2.6.1.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/pygments/2.6.1: 796 files, 9.4MB
==> Upgrading 57 dependents:
awscli 2.0.7 -> 2.0.34, awscli 2.0.7 -> 2.0.34, awscli 2.0.7 -> 2.0.34, crystal 0.34.0 -> 0.35.1_1, freetds 1.1.32 -> 1.2.3, gdk-pixbuf 2.40.0 -> 2.40.0_1, gdk-pixbuf 2.40.0 -> 2.40.0_1, gdk-pixbuf 2.40.0 -> 2.40.0_1, glib 2.64.2 -> 2.64.4, glib 2.64.2 -> 2.64.4, glib 2.64.2 -> 2.64.4, gnupg 2.2.20 -> 2.2.21, gnutls 3.6.12 -> 3.6.14, gpgme 1.13.1 -> 1.14.0, graphviz 2.42.3 -> 2.44.1, graphviz 2.42.3 -> 2.44.1, graphviz 2.42.3 -> 2.44.1, harfbuzz 2.6.4 -> 2.6.8, harfbuzz 2.6.4 -> 2.6.8, harfbuzz 2.6.4 -> 2.6.8, fontforge 20190801_1 -> 20200314_1, fontforge 20190801_1 -> 20200314_1, fontforge 20190801_1 -> 20200314_1, jrnl 2.2_1 -> 2.4.4, jrnl 2.2_1 -> 2.4.4, jrnl 2.2_1 -> 2.4.4, krb5 1.18 -> 1.18.2, libevent 2.1.11_1 -> 2.1.12, libgit2 0.28.4 -> 1.0.1, libheif 1.6.2_1 -> 1.7.0, libheif 1.6.2_1 -> 1.7.0, libheif 1.6.2_1 -> 1.7.0, libpq 12.2_1 -> 12.3, librsvg 2.48.3 -> 2.48.8, librsvg 2.48.3 -> 2.48.8, librsvg 2.48.3 -> 2.48.8, msmtp 1.8.7 -> 1.8.11, mysql 8.0.19 -> 8.0.21, notmuch 0.29.3 -> 0.30, notmuch 0.29.3 -> 0.30, notmuch 0.29.3 -> 0.30, neomutt 20191207 -> 20200626, neomutt 20191207 -> 20200626, neomutt 20191207 -> 20200626, nushell 0.12.0 -> 0.17.0, postgresql 12.2 -> 12.3_4, shared-mime-info 1.15 -> 2.0, shared-mime-info 1.15 -> 2.0, shared-mime-info 1.15 -> 2.0, imagemagick 7.0.9-16 -> 7.0.10-24, imagemagick 7.0.9-16 -> 7.0.10-24, imagemagick 7.0.9-16 -> 7.0.10-24, snipline/snipline/snipcli 0.3.3 -> 0.4.0, unbound 1.10.0 -> 1.10.1, xapian 1.4.15 -> 1.4.16, xapian 1.4.15 -> 1.4.16, xapian 1.4.15 -> 1.4.16

  </pre>
</details>

the person who installed git had similar results but didn't capture the output.

## What you expected to happen
I expected it to install pygments and its dependencies, but _not_ upgrade other packages that i may have been using specific versions without any user input. 

In addition to taking a _very long time_ (over an hour now). The unexpected upgrade has borked a number of other commands that were built against older versions of dlls that are now missing. I have no idea how long I'll be stumbling over the consequences of this.

## Step-by-step reproduction instructions (by running `brew` commands)

brew install pygments

this may be limited to fresh installs of a thing. I don't know. 

## Output of `brew config` and `brew doctor` commands

<pre>
[18/45] ~  brew config
HOMEBREW_VERSION: 2.4.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: e6b066a3d9fc5435009428fcd2855fddf9b455c0
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 673ca889006f5a94f429afe06d185796093dc922
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: mvim
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: N/A
Xcode: 11.6

9 EDT: . | . . . . . . . . :6 PDT
[18/45] ~  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  python@2
  mongodb
  contacts2

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  protobuf@3.7

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2
  emacs-plus
  python
  emacs
  freetds
  imagemagick
  gnupg
Error: unknown or unsupported macOS version: :mountain_lion

</pre>

**Comment by jonchang** [comment]
See my explanation in https://github.com/Homebrew/brew/issues/8092#issuecomment-663988984, but substitute the package names for the ones you're using. This is not a bug in Homebrew.

**Comment by masukomi** [comment]
Considering there have now been >=2 tickets on this, and there will probably be more, and it's acknowledged as "surprising" behavior wouldn't it make sense to alter homebrew so that after figuring out what the tree of things that would need to be upgraded it would say something like 

> In addition to installing XXX and its dependencies, we'll need to upgrade the following installed packages which have overlapping dependencies. Is that ok? [y/n]:

Because if I'd had any clue that I'd be breaking my terminal  prompt and pegging my computer's CPU for over an hour i would have said "you know what? I can install this later."

**Comment by jonchang** [comment]
We would accept a pull request to improve the messaging, as I said in the linked comment. Homebrew commands do not prompt the user so a pull request to add that wouldn't be accepted.

**Comment by iMichka** [comment]
Homebrew does not ask with Y/N in general. We never implemented logic asking but prefer the default behaviour. We make make the better choice for 99% of our users.

Also, if you respond NO to the prompt, this also means we just stop install XXX too, as we can only do that if the other deps are updated.

You could use `brew outdated` to know upfront what is likely to be updated, before running any upgrade/install command.

**Comment by MikeMcQuaid** [comment]
Note: we cannot adequately detect exactly what will need to be updated because some of it is based on linkage and your individual configuration of what's installed.
