### ISSUE TITLE
could not found icu-i18n on macos

### ISSUE THREAD

**Issue by qiyongxiao** [Homebrew/brew#8148]
# Build samba and samba-ldb program,tips me 
```
Mandatory library 'icui18n' not found for functions '<class 'list'>'
```
I could not found it with ```brew search```,will added it?

**Comment by claui** [comment]
Please fill out the issue template so there’s enough information that we can actually help you.

**Comment by qiyongxiao** [comment]
Oh, close the issue fo quickly?

**Comment by gromgit** [comment]
The issue template, which you chose to delete, starts with the following:
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

**Comment by claui** [comment]
> Oh, close the issue fo quickly?

@qiyongxiao We’ll consider reopening the issue if all the requested information is added.
Or feel free to file a new issue, if that’s easier.
