### ISSUE TITLE
Regression in #8144: HOMEBREW_VERBOSE and HOMEBREW_DEBUG no longer respected

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/brew#8168]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

---

#8144, or specifically d4c2ffd7056088a76055ae04d7107bcda0a4acba, seems to introduce a regression where `HOMEBREW_VERBOSE` and `HOMEBREW_DEBUG` are no longer respected (at least not for commands with `switch :verbose` and `switch :debug` removed, which is probably all of the relevant ones?). I always have `HOMEBREW_VERBOSE` on, but now commands don't print verbosely unless I manually add `--verbose`.

I haven't got time to inspect what's in #8144, which is <s>pretty huge</s> okay actually not huge, so can't exactly say whether it's intentional, but a lack of man page change seems to indicate it's not. If it is: this is not a welcome change, not for me at least.

CC @reitermarkus, and @MikeMcQuaid who approved #8144.

## What you were trying to do (and why)

Run `brew ls ffmpeg` with `HOMEBREW_VERBOSE` set.

## What happened (include command output)

`HOMEBREW_VERBOSE` is ignored, collapsing the full list of files into a bunch of `/path/to/directory (<N> files)`.

<details>
<summary>Command output</summary>
<pre>
$ brew ls ffmpeg
/usr/local/Cellar/ffmpeg/4.3.1/bin/aviocat
/usr/local/Cellar/ffmpeg/4.3.1/bin/bisect-create
/usr/local/Cellar/ffmpeg/4.3.1/bin/cl2c
/usr/local/Cellar/ffmpeg/4.3.1/bin/clean-diff
/usr/local/Cellar/ffmpeg/4.3.1/bin/crypto_bench
/usr/local/Cellar/ffmpeg/4.3.1/bin/cws2fws
/usr/local/Cellar/ffmpeg/4.3.1/bin/dvd2concat
/usr/local/Cellar/ffmpeg/4.3.1/bin/ffescape
/usr/local/Cellar/ffmpeg/4.3.1/bin/ffeval
/usr/local/Cellar/ffmpeg/4.3.1/bin/ffhash
/usr/local/Cellar/ffmpeg/4.3.1/bin/ffmpeg
/usr/local/Cellar/ffmpeg/4.3.1/bin/ffplay
/usr/local/Cellar/ffmpeg/4.3.1/bin/ffprobe
/usr/local/Cellar/ffmpeg/4.3.1/bin/fourcc2pixfmt
/usr/local/Cellar/ffmpeg/4.3.1/bin/gen-rc
/usr/local/Cellar/ffmpeg/4.3.1/bin/graph2dot
/usr/local/Cellar/ffmpeg/4.3.1/bin/ismindex
/usr/local/Cellar/ffmpeg/4.3.1/bin/libav-merge-next-commit
/usr/local/Cellar/ffmpeg/4.3.1/bin/loudnorm.rb
/usr/local/Cellar/ffmpeg/4.3.1/bin/make_chlayout_test
/usr/local/Cellar/ffmpeg/4.3.1/bin/missing_codec_desc
/usr/local/Cellar/ffmpeg/4.3.1/bin/murge
/usr/local/Cellar/ffmpeg/4.3.1/bin/normalize.py
/usr/local/Cellar/ffmpeg/4.3.1/bin/patcheck
/usr/local/Cellar/ffmpeg/4.3.1/bin/pktdumper
/usr/local/Cellar/ffmpeg/4.3.1/bin/plotframes
/usr/local/Cellar/ffmpeg/4.3.1/bin/probetest
/usr/local/Cellar/ffmpeg/4.3.1/bin/qt-faststart
/usr/local/Cellar/ffmpeg/4.3.1/bin/seek_print
/usr/local/Cellar/ffmpeg/4.3.1/bin/sidxindex
/usr/local/Cellar/ffmpeg/4.3.1/bin/target_dec_fate.sh
/usr/local/Cellar/ffmpeg/4.3.1/bin/trasher
/usr/local/Cellar/ffmpeg/4.3.1/bin/uncoded_frame
/usr/local/Cellar/ffmpeg/4.3.1/bin/unwrap-diff
/usr/local/Cellar/ffmpeg/4.3.1/bin/venc_data_dump
/usr/local/Cellar/ffmpeg/4.3.1/bin/zmqshell.py
/usr/local/Cellar/ffmpeg/4.3.1/include/libavcodec/ (24 files)
/usr/local/Cellar/ffmpeg/4.3.1/include/libavdevice/ (2 files)
/usr/local/Cellar/ffmpeg/4.3.1/include/libavfilter/ (4 files)
/usr/local/Cellar/ffmpeg/4.3.1/include/libavformat/ (3 files)
/usr/local/Cellar/ffmpeg/4.3.1/include/libavresample/ (2 files)
/usr/local/Cellar/ffmpeg/4.3.1/include/libavutil/ (86 files)
/usr/local/Cellar/ffmpeg/4.3.1/include/libpostproc/ (2 files)
/usr/local/Cellar/ffmpeg/4.3.1/include/libswresample/ (2 files)
/usr/local/Cellar/ffmpeg/4.3.1/include/libswscale/ (2 files)
/usr/local/Cellar/ffmpeg/4.3.1/lib/libavcodec.58.91.100.dylib
/usr/local/Cellar/ffmpeg/4.3.1/lib/libavdevice.58.10.100.dylib
/usr/local/Cellar/ffmpeg/4.3.1/lib/libavfilter.7.85.100.dylib
/usr/local/Cellar/ffmpeg/4.3.1/lib/libavformat.58.45.100.dylib
/usr/local/Cellar/ffmpeg/4.3.1/lib/libavresample.4.0.0.dylib
/usr/local/Cellar/ffmpeg/4.3.1/lib/libavutil.56.51.100.dylib
/usr/local/Cellar/ffmpeg/4.3.1/lib/libpostproc.55.7.100.dylib
/usr/local/Cellar/ffmpeg/4.3.1/lib/libswresample.3.7.100.dylib
/usr/local/Cellar/ffmpeg/4.3.1/lib/libswscale.5.7.100.dylib
/usr/local/Cellar/ffmpeg/4.3.1/lib/pkgconfig/ (9 files)
/usr/local/Cellar/ffmpeg/4.3.1/lib/ (27 other files)
/usr/local/Cellar/ffmpeg/4.3.1/share/doc/ (30 files)
/usr/local/Cellar/ffmpeg/4.3.1/share/ffmpeg/ (34 files)
/usr/local/Cellar/ffmpeg/4.3.1/share/man/ (22 files)
</pre>
</details>

## What you expected to happen

`HOMEBREW_VERBOSE` is respected, `brew ls ffmpeg` prints the full list of files just like `brew ls --verbose ffmpeg`.

## Step-by-step reproduction instructions (by running `brew` commands)

```
HOMEBREW_VERBOSE=1 brew ls ffmpeg
```

## Output of `brew config` and `brew doctor` commands

https://gist.github.com/zmwangx/1893709e4ff6e0aef260c04d4739cd8f

**Comment by zmwangx** [comment]
Okay the problem is more serious than I thought. Not only `HOMEBREW_VERBOSE` has no effect, even `--verbose` isn't behaving correctly.

```console
$ brew install -s --verbose ffmpeg  # Building an old version of FFmpeg from source
==> Downloading https://ffmpeg.org/releases/ffmpeg-4.2.tar.xz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.4.9-146-gaada3f6-dirty\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.6\)\ curl/7.64.1 --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/zmwang/Library/Caches/Homebrew/downloads/aba395a03327f94b56832e2fa29aee784ac7e3d59298e87fa20cba3bc3c75b1c--ffmpeg-4.2.tar.xz.incomplete https://ffmpeg.org/releases/ffmpeg-4.2.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8875k  100 8875k    0     0   638k      0  0:00:13  0:00:13 --:--:--  632k
==> Verifying aba395a03327f94b56832e2fa29aee784ac7e3d59298e87fa20cba3bc3c75b1c--ffmpeg-4.2.tar.xz checksum
Warning: Cannot verify integrity of aba395a03327f94b56832e2fa29aee784ac7e3d59298e87fa20cba3bc3c75b1c--ffmpeg-4.2.tar.xz
A checksum was not provided for this resource.
For your reference the SHA-256 is: 023f10831a97ad93d798f53a3640e55cd564abfeba807ecbe8524dac4fedecd5
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200801-47750-fgjpk6.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ffmpeg.rb --verbose
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/4.2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host
==> make install
==> make alltools
==> Cleaning
==> Finishing up
ln -s ../Cellar/ffmpeg/4.2/bin/aviocat aviocat
ln -s ../Cellar/ffmpeg/4.2/bin/bisect-create bisect-create
...
```

Note how the output of all build steps are suppressed despite `--verbose`.

**Comment by fxcoudert** [comment]
Also: `brew install --debug` is silently ignored. When `brew install whatever --debug` is run, upon build failure there will be no menu asking you what to do, it will error out.

**Comment by Rylan12** [comment]
`git bisect` indicates that the first bad commit for both the `HOMEBREW_VERBOSE` issue and the `--debug` issue is https://github.com/Homebrew/brew/commit/d4c2ffd7056088a76055ae04d7107bcda0a4acba

If I had to guess, it would be:

```ruby
Homebrew.args = Homebrew::CLI::Parser.new.parse(ignore_invalid_options: true)
```

**Comment by Bo98** [comment]
The two issues are separate. I've got a fix for the env issue and am looking for where the second issue is.

**Comment by Rylan12** [comment]
I think it's that `debug?` should be `@debug` in [`formula_installer`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_installer.rb)

**Comment by Bo98** [comment]
No, `mode_attr_accessor` should handle that.

I'll send a PR in a moment.
