### ISSUE TITLE
brew list --pinned report many package not pinned.

### ISSUE THREAD

**Issue by Bruno21** [Homebrew/brew#8170]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the restquested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

List all pinned packages
(actually I don't have any pinned package)

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
~/Documents/shell_scripts master*
❯ brew list | wc
     242     242    1913

~/Documents/shell_scripts master*
❯ brew list --pinned | wc
     242     485    3559

 ~/Documents/shell_scripts master*
❯ brew list --pinned
annie 0.10.3
antibody 6.1.0
.../...

~/Documents/shell_scripts master*
❯ brew unpin antibody
Warning: antibody not pinned

  </pre>
</details>

## What you expected to happen

Yesterday, the  brew list --pinned commands works as expected.

## Output of `brew config` and `brew doctor` commands

<pre>
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  spdylay

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php
  handbrake
  md5sha1sum

❯ brew config
HOMEBREW_VERSION: 2.4.9-148-gad4d2ac
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad4d2ac1daac76266943a1bd0d51c6d8336c32a3
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ff002fa4d51cb0e0537a4e836fb04da720d4ca3a
Core tap last commit: 28 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.4baiVKMb8u/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.1
macOS: 10.15.6-x86_64
CLT: 1103.0.32.62
Xcode: 11.6
XQuartz: 2.7.11 => /opt/X11
</pre>

**Comment by Rylan12** [comment]
Thanks for bringing this up, @Bruno21!

I have a fix ready in #8171
