### ISSUE TITLE
`brew deps --installed` does not work without formula argument

### ISSUE THREAD

**Issue by max-ae** [Homebrew/brew#8195]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I tried to run the external command [brew graph](https://github.com/martido/homebrew-graph).
It failed because `brew deps --installed` does not work without a formula argument anymore. I believe this has to to with #8144 and #8174 did not fix this.

## What happened (include command output)

`brew deps --installed` threw error for missing argument

<details>
  <summary>Command output</summary>
  <pre>

❯ brew deps --installed
Error: missing keyword: args
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/deps.rb:167:in `puts_deps'

/usr/local/Homebrew/Library/Homebrew/cmd/deps.rb:99:in `deps'

/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `\<main\>'
  </pre>
</details>

## What you expected to happen

`brew deps --installed` to list all dependencies for all installed formulae

## Step-by-step reproduction instructions (by running `brew` commands)

`brew deps --installed`

## Output of `brew config` and `brew doctor` commands

<pre>
❯ brew doctor
Your system is ready to brew.
❯ brew config
HOMEBREW_VERSION: 2.4.9-184-g197c466
ORIGIN: https://github.com/Homebrew/brew
HEAD: 197c4666cf1b53fa3e59d97347fefac73bf88a98
Last commit: 52 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f3a040d03cc4ecb0b874891aa8def551d445ed09
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ZOj5tmyj2K/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2, 13.0.1, 1.8.0_265
macOS: 10.15.6-x86_64
CLT: 1103.0.32.62
Xcode: 11.6
XQuartz: 2.7.11 => /opt/X11</pre>

**Comment by Rylan12** [comment]
Thanks for reporting, @max-ae! Fix should be in #8200
