### ISSUE TITLE
Misleading error messages for misnamed formula class

### ISSUE THREAD

**Issue by The-Compiler** [Homebrew/brew#82]
I'm trying to write my own first formula, so it's entirely possible I'm doing something wrong here, but the error I'm getting from brew is definitely confusing.

I'm running an updated homebrew:

```
Flos-Mac-mini:~ flo$ brew update 
Already up-to-date.
```

```
Flos-Mac-mini:~ flo$ brew --version
Homebrew 0.9.9 (git revision a8ed0; last commit 2016-04-13)
Homebrew/homebrew-core (git revision 4dbe; last commit 2016-04-13)
```

`brew doctor` is happy as well:

```
Flos-Mac-mini:~ flo$ brew doctor
Your system is ready to brew.
```

I'm copying my formula to the right place:

```
Flos-Mac-mini:~ flo$ cp qt5-webkit/qt5-webkit.rb /usr/local/Library/Formula/
Flos-Mac-mini:~ flo$
```

but installing it fails - it seems the formula gets found, but then brew decides it didn't find it anyways? :wink:

```
Flos-Mac-mini:~ flo$ brew install --debug --verbose qt5-webkit
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/qt5-webkit.rb
Error: No available formula with the name "qt5-webkit" 
==> Searching for similarly named formulae...
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/qt5-webkit.rb
This similarly named formula was found:
qt5-webkit
To install it, run:
  brew install qt5-webkit
==> Searching taps...
Error: No formulae found in taps.
```

My formula:

```ruby
class Qt5WebKit < Formula
  desc "Version 5 of the Qt framework - QtWebKit module"
  homepage "https://www.qt.io/"
  url "http://download.qt.io/community_releases/5.6/5.6.0/qtwebkit-opensource-src-5.6.0.tar.xz"
  mirror "https://www.mirrorservice.org/sites/download.qt-project.org/community_releases/5.6/5.6.0/qtwebkit-opensource-src-5.6.0.tar.xz"
  sha256 "9ca72373841f3a868a7bcc696956cdb0ad7f5e678c693659f6f0b919fdd16dfe"

  head "https://code.qt.io/qt/qtwebkit.git", :branch => "5.6", :shallow => false
 
  # OS X 10.7 Lion is still supported in Qt 5.5, but is no longer a reference
  # configuration and thus untested in practice. Builds on OS X 10.7 have been
  # reported to fail: <https://github.com/Homebrew/homebrew/issues/45284>.
  depends_on :macos => :mountain_lion
 
  depends_on "qt5"
  depends_on :xcode => :build
 
  def install
    system "qmake"
    system "make"
    system "make", "INSTALL_ROOT=#{prefix}" "install"
  end
 
  test do
    (testpath/"hello.pro").write <<-EOS.undent
      QT       += core webkit
      QT       -= gui
      TARGET = hello
      CONFIG   += console
      CONFIG   -= app_bundle
      TEMPLATE = app
      SOURCES += main.cpp
    EOS
 
    (testpath/"main.cpp").write <<-EOS.undent
      #include <QCoreApplication>
      #include <QDebug>
      #include <QWebView>
 
      int main(int argc, char *argv[])
      {
      }
    EOS
 
    system bin/"qmake", testpath/"hello.pro"
    system "make"
    assert File.exist?("hello")
    assert File.exist?("main.o")
  end
end
```

**Comment by apjanke** [comment]
Hi Florian,

On 4/13/16 10:00 AM, Florian Bruhin wrote:
>
> I'm trying to write my own first formula, so it's entirely possible 
> I'm doing something wrong here, but the error I'm getting from brew is 
> definitely confusing.
>
> |[...snip...] |
>
> but installing it fails - it seems the formula gets found, but then 
> brew decides it didn't find it anyways? :wink:
>
> |Flos-Mac-mini:~ flo$ brew install --debug --verbose qt5-webkit 
> /usr/local/Library/brew.rb (Formulary::FormulaLoader): loading 
> /usr/local/Library/Taps/homebrew/homebrew-core/Formula/qt5-webkit.rb 
> Error: No available formula with the name "qt5-webkit" ==> Searching 
> for similarly named formulae... /usr/local/Library/brew.rb 
> (Formulary::FormulaLoader): loading 
> /usr/local/Library/Taps/homebrew/homebrew-core/Formula/qt5-webkit.rb 
> This similarly named formula was found: qt5-webkit To install it, run: 
> brew install qt5-webkit ==> Searching taps... Error: No formulae found 
> in taps. |
>
> My formula:
>
> class  Qt5WebKit< Formula
>    desc"Version 5 of the Qt framework - QtWebKit module"
>    homepage"https://www.qt.io/"
>    [...snip...]

You're very close. Homebrew is very strict about the class naming 
pattern. `qt5-webkit` needs to become `Qt5Webkit`, not `Qt5WebKit`.
Only the first letter and letters immediately following a dash get 
capitalized.

The misleading error messages are an issue with brew. We'll try to do 
something about that. https://github.com/Homebrew/brew/issues/82

Cheers,
Andrew

**Comment by UniqMartin** [comment]
What @apjanke pointed out is probably the main issue.

> `system "make", "INSTALL_ROOT=#{prefix}" "install"`

There's also a missing comma in this line. Might be another reason why the formula file is found, but fails to load. You can check with `brew readall` for syntax errors in formulae. Running `brew style --strict --online qt5-webkit` is also a good idea to check that the formula is in a decent shape.

**Comment by The-Compiler** [comment]
Thanks a lot for the quick help and the helpful hints! :+1:

@UniqMartin getting a bit off-topic here, but do you think I should submit this formula after it's polished and working, or keep it for myself? After all, there was an official source release for QtWebKit with Qt 5.6, and there are chances it'll be [continued to be maintained](https://github.com/annulen/webkit) by the community in the future.

**Comment by UniqMartin** [comment]
> […] do you think I should submit this formula after it's polished and working, or keep it for myself?

I've seen some demand for this, so it would be nice of you to [put it in a tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) where others can find it. I'm not sure if we want to make that an official formula, though, as I believe our stance is that QtWebKit is basically broken and insecure, and it should die sooner than later. Including it could seem like an endorsement we don't want to commit to. @DomT4 and @mikemcquaid also might have an opinion.

**Comment by mikemcquaid** [comment]
> Including it could seem like an endorsement we don't want to commit to. @DomT4 and @mikemcquaid also might have an opinion.

Yeh, agreed.

**Comment by DomT4** [comment]
> as I believe our stance is that QtWebKit is basically broken and insecure, and it should die sooner than later. Including it could seem like an endorsement we don't want to commit to.

:+1: from me on that as well. A tap would be useful though, I agree.

**Comment by mikemcquaid** [comment]
Is the community QtWebkit using newer versions and e.g. accepting security updates? If so, we'd consider accepting it. Otherwise, as @UniqMartin said.

Closing this as it's not a Homebrew issue but happy to help further if you have questions.

**Comment by The-Compiler** [comment]
> Is the community QtWebkit using newer versions and e.g. accepting security updates? If so, we'd consider accepting it. 

It's still heavily work in progress, but I think that's the goal - having a QtWebKit based on an updated upstream WebKit.

> Closing this as it's not a Homebrew issue

How isn't it? Surely Homebrew could/should tell me something more useful than "qt5-webkit was not found, but qt5-webkit was found instead, try running the command you did just run"? :wink:

> but happy to help further if you have questions

Thank you and everyone for being so open and helpful, I really appreciate it! :+1:

**Comment by UniqMartin** [comment]
>> Closing this as it's not a Homebrew issue
>
> How isn't it? Surely Homebrew could/should tell me something more useful than "qt5-webkit was not found, but qt5-webkit was found instead, try running the command you did just run"? :wink:

You can find my attempt to improve the error message for this case in PR #101. Feedback welcome!
