### ISSUE TITLE
Command like brew pin but for preventing uninstall

### ISSUE THREAD

**Issue by SeekingMeaning** [Homebrew/brew#8206]
# A detailed description of the proposed feature

Allow users to run a command (or edit a file, similar to `.brew_livecheck_watchlist`) that will add formulae to a block-list; these formulae can only be uninstalled by running `brew uninstall --force`

# The motivation for the feature

Most users (myself included) probably have some packages that they want to always have installed (and keep updated). Adding this feature would prevent such packages from being accidentally uninstalled.

# How the feature would be relevant to at least 90% of Homebrew users

See above

# What alternatives to the feature have been considered

Alternatively, this could be an option for `brew pin` such as `--keep-updated`

**Comment by gromgit** [comment]
Hmmm. I occasionally run into the same problem, though I always discover it after the fact and have to reinstall the missing formulae.

How about `brew install --sticky` to literally set the sticky bit on the formula's `INSTALL_RECEIPT.json`, and `brew uninstall` to skip such "sticky" formulae?

**Comment by MikeMcQuaid** [comment]
This is the first request I've heard for this. I'd recommend soliciting feedback for at least 24h before opening PRs (to save you work).

I can't see the motivation for this. If you accidentally uninstall a package: you can reinstall it again almost immediately, no? 

I definitely can't see anywhere near the majority of users using this.

**Comment by reitermarkus** [comment]
The only edge case I could personally see this being used is so I don't accidentally `brew uninstall fish` and break my shell. This has not happened to me yet. Even if it did, I could easily install it again by temporarily using another shell.

**Comment by SeekingMeaning** [comment]
I often forget that I don't count as a normal user 😅
