### ISSUE TITLE
How to show progress bar for no-tty?

### ISSUE THREAD

**Issue by Whirlwind** [Homebrew/brew#8252]
I have a script environment to run the `brew cask install xx`, but I could not get the download progress bar of curl.
```
 ==> Downloading https://xxx
```

I check the source code, and I found the cask loader:
https://github.com/Homebrew/brew/blob/13a249a426c7e7189bd3211d10764220773ebfc0/Library/Homebrew/cask/cask_loader.rb#L103
and the `curl_download`:
https://github.com/Homebrew/brew/blob/56ed27af15dafb8e8f2e884656ccad546d784482/Library/Homebrew/utils/curl.rb#L84

So, the curl will not show output when the `show_output` is false and `$stdout.tty?` is false:
https://github.com/Homebrew/brew/blob/56ed27af15dafb8e8f2e884656ccad546d784482/Library/Homebrew/utils/curl.rb#L35-L40

How do I show the output when it is not a tty?

**Comment by maxim-belkin** [comment]
> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

Please always fill out our issue template.

The behavior you describe is not a bug. If you'd like to propose a change -- please do so using a feature template. You'll have to justify how this feature is relevant to 90% users.

Thank you!

**Comment by gromgit** [comment]
And if it can't be justified as relevant to 90% users, you could ask for help on the Homebrew Discourse (option 4 on the New Issue menu).

**Comment by MikeMcQuaid** [comment]
> How do I show the output when it is not a tty?

You do not. This is intentional behaviour, sorry.
