### ISSUE TITLE
ability to combine command line options

### ISSUE THREAD

**Issue by zachvalenta** [Homebrew/brew#8257]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

# A detailed description of the proposed feature

ability to combine command line options

# The motivation for the feature

I want to view packages:

* with version info 
* sorted by most recently modified

```sh
brew ls --versions -t
```

# How the feature would be relevant to at least 90% of Homebrew users

Keeping track of what packages you have installed at a particular time.

I've been doing this by running `brew leaves > $DOTFILES_DIR/pkg-brew.txt` after installing a new package, but more info and ordering would be helpful esp. when debugging.

# What alternatives to the feature have been considered

I queried opened issues and didn't see others that replicated this request.

**Comment by MikeMcQuaid** [comment]
> ability to combine command line options

This isn't detailed, I don't understand what this means.


> Keeping track of what packages you have installed at a particular time.

`brew bundle dump` or `brew ls --versions` if you want versions. `brew info --installed` if you want much more information.

**Comment by zachvalenta** [comment]
Meaning, I want to combine `brew ls --versions` (list detailed info on packages) with `brew ls -t` (list packages in order of most recently updated). Akin to how one can combine GNU coreutils `ls -l` and `ls -t` as `ls -lt`.

**Comment by MikeMcQuaid** [comment]
Cool. We're not supporting this for now. You can probably script it yourself.
