### ISSUE TITLE
Suggest fish compatible commands to fix directory permissions

### ISSUE THREAD

**Issue by domoritz** [Homebrew/brew#8263]
This is opening https://github.com/Homebrew/brew/issues/5680 up again as it's the only command that I have found to not be fish compatible. It would be awesome if you could reconsider the decision. 

# A detailed description of the proposed feature

The helpful error messages when directory permissions need to be changed should also work on fish shell. 

```
You should change the ownership of these directories to your user.
  sudo chown -R $(whoami) /usr/local/Frameworks /usr/local/bin /usr/local/etc /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/share/doc /usr/local/share/locale /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man2 /usr/local/share/man/man3 /usr/local/share/man/man4 /usr/local/share/man/man5 /usr/local/share/man/man8 /usr/local/share/zsh /usr/local/share/zsh/site-functions

And make sure that your user has write permission.
  chmod u+w /usr/local/Frameworks /usr/local/bin /usr/local/etc /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/share/doc /usr/local/share/locale /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man2 /usr/local/share/man/man3 /usr/local/share/man/man4 /usr/local/share/man/man5 /usr/local/share/man/man8 /usr/local/share/zsh /usr/local/share/zsh/site-functions
```

I propose to change `-R $(whoami)` to `-R (whoami)` when the user has the fish shell enabled. 

# The motivation for the feature

When I update macOS, the new installation resets directory permissions and so I get this error

```
Error: The following directories are not writable by your user:
/usr/local/Frameworks
/usr/local/bin
/usr/local/etc
/usr/local/lib
/usr/local/sbin
/usr/local/share
/usr/local/share/doc
/usr/local/share/locale
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man2
/usr/local/share/man/man3
/usr/local/share/man/man4
/usr/local/share/man/man5
/usr/local/share/man/man8
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
```

There is a useful hint about how to fix the permissions but the suggested command is not compatible with fish shell.

# How the feature would be relevant to at least 90% of Homebrew users

The feature would be useful for fish shell users. 

# What alternatives to the feature have been considered

I have not considered alternatives but this is not really a breaking change or new feature and more an enhancement.

**Comment by MikeMcQuaid** [comment]
> This is opening #5680 up again as it's the only command that I have found to not be fish compatible. It would be awesome if you could reconsider the decision.

No. Please don't reopen closed issues.
