### ISSUE TITLE
Essayer d'utiliser Open3.popen3 pour le texte principal aussi

### ISSUE THREAD

**Issue by PhilippePerret** [Homebrew/brew#8277]
La seule question que je me pose, c'est : est-ce que ça ne sera pas trop gros d'envoyer tout le texte alors que TreeTagger, lui, dans son script, doit certainement fonctionner en prenant le texte petit à petit.

**Comment by MikeMcQuaid** [comment]
Sorry, we don't speak French and you need to fill out the issue template.
