### ISSUE TITLE
home-brew installation unexpectedly drops out towards the completion of installation

### ISSUE THREAD

**Issue by sunshine1001** [Homebrew/brew#8279]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I was attempting to install 'exercism' but found I needed to install brew prior to that
## What happened (include command output)
So it appears to complete but this part was displayed in the Terminal window.. (my experience has always been Windows and have just recently bought a Mac-so please go easy)
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (39/39), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` exited with 128.
Error: Failure while executing; `/usr/local/bin/brew tap homebrew/core` exited with 1.
Failed during: /usr/local/bin/brew update --force

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

I expected the installation to complete

## Step-by-step reproduction instructions (by running `brew` commands)

please see a more detailed Terminal attached

## Output of `brew config` and `brew doctor` commands
[brew_problem_detailed.txt](https://github.com/Homebrew/brew/files/5051418/brew_problem_detailed.txt)

**Comment by MikeMcQuaid** [comment]
This is an issue with your connection to GitHub.

**Comment by claui** [comment]
Welcome to Homebrew @sunshine1001!

As Mike said, this is a network issue, and has nothing to do with Homebrew.

You can find out more if you go to https://discourse.brew.sh and search for `remote end hung up unexpectedly`. Reading a couple of posts there may help you figure out the root cause and a possible fix.
If that doesn’t help, try from different networks (e. g. company, university, home, cellular).

Good luck, and thank you for understanding we had to close this here because it’s not related to Homebrew.
