### ISSUE TITLE
Add explicit license disclaimer

### ISSUE THREAD

**Issue by dtrodrigues** [Homebrew/brew#8281]
# A detailed description of the proposed feature
Add explicit disclaimer about license information, possibly including how licenses are identified, somewhere in the documentation.

# The motivation for the feature
[GitHub](https://docs.github.com/en/rest/reference/licenses) includes information about how the license information is generated as well as a disclaimer about legal liability.

# How the feature would be relevant to at least 90% of Homebrew users

Homebrew users who have restrictions on which licenses they can use will be explicitly warned about the provenance and guarantees about the license information provided by Homebrew

# What alternatives to the feature have been considered
Not including a disclaimer since the existing Homebrew BSD 2-clause license already covers (lack of) liability.

@Homebrew/plc

**Comment by claui** [comment]
Sorry but I don’t quite understand what this is is about.

> Add explicit disclaimer about license information, possibly including how licenses are identified

What license information? Is this about upstream licenses (as referenced in the formulae) or the license under which Homebrew itself is published?

> as well as a disclaimer about legal liability.

Are you referring to the copy in the red box on the linked GitHub page?

**Comment by dtrodrigues** [comment]
> What license information? Is this about upstream licenses (as referenced in the formulae) or the license under which Homebrew itself is published?

This is referring to the upstream license information, not Homebrew itself.

> Are you referring to the copy in the red box on the linked GitHub page?

Yeah - the copy in the red box is what grabbed my attention.

**Comment by MikeMcQuaid** [comment]
> Not including a disclaimer since the existing Homebrew BSD 2-clause license already covers (lack of) liability.

I think this is sufficient, personally.  We don't really have documentation like that on GitHub.

**Comment by dtrodrigues** [comment]
Closing due to lack of @Homebrew/plc interest.

**Comment by jonchang** [comment]
Thanks for working on this! The licensing stuff is really tricky so we'll have to think carefully on everything that we're approachign this with.
