### ISSUE TITLE
Prevent homebrew to report updates when it's only linting changes or things like url/zap update

### ISSUE THREAD

**Issue by Porkepix** [Homebrew/brew#8282]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

Issue is opened here after discussions on https://github.com/Homebrew/homebrew-cask/issues/87343

## What you were trying to do (and why)

I just ran a `brew update`

## What happened (include command output)
I don't have command output at hand anymore, but result is the list of updated formulas/casks, excepted user can have formulas/casks reported as updated, while it was only updates on linting, zapped files, or url for example.

EDIT: Here's another example with iTerm2 and this commit: https://github.com/Homebrew/homebrew-cask/commit/1445723fd17f38bfd56399cc35de05d347847220

```
❯ brew update
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
abcmidi    clojure    fennel     ghc        openrtsp   whistle    x3270
acpica     devspace   folly      hcloud     phpunit    wtf
==> Updated Casks
iterm2 ✔                                 sweet-home3d
appium                                   tortoisehg
cocoaspell                               unity-android-support-for-editor
jetbrains-toolbox                        unity-download-assistant
multipass                                unity-lumin-support-for-editor
musicbrainz-picard                       unity-webgl-support-for-editor
proxyman                                 unity-windows-support-for-editor

~
❯ brew cask upgrade iterm2
~
❯ 
```

## What you expected to happen

That such changes, that are very different from an application update (version number change) would not be reported as updated. First, because for classic homebrew formulas (core), it can lead to very very long output as it did in the past few weeks with a big update that happened. But especially for casks: many casks do not upgrade when running a global `brew cask upgrade` because homebrew expect those to manage update by themselves. So if user try to upgrade them manually after that, eg. `brew cask upgrade firefox thunderbird` for today, then nothing happens, as the only change was https://github.com/Homebrew/homebrew-cask/pull/87307. Despite this very small change, those casks were reported as updated with the green check mark.

This kind of cases, including zap updates, url and other metadatas updates and so on, shouldn't be reported to the user as a formula update on `brew update` imho.

## Step-by-step reproduction instructions (by running `brew` commands)

A simple `brew update`

## Output of `brew config` and `brew doctor` commands

<pre>
❯ brew config
HOMEBREW_VERSION: 2.4.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: c49ef80dd37bcdbbb2d33b321e58a46fdd102267
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c82d4fd223518be30dece3563251a1da5875f952
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: N/A

~
❯ brew doctor
Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment]
Moving conversation back to https://github.com/Homebrew/homebrew-cask/issues/87343.
