### ISSUE TITLE
syntax error near unexpected token 

### ISSUE THREAD

**Issue by fm-techbts** [Homebrew/brew#829]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo) && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

No matter what I type I get the following

```
/usr/local/bin/brew: line 1: syntax error near unexpected token `<<<'
/usr/local/bin/brew: line 1: `<<<<<<< 7c5e149b1b56f59ce36dae145961d5ceb6cd3ac9'
$ brew install wget
/usr/local/bin/brew: line 1: syntax error near unexpected token `<<<'
/usr/local/bin/brew: line 1: `<<<<<<< 7c5e149b1b56f59ce36dae145961d5ceb6cd3ac9'
$ brew doctor
/usr/local/bin/brew: line 1: syntax error near unexpected token `<<<'
/usr/local/bin/brew: line 1: `<<<<<<< 7c5e149b1b56f59ce36dae145961d5ceb6cd3ac9'

```
I saw another guy having this issue but his thread was closed because he was being an asshole.

**Comment by DomT4** [comment]
Looks like a git rebase gone wrong, perhaps. Can you `cat /usr/local/bin/brew` and provide the output?

**Comment by fm-techbts** [comment]
`$ cat /usr/local/bin/brew
<<<<<<< 7c5e149b1b56f59ce36dae145961d5ceb6cd3ac9
#!/bin/bash
set +o posix

quiet_cd() {
  cd "$@" >/dev/null
}

symlink_target_directory() {
  local target="$(readlink "$1")"
  local target_dirname="$(dirname "$target")"
  local directory="$2"
  quiet_cd "$directory" && quiet_cd "$target_dirname" && pwd -P
}

BREW_FILE_DIRECTORY="$(quiet_cd "${0%/*}/" && pwd -P)"
HOMEBREW_BREW_FILE="${BREW_FILE_DIRECTORY%/}/${0##*/}"
HOMEBREW_PREFIX="${HOMEBREW_BREW_FILE%/*/*}"

# Default to / prefix if unset or the bin/brew file.
if [[ -z "$HOMEBREW_PREFIX" || "$HOMEBREW_PREFIX" = "$HOMEBREW_BREW_FILE" ]]
then
  HOMEBREW_PREFIX="/"
fi

HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX"

# Resolve the bin/brew symlink to find Homebrew's repository
if [[ -L "$HOMEBREW_BREW_FILE" ]]
then
  BREW_FILE_DIRECTORY="$(symlink_target_directory "$HOMEBREW_BREW_FILE" "$BREW_FILE_DIRECTORY")"
  HOMEBREW_REPOSITORY="${BREW_FILE_DIRECTORY%/*}"
fi

# Try to find a /usr/local HOMEBREW_PREFIX where possible (for bottles)
if [[ -L "/usr/local/bin/brew" ]]
then
  USR_LOCAL_BREW_FILE_DIRECTORY="$(symlink_target_directory "/usr/local/bin/brew" "/usr/local/bin")"
  USR_LOCAL_HOMEBREW_REPOSITORY="${USR_LOCAL_BREW_FILE_DIRECTORY%/*}"
  if [[ "$HOMEBREW_REPOSITORY" = "$USR_LOCAL_HOMEBREW_REPOSITORY" ]]
  then
    HOMEBREW_PREFIX="/usr/local"
  fi
fi

HOMEBREW_LIBRARY="$HOMEBREW_REPOSITORY/Library"

source "$HOMEBREW_LIBRARY/Homebrew/brew.sh"
=======
#!/bin/sh

chdir () {
  cd "$@" >/dev/null
}

BREW_FILE_DIRECTORY=$(chdir "${0%/*}" && pwd -P)
export HOMEBREW_BREW_FILE="$BREW_FILE_DIRECTORY/${0##*/}"

BREW_SYMLINK=$(readlink "$0")
if [ -n "$BREW_SYMLINK" ]
then
    BREW_SYMLINK_DIRECTORY=$(dirname "$BREW_SYMLINK")
    BREW_FILE_DIRECTORY=$(chdir "$BREW_FILE_DIRECTORY" &&
                          chdir "$BREW_SYMLINK_DIRECTORY" && pwd -P)
fi

BREW_LIBRARY_DIRECTORY=$(chdir "$BREW_FILE_DIRECTORY"/../Library && pwd -P)

# Users may have these set, pointing the system Ruby
# at non-system gem paths
unset GEM_HOME
unset GEM_PATH

BREW_SYSTEM=$(uname -s | tr "[:upper:]" "[:lower:]")
if [ "$BREW_SYSTEM" = "darwin" ]
then
    exec "$BREW_LIBRARY_DIRECTORY/brew.rb" "$@"
else
    exec ruby -W0 "$BREW_LIBRARY_DIRECTORY/brew.rb" "$@"
fi
>>>>>>> dieharder: add 3.31.1 bottle.`

**Comment by DomT4** [comment]
Yup, looks like a rebase gone wrong. Try:
```bash
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```

**Comment by fm-techbts** [comment]
Still getting the same error. 

```$ cd $(brew --prefix) && git fetch && git reset --hard origin/master
/usr/local/bin/brew: line 1: syntax error near unexpected token `<<<'
/usr/local/bin/brew: line 1: `<<<<<<< 7c5e149b1b56f59ce36dae145961d5ceb6cd3ac9'
fatal: Not a git repository (or any of the parent directories): .git
 ```

**Comment by DomT4** [comment]
Oh, that's because I'm an idiot. Of course `brew --prefix` will struggle to work if `brew` (the script) is messed up. Sorry.

Try:
```bash
cd /usr/local && git fetch && git reset --hard origin/master
```

**Comment by fm-techbts** [comment]
`n$ cd /usr/local && git fetch && git reset --hard origin/master
remote: Counting objects: 18, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 18 (delta 14), reused 18 (delta 14), pack-reused 0
Unpacking objects: 100% (18/18), done.
From https://github.com/Homebrew/brew
   7c5e149..8e29cf1  master     -> origin/master
error: unable to create file Library/Homebrew/dev-cmd/boneyard-formula-pr.rb (Permission denied)
error: unable to create file Library/Homebrew/dev-cmd/bump-formula-pr.rb (Permission denied)
error: unable to create file Library/Homebrew/dev-cmd/linkage.rb (Permission denied)
error: unable to create file Library/Homebrew/dev-cmd/mirror.rb (Permission denied)
error: unable to create file Library/Homebrew/dev-cmd/test-bot.rb (Permission denied)
error: unable to unlink old 'Library/Homebrew/dev-cmd/update-test.rb' (Permission denied)
error: unable to create symlink Library/Homebrew/test/bottles/testball_bottle-0.1.linux_x86_64.bottle.tar.gz (Permission denied)
error: unable to create symlink Library/Homebrew/test/bottles/testball_bottle-0.1.macintosh_intel.bottle.tar.gz (Permission denied)
error: unable to create symlink Library/Homebrew/test/bottles/testball_bottle-0.1.sierra.bottle.tar.gz (Permission denied)
fatal: Could not reset index file to revision 'origin/master'.
`

Sorry to just keep dumping error messages on you. I really do appreciate your help.

**Comment by fm-techbts** [comment]
I'm hesitant to try it with sudo since that may be what got me into this mess.

**Comment by DomT4** [comment]
Yikes, fun. Try a limited `sudo`:

```bash
sudo chown -R $(whoami) /usr/local/Library
```
And then do the fetch/reset again.

**Comment by fm-techbts** [comment]
`$ sudo chown -R $(whoami) /usr/local/Library
$ cd /usr/local && git fetch && git reset --hard origin/master
HEAD is now at 8e29cf1 Merge pull request #812 from DomT4/at
$ brew update
Already up-to-date.
$
1

You are awesome! Thank you! Now to see if I can get apt-get installed without fucking everything up again.

**Comment by DomT4** [comment]
Great! 😃. Give us a shout if anything else breaks.
