### ISSUE TITLE
Feature Request: man pages.

### ISSUE THREAD

**Issue by Alexeyan** [Homebrew/brew#83]
Hi.

If i install gcc over homebrew for example i don't get the man-page entry for it.
-> man gcc says no manual entry for gcc

Alex

**Comment by tdsmith** [comment]
Hi; thanks for getting in touch. We install the gcc manpages with the same names as the executables; try `man gcc-5`. If there's anything else you think we should have man pages for, please open a ticket for that package at Homebrew/homebrew-core. Let us know if we can help with anything else.

**Comment by Alexeyan** [comment]
man gcc-5 also gives "no manual entry for gcc"

**Comment by tdsmith** [comment]
That's odd; it works for me. `brew info gcc` shows that it's installed? Can you share `brew config` -- if you have Homebrew installed somewhere besides /usr/local, you probably have to set up MANPATH.

**Comment by Alexeyan** [comment]
huh.. I know i tried to install it. 
Just tried again and it died at "make bootstrap" had to ctrl-c and remebered, that the first installation went the same way. 
I just didn't notice because OS X has the gcc-pseudo frontend to clang...

**Comment by apjanke** [comment]
In that case, please post this as a build failure bug report over at https://github.com/homebrew/homebrew-core/issues, with build logs (from `brew gist-logs`) included. (Or if you're trying to build it `--without-multilib`, there's an existing issue https://github.com/Homebrew/homebrew-core/issues/234 that you can chime in on (again, with your `brew gist-logs` from it).)

For future reference, `brew ls -v <formula-name> | grep man` will give you a list of the man pages installed with a formula, if you need to verify them.
