### ISSUE TITLE
brew info gives error on upgraded pinned formula

### ISSUE THREAD

**Issue by koallen** [Homebrew/brew#831]
**This issue is previously opened at `homebrew-core` by my mistake (Homebrew/homebrew-core#4301). Reopening here at `brew`.**

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Previously, I pinned `gcc` since I don't wanna upgrade it. Later `r` is upgraded and that forced a upgrade to `gcc` (from `5.3.0` to `6.1.0`). After that, **I ran `brew cleanup`** to clean up old versions of packages. Just now I was trying to run `brew info gcc`, and I get an error saying `Error: /usr/local/Cellar/gcc/5.3.0 is not a directory`. This is similar to Homebrew/legacy-homebrew#46044.

I have to manually do `brew unpin gcc` and `brew pin gcc` so that I can get the correct info.

Is there some logical error in handling `brew info` with pinned packages?

**PS: The bug is reproduced by @ilovezfs in Homebrew/homebrew-core#4301.**

**Comment by MikeMcQuaid** [comment]
Should be fixed, I believe, by https://github.com/Homebrew/brew/issues/846
