### ISSUE TITLE
Feature: Add tags to brew install

### ISSUE THREAD

**Issue by cdce8p** [Homebrew/brew#8322]
## Description
Add an option to `brew install` to tag installed packages and its dependencies.
The `tag` could then be used for a clean uninstall of all related packages.

## Motivation
- Keep track which packages where installed for which purpose
- Simplify removal of multiple packages including their dependencies
- Many package manger / ecosystems allow users to create environments in which to install all their project dependencies and clean up after the project is done (e.g. Python venv). Homebrew doesn't have such an option.

## Homebrew community
- https://stackoverflow.com/questions/7323261/uninstall-remove-a-homebrew-package-including-all-its-dependencies
- https://github.com/Homebrew/legacy-homebrew/issues/7465

## Alternatives
Some solutions try to use `brew leaves` and `brew deps` in intelligent ways to allow users to remove a package and all its dependencies without breaking anything. However I haven't found any solution to keep track over which packages where installed from what purpose. 

#### Install package
- Add `--tag <my_tag>` option to `brew install <package>`
- This tag would be assigned to the package and all its dependencies
- In case the dependency was already installed and has another tag, add the new one to the tag list.
#### Remove package
- Extend `brew uninstall` to allow tags as target, therefore add an option `--tag <my_tag>`
- This command would then remove all packages with the associated tag, as long as it's the **only** tag (= no other package depends on it)
#### Backwards compatibility
- All newly installed packages would be assigned a tag, either the one specified by the user or a default one.
- During `install` we can check if an already installed dependency has no tags. If that is the case, we would add the default tag.
- Since we converted all packages when we add a new tag, `uninstall --tag` wouldn't need any changes
#### Manage tags
- Add a new cmd `brew tag` to manage tags
- `--add <my_tag> <Package>` would work similar to `brew install --tag`
- `--remove <my_tag> <Package>` would remove a given tag from a package and all its deps. If it was the last tag, add the default tag.
- `--mv <old_tag> <new_tag>` or `--rename` to rename tags. If <new_tag> already exists, this would equal a tag merge
- `--list` This cmd would list all tags and their packages
#### Misc
- `brew list` could be extended to print all assigned tags next to the package name.
- `brew bundle` could also be extended to included tags

**Comment by MikeMcQuaid** [comment]
> * `brew bundle` could also be extended to included tags

I think using separate `Brewfile`s is the best bet for this purpose. Beyond that: this is the perfect fit for an external command: https://docs.brew.sh/External-Commands
