### ISSUE TITLE
Version comparison inconsistent while upgrading from an unstable formula

### ISSUE THREAD

**Issue by CL-Jeremy** [Homebrew/brew#8323]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Doing `brew upgrade` after restoring Time Machine backup

## What happened (include command output)

Tried `brew cleanup` after all upgrades have finished, got:

<details>
  <summary>Command output</summary>
  <pre>

  Warning: Skipping speexdsp: most recent version 1.2.0 not installed

  </pre>
</details>

## What you expected to happen

`brew upgrade` should have upgraded `speexdsp` from 1.2rc3 to 1.2.0

## Step-by-step reproduction instructions (by running `brew` commands)

N/A (assuming there aren't any formula with version `*rc*` anymore)

## Output of `brew config` and `brew doctor` commands

N/A
<br />

Possibly related to #8186?

**Comment by gromgit** [comment]
> ## Output of `brew config` and `brew doctor` commands
> N/A

Given that:
* you restored from a fairly old backup (the bump to 1.2.0 was over a year ago)
* you said nothing about running `brew update`
* you're pointing to a very recent PR as a possible cause

I'd say the `brew config` and `brew doctor` outputs are **very** applicable, if for no other reason than as an assurance that your Homebrew repos are up-to-date.

**Comment by CL-Jeremy** [comment]
> * you said nothing about running `brew update`

Oh! Makes sense. I do have a Mavericks machine where I've been using an ancient Homebrew installation from early 2016 with `HOMEBREW_NO_AUTO_UPDATE=1`. Very, very specific edge case though.
<details>
<summary><tt>brew config</tt></summary>
<pre>
HOMEBREW_VERSION: 2.4.11-50-g6d9bf72-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6d9bf7286e776921dfff79f845f3f49cf449dce0
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 087008a4c8cfba1e728db58d936c24fead0de954
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.4, 11.0.3, 1.8.0_221, 1.8.0_202-BellSoft-b08, 1.8.0_202
macOS: 10.15.6-x86_64
CLT: 12.0.22.7
Xcode: N/A
</pre>
</details>

<details>
<summary><tt>brew doctor</tt></summary>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  python@2

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  polipo

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/opt/intelpython3/bin/freetype-config
  /usr/local/opt/intelpython3/bin/libpng16-config
  /usr/local/opt/intelpython3/bin/python3.6m-config
  /usr/local/opt/intelpython3/bin/libpng-config
  /usr/local/opt/intelpython3/bin/python3-config
  /usr/local/opt/intelpython3/bin/python3.6-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2
  lsusb
  libsigc++@2
  python@3.8

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> /Users/mike/.bash_profile

</details>

**Comment by MikeMcQuaid** [comment]
This isn't really fixable at this point. `brew uninstall` and `brew install` if you want to get onto that version.
