### ISSUE TITLE
bump-formula-pr does not respect --no-audit

### ISSUE THREAD

**Issue by kpenfound** [Homebrew/brew#8337]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?

- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Running bump-formula-pr against a tap, specifying --no-audit, --no-browse, --message, --url, and --version  to update a formula in a tap.

## What happened (include command output)

Up until today, the unchanged workflow was fine.  As of today (using latest brew),  the `--no-audit` flag doesn't seem to be respected as it is running `brew audit` and failing.  I corrected formatting issues in the formula which audit was complaining about, however I'm still getting hung up on:
`* C: 1: col 1: Incorrect file permissions (666): chmod o-w ...(my formula).rb`

If this is an issue with the formula or tap, I'm happy to correct that, but the `--no-audit` flag does seem to be getting skipped right now.

## What you expected to happen

I expect bump-formula-pr to create a PR and respect the flags passed to it..

## Step-by-step reproduction instructions (by running `brew` commands)

Run `brew bump-formula-pr --no-audit`.

## Output of `brew config` and `brew doctor` commands
config
```
brew config
HOMEBREW_VERSION: 2.4.11-72-g9fa67ba
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9fa67ba35404fcb40d9c50307161793993174916
Last commit: 54 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 81240ed35f6d674b4dc18e0ca4d92c1a225a8893
Core tap last commit: 57 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 1103.0.32.62
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

doctor
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unknown support status

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/share/man/man1/brew-cask.1
```

**Comment by Rylan12** [comment]
@reitermarkus looks like it's an issue with #8239
