### ISSUE TITLE
`brew cask list` dumps Ruby object when no file info available

### ISSUE THREAD

**Issue by gromgit** [Homebrew/brew#8342]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

In the process of helping out in [a Discourse thread](https://discourse.brew.sh/t/how-do-i-avoid-too-many-passwords/8540), I tried to list the files in the `smlnj` cask

## What happened (include command output)

`brew cask list smlnj` returns a Ruby Cask object dump for `smlnj`:

<details>
  <summary>Command output</summary>
  <pre>
$ brew cask list smlnj
{Cask::Artifact::Uninstall=>[#<Cask::Artifact::Uninstall:0x00007f900d9ad3d8 @cask=#<Cask::Cask:0x00007f900c8f90a0 @token="smlnj", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/smlnj.rb>, @tap=#<Tap:0x00007f900c97a6a0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f900c8f8f38@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/smlnj.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/smlnj>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/smlnj/.metadata>, @config=#<Cask::Config:0x00007f900da08260 @explicit={}, @default={:languages=>["en-SG"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/aho/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/aho/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/aho/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/aho/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/aho/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/aho/Library/Fonts>, :servicedir=>#<Pathname:/Users/aho/Library/Services>, :input_methoddir=>#<Pathname:/Users/aho/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/aho/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/aho/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/aho/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/aho/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/aho/Library/Screen Savers>}, @env={}>, @dsl=#<Cask::DSL:0x00007f900d059a20 @cask=#<Cask::Cask:0x00007f900c8f90a0 ...>, @token="smlnj", @version="110.98", @sha256="cb059e82046fda866af031d1cc39c56a53f951aa7370154a12113c580f44db78", @url=#<URL:0x00007f900d058be8 @uri=#<URI::HTTP http://smlnj.cs.uchicago.edu/dist/working/110.98/smlnj-amd64-110.98.pkg>, @user_agent=:default, @specs={}>, @name=["Standard ML of New Jersey"], @homepage="https://www.smlnj.org/", @artifacts=#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007f900d9ad3d8 ...>, #<Cask::Artifact::Pkg:0x00007f900c8705c0 @cask=#<Cask::Cask:0x00007f900c8f90a0 ...>, @path=#<Pathname:/usr/local/Caskroom/smlnj/110.98/smlnj-amd64-110.98.pkg>, @stanza_options={}>}>, @staged_path=#<Pathname:/usr/local/Caskroom/smlnj/110.98>, @caveats=#<Cask::DSL::Caveats:0x00007f900d9aced8 @cask=#<Cask::Cask:0x00007f900c8f90a0 ...>, @command=SystemCommand, @built_in_caveats={[:path_environment_variable, "/usr/local/smlnj/bin"]=>"To use smlnj, you may need to add the /usr/local/smlnj/bin directory\nto your PATH environment variable, e.g. (for bash shell):\n  export PATH=/usr/local/smlnj/bin:\"$PATH\"\n"}, @custom_caveats=[]>, @language=nil>>, @directives={:pkgutil=>"org.smlnj.amd64.pkg", :signal=>[]}>], Cask::Artifact::Pkg=>[#<Cask::Artifact::Pkg:0x00007f900c8705c0 @cask=#<Cask::Cask:0x00007f900c8f90a0 @token="smlnj", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/smlnj.rb>, @tap=#<Tap:0x00007f900c97a6a0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f900c8f8f38@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/smlnj.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/smlnj>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/smlnj/.metadata>, @config=#<Cask::Config:0x00007f900da08260 @explicit={}, @default={:languages=>["en-SG"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/aho/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/aho/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/aho/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/aho/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/aho/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/aho/Library/Fonts>, :servicedir=>#<Pathname:/Users/aho/Library/Services>, :input_methoddir=>#<Pathname:/Users/aho/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/aho/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/aho/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/aho/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/aho/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/aho/Library/Screen Savers>}, @env={}>, @dsl=#<Cask::DSL:0x00007f900d059a20 @cask=#<Cask::Cask:0x00007f900c8f90a0 ...>, @token="smlnj", @version="110.98", @sha256="cb059e82046fda866af031d1cc39c56a53f951aa7370154a12113c580f44db78", @url=#<URL:0x00007f900d058be8 @uri=#<URI::HTTP http://smlnj.cs.uchicago.edu/dist/working/110.98/smlnj-amd64-110.98.pkg>, @user_agent=:default, @specs={}>, @name=["Standard ML of New Jersey"], @homepage="https://www.smlnj.org/", @artifacts=#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007f900d9ad3d8 @cask=#<Cask::Cask:0x00007f900c8f90a0 ...>, @directives={:pkgutil=>"org.smlnj.amd64.pkg", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007f900c8705c0 ...>}>, @staged_path=#<Pathname:/usr/local/Caskroom/smlnj/110.98>, @caveats=#<Cask::DSL::Caveats:0x00007f900d9aced8 @cask=#<Cask::Cask:0x00007f900c8f90a0 ...>, @command=SystemCommand, @built_in_caveats={[:path_environment_variable, "/usr/local/smlnj/bin"]=>"To use smlnj, you may need to add the /usr/local/smlnj/bin directory\nto your PATH environment variable, e.g. (for bash shell):\n  export PATH=/usr/local/smlnj/bin:\"$PATH\"\n"}, @custom_caveats=[]>, @language=nil>>, @path=#<Pathname:/usr/local/Caskroom/smlnj/110.98/smlnj-amd64-110.98.pkg>, @stanza_options={}>]}
  </pre>
</details>

I tested several other casks, and the common factor seems to be that they're all package installs (i.e. they all contain a `pkg` stanza), so I guess there's no way to inspect it to find out what files were installed.

## What you expected to happen

I expected something like `No file listing available`, or something other than an impenetrable object dump.

## Step-by-step reproduction instructions (by running `brew` commands)

```sh
brew cask list appcleaner  # installs from ZIP, so lists files properly
brew cask list smlnj      # shows object dump for smlnj cask
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.4.11-78-g2a619a9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2a619a9cbdf0c5ff950ad93205b1574e507cb4c4
Last commit: 6 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7bc5ee35ae4cc3787d0ce7f8768c5b538d35c772
Core tap last commit: 3 hours ago
Core tap branch: bump-mariadb@10.2-10.2.33
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.6.0_51-b11-457
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.5
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libpgtcl.h

Warning: Found Ruby file outside gromgit/dev tap formula directory.
(/usr/local/Homebrew/Library/Taps/gromgit/homebrew-dev/Formula):
  /usr/local/Homebrew/Library/Taps/gromgit/homebrew-dev/tcl.gd.rb

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  moreutils
  gcc@8
  gcc@7
</pre>

**Comment by reitermarkus** [comment]
Seems like a regression in https://github.com/Homebrew/brew/pull/7966.

**Comment by SMillerDev** [comment]
#8355 should fix this
