### ISSUE TITLE
fatal to install homebrew or brew update or brew cask install

### ISSUE THREAD

**Issue by codesboy** [Homebrew/brew#8343]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I trying to install homebrew by  :/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

## What happened (include command output)
![1](https://user-images.githubusercontent.com/9047357/90215201-8c7b3200-de2d-11ea-836b-4a0e742c6235.png)

<details>
  <summary>Command output</summary>

  <pre>
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Caskroom

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /usr/sbin/chown rehack /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /bin/mkdir -p /Users/rehack/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/rehack/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown rehack /Users/rehack/Library/Caches/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at 2a619a9cb Merge pull request #8341 from reitermarkus/man-brew-cask
fatal: Unable to find remote helper for 'https'
fatal: Unable to find remote helper for 'https'
fatal: Unable to find remote helper for 'https'
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Homebrew failed!
fatal: Uh oh. Your system reports no Git commands at all.
fatal: Uh oh. Your system reports no Git commands at all.
Failed during: /usr/local/bin/brew update --force
  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew` commands)

I type: brew -v ,and geted the right version
and then I use git clone https://xxx ,the result is success!

## Output of `brew config` and `brew doctor` commands

<pre>
➜  brew config
HOMEBREW_VERSION: 2.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9ef993ab570ac6d4f2c4f88a96f2da8c3e71fa85
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 54870a1801526452451ffb7e6e1b4881edc85243
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A

➜  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libxml2.2.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libxml2/libxml/DOCBparser.h
  /usr/local/include/libxml2/libxml/HTMLparser.h
  /usr/local/include/libxml2/libxml/HTMLtree.h
  /usr/local/include/libxml2/libxml/SAX.h
  /usr/local/include/libxml2/libxml/SAX2.h
  /usr/local/include/libxml2/libxml/c14n.h
  /usr/local/include/libxml2/libxml/catalog.h
  /usr/local/include/libxml2/libxml/chvalid.h
  /usr/local/include/libxml2/libxml/debugXML.h
  /usr/local/include/libxml2/libxml/dict.h
  /usr/local/include/libxml2/libxml/encoding.h
  /usr/local/include/libxml2/libxml/entities.h
  /usr/local/include/libxml2/libxml/globals.h
  /usr/local/include/libxml2/libxml/hash.h
  /usr/local/include/libxml2/libxml/list.h
  /usr/local/include/libxml2/libxml/nanoftp.h
  /usr/local/include/libxml2/libxml/nanohttp.h
  /usr/local/include/libxml2/libxml/parser.h
  /usr/local/include/libxml2/libxml/parserInternals.h
  /usr/local/include/libxml2/libxml/pattern.h
  /usr/local/include/libxml2/libxml/relaxng.h
  /usr/local/include/libxml2/libxml/schemasInternals.h
  /usr/local/include/libxml2/libxml/schematron.h
  /usr/local/include/libxml2/libxml/threads.h
  /usr/local/include/libxml2/libxml/tree.h
  /usr/local/include/libxml2/libxml/uri.h
  /usr/local/include/libxml2/libxml/valid.h
  /usr/local/include/libxml2/libxml/xinclude.h
  /usr/local/include/libxml2/libxml/xlink.h
  /usr/local/include/libxml2/libxml/xmlIO.h
  /usr/local/include/libxml2/libxml/xmlautomata.h
  /usr/local/include/libxml2/libxml/xmlerror.h
  /usr/local/include/libxml2/libxml/xmlexports.h
  /usr/local/include/libxml2/libxml/xmlmemory.h
  /usr/local/include/libxml2/libxml/xmlmodule.h
  /usr/local/include/libxml2/libxml/xmlreader.h
  /usr/local/include/libxml2/libxml/xmlregexp.h
  /usr/local/include/libxml2/libxml/xmlsave.h
  /usr/local/include/libxml2/libxml/xmlschemas.h
  /usr/local/include/libxml2/libxml/xmlschemastypes.h
  /usr/local/include/libxml2/libxml/xmlstring.h
  /usr/local/include/libxml2/libxml/xmlunicode.h
  /usr/local/include/libxml2/libxml/xmlversion.h
  /usr/local/include/libxml2/libxml/xmlwriter.h
  /usr/local/include/libxml2/libxml/xpath.h
  /usr/local/include/libxml2/libxml/xpathInternals.h
  /usr/local/include/libxml2/libxml/xpointer.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libxml2.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/libxml-2.0.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libxml2.a
</pre>

**Comment by MikeMcQuaid** [comment]
This is an issue with your connection to GitHub.
