### ISSUE TITLE
bump-revision should allow for multiple formula to be specified

### ISSUE THREAD

**Issue by AustinShalit** [Homebrew/brew#8357]
# A detailed description of the proposed feature

I was recently updating a library with many downstream dependancies and had to go through all of the dependencies and run `brew bump-revision <formula>`. I propose that the script should take a variable number of formula: `brew bump-revision <formula ...>`.

# The motivation for the feature

See above but I was hoping for a nicer syntax for bumping the revision of many formula.

# How the feature would be relevant to at least 90% of Homebrew users

It is relevant to developers of Homebrew but is not directly relevant to Homebrew users.

# What alternatives to the feature have been considered

I could just script it in bash or use some other command line magic but I think this is something that others would benefit from.

**Comment by jonchang** [comment]
Please open a pull request for this, thanks! The relevant code is in `Library/Homebrew/dev-cmd/bump-revision.rb`. Feel free to cc me if you need help.

**Comment by dawidd6** [comment]
I'll take it.
