### ISSUE TITLE
Error downloading file using Brew 

### ISSUE THREAD

**Issue by pa1kishore** [Homebrew/brew#836]
After installing brew. I have ran brew update command twice.
HEAD is now at d2bbafa test_test_formula: Work around error on Linuxbrew
Already up-to-date.

 and then ran below commands.
`pci4kor@BMH1048881VM:~$ brew config
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-
p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.

pci4kor@BMH1048881VM:~$ brew doctor
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.

pci4kor@BMH1048881VM:~$ brew help
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.`

Note: Running the brew behind corporate proxy. and proxy is set using cntlm.

Please suggest what is mistake i am doing here.

**Comment by MikeMcQuaid** [comment]
Please report this to https://github.com/Linuxbrew/brew

**Comment by MikeMcQuaid** [comment]
> Note: Running the brew behind corporate proxy. and proxy is set using cntlm.

You need to be able to `curl https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz` without any arguments e.g. configure your environment sufficiently for that.
