### ISSUE TITLE
brew doctor

### ISSUE THREAD

**Issue by hktalent** [Homebrew/brew#838]
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /opt/local/bin/apr-1-config
    /opt/local/bin/apu-1-config
    /opt/local/bin/caca-config
    /opt/local/bin/curl-config
    /opt/local/bin/dnet-config
    /opt/local/bin/freetype-config
    /opt/local/bin/gdlib-config
    /opt/local/bin/gts-config
    /opt/local/bin/imlib2-config
    /opt/local/bin/krb5-config
    /opt/local/bin/libpng-config
    /opt/local/bin/libpng16-config
    /opt/local/bin/Magick++-config
    /opt/local/bin/Magick-config
    /opt/local/bin/MagickCore-config
    /opt/local/bin/MagickWand-config
    /opt/local/bin/ncurses6-config
    /opt/local/bin/ncursesw6-config
    /opt/local/bin/netpbm-config
    /opt/local/bin/pcap-config
    /opt/local/bin/pcre-config
    /opt/local/bin/pkg-config
    /opt/local/bin/python-config
    /opt/local/bin/python2.7-config
    /opt/local/bin/uuid-config
    /opt/local/bin/Wand-config
    /opt/local/bin/xml2-config
    /opt/local/bin/xslt-config
    /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
    /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
    /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config
    /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
    /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
    /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
    /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
    /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
    /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libpcre.la
    /usr/local/lib/libpcrecpp.la
    /usr/local/lib/libpcreposix.la

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    nmap
    python

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
    /opt/local/bin/
    /usr/local/bin/

Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /opt/local/bin/pkg-config

`./configure` may have problems finding brew-installed packages using
this other pkg-config.

Warning: Your Xcode (6.2) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.

**Comment by DomT4** [comment]
Is there anything specific you wanted clarification on or help with from that?

**Comment by hktalent** [comment]
how use brew fix ？thank you

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment]
Essentially everything about `/opt/local` is because you've installed MacPorts. If you want to keep Homebrew & MacPorts around, that's fine, but it may be worth moving MacPorts out of the way whilst using Homebrew because a lot of upstream build scripts will check `/opt` on OS X and that can cause odd breakage.

```
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config
/Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
/Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
```
You likely installed the Python packages for OS X from the upstream website. We recommend using ours.

```
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run brew link on these:
nmap
python
```
You can fix this with `brew link nmap python` unless leaving them unlinked is intentional.

```
Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
/opt/local/bin/
/usr/local/bin/
```
Stuff in your `$PATH` shouldn't end in a slash. Depending on where you've set your path from, you should remove the last forward slash from `/opt/local/bin/` & `/usr/local/bin/`, it isn't needed.

> Warning: Your Xcode (6.2) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.

Does what it says on the tin 😉. Check the Mac App Store for an Xcode update.

> Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run brew update.

Run `brew update`.
