### ISSUE TITLE
Support multiple versions of operartor-sdk formulae

### ISSUE THREAD

**Issue by ivandov** [Homebrew/brew#8384]
# A detailed description of the proposed feature

Support multiple versions of the `operator-sdk` formulae. 

# The motivation for the feature

The latest releases of Openshift Container Platform (OCP) do not support the latest releases of `operator-sdk` and for this reason, it is needed to downgrade to earlier versions. 

For example, the latest release of OCP, 4.5, does only support `operator-sdk` at version `0.17.2`. 

It would be great to manage these versions through `brew` instead of manual downloads from their Github releases.

# How the feature would be relevant to at least 90% of Homebrew users
This is relevant to any users of the `operator-sdk` formulae.

# What alternatives to the feature have been considered
Manual installations of the needed `operator-sdk` releases, not using `brew`.

**Comment by MikeMcQuaid** [comment]
Please submit a PR for this provided these requirements are met: https://docs.brew.sh/Versions#acceptable-versioned-formulae
