### ISSUE TITLE
github certificate verification failed during installation

### ISSUE THREAD

**Issue by crinklywrappr** [Homebrew/brew#8396]
## What you were trying to do (and why)

I am attempting to install brew on a Linux vm.

## What happened (include command output)

![image](https://user-images.githubusercontent.com/56522/90604363-57bb0200-e1c2-11ea-9d8d-5e9812eb80f9.png)

## What you expected to happen

I expected the install to work successfully

## Step-by-step reproduction instructions (by running `brew` commands)

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

## Additional information

I am running Artix (an Arch derivative) on Virtualbox.  I installed git using the `git-minimal` pkg from guix, since it's up-to-date.  I can GET the page (eg, using curl), so the certificate issue must be on my end.

![image](https://user-images.githubusercontent.com/56522/90605227-aa48ee00-e1c3-11ea-9589-c231cff4488c.png)

**Comment by MikeMcQuaid** [comment]
> so the certificate issue must be on my end.

It is so you'll need to fix it yourself.

**Comment by crinklywrappr** [comment]
I got past this by running these commands as root

```
# cert_file = $(curl-config --ca) # locate the certificate file
# echo -n | openssl s_client -showcerts -server www.github.com -connect www.github.com:443 2>/dev/null  | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> $cert_file # write the github certificates to it
```

Then this command as a regular user
```
$ cert_file = $(curl-config --ca) # locate the certificate file
$ git config --global http.sslCAinfo $cert_file # tell git where to find my certificates
```

It may be possible to skip the first section since I find it hard to believe the github certs would be missing on any Arch-based distro.  Most likely git just didn't know where to find them.
