### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by xsd0720** [Homebrew/brew#840]
localhost:~ huahua$ brew install nginx-full --with-rtmp-module
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing nginx-full from homebrew/homebrew-nginx
Error: wrong number of arguments (0 for 1..3)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/software_spec.rb:72:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:72:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1058:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-nginx/Formula/rtmp-nginx-module.rb:7:in `<class:RtmpNginxModule>'
/usr/local/Library/Taps/homebrew/homebrew-nginx/Formula/rtmp-nginx-module.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:78:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:69:in `klass'
/usr/local/Library/Homebrew/formulary.rb:65:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Library/Homebrew/dependency.rb:88:in `block in expand'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependency.rb:76:in `expand'
/usr/local/Library/Homebrew/formula.rb:714:in `recursive_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:98:in `verify_deps_exist'
/usr/local/Library/Homebrew/formula_installer.rb:91:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:176:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:124:in `<main>'

**Comment by bfontaine** [comment]
Please read our troubleshooting guide: https://git.io/brew-troubleshooting

**Comment by xsd0720** [comment]
After I run brew update, run  brew install nginx-full --with-rtmp-module    again.  success
