### ISSUE TITLE
Can't list casks & formulae together

### ISSUE THREAD

**Issue by swrobel** [Homebrew/brew#8405]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

See all installed formulae & casks listed together. I expected this to work because it seems that `brew outdated` & `brew upgrade` were recently updated to include both formulae & casks by default, with flags `--casks` and `--formulae` to deal with either independently.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  Error: Options --cask and --formula are mutually exclusive.

  </pre>
</details>

## What you expected to happen

`brew ls`/`brew list` would show all casks & formulae by default, unless passed `--casks` or `--formulae` to restrict output to one type.

## Step-by-step reproduction instructions (by running `brew` commands)

1. Run `brew ls --casks`
1. Run `brew ls`
1. Note that 2. doesn't include the output from 1.
1. Run `brew ls --casks --formulae`
1. Note output is `Error: Options --cask and --formula are mutually exclusive.`

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew doctor
Your system is ready to brew.

$ brew config
HOMEBREW_VERSION: 2.4.12-206-g85c0612
ORIGIN: https://github.com/Homebrew/brew
HEAD: 85c061295d61c2664c1480dd7c45e4fc398a3ef8
Last commit: 88 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 880c7afb21824f1b3f26d973804ee510881dd7af
Core tap last commit: 60 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: subl -w
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 1103.0.32.62
Xcode: 11.5
</pre>

**Comment by MikeMcQuaid** [comment]
This is intentional and cannot be changed as it would break backwards compatibility.

**Comment by swrobel** [comment]
@MikeMcQuaid I don't understand why default behavior for `brew outdated` & `brew upgrade` were changed, but this one can't be.

If we can't break backwards compatibility for this command, wouldn't it at least be reasonable to have an option that prints all formulae & casks together with a single command?

**Comment by MikeMcQuaid** [comment]
> I don't understand why default behavior for `brew outdated` & `brew upgrade` were changed, but this one can't be.

Their output is not consumed by other tools.

> If we can't break backwards compatibility for this command, wouldn't it at least be reasonable to have an option that prints all formulae & casks together with a single command?

Yes. We'd consider a PR that made `--cask` and `--formula` not conflict.
