### ISSUE TITLE
brew install gcc --enable-cxx 6.1.0 and 6.2.0 is missing header files

### ISSUE THREAD

**Issue by tommyjcarpenter** [Homebrew/brew#843]
I don't know if this is the right forum for specific brewed things. If it is not please tell me where to repost this and I will post if there.

I can't make anything with brewed gcc 6.1.0 or 6.2.0. The issue I posted here: http://stackoverflow.com/questions/39239722/homebrew-gcc-6-1-0-bits-cconfig-h-missing

In short there is a missing header file referenced from a header that brew does install so I don't know if this is a GCC bug or a homebrew bug.

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by tommyjcarpenter** [comment]
The product built and installed successfully. I think it is incomplete, though. There were no errors. 

My guesses are:
1) the tar that is downloaded is somehow incomplete: https://homebrew.bintray.com/bottles/gcc-6.2.0.el_capitan.bottle.tar.gz
2) it is built with an incorrect ./configure script.

**Comment by MikeMcQuaid** [comment]
Please follow those steps regardless.

**Comment by tommyjcarpenter** [comment]
@MikeMcQuaid ok I have followed those steps. Updated twice. gist shows `https://gist.github.com/0a3be249566145b6cbb335b9ba192d63`. Nothing in Doctor: `~ brew doctor
Your system is ready to brew.`. Not Java. XCode is `Version 7.3.1 `.

**Comment by tommyjcarpenter** [comment]
From comparing the downloaded bottle, vs. the GNU tar I linked in my SO post, I see a lot less files in the mac bottle, including the c++config file. Specifically from the bottle download, in `/Users/tommy/Downloads/gcc/6.2.0/include/c++/6.2.0/bits`, the header is missing. It is not missing from the vanilla GNU download.

**Comment by tommyjcarpenter** [comment]
Edit: this file appeared in another directory, /usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/x86_64-apple-darwin15.6.0/bits. I guess this is a platform specific configuration directory. So, this was my fault.
