### ISSUE TITLE
duck install claims upgrading my openjdk whereas it meets the requirements

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/brew#8475]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
Don't know how to remove the final error concerning internal brew error about runtime dependencies from /opt/homebrew/opt/libmpc@0.8/.brew/libmpc@0.8.rb, but I live with that for months
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrading to new available version of duck (7.5.2.33336) with `brew upgrade duck`. Knowing that:
- duck requirements say `depends_on java: ["1.8", :build]` which is largely met by my installed version of openjdk 13.
- my system has several JDK (Java) versions, and `openjdk` is pinned to version 13.0.2+8_2 (from brew) to avoid current version 14 that I preferred not install for the moment to keep version 13.

## What happened (include command output)

Error message saying I should unpin `openjdk` to install the latest version (which is 14)
<details>
  <summary>Command output</summary>
  <pre>
$ brew upgrade duck
==> Upgrading 1 outdated package:
duck 7.4.1.33065 -> 7.5.2.33336
==> Upgrading duck 7.4.1.33065 -> 7.5.2.33336 
Error: You must `brew unpin openjdk` as installing duck requires the latest version of pinned dependencies
  </pre>
</details>

## What you expected to happen

Since duck requirements say that Java 8 (very old version 1.8) is the minimum required, I expected that my installed version 13, more recent, would be largely enough.

## Step-by-step reproduction instructions (by running `brew` commands)

- have `openjdk` version 13 installed from brew, and pinned
- then `brew install duck`

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.4.13-93-g7596259
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 75962590db8cb57fa3b06621ed30446811be581a
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3f76a45c8d35e0d2486aad7fbd2a6c4f7d4ab782
Core tap last commit: 65 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.KC6b7b3gLC/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.2, 11.0.2, 1.8.0_241, 1.7.0_51
macOS: 10.15.6-x86_64
CLT: N/A
Xcode: 11.6
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  libinotify-kqueue
  syncthing-inotify
  python@2
  color-make
  xfig
  libmpc@0.8
  pplatex
  sqsh
  rar
  isl@0.11
  mpfr@2
  gmp@4
  eclipse-clp
  clang-omp
  catdoc
  antlr@3
  gv
  diffpdf
  forked-daapd
  bonzaiboost
  pdfjam
  xv
  djmount
  isl@0.14
  isl@0.12
  gcc@4.8

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  godep

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/ublio.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gcc@5
  isl@0.11
  mpfr@2
  opencv
  gcc@6
  unison
  gcc@4.8

Warning: Some installed formulae are not readable:
  mpfr@2: undefined method `undent' for #<String:0x00007f8d32779888>

  pdfjam: Unsupported special dependency :tex

  gcc@4.8: uninitialized constant #<Class:0x00007f8d3c06de90>::MaximumMacOSRequirement

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

Warning: /usr/bin occurs before /opt/homebrew/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/opt/homebrew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'setenv PATH /opt/homebrew/bin:$PATH' >> ~/.tcshrc

The following tools exist at both paths:
  smtpd2.7.py
  idle2.7
  pre-grohtml
  groff
  idle
  neqn
  db_upgrade
  db_hotbackup
  git-receive-pack
  2to3-2.7
  tfmtodit
  grolbp
  python3
  troff
  mmroff
  groffer
  easy_install
  pydoc
  db_printlog
  python
  python2
  pythonw
  db_archive
  refer
  pip3
  python2.7-config
  nano
  pfbtops
  grops
  grotty
  db_stat
  eqn
  db_load
  tbl
  rsync
  pydoc2.7
  git-upload-archive
  pythonw2.7
  indxbib
  soelim
  addftinfo
  python-config
  db_verify
  post-grohtml
  hpftodit
  pic
  patch
  gdiffmk
  easy_install-2.7
  grodvi
  lookbib
  afmtodit
  python2.7
  lkbib
  db_checkpoint
  git-shell
  grn
  nroff
  db_deadlock
  git-upload-pack
  grolj4
  grog
  db_recover
  db_dump
  smtpd.py
  git
Error: could not get runtime dependencies from /opt/homebrew/opt/libmpc@0.8/.brew/libmpc@0.8.rb!
</pre>

**Comment by reitermarkus** [comment]
> duck requirements say `depends_on java: ["1.8", :build]`

This means specifically “Java 8”, not “Java 8 or later”.

**Comment by MikeMcQuaid** [comment]
As @reitermarkus said. Additionally: we do not support pinning dependencies for other formulae, regardless of whether they are "new enough".

**Comment by Yann-R** [comment]
@MikeMcQuaid Thanks ! Really, I was not aware that the dependencies checking was not compatible with pinning.

@reitermarkus Thanks too ! OK, 1.8 means exactly 1.8 and not "1.8 or later"...
But I do have 1.8 on my system (as the output of `brew config`above showed...)
=> `Java: 13.0.2, 11.0.2, 1.8.0_241, 1.7.0_51`
So, how is it that this Java 1.8 requirement is not meet on my system? Is it because of the Mike's global answer above noticing that dependencies do not play well with pinning?

But, following the ideas in your answers:
- I unpinned `openjdk` (a bit worried that brew would then use it and install current Java 14) and relaunched `brew upgrade duck`
- It didn't download anything concerning `openjdk` (nor version 1.8, nor version 14)
- It downloaded `duck` bottle, that has been poured immediately
- And I re-pinned `openjdk` just afterwards :-)
So, it was simple behind the apparent problem !
Regards.
