### ISSUE TITLE
Shallow clones of brew repo not staying shallow

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#848]
Today I `git pull`ed my brew repo, which was a shallow clone of depth around 50, and suddenly it's a full clone.

This has been happening in recent weeks, though the clone doesn't always become entirely a full one.

I think it might have to do with something I've recently observed.  The commits page for brew is now regularly full of a bunch of merge commits by maintainers.  E.g., "maintainer X merged #N from maintainer-X/some_branch_name". This was formerly not the case.  The page used to just show the commits, not the commits capped off with a commit declaring a merge.  I don't know why it is now.  (FWIW, from a user perspective, it makes the formerly enjoyable enterprise of browsing and examining the latest commits into a difficult one.)

But then, I don't know much about git, so perhaps these two things are unrelated.  The suddenly unshallowed shallow clones thing is irritating, though.  If my connection is slow, I don't want to wait for commits from 2009 to be pulled in!

**Comment by MikeMcQuaid** [comment]
Do you have `HOMEBREW_DEVELOPER` set/unset?

**Comment by MikeMcQuaid** [comment]
Those things are likely unrelated. Is it literally a completely full clone now or just has more commits than you'd expect?

**Comment by chdiza** [comment]
I don't have `HOMEBREW_DEVELOPER` set.  (I used to, until it began triggering full clones a few months ago.)

It is a completely full clone AFAIK, in the sense that It's got the very first commit ever in HB, from May 2009, about "Belgian yeast".

Other times it doesn't become full, but I get *way* more commits than what has actually been committed since the last update.  E.g. several months' worth, even if I had updated earlier in the day.

**Comment by chdiza** [comment]
It just happened again: shallow clone to completely full.

Before I went to bed last night I shallowly cloned.  Since then, the only things committed to the brew repo are the mergings of PRs 850 (51bdd859) and 851 (b2cbe0479).  I cd'd to my local clone, did `git pull`, and the entire history got pulled in.

**Comment by chdiza** [comment]
If it helps:
```
remote: Counting objects: 63048, done.
remote: Compressing objects: 100% (16500/16500), done.
remote: Total 63048 (delta 45263), reused 62499 (delta 44752), pack-reused 0
Receiving objects: 100% (63048/63048), 14.71 MiB | 2.93 MiB/s, done.
Resolving deltas: 100% (45263/45263), completed with 414 local objects.
From https://github.com/Homebrew/brew
   a607a83..51bdd85  master     -> origin/master
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3
 * [new tag]         0.4        -> 0.4
 * [new tag]         0.5        -> 0.5
 * [new tag]         0.6        -> 0.6
 * [new tag]         0.7        -> 0.7
 * [new tag]         0.7.1      -> 0.7.1
 * [new tag]         0.8        -> 0.8
 * [new tag]         0.8.1      -> 0.8.1
 * [new tag]         0.9        -> 0.9
 * [new tag]         0.9.1      -> 0.9.1
 * [new tag]         0.9.2      -> 0.9.2
 * [new tag]         0.9.3      -> 0.9.3
 * [new tag]         0.9.4      -> 0.9.4
 * [new tag]         0.9.5      -> 0.9.5
 * [new tag]         0.9.8      -> 0.9.8
 * [new tag]         0.9.9      -> 0.9.9
Updating a607a83..51bdd85
Fast-forward
 Library/Homebrew/brew.sh  | 1 +
 Library/Homebrew/utils.rb | 2 +-
 2 files changed, 2 insertions(+), 1 deletion(-)
```

**Comment by chdiza** [comment]
And again, between 51bdd859ae49ba9c and d39eeac0d5041dbbc :(

**Comment by MikeMcQuaid** [comment]
What does `git show 29d85578e75170a6c0eaebda4d701b46f1acf446` say? Do you get shown a commit or an error message?

**Comment by chdiza** [comment]
A commit.

**Comment by chdiza** [comment]
(And in this instance I was surprised there was a commit there, because before I saw @MikeMcQuaid's question, I did as an experiment `git pull --depth=1` in my newly full repo, followed by a `git gc --aggressive`.  That shrunk the size of the `.git` folder quite a bit, and made `git log` only show one commit.  And yet, the very first HB commit is still lurking in there.)

**Comment by MikeMcQuaid** [comment]
@chdiza Do you have any other `git remote`s? Closing this out regardless, I'm afraid, as I'm not convinced there's anything we can do here.

**Comment by chdiza** [comment]
> Do you have any other git remotes?

No.

> I'm not convinced there's anything we can do here.

Something must've changed.  Are we sure it's not the advent of the merge commits mentioned earlier in this thread?  This started happening around the same time those started appearing.  Maybe the merges are bringing in something from way back that `git` thinks it needs to grab.  Tags?  I dunno.

**Comment by chdiza** [comment]
And again ... after I did a  fresh install with shallow clone a few minutes ago, `git pull` finds 327f5ca1778df and brings in the entire repo history.

**Comment by MikeMcQuaid** [comment]
> Are we sure it's not the advent of the merge commits mentioned earlier in this thread?

It could be but even if it is that's not a good enough reason for us to stop doing this, I'm afraid. It may mean we should stop bothering to use `--shallow` on Homebrew/brew.

**Comment by chdiza** [comment]
Out of curiosity, what was the reason for doing it in the first place?  I find it makes it much harder to read the GH commits page or `brew log`.  One thing I liked about HB (compared to the GH repos of other projects with multiple maintainers) was that HB didn't do that.

Oh well.

Anyway, I don't think this means there's no point to using `--shallow` during an install; it still makes the initial cloning nice and fast, even if subsequent updates take a while.  Particularly on installation, it's nice to just get up and running.

**Comment by MikeMcQuaid** [comment]
> Out of curiosity, what was the reason for doing it in the first place?

Preserves GPG verification, means we can use a single button for merging rather than `brew pull`, that it matters much less on this repo than Homebrew/homebrew-core.
