### ISSUE TITLE
SSL Error installing golang

### ISSUE THREAD

**Issue by JamesStidard** [Homebrew/brew#849]
Apologies if this is the wrong place to pos this issue - I couldn't find any maintainer contact listed against the brew formula. Tried golang repo already :).

I get an SSL error from curl when I try to `brew install golang`. Heres the trace:

```
$ brew install golang
==> Downloading https://homebrew.bintray.com/bottles/go-1.7.el_capitan.bottle.ta

curl: (51) SSL: certificate verification failed (result: 5)
Error: Failed to download resource "go"
Download failed: https://homebrew.bintray.com/bottles/go-1.7.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading https://storage.googleapis.com/golang/go1.7.src.tar.gz
Already downloaded: /Users/jamesstidard/Library/Caches/Homebrew/go-1.7.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.7.darwin-amd64.tar.gz

curl: (51) SSL: certificate verification failed (result: 5)
Error: Failed to download resource "go--gobootstrap"
Download failed: https://storage.googleapis.com/golang/go1.7.darwin-amd64.tar.gz
```

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Also, what happens if you run `curl https://homebrew.bintray.com/bottles/go-1.7.el_capitan.bottle.tar.gz`?

Thanks!

**Comment by Abbu1232** [comment]
varun@varun-HP-15-Notebook-PC:~$ brew install mongodb
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
==> Installing dependencies for mongodb: go, scons, libpcap
==> Installing mongodb dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.9.1.src.tar.gz
Already downloaded: /home/varun/.cache/Homebrew/go-1.9.1.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz
#####################                                                     30.2%
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
                                                                           0.0%
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
Error: Failed to download resource "go--gobootstrap"
Download failed: https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz
varun@varun-HP-15-Notebook-PC:~$ ^C
I tried a lot but can't sort out this problem please help.

**Comment by ilovezfs** [comment]
This is Homebrew not Linuxbrew.
