### ISSUE TITLE
Add package dependency tracking (like in apt)

### ISSUE THREAD

**Issue by GalacticLion7** [Homebrew/brew#8507]
Could Homebrew track package dependencies so unused packages dependencies could be easily removed (like in `apt autoremove`)?

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template.

`brew bundle dump` and `brew bundle cleanup` can do this for you.

**Comment by GalacticLion7** [comment]
It just gave me a list of formulae. When I try to uninstall one, it tells me that other formulae is depending on it.

**Comment by MikeMcQuaid** [comment]
You need to edit the `Brewfile` to only contain the formulae you want to be installed.

**Comment by dawidd6** [comment]
This external command might help you:
https://github.com/dawidd6/homebrew-autoremove

**Comment by GalacticLion7** [comment]
Thank you, this is exactly what I needed.

Question, why didn't it become an internal command?

**Comment by MikeMcQuaid** [comment]
I'd consider a PR to make it an official command if you're interested @dawidd6.

**Comment by maxim-belkin** [comment]
While we're at it... we can also modify/extend `brew leaves` to output "leaves" (or "branches" of formulae) that aren't "installed on request". And this can be part of `cleanup --unused`.

**Comment by jonchang** [comment]
This was fixed by @tie624 in https://github.com/Homebrew/brew/pull/9047; thanks!!
