### ISSUE TITLE
gnutls formula doesn't keep bottle file times

### ISSUE THREAD

**Issue by aconchillo** [Homebrew/brew#8514]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Use GnuTLS Guile bindings.

## What happened (include command output)

Guile detects that `/usr/local/Cellar/gnutls/3.6.14/share/guile/site/3.0/gnutls.scm` is newer than `/usr/local/Cellar/gnutls/3.6.14/lib/guile/3.0/site-ccache/gnutls.go`.

If you untar the bottle file manually both files have the same time as expected. I would also expect `cp -pR` (executed during `brew install`) to maintain original file times. Actually some files maintain the same time as in the bottle and some files do not. In the case above, `/usr/local/Cellar/gnutls/3.6.14/share/guile/site/3.0/gnutls.scm` has the installation time and `/usr/local/Cellar/gnutls/3.6.14/lib/guile/3.0/site-ccache/gnutls.go`.

```
tar xof /Users/aleix/Library/Caches/Homebrew/downloads/3beb2257ab02f02f52ba80ddb61a6f8a2c9731a7f949b6c4b8cfbf93e7976a72--gnutls-3.6.14.catalina.bottle.1.tar.gz -C /var/folders/h3/spftw_2n367_0k8b8ptn43mm0000gn/T/d20200827-45350-1kagroh
cp -pR /var/folders/h3/spftw_2n367_0k8b8ptn43mm0000gn/T/d20200827-45350-1kagroh/gnutls/. /usr/local/Cellar/gnutls
```

However, see times after `brew install gnutls`:

```
❯ l /usr/local/Cellar/gnutls/3.6.14/share/guile/site/3.0/gnutls.scm
-rw-r--r--  1 aleix  staff    24K Aug 27 10:27 /usr/local/Cellar/gnutls/3.6.14/share/guile/site/3.0/gnutls.scm
❯ l /usr/local/Cellar/gnutls/3.6.14/lib/guile/3.0/site-ccache/gnutls.go
-r--r--r--  1 aleix  staff   197K Jun  3 06:12 /usr/local/Cellar/gnutls/3.6.14/lib/guile/3.0/site-ccache/gnutls.go
```

<details>
  <summary>Command output</summary>
  <pre>

❯ guile
GNU Guile 3.0.4
Copyright (C) 1995-2020 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)> (use-modules (gnutls))
;;; note: source file /usr/local/share/guile/site/3.0/gnutls.scm
;;;       newer than compiled /usr/local/lib/guile/3.0/site-ccache/gnutls.go
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /usr/local/share/guile/site/3.0/gnutls.scm
;;; compiled /Users/aleix/.cache/guile/ccache/3.0-LE-8-4.3/usr/local/Cellar/gnutls/3.6.14/share/guile/site/3.0/gnutls.scm.go
scheme@(guile-user)>

  </pre>
</details>

Note that in the Guile message above Guile is using the links from that point to the Cellar files. But internally Guile uses the syscall `stat` (which follows links) to get the file time.

## What you expected to happen

Guile should not recompile `gnutls.scm`. And I would also expect `/usr/local/Cellar/gnutls/3.6.14/share/guile/site/3.0/gnutls.scm` has the original file time from the bottle not the installation time.

I don't see any more commands with `brew install -v gnutls` that would cause this.

## Step-by-step reproduction instructions (by running `brew` commands)

```
$ brew install -v gnutls
$ export GUILE_LOAD_PATH=/usr/local/share/guile/site/3.0
$ export GUILE_LOAD_COMPILED_PATH=/usr/local/lib/guile/3.0/site-ccache
$ export GUILE_SYSTEM_EXTENSIONS_PATH=/usr/local/lib/guile/3.0/extensions
$ guile
GNU Guile 3.0.4
Copyright (C) 1995-2020 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)> (use-modules (gnutls))
```

## Output of `brew config` and `brew doctor` commands

<pre>
❯ brew config
HOMEBREW_VERSION: 2.4.13-277-gff8d30d
ORIGIN: https://github.com/Homebrew/brew
HEAD: ff8d30df7439a665be4620b601a390d624f10f98
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2576cc1f1992e3eb250ddeb90afcc29613bccc29
Core tap last commit: 69 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs -q -nw
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 1103.0.32.59
Xcode: N/A
❯ brew doctor
Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment]
This is specific to a formula so should have been filed in Homebrew/homebrew-core (and I'll move it there after this comment).

This is definitely on the level of "we'll review a pull request to fix it" because I don't see the timestamp on a file as being higher priority than anything in our backlog, sorry.
