### ISSUE TITLE
brew install freetds --with-unixodbc fails 

### ISSUE THREAD

**Issue by terryllowery** [Homebrew/brew#852]
When you run brew install freetds --with-unicodbc it fails due to a bad url\version of freetds. 

freetds is version 1.00.14.tar.gz on the fossils.org url

The correct url is https://fossies.org/linux/privat/freetds-1.00.14.tar.gz/ for the mirror.

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information in a new issue on Homebrew/homebrew-core so we can help you with your problem.

Thanks!
