### ISSUE TITLE
brew installation seems to be relying on hardcoded /usr and /usr/bin/sudo

### ISSUE THREAD

**Issue by alexanderadam** [Homebrew/brew#8528]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

Installing homebrew on Termux / Android

## What happened (include command output)

<details>
  <summary>Command output</summary>

```bash

~ ❯❯❯ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
/bin/bash: line 276: cd: /usr: No such file or directory
/bin/bash: line 1: /usr/bin/sudo: No such file or directory
```

![Homebrew installation on Termux (Android 10, Samsung Galaxy Tab S6)](https://user-images.githubusercontent.com/372620/91614385-c6961900-e981-11ea-9a27-9a9f78097be1.jpg)

</details>

## What you expected to happen

That the installation should work

## Step-by-step reproduction instructions (by running `brew` commands)

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

## Output of `brew config` and `brew doctor` commands

well…
<pre>
command not found
</pre>

**PS:** At first I thought that this should be [a Termux issue](https://github.com/termux/termux-packages/issues/2071) but then I read that brew shouldn't be relying on `sudo` anymore. So IMHO this is most likely a bug in homebrew.
**PPS:** I'm not sure whether this is relevant, but I'm also using [`rbenv`](https://github.com/rbenv/rbenv) on this machine With a ruby global default of Ruby version `2.6.6`.

**Comment by maxim-belkin** [comment]
Thanks for the report!

1. This is an issue with [Homebrew/install](https://github.com/Homebrew/install) not [Homebrew/brew](https://github.com/Homebrew/brew), so please submit a report there.
2. Your Ruby version is OK: Homebrew uses 2.6.X.
3. If you have time, we'd appreciate a PR to fix these issues.

Thanks again!

**Comment by sjackman** [comment]
Android is not a supported target platform of Homebrew. That said
see https://github.com/Linuxbrew/brew/wiki/Android
and https://docs.brew.sh/Homebrew-on-Linux#alternative-installation

**Comment by alexanderadam** [comment]
Thank you for your fast response.

> Android is not a supported target platform of Homebrew.

Will this change in the future? Can I open an issue for this in [Homebrew/install](https://github.com/Homebrew/install) for tracking purposes?

**Comment by MikeMcQuaid** [comment]
> Will this change in the future? Can I open an issue for this in [Homebrew/install](https://github.com/Homebrew/install) for tracking purposes?

No and no, sorry.
