### ISSUE TITLE
error: RPC failed; curl 18 transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by Sulcalibur** [Homebrew/brew#8550]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install Homebrew on a new MacBook

## What happened (include command output)

Seemed to install but cannot `brew install …` anything

<details>
  <summary>Command output</summary>
  <pre>

  brew doctor
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` exited with 128.
Error: Failure while executing; `/usr/local/bin/brew tap homebrew/core` exited with 1.

  </pre>
</details>

## What you expected to happen

Not have the error

## Step-by-step reproduction instructions (by running `brew` commands)

Any `brew install …` has the same error after it tries to clone `homebrew-core`

## Output of `brew config` and `brew doctor` commands

<pre>
brew config
HOMEBREW_VERSION: 2.4.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: eb09a09b663be27f606a6c85911ceece72f2574e
Last commit: 14 hours ago
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit icelake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 12.0.0.0.1.1597368733
Xcode: 11.6

brew doctor
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (8/8), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` exited with 128.
Error: Failure while executing; `/usr/local/bin/brew tap homebrew/core` exited with 1.
</pre>

**Comment by maxim-belkin** [comment]
I experienced the same problem on several different systems, so this is most-likely a GitHub problem.
Try in a couple of minutes let us know if you still see it.

**Comment by Sulcalibur** [comment]
> I experienced the same problem on several different systems, so this is most-likely a GitHub problem.
> Try in a couple of minutes let us know if you still see it.

Hi, @maxim-belkin I also tried on different laptops and had the same problem. I have been trying at various times over the last couple of days. I'll keep persevering though. :)

**Comment by maxim-belkin** [comment]
For me it lasted just a couple of minutes and that's it. It looks like this issue is caused by slow network, see https://stackoverflow.com/questions/38618885, https://avinash.com.np/2016/11/15/git-clone-in-a-slow-connection/, ...

Try this:
```
mkdir -p /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
git clone --depth=1 https://github.com/Homebrew/homebrew-core.git
git fetch --unshallow
brew doctor
```

**Comment by Sulcalibur** [comment]
> Try this:
> 
> ```
> mkdir -p /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
> cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
> git clone --depth=1 https://github.com/Homebrew/homebrew-core.git
> git fetch --unshallow
> brew doctor
> ```

This worked!!! Thank you! You crafty genius!!! :)
