### ISSUE TITLE
Recent brew update on linux - with 'broken' packages such as vim 

### ISSUE THREAD

**Issue by ipstone** [Homebrew/brew#8574]
Hello, I have been using brew (linuxbrew) on centOS 7, but recent vim package update, some features such as python3+ support was removed. This in turn affected the vim plugin that I used with python3 underneath.  Should I report this issue here? -- I could not find the repo for the formula to report in the formula. [update: I just found the formula repo, and reported there, you can ignore this first part. But I do have question regarding the following general question for setup brew properly on centOS7]

Related, I have tried to install emacs onto centOS7 through brew multiple times, but could not get it compiled (without root right on the machine). Brew works beautifully on mac, but somehow on linux (centos7 is old but many are still being used in production) the stability/functionalities are not on par with mac.  

I would much appreciate if you have suggestions on how to setup brew properly on older linux distro such as centOS etc - for which I have a complex environment (built in - old libraries) including conda (needed for many scientific libraries) that could have conflicting libraries etc.

Thanks!

**Comment by MikeMcQuaid** [comment]
Please always fill the issue template.

This is a better fit for our https://github.com/homebrew/discussions or https://discourse.brew.sh
