### ISSUE TITLE
Problems in the shell completion documents

### ISSUE THREAD

**Issue by HsuanTingLu** [Homebrew/brew#8600]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was updating my `~/.bash_profile` and wanted to renew my homebrew bash-completion settings.
I applied the changes that #6322 introduced to [this section of the document](https://docs.brew.sh/Shell-Completion#configuring-completions-in-bash), but after adding the changes, bash-completion seems to be gone.

## What happened (include command output)

After moving the `for` loop into the `else` section, (see ***Step-by-step reproduction instructions***),
homebrew bash-completion seems gone.

## What you expected to happen

Bash can autocomplete `brew upgrade` after I typed `brew upg` then press TAB

## Step-by-step reproduction instructions (by running `brew` commands)

old config (that works):
```bash
if type brew &>/dev/null; then
    HOMEBREW_PREFIX="$(brew --prefix)"
    for COMPLETION in ${HOMEBREW_PREFIX}/etc/bash_completion.d/*; do
        [[ -f $COMPLETION ]] && source "$COMPLETION"
    done                                                                                                                                                                 
    if [[ -f ${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh ]]; then
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
    fi  
fi
```

new config (that completion has disappeared):
```bash
if type brew &>/dev/null; then
    HOMEBREW_PREFIX="$(brew --prefix)"
    if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
    else
        for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
            [[ -r "$COMPLETION" ]] && source "$COMPLETION"
        done
    fi
fi
```

In the new config (the currently recommended setting), the shell seems to enter the second `if` clause, thus skipping the `for` loop, which, after some experiment, seems to be the part that provides completion for my bash.

I noted that #6322 was aiming to solve problems for those who installed the formula `bash-completion`, but I don't have that installed.

### brew config
<pre>
HOMEBREW_VERSION: 2.4.16-131-g2d46ab1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2d46ab18bdfa2ad2df9763bb2f93b7b124bc5b76
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fdbf28a81a230cf6ed09a364a57b98daefa83bea
Core tap last commit: 45 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.pPI7zGdPVL/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_265
macOS: 10.15.6-x86_64
CLT: 1103.0.32.62
Xcode: 11.6
XQuartz: 2.7.11 => /opt/X11
</pre>

### brew doctor
<pre>
Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment]
> I noted that #6322 was aiming to solve problems for those who installed the formula `bash-completion`, but I don't have that installed.

What's the output of `ls $(brew --prefix)/etc/bash_completion.d/` on your machine?

**Comment by HsuanTingLu** [comment]
> What's the output of `ls $(brew --prefix)/etc/bash_completion.d/` on your machine?

output:
<pre>
bash                  brew-services         gio                   gresource             kind                  tmux
bazel-complete.bash   gapplication          git-completion.bash   gsettings             npm
brew                  gdbus                 git-prompt.sh         hwloc-completion.bash rclone
</pre>

**Comment by gromgit** [comment]
What's the output of `cat $(brew --prefix)/etc/profile.d/bash_completion.sh`?

**Comment by HsuanTingLu** [comment]
> cat $(brew --prefix)/etc/profile.d/bash_completion.sh

output:

<pre>
if [ -n "${BASH_VERSION-}" -a -n "${PS1-}" -a -z "${BASH_COMPLETION_VERSINFO-}" ]; then

    # Check for recent enough version of bash.
    if [ ${BASH_VERSINFO[0]} -gt 4 ] || \
       [ ${BASH_VERSINFO[0]} -eq 4 -a ${BASH_VERSINFO[1]} -ge 1 ]; then
        [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" ] && \
            . "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion"
        if shopt -q progcomp && [ -r /usr/local/Cellar/bash-completion@2/2.8/share/bash-completion/bash_completion ]; then
            # Source completion code.
            . /usr/local/Cellar/bash-completion@2/2.8/share/bash-completion/bash_completion
        fi
    fi

fi
</pre>

**Comment by gromgit** [comment]
That's an old version of `bash-completion@2` you have installed, and should be upgraded.

However, first check the output of `echo $BASH_VERSION`. I'm guessing it says `3.2.57(1)-release` or something earlier than 4.x, which means you're using the seriously outdated macOS system-bash. In that case, you need to uninstall `bash-completion@2` and install `bash-completion` instead.

**Comment by HsuanTingLu** [comment]
> That's an old version of `bash-completion@2` you have installed, and should be upgraded.

I don't recall installing this.
Didn't find any version of it. Could it be hiding somewhere unintuitive maybe?

Here are some other information that you might be interested in:

```ls /usr/local/Cellar/ | grep bash``` gives
<pre>
bash
</pre>

```brew list | grep bash``` gives
<pre>
bash
</pre>

> However, first check the output of `echo $BASH_VERSION`. I'm guessing it says `3.2.57(1)-release` or something earlier than 4.x, which means you're using the seriously outdated macOS system-bash. In that case, you need to uninstall `bash-completion@2` and install `bash-completion` instead.

```echo $BASH_VERSION``` gives
<pre>
5.0.18(1)-release
</pre>

as it is the bash from the homebrew formula `bash`

`echo $SHELL` gives `/usr/local/bin/bash`

BTW this completion-disappearance can be reproduced on homebrew-bash(5.0) and system-bash(3.2)

**Comment by gromgit** [comment]
> I don't recall installing this.

Your `bash_completion.sh` says you've installed version 2.8 of `bash_completion@2` (current version is 2.11). It's right there in the code you posted:
```
        if shopt -q progcomp && [ -r /usr/local/Cellar/bash-completion@2/2.8/share/bash-completion/bash_completion ]; then
            # Source completion code.
            . /usr/local/Cellar/bash-completion@2/2.8/share/bash-completion/bash_completion
```
> Didn't find any version of it. Could it be hiding somewhere unintuitive maybe?

`brew info bash-completion@2` should say, among other things, `Poured from bottle on ...`. If instead it says `Not installed`, something's b0rked with your setup.

Just to be sure, what does `ls -l /usr/local/etc/profile.d/bash_completion.sh` say?

Also, altering your `~/.bash_profile` (or wherever you put the completion code) as follows:
```
if type brew &>/dev/null; then
    HOMEBREW_PREFIX="$(brew --prefix)"
    if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
        # Let's make sure we actually got here...
        echo "WE HAVE A WINNER!!!"
    else
...
```
then open a new shell and see if you're a winner. If not, your completion code is in the wrong file.

**Comment by HsuanTingLu** [comment]
> > I don't recall installing this.
> 
> Your `bash_completion.sh` says you've installed version 2.8 of `bash_completion@2` (current version is 2.11). It's right there in the code you posted:
> 
> ```
>         if shopt -q progcomp && [ -r /usr/local/Cellar/bash-completion@2/2.8/share/bash-completion/bash_completion ]; then
>             # Source completion code.
>             . /usr/local/Cellar/bash-completion@2/2.8/share/bash-completion/bash_completion
> ```

Like what I've shown in the previous reply,
`ls /usr/local/Cellar/ | grep bash` gives only `bash`,
doesn't that mean that even if I've somehow installed `bash-completion` in the past, the if-clause will not be entered anyway?

But yes maybe it was installed as a dependency or something in the past, sounds like a good clue, thank you, I'll investigate further.

> > Didn't find any version of it. Could it be hiding somewhere unintuitive maybe?
> 
> `brew info bash-completion@2` should say, among other things, `Poured from bottle on ...`. If instead it says `Not installed`, something's b0rked with your setup.

It is consistent with the output of `brew list | grep bash` which only shows `bash`
`brew info bash-completion@2` says `Not installed`

> Just to be sure, what does `ls -l /usr/local/etc/profile.d/bash_completion.sh` say?

`-rw-r--r--  1 hehehe  admin  734 May  7  2018 /usr/local/etc/profile.d/bash_completion.sh`
 
> Also, try altering your `~/.bash_profile` (or wherever you put the completion code) as follows:
> 
> ```
> if type brew &>/dev/null; then
>     HOMEBREW_PREFIX="$(brew --prefix)"
>     if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
>         source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
>         # Let's make sure we actually got here...
>         echo "WE HAVE A WINNER!!!"
>     else
> ...
> ```
> 
> then open a new shell and see if you're a winner. If not, your completion code is in the wrong file.
 
shell does output: `WE HAVE A WINNER!!!`
Not a surprise given the results shown in https://github.com/Homebrew/brew/issues/8600#issuecomment-687569704 though

**Comment by HsuanTingLu** [comment]
By the way,
disclaimer: I'm not familiar with shells

Should a proper minimum auto complete setup have `bash-completion` installed? (I'm using bash-5.0 so it's probably `bash-completion@2` in this case)

**Comment by gromgit** [comment]
Apologies, I was distracted enough to miss the blindingly obvious clues you dropped: You have an _improper snapshot_ of `bash_completion@2`, probably "installed" via a recursive copy from another machine, or something similar. The clincher was actually:
```
$ ls -l /usr/local/etc/profile.d/bash_completion.sh
-rw-r--r-- 1 hehehe admin 734 May 7 2018 /usr/local/etc/profile.d/bash_completion.sh
```
In a proper installation, that should've been a symbolic link instead:
```
$ ls -l /usr/local/etc/profile.d/bash_completion.sh
lrwxr-xr-x 1 aho wheel 68 Sep  5 19:35 /usr/local/etc/profile.d/bash_completion.sh -> '../../Cellar/bash-completion@2/2.11/etc/profile.d/bash_completion.sh'
```
A `brew install --force bash-completion@2` should fix the issue.

**Comment by HsuanTingLu** [comment]
Thank you, that was spot-on.

Force installing failed though, reporting that the file already exists and demands a `brew link --overwrite bash-completion@2`.
After linking, completion works under [the recommended setting](https://docs.brew.sh/Shell-Completion#configuring-completions-in-bash) too. Just to be sure, I uninstall - cleanup - install again, everything works fine.

I did uninstall `bash-completion@2` in the end though, trying to reduce my setup to a minimum.
Thank you for solving this
