### ISSUE TITLE
Git download strategy: shallow clone for submodules

### ISSUE THREAD

**Issue by anishathalye** [Homebrew/brew#8607]
# Feature suggestion

When cloning modules from a Git repo, brew currently uses the `--depth=1` option (shallow clones) when possible. If the repository contains submodules, brew also clones those, but it does a full clone. It would be great to do a shallow clone there as well, to save bandwidth and speed up the download.

# A detailed description of the proposed feature

brew uses [shallow clones](https://github.com/Homebrew/brew/blob/d558b9f9e23fc0ad17e5728803ba441aca182cf7/Library/Homebrew/download_strategy.rb#L755) when cloning from Git (when the remote is [known](https://github.com/Homebrew/brew/blob/d558b9f9e23fc0ad17e5728803ba441aca182cf7/Library/Homebrew/download_strategy.rb#L674) to support it), but for submodules, a [full clone](https://github.com/Homebrew/brew/blob/d558b9f9e23fc0ad17e5728803ba441aca182cf7/Library/Homebrew/download_strategy.rb#L831) is always used (through `git submodule update --init --recursive`).

Implementing this feature may not be super straightforward. We can't, for example, just pass `--depth=1` to the `git submodule init`, because some of the submodules may point to remotes that don't support shallow clones. We could use `git submodule status` and friends to determine which submodules point to remotes that support shallow clones, and then invoke `git submodule update` with or without `--depth=1` on individual submodules.

I ran into this when installing [riscv-gnu-toolchain](https://github.com/riscv/homebrew-riscv/blob/master/riscv-gnu-toolchain.rb) from source. The download size is pretty huge, and shallow clones of submodules make a pretty big difference.

# The motivation for the feature

Save bandwidth and speed up downloads.

# How the feature would be relevant to at least 90% of Homebrew users

Without looking at analytics data, I can't say for sure, but I expect that most Homebrew users end up cloning something from Git at some point (e.g. when using flags that require compiling from source rather than using a bottle), and many Git repos use submodules.

# What alternatives to the feature have been considered

N/A? It could be left as-is. This feature doesn't affect functionality for end users, it would just make things faster.

# Implementation

If a core maintainer would like to implement this, that would be great. ~If this feature is desired / is likely to be merged if a PR is submitted, but the team doesn't have time to work on it, I'm happy to work on a PR.~ Edit: see below, I don't have time to implement this at the moment.

**Comment by MikeMcQuaid** [comment]
Seems like a good idea!

**Comment by SeekingMeaning** [comment]
Maybe [`--recommend-shallow`](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt---no-recommend-shallow) would be useful for this

**Comment by Rylan12** [comment]
@anishathalye I'd say go ahead and start on working on this if its something you're interested in doing. Feel free to open a draft PR or ask questions here if you need help!

**Comment by anishathalye** [comment]
> Maybe [`--recommend-shallow`](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt---no-recommend-shallow) would be useful for this

It looks relevant, but it doesn't do quite what we want. `--recommend-shallow` (which is the default) says whether the initial clone should follow the shallow recommendation in `submodule.<name>.shallow`. Looking at the relevant [code in git/builtin/submodule--helper.c](https://github.com/git/git/blob/3a238e539bcdfe3f9eb5010fd218640c1b499f7a/builtin/submodule--helper.c#L1728-L1729) confirms this: when both `submodule.<name>.shallow` and `--recommend-shallow` are given, the clone command uses `--depth=1`.

**Comment by Akylzhan** [comment]
Hello guys, I am new here
But I researched a bit and how do you think, will be the issue solved if we replace [this](https://github.com/Homebrew/brew/blob/d558b9f9e23fc0ad17e5728803ba441aca182cf7/Library/Homebrew/download_strategy.rb#L832) to this:
```
git submodule foreach '
a=$(git config -f $toplevel/.gitmodules --get submodule.$name.shallow)
if [ $a = true ]; then
  git submodule update --init --recursive --depth=1
else
  git submodule update --init --recursive
fi
'

```

**Comment by anishathalye** [comment]
That's already effectively what happens (but recursively) with the code as it's written. Git by default respects `submodule.<name>.shallow`. The issue is that most people don't use that config, but we want to clone submodules shallowly anyways (when possible).

**Comment by JJJensen** [comment]
Is it just me, or should this really be `--depth 1` (space) instead of `--depth=1` (equal sign)?

As far as I can see, `--depth=1` checks out *everything* (actually it times out after 5 minutes), while `--depth 1` does a shallow clone (it takes like 10 seconds).

**Comment by cnnrmnn** [comment]
@anishathalye Are you still working on this issue?

**Comment by anishathalye** [comment]
Sorry, nope, too many things to do at the moment. Feel free to implement it if you're interested, you won't be duplicating work.

**Comment by cnnrmnn** [comment]
@anishathalye No worries at all. Just wanted to make sure I wouldn't be duplicating your work :)

**Comment by cnnrmnn** [comment]
Why is there a shallow clone allowlist? Are shallow clones not supported everywhere?

**Comment by Rylan12** [comment]
> Why is there a shallow clone allowlist? Are shallow clones not supported everywhere?

Correct (I assume you're talking about this)

https://github.com/Homebrew/brew/blob/3476ca7b8ff889ef61e65783d35d1b2073bd4012/Library/Homebrew/download_strategy.rb#L779-L784

If the submodule isn't from one of those sources I think it will need to be a full clone.

**Comment by cnnrmnn** [comment]
Correct. I inferred that, but I was unsure as to why there is an allowlist. [Shallow cloning](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) is a relatively old feature of git and should be supported by any git server one might clone from.

**Comment by MikeMcQuaid** [comment]
> Seems like a good idea!

To adjust my previous comment: the rule of thumb for shallow clones: they are only better when you are never going to `git fetch` or `git pull` in them e.g. in a CI job where you clone once and then delete the repo/VM.

Given this, we should consider in which cases we expect to `fetch` a shallow clone again and not fetch in those cases.

**Comment by Rylan12** [comment]
If you have the repository checked out from installing a certain version and then try to upgrade to a new formula version that checks out the same repo, does Homebrew reclone or update the old one?

If the latter, we're probably breaking our own rule already because allowing shallow clones in these situations raising the possibility of needing to fetch later. We could instead just delete the old clone and reclone (shallowly). I'm not sure what's done currently to know whether this is already implemented or would be desired.

**Comment by MikeMcQuaid** [comment]
> If the latter, we're probably breaking our own rule already because allowing shallow clones in these situations raising the possibility of needing to fetch later.

Yes, we likely are.

> We could instead just delete the old clone and reclone (shallowly).

This is more expensive and, over time, slower, unfortunately.

**Comment by cnnrmnn** [comment]
At the moment, the update method of `GitDownloadStrategy` calls `update_repo` which performs a fetch even if the clone is shallow. Similar logic is used to update submodules.

https://github.com/Homebrew/brew/blob/53b9f8528100ae999bc954d73b9918772a8ecfd9/Library/Homebrew/download_strategy.rb#L902-L916

I'm not sure that it's possible to know ahead of time if a fetch will be performed on a shallow clone for the reasons @Rylan12 mentioned. Should shallow clones even be used at all? It seems like they're being misused.

**Comment by MikeMcQuaid** [comment]
> Should shallow clones even be used at all? It seems like they're being misused.

I'd say: no, we shouldn't use them. We should unshallow them before we attempt to fetch from them and stop creating any new shallow clones.
