### ISSUE TITLE
How to install home-brew from a python script?

### ISSUE THREAD

**Issue by gauthierbuttez** [Homebrew/brew#8619]
**Environment**

Python 3.7

Mac OS Catalina 10.15

**Problem**

This makes me crazy!

I need to install home-brew from my python script:

When I run:

    #mac_account is actual user who is not root
    f'sudo -u {mac_account} /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"'

I get this error output:

    Need sudo access on macOS

When I run the command as Admin:

    /usr/bin/osascript -e 'do shell script "{os.path.join(os.path.dirname(sys.argv[0]),'Install.sh')} args 2>&1 etc" with administrator privileges'

here is Install.sh source code:

    #!/bin/sh
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)

I get this error output:

    Don't run this as root!

**So How can we install home-brew from a python script?**

If I run it as admin, it says "Don't run this as root!"
If I run it as non-admin, it says "Need sudo access on macOS"

**Comment by maxim-belkin** [comment]
You have to fill out our issue template in order to get help here. Your problem, however, isn't related to Homebrew itself but to a way to call Homebrew installation script from Python. This is better to discuss at https://github.com/Homebrew/discussions/discussions

**Comment by gauthierbuttez** [comment]
> You have to fill out our issue template in order to get help here. Your problem, however, isn't related to Homebrew itself but to a way to call Homebrew installation script from Python. This is better to discuss at https://github.com/Homebrew/discussions/discussions

Thank you
