### ISSUE TITLE
brew install automatically stashing changes

### ISSUE THREAD

**Issue by jkarneges** [Homebrew/brew#862]
Hi devs,

Whenever I run "brew install" on a formula I am testing locally (based on changes against homebrew-core), my changes are stashed and the previous formula ends up being installed. This seems to be new behavior after recently running "brew update".

How do I work around this? Thanks.

**Comment by DomT4** [comment]
If you're making changes to formulae locally you should almost always, at least temporarily, set `HOMEBREW_DEVELOPER`. Pretty sure that resolves the behaviour here as well.

**Comment by jkarneges** [comment]
Thanks. While looking up that variable I also found `HOMEBREW_NO_AUTO_UPDATE` which worked too. https://github.com/Homebrew/brew/issues/716
