### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/brew#8629]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Figure out the new syntax for the brew command, so I looked at the manual page at 

https://docs.brew.sh/Manpage

## What happened (include command output)

The page lists commands like
`brew cask outdated`
which when run give
<details>
  <summary>Command output</summary>
  <pre>
brew cask outdated         
Warning: Calling brew cask outdated is deprecated! Use brew outdated --cask instead.  </pre>
</details>

## What you expected to happen

Up to date documentation consistent with the current syntax

## Step-by-step reproduction instructions (by running `brew` commands)

Not relevant

## Output of `brew config` and `brew doctor` commands

Not relevant.

**Comment by claui** [comment]
Related: https://github.com/Homebrew/homebrew-cask/pull/88682

**Comment by MikeMcQuaid** [comment]
@reitermarkus I guess this needs to call `hide_from_man_page!  if DEPRECATED_COMMANDS.key?(command)` somehow in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/cmd.rb. Mind giving it a go?

**Comment by dtrodrigues** [comment]
https://github.com/Homebrew/brew/pull/8899 being merged resolved this.
