### ISSUE TITLE
Send "Tapping" output to stderr

### ISSUE THREAD

**Issue by stefansundin** [Homebrew/brew#8633]
# Bug report

## What you were trying to do (and why)

The first time that you run `brew services list`, it will first tap the homebrew/services repository and then list the services. This works great, but two extra lines are sent to stdout because it is the first time that `brew services` is run.

There is a nice app called [BrewServicesMenubar](https://github.com/andrewn/brew-services-menubar) that makes it very easy to start/stop/restart homebrew services. If you use it and it causes Homebrew to tap the homebrew/services, then it doesn't currently expect these extra lines and it behaves strangely. It is a minor bug and doesn't cause it to crash.

I opened [a PR](https://github.com/andrewn/brew-services-menubar/pull/13) for that project to fix the problem there by accounting for this possibility, but I think the better place to fix this may be in Homebrew itself. If you disagree, then hopefully Andrew can merge my PR and release a new version of his app.

You can easily reproduce this by deleting `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services`, which causes `brew services` to tap the repository again. Note that the BrewServicesMenubar app will run `brew services list` after starting, so if you just let it sit and then click it, then you will just see a short flash of the two extra entries in the list (see https://github.com/andrewn/brew-services-menubar/pull/13 for a screenshot).

git sends all of the output from `git clone` to stderr, so use `brew services list 2>/dev/null` to exclude that line from your output.

## What happened (include command output)

<details>
  <summary>First-time `brew services list` output (stdout)</summary>
  <pre>
==> Tapping homebrew/services
Tapped 1 command (40 files, 338.6KB).
Name    Status  User Plist
caddy   stopped
unbound stopped
  </pre>
</details>

<details>
  <summary>Subsequent `brew services list` output (stdout)</summary>
  <pre>
Name    Status  User Plist
caddy   stopped
unbound stopped
  </pre>
</details>

## What you expected to happen

Send informational output to stderr. One could even argue that the header (`Name    Status  User Plist`) belongs on stderr.

## Step-by-step reproduction instructions (by running `brew` commands)

```
$ rm -rf /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services
$ brew services list 2>/dev/null
==> Tapping homebrew/services
Tapped 1 command (40 files, 338.6KB).
Name    Status  User Plist
caddy   stopped
unbound stopped
$ brew services list 2>/dev/null
Name    Status  User Plist
caddy   stopped
unbound stopped
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.4.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2a4c9f610e69b9fed1eec61ac2c53e4b11a32e4c
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 85bdb1a3845135bb3b7311ae6adcae8c82447951
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 12.0.0.0.1.1597368733
Xcode: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> /Users/stefan/.bash_profile
</pre>

**Comment by nandahkrishna** [comment]
@jonchang with the latest commit in #8633, here's the output:
```
➜ brew services list 2> test.txt
Name    Status  User Plist
unbound stopped      
➜ cat test.txt
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
Tapped 1 command (40 files, 337.2KB).
```

To fix the remaining part (the header, to be specific), I'll create a PR in homebrew-services and tag you. Is this alright so far?

**Comment by stefansundin** [comment]
Yes, looks great to me!

So the plan is to send the header to stderr as well? I wonder if it may be better to have a switch to disable it from being output perhaps, i.e. something like `--no-header`. But do whatever you think is best.

Thanks for the work on this!

**Comment by reitermarkus** [comment]
I think it makes sense for the header to be present all the time, since it provides a bit of context for the `Cloning…` output coming from `git`.

**Comment by reitermarkus** [comment]
Actually the `--quiet` flag will already hide it.

**Comment by nandahkrishna** [comment]
The changes made in #8624 should fix this issue - most of the informational output during tapping has been printed to `stderr`.

**Comment by stefansundin** [comment]
Thank you! Seems to work great. The bug is gone. 🎉 

It doesn't seem like https://github.com/Homebrew/brew/pull/8673 solved the `--quiet` issue though.
