### ISSUE TITLE
Sending a Ctrl-C (SIGINT) mid-operation to `brew bundle` corrupted `bash` for all running shell sessions

### ISSUE THREAD

**Issue by luizberti** [Homebrew/brew#8637]
1. I ran `brew bundle --taps` to list all tap dependencies;
2. `brew` decided to update beforehand;
3. `brew` started installing things from the bundle, instead of listing the `tap` dependencies because I forgot to use the `list` subcommand;
4. I hit Ctrl-C to avoid reinstalling everything on my computer, and it returned a bash syntax error when quitting;
5. Now any brew command returns that bash syntax error, as does trying to start `bash` from within that shell;
6. Exiting all shells that were running when this happened and starting a new ones restored things back to normal, but still unclear as to what happened 🤷🏻‍♂️

_Do note that I tried re-triggering this problem, but haven't been able to reproduce it again. Still I wonder which parts of brew could be messing with the outer shell environment..._

**Here's the entire shell session where this happened:**
```
luizberti@~/Desktop/dotfiles$ brew bundle --taps
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from b2d9594ca to d0e1595fc.
Updated 4 taps (homebrew/core, homebrew/cask, homebrew/cask-fonts and caskroom/cask).
==> New Formulae
croc
==> Updated Formulae
Updated 6 formulae.
==> Updated Casks
aerial                                       marshallofsound-google-play-music-player
aerial                                       multibit-hd
alt-tab                                      multibit-hd
Installing dash
^C
-bash: -: syntax error: operand expected (error token is "-")
-bash: test: -lt: unary operator expected

luizberti@~/Desktop/dotfiles$ brew bundle --taps
Killed: 9
-bash: -: syntax error: operand expected (error token is "-")
-bash: test: too many arguments

luizberti@~/Desktop/dotfiles$ brew bundle --taps
Killed: 9
-bash: -: syntax error: operand expected (error token is "-")
-bash: test: too many arguments

luizberti@~/Desktop/dotfiles$ brew bundle
Killed: 9
-bash: -: syntax error: operand expected (error token is "-")
-bash: test: too many arguments

luizberti@~/Desktop/dotfiles$ brew list
Killed: 9
-bash: -: syntax error: operand expected (error token is "-")
-bash: test: too many arguments

luizberti@~/Desktop/dotfiles$ bash
Killed: 9
-bash: -: syntax error: operand expected (error token is "-")
-bash: test: too many arguments
```

**Comment by MikeMcQuaid** [comment]
No idea how to reproduce or fix this, sorry. Please always use the issue template.
