### ISSUE TITLE
Suggestion: use GitHub-api to check updates for brew and homebrew-core

### ISSUE THREAD

**Issue by shcai97** [Homebrew/brew#8647]
# Feature suggestion

# A detailed description of the proposed feature

`brew update` uses GitHub API to check updates for taps other than `homebrew-core`. I think the API check also applies for `brew` and `homebrew-core`

# The motivation for the feature

Currently, `brew update` is forced to fetch `brew` and `homebrew-core` in every runs. If a check performed in advance, the execution time may be significantly reduced when no updates are available.

# How the feature would be relevant to at least 90% of Homebrew users

Every Hombrew users use `brew update`, this feature can save time

# What alternatives to the feature have been considered

**Comment by jonchang** [comment]
Homebrew already uses the GitHub API to see if updates are needed, before running any `git` commands. Look at the source code of `cmd/update.sh` and search for 'github'.
