### ISSUE TITLE
brew remove/uninstall not deleting hashes

### ISSUE THREAD

**Issue by kyle95wm** [Homebrew/brew#865]
### Bug reports:

So basically when I go to fully uninstall home-brew or any packages, and when I try to invoke any related commands, I get "no such file or directory" instead of "command not found". I have to run:

"type [COMMAND]" and it will tell me that file is hashed

from here I have to type "hash -d [COMMAND]" to delete the hash to bring the shell back to its normal behaviour. Can this be fixed in homebrew somehow? It's annoying whenever I remove a package that I have to run these commands manually each time.

**Comment by MikeMcQuaid** [comment]
This is down to the configuration of your shell rather than Homebrew, sorry.
