### ISSUE TITLE
Since brew 2.5.0, download progress is not shown

### ISSUE THREAD

**Issue by noelforte** [Homebrew/brew#8682]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Download any package

## What happened (include command output)

Download progress that normally shows no longer shows after updating to 2.5.0

<details>
<summary>Command output</summary>
<pre>
$ brew install <package-name>
==> Downloading &lt;url&gt;...
==> Downloading &lt;url&gt;...
==> Downloading &lt;url&gt;...
==> Downloading &lt;url&gt;...
</pre>
</details>

## What you expected to happen

Expected download progress to show so I can confirm packages are actually downloading and when long-running downloads have stalled.

## Step-by-step reproduction instructions (by running `brew` commands)

```
$ brew install <package-name>
```

## Output of `brew config` and `brew doctor` commands

<details>
<summary><code>brew config</code></summary>
<pre>
$ brew config
HOMEBREW_VERSION: 2.5.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ec8266697b2c9838cef86f8f97b5f392d0f926d
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b599f82489f1177cfb69f21f9878eeb3cb562cb5
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.hcnyc6Ew5X/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 10.0 build 1001
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 14.0.2
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
</pre>
</details>

<details>
<summary><code>brew doctor</code></summary>
<pre>
$ brew doctor
Your system is ready to brew.
</pre>
</details>

**Comment by MikeMcQuaid** [comment]
This is a regression from https://github.com/Homebrew/brew/commit/36a8a823a10ece7959f50980c85d523faf30f06d#diff-4a2fc48282e793a34459f309ef4ff28a CC @reitermarkus

**Comment by corehello** [comment]
@MikeMcQuaid hi, any workaround or any further PR to make the progress back?

**Comment by reitermarkus** [comment]
@corehello it was fixes in https://github.com/Homebrew/brew/pull/8686 and will be in the next release.

**Comment by corehello** [comment]
@reitermarkus Glad to know, and thx for the info.
