### ISSUE TITLE
Linkage cache can grow to gargantuan sizes, causing poor post-install linkage checker performance

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/brew#8690]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

When running `brew install`, I've noticed for awhile that Homebrew appears to hang after the install itself completes. I eventually figured out that it does complete, but it can take upwards of 60 seconds to complete even when the actual installation itself completes in under a second. After discussing it with @claui, it looks like I'm not the only person experiencing this. The factor I identified that's the same between both of us is that our linkage cache has grown to absolutely gargantuan proportions. Mine was 10MB of JSON, and hers was 20MB.

At this point I'm quite positive that the linkage cache is the culprit, because deleting my cache and allowing it to be recreated results in a 30KB cache and `brew install` operations now complete instantaneously.

I ran `brew prof --stackprof install blah`, and as expected it looks like most of the time is being spent in `CacheStoreDatabase`-related tasks. In particular it looks like `Formula#undeclared_runtime_dependencies` is slow when the cache gets this large, and it ended up being called 73 times here. This gets called several frames down from `check_broken_dependents`, via `Formula#runtime_installed_formula_dependents`.

It feels more than a little ironic that caching can end up making things many times slower than not caching at all! If we're never cleaning this cache file, or not correctly cleaning it, it would explain how it managers to get so bloated over time.

Here's the profiling data: https://gist.github.com/mistydemeo/638f2390bc3c4597fd3cc386e2b64900

## What happened (include command output)

The actual install process looks pretty much like normal; the user simply experiences a hang after the `installed` step, without any feedback that anything is happening.

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading http://old-releases.ubuntu.com/ubuntu/pool/universe/v/vcdtools/vcdtools_0.4.orig.tar.gz
Already downloaded: /Users/mistydemeo/Library/Caches/Homebrew/downloads/7c68e206d63c8b5145c7a8e365fea3ba770a3350684f4e6a84503fffa425e110--vcdtools_0.4.orig.tar.gz
==> make clean
==> make
🍺  /usr/local/Cellar/vcdtools/0.4: 6 files, 66.5KB, built in 5 seconds
  </pre>
</details>

## What you expected to happen

Installations complete in a short amount of time.

## Step-by-step reproduction instructions (by running `brew` commands)

Simply `brew install` any software, if your linkage cache is suitably large.

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.5.0-49-gc06848c
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c06848c48795904a39fb5a0114b6ddc7b49ccbf4
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 403b107e3272fcc1cc1ef78f6aeb07c2bb96fdd2
Core tap last commit: 4 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.dp4MCkVr4f/org.macosforge.xquartz:0
HOMEBREW_EDITOR: subl
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 11.0 build 1100
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_172
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  wine
</pre>

**Comment by MikeMcQuaid** [comment]
@mistydemeo Was there things in the linkage cache which weren't present on your system? It sounds like things weren't being removed from the cache correctly. Also, could you and @claui upload your cache somewhere so I can play around with it locally? Thanks!

**Comment by bayandin** [comment]
> It sounds like things weren't being removed from the cache correctly.

Sounds like you're right, here's an example for `youtube-dl`:
```
$ cat ~/Library/Caches/Homebrew/linkage.json | jq 'keys' | grep youtube-dl
  "/usr/local/Cellar/youtube-dl/2019.04.17",
  "/usr/local/Cellar/youtube-dl/2019.04.24",
  "/usr/local/Cellar/youtube-dl/2019.04.30",
  "/usr/local/Cellar/youtube-dl/2019.05.11",
  "/usr/local/Cellar/youtube-dl/2019.05.20",
  "/usr/local/Cellar/youtube-dl/2019.06.08",
  "/usr/local/Cellar/youtube-dl/2019.06.21",
  "/usr/local/Cellar/youtube-dl/2019.06.27",
  "/usr/local/Cellar/youtube-dl/2019.07.02",
  "/usr/local/Cellar/youtube-dl/2019.07.12",
  "/usr/local/Cellar/youtube-dl/2019.07.14",
  "/usr/local/Cellar/youtube-dl/2019.07.16",
  "/usr/local/Cellar/youtube-dl/2019.07.27",
  "/usr/local/Cellar/youtube-dl/2019.08.02",
  "/usr/local/Cellar/youtube-dl/2019.08.13",
  "/usr/local/Cellar/youtube-dl/2019.09.01",
  "/usr/local/Cellar/youtube-dl/2019.09.12.1",
  "/usr/local/Cellar/youtube-dl/2019.09.28",
  "/usr/local/Cellar/youtube-dl/2019.10.16",
  "/usr/local/Cellar/youtube-dl/2019.10.22",
  "/usr/local/Cellar/youtube-dl/2019.10.29",
  "/usr/local/Cellar/youtube-dl/2019.11.05",
  "/usr/local/Cellar/youtube-dl/2019.11.22",
  "/usr/local/Cellar/youtube-dl/2019.11.28",
  "/usr/local/Cellar/youtube-dl/2019.12.25",
  "/usr/local/Cellar/youtube-dl/2020.01.01",
  "/usr/local/Cellar/youtube-dl/2020.01.15",
  "/usr/local/Cellar/youtube-dl/2020.01.24",
  "/usr/local/Cellar/youtube-dl/2020.02.16",
  "/usr/local/Cellar/youtube-dl/2020.03.01",
  "/usr/local/Cellar/youtube-dl/2020.03.06",
  "/usr/local/Cellar/youtube-dl/2020.03.08",
  "/usr/local/Cellar/youtube-dl/2020.03.24",
  "/usr/local/Cellar/youtube-dl/2020.05.03",
  "/usr/local/Cellar/youtube-dl/2020.05.08",
  "/usr/local/Cellar/youtube-dl/2020.05.29",
  "/usr/local/Cellar/youtube-dl/2020.06.06",
  "/usr/local/Cellar/youtube-dl/2020.06.16.1",
  "/usr/local/Cellar/youtube-dl/2020.07.28",
  "/usr/local/Cellar/youtube-dl/2020.09.06",
```

**Comment by MikeMcQuaid** [comment]
Have opened https://github.com/Homebrew/brew/pull/8695 to address/improve this in several ways.
