### ISSUE TITLE
NF: Option to have a "current" symlink to the point to the current or main version of the app or util

### ISSUE THREAD

**Issue by izhakjakov** [Homebrew/brew#8699]
# Feature suggestion

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# A detailed description of the proposed feature

A feature to keep a symlink to the current path up to date.
This feature will be optional and the symlink will only be updated if the env var `HOMEBREW_BREW_CURRENT_PKG_VER=1`
If `HOMEBREW_BREW_CURRENT_PKG_VER=1` homebrew will create a symlink:
```
 $  ll /usr/local/Cellar/go/
drwxr-xr-x  320B  8 Sep 10:15 1.15.1
lrwxr-xr-x    6B  8 Sep 10:48 latest -> 1.15.1
```
# The motivation for the feature

Homebrew keeps the apps inside a version directory e.g. `/usr/local/Cellar/go/1.15.1`. This can cause problems with some applications that expect a path for an app but after updating won't be able to find it because `/usr/local/Cellar/go/1.14.2` is now `/usr/local/Cellar/go/1.15.1`
For example: goland relies on go to be installed in a certain path and needs to keep getting update with the new path

# How the feature would be relevant to at least 90% of Homebrew users

They will not need to manually update the path in applications that rely on utilities to be in certain location

# What alternatives to the feature have been considered

Using only for pkgs that are included in the var `HOMEBREW_BREW_CURRENT_PKG_VER` separated by colon as similar to the var `PATH`. 
For example:
`HOMEBREW_BREW_CURRENT_PKG_VER=go:perl`
But this will add more complexity and the env var would need to be updated everytime a new pkg needs this feature.
Could be implemented this way in the future if needed

**Comment by izhakjakov** [comment]
How can I assign this issue to myself?

**Comment by MikeMcQuaid** [comment]
`/usr/local/opt/go/` is this.

**Comment by izhakjakov** [comment]
> `/usr/local/opt/go/` is this.

haha 😅  thanks 😊
