### ISSUE TITLE
Homebrew broken on dosdude1 patched MacBooks

### ISSUE THREAD

**Issue by shaunsingh** [Homebrew/brew#8718]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?

yes

- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

yes

- [x] ran `brew config` and `brew doctor` and included their output with your issue?

yes

## What you were trying to do (and why)

I was trying to install qmk using home-brew on my 2009 Catalina-patcher MacBook

## What happened (include command output)

The install failed because of an error with python 

Everything goes well and then this pops up, along with a message that python quit unexpectedly 

<details>
  <summary>Command output</summary>
  <pre>

python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/qmk--homebrew-virtualenv-20200913-4557-1ehb8s/target
--install-scripts=/private/tmp/qmk--homebrew-virtualenv-20200913-4557-1ehb8s/target/bin
--single-version-externally-managed
--record=installed.txt

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/qmk/homebrew-qmk/issues

These open issues may also help:
brew install qmk/qmk/qmk fails to find module "setuptools" https://github.com/qmk/homebrew-qmk/issues/2

  </pre>
</details>

## What you expected to happen

have it install qmk

## Step-by-step reproduction instructions (by running `brew` commands)

run
brew install qmk/qmk/qmk (or any other package)

on an old patched Mac 

## Output of `brew config` and `brew doctor` commands

brew config
<pre>

Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab72dd1aba052ea550e8a2ef20a7716ccdf29e1f
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dual-core 64-bit penryn
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2, 1.8.0_261
macOS: 10.15.5-x86_64
CLT: 12.0.0.0.1.1595091463

brew doctor

Your system is ready to brew.
</pre>

There are quite a few threads about this on the home-brew forum
what is most likely happening is that there is a minimum cpu limit in the hardware.rb file. Changing this makes a few home-brew apps work if you build from source, but most of them still fail (including qmk)

I am just trying to make this machine run as long as possible, while I save up for a new laptop, and quite a few tools necessary to my workflow are available only in home-brew.

**Comment by jonchang** [comment]
If you're running on at least Mojave, Homebrew assumes your CPU is at least a Nehalem. You'll need to fork Homebrew if you want to change that assumption; the relevant code is in `extend/os/mac/hardware.rb`.

We don't generally support Homebrew on Hackintoshes or otherwise patched systems; in this specific case it's for performance reasons.

**Comment by shaunsingh** [comment]
Even after changing the specified file, it still fails installing things through brew most of the time
I am running macOS Catalina
In terms of performance, with an ssd and a ram upgrade the computer runs quite well, I don't see how performance is an issue.

**Comment by jonchang** [comment]
Yes, you'll also need to build every package from source.

**Comment by shaunsingh** [comment]
Thank you so much! brew install --build-from-source cask works!
