### ISSUE TITLE
installing Homebrew with tight umask leads to unhappiness

### ISSUE THREAD

**Issue by filbo** [Homebrew/brew#8726]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install brew onto a multi-user Mac, and have it accessible to all users.

## What happened (include command output)

I made the mistake of installing brew while my umask was (its default) 077.  I (perhaps stupidly) did not anticipate that it will install system-wide files applying my personal umask.

Everything in /usr/local came up with bad perms:

```
$ ls -l /usr/local 
total 8
drwxrwx---   2 filbo     admin   64 Sep 15 02:51 Caskroom
drwxrwx---   2 filbo     admin   64 Sep 15 02:51 Cellar
drwxrwx---   2 filbo     admin   64 Sep 15 02:51 Frameworks
drwxrwx---  20 filbo     admin  640 Sep 15 02:52 Homebrew
drwxrwxr-x  27 sysadmin  admin  864 Sep 15 02:52 bin
drwxrwx---   3 filbo     admin   96 Sep 15 02:55 etc
drwxrwx---   2 filbo     admin   64 Sep 15 02:51 include
drwxrwx---   2 filbo     admin   64 Sep 15 02:51 lib
lrwxr-xr-x   1 root      wheel   28 Jul 27  2016 mysql -> mysql-5.7.13-osx10.11-x86_64
drwxr-xr-x  12 root      wheel  384 Jun  4  2019 mysql-5.7.13-osx10.11-x86_64
drwxrwx---   2 filbo     admin   64 Sep 15 02:51 opt
drwxr-xr-x   3 root      wheel   96 Jun  4  2019 remotedesktop
drwxrwx---   2 filbo     admin   64 Sep 15 02:51 sbin
drwxrwx---   6 filbo     admin  192 Sep 15 02:55 share
drwxrwx---   3 filbo     admin   96 Sep 15 02:51 var
$ ls -l /usr/local/bin/brew
lrwx------  1 filbo  admin  28 Sep 15 02:52 /usr/local/bin/brew -> /usr/local/Homebrew/bin/brew
$ ls -lL /usr/local/bin/brew
-rwx------  1 filbo  admin  3401 Sep 15 02:52 /usr/local/bin/brew
$ ls -l /usr/local/Homebrew/bin/brew
-rwx------  1 filbo  admin  3401 Sep 15 02:52 /usr/local/Homebrew/bin/brew
```
'remotedesktop', 'mysql*', and the bin directory already existed.

brew's directories came up with 770 perms, which doesn't even make sense with an 077 umask; one would expect 700 (drwx------).

## What you expected to happen

As I was installing a system-wide tool, I expected it to be _accessible_.  With typical Mac stuff where you drag around '.dmg' files, this isn't an issue.  With Linux, I'm sitting there on my account with 077 umask, I run `apt-get install whatever`, the whatever is installed with its intended perms, not mangled by my umask.

I'm a 30-year Unix veteran and this threw me.  Of course, perhaps only a 30y veteran would have any idea about 077 umasks or whatever, but still.

What I expected, or expect now, or expect to have happen from this report is:

In future, when installing brew, it will _properly handle_ umask pursuant to a system component install.  More specifically, the best outcome is:

When installing, if umask is not open enough, it should _**ASK**_ what the installer's intent is, offering as the default (but not required / forced) option, to make everything world accessible.  Or, **if** the installing user says so, retain his incoming umask and install it so it will not be usable by other users.

Second best would be to just force the issue and make it world accessible, i.e. no stop-and-ask.

Worst is the current situation where it silently makes a useless mess.

A bit of googling finds multiple other reports of this, including back to https://github.com/Homebrew/legacy-homebrew/issues/7430, https://discourse.brew.sh/t/solution-for-homebrew-user-without-admin-privileges-in-urs-local/782, and many others.

=======

Upon realizing my mistake, I then made a series of further mistakes which took some untangling to get out of:

(1) I thought 'oh, I need to open up perms on brew's directory, /usr/local', and ran: `chmod -R a+rX /usr/local`.

This was wrong for several reasons.  One was, I had a moment of insanity and thought that brew was the only user of /usr/local; but as shown above, there were a couple of other existing residents.  I don't _think_ I harmed them with this widening of perms, but it was an extremely clumsy thing for me to have done.  This wouldn't have been a problem if brew installed itself in a safe place like /usr/local/homebrew, reaching out to /usr/local only for 'bin' symlinks (/usr/local/bin/brew -> /usr/local/homebrew/Homebrew/bin/brew, or whatever).

(2) having done this, the target audience -- the other user, my mom -- still couldn't run `brew`.  It would in fact error out with:
`/bin/bash: /usr/local/Library/Homebrew/brew.sh: No such file or directory`

The actual location was /usr/local/Homebrew/Library/Homebrew/brew.sh; it was trying to run it out of a path missing one '/Homebrew' component.

Why?

After a lot of head scratching, I realized that the symlink /usr/local/bin/brew was not _readable_ by her account.  The `chmod` command I ran had no special instructions for symlinks; as a result, it changed the mode only of the **target** of the link.  The _symlink itself_ still had 700 perms.  The script was actually executable, but as part of its execution it went back to read its own symlink -- and failed.  The script's function `symlink_target_directory()` fails to read the link, but does not error out in an intelligible manner ('/usr/local/bin/brew: readlink: cannot read link'); it saves it for half a script later to die in trying to exec the next step.

To avoid or repair this, I needed to do something like `find /usr/local -type l | chmod -h a+rx`.  But at this point I thought better of it, deleted everything, reinstalled with umask 022.

## Step-by-step reproduction instructions (by running `brew` commands)

With brew not installed:
```
$ umask 077
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
... complete installation
$ ls -l /usr/local
```
## Proposed nature of fix

1. Installer should examine and do something about umask.  Yes, an admin **might** want to install it with restricted perms, so I believe the best move is to prompt; but the prompt's _default_ should be to override the incoming restrictive umask.

2. Installer should have an argument to specify where to install brew.  Obviously /usr/local remains the default, but it should be easy **and** supported to install it elsewhere, e.g. /usr/local/homebrew or /usr/homebrew (or whatever the user invents).  I see the cautions against installing it in /opt etc. because it will confuse other parts of the ecosystem about brew vs macports vs etc.  The installer should be aware of that, prompting the user if they've specified one of those bad choices, but still allowing them to override it if they insist.

I also see the 'you can download the tarball and extract it anywhere', but that is not a proper install and certainly won't be supported by you.

Yes I'm entirely serious that you should support installing it elsewhere.  It is not rocket science, it's a tiny bit of discipline; one which brew itself enforces on **all** the packages it is able to install within itself!

Would such a change cause bugs?  Sure.  Make the change, let a few Unix veteran / pioneer types take the arrows in their back, they'll make sure it gets fixed, and eventually it will work Just As Well in /some/random/directory as it does in /usr/local/.

What I (and many others in the past) are asking for is _normal_ behavior for Unix-ish utilities.  And again, as I said, brew in fact enforces the very same thing on packages it installs: they land in a directory /usr/local/Homebrew/... which certainly isn't where they were born.  They handle it because they use a $BASE_DIRECTORY or whatever the call it.  Brew _also seems to handle it_, or it wouldn't be able to deal with /usr/local vs /home/linuxbrew/.linuxbrew/.  So just make it official.

The other thing people ask for is for it to be usable by multiple users while fewer are able to modify it.  This already exists.  Having installed it with 022 perms, well, it looks like it actually installed itself with effectively 002 perms.  The files are writable by _me_ and by group _admin_.  Not by world.  Any non-admin user on the machine has _access_ to all the brew-installed goodies, but can't modify them.  Exactly as an admin would wish.

This project has a whole decade (or more, I didn't keep searching) of complaints about this set of problems.  Please just fix it.

The users who want it to work will step up to fix the rough edges -- once the project accepts to move in the desired direction.

## Output of `brew config` and `brew doctor` commands

[brew-update.txt](https://github.com/Homebrew/brew/files/5223353/brew-update.txt)
[brew-doctor.txt](https://github.com/Homebrew/brew/files/5223354/brew-doctor.txt)
[brew-config.txt](https://github.com/Homebrew/brew/files/5223355/brew-config.txt)

**Comment by MikeMcQuaid** [comment]
> Install brew onto a multi-user Mac, and have it accessible to all users.

We don't support this. There's an open PR to do this better (https://github.com/Homebrew/install/pull/328) that your help would be welcome on.

> * Installer should examine and do something about umask.  Yes, an admin **might** want to install it with restricted perms, so I believe the best move is to prompt; but the prompt's _default_ should be to override the incoming restrictive umask.

We welcome PRs for improving this but this isn't a problem we've seen reported often so the onus is on those experiencing it to fix it. 

> 2\. Installer should have an argument to specify where to install brew.
> I also see the 'you can download the tarball and extract it anywhere', but that is not a proper install and certainly won't be supported by you.

We don't support installs installed outside of `/usr/local` at all.

> It is not rocket science, it's a tiny bit of discipline; one which brew itself enforces on **all** the packages it is able to install within itself!

It means most binary packages won't work.

> Brew _also seems to handle it_, or it wouldn't be able to deal with /usr/local vs /home/linuxbrew/.linuxbrew/.

That's a difference per-OS. On Linux: we don't support outside `/home/linuxbrew/.linuxbrew/` because, you guessed it: binary packages won't work.

> This project has a whole decade (or more, I didn't keep searching) of complaints about this set of problems. Please just fix it.

I don't appreciate the tone here. We're an open source project run entirely by volunteers, you're a 30 year Unix veteran: why don't you "just fix it"? That question is somewhat rhetorical: we haven't "fixed" it because there's no easy solutions to the problems you mention and they don't affect the majority of our users so maintainers haven't prioritised them.
