### ISSUE TITLE
Import license data from other sources such as GitHub and Debian

### ISSUE THREAD

**Issue by sjackman** [Homebrew/brew#8729]
# Feature suggestion

GitHub has a license API (https://docs.github.com/en/rest/reference/licenses), and the Debian Copyright file is machine readable. I suggest a Homebrew dev command that looks up the Debian package name in Repology, fetches the Debian copyright file, translates it to a Homebrew `license_info` DSL call, prints to the console, or optionally modifies the formula and opens a pull request.

# A detailed description of the proposed feature

TBD

# The motivation for the feature

Homebrew is in the process of adding `license_info` blocks to all formulae.

# How the feature would be relevant to at least 90% of Homebrew users

This feature is primarily intended for developers.

# What alternatives to the feature have been considered

Manually interpreting licenses and adding `license_info` to formulae.

**Comment by lionellloh** [comment]
This looks like something I can work on! I have some context about Formula license.

**Comment by lionellloh** [comment]
Hi @sjackman, I dug around the docs, issues and PRs but can't seem to find any information about what a `license_info` block looks like. Could you link me to the relevant PR / issue so that I may get some context?

**Comment by jonchang** [comment]
https://docs.brew.sh/License-Guidelines

**Comment by MikeMcQuaid** [comment]
@jonchang The `license` DSL was mostly written by @lionellloh. I'm pretty sure `license_info` was a typo here from @sjackman and it should have been `license`. Does that make more sense if so @lionellloh?

**Comment by jonchang** [comment]
The more detailed license blocks are new though, which is what the documentation goes into.

**Comment by MikeMcQuaid** [comment]
@jonchang I don't see any reference to `license_info` in that docs or in Homebrew/homebrew-core?

**Comment by jonchang** [comment]
Yes, I was assuming that Shaun had made a typo.

**Comment by lionellloh** [comment]
Yes that answers my question, thanks!

**Comment by Dancolukas568** [comment]
``

**Comment by sjackman** [comment]
Yes, a typo. Sorry for the confusion.

**Comment by iMichka** [comment]
It looks like we have gone for the manual way. The CI checks are remembering people to update licenses and it is being done on a regular basis. I looks like this project has not moved forward, should we close this?

**Comment by sjackman** [comment]
@lionellloh Were you still interested in working on this issue?

@iMichka I'm fine closing this issue. It depends on I think whether we still want this feature. If we don't then yeah close it. If we do, do we want to keep `help wanted` issues open to encourage new contributors?

**Comment by lionellloh** [comment]
@sjackman @iMichka My apologies for not following up, some personal issues came up. 
If this feature is still deemed necessary, I can work on it with the timeline of completion within next 2 - 3 weeks.

**Comment by carlocab** [comment]
I think the feature would be very nice to have so I would be pleased to see you continue working on it, @lionellloh. However, I also do not think it is urgent, so please do not rush it. Thank you!

**Comment by sjackman** [comment]
No worries at all, Lionell. Take your time. Thank you!

**Comment by cnnrmnn** [comment]
@lionellloh Are you still working on this issue?

**Comment by sjackman** [comment]
I'm going to close this issue, but feel free to re-open it if anyone is actively working on it.
