### ISSUE TITLE
Bug with new "@" formula names

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#873]
A custom `openssl@1.1` formula, living in my local tap, is uninstallable.  HB tells me: 
```
$brew install chdiza/dizaone/openssl@1.1
Error: No available formula with the name "chdiza/dizaone/openssl@1.1"
==> Searching for similarly named formulae...
This similarly named formula was found:
chdiza/dizaone/openssl@1.1
To install it, run:
  brew install chdiza/dizaone/openssl@1.1
==> Searching taps...
Error: No formulae found in taps.
```
There *is* a formula `openssl@1.1` in the tap `chdiza/dizaone`, and the output indicates that HB both believes it is there and that it is not there.

**Comment by chdiza** [comment]
Sorry for the noise, I had a subtly corrupted file.

**Comment by MikeMcQuaid** [comment]
😆
