### ISSUE TITLE
brew update for java11 is throwing errors

### ISSUE THREAD

**Issue by nickycutesc** [Homebrew/brew#8747]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [Y] ran `brew update` and can still reproduce the problem?
- [Y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Y] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Updating Homebrew!

## What happened (include command output)

Throwing the following error when running 'brew update':

Nicholass-MacBook-Pro:~ nicholaschen$ brew update

<details>
  <summary>Command output</summary>
  <pre>

  Nicholass-MacBook-Pro:~ nicholaschen$ brew update
Updated Homebrew from 22d908c85 to 871abe8b9.
Updated 1 tap (homebrew/cask-versions).
==> New Casks
parallels15
==> Deleted Casks
java11
Error: 767: unexpected token at '{
  "java11": "homebrew/core",
}
'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:544:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:300:in `block in migrate_tap_migration'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:298:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:298:in `migrate_tap_migration'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:122:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:122:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'

  </pre>
</details>

## What you expected to happen

No error to be thrown

## Step-by-step reproduction instructions (by running `brew` commands)

1. brew update

## Output of `brew config` and `brew doctor` commands

brew config:

HOMEBREW_VERSION: 2.5.1-42-g871abe8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 871abe8b9b5d5639439046840e786fcf3bb82e8e
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4f87b792811bec7d74abc30204f6d065e3a09a9a
Core tap last commit: 31 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.URzIEGkbCy/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2, 1.8.0_261, 1.8.0_162, 1.8.0_20, 1.7.0_25
macOS: 10.15.6-x86_64
CLT: N/A
Xcode: 11.7
XQuartz: 2.7.11 => /opt/X11

brew doctor:

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  python@2
  ruby@1.9
  camlp4
  wine
  gmp@4
  cloog@0.15
  ppl@0.11
  isl@0.12

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  protobuf@3.7

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  python@2

**Comment by reitermarkus** [comment]
Should be fixed already by https://github.com/Homebrew/homebrew-cask-versions/pull/9633.
