### ISSUE TITLE
macOS 11.0 Big Sur Beta 7 brew incompatibility with latest XCode CLT

### ISSUE THREAD

**Issue by tholu** [Homebrew/brew#8764]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to run `brew upgrade`.

## What happened (include command output)

`brew upgrade` fails, complaining about outdated XCode (CLT).

<details>
  <summary>Command output</summary>
  <pre>

  ➜  ~ brew upgrade
Warning: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

==> Upgrading 1 outdated package:
minio/stable/mc RELEASE.2020-09-03T00-08-28Z_1 -> RELEASE.2020-09-18T00-13-21Z_1
==> Upgrading minio/stable/mc RELEASE.2020-09-03T00-08-28Z_1 -> RELEASE.2020-09-18T00-13-21Z_1
==> Downloading https://dl.minio.io/client/mc/release/darwin-amd64/mc.RELEASE.2020-09-18T00-13-21Z
Already downloaded: /Users/thomaslutz/Library/Caches/Homebrew/downloads/27033a33cdd0ac4d9f0a05ca8abdbcc4aa34b02e5952f0e2bd5b69b6dfb053ce--mc.RELEASE.2020-09-18T00-13-21Z
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Error: An exception occurred within a child process:
  SystemExit: exit

  </pre>
</details>

## What you expected to happen

`brew upgrade` does not fail, as the latest XCode and CLT are installed.

## Step-by-step reproduction instructions (by running `brew` commands)

1. Update to latest macOS 11.0 Big Sur Beta 7
2. Update to latest XCode 12
3. Update to latest XCode CLT
4. Run `brew upgrade`

## Output of `brew config` and `brew doctor` commands

<pre>
➜  ~ brew config
HOMEBREW_VERSION: 2.5.1-80-ge9c634b
ORIGIN: https://github.com/Homebrew/brew
HEAD: e9c634beab50211d2b007affafe5324591942882
Last commit: 42 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 33ab1781fd7c8eaa089054c47ea19724647b5300
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.sWDs2tgmGB/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.2, 1.8.261.12, 1.8.0_265
macOS: 11.0-x86_64
CLT: 12.0.0.0.1.1599194153
Xcode: 12.0

➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libndi.4.dylib

Warning: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

Warning: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
</pre>

**Comment by tholu** [comment]
I'm guessing some adjustments in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac/xcode.rb are necessary to fix this.

**Comment by MikeMcQuaid** [comment]
> Warning: You are using macOS 11.0.
> We do not provide support for this pre-release version.
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC. You are responsible for resolving any issues you
> experience while you are running this pre-release version.

**Comment by tholu** [comment]
@MikeMcQuaid I created the issue as documentation and am currently working on a Pull Request, where I would like to reference the issue. You can keep it closed though, as I already expected it to get closed.

**Comment by MikeMcQuaid** [comment]
> You can keep it closed though, as I already expected it to get closed.

In future please don't submit issues when:
- you expect them to be closed
- you are already working on your own pull request to fix them

Thanks!

**Comment by echonox** [comment]
@tholu any updates on this?

**Comment by tholu** [comment]
@echonox Sorry, this was a dumb mistake on my side - I used the wrong XCode version (the final XCode 12 does **NOT** support Big Sur), so the error message from homebrew was on point:

Solution for me was to use XCode 12.2 Beta.

**Comment by echonox** [comment]
@

> @echonox Sorry, this was a dumb mistake on my side - I used the wrong XCode version (the final XCode 12 does **NOT** support Big Sur), so the error message from homebrew was on point.
> 
> Solution for me was to use XCode 12.2 Beta.

wow I thought Xcode 12 supports Big Sur.. tnx

**Comment by echonox** [comment]
@tholu i've installed the beta, but still get the error any steps I should take?

**Comment by pat-s** [comment]
Re-install the latest version of the CLT from Apples developer website.
