### ISSUE TITLE
Warn when auto-changing branch?

### ISSUE THREAD

**Issue by penman** [Homebrew/brew#877]
Homebrew automatically (sometimes unexpectedly) doing some git stuff when updating seems to come up in the issue tracker pretty regularly. In #737, @MikeMcQuaid [mentions]() that this is going to be improved at some point. In the meantime, though, I wonder if it would be worth emitting a warning explaining that Homebrew is checking out `master`, and explaining that setting `HOMEBREW_DEVELOPER` will prevent this behaviour?

Is this a good idea?

**Comment by vladshablinsky** [comment]
👍 Was thinking about it just yesterday. When `HOMEBREW_DEVELOPER` and `HOMEBREW_NO_AUTO_UPDATE` are not set, and you're on the different from master branch with unstaged changes, these changes get `stash`'ed and  `stash pop`'ed, but branch can be switched to master without any note.
