### ISSUE TITLE
Linux make shim causes infinite loop with extra slashes in path

### ISSUE THREAD

**Issue by LordFlashmeow** [Homebrew/brew#8773]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
---

When compiling from source, I noticed that `./configure` would freeze on the majority of formulae. 

When turning on verbose mode, it freezes right after checking for gawk. 

For example when installing hello:
```
==> ./configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/home/dpeter19/.linuxbrew/Cellar/hello/2.10
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
```

This is because the next line is `checking to see if make sets $(MAKE)`, which expands to `checking to see if //home/dpeter19/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/make sets $(MAKE)"`

Enabling debug mode and running the shim with `make -v`, I found these lines:

```
+ pathremove //home/dpeter19/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super

# and then somewhat further down

+ '[' /home/dpeter19/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super '!=' //home/dpeter19/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super ']'
```

The `make` shim causes an infinite loop, because there is an additional slash at the beginning of the path to remove, so it isn't removed before calling "the real make".

In this case, `$HOMEBREW_LIBRARY` doesn't resolve the path to remove the additional slashes, while the script that added the shim did remove them.

Probably the simplest solution would be changing the line 
```
pathremove "$HOMEBREW_LIBRARY/Homebrew/shims/linux/super"
```
to 
```
pathremove "$(dirname $(which make))"
```

Although I'm no bash expert myself, and this might remove the wrong `make` if the script isn't called through `make`.

https://github.com/Homebrew/brew/blob/a8a921dfaa44f71cdc53fac8ad3e42d491c7ea33/Library/Homebrew/shims/linux/super/make#L1-L25

---

HOMEBREW_VERSION: 2.5.1-90-ga8a921d
ORIGIN: https://github.com/Homebrew/brew
HEAD: a8a921dfaa44f71cdc53fac8ad3e42d491c7ea33
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 8482ea00b3a722e185b9eb414f0ee7d3cc3339b1
Core tap last commit: 33 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/dpeter19/.linuxbrew
HOMEBREW_REPOSITORY: //home/dpeter19/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/dpeter19/.linuxbrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 2.6.3 => /home/dpeter19/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 20-core 64-bit sandybridge
Clang: 3.4 build 34
Git: 2.28.0 => //home/dpeter19/.linuxbrew/bin/git
Curl: 7.29.0 => /usr/bin/curl
Kernel: Linux 3.10.0-1127.18.2.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.8.2003 (Core)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
/usr/bin/ruby: N/A
glibc: 2.23
gcc: 5.5.0_7
xorg: N/A

**Comment by MikeMcQuaid** [comment]
We'd accept a pull request to address this but as-is I'm considering this a user configuration issue, sorry.

**Comment by LordFlashmeow** [comment]
I seem to have fixed the issue by setting `$HOME` without the extra slash in my `.zshenv`, everything works fine now.

**Comment by maxim-belkin** [comment]
I was going to say that something isn't right with your setup because of the extra forward slash in `HOMEBREW_REPOSITORY`:

> HOMEBREW_PREFIX: /home/dpeter19/.linuxbrew
HOMEBREW_REPOSITORY: //home/dpeter19/.linuxbrew/Homebrew

Glad you figured this out but I'm not sure why you set `HOME` in the first place... perhaps, the right solution is to remove that line from your `.zshenv` altogether.

**Comment by LordFlashmeow** [comment]
It's something weird with how the server is set up, the double slash happens to other user accounts too.

**Comment by maxim-belkin** [comment]
Yeah, that's weird. You don't see these paths in `/etc/passwd`, do you? I'd report this to admin(s) anyways.
