### ISSUE TITLE
Why is it that every update to the brew itself is not permanent?

### ISSUE THREAD

**Issue by Imputes** [Homebrew/brew#8780]
This happens every time I run brew update in the terminal:
![image](https://user-images.githubusercontent.com/12896162/93694035-bb29ae00-fb39-11ea-8a21-0dfbe9d5b0b7.png)
Isn't brew update a permanent update?
Don't talk to me about brew doctor, I'm sure you absolutely already knew this would happen when you developed it. Otherwise you'd be handing the test over to the user?

**Comment by jonchang** [comment]
Homebrew is a rolling release package manager and will always aim to release the newest versions of software.

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
