### ISSUE TITLE
Your CLT does not support macOS 11.0 (Big Sur Beta 7)

### ISSUE THREAD

**Issue by echonox** [Homebrew/brew#8797]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install rabbitmq, which it failed with an error.. the same error/warning I get when running `brew doctor`

## What happened (include command output)

Rabbitmq failed to install

<details>
  <summary>Command output</summary>
  <pre>

  Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.

  </pre>
</details>

## What you expected to happen

I've expected the formula to get installed successfuly

## Step-by-step reproduction instructions (by running `brew` commands)

- Have homebrew installed on Big Sur Developer Beta 7
- run brew doctor (same error/warning)
- Install rabbitmq (same error/warning and the package fails to install)

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: cd4a3c0588abb82d916bc8558f4c157e951d449d
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c899d98ff122c16facdf0aa0c206d4c3c6a2a662
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0-x86_64
CLT: 12.0.0.0.1.1599194153
Xcode: 12.2 => /Applications/Xcode-beta.app/Contents/Developer
</pre>

<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

Warning: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
</pre>

NOTE:
Based on https://github.com/Homebrew/brew/issues/8764 I've tried the following:

What didn't work:
- switching between CLT 11 and CLT 12 in Xcode 12
- installing Xcode 12.2 Beta and switching between all 3 available CLT's CLT 11, CLT 12, CLT 12.2
- reinstalled the CLT from https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12/Command_Line_Tools_for_Xcode_12.dmg

What did work:
- uninstalling the CLT allowed me to install rabbitmq and got rid of CLT warning in `brew doctor`... but this is clearly not a solution

**Comment by SMillerDev** [comment]
You need to install the CLT for Xcode 12 beta 5. The Xcode 12 release doesn't support macOS 12 and the CLT in Xcode is not the same as the normal Command Line Tools.

---

Closing this because of the output in brew doctor:
> Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

**Comment by mtangoo** [comment]
Hi @SMillerDev,
I am facing some similar but a bit different issue (which might have the same cause). I just read your explanation below and could not understand it:

>You need to install the CLT for Xcode 12 beta 5. **The Xcode 12 release doesn't support macOS 12** and **the CLT in Xcode is not the same as the normal Command Line Tools**.

Can you help me understand the bold-ed statements?

TIA

**Comment by SMillerDev** [comment]
That should have been macOS 11. The Command Line Tools are closely tied to macOS releases. XCode 12.0 only supports macOS 10.15 and below. Even if you install the XCode 12.2 beta though, that will not impact the installed Command Line Tools, so you'll need to install an older beta for the CLT (the beta 5 one for Xcode 12) that did support macOS 11.

**Comment by mtangoo** [comment]
I think my understanding is quiet outdated. I thought XCode 12.0 is the latest release of the IDE that should work just fine with MacOS 11 (Big Sur) so it should be 10.15 and above, no?

I checked also [xcodereleases.com](https://xcodereleases.com/) and seems to support my thoughts, do you have any thoughts on that?

>so you'll need to install an older beta for the CLT (the beta 5 one for Xcode 12) that did support macOS 11
Again am confused with statement that it "did support MacOS 11" I thought MacOS11 is the latest version, and so should be supported even now?

Can you please provide the codename for the macOS 11 you are referring to?
Apple numbers someties gets confusing especially with their changes in numbering with Bigsur 

And thanks for your time!

**Comment by mtangoo** [comment]
Just to add on my original question, my problem is well documented in [Apple SE](https://apple.stackexchange.com/questions/401924/homebrew-i-cannot-install-from-source-command-clang-requires-clt)

**Comment by dive** [comment]
As I can see, [Xcode 12.2 Beta](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_2-beta-release-notes/) ships with macOS 11 SDK:
> Xcode 12.2 beta includes SDKs for iOS 14.2, iPadOS 14.2, tvOS 14.2, watchOS 7.1, and macOS Big Sur 11.

Works fine on macOS Big Sur v11.0 Beta (20A5374i):
```
➜  git:(master) xcode-select -p
./../Xcode_12.2_beta.app/Contents/Developer

➜  git:(master) brew doctor    
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.
```

**Comment by mtangoo** [comment]
>As I can see, Xcode 12.2 Beta ships with macOS 11 SDK:

>    Xcode 12.2 beta includes SDKs for iOS 14.2, iPadOS 14.2, tvOS 14.2, watchOS 7.1, and macOS Big Sur 11.

>Works fine on macOS Big Sur v11.0 Beta (20A5374i):

I had XCode12 Beta 5 and was working fine and when I saw that they have just released 12.0 GM I thought it is the stable version of that Beta, so I thought if Beta was working probably GM will work. Now it seems am wrong.

Can you help me understand this: When Big Sur is released will there be XCode 12.3 for it? Because my thinking was XCode 12 was for Big Sur just like XCode 11 was for Mojave/Catalina?

This switch to Silcon blah blah is really confusing to me. BTW am using a 2015 MBP!

**Comment by mtangoo** [comment]
So I unpacked the XCode 12 Beta 5 that I had kept and did `sudo xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer` and the build passes where it was failing.

Any article that explains how XCode version we working with this new change of numbering and hardware?

**Comment by MikeMcQuaid** [comment]
Sorry folks, we're not here to provide support for Big Sur. You'll have to figure this out yourself until we officially support it.
