### ISSUE TITLE
Central "scratch" repo [Proposal]

### ISSUE THREAD

**Issue by apjanke** [Homebrew/brew#88]
What do folks think about having a "scratch" central tap repo to use as a sandbox for testing issue and bottle-management code?

Developing and testing `brew pull` has been a little difficult because it acts on pending PRs, build jobs, and bottles on external servers. It's hard to test the code that operates on transitional states, like publishing files to Bintray and retrying downloads while they're 401-ing for a few seconds.

Proposal: Create a `homebrew/homebrew-scratch` tap repo that's included in the central repo list, so the test bot and CI are watching it and running test jobs and building bottles, and we can publish the bottles to Bintray. But it's just a sandbox for putting in example and test formulae, so we can work with it and iterate tests involving bot and Bintray server state, without affecting functionality for Homebrew end users. Same GitHub permissions as homebrew/core: only maintainers can push or publish to Bintray.

Would need a bit of restraint when using it, because it would share the same CI build queues as "production" PRs.

**Comment by mikemcquaid** [comment]
I think it's fine just using the main repos. If it becomes a problem, :+1: to this.

**Comment by apjanke** [comment]
Between putting dummy PRs in `homebrew/core` and the current state of `homebrew/science`, I was able to find test cases for everything I needed. Don't think this will be necessary in the near future. Closing out.
