### ISSUE TITLE
`brew style` generates errors on formulae outside of Homebrew directory structure

### ISSUE THREAD

**Issue by jabenninghoff** [Homebrew/brew#8803]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Running `brew style` on a Formula in my home directory, to validate style before checking it in to GitHub.

## What happened (include command output)

When running `brew style` on a file outside of the Homebrew directory structure additional, spurious, errors are generated.

<details>
  <summary>Command output</summary>
  <pre>
$ brew style ./rsync.rb 
rsync.rb:1:1: C: Missing top-level class documentation comment.
class Rsync < Formula
^^^^^
rsync.rb:1:1: C: Missing frozen string literal comment.
class Rsync < Formula
^
rsync.rb:39:3: C: Method has too many lines. [12/10]
  def install ...
  ^^^^^^^^^^^

1 file inspected, 3 offenses detected, 3 offenses auto-correctable
  </pre>
</details>

## What you expected to happen

Until recently, `brew style ./foo.rb` would not report these spurious errors. This change appears to be caused by PR #8542. Running `brew style` against the same formula in the `/usr/local/Homebrew/Library/Taps` directory structure generates no errors.

This change in behavior makes it harder to validate style when developing new Casks/Formulae.

## Step-by-step reproduction instructions (by running `brew` commands)

To reproduce:
```
$ cd ~
$ brew style /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rsync.rb

1 file inspected, no offenses detected
$ cp -i /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rsync.rb .
$ brew style ./rsync.rb 
rsync.rb:1:1: C: Missing top-level class documentation comment.
class Rsync < Formula
^^^^^
rsync.rb:1:1: C: Missing frozen string literal comment.
class Rsync < Formula
^
rsync.rb:39:3: C: Method has too many lines. [12/10]
  def install ...
  ^^^^^^^^^^^

1 file inspected, 3 offenses detected, 3 offenses auto-correctable
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.2-39-g48c0503
ORIGIN: https://github.com/Homebrew/brew
HEAD: 48c050371ded49d55ba8a90a7a75ca2785a693bb
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c0012fe8bc4985858abe502007d21d817eac7078
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 36500
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.jm9wzgh8XW/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15
macOS: 10.15.6-x86_64
CLT: 12.0.32.2
Xcode: 12.0
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment]
There's a WIP PR for this in https://github.com/Homebrew/brew/pull/8542 CC @claui

**Comment by claui** [comment]
@jabenninghoff Now that #8589 has landed, this should be fixed.
Feel free to comment here if any such errors still come up.
