### ISSUE TITLE
brew synlink with conda

### ISSUE THREAD

**Issue by m416kar98k** [Homebrew/brew#8807]
I notice conda package manager could be installed with brew cask. I suggest we could build a conda synlink with brew to help some package dependencies. It is more flexible to do version control with conda. I want to do some contributions in the update to make it possible.

**Comment by claui** [comment]
> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
