### ISSUE TITLE
cowsay formulae distributes zoophilic content

### ISSUE THREAD

**Issue by tdicola** [Homebrew/brew#8810]
The version of [cowsay distributed by Homebrew](https://formulae.brew.sh/formula/cowsay) includes offensive and zoophilic ASCII images that are installed by default and without warning on a user's computer. These images likely violate the [Homebrew code of conduct](https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md#code-of-conduct), and potentially violate international laws against distributing zoophilic content.

## repro steps

(content warning, ASCII images of zoophilia are shown by running these commands)
```
> brew install cowsay
> cowsay -l
Cow files in /usr/local/Cellar/cowsay/3.04/share/cows:
beavis.zen blowfish bong bud-frogs bunny cheese cower daemon default dragon
dragon-and-cow elephant elephant-in-snake eyes flaming-sheep ghostbusters
head-in hellokitty kiss kitty koala kosh luke-koala meow milk moofasa moose
mutilated ren satanic sheep skeleton small sodomized stegosaurus stimpy
supermilker surgery telebears three-eyes turkey turtle tux udder vader
vader-koala www
> echo "This is not what Homebrew should distribute!" | cowsay -f sodomized
<... zoophilic ASCII art omitted from bug report ...>
> echo "This is not what Homebrew should distribute!" | cowsay -f telebears
<... zoophilic ASCII art omitted from bug report ...>
```

## expected behavior

Installing cowsay with Homebrew should not load zoophilic content on a user's computer.

It appears the formulae for cowsay installs 'cowsay-off', an offensive version of cowsay which includes these images.  You can read a discussion of [Debian linux's response to this content](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882085) to see that they chose to turn cowsay into multiple packages such that the default does not include the problematic images.  I propose Homebrew follow this model and update its formulae to not use the 'cowsay-off' source.

I would also suggest Homebrew treat this issue with the severity and speed of resolution as a critical security issue.  Homebrew's distribution of these images could very well be in violation of several countries laws against indecency.  Users who have installed this formulae might unknowingly be in violation of local laws against indecency, and I would hope the Homebrew maintainers would do the due diligence to inform them of the issue and how to delete the images completely.

**Comment by issyl0** [comment]
Thanks for bringing this to our attention, @tdicola. The latest `cowsay` package as distributed by Homebrew (merged just now, https://github.com/Homebrew/homebrew-core/commit/6767a6aa5d2b62979a0c5d39bd7ddf9b93da3b62) does not contain this offensive imagery.
