### ISSUE TITLE
fortune formulae violates Homebrew code of conduct

### ISSUE THREAD

**Issue by tdicola** [Homebrew/brew#8811]
The version of fortune [installed by Homebrew](https://formulae.brew.sh/formula/fortune) is based on a distribution of the tool 'fortune-mod' which includes explicitly racist, homophobic, ethnically insensitive and other offensive content that directly conflicts with the [Homebrew's code of conduct](https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md#code-of-conduct).  Please adjust this formulae so that content which violates the code of conduct is not installed by default on a user's machine.

## repro steps

(content warning, running these commands will potentially output offensive content)

```
> brew install fortune
> fortune -o racism
<... racist quote omitted from bug report ...>
> fortune -o hphobia
<... homophobic quote omitted from bug report ...>
> fortune -o ethnic
<... ethnically insensitive quote omitted from bug report ...>
```

You can investigate all of the offensive databases installed by Homebrew's fortune formulae in its /share/games/fortunes/off directory:

```
> ls /usr/local/Cellar/fortune/9708/share/games/fortunes/off
astrology          drugs              limerick           misogyny           racism             sex
astrology.dat      drugs.dat          limerick.dat       misogyny.dat       racism.dat         sex.dat
black-humor        ethnic             misandry           politics           religion           songs-poems
black-humor.dat    ethnic.dat         misandry.dat       politics.dat       religion.dat       songs-poems.dat
definitions        hphobia            miscellaneous      privates           riddles            vulgarity
definitions.dat    hphobia.dat        miscellaneous.dat  privates.dat       riddles.dat        vulgarity.dat
```

Quotes from these databases are sourced randomly when the '-o' (offensive) option is passed to the tool, and/or the database is specified by name as an argument to the tool.

## expected behavior

Installing Homebrew's fortune formulae should not add to a user's machine databases of content which violate the Homebrew project's code of conduct.

The fortune tool has a long history and discussion of handling offensive content chronicled in its [readme file](https://www.ibiblio.org/pub/linux/games/amusements/fortune/fortune-mod-9708.README). It appears the past maintainers attempted to isolate offensive content into explicit databases hidden behind opt in command line parameters, however this content is still distributed and loaded on Homebrew user's machines likely without their knowledge or consent. I would recommend that Homebrew patch the formulae to move these offensive databases outside of the officially distributed package entirely. If users would like to use fortune with content that violates this project's code of conduct they can publish and maintain a tap on their own servers, under their own code of conduct.

**Comment by issyl0** [comment]
Thanks for bringing this to our attention, @tdicola. The latest `fortune` package as distributed by Homebrew (merged just now, 3fb3c4c) does not contain these offensive quotes.
