### ISSUE TITLE
pkg-config --cflags libffi returns include dir for previous macOS sdk

### ISSUE THREAD

**Issue by msbit** [Homebrew/brew#8812]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Get OS version appropriate `CFLAGS` for `libffi` under macOS 10.15.6

## What happened (include command output)

When calling `pkg-config --cflags libffi`, output for the previous version of macOS is returned.

<details>
  <summary>Command output</summary>
  <pre>
-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/ffi
  </pre>
</details>

## What you expected to happen

`-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/ffi`

## Step-by-step reproduction instructions (by running `brew` commands)

Full debug output of `pkg-config`:

<pre>
$ pkg-config --debug --cflags libffi
Error printing enabled by default due to use of output options besides --exists, --atleast/exact/max-version or --list-all. Value of --silence-errors: 0
Error printing enabled
Adding virtual 'pkg-config' package to list of known packages
Looking for package 'libffi'
Looking for package 'libffi-uninstalled'
Reading 'libffi' from file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14/libffi.pc'
Parsing package file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14/libffi.pc'
  line>homebrew_sdkroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
 Variable declaration, 'homebrew_sdkroot' has value '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk'
  line>prefix=${homebrew_sdkroot}/usr
 Variable declaration, 'prefix' has value '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr'
  line>exec_prefix=/usr
 Variable declaration, 'exec_prefix' has value '/usr'
  line>libdir=${exec_prefix}/lib
 Variable declaration, 'libdir' has value '/usr/lib'
  line>toolexeclibdir=${libdir}
 Variable declaration, 'toolexeclibdir' has value '/usr/lib'
  line>includedir=${prefix}/include/ffi
 Variable declaration, 'includedir' has value '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/ffi'
  line>
  line>Name: libffi
  line>Description: Library supporting Foreign Function Interfaces
  line>Version: 2.1
  line>Libs: -L${toolexeclibdir} -lffi
  line>Cflags: -I${includedir}
Path position of 'libffi' is 4
Adding 'libffi' to list of known packages
Package libffi has -L /usr/lib in Libs
Removing -L /usr/lib from libs for libffi
 post-recurse: libffi
adding CFLAGS_OTHER string ""
 post-recurse: libffi
 original: libffi
   sorted: libffi
adding CFLAGS_I string "-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/ffi "
returning flags string "-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/ffi"
-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/ffi
</pre>

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: cd4a3c0588abb82d916bc8558f4c157e951d449d
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b16b9af25c3fa784bce5844c5bc50e58e0f8fa80
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.3, 1.8.0_212
macOS: 10.15.6-x86_64
CLT: 1103.0.32.62
Xcode: 12.0
</pre>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  python@2

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  protobuf@3.7

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libusb-1.0.0.dylib
  /usr/local/lib/libusb-1.0.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2
  libusb

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.profile
</pre>

**Comment by msbit** [comment]
I was puzzling why `pkg-config` was jumping directly to `/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14`, and then I saw that the formula for `pkg-config` bakes the value in with the `--with-pc-path` argument.

So, I've been able to rectify this with a `brew reinstall pkg-config`.

Is there some scope to have this determined at runtime (in the `pkg-config` formula etc) or is the official Homebrew stance that packages need to be reinstalled between macOS versions to avoid these kinds of issues?

**Comment by jonchang** [comment]
Yeah, to be safe you'll probably want to reinstall Homebrew in between macOS version updates. You can use `brew bundle` to easily reinstall all your software.

**Comment by MikeMcQuaid** [comment]
You shouldn't need to reinstall all of Homebrew but you will need to reinstall `brew reinstall pkg-config`, yeh. CC @Bo98 FYI as you're working on this.

**Comment by Bo98** [comment]
Yes, automatically reinstalling of pkg-config on OS upgrades (after a brew upgrade or whatever) is a priority for me before Big Sur releases.

Some work to detect old installations is in already place. I should probably create an issue tracking progress towards the rest.
