### ISSUE TITLE
Command to list all directly installed items

### ISSUE THREAD

**Issue by thewilli** [Homebrew/brew#8817]
# Feature suggestion

Add command to list all directly installed items (i.e. excluding dependencies).

# A detailed description of the proposed feature

Add a command which outputs why a certain formula was installed, i.e. whether it's a dependency or was *directly* installed as per user request. The yarn package manager has a [why command](https://classic.yarnpkg.com/en/docs/cli/why/) I consider quite useful and might be useful to Homebrew as well.

# The motivation for the feature

My `brew list` output is too long to get an overview of what was *actually* installed by me, and what were just dependencies of my installations. I tend to regularly cleanup my installations and find it too hard and time-consuming to go through each item and study its description. I'd to know what I actually `brew install`ed.

# How the feature would be relevant to at least 90% of Homebrew users

Many users might have tried some packages, and most of us just don't have the time or motivation to cleanup right away. In addition to a cleanup scenario setting up a new machine (maybe with a different OS and no brew at all) might be another reason one wants to know about the tools being part of the daily routine.

# What alternatives to the feature have been considered

#8683 with the `--dry-run` option helps to cleanup, even though it's not completely what I wanted.

**Comment by issyl0** [comment]
> In addition to a cleanup scenario setting up a new machine (maybe with a different OS and no brew at all) might be another reason one wants to know about the tools being part of the daily routine.

The [Brewfile provided by Homebrew/homebrew-bundle](https://github.com/Homebrew/homebrew-bundle) might be a good fit for this. That also has `brew bundle --cleanup` which can uninstall everything that's not specified in a `Brewfile`.

**Comment by MikeMcQuaid** [comment]
> Add command to list all directly installed items (i.e. excluding dependencies).

`brew leaves`.
