### ISSUE TITLE
 double items in the lists `New Casks` and `Updated Casks`

### ISSUE THREAD

**Issue by WuglyakBolgoink** [Homebrew/brew#8819]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

```shell
$ brew update
$ brew upgrade
```

## What happened (include command output)

`brew update` show always double items in the lists `New Casks` and `Updated Casks`

For example:
![image](https://user-images.githubusercontent.com/2271337/94460669-6204ee80-01b9-11eb-841a-4d25162dd53c.png)

## What you expected to happen

show items once on every list

## Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew update
$ brew upgrade
```

## Output of `brew config` and `brew doctor` commands

`brew config` output:
<pre>
HOMEBREW_VERSION: 2.5.2-46-g91d58cd-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91d58cdc991a55ba24bfc3b07917e90b920bee0d
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 81624f11c7c511861fdec07ee58b988b60195dd0
Core tap last commit: 28 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: subl -w
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.3, 11.0.2, 1.8.0_265
macOS: 10.15.6-x86_64
CLT: N/A
Xcode: 11.6
</pre>

`brew tap` output:
<pre>
adoptopenjdk/openjdk
bazelbuild/tap
facebook/fb
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
mongodb/brew
phinze/cask
</pre>

`brew doctor` wrote that `phinze/cask` was deprecated, then I did `untap`:

<pre>
brew untap phinze/cask
Untapping phinze/cask...
</pre>

current `brew doctor` output:
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories do not exist:
/usr/local/Frameworks
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/Frameworks /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/Frameworks /usr/local/sbin

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.3.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  fbsimctl
  unbound
  nmap
  python@3.8
</pre>

**Comment by bayandin** [comment]
> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Fill the template, please and feel free to ping me to reopen the issue.
Also, an output of `brew tap` command could be useful as well.

**Comment by WuglyakBolgoink** [comment]
@bayandin ping... :-)

PS: Now I do not have any information in both commands and need wait some days until any package again publish a new release...

**Comment by reitermarkus** [comment]
This was most definitely caused by having `phinze/cask` installed which redirects to `homebrew/cask`, so you basically have the same tap installed twice.

**Comment by WuglyakBolgoink** [comment]
Hallo @reitermarkus , ok, i will check this in next days, and then I close this ticket
