### ISSUE TITLE
request: ungoogled-chromium

### ISSUE THREAD

**Issue by chovy** [Homebrew/brew#882]
https://github.com/Eloston/ungoogled-chromium

build instructions:

https://github.com/Eloston/ungoogled-chromium/blob/master/BUILDING.md

**Comment by zmwangx** [comment]
Unfortunately we don't accept GUI apps. Please submit this to [Homebrew-Cask](https://github.com/caskroom/homebrew-cask), or [submit a Cask request there](https://github.com/caskroom/homebrew-cask#requests) and people will help you.

**Comment by vitorgalvao** [comment]
[Already there](https://github.com/caskroom/homebrew-cask/blob/master/Casks/chromium.rb).
