### ISSUE TITLE
detected_python_shebang expects python to be installed only from default tap

### ISSUE THREAD

**Issue by beefon** [Homebrew/brew#8824]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ч] ran `brew update` and can still reproduce the problem?
- [ч] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ч] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I have in-house tap. We cached `iproute2mac`. It depends on `python@3.8`, which we also have cached in our tap.
So now formulа depends on `our/inhousetap/python@3.8`.

Whenever I try to `brew install our/inhousetap/iproute2mac`, I get an error.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
Error: An exception occurred within a child process:
   RuntimeError: Cannot detect Python shebang: formula does not depend on Python.
  </pre>
</details>

## What you expected to happen

Apparently there's a hardcoded regular expression, and brew expects python to be referred only via direct `python@3.8`. 
`our/inhousetap/python@3.8` does not match `^python(@.*)?$` regexp, and brew throws the error.

## Step-by-step reproduction instructions (by running `brew` commands)

1. Create and host your own git repo with formulas. Patсh them to make them use your tap instead of default brew one.

E.g. instead of
```
depends_on 'python@3.8'
```
make it look like
```
depends_on 'your/tap/python@3.8'
```

2. Add patched formula of `iproute2mac` to your tap
3. `brew install your/tap/iproute2mac`

## Output of `brew config` and `brew doctor` commands

<details>
  <summary>Outputs</summary>
<pre>
% brew config
HOMEBREW_VERSION: 2.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: cd4a3c0588abb82d916bc8558f4c157e951d449d
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3071401aa84905c95059696bce10053d5b52e713
Core tap last commit: 11 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode_11_7.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_265
macOS: 10.15.6-x86_64
CLT: 12.0.0.0.1.1599194153
Xcode: 11.7 => /Applications/Xcode_11_7.app/Contents/Developer

% brew doctor
Your system is ready to brew.
</pre>
</details>

**Comment by MikeMcQuaid** [comment]
Sorry, we do not support this workflow. We'll review a PR to improve it to meet your use-case.
