### ISSUE TITLE
`brew install external/tap/formula` when external/tap is not tapped fails with "No available formula or cask"

### ISSUE THREAD

**Issue by SimonBarendse** [Homebrew/brew#8830]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install the [secrethub-cli](https://github.com/secrethub/homebrew-tools/blob/294696f8284b93c0a4af4d56d4ff6f02c3a1ab46/Formula/secrethub-cli.rb) in the Docker container `linuxbrew/brew:latest`.

## What happened (include command output)

The formulae was not found (`Error: No available formula or cask with the name "secrethub/tools/secrethub-cli".`)

<details>
  <summary>Command output</summary>
  <pre>
brew install secrethub/tools/secrethub-cli      
==> Tapping secrethub/tools
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/secrethub/homebrew-tools'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 182 (delta 12), reused 0 (delta 0), pack-reused 127
Receiving objects: 100% (182/182), 30.87 KiB | 1.19 MiB/s, done.
Resolving deltas: 100% (39/39), done.
Tapped 1 formula (27 files, 136.6KB).
Error: No available formula or cask with the name "secrethub/tools/secrethub-cli".
==> Searching for similarly named formulae...
This similarly named formula was found:
secrethub-cli
To install it, run:
  brew install secrethub-cli
  </pre>
</details>

## What you expected to happen

Successful installation of the CLI, just like when using the `linuxbrew/brew:2.5.2` image.

## Step-by-step reproduction instructions (by running `brew` commands)

```
docker run linuxbrew/brew brew install secrethub/tools/secrethub-cli
```

## Output of `brew config` and `brew doctor` commands

<pre>
# brew doctor
Your system is ready to brew.
</pre>

<pre>
# brew config
HOMEBREW_VERSION: 2.5.2-69-g2331927
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2331927a3498e1107aef13f76f1ed2b8309be4b0
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: ebc6339d1832683cb3d9e14ae0f7e2b049102299
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.28.0 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-48-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.1 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: N/A
xorg: N/A
</pre>

**Comment by SimonBarendse** [comment]
`brew doctor` resolves the problem. Are we supposed to run `brew doctor` every time we start using the docker image?

**Comment by SimonBarendse** [comment]
<details>
  <summary>This isn't limited to the SecretHub tap. I'm seeing a similar error for `heroku/brew/heroku`</summary>
  <pre>
docker run linuxbrew/brew brew install heroku/brew/heroku
==> Homebrew has enabled anonymous aggregate formula and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics have been recorded yet (or will be during this `brew` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Tapping heroku/brew
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/heroku/homebrew-brew'...
Tapped 2 formulae (30 files, 368KB).
Error: No available formula or cask with the name "heroku/brew/heroku".
==> Searching for similarly named formulae...
This similarly named formula was found:
heroku
To install it, run:
  brew install heroku
  </pre>
</details>

**Comment by MikeMcQuaid** [comment]
> `brew doctor` resolves the problem. Should we run `brew doctor` every time we start using the docker image?

Can you elaborate how it seems to fix the problem?

**Comment by SimonBarendse** [comment]
@MikeMcQuaid I cannot seem to reproduce. I must have overlooked something when I reported it did solve the problem, sorry.

So the problem still persists after running `brew doctor`.

**Comment by jonchang** [comment]
Docker is a red herring. Merely running:

```bash
brew untap secrethub/tools
HOMEBREW_NO_ANALYTICS=1 brew install --only-dependencies secrethub/tools/secrethub-cli
```

is enough to observe the error. Bisect says:

```
f54b458cdaec5091cf7abfa3e09e9050a94a4a26 is the first bad commit
commit f54b458cdaec5091cf7abfa3e09e9050a94a4a26
Author: Markus Reiter <me@reitermark.us>
Date:   Fri Sep 25 21:13:26 2020 +0200

    Allow installing casks with `brew install`.

 Library/Homebrew/cask/cmd/abstract_command.rb |   1 +
 Library/Homebrew/cask/cmd/install.rb          |  29 +++-
 Library/Homebrew/cask/cmd/reinstall.rb        |   6 +-
 Library/Homebrew/cli/named_args.rb            |  63 ++++---
 Library/Homebrew/cmd/install.rb               | 227 +++++++++++++++++---------
 Library/Homebrew/exceptions.rb                |  16 +-
 docs/Manpage.md                               |  20 ++-
 manpages/brew.1                               |  40 ++++-
 8 files changed, 285 insertions(+), 117 deletions(-)
```
