### ISSUE TITLE
Would love to join and contribute

### ISSUE THREAD

**Issue by rutujak24** [Homebrew/brew#8833]
Hi there,

I am an undergraduate at PICT, Pune. A quality and output-driven computer enthusiast. Passionate about exploring computer science and technology-related topics. My domains & fields of interest are machine learning, data science, Computer Vision, Python, Java, C++, R, MATLAB, open-source. I aspire to work and contribute to these fields for betterment society through research and innovations for improvisation in the field of computer science and technology.

I have a keen interest in the research, especially in the domains of machine learning, AI, and data science. I have been a research fellow at The Emerging Tech Foundation. I have been a python mentor at Skillship foundation, a mentor at facebook's developer's circle. I have a keen interest in writing technical blogs and articles, worked at Geeksforgeeks.org as a technical content writer. Also currently I am an editor at PICT IEEE NewsletterGroup, which is a technical biannual magazine of my college. Also, I write technical blogs on medium.

I am even passionate about web-development. I have developed the official website of CTD 2020 (a technical event of PISB), also completed a couple of internships in this domain with Wikasta Technical Solutions and another with Kode IT Solutions. I am Technical Lead Developer at GirlScript Foundation Pune, here I manage all the tech issues and development of its official website.

I am a semifinalist of the national python codathon conducted by cisco and ISTE. I have been accepted as a Udacity scholar for the Microsoft Azure Machine Learning scholarship program. I am also an enthusiastic open source contributor, I am a Github's Arctic Code Vault Contributor.

Keen about exploring opportunities in the field of research and development in computer science-related technologies, also open for collaborations! 

Please add me to this organization, My Github ID is rutujak24.

Thank you!

**Comment by claui** [comment]
Sorry, we’re not accepting membership applications. Feel free to contribute by submitting meaningful pull requests. Thank you.
