### ISSUE TITLE
keep getting detach HEAD or git lfs errors when trying to tap wix/brew

### ISSUE THREAD

**Issue by Norfeldt** [Homebrew/brew#8861]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm trying to tap `wix/brew` but I keep facing either a detached **HEAD** or some `git fls` issue

## What happened (include command output)

<details>
  <summary>`Brew tap wix/brew` complains about a detached HEAD</summary>
  <pre>
$ brew tap wix/brew
Updating Homebrew...
Previous HEAD position was 10a01b68b8 Update unity from 2020.1.6f1,fc477ca6df10 to 2020.1.7f1,064ffcdb64ad (#90370)
HEAD is now at 00158d1d8e Update superproductivity from 5.9.2 to 5.9.10 (#90378)

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

error: could not detach HEAD
Previous HEAD position was 970ce274d92 icu4c: upstream patch for Xcode 9 (#59540)
HEAD is now at 0411a1ad9a2 php@7.3: update 7.3.23 bottle.

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

error: could not detach HEAD
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 2 formulae.
==> Updated Casks
mumble                            praat                             superproductivity

==> Tapping wix/brew
Cloning into '/usr/local/Homebrew/Library/Taps/wix/homebrew-brew'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 580 (delta 17), reused 27 (delta 9), pack-reused 544
Receiving objects: 100% (580/580), 1.57 MiB | 578.00 KiB/s, done.
Resolving deltas: 100% (304/304), done.

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

Error: Failure while executing; `git clone https://github.com/wix/homebrew-brew /usr/local/Homebrew/Library/Taps/wix/homebrew-brew` exited with 2.
  </pre>
</details>

<details>
  <summary>brew doctor says homebrew-core is not on the master branch</summary>
  <pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew/homebrew-core is not on the master branch.

Check out the master branch by running:
  git -C "$(brew --repo homebrew/core)" checkout master
  </pre>
</details>

<details>
  <summary>git checkout homebrew/core:master and do a pull</summary>
  <pre>
$ git -C "$(brew --repo homebrew/core)" checkout master
Previous HEAD position was 0411a1ad9a2 php@7.3: update 7.3.23 bottle.
Switched to branch 'master'
Your branch is behind 'origin/master' by 11 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

$ git -C "$(brew --repo homebrew/core)" pull
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Updating 64db5396afd..0411a1ad9a2
Fast-forward
 Formula/circleci.rb | 10 +++++-----
 Formula/icu4c.rb    |  7 +++++++
 Formula/krakend.rb  | 10 +++++-----
 Formula/libxpm.rb   | 10 +++++-----
 Formula/php@7.3.rb  | 19 +++++++++++++------
 Formula/pygitup.rb  | 39 +++++++++++++++++++--------------------
 6 files changed, 54 insertions(+), 41 deletions(-)
  </pre>
</details>

<details>
  <summary>Try to tap wix/brew again - but git-lfs error</summary>
  <pre>
$ brew tap wix/brew
Updating Homebrew...
Previous HEAD position was 00158d1d8e Update superproductivity from 5.9.2 to 5.9.10 (#90378)
HEAD is now at 4039e809dd Update session from 1.3.1 to 1.4.0 (#90379)

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

error: could not detach HEAD
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
session

==> Tapping wix/brew
Cloning into '/usr/local/Homebrew/Library/Taps/wix/homebrew-brew'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 580 (delta 17), reused 27 (delta 9), pack-reused 544
Receiving objects: 100% (580/580), 1.57 MiB | 2.95 MiB/s, done.
Resolving deltas: 100% (304/304), done.

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

Error: Failure while executing; `git clone https://github.com/wix/homebrew-brew /usr/local/Homebrew/Library/Taps/wix/homebrew-brew` exited with 2.
  </pre>
</details>

<details>
  <summary>brew doctor says everything is fine</summary>
  <pre>
$ brew doctor
Your system is ready to brew.
  </pre>
</details>

I also did the change to git master this way

<details>
  <summary>changed $(brew --repo) to master and did a pull</summary>
  <pre>
$ cd "$(brew --repo)"
$ gst
On branch stable
nothing to commit, working tree clean
$ git reset --hard HEAD

HEAD is now at 23e24c671 Merge pull request #8850 from dtrodrigues/post-version
$ master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ git stash drop
Dropped refs/stash@{0} (e75e89718c69f797718b023d01aee19efa404320)
$ ls
CHANGELOG.md    Dockerfile      Library         SECURITY.md     completions     manpages
CONTRIBUTING.md LICENSE.txt     README.md       bin             docs
$ git pull
From https://github.com/Homebrew/brew
 - [deleted]             (none)     -> origin/pr/1
 - [deleted]             (none)     -> origin/pr/10
 - [deleted]             (none)     -> origin/pr/1001
 - [deleted]             (none)     -> origin/pr/1002
 - [deleted]             (none)     -> origin/pr/1003
 - [deleted]             (none)     -> origin/pr/1004
 - [deleted]             (none)     -> origin/pr/1007
 - [deleted]             (none)     -> origin/pr/1008
 - [deleted]             (none)     -> origin/pr/1009
 - [deleted]             (none)     -> origin/pr/101
 - [deleted]             (none)     -> origin/pr/1010
...
  </pre>
</details>

## What you expected to happen

being able to add `wix/brew` as a tap and install requirements for `detox` ios stuff

## Step-by-step reproduction instructions (by running `brew` commands)

I did a lot of things... some of them can be seen [here](https://github.com/wix/homebrew-brew/issues/4) and [here](https://stackoverflow.com/questions/64210163/homebrew-update-keep-complaining-about-git-fls-but-which-repos-are-the-trouble?noredirect=1#comment113545300_64210163).

![Screen Shot 2020-10-05 at 20 38 30](https://user-images.githubusercontent.com/678806/95118579-dbb55300-074a-11eb-8b71-cb2e4faa4274.png)

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 23e24c6710fc02b844cf31a2c4f3e5d5d0ce2155
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0411a1ad9a251a7397d4afa1f9839dfedee7ad1e
Core tap last commit: 80 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.8, 1.8.0_144, 1.8.0_131
macOS: 10.15.7-x86_64
CLT: 12.0.0.0.1.1599194153
Xcode: 12.0.1

</pre>

**Comment by Norfeldt** [comment]
Trying to reinstall it also seems like it's detaching the head

```
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
Password:
Sorry, try again.
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at 23e24c671 Merge pull request #8850 from dtrodrigues/post-version

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.


This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (or will be during this `install` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://docs.brew.sh
```

**Comment by Norfeldt** [comment]
It seems like it's an issue about homebrew not making the dirs

```
$ brew --version
Homebrew 2.5.3
Homebrew/homebrew-core (git revision 0411a; last commit 2020-10-05)
$ brew tap wix/brew
Updating Homebrew...
==> Tapping wix/brew
Cloning into '/usr/local/Homebrew/Library/Taps/wix/homebrew-brew'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 580 (delta 17), reused 27 (delta 9), pack-reused 544
Receiving objects: 100% (580/580), 1.57 MiB | 3.87 MiB/s, done.
Resolving deltas: 100% (304/304), done.

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

Error: Failure while executing; `git clone https://github.com/wix/homebrew-brew /usr/local/Homebrew/Library/Taps/wix/homebrew-brew` exited with 2.
$ /usr/local/Homebrew/Library/Taps/wix/
zsh: no such file or directory: /usr/local/Homebrew/Library/Taps/wix/
$ mkdir /usr/local/Homebrew/Library/Taps/wix/
$ mkdir /usr/local/Homebrew/Library/Taps/wix/homebrew-brew
$ brew tap wix/brew
```

🤷‍♂️ how do I fix this issue?

**Comment by jonchang** [comment]
> This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

You need to address this error message.

**Comment by Norfeldt** [comment]
I have tried to fix this issue for a long time, but it's like pushing a spring down - it pops up every time you release the pressure.

```
$ brew reinstall git-lfs
==> Downloading https://homebrew.bintray.com/bottles/git-lfs-2.12.0.catalina.bottle.tar.gz
Already downloaded: /Users/norfeldt/Library/Caches/Homebrew/downloads/0a56965c16ba6c5c8c0e423ba5b19da484e23cce4d2388312914bfafd971e493--git-lfs-2.12.0.catalina.bottle.tar.gz
==> Reinstalling git-lfs 
==> Pouring git-lfs-2.12.0.catalina.bottle.tar.gz
==> Caveats
Update your git config to finish installation:

  # Update global git config
  $ git lfs install

  # Update system git config
  $ git lfs install --system
==> Summary
🍺  /usr/local/Cellar/git-lfs/2.12.0: 65 files, 11.7MB
$ git lfs install && git lfs install --system
Updated git hooks.
Git LFS initialized.
WARNING: current user is not root/admin, system install is likely to fail.
Updated git hooks.
Git LFS initialized.
$ brew reinstall python@3.8
==> Downloading https://homebrew.bintray.com/bottles/python%403.8-3.8.5.catalina.bottle.tar.gz
Already downloaded: /Users/norfeldt/Library/Caches/Homebrew/downloads/9dd7cd94f1e3f75a7f2fe63c7333d9de7e8241f212eeaa1e774c45fff2da63f8--python@3.8-3.8.5.catalina.bottle.tar.gz
==> Reinstalling python@3.8 
==> Pouring python@3.8-3.8.5.catalina.bottle.tar.gz
==> /usr/local/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --v
==> /usr/local/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --v
==> /usr/local/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --v
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.8/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@3.8/3.8.5: 4,331 files, 67MB
```

**Comment by Norfeldt** [comment]
@jonchang please reconsider reopening this issue


```
$ brew update

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.


This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

Note: switching to 'b3d4a75485eda69c64831f657104b5e76ae6e9c8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at b3d4a75485 sqlmap 1.4.10

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

error: could not detach HEAD
Updated 1 tap (homebrew/core).
==> New Formulae
commitizen
==> Updated Formulae
anime-downloader    direnv              lynis               pla                 sqlmap
argo                doctl               manticoresearch     pueue               ssdb
babl                firebase-cli        mcabber             rabbitmq            suil
bartycrouch         folly               meilisearch         rust-analyzer       whois
bowtie2             fonttools           mesos               scour               xmrig
carrot2             libopenmpt          node-sass           sfcgal
conan               lmod                oha                 sord
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew/homebrew-core is not on the master branch.

Check out the master branch by running:
  git -C "$(brew --repo homebrew/core)" checkout master
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew/homebrew-core is not on the master branch.

Check out the master branch by running:
  git -C "$(brew --repo homebrew/core)" checkout master
```

```
$ git -C "$(brew --repo homebrew/core)" checkout master
Previous HEAD position was b3d4a75485 sqlmap 1.4.10
Switched to branch 'master'
```

```
$ brew doctor
Your system is ready to brew.
```

```
$ brew update

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.


This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

Note: switching to 'b3d4a75485eda69c64831f657104b5e76ae6e9c8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at b3d4a75485 sqlmap 1.4.10

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

error: could not detach HEAD
Updated 1 tap (homebrew/core).
==> New Formulae
commitizen
==> Updated Formulae
anime-downloader    direnv              lynis               pla                 sqlmap
argo                doctl               manticoresearch     pueue               ssdb
babl                firebase-cli        mcabber             rabbitmq            suil
bartycrouch         folly               meilisearch         rust-analyzer       whois
bowtie2             fonttools           mesos               scour               xmrig
carrot2             libopenmpt          node-sass           sfcgal
conan               lmod                oha                 sord
```

```
$ git -C "$(brew --repo homebrew/core)" checkout master
Previous HEAD position was b3d4a75485 sqlmap 1.4.10
Switched to branch 'master'
```

```
$ brew update-reset
==> Fetching /usr/local/Homebrew...

==> Resetting /usr/local/Homebrew...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Switched to and reset branch 'master'
Your branch is up to date with 'origin/master'.

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.


==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

```

```
$ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
$ git-lfs install --local
Updated git hooks.
Git LFS initialized.
$ brew update-reset
==> Fetching /usr/local/Homebrew...

==> Resetting /usr/local/Homebrew...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.


==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.


$ cd /usr/local/Homebrew
$ git-lfs install --local
Updated git hooks.
Git LFS initialized.
$ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
$ git-lfs install --local
Updated git hooks.
Git LFS initialized.
```

```
$ brew update
Already up-to-date.
$ brew doctor
Your system is ready to brew.
```

```
$ cd ~
$ brew tap wix/brew
==> Tapping wix/brew
Cloning into '/usr/local/Homebrew/Library/Taps/wix/homebrew-brew'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 580 (delta 17), reused 27 (delta 9), pack-reused 544
Receiving objects: 100% (580/580), 1.57 MiB | 3.88 MiB/s, done.
Resolving deltas: 100% (304/304), done.

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

Error: Failure while executing; `git clone https://github.com/wix/homebrew-brew /usr/local/Homebrew/Library/Taps/wix/homebrew-brew` exited with 2.
```

It keeps detaching the **HEAD** or mess with `git-lfs`

**Comment by MikeMcQuaid** [comment]
> It seems like the `git clone https://github.com/wix/homebrew-brew /usr/local/Homebrew/Library/Taps/wix/homebrew-brew` are not able to create the needed folders.

This is not a Homebrew issue.
