### ISSUE TITLE
`--force-bottle` is misleadingly named

### ISSUE THREAD

**Issue by query** [Homebrew/brew#8866]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Unconditionally install a formula from its bottle, never attempting to build from source.

## What happened

`--force-bottle` appears to behave more like "prefer bottle": It will attempt to use the bottle in some cases where it wouldn't ordinarily be used — it's not documented what these are — but will still fall back to installing from source if the bottle fails for any reason. This isn't what's usually meant by "force", which implies "do it this way or fail". In fact, there are at least a handful of cases where `--force-bottle` will have no effect, sometimes silently:

* Downloads from Bintray are failing for whatever reason. This does show a warning message before falling back.

* The formula does not yet have a bottle. No warnings or errors are reported to the user.

* Homebrew is installed outside `/usr/local` and the bottle is not relocatable. No warnings or errors are reported to the user.

This confusion has been reported before as #6227.

## What you expected to happen

Either `--force-bottle` fails instead of falling back on source installation as it does now, or the option's name is changed to something like `--prefer-bottle` to more accurately reflect its behavior.

Additionally, a diagnostic message when falling back to source explaining why the bottle could not be used would be nice, even when the option isn't passed.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew install --force-bottle $FORMULA`

## Output of `brew config` and `brew doctor` commands

Not relevant.

**Comment by MikeMcQuaid** [comment]
> but no warnings or errors are reported to the user:
> * Downloads from Bintray are failing for whatever reason.

This does report a warning. If it doesn't for you: can you paste the output of faking this with e.g. disabling your internet connection and removing the bottle from your cache? 

> there are many cases

Are there any beyond these three? It'd be helpful to have the output to look at for each of these, too.

**Comment by query** [comment]
> > but no warnings or errors are reported to the user:
> > 
> > * Downloads from Bintray are failing for whatever reason.
> 
> This does report a warning. If it doesn't for you: can you paste the output of faking this with e.g. disabling your internet connection and removing the bottle from your cache?

Whoops, editing error there. You're right that there's a warning. Fixed.

> > there are many cases
> 
> Are there any beyond these three? It'd be helpful to have the output to look at for each of these, too.

Here's sample output for the "no bottle" case, which I simulated by commenting out the `bottle` stanza on the formula:

<details>
<summary>Command output</summary>

```
$ brew install --force-bottle scrcpy
==> Downloading https://github.com/Genymobile/scrcpy/releases/download/v1.16/sc
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaw
######################################################################## 100.0%
==> Downloading https://github.com/Genymobile/scrcpy/archive/v1.16.tar.gz
==> Downloading from https://codeload.github.com/Genymobile/scrcpy/tar.gz/v1.16
######################################################################## 100.0%
==> Installing scrcpy
==> Downloading https://github.com/Genymobile/scrcpy/releases/download/v1.16/sc
==> meson --prefix=/usr/local/Cellar/scrcpy/1.16 --libdir=/usr/local/Cellar/scr
==> ninja install
==> Caveats
At runtime, adb must be accessible from your PATH.

You can install adb from Homebrew Cask:
  brew cask install android-platform-tools
==> Summary
🍺  /usr/local/Cellar/scrcpy/1.16: 7 files, 162.4KB, built in 16 seconds
```
</details>

The "outside `/usr/local`" case is essentially the same, except for the `--prefix` indicated in the build commands.

I can't think of any other cases off the top of my head, but my knowledge here is limited.
