### ISSUE TITLE
brew seems to be broken

### ISSUE THREAD

**Issue by Nathanael8** [Homebrew/brew#8868]
# Bug report

- [yes] ran `brew update` and can still reproduce the problem?
- [yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [yes] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was upgrading and updating with `brew upgrade` and `brew upgrading` which already produced some errors, but seemed to do its job. Afterwards, I tried to figure out what is wrong and typed `brew doctor` which advised me to remove old symlinks and to add something to my path, which I did. I also tried to remove the recently added line to the path, but it didn't help.

## What happened (include command output)

<details>
  <summary>

  <pre>
Traceback (most recent call last):
	7: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
	6: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
	5: from /usr/local/Homebrew/Library/Homebrew/global.rb:16:in `<top (required)>'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/core_ext/object/blank.rb:3:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- concurrent/map (LoadError)
</summary>
  </pre>
</details>

## What you expected to happen

no error

## Step-by-step reproduction instructions (by running `brew` commands)

any command with `brew`. For example `brew doctor`

## Output of `brew config` and `brew doctor` commands

the same
<pre>
Traceback (most recent call last):
	7: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
	6: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
	5: from /usr/local/Homebrew/Library/Homebrew/global.rb:16:in `<top (required)>'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/core_ext/object/blank.rb:3:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- concurrent/map (LoadError)
</pre>

**Comment by MikeMcQuaid** [comment]
Run `brew update-reset`.
