### ISSUE TITLE
File Checksums Calculated by Various Homebrew-Installed Binaries Are Sporadically Wrong

### ISSUE THREAD

**Issue by joshdick** [Homebrew/brew#8874]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Use two different packages that compute file checksums to transfer/verify a large amount of data (~400 GB of files):
* `rsync: stable 3.2.3 (bottled)` installed via Homebrew
* Python 3 `chkbit` package installed via Homebrew-provided Python 3 (`python@3.8: stable 3.8.5 (bottled)`)

**The issue is that Homebrew-specific versions of these tools sporadically calculate incorrect/inconsistent checksums of files on disk, but equivalent tools natively provided by macOS do not have this issue/behave consistently and correctly, on the same machine.**

Because this issue (incorrectly?) led me to believe that my hardware was failing, I can confirm that I am able to reproduce it after a complete wipe and reinstallation from scratch of macOS.

I know how crazy and obtuse this issue must seem, but seeing both of the Homebrew-provided parts of these tools show what appears to be the same issue gave me pause after I figured out that the problems are seemingly only isolated to Homebrew and are not reproducible on the same machine using OS-native tools.

I have tried to be very detailed and complete without including irrelevant command output.

**I realize that both of the cases I detail below are not 1:1 comparisons**. In one case, I compare behavior across two different versions of Python, and in another, I compare behavior across two different versions of rsync. **The fact that the Homebrew-installed versions of both tools are showing very similar incorrect behavior, while their system-native analogs show no issues, has led me to question if there's a low-level dependency issue with the bottled formulas that's causing the behavior I'm seeing.** The fact that both of the Homebrew-provided parts of these tools are showing what appears to be the same issue could very well be a freak coincidence.

#### Background Info

I'm running each `rsync` binary with the following arguments in both cases described below:

`rsync --dry-run --checksum --itemize-changes -r -l -t --delete --progress --rsh=ssh -e "ssh -p 22" dir1 dir2 dir3 user@anotherhost:/path/to/Backup/`

#### What Happens

* rsync 3.2.3 installed via Homebrew (`/usr/local/bin/rsync`) detects seemingly random checksum changes in the specified files on repeated back-to-back runs, even when the file contents have not changed.

* System-native rsync 2.6.9 (`/usr/bin/rsync`) never detects checksum changes on repeated back-to-back runs.

#### What I Expect To Happen

Both Homebrew-installed rsync and system-native rsync have similar output/never detect checksum changes on repeated-back-to-back runs.

---

#### Background Info

`chkbit` (https://github.com/laktak/chkbit-py) is a bitrot detection program written in Python that checksums every file in specified directories and writes `.chkbit` index files that record those checksums.

On repeated runs, if file modification times haven't changed but their checksums have, `chkbit` outputs lines beginning with `ROT!` that correspond to each offending file.

This is the command I use to reproduce the issue: `/usr/local/bin/chkbit --update dir1/ dir2/ dir3/ [...]`

Although this is a Python program, given that I'm having the exact same issue with rsync as described above, I don't expect this to be an issue with Python itself or with Python-specific regressions between the Homebrew-provided Python (v3.8.5) vs the system-provided Python (v3.8.2.)

#### What Happens

`chkbit` installed via Homebrew-provided Python v3.8.5 (`/usr/local/bin/pip3 install chkbit`) shows a completely random set of `ROT!`ed files on repeated back-to-back runs without actually changing any of the files.

`chkbit` installed using the system Python v3.8.2 (`/usr/bin/pip3 install --user chkbit`) and running `/Users/josh/Library/Python/3.8/bin/chkbit` correctly reports no `ROT!` lines at all when doing repeated back-to-back runs without actually changing any of the files.

#### What I Expect To Happen

`chkbit` has the same output (no `ROT!` lines) when running against the system Python vs Homebrew-provided Python.

## Output of `brew config` and `brew doctor` commands

<pre>
josh@hermes:~/Backup 
❯ brew doctor
Your system is ready to brew.

josh@hermes:~/Backup 
❯ brew config
HOMEBREW_VERSION: 2.5.3-16-g569ce08
ORIGIN: https://github.com/Homebrew/brew
HEAD: 569ce08d9fd914907e2090c46a143e86d7e07bec
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e0c09f52b3a32536141fb531f4264d4c8140a14a
Core tap last commit: 25 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.32.2
Xcode: N/A
</pre>

**Comment by MikeMcQuaid** [comment]
Sorry, there's not enough reproducibility here for anyone to begin on a fix. If you figure it out we'll of course accept a PR.

**Comment by joshdick** [comment]
@MikeMcQuaid Closing this feels a bit premature given the effort I went through just to diagnose and document two different ways to reproduce the issue, but I understand your position given just how many moving pieces there are.

**Comment by MikeMcQuaid** [comment]
I'm sorry and we do appreciate your effort but we need open issues for us to be "actionable" and "likely for someone to work on other than the issue reporter" and I'm afraid my experience maintaining this project makes me think in this case this issue does not meet both criteria 😭
