### ISSUE TITLE
"brew edit" open non-existent formula file

### ISSUE THREAD

**Issue by hyuraku** [Homebrew/brew#8876]
# Bug report

**Please note we will close your issue without comment if you delete, do not read, or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

I expect `brew edit [non-existent formula]` would return an error like `brew cask edit`.

## What happened (include command output)
I executed `brew edit abcprogram`, and `Formula/abcprogram.rb` was created and opened.

<details>
  <summary>Command output</summary>
 after commaned , `Formula/abcprogram.rb` was created and opened.
  <pre>
$ brew edit abcprogram
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/abcprogram.rb
  </pre>
</details>

## What you expected to happen

```bash
$ brew edit abcprogram
Error: Formula 'abcprogram' is unavailable: No Formula with this name exists. Run brew create URL to create a new Formula.
```

## Step-by-step reproduction instructions (by running `brew` commands)

```bash
$brew search abcprogram
No formula or cask found for "abcprogram".

$brew edit abcprogram
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/abcprogram.rb

$brew cask edit abcprogram
Error: Cask 'abcprogram' is unavailable: No Cask with this name exists. Run brew cask create abcprogram to create a new Cask.
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Xcode (11.7) is outdated.
Please update to Xcode 12.0.1 (or delete it).
Xcode can be updated from the App Store.
</pre>

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.3-23-gccb271b
ORIGIN: https://github.com/Homebrew/brew
HEAD: ccb271bee4a4225f99afd546c85f754620f55eb5
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: ddd4f0b1a030b98e065874e137e3d2fd604b3f41
Core tap last commit: 57 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/code
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11, 1.8.0_192
macOS: 10.15.7-x86_64
CLT: 12.0.32.2
Xcode: 11.7
</pre>

**Comment by MikeMcQuaid** [comment]
@hyuraku Could you open a PR to address this? Thanks!

**Comment by hyuraku** [comment]
@MikeMcQuaid 
> Could you open a PR to address this?

Sure, I will open it.
