### ISSUE TITLE
YouTube dl wont install on BigSur

### ISSUE THREAD

**Issue by Aluhut** [Homebrew/brew#8886]
This is what Terminal spits out:
```
==> Downloading https://github.com/ytdl-org/youtube-dl/releases/download/2020.09.20/youtube-dl-2020.09.20.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/1039520/52dccb80-fb3d-11ea-938d-f7f
######################################################################## 100.0%
Error: An exception occurred within a child process:
  TypeError: no implicit conversion of Array into Integer
```

**Comment by noplanman** [comment]
I'm faced with the exact same issue and couldn't find any fix.

@MikeMcQuaid Is there a place you can point us to?

**Comment by vitorgalvao** [comment]
> Is there a place you can point us to?

You’ll need to report this to [the correct repo ](https://github.com/Homebrew/homebrew-core) *and* fill the template (which in some cases may fix the issue).
