### ISSUE TITLE
brew switch does not work, says version is not in Cellar

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/brew#8895]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
There are a few extra libs and things but none that seem relevant
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to temporarily switch to python@3.9 to test something 
(I intended to switch, make a test, then switch back to python 3.8)

## What happened (include command output)

brew switch command failed to find python@3.9 even though it is installed

<details>
  <summary>Command output</summary>
  <pre>
ralph@ralph ~ $ brew switch python python@3.9
Error: python does not have a version "python@3.9" in the Cellar.
python's installed versions: 
  </pre>
Yet python@3.9 is in the cellar:
  <pre>
ralph@ralph ~ $ ls /usr/local/Cellar/python*
/usr/local/Cellar/python:

/usr/local/Cellar/python3:

/usr/local/Cellar/python@3.8:
3.8.5

/usr/local/Cellar/python@3.9:
3.9.0
  </pre>

Note: I also tried 
brew switch python @3.9
in case I had the wrong idea about the syntax but that failed too.
</details>

## What you expected to happen

Switch to python@3.9

## Step-by-step reproduction instructions (by running `brew` commands)

```
brew install python@3.9
brew switch python python@3.9
```

## Output of `brew config` and `brew doctor` commands

<pre>
ralph@ralph ~ $ brew config     
HOMEBREW_VERSION: 2.5.5-4-gcfd4870
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: cfd4870247557526bba7f5a6bc0230b1cef92325
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8bcd0e3722ba050928900e5ee7182d5d8b1bd7a1
Core tap last commit: 27 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 0
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.kdfpCeSH3D/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/emacs
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.72.0 => /usr/local/opt/curl/bin/curl
Java: 15, 14.0.2, 1.8.0_261
macOS: 10.15.7-x86_64
CLT: 12.0.32.2
Xcode: 12.0.1
XQuartz: 2.7.11 => /opt/X11
ralph@ralph ~ $ brew doctor     
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libaspell.15.dylib
  /usr/local/lib/libchkp.dylib
  /usr/local/lib/libghdlvpi.dylib
  /usr/local/lib/libifcore.dylib
  /usr/local/lib/libifcoremt.dylib
  /usr/local/lib/libifport.dylib
  /usr/local/lib/libifportmt.dylib
  /usr/local/lib/libimf.dylib
  /usr/local/lib/libintlc.dylib
  /usr/local/lib/libiompstubs5.dylib
  /usr/local/lib/libirc.dylib
  /usr/local/lib/libirng.dylib
  /usr/local/lib/libjlinkpic32.6.34.6.dylib
  /usr/local/lib/libjpeg.8.dylib
  /usr/local/lib/libmkl_avx.dylib
  /usr/local/lib/libmkl_avx2.dylib
  /usr/local/lib/libmkl_avx512.dylib
  /usr/local/lib/libmkl_blacs_mpich_ilp64.dylib
  /usr/local/lib/libmkl_blacs_mpich_lp64.dylib
  /usr/local/lib/libmkl_cdft_core.dylib
  /usr/local/lib/libmkl_core.dylib
  /usr/local/lib/libmkl_intel_ilp64.dylib
  /usr/local/lib/libmkl_intel_lp64.dylib
  /usr/local/lib/libmkl_intel_thread.dylib
  /usr/local/lib/libmkl_mc.dylib
  /usr/local/lib/libmkl_mc3.dylib
  /usr/local/lib/libmkl_rt.dylib
  /usr/local/lib/libmkl_scalapack_ilp64.dylib
  /usr/local/lib/libmkl_scalapack_lp64.dylib
  /usr/local/lib/libmkl_sequential.dylib
  /usr/local/lib/libmkl_tbb_thread.dylib
  /usr/local/lib/libmkl_vml_avx.dylib
  /usr/local/lib/libmkl_vml_avx2.dylib
  /usr/local/lib/libmkl_vml_avx512.dylib
  /usr/local/lib/libmkl_vml_mc.dylib
  /usr/local/lib/libmkl_vml_mc2.dylib
  /usr/local/lib/libmkl_vml_mc3.dylib
  /usr/local/lib/libnettle.6.3.dylib
  /usr/local/lib/libpspell.15.dylib
  /usr/local/lib/libsvml.dylib
  /usr/local/lib/libusb-1.0.0.dylib
  /usr/local/lib/libusb-1.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/aspell.h
  /usr/local/include/vpi_user.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libpspell.la

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  cmake
ralph@ralph ~ $ 
</pre>

**Comment by miccal** [comment]
`brew switch` will not work since `python@3.9` is `keg-only`. 

As explained in the `caveats` from `brew info python@3.9`:
```
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python

python@3.9 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have python@3.9 first in your PATH run:
  echo 'export PATH="/usr/local/opt/python@3.9/bin:$PATH"' >> /Users/miccal/.bash_profile

For compilers to find python@3.9 you may need to set:
  export LDFLAGS="-L/usr/local/opt/python@3.9/lib"

For pkg-config to find python@3.9 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/python@3.9/lib/pkgconfig"
```
&nbsp;
So set your PATH (and also your LDFLAGS and PKG_CONFIG_PATH if necessary) as explained above to have `python@3.9` available for your testing purposes, then undo these changes to revert back to `python@3.8`.

**Comment by ralphrmartin** [comment]
At the very least, the documentation needs improving:
brew switch does not mention "keg only" at all. 
The caveats for python@3.9 do not mention "brew switch" at all.
It is not at all obvious that brew switch won't work, and take care of setting PATH etc as part of what it does.

Indeed, surely if the reason it will not work is because 
"python@3.9 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.",
the above observation will be true for any "alternate version" of anything, which means that "brew swtich" can never do anything useful?

So, it would be helpful for the documentation of brew switch to clarify what it is actually for, and when it is useful.

**Comment by jonchang** [comment]
Thanks for the feedback. We'd welcome any pull requests to improve our documentation: https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md

**Comment by ralphrmartin** [comment]
You have a chicken and egg there. If the documentation doesn't explain what brew switch is supposed to do, how can anyone figure it out, to help write the documentation? I suppose someone could reverse engineer it, but it is hardly normal practice for one team to write software, who then throw it over the wall to a documentation team who have to figure out what it is for and how it works...

**Comment by iMichka** [comment]
`brew switch` is not used that much, and not really maintained IMHO. It was much more used a few years ago, but it had it's issues and weaknesses. Since then we have massively worked with keg_only formulae (using formula@version), allowing to install multiple versions at the same time. I would rather see `brew switch` be removed on the long term. This is also why the documentation is not that up-to-date anymore regarding that command.

**Comment by ralphrmartin** [comment]
Thank you for the explanation. It would be great if the documentation could
(a) say it is deprecated
(b) explain in general terms how to switch between keg_only versions in general.

**Comment by RandomDSdevel** [comment]
@iMichka:  

> `brew switch` is not used that much, and not really maintained IMHO. It was much more used a few years ago, but it had it's issues and weaknesses. Since then we have massively worked with keg_only formulae (using formula@version), allowing to install multiple versions at the same time. I would rather see brew switch be removed on the long term. …

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;One use case for the command which might well still be somewhat relevant is when:  

 1. A new version of a formula's associated package is available through Homebrew, but you've seen that some people have problems with it.  
 1. You:  
    1. Just to be safe, set '`HOMEBREW_NO_INSTALL_CLEANUP=1`,' either globally, for your current shell session, or just for the next step.  
    1. '`brew upgrade`' that package to this new version, apparently successfully.  
 1. Upon trying to use the upgraded package, you get an unresolvable run-time error that is due not to user configuration but to a bug in the package's new version.  
 1. Since you had '`HOMEBREW_NO_INSTALL_CLEANUP`' set, you still have the old, working version laying around and can '`brew switch`' back to it.  

Granted, this _rarely_ happens; I haven't had the need to do this in _ages._  
---
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(If this actually turns out to be a notable, valid concern, discussion can continue on either Discourse or GitHub Discussions to avoid polluting this issue thread any further, whether I have anything more to add myself or not.)

**Comment by iMichka** [comment]
Yes, I think this discussion could be moved somewhere else, to not pollute the issue.

You just remembered me that another thing that "killed" brew switch is HOMEBREW_NO_INSTALL_CLEANUP. The automatic cleanup of packages renders it almost unusable for most of our users, as you need to know about the HOMEBREW_NO_INSTALL_CLEANUP flag upfront.

As you said, you have not used that in ages, and me neither.

In theory if you are running a production system and you are afraid of breakages, you need to test updates on a second system before upgrading. And this is the only way stuff should be done.

**Comment by MikeMcQuaid** [comment]
> If the documentation doesn't explain what brew switch is supposed to do, how can anyone figure it out, to help write the documentation? I suppose someone could reverse engineer it, but it is hardly normal practice for one team to write software, who then throw it over the wall to a documentation team who have to figure out what it is for and how it works...

@ralphrmartin I don't appreciate your tone here (or in other comments and issues). We're all volunteers here and you're perfectly capable of opening pull requests rather than asking others to do so on your behalf. If you're not sure what the documentation should be you can either do research or just make your best guess and let others guide your PR in the right direction.

@RandomDSdevel Please do not post your opinions about how best to use Homebrew on our issue tracker. Last time I checked, you'd left participating in project on fairly bad terms after creating a fork (which I was preemptively blocked on). Please limit any contributions to pull requests in future rather than comments on closed issues, thanks.

**Comment by ralphrmartin** [comment]
Mike, I am not a volunteer on the project, nor do I wish to be. I was simply trying to be helpful in pointing out things that do not work as per the documentation. It's entirely up to you and the team whether you want to fix them or not. It's your project. Clearly, constructive criticism is not appreciated, so I will refrain from making any in future.

**Comment by MikeMcQuaid** [comment]
> Mike, I am not a volunteer on the project, nor do I wish to be. I was simply trying to be helpful in pointing out things that do not work as per the documentation. It's entirely up to you and the team whether you want to fix them or not. It's your project. 

This isn't how open source works, I'm afraid. If you're going to point out problems: it's pretty normal (and reasonable) for others to suggest you help fix them.

> Clearly, constructive criticism is not appreciated, so I will refrain from making any in future.

Constructive criticism is appreciated. Statements like ".. hardly normal practice for one team to write software, who then throw it over the wall to a documentation team ..." are not; they are a wee bit patronising and rude.

**Comment by ralphrmartin** [comment]
For your first point - surely that is why github has "issues", as well as pull requests - to allow people who are not competent or confident to fix problems, to at least report them to those who are? It is certainly not my experience of any other open-source projects for the usual response to "there is a bug in x" to be "fix it yourself". I'm certainly willing to help track bugs down by running tests etc., producing minimal cases that trigger bugs, and so on, within my competence, but see my next point.

As for the second, I'm sorry if it came across like that, but it's hardly reasonable to expect end-users to fix documentation when 
(a) they have no idea how commands are supposed to work, or why, not having been involved in the original planning, design or implementation of the system as a whole, or those commands in particular, and why changes have been made to cause the commands to no longer be in step with the documentation - hence the remark about reverse engineering. 
(b) they are not privy to any plans the team may be making for future changes to the system that might affect those commands
The logical person to write the documentation, and to make sure the command and documentation are in agreement, is the person who wrote the command, and understands how it behaves, and why it behaves like that. This not someone from outside the project team can just jump in and do.

**Comment by MikeMcQuaid** [comment]
> It is certainly not my experience of any other open-source projects for the usual response to "there is a bug in x" to be "fix it yourself".

This is not the usual response in Homebrew either. In this case, it was the response, however.

> I'm sorry if it came across like that

Thanks for the apology, much appreciated ❤️ 

> they have no idea how commands are supposed to work, or why, not having been involved in the original planning, design or implementation of the system as a whole, or those commands in particular, and why changes have been made to cause the commands to no longer be in step with the documentation - hence the remark about reverse engineering
> The logical person to write the documentation, and to make sure the command and documentation are in agreement, is the person who wrote the command, and understands how it behaves, and why it behaves like that.

With this command: literally no Homebrew maintainers still on the project were involved in the creation of this command. By this logic: no-one can write the documentation for the command.

Given someone is going to have to do some reading/reverse engineering here: this is why it's suggested it could be you.

> it's hardly reasonable to expect end-users to fix documentation when

I think it's completely reasonable. https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/ explains a bit why it's equally (if not more) unreasonable to expect the maintainers to fix it for you.

**Comment by ralphrmartin** [comment]
Mike, given that no one currently on the team was involved in creating the brew command, I now understand the problem better. Thanks for the explanation.

I understand that volunteers owe non-contributing end users nothing, and I certainly don't expect them to do anything "for me". I submit bugs in the hope that the team might wish to know about them, and fix them for reasons like pride in the quality of their work, and / or the reputation of the project as a whole. In the best circumstances this becomes a win-win-win-win. The software / documentation gets fixed, which helps me, helps other users, gives the person fixing it a sense of satisfaction, and helps to improve the project's reputation, benefiting all team members.
