### ISSUE TITLE
GitHub API open fails when behind proxy

### ISSUE THREAD

**Issue by ahmadia** [Homebrew/brew#89]
Not sure what's causing this, but behind a pretty standard corporate web proxy that otherwise works properly (and worked with older versions of homebrew), we're now seeing:

```
Error: 407 "Proxy Authentication Required"
Please report this bug:
    https://git.io/brew-troubleshooting
```

Full traceback indicates the issue is in this function: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils.rb#L599-L623

Setting the `HOMEBREW_NO_GITHUB_API` environment variable seems to be a temporary workaround.

**Comment by ahmadia** [comment]
@mikemcquaid - I think the issue may be in https://github.com/Homebrew/brew/commit/6135da800e4f93ded3a5a331d0efa691f4822afb but I'm a little lost in trying to bisect to the error.  Let me know if we can provide any help in testing or trying to provide a fix.  

The way our proxy works, we set a username and password in the proxy url.  I'm wondering if the code here https://github.com/Homebrew/brew/blob/6135da800e4f93ded3a5a331d0efa691f4822afb/Library/Homebrew/cmd/gist-logs.rb#L122-L133 is somehow overriding our proxy environment variables?  We haven't set up GitHub credentials locally, so I'm not sure we should even be trying to login with them and instead should be falling back to unauthenticated requests.

**Comment by mikemcquaid** [comment]
> The way our proxy works, we set a username and password in the proxy url.

It sounds like this may be interfering. Homebrew's proxy support is not great and I'm sorry that this behaviour (which makes things better for non-proxy users) has made things worse for you. It's pretty much impossible for me to create a fix without your proxy to test. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by ahmadia** [comment]
Thanks Mike, I'm pretty sure this is going to be biting a few people so I'll take a look at it this week if I get some time.

**Comment by ahmadia** [comment]
Okay, two ideas.  

1. Don't try to login if there are no GitHub credentials stored on the system, instead just fall back to non-authenticated connection.  This seems the easiest to me and to be the most correct solution.

2. Check for the presence of the HTTPS_PROXY environment variable. If it's been set and is of the form prot://user:password@URL, then don't try to use Ruby basic authentication, since I believe this interferes with the basic authentication to the proxy.

I think [2] might work but that [1] is better for everybody involved.  Let me know if you have any ideas on this, otherwise I'll a little bit deeper into [1].

**Comment by mikemcquaid** [comment]
@ahmadia I'd be surprised if 1) isn't already the case. 2) sounds like a reasonable compromise, though.

**Comment by britztopher** [comment]
+1 as i just tried to upgrade to use brew 0.9.9 and ran into a couple issues because im behind a proxy server.  First, I kept getting this error:

      Error: Non-HTTP proxy URI: https://myun:mypassword@myproxy.com

Then found a workaround by setting `https_proxy=$http_proxy` which leads me to the `Error: 407 "Proxy Authentication Required`  I reverted back to the `homebrew-legacy` github project, which is working fine

**Comment by mikemcquaid** [comment]
@britztopher Could you file a separate bug report? The `homebrew-legacy` github project will not receive any more formula updates.

**Comment by britztopher** [comment]
@mikemcquaid  This bug is not for legacy homebrew
