### ISSUE TITLE
TypeError: no implicit conversion of Array into Integer

### ISSUE THREAD

**Issue by noplanman** [Homebrew/brew#8900]
# Bug report

Check discussion: https://github.com/Homebrew/discussions/discussions/47

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? (Apart from a few unlinked kegs that don't matter, yes)
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade packages that have a new version.

## What happened (include command output)

<details>
  <summary>$ brew upgrade phpunit</summary>
  <pre>
==> Upgrading 1 outdated package:
phpunit 9.4.0 -> 9.4.1
==> Upgrading phpunit 9.4.0 -> 9.4.1
==> Downloading https://phar.phpunit.de/phpunit-9.4.1.phar
Already downloaded: /cache/Homebrew/downloads/9337bd4f50040cc9e2d3720d635ca91336174f7dbe5bcdc982f617def81b5925--phpunit-9.4.1.phar
Error: An exception occurred within a child process:
  TypeError: no implicit conversion of Array into Integer
/usr/local/Homebrew/Library/Homebrew/os/mac/sdk.rb:36:in `first'
/usr/local/Homebrew/Library/Homebrew/os/mac/sdk.rb:36:in `each'
/usr/local/Homebrew/Library/Homebrew/os/mac/sdk.rb:36:in `max'
/usr/local/Homebrew/Library/Homebrew/os/mac/sdk.rb:36:in `latest_sdk'
/usr/local/Homebrew/Library/Homebrew/os/mac/sdk.rb:52:in `rescue in sdk_if_applicable'
/usr/local/Homebrew/Library/Homebrew/os/mac/sdk.rb:45:in `sdk_if_applicable'
/usr/local/Homebrew/Library/Homebrew/os/mac.rb:113:in `sdk'
/usr/local/Homebrew/Library/Homebrew/os/mac.rb:120:in `sdk_for_formula'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:111:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
  </pre>
</details>

## What you expected to happen

For the upgrade to go through normally, as it has in the past.
It works for some packages, and for some it doesn't.

## Step-by-step reproduction instructions (by running `brew` commands)

```
$ brew update
$ brew upgrade phpunit    # or some other package ('yarn' also doesn't work for me)
```

## Output of `brew config` and `brew doctor` commands

<details>
  <summary>$ brew config</summary>
  <pre>
HOMEBREW_VERSION: 2.5.5-33-ge30ed42
ORIGIN: https://github.com/Homebrew/brew
HEAD: e30ed42439f4cca705be54aa14193f6f0a05420d
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bf61d6b7896175cd85156408a39b0ad3e7f3ede6
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /cache/Homebrew
HOMEBREW_CASK_OPTS: ["--require-sha"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.HJFvNV5JGm/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSECURE_REDIRECT: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit sandybridge
Clang: 10.0 build 1000
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 15, 14.0.2, 14.0.1, 14, 13.0.2, 13.0.1, 13, 12.0.2, 10.0.1, 10, 9.0.4, 9.0.1, 9, 1.8.0_202, 1.8.0_172, 1.8.0_144, 1.8.0_141, 1.8.0_131
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
  </pre>
</details>
<details>
  <summary>$ brew doctor</summary>
  <pre>
﻿Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  php
  python@3.8
  </pre>
</details>

**Comment by koenvd** [comment]
Have this as well and I think it got introduced in version 2.5.4 by https://github.com/Homebrew/brew/pull/8859.
After I set brew to version 2.5.3 I could successfully install my package.

Seems the issue is located here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac/sdk.rb#L36 and it looks like the usage of `&:first` throws that error.

If I change that line to: `v, path = sdk_paths.max {|v1, v2| v1.first <=> v2.first}` I'm again able to install my package.

I'm not a Ruby specialist though so not sure if this is the correct fix and why using `&:first` would throw that error in this case.

**Comment by noplanman** [comment]
Thanks @koenvd, that small fix did it for me!

Like you, I'm no Rubyologist, but until this is fixed in brew, your patch gets the updates installed 😉

**Comment by maraflush** [comment]
Thank you very much ! It's work like a charm 👍
