### ISSUE TITLE
brew remove multiple versions that don't show on cleanup

### ISSUE THREAD

**Issue by kirk86** [Homebrew/brew#893]
Hi everyone,

in my system osx 10.11 I had installed the following compilers:
`clang`
`gcc6,`
`icc`

after `brew update --all`, `brew cleanup` and `brew doctor`

I get the following message:

```
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    gcc6
```

apparently what has happened is that after `brew update` I ended up with two different version of gcc6

```
/usr/localCellar/gcc/6.2.0
/usr/local/Cellar/gcc6/6.1.0
```

If I follow the message in the warning and I execute `brew link gcc6` I get:

```
Linking /usr/local/Cellar/gcc6/6.1.0...
Error: Could not symlink bin/c++-6
Target /usr/local/bin/c++-6
is a symlink belonging to gcc. You can unlink it:
  brew unlink gcc

To force the link and overwrite all conflicting files:
  brew link --overwrite gcc6

To list all files that would be deleted:
  brew link --overwrite --dry-run gcc6
```

Now the question is should I be doing the `--overwrite` or just remove `gcc6`?
Another thing that is weird is that new version of `gcc6->gcc-6.2.1` ended up in a different directory `/usr/local/Cellar/gcc/6.2.0` than from the previous version of `gcc6->gcc-6.1.0` `=> /usr/local/Cellar/gcc6/6.1.0`. Why is that?

That's why `brew list --versions --multiple` cannot catch that.

Otherwise `brew cleanup` would have saved us some time.

**Comment by vladshablinsky** [comment]
Seems like you have `homebrew/versions` tapped and installed gcc both from `homebrew/versions` and `homebrew/core`. Installing `gcc` from `homebrew/core` leaves you with installation under
`/usr/local/Cellar/gcc/<version>`. And `gcc6` is a different formula, so it gets installed under `/usr/local/Cellar/gcc6/<version>`. So, I can come up with this scenario:
You had installed both `gcc` and `gcc6` (both have `c++6` binary so even before upgrade your `brew doctor` would probably warn you) and then `gcc` got outdated, you upgraded it and cleaned it up, but nothing changed too much. You still have two formulae with similar binaries. It's up to you to choose which one to link and the behaviour you got is expected.

> Now the question is should I be doing the --overwrite or just remove gcc6?

Well, I think you should decide which of two formulae you need i.e. `gcc` or `gcc6`. And link it. But I'm not sure it'll fix the `brew doctor` warning. Uninstalling one of them should fix it.

**Comment by kirk86** [comment]
@vladshablinsky 👍  Thanks. sometimes when I look for too long the screen I don't know what I'm doing.  :(
