### ISSUE TITLE
gtest and gmock are now installable systemwide

### ISSUE THREAD

**Issue by rleigh-codelibre** [Homebrew/brew#8935]
# Feature suggestion

```
% brew install gtest
Updating Homebrew...
Error: No available formula or cask with the name "gtest".
Installing gtest system-wide is not recommended; it should be vendored
in your projects that use it.
```

This prohibition upon systemwide installation of gtest and gmock was never strictly correct.  The concerns which prevented it apply equally to all C++ libraries.

Current versions of googletest do permit systemwide installation and do have an install target which will correctly install gtest/gmock as expected.

# A detailed description of the proposed feature

Please drop the prohibition upon gtest/gmock installation and package it like any other library.

# The motivation for the feature

These libraries are widely used, currently if you're developing software you are required to vendor them, which is often not possible or undesirable, and this requires manually building a third-party dependency and explicitly configuring the build to use it.  This could be avoided entirely if it were packaged and installed directly through homebrew.

# How the feature would be relevant to at least 90% of Homebrew users

I'm not sure it would be something 90% would care about, since it's the removal of a special-case for two specific packages.  But it's something which I think would be relevant to all of the homebrew users who also use googletest.

# What alternatives to the feature have been considered

The alternative is the status quo which formally bans this being packaged.  It's this decision that I think should be revisited, because the upstream prohibition which prevented it being packaged has long since been relaxed.

**Comment by MikeMcQuaid** [comment]
Can you point to a link to convince us that this was an upstream recommendation that has now changed?

**Comment by rleigh-codelibre** [comment]
Hi Mike,


Install support was restored between 3 and 5 years ago in several PRs, for example:

* https://github.com/google/googletest/pull/650
* https://github.com/google/googletest/pull/1160
* https://github.com/google/googletest/pull/768

Additionally, the prohibition about not installing is now gone entirely.  This was primarily enforced by the Autotools build, which is now deleted.  From the 1.6.0 Makefile.am:

```
install-exec-local:
        echo "'make install' is dangerous and not supported. Instead, see README for how to integrate Google Test into your build system."
        false

install-data-local:
        echo "'make install' is dangerous and not supported. Instead, see README for how to integrate Google Test into your build system."
        false
```

This came from commit https://github.com/google/googletest/commit/661758ec1a2 in 2011 just prior to the 1.6.0 release.

The current top-level CMake build has:

https://github.com/google/googletest/blob/master/CMakeLists.txt#L26

```
option(INSTALL_GTEST "Enable installation of googletest. (Projects embedding googletest may want to turn this OFF.)" ON)
```

That is, installation is on by default unless you explicitly turn it off when embedding.

Other than the removal of the Autotools, and the improvement of the CMake install support over time, I can't point you to a single point in time when the old policy ended.  It was never enforced or documented anywhere except the Makefile.am.  The CMake support always permitted it as far as I can see (modulo bugs).

Also note that the ODR violation is primarily a Windows problem when using incompatible MSVC runtimes.  It's simply not a problem on MacOS or Linux with the system libc++ or libstdc++.  And the issue applies to every single C++ library on the system.  There is nothing about gtest which makes it special in this regard.  Note that even on Windows, vcpkg installs gtest (https://github.com/microsoft/vcpkg/blob/56ff7ccb48191618bd4a5bdfb6ab05d1e28a0683/ports/gtest/portfile.cmake).  The only other system I was aware of which didn't install the library was Debian and its derivatives, and it now also installs a static library and the headers (just checked).  FreeBSD ports install.  Fedora/CentOS installs.  As far as I can tell, Homebrew is the only system which continues to not permit installation, though there may be others I'm unaware of.  As a result, I think it would be perfectly reasonable for homebrew to also install.


Kind regards,
Roger

**Comment by MikeMcQuaid** [comment]
Thanks for the clarification! Could you open a PR to remove from the deny list: https://github.com/Homebrew/brew/blob/4e8d37494231718d501e04c482bdd764f6b2587a/Library/Homebrew/missing_formula.rb#L39-L46
