### ISSUE TITLE
How can developers in China improve Speed?

### ISSUE THREAD

**Issue by Xunzhuo** [Homebrew/brew#8938]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install and use homebrew.

## What happened (include command output)

When installing homebrew, the speed is very slow and often disconnect with server. Even if I install it, the speed of installing package is very slow as well.

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

Improve the speed or give me some help.

## Output of `brew config` and `brew doctor` commands

<pre>

</pre>

**Comment by MikeMcQuaid** [comment]
Sorry, this is something you'll need to figure out yourself, there's nothing Homebrew can do about it.
