### ISSUE TITLE
meld formula failed to build on 10.11.6 and brew update broke all package symlinks

### ISSUE THREAD

**Issue by aproxs** [Homebrew/brew#894]
I've run `brew update` twice and fixed as many issues as possible with `brew doctor` already.

I ran brew update on 09/05/16 and got a bunch of warnings saying that a substantial amount of symlinks were broken and/or needed update in:
```
/usr/local/share/man/man1
```
Which I deleted to move forward.

I ran the following commands after that:
```
brew update
brew update
brew upgrade
```

And every package that needed to be upgraded had issues with the symlinks.
the output from `brew upgrade` showed something like this (this example with meld, but it happened in all the other packages):
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/man/man1/meld.1
Target /usr/local/share/man/man1/meld.1
is a symlink belonging to meld. You can unlink it:
  brew unlink meld

To force the link and overwrite all conflicting files:
  brew link --overwrite meld

To list all files that would be deleted:
  brew link --overwrite --dry-run meld
```

When I run the suggested commands (`brew unlink meld`) I get 0 symlinks removed, and if I try to run 'brew update' again I keep getting the same error until I run `brew link --overwrite meld`.

This seems to be the case for all the packages I had installed in the system, and even their dependencies, which makes the upgrade process really involved an manual.

Things that I've noticed:
Before running the first `brew update`, homebrew was generating symlinks in:
```
/usr/local/bin
```
and now, when I install a package the symlink structure is different and is created under:
```
/usr/local/opt
```

A lot of the symlinks in the `$(brew --repo)/` subfolders (`bin`, `include`, `lib`, `opt`, `share`) seem to be broken and pointing to old versions of the packages.
I just did a quick check on those top level folders but I am sure that other folders and subfolders have broken links too (i.e.: `etc/bash_completion`.

Other than being located in `$HOME/homebrew`, my homebrew installation is nothing special.

Any suggestions on how to get out of this state?

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by aproxs** [comment]
Sorry for not posting the gist before.

Here is the gist: https://gist.github.com/anonymous/baf2fd3ddd22ad79a55d4856207a515c

**Comment by MikeMcQuaid** [comment]
@aproxs Can I see the output of your `which brew`? Do you intend your Homebrew to be entirely self-contained under `/Users/luis/homebrew`? Thanks!

**Comment by aproxs** [comment]
this is the output:
```
/Users/luis/homebrew/bin/brew
```

Yes, my intention is to have homebrew self contained.

**Comment by MikeMcQuaid** [comment]
@aproxs Interesting. Can I see the output from `ls -lha /usr/local/bin/brew` and `ls /usr/local/`? Thanks!

**Comment by aproxs** [comment]
The first one:
```
ls -lha /usr/local/bin/brew
lrwxr-xr-x 1 luis admin 29 Oct 30  2015 /usr/local/bin/brew -> /Users/luis/homebrew/bin/brew
```

And the second one:
```
ls /usr/local/
Frameworks  apache-maven  azure  bin  etc  git  include  lib  mysql  mysql-5.6.26-osx10.8-x86_64  opt  sbin  share  var
```

**Comment by MikeMcQuaid** [comment]
@aproxs That symlink is your issue; if you delete it you'll get back to your previous state. May I ask why you have it if it's not in your `$PATH`?

**Comment by aproxs** [comment]
I see. I don't remember when or why I might have created that symlink and I really don't have a good reason to keep it.

I deleted the symlink and homebrew seems happy now.

Thanks for taking the time to look into this Mike! I really appreciate it!
