### ISSUE TITLE
brew update gets stuck

### ISSUE THREAD

**Issue by JRSijsling** [Homebrew/brew#895]
Hello,

Yesterday I discovered the Aug10-11 bug and ran the line to fix this. It got my homebrew back to life and I got lost of updates. I could also install julia from cask. Since then, however, running

~$ brew update

seems to get stuck. That is, nothing happens and I need <Ctrl-C> to get back to the prompt. I have tried to rerun the Aug10-11 line and it too gets stuck now.

brew upgrade still did something (the first time, not afterwards of course), namely

$ brew upgrade
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
azure-cli               go                      influxdb                mercurial               pypy                    telegraf
fleetctl                gtkextra                lean-cli                pidcat                  sane-backends           todolist

The results of brew config and brew doctor can be found below. The files that the latter warns about have to do with mathematics software that I installed. Thanks in advance!

$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 495419a4ee0456e592bd32906b2d4a4cfa9dbf99
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d469e749120d701f84d47681497d049bba46d9c7
Core tap last commit: 15 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 6.0 build 600
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1/bin/ruby
Java: 1.6.0_65-b14-462
OS X: 10.9.5-x86_64
Xcode: N/A
bCLT: 6.2.0.0.1.1424975374
X11: 2.7.7 => /opt/X11
local$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.7) is outdated
Please install XQuartz 2.7.9:
  https://xquartz.macosforge.org

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libcmh.0.dylib
    /usr/local/lib/libfplll.0.dylib
    /usr/local/lib/libmpfrcx.1.dylib
    /usr/local/lib/libpari-gmp.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/cmh.h
    /usr/local/include/fplll/bkz.h
    /usr/local/include/fplll/defs.h
    /usr/local/include/fplll/dpe.h
    /usr/local/include/fplll/evaluator.h
    /usr/local/include/fplll/fplll.h
    /usr/local/include/fplll/fplll_config.h
    /usr/local/include/fplll/fplllv31.h
    /usr/local/include/fplll/gso.h
    /usr/local/include/fplll/lll.h
    /usr/local/include/fplll/matrix.h
    /usr/local/include/fplll/nr.h
    /usr/local/include/fplll/numvect.h
    /usr/local/include/fplll/svpcvp.h
    /usr/local/include/fplll/util.h
    /usr/local/include/fplll.h
    /usr/local/include/mpfrcx.h
    /usr/local/include/pari/mpinl.h
    /usr/local/include/pari/pari.h
    /usr/local/include/pari/paricast.h
    /usr/local/include/pari/paricfg.h
    /usr/local/include/pari/paricom.h
    /usr/local/include/pari/paridecl.h
    /usr/local/include/pari/parierr.h
    /usr/local/include/pari/parigen.h
    /usr/local/include/pari/pariinl.h
    /usr/local/include/pari/parimt.h
    /usr/local/include/pari/parinf.h
    /usr/local/include/pari/pariold.h
    /usr/local/include/pari/paripriv.h
    /usr/local/include/pari/paristio.h
    /usr/local/include/pari/parisys.h
    /usr/local/include/pari/paritune.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libcmh.la
    /usr/local/lib/libfplll.la
    /usr/local/lib/libmpfrcx.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libcmh.a
    /usr/local/lib/libfplll.a
    /usr/local/lib/libmpfrcx.a

**Comment by MikeMcQuaid** [comment]
Please run `brew update --debug --verbose` and paste your output in a Gist and then `brew update --force` and tell us if the latter command succeeds, thanks!

**Comment by JRSijsling** [comment]
Wonderful, that did it! It seems to be back to normal working order, so this is closed as far as I am concerned. Gist below in case you are interested. It downloaded something large in the process. Something to do with cask, which I needed to install Julia.

https://gist.github.com/JRSijsling/91c921d10331cfd5b1318081de3d0bde

**Comment by MikeMcQuaid** [comment]
Glad it's working!

**Comment by pearl98** [comment]
i also have the same issue
