### ISSUE TITLE
Formula not installing from file

### ISSUE THREAD

**Issue by Conky5** [Homebrew/brew#8966]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install a formula from a file on disk.

## What happened (include command output)

The `brew install` completes with no output and a success exit code, without installing the formula.

<details>
  <summary>Command output</summary>
  <pre>

% brew install Formula/eq.rb
%

  </pre>
</details>

## What you expected to happen

The formula gets installed.

## Step-by-step reproduction instructions (by running `brew` commands)

```shell
git clone https://github.com/Conky5/homebrew-tap.git
cd homebrew-tap
brew install Formula/eq.rb
```

It appears if you use an absolute path or prefix a local path with `./` it works. Like `brew install ./Formula/eq.rb`. This used to not be required, not sure if it is intentional or not.

## Output of `brew config` and `brew doctor` commands

<pre>
% brew config
HOMEBREW_VERSION: 2.5.6-106-g6747474
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6747474148b13bd6d399b05de38ffed515d4c395
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f877e3f8090f714a4f9c2cbeab374e7dfe116cde
Core tap last commit: 15 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dual-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_265
macOS: 10.15.7-x86_64
CLT: 12.0.32.2
Xcode: 12.0.1
% brew doctor
Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment]
> It appears if you use an absolute path or prefix a local path with `./` it works. Like `brew install ./Formula/eq.rb`. This used to not be required, not sure if it is intentional or not.

This is intentional otherwise it thinks `Formula/eq.rb` is the name of a formula. In general we using `brew tap` and `brew install user/repo/formula` instead.

**Comment by tmewett** [comment]
I still think this should be considered a bug. Surely there is supposed to be some info messages, or an error message, or at the very least a non-zero exit code? Otherwise this is a completely silent "task failed successfully" :grin: 

From our perspective this is a breaking change; previous version worked for about a year for me. If it's now required to use `./` when installing local formula, perhaps the relevant section of the manpage, [SPECIFYING FORMULAE](https://docs.brew.sh/Manpage#specifying-formulae), could be updated? What do you think?

**Comment by MikeMcQuaid** [comment]
@tmewett We do not consider it a bug. We'll review a PR to adjust documentation or the underlying behaviour if this negatively affects you.

**Comment by tmewett** [comment]
To clarify I'm not contending the new behaviour right now - I'm just saying, should there not be output? Is it completely intended for `brew install` to print absolutely nothing and return successful when it does nothing, after being explicitly asked to do *something*? I would expect some "install failed: cannot find tap/cask/core formula called Formula/eq.rb", but maybe I have different ideas about failure tolerance to you. Should I open another issue for this specifically?

Glad to hear you'd review a PR anyway. Thanks for the response

**Comment by MikeMcQuaid** [comment]
@tmewett I don't know what output you're seeing/not seeing. Can you paste what you're running and seeing here?

**Comment by dtrodrigues** [comment]
More background here - https://github.com/Homebrew/discussions/discussions/147. I agree that some sort of error message would be helpful vs silently doing nothing.

**Comment by reitermarkus** [comment]
Just to be explicit: The reason why `./` is required for relative paths is because we want `brew install formula` to always resolve to the `formula` in an installed tap instead of a file at `./formula`.

**Comment by MikeMcQuaid** [comment]
Yes, agreed: silent output here was not what I expected and is bad.
