### ISSUE TITLE
bump-formula-pr breaks formula when multiple URLs are used

### ISSUE THREAD

**Issue by rothgar** [Homebrew/brew#8967]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Bump a formula version for a formula that has multiple URLs to support macOS and Linux binaries.

## What happened (include command output)

I set up an example formula with 3 URLs for macOS, Linux (amd64 and arm). When I run this command

```
brew bump-formula-pr --version=0.1.3 --no-audit \
   --no-browse --message="testing" \
   --url="https://releases.hashicorp.com/waypoint/0.1.3/waypoint_0.1.3_linux_amd64.zip" \
   rothgar/homebrew-hashicorp-tap/waypoint
```

The all of the URLs are updated based on regex searches but only the linux url sha is updated for the new version. This breaks install for users trying to install from macOS or Linux with arm.

<details>
  <summary>Command output</summary>
  <pre>

==> Downloading https://releases.hashicorp.com/waypoint/0.1.3/waypoint_0.1.3_linux_amd64.zip
Already downloaded: /home/ANT.AMAZON.COM/rothgar/.cache/Homebrew/downloads/dcd9e4d97c7a280488be13c7646c622a1cc8e46b33b02107076f13abe5766e28--waypoint_0.1.3_linux_amd64.zip
Warning: Cannot verify integrity of dcd9e4d97c7a280488be13c7646c622a1cc8e46b33b02107076f13abe5766e28--waypoint_0.1.3_linux_amd64.zip
A checksum was not provided for this resource.
For your reference the SHA-256 is: bdf668eacd418ca412df9a93e9c243d790653eea75df608a242965ef79998633
==> replace /https:\/\/releases\.hashicorp\.com\/waypoint\/0\.1\.2\/waypoint_0\.1\.2_linux_amd64\.zip/ with "https://releases.hashicorp.com/waypoint/0.1.3/waypoint_0.1.3_linux_amd64.zip"
==> replace "bdf668eacd418ca412df9a93e9c243d790653eea75df608a242965ef79998633" with "bdf668eacd418ca412df9a93e9c243d790653eea75df608a242965ef79998633"
==> replace "0.1.2" with "0.1.3"
==> Skipping `brew audit`
M       Formula/waypoint.rb
Switched to a new branch 'bump-waypoint-0.1.3'
[bump-waypoint-0.1.3 e155817] waypoint 0.1.3
 1 file changed, 4 insertions(+), 4 deletions(-)
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 390 bytes | 390.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote:
remote: Create a pull request for 'bump-waypoint-0.1.3' on GitHub by visiting:
remote:      https://github.com/rothgar/homebrew-hashicorp-tap/pull/new/bump-waypoint-0.1.3
remote:
To https://github.com/rothgar/homebrew-hashicorp-tap.git
 * [new branch]      bump-waypoint-0.1.3 -> bump-waypoint-0.1.3
Branch 'bump-waypoint-0.1.3' set up to track remote branch 'bump-waypoint-0.1.3' from 'https://e9a26a15e1d233c558376809e02ac86ade4d00ea@github.com/rothgar/homebrew-hashicorp-tap.git'.
https://github.com/rothgar/homebrew-hashicorp-tap/pull/1

  </pre>
</details>

## What you expected to happen

I would like a way to specify multiple urls and shas so that I can update the required URLs and shas at once

## Step-by-step reproduction instructions (by running `brew` commands)

The same thing happens with and without `--sha`
```
brew bump-formula-pr --version=0.1.3 --no-audit \
   --no-browse --message="testing" \
   --url="https://releases.hashicorp.com/waypoint/0.1.3/waypoint_0.1.3_linux_amd64.zip" \
   rothgar/homebrew-hashicorp-tap/waypoint
```

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.5.6-106-g6747474
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6747474148b13bd6d399b05de38ffed515d4c395
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 33e5dd24320a2a40682ff1bc65f0b132d2982a2a
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 5.3.0-28-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.5 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.5.0
/usr/bin/ruby: 2.5.1
glibc: N/A
gcc: N/A
xorg: N/A
</pre>

<pre>
brew doctor
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libxfixes instead of deprecated linuxbrew/xorg/libxfixes
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libice instead of deprecated linuxbrew/xorg/libice
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libice instead of deprecated linuxbrew/xorg/libice
Warning: Use libsm instead of deprecated linuxbrew/xorg/libsm
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Your system is ready to brew.
</pre>
I haven't figured out how to fix the deprecated formula but I don't think they matter here

**Comment by MikeMcQuaid** [comment]
> Bump a formula version for a formula that has multiple URLs to support macOS and Linux binaries.

This is not something we support, sorry. Our way of distributing binaries is to use `bottle do` blocks. We'll review PRs to improve this behaviour.
