### ISSUE TITLE
install brew error  error: Failed to merge in the changes.

### ISSUE THREAD

**Issue by LIXIAOSHUANG** [Homebrew/brew#8975]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
install brew
/usr/bin/ruby -e "$(curl -fsSL https://cdn.jsdelivr.net/gh/ineo6/homebrew-install/install)"

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew` commands)

error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
To restore the stashed changes to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash pop'
Error: 767: unexpected token at '{
<<<<<<< HEAD
  "azure-cli": "homebrew/core",
  "basex": "homebrew/core",
  "borgbackup": "homebrew/core",
  "chronograf": "homebrew/core",
  "cocoapods": "homebrew/core",
  "consul": "homebrew/core",
  "consul-template": "homebrew/core",
  "cryptol": "homebrew/core",
  "cups-pdf": "homebrew/core",
  "dmd": "homebrew/core",
  "docker-compose": "homebrew/core",
  "exa": "homebrew/core",
  "exiftool": "homebrew/core",
  "fastlane": "homebrew/core",
  "fpc": "homebrew/core",
  "gedit": "homebrew/core",
  "ghc": "homebrew/core",
  "go": "homebrew/core",
  "graphviz": "homebrew/core",
  "handbrakecli": "homebrew/core",
  "helm": "homebrew/core",
  "hub": "homebrew/core",
  "hyper": "homebrew/core",
  "idris": "homebrew/core",
  "java": "homebrew/core",
  "jenkins": "homebrew/core",
  "lunchy": "homebrew/core",
  "minikube": "homebrew/core",
  "mitmproxy": "homebrew/core",
  "mosh": "homebrew/core",
  "nmap": "homebrew/core",
  "node": "homebrew/core",
  "nomad": "homebrew/core",
  "otto": "homebrew/core",
  "packer": "homebrew/core",
  "pandoc": "homebrew/core",
  "pgloader": "homebrew/core",
  "pgweb": "homebrew/core",
  "podman": "homebrew/core",
  "purescript": "homebrew/core",
  "python": "homebrew/core",
  "python3": "homebrew/core",
  "r": "homebrew/core",
  "redis": "homebrew/core",
  "rust": "homebrew/core",
  "serf": "homebrew/core",
  "sickbeard": "homebrew/core",
  "srclib": "homebrew/core",
  "sshfs": "homebrew/core",
  "sslmate": "homebrew/core",
  "swi-prolog": "homebrew/core",
  "syncthing": "homebrew/core",
  "terraform": "homebrew/core",
  "vault": "homebrew/core",
  "vfuse": "homebrew/core",
  "volatility": "homebrew/core"
=======
  "adobe-air-sdk": "homebrew/cask",
  "android-ndk": "homebrew/cask",
  "android-platform-tools": "homebrew/cask",
  "android-sdk": "homebrew/cask",
  "app-engine-go-32": "homebrew/cask/google-cloud-sdk",
  "app-engine-go-64": "homebrew/cask/google-cloud-sdk",
  "avidemux": "homebrew/cask",
  "chromedriver": "homebrew/cask",
  "cmucl": "homebrew/cask",
  "cockatrice": "homebrew/cask",
  "crystax-ndk": "homebrew/cask",
  "corelocationcli": "homebrew/cask",
  "dwarf-fortress": "homebrew/cask",
  "geany": "homebrew/cask",
  "gimp": "homebrew/cask",
  "grads": "homebrew/cask",
  "gtkwave": "homebrew/cask",
  "horndis": "homebrew/cask",
  "inkscape": "homebrew/cask",
  "jsl": "homebrew/cask",
  "kdiff3": "homebrew/cask",
  "keybase": "homebrew/cask",
  "meld": "homebrew/cask",
  "osxfuse": "homebrew/cask",
  "phantomjs": "homebrew/cask",
  "quassel": "homebrew/cask",
  "transmission-remote-gtk": "homebrew/cask/transmission-remote-gui",
  "tuntap": "homebrew/cask"
>>>>>>> imagemagick@6: update 6.9.10-53 bottle.
}
'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:541:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/tap.rb:687:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:220:in `block in report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:193:in `each_line'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:193:in `report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:430:in `add'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:105:in `block in update_report'
/usr/local/Homebrew/Library/Homebrew/tap.rb:559:in `block (2 levels) in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:558:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:558:in `block in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:557:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:557:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:94:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
Failed during: /usr/local/bin/brew update --force
## Output of `brew config` and `brew doctor` commands

<pre>

</pre>

**Comment by MikeMcQuaid** [comment]
`brew update-reset` should fix this.
