### ISSUE TITLE
Conflicting jpeg and libJPEG

### ISSUE THREAD

**Issue by nizar-sallem** [Homebrew/brew#898]
Homebrew was updated on Sep 8th 2016 

I did:
- [x] Ran `brew update` and retried
- [x] Ran `brew doctor`, no real issues there

### Bug reports:

I installed PCL from brew with qt support: brew install homebrew/science/pcl --with-qt, this installed jpeg among other things.

Trying to run pcl_vlp_viewer results in this error: 
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libjpeg.8.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Trace/BPT trap: 5

Seems that something is trying to load Framework JPEG library but it is actually built with brew jpeg.

Not sure what would be the appropriate fix.

**Comment by MikeMcQuaid** [comment]
Please report this to homebrew/science, thanks.
