### ISSUE TITLE
brew install/search combo command

### ISSUE THREAD

**Issue by tkreind** [Homebrew/brew#8986]
# Feature suggestion
I would like to propose a new subcommand 'sinstall' (hopefully someone comes up with a better name).

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# A detailed description of the proposed feature

sinstall simply bundles two brew commands in one, search and install. It attempts to install a package with the given name and if it doesn't exist performs a brew search.

# The motivation for the feature

I often find myself not confident that I know the exact name of a package, even when I usually do. I often don't want to search if I don't have to because it can take quite a while. A simple example that just occurred to me is as follows:

I wanted to install kekadefaultapp, I run 'brew cask install keka-default-app' which fails. I then run 'brew search keka-default-app' which shows me the cask I'm looking for is 'brew cask install kekadefaultapp'. Under the new routine I could run 'brew cask sinstall Keka-default-app' which would give me the required info in one less command.

Alternatively if I guessed it was kekadefaultapp but wasn't sure I might run an unnecessary search command beforehand. This removes the need for that.

# How the feature would be relevant to at least 90% of Homebrew users

I think this issue of not being confident we know a package name when we really do is quite common to the vast majority of users.

# What alternatives to the feature have been considered

brew install already has a default prompt if the specified formula was only barely off (ie python3.8 -> python@3.8). This is on the right track but isn't nearly as comprehensive as a full brew search and in my kekadefaultapp case and many others it doesn't catch it. Expanding this prompt to include a full array of brew search results would be even better, but I'd imagine isn't being done to lessen server load.

**Comment by MikeMcQuaid** [comment]
We do do a `brew install` and we don't find the formula it does automatically run `brew search` for your term. See:

```
mikebook # brew install wge
Error: No available formula or cask with the name "wge".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
These similarly named formulae were found:
brew-gem     liblwgeom    pwgen        sf-pwgen     wget ✔       wgetpaste
To install one of them, run (for example):
  brew install brew-gem
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```
