### ISSUE TITLE
brew upgrade --non-cask or --no-cask

### ISSUE THREAD

**Issue by docwhat** [Homebrew/brew#8992]
# Feature suggestion

Add a `brew upgrade` flag: `--no-cask` or `--non-cask`

# A detailed description of the proposed feature

I propose adding a flag to allow upgrading only non-cask items as a compliment to the `--cask` flag.

# The motivation for the feature

With the merging of the cask and non-cask commands (yay!) it is no longer possible to upgrade only non-cask formulas.

# How the feature would be relevant to at least 90% of Homebrew users

It was handy to upgrade formulas by themselves since they could run unattended.

Casks generally need to be watched and for some, a username and password would need to be provided for `sudo`.

# What alternatives to the feature have been considered

Installing (and attending) casks first.

**Comment by MikeMcQuaid** [comment]
`brew upgrade --formula`, `brew upgrade --cask` already exist. Please read the manpage in future first, thanks!

**Comment by docwhat** [comment]
I read the `brew upgrade --help` and `--formula` was not near `--cask` nor mentioned "cask".  The man page section for `upgrade` is similar.

It didn't occur to me that `formula` is the same as `non-cask`.

I saw that most options had `--no-foobar` versions and thought that `--non-cask` fit in with pattern.

Maybe mention cask in the `--formula` help and `formula` in the `--cask` help?

**Comment by MikeMcQuaid** [comment]
> Maybe mention cask in the `--formula` help and `formula` in the `--cask` help?

We'll consider this if we see more than one person with this problem.
