### ISSUE TITLE
El Capitan Upgrade results in error: Insecure world Issues on /usr/local in PATH

### ISSUE THREAD

**Issue by v1k0d3n** [Homebrew/brew#9]
Before an El Capitan upgrade, 'brew' was working just fine. Afterwards, I received errors:

```
...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040777
...
```
I tried to upgrade homebrew, but the problems still persist. I am using zsh, but this occurs in bash as well. Is there something else I should be doing to resolve this issue, or does anyone have any recommendations?

**Comment by v1k0d3n** [comment]
oddly enough, when i ran the old school "permissions repair" at the cli, now I receive the following: 

```
$ sudo /usr/libexec/repair_packages --repair --standard-pkgs --volume /
...
...
...
$ brew update
Error: /usr/local must be writable!
```

**Comment by UniqMartin** [comment]
This is not directly related to Homebrew, as the message is coming from the system-provided Ruby. Homebrew is just built on top of it, that's why you see those messages when using Homebrew.

At some point you must have changed the permissions of `/usr/local` to be writeable for *everyone*. That's usually not a good idea, hence the warning. It should go away if you change the permissions to something more restrictive (e.g. write access only for your user, others get only read access).

**Comment by v1k0d3n** [comment]
i definitely didn't change those permissions, unless the upgrade did something funky? this was a little unexpected, honestly. thanks for the quick reply though!

**Comment by UniqMartin** [comment]
> oddly enough, when i ran the old school "permissions repair" at the cli, now I receive the following:

That solved the problem of giving too many people access, which is good. But now you've locked yourself out of Homebrew. Please review the [troubleshooting guide](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting), the solution is listed in the “Common Issues” section! Thanks!

**Comment by v1k0d3n** [comment]
ah ha! did the trick. i've been using home-brew for a long time, but i think i mixed up the order when running `brew doctor`. repaired permissions and _then_ ran `sudo chown -R $(whoami) /usr/local`. problem solved. thank you for the _gentle_ reminder :)

**Comment by creationator** [comment]
I am having this issue now, and the troubleshooting guide is unavailable now...can someone help please!

**Comment by MikeMcQuaid** [comment]
@creationator `sudo chown -R $USER:admin /usr/local`.
