### ISSUE TITLE
ncmpcpp does not start after updated icu4u

### ISSUE THREAD

**Issue by fooness** [Homebrew/brew#90]
Maybe someone could please fix this. It seems ncmpcpp seems just to be linked(?) to the new library?

~ >> brew doctor
Your system is ready to brew.

~ >> ncmpcpp
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.56.dylib
  Referenced from: /usr/local/bin/ncmpcpp
  Reason: image not found
Trace/BPT trap: 5

~>> ls /usr/local/opt/icu4c/lib/libicuuc.<TAB>
libicuuc.57.1.dylib  libicuuc.57.dylib@   libicuuc.a           libicuuc.dylib@

Thanks in advance!

**Comment by UniqMartin** [comment]
`ncmpcpp` has no direct dependency on `icu4c`, but depends on a non-standard build of `boost` with the `--with-icu4c` option. I'm pretty sure that rebuilding `boost` will fix the problem, i.e. please try `brew reinstall boost` and report back.

In the future, please report this kind of issue to the [homebrew-core repository](https://github.com/Homebrew/homebrew-core). This repository is for issues with the package manager itself, not for issues with specific formulae. Thanks!

I'll check if we can do something to prevent this kind of breakage in the future.

**Comment by fooness** [comment]
Excuse me, I did not know I’m in the wrong repository—and thanks for the link to the right one! Unfortunately, that didn’t help. Can you maybe move the issue? I’m not sure that’s possible here.

~ >> brew reinstall boost
==> Reinstalling boost with --with-icu4c
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/boost-1.60.0.tar.bz2
==> Patching
patching file boost/graph/adjacency_matrix.hpp
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.60.0_1 --libdir=/usr/local/Cellar/boost/1.60.0_1/lib --with-icu=/usr/local/opt/icu4c --without-libraries=python,mpi
==> ./b2 headers
==> ./b2 --prefix=/usr/local/Cellar/boost/1.60.0_1 --libdir=/usr/local/Cellar/boost/1.60.0_1/lib -d2 -j4 --layout=tagged --user-config=user-config.jam install threading=multi,single link=shared,static
🍺  /usr/local/Cellar/boost/1.60.0_1: 11,139 files, 441.5M, built in 31 minutes 6 seconds

~ >> ncmpcpp -c .ncmpcpp/config.net
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.56.dylib
  Referenced from: /usr/local/bin/ncmpcpp
  Reason: image not found
Trace/BPT trap: 5

~ >> brew reinstall boost --force --download
==> Reinstalling boost with --with-icu4c
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/boost-1.60.0.tar.bz2
==> Patching
patching file boost/graph/adjacency_matrix.hpp
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.60.0_1 --libdir=/usr/local/Cellar/boost/1.60.0_1/lib --with-icu=/usr/local/opt/icu4c --without-libraries=python,mpi
==> ./b2 headers
==> ./b2 --prefix=/usr/local/Cellar/boost/1.60.0_1 --libdir=/usr/local/Cellar/boost/1.60.0_1/lib -d2 -j4 --layout=tagged --user-config=user-config.jam install threading=multi,single link=shared,static
🍺  /usr/local/Cellar/boost/1.60.0_1: 11,139 files, 441.5M, built in 16 minutes 1 second

~ >> ncmpcpp -c .ncmpcpp/config.net
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.56.dylib
  Referenced from: /usr/local/bin/ncmpcpp
  Reason: image not found
Trace/BPT trap: 5

**Comment by UniqMartin** [comment]
> Unfortunately, that didn’t help.

You're right, sorry. The rebuild of `boost` was probably necessary anyway, but there's one more issue. It's now identified and a new build of `ncmpcpp` is scheduled (see Homebrew/homebrew-core#344). It should be available soon and I'll let you know here in the issue once it's ready! If you're impatient, you can fix the issue by rebuilding from source via `brew reinstall --build-from-source ncmpcpp`.

> Can you maybe move the issue? I’m not sure that’s possible here.

Let's keep it here. Unfortunately, there's no nice way on GitHub to move issues to other repositories.

**Comment by UniqMartin** [comment]
The fixed bottle should be available now. A `brew update` followed by a `brew upgrade ncmpcpp` should fix the issue. Many thanks for reporting, @fooness!
