### ISSUE TITLE
`brew commands` doesn't show audit, etc.

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#900]
Some commands were newly moved into the dev-cmd folder.  These no longer show up in the output of `brew commands`.

I think it's a little surprising that users are often told to run `brew audit`, but `audit` doesn't appear in a requested list of available brew commands.

Same for `edit`.

**Comment by scpeters** [comment]
If you have `HOMEBREW_DEVELOPER` set then I think it will show them in a separate section.

**Comment by reitermarkus** [comment]
Works for me, with and without `HOMEBREW_DEVELOPER`.

![bildschirmfoto 2016-09-09 um 23 46 27](https://cloud.githubusercontent.com/assets/1309829/18403896/b27aec18-76e7-11e6-9b02-635ad88d9c47.png)

**Comment by bfontaine** [comment]
@reitermarkus Run `brew update` and try again 😉

**Comment by reitermarkus** [comment]
Ok, nevermind. 😂

**Comment by chdiza** [comment]
I kinda think the dev-cmds should be shown in their own section regardless of whether $HOMEBREW_DEVELOPER is set.

There seems to be no reason to hide them, especially when it just recently became the case that anyone can run them with `brew`, whether or not the shellvar is set.

**Comment by MikeMcQuaid** [comment]
Agreed. Will fix (but anyone feel free to beat me to it)

**Comment by zmwangx** [comment]
#903.
