### ISSUE TITLE
audit complains about linking to system frameworks that don't exist

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#9015]
Testing of the salt update PR gives a very weird audit error:

```
==> brew audit salt --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
Missing libraries:
  unexpected (/System/Library/Frameworks/AuthenticationServices.framework/Versions/A/AuthenticationServices)
  unexpected (/System/Library/Frameworks/OSLog.framework/Versions/A/OSLog)
  unexpected (/System/Library/Frameworks/PushKit.framework/Versions/A/PushKit)
  unexpected (/System/Library/Frameworks/Speech.framework/Versions/A/Speech)
  unexpected (/System/Library/Frameworks/SystemExtensions.framework/Versions/A/SystemExtensions)
Unexpected missing library linkage detected
salt:
  * salt has broken dynamic library links:
```

I suspect something is wrong with the audit, because it's perfectly legitimate for a formula to link against system frameworks. If there really is something wrong here, the error message is not clear enough that I understand what the problem is.

**Comment by MikeMcQuaid** [comment]
> I suspect something is wrong with the audit, because it's perfectly legitimate for a formula to link against system frameworks.

Are you sure those system frameworks exist?

**Comment by MikeMcQuaid** [comment]
Looking at the code: they do not.
