### ISSUE TITLE
Question: Does running `brew edit` make me a "developer" thereafter?

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#902]
Now that `brew edit` is a dev-cmd, running `brew edit foo` drops a crumb in the gitconfig file of the brew clone.

Does this mean that from now on, my local installation is going to behave as if I had set `HOMEBREW_DEVELOPER`?

If so, I think this is bad.  `brew edit` is a useful command for just looking at formulas even if I have no intention of "developing" them.  It's much more convenient than `brew cat` for this.  But I don't want the inspection of a formula to cause me to thereafter have to deal with the infelecities that go with having `HOMEBREW_DEVELOPER` set.  (In particular, with non-shallow clones of taps.)

I might be misunderstanding what that crumb does, though.  (Also, I know that the features lumped together under `HOMEBREW_DEVELOPER` might become separated somewhat.)

**Comment by MikeMcQuaid** [comment]
> Does this mean that from now on, my local installation is going to behave as if I had set HOMEBREW_DEVELOPER?

No. It'll mean we e.g. `git stash pop` and `git checkout` your existing branch when doing `brew update`.
