### ISSUE TITLE
'brew diy' preserves case in names, but 'brew link' lowercases. This makes mixed-case DIY kegs seemingly unlinkable

### ISSUE THREAD

**Issue by ferdnyc** [Homebrew/brew#9026]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Build 'AnsiGL' as an `autoconf` project, using an install prefix of `$(brew diy ...)`, then install and link it using `brew link AnsiGL`. (On Linux, though I think that's probably irrelevant for this bug. Have also tried this, separately, with a different project that uses CMake — identical results.)

## What happened (include command output)

`brew diy` preserved the case of the name (installed to `$(brew --prefix)/Cellar/AnsiGL/0.1/`), but `brew link AnsiGL` forces the name to lowercase. It fails to link `AnsiGL`, because it's looking for `ansigl`.

<details>
  <summary>Command output</summary>
  <pre>
$ cd /path/to/AnsiGL
$ ./configure $(brew diy --version 0.1)         
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
[---8<---snip---8<---]
$ make
[...COMPILER OUTPUT INTENSIFIES...]
$ make install   
Making install in src
make[1]: Entering directory '/home/ferd/rpmbuild/REPOS/AnsiGL/src'
Making install in ncurses
make[2]: Entering directory '/home/ferd/rpmbuild/REPOS/AnsiGL/src/ncurses'
make[3]: Entering directory '/home/ferd/rpmbuild/REPOS/AnsiGL/src/ncurses'
 /usr/bin/mkdir -p '/home/linuxbrew/.linuxbrew/Cellar/AnsiGL/0.1/lib'
 /bin/sh ../../libtool   --mode=install /usr/bin/install -c   libAnsiGL_ncurses.la '/home/linuxbrew/.linuxbrew/Cellar/AnsiGL/0.1/lib'
libtool: install: /usr/bin/install -c .libs/libAnsiGL_ncurses.so.0.0.0 /home/linuxbrew/.linuxbrew/Cellar/AnsiGL/0.1/lib/libAnsiGL_ncurses.so.0.0.0
libtool: install: (cd /home/linuxbrew/.linuxbrew/Cellar/AnsiGL/0.1/lib && { ln -s -f libAnsiGL_ncurses.so.0.0.0 libAnsiGL_ncurses.so.0 || { rm -f libAnsiGL_ncurses.so.0 && ln -s libAnsiGL_ncurses.so.0.0.0 libAnsiGL_ncurses.so.0; }; })
libtool: install: (cd /home/linuxbrew/.linuxbrew/Cellar/AnsiGL/0.1/lib && { ln -s -f libAnsiGL_ncurses.so.0.0.0 libAnsiGL_ncurses.so || { rm -f libAnsiGL_ncurses.so && ln -s libAnsiGL_ncurses.so.0.0.0 libAnsiGL_ncurses.so; }; })
libtool: install: /usr/bin/install -c .libs/libAnsiGL_ncurses.lai /home/linuxbrew/.linuxbrew/Cellar/AnsiGL/0.1/lib/libAnsiGL_ncurses.la
libtool: install: /usr/bin/install -c .libs/libAnsiGL_ncurses.a /home/linuxbrew/.linuxbrew/Cellar/AnsiGL/0.1/lib/libAnsiGL_ncurses.a
[...]
----------------------------------------------------------------------
Libraries have been installed in:
   /home/linuxbrew/.linuxbrew/Cellar/AnsiGL/0.1/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/home/linuxbrew/.linuxbrew/Cellar/AnsiGL/0.1/include/AnsiGL'
 /usr/bin/install -c -m 644 AnsiGL/achar.h AnsiGL/animation.h AnsiGL/ansi.h AnsiGL/area.h AnsiGL/camera.h AnsiGL/clone.h AnsiGL/color.h AnsiGL/content.h AnsiGL/context.h AnsiGL/defines.h AnsiGL/image.h AnsiGL/inputtext.h AnsiGL/inputwindow.h AnsiGL/pixel.h AnsiGL/point.h AnsiGL/string.h AnsiGL/surface.h AnsiGL/text.h AnsiGL/textwindow.h AnsiGL/uchar.h AnsiGL/window.h '/home/linuxbrew/.linuxbrew/Cellar/AnsiGL/0.1/include/AnsiGL'
make[3]: Leaving directory '/home/ferd/rpmbuild/REPOS/AnsiGL/src'
make[2]: Leaving directory '/home/ferd/rpmbuild/REPOS/AnsiGL/src'
make[1]: Leaving directory '/home/ferd/rpmbuild/REPOS/AnsiGL/src'
make[1]: Entering directory '/home/ferd/rpmbuild/REPOS/AnsiGL'
make[2]: Entering directory '/home/ferd/rpmbuild/REPOS/AnsiGL'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/ferd/rpmbuild/REPOS/AnsiGL'
make[1]: Leaving directory '/home/ferd/rpmbuild/REPOS/AnsiGL'

$ brew link AnsiGL
Error: No such keg: /home/linuxbrew/.linuxbrew/Cellar/ansigl
  </pre>
</details>

## What you expected to happen

Either `brew diy` lowercases the install path name, or `brew link` preserves the case of the supplied name. However they go about it, just that they agree with each other on how case is supposed to be handled.

## Step-by-step reproduction instructions (by running `brew` commands)

1. Build anything using `$(brew diy --name MixedCaseName --version 0.1)` as the install path
1. Install as per normal
1. `brew link MixedCaseName`
1. Get in response:
    > `Error: No such keg: $(brew --prefix)/Cellar/mixedcasename`

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.8-32-gfd00721-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: fd007219cc074d73ecb080fc26b1ce5b75ac1a13
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: e891c1aeeec7415b023043526f2e4539f9c92767
Core tap last commit: 73 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit sandybridge
Clang: 10.0 build (parse error)
Git: 2.26.2 => /bin/git
Curl: 7.69.1 => /usr/bin/curl
Kernel: Linux 5.8.15-201.fc32.x86_64 x86_64 GNU/Linux
OS: Fedora release 32 (Thirty Two) (ThirtyTwo)
Host glibc: 2.31
/usr/bin/gcc: 10.2.1
/usr/bin/ruby: 2.7.2
glibc: N/A
gcc: 5.5.0_7
xorg: N/A

$ brew doctor           
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  AnsiGL

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  AnsiGL
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libice instead of deprecated linuxbrew/xorg/libice
Warning: Use libsm instead of deprecated linuxbrew/xorg/libsm
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxfixes instead of deprecated linuxbrew/xorg/libxfixes
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
</pre>

**Comment by ferdnyc** [comment]
I searched for previous reports, but wasn't able to find anything that would make this a duplicate. I did find closed issue #6348 which I suspect _is_ probably related to this one.

**Comment by jonchang** [comment]
Can you open a pull request to fix this? The relevant code is in `dev-cmd/diy.rb`. Linux is usually installed on a case-sensitive filesystem but macOS is usually case-insensitive.

**Comment by ferdnyc** [comment]
> Linux is usually installed on a case-sensitive filesystem but macOS is usually case-insensitive.

Huh! I wasn't aware of that! I'll take a look, sure, though my Ruby skills are... well, calling them "skills" is unfair to people with actual skill.

**Comment by ferdnyc** [comment]
@jonchang (Can I assume, from the fact that you pointed me at `diy.rb`, that the correct fix would be for `brew diy` to _also_ lowercase names when it creates paths in `Cellar/`?)

**Comment by jonchang** [comment]
Yeah, that's what I was thinking. It should be a straightforward fix with little impact on anyone not using `brew diy`.

**Comment by ferdnyc** [comment]
@MikeMcQuaid 

I guess I shouldn't submit a PR for ferdnyc/brew@3a2b92c48 then?

**Comment by MikeMcQuaid** [comment]
@ferdnyc Can you see if https://github.com/Homebrew/brew/pull/9029 works for you? If not (and your PR does): feel free to submit 👍🏻
