### ISSUE TITLE
brew list -l produces short output for casks, doesn't print totals as claimed in help

### ISSUE THREAD

**Issue by rptb1** [Homebrew/brew#9033]
# Bug report

- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Obtaining long form output of all installed packages and casks.

## What happened (include command output)

`brew -l`

<details>
  <summary>Command output</summary>
  <pre>
rb@Silverbird$ brew list -l
total 0
drwxr-xr-x  3 rb  staff  96 Oct 17 19:17 adns
drwxr-xr-x  3 rb  staff  96 Oct 17 19:17 ansible
...
drwxr-xr-x  3 rb  staff  96 Nov  2 15:27 xz
drwxr-xr-x  3 rb  staff  96 Nov  2 15:29 youtube-dl
drwxr-xr-x  3 rb  staff  96 Oct 10 17:07 zstd
adium                      flash-npapi                qlvideo
adobe-acrobat-reader       flickr-uploadr             resilio-sync
...
drawio                     omnidisksweeper            vlc
emacs                      perforce                   xquartz
  </pre>
</details>

## What you expected to happen

1. `brew help list` says “If the output is to a terminal, a total sum for all the file sizes is printed before the long listing.”  There wasn't one.

2. Casks are printed in an inconsistent short format. I can see that `brew cask help list` shows no “long format” for casks, so I can see how this might have happened during the recent changes to merge casks into formulae.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew -l`

## Output of `brew config` and `brew doctor` commands

(Note, `brew doctor` says there are updated command line tools, even if I update them. Maybe it assumes I'm on latest mac OS?)

<pre>
rb@Silverbird$ brew config
HOMEBREW_VERSION: 2.5.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c822206a05cd7fffe526b8e0fa2f45365be72a5
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2893221039bc9ecc05c4828c1c50f34ae5f38a96
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: emacsclient --alternate-editor='bbedit -w'
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 11.0 build 1100
Git: 2.21.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 15
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11
rb@Silverbird$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
</pre>

**Comment by Akylzhan** [comment]
Options --cask and -l are mutually exclusive.
So if you want only formulae, you should specify `--formulae`

**Comment by rptb1** [comment]
> Options `--cask` and `-l` are mutually exclusive. This is why you got short output for casks
> So if you want only formulae, you should specify `--formulae`

Thanks, but I didn't specify `--cask`.  This is a report about the default output with just `-l`.
