### ISSUE TITLE
`brew link` doesn't work after running `brew diy`

### ISSUE THREAD

**Issue by JLP04** [Homebrew/brew#9036]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ✔️] ran `brew update` and can still reproduce the problem?
- [✔️ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [✔️ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to run `brew link` on a formula created with `brew diy` after installing the formula to the location that `brew diy` gave. 

## What happened (include command output)

I ran `brew diy` and it outputted `--prefix=/usr/local/Cellar/libudfread/1.1.1`. I then ran `brew link libudfread` and got the following. 

<details>
  <summary>Command output</summary>
  <pre>

`Error: No available formula with the name "libudfread"`

  </pre>
</details>

## What you expected to happen

I expected it to link the formula. 

## Step-by-step reproduction instructions (by running `brew` commands)

`brew diy`
`brew link`

## Output of `brew config` and `brew doctor` commands

<pre>
`brew config`: 
`HOMEBREW_VERSION: 2.5.8-56-g18c638d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 18c638de30b20b037914023d92d693dd5608962c
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a642cfcc78f9fbb0c74905b013b225a59532f1be
Core tap last commit: 11 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--colorpickerdir=/Library/ColorPickers", "--prefpanedir=/Library/PreferencePanes", "--qlplugindir=/Library/QuickLook", "--screen_saverdir=/Library/Screen Savers", "--dictionarydir=/Library/Dictionaries", "--fontdir=/Library/Fonts", "--input_methoddir=/Library/Input Methods", "--internet_plugindir=/Library/Internet Plug-Ins", "--audio_unit_plugindir=/Library/Audio/Plug-Ins/Components", "--vst_plugindir=/Library/Audio/Plug-Ins/VST", "--vst3_plugindir=/Library/Audio/Plug-Ins/VST3"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.wpb6e8bkbi/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15.0.1, 13.0.2, 12, 1.8.0_272, 1.8.0_221
macOS: 10.15.7-x86_64
CLT: 1103.0.32.62
Xcode: 12.1
XQuartz: 2.7.11 => /opt/X11`

`brew doctor`:
`Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  sudokut
  tfdocgen
  plib
  aplus
  tilp
  libticables
  lziprecover
  clamtk
  clamtk
  libticonv
  libtifiles
  gfm
  libudfread
  libudfread
  libticalcs
  OpenGL
  xdg-utils

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/pybind11-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /opt/perl5/perls/perl-5.32.0/bin/ppkg-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  sudokut
  speedtest
  cmake
  perl
  aplus
  clamtk
  docker-compose
  libudfread
  python@3.9
  berkeley-db`
</pre>

**Comment by MikeMcQuaid** [comment]
Please paste the output of `brew link libudfread --debug`, thanks!

**Comment by JLP04** [comment]
`Error: No such keg: /usr/local/Cellar/udfread
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:85:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:85:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:209:in `resolve_keg'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:149:in `block in to_kegs'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:148:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:148:in `to_kegs'
/usr/local/Homebrew/Library/Homebrew/cmd/link.rb:42:in `link'
/usr/local/Homebrew/Library/Homebrew/brew.rb:120:in `<main>'`

**Comment by gromgit** [comment]
Did you name your formula `udfread`? Because that's what Homebrew derives the various paths from.

**Comment by porteusconf** [comment]
Just to clarify, some change between 2.5.7-36-gac8cc16 and 2.5.8-62 seems to break linking kegs without formulae. The OP had an issue due to name mismatch, but all the actual issues were reproduced on 2 separate 10.14 macos laptops that are otherwise a-ok.

That is, after recent brew update,  `brew link` started failing for me, but *not* because of wrong name like udvread (above). I see two modes of failure: (1.) cannot unlink then relink existing diy links, and (2.) cannot create links for new diy formula in most cases, even with formula name correctly matching name of folder in `/usr/local/Cellar`. And `brew doctor` is warning incorrectly about "deleted formulae" that are not formula at all, but diy links.

Below I details the steps I can use to reproduce issues on macos 10.14.

(Symtom 1.) Previously linked diys cannot be unlinked then re-linked after brew update to 2.5.8-62-g084f2e7
```
bash-5.0$ brew link docopts
Linking /usr/local/Cellar/docopts/0.6.3... 1 symlinks created
bash-5.0$ brew config
HOMEBREW_VERSION: 2.5.7-36-gac8cc16
ORIGIN: https://github.com/Homebrew/brew
HEAD: ac8cc16b9e7a7e8da9d1a180ff549a28dd96b64a
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: da7c16e4a10a88492284cd08b025d73d029c83cb
Core tap last commit: 4 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 10.0 build 1001
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.54.0 => curl
Java: 1.8.0_242
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
bash-5.0$ brew unlink docopts && brew link docopts
Unlinking /usr/local/Cellar/docopts/0.6.3... 1 symlinks removed
Linking /usr/local/Cellar/docopts/0.6.3... 1 symlinks created. ### NO PROBLEM with 2.5.7-36-gac8cc16 
bash-5.0$ brew update
Updated Homebrew from ac8cc16b9 to 084f2e75e.
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/services).
==> New Formulae
cfn-flip            k3sup               phive               vulture
fizz                ox                  tree-sitter
...
==> Deleted Casks
aspera-connect
bash-5.0$ brew unlink docopts && brew link docopts
Unlinking /usr/local/Cellar/docopts/0.6.3... 1 symlinks removed
Error: No available formula with the name "docopts"    ### NEW PROBLEM AFTER  `brew update` to 2.5.8-62 
bash-5.0$ brew config
HOMEBREW_VERSION: 2.5.8-62-g084f2e7
```

Also after update, `brew doctor` issues incorrect warnings for "deleted formula": what the doctor now says are deleted formulae,  are, in reality  almost all my own diy-names, such as docopts 
```shell
$ brew doctor
Warning: Some installed formulae were deleted!  #  better word(s) than "deleted": "retired" or "no longer available"
You should find replacements for the following formulae:
docopts
$ docopts --version
docopts v0.6.3-rc2 commit 651ff2c built at 2020-04-05T05:13:14Z
$ brew link docopts
Warning: Already linked: /usr/local/Cellar/docopts/0.6.3
To relink:
  brew unlink docopts && brew link docopts
$ brew unlink docopts && brew link docopts
Unlinking /usr/local/Cellar/docopts/0.6.3... 1 symlinks removed
Error: No available formula with the name "docopts" 
```

(2.) Newly created diy software cannot be linked unless folder in /usr/local/Cellar is same name as existing formula.
At least as of today,2020-Nov-03, `brew link` usually fails with any new diy programs. For example, below`brew link` fails for diy-name hellognu , but `brew link` works  if I use diy-name `hello`, which is also the name of a formula that is *not* installed.
``` 
$ brew diy --name hellognu --version=2.10
$ cd /tmp && wget https://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
Error: Couldn't determine build system. You can manually put files into /usr/local/Cellar/hellognu/2.10 
$ mkdir  /usr/local/Cellar/hellognu/
$ cd /usr/local/Cellar/hellognu/
$ tar zxf  /tmp/hello-2.10.tar.gz
$ mv hello-2.10.  2.10
$ cd 2.10
$ pwd
/usr/local/Cellar/hellognu/2.10
$ ./configure  --prefix="/usr/local/Cellar/hellognu/2.10"  && make && make install
$ /usr/local/Cellar/hellognu/2.10/bin/hello --version 
hello (GNU Hello) 2.10
$ $ brew link gnuhello
Error: No such keg: /usr/local/Cellar/gnuhello
```
But below `brew link hello` works if I use create Cellar/hello which is name of existing formula `hello` (but `brew install hello` was never done.
```
$ which hello # not installed
$ brew diy --name="hello" --version=2.10 
--prefix=/usr/local/Cellar/hello/2.10
$ mkdir  /usr/local/Cellar/hello/
$ cd /usr/local/Cellar/hello/
$ tar zxf  /tmp/hello-2.10.tar.gz
$ mv hello-2.10.  2.10
$ cd 2.10
$ pwd
/usr/local/Cellar/hello/2.10
$ ./configure  --prefix="/usr/local/Cellar/hello/2.10"  && make && make install
$ /usr/local/Cellar/hello/2.10/bin/hello --version 
hello (GNU Hello) 2.10
$ brew link hello
$ brew link hello
Linking /usr/local/Cellar/hello/2.10... 168 symlinks created
```

**Comment by porteusconf** [comment]
I manually applied Mike's commit to link.rb to fix $9036 at [https://github.com/MikeMcQuaid/brew/commit/1f971ba2a0575523300df2f4e63c03769ed3ad2a](https://github.com/MikeMcQuaid/brew/commit/1f971ba2a0575523300df2f4e63c03769ed3ad2a)

And it worked for me! That is, using his  /usr/local/Homebrew/Library/Homebrew/cmd/link.rb I think it fixed all the [issues I reported](https://github.com/Homebrew/brew/issues/9036#issuecomment-721629232)
