### ISSUE TITLE
[Homebrew Cask] Disable Accessibility Access override for OSX 10.12

### ISSUE THREAD

**Issue by adidalal** [Homebrew/brew#905]
`TCC.db` is (rightfully) protected by SIP in Sierra.

We should prevent [`enable_accessibility_access`](https://github.com/Homebrew/brew/blob/9c09f0573020e253e979af44d623ce049a4a2bd6/Library/Homebrew/cask/lib/hbc/installer.rb#L225) ` if MacOS.release >= :sierra` (throw up a caveat instead?)

**Comment by vitorgalvao** [comment]
Closing in favour of the PR at https://github.com/Homebrew/brew/pull/1029.
