### ISSUE TITLE
Stop update taps

### ISSUE THREAD

**Issue by vitahlin** [Homebrew/brew#9062]
# Feature suggestion

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# A detailed description of the proposed feature

I found that the latest homebrew is not support install specified version with `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/<COMMIT-HASH>/Formula/<Software>.rb
`.

 I deciced to use `brew extract`, I forked homebrew-core in Github then:
```bash
$ brew extract --version 5.6.2 gradle vitahlin/core
$ brew install gradle@5.6.2
```

I am glad that the installation was successful, but how to avoid update `vitahlin/core` repository when `brew update` is executed？I do not want to untapped it because I may use it again in the future.

# The motivation for the feature 

# How the feature would be relevant to at least 90% of Homebrew users

# What alternatives to the feature have been considered

**Comment by MikeMcQuaid** [comment]
> I am glad that the installation was successful, but how to avoid update `vitahlin/core` repository when `brew update` is executed

You can't.

Please always fill out the issue template.

**Comment by vitahlin** [comment]
Thanks for your reply
