### ISSUE TITLE
OS::Mac::CLT.latest_clang_version returns unreleased version for macOS 10.15

### ISSUE THREAD

**Issue by dmolesUC** [Homebrew/brew#9073]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run `brew doctor` (hadn't run it in a while).

## What happened (include command output)

1. `brew doctor` returned the following warning:

    ```text
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry or file an issue; just ignore this. Thanks!

    Warning: A newer Command Line Tools release is available.
    Update them from Software Update in System Preferences or run:
      softwareupdate --all --install --force

    If that doesn't show you an update run:
      sudo rm -rf /Library/Developer/CommandLineTools
      sudo xcode-select --install

    Alternatively, manually download them from:
      https://developer.apple.com/download/more/.
    ```

2. `softwareupdate --all --install --force` output the following:

    ```text
    Software Update Tool

    Finding available software
    No new software available.
    ```

3. After `sudo rm -rf /Library/Developer/CommandLineTools`, `sudo xcode-select --install` failed (in the GUI) with the message:

    **can’t install the software because it is not currently available from the software update server**

4. Visiting https://developer.apple.com/download/more/, I found that in fact there was no newer general availability release of the XCode command line tools:

    <img width="729" alt="Screen Shot 2020-11-06 at 10 57 40 AM" src="https://user-images.githubusercontent.com/10374934/98406016-13e9d300-2022-11eb-90e4-19f84e72bb19.png">

    Note that XCode 12 is the latest general availability release.

### Workaround & Notes

I installed "Command Line tools for Xcode 12.1 GM seed", after which `brew config` showed `CLT: 12.1.0.0.1.1602137645`. This seems to have silenced the warning from `brew doctor`.

I dug into the code a bit and found [`OS::Mac::CLT.outdated?`](https://github.com/Homebrew/brew/blob/2.5.8/Library/Homebrew/os/mac/xcode.rb#L298-L303), which calls [`OS::Mac::CLT.latest_clang_version`](https://github.com/Homebrew/brew/blob/2.5.8/Library/Homebrew/os/mac/xcode.rb#L263-L276). What seemed odd was that the `clang` version didn't apparently change with the "GM seed" install: `brew config` reported `Clang: 12.0 build 1200` both before and after.

However, I ran `clang --version` (which is what [`OS::Mac::CLT.detect_clang_version`](https://github.com/Homebrew/brew/blob/2.5.8/Library/Homebrew/os/mac/xcode.rb#L305-L308) does) and got `Apple clang version 12.0.0 (clang-1200.0.32.21)`, which is the version called for in `latest_clang_version`.

Unfortunately, `brew config` doesn't report the Clang version at any finer grain than `12.0 build 1200`, so I'm not sure what the minor version was when I was seeing the warning, but presumably it was lower.

## What you expected to happen

- `brew doctor` only to warn about newer command line tools when there's a newer GA release
- `brew config` to report the clang version at the same granularity used by `OS::Mac::CLT.latest_clang_version`

## Step-by-step reproduction instructions (by running `brew` commands)

- On a Mac running macOS Catalina 10.15.7, with XCode 12:
  - upgrade to XCode 12.1 (note, did this some time ago, probably whenever 12.1 was released)
  - run `brew doctor`

### `brew config`

```txt
HOMEBREW_VERSION: 2.5.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c822206a05cd7fffe526b8e0fa2f45365be72a5
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 61cc0f35b77b0d83483e56d4702270a7a65781d7
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.7, 1.8.0_265
macOS: 10.15.7-x86_64
CLT: 12.0.26.2
Xcode: 12.1
```

### `brew doctor`

(see above)

**Comment by jonchang** [comment]
> Please note that these warnings are just used to help the Homebrew maintainers with debugging if you file an issue. If everything you use Homebrew for is working fine: please don't worry or file an issue; just ignore this. Thanks!

**Comment by dmolesUC** [comment]
Should I file a separate issue about the `brew config` output for Clang not including the minor version?

**Comment by MikeMcQuaid** [comment]
@dmolesUC No, it doesn't matter. If you would like to submit a PR: we can review that.
