### ISSUE TITLE
Please update LAMMPS Homebrew Formula wrt 29 Oct'20 release

### ISSUE THREAD

**Issue by prameth** [Homebrew/brew#9077]
# Feature suggestion

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# A detailed description of the proposed feature

Please change the respective Homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lammps.rb) to go with `lammps`'s newest [stable release](https://github.com/lammps/lammps/releases/tag/stable_29Oct2020)

# The motivation for the feature

With respect to the commits made by contributors of `lammps`

> This stable release corresponds to a significantly larger number of changes than between previous stable releases. There have been over 4000 commits added since the last stable release, while the two previous stable releases have been made after fewer than 2000 commits.

# How the feature would be relevant to at least 90% of Homebrew users
> This stable release corresponds to a significantly larger number of changes than between previous stable releases. There have been over 4000 commits added since the last stable release, while the two previous stable releases have been made after fewer than 2000 commits.

Also please check out the valuable changes made from current([3 March 2020](https://github.com/lammps/lammps/releases/tag/stable_3Mar2020)) release to [29 Oct 2020](https://github.com/lammps/lammps/releases/tag/stable_29Oct2020)

**Comment by Rylan12** [comment]
Please open a PR to update the formula. Check out https://docs.brew.sh/Updating-Software-in-Homebrew and the `brew bump-formula-pr` command.
