### ISSUE TITLE
Why graphviz dependent on python?

### ISSUE THREAD

**Issue by rudaoshi** [Homebrew/brew#9098]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [* ] ran `brew update` and can still reproduce the problem?
- [* ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [* ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew install graphviz 

## What happened (include command output)

It began to download python 3.9  and a lot of other packages, much more than the deps in the graphviz description file. 

<details>
  <summary>Command output</summary>
  <pre>

  Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.0_1.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/77254b7bca66680c41db33e78d40bef288924fb142deb73648ce67255c6dda83

  </pre>
</details>

## What you expected to happen

Just install the graphviz binary 

## Step-by-step reproduction instructions (by running `brew` commands)

brew install graphviz 

## Output of `brew config` and `brew doctor` commands

<pre>
➜  ~ brew config
HOMEBREW_VERSION: 2.5.9
ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HEAD: 2ed5d80ff2f8025823de9b9faacfca27fa006c80
Last commit: 16 hours ago
Core tap ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
Core tap HEAD: 5b7fcd34364adab5d13004ce793a9cabbbb3908a
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
http_proxy: http://127.0.0.1:1087
https_proxy: http://127.0.0.1:1087
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_192
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
</pre>

**Comment by jonchang** [comment]
Please use our discussion forum to ask questions.

> Get help in GitHub Discussions
> Have a question? Not sure if your issue affects everyone reproducibly? The quickest way to get help is on Homebrew's GitHub Discussions!

https://github.com/homebrew/discussions/discussions
