### ISSUE TITLE
Improve type checking documentation

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#9099]
Extracted from https://github.com/Homebrew/brew/issues/8991

- [x] Improve the documentation in https://docs.brew.sh/Typechecking (https://github.com/Homebrew/brew/pull/9129)
- [x] Improve tooling/CI output (e.g. `brew typecheck`) to reference documentation (and vice-versa)
- [ ] Consider/investigate improving naming here with some of our own aliases to be `Type::Signature`

**Comment by vidusheeamoli** [comment]
I'm on it!

**Comment by reitermarkus** [comment]
> Consider/investigate improving naming here with some of our own aliases to be `Type::Signature`

I don't think this will improve readability/understandability when people read Sorbet documentation which only ever mentions `T`, `T::Sig` and other methods on the `T` module but we choose to use a differing name.

**Comment by MikeMcQuaid** [comment]
> I don't think this will improve readability/understandability when people read Sorbet documentation which only ever mentions `T`, `T::Sig` and other methods on the `T` module but we choose to use a differing name.

It'll improve readability for people who read our code but haven't read Sorbet documentation. It is not a realistic expectation that this will happen for everyone who reads Homebrew's code. We should aim to improve the readability of Homebrew's code to newcomers.
