### ISSUE TITLE
Bash - shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

### ISSUE THREAD

**Issue by mprimi** [Homebrew/brew#9118]
# Bug report

- ✅  ran `brew update` and can still reproduce the problem?
- ✅  ran `brew doctor`, fixed all issues and can still reproduce the problem?
- ~ ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installed `bash` via Homebrew.
Seemed to work fine in my terminal, but in certain cases, I would bump into the error:

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```
**This is NOT the typical "you are running from a directory that doesn't exist or was recreated" (i.e. the common solution to this issue)**. Proof below.

I think this has to do with the shell environment during `bash` installation via Homebrew.

## What happened (include command output)

After installation, Bash works normally in a terminal, but fails in other circumstances, with error:
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

**Even if explicitly launched in a directory that exists! (such as `/tmp`)**

## What you expected to happen

`/usr/local/bin/bash` to work just like `/bin/bash`( IF launched from a directory that does exist).

## Step-by-step reproduction instructions (by running `brew` commands)

1. MacOS 10.15.7 default shell `zsh`. (I think this is the crux of the problem -- the fact that i installed within `zsh`)
2. `brew install bash`
3. Added `/usr/local/bin/bash` to `/etc/shells`
4. `chsh -s /usr/local/bin/bash`

At this point, any new terminal window is now using Homebrew `bash`. **Everything is working fine.**

However i was getting some errors from Java tests (that invoke `bash`).

Here's the minimal repro:

```
package mypackage;

import java.io.File;
import java.io.IOException;

public class BashTest {

    public static void main(String[] args) throws IOException, InterruptedException {
        System.out.println(new ProcessBuilder().directory(new File("/tmp")).command("bash", "-c", "echo").inheritIO().start().waitFor());
    }
}
```

Important to notice:
 * If i try to run from a non-existent directory, it fails, as expected.
 * If I run this with `/bin/bash` it works (meaning, there's nothing wrong with the Java environment)
 * If I run this with `/usr/local/bin/bash` (same as just `bash`) it fails!

So it must be due to how `/usr/local/bin/bash` sets the default directory.

### Resolution
The following did the trick: `brew reinstall bash`

I cannot reproduce the behavior above, even if everything is identical.
This leads me to believe something was off when the installation happened via `zsh`

## Output of `brew config` and `brew doctor` commands

The only warning I got from `doctor` is:
```
Warning: "config" scripts exist outside your system or Homebrew directories.
```
It's warning about some configs in `/opt` (from MacPorts). After removing all of `/opt/`, this didn't make a difference.

I did not run `brew config` before solving the problem, sorry.

## Final remarks

I know this is obscure and a corner case. I don't even know if it's worth chasing this down since it's such a corner case.

However, I still think it's worth reporting.
I hope this is brought to the attention of Homebrew `bash` maintainers who may be willing to take a deeper look.
I also hope this help other people that bump into the same.

All Google results for this error message are due to the user-problem "running in a directory that doesn't exist".
And it's not the case here, or at least not directly.

**Comment by MikeMcQuaid** [comment]
This doesn't seem Homebrew related, sorry. We don't provide support for the software we distribute to this extent.

**Comment by mprimi** [comment]
@MikeMcQuaid that's alright, I expected as much. 

I still hope this helps someone that bumps into the same problem.

**Comment by gromgit** [comment]
> I think this has to do with the shell environment during bash installation via Homebrew.
> ...
> The following did the trick: `brew reinstall bash`

In that case, it's more likely that you were bit by #64480, and #64549 was the fix. All of that happened just a few days ago.

**Comment by mprimi** [comment]
Ah! Nice! Thank you @gromgit
