### ISSUE TITLE
Your CLT does not support macOS 11.0

### ISSUE THREAD

**Issue by TheRav3n** [Homebrew/brew#9127]
Homebrew 2.5.10
Homebrew/homebrew-core (git revision c650d; last commit 2020-11-13)
Homebrew/homebrew-cask (git revision 8cad3; last commit 2020-11-13)

`brew update`

`brew upgrade mongodb-community`

Logs:
```
==> Downloading https://fastdl.mongodb.org/tools/db/mongodb-database-tools-macos
######################################################################## 100.0%
==> Downloading https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.4.1.tgz
######################################################################## 100.0%
==> Installing dependencies for mongodb/brew/mongodb-community: mongodb-database-tools
==> Installing mongodb/brew/mongodb-community dependency: mongodb-database-
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Error: An exception occurred within a child process:
```

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
