### ISSUE TITLE
Brew options doesn't do anything

### ISSUE THREAD

**Issue by grosch** [Homebrew/brew#9131]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

After upgrading to Big Sur, I'm trying to reinstall php.  In looking for the options available I found any 'brew options' command returns no output.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  
% brew options --all postgresql
%
  </pre>
</details>

## What you expected to happen

See the options available to build that package.

## Step-by-step reproduction instructions (by running `brew` commands)

Run any brew options command.

## Output of `brew config` and `brew doctor` commands

<pre>
% brew config
HOMEBREW_VERSION: 2.5.10-14-g8561fbf
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8561fbf5c8160694e8bc9a4765817b24f623fffd
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f5c2f027beb434a396ffd21189d4e51753df617f
Core tap last commit: 29 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.vPYWmuZ0Fk/org.macosforge.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit ivybridge
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.131.11, 1.8.0_131
macOS: 11.0.1-x86_64
CLT: N/A
Xcode: 12.2
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or any other official channels. You are responsible for
resolving any issues you experience while you are running this
released but not yet supported version.

</pre>

**Comment by gromgit** [comment]
Not a bug. `brew options` only shows options when there are options to show, and all core formulae had their options removed a long time ago, with one exception:
```
--HEAD
	Install HEAD version
```
That only appears with formulae that have a `head` stanza.

**Comment by grosch** [comment]
Maybe the command should go away then :)

**Comment by gromgit** [comment]
Only core formulae have no options. Formulae in third-party taps are free to use options as they see fit, and `brew options` outputs as expected there.
