### ISSUE TITLE
no reliance on ... xcode?

### ISSUE THREAD

**Issue by xenoterracide** [Homebrew/brew#9145]
Honestly I have no idea why brew needs xcode? seems like brew could replace the need for xcode by supplying more or less what it supplies, replacing it with gcc and the like? I don't really know what it supplies to be honest, or why this choice was made. I would love to know though.

**Comment by jonchang** [comment]
Please always fill out the issue template. Our issue tracker is not for general support requests or questions.

>  Get help in GitHub Discussions
> Have a question? Not sure if your issue affects everyone reproducibly? The quickest way to get help is on Homebrew's GitHub Discussions!
> https://github.com/Homebrew/discussions/discussions
