### ISSUE TITLE
The clang compiler does not support '-march=nehalem'

### ISSUE THREAD

**Issue by markwu** [Homebrew/brew#9167]
# Bug report

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I want to build `macvim` with `homebrew` under `macOS Catalina 10.15.7` with `Xcode 12.2` and `CLT 12.2` on `Late 2013 Macbook Pro Retina` machine. I use the following command:

`brew install markwu/personal/macvim`

(Current homebrew-core/macvim.rb need some patch to make it compiled with xcode 12.2, so, I made this one for tesing this issue)

## What happened (include command output)

It build failed with errors. It seems clang does not support  '-march=nehalem' anymore.

<details>
  <summary>Command output</summary>
  <pre>

brew reinstall macvim
Warning: Treating macvim as a formula. For the cask, use homebrew/cask/macvim
==> Cloning https://github.com/macvim-dev/macvim.git
Updating /Users/markwu/Library/Caches/Homebrew/macvim--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 0a1cf2e22 Merge remote-tracking branch 'vim/master'
==> Reinstalling markwu/personal/macvim
==> Patching
==> ./configure --with-features=huge --enable-multibyte --enable-perlinterp --enable-rubyinterp --enable-tclinterp --enable-terminal --with-tlib=ncurses --with-compiledby=Homebrew --with-loca
==> make
Last 15 lines from /Users/markwu/Library/Logs/Homebrew/macvim/02.make:
ProcessPCH /tmp/macvim-20201117-43642-41h37l/src/MacVim/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/4270105491631976141/AppKit.h.gch /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'PSMTabBarControlFramework' from project 'PSMTabBarControl')
    cd /tmp/macvim-20201117-43642-41h37l/src/MacVim/PSMTabBarControl
    clang -x objective-c-header -target arm64-apple-macos10.15 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DDISABLE_SPARKLE\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -iquote /tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/PSMTabBarControl-generated-files.hmap -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/PSMTabBarControl-own-target-headers.hmap -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/PSMTabBarControl-all-target-headers.hmap -iquote /tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/PSMTabBarControl-project-headers.hmap -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/Release/include -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/DerivedSources-normal/arm64 -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/DerivedSources/arm64 -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/DerivedSources -F/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/Release -c /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h -MD -MT dependencies -MF /tmp/macvim-20201117-43642-41h37l/src/MacVim/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/4270105491631976141/AppKit.h.d -iquote /tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/PSMTabBarControl-generated-files.hmap -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/PSMTabBarControl-own-target-headers.hmap -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/PSMTabBarControl-all-target-headers.hmap -iquote /tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/PSMTabBarControl-project-headers.hmap -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/Release/include -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/DerivedSources-normal/arm64 -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/DerivedSources/arm64 -I/tmp/macvim-20201117-43642-41h37l/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/DerivedSources -o /tmp/macvim-20201117-43642-41h37l/src/MacVim/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/4270105491631976141/AppKit.h.gch --serialize-diagnostics /tmp/macvim-20201117-43642-41h37l/src/MacVim/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/4270105491631976141/AppKit.h.dia
clang: error: the clang compiler does not support '-march=nehalem'

warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'MacVim' from project 'MacVim')
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'QuickLookStephen' from project 'QuickLookStephen')
** BUILD FAILED **

The following build commands failed:
	ProcessPCH /tmp/macvim-20201117-43642-41h37l/src/MacVim/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/4270105491631976141/AppKit.h.gch /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/markwu/homebrew-personal/issues

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

  </pre>
</details>

## What you expected to happen

Build without errors.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew install markwu/personal/macvim`

## Output of `brew config` and `brew doctor` commands

<pre>
$brew config
HOMEBREW_VERSION: 2.5.11-20-gaf41431-dirty
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: af4143150da32097f751b1538a5b6f6958bb2175
Last commit: 46 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 723b3d0d68fddbc3b4d468db8c11e3bee6f8469a
Core tap last commit: 47 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.MUWa2Waego/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2
macOS: 10.15.7-x86_64
CLT: 12.2.0.0.1.1604628099
Xcode: 12.2
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  rclone

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/markwu/.phpbrew/php/php-7.4.12/bin/php-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.8/greenlet/greenlet.h
  /usr/local/include/python3.9/greenlet/greenlet.h

Warning: You have uncommitted modifications to Homebrew/brew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew && git stash && git clean -d -f

Uncommitted files:
   M Library/Homebrew/hardware.rb
</pre>

### Reference and Solutions

I finally found someone has the same problem with me https://github.com/Homebrew/brew/issues/7857#issuecomment-655536261.

After remove `-march=nehalem` from homebrew source code, everything works well. I report the issue there and @claui ask me to file a new seperate issue and told me it might relate to this change https://github.com/Homebrew/brew/commit/374c734d9b3f8e6fa20810ad4d049ca2711e2156

That why this issue here.

I also report the issue in macvim https://github.com/macvim-dev/macvim/issues/1115

**Comment by jonchang** [comment]
I can't reproduce this. Do you have a more minimal example?

```console
% clang --version
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

% echo "int main(){return 0;}" | clang -xc - -march=undefined    
error: unknown target CPU 'undefined'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge,
      core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, knl, knm, k8, athlon64,
      athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64

% echo "int main(){return 0;}" | clang -xc - -march=nehalem      

% echo $?
0
```

**Comment by claui** [comment]
(@markwu Don’t worry about the issue being closed, it’s our way to track pending work.
The issue can be reopened if you provide a reproducible example.)

**Comment by claui** [comment]
Note: #9160 is an unrelated PR but will affect CPU family logic for M1.

**Comment by markwu** [comment]
@jonchang I can't reproduce your example step by step either.  Weird.

I also try to see the clang options from the above error messages and did not see any `-march=nehalem` either.

So, I try to copy the clang options from the about error messages and add `-march=nehalem` in the end of options, and see what's going on.

**test.c**
```
int main(void) {
    return 0;
}
```

**clang command**
```
clang -x objective-c-header -target arm64-apple-macos10.15 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DDISABLE_SPARKLE\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -march=nehalem test.c -o test
```

I just get 

**error messages**
```
clang: error: the clang compiler does not support '-march=nehalem'
```

I am not familiar with c/c++, not sure if this is what you want. I guess there might be some clang options conflicts, but have no idea the conflicts come from macvim side or homebrew side.

But, in xcode 11.x, It just works without any problems.

**Comment by markwu** [comment]
@jonchang  Okay, I try to remove most options, except `target`

```
clang -target arm64-apple-macos10.15 -march=nehalem test.c -o test
```

Maybe these two conflicts.

**Comment by jonchang** [comment]
You're trying to cross-compile targeting arm64, but there's no microarchitecture called nehalem for that target. The issue is with the build script or custom formula you're using, not with Homebrew.

**Comment by markwu** [comment]
@jonchang Thanks for your explanation! But, why the same formula works with `xcode 11.x` and failed after I upgrade to `xcode 12.2`. That's I don't understand.

**Comment by markwu** [comment]
reference: https://github.com/Homebrew/homebrew-core/pull/65100

**Comment by markwu** [comment]
Hi @jonchang 

I just check all homebrew compile logs, from `~/Library/Logs/Homebrew/macvim/01.configure.cc, it shows

```
superenv added:    -pipe -Os -march=nehalem -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -isystem/usr/local/include -isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/ruby/include
```

It seems the `-march=nehalem` is added by `brew` superenv, not macvim.

**Comment by markwu** [comment]
Okay, I think I found problem, there is another project under macvim, and it does not exclude arm arch. I'll do some test to see if it works.

Thanks!

**Comment by markwu** [comment]
@jonchang & @claui Thanks, the problem solved. It is the problem of macvim xcode project buildsettings. Atfer some patches, the problem solved.
