### ISSUE TITLE
brew link: add option to only link in $(brew --prefix)/opt

### ISSUE THREAD

**Issue by phil-blain** [Homebrew/brew#9171]
# Feature suggestion

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# A detailed description of the proposed feature

When using `brew link` to link DIY packages that are installed in the Cellar, if the link fails because it would overwrite already existing files from other formula, the files are symlinked into `$(brew --prefix)/opt`. **This is great! I don't want this to change.** However this is not documented (at least not somewhere I could find).

It would be even better if `brew link` would provided a flag to *only* link into `opt`, and not even try to link into `$(brew --prefix)`. This way, if you already know that the package you are linking has files that conflicts with other packages already linked, you can eg. `brew link --opt <formula>`  and not get any error.

# The motivation for the feature

Installing packages with conflicting files into `opt` only more seemlessly.

# How the feature would be relevant to at least 90% of Homebrew users

I don't know about 90%, since I don't think 90% of Homebrew users use `brew diy` and `brew link`. But, I think for those users that do, it would be useful.

# What alternatives to the feature have been considered

Ignoring the error :P

**Comment by reitermarkus** [comment]
What do you gain by only opt-linking a formula?

**Comment by MikeMcQuaid** [comment]
Passing on this, we are likely to deprecate `brew diy` in future.

**Comment by phil-blain** [comment]
I’m sad to hear that !! `brew diy` Is really useful for installing binary releases  into the homebrew prefix. 

Installing only in `opt` is nice because it’s a file system location that does not have the package version number, so it stays the same when I update the package.
