### ISSUE TITLE
How do I run the Homebrew installer under Rosetta 2?

### ISSUE THREAD

**Issue by 72L** [Homebrew/brew#9173]
# Bug report

- [ N/A ] ran `brew update` and can still reproduce the problem?
- [ N/A ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ N/A ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I am trying to install Homebrew.

## What happened (include command output)
I ran:
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

<details>
  <summary>Command output</summary>
  <pre>

Homebrew is not (yet) supported on ARM processors!
Rerun the Homebrew installer under Rosetta 2.
If you really know what you are doing and are prepared for a very broken experience you can use another installation option for installing on ARM:
  https://docs.brew.sh/Installation

  </pre>
</details>

## What you expected to happen

I expected it to install successfully, or give me more detailed instructions for this sentence: "Rerun the Homebrew installer under Rosetta 2."

## Step-by-step reproduction instructions (by running `brew` commands)

1. Use a new MacBook with Apple Silicon M1 chip.
2. Try to install homebrew

## Output of `brew config` and `brew doctor` commands

<pre>
N/A
</pre>

**Comment by Mootzy** [comment]
Trying to attempt the same

**Comment by andresavic** [comment]
https://docs.brew.sh/Installation

1.
`cd /opt
mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
sudo chown -R $(whoami) /opt/homebrew
`
2.
`sudo nano /etc/path`
Add this two paths
`/opt/homebrew/bin
/opt/homebrew/opt`

3.
Restarting terminal and `brew update`

I don't know if this is the right solution but it is working fine. I just have issues with specific formulas like "gpg"

**Comment by claui** [comment]
There’s a [PR in progress](https://github.com/Homebrew/brew/pull/9126/files#diff-e181586945bce9183b7c22ca539f9dd72d289287f6a763fe90667800614ddaf0R53) to explain exactly that in more detail.

From the PR (referring to installing a formula):

> To use it, you can choose between:
> 
> * running your Terminal from Rosetta 2
> * running `arch -x86_64 brew` instead of `brew`.

To install Homebrew itself, you can run `arch -x86_64 /bin/bash` instead of `/bin/bash`.
To configure Terminal to run under Rosetta 2, select Terminal.app in Finder, hit ⌘I, select _Open with Rosetta_, then restart your Terminal.

**Comment by medweb2020** [comment]
I tried to do the same but it's not working it opens a file for me in the terminal when I write the commands can you please help me I'm behind my projects and I need to get back to work asap. the m1 ship is holding all my work

**Comment by andresavic** [comment]
@medweb2020 This is the full command to install Homebrew under Rosetta 2
`arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

**Comment by claui** [comment]
> can you please help me I'm behind my projects and I need to get back to work asap. the m1 ship is holding all my work

@medweb2020 If you need support, please go to our Discourse and ask your questions there: https://discourse.brew.sh

I feel your pain. But GitHub issues are a space for reporting bugs and proposing features, and we absolutely need it to stay that way so we have a chance to do our work properly. I must insist that you please stop asking for support on GitHub issues.
