### ISSUE TITLE
`brew install --quiet` does not suppress warnings

### ISSUE THREAD

**Issue by jwalton** [Homebrew/brew#9179]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm trying to write an unattended install script to set up my mac - I want it to install all the brew formulae in a list, and not produce any output even if some of them are already installed.

## What happened (include command output)

If I run `brew install [already-installed-formula`], then brew produces a warning:

<details>
  <summary>brew install gh</summary>
  <pre>
19:36:19 [~] (5s) $ brew install gh
Warning: gh 1.2.1 is already installed and up-to-date
To reinstall 1.2.1, run `brew reinstall gh`
  </pre>
</details>

If I run `brew install -h`, it tells me:

```
-q, --quiet                      Suppress any warnings.
```

This is perfect - this is exactly what I want.  I want to suppress the warning.  In fact, for my use case, this is ideal, because if the forumla is already installed but is out of date, brew will print an error instead of a warning, so if I can just suppress the warnings, I'll get no output at all when I `brew install --quiet a b c d e...` when all of those are already installed, and I'll get errors for things that are out of date.  But... it doesn't work.  The warning still gets printed.  In fact, I get exactly the same output either way:

<details>
  <summary>brew install --quiet gh</summary>
  <pre>
19:36:19 [~] (5s) $ brew install gh
Warning: gh 1.2.1 is already installed and up-to-date
To reinstall 1.2.1, run `brew reinstall gh`
  </pre>
</details>

## What you expected to happen

`--quiet` should suppress warnings, like it says on the tin.

## Step-by-step reproduction instructions (by running `brew` commands)

```sh
brew install gh
brew install --quiet gh
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 07b3aa69f8dc5098437cf2562864558bae2d45aa
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ca417ec82143a1f405bacdb150a80cf7e1f3bc01
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.2.0.0.1.1604628099
Xcode: 12.2

$ brew doctor
Your system is ready to brew.
</pre>

**Comment by jwalton** [comment]
Thanks for the super fast turnaround @MikeMcQuaid !

**Comment by MikeMcQuaid** [comment]
You're very welcome @jwalton!
