### ISSUE TITLE
When 'brew install' need to do an update first, do the update in the 'verbose' mode, or add a progress bar, so I could know it's going well, especially when the update seems to take forever.

### ISSUE THREAD

**Issue by linxucc** [Homebrew/brew#9186]
# Feature suggestion

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# A detailed description of the proposed feature

When 'brew install something', and homebrew find itself needs an update first, update with '--verbose' as default. 

# The motivation for the feature

1. User experience, and less 'false alarms' questions/issues wasting you guy's time.
2. Less chance of potential damage by 'CTRL-C'.

If you search "brew update takes forever" (google will even auto-complete it for you) you'll see a whole lot of people are asking about the same questions on almost everywhere, but actually, there's no real problem in most cases, the update just runs well most time, and it just takes time, **the real problem is**, the user does not have a running prompt so that he/she knows that it's still running OK.

Currently, if you try to 'brew install something' but it needs an update first, the update will be done in silent mode. **The problem is**, sometimes this update could take a very long time, especially for ordinary users who don't install packages that often (very good chance that every time they try to install something, it will always need an update first), for this extended waiting period, they can't get any clue if the program is still running, but if there's an updating screen, he/she will know it's still running, and he/she will most probably wait.

I believe all these 'false alarms' questions have wasted many of you guy's time, and if the '--verbose' is default, I guess 90% of such question would not be asked. So when someone says the update takes forever, it may be some real problem there, you don't have to reply 'have you tried verbose?' to all such questions.

# How the feature would be relevant to at least 90% of Homebrew users

For most of the silent users, I believe more than 90%, homebrew is a tool that 'grab and go', that means you rarely use it, you use it once for a while, like say, 3 months or half a year or even longer, that's a cruel fact for tools like this, which means **it's always not up-to-date when you try to use it**.

So every time a normal user try to install something, it will at a very great chance stuck into this 'updating homebrew' prompt for a very long time, as described above, this is very confusing to users, "is it better to wait, or just CTRL-C?", "What if it's almost done?", "Bad internet connection"? 

For normal users, they don't install and update packages everyday, they are not terminal geeks, they install new things only when they need to, like, move to a new project, find themselves need something new, till then they run 'brew install something', and will most probably find it stuck at "updating homebrew" for a long time and experience what I have described. That's the actual use case for an ordinary user. These users do not actively speak in the 'community', they don't fire issue, they can't even describe the problem correctly, but they are there.

# What alternatives to the feature have been considered

1. It could show something like an increasing progress bar of characters (adding a '*' or '.' every few seconds), so that user knows the program is still running, when it's not in verbose more.
2. If you guys have a strong reason to make update silent as default, think about add some additional check on time, if it's out-dated for a extended period of time, say, 1 month or 3 months, verbose or progress bar as default, otherwise, silent, so you could know it runs fine in the very long run situation.

I myself prefer the verbose, I find myself feel very comfortable when I could see what's going on.

**Comment by MikeMcQuaid** [comment]
We already only display the "Updating Homebrew" if the update takes over a certain period of time. For people with fast computers/internet connections/small updates: this message is not shown. We can't somehow start the process silently and then make it verbose.

It is non-trivial to print a `.` every second but we'd consider accepting a pull request to add something similar or to run in verbose mode if Homebrew hasn't been run for e.g. a month.

**Comment by linxucc** [comment]
> We already only display the "Updating Homebrew" if the update takes over a certain period of time. For people with fast computers/internet connections/small updates: this message is not shown. We can't somehow start the process silently and then make it verbose.
> 
> It is non-trivial to print a `.` every second but we'd consider accepting a pull request to add something similar or to run in verbose mode if Homebrew hasn't been run for e.g. a month.

Thanks for your attention... Brew is a brilliant tool but almost every time I try to install something new I'll experience this situation, then I searched to see if it's a problem and I'm shocked to find that so many people are experiencing the same, questions been asked again and again. So I think it's good to show user interactively that the program is running fine when it takes a long time to update, so they can wait peacefully. If you actively play with brew you may never have this problem, but if you are just an ordinary user you have some good chance to wonder "why it's stuck at updating". Hope some improvement could be made.

**Comment by MikeMcQuaid** [comment]
> Hope some improvement could be made.

We welcome pull requests to make improvements.

**Comment by EricFromCanada** [comment]
I have a rudimentary implementation of animated dots in my [`update-spinner` branch](https://github.com/EricFromCanada/brew/commits/update-spinner). The main issue, though, is that `brew.sh`'s `update-preinstall-timer()` needs to be stopped before the output of `brew update-report` is printed to prevent both from printing characters at the same time. I have it saving its output to a variable by running it in a subshell, but that then causes it to run in non-interactive mode and so print all its output in a single column.
```
$ brew bundle dump
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask and homebrew/core).
==> Updated Formulae
Updated 11 formulae.
==> New Casks
tmnotifier
==> Updated Casks
banktivity
cisco-proximity
duet
family-tree-builder
hype
jamulus
kiwi-for-g-suite
komet
linphone
little-snitch
microsoft-edge
nordvpn-teams
screaming-frog-seo-spider
signal
smartgit
texmacs
windocd

```
