### ISSUE TITLE
`brew upgrade` fails with "coursier: Java 1.8+ is required for this software" although Java 7, 8, 9, 11, 14, and 15 are installed

### ISSUE THREAD

**Issue by jeffrey-aguilera** [Homebrew/brew#9194]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew upgrade` (after upgrading to macos BigSur)

## What happened (include command output)

Upgrade fails on coursier formula and its misdetection of installed JVMs.

<details>
  <summary>Command output</summary>
  <pre>

$ brew upgrade
==> Upgrading 1 outdated package:
coursier/formulas/coursier 2.0.6 -> 2.0.7
==> Upgrading coursier/formulas/coursier 2.0.6 -> 2.0.7 
coursier: Java 1.8+ is required for this software.
Install AdoptOpenJDK with Homebrew Cask:
  brew cask install adoptopenjdk
Error: coursier: An unsatisfied requirement failed this build.

$ brew cask install adoptopenjdk
Warning: Cask 'adoptopenjdk' is already installed.

To re-install adoptopenjdk, run:
  brew reinstall adoptopenjdk
  </pre>
</details>

The following JVMs are installed:
<pre>
    15 (x86_64) "AdoptOpenJDK" - "AdoptOpenJDK 15" /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home
    14.0.2 (x86_64) "Oracle Corporation" - "OpenJDK 14.0.2" /Library/Java/JavaVirtualMachines/openjdk-14.0.2.jdk/Contents/Home
    11.0.9 (x86_64) "UNDEFINED" - "OpenJDK 11.0.9" /usr/local/Cellar/openjdk@11/11.0.9/libexec/openjdk.jdk/Contents/Home
    9.0.4 (x86_64) "Oracle Corporation" - "Java SE 9.0.4" /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
    1.8.0_191 (x86_64) "Oracle Corporation" - "Java SE 8" /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home
    1.7.0_80 (x86_64) "Oracle Corporation" - "Java SE 7" /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
</pre>

JAVA_HOME references 11.0.9.

## What you expected to happen

`brew upgrade` to work without error.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew upgrade`

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.11-56-g1255557
ORIGIN: https://github.com/Homebrew/brew
HEAD: 125555752f13a579e693bdbbf51819741e4772d3
Last commit: 45 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 93ca3c41051b3ae2d5cda8152829b7fa69f5dbd6
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.LDcyboAKYs/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15, 14.0.2, 11.0.9, 9.0.4, 1.8.0_191, 1.7.0_80
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: 12.2
XQuartz: 2.7.11 => /opt/X11
</pre>

<pre>
$ brew dr
Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment]
Big Sur has broken the method we used for Java version detection. The `:java` requirement should be considered deprecated as a result (I will get around to marking it so ASAP).
