### ISSUE TITLE
Change version comparison behaviour for macOS version ≥ 11

### ISSUE THREAD

**Issue by soraros** [Homebrew/brew#9211]
# Feature suggestion

# A detailed description of the proposed feature

Change the behaviour of version comparison for macOS to reflect that a `XXX.a -> XXX.b` update is not a major update anymore in post Big Sur era.

In other words, for a version string `A.b.c` where `A >= 11` we should have `A.b.c <= A`.

# The motivation for the feature

Restore consistency for treatment regarding major macOS releases. 

# How the feature would be relevant to at least 90% of Homebrew users

See section motivation.

# What alternatives to the feature have been considered

Keep the current behaviour.

**Comment by MikeMcQuaid** [comment]
I don't understand what this means at all. Can you describe what Homebrew does now that you think should be different? This is very abstract as-is.

**Comment by soraros** [comment]
Consider the case where say 10.14 is the stable release, when the user is on 10.15, brew should report the newer version is not supported. However, it should not show the same message if the user is on 11.1 and the current stable release is 11.0 (for it is closer to 10.15.1 vs 10.15.2).

**Comment by MikeMcQuaid** [comment]
Yes, I see what you mean. If I hack the Homebrew internals to assume I'm on Big Sur 11.1 it (incorrectly) shows as a prerelease.
