### ISSUE TITLE
Loading dynamic libraries fail when Homebrew not installed in /usr/local on Apple Silicon

### ISSUE THREAD

**Issue by skra72** [Homebrew/brew#9214]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installed Homebrew in /opt/homebrew as suggest for ARM installations on Apple Silicon. Then installed some formula that put libraries into /opt/homebrew/lib.

To allow other applications to pick these libraries up, I created symlinks to these libraries in /usr/local/lib that point to the libraries installed in /opt/homebrew/lib.

## What happened (include command output)

Applications fail to use these libraries. dlopen fails with error the sandboxing does not allow to open libraries located in /opt/homebrew.

<details>
  <summary>dlopen error</summary>
  <pre>
  (dlopen(/usr/local/lib/libwhatever.dylib, 1): no suitable image found.  Did find: file system sandbox blocked open() of '/usr/local/lib/libwhatever.dylib')
  </pre>
</details>

Any attempt to load these libraries fails because of macOS security feature that prevents loading libraries outside the application sandbox.

## What you expected to happen

The Applications should be able to use libraries installed by Homebrew running on ARM.

I know that ARM still is not supported yet. But if Homebrew sticks to /opt/homebrew for ARM installations there should be a way to get installed libraries located in a way that the sandbox still allows applications to load them.

For me I fixed the problem by copying the required files manually in /usr/local/lib. But maybe there is a better way to get this working.
 
## Step-by-step reproduction instructions (by running `brew` commands)

1. Install Homebrew in /opt/homebrew
2. Install some library using `brew install <formula with lib whatever>`
3. Create symlinks from /usr/local/lib to installed library `ln -s /opt/homebrew/lib/libwhatever.dylib /usr/local/lib/libwhatever.lib`
4. Run an application that wants to use /usr/local/lib/libwhatever.dylib

**Comment by MikeMcQuaid** [comment]
> To allow other applications to pick these libraries up, I created symlinks to these libraries in /usr/local/lib that point to the libraries installed in /opt/homebrew/lib.

Don't do this. Specify the path to the existing prefix instead.

**Comment by skra72** [comment]
Sure.

My intention was more to get details how Homebrew will circumvent this problem on Apple Silicon machines? Will the installer add it’s library path to the search path? Or something else?

**Comment by gromgit** [comment]
Not a maintainer, but I don't see any problem to circumvent, on either AS or Intel machines:
* **Homebrew formulae** always have the correct linkages in the correct directories, and run as expected.
* **Third-party software built against Homebrew-provisioned libraries** would have the correct linkages in the correct directories (if built as directed by their respective library formulae), and would therefore run as expected.
* **Third-party software built against third-party libraries** would have _incorrect_ linkages to begin with. Trying to get them to work with Homebrew libraries with the same name may or may not work, but I doubt the Homebrew maintainers would support this usage.
