### ISSUE TITLE
`brew audit` fails with an error on `audit_exceptions`

### ISSUE THREAD

**Issue by jabenninghoff** [Homebrew/brew#9244]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run `brew audit` on my externally maintained formula in my home directory.

## What happened (include command output)

`brew audit` fails with an error on `audit_exceptions`

<details>
  <summary>Command output</summary>
  <pre>
$ brew audit apg.rb
Error: undefined method `audit_exceptions' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:183:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:172:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:172:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
  </pre>
</details>

## What you expected to happen

`brew audit` successfully audits the formula

## Step-by-step reproduction instructions (by running `brew` commands)

run `brew audit` on any formula outside of the homebrew Taps directory (`/usr/local/Homebrew/Library/Taps`)

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.11-129-g570edcc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 570edcc0ccc23ee0fd4edd2b41a4f3df6e0a57ff
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4b7175b84a09f47c17f500b43d22127d0140d750
Core tap last commit: 19 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 36500
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.yEasnJ1z7g/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 11.0 build 1100
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.73.0 => /usr/local/opt/curl/bin/curl
Java: 15
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
</pre>

**Comment by issyl0** [comment]
Thanks for the report. I've put up a PR to fix this at #9249. Personally, though, I find it easier to do operations like `brew audit` on formulae in taps via `brew tap user/repo`, `cd $(brew --repo) user/repo` (it's just a normal Git repo) so that I don't have to keep track of two locations.
