### ISSUE TITLE
Update Frequency option

### ISSUE THREAD

**Issue by MarcusJohnson91** [Homebrew/brew#9256]
I know Homebrew checks the environment variable `HOMEBREW_NO_AUTO_UPDATE `, but that's not what I'm looking for.

can there be an option to update only once a day? like every time I try to install something it updating is just too much.

maybe the option could be called `HOMEBREW_UPDATE_FREQUENCY=X` where X is number of days.

**Comment by carlocab** [comment]
Is `HOMEBREW_AUTO_UPDATE_SECS` what you're looking for? Default is `300`.

Also, I suspect it would've been more appropriate to post this on https://github.com/Homebrew/discussions/discussions.

**Comment by jonchang** [comment]
This is documented in our man page: https://docs.brew.sh/Manpage#environment

Please always fill out the issue template.
