### ISSUE TITLE
Brew install opencv

### ISSUE THREAD

**Issue by ggbound** [Homebrew/brew#9271]
# Bug report

System OS: Mac BIG SUR

fatal: unable to access 'https://gist.github.com/7a0023656ccfe309337a.git/': Failed to connect to gist.github.com port 443: Connection refused

https://gist.github.com/tdsmith/7a0023656ccfe309337a is asecret package,why import this!!

**Comment by iMichka** [comment]
Hi. This is the wrong repo to report this to. Ideally this should have been done in https://github.com/Homebrew/homebrew-core

You also failed to fill out the issue template, so we can not help you. I'll close this until you update your bug report.
