### ISSUE TITLE
We do not provide support for this pre-release version.

### ISSUE THREAD

**Issue by AndroidIosWebEmbeddedFirmwareDver** [Homebrew/brew#9290]
# How to resolve this question.

Do not report this issue to Homebrew/brew or Homebrew/core!

Error: You are using macOS 11.1.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

**Comment by iMichka** [comment]
Do not report this issue to Homebrew/brew or Homebrew/core!
