### ISSUE TITLE
brew list no longer supports being in a pipeline

### ISSUE THREAD

**Issue by norm** [Homebrew/brew#9293]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Find out if a machine had a specific command installed by running `brew list | grep awscli`.

Note: this happens to all attempts to capture the output of `brew list` into a pipeline or file.

## What happened (include command output)

I got an error.

<details>
  <summary>Command output</summary>
  <pre>
    (vanster ~)% brew list | grep awscli
    Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
    (vanster ~)% 
  </pre>
</details>

## What you expected to happen

To not get an error, and instead to get the output of `brew list` filtered through grep.

## Step-by-step reproduction instructions (by running `brew` commands)

Try to capture the output of `brew list`.

## Output of `brew config` and `brew doctor` commands

Doesn't seem relevant.

**Comment by MikeMcQuaid** [comment]
>     Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.

The error tells you what to run instead.


> * [ ]  ran `brew config` and `brew doctor` and included their output with your issue?
> Doesn't seem relevant.

It is. Please include it next time. We ask for it for a reason.

**Comment by norm** [comment]
Might I then suggest you change the help description:

      --formula, --formulae        List only formulae. This is the default
                                   when output is not to a terminal.

as it doesn't seem to be honoured.
