### ISSUE TITLE
Brew complains about keychain credentials after a build error

### ISSUE THREAD

**Issue by chdiza** [Homebrew/brew#93]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

I'm tinkering with a custom formula.  One of these tinkerings broke the build, and since I build with the `-d` flag, this is where I normally see the outputs of `brew --config`, etc., plus suggestions for issues to look at.  After that, I now see:

```
Error: Your OS X keychain GitHub credentials do not have sufficient scope!
Scopes they have: []
Create a personal access token: https://github.com/settings/tokens
and then set HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
```

I have never seen this, ever, despite breaking hundreds of my own builds.  I don't understand why brew would even be asking for credentials at all, much less from the OSX keychain, after a failed build.  This is weirder still because my Keychain's GH credentials are just fine; they allow me to push to my repos with no prompts, so long as the OSX Keychain is unlocked.

**Comment by mistydemeo** [comment]
That message is coming from the attempt to look up issues via the Github API. Since the fix for Homebrew/legacy-homebrew#46578, Homebrew will attempt to use your Github credentials to access the API; in your case, the username and password stored in your Keychain don't appear to have the scopes required to access the API, so the API call failed.

**Comment by chdiza** [comment]
@mistydemeo's answer also explains why I've been seeing mysterious "can you give permission to let `git-credential-osxkeychain` access your Keychain?" dialog boxes.  On prior versions of OS X, the dialog had a little triangle you could click which would tell you which program(s) want to access your keychain.  That triangle is no longer there, so I had absolutely no clue what was calling `git-credential-osxkeychain`.  (There really should be, dear Apple, a way to tell that either `brew` or at least `ruby` is what's behind all this.)  I therefore, out of an abundance of caution, kept hitting "DENY".

Anyway, I guess I will just set `HOMEBREW_NO_GITHUB_API`, assuming that doing so will get rid of the messages I reported at the top of this thread.

**Comment by mikemcquaid** [comment]
`HOMEBREW_NO_GITHUB_API` will get rid of these messages, yes.

**Comment by agirorn** [comment]
Deleting the github.com entry from "Keychain Access.app" fixed this for me.

**Comment by rquadling** [comment]
Wouldn't deleting your github entry from the keychain result in having to enter credentials to access github again?

**Comment by MikeMcQuaid** [comment]
@rquadling Yes.
