### ISSUE TITLE
Store dependencies and versions in INSTALL_RECEIPT.json

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#930]
The tab for an installed formula should include a new key with an array of all the runtime (i.e. non-`build` dependencies) used to build the formula.

Extracted from https://github.com/Homebrew/brew-evolution/blob/master/003-install-bottles-of-arbitrary-versions.md merged in https://github.com/Homebrew/brew-evolution/pull/6.

CC @sjackman

**Comment by sjackman** [comment]
I don't yet have an implementation of this feature. Someone else is welcome to tackle this if they're so inclined. Otherwise I will eventually get to it, work permitting.
