### ISSUE TITLE
brew bundle cleanup and brew info --cask fails

### ISSUE THREAD

**Issue by lonelykid** [Homebrew/brew#9306]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to remove unused dependencies.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

Usage: brew info [options] [formula]

Display brief statistics for your Homebrew installation.

If formula is provided, show summary of information about formula.

      --analytics                  List global Homebrew analytics data or, if
                                   specified, installation and build error
                                   data for formula (provided neither
                                   HOMEBREW_NO_ANALYTICS nor
                                   HOMEBREW_NO_GITHUB_API are set).
      --days                       How many days of analytics data to
                                   retrieve. The value for days must be
                                   30, 90 or 365. The default is 30.
      --category                   Which type of analytics data to retrieve.
                                   The value for category must be install,
                                   install-on-request or build-error;
                                   cask-install or os-version may be
                                   specified if formula is not. The default
                                   is install.
      --github                     Open the GitHub source page for formula
                                   in a browser. To view formula history
                                   locally: brew log -p formula
      --json                       Print a JSON representation of formula.
                                   Currently the default and only accepted
                                   value for version is v1. See the docs
                                   for examples of using the JSON output:
                                   https://docs.brew.sh/Querying-Brew
      --installed                  Print JSON of formulae that are currently
                                   installed.
      --all                        Print JSON of all available formulae.
  -v, --verbose                    Show more verbose analytics data for
                                   formula.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Suppress any warnings.
  -h, --help                       Show this message.
Error: invalid option: --cask
Warning: Failed to parse `brew info --cask --json`: 767: unexpected token at ''

  </pre>
</details>

## What you expected to happen

Cleanup unused dependencies. It did remove some of them and then this error happened.

## Step-by-step reproduction instructions (by running `brew` commands)

````
brew bundle dump
brew bundle --force cleanup 
````
fails with the previous output.

Directly using
````
brew info --cask CASKNAME
````
also fails. I know this ``brew info --cask`` is added recently, but I'm on the latest release version of homebrew. I'm using Big Sur on intel Mac. I don't think this is a Big Sur issue, but if you think it is, I understand it's not supported yet and could wait.

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 07b3aa69f8dc5098437cf2562864558bae2d45aa
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dab282000b8aa5a3676dcc8d5657d3be656e4cad
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_275
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.
</pre>

**Comment by MikeMcQuaid** [comment]
Should be filed at https://github.com/Homebrew/homebrew-bundle/issues.

**Comment by lonelykid** [comment]
I thought this should be a brew issue. Shouldn't it be OK  for ``brew bundle`` to excute ``brew info --cask``? ``brew info --cask`` is supposed to work. Even without incurring ``brew bundle``, ``brew info --cask`` does not work by itself.

**Comment by MikeMcQuaid** [comment]
> Shouldn't it be OK for `brew bundle` to excute `brew info --cask`?

Not on the version of Homebrew/brew you're on.
