### ISSUE TITLE
Store the formula used to build a bottle inside the bottle

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#931]
When building a bottle, store the formula used to build the keg inside the bottle in a file named `NAME/VERSION/.bottle/NAME.rb` after removing the `bottle do ... end` block.

Extracted from https://github.com/Homebrew/brew-evolution/blob/master/003-install-bottles-of-arbitrary-versions.md merged in https://github.com/Homebrew/brew-evolution/pull/6.

CC @sjackman

**Comment by sjackman** [comment]
I have an implementation of this feature that needs just a bit more work. I'll submit a PR this coming week (hopefully early in the week).

**Comment by MikeMcQuaid** [comment]
Cool, thanks @sjackman.

**Comment by sjackman** [comment]
I've created a PR at https://github.com/Homebrew/brew/pull/1052
