### ISSUE TITLE
Allow platform-specific cellars in bottle blocks

### ISSUE THREAD

**Issue by iMichka** [Homebrew/brew#9315]
# Feature suggestion

# A detailed description of the proposed feature

Bottle blocks currently look like this:
```
bottle do
  cellar :any_skip_relocation
  sha256 "a0af7dcbb5c83f6f3f7ecd507c2d352c1a018f894d51ad241ce8492fa598010f" => :big_sur
  sha256 "5334dd344986e46b2aa4f0471cac7b0914bd7de7cb890a34415771788d03f2ac" => :catalina
  sha256 "22948764d8f8d7be4870ff92dae64d986eb63a9150b219c20fff87d1a6aa93d6" => :mojave
  sha256 "702dc7f78444d2f4f1c19324be654bcbb8b99dd0e9ce26c3e2fbc3b6464a189f" => :x86_64_linux
end
```

The cellar line is often different on Linux, and might be different between Mac OS versions too.

The proposal is to have per-platform cellar lines, for example:

```
bottle do
  sha256 "a0af7dcbb5c83f6f3f7ecd507c2d352c1a018f894d51ad241ce8492fa598010f" => :big_sur, cellar :any_skip_relocation
  sha256 "5334dd344986e46b2aa4f0471cac7b0914bd7de7cb890a34415771788d03f2ac" => :catalina, cellar :any_skip_relocation
  sha256 "22948764d8f8d7be4870ff92dae64d986eb63a9150b219c20fff87d1a6aa93d6" => :mojave, cellar :any_skip_relocation
  sha256 "702dc7f78444d2f4f1c19324be654bcbb8b99dd0e9ce26c3e2fbc3b6464a189f" => :x86_64_linux, cellar :any
end
```

Making this work is mostly rewriting the merge function in bottle.rb.
Backward compatibility is a concern of course and need to be maintained with the old syntax.

# The motivation for the feature

This is needed for the linuxbrew-core to homebrew-core migration.

# How the feature would be relevant to at least 90% of Homebrew users

Having the right cellars for the right platform makes sure things do not go up in flames when we merge both repositories, so it's probably a good thing.

# What alternatives to the feature have been considered

- Use the Mac cellar line for linux: this might lead to some weird breakage

**Comment by MikeMcQuaid** [comment]
> Making this work is mostly rewriting the merge function in bottle.rb.

I mildly disagree. I see one step before that and (at least) two after:

1. adding DSL support for the new `cellar:` argument which takes priority over the block cellar (and both can be specified)
2. make the merge logic in `bottle.rb` start writing the new cellar and never the old one
3. add a RuboCop to fix up all existing `bottle do` blocks automatically with brew style --fix
4. `odeprecated` the old `cellar` DSL and eventually `odisabled` and eventually remove it (across three minor releases)

1. and 2. should be achieved with the minimum possible number of changes to `bottle.rb`. It maybe warrants a larger refactoring but that should happen after tests have been added (i.e. tests are added and merged before the refactoring is started and test changes aren't needed during the refactoring) and not as part of 1. or 2.

**Comment by iMichka** [comment]
After a bunch of refactoring and cleanup PR's, test additions around the bottle command, and finally the addition of the reading of the new syntax, I'll start working on step 2. Step 2 consists in writing the new cellars to the respective sha256 lines.

**Comment by iMichka** [comment]
We are done here, see #10449.

Thanks all for the help!

**Comment by iMichka** [comment]
Woups, re-opening we need to discuss step 3 and 4:
> add a RuboCop to fix up all existing bottle do blocks automatically with brew style --fix

> odeprecated the old cellar DSL and eventually odisabled and eventually remove it (across three minor releases)

Should we just leave this as-is and let the bottling magic fix the things over the years for us? I think that the old syntax will be gone with the next macOS version, so roughly in one year. This leaves also time to external taps to rebuild stuff naturally without noticing.

**Comment by MikeMcQuaid** [comment]
> > add a RuboCop to fix up all existing bottle do blocks automatically with brew style --fix

I think it would be ideal to have this as it'll let us deprecate, disable and remove the old behaviour more quickly. Doesn't mean you have to do it, though! One of our other rubocop experts could pick this up CC @SeekingMeaning @Rylan12 @carlocab @GauthamGoli in case any of you are interested.

**Comment by sjackman** [comment]
Brewsci/bio would be a great third-party tap beta test site for such a tool! I'd happily volunteer to try it out.

**Comment by iMichka** [comment]
The last remaining step is to:
> odeprecated the old cellar DSL

Does someone want to pick that up?

**Comment by Rylan12** [comment]
I opened a PR to prepare those deprecations: https://github.com/Homebrew/brew/pull/10547/files

**Comment by iMichka** [comment]
Cool. I'll close this then, and the deprecations will follow the normal process. Thanks all!
