### ISSUE TITLE
mongodb-community error

### ISSUE THREAD

**Issue by alex-toy** [Homebrew/brew#9332]
# Please fill out one of the templates on: https://github.com/Homebrew/brew/issues/new/choose or we will close it without comment.

brew services list
Name              Status  User   Plist
mongodb-community error   alexei /Users/alexei/Library/LaunchAgents/homebrew.mxcl.mongodb-community.plist
php               stopped        
postgresql        stopped

**Comment by gromgit** [comment]
`mongodb-community` is not a Homebrew core formula, so you're better off asking on their community forums: https://developer.mongodb.com/community/forums/
