### ISSUE TITLE
how to fix "Sorry, Homebrew does not support your computer's CPU architecture!"

### ISSUE THREAD

**Issue by OrioGod** [Homebrew/brew#9341]
Warning: Sorry, Homebrew does not support your computer's CPU architecture!
Warning: You are using macOS 11.0.
We do not provide support for this pre-release version.
![image](https://user-images.githubusercontent.com/37584680/100565684-1aa4f680-32ff-11eb-9a7e-174e7bd9d915.png)

**Comment by jonchang** [comment]
Please always fill out the issue template. This can be reopened if you add the requested information: https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE/bug.md

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.
