### ISSUE TITLE
Add audit to automatically detect 404ing mirrors

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#935]
A new audit check should be added that iterates through the various `mirror`s and checks that they do not 404. This could be part of `brew fetch` to check every mirror and the checksum.

**Comment by MatzFan** [comment]
Thinking of putting my hand up to help with this one. Is the ask to just verify the response codes of mirrors (not 400+ I guess), or this + download and verify checksum for every mirror too? If the later would you be happy with it delivered in 2 parts?!

**Comment by zmwangx** [comment]
IMO the latter (download and verify checksum) should be part of fetch rather than part of audit. No one should be downloading multiple copies locally, even when running the strictest audit; just let the bot handle that part.

**Comment by MatzFan** [comment]
OK, status codes it is then.

Before I start I need to find out why I have failing tests in my test env (`brew sh --env=std`) - where can I get help with this?

**Comment by zmwangx** [comment]
You should probably open an issue with more specific information.

**Comment by MatzFan** [comment]
will do, thx

**Comment by MikeMcQuaid** [comment]
Yeh, I reckon make it an optional part of `brew fetch` and download each one in turn and checksum it. Would be great to have you work on this!

**Comment by MatzFan** [comment]
Be glad to contribute - had so much out of Homebrew over the years 🍺

**Comment by MatzFan** [comment]
Gonna have to leave this one. Got a way in, but it seemed too complex - sorry for holding it up folks

**Comment by MikeMcQuaid** [comment]
@MatzFan No worries, thanks for looking. If you have a half-completed/work-in-progress PR then open it anyway and ensure you enable the "allow maintainers to push to this PR" and I can look at finishing it off.

**Comment by MikeMcQuaid** [comment]
This was done in https://github.com/Homebrew/brew/issues/1637 🎉
