### ISSUE TITLE
How to upgrade all brews when upgrading OS X - doc needed

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/brew#937]
I haven't found any information yet on how to handle homebrews when upgrading OS releases such as from 10.11 El Cap to 10.12 Sierra. Would be happy to write up such a doc if there are notes or suggestions on how to handle this that I can look at and pull together.

Since there are OS specific bottles (El Cap bottles, Sierra bottles, etc), it would seem I'd need to uninstall and reinstall all brews to get rid of El Cap bottles and get Sierra bottles instead. In addition, compiled (not bottled) brews may also need to uninstalled then re-compiled under the new OS X?

And a related issue - when upgrading to a new major Xcode/Command Line Tools release (such as Xcode 7.x -> 8.x), do compiled brews need to be recompiled with the new Xcode/CLI Tools?

**Comment by MikeMcQuaid** [comment]
Technically you don't need to reinstall them. If you really want to the best bet may be `brew bundle dump && brew uninstall $(brew list) && brew bundle`.

> do compiled brews need to be recompiled with the new Xcode/CLI Tools?

Definitely not.

**Comment by scpeters** [comment]
I don't know if the advice in the following link is still relevant ( https://jimlindley.com/blog/yosemite-upgrade-homebrew-tips/ ), but they said that having files in /usr/local made ugprading really slow. Maybe this has been fixed since 10.10.

**Comment by edrozenberg** [comment]
@scpeters thanks! Luckily I had no speed issues upgrading to macOS Sierra - took about 20-30 min as expected.
