### ISSUE TITLE
zsh path completion check is faulty

### ISSUE THREAD

**Issue by NReilingh** [Homebrew/brew#9387]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

When installing a formula with zsh shell completions, caveats checks to see whether the site-functions dir is in zsh's FPATH, and displays a message if it isn't. The logic for this appears to be faulty, and returns the message even when the dir is in FPATH.

This seems to be replicated independently already: https://github.com/jackboberg/dotfiles/issues/4

Looking into the source, this appears to be the offending snippet:

https://github.com/Homebrew/brew/blob/86631b4fef1b160477ed31a4e9667c8baeecb420/Library/Homebrew/caveats.rb#L136-L143

I'm not particularly familiar with Ruby or the homebrew source, but I suspect that `HOMEBREW_FPATH` isn't actually a thing.

It looks like the issue was introduced with this commit and PR: https://github.com/Homebrew/brew/commit/3002c810be2981543a4732016c83b6e140e6e439 https://github.com/Homebrew/brew/pull/9292

## What happened (include command output)

I found this when installing jfrog-cli, which includes path completions.

<details>
  <summary>Command output</summary>
  <pre>

nreiling@pac-aw-neonecho ~ % brew install jfrog-cli
==> jfrog-cli
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions

/usr/local/share/zsh/site-functions is not in your zsh FPATH!
Add it by following these steps:
  https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh

nreiling@pac-aw-neonecho ~ % echo $FPATH
/Users/nreiling/.twilio-cli/autocomplete/functions/zsh:/usr/local/share/zsh/site-functions:/usr/share/zsh/site-functions:/usr/share/zsh/5.7.1/functions
  </pre>
</details>

## What you expected to happen

since `$FPATH` contains `/usr/local/share/zsh/site-functions`, the caveat `/usr/local/share/zsh/site-functions is not in your zsh FPATH!` should not display.

## Step-by-step reproduction instructions (by running `brew` commands)

    brew install jfrog-cli

## Output of `brew config` and `brew doctor` commands

<details>
<summary>Command output</summary>
<pre>
nreiling@pac-aw-neonecho fc-sftp-server % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libndi.4.dylib
nreiling@pac-aw-neonecho fc-sftp-server % brew config
HOMEBREW_VERSION: 2.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1d5e354cc2ff048bd7161d95b3fa7f91dc9dd081
Last commit: 28 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fdb83fcfb482e5ed1f1c3c442a85b99223fcabeb
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.8JKV4eyHIZ/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1
macOS: 10.15.7-x86_64
CLT: 11.0.33.8
Xcode: 12.2
XQuartz: 2.7.11 => /opt/X11
nreiling@pac-aw-neonecho fc-sftp-server % 
</pre>
</details>

**Comment by MikeMcQuaid** [comment]
I use ZSH and have `FPATH` set and cannot reproduce this.

> but I suspect that `HOMEBREW_FPATH` isn't actually a thing.

It is, it's set from `FPATH`.

> since `$FPATH` contains `/usr/local/share/zsh/site-functions`, the caveat `/usr/local/share/zsh/site-functions is not in your zsh FPATH!` should not display.

Can I see the output of `env | grep FPATH`?

**Comment by NReilingh** [comment]
> Can I see the output of `env | grep FPATH`?

It is... blank! How interesting.

**Comment by sharris40** [comment]
@MikeMcQuaid, are you exporting FPATH in your profile somewhere? bin/brew is a Bash script, not a ZSH script, and FPATH shouldn’t be exported to it.

**Comment by MikeMcQuaid** [comment]
> are you exporting FPATH in your profile somewhere?

Yes.

I'm open to suggestions on how to detect this otherwise.

**Comment by sharris40** [comment]
I wrote a two-line script that I think might work, though I haven’t tested it thoroughly:

    #!/usr/bin/env zsh -i -t
    echo FPATH=$FPATH

The idea being that it runs the first instance of `zsh` in the path, forces it into interactive mode so that it reads its zshrc files, and forces it to exit after one command, which prevents it from saving session files (though it will still read them and restore any saved sessions). Then, in `bin/brew`, run it and grep for the line starting with “FPATH=”.

Alternatively, write a script that sources the zshrc files manually, but that would break if somebody has a ZSH that looks for startup scripts in some non-standard location for some reason.

**Comment by MikeMcQuaid** [comment]
@sharris40 does `zsh -c "echo $FPATH"` work for you?

**Comment by MikeMcQuaid** [comment]
@sharris40 you can ignore this, I have a fix in https://github.com/MikeMcQuaid/brew/pull/new/zsh-fpath-fixes

**Comment by sharris40** [comment]
I don’t think that fix works. FPATH is only supposed to be set in interactive shells and not exported, hence why it’s set in zshrc normally. Running zsh with -c doesn’t source zshrc. It has to be run with -i and not -c.

**Comment by MikeMcQuaid** [comment]
@sharris40 PR updated to add `-i`.
