### ISSUE TITLE
Formulae subcommand using GNU specific sed flags

### ISSUE THREAD

**Issue by bradschwartz** [Homebrew/brew#9388]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Was trying to use the completions for the `home` subcommand.
```bash
brew home <tab><tab>
```

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

   $ brew home sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]

  </pre>
</details>

## What you expected to happen

I expected to see a list of formula.

## Step-by-step reproduction instructions (by running `brew` commands)

```bash
brew home <tab><tab>
```

Starting a new shell with `bash -lx` to get the debug output prints out:

```bash
brew home + '[' 2 -gt 1 ']'
+ '[' home = services ']'
+ _brew
+ local i=1 cmd
+ [[ 1 -lt 2 ]]
+ local s=home
+ case "$s" in
+ cmd=home
+ break
+ [[ 1 -eq 2 ]]
+ case "$cmd" in
+ __brew_complete_formulae
+ local cur=
++ brew formulae
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
+ local formulae=
+ COMPREPLY=($(compgen -W "$formulae" -- "$cur"))
++ compgen -W '' -- ''
```

It looks like in the `formulae` subcommand it is using the GNU sed specific flag `-r` for extended
regular expressions. The POSIX flag is `-E` and is supported by BSD sed as well. This causes the
`__brew_complete_formulae` completion helper function to fail.
Believe this line: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/formulae.sh#L19
needs to change `-r` to `-E` but have not tested.

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.6.0-42-g68889b9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 68889b972c3d5d8bbe55a0633e1e6e320fe03232
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fdb83fcfb482e5ed1f1c3c442a85b99223fcabeb
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 3600
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15.0.1, 14.0.1, 13.0.2, 13.0.1, 10.0.1, 1.8.0_275, 1.8.0_231, 1.8.0_202
macOS: 10.15.7-x86_64
CLT: 12.0.32.27
Xcode: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  hadoop
</pre>

**Comment by MikeMcQuaid** [comment]
This will be fixed by https://github.com/Homebrew/brew/pull/9367
