### ISSUE TITLE
Automate getting updates

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [Homebrew/brew#9390]
# Feature suggestion

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

I think it would be very nice if you could automate the update process in the way, that a program automatic searches for new updates in the background so that you won't have to replace the older version automatically.

# A detailed description of the proposed feature

Maybe you could run something like a GitHub workflow that searches one time at a day/a week for newer version of the brew packages/casks and replaces the older versions automatically with the newer ones. 

# The motivation for the feature

I think this could reduce the work of the maintainers/developers a lot because you haven't to upgrade all the packages manually.

# How the feature would be relevant to at least 90% of Homebrew users

I think this feature could be relevant for the most home-brew users in the way that if that is working they can get the updates for their programs much faster. (f.e. I can install since more than 1 week manually an new iterm2 update and at the cli it don't update)

# What alternatives to the feature have been considered

A alternative is to continue the current workflow of keeping homebrew programs up to date.

**Comment by Rylan12** [comment]
Thanks for the suggestion. There's already an open issue for this (https://github.com/Homebrew/brew/issues/5725) so I'm going to close this one.

I haven't heard complaints from other maintainers about this being an issue, so I'm not sure we need to implement such a feature. As far as I know, we do a pretty good job of keeping packages up to date. In general, we rely on contributors as well as maintainers to open PRs to update versions, so if there's a specific formula that you would like to have updated that prompted this, I'd encourage you to open a PR to update the formula. There's some pretty helpful [documentation](https://docs.brew.sh/Updating-Software-in-Homebrew) available and the `brew bump-formula-pr` command makes it very easy.

This general functionality already exists with the `brew livecheck` command (especially when combined with `brew bump-formula-pr`). I believe that some maintainers may even have what you're suggesting running in the cloud somewhere (possibly in a GitHub action).
