### ISSUE TITLE
HomeBrew error for chromeos linux beta

### ISSUE THREAD

**Issue by but0004** [Homebrew/brew#9392]
What do I do?[]
![Screenshot 2020-12-03 at 8 58 39 AM](https://user-images.githubusercontent.com/75396588/100936888-4bc33800-3546-11eb-8f19-aeb2d28a0ba3.png)

**Comment by EricFromCanada** [comment]
> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
