### ISSUE TITLE
Issue finding a file for linux beta in chrome os

### ISSUE THREAD

**Issue by but0004** [Homebrew/brew#9393]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

<!Solve a issue>

## What happened (include command output)

<!when my terminal allways starts is says
-bash: /bin/brew:  can not be found
-bash: /bin/brew: can not be found
-bash: /bin/brew: can not be found

then i went into /local/bin and added a direcrory and now its saying:
-bash: /bin/brew: Is a directory
-bash: /bin/brew: Is a directory
-bash: /bin/brew: Is a directory
>

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

<!I thought mkdir brew would work but it didn't>

## Step-by-step reproduction instructions (by running `brew` commands)

<!i did brew doctor but did not change anything>

## Output of `brew config` and `brew doctor` commands
HOMEBREW_VERSION: 2.5.8-118-g2ac5cff
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ac5cffd0dc261b2ab922169197e8b766b7d5748
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 4e9e47959bc310bb900d4967b587dd6a9708a652
Core tap last commit: 4 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /home/but0004/.linuxbrew
HOMEBREW_REPOSITORY: /home/but0004/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/but0004/.linuxbrew/Cellar
HOMEBREW_BROWSER: /usr/bin/garcon-url-handler
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /home/but0004/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit unknown_0x6_0x7a
Clang: N/A
Git: 2.20.1 => /usr/bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 5.4.58-07649-ge120df5deade x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.28
/usr/bin/gcc: 8.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: 5.5.0_7
xorg: N/A

and doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

<pre>

</pre>

**Comment by gromgit** [comment]
If you're getting those errors when you start your terminal, something's wrong with your `.bashrc` or `.profile`, whichever script you try to run `brew` in. Given the specific path that's erroring out, I'm guessing that you're trying to run `$HOMEBREW_PREFIX/bin/brew`, but:
* you didn't set `HOMEBREW_PREFIX` correctly, and/or
* you misspelled `HOMEBREW_PREFIX` in your command

**Comment by but0004** [comment]
@gromgit How do i check it?

**Comment by gromgit** [comment]
Open each file in your editor, then search for `HOMEBREW_PREFIX`. Every line that you expected to find a match, but didn't, is a line that you typo'd. Fix those misspellings.

**Comment by but0004** [comment]
@gromgit is there a way to uninstall homebrew

**Comment by gromgit** [comment]
https://github.com/homebrew/install#uninstall-homebrew

**Comment by but0004** [comment]
@gromgit an error popped up
![Screenshot 2020-12-03 at 12 48 33 PM](https://user-images.githubusercontent.com/75396588/100953093-e8e19900-3565-11eb-88d5-80368a58de2b.png)

**Comment by but0004** [comment]
@gromgit now under those error messeges it comes up with
-bash: /home/but0004/.linuxbrew/bin/brew: No such file or directory
now when i start terminal

**Comment by gromgit** [comment]
As the error says:
```
To finish uninstalling rerun this script with `sudo`.
```
I'm not sure what `apt-get auto-remove` has to do with Homebrew.

Also, when asking for tech help in future, it's generally better to copy/paste terminal text instead of taking screenshots, so people helping you aren't forced to manually type in the same commands you did (and accidentally _not_ make the same typos).

**Comment by gromgit** [comment]
> `-bash: /home/but0004/.linuxbrew/bin/brew: No such file or directory`

Since you've uninstalled Homebrew, you have to stop invoking `brew` in your `.bashrc` and/or `.profile`.

**Comment by but0004** [comment]
@gromgit when i do it now it says 
/bin/bash: line 193: brew: command not found
Failed to locate Homebrew!

**Comment by gromgit** [comment]
```
curl -Lo /tmp/uninstall.sh https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
bash /tmp/uninstall.sh -p /home/but0004/.linuxbrew
```
If that succeeds, you can then `rm /tmp/uninstall.sh`.

**Comment by but0004** [comment]
@gromgit  output from bash:
Warning: Unrecognized option: '/home/but0004/.linuxbrew'
Homebrew Uninstaller
Usage: /tmp/uninstall.sh [options]
    -p, --path=PATH  Sets Homebrew prefix. Defaults to /usr/local.
        --skip-cache-and-logs
                     Skips removal of HOMEBREW_CACHE and HOMEBREW_LOGS.
    -f, --force      Uninstall without prompting.
    -q, --quiet      Suppress all output.
    -d, --dry-run    Simulate uninstall but don't remove anything.
    -h, --help       Display this message.

**Comment by gromgit** [comment]
Try this instead:
```
bash /tmp/uninstall.sh --path=/home/but0004/.linuxbrew
```
Also, this is no longer a `brew` issue, so if you need to continue, please go to https://github.com/Homebrew/discussions/discussions and open a new discussion.
