### ISSUE TITLE
bump-formula-pr "Error: package should be a valid PyPI url" but formula has no Python resources

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#9402]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I ran

    brew bump-formula-pr --version=2.0.9 emscripten

## What happened (include command output)

```
❯ brew bump-formula-pr --version=2.0.9 emscripten
Warning: This formula has resources that may need to be updated.
Error: package should be a valid PyPI url
/usr/local/Homebrew/Library/Homebrew/utils/pypi.rb:34:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/pypi.rb:111:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/pypi.rb:111:in `update_pypi_url'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:202:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

## What you expected to happen

No errors.

## Step-by-step reproduction instructions (by running `brew` commands)

Just `brew bump-formula-pr --version=2.0.9 emscripten`.

## Output of `brew config` and `brew doctor` commands

<pre>
❯ brew config && brew doctor
HOMEBREW_VERSION: 2.6.0-57-gdd61cea
ORIGIN: https://github.com/Homebrew/brew
HEAD: dd61cea63b11f58560cb24e5c745f0c411549d16
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e24f5681e7e2a9667361686f2f4896f0c480af06
Core tap last commit: 49 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_COLOR: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_VENDOR_RUBY: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: N/A
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
</pre>

**Comment by Rylan12** [comment]
Thanks for the report, @carlocab! Fix in https://github.com/Homebrew/brew/pull/9413
