### ISSUE TITLE
Cannot brew update or upgrade: Error: homebrew-cask is a shallow clone.

### ISSUE THREAD

**Issue by Fingel** [Homebrew/brew#9420]
# Bug report

- [* ] ran `brew update` and can still reproduce the problem?
- [* ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [* ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I tried to run `brew update` and `brew upgrade` as usual to update the packages on my machine. Instead, I got the error below informing me that homebrow-core is a shallow clone (that's a good thing right?) and that I should unshallow it. Seemed a bit odd to me, as I thought the point of a shallow clone was to save a bunch of disk space, but I ran the command anyway. After running the suggested command to unshallow, the error remains on subsequent tries. So perhaps the issue is unrelated to the "shallowness" of the repo.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew update
Error: homebrew-core is a shallow clone. To `brew update` first run:
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow

$ git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
remote: Enumerating objects: 848801, done.
remote: Counting objects: 100% (848798/848798), done.
remote: Compressing objects: 100% (272589/272589), done.
remote: Total 843685 (delta 574218), reused 837687 (delta 568229), pack-reused 0
Receiving objects: 100% (843685/843685), 331.47 MiB | 10.81 MiB/s, done.
Resolving deltas: 100% (574218/574218), completed with 4347 local objects.
From https://github.com/Homebrew/homebrew-core
   55b17bad99..536b616fc3 master     -> origin/master

$ brew upgrade
Error: homebrew-cask is a shallow clone. To `brew update` first run:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch --unshallow

  </pre>
</details>

## What you expected to happen

Brew update and upgrade to update and upgrade, respectively.

## Step-by-step reproduction instructions (by running `brew` commands)

    brew update

## Output of `brew config` and `brew doctor` commands

Brew Config:
<pre>
HOMEBREW_VERSION: 2.6.0-68-g5ad9496
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5ad949672f1fd9ce900e1196a0ad2c020f869480
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 55b17bad998d4b72411754fe69d68b7f3b4d1292
Core tap last commit: 25 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: 12.2
</pre>

Brew Doctor:
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  python@2

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.7m/greenlet/greenlet.h
  /usr/local/include/python3.8/greenlet/greenlet.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish

**Comment by EricFromCanada** [comment]
> Error: homebrew-cask is a shallow clone. To brew update first run:
>
> git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch --unshallow

Please do this.

**Comment by Fingel** [comment]
> Please do this.

I did? It's pretty clear in my bug report. But I'll post it here again:

```
$ brew update

Error: homebrew-core is a shallow clone. To brew update first run:

git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow


$ git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow

remote: Enumerating objects: 848801, done.

remote: Counting objects: 100% (848798/848798), done.

remote: Compressing objects: 100% (272589/272589), done.

remote: Total 843685 (delta 574218), reused 837687 (delta 568229), pack-reused 0

Receiving objects: 100% (843685/843685), 331.47 MiB | 10.81 MiB/s, done.

Resolving deltas: 100% (574218/574218), completed with 4347 local objects.

From https://github.com/Homebrew/homebrew-core

55b17bad99..536b616fc3 master     -> origin/master


$ brew upgrade

Error: homebrew-cask is a shallow clone. To brew update first run:

git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch --unshallow
```

**Comment by EricFromCanada** [comment]
No, what you ran was `git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow`. Not the same command.

**Comment by Fingel** [comment]
You're right! I didn't notice that the repo was different the second time around.

Closing now as it seems to be working. Any thoughts on why I had to unshallow these repos? Seems a bit annoying since they are huge.

**Comment by EricFromCanada** [comment]
[GitHub has requested this.](https://github.com/Homebrew/brew/pull/9383)

**Comment by Fingel** [comment]
Ouch. Alright, thanks!

**Comment by MikeMcQuaid** [comment]
I've opened https://github.com/Homebrew/brew/pull/9447 to improve the message here.

**Comment by niraj28** [comment]
Error: homebrew-core is a shallow clone. To `brew update` first run:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core. We don't do this for you automatically to avoid
repeatedly performing an expensive unshallow operation in CI systems (which
should instead be fixed to not use shallow clones). Sorry for the inconvenience!

having same issue, I tried running seperatly 
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" 
fetch --unshallow
not working, I am unable to figure out the mistake I might be doing.

**Comment by rishimohan** [comment]
@niraj28 Run the below and then try again

`git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch --unshallow`

**Comment by niraj28** [comment]
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch
 git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch --unshallow

now working fine.
