### ISSUE TITLE
banning shallow clones breaks existing installs with no explanation

### ISSUE THREAD

**Issue by gotyaoi** [Homebrew/brew#9426]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

run brew update

## What happened (include command output)

errors out

<details>
  <summary>Command output</summary>
  <pre>

Error: homebrew-core is a shallow clone. To `brew update` first run:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
  </pre>
</details>

## What you expected to happen

the update should run, or the error should have more explanation

## Step-by-step reproduction instructions (by running `brew` commands)

brew update after updating to https://github.com/Homebrew/brew/commit/10e73164f0f00c0451cd7c8ca289960d1326f7a0

## Output of `brew config` and `brew doctor` commands

<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config

HOMEBREW_VERSION: 2.6.0-91-g7e3e86e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7e3e86eb41d1b8f29708ac451946ff4f561d1abc
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cc60bcab602e7fdceb87e5d4118f7b7364cdf64d
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.9.1
macOS: 10.15.7-x86_64
CLT: 12.2.0.0.1.1604628099
Xcode: N/A
</pre>

I don't remember explicitly installing homebrew with a shallow clone, so I assume that it was the default at one point. This commit: https://github.com/Homebrew/brew/commit/10e73164f0f00c0451cd7c8ca289960d1326f7a0 bans the use of such shallow clones with just a message to run a command. Would most users know that they had a shallow clone in the first place, or why the command needs to be run, or what it will do? Additionally, no reference to the shallow clone being a problem exists in brew doctor.

Given that it's just one command, couldn't it be run automatically on update, since brew updating won't work anyway until it's been done?

**Comment by jonchang** [comment]
This is to avoid automatically updating CI pipelines which are incorrectly using shallow clones.

**Comment by gotyaoi** [comment]
Sorry, didn't see any reference to the PR in the commit, my bad. Given the comment in the PR: "I think this being documented in the PR is fine for now." do you think linking to the PR in the error message would be appropriate? ie. "see https://github.com/Homebrew/brew/pull/9383 for more info" or something?

**Comment by MikeMcQuaid** [comment]
I've opened https://github.com/Homebrew/brew/pull/9447 to improve the message here and explain wy this won't be done automatically.
