### ISSUE TITLE
Use /usr/local/bin/sudo instead of /usr/bin/sudo if it is found in the system.

### ISSUE THREAD

**Issue by rnicolas** [Homebrew/brew#9428]
# Feature suggestion

Mac OS systems does not have the last stable version of sudo, one can update sudo through the installers found in https://github.com/sudo-project/sudo, but those installers install the new version of sudo in /usr/local/bin/sudo. A check if this sudo is installed would be sufficient.

# A detailed description of the proposed feature

When the script checks for sudo in /usr/bin, it should check before if /usr/local/bin/sudo exists, and if it exists, assign that to SUDO variable. 

# The motivation for the feature

Mac OS 10.13 uses sudo 1.8.29 which throws a lot of weird errors when trying to do a new installation of brew.

# How the feature would be relevant to at least 90% of Homebrew users

We will be not attached to wait for Apple sudo updates and we can update it on our own.

# What alternatives to the feature have been considered

Continuing using the typical installers for Mac OS instead of brew.

**Comment by carlocab** [comment]
I don't like this idea.

The provenance of `/usr/bin/sudo` can be pretty much guaranteed due to SIP. Who knows what `/usr/local/bin/sudo` is? It could be a malicious script pretending to be `sudo` to steal credentials.

**Comment by rnicolas** [comment]
> The provenance of `/usr/bin/sudo` can be pretty much guaranteed due to SIP. Who knows what `/usr/local/bin/sudo` is? It could be a malicious script pretending to be `sudo` to steal credentials.

That's a discussion for sudo project and why their installer installs `sudo` in `/usr/local/bin/sudo` instead of `/usr/bin/sudo`.

**Comment by carlocab** [comment]
Leaving aside long-standing *nix conventions about installing in `/usr/bin` instead of `/usr/local/bin`, so trying to have that discussion there is going to go nowhere, the sudo-project will not be able to install `sudo` into `/usr/bin`:

>The provenance of /usr/bin/sudo can be pretty much guaranteed due to SIP.

**Comment by rnicolas** [comment]
Then why did you start it?

**Comment by carlocab** [comment]
I did not. If you think I did, then you have misunderstood what I said.

**Comment by vitorgalvao** [comment]
> Mac OS 10.13 uses sudo 1.8.29 which throws a lot of weird errors when trying to do a new installation of brew.

Technically [we require 10.14 or above](https://docs.brew.sh/Installation#macos-requirements), so I don’t think we should change behaviour with possible security implications to accommodate unsopported macOS versions whose usage will only diminish. I’d say that alone disqualifies it from the “How the feature would be relevant to at least 90% of Homebrew users” section.

**Comment by rnicolas** [comment]
> > Mac OS 10.13 uses sudo 1.8.29 which throws a lot of weird errors when trying to do a new installation of brew.
> 
> Technically [we require 10.14 or above](https://docs.brew.sh/Installation#macos-requirements), so I don’t think we should change behavior with possible security implications to accommodate unsopported macOS versions whose usage will only diminish. I’d say that alone disqualifies it from the “How the feature would be relevant to at least 90% of Homebrew users” section.

That's what motivated me to submit the feature, but it's not giving backward support per se. For example, I have another Mac with Catalina installed, `sudo` version in `/usr/bin` is 1.8.31 which has some flaws and bugs, and I want to use the updated version 1.9.4 which is found in `/usr/local/bin`.

**Comment by vitorgalvao** [comment]
> I have another Mac with Catalina installed, `sudo` version in `/usr/bin` is 1.8.31 which has some flaws and bugs

Do any of those affect normal Homebrew operations in a breaking or dangerous way? Because if not, the point still stands. It seems unlikely to me we’ll change that behaviour, especially since you seem to be the only one requesting it and there are other people actively against it.

But I’ll leave further commentary (and an eventual issue close) to another maintainer who may have touched those parts of the core directly.

> and I want to use the updated version 1.9.4 which is found in `/usr/local/bin`.

You’re still free to do so in your own software. For Homebrew itself, I still don’t see the point. I’m on Mojave and never bumped into any issue with `sudo`.

**Comment by rnicolas** [comment]
> Do any of those affect normal Homebrew operations in a breaking or dangerous way? Because if not, the point still stands. 

I'm not talking about a bug, I'm talking about a feature. But anyway, I'm closing it.

**Comment by MikeMcQuaid** [comment]
> Mac OS 10.13 uses sudo 1.8.29 which throws a lot of weird errors when trying to do a new installation of brew.

We'd consider PRs to improve this.

I agree with the closing of this, otherwise. Thanks!
