### ISSUE TITLE
Can't update or upgrade Homebrew

### ISSUE THREAD

**Issue by orome** [Homebrew/brew#9430]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run either `brew update` or  `brew upgrade`.

## What happened (include command output)

I can't preform either command and instead get:
```
Error: homebrew-core is a shallow clone. To `brew update` first run:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
```

## What you expected to happen

I expect basic commands like `upgrade` and `update` to run without errors.

## Step-by-step reproduction instructions (by running `brew` commands)

Run either 

`brew update`
or
`brew upgrade`

and the above error results.

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.6.0-82-gde1afcb
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: de1afcbfc58fb3cd5779bd8fbb6b9995700dda4c
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a7c63b0f7f7ae416a2f961b263155281759ac3a7
Core tap last commit: 28 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.FwPJPzeLfq/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/bbedit
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_EMOJI: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_172
macOS: 10.15.7-x86_64
CLT: 12.0.32.27
Xcode: 12.2
XQuartz: 2.7.11 => /opt/X11
</pre>

<pre>
Your system is ready to brew.
</pre>

**Comment by vitorgalvao** [comment]
> I can't preform either command and instead get:
> 
> ```
> Error: homebrew-core is a shallow clone. To `brew update` first run:
>   git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
> ```

And have you done so? Have you run that command? What’s the output?

**Comment by orome** [comment]
@vitorgalvao 
> And have you done so? Have you run that command? What’s the output?
Won't that [take up a ton of space and slow down Homerew](https://stackoverflow.com/questions/45782694/how-to-remove-the-shallow-clone-warning-from-homebrew#comment88882548_45784973)?

**Comment by EricFromCanada** [comment]
GitHub has [specifically requested](https://github.com/Homebrew/brew/pull/9383) that we stop using shallow clones.

**Comment by orome** [comment]
I'm just a user of Homebrew, not a developer. So I'm just looking for `update` and `upgrade` to do their magic. Whether git is involved at all is hidden from my user model. So if there's something git-y that needs to happen in order for those commands to work, then that ought to just happen.

**Comment by vitorgalvao** [comment]
> I'm just a user of Homebrew, not a developer. So I'm just looking for `update` and `upgrade` to do their magic.

But they are not magic; they are human technology. When they failed for you before, we printed *exactly* (and I’d say clearly) how to fix the error, and you did not follow the instructions.

> Whether git is involved at all is hidden from my user model. So if there's something git-y that needs to happen in order for those commands to work, then that ought to just happen.

Read the issue @EricFromCanada linked you to. [The same question was posed](https://github.com/Homebrew/brew/pull/9383#discussion_r534548401) and [answered](https://github.com/Homebrew/brew/pull/9383#discussion_r534931016).

**Comment by orome** [comment]
@vitorgalvao I understand that it's "human technology", but technology needs to be designed with users — many of whom are dumb and non-technical — in mind. 

If the logic of that comment is what you've settled on, then there are much better ways to implement it — e.g. minimally explaining that it is a one time operation, or wrapping it in a new flag for that does it so it doesn't look so under-the-hood like, say

    To continue using `brew update` first run: `brew update --unshallow` once.

Also: Clarke's Third Law.

**Comment by vitorgalvao** [comment]
> users — many of whom are dumb and non-technical

If a user understands enough of the command-line to use Homebrew; they’re likely capable of understanding that line and running that command.

> there are much better ways to implement it — e.g. minimally explaining that it is a one time operation, or wrapping it in a new flag for that does it so it doesn't look so under-the-hood like, say

I very much doubt this will be a big issue or that most users will care for the reason they need to run that command. That said, if you feel strongly about it you’re free to submit a PR with your recommended improvements so they can be discussed. I can’t promise it will be accepted, but I won’t be the one to refuse it.

> Also: Clarke's Third Law.

Yes, I understood your original point. That doesn’t mean I agree with labelling any technology “magic”. We could even argue that’s detrimental, as it only makes it look even more inaccessible.

**Comment by orome** [comment]
@vitorgalvao FWIW if I run

`git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow`

and then try `brew update` or `brew upgrade` I still get

```
Error: homebrew-core is a shallow clone. To `brew update` first run:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
```

So the suggested command doesn't even work. 

And of I then try the command again (maybe I didn't do it right the first time?) I get

`fatal: --unshallow on a complete repository does not make sense`

**Comment by EricFromCanada** [comment]
You probably mis-read the second suggestion, which likely said to unshallow `homebrew/cask` with `git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch --unshallow`.

**Comment by MikeMcQuaid** [comment]
I've opened https://github.com/Homebrew/brew/pull/9447 to improve the message here.
