### ISSUE TITLE
`brew audit` creates ~/.gem

### ISSUE THREAD

**Issue by penman** [Homebrew/brew#944]
I have `GEM_HOME` set to a non-default location to avoid gems being installed in my home directory. brew.sh unsets this variable, so when <kbd>brew audit</kbd> installs rubocop, this directory is created and gems are installed into a directory that otherwise doesn't exist. This means my gems are spread across two different locations, which doesn't seem like the correct behavior.

I understand that brew.sh unsettling this variable must be deliberate and prevent some bad behaviour, so if this is working as intended that's okay, but it doesn't seem like great behaviour to me.

**Comment by MikeMcQuaid** [comment]
I think we'd accept a PR to e.g. set it to `GEM_OLD_HOME` and then use that value in `brew audit` and `brew tests` if it's set.

**Comment by penman** [comment]
Sweet. I'll get one up shortly.
