### ISSUE TITLE
Universal Build Tools on Apple Silicon

### ISSUE THREAD

**Issue by lunixbochs** [Homebrew/brew#9454]
# A detailed description of the proposed feature

I believe build tools such as CMake and ninja should be compiled and delivered as universal binaries with both x86_64 (not x86_64h) and arm64 slices by default in homebrew, using e.g. `CMAKE_OSX_ARCHITECTURES="x86_64;arm64"`
or the CFLAGS `-arch x86_64 -arch arm`.

I believe this should be the case both with Intel and Apple Silicon targeted Homebrew, as Intel Homebrew is currently more reliable on Apple Silicon.

# The motivation for the feature

It's easier to run native Apple Silicon builds if basic build tools have an Apple Silicon slice even when using Intel homebrew on an Apple Silicon Mac. Builds can also be more performant if tools like ninja are executed through the Apple Silicon slice, as LLVM would otherwise run in the Rosetta emulator.

If your build tools are universal and don't contain `sysctl` processor type checking workarounds, you can build a native version of most projects on Apple Silicon with the standard `cmake .; make` flow. You can also build an x86 version of most projects with an arch override, like `arch -x86_64 cmake .; arch -x86_64 make`. You can then lipo them together and have a universal binary with minimal work.

See also this issue I filed against CMake, where CMake's current `sysctl` workaround for x86_64 CMake makes it more difficult to build some projects (e.g. Pytorch) as x86 on Apple Silicon host: https://gitlab.kitware.com/cmake/cmake/-/issues/21554#note_869690

# How the feature would be relevant to at least 90% of Homebrew users

All Macs will be Apple Silicon soon. Homebrew still has better support for Intel hosts. A universal build of projects like CMake and ninja makes it much nicer during the transition period to compile non-homebrew software (faster builds, easier to compile for a specific architecture when the project's build system is incapable of handling universal builds or arch overrides for some reason), and native build tool slices are currently even required in some cases to build some software as native or universal. 

Working with an x86 homebrew on Apple Silicon, I had to manually build an arm64 + universal `ninja` to be able to compile some software for arm64, and had to use a universal cmake with the sysctl check disabled to build Pytorch for x86.

# What alternatives to the feature have been considered

CMake currently uses a sysctl workaround to force an x86_64 cmake binary to set the processor type as arm64. This works ok for arm64 builds, but makes it very difficult to build the x86 variant of projects that check CMAKE_SYSTEM_PROCESSOR in their CMakeLists (such as Pytorch).

I don't believe ninja has any such alternative, it seems to unilaterally build x86 binaries of stuff (using the x86 llvm slice) if invoked naively with an x86 build of ninja and no compile flag tweaks. It wouldn't make sense for ninja to use the sysctl processor type check to force some kind of arm compilation because then it would be harder for ninja to act as an x86 build tool.

Thus the main alternative to Homebrew implementing this in my eyes, is for me to install build tools like CMake and ninja as universal outside of Homebrew, which is what I am doing now.

**Comment by fxcoudert** [comment]
> Homebrew still has better support for Intel hosts

We are working hard to provide ARM support, and once that happens we will have all the formulas supporting Apple Silicon running natively there.

You paint a very rosy picture, but universal builds open the door to a lot of tricky issues.

**Comment by lunixbochs** [comment]
I'm not talking about homebrew doing universal builds for everything. Just cmake and ninja if and only if the building machine supports -arch x86_64 -arch arm64.

My case for this is that the only reason I can think to `brew install cmake ninja` is the user wants to build a non-brew project, and regardless of whether they have an intel brew or arm brew, these tools will serve the users better in both cases if they are one-off universal.

**Comment by MikeMcQuaid** [comment]
We are not going to bring back universal builds, sorry. We did this in the past and it caused no end of issues for us and we can't feasibly test these. As @fxcoudert mentioned our plan is to support Apple Silicon natively without universal builds.

**Comment by lunixbochs** [comment]
This doesn't solve my problem and seems like a much more general response than what I was asking for.

**Comment by fxcoudert** [comment]
Sadly, we can't solve _all_ the problems. But it seems there are plenty of solutions for you around, either by installing one ARM version and one Intel version, or by using cmake's own universal builds, or by creating your own version, etc.

**Comment by lunixbochs** [comment]
I am already building my own cmake and ninja right now, because this issue renders homebrew unusable for diverse universal app dev workflow on M1.

Seems like I will need to migrate to macports going forward as it looks to have a universal slice option that will cover this use case.

FWIW two instances of arch specific homebrew in different prefixes doesn’t fix this and introduces new problems, because when using arch -x86_64 or arch -arm64, you’ll get “bad cpu type in executable” if anything tries to run a binary where the other arch is first in PATH, even if the binary is available for the current arch later in path. So you would need to both do fine grained path management and make sure you have both slices installed for all of your tools.

**Comment by MikeMcQuaid** [comment]
> Seems like I will need to migrate to macports going forward as it looks to have a universal slice option that will cover this use case.

Yes, it sounds like it.

> So you would need to both do fine grained path management and make sure you have both slices installed for all of your tools.

Yes.
