### ISSUE TITLE
brew‘s auto “Upgrading dependents” mechanism causes uninstalled python@3.9 installed back

### ISSUE THREAD

**Issue by chenzx** [Homebrew/brew#9458]
I'm using python 3.8 on Mac for tensorflow(which can only support up to 3.8), i installed python 3.8 by brew.

However, when i install some package x which seems dependent on latest python 3.9, this causes python 3.8 installed which conflicts with my previously manually installed 3.8

So i uninstalled both 3.8 & 3.9, and then re install 3.8, wierdly and evilly, brew does “Upgrading dependents”  after python 3.8 is installed ok.

I guess if i use the full path "/usr/local/opt/python@3.8/bin/python3" which will not interfere with 3.9? but i cannot directly use python3 in bash shell (i'm set $PATH to /usr/local/bin:/usr/bin ...)

**Comment by chenzx** [comment]
...

==> Summary
🍺  /usr/local/Cellar/python@3.8/3.8.6_2: 4,329 files, 69.4MB
==> Upgrading 5 dependents:
ffmpeg 4.3.1_2 -> 4.3.1_4, ninja 1.10.1_3 -> 1.10.2, pyqt 5.15.1_1 -> 5.15.2, vtk 9.0.1_1 -> 9.0.1_2, opencv 4.5.0_2 -> 4.5.0_5
==> Upgrading ffmpeg 4.3.1_2 -> 4.3.1_4 
==> Downloading https://homebrew.bintray.com/bottles/aom-2.0.1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/ebac8d7473e89b82ad00046243ef47207c0823e410c4d3c40483a81324ad2a4c?response-content-disposition=attachment%3Bfilename%3D%22aom-2.0.1.catalina.bottl
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.2.1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/35e9f82d80708ae8dea2d6b0646dcd86d692321b96effaa76b7fad4d6cffa5be?response-content-disposition=attachment%3Bfilename%3D%22gmp-6.2.1.catalina.bottl
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/c-ares-1.17.1.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/nghttp2-1.42.0_1.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/unbound-1.13.0.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/132e7387adde0939a0f50d125ef5b6bdfa0186bae6dd9628668e9813813f4a9a?response-content-disposition=attachment%3Bfilename%3D%22unbound-1.13.0.catalina.
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.0_4.catalina.bottle.1.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/933ca658fbb4f1a5f63c28c4857e0071e4c759a9dd449f35a7cc3e8e04cf92dd?response-content-disposition=attachment%3Bfilename%3D%22python%403.9-3.9.0_4.cat
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.1.0_1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/d92eb164b8fbe723a6006023f883a77bc02d4e54d8bbb1db6855f1ad7f1f1d6e?response-content-disposition=attachment%3Bfilename%3D%22libtiff-4.1.0_1.catalina
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/libsndfile-1.0.30_1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/8777b541acc126315428bcee3f3453a240157dcdca48d2e51609158ad3539284?response-content-disposition=attachment%3Bfilename%3D%22libsndfile-1.0.30_1.cata
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/x264-r3027_1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/60b2b82a877d14c5c02f28e0d51ae90b89d4a141fa3c4efcc3fed6926d41033a?response-content-disposition=attachment%3Bfilename%3D%22x264-r3027_1.catalina.bo
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-4.3.1_4.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/fa20f49d1650469cc4ea6fe6ef6c8d949106235cec8de9a386dec5839c2bb047?response-content-disposition=attachment%3Bfilename%3D%22ffmpeg-4.3.1_4.catalina.
######################################################################## 100.0%

**Comment by chenzx** [comment]
The problem is, package's dependency management always has version conflicting problem, each time i install a package from network, it cost ```time```.

Tools like brew seems not considering this and always do repeated networking downloads, treating local dev env like a re-writable file system, which is not my favorite...

**Comment by MikeMcQuaid** [comment]
Please fill out the issue template in future.

I have no idea what any issue is here. Please take it to Homebrew/discussions.
