### ISSUE TITLE
bump-formula-pr Error: undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#9462]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew bump-formula-pr --version=10.86.18 netpbm`

## What happened (include command output)

I saw the following error:
```
❯ brew update && brew update && brew doctor
Already up-to-date.
Already up-to-date.
Your system is ready to brew.
❯ brew bump-formula-pr --version=10.86.18 netpbm
Error: undefined method `gsub' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:181:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

<details><summary>Last 15 or so lines of Debug/Verbose Output</summary>
<p>

```
+ safe_cd /usr/local/Homebrew
+ cd /usr/local/Homebrew
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -d /usr/local/Homebrew/Library/LinkedKegs ]]
+ [[ ! -f /Users/chisquared/Library/Caches/Homebrew/all_commands_list.txt ]]
+ [[ -n '' ]]
+ [[ -z 1 ]]
+ exit 0
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/netpbm.rb
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.0-157-g3fc8c70\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.0.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=netpbm\+repo\%3AHomebrew\%2Fhomebrew-core\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --dump-header /private/tmp/github_api_headers20201208-25503-15hyvoz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.0-157-g3fc8c70\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.0.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=netpbm\+10.86.18\+repo\%3AHomebrew\%2Fhomebrew-core\+state\%3Aclosed\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --dump-header /private/tmp/github_api_headers20201208-25503-1hfny8o
Error: undefined method `gsub' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:181:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

</p>
</details>

## What you expected to happen

No errors.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew bump-formula-pr --version=10.86.18 netpbm`

## Output of `brew config` and `brew doctor` commands

<pre>
❯ brew doctor && brew config
Your system is ready to brew.
HOMEBREW_VERSION: 2.6.0-157-g3fc8c70
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3fc8c703f2dfccc09ca32537e20fcdb0411534ea
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 00f3ba291e8735113e6c452044f15b8e3a357922
Core tap last commit: 63 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_COLOR: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_VENDOR_RUBY: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: N/A
</pre>

**Comment by jonchang** [comment]
I actually hit this bug today; this appears to happen when you have an formula that uses an SVN checkout, which typically only have a `revision` argument, not a `tag`.

**Comment by jonchang** [comment]
Perhaps `brew bump-formula-pr` should just fail with an error if the stable url uses an svn checkout.

**Comment by EricFromCanada** [comment]
I'll soon have a fix that handles these cases; specifically, requiring `--revision` to be passed with `--version` if the formula does not specify a `tag:`.
