### ISSUE TITLE
Homebrew is repeatedly downloading and pouring "portable-ruby-2.6.3_2.yosemite.bottle.tar.gz"

### ISSUE THREAD

**Issue by shikibu-z** [Homebrew/brew#9469]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I tried to use `brew update` and `brew cleanup` to do updates. I tend to do update regularly.

## What happened (include command output)
After the last `brew cleanup`, the next `brew update` or `brew upgrade` will install portable-ruby-2.6.3_2.yosemite.bottle.tar.gz, regardless of the downloading and pouring from last time.
```
~ ❯ brew update
Already up-to-date.
~ ❯ brew upgrade
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
Already downloaded: /Users/feketerigo/Library/Caches/Homebrew/portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
==> Pouring portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
~ ❯ brew cleanup

~ ❯ brew update
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
Already downloaded: /Users/feketerigo/Library/Caches/Homebrew/portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
==> Pouring portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
jasper
==> Updated Casks
liya
~ ❯ 
```
It looks like the folder at `/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2` is deleted when running `brew cleanup`. I am not sure if this should be the correct behaviour but repeatedly downloading and pouring this file seems very weird.

## What you expected to happen

Homebrew not doing the same thing repeatedly.

## Step-by-step reproduction instructions (by running `brew` commands)

1. Run `brew update`, `brew upgrade` and `brew cleanup`.
2. Probably wait for 5 seconds if you would like to.
3. Run step 1 again.

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.6.0-174-gddfd499
ORIGIN: https://github.com/Homebrew/brew
HEAD: ddfd499c207e239372df0bdc3de652a5aae3df97
Last commit: 81 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 543de801887ff2b2343a63d58fcbb11e458a5235
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.32.21
Xcode: N/A
</pre>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/feketerigo/opt/anaconda3/bin/icu-config
  /Users/feketerigo/opt/anaconda3/bin/krb5-config
  /Users/feketerigo/opt/anaconda3/bin/freetype-config
  /Users/feketerigo/opt/anaconda3/bin/xslt-config
  /Users/feketerigo/opt/anaconda3/bin/libpng16-config
  /Users/feketerigo/opt/anaconda3/bin/python3.7-config
  /Users/feketerigo/opt/anaconda3/bin/libpng-config
  /Users/feketerigo/opt/anaconda3/bin/xml2-config
  /Users/feketerigo/opt/anaconda3/bin/python3.7m-config
  /Users/feketerigo/opt/anaconda3/bin/python3-config
  /Users/feketerigo/opt/anaconda3/bin/curl-config
  /Users/feketerigo/opt/anaconda3/bin/ncursesw6-config
  /Users/feketerigo/opt/anaconda3/bin/pybind11-config
  /Users/feketerigo/opt/anaconda3/bin/pcre-config

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
</pre>

**Comment by carlocab** [comment]
Something similar happens to me, too. However, I can't pin down when exactly `brew` decides to pour a `portable-ruby` bottle. All I know is that it does this (and install a lot of gems when I do something like `brew audit`) at least once a day.

Trying the commands in the repro steps don't do it for me. In case it's useful:
```
❯ brew config && brew doctor
HOMEBREW_VERSION: 2.6.0-174-gddfd499
ORIGIN: https://github.com/Homebrew/brew
HEAD: ddfd499c207e239372df0bdc3de652a5aae3df97
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 543de801887ff2b2343a63d58fcbb11e458a5235
Core tap last commit: 21 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_COLOR: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_VENDOR_RUBY: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: N/A
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
```

**Comment by dawidd6** [comment]
@shikibu-z could you please run:

```
brew update
brew cleanup --dry-run
```

and paste the output here?

**Comment by shikibu-z** [comment]
The output looks like this:
```
~ ❯ brew update
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
cargo-instruments          cpmtools                   istioctl                   swiftformat                terraform
==> Updated Casks
omniplan
~ ❯ brew cleanup --dry-run
Would remove: /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2 (1,394 files, 25.7MB)
```

**Comment by bdielman** [comment]
I saw the same after running `brew update` (also, why is it downloading the Yosemite bottle if I'm running Catalina?):

```
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
```

After this I tried running `brew upgrade` and received this message (which I have never seen before):

```
Error: homebrew-core is a shallow clone. To `brew update` first run:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
```

**Comment by EricFromCanada** [comment]
> why is it downloading the Yosemite bottle if I'm running Catalina?

The portable ruby bottle is compiled on the minimum version of macOS that Homebrew will run on. 

> and received this message (which I have never seen before):

https://github.com/Homebrew/brew/pull/9383
