### ISSUE TITLE
brew.sh should use HTTPS

### ISSUE THREAD

**Issue by micahflee** [Homebrew/brew#948]
To install Homebrew you're supposed to copy and paste some code from http://brew.sh/ into your terminal. This website should use HTTPS so that an attacker can't modify the command to copy and paste.

**Comment by zmwangx** [comment]
brew.sh is a GitHub Pages site with a custom domain and currently it's hard to support HTTPS on such sites. See also https://github.com/Homebrew/homebrew.github.io/issues/98.

There are instructions for the security-minded linked on the homepage too: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Installation.md#installation.

**Comment by micahflee** [comment]
Ahh, I see this has been discussed quite a bit elsewhere already.
