### ISSUE TITLE
Running `brew install --cask formula` does not tap `homebrew/cask`

### ISSUE THREAD

**Issue by pgrenaud** [Homebrew/brew#9485]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

While provisioning a new macbook, I was unable to install a cask using the command `brew install --cask formula`. After trying few formulae, I notice that `homebrew/cask` was not tapped and running `brew cask install formula` would actually tapped `homebrew/cask`.

[I switch the the new cask syntax according to the 2.6.0 release notes.](https://brew.sh/2020/12/01/homebrew-2.6.0/) I also got the deprecation warning when running the second command. Therefore, I believe that running `brew install --cask formula` should tap `homebrew/cask` like `brew cask install formula` does.

## What happened

<pre>
% brew install --cask betterzip
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

Error: Cask 'betterzip' is unavailable: No Cask with this name exists.

% brew cask install betterzip
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 107, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 577551 (delta 65), reused 27 (delta 10), pack-reused 577444
Receiving objects: 100% (577551/577551), 240.74 MiB | 41.07 MiB/s, done.
Resolving deltas: 100% (411097/411097), done.
Tapped 1 command and 3752 casks (3,871 files, 259MB).
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
==> Downloading https://macitbetter.s3.amazonaws.com/BetterZip-5.0.3.zip
######################################################################## 100.0%
==> Installing Cask betterzip
==> Moving App 'BetterZip.app' to '/Applications/BetterZip.app'.
🍺  betterzip was successfully installed!
</pre>

## What you expected to happen

Something along these lines:

<pre>
% brew install --cask betterzip
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 107, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 577551 (delta 65), reused 27 (delta 10), pack-reused 577444
Receiving objects: 100% (577551/577551), 240.74 MiB | 41.07 MiB/s, done.
Resolving deltas: 100% (411097/411097), done.
Tapped 1 command and 3752 casks (3,871 files, 259MB).
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
==> Downloading https://macitbetter.s3.amazonaws.com/BetterZip-5.0.3.zip
######################################################################## 100.0%
==> Installing Cask betterzip
==> Moving App 'BetterZip.app' to '/Applications/BetterZip.app'.
🍺  betterzip was successfully installed!
</pre>

## Step-by-step reproduction instructions

<pre>
% /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
% brew install --cask betterzip
</pre>

## Output of `brew config` and `brew doctor` commands

<pre>
% brew config
HOMEBREW_VERSION: 2.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1d5e354cc2ff048bd7161d95b3fa7f91dc9dd081
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6ba537d26f19bca9345a95447b6bdaacb3684964
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.2.0.0.1.1604628099
Xcode: N/A

% brew doctor
Your system is ready to brew.
</pre>

**Comment by MikeMcQuaid** [comment]
@pgrenaud Can you try to `brew update`? I think we literally just rolled out a new release with a fix for this.

**Comment by pgrenaud** [comment]
@MikeMcQuaid I tried when I got the issue an hour-ish ago, but no luck then. I can try again now, but what's the best way to test this? Do I need to just untap `homebrew/cask` or is it more complicated than that?

**Comment by MikeMcQuaid** [comment]
@pgrenaud `brew untap homebrew/cask; brew install --cask betterzip`

**Comment by pgrenaud** [comment]
Ref: https://github.com/Homebrew/brew/pull/9398

**Comment by MikeMcQuaid** [comment]
@pgrenaud Did that PR fix it for you?

**Comment by pgrenaud** [comment]
> @pgrenaud brew untap homebrew/cask; brew install --cask betterzip

Just did that and it worked. Well, it seems that I was unlucky with my timing! 😅

> @pgrenaud Did that PR fix it for you?

Yep!

Thanks again!
