### ISSUE TITLE
No Homebrew ruby 2.6.3_2 available for arm64 processors!

### ISSUE THREAD

**Issue by Wenyueh** [Homebrew/brew#9487]
I have a new macOS M1 with ARM processor. I install homebrew with:

`
% cd /opt
% mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
% sudo chown -R $(whoami) /opt/homebrew
`
Then I export the PATH. Finally i try brew install something or brew update, I got the error
Error: No Homebrew ruby 2.6.3_2 available for arm64 processors!

How should I deal with that?

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

See also: #7857
