### ISSUE TITLE
brew install openresty

### ISSUE THREAD

**Issue by gaobinzhan** [Homebrew/brew#9497]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew install openresty`

## What happened (include command output)

```
Warning: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.

$ softwareupdate --list
Software Update Tool

Finding available software

No new software available. 
```

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Output of `brew config` and `brew doctor` commands

<pre>

</pre>

**Comment by gaobinzhan** [comment]
`sudo rm -rf /Library/Developer/CommandLineTools && sudo xcode-select --install`

**Comment by MikeMcQuaid** [comment]
> Warning: You are using macOS 11.0.
> We do not provide support for this pre-release version.
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC. You are responsible for resolving any issues you
> experience while you are running this pre-release version.

Read this and please don't create more issues.
