### ISSUE TITLE
Brew update should be verbose by default

### ISSUE THREAD

**Issue by neilpanchal** [Homebrew/brew#9498]
# A detailed description of the proposed feature

When running `brew update`, I see no reason to not have `-v` or `--verbose` flag as a default. 

# The motivation for the feature
Studies have shown that even "fake" progress bars lead to better user experience. 

Everytime I run `brew update`, I wait in anxiety whether it is stuck or its doing something. Brew is very slow to update and not giving any feedback is painful. 

Verbose doesn't print a lot of stuff so I don't see why this shouldn't be the default.

# How the feature would be relevant to at least 90% of Homebrew users

Providing feedback is always better than not providing any. Brew users are developers and people who now how to deal with a little bit of verbosity.

# What alternatives to the feature have been considered

Alternative is a worse user experience.

**Comment by tobylane** [comment]
Disagree. 

I believe it's relevant here. I would like to be able to collapse the list of updated formulae and casks to the number count, or not, regardless of how many there are. Also an option to only show the installed ones.

**Comment by carlocab** [comment]
You can set verbose output by default using the environment variable `HOMEBREW_VERBOSE`. (Say, with `export HOMEBREW_VERBOSE=1`.)

Admittedly, it doesn't give you the granularity of verbose output only with `brew update`, but you can sort that out by wrapping `brew` in a function or a script.

**Comment by MikeMcQuaid** [comment]
> Disagree.

I'm unsurprised, therefore: closing.



> Also an option to only show the installed ones.

This exists: `HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED`. It's in `man brew`.
