### ISSUE TITLE
codesign on ARM requires CLT or Xcode to sign binaries

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#9525]
1. On Apple Silicon, we use `codesign` to provide an _ad hoc_ signature to the MachO files we pour from bottles, after rewriting them (binaries and shared libraries)
2. `codesign` is present at `/usr/bin/codesign` on base macOS (without Xcode or CLT)
3. But that version can only **verify** signatures, not sign MachO files. Signing requires `codesign_allocate` to be installed, which is called by `codesign`, and is part of Xcode or CLT.
4. Therefore, we cannot reliably pour bottles for Apple Silicon unless we have CLT or Xcode installed.

This leads to very bad user experience. Moreover, it also happens with brew-downloaded git bottles for ARM (now that we have them): leading to horrible user experience. https://github.com/Homebrew/brew/issues/7857#issuecomment-743580890

As a long-term solution, we could imagine having ruby-macho providing a pure-ruby signing mechanism. That would be ideal, but the first implementation had problems. poking @woodruffw on that

As a short-term solution, we need to:
- bail out early when neither CLT nor Xcode is installed on ARM
- in that case, tell users to install the CLT

**Comment by fxcoudert** [comment]
As for the reason why this happened: the user reports that installing the 11.1.0 RC uninstalled their previously installed CLT 😢

**Comment by SMillerDev** [comment]
As far as I remember, enrolling in betas that don't have a CLT version available will remove the CLT. Just like installing a normal update will usually have an update for the CLT as well. All brew installs need a CLT or XCode though, so I think aborting with a failure is the friendliest thing to do.

**Comment by mbirth** [comment]
Funny thing: The CLT is downloadable from the Developer Website, it's just not in their software repository.

**Comment by carlocab** [comment]
Not too surprising: it's still only RC, and not yet fully supported.

**Comment by johnalanwoods** [comment]
@fxcoudert, so as we know, HB installs CLT on initial install.

So, this will only affect users who are savvy enough to beta test macOS/RCs, (where the CLT might be removed). 

I don't see this as a huge issue, don't you agree? In all circumstances home-brew would have installed CLT on any stable macOS release prior to use.

**Comment by mbirth** [comment]
Just to remind you guys: "RC"s are what were "GM"s before - basically the release version, only a few days earlier. So it's not so weird for people to upgrade to an RC version if they don't want to wait hours for the download to complete on release day.

**Comment by carlocab** [comment]
>basically the release version, only a few days earlier

I think "basically" and "earlier" are keywords here: there are still some features that distinguish it from the released version, and that makes it not fully supported.

>it's not so weird for people to upgrade to an RC version if they don't want to wait hours for the download to complete on release day

I agree. But the price you pay for avoiding (among other things) the download wait on release day is that you get a piece of software that doesn't have the same guarantees as to the released version. One of those is the availability of CLT via `softwareupdate`. The workaround isn't difficult; though perhaps `brew` could generate more informative error messages here (which is actually part of the suggested short-term solution in the OP).

**Comment by SMillerDev** [comment]
> Just to remind you guys: "RC"s are what were "GM"s before - basically the release version, only a few days earlier.

And they aren't supported by brew as `brew doctor` will/should tell you. 

The developer previews of macOS 12 will also be like the release version, just a few months earlier and with bugs that might still be fixed later.

**Comment by gibfahn** [comment]
As the installer installs the CLT anyway:

https://github.com/Homebrew/install/blob/e141d766960553367441362490e42a2fead644c6/install.sh#L541

and it's already listed as a requirement in the installation instructions: https://docs.brew.sh/Installation

it seems reasonable to assume everyone will always have it and thus always do the `MacOS::CLT.installed?` check:

https://github.com/homebrew/brew/blob/77561fccc2a7536c1b554867362cd015d7c55bdd/Library/Homebrew/os/mac/xcode.rb#L233

(I have also been hit by this when upgrading to RCs, feels like an issue to raise with Apple via https://feedbackassistant.apple.com/ rather than brew though)

**Comment by fxcoudert** [comment]
For @woodruffw or whoever is willing to implement this in ruby: Go has made its own implementation, see https://github.com/golang/go/blob/master/src/cmd/internal/codesign/codesign.go

The small details of the implementation are discussed at length in the two linked issues: https://github.com/golang/go/issues/42684 and https://github.com/golang/go/issues/38485

**Comment by carlocab** [comment]
Upgrading to 11.1 gets rid of CLT. `xcode-select --install` now works, however.

**Comment by johnalanwoods** [comment]
It doesn't remove the CLT, you just need to select it again in Xcode prefs (or execute a path switch). ![Uploading 102193907...]

**Comment by carlocab** [comment]
Xcode prefs? I’m afraid I can’t do that since I don’t have Xcode installed...

**Comment by johnalanwoods** [comment]
@carlocab, still don't need to reinstall.
You just need to select the path for the CLT again.

`sudo xcode-select -switch /Library/Developer/CommandLineTools`

**Comment by fxcoudert** [comment]
@johnalanwoods it may depend on the circumstances, because on our CI machines, the update to 11.1 definitely removed the CLT entirely.

**Comment by carlocab** [comment]
Yep, it definitely removed CLT in my case. When CLT is installed, this happens:
```
❯ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
Predictably, that is not the error message I saw when I ran it after upgrading to 11.1.
