### ISSUE TITLE
Changing the DYLIB ID of the native compiled Elisp code breaks the dylib

### ISSUE THREAD

**Issue by daviderestivo** [Homebrew/brew#9526]
# Bug report

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm currently maintaining a brew formula for GNU/Emacs. Since some time a new branch of Emacs is being develped allowing LISP code compilation into native code (dylibs). More details here: http://akrl.sdf.org/gccemacs.html

I'm trying to modify my formula in order to support this new feature (native-comp branch) of GNU/Emacs HEAD. The installation is successful but it seems that after the "install" phase homebrew changes the DYLIB ID of the native compiled Elisp code breaking someway those libraries:

```
==> Changing dylib ID of /usr/local/Cellar/emacs-head@28/28.0.50_1/Emacs.app/Contents/native-lisp/28.0.50-x86_64-apple-darwin19.6.0-280c4c724fff373c5b7192112ad4147c/PY-b5-9da27250173071085086a7aed29fd29d-7a2e0ead8fc81e02717b53d465b7c866.eln 
  from /private/tmp/libgccjit-3EU2CE/fake.so 
    to /usr/local/opt/emacs-head@28/Emacs.app/Contents/native-lisp/28.0.50-x86_64-apple-darwin19.6.0-280c4c724fff373c5b7192112ad4147c/fake.so 
==> Changing dylib ID of /usr/local/Cellar/emacs-head@28/28.0.50_1/Emacs.app/Contents/native-lisp/28.0.50-x86_64-apple-darwin19.6.0-280c4c724fff373c5b7192112ad4147c/PY-df2668c28394ecb13448539e114796c3-49c85c7a1e624e4fcb832e0ae1789cce.eln 
  from /private/tmp/libgccjit-MdVbDk/fake.so 
    to /usr/local/opt/emacs-head@28/Emacs.app/Contents/native-lisp/28.0.50-x86_64-apple-darwin19.6.0-280c4c724fff373c5b7192112ad4147c/fake.so 
==> Changing dylib ID of /usr/local/Cellar/emacs-head@28/28.0.50_1/Emacs.app/Contents/native-lisp/28.0.50-x86_64-apple-darwin19.6.0-280c4c724fff373c5b7192112ad4147c/Punct-9d38e5d98c73f73af49bda4ce95ce922-b334c1a512d9d6beda163f5975881cb6.eln 
  from /private/tmp/libgccjit-sjtPHL/fake.so 
```

## What happened (include command output)

Emacs does not start.

<details>
  <summary>Command output</summary>
  <pre>
emacs -Q 
emacs: can't find function "F656c646f632d646f63756d656e746174696f6e2d64656661756c74_eldoc_documentation_default_0" in compilation unit /usr/local/Cellar/emacs-head@28/28.0.50_1/Emacs.app/Contents/MacOS/../native-lisp/28.0.50-x86_64-apple-darwin19.6.0-280c4c724fff373c5b7192112ad4147c/eldoc-d20a5fe96630926dde4deb5e10fdceb0-660cfdc64f0992e89ba750c634991e2c.eln 
gutter@nemesis ~/Documents/github-repos/homebrew-emacs-head $ otool /usr/local/Cellar/emacs-head@28/28.0.50_1/Emacs.app/Cont
  </pre>
</details>

## What you expected to happen

Emacs to start succesuffly

## Step-by-step reproduction instructions (by running `brew install` commands)

If I  put `system "false"` at the end of install function, but after `make install` and `prefix.install "nextstep/Emacs.app"`  then brew does not change the dylib ID of the Elisp libraries and Emacs start successfully

`$ /usr/local/Cellar/emacs-head@28/28.0.50/Emacs.app/Contents/MacOS/Emacs -Q`

Full logs can be found [here](https://gist.githubusercontent.com/daviderestivo/e6e519bec585285595fa4cac11c9c6dd/raw/646e0a20bcd6cd57ece674c26a22834aa58e9440/emacs-native-comp-fail01.txt%2520Secret)

**Comment by d12frosted** [comment]
Experience very same issue [here][1]. Thank you @daviderestivo for reporting.

  [1]: https://github.com/d12frosted/homebrew-emacs-plus/pull/188#issuecomment-735420741

**Comment by simonomis** [comment]
I did a bit of digging into this and found that it's the `fix_dynamic_linkage` method in `keg_relocate.rb` that's changing the dylib_id: https://github.com/Homebrew/brew/blob/b0a3b60292b7919f22a43d40e786ef35562d22df/Library/Homebrew/extend/os/mac/keg_relocate.rb#L64

So, based on the assumption that "normal" dylibs will have `dylib_id`s rooted in the cellar rather than the temp build directory, I added a check to that line to skip the call to `change_dylib_id` if the `dylib_id` is rooted in the temp directory:

```ruby
        change_dylib_id(dylib_id_for(file), file) if file.dylib? &&
                                                  file.dylib_id.start_with?("/") &&
                                                  !file.dylib_id.start_with?(HOMEBREW_TEMP.to_s) &&
                                                  !file.dylib_id.start_with?(HOMEBREW_TEMP.realpath.to_s)
```

That seems to have solved the issue - I can see from the debug logs that the id is not being changed, and the built Emacs.app starts without issues.

But the question is whether that's a safe assumption to make about "normal" dylibs, and whether there are any other unintended consequences. What's the best way to validate that it doesn't break other formulae?

**Comment by daviderestivo** [comment]
@simonomis thanks for the suggested fix. I think you're assumption "dylib_ids rooted in the cellar rather than the temp build " is in general valid so the proposed fix in general should not harm.

**Comment by simonomis** [comment]
Great, thanks @daviderestivo. I had some failing tests that were worrying me, but it looks like they're unrelated to this change so I'm going to go ahead and create a PR for it

**Comment by d12frosted** [comment]
@simonomis wow, thanks for your work! sounds promising. can't wait to get your PR and test if it works :)

**Comment by daviderestivo** [comment]
@simonomis Thanks :) ... I hope to see your PR approved soon 👍

**Comment by daviderestivo** [comment]
I have tried to change the .eln files dylib ID before post-install phase and it seems to be working. Probably I could use it as a workaround before we find a more nicer solution:

```
Dir.glob(contents_dir/"native-lisp/*/*.eln").each do |f|
  fo = MachO::MachOFile.new(f)
  ohai "Change dylib_id of: " + f
  fo.dylib_id = "#{contents_dir}/" + f
  fo.write!
end
```
