### ISSUE TITLE
qt5 bottle

### ISSUE THREAD

**Issue by maraflush** [Homebrew/brew#9532]
Hello,

Could you add some bottle the oldest osx for the bottle (and not forget the qt update) :
- high sierra
- sierra
- el capitan

Because the compilation time are just insane !
By advance,

Thanks

**Comment by gromgit** [comment]
I'm pretty sure that's not gonna happen, as the earliest OS available in CI is now Mojave.

**Comment by carlocab** [comment]
Yes, sorry. Homebrew's build and testing systems are only running Mojave, Catalina, and Big Sur, so I'm afraid those bottles would be impossible.

**Comment by maraflush** [comment]
Ok could you redirect me for a doc which explains how to build the bottle via GitHub ? 

Regards,

**Comment by gromgit** [comment]
You're probably looking for [**GitHub Actions**](https://docs.github.com/en/free-pro-team@latest/actions), about which I know next to nothing.

Even then, GitHub only offers Actions [for Catalina at the earliest](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#github-hosted-runners). Homebrew [uses its own CI hardware](https://docs.brew.sh/Brew-Test-Bot), so is able to provision back to Mojave.

**Comment by carlocab** [comment]
You can have a look at this: https://brew.sh/2020/12/01/homebrew-2.6.0/

However, as @gromgit points out, they only document support for Catalina and Big Sur. However, digging into their [repo](https://github.com/actions/virtual-environments) suggests that they might have nodes that run High Sierra and Mojave. This is not documented, so may not work.

**Comment by maraflush** [comment]
Thank you for all :)
