### ISSUE TITLE
All Star Eyes 🤩 

### ISSUE THREAD

**Issue by MarymagdalenaX86** [Homebrew/brew#9534]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Output of `brew config` and `brew doctor` commands

<pre>

</pre>

**Comment by MarymagdalenaX86** [comment]
> 
![30F39CB5-FD3D-47D8-9094-7A73CCFFE379](https://user-images.githubusercontent.com/56799905/102018004-809a7080-3d38-11eb-823f-68595bccdf12.jpeg)

**Comment by iMichka** [comment]
I added this user (bot) to the block list.
