### ISSUE TITLE
[Q] What is the rationale for externally managing Python dependencies?

### ISSUE THREAD

**Issue by a13xb** [Homebrew/brew#959]
Let's say I have a Python package that properly lists and pins its dependencies in `setup.py`. But with the way Homebrew manages Python dependencies, it's required to list them as resources in the formula, effectively duplicating dependencies list.

Right now `pip_install` runs pip with `--no-deps` and there is no way to side-step it, short of reimplementing [some Homebrew logic](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/python.rb).

Is this the only officially blessed way to handle dependencies? Is there a way to lean on dependency list in `setup.py` that I can't see?

**Comment by zmwangx** [comment]
We try hard to not have random unchecksummed downloads during build stage which is a security risk, simple as that.

It's easy to generate resource blocks from setup.py. See https://github.com/tdsmith/homebrew-pypi-poet from Tim, Python expert in our team. More info in https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md.

If you disagree, just install your stuff with pip in separate virtualenvs. That's another way to get sandboxed utilities, and the end result is pretty much the same as brew'ed Python packages anyway, except you need to worry about versioning yourself.

**Comment by zmwangx** [comment]
Please ask if the explanation is not clear.
