### ISSUE TITLE
you-get failed to build on macOS 10.12.

### ISSUE THREAD

**Issue by ttivan** [Homebrew/brew#960]
please see the detail info in the follow link:

https://gist.github.com/anonymous/010ddb0e65d1f944f0ed072bfc4c4744

**Comment by zmwangx** [comment]
I can't reproduce. Try `brew reinstall python3` maybe.

**Comment by tdsmith** [comment]
Concur with @zmwangx.

**Comment by jonct** [comment]
IMHO, mounting evidence that the new [CLT warning](https://github.com/Homebrew/brew/pull/965) in `brew doctor` should include Sierra.

**Comment by ttivan** [comment]
I try "brew reinstall python3" first，then use "sudo pip3 install you-get" to install you-get.  Success !!
3Q all

**Comment by tdsmith** [comment]
NB to anyone from the future: please don't use sudo; it'll make it hard to remove later.
