### ISSUE TITLE
bash reporting brew_bash_completion.sh as missing

### ISSUE THREAD

**Issue by kyleterry** [Homebrew/brew#97]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

After running a brew updata/upgrade, my shell started returning this error when a new session is opened:

```bash
-bash: /usr/local/Library/Contributions/brew_bash_completion.sh: No such file or directory
```

**Comment by kyleterry** [comment]
This was caused by something a script on my machine was souring from my .bashrc. Closing.

**Comment by sandroqz** [comment]
Hi. I think you should open this issue again. Same error here. No ideia what's going on.

**Comment by sandroqz** [comment]
Well, I think brew_bash_completion.sh doesn't exist anymore.
Can't find it with `sudo find / -type f -name brew_bash_completion.sh`
But... why?!

**Comment by DomT4** [comment]
Homebrew's `bash` completion is now in `HOMEBREW_PREFIX/etc/bash_completion.d` as simply `brew`.

**Comment by sandroqz** [comment]
Yeah! Tkz @DomT4! 😄
