### ISSUE TITLE
UX Feature request: Warn on invalid args

### ISSUE THREAD

**Issue by MatzFan** [Homebrew/brew#976]
Currently `brew install foo --with-bar` silently ignores `--with-bar` if it is not listed among the valid formula args - even in verbose mode. E.g. I just learned this to my cost with `brew install gdal --with-postgres` (not `--with-postgresql` 😞 ).

Would it be desirable/feasible when parsing formula build args to warn if an invalid option is encountered? Just a simple `'--with-bar' is not a valid install option, do you wish to proceed?` would do to help save us dumb users from such typos..

**Comment by zmwangx** [comment]
https://github.com/Homebrew/legacy-homebrew/issues/8937

"Closing old usability issues in favour of pull requests."

**Comment by MatzFan** [comment]
Thanks for the history lesson! Agree that a PR is way to go here. If I want it that much I'll submit one myself.

**Comment by zmwangx** [comment]
You could also submit an evolution proposal here: https://github.com/Homebrew/brew-evolution

Prepare to be invested though, it won't be like a casual feature request.

**Comment by MatzFan** [comment]
Awesome, thx

**Comment by bfontaine** [comment]
This is something that would be great but as written in https://github.com/Homebrew/legacy-homebrew/issues/8937 would require significant work.
