### ISSUE TITLE
Homebrew Cannot Update, Doctor, Unlink, etc.

### ISSUE THREAD

**Issue by stonemirror** [Homebrew/brew#991]
### Bug reports:

I ran a `brew update` yesterday unproblematically. Today, no matter what I try to do, I'm getting the following response:

```
Error: Could not symlink bin/easy_install
Target /usr/local/bin/easy_install
is a symlink belonging to python. You can unlink it:
  brew unlink python

To force the link and overwrite all conflicting files:
  brew link --overwrite python3

To list all files that would be deleted:
  brew link --overwrite --dry-run python3
```

Executing any of the `brew link` or `brew unlink` commands results in the same error. Removing the symlink and rerunning the command gives the same error; the symlink file reappears after any such attempt. I get the same error in response to a `brew doctor` command. I'm kind of at a loss here.

I also attempted the following:

```
chown -R $USER:admin /usr/local
cd /usr/local
git reset --hard origin/master
brew update
```

which, again, resulted in the same error.

I've made no changes since yesterday _except_ that I upgraded my copy of Xcode (and the Xcode command line tools), so I'm guessing that's what might be responsible somehow. Any suggestions as to how I might produce better information on what's going on here would be welcome...

**Comment by zmwangx** [comment]
Please `rm -rf /usr/local/Library/LinkedKegs` and that should get you back on your feet again. Sorry.

**Comment by stonemirror** [comment]
Thanks, but I'm receiving the same error:

```
<<mcfate::local>> $ rm -rf /usr/local/Library/LinkedKeg
<<mcfate::local>> $ brew update
Error: Could not symlink bin/easy_install
Target /usr/local/bin/easy_install
is a symlink belonging to python. You can unlink it:
  brew unlink python

To force the link and overwrite all conflicting files:
  brew link --overwrite python3

To list all files that would be deleted:
  brew link --overwrite --dry-run python3
<<mcfate::local>> $
```

**Comment by zmwangx** [comment]
Please attach `--debug` to `brew update`.

**Comment by enriquefernandez** [comment]
I was having a similar issue and just run `rm -rf /usr/local/Library/LinkedKegs`

What is that supposed to do?
Do I need to "refix" that somehow?

I don't think I've updated Xcode, so I don't really know why this happened...

**Comment by stonemirror** [comment]
I've posted a gist of the debug output [here](https://gist.github.com/stonemirror/ba24e9cdf851ddc63bce1d8a470afb2c)...

**Comment by zmwangx** [comment]
@enriquefernandez

First, did that fix the problem for you?

We're migrating `/usr/local/Library/LinkedKegs` to `/usr/local/var/homebrew/linked` (and `/usr/local/Library/PinnedKegs` to `/usr/local/var/homebrew/pinned` for that matter) and unfortunately there were bugs in migration code that had done damage that is hard to remedy within brew without a lot of complication.

> rm -rf /usr/local/Library/LinkedKegs
> 
> What is that supposed to do?

Blow away the old directory that somehow failed to migrate.

> Do I need to "refix" that somehow?

You may need to `brew unlink $(brew ls); brew link $(brew ls)` to restore keg links in `/usr/local/var/homebrew/linked` (ignore the keg-only warnings).

**Comment by zmwangx** [comment]
@stonemirror Could you try `cd /usr/local; git fetch; git reset --hard origin/master`?

**Comment by publicarray** [comment]
@zmwangx thanks that worked. It did fail on rake and python for some reason. I fixed it by reinstalling them.

**Comment by stonemirror** [comment]
Okay, I seem to be getting closer to something that's working; I got an `Already up-to-date` response from `brew update` and I'm running a `brew upgrade` now, which seems to be working. I think I may have to uninstall and reinstall python3, but that's do-able.

**Comment by zmwangx** [comment]
@publicarray Those appear to be conflicting files from multiple formulae. For instance, in OP's case, `python3` is trying to link its `bin/easy_install` while it should only have `bin/easy_install-3.5`, so I'm not exactly sure what's going on. Maybe not the latest version; or maybe it was built with some not heavily-tested options.

**Comment by enriquefernandez** [comment]
It partially solved my issues. Brew commands now work and I can update and install new things.

When running `brew unlink $(brew ls); brew link $(brew ls)` I'm getting errors about homebrew not being able to create symlinks.

Example:

```
Error: Could not symlink lib/pkgconfig/eigen3.pc
Target /usr/local/lib/pkgconfig/eigen3.pc
already exists. You may want to remove it:
  rm '/usr/local/lib/pkgconfig/eigen3.pc'

To force the link and overwrite all conflicting files:
  brew link --overwrite eigen

To list all files that would be deleted:
  brew link --overwrite --dry-run eigen
```

After running `brew link --overwrite --dry-run eigen` now I'm getting the same with  `gfortran`:

```
Error: Could not symlink bin/gfortran
Target /usr/local/bin/gfortran
is a symlink belonging to gcc. You can unlink it:
  brew unlink gcc

To force the link and overwrite all conflicting files:
  brew link --overwrite gfortran

To list all files that would be deleted:
  brew link --overwrite --dry-run gfortran
```

**Comment by zmwangx** [comment]
@stonemirror Good to hear, let us know if you're hitting other errors (other than conflicting links, which usually means you either have stale links that you could safely remove, or for some reason you have conflicting files from multiple formulae, which you should try to resolve by reinstalling the formula at question first).

**Comment by zmwangx** [comment]
@enriquefernandez Yeah unfortunately you have to resolve them one at a time, each time followed by a rerun of `brew link $(brew ls)`.

`brew list | xargs -n1 brew link` might help ease the process (you only need to run that once), but you'll need to pick out the errors from a stream of output and resolve them.

**Comment by enriquefernandez** [comment]
Solved! (sorry, updated my previous comment before seeing your reply)

**Comment by zmwangx** [comment]
@enriquefernandez As for `gfortran` in particular, it's a stale formula you have and you should probably just `brew uninstall --force gfortran`. It's now provided as part of gcc.

**Comment by zmwangx** [comment]
@enriquefernandez Glad to hear.

**Comment by stonemirror** [comment]
Yeah, I've uninstalled and reinstalled python3 after my science/opencv upgrade failed, and rerun the `brew upgrade --all`. Seems to be working again, or at least the problems at this point seem to be OpenCV's, not Homebrew's... 😆 

I'll close this, thanks for the help, @zmwangx!

**Comment by zmwangx** [comment]
Let's leave this open for a while actually for visibility.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/brew/pull/992 or similar will hopefully address this case a bit better.

**Comment by publicarray** [comment]
It might be beneficial to change the title from "since Xcode update" to LinkedKegs move or something similar to avoid comment confusion with #972

**Comment by zmwangx** [comment]
Edited title to uncouple from Xcode update.

**Comment by ashfurrow** [comment]
Running `brew update` twice fixed it for me (was seeing this on CI), thanks @zmwangx for adding that solution to the top of the discussion :+1:

**Comment by zmwangx** [comment]
Affected folks have probably sought (and hopefully found) help already. Closing.
