### ISSUE TITLE
Brew returns same error after different comands

### ISSUE THREAD

**Issue by kpashka** [Homebrew/brew#995]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

I was experimenting with switching Ansible versions via [Homebrew-versions](https://github.com/Homebrew/homebrew-versions), and it was working good, but today I've suddenly encountered this:

```
➜  FoxComm brew install docker-for-mac 
Error: No such file or directory - (../../../Cellar/ansible/2.1.1.0, /usr/local/var/homebrew/linked/ansible)
Error: No such file or directory - (../../../Cellar/ansible/2.1.1.0, /usr/local/var/homebrew/linked/ansible)
➜  FoxComm brew cask update
Error: No such file or directory - (../../../Cellar/ansible/2.1.1.0, /usr/local/var/homebrew/linked/ansible)
➜  FoxComm brew update
Error: No such file or directory - (../../../Cellar/ansible/2.1.1.0, /usr/local/var/homebrew/linked/ansible)
➜  FoxComm cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
HEAD is now at eb23a39 utils: remove bad symlink if it already exists.
Error: No such file or directory - (../../../Cellar/ansible/2.1.1.0, /usr/local/var/homebrew/linked/ansible)
➜  local git:(master) brew doctor
Error: No such file or directory - (../../../Cellar/ansible/2.1.1.0, /usr/local/var/homebrew/linked/ansible)
```

**Comment by zmwangx** [comment]
Please run `brew update --debug` twice.

**Comment by kpashka** [comment]
@zmwangx Sorry, I've accidentally fixed this by running:

```
mkdir -p /usr/local/var/homebrew/linked
ln -s /usr/local/bin/ansible /usr/local/var/homebrew/linked/ansible
brew unlink ansible
```

I've tried to rollback to previous error state by deleting symlink, but can't reproduce it now, everything works correctly.

**Comment by zmwangx** [comment]
Good to hear, sorry about breaking things. For reference what you hit was #991.
