### ISSUE TITLE
Brew throwing error no such file or directory for awscli package

### ISSUE THREAD

**Issue by johnib** [Homebrew/brew#997]
This is what I get all of a sudden.
I have done nothing that has to do with `awscli`.
I wanted to upgrade my `git` version and this suddenly happened.
A restart did not help.

Can anyone save me?

```
Jonathans-MacBook-Air:~ johni$ brew update
Error: No such file or directory - (../../../Cellar/awscli/1.10.28, /usr/local/var/homebrew/linked/awscli)

Jonathans-MacBook-Air:~ johni$ brew doctor
Error: No such file or directory - (../../../Cellar/awscli/1.10.28, /usr/local/var/homebrew/linked/awscli)

Jonathans-MacBook-Air:~ johni$ brew install awscli
Error: No such file or directory - (../../../Cellar/awscli/1.10.28, /usr/local/var/homebrew/linked/awscli)
Error: No such file or directory - (../../../Cellar/awscli/1.10.28, /usr/local/var/homebrew/linked/awscli)

Jonathans-MacBook-Air:~ johni$ brew uninstall awscli
Error: No such file or directory - (../../../Cellar/awscli/1.10.28, /usr/local/var/homebrew/linked/awscli)

Jonathans-MacBook-Air:~ johni$ brew upgrade awscli
Error: No such file or directory - (../../../Cellar/awscli/1.10.28, /usr/local/var/homebrew/linked/awscli)
Error: No such file or directory - (../../../Cellar/awscli/1.10.28, /usr/local/var/homebrew/linked/awscli)
```

**Comment by zmwangx** [comment]
Please run `brew update --debug` twice and report your findings.

**Comment by johnib** [comment]
`brew update --debug`:

http://pastebin.com/6dUf3NXM

**Comment by zmwangx** [comment]
If I'm not mistaken, that's not twice right?

**Comment by johnib** [comment]
@zmwangx what do you mean by "twice" ? the command had run once.

**Comment by zmwangx** [comment]
My theory was if you run `brew update --debug` followed by another `brew update --debug` the problem should resolve itself.

**Comment by zmwangx** [comment]
(`--debug` isn't necessary, but if it still doesn't work I want to see what it's doing.)

**Comment by johnib** [comment]
Hmm.. I had actually run it twice. the pastebin contains the logs of the later invocation.

BUT! after executing it again, it works.
That's weird...

**Comment by MikeMcQuaid** [comment]
Sorry for the pain, glad it works.

**Comment by zmwangx** [comment]
We pushed the fix only a few minutes ago.
