### ISSUE TITLE
all brew commands failing with 'No such file or directory' and giving a relative path

### ISSUE THREAD

**Issue by eadsjr** [Homebrew/brew#999]
### general troubleshooting steps:

OS Version:
      OS X El Capitan v10.11.6

- [x] Ran `brew update` and retried your prior step?  
        fails with error
       attempted to update via git directly, reported already up to date  
      on commit: eb23a397013622025dc3b64dda782a9a9cdea4cf
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?  
         fails with error

### Bug reports:

Brew got into a bad state somehow. All commands other then `brew help` failed with the the following message:

Error: No such file or directory - (../../../Cellar/ffmpeg/3.1.2, /usr/local/var/homebrew/linked/ffmpeg)

It prints twice on a call to `brew upgrade`

Particular event leading to this unidentified. `ffmpeg` was installed normally and working before.

### Followup:

After reinstalling as follows:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Commands work again, but all packages must be reinstalled.

**Comment by MikeMcQuaid** [comment]
There's been several commits since then if you rerun `brew update`. This was fixed in https://github.com/Homebrew/brew/commit/295e937f270826aef4e64f0056950a948e3502b1. Sorry!

**Comment by ehwest** [comment]
brew errors on all packages (on a MAC OSX)
TWI-2:~ ehwest$ brew --version
Homebrew 1.3.7
Homebrew/homebrew-core (git revision 3106; last commit 2017-11-17)
TWI-2:~ ehwest$ brew install node
==> Installing dependencies for node: icu4c
==> Installing node dependency: icu4c
Error: Not a directory @ rb_sysopen - /tmp/github_api_headers20171117-30360-1sliz12
